### ISSUE TITLE
quasar cli not passing extra parameters to electron

### ISSUE THREAD

**Issue by umonaca** [quasarframework/quasar#10002]
When I was following instructions on https://quasar.dev/quasar-cli/developing-electron-apps/preparation I got stuck in this problem for hours. I was trying to do the following:  
```
quasar dev -m electron -- --remote-debugging-port=9222
```
But the `--remote-debugging-port=9222` was never passed to electron.  
At first I was thinking that it was a bug in Quasar CLI, but after hours of debugging, in the end I found out the cause of the problem: I was using Windows Powershell, and [double hypen must be escaped](https://stackoverflow.com/questions/15780174/powershell-command-line-parameters-and) in Powershell.

**Suggestion**:
Because the default terminal in VSCode on Windows is Powershell, I think you should add one or two lines in your document saying that
```
if you are using Powershell, you must escape the double hypen.
```
And add an example like the following:
```
quasar dev -m electron '--' --remote-debugging-port=9222
```

**Comment by rstoenescu** [comment]
Thank you for opening this ticket.
Updated Qv2 docs and q/app.
