### ISSUE TITLE
in Uploader missed filename.

### ISSUE THREAD

**Issue by pepelazz** [quasarframework/quasar#10018]
**Describe the bug**
in Uploader missed filename as key in map. (undefined)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pepelazz/pen/MWmexLm?editors=101

**To Reproduce**
1. select file
2. click upload
3. open console XHR

**Expected behavior**
filename not undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/3218281/125082480-ef258e00-e0cf-11eb-97e4-b5eda6567178.png)

in v1 filename as key
![image](https://user-images.githubusercontent.com/3218281/125082578-111f1080-e0d0-11eb-8aee-8235f89b1823.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.3.
