### ISSUE TITLE
Updating Quasar Framework...

### ISSUE THREAD

**Issue by WCN-llc** [quasarframework/quasar#10016]
**Describe the bug**
I don't understand how the update works

1. Windows PowerShell: quasar --version -> 1.1.3 (As I understand it, this is global)
2. Message: Update available 1.1.3 → 1.2.1,  Run npm i -g @quasar/cli to update.
3. I run the command: npm i -g @quasar/cli - Download and update in progress.
4. Checking the updated version: quasar --version - but nothing has changed! -> 1.1.3

I try to check not globally, but in the project.
I launch the terminal.

And here I am generally confused, because it shows completely different numbers.

Quasar CLI · Gathering information with yarn...
 quasar: 2.0.1 → 2.0.2
 @quasar/app: 3.0.1 → 3.0.2

What should I think?

**Comment by WCN-llc** [comment]
This recommendation led me to the error: npm i -g @quasar/cli - Therefore, it was not updated.
We need this command: yarn global add @quasar/cli - now updated

**Comment by metalsadman** [comment]
Please ask questions in our [discussions](https://github.com/quasarframework/quasar/discussions) section next time. Thanks
