### ISSUE TITLE
Quasar bex non-JS module files deprecated. for production

### ISSUE THREAD

**Issue by keinagae** [quasarframework/quasar#10020]
**Describe the bug**
I have created a demo extension with quasar it work in dev but when i create its production build it says non-JS module files deprecated. when i try to add iframe on web page which will have extension

**Platform (please complete the following information):**
Quasar Version: 3
@quasar/app Version: 2

Quasar mode:
  - [X] BEX
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor

Tested on:
  - [X] BEX
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor

OS:
Node:
NPM:
Yarn:
Browsers: x
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
This should be fixed some q/app versions ago.
Please reopen/comment if it's not.
