### ISSUE TITLE
Prop 'mask' of q-input does not work

### ISSUE THREAD

**Issue by tequila99** [quasarframework/quasar#10031]
**Describe the bug**
Prop 'mask' of q-input does not work in Quasar ver  1.15.22. I don't have this issue in Quasar ver 1.15.21

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tequila99/pen/abWmmaM

**To Reproduce**
Try to input something that don't match the mask

**Expected behavior**
The result must match the mask

**Screenshots**
![image](https://user-images.githubusercontent.com/57666402/125158185-fc965300-e177-11eb-9972-b67b9ca0f39c.png)

**Platform (please complete the following information):**
Quasar Version: 1.15.22

**Additional context**
https://codepen.io/tequila99/pen/gOWwLpW
Example q-input with prop 'mask' for Quasar ver 1.15.21

And all examples on https://v1.quasar.dev/vue-components/input#mask have this issue

**Comment by codenamezjames** [comment]
Can confirm. 
If i drop the version of quasar its working just fine.
https://codepen.io/jamesdonaldharrington/pen/eYWBmdG?editors=101

**Comment by yosa** [comment]
I also have the problem, down to version 21.

**Comment by dorcilio** [comment]
I have the same problem

**Comment by obi84** [comment]
Same Problem. Please fix this!
It doesn't even work in the docs page.

**Comment by dannykhoo** [comment]
Same problem here

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.23.
