### ISSUE TITLE
[request] FAB Multi Direction

### ISSUE THREAD

**Issue by sandman18** [quasarframework/quasar#1004]
It would be great to have a  little more flexibility  around the direction of the FAB and FABactions.  For instance if I wanted to have the fab actions pop out in a circle around the button, or one up, one down, and two left.  Perhaps the prop would have to be placed on the action rather than the button itself.

**Comment by MadeMyDay** [comment]
Nested Fabs also would be awesome (first opens up, nested opens left for example). Currently not working.

**Comment by rstoenescu** [comment]
Welcoming a PR, although I would prefer not to bloat FABs with custom behavior. This would better be done as a Quasar plugin, so closing for now.
