### ISSUE TITLE
Trailing comma in quasar import statement results in build failure

### ISSUE THREAD

**Issue by tvkit** [quasarframework/quasar#10049]
**Describe the bug**
A trailing comma in a quasar import statement results in build failure.

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/tvkit/quasar-comma-bug

**To Reproduce**
clone, yarn, and run **quasar dev**

**Expected behavior**
successful build

**Screenshots**
![image](https://user-images.githubusercontent.com/28468364/125212548-29339300-e27c-11eb-8086-2c48cea729ec.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.2
@quasar/app Version: 3.0.2

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: 12.22.1
NPM: 6.14.12
Yarn: 1.22.5
Browsers: n/a
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**

A new quasar-generated project was created to demonstrate the behavior.

This results in failure:
`import { QTable, useQuasar, } from 'quasar';`

This does not:
`import { QTable, useQuasar } from 'quasar';`

A pesky vs-code extension insisted on the trailing comma. I've since removed the extension.

**Comment by hawkeye64** [comment]
This would be a result of whatever linter you are using and how the rules are set up.

**Comment by tvkit** [comment]
@hawkeye64 

Not a linter violation, but a compilation failure.

The issue is likely caused by an empty identifier on the following comma split:
https://github.com/quasarframework/quasar/blob/78df1f4939936fdbf591d90addf950a8f42e665b/app/lib/webpack/loader.js.transform-quasar-imports.js#L9

**Comment by hawkeye64** [comment]
@tvkit Good catch, since trailing commas are legal and quite common in JavaScript.

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v3.1.7.
This does not happen for non-TS though.
