### ISSUE TITLE
Editor runCmd doesn't work

### ISSUE THREAD

**Issue by Dokinz** [quasarframework/quasar#10050]
**To Reproduce**
https://quasar.dev/vue-components/editor#example--using-toolbar-slots

**Expected behavior**
https://v1.quasar.dev/vue-components/editor#example--using-toolbar-slots

**Comment by hawkeye64** [comment]
INFO:
From "token" select Email
![image](https://user-images.githubusercontent.com/10262924/125324387-19a85e80-e2fd-11eb-84ba-fea97847cc31.png)

Console:
![image](https://user-images.githubusercontent.com/10262924/125324427-23ca5d00-e2fd-11eb-8050-98389beab858.png)

![image](https://user-images.githubusercontent.com/10262924/125324541-40ff2b80-e2fd-11eb-8245-150021af3f08.png)

ToolbarSlot.vue
![image](https://user-images.githubusercontent.com/10262924/125324835-87548a80-e2fd-11eb-9418-bdc908142d73.png)

**Comment by hawkeye64** [comment]
I'll put together a PR for this.

**Comment by hawkeye64** [comment]
Replaced `ref="token"` with `ref="tokenRef"`

**Comment by rstoenescu** [comment]
Will be available in docs on next deployment.

**Comment by Dokinz** [comment]
Still not working.
`ref="token"` is not the only problem.

**Comment by hawkeye64** [comment]
@Dokinz Yep, you're right
![image](https://user-images.githubusercontent.com/10262924/126635737-28897ecd-3dbd-481b-90e2-d7c99f81a6d5.png)

**Comment by hawkeye64** [comment]
@pdanpdan Can you take a moment to look into this?
