### ISSUE TITLE
Feature request: Open method to context menu component

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar#1006]
Currently context menu have only close() method, it will be good if you can trigger open and pass coordinates

**Comment by rstoenescu** [comment]
Hi,

What would be the benefit? This component is supposed to be triggered by a user action (right-click).

**Comment by rstoenescu** [comment]
Please reopen with a use case. Thanks!

**Comment by MatanYed** [comment]
@rstoenescu I have a page with 30(or more) elements and every element should have the same context menu component inside the element. I want to make it smarter, I will use 1 context menu and I will trigger open() method with exactly x and y coordinates

**Comment by rstoenescu** [comment]
You can group those in an element and put the context menu as a direct descendent of that wrapper element. Or is your situation more complex?

**Comment by MatanYed** [comment]
It's more complex. Anyway it will helpful to have this method
