### ISSUE TITLE
Action sheet bug

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1007]
### Software version

 Quasar CLI v0.6.4
 App running on Quasar v0.14.5
Browsers: Chrome

### What did you get as the error?
> vue.runtime.esm.js?ff9b:3034 Uncaught TypeError: Cannot read property 'active' of undefined
    at VueComponent.opened (quasar.esm.js?8bfb:12482)
    at Watcher.get (vue.runtime.esm.js?ff9b:3029)
    at Watcher.evaluate (vue.runtime.esm.js?ff9b:3136)
    at VueComponent.computedGetter [as opened] (vue.runtime.esm.js?ff9b:3421)
    at VueComponent.close (quasar.esm.js?8bfb:12492)
    at Proxy.boundFn (vue.runtime.esm.js?ff9b:186)
    at click (quasar.esm.js?8bfb:12457)
    at invoker (vue.runtime.esm.js?ff9b:1933)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.runtime.esm.js?ff9b:1768)

### What steps did you take, to get the error?
Open the Action sheet once. Choose an option.
Open it a second time. and it bugs.

Here's my action sheet:

```Javascript
chooseLanguageMobile()
{
	ActionSheet.create({
		title: this.get.text.settings.language,
		actions: [
			{
				label: 'English',
				handler: () => { store.dispatch('setLanguage', 'en') }
			},
			{
				label: '日本語',
				handler: () => { store.dispatch('setLanguage', 'ja') }
			},
		],
		dismiss: { // label is used only for iOS theme
			label: 'Cancel',
			handler: () => {  }
		}
	})
},
```

**Comment by mesqueeb** [comment]
The error seems to be pointing here:
```
  computed: {
    opened: function opened () {
      return this.$refs.dialog.active
    },
    contentCss: function contentCss () {
      if (this.$q.theme === 'ios') {
        return {backgroundColor: 'transparent'}
      }
    }
```

**Comment by rstoenescu** [comment]
Available in v0.14.6 (just released it).

**Comment by mesqueeb** [comment]
Thank you so much!
I tried today debugging through the framework but couldn’t find it. Will be interested to see what has changed.

**Comment by pure-zero** [comment]
This issue is also occurring for me on 0.13.10, are there any workarounds I can use?
