### ISSUE TITLE
Button Dropdown props mismatch

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#10079]
**Describe the bug**
If Button dropdown has prop `split` and `unelevated`, shadows never removed `split` prop has some bug.
If Button dropdown has prop `split` and `outline`, split border removed. I think it shouldn't remove the split line.

**Platform (please complete the following information):**
Quasar Version: 2.0.2
@quasar/app Version: 3.0.2

**Additional context**
In this case, the shadow can remove with `no-shadow` class but I think to prop `unelevated` should work great.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.3.
