### ISSUE TITLE
QMenu: error occurred when auto closing QMenu written in <script setup>

### ISSUE THREAD

**Issue by xuzuodong** [quasarframework/quasar#10084]
**Describe the bug**
when clicking a list item in an auto closing QMenu written in <script setup>, error occurs. 

<img width="976" alt="image" src="https://user-images.githubusercontent.com/51878637/125750208-7fc358da-0f5b-493d-b564-3ba1055e02c9.png">

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/nervous-swanson-j4yhh?file=/src/views/Home.vue

**To Reproduce**
1. goto src/views/Home.vue 
2. click "OPEN" in browser
3. click a list item
4. check console
5. if use "non script setup" style code like in line 27 - 29, this error won't occur.

**Expected behavior**
This error doesn't occur.

**Platform (please complete the following information):**
Quasar Version: @latest
@quasar/app Version: @latest

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Should be fixed, at least in v2.2.0 (don't know the exact version where I pushed a fix related to this).
