### ISSUE TITLE
[bug] -webkit-transform causes intermittent screen flash

### ISSUE THREAD

**Issue by alexandesigner** [quasarframework/quasar#1009]
### Software version

Quasar: 0.15.0
OS: Mac OSX
Node: 8.6.0
Browsers: Chrome

### What did you get as the error?

See bug reported https://bugs.chromium.org/p/chromium/issues/detail?id=87512

I noticed that in chrome this behavior is happening in almost all modal-content transitions..

### What were you expecting?

Not flash

### What steps did you take, to get the error?

Open a simple modal with buttons "ripple"

### Solution is

```
.modal-content
   -webkit-backface-visibility hidden
```

See [PR](https://github.com/quasarframework/quasar/pull/1008) to fixes

**Comment by rstoenescu** [comment]
PR merged. Thanks for also providing a solution!

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.7
