### ISSUE TITLE
QDialog pluging doesn't show properly when maximized property is set

### ISSUE THREAD

**Issue by lugrinder** [quasarframework/quasar#10097]
**Describe the bug**
When a QDialog is shown with the maximized property set to true, the buttons are not shown at the bottom of the dialog and if it has many radio/checkbox/toggle, these don't fill the dialog.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Lugrinder/pen/vYmmOQY?editors=1010

**To Reproduce**
1. Go to codepen example
2. Click on any of the three example buttons
3. See error

**Expected behavior**
Dialog buttons rendered at the bottom of the dialog and the items (radio/checkbox/toggle) fill dialog up to buttons. Maximized is a nice feature for small screen devices.

**Platform (please complete the following information):**
Quasar Version: 2.0.2
@quasar/app Version:  3.0.2

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows
Node: 12.22.1
NPM: 6.14.12
Yarn:
Browsers: Firefox 89
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Play with `.q-dialog-plugin__form` CSS definition.
Dialog plugin is not meant to work in maximized mode.
