### ISSUE TITLE
[SSR] CSS module generated classes are undefined on the server, only show up after client hydration

### ISSUE THREAD

**Issue by vladcosorg** [quasarframework/quasar#10103]
**Describe the bug**
The server returns the markup without generated CSS Module classes.
The classes show up after you force the rerendering of the component on client.

**Codepen/jsFiddle/Codesandbox (required)**
Unable to use SSR there

**To Reproduce**
0. Install the standard project `quasar create`...
1. Go to 'src/pages/Index.vue'
2. Create a css module class
3. Assign that class to a component
4. Start the dev server in SSR mode and load the page

**Expected behavior**
The generated css class is present in the server-generated code

**Screenshots**
https://user-images.githubusercontent.com/467230/126049027-9dad87b2-ec23-43dc-b575-684ab24f82a9.mp4

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Macos
Node: 14
NPM:
Yarn:
Browsers: All
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Track it on the source
https://github.com/vuejs/vue-loader/issues/1759

**Comment by vladcosorg** [comment]
@pdanpdan It says there about **Critical** CSS, not a word about CSS **modules**, are you sure that is correct issue? 
Just making sure, no offence :)

**Comment by pdanpdan** [comment]
The Todo look like it is after the if for modules/not modules, so it should be that issue. Anyway, it's not from quasar.

**Comment by vladcosorg** [comment]
K thx!
