### ISSUE TITLE
QInfiniteScroll with props reverse don't scroll to bottom

### ISSUE THREAD

**Issue by MaYoRr** [quasarframework/quasar#10116]
QInfiniteScroll with props reverse don't scroll to bottom

![image](https://user-images.githubusercontent.com/49597310/126165551-e9b991c7-31fc-40aa-82ea-8097dae77b19.png)

![image](https://user-images.githubusercontent.com/49597310/126165624-eaf99f14-0341-4fa8-9ff3-8bf8969a6358.png)

**Comment by pdanpdan** [comment]
I suppose you should move the send messages outside the scroll, else it will cover the bottom.
