### ISSUE TITLE
Race conditions with closing Dialogs

### ISSUE THREAD

**Issue by aandr** [quasarframework/quasar#1012]
### Software version

Quasar: 0.14.6
OS: Mac OS 10.12.6
Node: 8.7.0
NPM: 5.4.2
Browsers: Chrome 61
iOS: Not tested
Android: Not tested
Any other software related to your bug:

### What did you get as the error?

- Issue 1: Dialog won't close if `close()` is called very soon after creating it. 
- Issue 2: If two dialogs are open, the topmost will always be closed first.

As context, I am using dialogs to show the progress of a long running operation. However, in some situations, the operation actually runs really quickly, which made the above race conditions apparent.

### What were you expecting?

- Issue 1: Programmatically closing a dialog shortly after opening should work.
- Issue 2: If two dialogs are open, closing the correct one should work.

### What steps did you take, to get the error?

- Issue 1:

```javascript
let dialog1 = Dialog.create({title: 'Please wait', progress: {indeterminate: true}})
/* quick (<10ms) operation*/
dialog1.close()

let dialog2 = Dialog.create({title: 'Success', message: 'Here are the results'})
```

After clicking OK on `dialog2`, `dialog1` will still be open.

- Issue 2: As an attempted workaround, I put `dialog1.close()` in a timeout. However, this lead to a second bug.

```javascript
let dialog1 = Dialog.create({title: 'Please wait', progress: {indeterminate: true}})

setTimeout(dialog1.close, 1000)

let dialog2 = Dialog.create({title: 'Success', message: 'Here are the results'})
```

After 1 second, `dialog2` will close instead of `dialog1`.

**Comment by rstoenescu** [comment]
Pass a callback to `close()` method to open subsequent Dialogs.

```js
const dialog1 = Dialog.create({title: 'Please wait', progress: {indeterminate: true}})
dialog1.close(() => {
  Dialog.create({title: 'Success', message: 'Here are the results'})
})
```
