### ISSUE TITLE
Scroll bar appears with devicePixelRatio = 1.25

### ISSUE THREAD

**Issue by vneznaikin** [quasarframework/quasar#10120]
With devicePixelRatio = 1.25 (recommended for many displays in Windows 10), the "min-height" of the **main** and **div.q-layout** tags is calculated by one pixel longer. The scroll bar appears!

**To Reproduce**
1. Go to Windows display settings and in "Scale and layout" change to 125%
2. Open https://quasar.dev/layout-builder

**Comment by hawkeye64** [comment]
@vneznaikin This is expected when working with fractional amounts.
Also, it's recommended for screens with higher resolutions, regardless of OS.

**Comment by vneznaikin** [comment]
why still not fixed?

**Comment by hawkeye64** [comment]
Duplicate: https://github.com/quasarframework/quasar/issues/11169

**Comment by rstoenescu** [comment]
Fixed it in Quasar v2.4.4 & v1.17.1 (to be released)

**Comment by yureckey** [comment]
Not sure should I post a new bug report or it's a continuation of this one.
I've spent quite some time trying to figure out why on Chrome browser on a brand new blank project I see a scrollbar and 1-pixel wide bar near footer.
It is gone when I changed the windows10-recommended scale from 125% to 100% (but it's quite uncomfortable for eyes now)
here is codesandbox (but there is really nothing besides auto generated code with added footer and background color)
https://mdn7e.sse.codesandbox.io/
https://codesandbox.io/s/condescending-elbakyan-mdn7e?file=/src/layouts/MainLayout.vue

**Comment by pdanpdan** [comment]
I've reopened - https://mdn7e.sse.codesandbox.io/ reproduces it even with HiDPI 100% but a browser zoom of 125% on linux Chrome

**Comment by yureckey** [comment]
> I've reopened - https://mdn7e.sse.codesandbox.io/ reproduces it even with HiDPI 100% but a browser zoom of 125% on linux Chrome

yes, on windows10 Chrome with browser zoom 125% I see scrollbar and 1-pixel bar. with browser zoom 110% I see only 1-pixel bar, no scrollbar. But I wasn't sure if browser zoom level differences in look are considered as bugs

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.5.0 and v1.18.0
