### ISSUE TITLE
 import QInlineDatetime from './QInlineDatetime' not found

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#1013]
QInlineDatetime.vue file does not exist in dev repo.
datetime/index.js

**Comment by rstoenescu** [comment]
Can you be more specific pls? I see the demo on doc website working, checked source code and everything seems ok. Is this v0.14 or future v0.15 related?

**Comment by codingfriend1** [comment]
In this folder there is no file named QInlineDatetime.vue:

https://github.com/quasarframework/quasar/tree/dev/src/components/datetime

which is required by

https://github.com/quasarframework/quasar/blob/dev/src/components/datetime/index.js

This was changed when you started separating the mat and ios themes into separate builds.

**Comment by rstoenescu** [comment]
Yes, webpack autofills with .mat.vue or .ios.vue extension. Look at webpack config.
