### ISSUE TITLE
Plugins are not working in quasar cli

### ISSUE THREAD

**Issue by kwarnkham** [quasarframework/quasar#10148]
**Describe the bug**
Adding plugins according docs via quasar.conf.js is not working

**To Reproduce**
1. create quasar project with quasar cli
2. install plugins via quasar.conf.js (I've tried "Loading" and "Notify")
3. either $q from useQuasar() or this.$q is not injected with the plugins installed
4. for "Loading", I've got "TypeError: Cannot read property 'show' of undefined"

**Expected behavior**
Plugins are injected into $q

**Screenshots**
<img width="542" alt="Screen Shot 2021-07-21 at 19 19 41" src="https://user-images.githubusercontent.com/31079306/126491121-50c85b70-45d6-4ec5-b961-e1e36341dfc4.png">

<img width="659" alt="Screen Shot 2021-07-21 at 19 22 54" src="https://user-images.githubusercontent.com/31079306/126491628-96779bad-fab3-486d-b613-82064ee933ff.png">

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: ^3.0.0

Quasar mode:
  - [x] SPA

Tested on:
  - [x] SPA

**Comment by hawkeye64** [comment]
Did you restart `quasar dev` after adding plugins to quasar.conf.js?

**Comment by kwarnkham** [comment]
> Did you restart `quasar dev` after adding plugins to quasar.conf.js?

Yes, I even `quasar clean` before `quasar dev`

**Comment by kwarnkham** [comment]
I try again today, turns out it's ok.
