### ISSUE TITLE
[docs] vuex with typescript

### ISSUE THREAD

**Issue by MaYoRr** [quasarframework/quasar#10146]
I enabled TS support, now I have a problem with vuex
`Property '$store' does not exist on type '{ messages(): any; load_more_url(): string; allow_get_more_messages(): boolean; messages_size(): number; user(): object; chain_
id(): number; }'.
`

**Comment by IlCallo** [comment]
Vuex usage with TS is known to be painful, we try to ease the integration but making them work fine together is something outside Quasar scope I'm afraid
Pinia has better TS support, as it will have Vuex5 (which will be based on Pinia)
