### ISSUE TITLE
QSelect - styling with [input-class] is not working

### ISSUE THREAD

**Issue by MuhammadFayed** [quasarframework/quasar#10166]
**Describe the bug**
The property **"input-class"** is not getting applied for **QSelect** 

**Codepen (required)**
[Demo Link](https://codepen.io/muhammadfayed-the-sans/pen/XWRePvW?editors=1010)

**Platform (please complete the following information):**
Quasar Version: v2.0.2
@quasar/app Version: v3.0.2

**Comment by MilosPaunovic** [comment]
Add `use-input` prop for it to work.

**Comment by MuhammadFayed** [comment]
Thanks, that did the trick
