### ISSUE TITLE
Multiple QSelect doesn't close on touch screen

### ISSUE THREAD

**Issue by igorgo** [quasarframework/quasar#1016]
### Software version

Quasar: 0.14.6
OS: Win10
Node: 8.6.0
NPM: 5.3.0
Browsers: Chrome
iOS: -
Android: 7.1.1
Any other software related to your bug:

### What did you get as the error?
On touch screen devices the option list of the `QSelect` with the `multiple` property closes and opens again after tap on the control.
### What were you expecting?
The option list of the `QSelect` must close after tap on its control, as well as it closes after mouse click.
### What steps did you take, to get the error?
1. On a touch screen, tap on `QSelect` with the `multiple` property.
2. Select one or more options.
3. Tap on `QSelect` again to close the options.
 - List hides and appears again.

(There is #924, but it's not about the multiple selection, and I could not reproduce it)

**Comment by rstoenescu** [comment]
Fixed in future v0.15
