### ISSUE TITLE
Empty .gz files with gzip option

### ISSUE THREAD

**Issue by slegrand-cpam45** [quasarframework/quasar#10161]
Files named `.gz` are generated if the `gzip` option is set to true in `quasar.conf.js`. The bug seems similar to #8064.

1. Create a new project
2. Set `gzip: true` in `quasar.conf.js`
3. Build the project
4. Empty `.gz` files are generated in build directories like `js` or `css`

**Expected behavior**
Compressed files should be generated. 

**Platform (please complete the following information):**
@quasar/cli: 1.2.1
quasar: 2.0.3
@quasar/app: 3.0.3
@quasar/extras: 1.10.8
webpack: 5.45.1
webpack-dev-server: 4.0.0-beta.3

Quasar mode:
  - SPA

Tested on:
  - SPA

OS: Windows NT v10
Node: 14.17.0
NPM: 6.14.13
Yarn: 1.22.10

**Additional context**
On my current Quasar project, i get the following error if i try to build it with the `gzip` option:
`Conflict: Multiple assets emit different content to the same filename js/.gz`

**Comment by miladmeidanshahi** [comment]
same issue.

**Comment by youmax210139** [comment]
try this in quasar.conf.js
```json
gzip: {
  filename: "[path][base].gz",
}
````

**Comment by slegrand-cpam45** [comment]
Indeed, this configuration line fixes the problem. Thank you! Does that mean the default config file should be modified to include this line?

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v3.1.3
