### ISSUE TITLE
q-stepper inside q-stepper

### ISSUE THREAD

**Issue by alainrc2005** [quasarframework/quasar#10191]
q-stepper inside q-stepper inherit contracted mode
Thanks

**Comment by pdanpdan** [comment]
please add a codepen to reproduce the problem

**Comment by alainrc2005** [comment]
[CodePen](https://codepen.io/alainrc2005/pen/MWmQwVx?editors=1000)

**Comment by rstoenescu** [comment]
Fix will be available in next Qv2 and Qv1 versions.
