### ISSUE TITLE
[Bug] Alert ignoring initial v-model value.

### ISSUE THREAD

**Issue by SeregPie** [quasarframework/quasar#1019]
Hello.

Just a small bug, but it is annoying. Alert, Modal etc. are visible/invisible per default at the beginning, ignoring initial `value` of `v-model` and changes their visibility only on the next `value` change.

There should be default value for `value`.

```js

value: {type: Boolean, default: true} // alert
value: {type: Boolean, default: false} // modal

```

And then there are 2 ways to fix it.

1) [QAlert.vue#L86](https://github.com/quasarframework/quasar/blob/3343c0b899204b3b158b8421bb333151abe856cf/src/components/alert/QAlert.vue#L86): init `active` in `data` function

```js

data() {
  return {active: this.value};
}

```

2) [QAlert.vue#L90](https://github.com/quasarframework/quasar/blob/3343c0b899204b3b158b8421bb333151abe856cf/src/components/alert/QAlert.vue#L90): immediate `value` watcher

```js

value: {
  handler(v) { ... },
  immediate: true,
}

```

**Comment by rstoenescu** [comment]
Can't see this issue with Modal.

Fix for Alert available in edge and future v0.14.7.
