### ISSUE TITLE
Q-input props conflicts: maxlength with type

### ISSUE THREAD

**Issue by nikober** [quasarframework/quasar#10194]
**Describe the bug**
Q-input props conflicts: maxlength with type

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/nikober/pen/gOWooPO

**To Reproduce**
1. Try check maxlength in q-input

**Expected behavior**
Maxlength is worked

**Platform (please complete the following information):**
Quasar Version: 1.14.2

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:  macOs Big Sur 11.2.3
Node: 14.15.1
NPM: 6.14.8
Browsers: Google Chrome
![image](https://user-images.githubusercontent.com/37027566/126944287-7ac10ba5-5e97-4d5a-b9e8-8cd5e2c282f1.png)

**Comment by pdanpdan** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefmaxlength
