### ISSUE TITLE
Fiddle, JSbin etc example for easily logging bugs

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#102]
Logging this bug here so I won't forget.

**Comment by mariaczi** [comment]
+1 . 
Definitely would be beneficial!

**Comment by murbanowicz** [comment]
http://www.webpackbin.com looks like good place for that!

**Comment by smolinari** [comment]
I know this would mean extra work, but a "quasarbin" or a "quasar-fiddle" specially built with and for quasar would be even cooler. Is that what you meant Razvan? Or did you want to use a third party as suggested?

Scott

**Comment by rstoenescu** [comment]
Got a third party in my mind. If time would allow a quasarbin would be a killer to have, although that won't happen too soon. Got A LOT of work items to do before this would see the light of day.

**Comment by smolinari** [comment]
Sure. It is always nice to dream though. :smile: 

Scott

**Comment by rstoenescu** [comment]
Will be available along with v0.15 release. Thank you for your patience!

**Comment by JCharante** [comment]
Really? Oh my god that's great!
