### ISSUE TITLE
Suppress Q-Select menu from appearing upon validation

### ISSUE THREAD

**Issue by TheQuail13** [quasarframework/quasar#10202]
**Is your feature request related to a problem? Please describe.**
I've spent a couple hours researching this but I haven't found a way of suppressing a q-select's menu from appearing when either its form or the field itself has internal validation run. As an example, imagine a form with multiple "required" q-select fields. When the user validates those fields and they fail, then a menu will appear for each one prompting the user to select a choice. Depending on the length and quantity of these menus, half the screen can be consumed or if on a mobile screen, would force a user to make a selection or cancel the menu before they are able to return to the base screen.

**Describe the solution you'd like**
A prop on the q-select component that gives the option to suppress the menu from appearing on form/field validation would be the most ideal. Given the user feedback I've received, I know that my current web app would greatly benefit from this and would improve the overall UX. If this functionality does not exist or if a full illustration is necessary, I'll add a fiddle to demonstrate the issue as best I can. Or a PR with a potential solution if I have time this week.

**Comment by TheQuail13** [comment]
After digging further, found that the q-form prop "no-error-focus" accomplishes this. Closing.

**Comment by pdanpdan** [comment]
Can you please create a codepen that opens more than one qselect? That would be a bug
