### ISSUE TITLE
uglifyOptions blank page

### ISSUE THREAD

**Issue by thingnoy** [quasarframework/quasar#10201]
**Describe the bug**

**To Reproduce**
1. `quasar.conf.js:`
```
module.exports = function (ctx) {
  return {
  ...
    build: {
    ...
      uglifyOptions: {
        compress: { drop_console: true }
      }
    },
  }
}
```
2. `quasar build`
3. `quasar serve --history dist/spa`
4. See blank page at http://localhost:4000

**Expected behavior**

**Screenshots**
<img width="1612" alt="Screen Shot 2021-07-27 at 00 08 34" src="https://user-images.githubusercontent.com/25950077/127030181-d4e28dd1-3d3c-4e79-8342-80df0f780210.png">

**Platform (please complete the following information):**
Quasar Version: 1.2.1
@quasar/app Version:  2.2.1

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOs 11.5
Node: 14.17.3
NPM: 7.20.1
Browsers: Chrome 91.0.4472.164 (Official Build) (x86_64)

**Additional context**

**Comment by MilosPaunovic** [comment]
Console is clear on your screenshot.

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce...
Are you sure that you've also build > vueRouterMode to 'history' ?
