### ISSUE TITLE
q-table Virtual scrolling and Sticky header/column used together, scrollbar scrolling misaligned

### ISSUE THREAD

**Issue by azhengyongqin** [quasarframework/quasar#10205]
**Describe the bug**
q-table Virtual scrolling and Sticky header/column used together, the vertical scrollbar is misaligned with the mouse slide.

**Codepen**
https://codepen.io/azhengyongqin/pen/KKmQzdo

**Screenshots**
![quasar-table](https://user-images.githubusercontent.com/18138282/127108705-bf432882-e977-43b4-b434-23d86e4a6da8.gif)

**Platform (please complete the following information):**
Quasar Version: ^2.0.3
@quasar/app Version: 2.0.3

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10 19042.1110
Node: v16.4.2
Yarn: 1.22.4
Electron: ^13.0.0

**Comment by pdanpdan** [comment]
They don't look missaligned, it's just that the columns have no width set on them and are rendered based on the content. When you are on the top of the table the numbers are small, later on bottom they are 4 digits long, so the column width changes.
Set widths on columns if you need them to be fixed.

Are we talking about something else?

**Comment by azhengyongqin** [comment]
@pdanpdan 
Oh no!
I mean the vertical scrollbar is misaligned with the mouse slide

**Comment by azhengyongqin** [comment]
@pdanpdan 
Oh no!
I mean the vertical scrollbar is misaligned with the mouse slide

**Comment by pdanpdan** [comment]
Then it must be something with the styles, because it looks like the example in the docs (https://quasar.dev/vue-components/table#example--virtual-scroll-with-sticky-header) is fine.
What I can see on a quick vie is that `:virtual-scroll-sticky-size-start="48"` is missing

**Comment by azhengyongqin** [comment]
@pdanpdan 

It seems that if I add `sitcky-header` and `sitcky-column` to `virtual-scroll` at the same time, there is a misalignment, only `sitcky-header` is normal.

Is this a bug? Or what do I need to do to fix it?

Here is the sass code for `sitcky-column` in the documentation
```sass
.my-sticky-virtscroll-table
  /* height or max-height is important */
  height: 410px
  width: 700px

  .q-table__top,
  .q-table__bottom,
  thead tr:first-child th /* bg color is important for th; just specify one */
    background-color: #fff

  thead tr th
    position: sticky
    z-index: 1
  /* this will be the loading indicator */
  thead tr:last-child th
    /* height of all previous header rows */
    top: 48px
  thead tr:first-child th
    top: 0
  
  
  td:first-child
    /* bg color is important for td; just specify one */
    background-color: #c1f4cd !important
  
  tr:first-child th:first-child
    /* highest z-index */
    z-index: 3

  td:first-child
    z-index: 1

  td:first-child, th:first-child
    position: sticky
    left: 0
```
https://codepen.io/azhengyongqin/pen/NWjyrbJ

**Comment by pdanpdan** [comment]
I think there are some quirks on rendering tables with first column sticky (something about how it evaluates the height of the row if the first td/th is sticky).
As a workaround you can add an empty first column and make the second one sticky
https://codepen.io/pdanpdan/pen/LYyQxZy?editors=0100

**Comment by azhengyongqin** [comment]
@pdanpdan 
hi bro ! 
In fact, my real use case is sticky the header and last column, as in the picture below.
![image](https://user-images.githubusercontent.com/18138282/127144444-292b845a-9ec2-418f-8bfb-0386b3c7d585.png)
But the same bug occurs when I sticky the last column.

https://codepen.io/azhengyongqin/pen/bGWLqeV?editors=0100

**Comment by pdanpdan** [comment]
I'll try to take a look on this, it's strange.

**Comment by Sincenir** [comment]
I think this is a quasar's bug. it may be a problem with the multiplication in the source code. You can try to debug in the source code to find error.

**Comment by pdanpdan** [comment]
I'm sorry but the problem is something related to how Chrome renders the table with sticky - maybe it's related to the new table layout engine.

For the first column I can see no workaround, but for the last column you can use `:nth-child(__number_of_last_column_1_based__)` instead of `:last-child` and it works.

I'll leave this open, but just for checking from time to time if it's fixed.

**Comment by pdanpdan** [comment]
Ok, I discovered the problem: in your CSS you are aplying sticky to th and td but not only scoped to the thead and the main content of the scroll but on all first/last tds - so also to the spacers.

https://codepen.io/pdanpdan/pen/vYmRypG

see the `.q-virtual-scroll__content td:first-child,  thead th:first-child`
