### ISSUE TITLE
Feautures: Enrich CSS Responsive Class

### ISSUE THREAD

**Issue by ukik** [quasarframework/quasar#10214]
Isuggest to Quasar V1 or V2 to have responsive CSS

for example

q-lg-ma-md (give margin to element based on screen viewport 1024px)
q-lg-text-red (give color text to red only based on screen viewport 1024px)
and soon

because at this moment I split each purpose CSS by using 

`<div :class="[ $q.screen.lg ? 'text-red' : 'text-red' ]" />`

above methods super complicated when project is big, as well as performance rendering sometimes getting problems... and for SSR is serious problems

**Comment by pdanpdan** [comment]
Hello. Please use the screen plugin to dynamically generate your class names.

**Comment by AlexAndrascu** [comment]
@pdanpdan I would second that. I am currently trying to get custom derived class names working like bellow: 
```     
<div class="column" v-for="card in cards" :key="card.title">
        <div :class="card.class">
```
I must add that I'm quite new to this framework and also Vue in general but did managed to get it working on other Vue framework. 
Documentation can perhaps be bettered on the screen plugin too. Any help or pointer would be appreciated.
