### ISSUE TITLE
[Vue warn]: Injection "__inputParent" not found     (QAutocomplete)

### ISSUE THREAD

**Issue by tombarfoot** [quasarframework/quasar#1021]
Quasar: v0.14.6
OS: OSx
Node:
NPM:
Browsers: all
iOS:
Android:

I've seen this error reported earlier, but am using the QAutocomplete inside a QInput and have this error.

[Vue warn]: Injection "__inputParent" not found
found in
---> <QAutocomplete>
       <QInputFrame>
         <QInput>
           <QField>
             <QScrollArea>
               <Home> at src/components/Home.vue
                 <QLayout>
                   <Mainlayout> at src/components/MainLayout.vue
                     <App> at src/App.vue
                       <Root>

**Comment by igorgo** [comment]
Please, give a snippet of your template.

**Comment by tombarfoot** [comment]
<div class="col">
            <q-field :helper="departHelper">
              <q-input @keyup="departHelperClear" :debounce="100" float-label="departure" max-length="15" v-model="depart" placeholder="departure">
                <q-autocomplete @search="search" @selected="departureSelected" />
              </q-input>
            </q-field>
          </div>

**Comment by rstoenescu** [comment]
Fix available in edge and future v0.14.7. Thanks for reporting!
