### ISSUE TITLE
QPopupProxy did not work correctlly when a QInput was used as its default slot in SSR mode

### ISSUE THREAD

**Issue by bayegy** [quasarframework/quasar#10218]
**Describe the bug**
QPopupProxy did not work correctlly when a QInput (could also be other component using v-model) was used as its default slot in SSR mode 

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/sad-wiles-shodu?file=/src/pages/Index.vue

**To Reproduce**
1. Click the button, popup showed as expected
2. Click again, popup was closed. Everything works fine for now
3. Click another time and error occurs; popup showed but with empty content

**Expected behavior**
Popup shows with correctly rendered contents no matter how many times toggled

**Platform (please complete the following information):**
Quasar Version: v2.0.2
@quasar/app Version: v3.0.2 

Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.3.0
