### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#10225]
### Discussed in https://github.com/quasarframework/quasar/discussions/10056

<div type='discussions-op-text'>

<sup>Originally posted by **fredericoregateiro** July 12, 2021</sup>
**Describe the bug**
Show a date popup from a dialog.
I really don't know what i'm doing wrong.

The problem is when i open the dialog on this [line](https://github.com/SolRIA/atlanticgrids/blob/b9af53f8b04596dc2c93198a6b91bcf063cf04eb/src/pages/Registed/Projects.vue#L103) and click on the input icon with the date field, to open the date picker.

**Codepen/jsFiddle/Codesandbox (required)**
[Sample](https://github.com/SolRIA/atlanticgrids)

**To Reproduce**
1. Create a dialog with a date picker inside a input control like this [example](https://quasar.dev/vue-components/date#with-qinput)
2. Click on the icon to open the date control
3. On the PC nothing hapens
4. On the mobile this error on the console: 
```
innerRef.value.click is not a function 
handleShow QDialog.js:217
```

**Expected behavior**
Open the date picker with no error

**Platform (please complete the following information):**
Quasar Version: 2.0.2
@quasar/app Version: v3.0.2

Quasar mode:
  - [x] SPA
  
Tested on:
  - [x] SPA

OS:Win10
Browsers: Edge, Firefox

**Additional context**
</div>

**Comment by fredericoregateiro** [comment]
The error only heppens using the iphone simulator, using the devtools.
On any other simulator, the datepicker just doesn't work

![127352687-eba4f943-28d6-40b3-bb75-022460405e9e](https://user-images.githubusercontent.com/6304701/127354560-7adaa1c2-6e70-4347-bdd5-a12cc18003a9.png)

**Comment by fredericoregateiro** [comment]
After a lot of trying, i've found the problem.
I'm importing the icons as svg's, doing this the date picker doesn't work

[codepen exemple](https://codepen.io/regateiro/pen/jOmKaEY)

**Comment by rstoenescu** [comment]
Wrap QIcons with a DIV when you want to place any component/DOM node inside of it. No way around it due to how svg's work.
