### ISSUE TITLE
UMD version doen't add desktop class to a body

### ISSUE THREAD

**Issue by Iworb** [quasarframework/quasar#1024]
Version: current dev branch.
`npm run build` built all versions of css and js files, and **there's no hover behaviour for buttons** in `quasar.mat.css`.
There's no problem in `quasar dev` server, just in the built styles.

**Comment by Iworb** [comment]
It's all about `desktop-only` property. UMD version doesn't add this class to a `body`, so it's acts like mobile version.

**Comment by rstoenescu** [comment]
Let the temporary CDN to update content and it will now work.
