### ISSUE TITLE
QBtn rerenders when switching to/from disabled state

### ISSUE THREAD

**Issue by parker-codes** [quasarframework/quasar#10252]
**Describe the bug**

I am attempting to transition the background and text colors when a QBtn switches to and from the disabled state. My use case is in a form context, to prevent submission until the current step is completed before the user moves on.

I noticed that the element is completely removed from the DOM and recreated when the `disable` prop is changed, which means I can't transition these colors.

---

**Codepen/jsFiddle/Codesandbox (required)**

[Demo of QBtn vs regular `<button>` element](https://codesandbox.io/s/magical-water-lhqxo?file=/src/pages/Index.vue)

---

**To Reproduce**

1. Create a QBtn
2. Conditionally disable it, like `:disable="disabled"`
3. Bind `disabled` to some action, like a checkbox or interval
4. Add styles to transition background and text colors
5. See that the change is immediate
6. Use "break-on" in devtools to see that element is removed and re-added to DOM

---

**Expected behavior**

In order to provide transitions like this, I expect that making a button disabled would simply add the disabled state and not rerender.

---

**Screenshots**

https://user-images.githubusercontent.com/17652149/127715753-155578e3-f79b-4bb8-b896-a7686e9c0707.mov

---

**Platform (please complete the following information):**

Quasar Version: 2+
@quasar/app Version: 3+

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [X] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS
Node: v16.5.0
NPM: v7.19.1
Yarn: v1.22.10
Browsers: Firefox, Chrome

**Comment by rstoenescu** [comment]
The reason for re-rendering was because of Vue architecture forcing us to do so otherwise directives are not detached. And we need this when QBtn is disabled.

But went for an alternative approach since your point is valid.

Improvement will be available in Quasar v2.2.1
