### ISSUE TITLE
q-table break-word on long lines

### ISSUE THREAD

**Issue by fredericoregateiro** [quasarframework/quasar#10250]
**Describe the bug**
When the cell value is too long, should be able to do word break and show the value on several lines

**Codepen/jsFiddle/Codesandbox (required)**
[codepen](https://codepen.io/regateiro/pen/mdmLGbx)

**Expected behavior**
Be able to do a line break by work or letter

**Comment by pdanpdan** [comment]
If you bother to read the docs (QTable API) you'll find `wrap-cells`.

https://codepen.io/pdanpdan/pen/mdmLYYP
