### ISSUE TITLE
Click/Select effect does not disappear automatically

### ISSUE THREAD

**Issue by gilhrpenner** [quasarframework/quasar#10253]
**Describe the bug**
When clicking a checkbox or a toggle, the selection effect does not disappear on mouse up, only when clicking elsewhere.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gpenner/pen/WNjJYxz

**To Reproduce**
1. Go to the codepen
2. Click on either toggle or checkbox

**Expected behavior**
The selection effect should disappear on mouse up, like Quasar v1

**Screenshots**
![image](https://user-images.githubusercontent.com/24423300/127727004-3e1121c2-4dcc-4741-bb8d-dbbb5c35f363.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac OS
Node: 15.3.0
NPM: 
Yarn: 1.22.10
Browsers: Chrome, Safari
iOS:
Android:
Electron: 13.1.6

**Comment by rstoenescu** [comment]
Hi,

This is by design. The component has focus and Quasar follows the accessibility recommendations.
