### ISSUE TITLE
transpiled modules don't get rebuilt anymore

### ISSUE THREAD

**Issue by therealcoder1337** [quasarframework/quasar#10260]
**Describe the bug**
modules (from `node_modules` folder) which are transpiled using `transpileDependencies` and `transpile` options in `quasar.conf.js` were previously watched for changes and if changes to those modules occurred, the quasar app (spa in my case) would rebuild and directly apply the changes. this can be useful, if you want to link your dependency and develop it within a quasar app, e. g. via `npm link my-dependency`. i used this for some years now.
but recently i noticed it doesn't work anymore. there are no errors in the console and the change still appears to be detected. it even looks like it's rebuilding the app (judging by console), but the app never updates the changed part. only restarting the development server (`quasar dev`) helps, or changing some prop in `quasar.conf.js` which triggers the whole app to be rebuilt.
this is a major blocker for any development involving (linked) dependencies. 

**Codepen/jsFiddle/Codesandbox (required)**
i don't think this can be shown on codepen, sorry.

**To Reproduce**
1. create a quasar spa app
2. add a dependency
3. link that dependency to your local project (`npm link my-dependency` in quasar folder)
4. add that dependency to `transpileDependencies` and set `transpile` option to `true` in `quasar.conf.js`
4. `quasar dev`
5. change something in the local project that is used by the quasar app (i tested  with `.vue` files)
6. see that change doesn't get applied

**Expected behavior**
change should be applied, just as if the dependency was a part of the source code

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: linux (someone i know could reproduce the issue in windows)
Node: 16 (also tested 14, no difference)
NPM: 7 (also tested 6 - i believe -, no difference)
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
I also tried downgrading node, which didn't help. I also tried downgrading the two quasar packages to some betas, which didn't help either.
i think this problem is different from the other one, because it only affects modules and i have no console errors. other one: https://github.com/quasarframework/quasar/issues/10083
i also believe this problem isn't directly about linking, because normal (unlinked) dependencies show the same issues when changed.

**Comment by rstoenescu** [comment]
This is an external problem and due to webpack changing its behavior. It's not watching node_module deps anymore.

**Comment by therealcoder1337** [comment]
@rstoenescu but it (mostly) worked with the hotfix i posted here: https://github.com/quasarframework/quasar/issues/10083#issuecomment-897269308
now it doesn't even refresh after f5, how is one supposed to develop a linked module if it doesn't reload?
it also seems that changes to the dependency are still recognized by the cli, because the console output triggeres a "recompile" when i change files of the dependency.

**Comment by rstoenescu** [comment]
Think I found the culprit.
Please retry with "@quasar/app" v3.1.6.

**Comment by therealcoder1337** [comment]
while hmr is not fixed, it now works after f5. good enough to work with. thank you!

**Comment by rstoenescu** [comment]
HMR should work with symlinked deps now. 100%.

Only thing that comes to my mind is you're prolly developing a PWA? In which case: https://quasar.dev/quasar-cli/developing-pwa/hmr-for-dev#introduction
