### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#10263]
I've been using QPopupProxy for QDate and somehow I got it to throw this error:

![image](https://user-images.githubusercontent.com/2260539/127786689-19d6297c-1c9b-467c-ad97-ab3cdb85974b.png)

![image](https://user-images.githubusercontent.com/2260539/127786648-f832c5dc-298e-49e2-8001-66baafbbdbb9.png)

https://github.com/quasarframework/quasar/blob/78df1f4939936fdbf591d90addf950a8f42e665b/ui/src/utils/dom.js#L77

https://github.com/quasarframework/quasar/blob/78df1f4939936fdbf591d90addf950a8f42e665b/ui/src/components/menu/QMenu.js#L308

I think only `null` check is missing (`innerRef` is initialized with `null`). I can submit a PR.

**Comment by hawkeye64** [comment]
@thexeos Please do, thanks!

**Comment by rstoenescu** [comment]
Thanks for PRing!
Fix will be available in Quasar v2.1.1
