### ISSUE TITLE
q-range q-slider min max

### ISSUE THREAD

**Issue by zanzara** [quasarframework/quasar#10276]
**Describe the bug**
`:min` and `:max` properties of `q-range`or `q-slider`  does not match on first render within a `q-popup-edit` component.

**Codepen/jsFiddle/Codesandbox (required)**
```vue
                <q-popup-edit
                  v-if="['LeerlaufdrehzahlVon','LeerlaufdrehzahlBis'].includes(col.name)"
                  v-model="Leerlaufdrehzahl"
                  @before-show="() => Leerlaufdrehzahl = initLeerlaufdrehzahl(props.row.LeerlaufdrehzahlVon,props.row.LeerlaufdrehzahlBis)"
                  @save="(v, i) => updateDrehzahl(v, props.row)"
                  buttons
                >
                <template v-slot:default="scope">
                  <div style="width: 300px;">
                    <q-field
                        class="row fit wrap "
                        stack-label
                        :hint="`${$t('gwsCol.Leerlaufdrehzahl.Label')} ${Leerlaufdrehzahl.min} - ${Leerlaufdrehzahl.max} ${$t(`gwsCol.${col.name}.unit`)}`"
                        dense
                        borderless
                      >
                      <template v-slot:control>
                        <q-slider
                          v-if="fixDrehzahl"
                          v-model="scope.value.min"
                          :min="500"
                          :max="20000"
                          :step="100"
                          label
                          label-always
                          class="q-mt-lg"
                        />
                        <q-range
                          v-else
                          v-model="scope.value" 
                          :min="500"
                          :max="20000"
                          :step="100"
                          label-always
                          class="q-mt-lg"
                          :left-label-value="Leerlaufdrehzahl.min"
                          :right-label-value="Leerlaufdrehzahl.max"
                          />
                          <q-checkbox dense v-model="fixDrehzahl" :label="$t('gwsCol.Leerlaufdrehzahl.fix')"  />               
                      </template>
                    </q-field>
                    </div>
                  </template>
                </q-popup-edit>

```

**To Reproduce**

**Expected behavior**
If I click on the first col/row from the 1st screenshot,  the 3rd pic is rendered which is wrong.
If I escape and click again on the same col/row the 2nd pic is rendered **which is correct**.

**Screenshots**
First: 
![Bildschirmfoto zu 2021-08-03 17-27-04](https://user-images.githubusercontent.com/7381054/128042753-dfbd5caa-d695-4230-b5df-04e27c3fa3ac.png)

Second:
![Bildschirmfoto zu 2021-08-03 17-26-32](https://user-images.githubusercontent.com/7381054/128042776-6bfc6623-8710-4589-b749-37f3fdd854fc.png)

Third:
![Bildschirmfoto zu 2021-08-03 17-26-18](https://user-images.githubusercontent.com/7381054/128042793-d014c216-c78c-427d-aac7-19e6c263bd09.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.4

Quasar mode:
  - [x] SPA

Tested on:
  - [x] SPA

Browsers: chrome

**Additional context**

**Comment by rstoenescu** [comment]
Please create a codepen (https://codepen.quasar.dev) so we can play with it and reproduce your issue.
Thanks.

**Comment by zanzara** [comment]
Unfortunately I cannot reproduce simply this behaviour in a codepen. I create  a small sample, forked from the "QDataTable with QPopupEdit"  and exchanged `q-input` with `q-range` i.e. but there it works fine:
https://codepen.io/zanzara/pen/OJjWwVR?editors=1010

Now weeks ago now,  I  could make a workaround , changing `v-model` and add `@change` event like this:
```vue
                            <q-range
                              v-else
                              @change="(v) => (scope.value = v)"
                              v-model="Leerlaufdrehzahl"
                              :min="gwsConst().LeerlaufdrehzahlMin"
                              :max="gwsConst().LeerlaufdrehzahlMax"
                              :step="100"
                              label-always
                              class="q-mt-lg"
                              :left-label-value="Leerlaufdrehzahl.min"
                              :right-label-value="Leerlaufdrehzahl.max"
                            />

```
With that change it works for me.
I really cannot say where my problem lies.
I'm no Vue Expert and I'm still fighting to really understand "slots" somehow. The docs doesn't help me here.
 
So probably this isn't a bug. You can close or delete this post  therefore. Sorry.
