### ISSUE TITLE
QTable

### ISSUE THREAD

**Issue by rafayeljamalyan** [quasarframework/quasar#10272]
Documentation of QTable says that to fill data in the table I should pass *rows* prop, but it doesn't work. I lost two hours reaching out to the source of the problem, and I wondered why I got an error if I copied all the code from an example. Finally, I found a codepen example where instead of *rows* there was *data*, and that solved my issue. Please fix this bug or change *rows* to *data* in docs.

**Comment by pdanpdan** [comment]
Read the docs for V1 if you use quasar v1

**Comment by rafayeljamalyan** [comment]
@pdanpdan My quasar version is 2.2.3

**Comment by pdanpdan** [comment]
Then it's `:rows`
