### ISSUE TITLE
[q-table] Embedded elements do not synchronize

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#10279]
If use an element with v-model inside q-table, it does not synchronize with its v-model.
Using for example a checkbox instead of string in a row has to allow change the checkbox state but fault.

Code for a column output:
```
 <template v-slot:body="props">
        <q-tr :props="props">
          ...
          <q-td key="calories" :props="props">
            <q-checkbox v-model="props.row.calories" dense v-if="typeof props.row.calories=='boolean'"></q-checkbox> 
            
            <q-badge color="green" v-else>
              {{ props.row.calories }}
            </q-badge>
          </q-td>
        ...
```
So if 'calories' is boolean then the element is a checkbox with the synchronized state. Does not work.

Example
https://codepen.io/Claus1/pen/eYWjxmz?editors=1011
**To Reproduce**
1. Go to https://codepen.io/Claus1/pen/eYWjxmz?editors=1011
2. Click on any checkbox 
3. See error.

**Expected behavior**
Has to change the state when click on the checkbox

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
2.0.3

Quasar mode:
  - [x ] SPA

Tested on:
  - [x ] SPA
  
OS: Linux
Node: Any
NPM: Any
Yarn: Any
Browsers: Chrome

**Comment by pdanpdan** [comment]
rows is not reactive, please read vue3 manual first

**Comment by Claus1** [comment]
@pdanpdan Is it possible to avoid or better rewrite q-table from scratch?

**Comment by pdanpdan** [comment]
Your row is not reactive

**Comment by Claus1** [comment]
Thanks for helping! I made isolated rows in custom component in data section.  

```
<template lang="pug">
q-table(:title='name' :rows='rows' :columns='columns' dense row-key="iiid")    
  template(v-slot:top-right)    
    template(v-slot:body='props')
    q-tr(:props='props')
      q-td(v-for="col in data['headers']" :key='col' :props='props')
        q-checkbox(v-model="props.row[col]" dense @click="change(props.row.iiid, col, props.row)" v-if="typeof props.row[col]=='boolean'")     
        div(v-else) {{  props.row[col]}}
</template>
...
export default defineComponent({
  name: 'utable',
  data(){
    return {
      rows : this.rows_(),
      value: true,
      search: ''
    }
  },
...
```
Now rows and row are reactive but the q-table is not updated anyway. 

![1row](https://user-images.githubusercontent.com/1247062/128133988-6a6f36f6-93d9-4473-9d3b-57697bf88d11.png)

**Comment by pdanpdan** [comment]
Please update the codepen so we can take a look

**Comment by Claus1** [comment]
I found a reason and it is terrible. For rows I used Map(s), not pure Object(s). With Map no reactivity.
