### ISSUE TITLE
Extension(@quasar/qpdfviewer): is not compatible with @quasar/app v3.0.3. Required version: ^1.0.0 || ^2.0.0

### ISSUE THREAD

**Issue by zhengbowen1698** [quasarframework/quasar#10280]
Extension(@quasar/qpdfviewer): is not compatible with @quasar/app v3.0.3. Required version: ^1.0.0 || ^2.0.0

**Comment by pdanpdan** [comment]
Please open issues on the correct repo if you want to open an issue for something so obvious.

**Comment by hawkeye64** [comment]
@zhengbowen1698 
Released today!
QPdfviewer v2.0.0-alpha.1 released! Now works with Quasar v2/Vue v3
https://github.com/quasarframework/app-extension-qpdfviewer/releases/tag/v2.0.0-alpha.1
Enjoy!
