### ISSUE TITLE
QDrawer scrollbars blink infinitely on some resolutions

### ISSUE THREAD

**Issue by zeroinformatique** [quasarframework/quasar#10281]
**Describe the bug**
The QDrawer component sometimes make native scrollbar appears (in addition to its own internal, stylized, scroll). On some resolutions or zoom-levels, it will start to blink in-and-out infinitely at 2 FPS.

**Codepen/jsFiddle/Codesandbox (required)**
You can reproduce this bug on your own documentation website:
https://quasar.dev/vue-components/stepper
The drawers on the left and on the right of the page may trigger this effect.

**To Reproduce**
1. Go to https://quasar.dev/vue-components/stepper
2. Play with `CTRL +` and `CTRL -` to zoom-in and zoom-out
3. You may see the native scrollbar pop in for a fraction of a second (this is not normal)
4. Eventually, if you insist at different resolutions and zoom-levels, it will start blinking and never stop

NOTE: On FireFox, I get to step 3 (which is still not normal). On Chrome, I get to step 4.
I suggest testing for this issue on Chromium for easier reproduction.

**Expected behavior**
The native scrollbar should never appear, especially because this component has its own, stylized, internal scroll.
A workaround is to add the css-class `no-scroll` on the QDrawer component; it fixed the issue for me.

**Screenshots**
![image](https://user-images.githubusercontent.com/10961896/128122853-536bc4b8-b3aa-4e53-a315-2903204f9ee6.png)
![image](https://user-images.githubusercontent.com/10961896/128122888-5e073d9e-f698-4b6d-8a12-88d70e4eb3a7.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.3

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 12.22.4
NPM: 6.14.14
Yarn: 1.22.11
Browsers: Chrome 92, FireFox 90

**Additional context**

**Comment by Evertvdw** [comment]
@zeroinformatique I had this same problem but I believe this is happening due to subpixel window heights. I have it for instance on certain heights when using a 4k monitor with 150% zoom (in windows desktop settings). Are you using a zoom at desktop level also?

**Comment by hawkeye64** [comment]
I also have seen this when using a zoomed of 200% and 125%

Once I removed the zoom, the issue went away. This is indeed a sub-pixel issue with the browsers.

**Comment by zeroinformatique** [comment]
> Are you using a zoom at desktop level also?

@Evertvdw  I use 125% DPI for my screens, yes.

**Comment by hawkeye64** [comment]
I am also curious if this only happens when you have Chrome Dev Tools opened?

**Comment by Evertvdw** [comment]
@hawkeye64 No, it happens on the PWA installed app om desktop for me too

**Comment by rstoenescu** [comment]
Fixed it in Quasar v2.4.4 & v1.17.1 (to be released)
