### ISSUE TITLE
QInput - help browser autocomplete

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#1028]
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.7

**Comment by CristalT** [comment]
It would be nice a property to disable the browser autofill feature on inputs of QSelect. Browser autofill coult be annoying while searching autocomplete results.

Html 5 property for this is `autocomplete="off"`

![Autocomplete results are hidden by autofill drowpdown](https://user-images.githubusercontent.com/12410837/59357739-bf91d500-8d01-11e9-9269-7a2d8eff8437.png)


![image](https://user-images.githubusercontent.com/12410837/59357452-48f4d780-8d01-11e9-8ef5-58069e653424.png)

**Comment by pdanpdan** [comment]
You can use that setting on QSelect if you want.

**Comment by CristalT** [comment]
It seems that the setting not affecting the QInput inside the QSelect
```
<q-select
            clearable
            use-input
            :options="provinciasFiltered"
            @filter="filterProvincias"
            label="Provincia"
            v-model="cliente.Provincia"
            autocomplete="off"
          />
```

**Comment by pdanpdan** [comment]
Can you inspect the input field to see if the attribute is placed on it? If it is then the rest is up to the browser.

**Comment by nothingismagick** [comment]
Are you using q-form? If so, you should put autocomplete="off" there. Otherwise you can wrap the components in a <form> element and do the same.

**Comment by pdanpdan** [comment]
I just checked and the attribute is passed to the input field as it should be.
