### ISSUE TITLE
q-select @input

### ISSUE THREAD

**Issue by peppicus** [quasarframework/quasar#10286]
**Describe the bug**
    <q-select
      class="col-2"
      v-model="model"
      :options="options"
      label="pagina"
      @update="(value) => { change(value) }"
    />

the method "change" wasn't not called when i change the select value

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/kz5o3c7r/1/

**To Reproduce**
change the value in the select widget: the console.log doesn't run

**Expected behavior**
i should see the console.log in the change method

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
$ quasar info

Operating System - Linux(5.4.0-80-generic) - linux/x64
NodeJs - 16.6.0

Global packages
  NPM - 7.19.1
  yarn - Not installed
  @quasar/cli - 1.2.1
  @quasar/icongenie - Not installed
  cordova - 10.0.0

Important local packages
  quasar - 1.15.23 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.2.10 -- Quasar Framework local CLI
  @quasar/extras - 1.10.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.14 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.5.1 -- Official router for Vue.js 2
  vuex - 3.6.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.14.8 -- Babel compiler core.
  webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Additional context**

**Comment by pdanpdan** [comment]
Please check the events described in the docs

**Comment by peppicus** [comment]
sorry i'm doing confusion testing ver 2

    <q-select
      class="col-2"
      v-model="model"
      :options="options"
      label="pagina"
      @input-value="(value) => { change(value) }"
    />

with this in ver 2 change doesn't trigger
i will open a brend nuew issue

**Comment by pdanpdan** [comment]
@input-value is triggered just when you use use-input and type something in the input field
