### ISSUE TITLE
about error-message

### ISSUE THREAD

**Issue by zta7** [quasarframework/quasar#10292]
**Is your feature request related to a problem? Please describe.**
If i want show error-message more than one line. I need to used 'slot #error' with v-html direction. Then the code doesnt look well it grows multiple rows.

**Describe the solution you'd like**
Add an attribute such as 'error-message-html'. Used render just for html messages.

**Comment by pdanpdan** [comment]
Sorry, this is what slots are for.

**Comment by syserr0r** [comment]
For anyone like me who stumbled upon this, I found this solution to work well (implemented as a component called `InputErrors` that extends `QInput`):

```js
<template>
  <q-input>
    <!-- pass through scoped slots -->
    <template
      v-for="(_, scopedSlotName) in $slots"
      v-slot:[scopedSlotName]="slotData">
      <slot :name="scopedSlotName" v-bind="slotData || {}" />
    </template>

    <!-- pass through normal slots -->
    <template v-for="(_, slotName) in $slots" v-slot:[slotName]>
      <slot :name="slotName" />
    </template>
    
    <!-- override error slot -->
    <template v-slot:error>
      <div v-if="Array.isArray(errorMessage)">
        <ul>
          <li v-for="item in errorMessage">
            {{ item }}
          </li>
        </ul>
      </div>
      <div v-else>{{ errorMessage }}</div>
    </template>
  </q-input>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'InputErrors',
  props: {
    errorMessage: {},
  },
});
</script>
```

Hopefully of some help to someone (and not against any rules)
