### ISSUE TITLE
Enable Table headers to display tooltip with icon

### ISSUE THREAD

**Issue by afnan** [quasarframework/quasar#10297]
Enable the table header columns to accept the tooltip icons and tooltip text. Currently, I guess this can be achieved with `<template v-slot:header="props">`. However, it would be fantastic if we could define two more properties while defining columns for example

 ```
columns: [
{
          name: 'totalOrders',
          field: 'type',
          align: 'centre',
          label: 'T.Orders',
          tooltipIcon:'fas fa-question-circle',
          tooltipText:'Displays the total orders imported through this store'
        },
]
```

**Comment by rstoenescu** [comment]
Hi,

The QTable component is already very complex. We do not want to make it even more complex with this custom request. This is one of those components that need to have VERY fast runtime, so that's why we added so many slots to it. When there's a custom scenario it can be written using one of the slots.
I hope you can understand our decision.

**Comment by homerjavi** [comment]
`<template v-slot:header="props">
          <q-tr :props="props">
            <q-th
              v-for="col in props.cols"
              :key="col.name"
              :props="props"
            >
              {{ col.label }}
              <q-tooltip v-if="col.tooltip">
                {{ col.tooltip }}
              </q-tooltip>
            </q-th>
          </q-tr>
        </template`

`{
        name: 'incoming',
        label: 'In',
        field: 'incomingCount',
        required: true,
        sortable: false,
        align: 'center',
        tooltip: 'Incoming candidates',
      },
      {
        name: 'process',
        label: 'P',
        field: 'processCount',
        required: false,
        sortable: false,
        align: 'center',
      },
      {
        name: 'finalist',
        label: 'F',
        field: 'finalistCount',
        required: false,
        sortable: false,
        align: 'center',
      },`
