### ISSUE TITLE
q-date range mode error

### ISSUE THREAD

**Issue by whiteua** [quasarframework/quasar#10294]
**Describe the bug**
<q-date v-model="calendar" range />
When re-selecting a date range, when selecting a start date in the date range of the previous selection, an error occurs.
If you select a new start date outside of the old range, no error occurs.

**To Reproduce**
1. Go to 'q-date range mode '
2. Click on 'Start date in the old period area'
3. See error "Uncaught (in promise) TypeError: Cannot read property 'from' of null"

**Expected behavior**
A new period selection will take place with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/6796581/128332657-47980c37-a0fc-4822-b05a-ac0f34043e9c.png)

**Platform (please complete the following information):**
Pkg quasar........ v2.0.3
Pkg @quasar/app... v3.0.4

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: v14.16.0
NPM: 6.14.11
Yarn:
Browsers: Chrome
iOS: -
Android: -
Electron: -

**Comment by hawkeye64** [comment]
@whiteua Can you please make a CodePen...

**Comment by whiteua** [comment]
https://codepen.io/whiteua/pen/eYWPBLB?editors=1010

In this example, the default selection is 1 to 14.

If I start a new range in this period, for example, from the 2nd to the 19th day. Clicking on the number 2 destroys the v-model object. 

If you continue, you can select a new range.

But if you select, for example, from 15 to 21, then the v-model object is not destroyed.

**Comment by hawkeye64** [comment]
@whiteua I see it. I don't know what the intention is for this component, but that does not seem right. I am imagining a date picker for booking something (like a vacation). Seems if you click within an existing range, then current range is removed and you have to start the process over again. Meaning additional clicks.
Can @pdanpdan weigh in on this?

**Comment by whiteua** [comment]
I agree, maybe so. But then model-value = {from: null, to: null} and in current implementation model-value = null, which leads to an error. I've made a crutch and don't allow model-value = null. But it took me a while. 
I use model for transaction sampling.

**Comment by whiteua** [comment]
Additional error.
If StartDateInRange = EdnDateInRange then model-value takes a string value, for example '2021/07/01' instead of storing the object value in 'Range' mode: {from: '2021/07/01', to: '2021/07/01'}.

I learned how to handle these errors. Still, it might save time for someone.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.6.

One comment though. The first click inside a selected range should unset it (otherwise there's no way for the user to unset the range); however, if the no-unset prop is used, then a new selection should start right away even if clicked inside the range (which was the bug fixed).
