### ISSUE TITLE
Specifying needed firewall rules in the docs

### ISSUE THREAD

**Issue by mYnDstrEAm** [quasarframework/quasar#10303]
Please specify which firewall rules are needed in the docs to make things a lot simpler for users who use stringent, protective/useful firewalls.

For instance, I currently can't get `quasar dev -m capacitor -T android` to start the app anymore after upgrading Quasar and Android Studio. **Edit**: it was due to the upgrade, not due to firewall rules and only couldn't get it to work again by running `quasar mode remove capacitor && quasar mode add capacitor` (using the former appId from capacitor.config.json in the latter) because there was an error in the code (I could find via the Android Studio output) which apparently was previously tolerated.

In Debian10/KDE the nftables firewall is used. I added these rules to allow localhost traffic as well as any http-alt from/to the local-ip (a bit too lax but that's what I used trying to get it to work; don't know why just allowing localhost like that didn't suffice):
```
ip saddr 127.0.0.1 ip daddr 127.0.0.1 accept
ip saddr mylocalip tcp dport http-alt counter packets 0 bytes 0 accept
ip saddr mylocalip tcp sport http-alt counter packets 0 bytes 0 accept
```
in chain INPUT and
```
ip saddr 127.0.0.1 ip daddr 127.0.0.1 accept
ip daddr mylocalip tcp dport http-alt counter packets 0 bytes 0 accept
ip daddr mylocalip tcp sport http-alt counter packets 0 bytes 0 accept
```
in chain OUTPUT.

The needed firewall rules or needed ports could be in a small info box, it could also be collapsed or just linked.

I think firewalls could be recommended for security purposes and having such things specified would make things a lot easier for users who use these. Please comment at that discussion if the cause of the app only showing white space / not starting isn't firewall rules.

**Comment by rstoenescu** [comment]
Hi @mYnDstrEAm ,

Thanks for this ticket.

Would you mind PRing the docs with the comment about firewall rules, pls? Just click the pencil (at the top) or the "Edit page" link (at bottom) on the page that needs updating -- it's an in-browser procedure so it's very fast.
