### ISSUE TITLE
QFooter 

### ISSUE THREAD

**Issue by ibrahim-developper** [quasarframework/quasar#10305]
**Describe the bug**
when open soft keyboard QFooter pushed up with the keyboard

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/ukhn2tbx/

**Expected behavior**
how i can fix it when open keyboard and keep it in the default position

**Screenshots**
<img src="https://user-images.githubusercontent.com/52491316/128520108-803b45d5-458d-4645-ae55-ee8e0117e724.jpg" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/52491316/128520479-30f5c1bf-7b3f-4afe-a159-53efcd48f5bd.jpg" width=50% height=50%>

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version: v1.2.1

Quasar mode:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers: google chrome mobile / samsung browser
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, what you want is not possible.

**Comment by pdanpdan** [comment]
For v2 I cannot help, but for v1 you can try an alternative build:

In package.json replace quasar dependency with:
"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.23-beta.5"

Then do a yarn or npm install and start the app again.

Please report if you find something not working.

**Comment by ibrahim-developper** [comment]
> For v2 I cannot help, but for v1 you can try an alternative build:
> 
> In package.json replace quasar dependency with:
> "quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.23-beta.5"
> 
> Then do a yarn or npm install and start the app again.
> 
> Please report if you find something not working.

hi thank you for your replay should i repeat all thing in the app ?

**Comment by pdanpdan** [comment]
Add that line in package.json in dependencies section
But only if you use quasar v1
Now it is

"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.23-beta.6"

**Comment by ibrahim-developper** [comment]
> Add that line in package.json in dependencies section
> But only if you use quasar v1
> Now it is
> 
> "quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.23-beta.6"

no i'm use quasar v2

**Comment by ibrahim-developper** [comment]
> > For v2 I cannot help, but for v1 you can try an alternative build:
> > In package.json replace quasar dependency with:
> > "quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.23-beta.5"
> > Then do a yarn or npm install and start the app again.
> > Please report if you find something not working.
> 
> hi thank you for your replay should i repeat all thing in the app ?

but i mean if i replace the version should repeat all thing in the app ?
thank you.
