### ISSUE TITLE
Notify.create TypeError: addNotification is not a function

### ISSUE THREAD

**Issue by gzhaipu** [quasarframework/quasar#10312]
**Describe the bug**
An error occurred during the creation of the Notify plugin: TypeError: addNotification is not a function

**To Reproduce**
use dist/quasar.esm.prod.js，Notify.create({ message: 'notify message' }) is error
use src/index.all.js，Notify.create({ message: 'notify message' }) is ok

**Screenshots**
![image](https://user-images.githubusercontent.com/3723585/128603489-8ef36a43-281e-4e44-bc37-643d96f72fb4.png

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.3

Quasar mode:
  - SPA

**Comment by rstoenescu** [comment]
Have you follow the instructions here? https://quasar.dev/quasar-plugins/notify#installation

**Comment by gzhaipu** [comment]
@

**Comment by sonikdesign** [comment]
Hello. I had the same problem with Notify, not inside a .vue component (where it works correctly):
```vue
import { useQuasar } from 'quasar'
...
const q = useQuasar()
q.notify('TEST')
```
but when used in a .ts file:
```vue
import { Notify } from 'quasar'
...
Notify.create('TEST')
```
Notify and other plugins are in quasar.conf.js "plugins" array.

tsconfig.json is correct, it's the same of a working quasar project. 

I have same problem with date (only when used in ts files):

```vue
import { date } from 'quasar'
...
date.formatDate (new Date (), 'DD / MM / YYYY')
```

date exists, date.formatDate exists. Running this code, the error is:
```
Uncaught (in promise) TypeError: Cannot read property 'date' of undefined
```

The error would appear inside formatDate:
```vue
Plugin$7.props.date
```

I also tried to install a package.json from a working quasar project, but nothing is changed. I am using Quasar 2.0.1 and latest.

**Comment by sonikdesign** [comment]
@gzhaipu @rstoenescu problem was this row in tsconfig.json:
```
// if using webpack 2+ or rollup, to leverage tree shaking:
"module": "CommonJS"
```

without it, all plugins work great.

**Comment by mesqueeb** [comment]
I have the same issue 😅

did follow the installation steps.
didn't have that thing in the TSConfig though.

**Comment by LiHDong** [comment]
I met the same issue either.And I found that I invoke the `Notify.create()` method before the plugin was installed.After changing the import order, the function could run normally.

**Comment by capodisseny** [comment]
I had the same issue. In my case was because I was loading quasar from an npm link package and was resolved with different files from that package and the main package. So adding this code to the quasar.config.js solved the issue.

```
build:{
extendWebpack(cfg){
cfg.resolve.alias["quasar"] = path.resolve('./node_modules/quasar')
}
}
```
