### ISSUE TITLE
Prefetch not being called when navigating using router link

### ISSUE THREAD

**Issue by lazaroofarrill** [quasarframework/quasar#10313]
**Describe the bug**
I'm building a site in SSR mode. I am prefetching data on every page. When navigating to a page entering the url directly or
using href, the content is loaded correctly. However when navigating using the `to` property of a router link or route-tab, or changing `window.location.url ` preFetch does not occur, so my pages render empty. Reloading the page at this state does trigger a preFetch since it's like navigating directly to it.

Edit:
This problem is not present in SPA mode.

**To Reproduce**
1. Use prefetch on page
2. Navigate to that page using a  regular href //works
3. Navigate to the same page using a router-link //doesn't work

**Expected behavior**
Since prefetching is based on vue-router, I expected router links to work seamlessly with it.

**Screenshots**

Navigation with router-link
![image](https://user-images.githubusercontent.com/35935209/128616465-e99fc257-f810-4570-91ac-465725967cd4.png)

Navigation with `a` tag
![image](https://user-images.githubusercontent.com/35935209/128616496-f28cf697-79c6-471a-a38b-2fe988efaa62.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.0.1

Quasar mode:
  - [ ] SPA
  - [X] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 21.04
Node: 14.17.0
NPM: 7.19.0
Yarn: 1.22.10
Browsers: Opera 77, Chrome 92, Firefox 90.0.2
iOS:
Android:
Electron:

**Comment by chAhmedRaza** [comment]
I'm facing a similar problem. How did you resolve it?

**Comment by lazaroofarrill** [comment]
> I'm facing a similar problem. How did you resolve it?

Actually I don't remember if it was related to the transition between pages, or maybe the scroll behavior.

**Comment by hawkeye64** [comment]
If it's transitioning between pages, I do believe that's changed: https://next.router.vuejs.org/guide/advanced/transitions.html
