### ISSUE TITLE
Add functionality to q-drawer so that it also works horizontally along top and bottom of the page

### ISSUE THREAD

**Issue by jl8n** [quasarframework/quasar#10314]
**Describe the solution you'd like**
Modify the current `q-drawer` component so that it also works horizontally, along the top and bottom of the viewport. The drawer could then expand downwards or upwards respectively.  

**Describe alternatives you've considered**
Making the  `q-header` and `q-footer` components expandable/collapsible might be a good alternative

**Additional context**
It would be useful to mimic functionality such as the Android notification bar or the iOS control panel

**Comment by MilosPaunovic** [comment]
Or, you could use this
https://quasar.dev/quasar-plugins/bottom-sheet

**Comment by pdanpdan** [comment]
Check this and adapt as needed: https://github.com/quasarframework/quasar/issues/7541
