### ISSUE TITLE
Autocomplete only work in q-search

### ISSUE THREAD

**Issue by nueko** [quasarframework/quasar#1032]
### Software version

Quasar: 0.14.6
OS: Win 10 x64
Node: 6x
NPM: 5.5.x
Browsers: Chrome 62
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
`Injection "__inputParent" not found`
### What were you expecting?
 working just like when the autocomplete wrapped by q-search
```html
<q-search v-model="terms">
  <q-autocomplete
    separator
    @search="search"
    @selected="selected"
  />
</q-search>
```
### What steps did you take, to get the error?
create any autocomplete with q-input or q-field
```html
<q-input color="amber" v-model="terms" placeholder="Type 'fre'">
  <q-autocomplete
    @search="search"
    :min-characters="3"
    @selected="selected"
  />
</q-input>
```

**Comment by nueko** [comment]
with the latest edge, get this
` Error in mounted hook: "TypeError: Cannot read property 'register' of null"`
when using q-field as the parent and add `helper` or `error-label` directive

**Comment by rstoenescu** [comment]
Update edge again. There have been some changes in the past few minutes. Also make sure you are running Vue 2.5+
