### ISSUE TITLE
The css is abnormal after the project is build

### ISSUE THREAD

**Issue by gzhaipu** [quasarframework/quasar#10329]
**Describe the bug**

After executing the build command, the style is abnormal under Android, and the official website is also the same。

**Screenshots**
![Screenshot_20210809_233346_com tencent mm](https://user-images.githubusercontent.com/3723585/128734043-ef43e093-3354-495c-9bfe-64e757fafdde.jpg)
![Screenshot_20210809_233412_com tencent mm](https://user-images.githubusercontent.com/3723585/128734092-02e8e9a4-4082-4ae9-b64f-cc27ea53bb55.jpg)
![Screenshot_20210809_233522_com tencent mm](https://user-images.githubusercontent.com/3723585/128734127-e2c29de7-43e7-4e25-9171-5a33623db0d3.jpg)

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.4

Quasar mode:
  -  SPA

Browsers:  OK
iOS: OK
Android:  Abnormal

**Comment by pdanpdan** [comment]
Android is not a browser.

**Comment by gzhaipu** [comment]
browser on Android os

--------------原始邮件--------------
发件人："Popescu Dan ***@***.***&gt;;
发送时间：2021年8月9日(星期一) 晚上11:53
收件人："quasarframework/quasar" ***@***.***&gt;;
抄送："gzhaipu ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [quasarframework/quasar] The css is abnormal after the project is build (#10329)
-----------------------------------

 

 
Android is not a browser.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pdanpdan** [comment]
Android is not iOS to have only Safari.
Please fill the browser and the version you are using or I'll close this, thank you.

**Comment by gzhaipu** [comment]
--------------原始邮件--------------
发件人："Popescu Dan ***@***.***&gt;;
发送时间：2021年8月9日(星期一) 晚上11:57
收件人："quasarframework/quasar" ***@***.***&gt;;
抄送："gzhaipu ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [quasarframework/quasar] The css is abnormal after the project is build (#10329)
-----------------------------------

 

 
Android is not iOS to have only Safari.
 Please fill the browser and the version you are using or I'll close this, thank you.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
