### ISSUE TITLE
[docs] Back button not work

### ISSUE THREAD

**Issue by MaYoRr** [quasarframework/quasar#10324]
I want the back button on android to return to the previous route, I put the following settings 
` framework: {
      iconSet: 'material-icons', // Quasar icon set
      lang: 'en-us', // Quasar language pack
      config: {
        capacitor: {
          backButtonExit: '*',
          backButton: true
        }
      },` '
and it does not work, I have to close the application. I use $router.push

**Comment by MaYoRr** [comment]
The plugin does not distinguish /menu/feed from /menu/messenger and so on. The position from the first route is carried over to all the others

`  {
    path: '/menu/',
    component: () => import('layouts/MenuLayout'),
    children: [
      {path: 'feed', component: () => import('pages/Tabs/Posts')},
      {path: 'groups', component: () => import('pages/Tabs/Groups')},
      {path: 'notifications', component: () => import('pages/Tabs/Notifications')},
      {path: 'people', component: () => import('pages/Tabs/People')},
      {path: 'messenger', component: () => import('pages/Tabs/Messenger')},
    ]
  },`

**Comment by pdanpdan** [comment]
Please fill the issue template and while doing this please check the versions noted here: https://v1.quasar.dev/vue-directives/go-back#cordova-capacitor
