### ISSUE TITLE
QDate not Rendering Properly on QDialog

### ISSUE THREAD

**Issue by snow-drop** [quasarframework/quasar#10335]
Good day.

I have a QDialog with QDate inside, but it seems that it can't render the QDate properly. I tested it outside QDialog and is working. 

![image](https://user-images.githubusercontent.com/34905419/128801083-fdbbe02d-1b8e-4047-a307-efb9e5298c81.png)

Here's a codepen as a sample: https://codepen.io/snow-drop/pen/bGWOrVp

Is there any quick fix for this? Thank youuu

**Comment by MilosPaunovic** [comment]
It is rendered just fine, only the `text-white` class on your `q-card` colors the text white, so it seems invisible. Change it to `text-dark` to check out.

**Comment by snow-drop** [comment]
> It is rendered just fine, only the `text-white` class on your `q-card` colors the text white, so it seems invisible. Change it to `text-dark` to check out.

Ohhhhh thank you very much for spotting it.
