### ISSUE TITLE
Problem with Autocomplete Popover position on iOS

### ISSUE THREAD

**Issue by wgarrido** [quasarframework/quasar#1034]
### Software version
Quasar: 0.14.6
iOS: 10/11

### What did you get as the error?

The Autocomplete popover position is wrong on iOS.

### What were you expecting?

The same result as on Android device.

### What steps did you take, to get the error?

![](https://media.giphy.com/media/xT9IgDlw6biM9hgTzW/giphy.gif)
![](https://media.giphy.com/media/xT9IgkTP8JWxghDOWk/giphy.gif)

**Comment by rstoenescu** [comment]
`cordova plugin add cordova-plugin-wkwebview-engine`
for your iOS Mobile app.

**Comment by MitchellMonaghan** [comment]
Hi Raz,

I am seeing this issue on quasar 0.16.4 on iphone 6 plus. ios seems to have a scroll when a input is focused and this causes the pop over to be positioned incorrectly.

This happens on just a regular spa. Currently not building a cordova app. Seems to be ios only.

**Comment by p3v9d5ui** [comment]
@rstoenescu Why do you suggest this as a solution? I do use cordova-plugin-wkwebview-engine, but I get the exact same behaviour as described in this ticket.

**Comment by rstoenescu** [comment]
Don't think you'll get that on v1, regardless if it's a mobile browser or a cordova/capacitor app :)
