### ISSUE TITLE
Prevent dialog hide/close inside the escape-key event function

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#10345]
**Is your feature request related to a problem? Please describe.**
We want to be able to close all dialogs with the esc key. But some dialogs contain forms and should only be able te be closed if everything is valid. So we need the possability to prevent the dialog from closing inside the escape-key function.

**Describe the solution you'd like**
The event is passed inside the escape-key function and can be stopped via stopPropagation etc.

**Describe alternatives you've considered**
If the escape-key function returns false, the dialog is not closed

**Comment by pdanpdan** [comment]
Use a dynamic `no-esc-dismiss` prop on the dialog based on the validation status.
