### ISSUE TITLE
The event for dialog hide and before-hide are not passed to the bound functions

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#10344]
**Describe the bug**
The [documentation ](https://quasar.dev/vue-components/dialog) states that the hide and before-hide event should be passed the event, but nothing is passed

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/gallant-almeida-gxkjc?file=/src/components/SimpleDialog.vue

**To Reproduce**
1. Click on 'click me'
2. Click on 'cancel'
3. alerts open and state that the event

**Expected behavior**
The event is passed

**Platform (please complete the following information):**
Quasar Version: Windows
@quasar/app Version: 2.0.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows

**Comment by pdanpdan** [comment]
Only the events related to clicking outside (backdrop click) are available - when clicking on the buttons there is no event by design
https://codesandbox.io/s/dreamy-cannon-ig90k?file=/src/components/SimpleDialog.vue
