### ISSUE TITLE
Issue: Feature request for SSR Build to Natively Support HTTPS (Quasar v2)

### ISSUE THREAD

**Issue by zanotam** [quasarframework/quasar#10363]
**Is your feature request related to a problem? Please describe.**
So I find it somewhat annoying that when setting up an SSR+PWA I end up with a node web server which I cannot control the port of nor enable HTTPS on for build unlike in dev. PWAs literally require HTTPS to function properly and having to create a reverse proxy in nginx or whatever feels rather over the top for basic testing of a server designed to be run on node. Maybe I'm just weird, but I even have my SSR+PWA made via Quasar using middleware to answer a POST API request because that's how I'm used to designing servers and it just seems, well, silly, to have to write an entire extra node server set-up to 'natively' handle https as is required for a PWA with just JS/Node code.

**Describe the solution you'd like**
Add options to enable HTTPS and choose port for SSR's in build mode similar to the more general options for those exact features in dev mode. 

**Describe alternatives you've considered**
I just worked around it in the end with Nginx acting as a reverse proxy, but it seemed unnecessarily complicated when the rest of the features I've needed so far have come out of the box ready. 

**Additional context**
N/A

**Comment by pdanpdan** [comment]
Https does not make sense. Terminate your secure connection in a proxy.
