### ISSUE TITLE
Select with disabled options

### ISSUE THREAD

**Issue by cedriccouret** [quasarframework/quasar#1036]
Hi,

I was wondering if it was possible to disable specific options in a select ?
I need to display options that are normally available but not in the current selection context.
The options array could look like this, with disabled set as false by default:
```
selectOptions: [
  {
    label: 'Google',
    value: 'goog',
    disabled: true
  },
  {
    label: 'Facebook',
    value: 'fb'
  },
  ...
]
```

Thanks.

**Comment by pdanpdan** [comment]
What is the desired behavior for the model when the selected options in model are disabled?
For the moment it'll stay as it is.

**Comment by cedriccouret** [comment]
Hi, thanks for your answer.

Actually the perfect scenario would be to pass the entire option object that has been selected inside the "selected" model. The entire original object would be passed so the @change event would get it entirely, not only its value. That's the "dream" scenario :-)

But my need isn't really to deal with the selected options model, but instead to be able to disable some options. When passing my available options to your component, I would need to display all options in the dropdown, but those who have their "enabled" property set to false would be unselectable and grayed out, like in a native dropdown.

That would be just great.
Thanks again.
