### ISSUE TITLE
Dynamic ref is null for q-input on a row for q-table

### ISSUE THREAD

**Issue by migsbeast** [quasarframework/quasar#10366]
I am trying to focus on an input from a row of a q-table after hitting enter or a submit button which makes an axios call that adds a new row to the table. The dynamic reference is being added to the divs array that I created, but the problem is when I try to access the focus method for the element it comes back as null so I'm not able to focus on the element.
I'm accessing the ref dynamically. Can anyone help?

https://codepen.io/migsbeast/pen/BaRbjvj

1. Enter the id on the search input that you want to add to the table  
2. Press enter or click on the search button 
3. The error occurs here

**Expected behavior**
It should blur the search input and focus on the cost input of the last row of the table

**Screenshots**
![refbug](https://user-images.githubusercontent.com/16072328/129262305-cb92d3db-a1b6-46e2-9543-c39d0bd579eb.PNG)

**Platform:**
Quasar Version: v3.0.0-rc.1

Quasar mode:
  - SPA

Tested on:
  - SPA

**Comment by mila76** [comment]
for now my only idea is try use nextTick for focus
`Vue.nextTick(() => this.setFocus())`
Somethinkg like this....

**Comment by mila76** [comment]
A working codepen [here](https://codepen.io/mila76/pen/bGWPwzy)
I dont really understand what you want to accomplish but i'm sure there is a better way to do than use a dynamic ref 

please close this

**Comment by rstoenescu** [comment]
This is just how Vue 3 handles refs. A nextTick() call would be what you need.
