### ISSUE TITLE
Please add back <div id="q-app"></div> to /src/index.template.html inside of <body>

### ISSUE THREAD

**Issue by Grawl** [quasarframework/quasar#10374]
**Describe the bug**

If I replace quotes from double to single in `src/index.template.html`, I got an error on app start:

```
 App • ⚠️  Please add back <div id="q-app"></div> to
    /src/index.template.html inside of <body>
```

**Codepen/jsFiddle/Codesandbox (required)**

https://codesandbox.io/s/vigilant-burnell-4qnn6?file=/src/index.template.html

**To Reproduce**
1. Go to 'src/index.template.html'
2. Replace `"` with `'`
3. Restart app (`quasar dev`)

**Expected behavior**
App is working

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.4

Quasar mode:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS 11.5.1 (20G80)
Node: 14.17.5
NPM: 6.14.14
Yarn: 1.22.10
Browsers: Google Chrome 92.0.4515.131

**Comment by pdanpdan** [comment]
The quotes used in html are double quotes, not single ones.

**Comment by Grawl** [comment]
You mean I cannot use single quotes in HTML?

**Comment by Grawl** [comment]
Fast googling takes me to [this StackOverflow question](https://stackoverflow.com/questions/273354/are-single-quotes-allowed-in-html) refers [the spec](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2) allowing single quotes in HTML.

**Comment by Grawl** [comment]
[Spec allows single quotes in HTML](https://dev.w3.org/html5/html-author/Overview.src.html#single-quote-attr)

**Comment by pdanpdan** [comment]
Ok, but use double quotes :)

**Comment by Grawl** [comment]
I use single quotes in all my codebase

**Comment by Grawl** [comment]
okay I just will use Pug to generate double-quoted HTML

```js
const fs = require('fs')
const pug = require('pug')
const template = pug.renderFile('./src/index.ejs.pug', { pretty: true })
fs.writeFileSync('./src/index.ejs', template)

module.exports = configure(function (ctx) {
	return {
		// ...
		sourceFiles: {
			indexHtmlTemplate: 'src/index.ejs',
		},
	}
}
```

**Comment by SharpBCD** [comment]
I have the same problem now. 
Here is my code
```	<!-- DO NOT touch the following DIV -->
	<div id="q-app"></div>
```

Notice I deleted the spaces around the "=" and then it works. This is a fresh generated quasar project, nothing was touched. 

 Dev mode.......... spa
 Pkg quasar........ v2.7.3
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... enabled
