### ISSUE TITLE
virtual-scroll header sticker is not displayed

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#10373]
Code example from quasar.dev does not work.
see Sticky headers table, Playing with sticky headers sections
https://quasar.dev/vue-components/virtual-scroll#example--sticky-headers-table

Original codepen code from that sections demonstrate the bug.

![image](https://user-images.githubusercontent.com/1247062/129314316-9333a785-012f-4ce0-85c8-bae741c991da.png)

Quasar Version: 2.03
@quasar/app Version: newest

Quasar mode:
  - [ x] SPA
Tested on:
  - [x ] SPA
  
OS: Linux mint
Node: newest
NPM: newest
Yarn: newest
Browsers: Chrome

**Comment by pdanpdan** [comment]
thead|tbody are wrapped in a `<template>` tag on conversion, even if they are already in a template

to make the example work you can for the moment remove the inside template tag
