### ISSUE TITLE
Q-Input and  v-model.trim and clearable  does not work on Q2

### ISSUE THREAD

**Issue by zanzara** [quasarframework/quasar#10376]
### Discussed in https://github.com/quasarframework/quasar/discussions/10362

<div type='discussions-op-text'>

<sup>Originally posted by **zanzara** August 12, 2021</sup>
IMO it seems to be a bug:
If i use this:
```vue
     <q-input
         v-model.trim="v$.bildUrl.$model" 
        :error="v$.bildUrl.$error"
        :error-message="getPicErrMsg(v$.bildUrl)"
         dense
         lazy-rules
         clearable
         autofocus
         :hint="$t('gwsCol.Bild.hint')"
   />
```
it throws me this error when I click on `clearable`:
![Bildschirmfoto zu 2021-08-12 15-18-12](https://user-images.githubusercontent.com/7381054/129203727-be2be1ea-80e5-4475-84ec-cade5632db40.png)

If I  use `v-model` w/o `.trim` it works.
Can anyone confirm? Or where is my mistake?  (it works in Q1)

(Info:   » Pkg quasar........ v2.0.3    » Pkg @quasar/app... v3.0.4 )
</div>

**Comment by ontwikkelfabriek** [comment]
I can confirm, pressing clear input on the first input with the `trim` modifier will throw a null pointer exception. The second input without `trim` is fine.

Here's a codepen:
https://codepen.io/ontwikkelfabriek/pen/MWmRwjr

**Comment by rstoenescu** [comment]
This should be "enhanced" in Vue itself.

Please use a slot and add yourself a QBtn/QIcon with a click handler to reset the model to an empty string instead of null. No way around it unless 1) Vue handles null value and 2) we introduce a breaking change and reset model to empty string (which is definitely a no-go).

**Comment by zanzara** [comment]
So last remark  'cause it had worked before in Qv1:
Is this a bug in Vue3?  Or how  do I should interpret "enhancement"  here?
@rstoenescu To be honest, I did not understood your explication.  I think it got something to do with `.trim` 
Because w/o this modifier it works pressing  the `clearable`  prop?!

**Comment by CamilleDrapier** [comment]
This might be fixed in `vue` in the following [PR](https://github.com/vuejs/core/pull/5770) related to this issues: https://github.com/vuejs/core/issues/5765
