### ISSUE TITLE
Vue3 + Vite + Quasar hmr bug

### ISSUE THREAD

**Issue by Eldar-X** [quasarframework/quasar#10387]
I know there is no official vite support yet but I am using Vue3 + Vite + Quasar and it was working fine so far but I found bug in hmr. When a QInput components is used within the QDialog component and the v-model property is set, hmr does not update it. The hmr can be updated properly when the v-model is not set. I made a minimal repo, there are 2 q-input components, you can change their labels or any other properties and see the difference. It works fine with or without the v-model set outside of the QDialog. My understanding is that hmr has trouble detecting changes in some cases. Can we handle this in quasar or should I open an issue on the vite repo?

https://github.com/Eldar-X/vite-quasar-hmr-bug

**Comment by IlCallo** [comment]
Official Vite plugin for Quasar has been released yesterday: https://quasar.dev/start/vite-plugin
Can you check if the problem you found is still reproducible and, if yes, update the repro to use the new plugin?

**Comment by rstoenescu** [comment]
Also, there's been a hmr bug fixed in vue-loader recently.
Please reopen or comment here if using our Vite plugin with latest Vite is still reproducing your issue.
