### ISSUE TITLE
[Request] Allow select input on Dialog

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1039]
Add support for `QSelect` and `QDialogSelect` to Dialog's forms.

```
Dialog.create({
  // ...
  form: {
    product: {
      type: 'select', // 'dialog-select',
      items: ...,
      model: ...
    }
  }
})
```

**Comment by rstoenescu** [comment]
In v0.15 you'll be able to add whatever components in Dialog that you want. There will be an extra component called QDialog for this (besides the default Dialog.create method).
