### ISSUE TITLE
[Roadmap]Vite.js plugin for Quasar v2 release date

### ISSUE THREAD

**Issue by fyeeme** [quasarframework/quasar#10398]
**Is your feature request related to a problem? Please describe.**
 Yes, Quasar for vite  would be start at Q2,  Q3 is coming, but still none of message or repo for vite

**Describe the solution you'd like**
 Is it better to create a branch or repo for vite as experimental.

**Comment by IlCallo** [comment]
Hey there, we are a bit late on the public roadmap, but Quasar plugin for Vite is the next big thing to do.
Many core team members are now on vacation and we'll probably advance faster on the roadmap from next month :)

Always remember this phrase from the roadmap page:

> The schedule may change based only on unforeseen and/or out of the ordinary circumstances.

**Comment by fyeeme** [comment]
@IlCallo  Many thanks for you reply and can't wait for the the **Big thing**

**Comment by IlCallo** [comment]
Vite plugin for Quasar has been released yesterday 🥳 
https://quasar.dev/start/vite-plugin

**Comment by fyeeme** [comment]
@IlCallo Yeah, have being used in my [Project](https://github.com/fyeeme/vite-quasar), and feel good. you are really did a great job. Awesome.
