### ISSUE TITLE
Axios concatenate baseURL with localhost

### ISSUE THREAD

**Issue by nicolaslima321** [quasarframework/quasar#10403]
Hello everyone! :smile: 

Im having an issue when making requests from axios, thats happen in very different ways, but basically, it concatenate my baseURL with localhost, i found an similiar issue described here on a [stackoverflow post](https://stackoverflow.com/questions/58680554/quasar-axios-request-wrong-url-double-url)

**Somethings that i tried:**
- Reinstall the project (Removing e installing node_modules again)
- Create a new Quasar Project, selecting Axios as a needed dependencie, and with axios dont selected too
- Tried axios with Import, with boot (By Quasar), importing, creating an axios instance and exporting

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/nicolaslima321/pen/poPmRGY

**To Reproduce**
I had 3 different ways to reproduce this error, but basically, its just do a axios request with baseURL setted:

1º -> When i create an axios instance and use it through my JS imports:
```
const api = axios.create({ baseURL: `${process.env.API_URL}/` })
export default api;

....

import api from './axios' (example)
api.post('/somepath')
```

2º -> When i static change axios.defaults.property:
```
axios.defaults.baseURL = apiUrl
axios.post('/somepath')
```

3º -> When i booted axios by Quasar [following it docs](https://quasar.dev/quasar-cli/boot-files#axios), using it directly in a Vue component:

Example (considering my boot/axios.js)
**axios.js:**
```
import { boot } from 'quasar/wrappers'
import axios from 'axios'

const api = axios.create({ baseURL: `${process.env.API_URL}/` })

export default boot(({ app }) => {
  app.config.globalProperties.$axios = axios
  app.config.globalProperties.$api = api
})
export { api }
```
**Component.vue:**
```
The result for two options is the same.
this.$api.post('/somepath')
this.$axios.post('/somepath')
```

**Expected behavior**
Do a request considering only the baseURL with nothing concatenated

**Screenshots**
(When i do a post request) with this code `return axios.post('/api/users', { user });`
![image](https://user-images.githubusercontent.com/23743072/129634989-633b118c-7455-4fdf-a72a-33a77fbc080e.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.0

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20
Node: v14.15.4
NPM: 6.14.10
Yarn: Not using
Browsers: Chrome
iOS: Not using
Android: Not using
Electron: Not using

**Comment by nicolaslima321** [comment]
BTW, im using this property on my `quasar.conf.js` for process.env.API_URL
```
    build: {
      env: {
        API_URL: ctx.dev
          ? 'https//lorem-dev-api.herokuapp.com/'
          : 'https//lorem-api.herokuapp.com/'
      },
```

**Comment by pdanpdan** [comment]
Hello. Please check the documentation on axios.
Your problem had nothing to do with quasar, except the fact that it can be installed automatically in the seed project.

**Comment by pdanpdan** [comment]
Btw, both strings you use as base url are not valid

**Comment by nicolaslima321** [comment]
I tried this before @pdanpdan , but will keep searching then..
and about the URL, yeah, i know, changed the real url to post this example on issue :smile:

**Comment by nicolaslima321** [comment]
thanks anyway! :fist_oncoming:

**Comment by nicolaslima321** [comment]
If anyone is dealing with this, to me it was solved when i defined baseUrl like this: `const apiUrl = 'https://api-url.com/';`, instead using `process.env.API_URL`

**Comment by pdanpdan** [comment]
No, it was solved when you added : after https and before //

**Comment by gh81997167** [comment]
@pdanpdan  Our request is based on the website's own domain name to request the interface, for example, the corresponding API request of a.com is a.com/api, the corresponding API request of b.com is b.com/api,  Found unavailable windos.localhost.host and process.env.api_url in boot/axios.js  
Process.env. API_URL can be used in the development environment but not in the production environment  
Is there any way to configure automatic domain name acquisition for the current site in boot/axios.js
