### ISSUE TITLE
q-img tag not working well in firefox version 91.0.1(64bit)

### ISSUE THREAD

**Issue by ruzlicali16** [quasarframework/quasar#10415]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**
The q-img is not working well when you use it in firefox but working good in brave browser. I used Firefox  version 91.0.1(64bit) and Brave Browser Version 1.27.111. I tried to change img tag only in firefox and it is now working.

**Screenshots**
Chrome:
![Screenshot 2021-08-18 202109](https://user-images.githubusercontent.com/44608860/129897418-3d8b0e50-192d-469d-bc1f-0056fd52c07a.png)
Firefox: 
![Screenshot 2021-08-18 202005](https://user-images.githubusercontent.com/44608860/129897463-c4267c2c-096d-4ae6-86f0-d8bbb69692f0.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [ -] SPA
  - [ ] SSR
  - [- ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [- ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows_NT(10.0.19042) - win32/x64
Node: 14.15.0
NPM: 7.19.0
Yarn:
Browsers: Firefox
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Hello. You provide no details on how you use QImg, no details on what version of quasar you are using. I can guess you are using SVGs. You must pass the width/height for Firefox. Check the duplicate issues.
