### ISSUE TITLE
virtual-scroll header sticker is not fixed if  slot:header is added to q-table

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#10412]
Class my-sticky-virtscroll-table of q-table fixes the header on the top of the table. Otherwise the header is scrolled with items.

If header slot is added to q-table with my-sticky-virtscroll-table,  the header is scrolling anyway.

https://codepen.io/Claus1/pen/eYWwJQZ?editors=101

1. Go to  https://codepen.io/Claus1/pen/eYWwJQZ?editors=101
2. Scroll the table items down.
4. See the header is scrolling with items.

![image](https://user-images.githubusercontent.com/1247062/129848198-7b4361a2-495f-4c64-92df-07e7e8c1e7ec.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.03/3.04

Quasar mode:
  - [ x] SPA

Tested on:
  - [x ] SPA
OS: Linux Mint
Node: newest
NPM: newest
Yarn: newest
Browsers: Chrome newest

**Comment by pdanpdan** [comment]
It might work better if you also copy the CSS from the example :)

**Comment by Claus1** [comment]
It does not help. At least the css from the example https://codepen.io/Claus1/pen/eYWwJQZ .
