### ISSUE TITLE
Support for .env for multiple environments

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#10418]
**Is your feature request related to a problem? Please describe.**
With Quasar V2, qenv plugin was deprecated. Using build env can build only production. but if we need to build for staging, QA builds using separate env values we can't handle that.   

**Describe the solution you'd like**
Introduce some variable to ctx object to load dotenv file or any other mechanism.  

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MilosPaunovic** [comment]
Check this discussion on that topic:
https://github.com/quasarframework/quasar/discussions/10234
