### ISSUE TITLE
quasar@1.0.0 run  error 

### ISSUE THREAD

**Issue by chend01** [quasarframework/quasar#10411]
**Describe the bug**
使用quasar@1.0.0 运行报错
(node:995) UnhandledPromiseRejectionWarning:   TypeError: Cannot read property 'charAt' of undefined
  
  - Extension.js:107 new Extension
    [client]/[@quasar]/app/lib/app-extension/Extension.js:107:14
  
  - quasar-run:51 run
    [client]/[@quasar]/app/bin/quasar-run:51:21
  
  - quasar-run:91 Object.<anonymous>
    [client]/[@quasar]/app/bin/quasar-run:91:1
  
  - loader.js:1063 Module._compile
    internal/modules/cjs/loader.js:1063:30
  
  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10
  
  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32
  
  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14
  
  - loader.js:952 Module.require
    internal/modules/cjs/loader.js:952:19
  
  - helpers.js:88 require
    internal/modules/cjs/helpers.js:88:18
  
  - quasar:80 Object.<anonymous>
    [client]/[@quasar]/app/bin/quasar:80:1
  

(Use `node --trace-warnings ...` to show where the warning was created)
(node:995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/VgQbdx) or a jsFiddle (https://jsfiddle.net/rstoenescu/rmaodk0f) or a Codesandbox (https://codesandbox.io/s/github/quasarframework/quasar-codesandbox) and hit save then copy-paste link here.

**Comment by MilosPaunovic** [comment]
Did you use `charAt` somewhere in your code? That should be your first attempt to solve this.

**Comment by chend01** [comment]
This is really the first time I have solved such a problem. I don't use chartAt in my code

**Comment by MilosPaunovic** [comment]
Okay, try to delete `node_modules` folder and do a fresh `npm i` after that.

**Comment by rstoenescu** [comment]
Make sure that you don't use an old Node.js version. Use LTS versions. For Qv1 in particular, you should be exactly on Node.js v12.

Then check what App Extensions you have installed. This error comes from one of them.
