### ISSUE TITLE
[sass] replace / with  math.div()

### ISSUE THREAD

**Issue by fyeeme** [quasarframework/quasar#10427]
╷
43 │     $sin: $sin + pow(-1, $i) * pow($rad, (2 * $i + 1)) / fact(2 * $i + 1)
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/quasar/dist/quasar.sass 43:18    sin()
    node_modules/quasar/dist/quasar.sass 4405:16  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

**Comment by pdanpdan** [comment]
duplicate of #9362
