### ISSUE TITLE
Add new language | IsoName: 'bn' | NativeName: বাংলা

### ISSUE THREAD

**Issue by ctpli** [quasarframework/quasar#10424]
**Is your feature request related to a problem? Please describe.**
No, just will help us build more language friendly apps in Bengali

**Describe the solution you'd like**

to add the language to the quasar and also I have created PR

**Describe alternatives you've considered**

I have created a PR for the issue and also provided the required language file

**Additional context**

download the file from https://github.com/quasarframework/quasar/files/7012047/bn.zip

**Comment by rstoenescu** [comment]
Language added in Quasar v2.0.4
