### ISSUE TITLE
QSelect is wrongly exposing some methods

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#10433]
**Describe the bug**
QSelect is exposing some methods wrongly, making it impossible to correctly use `getOptionLabel`, `getOptionValue`, and `isOptionDisabled` methods from outside(_e.g. through template refs_).

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/sborick/pen/abWemqd

**To Reproduce**
1. Open the provided Codepen link
2. See that wrong values are displayed
	- For example, in the first one, it's displaying all props of the component instance get displayed instead of `Google`)
	- See the code comments and values of others to compare.

**Expected behavior**
The expected behavior is to get the correct values, which are explained in the code comments on the repro.

**Platform**
Quasar Version: 2.0.3
@quasar/app Version: -

All modes are affected since it's a core UI bug.

**Additional context**
samborick#5569 from the Discord server noticed there is something wrong with `getOptionLabel` and `getOptionValue`:
> Hi everyone, I'm having some issues with QSelect getOptionValue and getOptionLabel.  They don't seem to be returning what I expect.  Here's a codepen example of my issue: https://codepen.io/sborick/pen/abWemqd
> am I using these methods incorrectly?

After some investigation, I found that the methods are working correctly, but they were getting exposed in the wrong way.

It's happening because arguments binding is not available in arrow functions, so it uses the arguments from the closest scope, which means the setup function, that's the reason it's returning the list of props: https://github.com/quasarframework/quasar/blob/bdcafc0486f804bc59298d79e045ddefe9e5bbae/ui/src/components/select/QSelect.js#L1429-L1431

**Comment by yusufkandemir** [comment]
I found that the same problem also applies to QInfiniteScroll:
https://github.com/quasarframework/quasar/blob/78df1f4939936fdbf591d90addf950a8f42e665b/ui/src/components/infinite-scroll/QInfiniteScroll.js#L144

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.4

**Comment by cirolosapio** [comment]
here's what I meant #9427
thanks @yusufkandemir
