### ISSUE TITLE
Stop deleting the dist folder on `quasar clean`

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#10444]
**Is your feature request related to a problem? Please describe.**
It could be that there are other files in that folder. In my case a firebase config and a .bat to deploy. After running quasar clean as I wanted to move to pwa, thouse were deleted as well.

**Describe the solution you'd like**
`quasar clean` should only delete quasar items.

**Comment by pdanpdan** [comment]
The dist folder is for quasar generated files. You can copy your files in a post-build hook, or put them in another place.
