### ISSUE TITLE
Q-Separator inset item only adds left margin

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/quasar#10452]
**Describe the bug**
the inset item of q-separator adds only left margin instead of both left and right margins as described in the docs

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/lukadriel/pen/OJgLroO

**To Reproduce**
1. Add a q-separator to a component or page
2. set inset to item
3. See left margin only

**Expected behavior**
inset="item" margin should apply both on the left and right margin

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version: 3.1.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: v14.17
NPM: v6.14.13
Yarn:
Browsers: Firefox 91.0.1
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
You are looking for the regular inset instead of inset="item" (which respects QItem design)

**Comment by lukadriel7** [comment]
So I guess it is a doc error. in the docs it states:

> inset: Boolean | String
Description
if set to true, the left and right margins will be set to 16px. If set to item, the left and right margins will be set to 72px. If set to item-thumbnail, the left margin is set to 116px and right margin is set to 0px
