### ISSUE TITLE
@quasar/extras ionicons-v5 results in large chunk in bundle (>100kB parsed)

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#10456]
Hello,

I am using the svg ionicons-v5 iconset from quasar/extras in my project. It seems to be working just fine but I noticed when building my application using the analyze flag that a substential part of the vendor.js chuck is due to the quasar/extras ionicons-v5:

![image](https://user-images.githubusercontent.com/30523269/130456828-95ca3513-a24b-440f-8bc8-56f28f827990.png)
![image](https://user-images.githubusercontent.com/30523269/130457015-db5b23e9-a522-4304-bf99-086ca0b67e3f.png)

By the looks of it the complete @quasar/extras/ionicons-v5/index.js file gets bundled (651KB). I would suspect that only the icons that I am really using inside my project to be bundled inside the final build which is not the case.

## Usage inside by project
I am registered the iconSet like below in the quasar.conf.js:

**quasar.conf.js**
```
...
boot: [
    'icons'
    ...
],

framework: {
    iconSet: 'svg-ionicons-v5', // Quasar icon set
    all: 'auto',
    ...
},
...
```

The bott/icons.js file holds all the icons i might use within my project to have sort of like an abstraction layer if I ever want to change any of the icons so I do not have to replace them in all of the files by only change the reference.

**boot/icons.js**
```
import Vue from 'vue';
import {
    ionHome,
    ionCompass,
    ...
} from '@quasar/extras/ionicons-v5';

Vue.prototype.$icon = {
    home: ionHome,
    compass: ionCompass,
    ...
};
```

And then use the global prototype in my components like this:

**components/MyComponent**

```
<template>
    <div>
        <q-icon :name="$icon.home"/>
    </div>
</template>
```

As you can see I am only importing the icons from '@quasar/extras/ionicons-v5' that I really use (~200 far from the >1300 icons which get bundled). Why is this resulting in the all the icons getting bundled? Is there a way for me to decrease this size?

Thank you very much!

**Comment by Quasarman** [comment]
Wait, while writing the issue I think I have just realized that the parsed size is most likely the size of the 200 icons (~1/6 of 1300 icons) I am using...if thats the case I will close this issue and feel very embarrassed.

**Comment by metalsadman** [comment]
Use svg version if there's any and import only ones that you are going to use as webfonts cannot be tree-shaken. See the guide in doing so further in this section https://quasar.dev/vue-components/icon#svg-icons

**Comment by ontwikkelfabriek** [comment]
@Quasarman  @metalsadman 

> webfonts cannot be tree-shaken

Yes they can now in Quasar, Danny shows how:
https://www.youtube.com/watch?v=WWWEA9UGY3A   (part1)
https://www.youtube.com/watch?v=na17MMNHwkM   (part2)
