### ISSUE TITLE
QPopupProxy is not working anymore when an SVG image is provided to it's QImg parent.

### ISSUE THREAD

**Issue by pintaf** [quasarframework/quasar#10465]
**Describe the bug**
QPopupProxy is not working anymore when an SVG image is provided to it's QImg parent.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/frosty-cache-hxg41

**To Reproduce**
1. Click on first icon
2. Click on second icon

**Expected behavior**
While the two icons carry a Q-Popup-Proxy, only one of the two display it on click.
Both should display it.
The only difference is that one of the two icons is provided with an SVG icon.
It used to work on Quasar V1.

The code can be seen in src/pages/index

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version: 3.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers: Yes
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Please wrap your QImg with a div and put the QPopupProxy inside the wrapping div.
There is no way around it due to how svgs work with their children DOM elements.
