### ISSUE TITLE
Expose easing animation time in QCircularProgress and QLinearProgress

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#10464]
I found that I have "jumpy" progress because my app updates every second or so.  The easing animation on progress is a nice feature of Quasar, but to make it look really polished, it would be nice if the animation time was exposed as a variable that the developer could set.  In my case I found that if I changed the default `0.6s ease` to `1s ease` that the result looked really nice.

```
<circle 
  class="q-circular-progress__circle text-secondary" 
  fill="transparent" 
  ...
  style="transition: stroke-dashoffset 1s ease 0s, stroke 1s ease 0s;">
</circle>
```
Not sure what the proposed attribute should be called... maybe "easeInterval"?

`<q-circular-progress ease-interval="1s" value=...etc>`

**Comment by rstoenescu** [comment]
New prop (animation-speed) for QLinearProgress and QCircularProgress will be available in Quasar v2.2.5.
