### ISSUE TITLE
Module '"@quasar/app"' has no exported member 'IndexAPI'

### ISSUE THREAD

**Issue by Gastienne** [quasarframework/quasar#10488]
Hello,

I use typescript to develop an app extension but when i compile my index.ts, i got error like:

Module '"@quasar/app"' has no exported member 'IndexAPI'

This is my index.ts content:

```
import { IndexAPI } from '@quasar/app'

export = function (api: any) {
    console.log('hi')
    console.log(api)
}


```

I use @quasar/app v3.1.0

**Comment by IlCallo** [comment]
Not sure what you're trying to accomplish, but we don't export any `IndexAPI` AFAIK
There has been contributions to add types for AE API, but it hasn't been reviewed and merged yet
