### ISSUE TITLE
q-table component with Pagination slot, sorting doesn't work

### ISSUE THREAD

**Issue by Proggramar** [quasarframework/quasar#10489]
q-table component with Pagination slot, sorting doesn't work

the bug can be seen even on the same quasar page: https://quasar.dev/vue-components/table#pagination

**Platform (please complete the following information):**
Quasar Version: 2.0.4

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Browsers:

**Comment by MatthewSH** [comment]
I'm confused how you see it's not working. I see it's working fine. 

Sort by calories descending, records per page 5. The first item is `KitKat` at 518, go to the last page and the last result is  `Frozen Yogurt` at 159 calories. I just looked at the sort columns to double-check them and as far as I can tell it's working as intended.

What are you seeing being incorrectly sorted? Can you provide a codepen or something with an example of your implementation and a dataset so we can see?

**Comment by DG3D** [comment]
> I'm confused how you see it's not working. I see it's working fine.
> 
> Sort by calories descending, records per page 5. The first item is `KitKat` at 518, go to the last page and the last result is `Frozen Yogurt` at 159 calories. I just looked at the sort columns to double-check them and as far as I can tell it's working as intended.
> 
> What are you seeing being incorrectly sorted? Can you provide a codepen or something with an example of your implementation and a dataset so we can see?

No... this isn't working . 

Take a look at this one : https://codepen.io/pen/?&editors=101 
and btw, this one https://quasar.dev/vue-components/table#example--dynamic-loading-virtual-scroll 
and the one after doesn't work too ;)

**Comment by DG3D** [comment]
`
      pagination: {
        rowsPerPage: 0,
        rowsNumber: rows.value.length,
      },
`   


Remove this
`rowsNumber: rows.value.length,`
and sorting is working again

**Comment by MatthewSH** [comment]
So what you're telling me is that...it's working exactly as intended? There's a [section entirely](https://quasar.dev/vue-components/table#server-side-pagination-filter-and-sorting) for that which is explained on [pagination](https://quasar.dev/vue-components/table#pagination) 

> When pagination has a property named rowsNumber, then this means that you’ll be configuring Table for server-side pagination (& sorting & filtering). See “Server side pagination, filter and sorting” section.

All the documentation is on the page.....
![image](https://user-images.githubusercontent.com/3768988/134184801-eded98f4-d7a5-4ad5-8002-27638b1c6a36.png)
![image](https://user-images.githubusercontent.com/3768988/134184939-7f20d84c-1404-468a-8c8c-a3ec0db0cd25.png)

Literally, everything you've provided, except the invalid codepen link, is behaving exactly as it was designed and is documented ;)

**Comment by DG3D** [comment]
oops my bad, didn't check that...
