### ISSUE TITLE
QTabs: active-class

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#10494]
**Is your feature request related to a problem? Please describe.**
Now we have `active-bg-color` and `active-color` which works fine for a single type of theme (dark/light). However, when using both dark and light theme it requires an additional check to set the appropriate colors.
Quasar colors can not be formatted based on theme.

**Describe the solution you'd like**
Add prop `active-class` where we can define background and color and change them with `.body--dark`

**Comment by pdanpdan** [comment]
You can change the active colors by using some computed depending on `$q.dark.isActive`

**Comment by SharpBCD** [comment]
True. I already do this. I have some charts that are recreated based on
theme. High computing intensive.

It will be so simple to NOT change color for tabs with js but with css and
let the browser handle it.

**Comment by pdanpdan** [comment]
yes, the request is valid :)

**Comment by rstoenescu** [comment]
Feature will be available in Quasar v2.1.4 through new QTabs prop `active-class`.
