### ISSUE TITLE
Expose QUploader state

### ISSUE THREAD

**Issue by gaby64** [quasarframework/quasar#10490]
**Is your feature request related to a problem? Please describe.**
My page uses QUploader to present a singular box for managing (files on server) and uploading new files
This requires access to QUploader internals: files, queuedFiles, uploadedFiles
And the method updateFileStatus

![image](https://user-images.githubusercontent.com/2108555/131016509-e5dd9cad-d6ab-4fe1-bdf2-fefdbf00326b.png)

**Describe the solution you'd like**
Expose what is required.

this is my working implementation

#### **`uploader-core.js`**
```js
  const publicMethods = {
    pickFiles,
    addFiles,
    reset,
    removeUploadedFiles,
    removeQueuedFiles,
    removeFile,
    upload,
    abort: state.abort,
    updateFile: state.updateFileStatus
  }

  // expose public methods
  Object.assign(proxy, publicMethods)
  Object.assign(proxy, { files: state.files, queuedFiles: state.queuedFiles, uploadedFiles: state.uploadedFiles })
```

**Comment by IlCallo** [comment]
You can create your own QUploader logic, where you have access to all the internal references you need: https://quasar.dev/vue-components/uploader#supporting-other-services

**Comment by michalzyka** [comment]
> You can create your own QUploader logic, where you have access to all the internal references you need: https://quasar.dev/vue-components/uploader#supporting-other-services

What if I want to access QUploader internals through a template ref? In v1, I was able to get $refs.uploader.files for instance.
Thanks!

**Comment by gaby64** [comment]
> https://github.com/quasarframework/quasar/issues/10490#issuecomment-1180340188 What if I want to access QUploader internals through a template ref? In v1, I was able to get $refs.uploader.files for instance. Thanks!



Here is my patch I apply with [patch-package](https://www.npmjs.com/package/patch-package)

```
diff --git a/node_modules/quasar/src/components/uploader/uploader-core.js b/node_modules/quasar/src/components/uploader/uploader-core.js
index 0313c8a..1ea90d2 100644
--- a/node_modules/quasar/src/components/uploader/uploader-core.js
+++ b/node_modules/quasar/src/components/uploader/uploader-core.js
@@ -439,7 +439,8 @@ export function getRenderer (getPlugin) {
     removeQueuedFiles,
     removeFile,
     upload,
-    abort: state.abort
+    abort: state.abort,
+    updateFile: state.updateFileStatus
   }
 
   // TODO: the result of this computed, especially the dynamic part, isn't currently typed
@@ -466,6 +467,7 @@ export function getRenderer (getPlugin) {
 
   // expose public methods
   Object.assign(proxy, publicMethods)
+  Object.assign(proxy, { files: state.files, queuedFiles: state.queuedFiles, uploadedFiles: state.uploadedFiles })
 
   return () => {
     const children = [
```

Be aware that you must use .value, like this:
$refs.uploader.files.value
