### ISSUE TITLE
Extensions not found on install when quasar dev is running

### ISSUE THREAD

**Issue by Sell24** [quasarframework/quasar#10506]
**Describe the bug**
When a quasar extension is added to a project with "quasar dev" already running the extension is not found during recompile.

**To Reproduce**
1. Create a new project
2. Run 'quasar dev'
3. Install an extension such as 'QPfdViewer'
4. Replace code in App.vue to load a PDF such as [https://github.com/quasarframework/app-extension-qpdfviewer/blob/next/docs/src/examples/Html5Example1.vue](https://github.com/quasarframework/app-extension-qpdfviewer/blob/next/docs/src/examples/Html5Example1.vue)
5. Code will generate a "Failed to resolve component: q-pdfviewer"

**Expected behavior**
If I recall correctly this did not happen in V1 but I cannot be 100% sure. I was expecting the extension to be compiled in correctly. The reason I am creating this issue is that I spent a lot of time trying to figure out why extensions I installed could not be found when I added them as all indications were that it compiled correctly. So I am documenting it for others and will let the dev team decide whether to fix it or not. 

**Screenshots**
Console output of error
![image](https://user-images.githubusercontent.com/16975650/131218673-435cdaf1-51a4-45a5-a476-3918f7136867.png)

Compiler output when first added
![image](https://user-images.githubusercontent.com/16975650/131218651-cb4c92ca-3f5b-40e5-90b0-409d95eb190e.png)

Compiler output after 'quasar dev' is restarted
![image](https://user-images.githubusercontent.com/16975650/131218728-ec6172ff-4ded-49e9-b1dc-1ad3965c3ca8.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.1.0 

Quasar mode:
  - [x] SPA

Tested on:
  - [x] SPA

OS:
Node: 14.16.0
NPM: 6.14.11
Browsers: Google Chrome

**Additional context**
To fix this, just stop and restart the compiler.

**Comment by pdanpdan** [comment]
Do you know many cars that work well if you replace parts of the engine while running? :)

**Comment by Sell24** [comment]
Nice response. How am I supposed to know what Hot Reload should or shouldn't load? A simple it is not supposed to work that way would have been nice
