### ISSUE TITLE
Scroll/Resize observer debounce prop is in fact throttle

### ISSUE THREAD

**Issue by qmorek** [quasarframework/quasar#10502]
**Describe the bug**
Setting debounce prop for ScrollObserver cause that function is throttled not debounced
https://quasar.dev/vue-components/scroll-observer

**Codepen/jsFiddle/Codesandbox (required)**
With ScrollObserver with "debounce"
https://codepen.io/qmorek/pen/qBjOBPm

Scroll directive with quasar throttle from utils:
https://codepen.io/qmorek/pen/PojPoVV

Scroll directive with quasar debounce from utils:
https://codepen.io/qmorek/pen/YzQyzOa

**To Reproduce**
1. Go to codepens
2. Start scrolling text in scroll area
3. You will see that Scroll Observer with debounce prop set behaves exactly the same as scroll directive with throttling

**Expected behavior**
ScrollObserver could have both props debounce and throttle with correct behaviour. As a quick fix debounce prop should be replaced with throttle.

**Platform (please complete the following information):**
Quasar Version:
codepens are for 2.0.4, locally:
Global packages
  @quasar/cli - 1.2.1
  @quasar/icongenie - 2.3.3

Important local packages
  quasar - 1.15.23 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.2.10 -- Quasar Framework local CLI

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Operating System - Darwin(19.6.0) - darwin/x64
NodeJs - 16.6.2
NPM - 7.20.6
yarn - 1.22.11
Browsers: Chrome

Related to: https://github.com/quasarframework/quasar/issues/2169

**Comment by pdanpdan** [comment]
Hello, QScrollObserver does not use neither throttle nor debounce as they are exposed in Quasar,
It uses a sort of debounce but with a maximum time interval for waiting (as can be seen from your examples:
- debounce: trigger only after TIME has passed from the last call
- throttle: trigger on first call and then only trigger again after TIME has passed from first call
- QScrollObserver: trigger after TIME has passed from first call

**Comment by qmorek** [comment]
Hi @pdanpdan,
thank you for your answer and explanation, anyway as for me using 'debounce' as prop name here is confusing and not consistent with other componebts. For instance If you use debounce for QInput, event will fire after given amount of time passed from moment when user stopped typing and the same I would expect here...
I am aware that changing this behavior now would break existing stuff already using this, but for new users I think it would be good to update documentation explaining what in fact this property does.
