### ISSUE TITLE
Tab Scroll Arrows not showing on overflow

### ISSUE THREAD

**Issue by zagreusinoz** [quasarframework/quasar#10511]
**Describe the bug**
When using q-tabs within a q-layout and q-page-sticky the arrows to scroll left and right don't show when the tabs go off the side of the page.

It looks like the toolbar is overlapping the scrollbar.  See the screenshot.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/zagreusinoz/pen/jOwbYBW

**To Reproduce**
1. Open the codepen
2. resize the browser so that tabs are cut off by the side of the page

**Expected behavior**
As with tabs not within a sticky, there should be arrows showing when the tabs overflow the screen.

**Platform (please complete the following information):**
Quasar Version: 3.04
@quasar/app Version: ^3.0.0

**Screenshot**
<img width="548" alt="Screen Shot 2021-08-29 at 10 04 00 am" src="https://user-images.githubusercontent.com/16147285/131233949-0462ef55-a87c-4452-bd39-3634a1ae5fb0.png">

Quasar mode:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS 11.5
Node: 14.7
NPM: 6.14
Yarn: 1.22
Browsers: Chrome 92
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Tell QTabs about the max width
Either with `row` on QToolbar and `col` on QTabs  (https://codepen.io/pdanpdan/pen/qBjbBLm?editors=1010) or setting `full-with` on QTabs.
