### ISSUE TITLE
Mouse hover stuck on the q-item after v-touch-hold triggered

### ISSUE THREAD

**Issue by rubymongoose** [quasarframework/quasar#10510]
**Describe the bug**
I added v-touch-hold.mouse in q-item.
After directive triggered, mouse hover stuck on it.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/TwentySix26/pen/XWgmerY

**Expected behavior**
Expected hover to dissapear after mouse leaves q-item.

**Platform (please complete the following information):**
Quasar Version:
quasar@2.0.4

OS: Ubuntu 20.04

**Comment by rstoenescu** [comment]
It's not "stuck". The element has focus (accessibility feature). Once you focus on something else it will be ok.
