### ISSUE TITLE
Q-img's event is triggered twice

### ISSUE THREAD

**Issue by 2BJulien** [quasarframework/quasar#10522]
**Describe the bug**
When you click on a q-img object, the click event is triggered twice

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/2bjulien/pen/wveMaLP?editors=1111

**To Reproduce**
1. Add an event to the image
2. Click on the image

**Expected behavior**
Should only log once

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version: 3.1.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node 12.22.1
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Firefox 91.0.2
iOS: /
Android: /
Electron: /

**Additional context**

**Comment by metalsadman** [comment]
@2BJulien since vue 3 event falling through has been changed, you will need to use `stop` modifier to prevent event from bubbling up.

**Comment by 2BJulien** [comment]
Thank you very much. It works now!
