### ISSUE TITLE
Datepicker is not displayed correctly on Ipad (iOS theme)

### ISSUE THREAD

**Issue by blogui91** [quasarframework/quasar#1052]
### Software version

Quasar: 0.14.4
OS: Mac OS El Capitan
Node: v8.1.3
NPM: 4.6.1
Browsers: Chrome, Safari
iOS: iPad
Android: Does not Apply
### What did you get as the error?
When I try to pick a date the datepicker is very small (this was tested on an iPad), however, if I use an iPhone it works correctly.
![image](https://user-images.githubusercontent.com/5723380/32022708-cf7b9e72-b99c-11e7-9717-b23fcbff9880.png)

### What were you expecting?
The datepicker should have a full width when is used in iPads, or it should work as the native.
For example:
![image](https://user-images.githubusercontent.com/5723380/32021723-ce98d612-b999-11e7-9c3c-f24e72f7824d.png)
### What steps did you take, to get the error?
1. Just use an iPad or any device with a width greater than 600px
2. Create a modal window and add a q-datepicker (creating a variable for v-model, etc)
3. Select a date 

### Extra notes
When the datepicker is used on Desktop, it works correctly 
![screen shot 2017-10-25 at 4 00 22 pm](https://user-images.githubusercontent.com/5723380/32023013-b4478908-b99d-11e7-8a6b-c72e98c31274.png)

**Comment by fionagithub** [comment]
i had an issue about drawer cannt display well on ipad(mat theme)

**Comment by rstoenescu** [comment]
Thanks for reporting this. Will fix it.

**Comment by blogui91** [comment]
@rstoenescu Thank you! 💃

**Comment by rstoenescu** [comment]
Closing as it's been fixed for v0.15.
