### ISSUE TITLE
Quasar Broken when upgrade Electron to v13, Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by tanshuai** [quasarframework/quasar#10523]
**Describe the bug**

The Electron displays blank window of Quasar app with the following console errors:

```
Uncaught ReferenceError: require is not defined
    at eval (external "url"?61e8:1)
    at Object.url (app.js:1195)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (createSocketUrl.js?00d7:4)
    at Object../node_modules/webpack-dev-server/client/utils/createSocketUrl.js (vendor.js:2180)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.eval (client?db9c:20)
    at eval (index.js?http://0.0.0.0:8080:177)
```

which is this clean quasar app project created by quasar cli ``` quasar create quasar-v1-electron-v13 --branch v1```, just upgrade electron to version "13.2.3".

**Codepen/jsFiddle/Codesandbox (required)**
Electron mode can't reproduce via Codepen...

GitHub Repo for Bug Reproduce: 

[quasar-v1-electron-v13](https://github.com/tanshuai/quasar-v1-electron-v13)

**To Reproduce**
1. Clean project by removing node_modules & ```quasar clean```
2. Upgrade electron to 13.2.3 via Yarn. 
3. Install npm modules by ```yarn upgrade  --latest  electron```
4. Run ```quasar d -m electron```
5. Electron shows blank window with console errors.

```bash
quasar create quasar-v1-electron-v13 --branch v1
cd quasar-v1-electron-v13
quasar mode add electron
quasar d -m electron <= Work!
yarn upgrade  --latest  electron
quasar d -m electron   <= Not work !
```

**Expected behavior**
Display Quasar App Content.

**Screenshots**
![image](https://user-images.githubusercontent.com/3947852/131324468-9c9eabe4-2414-47e9-a5b8-ca8b249b3e1f.png)

**Platform (please complete the following information):**
Quasar Version:  v1.15.23
@quasar/app Version: v2.2.10

Quasar mode:

  - [ V ] Electron

Tested on:

  - [ V ] Electron

OS: MacOS 11.5.2
Node: v14.17.3
NPM: v6.14.13
Yarn: v1.22.10
Browsers:
iOS:
Android:
Electron: v13.2.3

**Additional context**

 Dev mode.......... electron
 Pkg quasar........ v1.15.23
 Pkg @quasar/app... v2.2.10
 Debugging......... enabled

**Comment by IlCallo** [comment]
Electron past v10 required breaking changes which has been applied with Qv2 release.
If you need Electron >=v11, you need to use Qv2

**Comment by nicholaszuccarelli** [comment]
@rstoenescu Any chance the breaking changes to Electron could be backported to v1?

**Comment by rstoenescu** [comment]
@nicholaszuccarelli It's all a matter of Electron specs. If you follow them and do the necessary changes, it'll work with no problems. The most important change that Electron team implemented is the contextIsolation which is enabled by default. You could disable it, although we don't recommend it (for security reasons).
