### ISSUE TITLE
Long press without exiting button should be a click

### ISSUE THREAD

**Issue by soyangel** [quasarframework/quasar#1054]
### Software version

Quasar: 0.14.6
OS: Android
Node: 8.7.0
NPM: 5.5.1
Browsers: 
iOS:
Android: 7.0
Any other software related to your bug:

### What were you expecting?

Long pressing a button, dragging and releasing (inside the button) should count as a touch event. 

### What steps did you take, to get the error?

Buttons in mobile OS (at least Android & iOS) behave like this. You can press a button, drag your finger all you want without exiting the button and release inside the button and it will be a valid click.

**Comment by rstoenescu** [comment]
Hi,

Enabling this will trigger "clicks" even when user is scrolling the page, so it's not something we want.

**Comment by soyangel** [comment]
First of all thanks for your work, Quasar is really one of the most complete UI toolkits we have used. 

Just as a curiosity, is this a limitation of Cordova itself (as it is rendering in a browser)?

I have checked and with native apps (both iOS/Android) scrolling doesn't trigger a click event on clickable widgets.

Thanks!

**Comment by rstoenescu** [comment]
Thanks for the kind words. Yep, it is. It can be overcome, but this will generate issues.
