### ISSUE TITLE
Q-Notify whitespace when only using icon

### ISSUE THREAD

**Issue by maggie44** [quasarframework/quasar#10551]
When using only an icon in Q-Notify:

```
      $q.notify({
        type: 'positive',
        icon: 'done'
      })
```
There is whitespace to the right where it is expecting a message.

Would look better if the whitespace was removed so the icon sat in the centre. 

<img width="106" alt="Screenshot 2021-09-01 at 10 53 58" src="https://user-images.githubusercontent.com/64841595/131720095-0401e238-3901-41d7-861b-861d5f02ba5a.png">

**Comment by rstoenescu** [comment]
Feature will be available in Quasar v2.1.4.
