### ISSUE TITLE
Table popup editing doesn't apply changes

### ISSUE THREAD

**Issue by ntouran** [quasarframework/quasar#10552]
**Describe the bug**
When you try popup editing in a table [as in the example](https://quasar.dev/vue-components/table#popup-editing), changing a value does not reflect in the table itself. This can be seen in the live demo itself. 

**Codepen/jsFiddle/Codesandbox (required)**
Copied directly from the demo: https://codepen.io/ntouran/pen/oNwxyKK

**To Reproduce**
1. Go to a table with popup editing as shown [in the demo](https://quasar.dev/vue-components/table#popup-editing)
2. Click a cell
3. Edit a value
4. Click set
5. Observe that the original value stays put and does not update

**Expected behavior**
The value should update after it is edited

**Screenshots**
![image](https://user-images.githubusercontent.com/53948397/131720205-a074d605-a4e0-42b0-ac8e-8ba2edc04f3b.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version: 

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by metalsadman** [comment]
@ntouran that's a bug in the example, since the rows wasn't reactive, correct example would be here https://quasar.dev/vue-components/popup-edit#with-qtable.
