### ISSUE TITLE
"input style" can't work on WeChat browser

### ISSUE THREAD

**Issue by crackxia** [quasarframework/quasar#10560]
**Describe the bug**
"input style" can't work on WeChat browser

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**

**Expected behavior**

**Screenshots**
![6a2853984aa58fed4bdf8e2da7fa2a1](https://user-images.githubusercontent.com/516438/131784395-47add478-c19e-4a3b-9571-7c4224f3b554.jpg)

**Platform (please complete the following information):**
this url https://quasar.dev/vue-components/input

Quasar mode:

Tested on:

OS: android 10
Node:
NPM:
Yarn:
Browsers: "Mozilla/5.0 (Linux; Android 10; ONEPLUS A6000 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045709 Mobile Safari/537.36 MMWEBID/9076 MicroMessenger/8.0.7.1920(0x28000737) Process/tools WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64"
iOS:
Android: android 10
Electron:

**Additional context**

**Comment by Hemingwaycn** [comment]
Dingtalk App has same problem in Android
![IMG_20210902_130503](https://user-images.githubusercontent.com/19582122/131785329-aafad1bc-712c-4488-8c8d-076a3fe44af8.jpg)

**Comment by rstoenescu** [comment]
Please configure your package.json > browserslist accordingly to the browsers that you want to support.
