### ISSUE TITLE
Request for q-tree dense property.

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#10562]
Many of popular quasar elements have dense design option. but q-tree not, that is why the app looks weird if only q-tree non-dense and others are dense. Is it possible to fix it?

**Comment by hawkeye64** [comment]
Someone will likely look into this. Possibly a good one for @pdanpdan

**Comment by rstoenescu** [comment]
The reason why QTree does not have a dense mode is that the component is already pretty compact.
But nevertheless, added "dense" prop for an "ultra-compact" mode.

**Feature is available in Quasar v2.2.4+.**
