### ISSUE TITLE
Datatable - Dynamic update problems

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1057]
### Software version

Quasar: 0.14.6
OS: Windows 7 Pro 64
Node: 6.10.2
NPM: 4.1.2
Browsers: Chrome 58.0.3029.110 (64-bit)
iOS: Does not Apply
Android: Does not Apply
Any other software related to your bug:
webpack: 3.8.1
vue: 2.5

Hi,

First of all, sorry to [cross post](http://forum.quasar-framework.org/topic/1027/datatable-dynamic-update-problems/3) here because I'm still unable to change my [password](http://forum.quasar-framework.org/topic/1028/reset-password-not-sending-email) on the quasar's forum and I will loose access to it soon.

### What did you get as the error?

I'm trying to present a tab controls follow by a data-table under. Data-table columns/data are updated according the selected tab of the tab control. In other word, columns and data row are dynamic. Data are usually fetch using axios but for here I will simulate it. 

1. The data-table is sometime **missing some columns** even if they exists in the columns definition variables.
2. The data table **is sometimes visible, other times not**. When that happens, I sometime move its declaration in the DOM order and it re-appears. In my case, I move into the tab control and other times outside. It tends to disappear between each "hot plug" changes. That's really weird.

#### Screenshot of when the datatable is **simply not rendered**
![image](https://user-images.githubusercontent.com/7946730/32057079-40932728-ba34-11e7-8bc0-46b2da1a81b2.png)

#### Screenshot of when the datatable is **missing columns**
![image](https://user-images.githubusercontent.com/7946730/32057159-70c0d882-ba34-11e7-9a26-4d505722b7ef.png)

### What were you expecting?
I'm expecting that each time I update the columns definition and row data, the datatable is first rendered 
and has ALL the required columns.

#### Screen shot of a working example
    ![image](https://user-images.githubusercontent.com/7946730/32057017-16d6668e-ba34-11e7-9801-57eadc8f5991.png)

### What steps did you take, to get the error?

This is the code to reproduce the example
```jsx
<template>

 <div>

    <q-tabs ref="tabsReportList" class="shadow-2" inverted two-lines @select="handleTabChange">

        <q-tab slot="title"
          v-for="r in tabList"
          :key="r.name"
          :name="r.name"
          :label="r.name"/>

          <q-data-table
              :data="datatableData"
              :config="configDataTable"
              :columns="dynamicDataTableColumns">
          </q-data-table>    

    </q-tabs>

    <!-- <q-data-table
        :data="datatableData"
        :config="configDataTable"
        :columns="dynamicDataTableColumns">
    </q-data-table>        -->
    
    <span v-html="simulationInfo"></span>

  </div>
</template>

<script>
import _ from 'lodash'
import { QDataTable, QTabs, QTab } from 'quasar'

export default {
  name: 'index',
  components: {
    QDataTable,
    QTabs,
    QTab
  },
  data () {
    return {
      tabList: [],

      configDataTable: {
        /* rowHeight: '1.4rem', */
        responsive: true,
        pagination: {
          rowsPerPage: 10,
          options: [5, 10, 15, 30, 50, 100]
        }
      },

      staticDataTableColumns: [
        {
          label: 'Graph',
          field: 'graph',
          /* width: '2rem', */
          format () {
            return `<i class="material-icons" style="font-size: 1.6rem">show_chart</i>`
          }
        },
        {
          label: 'Name 1',
          field: 'name1'
          /* width: '2rem', */
        },
        {
          label: 'Name 2',
          field: 'name2'
          /* width: '2rem', */
        }
      ],

      dynamicDataTableColumns: [],

      datatableData: [],

      simulationInfo: ''
    }
  },
  computed: {},
  methods: {
    handleTabChange (activeTabName) {
      // Generate dynamic new columns
      const countDynamicColumns = 1 + Math.floor(Math.random() * 10)
      const newDynamicColumns = _.times(countDynamicColumns, () =>
        _.random(35).toString(36)
      ).reduce((acc, cur) => {
        acc.push({
          label: cur,
          /* width: '1.5rem', */
          field: cur
        })
        return acc
      }, [])

      // Merge static columns with new dynamic column
      console.log(`staticDataTableColumns :${JSON.stringify(this.staticDataTableColumns)} \n--> (${this.staticDataTableColumns.length} columns)`)
      console.log(`newDynamicColumns :${JSON.stringify(newDynamicColumns)} \n--> (${newDynamicColumns.length}) columns`)
      this.dynamicDataTableColumns = this.staticDataTableColumns.concat(newDynamicColumns)
      console.log(`dynamicDataTableColumns :${JSON.stringify(this.dynamicDataTableColumns)} \n--> (${this.dynamicDataTableColumns.length}) columns`)

      // Simulate new data
      const rowsCount = 5
      const that = this
      var newData = []
      for (let i = 0; i < rowsCount; ++i) {
        let r = {}
        for (let i = 0; i < that.dynamicDataTableColumns.length; ++i) {
          r[that.dynamicDataTableColumns[i].field] = Math.floor(
            Math.random() * 200
          )
        }
        newData.push(r)
      }
      this.datatableData = newData
      console.log(`datatableData :${JSON.stringify(this.datatableData)} \n--> (${this.datatableData.length}) rows`)

      // Update simulation information
      let simInfo =
        `Column count :${this.dynamicDataTableColumns.length} (` +
        _.map(this.dynamicDataTableColumns, 'field').join(',') +
        ')'
      simInfo += `<br>Rows count :${this.datatableData.length}`
      this.simulationInfo = simInfo
    }
  },
  created () {
    // Simulate dynamic tabs entries
    this.tabList = Array.apply(null, Array(5)).reduce((acc, cur, idx) => {
      acc.push({
        name: `Tab-${idx.toString()}`
      })
      return acc
    }, [])
  }
}
</script>
```
#### How the example works
1. You click on a tab and then the data-table will get new dynamic columns definition plus new data rows.
2. On the debug pane of Chrome, I output : 
    * The list of static columns (*those are not changing dynamically*)
    * The list of new dynamic columns (*those are changing dynamically*)
    * The final columns array resulting of the merge/concat of (static + dynamic columns)
    * The number of new generated rows
3. You will notice shortly that sometime the data-table is not rending **ALL** the columns present in the `dynamicDataTableColumns` variables. And sometime the data-table is not rendered at all.

Screenshot of missing columns
![image](https://user-images.githubusercontent.com/7946730/32057393-0f864524-ba35-11e7-84c0-dbf2902b697e.png)

As you can see, the datatable is now suppose to have 7 columns `graph, name1, name2, s, r, z, 8` but only these are visible `graph, name1, name2, 8`. Where are `s, r, z` columns ???

Maybe its my mistake, but maybe it a real bug ? 

I read that Quasar is going to release the 0.15 version but do you have an approximative release date or a way to test the new data-table implementation ? I already tried other frameworks first as (_element.io_) but I was not impressed by their responsive on mobile so I abandoned it. Now I was undecided between (Quasar / Vuetify). I finally choose Quasar for : 
* Compatibility with Cordova
* Responsive first and layout + component works all flawlessly on mobile
* Tons of components

What **was missing** before I start using it : 
* i18n for framework's components. I'm already using vue-i18n for the rest.

What is **NOW missing after I tried it** : 
* The data-table is not enough customizable, not enough data manipulation function 
    * Custom function search getting row by row
    * We can't create a column not associated to a specific field (Ex: a link),

After trying many framework, I'm now running out of time and the data-table is a critical component for me so If I can't get it work shortly I will regrettably have to migrate to another framework :(

Best regards,

**Comment by rstoenescu** [comment]
Hi, This won't be a problem in v0.15 datatable revamp, so closing. Thanks for the detailed description!

**Comment by purell** [comment]
Well, this is a really quick response @rstoenescu, thank you for your time.

But I'm out of time actually. Do you have a workaround in the mean time ? Or, can you explain me what is going on so I can found by myself a workaround ? This component is critical in my choice a framework.

If I can't fix it permanently or temporary util the new release, I will have to switch to another framework and I would like to avoid that. I even don't know if the bug is related to quasar or dom rendering of vue.js ? Thus, migrating to another framework like vuetify could probably bring back this problem and new ones also.

**Comment by purell** [comment]
Hi @rstoenescu, 

Sorry to annoying you again but if I well understand, I could use the dev branch from NPM and use it until you release quasar 0.15 ? This will allow me to test the new datatable ? But I will be on my own to make things work as some news element as QTable still not have example yet. Is I'm right ?

Best regards,
