### ISSUE TITLE
date picker multiple selection

### ISSUE THREAD

**Issue by the-pesar** [quasarframework/quasar#10581]
**When I select day in date picker multielection, it returns to the first month**
**Please test**
`https://quasar.dev/vue-components/date#multiple-selection`

https://user-images.githubusercontent.com/85296952/132205738-cfd1b06e-6637-48be-adfd-fad11c1fcbde.mp4

_**how to solve this problem :( ?**_

// thanks

**Comment by ontwikkelfabriek** [comment]
@pesarboy 

This behavior of Q-date for this specific case isn't very user friendly indeed.

**Comment by hawkeye64** [comment]
@pesarboy Have you tried the QCaendar app extension? You will have to build your own nav and year picker though

https://qcalendar.netlify.app/developing/qcalendarmonth-minimode/minimode-selected-dates

**Comment by JeRabix** [comment]
I can try fix this?

**Comment by JeRabix** [comment]
I did not understand why, when changing value, the last element from the array was always taken, you can take the last one, I looked at all the examples that are in the documentation and in my opinion it does not break the work in other cases

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.2.3

**Comment by MaVlaSa** [comment]
@JeRabix To take the last element is not good solution if i want to sort model-value in update event.
What about the idea :
```
watch(() => props.modelValue, v => {
      if (lastEmitValue === v) {

        lastEmitValue = 0
      }
      else {
        //const { year, month } = getViewModel(innerMask.value, innerLocale.value)
        const { year, month } = viewModel.value
 updateViewModel(year, month)
      }
    })
```

**Comment by qashier-ray-foo** [comment]
I'm having the same issue, I do not want to focus on the last element when unselecting a date because I still want to select other dates of the same month. This behavior is unnecessary and should be removed.
