### ISSUE TITLE
Context menu on nested elements doesn't work correctly.

### ISSUE THREAD

**Issue by enjoycod1ng** [quasarframework/quasar#10583]
**Describe the bug**
Context menu on nested elements doesn't work correctly.

This works on Codepen but does not work on jsFiddle.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mastercodingbear/pen/QWgKRrw
https://jsfiddle.net/24djun1g/1/

**To Reproduce**
1. Click on parent element - green area
2. Click on child element - blue area
3. See error - context menu on parent element still appear.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/84164835/132218784-2fbb98af-f160-4296-b861-756bb30f339f.png)

**Platform (please complete the following information):**
Quasar Version: latest
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by hawkeye64** [comment]
Your CodePen works for me Using a mouse). Is this an issue with touch screens?

**Comment by enjoycod1ng** [comment]
Did you check below `jsFiddle` link?

**Comment by hawkeye64** [comment]
> This works on Codepen but does not work on jsFiddle.

I just noticed that. This is very curious.

**Comment by enjoycod1ng** [comment]
Yeah. I think that's the correct action of this code(jsFiddle) but on Codepen it works well. Really curious.  :(

Is there any other way to implement this operation?

**Comment by hawkeye64** [comment]
Instead of QMenu, use event (oncontextmenu) that calls JavaScript where you can use QDialog plugin (not component) instead.

**Comment by pdanpdan** [comment]
The bug report is correct - in Q1 the click outside works as expected and closes the menu, while in Q2 the menu stays.

**Comment by hawkeye64** [comment]
@pdanpdan I know it's a bug. Why does it work on CodePen as expected, but not on jsfiddle?

**Comment by pdanpdan** [comment]
because one is Q1 and the other Q2

**Comment by enjoycod1ng** [comment]
> because one is Q1 and the other Q2

Could you explain what is `Q1` or `Q2` ?

**Comment by MilosPaunovic** [comment]
Q1 is the Quasar version which uses Vue 2 and Quasar 2 is current version utilising Vue 3.

**Comment by hawkeye64** [comment]
I updated the CodePen to be current versions: https://codepen.io/Hawkeye64/pen/bGRgjZe?editors=1010

**Comment by enjoycod1ng** [comment]
So is there any other way to solve this problem?

**Comment by hawkeye64** [comment]
Looks like a bug to me introduced in v2

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.3.
Actually fixed more than reported here.

One thing to note: remove `@touchstart.stop @contextmenu.stop` on the inner DIV. No longer needed (for both context-menu and non context-menu nested QMenus).
