### ISSUE TITLE
Having a hashtag (#) in the project folder path prevents webpack from working

### ISSUE THREAD

**Issue by felizk** [quasarframework/quasar#10591]
This is just a quick one I noticed on my Windows machine.

I created a new Quasar project in a folder "C:\#repos\quasarproject" and `quasar dev` would fail with:
`Error: Cannot find module 'C:\Dev\#repos\qplayer\node_modules\@quasar\app\lib\webpack\loader.js.transform-quasar-imports.js'`

Moving the project folder out of the #repos folder fixed it.

**To Reproduce**
1. On Windows, create a folder '#repos' in c:\
2. run 'quasar create myproject' in the #repos folder
3. run 'quasar dev' from the myproject folder 

**Expected behavior**
Maybe a warning that the path isn't supported if nothing else?

**Comment by pdanpdan** [comment]
You could better try putting all your projects inside a `c:\con` folder :)
Common, you can find better names.

**Comment by felizk** [comment]
Well yeah, I am going to just move my project and move on with my life. Just thought this error message is really obscure and may well trip up someone else in the future, but if you don't give a shit that's fine too.

**Comment by hawkeye64** [comment]
@felizk I think the issue here is outside of Quasar's control. You can see that this is a webpack loader issue. If you really care, go file an issue on that repo.
