### ISSUE TITLE
QUploader should not upload file when :disable="true"

### ISSUE THREAD

**Issue by afilic** [quasarframework/quasar#1059]
### Software version

Quasar: 0.14.6
OS: Ubuntu
Node:
NPM:
Browsers: Chromium, Firefox
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Uploader fires regardless of disable property.

### What were you expecting?
When disable is true upload shoud be disabled. Selecting file should also be disabled.
### What steps did you take, to get the error?

            <q-uploader
              :url="$http.defaults.baseURL+'/rn/doc_up'"
              :float-label="$t('lab.Upload')"
              :disable="validation.hasError()"
              :headers="{authorization: 'Bearer ' + accessToken}"
              :additionalFields="[
                { name: 'rn', value: osn.rn },
                { name: 'voz', value: osn.voz },
                { name: 'naz', value: osn.naz },
                { name: 'pod', value: pod_id },
              ]"
            />

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.7
