### ISSUE TITLE
focus() not work on q-select

### ISSUE THREAD

**Issue by the-pesar** [quasarframework/quasar#10601]
```
<q-select @click.enter="testRef2.focus()" ref="testRef1"></q-select>
<q-select ref="testRef2"></q-select>
```
**focus() event not work on q-select but right in q-input :(((**

how to solve this problem ?

**Comment by pdanpdan** [comment]
What do you mean? What is @click.enter.
Please reopen with a codepen and a description of what you do, what you expect to happen and what is wrong.
And fill the issue template.

**Comment by the-pesar** [comment]
v-on:click.enter="" == @click.enter=""
