### ISSUE TITLE
useing quasar create <folder_name> be defeated

### ISSUE THREAD

**Issue by zhengju1893** [quasarframework/quasar#10603]
![image](https://user-images.githubusercontent.com/23161548/132499015-0e404438-f7fa-4c6a-b23a-de2d1a2dbe0e.png)

It is the same error many times in a row, as well as changing NPM and PNPM

error-code:
[3/5] Fetching packages...
error https://registry.yarnpkg.com/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining/-/plugin-bugfix-v8-spread-parameters-in-optional-chaining-7.15.4.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EPERM: operation not permitted, open 'C:\\Users\\webSong\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining-7.15.4-dbdeabb1e80f622d9f0b583efb2999605e0a567e-integrity\\node_modules\\@babel\\plugin-bugfix-v8-spread-parameters-in-optional-chaining\\README.md'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

 yarn install FAILED... Possible temporary npm registry issues?
 Please try again later...

**Comment by pdanpdan** [comment]
Hello.
Either npm is down or you have a network filter.

**Comment by MilosPaunovic** [comment]
https://status.npmjs.org/

Seems like it's the second one from the answer Dan wrote.

**Comment by zhengju1893** [comment]
Ok, I'll try. Thank you
