### ISSUE TITLE
Two QTabs With QRouteTab Inside Them In One Layout Doesn't Work!

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1061]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: 8.8.1
NPM: 5.4.2
Browsers: Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
The QRouteTab of the second QTabs that used at the "footer" slot not work properly without showing errors.
### What were you expecting?
When clicking on the second QTabs tabs works like the first one in the "navigation" slot. 
### What steps did you take, to get the error?
Here is my layout:

```
<template>
  <!-- Configure "view" prop for QLayout -->
  <q-layout>
    <!-- Header -->
    <q-toolbar color="purple-14" slot="header">
      <q-toolbar-title class="text-right">
        Title
      </q-toolbar-title>
    </q-toolbar>
    <q-tabs color="purple-14" slot="navigation" class="shadow-2" align="justify">
      <q-route-tab to="/c/shirts" exact slot="title" label="shirts" />
      <q-route-tab to="/c/dresses" exact slot="title" label="dresses" />
      <q-route-tab to="/c/shoes" exact slot="title" label="shoes" />
    </q-tabs>

    <!-- Page -->
    <router-view />

    <!-- Footer -->
    <q-tabs color="purple-14" slot="footer" class="shadow-2" align="justify">
      <q-route-tab slot="title" to="/account" exact icon="person" label="account" />
      <q-route-tab slot="title" to="/cart" exact icon="local_mall" label="cart" />
      <q-route-tab slot="title" to="/wishlist" exact icon="favorite" label="wishlist" />
      <q-route-tab slot="title" to="/search" exact icon="search" label="search" />
      <q-route-tab slot="title" to="/" exact icon="home" label="home" />
    </q-tabs>
  </q-layout>
</template>

<script>
import {
  QLayout,
  QToolbar,
  QToolbarTitle,
  QList,
  QListHeader,
  QItem,
  QItemSide,
  QItemMain,
  QTabs,
  QRouteTab
} from "quasar";

export default {
  data() {
    return {};
  },
  directives: {},
  components: {
    QLayout,
    QToolbar,
    QToolbarTitle,
    QList,
    QListHeader,
    QItem,
    QItemSide,
    QItemMain,
    QTabs,
    QRouteTab
  }
};
</script>

<style>

</style>
```
The QTabs in the navigation slot works perfectly but the QTabs in the footer slot doesn't work properly.

**Comment by MohammedAl-Mahdawi** [comment]
After a lot of debugging, I think this bug is related to the home route "/" if I made it like "/home" the code looks like get worked!

**Comment by rstoenescu** [comment]
Hi, Yes, it matters how you configure routes for Vue Router. Remember you can use children for any route, so you don't necessarily need to make index page be /home.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu, thank you for your reply, yes you are right, there is no issue at all, it was my mistake, however for anyone that may face such issue here is the thing that was causing the issue, what I did is creating many layouts with different headers but the same footer replicates in every layout, this is incorrect, if you want to use a footer that appears on every page and use tabs with it then put that footer on a layout that still the same on all pages, don't create many layouts that replicate the footer.
