### ISSUE TITLE
Optional week numbers in QDate component

### ISSUE THREAD

**Issue by underdoeg** [quasarframework/quasar#10618]
**Is your feature request related to a problem? Please describe.**
We are using quasar for an in house project management solution and a lot of planning happens in weeks of the year. having this extra info in the QDate component would reduce the time we have to look up the corresponding week.

**Describe the solution you'd like**
See this mockup in a forum thread https://forum.quasar-framework.org/topic/6330/qdate-to-show-week-number

**Describe alternatives you've considered**
For the moment we display the week number of the selected date in the footer area.
![image](https://user-images.githubusercontent.com/243820/132658639-ae8b134f-0125-416d-a47b-f81dbfbf3c45.png)

**Comment by ontwikkelfabriek** [comment]
@underdoeg 

Have you considered the official Quasar calendar plugin? It has a **lot** more features then the q-date component.

https://github.com/quasarframework/quasar-ui-qcalendar

**Comment by hawkeye64** [comment]
@underdoeg  Adding to what @ontwikkelfabriek said, if it's for Quasar v2, make sure yu look at the `next` branch.

here are the docs: https://qcalendar.netlify.app/

https://qcalendar.netlify.app/developing/qcalendarmonth-minimode/minimode-workweeks

One thing about QCalendar is it tries to be less opinionated about things, so you have to build your own nav interface and call the functions in a ref for `prev()` and `next()`

![image](https://user-images.githubusercontent.com/10262924/132697518-d5b7aaaf-b67d-4e2a-b7f2-5a02bc1134ce.png)

**Comment by underdoeg** [comment]
Thank you. I will look into it
