### ISSUE TITLE
Error when using QRouteTab with nested routes and props

### ISSUE THREAD

**Issue by gauravjhs** [quasarframework/quasar#10610]
**Describe the bug**
Quasar throwing error when we change routes using QRouteTab in a nested route scenario.

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/gauravjhs/quasar_issue_repo

**To Reproduce**
1. Run The project
2. Click on the Home button to change the routing
3. Error thrown in the console

**Expected behavior**
QRouteTab should not check for Prop when it is not required.

**Screenshots**
![image](https://user-images.githubusercontent.com/10832473/132556502-cbedb802-428f-4acd-a62d-f56b3383bd70.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version:

Quasar mode:
  - [*] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [*] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows
Node: 14.17.5
NPM: 7.8.0
Yarn: 1:22.5
Browsers: Chrome

**Comment by pdanpdan** [comment]
I fail to see where are you using QRouteTab
In what file?
And it looks from your error that you are trying to use a route with required params without the params. The route must be valid, sorry.

**Comment by gauravjhs** [comment]
Please check file TestKPIDetailsDashboard.vue. There are 2 routes that require a param and one route without param. When we migrate from param route to non-param route, it throws an error of missing param. 
This error is thrown if I am using QRouteTab and works fine with RouterLink in exactly the same scenario.  

![image](https://user-images.githubusercontent.com/10832473/132626968-45fcd615-4600-4279-9b8a-5a3967edd01f.png)

**Comment by pdanpdan** [comment]
As already mentioned, I fail to see where is that file in the repo.

**Comment by gauravjhs** [comment]
My apologies. I have updated that repo.

**Comment by zagreusinoz** [comment]
I'm also experiencing this issue.  @gauravjhs did you find a workaround?

**Comment by gauravjhs** [comment]
@zagreusinoz  We have created a wrapper around RouterLink to mimic limited functionality similar to QRouteTab. It works as a short-term solution and we can easily revert back once we are able to resolve this.

**Comment by zagreusinoz** [comment]
Thanks @gauravjhs .  Could you share what you're using so I don't have to reinvent the wheel?

**Comment by gauravjhs** [comment]
[CustomRouteTab.txt](https://github.com/quasarframework/quasar/files/7335766/CustomRouteTab.txt)
This is customized to our use case, but you can edit it accordingly and use it.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.3.

**Comment by gauravjhs** [comment]
Many thanks @rstoenescu
