### ISSUE TITLE
QRange disable specific range

### ISSUE THREAD

**Issue by mortezasabihi** [quasarframework/quasar#10626]
**Is your feature request related to a problem? Please describe.**
A prop to disable specific range in QRange component.

**Describe the solution you'd like**
`<q-range :min="1" :max="24" :disabled-range="{min: 10, max:12}"  />`
User couldn't select range from 10 to 12.

**Comment by pdanpdan** [comment]
That is too specific and strange use case, sorry.
You should change the model based on your desired rules when you end up in that region.
For visual aspect use the markers slots available from v2.4.0/v1.17.0
