### ISSUE TITLE
QRange multi-range support

### ISSUE THREAD

**Issue by mortezasabihi** [quasarframework/quasar#10625]
**Is your feature request related to a problem? Please describe.**
Adding multi-range support to QRange component

**Comment by ontwikkelfabriek** [comment]
@mortezasabihi 

> Adding multi-range support to QRange component

Could you specify what you consider a `multi-range` Qrange? Preferably with a link to page with a functional multi-range component/widget/whatever.

**Comment by mortezasabihi** [comment]
@ontwikkelfabriek 

![image](https://user-images.githubusercontent.com/35567646/133084816-fb28de8e-0026-4239-bdfa-c0c3f524d1e7.png)


 I wanna have an option to have multiple triggers to select multiple ranges and each range couldn't have a conflict with each other.

**Comment by pdanpdan** [comment]
Sorry, it is too complex and non-standard case.
If you can think of any criteria to select one or another of the ranges you can try placing 2 QRange over each other and bring to front the one you want, but I cannot think of any such criteria
