### ISSUE TITLE
Warning shows Qtabs prop onUpdate:modelValue type check failed

### ISSUE THREAD

**Issue by blairfrontend** [quasarframework/quasar#10632]
**Describe the bug**

Pass a method to Qtabs as an event listener of update:model-value.
The qtabs works fine.
<img width="338" alt="截圖 2021-09-10 下午4 13 47" src="https://user-images.githubusercontent.com/43362250/132822623-2edb1d5d-dcaa-4724-83f6-e2b718dadce9.png">
<img width="608" alt="截圖 2021-09-10 下午4 14 08" src="https://user-images.githubusercontent.com/43362250/132822609-07748515-8866-4e58-9e30-2825e97faac3.png">

But system keeps showing a warning that the prop type check failed because the value it received was an array.
Per console, there's another unknown function.
Suppose the array and unknown function was created and passed by Quasar.
But I couldn't reproduce it in Codepen/jsFiddle/Codesandbox.
Could you please help check if there's any reasons that this is happening? Thank you.
<img width="460" alt="截圖 2021-09-10 下午4 13 10" src="https://user-images.githubusercontent.com/43362250/132822630-e77aa177-4d09-4e17-8232-357b1022ad77.png">
<img width="442" alt="截圖 2021-09-10 下午4 18 16" src="https://user-images.githubusercontent.com/43362250/132823130-2fabb341-b52f-4468-88b5-5c75886722b5.png">

**Expected behavior**
No warning showed.

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version: 3.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS 10.15.4
Node: 14.16.1
NPM: 6.14.12
Browsers: Chrome 92.0.4515.159 / Safari 13.1

**Comment by IlCallo** [comment]
May it be because you're defining both `v-model` and `@update:model-value`?
Try removing `v-model`, adding `:model-value="currentTab"` and update `currentTab` into your custom update handler

**Comment by blairfrontend** [comment]
It works! Thanks a lot. 😃
