### ISSUE TITLE
tab-panel in drawer no longer responsive!

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#10639]
**Describe the bug**

My app has a left drawer with various content contained in tab-panels.
The width is fixed and set in MainLayout like this:
`

          <div class="column no-wrap" :style="{ width: panelWidth + 'px'}">
            <q-tab-panels
              keep-alive
              animated
              transition-prev="slide-right"
              transition-next="slide-right"
              v-model="navPanel"
            >
`
Before upgrading to Quasar 2, all worked fine, but since upgrading, content in any of the tab-panels are not fitting within the containing div's width after the drawer is minimized and expanded again.
When the app first starts, it's fine, but if the drawer is set to mini, and then opened again, the problem shows.
I'm showing two screen-shots below to show the difference, and I made a stripped-down version to show it at
[codeSandbox](https://codesandbox.io/s/quasar-q-scroll-area-problem-od73m?file=/quasar.conf.js)...  (takes a while to load)

The 'q1scrollarea' shot shows how it looked with Quasar V1 - the drawer content fits nicely within the containing div column.
The 'q2scrollarea' shot shows new scrollarea__container and scrollarea__content.absolute divs, and the contents are now the full width of the window, instead of fitting within the container div.

I've tried various tricks to fix this, but I'm stumped. If this new behaviour is not a bug, I'd appreciate some guidance to solve the problem. Thanks.

Screen-shots:
With Quasar 1 (works perfectly):
![q1scrollarea](https://user-images.githubusercontent.com/45148066/132883276-3936b49f-64c7-4dd4-8406-194c63d373b6.jpg)
With Quasar 2 (scroll-area content overflows horizontally):
![q2scrollarea](https://user-images.githubusercontent.com/45148066/132883055-3e636b79-e5e8-48c7-bdfa-732f08ec9fca.jpg)

**Platform
Quasar Version: 2.0.4
@quasar/app Version: 3.1.0

Quasar mode:
  - [ ] SPA
Tested on:
  - [ ] SPA

OS: Windows 10
NPM: 7.22.0
Browsers: Chrome

**Comment by CrawfordW** [comment]
Added codeSandbox demo to show the problem:
[here:](https://codesandbox.io/s/quasar-q-scroll-area-problem-od73m?file=/quasar.conf.js)
(takes a while to load)

**Comment by CrawfordW** [comment]
Realized it's not a scroll-area problem. Happens when the drawer content is just a plain div.

**Comment by CrawfordW** [comment]
More general problem! Tab-panel content is no longer responsive!

**Comment by pdanpdan** [comment]
In Qv2 the QScrollArea scrolls both vertically and horizontally - so if you want to not have horizontal scroll you should limit the width of the content

**Comment by CrawfordW** [comment]
Problem for me is the page with the scroll area lives in a splitter pane which the user can resize horizontally. So the width is not known and hard to get dynamically. It would be better if QScrollArea had an option to only scroll vertically like it used to.

**Comment by pdanpdan** [comment]
You can put a v-model on QSplitter
Or if you make a codepen I can show you

**Comment by CrawfordW** [comment]
Sounds interesting...
But I have pages on tabs in splitters, so quite a few levels to get to the scroll-area. I need to somehow get the current dynamic width of the splitter pane - how can a v-model help? It would be much easier if I could just set the scroll-area for vertical only scrolling.

**Comment by pdanpdan** [comment]
It would have spared a lot of time if you creted a codepen
https://codepen.io/pdanpdan/pen/oNGPgwW?editors=1010

**Comment by CrawfordW** [comment]
Sorry, I'm slow and building a codepen never seems to work for me with a complex setup.
Thanks for your help - I really appreciate the excellent support!
