### ISSUE TITLE
qEditor(WYSIWYG) - problem with toolbar slots (missing caret; problems with runCmd - missing range selection)

### ISSUE THREAD

**Issue by eLeszek** [quasarframework/quasar#10635]
**Describe the bug**
1. After migrate to quasar v2 i have problem that is also visible on yours page (https://quasar.dev/vue-components/editor#example--using-toolbar-slots).  Using eg  edit.caret.restore() methods throws error because editor refer property "caret" is not visible.
2. After migrate to quasar v2 don't works eg  changing color. I'm using  toolbar slots for this. I'm using q-btn with q-popup-proxy contains q-color component. On change q-color is run method runCmd('foreColor', color).  On v1 I did not have to use edit.caret.restore() and all works. I tried to do like your  example from yours page mentioned above (q-btn-dropdown) and it also not works. But I noticed that when I'm using button (q-btn) without menu or popup changing color works (of course, the text to change color is marked in advance). So  still in v2 caret.restore() is not not needed in this case, but is problem with missing range selection when we click on menu or popup button from toolbar. If you can, add an example of changing the color of the text

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/editor#example--using-toolbar-slots

**To Reproduce**
1. Go to https://quasar.dev/vue-components/editor#example--using-toolbar-slots
2. Click on Token select
3. Select item
4. See error in console

**Screenshots**
![Zrzut ekranu z 2021-09-10 14-51-12](https://user-images.githubusercontent.com/30385390/132856037-040c9183-a677-45cc-9c72-7b23b676fd7a.png)
![Zrzut ekranu z 2021-09-10 14-53-01](https://user-images.githubusercontent.com/30385390/132856194-c83f6879-6996-4517-9d81-ff43524d0afe.png)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.4.
