### ISSUE TITLE
[Feature] Change datetime picker to datetime input

### ISSUE THREAD

**Issue by spaceywolfi** [quasarframework/quasar#1064]
I think it would be nice if people, especially desktop users could manually type in the date they would like in the datetime picker (thus making the calendar popup an optional feature)

I am thinking in the direction of this example:
http://haixing-hu.github.io/vue-datetime-picker/demo.html
even though in the above link the manual input is not very precise

**Comment by nueko** [comment]
have u this issue #1038 on setup quasar date picker?

**Comment by spaceywolfi** [comment]
@nueko no i do not have that issue

**Comment by PMeira** [comment]
The date picker from Angular Material is another example that allows typing directly:

https://material.angular.io/components/datepicker/overview

On desktop this is especially useful as using copy-paste is more common. The Quasar Color Picker, for example, allows typing/pasting a new color code and can be a time saver for the end user.

**Comment by rstoenescu** [comment]
This will get in, you just need to be patient.

**Comment by lxmfly123** [comment]
Really need this feature.

**Comment by rstoenescu** [comment]
Done for future v1.0.
