### ISSUE TITLE
Bug - Q-Select - clearable not working well with text autocomplete

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10656]
Using the example from your documents, adding "`clearable`" to the `<q-select>`

```
<!--
  Forked from:
  https://quasar.dev/vue-components/select#example--text-autocomplete
-->
<div id="q-app" style="min-height: 100vh;">
  <div class="q-pa-md">
    <div class="q-gutter-md row">
      <q-select clearable
        filled
        :model-value="model"
        use-input
        hide-selected
        fill-input
        input-debounce="0"
        :options="options"
        @filter="filterFn"
        @input-value="setModel"
        hint="Text autocomplete"
        style="width: 250px; padding-bottom: 32px"
      >
        <template v-slot:no-option>
          <q-item>
            <q-item-section class="text-grey">
              No results
            </q-item-section>
          </q-item>
        </template>
      </q-select>
    </div>
  </div>
</div>
```
```
const { ref } = Vue

const stringOptions = [
  'Google', 'Facebook', 'Twitter', 'Apple', 'Oracle'
].reduce((acc, opt) => {
  for (let i = 1; i <= 5; i++) {
    acc.push(opt + ' ' + i)
  }
  return acc
}, [])

const app = Vue.createApp({
  setup () {
    const model = ref(null)
    const options = ref(stringOptions)

    return {
      model,
      options,

      filterFn (val, update, abort) {
        update(() => {
          const needle = val.toLocaleLowerCase()
          options.value = stringOptions.filter(v => v.toLocaleLowerCase().indexOf(needle) > -1)
        })
      },

      setModel (val) {
        model.value = val
      }
    }
  }
})

app.use(Quasar, { config: {} })
app.mount('#q-app')

```

1st Bug
I don't know why this example in  https://quasar.dev/vue-components/select#example--text-autocomplete uses ":model-value" instead of "v-model". So clearable won't work with this example.

2nd Bug
"v-model" can be replaced with ":model-value", although I don't know it is a proper way or not. 
Now the clear button can work with the selected item.
However, typing could not be cleared.

https://user-images.githubusercontent.com/44498510/133206639-8e19c13a-a99a-4dca-ac2e-aeaed22352c1.mp4

Instead of `@input-value="setModel"`, can you provide the `v-model:inputValue` for Quasar v2? Vue3 supports mutiple v-model.

**Comment by metalsadman** [comment]
not a bug, it's simply because you have to update the model manually hence `:model-value...`, like so if you want to use the example with `clearable` prop, then make use of the `@clear` event. ie. `@clear="model = null"`.
