### ISSUE TITLE
QSelect with use-input & use-chips doesn't refocus on input field after removing a chip

### ISSUE THREAD

**Issue by syldman** [quasarframework/quasar#10654]
Steps to reproduce:
On the [Using menu and filtering](https://quasar.dev/vue-components/select#using-menu-and-filtering) add a few items and clear one. Input field has focus while adding, but loses focus on the first chip removed. Focus is regained on clicking.

**Comment by rstoenescu** [comment]
Hi,

Can't reproduce. Can you specify more details, like what browser are you using and on what platform? Thanks.

**Comment by hawkeye64** [comment]
I can reproduce this. I think maybe the steps are not clear.
Just type "google" in the input. Hit enter. It now becomes a chip. Press backspace, the chip disappears. You can type something else. This is all good.
Here is the issue. After the Google chip appears, delete it with the mouse. You can no longer edit with the keyboard. Clicking with mouse closes the selection, so now you have to click a second time to be able to edit again.
The issue then is that when deleting with the mouse, the input loses focus. It doesn't matter how many chips you have, just using the mouse to delete one causes this behavior.

**Comment by rstoenescu** [comment]
Then this is how it's supposed to happen. You click on something (so focus on something else).

We could add code to refocus on the input, but this would add a lot of complexity to the already complex focusing system between QField/QInput/QSelect/etc. The refocusing on this ticket's scenario looks like it's easy to implement, but it's actually far from that and would possibly introduce other bugs. And it's not worth it, as long as the user is already with his hand on the mouse and the natural behavior of clicking on something is to change focus to that something.

Please reopen if I missed anything or the removal of chips is not done with the mouse like we assumed.

**Comment by pdanpdan** [comment]
This is a regression from v1 (https://v1.quasar.dev/vue-components/select#using-menu-and-filtering)

**Comment by rstoenescu** [comment]
@pdanpdan Have you reproduced with v2 (cause I can't without the mouse) or can shed some light on what the reporter is actually experiencing? And if so, please PR to v2.

**Comment by hawkeye64** [comment]
When a chip is deleted, can you grab the current focus and put it back when chip deletion is done? Before the deletion, one can see the caret at the end of the chips. After deletion, you would expect the caret to still be visible at the end of the chips or when all chips have been deleted.
