### ISSUE TITLE
Bug - Q-Select with use-input - incorrect filtered list after clicking the page

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10659]
https://user-images.githubusercontent.com/44498510/133215458-e5f4a280-4b36-4be3-87b6-6018d9f34d0d.mp4

https://quasar.dev/vue-components/select#example--text-autocomplete

If the page outside the input is clicked, the filtered list would reset.
Is this a feature? but for an ordinary user, it seems weird.

**Comment by pdanpdan** [comment]
That's the expected behavior- the filter is always reset on open. In the case in the example the input is used both to display the current value and to filter - but it displays the current value.

**Comment by gaby64** [comment]
maybe have a flag for must match, value can only become a matching option, otherwise, discard on blur.
