### ISSUE TITLE
Conditional QTooltip causes TypeErrors

### ISSUE THREAD

**Issue by Sumurai8** [quasarframework/quasar#1065]
### Software version

Quasar: 0.14.6
Vue: 2.5.2
OS: Windows 10
Node: 6.11.4
NPM: 6.11.4
Browsers: Chrome

### What did you get as the error?
You get the following two errors (depending if the tooltip is added or removed from the dom)

[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'removeChild' of null"
[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'removeEventListener' of null"

### What were you expecting?
Conditional tooltips work. After all, I don't want empty tooltips to show up if I don't have anything sensible to say in them.

### What steps did you take, to get the error?
Have a component like this.

```
<template>
  <div>
    <q-tooltip v-if="showit">Test</q-tooltip>
    <q-btn @click="toggle">Toggle</q-btn>
  </div>
</template>

<script>
import {
  QTooltip,
  QBtn
} from 'quasar'

export default {
  name: 'comp-a',

  components: {
    QTooltip,
    QBtn
  },

  data () {
    return {
      showit: true
    }
  },

  methods: {
    toggle () {
      this.showit = !this.showit
    }
  }
}
</script>
```

Click toggle a few times

**Comment by Sumurai8** [comment]
I now realise that QTooltip is rendered outside the parent component. You don't want v-if to mess with that. You can instead use `v-show` (`<q-tooltip v-show="showit">Test</q-tooltip>`) or the `disable` property (`<q-tooltip :disable="!showit">Test</q-tooltip>`) on QTooltip to hide it when nothing meaningful can be displayed for some of the items. It has the added benefit that the tooltips still show after you passed an item that does not have a tooltip.

**Comment by anteqkois** [comment]
> I now realise that QTooltip is rendered outside the parent component. You don't want v-if to mess with that. You can instead use `v-show` (`<q-tooltip v-show="showit">Test</q-tooltip>`) or the `disable` property (`<q-tooltip :disable="!showit">Test</q-tooltip>`) on QTooltip to hide it when nothing meaningful can be displayed for some of the items. It has the added benefit that the tooltips still show after you passed an item that does not have a tooltip.

Any of these methods do not work.

Only this usage works for me:
```
<template v-if="showCondition">
    <q-tooltip>{{ $t('...')}}</q-tooltip>
</template>
```

**Comment by Sumurai8** [comment]
> > I now realise that QTooltip is rendered outside the parent component. You don't want v-if to mess with that. You can instead use `v-show` (`<q-tooltip v-show="showit">Test</q-tooltip>`) or the `disable` property (`<q-tooltip :disable="!showit">Test</q-tooltip>`) on QTooltip to hide it when nothing meaningful can be displayed for some of the items. It has the added benefit that the tooltips still show after you passed an item that does not have a tooltip.
> 
> Any of these methods do not work.
> 
> Only this usage works for me:
> 
> ```
> <template v-if="showCondition">
>     <q-tooltip>{{ $t('...')}}</q-tooltip>
> </template>
> ```

Hi. This is an issue from 7 years ago for a version of quasar that is ancient. I recommend finding up-to-date documentation on whatever version of quasar you are working on.
