### ISSUE TITLE
QSelect filtering is not showing all options after initial filtering with SSR

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#10660]
**Describe the bug**
When typing into an input during a QSelect to filter its options, the initial filtering is correct but when you backspace to remove what you typed all the options don't reappear. Instead you only see a few (1 or sometimes more) of the all the options in a list.

I put a watcher on the options to verify that the filteredOptions array is updated correctly but it is. It's a matter of rendering that is incorrect. This only happens on SSR and not on SPA. See the image below for an illustration what happens":

![qselectbug](https://user-images.githubusercontent.com/5757159/133230963-8c67cc5b-b6d0-4b08-b7c7-73b9425893e9.gif)

I tested also to see if my usage of class components had anything to do with this but I could also reproduce it using the options API, so it seems not.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/objective-spence-v0uok?file=/src/pages/Index.vue

**To Reproduce**
1. Click on the input
2. Type '100'
3. Backspace until the input is empty
4. Only 1 option is visible

**Expected behavior**
It should show all filtered options of course.

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version: 3.1.0

Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Thank you for reporting!
Fix will be available in Quasar v2.1.6.

**Comment by pdanpdan** [comment]
It looks like Qv1 does not need this.
