### ISSUE TITLE
Statics can't be obtained from backend server

### ISSUE THREAD

**Issue by songzhi** [quasarframework/quasar#1066]
Backend server like Django or Flask needs static file's urls have 'static'-like prefix.I know I could modify the publicPath in webpack config,and the urls will have the prefix.But it doesn't work in manifest.js which gets a [hash].js file ,and the file'url doesn't have the prefix,so it failed.And the whole page doesn't show.
I'm not sure it is definitely about the Quasar framework,but I can't find somewhere else to know how to fix it.
like this:
指向“http://127.0.0.1:5000/js/0.51a70a50366a9490c5e6.js”的 <script> 加载失败。
127.0.0.1:5000:1
Error: Loading chunk 0 failed.
Stack trace:
r@http://127.0.0.1:5000/static/js/manifest.js:1:553

**Comment by rstoenescu** [comment]
Hi,

Please redirect this to Webpack or Vue-loader. This is not handled by Quasar at all. Thank you!

**Comment by aFelipeSP** [comment]
I think this could be solved by changing webpack configuration, and I see that this could be made with the extendWebpack function in the build option of the quasar config file. But this function is not very well documented (or maybe I couldn't find how to use it) and I don't know how to change, for example the filename option of the generated bundles in the webpack rules, as this could be a solution.

Do you think such a solution, using the extendWebpack function, is possible, and if so, could you give us some hints about how could we do it?

**Comment by rstoenescu** [comment]
Please use our Discord server for questions. https://discord.gg/5TDhbDg
Thanks!

**Comment by songzhi** [comment]
@aFelipeSP Webpack has the option ：publicPath，I eventually solved the problem by using this option。
In case that @aFelipeSP can't see this,so I reply right here,just this once

**Comment by aFelipeSP** [comment]
I tried that and all the links, included the calls to an api inside the app were prepended with the word 'static/', and that's not what I need. I just want images, CSS and js files to have this prefix.

**Comment by songzhi** [comment]
@aFelipeSP Whats your publicPath,I used '/static/'.And in the common cases,it only works in the template.Are you writing api url in the template?Or using the relative url,for example 'api/users/' instead of '/api/users/'

**Comment by aFelipeSP** [comment]
that was the problem, I was using 'api/service/' instead of '/api/service/'. I changed it and your solution worked like a charm. Thanks a lot @songzhi
