### ISSUE TITLE
$slots error with wrapper components

### ISSUE THREAD

**Issue by Cmacu** [quasarframework/quasar#10675]
**Describe the bug**
there seams to be an issue with quasar. Just upgraded to 3.1 and started getting runtime errors from my wrapper components:

> TypeError: Cannot read properties of null (reading 'key')
>     at renderSlot (runtime-core.esm-bundler.js?9e79:6144)
>     at eval (BaseBtnIcon.vue?4259:3)
>     at renderFnWithContext (runtime-core.esm-bundler.js?9e79:718)
>     at renderSlot (runtime-core.esm-bundler.js?9e79:6143)
>     at eval (BaseBtn.vue?e13c:3)
>     at renderFnWithContext (runtime-core.esm-bundler.js?9e79:718)
>     at hMergeSlot (render.js?cdf5:25)
>     at Proxy.eval (QBtn.js?9c40:298)
>     at renderComponentRoot (runtime-core.esm-bundler.js?9e79:761)
>     at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bund

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/lucid-davinci-bjupy?file=/src/components/ButtonWrapper.vue

```
<template>
  <q-btn color="grey" flat round>
    <template v-for="(_, name) in $slots" v-slot:[name]="slotData">
      <slot :name="name" v-bind="slotData" />
    </template>
  </q-btn>
</template>
```

**Expected behavior**
A wrapper component should be able to pass slots to the qBtn

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.1.0 (the issue is not present in 3.0.4)

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
 » Dev mode.......... spa
 » Pkg quasar........ v2.0.4
 » Pkg @quasar/app... v3.1.0
 » Transpiled JS..... yes (Babel)

**Comment by metalsadman** [comment]
for anyone who'll stumble upon this vue 3.2 error, see workaround https://gist.github.com/loilo/73c55ed04917ecf5d682ec70a2a1b8e2#gistcomment-3869470.

**Comment by Cmacu** [comment]
@metalsadman Thanks. Can confirm that this workaround works.

**Comment by rstoenescu** [comment]
This should be reported to Vue team. Has nothing to do with Quasar.
