### ISSUE TITLE
Quasar boot error before iPhone 6+ (version 12.5.4)

### ISSUE THREAD

**Issue by abnerwang06** [quasarframework/quasar#10679]
**Describe the bug**
Quasar boot error before iPhone 6+(includes) (version 12.5.4).
The version after iPhone 7(includes) does not throw this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/33473028/133368497-7ad4cdf2-97ba-449a-8171-7b35b3e042c6.png)
![image](https://user-images.githubusercontent.com/33473028/133368516-d160dcc0-0611-41a9-b224-f307fd16b2f9.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.4

Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers: safari, chrome
iOS: 12.5.4
Android:
Electron:

**Additional context**
user agent: 
Mozilla/5.0 (iPhone; CPU iPhone OS 12_5_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

**Comment by abnerwang06** [comment]
I found the error is occurred in the file: .quasar/client-entry.js.
I tried the spa mode, it threw the same error.
According to the photos, the length of the param bootFiles has invalid array length in the version of IOS.
![image](https://user-images.githubusercontent.com/33473028/133392421-8e805467-ce66-40b4-900b-ad4100da8a92.png)

**Comment by pdanpdan** [comment]
Check the browserlist to include as many versions of iOS as required.
