### ISSUE TITLE
Apply "dense" to the QSelect drop-down list (Qitem) automatically 

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#10672]
Hello,

It would be really nice if when we apply "dense" option to the QSelect, it also applies to its drop-down list, without manually apply "dense" to <q-item> in <template #option="scope"> .

Thanks in advance.

**Comment by pdanpdan** [comment]
You already have a property for this. Search in API cards for dense.

**Comment by RejDev** [comment]
@pdanpdan 
I think I was not very clear in my explanations, here is the problem visually :
![aa](https://user-images.githubusercontent.com/12255492/133331099-ed6bddf0-c7f2-4cc7-9c86-245adde37cc1.png)

dense in q-select only affects the top area, not the list.

to force dense in  drop-down list, we have to do it manually like this :
```
<q-select v-model="XXXXXXXX" dense use-input input-debounce="0" label="LABEL" emit-value map-options :options="YYYYYYYYYYYYYYY" option-label="name" @filter="FFFFFFFFFFFF" @update:model-value="VVVVVVVVVV">
  <template #option="scope">
    <q-item v-bind="scope.itemProps" dense> <---------------------- dense also here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      <q-item-section avatar>
        <img style="display: inline-block; width: 32px; height: auto" :src="'img/flags/low/' + scope.opt.code + '.jpg'" />
      </q-item-section>
      <q-item-section>
        <q-item-label v-text="scope.opt.name" />
      </q-item-section>
    </q-item>
  </template>

  <template #no-option>
    <q-item>
      <q-item-section class="text-grey"> NO RESULT </q-item-section>
    </q-item>
  </template>
</q-select>
```

**Comment by pdanpdan** [comment]
Have you searched for dense? Show a screenshot with what you found

**Comment by RejDev** [comment]
**options-dense**   :+1: 
thank you so much @pdanpdan
