### ISSUE TITLE
Show to what JS Version Babel has transpiled the project

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#10680]
**Is your feature request related to a problem? Please describe.**
I would like to know to which JS (ES) Version Quasar/Babel have transpiled the code.
Currently Quasar show that transpilation was done, but not to what.
![obraz](https://user-images.githubusercontent.com/9776384/133401726-81ce571d-bffe-41cc-97f8-400a70a3b3f0.png)

**Describe the solution you'd like**
If quasar can know to what ES Version the code has been transpiled it would be nice to know this.

**Comment by rstoenescu** [comment]
It's all based on your package.json > browserslist. You don't need to handle a specific level of JS. Rather focus on what browsers you want to support and let Quasar do its magic. 
The JS language moves fast nowadays and browsers even support features that are stage 2 or 3 proposals.

**Comment by robert-niestroj** [comment]
@rstoenescu i know that. https://quasar.dev/quasar-cli/browser-compatibility says: 

> Be mindful about it though, as it is sufficient to add one “bad apple” in the options list and that will dumb down your code back to ES5.

I would like to know if i hit such a "bad apple" or not. Ideally i would like to know which browser was the "bad apple".

**Comment by rstoenescu** [comment]
The package handling the browserslist does not offer such a possibility.
It's a good rule of thumb to check the global marketshare lists and configure your browserslist to say "latest X versions" for the top browsers. It might be wise to avoid entries like "> X%" (browsers with more than X% global marketshare) as most likely this will end up including old browsers (like IE). Just specify the top browsers explicitly.

You can also play with https://browserslist.dev/ to check what the output would be.

When I wrote that text about the "bad apple" I was mostly referring to Internet Explorer (aka "Internet Exploder") which requires ES5. Top modern browsers support high levels of ES, so if you configure it like I mentioned earlier you should be good.
