### ISSUE TITLE
Reactive or Ref object for v-model on q-input changes value type from number to string

### ISSUE THREAD

**Issue by cmcleese** [quasarframework/quasar#10686]
**Describe the bug**
When using q-inputs and a type set as `number`, the v-model value type changes on the ref() from type `number` to `string`.
This only an issue when the v-model used on the q-input is a ref of a object or a reactive object.
Native HTML inputs respect the ref value type accordingly for both.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/cmcleese/pen/LYLOyOJ

**To Reproduce**
1. Go to codepen
2. enter values in native input elements and notice the value type stays the same
3. enter values in the q-inputs and notice the value types change but only for when the v-model on the q-input is a `ref` object or a `reactive` object.

**Expected behavior**
The type should not be changed for nested ref objects or reactive objects.

**Platform (please complete the following information):**
Quasar Version: 2.0..4
@quasar/app Version: 3.1.0

Quasar mode:
  - [x ] SPA

Tested on:
  - [ x] SPA

OS: windows
Node: 12.22.1

**Comment by rstoenescu** [comment]
The correct usage is:
type=number v-model.number="justnum"
The "number" modifier applied to the Vue native v-model directive is mandatory.

**Comment by cmcleese** [comment]
Thanks. Didn't realize about v-model modifiers.
https://v3.vuejs.org/guide/component-custom-events.html#handling-v-model-modifiers
