### ISSUE TITLE
Checkbox false-value does not send on form submit

### ISSUE THREAD

**Issue by victj99** [quasarframework/quasar#10687]
**Describe the bug**
q-checkbox false-value is not sent on form submission

**Codepen/jsFiddle/Codesandbox (required)**
 https://codepen.io/victj/pen/gORXKdY?editors=101.

**To Reproduce**
1. Go to 'https://codepen.io/victj/pen/gORXKdY?editors=101'
2. add false-value to some checkbox
3. Click on 'submit'

**Expected behavior**
Send false-value on form submit.

**Screenshots**
![image](https://user-images.githubusercontent.com/44973221/133514578-1039cb41-79b2-4522-92b6-53c027983129.png)

Quasar Version:
@quasar/app Version: 2.0.1

**Comment by pdanpdan** [comment]
Read the blue note: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
