### ISSUE TITLE
Quasar project build not working without devDependencies installed

### ISSUE THREAD

**Issue by MurzNN** [quasarframework/quasar#10681]
**Describe the bug**
I need to optimize the time and resources usage of Quasar build process. 
First step is do not install the development dependencies. 

But without them Quasar build command is missing!
```
$ yarn install --production
$ yarn build
 Error Unknown command "build"
```
**To Reproduce**
1. Create a new project and install only production dependencies via commands:
```
$ quasar create test3
$ cd test3
$ rm -rf ./node-modules
$ yarn install --production
```
2. Run 'quasar build'
```
 Error Unknown command "build"
```

And there are many confused people about this problem, eg in this forum thread: https://forum.quasar-framework.org/topic/5283/unknown-command-build-circleci?_=1631694999503&lang=en-GB

**Expected behavior**
Quasar should be able to build himself without development dependencies installed.

**Proposal**
If we move `@quasar/app` package from `devDependencies` to `dependencies` in `package.json` - all becomes to work well.
So maybe do this by default?

If not, can you describe the decision to place `@quasar/app` package into `devDependencies` by default?

**Comment by pdanpdan** [comment]
Then move it, it's your project.

**Comment by MurzNN** [comment]
> If not, can you describe the decision to place @quasar/app package into devDependencies by default?

@pdanpdan In my projects I can of course do this, but can you please describe why this isn't done by default? What is reason to require all dev dependencies in Quasar building process?

**Comment by pdanpdan** [comment]
devDependencies are modules which are only required during development.
When you build it it's considered development.
The only non-development is on SSR and electron, and for those cases a separate package.json is built accounting for dependencies.

**Comment by MurzNN** [comment]
Thank you for clarification!
