### ISSUE TITLE
Incorrect documentation for ion icons

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10682]
![image](https://user-images.githubusercontent.com/44498510/133431059-1fb5ba97-b2db-4733-b1a7-8efc94880e89.png)

In the complied js file, there is no such name

the correct name shall be without md

![image](https://user-images.githubusercontent.com/44498510/133431248-985569b9-526d-467e-958b-08979db1dfe9.png)

**Comment by hawkeye64** [comment]
@cyfung1031 Thanks for pointing this out. Ionicons dropped the `md` and `ios` names when they went to v5 and the docs were not updated to reflect that.

The fix will be in the next deployment of the docs (v1 and v2)
