### ISSUE TITLE
q-btn with type="anchor" and href not working in q-input templates (:before, :after, :append, :prepend)

### ISSUE THREAD

**Issue by obi84** [quasarframework/quasar#10696]
**Describe the bug**
When using q-input (this most likely concerns most if not all of the form components ) templates (:before, :after, :append, :prepend) and insert a q-btn with type anchor, anchor will not get opened. This is independent of link type (http, tel, email ) or target ("_blank").

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ObiRocks/pen/ZEyvGqy?editors=101

**To Reproduce**
neither of the buttons href work when clicked on.

**Expected behavior**
on click, open the href of the button link

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 1.15.23, 2.0.4
@quasar/app Version:
2

Quasar mode:
  - [x] PWA
  - [x] SPA

Tested on:
  - [x] SPA
  - [x] PWA

OS: MacOs
Browsers: Chrome, FF, Safari

**Comment by pdanpdan** [comment]
Use `@click.stop` on the link buttons inside `QInput / QField - derivatives`.
It looks like they don't behave (similar to `<button type="submit">`)
Maybe a mention in the docs  would be good.

**Comment by obi84** [comment]
That is a good workaround and would suffice my needs. A mention in the docs would be great for anyone else stumbling over this issue! 
Should I close the issue, or leave it open in case you guys decide upon fixing the behaviour without the @click.stop workaround?

**Comment by pdanpdan** [comment]
It's not really fixable in code, i left it open for docs.
