### ISSUE TITLE
Quasar Documentation site is down

### ISSUE THREAD

**Issue by amfine-soft-msouissi** [quasarframework/quasar#10699]
![using chrome](https://user-images.githubusercontent.com/53564975/133646694-90c3f6ae-c73c-4bc4-9f41-6aafe30cfe7e.png)
![using firefox](https://user-images.githubusercontent.com/53564975/133646698-9e08e4dc-dd89-4ab7-9327-b7f793dd105b.png)

**Comment by metalsadman** [comment]
it's up to me, please provide more info.
