### ISSUE TITLE
[Request][0.15] Sort on other other row properties/column data

### ISSUE THREAD

**Issue by codedog76** [quasarframework/quasar#1069]
It would be nice if we were able to sort on other column data/row properties. Currently, with sort(a, b), we are only able to sort on the current defined field for that column. Thanks in advance.

**Comment by rstoenescu** [comment]
I think you refer to the new datatable?
The sort method can be overriden to accomodate to any requirements by specifying `sortMethod` prop as a function taking following parameters data, sortBy, descending (provided by Quasar).
