### ISSUE TITLE
Nested QSelect with virtual scrolling throws warnings in the console

### ISSUE THREAD

**Issue by Skruvkork** [quasarframework/quasar#10698]
**Describe the bug**
I was using `QSelect` inside another component that passes on props and attrs to `QSelect`. When setting `@virtual-scroll` on that wrapper component and opening the options list, an error appears in the console.

```
[Vue warn]: Component emitted event "virtual-scroll" but it is neither declared in the emits option nor as an "onVirtual-scroll" prop.
```

This is presumably because `QSelect` is simply missing `virtual-scroll` in it's emits option. When I added it manually on my local machine the warning stopped appearing.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/ydnbtg8w/

**To Reproduce**
1. Go to the linked jsFiddle
2. Click on the QSelect to open the options overlay
4. See the warning in the console

**Expected behavior**
No warnings should be displayed for `@virtual-scroll`

**Platform (please complete the following information):**
Quasar Version: 2.0.4
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: 14.17.0
NPM: 6.14.13
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by metalsadman** [comment]
i don't know when this change came, but looks like it's a latest vue 3 version issue when wrapping a wrapper component. as you can see here https://codepen.io/metalsadman/pen/OJgzqBb?editors=1010. please also issue a ticket at vue-next repo.

**Comment by metalsadman** [comment]
mind issuing a pr pls. thx.

**Comment by rstoenescu** [comment]
This is a problem in your example.
Your wrapper component emits 'virtual-scroll' event but you haven't defined it as emitting such an event.

```js
app.component('select-wrapper', {
  emits: [ 'virtual-scroll' ], // <<<<< add this
  // ....
}
```

**Comment by kapchew** [comment]
Hi,

Using the same example, but with your recommended solution to add emits: [ 'virtual-scroll' ], it seems to work at first, but when an item is selected, and you try to select again, the same warning will be triggered:

[Vue warn]: Component emitted event "virtual-scroll" but it is neither declared in the emits option nor as an "onVirtual-scroll" prop.

This is the modified example: https://jsfiddle.net/kapchew/drpmbs9e/2/

**Comment by kapchew** [comment]
> This is a problem in your example. Your wrapper component emits 'virtual-scroll' event but you haven't defined it as emitting such an event.
> 
> ```js
> app.component('select-wrapper', {
>   emits: [ 'virtual-scroll' ], // <<<<< add this
>   // ....
> }
> ```

Hi,

Using the same example, but with your recommended solution to add emits: [ 'virtual-scroll' ], it seems to work at first, but when an item is selected, and you try to select again, the same warning will be triggered:

[Vue warn]: Component emitted event "virtual-scroll" but it is neither declared in the emits option nor as an "onVirtual-scroll" prop.

This is the modified example: https://jsfiddle.net/kapchew/drpmbs9e/2/

**Comment by hawkeye64** [comment]
@kapchew Check out the explanation here about a Vue bug related to this: https://github.com/quasarframework/quasar/issues/11475#issuecomment-980692233
