### ISSUE TITLE
Ripple effect for Material theme

### ISSUE THREAD

**Issue by marcusvbp** [quasarframework/quasar#107]
Hi,

Firstly, congrats for the Quasar Framework, it looks very promissing!

The material design theme can be improved by implementing the Ripple effect in clicable/touchable components.

And some components cannot follow the Material Design directives. For example, the tabs component:

https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsbHJuWi04N0ZIc0E/components_tabs_usage_mobile7.png

I want to help the project in the styling part. How I can do this? :)

**Comment by rstoenescu** [comment]
Hi,

I'm thrilled if you want to contribute to the project! Here are some basic steps to get you started:
1. Fork the repo
2. Git clone it on your machine
3. Checkout a topic branch from dev and merge back against dev.
4. Create a pull request.

Some more info here: http://quasar-framework.org/guide/contributing.html#Pull-Request-Guidelines and here: http://quasar-framework.org/guide/contributing.html#Development-Setup

Run `npm run dev`, make yourself a new page on that UI and work your thing with it.

Don't be discouraged if you don't understand everything. I'm here to help you get started if you have difficulties.

I'm not sure what exactly you want to do though. Let's discuss before you start making changes please.

Thanks again for wanting to improve the project!

Cheers,
Razvan

**Comment by rstoenescu** [comment]
The tabs do follow the Material design guidelines. Your screenshot is just another way of displaying Tabs. They can be tweaked to look like this in the app's code.

**Comment by marcusvbp** [comment]
@rstoenescu sorry, but in tab specs for MD I cannot find a reference for icon side by side the text. 

https://material.google.com/components/tabs.html#tabs-specs

**Comment by rstoenescu** [comment]
Aaah, you are right. Don't know how that slipped away. We should change that. It's a matter of changing Quasar flexbox classes. Would you be so kind to take a look and try to do it? Read about the http://quasar-framework.org/api/css-grid-layout.html to familiarize yourself with those classes.

**Comment by CookieJon** [comment]
Just parking an idea here in the same category as the "ripple" effect; there's also the animated border underneath tabs when the selection changes.

**Comment by rstoenescu** [comment]
Right. That's already on my list too.

**Comment by CookieJon** [comment]
Oh ok, sorry.  Do you mean just _your own_ to-do list, or should I be checking somewhere before spamming the  Issues list with non-issues? :-)

**Comment by rstoenescu** [comment]
No need to apologize man. It's actually my fault. Didn't write it down. But anyways, it was just a side comment. Will refrain myself from doing that in the future so I don't give the wrong impression :) Please do log on any idea you may have! If the idea ain't here on the github issues then you're free to write it down. Thanks for helping out!

**Comment by dobromir-hristov** [comment]
If the ripple effect and animated border are not worked on, I could try to do them?

**Comment by rstoenescu** [comment]
It might overlap with the Vue 2 work. Best thing is to wait for Vue 2 then jump in. Are you ok with this?

**Comment by dobromir-hristov** [comment]
Ok :)

**Comment by rstoenescu** [comment]
Trying to push v0.8 release this week. Let's see if I can make it happen so fast :)

**Comment by dobromir-hristov** [comment]
:D I am looking at the Commits on the 0.8 atm. Looks pretty good. Update on the docs will be a pain. Can I help in any way ?

**Comment by rstoenescu** [comment]
Of course. We'll split the docs when updating them if you want. Thanks a lot!

**Comment by rstoenescu** [comment]
Material ripples coming to v0.14 ;)
