### ISSUE TITLE
Need config option of QDialog's show event delay.

### ISSUE THREAD

**Issue by guogangj** [quasarframework/quasar#10705]
According to this post: #3473, It seems that there is a delay of the QDialog's show event.

Now, I have a QDialog with a input field, and I need to focus on this input field after show event, then I got the very tiny delay for this focus effect, that's a little uncomfortable. That would be great if there is a option for this delay.

**Comment by pdanpdan** [comment]
Set autofocus prop in the input.

**Comment by guogangj** [comment]
> Set autofocus prop in the input.

I tried. It's exactly same as handling the show event.

**Comment by rstoenescu** [comment]
You can use the before-show event to focus it (or even add a nextTick on the handler). But you will end up with a lot of trouble on iOS safari. There's some tickets that highlight the many problems on mobile devices, but if you don't care about them then go ahead.

**Comment by guogangj** [comment]
> You can use the before-show event to focus it (or even add a nextTick on the handler). But you will end up with a lot of trouble on iOS safari. There's some tickets that highlight the many problems on mobile devices, but if you don't care about them then go ahead.

Thanks for reply. However, before-show didn't work as expected. After many attempts, I gave up, it wasn't a big deal anyway.
