### ISSUE TITLE
QItemTile image property doesn't work

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1070]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: 8.8.1
NPM: 5.4.2
Browsers: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
`[Vue warn]: Invalid prop: type check failed for prop "image". Expected Boolean, got String.`
### What were you expecting?
I expected to see the image.
### What steps did you take, to get the error?
Running the following code, (please replace the fake URL with a real one):

```
<q-item-side right>
  <q-item-tile image="https://example.com/image.jpg" />
  <q-item-tile><p><strike class="text-faded">90 TL</strike> <span class="text-purple-6">55.99 TL</span></p></q-item-tile>
</q-item-side>
```

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting!

**Comment by rstoenescu** [comment]
Wrong use case. QItemTile has boolean "image" prop, so the correct usage is:
```html
<q-item-tile image> <img src="..."> </q-item-tile>
```
