### ISSUE TITLE
What is the correct / recommended way to create such layout?

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10701]
![image](https://user-images.githubusercontent.com/44498510/133684808-3f2ea1b5-7207-4406-ac28-6575c9c1dc47.png)

In the official docs, the scrollbar is to the overall page.

I tried to make it like
```
<div class="flex-row">
    <div>.....header....</div>
    <div style="flex: 1 1 auto;">
          <q-layout container  >
                <teleport to="body" :disabled="$q.platform.is.desktop">
                    <q-drawer mini-to-overlay :mini="miniState" bordered v-model="drawer" @mouseenter="miniState = false" @mouseleave="miniState = true"> .... </q-drawer>
                </teleport>
                <q-page-container>
                    <q-page class="flex-row">
                        <div style="flex: 1 1 auto;"> .... content ... </div>
                    </q-page>
                </q-page-container>
          </q-layout >
    </div>
</div>
```

It can work on both mobile and dekstop, but I cannot disable the scrolling and fix the full height of the content area.
Any correct / recommended way to create such layout?

**Comment by metalsadman** [comment]
please ask questions in the [discussions](https://github.com/quasarframework/quasar/discussions) or discord channels.
