### ISSUE TITLE
Error on template components for datatables

### ISSUE THREAD

**Issue by IgorDePaula** [quasarframework/quasar#1071]
### Software version

Quasar: ^0.14.4
OS: ubuntu 16.01
Node: 6.3.1
NPM: 3.10.3
Browsers: firefox
Any other software related to your bug:

On copied the datatables code for my situation, I received the error on console:
It's occur mainly on template column for a specific components

![selecao_076](https://user-images.githubusercontent.com/2833993/32179570-e174f014-bd76-11e7-9bca-3c87b7d79f05.png)

Copy the datatables code from docs and receive the error

### What did you get as the error?

On copied the datatables code for my situation, I received the error on console:
It's occur mainly on template column for a specific components

### What were you expecting?

No warning

### What steps did you take, to get the error?

On copied the datatables code for my situation, I received the error on console:
It's occur mainly on template column for a specific components.

Copy the datatables code from docs and receive the error

**Comment by rstoenescu** [comment]
This has to do with Vue 2.5 having a breaking change. "scope" needs to be "slot-scope". Just make a general replace of that and it will be fine.

**Comment by IgorDePaula** [comment]
<template slot='col-opcoes' slot-scope='cell'> ?

**Comment by IgorDePaula** [comment]
Fix, thanks
