### ISSUE TITLE
Request of adding an advanced QLayout Example with QScrollView

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10720]
I found using the combination of QHeader, QDrawer with miniState and QScrollView is a very great web app design to be considered. It also contains some features not showing in the official docs (i.e. how to make scrollable view inside q-page)

Without ["QScroller"](10716)
[CodePen](https://codepen.io/cyfung1031/pen/wveyPwv)
[Different UX for Mobile & Desktop](https://codepen.io/cyfung1031/live/wveyPwv)

With ["QScroller"](10716)
[CodePen](https://codepen.io/cyfung1031/pen/jOwZGYO)
[Different UX for Mobile & Desktop](https://codepen.io/cyfung1031/live/jOwZGYO)

**Comment by pdanpdan** [comment]
Sorry but these are mostly covered in the docs, and we cannot add all examples :)
But they are good here so somebody can look at them.
You may also take a look here: https://github.com/quasarframework/quasar/issues/10923
