### ISSUE TITLE
Keep hover effect of the main header even when using expand-icon-toggle for QExpansionItem

### ISSUE THREAD

**Issue by hyperkai** [quasarframework/quasar#10722]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hyperkai** [comment]
When using expand-icon-toggle for QExpansionItem, hover effect of the main header is removed but if the main header is link, hover effect is still needed to show that the main header is a link or clickable.

**Comment by pdanpdan** [comment]
Please add a codepen showing the problem.

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/powLbJy?editors=1000

**Comment by hyperkai** [comment]
Finally, I solved the problem. When I add routing destination with to="", the main header get back the hovering effect.
