### ISSUE TITLE
Convert existing vue writing in js to ts?

### ISSUE THREAD

**Issue by goforu** [quasarframework/quasar#10723]
**Is your feature request related to a problem? Please describe.**
I have an existing quasar project coding in javascript. To take advantage of Typescript feature, I want to add typescript to my existing project. Unfortunately, I have tons of vue files to rewrite.

**Describe the solution you'd like**
Can you give me a solution? 

**Describe alternatives you've considered**
Is there a quick way to convert js to ts? Or can I use both js and ts in my project?

**Additional context**
Huge amount of vue files writing in js and we need add ts support.

**Comment by pdanpdan** [comment]
Hello. Please open this in discussions. Thank you
