### ISSUE TITLE
Bug - QTime - "Now Button" not working if only hour is picked

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10727]
https://quasar.dev/vue-components/time#example--now-button

To reproduce:

1. Pick the "hour" => enter "minute" picker
2. Click "Now Button"
3. Look Okay, but
4. Pick the "hour" => enter "minute" picker
5. Click "Now Button"

It happens as long as the "picking" is incomplete.

![92886573-e502-4cbf-842a-c2d321542c40](https://user-images.githubusercontent.com/44498510/133887554-f71dafc0-92a7-4ecc-b9a4-9e7ee37ef233.gif)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.1.2
