### ISSUE TITLE
Icon Genie CLI - stopped working

### ISSUE THREAD

**Issue by whiteua** [quasarframework/quasar#10732]
**Describe the bug**
After running the command
icongenie generate -i logo-icon.png

Outputs the following error:

C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\node_modules\sharp\lib\constructor.js:32
  throw new Error(error);
  ^

Error:
Something went wrong when installing the 'sharp' module

Unable to find the '../build/Release/sharp.node' module.
Require stack:
- C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\node_modules\sharp\lib\constructor.js 
- C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\node_modules\sharp\lib\index.js       
- C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\lib\utils\get-files-options.js        
- C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\lib\cmd\generate.js
- C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\bin\icongenie-generate.js
- C:\Users\white\AppData\Roaming\nvm\v14.17.6\node_modules\@quasar\icongenie\bin\icongenie\bin\icongenie

- Delete the "node_modules/sharp" directory, then run the command
  "npm install --ignore-scripts=false --verbose sharp" and look for errors.
- Refer to the installation documentation at https://sharp.pixelplumbing.com/install.
- Find this error at https://github.com/lovell/sharp/issues

Everything was working fine before. 
I reinstalled NODE and all services. but that didn't help. Maybe you have instructions on how to properly install Icon Genie on Windows10 ?

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by yusufkandemir** [comment]
Please see the explanation on the error message:
> Delete the "node_modules/sharp" directory, then run the command
> "npm install --ignore-scripts=false --verbose sharp" and look for errors.
> 
> Refer to the installation documentation at sharp.pixelplumbing.com/install.
> 
> Find this error at https://github.com/lovell/sharp/issues

This is not an issue that is directly related to Icon Genie CLI, please try the solutions in the error message, and open an issue in https://github.com/lovell/sharp/issues if none of them solved your problem.
