### ISSUE TITLE
Opening and closing modals affect window.history

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1074]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: 8.8.1
NPM: 5.4.2
Browsers: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Didn't get error
### What were you expecting?
I didn't expect to see the modal interact with window.history
### What steps did you take, to get the error?
This issue appears on the official Quasar framework demo as well, please watch this https://www.dropbox.com/s/tufkv9pycamxy5n/quasar-framework-modal-bug.mkv?dl=0

**Comment by rstoenescu** [comment]
This is not a bug. This is a feature. It allows hitting "back" button (both on a desktop or on a mobile website or app) to close the modal, as would the user expect. This is something that sets apart Quasar from any other framework.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu sorry for that, my mistake, I have a small experience with other frameworks and because this is new to me I thought it is a bug, thank you so much for the clarification, I wish you and your awesome framework that I Iove too much all the best.
