### ISSUE TITLE
Icons Set - Request of adding Boxicons

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10752]
https://boxicons.com/

Information for Boxicons
1. Boxicons is new and getting popular now
2. Boxicons is used in Vuesax
3. Webfont only

Remarks:
Quasar Docs for relevant selections to be updated as well
https://quasar.dev/vue-components/icon#introduction

**Comment by hawkeye64** [comment]
Your request is probably better put here: https://github.com/hawkeye64/quasar-extras-svg-icons
Documentation: https://quasar-extras-svg-icons.netlify.app/

**Comment by hawkeye64** [comment]
I just noticed. They have **no releases** so you are expected to download them directly from GitHub. In order to integrate them, it'd be better if they had an NPM release so that when something changes, it gets updated properly. You can ask them here: https://github.com/atisawd/boxicons

**Comment by hawkeye64** [comment]
Further to this, their icons use the `use` svg directive, which is not compliant with quasar minified svg conversion. Specifically in this one: https://github.com/atisawd/boxicons/blob/master/svg/solid/bxs-droplet.svg

**Comment by hawkeye64** [comment]
Hmmm, lastly, they have no LICENSE file.

The icons look good, but they need to:
1. Clean up icons not to use keyword `use`
2. They need to have a LICENSE file
3. They need to make releases of the SVG whenever there are changes

You can make an issue for them and when they comply we can add it into quasar-extras-svg-icons package

**Comment by hawkeye64** [comment]
Only these two icons have issues:
1. bxs-droplet
2. bxs-hot

**Comment by hawkeye64** [comment]
ok, one last thing, they have a space at end of the name, before ` .svg` that breaks parsing, so it you create an issue, you can also mention this: 
![image](https://user-images.githubusercontent.com/10262924/134048100-4c88f080-9b8f-492d-b2a8-4e796cac3eab.png)

**Comment by hawkeye64** [comment]
I added box-icons in quasar-extras-svg-icons: https://github.com/hawkeye64/quasar-extras-svg-icons/releases/tag/v1.0.0-alpha.3

**Comment by hawkeye64** [comment]
I made an issue with them: https://github.com/atisawd/boxicons/issues/215
