### ISSUE TITLE
QPopupProxy (Popup Proxy) is not a search result for "Popup"

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10751]
https://quasar.dev/vue-components/

type **Popup** or **popup** in the top-left search bar
No results for Popup Proxy is shown

type **component popup** in the top-left search bar
Some results for Popup Proxy are shown

![image](https://user-images.githubusercontent.com/44498510/133994572-acc6d954-f24c-4346-8a95-afc5b2af1ade.png)
![image](https://user-images.githubusercontent.com/44498510/133994639-7314380b-7958-4a60-9e3b-03efaaf0223c.png)

Indeed I only need to search the heading
i.e. when i type popup, I would like to see "Close Popup", "Popup Edit", "Popup Proxy", etc.
I don't need the duplicated results for "Close Popup" and "Popup Edit"
(say "Close Popup | ClosePopup API", "Close Popup | Usage", "Close Popup | Usage >> Basic" are just in the same page under different sections)

**Comment by metalsadman** [comment]
the search api has limit of 10 results. wouldn't hurt to make the keyword a bit complete, ie. `proxy`, `popup prox`, etc...
