### ISSUE TITLE
Layout breaks with different login

### ISSUE THREAD

**Issue by Iscrimou** [quasarframework/quasar#10753]
Hello everyone, I have a problem in my application, my users have a role property, when I log in with a role 4, the layout breaks, and when I log in with a role 3 the layout is normal, nowhere in the code I differentiate between them, on the contrary, I redirect them both to the same place, in the same way. Does anyone know what can it be?

With a role 4:
![Screenshot(9)](https://user-images.githubusercontent.com/62183829/134035199-6274f5a7-53d0-4cdf-9ff0-131f337512ca.png)

With a role 3:
![Screenshot(10)](https://user-images.githubusercontent.com/62183829/134035278-97fba7c7-80d5-403b-9826-1f83b5a25b6e.png)

**Comment by pdanpdan** [comment]
Please use discord or discussions for help.
