### ISSUE TITLE
Quasar SSR: XSRF header not attaching

### ISSUE THREAD

**Issue by chAhmedRaza** [quasarframework/quasar#10764]
Hi, 
I am building a Quasar SSR app. And trying to send a request to the API. But axios is not attaching the X-XSRF-TOKEN header to the request in SSR mode (quasar dev -m ssr). However in non-SSR mode, the request is running alright with X-XSRF-TOKEN attached. 

Axios is all set to attach the credentials the the request headers using `axios.defaults.withCredentials = true;` 

How do I attach the X-XSRF-TOKEN to the request header in SSR?

**Comment by IlCallo** [comment]
Hi @chAhmedRaza, can you provide a repro?

**Comment by IlCallo** [comment]
Hi @chAhmedRaza may you reopen this issue providing a repro and following the issue template we provide?
