### ISSUE TITLE
qinput displays value far above the base line which doesn't look good

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10765]
**Describe the bug**
When using qinput with default settings the text is small and sits far above the baseline which doesn't look good. Contrast this with writing on lined paper where the text sits on the baseline.

This could be a simptom of the issue that I have with quasar in general which is that components seem to use way more vertical space than the content requires. It seems like the text in the input box is only about 30% as high as the box. I also added a couple icons to my codepen to illustrate this even more. 

I added a number input and I think it looks ridiculous with the text being so small.

I have looked at the CSS in the browser inspector and I don't see any margin or padding by default, so it is not clear how to address these issues.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Julie777/pen/ExXRWvp

**To Reproduce**
See codepen https://codepen.io/Julie777/pen/ExXRWvp

**Expected behavior**
I expect text in a component to be sized appropriately so it looks good. I expect text for an input field to sit on the baseline if that is the style for the input element.

**Screenshots**
![image](https://user-images.githubusercontent.com/5090005/134217198-d50559d2-bb97-4282-9e1f-f3a1699d7ffd.png)

**Platform (please complete the following information):**
Quasar Version: 2.1.0
@quasar/app Version:

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Please raise the issue on material design :)

**Comment by cyfung1031** [comment]
To be honest the styling in Vuetify is much better
In quasar, the development team expects you use `dense` for underline input and no `dense` for bordered input.
(From the examples in official docs, you can see they prefer `filled` without `dense`)

![image](https://user-images.githubusercontent.com/44498510/134223991-be758c79-acba-48f9-9588-62eee17d552d.png)


https://vuetifyjs.com/en/components/inputs/

Vuetify fully follows the Material Design while Quasar does not


For a easy solution, just use `dense` for underline input. (for both text field and number input)
(but not recommend if you want to use the label feature)
