### ISSUE TITLE
Change the background color of the Image Gallery Carousel

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1077]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: 8.8.1
NPM: 5.4.2
Browsers: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Didn't get error
### What were you expecting?
If I added class that starts with bg- like bg-warning I expect the background color changes to "warning" color
### What steps did you take, to get the error?
Adding bg-warning class to q-gallery-carousel and the background color still black.

**Comment by rstoenescu** [comment]
Carousel was rewritten in v0.15 to allow full customization. Closing as it's ready in future v0.15.
