### ISSUE TITLE
Quasar SSR: Unable to attach X-XSRF-TOKEN header in SSR mode.

### ISSUE THREAD

**Issue by chAhmedRaza** [quasarframework/quasar#10776]
**Describe the bug**
I am building a Quasar SSR app. And trying to send a request to the API (Built in Laravel and using Sanctum from CSRF). 
Making a request to csrf endpoint i.e `https://somedomain.com/sanctum/csrf-cookie` sends the set-cookie header in response with XSRF-TOKEN. 

I am using Axios to make request and configured it to send the X-XSRF-TOKEN with subsequent requests with `axios.defaults.withCredentials = true;` The app is running alright on non-SSR mode and axios is attaching the `X-XSRF-TOKEN` properly to the request headers as should. 

However in SSR mode, axios does not attach the `X-XSRF-TOKEN` to the requests. And the requests fail with 419 - csrf mismatch error.

**To Reproduce**
Following is how my axios.js boot file looks like:
```
import Vue from 'vue';
import axios from 'axios';

axios.defaults.withCredentials = true;

const api = axios.create({
  baseURL: 'https://somedomain.com',
  withCredentials: true,
});

Vue.prototype.$axios = axios;
Vue.prototype.$api = api;

export { axios, api }
```

The code from store actions is: 
```
export const fetchCategories = async function({ commit, state }, payload ){
    this._vm.$api.get('/sanctum/csrf-cookie' ).then(response => {
        this._vm.$api.post('/api/website/product/categories' ).then(response => {
            commit('setCategories', response.data.categories);
        }).catch(error => {
            commit('setCategories', error);
            console.log(error)
        })
    })
}
```

And inside of the component where I dispatch this actions looks like this: 
```
 async preFetch ({ store, currentRoute, previousRoute, redirect, ssrContext, urlPath, publicPath }){
    return store.dispatch('productsStore/fetchCategories')
  },
```

I am running the app using `quasar dev -m ssr`

**Expected behavior**
Axios should attach the headers as should in SSR app as well. 

How do I attach the `X-XSRF-TOKEN` header to the requests?

**Platform (please complete the following information):**
Quasar Version: v1
@quasar/app Version: ^2.2.10

Quasar mode:
  - [ ] SSR

Tested on:
  - [ ] SPA - Works fine
  - [ ] SSR - X-XSRF-TOKEN does not attach

**Comment by rstoenescu** [comment]
This has nothing to do with Quasar itself.

One thing to note is that on SSR server-side, the Axios request is done by the server itself on the client's behalf, not the client itself which may have cookies that you need.
You could use the Cookies plugin to get all cookies (or just the ones that you need) and inject into Axios instance, but you will need one new Axios instance for each request received otherwise you will pollute requests on the SSR server-side.
