### ISSUE TITLE
createUploaderComponent doesn't support emits as an object

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#10773]
**Describe the bug**
When `createUploaderComponent` has been created, `emits` specification only described the usage as an array (eg. `['update:label', 'change']`), later on they added the ability to provide an object for stricter type checking and validation, very much like `props`.
Currently `createUploaderComponent` only supports `emits` as an array and `props` as an object

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

```
import { createUploaderComponent } from 'quasar';
import myUploaderPlugin from './my-uploader-plugin';

export default createUploaderComponent({
  name: 'MyUploader',
  emits: {
    'change': (newValue: string) => true
  },
  injectPlugin: myUploaderPlugin,
});
```

then use the component anywhere and a warning (at least) will be fired

**Expected behavior**
`props` and `emits` should support both Array and Object styles

**Platform (please complete the following information):**
Quasar Version: 2.x
@quasar/app Version: 3.x

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux 18.04
Node: 12.22.6
NPM: 6.14.15
Yarn: 1.22.5

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v2.2.5.
