### ISSUE TITLE
Axios 0.21.4 and Ajax Bar

### ISSUE THREAD

**Issue by mila76** [quasarframework/quasar#10780]
After updating axios the ajax call enter in an infinite loop
https://codepen.io/mila76/pen/wvexgoE

This codepen have 0.21.1 and work correctly
https://codepen.io/mila76/pen/abwjpdd

I already tried removing ajax bar (cant do on codepen) and all work correcty on 0.21.4

**Comment by yusufkandemir** [comment]
QAjaxBar is working correctly. If you open the network tab in dev tools, you can see that it's constantly making requests. I am not sure about the reason, but there is something about watchEffect and axios. So, it's nothing to do with Quasar.

**Comment by mila76** [comment]
But without Ajax Bar all work even with new axios. Sure is some interaction problem but is beyond me to understand why
