### ISSUE TITLE
Quasar component docs missing basic information

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10784]
First I want to say that the examples for each component are excellent and amazing!

But, I believe that there is **too little narrative**. Each component should have discussion about why I would use it, where it is appropriate and the best ways to use it. Think about how you would explain the component to a novice. For example, why would I use an avatar instead of an icon. In addition I think details about the default layout for the component would be a huge help. Does the component set a default for padding or margin, font or font size, etc. QIcon mentions left and right will change the margin. But not all components document all this type of information.

Another way of looking at it, Quasar does many things implicitly and that makes it easier to quickly get started. For advanced users there is a need to be able to look up this information to be able to understand and change the little details that can make or break an app.

An example of something severely under documented is q-item-section. It has a three sentence description. It provides no help about why I would want or need to use it. What it can do for me etc.

**Comment by metalsadman** [comment]
@julie777 Suggest a PR, so we can weigh whether your view on what's already out there is better, otherwise it's just a matter of opinion. It may be hard for you or some others to understand or fine for others, seeing as this is the first issue or comment about this then yeah, please do file a PR.
