### ISSUE TITLE
Segment component

### ISSUE THREAD

**Issue by marcusvbp** [quasarframework/quasar#108]
Hi,

Actually the tab content is placed inside a div. Maybe it will better if the content of tab can be loaded in a directive (like in the tab component in Ionic Framework: http://ionicframework.com/docs/v2/components/#tabs)

And, maybe, quasar may have a "segment component" (again, like Ionic Framework: http://ionicframework.com/docs/v2/components/#segment) for internal content page.

**Comment by rstoenescu** [comment]
I'm not sure I follow you. Specifying content in a directive is not so good. It hinders some of Vue's capabilities regarding the tab's content. Imagine complicated tabs with several other components and inline modals and so on... Did I understand correctly?

Also, the segment component is a good idea.

**Comment by smolinari** [comment]
:+1:  on the segment component addition. 

Scott

**Comment by rstoenescu** [comment]
Hi, In v0.15 you can use the new component QBtnToggle which is essentially the same thing. So closing this.
