### ISSUE TITLE
[Feature] QKnob with normal text when a certain value is set

### ISSUE THREAD

**Issue by picarsite** [quasarframework/quasar#1080]
Currently, I have a situation, where I would like to show a normal text for multiple specific values instead of just a number. I use the knob for setting a distance. For example, let's say, I set a max value of 100. When the user sets the knob on 50, instead of the number, there should be displayed "Half" instead of "50". When the user sets the knob on 100, there should be displayed "All" instead of "100". This should be dynamic that I can configure the displayed text for all values. That would be a nice feature! Thanks.
Best regards

**Comment by rstoenescu** [comment]
Will do. Thanks.

**Comment by picarsite** [comment]
You don't need to implement it. I discovered a simple solution for it. Just had to use a computed property for it. Perhaps take it to the documentation.
`<q-knob color="primary" v-model="realDistance" :min="1" :max="50">{{computedDistance}}</q-knob>`
```
  computed: { 
    computedDistance: function () {
      if (this.realDistance === 25) {
        return 'Half'
      }
      else if (this.realDistance === 50) {
        return 'Full'
      }
      else {
        return this.realDistance
      }
    }
  }
```

When the QKnob is set to 25 then 'Half' is displayed. When the QKnob is set to 50 then 'Full' is displayed.

**Comment by rstoenescu** [comment]
Forgot to close this ticket long time ago :)
