### ISSUE TITLE
Github quasar overview page need a note about contributing. 

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10807]
I found a link to the contributing guide on the page for editing an issue, when I previously created a new issue. I think it is good to make this visible. Put it in the readme that shows, or on the custom page you have laid out. The sidebar for the quasar repo has links to readme and license and contributing could be added. The quasar framework/overview page should have all these added to the sidebar.

In fact, as the quasar framework page/project is the main/top page/repo, it could use a little more description of quasar...

Thanks for providing such a great tool!

**Comment by pdanpdan** [comment]
The contributing section is right there in the readme

**Comment by julie777** [comment]
Sorry. I don’t know how I missed it.
