### ISSUE TITLE
Icongenie cuts off icon

### ISSUE THREAD

**Issue by SmileSydney** [quasarframework/quasar#10801]
**Describe the bug**
Icongenie is producing icons that has truncated the image

**Codepen/jsFiddle/Codesandbox (required)**
Not relevant

**To Reproduce**
1.  icongenie generate -m spa -i .\src\assets\offmarkeys_icon_1024.png
2. Note the input file has "OM" but the output files only have "M"

**Expected behavior**
Generated icon files should look like source file

**Screenshots**
Input
![image](https://user-images.githubusercontent.com/26997048/134599286-ba3b16fa-3828-48c2-bb1e-0d5e2a25cbc5.png)
Output
![image](https://user-images.githubusercontent.com/26997048/134599345-a7bed2c1-0851-4dbb-b0f4-066f3fae1d05.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.1.0
@quasar/icongenie 2.4.0

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows
Node: 14.16.1
NPM: 6.14.12
Yarn: 1.22.10
Browsers: Chrome 93.0.4577.82 
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

**Comment by rstoenescu** [comment]
Hi @SmileSydney ,

Cannot reproduce this one.
Tried with the image from here, which may be tampered by Github.

Can you please:
1. Confirm (again) that you are using latest IconGenie (v2.4.0) -- run `$ icongenie -v`
2. If running v2.4.0 and still having this issue, can you please send me the original image to razvan [dot] stoenescu [at] gmail [dot] com?

<img width="411" alt="image" src="https://user-images.githubusercontent.com/4665641/136988156-cf2d3d40-baf2-4bc2-9298-ad00ef367333.png">

**Comment by rstoenescu** [comment]
Please reopen with requested information.
Thank you.
