### ISSUE TITLE
QScrollArea whith slot=rigth do not scrolling it.

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1081]
### Software version

Quasar: 0.14.6
OS: Windows 10
Node: 6.10.2
NPM: 3.10.10
Browsers: Chrome 62
iOS: no test
Android: 5
Any other software related to your bug:

### What did you get as the error?
do not scrolling

### What were you expecting?
scrolling

### What steps did you take, to get the error?
simple do not scrolling

I have a <div slot="right"> whith some itens.

And above, i have a
 <div class="column items-center">
   <q-scroll-area >
     <q-list >
       ...

At a Android run OK.
But at Chrome/Win10, when i move mouse over the scroll bar of <q-scroll-area>,
 this hide and  I can not place the mouse on the scroll bar.

I think the slot=right is disturbing positioning of mouse region.

Above, my code:

<template>
  <q-layout ref="layout">
    <q-toolbar slot="header" class="glossy" style="height:10px">
      <img :src="$store.state.logo" style="border-radius:8px;margin:0 -8px;padding:0;height:50px"/>

      <q-toolbar-title style="margin-left:5px;">
        {{$store.state.estab}}
        <span slot="subtitle">{{$store.state.jargao}}</span>
      </q-toolbar-title>

      <q-btn @click="$refs.layout.toggleRight()" style="margin:8px;padding:0" big>
        <q-icon name="menu" />
        <strong>{{$store.state.userName}}</strong>
      </q-btn>
    </q-toolbar>

    <div slot="right">
      <q-list highlight>
        <q-list-header><strong>Menu do Administrador</strong></q-list-header>
        <q-item v-show="!$store.state.userName" class="row">
          <q-item-side icon="face" />
          <q-item-main>
            <q-item-tile label>Login</q-item-tile>
            <q-item-tile sublabel>Acessar o Administrador Vital</q-item-tile>
          </q-item-main>

          <q-field style="margin:0" class="col-12" :error="userHasError" error-label="Usuário/senha não encontrado">
            <q-input float-label="usuário" v-model="$store.state.userLogin" type="text"/>
          </q-field>

          <q-field style="margin:0" class="col-12" >
            <q-input float-label="senha" v-model="$store.state.passLogin" type="password"/>
          </q-field>

          <q-btn @submit.prevent="validateLogin" @click.prevent="validateLogin" color="primary">Validar</q-btn>
        </q-item>

        <q-item v-show="$store.state.userName" class="row" @click.prevent="execLogout" style="cursor:pointer;">
          <q-item-side icon="exit to app" />
          
          <q-item-main>
            <q-item-tile label>Logout</q-item-tile>
            <q-item-tile sublabel>Sair do Administrador Vital</q-item-tile>
          </q-item-main>
          
          
        </q-item>

        <q-item v-show="$store.state.userName" class="row" @click.prevent="goMain" style="cursor:pointer;">
          <q-item-side icon="search" />
          
          <q-item-main>
            <q-item-tile label>Principal</q-item-tile>
            <q-item-tile sublabel>Tela de Pedidos</q-item-tile>
          </q-item-main>
          
          
        </q-item>
      </q-list>
      <q-inner-loading :visible="showValidating">
        <q-spinner-gears size="50px" color="primary"></q-spinner-gears>
      </q-inner-loading>
    </div>

    <div class="column items-center">
      <q-scroll-area style="width:100%;max-width:100vw;height:400px;max-height:50vh;" class="bg-grey-3 round-borders shadow-2">
        <q-list dense style="margin:-5px 0 0 0;" class="row">
          <q-item :key="index" v-for="(ped, index) in $store.state.pedidos" class="col-6 mo" :class="{active: activePedido === index }" @click.prevent="clickPedido({ped, index})">
            <q-item-main>
              <q-item-tile label style="font-size:18px;font-weight:bold;">{{ped.attributes.destino.cidade}}</q-item-tile>
              <span>{{ped.attributes.destino.bairro}}</span>
              <br v-show="!ped.attributes.destino.bairro"/>
              <q-item-tile sublabel style="color:blue;font-weight:bold;">{{ped.attributes.destino.entregar?ped.attributes.destino.cep.deEnd:'RETIRAR'}}</q-item-tile>
              <br v-show="!ped.attributes.destino.bairro"/>
              <div>
                <strong>{{ped.status}}</strong>
                <div>
                  <q-item-tile icon="add circle outline" color="green" @click.prevent="plus(ped)" style="cursor:pointer;margin:5px;"/>
                  <q-item-tile icon="add circle outline" color="green" @click.prevent="plus(ped)" style="cursor:pointer;margin:5px;"/>
                  <q-item-tile icon="remove circle outline" color="red" @click.prevent="minus(ped)" style="cursor:pointer;margin:5px;"/>
                </div>
              </div>
            </q-item-main>
            
          </q-item>
        </q-list>
      </q-scroll-area>
    </div>
    

    <div class="column items-center">
      <q-scroll-area style="width:100%;max-width:100vw;height:400px;max-height:50vh;" class="bg-grey-3 round-borders shadow-2">
        <q-list highlight striped-odd dense style="margin:-5px 0 0 0;" class="row">
          <q-item :key="index" v-for="(itemPedido, index) in pedido" class="col-12">
            <q-item-main>
              <q-item-tile label style="font-size:18px;font-weight:bold;">{{itemPedido.qtE}} - {{itemPedido.it}}</q-item-tile>
            </q-item-main>
            <q-item-side right style="margin:10px;">
              <strong style="font-size:20px;align:bottom">XXX</strong>
            </q-item-side>
          </q-item>
        </q-list>
      </q-scroll-area>
    </div>

    <div v-show="Math.trunc($store.state.ttQtd)>=1" class="row bg-orange-8 fixed-bottom" style="width:100%;height:25px;">
      <div class="fixed-bottom-left" style="margin:3px;color:white;font-weight:bold">
        {{Math.trunc($store.state.ttQtd)}} ite{{Math.trunc($store.state.ttQtd)>1?'ns':'m'}}
      </div>
      <div class="fixed-bottom-right" style="margin:3px;color:white;font-weight:bold">
        {{formatVal($store.state.ttVal)}}
      </div>
    </div>
  </div>

    
  </q-layout>
</template>

Tanks,

**Comment by rstoenescu** [comment]
Can you post the full layout template, including QLayout tag? Thanks!

**Comment by rstoenescu** [comment]
Tested it and it's working fine. Please post your full layout template so I can help.

**Comment by LuizLeite** [comment]
<template>  <q-layout ref="layout">    <q-toolbar slot="header" class="glossy" style="height:10px">      <img :src="$store.state.logo" style="border-radius:8px;margin:0 -8px;padding:0;height:50px"/>
      <q-toolbar-title style="margin-left:5px;">        {{$store.state.estab}}        <span slot="subtitle">{{$store.state.jargao}}</span>      </q-toolbar-title>
      <q-btn @click="$refs.layout.toggleRight()" style="margin:8px;padding:0" big>        <q-icon name="menu" />        <strong>{{$store.state.userName}}</strong>      </q-btn>    </q-toolbar>
    <div slot="right">      <q-list highlight>        <q-list-header><strong>Menu do Administrador</strong></q-list-header>        <q-item v-show="!$store.state.userName" class="row">          <q-item-side icon="face" />          <q-item-main>            <q-item-tile label>Login</q-item-tile>            <q-item-tile sublabel>Acessar o Administrador Vital</q-item-tile>          </q-item-main>
          <q-field style="margin:0" class="col-12" :error="userHasError" error-label="Usuário/senha não encontrado">            <q-input float-label="usuário" v-model="$store.state.userLogin" type="text"/>          </q-field>
          <q-field style="margin:0" class="col-12" >            <q-input float-label="senha" v-model="$store.state.passLogin" type="password"/>          </q-field>
          <q-btn @submit.prevent="validateLogin" @click.prevent="validateLogin" color="primary">Validar</q-btn>        </q-item>
        <q-item v-show="$store.state.userName" class="row" @click.prevent="execLogout" style="cursor:pointer;">          <q-item-side icon="exit to app" />                    <q-item-main>            <q-item-tile label>Logout</q-item-tile>            <q-item-tile sublabel>Sair do Administrador Vital</q-item-tile>          </q-item-main>                            </q-item>
        <q-item v-show="$store.state.userName" class="row" @click.prevent="goMain" style="cursor:pointer;">          <q-item-side icon="search" />                    <q-item-main>            <q-item-tile label>Principal</q-item-tile>            <q-item-tile sublabel>Tela de Pedidos</q-item-tile>          </q-item-main>                            </q-item>      </q-list>      <q-inner-loading :visible="showValidating">        <q-spinner-gears size="50px" color="primary"></q-spinner-gears>      </q-inner-loading>    </div>
    <div class="column items-center">      <q-scroll-area style="width:100%;max-width:100vw;height:400px;max-height:50vh;" class="bg-grey-3 round-borders shadow-2">        <q-list dense style="margin:-5px 0 0 0;" class="row">          <q-item :key="index" v-for="(ped, index) in $store.state.pedidos" class="col-6 mo" :class="{active: activePedido === index }" @click.prevent="clickPedido({ped, index})">            <q-item-main>              <q-item-tile label style="font-size:18px;font-weight:bold;">{{ped.attributes.destino.cidade}}</q-item-tile>              <span>{{ped.attributes.destino.bairro}}</span>              <br v-show="!ped.attributes.destino.bairro"/>              <q-item-tile sublabel style="color:blue;font-weight:bold;">{{ped.attributes.destino.entregar?ped.attributes.destino.cep.deEnd:'RETIRAR'}}</q-item-tile>              <br v-show="!ped.attributes.destino.bairro"/>              <div>                <strong>{{ped.status}}</strong>                              </div>            </q-item-main>                      </q-item>        </q-list>      </q-scroll-area>    </div>    
    <div class="column items-center">      <q-list style="margin:0;width:100%;height:25px;" class="row">        <q-item class="col-12">          <q-item-main>            <q-item-tile label style="margin:-28px 0 0 3px;font-size:18px;font-weight:bold;"><span style="font-size:14px;">Item</span> Descrição</q-item-tile>          </q-item-main>          <q-item-side right style="margin:1px;">            <strong style="font-size:18px;margin:-28px 0">QTD</strong>          </q-item-side>        </q-item>      </q-list>      <q-scroll-area style="width:100%;max-width:100vw;height:180px;max-height:50vh;" class="bg-grey-3 round-borders shadow-2">        <q-list highlight striped-odd dense style="margin:-5px 0 0 0;" class="row">          <q-item :key="index" v-for="(itemPedido, index) in pedido" class="col-12">            <q-item-main>              <q-item-tile label style="font-size:18px;font-weight:bold;"><span style="font-size:14px;">{{index+1}}/{{pedido.length}}</span> - {{itemPedido.it}} {{itemPedido.sg}}</q-item-tile>            </q-item-main>            <q-item-side right style="margin:1px;">              <strong style="font-size:18px;align:bottom">{{itemPedido.qtE}}</strong>            </q-item-side>          </q-item>        </q-list>      </q-scroll-area>    </div>
    <div v-show="Math.trunc($store.state.ttQtd)>=1" class="row bg-orange-8 fixed-bottom" style="width:100%;height:25px;">      <div class="fixed-bottom-left" style="margin:3px;color:white;font-weight:bold">        {{Math.trunc($store.state.ttQtd)}} ite{{Math.trunc($store.state.ttQtd)>1?'ns':'m'}}      </div>      <div class="fixed-bottom-right" style="margin:3px;color:white;font-weight:bold">        {{formatVal($store.state.ttVal)}}      </div>    </div>  </div>
      </q-layout></template>



Luiz Leite
 

    Em sexta-feira, 3 de novembro de 2017 08:35:38 BRST, Razvan Stoenescu <notifications@github.com> escreveu:  
 
 
Closed #1081.
