### ISSUE TITLE
have quasar create automatically run git init

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10812]
**Is your feature request related to a problem? Please describe.**
I get warnings in vscode because I have a .git directory somewhere in my path above the newly created project.
I have to manually initialize a git repo for every quasar project I create

**Describe the solution you'd like**
Have quasar create <project> initialize the git repo for the project.

**Additional context**
Quasar create already runs at least one post create command to run eslint --fix on the repo.

**Comment by pdanpdan** [comment]
Yes, you have to create it. Maybe you don't want to create it, maybe you don't have git.
