### ISSUE TITLE
Import only the necessary components (auto import does not affect styles)

### ISSUE THREAD

**Issue by Verhov** [quasarframework/quasar#10814]
**Description**
When building a SPA application, all components are included in the build.

**Expected behavior**
Build `dist\spa\css\vendor.####.css` should not include unused components styles.

**Seps to reproduce**
1. ```$ quasar create quasar-test``` (all options default)
2. Optional (has no effect) `quasar.conf.js`: ```... framework: { components: ['QLayout', 'QPageContainer'], }, ...```
3. ```$ quasar build``` (screenshot)

**Screenshots**
![quasar-css-components](https://user-images.githubusercontent.com/1572713/134737246-dc83a4e8-bd60-461f-b07e-7f07b433258e.png)

**Platform:**
```
$ quasar inspect
 Dev mode.......... spa    
 Pkg quasar........ v2.1.0 
 Pkg @quasar/app... v3.1.0 
 Pkg webpack....... v5   
 ...

$ quasar info

Operating System - Windows_NT(10.0.xx) - win32/x64
NodeJs - 14.17.6

Global packages
  NPM - 6.14.8
  yarn - 1.22.5
  @quasar/cli - 1.2.1
  ...

Important local packages
  quasar - 2.1.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.1.0 -- Quasar Framework local CLI
  @quasar/extras - 1.11.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.4 -- The progressive JavaScript framework for buiding modern web UI.
  ...
  webpack - 5.53.0 -- Packs CommonJs/AMD modules...
  webpack-dev-server - 4.0.0 -- Serves a webpack app. ...
  ...
```

Thanks! Quasar awesome)

**Comment by rstoenescu** [comment]
The whole CSS is bundled because of several reasons. Most important one being that we supply Sass/SCSS variables. If we were to auto-import css then we’d need to add considerable overhead in each .vue file by adding code which requests the variables file (from devland) then each component’s css. This would make the whole compiling process take several times longer. Furthermore, the the gzipped size of the whole CSS supplied by Quasar is ~30KB anyway, so the benefit would not be great while the downside with compile time would certainly be VERY noticeable (including on HMR).

**Comment by Verhov** [comment]
Yes, that's right.
I see the `...\index.sass` is used to list all components that need to be added to the build... What if we add the option to override it in config? e.g. ```... framework: { ..., sassIndexOverride: '.\src\css\components-custom.sass', ...} ```
And in the file sets the necessary components:
```scss
/* components-custom.sass */
@import './helpers/string.sass'
@import './helpers/math.sass'

@import './variables.sass'
@import './normalize.sass'

@import '../components/icon/QIcon.sass'

/* Composables */
@import '../composables/private/use-panel.sass'

/* Components */
// (don't use) @import '../components/ajax-bar/QAjaxBar.sass'
@import '../components/avatar/QAvatar.sass'
@import '../components/badge/QBadge.sass'
// @import '../components/banner/QBanner.sass'
// @import '../components/bar/QBar.sass'
// @import '../components/breadcrumbs/QBreadcrumbs.sass'
@import '../components/btn/QBtn.sass'
// @import '../components/btn-dropdown/QBtnDropdown.sass'
...
```

**Comment by vladcosorg** [comment]
Also need this, it is possible to override the index.sass ?

**Comment by uifox** [comment]
I agree, it would be really useful if my app didn't need to include styles it never uses. This is an important consideration in apps that must perform very well. Obviously, the smaller the bundle sizes, the faster it will load and run, something respected by search engines a lot. Core Web Vital scores are negatively affected by unused CSS / JS.
