### ISSUE TITLE
SSR: async setup + suspense within router-view throws an exception

### ISSUE THREAD

**Issue by Vicher** [quasarframework/quasar#10822]
**Describe the bug**
Using async setup + suspense within router-view in SSR mode throws an exception when trying to navigate to another route if async setup not completed

**Codepen/jsFiddle/Codesandbox (required)**
[https://codesandbox.io/s/awesome-bash-6ulwu](url)

**To Reproduce**
1. Open codesandbox URL
2. Click at "Second page" link at menu
3. Now you can see error `TypeError: Cannot read properties of null (reading 'shapeFlag')` at console and second page not displayed

**Expected behavior**
No exception and second page must be displayed

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.1.0
@quasar/app Version: 3.1.0

Quasar mode:
  - [ ] SPA
  - [X] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [X] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 14.16.1
NPM: 7.8.0
Yarn: 1.22.10
Browsers: Last version of Google Chrome

**Additional context**
SPA mode working fine, only SSR has error.

**Comment by TobyMosque** [comment]
(un)fortunately, that isn't a issue with Quasar.

First of all, you need to remmeber suspense is an experimental feature, so there isn't a clear way of how to use/configure it.
As it's today, i would recommend not put a `router-view` between your suspense component and your async setups.

here a example:
https://github.com/TobyMosque/quasar-suspense-pokedex
