### ISSUE TITLE
Custom scroll bar in table

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#10825]
scroll-area has thumb-style which allow to make a modern thumb
![image](https://user-images.githubusercontent.com/1247062/134939349-6456d42a-7e3f-499a-a61d-83a38058f4ba.png)

but for q-table impossible to make something like that. I offer to eliminate non-uniformity API and add  thumb-style to q-table.
Otherwise we are doomed to watch this forever:
![image](https://user-images.githubusercontent.com/1247062/134939841-fa840f3a-0e14-419f-807a-feb59179a121.png)

**Comment by hawkeye64** [comment]
@Claus1 QScrollArea implies a custom scrollbar. That doesn't mean that all components need that. However, in devland you can easily achieve the same thing as I demonstrate in this CodePen: https://codepen.io/Hawkeye64/pen/bGRXBOY?editors=1100

**Comment by Claus1** [comment]
@hawkeye64 thanks! The solution will be interesting for many users.
