### ISSUE TITLE
component with q-dialog no longer shows in Vue devtools after upgrade to Q2

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#10828]
I have a component which launches a dialog by calling:
this.$q.dialog({
   component: NewCategoryDialog,
   ...

It used to work fine, but now when the NewCategoryDialog opens, it is not visible in the Vue devtools list of components.

**Expected behavior**
When dialog is open, the component should be available for inspection in Vue devtools component list.

**Platform (please complete the following information):**
Quasar Version: 2.1.0
@quasar/app Version: 3.1.0
Vue: 3.2.4
Chrome: latest version
Vue.js devtools: 6.0.0 beta 18

Quasar mode:
  - [x ] SPA

Tested on:
  - [x ] SPA

OS: Windows
NPM: 7.22.0
Browsers: Chrome

**Comment by pdanpdan** [comment]
The new vue dev tools have a selector for the root component (on top) - click and select on mouse wheel over it.

**Comment by CrawfordW** [comment]
Do you mean scrolling between Components, Routes and Vuex?
When I select Components, I don't see the Dialog. Here's a screen shot...
![image](https://user-images.githubusercontent.com/45148066/134959260-d1571bb4-5946-411c-bc76-a0e39882a3fd.png)

**Comment by pdanpdan** [comment]
Click where it is written App

**Comment by CrawfordW** [comment]
There's nothing there - just App. Scrolling has no effect
![Appshot](https://user-images.githubusercontent.com/45148066/134960238-96e0e5e7-d729-4d71-9e4e-8e3a43ef2de4.png)
.

**Comment by MilosPaunovic** [comment]
Have you tried to use the third icon from the right in the top header of the `VueDevtools`, the little circle like target, it's component selector? You should click on dialog with it and it should highlight that part of the code in the component listing.

**Comment by CrawfordW** [comment]
Wow that works great! Thanks for the tip!
So much to learn since upgrading!
How do I close this issue now?

**Comment by MilosPaunovic** [comment]
It's already closed, don't worry.
