### ISSUE TITLE
QDialog - "keep alive" hidden dialog

### ISSUE THREAD

**Issue by aleksander237** [quasarframework/quasar#10830]
I'm incorporating quasar framework into a legacy system. I want to open a legacy page in an iframe in the QDialog. Unfortunately each time I close the dialog (set v-model to false) the markup of the dialog is removed from the page and the iframe gets destroyed. When i reopen the dialog, the iframe is loaded again which is time consuming. 

I was trying wrap the q-dialog into keep-alive but it does not work.

I would like to have a prop on thie QDialog component which let me decide if I want to preserve the content after the dialog is closed. This way I can redisplay the dialog with "heavy content" faster.

**Comment by pdanpdan** [comment]
Something like this cannot be done, sorry.

**Comment by wt0m** [comment]
I also need this, it is possible in MUI for React and I really miss it in Quasar.
Just a keep mounted prop so the dialog is only hidden/shown when needed.

**Comment by orioncx** [comment]
I guess you can achieve that by something like:

`dialogRef.value.$el.style['display']='none'`
