### ISSUE TITLE
Wrong Variable IMEI in cordova example

### ISSUE THREAD

**Issue by geminigeek** [quasarframework/quasar#10837]
hi the variable is in All Caps in template, but in setup its in lower caps, it causes error, possibly  it will be an issue for a new users.

its on this page https://quasar.dev/quasar-cli/developing-cordova-apps/cordova-plugins

replace
`<div>IMEI: {{ IMEI }}</div>`

with
`<div>IMEI: {{ imei }}</div>`

**Comment by pdanpdan** [comment]
Please make a PR for the fix, thank you.

**Comment by rstoenescu** [comment]
Thanks for the PR! Will be available on next docs deployment.
