### ISSUE TITLE
[Bug]Textarea can not show all rows when textarea is hidden by default

### ISSUE THREAD

**Issue by mrene327** [quasarframework/quasar#1083]
Quasar: 0.14.6 (mat theme)
OS: all desktop platform
Browsers: Chrome 62
Vue.js 2.5.2

The textarea with multiple rows of data and it is hidden by default(the 'hidden textarea' in following example), and then, show it by some operation(such as click a button), the textarea just show 2 rows data.
But if the textarea is visible by default(the 'visible textarea' in following example), it can show all rows data.
**Expected:**
The textarea should show all rows of data whether it is visible or hidden by default.

I know if I use v-if can solve the issue, but in my project, the page has so many fields and the user may be switch the status frequently, so, I hope use v-show instead of v-if.

```html
<template>
  <div>
    <q-btn @click="showTextarea=!showTextarea">show</q-btn>
    <div v-show="showTextarea">
      <q-input
       name="hidden textarea"
        type="textarea"
        v-model="textareadata"
        float-label="hidden by default"
      ></q-input>
    </div>
    <q-input
      name="visible textarea"
      type="textarea"
      v-model="textareadata"
      float-label="visible by default"
    ></q-input>
  </div>
</template>
```

```js
<script type="text/javascript">
import {
    QInput,
    QBtn,
  } from 'quasar'
  export default {
    data () {
      return {
        showTextarea: false,
        textareadata: "1\n2\n3\n4\n5\n6",
      }
    },
  components: {
      QInput,
      QBtn
    }
  }
</script>
```

**Comment by IMRosalado** [comment]
bump. Have same problem

**Comment by rstoenescu** [comment]
Please upgrade to v0.16 (v0.15 with almost no breaking changes) and let me know if it still happens. I could not reproduce it with v0.16. Thank you.
