### ISSUE TITLE
[APP] dependency problem during the build process [spa -> electron] [local modules]

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#10840]
Hello,
I have several observations regarding the build process.

**Describe the bug**
1) I noticed that if we add local dependencies to a project, the build process fails to build an **Electron** application.
ex:
```
*project_test
|
|--- dist
|--- node_modules
|--- local_node_modules
|--- src
|--- [...]

```
``` yarn add file:./local_node_modules/libXXX ```

``` yarn build -m spa  ```
-> **GOOD**
``` yarn build -m electron -T linux ```
-> **ERROR**
```
[2/5] Resolving packages...
error Package "libXXX" refers to a non-existing file '"/home/user/quasar_projects/project_test/dist/electron/UnPackaged/local_node_modules/libXXX"'.
```
I think it's because Quasar CLI copies the **package.json** file in **dist/electron/UnPackaged** without modifying the relative Paths.
package.json :
```
"dependencies": {
...
"libXXX": "file:./local_node_modules/libXXX"
...
}
```
he must add to the path : file: +  **../../../** + ./local_node_modules/libXXX

---

2)  during the electron build process, it performs an installation step, which is unnecessary and requires an internet connection.
App •  DONE  • "Renderer" compiled with success •
--> `App • Running "yarn install --production"`

---

**Platform (please complete the following information):**
Quasar Version: 2.1.0
@quasar/app Version : 3.1.0
 Build mode........ electron
 Pkg quasar........ v2.1.0
 Pkg @quasar/app... v3.1.0
 Pkg webpack....... v5

Thank you so much for this wonderful framework.

**Comment by yusufkandemir** [comment]
You can use `quasar.conf.js > build > extendPackageJson` to update it, please see https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron#quasar-conf-js. It would probably be something like:
```js
// optional; add/remove/change properties
// of production generated package.json
extendPackageJson (pkg) {
  // directly change props of pkg;
  // no need to return anything
  const prefix = 'file:';
  const [, originalPath] = pkg.dependencies.libXXX.split(prefix);
  pkg.dependencies.libXXX = prefix + '../../../' + originalPath;
},
```

As an alternative solution, you can also try using webpack-chain to move `local_node_modules` to `dist/electron/UnPackaged`.

**Comment by RejDev** [comment]
Thank you @yusufkandemir , i will try what you suggested.
