### ISSUE TITLE
q-input mask does not work when input type is number

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#10847]
Please see the codepen: https://codepen.io/bigradish/pen/powYogE
Thank you.

**Comment by pdanpdan** [comment]
Please see the docs
https://v1.quasar.dev/vue-components/input#mask

**Comment by bigradish** [comment]
@pdanpdan Sorry for my oversight of the doc.
Is it possible to add the support for the mask feature for the number input type? For on mobile phone, the number type will use the number keyboard directly.
Thank you very much.

**Comment by pdanpdan** [comment]
It's not possible, but as a workaround use type tel.
