### ISSUE TITLE
Visual bug when using QTable with sticky header/column and custom loading

### ISSUE THREAD

**Issue by frost18** [quasarframework/quasar#10849]
**Describe the bug**
Backgrounds conflicts when using QTable with sticky header/column and custom loading

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/frost18/pen/QWgYMvx

**To Reproduce**
1. Use QTable
2. Add styles from documentation for sticky header/column
3. Implement custom loading from documentation
4. Toggle loading

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.4

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by metalsadman** [comment]
@frost18 use `z-max` in your custom inner loader. https://codepen.io/metalsadman/pen/MWoxwxy
