### ISSUE TITLE
Any plans for a Desktop theme?

### ISSUE THREAD

**Issue by hmexx** [quasarframework/quasar#1084]
I'm evaluating which UI component library to use for our VueJS app. They all seem to have pros and cons. The only thing I don't like about Quasar is that I have to choose either material or ios, for my dekstop front-end, whilst something mobile-agnostics would look better on desktops.

Great work btw.

**Comment by rstoenescu** [comment]
Hi,

There's a confusion somewhere. Themes have nothing to do with writing a desktop or mobile app. You just pick one and develop your website. The responsiveness is still there.

Please help me understand better what you are thinking. Thanks.

**Comment by hmexx** [comment]
I'm happy to elaborate. You currently have 2 themes. One matches the iOS look&feel, and the other matches the Android look&feel.  Of course, there is no definite look & feel on desktop-focused websites, so you CAN use either of those themes, but it won't look as good, or as professional, as a set of styles that doesn't look like an Android or iOS app.

Does that make sense?

**Comment by rstoenescu** [comment]
Material design, as an example, is not used ONLY on Android mobile apps. It's used on websites too (check any of the Google services). People usually pick the "Material" theme when building a website with Quasar. And it looks quite good. Check this: http://quasar-framework.org/quasar-play/android/index.html#/showcase. **Everything is configurable, you can create any design with it.**

I'd recommend starting to take a look at QLayout (check and play with it, you'll certainly like it). It may be what you are looking for. Mind that QLayout is not required, but certainly helps you a lot in designing your responsive website.

**Comment by hmexx** [comment]
Yeah. I know Google uses that look&feel but for me it doesn't work well at all on big screens. Anyway, not a big deal if you're not making any more themes. I'll evaluate all my options and make a decision. Thanks for responding.

**Comment by rstoenescu** [comment]
Thanks for offering more details on what you think, but not sure what you mean by "doesn't works well at all on big screens". Why shouldn't it? Any example? I might shed some light on this.

**Comment by hmexx** [comment]
It's just a subjective view. For the same reason that I don't enjoy a visual style that reminds me of iOS on my desktop apps, I also don't enjoy a visual style that I got used to on Android phones. Check out Element for example of a visual style that looks more "desktop"-ish http://element.eleme.io/#/en-US

**Comment by WhatFreshHellIsThis** [comment]
I can help with this as I'm going through the same evaluation process.  To me the initial example of this issue that I ran into is the date picker component.  On desktop a Material or IOS style datepicker is weird looking and hard to use (particularly the IOS one).
