### ISSUE TITLE
Nodejs version does not include crypto generateKeyPairSync

### ISSUE THREAD

**Issue by dsportes** [quasarframework/quasar#10843]
Function generateKeyPairSync of crypto (Node) is available from v10.
Running quasar dev (with node version 14.16.0) has the issue: the crypto package does not expose generateKeyPairSync.
My app requires generating such key pairs on the client side.
How to do ?
Thanks

**Comment by pdanpdan** [comment]
Hello. You are not running node on client side.
Please use the discord channel or the discussions in github for help requests.

**Comment by dsportes** [comment]
OK you are right, I'm not under Electron and strictly speaking not running node on client side.
But I use node packages on client side, typically "crypto" _as if_ I'm running node.
Why the function generateKeyPair is not exposed while other asymetric encryption functions are ?
Thanks
