### ISSUE TITLE
Explain how the scrollTarget element is auto detected for QInfiniteScroll

### ISSUE THREAD

**Issue by Seanitzel** [quasarframework/quasar#10846]
When using the QInfiniteScroll component inside a QDialog, the Infinite scroll is scrolling and calling the onLoad function endlessly.

Codesandbox:
https://codesandbox.io/s/qdialog-qinfinitescroll-cf6tk?file=/src/components/InfiniteScroll.vue

**To Reproduce**
1. Go to https://codesandbox.io/s/qdialog-qinfinitescroll-cf6tk?file=/src/components/InfiniteScroll.vue.
2. Click the 'Click to open dialog' button,
3. Watch as it scrolls endlessly without you touching the mouse.

**Expected behavior**
The InifiniteScroll to only call the onLoad method when the user scrolls past the breaking point.

**Platform (please complete the following information):**
Quasar Version:  2.1.0
@quasar/app Version:  3.1.0

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac
Node: 14.17.0
NPM: 7.21.1
Yarn: 1.22.11
Browsers: Chrome
iOS:
Android:
Electron:

**Comment by rfox12** [comment]
@Seanitzel I took a look at your codepen... please keep in mind the tip on the [documentation page for Infinite Scroll](https://quasar.dev/vue-components/infinite-scroll#introduction):

**"Infinite Scroll loads items in advance when less than `offset` (default = 500) pixels is left to be seen. If the content you fetch has height less than the scroll target container’s height on screen then Infinite Scroll will continue loading more content. So make sure you load enough content."**

So in this case, because you're not reaching that 500 threshold, QInfiniteScroll is simply preloading everything when you modify your items model.

And also because your list is reversed (new items on top), the list will have to scroll to show new content right?

**Comment by Seanitzel** [comment]
Thank you for taking a look!

I tried it with the offset as well and i keep getting the same behavior...

I updated the codepen.

If you can make it work in the codepen or give me another example that can be great!

**Comment by MilosPaunovic** [comment]
You've never told the `QInfiniteScroll` component when to stop.

You need to test a condition, and, if it is met, you need to pass `true` to `done()` function.

Check out the `Events` part `QInfiniteScroll` API.
https://quasar.dev/vue-components/infinite-scroll#qinfinitescroll-api

**Comment by Seanitzel** [comment]
I don't want it to stop though, i want it to load more when it is scrolled to the bottom.

If the offset is 250, and it loades more elements when we open the dialog, then it should stop loading more until we scroll to the bottom of the component so we reach the offset.

Am i missing something?

**Comment by MilosPaunovic** [comment]
I'm not really sure that I understand what are you trying to accomplish, but could it be that the `reverse` prop brings in the confusion?

`reverse` : Boolean
Scroll area should behave like a messenger - starting scrolled to bottom and loading when reaching the top

**Comment by Seanitzel** [comment]
My goal is to have an infinite scroll that works like the example on the [API](https://quasar.dev/vue-components/infinite-scroll#qinfinitescroll-api) inside a dialog.

the same happens when i remove the reverse prop...
It just scrolls infinitely.

I have a component that can be seen on it's & within a dialog, No matter what i tried I can't make it work inside the dialog as expected = load more elements only when scrolled to the bottom

**Comment by MilosPaunovic** [comment]
So, you want this?

[https://codepen.io/milospaunovic/pen/KKvwdQo?editors=101](https://codepen.io/milospaunovic/pen/KKvwdQo?editors=101)

**Comment by Seanitzel** [comment]
Yes, notice that in your codepen as well, it keeps loading more elements infinitely regardless of the user scrolling in the dialog lol

That is my issue

**Comment by MilosPaunovic** [comment]
Well, that happens because we're not telling it where to stop.

Usually, there will be a data property returned from the backend which will tell us how many total results there are, and then we can check that condition, and if it's met, call `done(true)` to stop loading.

**Comment by Seanitzel** [comment]
That doesn't happen when not inside a dialog.

In my case i don't fetch the data from a backend, i simple load more elements that reside on the client.

https://codepen.io/pen/?&editors=101
This is exactly the behavior i'm trying to achieve, but inside a dialog.

Notice how it loads more elements untill the offset in the scroll bar is not satisfied, that's when the onload callback stops.

**Comment by MilosPaunovic** [comment]
Your codepen link is broken, but try this one out, I've maximized the content of the dialog.

[https://codepen.io/milospaunovic/pen/KKvwdQo?editors=101](https://codepen.io/milospaunovic/pen/KKvwdQo?editors=101)

**Comment by pdanpdan** [comment]
In order to make QInfiniteScroll's container auto detection work you need to have a scrolling container with class `scroll`.

https://codepen.io/pdanpdan/pen/PoKwNdY?editors=1010

**Comment by Seanitzel** [comment]
@pdanpdan That is exactly what i wanted, thanks!
I don't see that mentioned in the docs though

Sorry about the broken codepen link
@MilosPaunovic btw the bug occures on the codepen you shared as well lol

Thanks for all your help guys! <3

**Comment by pdanpdan** [comment]
Yes, the docs would need this detail. Reopening.
Can you please change the name of the issue in `Explain how the scrollTarget element is auto detected for QInfiniteScroll`?

**Comment by Seanitzel** [comment]
Changed the name :)

Btw, your example doesn't work when using a maximized dialog...
Couldn't get it to work on my codebase 😢

**Comment by pdanpdan** [comment]
It works just fine when maximized - check the warning in the docs (if you don't fill the scrolling container there is no loading - so make sure the scrolling container is not bigger than the elements in the list)
https://codepen.io/pdanpdan/pen/PoKwNdY?editors=1010
