### ISSUE TITLE
add `no-shake` props for `q-dialog`

### ISSUE THREAD

**Issue by Debonex** [quasarframework/quasar#10857]
**Is your feature request related to a problem? Please describe.**
I'm trying to embed a web shell into `q-dialog`, I need to press the Esc key inside to control the remote server, so I want the dialog not to be closed when the user presses the Esc key, and without shaking, the `seamless` props seems to be able to achieve this Effect, but I also want to keep the backdrop enabled

**Describe the solution you'd like**
Add a props to prevent shake behavior

**Describe alternatives you've considered**
I noticed that the Dialog will be hidden when emitting `escape-key` event, if there is a way to let me control the behavior when `escape-key` be emitted, it will be nice

**Additional context**

**Comment by hawkeye64** [comment]
@Debonex Your PR was merged. I can't say when there will be a build that includes it.

**Comment by hawkeye64** [comment]
Most likely this weekend
