### ISSUE TITLE
QScrollArea, position of the scroll bar [Left, Right] [Top, Bottom]

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#10851]
Hello,

It would be really great if we could choose the position of the scroll bar in QScrollArea, be able to put it [to the right / to the left] for the vertical scroll, or [Top / Bottom] for the horizontal scroll. (or both)

(i tried playing with dir = "rtl", but it doesn't work.)

thanks in advance.

**Comment by rstoenescu** [comment]
You can do it through the styling props.

Example:

```html
<q-scroll-area
      :horizontal-thumb-style="thumbStyleHorizontal"
      :vertical-thumb-style="thumbStyleVertical"
```
where:
```js
thumbStyleHorizontal: {
        top: '2px',
        opacity: 0.75
      },

      thumbStyleVertical: {
        left: '2px',
        opacity: 0.75
      }
```

This is for the thumb. But there are also the `vertical-bar-style` and `horizontal-bar-style` props for the bar itself, should you want to customize that as well.

**Comment by RejDev** [comment]
Thank you very much, @rstoenescu
