### ISSUE TITLE
[v0.15] QTable descending -->ascending (not working)

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1085]
### Software version

Quasar:**0.15**
OS:Windows 7 & Linux
Node:6.11.5
NPM:4.1.2
Browsers:Chrome
iOS:N/A
Android:N/A
Any other software related to your bug:

### What did you get as the error?
The QTable sorting is not working properly, we have to click 2 times instead of 1 time to invert the sorting order while going from `descending to ascending`.

### What were you expecting?
Going from descending to ascending take only one click, not two.

### What steps did you take, to get the error?
Using the [test page](https://github.com/quasarframework/quasar/blob/dev/dev/components/components/data-table.vue) I click on a sortable column one time, then click a second time. I repeat this step a couple of time and this is not working while going from descending to ascending.

Ordered ascending
![image](https://user-images.githubusercontent.com/7946730/32331221-b9d3f124-bfb8-11e7-9d16-121c00a43aa4.png)

I click ONE time on the same column and then nothing is reverted.
![image](https://user-images.githubusercontent.com/7946730/32331244-c6e893f6-bfb8-11e7-9c62-8119f87c839c.png)

I digged a little bit into the code and sometime we get `undefined` for `this.columnToSort` on this line
https://github.com/quasarframework/quasar/blob/a2ea80f53fc6d9190b4b12803956860d00ed94e9/src/components/table/QTable.js#L104

**Comment by rstoenescu** [comment]
The user needs to also remove sorting. So sorting has 3 stages: none, ascending, descending. Clicking goes from one to the next one.

**Comment by purell** [comment]
My fault, sorry. You're right, none is required to cancel the sort I had not thought about it.
Thank you for your time.

**Comment by piotrh** [comment]
3 stages for sorting makes server side sorting more complicated.

**Comment by rstoenescu** [comment]
Added `binary-state-sort` Boolean prop to QTable in Quasar v0.17.11 which enables 2 stages (ascending, descending) only.
