### ISSUE TITLE
Select with use-input: show input field only on focus

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#10856]
If a selection is used like the first from the Filtering options example: https://quasar.dev/vue-components/select#native-attributes-with-use-input and the options label is longer than the select. The input is moved below the "label" and creates a extra line.

We only want the select to be one line high (if not focused), so we already overwrite the selected-item slot and put the label into a span with ellipsis. But the input is auto generated/added and we cannot control it in a simple way.

So we would like it to be possible to hide that input and only show and focus it if the select is focused/clicked?
Like with a :show-input-on-focus property?

**Comment by chaosKP** [comment]
Okay, I got it to work with CSS:
.q-field__input {
  min-height: 0;

  &[aria-expanded="true"] {
    min-height: 24px;
  }
}
But a native solution would be better.

**Comment by pdanpdan** [comment]
Can you please fix the codepen link so we can play with it?

**Comment by chaosKP** [comment]
it was just the link to the codepen from the quasar website, I fixed the description.
