### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined is date formatDate

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#10885]
new project

﻿import { date } from 'quasar';
const { formatDate } = date;
const newDate = new Date();
const pId = formatDate(newDate, 'X');

`app.js:1642 Uncaught TypeError: Cannot read properties of undefined (reading 'date')
    at formatDate (date.js?bd4c:846)`

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.4
