### ISSUE TITLE
Since upgrading to 0.14.6 dialog fails to close

### ISSUE THREAD

**Issue by sysmesh** [quasarframework/quasar#1088]
### Software version

Quasar: 0.14.6
OS: Windows 10
Node: 8.6.0
NPM: 5.4.2
Browsers: Chrome & FireFox
iOS:
Android: Material theme
Any other software related to your bug:

In a simple vue component I've created a method that pops a simple Dialog as follows:
let tmpDialog = Dialog.create({
                    title: 'My Dialog',
                    noBackdropDismiss: false,
                    buttons: [
                    {
                        label: 'save',
                        preventClose: true,
                        handler(data, closeThis) {
                            // Validate all form inputs are in place
                            closeThis()l;
                        }
                    },
                    {
                        label: 'cancel',
                        handler(data) {
                            console.log("closing");
                        }
                    }
                ],
                form: {
                    header1: {
                        type: 'heading',
                        label: 'What is your name?'
                    },
                    name: {
                        type: 'text',
                        model: ''
                    }                    
                }
 });

The Dialog fails to close when clicking on ANY of the buttons. It also doesn't close when hitting ESC or clicking outside the dialog.
No errors are showing in the console.
This worked fine with older Quasar versions but stopped working since upgrading to 0.14.6

**Comment by rstoenescu** [comment]
Hi,

You have a JS error there: `closeThis()l;` --> remove that ending "l" character --> it halts JS code

**Comment by sysmesh** [comment]
Please don't close it.
The "l" there is a copy-paste mistake when I re-typed my code here and it isn't in my code.
Close/save doesn't work nor close the dialog regardless of the typo. Seems to be a version bug?

I've now tried a new blank dialog and got the same results: seems it doesn't even go into the handler() function. The console.log doen't print and NO JS error show on the console.

**Comment by rstoenescu** [comment]
Seems like you opened a new one. We'll continue there.
