### ISSUE TITLE
Quasar boot error before ios v12.5.4 although browser support included

### ISSUE THREAD

**Issue by abnerwang06** [quasarframework/quasar#10896]
**Describe the bug**
This issue is related to [#10679](https://github.com/quasarframework/quasar/issues/10679)
I've supposed the  browserslist did not include the required version, but it supported.
I used the default config(photo 1), and it supported the following version(photo 2).
**Screenshots**
![image](https://user-images.githubusercontent.com/33473028/135974527-b6cadc07-1302-4622-ae73-8ae57ad111b9.png)
![image](https://user-images.githubusercontent.com/33473028/135974586-a2fb1781-fa93-4640-abde-2e72563d9d5d.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.4

Quasar mode:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers: safari, chrome
iOS: 12.5.4
Android:
Electron:

**Additional context**
The same browserslist config in Quasar v1 does not throw this error in the same version of iphone.

**Comment by rstoenescu** [comment]
Hi. Can you pls create a reproduction repo or fork https://codesandbox.quasar.dev ?

**Comment by abnerwang06** [comment]
Sorry, [it](https://github.com/quasarframework/quasar/issues/10679#issuecomment-919784922) is in the folder ,.quasar, which is produced by using “quasar dev” command to start the server.
Maybe, it is caused by the difference of the version of webpack between Quasar v1 and v2.

**Comment by rstoenescu** [comment]
The .quasar folder is generated based on your code in /src, so please create a reproduction repo or fork our codesandbox so we can investigate.

**Comment by rstoenescu** [comment]
Please reopen with the requested reproduction repo or forked codesandbox.
We cannot make any progress on this otherwise.
