### ISSUE TITLE
SAAS json importer requires duplication in configuration

### ISSUE THREAD

**Issue by MikeDanilov** [quasarframework/quasar#10897]
**Describe the bug**
In my quasar application I want to create shared variables in json file which will be accessible in js files as well as quasar.variables.scss file. For that purpose I use `node-sass-json-importer` package. But once I've imported json file in quasar.variables.scss file I got an error. During debugging I found that importer returns correct data and an error occured somewhere afterwards. Suddenly duplication of configuration fixed the issue.
**Question**: is it intentionally and is there any reason for that or duplication should be fixed?

**To Reproduce**
1. Create quasar application using quasar cli
2. Create _/src/css/quasar.variables.json_ file with the following data  `{ "darkColor": "#2A3746" }`
3. Import json file into _quasar.variables.scss_ file like this `@import "./quasar.variables.json";`
4. Install `node-sass-json-importer` package using yarn add --dev node-sass-json-importer
5. Update quasar.conf.js file to include 
```
const jsonImporter = require('node-sass-json-importer');
....
build: {
...
scssLoaderOptions: {
      sassOptions: {
        importer: jsonImporter({
          convertCase: true,
        }),
      },
    },
...
}
```

**Expected behavior**
Project build and quasar.variables.scss contains $dark-color: #2A3746

**Actual Result**
Project build with errors

**Screenshots**
![image](https://user-images.githubusercontent.com/3873098/136020944-228cb858-81cf-42b5-ad04-96a186c97f4c.png)

**Platform (please complete the following information):**
Quasar Version: 2.0
@quasar/app Version:

Quasar mode:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: v16.9.0
NPM:7.21.1
Yarn: 1.22.11
Browsers: Chrome

**FIX**
To fix the issue we had to duplicate configuration like that
```
scssLoaderOptions: {
      sassOptions: {
        importer: jsonImporter({
          convertCase: true,
        }),
      },
    },
    sassLoaderOptions: {
      sassOptions: {
        importer: jsonImporter({
          convertCase: true,
        }),
      },
    },
```
and then everything worked fine.

**Comment by hawkeye64** [comment]
You should ask them for a webpack v5 example.The ones on their site are for v1 and v2. It was also published a year ago, so may not work with webpack v5 at all.

**Comment by MikeDanilov** [comment]
@hawkeye64  I think I'm using approach from quasar doc. Who I should ask for webpack v5 example?
I can see in quasar doc this 
![image](https://user-images.githubusercontent.com/3873098/136036872-7db66dd7-990a-4b1d-8319-0ee88e38f694.png)

and I'm using those options in configuration. The solution works but I'm wondered why I have to duplicate this for both configuration instead of having only one.

**Comment by hawkeye64** [comment]
I don't know, but this really isn't a Quasar issue. As I said, I would approach the respective repo and ask there. Once you have what you want from then and need help integrating it into quasar.conf.js, feel free to open a discussion (not an issue). Thanks.
