### ISSUE TITLE
[Bug] Mousedown on element with tooltip, makes tooltip re-appear

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#1090]
I have put a tooltip inside a radio button and I noticed that when I mousedown on that radio button, the tooltip disappears and re-appears (like flickering). Is this intended?

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting.

**Comment by slowaways** [comment]
I cannot reproduce!

**Comment by rstoenescu** [comment]
I believe this was fixed a while ago. Closing. Please reopen if it happens again.
