### ISSUE TITLE
[Feat]: Add `ripple` property to QItem (same as QBtn)

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#10907]
**Is your feature request related to a problem? Please describe.**

On Discord, several people want a clickable QItem, but they want to turn off the ripple.

**Describe the solution you'd like**

Same as QBtn

![image](https://user-images.githubusercontent.com/10262924/136209252-e259b5df-b08e-4f9b-83aa-7e914067cfaf.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by pdanpdan** [comment]
You can add the ripple using the `v-ripple` directive and it already has configuration available.
If you don't add the directive you have no ripple.

**Comment by hawkeye64** [comment]
The issue is with QItem. If you add the property `clickable` are you saying adding the `v-ripple` directive, you can turn it off on QItem?

**Comment by pdanpdan** [comment]
Adding v-ripple adds the ripple.

**Comment by hawkeye64** [comment]
Adding `clickable` adds the ripple. I will test on CodePen.

**Comment by hawkeye64** [comment]
Ahh, nvm, I see it now. They all have `v-ripple`.
