### ISSUE TITLE
Quasar 2: Locale not updated after language switch

### ISSUE THREAD

**Issue by yalinliu99** [quasarframework/quasar#10911]
Quasar 2 latest version, after switching language to fr, UI language correctly changed to French, but $q.lang.getLocale() is still my browser default: en-GB, however $q.lang.isoName returns the correct value fr. $q.lang.getLocale() has not been updated.

**Comment by pdanpdan** [comment]
Yellow box https://quasar.dev/options/app-internationalization#detecting-locale

**Comment by yalinliu99** [comment]
@pdanpdan Thank you for highlighting this
