### ISSUE TITLE
How to modify bex manifest.json during build to modify some paths like quasar does in changing www/bex-background.js to www/js/bex-background.js

### ISSUE THREAD

**Issue by keinagae** [quasarframework/quasar#10917]

**Comment by rstoenescu** [comment]
Implemented this for Quasar v2 with the upcoming Quasar CLI on Vite (unreleased as of writing these lines though). Will be available through: quasar.config.js > bex > extendBexManifestJson (json)

However, you can change it manually or through quasar.conf.js > build > afterBuild -- where you'd read the output file and make the necessary adjustments.
