### ISSUE TITLE
quasar wrap not working - error: Could not install from (path_of_nodejs_modules) as it does not contain a package.json file

### ISSUE THREAD

**Issue by rheingold** [quasarframework/quasar#1091]
Hi, anybody an idea, whats wrong here (see attached image), before I'll have to make a deepdive into the sources? Such error does not help when doing first hands-on!
Thanks

![quasar_wrap_not_working](https://user-images.githubusercontent.com/10280242/32374620-d229b268-c09e-11e7-9347-b202e50eba5d.png)

![obrazek](https://user-images.githubusercontent.com/10280242/32374776-5c5ece50-c09f-11e7-8a10-df696dbe011f.png)

**Comment by rstoenescu** [comment]
Please report this to Cordova devs. This has nothing to do with Quasar. Thanks.

**Comment by rstoenescu** [comment]
Have you also tried upgrading to latest Cordova?

**Comment by rheingold** [comment]
Hi, thanks. I have the latest Cordova ... as allready stated, doing this as a first hands-on, my Cordova is 7.1.0, yesterday installed from npm.
Reported as: https://issues.apache.org/jira/browse/CB-13536

**Comment by rheingold** [comment]
Hi, I have been redirected from corodva support back here: Please would there be a possibility for you to give a little more specific answer, in what moment this "cordova-related" error occurs? Eg. what command is "quasar wrap" issuing to cordova at that moment? Is there anything I could do to find out (some more verbose log etc.)? Thanks

**Comment by rstoenescu** [comment]
"quasar wrap" calls "cordova create cordova [..rest of params]" then makes a symlink for /cordova/www to point to /dist folder. And this is it. Reference: https://github.com/quasarframework/quasar-cli/blob/dev/bin/wrappers/cordova/install.js#L43

You can manually do the above and then fill this out in the Cordova bug.

**Comment by rheingold** [comment]
Thx a lot, fowarded and tested, the same issue results, have posted to the respective cordova issue ticket.

**Comment by rstoenescu** [comment]
Let me know how it goes. I am very interested in this. Thanks.

**Comment by rheingold** [comment]
Hi, the issue has been diagnosed - this behaviour of cordova is exhibited when the nodejs modules are not being installed into default directories, so perhaps some bug in cordova not expecting such a situation (but only in the effective code I think, because the paths in the error message were correct). For further details see my final repsonse in the ticket https://issues.apache.org/jira/browse/CB-13536?focusedCommentId=16255204&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16255204 

So far this does not concern quasar and thanks for your assistance with the pinpointing of the issue.

**Comment by janpio** [comment]
Or in other words: 
If Cordova is installed as documented (`npm install -g cordova`) everything works fine.

**Comment by rheingold** [comment]
The issue has evolved into https://issues.apache.org/jira/browse/CB-13588

**Comment by rheingold** [comment]
@janpio This is not entirely correct - as shown in https://issues.apache.org/jira/browse/CB-13588 the nodejs global node_modules folder has to be on exact place in C:\Users\%USERNAME%\AppData\Roaming\npm in order for this to work. If the nodejs has been installed in any other location, then - not important what technique one may employ to force any 'npm install [-g] <module_name>' go to that installation directory instead of "Roaming" - Cordova fails to copy the template files.

**Comment by janpio** [comment]
> as shown in issues.apache.org/jira/browse/CB-13588 the nodejs global node_modules folder has to be on exact place in C:\Users%USERNAME%\AppData\Roaming\npm in order for this to work. 

No it does not as you can see when you installed node via nvm-windows for example. Everything working, nothing in that folder.

If you mess with your npm before or use other command line options that are not documented to be used for a Cordova installation, that, of course, can cause all kind of problems like the one you are experiencing. But let's keep this to the Cordova issue where I try to actually understand what specific param you are using is causing the problem and if this is a honest problem that can be fixed in Cordova.

**Comment by rheingold** [comment]
Sorry, but that is an incorrect statement, since as you might observe from the "junction" I had to use (see screenshot below), in order to point the nvm into the correct directory, which was - once again - in Roaming. 

![12897980_cordova_create_over_nvm_std_dirs](https://user-images.githubusercontent.com/10280242/32955481-63e88612-cbb6-11e7-8b0f-0fc297af8f17.png)

Forcing nvm into a different directory has resulted into the same problem.

![
![12897764_nvm_cordova_create](https://user-images.githubusercontent.com/10280242/32955488-6916d648-cbb6-11e7-917f-9e39deb3715a.png)

**Comment by janpio** [comment]
A proper nvm installation via nvm-windows (following its README) will put the node installations in e.g. `C:/nvm` where you will have a folder for each node version which will contain a `node_modules` folder with the global packages (installed with `-g`). Otherwise, it would be impossible for each node to have its own set of global npm packages. No Roaming involved.

**Comment by rheingold** [comment]
Very sorry, but this is what I get (when uninstalled nodejs and cleaned any npm traces) when starting nvm-windows installer:
![obrazek](https://user-images.githubusercontent.com/10280242/32956849-59e432fc-cbba-11e7-995b-73812073d5f2.png)

**Comment by rheingold** [comment]
Ok, so I have the root-cause of the issue. The problem emerges, when the NODEJS directory is installed in a directory path where one of the directory names contains a "@". The cordova-create module then uses the "@" character as a decission point (see here: https://github.com/apache/cordova-create/blob/53d5894c849193073e65727033e27c8d2e428ac8/index.js#L191) and launches code that is not being run, when the directory path of nodejs node_modules does not contain the "@". For me usable as workaround so far (although it makes a little mess in my directory structure), but I hope somebody will be able to alter the code appropriately to the fact, that in Windows a "@" character is a valid directory name character.
The issue has been reported and is hopefully finally here in this ticket, whose further fate I cannot influence: https://issues.apache.org/jira/browse/CB-13590

**Comment by rheingold** [comment]
(
And just as a precaution before a flame should start here about the "@" character in the directory names:
1. The platform (Windows) makes this possible, it was designed that way, so that is how the world is. 
2. I use this syntax deliberately for my directories containing my work (if I would be with IBM, then the directory for my work data would by '@IBM'), which, since I work for multiple companies, is a perfect solution being ordered at the begining of my documents directory and also the meaning "at" is a handy shortcut. Thanks for understanding.
)
