### ISSUE TITLE
FR: Add an option to QBtnDropdown to hide the dropdown icon on the side

### ISSUE THREAD

**Issue by idc77** [quasarframework/quasar#10920]
**Is your feature request related to a problem? Please describe.**
QBtnDropdown always shows the dropdown caret.
If I,for instance, want a 3-dots menu, material-style, without the dropdown icon, it's not possible to have that. The caret uses up valuable screen real estate

**Describe the solution you'd like**
add hide-dropdown-icon directive
```
<q-dropdown-btn hide-dropdown-icon>
```

**Describe alternatives you've considered**
hide-icon
show-icon
show-dropdown
hide-dropdown

**Additional context**
![qbtndropdown](https://user-images.githubusercontent.com/87644834/136407238-f507810d-104a-4479-aedb-b7a2ab4b4e24.png)

**Comment by pdanpdan** [comment]
why don't you replace the arrow with your 3 dots icon
https://quasar.dev/vue-components/button-dropdown#example--custom-dropdown-icon

**Comment by rstoenescu** [comment]
QDropdownBtn without the dropdown icon is perfectly equivalent to a QBtn with a QMenu inside of it. So use QBtn + QMenu.

**Comment by rhues** [comment]
@rstoenescu, Maybe that's true, but the the docs don't talk about a solution for this common use case. It's a good thing Copilot knows the solution, but it should be in the docs.
