### ISSUE TITLE
Dialog component no longer able to close and also buttons miss-functioning since upgrading to 0.14.6

### ISSUE THREAD

**Issue by sysmesh** [quasarframework/quasar#1092]
**Software version:**
Quasar: 0.14.6
OS: Windows 10
Node: 8.6.0
NPM: 5.4.2
Browsers: Chrome & FireFox
iOS:
Android: Material theme

Issue with Dialog box since upgrading to 0.14.6
The following code stopped working since upgrading (worked fine on previous versions).
When trying to click button 1 the console logs the click but fails to close the dialog.
When clicking button 2 nothing happens  -  seems the handler isn't called.
Also - clicking outside the dialog or using the ESC key no longer closes the Dialog.

Here's my test.vue component:
```vue
 <template>
 <div>
    Test area
</div>
</template>

<script>
    import {
       QBtn,
       QIcon,
       QModal,
       Dialog
   } from 'quasar-framework'

    export default {
       name: 'Test',
       components: {
        QBtn,
        QIcon,
        QModal
       },
       data()  {
           return {}
       },
       computed: {
       },
       methods: {
           testDialog() {
                var that = this;
                let tmpDialog = Dialog.create({
                    title: 'Test Dialog',
                    noBackdropDismiss: false,
                    buttons: [
                    {
                        label: 'Button 1',
                        preventClose: true,
                        handler(data, closeThis) {
                            console.log("Button 1 clicked");
                            closeThis();
                         }
                    },
                    {
                        label: 'Button 2',
                        handler(data) {
                            console.log("Button 2 clicked");
                        }
                    }
                    ]
               });
           },
       },
       mounted () {
           this.testDialog();
       },
       nextTick() {},
       updated () {}
   }
</script>
```

**Comment by rstoenescu** [comment]
For the life of me, I cannot reproduce, even with your vue component... Any gif or something?

**Comment by rstoenescu** [comment]
First, are you sure you are using a v0.14 template? What was the version from which you upgraded?

**Comment by rstoenescu** [comment]
![dialog_test](https://user-images.githubusercontent.com/4665641/32381426-53cefdb6-c0bb-11e7-9dc7-1b78c235fc8f.gif)

**Comment by sysmesh** [comment]
Thanks for trying to help. I also find it puzzling as on my end it ignores the buttons.
It worked just fine until I upgraded so its really strange.

I upgraded from 0.14.2 to 0.14.6

My current composer is:
"dependencies": {
        "babel-runtime": "^6.25.0",
        "fastclick": "^1.0.6",
        "gulp": "^3.9.1",
        "laravel-elixir": "^6.0.0-16",
        "laravel-elixir-vue-2": "^0.3.0",
        "material-design-icons": "^3.0.1",
        "moment": "^2.19.1",
        "popper.js": "^1.12.6",
        "quasar-extras": "0.0.8",
        "quasar-framework": "^0.14.6",
        "roboto-fontface": "^0.7.0",
        "vue": "~2.5.2",
        "vue-i18n": "^7.3.2",
        "vue-resource": "^1.3.4",
        "vue-router": "^3.0.1",
        "vue-visible": "^1.0.2",
        "vuelidate": "^0.6.1"
    },
    "devDependencies": {
        "axios": "^0.16.2",
        "babel-loader": "^7.1.2",
        "babel-preset-es2015": "^6.24.1",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1.1",
        "css-loader": "^0.28.0",
        "laravel-mix": "^1.5.1",
        "lodash": "^4.17.4",
        "stylus": "^0.54.5",
        "stylus-loader": "^3.0.1",
        "vue-style-loader": "^3.0.3",
        "vue-template-compiler": "~2.5.2",
        "webpack": "^3.8.1"
    }

Previous version was: 
"dependencies": {
        "babel-runtime": "^6.25.0",
        "fastclick": "^1.0.6",
        "gulp": "^3.9.1",
        "laravel-elixir": "^6.0.0-15",
        "laravel-elixir-vue-2": "^0.3.0",
        "material-design-icons": "^3.0.1",
        "moment": "^2.15.0",
        "popper.js": "^1.12.5",
        "quasar-extras": "0.X",
        "quasar-framework": "^0.14.2",
        "roboto-fontface": "^0.7.0",
        "vue": "~2.3.4",
        "vue-i18n": "^7.2.0",
        "vue-resource": "^1.3.4",
        "vue-router": "^2.7.0",
        "vue-visible": "^1.0.2",
        "vuelidate": "^0.5.0"
    },
    "devDependencies": {
        "axios": "^0.16.2",
        "babel-loader": "^7.1.2",
        "babel-preset-es2015": "^6.24.1",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.0.1",
        "css-loader": "^0.28.0",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4",
        "stylus": "^0.54.5",
        "stylus-loader": "^3.0.1",
        "vue-style-loader": "^3.0.1",
        "vue-template-compiler": "~2.3.4",
        "webpack": "^3.5.6"
    }

Any hint/advice would be great!

**Comment by sysmesh** [comment]
![quasar_issue](https://user-images.githubusercontent.com/180796/32403353-23781078-c140-11e7-9148-ac8f9a07a970.gif)

**Comment by sysmesh** [comment]
Short update:  I now discovered that this issue happens only on Chrome. On FF it seems to work fine.

**Comment by sysmesh** [comment]
Update: I've not discovered that when in Incognito mode in the browser (FF) the test file works fine. 
I believe the issue must be somehow cache/browser cache related.

Thanks so much for trying to help. I'm a true fan of Vue and Quasar so I'm delighted to be using it for our company's product.

**Comment by rstoenescu** [comment]
I've tested in all browsers and it seems to work. So let's do some more tests to figure out what is happening for you:

1. Downgrade to your previous Quasar version. Make sure that version is installed, do not just change package.json then run "npm run dev". Also downgrade Vue to 2.3.x.

2. Second test (might be worth doing with both Quasar versions). Make a new route pointing to this vue file:

```vue
<template>
 <div>Test area</div>
</template>

<script>
import {
  Dialog
} from 'quasar'

export default {
  name: 'Test',
  beforeCreate () {
    console.log(`Quasar v${this.$q.version}`)
    console.log('has popstate:', this.$q.platform.has.popstate)
    window.addEventListener('popstate', () => {
      console.log('popstate occurred')
    })
  },
  created () {
    console.log('route', this.$route)
  },
  methods: {
    testDialog () {
      Dialog.create({
        title: 'Test Dialog 1',
        buttons: [
          {
            label: 'Button 1',
            preventClose: true,
            handler (data, closeThis) {
              console.log('Button 1 clicked')
              closeThis()
            }
          },
          {
            label: 'Button 2',
            handler () {
              console.log('Button 2 clicked')
            }
          }
        ]
      })
    }
  },
  mounted () {
    this.testDialog()
  }
}
</script>
```

3. Third test, change `mounted()` a little.
3.a. Try `mounted () { this.$nextTick(() => this.testDialog()) }`
3.b Try `mounted () { setTimeout(() => this.testDialog(), 500) }`

Let me know how each test goes. Thanks.

**Comment by sysmesh** [comment]
Thanks!
did you see my previous comment? I do suspect it's some cache related issue as Incognito mode on the browser causes the code to work properly.

I now made a clear cache test on my browser and all works fine. I suspect something remains cached which causes the issue hence it's not a Quasar code bug. 

Thanks so much for helping and sorry for the time wasted on this. 
I do suggest updating the bug report form to ask people to clear their browser cache and try to reproduce it in Incognito mode before reporting. This might save some other reports of similar causes.

**Comment by sysmesh** [comment]
So Strange. Chrome still refuses to run it properly unless I use incognito mode. 
Here's what I get when running your test script:
![quasar_issue2](https://user-images.githubusercontent.com/180796/32404606-6b8335f8-c15b-11e7-934c-2c6c22bea0ee.gif)

**Comment by rstoenescu** [comment]
1. Did you try downgrading and testing again?
2. Cache shouldn't affect this at all...
3. I'm gonna make a special debugging build for you to see what's going on. I see that the popstate event is called (which is good, this should close the modal), but it doesn't do anything. Wanna see why this is so.

**Comment by sysmesh** [comment]
Thanks!
1. I did not try to downgrade. My Vue+Quasar setup runs inside a Laravel 5.5 project and I fear messing up something else in it. 
Note that I did run a cache:clear on Laravel each time to ensure it's not some weird laravel thing.
2. So far it works just fine on: Firefox, Chrome incognito. Only fails on Chrome regular mode.
3. Wow man, thanks!!

**Comment by nueko** [comment]
as it laravel based, you maybe want to use [versioning asset](https://laravel.com/docs/5.5/mix#versioning-and-cache-busting)  method

**Comment by sysmesh** [comment]
Thanks! Good advice. 
I added it.

**Comment by kranzky** [comment]
I've hit the same issue; hacking away at a project and added a dialog only to find that it won't close (button handlers don't get called etc). Tried in incognito (after reading this) and it worked fine. Then tried opening a new tab in the original (non-incognito) browser window and that also worked. The original tab continued not to work. Weird.

**Comment by rstoenescu** [comment]
This behavior will go away 100% on v0.15 (to be released really soon).

**Comment by Trellian** [comment]
I've hit the same problem with a QModal. Closes fine when in private-browse mode, but not able to close in any way after hitting the any button on the Modal while in normal-browse mode. Bring on 0.15 :)

It's causing a lot of grief, because the Vue and Apollo developer tools only exist for Chrome at this point.

**Comment by rstoenescu** [comment]
Hi, pushing very hard to bring that v0.15 ASAP. I am excited about the many many improvements and I also want to see them released so you can all enjoy them. Also, a good news is that at current time it seems like v0.15 will be the last release before v1.0.

**Comment by Ivinnic** [comment]
Hello, I'm enjoing to use your framework! Thanks for your hard work!
I have the same problem. It's depens on popstate.  We can't update to the latest version now
Do you have any advice, how can I make hot-fix?

**Comment by Ivinnic** [comment]
I made screencast https://www.youtube.com/watch?v=w9vVqcQi2hw

**Comment by rstoenescu** [comment]
Until v0.15 is available, for v0.14 a workaround would be to disable this back-button feature completely by adding this in main.js:

```js
import { Platform } from 'quasar'
Platform.has.popstate = false
```

Sorry for the delay. I'm sure you all want v0.15 to be perfect when released.

**Comment by Ivinnic** [comment]
Thank you very much for your respond. 
I explored that has.popstate using in QCarousel QModal And SideMixin (v0.14.4)
I really liked the idea of using popstate for convenience on mobile devices. 
Bravo!

**Comment by rstoenescu** [comment]
Although this started out as a top feature to set the framework apart from all the rest, it caused more grief than what it brought good to a website/app. The fault is in the History API design and we can't do anything about it unfortunately.

As a result, this feature has been dropped from v0.15. This greatly simplifies many areas of the framework:
* You will no longer need QSideLink in drawers. You can directly tell the vue router to go to another route and it will do so without the need to get a Vue reference on the drawer to call its close/hide method. Same applies to QModals and all the components that were using popstate.
* QModals, QPopovers etc now work flawlessly with HMR too, and they can fully support a v-model instead of using references.
And this is just the tip of the iceberg. The overall complexity of app-space code for a website/app with Quasar will drop significantly.

**Comment by Ivinnic** [comment]
I'm glad to hear that there will be many improvements.
I wish you success!

**Comment by kotAPI** [comment]
Hey Razvan, 
          I've been facing the same problem. The Dialog was working well once, I don't know if I refreshed or navigated back to the page, the buttons stopped working. I read through the thread and found that this will be fixed in the next version... 

Will using `.has.popstate = false` for dialog work too?

**Comment by kotAPI** [comment]
UPDATE : 

I'm temporarily using `Platform.has.popstate = false` in my mount component for now, it works. Thanks for the suggestion!
