### ISSUE TITLE
Wrong scrolling behavior when navigating with Plugin Loading (SSR+Prefetch)

### ISSUE THREAD

**Issue by laferte-tech** [quasarframework/quasar#10929]
Hello,

i have a bug when we are in SSR Mode and using Prefetch, Axios and plugin Loading.
With this configuration, when navigating to the page, the scroll behavior is wrong and the position is keep to the from page (is not going to top of the new page).
It seems to be an old bug because it's described here:

[https://forum.quasar-framework.org/topic/5934/scroll-behaviour-when-using-prefetch-ssr](https://forum.quasar-framework.org/topic/5934/scroll-behaviour-when-using-prefetch-ssr)

in Page.vue i have this:

`  async preFetch({store, currentRoute}) {

    let currentId = Number(currentRoute.params.id);

    await store.dispatch('bar/foo', {id: currentId})
  },`

In boot file Axios.js i have this:

```
 instance.interceptors.request.use(config => {
     Loading.show({
       delay: 700 // ms
     })
}
```

When and only when Loading.show is triggered, the scroll behavior is wrong.  When commenting the Loading.show, no problem anymore (when navigating to the page, scroll is going to top).

Thanks a lot for your work and your help

**Comment by rstoenescu** [comment]
@GrandOurs35 Please create a codepen or codesandbox (https://codesandbox.quasar.dev) to highlight your problem. The Loading plugin does not influences scroll in any way so it must be your usage?

**Comment by laferte-tech** [comment]
Hello, thanks for your answer and sorry for not have made a codepen :/ 
I am currently switching to V2 so i think i can close this for the moment. If i still have the trouble with V2 i will make a codepen.
