### ISSUE TITLE
Add support to qlayout for fixed page

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10923]
**Is your feature request related to a problem? Please describe.**
I have read dozens of posts concerning quasar layout and scrolling. I have responded to quite a few based on my understanding and experimentation. I have spent countless hours reading quasar code and debugging layout in the browser. I think I understand how it works and adding just a little more info to the docs would help. For example: when a drawer is fixed, if the content is to tall for the window it automatically gets a scrollbar. If it is not fixed then the browser window gets a scrollbar.

When the drawers aren't fixed the browser scrollbar scrolls the drawers and the page. If the drawers are fixed then the browser scrollbar scrolls the page, even though it might be on the other side of the drawer. It will also extend up beside the header if there is one. 

All that was background to say that adding the ability to "fix" the page/pagecontainer would cause the page to have its own scrollbar which is preferable in many instances. 

**Describe the solution you'd like**
My proposal is that using a capital P in the page position of the layout string "hHh lPr lFf" would fix the page and also provide the magic and automatic scrolling of the page content if necessary. This would work just like using a capital L in the layout string to fix the left drawer prevents it from scrolling with the browser window and instead magically provides a scrollbar if necessary.

**Describe alternatives you've considered**
I have implemented a fixed page with a page scrollbar when necessary by
1. adding ```class="fixed fit scroll"``` to qpagecontainer in mainlayout.  
2. I also had to add ```class="fit scroll"``` to the qpage, but I am not sure why. 

Adding fixed to the page container gets rid of the browser scrollbar when drawers are fixed, which was my initial goal.
My "workaround" requires me to modify every page for it to work. I don't like that but I am new to quasar and don't fully understand all the details of the qlayout implementation. I am also not very experienced with CSS.

**Additional context**

**Comment by pdanpdan** [comment]
You can do it like this:
https://codepen.io/pdanpdan/pen/bGrRXRR?editors=1010

But you would lose `reveal` and `QPageScroller`

**Comment by julie777** [comment]
@pdanpdan I think your way is much better. Thank you!

I've boiled it down to the following. (for others reading this)

### Limit the page height to the area below the title bar.

Add the style-fn to the q-page.
```      <q-page class="column" style="padding-top: 50px" :style-fn="getPageStyle">```
and add the getPageStyle function to the return of the setup function.
```
setup () {
    return {
        getPageStyle (offset, height) {
        return {
          height: `${ height - offset }px`
        }
      }
    }
  }
```
This will set the page height to account for the title bar and automatically adjust if it changes.

### Make the page contents scrollable
Wrap the contents of the q-page with a scroll area which allows the page to scroll inside the area allocated to the page.
```
 <q-scroll-area class="col">
  page contents
</q-scroll-area>
```

My original use case is handle by the above 2 items. Easy peasy!

### Adding a page title bar

Adding the title bar for a page is easy.  Just add a sticky after the scroll area in the page.
```
         <q-page-sticky position="top" expand class="bg-accent text-white">
          <q-toolbar >
            <q-btn flat round dense icon="map"></q-btn>
            <q-toolbar-title>Title</q-toolbar-title>
          </q-toolbar>
        </q-page-sticky>
```
This will stay at the top of the page and not scroll when the page contents scrolls.

### Still an Issue
However, there is one issue, and that it that the page title (sticky) height is hard coded into the q-page ```style="padding-top: 50px"``` which means if the title changes height and gets taller then the page content might hide under it.

So the question remaining is given a page "layout" such as
```
<q-page class="column" style="padding-top: 50px" :style-fn="getPageStyle">
  <q-scroll-area class="col">
  </q-scroll-area>
  <q-page-sticky position="top" expand class="bg-accent text-white">
  </q-page-sticky>
</q-page>
```
How can I have the page style top padding be automatically calculated to account for the actual size of the sticky?
Maybe @pdanpdan can answer this, or I will if I can find a solution.

My plan is to create a ScrollablePage component to encapsulate the above and use that instead of q-page for my application.

**Comment by pdanpdan** [comment]
My opinion/way of implementing something like this:
- Use QHeader/QFooter for things that should go above/below the page (you can use multiple rows)
- Use the multiple slots of vue-router to have different header/footer for each route/page (for the same route you can define slots for header/footer/drawer, whatever) - place the router-view for each of the slots in the right place in the layout
- Try to avoid QPageSticky expand because you will need to account for the size

**Comment by julie777** [comment]
Using QHeader won't work for me as I have a full width header for my qlayout. Drawers are under the header. Some of my pages need a page header that is the width of the page, and inside the drawers. An example:

![image](https://user-images.githubusercontent.com/5090005/139543297-751dfb66-37ee-4b2f-abfb-2fc0f3d0b03a.png)

To clearly define my goals.
- page area has its own scrollbar if necessary and doesn't use browser window scrollbar. This is how drawers work by default.
- I want my sidebars and page scrollbars to look the same
- I want to be able to optionally add a page title bar that is sticky and doesn't scroll when the page content scrolls.
- I want the page content scrollbar to only be the height of the scrollable area
- I want the page content scrollbar to be always visible if there is scrollable content, just like the drawers

I now have a solution that I am starting to use. It still needs more testing for various reactive conditions. 
I didn't apply any extra CSS to the ScrollablePage. All style should be done to the components in the header and body slots.
For anyone that wants it, here it is. 

```vue
// ScrollablePage
<template>
  <q-page class="column" :style-fn="getPageStyle">
    <div class="col fit scroll" :style="topMargin">
      <slot>Empty Page</slot>
    </div>
    <q-page-sticky ref="pageHeader" position="top" expand>
      <slot name="header" />
    </q-page-sticky>
  </q-page>
</template>

<script setup>
// I chose to use a div for the scrollable area because I wanted the scrollbar
// to look and behave just like the one that shows when a drawer needs 
// scrolling
//
// I had originally q-scroll-area for the scrollable area, but I didn't find
// an easy way to get the kind of scroll bars that I wanted. 
//     <q-scroll-area class="col" visible :style="topMargin">
// Using visible keeps the scroll bar visible even when the cursor is not in
// the scrollable area, otherwise it hides.
//
// Applying CSS classes to the ScrollablePage will in turn apply them to the
// page which will likely cause layout problems. Instead apply CSS to the
// components inserted into the slots

import { computed, ref } from 'vue'

// This makes space for the App Header
function getPageStyle(offset, height) {
  return { height: `${height - offset}px` }
}

// This function makes space for the optional Page Header
// By using margin instead of padding the scrollbar doesn't go under the page header
const pageHeader = ref()
const topMargin = computed(() => {
  return {
    marginTop: (pageHeader.value ? pageHeader.value.$el.offsetHeight : 0)
      + 'px !important'
  }
})
</script>
```

**Comment by pdanpdan** [comment]
I modified the example here: https://codepen.io/pdanpdan/pen/bGrRXRR?editors=1000
For the scroll area bar visible or not just play with its properties

**Comment by julie777** [comment]
It is interesting. Your solution was to add code to the drawer to make it use ScrollableArea to match the page, where I tried to match the default scrollbars for the drawer.

I can't see how you are controlling the height off the scrolling area of the page. It looks like that because you are using toolbars for the page header and footer it just works magically.

I did try to resize the app window area in codepen and was surprised that the app footer stayed and the bottom of the screen and everything else in the app moved up and just left a big gap. I don't know if this is a codepen thing because i am new to codepen.

![image](https://user-images.githubusercontent.com/5090005/139554183-322f6c7e-2c73-497a-b4c2-6b80ebf1ca13.png)

**Comment by pdanpdan** [comment]
The page is `.column.no-wrap` so by default the children are placed vertically, full-width and their native height.
Then you have some things on top and bottom (toolbars in this case) that keep their native height
In the middle you have something (scroll area) that has a `.col` class and this tells it should fill all available vertical space and no more than that.
