### ISSUE TITLE
Q-field docs need update. Change value to modelValue.

### ISSUE THREAD

**Issue by jonathanpmartins** [quasarframework/quasar#10939]
I could not make my q-field to work correctly until I tried a different approach.

The docs indicate the user to use `value`, but I think it was updated to `modelValue`.

#### Docs:
![Screenshot from 2021-10-09 19-02-33](https://user-images.githubusercontent.com/6137992/136674796-98a3e84b-63e7-4fe8-a229-15d760cdac3b.png)

#### My code only works if I use `modelValue`:
![Screenshot from 2021-10-09 19-05-55](https://user-images.githubusercontent.com/6137992/136674809-19660c41-0422-45f1-8ecc-043186226999.png)

#### I'm working with:
![Screenshot from 2021-10-09 19-03-13](https://user-images.githubusercontent.com/6137992/136674846-eff4185f-51e8-491c-9aa0-5514cb6ee959.png)

If you need more information, please write back!
Cheers!

**Comment by jonathanpmartins** [comment]
Another think that I notice was that I could not make it reactive with the `@change` event. Only with `@input`

**Comment by pdanpdan** [comment]
You are reading the docs for v1
Sorry, my bad - you are talking about the slot

**Comment by rstoenescu** [comment]
Fixed the API definition. Thanks for opening this ticket.
Fix will be available in Quasar v2.1.2

**Comment by hawkeye64** [comment]
The terminology used in the commit is backwards...
