### ISSUE TITLE
QFabAction: Add a prop that enables you to set a size when using an image as icon 

### ISSUE THREAD

**Issue by lucasdavidferrero** [quasarframework/quasar#10957]
**Is your feature request related to a problem? Please describe.**
There are times when I use images (specially colored SVG illustrations) for QFabAction. It'd be nice if we could control the width and height of that icon's image, since It looks tiny when you're in desktop.

**Describe the solution you'd like**
When using the prop `icon` with 'img:' prefix, allow us to set the size of that image. Maybe we could use the standard sizes only (sm, md, etc).

**Describe alternatives you've considered**
I didn't find an alternative yet. If you have one, please share it :)

**Additional context**
Here you can see how tiny the icon looks on large screens:
![image](https://user-images.githubusercontent.com/15804058/136866522-ae1570db-3e01-44fa-804a-ee32582229d7.png)

This issue is **different** from this one: #3739

**Comment by metalsadman** [comment]
@lucasdavidferrero you can make use of the `default` slot and use QAvatar or QIcon as a child and set its `size` prop in there.
https://codepen.io/metalsadman/pen/XWaJBpY?editors=1010

**Comment by lucasdavidferrero** [comment]
@metalsadman thanks bro. Your solution solves this issue. I'll close it
