### ISSUE TITLE
Component: Date - Range selection

### ISSUE THREAD

**Issue by mrdreka** [quasarframework/quasar#10952]
**bug**
The bug appears when it comes to "Clicking on an already selected day will deselect it." which breaks when clicking inside of the range, when there is also input forms that can be used to edit it. 

** Reproduce**

1. Go to https://codepen.io/mrdreka/pen/JjyojJq?editors=1011
2. Click on on an area within the range
3. create an unhandled error that breaks the function of deselect

**Expected behavior**
Expected to work like normal range selection as shown in documentation, but instead it breaks when it is also possible to change it with input forms for "from" and "to".

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2

Overall it works with the exception of deselecting using the date-picker component

**Comment by rstoenescu** [comment]
That's what `no-unset` Boolean prop is for.

**Comment by mrdreka** [comment]
That is more of a workaround, the actual issue is that instead of having deselect set the model value to empty like { from: '', to: '' } that would allow deselect to still work, the deselect range sets the value to null.

**Comment by rstoenescu** [comment]
This will not change as it is this way for consistency with all the other features. Furthermore, changing this will bring a breaking change and it's definitely not something that we want.

However, you can wrap the model with a computed property to translate it to whatever value you need.
