### ISSUE TITLE
Double clicking `type=submit` button in `q-stepper` throws an error

### ISSUE THREAD

**Issue by sirkrypt0** [quasarframework/quasar#10955]
**Describe the bug**

Double clicking a `type=submit` button in a `q-form` which is part of a `q-stepper` throws an error.

**Codepen/jsFiddle/Codesandbox (required)**

<https://jsfiddle.net/73e2vfzp/2/>

**To Reproduce**
1. Run the jsfiddle
1. Double click the 'Continue button' button.
1. The stepper continues as expected. No error is thrown.
1. Rerun the jsfiddle or use the 'back' button to get back to the initial step.
1. Double click the 'Continue Form' button.
1. See error in console.

**Expected behavior**

No error occurs.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: `2.1.0`
@quasar/app Version: `3.1.2`

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Manjaro Linux 21.1.4
Node: `v16.10.0`
NPM: `7.24.1`
Yarn: `1.22.11`
Browsers: Firefox

**Additional context**

**Comment by pdanpdan** [comment]
Sorry, cannot reproduce it in Chrome or Firefox

**Comment by rstoenescu** [comment]
Cannot reproduce in Safari either.

**Comment by lmm-git** [comment]
I just verified it. It might not be obvious that there is a console error, but when double clicking quite fast on the button it throws an error.

![image](https://user-images.githubusercontent.com/2118953/136854264-4b89b39c-5786-4f0c-947f-52fe4e08ee9a.png)


Firefox 93, Ubuntu Linux 20.04

**Comment by pdanpdan** [comment]
I managed to reproduce it to find the source: rootRef.value is null at https://github.com/quasarframework/quasar/blob/9098399ef1c56c7071c2c08a55e40573b2db064b/ui/src/components/btn/QBtn.js#L124

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.2

**Comment by sirkrypt0** [comment]
> Fix will be available in Quasar v2.1.2

Great to hear and thanks for your work on that!
