### ISSUE TITLE
Options for navigation and footer reveals

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1096]
I chose Quasar for building a cross-platform app like this one:
https://play.google.com/store/apps/details?id=trendyol.com&hl=en
However this app has a header, navigation and footer reveal at the same time or sometimes just one or two of them, I reached to an advanced stage with my app and I really need and wish to see this feature supported in Quasar soon.

**Comment by rstoenescu** [comment]
Already in future v0.15 ;)

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu Awesome news! thank you.
