### ISSUE TITLE
use-form-child.js logs error when requiresQForm !== true 

### ISSUE THREAD

**Issue by piotrszyma** [quasarframework/quasar#10963]
When I use `useFormChild({..., requiresQForm: false})` composable in a component that is not wrapped in `QForm`, quasar prints a warning in a console: `Parent QForm not found on useFormChild()!`

Bug was introduced due to rename of `canFail` to `requiresQForm` in [this commit](https://github.com/quasarframework/quasar//commit/d4cd48b26cbb9b95fbc583bcda7bb661522199ba)

When the parameter was "canFail", then `canFail === false` should log, when it was renamed to `requiresQForm` then it should log when `requiresQForm === true` so I believe [line 32 in use-form-child.js](https://github.com/quasarframework/quasar/blob/dev/ui/src/composables/use-form-child.js#L32) should be:

```
  else if (requiresQForm === true) {
```
not 

```
  else if (requiresQForm !== true) {
```

Please double check if my issue is legitimate - I can prepare a pull request fixing that.

**Comment by rstoenescu** [comment]
Hi @piotrszyma ,

Took a quick look. Indeed, a fix is needed.
1. use-validate.js > `useFormChild({ validate, requiresQForm: false })` (was `requiresQForm: true` -- which is wrong)
2. use-form-child.js > `else if (requiresQForm === true) {` (was `!==` -- which is wrong)

Would you be so kind to create a PR for this?

**Comment by rstoenescu** [comment]
Thanks for PRing!
This will go into Quasar v2.1.2.
