### ISSUE TITLE
ExportFile Encoding

### ISSUE THREAD

**Issue by alemila01** [quasarframework/quasar#10969]
I'm using this function but i see problem opening on excel exported CSV with italian accent.
I see there is econdoding parameter but viewing on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/TextEncoder]) that in modern browser this feature is changed a lot so only UTF-8 work :(
Maybe another way is changing encoding with some js lib?

Update:
putting: {
  byteOrderMark: '\uFEFF',
  mimeType: 'text/csv;charset=utf-8;'
}
solved my problem....

I think stating in DOC this new browser behavior is enough
Maybe another change is removing encoding or change how i work in export-file.js

**Comment by pdanpdan** [comment]
Hello. This has nothing to do with quasar.

**Comment by alemila01** [comment]
Sorry you are right, i opened this issue with wrong assumption and lacked more undertanding of the encoding funcionality... 
BUT the doc is wrong and the encoding is funcionality is totally different.... so a quick update on that is more than enought
