### ISSUE TITLE
Can you import from the Quasar Module when trying to use UMD mode?

### ISSUE THREAD

**Issue by nikkwong** [quasarframework/quasar#10971]
Is it possible to use quasar like 
```
import {Quasar} from "quasar"
app.use(Quasar)
```

I want to use the UMD version but do not want to rely on a CDN.

When I try this I'm getting `cannot convert undefined or null to object`.

Thank you.

**Comment by rstoenescu** [comment]
The question itself is confusing.

Are you using Quasar in its UMD form? Then in your html file include a tag to point the Quasar UMD. Doesn't matter where you point at as long as the URL is correct. You can use the CDN links or download them from CDN and serve them yourself.

Executing a `import {Quasar} from "quasar"` means you actually have a build system in place (Quasar CLI, webpack, etc etc) which handles the imports. But this has nothing to do with Quasar in the UMD form.

**Comment by rstoenescu** [comment]
As long as you have those tags included in your project's html file, then access `Quasar` directly (or to be more explicit: `window.Quasar` -- same thing).

**Comment by nikkwong** [comment]
Sorry, I meant ESM. I'm using a webpack esque build, and would like to potentially take advantage of treeshaking. The import style I used above does not work with the error referenced above. Am I doing something wrong?

**Comment by nikkwong** [comment]
@pdanpdan or @rstoenescu  would love some assistance thanks.

**Comment by rstoenescu** [comment]
If you're onto webpack-esque things, then by all means, **please do use Quasar CLI (recommended)** or Vue CLI+Quasar Vue CLI Plugin. However you have configured webpack, you'll be able to extend both Quasar CLI's or Vue CLI's config.

If that's not an approach that you'd like to follow, then you can take a look at (easier to show you the quasar vue cli plugin than the equivalent Quasar CLI code):
1. All files from https://github.com/quasarframework/vue-cli-plugin-quasar/tree/dev/lib except for the extendPluginOptions.js
2. And this is how to use those files: https://github.com/quasarframework/vue-cli-plugin-quasar/blob/dev/index.js

Please beware that anything may change in the future and we currently have no plans to release a standalone webpack plugin for Quasar.
