### ISSUE TITLE
[FEATURE REQUEST] Make q-input center-able

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#1097]
I would like to be able to use an `align` prop on q-input, q-select and other form items to align text. Currently simply adding the `text-center` class does not work.

The end result may look like so

```
<q-input align="center" />
```

**Comment by rstoenescu** [comment]
So use it, cause it's already there :)

**Comment by BenoitRanque** [comment]
Darn you! Missed it in the docs!

**Comment by BenoitRanque** [comment]
Just to be nasty, let me point out this does not work on the float-label.... and text-center leaves it off balance

**Comment by BenoitRanque** [comment]
Work fine on placeholder, going with that. As always thanks for lighting fast response time!
