### ISSUE TITLE
Problem creating app after uploading to google play

### ISSUE THREAD

**Issue by antbelogurov** [quasarframework/quasar#10975]
Hi.
I was building my application using cordova.
Everything works on my computer. Debugg version also worked on all phones, but release version doesn't work. Throws the following error (see screenshot)
When opening an application from google play, the application tries to connect to the ip address of my computer, although I have not specified it anywhere in the application.
How to solve this problem?
[https://i.stack.imgur.com/QUQU5.jpg](url)

**Comment by MilosPaunovic** [comment]
Do you have any enviroment variable or base URL setting for axios set up to go to your local IP?

**Comment by antbelogurov** [comment]
> Do you have any enviroment variable or base URL setting for axios set up to go to your local IP?

I have the address of the server I am accessing, but it has nothing to do with the ip of my computer

**Comment by MilosPaunovic** [comment]
What happens when you build signed version of the application and try to install it on your phone?

**Comment by antbelogurov** [comment]
> What happens when you build signed version of the application and try to install it on your phone?

the same happens if I install the release apk

**Comment by MilosPaunovic** [comment]
> I have the address of the server I am accessing, but it has nothing to do with the ip of my computer

Do you use different addresses in development and production applications? It just seems to me that, somehow, you've left some baseURL to go to your local backend...

**Comment by pdanpdan** [comment]
Please move this to discussions, it has nothing to do with the framework. Thank you.

**Comment by antbelogurov** [comment]
> > I have the address of the server I am accessing, but it has nothing to do with the ip of my computer
> 
> Do you use different addresses in development and production applications? It just seems to me that, somehow, you've left some baseURL to go to your local backend...
https://ibb.co/HpDbnTT

this is the only place where baseurl appears.


If you have any understanding because I find it difficult with this, if it's not difficult for you to write in telegramm @antbelogurov I will be very grateful
