### ISSUE TITLE
QSelect use fill-input prop, virtual-scroll event will be triggered consecutively.

### ISSUE THREAD

**Issue by zhiyuanzmj** [quasarframework/quasar#10972]
**Describe the bug**
QSelect use fill-input prop, virtual-scroll event will be triggered consecutively.

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/zhiyuanzmj/pen/dyzoJgN](https://codepen.io/zhiyuanzmj/pen/dyzoJgN)

**To Reproduce**
1. Click on 'QSelect'
2. foo ref begin to increase

**Platform (please complete the following information):**
Quasar Version: v2.1.1

Quasar mode:
  - [x ] SPA

**Comment by pdanpdan** [comment]
Are you joking? You are calling `refresh` method on the QSelect after each virtual-scroll event. Of course after refresh it announces the new scroll position.
