### ISSUE TITLE
`quasar ext add @quasar/testing` doesn't work at all out-of-box

### ISSUE THREAD

**Issue by khteh** [quasarframework/quasar#10980]
**Describe the bug**
I `quasar ext add @quasar/testing` and only selected `Jest Unit Testing` from the list. After the "successful" installation, npm shows `28 high severity vulnerabilities` and `npm audit fix --force` doesn't fix any of them at all and all have to do with `jest`. When I ran `quasar test --unit jest`, I see the following errors:
```
$ quasar test --unit jest
 App • Running "@quasar/testing" Quasar App Extension...
 App • Running "@quasar/testing" > "test" command


              
 RUN:  Running unit tests with jest

            
$ jest --ci
● Validation Error:

  Module vue-jest in the transform option was not found.
         <rootDir> is: /usr/src/khteh

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```
What do I miss from following your documentation!?!
https://quasar.dev/quasar-cli/testing-and-auditing#documentation
https://github.com/quasarframework/quasar-testing#installation
https://github.com/quasarframework/quasar-testing/blob/dev/packages/testing/README.md

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**
Expect to be able to run `quasar test` command without error after "successful" installation of the testing App Extension!

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 3.1.3
@quasar/app Version:

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 21.04
Node: V16.11.1
NPM: 8.0.0
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by IlCallo** [comment]
@khteh you need to use `quasar ext add @quasar/testing@beta` as new Qv2-compliant testing AEs aren't yet released as stable

But you're right, we need to update those pages in the docs to account for this, thanks for bringing it up

**Comment by khteh** [comment]
When will it be release as stable?

**Comment by IlCallo** [comment]
Now :)
Jest and Cypress will take some time yet, Jest in particular as the upstream packages are still in alpha phase too

**Comment by khteh** [comment]
What do you mean now and why is this closed? I `quasar ext add @quasar/testing` and still see the same error:
```
$ quasar test --unit jest
 App • Running "@quasar/testing" Quasar App Extension...
 App • Running "@quasar/testing" > "test" command


              
 RUN:  Running unit tests with jest

            
$ jest --ci
● Validation Error:

  Module vue-jest in the transform option was not found.
         <rootDir> is: /usr/src/khteh

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```
/open

**Comment by MilosPaunovic** [comment]
`quasar ext add @quasar/testing@beta`

**Comment by IlCallo** [comment]
@khteh have you reinstalled the jest AE when reinstalling the testing harnesses manager?

**Comment by khteh** [comment]
Yes I did

**Comment by IlCallo** [comment]
I just tested it again following the steps you described and it works correctly. Please provide a repro if the problem persist

**Comment by khteh** [comment]
@IlCallo I have only tried with `quasar ext add @quasar/testing`. Not `@beta`. I asked when would it be released as stable and you said "now". So I tried again and it still fails. The repo is https://github.com/khteh/quasar

**Comment by IlCallo** [comment]
Yes, I tried without the `@beta` too, as testing manager has been released as stable when I said `now`
In the repo you posted, there's no testing harness installed, nor the testing harnesses manager

A repro is a minimal repository I can run without any modifications to see the problem in action, what you sent me isn't a repro

**Comment by khteh** [comment]
I tried again today and it works. What happaned?

Howeever, there is symbol missing error from your `'@quasar/quasar-app-extension-testing-unit-jest'`:
```
$ quasar test --unit jest
 App • Running "@quasar/testing" Quasar App Extension...
 App • Running "@quasar/testing" > "test" command


              
 RUN:  Running unit tests with jest

            
$ jest --ci
 PASS  test/jest/__tests__/MyButton.spec.js
 FAIL  test/pages/Fibonacci.test.js
  ● Test suite failed to run

    TypeError: (0 , _quasarAppExtensionTestingUnitJest.mountFactory) is not a function

      2 | import { QInput } from 'quasar'; // <= cherry pick only the components you actually use
      3 | import Fibonacci from '../../src/pages/Fibonacci'; // <= note the absence of `.vue` extension, here we are importing the JS/TS part of a Double File Component
    > 4 | const factory = mountFactory(Fibonacci, {
        |                 ^
      5 |   // mount: { type: 'full' } <= uncomment this line to use `mount`; `shallowMount` is used by default as it will stub all **registered** components found into the template
      6 |   quasar: { components: { QInput } },  
      7 |   mount: {

      at Object.<anonymous> (test/pages/Fibonacci.test.js:4:17)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        1.448 s
Ran all test suites.
```
