### ISSUE TITLE
Editor runCmd

### ISSUE THREAD

**Issue by cgzcgb** [quasarframework/quasar#10981]
https://quasar.dev/vue-components/editor#example--using-toolbar-slots

![image](https://user-images.githubusercontent.com/22539880/137287512-56fcf1b0-329f-4b8a-a939-f7c70a31c28e.png)
Editor runCmd is not work!

![image](https://user-images.githubusercontent.com/22539880/137287731-67bcb4e3-11c5-4d19-b18f-66074c57b6d6.png)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.4.
