### ISSUE TITLE
QEditor does not yet implement input sanitization natively

### ISSUE THREAD

**Issue by mattopmaster** [quasarframework/quasar#10986]
Basically what's in the title. The QEditor component does not implement any input sanitization as of now (or I'm not aware of it, in which case I apologize).
This can potentially lead inexperienced or uninformed developers to develop applications that are vulnerable to XSS attacks.
This can only happen if the user generated input is rendered using `v-html`, but the potential for damage is still there.
A possible fix may be to implement a library, such as sanitize-html, or to add a regular expression check that broadly matches the harmful parts of an input and replaces it with a string.

**Comment by pdanpdan** [comment]
This is outside the scope of quasar. Feel free to try to sanitize with anything you want.

**Comment by idc77** [comment]
@pdanpdan you're really an ignorant and angry little man.
If anything this should be added to the documentation as a warning.
A toolkit that claims to be "enterprise" deserves a more aware guard dog than you. You're doing a bad job.
Not only do you close valid issues you also get into fights with users.
I have seen multiple complaints about your behavior.
Get your act together!
