### ISSUE TITLE
q-select hide-bottom-space not working

### ISSUE THREAD

**Issue by NicoP-S** [quasarframework/quasar#10994]
**Describe the bug**
hide-bottom-space does nothing even if the hint has a value of null

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/ag2bp4hq/3/

**To Reproduce**
See jsfiddle

**Expected behavior**
The select should occupy less space if there is no hint.

**Platform (please complete the following information):**
Pkg quasar........ v2.1.0 
 Pkg @quasar/app... v3.1.0

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by pdanpdan** [comment]
Use `undefined` (or `void 0`)
