### ISSUE TITLE
Would like to position banner or dialog child of Popup Proxy to the left of the icon, ~ Google Maps

### ISSUE THREAD

**Issue by brent-williams** [quasarframework/quasar#10997]
I'd like to position the child of  a Popup Proxy to the right of an icon, similar to Google Maps (attached).

Have tried with both banner and dialog children.  Banner always displays below, dialogs I can't position either.  Styling e.g. `position:relative; top:-20px` will move the e.g. interior of the banner but not the banner itself.  

So close to perfect!  Not sure if this is a feature request or if there's some workaround that would allow me to position a banner or dialog child of a proxy to the left of the proxy icon, per attached.  Any suggestions much appreciated.

<img width="610" alt="a" src="https://user-images.githubusercontent.com/1694687/137575305-e4aa90e8-6b29-4712-aabb-b83504f65e95.png">

<img width="555" alt="b" src="https://user-images.githubusercontent.com/1694687/137575307-d4744493-5539-4e3d-93e5-fa9d667f4752.png">

**Comment by pdanpdan** [comment]
Use the same positioning props as in QMenu

**Comment by brent-williams** [comment]
@pdanpdan rock thanks very much
