### ISSUE TITLE
`quasar upgrade` not in sync with `npm outdated`

### ISSUE THREAD

**Issue by khteh** [quasarframework/quasar#10998]
**Describe the bug**
Running `quasar upgrade` shows all packages are up to date:
```
$ quasar upgrade

  Quasar CLI · Gathering information with npm...

  Congrats! All Quasar packages are up to date.
```
However, `npm` disagrees!
```
$ npm outdated
Package                Current  Wanted  Latest  Location                            Depended by
core-js                 3.18.2  3.18.3  3.18.3  node_modules/core-js                project
eslint                  7.32.0  7.32.0   8.0.1  node_modules/eslint                 project
eslint-webpack-plugin    2.5.4   2.5.4   3.0.1  node_modules/eslint-webpack-plugin  project
firebase                 9.1.2   9.1.3   9.1.3  node_modules/firebase               project
```
**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/VgQbdx) or a jsFiddle (https://jsfiddle.net/rstoenescu/rmaodk0f) or a Codesandbox (https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/tree/legacy-v1) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 3.1.3
@quasar/app Version:

Quasar mode:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 21.10
Node: v16.11.1
NPM:8.0.0
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by MilosPaunovic** [comment]
[https://quasar.dev/quasar-cli/commands-list#upgrade](https://quasar.dev/quasar-cli/commands-list#upgrade
)

> Check (and optionally) upgrade Quasar packages from a Quasar project folder.

So, it only checks and updates `Quasar` packages, and `Firebase`, `ESLint` and other ones you're reffering to are not.
