### ISSUE TITLE
Options of q-select always on screen even the source q-select component scrolled to off-screen

### ISSUE THREAD

**Issue by tanshuai** [quasarframework/quasar#11000]
**Describe the bug**

Options of q-select always on screen even the source q-select component scrolled to off-screen.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tanshuai/pen/Yzxwxvy

**To Reproduce**
1. Click 'Standard' show options of q-select
2. Scroll down the screen to the bottom
3. The options "Google, Facebook..." still on the screen, but the q-select 'Standard' has already off-screen

**Expected behavior**
The options of q-select follows q-select 'Standard" scroll to off-screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/3947852/137578807-30d57007-1302-4c4b-96f6-9432b90465b4.png)

**Platform (please complete the following information):**
Quasar Version: v1 & v2
@quasar/app Version: Any

Quasar mode:
  - [x] SPA
  - [x] SSR
  - [x] PWA
  - [x] Electron
  - [x] Cordova
  - [x] Capacitor
  - [x] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Any
Node: Any
NPM: Any
Yarn: Any
Browsers: Any
iOS: Any
Android: Any
Electron: Any

**Additional context**
Bug can be reproduced on Quasar Dev documentation of v1 & v2

- https://v1.quasar.dev/vue-components/select
- https://quasar.dev/vue-components/select

**Comment by rstoenescu** [comment]
Hi,

This is by design. We do want that due to some more advanced use cases where the user can lose inputted data otherwise.
