### ISSUE TITLE
HTTP/2 HTTP/3 support?

### ISSUE THREAD

**Issue by khteh** [quasarframework/quasar#11019]
Launching `quasar dev` locally shows that it is on HTTP/1.1 GitHub page is using HTTP/2 though.
How to enable support for HTTP/2? If it doesn't at the moment, any plan to support HTTP/2 and/or HTTP/3?

**Comment by hawkeye64** [comment]
`quasar dev` uses the package `webpack-dev-server.`
You should look at that site and ask on their repo.
Quasar will support it if they do.

https://webpack.js.org/configuration/dev-server/
https://github.com/webpack/webpack-dev-server#readme

**Comment by khteh** [comment]
It works with the following quasar.conf.js using self-signed cert:
```
    devServer: {
      http2: true,
      https: {
        key: fs.readFileSync('server.key'),
        cert: fs.readFileSync('server.crt'),
      },
```
However, some node packages are using deprecated symbols:
```
(node:155094) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(node:157424) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
```

**Comment by rstoenescu** [comment]
@khteh Those warnings should be reported to webpack-dev-server. Those are not Quasar code.
