### ISSUE TITLE
QScrollArea inside into QCollapsible dont scroll at Web (Chrome and Mozilla)

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1101]
### Software version

Quasar: 0.14.6
OS: Win10x64
Node: 6.10.2
NPM: 3.10.10
Browsers: Chrome 62
iOS: ---
Android: Run OK
Any other software related to your bug:

### What did you get as the error?
Dont appear right scroll

### What were you expecting?

At Web chrome 62 # dont show scroll bar
At Android run OK (chrome and Samsung Browser) and APK run but dont apperars scroll bar.

### What steps did you take, to get the error?
See source below:

`<template>
  <q-collapsible icon="folder" label="Grupo">
    <q-scroll-area style="height:90px;" class="bg-grey-3 round-borders shadow-2">
      <div v-for="(grupo, index) in grupos" class="row">
        <span style="width:75%;">{{grupo.nome}}</span>
        <q-icon name="edit" color="blue" size="24px" style="width:30px"/>
        <q-icon name="delete" color="red" size="24px" style="width:30px"/>
      </div>
    </q-scroll-area>
  </q-collapsible>
</template>

<script>
import {
  QCollapsible,
  QIcon,
  QScrollArea
} from 'quasar'

export default {
  components: {
    QCollapsible,
    QIcon,
    QScrollArea
  },
  computed: {
  },
  data () {
    return {
      grupos: [{nome: 'Pizza'}, {nome: 'Bebida'}, {nome: 'Doce'}, {nome: 'Sobremesa'}, {nome: 'Especiais'}, {nome: 'Opcionais'}, {nome: 'Promoções'}, {nome: 'Especial do Dia'}]
    }
  }
}
</script>

<style scoped>
</style>
`

**Comment by rstoenescu** [comment]
QScrollArea makes sense only desktop browsers to actually hide the default ugly ones. By default, mobile browsers (including mobile apps) hide the scrollbar and show it only scrolling is occurring, so Quasar can rely on that.

Bottom line, why should Quasar not rely on the default behaviour on mobile browsers / mobile apps?

**Comment by LuizLeite** [comment]
Ok. I understand that.
But you dont understant this issue or my explanation was poor.
There are 8 grupos (groups), but only 4 appears and the mouse cant scroll.
Run the code below.
[Test.txt](https://github.com/quasarframework/quasar/files/1459125/Test.txt)

**Comment by rstoenescu** [comment]
I just revisited this ticket. QScrollArea inside into QCollapsible is not supported. Sorry. Let me know if you need more details.
