### ISSUE TITLE
Vetur to Volar => undefined problem in modelValue

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#11018]
Hello,
when I changed Vetur to Volar, all my q-input, q-select.. generates these errors :
```
Cannot assign type 'string | undefined 'to type' string | number'.
Cannot assign type 'string | undefined 'to type' string | number | any [] '.
```
but normal  (html) inputs no.

the cause is the declaration file it does not contain **undefined**

` modelValue: string | number;`

I am using DTOs which may have null or undefined values, 
DTOs are generated with OpenApi Generator, and any fields not required are converted to string | undefined.
so either I have to change the q-input by input, or else create intermediate DTOs and do a **DTO** <-> **[DTO without undefined]** mapping, which will add complexity for nothing and a loss of performance

OR
add undefined to all modelValue on  Quasar declaration file ?
like this :
`modelValue: string | number | undefined;`

if you have any solutions or tips for this kind of problem, i will be very grateful to you

example :

-------> script
```typescript
interface TestDTO
{
  a: string | undefined;
  b: string;
}

const entry : Ref<TestDTO> = ref(<TestDTO>{});
```

-----> in template :
```html
** with Volar 
<q-input v-model="entry.a" />   // Volar cast error
<q-input v-model="entry.b" />  // OK 

<input v-model="entry.a" />   // OK
```

```html
** with Vetur 
<q-input v-model="entry.a" />   // OK
<q-input v-model="entry.b" />  // OK 

<input v-model="entry.a" />   // OK
```
 

even by forcing the values, still the same problem with Volar
```typescript
const entry : Ref<TestDTO> = ref(<TestDTO>{a: '',  b: ''});

```

**Platform (please complete the following information):**
Quasar Version: 2.1.4

thank you for your precious time..

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.1.6.

**Comment by RejDev** [comment]
Thank-you for your prompt response,
Can you also add **undefined** for optional fields ?    ( field **?** :  type )

```typescript
interface TestDTO
{
  field? : string | null;
}
```
generate :
```typescript
field : string | null | undefined
```

**Comment by rstoenescu** [comment]
Pushed another commit. Will be available in Quasar v2.1.8

**Comment by rstoenescu** [comment]
Made other improvements as well.

**Comment by ItsClemi** [comment]
Awesome!

Does Volar require the ``modelValue`` property in the type definitions?

Because when used with tsx, ts also requires this property which then clashes with ``v-model`` usage.
Therefore we currently replace all required ``modelValue:`` properties with optional ones via patch files.

Eg.:
```shell
@@ -1362,7 +1362,7 @@ export interface QBtnDropdownProps {
   /**
    * Controls Menu show/hidden state; Either use this property (along with a listener for 'update:modelValue' event) OR use v-model directive
    */
-  modelValue: boolean;
+  modelValue?: boolean;
   /**
    * Size in CSS units, including unit name or standard size name (xs|sm|md|lg|xl)
    */
```

Thanks 🥳

**Comment by RejDev** [comment]
Hello,

@rstoenescu ,  for the **q-select**  v-model, i think it would be better to add  >> **any** << also for a unique selection result. 
(with  `any[]` , **modelValue** only accepts arrays of objects)

```typescript
modelValue: number | string | any[] | **any** | null | undefined;
```

thank you so much.
