### ISSUE TITLE
Bug report/Design discussion: Use QSelect as a combobox

### ISSUE THREAD

**Issue by hermit99** [quasarframework/quasar#11022]
**Is your feature request related to a problem? Please describe.**
I just started using Quasar and enjoyed it until I bumped into QSelect. My use case is to use it to auto complete address search, i.e. user inputs some characters then trigger an Ajax call to get a list of addresses remotely. User then select one of them, task done.

As there is no Quasar component similar to Vue Combobox, the only closest solution may be the QSelect, here is my work-around:

     <q-select
       v-model="input"
       :options="store.addresses"
       @filter="loadOptions"
       @input-value="doSearch"
       @update:model-value="addressSelected"
       clearable
       fill-input
       hide-dropdown-icon
       hide-selected
       use-input
       input-debounce="0"
       label="Search address">

       <template v-slot:append>
         <q-icon name="search"/>
       </template>
     </q-select>

But there are three main issues:

1. When input loses focus, the input value gets reset.
This is annoying and unexpected behavior in many cases. It also triggers additional Ajax call in my example as the input value was changed by this undocumented behavior.

2. input-debounce option is misleading. It doesn't debounce the input at all, but just a delay to filter.

3. Use filter event for lazy loading options data is not ideal. It's a ugly work-around to current limitations.

**Describe the solution you'd like**
For issue 1, please remove resetInputValue() @line1472
For issue 2, please use lodash _debounce to make this input-debounce option more relevant.
For issue 3, I would hope the design of this component be enhanced, or maybe create a new component similar to this [AutoComplete](https://www.iviewui.com/components/auto-complete-en) component in View Design?

**Describe alternatives you've considered**
For issue 2, we should update the document if a real debounce is not going to be implemented.

Thanks for consideration.

**Comment by rstoenescu** [comment]
The QSelect component is battle tested and covers all possible use-cases, including yours.
https://quasar.dev/vue-components/select#example--text-autocomplete (QSelect -> Text autocomplete)

The filter() doesn't need a debounce (btw, Quasar exports that util baked in-house too). It already has it through the need to call the update() function. Its purpose is to do any async work outside of it then call update() to set the actual value.

Feel free to post a codepen with what you tried in case I missed something.
