### ISSUE TITLE
Icon is not showing complete when build desktop application in windows

### ISSUE THREAD

**Issue by GHChrisSu** [quasarframework/quasar#11025]
**Describe the bug**
Use command to build all desktop application
`quasar build -m electron -T all`
The icon in mac is good, but in windows only 1/4 part was shown
I thought that was icongenie problem when generate the icon.ico, then I used the `Axialis IconWorkshop` to create the ico for windows, but it still not working.

**To Reproduce**
`quasar build -m electron -T all` 
install windows exe

**Expected behavior**
icon show complete

**Screenshots**
![image](https://user-images.githubusercontent.com/13779988/137730473-477d8172-4406-42d3-a254-afaeab37237b.png)
![image](https://user-images.githubusercontent.com/13779988/137730481-5bc791fe-cbb6-4189-a404-1fbf7e028e07.png)

**Platform (please complete the following information):**
Quasar Version:^2.0.2
@quasar/app Version:^3.0.2

Quasar mode:
  - [*] Electron

Tested on:
  - [*] Electron

OS: win10
Node: 14.17
NPM: 6.14.13

**Comment by rstoenescu** [comment]
This is handled by electron-packager or electron-builder (whatever you chose). Please open them a ticket instead as this is outside of Quasar's reach. Thank you.
