### ISSUE TITLE
Style attribute does not work with QTooltip

### ISSUE THREAD

**Issue by gaw89** [quasarframework/quasar#11033]
**Describe the bug**
[Quasar V2 docs indicate](https://quasar.dev/start/upgrade-guide#qdrawer-qdialog-qmenu-qtooltip) that QTooltip should no longer use `content-style` attribute but just `style`.  However, it appears the `style` attribute does not get applied to QTooltip.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gaw89/pen/OJjNeoq?editors=101

**To Reproduce**
1. Hover over the button

**Expected behavior**
I expect the style to be applied to QTooltip the same way it was in V1 with the "content-style" attribute.

**Platform (please complete the following information):**
Quasar Version:  2.1.2
@quasar/app Version: 3.1.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10 😢 
Node: 14.16.0
NPM: 7.6.3
Yarn: 1.22.10
Browsers: Chrome

**Additional context**
The docs indicate the same change for QDialog, and QDialog does appear to function correctly, as demonstrated [here](https://codepen.io/gaw89/pen/NWvNZBQ?editors=101).

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.1.6

**Comment by gaw89** [comment]
@rstoenescu, you are amazing!!
