### ISSUE TITLE
[QInput] Prefix and suffix are not visible when `label` prop is added

### ISSUE THREAD

**Issue by JercSi** [quasarframework/quasar#11036]
**Describe the bug**
I got unexpected behavior on q-input component when `label` property is added. Prefix and suffix are not visible until focus is made. When `label` is not used, prefix and suffix are visible all the time. See on the screenshot below.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/boring-moore-12s2z?file=/src/App.vue

**To Reproduce**
1. Add q-input component with label, suffix and prefix
2. Focus on input field to show the suffix and prefix

**Expected behavior**
Prefix and suffix should be visible all time, even when the `label` property is added.

**Screenshots**
![image](https://user-images.githubusercontent.com/5267726/137858350-a0dafda2-02ee-4882-b3da-4c4948a1743d.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.1.3, 2.1.4, 2.1.5

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10, Running in docker container
Node: 16.11.0-alpine
NPM: -
Yarn: 1.22.15
Browsers: Firefox, Chrome
iOS: -
Android: -
Electron: -

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

This is by design as per Material specs.

**Comment by pdanpdan** [comment]
Hello. This is so by design. If you want them always visible with label use stack-label

:)
