### ISSUE TITLE
Feature: Alignment inside q-data-table (especially headers)

### ISSUE THREAD

**Issue by Spoja** [quasarframework/quasar#1104]
Again me, i noticed there is no simple way to align headers of q-data-table. Currently you can only align values and headers in columns by adding style in definiton of columns of the table like this:

```
columns: [
  { label: 'column',
          field: 'col',
          width: '50px',
          filter: false,
          sort: true,
          style: 'text-align: right' // style: text-align: 'right' causes error because 
                                    // of '-', other way to do it is style: { 'text-align': 'right'}
]
```
This will align only values but not header, to align header you have to add ref to your data table and then in mounted through that ref change the alignment of chosen header:
```
this.$refs.dataTable.$children[2].$el.children[1].lastChild.children[column_number].align = 'right'
```
Having headers and values aligned to right is almost always needed when displaying currency, so im suggesting to add simpler way of changing it. 
Maybe add it to the definitions of columns like this (I dont think you ever need your header and data aligned differently so they can be both changed by property align):
```
columns: [
  { label: 'column',
          field: 'col',
          width: '50px',
          filter: false,
          sort: true,
          align: right
]
```
Or you could just change that current attribute style applies on headers aswell.

**Comment by rstoenescu** [comment]
This is already enhanced in future v0.15. Closing as it's implemented.
