### ISSUE TITLE
When build browser extention, index.html (for popup window) must be in www folder (according to manifest)

### ISSUE THREAD

**Issue by FragsterAt** [quasarframework/quasar#11047]
**Describe the bug**
When build browser extention and add it to browser - popup button doesnt work with file not found error until you copy index.html in www folder

**To Reproduce**
1. create fresh quasar project
2. add BEX mode: `quasar mode add bex`
3. add popup window to manifest:
```json
  "browser_action": {
    "default_title": "quasar-browser-extension",
    "default_popup": "www/index.html"
  },
```
with path `"default_popup": "index.html"` popup didn't work

4. check in dev mode: `quasar dev -m bex` - all work, popup shoving:
![изображение](https://user-images.githubusercontent.com/20900647/138051656-869c581a-9f92-4c91-b97e-a71f8f5b03c7.png)

5. build `quasar dev -m bex` 
6. add unpacked ext to browser from `/dist/bex/UnPackaged` - popup dint works:
firefox:
![изображение](https://user-images.githubusercontent.com/20900647/138052143-cad4dbbc-acf1-4976-b16b-becffc821b50.png)
chrome:
![изображение](https://user-images.githubusercontent.com/20900647/138052083-966f76a6-6676-4f23-bccd-c597edb0d9fe.png)

**Expected behavior**
working 

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.1.7

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [+] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [+] BEX

OS: win 10
Node: 14.17
NPM: 7.16
Browsers: chrome 94, firefox 93

**Additional context**
workaround is to copy index.html from `/dist/bex/UnPackaged` to `/dist/bex/UnPackaged/www` after build

**Comment by rstoenescu** [comment]
Fix will be available in q/app v3.1.7
