### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by khteh** [quasarframework/quasar#11046]
**Describe the bug**
Upgraded to Node.JS 17.0.0 and bump into this error:
```
$ quasar dev

 Dev mode.......... spa
 Pkg quasar........ v2.1.5
 Pkg @quasar/app... v3.1.4
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 88.66% of global marketshare):
 · Chrome for Android >= 94
 · Firefox for Android >= 92
 · Android >= 94
 · Chrome >= 85
 · Edge >= 91
 · Firefox >= 84
 · iOS >= 11.3-11.4
 · Opera >= 76
 · Safari >= 12

 App • Running "@quasar/dotenv" Quasar App Extension...
 App • Running "@quasar/testing" Quasar App Extension...
 App • Running "@quasar/testing-unit-jest" Quasar App Extension...
 App • Running "@quasar/testing-e2e-cypress" Quasar App Extension...
 App • Extension(@quasar/dotenv): Extending quasar.conf...
 App • Extension(@quasar/testing-e2e-cypress): Extending quasar.conf...
 App • Chaining "UI" Webpack config
(node:42896) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 App •  WAIT  • Compiling of "UI" in progress...

 • Compiling:
 └── UI ██                   7% setup compile ExternalsPlugin

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

[  Error: error:0308010C:digital envelope routines::unsupported
  
  - hash:67 new Hash
    node:internal/crypto/hash:67:19
  
  - node:crypto:130 Object.createHash
    node:crypto:130:10
  
  - createHash.js:155 BulkUpdateDecorator.hashFactory
    [khteh]/[webpack]/lib/util/createHash.js:155:18
  
  - createHash.js:80 BulkUpdateDecorator.digest
    [khteh]/[webpack]/lib/util/createHash.js:80:21
  
  - DefinePlugin.js:595 
    [khteh]/[webpack]/lib/DefinePlugin.js:595:38
  
  
  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [khteh]/[tapable]/lib/Hook.js:14:14
  
  - Compiler.js:1053 Compiler.newCompilation
    [khteh]/[webpack]/lib/Compiler.js:1053:26
  
  - Compiler.js:1097 
    [khteh]/[webpack]/lib/Compiler.js:1097:29
  
  
] {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.0

```
**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 21.10
Node: 17.0.0
NPM: 8.1.0
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by MilosPaunovic** [comment]
This doesn't seem to be related to Quasar.

Quick Google search says:

> There is a hashing algorithm that comes with webpack v5.54.0+ that does not rely on OpenSSL.
> 
> To use this hash function that relies on a npm-provided dependency instead of an operating system-provided dependency, modify the webpack.config.cjs output key to include the hashFunction: "xxhash64" option.
> 

Check this out:
https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by khteh** [comment]
Why isn't this "related to" Quasar when quasar uses webpack-dev-server under the cover without our knowledge at all and it's not something that we installled ourselves?

**Comment by MilosPaunovic** [comment]
Quasar only utilises that library, it can't change its source code.

**Comment by khteh** [comment]
Which version of webpack is used by quasar? The solution provided in the URL does not work as there is no `webpack.config.js`.

**Comment by MilosPaunovic** [comment]
Quasar 2 is using Webpack 5 in the background.

**Comment by khteh** [comment]
Is it `v5.54.0+`? How to tell webpack to use which `hashFunction` since there is no `webpack.config.js`?

**Comment by rstoenescu** [comment]
This should be reported and fixed by the webpack-dev-server team.

@khteh how is it "without your knowledge"; it's all over the Quasar docs. Just do a search for webpack-dev-server. Example:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/4665641/138065158-1e74db51-8d4e-4c17-916b-82a04a3f0c81.png">

**Comment by ldiebold** [comment]
Currently, this will happend if you're on node 17 (latest node)
Here is a workaround for the meantime: https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

specifically...

```shell
export NODE_OPTIONS=--openssl-legacy-provider
```

You can add the above to `package.json` then run `yarn dev` or `npm run dev`

```json
{
  "scripts": {
    "dev": "export NODE_OPTIONS=--openssl-legacy-provider && quasar dev"
  }
}
```

Having said that, it's probably **best to move to node 16**
node **odd** version numbers are experimental and not supported by many frameworks (I believe this is the case with Quasar)
node **even** version numbers are stable, and far less likely to cause issues

**Comment by milad4444** [comment]
@ldiebold
![Screenshot 2022-12-08 212106](https://user-images.githubusercontent.com/48815319/206526782-9100aee5-fb35-475c-92f0-ff895e847117.jpg)
 thank you that worked for me
