### ISSUE TITLE
Q-Date only year or year+month

### ISSUE THREAD

**Issue by cimpok** [quasarframework/quasar#11049]
Is it possible to use Q-Date to ask for the year or year+month only and not the full date? If not, could you please consider adding this feature. Thank you.

**Comment by MilosPaunovic** [comment]
Take a look at the `QScroller` extension.
https://quasarframework.github.io/quasar-ui-qscroller/docs

**Comment by pdanpdan** [comment]
duplicate of https://github.com/quasarframework/quasar/issues/9419

**Comment by sinbino** [comment]
QScroller does not support vue3...

**Comment by hawkeye64** [comment]
> QScroller does not support vue3...

It does not and will likely be deprecated.
