### ISSUE TITLE
Default QInput Debounce to 0

### ISSUE THREAD

**Issue by MRR0GERS** [quasarframework/quasar#11041]
**Is your feature request related to a problem? Please describe.**
I have a lot of QInput components that are freeform text and there is a delay while typing in the inputs

**Describe the solution you'd like**
Default the debounce for QInput to 0

**Describe alternatives you've considered**
I could manually set the debounce prop for all instances but would like to avoid this if possible.

**Additional context**
I really like Quasar.

**Comment by pdanpdan** [comment]
There is no debounce by default in QInput
