### ISSUE TITLE
`muted` property is removed from `video` tag ?

### ISSUE THREAD

**Issue by lambda0xff** [quasarframework/quasar#11054]
**Describe the bug**
When adding the `muted` property to a `video` tag, it seems to be removed automatically ?

This is very annoying since it breaks this behavior: https://developers.google.com/web/updates/2016/07/autoplay
which allows to autoplay videos on mobile browsers

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/lambda0xff/pen/MWvjqRm

**To Reproduce**
1. go to the pen
2. view source
3. the autoplay and loop properties are there but the 'muted' property is gone

**Expected behavior**
Should keep the 'muted' property

**Platform (please complete the following information):**
Quasar Version:2
@quasar/app Version:

Quasar mode:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

The `<video>` tag is a native element. Has nothing to do with Quasar. It's handled by the browser directly. At best, it could be a problem in vue-loader (outside of Quasar's reach), but I doubt it.

**Comment by hawkeye64** [comment]
@lambda0xff As the authour of QMediaPlayer, I found the best way to handle some of these items, like `muted` is to put a ref on the tag and then set it directly instead of some attributes.

ie:
```
<video ref="videoRef" width="320" height="240">
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>
```
```
videoRef.muted = true
```
