### ISSUE TITLE
Q-rating does not display tooltip when custom icon is used

### ISSUE THREAD

**Issue by mastnym** [quasarframework/quasar#11055]
**Describe the bug**
When svg icon is used in q-rating component like `icon="img:icons/blah.svg"` and one want to display tooltip, no tooltip is shown. I think it's related to [this issue](https://github.com/quasarframework/quasar/issues/6618), but there is no way in q-rating to wrap the icon in `div/span`

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/rating#tooltips
Example is broken

**To Reproduce**
Create a q-rating component with custom svg icon
Add a q-tooltip via slot `tip-1` to this icon
Tooltip is not displayed

**Expected behavior**
Tooltip should be visible on hover

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.1.8/edge

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:y
NPM:y
Yarn:
Browsers: chrome, FF
iOS:
Android:
Electron:

**Additional context**

**Comment by hawkeye64** [comment]
@mastnym Indeed, the examples are not working as expected. Thank you for letting us know.n It appears they are being created at the end of the document, they just don't display.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.10
