### ISSUE TITLE
Q-tree doesn't default expand new nodes when default-expand-all set

### ISSUE THREAD

**Issue by yesennes** [quasarframework/quasar#11052]
**Describe the bug**
`default-expand-all` doesn't work when nodes are changed after `q-tree` is automatically expanded. 

**To Reproduce**
Make a `q-tree` with `default-expand-all` set. Use a button to change the `nodes` of the `q-tree`. The new nodes won't be expanded.

Here's a quick code pen showing the behavior: https://codepen.io/yesennes/pen/dyzpzbJ

**Expected behavior**
New nodes would be expanded like starting nodes. Obviously there are easy workarounds to this, but it'd still be nice if the auto-expanded.

**Platform (please complete the following information):**
Quasar Version:
quasar@2.1.8

OS: Ubuntu
Node: v12.22.6
Yarn: 1.22.15
Browsers: Chrome 94.0.4606.81

**Comment by hawkeye64** [comment]
@yesennes It says right in the documentation that `default-expand-all` is only applied to the first rendering.

![image](https://user-images.githubusercontent.com/10262924/139702703-4195ec08-c2b6-46b0-9ee1-6675d3d44f29.png)

The work-around for what you want is to use the `selected` array to add your keys automatically when switching tree branches.

**Comment by nekooee** [comment]
> **Describe the bug** `default-expand-all` doesn't work when nodes are changed after `q-tree` is automatically expanded.
> 
> **To Reproduce** Make a `q-tree` with `default-expand-all` set. Use a button to change the `nodes` of the `q-tree`. The new nodes won't be expanded.
> 
> Here's a quick code pen showing the behavior: https://codepen.io/yesennes/pen/dyzpzbJ
> 
> **Expected behavior** New nodes would be expanded like starting nodes. Obviously there are easy workarounds to this, but it'd still be nice if the auto-expanded.
> 
> **Platform (please complete the following information):** Quasar Version: quasar@2.1.8
> 
> OS: Ubuntu Node: v12.22.6 Yarn: 1.22.15 Browsers: Chrome 94.0.4606.81

add key for Re-rendering component if change items. for example:

```js
<q-tree
        :nodes="items"
        node-key="id"
        :key="items.length"
        v-model:ticked="selected"
        v-model:expanded="expanded"
        default-expand-all
        label-key="title"
        :filter="search"
      />
```
