### ISSUE TITLE
[v0.15] Datatable - Filtering broken when NOT using lowercase

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1105]
### Software version

Quasar:0.15
OS:Windows7 & Linux
Node:6.11.5
NPM:4.1.2
Browsers:Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

![image](https://user-images.githubusercontent.com/7946730/32512115-eda20e32-c3c3-11e7-89ca-4bad8766f87b.png)

If we try filtering the datatable for keyword `Eclair` we get no result

![image](https://user-images.githubusercontent.com/7946730/32512140-0b8630d6-c3c4-11e7-9d77-2addfb53d201.png)

But if we try using the keyword `eclair`, now it's working perfectly.

![image](https://user-images.githubusercontent.com/7946730/32512163-290d5094-c3c4-11e7-9bc2-be66fe025bef.png)

### What were you expecting?

Searching may be case sensitive or insensitive but not forcing us to search in lower case only.

To fix this, we could replace this line
https://github.com/quasarframework/quasar/blob/eeb4050dd6ad1d35fee9ff1372efe990bb4a8ed8/src/components/table/table-filter.js#L8
by
```javascript
row => cols.some(col => (cellValue(col, row) + '').toLowerCase().indexOf(terms.toLowerCase()) !== -1)
```

**Comment by rstoenescu** [comment]
Hi, Care for a quick PR?

**Comment by purell** [comment]
Yes with pleasure ;)

By the way, when will you have time to release a new quasar-future release ? I've got some problem with issue (https://github.com/quasarframework/quasar/issues/1063) and I noticed that a patch has been applied 4 days ago. But quasar-future is 10 or more day older...

**Comment by rstoenescu** [comment]
There are some breaking changes. Like your app needs to have a root QApp (new component) and also the QLayout has changed syntax a bit (but not yet finalized). I need to document all these somehow before doing a new quasar-future build and currently on a very tight schedule. I guess I'll just release a new version and let devs look at the examples to figure out the changes (they are easy ones)... Wish I weren't on such a tight schedule :(

**Comment by purell** [comment]
No problem, I using quasar-future since two week and I mostly learn using the `dev` exemple folder. By the way, I really like the new data table, it very flexible and well thought out.

I'm doing the PR right now. Thank you so much.

**Comment by purell** [comment]
https://github.com/quasarframework/quasar/pull/1106
