### ISSUE TITLE
QRange - a markers option independent of the step one

### ISSUE THREAD

**Issue by carueda** [quasarframework/quasar#11058]
**Is your feature request related to a problem? Please describe.**

The `marker`/`step` combination works great in general: one gets those nice little markers according to the step.

However, while dragging the range (or any of its ends), the relevant value(s) are "forced" according to the `step`, that is, one can not just select any value within the min/max of the range. This behavior would seem more appropriate if `snap` is also used. Sure, changing the semantics of these existing options would break compatibility, so below is a suggestion.

**Describe the solution you'd like**

A new option, say, `with-markers`, that allows to get the visual effect of the nice little markers, with no dependency on the traditional `step` option.

**Describe alternatives you've considered**

The ['Getting creative' section in the doc](https://quasar.dev/vue-components/range#getting-creative) certainly provides a possible alternative via styling, etc. However, simply setting something like `with-markers=50` would be very handy (and probably not requiring a lot of implementation effort in quasar).

**Additional context**

I entered this for v1, but, per the v2 documentation, seems like it may still be relevant for v2.  Thanks!

**Comment by rstoenescu** [comment]
Hi,

Trying to understand the request.

Are you sure that you're not referring to the already available `:step="0" markers` combination? Step 0 means infinite precision, and you can also display the markers.

Or are you referring to step 0 along with a markers="N", where N would be the step for the markers themselves?

**Comment by carueda** [comment]
Thanks for the quick response.

> Are you sure that you're not referring to the already available :step="0" markers combination? Step 0 means infinite precision, and you can also display the markers.

That would work (I need infinite precision in the sense of allowing the dragging to finish in _any_ value within the range), **but** the `markers` option is directly associated to the `step` option as far as I understand the doc (and consistent with actual code).

> Or are you referring to step 0 along with a markers="N", where N would be the step for the markers themselves?

I think this better aligns to what I have in mind:  just setting `:markers="N"` would be great. The concrete use case here is just about showing the markers via a straightforward option while no preventing the user from setting any value within the min/max range. So, probably make the existing `markers` option accept no only Boolean, but also a number, in this case with the new suggested behavior.  Hope that helps clarify. Thanks again!

**Comment by rstoenescu** [comment]
Custom markers step ("markers" prop accepting Number as well) for QSlider and QRange will be available in Quasar v2.2.1.

**Comment by carueda** [comment]
wow, that was really quick, thanks much!

Although one more reason to put the migration to v2 higher in my TODO list, unfortunately that won't happen any time soon (so, just wondering whether this enhancement could be ported to v1 as well.)

**Comment by carueda** [comment]
Great to see this has been back-ported to Qv1!!
