### ISSUE TITLE
Wrong generated quasar-user-options

### ISSUE THREAD

**Issue by Pietervanhalem** [quasarframework/quasar#11064]
**Describe the bug**
I created a quasar2 app with quasar create and then I added the Notify component to my quasar.conf.js however when I run ```quasar dev``` my ```quasar-user-options``` file looks like the following. This means that I cannot use the notify plugin (or any other quasar plugin). I also cannot manualy change it because when I run quasar dev it gets overwritten.

What me confuses is that:

```js
    showNotify3() {
      Notify.create({
        message: 'Jim pinged you.',
        icon: 'announcement',
      });
    },
```
also doesn't work...

Can some confirm if this is a bug or if it is not a bug help me to fix it?

**Codepen/jsFiddle/Codesandbox (required)**
Since it has to do with the quasar-cli it is not reproduceable in jsFidle etc...
https://github.com/VanOord/quasar-notify

**To Reproduce**
1. Go to 'index page of https://github.com/VanOord/quasar-notify'
2. Click on 'one of the notify buttons'
3. Scroll down to 'N.A.'

**Expected behavior**
the file ```quasar-user-options``` should generate as:

```js
/**

 * THIS FILE IS GENERATED AUTOMATICALLY.

 * DO NOT EDIT.

 *

 * You are probably looking on adding startup/initialization code.

 * Use "quasar new boot <name>" and add it there.

 * One boot file per concern. Then reference the file(s) in quasar.conf.js > boot:

 * boot: ['file', ...] // do not add ".js" extension to it.

 *

 * Boot files are your "main.js"

 **/





 import {Notify,Loading} from 'quasar'





 export default { config: {},plugins: {Notify,Loading} }
```

but generates as:

```ks
/**
 * THIS FILE IS GENERATED AUTOMATICALLY.
 * DO NOT EDIT.
 *
 * You are probably looking on adding startup/initialization code.
 * Use "quasar new boot <name>" and add it there.
 * One boot file per concern. Then reference the file(s) in quasar.conf.js > boot:
 * boot: ['file', ...] // do not add ".js" extension to it.
 *
 * Boot files are your "main.js"
 **/




export default { config: {} }
```

resulting in not being able to use the notify plugin

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:3.1.4

Quasar mode:
  * SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  * SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: v16.10.0
NPM: 7.24.0
Yarn:
Browsers: chrome
iOS: NA
Android:NA
Electron:NA

**Additional context**

**Comment by MilosPaunovic** [comment]
Your file doesn't seem properly formatted:
https://github.com/VanOord/quasar-notify/blob/master/src/pages/Index.vue

```js
export default defineComponent({
  name: 'PageIndex',
  setup() {
    // from https://quasar.dev/quasar-plugins/notify
    const $q = useQuasar();

    return {
      notify() {
        $q.notify({
          message: 'Jim pinged you.',
          icon: 'announcement',
        });
      },
      showNotify2() {
         $q.notify({
            message: 'Jim pinged you.',
            icon: 'announcement',
          });
      },
      showNotify3() {
         $q.notify({
            message: 'Jim pinged you.',
            icon: 'announcement',
         });
      },
    };
  },
```

Check official docs for examples:
https://quasar.dev/quasar-plugins/notify

**Comment by rstoenescu** [comment]
Hi,

Your quasar.conf.js is returning a malformed Object. Most of the stuff seems to be under the "build" root prop, including "devServer", "ssr" etc.

```
"build": {
   // ...,
   devServer: ..., // <<--- should be root prop, at same level with "build"
   ssr: ..., // <<--- should be root prop, at same level with "build"
   framework: ..., // <<--- should be root prop, at same level with "build"
}
```

Check all props. The above are just a few examples and not a complete list of props wrongly added under "build".

**Comment by Pietervanhalem** [comment]
Thank you so much, that fixed it! sorry to bother you...
