### ISSUE TITLE
cli exit code 0 for unknown command

### ISSUE THREAD

**Issue by moander** [quasarframework/quasar#11063]
I get exit code 0 when `quasar build` fails with error `Unknown command "build"`

**To Reproduce**
1. Go to a folder without quasar
2. Run `quasar build`
3. Run `echo $?`
4. See exit code 0

**Expected behavior**
exit code 1

**Platform (please complete the following information):**
Quasar CLI v3.0.4

**Comment by MilosPaunovic** [comment]
> Go to a folder without quasar

You can't build empty folder.

**Comment by moander** [comment]
> You can't build empty folder.

That is why I expect exit code != 0. Now the CLI signals that the empty folder was built successfully.

**Comment by MilosPaunovic** [comment]
Ohhh, I understand now.

It should potentially be `command not found` code `127` or the `general errors` code `1`
[https://tldp.org/LDP/abs/html/exitcodes.html](https://tldp.org/LDP/abs/html/exitcodes.html)

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fixed in "@quasar/cli" v1.2.2 -- the (optional) global installable part of Quasar CLI.

(just released it)
