### ISSUE TITLE
QSelect disabled showing options

### ISSUE THREAD

**Issue by rodrigobr92** [quasarframework/quasar#1107]
Quasar: 0.14.7
OS: MacOS
Node: 6.11.0
Browsers: Chrome, Firefox, Safari

When using the q-select with the disabled prop, the popover still shows when clicked, even if the model doesn't have any values.

Example: 
On Html: <q-select v-model='subcategory' :options="subcategoryList" :disabled="true" inverted></q-select>

On data return: subcategoryList: [],

**Comment by pdanpdan** [comment]
The prop is disable.

**Comment by rstoenescu** [comment]
As stated, the property name is "disable", not "disabled".
