### ISSUE TITLE
QEditor using deprecated font element

### ISSUE THREAD

**Issue by mseiimeorn** [quasarframework/quasar#11074]
**Description:**
When using the QEditor it is adding the font styles by using the `<font>` HTML element, e.g. for the font size.

According to [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font](url) this is deprecated.
It should instead use CSS Fonts properties, like here:
[https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts](url).

**Comment by rstoenescu** [comment]
As we stated in the documentation, QEditor is based on the native document.execCommand. The browser itself handles the DOM transformations, so it's out of our reach.
