### ISSUE TITLE
Disable Page Scroll When Drawer Is Open

### ISSUE THREAD

**Issue by BrianMoreno1994** [quasarframework/quasar#1108]
Hi, I'm having a bit of a problem. I want to disable page scroll when the drawer is opened. Right now when I open the drawer the user can tap and hold on an element outside the drawer and start scrolling. This results in the toolbar, drawer and content getting out of place. 

This is a video example of my problem: [https://www.youtube.com/watch?v=HqsCOBazNrE](https://www.youtube.com/watch?v=HqsCOBazNrE)

Any help is greatly appreciated! :)

**Comment by rstoenescu** [comment]
Hi,

There is a issue template when you hit the "New issue" button. Kindly ask you to fill that out, it has all the necessary information for me to investigate. Thank you!

**Comment by cklinx** [comment]
Same problem with QModal Component: i solved adding (when modal is opened) and removing (closed) this class to body:

`.fixedBody
  left: 0
  -webkit-overflow-scrolling: touch
  position: fixed
  top: 0
  width: 100%`

hope help.

**Comment by rstoenescu** [comment]
I believe this is already fixed in v0.15 anyway. Will check later.

**Comment by leuterio** [comment]
The solution of @cklinx worked for me. Thanks man.

**Comment by gyohng** [comment]
I think, this still does not apply to modals (0.16).
