### ISSUE TITLE
Some way to make `QInput` hide the validation output div when empty to keep vertical density.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#11093]
**Is your feature request related to a problem? Please describe.**

I need to display a vertical list of QInput fields with minimal vertical spacing between them (dense). I use the `dense` property however, if any of the fields have a :rule=[...]" property, QInput adds unwanted vertical spacing to display the rule result, even when the field is untouched or valid (i.e. no invalid message). This kinda ruins the "dense" vertical spacing. Worse, If you have a mixture of QInput fields .. some with :rule values and some not then the vertical spacing becomes ugly and inconsistent.  

Vertical density is big deal for large enterprise apps where you frequently need to pack many fields onto a limited space in the page and avoid scrolling. 

**Describe the solution you'd like**

I realise that QInput rendering needs to remain backward compatible so my suggestion is that we add to QInput a `dense-rules` property to remove the rule message div when there's no message thus keeping the layout vertically dense. You might have another suggestion. 

**Describe alternatives you've considered**

I've considered using hacks like conditionally adding the rule array when a value is keyed in and using `reactive-rules` but for my current case where I'm are just checking Required fields, this does not really work since it's only **empty** and **touched** fields that need to display a message.   

**Additional context**

Example showing that adding / removing `:rule` array property adds/removes the vertical spacing.  

```html
        <div class="text-subtitle2">You</div>
        <div class="row q-gutter-sm">
          <q-input
            name="title" label="Title" v-model.trim="user.title"
            dense outlined style="min-width: 30px"
          />
          <q-input
            name="first_name" label="First Name" v-model.trim="user.first_name"
            dense outlined style="min-width: 250px"
            :rules="[(val) => !!val || 'Required' ]"
          />
          <q-input
            name="last_name" label="Last Name" v-model.trim="user.last_name"
            dense outlined style="min-width: 250px"
            :rules="[(val) => !!val || 'Required' ]"
          />
        </div>

        <div class="text-subtitle2">Your Spouse (optional)</div>
        <div class="row q-gutter-sm">
          <q-input
            name="spouse_title" label="Title" v-model.trim="user.spouse_title"
            dense outlined style="min-width: 30px"
          />
          <q-input
            name="spouse_first_name" label="First Name" v-model.trim="user.spouse_first_name"
            dense outlined style="min-width: 250px"
          />
          <q-input
            name="last_name" label="Last Name" v-model.trim="user.spouse_last_name"
            dense outlined style="min-width: 250px"
          />
        </div>
```

![image](https://user-images.githubusercontent.com/301525/138692062-21e96c1c-5d29-4b9f-b6fd-12693d5b55ce.png)

**Comment by MilosPaunovic** [comment]
What you're looking for is the `hide-bottom-space` prop of `QInput`.

**Comment by rstoenescu** [comment]
Hi, Milos (above) is right.

**Comment by tohagan** [comment]
Awesome! Thanks very much.
