### ISSUE TITLE
Scoped slot prarams types for QUploader

### ISSUE THREAD

**Issue by soulsam480** [quasarframework/quasar#11090]
**Is your feature request related to a problem? Please describe.**
As quasar is moving towards a fully types component lib, I think it'll be great to have types for QUploader scoped slots too. 
![image](https://user-images.githubusercontent.com/35460828/138633413-4b09a7f8-b067-40a9-ac06-a6442a4c0aec.png)

**Describe the solution you'd like**
- types scoped slot params for QUploader like other components

**Describe alternatives you've considered**

**Additional context**

@IlCallo @yusufkandemir

**Comment by rstoenescu** [comment]
@IlCallo @yusufkandemir Would you be so kind to take care of this, please? It only needs the definition for the slots in the API file instead of the current exemption.

**Comment by rstoenescu** [comment]
Changes will be available in Quasar v2.3.5

**Comment by paya-cz** [comment]
If I try this with the [example from documentation](https://quasar.dev/vue-components/uploader#example--custom-header), I am still seeing typescript errors for other scope properties such as:

- queuedFiles
- uploadedFiles
- isUploading
- canAddFiles
- canUpload

The error I am seeing reads:
`Property 'canUpload' does not exist on type 'QUploader'.`

quasar - 2.6.5

**Comment by rafaeldellaquila** [comment]
Still missing this types on v2.7.3
