### ISSUE TITLE
[proposal] Change Datetime values in IOS theme

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#1110]
Hi!

As I could see, now in Datetime component for _ios_ theme values change only by dragging. In my opinion it could be useful to change values also by click. For example (picture), if we want to change month we click above current selection and value decrease by 1; when we click below selection - month increase by 1. Same for others fields.

Thanks!

![untitled-1](https://user-images.githubusercontent.com/30389307/32630110-248fde4c-c5a4-11e7-9acc-5fdefc78e09e.jpg)

**Comment by rstoenescu** [comment]
No longer relevant for v1.0 and v0.17 has a feature freeze in effect.

**Comment by olegvakulenko** [comment]
Sorry for asking again, but I can't understand you answer. Is this impossible to make for some reason, or this is already done in v1.0, or it may be done somewhere in future?
