### ISSUE TITLE
[vite-plugin] Uncaught ReferenceError: QItem_label is not defined

### ISSUE THREAD

**Issue by bompus** [quasarframework/quasar#11106]
I'm only experiencing this bug when using the vite plugin `@quasar/vite-plugin`. When I use quasar + vite without vite-plugin, the code works as expected.

From what I can gather, it has something to do with quasar component functions not existing when the component is referenced inside of a v-else block.

I've created a minimal reproduction repo where you can comment/uncomment between several `import App from ...` lines in `main.js` to see the thrown ReferenceError on Broken1 and Broken2, then see it working on Working1 and Working2.

Additionally, you can comment the quasar() plugin block in `vite.config.js` and verify that Broken1 and Broken2 App examples work without errors being thrown.

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/bompus/quasar-vite-plugin-referenceerror

**To Reproduce**
1. Clone the reproduction repo
2. pnpm install
3. pnpm run dev
4. Open browser to vite-provided URL
5. See ReferenceError in browser console
6. Edit main.js and toggle between the various `import App from ...` lines
7. Edit vite.config.js and comment quasar vite plugin from being called, and the error does not occur.

**Expected behavior**
The page will render without throwing a ReferenceError.

**Platform:**
Quasar Version: 2.2.1
@quasar/app Version: 3.1.6
@quasar/vite-plugin Version: 1.0.0

Quasar mode:
  - [x] SPA

Tested on:
  - [x] SPA

OS: Linux Ubuntu 20.04
Node: 17.0.1
pnpm: 6.19.0
Browsers: Chrome 95.0.4638.54

**Comment by rstoenescu** [comment]
Thank you for reporting! And for the detailed description.
Fix is available in `@quasar/vite-plugin` v1.0.1.

**Comment by bompus** [comment]
I've confirmed this is now working. Thank you for the incredibly fast fixes!
