### ISSUE TITLE
YYYY formatter doesn't properly format years before 1000

### ISSUE THREAD

**Issue by tmas** [quasarframework/quasar#11104]
**Describe the bug**
Formatting a date in the year 999 or before using the YYYY formatter results in a 3-digit year

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tmas-the-lessful/pen/poreLed

**To Reproduce**
1. Enter a date in the Date field (or use the default)
2. See the date improperly formatted in the readonly formattedDate field

**Expected behavior**
Formatted date should be left-padded with zeros as necessary to display as 4 characters (e.g. 0999)

**Screenshots**
![image](https://user-images.githubusercontent.com/271652/138752837-fac736c2-708e-4646-8a1c-1020b98eb493.png)

**Platform (please complete the following information):**
Quasar Version: v1.16.0
@quasar/app Version: v1.9.6

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 21.04
Node: v14.17.2
NPM: N/A (6.14.13)
Yarn: 1.22.5
Browsers: Firefox 93.0, Chrome 95.0.4638.54 (Official Build) (64-bit)
iOS: untested
Android: untested
Electron: untested

**Additional context**
I believe the issue is that the YYYY formatter uses date.getFullYear() and doesn't check the number of characters the year will be as a string. Link to the relevant area of the code: https://github.com/quasarframework/quasar/blob/dev/ui/src/utils/date.js#L667

I found this issue in Quasar v1 but that part of the code doesn't seem to have changed in v2, so I believe this issue will be present there as well.

**Comment by pdanpdan** [comment]
Hello.
YYYY is the format for full year, not for year using 4 digits.
