### ISSUE TITLE
QInfiniteScroll loading slot after "done(true)" doesn't disappear, it's just invisible

### ISSUE THREAD

**Issue by aren1989** [quasarframework/quasar#11100]
**Describe the bug**
QInfiniteScroll loading slot after "done(true)" doesn't disappear, it's just invisible

**Codesandbox**
https://codesandbox.io/s/blissful-hypatia-onci2

**To Reproduce**
1. Go to Codesandbox link
2. Scroll down 3 time 
4. See "loading slot" already exist, just invisible

**Expected behavior**
I think the problem is "isWorking" variable in QInfiniteScroll.js, because it's not a reactive ref object and when it changes, template doesn't rendered again

**Screenshots**
![Screenshot (88)_LI](https://user-images.githubusercontent.com/10001337/138725303-90e233fb-ee34-40d6-b380-efe837659176.jpg)

**Platform:**
Quasar Version: 2.2.1

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [x] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [x] Capacitor
  - [ ] BEX

OS: Windows
Node: v14.15.4
NPM: 7.21.0
Yarn: x
Browsers: Chrome Version 95.0.4638.54
iOS: x
Android: 7.0 | chrome version 94.0.4606.85
Electron: x

**Additional context**
I changed the "isWorking" to ref object and the problem was solved, Maybe it work

**Comment by rstoenescu** [comment]
Thank you for reporting.
Fix will be available in Quasar v2.2.5.
