### ISSUE TITLE
documentation about configurating vue-gtags on quasar v2

### ISSUE THREAD

**Issue by eeerrrttty** [quasarframework/quasar#11116]
There is a awesome vuejs npm package to controll gtag.

https://github.com/MatteoGabriele/vue-gtag-next

I couldn't handle to import it on boot using quasar because of lack of documentation.

Can it be improved ? Can someone explain it to me ?

**Comment by pdanpdan** [comment]
Hello. It is already explained in the docs how to use the boot files.
Please use the discord channel or the discussions for help requests.
