### ISSUE TITLE
[Request] QSearch do not require icon

### ISSUE THREAD

**Issue by nueko** [quasarframework/quasar#1111]
Halo, It's just feature request to not require an icon to q-search or maybe accept boolean false to the icon props.

Thanks

**Comment by rstoenescu** [comment]
Hi, will do.

**Comment by nueko** [comment]
Also, what about omitting the default placeholder?

**Comment by rstoenescu** [comment]
This was implemented in v0.15. Forgot to close the ticket. `no-icon` Boolean prop.
