### ISSUE TITLE
Quasar v2 ssr deploy owner server witth https

### ISSUE THREAD

**Issue by lohonyai** [quasarframework/quasar#11126]
Hello!
I have an application which is SSR+PWA and I want to use it on my own server with https protocol. In the description it says that the system uses basic express, but where can I configure it? In v1 there was a file for this, but in v2 where can I do it? 
I need this to be able to use https protocol. 
Thanks for the answers!

**Comment by TobyMosque** [comment]
You can use SSR Middlewarre to add behaviors or configure the express instance:
https://quasar.dev/quasar-cli/developing-ssr/ssr-middleware

my advice, u would use PM2 or Docker to run your app, so enable HSTS in your reverse proxy (nginx, traefik, etc)
Anyway, that isn't an issue, so u're welcome to open a discussion if u had additional questions.

**Comment by rstoenescu** [comment]
Like mentioned above, use nginx (etc) to redirect to your app's internal port.
This should not be handled by Quasar itself as it would limit its usage opportunities (or add unnecessary overhead).
