### ISSUE TITLE
Vite plugin code generator generates invalid import path for roboto font

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#11129]
Specifically, when roboto is selected the generated code looks like this:
```js
import '@quasar/extras/roboto/roboto.css'
```
But the file is actually located at
```js
import '@quasar/extras/roboto-font/roboto-font.css'
```
Drafting a pr now on the assumption that only the VitePluginUsage component needs to be fixed to remedy this

**Comment by rstoenescu** [comment]
Thanks for PRing! This will be available on next docs deployment.
