### ISSUE TITLE
Idea, q-select: Element q-select doesn't have required attribute model-value 

### ISSUE THREAD

**Issue by 209** [quasarframework/quasar#11122]
**Describe the bug**
`<q-select v-model="item" :options="items" />`
IDEA warning: Element q-select doesn't have required attribute model-value 

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/aeLkjyf2/3/

**To Reproduce**
1. add q-select
2. ... 

**Expected behavior**

**Screenshots**
<img width="865" alt="Снимок экрана 2021-10-27 в 00 19 58" src="https://user-images.githubusercontent.com/4629854/138962640-bdb35e92-25ee-4032-b729-b90c614bc899.png">

**Platform (please complete the following information):**
Quasar Version: 2.2.0
@quasar/app Version: 3.1.6

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macos
Node: v14.18.1
NPM: 8.1.0
Yarn: 1.22.17

**Comment by hawkeye64** [comment]
Do you have the Vue plug-in installed and does it support Vue 3?

**Comment by 209** [comment]
Installed, partially supported.
There are no other problems with vue3 support.

Maybe this is a question for ts
```
export interface QSelectProps {
  ...
  modelValue: number | string | any[] | null | undefined;
```

> Model of the component; Must be Array if using 'multiple' prop; Either use this property (along with a listener for 'update:modelValue' event) OR use v-model directive

**Comment by hawkeye64** [comment]
It really seems like an issue for IDEA. Although `model-value` is required, it's not recognizing it as being used via `v-model`. I am wondering if you removed the v-model and did the manual way if it'd work. If so, then this is really an issue for the IDEA people.

**Comment by 209** [comment]
Ok, thanks.
