### ISSUE TITLE
i18n difference migration guide and generated code

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#11130]
The docs here https://quasar.dev/start/upgrade-guide#vue-i18n-v9 show a different content then what `quasar create` generates on an empty project. Why is it different? What is correct? I'm right in a migration Qv1 -> Qv2 and have problems with i18n. 

Docs:
![image](https://user-images.githubusercontent.com/9776384/139095711-0ef57aa6-2706-415c-b36e-a1ec8ebb5694.png)

Generated code: 
![image](https://user-images.githubusercontent.com/9776384/139095769-a522cfeb-6d7d-4d0f-8f76-9020a04d4e76.png)

Expected result: 
docs match generated code

**Comment by rstoenescu** [comment]
Both forms are correct if you're not developing with SSR.
If on SSR, then moving everything under the default export is correct.
