### ISSUE TITLE
[Request] Export mixins

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1113]
Hi,

I tried importing mixins : 
```javscript
import { FrameMixin, InputMixin, ... } from 'quasar';
```
But without success. Looking at `quasar/src/index.*.js` I did not see any mixins export. Is it right ?

It would be convenient to export them [mixins](https://github.com/quasarframework/quasar/tree/dev/src/mixins) or some of them at least. 

I need to override the behavior of the QInputChips and I was expecting copy source code from [QChipsInput.vue](https://github.com/quasarframework/quasar/blob/dev/src/components/chips-input/QChipsInput.vue), rework it for my needs.

FrameMixin adn InputMixin bring many usefull base behavior that I would avoid to re-implement.

One of the main concern I have with the **QChipsInput** is that we can't set its value like the other components (Option, Select, et...). Ex : 
```javascript
[
  { label : "foo", value="2" },
  { label : "fuu", value="3" },
 ... 
]
```

I want to build a path selector using a PopupOver. Each time the user select an entries, the available entries in the PopupOver changes according the depth position we are in the path. But is it possible that path may contains same string. Ex

![image](https://user-images.githubusercontent.com/7946730/32676316-316651a8-c628-11e7-848d-896582187926.png)

Now, what happel if I click on the **X** of the first **A** chips to close it ?
```jsx
<q-chips-input @change="change" .../>
```
```javascript
  methods: {
    change(newValue) {
      // newValue will contains `A`, but which A ??? The first one or the last one ?
    },
    ...
```

Best regards,

**Comment by MatanYed** [comment]
+1
Me too need that for the same reason (chips with autocomplete)

**Comment by rstoenescu** [comment]
In v0.15 the /src folder will be in the NPM package, so closing this.
