### ISSUE TITLE
Error / compilation failure using the 'loading' plugin with Quasar CLI

### ISSUE THREAD

**Issue by roberttolton** [quasarframework/quasar#11131]
**Describe the bug**
Adding the 'loading' plugin to a new Quasar v2 CLI Vue3 TypeScript project causes the following error:

```
 App •  ERROR  •  UI  in ./.quasar/quasar-user-options.js

Error: loading

  - import-transformation.js:6 module.exports
    [dealer-portal]/[quasar]/dist/transforms/import-transformation.js:6:11

  - loader.js.transform-quasar-imports.js:14
    [dealer-portal]/[@quasar]/app/lib/webpack/loader.js.transform-quasar-imports    .js:14:78

  - Array.map

  - loader.js.transform-quasar-imports.js:10
    [dealer-portal]/[@quasar]/app/lib/webpack/loader.js.transform-quasar-imports    .js:10:8

  - String.replace

  - loader.js.transform-quasar-imports.js:7 Object.module.exports
    [dealer-portal]/[@quasar]/app/lib/webpack/loader.js.transform-quasar-imports    .js:7:30



 App •  COMPILATION FAILED  • Please check the log above for details.
```

This is all the information that the error displays, so I'm not sure exactly what it's having trouble with.

The `quasar-user-options` file contains:

```
import {loading} from 'quasar'
export default { config: {"loading":{}},plugins: {loading} }
```

**To Reproduce**
1. Create a new Quasar CLI Vue3 TypeScript project
2. Add 'loading' plugin and empty/default loading config object as per docs
3. Run `dev` command and see error

**Expected behavior**
Plugin to work as expected and outlined in docs.

**Platform (please complete the following information):**
Quasar Version: v2
@quasar/app Version: `3.1.5`

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS 11.6
Node: 16.4
NPM: 7.18.1
Browsers: Chrome 94

**Comment by pdanpdan** [comment]
Uppercase L

**Comment by roberttolton** [comment]
![Facepalm](https://c.tenor.com/IErgRzEXuJQAAAAd/why-me-facepalm.gif)
