### ISSUE TITLE
QTime logs unwanted data to the console

### ISSUE THREAD

**Issue by jop-io** [quasarframework/quasar#11144]
**Describe the bug**
When using the q-time component and a time has been selected, the data model is being logged in the console. It looks like @rstoenescu added this by mistake in his last commit.

**To Reproduce**
1. Go to https://github.com/quasarframework/quasar/commit/950355bdcb36afd5741a6e7d5b1b860c047969fe#diff-033e2e5186c84b37e3a65086628948dd110dbec4665652ed43828c4bf7003e47
2. Look at line `291`

**Expected behavior**
Arbitrary data (non info/errors/warnings) should not be logged.

**Platform (please complete the following information):**
Quasar Version: 2.2.1
@quasar/app Version: 3.1.7

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.2.2
