### ISSUE TITLE
No tooltip on hover disabled button (chrome)

### ISSUE THREAD

**Issue by martijn788** [quasarframework/quasar#11146]
**Describe the bug**
When a button is disabled the tooltip is shown in firefox, but not shown in chrome.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/martijn788/pen/WNEOYRQ

**To Reproduce**
1. create q-btn with a tooltip and disable it.
2. hover in firefox and see the tooltip
3. hover in chrome and don't see the tooltip

**Expected behavior**
I expect a hover in both browsers. 

**Platform (please complete the following information):**
Quasar Version: 2.X

Quasar mode:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Browsers: Chrome and Firefox

**Comment by pdanpdan** [comment]
https://github.com/quasarframework/quasar/issues?q=is%3Aissue+disable+tooltip
