### ISSUE TITLE
Replace chunkhash with contenthash for better SRI support

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#11154]
Currently, chunk filenames are generated using `chunkhash`, which does the job, however, it is not as stable as `contenthash`. In other words, the content may change (and thus the [Subresource Integrity Hash](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)), while the filename would remain unchanged.

https://github.com/quasarframework/quasar/blob/9bb21ec99408b8f234720a80a077b432e85c4e3b/app/lib/webpack/create-chain.js#L45-L46

https://github.com/quasarframework/quasar/blob/9bb21ec99408b8f234720a80a077b432e85c4e3b/app/lib/webpack/create-chain.js#L65-L66

See [webpack-subresource-integrity's README](https://github.com/waysact/webpack-subresource-integrity/blob/61cca0722271061fb62ce1120a6442d1a8bf2caa/webpack-subresource-integrity/README.md#caching).

I can submit a PR if you agree with this change.

**Comment by rstoenescu** [comment]
Hi,

The key point is the build speed. The current config does the job already (so a code change doesn't actually fixes anything) and is way faster than `contenthash`.

However, for someone wanting to change the current behavior, there's the extendWebpack/chainWebpack methods in quasar.conf.js which can tamper with the underlying Webpack config.
