### ISSUE TITLE
q-select in iOS 15.1 dark mode not working good

### ISSUE THREAD

**Issue by GHChrisSu** [quasarframework/quasar#11167]
**Describe the bug**
q-select in iOS 15.1 dark mode is showing a white background cause the white words can not see in q-select input area.

**To Reproduce**
1. Use iOS 15.1 and set it to dark mode
2. Use q-select which can input 
3. See error

**Expected behavior**
Black background

**Screenshots**
![IMG_DF38B70011F4-1](https://user-images.githubusercontent.com/13779988/139561680-d77ac5e0-850c-459e-933b-eda26bce6584.jpeg)

**Platform (please complete the following information):**
Quasar Version: v2.2.1
@quasar/app Version: v3.1.7

Quasar mode:
  - Capacitor

Tested on:
  - Capacitor

OS: Mac Big Sur 11.6
Node: 14.17
NPM: 6.14.13
iOS: iOS 15.1

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.2.3.
