### ISSUE TITLE
q-date in q-input not working with SVG icon

### ISSUE THREAD

**Issue by Nincha** [quasarframework/quasar#11164]
**Describe the bug**
When using an example from the documentation, I just noticed that the q-date component used along with q-input ( https://quasar.dev/vue-components/date#with-qinput ) seems to have an issue with SVG icons :  when you replace for example name="event" with :name="myIcon" the q-popup containing the date picker isn't opened on click anymore. Is it expected behaviour, and/or is there a workaround?

**Codepen/jsFiddle/Codesandbox (required)**
Sorry I'm not familiar enough with those tools to know how to provide an example with imported SVG icons, but I feel reproduction is very easy for that one. 😄 

**To Reproduce**
1. Use the example from https://quasar.dev/vue-components/date#with-qinput 
2. Change `<q-icon name="event" class="cursor-pointer">` to `<q-icon :name="mySvgIcon" class="cursor-pointer">`

**Expected behavior**
The q-date component should appear on click on the mySvgIcon SVG icon.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.2.2
@quasar/app Version: 3.1.8

Quasar mode:
  - [*] SPA
  - [*] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [*] SPA
  - [*] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows
Node: 12.22.1
NPM: 6.14.12
Yarn: 1.21.1
Browsers: Chrome latest
iOS: Chrome latest
Android: Chrome latest
Electron: not tested

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

When using svg or image icons, it's required to use a wrapper div element in your case. No other way around it due to the HTML syntax hindering children nodes on certain elements (which happen to be the ones used by svg and img).

```
<template v-slot:append>
  <div>
    <q-icon ... />
    <q-popup-proxy ...>
      <q-date ... />
    </q-popup-proxy>
  </div>
</template>
```
