### ISSUE TITLE
q-table horizontal scroll no longer working when in q-scroll-area

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#11175]
I have a large component with several areas separated by expansion-items (which do not operate as accordion).
The page can be in a splitter panel so the width can be adjusted by the user and everything is designed to be responsive to page width.
Most of the page, except a top toolbar, lives in a q-scroll-area to provide vertical scrolling.
One of the expansion items contains a q-table which has many columns.
Everything on the page is responsive, so I don't ever want a horizontal scrollbar for the whole page.
But the table may be too wide if user narrows the splitter, so the table needs its own scrollbar (with sticky-header-column).
Prior to upgrading, this worked fine. If the page width was too narrow to show all columns, the table showed a horizontal scrollbar.
Now when the expansion item containing the table is opened, the entire page width expands and shows a scrollbar for the whole page, so none of the other areas fit within the page anymore.

Tried to make a codeSandbox but keep getting stupid linting errors. But just this code shows the problem...
```
<template>
  <div class="column full-height full-width no-wrap overflow-hidden>
    // Toolbar goes here
    <q-scroll-area class="full-height">
      <q-table
        style="max-width: 80rem"
        class="sticky-header-column full-height non-selectable q-mx-auto"
        :rows="rows"
        :columns="columns"
      />
    </q-scroll-area>
  </div>
</template>
```
       
With the scroll-area, we get a horizontal scrollbar for the whole page. If you comment out the scroll-area, the table shows a horizontal scrollbar.

Screenshots:
Without scroll-area...
![withoutScrollArea](https://user-images.githubusercontent.com/45148066/139592658-b74ef775-4155-49ff-a28e-10a95ab7f31a.png)

With scroll-area - q-table no longer scrolls:
![withScrollArea](https://user-images.githubusercontent.com/45148066/139592684-625e6be3-6f32-4993-8e62-5b0a9c069741.png)

So something has changed. I this is not a bug, I'd appreciate some guidance to get back my previous behaviour. Thanks.

Quasar Version:
@quasar/app Version:

Quasar mode:
  - [X ] SPA

Tested on:
  - [ X] SPA

OS: Windows
Browsers: Chrome
Quasar 2,2,1
quasar/app: 3.1.7

**Comment by pdanpdan** [comment]
Please make a codepen to show the problem

**Comment by CrawfordW** [comment]
Sorry, I don't know how to build a Quasar codepen. I tried to make a codesandbox but it keeps showing stupid linting errors for legitimate code and won't run correctly. For some reason it doesn't like the line :rows="rows" so the table doesn't show.
You can see it here...
https://codesandbox.io/s/quasar-table-scroll-problem-e36ee

**Comment by hawkeye64** [comment]
@CrawfordW go to any example in docs that is close to what you want and click the CodePen link. It'll build you a CodePen. Then modify the code to create your example. Bear in mind, you can't use self-closing tags on CodePen. 

Also, have you checked the width/height of your QScrollArea in dev tools?

**Comment by CrawfordW** [comment]
Thanks for the codepen tip. Looks like I'll have to learn composition API in order to integrate my code into the Quasar template (I've been avoiding this!).
My scroll-area has class="full-height" and lives in a column with class="full-height full-width". Always worked before.
I need this because the page is loaded into a splitter pane (either horizontal or vertical) so needs to adapt.

**Comment by hawkeye64** [comment]
`full-height` is just `height: 100%`, but even in regular CSS that doesn't work unless the parent has a fixed height.

**Comment by CrawfordW** [comment]
Tried to make a codepen at https://codepen.io/crawfordw/pen/xxLywmW?editors=1111
but the table's not showing for some reason.
Because any page can be in a horizontal splitter, I need scroll-area to handle that. Up until recently it's been working perfectly on many pages I've built.

**Comment by CrawfordW** [comment]
To show what I need, you can see my prototype app built with Q1 at https://www.soapmaker.ca/SM4proto
1. Log in with your own email and password 'earlyTester21'
2. Click the 'Recipes' icon on the left vertical toolbar
3. Expand Solid Soap/ Soap bases and right-click 'Soy Base'. Choose 'Edit recipe content...'
4. Click OK and then expand the Ingredients expansion item to see the table.
5. On the top toolbar, click the 'Split Across' button.
6. Now when you move the splitter, the table horizontal scroll bar works, and other areas just adapt to the width.
Since upgrading to Q2, this no longer works. Now when the table is visible, the entire page gets a horizontal scrollbar!

**Comment by pdanpdan** [comment]
Yes, in all Qv2 and the recent Qv1 the QScrollArea can work both horizontally and vertically.
If you don't want to have horizontal scroll you should get the (left side) size from the splitter and apply a max-width style on the table so that id does not extend more than you want.

**Comment by CrawfordW** [comment]
Dan, OK I understand. But can I request a feature?
If QScrollArea had an option to only scroll vertically, it would work as before and save a lot of fiddling. Getting a splitter pane width and then passing it down through a tabstrip component to a page on a tab seems like it should be unnecessary.
Thanks for listening, and for your continued support!

**Comment by pdanpdan** [comment]
You can put full-width class or width 100% on the content like in the example and have no horizontal scroll
https://github.com/quasarframework/quasar/issues/10639#issuecomment-1007990576

**Comment by CrawfordW** [comment]
Dan, I've tried to make a codepen to show my issue, but it's not showing the table for some reason. Probably because I don't really grok composition API. Anyway here's the link if you feel up to having a look...
https://codepen.io/crawfordw/pen/Exweyxd

**Comment by pdanpdan** [comment]
You cannot use self closing tags in codepen :)
And you messed up the indenting
https://codepen.io/pdanpdan/pen/dyVqXEX?editors=1000

**Comment by CrawfordW** [comment]
Oh sorry I forgot that limitation of codepen.
OK, so it's working now and shows the table. As you can see, the section above the table but within the scroll area needs to scroll vertically, but NOT horizontally because it's responsive.
Only the table content should scroll horizontally. This used to work in version 1, but now the table forces the entire scroll area to be wider than the window width.
Can you suggest a way to do this?

**Comment by pdanpdan** [comment]
Something like this https://codepen.io/pdanpdan/pen/dyVqXEX?editors=1010
See the class on QScrollArea and the definition in CSS section

**Comment by pdanpdan** [comment]
Something like this https://codepen.io/pdanpdan/pen/dyVqXEX?editors=1010
See the class on QScrollArea and the definition in CSS section

**Comment by pdanpdan** [comment]
Something like this https://codepen.io/pdanpdan/pen/dyVqXEX?editors=1010
See the class on QScrollArea and the definition in CSS section

**Comment by CrawfordW** [comment]
It works! Dan you are my hero!

**Comment by CrawfordW** [comment]
Dan, it works great in the codepen, but when I added it to my app, I still have the problem. I wonder if it has something to do with structures that contain the page... in my app, each splitter pane contains a tab-strip and tab-panels. So I tried to add a containing tab-panel to our codepen, but now nothing shows in the right splitter pane so I can't experiment further. 
If you have time, could you have a look? Here's the modified codepen...
https://codepen.io/crawfordw/pen/OJxoxdV?editors=1111
