### ISSUE TITLE
add directives issue

### ISSUE THREAD

**Issue by ibrahim-developper** [quasarframework/quasar#11187]
**Describe the bug**
i want to add directive when scroll the page to do some animation.

So my app use i18n and have i18n file in the boot folder i add my directive in this file

![i18n](https://user-images.githubusercontent.com/52491316/139920512-598c3454-9c1b-4e38-986d-b65ea89d6eec.png)

**and my directive file is** 
--------------------------------
![intersect](https://user-images.githubusercontent.com/52491316/139920479-876ffb15-fd00-41cc-b0a4-11c5e7c9f68f.png)

and last thing i put my directive to this h3 ( i try this also to other elements but not work)

`<h3 v-scrollanimation data-text="Popular Products">Popular Products</h3>`

**Expected behavior**
minimum this  console.log("register el",el) should see in the console bot nothing happen 

**Platform (please complete the following information):**
Quasar Version: 2.2.2
@quasar/app Version: 3.1.8

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Hello. Please use discussions or discord for help requests. And try to format the code so that it can be read.

**Comment by rstoenescu** [comment]
@ibrahim-developper 

There is no "bind" method for Vue 3 directives... That is Vue 2 syntax.
Please check the Vue 3 docs: https://v3.vuejs.org/guide/custom-directive.html#intro

**Comment by ibrahim-developper** [comment]
> @ibrahim-developper
> 
> There is no "bind" method for Vue 3 directives... That is Vue 2 syntax. Please check the Vue 3 docs: https://v3.vuejs.org/guide/custom-directive.html#intro

Thank you alot ♥️
