### ISSUE TITLE
Turn Quasar documents into i18n mode

### ISSUE THREAD

**Issue by fjxhkj** [quasarframework/quasar#11183]
Can you convert the documents of Quasar to i18n multinational language mode to other languages involved in translation?

**Comment by rstoenescu** [comment]
Hi,

This will be the last time that I explain this. Did it too many times already.
It's easy to add i18n to the docs. What is really hard is to keep it up to date. And take the Quasar language pack files for example.. it's already hard to contact the initial submitters for making a few simple changes. And Quasar language packs are simple json files with a few entries. Now put that against the tons and tons of complex pages in docs that need to get updated (and quite frequently). What I personally hate is for the official docs to get out of date with non-English languages and misleading/confusing the readers on why "X does not works this way". And by looking at the Quasar language pack files then we'd definitely head into confusing everyone. And that's even worse than not having the docs in a non-English language. Not saying it's a good alternative but nowadays Google Translate is even embedded into Chrome and can translate the pages on the fly. Then one more thing is that we'd have to wait for translations to all the supported languages before releasing any new features -- which can take quite a while and we can't force anyone to help us asap.
