### ISSUE TITLE
The update:model-value event of q-check-box can not be triggered when v-model changed

### ISSUE THREAD

**Issue by zouyaoji** [quasarframework/quasar#11196]
**Describe the bug**
The update:model-value event of q-check-box can not be triggered when v-model changed. But it can be triggered by clicking.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/zouyaoji/pen/xxLpZqp?editors=101

**To Reproduce**
1. Go to https://codepen.io/zouyaoji/pen/xxLpZqp?editors=101
2. Open the browser console.
3. See error

```
// Can not trigger this callback
const updated = (e) => {
   console.log(e)
}
```

**Expected behavior**
The update:model-value event of q-check-box can be triggered when v-model changed. 

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

> OS: Windows 10 Node: 14 NPM: 7 Browsers: Chrome and Firefox latest

**Comment by pdanpdan** [comment]
Hello. You are changing the model from outside.

**Comment by zouyaoji** [comment]
However, changing the model from outside can change the check state of the checkbox, but the change event is not triggered.

**Comment by MilosPaunovic** [comment]
If you pass both value and event to the handler (as it is shown in the docs), everything works as it's supposed to.
https://codepen.io/milospaunovic/pen/dyzJGKQ?editors=1011

![Screenshot 2021-11-03 at 09 08 12](https://user-images.githubusercontent.com/62475782/140026979-b2e13648-aa35-457e-a561-bded8e8bf15e.png)

**Comment by zouyaoji** [comment]
Thank you, I've now understood.

**Comment by ryhn** [comment]
@MilosPaunovic , it does not work in your example. Event not firing.

**Comment by MilosPaunovic** [comment]
Create a reproduction.

**Comment by ryhn** [comment]
Actually title explain the issue

`update:model-value event of q-check-box can not be triggered when v-model changed`

Here is example;

https://codepen.io/milospaunovic/pen/dyzJGKQ?editors=1011

I did not see console.log(v) result in console did you see ?

**Comment by pdanpdan** [comment]
read first comment
you are changing the model - should we tell you you told us to change the value?

**Comment by ryhn** [comment]
@pdanpdan, I expect model changes from outside or inside trigger the event.  This logic seems a bit strange to me.  I found other solution with custom getters.  But it would be great just simple this.model = true/false trigger the event

```
<template>
  <div class="hello">
   <input type="checkbox" v-model="customProperty" v-on:update:modelValue="updated" />
    <button @click="box=!box">Toggle</button>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  props: {
    msg: String,
  },
  data(){
    return {
      box:false
    }
  },
  computed: {
      customProperty: {
        get() {
          console.log(this.box);
         // run function here
          return this.box;
        },
        set(v) {
          this.box = v;
        },
      }
    },
  methods:{
    updated(v){
      console.log("updated");
    }
  }
};
</script>



``` 

Not : I am using vue3 with Options Api.

**Comment by pdanpdan** [comment]
Update events are used to notify parent that a model change is required from the child. In your case the model in the parent is already changed and the child just renders the value.
You can use watch in the parent if you want to be notified on model change

**Comment by ryhn** [comment]
> You can use watch in the parent if you want to be notified on model change
I know that.  

Actually i didn't need this before so i thought the model change would work. Anyway thanks.
