### ISSUE TITLE
[Request] Vertical orientation for Slider and Range components

### ISSUE THREAD

**Issue by skmbr** [quasarframework/quasar#1119]
It would be great if the slider/range component could also work vertically.

Ideally, an orientation prop could be set to horizontal or vertical, with horizontal obviously being the default.

**Comment by rstoenescu** [comment]
Hi. Will do. I think there is another request related to this, but don't have time now for it.
In any case, this will be implemented. Thanks.

**Comment by skmbr** [comment]
Great, thanks!  

I've also just come across a case where I need a horizontal slider to be reversed, ie. from the max value on the left to the min value on the right.

Would this be related to this or should I raise as a separate feature request?

**Comment by rstoenescu** [comment]
This ticket is enough. Thanks for the proposal!

**Comment by CelticParser** [comment]
Sorry, I don't see this in the docs - nor in v1.0.  can you lead the way?  Thnx

**Comment by pdanpdan** [comment]
Closing this one to follow in #5691

**Comment by Robula** [comment]
@pdanpdan Why are you closing this? #5691 doesn't mention anything about vertical sliders.

**Comment by pdanpdan** [comment]
The initial idea was to follow in one issue only, but because only the horizontal orientation was solved Razvan reopened it. All looks good.

**Comment by Robula** [comment]
Okay thanks! This has a milestone of 1.0 which was closed on 30th August, will this issue be rescheduled?

**Comment by Robula** [comment]
@pdanpdan How would I go about implementing this myself? I have tried CSS transforms but of course that causes the element to ignore DOM layout rules. Thanks :)

**Comment by pdanpdan** [comment]
Hi. We'll look into this but for the moment it is low priority - I'll update this issue when we get to this.
Simple CSS transforms would not work, it needs a deeper refactoring.

**Comment by Asthonishia** [comment]
Any idea of a release date ?

**Comment by rstoenescu** [comment]
Will be available in "quasar" v1.10.0
