### ISSUE TITLE
confirm directive

### ISSUE THREAD

**Issue by xlaussel** [quasarframework/quasar#11208]
Hello again and thanks again for this incredible framework!

I have a suggestion: A q-confirm directive intercepting the events (click most of the time) and opening a dialog asking for confirmation. On confirmation the event is triggered.

The basic parameters would be just the text confirmation and the dialog would be opened with default values.
For more complicated cases it would be the same object thant the $q.dialog parameter (props) function:

v-q-confirm="Do you really want to delete this item??"
v-q-confirm="{title:'Confirm the submission of this dangerous form?',message:'Do you really want?'}"

Also a boolean activating/desactivating the confirmation prompt is usefull.

The modifiers of the directive can be the event type. For exempe:
v-q-confirm.click="Do you really want to delete this important item??"
or maybe also the position
v-q-confirm.submit.top="Submit that form??"

Very usefull and time saving !!

I already did it for another framework but only for native events, I can share the code. I don't know if it is possible with custom vue events but I can have a look

**Comment by rstoenescu** [comment]
You mean Dialog plugin's first example: https://quasar.dev/quasar-plugins/dialog#example--basic
