### ISSUE TITLE
tooltip directive

### ISSUE THREAD

**Issue by xlaussel** [quasarframework/quasar#11207]
Hello and thanks for this wonderfull framework: It is nice, well designed, up to date (vue3!!). Definitevely the best!

I have a suggestion about tooltips:
Why not creating a directive (v-q-tooltip maybe :-) )? The parameters could be

- a string (the text) for the common use
- or an object with the actual QTooltip props for more complicated cases

And with modifiers for the position maybe?

It would be easier and quicker than instancianting a q-tooltip component, especially for the common case where we just want to display an help text. Just adding a v-q-tootlip="my help text" would be nice!

**Comment by hawkeye64** [comment]
What about styling the tooltip? This could get messy.

**Comment by xlaussel** [comment]
> What about styling the tooltip? This could get messy.

The directive would accept an object with the actual QTooltip props. Yes it can be messy but most of the time people doesn't want to style the tooltip, they just want to display a simple message and in this case v-q-tooltip="My message" is very easy and clear.

But it could be interesting also to set some global tooltip styling options elsewhere

And if

**Comment by rstoenescu** [comment]
Directives are not that efficient perf-wise. Especially if you supply an Object as param.
It makes no sense to add the same functionality as the QTooltip already offers. It's not more performant and it definitely isn't easier to type (as in "less characters"). Then comes the problem of a directive applied to a component -- now what DOM node you actually want it to be applied to? Components can render into very complex DOM structures.
