### ISSUE TITLE
screen plugin

### ISSUE THREAD

**Issue by amirsafaricg** [quasarframework/quasar#11209]
Hello 
screen plugin breakpoints are not changing with setscreen function 

please fix it 
thanks

**Comment by amirsafaricg** [comment]
even the real screen width differs from real screen width 

i guess the whole screen plugin needs to get fixed not just set size

**Comment by MilosPaunovic** [comment]
I could not reproduce the problem with `Quasar@1.16.0`.
Please provide a Codepen reproduction of the exact problem so it can be fixed easier.

**Comment by pdanpdan** [comment]
it's setSizes

**Comment by amirsafaricg** [comment]
> it's setSizes

Im wrote my issue here not code

**Comment by rstoenescu** [comment]
Please provide a codepen or codesandbox to understand your issue. Otherwise there is nothing actionable here.
