### ISSUE TITLE
value prop on input doesn't work.

### ISSUE THREAD

**Issue by KiwiVFX** [quasarframework/quasar#11212]
**Describe the bug**
Hello, I'm using quasar from version 1 till today.
I've Started a clean project with latest versions, tried to create setter and getter for v-for loop, for children. Couldn't pass index so i went for :value to set default value for the field. I tried non dynamic as well and it doesn't work. Looking on my previous projects in which that was the way to set the value.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/KiwiVFX/pen/zYdpgyP

**To Reproduce**
1. Add value or :value prop to input. works.
2. Add value or :value prop to q-input. doesn't work.

**Expected behavior**
Add value or :value prop to input should work.
**Platform (please complete the following information):**
Quasar Version:
 » Dev mode.......... spa
 » Pkg quasar........ v2.1.5
 » Pkg @quasar/app... v3.1.5
 » Transpiled JS..... yes (Babel)

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by pdanpdan** [comment]
Please check migration guide and vue upgrade guide from vue2 to vue3.
https://v3.vuejs.org/guide/migration/v-model.html#overview
