### ISSUE TITLE
Plotly.js is not working with Quasar

### ISSUE THREAD

**Issue by kostyfisik** [quasarframework/quasar#11229]
### Discussed in https://github.com/quasarframework/quasar/discussions/11133

<div type='discussions-op-text'>

<sup>Originally posted by **kostyfisik** October 27, 2021</sup>
Hi! First of all, I would like to thank for Quasar - a real software masterpiece! Next, I am quite new to Quasar, Typescript, and Vuex, however, I had decided to move my project from vue2 to vue3 with all these technologies improvements. 

The problem I failed to solve is to use plotting library plotly.js. I have created a minimal *.vue component

```vue
<template>
  <div id="plotly_chart" />
</template>

<script lang="ts">
import { newPlot } from 'plotly.js'

import {
  defineComponent,
  onMounted,
} from 'vue'

export default defineComponent({
  name: 'ReactiveChart',
  setup() {
    onMounted( async () => {
      await newPlot('plotly_chart', [{
        x: [1,2,3,4],
        y: [3,1,4,1]
      }])
    })
  }
})
</script>
```
If I create a basic VueCli project (with TypeScript and Vue3), it just works. I just need to install the dependencies:
```bash
npm i plotly.js
npm i -D @types/plotly.js
```
The result looks like this:

![Screenshot from 2021-10-27 22-42-50](https://user-images.githubusercontent.com/5239997/139135749-e3609059-6740-4ea1-92ee-d5994044d42e.png)

So, it creates a predefined plot, well done. Now, I use Quasar CLI with similar settings (TypeScript, Vuex) and replace example component on `Index.vue` page with my one. However, the mentioned dependencies above for some reason is not enough, `quasar dev` shows me an error:

![Screenshot from 2021-10-27 22-25-28](https://user-images.githubusercontent.com/5239997/139136410-c2fb84b7-5fc9-465d-8f96-22537e5c2149.png)

For some reason, it requires new dependencies... Well, looks strange, but not fatal. So I `npm i assert stream`.... As a result, `quasar dev` starts without any issues... just to end with a blank screen and errors in web console:

![Screenshot from 2021-10-27 22-27-50](https://user-images.githubusercontent.com/5239997/139136971-373e598f-f03f-44cf-a743-6768a4e980be.png)

Any ideas, how I can fix this, or in which direction I should move next to get the solution?

</div>

**Comment by rstoenescu** [comment]
`stream`, `assert` etc are Nodejs native. DON'T npm install the equivalent packages.
In any case, if Plotly is a client-side lib then why does it imports Nodejs stuff?

## Extract from docs:

Webpack v5 removed the Nodejs polyfills for the web client builds. If you are using packages for the web client that rely on Nodejs API (they shouldn't!), you will get errors saying that some packages are missing. Examples: `Buffer`, `crypto`, `os`, `path`.

These need to be addressed by the package owners. But if you don't want to wait and just want to run your app/website (with a bit of risk), then you can manually install [node-polyfill-webpack-plugin](https://www.npmjs.com/package/node-polyfill-webpack-plugin) (`yarn add --dev node-polyfill-webpack-plugin`) then reference it in quasar.conf.js > build > chainWebpack. Example:

```
// quasar.conf.js
build: {
  chainWebpack (chain) {
    const nodePolyfillWebpackPlugin = require('node-polyfill-webpack-plugin')
    chain.plugin('node-polyfill').use(nodePolyfillWebpackPlugin)
  }
}
```

**Comment by kostyfisik** [comment]
@rstoenescu  Thank you a lot, work fine with polyfill plugin now! 

I will move your answer to docs where I missed it, I hope you don't mind.

![Screenshot from 2021-11-09 14-29-44](https://user-images.githubusercontent.com/5239997/140916388-e6de92f7-120b-4394-b33b-377b22468c9a.png)

**Comment by rstoenescu** [comment]
Not at all. Thanks for the PR!

**Comment by kostyfisik** [comment]
For future reference: the solution is now described in the documentation https://quasar.dev/quasar-cli/handling-webpack#webpack-v5-compatibility-issues
