### ISSUE TITLE
qtooltip in qtab: setting class attribute has no effect

### ISSUE THREAD

**Issue by flowt-au** [quasarframework/quasar#11225]
**Describe the bug**
When using a tooltip within a qtab, setting the class has no effect.

**Codepen**
https://codepen.io/flowt-au/pen/mdMxeGw

**Expected behavior**
In the codepen I would expect the background color to be red.

**Platform (please complete the following information):**
Quasar Version: Latest: Codepen from Quasar docs
Chrome and Firefox.

Given that the `:offset` binding works I also tried a `:class` binding but still no go.
Thanks.

**Comment by rstoenescu** [comment]
Hi,

It's "content-class" instead of "class" for Quasar v1.

**Comment by flowt-au** [comment]
Oh... so sorry... I missed that difference in versions. All working correctly now. :-)
Thanks so much.
Murray
