### ISSUE TITLE
After npm run build:ssr deploys the ssr directory, the file core.xxx will be automatically produced every day.

### ISSUE THREAD

**Issue by daxiongYang** [quasarframework/quasar#11221]
Please tell me what is causing this?
![QQ20211105-103901](https://user-images.githubusercontent.com/29277125/140449561-77a691fc-069f-4a36-be05-67bf7cbd2ca2.png)

**Comment by pdanpdan** [comment]
Hello. Please use discussions here or discord channel for help requests.

**Comment by rstoenescu** [comment]
It may be a coredump. Something is crashing the server side. You can check the server logs (assuming you have them enabled on your deployment environment) to see what's going on.

**Comment by daxiongYang** [comment]
@rstoenescu Thank you very much for your hint, the problem has been solved.
After that, I will go to discussions to discuss any questions.
