### ISSUE TITLE
[Feature Request] Input built-in validation

### ISSUE THREAD

**Issue by nueko** [quasarframework/quasar#1123]
Halo, 
How about adding built-in basic validation to the q-input or q-field
something like
```pug
q-input(:errors="[Boolean(name) || 'name is required', name.length >= 2 || 'minimal 2 chars']", v-model="name")
q-input(:warnings="[name.length > 1000 || 'too many chars']", v-model="name")
```

**Comment by vuchl** [comment]
This is pretty easily solvable via comoputed properties or a 3rd party library allready.

**Comment by nueko** [comment]
@vuchl yes that is.
we can use vee-validate or vuelidate. But it will be nice if we have the simple one built-in

**Comment by rstoenescu** [comment]
@nueko It's not a bad idea. However reinventing the wheel here adds no value. If Quasar has something simple, devs will jump asking for more and more features (like it happened with Dialog) -- and we'll end up duplicating packages like vuelidate. Vuelidate is simply easy and great and the devs are going into the right direction with it, so I strongly recommend this package.
