### ISSUE TITLE
SSR + serverless infrastructure

### ISSUE THREAD

**Issue by Seanitzel** [quasarframework/quasar#11231]
**Problem**
Currently there is no way to export the handler when building a V2 SSR app.
The only way to make it happen is to literally edit the generated index.js file.

**Describe the solution you'd like**

A way to define exactly what will be exported from the SSR app built.

**Describe alternatives you've considered**
From reading the docs i understand that the only thing we can do at the moment is the different options that exist in Quasar.conf. None of them offer that.

**Additional context**
There is more information here:
 https://github.com/l1qu1d/quasar-v2-ssr-firebase 

My goal was to deploy the app to firebase cloud functions, and it doesn't work with the way the build is created at the moment.

**Comment by rstoenescu** [comment]
Will be available through "@quasar/app" v3.2.0.
Haven't written the docs yet (todo tomorrow), but will tag this ticket when I do.

**Comment by rstoenescu** [comment]
@Seanitzel Will you be around tomorrow (Tuesday) to help me with some tests before I release the new q/app version? Would like to be 110% sure everything will work as smooth as possible. Can we connect through Discord to speed things up?

**Comment by Seanitzel** [comment]
To be honest tomorrow is the worst day possible for that since i'm having a surgery 😅😂

But I still might be able to, i'll hit you up on discord when i'll be back

And thanks for addressing this issue so quickly!

**Comment by rstoenescu** [comment]
Hope all goes well!! Don't worry about me.
