### ISSUE TITLE
Material icons are out-dated

### ISSUE THREAD

**Issue by melroy89** [quasarframework/quasar#11234]
**Is your feature request related to a problem? Please describe.**

I can't use `question_mark` of Google Material Design Icons. This should be a valid icon: https://fonts.google.com/icons?selected=Material+Icons&icon.query=question+mark. 

Example use-case:

```html
<q-btn flat dense icon="question_mark" class="q-mr-sm" />
```

**Describe the solution you'd like**

I think we should update the css/font.

**Additional context**

And why not update the other icon packs as well?

**Comment by melroy89** [comment]
Running the update.sh and coping those woff and woff2 files into my node_modules project did solve me problem.. So it's indeed out-of-date.

Update: I'm running Quasar v2.3.0.

**Comment by melroy89** [comment]
See PR :)

**Comment by MilosPaunovic** [comment]
There was no problem using `question_mark` in the exact way you've described.
[https://codepen.io/milospaunovic/pen/BadrqMK?editors=101](https://codepen.io/milospaunovic/pen/BadrqMK?editors=101)

If you're still having problem, please provide Codepen reproduction.

**Comment by hawkeye64** [comment]
The latest (released usually every Sunday) can be found here: https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fextras-v1.11.5
