### ISSUE TITLE
q-toolbar dark didn't work

### ISSUE THREAD

**Issue by heyingjie** [quasarframework/quasar#11239]
**Describe the bug**

use code like below to set dark mode,but have no effect on q-toolbar.
`$q.dark.set(true);`

**Expected behavior**
q-toolbar change to dark mode,black background,white text.

**Screenshots**
![image](https://user-images.githubusercontent.com/11901953/140640965-fee0b8e6-2e80-4c67-afcb-9a5f6c941354.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: v2.3.0

Quasar mode:
  SPA

Tested on:
  - SPA

OS: Windows 10
Node: v14.17.6
Yarn: 1.22.17
Browsers: Chrome 94.0.4606.54

**Comment by MilosPaunovic** [comment]
Please provide a Codepen reproduction of your problem, or at least the code you've written for `QToolbar`.

**Comment by heyingjie** [comment]
`<template>
  <q-layout view="lHh Lpr lFf">
    <q-header elevated>
      <q-toolbar>

        <q-toolbar-title> Quasar App </q-toolbar-title>

        <q-btn push label="Toggle Dark Mode" @click="toggleDarkMode" />

        <div>Quasar v{{ $q.version }}</div>
      </q-toolbar>
    </q-header>

    <q-page-container>
    </q-page-container>
  </q-layout>
</template>

<script>
import { useQuasar } from "quasar";

import { defineComponent } from "vue";

export default defineComponent({
  name: "MainLayout",

  setup() {
    const $q = useQuasar();

    $q.dark.set(true);

    watch(
      () => $q.dark.isActive,
      (val) => {
        console.log(val ? "On dark mode" : "On light mode");
      }
    );
 
    return {
      toggleDarkMode() {
        $q.dark.toggle();
      },
    };
  },
});
</script>
`

**Comment by heyingjie** [comment]
> Please provide a Codepen reproduction of your problem, or at least the code you've wirtten for `QToolbar`.

<template>
  <q-layout view="lHh Lpr lFf">
    <q-header elevated>
      <q-toolbar>

        <q-toolbar-title> Quasar App </q-toolbar-title>

        <q-btn push label="Toggle Dark Mode" @click="toggleDarkMode" />

        <div>Quasar v{{ $q.version }}</div>
      </q-toolbar>
    </q-header>

    <q-page-container>
    </q-page-container>
  </q-layout>
</template>

<script>
import { useQuasar } from "quasar";

import { defineComponent } from "vue";

export default defineComponent({
  name: "MainLayout",

  setup() {
    const $q = useQuasar();

    $q.dark.set(true);

    watch(
      () => $q.dark.isActive,
      (val) => {
        console.log(val ? "On dark mode" : "On light mode");
      }
    );
 
    return {
      toggleDarkMode() {
        $q.dark.toggle();
      },
    };
  },
});
</script>

**Comment by heyingjie** [comment]
`<template>
  <q-layout view="lHh Lpr lFf">
    <q-header elevated>
      <q-toolbar>

        <q-toolbar-title> Quasar App </q-toolbar-title>

        <q-btn push label="Toggle Dark Mode" @click="toggleDarkMode" />

        <div>Quasar v{{ $q.version }}</div>
      </q-toolbar>
    </q-header>

    <q-page-container>
    </q-page-container>
  </q-layout>
</template>`

`<script>
import { useQuasar } from "quasar";

import { defineComponent } from "vue";

export default defineComponent({
  name: "MainLayout",

  setup() {
    const $q = useQuasar();

    $q.dark.set(true);
 
    return {
      toggleDarkMode() {
        $q.dark.toggle();
      },
    };
  },
});
</script>`

**Comment by heyingjie** [comment]
```
<template>
  <q-layout view="lHh Lpr lFf">
    <q-header elevated>
      <q-toolbar>
        <q-toolbar-title> Quasar App </q-toolbar-title>
        <q-btn push label="Toggle Dark Mode" @click="toggleDarkMode" />
        <div>Quasar v{{ $q.version }}</div>
      </q-toolbar>
    </q-header>
    <q-page-container>
    </q-page-container>
  </q-layout>
</template>
```

```
<script>
import { useQuasar } from "quasar";

import { defineComponent } from "vue";

export default defineComponent({
  name: "MainLayout",

  setup() {
    const $q = useQuasar();

    $q.dark.set(true);
 
    return {
      toggleDarkMode() {
        $q.dark.toggle();
      },
    };
  },
});
</script>
```

**Comment by MilosPaunovic** [comment]
You need to bind background class to `QToolbar`, like this:
```html
<q-toolbar :class="{'bg-dark': $q.dark.isActive}">
```

[https://codepen.io/milospaunovic/pen/yLoKGGN?editors=101](https://codepen.io/milospaunovic/pen/yLoKGGN?editors=101)

**Comment by heyingjie** [comment]
tks，it works
