### ISSUE TITLE
Jumping QTable pagination menu

### ISSUE THREAD

**Issue by AlexDaniel** [quasarframework/quasar#11247]
Any table in the official documentation can be used to reproduce:
https://quasar.dev/vue-components/table#basic-usage

![Peek 2021-11-07 23-14](https://user-images.githubusercontent.com/5507503/140662103-0ebc4aa8-d633-4025-9aae-72fc4dc28a70.gif)

**Steps to reproduce the behavior:**
1. Look at any QTable with “Records per page:” option available
2. Click on the number
3. The menu will appear, and it will immediately jump to a different place

**Expected behavior**
The menu should not jump.

OS: Linux
Browsers: Firefox 93.0, Chromium 93.0.4577.82 (yeah, both version numbers are 93, amazing)

**Additional context**
The menu doesn't jump if you open it again. The problem is not just with the docs, I see it locally in my own project too.

**Comment by AlexDaniel** [comment]
It has been quite a while since I posted this, so just to clarify, the bug is still present.

**Comment by Marcindyg** [comment]
My team also struggle with this problem. Any chance to solve it?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.12.1

**Comment by ddenev** [comment]
@rstoenescu, I think this fix critically breaks the usage of `anchor` and `self` for QMenu.

Please check this - https://codepen.io/ddenev/pen/OJamvJP

I just have added
```
anchor="bottom middle" self="top middle"
```
to the `q-menu` element.

This was working properly on v2.12.0

**Comment by rstoenescu** [comment]
@ddenev Thanks for pointing this out. Fixed it. Will be available in today's UI release.

**Comment by AlexDaniel** [comment]
@rstoenescu the issue is still present in the docs. Is that expected?

**Comment by rstoenescu** [comment]
@AlexDaniel The docs is a PWA. It may not have updated for you yet. Check the Quasar UI version on the header (right-side version dropdown). Either wait for it to get updated or open devtools and remove the PWA then refresh to get it going reinstalling the latest and greatest.

**Comment by AlexDaniel** [comment]
Ah yeah, it works now! Thank you very much!
