### ISSUE TITLE
`@update:model-value` event fired twice in `q-input` type "number"

### ISSUE THREAD

**Issue by Smrtnyk** [quasarframework/quasar#11246]
**Describe the bug**
When using q-input with type number and increment button is clicked, @update event is fired twice
then the value gets incremented twice
HAPPENS ONLY WHEN DEVTOOLS OPEN!

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Smrtnyk93/pen/PoKRrEp

**To Reproduce**
1. Go to linked codepen
2. Open dev tools so debugger can stop on breakpoint
3. Click on the increment button on the right side of the q-input
4. See that debugger stops execution twice on the break point and value is incremented twice

**Expected behavior**
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number
if you go here it should increment by 1, and I would not expect that the @update event is fired twice

**Platform (please complete the following information):**
Quasar Version:  see codepen
@quasar/app Version: see codepen

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux ubuntu
Node: 16
NPM: 8
Browsers: Chromium

**Additional context**
Tested in codepen and on my local ubuntu with latest quasar

**Comment by hawkeye64** [comment]
Indeed, this is an interesting bug. Possibly a reactivity issue.

**Comment by yusufkandemir** [comment]
It also happens with regular HTML input, created a Codepen based on your example: https://codepen.io/yusufkandemir/pen/zYdjMVQ
So, it's about how browsers are handling things, not specific to Quasar, Vue, or anything else.

**Comment by hawkeye64** [comment]
@yusufkandemir Good to know! Thanks for following up on this and finding it is NOT a Quasar issue. Seems this is only happening in Chromium-based browsers. It does not happen with Firefox. I am curious if this happens with Safari.

**Comment by MilosPaunovic** [comment]
@hawkeye64 Safari `Version 14.1.1 (16611.2.7.1.4)` on MacOS BigSur `11.4 (20F71)` goes nuts with initial Codepen example from this issue [https://codepen.io/Smrtnyk93/pen/PoKRrEp](https://codepen.io/Smrtnyk93/pen/PoKRrEp).

https://user-images.githubusercontent.com/62475782/141008733-00774fca-fc9e-4d06-a588-180ef16742ac.mov

**Comment by Smrtnyk** [comment]
@MilosPaunovic  is it like that with the codepen from @yusufkandemir ?

**Comment by MilosPaunovic** [comment]
It's kinda same. The input goes to `5`, but only as that's max value.
When I change `max` to any larger number, it goes up unitl it.

https://user-images.githubusercontent.com/62475782/141100679-627ba1a7-e215-4b2d-b2fb-2f5b764d0e30.mov

**Comment by pdanpdan** [comment]
It doesn't matter. It's just something related to stopping the execution in debugger. You'll see also bugs where it you stop before a console.log the execution would break when it executes the log

**Comment by Smrtnyk** [comment]
anyways, related to multiple events
can anyone tell me why dialog is created two times if I type something in the input field
Here is the repo
https://github.com/Smrtnyk/quasar-event-repro
