### ISSUE TITLE
Q-select: Focus remains on invalid content

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#11256]
This is a minor issue (now I know how to avoid it), but I wasted days chasing it down...
When using Q-select in 'text autocomplete' mode, tabbing out of the q-select when an invalid entry has been typed causes the q-select to **remain focused**, unless it includes a no-option slot!
Since I didn't want the no-option slot, I spent days trying to solve the stuck focus problem.
The work-around is to always include the no-option slot even if it has no content.

Here's a code sandbox demo...
https://codesandbox.io/s/q-select-focus-problem-z0gbb

Quasar Version: 2.2.2
@quasar/app Version: 3.1.8

Quasar mode:
  - [ x] SPA

OS: Windows
Browsers: Chrome

**Comment by hawkeye64** [comment]
The q-select still has the blue underline, indicating focus...
![image](https://user-images.githubusercontent.com/10262924/140805453-335a7fc0-19fc-45de-ac06-54f374811b5e.png)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.3.1.
