### ISSUE TITLE
QInput - when type=number, mask and maxlength is not working

### ISSUE THREAD

**Issue by cristian-swf** [quasarframework/quasar#11254]
When a QInput type is number, the mask, for example (######) and maxlength is not working. If type is set to text, they work ok.

**To Reproduce**
1. Add a QInput wity type=number, mask ###### and maxlength=6
2. Check in browser to see if the mask and maxlength is respected
3. See error

**Expected behavior**
Qinput type=number should respect maxlenght and/or mask (if applicable)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.1.6

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [x] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [x] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: 16.10
NPM: 7.24
Browsers: Firefox, Chrome
Android: 12

**Comment by MilosPaunovic** [comment]
That is correct behaviour.

Check out `Warning` banner on the official docs:
[https://quasar.dev/vue-components/input#mask](https://quasar.dev/vue-components/input#mask)

![Screenshot 2021-11-08 at 16 00 35](https://user-images.githubusercontent.com/62475782/140765492-4f93515f-ada8-4471-b74e-720ab053554c.png)

**Comment by cristian-swf** [comment]
Oups, missed that one :(
But still, the issue with maxlength is still present. I know the native input type number does not support it, only min and max, but can this be implemented in a future release in the component?

**Comment by MilosPaunovic** [comment]
I don't see it implemented as `Quasar` follows web standards.

What you could do is implement custom validation for that field:
[https://quasar.dev/vue-components/input#validation](https://quasar.dev/vue-components/input#validation)
