### ISSUE TITLE
Error when SSR is runing to cpanel node.js

### ISSUE THREAD

**Issue by ukik** [quasarframework/quasar#11259]
i got error like this from log in cpanel. my app work well on localhost but on ndoe.js server my server-side-rendering app got error like this:

BROWSER
500 | Internal Server Error

LOG FILE
(node:28456) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/rzedixky/nodevenv/tera1.labsnip.com/10/lib/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/rzedixky/nodevenv/tera1.labsnip.com/10/lib/node_modules/express/lib/response.js:170:12)
    at t.then.catch.e (/home/rzedixky/tera1.labsnip.com/index.js:1:679)
(node:28456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rstoenescu** [comment]
Hi,

This has nothing to do with Quasar. It's related to your code or your deployment infrastructure. But no details have been supplied. Put yourself in our shoes: you get a ticket with a thrown-out error message (stack not even showing any Quasar or Quasar CLI files). How can this be investigated.. at all?

Please supply a reproduction repo and detail as much as possible how and where you deploy your app.
