### ISSUE TITLE
onClose handler for left and right drawers 

### ISSUE THREAD

**Issue by prsnnami** [quasarframework/quasar#1125]
Is there a way to run something when the drawer closes.

**Comment by rstoenescu** [comment]
Yes. Please read the documentation. Use the callbacks.

**Comment by prsnnami** [comment]
where exactly is this in the documentation, sorry cant find it still.

**Comment by rstoenescu** [comment]
http://quasar-framework.org/components/layout.html#Vue-Methods --> all these take a callback as param. I now see the documentation is lacking this part, so will add it. Sorry for this.

**Comment by prsnnami** [comment]
Also the callback is only running if I close the drawer with the toggleRight()/hideRight() but not when i dismiss it by clicking outside the drawer.

**Comment by rstoenescu** [comment]
You'll be able to detect that in v0.15. Working with full energy on releasing that (along with a top-notch new starter kit which will enhance the developer experience greatly!)
