### ISSUE TITLE
QSlider is not reacting to model value change

### ISSUE THREAD

**Issue by susnux** [quasarframework/quasar#11250]
**Describe the bug**
If you change the model value of a QSlider by sliding and after that by changing the model-value programmtically it does not react to the latter one.
So after using the slider the model-value is not reactive anymore.

See the example below.

**Codepen/jsFiddle/Codesandbox (required)**
[sandbox](https://codesandbox.io/s/lucid-bassi-0ij5t?file=/src/pages/Index.vue)

**To Reproduce**
Open the sandbox, there is a timeout (5 seconds), if you change the first slider within those 5 seconds it does not react to
the timeout, if you do not touch it the slider will move after 5 seconds.

Or use the second slider, the model-value will only change if you set the slider to an uneven value, but as you can see the slider
will take every value, even if the model-value is not updated.

**Expected behavior**
The slider should emit its current value and then go back to its model-value.

**Screenshots**
see sandbox.

**Platform (please complete the following information):**
Quasar Version: 2.3.0
@quasar/app Version: 3.1.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux
Node: 
NPM: 12.x and 16.6.2
Yarn: 1.22.17
Browsers: Firefox 93.0
iOS: -
Android: -
Electron: -

**Additional context**
(I wanted to submit the value to an API and if it fails the slider should revert to the previous state).

**Comment by rstoenescu** [comment]
It's related to the focus state. Has nothing to do with the model reactivity.
Fix will be available in Quasar v2.3.1.
