### ISSUE TITLE
Error with vue-class-component

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#11255]
Hello , 
from quasar/app-v3.1.9 with vue 3.2.21 , I think this dependency create blocking issue with vue-class-component , I have this error for my all componenst : 
Class extends value # is not a constructor or null

if i go back to vue 3.2.20 i feel like it works.

I created an issue on the vue-class-component side : 
https://github.com/vuejs/vue-class-component/issues/576

**Comment by rstoenescu** [comment]
This has nothing to do with Quasar... Please follow the Vue ticket.
Hope we don't go the same route of waiting for me to fix external libs (as recently happened), because Quasar itself needs my attention too and we're quite busy preparing awesome new stuff :)

**Comment by rstoenescu** [comment]
Did you mean Vue 3.2.1 & 3.2.0 or actually 3.2.21 & 3.2.20 ? @nseb

**Comment by nseb** [comment]
sorry 3.2.21 error , 3.2.20 works
@rstoenescu I know it's an external dependency, it's mostly to alert those who updated like me.

**Comment by rstoenescu** [comment]
I will temporarily downgrade Vue to 3.2.20 in q/app v3.2.0 -- to be released tomorrow with a huge new feature (SSR-related).

**Comment by nseb** [comment]
@rstoenescu thx
I prepare un code example CodePen to fill issue for vue
