### ISSUE TITLE
adding own colors missing !import

### ISSUE THREAD

**Issue by silberGuy** [quasarframework/quasar#11269]
Hey :)
I tried to add a custom color to the app, as explained here:
https://quasar.dev/style/color-palette#adding-your-own-colors

but none of the components were affected, because their inner stylings is overriding my own `text-brand`.
For instance, the example shown does not work because `.q-btn` defines color as with "inherit" and wins against the `text-brand`.

I saw that the framework defines the brand colors classes with `!important`:
https://github.com/quasarframework/quasar/blob/dev/ui/src/css/core/colors.sass

I guess this should be added to the docs?

Thank you!

**Comment by rstoenescu** [comment]
Thanks for catching this. Update will be available on next docs deployment.
