### ISSUE TITLE
[bug] Link of viewsource is broken in the components page CSS Flex of Quasar

### ISSUE THREAD

**Issue by cristianolemospompeia** [quasarframework/quasar#1126]
Hi! Sorry, but my English is not verywell.
I trie access the link https://github.com/quasarframework/quasar-play/tree/master/src/components/showcase/css-helpers/flex-css.vue but is show error 404.
Fix this please.

Thanks a lot

**Comment by rstoenescu** [comment]
Hi, please redirect this to the documentation repo. Thanks. https://github.com/quasarframework/quasar-framework.org
