### ISSUE TITLE
vueLoaderOptions details missed in doc

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#11263]
I needed to access vue app parameters because I wanted to change delimiters in templates
I couldnt find any description about `vueLoaderOptions` in `quasar.conf.js` docs. 
It's currently only documented in https://quasar.dev/start/upgrade-guide#quasar-app-cli and has no description other then the self descriptive name

**Comment by rstoenescu** [comment]
Like the name implies, you can set whatever the `vue-loader` params supply (quasar.conf > build > vueLoaderOptions). Example: `{ compilerOptions: {..} }`.
Indeed, it should be added to quasar.conf.js doc page. Somehow this was missed.

**Comment by rstoenescu** [comment]
Will be available on next docs deployment.
