### ISSUE TITLE
Meta does not work on server side

### ISSUE THREAD

**Issue by mirkofisic** [quasarframework/quasar#11275]
**Describe the bug**
I want to use Meta plugin on server side to change head title and description during render, but on server env I got error and it only works when page comes to the client mode:

> [Vue warn]: Unhandled error during execution of setup function 
>   at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
> [Quasar Dev Webserver] / -> error during render
> TypeError: Cannot read properties of undefined (reading 'push')
>     at useMeta (C:\projects\quasar\testpr\node_modules\quasar\dist\quasar.cjs.prod.js:6:465788)
>     at setup (chunk-src_pages_Index_vue.js:68:52)
>     at callWithErrorHandling (C:\projects\quasar\testpr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6615:22)
>     at setupStatefulComponent (C:\projects\quasar\testpr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6241:29)
>     at setupComponent (C:\projects\quasar\testpr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6197:11)
>     at renderComponentVNode (C:\projects\quasar\testpr\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:198:17)
>     at renderVNode (C:\projects\quasar\testpr\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:304:22)
>     at renderComponentSubTree (C:\projects\quasar\testpr\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:269:13)
>     at renderComponentVNode (C:\projects\quasar\testpr\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)
>     at renderVNode (C:\projects\quasar\testpr\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:304:22)

Also I have to note that I use SSR and PWA

```
<script async setup>
import { useMeta } from 'quasar'
const metaData = {
  title: 'Test Index',
  meta: {
    description: { name: 'description', content: 'Page 1' },
    keywords: { name: 'keywords', content: 'Quasar website' }
  }
}
console.log('IsServer:', process.env.SERVER)
useMeta(metaData) // does not work
</script>
```

So tried to use the meta inside <script setup> I also tried to use inside the setup () function when defining the component the error is always the same, it looks like that meta only works with Options API and createMetaMixin hook.

**Platform (please complete the following information):**
Quasar Version: 2.3.0
@quasar/app Version: 3.0.0

Quasar mode:
  - [x ] SSR
  - [ x] PWA

Tested on:

  - [ x] SSR
  - [ x] PWA

OS: windows
Node: v16.13.0
NPM:7.20.0
Yarn:
Browsers: Chrome Version 95.0.4638.69
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
I have to ask: did u follow the Meta plugin install instructions?

**Comment by rstoenescu** [comment]
Yeah, you haven't installed it.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/4665641/141108834-f3fb968e-6f44-4bb5-a8f3-811816ec5e5c.png">

**Comment by mirkofisic** [comment]
> Yeah, you haven't installed it.
> 
> <img alt="image" width="454" src="https://user-images.githubusercontent.com/4665641/141108834-f3fb968e-6f44-4bb5-a8f3-811816ec5e5c.png">

I was sure that I installed it, sorry i make mistake. thank you very much
