### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'contains')     at refocusTarget

### ISSUE THREAD

**Issue by leonbuild** [quasarframework/quasar#11272]
**Describe the bug**
Within a radio button, I'm putting a button that jumps to another page. 
When click that button to jump, the error happens: 
![image](https://user-images.githubusercontent.com/71315684/141078421-4073ee53-26ac-4783-b584-99d790d6e691.png)
![image](https://user-images.githubusercontent.com/71315684/141082318-e67845d1-176b-4bcd-b472-d429241453e1.png)

https://github.com/quasarframework/quasar/blob/1b310a405717d1ee0b5829d4a185601d814ea64d/ui/src/components/radio/QRadio.js#L113

https://github.com/quasarframework/quasar/blob/1b310a405717d1ee0b5829d4a185601d814ea64d/ui/src/composables/private/use-refocus-target.js#L24

I think a `null` check of `rootRef` is needed here.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.3.1.
