### ISSUE TITLE
In production, the modal doesn't close if the server response time was below 200ms

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1127]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: v8.9.1
NPM: 5.5.1
Browsers: Google Chrome Version 62.0.3202.89 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
No error but the modal still open
### What were you expecting?
I expect the modal to close when changing the v-model to false
### What steps did you take, to get the error?
I've created a loading modal that contains a message and spinner and opening and closing it automatically using v-model, I show this modal every time the user login/register etc. what happening is if the server response time was below 200ms the modal still open.

**Comment by rstoenescu** [comment]
Already fixed in future v0.15.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu WOW thank you so much, I'm really excited about v0.15

However, I've created a workaround to solve the issue temporarily, for anyone that needs to be sure that the modal will be open for a specific amount of time, here is my entire LoadingModel.vue file:

```
<template>
    <q-modal :no-backdrop-dismiss="true" @close="closed" v-model="isOpen" class="text-center confirmation-modal" minimized :content-css="{padding: '20px'}">
        <div class="row xs-gutter">
            <div class="col">
                <q-spinner-hearts color="purple-6" slot="message" :size="90" />
            </div>
        </div>
        <p class="to-rtl">جار تنفيذ الطلب</p>
    </q-modal>
</template>

<script>
import { QModal, QSpinnerHearts } from "quasar";

export default {
  props: {
    open: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      isOpen: false,
      modalCloseProcessing: false,
      modalMustStillOpenAtLeastFor: 250,//In miliseconds
      modalOpenSinceInDateFormat: null
    };
  },
  methods: {
    closed() {
      this.$emit("closed", true);
    }
  },
  watch: {
    open: function(newValue) {
      let vm = this;

      if (newValue && !vm.modalCloseProcessing) {
        vm.isOpen = true;
        vm.modalCloseProcessing = true;
        vm.modalOpenSinceInDateFormat = new Date();
      } else if (!newValue && vm.modalCloseProcessing) {
        let modalOpenSinceInMilisecondFormat =
          new Date() - vm.modalOpenSinceInDateFormat;
        if (
          modalOpenSinceInMilisecondFormat < vm.modalMustStillOpenAtLeastFor
        ) {
          setTimeout(function() {
            vm.isOpen = false;
            vm.modalCloseProcessing = false;
          }, (vm.modalMustStillOpenAtLeastFor -
            modalOpenSinceInMilisecondFormat));
        }
      }
    }
  },
  components: {
    QModal,
    QSpinnerHearts
  }
};
</script>

<style scoped>
.confirmation-modal>>>.to-rtl {
  direction: rtl;
}
</style>

```

**Comment by rstoenescu** [comment]
@MohammedAl-Mahdawi I see you're using RTL. Would you be so kind to help out on the official RTL release? I need devs tweaking the RTL build.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu Sure, the project that I'm currently working on is RTL project, please just tell me how can I help and I'll do my best.
