### ISSUE TITLE
Q-select menu problem

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#11289]
Getting a weird looking drop-down menu from Q-select.
I'm trying to build a custom component based on Q-select with autofill. I need to make several forms with tables containing combo-box entries, and want to consolidate all the filtering, etc. code in my custom component called MySelect.

The options passed down to MySelect will be an object with key-value pairs where the key represents an ID, and the value is the Name of the item. It's working fine EXCEPT when typing into the box and more characters are typed than needed for a match, I get  this weird menu behaviour...
![MenuProblem](https://user-images.githubusercontent.com/45148066/141325926-b4d8ecdc-35f2-46fb-a90b-2fff69ae2ebe.png)

I've built a code sandbox demo to show it here...
https://codesandbox.io/s/q-select-menu-problem-7nweu

I don't know if this is a Quasar bug, or I'm just using it wrong. If the latter, suggestions will be appreciated.
Thanks for the great work!

Quasar Version: 2.3.0
@quasar/app Version: 3.1.10

Quasar mode:
  - [ ] SPA

Tested on:
  - [ ] SPA

OS: Windows 10
Browsers: Chrome

**Comment by hawkeye64** [comment]
@CrawfordW  Looks like a legit bug to me. The virtual scrolling is getting turned on for some reason.

**Comment by pdanpdan** [comment]
The component uses the best worst practices :))))

https://codesandbox.io/s/q-select-menu-problem-forked-9mof0?file=/src/components/MySelect.vue

**Comment by CrawfordW** [comment]
Thanks - that fixed it! I'm still learning the ropes and appreciate your help.

**Comment by pdanpdan** [comment]
- pass model-value (modelValue) from parent to component
- emit update:modelValue from child to notify the parent that the component has changed the model
- try not to keep internal state if you don't need it (you'll have a lot of fun with syncing modelValue with your internal value)
- use computed if you can

- in the specific case of that component in the example I'm not sure I understand why you reset the model to null in all cases except 1 option or select from list - I would say in a lot of cases you should leave it as it is
