### ISSUE TITLE
Q-Btn Support active router link (router-link-exact-active)

### ISSUE THREAD

**Issue by melroy89** [quasarframework/quasar#11280]
**Is your feature request related to a problem? Please describe.**

The Q-Btn ([Quasar Button](https://quasar.dev/vue-components/button)) support router links via `to=..`, which is very helpful. However, when I press the link normally the link should contain the class `router-link-exact-active` when the route is active (user pressed the link), allowing you to give it another color.

**Describe the solution you'd like**

I would like to be able to just style the button color text, eg. `a.router-link-exact-active`. Which is not possible now.

**Describe alternatives you've considered**

Wrap the q-btn around a router-link yourself, defeat the whole purpose of using `to=` attribute to q-btn.

```vue
<q-btn stretch flat label="Items">
  <router-link
    exact
    :to="{ name: 'items' }"
    class="absolute full-width full-height"
  ></router-link>
</q-btn>
```

**Additional context**

Discussion in Forum: https://forum.quasar-framework.org/topic/5133/how-to-style-q-btn-with-to/4

**Comment by MilosPaunovic** [comment]
Have you considered binding class to button based on route?

```js
<q-btn :to="{ name: 'Somewhere' }" :class="{ active: $route.name === 'Somewhere' }" label="Link to somewhere">
```

**Comment by melroy89** [comment]
No, but still looks like a workaround. Thank you anyway for this alternative.

**Comment by rstoenescu** [comment]
QBtn is one of the most used components in any apps.
We keep on adding features to it, but we must not forget that the runtime speed needs to be as high as possible. For this reason, we will not add the active/exact-active feature to it because the overhead is huge.

The `:class="{ active: $route.name === 'Somewhere' }"` approach is legit.

**Comment by melroy89** [comment]
😢  but understandable I think
