### ISSUE TITLE
"@quasar/app": "3.2.0", TypeError: injectMiddleware is not a function

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#11283]
update "@quasar/app": "3.2.0" dev server error； build ok；

rollback "@quasar/app": "3.1.10" ok

node_modules/@quasar/app/lib/dev-server-ssr.js:141
            return injectMiddleware({
                   ^

TypeError: injectMiddleware is not a function
    at /node_modules/@quasar/app/lib/dev-server-ssr.js:141:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);

**Comment by rstoenescu** [comment]
Fix is available in "@quasar/app" v3.2.1
