### ISSUE TITLE
Setting color for clearable icon in qipunt

### ISSUE THREAD

**Issue by stefanocarraro-centropaghe** [quasarframework/quasar#11292]
**Is your feature request related to a problem? Please describe.**
On q-input there's the property clearable. It would be nice to be able to specify the color for the clearable icon.

**Describe the solution you'd like**
A String property that can set the clearable icon color or class/style.

**Comment by hawkeye64** [comment]
@stefanocarraro-centropaghe Quasar v1 is in LTS mode, which means no more changes or updates unless it's a bug or security issue.

**Comment by pdanpdan** [comment]
add a class on QInput and style the clearable icon as you need
or use the slot, Luke
https://codepen.io/pdanpdan/pen/eYEjqyQ

**Comment by stefanocarraro-centropaghe** [comment]
@pdanpdan nice idea, thanks.
