### ISSUE TITLE
[Request]Provide a unified build script

### ISSUE THREAD

**Issue by joe-re** [quasarframework/quasar#1129]
Now there are quasar project's build scripts on each templates(default, pwa) and so this repo.
But In fact, there are hardly different.

For example, it looks like build/script.dev.js's different is only presence or absence of proxy-table setting.
https://github.com/quasarframework/quasar/blob/dev/build/script.dev.js
https://github.com/quasarframework/quasar-template-pwa/blob/master/template/build/script.dev.js

I think we should unified them and provide build command which can use on each templates(and this repo).

It let developper to contribute to build script more easy.
Typescript support or https protocol support or and so.

In fact different parts are needed each template.For example, there is service worker support on PWA, but other template isn't.

Good solution is we provide setting script about that.
I think, foundamental build script(webpack.config etc) should be hided from user.
And we should provide 'eject' command like react-create-app or angular-cli.
if who want to setting manually and finely, can use this to out all scripts to user project directory.

How do you think?

**Comment by rstoenescu** [comment]
This is exactly what I am focusing now. A new starter kit which has it all. You will be able to build SPA, PWA, Mobile apps (Cordova) and Electron apps with only one starter kit. In addition, the developer experience for Cordova and Electron is going to take a huge jump forward! Imagine dynamic webpack config (!!) and HMR directly on a device emulator or a real mobile device, without the need of Quasar Play, an furthermore, working with Cordova plugins too! Electron apps will no longer require two package.json... And many many many new possibilites!

One starter kit to rule them all seamlessly. Stay tuned. Quasar is going to bring the developer experience to its best!

**Comment by joe-re** [comment]
Nice 👍
I'm looking forward to it :)
