### ISSUE TITLE
Side bar keep flicking

### ISSUE THREAD

**Issue by tianhuat** [quasarframework/quasar#11318]
In this page https://quasar.dev/layout/page-sticky#expanded
The side bar here keep flicking
![image](https://user-images.githubusercontent.com/12793956/141595339-1f45235c-83bb-4d1a-b868-120220ce5567.png)
What is the issue here?

**Comment by pdanpdan** [comment]
~~#7822~~

**Comment by tianhuat** [comment]
@pdanpdan Why is this closed? the issue is still there..

**Comment by tianhuat** [comment]
@pdanpdan

**Comment by pdanpdan** [comment]
Sorry, I mixed up the duplication label:
duplicate of https://github.com/quasarframework/quasar/issues/10281
duplicate of https://github.com/quasarframework/quasar/issues/11169
Also:
https://github.com/quasarframework/quasar/issues/8469

**Comment by rstoenescu** [comment]
Fixed it in Quasar v2.4.4 & v1.17.1 (to be released)
