### ISSUE TITLE
QScrollArea prop issue

### ISSUE THREAD

**Issue by possibility-of-offense** [quasarframework/quasar#11313]
**QScrollArea prop "content-active-style" is not being applied even if I remove "content-style" prop.**

** https://codepen.io/conscience90/pen/xxLaQMj **

1. Hover over the content area and the new color is not being applied (I've tried with a computed property; the styles are not being applied as well).

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.2.

**Comment by possibility-of-offense** [comment]
I've fixed it locally but I don't know how to make a pull request to the repo.
