### ISSUE TITLE
Documentation bug - side bar keep flickering

### ISSUE THREAD

**Issue by tianhuat** [quasarframework/quasar#11319]
In this page https://quasar.dev/layout/page-sticky#expanded
The side bar here keep flicking

![2021-11-13_13-46-30](https://user-images.githubusercontent.com/12793956/141607511-15c95909-1585-44fe-bcaa-c2efc5a7b71f.gif)

**Comment by pdanpdan** [comment]
duplicate of https://github.com/quasarframework/quasar/issues/10281
duplicate of https://github.com/quasarframework/quasar/issues/11169
duplicate of https://github.com/quasarframework/quasar/issues/11318
Also:
https://github.com/quasarframework/quasar/issues/8469

**Comment by rstoenescu** [comment]
Fixed it in Quasar v2.4.4 & v1.17.1 (to be released)
