### ISSUE TITLE
[Request] Quasar Universal Template

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#1131]
This actually makes all the template build configs in one 

Is this possible in quasar to be an isomorphic framework on all platforms?

**Comment by rstoenescu** [comment]
This is exactly what I am focusing now. A new starter kit which has it all. You will be able to build SPA, PWA, Mobile apps (Cordova) and Electron apps (and SSR -- not sure if at first release, but it will be there) with only one starter kit. In addition, the developer experience for Cordova and Electron is going to take a huge jump forward! Imagine dynamic webpack config (!!) and HMR directly on a device emulator or a real mobile device, without the need of Quasar Play, an furthermore, working with Cordova plugins too! Electron apps will no longer require two package.json... And many many many new possibilites!

One starter kit to rule them all seamlessly. Stay tuned. Quasar is going to bring the developer experience to its best!
