### ISSUE TITLE
[Request] Datetime range selector like Airbnb

### ISSUE THREAD

**Issue by aprilpnguyen** [quasarframework/quasar#1132]
Can we please have a datetime range selector similar to Airbnb? That is one click to select the start date and one click to select the end date on the calendar. The selected range is highlighted. The Airbnb one is just for dates. Can our one have time as well? Thank you!

![screen shot 2017-11-14 at 5 40 02 pm](https://user-images.githubusercontent.com/4740941/32782869-44e37a88-c963-11e7-9eb0-05de45df1817.png)

**Comment by rstoenescu** [comment]
Sounds like a good idea

**Comment by MartinMuzatko** [comment]
I would love to see this. Flatpickr has also a very solid implementation of this: https://flatpickr.js.org/examples/#range-calendar

Since the change from quasar 0.14 to 0.15, the http://v0-14.quasar-framework.org/components/datetime-range.html was removed. I guess this was because it didn't work out that well?

**Comment by topvis** [comment]
It would be great to have this component. Just to provide another example from [Google Flights](https://www.google.com/flights)

![image](https://user-images.githubusercontent.com/5996531/45689754-be40cc80-bb22-11e8-80ef-6459f2bd17a1.png)

**Comment by yellow1912** [comment]
Hello, is there any update on this issue?

**Comment by wc-matteo** [comment]
I would really need this as well!

**Comment by paolog22** [comment]
also looking for this.. +1

**Comment by MartinMuzatko** [comment]
there is https://vcalendar.io now, if you look for a very extensive calendar plugin.

**Comment by MartinManev** [comment]
Hello. I think this will be a great feature to add and I would definitely have use for it. The material design spec does provide an example of a date range picker with mobile and desktop versions here: https://material.io/design/components/pickers.html

Here are some images from that page:
https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1563837804615%2Fassets%2F1ngkWqYCRDQw3ErFqexDfiyoSYQXemrjj%2Fpicker-choosing-range.png

https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1563837804615%2Fassets%2F0B54x0KDcs5U-WTJQQlY3ZXNocHM%2Fpicker-choosing-daterange-desktop.png

**Comment by Rytiggy** [comment]
+1 this

**Comment by pdanpdan** [comment]
Close this issue - please follow up in unified #5052
