### ISSUE TITLE
Dialog plugin fails in mounted hook, requires $nextTick before use

### ISSUE THREAD

**Issue by disarticulate** [quasarframework/quasar#11335]
**Describe the bug**
Dialog plugin fails to work in mounted () hook.

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/disarticulate/QuasarTestDialogv2.3.2.git

**To Reproduce**
clone the repo, run quasar dev, observe which dialogs popup. Only dialogs in $nextTick wrapper fire.

**Expected behavior**
after boot, $q.dialog and Dialog.create should be available in mounted

**Platform (please complete the following information):**
Quasar Version: v2.32

@quasar/app Version: ^3.0.0

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Unix/Windows
Yarn: 1.22.15
Browsers: Chrome, Edge

**Additional context**

**Comment by laferte-tech** [comment]
Hello,

same for me. 
I made a sandbox to show this also:

https://codesandbox.io/s/romantic-spence-tbhxx?file=/src/App.vue

Dialog should be shown when App.vue is mounted but nothing happen.

Thanks for your help.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.5
