### ISSUE TITLE
Error with icon while building electron app for linux

### ISSUE THREAD

**Issue by d-kurchenko** [quasarframework/quasar#11330]
**Describe the bug**
I get error `⨯ stat path/quasar-test-app/src-electron/icons/icon: no such file or directory` while building electron app for linux.

**To Reproduce**
1.` quasar create quasar-test-app`
2. `quasar mode add electron`
3. `open quasar.conf.js`
4. change bundler mode from "packager" to "builder"
5. `quasar dev -m electron -T linux`

**Screenshots**
![image](https://user-images.githubusercontent.com/93146235/141656807-aa4c426a-8818-4c5a-bd2f-6e6684b38837.png)

**Platform (please complete the following information):**
Operating System - Linux Ubuntu 20.04
@quasar/cli - 1.2.2
Quasar Version: 2.3.1
@quasar/app Version: 3.2.1

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 16.10.0
NPM: 8.1.3
Yarn: 1.22.17
Electron: 15.3.1
Electron-Builder - 22.13.1

**Additional context**
I don't get this error if i build app for win.
After I get this error, folders linux-unpacked and UnPackaged are still created, and UnPackaged/icons has all neded icons. I can run program from my command line but it is has not icon.

**Comment by hawkeye64** [comment]
This only happens for Linux builds (which are currently broken). I have a PR here to fix all that: https://github.com/quasarframework/quasar/pull/11163

**Comment by rstoenescu** [comment]
Fix will be available through "@quasar/app" v3.2.2
