### ISSUE TITLE
Possibility to externalize StaticServe Middleware (SSR)

### ISSUE THREAD

**Issue by Dodobibi** [quasarframework/quasar#11331]
Because the `staticServe` middleware is registered before `injectMiddlewares`, these latter middlewares cannot be applied on static files (ex: compression or helmet middlewares)
[Line 57 of ssr-prod-webserver.js](https://github.com/quasarframework/quasar/blob/8ffd04e223829f36af1e549b8006bfbfa6002799/app/templates/entry/ssr-prod-webserver.js#L57)

It would be nice if it can be possible to extract the staticServe middleware (in the same way than compression or render middleware) for customize it.

**Comment by Evertvdw** [comment]
@Dodobibi I just ran into the same issue, I found a workaround though. You can call `	app._router.stack.unshift(app._router.stack.pop());` after the `app.use()` call to move the middleware that was just added to the first position in the stack.

**Comment by Dodobibi** [comment]
@Evertvdw Thanks !
Also, the new @quasar/app-vite solves this problem, because we have direct access to server.js
