### ISSUE TITLE
Invoking custom component in dialog of Quasar, close dialog can not remove dom

### ISSUE THREAD

**Issue by thisisgpy** [quasarframework/quasar#11344]
I encapsulated a component named GDialog which base on QDialog, codes shows below

    import {QBtn, QCard, QCardActions, QCardSection, QDialog, useDialogPluginComponent} from "quasar";

    export default {
      name: "GDialog",
      components: {
        QBtn,
        QCard,
        QCardActions,
        QCardSection,
        QDialog,
        useDialogPluginComponent
      },
      props: {
        showDialog: {
          readonly: false,
          type: Boolean,
          required: true
        },
        title: {
          type: String,
          required: true
        }
      },
      emits: ['onSave', 'onCancel'],
      setup(props, context) {

        function save() {
          context.emit('onSave')
        }

        function cancel() {
          context.emit('onCancel')
        }

        return {
          save,
          cancel,
        }
      }
    }

    .card-container {
        min-width: 500px;
      }

    <template>
      <q-dialog v-model="showDialog" persistent>
        <q-card class="card-container">
          <q-card-section>
            <div class="text-h6 q-mb-xs text-primary">{{title}}</div>
            <slot></slot>
            <q-card-actions align="right">
              <q-btn icon="save" label="SAVE" color="primary" size="md" @click="save"/>
              <q-btn icon="cancel" label="CLOSE" color="primary" size="md" @click="cancel"/>
            </q-card-actions>
          </q-card-section>
        </q-card>
      </q-dialog>
    </template>

Then I create a component named GDialogForm base on GDialog, codes shows below

    import GDialog from "./GDialog.vue";
    import {QForm, QInput, useDialogPluginComponent} from "quasar";
    import {onMounted, ref} from "vue";
    import {get} from "../../utils/http";

    export default {
      name: "GDialogForm",
      components: {
        GDialog,
        QForm,
        QInput,
      },
      props: {
        showDialog: {
          readonly: false,
          type: Boolean,
          required: true
        },
        title: {
          type: String,
          required: true
        },
        id: {
          type: Number,
          required: false,
          default: -1
        }
      },
      emits: [...useDialogPluginComponent.emits],
      setup(props, context) {
        const { dialogRef, onDialogHide, onDialogOK, onDialogCancel } = useDialogPluginComponent()
        const dialogDisplay = ref(props.showDialog)
        const tagInfo = ref({})
        onMounted(() => {
          if (props.id === -1) {
            tagInfo.value = {
              id: -1,
              tagName: '',
              maxId: 0,
              step: 1000,
              description: '',
              active: true
            }
          } else {
            get(`/api/tag/get/${props.id}`).then(async res => {
              tagInfo.value = await res.data
            }).catch(err => {
              tagInfo.value = {
                id: -1,
                tagName: '',
                maxId: 0,
                step: 1000,
                description: '',
                active: true
              }
            })
          }
        })

        function saveTag() {
          console.log(tagInfo)
          console.log(tagInfo.value)
        }

        function closeDialog() {
          dialogDisplay.value = false
        }

        return {
          dialogRef,
          onDialogHide,
          onOKClick () {
            onDialogOK()
          },
          onCancelClick: onDialogCancel,
          dialogDisplay,
          tagInfo,
          saveTag,
          closeDialog
        }
      }
    }

    <template>
      <g-dialog :show-dialog="dialogDisplay" :title="title" @onSave="saveTag" @onCancel="closeDialog" ref="dialogRef">
        <template v-slot:default>
          <q-form>
            <q-input
                outlined
                v-model="tagInfo.tagName"
                label="TAG-NAME"
                lazy-rules
                :rules="[ val => val && val.length > 0 && val.length < 10 || 'length(0,10)']"
            />

            <q-input
                outlined
                type="number"
                v-model="tagInfo.maxId"
                label="MAX-ID"
                lazy-rules
                :rules="[ val => val && val >= 0 || 'id[0,+∞]']"
            />

            <q-input
                outlined
                type="number"
                v-model="tagInfo.step"
                label="STEP"
                lazy-rules
                :rules="[ val => val && val > 0 || 'id[0,+∞]']"
            />

            <q-input
                outlined
                v-model="tagInfo.description"
                label="DESCRIPTION"
                lazy-rules
                :rules="[ val => val && val.length > 0 && val.length < 30 || 'length(0,30)']"
            />
          </q-form>
        </template>
      </g-dialog>
    </template>

Now, when I click close button, the dialog will be hide. But the dynamic generated dom <div data-v-app>...</div> still exists.

Why?

The result I expect is that as the Dialog is closed, the DOM should be removed, just like the default behavior of QDialog.

**Comment by pdanpdan** [comment]
Hello. Please use the discord channel or the discussions for help requests.
Also in such a case make a codepen.
