### ISSUE TITLE
Feature request: Add --plain-text-output switch to "quasar inspect" command

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#11340]
**Is your feature request related to a problem? Please describe.**

I am saving "quasar inspect" output to file using this command:
```bat
quasar inspect >inspect.txt
```

As a result I get color markup in inspect.txt:
```
[32m'images'[39m,
```

**Describe the solution you'd like**

Add command line switch to output plain text without color markup.

**Describe alternatives you've considered**

I tried to view it directly.
But it is inconvenient because of large output size.

I prefer to output to file and use search to find the right place.

**Additional context**

![Screenshot](https://user-images.githubusercontent.com/70687432/141754776-b38bb1ef-0d7b-40dd-911f-ea067fe52aa7.jpg)

**Comment by hawkeye64** [comment]
Use a tool that strips the codes. I think `less -R` will also display correctly. Otherwise, use a tool like this one: https://github.com/kilobyte/colorized-logs

**Comment by pdanpdan** [comment]
I think it should respect the Unix behavior of only outputting ANSI colors when using the console

**Comment by hawkeye64** [comment]
Yes, we do the same thing for the build. @rstoenescu can re-open if he wants to add this to his already busy list of activities.
