### ISSUE TITLE
[Feature Request] icon properties instead of hard-coded material icons

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar#1135]
I'm using [Ionicons v3](https://ionicframework.com/docs/ionicons/) in my Android+iOS PWA app. To make my app loading time as small as possible, I'm not downloading Material Icons on iOS. I have to use cumbersome CSS tricks to use Ionicons iOS icons instead of default Quasar hard-coded material design icons (collapsible down arrow, password visibility eye icons…).

Just like for `q-checkbox`, Is it possible to create icon properties for quasar components using hard-coded material icons, for instance something like `arrow-icon`, `visibility-on-icon`, `visibility-off-icon` and so?
I can make a PR if needed.

That would really make Quasar more cross-plattform friendly. Thanks!

**Comment by rstoenescu** [comment]
In future v0.15 you'll be able to select what icon package to use (material, ionicons or fontawesome) and only that package will be needed. So Material icons will no longer be an absolute requirement. Furthermore, you'll be able to customize all icons used by Quasar components.

**Comment by laurentpayot** [comment]
Amazing. Thanks Razvan :+1:
