### ISSUE TITLE
Q-table sort not working when using a length as cell content

### ISSUE THREAD

**Issue by Craigzyc** [quasarframework/quasar#11350]
**Describe the bug**
This seems to be a bug but I'm probably just doing something wrong. 
I am trying to load up a view that shows the counts of occurances in an array using length. The numbers display fine in this way but the sort doesn't work at all. 

https://jsfiddle.net/craigzych/jxk8mLbr/3/

Open the fiddle
Try to sort by the columns
They don't sort in numerical order

**Expected behavior**
Proper sorting

**Screenshots**
![image](https://user-images.githubusercontent.com/20641872/141827372-1c314f4e-1d9a-45bd-9bf2-780aa3765172.png)

**Platform (please complete the following information):**
Quasar Version: 2.3.0
@quasar/app Version:3.1.10

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:winodws 11
Node: 16.13.0
NPM:8.1.1
Yarn:
Browsers: chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Hello. For help requests please use the discord channels or the discussions.
