### ISSUE TITLE
Selected text on q-editor is not replaced when using plaintext-pasting if selected using ctrl+a

### ISSUE THREAD

**Issue by lukegravitt** [quasarframework/quasar#11355]
**Describe the bug**
The underlying selected text in a q-editor is not replaced when using the plaintext-pasting from the docs, if the text is selected using Ctrl + A or if the mouse up event occurs outside of the q-editor control.

**Codepen/jsFiddle/Codesandbox (required)**

It's reproducible in the editor embedded in the docs here:
https://v1.quasar.dev/vue-components/editor#plaintext-pasting

**To Reproduce**
1. Click inside q-editor
2. Press ctrl+A
3. Attempt to paste anything

**Expected behavior**
All text in the editor is replaced with the copied text.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.2.4

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
I cannot reproduce it. What browser / os?
Are there any other steps needed to reproduce?

**Comment by lukegravitt** [comment]
Very reproducible on Chrome/OSX by doing the steps -- the behavior seems to be different depending on whether the mouse is still hovering over the editor (bug occurs) or whether its outside of it (does not occur).

If you select all the text with a drag and end the drag outside the editor it also occurs.

Also occurs on Firefox and Safari on OSX.
Also occurs in v2 of Quasar: https://quasar.dev/vue-components/editor#plaintext-pasting

Also occurs on Chrome on mobile (Android)

**Comment by rstoenescu** [comment]
This should work correctly in latest Qv2 and Qv1.
