### ISSUE TITLE
When the mouse clicks on the canvas container, the q-menu cannot be hidden.

### ISSUE THREAD

**Issue by zouyaoji** [quasarframework/quasar#11359]
**Describe the bug**
I use quasar in the map app. I have a problem, it may be a bug.

When the menu is in the shown state, click the map container, it cannot be hidden.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/nostalgic-hill-ybq8c?file=/src/layouts/main-layout.vue

**To Reproduce**
1. Go to https://codesandbox.io/s/nostalgic-hill-ybq8c?file=/src/layouts/main-layout.vue
2. Click on the 'BASIC MENU'  button, and the menu will be shown.
3. Click on the map container.
4. See error —— the q-menu cannot be hidden.

**Expected behavior**
the q-menu can be hidden.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: win10
Node: 14 LTS
NPM: 
Yarn:
Browsers: Google Chrome 版本 95.0.4638.69（正式版本） （64 位）
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Sorry, canvas shoes not pass events to parent registered handlers, so it's not much we can do.
