### ISSUE TITLE
QFixedPosition displays behind QDataTable due to missing z-index

### ISSUE THREAD

**Issue by altShiftDev** [quasarframework/quasar#1136]
### Software version

Quasar: 0.14.7
OS: OSX 10.12.6
Node: IDK
NPM: 4.2.0
Browsers: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
iOS: 
Android:
Any other software related to your bug:

### What did you get as the error?
QFixedPosition fails to place the button on top of the QDataTable component.
### What were you expecting?
QFixedPosition to have a higher z-index so to be always visible.
### What steps did you take, to get the error?
None, default behavior.

### My Fix: 
Add this CSS
```
.z-fixed {
  z-index: 1;
}
```

**Comment by altShiftDev** [comment]
This is my sample QFixedPosition code that I took from the Quasar documentation, adding these lines should be enough to reproduce:
(Note all of the below code is directly inside of a `q-layout` with `view="lHr Lpr lFf"`)

```
      <q-fixed-position corner="bottom-left" :offset="[38, 38]">
        <q-btn round color="primary" icon="person_add" @click='addUser()'/>
      </q-fixed-position>

      <!-- Above Btn should be hidden behind this table element -->
      <q-data-table
        :data="data"
        :config="config"
        :columns="columns"
        >
        <!-- Table Config -->
      </q-data-table>
```

**Comment by rstoenescu** [comment]
This is absolutely normal according to current web standards (referring to the way you are using it -- before the datatable). Furthermore, on IOS the z-index will not save you. What is recommended is that the elements that you want to place on top of others be the last or close to last on pages (or at least after the elements that you want to position on top of them). There is no other better way to handle this cross-browser. Imagine a scenario where you use an element with its own z-index -- combined with a hard-coded z-index for QFixedPosition means more trouble than it solves. You can read on by googling about z-index issues.

**Comment by altShiftDev** [comment]
Ah, OK. Placing it below q-table works perfectly. Sorry!
