### ISSUE TITLE
Using script setup and 'component is' with component names defined external, tree shaking removes the imports of the components

### ISSUE THREAD

**Issue by ap91484** [quasarframework/quasar#11360]
**Describe the bug**
The project is set up with Quasar CLI and Webpack

I have a page which uses dynamic components with `<component :is=.../>`
The list of component names and logic which component to use are in the store.
`<script setup>` is used and all possible components are imported
After `quasar dev` or `quasar build` tree shaking removes the imports, because it is not detecting them used on the page

When I use normal `<script>` where the components are returned it works fine. But with `<script setup> implicit returns, it doesn't.

I defined sideEffects in package.json for *.vue and *.css to no avail.

**Codepen/jsFiddle/Codesandbox (required)**
Only happens when bundled with Webpack

**To Reproduce**
1. Create a project with Quasar CLI
2. Create a page with `<script setup>` use `<component is>` in the template and a component
3. import the component
4. Create a store with a getter to return the component name from an array of names.
5. Bind the `<component :is="">` to the getter
6. Run 'quasar dev'

**Expected behavior**
The imports should be kept in the bundle

**Platform (please complete the following information):**
Quasar CLI Version:  1.2.2
@quasar/app Version: 3.00

Quasar mode:
  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04
Node: 12.22.7
NPM: 
Yarn: 1.22.11
Browsers: Chrome, Safari
iOS:
Android:
Electron:

Current work around is to use normal `<script>` instead of `<script setup>`.

**Comment by hawkeye64** [comment]
Can you add example code:
1) How it's being used dynamically with `<script setup>`
2) How the store containing the components looks

**Comment by ap91484** [comment]
Sorry, couldn't get this to work at all in a sample with script setup and referring to the component by name.
I moved to defineAsyncComponent which works without problems
You can close this issue.
