### ISSUE TITLE
q-linear-progress strips animation not adjusted to bar animation

### ISSUE THREAD

**Issue by alex9849** [quasarframework/quasar#11374]
**Describe the bug**
When changing the value of the q-linear-progress-component with enabled stripes, the stripe-moving animation is shorter than the animation of the colored bar.

Codepen:
https://codepen.io/alex9849/pen/JjywPZP

**To Reproduce**
1. Go to create a component with q-linear-progress and add the stripe option
2. Change the value
3. https://codepen.io/alex9849/pen/JjywPZP

**Expected behavior**
Stripes should move in synchrony with the colored bar

**Platform**
Quasar Version: v3.2.2
@quasar/app Version:

Quasar mode:
  - [ X ] SPA

Tested on:
  - [ X ] SPA

Browsers: Firefox 94.0.1

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.3.
