### ISSUE TITLE
Changing the position of files

### ISSUE THREAD

**Issue by Saravanan-TeslaTuring** [quasarframework/quasar#11377]
### Discussed in https://github.com/quasarframework/quasar/discussions/11376

<div type='discussions-op-text'>

<sup>Originally posted by **Saravanan-TeslaTuring** November 17, 2021</sup>
Hi,
I am new to Quasar. We are looking to change the structure of files. Like I want to move the CSS to the assets folder. I can add the path for app.scss but where I should need to change the path for quasar.variables.scss

![image](https://user-images.githubusercontent.com/67113322/142139302-209c9787-bb6d-4f35-85e4-12f9a29765b0.png)
</div>

**Comment by rstoenescu** [comment]
Creating a ticket AND also a Discussion with same thing is not helpful. It just clutters our Github...
Unfortunately, we do not support such customization. However, css/app.scss can even be deleted or moved elsewhere as long as the quasar.conf.js > css is changed appropriately (referring to the path).

**Comment by Saravanan-TeslaTuring** [comment]
Ok Sorry and thanks
