### ISSUE TITLE
[Feature Request] Add iconColor in q-collapsible

### ISSUE THREAD

**Issue by BlackMix** [quasarframework/quasar#1137]
I would very much like to be able to change the
icon color in q-collapsible..

I think this would be very good for many people too :)

**Comment by leonardoEbert** [comment]
Agreed, this will be a very useful feature

**Comment by rstoenescu** [comment]
@leonardoEbert http://quasar-framework.org/components/collapsible.html#Custom-Header

**Comment by leonardoEbert** [comment]
Thanks @rstoenescu, i haven't seen It when i was reading the documentário...

**Comment by leonardoEbert** [comment]
*Documentation, i'm answering with my smartphone and it translated to Brazilian portuguese

**Comment by profalves** [comment]
and for version 0.14, have any solutions?
