### ISSUE TITLE
update "@quasar/app": "3.1.9" after ,   quasar dev -m ssr error

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#11379]
update "@quasar/app": "3.1.9" after ,   quasar dev -m ssr

[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
[Vue warn]: resolveComponent can only be used in render() or setup().
[Quasar Dev Webserver] /mobile/ -> error during render
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/panhezeng/Workspace/moocnd-wechat-ssr/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2654:15)

Parameter 'options' implicitly has an 'any' type.
 async preFetch(options) {

Should be upgraded vue@3.2.21  reason

rollback  @quasar/app 3.1.8 ok

**Comment by rstoenescu** [comment]
Vue has been upgraded to v3.2.22 in "@quasar/app" v3.2.3
