### ISSUE TITLE
QFooter and QHeader are always fixed when using containerized QLayout.

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#11397]
**Describe the bug**
When using a QLayout in containerized mode it is currently not possible to have the footer not 'fixed' at the bottom. I would like to have the footer be part of the page, so only visible when you have scrolled all the way down. 

Only options currently are having it `fixed` or using the `reveal` proptery of the footer. The same thing applies to the header, there that option is also not available when using containerized layouts.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Mett-codepens/pen/GRvzyzL?editors=101

**To Reproduce**
1. Notice  the small 'f' in the layoutView. This normally indicates if you want your footer fixed or not.
2. Scroll down and see that footer is always fixed.

**Expected behavior**
Footer (and header) should scroll in and out of view with the rest of the page content.

I created a PR to fix this issue: #11369 

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.3.2
@quasar/app Version: 

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Additional context**

**Comment by rstoenescu** [comment]
This is on purpose, but honestly I can't remember the reason.

This should be tested on a page with multiple QLayout view configurations (including "funky" ones like "lhh LpR ffr" but not limited to) and on:
* Desktop Chrome / FF / Safari
* Mobile browser Chrome / FF / Safari
* Cordova app Android / iOS
* Capacitor app Android / iOS
* PWA (after installing it and launching it): iOS (especially), Android
* Electron

Cannot merge the PR until these tests are done.
