### ISSUE TITLE
$q.screen gt and lt seems wrong

### ISSUE THREAD

**Issue by amitgur** [quasarframework/quasar#11406]
**Describe the bug**
When sceen size is 990px, $q.sceeen.gt.sm is false and $q.screen.lt.sm is false (the last should be true)

**Codepen/jsFiddle/Codesandbox (required)**
[Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.](https://codepen.io/amitgur/pen/yLowegB)

**To Reproduce**
1. https://codepen.io/amitgur/pen/yLowegB
2. Click on "CONSOLE SCREEN"
3. See the lt and gt flags for that size

**Expected behavior**
One should be true (lt) and one should be false (gt)

**Screenshots**

**Platform (please complete the following information):**
![quasar_bug](https://user-images.githubusercontent.com/4021701/142603563-092a5b06-3315-4956-ac93-5ab024c17521.png)

Quasar Version:2.3.2
@quasar/app Version:

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu
Node:14.16.1
NPM: 7.20.3
Yarn:1.22
Browsers:Chrome and FF
iOS:
Android:
Electron:

**Additional context**

**Comment by MilosPaunovic** [comment]
Breakpoints [documentation](https://quasar.dev/style/breakpoints#introduction) says:

Window Size | Name | Width treshhold in pixels
-- | -- | --
Extra Small | xs | Up to 599px
Small | sm | Up to 1023px
Medium | md | Up to 1439px

And your code prints :
```js
$q.notify(`width ${document.body.clientWidth} lt.sm ${$q.screen.lt.sm} gt.sm ${$q.screen.gt.sm}`  )
```

If my math is correct, `990px` is neither in the smaller `xs` nor larger `md` catgory, it falls just right into `sm`, so I woud say it prints out correct values.

**Comment by amitgur** [comment]
I guess I don't understand the declaration. 
lt.sm is lower than sm=1023, so 900 should give true. Where is my mistake?

**Comment by MilosPaunovic** [comment]
Take a look at [this](https://quasar.dev/style/visibility#window-width-related).

`sm` breakpoint is between `xs` and `md`, meaning `sm` is between 600 and 1023 pixels. So `lt.sm` will be true if the width is less than 600px.

**Comment by pdanpdan** [comment]
Lt and gt on the same breakpoint are not the opposite of each other.
The opposites are gt a breakpoint and lt the next greater breakpoint.

**Comment by amitgur** [comment]
I think what's confusing here is the document statement 

sm Up to 1023px

When the meaning here is 

sm Between 599px - 1023px

Then speaking about lower than sm and greater than sm will have the meaning you pointed out.

**Comment by rstoenescu** [comment]
@amitgur Thanks for taking the time to PR the docs on this one! Much appreciate it.
