### ISSUE TITLE
In the Dev-server accept . (dots) in the URL for a specific routes

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1141]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: v8.9.1
NPM: 5.5.1
Browsers: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Cannot GET /reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OWE2MDI2MWEwOGFjMjM5NzE1YzU4YjYiLCJhY2Nlc3MiOiJmb3Jnb3RQYXNzd29yZCIsImlhdCI6MTUxMDc4ODU0NSwiZXhwIjoxNTEwODE3MzQ1fQ.sp4cc7K4KYocClZ652R47nAfU7pmuY-LPfpMA_gIpvM
### What were you expecting?
I expect to be able to set some roles for the dev server to allow the dots in the URL for specific routes. I use JWT in the reset password URL that sends to the user's email address.
### What steps did you take, to get the error?
Just take the URL put it in the browser address bar and hit enter(here I'm talking about the dev server http://localhost:8080).

What I'm doing in my other Vue projects is putting this:

```
// handle fallback for HTML5 history API
app.use(require('connect-history-api-fallback')({
  // disableDotRule: true,
  // verbose: true,
  rewrites: [
      {
          from: /^\/reset-password\/.*$/,
          to: '/'
      }
  ]
}))
```

In build/dev-server.js file but I was not able to find this file in the build folder.

**Comment by rstoenescu** [comment]
Hi,

Would you be so kind to redirect this issue to the [default starter kit repo](https://github.com/quasarframework/quasar-template-default) pls? This has to do with it rather than Quasar itself. Many thanks!

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu done with pleasure https://github.com/quasarframework/quasar-template-default/issues/51
