### ISSUE TITLE
QTable: slot 'top-selection' not working

### ISSUE THREAD

**Issue by mrabczuk** [quasarframework/quasar#11413]
**Describe the bug**
QTable slot 'top-selection' is not working.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/5nurg1ja/

**To Reproduce**
1. Select any row
2. See error: slot 'top-selection' is not shown

**Expected behavior**
After selecting a row, content of slot 'top-selection' should be shown.

**Platform (please complete the following information):**
Quasar Version: 2.1.9
@quasar/app Version: 3.1.5

Quasar mode:
  - [X ] SPA

Tested on:
  - [ X] SPA

**Additional context**
The error is caused by a typo (vaue instead of value) here:
https://github.com/quasarframework/quasar/blob/e825f0466a1150ab47579439e3bc5444eea43dd4/ui/src/components/table/QTable.js#L565

**Comment by rstoenescu** [comment]
A PR would have been wonderful, but thanks for reporting!
Fix will be available in Quasar v2.3.4
