### ISSUE TITLE
Q-Input clearable doesn't work if v-model has trim

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#11423]
**Describe the bug**
Simple q-input with clearable and v-model.trim

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dariodepaolis/pen/NWvJeao

**To Reproduce**
Create a q-input with clearable, set a vmodel.trim then tap on the icon

**Platform (please complete the following information):**
Quasar Version: v2.3.1

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by MilosPaunovic** [comment]
Duplicate #10376

**Comment by hawkeye64** [comment]
It's because Vue's `trim` doesn't check for null. It's expecting a string. You can raise an issue against Vue or use `update:model-value` and provide your own check for null and trim.

**Comment by dariodepaolis** [comment]
Ok thank you, I've noticed this, I opened a bug only because it worked on Qv1, just this ;)

**Comment by hawkeye64** [comment]
We can't fix this from Quasar side as it'd introduce a breaking change.

**Comment by dariodepaolis** [comment]
No problem I understand and thank you for the answer!

**Comment by qxygene** [comment]
any update on this?

**Comment by pdanpdan** [comment]
@qxygene interesting, your very helpful multiple contribution missed the only place where there was an update
https://github.com/quasarframework/quasar/issues/10376#issuecomment-1108320740
