### ISSUE TITLE
"Cannot convert undefined or null to object" at installQuasar

### ISSUE THREAD

**Issue by rimijn** [quasarframework/quasar#11424]
Application uses vue3 + ts + quasar and jest for testing. Getting error "Cannot convert undefined or null to object" at installQuasar when doing localVue.use(Quasar) or plugins: [Quasar] in test file. The config files are as mentioned below

**package.json -** 
```json
"dependencies": {
    "@quasar/extras": "^1.11.4",
    "@types/vue-i18n": "^7.0.0",
    "axios": "^0.20.0",
    "core-js": "^3.6.5",
    "d3": "^6.2.0",
    "echarts": "^5.1.2",
    "lodash": "~4.17.20",
    "qs": "^6.9.6",
    "quasar": "^2.2.1",
    "rison": "^0.1.1",
    "vue": "3.0.6",
    "vue-i18n": "^9.1.5",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@types/d3": "^5.16.3",
    "@types/echarts": "^4.9.8",
    "@types/lodash": "^4.14.160",
    "@types/node": "^14.17.32",
    "@types/rison": "0.0.6",
    "@types/webpack-env": "^1.16.3",
    "@typescript-eslint/eslint-plugin": "^5.3.1",
    "@typescript-eslint/parser": "^5.3.1",
    "@vue/cli-plugin-babel": "^4.5.14",
    "@vue/cli-plugin-eslint": "^4.5.14",
    "@vue/cli-plugin-router": "^4.5.14",
    "@vue/cli-plugin-typescript": "^4.5.14",
    "@vue/cli-plugin-unit-jest": "^4.5.15",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^9.0.1",
    "@vue/test-utils": "^2.0.0-0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-plugin-transform-imports": "2.0.0",
    "eslint": "^7.0.0",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^7.0.0",
    "node-sass": "4.13.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3",
    "vue-cli-plugin-quasar": "~4.0.4",
    "vue-jest": "^5.0.0-0"
  }
```

**jest.config.js -** 
```js
module.exports = {
  preset: "@vue/cli-plugin-unit-jest/presets/typescript-and-babel",
  transformIgnorePatterns: ["node_modules/(?!(quasar|echarts|zrender)/)"],
  transform: {
    // process *.vue files with vue-jest
    '^.+\\.vue$': require.resolve('vue-jest'),
  }
};
```

**babel.config.js -** 
```js
module.exports = {
  presets: ["@vue/cli-plugin-babel/preset"]
};
```

**test file assets.spec.ts-** 
```js
import { Quasar } from "quasar";
import { createApp } from "vue";

const localVue = createApp({});
localVue.use(Quasar);
```
**Error**
```
 Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at Function.assign (<anonymous>)

      4 |
      5 | const localVue = createApp({});
    > 6 | localVue.use(Quasar);
        |          ^
      7 |

      at installQuasar (node_modules/quasar/dist/quasar.cjs.prod.js:6:13539)
      at Object.install (node_modules/quasar/dist/quasar.cjs.prod.js:6:468377)
      at Object.use (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2962:28)
      at Object.<anonymous> (tests/unit/assets.spec.ts:6:10)
```

**Comment by DanieloFleming** [comment]
I had the same issue, but this seems to be a bug in quasar. i am using "quasar": "^2.4.10" and got:

```    
at installQuasar (@node_modules/quasar/dist/quasar.cjs.prod.js:6:13696)
...
```

after going to the source i saw 2 things.
1. line 13696: `var installQuasar = function (e, t = {}, o) {...` It seemed to me like `o` was missing a default value `{}`;
i change it to `var installQuasar = function (e, t = {}, o = {}) {...`  and go the next error
```
TypeError: Cannot read property 'headers' of undefined
    at Object.parseSSR (@node_modules/quasar/dist/quasar.cjs.prod.js:6:2652)
    ...
```
going over there i saw:
2. line 2652: `const t = e.req.headers["user-agent"] || e.req.headers["User-Agent"] || "";` it seemed to me like `req` could be undefined so i changed it to `const t = e.req?.headers["user-agent"] || e.req?.headers["User-Agent"] || "";`

After this change the errors where gone and jest was all green.

I haven't really checked why it's going wrong, but maybe this information helps with the bugfix
---
edit

1st issue:
in `@node_modules/quasar/dist/quasar.umd.js` on line 1454

2nd issue:
in `node_modules/quasar/src/plugins/Platform.js` on line 321

**Comment by yusufkandemir** [comment]
https://next.vue-test-utils.vuejs.org/migration/#no-more-createlocalvue
> For most cases where you would previously use `createLocalVue` and the `localVue` mounting option to install a plugin, mixin, or directive, you now use the [`global` mounting option](https://next.vue-test-utils.vuejs.org/api/#global-components). Here is an example of a component and test that used `localVue`, and how it now looks (using `global.plugins`, since Vuex is a plugin):
...

Some stuff got updated in `@vue/test-utils`, and `@quasar/testing-unit-jest` provides [`installQuasarPlugin(options)`](https://github.com/quasarframework/quasar-testing/tree/next/packages/unit-jest#installquasarpluginoptions) for handling the initialization stuff correctly.

@rimijn is using `@quasar/app` which is the local Quasar App CLI but also seem to be using Vue CLI stuff, and @DanieloFleming didn't state anything that might help, so we can't really know which flavor of Quasar you are using, if you are using TS or not, etc. But, if you aren't using Quasar CLI, you can't use App Extensions. So, you must handle your Jest and Babel configuration on your own, and it really matters. So, I would recommend taking a look at these configuration files and giving them a try on your own projects:
https://github.com/quasarframework/quasar-testing/blob/next/packages/unit-jest/src/templates/
IIRC, specifically using the ESM version of Quasar is really important, because that's what gets used on the browser environment after all.

/cc @IlCallo

**Comment by IlCallo** [comment]
Correct, CJS exported version is optimized for SSR, so it will give you all kind of weird issues while testing
You need to add these lines to your jest config to use and transform the ESM build version:
- https://github.com/quasarframework/quasar-testing/blob/5a761b2d8f25656d09d237a525e96cf60e5401ae/packages/unit-jest/src/templates/typescript/jest.config.js#L1
- https://github.com/quasarframework/quasar-testing/blob/5a761b2d8f25656d09d237a525e96cf60e5401ae/packages/unit-jest/src/templates/typescript/jest.config.js#L56
- https://github.com/quasarframework/quasar-testing/blob/5a761b2d8f25656d09d237a525e96cf60e5401ae/packages/unit-jest/src/templates/typescript/jest.config.js#L79

Also take a look to https://github.com/quasarframework/quasar-testing/blob/5a761b2d8f25656d09d237a525e96cf60e5401ae/packages/unit-jest/src/helpers/install-quasar-plugin.ts#L6 implementation and usage, as Yusuf correctly pointed out.

**Comment by DanieloFleming** [comment]
@yusufkandemir First of all thank you for the feedback.

Fair enough. I am in deed not using the quasar/Vue cli, but vite with typescript. 

i simply added this to my `setupFilesAfterEnv` in `jest.config.js`
```
import { config } from '@vue/test-utils';
import {Quasar} from 'quasar';

config.global.plugins.push([Quasar, {}]);
```
i now see the `installQuasarPlugin` is basically doing the same, but probably more effective.
my jest.config is nothing more then this:
```  testEnvironment: "jsdom",
  testMatch: ["**/src/**/*.test.js"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  preset: 'ts-jest',
  modulePaths: ["<rootDir>/node_modules"],
  moduleFileExtensions: ["js", "json", "vue", "ts"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^.+\\.(css|less|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub",
  },
  transform: {
    "^.+\\.js$": "babel-jest",
    "^.+\\.vue$": "@vue/vue3-jest"
  },
  "transformIgnorePatterns": [
    "<rootDir>/node_modules/(?!lodash-es/.*)"
  ],
  ```


Ill take a look at the provided solutions to see if it makes a difference. But still it would be awesome if the non quasar/VueCLi version for testing quasar in jest or any popular framework could be documented on the website. It's not always viable to replace a setup with the quasar/vue cli.

**Comment by IlCallo** [comment]
We'd love that, even if we currently don't have much time to work on it
If you find a solution in the meantime, please report back here

**Comment by ParsonsProjects** [comment]
Hi All,

I was having a similar issue using Vue CLI and Quasar I manged to resolve it with the below jest config.

```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest/presets/typescript-and-babel',
  transform: {
    '^.+\\.mjs$': 'babel-jest',
    '^.+\\.js$': 'babel-jest',
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
  },
  globals: { useHead: () => ({}) },
  setupFiles: ['<rootDir>/tests/unit/setup.ts'],
  testPathIgnorePatterns: [
    '<rootDir>/build/',
    '<rootDir>/node_modules/',
  ],
  moduleNameMapper: {
    '^quasar$': 'quasar/dist/quasar.esm.prod.js',
  },
  transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!quasar|vue-router)',
  ],
  testMatch: [
    '**/tests/unit/**/*.spec.(js|jsx|ts|tsx)',
    '**/__tests__/*.spec.(js|jsx|ts|tsx)',
  ],
  collectCoverageFrom: [
    '**/*.{js,jsx,ts,vue}',
    '!**/*.cy.{js,jsx,ts,vue}',
    '!**/node_modules/**',
    '!**/vendor/**',
  ],
};
```

The only additional bit I had to add was the below snippet
```
moduleNameMapper: {
  '^quasar$': 'quasar/dist/quasar.esm.prod.js',
},
```

**Comment by yusufkandemir** [comment]
Here is a solution that is based on a Vite setup: https://github.com/quasarframework/quasar/discussions/12177#discussioncomment-2046577.

I am hoping to create an example repo and write a tutorial/article about Vue CLI and Vite setups.

**Comment by cyril2day** [comment]
I had this same problem with Vue 3 + Quasar 2.6.5 + Vitest. 

This solved for me: https://github.com/quasarframework/quasar-testing/blob/5a761b2d8f25656d09d237a525e96cf60e5401ae/packages/unit-jest/src/helpers/install-quasar-plugin.ts

In addition, instead of this:

```ts
import { Quasar, QuasarPluginOptions } from 'quasar'
```

I did like:

```ts
// @ts-ignore
import { Quasar, QuasarPluginOptions } from 'quasar/dist/quasar.esm.prod'
```

EDIT:
@ts-ignore can be eliminated by creating module declaration like:
```ts
declare module 'quasar/dist/quasar.esm.prod' {
  import { Quasar, QuasarPluginOptions } from 'quasar'

  export { Quasar, QuasarPluginOptions }
}

```

[my repo](https://github.com/cyril2day/endeavor-admin-template/tree/master/src)
