### ISSUE TITLE
Incorrect arrow icons when useing RTL with QDatetime

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1143]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: v8.9.1
NPM: 5.5.1
Browsers: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
No error
### What were you expecting?
I expect to see the icons like <> but instead, the icons became ><
### What steps did you take, to get the error?
I just used the CSS property direction: rtl; on the wrapper div then the QDatetime arrow icons became >< and they must become <>
We need a way to change these icons, I've already created [this PR](https://github.com/quasarframework/quasar/pull/1139) regarding this.

**Comment by rstoenescu** [comment]
Available in 0.15.5
