### ISSUE TITLE
rtl css not compatible with devextreme dxdatagrid

### ISSUE THREAD

**Issue by mbtolou** [quasarframework/quasar#11446]
I created a repository to test the dxdatagrid

There was no way I could match the dxdatagrid and the rtlcss.
Can you help me solve the problem?

https://github.com/mbtolou/devextreme_rtlcss

**Comment by metalsadman** [comment]
use the discussions for questions or asking for help. thx.

**Comment by mbtolou** [comment]
asking for help

**Comment by hawkeye64** [comment]
> asking for help

Yes, but this is in Issues. Please use the [Discussions](https://github.com/quasarframework/quasar/discussions) or the [Discord](https://chat.quasar.dev/) server.

**Comment by mbtolou** [comment]
> > asking for help
> 
> Yes, but this is in Issues. Please use the [Discussions](https://github.com/quasarframework/quasar/discussions) or the [Discord](https://chat.quasar.dev/) server.

https://github.com/quasarframework/quasar/discussions/11447

i open issue.
can you help me ?
