### ISSUE TITLE
QPagiantion prop 'active-color' doesn't work for bounary number links when ellipses are visible

### ISSUE THREAD

**Issue by maddogcz** [quasarframework/quasar#11440]
**Describe the bug**
'active-color' color property don't apply to boundary number links when ellipses are visible

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/maddogcz/pen/NWvmEVX

**To Reproduce**
1. click on any non-boundary link, the color will change to what it should be

**Expected behavior**
active-color property will work independently to max-pages

**Platform (please complete the following information):**
Quasar Version: v2.3.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04.3
Node: v10.19.0
NPM: 7.20.2

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.5
