### ISSUE TITLE
QSelect hide-selected hiding the selected items in the input textbox instead of hiding in the dropdown list

### ISSUE THREAD

**Issue by SujanKumarK** [quasarframework/quasar#11454]
**To Reproduce**
select any demo code in document and add hide-selected attribute.

**Expected behavior**
Selected items to be displayed in text box and hidden in dropdown list box.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: v2.3.1
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows-10
Node: v14.18.0
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
:)
It does the right/expected/desired thing.

**Comment by SujanKumarK** [comment]
Please check codepen https://codepen.io/sujan_kolli/pen/OJjeNKe?editors=101
It is not working

**Comment by metalsadman** [comment]
it's in the docs 
![image](https://user-images.githubusercontent.com/31038838/143667991-1f50cc88-6cfb-4c8f-8fff-ce0347a7041f.png)
it's not suppose to do what you've stated in your title.

**Comment by SujanKumarK** [comment]
@metalsadman. Thanks for your reply. Sorry for understanding the functionality in reverse.
