### ISSUE TITLE
[vite-plugin] auto import component not works with pug

### ISSUE THREAD

**Issue by alphaelf** [quasarframework/quasar#11455]
hi,
it seems auto-import mechanism not works with pug templates

**Comment by theosherman** [comment]
So it appears. I would like to back this up with a stackblitz reproduction.

https://stackblitz.com/edit/vitejs-vite-19mefe

Checking the devtools console after running `npm run dev` in the stackblitz terminal will show the following warning...
`[Vue warn]: Failed to resolve component: q-spinner`

Would love to have support for this. But in the meantime, thank you for providing vite support! It has been an absolute pleasure working with vite and quasar.

**Comment by rstoenescu** [comment]
Hi,

I can't reproduce it on the stackblitz.com link. Downloaded the project, installed deps, ran yarn dev. Still can't reproduce it.
Please offer more details.

Also, please pin "sass" to v1.32.0. Do not install latest because you will get numerous warnings --- they changed something and we can't use their new syntax without making breaking changes. So pinning the Sass version is required.

**Comment by rstoenescu** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/4665641/145226112-f1cc44b7-57d6-431b-b07d-63df0d7d2e93.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/4665641/145226193-48d73101-a327-4419-afe9-36760347740d.png">

**Comment by theosherman** [comment]
> Hi,
> 
> I can't reproduce it on the stackblitz.com link. Downloaded the project, installed deps, ran yarn dev. Still can't reproduce it. Please offer more details.

My apologies @rstoenescu . I had manually imported QSpinner to verify that it works, and I forgot to comment the line.

pug.vue
```
<script setup lang="ts">
// import { QSpinner } from 'quasar';
</script>
```

You can re-try the stackblitz.

**Comment by rstoenescu** [comment]
Thank you for reporting and offering a reproduction repo.
Fix is available in "@quasar/vite-plugin" v1.0.3 -- just published it.

**Comment by rstoenescu** [comment]
Donations towards the framework are appreciated: https://donate.quasar.dev

**Comment by elali** [comment]
Hi, is this issue resolved in the "Quasar CLI with Vite" build? I am getting this error when creating a project with CLI and choosing vite.
