### ISSUE TITLE
Any change in server side code in ssr mode causing webpack dev server to return 404 response (with 200 status code) for incremental builds in dev mode 

### ISSUE THREAD

**Issue by dinesh-chander** [quasarframework/quasar#11457]
**Describe the bug**
If any blocking operation (or await for a promise/async operation) is performed in middleware, it causes the webpackdev server to return 404 for CSS and JS assets in successive requests.

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/dinesh-chander/quasar-ssr-blocking-bug

**To Reproduce**
1. Check the compression middleware
2. We are awaiting a async operation 
3. Run app and change any line in backend code which should trigger the compilation. Now load app again in browser. You will see
![image](https://user-images.githubusercontent.com/4879886/143227326-bec38f28-2a7b-41ff-9bb9-c0cd7a4727bb.png)

**Expected behavior**
Not sure if this is the expected behavior but webpack dev server should return correct response for assets in successive requests.

**Platform (please complete the following information):**
Quasar Version: 2.3.3
@quasar/app Version:  3.2.3

Quasar mode:
  - [x] SSR

Tested on:
  - [x] SSR

OS: Windows
Node: 16.11.1
NPM: 8.0.0
Browsers: chrome

**Comment by dinesh-chander** [comment]
This is happening without blocking code also. Create a new project and run it in SSR mode. Change code in ssr folder, it should trigger compilation. Now check the app in browser, you will find 404's in response with status code 200 for CSS and js assets

**Comment by dinesh-chander** [comment]
@rstoenescu Could you please have a look?

**Comment by sheldonbaker** [comment]
This has been happening to me too. It seems like any of the requests that 404 (for `vendor.js`, for example), are actually being treated as a full routing request (triggering boot files, etc.).

**Comment by dinesh-chander** [comment]
This has been fixed in one of the new releases. So closing this issue.
