### ISSUE TITLE
[Feature] Responsive menu (like collapsing navbar in bootstrap)

### ISSUE THREAD

**Issue by otabekgb** [quasarframework/quasar#1145]
I haven't seen something like this among the components.

**Comment by mstaack** [comment]
How about drawer & toolbar? I think you need to recheck docs;)

**Comment by otabekgb** [comment]
Can you nest submenu in toolbar, will toolbar collapse in mobile view

**Comment by bloodf** [comment]
You can make the same with PopOver. But the main design guides suggest the lateral menu as like an App Menu.
