### ISSUE TITLE
QSlider: Add min-value and max-value props in addition to min and max

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#11456]
**Is your feature request related to a problem? Please describe.**

I want slider to show interval form 0% to 100%.
However, I want selectable interval to be from 30% to 90%.

See screenshot:
![Scheme](https://user-images.githubusercontent.com/70687432/143223019-b68cc99c-a765-4d2d-9612-0a7bff407364.jpg)

The benefit:
Imagine that I change value from 35% to 45%.
With current slider it will look as a big change when the change is actually small.
With layout I suggest user will get correct impression about how big the change is.

**Describe the solution you'd like**

Add min-value and max-value props in addition to min and max.
min and max should determine showed interval.
min-value and max-value should determine selectable interval.

**Comment by rstoenescu** [comment]
New props for both QSlider and QRange will be available in Quasar v2.4.0: inner-min and inner-max
