### ISSUE TITLE
Quasar v2 usage with Docker

### ISSUE THREAD

**Issue by Karnith** [quasarframework/quasar#11465]
In order to get Quasar V2 file watcher to work with Docker, the quasar.config.js file needs to be updated with
```js
extendWebpack(cfg) {
  cfg.watchOptions = {
    aggregateTimeout: 200,
    poll: 1000,
  };
},
```
In webpack watchOptions is still available, so in order to get polling working in a Docker container, the watchOptions object needs to be added to the webpack config. The ```aggregateTimeout``` attribute is to add a delay for rebuilding. Webpack instructions found here https://webpack.js.org/configuration/watch/#watchoptions

**Comment by DengnisR** [comment]
hi-- this it for vite?--

```
extendWebpack(cfg) {
  cfg.watchOptions = {
    aggregateTimeout: 200,
    poll: 1000,
  };
},
```

i need make this for quasar with vite--
