### ISSUE TITLE
HMR try to reload many times when the eslint's warn and error occured together

### ISSUE THREAD

**Issue by naremloa** [quasarframework/quasar#11468]
**Describe the bug**
HMR try to reload too many times when the eslint's warn and error occured together

**To Reproduce**
1. Create new quasar project by using quasar-cli
2. code something like 'const error = "error"' to produce a eslint's error(no-unused-vars) 
3. code something like 'console.log("warn")' to product a eslint's warn(no-console)

**Expected behavior**
Stop building page and prompt a report with error and warn.
Page will not try to reload before i make any new changes.

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: mac OS Big Sur
Node: v14.17.5
NPM:
Yarn: 1.22.11
Browsers: Chrome
iOS:
Android:
Electron:

**Comment by Smrtnyk** [comment]
I have the same issue, eventually sometimes browser crashes

**Comment by rstoenescu** [comment]
This is an external issue in webpack-dev-server.
Should be fixed with the updated webpack-dev-server through "@quasar/app" v3.2.4
