### ISSUE TITLE
v-close-popup should close popup earlier

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#11469]
**Describe the bug**

Consider this sample:
https://codepen.io/ilyalyu/pen/wvqLROy
It has menu with two options: A and B.
Currently selected option is disabled: if you put mouse over it you will see red cursor.

If you click option B the following will happen:
1. Click action will be triggered that will select option B.
2. Option B becomes disabled and you see red cursor (undesired behavior).
3. Now v-close-popup does its job (Alas, too late) and closes popup.

Consider this manual fix:
https://codepen.io/ilyalyu/pen/WNEqLVg
I have added the following code to click action:
```ts
showMenu.value = false;
```
This solves the problem, however this solution implies manual fix and it polutes the code with "showMenu" ref.

I think that v-close-popup should close popup before my click action is called.

**Codepen/jsFiddle/Codesandbox (required)**

Bad behavior:
https://codepen.io/ilyalyu/pen/wvqLROy

Manual fix:
https://codepen.io/ilyalyu/pen/WNEqLVg

**To Reproduce**

Explained above

**Expected behavior**

v-close-popup should close popup before my click action is called to avoid flickering in a situation when click action disables menu item.

**Screenshots**

See codepen. Screenshot does not catch cursor.

**Platform (please complete the following information):**

Codepen.

**Additional context**

No.

**Comment by pdanpdan** [comment]
You can delay setting the selection
https://codepen.io/pdanpdan/pen/BadgEJZ?editors=1010

**Comment by iliubinskii** [comment]
I know that I can fix it in every place manually. I posted a link showing the fix in the original message:
https://codepen.io/ilyalyu/pen/WNEqLVg

But I think that good framework is the one where each component works out of the box without fixes and patches.

If it is possible for v-close-popup to act earlier it would eleminate the necesity to patch it in every place where you disable menu item. If not, still thx for great work.

**Comment by pdanpdan** [comment]
ClosePopup needs to execute in a setTimeout to allow the click to be processed by the component (the target of the click)
Else, if the close is instant, you'll end up with the menu closing and destroying the children components before they were able to process the click.

see here: https://github.com/quasarframework/quasar/issues/3795

**Comment by iliubinskii** [comment]
I don't know the internals of quasar framework, but I guess the following may work:

Option 1:

If the problem is in destroying menu item then v-close-popup may prevent menu from destroying. It can keep it alive.

Option 2:

1. Let's modify the code:
```vue
<q-item v-close-popup @click="...">
->
<q-item v-close-popup @clickclose="...">
```

2. Let's make v-close-popup trigger "clickclose" event (if q-item is destroyed then v-close-popup can cache "clickclose" handler and call it later).

Now "clickclose" event can be used by those who want and it will be triggered after popup is closed.

I am sure there should be some elegant solution.

**Comment by rstoenescu** [comment]
Both your options are not good.

Option 1 -> not destroying the menu means you end up with memory leak
Option 2 -> first, it means adding a breaking change (which is definitely a no-go); secondly, vue directives interfering with the host nodes and changing event behavior is again definitely a no-go due to the unpredictable behavior

A good framework approach is the one that we have, not trying to add overhead and unpredictable behavior.
Sorry but will not change the approach.
