### ISSUE TITLE
QAvatar component using slot and icon 'img' prefix

### ISSUE THREAD

**Issue by Mr-Geneo** [quasarframework/quasar#11470]
**Describe the bug**
The QAvatar component using slot and icon, the presentation content is not uniform

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mr-geneo/pen/abygXVm

**Expected behavior**
After using the 'img' prefix, the font size should be the same as that of the slot

**Platform:**
Quasar Version:  v2.3.3
@quasar/app Version: v3.2.3

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/yLodwGo?editors=1010
