### ISSUE TITLE
electron remote api or renderer features can not use in quasar

### ISSUE THREAD

**Issue by lichnow** [quasarframework/quasar#1147]
electron remote api can not use in main.js and vue components.
```
// main.js
import webFrame from 'electron'

webFrame.setVisualZoomLevelLimits(1, 1)

```
when i change the webpack config `libraryTarget: 'commonjs2'`,`require('electron')` will work ,but many other features of electron must be configure of webpack and run script, because quasar framework will build spa page,this is really a large work.A perfect framework of vue and electron integration is [electron-vue](https://simulatedgreg.gitbooks.io),but the best model is development in quasar framework,and generator electron project.

The quasar have a plan to perfect integration `vue` and `electron` or integration `quasar` and `vue-electron`?

**Comment by rstoenescu** [comment]
Hi,

You will really like the new starter kit that's getting prepared for v0.15. Everything will be seamless, including your issue. One folder, one package.json, multiple build modes (spa, pwa, electron, cordova, ...).

For the current default starter kit, the short answer is: there are two types of electron integrations: a soft one and a deep one. You want the deep, which requires some tweaks to the starter kit. This will not be a problem in the new starter kit. Thanks for being patient for v0.15 and the new starter kit.

**Comment by lichnow** [comment]
@rstoenescu thanks for your work.our team's production's UI development by `vuetify`'s components + `quasarframework`' start kit. now for electron, I use `electron-vue` build for electron temporarily.hope and wait the `quasarframework v0.15`.

thx for your great work!
