### ISSUE TITLE
Enhance types for QSelect `onFilter` and `onNewValue`

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#11471]
**Is your feature request related to a problem? Please describe.**
The current types don't specify how the `doneFn` should look like, which can be improved.

**Describe the solution you'd like**
From:
```ts
onNewValue?: (inputValue: string, doneFn: Function) => void;
onFilter?: (inputValue: string, doneFn: Function, abortFn: Function) => void;
```
To:
```ts
onNewValue?: (inputValue: string, doneFn: (item?: any, mode?: "add" | "add-unique" | "toggle") => void) => void;
onFilter?: (inputValue: string, doneFn: (callbackFn: Function, afterFn: (ref: QSelect) => void) => void, abortFn: Function) => void;
```

**Comment by yusufkandemir** [comment]
Currently(_Quasar v2.3.3_), the types are like this:
```ts
onNewValue?: (
  inputValue: string,
  doneFn: (item?: any, mode?: "add" | "add-unique" | "toggle") => void
) => void;

onFilter?: (
  inputValue: string,
  doneFn: (
    callbackFn: () => void,
    afterFn?: (ref: LooseDictionary) => void
  ) => void,
  abortFn: () => void
) => void;
```
#11109 generated the function types themselves, and #11347 fixed the required logic. In your example, `afterFn` should be optional too.

So, the only improvement that can be made is to change `LooseDictionary` to `QSelect`. I had that in mind for some time, now created an issue to track it, see #11483. So, thanks for an implicit reminder 😅
