### ISSUE TITLE
Bug: QInput White box on iOS 15 (Quasar 1)

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#11480]
The bug which was fixed here on Quasar 2: https://github.com/quasarframework/quasar/issues/11167
Should be applied to Quasar v1
 
On iOS 15, my Quasar 1 app has a bunch of boxes with a white background
This is also evident when viewing the Quasar 1 Docs on iOS 15.

**Comment by rstoenescu** [comment]
Backported fix from Quasar v2 to v1.16.1 (and released it).
