### ISSUE TITLE
Type 'modelValue' of QSelectProps incomplete

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#11485]
**Describe the bug**
Currently with typescript it is not possible to have an object as modelValue as it is typed as:
`modelValue: number | string | any[] | null | undefined;`

**Codepen/jsFiddle/Codesandbox (required)**
This causes issues when using the QSelect like this:
https://codepen.io/Mett-codepens/pen/BadXZgj?editors=1010

**Expected behavior**
ModelValue should be typed to include Objects, like:
`modelValue: number | string | any[] | null | LooseDictionary |  undefined;`

**Platform (please complete the following information):**
Quasar Version: 2.3.3
@quasar/app Version: 3.2.3

**Comment by yusufkandemir** [comment]
`type` here also needs `"Object"`:
https://github.com/quasarframework/quasar/blob/174f15fd4d29788da9b31f2f9beb79c3baa97af9/ui/src/components/select/QSelect.json#L11

Can you PR it, please? Don't forget to check if the final generated types are correct after running `yarn build js types`, it will output the diff to console.

**Comment by Evertvdw** [comment]
Ok, will do!
