### ISSUE TITLE
Use correct types for component references

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#11483]
**Is your feature request related to a problem? Please describe.**
Objects that are references to component instances are typed as generic objects using `LooseDictionary`, which doesn't help when interacting with them.

**Describe the solution you'd like**
Those types should be shipped correctly as `QScrollArea`, `QSelect`, etc.

**Describe alternatives you've considered**
Casting them manually.

**Additional context**
In JSON API their `type` should be changed from `Object` to `Component` and `tsType` should contain the component type, e.g. `QSelect`.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v2.3.4
