### ISSUE TITLE
Bug: QSelect with use-input scrolling to top of page on mobile (Quasar 1)

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#11481]
I notice that this bug has been fixed on Quasar 2 however I cannot find a supporting bug report for this problem.

When using QSelect with the `use-input` prop on mobile, closing/exiting the QSelect will sometimes scroll to the top of the page.
This is evident in the Quasar 1 Docs (and the issue is also happening on my Quasar 1 app).
The bug is also very annoying on long pages as you're forced to scroll all the way back down.

Problem can be seen in the following video (second tab is the Quasar 2 docs):
Problem occurs on both Android and iOS

https://user-images.githubusercontent.com/13761766/143534145-82c0c6e7-d19f-4315-9ed7-378714c30bcb.mp4

**Comment by pdanpdan** [comment]
Can you please check here: https://pdanpdan.github.io/quasar-docs/vue-components/select#filtering-and-autocomplete
There are lots of fixes for iOS: https://github.com/pdanpdan/quasar/releases

**Comment by nicholaszuccarelli** [comment]
Yep, fixed on that version! Looks fantastic. Can't wait for it!

**Comment by pdanpdan** [comment]
I don't think the changes will end up in the official release, so if you need them:

In package.json replace (or add) quasar dependency with:
"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.16.0-beta.24"

Then do a yarn or npm install and start the app again.

Please report if you find something not working.

**Comment by nicholaszuccarelli** [comment]
How come you don't think the changes will become official? These seem like some quite important fixes.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.17.0
