### ISSUE TITLE
QBtnDropdown has prop `modelValue` required while it can be used without

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#11493]
**Describe the bug**
[QBtnDropdown API](https://quasar.dev/vue-components/button-dropdown#qbtndropdown-api) specifies model-value as required but the first example in there does not specify this. It seems to me that this prop should not be required as the component works fine without it. This causes TS issues with Volar when it is not supplied.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Mett-codepens/pen/dyzxKwV?editors=101

**Expected behavior**
Make `modelValue` not required in the API docs and types updated.

**Platform (please complete the following information):**
Quasar Version: 2.3.3
@quasar/app Version: 3.2.3

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.4.
