### ISSUE TITLE
QTree in dense mode and node without children

### ISSUE THREAD

**Issue by Junvary** [quasarframework/quasar#11498]
![20211127144005](https://user-images.githubusercontent.com/26101389/143671264-cd7923be-9060-4e22-956d-5360418470e2.png)
![20211127144055](https://user-images.githubusercontent.com/26101389/143671266-c7c4d64d-975a-4bd8-bd78-6e9bed20c5c3.png)
![20211127144120](https://user-images.githubusercontent.com/26101389/143671267-56626c55-b0bb-4dcd-a062-bd6b919bce6b.png)
![20211127144751](https://user-images.githubusercontent.com/26101389/143671431-a24e8e76-1bde-442e-b42f-2830a41b6f20.png)

**Comment by pdanpdan** [comment]
Please make a codepen

**Comment by Junvary** [comment]
> Please make a codepen

https://codepen.io/junvary/pen/mdMNNbN?editors=101

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.4
