### ISSUE TITLE
Make back button work on Popovers too

### ISSUE THREAD

**Issue by yeknava** [quasarframework/quasar#115]
Android back button didnt closed Select. instead it will change route.

**Comment by rstoenescu** [comment]
Normally this would not happen since changing routes means changing view components (pages) and the popovers are destroyed when switching to another page because they are part of the old page.
I'm interested in your particular case. Can you detail a little bit more please? Is popover part of your page view? Switching to another view has impact over the popover?, meaning if part of the page and route changes, then it should be destroyed. Please detail your case. Thanks!

**Comment by rstoenescu** [comment]
Ok, figured out on Gitter channel. This would be an enhancement. To add back button support for Popovers too.

**Comment by yeknava** [comment]
when select is in showing state back button functionality should close select instead of changing route.

**Comment by slayerjain** [comment]
I'll try this, but will need help getting started :D

**Comment by rstoenescu** [comment]
http://quasar-framework.org/guide/contributing.html

Needs to be more detailed, but it's a starting point. Fork Quasar and inspect `package.json` for npm scripts you can run. You'll need `npm run dev` to start a dev server, then go to "Popovers" button and click on it. Popover code is in `src/vue-components/popover`. Don't be discouraged if there's something you don't understand. I'm here to help! Thanks a lot for wanting to contribute!

**Comment by slayerjain** [comment]
I've understood the problem! any hint on how to implement this? :D

**Comment by rstoenescu** [comment]
You need to be very familiar with `window.history` object. Push state, replace state etc. It ain't the best example, but look at Modal and search for `window.history`.

**Comment by slayerjain** [comment]
checking it out!

**Comment by slayerjain** [comment]
I never tried vue.js framework. can you suggest a great to place to a feel of the framework?

**Comment by rstoenescu** [comment]
Best documentation is on the official website: http://vuejs.org

**Comment by slayerjain** [comment]
great! 💃

**Comment by rstoenescu** [comment]
Hi, unfortunately I've decided not to pursue with this enhancement. It adds a lot of issues and it's ridiculously hard to maintain over the time. Sorry but it's for the best.
