### ISSUE TITLE
QOptionGroup label slot types are wrong

### ISSUE THREAD

**Issue by lambda0xff** [quasarframework/quasar#11500]
**Describe the bug**

![Screenshot 2021-11-27 at 12 04 26](https://user-images.githubusercontent.com/38687176/143679410-8638f2e3-dcea-4f9b-b2bc-5f7fe2a91865.png)

using 'label-0' works

**Platform (please complete the following information):**
Quasar Version:3.2.3
@quasar/app Version: 3.2.3

Quasar mode:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [X ] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
autocomplete in neovim + volar

**Comment by rstoenescu** [comment]
Changes will be available in Quasar v2.3.5
