### ISSUE TITLE
Change options for DateUtils getDateDiff

### ISSUE THREAD

**Issue by susnux** [quasarframework/quasar#11509]
**Is your feature request related to a problem? Please describe.**
Only `getDateDiff` has other options as the other methods, so it is easy to get confused when to use e.g. `year` and when `years`.
Also the TypeScript interface is annoying by just being set to `string`, so if consolidating the options, you could simply use `DateUnitOptions` as type for the options argument.

**Describe the solution you'd like**
consolidating the options

**Describe alternatives you've considered**
Just adding correct types for `getDateDiff`.

**Additional context**
This would break the API, but is easy to fix.

**Comment by IlCallo** [comment]
Fixed in 766cc763f00d404f930798addc0216b694335350
Will be available into next release (2.4.3)
