### ISSUE TITLE
q-input type="time" error

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1150]
### Software version

Quasar: 0.14.7
OS: WIN10
Node: 6.10.2
NPM: 3.10.10
Browsers: Chrome 62, Firefox 57
iOS: not tested
Android: 5.1.1
Any other software related to your bug:

### What did you get as the error?
[Vue warn]: Invalid prop: custom validator check failed for prop "type".

### What were you expecting?
No error message appears

### What steps did you take, to get the error?
<q-input inverted float-label="Hour"   v-model="hh"  type="time" />

I know in docs there is not type="time", by the way is running very well.

But, there are the error message:
[Vue warn]: Invalid prop: custom validator check failed for prop "type".

Tanks

**Comment by rstoenescu** [comment]
Added "time" and "date" types. Beware that IE & Safari does NOT support it. You can also use QDatetime.
Available in edge and future v0.14.8
