### ISSUE TITLE
Popup edit doesn't update a value in the table when a virtual scroll enabled

### ISSUE THREAD

**Issue by ThisIsRex** [quasarframework/quasar#11504]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
https://codepen.io/rixojow151/pen/WNZexmr

**To Reproduce**
Edit the first column field. Value will be left unchanged. Then scroll to hide edited line, and then scroll back. The value will be changed.

**Expected behavior**
Instant value change

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.3.3
@quasar/app Version:

Quasar mode:
  - [+] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [+] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [+] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers: FF, Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
It is a pure happening that it updates when you scroll (and I would think it's a bug somewhere).
You are not using ref on rows, so they should not be reactive.
https://codepen.io/pdanpdan/pen/poWzEoe?editors=1010
