### ISSUE TITLE
Programmatic routing with quasar v2 and typescript

### ISSUE THREAD

**Issue by BrynBerkeley** [quasarframework/quasar#11519]
**Describe the bug**
When using the router instance to push routes to history. The URL updates but the router-view does not.

**To Reproduce**
1. New quasar project via CLI with: ESLint, Typescript, Axios, Vue-i18n
2. Add @click event to an element calling a function which will navigate
3. use router instance and create navigate function
```
setup(props) {
    let router: Router

    onMounted(async () => {
      try {
        router = await useRouter({})
      } catch(err) {

      }
    })
    const navigateToHome = async () => {
      const nav = await router.push('/home')
      console.log(nav)
    }
    return { navigateToHome };
  }
```

3. Click on element

**Expected behavior**
Router view should change as well as the URL

**Platform (please complete the following information):**
Quasar Version: 2.3.3
@quasar/app Version: 3.2.3

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [X] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [X] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux(5.13.0-21-generic) - linux/x64
Node: v12.22.5
NPM: 7.5.2
Yarn: 1.22.15
Browsers: Chrome

Am I misusing the route function found in 'src/router/' and if so how should it be used. Thanks in advance

**Comment by pdanpdan** [comment]
I don't know what are you doing there, but:

- `useRouter` is not returning a promise
- what is `useRouter({})` (the empty object) doing?
- last but not by far least - `useRouter` (like almost all `use...`) must by called synchronously right inside `setup()`

So in your case you end up with some router instance, nobody knows what instance :)

**Comment by BrynBerkeley** [comment]
I named the function poorly when I imported it, this is the `route` variable imported from src/routes/index.ts. The exported `route` variable is a function that expects a params object. To satisfy typescript I passed an empty object. However, I am lost as to how I am supposed to use this. It is not the useRouter function provided by vue-router.

Thanks for the quick reply :)

**Comment by pdanpdan** [comment]
Please make a reproduction (codesandbox) and ask for help in discussions.
As you can see what is shown in your code looks like a duck but it's not a duck so somebody has to see all code and understand.
