### ISSUE TITLE
quasar V2 SSR mode gzip failed

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar#11528]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. quasar create test
2. quasar mode add ssr, find quasar.conf.js file and change "gzip: true".
3. quasar build -m ssr
4. enter /dist/ssr run "node index.js" or "pm2 start index.js"
5. open http://localhost:3000 and open the devtool network page
6. you can see all the js and css files not gziped

![image](https://user-images.githubusercontent.com/11263870/144199816-00afa7f0-f06a-4b3c-8ebe-0487e9826550.png)
![image](https://user-images.githubusercontent.com/11263870/144199868-2787c2ce-dc2d-40ec-a3d0-4f79ebaa6427.png)
![image](https://user-images.githubusercontent.com/11263870/144199955-f8d42899-4475-4543-9e27-6aa1c39cc234.png)
![image](https://user-images.githubusercontent.com/11263870/144200061-0d16c127-c6a0-4908-b718-bc4639a0863f.png)
![image](https://user-images.githubusercontent.com/11263870/144200332-eacbfb02-b2aa-40dd-a796-4bbfdb9ecfbd.png)

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [ x ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ x ] Typescript
- [ x ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ x ] Standard (eslint)
  
Tested on:
  - [ ] SPA
  - [ x ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: windows and centos
Node: 16.13.0
NPM: 8.1.3
Yarn: 1.12.15
Browsers: chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
That option (gzip) is only for build - so for static SPA/PWA
When you use SSR you should use something in front (a reverse proxy) to:
- terminate SSL
- compress if you wish
- set cache policies
- route to different backends based on path
- load ballance

**But you have a point that the static resources should respect gzip even in SSR mode.**

**Comment by zknic** [comment]
> That option (gzip) is only for build - so for static SPA/PWA When you use SSR you should use something in front (a reverse proxy) to:
> 
> * terminate SSL
> * compress if you wish
> * set cache policies
> * route to different backends based on path
> * load ballance
> 
> But you have a point that the static resources should respect gzip even in SSR mode.

but it is correct in quasar v1

**Comment by pdanpdan** [comment]
Emphasized the part that agrees with you :)
The first part is just about what you should do to not depend on the server for things that can be better handled somewhere else.

**Comment by zknic** [comment]
> Emphasized the part that agrees with you :) The first part is just about what you should do to not depend on the server for things that can be better handled somewhere else.

i got it, for example: nginx should forwarding a static request to disk-files and  forwarding a dynamic request  to node-server.
