### ISSUE TITLE
Vue update to 3.2.23 , quasar build -m ssr error

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#11527]
vue update 3.2.23 , quasar build -m ssr error ?

Why did the quasar compile error report as soon as Vue was upgraded, and it was the same last time. Features
Upgraded Vue to v3.2.22 #11379 #10943

**Comment by panhezeng** [comment]
Now you must add "vue": "3.2.22" to the dependencies of your own project's package.json

**Comment by panhezeng** [comment]
ERROR in src/boot/lazy.ts:6:3
TS2321: Excessive stack depth comparing types '{ install(app: App<any>, options?: LazyloadOptions | undefined): void; }' and 'Plugin_2'.
     4 | export default boot(({ app, ssrContext }) => {
  >  6 |   app.use(Lazyload, {
       |   ^^^^^^^^^^^^^^^^^^^
  >  7 |     lazyComponent: true,
       | ^^^^^^^^^^^^^^^^^^^^^^^^


ERROR in src/layouts/Mobile.vue:50:18
TS7006: Parameter 'options' implicitly has an 'any' type.
 async preFetch(options) {

**Comment by Smrtnyk** [comment]
you updated vue dep manually?
if you are using quasar cli you should wait for quasar to update it, because they also test it and fix issues before shipping the new app with updated deps

**Comment by rstoenescu** [comment]
Please upgrade to "@quasar/app" v3.2.4.
It's not recommended to manually upgrade the vue version yourself.

**Comment by panhezeng** [comment]
I did not install vue by myself, but installed vuex, it should be an internal problem of vuex

```
  "homepage": "https://github.com/vuejs/vuex#readme",
  "peerDependencies": {
    "vue": "^3.0.2"
  },
```

**Comment by panhezeng** [comment]
> Please upgrade to "@quasar/app" v3.2.4. It's not recommended to manually upgrade the vue version yourself.

I did not install vue by myself, but installed vuex, it should be an internal problem of vuex
```
  "homepage": "https://github.com/vuejs/vuex#readme",
  "peerDependencies": {
    "vue": "^3.0.2"
  },
```

**Comment by panhezeng** [comment]
> you updated vue dep manually? if you are using quasar cli you should wait for quasar to update it, because they also test it and fix issues before shipping the new app with updated deps

Is there any way to completely lock the version that quasar can run normally? The current situation is that the priority of vuex seems to be higher than @quasar/app

**Comment by panhezeng** [comment]
In fact, not only vuex, but also other libraries, all have similar "peerDependencies": {
     "vue": "^3.0.0"
   }, the dependency statement

**Comment by Smrtnyk** [comment]
you shouldn't install vuex yourself
quasar installs it for you
remove vuex from your package.json

**Comment by rstoenescu** [comment]
@panhezeng That's really unfortunate. Will see what I can do. Thanks for the feedback!
