### ISSUE TITLE
typescript build error with i18n [Excessive stack depth comparing types] 

### ISSUE THREAD

**Issue by HibernantBear** [quasarframework/quasar#11526]
**Describe the bug**
use quasar with specified version blow, select typescript and i18n support, keep the work as it is and run 'quasar dev', you will see

 Dev mode.......... spa
 Pkg quasar........ v2.3.3
 Pkg @quasar/app... v3.2.3
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 89.37% of global marketshare):
 · Chrome for Android >= 96
 · Firefox for Android >= 94
 · Android >= 96
 · Chrome >= 87
 · Edge >= 93
 · Firefox >= 85
 · iOS >= 11.3-11.4
 · Opera >= 77
 · Safari >= 12.1

 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with success • 9828ms

 App •  READY  • Compiled: "UI"

 » App dir........... /home/hibernantbear/quasar2
 » App URL........... http://localhost:8080
                      http://172.29.67.217:8080
 » Dev mode.......... spa
 » Pkg quasar........ v2.3.3
 » Pkg @quasar/app... v3.2.3
 » Transpiled JS..... yes (Babel)

 App • Opening default browser at http://localhost:8080

 App • ⚠️  Failed to open default browser

ERROR in src/boot/i18n.ts:13:3
TS2321: Excessive stack depth comparing types 'I18n<{ 'en-US': { failed: string; success: string; }; }, unknown, unknown, true>' and 'Plugin_2'.
    11 |
    12 |   // Set i18n instance on app
  > 13 |   app.use(i18n);
       |   ^^^^^^^^^^^^^
    14 | });
    15 |

ERROR in src/boot/i18n.ts:13:11
TS2345: Argument of type 'I18n<{ 'en-US': { failed: string; success: string; }; }, unknown, unknown, true>' is not assignable to parameter of type 'Plugin_2'.
  Type 'I18n<{ 'en-US': { failed: string; success: string; }; }, unknown, unknown, true>' is not assignable to type '{ install: PluginInstallFunction; }'.
    Types of property 'install' are incompatible.
      Type '(app: App<any>, ...options: unknown[]) => void' is not assignable to type 'PluginInstallFunction'.
        Types of parameters 'app' and 'app' are incompatible.
          Type 'import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").App<any>' is not assignable to type 'import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").App<any>'.
            The types of 'config.errorHandler' are incompatible between these types.
              Type '((err: unknown, instance: import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").Comp...' is not assignable to type '((err: unknown, instance: import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentOptionsBase<any, any, any, any, any, any, any...'.
                Type '(err: unknown, instance: import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").Compo...' is not assignable to type '(err: unknown, instance: import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentOptionsBase<any, any, any, any, any, any, any,...'.
                  Types of parameters 'instance' and 'instance' are incompatible.
                    Type 'import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>> | null' is not assignable to type 'import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentOptionsBase<any, any,...'.
                      Type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>> | null'.
                        Type 'import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type 'import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentOptionsBase<any, any,...'.
                          Type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type '{ $: ComponentInternalInstance; $data: {}; $props: {}; $attrs: Data; $refs: Data; $slots: Readonly<InternalSlots>; $root: ComponentPublicInstance<...> | null; ... 6 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; }'.
                            The types of '$.type' are incompatible between these types.
                              Type 'import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ConcreteComponent<{}, any, any, import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/home/hibernantbear/quasar2/node_modules/@vue/runtime-core/dist/runtime-core").MethodO...' is not assignable to type 'import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ConcreteComponent<{}, any, any, import("/home/hibernantbear/quasar2/node_modules/@quasar/app/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/home/hibernantbear/quasar2/node_mod...'.
                                Type 'ComponentOptions<{}, any, any, ComputedOptions, MethodOptions, any, any, any>' is not assignable to type 'ConcreteComponent<{}, any, any, ComputedOptions, MethodOptions>'.
                                  Type 'ComponentOptions<{}, any, any, ComputedOptions, MethodOptions, any, any, any>' is not assignable to type 'FunctionalComponent<{}, any>'.
                                    Type 'ComponentOptionsBase<{}, any, any, ComputedOptions, MethodOptions, any, any, any, string, {}> & ThisType<any>' provides no match for the signature '(props: {}, ctx: Omit<SetupContext<any>, "expose">): any'.
    11 |
    12 |   // Set i18n instance on app
  > 13 |   app.use(i18n);
       |           ^^^^
    14 | });
    15 |

 quasar info excute output blow:

Operating System - Linux(4.19.104-microsoft-standard) - linux/x64
NodeJs - 16.13.0

Global packages
  NPM - 8.1.4
  yarn - Not installed
  @quasar/cli - 1.2.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.3.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.2.3 -- Quasar Framework local CLI
  @quasar/extras - 1.12.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.23 -- The progressive JavaScript framework for buiding modern web UI.
  vue-router - 4.0.12
  vuex - 4.0.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.0 -- Babel compiler core.
  webpack - 5.64.4 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.4.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.4.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - [masked]
  eth0 - [masked]

as I googled, it is typescript after version 4.3 limit defined check recursive depth, and seems i18n support just hit the goal

**Comment by Nigui** [comment]
same error for me ☹️

**Comment by yusufkandemir** [comment]
Using yarn should solve this problem, it's been discussed and tested on [our community Discord server](https://chat.quasar.dev). Please try removing `package-lock.json` and `node_modules`, then install the dependencies using `yarn` to see if it solves the problem.

**Comment by yusufkandemir** [comment]
It's also stated in https://github.com/intlify/vue-i18n-next/issues/795#issuecomment-981107414
