### ISSUE TITLE
Issues setting quasar.lang at runtime as described in the docs.

### ISSUE THREAD

**Issue by obi84** [quasarframework/quasar#11529]
**Describe the bug**
I cannot set the quasar lang as described in the docs. The import statement always throws an error and says the file (translation file) cannot be found. therefore the quasar.lang never gets set.

Also importing languages in the /src/boot/quasar-lang-pack.js will not work! remove try catch or log error in catch, otherwise you won't even see the error.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ObiRocks/pen/LYzELBy

**To Reproduce**
 - Create a new empty project
  - make a language select as described in the docs, (https://v1.quasar.dev/options/quasar-language-packs#dynamical-non-ssr-)
Select a language, and maybe remove the try catch block to actually see the error.

**Expected behavior**
Setting of quasar language, to alter components/labels/descriptions at runtime.

**Screenshots**

![error](https://user-images.githubusercontent.com/24891737/144202797-8caeaf39-574e-4c55-b5f7-243eb14d8b7f.png)

**Platform (please complete the following information):**
Quasar Version: 1.16.0
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [ ] PWA

Tested on:
  - [ ] SPA
  - [ ] SSR

OS: OSX
Node: 
NPM:
Yarn: latest
Browsers: Chrome, Safari
Android:

**Additional context**
Tried different paths to the quasar language file imports, but it will not work for me.

**Comment by pdanpdan** [comment]
Hello:
- I hope you do not expect it to work like this in codepen :)
- ```const path = `../quasar/lang/${isoLang}`;``` is wrong - you have an extra `../` in front
- https://v1.quasar.dev/options/quasar-language-packs#dynamical-non-ssr-

**Comment by obi84** [comment]
- I hope you do not expect it to work like this in codepen :)
No I didn't, but that's the requirement when creating an issue, isn't it?

as for the path, I tried it like you described, didn't work as well.

**Comment by obi84** [comment]
you can just create a completely new project to reproduce.
also: it doesn't work in the boot file as well.

**Comment by obi84** [comment]
@pdanpdan please reopen this issue, since it is not finished!
You can see in the screenshot of the error message that is doesn't work with `quasar/lang/${isoLang}` as well;

**Comment by yusufkandemir** [comment]
@obi84 
For Codepen, you need to use the UMD version, which is used differently, here are the instructions: https://v1.quasar.dev/options/quasar-language-packs#quasar-umd

But, if you are experiencing this issue with Quasar CLI, then you need to create a CodeSandbox by forking [this link](https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/tree/legacy-v1) to be able to reproduce it.

**Comment by obi84** [comment]
@yusufkandemir 
I am using Quasar CLI. 
I created a CodeSandbox as suggested, and tried to reproduce the error there, but was not able to do so. (On Codesandbox it worked as expected..).

I am therefore not sure what to do to convice you it is an error.. 
Locally, it always throws an error when trying to import a language from 'quasar/lang/'+whatever.. 
Might this be a file read problem?
A problem that only occurs when mode is development mode?


As I said, i experienced this problem with a fresh install of quasar at 1.6.0, but also with multiple other quasar projects that I try to update to this version. (always locally, in dev mode)

![Bildschirmfoto 2021-12-01 um 14 45 42](https://user-images.githubusercontent.com/24891737/144245947-81af673c-3cfd-4ce2-b0c3-105f8e27e875.png)

**Comment by MilosPaunovic** [comment]
Are you completely sure that the `path` you're trying to importfile from  is correct?

**Comment by obi84** [comment]
> Are you completely sure that the `path` you're trying to importfile from is correct?
pretty sure!

```
watch: {
    async lang(isoLang = 'de') {
      // dynamic import, so loading on demand only
      Quasar.lang.set(isoLang);
      const path = `quasar/lang/${isoLang}`;
      await import(
        /* webpackInclude: /(de|en-us)\.js$/ */
        path
      ).then((lang) => {
        Quasar.lang.set(lang.default);
      });
    },
  },
```

And as you can see in the error, it also confirms that.
(Cannot find module 'quasar/lang/en-us')

Also I used the exact same code for my local project as for the CodeSandbox. In the CodeSandbox it worked, so why not locally..?

**Comment by yusufkandemir** [comment]
This is what Quasar Docs suggest:
```js
await import(
  /* webpackInclude: /(de|en-us)\.js$/ */
  'quasar/lang/' + langIso
)
```
and this is what you are doing:
```js
const path = `quasar/lang/${isoLang}`;
await import(
  /* webpackInclude: /(de|en-us)\.js$/ */
  path
)
```

They might sound logically the same, but they are not. That's how webpack works, get rid of the `path` variable and use the string directly inside import, and you will see it will work.

> Also I used **the exact same code** for my local project as for the CodeSandbox. In the CodeSandbox it worked, so why not locally..?

I am 100% sure that **the exact same code** is not correct, because of that small but actually big difference.

So, please use this one:
```js
await import(
  /* webpackInclude: /(de|en-us)\.js$/ */
  'quasar/lang/' + langIso
)
```
or
```js
await import(
  /* webpackInclude: /(de|en-us)\.js$/ */
  `quasar/lang/${isoLang}`
)
```
so that webpack can analyze and bundle that.

> It is not possible to use a fully dynamic import statement, such as import(foo). Because foo could potentially be any path to any file in your system or project.

See: https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

**Comment by obi84** [comment]
> ```js
> `quasar/lang/${isoLang}`
> ```

Ok, I will try that. thank you very much for explaining.
The only reason i did extract the string into a "path" variable is because of ESLint telling me it has a problem with dynamic imports..

**Comment by hawkeye64** [comment]
Just a side note, but in quasar v2, something like `en-us` has become `en-US` for compliance with the standard.
