### ISSUE TITLE
Q-Loading - Counter for use-case where tasks execute may exec synchronously and asynchronously (e.g. Promise.all)

### ISSUE THREAD

**Issue by jimtendo** [quasarframework/quasar#11538]
**Is your feature request related to a problem? Please describe.**

Hi all, apologies if this has already been discussed (but couldn't see in Github issues).
Is there any interest in q-loading to use a counter system? Generally, when I write functions I wrap them like so:

```
methods: {
  async someFunc () {
    try {
      this.$q.loading.show()
      // other code
    } catch (err) {
      // catch err
    } finally {
      this.$q.loading.hide()
    }
  }
}
```

This works well - but if I have a mounted/created hook where I want to call these in a Promise.all:

```
async mounted () {
  await Promise.all(this.someFuncA(), someFuncB())
}
```

... the Promise that reaches finally first will remove the Loading indicator (despite the other functions still executing).

**Describe the solution you'd like**

If the Loading Component supported a param upon initialization like `useCounter: true` the show() function could incremement this counter and the hide() function could decrement and hide the loading indicator - if it's value is less than one. This approach should also be backwards compatible as the useCounter (or whatever) param could be set to false by default.

**Describe alternatives you've considered**

Alternative might be to have different functions than `show()` and `hide()`. For example, `increment()` and `decrement()` that leverage the counter specifically.

A Dev could also probably create their own class to wrap this functionality without too much difficulty (would still be nice OOTB imo though).

**Additional context**

Quick glance through the loader code, I don't think adding this would be "too bulky" (few LoC). I may've overlooked something though.

It would also mean that if dev's were to utilize this, they'd have to make sure that every `show()` call had a corresponding `hide()` call. I'm also not sure if the try/catch/finally pattern I use is how other dev's go about this.

**Comment by pdanpdan** [comment]
Use a wrapper for the promises:
https://codepen.io/pdanpdan/pen/LYzNMjG?editors=0010

It would be outside of the scope of the plugin to decide if you really want to show/hide it
