### ISSUE TITLE
Components not available to runtime compiler when using importStrategy: 'all' in quasar CLI

### ISSUE THREAD

**Issue by xlaussel** [quasarframework/quasar#11543]
**Describe the bug**
When using the runtime compiler in order to compile vue templates on the fly in the browser (with vueCompiler option set to true into the build section of the quasar.conf.js) with importStrategy: 'all' ,  the compiler cannot resolve the components. They must be registered one by one into the components option.

**Expected behavior**
All the quasar compponents should be available. Before the Quasar CLI I was using my own webpack conf. I was activating the Quasar plugin by calling app.use(Quasar) and after this call all the quasar components were available to the runtime compiler. 

**Platform (please complete the following information):**
Quasar Version: 2.3.3
@quasar/app Version: 3.2.3

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ ] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [X] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Debian Buster
Node: NA
NPM: 7.7.4
Yarn: 1.22.10
Browsers: Chrome

**Comment by hawkeye64** [comment]
https://github.com/quasarframework/quasar/issues/11455#issuecomment-985907013

**Comment by rstoenescu** [comment]
Hi,

There is no `importStrategy` anymore. Treeshaking Quasar is enabled by default.
You will have to manually import the components and feed them to your vue component (which uses the runtime compiler) or register them directly with your Vue app instance or add them to app.use(Quasar, { components: { ... } }).

**Comment by xlaussel** [comment]
> Hi,
> 
> There is no `importStrategy` anymore. Treeshaking Quasar is enabled by default. You will have to manually import the components and feed them to your vue component (which uses the runtime compiler) or register them directly with your Vue app instance or add them to app.use(Quasar, { components: { ... } }).

OK but note that I tried with app.use(Quasar) without specifying the components option and all the components where available to the runtime compiler
