### ISSUE TITLE
Uploader error when file name containing unicode character

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#11553]
with quasar uploader,
if user select turkish named file, uploading proggres is interrupted
and server response 400 error code.
regular named files no error

![image](https://user-images.githubusercontent.com/53820589/144619697-ff8246bf-cdbf-4332-ab11-9cbb2e9b91d2.png)

Chrome and safari no console error. firefox logs "xml parsing error root element not found"

**Comment by pdanpdan** [comment]
Please check the request in the inspector and fix your server
