### ISSUE TITLE
QExpansionItem: ability to remove the toggle icon without disabling component

### ISSUE THREAD

**Issue by lambda0xff** [quasarframework/quasar#11551]
A toggle icon is always displayed even when there's not content to show besides the header.

**Describe the solution you'd like**
A prop `display-toggle-icon: Boolean` to control the display of the toggle icon
Or a prop `hide-icon-when-empty` to automatically remove the icon when no content

**Describe alternatives you've considered**
`disabled` : is ok but applies an opacity styling

**Comment by pdanpdan** [comment]
Hello.
A QExpansionItem without content is a QItem.
Render a QItem in this case

**Comment by MilosPaunovic** [comment]
Or you could simply add a `expand-icon-class="invisible"` if, for some reason, you need it to be `QExpansionItem`.

**Comment by lambda0xff** [comment]
Ok thanks, I looks like `expand-icon-class="hidden"` is what I'm looking for.
