### ISSUE TITLE
Quasar and some Drupal web-site CSS conflict

### ISSUE THREAD

**Issue by kostyfisik** [quasarframework/quasar#11554]
**Describe the bug**
This has the same origin as #6775 
(it might be not only Drupal CMS problem, I'll check it with WordPress later on)

As you add ``` <div id="q-app"></div>``` to html block in web-site, there is a CSS conflict. The problem is two-fold:
1) Website styles randomly change Quasar styles.
2) Quasar randomly change styles of the website.

First is not pleasant, as soon as website can change styling (it is out of my control) my app style will be broken. So, I need to manually detect the problems and provide patches like 
```css
#q-app a {
    text-decoration: none;
}
```
to the `index.template.html` in quasar project to redefine some style back as they were originally set in Quasar.
Second is a problem, I don't see an easy way to solve it.  E.g. Quasar has
```css
.block { display: block !important }
```
which propagates out of the q-app div and breaks the website's design.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
As soon as it is a problem which happens during deployment to the styled website, see an example at https://physics.itmo.ru/ru/mie-next#/spectrum
The source of the webapp is available at https://github.com/ovidiopr/scattnlay/tree/ec48cf99faa04d47c012fe8a59b8e00bf5095d9c/guiapp 

See screenshot section for details.

**Expected behavior**
It would be nice to have an option to completely isolate Quasar styles.  So inserting  `<div id="q-app"></div>` to any page of any website 1) Should result in adding the same computed style of the webapp as in development 2) Should not affect the embedding website.

**Screenshots**
The original website header

![Screenshot from 2021-12-03 16-47-52](https://user-images.githubusercontent.com/5239997/144613330-df71c353-b1a2-4759-bac7-a78359402da0.png)

After adding Quasar webapp

![Screenshot from 2021-12-03 16-46-46](https://user-images.githubusercontent.com/5239997/144613335-2bdfe222-fbdd-441d-8ddb-25dc1422eaf7.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: v3.1.0

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [X] Typescript
- [ ] SFC usage with `<script setup>`
- [X] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux
Node: static files after build with 
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Hello.

Sorry, but this is adds nothing new to #6775

**Comment by kostyfisik** [comment]
@pdanpdan Sorry, but #6775 had a solution - using additional name convention for the external lib. It is not the case when you have access to a single page in CMS and related path to upload the build.... Any ideas how to fix it?

**Comment by pdanpdan** [comment]
Not really, sorry. You can try embedding the app in an iframe

**Comment by kostyfisik** [comment]
I've already tried this. As soon as my app reactively changes the size of the plot to fit it almost to the whole visible part of the windows, iframe is always coming with a scrollbar. At the moment I just
```bash
cd dist/spa/css
for file in `ls *.css`; do sed -i 's/[.]block{display:block\!important}//g' $file; done
```
For now, it works fine for my set of used Quasar components, not sure how it will go later on.

**Comment by pdanpdan** [comment]
https://github.com/davidjbradshaw/iframe-resizer

**Comment by kostyfisik** [comment]
Is my hack and iframe-resizer are worth mentioning in https://quasar.dev/quasar-cli/developing-spa/deploying#introduction ?
