### ISSUE TITLE
QLinearProgress: query state should travel in the opposite direction

### ISSUE THREAD

**Issue by sullyD64** [quasarframework/quasar#11566]
Opening this small issue as requested by @pdanpdan. There are no visual differences between the `query` and `indeterminate` props for QLinearProgress, but as Dan said `query` should go the opposite direction.

Posting no codepen since this can be seen in the docs: https://quasar.dev/vue-components/linear-progress#indeterminate-state

![immagine](https://user-images.githubusercontent.com/26333714/144867274-4a381455-ce51-43ff-bfef-ac1833103717.png)

**Platform (please complete the following information):**
Quasar Version: 
@quasar/app Version: 3.2.3

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.4
