### ISSUE TITLE
Add console warn message (or callback) when icon name is not found (Qv2!)

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#11567]
**Is your feature request related to a problem? Please describe.**
My problem is that I'm working on a large project with many different icons from many different sources.  In some cases it can be hard to detect if all q-icons will render as needed.  If, for instance, fontawesome 5 is not available, q-icons will fail silently today.

**Describe the solution you'd like**
A simple warning to the browswer console that a particular icon was not found would be helpful.  Even better: a call back function we can provide along side `iconMapFn` to capture "not found" instances.

**Describe alternatives you've considered**
No easy way to debug this today--hard to test everything with visual methods.

**Comment by rfox12** [comment]
As a side note here, I noticed that github automatically attached a "Qv1" tag when I selected "feature request" tag.  Couldn't see how to remove that.  I'm using Quasar v2.

**Comment by pdanpdan** [comment]
QIcon does not know and cannot know if the text/class of the icon will generate or not a visible icon.

**Comment by rfox12** [comment]
I sense your heartfelt empathy for my struggle here. :)  Apparently you've never had a missing icon issue. @pdanpdan let me ask another question... is there an easy way to have Quasar dump the "name="  field on every QIcon encountered at build time?

**Comment by pdanpdan** [comment]
You can use a custom iconMapFn that prints the name on the console and then return undefined
https://quasar.dev/vue-components/icon#custom-mapping
