### ISSUE TITLE
[Feature Request] Toolbar Menu or Menu and Sub Menu

### ISSUE THREAD

**Issue by donPuerto** [quasarframework/quasar#1156]
**Useful for desktop applications or probably in mobile.**

[Feature] Responsive menu (like collapsing navbar in bootstrap)
![image](https://user-images.githubusercontent.com/9329005/33017182-4c844f60-ce2c-11e7-9b8e-73a4af2c9019.png)

![image](https://user-images.githubusercontent.com/9329005/33017201-59f9092e-ce2c-11e7-905e-3402629a260d.png)

![image](https://user-images.githubusercontent.com/9329005/33017214-69868754-ce2c-11e7-939a-dd0c2c099bd6.png)

**Comment by rstoenescu** [comment]
But there's the QPopover for this... Am I missing something?

**Comment by donPuerto** [comment]
Sorry mate, just a new kid in town..
