### ISSUE TITLE
Router scrollBehavior to.hash is not working

### ISSUE THREAD

**Issue by kostyfisik** [quasarframework/quasar#11576]
**Describe the bug**
Router scrollBehavior with to.hash is not working

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Provided templates to don use Vue Router, which is needed to reproduce the bug

**To Reproduce**
1. Using Quasar CLI create new project with Vue Router and typescript  
2. Add 
```html
  <div>
      <div v-for='n in 100' :id="n" v-bind:key="n">{{n}} bar</div>
  </div>
```
to `src/pages/Index.vue` inside `q-page` tag

3. Change in `src/router/index.tx` in `createRouter` the `scrollBehavior` to
```js
    scrollBehavior: (to) => {
      if (to.hash) {
        return {
          selector: to.hash
          , offset: { x: 0, y: 10 }
        }
      }
      return { left: 0, top: 0 }
    },

```
see more about this change in https://router.vuejs.org/guide/advanced/scroll-behavior.html

4. Try to navigate to `http://localhost:8080/#/#100`. However, there is no scrolling to the `id="100"`. Checked in some recent versions of Firefox, Chrome, Opera.

**Expected behavior**
Scrolling to specified element ID. E.g. if you create the project using Vue CLI (with router and typescript), add the same content to `src/views/Home.vue` and change settings to the same in `src/router/index.ts` and try to navigate to `http://localhost:8080/#100` it will scroll you to the element. Works fine in Firefox and Chrome, for Opera you need to navigate first to `http://localhost:8080` and after that change it to `http://localhost:8080/#100`, direct link to the element doesn`t work in the new tab.

**Platform (please complete the following information):**
Quasar Version: v2.3.3
@quasar/app Version: v3.2.4

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [X] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux
Node: v14.15.5
NPM: 8.1.3
Yarn: 1.22.17
Browsers: Firefox 94,  Opera 63, Chromium 96
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Does it work with vue-router?
https://stackoverflow.com/a/79022

**Comment by kostyfisik** [comment]
No, you can use a valid string for an ID in Quasar, it still doesn't work. Note, I used exactly the same ID and vue-router settings for Quasar CLI and Vue CLI, it works fine with Vue CLI and doesn't work with Quasar.

**Comment by pdanpdan** [comment]
Add a console.log(to.hash) in your scroll function
You use has mode in quasar and history mode in vue
Anyway quasar has nothing to do with that - it's vue-router, so if it's the same version then it should work exactly the same

**Comment by kostyfisik** [comment]
Thank you for your comment! console.log(to.hash) returns and expected string. The reason for scrollBehavior not working was hash mode. It can be found in comment at https://github.com/vuejs/vue-router/blob/dev/examples/scroll-behavior/app.js#L21
