### ISSUE TITLE
Feature request: "Forbidden" cursor for v-touch-pan

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#11577]
**Is your feature request related to a problem? Please describe.**

I want to use v-touch-pan to resize element that has min and max width.

I want to show "Hand" cursor when user moved mouse to allowed position and "Forbidden" cursor for disallowed position.

"preserveCursor" modifier does not help, because it just shows "Pointer" cursor instead of "Hand" cursor, ignoring cursor set for element containing v-touch-pan:
```vue
<div v-touch-pan.horizontal.mouse="handlePan" style="cursor: col-resize;"></div>
```

**Describe the solution you'd like**

Any solution that allows to alternate cursor:

a) handlePan function might return true for allowed locations and false for disallowed. Then v-touch-pan could alter cursor based on returned value.

b) v-touch-pan might have modifier "useCursorFromContainingElement":
```vue
<div 
  v-touch-pan.horizontal.mouse.useCursorFromContainingElement="handlePan" 
  :style="{ 
    cursor: cursorNameDependingOnPosition
  }"
></div>
```

**Comment by pdanpdan** [comment]
Can you please make a codepen, so we can play with it?

**Comment by iliubinskii** [comment]
Thx for response.

Here is codepen:
https://codepen.io/ilyalyu/pen/wvrGYYV

As you can see, the size of the div is limited between 100 and 300 px.

So, what I want to achieve is that when I drag more than 300 px and less than 100 px cursor should change from "Hand" to "Forbidden".

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/GRMZwxJ?editors=1010

**Comment by iliubinskii** [comment]
Thank you for great and easy solution
