### ISSUE TITLE
Add "clear-value" prop for clearable behavior

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1157]
I have a problem when `clearable` prop is set on a `QInput` (text) field: when I click on the "clear" button, I'd like to set the input's value to `null`. Instead, it's set on an empty string.

My suggestion is to add a new prop to set the value to be used when clearing the input:

```
<q-input clearable :clear-value="null"/>
<q-select clearable :clear-value="null"/>
...
```

**Comment by dennythecoder** [comment]
I like the intent on this, but I think I'd like an event even more
``
<q-input clearable @clear="handler" />
``

**Comment by rstoenescu** [comment]
Added "clear-value" prop and it emits `@clear` event (for all form components that are "clearable"). In future v0.15.
