### ISSUE TITLE
Using q-popup-edit on a q-table cell that is being sorted

### ISSUE THREAD

**Issue by DaveDisco** [quasarframework/quasar#11585]
When editing a cell using q-popup-edit where the cell's column is the current sorted column, the input updates the model which in turn triggers the sort so the table, behind the popup, is reordered. Your next key input is now affecting a different row so your typing in the popup input is being randomly distributed to different rows. 
 
I found this is my application but the behaviour is reproducible on the example in the Quasar docs.

![image](https://user-images.githubusercontent.com/19912952/145176470-08fa08fd-c7cc-47d2-929d-e2ae1c1b547f.png)

**Comment by rstoenescu** [comment]
The example is not correct. Quasar works correctly.
Fix for the docs example will be available on next docs deployment.
