### ISSUE TITLE
Is this how to import code? Why not write it down directly? Will it be more convenient and easy to understand

### ISSUE THREAD

**Issue by FlinSun** [quasarframework/quasar#11581]
import { Platform, Cookies } from 'quasar'
Is this how you import code?It’s not like what I saw on github. The GitHub is displayed like this. Is it set like this?
import Platform from 'quasar/src/plugins/Platform.js';import Cookies from 'quasar/src/plugins/Cookies.js';
Because some novices can't understand this code, but why bother when there is such a simple method?

![image](https://user-images.githubusercontent.com/89564103/145037730-c98f2c6d-65b9-4197-bd8f-3d2d665b16f6.png)

**Comment by pdanpdan** [comment]
I don't understand what you mean.
Where is this screenshot taken from?
What is the problem, and what is the solution?
