### ISSUE TITLE
Allow using `v-show` instead of `v-if` for QMenu visibility

### ISSUE THREAD

**Issue by sgielen** [quasarframework/quasar#11595]
**Is your feature request related to a problem? Please describe.**
I have a ProgressBar component, which receives a progressBarId prop and uses `mounted()` to start listening for updates. When updates come in, it renders updates to the progress bar, and eventually emits "error" or "finished".

Now, I have a QMenu containing such ProgressBars. When the menu is hidden, the ProgressBars are not in the DOM, so their `mounted()` never runs. The QMenu opens when an icon is clicked.

Now, I want to display a badge on top of the icon that shows how many progress bars are ongoing. I can easily find the number of progress bars, and count the number of 'completed' progress bars by counting the 'error' or 'finished' emissions.

Unfortunately, when the QMenu is closed, the ProgressBar components are never actually rendered, so the `mounted()` method never gets called, so the code never subscribes to the progress bar updates, so the "error" or "finished" emissions never occur. Therefore, counting the badge does not work, and the badge icon is always incorrect -- at least, until the menu is opened, the subscribe takes place, and the emissions occur immediately.

**Describe the solution you'd like**
I'd like to be able to set an option on QMenu to use `v-show` instead of `v-if`, ensuring its contents are in the DOM regardless of whether the menu is open or not.

**Describe alternatives you've considered**
One alternative would be to move the progress bar subscription outside of the ProgressBar component, at the cost of code complexity and duplication.

Thank you for this amazing library!

**Comment by pdanpdan** [comment]
You are holding it wrong :)
Use some sort of store for the state and only render the state in your component.
If you want listen in the badge component, keep the state inside and pass it as prop to the QMenu you are rendering from it.

**Comment by sgielen** [comment]
Thanks @pdanpdan for the response. I considered your option (see "alternatives you've considered"), but splitting up Progress Bar code outside of the component seems contraproductive to me. Do you disagree with the problem or with the solution? Should I interpret this as a "hard no" on `v-show` support regardless of argument, or the argument not good enough for you?

**Comment by pdanpdan** [comment]
I'm sorry but it's a `cannot be done`, because the content of QMenu is only rendered when it is open
