### ISSUE TITLE
QInfiniteScroll containerHeight error

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar#11606]
https://github.com/quasarframework/quasar/blob/ae2ab94a1877c9bea835708ab8c45dd760ed5fb2/ui/src/utils/dom.js#L18

in some mobile devices, "el.getBoundingClientRect().height" return the floating number ，it cause QInfiniteScroll can't trigger  "emit('load)". 
https://github.com/quasarframework/quasar/blob/ae2ab94a1877c9bea835708ab8c45dd760ed5fb2/ui/src/components/infinite-scroll/QInfiniteScroll.js#L63

![image](https://user-images.githubusercontent.com/11263870/145339783-2ea09993-2463-4da8-8909-54dcda6c2ae1.png)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.5
