### ISSUE TITLE
screenwide modal shows scrollbar before modal appears (only in fullscreen mode)

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#1160]
I have a screenwide modal, actually the one mentioned here: #986

Before modal opens rightside/ scrollbar on the screen looks like this:
![screenshot from 2017-11-21 09-45-36](https://user-images.githubusercontent.com/10334123/33063402-a14737da-cea2-11e7-8ec0-974c16dc78df.png)

When a button to open the modal is pushed the first thing that happens is that the rightside scrollbar is shifted to the left by an element which looks to me like the rightside scrollbar of the modal. It pushes (elements on) the screen to the left. 
![screenshot from 2017-11-21 09-46-30](https://user-images.githubusercontent.com/10334123/33063573-1fd6cb2e-cea3-11e7-9a33-c96d8be8704a.png)

A split second after that the modal appears on top (with its own rightside scrollbar). 
![screenshot from 2017-11-21 09-47-40](https://user-images.githubusercontent.com/10334123/33063647-5df58396-cea3-11e7-8491-54c7e0a554aa.png)

This transition looks shaky/ does not look nice. It **only happens in fullscreen**. In mobile screen the modal just appears 'instantly' (without the scrollbar first), which is preferable.

When the modal is closed the same thing happens in opposite order (modal goes, but its scrollbar remains for a split second, then goes, with the same shaky transition result).

Any ideas?

**Comment by rstoenescu** [comment]
Was just working now in that area and this will disappear. Will close ticket when it's in future v0.15 code.

**Comment by bdurrer** [comment]
I am not sure if it is the same issue or something different: the modals keep adding `padding-right: 16px` to the body. Can also be seen in the demo.

**Comment by cgestes** [comment]
I also have this issue. padding-right: 15px is added to the body.

**Comment by KammererTob** [comment]
Can confirm. 16px added as right padding to the body element.

**Comment by rstoenescu** [comment]
Removed the behavior in latest v0.15
