### ISSUE TITLE
[Request] @focus and @blur for Q-Btn

### ISSUE THREAD

**Issue by frankbrussel** [quasarframework/quasar#1161]
Currently, many inputs support the @focus and @blur, which is useful and I'm using those a lot. The request is that the Q-Btn would also support the @focus and @blur. 

The use case is especially clear for situations in which tab is used to navigate. In my case: a form. The @focus can then be used to highlight what will happen when pressed enter. Also I would use it to set styling: the currently active item is now styled such that it is clear that that item is active. With the input fields on that item, it works fine. However, when at an input field and the tab is pressed such that the button becomes focused, there is no handle to use to also set the styling of the item on which the button is placed. 

And many thanks for everything that already exists!

**Comment by rstoenescu** [comment]
Yes, but you can use @focus.native and @blur.native. There are a LOT of events. Only some (like `@click` matter for QBtn inner workings so they are "custom" to Quasar). The rest can be taken from the native DOM element.

**Comment by frankbrussel** [comment]
Ah this worked very good, didn't know this existed. Thank you!
