### ISSUE TITLE
Module parse failed: 'return' outside of function (4:2)

### ISSUE THREAD

**Issue by 618457** [quasarframework/quasar#1162]
ERROR  Failed to compile with 1 errors                                                                                                                         00:29:57
 error  in ./node_modules/kaiser/lib/index.js

Module parse failed: 'return' outside of function (4:2)
You may need an appropriate loader to handle this file type.

=============================
Information shows up when I just init a Vue webpack project, install the Quasar and follow the component guide from Quasar website to try the QBtn QIcon (or any component else) in component way.

Would anybody help?

Thank you.

**Comment by rstoenescu** [comment]
Use the default starter kit. You shouldn't have any problems with it.
One small remark, please use the forum for questions. This is reserved for requests or bugs only. Thank you.
