### ISSUE TITLE
Hot reload with Docker (+WSL2) not working

### ISSUE THREAD

**Issue by ruilvo** [quasarframework/quasar#11636]
**Describe the bug**
Under the following system environment:

- Windows 10;
- Docker, using WSL2.

I can't get Quasar to hot reload using the development server. 

**Reproduction**
Basic project to reproduce on [this repository](https://github.com/ruilvo/quasar-docker-hot-reload-fail).

**To Reproduce**
Steps to reproduce the behaviour:
[Using the mentioned environment]
1. Clone the test repository;
2. Using `docker-compose -f "docker-compose.yml" up -d --build`, pull up the build;
3. Access the webpage using `localhost:8080`;
4. Edit some file (eg. `src/pages/Index.vue` and delete the `<img //...`)
5. Notice the page doesn't reload, not reloading the page shows a changed page.

**Expected behavior**
The page to change, aka, for hot reload to work.

**Platform (please complete the following information):**
Quasar Version: `"quasar": "^2.0.0",`
@quasar/app Version: `"@quasar/app": "^3.0.0",`
Latest Quasar CLI at the time of writing.

Quasar mode:
  - [x] SPA

Additonal Info:
- [x] Vuex
- [x] Prettier (eslint)
  
Tested on:
  - [x] SPA

OS: Host Windows 10, Debian Bullseye server.
Node: Last LTS at the time of writing: `node:16.13-bullseye`.
Browsers: Latest Firefox at time of writing.

**Additional context**

_What have you tried?_
- Using `CHOKIDAR_USEPOLLING=true` in [the environment file](https://github.com/ruilvo/quasar-docker-hot-reload-fail/blob/master/dev.env#L2). **This is enough to make it work in regular Vue.js**
- Using 
```js
// ...
    devServer: {
      // ...
      watchFiles: {
        paths: ["src/**/*", "public/**/*"],
        options: {
          usePolling: true,
        },
      },
    },
// ...
```
in [`quasar.conf.js`](https://github.com/ruilvo/quasar-docker-hot-reload-fail/blob/master/quasar.conf.js#L79) as per [Webpack docs](https://webpack.js.org/configuration/dev-server/#devserverwatchfiles).

Additionally, in [Quasar's website -> Quasar CLI introduction page](https://quasar.dev/quasar-cli/installation#introduction), is says that:

> [...] HMR (Hot Module Reload) will not work ([without a hack](https://quasar.dev/quasar-cli/quasar-conf-js#Docker-and-WSL-Issues-with-HRM)) [...]

The `without a hack` links to the tag `/quasar-conf-js#Docker-and-WSL-Issues-with-HRM` which doesn't seem to exist any longer.

I'm reporting as a bug because 1) this works in regular Vue.js after setting said environment variable, and 2) the "bug" in documentation.

**Comment by ruilvo** [comment]
![imagem](https://user-images.githubusercontent.com/8402646/145627475-ec2bc4a4-1c22-4a68-8103-31e6ac9fb398.png)

Extra info:
- Using Hyper-V the project works.

**Comment by pdanpdan** [comment]
See:
https://github.com/quasarframework/quasar/issues/7359
https://github.com/quasarframework/quasar/issues/11465

**Comment by pdanpdan** [comment]
About the link, it's
```
https://quasar.dev/quasar-cli/quasar-conf-js#Docker-and-WSL-Issues-with-HRM
vs.
https://quasar.dev/quasar-cli/quasar-conf-js#docker-and-wsl-issues-with-hmr
```

If you have time please edit the page and open a PR for the fix, ty.

**Comment by ruilvo** [comment]
For completeness, a [working Vue.js example](https://github.com/ruilvo/quasar-docker-hot-reload-fail/tree/demo-vue) has been pushed.

I'll report on findings and maybe fixing the page.

**Comment by ruilvo** [comment]
The findings in #11465 do work.

**Comment by TobyMosque** [comment]
`watchOptions` is a workaround what is only needed when u're running from a windows partition (eg: `/mnt/c`, `/mnt/d`), that is needed because linux (WSL2) can't watch a windows partition (as well, the general perfomance is really poor).

in that case, just install the [VsCode](https://code.visualstudio.com) and the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack), install the docker (+compose) in your WSL distro and run your code directly from the WSL.

here my current setup:
https://github.com/TobyMosque/quasar-docker-demo

**Comment by ruilvo** [comment]
I use VSCode, but I don't understand what you mean by 

> install the docker (+compose) in your WSL distro and run your code directly from the WSL.

So I'd have a basic WSL distro, and run VSCode server inside it, and Docker inside it?

That's some virtualization-ception.

I honestly really like the setup I currently have, with Docker running directly on Windows. (Docker just uses WSL2 APIs for its virtualization).

**Comment by kevinpostal** [comment]
> That's some virtualization-ception.
