### ISSUE TITLE
Quasar testing - jest with typescript can't resolve and import SFC modules

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#11635]
I installed quasar testing for quasar v1, along with jest for unit testing and typescript.

1) The IDE is unable to resolve SFC modules (though I can suppress the errors).
I saw the following note in the docs:
`TypeScript cannot infer a component type from a SFC, because it cannot understand the content of files which are not JS or TS. To allow correct inference of the component type, you shall separate the <script> tag content of your SFC into a standalone file, adopting a DFC (Double File Component) fashion.`
https://testing.quasar.dev/packages/unit-jest/
Is there any way to avoid migrating to DFC? I already have a huge codebase full of SFC.

2) Files can't be resolved using the @ alias for src/.

3) Even when using relative imports and thus avoiding the @ alias issue, components "mount with errors".

**Comment by yusufkandemir** [comment]
[Quasar v1 is EOL](https://github.com/quasarframework/quasar/discussions/15229), so I am closing this issue.

Also, use https://github.com/quasarframework/quasar-testing for testing-related issues.
