### ISSUE TITLE
Text in buttons for days in QDate are not centered

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#11659]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5757159/145790989-a9ad48ac-ffe5-4d91-ad38-4ffdd7b35f9e.png)

Notice the 1 in the selected day is not exactly centered vertically. When inspecting this button has a height of 30px and a line height of `24.01px` coming from the .q-btn style `line-height: 1.715em`.
When disabling this line-height or overriding the line height, the text in the buttons align correctly again.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
https://quasar.dev/vue-components/date#basic

**To Reproduce**
Inspect a day button in the QDate component in the docs to see that it is not correctly aligned. Override the `line-height` property on the `button` element to see it center correctly.

**Expected behavior**
Text in the buttons should be centered to prevent this:
![Alt Text](https://media0.giphy.com/media/iTOSoEs4eFwqs/giphy.gif?cid=ecf05e47nxs5s337aixvv0jich5sque77gdba2n8fwtgswa7&rid=giphy.gif&ct=g)

**Platform (please complete the following information):**
Quasar Version: 2.3.4

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v3.4.0
