### ISSUE TITLE
Stepper - first icon is fixed as "edit"

### ISSUE THREAD

**Issue by ap1969** [quasarframework/quasar#11661]
**Describe the bug**
Changing the first icon in the Stepper component's steps doesn't change the displayed icon - it remains as the "edit" icon

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
[https://codepen.io/blakeyuk/pen/MWEbPyP](https://codepen.io/blakeyuk/pen/MWEbPyP)

**To Reproduce**
1. The codepen above is based off the first example at https://quasar.dev/vue-components/stepper#style
2. Change all steps' icons to 'create_new_folder'

**Expected behavior**
All steps should have the create new folder icon

**Screenshots**
![Screenshot 2021-12-13 105538](https://user-images.githubusercontent.com/1629592/145800167-2499b0a4-6f5a-4ced-8bbe-a9a53224875b.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.3.4

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

**Comment by rstoenescu** [comment]
Hi,

That is the "active-icon" that gets displayed since user is currently at that step. You can configure this prop on QStepper or individually on each QStep.

**Comment by ap1969** [comment]
Ah, thanks so much.
