### ISSUE TITLE
Sass deprecation warnings emitted during build

### ISSUE THREAD

**Issue by p3v9d5ui** [quasarframework/quasar#11683]
**Describe the bug**

During build (Vite 2.7.1), several deprecation warnings (Dart Sass) are emitted. The warning is:

    Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

**To Reproduce**

Start a Vue3.2.24/Quasar2.3.4/Vite@2.7.1 project using "npm run dev"

**Expected behavior**

No warnings should be emitted. However, these warnings are emitted:

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($angle, 180) or calc($angle / 180)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
29 │   $rad: $angle / 180 * $PI
   │         ^^^^^^^^^^^^
   ╵
    node_modules/quasar/src/css/helpers/math.sass 29:9         sin()
    node_modules/quasar/src/components/time/QTime.sass 128:16  @import
    node_modules/quasar/src/css/index.sass 71:9                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(pow(-1, $i) * pow($rad, (2 * $i + 1)), fact(2 * $i + 1)) or calc(pow(-1, $i) * pow($rad, (2 * $i + 1)) / fact(2 * $i + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
32 │     $sin: $sin + pow(-1, $i) * pow($rad, (2 * $i + 1)) / fact(2 * $i + 1)
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/quasar/src/css/helpers/math.sass 32:18        sin()
    node_modules/quasar/src/components/time/QTime.sass 128:16  @import
    node_modules/quasar/src/css/index.sass 71:9                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($angle, 180) or calc($angle / 180)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
38 │   $rad: $angle / 180 * $PI
   │         ^^^^^^^^^^^^
   ╵
    node_modules/quasar/src/css/helpers/math.sass 38:9         cos()
    node_modules/quasar/src/components/time/QTime.sass 129:17  @import
    node_modules/quasar/src/css/index.sass 71:9                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(pow(-1, $i) * pow($rad, 2 * $i), fact(2 * $i)) or calc(pow(-1, $i) * pow($rad, 2 * $i) / fact(2 * $i))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
41 │     $cos: $cos + pow(-1, $i) * pow($rad, 2 * $i) / fact(2 * $i)
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/quasar/src/css/helpers/math.sass 41:18        cos()
    node_modules/quasar/src/components/time/QTime.sass 129:17  @import
    node_modules/quasar/src/css/index.sass 71:9                root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(round($number * $power), $power) or calc(round($number * $power) / $power)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
24 │   @return round($number * $power) / $power
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/quasar/src/css/helpers/math.sass 24:11        toFixed()
    node_modules/quasar/src/components/time/QTime.sass 132:12  @import
    node_modules/quasar/src/css/index.sass 71:9                root stylesheet
```

**Platform (please complete the following information):**
Quasar Version: 2.3.4
@quasar/app Version: n/a

Quasar mode:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ x] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ x] Standard (eslint)
  
Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Any
Node: 14.18.2
NPM: 8.3.0
Yarn: n/a
Browsers: any
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**

**Comment by rstoenescu** [comment]
Sass has decided (in a minor release) to issue this warnings because they changed something that would be a breaking change for Quasar. For stability reasons, we are not going to do any breaking changes, so please go with our recommendations (can be found in docs too) to stick with "sass" v1.32.12.

**Comment by p3v9d5ui** [comment]
Thank you. For those looking for the documentation, it is here:

https://quasar.dev/start/vite-plugin

**Comment by rmarchant-tc** [comment]
You can use a newer sass version and avoid the warnings with this workaround: you can "fix on build" the files that trigger the warnings. I added this to our docker file on each build (before `npm run build`):

```
RUN npm install -g sass-migrator
RUN sass-migrator division node_modules/quasar/src/css/**/*.sass
```

**Comment by Flamenco** [comment]
You can use the sass migrator with the `--migrate-deps` flag and it will convert the 2 files that have the issue.

**Comment by Flamenco** [comment]
We just added a rollup plugin to remove these errors.

https://www.npmjs.com/package/rollup-plugin-sass-migrator

**Comment by Flamenco** [comment]
We built a `Rollup` plugin that automates this for every `Vite` build, and it works like a charm.

```
sass-migrator division --migrate-deps node_modules/quasar/src/css/index.sass
```
