### ISSUE TITLE
q-select with multiple and clearable return null instead of empty array when cleared

### ISSUE THREAD

**Issue by sageworksstudio** [quasarframework/quasar#11688]
q-select with `multiple` and `clearable` return _null_ instead of empty array when cleared

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
https://codepen.io/sageworks/pen/VwMPGWq

```
<q-select  multiple clearable . . . />
```

**To Reproduce**
1. use `clearable` and `multiple` with q-select menu
2. Select some options and note that q-select is creating an array as the value of q-select
3. Deselect all option by manually clicking on all currently selected options. After all options are deselected, note that the value of q-select is now an empty array.
4. Again, select more options.
5. Now click on the `claerable` icon. Note that the value of q-select is now `null` instead of an empty array.

**Expected behavior**
Since value of q-select is set as an array when items are selected and deselected I was expecting the value of q-select to also be an empty array when using the clearable option. 

**Platform (please complete the following information):**
Quasar Version: 3.2.1

Quasar mode:
  - [X] SPA

Tested on:
  - [X] SPA

OS: Pop_OS (Ubuntu 20)
Node: 14.16.0
Yarn: 1.22.15
Browsers: Chrome / Firefox

**Additional context**
Possibly this is not a bug, but it seems inconsistent. Additionally, evaluating the value, when expecting an array, using `Array.isArray()` or `array.length` return errors.

**Comment by pdanpdan** [comment]
Works as documented:

```
clearable : Boolean
Description: Appends clearable icon when a value (not undefined or null) is set; When clicked, model becomes null
```

Clearable sets the model to null in all components that have it.

If you need you have the `@clear` event:

```
@clear -> function(value)
Description: When using the 'clearable' property, this event is emitted when the clear icon is clicked
Parameters:
  value : The previous value before clearing it
```

You can listen for the event and change the model to an array

**Comment by sageworksstudio** [comment]
Thanks @pdanpdan .

That looks like what I need to get around the issue. I agree It's not a bug and the docs are correct, but maybe it's inconsistent? Maybe it deserves a review as an enhancement? (if clearable, return empty array)

**Comment by pdanpdan** [comment]
It's been discussed before and it's not going to change (too many edge cases, mainly because people want to define the value to be set on clear): https://github.com/quasarframework/quasar/issues/8092

But you have some simple solutions: https://codepen.io/pdanpdan/pen/gOGgBgL?editors=1010
