### ISSUE TITLE
Vue devtools not working

### ISSUE THREAD

**Issue by ivanjaros** [quasarframework/quasar#11696]
I have installed the latest Vue devtools 5.3.4 into Firefox 95.0 and I have set up app via quasar cli 1.2.2 and when I run the app via quasar dev, Vue devtools are not detecting Vue.js and simply do not work. This is my first time using quasar so maybe there are some additional steps needed in order for this to work out of the box, like with basic vue cli?

**Comment by pdanpdan** [comment]
This is you friendly google robot, thank you for not bothering to type
https://www.google.com/search?q=vue+3+vue+devtools+firefox

**Comment by ivanjaros** [comment]
> This is you friendly google robot, thank you for not bothering to type https://www.google.com/search?q=vue+3+vue+devtools+firefox

i searched within quasar context and i haven't found anything useful. searching with firefox context now shows some results.
