### ISSUE TITLE
[BUG] QToggle does not updated input status `checked` if it has no name

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [quasarframework/quasar#11702]
**Describe the bug**
The checkbox of QToggle does not update the `checked` state if QToggle does not have a `name` attribute.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
https://jsfiddle.net/hz0xe9sw/

**To Reproduce**
1. Click the first toggle twice
2. Check console // [false, false]
3. Click the second toggle
4. Check console  // [true, false] <- maybe also a bug

**Expected behavior**
The checked status should always be the same whether the input has a name or not.

**Comment by smolinari** [comment]
@sschneider-ihre-pvs - I believe that is standard procedure. See here: https://quasar.dev/vue-components/toggle#native-form-submit

Scott

**Comment by pdanpdan** [comment]
Hello. This is by design. And for the checked attr not being set when name is present there is already a commit for the next release.
