### ISSUE TITLE
Adding files to QUploader programatically

### ISSUE THREAD

**Issue by ivanjaros** [quasarframework/quasar#11700]
The documentation for QUploader lists `addFiles(FileList | Array) `method which should allow me to add one or more files into the uploader programmatically. Unfortunately the uploader does not work with `v-model` which means I do not have access to its files and I have to use this dedicated method, but I don't know how. I  don't see how I can access the uploader instance in order to call it.

**Comment by pdanpdan** [comment]
Set a ref on the element
