### ISSUE TITLE
can not type Chinese in textarea or field

### ISSUE THREAD

**Issue by xujialiang** [quasarframework/quasar#1170]
### Software version

Quasar:newest
iOS

### What did you get as the error?
Can not input Chinese
### What were you expecting?
type Chinese in textfield

**Comment by hoipo** [comment]
I try it. It works !

**Comment by ueda19850603** [comment]
If the browser is Safari, it seems that you can not enter Chinese by q input.
It is impossible to input from the keyboard. However, I could enter it with copy paste.

**Comment by cosformula** [comment]
same issue

**Comment by aaronguostudio** [comment]
Hi, I just started with Quasar yesterday. I made a demo and the q-input works fine when I input Chinese use iOS Safari.

I am curious that have you add a 'v-model' for the <q-input> like this:
<q-input v-model="...">

**Comment by cosformula** [comment]
@aaronguostudio 
I simply wrote this
`<q-input v-model="name" stack-label="name" />`
and safari just didn't work, but other browers works fine

**Comment by cosformula** [comment]
this happens with quasar-play too
![screenshot](https://user-images.githubusercontent.com/18232501/34487036-80d202f0-f00d-11e7-9573-a73429852be3.gif)
iPad with iOS v11.2.1(15C153) if help

**Comment by rstoenescu** [comment]
Hi,

Will investigate. It might need a bit of work, so thank you for your patience!

**Comment by jolee11** [comment]
Start from 0.15, I can enter chinese in field without problems!

**Comment by rstoenescu** [comment]
Can everybody confirm it is working with v0.15?

**Comment by ueda19850603** [comment]
i'm ok,
v0.15 is excellent work
thank you very match

**Comment by rstoenescu** [comment]
Ok, closing as it's now working with v0.15.
