### ISSUE TITLE
Update event for q-toggle passes different targets

### ISSUE THREAD

**Issue by gratmoAldo** [quasarframework/quasar#11710]
Greetings! 
I've been trying to capture status changes for q-toggle, using @update:model-value, so I can take actions with a custom function.

The problem is that the custom function receives the JS event object, but the 'target' references the toggle 'thumb', rather than the toggle itself.
In the custom function, I need to be able to retrieve the toggle name or id so I know what to do with it.

Code here: https://jsfiddle.net/gratmoAldo/nL98x5zk/22/

1. Open the jsfiddle page
2. Open the browser console (not the console in jsfiddle, as it outputs too much text)
3. Flip the toggle ON & OFF to run the custom function on status change
4. Look in the console: evt.target points to the toggle 'thumb'. But in the DOM, the toggle id 'someId'  and name 'someName' are set at the parent.parent and sibling level:
<div class="q-toggle cursor-pointer no-outline row inline no-wrap items-center" tabindex="0" role="checkbox" aria-checked="true" id="**someId**">
	<div class="q-toggle__inner relative-position non-selectable q-toggle__inner--truthy">
		<input class="hidden q-toggle__native absolute q-ma-none q-pa-none" type="checkbox" name="**someName**" value="true">
		<div class="q-toggle__track">
		</div>
		<div class="**q-toggle__thumb** absolute flex flex-center no-wrap">
		</div>
	</div>
</div>

**Expected behavior**
Shouldn't the evt.target always point to the top element of the toggle where the id is set?

**Platform (please complete the following information):**
Quasar Version: @quasar/cl v1.2.1
@quasar/app Version: 3.1.10

Quasar mode:
  - [ X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ ] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [ X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS
Node:
NPM:
Yarn:
Browsers: Safari, Chrome
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
To put it in apple's terms, you are holding it wrong :)
https://jsfiddle.net/a3suj25f/
The event is the DOM event that triggered the change.
If you want to do something you don't need the DOM, you have the model.

**Comment by gratmoAldo** [comment]
@pdanpdan Thank you! That makes total sense.
