### ISSUE TITLE
Adding Vite Support

### ISSUE THREAD

**Issue by AlaaDq** [quasarframework/quasar#11717]
add a way to use Vite With Quasar V2

**Comment by MilosPaunovic** [comment]
There already is a great `Vite` support.
Check this out: [https://quasar.dev/start/vite-plugin](https://quasar.dev/start/vite-plugin)

**Comment by 0xBiriyani** [comment]
https://github.com/quasarframework/quasar/blob/dev/ROADMAP.md#q1-2022

**Comment by AlaaDq** [comment]
> 

thanks i just noticed it

can i migrate existing project to use vite?
