### ISSUE TITLE
Use Cordova plugins in Vue File not works

### ISSUE THREAD

**Issue by carlosaroca** [quasarframework/quasar#11724]
### Discussed in https://github.com/quasarframework/quasar/discussions/11723

<div type='discussions-op-text'>

<sup>Originally posted by **carlosaroca** December 19, 2021</sup>
When I try to use Cordova in file allways show error **"Uncaught (in promise) ReferenceError: cordova is not defined"** Im use like this with Quasar 2..3 but this not works.

I try other ways but not works any. Please some support for this, in Quasar 1 this works normal

I just use like 
```
after export default defineComponent({
setup () {
    const $q = cordova.plugins
    console.log("HOLA")
    console.log($q)
    console.log("CHAO")
  } 
.
.
.

```
</div>

**Comment by pdanpdan** [comment]
Hello. The code is meaningless, sorry. Wait for help in your discussion thread, and try to add some details there.
