### ISSUE TITLE
Color picker: different icon set

### ISSUE THREAD

**Issue by joppehoekstra** [quasarframework/quasar#11732]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to change the icons for the [color picker](https://quasar.dev/vue-components/color-picker) (in the three tabs in the bottom). This is problematic if you use a different icon set and do not want to load the default icon set as well. 

**Describe the solution you'd like**
Add the possibility to set custom icons for the three tabs in the color picker.

**Comment by yusufkandemir** [comment]
Hi, you can adjust the icon set, `colorPicker` has `spectrum`, `tune`, and `palette` properties, for adjusting the three tabs you pointed at. You can take a look at this example configuration(`svg-material-icons`):
https://github.com/quasarframework/quasar/blob/dd65e38ed9aa4adaa2197a993b7192d13606aba4/ui/icon-set/svg-material-icons.js#L95-L99

You can use one of the pre-configured `iconSet`s, and you can also configure individual icons to your liking. You can take a look at the documentation to learn about it: https://quasar.dev/options/quasar-icon-sets
