### ISSUE TITLE
Disabled buttons still fire v-touch-repeat events

### ISSUE THREAD

**Issue by Hoppi164** [quasarframework/quasar#11749]
**Describe the bug**

Disabled buttons still fire v-touch-repeat events
* A button is disabled by `:disable="true"`
* This button has a v-touch-repeat event on it
* This event fires when clicking the button, even though the button is disabled

Expected Behavior:
* Button SHOULD trigger an event if it is ENABLED
* Button SHOULD NOT trigger an event if it is DISABLED

Actual Behavior:
* Button triggers an event despite it's `disable` status

**To Reproduce**
1. Create Vue Component
2. Click on the disabled `-` ( subtract ) button
3. Take note that the value has decreased
4. Note: changing the trigger to `@click="decrement"` instead of `v-touch-repeat.mouse="decrement"` makes the program behave as expected

#### Instantiate Component
`<CustomSlider :min="0" :max="10" :step="1" v-model:value="totalLength"></CustomSlider>`

#### CustomSlider.Vue
```
<template>
    <q-card-section horizontal class="fit items-center no-wrap">
        <!-- Decrement Button -->
        <q-btn round color="negative" icon="remove" :disable="value <= min" v-touch-repeat.mouse="decrement">
        </q-btn>
        <!-- Slider -->
        <div class="col q-px-md">
            <q-slider class="full-width" :model-value="value" @change="val => emit('update:value', val)" :min="min" :max="max" :step="step" snap label label-always color="purple">
            </q-slider>
        </div>
        <!-- Increment Button -->
        <q-btn round color="positive" icon="add" :disable="value >= max" v-touch-repeat.mouse="increment"></q-btn>
    </q-card-section>
</template>
<script setup>
import { computed, ref } from 'vue'

const props = defineProps({
    min: Number,
    max: Number,
    step: {type: Number, default: 1},
    value: Number
})

const emit = defineEmits(['update:value'])

function increment() {
    emit('update:value', props.value + props.step)
}

function decrement() {
    emit('update:value', props.value - props.step)
}
</script>
```

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.3.4
@quasar/app Version:

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ ] Typescript
- [X] SFC usage with `<script setup>`
- [ ] Vuex
- [X] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Android Version 11, Windows 10
Node:12
NPM:
Yarn:
Browsers: Google Chrome / Android Browser / FireFox
iOS:
Android: YES - ISSUE Occurs on Android 11
Electron:

**Comment by pdanpdan** [comment]
Hello. The disabled button does not trigger the click event. You are using a directive that has nothing to do with the button and it's disabled state.
Disable the directive in sync with the button's disable state.

**Comment by Hoppi164** [comment]
My apologies, there seems to be some confusion..

I've created a codepen to illustrate the issue a bit better.

https://codepen.io/DrewDrew164/pen/bGoodBP?editors=1011

Steps to reproduce:
(On Windows)
* Navigate to `https://codepen.io/DrewDrew164/pen/bGoodBP?editors=1010`
* Set the slider to value 5
* Using the mouse: click and hold the red subtract button
* Notice that the touch-repeat directive continues firing AFTER the button has been disabled, resulting in the value becoming a negative number

![image](https://user-images.githubusercontent.com/9586453/147105316-82ebef08-7b6e-4396-893d-590209a5373f.png)

![image](https://user-images.githubusercontent.com/9586453/147105518-33938486-3c5d-45ac-a36a-e86947c31b9e.png)

Steps to reproduce:
(On Mobile - Google Chrome / Android Browser):
* Navigate to `https://codepen.io/DrewDrew164/pen/bGoodBP?editors=1010`
* Tap the red subtract button once: The v-touch event fires, despite the button actually being disabled.
* Notice that with a single tap the value still becomes a negative number

![Screenshot_20211223-001050](https://user-images.githubusercontent.com/9586453/147105822-a457108b-703a-42bc-9867-4e6754699c63.png)

**Comment by pdanpdan** [comment]
Yes, it is expected - the directive does not know (and does not care) about the state of the element it works on
You must disable the directive when the button is disabled: https://codepen.io/pdanpdan/pen/jOGGbRz?editors=1011
It is a side effect that when the button is disabled a new click/click+hold with the mouse on the disabled button does not trigger the event - a disabled button does not allow mouse events.

**Comment by Hoppi164** [comment]
Oh, that's the expected behaviour?
Okay my apologies.


Thanks for your help and clarification Dan.
Have a great day :D
