### ISSUE TITLE
Option to add state-based classes to `q-toggle` and `q-btn-toggle`

### ISSUE THREAD

**Issue by matthiasmoier** [quasarframework/quasar#11753]
**Is your feature request related to a problem? Please describe.**
I’d like to have an easy way to edit/enhance the styling of `q-toggle` and `q-btn-toggle` items based on their current state. The provided possibilities are sufficient for most use cases but are pretty limited (to colors) none the less. I get into the situation that I’d like to have enhanced styling besides the colors for the different states every now and then.

**Describe the solution you'd like**
To be able to adjust the styling in a more complex way, it would be fantastic to either have a state-based CSS class provided by default (f.e. `toggle-on` / `toggle-off` … or at least `toggled` for the toggled state to be able to distinguish the two states).

An even nicer – and way more flexible – solution would be to extend the according APIs with something like `toggle-class` and `toggle-off-class` that could then be provided when using the component.

This way, the styling of the items could completely be customized in an easy way. (In our case, I’d like to use some CSS animations and extensive custom styling.)

**Describe alternatives you've considered**
I currently use a volatile (and kinda hacky) workaround by abusing the `toggle-color` prop to add an additional CSS class:

```html
<q-btn-toggle toggle-color="some-color btn-toggle-additional-hacky-css-class" />
```

But this only works in conjunction with a provided color and because (and as long as) Quasar just takes the *first* part and turns that into the `bg-some-color` class on the item and just adds the part after the space afterwards to the class list.

It would be way more flexible – and comfortable – if this could be done f.e. like this:

```html
<q-btn-toggle
    toggle-color="some-color"
    toggle-class="btn-toggle-additional-css-class"
    toggle-off-class="btn-currently-not-toggled-css-class"
/>
```

**Additional context**
This could somewhat be related to https://github.com/quasarframework/quasar/issues/7593 and https://github.com/quasarframework/quasar/issues/7004 as – I think – this could also provide a (custom CSS-based) solution to those requests.

Maybe this could also be used as an idea for other components that have different states (f.e. `q-radio` or `q-option-group` items).

**Comment by pdanpdan** [comment]
Cannot this be already done using the inner classes of QToggle?
https://codepen.io/pdanpdan/pen/XWeVPbY

**Comment by matthiasmoier** [comment]
Thanks for your reply, @pdanpdan.

In your example, the class is not changed depending on the state of the toggle? (Also, there does not seem to be a `inner-class` prop on `q-toggle` and `q-btn-toggle`.)

I created a quick pen with some examples: https://codepen.io/moier/pen/LYzmmaX
Could you explain it again using this pen?

**Comment by pdanpdan** [comment]
I updated my example with another case: https://codepen.io/pdanpdan/pen/XWeVPbY
What I meant by inner classes are the ones applied by default on QToggle based on state (`.q-toggle__inner--falsy`, `.q-toggle__inner--indet`, `.q-toggle__inner--truthy`)
Also applied to your codepen: https://codepen.io/pdanpdan/pen/XWeqyMW
Quasar would do the exactly same thing, except than it would do more work for all cases that do not require it
