### ISSUE TITLE
Unable to load electron preload script

### ISSUE THREAD

**Issue by tmotagam** [quasarframework/quasar#11759]
**Describe the bug**
The preload script in the electron mode is loading correctly when I am enabling the sandbox mode in the electron

**Electron v 16.0.5**

**Expected behavior**
The preload script should load when the sandbox mode is enabled

**Screenshots**
![Screenshot 2021-12-22 213503](https://user-images.githubusercontent.com/63451837/147122533-2e727eb4-f434-4ef4-aeb6-669673f3201d.png)
![Screenshot 2021-12-22 213643](https://user-images.githubusercontent.com/63451837/147122552-53844a09-c715-4471-acd8-3b2191faf3f8.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ ] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [x] Standard (eslint)
  
Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: windows 10
Node: 16.13.0
NPM: 8.1.0
Yarn:
Browsers:
iOS:
Android:
Electron: 16.0.5

**Additional context**
The preload script loads correctly if I add 'electron-preload.js' in the preload option only in dev mode
in production mode the process.env.QUASAR_ELECTRON_PRELOAD and the path 'electron-preload.js' does not work at all

**Comment by hawkeye64** [comment]
@tmotagam This works in this project: https://github.com/hawkeye64/electron-quasar-file-explorer-v2/blob/main/src-electron/electron-main.js#L34
Fork it and see if it builds for you. I am wondering if it has anything to do with your environment?

**Comment by tmotagam** [comment]
@hawkeye64 I did what you asked but the error is persisting if I use app.enableSandbox() or sandbox flag in the electron-main.js file during dev mode or production.

But the error is removed if I do not use the sandbox flag or the app.enablesandbox()

**Comment by hawkeye64** [comment]
@tmotagam I added `sandbox: true` and get the same thing. Yet, the app still works, so the preload script is obviously loaded (from something/somewhere else?) as the app still works.

This is beyond a Quasar issue as I feel there's nothing we can do to resolve this. I would suggest you start a communication with the Electron folks.

**Comment by tmotagam** [comment]
@hawkeye64 I am opening this issue again as the electron people is saying that since the error cannot be generated without the quasar framework.
They are asking for the demonstration that the issue is with the electron and not within the configuration of quasar.

**Comment by tmotagam** [comment]
https://github.com/electron/electron/issues/32280#issuecomment-1006646606

**Comment by TobyMosque** [comment]
u said that works in a electron app without quasar, but didn't uploaded that anywhere.

Do u can upload your electron app with sandbox and context isolation where the preload scripts are working as expected in a repo?

**Comment by tmotagam** [comment]
@TobyMosque this is the example if you run it with the latest electron (16.0.6) it will work as expected

https://github.com/tmotagam/sqlite-electron/tree/master/example

**Comment by szekelyisz** [comment]
I can confirm that the issue still persists with `sandbox: true`. Just create a new project, add electron support, and run the example. See the devtools console for errors like above.

```
 Dev mode.................. electron
 Pkg quasar................ v2.10.0
 Pkg @quasar/app-webpack... v3.6.2
 Pkg webpack............... v5
 Debugging................. enabled
```

I can also confirm that @tmotagam's example doesn't have this issue.

@hawkeye64 your example works because you depend on electron 18 whereas Quasar's default is 21 as of now. Sandboxing was enabled by default in electron 20.

**Comment by rotu** [comment]
I still think this is broken. Right now creating a quasar electron project installs `electron@latest` so a new template project will have this as an issue.

Even *with* `sandbox: true` (the default), I think the preload script should not crash - it should just run sandboxed.

**Comment by rotu** [comment]
I figured it out! We're bundling things in a slightly wrong module system https://webpack.js.org/configuration/output/#module-definition-systems

In `@quasar/app-webpack`, we bundle the prepackaged script as `commonjs2` output:
https://github.com/quasarframework/quasar/blob/91739c11f672bd77deaaae1e38a6544dfa4b6cd1/app-webpack/lib/webpack/electron/create-node-chain.js#L33-L40

But the Electron script sandbox `runPreloadScript` runs this with the `commonjs` convention (no `module` object):
https://github.com/electron/electron/blob/a8c0ed890f61664156886356ecb6ab9f73c69cf1/lib/sandboxed_renderer/init.ts#L104C1-L114
