### ISSUE TITLE
dark mode not work

### ISSUE THREAD

**Issue by ltbyun** [quasarframework/quasar#11766]
**Describe the bug**
dark mode do nothing

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**

**To Reproduce**
1. create app
```
yarn global add @quasar/cli
quasar create qt
```
2. edit quasar.conof.js as follows
```
framework: {
      config: {
        dark: 'true'
      },
...
}
```
3. run, the ui is still in light mode
`quasar dev`

**Expected behavior**
ui change to dark

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
2.3.4

OS: win10
Node: 16.13.1
NPM: 8.1.2
Yarn: 1.22.15
Browsers: edge
iOS:
Android:
Electron:

**Additional context**

**Comment by MilosPaunovic** [comment]
You should pass a `Boolean` value, as stated in the docs:
[https://quasar.dev/quasar-plugins/dark#through-quasar-conf-js](https://quasar.dev/quasar-plugins/dark#through-quasar-conf-js)

```js
framework: {
  config: {
    dark: 'auto' // or Boolean true/false
  }
}
```

**Comment by ltbyun** [comment]
@MilosPaunovic it works, it's my fault
