### ISSUE TITLE
How to remove the "statics" directory or change your location?

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#1177]
I am structuring the folders in my project differently and would like to be able to modify the location of the statics folder.

**Comment by rstoenescu** [comment]
Hi,

You got the /build folder in your app with all the webpack configuration so you can tweak it to meet your needs. Start by doing a global search in this folder over "statics" keyword.

**Comment by slowaways** [comment]
Thanks! It's works in dev environment!
