### ISSUE TITLE
Typescript build error in v2.4.0

### ISSUE THREAD

**Issue by sinbino** [quasarframework/quasar#11784]
**Describe the bug**
Typescript build error in v2.4.0

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Due to typescript build error, reproduction by Codepen is not applicable.

**To Reproduce**
1. Follow the guide below to create a project 
    https://quasar.dev/start/vite-plugin
2. Create a production build with "yarn build" command
3. Get the following error
```
$ vue-tsc --noEmit && vite build
node_modules/quasar/dist/types/api/slider.d.ts:8:2 - error TS1036: Statements are not allowed in ambient contexts.

8 };
   ~

Found 1 error.
```

The URL below is a minimal reproduction repository
https://github.com/sinbino/issue-quasar-tsbuild

**Expected behavior**
The build should be a success.
In quasar v2.3.4, the same procedure succeeds.

**Screenshots**
none.

**Platform (please complete the following information):**
Quasar Version: 2.4.0
@quasar/app Version: none
@quasar/vite-plugin Version: 1.0.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [x] Vite Plugin

Additonal Info:
- [x] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: alpine 3.15.0
Node: 17.2.0
NPM: none
Yarn: 1.22.17
Browsers: none
iOS: none
Android: none
Electron: none

**Additional context**
none

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available shortly (in a few minutes) in Quasar v2.4.1
