### ISSUE TITLE
[Bug] [Mobile] [v1 & v2] QExpansionItem becomes focus styled on mobile when tapped, it does not on desktop

### ISSUE THREAD

**Issue by douglasg14b** [quasarframework/quasar#11788]
**Describe the bug**
The expansion item header becomes focus styled on mobile when tapped, this behavior is not present on desktop.

**Codepen/jsFiddle/Codesandbox (required)**

* https://quasar.dev/vue-components/expansion-item
* https://codepen.io/douglasg14b/pen/OJxzLJQ?editors=101 
   * Note: Codepen breaks on mobile for me and doesn't display the behavior... your mileage may vary?)

**To Reproduce**
1. On mobile/mobile mode
2. Click an expansion item
3. Notice how it stays highlighted

**Expected behavior**
That the expansion panel opens without changing the style of the header

**Screenshots**

![image](https://user-images.githubusercontent.com/1400380/147421693-bfb54d36-f403-4e40-9245-2feadd6be8a0.png)

**Platform (please complete the following information):**
Quasar Version: `1.15 & 2.x`
@quasar/app Version: `2.2.6`

Quasar mode:
  - [x] SPA

Tested on:
  - [x] SPA

Browsers: Chrome

**Comment by douglasg14b** [comment]
This is quite annoying since we don't seem to have control over the `q-item` the header is wrapped in. And the focus opacity styling really messes with the look & feel of expansion items, even moreso on mobile where the styles are more sensitive.

If we had the ability to omit/toggle the  `q-focusable` and `q-hoverable` classes as a prop, that would work well.

**Comment by pdanpdan** [comment]
Are you sure you are testing on mobile, or that you refresh after changing the emulation from desktop to mobile?
The platform detection only runs once on load.
