### ISSUE TITLE
Q-Editor paste event override in the docs not working: each copy-paste is appended twice in the editor

### ISSUE THREAD

**Issue by jra11** [quasarframework/quasar#11787]
**Describe the bug**
The "plaintext pasting" code in the docs is not working, either in the included demo in the docs, or in a standalone fresh Quasar installation.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Just go on https://quasar.dev/vue-components/editor#plaintext-pasting
Copy-paste a word, the word is added twice in the editor.

**To Reproduce**

1. Go to the Quasar v2 docs, on the q-editor page ](https://quasar.dev/vue-components/editor#plaintext-pasting)
2. Copy-paste a word in the "Paste Event Override" editor
3. See that the word is pasted twice.

**Comment by pdanpdan** [comment]
yep, looks like it's a regression from V1

**Comment by jra11** [comment]
Solved by adding:

```
 evt.stopPropagation()
```

So it seems a docs issue.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fixed example will be available on next docs deployment
