### ISSUE TITLE
Right-click and touch-hold options for QTree

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#11792]
I'm trying to create a context menu that is dependent on the type of node that the user is activating in my QTree.  Today, however, only a left click can select a tree node.  The QTree "handler" also only works with a left click.  

The result is that I cannot customize my context menu in my menu's @before-show method--because the node selection does not occur first.

**Describe the solution you'd like**
I think the simplest solution (for me) would be to add an option to QTree that would make right-click and touch-hold select the underlying node.  Careful consideration of event propagation would hopefully mean that the sequence of events could then be:

1. user right clicks a node
2. node becomes selected (because of option set in QTree)
3. context menu that is attached to a parent DOM node of QTree is invoked

Then my context menu could rely on "selected" in my QTree being correct....
And for touch users hopefully the sequence of events would also propagate properly for long-touch.

**Describe alternatives you've considered**
I've tried various methods; but I cannot get a right-click to select a node.  Nor can I determine the current node given the mouse location.

**Comment by rfox12** [comment]
Figured out vue uses @contextmenu to represent right-clicks; but there are still gaps in my click-able spaces when using header and body templates.  The @contextmenu should ideally be higher up in the DOM for each node

**Comment by ke4nec** [comment]
Any progress about right click node?
