### ISSUE TITLE
Add Vue 3 to Github Topics

### ISSUE THREAD

**Issue by joshbuker** [quasarframework/quasar#11801]
The Github topics include `vue2` but not `vue3`. With Quasar v2, it now supports Vue 3 so it would make sense to add `vue3` and `vuejs3` as topics as well.

![Repo Metadata](https://user-images.githubusercontent.com/1802598/147518324-1c057bd6-9083-49f0-9c3e-e62c5aa3e062.png)

Doesn't matter all that much, but it should also take only a few seconds to update.

**Comment by hawkeye64** [comment]
Unfortunately, discussions only allow 10 topics and we are at the limit.

**Comment by hawkeye64** [comment]
Oops, I see what you mean. Will add momentarily.

**Comment by hawkeye64** [comment]
I had to remove the Vue2 and Vuejs2 as only 20 topics are allowed. :(
I added the Vue3 and Vuejs3 equivalents.

**Comment by joshbuker** [comment]
Didn't realize they capped it at 20, but I suppose otherwise you'd run into the same issues SEO did with keyword spam...

I wonder if it would be worth the time and effort min-maxing the keywords for optimal discoverability? 🤔 Probably not, tbh...

Anyway, thanks for updating that!
