### ISSUE TITLE
rules span broke template

### ISSUE THREAD

**Issue by Aerkante** [quasarframework/quasar#11809]
When you put a rule to a label, it reversed a space below input. If you working with flex box, they are broke other inputs and misalign entire form

**Comment by MilosPaunovic** [comment]
Please use [Discussions](https://github.com/quasarframework/quasar/discussions) for this kind of stuff, and, even more importantly, provide a Codepen reproduction so someone could help with your issue.

**Comment by pdanpdan** [comment]
Hello, please check the docs, and use discord or discussions for help requests.
And when you seek for help please provide info and a reproduction
