### ISSUE TITLE
DataTable dont show header at Android, but the same source show in Chrome

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1180]
### Software version

Quasar: 0.14.7
OS: Win10
Node: 6.10.2
NPM: 3.10.10
Browsers: Chrome 62
iOS: ---
Android: 5.1.1
Any other software related to your bug:

### What did you get as the error?
Dont show header at Android

### What were you expecting?
Headers

### What steps did you take, to get the error?
Simply dont show header at Android
And under a Quarsar Play, show the colummns at each new row

SOURCE BELOW:

q-data-table :data="users" :config="config" :columns="columns"

  data () {
    return {
      config: {
        rowHeight: '40px',
        title: '',
        noHeader: false,
        refresh: false,
        columnPicker: false,
        bodyStyle: {
          maxHeight: '200px'
        },
        responsive: true,
        selection: 'single',
        messages: {
          noData: '<i>Atenção</i>. Não existem usuários cadastrados',
          noDataAfterFiltering: '<i>Atenção</i> Não encontrados usuários.'
        },
      },
      columns: [{
        label: 'User',
        field: 'user',
        width: '70px'
      },
      {
        label: 'Perfil',
        field: 'perfil',
        width: '70px'
      },
      {
        label: 'email',
        field: 'email',
        width: '200px',
        type: 'email'
      }],
      users: [{
        id: 1,
        user: 'Luiz',
        perfil: 'Cozinha',
        email: 'luiz@recanto.com.br'
      },
      {
        id: 2,
        user: 'r.luiz',
        perfil: 'Administrador',
        email: 'luiz@urca.com.br'
      },
      {
        id: 3,
        user: 'bruno',
        perfil: 'Entregador',
        email: 'bruno@urca.com.br'
      }],
   }
}

**Comment by rstoenescu** [comment]
Hi,

The DataTable in v0.15 has been revamped, which will allow TOTAL customisation power. Currently focusing on finishing the new version to release it ASAP. What this means is that v0.14 won't receive any further updates. All dev resources are currently aiming v0.15. If you can wait for the new release it will be all worth it.
Closing this bug as your request will be easy to do with the new version.
