### ISSUE TITLE
capacitor can't work with secure context because of quasar overide of https to http

### ISSUE THREAD

**Issue by amitgur** [quasarframework/quasar#11814]
**Describe the bug**
When working with capacitor with [Secure Context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) , for example navigator.getUserMedua, capacitor should be served through localhost/https. As this configuration cannot run though localhost, webpack-dev-server is created with the phone ip to serve the application from the connected mobile phone. 
devServer doesn't work with https (checked that with capacitor v2 and v3). The solution is to use [Capacitor Configuration](https://capacitorjs.com/docs/config) and to add 
`
"server": {
    "hostname": "192.168.0.41:5000",
    "iosScheme": "https",
    "androidScheme": "https"
  }
`
The problem is that after running
`quasar dev -m capacitor -T android`
quasar is adding url property to /src-capacitor/android/app/src/main/assets/capacitor.config.json without https:
`
"server": {
		"hostname": "192.168.0.41:5000",
		"iosScheme": "https",
		"androidScheme": "https",
		"url": "http://192.168.0.41:5000"
	}
`
And thats break the secure context, if I change that created http to https the problem is solved, but I have to do that for every "quasar dev" at the moment.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Can that be created in Codesandbox? didn't succeed.

**To Reproduce**
1. Create a new quasar project with capacitor
2. add your mobile phone ip to src-capacitor/copacitor.config.json as described above as "server" property with https scheme
3. quasar dev -m capacitor -T android

**Expected behavior**
src-capacitor/android/app/src/main/assets/capacitor.config.json should have server.url: "https://192.168.0.41:5000"

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [X] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ ] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [X] Capacitor
  - [ ] BEX

OS: Ubuntu
Node: 14.16.1
NPM: 8.3
Yarn:1.22.5
Browsers:
iOS:
Android:11
Electron:

**Additional context**
I would like to try and fix that, never commited a code PR, only doc PR

**Comment by yusufkandemir** [comment]
Hi @amitgur 👋 Make sure you set `quasar.conf.js > devServer > server > type = 'https'`(_It is not yet supported for Capacitor v3, not sure if anything got changed_) for HTTPS on the dev server. When you do that, the `url` property will be set as `https://....`. By the way, `https` is not a valid value for `iosScheme` as stated in the documentation link you've sent.

So, please use `quasar.conf.js > devServer` to configure the dev server behavior(_host name, https, etc._) when possible to avoid these kinds of problems.

It should definitely work with Capacitor v2, if you can get it to work with Capacitor v3 with self signed certificates and such, please let us know.
