### ISSUE TITLE
Add "disable" prop to q-tooltip

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#11818]
**Is your feature request related to a problem? Please describe.**

I want to disable all tooltips during drag operation.

I don't like to use v-if for this because it will destroy and create tooltip components each time.
I get error if I add v-show.
If I use v-model it will break default mechanism of showing tooltip, which is not desired.
Keep alive also did not work - with keep alive tooltip continues to show.

**Describe the solution you'd like**

Add "disable" prop or make v-show work for tooltip.

**Describe alternatives you've considered**

I am using v-if for now, but I don't like it for performance reasons.

**Additional context**

No

**Comment by rstoenescu** [comment]
Hi,

You've got nothing to worry about the component being destroyed and recreated. The component itself is very smart and does not renders the content when it's closed anyway. The "overhead" is really negligible, especially with Vue 3. Which is why we haven't added the "disable" prop...
