### ISSUE TITLE
[Request] In DataTable, at @rowclick, can you make row highlight?

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1181]
At Android, the space of screen is gold.
If the row is highlight when clicked,
and when clicked in anothed row,
the older is return at normal e the new one is highlighted.
I will be very happy.
May be a propertie color-selected="color"
Tanks.

**Comment by rstoenescu** [comment]
Hi,

The DataTable in v0.15 has been revamped, which will allow TOTAL customisation power. Currently focusing on finishing the new version to release it ASAP. What this means is that v0.14 won't receive any further updates. All dev resources are currently aiming v0.15. If you can wait for the new release it will be all worth it.
Closing this bug as your request will be easy to do with the new version.
