### ISSUE TITLE
QLinearProgress animation-speed default doesn't match actual value

### ISSUE THREAD

**Issue by joshbuker** [quasarframework/quasar#11832]
The animation speed default value in the docs is `300ms`, but the actual value is `2100`.

I looked at how the defaults are being loaded in, and it's some witchcraft that I would need more time to unravel. I figure it would be faster to just show whats going on and let someone more familiar with the project take a stab.

- https://quasar.dev/vue-components/linear-progress#qlinearprogress-api
- https://github.com/quasarframework/quasar/blob/262ec7dd297627f0c5defe75ec0c080f17439faf/ui/src/components/linear-progress/QLinearProgress.js#L49

![Screenshot from 2021-12-29 13-24-47](https://user-images.githubusercontent.com/1802598/147705575-5e196c36-2b6a-4c0b-9f74-f45f6772239e.png)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.4.3
