### ISSUE TITLE
[BUG?] Data not deleted in QTable's "Handling Bottom Layer" section in Quasar Website

### ISSUE THREAD

**Issue by angelhdzmultimedia** [quasarframework/quasar#11837]
### Link
[https://quasar.dev/vue-components/table#handling-bottom-layer](url)

### Description
Toggling the **Fill with data** QToggle in the _"Handling Bottom Layer"_ section of the QTable documentation in Quasar website, fails to delete the data to test the "Hide No data" toggle to hide the No Data Slot.

**Comment by rstoenescu** [comment]
Fix to docs example will be available on next deployment.
