### ISSUE TITLE
How to compile my own version of Quasar?

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#1183]
I wanted to modify the q-select component for learning and testing purposes. I did not want to create a custom component. I expected the components to be in a folder on the node_modules.
I tried install my own version of Quasar through a fork here on GitHub (`npm install https://github.com/slowaways/quasar.git`) when compiling says that the `quasar` package is missing.

I honestly did not find any tutorials within the documentation for this.
Thanks!

**Comment by pdanpdan** [comment]
You have to compile quasar first. If you try the v0.15 (Dev) branch you can do a npm run build in the quasar clone folder, or a npm run dev to start in dev mode.

**Comment by slowaways** [comment]
Thanks @pdanpdan, but I do not have enough knowledge on node and npm:

git clone https://github.com/slowaways/quasar.git - OK
cd quasar - OK
npm install - OK
npm run dev - OK
...
How to use this compiled version in my project?

**Comment by pdanpdan** [comment]
I thought you only wanted to test your changed components

**Comment by slowaways** [comment]
@rstoenescu Can you help me?

**Comment by pdanpdan** [comment]
Hello. This issue is hardly a place for a npm tutorial. Please join the forum at http://forum.quasar-framework.org.

**Comment by slowaways** [comment]
Done.
http://forum.quasar-framework.org/topic/1616/how-to-compile-my-own-version-of-quasar-framework

**Comment by rstoenescu** [comment]
Also run a 'npm run build' -- this will create a /dist folder in your Quasar clone. That's the compiled version.

**Comment by slowaways** [comment]
Just replace the content of the node_modules/quasar-framework/dist folder?

**Comment by rstoenescu** [comment]
And also copy package.json outside of dist.
Best is to create a symbolic link to where your Quasar clone is.

**Comment by slowaways** [comment]
I'm coming back after so long without touching with Vue and Quasar.

What do I have to compile first now? The UI folder? App?

It would be nice if you had a tutorial for beginners to make a better contribution to Quasar, compiling their own version, modifying and testing it.
There are people who are better at developing (creating), others at understanding the code, others at testing and debugging, others at having ideas about what to create or modify.
