### ISSUE TITLE
[Feature Request] Add CSS helper classes for margins and padding

### ISSUE THREAD

**Issue by f12Devs** [quasarframework/quasar#1185]
Something that I feel is missing from Quasar is a set of CSS helper classes for setting margins and padding. For example, to set the left margin of element, you should be able to use .ml[**0-5**, or **a** for auto]. This will make it really easy to set margins and padding for an element. The syntax I propose is the following:

first char (type): **m** or **p**, for margin or padding
second char (direction): **l, r, t, b, or a**, for left, right, top, bottom, or all
third char: **0-5** or **a**, for the size of margin/padding. **a** is for auto. You could also use xs, sm, md, etc. instead

**Comment by rstoenescu** [comment]
Hi, Already in future v0.15. Closing this.
