### ISSUE TITLE
ValidationRule typescript error

### ISSUE THREAD

**Issue by Quimy** [quasarframework/quasar#11854]
I added promise as a validation rule on q-input and type check returns error:

`Type '(((val: string) => string | true) | ((val: string) => Promise<string | boolean>))[]' is not assignable to type 'ValidationRule<any>[]'.
  Type '((val: string) => string | true) | ((val: string) => Promise<string | boolean>)' is not assignable to type 'ValidationRule<any>'.
    Type '(val: string) => Promise<string | boolean>' is not assignable to type 'ValidationRule<any>'.
      Type '(val: string) => Promise<string | boolean>' is not assignable to type '(value: any) => string | boolean'.
        Type 'Promise<string | boolean>' is not assignable to type 'string | boolean'.
          Type 'Promise<string | boolean>' is not assignable to type 'true'.`

In my opinion type definition is missing a Promise: https://github.com/quasarframework/quasar/blob/957981595beccc86282d4726ea50d5f00dfe1251/ui/types/api/validation.d.ts#L4

Documentation mentions that Promise as a rule is possible: https://quasar.dev/vue-components/input#example--async-rules

Is this a thing or am I missing something?

Quasar Version: 2.4.1

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [x] Vite Plugin
 
Additonal Info:
- [x] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux
Browsers: Electron

**Comment by lupodellasleppa** [comment]
same happens if the validation rule is a computed boolean

![image](https://github.com/quasarframework/quasar/assets/23663689/8d4f5a27-d246-463a-851d-782e5fab3c18)

```
const agentValid = computed(() => {
  return agentsStore.agents.includes(tourEditStore.tour.agent);
});
```
