### ISSUE TITLE
update doc suggestion

### ISSUE THREAD

**Issue by jmellicker** [quasarframework/quasar#1187]
On this page: [http://quasar-framework.org/guide/quasar-cli.html ](http://quasar-framework.org/guide/quasar-cli.html )there is a lot of valuable info, a suggestion of something that could be added is this:

When you run: `cordova requirements` on MacOS, you will get:

`ios-deploy was not found. Please download, build and install version 1.9.2 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'
`

But

`npm install -g ios-deploy`

doesn't work.

But this does:

`sudo npm install --global --unsafe-perm ios-deploy`

(see issue [here](https://github.com/phonegap/ios-deploy/issues/109))

Anyway, just a thought.

**Comment by BenoitRanque** [comment]
Could you make a pr?

**Comment by rstoenescu** [comment]
Moved this to the docs repo.
