### ISSUE TITLE
interactive documentation

### ISSUE THREAD

**Issue by Maxhodges** [quasarframework/quasar#1188]
It would be cool if we could play around with Quasar components in the documentation. With [react-semantic-ui](https://react.semantic-ui.com/collections/form#form-example-form) docs, you can edit the code samples and it re-renders the sample component live in the browser. Useful!

![isitmrm4hs](https://user-images.githubusercontent.com/957271/33263783-6b86ff52-d3ae-11e7-90ce-e36c7447b689.gif)

http://recordit.co/iSITMrM4HS

**Comment by rstoenescu** [comment]
Will do along with SSR support. The documentation will be a Quasar SSR app ;)
Closing this as it belongs to the docs repo.
