### ISSUE TITLE
Avoid adding spacing for empty slots

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#11883]
Sometimes in Quasar, when you have conditional slot content (v-if), quasar will still apply extra slot spacing, causing UI quirks...
Here's an example of QInput using conditional content in the `#before` template:
https://codepen.io/robert123789/pen/VwMxpoJ

I would recommend adding some rules using a css :empty selector.  
For the codepen example, the following code helps default Quasar behave nicely when the slot is empty:
```
.q-field .q-field__before:empty, .q-field .q-field__prepend:empty {
  padding-right: 0px;  
}
```

There are probably many areas for which this could be a benefit, but luckily it look like most of them fall into the QField domain.

I think adding this feature would make Quasar an even more powerful and consistent UI library!

**Comment by pdanpdan** [comment]
That is because you use the slots in the wrong way.
As you use them you create slots with no content.
Move the condition on the template and you will have no slots.
