### ISSUE TITLE
Add 'title' prop for QVideo (accessibility)

### ISSUE THREAD

**Issue by joppehoekstra** [quasarframework/quasar#11894]
**Is your feature request related to a problem? Please describe.**
Currently, the [QVideo](https://quasar.dev/vue-components/video) component does not add a title to the iframe of the video that is being loaded. This causes [issues](https://web.dev/frame-title/?utm_source=lighthouse&utm_medium=lr#how-the-lighthouse-frame-title-audit-fails) for some screen readers.

**Describe the solution you'd like**
Add a 'title' prop for the QVideo component, which is passed through to the iframe.

**Comment by rstoenescu** [comment]
New prop (title) will be available in Quasar v2.4.3 and v1.17.

**Comment by joppehoekstra** [comment]
Awesome, love the speedy response!
