### ISSUE TITLE
Increase opacity QTimelineEntry Subtitle for accessibility purposes

### ISSUE THREAD

**Issue by joppehoekstra** [quasarframework/quasar#11895]
**Is your feature request related to a problem? Please describe.**
Currently, the opacity of the `.q-timeline__subtitle` class of the [QTimelineEntry](https://quasar.dev/vue-components/timeline#qtimelineentry-api) is set to 0.4. This causes the text to have too little contrast according to the [Web Content Accessibility Guidelines](https://webaim.org/resources/contrastchecker/). 

**Describe the solution you'd like**
Change the opacity of the `.q-timeline__subtitle` class to 0.6 to comply with the WCAG AA standard.

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.4.4 and v1.17.1
