### ISSUE TITLE
App •  WARNING  •  UI  in ./node_modules/keyv/src/index.js  Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by test4appdev1** [quasarframework/quasar#11899]
I got this error:

```
App •  WARNING  •  UI  in ./node_modules/keyv/src/index.js

Critical dependency: the request of a dependency is an expression
```

How can I solve it?

**Comment by pdanpdan** [comment]
The first step would be to make the minimal effort to use google and find this:
https://github.com/jaredwray/keyv/issues/45

Btw, read this: https://github.com/quasarframework/quasar/issues/8469

**Comment by test4appdev1** [comment]
I've already tried to do your way but couldn't solve it. It's better you show how to implement your way to quasar.conf.js.
