### ISSUE TITLE
Dependency warnings on `yarn install`

### ISSUE THREAD

**Issue by Shayan-To** [quasarframework/quasar#11906]
**Describe the bug**
I'm using yarn 3 with `node-modules` linker for my project, and everything is working fine. The only problem is every time I run `yarn install` or `yarn add`, some warnings are emitted that I think at most of them can be fixed by you.

```
PS> yarn
➤ YN0000: ┌ Resolution step
➤ YN0061: │ @types/compression-webpack-plugin@npm:9.1.1 is deprecated: This is a stub types definition. compression-webpack-plugin provides its own type definitions, so you do not need this installed.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ @quasar/babel-preset-app@npm:2.0.1 doesn't provide webpack (p2b9a9), requested by babel-loader
➤ YN0002: │ @types/compression-webpack-plugin@npm:9.1.1 doesn't provide webpack (pd4ce8), requested by compression-webpack-plugin
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1m 14s
...
```

If I understand correctly, the first one is saying there is a deprecated and now unnecessary dependency (it is a dependency of `@quasar/app` as `yarn why` says), and if this is fixed, the fourth warning will hopefully be gone as well.

And the third one is complaining about some unmet peer dependency in `@quasar/babel-preset-app`:

```
PS> yarn explain peer-requirements p2b9a9
➤ YN0000: @quasar/babel-preset-app@npm:2.0.1 doesn't provide webpack, breaking the following requirements:
➤ YN0000: babel-loader@npm:8.2.3 [c2c8b] → >=2 ✘
```

**Codepen/jsFiddle/Codesandbox**
The `package.json` file is available in [this Codesandbox](https://codesandbox.io/s/immutable-thunder-vy6i7?file=/package.json) and in [this zip file](https://github.com/quasarframework/quasar/files/7814151/package.json.zip).

**To Reproduce**
Put the `package.json` file from the previous section into a (possibly empty) folder, install yarn (`corepack enable`), and run `yarn` (or `yarn install`).

**Expected behavior**
No dependency warnings are emitted.

**Screenshots**
![image](https://user-images.githubusercontent.com/12458563/148199553-2496d1a1-5120-409d-99d2-862e95651a83.png)
![image](https://user-images.githubusercontent.com/12458563/148199567-66d51931-1dcb-4ddf-8414-f090ef7bc59b.png)

**Platform (please complete the following information):**
Quasar Version: 2.4.3
@quasar/app Version: 3.2.6

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [X] Typescript
- [X] SFC usage with `<script setup>`
- [X] Vuex
- [X] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows_NT(10.0.22000) - win32/x64
Node: 16.13.1
NPM: 6.14.15
Yarn: 3.1.1
Browsers: Microsoft Edge Version 96.0.1054.62 (Official build) (64-bit)
iOS: -
Android: -
Electron: -

**Additional context**
None.

**Comment by IlCallo** [comment]
> @quasar/babel-preset-app@npm:2.0.1 doesn't provide webpack (p2b9a9), requested by babel-loader
We cannot fix this into Qv2 lifecycle since it would require to change how we manage transitional deps (which is what q/app is based on)
It will be addressed into Qv3 release

The deprecation notice will be solved with the PR I just created
