### ISSUE TITLE
QBtn missing role="button" attribute

### ISSUE THREAD

**Issue by denovodavid** [quasarframework/quasar#11903]
**Describe the bug**
QBtn is missing the `role="button"` attribute by default since **v2.4.0**.

**Codepen**
https://codepen.io/denovodavid/pen/yLzELeG

**To Reproduce**
1. Make a `<QBtn />`
2. Inspect source
3. No `role="button"` attribute

**Expected behavior**
Expected to behave like **v2.3.4**, and have `role="button"` attribute.

**Platform**
Quasar Version: `2.4.3`

**Additional context**
Seems due to changes from 18c61d29d181a125e1ff54afb5f0b5b953330c1e
I was using `@testing-library/*` packages which recommend `getByRole` functions for max accessibility. Surely I don't have to add `role="button"` to all my `<QBtn />` uses, I think that should be implied.

**Comment by pdanpdan** [comment]
It was fixed in the just released 2.4.3 version
https://github.com/quasarframework/quasar/releases/tag/quasar-v2.4.3

Sorry, it was fixed before, in 2.4.2
And if it is rendered as a button it does not need the button role. The problem was that it was missing the type
