### ISSUE TITLE
The background of Dialog plugin is transparent 100% on some phone.

### ISSUE THREAD

**Issue by fisher030712** [quasarframework/quasar#11909]
On HuaWei phone, the background of Dialog plugin is transparent 100%.

.q-dialog__backdrop {
    background: #0006;
}

change to : background: rgba(0,0,0,0.6)，is OK。

and the q-btn, has same issue.

**Comment by pdanpdan** [comment]
Sorry, but you should use another browser (I don't know what browser is used by Huawei)
In case you need it then you should override the styles as it fits you, but we cannot change for everybody.
