### ISSUE TITLE
Q-select with @filter, "use-input" and "multiple" properties let the search string in the field after closing options list

### ISSUE THREAD

**Issue by jra11** [quasarframework/quasar#11919]
**Describe the bug**
Q-select with @filter and "multiple" properties has unusual behaviour. 

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
See this [Codepen](https://codepen.io/ju22/pen/LYzrQxq) which is forked from the official doc. 

**To Reproduce**
1. Go to the Codepen above
2. Focus on the select filed
3. Enter "Face" without typing enter
4. Select "Facebook" with the mouse

**Expected behavior**
It should only display Facebook. Instead, it displays "Facebook Face"

**Comment by pdanpdan** [comment]
Hello.
The behavior you describe is the expected one: being multiple the filter is kept in case you want to select some other option.

But what is not right is that when you unfocus the QSelect/close the popup the filter is not cleaned.

So please change the title in `Q-select with @filter, "use-input" and "multiple" properties let the search string in the field after closing options list` so we can track it.

Thank you

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.12 & v1.17.7
