### ISSUE TITLE
Bottom sheet action is missing property "id"

### ISSUE THREAD

**Issue by suneab** [quasarframework/quasar#11924]
**Describe the bug**
The "id" property is missing on the actions type for Bottom Sheet. The API shows no "id" field under actions https://quasar.dev/api-explorer#api--bottomsheet

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Everything works if you ignore the typescript warnings https://jsfiddle.net/pm4v0jg9/1/

**To Reproduce**
Copy paste the examples for how to use the component here: https://quasar.dev/quasar-plugins/bottom-sheet#usage
Implement in your IDE with any typescript validation

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/14541593/148390031-3c4daa5f-6501-4839-bab4-6762c4bb0c6b.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.4.3

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [x] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [x] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: OSX 12.0.1
Node: 16.13.0
NPM: 8.1
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
This issue could have been posted in the incorrect docs folder, but i think this variable is very valuable as no other reliable  identification for the selected answer is available

**Comment by pdanpdan** [comment]
Please change the title to request changes in TS definition to allow extra properties in actions objects
The `id` key is an extra property, so it is not specified in the definition

**Comment by rstoenescu** [comment]
There's no need for the `id` prop.

**Comment by suneab** [comment]
Labels aren't necessarily unique. A unique identifier for each option would be valuable.

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.4.4
