### ISSUE TITLE
QCarousel: add an option to unselect the current image by clicking on the thumbnail already selected

### ISSUE THREAD

**Issue by jra11** [quasarframework/quasar#11936]
I suppose that many developers use the QCarousel component as an optional Image selector. Unfortunately, there is no native mean to "unselect" an image by clicking the selected thumbnail, except selecting another one.

An easy alternative is to make a "reset" or unselect button, but it would be more practical to click on the selected thumbnail to empty the model.

A props called: "thumbnail-unselect" would be nice.

**Comment by pdanpdan** [comment]
You just need to manage your model
https://codepen.io/pdanpdan/pen/KKXBZXP?editors=101
