### ISSUE TITLE
[Request] - Datatable (v0.15) - Emit computedPagination event ?

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1193]
### Software version

Quasar: 0.15
OS: Linxu & Windows
Node: 6.11
NPM: 4.1.2
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Maybe I did not look properly, but on the datatable component there does not seem to be any event emitted while 
* Page changed programmatically or using datatable pager.
* Search/Filter content changed programmatically or using datatable pager.

### What were you expecting?
Having those event could allow us to detect when sorting or current page number change. What if we want to store those settings into a store and then restore it later ?

The only thing I saw is 
![image](https://user-images.githubusercontent.com/7946730/33289856-dc0b6c60-d38e-11e7-96af-433bdfd43b4d.png)

AFAIR `this.refs` is not reactive so I can't watch like this
```js
 watch: {
    '$refs.myDatatable.computedPagination': {
      handler(newVal) {
        console.dir(newVal);
      },
      deep: true,
    },
  },
```

**Comment by rstoenescu** [comment]
Hi,

You can use a "pagination" variable and watch that instead.

**Comment by purell** [comment]
This is what I've tried so far, but without success. By pagination variable you mean `computedPagination` computed property of datatable ?

But how to watch it ?

```js
watch: {
    '$refs.myDatatable.computedPagination': {
      handler(newVal) {
        console.dir(newVal);
      },
      deep: true,
    },
  },
```
Because this does not work :(

**Comment by purell** [comment]
Ok, I finally found it, I forgot about the `sync` modifier of vue-js and the fact that you allow using it with `emit('update:pagination')`. Hope this will help someone else ;)

```jsx
    <q-table
      ...
      :pagination.sync="pagination"
```

```js
  data() {
    return {
      pagination: {
        page: 1,
        rowsPerPage: 5,
      },
    };
  },
  watch: {
    pagination: {
      handler(newVal) {
        console.dir(newVal);
      },
      deep: true,
    },
```

**Comment by cqazsxer** [comment]
is 0.15 published? @rstoenescu

**Comment by rstoenescu** [comment]
not yet. mid-January.
