### ISSUE TITLE
[Request] - Datatable (v0.15) - Go to row's page ? 

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1194]
Hi,

It should be useful to allow seeking the page of a specific row. But actually, the datatable exposes only the data it displays on the screen instead of all computed rows before the pagination occurred.

* Here we are at page **2** 
* We see the **Honeycomb** row at 3rd position (`computedRows[2]`).
* The computed property `computedRow` of the datatable is holding only **5** rows. Thus, those we are seeing.

![image](https://user-images.githubusercontent.com/7946730/33290251-1fe4825e-d390-11e7-8ca1-d765fab7c5d6.png)

What if I come back to first page

![image](https://user-images.githubusercontent.com/7946730/33290379-7cb9bc06-d390-11e7-9d02-3cf2f68af995.png)

Now : 
* computedRows is still holding 5 rows, but this time the `computedRows[2]` is not `Honeycomb`. It is `Eclair`.  
* I no longer have access to the rows of the second page as `computedRows` only hold those we are seeing on the screen. Sure, we could access it by looking at the initial model pass to the datatable but this one is not filtered or sorted so this is not going to work to find the page of a row.

May be we should two computed property on the datatable to overcome this.

```js
computed: {
   // This property hold the computed rows after they have been filtered and sorted.
    computedRows () {
      let rows = this.data.slice()

      if (rows.length === 0) {
        return []
      }
      if (this.isServerSide) {
        return rows
      }

      const { sortBy, descending, rowsPerPage } = this.computedPagination

      if (this.hasFilter && this.filter) {
        rows = this.filterMethod(rows, this.filter, this.computedCols)
      }

      if (this.columnToSort) {
        rows = this.sortMethod(rows, sortBy, descending)
      }

      return rows
    },
   // This property is holding the computed row before the filtering, sorting and pagination occurred.
    computedUnpaginatedRows () {
      let rows = this.computedRows;

      const { rowsPerPage } = this.computedPagination
      if (rowsPerPage) {
        rows = rows.slice(this.firstRowIndex, this.lastRowIndex)
      }

      return rows
    },  
```

@rstoenescu If you care about `duplicated memory` issue, we could create a mirror array holding only **the key** of rows once they have been filtered, ordered and paginated. This is what I do in the new tree component and it work well without sacrificing functionality ;)

Without exposing rows before they get paginated, I see no other solution to seek the page of specific row.

**Comment by kidox** [comment]
Any plans to implement the "go to row page" functionality?

It would be very useful when inserting new data rows to a paginated table and after adding it the newly created column is not visible because it is in another page.

**Comment by rstoenescu** [comment]
Hi,

Sorry for not closing this along with the v1.7.2 release. There is a "scrollTo(index)" method with virtual-scrolling (not pagination).
