### ISSUE TITLE
Add to property to QTable rows

### ISSUE THREAD

**Issue by Greenscreen23** [quasarframework/quasar#11941]
**Is your feature request related to a problem? Please describe.**
For a QTable, I would like to turn every row into link. Currently, QTables only support a "row-clicked" event, and it is not possible to turn every row of a QTable into a link. It is possible to add `router.push` to the row-clicked function, but this doesn't add the usual options to open a link in a new tab, like normal links. (So _right click -> open in new tab_, _ctrl + left click_ and _middle mouse click_ are not working)

**Describe the solution you'd like**
I would like to be able to add a "to" property to each of my rows and then have that row be turned into a clickable link.
This could be implemented by wrapping all rows inside a `<router-link>` element with `display: contents` set. Here's a JSFiddle which demonstrates how this can be implemented manually in quasar: https://jsfiddle.net/Greenscreen23/twekxLp9/28/ (I've replaced the `<router-link>` with an `<a>` Element for demonstration purpose only)
Because changing an entire table is a quite tedious process, I think it'd be nice if this was already build into quasar. This solution currently also has the problem that rows are not highlighted when you hover over them, for which I have not found a solution.

**Describe alternatives you've considered**
1. The easiest solution is to add a `router.push` call to the "row-clicked" function, which has the aforementioned problems of not offering any options to open the link in a new tab.
2. I've also tried wrapping the content of each `<q-td>` element in a `<router-link>`. This results in parts of the row being clickable and other parts not being clickable.

**Comment by pdanpdan** [comment]
You cannot have links as tr in table

**Comment by Greenscreen23** [comment]
Please take a look at my jsfiddle, I think it is possible, using `display: contents`

**Comment by pdanpdan** [comment]
Yes, sorry, you cannot have a link as a child of tr and parent of td - even if chrome or some browsers allow it
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#technical_summary
It would break at least in SSR if not in a lot of browsers

**Comment by Greenscreen23** [comment]
Hm, I was hoping that because it appeared to be working on chrome and firefox (which are the majority of engines used if I'm correct), desktop as well as mobile, (and safari on macos as far as I've heard) that this was something that might be experimental, but possible.
