### ISSUE TITLE
Qbreadcrumbs not coloring when active navigation

### ISSUE THREAD

**Issue by laferte-tech** [quasarframework/quasar#11959]
Hello,
before upgrading to 2.4, Qbreadcrumbs elements where coloring (based on active-color) when they were active (using to for navigation)

Please check example below:

[https://codesandbox.io/s/nostalgic-parm-hb6we?file=/src/components/bread.vue](https://codesandbox.io/s/nostalgic-parm-hb6we?file=/src/components/bread.vue)

When navigating between Index, page2 and page3, the breadcrumb element is not coloring (based on active-color) and active class is not applied either to element.
Downgrading to 2.3 and you can see that the active-color is applied.

Thanks for your help.

**Platform (please complete the following information):**
Quasar Version: 2.4.4

Quasar mode:
  - [X ] SPA

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.4.5
