### ISSUE TITLE
The 'val' prop of the 'q-radio' component does not accept the 'undefined' type

### ISSUE THREAD

**Issue by linvsendian** [quasarframework/quasar#11955]
**Describe the bug**
The 'val' prop of the 'q-radio' component does not accept the 'undefined' type but the 'model-value' does accept. I can really ignore it but the typescript error warning is quite annoying.

**Expected behavior**
The 'val' prop should accept the 'undefined' value.

**Screenshots**
Type 'undefined' is not assignable to type 'string | number':
<img width="1013" alt="Screenshot 2022-01-08 at 15 36 13" src="https://user-images.githubusercontent.com/34980601/148648217-30e7c6c6-844c-4123-9d48-3af7aa261e5b.png">

Possible solution:
<img width="1024" alt="Screenshot 2022-01-08 at 15 47 34" src="https://user-images.githubusercontent.com/34980601/148648748-1bfaefdb-3df5-4279-9117-889f2022dd39.png">

**Platform (please complete the following information):**
Quasar Version: 2.4.4

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [x] Vite Plugin

Additonal Info:
- [x] Typescript
- [ ] SFC usage with `<script setup>`
- [ ] Vuex
- [ ] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac
Node: Latest
NPM: Latest

**Comment by pdanpdan** [comment]
Not commenting on the main request, but what would be the point on a radio with undefined value?
I understand null, but undefined?

**Comment by linvsendian** [comment]
> Not commenting on the main request, but what would be the point on a radio with undefined value?
> I understand null, but undefined?

I can really have an interface or object with an optional property, and this property is the param which I wanna pass to the 'val' property of the 'q-radio', and when the radio is checked, I need the property can be assigned with 'undefined' value.

**Comment by rstoenescu** [comment]
I don't agree with val being undefined, but regardless, it will be available in Quasar v2.4.5
