### ISSUE TITLE
Loadingbar - disable per component/allow-list?

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#11952]
**Is your feature request related to a problem? Please describe.**
I really like the loadingbar plugin, however it doesn't play nicely when doing a lot of API requests.

For instance, I'm running a VOD app which receives segments every X seconds, leading to the loadingbar being activated all the time.

**Describe the solution you'd like**
Allow to disable the loadingbar per component or allow/block-list.

**Describe alternatives you've considered**
```
config: {
      loadingBar: {
        skipHijack: true
      },
    },
```
However, this doesn't integrate nicely with API requests and I need to manually calculate each loading.

**Additional context**
N/A

Thanks!

**Comment by pdanpdan** [comment]
The loading bar does not hook to components but to xhr requests, which could come from whatever code started them. You cannot filter by components.

**Comment by francoism90** [comment]
@pdanpdan Thanks for the explanation. :)

It cannot be done filtering on XHR requests? Like with a custom callback.

**Comment by pdanpdan** [comment]
Now there is no way, I'm sorry.

**Comment by francoism90** [comment]
@pdanpdan No worries! :)

**Comment by rstoenescu** [comment]
I wanted to implement some filters for a long time (for QAjaxBar and implicitly for LoadingBar), so reopening. Will work on them.

**Comment by francoism90** [comment]
@rstoenescu Great news! Take your time, it's not a must, more a nice to have. :)

**Comment by rstoenescu** [comment]
Will be available through new prop (hijack-filter Function) in Quasar v2.4.5

**Comment by francoism90** [comment]
@rstoenescu Great stuff! :D

Could you please give more examples?

What if I want to exclude a path: `https://my-service.com/api/v1/ignore`
From the looks of it, I can parse the given URL and simple return false/true to use the loadingbar? :)

**Comment by MilosPaunovic** [comment]
As the new sample code states:

```js
import { LoadingBar } from 'quasar'

LoadingBar.setDefaults({
  // return a Boolean which has the meaning of
  // "does this URL should trigger LoadingBar?"
  hijackFilter (url) {
    // example (only https://my-service.com/* should trigger)
    return /^https:\/\/my-service\.com/.test(url)
  }
})
```

You could filter the path in question however you like and eventually return `false` if you don't want `LoadingBar` to show.

**Comment by francoism90** [comment]
@MilosPaunovic I another way to parse the path:
```
hijackFilter(url: string) {
        const parsedUrl = new URL(url);

        return parsedUrl.pathname.includes('api');
      },
```
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

You can use different kind of matches as well, like the hostname. :)

**Comment by MilosPaunovic** [comment]
> You can use different kind of matches as well, like the hostname. :)

You can use whatever your heart desires, as long as you return a `Boolean` value 🙂

**Comment by ibrainventures** [comment]
Great feature.
Tested and works fine. May for the docs:
If the api call is inside your webroot, there is no webserver adress inside the url param.

And for a more "programmatic" way, i soluted it by a "contains not" regex and so
i can add e.g. a ?q=tpisd to my calls (which means, this is a silent request):

```
     hijackFilter (url) {
        return /^((?!tpisd|othersilentword).)*$/.test(url)
      }
```

**Comment by maggie44** [comment]
> Will be available through new prop (hijack-filter Function) in Quasar v2.4.5

Can it be specified through the quasar.conf.js config for the loading bar too?

```
    framework: {
      config: {
        loadingBar: {
          color: 'primary',
          size: '7px',
          position: 'bottom',
          hijackFilter(url) {
            console.log(url)
            const parsedUrl = new URL(url)

            return !parsedUrl.pathname.includes('systeminfo')
          }
        }
      },
```

**Comment by rstoenescu** [comment]
@maggie0002  No, because quasar.conf.js runs in a Nodejs context, and that function should be part of your UI code.
Use the setDefaults() in a boot file instead.
