### ISSUE TITLE
QToggle - slot for `checked-icon` / `unchecked-icon` / `indeterminate-icon`

### ISSUE THREAD

**Issue by Zefau** [quasarframework/quasar#11958]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to use a customized icon which is not part of the Quasar imported icon sets, e.g from Iconify.

**Describe the solution you'd like**
I would appreciate a slot to customize the icon on the QToggle (https://quasar.dev/vue-components/toggle#with-icons).

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by rstoenescu** [comment]
Hi,

This is not needed. You can use whatever icon set you want by providing a custom mapping: https://quasar.dev/vue-components/icon#custom-mapping

Please reopen if I missed anything.

**Comment by Zefau** [comment]
Would it be possible to inherit more attributes through `iconMapFn`? I need `data-icon` to be set, e.g.
```
$q.iconMapFn = iconName => {
	if (!iconName.startsWith('mdi') && iconName.indexOf(':') !== -1) {
		return {
			'cls': 'iconify',
			'data-icon': iconName
		}
	}
	
	return undefined;
}
```
