### ISSUE TITLE
[Request] Add iconfont support

### ISSUE THREAD

**Issue by relzhong** [quasarframework/quasar#1196]
[iconfont](http://iconfont.cn) is a font icon platform powered by alibaba. 

We can use it to add icon font for special project, and there are many people share their font.
Here is a font [css sample ](http://at.alicdn.com/t/font_483168_4dff2aafa9d4pldi.css) in one of my project.

Font css import a  font-family named `iconfont`, however the **icon name define is conflict with Ionicons.

I think it can be solved by adding  `iconfont` class to icon if icon is starts with  'icon-' 
replace this line by `name = iconfont ${icon}`
https://github.com/quasarframework/quasar/blob/06bd98b866a70a42702c94e8763e4fd2130ecae7/src/components/icon/QIcon.js#L31

**Comment by zuck** [comment]
Nice :+1: 

By the way, it's more an issue for [quasarframework/quasar-extras](https://github.com/quasarframework/quasar-extras).

Look at https://github.com/quasarframework/quasar-extras/pull/5 and https://github.com/quasarframework/quasar-extras/pull/6.

**Comment by relzhong** [comment]
Actually, I think we use quasar-extras to import css locally, but we can also link css directly in http head.

As iconfont is a platform that store different people's font icon, everyone has his own css file, so I think it may not good to be placed in quasar-extras. Adding css link in http head is a better plactice.
@zuck

**Comment by rstoenescu** [comment]
Closed as per @relzhong
