### ISSUE TITLE
Hover on menu items has lag

### ISSUE THREAD

**Issue by darkopetreski** [quasarframework/quasar#11970]
### What happened?

When I hover over some q-items, example select, navigation... there is a lag - the hover effect appears with delay when I hover over the items. This is happening on Chrome version 97 on KUbuntu. This lag/hover delay only happens on quasar components and does not occur on other components/pages. I have also tried other frameworks like vuetify the hover works fine. Just the quasar components has this hover delay. So since I haven't seen any other pages/components with this hover delay I assume this is a quasar bug. I use Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz so the performance of the PC is pretty good.

![chrome-capture](https://user-images.githubusercontent.com/4987585/148795180-e3dbd457-6e92-4630-9b75-c5eeb53b9d26.gif)

On other browsers like Firefox forks fine.

### What did you expect to happen?

When I hover over those items I expect to see the hover effect with no delay.

### Reproduction URL

https://quasar.dev/vue-components/select

### How to reproduce?

Open any page that contains q-select. Hover over the items. The hover effect should be noticeable delayed. 
I have noticed this problem on Kubuntu and Chrome 97. Unfortunately I haven't tested it with other OS. Also even if I have only one component per page in my project, the same delay occurs. Other browsers like Firefox forks fine.

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```shell
Operating System - Linux(5.4.0-92-generic) - linux/x64
NodeJs - 17.3.0

Global packages
  NPM - 8.3.0
  yarn - 1.22.17
  @quasar/cli - 1.2.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.3.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.2.5 -- Quasar Framework local CLI
  @quasar/extras - 1.12.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.24 -- The progressive JavaScript framework for buiding modern web UI.
  vue-router - 4.0.12
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.0 -- Babel compiler core.
  webpack - 5.65.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.6.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.4.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qenv - 1.1.0 -- Load targeted variables into your quasar project

Networking
  Host - 7bd0f5b3bfbe
  eth0 - 172.17.0.3
```

**Comment by pxDot** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/11967

**Comment by darkopetreski** [comment]
Additional info, on my other workstation, KUbuntu 20.04, chrome 97, same as the test case with the bug above it works fine. The only difference is that on the pc with the bug I do not have any graphics card attached.

**Comment by darkopetreski** [comment]
Since it is duplicate, I will close this one.
