### ISSUE TITLE
QMenu breaks input field

### ISSUE THREAD

**Issue by ivanjaros** [quasarframework/quasar#11971]
### What happened?

I am working on autocomplete search input where I have search input and qmenu to display results via list.
The problem I have observed is that the input's focus is not working properly. The behavior is that when I click into the search input, it immediately defocuses so I have to click for the second time. Another case is when I click once, then click away and click back into the input and it again requires two clicks. If the input is wrapped in another element, it still does not isolate the behavior and does not fix anything. This can be easily reproduced with this simple template:

```
<div>
    <q-input v-model="text"></q-input>
    <q-menu></q-menu>
</div>
```

where text is used only so the input will render.

Wrapping the menu into something fixes the behavior but that should not be required since it does not have touch-position property. **It also defocuses the input once it is open**.

### What did you expect to happen?

Standard focus behavior of the input field.

### Reproduction URL

https://jsfiddle.net/836dbL4n/

### How to reproduce?

Click once into the input and see that it defocuses immediately.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
Check QMenu props related to focus

**Comment by ivanjaros** [comment]
> Check QMenu props related to focus

no-focus/no-refocus seem to be working in that jsfiddle. I will test it tomorrow in my code but is seems to fix the problem. Thanks.
