### ISSUE TITLE
Inconsistent and duplicated focus opacity on q-focus-helper

### ISSUE THREAD

**Issue by pxDot** [quasarframework/quasar#11975]
### What happened?

q-focus-helper has some duplicated and inconsistent styles which causes a incoherent behaviour in style and additionally making it hard to override:
https://github.com/quasarframework/quasar/blob/0e856ac41d8c3430debea209c84ad4fab8196da7/ui/src/css/core/visibility.sass#L151-L162

### What did you expect to happen?

Styles should be concise and consistent to ensure a smooth and coherent look & feel.

### Reproduction URL

https://quasar.dev/vue-components/menu

### How to reproduce?

1. go to reproduction link
2. set a menu item to hover in dev console
3. set a menu item to focus in dev console
4. notice a slight change of background opacity

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Hello. What do you think is wrong with that definition?
The opacity is different for `.q-focusable:focus, .q-manual-focusable--focused ` and for `.q-hoverable:hover`
What you did in the PR is remove that difference

**Comment by pxDot** [comment]
> Hello. What do you think is wrong with that definition?
> The opacity is different for `.q-focusable:focus, .q-manual-focusable--focused ` and for `.q-hoverable:hover`
> What you did in the PR is remove that difference

You are right, it should have some difference between a hovered state and a focussed state.
My confusion comes from a `QItem` in a `QList` which has `manual-focus` and `focused` property. When enabled it ignores hover state though and is only manually focusable but not hoverable.

I guess I just override the styles for this component in my application to have the same style for hover and focus state, although I find it a bit confusing and am not sure if it is the expected behaviour to disable hover styles with enabled `manual-focus`.

**Comment by pdanpdan** [comment]
Can you please make a codepen with your code sample to understand exactly what you need?

**Comment by pxDot** [comment]
> Can you please make a codepen with your code sample to understand exactly what you need?

See here: https://codepen.io/squareloop1/pen/qBPQROK

Notice how the middle list item with `:focused="false"` doesn't have any hover effects?

**Comment by pdanpdan** [comment]
You can try adding the `q-hoverable` class to QItem with `manual-focus` if you need
https://codepen.io/pdanpdan/pen/xxXQgXa?editors=1010

But `manual-focus` is sort of a special use case where you want to control the focus with events happening in another place

Tell me if there are still problems

**Comment by pxDot** [comment]
> You can try adding the `q-hoverable` class to QItem with `manual-focus` if you need https://codepen.io/pdanpdan/pen/xxXQgXa?editors=1010
> 
> But `manual-focus` is sort of a special use case where you want to control the focus with events happening in another place
> 
> Tell me if there are still problems

Thank you very much. Seems like that was the piece I was missing.
