### ISSUE TITLE
QBreadcrumbsEl has `.q-breadcrumbs--last` applied to all but the last element

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#11976]
### What happened?

The last class is applied incorrectly. 

### What did you expect to happen?

The last class should only be on the last item.

### Reproduction URL

https://codepen.io/Mett-codepens/pen/BawqrZz

### How to reproduce?

1. Open the element inspector and check the elements classes

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar), Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.5
