### ISSUE TITLE
Localstorage empty string bad behavior

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1199]
### Software version

Quasar:0.14 and 0.15
OS:Windows & Linux
Node:6.x
NPM:4
Browsers:Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

Storing an empty string with LocalStorage result in storing this `__q_strn|`. But if we read the value we get `__q_strn|` instead of `""`

![image](https://user-images.githubusercontent.com/7946730/33354786-8136fa80-d482-11e7-911d-acd803aef3e4.png)

### What were you expecting?

Storing an empty string and getting an empty string.

### What steps did you take, to get the error?

```js
LocalStorage.set('foo', '');            // Store __q_strn|
const c = LocalStorage.get.item('foo'); // c contains "__q_strn|" instead of ""
```

I fix the problem here https://github.com/quasarframework/quasar/pull/1198

**Comment by rstoenescu** [comment]
Thank you for providing a PR as well! It's available in future v0.15.

**Comment by desarrollador1IR** [comment]
Hi, sorry for ask but i have an issue with this

`$q.sessionStorage.set('access_token', response.data.token)`

and in the sessionStorage "__q_strn| ey...restofthetoken", how can i fix this?

**Comment by rstoenescu** [comment]
@desarrollador1IR The LocalStorage/SessionStorage is designed to retain the type of the thing that you are storing. So, if you set it with LocalStorage/SessionStorage, read it with it too.
