### ISSUE TITLE
QEditor fullscreen mode in QStepper bug

### ISSUE THREAD

**Issue by KINGER404** [quasarframework/quasar#11997]
### What happened?

After turning off fullscreen mode in a QEditor placed in a QStepper, the current QStep disappears

### What did you expect to happen?

Expected normal QStepper operation

### Reproduction URL

https://codepen.io/kinger404/pen/MWEzWqQ?editors=1010

### How to reproduce?

1. Click on fullscreen mode in QEditor
2. Turn off fullscreen mode in QEditor
3. See the bug

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.12 & v1.17.7
