### ISSUE TITLE
q-icon doesn't properly resize SVG images since 1.17+

### ISSUE THREAD

**Issue by tomlukman** [quasarframework/quasar#12002]
### What happened?

q-Icons that come from a svg source don't get properly scaled
Preview: https://www.screencast.com/t/ygkg2trx

I noticed this on buttons first, but other slots using q-icon seem to be affected with this.

### What did you expect to happen?

Before 1.7 update: https://www.screencast.com/t/CQTLq7r2DNu

### Reproduction URL

https://codepen.io/tom_lukman/pen/yLzQXrv

### How to reproduce?

Just add any icon="img:something.svg"

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by MilosPaunovic** [comment]
PR (for `Q2`) is here, #12001, should be backported to `Q1`, as well.

**Comment by rstoenescu** [comment]
Fixed it for Quasar v2.4.8 and v1.17.3 (will be released soon)
