### ISSUE TITLE
QTree expand/collapse bug and how to fix it

### ISSUE THREAD

**Issue by MTLink** [quasarframework/quasar#1200]
QTree expand/collapse functionality doesn't work in some cases. For example if tree model is dynamicaly created. The reason for this is an error in quasar/src/components/tree/TreeItem.vue 
Vue framework doesn't  allow to change props inside component
`this.model.expanded = !this.model.expanded` -- not correct

Therefore it is I needed add
```
data: function () {
  return { expanded: this.model.expanded }
}
```
And then use `expanded `instead of `model.expanded`

**Comment by rstoenescu** [comment]
Available in future v0.15
