### ISSUE TITLE
QScrollArea mouse press in the area next to thumb causes undesirable scroll jump

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#12018]
### What happened?

When scroll bar is slightly wider than thumb (almost always), if you miss the thumb with your mouse even by 1 pixel, the scroll position will jump, so that mouse is in the middle of the thumb, and only then thumb pan activates.

Relevant lines:

https://github.com/quasarframework/quasar/blob/b10202d94579e42269ea74e812c2ddc8ab71b46f/ui/src/components/scroll-area/QScrollArea.js#L314-L315

Screencast:
![msedge_1n4CMMSHfi](https://user-images.githubusercontent.com/2260539/149253898-fa438e65-e8ef-471c-b4b0-9be6d0b3fd36.gif)

### What did you expect to happen?

Ideally, the code would check if the mousepress is within the vertical/horizontal bounds of the thumb, and if it is, then it would not run the `setScroll` method, and instead launch the thumb pan immediately.

### Reproduction URL

https://codepen.io/thexeos/pen/vYeQMPx

### How to reproduce?

1. Open the Codepen
2. Click and drag from the thumb - notice how there is no "jump" when you click on it
3. Click and drag from 2-4 pixels to the left or to the right of the thumb - notice how the thumb jumps into position

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Additional context

It appears all the information to calculate this is available in the function - the dimensions of the thumb, the position of the thumb, and the position of the mouse press.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.9 and v1.17.4
