### ISSUE TITLE
BEX opens with vertical scrollbar in Chrome

### ISSUE THREAD

**Issue by thdoan** [quasarframework/quasar#12015]
### What happened?

On my Windows 10 PC with 1920x1080 resolution, I see a vertical scrollbar when opening the default BEX app:

![image](https://user-images.githubusercontent.com/4110567/149216844-b741251d-da0d-4d66-9a6c-deebd780febd.png)

The scrollbar goes away when you resize the window and maximize it again, but the page is still scrollable, as evident here:

https://www.loom.com/share/89c1ac9ea4cb480fb10cae13d7c9ad67

### What did you expect to happen?

I expect there to be no vertical scrollbar visible since the page only contains a single image in the center.

### Reproduction URL

https://github.com/quasarframework/quasar

### How to reproduce?

1. Create a new Quasar project
2. `quasar dev -m bex` to build the BEX
3. Click on extension icon to open the app
4. Note the vertical scrollbar

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

BEX Mode

### Platforms/Browsers

Chrome

### Quasar info output

```shell
Operating System        Windows_NT(10.0.19043) - win32/x64
NodeJs                  16.1.0

Global packages
  NPM                   8.1.4
  yarn                  1.22.17
  @quasar/cli           1.2.2
  @quasar/icongenie     Not installed
  cordova               Not installed
```

### Additional context

Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
Should be fixed in Quasar v2.5.3 and v1.18.3
