### ISSUE TITLE
Intersection Directive Sample Ambiguity

### ISSUE THREAD

**Issue by PowerWeb5** [quasarframework/quasar#12035]
In samples at https://quasar.dev/vue-directives/intersection there is no indication that each sample is scrollable in that page on mobile devices (as there is no scrollbar), hence the confusion. Even with the Tip instructions, it seems as if supposed to scroll down page until each red box is in view (scroll down to additional samples), as opposed to scrolling down to the sample and then scrolling within it to the Observed Element. It seemed as if the red div labeled Hidden is the Observed Element. Either showing a scrollbar on mobile or changing the text from Hidden to "Hidden Below" would clear up any confusion.

**Comment by pdanpdan** [comment]
It is working just fine

**Comment by PowerWeb5** [comment]
There is no indication that each sample is scrollable in that page on mobile devices (as there is no scrollbar), hence the confusion. Even with the Tip instructions, it seems as if supposed to scroll down page until each red box is in view (scroll down to additional samples), as opposed to scrolling down to the sample and then scrolling within it to the Observed Element. It seemed as if the red div labeled Hidden is the Observed Element. Either showing a scrollbar on mobile or changing the text from Hidden to "Hidden Below" would clear up any confusion.
