### ISSUE TITLE
pull to refresh callback not working

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [quasarframework/quasar#1203]
version 0.14.7
using default cli template

getting error: TypeError: refreshDoneCallback is not a function(…)

my method

```javascript
fetchTurmas(refreshDoneCallback) {

        Loading.show()

        console.log(this.$q)

        this.turmas = []

        this.$fs.collection('turmas').orderBy('nome').get()
          .then(turmasSnapshot => {
            turmasSnapshot.forEach(turma => {
              this.turmas.push({
                id: turma.ref.id,
                nome: turma.data().nome,
                reference: turma.ref.path
              })
            })
          })
          .then(() => refreshDoneCallback())
          .then(() => Loading.hide())
          .catch(error => {
            Alert.create({
              enter: 'fadeIn',
              leave: 'fadeOut',
              color: 'negative',
              html: 'Não foi possível carregar as turmas.',
              position: 'top'
            })
            console.log(error)
          })
      }
```

in the template 

```
<q-transition appear enter='fadeIn' leave='fadeOut' v-if='hasTurmas'>

      <q-pull-to-refresh
        :handler='fetchTurmas'
        pull-message='Puxe para atualizar'
        release-message='Solte para atualizar'
        refresh-message='Carregando'>

        <q-list separator sparse>
          <q-item v-for='turma in turmas' :key='turma.id'> <q-item-main :label='turma.nome'></q-item-main> </q-item>
        </q-list>

      </q-pull-to-refresh>

    </q-transition>
```

Note: putting pull to refresh inside or outside transition doesnt seem to change anything, i tried that just in case

**Comment by pdanpdan** [comment]
Can you do a console.log(refreshDoneCallback) in your method. Or put a breakpoint/add a debugger statement there and inspect.

**Comment by diego-lipinski-de-castro** [comment]
On first tries it was undefined, after i tried to move on to a new function, called only by the refresher, and then it worked (the callback was logging always as the actual cb function), i think that  it's because i was calling the older function on the mounted hook and then the callback was undefined at that time (because it wasnt called by the refresher), afterwards then it would work as inteded (when called by the refresher).
Feedback if that's fine and understood, then I can close this.

**Comment by rstoenescu** [comment]
Yes, you got this right. You can close this. Thanks for the explanations!
