### ISSUE TITLE
QSelect method `isOptionDisabled` returns the option when the disable option is not specified

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#12046]
### What happened?

Considering options like this:
`[ { label: '1', value: 1, disable: true }, { label: '2', value: 2 }, { label: '3', value: 3 } ]`
When calling the `isOptionDisabled` method on the first option it returns `true`.
When calling it on the second and third option it return the option itself which will also evaluate to true.

### What did you expect to happen?

The docs state that it should return a Boolean value, so it should always return a boolean. Also specifying `disable: false` on every option should not be necessary in my opinion. 

### Reproduction URL

https://codepen.io/Evertvdw/pen/WNZPvyL?editors=1011

### How to reproduce?

Not sure yet how to properly use a component ref in a codepen so I'm not able to call a method yet. When I find out I will share.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Maybe for performance reasons it is better to leave it as it is?
We have 3 uses, but each one can use a custom function to extract the value:
1. getOptionValue (can return anything)
2. getOptionLabel (should in theory return a string - or at least a non-object)
3. isOptionDisabled (should return boolean)

In the case of 3. the easiest way would be to just check it against true ( `=== true`)

**Comment by Evertvdw** [comment]
@pdanpdan Would it not be just as easy to return `false` here instead of `opt` at the end here: https://github.com/quasarframework/quasar/blob/3e9f39a441b395d939527a4644763755cc818cc6/ui/src/components/select/QSelect.js#L605

Or atleast undefined and cast it to a boolean in https://github.com/quasarframework/quasar/blob/3e9f39a441b395d939527a4644763755cc818cc6/ui/src/components/select/QSelect.js#L1387

Or change the documentation :)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.14.
