### ISSUE TITLE
[TS] Platform broken since 2.4.10

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#12054]
### What happened?

```
export interface Platform {
  /**
   * Client browser User Agent
   */
  userAgent: string;
  /**
   * Client browser details (property names depend on browser)
   */
  is: any;

...
}
```
This causes issues when doing something like this:
```
const isUsable = () => Platform.is.capacitor === true; // Unsafe member access .capacitor on an `any` value.
```
Why has this been changed? What should it return?

### What did you expect to happen?

Return platform type as seen in https://quasar.dev/options/platform-detection#introduction

### Reproduction URL

https://quasar.dev/options/platform-detection#introduction

### How to reproduce?

```
const isUsable = () => Platform.is.capacitor === true; // or any other value like desktop.
```

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

TypeScript Support

**Comment by diadal** [comment]
Yes same issue

**Comment by yvhr** [comment]
Experiencing the same issue after issuing `quasar upgrade -i`

**Comment by yusufkandemir** [comment]
This is a side-effect of #12045. It previously was a loose object type, but it's now `any`, which causes this error.

I am working on providing something that will both fix the error and provide better types than before.
```ts
export interface Platform {
  /**
   * Client browser User Agent
   */
  userAgent: string;
  /**
   * Client browser details (property names depend on browser)
   */
  is: {
    /**
     * Browser name
     */
    name: string;
    /**
     * Platform name
     */
    platform: string;
    /**
     * Whether the browser is a desktop browser
     */
    desktop?: boolean;
    
    // ...
  };
  // ...
};
```
