### ISSUE TITLE
Input visibility problem

### ISSUE THREAD

**Issue by GuilhermeErmel** [quasarframework/quasar#12078]
### What happened?

Hello,

I'm having a behave problem using a set of Quasar components (in current Chrome 97.0.4692.71). I have a 'sign in' page where the password input allows change the value visibility and it also has a button to clear its value... Well, is very simple.

https://codepen.io/ermel/pen/vYebBoR?editors=1011
https://cdpn.io/ermel/debug/vYebBoR/GnAnbXDDOdeA

However, when the user already has an email/password saved in browser and click to 'see the password' the input value is not displayed (but the model value stil is there - if you blur and focus the input one more time and then click to 'see the password' again, the value will be displayed).

### What did you expect to happen?

The password input should show its value

### Reproduction URL

https://codepen.io/ermel/pen/vYebBoR?editors=1011

### How to reproduce?

Steps:
1. Save an user and password
![image](https://user-images.githubusercontent.com/32545608/149808061-24782190-873d-450b-b68c-526342054391.png)

2. After accessing the sign in
![image](https://user-images.githubusercontent.com/32545608/149808081-bed71d40-0d0c-4410-a169-7ad41e4eccba.png)

3. Click to see the password
![image](https://user-images.githubusercontent.com/32545608/149808100-006e80a7-c598-42c3-8fd1-6b75b691f3f2.png)

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Additional context

**The problem seems to be in 'QBtn' + 'v-if'** (NOT in the 'QIcon' who shows/hides the password)!

If:
- I use 'QIcon' instead 'QBtn' it works
- I use 'v-show' instead 'v-if' it works
- I use 'Firefox' it works

Thanks!

**Comment by pdanpdan** [comment]
Works for me
https://codepen.io/pdanpdan/pen/MWExzPK?editors=1011

**Comment by GuilhermeErmel** [comment]
Did you access in debug mode (on codepen)?

After click in 'Show login', Chorme autocompletes the inputs. Then, if I click to see the password, its value isn't displayed.

_Remembering: First you need to fill the user and password and submit the form to Chrome to suggest saveing these informations._

**Comment by babalubas090** [comment]
I'm having the same issue here...  I put the code of the CodePen sandbox that @GuilhermeErmel did in the CodeSandbox and the problem can be simulated more easily. 

https://codesandbox.io/s/laughing-rubin-00nyi

Noting that Chrome's autofill doesn't work in the iframe mode that is exhibited in the CodeSandBox. With that in mind, you need to open the link that is displayed in the URL bar above the iframe, in a new tab.

If the link doesn't change automatically, you can access the simulation entering here:
https://00nyi.csb.app/

**Comment by GuilhermeErmel** [comment]
@pdanpdan

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.14.
