### ISSUE TITLE
Bump webpack-dev-server to resolve security vulnerability 

### ISSUE THREAD

**Issue by maggie44** [quasarframework/quasar#12076]
### What happened?

GitHub reports a package with a security vulnerability. webpack-dev-server needs updating to resolve it.

### What did you expect to happen?

Further details here: https://github.com/webpack/webpack-dev-server/issues/4167

### Reproduction URL

```
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "node-forge"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "node-forge@0.10.0"
info Reasons this module exists
   - "@quasar#app#webpack-dev-server#selfsigned" depends on it
   - Hoisted from "@quasar#app#webpack-dev-server#selfsigned#node-forge"
info Disk size without dependencies: "1.77MB"
info Disk size with unique dependencies: "1.77MB"
info Disk size with transitive dependencies: "1.77MB"
info Number of shared dependencies: 0
```

https://github.com/webpack/webpack-dev-server/issues/4167

### How to reproduce?

Push a Quasar app to GitHub with dependabot enabled. 

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by rstoenescu** [comment]
Will be available in "@quasar/app" v3.2.7
