### ISSUE TITLE
Any plan that tree support drag and drop

### ISSUE THREAD

**Issue by fyeeme** [quasarframework/quasar#12094]
### What happened?

Currently tree does not supported  drag and drop

### What did you expect to happen?

Offically supported  drag and drop

### Reproduction URL

https://codepen.io/fyeeme/pen/rNGbzoJ?editors=101

### How to reproduce?

1. click the tree and try to drag and drop 

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by fyeeme** [comment]
link has been updated

**Comment by pdanpdan** [comment]
duplicate of #6044, #7299, #5890, #6959
