### ISSUE TITLE
QTime minute-options

### ISSUE THREAD

**Issue by shiouming** [quasarframework/quasar#12116]
### What happened?

Steps to reproduce:
1. Visit QTime documentation page: https://quasar.dev/vue-components/time
2. Open Codepen from the docs page (version info displayed: QTime: Basic - Quasar v2.4.11).
3. Append minute-options to restrict minute selector to 4 options: 0, 15, 30, 45
`<q-time v-model="time" minute-options="[0, 15, 30, 45]"></q-time>`

Expected result:
The minute selector should only give 4 options: 0, 15, 30 and 45.

Actual result:
The minute selector gave 9 options: 0, 1, 2, 3, 4, 5, 15, 30 and 45.

Note: I'm not sure about the flavour used by the docs page.

Screenshot attached.
![screenshot-codepen-code-and-result](https://user-images.githubusercontent.com/37605886/150300425-95e77b39-8a38-4ee2-b43f-5da4c601f31b.png)

### What did you expect to happen?

The minute selector should only give 4 options: 0, 15, 30 and 45.

### Reproduction URL

https://quasar.dev/vue-components/time

### How to reproduce?

1. Visit QTime documentation page: https://quasar.dev/vue-components/time
2. Open Codepen from the docs page (version info displayed: QTime: Basic - Quasar v2.4.11).
3. Append minute-options to restrict minute selector to 4 options: 0, 15, 30, 45
`<q-time v-model="time" minute-options="[0, 15, 30, 45]"></q-time>`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
It's `:minute-options="[0, 15, 30, 45]"`
You are passing a string ("[0, 15, 30, 45]") and 5 is included in the string :)

**Comment by shiouming** [comment]
> It's `:minute-options="[0, 15, 30, 45]"` You are passing a string ("[0, 15, 30, 45]") and 5 is included in the string :)

Ah! I missed the colon. Thanks.
