### ISSUE TITLE
can't edit select field after reopen browser page on mobile

### ISSUE THREAD

**Issue by Vchekryzhov** [quasarframework/quasar#12113]
### What happened?

I can't edit my input in select with autocomplete on mobile device after reopen page. all my input is highlight and i can only delete it.
https://quasar.dev/vue-components/select#filtering-and-autocomplete
![select](https://user-images.githubusercontent.com/29312284/150220284-6709a022-2afb-442b-9c84-9c4d8891822e.jpg)

> 

### What did you expect to happen?

i expect that i can edit.

### Reproduction URL

https://codepen.io/vchekryzhov/pen/dyVEdzB?editors=101

### How to reproduce?

1. Go to the provide reproducing link on mobile devise, in my case it was chrome browser
2. type something in select
3. minimize the browser
4. open page again
5. your can't edit your input

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Tap around the text to unset the selected text.

This is by design as the vast majority of use cases require user to type something different.

**Comment by pdanpdan** [comment]
related: #11919

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.12 & v1.17.7

**Comment by Vchekryzhov** [comment]
thanks guys you are best
