### ISSUE TITLE
q-icon doesn't resize SVG images

### ISSUE THREAD

**Issue by leonbuild** [quasarframework/quasar#12137]
### What happened?

Firstly I want to thank you for your great work!

I do see the issue #12002, but this one seems to behave differently. 

I used to resize the svg images within q-icons by putting heights and widths in the style tag:
` <q-icon name="img:https://cdn.quasar.dev/logo-v2/svg/logo.svg" style="width:200px; height: 200px;"></q-icon>`

Previously it works fine, but after upgrading to 2.4.11, the svg image keeps staying at the default size, ignoring the style tag. 

### What did you expect to happen?

I do expect the svg image within the q-icons to resize according to the styles. 
Not sure whether this is a feature change or a bug. Please correct me if I'm doing anything wrong.

### Reproduction URL

https://codepen.io/r3t5n0m/pen/yLzdpZO

### How to reproduce?

` <q-icon name="img:https://cdn.quasar.dev/logo-v2/svg/logo.svg" style="width:200px; height: 200px;"></q-icon>`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
I would say you should better use `:size="200px"`
https://codepen.io/pdanpdan/pen/yLzdvEz

**Comment by leonbuild** [comment]
Thanks @pdanpdan , that's helpful!
Using a `class="inherit-icon-size"` is new to me.

**Comment by rstoenescu** [comment]
Stick with the 'size' prop, as QIcon is intended to be used.

The class approach is a custom class (not Quasar) in that example which overrides the width and height to the appropriate values.
