### ISSUE TITLE
QSelect cursor issue with use-input

### ISSUE THREAD

**Issue by jmroon** [quasarframework/quasar#12132]
### What happened?

When using the use-input property for QSelect, the input field has a cursor: pointer style applied to it.

![image](https://cdn.discordapp.com/attachments/806171748046733332/933834283452366848/q-select-input.gif)

### What did you expect to happen?

The input field should have a cursor: text style applied to it.

As the action is the same no matter where you click, changing to a pointer on the invisible input field is jarring. At most, I'd expect a cursor on the dropdown icon and other actionable icons (such as clearable)

### Reproduction URL

https://codepen.io/jmroon/pen/mdBZRyE

### How to reproduce?

Create a QSelect with use-input. Hover over different parts of it.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Additional context

The problem can be remedied easily enough in Vue, so it's not a major issue, just feels odd.

```
.my-filtered-select >>> input {
    cursor: text;
} 
```

**Comment by jmroon** [comment]
Well that was fixed in record time. :o

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.12 & v1.17.7
