### ISSUE TITLE
QSelect's Dropdown is broken.

### ISSUE THREAD

**Issue by sinbino** [quasarframework/quasar#12146]
### What happened?

When I first open QSelect's Dropdown, it is broken.
Perhaps the virtual scrolling used in the dropdown is not working properly.
![Peek 2022-01-21 11-45](https://user-images.githubusercontent.com/22654430/150558175-092a358b-e8b4-4289-b033-215079a577cb.gif)

### What did you expect to happen?

The dropdown will be drawn correctly.

### Reproduction URL

https://codepen.io/sinbino/pen/PoJrjEK

### How to reproduce?

1. Go to Reproduction URL
2. Click on the QSelect component to open the drop-down.
3. Only at first, the drop-down is not drawn correctly.
4. You will need a browser viewport with a large height to reproduce this. In my environment, 900px is enough to reproduce it.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome

### Additional context

vue 3.2.27
vite 2.7.13
quasar 2.4.11
@quasar/extras 1.12.4
@quasar/vite-plugin 1.0.4

**Comment by chaosKP** [comment]
Had the same problem, but seems to be fixed with quasar 2.4.12

**Comment by sinbino** [comment]
I just checked. Thanks for letting me know!
