### ISSUE TITLE
Meta script tag with defer, async : not possible to set boolean value

### ISSUE THREAD

**Issue by laferte-tech** [quasarframework/quasar#12144]
### What happened?

Hello,

When using the Meta Plugin with SSR and when we want to add a script tag, it's impossible to give boolean values to attributes like defer or async.
So the result is something like this:

`<script src="//url" defer="" data-qmeta="google"></script>`

We can just pass string so we can pass something like : defer: 'defer" or defer: '' but not defer: true

### What did you expect to happen?

I would like to be able to give attributes a boolean value instead of a string to have something like that:

`<script src="//url" defer data-qmeta="google"></script>`

Reading the source code of Quasar for Meta plugin, i can see that attributes like defer or async are not handled for the moment.

Thank you very much!

### Reproduction URL

https://codesandbox.io/s/exciting-dewdney-tujjz?file=/src/pages/Index.vue

### How to reproduce?

Go to the sandbox, open source code and check the meta property.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.4.14.
