### ISSUE TITLE
Inconsistent behavior of QVirtualScroll's virtual-scroll-slice-ratio-after property by type

### ISSUE THREAD

**Issue by sinbino** [quasarframework/quasar#12150]
### What happened?

If the QVirtualScroll virtual-scroll-slice-ratio-after or virtual-scroll-slice-ratio-before property is given a value of type number, it will behave as expected, but if it is given a value of type string property with a value of type string, it behaves strangely.

There seems to be a problem with the calculations involving virtualScrollSliceRatioBefore and virtualScrollSliceRatioAfter in the setVirtualScrollSize method of quasar/ui/src/components/virtual-scroll/use-virtual-scroll.js.

### What did you expect to happen?

QVirtualScroll's virtual-scroll-slice-ratio-after or virtual-scroll-slice-ratio-before properties behave the same for the number and string types.

### Reproduction URL

https://codepen.io/sinbino/pen/BawgYPK

### How to reproduce?

1. Go to Reproduction URL
2.  Check the dom structure of the blue list (number type, given virtual-scroll-slice-ratio-after) and the red list (string type, given virtual-scroll-slice-ratio-after) using chrome's devtools, etc.
3. The blue list has an appropriate number of virtual scroll items created, but the number of items created in the red list is unusually large.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome

### Additional context

vue 3.2.27
vite 2.7.13
quasar 2.4.11
@quasar/extras 1.12.4
@quasar/vite-plugin 1.0.4

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.13 and v1.17.8
