### ISSUE TITLE
QInput dark mode error message transition

### ISSUE THREAD

**Issue by pxDot** [quasarframework/quasar#12172]
### What happened?

The transition for the error message on `QInput` with enabled dark mode has a weird transition bug where it seems to not keep the color or loosing anti-aliasing in the transitory state. I'm not sure if this is happening without dark mode too as it might be hard to see there.

This issue is showing up in Chrome for me. In Firefox the same is happening but not as extreme as in Chrome and only for the placeholder, not for the error message itself.

![transition-bug](https://user-images.githubusercontent.com/36505652/150832173-8d5e4e63-b26a-4257-8d06-3bbca15a8720.gif)

### What did you expect to happen?

It should be a smooth transition without changing colors / loosing font smoothing

### Reproduction URL

https://codepen.io/squareloop1/pen/gOXYKpd

### How to reproduce?

1. Go to reproduction link
2. Trigger the validation by focussing and bluring the input with mouse clicks inside and outside of the input

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Additional context

Chrome 97.0.4692.71 64bit (Windows)
Maybe related to #11975

**Comment by rstoenescu** [comment]
Thanks for PRing!
Fix will be available in Quasar v2.5.1 and v1.18.1
