### ISSUE TITLE
missing touch repeat directive related links

### ISSUE THREAD

**Issue by mpavlase** [quasarframework/quasar#12201]
### Description

Touch repeat seems to be added recently, there is missing link to other touch directives and vice versa.

### Documentation Section URL
https://quasar.dev/vue-directives/touch-repeat

### Areas

Directives (quasar)

**Comment by rstoenescu** [comment]
TouchRepeat was added years ago.
Can you be more specific pls on what you think is missing and where? Thanks in advance.
