### ISSUE TITLE
File upload select action

### ISSUE THREAD

**Issue by eugenemaning** [quasarframework/quasar#1221]
File upload doesn't have option to get files from gallery. It only shows: Camera, Camcorder, Voice Recorder, Documents... no Gallery.

**Comment by erikcunha** [comment]
If you are following the docs https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/, have you tried the option 'navigator.camera.PictureSourceType.PHOTOLIBRARY' ?

**Comment by eugenemaning** [comment]
I am following this guide http://quasar-framework.org/components/uploader.html
I am not sure how do I make your suggestion worked with what's currently here. I'm pretty new to know QuasarFramework and I'm loving it.

**Comment by eugenemaning** [comment]
Thanks for your suggestion. I'm thinking of a solution already.

**Comment by erikcunha** [comment]
If you still want to use the uploader for many types of files, i guess you will have to nav to the folder of gallery and select your files, otherwise if you only want images i guess that is better work with cordova.camera, i hope this could be useful.

**Comment by rstoenescu** [comment]
Hi, This is not something that Quasar can control. Rather the web view running the native input type=file control (which Quasar wraps). That is actually triggering the selection menu that appears. So closing this.
