### ISSUE TITLE
Potential AM flag inconsistency in QTime implementation with 24-hour clock enabled

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#12214]
I've noticed that the code to update the AM/PM in QTime differs between `updateClock` and `model-value` watch handler:

- In `updateClock`, the AM is selected only when 24-hour clock is **enabled**
- In watch handler, the AM is always selected, even if 24-hour clock format is **currently disabled**

https://github.com/quasarframework/quasar/blob/c1205680f53447f802053ccfa714c83934b4cee2/ui/src/components/time/QTime.js#L503-L505

https://github.com/quasarframework/quasar/blob/c1205680f53447f802053ccfa714c83934b4cee2/ui/src/components/time/QTime.js#L301-L303

This may or may not cause actual issues, but with 24-hour clock enabled the state update for `isAM` flag seems unexpected.

**Comment by pdanpdan** [comment]
Hello

`updateClock` is called from user interactions

When you are using 12h clock:
- you always send a 1-12 hour value (so the AM/PM state cannot be inferred from it)
- you can set the AM/PM from interface

When you are using 24h clock:
- you send a 0-23 hour value (and the AM/PM is inferred from it)

In the model watcher the hour is always normalized to 0-23, so the AM/PM is inferred from it.
