### ISSUE TITLE
Vetur errors after upgrading @quasar/app from 3.2.6 to 3.2.7

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12215]
### What happened?

This is screenshot from Visual Studio Code with Vetur:
![image](https://user-images.githubusercontent.com/70687432/151315087-30a1a451-b1d5-4a78-8c95-2c9c5d846a8e.png)
I started seeing this error after upgrading @quasar/app from 3.2.6 to 3.2.7

I have created fresh project using "quasar create" command with "typescript" enabled. Here is a repo:
https://github.com/ilyub/repro-quasar-vscode
Freshly created project has the same issue:
![image](https://user-images.githubusercontent.com/70687432/151315921-b48ccce3-e1a8-418e-9824-d677c075d265.png)

### What did you expect to happen?

I expect quasar to be compatible with Visual Studio Code and Vetur

### Reproduction URL

https://github.com/ilyub/repro-quasar-vscode

### How to reproduce?

1. Clone repro repository https://github.com/ilyub/repro-quasar-vscode
2. Install Visual Studio Code
3. Install Vetur

Let me know if this is not enough to reproduce

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

TypeScript Support

**Comment by yusufkandemir** [comment]
I couldn't reproduce the problem.
The project correctly builds, Vetur doesn't show any error.
![image](https://user-images.githubusercontent.com/6266078/151350537-570d6f04-b7b6-4e3f-8e9e-16a7fd3fa79f.png)
I even tried enabling Vetur and Volar at the same time to break things, but it still worked.

A side note: Volar works much better, both Vue team and we recommend using Volar. We will update our documentation and starter kit to reflect this.

**Comment by iliubinskii** [comment]
Thank you for the hint,

Switching to Volar solves the problem for me.

Regarding Vetur, I can additionally note that errors depend on this setting:
![Screen1](https://user-images.githubusercontent.com/70687432/151376270-f4ae0259-2214-4ca1-b0db-04774d746d77.jpg)
but other than that I don't know what influences this.
