### ISSUE TITLE
Need to add the very helpful "flex-center" CSS class to the docs

### ISSUE THREAD

**Issue by BenJackGill** [quasarframework/quasar#12226]
### Description

I commonly use `flex flex-center` CSS classes to center things.

It's much simpler then trying to remeber `flex items-center justify-center items-center`.

And I might be wrong, but I think `flex-center` is a special Quasar created class because I can't find it documented anywhere else.

The problem is that Quasar also hasn't documented it.

So it would be great to add `flex-center` to the Quasar docs because of how useful it is.

### Documentation Section URL

https://quasar.dev/layout/grid/introduction-to-flexbox

### Areas

Style & Identity (quasar)

**Comment by MilosPaunovic** [comment]
It is mentioned in the docs, as part of this:
[https://quasar.dev/layout/grid/introduction-to-flexbox#flex-addons](https://quasar.dev/layout/grid/introduction-to-flexbox#flex-addons)

**Comment by rstoenescu** [comment]
It's not part of the addons, so it makes sense to explicitly mention it.
Will be available on next docs deployment.
