### ISSUE TITLE
[Request] Option to set default control icons

### ISSUE THREAD

**Issue by dboune** [quasarframework/quasar#1222]
It would be helpful if it were possible to change the default control icons. At present you can add additional icons, but I found no reasonable way to disable or change any predefined icon.

Though I am referring to the `Select` component below, the concept applies to any component that includes a default set of icons. 

https://github.com/quasarframework/quasar/blob/55a47463c9e6f311441d61f7463927ad1b99eba5/src/components/select/QSelect.vue#L52-L59

**Proposal**
```html
<q-select
  ...
  clearable
  :control-icons="{
    default: controlIcon,
    clear: 'clear'
  }"
></q-select>
```

**Comment by laurentpayot** [comment]
More or less the same as #1135

**Comment by dboune** [comment]
Oops. Agreed. I missed it.

**Comment by rstoenescu** [comment]
Closing as it has been found as duped.

**Comment by picbenoit** [comment]
Can you give us a exemple to change default icon used when you do not use "material-icons" ? I didn't find the solution by reading you.
When I used password input, the eye at the end of input is changed by "visibility", "visibility_off". I want to change it to Awesome icons "fa-eye" and "fa-eye-slash".
Thanks a lot

**Comment by laurentpayot** [comment]
@picbenoit 

-  remove hard-coded password field visibility material icons
```stylus
.q-input i.q-if-control.q-icon.material-icons
	display none
```
- set your icons using `before` and `after` attribute of `q-input` (docs [here](http://quasar-framework.org/components/input.html#Icon-buttons))

**Comment by mrKoujou** [comment]
In current version of Quasar (v0.15.10) i was in need to customize dropdown icon of Select control for the whole project. I was using Font awesome pro. I want to share solution i found (without changing distributive packages from node_modules and not using before and after).
Edit src\plugins\fontawesome-pro.js as follows:
import iconSet from 'quasar-framework/icons/fontawesome-pro';
export default () => {
	iconSet.input.dropdown = 'fal fa-angle-down';
};
That's it. Any icons can be customized that way. When using regular Font awesome or other icon sets, i think it can be done in Boot plugin the same way (look into node_modules/quasar-framework/icons).
