### ISSUE TITLE
Unexpected behavior between versions 1.16.3 and 1.17.0 break layout

### ISSUE THREAD

**Issue by gilvansfilho** [quasarframework/quasar#12224]
### What happened?

Between versions 1.16.3 and 1.17.0 there is a unexpected behavior when using `q-input` component and `:rules` directive.

When using `:rules` directive in 1.16.3 there is a bottom padding no matter component state (enabled/disabled).
When using `:rules` directive in >=1.17.0 the bottom padding only is present when component is enabled.

Without `:rules` directive the behavior is same in both versions.

Below is a reproducer:
- version 1.16.3 - https://codepen.io/gsfilho/pen/xxPGxLp
- version 1.17.0 - https://codepen.io/gsfilho/pen/MWOwWEb

### What did you expect to happen?

Components should works same way in both versions.

### Reproduction URL

https://codepen.io/gsfilho/pen/MWOwWEb

### How to reproduce?

Use "Change Form State" button at reproducer and watch what happens

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.17.9 & v2.4.14.
