### ISSUE TITLE
Input content is not shown

### ISSUE THREAD

**Issue by GuilhermeErmel** [quasarframework/quasar#12223]
### What happened?

I wrote the issue here: [12078](https://github.com/quasarframework/quasar/issues/12078), but I didn't receive answer anymore :(

### What did you expect to happen?

The value shoud be displayed

### Reproduction URL

https://codesandbox.io/s/laughing-rubin-00nyi

### How to reproduce?

Read in issue [12078](https://github.com/quasarframework/quasar/issues/12078)

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by GuilhermeErmel** [comment]
You can simulate the problem accessing https://codesandbox.io/s/laughing-rubin-00nyi and clicking in "open in new window".

![image](https://user-images.githubusercontent.com/32545608/151544419-6921c607-975a-41fb-962c-f66c32844363.png)

**Comment by rstoenescu** [comment]
Cannot reproduce...
What browser are you using?

**Comment by rstoenescu** [comment]
Ah. Scratch that. Reproduced it.

**Comment by yusufkandemir** [comment]
I'd say the repro steps were quite obscure, and having two issues for the same problem, where the description is spread out is making it even harder. But, I reproduced the problem Microsoft Edge v97.0.1072.69.

**Comment by rstoenescu** [comment]
We'll continue on #12078
