### ISSUE TITLE
QTime: "options" prop has incorrect type

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12243]
### What happened?

![image](https://user-images.githubusercontent.com/70687432/151655313-a4123063-9597-4596-8576-357648096537.png)

"options" prop has the following type:
```
(hr: number, min: number, sec: number) => void
```

### What did you expect to happen?

The type should be:
```
(hr: number, min: number | null, sec: number | null) => void
```
because "min" param can be null. See console here:
https://codepen.io/ilyalyu/pen/VwrvaKe?editors=1111

### Reproduction URL

https://codepen.io/ilyalyu/pen/VwrvaKe?editors=1111

### How to reproduce?

See console here:
https://codepen.io/ilyalyu/pen/VwrvaKe?editors=1111

To see incorrect typing see screenshot:
![image](https://user-images.githubusercontent.com/70687432/151655313-a4123063-9597-4596-8576-357648096537.png)

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar), TypeScript Support

### Platforms/Browsers

Firefox

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.5
