### ISSUE TITLE
UMD configuration: Native Line Awesome, not Font Awesome mig

### ISSUE THREAD

**Issue by eddelplus** [quasarframework/quasar#12252]
### Description

I managed to include Quasar.iconSet.set(Quasar.iconSet.lineAwesome) but still didn't get icons on the color picker. This was caused by using the URL to the Font Awesome replacement version of Line Awesome. To get the **_las la-..._** icons, the link marked with "If you are starting a new project..." on the [Line Awesome home page](https://icons8.com/line-awesome/howto) is needed.

Created pull request #12251 to fix this. Would be nice, if you could merge that.

Impressive Framework for a < 500 kB production UMD build !!

### Flavour

UMD

### Areas

Style & Identity (quasar)

**Comment by rstoenescu** [comment]
Thanks for providing a PR and fixing the link!
