### ISSUE TITLE
Make 'Alert' dismissible, even with other actions

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1227]
From the docs:
> If you do not define any actions, the alert method will automatically be dismissible i.e. there will be an “X” button available for the user to dismiss the alert.

Currently for the `Alert` component to force 'dismissible' to be true is only possible on the Alert as Quasar-Component `<q-alert>`. But not when calling it on the global scale and adding `dismissible: true,` in the parameters.

**Comment by rstoenescu** [comment]
Hi, There's Notify in future v0.15 which unifies Toast and Alert -- it allows what you want.
