### ISSUE TITLE
URGENT : publicPath bug

### ISSUE THREAD

**Issue by gittrolo** [quasarframework/quasar#12296]
### What happened?

I created an app with quasar cli, without making any changes to the code. I launched it by calling a url with a parameter a=c , and everything works fine:
![1](https://user-images.githubusercontent.com/52664193/151984583-6e902ddc-8bac-4c5a-b8c9-ba0b0e59a446.JPG)

if I add the parameter   publicPath: "b" in quasar.conf.js and launch the app
I am immediately redirected from the address http://localhost:8080/b/index.html?a=c to http://localhost:8080/b/
![3](https://user-images.githubusercontent.com/52664193/151985674-1f1b4286-9ad3-402f-bbc1-bee11c2ee8e1.JPG)

### What did you expect to happen?

I need the app to stay on the starting address and not redirect

### How to reproduce?

No link to reproduce the problem

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
Isn't that what `publicPath` is for:
[https://quasar.dev/quasar-cli/quasar-conf-js#:~:text=to%20%2DP%20parameter.-,publicPath,-String](https://quasar.dev/quasar-cli/quasar-conf-js#:~:text=to%20%2DP%20parameter.-,publicPath,-String)

or am I missing something?

**Comment by rstoenescu** [comment]
There's nothing wrong with Quasar. At best, it would be something wrong with vue-router.
This should have been opened as a discussion. It's also rude to open with the terminology "URGENT". This is not how opensource works. At least being a donator would put you higher up in line.

**Comment by 717009629** [comment]
I have same problem ,Have you solved the problem?
