### ISSUE TITLE
(V1 / V2) Screen.js plugin since update 1.18.1 gives wrong Height (Ios 15.x / Safari )

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#12311]
### What happened?

The new Screen.js viewport Calculation delivers to high "height" pixel viewport Calculations
on Ios / Iphone and Ipad (higher than the vendor viewport) . (did not tested on Android)

https://yesviz.com/devices/iphone-xr/

Iphone XR - Offical max Viewport 414 x 896  

**With new Viewport Calculation / V.1.18.1.**

**with Adressbar on Top:**
715 px (with Adressbar)
**949 px** (scrolled, no Adressbar) ---> thats higher than the physical vp.

**with Adressbar on Bottom:**
715 px (with Adressbar)
877 px (scrolled, no Adressbar)

**Older Screen.js plugin gives**

**with Adressbar on Top:**
715 px (with Adressbar)
832px (scrolled, no Adressbar) 

**with Adressbar on Bottom:**
715 px (with Adressbar)
796 px (scrolled, no Adressbar)

On Ipad it also has a wrong calculation (1049 px (physical 1024 px)

On the first view the : 
`window.innerHeight - document.scrollingElement.clientHeight` is here the culprit ?

visualViewport.scale says always 1 (and grows on pinch zooming)

--> the width calculations are normal / unchanged.

### What did you expect to happen?

correct calculation

### Reproduction URL

https://www.quasar.dev

### How to reproduce?

insert a:

`{{ $q.screen.height}}`

and scroll down ..

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

### Platforms/Browsers

iOS

**Comment by ibrainventures** [comment]
Saw the existing issue to late ..

give those informations into the comments

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.5.2 and v1.18.2
