### ISSUE TITLE
Numerc value does not update in QInput with mask

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12326]
### What happened?

1. Open codepen https://codepen.io/ilyalyu/pen/RwjRxKM
2. Click on "Inc" button several times
3. See that input value updates only on each second click

### What did you expect to happen?

1. ...
2. ...
3. It shoud update on each click

### Reproduction URL

https://codepen.io/ilyalyu/pen/RwjRxKM

### How to reproduce?

1. Open codepen https://codepen.io/ilyalyu/pen/RwjRxKM
2. Click on "Inc" button several times
3. See that input value updates only on each second click

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by JeRabix** [comment]
If comment this lines - bug fixed :)
![image](https://user-images.githubusercontent.com/46298617/152432012-faf0c39b-5304-4ac2-9ed4-58edb57ad297.png)
QInput.js file in src/components/input/

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.5.4 and v1.18.4
