### ISSUE TITLE
<q-input type="number"> allows non-numeric input

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12323]
### What happened?

1.

<q-input type="number"> allows non-numeric input.

Adding ### mask does not help.

2.

Also, up/down buttons on the right are too small.
I think they are unusable on mobile devices.

### What did you expect to happen?

1.

It should not accept non-numeric input.

2.

There should be style with bigger arrows

### Reproduction URL

https://codepen.io/ilyalyu/pen/VwrjMXO

### How to reproduce?

1. Open https://codepen.io/ilyalyu/pen/VwrjMXO
2. Enter any non-numeric character

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by MilosPaunovic** [comment]
Check this out: [https://stackoverflow.com/a/31706796](https://stackoverflow.com/a/31706796).

**Comment by iliubinskii** [comment]
> Check this out: https://stackoverflow.com/a/31706796.

Thx, I have checked your link.

I see that numeric input should accept floating-point-related characters: "e", "." etc.

But I still see problem with <q-input type="number">:
1. It accepts all characters, not just "e", "." etc.
2. It does not respect mask
3. Up/down arrows are so small that they are unusable on mobile devices

I would also suggest to add prop to allow either (a) only natural numbers or (b) both natural and floating point numbers.

**Comment by MilosPaunovic** [comment]
1. I could not reproduce - could input only `e` and numbers in your codepen
2. Mask is not supproted for that input type, as stated in the `Warning` card in the docs:
[https://quasar.dev/vue-components/input#mask](https://quasar.dev/vue-components/input#mask)
3. Arrows are standard browser ones, not affected by any of the Quasar styling

**Comment by gregadro** [comment]
The input uses browser validation, also the increment/decrement buttons are browser native controls. And Firefox unfortunatelly lets you type all the alpha characters.

**Comment by iliubinskii** [comment]
1. I see issue in Firefox 96.0.3 on Windows 10. After your comment I tried in Google Chrome and Microsoft Edge - they work fine. So, I guess this is browser issue rather than Quasar issue.
2. Ok, this makes sense if browser makes validation
3. Ok, clear

Finally, I see that there is no bug with QInput.

But I have suggestion to add separate component for natural numbers.
It is very common to have natural number input and QKnob is not always good in such situation.
Do you think this suggestion is worth adding as separate ticket?

**Comment by rstoenescu** [comment]
~~Fix will be available in Quasar v2.5.4 and v1.18.4~~
Correction. This was intended for another ticket.
Still, this ticket should be closed for reasons in comments above.

**Comment by Divensky** [comment]
I've struggled with the same problem, here is a demo of how I made custom validation to go around this:
https://github.com/Divensky/quasar-inputs
