### ISSUE TITLE
the datetime picker haven't linkage function.

### ISSUE THREAD

**Issue by owey0312** [quasarframework/quasar#1233]
the scene such as :
A{
  A1,
  A2
} ,
B{
 B1,
 B2
}

when i select A, the another list show A1, A2...
when i select B, the another list show B1, B2...
 

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Hi,

Please reopen with some details, even with a template. I really don't understand what you mean...
