### ISSUE TITLE
Vite - How to use boot files and boot function's type

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#12340]
### Description

From the document exist example to add [boot file](https://quasar.dev/quasar-cli/boot-files#usage-of-boot-files) but did not make it clear how to use for Vite project, where doesn't exist `quasar.conf.js`

And for Quasar project with Typescript, exist `BootCallback` type for boot files inside `@quasar/app package`, but for Vite project (project not created by quasar CLI) how to use it?

### Documentation Section URL

https://quasar.dev/start/vite-plugin#using-quasar

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app), TypeScript Support

**Comment by alexrififi** [comment]
Maybe like this?

```ts
// main.ts

Object.values(import.meta.globEager('/src/boot/*.ts')).forEach(module => module.default({app, router, store}))
```

**Comment by rstoenescu** [comment]
Boot files are a feature of Quasar CLI. It has nothing to do with our plugin for Vite. Also notice that boot files are under the root "Quasar CLI" category in the docs menu.

PS: a Quasar CLI with Vite under the hood is scheduled in the near future.

**Comment by maico910** [comment]
@medvinator That`s works, thanks for the help.

**Comment by maico910** [comment]
@rstoenescu Thanks for the reply.

**Comment by cerw** [comment]
Can this be done with vite plugin? I miss booters!
