### ISSUE TITLE
Q-Select : pressing TAB-key or ENTER-KEY after clicking on an option, sometimes picks the wrong value

### ISSUE THREAD

**Issue by Dylan190774** [quasarframework/quasar#12358]
### What happened?

While using a Q-select with `use-input` set, I noticed that sometimes after pressing the `TAB`-key or '`ENTER`'-key the wrong value is picked.

I'm guessing it has something to do with the hovering over the options-list, which is apparently still active somehow, after clicking on an option. Even with `transition-hide` set tot 'none' this happens.

When you hold the mouse-pointer still for a little while after picking the option, this behaviour doesn't happen.

### What did you expect to happen?

The value that was clicked on should be the value. Pressing the TAB-key or ENTER-key after clicking should never change the value.

An option to disable the picking of the hovered option with the TAB-key would be nice too, even though this is standard behaviour with a normal HTML select tag.

### Reproduction URL

https://codepen.io/bobdylan2022/pen/oNozmxq?editors=101

### How to reproduce?

1 - Click the Q-Select open with the mouse.
2 - Pick an option in the middle of the list with the mouse.
3 - Quickly move the mouse-pointer up or down after clicking (within a second or so)
4 - Wait a few seconds
5 - Press TAB-key or ENTER-key and see the value change to another one that was NOT picked.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
The value that is currently highlighted when pressing TAB because the selected one.

**Comment by Dylan190774** [comment]
No, the value that was clicked on appears correctly as the value of the select,  but CHANGES (even minutes later!) after pressing TAB or ENTER to an option that was maybe hovered on,  while the options-list was not even visible!

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.5.4

**Comment by Dylan190774** [comment]
Thank you! Love the framework!
