### ISSUE TITLE
On a q-card component, when the view width is an even/odd number of pixels, the q-img component is off by 1 pixel on the right edge

### ISSUE THREAD

**Issue by npsyhos** [quasarframework/quasar#12370]
### What happened?

On a q-card component, when the view width is an even/odd number of pixels, the q-img component is off by 1 pixel on the right edge

### What did you expect to happen?

I expect the q-img/q-card to not have an extra 1 pixel on the right side when there's an odd/even number of pixels in the view width.

### Reproduction URL

https://codepen.io/npsyhos/pen/dyZOdGJ

### How to reproduce?

1. Go to reproduction link
2. Click on the button to get the q-dialog
3. Adjust the width of the view
4. If you change the width on the q-card inline style to an odd number, you will notice the inverse happens. This will also happen regardless of the inline style being set.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Quasar info output

```shell
Operating System - Darwin(20.6.0) - darwin/x64
NodeJs - 14.18.0

Global packages
  NPM - 8.3.2
  yarn - Not installed
  @quasar/cli - 1.2.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.4.12 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.2.9 -- Quasar Framework local CLI
  @quasar/extras - 1.12.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.29 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.12
  vuex - 4.0.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.12 -- Babel compiler core.
  webpack - 5.67.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Nicholass-MacBook-Air.local
  en0 - 10.0.0.12
```

### Additional context

I noticed it seems to have something to do with object-fit: cover. If I remove that style in developer tools, the problem seems to go away.

**Comment by rstoenescu** [comment]
Although I could not reproduce, it's at best a bug of the browser rather than a bug in Quasar. There are some more scenarios with same root cause and we're also waiting for a fix (at least in Chrome).
In the mean time, you could try to play with the other values of the `fit` prop.
