### ISSUE TITLE
QSelect - Selecting option after filtering example doesn't work

### ISSUE THREAD

**Issue by jeroenqui** [quasarframework/quasar#12371]
### Description

The second example (Autoselect after filtering) is not working. 
This is because `ref.optionIndex` in the code (see below) returns `undefined`

```
// "ref" is the Vue reference to the QSelect
ref => {
   if (val !== '' && ref.options.length > 0 && ref.optionIndex === -1) {
      ref.moveOptionSelection(1, true) // focus the first selectable option and do not update the input-value
      ref.toggleOption(ref.options[ ref.optionIndex ], true) // toggle the focused option
   }
}
```

### Documentation Section URL

https://quasar.dev/vue-components/select#example--selecting-option-after-filtering

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Thanks for reporting this.
New method will be available for QSelect -> getOptionIndex()

**Comment by lxmfly123** [comment]
In latest Quasar release for now(v2.5.5), this method is `getOptionIndex: (index: number) => void;`, it should be `getOptionIndex: () => number`.
