### ISSUE TITLE
QBtn - event prevention

### ISSUE THREAD

**Issue by Kylyi** [quasarframework/quasar#12385]
### What happened?

I have a chat component where you can fill an input with text and send the message via button.
On mobile device, I would like to keep focus inside the input element after I click the button so the virtual keyboard does not hide.

Without Quasar, I would use a very simple button with `@mousedown.prevent` but that doesn't seem to work for `QBtn`.

Note: Refocusing the input on btn `click` or `mouseup` will make the virtual keyboard jump which I'd like to prevent.
Note 2: Refocusing the input on btn `mousedown` doesn't seem to do anything.

### What did you expect to happen?

The `@mousedown.prevent` should prevent the button from getting focused

### Reproduction URL

https://codepen.io/Kylyi/pen/ExbZKrw?editors=101

### How to reproduce?

1. Focus the input if it is not already focused
2. (optional) write something into the input
3. Click the first button (the standard `<button>`) -> the input should stay focused
4. Click the second button (the `<q-btn>` -> the input gets blurred

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

**Comment by hawkeye64** [comment]
@Kylyi Look at @rstoenescu 's answer here: https://github.com/quasarframework/quasar/discussions/12110

**Comment by rstoenescu** [comment]
Valid claim. He IS using mousedown.prevent

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v2.5.6.

Correct way to prevent: `@keydown.enter.space.prevent @mousedown.prevent @touchstart.prevent`

**Comment by philippedasilva-orizone** [comment]
@rstoenescu I believe the changes made to solve that issue introduced back some validation errors with: "non-passive event listenter to a scroll-blocking 'touchstart' event"
You can clearly see it when going to the QBtn component page in the documentation (console warnings)
![image](https://user-images.githubusercontent.com/77384971/159674925-6373f7c7-1c5f-4e32-bd2a-7fcb79e7f337.png)
