### ISSUE TITLE
Meta plugin does not update <html> or <body> when using Options API

### ISSUE THREAD

**Issue by sluedecke** [quasarframework/quasar#12393]
### What happened?

Following the documentation for the [meta plugin](https://quasar.dev/quasar-plugins/meta#introduction) in an options API based project, I added the respective code to a sample project: https://github.com/sluedecke/sl-quasar-metamixin

### What did you expect to happen?

I expect the html, body and meta tags to be set accordingly (when viewing the source code of the generated page).

### Reproduction URL

https://github.com/sluedecke/sl-quasar-metamixin

### How to reproduce?

- clone repository
- run with `quasar dev`
- open page in browser
- view source code of page

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

### Quasar info output

```shell
Operating System - Linux(5.16.5-arch1-1) - linux/x64
NodeJs - 17.3.0

Global packages
  NPM - 8.4.0
  yarn - 1.22.17
  @quasar/cli - 1.2.2
  @quasar/icongenie - 2.3.4-cc
  cordova - You have been opted out of telemetry. To change this, run: cordova telemetry on.
9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 2.5.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.2 -- Quasar Framework local CLI
  @quasar/extras - 1.12.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.30 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.12
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.17.0 -- Babel compiler core.
  webpack - 5.68.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - MYHOST
  wlan0 - 192.168.0.3
```

**Comment by rstoenescu** [comment]
Works just fine....

<img width="669" alt="image" src="https://user-images.githubusercontent.com/4665641/153061230-50854f4c-b460-4a27-91d4-508d3cb08b94.png">

Only thing that is not configured correctly is that you're already specifying `<title>...` and `<meta name="description" content="<%= productDescription %>" />` in /src/index.template.html
When using Meta plugin and specifying them there, remove them from index.template.html. The Meta plugin is highly optimized and does NOT account for tags, attributes etc already in index.template.html.

**Comment by sluedecke** [comment]
Thanks for looking into it!  Apparently neither Chrome nor Firefox show the updated tags when viewing the page source, but in the web development tools inspector section, the modifications show just fine.

**Comment by rstoenescu** [comment]
"View page source" shows what the webserver supplies to the client when fetching the page. But a SPA or PWA is JS code that runs and renders your page. Whatever changes are applied will not be visible with "View page source" because the source changed from what is currently rendered :)

Any web dev nowadays should use the devtools.

**Comment by sluedecke** [comment]
Yeah, "years in business" and I am still learning something new on a daily basis - even the basics:)

**Comment by scottie** [comment]
So how does a SEO spider get the meta tags, ie: title if the curl don't render the JS.
Sure if you inspect it will show the title because its set by JS dynamically but if you CURL or use a tool like https://www.heymeta.com/ nothing shows, thoughts ?

**Comment by scottie** [comment]
hang on a moment, are you guys even using meta plugin ?? seems not ...
![image](https://github.com/quasarframework/quasar/assets/94546/9f8fdcfb-205d-4814-9c97-a15cf47a1919)

**Comment by rstoenescu** [comment]
> So how does a SEO spider get the meta tags, ie: title if the curl don't render the JS.
> 
> Sure if you inspect it will show the title because its set by JS dynamically but if you CURL or use a tool like https://www.heymeta.com/ nothing shows, thoughts ?

That's where SSR comes into play.

**Comment by scottie** [comment]
Thank you for the reply, SSR would show the meta details in view source but you said it will not show in view source suggesting not SSR so are you suggesting that now google can decipher JS ? I did not even know Quasar could be used server side thank you for the news.
