### ISSUE TITLE
Memory not released when removing components with v-if

### ISSUE THREAD

**Issue by Codebreaker101** [quasarframework/quasar#12392]
### What happened?

When toggling `q-input` with `v-if`, for example, the memory is not released. 

(on-off)

![Screenshot from 2022-02-08 10-15-17](https://user-images.githubusercontent.com/16204269/152955613-92c59399-d0de-45b1-a27f-b81fd095663a.png)

(3x on-off)

![Screenshot from 2022-02-08 10-18-00](https://user-images.githubusercontent.com/16204269/152956036-f3098047-a2b8-482f-872c-38805246b5e8.png)

### What did you expect to happen?

For the memory to be released when nodes are removed from DOM.

### Reproduction URL

https://codesandbox.io/s/boring-ramanujan-ogd3c?file=/src/pages/Index.vue

### How to reproduce?

1. Use this template
``` js 
<template>
  <q-page>
    <q-btn label="Notify" color="primary" @click="trigger"></q-btn>
    <div v-if="show">
      <q-input
        v-for="idx in 1000"
        label="test"
        hint="test"
        :key="idx"
        v-model="model"
        lazy-rules
        outlined
        bottom-slots
      />
    </div>
  </q-page>
</template>

<script>
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'PageIndex',
  setup() {
    const show = ref(false);
    return {
      show,
      trigger: () => (show.value = !show.value),
      model: ref('test'),
    };
  },
});
</script>

```

2. Click Trigger a couple  of times and watch memory grow

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```shell
Operating System - Linux(5.10.93-1-MANJARO) - linux/x64
NodeJs - 14.17.6

Global packages
  NPM - 6.14.15
  yarn - 1.22.17
  @quasar/cli - 1.2.1
  @quasar/icongenie - 2.4.0
  cordova - Not installed

Important local packages
  quasar - 2.5.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.2 -- Quasar Framework local CLI
  @quasar/extras - 1.12.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.29 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.12
  vuex - 4.0.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.12 -- Babel compiler core.
  webpack - 5.67.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by Codebreaker101** [comment]
It seems this happens only during development so I'm gonna close this.

**Comment by hawkeye64** [comment]
@Codebreaker101 Also, if this is a `v-if` issue, then you would put an issue against the Vue repo, not Quasar. :)

**Comment by Codebreaker101** [comment]
@hawkeye64 True, but in my case when using native _input_ or other components like QCard, QIcon or other _simple_ components it is not a problem, only with QInput (and _I'm guessing_ other QFields, not tested).

On further testing this seems to happen only when I have Vue Devtools extension enabled. Disabling Vue Devtools extension reduces memory usage for that tab. 

![Screenshot from 2022-02-09 16-31-16](https://user-images.githubusercontent.com/16204269/153233744-59c93568-2103-4dd3-a799-a71b29e9e5c5.png)

Maybe this is not the place to ask, but, why doesn't quasar/vue/browser release the initial nodes when removed by `v-if`? As can be seen from the image, all the subsequent created nodes are released when removed by `v-if`.

**Comment by hawkeye64** [comment]
Have you checked the actual node in dev tools? Vue does some caching and I believe their cache variables start with $.
However, with the node gone via `v-if`, that should also be gone.
