### ISSUE TITLE
Bug report codepen has bugs

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#12409]
### What happened?

I was going to submit a bug report, but the code pen link has bugs :) See the error in the console in codepen:

![image](https://user-images.githubusercontent.com/900542/153176765-23be9d0e-9dd0-4353-a62e-a4cbeda1bda4.png)

### What did you expect to happen?

To submit a different kind of bug report.

### Reproduction URL

https://codepen.io/rstoenescu/pen/VgQbdx

### How to reproduce?

1. Go to the codepen link
2. Open the console

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by gregadro** [comment]
Your pen is referencing Quasar v1 and Vue v3 (which is now the default Vue version). Quasar v1 is not compatible with Vue 3.

**Comment by rstoenescu** [comment]
Fixed the jsfiddle and codepen link on the docs Playground page: https://v1.quasar.dev/start/playground
Thanks for reporting this.
