### ISSUE TITLE
QUploader throwing warnings on console when using 'factory' prop

### ISSUE THREAD

**Issue by babalubas090** [quasarframework/quasar#12403]
### What happened?

When uploading in QUploader using the 'factory' prop, the component throws some warnings on console
![image](https://user-images.githubusercontent.com/16084368/153067677-d0b79d1b-4933-40c6-b498-b6f9ef31dc13.png)
![image](https://user-images.githubusercontent.com/16084368/153067765-6f6d8584-e1c5-42aa-ac05-891f520d507b.png)

### What did you expect to happen?

Do not throw warnings on console

### Reproduction URL

https://codepen.io/ricardo-luiz-gomes/pen/gOXmrPv

### How to reproduce?

1. Go to the provided reproduction link
2. Upload some file 
4. Go to the browser's console and see the warnings 

### Flavour

UMD

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Thanks for reporting!
This revealed an under the hood problem with the detection of plain Objects. Fix will be available in Quasar v2.5.5
