### ISSUE TITLE
QInput clearable does not work with v-model.trim

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#12431]
### What happened?

When the clearable button is pressed, the text is not cleared. In the devtools console you will see an error: `Cannot read properties of null (reading 'trim')`. This is because the clearable button sets the model to null.

### What did you expect to happen?

The text to clear with no error.

### Reproduction URL

https://codepen.io/smakinson/pen/MWOmVaw

### How to reproduce?

Use a `QInput` with clearable and `v-model.trim`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Quasar info output

```shell
quasar - 2.5.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
@quasar/app - 3.3.2 -- Quasar Framework local CLI
@quasar/extras - 1.12.4 -- Quasar Framework fonts, icons and animations
```

### Relevant log output

```shell
TypeError: Cannot read properties of null (reading 'trim')
```

**Comment by MilosPaunovic** [comment]
Duplicate [https://github.com/quasarframework/quasar/issues/11423](https://github.com/quasarframework/quasar/issues/11423), [https://github.com/quasarframework/quasar/issues/10376](https://github.com/quasarframework/quasar/issues/10376), [https://github.com/quasarframework/quasar/discussions/10362](https://github.com/quasarframework/quasar/discussions/10362)

**Comment by qxygene** [comment]
any update on this?

**Comment by pdanpdan** [comment]
@qxygene interesting, your very helpful multiple contribution missed the only place where there was an update
https://github.com/quasarframework/quasar/issues/10376#issuecomment-1108320740
