### ISSUE TITLE
Q-Select options filter issue

### ISSUE THREAD

**Issue by iXyles** [quasarframework/quasar#12434]
### What happened?

When having a computed method, or a list of items that changes as "options" for the q-select as a filter to prevent some combinations, the content is not always updating/expanding as expected if the q-select has a "value" in the model when being opened. It however works just fine if no value is selected before you open the q-select the first time.

### What did you expect to happen?

I was expecting the list of options to expand as expected with the new options in both scenarios, and not only if the value was empty when you opened the q-select the first time.

### Reproduction URL

https://codepen.io/ixyles/pen/RwjVdOd

### How to reproduce?

1. Open the Q-Select and select Google & Facebook
2. Close the Q-Select
3. Open the Q-Select again and untick Google and Facebook

Expected result
4. You see the whole list of all 5 items as expected

Actual result:
4. You are only seeing two elements as it is not fully expanding correctly

Workaround:
Close Q-Select and open it again.

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rtynski** [comment]
Smal fix:
https://codepen.io/rafalty/pen/OJOgvKe
`
return [...this.options];
`
And working.
But the bug is still there.

https://codepen.io/rafalty/pen/eYeRrmW

**Comment by metalsadman** [comment]
https://quasar.dev/vue-components/select#api--qselect
![Screen Shot 2022-02-12 at 12 16 39 PM](https://user-images.githubusercontent.com/31038838/153696197-3e629f56-92b1-45dc-8371-b4a85eed49e4.png)


https://codepen.io/metalsadman/pen/wvPexOV?editors=1010

**Comment by rstoenescu** [comment]
Reopening so I don't forget to look into something.

**Comment by iXyles** [comment]
> https://quasar.dev/vue-components/select#api--qselect ![Screen Shot 2022-02-12 at 12 16 39 PM](https://user-images.githubusercontent.com/31038838/153696197-3e629f56-92b1-45dc-8371-b4a85eed49e4.png) r.dev/vue-components/select#api--qselect
> 
> https://codepen.io/metalsadman/pen/wvPexOV?editors=1010

Thanks :) I actually missed this!

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.2
