### ISSUE TITLE
Icon Genie generates icon for cordova but when running cordova app icon doesn't change

### ISSUE THREAD

**Issue by aryan1107** [quasarframework/quasar#12449]
### What happened?

Icon Genie generates icon for cordova but when running cordova app icon doesn't change. It shows default cordova icons.

Even though I can see generated icons inside src-cordova within res folder. When running cordova app it just shows default icons.

### What did you expect to happen?

Instead of default icon it should show generated icons.

### Reproduction URL

.

### How to reproduce?

.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Icon Genie CLI (@quasar/icongenie)

**Comment by janjas92** [comment]
@aryan1107  do you resolve this problem?

**Comment by janjas92** [comment]
For everyone who has this problem. I add param name to the platform param in config.xml which is located in src-cordova.
![obraz](https://user-images.githubusercontent.com/16246374/161445179-1078e05f-1bee-47c4-8f9e-4a29bb601030.png)


 I think this problem is with icongenie?
