### ISSUE TITLE
Quasar app bug

### ISSUE THREAD

**Issue by gittrolo** [quasarframework/quasar#12440]
### What happened?

after updating quasar app from 3.2.2 to 3.3.3, build command failed:

![2022-02-11_100553](https://user-images.githubusercontent.com/52664193/153565140-5dbfa6ff-17da-40bb-9326-0eea6e0d300a.JPG)

### What did you expect to happen?

build does not fail

### Reproduction URL

https://nolink.com

### How to reproduce?

No link

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by MilosPaunovic** [comment]
Try with fresh dependency installing by first removing `node_modules` and `package-lock.json` and then running `npm i` command.

**Comment by gittrolo** [comment]
It's OK. Thank you
