### ISSUE TITLE
Wrong path for @quasar/extras assets when using vite on URLs other than localhost:3000

### ISSUE THREAD

**Issue by FlorianMoser** [quasarframework/quasar#12445]
### What happened?

This issue happens when using `@quasar/extras` and `vite` with a development URL (for example `mydevdomain.test`) other than `http://localhost:3000`, for example when working with Laravel and InertiaJS.

The material icon fonts are loaded from the URL `http://mydevdomain.test/node_modules/@quasar/extras/material-icons/web-font/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2`, which results in a 404 error.

### What did you expect to happen?

The fonts should be loaded from the URL `http://localhost:3000/node_modules/@quasar/extras/material-icons/web-font/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2`

### Reproduction URL

https://quasar.dev/start/vite-plugin

### How to reproduce?

1. Have a project that uses `http://localhost:3000` for the assets and any other URL to develop (like any Laravel/InertiaJS project)
2. Install Quasar and its vite-plugin exactly as described on the [Reproduction URL](https://quasar.dev/start/vite-plugin). Don't change any option, just take the offered code for `main.js`, `vite.config.js` and `src/quasar-variables.sass`.
3. Run `yarn dev`
4. Visit your development URL

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar), Quasar Extras (@quasar/extras)

### Quasar info output

```shell
Operating System   	Darwin(20.6.0) - darwin/arm64
NodeJs             	16.13.2

Global packages
  NPM              	8.4.1
  yarn             	1.22.17
  @quasar/cli      	1.2.1
  @quasar/icongenie	Not installed
  cordova          	Not installed

Networking
  Host             	
  en1              	10.0.0.5
```

### Relevant log output

```shell
downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: http://mydevdomain.test/node_modules/@quasar/extras/material-icons/web-font/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2

downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: http://mydevdomain.test/node_modules/@quasar/extras/material-icons/web-font/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff
```

**Comment by rstoenescu** [comment]
Hi,

This has nothing to do with our Vite plugin. Asset handling, bundling etc etc is handled by Vite. So look into your Vite config. Most likely you've set a public path or base to that URL for dev too and Vite is doing what you told.

**Comment by FlorianMoser** [comment]
Thanks, @rstoenescu 

For future reference: you have to explicitly set the `server.origin` option in `vite.config.js`, if your development URL differs from `http://localhost:3000`:

```
    server: {
        origin: 'http://localhost:3000',
    }
```
