### ISSUE TITLE
Q-table, @row-click not work within body-slot

### ISSUE THREAD

**Issue by gowy222** [quasarframework/quasar#12451]
### What happened?

see as  title said if useing body-slot in q-table, the event @row-click never work..

### What did you expect to happen?

Im tring to use body-slot manage user clicked row bgc/border color, cuz no api to set this prop. Thus, try to use body-slot :class='is_current_clicked_row', however the api @row-click  never worked.

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

```
    <q-table
      title="Treats"
      :rows="rows"
      :columns="columns"
      row-key="name"
      @row-click="current_clicked_row" //here
    >
      <template v-slot:body="props">
        <q-tr :props="props">
           ........... see https://quasar.dev/vue-components/table#body-slots

```
---------------------------------------------------
```
  setup () {
      let current_clicked_row = (evt, row, index)=>{
        console.log(index); // no data in console...
      }
  
    return {
      current_clicked_row,
      columns,
      rows
    }
  }
```
....

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```shell
V2.5.5 + VUE3
```

**Comment by MilosPaunovic** [comment]
You need to add `@click` event to your `q-tr`.

**Comment by tzmartin** [comment]
> You need to add @click event to your q-tr.

this method only returns `PointerClick` event, not `row` or `index`.  `@row-click` is still not working for `q-tr` or `q-table` while using a body-slot.

**Comment by metalsadman** [comment]
> > You need to add @click event to your q-tr.
> 
> this method only returns `PointerClick` event, not `row` or `index`. `@row-click` is still not working for `q-tr` or `q-table` while using a body-slot.

![Screen Shot 2022-02-14 at 9 10 20 AM](https://user-images.githubusercontent.com/31038838/153784319-1b48398b-52df-4c79-be92-de95a187f87f.png)

follow what Milos suggested.

**Comment by petegriffith** [comment]
Wait, so is there any way to grab row data from @click on q-tr? 

If I'm using body slots, is there any way to get row data on click?

**Comment by MilosPaunovic** [comment]
Just pas down the props from body slot.
[https://codepen.io/milospaunovic/pen/yLPGxPm?editors=1011](https://codepen.io/milospaunovic/pen/yLPGxPm?editors=1011)

**Comment by superuser-chi** [comment]
Hi @gowy222,

Make sure your data has a unique id and specify it in your  q-table using the row-key prop

**Comment by ajmas** [comment]
Tempted to update the "body slots" examples to include the mentioned solution. It isn't ideal for this to be place that people come for the answer.
