### ISSUE TITLE
q-toggle @update not working

### ISSUE THREAD

**Issue by fairking** [quasarframework/quasar#12454]
### What happened?

Having this doc: https://quasar.dev/vue-components/toggle

The q-toggle is not working as expected. the event @update is not triggered.
https://jsfiddle.net/3dr6n0qv/

### What did you expect to happen?

working `@update` event

### Reproduction URL

https://jsfiddle.net/3dr6n0qv/

### How to reproduce?

Click toggle

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Other

**Comment by fairking** [comment]
> Hi @fairking! 👋
> 
> Without a proper reproduction, your issue will have to get closed.
> 
> Thank you for your collaboration. 👏

what? could someone please disable that bot :-)?

**Comment by fairking** [comment]
I can see the [function](https://github.com/quasarframework/quasar/blob/4242b46ace45c9a6dc8965ef1fab718b32e09926/ui/src/components/checkbox/use-checkbox.js#L143):
```js
  function onClick (e) {
    if (e !== void 0) {
      stopAndPrevent(e)
      refocusTarget(e)
    }

    if (props.disable !== true) {
      emit('update:modelValue', getNextValue(), e)
    }
  }
```

But I cannot understand what it is doing? on click we trigger update? what if I need to listen to click itself? click and update are two different things I assume. Anyway those were just my thoughts.

**Comment by gregadro** [comment]
There is no such event with that name. The correct event name is `@update:model-value`, also seen from the code snippet above. So in your CodePen you should use `@update:model-value="onUpdate"`.

**Comment by fairking** [comment]
oh nice, I came from the vuejs2 world. So apologize for any misunderstanding. Closing the issue.

**Comment by fairking** [comment]
Comparing the code against f7 or even ionic I can see the Quasar is more mature and focused on vue only 👍. Thanks.

**Comment by fairking** [comment]
I'll reopen the issue just for one small question, if you don't mind.

The only small issue I can see with those events. Why do we need `@update:model-value` in a first place instead of just `@update`?
I can see a huge issue if you lets say rename some of the model value name to `@update:model-start-date` all users will have problems without noticing (events will just simply stop working). I guess there is no compiler validation against model value names in events.
What do you think guys? I feel like first the `model-value` is unnecessary and the second it creates extra job with keeping this `model-value` names in sync. Unless I missing something important why they required.
