### ISSUE TITLE
Links in documentation do no show keyboard focus

### ISSUE THREAD

**Issue by pbb72** [quasarframework/quasar#12464]
### Description

As part of accessibility requirements, links need to have an indicator to show they have keyboard focus. This is not the case for the Quasar documentation.

The cause of this is simply the `outline: 0` code in the style of `.doc-link` elements.

### Areas

Style & Identity (quasar)

**Comment by rstoenescu** [comment]
Hi,

This is just the docs website. Does not mean apps built with Quasar will have the custom classes that we wrote for the docs.

**Comment by pbb72** [comment]
I clearly stated in both the title and the description that this is concerning the documentation.

Why close the issue, is it fixed? Or don't we care about accessible documentation? (Is it not required by law?)
