### ISSUE TITLE
.fixed-right should not use top: 0

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1248]
### Software version

Quasar: 0.14.7

Actually `.fixed-right` is also using `top: 0` property, which makes `.fixed-right` act as `.fixed-top-right`

https://github.com/quasarframework/quasar/blob/7cc215d3e5f43c4d14d2fae9ff67def9f24fc4b6/src/css/core/positioning.styl#L39

Same with the rest of classes of that kind.

**Comment by rstoenescu** [comment]
Hi,

It actually also needs top 0 and bottom 0 so it can occupy full window height on the right side of screen, which is the intended use.

So it is designed to be positioned like this:
```
========
=     &=
=     &=
=     &=
========
```

If someone wants to get an element at middle-height on right-side, it can use the Quasar CSS flex classes to position it, like this:
`<div class="fixed-right row items-center"> <div>content...</div> </div>`

Mind that that you'd need to also place no-pointer-events and all-pointer-events CSS classes so the user can still click/tap around the inner content div:
`<div class="fixed-right row items-center no-pointer-events"> <div class="all-pointer-events">content...</div> </div>`
