### ISSUE TITLE
Working with q-radio the vuex way - add change events

### ISSUE THREAD

**Issue by MartinMuzatko** [quasarframework/quasar#1254]
Hello!
The documentation says, that I am supposed to use `v-model`. However, this will not work together with Vuex. Instead, I would like to do it as described in the official vue documentation:
```html
<input :value="message" @input="updateMessage">
```
```js
// ...
computed: {
  ...mapState({
    message: state => state.obj.message
  })
},
methods: {
  updateMessage (e) {
    this.$store.commit('updateMessage', e.target.value)
  }
}
```
Right now, it is not possible to set the value of a `q-radio`. (no `@change` or `@onchange`)

I would like to propose to add these events, if it is not possible otherwise.

Best,
Martin

**Comment by rstoenescu** [comment]
Hi, Already done in future v0.15.

**Comment by MartinMuzatko** [comment]
Thanks for the quick response! :D
