### ISSUE TITLE
Extras packages in /dist use the full path of their original location, and are ignored by .gitignore

### ISSUE THREAD

**Issue by dbryar** [quasarframework/quasar#12546]
### What happened?

when building for production, the extras a re-packaged in 
```
/dist/fonts/node_modules/@quasar/extras/<extras included in config>
```
Because the folder contains the keyword `node_modules` in the path, everything below it in the structure is ignored by the standard settings in `.gitignore`.

The workaround at present is to `git add --force /dist/.` but that is not ideal

### Why is this a problem?
Because some old poorly designed deployments require the `/dist` files to be in the git repo. Not everyone has full CI/CD builders at the far end (client, not me)

### What did you expect to happen?

I would expect the files to be packaged in 
```
/dist/fonts/<extras included in config>
```

There is no need for the preceding directory structure from the extras package

### Reproduction URL

N/A

### How to reproduce?

just build a project `quasar build` that uses extras

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

### Platforms/Browsers

Other

**Comment by dbryar** [comment]
Maybe also program action bot to look at the keyword `N/A`, or not applicable, or don't make it a mandatory item to add a URL

**Comment by yusufkandemir** [comment]
Couldn't reproduce.
![image](https://user-images.githubusercontent.com/6266078/154903523-e3dbb5d4-10d8-484d-8d3d-e4de9155e745.png)

The reproduction URL is always applicable. Even if it's a dead-simple fresh Quasar project, you might have some problems with a configuration, maybe about the lock file, etc. So, a repro in any form is always helpful and required. In this case, `quasar info` output, your git config, the packages you specified in `extras`, your build configuration, etc. would have made the difference, but currently, it's not enough to reproduce the problem.

**Comment by dbryar** [comment]
FWIW @yusufkandemir 

```
Operating System - Linux(4.4.0-19041-Microsoft) - linux/x64
NodeJs - 14.17.0

Global packages
  NPM - 7.21.1
  yarn - Not installed
  @quasar/cli - 1.2.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.4.13 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.0 -- Quasar Framework local CLI
  @quasar/extras - 1.12.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.29 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.12
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.12 -- Babel compiler core.
  webpack - 5.67.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

```
 Build succeeded

 Build mode........ spa
 Pkg quasar........ v2.4.13
 Pkg @quasar/app... v3.3.0
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no
 Transpiled JS..... yes (Babel)
 ==================
```

![image](https://user-images.githubusercontent.com/20749904/155034096-38bded9a-feca-4226-8c26-de1e59fd05c3.png)

Props for responding inside 24h, probably less than 12!

It still does the same thing on this project which is a very simple landing page product chooser

**Comment by yusufkandemir** [comment]
Please upgrade `@quasar/app` from v3.3.0 to at least v3.3.1 to get the related fix, which got released almost a month ago. The latest version at the moment is v3.3.3. In general, when troubleshooting, I would advise taking a look at future versions release notes and upgrading packages to see if that solves anything.

Bonus tip: if the intended dist structure was like that(_it isn't_), and you want to not .gitignore it, you would use a negation pattern.
```.gitignore
node_modules/           # Ignore all node_modules folder recursively
!/dist/**/node_modules/ # except the ones inside the dist folder
```

> Props for responding inside 24h, probably less than 12!

You are welcome, 5.5 hours to be precise 😅 We may not always be able to act quickly, but we are trying out best.

Good luck!

**Comment by dbryar** [comment]
Just confirming for anyone else that ends up here;

If you built a project with `quasar create <folder_name>` using quasar CLI, it may have `@quasar/app^3.3.0` in the `package.json`

you need to manually run `npm install @quasar/app@latest` to get 3.3.3, which does indeed fix this build behaviour.
