### ISSUE TITLE
q-btn doesn't talk about `type` property for navigation

### ISSUE THREAD

**Issue by AbhimanyuAryan** [quasarframework/quasar#12564]
### What happened?

from docs: https://v1.quasar.dev/vue-components/button#handling-navigation 

```html
<template>
  <div class="q-pa-md q-gutter-sm">
    <q-btn to="/start/pick-quasar-flavour" label="To Docs index" outline color="purple" />
    <q-btn to="/start/pick-quasar-flavour" label="To Docs index in 2s" @click="linkClick" glossy color="purple" />

    <q-btn href="start/pick-quasar-flavour" label="With href" push color="purple" />
    <q-btn href="start/pick-quasar-flavour" target="_blank" label="With href - open in new window" color="purple" />
  </div>
</template>
```

the `q-btn` component with `href` doesn't talk about `type= "a"` property to turn the `<button>` attribute into `<a>` attribute. Found it the hard way thanks to @protozoo 

The weird part is the examples in docs work without `type= "a"` but in codepen they don't

### What did you expect to happen?

Have the docs example code contain `type= "a"` property

### Reproduction URL

https://codepen.io/abhimanyuaryan/pen/yLPjWew

### How to reproduce?

1. Go to codepen link I gave
2. remove `type= "a"` from `html` code and button navigation will fail

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by AbhimanyuAryan** [comment]
Should I go ahead and make a pull request?

**Comment by rstoenescu** [comment]
@AbhimanyuAryan yes, definitely. please go ahead.

**Comment by AbhimanyuAryan** [comment]
@rstoenescu I can't figure out where are examples for `dev` branch. Docs Github logo takes me to https://github.com/quasarframework/quasar/tree/dev/docs/src/examples/QBtn/Links.vue

Example is available on v1 branch: https://github.com/quasarframework/quasar/blob/v1/docs/src/examples/QBtn/Links.vue

should I change at v1? Or the location for example is changed in dev?

**Comment by yusufkandemir** [comment]
@AbhimanyuAryan please use Docs Report instead of Bug Report next time, as this is not a bug.

Since this applies to examples of both Qv1 and Qv2, you need to create 2 separate PRs, for `dev` and `v1` branches. Here are the file locations for both branches:
`dev`(Qv2): https://github.com/quasarframework/quasar/blob/dev/docs/public/examples/QBtn/Links.vue
`v1`(Qv1): https://github.com/quasarframework/quasar/blob/v1/docs/src/examples/QBtn/Links.vue

Thanks for your effort 👏

**Comment by AbhimanyuAryan** [comment]
@yusufkandemir thanks I'll do that. Is it possible to move this docs report now?

**Comment by yusufkandemir** [comment]
@AbhimanyuAryan it's not that important, don't worry. I've adjusted the labels to reflect the situation, so there is no problem.

**Comment by AbhimanyuAryan** [comment]
added for v1: https://github.com/quasarframework/quasar/pull/12909
added for dev: https://github.com/quasarframework/quasar/pull/12910

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing.
But you're using Quasar v1.4.4... There's a huge difference between 1.4.4 and 1.18.6. Can't remember when I added this feature (of NOT needing type="a" when you already have href), but it definitely wasn't in v1.4.4.
