### ISSUE TITLE
LoadingBar.isActive reactive property

### ISSUE THREAD

**Issue by alainrc2005** [quasarframework/quasar#12573]
### What happened?

isActive reactive property to LoadingBar no working

### What did you expect to happen?

isActive reactive

### Reproduction URL

https://codepen.io/alainrc2005/pen/KKyeBrM?editors=1111

### How to reproduce?

1. View demo in CodePen

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.0 and v1.18.6

**Comment by alainrc2005** [comment]
Thank you very much!!!
