### ISSUE TITLE
opinion: remove 'clear', 'cancel' and 'set' from QDatetime

### ISSUE THREAD

**Issue by jmellicker** [quasarframework/quasar#1259]
Seems like the ideal user experience is to simply click a date, then the picker closes.

(Having to click "set" is too many clicks IMO...)

**Comment by rstoenescu** [comment]
What if the user can also select the hour and minute? Clicking on the exact hour and minute can be error-prone. Will see what I can do.

**Comment by vitorosan** [comment]
You also could have a clear icon on the input (like in QSearch) to clear the value without opening the modal to do it.

**Comment by rstoenescu** [comment]
Done in future v0.15.
