### ISSUE TITLE
q-input with maxDecimals attribute cannot keyin desired value

### ISSUE THREAD

**Issue by Mohanrau** [quasarframework/quasar#1260]
### Software version

Quasar:v0.14.7
OS:
Node:
NPM:
Browsers:chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
if q-input with maxDecimals attribute user cannot type desired value if did so the q-input value keep increasing like step attribute

### What were you expecting?
able to type exact decimal value directly

### What steps did you take, to get the error?

```
<q-input :disable="taxable"
                                 v-model="standardProduct.base_price.gmp_price_tax" :maxDecimals=2
                                 type="number" align="left"
                                 :prefix="currencyLabel" color="black"
                                 :stack-label="$t('products.standard.price.gmp')"
                                 @change="validation.standardProduct.base_price.gmp_price_tax.$touch"
                        />
```

**Comment by rstoenescu** [comment]
Hi, This is already fixed in future v0.15, so closing as v0.15 is close to its release.
