### ISSUE TITLE
Bug in template used to generate `date.d.ts` causes compilation errors.

### ISSUE THREAD

**Issue by supermonkeybrainz** [quasarframework/quasar#12616]
### What happened?

Getting a compilation issue due to [this line](https://github.com/quasarframework/quasar/blob/31fd14a0e3d461f8f4ab6aad2500c47a75773a03/ui/types/utils/date.d.ts#L55).

```
  function getDateDiff(date: Date | number | string, subtract: Date | number | string, unit?: `${DateUnitOptions}s`): number;
```

Note that "unit?: `${DateUnitOptions}s`" part.

### What did you expect to happen?

Not to get a compilation issue.

### Reproduction URL

https://github.com/quasarframework/quasar/blob/quasar-v1.18.5/ui/types/utils/date.d.ts

### How to reproduce?

Look at file.  See bad type.  Apologies for the terse explanation, but this should be self-explanatory.  If you disagree, just close the issue I guess. 🤷   The error occurs on a network that I don't have GitHub access with, so hard to get the details.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by yusufkandemir** [comment]
Hi @supermonkeybrainz. It's not a "bad" type, it is called a [Template Literal Type](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html). You need TypeScript v4.1+. If you are using `@quasar/app` v2.2.0+, you should have TypeScript 4.2+. Just make sure your package versions are correct.

**Comment by supermonkeybrainz** [comment]
Oh, my bad.  Didn't know that was a thing.  Apologize for the confusion.  Thanks!
