### ISSUE TITLE
Data Table when use selection: 'multiple' or 'single'

### ISSUE THREAD

**Issue by soeOleg** [quasarframework/quasar#1261]
quasar-framework: 0.14.7
vue: 2.5.2
OS: Linux Fedora
Chrome,Firefox
theme: default

![1](https://user-images.githubusercontent.com/16119322/33762175-2762eb9a-dc3e-11e7-9389-fdc1b5c58422.jpg)

![2](https://user-images.githubusercontent.com/16119322/33762179-2aa66ce6-dc3e-11e7-9d7b-37cc5f9f47dd.jpg)

**Comment by rstoenescu** [comment]
Hi, QDataTable has been revamped completely in v0.15, so this is outdated. This type of issue cannot occur in the revamp anyway.
