### ISSUE TITLE
🐛 [BUG]: date.formatDate does not allow [ ] in format string

### ISSUE THREAD

**Issue by hinogi** [quasarframework/quasar#12611]
### What happened?

So the token matcher hits on [ ] and [ ] alone, ( ) and { } are a lot in a format string only [ ] does not work.
![image](https://user-images.githubusercontent.com/4602609/155863615-41690d1d-6326-4f68-97c5-8d1154529dba.png)

https://github.com/quasarframework/quasar/blob/82adfbd8997066bec2fcee09d3435f027eafe30e/ui/src/utils/date.js#L13

### What did you expect to happen?

If the other kinds of brackets work [ ] should also work for formatting.

### Reproduction URL

https://jsfiddle.net/hfnrvo61/

### How to reproduce?

`date.formatDate(now, '[ww] dd. DD.MM.YY')`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron, Other

**Comment by pdanpdan** [comment]
Wrap what you want to escape (`[|]`) in `[]`
```js
console.log(date.formatDate(now, '[[]ww[]] dd. DD.MM.YY'))
```

**Comment by hinogi** [comment]
> Wrap what you want to escape (`[|]`) in `[]`
> 
> ```js
> console.log(date.formatDate(now, '[[]ww[]] dd. DD.MM.YY'))
> ```

That is probably the most odd way to escape something that I have seen :D

**Comment by hinogi** [comment]
We shall call it the headphones escape

**Comment by pdanpdan** [comment]
We had to use some markers (start/stop) that escape (do not parse) the content, and these are `[` and `]`
But that means these 2 chars need to be escaped when you want to show them.

If you want to have an output like `[23.12.2022] in DD.MM.YYYY form` you need to use `[[]DD.MM.YYYY[]] [in DD.MM.YYYY form]`

What is between `[` and `]` is output as is, without parsing, all else is tokenized/replaced

**Comment by hinogi** [comment]
> We had to use some markers (start/stop) that escapes (does not parse) the content, and these are `[` and `]` But that means that these 2 chars need to be escaped when you want to show them.
> 
> If you want to have an output like `[23.12.2022] in DD.MM.YYYY form` you need to use `[[]DD.MM.YYYY[]] [in DD.MM.YYYY form]`
> 
> What is between `[` and `]` is output as is, without parsing, all else is tokenized/replaced

That is totally fine, it would be in the docs 😁

**Comment by pdanpdan** [comment]
Until you mentioned I was convinced it is somewhere in the docs.  I'll check and make a PR if it is missing.

**Comment by hinogi** [comment]
organizational blindness, we all been there. Much appreciated the explanation
