### ISSUE TITLE
Vitest and the $q object

### ISSUE THREAD

**Issue by OneFourFree** [quasarframework/quasar#12613]
### What happened?

Running tests on a project using Quasar v2, Vue 3, Vite, and Vitest produces the following error.
```
TypeError: Cannot read properties of undefined (reading 'screen')
 ❯ setup node_modules/quasar/src/components/layout/QLayout.js:35:27
     33| 
     34|     // page related
     35|     const height = ref($q.screen.height)
       |                           ^
     36|     const width = ref(props.container === true ? 0 : $q.screen.width)
     37|     const scroll = ref({ position: 0, direction: 'down', inflectionPoint: 0 })
 ❯ callWithErrorHandling node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22
 ❯ setupStatefulComponent node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6977:29
 ❯ setupComponent node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6933:11
 ❯ mountComponent node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4855:13
 ❯ processComponent node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4830:17
 ❯ patch node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4433:21
 ❯ ReactiveEffect.componentUpdateFn [as fn] node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4970:21
 ❯ ReactiveEffect.run node_modules/@vue/reactivity/dist/reactivity.cjs.js:171:25
 ❯ setupRenderEffect node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5089:9
```

### What did you expect to happen?

The tests to run successfully.

### Reproduction URL

https://github.com/OneFourFree/quasar-vitest

### How to reproduce?

Run `yarn test:unit` on the repo.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

**Comment by yusufkandemir** [comment]
Just calling `mount(...)` of `@vue/testing-utils` straight doesn't and can't install/configure Vue plugins like Vue Router, Vuex, and most importantly Quasar here. So, it's not a Quasar-related issue, but more about how to install Vue plugins or make configurations when using `@vue/testing-utils`.

You can take a look at how it's being handled in Quasar Jest Unit Testing App Extension:
https://github.com/quasarframework/quasar-testing/tree/dev/packages/unit-jest#installquasarpluginoptions
https://github.com/quasarframework/quasar-testing/blob/dev/packages/unit-jest/src/helpers/install-quasar-plugin.ts

You can also make a feature request at https://github.com/quasarframework/quasar-testing about Vitest integration.

**Comment by OneFourFree** [comment]
Thanks, adding a similar function for vitest did the trick

**Comment by ghiscoding** [comment]
@OneFourFree could you provide your solution? I'm trying to write a Vitest unit test as well and I'm facing errors which seems related

```bash
TypeError: Cannot read properties of undefined (reading 'value')
 ❯ setup node_modules/quasar/src/components/drawer/QDrawer.js:88:62
     86|     const belowBreakpoint = ref(
     87|       props.behavior === 'mobile'
     88|       || (props.behavior !== 'desktop' && $layout.totalWidth.value <= props.breakpoint)
       |                                                              ^
     89|     )
```
and I created the helper with this (note I didn't use `clonedeep` from lodash because I didn't want to install extra lib
```ts
import { afterAll } from 'vitest';
import { config } from '@vue/test-utils';
import { Quasar, QuasarPluginOptions } from 'quasar';

export function installQuasarPlugin(options?: Partial<QuasarPluginOptions>) {
  const globalConfigBackup = { ...config.global };

  // We must execute this outside a `beforeAll`
  // or `mount` calls outside `test` context (eg. called into a `describe` context and shared by multiple tests)
  // won't have those defaults applied
  config.global.plugins.unshift([Quasar, options]);

  afterAll(() => {
    config.global = globalConfigBackup;
  });
}
```
```ts
// spec file

installQuasarPlugin();

function mountApp() {
  return mount(PsLeftSidebar, {
    global: {
      plugins: [createI18n({}), Quasar],
    },
  });
}
```

**Comment by OneFourFree** [comment]
@ghiscoding yeah sure, there is an example test in the quasar testing repo. You can find it [here](https://github.com/quasarframework/quasar-testing/blob/dev/packages/unit-jest/src/templates/typescript/test/jest/___tests__/MyDialog.spec.js).
