### ISSUE TITLE
Quasar Tabs (q-tabs) are not accessible using keyboard

### ISSUE THREAD

**Issue by jannhama** [quasarframework/quasar#12621]
### What happened?

Quasar tabs (q-tabs with q-tab or q-router-tab) are not accessible by keyboard. If you try to move between the following things happen:

* When moving forward on the page using the TAB key, the focus goes only to the first tab, and the rest of the tabs are skipped.
* When moving backward on the page using SHIFT + TAB only the last tab is focused and the rest are skipped

### What did you expect to happen?

When using the keyboard only to navigate a web page I would be able to go through all the tabs and activate one I want. 

### Reproduction URL

https://codepen.io/jannhama/pen/RwjEPPE?editors=101

### How to reproduce?

1. Go to the link provided and you should see the basic examples
2. Click on empty space before tabs with mouse
3. Press the TAB key to navigate to the tab
4. Press the TAB key to move to the next tab
5. Focus is not moved to the next tab but to the next tab example
6. Press the SHIFT + TAB key to move backward 
7. Focus is placed to the last tab item
8. Press the SHIFT + TAB key to move backward 
9. Focus is not placed to the previous tab but it jumps away from the tabs.on

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```shell
Operating System   	Linux(5.13.0-28-generic) - linux/x64
NodeJs             	16.13.2

Global packages    	
  NPM              	8.4.1
  yarn             	Not installed
  @quasar/cli      	1.2.2
  @quasar/icongenie	Not installed
  cordova          	Not installed
```

### Additional context

This is an accessibility issue and the user is not able to use tabs or even worse the navigation in case of router tabs.

**Comment by jannhama** [comment]
Updated URL

**Comment by jannhama** [comment]
Fixed URL again since Quasar examples seemed to be empty after sharing.

**Comment by pdanpdan** [comment]
Inside tabs list the navigation is done with arrow keys.
