### ISSUE TITLE
All components' $el has its 'scrollTop' property equals 0

### ISSUE THREAD

**Issue by imdanielpiva** [quasarframework/quasar#1263]
Hi, there, I would like to know why each component's $el is returning scrollTop: 0, any component, then I'm not able to use scroll utils to animate elements. Is there any reason why it could happen?

I'm heavily using QScrollArea, and QInfiniteScroll and QCollapsible for the specific part of the application that I want to animate.

Not showing any code just because it's not an open source project. But I've checked in any component.

### Software version

Quasar: 0.14.7
OS: Deepin Linux
Node: 9.2.0
yarn: 1.3.2
Browsers: Chrome 62.0.3202.89
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
All components' elements return its 'scrollTop: 0'
### What were you expecting?
I was expecting have any other sensible number
### What steps did you take, to get the error?

**Comment by rstoenescu** [comment]
Hi,

Please take a good read at [the specs of scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop), especially the topmost description of it.
