### ISSUE TITLE
Remove explicit blur on QBtn/QToggleBtn click

### ISSUE THREAD

**Issue by Apxdono** [quasarframework/quasar#1265]
I have a question and suggestion on the current `QBtn` `click` logic. Right now `click` triggers automatic `blur` (https://github.com/quasarframework/quasar/blob/dev/src/components/btn/QBtn.js#L42)

This is not a nice behavior, especially when developing accessible applications. 
The problem is that focus on the element gets lost after pressing a button on keyboard. This is especially annoying for `QToggleBtn`. 

Is it ok if I'll create a PR and remove this or there's some specific reason behind this explicit `blur` call.

**Comment by rstoenescu** [comment]
The reason for this is that on mobile, if you don't blur the button then it remains in "active" state.
If you have time, please submit a PR to only emit blur for mobile (make use of  `this.$q.platform.is.mobile`).

Thank you! Be sure to test this thoroughly on mobile and desktop.

**Comment by Apxdono** [comment]
Ok, I'll create a PR 4 this one as well.
