### ISSUE TITLE
Per-Route Transition not working

### ISSUE THREAD

**Issue by kjetilge** [quasarframework/quasar#1266]
I'm trying to transition between two routes and have both animations shown simultaneously. (for example have a new page slide in from the right at the same time as the the old page slides out to the left)

First I tried using a grouped q-transition, but then I get the missing keys on children error.
Then I tried to apply q-transition like in the vue router dos:
```
const Foo = {
  template: `
    <transition name="slide">
      <div class="foo">...</div>
    </transition>
  `
}

const Bar = {
  template: `
    <transition name="fade">
      <div class="bar">...</div>
    </transition>
  `
}
```

I switched transition for q-transition, imported animations from quasar-extras and added enter/leave params.
Then I get the error:  ```Multiple root nodes returned from render.....```

I also tried using plane vue transitions, but that does not work either.

Is there any way to get simultaneous animations on route transitions in Quasar ?

**Comment by rstoenescu** [comment]
Wrap QTransition over <router-view> in your layout and specify mode="in-out". For more details, read about [Transition Modes](https://vuejs.org/v2/guide/transitions.html#Transition-Modes).

**Comment by kjetilge** [comment]
I have tried that now and the result is the same as my first attempt. My layout now looks like this:
```
  <q-layout>
    <q-transition enter="slideInRight" leave="slideOutLeft" mode="out-in" appear>
      <router-view />
    </q-transition>
  </q-layout>
```

When the app transition from page1 to page2 I first see page1 slide to white (background color) then page2 slides in from white.

What I want is for page1 to start sliding at the same time page2 starts sliding, as demonstrated here: https://vuejs.org/v2/guide/transitions.html#Transition-Modes

right under "And then maybe also translated so that they look like slide transitions:"

- the "on-button" slides out to the left as the "off-button" slides in from the right.

It seems what I need to do is to remove mode="out-in" and somehow absolute position "something"

**Comment by kjetilge** [comment]
In my layout vue file style I now added this:
```
  .animated {
    position: absolute;
    top: 0;
    left: 0;
  }
```

And it seems to be working ! :-)

It should be in the documentation how to do this, since it's very often used on master->detail pages (a list of links that when clicked will slide in the detail-page from the right, and the a backbutton should slide the list back in from the left)
