### ISSUE TITLE
[Request] Add circle progress component

### ISSUE THREAD

**Issue by neorganic** [quasarframework/quasar#1267]
Hello it's strange that quasar doesn't has this component, would be great if it would so there would be no need to mix other css/libraries like bootstraps....

Image for visualization : 
![](http://www.jitendrazaa.com/blog/wp-content/uploads/2016/12/Circuar-Progress-Bar-v2-1200x272.gif)

**Comment by rstoenescu** [comment]
Hi, This is equivalent with readonly QKnob:
* http://quasar-framework.org/components/knob.html
* http://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/knob
