### ISSUE TITLE
QField, QInput: append slot position relative to clearable and error icons

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12699]
### What happened?

Append icon shows before error icon and clearable icon

### What did you expect to happen?

Append icon is permanent.
Error icon and clearable icon are temporary.
They should not shift permanent icons.

I think that right order is the following (from let to right): Error icon, clearable icon, append icons.

It can be achieved by adding additional slot that will appear after error and clearable (NOTE: "after" slot does not work because it does not show above lower line as "append" slot).

### Reproduction URL

https://codepen.io/ilyalyu/pen/ZEaNBgQ

### How to reproduce?

https://codepen.io/ilyalyu/pen/ZEaNBgQ

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
I think it makes sense for icons.

The problem I see is for appended text, where it is more frequent to want something like the text directly after the input, but that should be covered by `suffix`.

I cannot find any such case in the material documentation :(

**Comment by iliubinskii** [comment]
> The problem I see is for appended text, where it is more frequent to want something like the text directly after the input

There can be two slots: one directly after the input and one after clear/exclamation icons.
So everybody will be satisfied.
OR
The position of the slot can be determined by additional prop.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.0 and v1.18.6
