### ISSUE TITLE
Linear-progress component doesn't render with rounded corners on Mobile (iOS)

### ISSUE THREAD

**Issue by dmitriyzhuk** [quasarframework/quasar#12694]
### What happened?

When using the linear-progress component with rounded prop it doesn't render with rounded corners. On desktop it renders. this is visible even on the Documentation 

https://quasar.dev/vue-components/linear-progress
Desktop
<img width="875" alt="Screen Shot 2022-03-07 at 8 20 35 PM" src="https://user-images.githubusercontent.com/24543836/157094386-b741cb74-56ce-4baf-8828-d2c4bc0f4bf7.png">

Mobile
![IMG_4132](https://user-images.githubusercontent.com/24543836/157094361-c5c8af28-7ab1-4171-afde-1f4fc6b86aa9.PNG)

### What did you expect to happen?

Should be rounded like on desktop

### Reproduction URL

https://codepen.io/Dmitriyzhuk/pen/yLPrpZG

### How to reproduce?

1. open the doc on desktop https://quasar.dev/vue-components/linear-progress
2. than open on your mobile device https://quasar.dev/vue-components/linear-progress
3. you will notice that the borders are not rounded.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

iOS

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.0 and v1.18.6
