### ISSUE TITLE
Method t setScrollPosition Not working with QScrollArea

### ISSUE THREAD

**Issue by rashnk** [quasarframework/quasar#1270]
Quasar: v0.14.7
Quasar CLI v0.6.4
OS: windows 7
 

**ERROR**
I Cannot set scrollposition to QScrollArea
Error in console

```
[Vue warn]: Error in event handler for "click": "TypeError: Cannot set property 'scrollTop' of undefined"

found in

---> <QBtn>
       <Ayatpage> at src\components\ayat-page\ayat-page.vue
         <QLayout>
           <Index> at src\components\Home.vue
             <App> at src\App.vue
               <Root>
```

**expecting** 
It should set the QScrollArea scroll position to top 

**Steps**
```
<q-btn @click="$refs.myscroll.setScrollPosition(0)" >Click</q-btn>
<q-scroll-area ref="myscroll" style="height:400px" class="bg-yellow-1" >
   <q-list>
   //100 + items ......
   </q-list>
</q-scroll-area>
```

**Comment by BenoitRanque** [comment]
Cannot reproduce

**Comment by rashnk** [comment]
The issue happens when i toggle device mode in chrome
create new quasar project
Copy the src
run quasar dev
open chrome and toggle device mode

**Comment by rashnk** [comment]
to reproduce, 
1.Toggle device mode in chrome 
2. scroll the numbers to bottom 
3. click the button to reset scrollposition it will show error in console
