### ISSUE TITLE
$q.notify not support free drag

### ISSUE THREAD

**Issue by dirkhe1051931999** [quasarframework/quasar#12713]
### What happened?

$q.notify not support free drag

### What did you expect to happen?

$q.notify support free drag

### Reproduction URL

not have url

### How to reproduce?

write code

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
Nowhere in the docs is stated that `Notify` plugin supports any kind of drag behaviour.

**Comment by dirkhe1051931999** [comment]
> Nowhere in the docs is stated that `Notify` plugin supports any kind of drag behaviour.

sometimes the notify is aways show , user want to drag it，it is a feature right?

**Comment by rstoenescu** [comment]
Why is this marked as a bug?

**Comment by rstoenescu** [comment]
Either way, we can't make it draggable as it will break all the animations. Sorry.
