### ISSUE TITLE
[Request] Alert as a Method - add dismissible, duration and possibility to customize a position

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#1271]
Hello,
I'd like to have some options in the alerts as method:

```
Alert.create({
          color: 'dark',
          icon: 'info',
          html: `Data last received 626ms ago...`,
          position: 'bottom-center',

          dismissible: false,
          duration: 1000, // Show the alert for 1 second and then call the dismiss() function
          offset: '50px'
        })
```

Explanation of offset:
The offset defines custom properties of css to the alert, based on the defined main position (top-*, right, bottom-*, left). In the above case, as defined bottom-center, the offset defines the css `bottom: 50px` for the alert, so that it can be positioned above a `q-toolbar` with `slot="footer"` for example.

With offset 50px:
![screenshot_20171210_130348](https://user-images.githubusercontent.com/9668277/33806704-c9f07b6c-ddaa-11e7-91c2-6d4349716b94.png)

Without offset:
![screenshot_20171210_130430](https://user-images.githubusercontent.com/9668277/33806715-e266e294-ddaa-11e7-93c2-2e8c50d4903f.png)

**Comment by rstoenescu** [comment]
Already in future v0.15 as Notify.

**Comment by slowaways** [comment]
Can not wait for version 0.15. :)
