### ISSUE TITLE
[Request] Datatables - Multi-column ordering

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#1272]
I wish Quasar had this feature:
https://datatables.net/examples/basic_init/multi_col_sort.html

Only Office column sort
![screenshot_20171210_134635](https://user-images.githubusercontent.com/9668277/33807103-9285d40a-ddb0-11e7-96b6-83197b8fcde0.png)

Office + Salary columns sort (Press and hold `ALT key` and click in Salary column to combine)
![screenshot_20171210_134250](https://user-images.githubusercontent.com/9668277/33807076-3c7dc43c-ddb0-11e7-8f75-7ce1b8e4ed36.png)

**Comment by rstoenescu** [comment]
Hi,

Sorry but will close this. It's not a bad idea but it would generate a lot of complications and breaking changes in QTable.

**Comment by slowaways** [comment]
:/ Okay.
