### ISSUE TITLE
QChatMessage does not completely work with custom color added to Quasar Color Palette 

### ISSUE THREAD

**Issue by tannert44** [quasarframework/quasar#12747]
### What happened?

Add below to app.scss:

`.text-primary-dark {
  background: $primary-dark  !important;
}

.bg-primary-dark {
  background: $primary-dark  !important;
}`

Create a QChatMessage using that custom color:

`<q-chat-message
          :name="'John Doe'"
          :avatar="'https://cdn.quasar.dev/img/avatar5.jpg'"
          :text="['some text']"
          :sent="true"
          text-color="white"
          bg-color="'secondary-dark'"
        />`
        
 It took me awhile to realize that you have to have both classes for it to be picked up as a color in the Quasar Color Palette so one short side note, would be to mention that some where on the docs for custom colors.  
 
 Once I added both classes it started to pick up the background appropriately, but there is a very tiny triangle off to the side of the chat message that doesn't change with the background when you use custom colors.
 
 I was able to work around this by overriding the following selectors:
 
 `.q-message-text--received:last-child:before {
  border-bottom: 8px solid $secondary-dark
}

.q-message-text--sent:last-child:before {
  border-bottom: 8px solid $accent-dark
}
`

### What did you expect to happen?

The expected result was that the little triangle off to the side of the chat bubble changed with the background. 

### Reproduction URL

https://codepen.io/tanner_terry/pen/YzYKGqv

### How to reproduce?

1. Add below to app.scss

`.text-primary-dark {
  background: $primary-dark  !important;
}

.bg-primary-dark {
  background: $primary-dark  !important;
}`

2. Create a QChatMessage using that custom color

`<q-chat-message
          :name="'John Doe'"
          :avatar="'https://cdn.quasar.dev/img/avatar5.jpg'"
          :text="['some text']"
          :sent="true"
          text-color="white"
          bg-color="'secondary-dark'"
        />`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Hello, I don't understand what is your request.
The codepen has some errors: https://codepen.io/pdanpdan/pen/mdpbrpo

**Comment by rstoenescu** [comment]
The `text-*` classes need to declare "color", not "background" or "background-color".

**Comment by tannert44** [comment]
Thanks. Copy and paste is the devil sometimes
