### ISSUE TITLE
How to to use jsx?

### ISSUE THREAD

**Issue by z245094616** [quasarframework/quasar#12748]
### Description

The project generated directly by vue-cli can use tsx directly using the @vue/babel-plugin-jsx plugin, but the project I generated in quasar-cli cannot be used. The plugin has been added to babel.config.js

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

**Comment by pdanpdan** [comment]
duplicate of https://github.com/quasarframework/quasar/issues/7672, https://github.com/quasarframework/quasar/issues/8503, https://github.com/quasarframework/quasar/issues/8690

@IlCallo can you please check how https://github.com/quasarframework/quasar/issues/8503 was closed? It links to the same issue

**Comment by z245094616** [comment]
Solved, thanks!

**Comment by IlCallo** [comment]
Apparently I self linked the issue by mistake, fixed it to link to the one actually containing the workaround, #8690, thanks for the heads up
