### ISSUE TITLE
QFile is throwing an error when file selection is canceled

### ISSUE THREAD

**Issue by MtDalPizzol** [quasarframework/quasar#12753]
### What happened?

QFile is throwing an error on this scenario:

1. Select a file
2. Click the q-file again to select another file
3. Click the Cancel button on the File selection window

```
Uncaught TypeError: Cannot read properties of undefined (reading 'webkitRelativePath') 
    at use-file.js?v=f4b94cd5:127:25
```

### What did you expect to happen?

Nothing should be thrown when canceling the file selection.

### Reproduction URL

https://codepen.io/mtdalpizzol/pen/mdpbqLp?editors=1111

### How to reproduce?

1. Go to the provided reproduction link
2. Click the QFile input.
3. Select a file.
4. Click the QFile input again.
5. Click the Cancel button on the file selection window
6. Confirm that an error is thrown int the console.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```shell
Not using Quasar CLI.
```

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'webkitRelativePath') 
    at use-file.js?v=f4b94cd5:127:25
```

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.0 and v1.18.7
