### ISSUE TITLE
default property doesn't work with QRouteTab

### ISSUE THREAD

**Issue by Akaryatrh** [quasarframework/quasar#1276]
Quasar: 0.14.7
OS: OSX
Node: v9.2.0
NPM: 5.5.1
Browsers: Chrome

### What did you get as the error?
QRouterTab doesn't handle `default` property
### What were you expecting?
As the documentation says, `The Tabs Router component is just like the QTab component and shares the same properties`, so I was expecting that first tab would be triggered by default if the `q-route-tab` component had the `default` property.
### What steps did you take, to get the error?
Simple usage example:
```javascript
<q-route-tab
  exact
  default
  to="/authenticate/login"
  slot="title"
  label="Login"
  name="login" />
<q-route-tab
  exact
  to="/authenticate/register"
  slot="title"
  label="Register"
  name="register" />
```

**Comment by slowaways** [comment]
Hello @Akaryatrh,
Do you want that when the user visits the route `/authenticate` be redirected to the route `/authenticate/ login`?

**Comment by rstoenescu** [comment]
This is one exception. A component changing route when first being rendered can create havoc and unpredictibility within the app, so the "default" property is not taken into account.

**Comment by Akaryatrh** [comment]
Hey @rstoenescu, thx for explanations 👍
Nevertheless, documentation should maybe tell about this exception. Is there any related repository where I could open a PR to improve current documentation?

@slowaways Yep, exactly. BTW, this can be achieved in many other ways through `vue-router` options, so that's ok :)
