### ISSUE TITLE
Version 1.18.6 is tagged as latest

### ISSUE THREAD

**Issue by ramicohen303** [quasarframework/quasar#12763]
### What happened?

Today's release of 1.18.6 is tagged as latest.

### What did you expect to happen?

v2.5.5 should be tagged as latest

### Reproduction URL

https://www.npmjs.com/package/quasar/v/1.18.6

### How to reproduce?

Go to link

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Done. Thanks for the ticket and sorry for the mixup.
