### ISSUE TITLE
new quasar feature 

### ISSUE THREAD

**Issue by publicocean0** [quasarframework/quasar#1277]
Using instrumentation it is possible to replace a synchronized block (using monitorenter/monitorexit opcodes) with the same block wrapped in quasar RWLock. For understanding if you have to use read or write lock you can analized the block for finding assigmenent to the object synchonized. 
In this way all of old projects can use fibers and developers can continue to use syncronized keyword also in new source code having better performance non only because they use quasar but also because default java monitor is a exclusive lock not a rw lock.

**Comment by pdanpdan** [comment]
Are you sure you're in the right place?

**Comment by publicocean0** [comment]
ops sorry :)
