### ISSUE TITLE
await data from the DB to set up the meta data (meta plugin)

### ISSUE THREAD

**Issue by romain130492** [quasarframework/quasar#12771]
### Description

Hey
im simply trying to set up meta data using the meta() quasar plugin.
im using quasar v1, with SSR.
i want to await for a call in my DB and then set up the meta data with some data, any clear explanation of how to achieve this?

thanks!

### Areas

Plugins (quasar)

**Comment by yusufkandemir** [comment]
[Quasar v1 is EOL](https://github.com/quasarframework/quasar/discussions/15229), so I am closing this issue.

With Quasar v2, it should be possible by using an async `setup()` and then calling `useMeta` composable afterward. But, I didn't test it. Please open a discussion for Quasar v2 if you still need this.
