### ISSUE TITLE
Quasar CLI Vite -  .json from asset folder does not render correctly🔝

### ISSUE THREAD

**Issue by HannesOberreiter** [quasarframework/quasar#12786]
### What happened?

Importing `.json` file do not render correctly inside template.

![example](https://user-images.githubusercontent.com/16878981/158176735-9e9e2a76-7a7f-4994-8683-23b4de7e840f.png)

### What did you expect to happen?

The import should parse the json and work as it is inside the template (works with Quasar CLI webpack ).

### Reproduction URL

https://codepen.io/

### How to reproduce?

1. create Qv2 project with quasar/app-vite v1.0.0-beta.2
2. create a .json file in asset directory
3. add content to .json file `{"name": "Hello World"}`
4. import json `import test from 'assets/test.json`
5. render it inside template `<template>{{test.name}}</template>`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome, Safari

### Quasar info output

```Shell
Operating System - Darwin(21.3.0) - darwin/x64
NodeJs - 14.17.0

Global packages
  NPM - 7.20.5
  yarn - 1.22.17
  @quasar/cli - 1.3.0
  @quasar/icongenie - 2.4.2
  cordova - Not installed

Important local packages
  quasar - 2.6.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.0-beta.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - 2.0.11 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.8.6 -- Native-ESM powered web dev build tool
  eslint - 8.11.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
Cannot reproduce. Seems to work just fine.
Please provide a reproduction repo.

**Comment by HannesOberreiter** [comment]
Hi @rstoenescu, 

thanks for your quick service. Here is a small repo, hope it works. 

The first time I created a repo directly from GitHub:

https://codesandbox.io/s/friendly-butterfly-spijuw?file=/src/pages/Index.vue

Cheers
Hannes

**Comment by HannesOberreiter** [comment]
Oh sorry completely forgot that I changed the javascript code into `<script setup>` this is probably the reason .... need to make a few more tests!

**Comment by rstoenescu** [comment]
Seems to me that it has to do with TS rather than anything else. The `resolveJsonModule` option is not being picked up.

**Comment by rstoenescu** [comment]
@IlCallo @yusufkandemir can one of you take a look pls? Seems to happen only with TS. The "resolveJsonModule" does not seem to be picked up from tsconfig.json

**Comment by Evertvdw** [comment]
I also ran into this with i18n translation files, paste from Discord:
I'm having an issue with importing .json files in my project. I had to add `resolveJsonModule` to `tsconfig.node.json` but now I get this:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/5757159/158244442-d3dc9e9a-849e-4679-b92c-461e176fc4d0.png">
However, adding an include to tsconfig.node.json breaks all other kinds of typing. Also removing the `composite: true` line of that config solves the issue but then tsconfig.json complains that composite true should be set 🤷‍♂️

**Comment by kevingermain** [comment]
I got the same issue when I converted my project and I have no idea after spending a day, where it came from.

**Comment by kevingermain** [comment]
OMG I found the culprit, in quasar.conf.js, if you dont have `include: path.resolve(__dirname, './src/i18n/**'),` inside this part :
```js
  vitePlugins: [
    ['@intlify/vite-plugin-vue-i18n', {
      // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
      // compositionOnly: false,

      // you need to set i18n resource including paths !
      include: path.resolve(__dirname, './src/i18n/**'),
    }],
  ],
```

Somehow, the json imported was behaving like the property `forceStringify` of this plugin.

**Comment by HannesOberreiter** [comment]
I resolved my issue by using the standard tsconfig.json from vitesse template https://github.com/antfu/vitesse/blob/main/tsconfig.json

So far this TypeScript settings work perfectly fine with my Quasar build.

Cheers
Hannes

**Comment by HannesOberreiter** [comment]
Problem seems to fixed with https://github.com/quasarframework/quasar/pull/12978

Thanks!

**Comment by rstoenescu** [comment]
@HannesOberreiter indeed. forgot to mention it here too.
