### ISSUE TITLE
Quasar CLI Vite - quasar dev command not detecting inside yarn workspace

### ISSUE THREAD

**Issue by onurkose** [quasarframework/quasar#12784]
### What happened?

When using yarn workspaces, after installing a quasar project with `yarn create quasar`, running `quasar dev` inside the project folder throws this error:

`App • ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.`

On the other hand, `yarn quasar dev` works fine and initiates the dev server.

### What did you expect to happen?

`quasar dev` detects the project folder even if installed within a yarn workspace.

### Reproduction URL

https://codepen.quasar.dev/

### How to reproduce?

cannot producible over codepen etc.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
yarn run v1.22.17
$ ../../node_modules/.bin/quasar info

Operating System - Darwin(21.3.0) - darwin/x64
NodeJs - 16.6.1

Global packages
  NPM - 7.20.5
  yarn - 1.22.17
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.0-beta.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - 2.0.11 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.8.6 -- Native-ESM powered web dev build tool
  eslint - 8.11.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - *6V***
  en0 - 192.168.2.109
  bridge100 - 10.**.2
  utun3 - 10.**.41
  bridge101 - 10.**.2
```

**Comment by smolinari** [comment]
@onurkose 

> @quasar/cli - undefined

Did you install the (new) global CLI? From the `quasar info` it looks like it is missing.

```bash
$ npm i -g @quasar/cli
```

Scott

**Comment by smolinari** [comment]
Hmm... wait. How did you get `quasar info`...??? :thinking: 

Scott

**Comment by onurkose** [comment]
Yes, I've installed the @quasar/cli.
For another project outside of workspace shows `quasar info` like this:

```
Global packages
  NPM - 7.20.5
  yarn - 1.22.17
  @quasar/cli - 1.3.0
```

But inside the yarn workspace, quasar commands can run only with yarn at the beginning: `yarn quasar info`

**Comment by rstoenescu** [comment]
@yusufkandemir ping. u got time for this?

**Comment by yusufkandemir** [comment]
- `quasar dev`, `yarn quasar dev`, and `yarn dev`(_custom package.json script_) all work fine in Yarn workspaces(v1.22.17). We've been using it on different projects for a long while. I migrated a project to Vite recently as well, so I know that one works too.
- `quasar info` correctly detects packages and their versions.
- The packages are living inside the root `node_modules` and not the project one, so we are really sure that workspace-specific resolving behavior is working correctly too.

So, without a repro, I can't say anything else.

`yarn quasar info`(_and `npx quasar info`_) is showing `@quasar/cli` version as `undefined` because it assumes to be executed globally, and tries to read its own `package.json` for the version. It's not the problem here. It can be a small improvement to have it working though.

**Comment by hawkeye64** [comment]
I'm also having no issues with yarn workspaces. All of my app extensions use yarn workspaces and the docs are quasar projects.

**Comment by rstoenescu** [comment]
@yusufkandemir Not sure what the OP is referring to, but I'm specifically looking into node-packager.js at the hardcoded paths in `isUsed()` method. I might be wrong, but shouldn't a recursive lookup be used instead (just like I'm doing with the quasar.config.js file). If I'm missing something and indeed everything's ok then please close this ticket.

**Comment by yusufkandemir** [comment]
@rstoenescu the OP is referring to `quasar dev` not detecting the project folder(_i.e. `lib/app-paths.js > getAppDir()`_). So, it's not about using the correct package manager. `Quasar v1+ project` part in the message is old, it's now referred to as just `Quasar project`, so it might just be about using an old CLI version. So, I am closing this issue, if we get a repro, we can reopen the issue.

About the recursive lookup in the package manager logic, yes, you are right. But, it still works because even if there is no `yarn.lock` file in a specific workspace, it still uses yarn because `yarn` is installed. But, when using npm workspaces while having yarn installed, it will not find `yarn.lock` nor `package-lock.json` on the project folder, thus will try to use `yarn`. I opened #12959 to cover this part(_not related to this issue_).

**Comment by onurkose** [comment]
@rstoenescu @yusufkandemir

I found the problem, though I'm not sure if it's a bug or not.

Somehow, running the quasar commands in a vite project folder was using `@quasar/app`, instead of `@quasar/app-vite`.

I have two legacy projects within the same workspace that uses `@quasar/app` project rather than `@quasar/app-webpack`, and since its `lib/app-path.js` was trying to find `quasar.conf.js`, instead of `quasar.config.js`, it could not detect the folder is a quasar (vite) project.

**Comment by hyahm** [comment]
@onurkose   Hi,   How to fix this issue

I have create new project . the same issue
```
yarn global add @quasar/cli
yarn create quasar
```
![图片](https://user-images.githubusercontent.com/22030094/169677442-42614ccc-6b32-480b-84e3-be24c0315948.png)

This is `quasar info`
```
PS C:\Users\cande\Desktop> quasar info

Operating System                Windows_NT(10.0.19044) - win32/x64
NodeJs                          16.14.0

Global packages
  NPM                           8.3.1
  yarn                          1.22.17
  @quasar/cli                   1.3.2
  @quasar/icongenie             Not installed
  cordova                       Not installed

Networking
  Host                          DESKTOP-6SSBCHN
  以太网                                192.168.101.11
  VMware Network Adapter VMnet1 192.168.189.1
  VMware Network Adapter VMnet8 192.168.65.1
  vEthernet (WSL)               172.18.192.1
```

add a ext 
```powershell
PS C:\Users\cande\Desktop> cd .\quasar-project\
PS C:\Users\cande\Desktop\quasar-project> quasar ext add draggable
 App • Installing "draggable" Quasar App Extension

 App • Installing quasar-app-extension-draggable...
 App • [sync] Running "yarn add --dev quasar-app-extension-draggable" in C:\Users\cande\Desktop\quasar-project

yarn add v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
warning quasar-app-extension-draggable@0.2.3: When I need similar functionality again in the future I will recreate a new project that is framework agnostic.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@quasar/app-vite > rollup-plugin-visualizer@5.6.0" has unmet peer dependency "rollup@^2.0.0".
warning " > autoprefixer@10.4.7" has unmet peer dependency "postcss@^8.1.0".
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ quasar-app-extension-draggable@0.2.3
info All dependencies
└─ quasar-app-extension-draggable@0.2.3
Done in 2.19s.
 App • Updating /quasar.extensions.json for "draggable" extension ...
 App • Quasar App Extension "draggable" successfully installed.
```
Run it 
```
quasar dev

 App • ⚠️  Extension(draggable): Dependency not found - @quasar/app. Please install it
```

Add @quasar/app and run `quasar dev`
```
 yarn add @quasar/app
PS C:\Users\cande\Desktop\quasar-project> quasar dev

 App • ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.
```
Add @quasar/app-vite and run `quasar dev`
```
 yarn add @quasar/app-vite
PS C:\Users\cande\Desktop\quasar-project> quasar dev

 App • ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.
```

**This is true for any extension added, not just draggable**

**Comment by onurkose** [comment]
with `yarn quasar info`

14 Mar 2022 Pzt 12:38 tarihinde Scott ***@***.***> şunu yazdı:

**Comment by MilosPaunovic** [comment]
@hyahm The `quasar-app-extension-draggable` extension isn't adapted to use Quasar 2.

**Comment by iquirino** [comment]
I've run into this issue running with pnpm (pnpm install & pnpm run dev)
Maybe quasar is not compatible with pnpm..

**Comment by rstoenescu** [comment]
@iquirino inside of your project folder, you need some PNPM config in `.npmrc` (create it if you don't have it):

```
# pnpm-related options
shamefully-hoist=true
strict-peer-dependencies=false
```

Then you can pnpm install.

**Comment by freddy38510** [comment]
@onurkose What is the output of the `which quasar` command in your quasar project folder ?

I guess this could be an interesting information.

**Comment by onurkose** [comment]
> @onurkose What is the output of the `which quasar` command in your quasar project folder ?
> 
> I guess this could be an interesting information.

`/Users/onurkose/.nvm/versions/node/v18.12.1/bin/quasar`

I switched using pnpm instead of yarn long time ago, it's all fine for me now.

**Comment by freddy38510** [comment]
I missed [this comment](https://github.com/quasarframework/quasar/issues/12784#issuecomment-1081896069).

Indeed, the `@quasar/cli` globally installed pkg, [was resolving the quasar binary file from `@quasar/app` pkg first](https://github.com/quasarframework/quasar/blob/%40quasar/cli-v1.4.0/cli/bin/quasar#L40).

@quasar/cli v2 [seems to solve](https://github.com/quasarframework/quasar/blob/%40quasar/cli-v2.0.0/cli/bin/quasar.js#L48) this issue by trying to resolve the quasar binary file from the `@quasar/app-vite` pkg first.

The `yarn run quasar` command uses directly the quasar binary file from the current working directory. This is why it was working fine.

**Comment by alemkhodadadi** [comment]
try `npx quasar ...`
