### ISSUE TITLE
[Discussion] QToolbar, ... - Background color x text color

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#1279]
Let's consider the following toolbar:

*Code:*
```
    <q-toolbar color="light">
      <q-toolbar-title>
        <q-icon name="access_time" /> 11:01
      </q-toolbar-title>
    </q-toolbar>
```
*Output:*
![screenshot_20171211_210131](https://user-images.githubusercontent.com/9668277/33860238-86a402b8-deb6-11e7-9a3d-3acb005bd58f.png)

**The problem:**
By setting a light color on a toolbar, the color of all the text inside it is still light and in that case it should be dark to give the contrast and make the text readable.
_________________
**Temporary solution was:**
```
    <q-toolbar color="light" style="color: #777">
      <q-toolbar-title>
        <q-icon name="access_time" /> 11:01
      </q-toolbar-title>
    </q-toolbar>
```
![screenshot_20171211_210144](https://user-images.githubusercontent.com/9668277/33860424-71340940-deb7-11e7-93d9-1880b36f8725.png)
_________________
If there is already a solution for this in future versions please disregard.
Thanks for listening!

**Comment by rstoenescu** [comment]
Hi,

This is exactly how they are supposed to work. Take a look at the demo source code here: https://github.com/quasarframework/quasar-play/blob/dev/src/components/showcase/navigation/toolbar.vue#L47

The "color" prop is either for background (when non-inverted) or for text (when inverted). This prop itself is a convenience prop to be consistent with all other components, but you can even go wild and don't add any "color" prop but instead use "text-X" and "bg-X" classes on it.

**Comment by slowaways** [comment]
Ok,
Thanks!
