### ISSUE TITLE
Can not run dev server after update

### ISSUE THREAD

**Issue by m00nk** [quasarframework/quasar#12791]
### What happened?

I can run dev server with `quasar dev -m ssr` on versions `quasar@2.5.5` and `@quasar/cli@1.2.2`

When I have updated packages to `quasar@2.6.0` and `@quasar/cli@1.3.0` I have got the error:

```
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'quasar/dist/ssr-directives/index.js'
Require stack:
- /sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/lib/quasar-conf-file.js
- /sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/bin/quasar-dev
- /sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/bin/quasar
- /sites/my/xii-dadvert2/quasar/node_modules/@quasar/cli/bin/quasar
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at QuasarConfFile.compile (/sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/lib/quasar-conf-file.js:575:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async goLive (/sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/bin/quasar-dev:243:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/lib/quasar-conf-file.js',
    '/sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/bin/quasar-dev',
    '/sites/my/xii-dadvert2/quasar/node_modules/@quasar/app/bin/quasar',
    '/sites/my/xii-dadvert2/quasar/node_modules/@quasar/cli/bin/quasar'
  ]
}
```

### What did you expect to happen?

The devr server has to work

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

I don't know how to reproduce this bug outside, sorry

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SSR Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System   	Linux(5.4.0-104-generic) - linux/x64
NodeJs             	16.14.0

Global packages    	
  NPM              	8.5.1
  yarn             	1.22.17
  @quasar/cli      	1.2.1
  @quasar/icongenie	Not installed
  cordova          	Not installed
```

**Comment by rstoenescu** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/4665641/158229296-70e765e5-65d0-4b51-b4bb-2bd18ad02649.png">

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/4665641/158229507-29c8e4da-ff47-426b-9624-d43fb6da4728.png">

**Comment by m00nk** [comment]
@rstoenescu where I can read this explanations (google did not help)? How can I be informed about the breaking changes you will make in future versions?

**Comment by MilosPaunovic** [comment]
Watch Release notes on the docs page [https://quasar.dev/start/release-notes](https://quasar.dev/start/release-notes) or the GH repo.

**Comment by m00nk** [comment]
@MilosPaunovic thank you.
