### ISSUE TITLE
Vite production build warning for app-vite

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#12792]
### Description

When using the app-vite cli, there is a warning when building for production, documented here: https://quasar.dev/start/vite-plugin#warning-when-building-for-production

This section should also be mentioned/moved to the `app-vite` specific section of the docs.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Yes, we are well aware of it. It's an external issue. Please ignore for now as it won't break anything.
