### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module from quasar-config-file.js

### ISSUE THREAD

**Issue by Rolanddoda** [quasarframework/quasar#12818]
### What happened?

I am converting my app to Quasar CLI with Vite. Vite leverages ESM and thus it makes sense to use ESM for  `quasar.config.js`.

So I added `"type":"module"` in package.json and converted the `require` to `import` e.g. this:

```js
const { configure } = require('quasar/wrappers')

module.exports = configure(function (ctx) {
  /* configuration options */
})
```

to this:

```js
import { configure } from 'quasar/wrappers'

export default configure(function (ctx) {
  /* configuration options */
})
```

### What did you expect to happen?

I thought this could work when using Quasar CLI with Vite but it doesn't work and errors show that `node_modules\@quasar\app-vite\lib\quasar-config-file.js` doesn't support ESM.

If that's not a bug, then I suppose it should be a feature request that ESM works in a quasar created project with Quasar CLI with Vite.

### Reproduction URL

no-reproduction

### How to reproduce?

1. Create a new quasar project and choose Quasar CLI with Vite
2. Add "type":"module" to package.json
3. Change `quasar.config.js` to use ESM

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

Do NOT add `"type":"module"` to your package.json and leave quasar.config.js with cjs syntax.
Please report back if it still happens

**Comment by Rolanddoda** [comment]
@rstoenescu I see that `"type":"module"` might not be needed but if you have some scripts in your app and want to use ESM, `"type":"module"` is required.

However, this issue is not about `"type":"module"` but about the ability to use ESM in `quasar.config.js`.

**Comment by rstoenescu** [comment]
In order to use ESM in quasar.config.js the whole q/app-vite CLI needs to be ESM too, because that's the one loading this file. Due to time constraints, it's not yet there. However, it will be in the future.

**Comment by Rolanddoda** [comment]
Great, thanks @rstoenescu for the amazing work!

**Comment by eladcandroid** [comment]
@rstoenescu Hi, any update about using ESM in quasar.config.js? 
I have a Vite plugin which is ESM only and I can't attach it to quasar config.

**Comment by JeRabix** [comment]
@rstoenescu 
1. Is there any hack at the moment so that you can connect the ESM library?
2. Can I help with rewriting the vite cli, are there any developments already?

**Comment by alejandromaier** [comment]
Hello @rstoenescu, is there any updates on this? thanks

**Comment by rstoenescu** [comment]
@eladcandroid @JeRabix @alejandromaier Upgrade to the new beta version -> https://github.com/quasarframework/quasar/discussions/16877
