### ISSUE TITLE
capacitor ios dev not working 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#12812]
### What happened?

run `quasar d -m capacitor -T ios` open Xcode but page stocked at
![Simulator Screen Shot - iPhone 13 - 2022-03-15 at 10 13 02](https://user-images.githubusercontent.com/19895516/158444789-6c9549c0-a410-4974-9905-56a90237772e.png)
 

### What did you expect to happen?

working normally able to access the app

### Reproduction URL

no link 

### How to reproduce?

run `quasar d -m capacitor -T ios` 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

iOS

**Comment by rstoenescu** [comment]
Fix will be available in q/app-vite 1.0.0-beta.4

**Comment by diadal** [comment]
> Fix will be available in q/app-vite 1.0.0-beta.4

in addition after running `quasar build -m capacitor -T android/ios`  then not possible to run `quasar d ` again a lot of errors not being able to find files 

` [ERROR] [plugin vite:dep-scan] ENOENT: no such file or directory, open '/opt/homebrew/var/www/Sites/test/src/assets/index.e5d2c312.js'`

All the index.html files below need to be deleted before `quasar d` could run again

`src-capacitor/android/app/src/main/assets/public/index.html` 
`src-capacitor/ios/App/App/public/index.html`
`src-capacitor/www/index.html`

**Comment by rstoenescu** [comment]
This was handled already. Maybe something changed in the newer Vite versions since then. Will investigate.

**Comment by diadal** [comment]
ok

**Comment by rstoenescu** [comment]
I see now. Some architecture changes broke this.
Fix for dep-scan will be available in q/app-vite beta.4

**Comment by diadal** [comment]
@rstoenescu is it possible beta.4 come with a fix for https://github.com/quasarframework/quasar/issues/12806
