### ISSUE TITLE
Problem resolving icon set mdi-v6 (v2.6.1)

### ISSUE THREAD

**Issue by enpasos** [quasarframework/quasar#12832]
### What happened?

I just did un upgrade

![grafik](https://user-images.githubusercontent.com/9622808/158784484-9b9230c5-88a8-4c40-9f95-c207f3d48878.png)

Reported error on 'quasar dev'

![grafik](https://user-images.githubusercontent.com/9622808/158784789-36806511-2891-4cb0-afa3-58d58dc8bcc1.png)

### What did you expect to happen?

No such error before update.

### Reproduction URL

-

### How to reproduce?

none

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar Extras (@quasar/extras)

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22000) - win32/x64
NodeJs - 14.16.1

Global packages
  NPM - 6.14.12
  yarn - 1.17.3
  @quasar/cli - 1.2.1
  @quasar/icongenie - Not installed
  cordova - 10.0.0 (cordova-lib@10.1.0)

Important local packages
  quasar - 2.6.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.3 -- Quasar Framework local CLI
  @quasar/extras - 1.13.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.1.0 -- Official ESLint plugin for Quasar
  vue - 3.2.29 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.12 -- > This is the repository for Vue Router 4 (for Vue 3)
  vuex - Not installed
  electron - 16.0.2 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 15.4.0 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @babel/core - 7.13.16 -- Babel compiler core.
  webpack - 5.69.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.4 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 6.1.5 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
```

### Relevant log output

```Shell
none
```

### Additional context

none

**Comment by rstoenescu** [comment]
Move to latest q/app-webpack, like in the release notes.

**Comment by enpasos** [comment]
> Move to latest q/app-webpack, like in the release notes.

Thanx for the hint.
I upgraded to ... (from my package-lock.json): 
 
      "dependencies": {
        "@quasar/app-webpack": "^3.4.2",
        "@quasar/cli": "^1.3.1",
        "@quasar/extras": "^1.13.3",
        "axios": "^0.21.4",
        "core-js": "^3.6.5",
        "docsearch.js": "^2.6.2",
        "ndarray": "^1.0.19",
        "ndarray-ops": "^1.2.2",
        "ndarray-resample": "^1.0.1",
        "ndarray-squeeze": "^1.0.2",
        "ndarray-unpack": "^1.0.0",
        "onnxruntime-web": "1.10.0",
        "prismjs": "^1.27.0",
        "quasar": "^2.6.1",
        "tenuki": "^0.3.1",
        "to": "^0.2.9",
        "update": "^0.7.4",
        "vue": "^3.2.29",
        "vue-router": "^4.0.12",
        "webpack": "^5.70.0"
      },
 
But still got the same problem. 

If I comment "iconSet: 'svg-mdi-v6'," in quasar.config.js the application starts.

Maybe you see directly what I'm missing or doing wrong.

**Comment by enpasos** [comment]
I changed the iconset value in quasar.config.js and now it works.

quasar.config.js ...
...
    extras: [
      'roboto-font',
      'material-icons',
      'mdi-v6'
    ],
...
    framework: {
      iconSet: 'mdi-v6',
...


However, in quasar/docs source code I see 

    extras: [
      'material-icons'
    ],
...
    framework: {
      iconSet: 'svg-mdi-v6',

Shouldn't that work?

**Comment by rstoenescu** [comment]
`@quasar/app-webpack` should be in devDependencies. And make sure that you don't have "@quasar/app" there too. Also, what's `@quasar/cli` doing in your project's deps? That a global package. And you still have v1.2.1 of it. Upgrade it to latest. @enpasos 

Best would have been to `yarn global add @quasar/cli@latest` or `npm i -g @quasar/cli@latest` then run `quasar upgrade -i` command. It would have done everything for you.

**Comment by enpasos** [comment]
Thanx a lot. Very helpful. Now works ... and I learned something :-)

**Comment by cmcleese** [comment]
I've always only done `quasar upgrade -i` and did not have `@quasar/app-webpack` included in my dev dependencies.
Must have missed the manual step in a release notes post but regardless this explanation fixed everything.
Many thanks
