### ISSUE TITLE
QCheckbox with fontawesome icon bug

### ISSUE THREAD

**Issue by KINGER404** [quasarframework/quasar#12837]
### What happened?

The icon placed in the q-checkbox is 24x24, but the wrapped area is 20x20. This is especially noticeable on q-checkbox with props dense 

### What did you expect to happen?

Icons and wrapped area were expected to be the same size

### Reproduction URL

https://codesandbox.io/s/hardcore-rui-5p6v71?file=/src/pages/Index.vue

### How to reproduce?

1. Go to the reproduction URL
2. Inspect q-checkbox

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari

### Additional context

For the props dense case, I found that the wrapped tag has a class:
`.q-checkbox--dense .q-checkbox__inner {
  height: .5em;
  min-width: .5em;
  width: .5em;
}`

Whereas, the icon has the class:
`.q-checkbox--dense .q-checkbox__icon {
  font-size: 0.6em;
}`

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.6.3 and v1.18.8
