### ISSUE TITLE
deep extend() turns Date objects into empty objects since v2.6.0

### ISSUE THREAD

**Issue by tiltec** [quasarframework/quasar#12831]
### What happened?

```js
import { extend } from 'quasar'
const result = extend(true, {}, { d: new Date() })
console.log(result.d) // is '{}'!
```

### What did you expect to happen?

Until v2.6.0, deep clone worked fine with Date objects.

I think this commit broke it: https://github.com/quasarframework/quasar/commit/75ffaa28f1b68c9be65be0992823d7edc9f7f463

Non-deep clone is not affected by this.

### Reproduction URL

https://codepen.io/tiltec/pen/OJzMLKe

### How to reproduce?

HTML result is `{ "d": {} }`, should be similar to `{ "d": "2022-03-17T08:57:26.935Z" }`.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.2.
