### ISSUE TITLE
@click does not work inside <q-th>

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12845]
### What happened?

@click does not work inside <q-th>

### What did you expect to happen?

It should work

### Reproduction URL

https://codepen.io/ilyalyu/pen/vYpGyBy

### How to reproduce?

1. Open https://codepen.io/ilyalyu/pen/vYpGyBy
2. Try to click <q-th> - it does not work.
3. Try to click <q-td> - it works norm.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.3.

**Comment by iliubinskii** [comment]
Thx for the fix
