### ISSUE TITLE
Convert project to Quasar CLI with Vite: PWA related section incorrect

### ISSUE THREAD

**Issue by abraxxa** [quasarframework/quasar#12841]
### Description

As discussed with @yusufkandemir on discord, the PWA-related section is incorrect.
The instructions on the first point need to be swapped.
So, it would be "Move quasar.config.js > manifest to /src-pwa/manifest.json" for Webpack to Vite guide.

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite#6-pwa-related

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

PWA Mode

**Comment by yusufkandemir** [comment]
Thanks for reporting! 👏
