### ISSUE TITLE
Vite: Dev env error: Failed to load source map for /node_modules/...

### ISSUE THREAD

**Issue by maggie44** [quasarframework/quasar#12859]
### What happened?

When starting a Vite development environment on a Raspberry PI the following message are displayed from Vite. 

```
6:14:10 PM [vite] Failed to load source map for /node_modules/.q-cache/vite/spa/axios.js?v=b3dc6034.
6:14:10 PM [vite] Failed to load source map for /node_modules/.q-cache/vite/spa/vue.js?v=b3dc6034.
6:14:27 PM [vite] Failed to load source map for /node_modules/vue3-apexcharts/dist/vue3-apexcharts.common.js.
```

The fact it is a Raspberry pi must raise a bunch of questions, especially as I can't seem to reproduce this on my Mac. Not sure if that is a speed or a architecture difference, or if there are errors on other systems that just aren't displayed but are relevant. 

There is a lot of precedent for this though and seems to be related to imported dependencies: https://github.com/nuxt/vite/issues/198

As the errors seems to relate primarily to imports from boot files, a unique Quasar feature, thought this was worth flagging and logging. 

### What did you expect to happen?

There not be errors. 

### Reproduction URL

Try a Quasar Vite setup with Axios, but I haven't been able to reproduce this on a Mac.

### How to reproduce?

N/A, see above, unless you have a Raspberry Pi and really want to get in deep. 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting, but this is outside of our reach as it's a feature of Vite. You might want to report this to Vite.
PS: boot files are not special at all; they're just .js/.ts files importing and exporting "stuff".

**Comment by maggie44** [comment]
Some had noted that adding in all the dependencies helped, which is what lead me to query how it was importing dependencies: https://github.com/nuxt/vite/issues/198#issuecomment-1000347231

After a few days of running it, it now seems to be an intermittent issue, so almost certainly a Vite thing. 

Thanks for the time.

**Comment by maggie44** [comment]
Just for reference, got this today on the Mac. So definitely intermittent and not hardware specific:

`[vite] Failed to load source map for /node_modules/.q-cache/vite/spa/vue-i18n.js?v=b7f12d18.`
