### ISSUE TITLE
ssr not working

### ISSUE THREAD

**Issue by hooman-mirghasemi** [quasarframework/quasar#12852]
### What happened?

quasar build -m ssr   

 Build mode........ ssr
 Pkg quasar........ v2.6.1
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no

 Configured browser support (>= 87.51% of global marketshare):
 · Chrome for Android >= 99
 · Firefox for Android >= 96
 · Android >= 99
 · Chrome >= 90
 · Edge >= 96
 · Firefox >= 89
 · iOS >= 12.2-12.5
 · Opera >= 79
 · Safari >= 13.1

 App • Building the devland SSR directives...
(node:36914) UnhandledPromiseRejectionWarning:   Error: Cannot find module 'quasar/dist/ssr-directives/index.js'
  Require stack:
  - /home/hooman/dev/ss/node_modules/@quasar/app/lib/quasar-conf-file.js
  - /home/hooman/dev/ss/node_modules/@quasar/app/bin/quasar-build
  - /home/hooman/dev/ss/node_modules/@quasar/app/bin/quasar
  - /usr/local/lib/node_modules/@quasar/cli/bin/quasar
  
  - loader.js:902 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:902:15
  
  - loader.js:746 Function.Module._load
    internal/modules/cjs/loader.js:746:27
  
  - loader.js:974 Module.require
    internal/modules/cjs/loader.js:974:19
  
  - helpers.js:93 require
    internal/modules/cjs/helpers.js:93:18
  
  - quasar-conf-file.js:575 QuasarConfFile.compile
    [ss]/[@quasar]/app/lib/quasar-conf-file.js:575:14
  
  - quasar-build:184 async build
    [ss]/[@quasar]/app/bin/quasar-build:184:3
  

(Use `node --trace-warnings ...` to show where the warning was created)
(node:36914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36914) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### What did you expect to happen?

build compelete

### Reproduction URL

das

### How to reproduce?

fdsa

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SSR Mode

### Platforms/Browsers

Chrome

**Comment by hooman-mirghasemi** [comment]
I just ceate a new project and try to run it with ssr. so i see this error:
(node:36914) UnhandledPromiseRejectionWarning: Error: Cannot find module 'quasar/dist/ssr-directives/index.js'

I try it with : quasar dev -m ssr, have same result.

it was a very new project and i dont change any line of code

**Comment by rstoenescu** [comment]
@hooman-mirghasemi Except the new project is using q/app instead of q/app-webpack, which means it's not new. Upgrade the global installation of '@quasar/cli' and run "quasar upgrade -i" in it to auto update everything that's necessary.
