### ISSUE TITLE
can't setup mode: quasar mode add electron/pwa

### ISSUE THREAD

**Issue by suleimanas** [quasarframework/quasar#12853]
### What happened?

Can't add mode after upgrading to the latest version, if you create quasar using Quasar App CLI with Webpack (stable) selecting npm, it uses yarn. and since i don't use yarn i get the error: Command "yarn" failed with exit code: 1

### What did you expect to happen?

install the packages using npm

### Reproduction URL

https://quasar.dev/quasar-cli-webpack/developing-electron-apps/preparation

### How to reproduce?

1. npm init quasar
2. What would you like to build? » App with Quasar CLI, let's go!
3. Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
4. Pick script type: » Javascript
5. Pick Quasar App CLI variant: » Quasar App CLI with Webpack (stable)
6. Pick your CSS preprocessor: » Sass with SCSS syntax
7. Install project dependencies? (recommended) » Yes, use npm
8. quasar mode add electron or quasar mode add pwa

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
quasar mode add electron
 App • Installing Electron dependencies...
 App • [sync] Running "yarn add --dev electron@latest" in D:\work\hailedu_maps\system

'yarn' is not recognized as an internal or external command,
operable program or batch file.

 App • ⚠️  Command "yarn" failed with exit code: 1

 App • ⚠️   FAIL  Failed to install Electron dependencies
```

**Comment by DarkLite1** [comment]
Having the same issue when selecting `npm` instead of `yarn`

Ran:
```
npm init quasar
quasar mode add electron
```
![image](https://user-images.githubusercontent.com/10828570/184311440-ddd001ca-c220-451c-a064-0b82d430ad5f.png)

Quasaer version 1.0.6

I would expect Quasar to use `npm` and not my broken `yarn` installation of the latest version. This does not seem to be the case. @yusufkandemir  can this be reopened?

**Comment by pdanpdan** [comment]
If you have a `yarn.lock` file in the project it would be considered that yarn should be used

**Comment by DarkLite1** [comment]
Yup, removing that worked. Thx :)
