### ISSUE TITLE
QBtnDropdown has no loading slot

### ISSUE THREAD

**Issue by alexrififi** [quasarframework/quasar#12857]
### Description

**QBtnDropdown** has `loading` props with description
> Put button into loading state (displays a QSpinner -- can be overridden by using a 'loading' slot)

But I can't override by this code:
```vue
<q-btn-dropdown loading>
  <template #loading><q-spinner-dots /></template>
</q-btn-dropdown>
```

Cause **QBtnDropdown** has no loading slot (it's also missing in the docs)

### Documentation Section URL

https://quasar.dev/vue-components/button-dropdown#qbtndropdown-api

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
The "loading" slot will be available in Quasar v2.8.0 and v1.19.6
