### ISSUE TITLE
quasar@2.6.1 on vite plugin - language packs error prevent the app from working

### ISSUE THREAD

**Issue by vieruuuu** [quasarframework/quasar#12851]
### What happened?

quasar@2.6.1 with @quasar/vite-plugin@1.0.7

this is the full error:
`The requested module '/node_modules/quasar/lang/en-US.js?v=c9d0fee1' does not provide an export named 'default'`

nothing too special, just the default configuration, i downgraded quasar to 2.6.0 and it all works fine

### What did you expect to happen?

on quasar@2.6.0 its working fine, its the latest bug fix that broke it

### Reproduction URL

no need

### How to reproduce?

just try quasar@2.6.1 with @quasar/vite-plugin@1.0.7 and it should throw in the browser console

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Do not explicitly use the extension.

```js
// bad
import quasarLang from 'quasar/lang/es.js'

// good
import quasarLang from 'quasar/lang/es'
```
