### ISSUE TITLE
Vite: "@charset" must be the first rule in the file

### ISSUE THREAD

**Issue by maggie44** [quasarframework/quasar#12867]
### What happened?

When building using Vite, the following message displays:

```
▲ [WARNING] "@charset" must be the first rule in the file

    <stdin>:68:0:
      68 │ @charset "UTF-8";
         ╵ ~~~~~~~~

  This rule cannot come before a "@charset" rule

    <stdin>:1:0:
      1 │ @font-face {
        ╵ ^
```

There is a proposed fix to consider as default: https://github.com/vitejs/vite/issues/6333#issuecomment-1003318603

### What did you expect to happen?

No need for these error messages to display.

### Reproduction URL

Not applicable

### How to reproduce?

Run `quasar build` on a new Quasar project using Vite (I chose Typescript but otherwise default settings). 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by smolinari** [comment]
@maggie0002 - See here: https://quasar.dev/start/vite-plugin#warning-when-building-for-production

Scott

**Comment by pdanpdan** [comment]
It looks like this works: https://lifesaver.codes/answer/build-includes-charset-problem-5833

In `quasar.config.js` under `build` key
```javascript
{
  build: {
    extendViteConf(viteConf) {
      if (viteConf.css !== Object(viteConf.css)) {
        viteConf.css = {};
      }
      if (viteConf.css.postcss !== Object(viteConf.css.postcss)) {
        viteConf.css.postcss = {};
      }
      if (Array.isArray(viteConf.css.postcss.plugins) === false) {
        viteConf.css.postcss.plugins = [];
      }
      viteConf.css.postcss.plugins.unshift({
        postcssPlugin: 'internal:charset-removal',
        AtRule: {
          charset: (atRule) => {
            if (atRule.name === 'charset') {
              atRule.remove();
            }
          },
        },
      });
    },
  },
},
```

**Comment by smolinari** [comment]
@pdanpdan - Confirmed. This fixes the build warning. Thanks!

Scott

**Comment by maggie44** [comment]
I think there is an upstream fix coming for it too: https://github.com/vitejs/vite/issues/6333#issuecomment-1087409914 & https://github.com/vitejs/vite/pull/7678
