### ISSUE TITLE
Cannot tab forward on Quasar Plugin cancel button

### ISSUE THREAD

**Issue by gwynncausing** [quasarframework/quasar#12871]
### What happened?

when tabbing continuously in the Dialog, it will not focus in the cancel button.

### What did you expect to happen?

It should be able to focus

### Reproduction URL

https://codepen.io/gwynncausing/pen/popNjpX

### How to reproduce?

1. Open the reproduction link or visit this [link](https://quasar.dev/quasar-plugins/dialog#predefined), this is from quasar website.
2. Open any Dialog that has cancel and OK in it.
3. Press tab multiple times

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar), Plugins (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

**Comment by rstoenescu** [comment]
Shift-tab would do the trick. The "OK" button is set as default go-to for focus.
But I see your point. Will exchange positions of OK with Cancel.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.3 and v1.18.8

**Comment by pdanpdan** [comment]
I've never seen a dialog with the cancel button in the primary position.
https://material.io/components/dialogs#anatomy

**Comment by Nisgrak** [comment]
This change needs to be a MAJOR version, this is almost a breaking change...

Anyway this not looks good in a Dialog, even the Material spec says the accept button must be in rigth like @pdanpdan says:
![image](https://user-images.githubusercontent.com/19597708/161081757-d8d9570c-068e-4bfa-87cb-8ea07c1eac33.png)

**Comment by rstoenescu** [comment]
Working on another fix rather than switching buttons order, but in the meantime we can't leave out important functionality.
