### ISSUE TITLE
Data Table - Row Click Issue

### ISSUE THREAD

**Issue by SeoRoman** [quasarframework/quasar#1289]
I noticed rowclick was added in 0.14 and it works great, however my issue is, whenever I have other buttons or checkboxes or inputs on the row, it clicks the row, even if that wasn't the user's intention.

Is there a way to stop that propagation? 

I would prefer to make individual cells clickable, but I can't figure out how to do that...

Thanks!

**Comment by rstoenescu** [comment]
Hi, Use <event>.stopPropagation() on all the children.

**Comment by migsbeast** [comment]
@SeoRoman did that help you? I'm stuck on the same situation where a row that's clickable but has multiple buttons that opens a dialog even though I'm clicking a specific button that has a different function.

**Comment by hawkeye64** [comment]
@migsbeast For each button where you don't want to propagate to the row, then just `@click.stop="myHandler"`
