### ISSUE TITLE
Tree shaking not working when template, script and style are separated into different files

### ISSUE THREAD

**Issue by customautosys** [quasarframework/quasar#12904]
Dear Razvan,

I like to separate my code into scss, html and ts files like this in my Vue files:
```
<style src="./component/component.scoped.vue.scss" lang="scss" scoped></style>
<template src="./component/component.vue.html" lang="html"></template>
<script src="./component/component.vue.ts" lang="ts"></script>
```
Previously, I used importStrategy: 'all', but I notice this has been removed. Auto-import doesn't work when I do this.

Is there any way to get the auto-import working when my styles, templates and scripts are separated in this way? I feel this is a bug because Vue does allow for template, script and style to be placed in separate files, but it doesn't work with Quasar.

I would be happy to try my hand at working on the PR but I was informed by Yusuf to state this first because it's not guaranteed that the PR will be accepted because this is complex.

Thanks a lot!

Cheers,
Wilson

_Originally posted by @siauderman in https://github.com/quasarframework/quasar/discussions/12319_

**Comment by yusufkandemir** [comment]
Let's keep the discussion at the original _discussion_ thread. #12319
