### ISSUE TITLE
QSelect component doesn't hold persisted store properties after refresh

### ISSUE THREAD

**Issue by john6832** [quasarframework/quasar#1290]
### Software version

Quasar: v0.14.7
OS: Linux Mint 18.2 Cinnamon 64-bit
Node: v9.2.1
NPM: 5.5.1
Browsers: Chrome 60.0.3112.90
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
I'm implementing Vuex using the vuex-persistedstate plugin for persisting the store between page refresh using Cookies (same result using localStorage, sessionStorage). The QSelect Component doesn't retain the object while re-rendering the value the computed property gets from the restored store.

### What were you expecting?
The QSelect selected label/value object should be still rendered because the property is still there on the state and it is reactive.
After the refresh, 'selectedProperty' should still be selected on the dropdown.

### What steps did you take, to get the error?
// QSelect configuration

```
<h1>{{selectedProperty.name}}</h1> //This line prints perfect, after refresh

<q-select
          v-model="selectedProperty"
          float-label="Property"
          :options="selectionOptions"
/>
// Blank selection :(

```

// Vuex Store Configuration

```
import * as Cookies from 'js-cookie'
import createPersistedState from 'vuex-persistedstate'

export default new Vuex.Store({
  strict: true,
  modules: {
    fooModule,
  },
  plugins: [createPersistedState({
    getState: key => Cookies.getJSON(key),
    setState: (key, state) => Cookies.set(key, state, {expires: 10, secure: false})
  })]
})
```

Module Configuration

```
const fooModule = {
  namespaced: true,
  state: {
    selectedProperty: {id: 1, name: 'foo'},
    properties: [{id: 1, name: 'foo'}, {id: 2, name: 'foo2'}]
  },
  getters: {
    selectionOptions: state => {

      let options = []

      if (state.properties && state.properties.length > 0) {
        state.properties.forEach(function (property) {
          options.push({label: property.name, value: property})
        })
      }

      return options
    },
  mutations,
  actions
}
}
```

This behavior happens only on the QSelect component so far.

**Comment by pdanpdan** [comment]
In vuex in your code selectedProperty is not an item from properties, but a new object. Try making a options constant with properties and use options[0] as selectedProperty
