### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by oleksandr-vynnyk** [quasarframework/quasar#12917]
### Description

All of links to code example at https://quasar.dev are pointed to incorrect address. E.g. https://quasar.dev/vue-components/table#basic-usage -> "view on github" is pointed to https://quasar.dev/vue-components/table#basic-usage that is not available.

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
It's working, maybe you got stuck in an old docs version? You can try in another browser or in a private window to confirm that it's working.

**Comment by oleksandr-vynnyk** [comment]
@yusufkandemir sorry, "view on github" is pointed to https://github.com/quasarframework/quasar/tree/dev/docs/src/examples/QTable/Basic.vue. The directory "docs/src/examples" does not exist

**Comment by MilosPaunovic** [comment]
You should try from another browser or private window, as Yusuf suggested. It works fine for me, as the link points to [https://github.com/quasarframework/quasar/blob/dev/docs/public/examples/QTable/Basic.vue](https://github.com/quasarframework/quasar/blob/dev/docs/public/examples/QTable/Basic.vue)

**Comment by yusufkandemir** [comment]
@oleksandr-vynnyk no, it used to point to there, but it now points to `/public/examples` instead of `src/examples`:
https://github.com/quasarframework/quasar/blob/8e252753129207d521d176f27bf2648dde70e8ec/docs/src/components/DocExample.vue#L185

That's why I said you might get stuck with an old version.
