### ISSUE TITLE
Child components do not load if routed by "name" instead of "path"

### ISSUE THREAD

**Issue by bryancurran** [quasarframework/quasar#12916]
### What happened?

Given the following route:

`  {
    name: 'user',
    path: '/user',
    component: () => import('layouts/PrimaryLayout.vue'),
    children: [{ path: '', component: () => import('pages/User.vue') }],
  },`

This code **will** work correctly:

`router.push({ path: '/user'});`

However this code **will not** load the child element _pages/User.vue_, only the Layout is loaded:

`router.push({ name: 'user'});`

### What did you expect to happen?

The child element listed in the route should load regardless if navigated to via "path" or "name".

### Reproduction URL

https://codepen.io/indiebryan/pen/NWXdqKx

### How to reproduce?

See code above

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
This is related to Vue Router, and it's not an issue. It's an expected behavior https://github.com/vuejs/router/issues/1254#issuecomment-998720621
