### ISSUE TITLE
Adding a Pinia Store creates a VUex store

### ISSUE THREAD

**Issue by geomatix-au** [quasarframework/quasar#12929]
### What happened?

As per the docs to create a Pinia store using the command line: quasar new store <store_name> 

This creates a vuex store instead of a pinia store

### What did you expect to happen?

Expected a Pinia store to be created

### Reproduction URL

?

### How to reproduce?

In a quasar project with no stores, open up a terminal and enter $ quasar new store <store_name>

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by MilosPaunovic** [comment]
Are your Quasar related dependencies up to date? Can you provide output of `quasar info` command?

**Comment by rstoenescu** [comment]
We've tested this thoroughly. You're either on an old version or else we need more info like @MilosPaunovic requested above.

My first bet would be that you're still on "@quasar/app" instead of switching to "@quasar/app-webpack" (or even "@quasar/app-vite"). And q/app only knows about Vuex so it's natural to create a Vuex store.
My second bet would be that you still have /src/store along with /src/stores (notice the ending "s"). One is for Vuex, one is for Pinia. OR you still have vuex specified in your package.json (and you should obviously remove it).

But we can't tell unless you provide more info. Will reopen when this is provided, otherwise we don't have anything actionable to continue here.

**Comment by Richard-Walter** [comment]
Sorry for the late reply but ive been away the last few days.  As requested here is the output of quasar info:

$ quasar info

Operating System - Windows_NT(10.0.22000) - win32/x64
NodeJs - 14.17.6

Global packages
  NPM - 6.14.15
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - 11.0.0

Important local packages
  quasar - 2.5.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.3 -- Quasar Framework local CLI
  @quasar/extras - 1.12.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.12 -- > This is the repository for Vue Router 4 (for Vue 3)
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.17.5 -- Babel compiler core.
  webpack - 5.69.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.4 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Rich-laptop
  Wi-Fi - 192.168.1.112

**Comment by Richard-Walter** [comment]
Running this command: quasar new store test  produces this output:

![image](https://user-images.githubusercontent.com/47770368/160495242-321db490-7f7e-4987-9afa-c53f4190aad2.png)

**Comment by Richard-Walter** [comment]
As per your docs, the command line to create a pinia store and vuex store are the same:

quasar new store <store_name> [--format ts]
quasar new store <store_name> [--format ts]

How does one differetiate between the two?

**Comment by TobyMosque** [comment]
> Sorry for the late reply but ive been away the last few days. As requested here is the output of quasar info:
> 
> $ quasar info
> 
> Operating System - Windows_NT(10.0.22000) - win32/x64 NodeJs - 14.17.6
> 
> Global packages NPM - 6.14.15 yarn - Not installed @quasar/cli - 1.3.2 @quasar/icongenie - Not installed cordova - 11.0.0
> 
> Important local packages quasar - 2.5.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time @quasar/app - 3.3.3 -- Quasar Framework local CLI @quasar/extras - 1.12.5 -- Quasar Framework fonts, icons and animations eslint-plugin-quasar - Not installed vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI. vue-router - 4.0.12 -- > This is the repository for Vue Router 4 (for Vue 3) vuex - Not installed electron - Not installed electron-packager - Not installed electron-builder - Not installed @babel/core - 7.17.5 -- Babel compiler core. webpack - 5.69.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff. webpack-dev-server - 4.7.4 -- Serves a webpack app. Updates the browser on changes. workbox-webpack-plugin - Not installed register-service-worker - 1.7.2 -- Script for registering service worker, with hooks typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development @capacitor/core - Not installed @capacitor/cli - Not installed @capacitor/android - Not installed @capacitor/ios - Not installed
> 
> Quasar App Extensions _None installed_
> 
> Networking Host - Rich-laptop Wi-Fi - 192.168.1.112

as Razvan said, u would replace your @quasar/app by the @quasar/app-webpack

> My first bet would be that you're still on "@quasar/app" instead of switching to "@quasar/app-webpack" (or even "@quasar/app-vite"). And q/app only knows about Vuex so it's natural to create a Vuex store.

If u don't wanna do that manually, just run:

```bash
npm i -d @quasar/cli@latest
quasar upgrade -i
```

**Comment by Richard-Walter** [comment]
Thanks Toby.  That did the trick.   Is @quasar/app-webpack not the default option when creating a quasar project using the cli?

**Comment by rstoenescu** [comment]
@Richard-Walter Use the new scaffolding method through:

```js
yarn create quasar
# or: npm init quasar
```

Also, make sure that your global installation of `@quasar/cli` is up to date.

It goes without saying, but reading the [release notes](https://quasar.dev/start/release-notes) is very important.

**Comment by CrawfordW** [comment]
Is it possible to have both vuex and pinia in the same project? I have a large app with many vuex modules and want to upgrade to pinia one module at a time. Can't figure out how to do this.

**Comment by lajuffermans** [comment]
> Is it possible to have both vuex and pinia in the same project? I have a large app with many vuex modules and want to upgrade to pinia one module at a time. Can't figure out how to do this.

Any luck on this? Same issue here....

**Comment by CrawfordW** [comment]
I gave up and converted everything to Pinia. It's much better, but still getting the hang of it.

**Comment by TobyMosque** [comment]
> > Is it possible to have both vuex and pinia in the same project? I have a large app with many vuex modules and want to upgrade to pinia one module at a time. Can't figure out how to do this.
> 
> Any luck on this? Same issue here....

is possible, but the quasar cli will handle only the vuex store, u'll need to handle the pinia store.
https://github.com/TobyMosque/q-vuex-to-pinia

**1 - create a new project with pinia and copy the stores folder to your old project with vuex.**
**src/stores/index.js**
```js
import { store } from 'quasar/wrappers'
import { createPinia } from 'pinia'

export default store((/* { ssrContext } */) => {
  const pinia = createPinia()
  // You can add Pinia plugins here
  // pinia.use(SomePiniaPlugin)
  return pinia
})
```

**ALL next steps are part of a migration strategy, they can be removed/reverted as soon the vuex is removed from the project**

**2 - create a boot to handle the pinia, u would remove this boot as soon u get ride of the vuex**
**src/stores/index.js**
```js
import { boot } from "quasar/wrappers";
import createStore from "src/stores/index";
import { unref } from "vue";

// "async" is optional;
// more info on params: https://v2.quasar.dev/quasar-cli/boot-files
export default boot(async (ctx) => {
  const { app, store } = ctx;
  const pinia = createStore(ctx);
  store.pinia = pinia;
  pinia.use(() => ({
    store,
  }));

  app.use(pinia);
  if (process.env.MODE === "ssr") {
    const { ssrContext } = ctx;
    if (process.env.SERVER) {
      ssrContext.onRendered(function () {
        const state = unref(pinia.state);
        this.__pinia = JSON.stringify(JSON.stringify(state));
      });
    }
    if (process.env.CLIENT) {
      const script = document.getElementById("pinia-state");
      if (script) {
        pinia.state.value = JSON.parse(window.__PINIA_STATE__);
        delete window.__PINIA_STATE__;
        script.remove();
      }
    }
  }
});
```

**2.1 - if u'd a SSR app, u would modify your index.html (undo that as soon u remove the vuex from the project)**
```html
  <body>
    <!-- quasar:entry-point -->
    <script id="pinia-state">
      window.__PINIA_STATE__ = {{ __pinia }};
    </script>
  </body>
```

**2.2 - some explanations:**
![image](https://user-images.githubusercontent.com/13981214/233048421-af12659b-6325-418d-9fc7-636cae523d8d.png)

  2.2.1 - the first block is needed to access the pinia instance from the vuex store and vuex store from the pinia stores.
  2.2.2 - the second block is needed only to SSR, 
  
**3 - write a helper to retrieve the pinia store from the boot/prefetch**
**src/composables/pinia.js**
```js
export function usePinia (store) {
  return store.pinia || store
}
```

**3.1 - examples of usage**
```js
import { usePinia } from "src/composables/pinia";
import { useAppStore } from "src/stores/app";
import { boot } from "quasar/wrappers";

export default boot(({ store }) => {
  const pinia = usePinia(store)
  const appStore = useAppStore(pinia)
})
```

```js
import { usePinia } from "src/composables/pinia";
import { useAppStore } from "src/stores/app";
import { preFetch } from "quasar/wrappers";
import { defineComponent } from "vue";

export default defineComponent({
  preFetch: preFetch({ store }) => {
    const pinia = usePinia(store)
    const appStore = useAppStore(pinia)
  })
})
```

**4 - access one store from the another**
**4.1 - pinia instance from the vuex store**

**src/store/app.js**
```js
import { useAppStore } from "src/stores/app";

// u can't access the pinia instance from the vuex store getter, so you need to pass the entire store.
export default function (store) {
  return {
    namespaced: true,
    getters: {
      doSomething(...args) {
        const appStore = useAppStore(store.pinia);
        return appStore.getSomething;
      },
    },
    actions: {
      doSomething(ctx) {
        const appStore = useAppStore(this.pinia);
        appStore.doSomething();
      },
    },
  };
}
```

**src/store/index.js**
```js
import { store } from "quasar/wrappers";
import { createStore } from "vuex";

import app from "./app";

export default store(function (ctx) {
  const Store = createStore({
    strict: process.env.DEBUGGING,
  });
  Store.registerModule("app", app(Store));
  return Store;
});
```

**4.2 - vuex store from the pinia store (options)**
**src/stores/app.js**
```js
import { defineStore } from "pinia";

export const useCounterOptionsStore = defineStore("app", {
  getters: {
    getSomething() {
      return this.store.getters["app/getSomething"];
    },
  },
  actions: {
    async doSomething() {
      await this.store.dispatch("app/doSomething");
    },
  },
});
```

**4.3 - vuex store from the pinia store (setup)**
**src/stores/app.js**
```js
import { defineStore } from "pinia";

export const useCounterSetupStore = defineStore("app", () => {
  // u can't access the vuex getters from an pinia store getter (setup only)
  function getSomething() {
    return this.store.getters["app/getSomething"];
  }
  async function doSomething() {
    await this.store.dispatch("app/doSomething");
  }
  return {
    getSomething,
    doSomething,
  };
});
```
