### ISSUE TITLE
q-expansion-item  attribute active-class  not active

### ISSUE THREAD

**Issue by dirkhe1051931999** [quasarframework/quasar#12930]
### What happened?

q-expansion-item tag set active-class like this
```
:active-class="$route.path === resolvePath(route) ? 'bg-small-blue text-primary active-tab' : 'text-black2'"
```
![image](https://user-images.githubusercontent.com/22389976/160066502-9558c525-4f87-4c75-b787-b6f8fb512bce.png)

but render html not have any class 
![image](https://user-images.githubusercontent.com/22389976/160066434-8a0da8e7-2d11-4566-9a50-b7f49084e61e.png)

### What did you expect to happen?

active attribute

### Reproduction URL

no url

### How to reproduce?

render <q-list> and <q-expansion-item>

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by dirkhe1051931999** [comment]
but other item active-class is active 
same code and not do anything!!!

**Comment by MilosPaunovic** [comment]
If prop `active-class` of one item works correctly and the other ones doesn't, seems like the issue is in the implemented logic and not Quasar itself. Try checking out the condition on which you base your class selection.

**Comment by dirkhe1051931999** [comment]
I have use other method to instead it

**Comment by rstoenescu** [comment]
It doesn't makes any sense to check if the route is the one active inside of `active-class` definition. The active-class is used only when the route is actually active. It's not being used if the route is not active, so doesn't matter what value you're supplying to it in this case.

Please provide a reproduction of your issue so we can help further (https://codesandbox.quasar.dev or https://codepen.quasar.dev), but regardless, I see no bug in Quasar here.
