### ISSUE TITLE
Vue warn when using the router inside of a Pinia store

### ISSUE THREAD

**Issue by Bosphoramus** [quasarframework/quasar#12936]
### What happened?

Since @quasar/app-webpack version 3.4.3 we get a Vue Warn when using the router from Pinia stores, this is the warn: [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

This is caused because the router we provide to the store in the default boot file is not wrapped by Vue's markRaw()

This is documented on Pinia's docs as we can see [here]([#](https://pinia.vuejs.org/core-concepts/plugins.html#adding-new-external-properties))

### What did you expect to happen?

Everything works, at leas on dev mode, but id spect it to work without warnings on the console.

### Reproduction URL

No

### How to reproduce?

Try to use the router with this.router inside of a pinia store on @quasar/app-webpack version 3.4.3 - 3.4.5 and check the console.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SPA Mode

**Comment by rstoenescu** [comment]
Fix will be available in q/app-vite 1.0.0-beta.9 and q/app-webpack v3.4.6
