### ISSUE TITLE
QFab API - active-icon is ignored and forced to load material icons 

### ISSUE THREAD

**Issue by ptc-tonyo** [quasarframework/quasar#12932]
### What happened?

However, the QFAB no longer displays the active-icon.  It will also only display the "close" icon if "material-icons" is included in "extras" setting in `quasr.conf.js`. This was not the case in the past. I didn't need to load "material-icons" at all.

I've attempted to use iconMap to convert "close" icon to "las la-times-circle" but that also failed to map the icon!!
So in summary, to get *any* icon to display I'm forced to load "material-icons" and then it will only use the "close" icon.

 

### What did you expect to happen?

I should be able to set `active-icon="laTimesCircleSolid"` on `<q-fab>` and have it display when active. 

### Reproduction URL

https://codepen.io/tohagan/pen/NWXpKOd

## Test #1

1. Cloned a code sample from QFab into CodePen 
    - https://quasar.dev/vue-components/floating-action-button#expandable   
2. Activated the FAB button and it still the "close" material icon.
2. Set active-icon of 1st <q-fab> to "paid" icon   
3. Activated the FAB button and it still shows the "close" icon.

## Test #2
I have ported an old app that used QFab and worked fine. It used line awesome SVG constants ... 
So in summary, to get *any* icon to display I'm forced to load "material-icons" and then it will only use the "close" icon.

On the <q-fab> element ... 

    :icon="laShareSolid"
    :active-icon="laTimesCircleSolid"

In scripts ... 

    import {   laTimesCircleSolid,   laShareSolid, } from "@quasar/extras/line-awesome";

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19043) - win32/x64
NodeJs - 14.17.3

Global packages
  NPM - 6.14.13
  yarn - 1.22.17
  @quasar/cli - 1.3.2
  cordova - Not installed

Important local packages
  quasar - 1.18.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.9.6 -- Quasar Framework local CLI
  @quasar/extras - 1.13.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - 7.3.3 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.5 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw 
should precache.
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.8.3 -- TypeScript is a language for application scale JavaScript development

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
None
```

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in Quasar v2.6.2 and v1.18.7
