### ISSUE TITLE
exportFile util encoding bug

### ISSUE THREAD

**Issue by jhx-zc** [quasarframework/quasar#12934]
### What happened?

I am trying to export data to csv with utf-8 encoding.But it is not work.
This is my code:
![image](https://user-images.githubusercontent.com/52167297/160132679-fcc71b5b-43c9-47e0-83a4-a13d4ac1ce39.png)

And i can not find any useful doc for exportFile util encoding arg usage.

### What did you expect to happen?

If it my wrong,please tell me how to write the right code.
Or fix this bug...

### Reproduction URL

https://codepen.io/jhx-zc/pen/QWapWRJ

### How to reproduce?

no.Just code err.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by MilosPaunovic** [comment]
Check out that functions documentation:
[https://github.com/quasarframework/quasar/blob/56dd9651d7295819b9f0981157d6dd01b12abb6d/ui/src/utils/export-file.js#L10](https://github.com/quasarframework/quasar/blob/56dd9651d7295819b9f0981157d6dd01b12abb6d/ui/src/utils/export-file.js#L10)

**Comment by jhx-zc** [comment]
It is work when i set truly opt arg:

the key word is: `byteOrderMark:'\uFEFF',`

![image](https://user-images.githubusercontent.com/52167297/160221558-6a9f0b60-b941-4ad6-a166-1666b9634aec.png)

**Comment by rstoenescu** [comment]
There is no need to look at the code. The function is described in detail at https://quasar.dev/quasar-utils/other-utils#export-file

**Comment by jhx-zc** [comment]
If not look at the source code. It's deceptived that parameter `byteOrderMark` have a default value :`\nFEFF`
![image](https://user-images.githubusercontent.com/52167297/160222664-ed78b378-2b1e-45d0-8333-c1f6046ce2e2.png)

**Comment by rstoenescu** [comment]
> If not look at the source code. It's deceptived that parameter `byteOrderMark` have a default value :`\nFEFF`
> 
> ![image](https://user-images.githubusercontent.com/52167297/160222664-ed78b378-2b1e-45d0-8333-c1f6046ce2e2.png)
> 
> 

It doesn't say anywhere that that is the default value. It's just an example to get a feel of what it means.
