### ISSUE TITLE
Boot files don't get passed "store" object when using vuex

### ISSUE THREAD

**Issue by therealcoder1337** [quasarframework/quasar#12952]
### What happened?

`store` is not available in boot files when creating a new Quasar v2 (Vue 3) project with vuex.

This seems to be an issue since `@quasar/app-webpack` version `3.4.*`. Version `3.3.3` still seems to pass `store`, at least in existing projects.

### What did you expect to happen?

Boot files should have `store` available when using vuex.

### Reproduction URL

https://example.com

### How to reproduce?

1. npm init quasar
2. Choices: Quasar CLI, Quasar v2/Vue 3, Javascript, Webpack, Sass/SCSS, ESLint State Management (Vuex), Prettier, Yes - use npm
3. Create some boot file function that logs parameters
4. Add that boot file to `quasar.config.js`
5. `quasar dev`
6. See there are boot function arguments logged, but none of them is `store`

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Additional context

Sorry for not having the time to create an online example.

**Comment by yusufkandemir** [comment]
Couldn't reproduce it, works correctly:
![image](https://user-images.githubusercontent.com/6266078/160289531-7442c2a5-38ce-48f7-96ce-55fbb2d85e98.png)

Full list of options I've used. I tried both npm and yarn, with Node v12, v14, and v16.
```
✔ What would you like to build? › App with Quasar CLI, let's go!
✔ Project folder: … quasar-webpack-vuex-npm
✔ Pick Quasar version: › Quasar v2 (Vue 3 | latest and greatest)
✔ Pick script type: › Javascript
✔ Pick Quasar App CLI variant: › Quasar App CLI with Webpack (stable)
✔ Package name: … quasar-webpack-vuex-npm
✔ Project product name: (must start with letter if building mobile apps) … Quasar App
✔ Project description: … A Quasar Project
✔ Author: … Yusuf Kandemir <yusuf.kandemir@outlook.com.tr>
✔ Pick your CSS preprocessor: › Sass with SCSS syntax
✔ Check the features needed for your project: › ESLint, State Management (Vuex) [DEPRECATED by Vue Team]
✔ Pick an ESLint preset: › Prettier
```

Make sure you've actually selected Vuex by pressing "space" first, then press enter to continue.
![image](https://user-images.githubusercontent.com/6266078/160289711-a5e3c73a-6c45-4ae3-9573-0f4bbe324564.png)
then confirm it's actually selected
![image](https://user-images.githubusercontent.com/6266078/160289744-4ba2cfb2-f004-42e9-9762-2f6340e41273.png)

**Comment by therealcoder1337** [comment]
@yusufkandemir You are right. With Node 16.x it works, I was on Node 17.x before and that seems to have caused this weird issue.

**Comment by yusufkandemir** [comment]
For reference:

https://nodejs.org/en/about/releases/#releases
> After six months, **odd-numbered** releases (9, 11, etc.) become **unsupported**, and **even-numbered** releases (10, 12, etc.) move to **Active LTS** status and are **ready for general use**. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. **Production applications should only use Active LTS or Maintenance LTS releases.**

Here are the NodeJS versions that are properly supported:
For `@quasar/app-webpack`: Node v12, v14, and v16
For `@quasar/app-vite`: Node v14 and v16
