### ISSUE TITLE
When using Qbtn in Qcard. The routing cannot be redirected

### ISSUE THREAD

**Issue by gh81997167** [quasarframework/quasar#12953]
### What happened?

The routing cannot be redirected

### What did you expect to happen?

I want the route to jump

### Reproduction URL

https://codepen.io/gh81997167/pen/oNpWbyw

### How to reproduce?

![image](https://user-images.githubusercontent.com/10526983/160292124-c22f2a2c-bf32-425b-8f26-c718f2868228.png)

<template>
  <q-page class="flex flex-center">
    <div class="row justify-start guess" :style="$q.screen.lt.sm ? '' : 'max-width: 1200px'">
      <q-intersection v-for="index in 30" :key="index" :class="$q.screen.lt.sm ? 'example-item-mobile' : 'example-item'">
        <q-card class="q-ma-sm">
          <q-img basic src="https://img14.360buyimg.com/pop/jfs/t1/138618/7/25168/90974/61bfd694Eeefc0804/5acd9cba58493599.jpg">
            <div class="absolute-bottom text-h6 red text-left">$1688.00</div>
              <q-btn to="/good" @click="linkClick" v-if="$q.screen.lt.sm" ripple size="sm" round class="absolute-bottom-right" color="light-green" icon="shopping_cart" style="right: 5px;bottom: 5px;" />
              <q-btn to="/good" @click="linkClick" v-if="$q.screen.gt.sm" push ripple size="md" round class="absolute-bottom-right" color="light-green" icon="shopping_cart" style="right: 10px;bottom: 10px;" />
          </q-img>
          <router-link to="/good" class="router-link">
            <q-card-section>
              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            </q-card-section>
          </router-link>
        </q-card>
      </q-intersection>
    </div>
  </q-page>
</template>
<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'IndexPage2',
  setup (router) {
    function linkClick(e, go){
      e.navigate = false
      setTimeout(() => {
        go()
      }, 2000)
    }

    return {
      linkClick
    }
  }
});
</script>
<style lang="sass" scoped>
.example-item
  height: auto
  width: 300px
.example-item-mobile
  height: auto
  width: calc(50vw)
.guess
  margin: auto
.router-link
  text-decoration: none
  color: #1d1d1d
</style>

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
nothing
```

### Relevant log output

```Shell
nothing
```

### Additional context

nothing

**Comment by pdanpdan** [comment]
Please make the codepen work

**Comment by rstoenescu** [comment]
@gh81997167 You are probably upgrading from Qv1. The behavior changed.
Instead of `e.navigate = false` just call `e.preventDefault()`.

**Comment by gh81997167** [comment]
> @gh81997167 You are probably upgrading from Qv1. The behavior changed. Instead of `e.navigate = false` just call `e.preventDefault()`.
I tried to use it but it still couldn't jump through the route.

**Comment by gh81997167** [comment]
> > @gh81997167 You are probably upgrading from Qv1. The behavior changed. Instead of `e.navigate = false` just call `e.preventDefault()`.
> > I tried to use it but it still couldn't jump through the route.
You can try running my sample code

the package.json
![image](https://user-images.githubusercontent.com/10526983/160330445-3f2c626e-89f1-48d6-a760-f8828ffb7a02.png)

**Comment by gh81997167** [comment]
> Please make the codepen work

OK，Thanks
