### ISSUE TITLE
Pinia store loses typing in vite SSR setup

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [quasarframework/quasar#12954]
### What happened?

Whenever we create a new store (or even the default one) in Pinia and import it, the types are lost. Actions, getters and state are completely lost.

### What did you expect to happen?

The Pinia store when imported should still have it's typing just like it has when creating a project via Vue's CLI

### Reproduction URL

?

### How to reproduce?

Create a store:

```typescript
// /src/stores/app.ts

import { defineStore } from 'pinia';

export default defineStore('app', {
  state: () => ({ exampleState: 'foo' }),
  getters: {
    uppercaseExample: (state) => state.exampleState.toUpperCase(),
  },
  actions: {
    fetchSomething() { console.log('fetched') }
  }
})

```

Now when we import this store into a `ts` file we do not have the typings on it:

```typescript
import useAppStore from 'stores/app';

export const Component = defineComponent({
  setup() {
    const appStore = useAppStore();

    // TS2339: Property 'fetchSomething' does not exist on type 'Store '.
    appStore.fetchSomething();
  }
})
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support, SSR Mode

### Quasar info output

```Shell
perating System - Linux(5.13.0-37-generic) - linux/x64
NodeJs - 14.19.1

Global packages
  NPM - 6.14.16
  yarn - 1.22.10
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.0-beta.5 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - 2.0.12 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.8.6 -- Native-ESM powered web dev build tool
  eslint - 8.11.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - whatever
  wlo1 - 192.168.5.14
  br-9d3af89047dd - 172.18.0.1
```

### Additional context

I have tried to use a Sandbox to replicate the issue but unfurtonately I'm not getting Typescript suppoer there. I have made the same question in StackOverflow ([question](https://stackoverflow.com/questions/71557584/add-new-root-base-definition-for-pinia)) and @tony has asked me to open an issue with this losing of typing over here.

**Comment by CharlieBrownCharacter** [comment]
@yusufkandemir Let me know if I can do anything else to help you out on this issue

**Comment by yusufkandemir** [comment]
@CharlieBrownCharacter I can't reproduce the issue. A repro is always helpful and saves everybody's time as stated in the issue template and the bot's message. You can use a GitHub repo in this case. Logically, I wouldn't expect such an error to be related to Quasar, but we'll see if you provide a repro.
