### ISSUE TITLE
[Bug] QAutocomplete popover disappearing every second char

### ISSUE THREAD

**Issue by shandrolis** [quasarframework/quasar#1296]
### Software version

Quasar: 0.14.7
OS: W10 x64
Node: v8.9.3
NPM: v5.5.1
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
When giving an input, the popover is displayed only every second character
### What were you expecting?
The popover to be displayed as long as there is input
### What steps did you take, to get the error?
I have an array containing objects. I want to search all fields on every object in this array, and if a (partial) match has been found, display this in the popover.

![image](https://user-images.githubusercontent.com/10201423/33939872-14e4982e-e00d-11e7-9fee-2a8d2f7858bd.png)

![image](https://user-images.githubusercontent.com/10201423/33940075-f538227e-e00d-11e7-9376-0b025c14656c.png)

When inspecting the component with chrome's vue dev tools you can see the popover's `opened` boolean is switching between true and false very quickly which somehow confuses Vue.

A workaround is adding a `setTimeout( () => done(result), 50)` in my @search implementation.

Example code blow.

`<template>
  <div class="layout-padding">

    <q-card class="bg-white" style="min-height: 20vh;">
      <q-search icon="mail_outline" style="padding: 20px; margin: 10px; max-width:40vw"
                v-model="input"
                type="email"
                placeholder="Search..."
      >
        <q-autocomplete
          separator
          :debounce="0"
          ref="autocomplete"
          @search="search"
        />

      </q-search>

    </q-card>
  </div>
</template>

```
<scrript>
  import { QAutocomplete, QSearch, QCard } from 'quasar-framework'

  export default {
    data: function () {
      return {
        input: '',
        dataSource: [{
          'username': 'user_001',
          'email': 'user001@company.com',
          'firstname': 'Scot',
          'middlename': null,
          'lastname': 'Wyatt'
        }, {
          'username': 'user_002',
          'email': 'user002@company.com',
          'firstname': 'Seth',
          'middlename': null,
          'lastname': 'Benson'
        }, {
          'username': 'user_003',
          'email': 'user003@company.com',
          'firstname': 'Robert',
          'middlename': null,
          'lastname': 'Linwood'
        }, {
          'username': 'user_004',
          'email': 'user004@company.com',
          'firstname': 'Timothy',
          'middlename': null,
          'lastname': 'Webster'
        }, {
          'username': 'user_005',
          'email': 'user005@company.com',
          'firstname': 'Ben',
          'middlename': null,
          'lastname': 'Sanders'
        }]
      }
    },
    name: 'testy',
    components: {QSearch, QAutocomplete, QCard},
    methods: {
      search (terms, done) {
        let result = []
        console.log('searchterms is ', terms)
        this.dataSource.forEach(user => {
          for (let i in user) {
            if (user.hasOwnProperty(i) && user[i] !== null && user[i].toLowerCase().includes(terms.toLowerCase())) {
              if (result.some(item => item.label === user.username)) continue
              result.push({
                label: user.username,
                icon: 'person'
              })
            }
          }
        })
        console.log('result:', result)
        setTimeout(() => {
          // done(result)
        }, 50)
        done(result)
      },
    }
  }```

**Comment by rstoenescu** [comment]
Hi. There's no problem with QAutocomplete.

The results have no "value" prop specified.
```js
result.push({
  label: user.username,
  icon: 'person',
  value: user.email // <<<<<<<<<<<<<<<<
})
```

**Comment by shandrolis** [comment]
Adding a value prop makes no difference.

**Comment by rstoenescu** [comment]
Time does not allow to make a test on v0.14, but I can assure v0.15 is working as expected.

**Comment by wc-matteo** [comment]
Same issue here on v0.14
