### ISSUE TITLE
QSelect - Popup opens when chips deleting with removeAtIndex() in multiple-mode

### ISSUE THREAD

**Issue by namespace-github** [quasarframework/quasar#12976]
### Description

Using Quasar 2.6.2

The  "removeAtIndex"-method in the following example triggers the opening of the popup.

```html
<q-select multiple use-chips v-model="items">
    <template #selected-item="scope">
      <q-chip>
        {{ scope.opt }}
        <q-btn
          icon="remove"
          @click.stop=" scope.removeAtIndex(scope.index)"
        />
      </q-chip>
    </template>
</q-select> 
`````

If i remove this method with only "@click.stop" then the click-action do not trigger the popup

### Documentation Section URL

https://quasar.dev/vue-components/select#qselect-api

### Areas

Components (quasar)

**Comment by hendrik-schneider** [comment]
I can limit the Problem to the fact, that the popup opens only if the last of all chips being removed.

Here is an example of the Problem.

[https://codepen.io/2425273039/pen/mdpMewZ?editors=101](https://codepen.io/2425273039/pen/mdpMewZ?editors=101)

**Comment by pdanpdan** [comment]
Also add .prevent
https://codepen.io/pdanpdan/pen/MWrvyGa?editors=1000

**Comment by hendrik-schneider** [comment]
> Also add .prevent https://codepen.io/pdanpdan/pen/MWrvyGa?editors=1000

That works! Thank you.
