### ISSUE TITLE
Error in getting started doc - config not set

### ISSUE THREAD

**Issue by jornhd** [quasarframework/quasar#12986]
### Description

In the Getting started page, under Vite plugin for Quasar:
When following the exact instructions, you'll get the error: `Cannot read property 'config' of undefined` when trying to use a component.
After hours of googling, trying and failing I discovered that I needed to add an empty config object in the app.Use Quasar option.
So instead of having this in main.js:
```js
myApp.use(Quasar, {
  plugins: {}, // import Quasar plugins and add here
})
```
It should be like this:
```js
myApp.use(Quasar, {
  plugins: {}, // import Quasar plugins and add here
  config: {},
})
```

There is a switch to include Quasar Config Object, but this comments out the entire config object, not the content.
This:
```js
myApp.use(Quasar, {
  plugins: {}, // import Quasar plugins and add here
  /*
  config: {
    brand: {
      // primary: '#e46262',
      // ... or all other brand colors
    },
    notify: {...}, // default set of options for Notify Quasar plugin
    loading: {...}, // default set of options for Loading Quasar plugin
    loadingBar: { ... }, // settings for LoadingBar Quasar plugin
    // ..and many more (check Installation card on each Quasar component/directive/plugin)
  }
  */
})
```
should be this:
```js
myApp.use(Quasar, {
  plugins: {}, // import Quasar plugins and add here
  config: {
    /*
    brand: {
      // primary: '#e46262',
      // ... or all other brand colors
    },
    notify: {...}, // default set of options for Notify Quasar plugin
    loading: {...}, // default set of options for Loading Quasar plugin
    loadingBar: { ... }, // settings for LoadingBar Quasar plugin
    // ..and many more (check Installation card on each Quasar component/directive/plugin)
    */
  }
})
```

### Documentation Section URL

https://quasar.dev/start/vite-plugin

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Not sure what you tested, but you don't need that.
I just tested it. Then I also look at the code again. You don't need it...

Attaching a project folder which follows the guide on https://quasar.dev/start/vite-plugin to the letter.
Your problem must come from somewhere else.

[my-vue-app.zip](https://github.com/quasarframework/quasar/files/8382667/my-vue-app.zip)
