### ISSUE TITLE
A minimum size must be forced for a Modal Layout or else the window dissapears

### ISSUE THREAD

**Issue by realcarbonneau** [quasarframework/quasar#1298]
The <q-modal-layout> seems to require a minimum or else the window dissapears when it is not full screen.   This is a problem if the user wants the minimum size modal dialog box, while also retaining reactivity.  A workaround is to use the Toolbar directly within the modal without the ModalLayout, thus providing most of the same functionalities, however, this workaround may have other problems  since it is not following the suggested usage.

Quasar CLI v0.6.4
App running on Quasar v0.14.7
Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Firefox Version 57.0.2 (64-bit)
Windows 10
Tested with both 'quasar dev mat' and 'quasar dev ios'.

This attached script demonstrates the problem:
Modal A: Works because the minimum size is forced
Modal B: The Modal window dissapears once the display window is big enough to switch out of fullscreen.
Modal C: This workaround that avoids the ModalLayout and displays correctly

<template> 
  <div>
    <q-btn @click="$refs.modalA.open()">Open Modal A</q-btn>
    <q-btn @click="$refs.modalB.open()">Open Modal B</q-btn>
    <q-btn @click="$refs.modalC.open()">Open Modal C</q-btn>
    
    <q-modal ref="modalA" :content-css="{minWidth: '80vw', minHeight: '80vh'}">
      <q-modal-layout>
        <q-toolbar slot="header">
          Modal A
        </q-toolbar>
        <q-toolbar slot="footer">
          <q-btn @click="$refs.modalA.close()">Close</q-btn>
        </q-toolbar>
        <div class="layout-padding">
          <p>Content</p>
        </div>
      </q-modal-layout>
    </q-modal>
    
    <q-modal ref="modalB">
      <q-modal-layout>
        <q-toolbar slot="header">
          Modal B
        </q-toolbar>
        <q-toolbar slot="footer">
          <q-btn @click="$refs.modalB.close()">Close</q-btn>
        </q-toolbar>
        <div class="layout-padding">
          <p>Content</p>
        </div>
      </q-modal-layout>
    </q-modal>
    
    <q-modal ref="modalC">
      <q-toolbar>
        Modal C
      </q-toolbar>
      <div class="layout-padding">
        <p>Content</p>
      </div>
      <q-toolbar>
        <q-btn @click="$refs.modalC.close()">Close</q-btn>
      </q-toolbar>
    </q-modal>
  </div>
</template>

<script>
</script>

<style lang="stylus">
</style>

[ModalTest_vue.txt](https://github.com/quasarframework/quasar/files/1557373/ModalTest_vue.txt)

**Comment by rstoenescu** [comment]
Using QToolbar within a layout, or using a modal layout within a Modal is NOT enforced. You as a developer can choose to display the Modal however you want. It is currently designed to take the width from its content unless you specify a min-width, which allows for great flexibility.

Am I missing the point here? If so, please feel free to reopen.

**Comment by realcarbonneau** [comment]
![modal](https://user-images.githubusercontent.com/29619229/34328831-186363fe-e8b9-11e7-8669-379b858d54f8.gif)

Check the video, Modal B should work.  I will try to figure it out.

**Comment by mattisback** [comment]
I still get this problem.. Maybe I misunderstand it.  The docs seem to say that to build a modal you should use QModalLayout but QModalLayout only seems to work with a fixed width/height.

**Comment by realcarbonneau** [comment]
I have a patch in my fork that fixes this, but I haven't checked it in a while.  Do you need this?

**Comment by mattisback** [comment]
I ended up getting around this issue by using method C instead of B.  Thanks.
