### ISSUE TITLE
q-popup-edit. v-slot:title isn't working

### ISSUE THREAD

**Issue by syldman** [quasarframework/quasar#12993]
### What happened?

**title** slot on q-popup-edit doesn't work. 

The docs show an example with **title** slot, and the **title** slot doesn't work there too (check 'Calcium' column)
https://quasar.dev/vue-components/popup-edit#with-qtable

### What did you expect to happen?

trying to use v-slot:title to edit title class/style

### Reproduction URL

https://quasar.dev/vue-components/popup-edit#with-qtable

### How to reproduce?

1. https://quasar.dev/vue-components/popup-edit#with-qtable
2. popup-edit on Calcium column should show 'My Custom Title' as the popup title

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

**Comment by metalsadman** [comment]
@syldman there's no slot `title` but a prop, nor other slot other than the `default`.

**Comment by rstoenescu** [comment]
@syldman 

Thanks for reporting the error in the docs example. The "title" slot was removed in Qv2 but somehow this example wasn't updated fully. Fixed it and will be available in next docs deployment.

Main idea is: write your custom title directly in the default slot or use the "title" prop. For reference:

```html
<q-td key="calcium" :props="props">
  {{ props.row.calcium }}
  <q-popup-edit v-model="props.row.calcium" v-slot="scope">
      <div class="text-italic text-primary">
        My Custom Title
      </div>
      <q-input type="number" v-model.number="scope.value" dense autofocus @keyup.enter="scope.set" />
  </q-popup-edit>
</q-td>
```
