### ISSUE TITLE
QSelect input event not emitted when selected value has not changed

### ISSUE THREAD

**Issue by hctpbl** [quasarframework/quasar#1299]
### Software version

Quasar: 0.14.7

### What did you get as the error?
Case scenario:
I use q-select to show a list of options. When I select some of them, I not only expect the selected value to be set to the model, I also want some additional actions to be performed, so I use the `value` prop and the `input` event to handle the internal logic of my app instead of using v-model. My q-select, then, looks like this:

```
<q-select
   :value="getSelectedParameterValue(parameterName)"
   @input="value => { selectNewValue(parameterName, value) }"
   :options="options" />
```

Let's say the available options are time spans:

```
[...]: {
   options: [
      {
          label: 'Monthly',
          value: '1m',
      },
      {
          label: 'Weekly',
          value: '1w',
      },
      {
          label: 'Custom',
          value: 'custom',
      },
   ]
}
```

When the user clicks on the 'Monthly' or 'Weekly' options, the `selectNewValue` method I call when the `input` event is emitted will just assign the new value to the model, but if the user clicks on the 'Custom' option I want to show some controls for the user to select a custom time span before assigning the new value to the model.

This approach works, except when a user is seeing a custom time span and he uses the `q-select` again, choosing the 'Custom' option one more time, to make the dialog open again and select a different time span.

### What were you expecting?
There is already a method present in the q-select interface, `change`, that only fires when the chosen value has actually changed. I expect the `input` event to be fired every time a value has been chosen, regardless of it being different to the one that was selected before.

When I look at the `__emit` event on the `select-mixin.js` [I see the code checking for equality with the old value to emit both the `input` and the `change` event](https://github.com/quasarframework/quasar/blob/v0.14.7/src/components/select/select-mixin.js#L83). IMHO, I would always emit the `input` event, and emit the `change` event only when there is a change:

```
    __emit (val) {
        this.$emit('input', val)
        if (this.value !== val) {
            this.$emit('change', val)
        }
    },
```

In case this is not a feasible option, I would at least expect to be able to:
* Pass an option to Quasar's component so it always emits `input` when an element of the list is selected.
* Have a new event, different from `input` and `change`, to be emitted every time an option is selected.

I can happily make a PR to fix it if you suggest me which strategy to follow.

P.S: I have temporarily fixed this issue for me by creating my own component to extend Quasar's `q-select` replacing the `__singleSelect` method. Not an elegant solution, but working.

**Comment by rstoenescu** [comment]
`@input` and `@change` events have been rethought in v0.15 and this issue has been implicitly fixed. Waiting on Vue's v-model "lazy" modifier to work on components too (PR submitted).
