### ISSUE TITLE
q-chips can't react to @click event

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#13012]
### What happened?

Created a q-chip and tried to do something when clicked

### What did you expect to happen?

Execute the function

### Reproduction URL

https://codesandbox.io/s/rough-dust-0g9i6n?file=/src/pages/Index.vue

### How to reproduce?

Gust declare a q-chip, and try to execute a function reacting to the @click event

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System        Linux(5.13.0-37-generic) - linux/x64
NodeJs                  12.22.1

Global packages    
  NPM                   6.14.12
  yarn                  1.22.17
  @quasar/cli           1.2.2
  @quasar/icongenie     Not installed
  cordova               Not installed
```

### Additional context

From the VueDevTool you can see that the event is generated but the funcion isn't called

**Comment by rstoenescu** [comment]
`<q-chip clickable @click="...`
You forgot about the "clickable" prop.

**Comment by vandelpavel** [comment]
Missed that, thanks!
