### ISSUE TITLE
QEditor: Uncaught TypeError: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by frodronn** [quasarframework/quasar#13019]
### What happened?

In QEditor, when the input field is focused and editor is unmounted e.g., by a click outside, an error occurs:

![image](https://user-images.githubusercontent.com/58413819/161206714-154a6f2d-e1b0-43ea-9c8c-d1631fd8ac63.png)

Related / similar problem? -> https://github.com/quasarframework/quasar/issues/11272

Tested latest on quasar@2.6.4

### What did you expect to happen?

Expect error not to occur.

### Reproduction URL

https://codepen.io/frodronn/pen/QWaqraq

### How to reproduce?

1. Go to the reproduction URL
2. Click the button to display the editor
3. Click inside the input field to obtain focus
4. Click outside the editor so the dropdown closes
5. See console for error

### Flavour

UMD

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.6
