### ISSUE TITLE
wrapCsvValue fails for exportTable if format function uses a row in the calculation.

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#13029]
### What happened?

One column definition for my table looks like this:

```
        {
          name: "bholdings",
          align: "center",
          label: "HLDGS",
          field: "bholdings",
          format: (val, row) => ( val && !row.bwashsale), // hide wash sale records from holdings
          sortable: true,
          sortOrder: "da",
          sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
        },
```

It's important that the row element be there for display purposes.  But because the row isn't passed to wrapCsvValue, it fails with the error below when trying to export to a spreadsheet.  I suspect this affects Qv2 as well.

![image](https://user-images.githubusercontent.com/12553953/161329186-8ebf1852-b741-430c-aeca-bcb0639b231c.png)

### What did you expect to happen?

Receive a spreadsheet

### Reproduction URL

https://codepen.io/daemach/pen/LYeOEGM

### How to reproduce?

Any column formatting function that needs something from the row will fail when exporting to table.  See codepen above.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

SPA Mode

### Platforms/Browsers

Firefox

**Comment by rstoenescu** [comment]
Hi,

This is not a Quasar issue, so it should have rather been a discussion on "how to adapt one example from Quasar docs to my specific use-case".

So that's what you need to do. Adapt the example to your needs:

```js
function wrapCsvValue (val, formatFn, row) {
  let formatted = formatFn !== void 0
    ? formatFn(val, row)
    : val

  formatted = formatted === void 0 || formatted === null
    ? ''
    : String(formatted)

  formatted = formatted.split('"').join('""')
  /**
   * Excel accepts \n and \r in strings, but some other CSV parsers do not
   * Uncomment the next two lines to escape new lines
   */
  // .split('\n').join('\\n')
  // .split('\r').join('\\r')

  return `"${formatted}"`
}
```

And then call `wrapCsvValue()` with an additional param: the `row` that you need:

```js
const content = [ this.columns.map(col => wrapCsvValue(col.label)) ].concat(
        this.data.map(row => this.columns.map(col => wrapCsvValue(
          typeof col.field === 'function'
            ? col.field(row)
            : row[col.field === void 0 ? col.name : col.field],
          col.format,
          row // <<<--- the additional param here
        )).join(','))
      ).join('\r\n')
```

**Comment by Daemach** [comment]
I appreciate your taking the time to show me this.  I'm likely not the only person that is going to run into this situation, and you lose nothing by making this change centrally.  Why not include this in the codebase to prevent the next guy from having to puzzle through or seek out this solution?

**Comment by rstoenescu** [comment]
@Daemach done. would appreciate some help PRing stuff like this as it allows us to focus on the core things.

**Comment by Daemach** [comment]
@rstoenescu you make a good point.  I'll do that next time.
