### ISSUE TITLE
Q-Table grid mode styling bug with selection enabled

### ISSUE THREAD

**Issue by Diesmo** [quasarframework/quasar#13021]
### What happened?

Selecting an grid item (clicking the checkbox) in a Q-Table in gridmode with enabled selection-model makes the selected grid items wider.

### What did you expect to happen?

The grid item to not get wider after selecting it.

### Reproduction URL

https://codepen.io/Diesmon/pen/dyJVgRO

### How to reproduce?

1. Go to the codepen
2. Click any checkbox of a card/grid-item
3. See the item get wider

### Flavour

UMD

### Areas

Components (quasar), Style & Identity (quasar)

### Additional context

Most likely a bug in concatenating the CSS classes while adding the `q-table__grid-item--selected` to the class list, as it is added without a space-character before it, therefore its merging with the `col-lg-3` standing right before it and rendering both classes useless.

Without the space:
![Screenshot from 2022-04-01 12-12-51](https://user-images.githubusercontent.com/17813062/161245767-39b3d30d-3edb-45b8-a4c4-e801d45539db.png)
![Screenshot from 2022-04-01 12-13-36](https://user-images.githubusercontent.com/17813062/161245834-49830398-aafb-4bd0-b690-8144c50b8d09.png)

With manual added space:
![Screenshot from 2022-04-01 12-26-20](https://user-images.githubusercontent.com/17813062/161245969-c0f3ef26-0c45-4e77-a06f-449f751ff518.png)
![Screenshot from 2022-04-01 12-26-28](https://user-images.githubusercontent.com/17813062/161245998-d7194f10-7644-4aa6-810e-48f9b249da47.png)

Codepen was taken and modified from [your docs](https://quasar.dev/vue-components/table#grid-style) (Added selection model)

**Comment by Diesmo** [comment]
Forgot to add that the codepen is running Quasar v2.6.4, which should be the latest.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.6
