### ISSUE TITLE
Qtable wrongly appends q-table__grid-item--selected class

### ISSUE THREAD

**Issue by Apollo314** [quasarframework/quasar#13053]
### What happened?

When you select rows in grid mode, quasar appends selected class without space. which breaks col-lg-3 class and itself.

![image](https://user-images.githubusercontent.com/29009961/161457976-5e430191-6959-482b-a28c-232fffeeea39.png)

### What did you expect to happen?

the class should be appended with a space in between. 

### Reproduction URL

https://codesandbox.io/s/boring-perlman-p3hkn9?file=/src/pages/Index.vue

### How to reproduce?

go to codesandbox link and select any grid item. it will add .q-table__grid-item--selected class without any space. 

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

**Comment by MilosPaunovic** [comment]
Duplicate [https://github.com/quasarframework/quasar/issues/13021](https://github.com/quasarframework/quasar/issues/13021).

Fix will be available in Quasar v2.6.6
