### ISSUE TITLE
QCheckbox with icon placed in QBtn

### ISSUE THREAD

**Issue by KINGER404** [quasarframework/quasar#13063]
### What happened?

The icon in the Qcheckbox that is placed in the QBtn becomes very large

### What did you expect to happen?

Standard icon size

### Reproduction URL

https://codepen.io/kinger404/pen/oNppJyJ?editors=101

### How to reproduce?

Just open link

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Additional context

Now for the size of the icon in the button uses this class:

`.q-btn .q-icon, .q-btn .q-spinner {
  font-size: 1.618em;
}`

Possible solution is to add this:

`.q-btn .q-checkbox .q-icon {
  font-size: 0.5em;
}`

But I'm not sure if it's correct...

**Comment by KINGER404** [comment]
The same problem for the QRadio, the solution is the same as for the QCheckbox

**Comment by rstoenescu** [comment]
QCheckbox/QRadio in QBtn makes no sense. Use them separately.
Or if you actually want a button, then make the icon dynamic (`:icon="condition ? 'this_icon' : 'that_icon'`)
