### ISSUE TITLE
Editing a QInput with a mask forces the cursor to move to the end

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#13095]
### What happened?

When editing a QInput that has `mask` prop set, entering valid input forces the cursor to move to the end, making it really hard to edit inputs.

### What did you expect to happen?

It should not force move the cursor to the end, but move the cursor one by one as it does in v1 and v2.5.5.

### Reproduction URL

https://codepen.io/yusufkandemir/pen/MWrQxqN

### How to reproduce?

1. Go to the provided reproduction link
2. Click on the first QInput.
3. Move the cursor to the start or somewhere in the middle.
4. Type some numbers.
5. See that it moves the cursor to the end.
6. Move the cursor to the start or somewhere in the middle.
7. Type some letters.
8. See that it doesn't mutate the input and moves the cursor to the side by one character.

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Microsoft Edge

### Additional context

✅ v2.5.5: https://codepen.io/yusufkandemir/pen/BaJYEjM
✅ v1.18.9: https://codepen.io/yusufkandemir/pen/OJzQGRd

❌ v2.6.0: https://codepen.io/yusufkandemir/pen/MWrQxqN

**Comment by hooman-mirghasemi** [comment]
same problem for me 
and also problem is avalable on document  demo: https://quasar.dev/vue-components/input#mask

**Comment by obi84** [comment]
can confirm the problem and really need a fix.

**Comment by felipesdias** [comment]
[The bug was introduced in this PR](https://github.com/quasarframework/quasar/pull/12724/files)

updateMaskValue is reponsable for updating cursor position. At the moment I can't solve the problem, but in 2 or 3 weeks I can

**Comment by therealcoder1337** [comment]
could this please be prioritized a bit? it even affects the examples in the docs and seems like a non-trivial issue by now, as user input is really aggravated by this. thank you. <3

**Comment by yusufkandemir** [comment]
This issue got fixed in https://github.com/quasarframework/quasar/releases/tag/quasar-v2.7.0

**Comment by mityaua** [comment]
Can this be considered a bug if we add the autofocus attribute? [codepen](https://codepen.io/mityaua/pen/zYjQQNE?editors=1010)
