### ISSUE TITLE
Variables inside quasar.{theme.}styl to persist in app.variables.stylus 

### ISSUE THREAD

**Issue by dobromir-hristov** [quasarframework/quasar#131]
If for example you decide to stick to global paddings or extend a button you cant import the main stylus and use the variables there because it will duplicate the whole code. 

The guys over at Foundation have a _settings.scss which has about 90% of the variables defined and commented out. If you need something, you import that file and use everything you want.

Just think it could make things a bit easier.

**Comment by rstoenescu** [comment]
There's a bit of comment to do here, but you are right. This can be improved. And it will.

**Comment by dobromir-hristov** [comment]
Yeah, I know its not just "copy this there" but I think it will be really helpful, today I needed this like 10 times and decided to mention it.

**Comment by rstoenescu** [comment]
Thanks for opening this! Please do open issues where you think things can be improved.

**Comment by rstoenescu** [comment]
Why closing?

**Comment by dobromir-hristov** [comment]
Mistake. Thought it was something else...

**Comment by rstoenescu** [comment]
Just realized this is a duplicate of #106
