### ISSUE TITLE
not possible to trigger the q-uploader __pick method

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#1311]
Thanks for the great q-uploader! Currently I have:

1. a button, which when clicked shows
2. the q-uploader with the add button, which when clicked shows
3. the file selector

I would prefer to have:
1. a button, which when clicked
2. shows the q-uploader with the add button, **and instantly opens the** 
3. the file selector

Looking at the [src](https://github.com/quasarframework/quasar/blob/549111ec87f9bb99c3497982455a5f9a6ae57891/src/components/uploader/QUploader.vue#L339) code it looks like I need to trigger the __pick method somehow. I tried selecting this button:
```
<q-icon
        v-if="!uploading"
        slot="after"
        :name="$q.icon.uploader.add"
        class="q-uploader-pick-button q-if-control relative-position overflow-hidden"
        @click="__pick"
        :disabled="addDisabled"
      >
```

and then clicking it..., but I do not succeed somehow. Is this possible? How to do it? Maybe this should be part of the API?

**Comment by musicformellons** [comment]
Ah! Got it working with:
`this.$el.querySelector('input, q-uploader-input').click()`

Maybe still a good idea to have it in the API as in my opinion clicking the add button is kind of redundant.

**Comment by rstoenescu** [comment]
Hi,

Methods that begin with "__" are private and should not be used in App.
Added "pick()" method in future v0.15.
