### ISSUE TITLE
I found an error when I used pinia state management to request the network in the Prefetch hook  

### ISSUE THREAD

**Issue by gh81997167** [quasarframework/quasar#13126]
### What happened?

1.Directly accessed by the browser, the network request will be pre-executed in the Prefetch hook, and the link record of the network request will not be found in the console
2.By clicking the route to jump to the specified page, the network request is not executed ahead of time in the Prefetch hook, and the link record of the network request is displayed in the console 

### What did you expect to happen?

Browser direct access and route jumps can both prefetch data in prefech hooks rather than display API requested links in the console  

### Reproduction URL

http://localhost:9100/good/jznw02

### How to reproduce?

![image](https://user-images.githubusercontent.com/10526983/162418651-c7ee5be9-4680-4976-86b7-eae1dc3b840e.png)
![无111标题](https://user-images.githubusercontent.com/10526983/162419288-e20cdb93-195e-4ab0-a7f0-8e8d5e05af84.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
You didn't provide a reproduction(_we can't magically access your local project_), not even a code snippet. So, we can't understand the problem. If you provide a clear reproduction, we can reopen the issue and take a look at it.
