### ISSUE TITLE
Remove margin left thumbnail not working

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#13128]
### Description

If you check [this example](https://quasar.dev/vue-components/list-and-list-items#qitemsection) of using thumbnail images you can see that the image is shifted even if inside the template you were trying to remove that effect by assigning "q-ml-none".
Probably a specificiy problem.
You may consider to remove that class from the example or lower the specificity of the negative margin's class.

### Documentation Section URL

https://quasar.dev/vue-components/list-and-list-items#qitemsection

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), Style & Identity (quasar)

**Comment by pdanpdan** [comment]
What example are you talking about? There is no `q-ml-none` in the examples.
If you have a specific case make a codepen to see what you are doing.

**Comment by bartduisters** [comment]
@pdanpdan 
I think he meant 'even if you try to add `q-ml-none`, the image is shifted to the left.

But the image is not shifted to the left, it's just styled as a `thumbnail`.

The bottom one is 'shifted to the left'.
<img width="655" alt="Screenshot 2022-05-06 at 01 53 23" src="https://user-images.githubusercontent.com/43420049/167045128-15beb5c3-e527-4a2c-8e45-c3294d558690.png">


Here I applied the `thumbnail` attribute to both the last and second to last item.
<img width="669" alt="Screenshot 2022-05-06 at 01 53 13" src="https://user-images.githubusercontent.com/43420049/167045122-865d6197-594d-444f-92f1-f8da46df57c8.png">

@vandelpavel 
Is my assumption correct? If so, this issue can probably be closed.

**Comment by vandelpavel** [comment]
I'm sorry. Just noticed that the link points to the wrong place.
Check here: https://quasar.dev/vue-components/list-and-list-items#qitemlabel

I was trying to remove that "shifted "effect and it wasn't working using that class. That clearly a specificity problem that could esily be solved.

If you can see in the updated link you are actually using that class and it's not working. 
So maybe you want to remove it also from that example?
Probably just a typo :)

**Comment by bartduisters** [comment]
Yeah, that class doesn't do anything. To remove the 'shift', the negative margin has to be overridden.

<img width="1112" alt="Screenshot 2022-05-06 at 16 29 04" src="https://user-images.githubusercontent.com/43420049/167153792-a8d77bdc-70e0-42e6-8adc-6b96b5aba769.png">

**Comment by successbyte** [comment]
Hi,

Please assign me to this issue so I can work on solving it.
I have been using Quasar for two years and would like to give back to the Quasar community.
This issue would be a great starting point for my contributions.

Thank you!

**Comment by bartduisters** [comment]
@successbyte 
You can just start a branch and open a PR linked to this issue - there is no separate assignment flow.

**Comment by rstoenescu** [comment]
Hi,

Thank you for the willingness to contribute. But this is by design, as per Material Design.

**Comment by successbyte** [comment]
Hi @rstoenescu and @bartduisters 
thanks for your kind words ok I will try to select and solve another issue
