### ISSUE TITLE
[Slider] Vertical: Keyboard edit (up/down keys) has very weird logic

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#13132]
### What happened?

The issue is that the default vertical slider is pointing down instead of pointing up. When using the arrow keys, pressing the up key increments the slider value (as expected) but the thumb is actually going down, which is weird. 

![image](https://user-images.githubusercontent.com/16233697/162529582-4f46664f-e87a-4bf3-b0d0-b165b632a34a.png)

My actual use case is that I want a vertical slider pointing up, so I'm using the `reversed` prop. When I press the up key I expect the thumb to go up and the value to increase. However, the exact opposite occurs (the value decreases and the thumb is going down).

Fixing this would be a breaking change I suppose, but the logic really seems wrong to me.

### What did you expect to happen?

Explained above.

### Reproduction URL

https://quasar.dev/vue-components/slider#vertical

### How to reproduce?

Just mess around with the vertical slider and the up/down right/left keys

### Flavour

UMD

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.8 & v1.20
