### ISSUE TITLE
[0.17] Quasar build command doesn't exit after running

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#13136]
### What happened?

I'm trying to deploy a quasar project to netlify, but it does this locally too. When I run `quasar build` it just finishes building and displays the tips messages, but doesn't exit the process. So the netlify deployment can't complete

<img width="1314" alt="Screen Shot 2022-04-10 at 8 36 51 pm" src="https://user-images.githubusercontent.com/13629190/162614278-df40c020-8dec-4f9f-923d-eebe40db3fb4.png">

### What did you expect to happen?

Command exits after successful build

### Reproduction URL

https://github.com/lopugit/planetexpress

### How to reproduce?

Download repo
`npm i`
`quasar build`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

### Platforms/Browsers

Chrome

### Quasar info output

```shell
lopu@mbp13:~/things/git/lopugit/planetexpress-frontend quasar info

Operating System                Darwin(20.5.0) - darwin/arm64
NodeJs                          16.14.2

Global packages          
  NPM                           8.5.0
  yarn                          1.22.18
  quasar-cli                    0.17.20
  vue-cli                       Not installed
  cordova                       Not installed

Important local packages 
  quasar-cli                    0.17.20 (Quasar Framework CLI)
  quasar-framework              0.17.17 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.8   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.46.0  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

Networking               
  Host                          mbp13.local
  en0                           192.168.1.130
```

### Additional context

This is quasar-cli v 0.17.20, sorry

**Comment by lopugit** [comment]
bump, sorry

**Comment by goldelehr** [comment]
Do you have any kind of workaround for automated pipelines? I'm just trying to build a SPA, but after displaying the success message the build tool never stops. 

@quasar/cli version is 1.3.2

**Comment by yusufkandemir** [comment]
We no longer support v0.x. So, I am closing this issue. Use v1(_support until the end of the year_) or newer(e.g. v2) to get support.

**Comment by yusufkandemir** [comment]
@goldelehr if you still experience the issue for Quasar v1 or v2, please open a separate issue with a reproduction. But, according to my experience, Quasar v1&v2, with Webpack and Vite, works fine on tools and services like Docker, GitHub actions, GitLab CI/CD, Azure DevOps, and AWS stuff. I didn't test every other tool available so I can't talk about the rest, but it should work fine in pretty much every environment.
