### ISSUE TITLE
QTable row value doesn't update after any change in the columns array

### ISSUE THREAD

**Issue by pratik227** [quasarframework/quasar#13148]
### What happened?

After updating the columns value field key the table body doesn't update the value accordingly. 

### What did you expect to happen?

It should update the body after anything changes in the column value

### Reproduction URL

https://codepen.io/Pratik__007/pen/popZKeo

### How to reproduce?

1. Got to the reproduction link and click on the Update Column Field button.
2. It's not updating values

Here is V1 codepen link as you can see it's working here - https://codepen.io/Pratik__007/pen/VwyBdPy

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Your columns variable is not reactive

**Comment by pratik227** [comment]
@pdanpdan  Is there any way we can achieve this ? I want this in the QGrid extension

**Comment by pdanpdan** [comment]
https://vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue

https://codepen.io/pdanpdan/pen/gOojjON?editors=1010

**Comment by pratik227** [comment]
Thanks I will check

**Comment by pratik227** [comment]
Thanks @pdanpdan  it works !!
