### ISSUE TITLE
QuasarPluginOptions iconSet and lang property types are incorrect

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#13151]
### What happened?

I'm using QuasarPluginOptions type for setting Quasar config object, but got this error:

Property 'set' is missing in type 'QuasarIconSet' but required in type 'GlobalQuasarIconSet'.ts(2741)

```ts
export const quasarConfig: Partial<QuasarPluginOptions> = {
  plugins: { Notify, LocalStorage },
  iconSet,
  config: {
    dark: true,
  },
};
```

Although the doc says that we can just have iconSet:
https://quasar.dev/options/quasar-icon-sets#quasar-vite-plugin-way

### What did you expect to happen?

No TS errors

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

Create a new Quasar v2 project with TS support

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

### Quasar info output

```Shell
Operating System        Darwin(21.3.0) - darwin/arm64
NodeJs                  16.13.0

Global packages    
  NPM                   8.1.0
  yarn                  1.22.17
  @quasar/cli           1.2.2
```

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.6.7
