### ISSUE TITLE
Project styles not inlined anymore in SSR

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#13169]
### What happened?

Quasar used to inline used styles and having `extractCss` to false
This was done by attaching into the header tag any style collected by `vue-style-loader`, which exposed it through `ssrContext.styles`

https://github.com/quasarframework/quasar/blob/e9103e550a9031f1df32325d05b32708d6ff03bc/utils/ssr-helpers/create-renderer.js#L106

At some point, probably with Vue3, something must have changed, as now `ssrContext.styles` appears to be always empty, no matter what.
This means that the initial html returned from a SSR bundle will cause a flash of unstyled content, as there won't be any style applied.

`extractCss` is set to true by default, and this allows to at least have app and vendor styles, but any devland custom CSS is ignored, causing a FOUC even when using default configuration.
When using `extractCss` to false, no CSS at all is loaded

This can be kind-of mitigated by forcing Quasar to bundle components, pages and layouts into the initial bundle instead of lazy loading them, eg. by avoiding dynamic `import`s into the routes file

### What did you expect to happen?

When using `extractCss` to false, I'd expect all styles to be inlined, as it was with Qv1/Vue2

### Reproduction URL

https://github.com/IlCallo/ssr-style-not-inlined

### How to reproduce?

1. clone repo
2. `yarn install`
3. `quasar build -m ssr`
4. `quasar serve dist/ssr/`
5. Open localhost:3000
6. Disable JS
7. Reload page

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SSR Mode

### Quasar info output

```Shell
Operating System - Linux(5.4.0-107-generic) - linux/x64
NodeJs - 14.19.1

Global packages
  NPM - 6.14.16
  yarn - 1.22.18
  @quasar/cli - 1.3.2
  @quasar/icongenie - 2.5.0
  cordova - Not installed

Important local packages
  quasar - 2.6.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.5.1 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.13.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.32 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - Not installed
  vuex - 4.0.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.17.9 -- Babel compiler core.
  webpack - 5.72.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.8.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Additional context

I can follow up with Vue team, if it's confirmed that the problem isn't in our build pipeline

**Comment by rstoenescu** [comment]
This is due to Vue exclusively and out of our reach for q/app-webpack. Discussed this issue with Evan and long story short his only recommendation is to extract css. So don't set extractCss to false.

**Comment by IlCallo** [comment]
Interesting, shall we mention this into the docs and deprecate the option? Does `extractCSS` serve any purpose at all at this point? 

---

Aside that, I continued testing and discovered that `extractCSS: true` didn't inline async components CSS for us due to a third party webpack loader (`vue-svg-inline-loader`), which for some reason broke CSS extraction and inlining when pushed as last loader for Vue files

I remembered we hit some similar problem in the past and found out [this](https://github.com/freddy38510/quasar-app-extension-ssg/issues/162#issuecomment-1024690508), which pointed us to the right culprit

This used to work correctly into Vue2, somehow it broke something silently into Vue3

**Comment by rstoenescu** [comment]
SSR is not everything. `extractCSS` makes sense for all other modes.
