### ISSUE TITLE
q-select does not render semantic HTML

### ISSUE THREAD

**Issue by nithinpeter** [quasarframework/quasar#1316]
The `q-select` does not render semantic HTML (`select` and `option` HTML tags), instead it renders `div` tags. This is causing the following problems for me:
1. Browser autocomplete not working as the `name` and `autocomplete` attributes has no effect.
2. Accessibility issues. Doesn't work properly  with screen readers.

I am happy to take a shot at fixing the issue, if someone can confirm the stuff I mentioned above are correct and I am not missing anything obvious. :)

**Comment by dennythecoder** [comment]
Looks like Bootstrap, Bulma, and Foundation land on using a styled select.  Vuetify seems close to what Quasar is doing.  Element is using a text box that drops down divs.  Doesn't look like Quasar would be able to maintain the same features if it goes with a select box.  Not sure about the accessibility, but autocomplete would be solved with an input box though, right?

**Comment by rstoenescu** [comment]
@dennythecoder is right. The canonical HTML syntax does not allow all the features currently embedded in QSelect, so we can't switch to it unfortunately.
In v1.0 there's going to be a lot of accessibility work done and it may alleviate your problem.
