### ISSUE TITLE
Upgrade Quasar without globally installed @quasar/cli

### ISSUE THREAD

**Issue by paya-cz** [quasarframework/quasar#13174]
### Description

[Quasar supports setting up a project without globally installed @quasar/cli](https://quasar.dev/start/quasar-cli#running-without-the-global-quasar-cli). The problem is how to upgrade such a project to the latest Quasar v2 version. I follow the [docs here](https://quasar.dev/start/upgrade-guide#older-v2-to-latest-v2) but I always get `Quasar App Extension "upgrade" is missing...` error even if I run `npx quasar upgrade` using external command prompt. I tried to install `@quasar/cli` locally using `npm install --save-dev @quasar/cli` and run the `npx quasar upgrade` again using external command prompt, yet the same error remains.

I think the [upgrade guide](https://quasar.dev/start/upgrade-guide#older-v2-to-latest-v2) should explain how to upgrade the project in cases when people don't have a global `@quasar/cli`

### Documentation Section URL

https://quasar.dev/start/upgrade-guide#older-v2-to-latest-v2

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

Use yarn/npm directly.

Also, it doesn't makes sense to add the upgrade command to the locally installed q/app-vite or q/app-webpack too because sometimes (extremely rare) we add little bonuses to the upgrade process. How would a previous version of q/app-* know what to do for a subsequent one in this case? :)

**Comment by lucho19jose** [comment]
to upgrade quasar vite what we have to do is: npm update --save
