### ISSUE TITLE
QTree (v0.15) - Better alignment for empty root node

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1317]
### Software version

Quasar: Futur 0.15
OS: Windows & Linux
Node: 8.9.3
NPM: 5.5.1
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

The last node `empty` (that contains no child) is not horizontally align with other root node.
![image](https://user-images.githubusercontent.com/7946730/34066573-b99d5fd6-e1de-11e7-8382-fe799bc327c7.png)

### What were you expecting?

![image](https://user-images.githubusercontent.com/7946730/34066582-d72b8d66-e1de-11e7-9848-6d477bbafa7d.png)

**Comment by rstoenescu** [comment]
Pushed fix. Thanks for suggestion.
