### ISSUE TITLE
QSelect selects/deselects multiple objects when field value is null

### ISSUE THREAD

**Issue by jclijmans** [quasarframework/quasar#13183]
### What happened?

I have a QSelect bound to an array of objects. Those objects have a property "value", some of these have this property not filled in.
When I select an item with value null, all items with value null are selected.
I presume quasar is using the value as comparison to determine the selected item. Is there a way to specify it's comparison field?

I've created a [jsFiddle](https://jsfiddle.net/yq0jhdmt/2/) for it, but here is the code and html
```ts
  setup () {
    ...
    const items = [
       {id: 1, name:"item1", value: "x"},
       {id: 2, name:"item2", value: "y"},
       {id: 3, name:"item3", value: null},
       {id: 4, name:"item4", value: null},
    ];
	
    const selectedItems = ref([]);  
    
    return {
      ...
      items,
      selectedItems
    }
  }
```

```html
  <div class="q-pa-md">
    <q-select :options="items" label="Select an item" option-label="name" v-model="selectedItems" multiple></q-select>
  </div>
  <div>
    <pre>Selected items : {{ selectedItems }}</pre>
  </div>

```

### What did you expect to happen?

Only the selected item should be selected.

### Reproduction URL

https://jsfiddle.net/yq0jhdmt/2/

### How to reproduce?

1. Go to the jsfiddel
2. select item1 and item3 from the q-select
3. select item4

Notice that now item3 is deselected instead of adding item4 to the selection

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

**Comment by metalsadman** [comment]
`:option-value="(item) => item === null ? null : item.name"`

**Comment by jclijmans** [comment]
Thanks for your solution.
I totally misunderstood the option-value property. I thought it was the value that would be put in the model once the item is selected

From the docs
-option-value :  Property of option which holds the 'value'; default 'value'

That seems odd to me, if you don't specify the option-value and the object does not have a value property, what property is used then? It works in that case

So I tried  option-value="id", and that worked out perfectly 

Anyway, thanks for the solution
