### ISSUE TITLE
[Suggestion] Allow the user to set non-flat buttons for Dialog component

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1318]
v0.14.7

As seen in these 2 lines: https://github.com/quasarframework/quasar/blob/d4125b907d50fccefa4732e03cbd8965daa7e899/src/components/dialog/QDialog.js#L197

buttons are gonna be always flat (even button stacks), so if I want to use non-flat buttons for Dialogs, I suggest this instead
```js
  props: {
    color: this.color,
    flat: this.flat === false ? false : true,
    label: this.cancelLabel,
    waitForRipple: true
  }
```

Now we can set buttons with `{label: 'Ok', flat: false, color: 'primary'}`.

Can provide a PR if suggestion's accepted.

EDIT: I'm not really sure that's the logic behind Dialog's btns rendering. But if someone can point me into the right file...

**Comment by rstoenescu** [comment]
That is code for v0.15. And it allows setting buttons through scoped slot, so you can fully customise them however you want. So closing this.

For v0.14, you have props to configure if button is flat, push, etc, so closing this.

**Comment by Frondor** [comment]
@rstoenescu Try setting `flat: false` in Dialog btns (v0.14.7), you'll notice it has no effect since that prop is hardcoded to be always flat.

**Comment by rstoenescu** [comment]
@Frondor just set one of the other types of buttons to "true". The button needs to be set with a type. Let me know if you have any problems with it. Also check [the demo](http://quasar-framework.org/quasar-play/android/index.html#/showcase/popups/dialog) with [its source](https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/popups/dialog.vue).
