### ISSUE TITLE
`quasar upgrade` not working with Yarn 3

### ISSUE THREAD

**Issue by maggie44** [quasarframework/quasar#13197]
### What happened?

I have updated yarn on my system globally to the latest stable (Yarn 3.2.0). Now when I run `quasar upgrade` I get the following error:

```
quasar upgrade   

  Quasar CLI · Gathering information with yarn...

/Users/user/.config/yarn/global/node_modules/@quasar/cli/bin/quasar-upgrade:106
  versions = versions.filter(version => regex.test(version))
                      ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at getLatestVersion (/Users/user/.config/yarn/global/node_modules/@quasar/cli/bin/quasar-upgrade:106:23)
    at upgradeQuasar (/Users/user/.config/yarn/global/node_modules/@quasar/cli/bin/quasar-upgrade:145:29)
    at Object.<anonymous> (/Users/user/.config/yarn/global/node_modules/@quasar/cli/bin/quasar-upgrade:254:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/.config/yarn/global/node_modules/@quasar/cli/bin/quasar:33:3)
```

It is a monorepo with Vite. When I run it on a normal Quasar Vite only project folder:

```
quasar upgrade   

  Quasar CLI · Gathering information with yarn...

 @quasar/extras: 1.13.5 → Skipping!
   (⚠️  NPM server returned an error, so we cannot detect latest version)
 quasar: 2.6.5 → Skipping!
   (⚠️  NPM server returned an error, so we cannot detect latest version)
 @quasar/app-vite: 1.0.0-beta.12 → Skipping!
   (⚠️  NPM server returned an error, so we cannot detect latest version)
  Congrats! All Quasar packages are up to date.
```

### What did you expect to happen?

Quasar to check for available updates. 

### Reproduction URL

N/A

### How to reproduce?

`yarn --version` <-- get your current Yarn version

Outside of a Quasar project run `yarn set version berry` to set the global yarn on your system to the latest

`quasar upgrade` in a Quasar project. 

`yarn set version x.x.x` where x.x.x. is the version fetched earlier to ensure there isn't any breaking of other projects. 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by MilosPaunovic** [comment]
Check this out; related:
https://github.com/quasarframework/quasar/discussions/12858#discussioncomment-2394766

**Comment by maggie44** [comment]
It's not an issue installing Quasar CLI, it is an issue using it. I should have also added, it is still using the node_modules structure, not the new fangled zero install stuff. Is the advice still to downgrade to Yarn 1, because Yarn are suggesting yarn 3 to be stable and recommended, even without the zero install? It would mean that we can't 'still use yarn for installing local dependencies' as mentioned in the post, or at least not via the CLI.

**Comment by MilosPaunovic** [comment]
As the docs state:

> Yarn v1 (strongly recommended) or NPM.

[https://quasar.dev/start/quasar-cli#tl-dr](https://quasar.dev/start/quasar-cli#tl-dr)

**Comment by hawkeye64** [comment]
Yarn > v1 is not supported.
