### ISSUE TITLE
QInput

### ISSUE THREAD

**Issue by zta7** [quasarframework/quasar#13196]
### What happened?

When using Qinput with autogrow attr and input mutiple lines then scrollbar appear.

### What did you expect to happen?

And class='no-scroll' to input element directly and no scrollbar.

### Reproduction URL

https://codepen.io/zta/pen/KKZrjaO?editors=101

### How to reproduce?

[](https://codepen.io/zta/pen/KKZrjaO?editors=101)

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
I can't reproduce it. 
[https://codepen.io/milospaunovic/pen/dyJQBVJ?editors=1010](https://codepen.io/milospaunovic/pen/dyJQBVJ?editors=1010)

Where does the scroll appear?

**Comment by zta7** [comment]
![image](https://user-images.githubusercontent.com/30122066/163716823-9bfef239-e015-4f7b-9994-77f8f8d7ae9c.png)
emmmm....

> I can't reproduce it. https://codepen.io/milospaunovic/pen/dyJQBVJ?editors=1010
> 
> Where does the scroll appear?

**Comment by MilosPaunovic** [comment]
![Screenshot 2022-04-17 at 15 44 58](https://user-images.githubusercontent.com/62475782/163717106-11b22f3c-1b62-4764-bcc4-b86e76001ab4.png)

It doesn't happen with me, on Chrome `Version 100.0.4896.88 (Official Build) (x86_64)`, `macOs BigSur 11.4`. Please provide platform and browser info, so it could be further investigated.

**Comment by zta7** [comment]
Same chrome version as yours. But both on win10 or win11 laptop has that problem.

**Comment by zta7** [comment]
idk how scrollbar appeared, but add 'no-scroll' class on input work for me.

**Comment by zta7** [comment]
And here's another problem with autogrow attr.Bcz it doesnt check window resize.
Should it fix in QInput component ?
![image](https://user-images.githubusercontent.com/30122066/163720546-bf73cfeb-697a-4f89-bbe7-30ef04f689f0.png)
![image](https://user-images.githubusercontent.com/30122066/163720555-f8889108-d014-45b8-abd2-6f31eb81c14d.png)

**Comment by MilosPaunovic** [comment]
I've just tried on Chrome `Version 100.0.4896.88 (Official Build) (64-bit)` on Win10 HP laptop, and it does seem alright. Could your try in Incognito mode and in another browser, to try to pinpoint the exact issue?

**Comment by zta7** [comment]
In Incognito mode on chrome 
Version 100.0.4896.127 (Official Build) (64-bit)  (i just upgrade)
win11 XiaoMi laptop

![image](https://user-images.githubusercontent.com/30122066/163727516-d99f1a07-94df-4079-a5bc-27961f14d80f.png)
And same problem the newest firefox.

Look at [https://usefulangle.com/post/41/javascript-textarea-autogrow-adjust-height-based-on-content](url)
It's works fine with 'overflow:hidden'
![image](https://user-images.githubusercontent.com/30122066/163729270-de61e1dc-4aa9-4f4e-a83f-36f7475b5c73.png)
but since i disabled it, the scrollbar show up.
![image](https://user-images.githubusercontent.com/30122066/163729295-fb2989e5-da54-486e-b9b2-97ad6ffa2ab5.png)

And [https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight](url)
![image](https://user-images.githubusercontent.com/30122066/163730118-b137301e-45fe-448a-9e7d-61215cc554e7.png)
This will make height less than the real height bcz it use round to calc, so it's reasonable set 'autoflow: hidden' to totally avoid scrollbar issue.

Actually i did some research, i found people use 
'input.style.height=1px
 input.style.height=input.scrollHeight ' 
always make scrollbar be hiddened.
But i cant figure out what make the scrollbar happend.

BTW, not the real bussiness. Qinput -> adjustHeight() trigger twice in each user input.
"version": "2.6.6",
![image](https://user-images.githubusercontent.com/30122066/163729778-09c441a7-9e95-4b4f-b219-63f615eae480.png)
![image](https://user-images.githubusercontent.com/30122066/163729797-b2be4b97-9d18-469c-85cc-a4044c11cd54.png)

**Comment by zta7** [comment]
Hey, bro. I found more common issue reproduce. Tested on win10 Chrome 100.0.1185.44
No 'Enter' pressed !

[https://codepen.io/milospaunovic/pen/dyJQBVJ?editors=1010](url)
The Begining it has one more line which should not exist.
![1650610629(1)](https://user-images.githubusercontent.com/30122066/164620771-9cbd30ab-ae7e-4389-98f4-87220c37cfc1.png)

After u type more words, textarea comes more weird.
![1650610656(1)](https://user-images.githubusercontent.com/30122066/164620898-01797de1-84f6-4987-a405-d35dae8804dc.png)

**Comment by hawkeye64** [comment]
I can't make it create a scrollbar, but I do see the extra line (or 2) at the bottom behavior.

**Comment by jhisworking** [comment]
Thank you guys for finding and fixing this one... do you know in which version it will be available?

**Comment by rstoenescu** [comment]
Fix will be available in v2.8.3
