### ISSUE TITLE
The label is overlapped with date control

### ISSUE THREAD

**Issue by fisher030712** [quasarframework/quasar#13193]
### What happened?

![image](https://user-images.githubusercontent.com/18588176/163698928-9316fbee-c6dc-4bf1-a82a-135bc529d387.png)

### What did you expect to happen?

remove chinese "年-月-日", it desn't help.

### Reproduction URL

no

### How to reproduce?

put a q-input with lable = "test" and type = "date"

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
11
```

### Relevant log output

```Shell
11
```

### Additional context

11

**Comment by zta7** [comment]
Use stack-label attr.
[https://codepen.io/zta/pen/yLpGoKX?editors=1010](url)
