### ISSUE TITLE
QInfiniteScroll fails to emit the load event under some conditions

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#13212]
### What happened?

When QInfiniteScroll  is used in a dialog, and the initial content of the QInfiniteScroll  is empty, and the page which the dialog is on is high and has a scroll bar, QInfiniteScroll fails to emit the first load event.

### What did you expect to happen?

QInfiniteScroll emits the first load event.

### Reproduction URL

https://codepen.io/bigradish/pen/YzYddgo

### How to reproduce?

1. Go to the codepen
2. click on the "infi scroll" button.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
~Does the reproduction need some special conditions for window size or browser/os?
Because I cannot reproduce it (chrome/wayland)~

Ignore - it just needs more scroll to reproduce

**Comment by pdanpdan** [comment]
Fix will be available in v2.6.7/V1.18.11

**Comment by bigradish** [comment]
Hi @pdanpdan ,

Though after the fix the first "load" event is emitted, later "load" events are not emitted. Please check this.
Thank you very much.

**Comment by pdanpdan** [comment]
I cannot reproduce it here: https://codepen.io/pdanpdan/pen/MWQOWJr?editors=1010

**Comment by bigradish** [comment]
Hi @pdanpdan ,

I'm very sorry. There is a oversight in my code. The fix works. Thank you very much again.

**Comment by bigradish** [comment]
Hi @pdanpdan ,

I noticed that QInfiniteScroll is implemented by polling in the main thread. This may influence the performance of the app.
I think using [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) will be much better, for the doc says:

> The Intersection Observer API lets code register a callback function that is executed whenever an element they wish to monitor enters or exits another element (or the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport)), or when the amount by which the two intersect changes by a requested amount. This way, sites no longer need to do anything on the main thread to watch for this kind of element intersection, and the browser is free to optimize the management of intersections as it sees fit.

And Intersection Observer API is very easy to be used. Please consider. Thank you very much.

**Comment by pdanpdan** [comment]
The function is called poll, but it is in fact triggered mainly by the scroll event (and some other changes in the props) :)

**Comment by bigradish** [comment]
HI @pdanpdan ,

I'm sorry for not reading the code carefully. The event-driven idea is good. Have a good day! :)

**Comment by bigradish** [comment]
HI @pdanpdan ,

I read the code again, and found when the user begins to scroll (the "scroll" event fires), QInfiniteScroll checks (polls) tightly if the load conditions are met. The checking happens in the main thread. I think this design is not ideal.
If Intersection Observer API is used, the checking task is assigned to the browser, and does not influence the running of the main thread.
Please consider. Thank you very much.

**Comment by pdanpdan** [comment]
Can you please put this in a separate issue? Thank you

**Comment by bigradish** [comment]
Hi @pdanpdan ,

I made the issue https://github.com/quasarframework/quasar/discussions/13673 . Thank you. :)
