### ISSUE TITLE
table scrollbar style different in different time 

### ISSUE THREAD

**Issue by jfy3d** [quasarframework/quasar#13214]
### What happened?

table scrollbar style different in different time     quasar 1.x
see two pictures
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/1300161/163980308-db0f18e0-f22c-463f-baf5-fbc49dd47352.png">
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/1300161/163980472-cca17d81-3b73-45ce-9366-28e65d863efe.png">

this  phenomenon  been a long time
It has only recently been found that it has something to do with time

### What did you expect to happen?

none

### Reproduction URL

http://none

### How to reproduce?

see  in different time like my two pictures

my timezone   china +8:00

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by MilosPaunovic** [comment]
I assure you it has nothing to do with system time.

Are you using same environment/browser/resolution for both cases?

**Comment by jfy3d** [comment]
yes 
 same environment/browser/resolution for both cases
my system  mac os
i had try  chrome  safari ,  same phenomenon

**Comment by MilosPaunovic** [comment]
I've just checked - scrollbar is hidden until you try to scroll table. That is expected behaviour.

**Comment by jfy3d** [comment]
I've just checked  scrollbar is  not auto hidden,  i  I also tried  windows chrome   not auto hidden

My colleague  mac os  chrome  is  not auto hidden

**Comment by MilosPaunovic** [comment]
https://user-images.githubusercontent.com/62475782/163987620-8f9e8697-5af2-4913-a33b-98ea71927c51.mov

**Comment by jfy3d** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/1300161/163998920-8a90ff31-759d-40e5-a8d1-40d49e4cb8d3.png">

now   when night   scrollbar can auto hidden
It's so confusing

**Comment by rstoenescu** [comment]
Hi,

This is browser + os behavior. Has nothing to do with Quasar. It's just a scrollable div.
