### ISSUE TITLE
vue3 keep-alive not working

### ISSUE THREAD

**Issue by liuhengloveyou** [quasarframework/quasar#13222]
### What happened?

I tried two ways:

```

<template>
  <!-- <router-view /> -->
  <router-view v-slot="{ Component }">
    <keep-alive>
      <component :is="Component" :key="$route.name" v-if="$route.meta.keepAlive"></component>
    </keep-alive>
    <component :is="Component" v-if="!$route.meta.keepAlive" :key="$route.name"></component>
  </router-view>
</template>

```

AND

```

<template>
  <!-- <router-view /> -->
  <router-view v-slot="{ Component }">
    <keep-alive include="xxx,bbb">
      <component :is="Component" :key="$route.name"></component>
    </keep-alive>
  </router-view>
</template>

```

keep alive not working, created/unmounted is always called.
What's wrong with it?

### What did you expect to happen?

The keepalive component should be cached and not refreshed

### Reproduction URL

Use keep-alive by document

### How to reproduce?

Use keep-alive by document

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
Dev mode.......... spa
 Pkg quasar........ v2.6.6
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 86.50% of global marketshare):
 · Chrome for Android >= 100
 · Firefox for Android >= 99
 · Android >= 100
 · Chrome >= 91
 · Edge >= 97
 · Firefox >= 90
 · iOS >= 12.2-12.5
 · Opera >= 79
 · Safari >= 13.1
```

**Comment by pdanpdan** [comment]
Sorry but what part of this has anything to do with quasar?
It's all pure vue

**Comment by liuhengloveyou** [comment]
I look at the documentation of vue and Vue route, it seems that some configuration needs to be changed? Does the quasar have any configuration or adaptation?

According to vue's documentation and Google's answer, this should work, but it just doesn't.

**Comment by rstoenescu** [comment]
Hi,

Don't think there's something that needs configured for this to work. However, all things that can be configured are [here](https://quasar.dev/quasar-cli-webpack/quasar-config-js#property-build).

Copy-pasting stuff from the "net" without understanding them is not really a good way to make progress. This ticket should at best be a post in our [forum](https://forum.quasar.dev) requesting help from the community.

But bottom line, this has nothing to do with Quasar but with Vue exclusively (if even). The right approach to report a Vue ticket is to their repo, not ours.

Thanks.

**Comment by cozumel424** [comment]
A lot of Quasar components are calling `onActivated`, `onDeactivated` and `onUnmounted` etc which throws errors when `keep-alive` is used in vue because those lifecycle hooks are no longer available, but Quasar doesn't check, so yes it's not a Vue issue, it's 100% a Quasar issue.

**Comment by pdanpdan** [comment]
@cozumel424 what???

**Comment by cozumel424** [comment]
You shot down the parent commenter but it's a Quasar issue. Look at the tabs component for an example ( /quasar/src/components/tabs/QTabs.js )

It calls the `onActivated` and `onDeactivated` vue lifecycle hooks. They **aren't available** when the `keep-alive` component is used in Vue, so Quasar just errors out. Just wrap any of your components in `keep-alive` and you'll see it yourself.

**Comment by pdanpdan** [comment]
@cozumel424  please make a codepen
