### ISSUE TITLE
Vite + i18n build production not work, only dev works

### ISSUE THREAD

**Issue by IgorFachini** [quasarframework/quasar#13229]
### What happened?

When use $t() by i18n, only production build, this happen.
With: "vue-i18n": "^9.2.0-beta.35"
![Captura de tela de 2022-04-21 17-23-10](https://user-images.githubusercontent.com/15202356/164557967-d5e24c24-9a51-43b4-8c3e-6a4381612542.png)

With: "vue-i18n": "^9.2.0"
![Captura de tela de 2022-04-20 23-37-53](https://user-images.githubusercontent.com/15202356/164559029-5f8ca080-c8d7-4c5e-894d-6da02cfa0546.png)

### What did you expect to happen?

![Captura de tela de 2022-04-21 17-23-21](https://user-images.githubusercontent.com/15202356/164557947-5c6e7ea2-47ed-40ad-af4d-20bad60e9de7.png)
Only work in dev mode.

### Reproduction URL

https://store-system-vue-stage.vercel.app/

### How to reproduce?

1. Acess https://store-system-vue-stage.vercel.app/
2. Login with: 
Email: [staging@staging.com](mailto:staging@staging.com)
Password: staging
3. Se problem in left menu 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode, PWA Mode

### Platforms/Browsers

Chrome

### Additional context

Repository with problem:
https://github.com/IgorFachini/store-system-vue/tree/staging

Actually version:
Version i18n:     "vue-i18n": "^9.2.0-beta.35"

**Comment by yusufkandemir** [comment]
You need to uncomment the related line since you are using Options API:
https://github.com/IgorFachini/store-system-vue/blob/294b897f617f1fff3e71becb0fcd17a896d4a0ad/quasar.config.js#L101-L102
```js
// if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
// compositionOnly: false,
```

See [the notice on `@intlify/vite-plugin-vue-i18n`](https://github.com/intlify/bundle-tools/blob/c7d58763e52bedd3c86d27742eb727153146ab63/packages/vite-plugin-vue-i18n/README.md#%EF%B8%8F-notice)

**Comment by IgorFachini** [comment]
> You need to uncomment the related line since you are using Options API: https://github.com/IgorFachini/store-system-vue/blob/294b897f617f1fff3e71becb0fcd17a896d4a0ad/quasar.config.js#L101-L102
> 
> ```js
> // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
> // compositionOnly: false,
> ```
> 
> See [the notice on `@intlify/vite-plugin-vue-i18n`](https://github.com/intlify/bundle-tools/blob/c7d58763e52bedd3c86d27742eb727153146ab63/packages/vite-plugin-vue-i18n/README.md#%EF%B8%8F-notice)

Thanks for the answer, I changed and committed, but not worked.

**Comment by jhx-zc** [comment]
I meet the error too. When run project as dev, it is ok. But if build and run with serve, i18n not work.
![image](https://user-images.githubusercontent.com/52167297/166100780-711defa0-c43f-44f7-9a7f-da59bb6aadca.png)

there is vite config:
![image](https://user-images.githubusercontent.com/52167297/166100808-e6f54e4d-bdd4-4324-87bf-1bfb265e1dc7.png)

**Comment by ArtemDehteruk** [comment]
Hello.
Add a "runtimeOnly: false" property for the @intlify/vite-plugin-vue-i18n options.

For example.
```
['@intlify/vite-plugin-vue-i18n', {
    // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
    // compositionOnly: false,
    runtimeOnly: false,

    // you need to set i18n resource including paths !
    include: path.resolve(__dirname, './src/i18n/**')
}]
```

**Comment by jhx-zc** [comment]
> Hello. Add a "runtimeOnly: false" property for the @intlify/vite-plugin-vue-i18n options.
> 
> For example.
> 
> ```
> ['@intlify/vite-plugin-vue-i18n', {
>     // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
>     // compositionOnly: false,
>     runtimeOnly: false,
> 
>     // you need to set i18n resource including paths !
>     include: path.resolve(__dirname, './src/i18n/**')
> }]
> ```

Thanks for the answer, it is work

**Comment by IgorFachini** [comment]
> runtimeOnly: false,

Nice, it's works thanks
