### ISSUE TITLE
Adding percentage next to the knob(circle graph) number ?

### ISSUE THREAD

**Issue by neorganic** [quasarframework/quasar#1322]
Is it possible to append a percent symbol **%** the the number value of this component  http://quasar-framework.org/components/knob.html ? 
![](https://i.imgur.com/erWpXmI.png)

**Comment by rstoenescu** [comment]
Use placeholder. Example from demo source:

```html
<!-- With custom placeholder -->
<q-knob
  v-model="model"
  :min="min"
  :max="max"
  :placeholder="'$ ' + model"
></q-knob>
```

In your case: `:placeholder="model + ' %'"`

**Comment by neorganic** [comment]
Great, thanks !

**Comment by neorganic** [comment]
@rstoenescu  Um, the documentation is wrong on this 
```
<!-- With custom placeholder -->
<q-knob
  v-model="model"
  :min="min"
  :max="max"
  :placeholder="'$ ' + model"
></q-knob>
```
Doesn't work. But this works:

```
<!-- With custom placeholder -->
<q-knob
  v-model="model"
  :min="min"
  :max="max"
>
  {{model}} %
</q-knob>
```
Find this out, by looking to your source code examples where you are also using   ` {{model}} %` approach .
 https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/forms/knob.vue

**Comment by rstoenescu** [comment]
Ah, sorry, gave out the v0.15 way :)

**Comment by raxor123** [comment]
The v0.15 still doesnt have the update

**Comment by wwwizzarrdry** [comment]
The v1.0 documentation still doesn't mention anything about a `placeholder` prop. Glad I found this thread.

**Comment by smolinari** [comment]
@wwwizzarrdry - That's because it's now done over the default slot with the `show-value` prop.

https://quasar.dev/vue-components/knob#Example--Show-value

Scott
