### ISSUE TITLE
class="my-sticky-virtscroll-table" Dark Mode

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#13230]
### What happened?

class="my-sticky-virtscroll-table"  do not work with dark mode

### What did you expect to happen?

to work

### Reproduction URL

https://suguffie.com/

### How to reproduce?

go to users page

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You realize that is an example in the docs and you are supposed to adjust the css as you need?

**Comment by modemb** [comment]
> You realize that is an example in the docs and you are supposed to adjust the css as you need?

Then why the dark mode is for then if I have to do it myself?
