### ISSUE TITLE
 injection "store" not found

### ISSUE THREAD

**Issue by d-kurchenko** [quasarframework/quasar#13249]
### What happened?

After I update my quasar-app version to quasar-webpack, my Vuex store become not work.

### What did you expect to happen?

To work with vuex store with new quasar-webpack version.

### Reproduction URL

https://codepen.io/pen?&editors=101
do not try to use it, i cant produce my problem in online editors

### How to reproduce?

`yarn create quasar`
choose vuex store
use hook "useStore"
`quasar dev`

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(5.16.0-kali5-amd64) - linux/x64
NodeJs - 17.7.1

Global packages
  NPM - 8.5.4
  yarn - 1.22.18
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.5.1 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.13.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.33 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - Not installed
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.17.9 -- Babel compiler core.
  webpack - 5.72.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.8.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - darij
  wlan0 - 192.168.0.105
```

**Comment by yusufkandemir** [comment]
Judging from `vuex - Not installed`, you probably didn't install Vuex(`yarn add vuex`). If it also happens to be the case when creating a new project, then you probably didn't press Space to select Vuex, but rather pressed Enter key to continue, which made it continue without selecting Vuex. Make sure it displays Vuex as selected after continuing.
![image](https://user-images.githubusercontent.com/6266078/164993944-658ffc03-4aaa-4254-9a4a-9d8082d2aa83.png)

**Comment by d-kurchenko** [comment]
> Judging from `vuex - Not installed`, you probably didn't install Vuex(`yarn add vuex`). If it also happens to be the case when creating a new project, then you probably didn't press Space to select Vuex, but rather pressed Enter key to continue, which made it continue without selecting Vuex. Make sure it displays Vuex as selected after continuing

But, vuex is installed in my package.json. And it works before i ran `quasar upgrade -i`. I also tried to make new project and select vuex, but useStore returns undefined, there is even no store object in app context. I think that it is a problem with quasar/app-webpack, because src/store/index.ts is not running in new clear project.

**Comment by yusufkandemir** [comment]
> I think that it is a problem with quasar/app-webpack, because src/store/index.ts is not running in new clear project.

Provide a repro so we can reproduce the issue. "Reproduction URL" is there for a reason, a GitHub repository also works, just saying "do this, create new project, etc." is not enough.

**Comment by d-kurchenko** [comment]
@yusufkandemir https://github.com/KurchenkoDarij/quasar-vuex-test

**Comment by yusufkandemir** [comment]
@KurchenkoDarij I cloned the repo, run `yarn` and `quasar dev`, it works fine:
![image](https://user-images.githubusercontent.com/6266078/164996129-65ea8be4-7623-4347-98cd-2e97c0cdb01a.png)

**Comment by d-kurchenko** [comment]
@yusufkandemir it is realy strange. I have just tried to reinstall quasar-cli but it not help.
![изображение](https://user-images.githubusercontent.com/93146235/165033716-7ec150e2-aeeb-499f-878c-c2560345d42f.png)

**Comment by yusufkandemir** [comment]
@KurchenkoDarij I just noticed you are using an odd-numbered Node version(`NodeJs - 17.7.1`). Don't do that, always use even-numbered Node versions, because they are the stable ones. Supported and stable Node versions for app-webpack: v12, v14, and v16; for app-vite: v14 and v16. The source of the problem is highly likely this.

**Comment by d-kurchenko** [comment]
@yusufkandemir Realy, it work! Thank You! But it works with 17+ node version before i upgrade my quasar project.

**Comment by exbotanical** [comment]
Yep, my team has run into this issue. Just ensure your devs are using a stable Node version e.g. 16.

**Comment by krushndayshmookh** [comment]
wow. switching to node 16 fixed the problem
