### ISSUE TITLE
v-ripple can't use in SFC with script-setup

### ISSUE THREAD

**Issue by Junvary** [quasarframework/quasar#13242]
### What happened?

v-ripple can't use in SFC with script-setup

### What did you expect to happen?

no bug

### Reproduction URL

https://codesandbox.io/s/kind-carlos-i11q56?file=/src/pages/Index.vue

### How to reproduce?

1. go to https://codesandbox.io/s/kind-carlos-i11q56?file=/src/pages/Index.vue
2. open chrome console
3. u will see: 
   TypeError: Cannot read properties of undefined (reading 'config')
    at updateModifiers (Ripple.js?714f:65:1

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Directives (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/13154
External issue. Bug in Vue.
Temporarily downgrade to vue 3.2.31

**Comment by baghdadraza** [comment]
temporarily fix

```vue
<script setup>

const $q = useQuasar()

defineExpose({ $q })

</script>
```
