### ISSUE TITLE
QUploader with websockets

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#1327]
I am trying to get QUploader (version 0.14.7) working uploading images to a featherjs 'service' on external server, basically following along [this example](https://github.com/feathersjs/docs/blob/master/guides/advanced/file-uploading.md).

How do I use QUploader with websockets?

**Comment by musicformellons** [comment]
I read somewhere that using http is more suitable for file uploading. Do not know whether that is good advice. Anyway I moved on and used uppy.io which is nice.

**Comment by donvie** [comment]
@musicformellons Have you fixed your problem? May i know your solutions to that?

**Comment by musicformellons** [comment]
@donvie I am using uppy.io and tus-node-server and it works fine. [This example](https://gist.github.com/pooot/a2f86e6847a8be51fb2e3672a00a905f) might help in building your own component.
