### ISSUE TITLE
Can't set the id attribute of the Q-Input?

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#13278]
### What happened?

1. Using the Q-Input component and set it's id attribute, for example: <q-input v-model="text" label="Standard" id="myinput"></q-input>)
2.  Display in chrome browser,  but the id value of the input element  is a different value, here, the value would be ''f_ec05557b-2def-4b09-84aa-d5ebb2694726'

### What did you expect to happen?

the id of the Q-Input should be set correctly when displayed in browser.

### Reproduction URL

https://codepen.io/zouzg7829/pen/LYewBpm?editors=101

### How to reproduce?

none

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
Check the docs, `for` prop

**Comment by zouzg7829** [comment]
> Check the docs, for prop

the prop doc of q-input component have nothing about id attribute
why can't set the expected id value of the q-input component?

**Comment by MilosPaunovic** [comment]
Every component page has the API section at the very top.
Every API section has a great little search functionality.

When you type `id` in the search field of the `QInput`s API section, you'll get a couple of results, one of which is the `for` prop, which says: `Used to specify the 'id' of the control and also the 'for' attribute of the label that wraps it; If no 'name' prop is specified, then it is used for this attribute as well`

**Comment by zouzg7829** [comment]
> Every component page has the API section at the very top. Every API section has a great little search functionality.
> 
> When you type `id` in the search field of the `QInput`s API section, you'll get a couple of results, one of which is the `for` prop, which says: `Used to specify the 'id' of the control and also the 'for' attribute of the label that wraps it; If no 'name' prop is specified, then it is used for this attribute as well`

Thank you very much!
I didn't pay attention to the 'for' description in the doc of the QInput' API before.
