### ISSUE TITLE
colors-1.4.2.tgz  Not Found

### ISSUE THREAD

**Issue by leafiy** [quasarframework/quasar#13285]
### What happened?

<img width="999" alt="image" src="https://user-images.githubusercontent.com/870449/165774162-0ad11af6-f9b7-4e97-a100-4d9b0c0b4e3f.png">
<img width="355" alt="image" src="https://user-images.githubusercontent.com/870449/165774255-3064f3aa-357e-4519-98c7-5c5bb28e7e71.png">

### What did you expect to happen?

quasar installed

### Reproduction URL

no

### How to reproduce?

yarn global add @quasar/cli

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by MilosPaunovic** [comment]
Run `yarn global upgrade @quasar/cli@latest`.
