### ISSUE TITLE
qimg :src"https://image.png" doesn't work

### ISSUE THREAD

**Issue by AndrianD** [quasarframework/quasar#13283]
### What happened?

I am currently using quasar2 with vue3 and here is the scenario:
Why when I put `<img src="https://images.png" /> ` does it display an image 
and when I put `<q-img src="https://images.png" />` the image does not s not display?

Does Qimg only process images locally?

thank you very much for your answer

### What did you expect to happen?

Qimg should display url image from external resource

### Reproduction URL

https://codesandbox.io/s/q-img-src-1r1evc

### How to reproduce?

1. Select a page
2. Make axios request
3. pass the result data url inside qimg src
4. Image don't display

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
I'm not sure what exactly is bothering you, but images from external resources are shown without issues.
[https://codepen.io/milospaunovic/pen/abEerVm?editors=1010](https://codepen.io/milospaunovic/pen/abEerVm?editors=1010)

**Comment by AndrianD** [comment]
Ok, here is a sandbox that describes the situation:
https://codesandbox.io/s/q-img-src-1r1evc

I make a component GridTemplate.vue that takes the `images` as props, the parent is in the pages/index.vue where i inject the images.
As you can see, no images is displayed but the component is loaded correctly.
Otherwise when you put `<img :src="">` it works, so what happening with q-img in this case ?

**Comment by AndrianD** [comment]
> I'm not sure what exactly is bothering you, but images from external resources are shown without issues. https://codepen.io/milospaunovic/pen/abEerVm?editors=1010

I update the link: https://codesandbox.io/s/q-img-src-1r1evc for the exampl

**Comment by MilosPaunovic** [comment]
The problem is that you are using wrong piece of data - when you fetch images, you get array of objects, and the property `download_url` of every image is the one you'll need to use and, you need to pass either height or width to your `QImg` component.

So, if you change it to:
```html
<q-img :src="image.download_url" width="200px"></q-img>
```

it will render just fine.

**Comment by AndrianD** [comment]
I don't know where you saw that it works, download_url is a download link, moreover it doesn't work, neither with images.url nor with images.download_url.
Did you have time to test the code?

![q-img_src_-_CodeSandbox](https://user-images.githubusercontent.com/6118385/166067148-ff30b79d-5c20-4759-9b44-246136c3d3f0.jpg)

**Comment by AndrianD** [comment]
> you need to pass either height or width to your QImg component.

Ah okay, but suddenly we must always pass a `width` or a `height` to q-img so that it displays an image then? And how about responsive ?

**Comment by AndrianD** [comment]
Thank you very much for your answer!
