### ISSUE TITLE
Request usage example for preFetch in the <script setup lang=ts> block of a component

### ISSUE THREAD

**Issue by kastork** [quasarframework/quasar#13290]
### Description

When using the composition api with the `setup` attribute in the `<script>` tag of a single file component, it isn't clear from the documents how to declare the `preFetch` method.

All the examples seem to be for the options api.

```typescript

#...
<script setup lang=ts>

import {preFetch} from 'quasar/wrappers';

# then what?

#...
</script>
```

### Documentation Section URL

https://quasar.dev/quasar-cli-webpack/prefetch-feature#using-prefetch-to-initialize-pinia-or-vuex-store-s-

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

TypeScript Support, SPA Mode

**Comment by Evertvdw** [comment]
What I do currently is define the whole component as  regular composition component using defineComponent. As far as I know it does not work with setup. You could also have two script blocks in your component I believe, one with the preFetch and the other with script setup.

**Comment by TobyMosque** [comment]
> What I do currently is define the whole component as regular composition component using defineComponent. As far as I know it does not work with setup. You could also have two script blocks in your component I believe, one with the preFetch and the other with script setup.

I didn't expected that would work, but worked:
https://github.com/TobyMosque/quasar-element-plus/blob/master/src/pages/IndexPage.vue#L48

**Comment by metalsadman** [comment]
I don't know if this was added in the docs prior or later after this thread, but you can find an example of it here 
![Screen Shot 2022-05-10 at 8 43 33 AM](https://user-images.githubusercontent.com/31038838/167520651-685781de-819e-4ed7-bdba-b7e885369352.png)
https://quasar.dev/quasar-cli-vite/prefetch-feature#usage

**Comment by rstoenescu** [comment]
> I don't know if this was added in the docs prior or later after this thread, but you can find an example of it here 
> 
> ![Screen Shot 2022-05-10 at 8 43 33 AM](https://user-images.githubusercontent.com/31038838/167520651-685781de-819e-4ed7-bdba-b7e885369352.png)
> 
> https://quasar.dev/quasar-cli-vite/prefetch-feature#usage

It was there all along.

**Comment by D3-FC** [comment]
> > I don't know if this was added in the docs prior or later after this thread, but you can find an example of it here
> > ![Screen Shot 2022-05-10 at 8 43 33 AM](https://user-images.githubusercontent.com/31038838/167520651-685781de-819e-4ed7-bdba-b7e885369352.png)
> > https://quasar.dev/quasar-cli-vite/prefetch-feature#usage
> 
> It was there all along.

But in this case if you are using ts, then f.e. vue-ts will show `Duplicate identifier` error if you are importing same store in both sections

```TS
<script
  lang="ts"
  setup
>
    const { rows } = storeToRefs(useCustomerListPageStore())
</script>

<script lang="ts">
import { PreFetchOptions } from '@quasar/app-vite'
import { useCustomerListPage } from '../../stores/customer/useCustomerListPage'

export default {
  async preFetch ({ store }: PreFetchOptions<any>) {
    await useCustomerListPage(store).preFetch()
  }
}
</script>

```

Would be nice to have kind of `defineProps` analogue

f.e. `definePreFetch` or `onPreFetch`
