### ISSUE TITLE
"yarn dev" not working in "./ui/dev/" folder - App Extension

### ISSUE THREAD

**Issue by domlysi** [quasarframework/quasar#13324]
### What happened?

When creating a new app extension from "npm init quasar" with UI components, it is not possible to start up the dev server  as described in docs.

"""
When using the UI kit, you will have two npm packages; one for the App Extension and one for the UI module. For testing with the dev app, from the ui folder type yarn dev. Create pages in the dev folder for testing and they will automatically be injected into the test app. Also, check out the scripts section in the package.json to see what you have available. When you yarn build, a dist folder will be created and populated with various types of packages (common, esm, and umd).
"""

An error occurs saying 'Unknown command "dev"'.
Seems like no quasar instance can be detected.

### What did you expect to happen?

A running dev server for developing the app extensions.

### Reproduction URL

No codepen required

### How to reproduce?

1. npm init quasar 

With options 
- Choose Quasar UI kit 
- Quasar v2
- Vue component, Quasar App Extension
- no prompt, no install, no uninstall

2. cd into "<project>/ui/dev"
3. run "yarn dev"

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), App Extension API

### Quasar info output

```Shell
Operating System   	Linux(5.13.0-40-generic) - linux/x64
NodeJs             	16.15.0

Global packages    	
  NPM              	8.8.0
  yarn             	1.22.18
  @quasar/cli      	1.3.2
  @quasar/icongenie	Not installed
  cordova          	11.0.0
```

### Relevant log output

```Shell
yarn run v1.22.18
warning ../../../../../../package.json: No license field
$ quasar dev


 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

  Running @quasar/cli v1.3.2

  Example usage
    $ quasar <command> <options>

  Help for a command
    $ quasar <command> --help
    $ quasar <command> -h

  Options
    --version, -v Print Quasar CLI version

  Commands
    create    Create a project folder
    info      Display info about your machine
                   (and your App if in a project folder)
    upgrade   Check (and optionally) upgrade Quasar packages
                   from a Quasar project folder
    serve     Create an ad-hoc server on App's distributables
    help, -h  Displays this message

  --------------
  => IMPORTANT !
  => Trigger this inside of a Quasar project (and npm/yarn install) for more commands.
  --------------


 Error Unknown command "dev"

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MilosPaunovic** [comment]
`yarn run dev`

**Comment by domlysi** [comment]
My bad. Running `npm install` inside *.../ui/* solved this issue
