### ISSUE TITLE
QEditor Plaintext Example concats content on paste

### ISSUE THREAD

**Issue by Diesmo** [quasarframework/quasar#13326]
### Description

When marking the editor text of the plaintext example, the marked text will not be replaced and pasted text will get added to the end of the current text under certain conditions.

Reproduce steps:
1. Copy anything from anywhere, so you have something in your clipboard.
2. Go the the linked docs example (plaintext-example)
3. Mark the editor text content by mouse dragging (select via holding left mouse button)
4. Drag the cursor outside the editor component, while still holding the left mouse button.
5. Release left mouse button when anywhere outside of Editor component
6. Press Crtl+V

Outcome:
Marked text is still there and the pasted content is added at the end of current editor text

Expected Outcome:
Marked text should be replaced inline/at correct position with content of clipboard 

I'm unsure if this is a Docs Example code bug or if the bug is inside the QEditor component. Because the same code path is traversed when the paste goes wrong (released outside) or correct (released inside), I think it might be a component/underlying API bug behind the line:
`editorRef.value.runCmd('insertText', text)`

For now I labeled it as Docs Bug, feel free to correct it.

This bug might or might not be related to [#11355](https://github.com/quasarframework/quasar/issues/11355)

### Documentation Section URL

https://quasar.dev/vue-components/editor#plaintext-pasting

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.0 and v1.19
