### ISSUE TITLE
Qinput with mask does not udate model value as without

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#13372]
### What happened?

Found some similar issues but they weren't treating that exact problem.
I'm trying to use an input field do add a number. When the model is updated i need to get the new value throug a proxy function in order to never show the input field empty. So if the new value is '' or null it should display '0'.
Actually works with a qInput with no mask. 

### What did you expect to happen?

When i clear dthe dialog the value should be updated. Then if i keep clearing it should remain the same and not disappear.

### Reproduction URL

https://codesandbox.io/s/suspicious-river-1khrdc?file=/src/pages/Index.vue

### How to reproduce?

Try to digit something.
Delete it from the top input.
IT WORKS!
Re delete it!
NOW IT DOESN'T WORK

If you try the same with a qInput with no mask the actual model comes back when we lose the focus.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

Operating System        Linux(5.13.0-40-generic) - linux/x64
NodeJs                  12.22.1

Global packages    
  NPM                   6.14.12
  yarn                  1.22.17
  @quasar/cli           1.2.2
  @quasar/icongenie     Not installed
  cordova               Not installed

### Additional context

I think it's a problem between the actual inputValue and the model value

**Comment by pdanpdan** [comment]
Vue does not react to assigning the same value to a reactive value.

So you need to assign the original value and in a nexTick to assign "0" if it's needed (and not already changed)

https://codesandbox.io/s/jolly-mccarthy-dwxchw?file=/src/pages/Index.vue
