### ISSUE TITLE
Event bus not working (eiter

### ISSUE THREAD

**Issue by mkhanal** [quasarframework/quasar#1337]
### Software version

Quasar: 0.14.7
OS: OSX 10.13.1
Node: v8.4.0
NPM: 5.6.0
Browsers: chrome, firefox
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
    Events $emit and $on do not communicate with each other. Either $emit does not emit event or $on does not listen.

### What were you expecting?
    $emit to emit an event and $on to listen to it.

### What steps did you take, to get the error?

```javascript
   Events.$on('event1',
      () => console.log('local event testing fired event1'))
   Events.$emit('event1')
```

I don't see a console statement

**Comment by rstoenescu** [comment]
You are probably using Events outside of a Vue component. In this case, Events are registered/initialised after your app runs `Vue.use(Quasar, ...)`. Using Events before that point won't work. Have you considered using Vuex if your case does not meets this criteria?

**Comment by rstoenescu** [comment]
You can also create your own event bus (`const bus = new Vue()`). Events is a wrapper over Vue's event bus anyway.
