### ISSUE TITLE
Dialog plugin with <script setup>

### ISSUE THREAD

**Issue by syldman** [quasarframework/quasar#13380]
### What happened?

Looks like Dialog plugin doesn't load properly with <script setup> in Vue3. I'm getting both 'is not a function' for both $q.dialog() and Dialog.create()

PS: Loading plugin is working fine from the same component.

<App.vue:98 Uncaught (in promise) TypeError: Dialog.create is not a function
    at App.vue:98:18
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js:1726:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at Array.job (runtime-core.esm-bundler.js:1790:20)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:328:31)
    at flushJobs (runtime-core.esm-bundler.js:369:5)>

### What did you expect to happen?

Dialog to load

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

Try using Dialog plugin from within <script setup> Vue3

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
It's not specific or related to `<script setup>`. You need to "install" the plugin by adding it to the `quasar.config.js > framework > plugins` array.
https://quasar.dev/quasar-plugins/dialog#installation

**Comment by syldman** [comment]
It's installed


```
import { Quasar, Loading, Dialog } from 'quasar'
        app = createApp(App)
            .use(Quasar, quasarUserOptions, {
                plugins: {Loading, Dialog},
                config: {
                    loading: { /* look at QuasarConfOptions from the API card */ }
                }
            })
            .mount('#app')
    }
```

**Comment by yusufkandemir** [comment]
You didn't provide a repro, you can use a [CodeSandbox](https://codesandbox.quasar.dev/) or a GitHub repo.

**Comment by TobyMosque** [comment]
do u're using the composabl?
https://quasar.dev/vue-composables/use-quasar

```js
import { useQuasar } from 'quasar'

const $q = useQuasar()
$q.dialog({ ... })
```

**Comment by syldman** [comment]
Yep. I've just checked with $q.platform and got the expected value: `{"userAgent": "Mozilla/5.0 (iPhone; ...}`

yet calling 
```
<script setup>
import {useQuasar} from "quasar";
const $q = useQuasar()
const trueVar = ref(true)

  watchEffect(
      () => {
        if (trueVar) {
          console.log($q.platform)
          $q.dialog({
            title: 'Error Title',
            message: 'Error Message',
          })
        }
      }
  )
</script>
```

returns
```
App.vue:98 Uncaught (in promise) TypeError: $q.dialog is not a function
    at watchEffect.flush (App.vue:98:14)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js:1726:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at Array.job (runtime-core.esm-bundler.js:1790:20)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:356:32)
    at flushJobs (runtime-core.esm-bundler.js:401:9)
```

**Comment by syldman** [comment]
Also WebStorm correctly sees $q.dialog() as a function and I can drill down to the source code. 
So it seems like just a runtime error.

**Comment by syldman** [comment]
Looks like the issue was in quasarUserOptions file that I've been loading in ` .use(Quasar, quasarUserOptions, {`

Interestingly Loading plugin got loaded anyway, but Vue didn't see Notify and Dialog plugins.

**Comment by tuffkidd** [comment]
Same issue here,

`quasar.config.js`
```js
framework: {
  config: {
    notify: {}
  },
  plugins : ['Notify']
}
```

`TestPage.vue`
```js
<script setup>
import { useQuasar } from 'quasar'
const $q = useQuasar()
$q.notify('Awesome Quasar!')
</script>
```
This works first start `quasar dev -m ssr` but not work after.
Browser shows error below.
```
TypeError (500)
$q.notify is not a function
```
Did anyone solve this problem?

**Comment by syldman** [comment]
@tuffkidd check my previous comment. In my case the issue that I was loading quasarUserOptions and basically overwriting plugins. Thus the IDE worked fine, but it failed at runtime.

**Comment by tuffkidd** [comment]
@syldman Thanks but I'm not use quasarUserOptions. 
I found the problem.

At the first execution `quasar dev -m ssr`, the plugin files (eg. Dialog, Notify.. ) are loaded but after hmr, the plugin files are not loaded.

Chrome dev tool filter `plugin`
1. Dialog, Notify plugins are loaded after `quasar dev -m ssr`
![1](https://user-images.githubusercontent.com/2167254/187652727-c72131df-4938-4148-82d8-d22b4a47a12e.png)

2. Edit a 'vue' file and after HMR
![2](https://user-images.githubusercontent.com/2167254/187652942-f97d689b-7190-49dd-93a6-a900204a8d93.png)


`quasar info`
```sh
Operating System - Linux(5.4.0-122-generic) - linux/arm64
NodeJs - 16.17.0

Global packages
  NPM - 8.15.0
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.6 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.21 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.23.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - playground
  eth0 - 10.211.55.11
  eth1 - 192.168.56.56
  eth2 - 192.168.0.201
```

**Comment by syldman** [comment]
In that case it might be better to open a new issue. This one is closed, and you might not hear from devs.

**Comment by tuffkidd** [comment]
@syldman Yes, thank you.

**Comment by tuffkidd** [comment]
My problem is not a Quasar issue. It's My environments problem. I'm so sorry about that.

**Comment by xoewrl** [comment]
> Same issue here,
> 
> `quasar.config.js`
> 
> ```js
> framework: {
>   config: {
>     notify: {}
>   },
>   plugins : ['Notify']
> }
> ```
> 
> `TestPage.vue`
> 
> ```js
> <script setup>
> import { useQuasar } from 'quasar'
> const $q = useQuasar()
> $q.notify('Awesome Quasar!')
> </script>
> ```
> 
> This works first start `quasar dev -m ssr` but not work after. Browser shows error below.
> 
> ```
> TypeError (500)
> $q.notify is not a function
> ```
> 
> Did anyone solve this problem?

good for me
