### ISSUE TITLE
QLinearProgress :stripe prop not working with :query or :indeterminate

### ISSUE THREAD

**Issue by sullyD64** [quasarframework/quasar#13389]
### What happened?

The QLinearProgress [:stripe](https://quasar.dev/vue-components/linear-progress#example--stripe) prop doesn't render stripes when used in combination with :query or :indeterminate.

### What did you expect to happen?

The stripes render correctly even in :query or :indeterminate states.

### Reproduction URL

https://codepen.io/sullyD64/pen/oNELvMM

### How to reproduce?

See the codepen

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System        Linux(5.13.0-39-generic) - linux/x64
NodeJs                  14.15.0

Global packages    
  NPM                   8.1.0
  yarn                  1.22.17
  @quasar/cli           1.3.2
  @quasar/icongenie     2.5.1
  cordova               Not installed

Networking         
  Host                  P15
  wlo1                  192.168.1.244
  docker0               172.17.0.1
  tun0                  10.10.11.9
```

### Additional context

This is a screenshot from the codepen above:
![immagine](https://user-images.githubusercontent.com/26333714/167665809-8281e6b4-5492-4a5d-a943-04dee8743d3b.png)

**Comment by MilosPaunovic** [comment]
That's expected behaviour, as `indeterminate` and `query` states arent determinate.

![Screenshot 2022-05-10 at 17 42 47](https://user-images.githubusercontent.com/62475782/167668605-ab8c3053-0284-4e71-9687-228729851fda.png)
