### ISSUE TITLE
Keyboard arrows not scrolling inside QDialog

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#13394]
### What happened?

Keyboard arrow scrolling not working inside QDialog

### What did you expect to happen?

Keyboard arrow scrolling should work inside QDialog

### Reproduction URL

https://codepen.io/metalsadman/pen/qBxNPaX

### How to reproduce?
0. Go to provided codepen or this example of the docs 
https://quasar.dev/layout/layout#example--in-a-qdialog
1. Click Open Dialog Button
2. Click on content
3. Press keyboard up/down arrow to scroll
4. Doesn't scroll
5. Compare it to above example https://quasar.dev/layout/layout#example--containerized-qlayout

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
fix is available starting with Qv2.7.0 / Qv1.19.0
