### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by seme1** [quasarframework/quasar#134]
Please support Right To Left languages.

**Comment by rstoenescu** [comment]
Some teasers. It's still WIP (with lots of bugs) and I need help as I don't have enough time for it.

![screenshot from 2017-06-30 11 53 28](https://user-images.githubusercontent.com/4665641/27728716-a2f3b19a-5d8b-11e7-902c-474bce448d70.png)
![screenshot from 2017-06-30 11 53 16](https://user-images.githubusercontent.com/4665641/27728720-a305400e-5d8b-11e7-8746-a2e36a69ba99.png)
![screenshot from 2017-06-30 11 53 01](https://user-images.githubusercontent.com/4665641/27728718-a2f5e546-5d8b-11e7-8b19-119b496b0903.png)
![screenshot from 2017-06-30 11 52 10](https://user-images.githubusercontent.com/4665641/27728715-a2f22ece-5d8b-11e7-95dd-d9ff6e0636b2.png)
![screenshot from 2017-06-30 11 51 24](https://user-images.githubusercontent.com/4665641/27728719-a2f725f0-5d8b-11e7-9ec3-4062c55a191d.png)
![screenshot from 2017-06-30 11 50 58](https://user-images.githubusercontent.com/4665641/27728717-a2f55d92-5d8b-11e7-805c-f110a31405d6.png)
![screenshot from 2017-06-30 11 50 35](https://user-images.githubusercontent.com/4665641/27728721-a3106b50-5d8b-11e7-9063-9a2d6377d129.png)
![screenshot from 2017-06-30 11 50 18](https://user-images.githubusercontent.com/4665641/27728722-a3113a30-5d8b-11e7-9de1-a56dbb1fa2d6.png)
![screenshot from 2017-06-30 11 49 33](https://user-images.githubusercontent.com/4665641/27728725-a315ae12-5d8b-11e7-8fa0-fd3af26e1e8c.png)
![screenshot from 2017-06-30 11 49 07](https://user-images.githubusercontent.com/4665641/27728724-a3140256-5d8b-11e7-8d0c-72be0efad12e.png)
![screenshot from 2017-06-30 11 48 56](https://user-images.githubusercontent.com/4665641/27728723-a31362d8-5d8b-11e7-8780-eb6d66869e49.png)
![screenshot from 2017-06-30 11 48 37](https://user-images.githubusercontent.com/4665641/27728726-a32420dc-5d8b-11e7-83f9-bcc2e1063ca2.png)
![screenshot from 2017-06-30 11 47 38](https://user-images.githubusercontent.com/4665641/27728727-a32a6410-5d8b-11e7-84dc-9e42a96a6807.png)
![screenshot from 2017-06-30 11 47 10](https://user-images.githubusercontent.com/4665641/27728728-a32ed6da-5d8b-11e7-963b-36839d4a3185.png)

**Comment by rstoenescu** [comment]
Full production-ready support available in 0.15.5
