### ISSUE TITLE
Add support for Chrome's Manifest V3

### ISSUE THREAD

**Issue by niketpathak** [quasarframework/quasar#13407]
### What happened?

While trying out the BEX (Browser Extension) mode on Chrome, it shows an error regarding the manifest version (see attached screenshot) which is still based on V2 instead of V3. 
![image](https://user-images.githubusercontent.com/10226768/168096298-6920cd10-8a3a-449c-ae62-6a35d54c0d33.png)

### What did you expect to happen?

While building the Extension for Chrome via the [official docs](https://quasar.dev/quasar-cli-webpack/developing-browser-extensions/build-commands), I expect to have no errors.  

### Reproduction URL

https://github.com/no-url-since-unable-to-instantiate-bex-mode-on-codesandbox

### How to reproduce?

1. Follow official Docs to setup a new BEX
2. Build App and try the default App on Chrome

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

BEX Mode

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
https://github.com/quasarframework/quasar/issues/8822#issuecomment-1059947120

**Comment by rstoenescu** [comment]
Manifest v3 is available ONLY for Quasar CLI with Vite.
Cannot offer support for it for Quasar CLI with Webpack because this requires breaking changes to the structure of src-bex (Manifest v3 requires a fixed file structure which does not matches current one).
