### ISSUE TITLE
QScrollArea re-renders the template when scrolling.

### ISSUE THREAD

**Issue by yeyuqh** [quasarframework/quasar#13418]
### What happened?

The template is re rendered.

### What did you expect to happen?

The template will not be updated.

### Reproduction URL

https://codepen.io/yeyu_qh/pen/LYQRvRw?editors=101

### How to reproduce?

Move the mouse into the scroll area.

or

When scrolling.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari

**Comment by pdanpdan** [comment]
This is related to how Vue3 recomputes inline code.
You should use one of:
- not changing values
- components for content
- use v-memo

https://codepen.io/pdanpdan/pen/MWQbXMw?editors=1000
