### ISSUE TITLE
q-carousel.goToSlide(n) not working in their parent mounted() method.

### ISSUE THREAD

**Issue by diazemiliano** [quasarframework/quasar#1341]
Quasar: 14.7
OS: Windows 10
Node: 8.6.0
NPM: 5.4.2
Browsers: Chrome 63.0.3239.108 (Build oficial) (64 bits)

I'm using `q-carousel` in a custom component.
I've 3 slides and what I want it's set te second slide as the initial with `this.$refs.carousel.goToSlide('1')`. So in my parent component I've...
```
 <q-carousel ref="carousel">
...
 <q-carousel />
...

mounted () {
   this.$refs.carousel.goToSlide()
 }
```
But this doesn't work. If I use  `this.$refs.carousel.goToSlide('1')` on click from a button for example, this works.
Thanks.

**Comment by rstoenescu** [comment]
You need to allow time for Carousel slides to connect to QCarousel. So, use $nextTick() like this:

```html
mounted () {
  this.$nextTick(() => {
    this.$refs.carousel.goToSlide(..)
  })
}
```

In v0.15 you'll be able to use a model (defining current slide) for QCarousel so this won't be needed.
