### ISSUE TITLE
Quasar with Vite can't import type

### ISSUE THREAD

**Issue by RovshenTagangylyjov** [quasarframework/quasar#13413]
### What happened?

When I import a type i get the following error on Browser console:
```
SyntaxError: The requested module '/src/types/index.ts' does not provide an export named 'Product' (at ProductDetail.vue:15:1)
```

Everything OK in code editor, no warnings, no problems.

**NOTE It's dev environment only issue.** 

### What did you expect to happen?

.

### Reproduction URL

.

### How to reproduce?

types/index.ts
```
export interface BaseProduct {
  name: string;
  description: string;
  from_age: number | null;
  to_age: number | null;
  female: boolean;
  male: boolean;
  price: number | null;
  stock: number | null;
  categories: number[];
  is_active: boolean;
}

export interface Product extends BaseProduct {
  id: number;
  slug: string;
  from_age: number;
  to_age: number;
  price: number;
  stock: number;
  average_rating: number;
  rate_count: number;
  is_favorite: boolean;
  users_rating: Rating | null;
  total_sold: number;
  date_created: string;
  date_updated: string;
}

```

ProductDetail.vue
```
<script setup lang="ts">
import ProductDetailCarousel from 'components/ProductDetailCarousel.vue';
import TheRateProduct from 'components/TheRateProduct.vue';
import ButtonAddToCart from 'components/ButtonAddToCart.vue';
import ButtonAddToFavorites from 'components/ButtonAddToFavorites.vue';
import ProductQuantity from 'components/ProductQuantity.vue';
import DialogConfirmDelete from 'components/DialogConfirmDelete.vue';
import { ref } from 'vue';
import { useProduct, useUser } from 'src/stores';
import { Product } from 'src/types';
import { useRouter } from 'vue-router';
import { DollarToManat } from 'src/helpers/product';

const productStore = useProduct();
const user = useUser();
const router = useRouter();
const product = productStore.product as Product;
const quantity = ref<number>(1);
const showDeleteConfirm = ref(false);

const deleteProduct = async () => {
  await productStore.delete(product.id).then(() => router.go(-1));
};
</script>

```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), TypeScript Support, SPA Mode

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Shouldn't it be `import type { Product } from 'src/types';`?
What does this have to do with quasar or vite?

**Comment by yusufkandemir** [comment]
This is a Vue limitation as @pdanpdan stated, see https://github.com/vuejs/core/issues/5414#issuecomment-1037063829

A potential fix has been introduced in https://github.com/vuejs/core/commit/ccf92564d339cdee3947aecfba2e861c88864883 22 hours ago, which is not released yet. You can watch out for a new Vue release to see if it solves your problem. If it does not, you might consider making a comment on that issue or creating a new one in the Vue repo.

**Comment by RovshenTagangylyjov** [comment]
Thanks @pdanpdan and @yusufkandemir , I didn't know about `import type {...} from '...' `  thing. It used to work before. 
Used as you showed and know it's working. Thanks.
