### ISSUE TITLE
Time picker in RTL

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar#1344]
On latest version, in RTL mode, time picker is not working properly
When I click 10 it choose 50
It takes the opposite, just like mirror
I tried to fix the HTML/CSS but no success

I have 2 big projects that wait to release and I can't release them because of this
Fix this bug is very important

**Comment by MatanYed** [comment]
Example
https://www167.lunapic.com/do-not-link-here-use-hosting-instead/15143959078669?9630636080

**Comment by MatanYed** [comment]
i found the solution, the rtl css for .q-datetime-clock is completely wrong and should be deleted in the rtl.css file
the only thing is should have in rtl is 'direction: ltr'

**Comment by rstoenescu** [comment]
Will be available in 0.15.5
