### ISSUE TITLE
QChatMessage becomes abnormal when contains QMenu

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#13440]
### What happened?

When QChatMessage contains a QMenu, it does not show its text.

### What did you expect to happen?

QChatMessage shows its text.

### Reproduction URL

https://codepen.io/bigradish/pen/jOZyWza?editors=101

### How to reproduce?

1. Go to the codepen.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
If you are using the default slot them you must render the content there too

**Comment by bigradish** [comment]
@pdanpdan Then, QMenu can not be used in QChatMessage in the pattern in which it is used in other components, right?

**Comment by metalsadman** [comment]
@bigradish you can't yep
so you'll do something like this
```html
<q-chat-message sent>
  <p>hey, how are you? // {{orAPropHoldingYourText}}
    <q-menu touch-position context-menu>
       menu
    </q-menu>
  </p>        
</q-chat-message>
```
