### ISSUE TITLE
Using Vue api removed in Vue 3 (`app.config.devtools`)

### ISSUE THREAD

**Issue by zenflow** [quasarframework/quasar#13445]
### What happened?

I installed [`@vue/compat`](https://www.npmjs.com/package/@vue/compat?activeTab=readme) and got this warning from browser console: 

![image](https://user-images.githubusercontent.com/3198597/168618194-3ff06d77-8a29-4403-9939-f32d74e063eb.png)

which traced back to this bit of code in `@quasar/app-webpack` (used to generate `my-project/.quasar/app.js`):

https://github.com/quasarframework/quasar/blob/ae4005deab1e794d69fb78e2f7822c9d41bbbea9/app-webpack/templates/entry/app.js#L75-L77

### What did you expect to happen?

I expected not to get any Vue3 compatibility warnings or errors from Quasar itself, just from the app I am migrating.

### Reproduction URL

https://codesandbox.io/s/sweet-cdn-ie09e3?file=/quasar.conf.js

### How to reproduce?

1. Go to the provided reproduction link
2. Open the "Console" tab (next to "Terminal", below "Browser")
3. Notice the warning

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron

### Quasar info output

```Shell
$ /code/node_modules/.bin/quasar info

Operating System - Linux(5.10.102.1-microsoft-standard-WSL2) - linux/x64
NodeJs - 16.15.0

Global packages
  NPM - 8.5.5
  yarn - 1.22.18
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.5.1 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.13.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.33 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - Not installed
  vuex - 4.0.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.17.9 -- Babel compiler core.
  webpack - 5.72.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.8.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 6.5.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qmarkdown - 2.0.0-beta.7 -- Display inline markdown in your Quasar App

Networking
  Host - 621ae90361fb
  eth0 - 172.18.0.3
```

### Additional context

More info on the compatibility warning: https://www.npmjs.com/package/@vue/compat?activeTab=readme#:~:text=link-,CONFIG_DEVTOOLS,-%E2%A8%82

**Comment by yusufkandemir** [comment]
This should be fixed in #13479. Released in [`@quasar/app-vite-v1.0.1`](https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-vite-v1.0.1), the webpack version is not released yet.
