### ISSUE TITLE
QOptionGroup with objects as values for the options does not reflect the selected option in UI

### ISSUE THREAD

**Issue by suchwerk** [quasarframework/quasar#13457]
### What happened?

Using a default (radio-button) q-option-group with objects a as values for the options the modelValue is changed correctly on selection but the UI does not reflect the state.

### What did you expect to happen?

The radio button of the current selection should be filled (reflect the selection).

### Reproduction URL

https://codepen.io/suchwerk123/pen/WNMjNva?editors=101

### How to reproduce?

1. Make a selection
2. See that the model value changed
3. The radio button of the selected option still is not filled

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
Vue reactive values compare:
https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgc2hhbGxvd1JlZiwgdG9SYXcgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG9yaWcgPSB7IGE6IDEgfVxuY29uc3QgcmVmT3JpZzEgPSByZWYob3JpZylcbmNvbnN0IHJlZk9yaWcyID0gcmVmKG9yaWcpXG5jb25zdCBzaGFsbG93UmVmT3JpZyA9IHNoYWxsb3dSZWYob3JpZylcblxuY29uc29sZS5sb2coJ29yaWcgPT09IHJlZk9yaWcxLnZhbHVlJywgb3JpZyA9PT0gcmVmT3JpZzEudmFsdWUpXG5jb25zb2xlLmxvZygncmVmT3JpZzIudmFsdWUgPT09IHJlZk9yaWcxLnZhbHVlJywgcmVmT3JpZzIudmFsdWUgPT09IHJlZk9yaWcxLnZhbHVlKVxuY29uc29sZS5sb2coJ29yaWcgPT09IHRvUmF3KHJlZk9yaWcxLnZhbHVlKScsIG9yaWcgPT09IHRvUmF3KHJlZk9yaWcxLnZhbHVlKSlcbmNvbnNvbGUubG9nKCd0b1JhdyhvcmlnKSA9PT0gdG9SYXcocmVmT3JpZzEudmFsdWUpJywgdG9SYXcob3JpZykgPT09IHRvUmF3KHJlZk9yaWcxLnZhbHVlKSlcblxuY29uc29sZS5sb2coJ29yaWcgPT09IHNoYWxsb3dSZWZPcmlnLnZhbHVlJywgb3JpZyA9PT0gc2hhbGxvd1JlZk9yaWcudmFsdWUpXG5jb25zb2xlLmxvZygncmVmT3JpZzIudmFsdWUgPT09IHNoYWxsb3dSZWZPcmlnLnZhbHVlJywgcmVmT3JpZzIudmFsdWUgPT09IHNoYWxsb3dSZWZPcmlnLnZhbHVlKVxuY29uc29sZS5sb2coJ29yaWcgPT09IHRvUmF3KHNoYWxsb3dSZWZPcmlnLnZhbHVlKScsIG9yaWcgPT09IHRvUmF3KHNoYWxsb3dSZWZPcmlnLnZhbHVlKSlcbmNvbnNvbGUubG9nKCd0b1JhdyhvcmlnKSA9PT0gdG9SYXcoc2hhbGxvd1JlZk9yaWcudmFsdWUpJywgdG9SYXcob3JpZykgPT09IHRvUmF3KHNoYWxsb3dSZWZPcmlnLnZhbHVlKSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIENoZWNrIGNvbnNvbGVcbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMzQvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==

**Comment by tjunussov** [comment]
There is another bug, when v-model defined as object at initial time, options are not selected ( at least in UI now dot shown ) 
[here is codepen with reproduction of this issue using Quasar 2.9.0 version](https://codepen.io/tjunussov/pen/LYBqaYw)

**Comment by pdanpdan** [comment]
2 objects are not the same if they look alike

**Comment by tjunussov** [comment]
> 2 objects are not the same if they look alike
So it not possible set initial state of options ? maybe we should change doc about Warning! Dont use objects in v-model

**Comment by pdanpdan** [comment]
You can use objects, there is no problem.
But in JavaScript `{ a: 1 } !== { a: 1 }`
