### ISSUE TITLE
Flexbox row within column are not positioned correctly

### ISSUE THREAD

**Issue by schehlmj** [quasarframework/quasar#13460]
### What happened?

The elements in a page are not positioned correctly when using "column" positioning.

In a layout where:
```
<div class="column">
    <div class="col-shrink">
        <div class="row">
             <div class="col-4">col-4</div>
             <div class="col-8">col-8</div>
        </div>
    </div>
    <div class="col-grow">
         col-grow
    </div>
</div>
```

Then there is extra space at the bottom of the "col-shrink" div that is not margin or padding. 

The extra space goes away if the "col-4" and "col-8" columns are both changed to "col-6".  The extra space also goes away if the "col-4" is changed to "col-12" and the "col-8" div is removed.  The extra space also goes away when the "column" div has "no-wrap" added to it.  The extra space also goes away when various amounts of text are added into the columns.

### What did you expect to happen?

I don't expect this extra space. It requires extra steps to try to try and remove the extra space.

### Reproduction URL

https://codepen.io/schehlmj/pen/RwQVPZa

### How to reproduce?

1. Go to the reproduction link.
2. Resize your browser very wide and short and see a red bar above that shouldn't be there. 
3. Resize your browser very tall and thin and see a red bar above that shouldn't be there.
4. While red bar is showing, change to use no-wrap class
5. Turn off no-wrap, and then change inner layout to be "col-6 col-6" or "col-12", and see that the red bar goes away
6. Change back to "col-4 col-8" and use the sliders to add text to each of the columns.  At various lengths the red bar grows and shrinks.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You get a loop in the flexbox size calculations in browser.

Column by default uses an `align-items: stretch` which means the children are using the width of the parent.
But at the calculation start the width is smaller and what the browser gets for height is the height of the row as if it would have been narrower.

Anyway, the solution is to:
- either use `no-wrap` on the column flex parent
- or set a width on the shrinking child (I know it's funny: `full-width` class works without problem)

https://codepen.io/pdanpdan/pen/MWQmerg
