### ISSUE TITLE
QScrollArea content-style work wrong.

### ISSUE THREAD

**Issue by zta7** [quasarframework/quasar#13461]
### What happened?

context-style not change.

### What did you expect to happen?

...

### Reproduction URL

https://codepen.io/zta/pen/eYVWdYd?editors=1010

### How to reproduce?

mouseover and mouseout u will see the style changed.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
Yes, you only set the `content-style`
Set `content-active-style` also

**Comment by zta7** [comment]
Ok, but after that, the behavior still weird: first time dom loaded it's behavior is 'content-active-style', then after like one or two seconds it's behavior turn to 'content-style'. Is that right ?
https://codepen.io/zta/pen/eYVWdYd?editors=1010

**Comment by zta7** [comment]
I think content-style should not detect 'mouse is hovered or not' to remove/add that style.

**Comment by pdanpdan** [comment]
That is something to discuss. When content changes the scrollbars are auto activating and stay active for the duration of the delay. To discuss is if the initial render should be considered content change @rstoenescu

**Comment by zta7** [comment]
Ok, that's not a big problem, i also can apply style by myself to the slot's element. But i feel i cant use these two attrs, it's behavior is not good.
And in my view, 'content-style' should work as same as 'input-style'/'table-style', just put style/class on it.
