### ISSUE TITLE
[DialogPlugin]: cannot invoke custom async component

### ISSUE THREAD

**Issue by xuzuodong** [quasarframework/quasar#13463]
### What happened?

Seems that Dialog plugin does not support importing async component like this: 

``` ts
import { Dialog } from 'quasar'

Dialog.create({
    component: () => import('./dialog.vue'),
})
```

which causes: 

<img width="805" alt="WX20220519-111701@2x" src="https://user-images.githubusercontent.com/51878637/169196939-02618f2e-1def-4ba6-afcf-c62acc568329.png">

I found this related issue: #8288, but it's using quasar v1 and Options API. 

### What did you expect to happen?

The dialog with async component should open. 

### Reproduction URL

https://github.com/xuzuodong/quasar-dialog-plugin-async-comp/blob/master/src/App.vue

### How to reproduce?

- ` pnpm i`

- `pnpm dev`

- click buttons on the opened page, and then check console

![屏幕录制2022-05-19 11 09 18](https://user-images.githubusercontent.com/51878637/169196171-e7efa35f-7e21-4c78-ae5a-56c40a9c41ad.gif)

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System        Darwin(21.4.0) - darwin/arm64
NodeJs                  16.15.0

Global packages    
  NPM                   8.5.5
  yarn                  1.22.11
  @quasar/cli           1.2.0
  @quasar/icongenie     Not installed
  cordova               Not installed

Networking         
  Host                  xuzuodongdeMacBook-Air.local
  en0                   172.16.88.130
```

**Comment by MilosPaunovic** [comment]
[https://quasar.dev/quasar-plugins/dialog#invoking-custom-component](https://quasar.dev/quasar-plugins/dialog#invoking-custom-component)

**Comment by metalsadman** [comment]
@xuzuodong 
```js
async function asyncDialog() {
  Dialog.create({
    component: await defineAsyncComponent(() => import('./Dialog.vue')).__asyncLoader(),
  })
}
```

**Comment by yusufkandemir** [comment]
The correct way to define an async component is to use [`defineAsyncComponent`](https://vuejs.org/api/general.html#defineasynccomponent). See [Async Components | Vue.js](https://vuejs.org/guide/components/async.html) for more info. So, you would need to do this:

```js
Dialog.create({
  component: defineAsyncComponent(() => import('./Dialog.vue')),
})
```

However, async doesn't seem to be working well with `<script setup>`. The workaround is to use @metalsadman's suggestion.

**Comment by zhongjiaguo001** [comment]
> @xuzuodong
> 
> ```js
> async function asyncDialog() {
>   Dialog.create({
>     component: await defineAsyncComponent(() => import('./Dialog.vue')).__asyncLoader(),
>   })
> }
> ```
Hello, this is my first time using the Dialog plug-in to customize components. I use Vite as a packaging tool. How can I import my custom components asynchronously? Thank you for your time.

**Comment by xuzuodong** [comment]
> > @xuzuodong
> > ```js
> > async function asyncDialog() {
> >   Dialog.create({
> >     component: await defineAsyncComponent(() => import('./Dialog.vue')).__asyncLoader(),
> >   })
> > }
> > ```
> 
> Hello, this is my first time using the Dialog plug-in to customize components. I use Vite as a packaging tool. How can I import my custom components asynchronously? Thank you for your time.

@zhongjiaguo001 Now you can just do what @yusufkandemir said, as they have fixed this issue: 

``` js
Dialog.create({
  component: defineAsyncComponent(() => import('./Dialog.vue')),
})
```

**Comment by zhongjiaguo001** [comment]
> ```js
>   component: defineAsyncComponent(() => import('./Dialog.vue')),
> ```
Thank you for your valuable time. Now I can use it normally
