### ISSUE TITLE
[ios] Devices - <q-gallery Fullscreen Image toogle didnt work

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#1347]
Quasar 14.7 (and also 14.8) 

Devices : Apple Iphone and Ipad

Adding the   fullscreen  property to the <q-gallery  component  didnt work on the 
ios devices. Works fine on Chrome / Firefox.

Independent of the "mat"  / "ios"  theme 

Image did not get fullscreen, it only flickers short. Pressing the <q-btn flat @click="$refs.layout.toggleLeft()"> sometimes shows the fullscreen image ...

Strange.
any Idea ?

on my actual project this is a show-stopper :-/
Jochen Geiger

**Comment by rstoenescu** [comment]
Can you post your full vue templates? Need details to investigate. Thanks.

**Comment by ibrainventures** [comment]
its only a simple:
`  <q-gallery-carousel :src="gallery" horizontal-quick-view fullscreen></q-gallery-carousel>`

[Gallerytest.txt](https://github.com/quasarframework/quasar/files/1579561/Gallerytest.txt)

`<template>
  <q-layout ref="layout" view="hHr LpR lFf" :left-breakpoint="900" reveal>
    <q-toolbar slot="header" color="red">
      <q-btn flat @click="$refs.layout.toggleLeft()">
        <q-icon name="menu" />
      </q-btn>
      <q-toolbar-title>
        Titel
      </q-toolbar-title>
    </q-toolbar>

    
    <div slot="left">
      <q-list-header>Menue</q-list-header>
      <q-list no-border link inset-separator>
      </q-list>
    </div>

    <div class="layout-padding row justify-center">
      <div style="width: 500px; max-width: 90vw;">
        <p class="caption">Gallerie</p>
        <q-gallery-carousel :src="gallery" horizontal-quick-view fullscreen></q-gallery-carousel>
      </div>
    </div>

  </q-layout>
</template>

<style></style>

<script>
  import { GoBack, QLayout, QToolbar, QBtn, QIcon, QToolbarTitle, QList, QSideLink, QItemSide, QItemMain, QItem, QItemTile, QListHeader, QGallery, QGalleryCarousel } from 'quasar'

  export default{

    components: { QLayout, QToolbar, QBtn, QIcon, QToolbarTitle, QList, QSideLink, QItemSide, QItemMain, QItem, QItemTile, QListHeader, QGallery, QGalleryCarousel },

    data () {
      return {
        title: '',
        gallery: [
          'https://www.unilad.co.uk/wp-content/uploads/2016/06/trump-featured.jpg'
        ]
      }
    }
  }
</script>
</template>`

**Comment by rstoenescu** [comment]
The Carousel has been revamped in v0.15. Tested it right now again with v0.15 and your problem is no longer reproducible. Focusing on releasing v0.15 asap, so don't really have time to investigate at the moment.
Do you need a fix for v0.14 or can you wait a few days for v0.15? I'd rather spend time on v0.15 than investigating an already obsolete issue with latest version.

**Comment by rstoenescu** [comment]
Closing this as it's not a problem in v0.15. Let me know if this is a stop-ship for you on v0.14 or you can wait for v0.15.

**Comment by ibrainventures** [comment]
we tested it with 0.15 and it works fine .. we are still discussing about a workaround fullscreen modal ..
