### ISSUE TITLE
App-Vite + Pinia Production Error

### ISSUE THREAD

**Issue by folamy** [quasarframework/quasar#13480]
### What happened?

Everything works fine in Development but gets error from pinia:
```js
Uncaught TypeError: mc.version.split is not a function
    at index.ea2aaadc.js:6:10888
```
![Screenshot from 2022-05-20 08-04-18](https://user-images.githubusercontent.com/4560948/169528392-2015a4ac-8a45-42fb-8cc3-2c52c9034fed.png)

### What did you expect to happen?

Normal Behavior as in Development

### Reproduction URL

nill

### How to reproduce?

nil

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support, SSR Mode

### Platforms/Browsers

Firefox, Chrome

**Comment by MilosPaunovic** [comment]
Have you tried to manually install latest version of Pinia using `npm i pinia@latest`?

**Comment by folamy** [comment]
> Have you tried to manually install latest version of Pinia using `npm i pinia@latest`?

Yes, I did that and still the same problem persist! But everything works fine in Development.

**Comment by MilosPaunovic** [comment]
What differs between development and production? How do you build your app, how do you deploy it...?

**Comment by folamy** [comment]
> What differs between development and production? How do you build your app, how do you deploy it...?

quasar build -m ssr

**Comment by MilosPaunovic** [comment]
How do you deploy it? As much data you provide, the better support you could get from the community...

**Comment by folamy** [comment]
Well, I have not deployed yet.
I do:
cd dist/ssr
yarn start

**Comment by MilosPaunovic** [comment]
Okay, this is just working in the dark for anyone willing to help. Please provide a minimal code reproduction, share it with us and provide steps to reproduce, as well. That way, someone will be able to take a closer look and provide better support.
