### ISSUE TITLE
Dialog Plugin properly support async + <script setup>

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#13489]
### Current support matrix
|       | Options API | Composition API | <script setup> |
|-------|-------------|-----------------|----------------|
| Sync  |     ✔️     |       ✔️        |       ✔️      |
| Async |     ✔️     |       ✔️        |       ❌      |

See https://github.com/quasarframework/quasar/issues/13463#issuecomment-1133641238 for some findings.
See https://github.com/quasarframework/quasar/issues/13463#issuecomment-1132476252 for the workaround.

### Repro
https://stackblitz.com/edit/quasar-dialog-plugin-async-script-setup-issue?file=src%2Fpages%2FIndexPage.vue

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.7.1
