### ISSUE TITLE
QScrollArea container size incorrect

### ISSUE THREAD

**Issue by lajxw** [quasarframework/quasar#13497]
### What happened?

Chart Size beyond screen

### What did you expect to happen?

Don't go beyond the screen

### Reproduction URL

https://codesandbox.io/s/quirky-moore-i4sxnf?file=/src/pages/Index.vue

### How to reproduce?

1.go tu the Codesandbox
2.open browser in a new window
3.Press F12
4.Press F12

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Can you explain what is the problem?

**Comment by lajxw** [comment]
After changing the screen size, you can see the table size error. Once the qscrollarea is removed, the table size can be set correctly.
![QQ截图20220523233141](https://user-images.githubusercontent.com/46254113/169855439-056f504c-6208-4bdb-a9ef-be83080ae04f.png)
![QQ截图20220523233157](https://user-images.githubusercontent.com/46254113/169855460-14589b3e-8a66-4602-9aab-f036657728af.png)

**Comment by pdanpdan** [comment]
This is normal and expected - you are creating a scrolling element (and you define the size of the outside of that element) and then you put something inside without specifying any width for the content - so the content is rendered as it likes - in that case I suppose it has a default large width

**Comment by lajxw** [comment]
Thank you. I see
