### ISSUE TITLE
Typo in rtl document

### ISSUE THREAD

**Issue by alirezamastery** [quasarframework/quasar#13494]
### Description

there is a typo in requirement 3 in "How it Works" section in [rtl-support](https://quasar.dev/options/rtl-support#how-it-works):

`require('postcss-rtlcss', { source: 'rtl' })` should be: `require('postcss-rtlcss')({source: 'rtl'})`

### Documentation Section URL

https://quasar.dev/options/rtl-support#how-it-works

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by MilosPaunovic** [comment]
Pull requests are very welcome 🙂

**Comment by alirezamastery** [comment]
@MilosPaunovic I created a pr #13495 . thank you 👍🏻

**Comment by rstoenescu** [comment]
Thanks for PRing!
Will be available on next docs deployment.

**Comment by alirezamastery** [comment]
@rstoenescu thank you for this great framework!
