### ISSUE TITLE
Virtual List support

### ISSUE THREAD

**Issue by seme1** [quasarframework/quasar#135]
Please add support to Virtual Lists (or Collection-repeat)
http://ionicframework.com/docs/api/directive/collectionRepeat/
http://framework7.io/docs/virtual-list.html

**Comment by bloodf** [comment]
This can be a great increase on the platform, because we can better manage the memory on the painter.

**Comment by mamcx** [comment]
Any plan (or workaround) on this? I try to q-list into https://github.com/tangbc/vue-virtual-scroll-list/blob/master/examples/infinite/infinite.vue but the result is sub-optimal. 

Neither put q-infinite-scroll work.

**Comment by smolinari** [comment]
https://jsfiddle.net/smolinari/qc0Lex7o/

Scott

**Comment by mamcx** [comment]
Hi scott, the fiddle not work and when I try to put the solution on my code, neither. The spinner show and that is all.

**Comment by smolinari** [comment]
On JSFiddle, try putting the cursor in the JS code box and hitting Ctrl + Enter. Or hitting the "Run" button upper left corner. 

For some reason jsfiddle or rather the unpkg site isn't working right. 

Scott

**Comment by mamcx** [comment]
Ok, I retry in other browser and it work. However, still in my project (using the same browser) not. The refresher is not called.:

```
<template id="ListCustomersPage">
<q-layout>
  <q-layout-header>
    <toolbar :title="title" :label="$t('New')"></toolbar>
    <q-search clearable inverted :placeholder="$t('Type Name, Code, Nit, Phone Number or Email')" :float-label="$t('Search')" v-model="search" autofocus=true></q-search>
  </q-layout-header>

  <q-page-container> 
    <q-page>
      <q-infinite-scroll :handler="loadMore">

      <q-list highlight inset-separator>
        <q-item v-for="item in items" :key="item.customer_id">
          <q-item-side left>
            <q-btn @click.native="reportTotal(item.customer_code)" :color="colorDebt(item)" icon="attach_money">              
            </q-btn>
          </q-item-side>

          <q-item-main :label="item.name + ' - ' + item.customer_code" :sublabel="'Tel:' + item.phone1 + ' | ' + item.address + ' | ' + item.city"  @click.native="selectAction(item)"></q-item-main>
          <q-item-side right v-if="allowCustomer(item)" icon="chevron_right" color="primary"></q-item-side>
        </q-item>
      </q-list>

    <div class="row justify-center" style="margin-bottom: 50px;">
      <q-spinner-dots slot="message" :size="40" />
    </div>

      </q-infinite-scroll>
    </q-page> 
  </q-page-container>
</q-layout>
</template>
```

and

```
methods: {
    loadMore(index, done) {
      console.log(index, done);
}
...
...
```

**Comment by smolinari** [comment]
Don't you have to give the v-for some items? Are they being loaded and loaded past the bottom of the page?

Scott

**Comment by mamcx** [comment]
I request in an Ajax call 100 items. Scroll to to the bottom then see the spinner, but loadMore is not called.

**Comment by smolinari** [comment]
https://jsfiddle.net/smolinari/zdv97kbm/

Scott

**Comment by pdanpdan** [comment]
This will be added in the next release (v1.1.0)
