### ISSUE TITLE
Quasar CLI with Vite still documented as beta

### ISSUE THREAD

**Issue by straurob** [quasarframework/quasar#13513]
### Description

The documentation [Convert project to Quasar CLI with Vite](https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite) contains the following passage:

> WARNING
> Quasar CLI with Vite (@quasar/app-vite) is currently in BETA. Specifications may slightly change until the stable release.

From my understanding and https://github.com/quasarframework/quasar/discussions/11101, the Vite CLI has been released and is out of beta.

This information should be removed from the documentation.

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by straurob** [comment]
The upgrade guide [Migrate to v2 from v1](https://quasar.dev/start/upgrade-guide#migrate-to-v2-from-v1) also contains the beta status.

**Comment by rstoenescu** [comment]
Thanks for PRing!
