### ISSUE TITLE
when set publicPath ,query will be lost.   'http://localhost:8081/?a=1' => 'http://localhost:8081/#/'

### ISSUE THREAD

**Issue by 717009629** [quasarframework/quasar#13534]
### What happened?

I create new quasar project, then set publicPath='/'.
I visit 'http://localhost:8081/?a=1'  ,it will become 'http://localhost:8081/#/', the query is lost.

### What did you expect to happen?

when I visit 'http://localhost:8081/?a=1', the url become  'http://localhost:8081/?a=1#/' not  'http://localhost:8081/#/'

### Reproduction URL

yarn create quasar

### How to reproduce?

1 yarn create quasar
2 set publicPath:'/'
3 quasar dev
4 visit http://localhost:8080/a=1
5 url will become http://localhost:8080/#/

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Additional context

When I create a new vue project ,it work right.

**Comment by metalsadman** [comment]
https://quasar.dev/quasar-cli-webpack/quasar-config-js#property-build
![Screen Shot 2022-05-26 at 11 44 50 AM](https://user-images.githubusercontent.com/31038838/170411821-308a53fd-ac7b-4a9a-ae06-c7a660498089.png)
https://router.vuejs.org/guide/essentials/history-mode.html

**Comment by 717009629** [comment]
> https://quasar.dev/quasar-cli-webpack/quasar-config-js#property-build ![Screen Shot 2022-05-26 at 11 44 50 AM](https://user-images.githubusercontent.com/31038838/170411821-308a53fd-ac7b-4a9a-ae06-c7a660498089.png) https://router.vuejs.org/guide/essentials/history-mode.html

But when I create a vue project and use hash mode， the query will not be lost.

**Comment by MilosPaunovic** [comment]
Check out the docs for `VueRouter`.

**Comment by 717009629** [comment]
> 
when I create a vue project  or  I create a quasar project and don't set 'publicPath',  it works well( query not lost).

**Comment by 717009629** [comment]
> Check out the docs for `VueRouter`.

when I create a vue project or I create a quasar project and don't set 'publicPath', it works well( query not lost).

**Comment by 717009629** [comment]
> Check out the docs for `VueRouter`.



**quasar project** 
![1](https://user-images.githubusercontent.com/16289643/170425627-9f4f34af-28bc-49f1-872a-1e5fea12a3e0.gif)







**vue project** 
![2](https://user-images.githubusercontent.com/16289643/170425821-9bc678e0-2585-4318-85d6-44e261a7051f.gif)

**Comment by 717009629** [comment]
thank you ,I change router history , it works well
```
export default route(function (/* { store, ssrContext } */) {
  const createHistory = process.env.SERVER
    ? createMemoryHistory
    : (process.env.VUE_ROUTER_MODE === 'history' ? createWebHistory : createWebHashHistory)

  const Router = createRouter({
    scrollBehavior: () => ({ left: 0, top: 0 }),
    routes,

    // Leave this as is and make changes in quasar.conf.js instead!
    // quasar.conf.js -> build -> vueRouterMode
    // quasar.conf.js -> build -> publicPath
    // history: createHistory(process.env.MODE === 'ssr' ? void 0 : process.env.VUE_ROUTER_BASE)
    history: createHistory()
  })
  return Router
})

```
