### ISSUE TITLE
Unusable search, dead subdomains and broken links in docs.

### ISSUE THREAD

**Issue by goteguru** [quasarframework/quasar#13542]
### Description

Search is not working, multiple internal links are dead, subdomains are dead therefore some external links are broken.

Typing anything to the search box gives us an error message: 
```
It's not you, it's me.
Could not connect with our search service...
```

The following subdomains are dead: 

- https://awesome.quasar.dev/ 
- https://codepen.quasar.dev/
- https://jsfiddle.quasar.dev/
- https://codesandbox.quasar.dev/
- https://chat.quasar.dev/
- https://forum.quasar.dev/
- https://blog.quasar.dev/
- https://twitter.quasar.dev/
- https://facebook.quasar.dev/
- https://donate.quasar.dev/

Therefore all links pointing at them (eg. from the *tool* and *support* menus) are broken. Unfortunately many external sites and guides are linking the above urls.

v1 docs are also effected 

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Components (quasar), Plugins (quasar), Style & Identity (quasar), Electron Mode, Cordova Mode, Capacitor Mode

**Comment by MilosPaunovic** [comment]
I've just checked, it all works fine. Try different browser; might be a minor glitch in the infrastructure.

**Comment by goteguru** [comment]
> I've just checked, it all works fine. Try different browser; might be a minor glitch in the infrastructure.

Thank you for your answer, rechecking.

**Comment by goteguru** [comment]
Seems to be working indeed. Sorry for the false alarm!
