### ISSUE TITLE
[0.15] [enhacement] Basic Carousel - swipe not work on video slide

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#1354]
tested on ios devices ..

-> think this is a enhacemnet for 0.22 ;-)

**Comment by rstoenescu** [comment]
Hi,

This is not really solvable, since the video iframe itself captures the events and doesn't propagate them. So Quasar cannot intercept them. And it really shouldn't intercept them as the video scripts embedded might become unusable (they have their own controls which shouldn't stop working).
