### ISSUE TITLE
No clarity on how to create a client side component WITH a node_modules/.js file and use it in a page.

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [quasarframework/quasar#13552]
### Description

There is no proper documentation on integrating a JS file (for example [wordcloud](https://www.npmjs.com/package/wordcloud)) inside an SSR enabled project, inside a page or component.

Yes there's a QNoSsr component but this does not address the problem, ok so the Template doesn't load but how do you manage the Imports in the `<script setup>`?
Putting the import inside a component inside a `QNoSSR` still runs the import server-side, running the file, causing an error and the library is useless.

How do you dynamically import without creating an invalid template?

I'm using (!process.env.SERVER) as well around an attempt at a runtime client-side import but the import runs on the server anyway resulting in `document` undefined errors.
I expect such errors when it runs server side but what's the point of 'client side checks' if it just gets ignored and it all runs on the server...

The documentation needs a clear example of a small working integration of _any_ third party .js file (preferably inside a TS context) so that it's not complete guesswork to implement.

If you can suggest any alternative for the meanwhile or a specific documentation link you think I may have missed, I'd appreciate it greatly.

https://quasar.dev/quasar-cli-webpack/developing-ssr/ssr-frequently-asked-questions

### Documentation Section URL

https://quasar.dev/quasar-cli-webpack/developing-ssr

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), TypeScript Support, SSR Mode, PWA Mode

**Comment by pdanpdan** [comment]
You have all the details related to quasar here: https://quasar.dev/quasar-cli-vite/boot-files#usage-of-boot-files

For the rest please check the Vue docs, or the docs of what you are using
