### ISSUE TITLE
q-chip css issue

### ISSUE THREAD

**Issue by ftKnox** [quasarframework/quasar#1355]
### Software version

Quasar:0.14.7
OS: macOS
Node:
NPM:
Browsers:  tested in firefox quantum & safari 11.0.2
iOS:
Android:

there is a css issue when using both detail and square properties on a q-chip
<img width="150" alt="screen shot 2017-12-22 at 3 42 07 pm" src="https://user-images.githubusercontent.com/11303823/34314262-f8ff795c-e72e-11e7-9b6f-1a85609a9411.png">

**Comment by rstoenescu** [comment]
Hi, Thanks for reporting. Fixed in future v0.15.
