### ISSUE TITLE
Icongenie won't find .png file with a relative path

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#13560]
### What happened?

Icongen failed to read a relative path (it used to), but now only works with an absolute path
I'm using Bash for Windows (installed with Git for Windows) 

### What did you expect to happen?

Should read a relative path.

### Reproduction URL

can't run in codepen

### How to reproduce?

    $ node -v
    v14.19.0
 
    $ npm install -g @quasar/icongenie   ## Install the latest
    $ icongenie --version
    2.5.2
    
    $ ls app-icon.png   ## Confirm PNG File exists
    app-icon.png

    $ icongenie g --icon app-icon.png   
    * ⚠️  Path to source icon file does not exists: "app-icon.png"   ## Huh What?
    
    $ icongenie g --icon `pwd`/app-icon.png     ## Works!
    
    

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Icon Genie CLI (@quasar/icongenie)

### Platforms/Browsers

Other

**Comment by pdanpdan** [comment]
The relative path must be from the root folder of your project
Or much better run icongenie from that folder

**Comment by tohagan** [comment]
I'm running this from the `src` folder.

**Comment by pdanpdan** [comment]
the root folder of the project is the one that has src in it

**Comment by rstoenescu** [comment]
The `icon` param is designed as absolute path or relative path (to project root).
However, enhanced it to work as relative path (to current dir) also. Affected commands: generate and profile. The profile command will now parse the icon path and write the profile file with a value relative path (to project root) regardless of the parameter sent (if it's not an absolute path already).

**Comment by rstoenescu** [comment]
Will be available in Icongenie 2.5.3
