### ISSUE TITLE
QDialog keeps focus inside the dialog (focus stealing)

### ISSUE THREAD

**Issue by mspiderv** [quasarframework/quasar#13595]
### What happened?

**This problem is NOT related to TinyMCE, I just use it as an example!**

I have an [TinyMCE WYSIWYG editor](https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/) inside a QDialog. 

```
<q-dialog :model-value="true">
   <tinymce-component />
</q-dialog>
```

This is how it looks like. TinyMCE inside an opened QDialog (You can see the gray QDialog's backdrop area in the background):

![1](https://user-images.githubusercontent.com/2259835/171639688-f2ecabed-40b3-4eb6-8ea7-0d2eb495a938.png)

Many wysiwyg editors uses their own "dialogs". (For example [CKEditor](https://ckeditor.com/) does this as well).

For example, when I try to add a link inside the wysiwyg editor, a new dialog shows
![2](https://user-images.githubusercontent.com/2259835/171640179-d502f50c-252b-4e62-bc7d-f8714c658c19.png)
![3](https://user-images.githubusercontent.com/2259835/171640299-89e86c6f-3dc6-46b5-bc57-d17b2351a03b.png)

These dialogs are implemented as a `<div>` directly under `<body>` so they **are not** a child element of QDialog as you can see in the next image:

![5](https://user-images.githubusercontent.com/2259835/171640404-32d21ced-d179-4828-a121-7e90dd10770e.png)

**Problem:** QDialog is implemented in such a way that it keeps focus **inside** the QDialog and therefore Im not able to focus anywhere outside the QDialog.

In my scenario, I cannot focus the highlighted `<input>` because QDialog always keep focus inside the QDialog.

![4](https://user-images.githubusercontent.com/2259835/171640550-dc765ad9-a12e-46b3-966d-c5d4d98eb924.png)

**Why is this happening?**

I foud the Quasar's code responsible for this: https://github.com/quasarframework/quasar/blob/dev/ui/src/components/dialog/QDialog.js#L351
The `onFocusChange` function is called everytime I try to focus some element. The `childHasFocus(innerRef.value, evt.target)` condition is `false` obviously because the WYSIWYG's dialog is **NOT** a child of QDialog so this line `focus('[tabindex]:not([tabindex="-1"])')` is called. And this process repeats everytime I try to focus that input, so as a result Im not able to focus it at all.

The only solution I found is to use `seamless` option, but I don't want to use it. I want my QDialog's backdrop area to work.

### What did you expect to happen?

I expect Quasar's QDialog component to allow elements outside the QDialog be focused. Expect the `no-focus` and `no-refocus` properties there might be a new prop `allow-focus-outside` (or whatever) that would allow me to focus elements outside the QDialog. I see no reason why this is implemented: https://github.com/quasarframework/quasar/blob/dev/ui/src/components/dialog/QDialog.js#L167

When the QDialog is in seamless mode, this code is ignored and when the QDialog is not in seamless mode then user cannot click on any element below the backdrop area (because of the `z-index`). But I see no reason why user cannot click on an element with `z-index` higher than the QDialog's backdrop. I guess it's because of the keyboard access? (User should not be able to focus element outside the QDialog using the `TAB` key?

I know it's an complex problem and there is no clear solution, but maybe simple adding the `allow-focus-outside` property would be good enough. This new prop would simply change [this function](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/dialog/QDialog.js#L351) from this:

```js
function onFocusChange (evt) {
  // the focus is not in a vue child component
  if (
    portalIsAccessible.value === true
    && childHasFocus(innerRef.value, evt.target) !== true
  ) {
    focus('[tabindex]:not([tabindex="-1"])')
  }
}
```

to this:

```js
function onFocusChange (evt) {
  // the focus is not in a vue child component
  if (
    props.allowFocusOutside !== true
    && portalIsAccessible.value === true
    && childHasFocus(innerRef.value, evt.target) !== true
  ) {
    focus('[tabindex]:not([tabindex="-1"])')
  }
}
```

### Reproduction URL

https://codesandbox.io/s/sharp-architecture-8bfu6p?file=/src/pages/Index.vue

### How to reproduce?

1. Go to provided reproduction link
2. Click on `SHOW DIALOG` button
![6](https://user-images.githubusercontent.com/2259835/171645058-d6d3a2d6-980b-4ab6-ae13-b4eaa1941c59.png)
4. TinyMCE editor inside a QDialog should show
![1](https://user-images.githubusercontent.com/2259835/171639688-f2ecabed-40b3-4eb6-8ea7-0d2eb495a938.png)
5. Click on the "link" button
![2](https://user-images.githubusercontent.com/2259835/171640179-d502f50c-252b-4e62-bc7d-f8714c658c19.png)
6. Try to focus an `<input>` inside the TinyMCE's dialog. Quasar will not allow you to do that.
![4](https://user-images.githubusercontent.com/2259835/171640550-dc765ad9-a12e-46b3-966d-c5d4d98eb924.png)

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), Plugins (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
$ quasar info

Operating System        Linux(5.3.0-28-generic) - linux/x64
NodeJs                  14.19.3

Global packages         
  NPM                   6.14.17
  yarn                  1.22.5
  @quasar/cli           1.3.2
  @quasar/icongenie     2.5.1
  cordova               Not installed

Networking              
  Host                  mspiderv-linux
  enp39s0               192.168.1.16
```

**Comment by rstoenescu** [comment]
Agreed. The new Boolean prop (allow-focus-outside) will be available in Quasar v2.7.2
