### ISSUE TITLE
QImg: The picture is squeezed out when QImg is small enough

### ISSUE THREAD

**Issue by brendan-lee** [quasarframework/quasar#13598]
### What happened?

If the size of a QImg is small enough, say `12px`, the picture will be squeezed down and only be partially visible. The smaller the size, the less visible part, until completely disappeared.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/10712544/171772441-eea3d2ea-f7f2-49ee-993a-03a4bc8aff5f.png">

It starts to happen when approaching the `font-size` and seems to be caused by a "strut", here is the [spec](https://www.w3.org/TR/css-inline-3/#inline-height) describing it:

> To find the [layout bounds](https://www.w3.org/TR/css-inline-3/#layout-bounds) of an [inline box](https://www.w3.org/TR/css-display-3/#inline-box), the UA must first align all the glyphs directly contained in the inline box to each other by their [dominant baselines](https://www.w3.org/TR/css-inline-3/#dominant-baseline). (See [§ 3.3 Baselines of Glyphs and Boxes](https://www.w3.org/TR/css-inline-3/#baseline-tables).) If the inline box contains no glyphs at all, or if it contains only glyphs from fallback fonts, it is considered to contain a “strut” (an invisible glyph of zero width) with the metrics of the box’s [first available font](https://www.w3.org/TR/css-fonts-4/#first-available-font).

After setting the `font-size` of the image container (i.e. `.q-img__container`) to `0`, the bug goes away.

### What did you expect to happen?

The picture should be in the correct position at whatever size.

### Reproduction URL

https://codepen.io/lzm956902416/pen/jOZKVLZ

### How to reproduce?

1. Change `font-size` by the slider and see how `<QImg>` be squeezed. 
2. Turn the "Fix it" switch on, slide again, and now the bug is gone.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, iOS

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.2 and v1.19.2
