### ISSUE TITLE
QSelect filtering

### ISSUE THREAD

**Issue by GitNomster** [quasarframework/quasar#13599]
### What happened?

Filtering in the select field does not work when I enter letters. But it works when I enter numbers. Filter event not firing.
This was tested on android 10 chrome 102.0.5005.78.
Same problem on quasar v2.

![phone_filter](https://user-images.githubusercontent.com/29253035/171833953-e2f7534e-4179-4e1e-a240-7a1a40db7f4a.gif)

### What did you expect to happen?

Normal filtering on android.

### Reproduction URL

https://codepen.io/gitnomster/pen/zYRaPpr

### How to reproduce?

Open chrome browser on android. Tap on input, press any letters.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Android, Chrome

**Comment by MilosPaunovic** [comment]
It might be something related to your phone. Try opening Chrome in incognito mode. ![Screenshot_20220603_122008_com.android.chrome.jpg](https://user-images.githubusercontent.com/62475782/171836309-52c75447-f6f8-4568-ac83-65c93e875380.jpg)

**Comment by GitNomster** [comment]
Same problem in incognito.

**Comment by pdanpdan** [comment]
It's the keyboard composing. Press space or click the word in the suggestions

**Comment by GitNomster** [comment]
With GBoard in chrome not working and maby emojiboard.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.7.2 and 1.19.2

**Comment by nulele** [comment]
Hello,

I'm running

@quasar/cli v1.2.2
@quasar/app v3.3.3

on Android cordova app. Still when typing nothing happens until I add a space, pick the suggested word or tab the search button on the keyboard.

**Comment by pdanpdan** [comment]
Update your packages - `@quasar/app` is very old, so your quasar framework version is also old
Check the docs for upgrading to the newer `@quasar/app-webpack` or `@quasar/app-vite`

**Comment by nulele** [comment]
Yeah, it was an old project... now I upgraded and it works!!! Many thanks!!!
