### ISSUE TITLE
The ripple of q-tab is triggered twice on a touchscreen

### ISSUE THREAD

**Issue by brendan-lee** [quasarframework/quasar#13596]
### What happened?

Everything is fine with a mouse, but on a touchscreen the ripple effect of ```q-tab``` triggers once on ```touchstart``` and again on ```touchend``` . So if you tap on a tab, it'll show the ripple twice fast.

### What did you expect to happen?

Triggers the ripple on ```touchstart``` only.

### Reproduction URL

https://quasar.dev/vue-components/tabs#basic

### How to reproduce?

Tap a tab on a touchscreen.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

iOS

**Comment by FrankySnow** [comment]
Also experiencing it on Firefox / Android. It's better visualized when tapping & holding the finger (→ first ripple) then releasing it just before the first ripple ends (→ second ripple).

This is also noticeable in [early triggered ripples](https://quasar.dev/vue-directives/material-ripple#triggering-early) but not standard ripples.

**Comment by FrankySnow** [comment]
[Here is a Codepen](https://codepen.io/FrankySnow/pen/poaYoXP?editors=0011) to reproduce the problem.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.2
