### ISSUE TITLE
Style not working with scoped 

### ISSUE THREAD

**Issue by atillaaliyev** [quasarframework/quasar#13607]
### What happened?

I have a q-menu component and I want to change its border radius vs other css properties. I'm using style , it's ok but when I wanted using css class , it's not working. It's about style scoped but I didn't understand. When I removed scoped from style tag,it's working.

```
<template>
  <q-menu
      anchor="top start"
      class="text-weight-bolder text-blue-grey-3"
      :style="{minWidth:$q.screen.gt.sm ? '550px' : 'auto'} "
      self="bottom start"
      transition-show="scale"
      transition-hide="scale"
      width="auto"
      @hide="onReset"
  >
<!--    Other codes-->
  </q-menu>
</template>
<style lang="scss" scoped>

.q-menu {
  border-radius: 16px !important;
  max-width: calc(100% - 50px);
} //it's not working

</style>
```

### What did you expect to happen?

I don't override .q-menu class completly, only I want to override some style properties.

### Reproduction URL

https://codepen.io/atillaaliyev/pen/ZErjKqj

### How to reproduce?

1.Go to link

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

**Comment by brendan-lee** [comment]
Take a look at [CSS Modules](https://vuejs.org/api/sfc-css-features.html#css-modules).
