### ISSUE TITLE
QInput attribute

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#13602]
### What happened?

 `QInput` showing ts error when adding input attributes like `autocomplete` `inputmode` and others 

<img width="308" alt="Screen Shot 2022-06-04 at 9 07 17 AM" src="https://user-images.githubusercontent.com/19895516/171990874-b21c0451-2fb5-4244-bdf6-19deff58352b.png">

<img width="955" alt="Screen Shot 2022-06-04 at 9 07 26 AM" src="https://user-images.githubusercontent.com/19895516/171990882-fe036290-9b91-4c1f-a022-b1696e94e6b9.png">

### What did you expect to happen?

warning free

### Reproduction URL

no link 

### How to reproduce?

tried clean up the same 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Chrome, Safari, iOS, Android

### Quasar info output

```Shell
Operating System - Darwin(21.4.0) - darwin/arm64
NodeJs - 18.0.0

Global packages
  NPM - 8.6.0
  yarn - 1.22.18
  @quasar/cli - 1.3.2
  @quasar/icongenie - 2.5.1
  cordova - Not installed

Important local packages
  quasar - 2.7.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.14.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.1.0 -- Official ESLint plugin for Quasar
  vue - 3.2.33 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - 2.0.13 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.14.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - 3.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 3.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 3.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 3.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  *None installed*
```

**Comment by metalsadman** [comment]
looks related to this https://github.com/johnsoncodehk/volar/issues/1077

**Comment by metalsadman** [comment]
new version of volar was released 
![Screen Shot 2022-06-06 at 11 17 47 AM](https://user-images.githubusercontent.com/31038838/172088939-f46a24b8-d31d-4b8b-beb1-06ffb2a48025.png)
reload your IDE, please confirm if it fixes it, thx.
