### ISSUE TITLE
Tooltip does not disappear if the button becomes disabled

### ISSUE THREAD

**Issue by doox911** [quasarframework/quasar#13606]
### What happened?

If the cursor is over the button and the button becomes inactive after the click, the tooltip does not disappear.

### What did you expect to happen?

Tooltip will disappear

### Reproduction URL

https://codepen.io/doox911/pen/wvyxgYE?editors=101

### How to reproduce?

1. Describe the button
2. Put the Tooltip inside
3. Make button inactive

Example code:
```vue
<div id="q-app">
  <div class="q-pa-md">
    <q-btn  label="With Tooltip" :disable="disabled" @click="disabled = true">
      <q-tooltip class="bg-accent">I'm a tooltip</q-tooltip>
    </q-btn>
  </div>
</div>
```

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
You can toggle it through the `v-model` and have desired behaviour.
[https://quasar.dev/vue-components/tooltip#example--toggle-through-v-model](https://quasar.dev/vue-components/tooltip#example--toggle-through-v-model)

**Comment by doox911** [comment]
> You can toggle it through the `v-model` and have desired behaviour. https://quasar.dev/vue-components/tooltip#example--toggle-through-v-model

It works. But I think it's still illogical behavior. Since the cursor is out of button.

**Comment by pdanpdan** [comment]
Disabled buttons do not receive pointer events, so the tooltip cannot know the pointer is not hovering anymore.
You should use a `v-if` on the tooltip that only renders it when the button is enabled, or use a wrapper div that has the button and the tooltip as direct children.

**Comment by rstoenescu** [comment]
By default, QBtn renders into a `<button>` native element. Use `<q-btn type="a"` to force QBtn be rendered as an `<a>` tag. These tags still have pointer events even if "disabled".
