### ISSUE TITLE
[Enhancement] add non-linear property to stepper

### ISSUE THREAD

**Issue by psychonetic** [quasarframework/quasar#1361]
It would be great if the stepper would have a non-linear property like the stepper from vuetify.js.
If the component has a non-linear property, the user can switch between all steps (does not matter if step is done). See: https://vuetifyjs.com/components/steppers#example-8

**Comment by pdanpdan** [comment]
In my opinion:
- for specific cases you can use stepper.goToStep('step-name') - that is if the user can skip some optional steps (this option is available in v0.15 - I don't remember if it's in v0.14 also)
- but this should go into the QStepperNavigation, not in the list of steps, or else you would only transform it to a list of tabs

**Comment by matejicekme** [comment]
+1 for this feature :) would make the stepper usable in more cases.

**Comment by rstoenescu** [comment]
Hi,

QStepper will be much more flexible in v1.0. It includes ability to use it in a "non-linear" fashion too.

**Comment by zedektador** [comment]
any reports?
