### ISSUE TITLE
Dialog plugin - template refs are not set when using custom dialog component

### ISSUE THREAD

**Issue by ddenev** [quasarframework/quasar#13628]
### What happened?

When using Dialog plugin with custom component, the template refs that are within the custom dialog component are not set.

Check the jsfiddle below. My expectation is that in the `onMounted` hook the `cardRef` would be set but it's not. Even with `nextTick` it is still not set.

### What did you expect to happen?

Expect template refs to be set and valid within `onMounted` hook.

### Reproduction URL

https://jsfiddle.net/ddenev/ruhxv3md/37/

### How to reproduce?

1. Go to the reproduction link
2. Make sure the console is visible
3. Hit the "Open Dialog" button
4. Observe that `cardRef` value is `null` in the console

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Plugins (quasar)

**Comment by pdanpdan** [comment]
That ref will only be set when the dialog is open - the whole content of dialog is only rendered when it is displayed.

**Comment by ddenev** [comment]
Thank you, @pdanpdan , but I don't understand what you mean.

> the whole content of dialog is only rendered when it is displayed.

Isn't this exactly what `onMounted` is for? If not, then how can I use the `cardRef` properly?

**Comment by pdanpdan** [comment]
No, `onMounted` is called when your custom component (that has the dialog in it) is rendered.
But that component is rendered before the dialog is opened.
BTW, `cardRef` is not returned from setup, so it would not work anyway.

Working example (listening for `@show`): https://jsfiddle.net/ozcLufgd/3/

**Comment by ddenev** [comment]
Got it, thank you for explaining and for the working example, @pdanpdan !

**Comment by ddenev** [comment]
One more question, @pdanpdan:

Is this the way Quasar is implemented - I mean that the ref is set after the dialog is opened - or is this coming from Vue?

I ask because the Vue docs (https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs) say that:
> you can only access the ref after the component is mounted

so I natively expected that all template refs which are part of the component would be properly set at the time it has been rendered.
If Quasar is setting the refs after the dialog is opened, isn't that a deviation from the Vue spec?

**Comment by rstoenescu** [comment]
Dialogs, Menus and Tooltips are rendered only they are actually shown on screen (for huge perf gains among other reasons as well). They are mounted into a comment tag (by Vue). So basically, refs are available only when Dialogs are shown on screen (so they are rendered and mounted).

**Comment by pdanpdan** [comment]
It's native Vue behaviour to only set the refs when the element with the ref is rendered.
The content of QDialog is a slot, and that slot is rendered only when the dialog is opened.
So the refs inside QDialog are set when the dialog is opened and the refs on QDialog are set when the custom component is rendered.
