### ISSUE TITLE
QSelect `input-class` and `input-style` don't seem to work

### ISSUE THREAD

**Issue by mv-go** [quasarframework/quasar#13631]
### What happened?

Selected option does not seem to reflect `input-style` and/or `input-class` when applied to `QSelect`.

```
<q-select v-model="model" :options="options" input-class="text-weight-bold text-red"/>

setup () {
    return {
      model: ref('Google'),
      options: [
        'Google', 'Facebook', 'Twitter', 'Apple', 'Oracle'
      ]
    }
  }
```

### What did you expect to happen?

Selected option to be coloured in red and font-weight to be changed to bold

### Reproduction URL

https://codepen.io/mv-go/pen/KKQxqJb

### How to reproduce?

1. Open the codepen
2. Selected option (Google) should be coloured and font-weight should be changed

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari

### Quasar info output

```Shell
Operating System - Darwin(21.4.0) - darwin/arm64
NodeJs - 18.2.0

Global packages
  NPM - 8.9.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.14.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.36 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.15
  pinia - 2.0.14 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.9 -- Native-ESM powered web dev build tool
  eslint - 8.16.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 2.0.4 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-e2e-cypress - 4.1.2 -- A Quasar App Extension for Cypress e2e

Networking
  Host - MacBook-Air.local
```

**Comment by pdanpdan** [comment]
These props only apply to the input that is used when `use-input` is set
https://codepen.io/pdanpdan/pen/LYQJjdO?editors=1010

**Comment by mikocoral05** [comment]
is there a way to adjust the font size of the selected option @pdanpdan 
.q-select {
  .q-field__inner {
    .q-field__control {
      .q-field__control-container {
        .q-field__native {
          span {
            font-size: 13px ;
          }
        }
      }
    }
  }
}
i tried to target the span where the selected option is displayed but not working
