### ISSUE TITLE
QTooltip not working as expected on ios devices

### ISSUE THREAD

**Issue by karanodedra20** [quasarframework/quasar#13632]
### What happened?

For QTooltip, tap and hold is not working on ios devices. It works when we release the tap.

### What did you expect to happen?

Tap and hold should display the text.

### Reproduction URL

https://codepen.io/KaranOdedra/pen/qBxMVGN?editors=101

### How to reproduce?

1. Open the URL on the ios device.
2. Tap and hold, and then release.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

iOS

**Comment by rstoenescu** [comment]
What mobile browser are you using? Seems to work fine with Safari and Chrome. If you are building a mobile app, did you choose Cordova (and which webview? the default one or the wkwebview?) or Capacitor? And which versions.

**Comment by karanodedra20** [comment]
I checked on iPhone 13, chrome (BrowserStack). It is a web app. Text is displayed when I release the 'Tap & Hold'. I also checked on Oneplus 9, chrome, and it works fine.

**Comment by rstoenescu** [comment]
Works fine on a real iOS device, so it might be BrowserStack interfering somehow...

**Comment by rstoenescu** [comment]
Please reopen if you encounter problems on a real device. I just re-tested and everything looks fine.
