### ISSUE TITLE
QTable loading state with auto-width col

### ISSUE THREAD

**Issue by KINGER404** [quasarframework/quasar#13644]
### What happened?

The loading bar in the table is not full width when the header has a column with the auto-width prop

### What did you expect to happen?

Full width loading bar

### Reproduction URL

https://codepen.io/kinger404/pen/qBxJqPK

### How to reproduce?

1. Open reproduction URL
2. Look at the loading bar in the table

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
You are rendering a different number of columns that the one in the columns definition.
Tell QTable how many columns you are rendering with `table-colspan`
