### ISSUE TITLE
Error in quasar's build/eslint 

### ISSUE THREAD

**Issue by dreyn74** [quasarframework/quasar#1364]
Hi,
I just started using quasar yesterday, and every time that I try to run `quasar build` or `quasar lint`
I get this issue:
- `npm ERR! code ELIFECYCLE`
- `npm ERR! errno 1`
- `npm ERR! quasar-app@0.0.1 lint: `eslint --ext .js,.vue src`
- `npm ERR! Exit status 1`
- `npm ERR!`
- `npm ERR! Failed at the quasar-app@0.0.1 lint script.`

This project was installed using quasar-cli, and the default template.
I started the project with `quasar dev mat --play`
I removed my global installation of eslint, and that did not help.

**Comment by rstoenescu** [comment]
Hi,

What's your host OS? Please copy-paste the whole console output (including your command).
I assume that you've run "npm install" inside the project folder, right?

Thanks.

**Comment by dreyn74** [comment]
Up to date version of Windows 10.
I reinstalled one more time, and I get the same error: 
`
c:\Users\dreyn\Downloads\www\quasar\test>quasar lint --fix


> quasar-app@0.0.1 lint c:\Users\dreyn\Downloads\www\quasar\test
> eslint --ext .js,.vue src


c:\Users\dreyn\Downloads\www\quasar\test\src\App.vue
   12:1   error  Expected space or tab after '//' in comment                           spaced-comment
   13:1   error  'modules' is not defined                                              no-undef
   14:7   error  Strings must use singlequote                                          quotes
   15:1   error  Expected indentation of 2 spaces but found 4                          indent
   16:1   error  Expected indentation of 4 spaces but found 8                          indent
   16:18  error  Expected space or tab after '//' in comment                           spaced-comment
   17:1   error  Expected indentation of 4 spaces but found 8                          indent
   17:19  error  Expected space or tab after '//' in comment                           spaced-comment
   18:1   error  Expected indentation of 4 spaces but found 8                          indent
   19:1   error  Expected indentation of 4 spaces but found 8                          indent
   20:1   error  Expected indentation of 2 spaces but found 4                          indent
   21:1   error  Expected indentation of 2 spaces but found 4                          indent
   21:12  error  Missing space before function parentheses                             space-before-function-paren
   22:1   error  Expected indentation of 4 spaces but found 8                          indent
   22:23  error  Extra semicolon                                                       semi
   23:1   error  Expected indentation of 2 spaces but found 4                          indent
   25:1   error  Expected indentation of 2 spaces but found 4                          indent
   26:1   error  Expected indentation of 4 spaces but found 8                          indent
   27:1   error  Expected indentation of 6 spaces but found 12                         indent
   27:26  error  Missing space before function parentheses                             space-before-function-paren
   29:1   error  Expected indentation of 6 spaces but found 12                         indent
   31:1   error  Expected indentation of 6 spaces but found 12                         indent
   31:26  error  Missing space before function parentheses                             space-before-function-paren
   32:1   error  Expected indentation of 8 spaces but found 16                         indent
   33:1   error  Expected indentation of 8 spaces but found 16                         indent
   33:48  error  Extra semicolon                                                       semi
   34:1   error  Expected indentation of 8 spaces but found 16                         indent
   34:42  error  Strings must use singlequote                                          quotes
   35:1   error  Expected indentation of 10 spaces but found 20                        indent
   35:37  error  Strings must use singlequote                                          quotes
   35:48  error  Extra semicolon                                                       semi
   36:1   error  Expected indentation of 8 spaces but found 16                         indent
   36:17  error  Closing curly brace appears on the same line as the subsequent block  brace-style
   37:1   error  Expected indentation of 10 spaces but found 20                        indent
   37:37  error  Strings must use singlequote                                          quotes
   37:47  error  Extra semicolon                                                       semi
   38:1   error  Expected indentation of 8 spaces but found 16                         indent
   39:1   error  Expected indentation of 8 spaces but found 16                         indent
   39:36  error  Extra semicolon                                                       semi
   40:1   error  Expected indentation of 6 spaces but found 12                         indent
   41:1   error  Expected indentation of 4 spaces but found 8                          indent
   42:1   error  Expected indentation of 2 spaces but found 4                          indent
   44:1   error  Expected indentation of 2 spaces but found 4                          indent
   45:1   error  Expected indentation of 4 spaces but found 8                          indent
   45:16  error  Missing space before function parentheses                             space-before-function-paren
   46:1   error  Expected indentation of 6 spaces but found 12                         indent
   46:25  error  Strings must use singlequote                                          quotes
   46:46  error  Extra semicolon                                                       semi
   47:1   error  Expected indentation of 6 spaces but found 12                         indent
   47:29  error  Extra semicolon                                                       semi
   48:1   error  Expected indentation of 6 spaces but found 12                         indent
   49:1   error  Expected indentation of 8 spaces but found 16                         indent
   50:1   error  Expected indentation of 8 spaces but found 16                         indent
   50:30  error  Missing space before function parentheses                             space-before-function-paren
   51:1   error  Expected indentation of 10 spaces but found 20                        indent
   52:1   error  Expected indentation of 12 spaces but found 24                        indent
   53:1   error  Expected indentation of 12 spaces but found 24                        indent
   53:38  error  Missing space before function parentheses                             space-before-function-paren
   54:1   error  Expected indentation of 14 spaces but found 28                        indent
   55:1   error  Expected indentation of 16 spaces but found 32                        indent
   56:1   error  Expected indentation of 16 spaces but found 32                        indent
   57:1   error  Expected indentation of 16 spaces but found 32                        indent
   58:1   error  Expected indentation of 16 spaces but found 32                        indent
   58:43  error  Strings must use singlequote                                          quotes
   59:1   error  Expected indentation of 14 spaces but found 28                        indent
   59:30  error  Extra semicolon                                                       semi
   60:1   error  Expected indentation of 12 spaces but found 24                        indent
   60:27  error  Extra semicolon                                                       semi
   61:1   error  Expected indentation of 8 spaces but found 16                         indent
   61:19  error  Extra semicolon                                                       semi
   62:1   error  Expected indentation of 4 spaces but found 8                          indent
   64:1   error  Expected indentation of 4 spaces but found 8                          indent
   64:19  error  Missing space before function parentheses                             space-before-function-paren
   65:1   error  Expected indentation of 6 spaces but found 12                         indent
   66:1   error  Expected indentation of 6 spaces but found 12                         indent
   67:1   error  Expected indentation of 6 spaces but found 12                         indent
   67:13  error  Expected space or tab after '//' in comment                           spaced-comment
   68:1   error  Expected indentation of 6 spaces but found 12                         indent
   68:36  error  Missing space before function parentheses                             space-before-function-paren
   69:1   error  Expected indentation of 8 spaces but found 16                         indent
   69:41  error  Missing space before function parentheses                             space-before-function-paren
   70:1   error  Expected indentation of 10 spaces but found 20                        indent
   70:27  error  Expected '===' and instead saw '=='                                   eqeqeq
   70:39  error  Expected '===' and instead saw '=='                                   eqeqeq
   71:1   error  Expected indentation of 12 spaces but found 24                        indent
   71:51  error  Extra semicolon                                                       semi
   72:1   error  Expected indentation of 10 spaces but found 20                        indent
   73:1   error  Expected indentation of 10 spaces but found 20                        indent
   73:32  error  Extra semicolon                                                       semi
   74:1   error  Expected indentation of 8 spaces but found 16                         indent
   74:19  error  Extra semicolon                                                       semi
   75:1   error  Expected indentation of 6 spaces but found 12                         indent
   75:15  error  Extra semicolon                                                       semi
   76:1   error  Expected indentation of 4 spaces but found 8                          indent
   78:1   error  Expected indentation of 4 spaces but found 8                          indent
   78:17  error  Missing space before function parentheses                             space-before-function-paren
   79:1   error  Expected indentation of 6 spaces but found 12                         indent
   79:25  error  Strings must use singlequote                                          quotes
   79:47  error  Extra semicolon                                                       semi
   80:1   error  Expected indentation of 6 spaces but found 12                         indent
   80:47  error  Missing space before function parentheses                             space-before-function-paren
   81:1   error  Expected indentation of 8 spaces but found 16                         indent
   81:42  error  Strings must use singlequote                                          quotes
   82:1   error  Expected indentation of 10 spaces but found 20                        indent
   82:37  error  Strings must use singlequote                                          quotes
   82:48  error  Extra semicolon                                                       semi
   83:1   error  Expected indentation of 8 spaces but found 16                         indent
   83:17  error  Closing curly brace appears on the same line as the subsequent block  brace-style
   84:1   error  Expected indentation of 10 spaces but found 20                        indent
   84:37  error  Strings must use singlequote                                          quotes
   84:47  error  Extra semicolon                                                       semi
   85:1   error  Expected indentation of 8 spaces but found 16                         indent
   86:1   error  Expected indentation of 8 spaces but found 16                         indent
   86:28  error  Extra semicolon                                                       semi
   87:1   error  Expected indentation of 6 spaces but found 12                         indent
   87:15  error  Extra semicolon                                                       semi
   88:1   error  Expected indentation of 4 spaces but found 8                          indent
   90:1   error  Expected indentation of 4 spaces but found 8                          indent
   90:17  error  Missing space before function parentheses                             space-before-function-paren
   90:28  error  Identifier 'unvealing_all' is not in camel case                       camelcase
   91:1   error  Expected indentation of 6 spaces but found 12                         indent
   91:25  error  Strings must use singlequote                                          quotes
   91:47  error  Extra semicolon                                                       semi
   92:1   error  Expected indentation of 6 spaces but found 12                         indent
   92:44  error  Extra semicolon                                                       semi
   93:1   error  Expected indentation of 6 spaces but found 12                         indent
   93:29  error  Extra semicolon                                                       semi
   94:1   error  Expected indentation of 6 spaces but found 12                         indent
   95:1   error  Expected indentation of 6 spaces but found 12                         indent
   95:38  error  Strings must use singlequote                                          quotes
   96:1   error  Expected indentation of 8 spaces but found 16                         indent
   96:23  error  Extra semicolon                                                       semi
   97:1   error  Expected indentation of 6 spaces but found 12                         indent
   99:1   error  Expected indentation of 6 spaces but found 12                         indent
  100:1   error  Expected indentation of 8 spaces but found 16                         indent
  100:51  error  Missing space before function parentheses                             space-before-function-paren
  101:1   error  Expected indentation of 10 spaces but found 20                        indent
  101:37  error  Strings must use singlequote                                          quotes
  101:44  error  Extra semicolon                                                       semi
  102:1   error  Expected indentation of 10 spaces but found 20                        indent
  102:32  error  Extra semicolon                                                       semi
  103:1   error  Expected indentation of 8 spaces but found 16                         indent
  103:19  error  Extra semicolon                                                       semi
  104:1   error  Expected indentation of 8 spaces but found 16                         indent
  104:22  error  Identifier 'unvealing_all' is not in camel case                       camelcase
  105:1   error  Expected indentation of 10 spaces but found 20                        indent
  105:37  error  Extra semicolon                                                       semi
  106:1   error  Expected indentation of 8 spaces but found 16                         indent
  107:1   error  Expected indentation of 6 spaces but found 12                         indent
  107:13  error  Closing curly brace appears on the same line as the subsequent block  brace-style
  108:1   error  Expected indentation of 8 spaces but found 16                         indent
  108:68  error  Extra semicolon                                                       semi
  109:1   error  Expected indentation of 8 spaces but found 16                         indent
  109:36  error  Expected '===' and instead saw '=='                                   eqeqeq
  110:1   error  Expected indentation of 10 spaces but found 20                        indent
  110:55  error  Missing space before function parentheses                             space-before-function-paren
  111:1   error  Expected indentation of 12 spaces but found 24                        indent
  111:41  error  Strings must use singlequote                                          quotes
  111:50  error  Extra semicolon                                                       semi
  112:1   error  Expected indentation of 12 spaces but found 24                        indent
  112:36  error  Extra semicolon                                                       semi
  113:1   error  Expected indentation of 10 spaces but found 20                        indent
  113:23  error  Extra semicolon                                                       semi
  115:1   error  Expected indentation of 10 spaces but found 20                        indent
  115:26  error  Identifier 'unvealing_all' is not in camel case                       camelcase
  116:1   error  Expected indentation of 12 spaces but found 24                        indent
  116:63  error  Missing space before function parentheses                             space-before-function-paren
  117:1   error  Expected indentation of 14 spaces but found 28                        indent
  117:72  error  Extra semicolon                                                       semi
  118:1   error  Expected indentation of 12 spaces but found 24                        indent
  118:27  error  Extra semicolon                                                       semi
  119:1   error  Expected indentation of 10 spaces but found 20                        indent
  120:1   error  Expected indentation of 8 spaces but found 16                         indent
  120:17  error  Closing curly brace appears on the same line as the subsequent block  brace-style
  121:1   error  Expected indentation of 10 spaces but found 20                        indent
  121:55  error  Missing space before function parentheses                             space-before-function-paren
  122:1   error  Expected indentation of 12 spaces but found 24                        indent
  122:41  error  Strings must use singlequote                                          quotes
  122:76  error  Extra semicolon                                                       semi
  123:1   error  Expected indentation of 12 spaces but found 24                        indent
  123:36  error  Extra semicolon                                                       semi
  124:1   error  Expected indentation of 10 spaces but found 20                        indent
  124:23  error  Extra semicolon                                                       semi
  125:1   error  Expected indentation of 8 spaces but found 16                         indent
  126:1   error  Expected indentation of 6 spaces but found 12                         indent
  127:1   error  Expected indentation of 4 spaces but found 8                          indent
  129:1   error  Expected indentation of 4 spaces but found 8                          indent
  129:18  error  Missing space before function parentheses                             space-before-function-paren
  130:1   error  Expected indentation of 6 spaces but found 12                         indent
  130:29  error  Extra semicolon                                                       semi
  131:1   error  Expected indentation of 6 spaces but found 12                         indent
  131:40  error  Missing space before function parentheses                             space-before-function-paren
  132:1   error  Expected indentation of 8 spaces but found 16                         indent
  132:37  error  Missing space before function parentheses                             space-before-function-paren
  133:1   error  Expected indentation of 10 spaces but found 20                        indent
  133:47  error  Extra semicolon                                                       semi
  134:1   error  Expected indentation of 8 spaces but found 16                         indent
  134:19  error  Extra semicolon                                                       semi
  135:1   error  Expected indentation of 6 spaces but found 12                         indent
  135:15  error  Extra semicolon                                                       semi
  136:1   error  Expected indentation of 4 spaces but found 8                          indent
  138:1   error  Expected indentation of 4 spaces but found 8                          indent
  138:28  error  Missing space before function parentheses                             space-before-function-paren
  139:1   error  Expected indentation of 6 spaces but found 12                         indent
  139:57  error  Missing space before function parentheses                             space-before-function-paren
  140:1   error  Expected indentation of 8 spaces but found 16                         indent
  140:39  error  Extra semicolon                                                       semi
  141:1   error  Expected indentation of 6 spaces but found 12                         indent
  141:22  error  Extra semicolon                                                       semi
  142:1   error  Expected indentation of 4 spaces but found 8                          indent
  144:1   error  Expected indentation of 4 spaces but found 8                          indent
  144:19  error  Missing space before function parentheses                             space-before-function-paren
  145:1   error  Expected indentation of 6 spaces but found 12                         indent
  145:29  error  Extra semicolon                                                       semi
  146:1   error  Expected indentation of 6 spaces but found 12                         indent
  148:1   error  Expected indentation of 6 spaces but found 12                         indent
  149:1   error  Expected indentation of 8 spaces but found 16                         indent
  150:1   error  Expected indentation of 8 spaces but found 16                         indent
  151:1   error  Expected indentation of 8 spaces but found 16                         indent
  152:1   error  Expected indentation of 8 spaces but found 16                         indent
  153:1   error  Expected indentation of 8 spaces but found 16                         indent
  154:1   error  Expected indentation of 8 spaces but found 16                         indent
  155:1   error  Expected indentation of 8 spaces but found 16                         indent
  156:1   error  Expected indentation of 8 spaces but found 16                         indent
  157:1   error  Expected indentation of 6 spaces but found 12                         indent
  157:31  error  Missing space before function parentheses                             space-before-function-paren
  158:1   error  Expected indentation of 8 spaces but found 16                         indent
  159:1   error  Expected indentation of 10 spaces but found 20                        indent
  159:45  error  Extra semicolon                                                       semi
  161:1   error  Expected indentation of 8 spaces but found 16                         indent
  162:1   error  Expected indentation of 10 spaces but found 20                        indent
  162:58  error  Extra semicolon                                                       semi
  163:1   error  Expected indentation of 8 spaces but found 16                         indent
  164:1   error  Expected indentation of 6 spaces but found 12                         indent
  164:15  error  Extra semicolon                                                       semi
  166:1   error  Expected indentation of 6 spaces but found 12                         indent
  166:33  error  Extra semicolon                                                       semi
  167:1   error  Expected indentation of 4 spaces but found 8                          indent
  169:1   error  Expected indentation of 4 spaces but found 8                          indent
  169:14  error  Missing space before function parentheses                             space-before-function-paren
  170:1   error  Expected indentation of 6 spaces but found 12                         indent
  171:1   error  Expected indentation of 8 spaces but found 16                         indent
  175:1   error  Expected indentation of 6 spaces but found 12                         indent
  175:14  error  Extra semicolon                                                       semi
  176:1   error  Expected indentation of 4 spaces but found 8                          indent
  177:1   error  Expected indentation of 2 spaces but found 4                          indent

✖ 246 problems (246 errors, 0 warnings)
  239 errors, 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quasar-app@0.0.1 lint: `eslint --ext .js,.vue src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quasar-app@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dreyn\AppData\Roaming\npm-cache\_logs\2017-12-28T03_55_58_369Z-debug.log
`

**Comment by wedog** [comment]
Appears to violate eslint rule constraints. 
look https://eslint.org/

**Comment by dreyn74** [comment]
> Appears to violate eslint rule constraints.
> look https://eslint.org/

The issue is that `quasar lint --fix` does not fix the lint errors.

**Comment by dreyn74** [comment]
I have discovered that this is a problem with eslint/npm. 
Thank you anyway.

**Comment by rstoenescu** [comment]
Also, try installing eslint globally and run "eslint --ext .js,.vue src --fix". Closing as you mentioned it's a problem with eslint itself. Let me know how it goes. Thank you!

**Comment by PradeepSusaiRaj** [comment]
> I have discovered that this is a problem with eslint/npm.
> Thank you anyway.

how did you clear this one

**Comment by hawkeye64** [comment]
In your package.json, add this as script:
```
"lint-fix": "eslint --ext .js,.vue src --fix",
```
then from command-line, run `yarn lint-fix`
