### ISSUE TITLE
QBtn disabled prop and href not working

### ISSUE THREAD

**Issue by HannesOberreiter** [quasarframework/quasar#13654]
### What happened?

If you add `disabled=false` or `disabled=true` and a `href` attribute to the `q-btn` component it always shows as disabled, but you can still click it. It works if you use the native `disable` attribute.

 

### What did you expect to happen?

I would expect if you use the `disabled=true` prop the underlaying `a` tag should get a `disable` prop.

### Reproduction URL

https://codepen.io/hannesoberreiter/pen/rNJqZzN

### How to reproduce?

1. go to the provided repo
2. first row uses `disabled` props (false and true)
3. second row uses `disable` props (false and true)

![image](https://user-images.githubusercontent.com/16878981/172856587-47fe85ba-5616-4a90-b62c-accccaa5ed03.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Additional context

PS: I actually did try to create a `q-btn` which does download the `href` content, see added `download` attribute in the CodePen. It does only redirect to the `href` and does not force a download. Is this a normal behaviour? 

Cheers
Hannes

**Comment by pdanpdan** [comment]
The prop is not disabled, is disable

**Comment by HannesOberreiter** [comment]
@pdanpdan thanks and sorry, seems like I messed it up :) I really though it was `disabled` ...

By any chance do you know why the download attribute does not work as I would expect it?

Thanks in advance!
Hannes

**Comment by pdanpdan** [comment]
The navigation is performed using JS, and the download attribute is not accounted for.
Anyway for the case of download I think it is better to just a simple native `<a href... download>` or a full save-as solution.
