### ISSUE TITLE
q-table: `v-model:pagination` + `:filter="Object"` + `:filter-method` breaks pagination

### ISSUE THREAD

**Issue by mjsir911** [quasarframework/quasar#13662]
### What happened?

Clicking on the next button of the table's pagination bar does nothing.

### What did you expect to happen?

Pagination to work as expected similarly to without `v-model:`

### Reproduction URL

https://codepen.io/mjsir911/pen/dydgreP

### How to reproduce?

```vue
    <q-table
      :filter="{text: filterText}"
      :filter-method="myfiltermethod"
      v-model:pagination="pagination"
```

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

**Comment by metalsadman** [comment]
@mjsir911 it's working fine, it's your filter-method logic that needs to be changed `rows.filter(row => (row.name).toLowerCase().includes(terms.text.toLowerCase()));`.

p.s. please use discussions next time for stuff that aren't a bug.

**Comment by rstoenescu** [comment]
Hi,

The way that you declared your filter creates a new Object on each re-render -- which triggers QTable to reset pagination to first page (obvious feature - you change the filter, it should show you first page of "results").

What you should do instead is to create a computed prop for the filter and assign it in your vue template. This way the filter will only change when the actual filterText changes.

```
:filter="myFilter"

setup () {
    const filterText = ref('')
    return {
      columns,
      rows: ref(rows),
      myFilter: computed(() => ({text: filterText.value})),
      filterText,
      pagination: ref({
        sortBy: 'desc',
        descending: false,
        page: 2,
        rowsPerPage: 3
        // rowsNumber: xx if getting data from a server
      })
    }
