### ISSUE TITLE
[PR Pre-Request] Interval against Timepicker?

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#1367]
Would you accept a PR for setting an interval against the DateTime? I'll write my own component if not which is why I thought I'd ask first.

I'd like to be able to set whether you can select 5, 10, 15 mins etc rather than each minute. 

My app has a planner which I allow jobs to be added on the hour, quarter hour or half hour. It would be nice to make the Time picker support this.

**Comment by rstoenescu** [comment]
Yes, green light. Thanks if you want to provide a PR for this!

**Comment by webnoob** [comment]
I've done all the changes required for the mat theme but I'm having a hard time with the iOS theme. We want it to appear as (for a 15 min interval):

00
15
30
45

Normally, with no intervals, when you scroll to position 1, it's assuming it's minute 1 and calculating the CSS transitions etc as such. With intervals, we need position 1 to actually be minute 15 but if we do that then it's making the CSS transitions way off.

Any guidance on the best thing to do here?

**Comment by webnoob** [comment]
I've not been on this for the past couple of weeks but I still need to get it done for my app launch. 

If I get it done over the next couple of days, would it be possible to be included in the 0.15 sprint?

**Comment by rstoenescu** [comment]
Yes, sure. Please go ahead.

**Comment by realcarbonneau** [comment]
@webnoob I am doing some work on datetime also, I could try to include this if you can't get it working.  I will add it to my list.

**Comment by realcarbonneau** [comment]
Other intervals could be added also, like select week or month granularity.

**Comment by webnoob** [comment]
I've got it working well for the mat theme but was having issues with iOS a couple of weeks ago. I was planning on sitting down tomorrow to take a look again but if it's something you're happy implementing then go ahead (I have tons on my to do list for my product launch already)

As it stands, I've implemented a new prop `:time-interval="15"` (it accepts any of the following: 5, 10, 15, 20, 30) which when set just shows the 0, 15, 30 and 45 minute sections on the clock face. Clicking between the intervals on the clock face will select the closest interval.

If want the existing work then just let me know - there isn't much to the changes TBH.

**Comment by realcarbonneau** [comment]
Continue on it if you can.  I will try to look at it when I get to it, but no guarantees when. 
Ideally, the interval props should be flexible for any factor of 60.   Eg (time-interval%60 === 0)

**Comment by webnoob** [comment]
Ok, no problem, I'll carry on.
Good point about the interval, I'll change it.

**Comment by rstoenescu** [comment]
Any progress on this?

**Comment by webnoob** [comment]
Hey Razvan,

Unfortunately not - I had other pressing things I needed to get done and this fell out of radar. I still need / want the functionality but don't really have the time to complete the work at this point.

From memory I have the changes made for android but not iOS.

**Comment by rstoenescu** [comment]
Done for future v1.0.
