### ISSUE TITLE
q-field: clearable is not showing up on empty string vs null

### ISSUE THREAD

**Issue by eyedean** [quasarframework/quasar#13677]
### What happened?

QField (and QInput)'s `clearable` property doesn't show up on an empty string to make it `null`.

In my forms, there is a difference between `null` and empty string.  I need to differentiate between the input not being set (e.g. no `name` is assigned, so a default name will be assigned) or the name is assigned and it's empty (i.e. `""` value, the user wants to have an empty name).  Since `undefined` is messing up with the Vue's two-way binding, I am using `null` (never touched, initial value, or cleared) for the first case and empty string for the second case.

The problem is if the model value is an empty string (e.g. you type one character and you hit backspace) then it's not possible to make it `null` because the `clearable` icon is not showing up.

property

### What did you expect to happen?

While the doc says `clearable` will show if any value (other than `undefined` or `null`) is set (screenshot below), the code check ignores empty string.

### Doc
https://quasar.dev/vue-components/input#qinput-api

<img width="447" alt="image" src="https://user-images.githubusercontent.com/5694695/173280744-a452cee3-e8d1-4900-8f0e-7a491de723c2.png">

### Code
https://github.com/quasarframework/quasar/blob/a59f2a180377c5798cfa9601fcdc029403e21990/ui/src/components/field/QField.js#L97-L103

### Reproduction URL

https://codepen.io/eyedean/pen/abqPJmg?editors=1010

### How to reproduce?

1. Go to https://codepen.io/eyedean/pen/abqPJmg?editors=1010
2. Hit the clear icon, the model (JSON.stringify'ed in the HTML) becomes `null`
3. Now type something and erase it with backspace.
4. The model is `""` and you cannot make it `null`.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari

### Additional context

I understand that showing the clear icon when the field is visually empty, can be undesirable and confusing.

However
1. I believe the doc and the code should be aligned.
2. There must be an option/prop to make it possible to show clearable when it's non-`null` and just an empty string. (e.g. `always-show-clearable` prop/attr.

With the correct mechanism, based on whether the user erases the field with backspace or with the clear icon, the form's values would be different.

**Comment by pdanpdan** [comment]
That is a tradeoff used for clearable
If you need specific behaviour please use a custom clear button (https://quasar.dev/vue-components/input#example--clearable) and adjust the show condition and the clear value as required
