### ISSUE TITLE
Dialog Plugin with custom component, persistent prop does not work

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [quasarframework/quasar#13671]
### What happened?

When using the dialog plugin with a custom component, the `persistent` prop is not honored.

### What did you expect to happen?

Dialog should remain persistent when the `persistent` prop is set to true.

### Reproduction URL

https://codesandbox.io/s/gallant-bhaskara-07eqml?file=/src/pages/Index.vue

### How to reproduce?

1. go to the repro link
2. press the dialog button
3. press ESC or click outside the dialog

The dialog will be dismissed.

If you uncomment the commented lines and pass `persistent: true` in the `componentProps` object, _it works_. This is unexpected to me, and I actually just now tried it. I still think this is a bug, or at least a documentation issue.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Microsoft Edge

### Quasar info output

```Shell
Operating System   	Windows_NT(10.0.19044) - win32/x64
NodeJs             	16.15.0

Global packages    	
  NPM              	8.12.1
  yarn             	1.22.15
  @quasar/cli      	1.3.2
  @quasar/icongenie	Not installed
  cordova          	Not installed
```

**Comment by metalsadman** [comment]
working fine to me. please site which is confusing to you.
![Screen Shot 2022-06-11 at 11 31 43 AM](https://user-images.githubusercontent.com/31038838/173170906-93ceb4c7-af5b-42bc-acfb-2c8bbdd2ccf6.png)

**Comment by pdanpdan** [comment]
https://github.com/quasarframework/quasar/discussions/9911
https://github.com/quasarframework/quasar/discussions/12130

**Comment by ErikPilsits-RJW** [comment]
I think our confusion was we didn't realize that `componentProps` was also meant to pass the default dialog props, such as `persistent`. It seemed to us that object was meant to pass our own component-specific props, while the dialog props would remain in the parent object.

I think this might just be an opportunity to improve the documentation a bit, and remove that ambiguity.
