### ISSUE TITLE
QTable - Row move transition

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1368]
Hi,

I would like to create a sliding up/down transition on QTable (0.15) but I’m unable to achieve that with the current QTable implementation.

Here is a working example I did using raw vue-js : https://jsfiddle.net/d5sozk3b/1/

To get this thing work on Quasar QTable we should have a slot/template exposed for the `tbody` at https://github.com/quasarframework/quasar/blob/dev/src/components/table/table-body.js#L71

I could create a PR if it's accepted.

I would like to avoid copying the QTable source code and create a new component as I need the filter/sort/columns/paging behavior.

Best regards,

Martin

**Comment by purell** [comment]
https://github.com/quasarframework/quasar/pull/1387

**Comment by rstoenescu** [comment]
Hi,

Sorry but closing this. Too many complications arise and can't make this as generic as it should be.
