### ISSUE TITLE
Disappearing borders

### ISSUE THREAD

**Issue by pbkompasz** [quasarframework/quasar#13695]
### What happened?

In a container the vertical part of the border of every child element, the top part of the border of the first element and the bottom part of the border of the last element is missing.

### What did you expect to happen?

Each child element should have a continous border around it.

### Reproduction URL

https://codepen.io/pbkompasz/pen/wvyNGZZ

### How to reproduce?

Go to the reproduction URL

### Flavour

UMD

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Yes, that is the styling for the QCard.
Don't put your elements as direct children or don't put them in QCard
