### ISSUE TITLE
QSelect start on selected option (issue with Dynamic Loading Options)

### ISSUE THREAD

**Issue by gcarpi** [quasarframework/quasar#13694]
### What happened?

I'm using the example of [Dynamic Loading Options](https://quasar.dev/vue-components/select#example--dynamic-loading-options) and when I populate the select with more options the scroll is reset to the first selected.

This happens because there is a [feature that performs this action](https://github.com/quasarframework/quasar/pull/4427), but I believe that usability is affected when we want to pull more options for the select (lazy loading of options).

![Simulation](https://user-images.githubusercontent.com/19765074/173612332-3ba0a9d7-90c6-44b6-b111-c1604df92593.gif)

**OBS:** This behavior happens in v2 too 

### What did you expect to happen?

My suggestion is to create a property to disable this action, preventing the current behavior of QSelect from being changed.

### Reproduction URL
https://codepen.io/guilhermecarpi/pen/gOvqwPr?editors=101

### How to reproduce?

1. Go to the reproduction URL;
2. Choose for example option 30;
3. Perform the scroll event to search for more options;
4. When the options are incremented, notice that the scroll is returned to the first selected one.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by DouglasCalora** [comment]
Any idea if this will be fixed?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.2 and 1.19.2
