### ISSUE TITLE
[quasar][capacitor] No external IP detected. Can't run without one

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#13691]
### What happened?

I am working on a quasar project for a mobile app using capacitor.

I used to run the app on my phone with the hot-reload module with quasar dev -m capacitor -T android. But since a few days ago, for some reason, I am getting this error : App • ⚠️  No external IP detected. Can't run without one. Manually specify one?.

I tried removing the src-capacitor folder, rolling back to a version of the project that I know was working, re-installing android studio. But none of these worked.

Additionnal information : I can launch the app on my phone from android studio but I get a white screen asking me to launch the app with quasar dev, the phone is pingabble from the computer and vice-versa, adb devices finds the phone.

I think that the issue is with quasar not finding how to open android studio as the command should open android studio with or without a phone attached.

### What did you expect to happen?

to work

### Reproduction URL
http://larasar.modemb.com

### How to reproduce?

run quasar dev -m capacitor -T android

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
> I specified the private ip address of my computer with -H 192.168.1.222 and it now works. But I have no idea why I need to specify it while it was working without it before

https://stackoverflow.com/questions/72263119/quasarcapacitor-no-external-ip-detected-cant-run-without-one#comment127686064_72263119

Does it work if you specify an IP manually? If yes, there might be a problem in IP detection logic.

> But since a few days ago, for some reason, I am getting this error.

Did you upgrade any package, re-installed your dependencies, moved to another computer, updated your computer, etc., or didn't do anything and it just started happening magically. If you think it's the latter, it's not realistic, we can't help. If you made any changes, please try to provide more info so we can pinpoint the issue and the first version it started happening, whether it was due to a code change or a bumped dependency on our side, etc.

**Comment by modemb** [comment]
I just wanted to publish my app in a store, sometime the dev works sometimes it doesn't, but the build never works, here the app https://suguffie.com, you can check the code and reproduce in http://larasar.modemb.com

**Comment by modemb** [comment]
You guys need any more information from me?

**Comment by davidAtInleague** [comment]
I think I have the same issue? Can't quite tell. I migrated a webpack based quasar project to vite; the webpack project has a working android capacitor setup, it launches into android studio, etc. But, the vite project, when running `quasar dev -m capacitor -T android` does nothing and exits with status code 1, no diagnostic.

**Comment by davidAtInleague** [comment]
on this end, seems vite-plugin-checker ends up throwing an exception that gets pretty well silenced when running in capacitor/android mode.

fwiw this line in dep-611778e0.js (representing tsconfck source?) called from vite-plugin-checker's setup throws
`const dirents = await fs$n.promises.readdir(dir, { withFileTypes: true });`

disabling vite-plugin-checker got android studio booting

**Comment by modemb** [comment]
> on this end, seems vite-plugin-checker ends up throwing an exception that gets pretty well silenced when running in capacitor/android mode.
> 
> fwiw this line in dep-611778e0.js (representing tsconfck source?) called from vite-plugin-checker's setup throws
> `const dirents = await fs$n.promises.readdir(dir, { withFileTypes: true });`
> 
> disabling vite-plugin-checker got android studio booting

Mine is in webpack, but can't build nor run dev, this is very, what did you do for the webpack one?

**Comment by modemb** [comment]
please when this going to be fix?

**Comment by analubarreto** [comment]
I'm having the same exact problem, only this is a brand new project. It's happening with both android and ios.

**Comment by modemb** [comment]
> I'm having the same exact problem, only this is a brand new project. It's happening with both android and ios.

Please if you find any solution, let me know , looks like they are not doing anything about it, now my business is stoked, just was using quasar for mobile app

**Comment by patacoing** [comment]
I'm having the same problem, and when I put the -H flag with my private ip adress (127.0.0.1), it throws me : 
` App • ⚠️  No external IP detected. Can't run without one. Manually specify one?`
 When I add a port with the IP, i got : 
 ```
 App • ⚠️  Unknown network error occurred
Error: getaddrinfo ENOTFOUND 127.0.0.1:8080
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:83:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '127.0.0.1:8080'
}
```

**Comment by patacoing** [comment]
I have found a solution for my problem, I was using wsl, just go on powershell solved this.

**Comment by modemb** [comment]
> I have found a solution for my problem, I was using wsl, just go on powershell solved this.

Powershell didn't solve my problem
