### ISSUE TITLE
Autocomplete doesn't register parent QInput

### ISSUE THREAD

**Issue by Kminkjan** [quasarframework/quasar#1370]
### Software version

Quasar:  0.14.7
OS: Windows 10
Node: 8.1.4
NPM: 5.4.2
Browsers: Chrome 63.0.3239.84

### What did you get as the error?
When i upgraded to quasar 0.14.7, my QAutocomplete stopped working. After some digging around it seems that it can't detect it's parent QInput or QSearchcomponent. The error i'm getting is:
`Error in mounted hook: "TypeError: Cannot read property 'register' of undefined"`

In the following snippet is the location from where the error is thrown:

```
  mounted: function mounted () {
    var this$1 = this;

    if (this.__input === null) {
      console.error('Autocomplete needs to be inserted into a QInput or QSearch component.');
      return
    }
    this.__input.register();  // This is the line where the error was thrown!
    if (this.__inputDebounce) {
      this.__inputDebounce.setChildDebounce(true);
    }
    this.$nextTick(function () {
      this$1.inputEl = this$1.__input.getEl();
      this$1.inputEl.addEventListener('keyup', this$1.__handleKeypress);
    });
  },
```

### What were you expecting?
A working autocomplete

### What steps did you take, to get the error?
I created this autocomplete:

```
<q-input v-model="terms" placeholder="Type something">
      <q-autocomplete
        @search="search"
        :min-characters="2"/>
    </q-input>
```

**Comment by rstoenescu** [comment]
Hi,

Something must be wrong in your app.
Take a look at docs again pls: http://quasar-framework.org/components/autocomplete.html
and at the demo on docs page: http://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/autocomplete
and at the demo's source code: https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/forms/autocomplete.vue

The autocomplete has been battle tested, so something must be wrong in your usage. If you are following everything to the letter, then pls reopen with your exact .vue file.
Thank you!

**Comment by imdanielpiva** [comment]
hey, @rstoenescu, actually this is happing. I'm getting the same error too, and everything is just docs says.

**Comment by rstoenescu** [comment]
Fixed in v0.15-beta.10

**Comment by pdanpdan** [comment]
What version of Vue do you use?
Can you provide web access to a demo showing the problem?

**Comment by imdanielpiva** [comment]
Tomorrow, @pdanpdan.

**Comment by Frondor** [comment]
> Fixed in v0.15-beta.10

How did it happen @rstoenescu ? It was working well for me, but I changed something and started to get this error. The logs are useless, all it shows is that the input reference is not there, although it should be, since the autocomplete doesn't mounts unless the input has been already mounted.

**Comment by rstoenescu** [comment]
The problem is really complex. Has to do with HMR and some Vue lifecycle hooks. There's been another patch done recently which will get into 0.15.7 (releasing today). So expect this issue to finally vanish for good.

**Comment by Frondor** [comment]
I couldn't debug this issue, so I ended up doing something like

```html
<q-input ref="parentInput">
  <q-autocomplete v-if="$refs.parentInput"> 
```

**Comment by rstoenescu** [comment]
@Kminkjan  @Frondor can you confirm this is no longer a problem with Quasar 0.15.7?
