### ISSUE TITLE
[Request/Suggestion] Make q-transition a directive

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#1371]
Multiple users have having issues with q-transition due to it being a component, and some items having strict ancestry rules. Examples includes q-table, and q-list, there is an forum post [here](http://forum.quasar-framework.org/topic/1698/apply-striped-vue-propery-to-items-rendered-with-v-for) on this matter.

Could q-transition be made into a directive? This would solve a lot of problems.

**Comment by rstoenescu** [comment]
Hi,

1. QTransition is just a soft-wrap over Vue's `<transition>` component.
2. Like the component it wraps (described earlier), it does NOT add any additional DOM element, it just tells Vue what animation to use and how.
3. Regarding the QList example: the "striped" property adds a CSS class to the QItem(s) which uses a CSS selector to tell which QItems should have different background color. But the CSS selector takes into account all DOM nodes (including ones which have CSS to hide them). By using QTransition/Vue-transition, some QItems may be in that case so the "striped" may appear broken (as it does not take into account the "hidden from view" nodes, it just takes into account all DOM sibling nodes). One solution to this would be to write and apply a custom CSS class based on the index on that v-for, something like if index divides by 2, then apply that class.

Furthermore, did some performance tests and it appears it's actually better to remove the sugar-coated QTransition and enforce developers to directly use Vue's <transition>, so this component will probably be removed for v0.15.
