### ISSUE TITLE
Modal ESC / Backdrop dismiss (Directly mutating prop)

### ISSUE THREAD

**Issue by SeoRoman** [quasarframework/quasar#1372]
When using <q-modal> within a component and passing the "open" prop, there is no way to catch the ESC and Backdrop click events before they mutate the prop directly and thus throwing the error.

Buttons on the modal can be used to call a close() method, which can $emit('close') and be caught with @close="open = false" but the ESC and Backdrop click methods cannot be caught and attempt to change the v-model directly.

<q-btn @click="test = true"></q-btn>
<component :open="test" @close="test = false"></component>

<q-modal v-model="open">
...
<q-btn @click="close"></q-btn>
</q-modal>

methods: {
  close () { this.$emit('close') }
}

The only way to prevent that message is to utilize no-esc-dismiss and no-backdrop-dismiss but that makes your modals forced...

**Comment by rstoenescu** [comment]
The event has been fixed already in future v0.15. Also, the better way to deal with this in v0.15 will be through the v-model applied to the Modal. You'll be able to listen for the 'close' event or add a watcher on the model.

**Comment by toymachiner62** [comment]
Is there an updated example on this recommended approach?

**Comment by SharpBCD** [comment]
Also looking for a solution. Any tips for v1?
