### ISSUE TITLE
QScrollArea bar min height 

### ISSUE THREAD

**Issue by hopegame** [quasarframework/quasar#13738]
### What happened?

The scroll area is less than 50px, and the minimum scroll bar is equal to 50px.

### What did you expect to happen?

If the scroll area is less than 50px, the scroll bar should be counted as %

### Reproduction URL

https://github.com/quasarframework/quasar/discussions/13666

### How to reproduce?

Use QScrollArea to set style="height:40px" and content over 100px

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.4 and 1.19.3
