### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export with starter kit

### ISSUE THREAD

**Issue by averri** [quasarframework/quasar#1373]
I have used the starter kit for Quasar as follows:

```
npm install -g quasar-cli
quasar init default#webpack1 quasar-demo
cd quasar-demo
npm install
quasar dev
```

The index demo page is blank due to the following error:

![image](https://user-images.githubusercontent.com/1898447/34522141-33eb76ca-f089-11e7-97c7-bb72026ad113.png)

Quasar seems a fantastic framework, but I think the starter kits could be improved, it's a bit frustrating now. It's still using Webpack 1, I see that there is plans to support Webpack 3 which is great.

Environment:

OS: Windows 7
Nodejs: 8.9.4

**Comment by rstoenescu** [comment]
Hi,

You are creating project folders using the webpack1 starter kit...
Just issue "quasar init quasar-demo" -- webpack3 has been added to the starter kit looong time ago.

**Comment by averri** [comment]
Hi @rstoenescu, thank you very much for that information. I just didn't find that in the `quasar list` output.

**Comment by rstoenescu** [comment]
Please always read the documentation: http://quasar-framework.org/guide/
