### ISSUE TITLE
Button loader with v-model auto sets to true on click

### ISSUE THREAD

**Issue by haquex19** [quasarframework/quasar#1375]
Quasar: 0.14.7
OS: Win 10
Browsers: Chrome

### What did you get as the error?
When using a button loader with v-model, the property set to the v-model is automatically being set to true on click of the button. This does not give complete control to the user as it is modifying a property of the button which should be controlled by the developer. 

Here is the scenario I'm looking into. There exists a delete button with `loader` set and `v-model` set to a property. When clicking on this button I would like to display a confirmation dialog to the user. At this point, the button should not be displaying the loading screen as nothing is happening yet. Once the user clicks on "OK", I want to then set the `v-model` to true to start the animation process.

I can't do this because the loading animation is already running because the `v-model` is set to true automatically on click.

### What were you expecting?
Complete control of the loading animation when using a button loader with the `v-model`. Expecting the `v-model` property to not be changed by the button, but by the developer.

**Comment by rstoenescu** [comment]
The purpose of this feature is to offer a boilerplate-free opportunity for the developer to have a "loading" feature embedded into the QBtn, which may not cover all possible use-cases.

However, for custom use-cases, you can still do it... Just place your logic inside the QBtn:

```html
<q-btn ..... >
   <q-spinner v-if="loading" />
   <span v-else>My label...</span>
</q-btn>
```
