### ISSUE TITLE
Missing source map file for mdi-v6

### ISSUE THREAD

**Issue by PawelekX** [quasarframework/quasar#13763]
### What happened?

After installed Quasar extras, which included mdi-v6 i had occured this issue. 

10:26:59 [vite] Failed to load source map for /node_modules/@quasar/extras/mdi-v6/mdi-v6.css.

### What did you expect to happen?

clear console

### Reproduction URL

https://quasar.dev/start/vite-plugin

### How to reproduce?

1. install Quasar extras from offical docs
2. Include mdi-v6
3.  run app

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

**Comment by jeannot-muller** [comment]
<img width="979" alt="ScreenShot 2022-06-23 at 20 53 11@2x" src="https://user-images.githubusercontent.com/7870873/175375856-04c15fb4-f2eb-4e9b-9e8f-e4dd75cd8aa3.png">

I can confirm the issue.

**Comment by hawkeye64** [comment]
Try deleting your `node_modules/.vite` folder and rebuild. Extras does not have anything compiled and therefore no source maps. However, vite does compile and creates source maps, but because of a race condition within vite and esbuild, it hasn't loaded the generated source maps before esbuild needs them.

**Comment by jeannot-muller** [comment]
Thank you for reaching out. Unfortunately that doesn't help. This message doesn't show during build, but dev only. Nothing big, all is working.

**Comment by kikuchan** [comment]
I'm facing the same issue, and have solved it by applying the following patch.
```
--- @quasar/extras/mdi-v6/mdi-v6.css.bak        2022-06-25 22:16:44.844506000 +0900
+++ @quasar/extras/mdi-v6/mdi-v6.css    2022-06-25 22:16:49.831606000 +0900
@@ -27455,4 +27455,3 @@
   }
 }

-/*# sourceMappingURL=materialdesignicons.css.map */
```

**Comment by rstoenescu** [comment]
Fix will be available in q/extras 1.14.2.

**Comment by rstoenescu** [comment]
@hawkeye64 can u release 1.14.2 with the fix pls?

**Comment by hawkeye64** [comment]
> @hawkeye64 can u release 1.14.2 with the fix pls?

Yep

**Comment by hawkeye64** [comment]
This was done yesterday (apologies for the delay)
