### ISSUE TITLE
date.formatDate adds a minus to the year

### ISSUE THREAD

**Issue by sitnikovalex** [quasarframework/quasar#13778]
### What happened?

date.formatDate gives wrong value for years with trailing zeros (2000, 2100, 1900)
If we use the format 'DD.MM.YY' 
we get the value 01.01.-00 for January 1, 2000

### What did you expect to happen?

Would like to get the following formatting 01.01.00

### Reproduction URL

https://codepen.io/sitnikovalex/pen/abqeEbN

### How to reproduce?

Go to the provided reproduction link

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Plugins (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.7.4 and 1.19.3
