### ISSUE TITLE
Missing files prop in QUploader type

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#13785]
### What happened?

When using the `list` slot of `QUploader` the scope property has missing props like `files`.

I'm sorry the reproduction in a repo but the IDE of Stackblitz, Codesanbox or Codepen don't evaluate the TS inside the template as I can check.

### What did you expect to happen?

Has the proper types, in my case I missing files prop with this options:

```ts
interface QUploaderWithFiles extends QUploader {
  files: {
    __key: string,
    name: string
    __image: {
      src: string
    }
  }[]
}
```

### Reproduction URL

https://github.com/Nisgrak/repro-error-quploader

### How to reproduce?

1. Use Typescript
2. Use QUploader
3. Create a template for `list` slot
4. Use the scope prop it have
5. See the error in the IDE

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), TypeScript Support

### Quasar info output

```Shell
Operating System - Linux(5.10.102.1-microsoft-standard-WSL2) - linux/x64
NodeJs - 16.15.0

Global packages
  NPM - 8.8.0
  yarn - 1.22.18
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.14.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.16
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.18.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-K1SIU8V
  eth0 - 172.23.36.140
```

### Additional context

![image](https://user-images.githubusercontent.com/19597708/175664298-308f65b9-41de-4651-b434-d4ab09315a76.png)

**Comment by yusufkandemir** [comment]
It's not specific to the `list` slot nor the `files` property. It's a more generic limitation, see #13217.
