### ISSUE TITLE
[Request] Pass input/select argument to before/after handlers

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1378]
It would be very useful to pass "parent" input/select as an argument to before/after handlers, in order to access its value and props:

```
<q-select
  options="..."
  :before="[{
    icon: 'edit',
    handler: (input) => {
      this.$route.push('/people/' + input.value)
    }
  }]"
/>
```

**Comment by rstoenescu** [comment]
Hi,

In this case you want the value, right? But you have it in your vue scope and you can use it (the v-model). You can even apply a Vue ref on the select and then access it.

Adding the new prop is reduntant.

**Comment by zuck** [comment]
My use case is inside a component called **Repeater** which basically accepts a delegate component and the props to be passed to each instance of it.

The point is that at declaration time (passing delegate component and delegate's props to Repeater), it's hard to access to the final rendered instance inside given handler, e.g.:

```
<repeater
  :delegate="delegateComponent"
  :props="{
    before: () => { /* HERE */ }
  }"
/>
```

Probably I can just use **refs** as you suggested...I'll try!
