### ISSUE TITLE
Request: How to charge q-uploader with previously images uploaded for edit pourposes?

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1379]
Hi.

I'm using q-uploader to upload images of the products, and is work fine.

But, in another day, when i need to edit this document, i do not know how do it with q-uploader.

Are there any way to charge images to q-uploader for CRUD pourposes?

Can you help me?

Tanks.

**Comment by rstoenescu** [comment]
Hi,

I'm not sure what you mean. Help me understand. QUploader is meant only for uploading files. Once they are uploaded, it's developer's task to do something with them or later retrieve them from the server etc... If the latter is your case, please close as this is not QUploader's responsibility.

Please explain in a detailed way what you are trying to do, but take into account the above words.

Thank you.

**Comment by LuizLeite** [comment]
Yes.
Its runs very well.
I have an CRUD operation, for INSERT pourposes is OK with q-uploader.
But, when i will UPDATE, i have two controls to use one for upload new images and another to show
lasted images uploadeds (i do with carousel).
If there is any way I can load the pre-existing images (uploaded before) in the q-uploader I would have only one component on the screen.
That's it for now.
Tanks.

**Comment by caiotarifa** [comment]
Please reopen this.

Maybe an option like `:list="['image1.jpg', 'image2.jpg']"` to add files to the component list.

**Comment by azabroflovski** [comment]
> Please reopen this.
> 
> Maybe an option like `:files="['image1.jpg', 'image2.jpg']"` to add files to the component list.

+ it would be nice, otherwise you need to write a wrapper

**Comment by roman-tiukh** [comment]
++

**Comment by infinite-system** [comment]
++ I need this too, is there a way, or I have to overwrite the list template manually?

**Comment by litvinenkow** [comment]
you can use my implementation of this (sorry, now it uploads only one file, but you can implement uploading of multiple)
just rename FileUploader.txt to .vue
and FileUploaderWrapper.txt to .js
[FileUploader.txt](https://github.com/quasarframework/quasar/files/13715915/FileUploader.txt)
[FileUploaderWrapper.txt](https://github.com/quasarframework/quasar/files/13715918/FileUploaderWrapper.txt)
import FileUploader.vue and use it like this depending on what your backend returning maybe you need to change some lines
it's a little bit dirty now) but i hope you will know now where to dig
maybe later when i'm fill it with multiple files upload function i post here a wrapper repository
```
<template>
<FileUploader
    v-model="yourComputed"
    @fileUploaded="yourHandlerWhenUploaded"
  />
</template>

<script setup>
const yourComputed= ref(); // or computed

const yourHandlerWhenUploaded = function($event) {
 // here you do with event everything you need like so
yourComputed.value = $event;
}
</script>
```

**Comment by lee1994522** [comment]
Really need this feature, hope for a solution.Adding a prop like "files" or "initial-files" will be the best.

**Comment by AlexDaniel** [comment]
@rstoenescu I know that this is 8 years old, but please reopen. Use case is simple – when the user returns to the same page (e.g. draft) they're supposed to see previously uploaded images. As they should be able to remove existing ones and upload new images, it's not wise to show previously submitted images separately.
