### ISSUE TITLE
QSelect Label doesn't float after updateInputValue

### ISSUE THREAD

**Issue by gruppler** [quasarframework/quasar#13801]
### What happened?

When using the `updateInputValue` method on a QSelect with `use-input` the label does not float upward, so it overlaps the input text.

### What did you expect to happen?

The label should float after calling `updateInputValue`.

### Reproduction URL

https://codepen.io/gruppler/pen/WNzeWdL

### How to reproduce?

1. Go to the codepen, observe the label

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.4 and v1.19.3
