### ISSUE TITLE
Flex Addon points to css instead of sass

### ISSUE THREAD

**Issue by msamara** [quasarframework/quasar#13811]
### What happened?

When enabling Flex Addon through cssAddon: true in quasar.config.js this line gets added automatically to the client-entry file

```
// We add Quasar addons, if they were requested
import 'quasar/src/css/flex-addon.css'
```

However flex-addon.css does not get added to the above location, instead I see flex-addon.sass

This will cause the following error to appear when running

```
Module not found: Can't resolve imported dependency "quasar/src/css/flex-addon.css"
Did you forget to install it? You can run: npm install --save quasar/src/css/flex-addon.css
```

### What did you expect to happen?

Correct file name to be added

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

Compile

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
There is no place referencing the .css variant in our Quasar vue cli plugin (v5.0.1 is latest).
Please supply a reproduction repo otherwise we can't help you. You may be using an old version of the plugin or manually requesting that .css variant.
