### ISSUE TITLE
Ajax Bar with Routes Lazy Loading Question or Request

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1381]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: 9.3
NPM: 5.5.1
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
No errors
### What were you expecting?
I expect to see the Ajax Bar when Webpack loading the route.
### What steps did you take, to get the error?
Hi,

Since our app makes a lot of Ajax calls I was not able to be sure if the Ajax Bar appear when loading a route using the lazy loading feature, so is the Ajax Bar appear when Webpack loads the route? if no please how we make it appear?

All the best,
Mohammed

**Comment by rstoenescu** [comment]
Hi,

The pages/layouts are loaded by Webpack through JSONP and not Ajax, so it won't capture that too. However, you can use Vue Router's  navigation guards to connect with QAjaxBar's start/stop methods (start increments number of current loading resources, stop decrements that number, so you can call multiple start or multiple stop at once). In order to connect the QAjaxBar's methods with Vue Router's navigation guards use a store/vuex prop, watch on it on the vue template where you have QAjaxBar defined and call the methods on the vue ref. Wish this was easier, but due to how Vue Router + Webpack works, it's currently a limitation. Will try in the future to further research on how to ease this and probably automate it.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu 

Thank you for the instructions, here is my current working code in case if anyone face the same issue.

In the main.js I have the follwing:
```
router.beforeEach((to, from, next) => {
  store.commit('loadingRoute', true);
  next()
})

router.afterEach((to, from) => {
  store.commit('loadingRoute', false);
})
```

In the guards that may prevent the user from accessing them depends for example if the user is authenticated or no I put the following:
`store.commit('loadingRoute', false);
`
In the App.vue's template I put the QAjaxBar:
`<q-ajax-bar ref="bar" color="purple-6" size="2px" :reverse="true" :delay="0" />`

And I watch the vuex's loadingRoute

```
  watch: {
    loadingRoute(status) {
      if (status) {
        this.$refs.bar.start();
      } else {
        this.$refs.bar.stop();
      }
    }
  }
```

**Comment by zouyaoji** [comment]
@MohammedAl-Mahdawi 
hi, I refer to your code , In my App.vue's:
`<template>
  
  <div id="q-app" class="songluck">
    <q-transition enter="fadeIn" leave="fadeOut" mode="out-in" :duration="300" @leave="resetScroll">
      <router-view />
    </q-transition>
    <q-ajax-bar ref="bar" color="red" size="2px" :delay="0" />
  </div>
</template>

<script>
import { mapGetters } from 'vuex'

export default {
  name: 'q-app',
  methods: {
    resetScroll (el, done) {
      document.documentElement.scrollTop = 0
      document.body.scrollTop = 0
      done()
    }
  },
  computed: {
    ...mapGetters({
      isLoadingRoute: 'getIsLoadingRoute'
    })
  },
  watch: {
    isLoadingRoute (status) {
      console.log(status)
      if (status) {
        this.$refs.bar.start()
      }
      else {
        this.$refs.bar.stop()
      }
    }
  }
}
</script>
<style>
</style>`

and in my router.js's:
`// 全局路由配置
// 路由开始之前的操作
router.beforeEach((to, from, next) => {
  store.commit('setIsLoadingRoute', true)
  next()
})

// 路由完成之后的操作
router.afterEach((to, from) => {
  store.commit('setIsLoadingRoute', false)
})`

Just a few times before you can see it, then it doesn't work.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @zouyaoji

I think it is a normal behavior, it happens to me as well, since the route has been downloaded then the process will be too fast in order to be noticed by us.

You can check if it is working or no using the console.log()

Regards

**Comment by zouyaoji** [comment]
@MohammedAl-Mahdawi 
hello, I get it,  Thanks,
Best wish
