### ISSUE TITLE
Active Colors Not Showing for Breadcrumbs

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#13827]
### Discussed in https://github.com/quasarframework/quasar/discussions/13824

<div type='discussions-op-text'>

<sup>Originally posted by **Cassianky** June 30, 2022</sup>
![Screenshot (160)](https://user-images.githubusercontent.com/77654564/176578343-4ce1bdaa-cf66-4a34-825d-07086945d389.png)

This is a comparison of the v1 and v2 quasar documentation regarding breadcrumbs. Even though the sample code is identical, but the active colours for breadcrumb is not showing for v2 quasar documentation. I saw a similar thread that was resolved with the update offered in quasar v (link: https://github.com/quasarframework/quasar/issues/11959). But I could replicate the error in quasar v2.7.1 as well. 

I'm a beginner in quasar so I'm not sure if my usage of breadcrumbs like in the documentation/link is correct. Thanks in advance.</div>

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.5
