### ISSUE TITLE
Allow to also pick seconds in DatetimePicker

### ISSUE THREAD

**Issue by KammererTob** [quasarframework/quasar#1382]
Currently the Datetime component only allows to pick hours and minutes. Some applications need more fine grained selections in terms of seconds. Would it be possible to allow that optionally?
Not sure how this would be integrated as an optional selection, because it would not apply to the type "date". Otherwise i think the implementation should be relatively straight forward and i could maybe create a pull request if approved.

**Comment by m-swift** [comment]
I set this up in a fork, although my updates use seconds as an always-on feature.

Maybe use a boolean flag like `:seconds='true'`?

**Comment by rstoenescu** [comment]
Done for v1.0.
