### ISSUE TITLE
q-select cannot autofocus in a q-dialog

### ISSUE THREAD

**Issue by Cassianky** [quasarframework/quasar#13831]
### What happened?

Autofocus prop does not work for q-select in q-dialog component (for quasar v2.7.1 and v.1.19).

### What did you expect to happen?

In v1.15 Quasar, the autofocus prop for q-select works. However, in v1.19 and v2.7.1 quasar, the autofocus no longer works for q-select in a q-dialog component.

### Reproduction URL

https://codepen.io/cassianky/pen/dymPQpg

### How to reproduce?

1. In v1.19 or v2.7.1, simply copy the sample code for q-dialog from documentation and add a q-select component in q-dialog. 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.5 and 1.19.4

**Comment by maven1129** [comment]
@rstoenescu this still doesn't work on iOS. When dialog pops on focus, is does not focus the input, and is not intuitive to have to tap in again for users.  Behavior on Android is as expected - tapping on input does focus the dialog version of the input.  Not sure if this is the same issue or not - if not please open new issue.

https://user-images.githubusercontent.com/7674880/204901969-30dc2a46-ee13-4429-b84c-48950cdf5b47.mov

**Comment by dehmlowm** [comment]
> @rstoenescu this still doesn't work on iOS. When dialog pops on focus, is does not focus the input, and is not intuitive to have to tap in again for users. Behavior on Android is as expected - tapping on input does focus the dialog version of the input. Not sure if this is the same issue or not - if not please open new issue.
> 
>  RPReplay_Final1669840038.mov

Bump^^
Same issue in 2.12.3.

When you tap the select it does not autofocus the dialog input.
