### ISSUE TITLE
[Vite PWA] no caching of index.xxxx.js file with the Dialog plugin enabled

### ISSUE THREAD

**Issue by wactrum** [quasarframework/quasar#13842]
### What happened?

When building a project with the -d flag (quasar build -m pwa -d) and the included Dialog plugin

In the file automatically generated using generate SW -> sw.js , there is no cache of the main index.js file

### What did you expect to happen?

Caching of this index.js file

### Reproduction URL

https://github.com/wactrum/wactrum.github.io

### How to reproduce?

# Fast
Go to the repository and click on 'Go to example'
View the console and pay attention to the file index.ca91cb47.js, it is not handled by Service Worker

The link leads to github pages, I just don't know how else to reproduce the error with PWA

# Local
1. run npm init quasar, select CLI with Vite + i18n + typescript, add 'Dialog' in plugins, and build with the quasar build -m pwa -d command
2. run quasar serve to your build folder

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Plugins (quasar), PWA Mode

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Quasar info output

```Shell
Operating System        Darwin(21.5.0) - darwin/arm64
NodeJs                  14.19.1

Global packages         
  NPM                   6.14.16
  yarn                  1.22.11
  @quasar/cli           1.2.2
  @quasar/icongenie     2.5.2
  cordova               Not installed

Networking              
  Host                  iMac.local
  en1                   ##########
```

### Relevant log output

```Shell
// Quasar plugins
plugins: [
 'Dialog',
],

// package.json
{
  "name": "####",
  "version": "0.0.1",
  "description": "###",
  "productName": "###",
  "author": "####",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.ts,.vue ./",
    "dev": "quasar dev -m pwa",
    "build:dev": "quasar build -m pwa -d"
  },
  "dependencies": {
    "@quasar/extras": "^1.14.0",
    "@sentry/tracing": "^7.2.0",
    "@sentry/vue": "^7.3.0",
    "@vuelidate/core": "^2.0.0-alpha.41",
    "@vuelidate/validators": "^2.0.0-alpha.29",
    "@vueuse/core": "^8.6.0",
    "axios": "^0.27.1",
    "pinia": "^2.0.14",
    "quasar": "^2.7.3",
    "vue": "^3.2.37",
    "vue-i18n": "^9.2.0-beta.36",
    "vue-router": "^4.0.0",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.4.0",
    "@quasar/app-vite": "^1.0.0",
    "@types/node": "^12.20.21",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "autoprefixer": "^10.4.2",
    "dotenv": "^16.0.1",
    "eslint": "^8.17.0",
    "eslint-plugin-vue": "^9.1.0",
    "typescript": "^4.7.3",
    "workbox-build": "^6.5.0",
    "workbox-cacheable-response": "^6.5.0",
    "workbox-core": "^6.5.0",
    "workbox-expiration": "^6.5.0",
    "workbox-precaching": "^6.5.0",
    "workbox-routing": "^6.5.0",
    "workbox-strategies": "^6.5.0"
  },
  "engines": {
    "node": "^18 || ^16 || ^14.19",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}
```

### Additional context

Is there a way to add this file yourself while this error is being discussed?

**Comment by wactrum** [comment]
I was able to find a workaround by manually turning off sourcemap when building with the -d flag

**Comment by adarshmadrecha** [comment]
@wactrum you can close this issue?
