### ISSUE TITLE
qtab flickering inside qtoolbar

### ISSUE THREAD

**Issue by botura** [quasarframework/quasar#13847]
### What happened?

In a very specfic use case (qtab inside qtoolbar), qtab arrow starts flickering. I think is it related to `mobile-arrows` and `outside-arrows` properties. The arrow is constatilly showed and hidded, depending on qtoolbar width, given this annoying flicker effect.

### What did you expect to happen?

Render a nice qtab

### Reproduction URL

https://codepen.io/botura/pen/MWVwKdx?editors=1000

### How to reproduce?

1. go to the link provided above
2. you shoud see both qtab flickering
3. remove line `style="width: 533px"`
4. the flickering is gone
5. reduce browser width, as you get around 550px is starts flickering and stop at about 510px

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari

### Additional context

I saw this problem since a long time ago (quasar1), but I thought it was something wrong with my code.

**Comment by pdanpdan** [comment]
I'm not very sure there is something that can be done in this case (except using inside arrows), because the 2 tab sets each change the available space for the other

**Comment by botura** [comment]
Will use inside arrows. Tks @pdanpdan .

**Comment by pdanpdan** [comment]
I'll close this one - I don't think there is something generic that can fix something like this, and an acceptable workaround is available.
