### ISSUE TITLE
[Component] carousel arrow icon style

### ISSUE THREAD

**Issue by Sapphire2k** [quasarframework/quasar#1384]
### Software version

Quasar: 0.14.7
OS: OSX 10.11.6
Node: v9.2.0
NPM: v5.5
Browsers: Chrome v64

### What did you get as the error?
Use the Carousel Component
When i reload the page, showing the arrow icon name firstly, seems that it was a bug and ugly T^T .
![image](https://user-images.githubusercontent.com/17328005/34662672-298c034a-f48d-11e7-978c-a6142950897d.png)

### What were you expecting?

When the page load or reload, the icon will not change..
Can u provide another way to show icon, like svg, not using font?

### What steps did you take, to get the error?
Just load or reload

**Comment by leopiccionia** [comment]
Are you with `Disable cache` option set on Chrome DevTools? By default, fonts would be cached and this "glitch" wouldn't happen even in very slow networks.

**Comment by rstoenescu** [comment]
Please reopen with an answer to leopiccionia. Thanks.
