### ISSUE TITLE
@click.stop on template slot of q-select does not prevent the menu to open. 

### ISSUE THREAD

**Issue by Qualzz** [quasarframework/quasar#13855]
### Description

Hello devs of Quasar. 

The documentation mentions that: 

` <q-select clearable filled color="purple-12" v-model="model" :options="options" label="Label" />`

is the equivalent of 

 
      <q-select color="orange" filled v-model="model" :options="options" label="Label">
        <template v-if="model" v-slot:append>
          <q-icon name="cancel" @click.stop="model = null" class="cursor-pointer" />
        </template>
      </q-select>

but despite having a `@click.stop`, clicking on the icon is triggering the menu of the q-select (which shouldn't happen) while this is not the case for the first exemple. 

I'm not sure if it's intented, if this should be in docs-report or if this is a bug. 
 

### Documentation Section URL

https://quasar.dev/vue-components/select#clearable

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
It also needs `.prevent` - if you can please make a PR for the docs (text and example)
https://codepen.io/pdanpdan/pen/XWEmWpM?editors=1010
