### ISSUE TITLE
[FR] disabled QSelect to appear similar to disabled QInput by default

### ISSUE THREAD

**Issue by frankbrussel** [quasarframework/quasar#1385]
Could also be seen as a bug. however, the current behavior is in line with the documentation, so I assume this should be a feature request.

A disabled Qselect has (by default) black text. A disabled QInput has (by default) grey text. I think the grey is better, it better signals the user that the Input or Select is unavailable. Currently, a list of disabled QInputs with a QSelect between them could confuse the user: thinking the Qselect is not disabled. I think it would be better if the QSelect and QInput have the same appearance (=> grey) when disabled (by default, without custom styling).

**Comment by realcarbonneau** [comment]
I noticed that also and just double-checked.  Here are the screen shots of the problem and the fix in pull request #1390

**Comment by rstoenescu** [comment]
Merged PR. Thanks!
