### ISSUE TITLE
QChip's Icon css issue in rtl mode.

### ISSUE THREAD

**Issue by zta7** [quasarframework/quasar#13856]
### What happened?

An unexpected  margin-right setted on Qchip's icon in rtl mode.
![image](https://user-images.githubusercontent.com/30122066/177074618-c7b42d38-2e37-4e5f-80e1-f711409787d3.png)

### What did you expect to happen?

.

### Reproduction URL

https://codepen.io/zta/pen/mdxJNdb?editors=101

### How to reproduce?

.

### Flavour

UMD

### Areas

Components (quasar)

**Comment by zta7** [comment]
And QSelect also has this problem too. [https://codepen.io/zta/pen/wvmaVxe?editors=101](url)
![image](https://user-images.githubusercontent.com/30122066/177077357-eb759719-c7ce-4400-a3a3-188f30d15cb7.png)
Both cases they all take [dir='ltr'] or [dir='right'] affected.
![image](https://user-images.githubusercontent.com/30122066/177077490-06e4d011-6d5c-4cc7-9f25-53febf715bcd.png)

**Comment by pdanpdan** [comment]
Hello. All RTL/LTR is done for using one direction only, set on the `<html>` tag.
If you have `dir="ltr"` on `<html>` and `dir="rtl"` on a child then you'll get problems.

**Comment by zta7** [comment]
Ok, That's how it works.
