### ISSUE TITLE
Native scrolling?

### ISSUE THREAD

**Issue by george-kar** [quasarframework/quasar#1386]
Are there any plans to add native scrolling on Quasar? Its the only thing that holds me back from choosing Quasar instead of Framework7.

**Comment by rstoenescu** [comment]
Hi,

The old layout in v0.13 used flexbox which in turn hindered the use of native scrolling. But in v0.14 it's not the case anymore. You only use the native scrolling now.

If you want to switch from Framework7, it might be worth-wile to wait a little bit longer as v0.15 will be out of the oven this month. Major improvements in all areas, including the developer experience when building mobile apps.
