### ISSUE TITLE
QTime model value update behaves differently in Quasar v1 and Quasar v2

### ISSUE THREAD

**Issue by flopail** [quasarframework/quasar#13872]
### What happened?

Hi, I'm upgrading my app from Quasar v1 to v2. And I note a change in QTime on event @update:model-value (or event @input in v1). In v1, the model value is updated once we both modify hours and minutes. In v2, model value is updated when we select hours, without awaiting minute selection.

This becomes a problem when we use QTime with a QInput and a QPopupProxy with an auto-close behavior on event @update;model-value. Indeed, popup closes once hours are selected and before minute selection.

Thanks you very much for your feedback.

### What did you expect to happen?

I expect QTime to have the same behavior such as Quasar v1.

### Reproduction URL

https://codepen.io/flopail/pen/OJvyZem

### How to reproduce?

To see difference, you just have to look at model update (in mask section example) during hour selection in both docs (v1 and v2). Please find these ones below:
- Quasar v1 : https://v1.quasar.dev/vue-components/time#model-mask
- Quasar v2: https://quasar.dev/vue-components/time#model-mask

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by MilosPaunovic** [comment]
Perhaps this could shed some light to your request:
[https://github.com/quasarframework/quasar/issues/13562#issuecomment-1169799907](https://github.com/quasarframework/quasar/issues/13562#issuecomment-1169799907)

**Comment by flopail** [comment]
Hi Milos and thank you for your answer. I didn't find this issue before posting. Sorry for the duplicated issue. I think it could be good to have a prop (a boolean for example) to manage both cases (v1 behavior and v2 behavior). In the meanwhile, adding it in upgrade guide smells like a good idea. :)
