### ISSUE TITLE
Min-width not specified

### ISSUE THREAD

**Issue by WCN-llc** [quasarframework/quasar#13888]
### What happened?

Hi,
Works on all breakpoints.
@media (min-width: 0)
.q-mt-xs-xl {
    margin-top: 48px;
}
@media (min-width: 0)
.q-mb-xs-md {
    margin-bottom: 16px;
}
@media (min-width: 0)
.q-px-xs-md {
    padding-left: 16px;
    padding-right: 16px;
}

### What did you expect to happen?

Correct work, according to breakpoints.

### Reproduction URL

No

### How to reproduce?

Set up by yourself.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Hello. Please use words to explain what is your problem.
We will reopen if there is a proper explanation of the problem.

**Comment by WCN-llc** [comment]
> Hello. Please use words to explain what is your problem. We will reopen if there is a proper explanation of the problem.
Hello.
I specified in the component settings:  
q-mt-xs-xl 
q-mb-xs-md 
q-px-xs-md
add margins for screen size Up to 599px.
But the added margins are visible on screens of all sizes.
Сhecked css - width not set: media (min-width: 0)
media (min-width: 0)
.q-mt-xs-xl {
margin-top: 48px;
}
media (min-width: 0)
.q-mb-xs-md {
margin-bottom: 16px;
}
media (min-width: 0)
.q-px-xs-md {
padding-left: 16px;
padding-right: 16px;
}

**Comment by pdanpdan** [comment]
Quasar uses a mobile first approach to CSS, and all breakpoints are arre applied in the order of screen width increase (xs -> sm -> md -> lg -> xl)

xs is the same as no breakpoint qualifier

**Comment by WCN-llc** [comment]
> Quasar uses a mobile first approach to CSS, and all breakpoints are arre applied in the order of screen width increase (xs -> sm -> md -> lg -> xl)
> 
> xs is the same as no breakpoint qualifier

Hello.
.q-mt-xs-xl - this is specified in the Quasar styles and says this:
.q - Quasar;
mt - margin-top;
xs - on screens up to 599px;
xl - 48px.
but xs is not set 599px (media (min-width: 0))
so 48px is shown on screens of all sizes: xs -> sm -> md -> lg -> xl

**Comment by pdanpdan** [comment]
Ah, the docs are worded wrong

**Comment by WCN-llc** [comment]
It happens.
Prosperity to your team!
