### ISSUE TITLE
IE9 support for docs

### ISSUE THREAD

**Issue by plievone** [quasarframework/quasar#139]
Hi, would you consider adding necessary polyfills for docs to work in IE9? I haven't looked into the internals yet, but I suspect at least `classList` is needed, if you use it directly. I'm ok with some visual layout errors but it would be nice to be able to experiment with quasar via BrowserStack, now it throws an error.

I will also experiment with some polyfills locally, but adding them to docs would benefit more people.

**Comment by rstoenescu** [comment]
Sure, will do. Maybe you can help a little to supply some polyfills in your own investigation? That would speed things up. Thanks!

**Comment by plievone** [comment]
I'll investigate and report here, thanks!

**Comment by rstoenescu** [comment]
I've been working like a machine these last few days for v0.8... my schedule was only sleep and programming. I'm very exhausted, so any help is appreciated :)

**Comment by plievone** [comment]
Ok, got it working in IE9 mostly without js errors. Layout for docs work fine, but framework components are all over the place, there's some general styling issue I guess and some pretty major visual errors preventing some components being used. In my brief testing, Javascript errors could be prevented with these three modifications:

`Element.classList`. Polyfilled with some general classList script. But note that vue.js doesn't need a polyfill, perhaps Quasar could follow similar route or document that it is needed: https://github.com/vuejs/vue/blob/ae93d2b/src/platforms/web/runtime/class-util.js

`Element.dataset`, which is IE11 only, but luckily quasar only reads from dataset so it could be somewhat polyfilled with some general dataset script utilizing getters. Maybe you could use data-* attributes directly or document that it is needed. It is used in a couple of places here: https://github.com/rstoenescu/quasar-framework/blob/1d7e6f9/src/utils/store.js#L7

`Array.prototype.find` which is a ES2015 feature and not available in IE11. Could be polyfilled with some general Array.prototype.find script. So that should be documented. It is used in some or all of these lines:
https://github.com/rstoenescu/quasar-framework/blob/c569360/src/vue-components/tab/Tabs.vue#L173
https://github.com/rstoenescu/quasar-framework/blob/c569360/src/vue-components/select/DialogSelect.vue#L61
https://github.com/rstoenescu/quasar-framework/blob/c569360/src/vue-components/select/Select.vue#L128

In some of those places where Array.prototype.find is used, does it also use Array.prototype.includes, which is ES2016, but I didn't come across those error yet.

**Comment by rstoenescu** [comment]
Array.prototype.find() polyfill will be available in Quasar v0.11 to be released soon.

**Comment by rstoenescu** [comment]
Ok, some words on this. Due to the lack of some important CSS features, sorry but IE 9 and 10 won't be supported. Support will be available for IE11+ & Edge.
