### ISSUE TITLE
i18n vite config issues.

### ISSUE THREAD

**Issue by tmikaeld** [quasarframework/quasar#13908]
### What happened?

$t doesn't work to work in templates after generating a new project with i18n from quasar-cli with Vite.

### What did you expect to happen?

$t and this.$t to work.

### Reproduction URL

not needed

### How to reproduce?

Generate a new quasar project with vite and i18n using Quasar CLI

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Plugins (quasar)

### Quasar info output

```Shell
i18n.f51426e2.js:603 Uncaught TypeError: messageCompiler is not a function after build
```

### Relevant log output

```Shell
i18n.f51426e2.js:603 Uncaught TypeError: messageCompiler is not a function after build
```

## Solution:

1. `createI18n` needs to be configured with `globalInjection: true` or $t will not work in projects.
2. `vite-plugin-vue-i18n` needs to be configured with `runtimeOnly: false` or will shoot `messageCompiler is not a function` after building.

**Comment by Freespacer** [comment]
Hi @all,

I have similar issue with Quasar and Vite with vue-i18n. The calling of global shortcut method $t() is not provided some versions of vue-i18n (9.0 and 9.1) for Vue 3 by default. In future versions (vue-i18n v9.2-beta.34 or later) it will be enabled again by default.

See: https://vue-i18n.intlify.dev/guide/advanced/composition.html#implicit-with-injected-properties-and-functions

For the moment you can enable global injection in /boot/i18n.js with **globalInjection: true**

```
import { boot } from 'quasar/wrappers'
import { createI18n } from 'vue-i18n'
import messages from 'src/i18n'

export default boot(({ app }) => {
  const i18n = createI18n({
    globalInjection: true, // <---- this should be set to restore the old behavior
    locale: 'en-US',
    messages
  })

  // Set i18n instance on app
  app.use(i18n)
})
```
This problem also exists in the scaffolding of a new Quasar project (with vue-i18n 9.1) like:
`yarn create quasar`

In the documentation is missing the hint in 2 pages too:
https://quasar.dev/options/app-internationalization#setup-manually

https://quasar.dev/start/upgrade-guide#vue-i18n-v9

**Comment by tmikaeld** [comment]
@Freespacer Also see point 2 in my post under "solution", while `globalInjection: true` is enough to make it work in dev, it's not enough to make it work in production build.

**Comment by Freespacer** [comment]
@tmikaeld You are right! In development mode it works, but in production mode won't work. I had not yet an eye on the production build. My bad. Add `runtimeOnly: false` in quasar.config.js in the section `vitePlugins` works as you suggested.

```
            vitePlugins: [
                [
                    '@intlify/vite-plugin-vue-i18n',
                    {
                        // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
                        // compositionOnly: false,

                        // you need to set i18n resource including paths !
                        include: path.resolve(__dirname, './src/i18n/**'),
                        runtimeOnly: false,
                    },
                ],
            ],
```

Thanks for pointing this out. Hopefully the maintainer can take a look at this problem and add this in the scaffolding quasar project and in the documentation.
