### ISSUE TITLE
(Accessibility) No navigation possible in QDate and QTime in Quasar V2

### ISSUE THREAD

**Issue by pieterzeilstra** [quasarframework/quasar#13932]
### What happened?

In Quasar 1 you are able to tab inside each element in QTime and QDate.
In Quasar 2 you just skip QDate and QTime when tabbing.

### What did you expect to happen?

I expect this functionality to work the same accros both quasar functions. I see there are still accessibility updates in Quasar 1 so it would be nice if was the same accross both versions.

### Reproduction URL

https://codepen.io/pieterzeilstraparantion/pen/QWmKyey?editors=101

### How to reproduce?

https://codepen.io/pieterzeilstraparantion/pen/QWmKyey?editors=101 for Quasar1
https://codepen.io/pieterzeilstraparantion/pen/wvmzMVv?editors=101 for Quasar2

Just try to press tab on both versions and see the difference.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
fixed in Qv2.11.6
