### ISSUE TITLE
q-route-tab/qRouteTab doesn't show as active when the route includes a parameter

### ISSUE THREAD

**Issue by Gnopps** [quasarframework/quasar#13931]
### What happened?

q-route-tab/qRouteTab doesn't show as active when the route includes a parameter. 

`<q-route-tab to="/pageOne">` will show as active when you access "/pageOne" but not when you access "/pageOne/myID" if it is defined with a parameter in routes, for example as "/pageOne/:id". 

### What did you expect to happen?

q-route-tab should show as active also when the route accessed contains a parameter.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-6k7m1s?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to reproduction link
2. Click on buttons to go to pages one, pages one with child and page two. Note that all of them show the q-router-tab as active.
3. Click on button to go to page two with a parameter. Note that the q-router-tab for page two remains inactive.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System - Linux(5.0 (Windows)) - linux/x64
NodeJs - 16.14.2

Global packages
  NPM - 7.17.0
  yarn - 1.22.10
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.12.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - quasarframework-6k7m1s
  en0 - 192.168.1.104
```

**Comment by pdanpdan** [comment]
PageTwo with parameter is not a child of PageTwo route, it's a parallel branch, so when the route with :id is active the one without is not active

**Comment by 54mu3l** [comment]
### The Problem:
I think with optional parameters this really is a problem/bug.

> PageTwo with parameter is not a child of PageTwo route, it's a parallel branch, so when the route with :id is active the one without is not active

Yes, in the provided reproduction URL PageTwo with parameter is not a child of PageTwo. **But** let me give you another example where I think this really is a problem/bug.

Just edit `routes.js` and combine these to routes.

Old:
```javascript
{
    path: '/pageTwo',
    component: () => import('pages/pageTwo.vue'),
},
{
    path: '/pageTwo/:id',
    component: () => import('pages/pageTwo.vue'),
},
```
New:
```javascript
{
    path: '/pageTwo/:id?',
    component: () => import('pages/pageTwo.vue'),
},
```

(Reproduction URL: https://stackblitz.com/edit/quasarframework-6hxcaz?file=src%2Frouter%2Froutes.js)

The route is now _technically one route_ and therefore the QRouteTab (or QItem in my case) should be highlighted (with or without parameter).


### Use Case:
For us it's quiet common to have optional parameters for a page and the parameters are used to store the current selection (with no parameter it falls back to the default selection). And the QRouteTab/QItem loosing the `q-router-link--active` class breaks the UI.

Maybe it makes sense to reopen this issue?

**Comment by doox911-opensource** [comment]
This is definitely a bug!

I have routes:

```
http://localhost/operational (first tab)
http://localhost/boot (second tab)

```

But if I have a route with an ID (http://localhost/boot/12 ), then the tabs do not work correctly (the first tab is always active).

The above example perfectly demonstrates this.

```
"dependencies": {
    "@quasar/cli": "^2.3.0",
    "@quasar/extras": "^1.16.4",
    "axios": "^1.2.1",
    "pinia": "^2.0.11",
    "quasar": "^2.6.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0"
  },
  "devDependencies": {
    "@openapitools/openapi-generator-cli": "^2.7.0",
    "@quasar/app-vite": "^1.3.0",
    "@types/node": "^12.20.21",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "autoprefixer": "^10.4.2",
    "eslint": "^8.10.0",
    "eslint-config-standard": "^17.0.0",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-vue": "^9.0.0",
    "typescript": "^4.5.4"
  },
```

**Comment by pdanpdan** [comment]
Can we have a repro that works and shows the problem?

**Comment by doox911-opensource** [comment]
> Can we have a repro that works and shows the problem?

https://stackblitz.com/edit/quasarframework-nfoddo?file=src%2FApp.vue

When I click on a static link (without an ID), the tabs correctly become active, but when there is a dynamic parameter (ID) in the link, the tab is not detected and  tab `Home` is always active.

**Comment by pdanpdan** [comment]
It is because as I have already said you are using routes that are on the same level.
The matched routes for each of your routes are [`/`, `routeX`] and [`/`, `routeX/:id`]

https://stackblitz.com/edit/quasarframework-etf99w?file=src%2Frouter%2Froutes.js

**Comment by doox911-opensource** [comment]
> It is because as I have already said you are using routes that are on the same level. The matched routes for each of your routes are [`/`, `routeX`] and [`/`, `routeX/:id`]
> 
> https://stackblitz.com/edit/quasarframework-etf99w?file=src%2Frouter%2Froutes.js

Thank you. I think it should be described in the documentation and attach an example.

**Comment by pdanpdan** [comment]
It is basic VueRouter - it is in their docs.

@54mu3l 
And about the case with one route with optional path param - use named routes (I have updated the codepen).

**Comment by 54mu3l** [comment]
> It is basic VueRouter - it is in their docs.

Yes 100% what @doox911-opensource is describing is normal VueRouter behavior.

> @54mu3l And about the case with one route with optional path param - use named routes (I have updated the codepen).

Perfect thank you! We actually already use named routes everywhere in the project - except for the menu (since it's autogenerated). Thank you, we'll change that now.

For everyone else wondering. This works:
```javascript
<q-route-tab :to="{ name: 'pageTwo' }" label="Two" />
```
