### ISSUE TITLE
It is no longer possible to navigate Qslider with keyboard.

### ISSUE THREAD

**Issue by pieterzeilstra** [quasarframework/quasar#13943]
### What happened?

After updating to Quasar 2.7.5 or Quasar 1.19.4. It is no longer possible to navigate and change the value of the QSlider only using the keyboard. I some aria properties in QSlider are changed in the newest version so the problem probably lies somewhere there.

### What did you expect to happen?

I expect that i can change the value of the slider using a keyboard the same way it is possible in QKnob.

### Reproduction URL

https://codepen.io/pieterzeilstraparantion/pen/OJvRwxj?editors=101

### How to reproduce?

In the reproduction link try to change the value using the keyboard.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by Saeid-Za** [comment]
Hello, I can still change the value of `q-slider` with navigation keys. but first I have to click somewhere on the component to focus on it.

**Comment by pieterzeilstra** [comment]
Very strange it was not working for me a couple of day ago but now it does work. Sorry for the issue!
