### ISSUE TITLE
Custom Scss variable not work on q-btn color props

### ISSUE THREAD

**Issue by manimovassagh** [quasarframework/quasar#13953]
### What happened?

Base on the documentation i defined new scss variable in quasar.variable.sccc as follows.
$somevariable: #2e7b99;
then i want to use it inside q-btn
<q-btn color="somevariable"></q-btn>
what happend is for a les than a second the color change and immediatly it goes like no color.

### What did you expect to happen?

As in documentation it should change to new color.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-feztzq?file=src/layouts/MainLayout.vue

### How to reproduce?

Go to peovided link

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You have not defined the bg-somevariable and color-somevariable classes to tell what to do
read the docs

**Comment by manimovassagh** [comment]
Thanks a lot it worked 👍
