### ISSUE TITLE
Custom Scss variable not work on q-btn color props

### ISSUE THREAD

**Issue by manimovassagh** [quasarframework/quasar#13954]
### What happened?

base on diocumentation i have defined new Scss variable in quasar.variable.scss as follows.
$somevariable:'2e7b99;
then i eanted to use it inside q-brn instead of primary color.
but the button lost color and it is like no color .
also i have found that  if i **edit the predefined scss** variable inside quasar color pallet it works but with new scss definition not working.

### What did you expect to happen?

I expect to change the style of button with new scss variable but the button lost all styles.
see in reproduction URL.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-feztzq?file=src/css/quasar.variables.scss

### How to reproduce?

Go to the provided production link

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

### Additional context

Just as info i made once this issue but i assume that accidently, i removed it. sorry if it is duplicate.

**Comment by MilosPaunovic** [comment]
As Dan suggested in https://github.com/quasarframework/quasar/issues/13953, you have to define classes with your new color variable:

```css
.bg-somevariable {
  background: $somevariable;
}

.text-somevariable {
  color: $somevariable;
}
```

**Comment by manimovassagh** [comment]
Thanks a lot it worked 👍

**Comment by aryankarim** [comment]
> As Dan suggested in #13953, you have to define classes with your new color variable:
> 
> ```css
> .bg-somevariable {
>   background: $somevariable;
> }
> 
> .text-somevariable {
>   color: $somevariable;
> }
> ```

this works but this makes the code disorganized. It's preferable if we put the new color with the rest of the colors.

**Comment by aryankarim** [comment]
changing the `/css/quasar-variables.sass` as follows makes the relevant  code more centralized
```sass
$primary   : #1976d2
$secondary : #26A69A
$accent    : #9C27B0

$dark      : #1d1d1d
$dark-page : #121212

$positive  : #21BA45
$negative  : #C10015
$info      : #31CCEC
$warning   : #F2C037

// Add .bg-<color> and .text-<color> class after new colors

$light: #EDF7F5

.bg-light
  background: $light !important

.text-light 
  color: $light !important
```
