### ISSUE TITLE
[Request] QDataTable: Search by formatted string

### ISSUE THREAD

**Issue by daniel-shuy** [quasarframework/quasar#1396]
`QDataTable` should search by formatted string instead of actual data string.

Using the demo Quasar Play App as an example, in the QDataTable example (http://v0-13.quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/data-table), the date is formatted using:
```javascript
format (value) {
    return new Date(value).toLocaleString()
}
```
but searching for the literal String `AM` in the `Date` column reveals no results, because the underlying data string is still in `YYYY-MM-DDTHH:MM:SS` format (see https://github.com/quasarframework/quasar-play/blob/v0.13/src/data/table.json).

@rstoenescu I know you've already mentioned this feature will be in v0.15. I'm submitting this as an Issue partially as a reminder for myself because I keep forgetting that I've already requested for it on Gitter.

**Comment by rstoenescu** [comment]
Hi, yes. Please don't use this space as a personal "Google Keep" :)))
