### ISSUE TITLE
Cannot unselect a node in QTree

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1397]
### Software version

Quasar:0.15
OS:Windows & Linux
Node:8.9.3
NPM:5.5.1
Browsers:Chrome & Firefox
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
In the **QTree** component, once a node is selected, we can't unselect it. I do not talk about the tick but selectable mode.

### What were you expecting?
When a node is already selected, it should be UNselected when clicked again.

### What steps did you take, to get the error?

If a node is already selected and then we click one more time on it, it remains selected instead of being **unselected**.

**Comment by rstoenescu** [comment]
Fixed by https://github.com/quasarframework/quasar/pull/1398.
Thanks for PR!
