### ISSUE TITLE
[QSelect] label not stacking with object options using `hide-selected` and `option-label` pointing to a `number`

### ISSUE THREAD

**Issue by sullyD64** [quasarframework/quasar#13985]
### What happened?

When using the `use-input` prop for enabling filtering the QSelect's options, when said options are in object form and `option-label` is used to point a property of the option which is a `number`, AND when the `hide-selected` prop is used (along with the `fill-input` prop), this happens:
![immagine](https://user-images.githubusercontent.com/26333714/179548675-caec0440-d53f-4035-913b-72707dfd2a68.png)
 
### What did you expect to happen?

Removing the `hide-selected` prop inherently fixes the problem (i removed the `fill-input` prop too, but it seems to not influence the stacking label anyway):
![immagine](https://user-images.githubusercontent.com/26333714/179550082-2bb36adb-5df1-47d0-8b60-62222debc596.png)

### Reproduction URL

https://codepen.io/sullyD64/pen/QWmpbBw

### How to reproduce?

See codepen

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Additional context

Disclaimer:
- Using `stack-label` is not a solution for me, since I want the label to stack only if there is a value selected.
- I really want to use `hide-selected` + `fill-input` since I've found out it works best for me in many scenarios, and the stacking label problem only happens in this particular edge case;

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.7.6 and 1.19.5
