### ISSUE TITLE
q-loading does not apply z-max class correctly

### ISSUE THREAD

**Issue by Phunky** [quasarframework/quasar#1399]
### Software version

Quasar: 
OS: quasar-edge
Node: v9.3.0
NPM: 5.6.0
Browsers: Chrome

### What did you get as the error?

Loading overlay is not above all elements and 'undefined' class incorrectly applied to element.

![image](https://user-images.githubusercontent.com/67351/34817730-a6fe4854-f6b0-11e7-93c2-984fbfc3b283.png)

### What were you expecting?

Loading overlay **to be above** all elements and for 'z-max' to be correctly defined without 'undefined' appending it.

![image](https://user-images.githubusercontent.com/67351/34817750-bae4c4d8-f6b0-11e7-9df0-9a778e3e14f5.png)

### What steps did you take, to get the error?

Running `quasar dev mat` and buidling.

I've fixed this by adding a space to the end of `staticClass` in quasar.esm.js in the node folder for now.

**Comment by rstoenescu** [comment]
Hi,

Already fixed this in v0.15 (which is around the corner).
Can you wait for the release or do you need this badly in v0.14? Currently focusing on bringing v0.15 out of the oven asap.

**Comment by Phunky** [comment]
Totally fine, just wanted to highlight it incase no one else had :)
