### ISSUE TITLE
Float label static on number input with undefined model

### ISSUE THREAD

**Issue by KammererTob** [quasarframework/quasar#1400]
I noticed that the float-label for an input of type="number" becomes static when the intial value of the v-model is undefined:
![image](https://user-images.githubusercontent.com/1510949/34828237-2e8e3e10-f6dd-11e7-93f9-57fc70fc0668.png)

Example code:
```
data () {
    return {
        testObj: {}
    }
}

<q-input type="number" float-label="Fei Id" v-model="testObj.feiId"></q-input>
```
If i set the value to null or an empty string it works as expected:
```
data () {
    return {
        testObj: {
            feiId: null
        }
    }
}
```

Is this a bug or expected behaviour?

Quasar: 0.14.7
OS: Windows 7 x64
Node: 6.6.0
NPM: 3.9.0
Browsers: Chrome

**Comment by rstoenescu** [comment]
Yes. It evaluates the value given, in this case '{}' which is an Object, so always true-ish. But don't make the value an object as it doesn't makes sense.

**Comment by KammererTob** [comment]
I think you might have misunderstood me. I bind a non-existing property of the empty object (testObj) to the input (testObj.feiId). Shouldn't vue-js automatically create this property? Or is the property created as an object and thus evalutes to true-ish?
