### ISSUE TITLE
[BUG] Dialog component padding-right on body

### ISSUE THREAD

**Issue by erikcunha** [quasarframework/quasar#1401]
Hi, when I simply create a Dialog : 
```
Dialog.create({
  title: 'Warning',
  message: 'You are about to run out of disk space.',
  buttons: [
    'Cancel',
    {
      label: 'Empty Trash Bin',
      handler () {
        // empty the trash bin, yo
      }
    }
  ]
})
```
it's added on tag body element some padding-right and when i close the Dialog it comes back to normal with padding-right: 0px again, any way to stop this ?

**Comment by rstoenescu** [comment]
Already fixed in future v0.15. This was a feature that eventually brought more trouble than its worth :)
