### ISSUE TITLE
Quasar not work in production (vite-plugin)

### ISSUE THREAD

**Issue by red010182** [quasarframework/quasar#14015]
### What happened?

I followed the official [guide](https://quasar.dev/start/vite-plugin) to install quasar  2.5.5 to my existing vue3 (vite 3.0.0) project.

`pnpm dev` => works perfect

`pnpm build` => Build successfully but quasar didn't active on the generated application. For example, a `<q-btn>` tag didn't translate to what it should be in production.

### What did you expect to happen?

quasar should active on production.

### Reproduction URL

https://github.com/red010182/vue3-starter/tree/quasar

### How to reproduce?

dowload quasar branch mentioned above

```
pnpm i
pnpm build
```

serve dist folder and check it out

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Platforms/Browsers

OSX/Chrome

**Comment by pdanpdan** [comment]
I don't understand, why is the issue opened here instead of in the fork repo?

**Comment by red010182** [comment]
@pdanpdan Sorry if it's not the right place to ask. But this problem also occurs in a fresh new vite project (created by vite-cli).

I found the solution: just comment out `quasar()` in vite.config.js

**Comment by CharlieDigital** [comment]
Running into the same issue.

Removing `quasar()` from `vite.config.ts` solves the issue, but I also lose all of the SASS variable customizations.

What is the right place to report this issue?

**Comment by rstoenescu** [comment]
@CharlieDigital what error are you getting? Would you be so kind to also supply a barebones reproduction repo pls?

**Comment by CharlieDigital** [comment]
@rstoenescu I went to reproduce it with a simple standalone repo and noticed that I could not.  When I ran `http-server` from the `/dist` folder, everything worked as expected.

I double checked the version dependencies.

Went back to my main project and noticed that updating the following resolved the issue:

- `@quasar/vite-plugin` from `1.2.1` → `1.2.3`
- `quasar` from `2.8.3` → `2.8.4`

In the sample reproduction project, even downgrading to the versions (deleting `/dist` and `/node_modules`) can't reproduce it.

I appreciate the attention and apologize for the false alarm! 

For future travelers, update the dep versions.

**Comment by MikesAtMIT** [comment]
@CharlieDigital I'm having the same issue as you where if I build while `quasar()` is in my `vite.config.js`, the built files still have things like `<q-btn>` in them. But if I comment it out, then it's fine but I lose my `sassVariables`. I am on `quasar 2.10.1` and `@quasar/vite-plugin 1.2.3`. Are you sure it was only a dependency problem that solved it for you?

**Comment by CharlieDigital** [comment]
@MikesAtMIT yes; 100% certain it was a version issue in my case.

I figured it out by simply trying to create a minimum reproduction of the issue by creating a new project with a clean template and worked my way backwards on the deltas.

Your case may or may not be a mis-match between versions.  I'd recommend creating a clean template and then checking the versions in `package.json` and see if it works.

**Comment by MikesAtMIT** [comment]
@CharlieDigital
I finally figured out what the problem was in my project. It was the order of the options in the vite config file:
```
// does not work
export default defineConfig({
  plugins: [
    quasar({ sassVariables: '@/assets/quasar-variables.sass' }),
    vue({ template: { transformAssetUrls }}),
  ],
})

// does work
export default defineConfig({
  plugins: [
    vue({ template: { transformAssetUrls }}),
    quasar({ sassVariables: '@/assets/quasar-variables.sass' }),
  ],
})
```
Both work fine in `npm run dev`, it's just when you `npm run build` that the first config doesn't properly build the quasar components.
