### ISSUE TITLE
Q Radio SVG is a little off center

### ISSUE THREAD

**Issue by lmarne01** [quasarframework/quasar#14010]
Hello,

This is a small observation I found while looking and working with Q radio. The bullet in smaller sizes is 1 pixel off center.
![image](https://user-images.githubusercontent.com/43149510/180229403-d915de26-7b95-4e47-be02-6ca8bee1481a.png)
It seems that 1 pixel increase of height and width in svg's ViewBox(viewBox=0 0 25 25) fixes the issue.

### What did you expect to happen?

I expected that the bullet is centered to the outer circle like this 

![image](https://user-images.githubusercontent.com/43149510/180229158-b7afad65-4a56-4936-9213-ecf753364795.png)

### Reproduction URL

https://codepen.io/loizos_darkpony/pen/QWmvzBQ

### How to reproduce?

1. Go to The provided link

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
What browser/os/..., because I cannot reproduce on Chrome/Ubuntu

**Comment by lmarne01** [comment]
I was on windows 10 Pro, Chrome when this occurred, but it seems that it doesn't do that anymore neither in the provided link nor in Chrome in general. Weird because it was doing it for the whole day when I first found this. I guess this thread issue should close
