### ISSUE TITLE
Improve Pinia example?

### ISSUE THREAD

**Issue by rowild** [quasarframework/quasar#14020]
### Description

When learning aboout how to use Pinia with Quasar, the current documentation has a little walk-through here:

https://quasar.dev/quasar-cli-vite/state-management-with-pinia

However, it is a quite strange example, since the code provided turns on/off the counter via a toggle-component, while in fact it should provide an interface and a display for a counter. 

At least that is what I would expect. If my assumption is wrong, I do not fully understand what the intention of this example is supposed to be. It works, but it does not make sense IMO. Am I wrong? If so, I'd love to to be corrected!

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/state-management-with-pinia#adding-a-pinia-store

### Areas

Plugins (quasar)

**Comment by bartduisters** [comment]
https://github.com/quasarframework/quasar/pull/14070/files
@yusufkandemir PR opened
