### ISSUE TITLE
q.platform.is.mobile return true in apps built within capacitor wrapper 

### ISSUE THREAD

**Issue by pylvr** [quasarframework/quasar#14031]
### What happened?

Describe the bug
build apps (via quasar dev -m capacitor -T android) the "$q.platform.is.mobile" return true on mobiles browsers  and within a capacitor wrapper 

### What did you expect to happen?

Expected behavior
$q.platform.is.mobile without i capacitor wrapper should return false 

### Reproduction URL

https://github.com/

### How to reproduce?

To Reproduce

    Make an app for capacitor
    Use a <div v-if=" !$q.platform.is.mobile" ></div> to hide an element on an capacitor wrapper app 
    Build it with quasar dev -m capacitor -T android to a real device or the emulator (same result)
    Notice that the element will not be hidden even though it should be
 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Capacitor Mode

### Platforms/Browsers

Android

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22000) - win32/x64
NodeJs - 16.15.1

Global packages
  NPM - 8.11.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.4 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.14.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.16
  pinia - 2.0.16 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.13 -- Native-ESM powered web dev build tool
  eslint - 8.19.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - 2.5.0 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/cli - 2.5.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 2.5.0 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Yasser
  Wi-Fi - 192.168.1.37
  vEthernet (WSL) - 172.26.160.1
```

**Comment by yusufkandemir** [comment]
An app running in Capacitor wrapper still runs in a "mobile" device, so `Platform.is.mobile` is `true`, which is correct. If you want to check for a mobile device that is not running inside Cordova/Capacitor wrapper, then use `if(!Platform.is.nativeMobile)`. I noticed this information was missing in the docs, so I added a commit to reference it. It will be available when the docs are deployed.
