### ISSUE TITLE
Height: 100% for all parents to space out content

### ISSUE THREAD

**Issue by MartinMuzatko** [quasarframework/quasar#1404]
Hello!

I noticed, that there is no styling for html elements at all (other than normalize). In order to be able to evenly space out children elements vertically, it is required to have all parent elements to be of height 100%, otherwise the container will only fill the space that is required to paint.

Is there a reason why there is no `height: 100%` applied to `body` and `html` root elements?

While there is the `.full-height` helper class, it is a little bit annoying to put it on any component that contains my content. Your thoughts?

![image](https://user-images.githubusercontent.com/2950505/34864118-00665fc2-f773-11e7-900d-3e460e35b31c.png)

**Comment by rstoenescu** [comment]
Hi, Already fixed that with the much superior layout in v0.15.
