### ISSUE TITLE
QDialog Aria-label of buttons not working in specific circumstances. (Chrome)

### ISSUE THREAD

**Issue by pieterzeilstra** [quasarframework/quasar#14056]
### What happened?

In specific circumstances the aria-label of buttons dont work inside a QDialog.
I had this issue in my own project and is aswell present in the quasar website (https://quasar.dev/vue-components/dialog#introduction). When using the codepen of the QDialog it does work correctly what is strange.

I tried to reproduce it but can't find the problem causing it and it seems to happen when you import a component with a QDialog somehow?

I also tried in firefox but there it is working normally.

(This issue is also present in Quasar 1)

### What did you expect to happen?

A screenreader should always pronounce the button name inside a dialog.

### Reproduction URL

https://codepen.io/pieterzeilstraparantion/pen/bGvobva?editors=101

### How to reproduce?

1. Go to https://quasar.dev/vue-components/dialog#introduction with a screen reader.
2. Press on a button to open a dialog and press tab.
3. You will hear 'empty' because no aria label was found.

Now go to: https://codepen.io/pieterzeilstraparantion/pen/bGvobva?editors=101
And try the same and now it will work!

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
I tried and I cannot reproduce, sorry
If it's still happening please reopen this one and also specify OS, screen reader and whatever you can so we can reproduce it
