### ISSUE TITLE
Document this.router(Pinia) and this.$router(Vuex)

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#14068]
We are providing `this.router` for Pinia and `this.$router` for Vuex under the hood so the users can easily access the router in their stores. But, this is an undocumented feature ATM, so we need to document it.

### Documentation

We should probably create a sub-section called something like "Accessing the router", explain the properties, and show an example usage.

- [x] app-vite: #14079
	- [x] Pinia
	- [x] Vuex
- [x] app-webpack: #14079
	- [x] Pinia
	- [x] Vuex

### TypeScript definitions

- Pinia: https://pinia.vuejs.org/core-concepts/plugins.html#typing-new-store-properties
- Vuex:
	```ts
    declare module "vuex" {
      export interface Store<S> {
        readonly $router: Router;
      }
    }
	```

- [x] Templates for app-vite&app-webpack
	- [x] Pinia: #14062
	- [x] Vuex: #14080
- [x] Templates for create-quasar
	- [x] Pinia: #14080
	- [x] Vuex: #14080

**Comment by yusufkandemir** [comment]
@rashidpathiyil would you be willing to give this a go, at least partially, since you created #14062?

**Comment by rashidpathiyil** [comment]
I will try

**Comment by rashidpathiyil** [comment]
Can you please review the line 28 before adding TypeScript definitions to app-vite & app-webpack templates.

![image](https://user-images.githubusercontent.com/15140041/181496717-77803813-053b-4615-a40b-fe5652ea0db4.png)

**Comment by yusufkandemir** [comment]
Thanks for handling this @rashidpathiyil 👏
