### ISSUE TITLE
about startOfDate

### ISSUE THREAD

**Issue by 332lfgb6** [quasarframework/quasar#14086]
### New Date() If you take a single number as an argument, that number represents milliseconds, not years.
Quasar1 and QuasAR2 both have this problem
![image](https://user-images.githubusercontent.com/51245335/181658994-575c3189-7606-462e-a11f-211578a79613.png)

### Documentation Section URL

https://quasar.dev/quasar-utils/date-utils#start-end-of-time

### Areas

Plugins (quasar)

**Comment by MilosPaunovic** [comment]
@332lfgb6 You are right, if the `new Date()` constructor takes single parameter and it's integer, it will parse it as milliseconds; if that single parameter is a string, it will parse it as a year.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

So, what needs to be done in the example above (both for v1 & v2 docs is to wrap `2000` in quotes. Are you willing to submit a PRs for it?

**Comment by 332lfgb6** [comment]
> @332lfgb6 You are right, if the `new Date()` constructor takes single parameter and it's integer, it will parse it as milliseconds; if that single parameter is a string, it will parse it as a year.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
> 
> So, what needs to be done in the example above (both for v1 & v2 docs is to wrap `2000` in quotes. Are you willing to submit a PRs for it?

I didn't study PR
