### ISSUE TITLE
quasar build mode electron  "Renderer" compiled with errors in linux

### ISSUE THREAD

**Issue by NouhToulali1997** [quasarframework/quasar#14095]
### What happened?

In remote server under linux, While compiling my application using electron mode (same issue using cordova mode) I got the following error :

 sudo quasar build -c --mode electron -T win32

 Build mode........ electron
 Pkg quasar........ v2.7.5
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no

 Configured browser support (>= 88.14% of global marketshare):
 · Chrome for Android >= 103
 · Firefox for Android >= 101
 · Android >= 103
 · Chrome >= 94
 · Edge >= 100
 · Firefox >= 93
 · iOS >= 13.0-13.1
 · Opera >= 82
 · Safari >= 14

 App • Cleaned build artifact: "/home/web/appli/dist/electron"
 App •  WAIT  • Compiling of "Renderer" in progress...
 App •  WAIT  • Compiling of "Preload" in progress...
 App •  WAIT  • Compiling of "Main" in progress...
(node:3709550) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/web/appli/node_modules/vuex/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
 App •  DONE  • "Main" compiled with success • 2230ms
 App •  DONE  • "Preload" compiled with success • 11009ms
 **App •  DONE  • "Renderer" compiled with errors • 22564ms**

 **App •  ERROR  •  Renderer**

**File size (2615101396) is greater than 2 GB**

 **App •  ERROR  •  Renderer**

**File size (2599305216) is greater than 2 GB**

 App •  COMPILATION FAILED  • Please check the log above for details.

otherwise, the build is working in windows correctly.

I tried fixing it by increasing file size in linux under /etc/security/limits.conf by adding : 
appli           hard    fsize   5615101396
appli           soft    fsize   5615101396
root            hard    fsize   5615101396
root            soft    fsize   5615101396
 but still not working

### What did you expect to happen?

the application should be built

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

under linux, try to generates electron build with a large application rendered file

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Electron Mode, Cordova Mode

### Quasar info output

```Shell
Operating System - Linux(5.4.0-120-generic) - linux/x64
NodeJs - 16.15.1

Global packages
  NPM - 8.11.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - 11.0.0

Important local packages
  quasar - 2.7.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.3 -- Quasar Framework local CLI
  @quasar/extras - 1.14.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.0
  vuex - 4.0.2 -- state management for Vue.js
  electron - 19.0.9 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 15.5.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 22.14.13 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @babel/core - 7.18.6 -- Babel compiler core.
  webpack - 5.73.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.4 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 6.5.4 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
Hi,

1. Why are you still on the deprecated `@quasar/app` (deprecated for Qv2) and not on the newer `@quasar/app-webpack`?
2. This is a limitation of Webpack, your Nodejs or of your filesystem. Nothing to do with Quasar CLI actually. You might want to investigate if Webpack has a setting to increase this filesize limit. Then you might try increasing the memory limit of Nodejs (`node --max-old-space-size=5120 quasar dev/build`).

Would be glad to assist you on point no. 2, but the time doesn't allow it.
