### ISSUE TITLE
if q-input set readonly from 'off' to 'on' then executing focus() without pause won't work properly

### ISSUE THREAD

**Issue by yureckey** [quasarframework/quasar#14096]
### What happened?

if q-input set readonly from 'off' to 'on' then executing focus() without pause won't work properly.
input UI not updated to focused state.
I don't know, maybe it is obvious that developer should add pause? If yes, then make sense to add this into documentation

### What did you expect to happen?

input UI updated to focused state

### Reproduction URL

https://codepen.io/yureckey/pen/gOeXKVm

### How to reproduce?

click edit icon
see that focus is partially worked - editing cursor there, but UI of input didn't changed properly
uncomment //await timeout(500);
click edit icon
see that focus work with proper UI update now

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
latest quasar
```

**Comment by pdanpdan** [comment]
Hello. It's enough to wait for nextTick.
This is normal and expected, JavaScript is single thread, so it has to finish the current executing code to update the html

**Comment by yureckey** [comment]
Ah, sorry, didn't realized that, thanks!
