### ISSUE TITLE
While trying to update quasar to version 1.19.4 I get an error

### ISSUE THREAD

**Issue by talkonadmin** [quasarframework/quasar#14112]
While trying to update quasar to version 1.19.4 I get the error:
sync-fetch@0.4.1: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.12"

I am using node v12 since this the only version supported by quasar cli 1.3.2

_Originally posted by @talkonadmin in https://github.com/quasarframework/quasar/discussions/14022_

**Comment by MilosPaunovic** [comment]
I'm using `Node@16` with `Quasar@1` for quite a while now; works like a charm. Just do the necessary Node update if you want the latest version of `v1` to work.

**Comment by talkonadmin** [comment]
> I'm using `Node@16` with `Quasar@1` for quite a while now; works like a charm. Just do the necessary Node update if you want the latest version of `v1` to work.

I have an existing project the works with webpack 4, do I need to upgrade to webpack 5?

**Comment by MilosPaunovic** [comment]
`Quasar@1` utilizes `Webpack@4`, `Quasar@2` runs with `Webpack@5`, so I you want to stay on Q1, no, no need to upgrade Webpack.

**Comment by rstoenescu** [comment]
You can safely upgrade to Node v14+.
