### ISSUE TITLE
QTime need to click twice to set time

### ISSUE THREAD

**Issue by jpmc3630** [quasarframework/quasar#14139]
### What happened?

The first time clicking on the clock, it reloads the QTime component and doesn't set the time.  
  
The second click (and subsequent clicks) work fine and set the time.  
  
It appears to be on the mouseUp (the first time) that is reloading the component.  
  
This is also happening on the examples in the Quasar docs [https://quasar.dev/vue-components/time](https://quasar.dev/vue-components/time)  
  
Issue is happening with Chrome and Safari on desktop.  

### What did you expect to happen?

QTime should set the time with one click.

### Reproduction URL

https://codepen.io/jpmc3630/pen/XWEqWNE

### How to reproduce?

1. Go to the reproduction URL
2. Click the QTime clock face to set a time
3. The QTime component will reload on first click and not set the time
4. Second and future times it will work as expected

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari

### Quasar info output

```Shell
Operating System - Darwin(20.6.0) - darwin/x64
NodeJs - 16.13.0

Global packages
  NPM - 8.1.0
  yarn - 1.22.10
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 2.7.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.6 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.33 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.15
  pinia - 2.0.14 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.14 -- Native-ESM powered web dev build tool
  eslint - 8.15.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - MacBook-Pro.lan
  en0 - 10.1.1.108
```

**Comment by pdanpdan** [comment]
On your first click you only have the hour set, and on the second click you have a full time with minutes

**Comment by jpmc3630** [comment]
Thanks, I forgot how a clock works!
