### ISSUE TITLE
BUG: IOS Safari 10 and android version Chrome setScrollPosition() function error

### ISSUE THREAD

**Issue by shawerestart** [quasarframework/quasar#1413]
### Software version

Quasar: 0.14.4
iOS: Safari 10.3
Android: chrome 63

### What did you get as the error?
i'm doing a chatroom and and need to scroll to bottom with a scroll area.
it can work in mac OS chrome 63
and can't work with safari 10.3 and android browser.

and i see the error in the safari broswer 

it can work without any error in safari 11 and desktop verison chrome
![image](https://user-images.githubusercontent.com/26781205/34905133-d73745a0-f88d-11e7-8f41-9774154b67a5.png)
and my code is:
![image](https://user-images.githubusercontent.com/26781205/34905129-c87f479c-f88d-11e7-8b69-126be6f8cc05.png)

**Comment by shawerestart** [comment]
and it can't work in ios simulator too

**Comment by shawerestart** [comment]
and i updated the lastest version of quasar-framework -- 0.14.7 but still have this issue

**Comment by shawerestart** [comment]
ok 
i finally found the reason why i will fail in this part.
setScrollPosition function need three args
setScrollPosition(el, offset, duration) instead of this.$refs.setScrollPosition(offset, duration)


i see the doc have some wrong
![image](https://user-images.githubusercontent.com/26781205/34905596-557ea148-f897-11e7-9696-2c38a7c23e9f.png)

**Comment by rstoenescu** [comment]
Would you be so kind to make a PR for docs? Hit the pencil at the top or the "Edit this page" link at the bottom, make changes, then submit PR.
