### ISSUE TITLE
new Quasarv1 project cannot open in IE11

### ISSUE THREAD

**Issue by 332lfgb6** [quasarframework/quasar#14134]
### What happened?

my new project have checked IE 11 support, but it still doesn't work in IE 11
![image](https://user-images.githubusercontent.com/51245335/182752818-0b1adcfa-a460-4f78-b5d4-11b9501b5d4d.png)
![image](https://user-images.githubusercontent.com/51245335/182756452-1c1c32f6-729d-4c1c-a7e4-5f9f35fdd98b.png)
Other browsers work fine

### What did you expect to happen?

It can run successfully in Internet Explorer 11

### Reproduction URL

https://github.com/332lfgb6/quasar-project

### How to reproduce?

1. yarn
2. quasar dev
3. open ie11

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

SPA Mode

### Platforms/Browsers

Internet Explorer 11

### Quasar info output

Operating System - Windows_NT(10.0.19041) - win32/x64
NodeJs - 12.22.10

Global packages
  NPM - 6.14.16
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 1.19.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.4.1 -- Quasar Framework local CLI
  @quasar/extras - 1.15.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.7.8 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.5.3 -- Official router for Vue.js 2
  vuex - 3.6.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.18.10 -- Babel compiler core.
  webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess file
s, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-B8CE02A
  以太网 2 - 10.100.19.162
  WLAN 5 - 192.168.3.159

**Comment by pdanpdan** [comment]
Hello. Can you please try to check what is in vendor.js on that line?

**Comment by 332lfgb6** [comment]
> 

Is this

![image](https://user-images.githubusercontent.com/51245335/182777063-b1562b88-9c97-426c-9fa4-e082c3ed8f0a.png)

**Comment by 332lfgb6** [comment]
> Hello. Can you please try to check what is in vendor.js on that line?

Is this

![image](https://user-images.githubusercontent.com/51245335/182777284-a97fae51-9c53-4bbe-abe0-77f012bc6565.png)

![image](https://user-images.githubusercontent.com/51245335/182777209-ee881267-91dd-4361-bb64-be0f68c3f750.png)

**Comment by 332lfgb6** [comment]
> Hello. Can you please try to check what is in vendor.js on that line?

is this

![image](https://user-images.githubusercontent.com/51245335/182777492-95a2c70a-a72b-4ca1-bbb3-9a9c9194a85f.png)
![image](https://user-images.githubusercontent.com/51245335/182777563-d2f9812d-d930-4d88-82e1-7cf151d80c4b.png)

**Comment by pdanpdan** [comment]
Are you sure you have ie11 in browserlist?
https://v1.quasar.dev/quasar-cli/browser-compatibility#ie-11-support

**Comment by 332lfgb6** [comment]
> Are you sure you have ie11 in browserlist? https://v1.quasar.dev/quasar-cli/browser-compatibility#ie-11-support

yes.
![image](https://user-images.githubusercontent.com/51245335/183030464-2efe9d13-2a36-4f6e-bb6e-1ea992391713.png)

**Comment by 332lfgb6** [comment]
It's automatically generated

**Comment by pdanpdan** [comment]
@rstoenescu 

It looks like webpack-dev-server does not work as expected in IE11 when `inline: true` is used here: https://github.com/quasarframework/quasar/blob/285f9960dbd6af2e3f6bfb30045594e4121bbcf9/app/lib/quasar-conf-file.js#L600

https://github.com/webpack/webpack-dev-server/issues/2439

Maybe we could set it to false if IE11 support is required?

**Comment by 332lfgb6** [comment]
> @rstoenescu
> 
> It looks like webpack-dev-server does not work as expected in IE11 when `inline: true` is used here:
> 
> https://github.com/quasarframework/quasar/blob/285f9960dbd6af2e3f6bfb30045594e4121bbcf9/app/lib/quasar-conf-file.js#L600
> 
> [webpack/webpack-dev-server#2439](https://github.com/webpack/webpack-dev-server/issues/2439)
> 
> Maybe we could set it to false if IE11 support is required?

Is there any way I can lower the version to make it IE11 compatible? As I recall, it used to run in IE11.

**Comment by 332lfgb6** [comment]
Hopefully this bug will be fixed otherwise Quasar V1 will lose its only meaning (IE 11 support).Thanks.

**Comment by yusufkandemir** [comment]
[Quasar v1 is EOL](https://github.com/quasarframework/quasar/discussions/15229), so I am closing this issue.

**Comment by little3201** [comment]
had the same error, i resolved it with a new quasar project, maybe need to add this:
`build: {
  transpileDependencies: ['sockjs-client', 'axios'],
},`
if has another error, just find what should add to.
