### ISSUE TITLE
 __removeUploaded  of QUploader not used

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#1414]
In version 0.14.7 and current dev version [following code](https://github.com/quasarframework/quasar/blob/dev/src/components/uploader/QUploader.vue#L335) in uploader component is not used:
```
    __removeUploaded () {
      this.files = this.files.filter(f => !f.__doneUploading)
      this.__computeTotalSize()
    },
```
Probably was meant to be an extra property.

**Comment by rstoenescu** [comment]
Fixed it. It should have been removed. Thanks for reporting!
