### ISSUE TITLE
[Suggestion] Drop eslint-plugin-html dependency in favor of the official eslint-plugin-vue

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1416]
As stated in [eslint-plugin-html README](https://github.com/BenoitZugmeyer/eslint-plugin-html#linting-vue-files):

> Initially, [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) was using `eslint-plugin-html` to lint code inside script tags. Since v3, eslint-plugin-vue is using its own parser, so it is incompatible with `eslint-plugin-html`. You should remove `eslint-plugin-html` from your dependencies if you still have this.

Should I prepare a PR?

**Comment by rstoenescu** [comment]
This is scheduled, but in my tests I found it's not stable enough. For example, simple ".js" files are parsed by eslint-plugin-vue too and it throws an error in its own code. So can't have this embedded yet. I already have the code ready, just waiting for this to be fixed.
Thanks for the suggestion and for offering to create a PR!
