### ISSUE TITLE
Unable to load preload script. Error: module not found: fs/promises

### ISSUE THREAD

**Issue by hermit99** [quasarframework/quasar#14179]
### What happened?

Quasar 2.7.7 in Electron mode is currently broken when using fs promises APIs. Same issue as #11759, which seemed closed without a solution?

> Unable to load preload script: C:\quasar-project\.quasar\electron\electron-preload.js
> (anonymous) @ VM4 sandbox_bundle:93
> VM4 sandbox_bundle:93 
> 
> Error: module not found: fs/promises
>     at preloadRequire (VM4 sandbox_bundle:93:1386)
>     at <anonymous>:4:23
>     at runPreloadScript (VM4 sandbox_bundle:93:2213)
>     at Object.<anonymous> (VM4 sandbox_bundle:93:2480)
>     at ./lib/sandboxed_renderer/init.ts (VM4 sandbox_bundle:93:2636)
>     at __webpack_require__ (VM4 sandbox_bundle:1:170)
>     at VM4 sandbox_bundle:1:1242
>     at ___electron_webpack_init__ (VM4 sandbox_bundle:1:1320)
>     at VM4 sandbox_bundle:160:455

OS: Windows 11
Node.js: 18.7.0 | 16.15.1 | 14.17.4 (webpack flavor only as vite needs higher) Same error on all 3 versions
Quasar 2.7.7
Electron: installed by quasar

### What did you expect to happen?

In Electron console, no errors should be thrown

### Reproduction URL

[github](https://github.com/hermit99/quasar-project)

### How to reproduce?

1. npm i -g @quasar/cli
2. npm init quasar
    choose either Vite or Webpack
    Features pick ESLint, Pinia, Vue-i18n
    all others default
3. quasar mode add electron
4. Replace content in src-electron/electron-preload.js with:

        import { contextBridge } from 'electron'
        import { readFile } from 'fs/promises'

        contextBridge.exposeInMainWorld('electronAPI', {
           readFile
        })
6. quasar dev -m electron

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Electron

### Additional context

There would be no error on console if `import { readFile } from 'fs/promises'` is commented out as well as the readFile exposed API

**Comment by mStylias** [comment]
Hey @hermit99!
I had a similar issue while trying to load the remote module through
`import { BrowserWindow } from '@electron/remote'` 
In my case it was fixed by specifying **sandbox: false** inside **webPreferences** like so:
```
mainWindow = new BrowserWindow({  
    icon: path.resolve(__dirname, 'icons/icon.png'),
    width: 1200,
    height: 900,
    frame: false,
    useContentSize: true,
    webPreferences: {
      contextIsolation: true,
      sandbox: false, // add this
      // More info: https://v2.quasar.dev/quasar-cli-vite/developing-electron-apps/electron-preload-script
      preload: path.resolve(__dirname, process.env.QUASAR_ELECTRON_PRELOAD),
    },
  });
```

**Comment by hermit99** [comment]
Thanks @mStylias! You are right, this issue was introduced by latest Electron v20.0.0:
Renderers are now sandboxed by default unless nodeIntegration: true or sandbox: false is specified. (https://github.com/electron/electron/pull/35125)
