### ISSUE TITLE
Add information about material-symbols to extras/readme.md

### ISSUE THREAD

**Issue by Patrick-clone** [quasarframework/quasar#14178]
### Description

Unfortunately the readme of "extras" is not complete regarding "material symbols". After a long search I've been able to use `material-symbols-outlined` but I created this issue so that other people will have an easier time.

- Please add information about prefix needed for using `material-symbols-outlined`, `material-symbols-rounded` and `material-symbols-sharp`.
- Please add notes to the table webfonts telling that quasar version 2.7.0 or above is needed to use `material-symbols-*`

### Documentation Section URL

https://github.com/quasarframework/quasar/tree/dev/extras#webfonts

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar Extras (@quasar/extras)

**Comment by MilosPaunovic** [comment]
If you think there is room for improvement, PRs are always welcome.

**Comment by Patrick-clone** [comment]
I'm not able to properly make a pull request. Never done it before. I can't find a clear tutorial. I can't spend anymore time on this. I'm posting the changes here for anyone who is wondering.

### Changed lines:
```
| [Material Symbols Outlined](https://fonts.google.com/icons?icon.style=Outlined) (Google) | CDN v35 | `svg-material-symbols-outlined` | `@quasar/extras/material-symbols-outlined` | Requires: quasar 2.7.0+, @quasar/extras 1.14+ | [License](material-symbols-outlined/LICENSE) |
| [Material Symbols Rounded](https://fonts.google.com/icons?icon.style=Rounded) (Google) | CDN v34 | `svg-material-symbols-rounded` | `@quasar/extras/material-symbols-rounded` | Requires: quasar 2.7.0+, @quasar/extras 1.14+ | [License](material-symbols-round/LICENSE) |
| [Material Symbols Sharp](https://fonts.google.com/icons?icon.style=Sharp) (Google) | CDN v34 | `svg-material-symbols-sharp` | `@quasar/extras/material-symbols-sharp` | Requires: quasar 2.7.0+, @quasar/extras 1.14+ | [License](material-symbols-sharp/LICENSE) |
```

### Added lines:
```
| material-symbols-outlined | sym_o_ | sym_o_thumb_up | Notice the underline character instead of dash or space | |
| material-symbols-rounded | sym_r_ | sym_r_thumb_up | Notice the underline character instead of dash or space | |
| material-symbols-sharp | sym_s_ | sym_s_thumb_up | Notice the underline character instead of dash or space | |
```
