### ISSUE TITLE
[Request] Add numeric spinner component

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1418]
I think there is a very missing component from the powerful Quasar's toolbox: a numeric spinner with classic two buttons to increment or decrement value:

![image](https://user-images.githubusercontent.com/1370938/34921034-d1220dfe-f97c-11e7-917d-4f08b9d37944.png)

**Comment by bloodf** [comment]
I've made the same 
![image](https://user-images.githubusercontent.com/1626923/40880963-7be5a8dc-6691-11e8-9413-15fbd6967409.png)

You need just flex ordering with quasar buttons and inputs.

**Comment by pdanpdan** [comment]
This is trivial to implement in user code.

```html
<div class="shadow-2 row">
  <q-btn flat label="-" :repeat-timeout="1000" @click="() => { model -= 1; }" />
  <q-input type="number" class="col" align="right" hide-underline v-model="model" />
  <q-btn flat label="+" :repeat-timeout="1000" @click="() => { model += 1; }" />
</div>
```
