### ISSUE TITLE
q-chat-message not showing if avatar is omitted

### ISSUE THREAD

**Issue by kjetilge** [quasarframework/quasar#1420]
If I do not supply a url to to avatar in q-chat-message the whole bubble dissapears - is there any way around this ?

**Comment by realcarbonneau** [comment]
I have submitted a fix.  You will be able to use the QChat without avatars, however, to mix messages with and without avatars and keep them aligned, you need to supply placeholder avatars.  See the details in the pull request.

Here is a video of the reproduction of your issue:
![qchatnoavatarbug](https://user-images.githubusercontent.com/29619229/34925668-bfc68368-f978-11e7-9418-8d2b57c98370.gif)

**Comment by rstoenescu** [comment]
Merged PR. Thank u both!
