### ISSUE TITLE
In Firefox, the js file is loaded twice, why?

### ISSUE THREAD

**Issue by FrostYen** [quasarframework/quasar#14242]
### What happened?

In Firefox, the js file is loaded twice, why?
![_20220823114753](https://user-images.githubusercontent.com/50440625/186065840-05966942-5248-48bc-b01b-31f1b4cd0773.jpg)

### What did you expect to happen?

In Firefox, the js file is loaded only once

### Reproduction URL
https://github.com/quasarframework/quasar/issues/14242

### How to reproduce?

Can be tested with any quasar project

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

SPA Mode

### Platforms/Browsers

Firefox

**Comment by pdanpdan** [comment]
https://github.com/vitejs/vite/issues/5532
