### ISSUE TITLE
Qinput lose focus when change value

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#14256]
### What happened?

When start to type in a q-input inside a q-table it loses focus and only one letter typed in the input ( only the second column Qinput has this problem )

### What did you expect to happen?

The input should not loss focus.

### Reproduction URL

https://codepen.io/alaarihan/pen/YzaMoZg

### How to reproduce?

1- Go to the reproduction URL
2- click "add new row"
3- try to change "value" input.

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You are editing the key

**Comment by ghost** [comment]
Thank you for your reply, you are correct, my bad
