### ISSUE TITLE
[Suggestion] Give option to users to choose when to collapse data table based on screen sizes

### ISSUE THREAD

**Issue by TingtingGu2014** [quasarframework/quasar#1426]
Wonder if some config option can be added to control when to collapse the data table based on screen sizes. I think the default threshold is 600px. I might want to set the value to 768px, etc.
Thanks!

**Comment by rstoenescu** [comment]
Hi, This is no longer relevant for v0.15 as in this version (releasing soon) data-tables have been completely revamped.
Let me know if this is a stop-ship for you on v0.14. Thanks.

**Comment by CristalT** [comment]
I think QDataTable component from v0.14 was better. The collapsible style compared with the current narrow style of QTable component was really responsive. It would be great that quasar v0.15 bring with the old QDataTable besides than QTable current component
