### ISSUE TITLE
i18n error:  SyntaxError: Not available in legacy mode

### ISSUE THREAD

**Issue by asdrubalp9** [quasarframework/quasar#14279]
### What happened?

Followed the steps in https://quasar.dev/options/app-internationalization#introduction with quasar version "^2.6.0"
and getting the error: 

> message-compiler.esm-bundler.js:54 Uncaught (in promise) SyntaxError: Not available in legacy mode (at message-compiler.esm-bundler.js:54:19)
>     at createCompileError (message-compiler.esm-bundler.js:54:19)
>     at createI18nError (vue-i18n.esm-bundler.js:100:12)
>     at useI18n (vue-i18n.esm-bundler.js:2228:23)
>     at setup (headerComponent.vue:82:24)
>     at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
>     at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
>     at setupComponent (runtime-core.esm-bundler.js:7120:11)
>     at mountComponent (runtime-core.esm-bundler.js:5473:13)
>     at processComponent (runtime-core.esm-bundler.js:5448:17)
>     at patch (runtime-core.esm-bundler.js:5038:21) 

code in failling component:

```
<script>
import { onMounted, ref, watch } from "vue";
import { useLanguageStore } from "stores/language";
import { useI18n } from "vue-i18n";
export default {
  name: "HeaderComponent",
  setup() {
    const { locale } = useI18n({ useScope: "global" }); // when I comment the line it doesn't give an error.


```

### What did you expect to happen?

to work and toggle the languages of the app

### Reproduction URL

https://stackblitz.com/edit/quasarframework-bmv9ri?file=src/pages/IndexPage.vue

### How to reproduce?

go to link https://stackblitz.com/edit/quasarframework-bmv9ri?file=src/pages/IndexPage.vue
open console
see error staring at you dead in the face and laughing after following the steps in the documentation.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by MilosPaunovic** [comment]
Check wheter does this help you out:
https://github.com/quasarframework/quasar/discussions/14135#discussioncomment-3323885

**Comment by asdrubalp9** [comment]
thanks,
this fixed it!
