### ISSUE TITLE
[v0.13] q-dialog-select no event work

### ISSUE THREAD

**Issue by giuseppe-palmeri** [quasarframework/quasar#1428]
### Software version

Quasar: 0.13.4
Vue: 2.2
OS: Linux / Ubuntu 
Node: v9.2.1
NPM: 5.5.1
Browsers: Chromium
iOS:
Android:
Any other software related to your bug:

List of dipendencies on package.json

        "fastclick": "^1.0.6",
        "hellojs": "^2.0.0-4",
        "laravel-vue-i18n-generator-webpack": "^0.1.0",
        "material-design-icons": "^3.0.1",
        "moment": "^2.15.0",
        "quasar-framework": "^0.13.4",
        "roboto-fontface": "^0.7.0",
        "vue-authenticate": "^1.3.4",
        "vue-cli": "^2.9.2",
        "vue-hellojs": "0.0.4",
        "vue-i18n": "^7.4.0",
        "vue-persist": "^0.4.0",
        "vue-router": "^3.0.1"

### What did you get as the error?
I created a q-dialog-select to change the language.
When changing the language, I have to take some actions and for this
I used @change as indicated on the documentation.

### What were you expecting?
I expect the onChange function to be executed after changing items on the list and pressing OK on the dialog.
Nothing happens.

Also, I did not find any working examples of q-dialog-select on the documentation with "change" event

Note: **This also happens if I use it q-select .**
### What steps did you take, to get the error?
To reproduce the problem try this template:
```

<template>
<div>
    <q-dialog-select
      type="radio"
      @change="onChange"
      @click="onChange"


      v-on:change="onChange"
      v-on:blur="onChange"
      v-on:click="onChange"
      @blur="onChange"
      :padding="1"
      class="primary big on-left"
      v-model="curlang"
      :options="selectOptions"
      :ok-label="$t('app.ok')"
      :cancel-label="$t('app.cancel')"
      :title="$t('app.languages')"

    ></q-dialog-select>


</div>
</template>

<script>

export default {
    data() {
            return {
                curlang: localStorage.getItem('curlocale', 'en'),
                auth: auth,
                selectOptions: [
                  {
                    label: '<img style="height:14px;" src="/storage/flags/flags/flat/16/United-Kingdom.png"> English',
                    value: 'en'
                  },
                  {
                    label: '<img style="height:14px;" src="/storage/flags/flags/flat/16/Italy.png"> Italiano',
                     value: 'it'
                  }
                ]
            }
        },

        methods: {
            onChange() {
              alert("test");
            }
        },
        mounted: function () {
            this.$nextTick(function () {
            })
        }
}
</script>
```

**no event is captured.**

**Comment by rstoenescu** [comment]
This has been fixed in v0.14+, so closing. Not enough resources to release another v0.13 iteration, so sorry. Please upgrade.
