### ISSUE TITLE
cli-app-vite auto import not working when quasar component is loaded dynamically thru component tag.

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#14290]
### What happened?

cli-app-vite auto import not working when quasar component is loaded dynamically thru component tag.
ie. `<component :is="'q-input'" />` fails to load

### What did you expect to happen?

auto import should detect usage.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-oagn9v?file=src%2Fpages%2FIndexPage.vue 

### How to reproduce?

1. go to provided link
2. see bug

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Additional context

stackblitz showing it works fine in cli-webpack
https://stackblitz.com/edit/quasarframework-webpack-17naed?file=src%2Fpages%2FIndexPage.vue

**Comment by rstoenescu** [comment]
Hi,

Yes, we cannot account for this kind of dynamic usage in the autoimport procedure. This would blow out the compiling performance.

However, you can register the component(s) globally or in your target component.

**Comment by metalsadman** [comment]
> Hi,
> 
> Yes, we cannot account for this kind of dynamic usage in the autoimport procedure. This would blow out the compiling performance.
> 
> However, you can register the component(s) globally or in your target component.

that's my suggestion to users, though with the removal of `installation` section in the docs, users might be mislead that this works ootb with auto import.
