### ISSUE TITLE
problem with quasar build -m capacitor -T android

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#14294]
### Description

when I run quasar build -m capacitor -T android it gives me 

    App • ⚠️  Gradle build failed!
    App • ⚠️  As an alternative, you can use the "--ide" pa
    ram and build from the IDE.
    when I use android studio to build it give me error "Duplicate resources"

reproduction 
https://github.com/modemb/larasar

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by MilosPaunovic** [comment]
Have you tried Googling the issue, as it's more Gradle/Capacitor related than Quasar itself?
https://github.com/facebook/react-native/issues/19239#issuecomment-414564404

**Comment by modemb** [comment]
> Have you tried Googling the issue, as it's more Gradle/Capacitor related than Quasar itself?
> https://github.com/facebook/react-native/issues/19239#issuecomment-414564404

Yes but it is quasar cli though,

**Comment by modemb** [comment]
> Have you tried Googling the issue, as it's more Gradle/Capacitor related than Quasar itself? [facebook/react-native#19239 (comment)](https://github.com/facebook/react-native/issues/19239#issuecomment-414564404)

this didn't fix it

**Comment by metalsadman** [comment]
try https://github.com/gradle/gradle/issues/10248#issuecomment-647423613
