### ISSUE TITLE
Typescript typings error on openUrl

### ISSUE THREAD

**Issue by maggie44** [quasarframework/quasar#14292]
### What happened?

There seems to be an issue with the typings from open URL:

```
      openURL(url, null, {
        width: '1050'
      })
```

`Argument of type 'null' is not assignable to parameter of type '((...args: any[]) => any) | undefined'`.

Yet the docs provide null as the example: https://quasar.dev/quasar-utils/other-utils#open-external-url

### What did you expect to happen?

Null be accepted instead of a function.

### Reproduction URL

N/A

### How to reproduce?

Start a Quasar typescript project and use the command:

```
      openURL(url, null, {
        width: '1050'
      })
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Electron Mode

### Quasar info output

```Shell
Operating System - Darwin(21.6.0) - darwin/arm64
NodeJs - 16.16.0

Global packages
  NPM - 8.11.0
  yarn - 3.2.3
  @quasar/cli - 1.3.2
  @quasar/icongenie - 2.5.3
  cordova - Not installed

Important local packages
  quasar - 2.7.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.6 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.3
  pinia - 2.0.20 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.22.0 -- An AST-based pattern checker for JavaScript.
  electron - 20.0.3 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 15.5.2 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Additional context

I am build Electron apps, but don't think it's relevant.

**Comment by IlCallo** [comment]
Hey there, could you try it with `undefined` instead of `null`?
We may have to update the docs

**Comment by maggie44** [comment]
Undefined did the trick, thanks. I will leave the issue open for docs consideration.

**Comment by yusufkandemir** [comment]
Typings are configured to include `undefined` but not `null`. The code is configured to be run properly with any falsy value(_`undefined`, `null`, `0`, `''`, etc._). So, "officially" declaring only `undefined` to be passed and updating the docs to reflect that makes more sense to me.

**Comment by IlCallo** [comment]
@maggie0002 could you open a PR fixing the docs to use `undefined` instead of `null`? :)
