### ISSUE TITLE
q-input trigger false change event (v0.15.beta)

### ISSUE THREAD

**Issue by wux5** [quasarframework/quasar#1430]
### Software version

Quasar: 0.15.0-beta.4
OS: MacOS 10.12.6 (Sierra)
Node: 8.9.1
NPM: 5.x
Browsers: Chrome 63

### What did you get as the error?
Create a q-input and bind @ change event, supposedly the change event should get triggered only if the value changed in the input, but it actually triggered change event when you click the input and then click somewhere else, without even any key input.

### What were you expecting?
q-input trigger change event only if there is actually value changes.

**Comment by rstoenescu** [comment]
Yes, this is being worked on.

**Comment by rstoenescu** [comment]
Fixed in latest v0.15 build.
