### ISSUE TITLE
When "q-input" is included in "q-pop-proxy" and "@ Keydown. Enter. Stop" is bound, it cannot be closed correctly

### ISSUE THREAD

**Issue by yj3921** [quasarframework/quasar#14320]
### What happened?

"Popup proxy" cannot be properly closed when the Enter key is pressed.

### What did you expect to happen?

When the "enter" key is pressed, it should be closed correctly

### Reproduction URL

https://codepen.io/PoJie/pen/QWrwaJb

### How to reproduce?

1，Please check the link to provide the case
2，Click the Add button
3，Place the mouse cursor on input
4，Press enter

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
It cannot because you stop the event propagation. Catch enter and close the popup as you see fit

**Comment by yj3921** [comment]
> 它不能，因为您停止了事件传播。在您认为合适的情况下输入并关闭弹出窗口

Sorry, I didn't catch your meaning

**Comment by yj3921** [comment]
> It cannot because you stop the event propagation. Catch enter and close the popup as you see fit
Sorry, I didn't catch your meaning

**Comment by yj3921** [comment]
@pdanpdan Sorry, I didn't catch your meaning

**Comment by yj3921** [comment]
I just want to turn off the popup-proxy when I press enter, but now it turns on automatically after it is turned off. Is this normal?

**Comment by pdanpdan** [comment]
Ok, I now understand - you want to close the popup :)
https://codepen.io/pdanpdan/pen/poVvZpQ?editors=1010

You need to set a small delay (300ms) before closing the popup - else the focus goes on the opening button (ADD +) and the ENTER key makes the popup open again
