### ISSUE TITLE
Limit of "maxlength" loses efficacy when set type to "number"

### ISSUE THREAD

**Issue by flyinmind** [quasarframework/quasar#14326]
### What happened?

Limit of "maxlength" loses efficacy when set type to "number"

### What did you expect to happen?

Limit the maxlength when set type to number.

### Reproduction URL

none

### How to reproduce?

Use input in UMD mode, set type to 'number' and maxlength to 11

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
none
```

### Relevant log output

```Shell
none
```

### Additional context

none

**Comment by pdanpdan** [comment]
Maxlengthv is an attribute of the native input and works as it is implemented in the browser.
