### ISSUE TITLE
Loader property reports error in Safari 11

### ISSUE THREAD

**Issue by sdellis** [quasarframework/quasar#1434]
### Software version

Quasar: 0.14.6 (current
OS: MacOSX 10.13.2 (High Sierra)
Node: 8.2.1
NPM: 5.4.1
Browsers: Safari 11.0.2
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Console error: `Error: Invalid value for <svg> attribute width="1rem"` and `Error: Invalid value for <svg> attribute height="1rem"`

### What were you expecting?
I was expecting no error.

### What steps did you take, to get the error?
I added a button with a `loader` property. 

This bug can also be seen on the [quasar dev site - Button With Progress example](http://quasar-framework.org/components/button.html#Button-with-Progress ). Click one of the buttons with Progress in the example and it will appear in the console.

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting!

**Comment by rstoenescu** [comment]
I can confirm two things:
1. It can easily be reproduced with v0.14
2. No longer happens in v0.15.

As v0.15 is so close to its release, will simply close this. Let me know if this is critical for your app.
