### ISSUE TITLE
Quloader Doc Issue

### ISSUE THREAD

**Issue by xiaolangyuxin** [quasarframework/quasar#14346]
### Description

the documents for quploader components has following isue.

in the document,it claims field-name,form-fields props, acturraly it works wrong, the field-name , formFields props can work well. 

![2](https://user-images.githubusercontent.com/22924583/189087173-a87053ad-dbd0-4f97-bc64-65e3c2147093.png)

### Documentation Section URL

https://quasar.dev/vue-components/uploader

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
All Vue props should be used kebab-case but are recognized as camel-case
