### ISSUE TITLE
Ctrl+Z doesn't work in firefox for QInput with autogrow

### ISSUE THREAD

**Issue by dexif** [quasarframework/quasar#14344]
### What happened?

Ctrl+Z doesn't work in firefox for &lt;q-input type="textarea" autogrow&gt;

### What did you expect to happen?

Ctrl+Z should undo text changes

### Reproduction URL

https://codepen.io/dexif/pen/RwyGxVX

### How to reproduce?

1. Open Firefox (any version)
2. https://codepen.io/dexif/pen/RwyGxVX
3. Type any text.
4. Ctrl+Z

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Any version v1 and v2
```

**Comment by pdanpdan** [comment]
It's just another 10 years old bug in firefox :)
https://bugzilla.mozilla.org/show_bug.cgi?id=854272

**Comment by rstoenescu** [comment]
Fix will be available in v2.8.3
