### ISSUE TITLE
[Firefox] Unpleasant rendering of some q-input types

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1435]
On Firefox 57 some `q-input` are partially rendered using Firefox's native input style:

- [ ] Numeric inputs show increment/decrement arrows that look terrible with material/iOS themes
- [ ] Email input show a red border. Maybe related to #317.

I'm checking other types too...

**Comment by rstoenescu** [comment]
What Quasar version? Have you checked this with latest v0.15 beta (6) too?

**Comment by zuck** [comment]
Thanks!
