### ISSUE TITLE
quasar build not detach terminal ( build docker image)

### ISSUE THREAD

**Issue by hooman-mirghasemi** [quasarframework/quasar#14363]
### What happened?

I write my docker file :

FROM node:16-alpine as builder
WORKDIR /app

COPY ./src/admin/package.json package.json
COPY ./src/admin/package-lock.json package-lock.json

RUN npm i -g @quasar/cli

RUN npm install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false

COPY ./src/admin .

RUN mv .env.example .env
RUN quasar build
RUN mkdir "test"

FROM nginx:1.23.1
RUN apt-get update && apt install -y htop
WORKDIR /app

COPY --from=builder ./app/dist/spa /app
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

### What did you expect to happen?

when it run 
RUN quasar build

get terminal proccess and dont let to go next step

I test in in my local machine have same behavior and force me to use ctl+c to detach terminal

### Reproduction URL

test

### How to reproduce?

q

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SPA Mode

**Comment by MilosPaunovic** [comment]
Do you have `analyze` property of the `build` object in `quasar.config.js` set to `true`?

**Comment by hooman-mirghasemi** [comment]
Yes, and you save me.
Thank you man
