### ISSUE TITLE
LoadingBar.setDefaults not working properly

### ISSUE THREAD

**Issue by zhongjiaguo001** [quasarframework/quasar#14382]
### What happened?

Using LoadingBar's setDefaults method does not take effect
![image](https://user-images.githubusercontent.com/44691489/190050384-02eaef05-325c-4cb5-a994-eb2f41ab1297.png)
![image](https://user-images.githubusercontent.com/44691489/190050651-368c4415-7cd7-4c6c-8088-69a8c47fc490.png)

quasar version：2.7.7

### What did you expect to happen?

Normal use

### Reproduction URL

none

### How to reproduce?

1、Introduce loadingbar
2、Use the setDefaults method

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
If you want to set defaults in `quasar.config.js` file, you need to add them under `framework -> config`, like in the example below:

`
return {
  framework: {
    plugins: [
      'LoadingBar'
    ],
    config: {
      loadingBar: { /* look at QuasarConfOptions from the API card */ }
    }
  }
}
`

**Comment by zhongjiaguo001** [comment]
> 如果要在`quasar.config.js`文件中设置默认值，则需要在 下添加它们`framework -> config`，如下例所示：
> 
> `return { framework: { plugins: [ 'LoadingBar' ], config: { loadingBar: { /* look at QuasarConfOptions from the API card */ } } } }`

I installed it in the way of Vite plugins, the loadingBar took effect normally, but the setDefaults method did not take effect.

**Comment by rstoenescu** [comment]
Hi,

Any method of any Quasar Plugin must be called after it gets a chance to get installed (aka app.use(Quasar, ...) call)

**Comment by zhongjiaguo001** [comment]
> 你好，
> 
> 任何 Quasar 插件的任何方法都必须在有机会安装后调用（又名 app.use(Quasar, ...) 调用）
I installed it, the loading bar is showing normally, but the setDefaults method is not working properly
