### ISSUE TITLE
input element - weird behavior (unexpected focus) when clicked area below element

### ISSUE THREAD

**Issue by yureckey** [quasarframework/quasar#14383]
### What happened?

if your input have validation rules (and hence ui element for notification message below input)
input element got focused when user clicks below input. There is no indication why clicking below would make input focused. Also - there is no focusing if input doesn't have validation rules. I mean this behavior is confusing and unexpected for user.
(same behavior is when Select have validation rule)

### What did you expect to happen?

no focus in input element

### Reproduction URL

https://codepen.io/yureckey/pen/gOzwqNv

### How to reproduce?

1. go to provided link
2. click in an area under any input element

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
latest
```

**Comment by MilosPaunovic** [comment]
You could use `hide-bottom-space` prop as a solution.

**Comment by yureckey** [comment]
Yes, that would work, but layout will be moved when there is validation error message. I would prefer this "bottom space" to not react to click

**Comment by rstoenescu** [comment]
Fix will be available in Quasar ~~v2.8~~ v2.8.1 and  v1.20
