### ISSUE TITLE
v2.8.0 can't convert undefined to object

### ISSUE THREAD

**Issue by artnova-david** [quasarframework/quasar#14393]
### What happened?

After installing v2.8.0 following error was thrown: can't convert undefined to object

![q-error](https://user-images.githubusercontent.com/21141231/190323110-da277064-52d3-476d-bcba-f2b018da4642.jpg)

### What did you expect to happen?

No error

### Reproduction URL

/

### How to reproduce?

1. Install Quasar v2.8.0
2. Bundle
3. ...check console

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar), Plugins (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome, Safari

**Comment by rstoenescu** [comment]
Hi,

I just checked and everything works fine. Are you sure that you are using `vue-cli-plugin-quasar` v5 with `@vue/cli` v5?
Please provide a reproduction repo with your setup. Thanks in advance.

**Comment by artnova-david** [comment]
Hi,
Thanks for your reply.
I'm not using vue-cli-plugin-quasar just vue cli v5.0.8 and importing quasar like this

`import { Quasar, Notify, Screen, AppFullscreen } from "quasar"`

` app.use(Quasar, {

      lang: lang,

      iconSet: iconSet,

      cssAddon: true,

      plugins: [
         Notify,
         Screen,
         AppFullscreen
      ],

      config: {
         loadingBar: {
            skipHijack: true
         }
      }

   })`

This worked just fine before updating from v2.7.7 to v2.8.0.
A reproduction repo is not possible, because this is a private and custom project

Thanks.

**Comment by rstoenescu** [comment]
@artnova-david It is highly recommended to use `vue-cli-plugin-quasar` otherwise you won't benefit from important features like tree-shaking.

**Comment by rstoenescu** [comment]
Decided to add back quasar.esm.prod.js and released Quasar v2.8.1.

Again, it's highly recommended to use `vue-cli-plugin-quasar` when on a Vue CLI project and `@quasar/vite-plugin` when on a Vite project (not referring here to Quasar CLI with Vite).

**Comment by artnova-david** [comment]
Hi,
Thanks for the fix, highly appreciated.
Will be adding `vue-cli-plugin-quasar` to the project soon.

Thanks again.

**Comment by rstoenescu** [comment]
Forgot to auto-register all components and directives for that entry-point. Released v2.8.2.
