### ISSUE TITLE
Adding back Grid component (not referring to Grid CSS)

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#144]

**Comment by zoomclub** [comment]
However, CSS-Grid is coming soon to all apps near you √

**Comment by rstoenescu** [comment]
There was a Grid Vue component that wasn't ported to Vue 2. That is what's about. Not about CSS standards :)

**Comment by angleman** [comment]
Congrads on the 0.8.x releases. Any estimate on when this will be available again?

**Comment by rstoenescu** [comment]
Thank you. Next in line is the electron wrapper then this grid component. 2-3 weeks worst case.

**Comment by CookieJon** [comment]
I'm on it!

Any **extra** feature requests that aren't already in the original, please add 'em here...!

**Comment by rstoenescu** [comment]
Releasing new Quasar version at the end of this week which will have DataTable (replacing old Grid component).

![screenshot from 2016-12-07 10 31 54](https://cloud.githubusercontent.com/assets/4665641/20960321/8db4dd78-bc68-11e6-9056-00a9399a93b3.png)

**Comment by rstoenescu** [comment]
Closing this. Will be available shortly in v0.10
