### ISSUE TITLE
QTable v0.15 columns visibility

### ISSUE THREAD

**Issue by pdwinkel** [quasarframework/quasar#1440]
The column settings on the QTable v0.15 seems not to be working in the data-table and data-table-2 dev tests.

**Comment by rstoenescu** [comment]
Hi,

Please reopen detailing the issue. Saying something vague doesn't help.

**Comment by pdwinkel** [comment]
Well, when you toggle the columns in the QTableColumns, the visibility of the columns in the QTable is not changing. For example using the data-table page:

![image](https://user-images.githubusercontent.com/533727/35064728-46b89b96-fbcb-11e7-9589-26c01d4592a9.png)


The 'Fat (g)'  column stays visible when you toggle it.

**Comment by rstoenescu** [comment]
Fixed it. Thanks for reporting!
