### ISSUE TITLE
`loading` property from`useQuasar()` is typed incorrectly

### ISSUE THREAD

**Issue by Basaingeal** [quasarframework/quasar#14404]
### What happened?

The `loading` property in `QVueGlobals` is defined with this type.
```typescript
loading: (
      opts?: QLoadingShowOptions
    ) => (props?: QLoadingUpdateOptions) => void;
```

But this doesn't line up with what is actually returned from `useQuasar()` which is an object fulfilling the `Loading` interface.

```typescript
const { loading } = useQuasar();
console.log(loading);
```
`{show: ƒ, hide: ƒ, setDefaults: ƒ, install: ƒ, …}`

### What did you expect to happen?

The type for `loading` in `QVueGlobals` should be the interface `Loading`

### Reproduction URL

https://stackblitz.com/edit/quasarframework-pyoesh?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to reproduction link.
2. Click the Loader button. See that it is functional.
3. Open a new terminal
4. Run `npm run tsc`
5. View type errors

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

**Comment by rstoenescu** [comment]
Fixed already. Will be available in v2.8.3
