### ISSUE TITLE
QFile multiple select bug

### ISSUE THREAD

**Issue by olegbaturin** [quasarframework/quasar#14406]
### What happened?

1. Select only 'file1'
2. Select 'file1' and 'file2'
3. Only 'file2' is selected

### What did you expect to happen?

'file1' and 'file2' selected

### Reproduction URL

https://quasar.dev/vue-components/file-picker#example--multiple-files

### How to reproduce?

1. Select only 'file1'
2. Select 'file1' and 'file2'
3. Only 'file2' is selected

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.8.3 and 1.20.1

**Comment by olegbaturin** [comment]
Now if append="true" duplicates are not removed. And if append="false", previous selection [file1, file2] is not cleared if [file1] is selected.

**Comment by olegbaturin** [comment]
this commit [d40477b](https://github.com/pdanpdan/quasar/commit/d40477b5503d91ab850aeca362ffe3d5fe3df04f) works fine

**Comment by pdanpdan** [comment]
The current solution is better, just the check is the other way around, it'll be fixed in next version.

**Comment by olegbaturin** [comment]
ok, thanks
