### ISSUE TITLE
Request: Enhance q-layout-drawer 'behavior'?

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#1445]
I would like to implement a left-drawer which contains a carousel for displaying different sets of information (like the Slack app which allows you to swipe the left drawer between teams, channels and direct messages). Obviously this needs to interact quite closely with the 'swipe to open' / 'swipe to close' functionality of the mobile behaviour.

What I was hoping for is the ability to swipe from the left to open a drawer, and on the 'background' (to the right of a left drawer) to close the drawer, but swipes _on the drawer itself_ would be ignored (or rather passed down to the carousel to manage its content with).

By commenting out lines 259–263 of `QLayoutDrawer.js` I get the behaviour I want, so I guess it would be a case of making that directive conditional on `this.mobileView` _and_ a new prop?

**Comment by dsl101** [comment]
And then that led me to another pitfall of this, which I'm still interested in finding out about. The challenge now (for a web app using this interface) is that swiping the drawer is very close to swiping back / forward on ios. Apparently it's not possible for a web page to 'ask' ios not to do this. See also [this issue](https://github.com/quasarframework/quasar/issues/366).

That got me wondering though, for an 'app' in mobile Safari, the back / forward history thing is not so useful anyway. I'd be happy for users to always have to click / tap on something to navigate, rather than relying on browser history. I don't really want the '#' in the URLs, but by zeroing out the browser tab history, that should prevent ios from attempting to navigate back forward and allow the drawer open swipe, swipe contents, and close swipe to all work together. But would clearing history break anything else?

**Comment by dsl101** [comment]
In fact, in hash mode, with those lines commented out, it works _really nicely_ on a brand new tab (with no existing history). The drawer can be opened by swipe, the contents (a q-carousel) can be swiped, and the drawer can be closed by swiping from the right hand edge of the phone screen.

I _think_ clearing the history on load, and only ever using `$router.replace()` should work. So, I just need a prop to make swiping to close conditional now.

**Comment by rstoenescu** [comment]
Pushed commit:

    fix: close #1445 Request: Enhance q-layout-drawer 'behaviour'?
    QLayoutDrawer -> new props: "no-swipe-open", "no-swipe-close"

Combine the new props with $q.platform and you got full power over the behavior.

**Comment by dsl101** [comment]
Tx - perfect :).

**Comment by dsl101** [comment]
Now, I say 'perfect', and indeed it does exactly what I want. But I think the logic _may_ confuse some people. My use case is maybe niche, but I don't think unique in wanting a carousel in a drawer. Native apps seem to be using that model for hierarchical data.

My point is this; with the current logic, `noSwipeOpen` will also imply `noSwipeClose` _on the background_—i.e. to the right/left of the drawer. `noSwipeClose` will disable closing by swiping the drawer itself, but will still allow swipe to close on the background.

I guess it might be enough to explain this in the docs—happy to work on that page when it's live

**Comment by rstoenescu** [comment]
Yes. My thoughts exactly. There is no reason to block swipe on the overlay behind the drawer. It will get documented. Thanks for wanting to help out. Will tell you when you can help on docs.

**Comment by dsl101** [comment]
Actually, I think my first point isn't right. I'd misread where the curly brackets were, and `noSwipeOpen` will still allow the 'close' background overlay (which is good for me).

The second point is that `noSwipeClose` really only means `noSwipeDrawerClose`—you could still swipe the _background_ to close. That is in fact exactly what I want, so I wouldn't want to see that 'fixed' :).
