### ISSUE TITLE
Qicon: name prefix not working

### ISSUE THREAD

**Issue by abnerwang06** [quasarframework/quasar#14473]
### What happened?

Material icons doesn't display when I added prefix , o_, to name of Qicon

### What did you expect to happen?

Displaying outlined icon

### Reproduction URL

https://stackblitz.com/edit/quasarframework-dzwppm?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

Add prefix , o_, to name of Qicon

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/icon#webfont-icons

**Comment by abnerwang06** [comment]
> https://quasar.dev/vue-components/icon#webfont-icons

![image](https://user-images.githubusercontent.com/33473028/192188382-8130fe84-845f-4bbb-a7d5-64bf2d6251b6.png)
I used the example, it didn't display icon

**Comment by MilosPaunovic** [comment]
Have you checked the warning in a yellow card just below the headline, which says:

`
If you are using webfont-based icons, make sure that you [installed the icon library](https://quasar.dev/options/installing-icon-libraries) that you are using, otherwise it won’t show up!
`

**Comment by abnerwang06** [comment]
> 

I got it, I supposed extras in quasar config including 'material-icons' would import all styles of material-icons.
The icons displayed after adding 'material-icons-outlined' to extras. 
Thank you.

**Comment by rstoenescu** [comment]
Including them all would be a waste of bandwidth for the end-users. You need to pick exactly what you are using.
