### ISSUE TITLE
Missing feature flag generation is broken

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#14483]
```
Error: ENOENT: no such file or directory, lstat '/.../node_modules/@quasar/app-vite/templates/pwa/pwa-flag.d.ts'
```

https://github.com/quasarframework/quasar/blob/3f9296502784e64473547aabafdfde90a580b782/app-vite/lib/helpers/types-feature-flags.js#L40

But, that file is missing in the root folder of some modes.
https://github.com/quasarframework/quasar/tree/dev/app-vite/templates/pwa
https://github.com/quasarframework/quasar/tree/dev/app-vite/templates/electron
...

We can adjust the paths or just make sure to put the file into root folders as well.

**Comment by rstoenescu** [comment]
@yusufkandemir 
Flag files should be in their /src-*/ folder, not root. So that if/when the mode is removed it won't impact the functionality of the project.

**Comment by yusufkandemir** [comment]
@rstoenescu root folder in this context is `app-vite/templates/pwa`, not `/src-pwa`. So, everything will be the same as before in the userland. This is a basic error that got introduced when adding TS variants to modes, which needed a different templates folder structure.

**Comment by rstoenescu** [comment]
Fix will be available in q/app-vite 1.1.3 and q/app-webpack 3.6.2.

**Comment by FKPSC** [comment]
I just got the error:
```
Error: ENOENT: no such file or directory, lstat '/media/veracrypt16/work/PSC/quasar-app_TS_electron_gt_v28/node_modules/@quasar/app-vite/templates/pwa/pwa-flag.d.ts'
```
when running the command `quasar mode add pwa`
Here is my `quasa info`:
```
Operating System - Linux(6.9.3-76060903-generic) - linux/x64
NodeJs - 20.16.0

Global packages
  NPM - 10.8.1
  yarn - 1.22.22
  pnpm - Not installed
  bun - Not installed
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.16.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.0-beta.19 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.38 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.3
  pinia - 2.2.2 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 5.4.1 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 8.57.0 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.23.1 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.4 -- TypeScript is a language for application scale JavaScript development
  workbox-build - 7.1.1 -- A module that integrates into your build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  electron - 32.0.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  @electron/packager - 18.3.3 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
```

**Comment by yusufkandemir** [comment]
@FKPSC it's fixed in https://github.com/quasarframework/quasar/commit/b27711e4a1cf7164bdd6d688be84aa0dcbd52b0f. The fix will be included in the next releases.

**Comment by FKPSC** [comment]
@yusufkandemir which release? The previous comment seems to mention a version that is already out.

**Comment by yusufkandemir** [comment]
@FKPSC
Here is the GitHub's recommendation when you are leaving a comment here
![image](https://github.com/user-attachments/assets/8127e348-3fec-4fba-9b57-f5109aaeaa73)

This issue was old, got fixed, and released a long time ago. The issue you've faced is new, and I replied to you as:
> The fix **WILL BE** included in the **NEXT** releases.
