### ISSUE TITLE
[Request] (low priority) support for "epic spinners"

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1449]
I'd love at some date in the future to have support for "epic spinners" right out of the box along side Quasar's other spinners.

http://epic-spinners.epicmax.co/#/

low priority. Maybe Quasar version 1.1

**Comment by Frondor** [comment]
Its pretty trivial to implement your own loader icon tho. You can even extend the component and make your own version with whatever icon library you want.
I don't think yet another dependency is what we need here, just my $ 0.50

**Comment by mesqueeb** [comment]
I meant not as a dependency, but just copy these entire animations as Quasar standard animations some day.
That they can be used like any other quasar spinner, but quasar has these default really cool spinners as well.

It's doesn't matter that much though.

**Comment by sganz** [comment]
I would add it would be cool to have the quasar logo as a spinner, somewhat off topic but just tossing it in :)

**Comment by rstoenescu** [comment]
Hi,

Three main reasons not to include this by default:

1. Like already said, it's almost trivial to add this to your app by yourself. And I'd go with this approach.
2. We do not need to bloat Quasar with hundreds of spinners now -- even if we got tree-shaking in place, the UMD version will be forced to include them. So not good.
3. The default spinners are svg based, and for a good reason. You can dynamically change color and size. Hard to do that with CSS only spinners.
