### ISSUE TITLE
Inline QOptionGroup seems to break Grid Row/Column layout

### ISSUE THREAD

**Issue by 54mu3l** [quasarframework/quasar#14496]
### What happened?

I have a form with multiple rows. The rows are grouped into a [Grid Column](https://quasar.dev/layout/grid/column) (for gutter reasons). Within a [Row](https://quasar.dev/layout/grid/row) there are col's (for label and input = left and right).

I would expect the rows to take up only as much space (height) as they need (since they're wrapped within a `col-auto`).
This works for all kinds of quasar components. Except for the QOptionGroup. As soon as I set the `inline` property it takes up more space than it should. As far as I can see I used the column/row/col concept correctly and since it only happens for a inline QOptionsGroup it seems like a bug to me.

As you can see here there is space between "Line 5" and "Line 6":
https://codepen.io/54mu3l/pen/vYjWMpE?editors=1010

### What did you expect to happen?

I would expect no space between "Line 5" and "Line 6" (see reproduction URL).

### Reproduction URL

https://codepen.io/54mu3l/pen/vYjWMpE?editors=1010

### How to reproduce?

1. Go to the reproduction URL
2. See the space between "Line 5" and "Line 6"
3. Where does this space come from? (QOptionGroup bug?)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22000) - win32/x64
NodeJs - 16.13.2

Global packages
  NPM - 8.12.1
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.8.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.39 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.22 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.23.1 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by pdanpdan** [comment]
That is because flex first tries to adjust to the height of the content using the minimum width of the content, and then increases the width as much as it can (so the height becomes smaller)

You have a few ways to mitigate this:
https://codepen.io/pdanpdan/pen/XWqzvWZ?editors=1000
