### ISSUE TITLE
QTree with `no-selection-unset` option set can't accept `0` as a key

### ISSUE THREAD

**Issue by znfgnu** [quasarframework/quasar#14505]
### What happened?

On my website I have QTree component that shows items tree. Items are differentiated by `idx` field that contains integer numbers starting from 0. The QTree also has `v-model:selected` property set to `selectedItem`. Since I added `no-selection-unset` property to QTree, after selecting item with `idx` of `0` , `selectedItem` contains `null` instead. After removing `no-selection-unset` everything works ok.

### What did you expect to happen?

With `no-selection-unset`: After selecting item with key `0`, selected model should contain `0` instead of null.

### Reproduction URL

https://codepen.io/znfgnu/pen/xxjYqbp

### How to reproduce?

1. Go to reproduction link
2. Try to select option "zero"
3. Selected item below will turn to `null` instead of zero (other options work ok)

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by argomale** [comment]
are u dolbayob? why u open such stuped issues
ill rip your facking face dog if you post it next time

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.8.5
