### ISSUE TITLE
QForm submit with input validation dosnt work in new version v1.20.2

### ISSUE THREAD

**Issue by abitaf** [quasarframework/quasar#14503]
### What happened?

https://codepen.io/pen?&editors=101

### What did you expect to happen?

Enter the function "onSubmit" after clicking on submit

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

Click on submit button after fill in the form not showing the notify

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Relevant log output

```Shell
QForm.js?0378:86 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at eval (QForm.js?0378:86:1)
```

**Comment by MilosPaunovic** [comment]
Duplicate https://github.com/quasarframework/quasar/issues/14492
