### ISSUE TITLE
How to use internal validators with an error message

### ISSUE THREAD

**Issue by danbars** [quasarframework/quasar#14502]
### Description

In [qinput](https://quasar.dev/vue-components/input#internal-validation) docs it is mentioned that there are helper validators, and there is a link to the code.

In the same doc, the [`rules` property description](https://quasar.dev/vue-components/input#qinput-api) says that:
> Array of Functions/Strings; If String, then it must be a name of one of the embedded validation rules
and the examples shows this:
```
:rules="[ 'fulltime' ]"
:rules="[ (val, rules) => rules.email(val) || 'Please enter a valid email address' ]"
```

The second parameter of the last validation method is not described anywhere (in fact, the first one is also not described, but it's more obvious). I assumed that it would be an object with the built-in helper methods. But in run time, `rules` was was not defined and the method threw an exception. 

I'm not sure if this is a problem in docs and this example is wrong, or if this is a bug, or if I just don't understand something.
Also, it is not clear from the docs how to set the error-message when you use the built-in validators. Because when you just provide a string instead of a method, you can't return anything...

### Documentation Section URL

https://quasar.dev/vue-components/input

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by MilosPaunovic** [comment]
Take a look at this https://github.com/quasarframework/quasar/pull/14403, it should bring solution to your issue, but use it with caution, as it might get reverted soon, you'll see more details on the PR link I've sent you.

**Comment by Tofandel** [comment]
@danbars What version of quasar are you using? This was introduced in 2.8.3 (12 days ago) make sure you're up to date

But yes as mentionned in the PR, if you want to use core rules, it's safer to use
```
import { patterns } from 'quasar'

const { testPattern: rules } = patterns;

<q-input
  :rules="[
    (val) => rules.email(val) || 'Please enter a valid email address'
  ]"
/>
```

Instead of the second parameter

The list of available rules is there https://github.com/quasarframework/quasar/pull/14403/files#diff-f6adc30352a1c43a7a6a109df0d563fb499b2430181caa9423c8b9d0a51f5753

**Comment by danbars** [comment]
I'm on an older version, this is why it didn't work.
I'll use the import as mentioned. Thanks.
I think once the PR is reversed, this code snippet should be documented.

I'm closing this ticket. Thanks!
