### ISSUE TITLE
QTree - bad performance / freeze if loaded with relatively large data

### ISSUE THREAD

**Issue by hermit99** [quasarframework/quasar#14521]
### What happened?

When load QTree with relatively large data, eg. 30K nodes, expandAll() or tick at root node, UI will be extremely slow that the browser literally freezes. Checking Task Manager on my Windows PC, CPU >11%, power usage very high and memory usage bumps up to ~3GB. CPU usage will come down to normal (<1%) after the rendering is finished several minutes later.

### What did you expect to happen?

With large data, slowness is expected, but ideally it shouldn't block the renderer, at least allow other components such as spin to render and indicate.

### Reproduction URL

https://codepen.io/hermit99/pen/QWrOYqJ?editors=1010

### How to reproduce?

1. Go to the reproduction link
2. Click "Expand All" button
3. UI lost response
4. Observe CPU and Mem usage

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge, Electron

### Additional context

I don't want to walk around using lazyload as tens of thousands of node shouldn't be tree component's limit. Also tuning `duration` prop had no effect.

Looking into QTree.js, I suspect QSlideTransition is the root cause, but I can't verify:

1. if there were memory leaks in QSlideTransition, or
2. if the performance penalty comes from Vue's Transition or QTree implementing transition using js instead of css

If QSlideTransition is the culprit, can we add a prop in QTree to turn the transition off then?

**Comment by rstoenescu** [comment]
New Boolean prop `no-transition` will be available in Quasar v2.9.2
