### ISSUE TITLE
Backspace removes value in q-selects **without** clearable prop

### ISSUE THREAD

**Issue by Noxdor** [quasarframework/quasar#14522]
### What happened?

The problem is pretty straight forward. We have selects in our company project, where we don't ever want the user to fully remove the input. We select a default option and the user can change it if he wants to. We expect that - as long as the `clearable` prop is not set - it is not possible to remove the selected value.
This doesn't appear to be the case. Either we misunderstand the intended behaviour, or this is small but hugely problematic bug that allows the user to cause unintended behaviour. What happens is, that if you have a value selected, open the select by left clicking it and then press backspace, the value is removed.

### What did you expect to happen?

I expected nothing to happen. As long as `clearable` is not set, it should not be possible to remove the value.

### Reproduction URL

https://quasar.dev/vue-components/select#introduction

### How to reproduce?

1. Take the first `q-select`. Open it by left clicking and select any value.
2. Open it again and press `Backspace` to remove the value.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Quasar info output

```Shell
Operating System - Linux(5.19.11-zen1-1-zen) - linux/x64
NodeJs - 16.16.0

Global packages
  NPM - 8.11.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.0-beta.14 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - 2.0.13 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.12.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Additional context

The problem probably exists on all platforms, Chrome, Edge and Firefox are the ones we tested.

**Comment by MilosPaunovic** [comment]
That is documented behaviour:
https://quasar.dev/vue-components/select#keyboard-navigation:~:text=from%20the%20selection-,pressing,is%20set%20the%20input%20should%20be%20empty),-pressing

**Comment by Noxdor** [comment]
Thank you for providing me the acnchored link, I looked but couln't find anything about it. Imo that as default behaviour is problematic, but that is your call. Is there a native option though to disable this behaviour? I couln't find anything about that either.

**Comment by pdanpdan** [comment]
You can listen on the `@input` / `@update:model-value` event and set back the original value in a `nextTick` if the new value is empty

**Comment by Noxdor** [comment]
Thank you for the help, I will close this issue now.
