### ISSUE TITLE
quasar dev -m capacitor -T android: Error. This command must be executed inside a Quasar v1+ project folder.

### ISSUE THREAD

**Issue by xiangnanscu** [quasarframework/quasar#14538]
### What happened?

when I run `quasar dev -m capacitor -T android`, error:
```
 App • ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.  
```

### What did you expect to happen?

no error

### Reproduction URL

https://github.com/xiangnanscu/pan1.git

### How to reproduce?

run `quasar dev -m capacitor -T android`,

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Android

### Quasar info output

```Shell
$ quasar info

 App • ⚠️  Error. This command must be executed inside a Quasar v1+ project folder. 
```
```


### Relevant log output

_No response_

### Additional context

_No response_

**Comment by xiangnanscu** [comment]
I just run `npm init quasar` like below . What could I do to make quasar cli work normally?
```
$ npm list --global
C:\Users\xn\AppData\Roaming\npm
├── @quasar/cli@1.3.2
└── eslint@7.24.0

$ npm init quasar


 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

√ What would you like to build? » App with Quasar CLI, let's go!
√ Project folder: ... pan
√ Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
√ Pick script type: » Javascript
√ Pick Quasar App CLI variant: » Quasar App CLI with Vite
√ Package name: ... pan
√ Project product name: (must start with letter if building mobile apps) ... Pan App
√ Project description: ... A Quasar Project
√ Author: ... xn <280145668@qq.com>
√ Pick your CSS preprocessor: » Sass with SCSS syntax
√ Check the features needed for your project: » ESLint, State Management (Pinia), Axios
√ Pick an ESLint preset: » Prettier

 Quasar • Generating files...
```

**Comment by xiangnanscu** [comment]
turned out `npm uninstall @quasar/app` solved my problem. But the official doc says [You will need quasar v2.0.0-beta.8+ and @quasar/app v3.0.0-beta.8+.](https://quasar.dev/quasar-cli/developing-capacitor-apps/capacitor-version-support#capacitor-v3), I need to use capacitor-v3, that's why I mannually install `@quasar/app`.

**Comment by rstoenescu** [comment]
There's no mention anywhere of `@quasar/app` on the indicated page. Actually, anywhere in the docs for that matter.
For Quasar v2, the CLI evolved into two variants: the Webpack one and the Vite one. So whatever you do, do not install the obsolete `@quasar/app`.

**Comment by xiangnanscu** [comment]
@rstoenescu At lease when I submit this issue, there is
![image](https://user-images.githubusercontent.com/8246344/193461953-8df14bd5-06c5-45d7-bbd2-57ee5b27d463.png)

**Comment by rstoenescu** [comment]
Please clear your browser cache and/or remove the installed PWA, because that is NOT the current docs. You must be having a VERY old version of it, for some reason.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/4665641/193466871-5f847a69-1fa0-41af-aa6b-8509de595703.png">
