### ISSUE TITLE
QTable - Hiding the noResult row

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1453]
### Software version

Quasar:0.15 (beta 7)
OS:Windows & Linux
Node:8.9.3
NPM:5.5.1
Browsers:Chrome & Firefox
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
If we set the prop `hideBottom` to `true` we are still seeing the `noData` row.

### What were you expecting?
Can we add another property to hide the `noData` row ? Like `hideNoResultLabel` ?

**Comment by rstoenescu** [comment]
Property "hideBottom" will also hide this.
Will be available shortly in beta.9
