### ISSUE TITLE
QRange :min and :max bind to variable

### ISSUE THREAD

**Issue by Nattapong-sir** [quasarframework/quasar#1455]
Quasar: 0.14.7
OS: Windows 7
Node: 8.9.4
NPM: 5.6.0
Browsers: Chrome 63.0.3239.132

### What did you get as the error?
- Max side is less that actual max value store in variable
- Range error: min >= max appear in console when dragging min to 75% length of max.
- Click on max side of slider and label will show max value equal to variable's max. Drag it a bit to the left and max side become less than variable's max.

### What were you expecting?
- Min and Max side of slider equals to value store in variable.
- Min can be slide to max without breaking QRange

### What steps did you take, to get the error?
q-range(:min="a.min" :max="a.max" :step="1" v-model="b" label)
where a is an object containing attribute min = 1 and max = 3.

**Comment by rstoenescu** [comment]
Hi,

I've re-tested everything on v0.15. Here's a jsfiddle: https://jsfiddle.net/rstoenescu/w9coused/
Seems to be working correctly. Not much has changed on v0.15 vs v0.14, so it should work on v0.14 too. Unfortunately, don't have time right now to also test on v0.14. Focusing solely on v0.15. Will close this as on v0.15 it works.

Feel free to reopen by updating the jsfiddle with a possible non-working case of your issue. Thank you!
