### ISSUE TITLE
Type definition for Quasar.lang is incorrect

### ISSUE THREAD

**Issue by GielDeClercq** [quasarframework/quasar#14569]
### What happened?

The global Quasar object's (imported via `import { Quasar } from 'quasar'`) lang property differs from its type. In my case it was the rtl property.

### What did you expect to happen?

EITHER 
`Quasar.lang.rtl` returns me the `true` or `false` instead of undefined
OR
  The Typescript definition of that object tells me that I need to use `Quasar.lang.props.rtl` instead of throwing a type error.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-8o5cld?file=src/pages/index-page.ts

### How to reproduce?

1. Go to the Reproduction URL and start up the application (npm run dev)
2. Check the `index-page.ts` file and you'll see that there is a Typescript error on line 5.
3. Check the `IndexPage.vue` file and the preview and you'll see that the method using `Quasar.lang.rtl` doesn't give the correct output while the method using the (according to Typescript, faulty) `Quasar.lang.props.rtl` does give the correct output.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar), TypeScript Support

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.14.6
