### ISSUE TITLE
Quasar vite production is not rendering the components

### ISSUE THREAD

**Issue by sabasayer** [quasarframework/quasar#14578]
### What happened?

I followed the documentation for vite and created a simple project with vite + vue3 + Quasar2 . 
Development is fine but at the production build Quasar components are not built.

![image](https://user-images.githubusercontent.com/45066901/194555518-261a2e05-058c-43ec-83cb-d55110854533.png)

"@quasar/vite-plugin": "^1.2.3",
"quasar": "^2.9.2",
"vite": "^3.0.9"

I tried removing quasar method from vite.config. It works but it shouldn't be the fix.

### What did you expect to happen?

Quasar components must be rendered at the production build.

### Reproduction URL

 https://github.com/sabasayer/vue3-quasar-test

https://vue3-quasar-test-1specqo00-sabasayer.vercel.app/

### How to reproduce?

`pnpm i`
`pnpm run build`
`pnpm run preview`

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You use PascalCase for the component names
Go to https://quasar.dev/start/vite-plugin#using-quasar and select PascalCase and adjust your config

**Comment by sabasayer** [comment]
> You use PascalCase for the component names Go to https://quasar.dev/start/vite-plugin#using-quasar and select PascalCase and adjust your config

Thank you it resolved my problem. But some other people can also have the same problem. A warning would be good like:  'if you don't do this configuration, your production build will not work'

**Comment by rstoenescu** [comment]
This is why I wrote the configurator on the docs. The default is kebab case and you don't need anything extra, however for non-default you need to specify this option.
