### ISSUE TITLE
QLayout scroll bar make a space between QPageContainer and QDrawer with reload

### ISSUE THREAD

**Issue by wowissu** [quasarframework/quasar#14573]
### Description

It have a space between QPageContainer and QDrawer when ever reload and space width same as scrollbar
And QDrawer covered on right side scrollbar
Is fix after trigger fold or unfold

<img width="892" alt="截圖 2022-10-07 下午1 04 40" src="https://user-images.githubusercontent.com/12434914/194472568-568b697e-e828-4f0b-aa7a-e5c633d0334c.png">

### Documentation Section URL

https://quasar.dev/layout/layout

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Root caused the problem. Will push a fix in a few hours.

**Comment by rstoenescu** [comment]
Thanks for reporting this!
Fix will be available in 2.9.3
