### ISSUE TITLE
QPagination text color doesn't work

### ISSUE THREAD

**Issue by tomukasas** [quasarframework/quasar#14577]
### What happened?

As title says

### What did you expect to happen?

Text color to work

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-aun8hn?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to reproduction link
2. Notice the text color is blue, while it should be black based on `text-color="black"` prop

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
I think you want this: https://codepen.io/pdanpdan/pen/wvjEbbw?editors=101

@rstoenescu I think `text-color` is useless (not used) for QPagination and we should remove it

**Comment by tomukasas** [comment]
`color` prop is used for background color on other components, so from consistency point of view it would be wise to keep that naming pattern and set the background color, not the text color.

**Comment by pdanpdan** [comment]
All buttons that are not active are flat
And for active there is activeColor and activeTextColor

**Comment by tomukasas** [comment]
`active-text-color` works fine :) the bug is about `text-color`

**Comment by pdanpdan** [comment]
In the implementation both do the exact same thing. If you don't set activeTextColor then textColor will work :)

**Comment by tomukasas** [comment]
And what should I do if I need both? :)

I don't mind adding some custom css to override the look and feel to how I want, just trying to save couple code lines :D

**Comment by pdanpdan** [comment]
That was the question. What do you want to do?

**Comment by tomukasas** [comment]
To set correct colors for buttons :)

How I imagine it should work is - `text-color` should be set for all buttons, `active-text-color` should be set only on the active button. Hope that makes sense.

**Comment by pdanpdan** [comment]
Isn't it what I posted first?
https://codepen.io/pdanpdan/pen/wvjEbbw?editors=101

Flat buttons only have one color (color)

**Comment by tomukasas** [comment]
Right, What if I want red background color and white text? And for active button I want white background and black text?

**Comment by pdanpdan** [comment]
As I said, all not active buttons are flat, so no bg

**Comment by tomukasas** [comment]
Ok, got it, thanks :)

**Comment by rstoenescu** [comment]
@tomukasas 

Thank you for opening this ticket. There were lots of issues with the current implementation in regards to the design.
Everything will work as expected now, with new possibilities as well. You will be able to also pick the active btn design (flat/outline/push/unelevated/default). The "active-color/text-color" props will work as expected. Also added a new prop for the gutter. Also did some perf work with this component.

The goodies will land in Quasar v2.9.3

**Comment by webnoob** [comment]
Thanks @rstoenescu :)
