### ISSUE TITLE
Not working when more than one route?

### ISSUE THREAD

**Issue by artem0071** [quasarframework/quasar#1457]
I'm using router history.
.htaccess like in documentation:
`RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]`

All is good when I dev project and going to example.com/ or example.com/home all is good
But when there is more than one route, like example.com/user/1 or example.com/group/xxx project not working and there is some errors with path of files

To improve it I set "/" before every imported file in index.html
example: 
this -> href=statics/manifest.json
turns this -> href=/statics/manifest.json
and so on..

Is there some another solution?

**Comment by rstoenescu** [comment]
Hi,

Please make sure you are configuring publicPath (from /config/index.js) correctly in order to match how your server works.
Here is a guide on how to configure your server: https://router.vuejs.org/en/essentials/history-mode.html

**Comment by artem0071** [comment]
As I say before I configurated server as it says in this documentation https://router.vuejs.org/en/essentials/history-mode.html

When I entered site via example.com or example.com/main and then go to example.com/user/1 everything works fine

But when I entered directly through example.com/user/1 there are errors with not founded files

**Comment by rstoenescu** [comment]
There must be something wrong in the way that you configured the server. The very thing that docs is there is to help add redirects to index.html for each URL, because index.html will serve any incoming request no matter the URL. Make sure you remove any 404 config in your server or put that last, otherwise 404 will override the URL rewrite rules.

Please use the chat (Gitter) or forum if something is still not right in your config.
Thank you.

**Comment by aaronguostudio** [comment]
Thanks @rstoenescu 

I had the same issue. I was using quasar-cli 0.65 to generate a project. There are routes: /a and /a/b in the project. If I enter url domain.com/a in the browser manually, it works fine. But if I enter domain.com/a/b, the web page will be blank.

After I config the publicPath in /config/index.js, it works.

build: {
    env: require('./prod.env'),
    publicPath: '/',  
    ...
