### ISSUE TITLE
QUpload "filter" property

### ISSUE THREAD

**Issue by dwoutsourcing** [quasarframework/quasar#1458]
When used in conjunction with validators, each file may be either "accepted" or "rejected"
In such cases, adding & removing files from the upload queue list would be a very useful feature.

By now we can listen to the @add event but we have no way to reject files (remove them from the list when some criteria is not satisfied)

**Comment by rstoenescu** [comment]
Agreed, will do.

**Comment by simon-the-sloth** [comment]
Is there an ETA for this? Having a clear() method, or ability to remove files one by one would come really handy.

**Comment by rstoenescu** [comment]
Available in v0.17.9 through "filter" Function prop:
```js
filter (files) {
  .....
  return filteredFiles
}
```
