### ISSUE TITLE
Hot reload seems broken for Webpack but works in Vite (FreeBSD)

### ISSUE THREAD

**Issue by jhfoo** [quasarframework/quasar#14590]
### What happened?

Created a boilerplate app via @quasar/cli per online documentation using webpack. Hot reload in dev mode responds to change in quasar.config.js but not other .js (e.g. router/index.js) and .vue (e.g. App.vue) files.

Rebuilt same boilerplate using Vite and hot reload works as expected.

### What did you expect to happen?

Hot reload for boilerplate app should work in Webpack as it does in Vite.

### Reproduction URL

NA

### How to reproduce?

1. Login to freebsd console
2. Create app using online tutorial and configure webpack as transpiler
3. Run in dev mode
4. Change IndexPage.vue
5. Observe if change reflects automatically on browser.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
%quasar info                       

Operating System - FreeBSD(13.1-RELEASE) - freebsd/x64
NodeJs - 16.16.0

Global packages
  NPM - Not installed
  yarn - 1.22.18
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.9.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.40 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.23 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.25.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by pdanpdan** [comment]
I suppose there is a problem with webpack watch on FreeBSD
See if something from here helps: https://stackoverflow.com/questions/26708205/webpack-watch-isnt-compiling-changed-files

**Comment by rstoenescu** [comment]
Hi,

This has to do exclusively with Webpack and its dependencies, and not with Quasar.
Closing.
