### ISSUE TITLE
@click event doesn't throw any warning on console

### ISSUE THREAD

**Issue by akash-melkeri** [quasarframework/quasar#14593]
### What happened?

Quasar didn't throw any warning even though I had an undefined property.
This property was used in one of button's `@click` event.

### What did you expect to happen?

I wanted quasar to throw following warning,

> [Vue warn]: Property "abc" was accessed during render but is not defined on instance.

But it didn't throw any warning as it should.

### Reproduction URL

https://jsfiddle.net/0Lfy58cx/

### How to reproduce?

**Extra Info :**
- I am running this on devserver.

On reproduction link, You see a button which has `@click` event.
Which is used for assigning an undefined property.
And in my opinion,
It should throw error as :

> _[Vue warn]: Property "abc" was accessed during render but is not defined on instance._

Which it doesn't.
That makes it harder for senior developer debug a code.
As he/she wont check each and every line of the code to solve problems.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Components (quasar)

### Platforms/Browsers

Chrome

### Additional context

As I was looking throw the code. I never notice an unused and undefined property.
And also quasar didn't show any warning on the console.

This Issue didn't cause much problem for me.
But I think it may cause problems for someone else.

I suggest to add check for events too.
I Haven't tested for any other events as I have lot pressure of my work already :hot_face: .
So, Please do the needful testing for other events as well.

AND,
Kudos :tada:  to the Quasar Team for making such great Framework.

**Comment by metalsadman** [comment]
jsfiddle/codepen are using production version of vue, change it to non prod version to see the error messages.

**Comment by pdanpdan** [comment]
You mean
https://sfc.vuejs.org/#eNo9j71uwzAMhF+F4JKlseDVUIJ260NwSR06Vhr9QKTbQdC7R0qCbLzj4eOx4FdKw9/GOKGVObukIKxbOlJwPsWsUCDzAhWWHD3sWnRHwZpntqWaUPbpdlJuCsCuI3zONzf/HgiVReEAI+HxmzODRM+6unCBLZx5cYHPExCWAo9krYTWrGMDWfOm4gc+q+z9KQ1XiaGVLf0WvRZCOMHD6V6r2DXhqppkMkaWub94lSHmi2nTkLegzvPA4vc/Of4L5wYm7IhKoWK9A1q4YK8=

This is the linter's / language server job so please check your linter of if you use VScode your volar configuration
