### ISSUE TITLE
QBreadcrumbsEl has useless "ripple" prop

### ISSUE THREAD

**Issue by KareemDa** [quasarframework/quasar#14602]
### Description

Check [Breadcrumbs EL Docs Page](https://quasar.dev/vue-components/breadcrumbs#qbreadcrumbsel-api)

It has a prop called: "ripple" but this prop is never used

You can check the component. It's never used there

### Documentation Section URL

https://quasar.dev/vue-components/breadcrumbs#qbreadcrumbsel-api

### Areas

Components (quasar)

**Comment by MilosPaunovic** [comment]
Seems like you are correct. Would you care to make a PR for a fix?

**Comment by KareemDa** [comment]
Sure. I'll push it within 1 hour

**Comment by KareemDa** [comment]
@MilosPaunovic 
Kindly check [14603](https://github.com/quasarframework/quasar/pull/14603)

**Comment by rstoenescu** [comment]
Fixed by PR (removed non-existent prop)
