### ISSUE TITLE
QSlider step value doesnt' step as specified.

### ISSUE THREAD

**Issue by Nattapong-sir** [quasarframework/quasar#1461]
### Software version

Quasar: 0.14.7 and 0.15 beta 9
OS: Windows 7
Node: 8.9.4
NPM: 5.6.0
Browsers: Chrome  63.0.3239.132

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/wd0gcvxv/4/

### What did you get as the error?
Slider for step = 0.1 get very tiny fraction added.
For example 1.900000001

### What were you expecting?
Exact 0.1 step. No tiny fraction added.

### What steps did you take, to get the error?
Simply add step and label to slider and problem showup.

**Comment by rstoenescu** [comment]
Will be available in next Quasar v0.15 beta. Thank you for reporting.
