### ISSUE TITLE
Table: Virtual scrolling cannot follow tables into dark mode

### ISSUE THREAD

**Issue by jack3018** [quasarframework/quasar#14634]
### What happened?

Table: Virtual scrolling cannot follow tables into dark mode

### What did you expect to happen?

Table: Virtual scrolling should automatically switch to dark mode following the table

### Reproduction URL

https://codepen.io/jack3018/pen/jOxdoLZ

### How to reproduce?

See codepen

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari

**Comment by pdanpdan** [comment]
What do you mean? What is not working?
Closing - we'll reopen if we have a proper explanation of the problem.

**Comment by jack3018** [comment]
When QTable is switched to dark mode, the scrollbars at the sides and bottom of the table remain in light mode.  It doesn't match the theme

<img width="798" alt="102843@2x" src="https://user-images.githubusercontent.com/2884203/196321417-bdece0cd-45d5-40a8-bce9-59a4028a5276.png">
