### ISSUE TITLE
[ERROR] - Unexpected border-top In QField When Using "helper" or "error-label" props

### ISSUE THREAD

**Issue by imdanielpiva** [quasarframework/quasar#1463]
### Software version

Quasar: 14.7
OS: deepin Linux
Node: 9.4.0
NPM: 5.6.0
Browsers: Chrome 63.0.3239.84, Firefox 57.0.4
Any other software related to your bug:

### What did you get as the error?
An unexpected border-top shows up when using q-field "helper" or "error-label" props

### What were you expecting?
No border
### What steps did you take, to get the error?
Just used the props

## Screen-shot
![deepinscreenshot_select-area_20180122081414](https://user-images.githubusercontent.com/26178791/35215860-c8d530c4-ff4c-11e7-88a3-330567a229f7.png)

**Comment by pdanpdan** [comment]
Can you please share the code that produces this problem?
If this is not possible then please attach a screenshot of the chrome inspector (with styles) when you have the helper or the error-label selected in inspector.

**Comment by imdanielpiva** [comment]
### Other info

I've made a component, which has this snippet below, but when I run the `yarn dev` it happens, but using the same component inside storybook it works fine.

### Snippet

```html
<q-field
    icon="description"
    :error="validation.hasError('entityName')"
    :error-label="validation.firstError('entityName')"
    class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12"
>
        <q-input
	    v-model="entityName"
            @keyup="unmaskStr(entityName)"
            :error="validation.hasError('entityName')"
	    float-label="Entity name"
        />
</q-field>
```

### DevTools screen-shots

![deepinscreenshot_20180122103127](https://user-images.githubusercontent.com/26178791/35223299-fc6d310a-ff67-11e7-92e4-700f8d0683c1.png)
![deepinscreenshot_20180122113119](https://user-images.githubusercontent.com/26178791/35223300-fc89af88-ff67-11e7-8e88-a48b289ba4cf.png)
![deepinscreenshot_20180122113133](https://user-images.githubusercontent.com/26178791/35223301-fca88124-ff67-11e7-8015-73f099c04f1c.png)
![deepinscreenshot_20180122113143](https://user-images.githubusercontent.com/26178791/35223302-fcc80e04-ff67-11e7-9537-79413cb02aa3.png)
![deepinscreenshot_20180122113212](https://user-images.githubusercontent.com/26178791/35223303-fce621fa-ff67-11e7-81dc-5e1285186ff3.png)

**Comment by pdanpdan** [comment]
Thank you, I found the problem.

**Comment by imdanielpiva** [comment]
Could you give me some info about this?

**Comment by pdanpdan** [comment]
It looks like the control element (QInput in this case) is not registered properly inside the QField when using dev/HMR.
You can check this by doing a little test for me:
- start with ```yarn dev```
- refresh the browser => all should be good
- change something in the code => the browser should be updated => it should look bad
- refresh the broser => all should be good

Please let me know if this is what happens.

**Comment by imdanielpiva** [comment]
Nope, it's not. I've seen this behavior with QModal, but not with QField.

PS: I ran `yarn build` command already and the took a look at the dist version, the same problem.

**Comment by rstoenescu** [comment]
Fix available in next Quasar beta. https://github.com/quasarframework/quasar/pull/1469

**Comment by imdanielpiva** [comment]
Thanks, @rstoenescu!
