### ISSUE TITLE
When QTable is switched to dark mode, the scrollbars at the sides and bottom of the table remain in light mode. It doesn't match the theme

### ISSUE THREAD

**Issue by jack3018** [quasarframework/quasar#14640]
### What happened?

When QTable is switched to dark mode, the scrollbars at the sides and bottom of the table remain in light mode. It doesn't match the theme

<img width="798" alt="102843@2x" src="https://user-images.githubusercontent.com/2884203/196325013-926c21d6-7ae2-444e-9275-e8ef0bc4fcca.png">

### What did you expect to happen?

Scroll bar Dark mode

<img width="1121" alt="110111@2x" src="https://user-images.githubusercontent.com/2884203/196325915-ddfc0d06-b321-485b-9fea-fa1fbc65f48e.png">

### Reproduction URL

https://codepen.io/jack3018/pen/jOxdoLZ

### How to reproduce?

none

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
These are the native scroll bars of the browser. QTable uses native scroll

**Comment by MilosPaunovic** [comment]
@jack3018 And you can style them pretty easy - https://codepen.io/milospaunovic/pen/ExLJqqb.
