### ISSUE TITLE
QButton Dropdown flat does not work with split

### ISSUE THREAD

**Issue by jblyberg** [quasarframework/quasar#14657]
### What happened?

When using the `q-btn-dropdown` component with the split prop, the flat prop does not work. The button appears elevated

### What did you expect to happen?

The button should be flat and un-elevated when using the split and flat props together.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-b4au8c?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Go to provided reproduction URL
2. Button will display as elevated

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.10.1
