### ISSUE TITLE
Autofocus not working on q-select version 2

### ISSUE THREAD

**Issue by jmriyaz84** [quasarframework/quasar#14652]
### What happened?

Dropdown is not getting populated when I set autofocus on q-select

### What did you expect to happen?

Dropdown is populate the data when I set autofocus on q-select , it is working well in version 1 but not in version 2

### Reproduction URL

https://codepen.io/jmriyaz84/pen/eYraQQo

### How to reproduce?

Just add autofocus in q-select & check the behaviour

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment]
https://codepen.io/milospaunovic/pen/VwxOqwP?editors=1111

**Comment by pdanpdan** [comment]
you have no options
