### ISSUE TITLE
Vue-router, transitions and scrollBehavior - Page jumping back to top or changing scroll location

### ISSUE THREAD

**Issue by realcarbonneau** [quasarframework/quasar#1466]
There is currently a problem with the vue-router and vue-transitions (outside of Quasar) that causes pages to jump back to the top before transitions and also to change scroll location when doing popstate navigations (browser back and forward buttons.  Here are some details, please post comments or questions on this topic here.

vue-router with scrollBehavior currently works when there are NO transitions.  The users scroll position will be retained between popstate navigations.
```
export default new VueRouter({
  // mode: 'history',
  routes,
  scrollBehavior (to, from, savedPosition) {
    if (savedPosition) {
      // Keep scroll position when using browser buttons
      return savedPosition
    }
    else {
      return { x: 0, y: 0 }
    }
  }
})
```

Additionally, to ensure that the component state is retained (eg form field data, opened tabs, etc.) the keep-alive must be used
```
      <keep-alive>
        <router-view></router-view>
      </keep-alive>
```

For transitions on routes, there is a new Async scrollBehavior, but there are still some issues that are currently being worked on by the vue team.  Here is the current partial solution. Note that the scrollBehavior delay is 1 second and the transition is 0.5s to emphasize the mechanics in play here.
```
export default new VueRouter({
  // mode: 'history',
  routes,
  scrollBehavior (to, from, savedPosition) {
    let position = { x: 0, y: 0 }
    // Keep scroll position when using browser buttons
    if (savedPosition) {
      position = savedPosition
    }

    // Workaround for transitions scrolling to the top of the page
    // However, there are still some problems being fixed by the vue team
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(position)
      }, 1000)
    })
  }
})
```

References:
https://router.vuejs.org/en/advanced/scroll-behavior.html

**Comment by pdanpdan** [comment]
This example might be useful:

https://github.com/vuejs/vue-router/blob/dev/examples/scroll-behavior/app.js

**Comment by realcarbonneau** [comment]
That is the simplest use case, and it will do jumps in scroll position when combined with transitions.  

Note line 24-26 of your example:
```
  if (savedPosition) {
    // savedPosition is only available for popstate navigations.
    return savedPosition
```

See the video, it's aweful :S
![vueroutertransitionscrollposition](https://user-images.githubusercontent.com/29619229/35241493-a5baf032-ff84-11e7-974a-c9123022b863.gif)

**Comment by Jamiewarb** [comment]
I'm also having this issue and looking for a solution

**Comment by piotrek-horodenski** [comment]
same problem here, scroll behavior should be invoked not sooner than leave transition finishes, I will probably temporarly fix it with disabling scroll behavior and emulate proper behavior manually

**Comment by yiqianglin** [comment]
I'm also having this issue and looking for a solution

**Comment by tkiley** [comment]
I had this same problem. It looks like modern browsers set the scroll to savedPosition immediately when you navigate using the browser buttons, so returning a promise from scrollBehavior does not fix the flickering issue entirely.

In order to prevent the browser's default behavior, do this:

`if ('scrollRestoration' in history) {
  history.scrollRestoration = 'manual';
}`

Perhaps this should be included in the docs or should be set by the router by default?

**Comment by joantune** [comment]
Why is this closed? I'm getting the same issue with the <transition element without using VueRouters

**Comment by cybercussion** [comment]
Agreed I'm also having this issue still.

**Comment by nothingismagick** [comment]
Did you try this approach example @cybercussion ?
https://github.com/quasarframework/quasar/issues/1466#issuecomment-416495843

**Comment by cybercussion** [comment]
@nothingismagick I used tkiley's approach and its good in Safari/Chrome.  I think my cache was sticking.

**Comment by Mighty683** [comment]
> I had this same problem. It looks like modern browsers set the scroll to savedPosition immediately when you navigate using the browser buttons, so returning a promise from scrollBehavior does not fix the flickering issue entirely.
> 
> In order to prevent the browser's default behavior, do this:
> 
> `if ('scrollRestoration' in history) { history.scrollRestoration = 'manual'; }`
> 
> Perhaps this should be included in the docs or should be set by the router by default?

I think such information should be placed in documentation

**Comment by pdanpdan** [comment]
Please head to VueRouter for this, thank you.

**Comment by suneetjain** [comment]
> Please head to VueRouter for this, thank you.

There is no support from Vue, I even tried the documentation [Vue Router - Scroll Behaviour](https://router.vuejs.org/guide/advanced/scroll-behavior.html) but no success.

To every page I navigate back, the page is scrolled to top. Quasar should provide some support on this.

**Comment by pdanpdan** [comment]
It's up to you to decide what you need.
Also, as far as I know, vue-router has good docs and even an example here: https://github.com/vuejs/vue-router-demos/blob/master/examples/scroll-behavior/index.js

And Google if full of examples: https://www.google.com/search?q=vue-router+scrollBehaviour+example&pws=0&gl=us&gws_rd=cr
