### ISSUE TITLE
.js import files in generated client-entry file (typescript)

### ISSUE THREAD

**Issue by avxart** [quasarframework/quasar#14663]
### What happened?

On build the framework generates the client-entry boot imports, this file also includes import references to the JS versions of some of the boot files. This is problematic as I can't find anything referencing those in the code.

I have tried a fresh install, clearing the cache, Quasar clean.

![Capture](https://user-images.githubusercontent.com/23410741/196898490-0b8cdfff-dcb5-41a9-8c39-40f2768bc5f9.PNG)

Any ideas on this?

### What did you expect to happen?

Not the above issue. Doesn't make sense to include those files in the imports twice.

### Reproduction URL

null

### How to reproduce?

_

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Please provide the boot entry from quasar conf file
Also what `@quasar/app-???` are you using (vite or webpack) and what version

**Comment by avxart** [comment]
Here's what my boot entry looks like:
![boot](https://user-images.githubusercontent.com/23410741/196914198-86c4f02a-da19-4886-8fd9-e853b222dee2.PNG)

using @quasar/app-vite: 1.1.2

**Comment by avxart** [comment]
Still haven't been able to figure out the above issue. It happens on other machines as well, even freshly created docker containers.

for now here's a temporary solution in case someone else is experiencing this: 
beforeDev() {
  const file = __dirname + '/.quasar/client-entry.js'
  var data = fs.readFileSync(file, 'utf-8')
  var toBeRemoved = [
    "import('boot/axios.js'),",
    "import('boot/vuelidate.js'),",
    "import('boot/auth.js')"
  ]

  toBeRemoved.forEach(function (item) {
    data = data.replace(item, '')
  })
  fs.writeFileSync(file, data, 'utf-8')
},

Add it into your quasar.config.js -> build
