### ISSUE TITLE
Can't close modal after I change code

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar#1467]
Hello, there is no problem with modal in production, but there is problem in development
When I run `quasar dev` and use modal in my app its working fine
But when I change something in my code, I have to re-run `quasar dev` command, because if i won't - i can't close modal, not by function and not by Esc button, or click on backdrop

**Comment by imdanielpiva** [comment]
That's because of the Hot Replacement Module. It's normal, see the docs' disclaimer at the very beginning of the page, second paragraph: http://quasar-framework.org/components/modal

**Comment by rstoenescu** [comment]
Hi, Closing this as it won't happen with v0.15. There are some tickets on the exact same issue where I've explained what is going on.
