### ISSUE TITLE
QDate with locale option crash on production build (SPA)

### ISSUE THREAD

**Issue by loma-cambodia** [quasarframework/quasar#14698]
### What happened?

<q-date
           v-model="range"
           :locale='{
             days: ["星期日", "星期一", "星期二", "星期三", "星期四","星期五", "星期六"],
             daysShort: [ "星期日", "星期一", "星期二", "星期三", "星期四",  "星期五", "星期六"]
           }'
           range bordered>
   
    </q-date>

`range = ref({from : '', to: ''})`

The first selection works and then browser freeze

Console Warning:
Maximum recursive updates exceeded in component <QBar>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

### What did you expect to happen?

Runs fine in dev with warning " Maximum recursive updates exceeded in component <QBar>" but in production build it crashed.

Expected to work in both dev and production with LOCALE props

### Reproduction URL

https://jsfiddle.net/drn7tkyj/11/

### How to reproduce?

1. Go to the provided reproduction link
2.  Select any date range
3. And the try to select another date range. Its not possible to select anymore

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome

### Relevant log output

```Shell
Maximum recursive updates exceeded in component <QBar>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

Maximum recursive updates exceeded in component <BaseTransition>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

**Comment by pdanpdan** [comment]
You are passing the locale as a local object in the template, and that means that every time the component is rendered the locale would change (new object) and this produces a loop
Pass the locale as an object from code

https://jsfiddle.net/7kL9gqp6/4/
