### ISSUE TITLE
Not used import statement

### ISSUE THREAD

**Issue by MerlinEmris** [quasarframework/quasar#14692]
### Description

On https://quasar.dev/options/app-internationalization#create-language-switcher example code there is not used import statement.

`import { ref, watch } from 'vue'`

### Documentation Section URL

https://quasar.dev/options/app-internationalization#create-language-switcher

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Thanks for the PR.
Will be available on next docs deployment.
