### ISSUE TITLE
Provide uniform/standard/documented way of accessing the outer/inner elements of QDialog/QMenu/QTooltip

### ISSUE THREAD

**Issue by ddenev** [quasarframework/quasar#14708]
### What happened?

I have a custom component that wraps QMenu, e.g.:
```js
<template>
  <q-menu ref="menuRef" @show="onShow">
    ... content ...
  </q-menu>
</template>

<script setup>
const menuRef = ref(null)
function onShow () {
  console.log('onShow', menuRef.value.$el)
}
</script>
```

The problem is - upon showing the menu, the `menuRef.value.$el` is resolved to `#text` and not to the actual menu element - please see the codepen below.

### What did you expect to happen?

As explained in this thread - https://github.com/quasarframework/quasar/issues/13628 - refs are resolved after `@show()` - and indeed, I have a QDialog which works OK, but it seems this is not working for QMenu.

### Reproduction URL

https://codepen.io/ddenev/pen/BaVaQLx

### How to reproduce?

1. Go to the repro link
2. Click on the button
3. Check the console output - it shows that menuRef.value.$el is text and not the menu element

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
With components that use portal(QMenu, QDialog, QTooltip) and components that use them internally (QSelect, QPopupEdit, QPopupProxy, QBtnDropdown) you have 2 things:

- a comment that is rendered where the component is in DOM (Vue hierarchy)
- the rendered menu/dialog/tooltip that is placed at the end of the document

your ref is to the comment

https://codepen.io/pdanpdan/pen/rNKNjMy?editors=1010

**Comment by ddenev** [comment]
Thank you @pdanpdan, but I believe you were too quick to close the issue.

Did you notice that I mentioned that the same logic as above actually works for QDialog, i.e. `dialoRef.value.$el` after `@show` on the dialog actually refers to the proper dialog element (which is rendered at the end of the document).

Why the same doesn't work with QMenu?

In addition - is `__qPortalInnerRef` safe to use? it seems internal and I don't see it anywhere in the docs.

**Comment by pdanpdan** [comment]
It's exactly the same for QDialog (updated https://codepen.io/pdanpdan/pen/rNKNjMy?editors=0010)
about `__qPortalInnerRef`, not really :)

**Comment by pdanpdan** [comment]
But if we talk about how to get the read displayed elements please open another issue and request a method to get it for all components

**Comment by ddenev** [comment]
> It's exactly the same for QDialog (updated https://codepen.io/pdanpdan/pen/rNKNjMy?editors=0010) 

that's very strange! it seems that the way the QDialog is created matters! Please check https://codepen.io/ddenev/pen/XWYWMxG?editors=1011

In this example I am creating the dialog using the dialog plugin and in this case `dialogRef.value.$el` shows the correct element (actually the parent with class `.q-dialog`. In this case I could locate the inner element (pointed to by `dialogRef.value.__qPortalInnerRef.value`) without a problem.
While if the dialog is called as a standalone component (your example) then `dialogRef.value.$el` refers to the text.

Is this the bug you want me to report?

**Comment by pdanpdan** [comment]
It's not a bug, just a different way the components are created/used.
I'll reopen this, but please change the title to something like `Provide uniform/standard/documented way of accessing the outer/inner elements of QDialog/QMenu/QTooltip`

**Comment by rstoenescu** [comment]
Do not use internal variables. It will work until it won't.
Will provide a uniform way of accessing the actual content for all portal-based components.

**Comment by rstoenescu** [comment]
`contentEl` will be available on the QDialog/QMenu/QTooltip vue ref and will point to the rendered content.
Quasar v2.10.1
