### ISSUE TITLE
Add shelves icon to Material Icons

### ISSUE THREAD

**Issue by olegbaturin** [quasarframework/quasar#14703]
### What happened?

Material Icon 'shelves' is missed in the '/extras/material-icons'.

### What did you expect to happen?

Material Icon 'shelves' is not missed

### Reproduction URL

https://fonts.google.com/icons?selected=Material%20Icons%3Ashelves%3A

### How to reproduce?

import { matShelves } from '@quasar/extras/material-icons';

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar Extras (@quasar/extras)

**Comment by pdanpdan** [comment]
The icon packs are updated periodically - there is no need to open an issue each time a new icon show up :)
