### ISSUE TITLE
onBeforeUpdate and onUpdate not triggering

### ISSUE THREAD

**Issue by Pero122** [quasarframework/quasar#14714]
### What happened?

I have a simple app with three things:
- counter
- button that increases counter
- onBeforeUpdate and onUpdate hooks 

When I press the increase button the onBeforeUpdate  and onUpdate hooks DON'T trigger (they should just do some console.log)

### What did you expect to happen?

I expected onBeforeUpdate and onUpdate being called and they should do some console.log in the console.

I attached the look of the project:
![quasarBug](https://user-images.githubusercontent.com/24699984/197890165-7332083c-96cb-4b2b-9703-60ffaf55ffe8.png)

### Reproduction URL

https://stackblitz.com/edit/quasarframework-aj9suk?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to link and wait until the project loads (you see text and btn)
2. Open console (F12 or Right click and Inspect)
3. Click the button, counter should increase, but the methods won't trigger

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19044) - win32/x64
NodeJs - 16.15.0

Global packages
  NPM - 8.19.2
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.8.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.39 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.22 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.23.1 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed    

Quasar App Extensions
  *None installed*
```

**Comment by Pero122** [comment]
I tried to replicate this on a pure Vue Vite project and I had NO problem there. The onBeforeUpdate and onUpdate hooks did trigger, so I must be Quasar specific or I must be missing something.

**Comment by pdanpdan** [comment]
The component life cycles are not called because only the content of the slot of QPage changes

```html
<template>
  <q-page class="flex flex-center">
    <div class="q-pa-lg">
      Open console, you will see that onBeforeUpdate and onUpdated are not being
      triggered when counter is being changed
    </div>

    <div
      :onVnodeBeforeUpdate="log('onBeforeUpdate')"
      :onVnodeUpdated="log('onUpdated')"
    >
      {{ counter }}
    </div>

    <button @click="increaseCounter">Increase</button>
  </q-page>
</template>
```

or 

```html
<template>
  <div class="q-pa-lg">
    Open console, you will see that onBeforeUpdate and onUpdated are not being
    triggered when counter is being changed
  </div>

  <div>{{ counter }}</div>

  <button @click="increaseCounter">Increase</button>
</template>
```
