### ISSUE TITLE
Different dataTable design result with quasar dev and quasar build

### ISSUE THREAD

**Issue by z333d** [quasarframework/quasar#1472]
### Software version

Quasar: 0.14.7
OS: macOS High Sierra 10.13.2
Node: v9.4.0
NPM: 5.6.0
Browsers: Chrome 63.0.3239.132 (Official Build) (64-bit)

### What were you expecting?
I'm expecting to browser dataTable in mobile with vertical design like the demo, but the problem is that i have different result with `dev` and `build`, that is to say, with `quasar dev`, the dataTable shows normal result in mobile, but with `quasar build`, the dataTable still show horizontal design in mobile.
![image](https://user-images.githubusercontent.com/11628392/35264507-f5160c38-0057-11e8-860c-6269768ec228.png)

**Comment by rstoenescu** [comment]
Hi,

1. There are several other tickets opened for this.
2. Workaround: disable purifyCSS from /config/index.js
3. No longer a problem in v0.15, so closing.

Thanks.
