### ISSUE TITLE
QEditor: some style actions cannot be undone

### ISSUE THREAD

**Issue by NPi2Loup** [quasarframework/quasar#14761]
### What happened?

On QEditor, some commands cannot be cancelled.
We have observe two cases: 
- **blockquote**: a &lt;blockquote&gt; tag was added each time we hit the command, then we got something like this: 
<blockquote><blockquote><blockquote><pre>See the two different types of dropdowns in each of the "Align" buttons.</pre></blockquote></blockquote></blockquote>. 

- **Formatting** (paragraph, h1,h2,...): you can switch from paragraph to heading, you can change the size of the heading to another one (h2->h3), but you can't go back to the paragraph: the commands have no effect....

Note : Remove formating => didn't work either (don't know if related)

It seems that the problem is only related to Firefox (tested with 91.11.0esr and 106.0.3). 
This problem also affects quasar2.

### What did you expect to happen?

We expect the same behavior as with Chrome.

- blockquote: each hit toogle blockquote

- formatting: selecting the paragraph command on a title text: delete the title tag and put a &lt;p&gt; tag instead

### Reproduction URL

https://codepen.io/pen?&editors=101&prefill_data_id=0a26925a-cb1e-4f4d-8aa1-341e04ee030e

### How to reproduce?

1. go to the reproduction URL (the same as https://v1.quasar.dev/vue-components/editor#examples) with Firefox
2. focus on the first line
3. hit quote button (or CTRL-Q)
4. see the text move to right
5. click on 'view source'
6. see the multiple &lt;blockquote&gt; tag

for headings:
1. go to the reproduction URL (the same as https://v1.quasar.dev/vue-components/editor#examples) with Firefox
2. focus on the first line
3. change to heading3
4. see the text become bigger
5. change to heading4
6. see the text become smaller
7. change to paragraph
8. see the text stay as big as heading4 (some time it work one time => retry step 5 to7)

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Use quasar flavour UMD
v1.22.1
```

**Comment by NPi2Loup** [comment]
Maybe it's related how Firefox implements document.execCommand,and nothing to do with Quasar ?
(Like you say in : this comment https://github.com/quasarframework/quasar/issues/4349#issuecomment-592499344)

**Comment by rstoenescu** [comment]
Hi,

Yes, it's exactly like you said. Nothing we can do in Quasar, unfortunately.
