### ISSUE TITLE
HTML table

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#1478]
Hi!

In v0.14.7 exist classes for HTML table and page in documentation:
http://quasar-framework.org/components/html-table.html

In my app, where I use standalone version of Quasar, I use "responsive" class for my reports.
But in v0.15 I can't find this classes.
Is it possible to styling HTML tables with responsible behavior in 0.15?

Thanks!

**Comment by rstoenescu** [comment]
Hi,

This has been removed from v0.15.

Here's the source code for it if you want to add it in your app. You might need to rename a few CSS classes so it won't clash with QTable, but it's easy to figure this out. https://github.com/quasarframework/quasar/tree/v0.14/src/components/html-table
