### ISSUE TITLE
QLinearProgress does not animate

### ISSUE THREAD

**Issue by BenJackGill** [quasarframework/quasar#14786]
### What happened?

When first adding a QLinearProgress bar to the page it will animate. But then it stops animating after that. All other page loads and page refreshes do not animate the progress bar.

Here is the code I am using:

```
    <q-linear-progress
      :value="0.9"
      class="q-mt-md"
      rounded
      color="primary"
      size="10px"
      animation-speed="1000"
    />
```

### What did you expect to happen?

It should animate on each page load, even when navigating to another page of a SPA and then coming back.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-ybf2jz?file=src/pages/IndexPage.vue

### How to reproduce?

1. Create a QLinearProgress bar using the code provided above.
2. Refresh the page

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System - Darwin(22.1.0) - darwin/arm64
NodeJs - 18.4.0

Global packages
  NPM - 8.12.1
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - 2.5.4
  cordova - Not installed

Important local packages
  quasar - 2.7.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.16
  pinia - 2.0.14 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.18.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - BenBookAir.local
  en0 - 10.10.1.30
```

**Comment by stildalf** [comment]
Perhaps I'm not quite with you there, @BenJackGill , but your example doesn't ever change the `value` of the progress bar, so you won't be seeing much animation.

Have a look at a forked [example](https://stackblitz.com/edit/quasarframework-x1a8qu?file=src/pages/IndexPage.vue).

**Comment by BenJackGill** [comment]
I assumed that on page load it would animate from `0` to the value set. But I guess not?

I can always use the `onMounted` and `setInterval` trick you have done here though :)

**Comment by pdanpdan** [comment]
It only animates when the model changes
See here: https://github.com/quasarframework/quasar/discussions/14643
