### ISSUE TITLE
[Request] Image Gallery Carousel: Title & Subtitle like cards

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1479]
So I'd love to get **title** & **subtitle** functionality on an Image Gallery Carousel like so:

<img width="289" alt="2018-01-24 14 22 28" src="https://user-images.githubusercontent.com/3253920/35316159-66fb8902-0113-11e8-88a9-fbbaf8acf94c.png">

If it's already in the next build I'm sorry if I missed it!
I heard there were some changes already with the carousel, but I couldn't find them. (which branch do I look to see?)

**Comment by rstoenescu** [comment]
Added an example to /dev in Carousel page.

**Comment by mesqueeb** [comment]
@rstoenescu I just wanted to express my gratitude.
I checked your commit, you call it a "small update" but I'm surprised how you immediately made all these changes just for me!
You did a really great job!

I'm rooting for v1.15! Let me know if I can help with anything.
