### ISSUE TITLE
Borderless prop of QField-based components in append slot of other QField-based components not working

### ISSUE THREAD

**Issue by FragsterAt** [quasarframework/quasar#14793]
### What happened?

I try to set borderless prop in QInput (or QSelect or other QField-based component), that is placed in `#append` slot of other q-input and it isn't works.

### What did you expect to happen?

Borderless inner q-field

### Reproduction URL

https://codepen.io/FragsterAt/pen/ExRPGwW?editors=1111

### How to reproduce?

Just open reproduction URL

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Quasar info output

```Shell
Quasar v2.10.1
```

**Comment by pdanpdan** [comment]
QField is not designed to work one inside other one
You need to tweak the CSS if you want that

https://codepen.io/pdanpdan/pen/XWYWwZJ
