### ISSUE TITLE
QSelect 'handle' icon in append slot of QInput incorrectly positioned

### ISSUE THREAD

**Issue by FragsterAt** [quasarframework/quasar#14794]
### What happened?

icon of q-select is placed is pinned to top of component

### What did you expect to happen?

icon of q-select on right height (aligned to baseline, like in standalone QSelect)

### Reproduction URL

https://codepen.io/FragsterAt/pen/oNyxMOL

### How to reproduce?

just open the link

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Quasar info output

```Shell
Quasar v2.10.1
```

**Comment by pdanpdan** [comment]
QField is not designed to work one inside other one
You should put your select in `#after` slot and adjust the spacing if you want
https://codepen.io/pdanpdan/pen/JjZXqqw
