### ISSUE TITLE
[Request] Image Gallery Carousel: Cover images (so there are no black borders)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1480]
I love the Image Gallery Carousel.
But it sizes the height of the Carousel to the biggest picture, and all pictures have black borders.

Similar to the "cover" option on background images in CSS, I'd love for the images to be zoomed so there are no black borders.

<img width="701" alt="2018-01-24 14 45 31" src="https://user-images.githubusercontent.com/3253920/35316907-69ab3b4e-0117-11e8-8653-5e47d3c8fd69.png">

**Comment by rstoenescu** [comment]
Already in v0.15
