### ISSUE TITLE
QInput: Number arrows are not centered vertically when input type number with label

### ISSUE THREAD

**Issue by straurob** [quasarframework/quasar#14800]
### What happened?

When using a `QInput` of type `number` which contains a `label`, then the number arrows are not centered vertically with the component. This becomes even more obvious when adding the `clearable` property.

```
<q-input
  v-model.number="age"
  type="number"
  label="Age"
  clearable
/>
```

![screenshot](https://user-images.githubusercontent.com/18437455/199839182-e3cd920b-6231-4092-ab03-0735282f1cba.png)

### What did you expect to happen?

I would expect the number arrows to be vertically aligned with the clear icon and the component itself.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-txhwbj?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to the reproduction link.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
Those arrows are from the browser and can only be hidden.
