### ISSUE TITLE
electron+typescript build err

### ISSUE THREAD

**Issue by orangebom** [quasarframework/quasar#14819]
### Description

Project Build Options：
![53e7b908cc30a911f0cc1ffd66dd19b](https://user-images.githubusercontent.com/34227259/200105642-c59d7a18-1ae0-431d-8048-eb47cc4332a0.png)
 after run command：
```
quasar build -m electron
```
report error:
```
App • ⚠️   FAIL  electron-packager could not build

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ORANGE~1\AppData\Local\Temp\electron-packager\win32-x64\Quasar App-win32-x64'

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[  UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block,   or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".    
] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

env：
```
"quasar": "^2.6.0",
"vue": "^3.0.0",
"electron": "^21.2.2",
"eslint": "^8.10.0",
"@quasar/app-webpack": "^3.0.0",
"@types/node": "^12.20.21",
```
pc:
Windows 10 19043.2130
ps:
It is normal to create using javascript and can generate an exe

### Areas

TypeScript Support

**Comment by pdanpdan** [comment]
What is the path where you have your code?
It looks like you have some files in `C:\Users\ORANGE~1\AppData\Local\Temp\electron-packager\win32-x64\Quasar App-win32-x64` that are hidden or protected or created by another user.
