### ISSUE TITLE
API level 31

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#14821]
### What happened?

Your app currently targets API level 29 and must target at least API level 31 to ensure that it is built on the latest APIs optimised for security and performance. Change your app's target API level to at least 31.

### What did you expect to happen?

Be able to release a signed app 

### Reproduction URL

https://github.com/modemb/larasar

### How to reproduce?

Releases signed by Google Play
Google will generate and protect an app signing key for your releases

App bundles
https://play.google.com/console/u/0/developers/5386453075777137237/app/4976012055425974295/tracks/4701705948117675044/releases/1/prepare

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Capacitor Mode

### Platforms/Browsers

Android

### Quasar info output

```Shell
Your app currently targets API level 29 and must target at least API level 31 to ensure that it is built on the latest APIs optimised for security and performance. Change your app's target API level to at least 31.
```

**Comment by pdanpdan** [comment]
Update you API in the project - it's the default level in the version of capacitor used

**Comment by modemb** [comment]
tried that without success

**Comment by pdanpdan** [comment]
Have you checked first item on google?
https://ionic.io/blog/update-your-target-android-api-level-by-november-1

**Comment by modemb** [comment]
follow this steps, but cant get it to work

**Comment by lmfmaier** [comment]
Quasar should officially support Capacitor 4, since Capacitor 3 breaks on Api level 31/32 (for example push messaging is no longer working)

You' can't upload API level 30 (Capacitor 3) apps to Play Store anymore, so the current official Quasar release no longer supports Capacitor apps on Android

**Comment by modemb** [comment]
> Quasar should officially support Capacitor 4, since Capacitor 3 breaks on Api level 31/32 (for example push messaging is no longer working)
> 
> You' can't upload API level 30 (Capacitor 3) apps to Play Store anymore, so the current official Quasar release no longer supports Capacitor apps on Android



   updated manually from variables.gradle to api 31, but now getting this error

   You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without the 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported
      public MockCordovaInterfaceImpl(Activity activity) {
            // super(activity, Executors.newCachedThreadPool());
            super((AppCompatActivity) activity, Executors.newCachedThreadPool());
      }
