### ISSUE TITLE
Request: Media Object Component

### ISSUE THREAD

**Issue by Veraclins** [quasarframework/quasar#1484]
I recently started playing around with Quasar and I must confess I fell in love with it almost immediately.
But media objects (like those of Twitter and Facebook)  is one component that I find so helpful and which will be very useful in a project I'm currently working on.
It's there any plans to add such a component to Quasar anytime soon or is there a way to achieve such already?
That's the only thing stopping going all the way with this amazing project.

**Comment by rstoenescu** [comment]
Hi. Are you referring to the logo icons of Twitter/Facebook/Google etc?

**Comment by Veraclins** [comment]
Not just the logo icon. It's a css component present in bulma.io bootstrap and others that makes displaying the tweet and related data like user avatar, likes, time of tweets etc very easy.
You can't check it out on bulma https://bulma.io/documentation/layout/media-object/

**Comment by Veraclins** [comment]
@rstoenescu please check out this pattern with flexbox here https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/media.css

**Comment by rstoenescu** [comment]
Hi,

This is achievable through Quasar [Flex CSS](http://quasar-framework.org/components/flex-css.html). Take a look. It is easy. Don't think it deserves a place in Quasar Core.
