### ISSUE TITLE
<style module> not support Sass/SCSS variables

### ISSUE THREAD

**Issue by LetFree** [quasarframework/quasar#14847]
### What happened?

```
Undefined variable.
   ╷
43 │   border-left: 1px solid $teal-3;
   │                          ^^^^^^^
   ╵
  src\pages\index\index.vue 43:26  root stylesheet
```

### What did you expect to happen?

Compile correctly

### Reproduction URL

https://stackblitz.com/edit/quasarframework-yj25cu?file=src/pages/IndexPage.vue

### How to reproduce?

none

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Will be available through `@quasar/vite-plugin` v1.3.0

For anyone using Quasar CLI with Vite and reading this: don't manually install the package above as it comes by default with the CLI.

**Comment by LetFree** [comment]
Hard work, thank you very much

**Comment by apasov** [comment]
> For anyone using Quasar CLI with Vite and reading this: don't manually install the package above as it comes by default with the CLI.

I'm using latest Quasar CLI with Vite which is `@quasar/app-vite` v1.1.3
But it still uses `@quasar/vite-plugin` v1.2.3 so I get this error.
How soon `@quasar/app-vite` with `@quasar/vite-plugin` v1.3.0 is going to be released?
