### ISSUE TITLE
QImg placeholder-src

### ISSUE THREAD

**Issue by tomukasas** [quasarframework/quasar#14858]
### What happened?

I am not sure if that is a new feature added in v2 or a bug. What happens is that `placeholder-src` doesn't work if there is falsy `src` attribute. Compared to v1 that is a bug as it doesn't work same.

In v1 the `placeholder-src` is showing if the `src` attribute is falsy.

### What did you expect to happen?

To work same as v1

### Reproduction URL

https://codepen.io/tomasj/pen/xxzgJGr?editors=1000

### How to reproduce?

1. Go to the provided link
2. Once the pen loads, notice there is no placeholder shown
3. Change js `const url = ref(null)` to `const url = ref('')` or `const url = ref(undefined)` to see that all falsy values don't bring the placeholder image in

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by tomukasas** [comment]
Placeholder image is cleared here (compiled QImg component):

![image](https://user-images.githubusercontent.com/8329500/201029349-8975ed9d-6cdd-4065-b20b-5be8add20f09.png)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.10.2
