### ISSUE TITLE
Request: Card Style Carousel

### ISSUE THREAD

**Issue by arjitkhullar** [quasarframework/quasar#1486]
This is a request for card style container.

Examples: 
 [Example 1](http://element.eleme.io/#/en-US/component/carousel#card-mode)
 [Example 2](https://codepen.io/anon/pen/WdqemV)

**Comment by nsbabrah** [comment]
yes this will be a good add on.

more example here

[Slick Js](http://kenwheeler.github.io/slick/)

**Comment by arjitkhullar** [comment]
#1670

**Comment by rstoenescu** [comment]
Duplicate of #1670
