### ISSUE TITLE
QDate - changing view "steals" focus even when prevented

### ISSUE THREAD

**Issue by ddenev** [quasarframework/quasar#14878]
### What happened?

As described in this post - https://github.com/quasarframework/quasar/discussions/14841 - `QDate` "steals" the focus from the input element, even when I explicitly set this to be prevented.

I report this as a bug as I checked the code for `QDate` and I haven't been able to find a solid reason why `QDate` does this. In addition, this behavior currently conflicts with my use-case and I haven't been able (although I tried for a week) to find a userland solution to this.

Please, either remove this call to `focus()` or make it configurable.

Thank you!

### What did you expect to happen?

Changing the view should not steal the focus from my input element, when I prevented it explicitly.

### Reproduction URL

https://codepen.io/ddenev/pen/XWYjQKG

### How to reproduce?

All described in the linked post - https://github.com/quasarframework/quasar/discussions/14841

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.10.2 and v1.22.2
