### ISSUE TITLE
Update google icons last update

### ISSUE THREAD

**Issue by helioh3** [quasarframework/quasar#14881]
### What happened?

is it possible to put the latest version of google icons in quasar v1?

### What did you expect to happen?

If you can put the latest versions of google icons I would be very grateful

### Reproduction URL

https://jsfiddle.net/rstoenescu/rmaodk0f

### How to reproduce?

not view icons last update google icons

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar Extras (@quasar/extras)

### Platforms/Browsers

Other

### Quasar info output

```Shell
not view icons last update google icons
```

### Relevant log output

```Shell
not view icons last update google icons
```

### Additional context

not view icons last update google icons

**Comment by pdanpdan** [comment]
Icons are updated periodically. No need to open generic issues for that

**Comment by helioh3** [comment]
Ok. Thanks for answer
