### ISSUE TITLE
[DESIGN/MATERIAL] 24h datetime picker has weird look

### ISSUE THREAD

**Issue by Marcel50506** [quasarframework/quasar#1488]
When using the datetimepicker with the format24h set, the hour-picker displays the hours in one circle going from 0 to 23. This is weird behaviour, since a clock only has 12 hours in a circle.

Android resolves this problem by using two concentric circles of numbers, one ranging from 1-12, the other ranging from 13-0.

See the image below.

![24h clock](https://materialdoc.com/images/time-picker-1.png)

**Comment by realcarbonneau** [comment]
Can you post your code? Quasar version? 

It works for me with V0.15 and the /form/datetime.vue demo/tests.  See my screenshot below.

![2018-01-26 14_39_35-quasar development](https://user-images.githubusercontent.com/29619229/35457589-74fca23a-02a7-11e8-9c1e-8c909bcbaf2b.png)

**Comment by realcarbonneau** [comment]
Sorry, I miss-understood, and @rstoenescu clarified.  I understand, and yes you are correct, my adroid does as you indicated.

**Comment by zuck** [comment]
From a design point-of-view I find the Android-way even more weird because it's not really consistent: why should they put 00, 13 .. 23  on a visually different circle? Only because clocks usually have only 12h? Hours should have equal importance...

**Comment by realcarbonneau** [comment]
Ageed, maybe it won't last!?

**Comment by Marcel50506** [comment]
From a design point of view, I think the android way tries to approach the clock as having 12 hours per circle. When I think of 13:00, my clock points to the same position as 01:00, so these positions should be similar. In the current timepicker, the 13:00 location is on the other side of the clock.

But besides design: Google/Android is using this 'two-circles' clock since Android L, which was introduced in 2014, about 3.5 years ago. I don't think they will change this pattern. IMHO, Quasar should follow that design, since users are already familiar with this pattern of time-picking.

**Comment by MoacirSchmidt** [comment]
I strongly agree with Marcel50506! Please consider change that weird design. Most of times when you are scheduling something its gonna happen on work days! Of course "night days" are still important, but not so much as "work days"

**Comment by MoacirSchmidt** [comment]
![image](https://user-images.githubusercontent.com/15182027/35688287-fba72da0-0757-11e8-8d20-0568e5fcbacf.png)

**Comment by Marcel50506** [comment]
Is there any update on this issue? Will this be picked up, and if so, in what timeframe?

**Comment by rstoenescu** [comment]
This will get in. v1.0.

**Comment by rstoenescu** [comment]
Will be available in v0.17.12
