### ISSUE TITLE
QVirtualScroll (horizontal) RTL renders a limited amount of item

### ISSUE THREAD

**Issue by JiPaix** [quasarframework/quasar#14882]
### What happened?

QVirtualScroll with `style="direction: rtl;"` or `dir="rtl"` does render a *limited* amount of items. 

The amount of items rendered seems to be consistent but is also variable between context:
I always get 60 items on codepen and 150 within my app.

### What did you expect to happen?

QVirtualScroll to work the same in both rtl and ltr

### Reproduction URL

https://codepen.io/jipaix/pen/yLEbGoM

### How to reproduce?

1. Open codepen link
2. switch between rtl and ltr by clicking the "turn on/off rtl" button
3. scroll lists in both mode and see the difference

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Electron

**Comment by pdanpdan** [comment]
We do not support RTL/LTR changes on a per element base - you need to change LTR/RTL mode for the whole page (using https://v1.quasar.dev/options/rtl-support)

**Comment by rstoenescu** [comment]
The correct link is https://quasar.dev/options/rtl-support (Qv2)
