### ISSUE TITLE
cannot use quasar extension  @quasar/qmarkdown, error occurring while installation.

### ISSUE THREAD

**Issue by AhmedHamdy-B** [quasarframework/quasar#14892]
### What happened?

trying to add the plugin to read .md files and after installing and trying to run the app it shows that the extension is not compatible with quasar v2.7.3 required version is  ^1.5.0

![image](https://user-images.githubusercontent.com/56585994/201641566-1cfb8dfe-250c-496a-9003-86d082427e3b.png)
![image](https://user-images.githubusercontent.com/56585994/201641816-dd082f41-942b-41e4-97be-2483e9424c25.png)

Note: I don't really mind using other extension or loaders, I just want to read my md files in my Quasar app. any help? 

### What did you expect to happen?

extension to be installed normally and import my .md files to my HTML as it should.

### Reproduction URL

[donthave](https://codepen.io/Hawkeye64/pen/ExxzdMp?editors=1010)

### How to reproduce?

1-go to any Quasar app.
2-install the extension from https://www.npmjs.com/package/@quasar/quasar-app-extension-qmarkdown.
3-error occurring.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Plugins (quasar)

**Comment by yusufkandemir** [comment]
![image](https://user-images.githubusercontent.com/6266078/201647439-5878bff0-cbf2-4c58-a211-af7e2b0ef117.png)

https://qmarkdown.netlify.app/all-about-qmarkdown/installation-types#Install

```bash
quasar ext add @quasar/qmarkdown@next
```
`@next` is the important part.

**Comment by AhmedHamdy-B** [comment]
Thanks A lot ♥
