### ISSUE TITLE
QInput prop `bottom-slots` overhided by prop `error` even if it's `false`

### ISSUE THREAD

**Issue by DouglasCalora** [quasarframework/quasar#14897]
### What happened?

QInput prop `bottom-slots` is over hided by prop `error` even if it's `false`, if the value of error is false, it shows the bottom slots like "hint" for example.
Undefined value has the same behavior of "false" in error prop, why  "bottom-slots" has different behavior then?
Is this the correct behavior?

### What did you expect to happen?

A documentation explaining that this happens or change the behavior (if it's wrong).

### Reproduction URL

https://codepen.io/DouglasCalora/pen/MWXozxY

### How to reproduce?

Just open de link

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
https://quasar.dev/vue-components/input#external-validation
> You can also use external validation and only pass `error` and `error-message` (enable `bottom-slots` to display this error message).

Another reproduction that uses the second docs example as the base but without passing `bottom-slots`: https://codepen.io/yusufkandemir/pen/jOKjmrG?editors=101

According to the docs, it should clearly be hidden without `bottom-slots`. So, I would say this is a bug.

**Comment by DouglasCalora** [comment]
Nothing yet?

**Comment by rstoenescu** [comment]
Hi,

Not a bug. This is the condition for rendering the bottom:

```js
const shouldRenderBottom = computed(() =>
    props.bottomSlots === true
    || props.hint !== void 0
    || hasRules.value === true
    || props.counter === true
    || props.error !== null
  )
```

**Comment by rstoenescu** [comment]
One more thing: Boolean props are by default `false`, so it has no effect to explicitly specify them with their default value.
