### ISSUE TITLE
What target platforms will be supported

### ISSUE THREAD

**Issue by zoomclub** [quasarframework/quasar#149]
Just spent a little time tonight looking around at Windows Universal Apps and the tools around the Windows 10 platform. Being that there are multiple targets to deploy to using modern JS I was just wondering if these are being considered by Quasar? What are the capabilities to reach the following targets using Quasar?

• Windows Universal Apps (mobile, xbox, etc)
• Electron (mac, windows, linux desktops)

It would seem Cordova is being leveraged to reach all platforms including iOS and Android. Would using the coming Weex native engine also be an option for mobile specific apps?

Just had to ask and clarify, do not mean to imply that Quasar is not already fantastic. Instead, I think Quasar would be a good place to address these deployment options as well.

**Comment by rstoenescu** [comment]
Hi,

For a browser support statement, take a look at: https://github.com/quasarframework/quasar-framework.org/issues/20

An electron wrapper (mac, windows, linux, ...) is currently being worked on and will be available really soon, so this will also probably also help with UWP (universal windows platform) apps.
Also planning on making an assessment to use Weex native engine once it is out. It will most likely be possible to make a wrapper for it too.

Thanks for posting this question!
