### ISSUE TITLE
[Request] QTable: Group Rows By ColumnKey

### ISSUE THREAD

**Issue by DomenicoCatrambone** [quasarframework/quasar#1491]
There are few table components that have a "GroupBy" prop. Can you add that in the future?
Actually that can be achieved sorting rows and use vanilla js to add a row when needed. (So you must disable manual sorting).

Are there better methods? I need only one level group like:

```
Good
  Superman
  Ironman
  Spiderman
Evil
  Joker
  Thanos
```

**Comment by rstoenescu** [comment]
Hi,

Please check out the QTable in v0.15 (replacing the old data table component). Specifically, look at using scoped slots to achieve what you want. Thank you.
