### ISSUE TITLE
q-table example for editable cells without q-popup-edit buttons misses "enter" processing / way to confirm edit

### ISSUE THREAD

**Issue by RustyJoeM** [quasarframework/quasar#14935]
### Description

Hello,

There seems to be minor bug in example code - https://quasar.dev/vue-components/table#popup-editing 
When first column of the example's table is being edited, enter key does not work, and edited text cannot be "applied".
Exiting popup reverts value to the original one before editing.

I noticed that `QPopupEdit`'s own page has example (https://quasar.dev/vue-components/popup-edit#example--edit-first-columns) that includes  extra `@keyup.enter="scope.set"` on nested `q-input`.
That seems handle enter keypress/applying the edit fine.

I'm not sure whether this is obvious behavior, or some description note and/or `keyup.enter` event should be added to the example's first column in my first linnk above too.

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
It looks like the need to set `@keyup.enter` is documented in the upgrade guide (https://quasar.dev/start/upgrade-guide#qpopupedit)

- the tip in here (https://quasar.dev/vue-components/popup-edit#textarea-qeditor) is no longer needed
- it would need a warning about how to close on enter

The examples in QTable are missing the update on `@keyup.enter`
