### ISSUE TITLE
Quasar Vite plugin can't find Vue plugin if it's nested

### ISSUE THREAD

**Issue by sxzz** [quasarframework/quasar#14932]
### What happened?

https://github.com/quasarframework/quasar/blob/6cc5cd8c0f0e2a3188b59af1cd44435adee164bf/vite-plugin/src/plugin.js#L21

`viteConf.plugins` could be a nested plugin array. For example, it could be: `[foo, bar, [[baz, vuePlugin], qux]]`

### What did you expect to happen?

Check Vue plugin correctly when Vue plugin is put inside of a nested plugin array.

### Reproduction URL

N/A

### How to reproduce?

N/A

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Will be available in `@quasar/vite-plugin` v1.3.0
