### ISSUE TITLE
Hide QTabs horizontal scrollbar

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1493]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: v9.4.0
NPM: 5.6.0
Browsers: Google Chrome for Android mobile(latest version)
iOS:
Android: 6.1
Any other software related to your bug:

### What did you get as the error?
No errors
### What were you expecting?
I expect an option or way to hide the scrollbar but keep it function(so the user still able to scroll the tabs)
### What steps did you take, to get the error?
I tried these CSS rules to hide it but they didn't work:

```
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
  -ms-overflow-style: -ms-autohiding-scrollbar;
```
All the best,
Mohammed

**Comment by rstoenescu** [comment]
Hi, Any screenshot of exactly what bother you pls? Thanks.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu 

Thank you for your reply.

Here is a video https://www.dropbox.com/s/cpti6uy7v9wy7vl/20180126_201037.mp4?dl=0 that shows the scrollbar that I mean in action.

Warm Regards,
Mohammed

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu Here is the website if you want to take a look at the code as well:

https://romionline.com

Just view it on Android mobile with Chrome browser

**Comment by rstoenescu** [comment]
Ah. You mean that. That are the scrollbars that the browsers use when on mobile. There is no way around it if you don't want to lose the native scrolling (which is smooth). Trust me, you want the native scrolling. Sorry.

**Comment by rstoenescu** [comment]
By the way. Nice website/app. Would like to see that on https://github.com/quasarframework/quasar-awesome when it's done.

**Comment by MohammedAl-Mahdawi** [comment]
> Ah. You mean that. That are the scrollbars that the browsers use when on mobile. There is no way around it if you don't want to lose the native scrolling (which is smooth). Trust me, you want the native scrolling. Sorry.

@rstoenescu Aha, thank you for letting me know that, I thought it is related to QTabs.

> By the way. Nice website/app. Would like to see that on https://github.com/quasarframework/quasar-awesome when it's done.

Thank you, sure, it will be my pleasure to do so, I'll let you know when it will be finished.

All the best,
Mohammed
