### ISSUE TITLE
(Since 1.22.1) Cordova Dialogs/QSelect requires double tap to leave dialog

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#14945]
### What happened?

On Cordova apps since v1.22.1, exiting a dialog requires double-tapping on the backdrop, rather than a single tap.
Only on Cordova compiled apps. Works normal on the standard SPA version.
This occurs on all dialog variants (QPopupProxy, QDialog, QSelect, etc)

### What did you expect to happen?

On single tap, the backdrop should trigger the dialog to close

### Reproduction URL

- https://github.com/nicholaszuccarelli/cordova-broken-dialogs

### How to reproduce?

1. Create a QDialog
2. Open the dialog
3. On Cordova, attempt to leave dialog by tapping on the backdrop. Will only work with double taps

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Other

**Comment by nicholaszuccarelli** [comment]
Supplied reproduction URL.
Change the package.json Quasar version to v1.22.0 and it will work as expected

https://github.com/nicholaszuccarelli/cordova-broken-dialogs

**Comment by pdanpdan** [comment]
It looks like another apple optimization
https://stackoverflow.com/questions/45686710/ios-safari-focus-not-triggering-on-tap
https://itnext.io/fixing-focus-for-safari-b5916fef1064

**Comment by nicholaszuccarelli** [comment]
Oddly enough only occurs in Cordova though. Running my app via Safari works as expected

**Comment by rstoenescu** [comment]
Should be ok with Quasar v2.11.0 and v1.22.3.
If I missed something, please comment and I will reopen.
