### ISSUE TITLE
QUploader computedProps not reactive

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#14967]
### What happened?

QUploader's computedProps(`files`, `queuedFiles`, etc.) are not working properly when accessed via template refs.

### What did you expect to happen?

computedProps to be properly reactive.

### Reproduction URL

https://codepen.io/yusufkandemir/pen/KKeoZgy?editors=101

### How to reproduce?

1. Go to the link
2. Click the "Notify files.length" button, and confirm you get `There are 0 files`
3. Confirm it says `Files count: 0` inside the uploader and under the button.
4. Add a new file to the uploader.
5. Confirm it says `Files count: 1` inside the uploader ✅ 
6. Confirm it still says `Files count: 0` under the button ❌
7. Confirm it says still `There are 0 files` when you click the button

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Additional context

Possible cause: https://github.com/quasarframework/quasar/commit/d3765c1bcd174c757c8597f50feeaec468b65da5#diff-10454ab8334f9a1ee3fd3ff5844907913ca6e069f8509927e7d3db1be38e8171

**Comment by Secusaurus** [comment]
Has anybody found a good workaround for this issue, as long as it is not fixed?

In my project, I currently fire the upload regardless of if there is a file or not. Unfortunately, without a file, neither of the following methods get fired, so I just assume "everything will be fine" after some seconds.

**Comment by dZlatanovski** [comment]
@TDArlt I know it's been a while but there hasn't been any workaround posted yet so here's a dirty suggestion of mine (Vue 3 SFC setup script syntax):
```
<template>
  <div>
    <q-uploader 
      url="http://localhost:4444/upload"
      style="max-width: 300px"
      :auto-upload="false"
      @added="(files) => uploaderFiles.push(...files)"
      @removed="(files) => removeFiles(files)"
    />
    <q-btn label="Click me" @click="handleClick"/>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const uploaderFiles = ref([]);

function getFileKey(file) {
  return return file.webkitRelativePath + file.lastModified + file.name + file.size;
}

function removeFiles(files) {
  uploaderFiles.value = uploaderFiles.value.filter(
    (f) => !files.map(f2 => getFileKey(f2)).includes(getFileKey(f1))
  )
}

function handleClick() {
  console.log(uploaderFiles.value);
}
</script>
```

Explanation:
We create our own array where we store the files that the q uploader holds. Every time files are added to the q uploader, we add those files to our array, and every time files are removed, we filter those files out of our array too. The file key thing is what the q uploader actually does in the background to make sure to disallow duplicates (at least from what I saw in the source code).
Hope this helps.

**Comment by gitrojones** [comment]
Finally got around to look into this as we've just been using a workaround on our project. Looks to be because of https://github.com/quasarframework/quasar/blob/636f555d8ca197421819f3e8d3d7b5a8bad0b221/ui/src/components/uploader/uploader-core.js#L462

Object.assign is going to copy the getter value, not the getter itself (hence the broken references). Easy fix is just doing a subsequent re-assign on proxy so the getters are available for both internal state and on the proxy. EG:

```javascript
  // expose public api (methods & computed props)
  Object.assign(proxy, publicApi)

  // Re-assign getters enumerable on proxy object
  for (const key in state) {
    if (isRef(state[ key ]) === true) {
      injectProp(proxy, key, () => state[ key ].value)
    }
  }
```

[Submitted a PR for this](https://github.com/quasarframework/quasar/pull/15898), surprised this hasn't gotten any attention.

**Comment by rstoenescu** [comment]
Fix will be available in next version.
