### ISSUE TITLE
q-btn-dropdown does not update label attribute

### ISSUE THREAD

**Issue by wux5** [quasarframework/quasar#1496]
### Software version

Quasar: 0.15.0-beta.10
OS: OSX Sierra
Browsers: Chrome 63

### What did you get as the error?
The q-btn-dropdown does not update label when it changed. For example:
```js
    <q-btn-dropdown :label="label1">
    </q-btn-dropdown>
    <q-btn @click="label1='111111111'" :label="label1" />
```
When changing label1 value, the q-btn label will be updated, but q-btn-dropdown does not.

**Comment by rstoenescu** [comment]
Hi,

Please check your code. It is working. https://jsfiddle.net/rstoenescu/na2gf2q8/

**Comment by wux5** [comment]
Thanks for looking into it. So the issue happens when the initial label is empty. See the updated jsfiddle with initial label value='': https://jsfiddle.net/kjLak28c/

**Comment by realcarbonneau** [comment]
I have reproduced the problem, something strange with reactivity.  Button label div being added reactively for regular button, but not for the dropdown. In debug, reactivity works and the div should be added, but doesn't end up in the virtual DOM... strange, still looking...

**Comment by rstoenescu** [comment]
Thanks for reporting. Will be available in beta.11.

**Comment by realcarbonneau** [comment]
Damn, faster than me, I was almost at a fix! :P

**Comment by rstoenescu** [comment]
I appreciate looking into it though. Thought you were away so fixed it.
