### ISSUE TITLE
mdi-v6 and -v7 icons missing (or misleading documentation)

### ISSUE THREAD

**Issue by zegkljan** [quasarframework/quasar#14964]
### What happened?

The documentation for `q-icon` regarding MDI SVG icons says 

> Go to [MDI](https://materialdesignicons.com/), look for your desired icon, click on it. A dialog box will appear. Get the title (eg. “account-key”), prefix it with “mdi-” and you get the result (eg. “mdi-account-key”).

for [webfont icons](https://quasar.dev/vue-components/icon#mdi-material-design-icons-), and

> Go to MDI, look for your desired icon, click on it. A dialog box will appear. Get the title (eg. “account-key”), prefix it with “mdi” and camel-case the result (eg. “mdiAccountKey”).

for [SVG icons](https://quasar.dev/vue-components/icon#svg-mdi-material-design-icons-).

I wanted to use the `cloud-arrow-right` icon, which [does exist on materialdesignicons.com](https://materialdesignicons.com/icon/cloud-arrow-right), but using `mdi-cloud-arrow-right` produces no icon, and `mdiCloudArrowRight` is simply not present in `@quasar/extras/mdi-v6` (and neither in `-v7`).

### What did you expect to happen?

The icon should be available (as a webfont and as SVG in `@quasar/extras/mdi-v6` and/or in `-v7`), OR the documentation should be clear about some icons not being available (and, ideally, why are they not available).

### Reproduction URL

https://stackblitz.com/edit/quasarframework-ognnpd?file=src/App.vue

### How to reproduce?

See the reproduction link - following the instructions in `q-icon` documentation does not produce the sought icon.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar Extras (@quasar/extras)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(6.0.8-arch1-1) - linux/x64
NodeJs - 18.12.1

Global packages
  NPM - 8.19.2
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.10.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.25 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.28.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qoverlay - 2.0.1 -- A Quasar App Extension

Networking
  Host - vetrnik
  enp2s0 - 192.168.2.95
  br-78fcc9278498 - 172.22.0.1
  tailscale0 - 100.120.98.30
```

**Comment by yusufkandemir** [comment]
It's a 3-day-old icon and the latest MDI release(v7.0.96) is 4 months ago, so it's not been released yet:
https://github.com/Templarian/MaterialDesign/commits/master/svg/cloud-arrow-right.svg
https://www.npmjs.com/package/@mdi/svg?activeTab=versions
So, even if you are using `@mdi/js` or `@mdi/svg`, you wouldn't access that icon. It's a problem with MDI's website not being bound to a certain version. `@quasar/extras` will be updated with those icons after MDI makes a release.

If you want to see the actual list of icons that are actually released and is available in Quasar, you can use https://iconexplorer.app/icons/mdi-v7?selected
We should probably reference this from our docs instead.

**Comment by zegkljan** [comment]
Oh, I didn't realise that! As you say, I think the documentation should point to the icon explorer instead of the MDI site.
