### ISSUE TITLE
[Request] @clear event for QSearch (icw QAutocomplete)

### ISSUE THREAD

**Issue by frankbrussel** [quasarframework/quasar#1497]
The current QSearch has a clear button, which clears the input field. 

It would be great if it would also be possible to specify additional actions to be taken when the clear button is used, through an @clear event. 

For instance: when the search is used to fill in other fields, these can be cleared when the clear button is selected. In my case: the search field is used to select an address from known addresses. The selected address is then filled in in multiple other input fields: a street, zipcode etc. Using the clear button right now only clears the search field, however it is not easy to specify that those other fields also need to be cleared.

**Comment by rstoenescu** [comment]
This is already in v0.15, so closing.
