### ISSUE TITLE
Big bug for QTabPanels(Component not call onUnmounted with when use keep-alive prop when panel removed)

### ISSUE THREAD

**Issue by lanzze** [quasarframework/quasar#14979]
### What happened?

I use keey-alive prop on QTabPanels, but when some panel component  removed, the component not trigger onUnmounted call.

You should know that: The component was removed from QTabPanels!!!

I saw the QTabPanels only render one component at anytime. W
hy cannot give a prop to control it?  render one(lazy) or render all.

### What did you expect to happen?

When component remove from QTabPanels, the component will be destroy! Then onUnmounted hook will call!

### Reproduction URL

https://codepen.io/lanzze/pen/RwJJbaG

### How to reproduce?

1. Add keep-alive prop on QTabPanels.
2. Add any component to QTabPanels.
3. Remove some component from QTabPanels.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platform
Quasar version: ^2.10
Vue version: ^3.2

**Comment by pdanpdan** [comment]
We'll reopen if you provide a reproduction.

But if you mean what I believe you mean (that you remove a tab panel that is not active) then this is related to how keep alive works in vue (not-active components in keep alive are inactive :) ) and you can solve it by dynamically set the `keep-alive-exclude` prop of QTabPanels to include the key of the removed panel.

**Comment by lanzze** [comment]
Thanks [pdanpdan](https://github.com/pdanpdan) reply.

I know that prop(keep-alive-include). But one thing you should know, The kee-aplive-include need component's name!! I can't get the name  beccause the component was dynamic import(A function like ()=>import(path) ) and  wrapped in defineAsyncComponent.

I use QTabPanels bind a component array, I change the array dynamic out site. Where I get the component's name?

If keep-alive-include use the component's key, that resolve the problem.

**Comment by pdanpdan** [comment]
You need to set `keep-alive-exclude` on QTabPanels (or `exclude` on a KeepAlive in Vue3)

https://codepen.io/pdanpdan/pen/bGKOPZW?editors=0010

But it still has nothing special to to with Quasar - we just forward the `KeepAliveInclude` to `include` and `KeepAliveExclude` to `exclude`

Hmm, in fact it looks like in Quasar there is a side-effect that you can use empty `KeepAliveInclude` or `KeepAliveExclude` to force using keyed wrapper for panels and that has the side effect of destroying the panels when they are removed from the array

I updated the codepen with different types of rendering
