### ISSUE TITLE
can i use quasar with browserify?

### ISSUE THREAD

**Issue by sombriks** [quasarframework/quasar#150]
i understand that quasar-cli gives me a quite healthy webpack setup, however i would like to know it it will work on existing browserify project

**Comment by mariaczi** [comment]
I don't see any reason why it would not work.
In deep, it is just npm-package so should work perfectly fine with Browsify, but let @rstoenescu give us his thoughts.

**Comment by rstoenescu** [comment]
Hi,

Yes, as @mariaczi indicated, this is totally possible.

1. NPM install 'quasar-framework'
2. Import Quasar and tell Vue to use it in your browserify configuration:

  ``` js
 import Quasar from 'quasar-framework'
 Vue.use(Quasar)
 ````

3. Import Quasar's CSS too, which will be located in `node_modules/quasar-framework/dist/quasar.mat.css` or `node_modules/quasar-framework/dist/quasar.ios.css` (depending on your theme.
