### ISSUE TITLE
QModal auto-hide with route change, modal state becomes out of sync with the v-model/value prop

### ISSUE THREAD

**Issue by realcarbonneau** [quasarframework/quasar#1502]
The QModal control has an auto-hide when the route changes, regardless if a v-model/value prop has be provided.  This results in the modal display becoming out of sync with the v-model/value prop.

I was testing a login modal and this is a problem because on the initial load and route changes, the modal closed even if the v-model/value prop was still in a state that requires the modal to be open.  I will submit a PR.

```
  watch: {
    $route () {
      this.hide()
    }
  },
```

**Comment by rstoenescu** [comment]
Calling "hide()" makes the Modal emit an event so that v-model directive captures it and updates the model. It can't become out of sync.

**Comment by realcarbonneau** [comment]
Agreed, but the component modal component should not be imposing a state change on the v-model/value during a route change.  The component already has options noBackdropDismiss and noEscDismiss, which permit the designer to ensure that no model changes are imposed by the component.

I my given authentication scenario, the QModal should not impose a change to the value authenticated value simply because of a route change.

My PR will deactivate the auto-hide on route change when a v-model is provided.  Anothe alternative would be to have an option like noRouteChangeDismiss.
