### ISSUE TITLE
v-ripper lost  on grid layout

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#15035]
### What happened?

I created 9 blocks on display:grid,but the ripper shows abnormal.

### What did you expect to happen?

CSS display:grid and v-ripper compatible.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-rwelqr?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

```
<q-card>
    <div style="
        display: grid;
        grid-template-columns: repeat(3, 100px);
        grid-template-rows: repeat(3, 100px);
        gap: 10px;
">
        <div v-ripple v-for="i in 9" style="background-color:pink;">
            {{ i }}
        </div>
    </div>
</q-card>
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Directives (quasar)

**Comment by pdanpdan** [comment]
The container should be non-static positioned
