### ISSUE TITLE
QDataTable mobile problem after dev

### ISSUE THREAD

**Issue by artem0071** [quasarframework/quasar#1504]
When I make table in developing mode and "quasar dev ios" on chrome in mobile mode there is no problem:
![2018-01-27 15 09 09](https://user-images.githubusercontent.com/21971875/35471886-4dfbf1d0-0375-11e8-8f2a-33e69ad472de.png)

But when I do "quasar build ios" there is no "ios"/"mobile" theme
![2018-01-27 15 22 56](https://user-images.githubusercontent.com/21971875/35471910-fc58f0ca-0375-11e8-9869-4ba31db4744d.png)

v0.14.7

**Comment by rstoenescu** [comment]
Hi,

There are two options for v0.14: 1. Disable purify CSS from /config/index.js. 2. Look for similar tickets on Data table where people have offered a tweak on purifyCSS configuration.

Please note that the Data table has been revamped in v0.15 anyway.
