### ISSUE TITLE
QScrollArea scrollbar is decorative in RTL

### ISSUE THREAD

**Issue by JiPaix** [quasarframework/quasar#15050]
### What happened?

If QScrollArea direction is set to rtl the scrollbar doesn't move, but the content does.

### What did you expect to happen?

The scrollbar should be moving along with the content in rtl

### Reproduction URL

https://codepen.io/jipaix/pen/yLEbGoM

### How to reproduce?

1. Open codepen
2. Click "turn on rtl" button
3. scroll the QScrollArea

### Flavour

UMD

### Areas

Components (quasar), Style & Identity (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge, Electron

**Comment by pdanpdan** [comment]
A few problems with your codepen:
1. Quasar needs to be told the direction of the page using `$q.lang.set` - it does not obey local(element) `dir="..."`
2. You need to load only the `.rtl` CSS file (not both non-rtl and rtl (and in codepen you need to load it in CSS section, not JS section)

Except for this all works as expected

https://codepen.io/pdanpdan/pen/LYrXZXp?editors=1010
