### ISSUE TITLE
Design issue on q-input

### ISSUE THREAD

**Issue by akash-melkeri** [quasarframework/quasar#15052]
### What happened?

Q-input background overflows.
A `q-input` with `rounded` and `outlined`.
If I use _background_ color on it. it overflows even outside of borders.

### What did you expect to happen?

background should not overflow.
If I use _background_ color on it. it should not overflow outside of outline.

### Reproduction URL

https://jsfiddle.net/f5nht6wr/2/

### How to reproduce?

1.Go to reproduction link
2. Look at q-input.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), Style & Identity (quasar)

### Platforms/Browsers

Safari

**Comment by pdanpdan** [comment]
This is expected - the QInput has an inside (the bordered one) and an outside part (before and after slots)
The class applies to all, so in that case you need to target the internal part (`.q-field > .q-field__inner > .q-field__control` in inspector)

https://jsfiddle.net/7xh45jun/
