### ISSUE TITLE
Bug? quasar upgrade -i still keep going Yarn not PNPM (default)

### ISSUE THREAD

**Issue by gowy222** [quasarframework/quasar#15055]
### What happened?

`PS D:\mycode\quasar\vue> quasar upgrade -i

    Quasar CLI · Gathering information with yarn...

 @quasar/extras: 1.15.6 → 1.15.7

  Quasar CLI · Running "yarn add @quasar/extras@^1.15.7"

yarn add v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning vue > @vue/compiler-sfc > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning @quasar/app-webpack > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning unplugin-auto-import > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[3/5] Fetching packages...
[4/5] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile ....`

### What did you expect to happen?

env: npm,yarn,pnpm all installed in my system for diff old project

and new project:
pnpm create quasar  => set pnpm by default

quasar upgrade -i should use pnpm not yarn
this will mess up package stores

### Reproduction URL

nop

### How to reproduce?

pnpm create quasar  
=> set pnpm by default
=> quasar upgrade -i

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Quasar CLI · Gathering information with yarn...

 @quasar/extras: 1.15.6 → 1.15.7

  Quasar CLI · Running "yarn add @quasar/extras@^1.15.7"

yarn add v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning vue > @vue/compiler-sfc > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning @quasar/app-webpack > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning unplugin-auto-import > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[3/5] Fetching packages...
[4/5] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile
```

**Comment by gowy222** [comment]
if i 
`pnpm add @quasar/extras@^1.15.7`

then i lost
Error: Cannot find module 'webpack'


` Dev mode.................. spa
 Pkg quasar................ v2.10.2
 Pkg @quasar/app-webpack... v3.6.1
 Pkg webpack............... v5
 Debugging................. enabled

 Configured browser support (>= 89.18% of global marketshare):
 · Chrome for Android >= 107
 · Firefox for Android >= 106
 · Android >= 107
 · Chrome >= 99
 · Edge >= 104
 · Firefox >= 98
 · iOS >= 13.4-13.7
 · Opera >= 88
 · Safari >= 15.1

[  Error: Cannot find module 'webpack'
  Require stack:
  - D:\mycode\quasar_oms\oms\quasar.config.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.6.1_ggkzqseu57njbmlcsujprzzlla\node_modules\@quasar\app-webpack\lib\quasar-conf-file.js 
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.6.1_ggkzqseu57njbmlcsujprzzlla\node_modules\@quasar\app-webpack\lib\cmd\dev.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.6.1_ggkzqseu57njbmlcsujprzzlla\node_modules\@quasar\app-webpack\bin\quasar
  - D:\nodejs\cache_folder\node_global\node_modules\@quasar\cli\bin\quasar

  - loader:933 Function.Module._resolveFilename
    node:internal/modules/cjs/loader:933:15

  - loader:778 Function.Module._load
    node:internal/modules/cjs/loader:778:27

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

    node:internal/modules/cjs/loader:1155:10

  - loader:981 Module.load
    node:internal/modules/cjs/loader:981:32

  - loader:822 Function.Module._load
    node:internal/modules/cjs/loader:822:12

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\mycode\\quasar_oms\\oms\\quasar.config.js',
    'D:\\mycode\\quasar_oms\\oms\\node_modules\\.pnpm\\@quasar+app-webpack@3.6.1_ggkzqseu57njbmlcsujprzzlla\\node_modules\\@quasar\\app-webpack\\lib\\quasar-conf-file.js',
    'D:\\mycode\\quasar_oms\\oms\\node_modules\\.pnpm\\@quasar+app-webpack@3.6.1_ggkzqseu57njbmlcsujprzzlla\\node_modules\\@quasar\\app-webpack\\lib\\cmd\\dev.js',
    'D:\\mycode\\quasar_oms\\oms\\node_modules\\.pnpm\\@quasar+app-webpack@3.6.1_ggkzqseu57njbmlcsujprzzlla\\node_modules\\@quasar\\app-webpack\\bin\\quasar',    'D:\\nodejs\\cache_folder\\node_global\\node_modules\\@quasar\\cli\\bin\\quasar'
  ]
}`

**Comment by gowy222** [comment]
`
PS D:\mycode\quasar_oms\oms> pnpm store prune
Removed all cached metadata files
Removed 5371 files
Removed 20 packages
PS D:\mycode\quasar_oms\oms> pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date
 WARN  Failed to create bin at D:\mycode\quasar_oms\oms\node_modules\.bin\autoprefixer. The source file at D:\mycode\quasar_oms\oms\node_modules\autoprefixer\bin\autoprefixer does not exist.
 WARN  Failed to create bin at D:\mycode\quasar_oms\oms\node_modules\.bin\cssesc. The source file at D:\mycode\quasar_oms\oms\node_modules\cssesc\bin\cssesc does not exist.
 WARN  Failed to create bin at D:\mycode\quasar_oms\oms\node_modules\.bin\acorn. The source file at D:\mycode\quasar_oms\oms\node_modules\acorn\bin\acorn does not exist.
 WARN  Failed to create bin at D:\mycode\quasar_oms\oms\node_modules\.bin\he. The source file at D:\mycode\quasar_oms\oms\node_modules\he\bin\he does not exist.
 WARN  Failed to create bin at D:\mycode\quasar_oms\oms\node_modules\.bin\ejs. The source file at D:\mycode\quasar_oms\oms\node_modules\ejs\bin\cli.js does not exist.
 WARN  8 other warnings
Done in 699ms

`

**Comment by rstoenescu** [comment]
Will be available in the global installation of Quasar CLI (v1.4.0)
