### ISSUE TITLE
Error in App extension

### ISSUE THREAD

**Issue by ErhardScampi** [quasarframework/quasar#15053]
### What happened?

created with yarn create quasar an app-extension.

in the app-extension I created a normal quasar project for testing purpose.

I added the app extension to the test quasar project via 
yarn add --dev link:////Users/sc/dev/my-login-component

I registered it with 
and boom (same behavior with vite and webpack)

daphne testapp$ quasar ext invoke my-login-component
 App • Invoking "my-login-component" Quasar App Extension

 App • Updating /quasar.extensions.json for "my-login-component" extension ...
 App • Running App Extension install script...
/Users/sc/dev/my-login-component/testapp/node_modules/@quasar/app-webpack/lib/app-extension/Extension.js:338
    await script(api)
          ^

[  TypeError: script is not a function

  - Extension.js:338 Extension.__runInstallScript
    [testapp]/[@quasar]/app-webpack/lib/app-extension/Extension.js:338:11

It has nothing to do with the install.js (I tested it with an old one from another extension of mine) and with the empty one.

Any ideas ?

### What did you expect to happen?

Registering app extension should work

### Reproduction URL

https://github.com/ErhardScampi/my-login-component

Sorry how should I send You my command line......

### How to reproduce?

The description

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

App Extension API

### Quasar info output

```Shell
See description
```

**Comment by ErhardScampi** [comment]
Sry but can't fiddle a command line issue.... Or do not know how.

**Comment by yusufkandemir** [comment]
You have a completely empty `src/install.js` file. You should at least have  the default export, e.g.:
```js
module.exports = function (api) {
  //
}
```
