### ISSUE TITLE
BUG?  CLI build => Extract CSS from Vue files get 0 size file

### ISSUE THREAD

**Issue by gowy222** [quasarframework/quasar#15051]
### What happened?

![_20221203172855](https://user-images.githubusercontent.com/52201479/205434157-1f18767d-cabb-47bc-a192-a9488158f297.png)

```
<style scoped>
/* :deep(.test) {
  border-color: rgb(16, 17, 18) !important;
}
 */
</style>
```
if the vue file  style scoped = empty, but has < style scoped> tag, 
quasar build result will get a 0 size .css file
and gzip even more big?

### What did you expect to happen?

ignore 0 size file! 
ignore 0 szie file to gzip!

### Reproduction URL

nop

### How to reproduce?

see the pic above

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by gowy222** [comment]
```
  "dependencies": {
    "@quasar/extras": "^1.15.6",
    "@vueuse/core": "^9.6.0",
    "axios": "^1.2.0",
    "core-js": "^3.26.1",
    "echarts": "^5.4.0",
    "pinia": "^2.0.27",
    "quasar": "^2.10.2",
    "vue": "^3.2.45",
    "vue-echarts": "^6.2.3",
    "vue-router": "^4.1.6",
  },
  "devDependencies": {
    "@quasar/app-webpack": "^3.6.1",
    "babel-plugin-import": "^1.13.5",
    "uglify-js": "^3.17.4",
    "unplugin-auto-import": "^0.12.0",
    "unplugin-vue-components": "^0.22.11"
  },
```

**Comment by MilosPaunovic** [comment]
It's just a rounded value to two digits, seems like everything works alright.

**Comment by gowy222** [comment]
@MilosPaunovic 
but the .css output file in dist is real empty with nothing init.. 
whats the point to create a 0 size file as output, I guess this shouda ignore during building, or this will waste a browser http request to try get file from remote sever?

**Comment by rstoenescu** [comment]
This has nothing to do with Quasar but with Webpack. You should open a ticket for Webpack team.
