### ISSUE TITLE
[Proposal] q-btn left/right-most sided icons while text is still centered

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1509]
I'd like to set icons to the very begining/end of the button, while text is still center aligned.

Example: 
![https://i.imgur.com/yWnMJoB.png](https://i.imgur.com/yWnMJoB.png)

```html
<q-btn icon="person" left-most-icon>Some centered text</q-btn>
<q-btn icon-right="person" right-most-icon>Some centered text</q-btn>
```
I wish we could do something with modifiers here `icon-right.most="person"`, but its not a directive and even if we make one, I think that's kinda overkill for a simple feature.

**EDIT:**
I can't decide whether `left-most-icon` or `icon-side="left"` looks better here, I'm voting for the former one.

As always, <s>I can prepare a PR</s> (couldn't wait, it took 5 mins anyway) :laughing: 
Feel free to discuss the idea and naming conventions before merging it (if accepted).

**Comment by BenoitRanque** [comment]
Does `align="between"` not work?

**Comment by Frondor** [comment]
@BenoitRanque Nope, try it yourself https://codepen.io/rstoenescu/pen/KQRZJg

**Comment by BenoitRanque** [comment]
You're right, seems other element interfere

**Comment by pdanpdan** [comment]
You can do it like this:

```html
<q-btn class="full-width" align="between">
  <q-icon name="wifi" />
  <div class="col">Text</div>
  <q-icon name="wifi" />
</q-btn>
```
