### ISSUE TITLE
The form is being submit when I click on set date of datetime

### ISSUE THREAD

**Issue by tiaguinhor** [quasarframework/quasar#151]
When I click on "set date" of the datetime component, the form is being submit. The version of the quasar framework is "0.8.2".

**Comment by rstoenescu** [comment]
Will take a look later this evening. You shouldn't wrap with `<form>` in the first place though.

**Comment by tiaguinhor** [comment]
Oh yes, if I do not engage in one form, it works normally. In any case, thanks for the feedback my friend.

**Comment by rstoenescu** [comment]
The `<button>` is interpreted as a form submitter. But we're using Vue, we don't need `<form>`s.
