### ISSUE TITLE
Improve QInput.nativeEl and QFile.nativeEl types by narrowing

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#15128]
### Discussed in https://github.com/quasarframework/quasar/discussions/15121

<div type='discussions-op-text'>

<sup>Originally posted by **mv-go** December 16, 2022</sup>
According to [docs](https://quasar.dev/vue-components/input#qinput-api) the type of `nativeEl` and the return type of `getNativeElement` is
```The native input/textarea DOM Element```

However, the typings that shipped with the library suggest that the type here is a very general `Element`.

Could it be possible to narrow it down to `HTMLInputElement | HTMLTextAreaElement`? Or are there some edge cases that I'm missing?</div>

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.0
