### ISSUE TITLE
[Help] QTable v 0.15

### ISSUE THREAD

**Issue by DomenicoCatrambone** [quasarframework/quasar#1512]
I cannot see how to replicate this: https://datatables.net/examples/advanced_init/row_grouping.html with the new datatable component. (https://github.com/quasarframework/quasar/issues/1491)

**Comment by rstoenescu** [comment]
Ah, ok. Now I understand. Unfortunately that kind of row grouping is not yet supported. Will consider it for next Quasar versions, but it's definitely no small feat.

**Comment by jonasalbert** [comment]
Would love to see this feature. Especially if you could collapse or expand the groupings.
