### ISSUE TITLE
CSS not include in SSR render page

### ISSUE THREAD

**Issue by JeRabix** [quasarframework/quasar#15153]
### What happened?

I create new quasar project:

SSR mode - page not include css (link or inline styles)
and styles fetch only in front part

it's bug only with app-vite
with app-webpack - app.css add to <head> tag in SSR mode

### What did you expect to happen?

SSR render page include <style> tag or <link> tag with my styles from app.(scss/sass) or component styles tags.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-he7hqv?file=src/css/app.scss

### How to reproduce?

√ What would you like to build? » App with Quasar CLI, let's go!
√ Project folder: ... test2
√ Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
√ Pick script type: » Typescript
√ Pick Quasar App CLI variant: » Quasar App CLI with Vite
√ Package name: ... test2
√ Project product name: (must start with letter if building mobile apps) ... Quasar App
√ Project description: ... A Quasar Project
√ Author: ... Evgeniy Yurchenko <rabix346@yandex.ru>
√ Pick a Vue component style: » Composition API with <script setup>
√ Pick your CSS preprocessor: » Sass with SCSS syntax
√ Check the features needed for your project: » ESLint
√ Pick an ESLint preset: » Standard

- install dependencies
- add styles to app.scss or to component style tag
- start project in SSR mode
- press "control" + "U" (in Chrome) to view SSR render page

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SSR Mode

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Are you referring to the production build or dev? Because on dev this is normal to happen. Not in production though.

**Comment by JeRabix** [comment]
> Are you referring to the production build or dev? Because on dev this is normal to happen. Not in production though.

After build i have same

**Comment by JeRabix** [comment]
Ok, after build - all OK.
@rstoenescu

**Comment by rstoenescu** [comment]
Would have been really surprised this not to work on prod. The docs website is SSR with PWA takeover after all so the issue would have been picked up immediately.

Glad everything is ok.

**Comment by pylvr** [comment]
@rstoenescu i have the same problem in the prod build too 
inline css works fine but css in the <style scoped > does not show in the page inspector, images does not show up also 
see picture  

![githibcrr](https://user-images.githubusercontent.com/30418883/209484708-d2bd28b3-66e0-45a2-a530-abe2ff94111b.png)

**Comment by pylvr** [comment]
plus @rstoenescu  can you take a look at this thread please when you got 2 minutes : 
https://stackoverflow.com/questions/74913637/vue3-ssr-does-not-return-plain-html

**Comment by pylvr** [comment]
> Ok, after build - all OK. @rstoenescu

How did you solve the problem ?

**Comment by JeRabix** [comment]
> > Ok, after build - all OK. @rstoenescu
> 
> How did you solve the problem ?

I no solve dev problem) after build all ok - it's ok for me)

**Comment by Evertvdw** [comment]
It would be nice to have this, but there is already a thread on this: https://github.com/quasarframework/quasar/issues/12803
