### ISSUE TITLE
Data-table width of columns dont work at Android

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1516]
### Software version

Quasar: 0.14.7
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: Google 63.0 & Firefox 58.0
iOS: not tested
Android: 5.1.1
Any other software related to your bug: none

### What did you get as the error? 
not a error

### What were you expecting? 
width of columns 

### What steps did you take, to get the error?
width column value show correct 

Only in Android (Chrome and Firefox is ok) any column width value is being ignored. It is distributing the columns of the same width. I increase / decrease the column width value with no effect on Android. Any suggestion?

Below in Chrome, OK.
![screen_001_web](https://user-images.githubusercontent.com/3832694/35592246-8cd25284-05f3-11e8-8f70-e00764e92fb8.jpg)

Below in Android (not correct), i need more width at second column.
I try values 50px, 100px, 200px and now 400px and the visual as the same.
![screenshot_002_android](https://user-images.githubusercontent.com/3832694/35592247-8d055e68-05f3-11e8-9ec9-b082b33b0aec.png)

Source below:

            <q-data-table :data="selTabGrupoItem>-1&&selTabSubgrupoItem>-1?$store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it:[]" :config="cfgGrupo" :columns="colGrupo" style="margin:-10px;">
              <template slot="col-foto" slot-scope="cell">
                <img v-show="$store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it[cell.row.__index].fotos.length>0" :src="$store.state.urlImages+$store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it[cell.row.__index].fotos[0]" style="margin:-8px;width:30px;height:30px;"/>
              </template>
              <template slot="col-nm" slot-scope="cell">
                <span>{{$store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it[cell.row.__index].nm}}<br/>{{$store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it[cell.row.__index].de}}</span>
              </template>
              <template slot="col-vl" slot-scope="cell">
                <span>{{formatVal($store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it[cell.row.__index].vl)}}</span>
              </template>
              <template slot="col-qt" slot-scope="cell">
                <span>{{$store.state.treeM[selTabGrupoItem].sg[selTabSubgrupoItem].it[cell.row.__index].qt}}</span>
              </template>
            </q-data-table>

...
      cfgGrupo: {
        leftStickyColumns: 0,
        rowHeight: '40px',
        title: '',
        noHeader: true,
        refresh: false,
        columnPicker: false,
        bodyStyle: {
          maxHeight: '65vh'
        },
        responsive: true,
        // rightStickyColumns: 1,
        // selection: 'single',
        messages: {
          noData: 'Sem itens cadastrados',
          noDataAfterFiltering: '<i>Atenção</i> Itens não encontrados.'
        }
      },
      colGrupo: [{
        label: 'foto',
        field: 'foto',
        width: '10px',
        type: 'string'
      },
      {
        label: 'Descrição',
        field: 'nm',
        width: '400px',
        type: 'string'
      },
      {
        label: 'Valor',
        field: 'vl',
        width: '40px',
        type: 'string'
      },
      {
        label: 'Qtd',
        field: 'qt',
        width: '40px',
        type: 'string'
      }]

**Comment by rstoenescu** [comment]
Hi, This is obsolete now. Please upgrade to v0.15 -- QTable is a total revamp of QDataTable.
