### ISSUE TITLE
Significant tap delay from q-route-tab component in Android

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1517]
Issue related to #1269 

### Software version

Quasar: 0.14.7
Browsers: Chrome (with devtools' android emulator), Android, Webview
Android: 5.1 (_didn't test in iOS_)

Demo **https://youtu.be/iHTzxNyQw60**

On chrome dev tools android emulator (device toolbar) and chrome browser (android app), there's some delay after tapping a **router-link tab**.

Looks like the underlying implementation of `router-link` component has some performance issue.

If I have to give my $ 0.50, I'd blame `$nextTick` here https://github.com/quasarframework/quasar/blob/7337478eb74d573554b5f4611279aa483c041d08/src/components/tab/QRouteTab.js#L9

Isn't it possible to get rid of all that router link mixin / implementation and simply work with programmatic navigation? Thus working with `this.$router.replace` (and getting rid of that watcher) in computed properties for the element state / classes?

Code
```html
    <q-tabs slot="footer"
      position="bottom"
      :color="appColor"
      align="justify"
      :two-lines="false"
      class="non-selectable">
      <q-route-tab replace to="/route/tab1"
        icon="devices_other"
        slot="title" />
      <q-route-tab replace to="/route/tab2"
        icon="store"
        slot="title" />
      <q-route-tab replace to="/route/tab3"
        icon="room_service"
        slot="title" />
      <q-route-tab replace to="/route/tab4"
        icon="local_activity"
        slot="title" />
    </q-tabs>
```

Although in this example looks like it works fine https://codesandbox.io/s/381l9rz8wm so I don't really know atm

Tried some recommendations from this article https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away hoping that the 300ms rule were the one to blame here but no, no success.

I strongly believe the problem is within `q-route-tab` component, because normal `q-tab` are working just fine.

**Comment by rstoenescu** [comment]
@Frondor Can you reproduce this with v0.15 too?

**Comment by Frondor** [comment]
I've been a bit busy this week. I'll try a new installation of v0.15 tomorrow and see if the issue reproduces!

**Comment by Frondor** [comment]
Closing this as I can't reproduce it outside of my project. disregarding quasar's version.

**Comment by Frondor** [comment]
Closing this as I can't reproduce it outside of my project. disregarding quasar's version.

**Comment by rstoenescu** [comment]
Let me know if I can help in any way, but after v0.15 release.
