### ISSUE TITLE
Capacitor/Cordova: www folder not cleaned up before build

### ISSUE THREAD

**Issue by yxyx-github** [quasarframework/quasar#15186]
### Description

When upgrading Capacitor as described in the documentation (see the link below), you should also delete the ```www``` folder, otherwise the bundle files will be created twice (or even more), which will make the final APK file unnecessarily large.
The more often you perform the upgrade steps, the more duplicates will result.
So I would suggest to add the ```www``` folder to the folders to delete in the first step of the Upgrade guide in the documentation.
I don't know if this only occurs with Vite because I did not test it with Webpack.

Thanks for all your work for such a great framework! I wish you a happy new year!

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/developing-capacitor-apps/capacitor-version-support#upgrading-capacitor

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Capacitor Mode

**Comment by rstoenescu** [comment]
Hi,

This is not a documentation bug. But an actual bug in both q/app-vite and q/app-webpack.
Fixing...

**Comment by rstoenescu** [comment]
Fix will be available in q/app-vite v1.1.4 and q/app-webpack v3.7.0
