### ISSUE TITLE
QRadio Native form submit : Re-selection of last radio is absent on Chromium

### ISSUE THREAD

**Issue by RemiBrb** [quasarframework/quasar#15182]
### What happened?

When a q-form has multiple q-radio in it with the same **name**, re-selecting the last q-radio button and submitting the form results in the value being omited from **submitResult**. **It seems to be related to Chromium browser, it works perfectly fine on Firefox**.

### What did you expect to happen?

I expect the value to be present in the submitResult.

### Reproduction URL

https://codepen.io/RemiBrb/pen/mdjVaqy

### How to reproduce?

On Chrome or Edge, open https://quasar.dev/vue-components/radio#native-form-submit : 
1. Click on radio button Polygon
2. Click on any ohter radio button, Ellipse for example
3. Click on radio button Polygon
4. Click on submit button

(Working scenario : Click on radio button Polygon then Click on submit button).

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.3
