### ISSUE TITLE
Notification plugin generates infinite loops on certain re-renders

### ISSUE THREAD

**Issue by cohlar** [quasarframework/quasar#15184]
### What happened?

The `Notify` plugin generates infinite loops on certain re-renders, e.g. in computed or template methods.
When replacing `$q.notify` with `console.log`, everything works perfectly.

### What did you expect to happen?

Notifications should be triggered only once.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-r1ksrv?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go on the reproduction link.
2. Click on "Clear Radius".
3. Check the console and the number on top of the notifications.

I made a [second, different reproduction example](https://stackblitz.com/edit/quasarframework-p6ha7c?file=src/pages/IndexPage.vue) that also triggers an infinite loop - hopefully this will help understand the underlying issue. Steps in the second reproduction example:
1. Go on the reproduction link
2. Increase the "Area" fields from `0` to `1` before the opening notification disappears.
3. Check the console and the number on top of the notifications.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.12.1

Global packages
  NPM - 9.1.1
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed     
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.    
  vue-router - 4.1.6
  pinia - 2.0.28 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.30.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed        
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed       
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - LAPTOP-GALIM
  Wi-Fi - 192.168.100.12
  vEthernet (WSL) - 172.22.112.1
```

**Comment by cohlar** [comment]
For now, a workaround that seems to work is to use `watchEffect` instead of `computed` or template methods.

For the first reproduction URL, this would fix the issue - thanks @metalsadman  for this workaround:
``` 
watchEffect(() => {
   if (radius.value === '') {
      const message = 'Please provide a radius to calculate the circle area';
      $q.notify({ type: 'error', message });
   }
})
```

For the second reproduction URL, here is another [proposed fix](https://github.com/cohlar/quasar-notify-loop/pull/1/files).

**Comment by rstoenescu** [comment]
It's generally a bad idea to directly involve a reactive object's methods (like `$q` has with `notify`) inside of a computed function.

Better to run this "outside" or "immediately after" computed call to avoid the side effects.

```
setTimeout(() => {
  $q.notify(...);
});
```

**Comment by cohlar** [comment]
Thanks for the quick reply!
