### ISSUE TITLE
q-select bug in the mobile version when using use-input 

### ISSUE THREAD

**Issue by Teo-Reat** [quasarframework/quasar#15192]
### What happened?

The options menu in q-select breaks down if such factors coincide:
- mobile version
- q-select has the use-input property
- q-select opens in a modal window
- the number of options is large enough for the list to have a scroll

### What did you expect to happen?

If you open q-select with the use-input property in the modal window, the height and position of the options will break. I will attach a link to codepen, you need to watch with mobile phone emulation.

### Reproduction URL

https://codepen.io/teo-reat/pen/oNMxbLQ?editors=1010

### How to reproduce?

1. Go to link
2. Open devtools
3. Use mobile version emulation
4. Сlick on button, in opened modal click on select
5. Instead of taking up most of the screen in height, the options window is reduced to half the screen and occupies a position at the top without indentation.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Style & Identity (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
Hello

This is the normal behavior on mobile (and the space on bottom is the keyboard on the real mobile)
It you want the desktop look use `behaviour="menu"`
