### ISSUE TITLE
Use american english for color names (grey should be gray)

### ISSUE THREAD

**Issue by MartinMuzatko** [quasarframework/quasar#1520]
Hello!

I noticed, since the rest of the website and project is in american english, the color names should adhere to that convention too.

Which is why I would suggest to rename `grey` to `gray`. Or at least, create an alias if you care about backwards compatibility.

`blue-grey` would also have to be renamed to `blue-gray`.

Your thoughts?

**Comment by rstoenescu** [comment]
Hi,

Just following the Material Guidelines, which specify "grey".
https://material.io/guidelines/style/color.html#color-color-palette

**Comment by MartinMuzatko** [comment]
Interesting! thanks for clarifying :)
