### ISSUE TITLE
Loading will record the scroll position when the routing page changes

### ISSUE THREAD

**Issue by YangQuan666** [quasarframework/quasar#15211]
### What happened?

i'm using quasar in my vitepress project,and I added a loading animation when the route changes, but I found that when the route is switched, the new page will scroll to the previous page position, which seems to be a bug,
this is my code:
1. `.vitepress/config.js`
  ```js 
  export default {
      Layout,
      NotFound: Error404,
      enhanceApp({app, router, siteData}) {
          initQuasar(app)
  
          router.onBeforeRouteChange = () => {
              Loading.show({message: '(ง •̀_•́)ง (*•̀ㅂ•́)و 努力加载中...'})
          }
  
          router.onAfterRouteChanged = () => {
              Loading.hide()
          }
      }
  }
  ```
2. `Layout.vue`
```vue
<template>
  <q-img src="mountain.jpg" height="400px" alt="background">
    <h3 class="absolute-full flex flex-center">
      When in doubt, use brute force.
    </h3>
  </q-img>
  <div class="row animate__animated animate__fadeIn">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2">
      <q-timeline :layout="layout" color="secondary">
        <q-timeline-entry heading>时间轴（{{summaries.length}}）</q-timeline-entry>
        <q-timeline-entry
            v-for="summary in summaries"
            :title="summary.title"
            :subtitle="summary.time"
            side="left"
        >
          <div class="text-caption">{{ summary.excerpt }}</div>
          <q-btn
              flat
              color="info"
              @click="router.go(summary.link)"
          >
            阅读全文
          </q-btn>
        </q-timeline-entry>
      </q-timeline>
    </div>
  </div>
</template>

<script setup>
import {computed} from 'vue'
import {useRouter} from 'vitepress'
import {useQuasar} from 'quasar'
import summaries from '../../../post/summary.json'

const router = useRouter()
const $q = useQuasar()

const layout = computed(() => $q.screen.lt.sm ? 'dense' : 'comfortable')
</script>
```

### What did you expect to happen?

I expect the new page position is zero

### Reproduction URL

https://codesandbox.io/p/github/YangQuan666/yangquan666.github.io/draft/elastic-darkness?file=%2Fdocs%2F.vitepress%2Ftheme%2Findex.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A154%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A154%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clcd9z83v000k7ni0e5h50brk%2522%252C%2522openFiles%2522%253A%255B%2522%252Fdocs%252Fpost%252Ftest.md%2522%252C%2522%252Fdocs%252F.vitepress%252Ftheme%252Fcomponents%252FTimeline.vue%2522%252C%2522%252Fdocs%252F.vitepress%252Ftheme%252Fstyle%252Fcustom.css%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clcda1wd300133b6gl4e5icbt%2522%253A%257B%2522key%2522%253A%2522clcda1wd300133b6gl4e5icbt%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522docs%253Adev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clcdaaj3704ei3b6gh0g9ws2q%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clcda1wd300133b6gl4e5icbt%2522%252C%2522spacesOrder%2522%253A%255B%2522clcda1wd300133b6gl4e5icbt%2522%255D%257D

### How to reproduce?

1. open codesandbox
2. scroll down the page
3. Just click a button `阅读全文`
4. new page while scroll to prev page position

### Flavour

UMD

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome, Safari

### Additional context

https://user-images.githubusercontent.com/27985301/210169370-ddc15ba2-04a9-48e3-866a-e6e6df474130.mov

**Comment by rstoenescu** [comment]
Thanks for reporting this.
Fix will be available in Quasar v2.11.5 and v1.22.5
