### ISSUE TITLE
dialog in dialog bugger

### ISSUE THREAD

**Issue by linfulongnet** [quasarframework/quasar#15223]
### What happened?

dialog in dialog bugger, when child dialog full screen, parent dialog overlay full screen window

### What did you expect to happen?

when child dialog full screen, parent dialog not covered full screen window

### Reproduction URL

https://codepen.io/linfulongnet/pen/jOpMjJJ?editors=101

### How to reproduce?

1.to go the provided reproduction link
2.Click on 'Open another dialog'
3.Click on 'Fillscreen'
4.See the error

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.11.4
