### ISSUE TITLE
QRating v2.1.9+ onKeyup error

### ISSUE THREAD

**Issue by mariofagac** [quasarframework/quasar#15235]
### What happened?

Error after update from version 2.1.9 to recent ones (keyboard navigation with arrow keys not working for Electron and SPA builds).
![Screen Shot 1](https://user-images.githubusercontent.com/33401013/211181929-33f6014c-67ce-4d97-9dd1-f439701cf8ca.jpg)

### What did you expect to happen?

To work as before update.

### Reproduction URL

https://quasar.dev/vue-components/rating

### How to reproduce?

Just open basic usage codepen demo from docs site.
https://quasar.dev/vue-components/rating

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari, Electron, Other

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.11.5

**Comment by mariofagac** [comment]
Thanks.
