### ISSUE TITLE
@quasar/app-vite does not support TS 4.9+ 'satisfies' operator

### ISSUE THREAD

**Issue by cohlar** [quasarframework/quasar#15242]
### What happened?

I upgraded `typescript` to version `4.9.4` and started using the new `satisfies` operator.
When running the dev server with `@quasar/app-vite` version `1.1.3`, I got the following error: `Expected ";" but found "satisfies"`.

### What did you expect to happen?

No error.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-ihkpgu?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to the provided reproduction link
2. Run `npm run dev`
3. See error

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.12.1

Global packages
  NPM - 9.1.1
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.28 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.31.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - LAPTOP-GALIM
  Wi-Fi - 192.168.100.12
  vEthernet (WSL) - 172.23.176.1
```

### Additional context

I believe it has to do with the version of `esbuild` - [the `satisfies` operator is only supported from version `v0.15.13`](https://github.com/evanw/esbuild/releases/tag/v0.15.13).

**Comment by yusufkandemir** [comment]
Thanks for the useful report. Quasar CLI with Vite is using Vite v2. The latest Vite v2.x version is v2.9.15, which uses esbuild v0.14.x. So, this is not possible with Vite 2. This will automatically be addressed with the planned Vite 3/4 support (#14077). There is a workaround to use Vite 3/4 with the current Quasar CLI with Vite version, in case you want to try: https://github.com/quasarframework/quasar/issues/14077#issuecomment-1353213893 It might not fully work as Quasar uses `esbuild` for building extra files for modes like Electron, BEX, etc., in that case, override the esbuild version and hope it works as well.
