### ISSUE TITLE
q-input textarea doesn't seem to respect :min-rows

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#1525]
### Software version

Quasar: 0.15.0-beta.39

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/muehjhao/3/

### What did you get as the error?
Always a 2-line textarea

### What were you expecting?
Different numbers of lines. I can't find any reference to that prop in the `q-input` source code, but it's used in the dev demo.

**Comment by rstoenescu** [comment]
Demo is outdated in some places. Use the native "rows" instead. No need to bind it, since all unrecognised props are attached as attributes to the input (in order to allow for autocompletion & co & other native attributes to be configured).
