### ISSUE TITLE
V2.11.5 Q-tree  -> unexpand  transition laging -> like 2 steps transition -> not Smooth at all

### ISSUE THREAD

**Issue by gowy222** [quasarframework/quasar#15262]
### What happened?

https://quasar.dev/vue-components/tree
not just in doc demo, also in real project.

click item(folder), expanding sub-items(files) is ok, transition smooth very;

and click item(folder) again -> to unexpand  sub-items(files) is laging, transition was thru 2 times, not smooth  at all..

### What did you expect to happen?

unexpand  transition smooth  

### Reproduction URL

https://quasar.dev/vue-components/tree

### How to reproduce?

click any tree item to unexpand  sub-items

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by gowy222** [comment]
I guess ... duration =>Default  300 make this lag?
unexpand compute sub-item should not thru duration, maybe..

**Comment by pdanpdan** [comment]
Do you see the same thing in the Dense example?
~Because I think what you see is the start of the animation where the empty space on bottom starts shrinking and you don't have a visual feedback of what is happening~
In fact the bottom padding change is not animated

**Comment by gowy222** [comment]
@pdanpdan well...it is :P

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.6 and v1.22.6
