### ISSUE TITLE
@paste no longer supported fo

### ISSUE THREAD

**Issue by Sylv4nn** [quasarframework/quasar#15267]
### What happened?

After updating to quasar 2 we noticed that <q-select> no longer supported @paste event, which we were using to handle when an user pasted in multiple cell rows from excel. Since @paste doesn't work anymore, we can't split based on \n since it's automatically removed in the <q-select/> field

### What did you expect to happen?

Expectation is that on the @paste event, the pasteData function that's defined in the codepen attachment would execute and start reading the clipboard where the "\n" is not yet removed, so that we can add multiple chips after paste.

### Reproduction URL

https://codepen.io/Drudututu/pen/GRBEWrq?editors=1011

### How to reproduce?

Paste in 10 copied rows from Excel into the select field, e.g.
Example 1
Example 2
Example 3
Example 4
Example 5
Example 6
Example 7
Example 8
Example 9
Example 10

expected outcome would be that it adds it all as 10 separate chips, example 1... example 10

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Additional context

We just converted to quasar 2 from quasar 1, and noticed that @paste wasn't in the breaking changes documentation, and we were wondering if it just fell through the cracks during upgrade?  Is it possible to add the feature back to quasar 2?

**Comment by pdanpdan** [comment]
There is no more `.native` modifier for event listeners in Vue3 (https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed.html)

~For some reason I cannot identify now~ if you use `@paste` on QSelect it is not working, but if you put it on a parent it is working.

@rstoenescu it looks like we are not binding `splitAttrs.listeners` when we use `inheritAttrs: false` in QSelect, QFile ...

**Comment by Sylv4nn** [comment]
That works great!
Thank you for the quick response 😊

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.11.8
