### ISSUE TITLE
Click on q-btn with loading prop will trigger "[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event" message.

### ISSUE THREAD

**Issue by guogangj** [quasarframework/quasar#15278]
### What happened?

Click on QBtn with loading prop will trigger the brower print a [Violation] message: [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

![image](https://user-images.githubusercontent.com/6103026/212582618-848a79b5-6547-47ba-ae6f-cb729471626a.png)

### What did you expect to happen?

The [Violation] message should not be shown.

### Reproduction URL

https://codepen.io/pen?&editors=101&prefill_data_id=65b0c8fb-8bd2-42bb-b741-06a09cfc0e5e

### How to reproduce?

1, Go to the QBtn's document page: [https://quasar.dev/vue-components/button#progress-related](https://quasar.dev/vue-components/button#progress-related)
2, click the "Edit in Codepen" button to open Codepen.
3, Press F12 to open browser's devtools then switch to the Console tab. 
4, Click on the buttons with loading state, then you will see the [Violation] message on the Console output.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 16.13.2

Global packages
  NPM - 8.1.2
  yarn - 1.22.4
  @quasar/cli - 1.3.2
  @quasar/icongenie - 2.4.0
  cordova - Not installed

Important local packages
  quasar - 2.11.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.30.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by pdanpdan** [comment]
This is because the touchstart event in that case cannot be passive (it is attached while the button is in the loading state)

**Comment by imvenx** [comment]
I keep having this problem, please @pdanpdan can you give an example of a way on how this should be handled then if it is not a bug?

In my case I have a desktop app, it calls electron to execute a command, in the meanwhile I want to leave this button as loading state, I don't know what would be wrong with that approach and how to address... One way would be to add a v-if with a loading spinner, but don't see the point of dong that when the component has already a spinner.

**Comment by pdanpdan** [comment]
Because the internal spinner also prevents clicking on the button. If you want a simple spinner use a spinner inside the button with v-if

**Comment by imvenx** [comment]
Ok, then if I understood correctly.. Loading prop and button events are not compatible? At least some of them like click

**Comment by pdanpdan** [comment]
I don't understand what you mean.
Last time - loading prop does 2 things:
- show loading indicator
- prevent the button from being clicked/pressed/whatever
