### ISSUE TITLE
CookieManager flush needed

### ISSUE THREAD

**Issue by RAIbrahim360** [quasarframework/quasar#15270]
### What happened?

After saving a cookie if reopen app, cookies will be removed, but if you stay in the app for about 30 seconds before reopening, cookies won't be removed. it seems there is a 30 second timer on the sync process between WebView and CookieManager. It is known issue. We can solve this by manually flushing the CookieManager.

### What did you expect to happen?

When I open the app again the cookies will exist

### Reproduction URL

https://codepen.io/Ibishka/pen/RwBgYGP

### How to reproduce?

After saving a cookie if reopen app, cookies will be removed, but if staying in app for about 30 second before reopening, cookies will not be removed.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 16.15.1

Global packages
  NPM - 8.11.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - 11.0.0

Important local packages
  quasar - 2.11.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.6.2 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.15.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.28 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.18.6 -- Babel compiler core.
  webpack - 5.73.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.9.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 2.5.0 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/cli - 2.5.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 2.5.0 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/ios - 2.5.0 -- Capacitor: cross-platform mobile apps with the web

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
Hi,

First of all, you haven't specified what Quasar mode you are using.
Secondly, regardless of the Quasar mode, it is not Quasar that manages the WebView in any shape or form. If something seems off with the cookies management, please refer to Capacitor or Cordova teams (assuming you are talking about one of these modes).
