### ISSUE TITLE
QMenu/QPopupProxy inside QInput does not focus correctly

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#15285]
### What happened?

Typically I would place a QPopupProxy inside a QInput to offer some suggestions for results that can be picked (No issues with Quasar 1).

The popup itself has a static model-value where the `@focus` and `@blur` of the `<q-input>` manages the active state of the popup.

However I am unable to interact with anything inside the QPopupProxy. When attempting to interact with the items, the popup will close (as the state has moved away directly from QInput).

### What did you expect to happen?

The "focus" should remain on the QInput item, while still allowing the user to interact with items inside the QMenu/QPopupProxy.

Once the user has clicked on another DOM element (not the QInput or popup), the @blur event should be triggered.

### Reproduction URL

https://github.com/nicholaszuccarelli/quasar-broken-popover-inside-field

### How to reproduce?

-Clone git project
-npm install
-quasar dev
-Click on the QInput
-Attempt to click on an item which pops up in the QPopupProxy (clicking an item should update the QInput value) - the dropdown will flicker and the QInput value change will not trigger as @blur was triggered

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), SPA Mode

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 16.18.1

Global packages
  NPM - 8.19.2
  yarn - Not installed
  @quasar/cli - 1.4.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.7.1 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.15.9 -- Quasar Framework fonts, icons and animations

Networking
  Host - NICHOLAS-PCi9
  vEthernet (WSL) - 172.17.176.1
  Ethernet - 192.168.1.50
```

**Comment by nicholaszuccarelli** [comment]
Closing this issue as I've found a solution to this problem - although I still feel it is technically wrong that focus is placed out of the input box when interacting with its QMenu, unlike Quasar 1.

**Comment by Qualzz** [comment]
bruh, when you found a solution, post it.
