### ISSUE TITLE
Quasar CLI 2.0 + Quasar/app-webpack 3.7.0 => Build Error: Cannot find module 'loader-utils/lib/stringifyRequest'

### ISSUE THREAD

**Issue by gowy222** [quasarframework/quasar#15280]
### What happened?

  "dependencies": {
    "@quasar/extras": "^1.15.9",
    "@vueuse/core": "^9.10.0",
    "axios": "^1.2.2",
    "core-js": "^3.27.1",
    "echarts": "^5.4.1",
    "file-saver": "^2.0.5",
    "material-icons": "^1.13.1",
    "naive-ui": "^2.34.3",
    "pinia": "^2.0.29",
    "quasar": "^2.11.5",
    "vue": "^3.2.45",
    "vue-echarts": "^6.5.1",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@arco-design/web-vue": "^2.42.0",
    "@quasar/app-webpack": "^3.7.0",
    "babel-plugin-import": "^1.13.6",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "uglify-js": "^3.17.4",
    "unplugin-auto-import": "^0.12.1",
    "unplugin-vue-components": "^0.22.12"
  },

==================================
quasar.config.js = > build = >uglifyOptions: {
        compress: {

          drop_debugger: true, 
          dead_code: true,
          drop_console: true,

        },
}
====================================
quasar b
====================================
Err:

` App • Chaining "UI" Webpack config
 App • Cleaned build artifact: "D:\mycode\quasar_oms\oms\dist\spa"
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 8003ms

 App •  ERROR  •  UI  in ./src/App.vue

Error: Cannot find module 'loader-utils/lib/stringifyRequest'
  Require stack:
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\webpack\loa
  der.vue.auto-import-quasar.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\webpack@5.75.0_uglify-js@3.17.4\node_modules\webpack\lib\ProgressPlugin.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\webpack@5.75.0_uglify-js@3.17.4\node_modules\webpack\lib\index.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\cmd\build.j
  s
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\bin\quasar     
  - D:\nodejs\cache_folder\node_global\node_modules\@quasar\cli\bin\quasar.js

  - loader:933 Function.Module._resolveFilename
    node:internal/modules/cjs/loader:933:15

  - loader:778 Function.Module._load
    node:internal/modules/cjs/loader:778:27

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

  - helpers:102 require
    node:internal/modules/cjs/helpers:102:18

  - loader.vue.auto-import-quasar.js:3 Object.<anonymous>
    [oms]/[@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:3:26

  - loader:1103 Module._compile
    node:internal/modules/cjs/loader:1103:14

  - loader:1155 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1155:10

  - loader:981 Module.load
    node:internal/modules/cjs/loader:981:32

  - loader:822 Function.Module._load
    node:internal/modules/cjs/loader:822:12

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

  - helpers:102 require
    node:internal/modules/cjs/helpers:102:18

  - ProgressPlugin.js:412
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/ProgressPlugin.js:412:9

  - NormalModule.js:809 NormalModule._doBuild
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/NormalModule.js:809:24

  - NormalModule.js:963 NormalModule.build
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/NormalModule.js:963:15

  - Compilation.js:1371
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/Compilation.js:1371:12

  - NormalModule.js:1253 NormalModule.needBuild
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/NormalModule.js:1253:32

  - Compilation.js:1352 Compilation._buildModule
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/Compilation.js:1352:10

  - AsyncQueue.js:303
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/util/AsyncQueue.js:303:10

  - AsyncQueue.js:293 AsyncQueue._startProcessing
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/util/AsyncQueue.js:293:26

  - AsyncQueue.js:280 AsyncQueue._ensureProcessing
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/util/AsyncQueue.js:280:12

  - timers:466 processImmediate
    node:internal/timers:466:21

 App •  ERROR  •  UI  in ./src/components/com_Q_copyBtn.vue

Error: Cannot find module 'loader-utils/lib/stringifyRequest'
  Require stack:
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\webpack\loa
  der.vue.auto-import-quasar.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\loader-runner@4.3.0\node_modules\loader-runner\lib\loadLoader.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\loader-runner@4.3.0\node_modules\loader-runner\lib\LoaderRunner.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\webpack@5.75.0_uglify-js@3.17.4\node_modules\webpack\lib\NormalModule.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\vue-loader@17.0.1_vue@3.2.45+webpack@5.75.0\node_modules\vue-loader\dist\pluginWebpack5.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\vue-loader@17.0.1_vue@3.2.45+webpack@5.75.0\node_modules\vue-loader\dist\plugin.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\vue-loader@17.0.1_vue@3.2.45+webpack@5.75.0\node_modules\vue-loader\dist\index.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\webpack\cre
  ate-chain.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\webpack\ind
  ex.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\quasar-conf
  -file.js
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\lib\cmd\build.j
  s
  - D:\mycode\quasar_oms\oms\node_modules\.pnpm\@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra\node_modules\@quasar\app-webpack\bin\quasar     
  - D:\nodejs\cache_folder\node_global\node_modules\@quasar\cli\bin\quasar.js

  - loader:933 Function.Module._resolveFilename
    node:internal/modules/cjs/loader:933:15

  - loader:778 Function.Module._load
    node:internal/modules/cjs/loader:778:27

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

  - helpers:102 require
    node:internal/modules/cjs/helpers:102:18

  - loader.vue.auto-import-quasar.js:3 Object.<anonymous>
    [oms]/[@quasar+app-webpack@3.7.0_4lbzpzy7sfz64dihnzwjgcy3ra]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:3:26

  - loader:1103 Module._compile
    node:internal/modules/cjs/loader:1103:14

  - loader:1155 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1155:10

  - loader:981 Module.load
    node:internal/modules/cjs/loader:981:32

  - loader:822 Function.Module._load
    node:internal/modules/cjs/loader:822:12

  - loader:1005 Module.require
    node:internal/modules/cjs/loader:1005:19

  - helpers:102 require
    node:internal/modules/cjs/helpers:102:18

  - loadLoader.js:19 loadLoader
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/loadLoader.js:19:17

  - LoaderRunner.js:182 iteratePitchingLoaders
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:182:2

  - LoaderRunner.js:178 iteratePitchingLoaders
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:178:10

  - LoaderRunner.js:189
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:189:18

  - loadLoader.js:53 handleResult
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/loadLoader.js:53:2

  - loadLoader.js:35 loadLoader
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/loadLoader.js:35:10

  - LoaderRunner.js:182 iteratePitchingLoaders
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:182:2

  - LoaderRunner.js:178 iteratePitchingLoaders
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:178:10

  - LoaderRunner.js:189
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:189:18

  - loadLoader.js:53 handleResult
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/loadLoader.js:53:2

  - loadLoader.js:35 loadLoader
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/loadLoader.js:35:10

  - LoaderRunner.js:182 iteratePitchingLoaders
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:182:2

  - LoaderRunner.js:398 runLoaders
    [oms]/[loader-runner@4.3.0]/[loader-runner]/lib/LoaderRunner.js:398:2

  - NormalModule.js:819 NormalModule._doBuild
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/NormalModule.js:819:3

  - NormalModule.js:963 NormalModule.build
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/NormalModule.js:963:15

  - Compilation.js:1371
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/Compilation.js:1371:12

  - NormalModule.js:1253 NormalModule.needBuild
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/NormalModule.js:1253:32

  - Compilation.js:1352 Compilation._buildModule
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/Compilation.js:1352:10

  - AsyncQueue.js:303 
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/util/AsyncQueue.js:303:10

  - AsyncQueue.js:293 AsyncQueue._startProcessing
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/util/AsyncQueue.js:293:26

  - AsyncQueue.js:280 AsyncQueue._ensureProcessing
    [oms]/[webpack@5.75.0_uglify-js@3.17.4]/[webpack]/lib/util/AsyncQueue.js:280:12

  - timers:466 processImmediate
    node:internal/timers:466:21

 App •  COMPILATION FAILED  • Please check the log above for details.`

### What did you expect to happen?

no err

### Reproduction URL

nop

### How to reproduce?

just mins ago!

quasar upgrade -i  (PNPM)

npm install @quasar/cli -g

quasar b

then err.. after 98%

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by gowy222** [comment]
node -v =>v16.14.0

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. For some reason, this isn't a problem with Yarn so missed the wrong loader-utils reference.

Fixed (and released) in q/app-webpack 3.7.1
