### ISSUE TITLE
[Bug] QAutocomplete - TAB on PC does not close options list

### ISSUE THREAD

**Issue by Miosss** [quasarframework/quasar#1529]
### Software version

Quasar: 0.14.7
OS: Windows 10
Node: 9.3.0
NPM: 5.6.0
Browsers: Chrome 63 / Vivaldi 1.14
iOS: -
Android: -

### JsFiddle (for Quasar v0.15+ only)
http://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/autocomplete

### What did you get as the error?
Suggestion list stays after input for autocomplete losts focus due to TAB navigation. Mouse click on other part of page correctly closes the list.

### What were you expecting?
That list would hide on input blur, just as it does when focus is lost due to mouse click.

### What steps did you take, to get the error?
1. Use PC.
2. Start typing until suggestions list show on QAutocomplete.
3. Press TAB to navigate to other field.
4. Suggestions list stays visible.

**Comment by rstoenescu** [comment]
Hi,

Already fixed in v0.15, so closing this.
