### ISSUE TITLE
Update q-table#body docs slots to show how to handle row clicks

### ISSUE THREAD

**Issue by ajmas** [quasarframework/quasar#15293]
### Description

It would be useful to update the documentation for q-table -> body slots' so it demonstrates how to handle the row click scenario.

There is an [existing closed ticket ](https://github.com/quasarframework/quasar/issues/12451) where help was asked for and provided, but it would be better that the solution is part of the documentation, rather than having people needing to find it in the issues.

The example would be updated such that an `onRowClick` function would be added (key parts of examples are reproduced with the changes):

```html
<template>
  <div class="q-pa-md">
    <q-table
      title="Treats"
      :rows="rows"
      :columns="columns"
      row-key="name"
    >
      <template v-slot:body="props">
        <q-tr :props="props" @click="onRowClick(props.row)">
...
        </q-tr>
      </template>
    </q-table>
  </div>
</template>
```

```js

const app = Vue.createApp({
  setup () {
    return {
      onRowClick: (row) => alert(`${row.name} clicked`),
      columns,
      rows
    }
  }
})
```

If this is considered okay as an addition, I can provide the changes.

### Documentation Section URL

https://quasar.dev/vue-components/table#body-slots

### Flavour

None

### Areas

Components (quasar)

**Comment by ajmas** [comment]
Added PR: https://github.com/quasarframework/quasar/pull/15294

**Comment by rstoenescu** [comment]
Merged PR. Will be available on next docs deployment.
Thanks everyone
