### ISSUE TITLE
"using / for division outside of calc() is deprecated" Dart Sass error.

### ISSUE THREAD

**Issue by Derasm** [quasarframework/quasar#15299]
### What happened?

Installed Quasar Vite plugin to existing project.

Did not install Sass version 1.32.12 as this is 2 years outdated.

- Installed packages sans the "extra" package.
- added to main.ts
- created quasar-variables.css
- created quasar.config.js
Started project, got error
"Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0. "
This comes in the following variations:
- ```$rad: $angle / 180 * $PI```
- ```$sin: $sin + pow(-1, $i) * pow($rad, (2 * $i + 1)) / fact(2 * $i + 1)```
- ```$cos: $cos + pow(-1, $i) * pow($rad, 2 * $i) / fact(2 * $i)```
- ``` @return round($number * $power) / $power```

Due to the error build tasks are failing.

If this is due to Sass 1.32.12 missing, the recommendation is using their automated migrator [Sass automated migrator](https://sass-lang.com/d/slash-div)

If this is due to something else, i have no clue what.

### What did you expect to happen?

Project would start up as usual, without the deprecation warnings. 

### Reproduction URL

https://codepen.io/Derasm/pen/dyjZKEX

### How to reproduce?

Install vite plugin to existing project
DO NOT use sass 1.32.12 as it is 2 years old.
do the usual: Main.ts file, quasar-variables.css, quasar.config.js

start project

See deprecation errors

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by yusufkandemir** [comment]
https://github.com/quasarframework/quasar/issues/9362
