### ISSUE TITLE
DialogPlugin - After closing a regular dialog, it emits double update on modelValue

### ISSUE THREAD

**Issue by juakotorres** [quasarframework/quasar#15301]
### What happened?

We are building an app with a dismiss confirmation dialog. This dialog asks the user if they want to dismiss the dialog before saving. So what happens is that after opening a confirmation dialog "B" to dismiss another dialog "A", it reopens again dialog "B". The steps are the following:

1. Open a Dialog "A"
2. Try to close the dialog by clicking outside
3. This opens a new dialog "B" confirming to close "A"
4. After confirming it closes both dialogs "A" and "B", but reopens "B" again.

We investigated this a little bit and found out that in dialog "A" the modelValue is updated twice triggering the confirmation dialog twice. With further investigation, we discovered that this bug appeared in Quasar version `2.10.1`, this does not happen in version `2.10.0`.  

In the implementation, we followed the guidelines given on the official site -> https://quasar.dev/quasar-plugins/dialog#sfc-with-script-setup-and-composition-api-variant

### What did you expect to happen?

Both dialogs should be closed and no new dialog should be opened again.

### Reproduction URL

https://github.com/juakotorres/QuasarTestDialog

### How to reproduce?

We opened a repository because we wanted to show both examples in a different version of Quasar. The repository was created using Quasar CLI with Webpack.

In the repository, you have a simple example of two buttons that each opens a dialog. One opens the dialog with the bug and the other one is an approach we made to solve the issue.  

There are two branches, one is `master` which shows the example with the bug and there is a branch `quasar-2.10.0` which contains the same app but with an old version of quasar working.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Plugins (quasar), Composables (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System - Darwin(22.2.0) - darwin/x64
NodeJs - 18.12.1

Global packages
  NPM - 8.19.2
  yarn - 1.22.15
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.7.1 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.15.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.20.12 -- Babel compiler core.
  webpack - 5.75.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Joaquins-MacBook-Pro.local
  en0 - 192.168.113.26
```

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.6.
