### ISSUE TITLE
quploader component not working with ref

### ISSUE THREAD

**Issue by gvdes** [quasarframework/quasar#15329]
### What happened?

created a reference to the "q uploader" component to be able to access its methods (ex. pickFiles(), reset(), upload(), etc) and computed properties (ex. files, queuedFiles, etc), however I have not been able to call them :(

### What did you expect to happen?

I want to access the methods and computed properties of a "quploader" component from a reference, or know if the way I'm trying is wrong, (drag and drop if they work)

### Reproduction URL

https://stackblitz.com/edit/quasarframework-ncj7d1?file=src%2Flayouts%2FQUploaderImg.vue

### How to reproduce?

1. open my stackblitz
2. click on button + (the only button)
3. and see how nothing happens

the pickFiles event should be executed (to open the file explorer), but it doesn't

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Android

### Quasar info output

```Shell
there is no way out of any kind, since there are no errors or warnings of any kind
```

**Comment by metalsadman** [comment]
related https://github.com/quasarframework/quasar/issues/14967
