### ISSUE TITLE
QuasarBuildConfiguration after/before method argument types lack ctx object

### ISSUE THREAD

**Issue by BenceSzalai** [quasarframework/quasar#15336]
### What happened?

The `build` property in `quasar.config.js` has optional methods: `beforeDev`, `afterDev`, `beforeBuild` and `afterBuild` as declared in [`app-vite/types/configuration/build.d.ts`](https://github.com/quasarframework/quasar/blob/dev/app-vite/types/configuration/build.d.ts#L155-L186).
The argument of these methods is declared to be a [`QuasarHookParams`](https://github.com/quasarframework/quasar/blob/dev/app-vite/types/configuration/conf.d.ts#L91-L93) type, which in turn has a `quasarConf` property typed as [`QuasarConf`](https://github.com/quasarframework/quasar/blob/dev/app-vite/types/configuration/conf.d.ts#L95).

During the execution of these methods `quasarConf` passed to the implementation includes a property called `ctx` that is of the type [`QuasarContext`](https://github.com/quasarframework/quasar/blob/dev/app-vite/types/configuration/context.d.ts#L145)

However `QuasarConf` does not declare `ctx` to be part of the contract.

### What did you expect to happen?

`QuasarHookParams` should declare `quasarConf` to be typed as the union of `QuasarConf` and `{ctx: QuasarContext}`, e.g.:

https://github.com/quasarframework/quasar/blob/dev/app-vite/types/configuration/conf.d.ts#L91-L93 should be roughly something meaning:
```ts
export interface QuasarHookParams {
  quasarConf: QuasarConf & { ctx: QuasarContext };
}
```

### Reproduction URL

https://stackblitz.com/edit/quasarframework-s4anc3?file=quasar.config.js%3AL80

### How to reproduce?

1. Go to reproduction link (or any projects in an IDE)
2. Try to get type hints for the `ctx` as shown in the example above (from line 80 in quasar.config.js)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), TypeScript Support

### Quasar info output

```Shell
Operating System - Linux(5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36) - linux/x64
NodeJs - 16.14.2

Global packages
  NPM - 7.17.0
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.9.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.40 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.24.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - quasarframeworks4anc3-mslz
  en0 - 192.168.1.104
```

**Comment by rstoenescu** [comment]
Hi,

The `ctx` that you should use is the returning function param in quasar.config.js:

```js
module.exports = function (ctx) {
```

If you are writing an AppExtension, then you have `api.ctx` from:

```js
module.exports = function (api) {
```

The fact that at some point `ctx` is in the quasarConf object should not be relied upon.

**Comment by BenceSzalai** [comment]
Ahhhh, what a "can't see the forest for the trees" situation. Indeed the `ctx` object is available from the outer scope.

Thanks for looking into it and sorry for wasting your time!

**Comment by rstoenescu** [comment]
No problem. Thanks for wanting to improve Quasar!
