### ISSUE TITLE
FYI:  PlaceIMG is shutting down in June

### ISSUE THREAD

**Issue by corepay** [quasarframework/quasar#15339]
### Description

<img width="901" alt="image" src="https://user-images.githubusercontent.com/48992923/215328525-f344150b-311b-4563-acf8-637a0768d77f.png">

### Documentation Section URL

https://quasar.dev/vue-components/img

### Flavour

None

### Areas

Components (quasar)

**Comment by MilosPaunovic** [comment]
Hi @corepay, nice catch!

Are you willing to make a contribution to Quasar with a PR which will handle this?
You can use another convenient placeholder API, which you can find at `https://picsum.photos/`.

**Comment by rstoenescu** [comment]
Thanks for reporting. This will be available on next docs deployment.
