### ISSUE TITLE
Typescript signature for debounce is wrong

### ISSUE THREAD

**Issue by Buri** [quasarframework/quasar#15346]
### What happened?

When we `debounce` function, it no longer returns the same value as the original function. However, the typescript signature states that it returns the original function. This is no longer the case.

### What did you expect to happen?

Expected
```typescript
function foo = (bar: number): number => bar * 3; // (bar: number): number
const debouncedFoo = debounce(foo, 150); // (bar: number): void
```

Actual:
```typescript
function foo = (bar: number): number => bar * 3; // (bar: number): number
const debouncedFoo = debounce(foo, 150); // (bar: number): number - wrong
```

### Reproduction URL

https://codepen.io/Buri-the-scripter/pen/MWBqYmV

### How to reproduce?

Use debounced function where original returns a value.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

TypeScript Support

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by pdanpdan** [comment]
Maybe something like this would be better?
https://gist.github.com/ca0v/73a31f57b397606c9813472f7493a940?permalink_comment_id=4307328#gistcomment-4307328
