### ISSUE TITLE
QModal causes QInputs to render incorrectly on iOS Mobile Safari

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#1534]
### Software version

Quasar: 0.15
Browsers: Mobile Safari
iOS: 11.1.2

### JsFiddle (for Quasar v0.15+ only)
This bug has been there since at least 0.14, hoping it had gone in 0.15, but seems still the same. Can't easily be reproduced in a fiddle, as it happens when inputs are used in a QModal that opens 'full screen'. JSFiddle seems to defeat that. Paste this into `index.vue` inside the starter kit app (and add QModal and QInput to the configuration file):

```
<template>
  <q-page class="flex flex-center">
    <q-input v-model="text01"></q-input>
    <q-input v-model="text02"></q-input>
    <q-input v-model="text03"></q-input>
    <q-input v-model="text04"></q-input>
    <q-input v-model="text05"></q-input>
    <q-input v-model="text06"></q-input>
    <q-input v-model="text07"></q-input>
    <q-input v-model="text08"></q-input>
    <q-input v-model="text09"></q-input>
    <q-input v-model="text10"></q-input>

    <q-btn @click="$refs.modal.show()">Open Modal</q-btn>
    <q-modal ref="modal">
      <q-input v-model="text01"></q-input>
      <q-input v-model="text02"></q-input>
      <q-input v-model="text03"></q-input>
      <q-input v-model="text04"></q-input>
      <q-input v-model="text05"></q-input>
      <q-input v-model="text06"></q-input>
      <q-input v-model="text07"></q-input>
      <q-input v-model="text08"></q-input>
      <q-input v-model="text09"></q-input>
      <q-input v-model="text10"></q-input>
    </q-modal>
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  data () {
    return {
      text01: '',
      text02: '',
      text03: '',
      text04: '',
      text05: '',
      text06: '',
      text07: '',
      text08: '',
      text09: '',
      text10: '',
    }
  }
}
</script>
```

### What did you get as the error?
Inputs on the main page work nicely on mobile safari, and you can use the up/down arrows above the iOS keyboard to 'tab' between inputs. But once you open the modal, the input caret starts to be rendered in the 'wrong' place vertically, sometimes not being visible at all, and usually being 'below' the actual input which is focused.

### What were you expecting?
Inputs inside a QModal to work the same as on the main page.

The first few inputs (in the QModal) work OK, but by about input 4 or 5 (on my device—resolution probably plays a part here), the iOS screen is starting to scroll, and it seems _that_ is what upsets the caret positioning. I think mobile safari tries to scroll the page to keep the active input in view, and this is somehow conflicting with the QModal scroll behaviour. Note it can sometimes take a few 'goes' moving the focus up and down before the problem shows up. But I've never failed to be able to get it to go wrong, just by focusing different inputs (in the QModal) and then using the up / down arrows a handful of times, making sure that iOS is scrolling the view.

**Comment by rstoenescu** [comment]
Can anyone reproduce this? Seems that I can't....
@dsl101 Can you install this Cordova plugin (that replaces the default ios buggy webview with a better one) and report back? https://github.com/ionic-team/cordova-plugin-ionic-webview Thanks!

**Comment by dsl101** [comment]
I will try. But note this was running on node on my local dev pc which I
was browsing from my phone. I’m not using Cordova at all.

**Comment by rstoenescu** [comment]
For reference: https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8

**Comment by rstoenescu** [comment]
Reference 2: https://stackoverflow.com/questions/46339063/ios-11-safari-bootstrap-modal-text-area-outside-of-cursor

Can you add a "fixed" class to the body element after opening the modal and see if this would fix it, as many indicate?

**Comment by dsl101** [comment]
Thanks for the references—I never expected that to be as far down the hole! Good news from the Webkit bug tracker though is that it seems fixed in iOS 11.3 due out soon.

In the mean time, I can confirm, at the expense of messing up main page scroll position, adding `fixed` via a watcher does seem to solve the input box problem. I presume this is something which our app will need to handle rather than Quasar? And since the need for it should go away soon, we might even get away with just ignoring it...
```
<template>
  <q-page class="flex flex-center">
    <q-input v-model="text01"></q-input>
    <q-input v-model="text02"></q-input>
    <q-input v-model="text03"></q-input>
    <q-input v-model="text04"></q-input>
    <q-input v-model="text05"></q-input>
    <q-input v-model="text06"></q-input>
    <q-input v-model="text07"></q-input>
    <q-input v-model="text08"></q-input>
    <q-input v-model="text09"></q-input>
    <q-input v-model="text10"></q-input>
    <q-btn @click="$refs.modal.show()">Open Modal</q-btn>

    <q-modal ref="modal" v-model="modal">
      <q-input v-model="text01"></q-input>
      <q-input v-model="text02"></q-input>
      <q-input v-model="text03"></q-input>
      <q-input v-model="text04"></q-input>
      <q-input v-model="text05"></q-input>
      <q-input v-model="text06"></q-input>
      <q-input v-model="text07"></q-input>
      <q-input v-model="text08"></q-input>
      <q-input v-model="text09"></q-input>
      <q-input v-model="text10"></q-input>
      <q-btn @click="$refs.modal.hide()">CLose Modal</q-btn>
    </q-modal>
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  data () {
    return {
      modal: false,
      text01: '',
      text02: '',
      text03: '',
      text04: '',
      text05: '',
      text06: '',
      text07: '',
      text08: '',
      text09: '',
      text10: '',
    }
  },
  watch: {
    modal () {
      if(this.modal) {
        document.body.classList.add('fixed')
      } else {
        document.body.classList.remove('fixed')
      }
    }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Nope. The fix has issues. Got to think some other way. When you add "fixed" class to body you'll lose scroll position.

**Comment by dsl101** [comment]
Yes, that’s in those links. I don’t think there’s a side-effect-free fix.
Apart from hope that iOS 11.3 really does have a fix. Apparently the beta
does.

**Comment by cdnrg** [comment]
Able to reproduce. Same situation I have a maximized modal in .15 that has a very long form. Caret starts to float and be visibly moving around on the screen. Regular text inputs seem like they are typing but there are no letters showing. Once I scroll the letters appear.

**Comment by cdnrg** [comment]
Sorry I should have mentioned this is in Chrome for me. I will open a new issue with some screenshots.

**Comment by rstoenescu** [comment]
The UIWebView used on iOS devices is very very buggy. Please use WkWebView which is far superior.
https://github.com/apache/cordova-plugin-wkwebview-engine
