### ISSUE TITLE
QTree not using given generic param. 

### ISSUE THREAD

**Issue by Derasm** [quasarframework/quasar#15351]
### What happened?

Using QTreeView, an attempt was made to add an ID/key to the nodes being shown on the tree. Doing this requires augmenting the QTreeNode<unknown> with a different type, in this case, TreeNode.
Structure:

```ts
type TreeNode = { key: string } & QTreeNode<TreeNode>;
const nodes: TreeNode[] = [
  {
    key: 'foo',
    label: 'bar',
    children: []
  }
];
```
```html
<q-tree v-model:selected="selected" :nodes="nodes" dense node-key="index" />
```

### What did you expect to happen?

The nodes prop would accept the augmented type without issue, as the type had a declaration and as such should fulfill the requirement of the `QTreeNode<unknown>`.

### Reproduction URL

No repro link, see images.

### How to reproduce?

[Error statement](https://media.discordapp.net/attachments/807654245640962059/1069937693871579176/image.png)

[Type image](https://media.discordapp.net/attachments/807654245640962059/1069937742869446656/image.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Additional context

This can be fixed by doing the following instead, however, it highlights the problem that QTreenode doesn't really use the given generic parameter.
```ts
type TreeNode = { key: string } & QTreeNode<TreeNode>;
const nodes: TreeNode[] = [
  {
    key: 'foo',
    label: 'bar',
    children: []
  }
];
```

**Comment by rstoenescu** [comment]
ping @yusufkandemir
