### ISSUE TITLE
vite-plugin-vue-inspector not working

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#15378]
### What happened?

PLATFORM: 
  win10, "quasar": "^2.11.5", "@quasar/app-vite": "^1.2.0",

[vite-plugin-vue-inspector](https://github.com/webfansplz/vite-plugin-vue-inspector) not working.

It sends request to 
**GET http://0.0.0.0:9300/__open-in-editor?file=AppLibrary\libFront\GlobalComponents\HomeComp.vue:2:3**

After adding to quasar.config.js 
```
const Inspector=require('vite-plugin-vue-inspector').default
module.exports = configure(function (/* ctx */) {
  return {
....
build: {
    .....
   extendViteConf(viteConf) {
        viteConf.server.port=9300;
        viteConf.server.host='localhost';

      } ,
   vitePlugins: [ Inspector() ],  
}
```
it sends request to 
**GET http://localhost:9300/__open-in-editor?file=AppLibrary\libFront\GlobalComponents\HomeComp.vue:2:3**  
and everything works.

### What did you expect to happen?

work with default configuration

### Reproduction URL

https://stackblitz.com/edit/quasarframework-kpfr3f?file=package.json,quasar.config.js

### How to reproduce?

try new vite project

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Project Creation (create-quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by yusufkandemir** [comment]
I could not reproduce the problem. It works great for me. I also don't see why this would be a Quasar problem.

Also, do not trick the repro URL part, if you don't provide a proper reproduction, this issue will not be opened again.

**Comment by fprijate** [comment]
> 

Sory. There is now correct link [stackblitz](https://stackblitz.com/edit/quasarframework-kpfr3f?file=package.json,quasar.config.js)
But it's useless because Ctrl+Shift doesn't work ( which is required) . If you clone project and run it locally 
Ctrl+Shift works but file is not opened in local editor. In devtools you see that url is wrong.

**Comment by yusufkandemir** [comment]
> But it's useless because Ctrl+Shift doesn't work ( which is required)

It works for me. It also correctly opens the related page at the related line in the StackBlitz editor.
