### ISSUE TITLE
Translation for OK is "Vredu" in Slovenian, but should be "V redu"

### ISSUE THREAD

**Issue by janrobas** [quasarframework/quasar#15386]
### What happened?

When the dialog is created (`Dialog.create`), the label for OK in Slovenian language is `Vredu`.

### What did you expect to happen?

The label for `OK` in Slovenian language should be `V redu`. Two words instead of one.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-xjtv5x?file=src/pages/IndexPage.vue

### How to reproduce?

1. Click the button to open the dialog.
2. See that the OK button has 1 word instead of 2.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Plugins (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Additional context

`V redu` are two words that are often used together.  `Vredu` without spaces seems like a typo, since it is written as `V redu` everywhere else.

Slovenian references:
https://fran.si/208/sinonimni-slovar/4403409/v-redu?View=1&Query=v+redu
https://dariah-si.github.io/suss/suss-arhiv-000461.html

**Comment by MilosPaunovic** [comment]
Hi @janrobas, nice catch!

Are you willing to create a PR for the fix?
You can use this one as a guide: https://github.com/quasarframework/quasar/pull/14499

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.6
