### ISSUE TITLE
Double-click handler requires three taps on iOS on PWA-built app added to home screen

### ISSUE THREAD

**Issue by piperone** [quasarframework/quasar#15384]
### What happened?

I added a @dblclick-handler to a QTab-element. Using my app (built in PWA mode) on an iOS-device added to the home screen, *three* taps are required for the event to fire. This issue is probably related to #13619 and the fastclick-library which has been causing headaches on iOS. In conditions described above, tapping once on a QDialog backdrop wasn't enough to dismiss the QDialog, which you would expect. Instead two taps were required. Because of this, I expect this issue to share the same root cause as the referenced issue. #13619 was fixed previously, but unfortunately not the dblclick-issue.

### What did you expect to happen?

I expect a dblclick-event to fire after a double-click

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-oyklmv?file=src/pages/IndexPage.vue

### How to reproduce?

1. Add a dblclick-handler to a QTab-element
2. Build the app with `-m pwa`
3. Open the app on iOS Safari
4. Add the app to the home-screen
5. The QTab will now require three taps in order to fire the dblclick-event

Note:
Make sure the setting in `Settings -> Safari -> Show desktop version -> All webpages` is *OFF* (which it is by default).

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), PWA Mode

### Platforms/Browsers

iOS

### Quasar info output

```Shell
Operating System   	Darwin(21.6.0) - darwin/x64
NodeJs             	18.10.0

Global packages
  NPM              	8.19.2
  yarn             	1.22.19
  @quasar/cli      	2.0.0
  @quasar/icongenie	2.4.0
```

**Comment by rstoenescu** [comment]
Is this still happening? It should not. Please comment so I can reopen if it's still an issue. Thank you.

**Comment by piperone** [comment]
I cannot see this behavior regardless of the value of `Settings -> Safari -> Show desktop version -> All webpages` now. Seems to be fixed.
