### ISSUE TITLE
QOptionGroup with objects as values for the options does not reflect the selected option in UI at setup/created time

### ISSUE THREAD

**Issue by tjunussov** [quasarframework/quasar#15383]
### What happened?

Bug already fixed in this issue https://github.com/quasarframework/quasar/issues/13457

BUT! bug still persist at load/setup time.

Using a default (radio-button) q-option-group with objects a as values for the options the modelValue is changed correctly on selection but the UI does not reflect the state at load/setup time

### What did you expect to happen?

The radio button of the current selection should be filled (reflect the selection).

### Reproduction URL

https://codepen.io/tjunussov/pen/LYBqaYw

### How to reproduce?

The radio button of the selected option still is not filled however initial data specified
Make a selection
See that the model value changed and it's working

### Flavour

UMD

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
You are using an object that is not in the list of options (they are object literals)

**Comment by tjunussov** [comment]
One workaround ( suggested by ChatGPT :) )
is to force assign model value on initial setup 

```
created(){
   this.group = this.options.find((o)=>o.id)
}
```
