### ISSUE TITLE
QLayout adds extra space

### ISSUE THREAD

**Issue by Maurice-Mueller** [quasarframework/quasar#1539]
First, thanks for this awesome framework!

I noticed an issue, though. If I add QLayout to the main component there will be some extra space at the end of the page - which is annoying because a scrollbar is added. I generated a standard project with quasar CLI.

I already found at that deleting the **margin-top** and **height** in the style tag will remove this space. So to me it seems like a miscalculation inside the QLayout component.

```
<template>
   <!-- Don't drop "q-app" class -->
   <div id="q-app">
      <header></header>
      <main>
         <q-layout>
            <router-view />
         </q-layout>
      </main>
   </div>
</template>

<script lang="ts">
   import Vue from 'vue'
   import Component from 'vue-class-component'

   @Component({} as any)
   export default class App extends Vue {
   }
</script>

<style lang="stylus">
   @import '~variables'

   main
      text-align center
      margin-top 40px

   header
      margin 0
      height 10px
      background-color $primary
</style>
```

**Comment by rstoenescu** [comment]
Hi,

You're using QLayout wrongly unfortunately. Put your header in the "header" slot of the QLayout (assuming u are on v0.14). Please read the QLayout documentation page.

Also, please fill in the template that gets shown when logging a Github ticket. It helps both you and me. I understand quicker your scenario and you get a faster response.

Thank you,
Razvan

**Comment by Maurice-Mueller** [comment]
Hi Razvan,

thanks for the fast reply. Ok, sorry, my bad, I didn't get the part with the slots. Now I understand.

Still, QLayout has problems with margins (or I'm doing something wrong again). A simple example where QLayout adds the extra space:

```
<template>
      <q-layout id="q-app" :header-style="{'margin-top': '50px'}>
           <div slot="header">HEADER</div>
           <div slot="footer">FOOTER</div>
      </q-layout>
</template>

<script lang="ts">
   import Vue from 'vue'
   import Component from 'vue-class-component'

   @Component({} as any)
   export default class App extends Vue {
   }
</script>
```

But when I'm using **padding** instead of **margin** it works. If this is by design I'm happy to update the docs (i.e. that you have to use padding everywhere inside QLayout instead of margin).

Since padding works for me I'm happy either way ;)   Thanks again!

**Comment by rstoenescu** [comment]
QLayout is supposed to cover the entire screen, so putting a margin on it breaks things.

**Comment by Maurice-Mueller** [comment]
Yes, but since I'm putting a style on an element **inside** QLayout it's probably worth mentioning in the docs. What do you think? I can cover this part.

**Comment by rstoenescu** [comment]
Yes, sure. Thanks!

**Comment by David-code-hub** [comment]
I'm using quasar 2.10 and bumped into the same problem.

👇This helped me

My code :

```
<q-layout
    view='hHh LpR lff'
    container
    style='height: 100vh'
    class='shadow-2 rounded-borders layout-main'
  >
 </q-layout>
```

I added custom class 'layout-main' and used that to reference it's child `div` which was causing the error.

My css: 

`.layout-main div{
  right:0px!important;
}`
