### ISSUE TITLE
<a> tags in q-input #hint slot don't work

### ISSUE THREAD

**Issue by cohlar** [quasarframework/quasar#15399]
### What happened?

When I add an anchor tag to the hint slot of a `<q-input>`, clicking the link does not do anything.

### What did you expect to happen?

When clicking the link, I expect a new tab to open directing me to the specified link.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-j59q8j?file=src/pages/IndexPage.vue

### How to reproduce?

1. Go to the reproduction link
2. Click on the "Click me" button

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.12.1

Global packages
  NPM - 9.1.1
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.10 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.30 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 4.1.1 -- Native-ESM powered web dev build tool
  eslint - 8.32.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 2.0.6 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-vitest - 0.1.2 -- A Quasar App Extension for running tests with Vitest

Networking
  Host - LAPTOP-GALIM
  Wi-Fi - 192.168.100.12
  vEthernet (WSL) - 192.168.64.1
```

**Comment by cohlar** [comment]
For now I'm using the following workaround:
```vue
<a href="https://quasar.dev/" target="_blank" @click="forceRoute('https://quasar.dev/')">Click me</a>
```

```ts
const forceRoute = (link: string) => window.open(link, '_blank');
```

**Comment by yusufkandemir** [comment]
The label string, hint, etc. all go inside `<label>` which is paired with the native input. So, when you click on any of them, the input element gets focused. You should not put interactive content as the label string, hint, etc.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content
> Don't place interactive elements such as [anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) or [buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) inside a label. Doing so makes it difficult for people to activate the form input associated with the label.

**Comment by cohlar** [comment]
Got it, thank you for the clarification.
