### ISSUE TITLE
Bug QUploader when emit "factory-failed"

### ISSUE THREAD

**Issue by DouglasCalora** [quasarframework/quasar#15395]
### What happened?

Factory failed is defined as `'factory-failed'` but emitted as `'factoryFailed`.

warning:
```
[Vue warn]: Component emitted event "factoryFailed" but it is neither declared in the emits option nor as an "onFactoryFailed" prop.
```

![image](https://user-images.githubusercontent.com/32134017/217062188-bf052bd7-8c78-44fd-8f6a-09de159d2de2.png)

![image](https://user-images.githubusercontent.com/32134017/217062280-5fbc5f2b-c440-4ce9-9d74-2bb07f7eb674.png)

### What did you expect to happen?

Not having warning.

### Reproduction URL

https://codesandbox.io/s/vibrant-jang-5876uj?file=/src/pages/Index.vue

### How to reproduce?

Make an upload and check the console

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Relevant log output

```Shell
[Vue warn]: Component emitted event "factoryFailed" but it is neither declared in the emits option nor as an "onFactoryFailed" prop.
```

**Comment by eliasassuncao** [comment]
happens to me too 😟

**Comment by gcarpi** [comment]
Up!
