### ISSUE TITLE
Quasar uses fastclick?

### ISSUE THREAD

**Issue by adwidianjaya** [quasarframework/quasar#154]
Quasar is a great work. Good choice for using Vue. Really hyped about this. However, does quasar uses fastclick? https://github.com/ftlabs/fastclick. I'm still experiencing several delay after clicking on button. Thank you.

**Comment by rstoenescu** [comment]
Hi,

Yes, Quasar uses fastclick. It depends on what your buttons do and how fast Vue 2 can render. Your delay might exist because of Vue struggling to cope with your templates.

**Comment by mariaczi** [comment]
I would suggest reopen it...
I found the issue with buttons. E.g. I have FAB button on card. It is always present issue that it is not getting hover state immediately when mouse is on..

**Comment by rstoenescu** [comment]
Fastclick has not nothing to do with desktop. It just solves delays for taps on touch capable devices.

**Comment by mariaczi** [comment]
Sorry, not familiar with that, but still there is some issues wit FAB buttons

**Comment by rstoenescu** [comment]
Would you care to elaborate please?

**Comment by mariaczi** [comment]
As described before = it's not getting hover state when mouse is over it. I mean not always, not immediately. Sometimes have to move mouse just a little bit to get hover.

**Comment by rstoenescu** [comment]
You have a video/gif or a live example or anything? I can hardly believe that. If mouse hover is not working then the basic CSS `:hover` is not working.. which is not likely these days... It's no magic code behind that mouse hover, just basic CSS :)

**Comment by mariaczi** [comment]
@rstoenescu 
[https://sendvid.com/v8gguw65](https://sendvid.com/v8gguw65)

I found that it's not getting hover state on the bottom half of that (something about overflow?)

**Comment by rstoenescu** [comment]
Ah, I see. It's got to do with card CSS rather than FAB itself. Will fix this.

**Comment by murbanowicz** [comment]
Did you fix it? ? It needs just z-index for fab button on card-media
