### ISSUE TITLE
Multiple Slider issues

### ISSUE THREAD

**Issue by weingaunity** [quasarframework/quasar#1540]
Relates to v0.15.+

See https://jsfiddle.net/_wg_/uur8yrmL/3/

I made comments with <!-- Issue within the HTML code. Please check this.

Issue 1: The List after a slider is not showed. Workaround: put the slider within a div container
Issue 2: The sliders within the list are not shown correctly, but according the documentation example it should work: http://quasar-framework.org/components/slider.html#Basic-Usage

Lg, _WG_

**Comment by rstoenescu** [comment]
Browsers do not know how to handle self-closing custom tags. So don't use them in jsFiddle or on a Quasar website that uses the UMD version. Instead, use a closing tag.

See updated example: https://jsfiddle.net/mw6s5cn2/

**Comment by weingaunity** [comment]
Thx. I used XML+XSLT and HTML a lot since the last approx. 12 years and up to now i did not recogniced this behavior. I always thought, that valid XML is valid HTML too.

**Comment by rstoenescu** [comment]
In this case you got custom elements that are not registered and only later parsed by Vue. So if the initial HTML is not recognised then it breaks. Browsers translate your example's HTML like this: self-closing tags actually containing the rest of the page, not being siblings with the rest of the page as you would expect.
