### ISSUE TITLE
Multi Environmental Variable | Quasar v2

### ISSUE THREAD

**Issue by jmriyaz84** [quasarframework/quasar#15405]
### What happened?

We developed the application by using Quasar . Our application has 3 environments Local , Dev & Prod.

Each environment has its own endpoints for Azure Authentication (Client Id , Tenant Id & Redirect Url ) & API.

We were using Quasar [QEnv ](https://www.npmjs.com/package/@quasar/quasar-app-extension-qenv)extension from last 2 years. Recently we have upgraded our application to Quasar v2.  The environment setup is working fine for local & dev but we are getting following error on production. [Quasar] boot error : ReferenceError : process is not defined
 
![image](https://user-images.githubusercontent.com/8514576/217450130-e16bb8ee-be80-4b3a-ae85-f96f2296e642.png)

QEnv recommends to use Quasar's build->env for enviroment setup. But following bug https://github.com/quasarframework/app-extension-dotenv/issues/21 says we can use dot env only for 2 environment (Dev & Prod) but we have 3 environment & in future one more environment stage also will get added.

Please help us to configure multiple environment in quasar  

### What did you expect to happen?

Quasar v2 should support Multi Environment variable support. (Local , Dev , Stage  & Prod)

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

1. Configure Quasar Application with multiple environment
2. Deploy the Minified code in production
3. It should work in production with prod env variables.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System        Windows_NT(10.0.19042) - win32/x64
NodeJs                  16.17.0

Global packages
  NPM                   8.15.0
  yarn                  1.22.19
  @quasar/cli           2.0.0
  @quasar/icongenie     Not installed
  cordova               11.0.0
```

**Comment by MilosPaunovic** [comment]
Take a look at this guide, seems like exactly what you need:
https://gist.github.com/MilosPaunovic/1da784b83466197196b4b0fd6448c0b1

**Comment by jmriyaz84** [comment]
Thanks @MilosPaunovic  for your quick response . One clarification , in your example you used only 2 environment local & production. Can we use for other environment like stage.

 "dev:local": "cross-env ENVIRONMENT=local quasar dev",
  "build:local": "cross-env ENVIRONMENT=local quasar build --debug",

  "dev:production": "cross-env ENVIRONMENT=production quasar dev",
  "build:production": "cross-env ENVIRONMENT=production quasar build",

**Comment by MilosPaunovic** [comment]
You can use as many of them as you need, just follow the same principles.

**Comment by jmriyaz84** [comment]
Thanks we will try & let you know
