### ISSUE TITLE
Does qtooltips ONLY work within Quasar components?

### ISSUE THREAD

**Issue by TingtingGu2014** [quasarframework/quasar#1541]
Is that correct?

This tooltip does not show up:

`
    
    <p class="col commentBody" style="width: 100%;" v-html="value">
        
     <q-tooltip anchor="center right" self="center left" :offset="[10, 10]">
               <strong>Tooltip</strong> on <em>right</em> (<q-icon name="keyboard_arrow_right" />)
        </q-tooltip>
    </p>
`

Thanks.

**Comment by rstoenescu** [comment]
Hi,

No, it works for any DOM element or component. The problem with your example is that you are using v-html directive which overwrites any content, including that QTooltip.
What I'd suggest is that you use a `<span v-html="value">` as child of `<p>` tag, before the tooltip:

```html
<p class="col commentBody" style="width: 100%;">
  <span v-html="value"></span>  
  <q-tooltip anchor="center right" self="center left" :offset="[10, 10]">
    <strong>Tooltip</strong> on <em>right</em> (<q-icon name="keyboard_arrow_right" />)
  </q-tooltip>
</p>
```
