### ISSUE TITLE
Typescript: using Quasar.iconSet.iconMapFn results in a type error

### ISSUE THREAD

**Issue by DavidWard98** [quasarframework/quasar#15420]
### What happened?

I am using an icon [custom mapping](https://quasar.dev/vue-components/icon#custom-mapping) using the $q object [outside of a vue file](https://quasar.dev/options/the-q-object#outside-of-a-vue-file). I get a typescript type error on `Quasar.iconSet.iconMapFn`.

Dumping the `Quasar.iconSet` object to the console you can see that `iconMapFn` is an accessible property and the code works as expected.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/45475170/218152954-ad917099-ce47-4a4e-8102-af1ae1b9bdd6.png">

### What did you expect to happen?

No type error

### Reproduction URL

https://stackblitz.com/edit/quasarframework-3kqszv?file=example.ts

### How to reproduce?

1. run: `npm run typecheck`

<img width="795" alt="image" src="https://user-images.githubusercontent.com/45475170/218154652-8594145c-e372-4147-86e3-35f7f10d75b0.png">

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.14.6
