### ISSUE TITLE
extras: Material Symbols are missing autoplay icon (maybe some others)

### ISSUE THREAD

**Issue by nikola-jokic** [quasarframework/quasar#15429]
### What happened?

Autoplay icon is shown as a text. Other material symbols are loaded well, but the autoplay icon is missing.

### What did you expect to happen?

I would expect to show the icon correctly

### Reproduction URL

https://jsfiddle.net/jokicnikola07/2dctu67m/3/#&togetherjs=rjmbk0wHNk

### How to reproduce?

1. In main.js include import `"@quasar/extras/material-symbols-outlined/material-symbols-outlined.css";`
2. Try using some ison: `<q-icon name="sym_o_thumb_up"></q-icon>` (this works)
3. Try using the autoplay icon: https://fonts.google.com/icons?icon.query=autoplay
4. See it just shows the text

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar Extras (@quasar/extras)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System        Linux(6.1.6-060106-generic) - linux/x64
NodeJs                  18.13.0

Global packages    
  NPM                   8.19.3
  yarn                  1.22.19
  @quasar/cli           2.0.0
  @quasar/icongenie     Not installed
  cordova               Not installed
```

**Comment by hawkeye64** [comment]
Fixed in @quasar/extras v1.15.11
