### ISSUE TITLE
why the compilation of quasar with webpack is too slow ?

### ISSUE THREAD

**Issue by ajayashuba** [quasarframework/quasar#1542]
Do you think there is any need to integrate any plugin or anything is missing to make faster hot reload ?

**Comment by rstoenescu** [comment]
Hi,

The webpack config is actually on steroids. But it depends on your app code. How many external packages are you loading? How are you structuring your app?
What you could do to speed up your app development is to remove the source maps from it. That takes the most time to compile.

Please use the forum for questions. Thanks.
