### ISSUE TITLE
q-select and selecting option after filtering

### ISSUE THREAD

**Issue by drbergeron** [quasarframework/quasar#15428]
### Description

Hi, thanks for taking the time to read this.

There is currently a great guide and great code for selecting options after a filtering operation completes with the following example:
```
filterFnAutoselect (val, update, abort) {
  // call abort() at any time if you can't retrieve data somehow

  setTimeout(() => {
    update(
      () => {
        if (val === '') {
          options.value = stringOptions
        }
        else {
          const needle = val.toLowerCase()
          options.value = stringOptions.filter(v => v.toLowerCase().indexOf(needle) > -1)
        }
      },

      // "ref" is the Vue reference to the QSelect
      ref => {
        if (val !== '' && ref.options.length > 0 && ref.getOptionIndex() === -1) {
          ref.moveOptionSelection(1, true) // focus the first selectable option and do not update the input-value
          ref.toggleOption(ref.options[ ref.optionIndex ], true) // toggle the focused option
        }
      }
    )
  }, 300)
}
```

Can we get some comments in here or as a little lightbulb section below on what the quasar devs' best practices/recommendations are around using setTimeout in both wrapping the update function, or even inside of the update and ref functions?

Context behind this is that I've used the `Update( () => {...}, (ref:Qselect) => {... });` format now and this works great for synchronous filtering of data loaded into the component on mounting , but falls down when used asynchronously to retrieve list options like this:  `Update( async () => { await ...}, (ref:Qselect) => {... });` as the ref is called before any awaited code is finished. 

my personal solution to this was to have the (ref:QSelect) function have a setTimeout inside of it so there'd be a delay, but i'm looking for something more elegant so that if the update function is async the ref:QSelect function is called upon completion.

### Documentation Section URL

https://quasar.dev/vue-components/select#example--selecting-option-after-filtering

### Flavour

None

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
You should always have your async functions outside update, and when you have the data call update.
Update also sets the loading indicator status.
