### ISSUE TITLE
quasar build not working with Vite

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#15437]
### What happened?

Scaffolded a new quasar project using webpack, then built a SPA with the example provided with the scaffold.
Runs fine.
Scaffolded a new project using Vite, but when this is built, I get errors like this:
index.d5310db4.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
index.2b87af5a.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)

This is a serious problem for me, as I converted a large project to Vite so I could use Pinia instead of Vuex, but I cannot get my project to build now. Used to work fine when I used webpack.

### What did you expect to happen?

Expected quasar build to product a working app when using Vite as it does with webpack.

### Reproduction URL

https://codepen.io/crawfordw/pen/poOzVma

### How to reproduce?

scaffold a new quasar app:
>npm init quasar
choose 'App with Quasar CLI, Quasar V2 and Javascript
choose Quasar App CLI with Vite
When the project has been scaffolded, cd to the project folder and
>quasar build
Move the contents of dist/spa folder to local server htdocs folder and launch in a browser.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Quasar info output

```Shell
Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.11 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.34.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
index.d5310db4.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
index.2b87af5a.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
reload.js:22 WebSocket connection to 'ws://127.0.0.1:5500//ws' failed: 
init @ reload.js:22
index.2b87af5a.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
```

### Additional context

Scaffolding with webpack works fine, but with Vite, it will not build a working app.

**Comment by CrawfordW** [comment]
Note: the codepen is just a copy of the example code that is included in the initial quasar app. Included because need something in order to post an issue :)

Update:
Seems quasar cli now allows pinia with webpack, so I re-scaffolded my app with webpack, and everything seems ok.
But if the team is recommending vite over webpack, this issue will need to be addressed.

**Comment by yusufkandemir** [comment]
Works fine, couldn't reproduce.

```shell
$ pnpm create quasar

...
✔ What would you like to build? › App with Quasar CLI, let's go!
✔ Project folder: … quasar-15437
✔ Pick Quasar version: › Quasar v2 (Vue 3 | latest and greatest)
✔ Pick script type: › Javascript
✔ Pick Quasar App CLI variant: › Quasar App CLI with Vite
✔ Package name: … quasar-15437
✔ Project product name: (must start with letter if building mobile apps) … Quasar App
✔ Project description: … A Quasar Project
✔ Author: … Yusuf Kandemir <yusuf.kandemir@outlook.com.tr>
✔ Pick your CSS preprocessor: › Sass with SCSS syntax
✔ Check the features needed for your project: › ESLint
✔ Pick an ESLint preset: › Prettier
...

$ cd quasar-15437

$ pnpm quasar build
...

$ npx @quasar/cli serve dist/spa
```

Instead of "bypassing" the reproduction URL, you could've created a GitHub repo, put the project in it, and shared it.

Most probably there is something wrong with your webserver configuration. `quasar serve dist/spa`(_or any properly configured webserver_) works fine serving it.

**Comment by luoyunpeng** [comment]
i met the issue too,  and my dev environment as follow:
>node： v22.11.0
> npm ： 10.9.0
>pnpm ： 9.14.2

just follow the official document "https://quasar.dev/start/quick-start" to scaffold a new quasar project using wite, and run 'quasar build', then copy the build package to the httpd directory,
