### ISSUE TITLE
[QDate] Resets time when changing date

### ISSUE THREAD

**Issue by Tofandel** [quasarframework/quasar#15442]
### What happened?

Changing the day in the QDate component resets the QTime of when the QDate component was first mounted instead of keeping the selected time

### What did you expect to happen?

The time should not change when selecting a day

### Reproduction URL

https://codepen.io/Tofandel/pen/zYJYzYx?editors=101
On the demo: https://quasar.dev/vue-components/date#example--qdate-and-qtime-on-same-model

### How to reproduce?

1. Change the time
2. Change the day
3. The time has been reset to 9:02

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Additional information

The issue is located within the `updateViewModel` method which doesn't update the minutes and hours of the original view model, which is only created on mounted
https://github.com/quasarframework/quasar/blob/a9ffb06d5cee0e8b3a7e9b25e640c3fc307b40ff/ui/src/components/date/QDate.js#L700-L708
https://github.com/quasarframework/quasar/blob/a9ffb06d5cee0e8b3a7e9b25e640c3fc307b40ff/ui/src/components/date/QDate.js#L903-L936

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.7 and v1.22.6
