### ISSUE TITLE
q-input dont accept point to number decimal (pt-BR) at Android

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#1545]
Hi.

At Chorme is ok (keyboard have a comma),
but at Android dont have.

How i can input decimal numbers at a q-input on Android, like 12,50?

When a type a point (Chrome and Android), the q-input blank the field.

And if a leave field blank generete a warning NaN.

Can you implement this at 0.15?

Tanks.

**Comment by rstoenescu** [comment]
Hi,

This scenario is covered by v0.15 already. There's a new prop called `numeric-keyboard-toggle` which adds a icon that when clicked/tapped it switches the keyboard to alphanumeric in order to allow the decimal point (among other things).

**Comment by dhalsted** [comment]
Hi,

I can't seem to get the numeric-keyboard-toggle to work (still refuses to accept a period as a decimal point).  Perhaps you could post a working example in the docs.

**Comment by rstoenescu** [comment]
@pdanpdan Care to give him an example pls?

**Comment by dhalsted** [comment]
Um, I did this:

<q-input v-model="reportLine.sales_total" float-label='Sales' @input="calcTotal" type="number" :decimals="2" align="right" numeric-keyboard-toggle/>

and tested on an iPhone.  I saw the keyboard toggle icon but still could not use a period as a decimal point.  In any case, a new icon is probably not an acceptable solution for my users; it'll probably confuse them.

**Comment by pdanpdan** [comment]
@dhalsted Can you check this one: https://codepen.io/anon/pen/mKZJoV
The keyboard should be the numeric one by default, but if it's missing `.` you can only press the toggle to switch to full keyboard.

**Comment by dhalsted** [comment]
That example works, so it's something else.  Thanks!

**Comment by caitcif** [comment]
> @dhalsted Can you check this one: https://codepen.io/anon/pen/mKZJoV
> The keyboard should be the numeric one by default, but if it's missing `.` you can only press the toggle to switch to full keyboard.

Hi there, I am using Quasar 1.1.4 and I cannot make this simple example work to justify right and just have 2 decimals. Has it all changed since? Thanks

**Comment by rstoenescu** [comment]
@caitcif https://quasar.dev/vue-components/input#Example--Filling-the-mask-in-reverse

**Comment by caitcif** [comment]
> @caitcif https://quasar.dev/vue-components/input#Example--Filling-the-mask-in-reverse

@rstoenescu I am not sure what you are pointing me too. If I take the codepen and try it in the latest version of quasar, these 2 statements seem to do nothing:
      :decimals="2"
      align="right"

I can enter as many decimals as I want and the text is still aligned to the left.
I used the basic quasar test example and in Index.vue have:

<template>
  <div class="q-ma-md q-pa-sm shadow-2">
    <q-input
      v-model="value"
      float-label="Sales"
      type="text"
      :decimals="2"
      align="right"
      numeric-keyboard-toggle
      @input="notify"
    />
  </div>
</template>

<style></style>

<script>
export default {
  name: "PageIndex",
  data: function() {
    return {
      version: this.$q.version,
      value: null
    };
  },
  methods: {
    notify: function(note) {
      this.$q.notify(JSON.stringify(note));
    }
  }
};
</script>

**Comment by rstoenescu** [comment]
I'm pointing you to this:

<img width="853" alt="mask" src="https://user-images.githubusercontent.com/4665641/66259380-062ba380-e7b9-11e9-9b1c-5eb24c943aec.png">

**Comment by mclate** [comment]
For anyone stumbled upon this issue, the solution is not quite related to Quasar. It's native input validation that prevents float values to be entered for `input type="number"`. To fix that, one has to add `step="any"` (or any numeric value of a minimal change step). Here are docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step

**Comment by loiccc** [comment]
thanks @mclate ! it's working !
