### ISSUE TITLE
Fix cursor positioning when pasting text in a field with mask

### ISSUE THREAD

**Issue by tjunussov** [quasarframework/quasar#15453]
### What happened?

Copy pasting text in input field, cursor position doesn't respect mask formatting,

### What did you expect to happen?

Cursor must be positioned at the end

### Reproduction URL

https://codepen.io/tjunussov/pen/abaOwVb?editors=1010

### How to reproduce?

1) Go to codepen
2) Copy and paste id( 12 number ) and paste it in text field
3) You notice what cursor will be wrong positioned ( not in the end )

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.11.8 and v1.22.7
