### ISSUE TITLE
Cannot install `@quasar/app-vite` in node v19

### ISSUE THREAD

**Issue by ydfzgyj** [quasarframework/quasar#15463]
### What happened?

In `package.json` of `@quasar/app-vite`, expected node version is `^24 || ^22 || ^20 || ^18 || ^16 || ^14.19`, but current node version is v19, so after I upgrade node to v19, I can't install dependencies with this error:
```bash
@quasar/app-vite@1.2.0: The engine "node" is incompatible with this module. Expected version "^24 || ^22 || ^20 || ^18 || ^16 || ^14.19". Got "19.6.0"
```

### What did you expect to happen?

Support all node versions in life circle

### Reproduction URL

no url

### How to reproduce?

npm install @quasar/app-vite

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 19.6.0

Global packages
  NPM - 9.4.0
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.0 -- Quasar Framework App CLI with Vite
```

**Comment by MilosPaunovic** [comment]
https://github.com/quasarframework/quasar/discussions/15454#discussioncomment-5008708

**Comment by ydfzgyj** [comment]
@MilosPaunovic but `quasar`, `@quasar/app-webpack`, `@quasar/cli`, even `@quasar/vite-plugin` all specify the node version by `>=XX`, only `@quasar/app-vite` use a different strategy, and I really haven't seen any words in quasar doc about we should use LTS node version

**Comment by MilosPaunovic** [comment]
https://quasar.dev/icongenie/installation#:~:text=on%20your%20machine.-,WARNING,-Do%20not%20use

But yeah, the warning should be on a more prominent place.
