### ISSUE TITLE
Vite does not hot reloads pinia store

### ISSUE THREAD

**Issue by Serhioromano** [quasarframework/quasar#15482]
### What happened?

When I make changed in pinia store, I need to restart quasar app in order to see changes

### What did you expect to happen?

After I change pinia store code it immediately acts acordingly

### Reproduction URL

https://stackblitz.com/edit/quasarframework-d2rq4o

### How to reproduce?

- Open `stores/mainStore.js` in line 7 change console log to a different number. 
- On the main Layout there is a code that call this method. On main page click TEST button and in console log you will see old number unless you restart quasar app.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Microsoft Edge

### Quasar info output

```Shell
Operating System - Linux(5.10.102.1-microsoft-standard-WSL2) - linux/x64
NodeJs - 16.19.0

Global packages
  NPM - 9.4.2
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - You have been opted out of telemetry. To change this, run: cordova telemetry on.
11.0.0

Important local packages
  quasar - 2.11.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.11 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.30 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.34.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - SergeyHC
  eth0 - 172.30.206.124
```

### Additional context

Video with more details.
https://www.youtube.com/watch?v=fwm5oF3Tq5k

**Comment by popadicbranislav** [comment]
Hi @Serhioromano,

For pinia to be able to hot reload, you need to do following changes in your code:
```ts
import { defineStore, acceptHMRUpdate } from 'pinia';

export const useCounterStore = defineStore('counter', () => {
// ...
})

if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useCounterStore, import.meta.hot));
}
```

You can read more about it [here](https://pinia.vuejs.org/cookbook/hot-module-replacement.html)

Anyway, I think this is not a quasar issue.

**Comment by Serhioromano** [comment]
> Hi @Serhioromano,
> 
> For pinia to be able to hot reload, you need to do following changes in your code:
> 
> ```ts
> import { defineStore, acceptHMRUpdate } from 'pinia';
> 
> export const useCounterStore = defineStore('counter', () => {
> // ...
> })
> 
> if (import.meta.hot) {
>   import.meta.hot.accept(acceptHMRUpdate(useCounterStore, import.meta.hot));
> }
> ```
> 
> You can read more about it [here](https://pinia.vuejs.org/cookbook/hot-module-replacement.html)
> 
> Anyway, I think this is not a quasar issue.

I think it is different. Read this

> Pinia supports Hot Module replacement so you can edit your stores and interact with them directly in your app without reloading the page, allowing you to keep the existing state, add, or even remove state, actions, and getters. 

This says that it is the way to inject new store without reload of page. When I use `quasar dev` and it rebuilds app it reloads page in browser. So now it does not work even with browser reload. But I'll try to add this and see if it works.

**Comment by Serhioromano** [comment]
Tested it on URL with playground. Now when I save store it say 

```
[vite] hot updated: /src/stores/mainStore.js
```

But still console.log shows old string.

**Comment by popadicbranislav** [comment]
Hi @Serhioromano,

Please check this [playground](https://stackblitz.com/edit/quasarframework-lucwsi?file=src/stores/mainStore.js). It is fork of your. I updated the store so it hot reloads, and added some more code for demonstration. Feel free to play with it and let me know if you  have some more questions.

**Comment by Serhioromano** [comment]
It works now. Ok, thank you.
