### ISSUE TITLE
Page transition

### ISSUE THREAD

**Issue by adwidianjaya** [quasarframework/quasar#155]
Is vue-transition (http://quasar-framework.org/components/vue-transitions.html) applicable for page transition too? It's very nice if you find that vue-transition supports both HTML element and page with built-in transitions (e.g. slider, fade). Although it's possible to define the transition by ourself. Thank you.

**Comment by rstoenescu** [comment]
Hi,

Yes, you can use `<quasar-transition>` on your `<router-view>`s (inside layouts too if you have any). It currently supports only one type of transition (slide) and next Quasar version will add the `appear` property. Quasar transition wraps `<transition>` Vue component so use it on only one descendent as child (not multiple nodes) as that would require the use of `<group-transition>`.

This component will get enhanced in later Quasar versions. It currently just isn't a high priority, so stay tuned :)

Cheers.

**Comment by rstoenescu** [comment]
@rlam3 Check http://quasar-framework.org/components/transition.html & http://quasar-framework.org/quasar-play/android/index.html#/showcase/animation/transition and use `<transition>` to wrap your page or `<router-view>`.
