### ISSUE TITLE
#top-left slot results in class "q-table-control" instead of "q-table__control"

### ISSUE THREAD

**Issue by J43fura** [quasarframework/quasar#15509]
### What happened?

#top-left slot results in class "q-table-control" instead of "q-table__control" like #top-right.
![Screenshot from 2023-03-01 16-07-16](https://user-images.githubusercontent.com/73950268/222180287-2beeec7c-ae43-4490-89ac-644ebd2a913c.png)
![Screenshot from 2023-03-01 16-07-24](https://user-images.githubusercontent.com/73950268/222180141-e12604a8-37d8-410d-b2d3-3c84539e5819.png)

### What did you expect to happen?

![Screenshot from 2023-03-01 16-07-51](https://user-images.githubusercontent.com/73950268/222180070-68d146d7-d1cf-4edb-a28f-8647dfb3e9d3.png)

### Reproduction URL

https://codepen.io/J43fura/pen/gOdmrEW

### How to reproduce?

1. Go to the provided reproduction link.
2. Open Web development tools.
3. Inspect table top elements like in the picture.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar), Style & Identity (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.8

**Comment by rstoenescu** [comment]
And v1.22.7
