### ISSUE TITLE
Hot module Replacement freeze after compiling. Quasar 0.15

### ISSUE THREAD

**Issue by cklinx** [quasarframework/quasar#1550]
### Software version

Quasar: 0.15 Started kit
OS: Linux - Ubuntu
Node: v9.4.0
NPM: 5.6.0
Browsers: Firefox 57.0.4
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Everytime i compile my code for cordova "quasar build -m cordova -T android" my browser freezes in the white page. It doesnt load the correct page, even if i refresh the browser page. To solve the problem i must stop the dev process and give the command "sudo quasar dev" again so the hot module replacement starts to works correctly.

### What were you expecting?
The browser page continue to show the correct browser page, not white page.

### What steps did you take, to get the error?
Just give  "quasar build -m cordova -T android" command to stop the hot module works.

**Comment by rstoenescu** [comment]
While developing: `quasar dev -m cordova -T android`
Making the production build -- has nothing to do with the browser -- : `quasar build -m cordova -T android`

Basically what you are saying is that you give a command to build the production distributables and you don't get HMR. "dev" and "build" have different purposes.

What you actually want is "quasar dev -m cordova -T android".

**Comment by cklinx** [comment]
Actually i have same problem with "quasar dev -m cordova -T android". Browser gives me white page.

**Comment by rstoenescu** [comment]
Use remote debugging to find out what JS errors you have. http://quasar-framework.org/guide/cordova-wrapper.html#Remote-Debugging

**Comment by cklinx** [comment]
I work with my browser with "sudo quasar dev" and i do everything over there. After i like my layout i want try it on my phone so i execute "quasar build -m cordova -T android"; the goal is try it on phonegap app. 
Phonegap works fine but my browser stop working so i cant continue to use it (on quasar 0.14.8 it works).

I think i dont need use remote-Debugging maybe i'm doing something wrong with the new release.

**Comment by rstoenescu** [comment]
I was just talking to someone. I hope you are not killing the "quasar dev -m cordova" process then still run the dev app installed. Because that only works while "quasar dev -m cordova" is running.

**Comment by cklinx** [comment]
Of course i'm not closing the 'quasar dev' terminal. I tried with a fresh installation also: Same problem.

**Comment by rstoenescu** [comment]
It's unclear what you want but I am more and more sure that you got a misunderstanding here.

While you develop your app for Cordova, a dev app gets installed on your phone. If no phone is connected, the emulator is used. You are mentioning a browser. What browser? Are you referring to your desktop browser? If yes, then this is not the way to go. You either develop in your desktop browser or on an emulator/phone. I mentioned the remote debugging. Use it.

**Comment by cklinx** [comment]
Hope this can help you to understand [example](https://imgur.com/a/H1x7t).

**Comment by rstoenescu** [comment]
Oh. Wow. If this was it, then yes. You can't have multiple instance of Quasar CLI running under the same project folder. In this case you are running both dev and build. Avoid running multiple CLI commands simultaneously.

**Comment by cklinx** [comment]
Is there a workaround to use it? It is really useful for me.

Thanks

**Comment by rstoenescu** [comment]
Currently no. Probably in future CLI versions.

**Comment by cklinx** [comment]
Ok. Really thanks for your time.
