### ISSUE TITLE
[Bug]DataTable columns <th> height bug when columns label using chinese.

### ISSUE THREAD

**Issue by ChandlerBent** [quasarframework/quasar#1552]
![image](https://user-images.githubusercontent.com/22490739/36016691-33a4606c-0daf-11e8-88f0-35894e426488.png)

**Comment by lyb12358** [comment]
v0.15 fix it  as I know

**Comment by ChandlerBent** [comment]
Ok, thank you for answer.

**Comment by psychonetic** [comment]
@lyb12358 I had the same bug, which was caused by loading data from an api. It only worked, if I had at least one row, otherwise the border was ugly. (I know that quasar framework v15 ships with an own serverside component.)

**Comment by rstoenescu** [comment]
@psychonetic Yes.
