### ISSUE TITLE
q-input mask # can't type "0" as first char

### ISSUE THREAD

**Issue by neitsr** [quasarframework/quasar#15526]
### What happened?

when trying to type a "0" as the first char in a q-input with a digit mask nothing happens

### What did you expect to happen?

a "0" to be typed in as the first char in a q-input with a digit mask

### Reproduction URL

https://codepen.io/neitsr/pen/NWLvGav

### How to reproduce?

self explanatory

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
You use 0 as the fill mask
Use another character (i think you can find even something looking like 0 if you need it)

**Comment by neitsr** [comment]
Maybe I can find a cool emoji.. Depends how nit-picky the designer you're working with is gonna be. I still don't see why it is not a bug..

**Comment by pdanpdan** [comment]
This is how it is designed - if it cannot distinguish between the mask and the input it cannot work

**Comment by neitsr** [comment]
Roger 👷‍♂️👍🏻
