### ISSUE TITLE
Alert dismiss problem

### ISSUE THREAD

**Issue by sefarsen** [quasarframework/quasar#1553]
I cannot dismiss Alert component programmatically, when define Alert as const alert and make `alert.dismiss()` I got an error 

> Uncaught TypeError: alert.dismiss is not a function

**Comment by rstoenescu** [comment]
Please fill in the template that gets shown by default when opening a Github ticket here. It's not there for nothing. What version of Quasar are you using? Also offer the exact code that you are using. Thanks.
