### ISSUE TITLE
publicPath doesn't seem to have any effect in capacitor build and breaks the app in history mode

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#15545]
### What happened?

Setting `build.publicPath` to `/` in quasar.conf.js doesn't set  `cfg.output.publicPath` in webpack config, which then makes all asset urls relative and breaks the app in history mode.

### What did you expect to happen?

I expected all asset urls to be absolute in capacitor build. Not sure if setting the publicPath to `/` is expected requirement, it's not mentioned in the docs for capacitor mode. The app uses absolute urls when built in SPA mode.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-wvqqdh?file=quasar.config.js

### How to reproduce?

1. go to the repro
2. run `quasar build -m capacitor -T android`

alternatively
1. scaffold new quasar project
2. add set build.publicPath to `/` in quasar conf
3. add this code to the build prop
```javascript
       extendWebpack(cfg) {
        if (cfg.output.publicPath !== '/') {
          throw new Error('public path should be / ');
        }
      },
```
3. run `quasar build -m capacitor -T android`

You can also remove the `throw` and look at the build output. JS and CSS urls are relative instead of absolute.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Capacitor Mode

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19044) - win32/x64
NodeJs - 16.18.1

Global packages
  NPM - 6.13.4
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - 2.5.4
  cordova - Not installed

Important local packages
  quasar - 2.11.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.7.2 -- Quasar Framework App CLI with Webpack
  @quasar/extras - Not installed
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - 4.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.21.0 -- Babel compiler core.
  webpack - 5.75.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 3.9.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 3.9.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 3.9.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-LCL64AA
  vEthernet (WSL) - 172.29.112.1
  Ethernet - 192.168.0.43

Done in 1.83s.
```

**Comment by rstoenescu** [comment]
Hi,

Due to how Capacitor (and also how Cordova) works by being encapsulated in a Webview and running "locally" (through file:// protocol on production), it makes no sense to configure any publicPath or vue router mode other than the one that Quasar CLI enforces.
