### ISSUE TITLE
chips doesn't toggle in q-dialog-select

### ISSUE THREAD

**Issue by amfine-soft-scheminel** [quasarframework/quasar#1554]
Hi

On the documentation page of the q-dialog-select : 
http://quasar-framework.org/components/dialog-select.html 

On the exemple "List with float label & toggles" (it's the orange one).

If you click on the chips cross to toggle the element you have a "TypeError: t.__toggle is not a function" and the element is not toggle.

```
TypeError: t.__toggle is not a function
Stack trace:
close@http://quasar-framework.org/quasar-play/android/js/vendor.js:6:162750
e@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6965
[2]/</</t.prototype.$emit@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:43857
click@http://quasar-framework.org/quasar-play/android/js/vendor.js:6:115170
e@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6965
ot/t._withTask@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6643
 vendor.js:11:6471
	it http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6471
	nt http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6398
	et http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6264
	[2]/</</t.prototype.$emit http://quasar-framework.org/quasar-play/android/js/vendor.js:11:43882
	click http://quasar-framework.org/quasar-play/android/js/vendor.js:6:115170
	e http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6965
	ot/t._withTask http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6643
```

**Comment by rstoenescu** [comment]
Hi. Clear cache? Works fine for me...

![dialog-select 2](https://user-images.githubusercontent.com/4665641/36043240-49d0e50e-0dd7-11e8-8785-051e416ebaed.gif)

**Comment by amfine-soft-scheminel** [comment]
You misunderstood my description (I'm not a native english spoker)
I've wrote "click on the chips cross" I meant the cross within the round circle in the image above :
![image](https://user-images.githubusercontent.com/27482865/36097967-76355b20-0ffd-11e8-81ef-542f83685fe2.png)

**Comment by amfine-soft-scheminel** [comment]
@rstoenescu Sorry for direct messaging but I can't reopen the issue.
