### ISSUE TITLE
Failed to add alias

### ISSUE THREAD

**Issue by suzhenghui-sky** [quasarframework/quasar#15577]
### What happened?

Failed to add alias

### What did you expect to happen?

I think it will work

### Reproduction URL

https://stackblitz.com/edit/quasarframework-3bqqqb?file=quasar.config.js

### How to reproduce?

Failed to add alias
![图片](https://user-images.githubusercontent.com/48371536/225816476-a701ecab-a00e-4cbb-bfd9-2ae5626456c0.png)
![图片](https://user-images.githubusercontent.com/48371536/225816426-829b1426-0815-454e-a0d3-2b871e4bc175.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), TypeScript Support, SPA Mode

**Comment by pdanpdan** [comment]
https://quasar.dev/quasar-cli-vite/handling-vite#adding-folder-aliases
