### ISSUE TITLE
QTableProps.onRequest should support async methods

### ISSUE THREAD

**Issue by mlilback** [quasarframework/quasar#15573]
### What happened?

The typescript definition for QTableProps.onRequest specifies the value should return `void`. However, the purpose is to make a network call, which requires an async method. This has no effect on actual production code, but Volar reports an incompatible type error since a method that returns `Promise<void>` is not the same as one that returns `void`.

### What did you expect to happen?

There should not be a warning about incompatible types because async event handlers should an acceptable value for onRequest.

### Reproduction URL

https://stackblitz.com/edit/vue3-vite-typescript-quasar-starter-us3vf4?file=src/components/TableExample.vue

### How to reproduce?

1. Go to the provided link
2. Download the project
3. Open the project in Visual Studio Code with Volar installed
4. Open a terminal
5. run `npm install`
6. Open `src/components/TableExample.vue` in the editor
7. See error on line 13

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

### Platforms/Browsers

Other

### Quasar info output

```Shell
Operating System        Darwin(21.6.0) - darwin/x64
NodeJs                  16.16.0

Global packages    
  NPM                   8.11.0
  yarn                  1.22.19
  @quasar/cli           2.0.0
  @quasar/icongenie     Not installed
  cordova               Not installed

Networking         
  Host                  tiger
  en0                   192.168.1.151
```

### Relevant log output

```Shell
[{
	"resource": "/Users/mlilback/Downloads/s3/src/components/TableExample.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2322",
	"severity": 8,
	"message": "Type '(props: { sortBy?: string | undefined; descending?: boolean | undefined; page?: number | undefined; rowsPerPage?: number | undefined; rowsNumber?: number | undefined; }) => Promise<void>' is not assignable to type '(requestProp: { pagination: { sortBy: string; descending: boolean; page: number; rowsPerPage: number; }; filter: (rows: any[], terms: any, cols?: any[] | undefined, getCellValue?: ((col: any, row: any) => any) | undefined) => any[]; getCellValue: (col: any, row: any) => any; }) => void'.\n  Types of parameters 'props' and 'requestProp' are incompatible.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 8,
	"endLineNumber": 13,
	"endColumn": 15
}]
```

### Additional context

Browser doesn't matter, problem is with typescript definition and error in IDE using Volar.

Log output is the warning copied from the the Visual Code Problems tab.

**Comment by pdanpdan** [comment]
Not about solving the typescript problem, but shouldn't line 60 start with `await`?
What I mean is that if you don't await something there there is no point in making the function async

**Comment by yusufkandemir** [comment]
The error is unrelated to the return type, callback being async, etc. It's happening because the manual types you are constructing are incorrect. Due to the wrong types, the code is also incorrect. It should be `props.pagination.page` not `props.page`. Here is the correct way:
```ts
import { QTableProps } from 'quasar';

const onRequest: QTableProps['onRequest'] = (props) => {
  // props: {
  //   pagination: {
  //     sortBy: string;
  //     descending: boolean;
  //     page: number;
  //     rowsPerPage: number;
  //   };
  //   filter?: any;
  //   getCellValue: (col: any, row: any) => any;
  // }
  // ...
};
```

Also incorporating @pdanpdan's advice, and improving all type-related stuff, here is the final code:

```ts
import { QTable, QTableProps, QTableColumn } from 'quasar';
import { ref, Ref, onMounted } from 'vue';

type BeerFormat = {
  id: number;
  name: string;
  abv: number;
  tagline: string;
};

const columns: QTableColumn<BeerFormat>[] = [
  { name: 'name', align: 'left', label: 'Name', field: 'name', sortable: true },
  { name: 'abv', label: 'AbV', field: 'abv', sortable: true },
  { name: 'tagline', label: 'Tag Line', field: 'tagline', sortable: true },
];

const tableRef = ref() as Ref<QTable>;
const rows = ref<BeerFormat[]>([]);
const filter = ref('');
const loading = ref(false);
const pagination = ref<QTableProps['pagination']>({
  sortBy: 'desc',
  descending: false,
  page: 1,
  rowsPerPage: 3,
  rowsNumber: 10,
});

const onRequest: QTableProps['onRequest'] = async ({ pagination }) => {
  loading.value = true;

  const response = await fetch(
    `https://api.punkapi.com/v2/beers?page=${pagination.page}&per_page=${pagination.rowsPerPage}`,
  );
  const data = (await response.json()) as BeerFormat[];

  rows.value.splice(0, rows.value.length, ...data);

  // TODO: Do NOT forget to update the pagination as stated in the documentation
  // pagination.value = { ...pagination.value, /* updated pagination values here */ }

  loading.value = false;
};

onMounted(() => {
  // get initial data from server (1st page)
  tableRef.value.requestServerInteraction();
});
```

Here are some useful resources:
- Pinned messages in [`#v2-typescript`](https://discord.com/channels/415874313728688138/807654245640962059) channel on [our Discord server](https://chat.quasar.dev).
- My talk on Quasar Conf 2022: https://youtu.be/CkHM8VLxuus?t=2849
