### ISSUE TITLE
QTable - Watch page index range

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#1557]
### Software version

Quasar:0.15.0-beta.13
OS:Windows & Linux
Node:8.9.3
NPM:5.5.1
Browsers:Chrome & Firefox
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
To give the user a more agreable visit, it is not uncommon to save its navigation state settings like (`table page index`, `table row per page`, etc ...).

1. If when a user (_call it Bob_) was browsing a QTable, this one had `3 pages` and the user was at `page 2`. Now he close its browser.
2. Later, another user (_call it Rob_) is removing a couple of row from the the same source and how the QTable only contains 3 rows that fit on a `single page`.
3. When the user Bob will browse the same table, we will restore its pagination (_page index and row per page settings_) and will set the current page index to `3`.  But this one not exists.

The behavior of the QTable is to hide the pagination control and show a `No matching records found`.  So, without navigation, the user can no longer use the QTable.

### What were you expecting?
If the index overflow
1. Maybe validate the `pagination` page index range with a vue-js `watch` ?
2. Do not hide the pagination control of the QTable and go automatically to the last page.
3. This could be handled or validated in the application scope instead of quasar-framework, but I think it make more sens to handle it into the QTable.

### What steps did you take, to get the error?
If it's unclear, I can produce a jsfiddle, let me know.

**Comment by purell** [comment]
Fixed in https://github.com/quasarframework/quasar/pull/1564

**Comment by purell** [comment]
I made an example https://jsfiddle.net/gs9b2hs6/3/

Clicking on the top button will set an **out of range** pagination index. You will noticed that table is loosing its pagination controls too.

**Comment by rstoenescu** [comment]
Fix available in v0.15.2. Releasing later today.
