### ISSUE TITLE
Focus color remains with q-tab on mobile

### ISSUE THREAD

**Issue by oxosi** [quasarframework/quasar#15595]
### What happened?

Since the focus does not shift on mobile devices, the focus color remains forever and an unfocusing operation is required to display the correct background color with q-focus-helper.

### What did you expect to happen?

I want it to go out of focus immediately on mobile and show the correct background color

### Reproduction URL

https://quasar.dev/vue-components/tabs#individual-colors

### How to reproduce?

1. Open URL.
2. Open Chrome develover window with F12.
3. Switch Mobile Emulation with Ctrl+Shift+M.
4. Tap 'Individual Color' or 'Ripple' sample.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
you must reload page after changing the emulation in desktop browser
