### ISSUE TITLE
Live templates for Webstorm/PHPStorm

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#156]
Hello,
I found that this is your intended place for submitting ideas.

IntelliJ IDEs are really trending this time as they are really good tools for webdev.

I would suggest that this would be crazy useful and would be great advantage of Quasar to come with Live Templates for Vue components and CSS components as well. 

It would speed up the work so much!

**Comment by rstoenescu** [comment]
@murbanowicz can you elaborate a little on what exactly would you want Quasar to have? What are these templates? Should they be part of the default app template? Or is this something separate? Is this something we still need? Haven't used IntelliJ. Thx.

**Comment by rstoenescu** [comment]
Closing this for now as it is not vital. Would also take a huge amount of time and maintenance. If anyone wants to take a shot at it let me know. Thanks!

**Comment by insign** [comment]
I'll start to make this. Since as I know it can't be by project, only per IDE, I will start on my own account. We talk in a near future!

**Comment by panstromek** [comment]
[ide-helper](https://github.com/panstromek/quasar-ide-helper) can also generate Live Templates now 😉 They are not perfect, but it's a good start and I'm looking forward to make them better in the future.

@insign Did you manage to get somewhere with your effort? We can develop on that if you want 😉

**Comment by insign** [comment]
Hi @panstromek sure we can. Let me take a look at the ide-helper, maybe we can just improve making PR.  :)

**Comment by insign** [comment]
I'll try to research on how create auto complete for icons.

**Comment by panstromek** [comment]
@insign with ide helper, it could be something like - pull all possible icons (their names are somewhere in the source as bunch of CSS classes) and put them on jsdoc comments like ` * @param {('check', 'clear', 'thumb_up', ...)} icon`. JSDoc can do enums like this, but I am afraid IDEA can't autocomplete the very well on HTML attribute.

All that said - maybe this can done at least in Live Template with expressions (You can hint what should be filled like - current date, username, jsExpression etc.)...

**Comment by insign** [comment]
Hi @panstromek as I promised I found how to autocomplete icons, and create a node cli.

https://github.com/insign/universal-ide-helper

Please, copy the logic to your project.

Maybe I will slowdown the dev on this project, but the idea is extend to more frameworks besides icons.
