### ISSUE TITLE
q-tabs is missing dark style/class

### ISSUE THREAD

**Issue by ViToni** [quasarframework/quasar#15604]
### What happened?

It's not directly possible to distinguish q-tabs being in regular or dark mode as they do not carry `--dark` when in dark mode.
Trying to style the q-tabs for dark mode is only indirectyl possible.
However I was able to use a workaround:

Instead of
```
.q-tabs {
    background: red;
}
.q-tabs--dark {
    background: blue;
}
```

one can use indirection:

```
.body--light {
    --q-tabs: red;
}
.body--dark {
    --q-tabs: blue;
}
.q-tabs {
    background: var(--q-tabs);
    color: white;
}
```

### What did you expect to happen?

I'd expect
```
.q-tabs {
    background: red;
}
.q-tabs--dark {
    background: blue;
}
```
to work out of the box.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-2nn7ea?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Go to the production URL
2. use dark mode toggle
3. When in dark mode the q-tabs should be green but are blue since 
```
.q-tabs--dark {
    background: green;
}
```
won't override the `.q-tabs` definition.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System - Linux(5.0 (Macintosh)) - linux/x64
NodeJs - 16.14.2

Global packages
  NPM - 7.17.0
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.9.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.40 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.24.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - quasarframework2nn7ea-kzhf-h3vu1y3b
  en0 - 192.168.1.104
```

**Comment by rstoenescu** [comment]
Hi.

The QTabs are highly configurable through props. So please specify them and base your values on whether dark mode is enabled or not.

**Comment by ViToni** [comment]
Hi @rstoenescu.
Please apoligize if me asking but I just started using Vue/Quasar and would like to understand the reasoning behind design choices.
Is there specific reason for q-tabs NOT to have a `dark` property set in case of dark mode?
Or more generically why is it for some components better to have a `dark` property set and for others it's better to use something along the line:
```
$q.dark.isActive ? ... : ... ;
```
(if that's even what you meant, not sure I got it right)
