### ISSUE TITLE
bug, V2.11.8， quasar d => err

### ISSUE THREAD

**Issue by gowy222** [quasarframework/quasar#15608]
### What happened?

pnpm + quasar upgrade -i

then quasar d

`Error: undefined

  - import-transformation.js:6 module.exports
    [oms]/[quasar@2.11.8]/[quasar]/dist/transforms/import-transformation.js:6:11

  - loader.vue.auto-import-quasar.js:20
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:20:42

  - Array.map

  - loader.vue.auto-import-quasar.js:20 transform
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:20:6

  - loader.vue.auto-import-quasar.js:50 extract
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:50:25

  - loader.vue.auto-import-quasar.js:94 Object.module.exports
  - import-transformation.js:6 module.exports
    [oms]/[quasar@2.11.8]/[quasar]/dist/transforms/import-transformation.js:6:11

  - loader.vue.auto-import-quasar.js:20
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:20:42

  - Array.map

  - loader.vue.auto-import-quasar.js:20 transform
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:20:6

  - loader.vue.auto-import-quasar.js:50 extract
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:50:25

  - loader.vue.auto-import-quasar.js:94 Object.module.exports
    [oms]/[@quasar+app-webpack@3.7.2_lydppierdotogu2abw3k7bipqa]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:94:20

 App •  COMPILATION FAILED  • Please check the log above for details.`

### What did you expect to happen?

nothing change in project，just upgrade.. shoulda work fine..

### Reproduction URL

no

### How to reproduce?

(pnpm)quasar upgrade -i => 2.11.8

then => quasar d

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Please try to delete `node_modules` and `pnpm-lock.yaml` and reinstall with PNPM.
This seems more like a pnpm bug rather than Quasar. A fresh project with PNPM works without error and the files indicated in your log haven't changed in quite some time.

Alternatively, please provide a stackblitz or github repo with reproduction. Or contact me directly on our [Discord](https://chat.quasar.dev).

**Comment by gowy222** [comment]
@rstoenescu sorry, i cant join Discord within net area block, but i found something..

i add console.log in node_modules\@quasar\app-webpack\lib\webpack\loader.vue.auto-import-quasar.js

`function extract (content, ctx, autoImportCase) {
  let comp = content.match(compRegex[autoImportCase])
  console.log('*****comp>>>>',comp);
  let dir = content.match(dirRegex)

  if (comp === null && dir === null) {
    return
  }

  let importStatements = ''
  let installStatements = ''

  if (comp !== null) {
    // avoid duplicates
    comp = Array.from(new Set(comp))
    console.log('init comp>>>',comp);
    // map comp names only if not pascal-case already
    if (autoImportCase !== 'pascal') {
      comp = comp.map(name => autoImportData.importName[name])
      console.log('pascal comp>>>',comp);
    }

    if (autoImportCase === 'combined') {
      // could have been transformed QIcon and q-icon too,
      // so avoid duplicates
      
      comp = Array.from(new Set(comp))
      console.log('combined comp>>>',comp);
    }

    console.log('before transform >>> comp>>>',comp);
    importStatements += transform(comp)
    installStatements += `qInstall(script, 'components', {${comp.join(',')}});`
  }`

then i got : 
`*****comp>>>> [
  'q-bar',     'q-tooltip',
  'q-tooltip', 'q-chip',
  'q-chip',    'q-chip-cy',
  'q-chip',    'q-chip',
  'q-chip',    'q-chip',
  'q-chip',    'q-chip',
  'q-chip',    'q-chip',
  'q-chip',    'q-chip',
  'q-chip-cy', 'q-chip',
  'q-bar'
]
init comp>>> [ 'q-bar', 'q-tooltip', 'q-chip', 'q-chip-cy' ]                                                                                               
pascal comp>>> [ 'QBar', 'QTooltip', 'QChip', undefined ]                                                                                                  
before transform >>> comp>>> [ 'QBar', 'QTooltip', 'QChip', undefined ]                                                                                    
*****itemArray>>>> [ 'QBar', 'QTooltip', 'QChip', undefined ]    `

so, the err happen during :
`autoImportCase !== 'pascal'` ---> comp = comp.map(name => autoImportData.importName[name])
got 'undefined' in array

**Comment by gowy222** [comment]
@rstoenescu  https://stackblitz.com/edit/node-5jzx8z?file=quasar-project/src/layouts/MainLayout.vue


to run in Terminal:
cd quasar-project
pnpm install
quasar d


check: components/test_err.vue 
sub `<template>` tag in `<template>`
There was no problem with the old version of quasar/quasar-webpack, and the online app has been running

the err occurred by 
node_modules\@quasar\app-webpack\lib\webpack\loader.vue.auto-import-quasar.js

    if (autoImportCase !== 'pascal') {
      comp = comp.map(name => autoImportData.importName[name])// got 'undefined' in comp  array
    }

**Comment by gowy222** [comment]
Confirmed: The same quasar version, quasar-vite can build, but quasar-webpack can’t

**Comment by rstoenescu** [comment]
Problem is that the new Cypress test files have different filenames and are now included in the transformation list. This in turn also catches the `q-chip-cy` (from `q-chip-cyan`). Notice the '-cy' suffix (which is erroneously part of the transform list).

Fix will be available shortly in Quasar v2.11.9

**Comment by rstoenescu** [comment]
Released v2.11.9.
And thanks for supplying that stackblitz reproduction. It was key to fast fixing the issue.

**Comment by maiolica** [comment]
Can the new regex work for tests outside the `__tests__` folder?
One can find it useful to have a component and the test on that component in the same folder.
