### ISSUE TITLE
Upgrade Android showcase

### ISSUE THREAD

**Issue by mbnoimi** [quasarframework/quasar#15609]
### What happened?

[Quasar Android showcase app](https://play.google.com/store/apps/details?id=com.quasarframework.quasarplay&hl=en&gl=US) is outdated (incomparable with 2021+ mobile phones)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Cordova Mode, Capacitor Mode

### Platforms/Browsers

Android

**Comment by pdanpdan** [comment]
That is deprecated from quasar V1, lots of years ago
