### ISSUE TITLE
Why the same piece of typescript code runs differently between Quasar CLI (with Webpack) and Quasar CLI (with Vite)?

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#15616]
### What happened?

in  App.vue file, add the following typescript code:
**abstract class A {
    visible!: boolean
}
A.prototype.visible = true
class B extends A {
}
let b = new B()
console.log('----------------------:',b.visible)**

execute the 'quasar dev' command.

the output result  between Quasar CLI (with Webpack) and Quasar CLI (with Vite) is different.

in Quasar CLI (with Webpack), the output is：
----------------------: true
but in Quasar CLI (with Vite), the output is:
----------------------: undefined

### What did you expect to happen?

the output result  between Quasar CLI (with Webpack) and Quasar CLI (with Vite) should be the same. that is, the output result is:
**----------------------: true**

### Reproduction URL

none

### How to reproduce?

in  App.vue file, add the following typescript code:
**abstract class A {
    visible!: boolean
}
A.prototype.visible = true
class B extends A {
}
let b = new B()
console.log('----------------------:',b.visible)**

execute the 'quasar dev' command.

the output result  between Quasar CLI (with Webpack) and Quasar CLI (with Vite) is different.

in Quasar CLI (with Webpack), the output is：
----------------------: true
but in Quasar CLI (with Vite), the output is:
----------------------: undefined

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), TypeScript Support

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
It's not directly related to Quasar CLI. It's a Webpack vs Vite/ESBuild difference. Please use Vite resources/support to see if it's possible to achieve what you want in Vite.
