### ISSUE TITLE
QCard click event fired when "pulling to refresh" (Chrome 64). 

### ISSUE THREAD

**Issue by MoacirSchmidt** [quasarframework/quasar#1561]
Quasar: 0.15.0-beta.13
Browsers: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/g1jx7ho1/2/

If you click over the ICON and drag the mouse cursor a little  (~50 pixels) to "pull to refresh" it fires the click event on QCard.

**Comment by rstoenescu** [comment]
Hi,

There's not much that can be done. It's not Quasar's fault either.
What happens is that when you finish up with the panning and your finger or mouse pointer is still on the card, the browser triggers the "click" event on it. No way to stop it either..
