### ISSUE TITLE
Missing an option in the quasar/VITE (mode PWA) config to add/edit the paths of the 'denylist' - Inconsistency between webpack and vite

### ISSUE THREAD

**Issue by xSavior-of-God** [quasarframework/quasar#15617]
### What happened?

**DISCLAIMER:** **_I state that I'm not sure what I'm about to say and it would be useful to have such a function that I'm about to describe, in case I apologize in advance._**

I need a option to add/modify the path of denylists for PWA mode on quasar/VITE with workboxMode 'GenerateSW'.
Currently it's only possible to do it manually(with workboxMode 'injectManifest') or via config via quasar/WEBPACK with workboxMode 'GenerateSW'.

Looking at the sourcecode and talking on discord (in italian) with Callo#3200, we found the possibile Inconsistency.

Quasar/VITE code:
https://github.com/quasarframework/quasar/blob/0d23a916d7e14fa19ef73fd4e96f74713c9491f5/app-vite/lib/modes/pwa/pwa-config.js#L79-L82

Quasar/WEBPACK code:
https://github.com/quasarframework/quasar/blob/0d23a916d7e14fa19ef73fd4e96f74713c9491f5/app-webpack/lib/webpack/pwa/index.js#L64-L66

### What did you expect to happen?

I expect to find a field where I can set the list as regex of the path/files that I want the service worker to exclude.

Something like this (**navigateFallbackDenylist**):

```js
    pwa: {
      workboxMode: 'generateSW',
      navigateFallbackDenylist: [ /service-worker\.js$/, /workbox-(.)*\.js$/, /customfile\.txt$/ ],
      injectPwaMetaTags: true,
      swFilename: 'sw.js',
      manifestFilename: 'manifest.json',
      useCredentialsForManifestTag: false
      // useFilenameHashes: true,
      // extendGenerateSWOptions (cfg) {}
      // extendInjectManifestOptions (cfg) {},
      // extendManifestJson (json) {}
      // extendPWACustomSWConf (esbuildConf) {}
    },

```

### Reproduction URL

/

### How to reproduce?

/

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

PWA Mode

### Additional context

Currently I have solved the problem by changing the 'workboxMode' to 'injectManifest' and by adding the paths (`/\.auth.*$/, /api.*$/`) on the `custom-service-worker.js` file, like this:

```js
import { setCacheNameDetails, skipWaiting, clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { CacheFirst } from "workbox-strategies";

setCacheNameDetails({ prefix: "countryorigin-wizard" });
clientsClaim();
skipWaiting();

self.addEventListener("message", event => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    console.log("in condition: ", event);
  }
});
self.__precacheManifest = [].concat(self.__WB_MANIFEST || []);
precacheAndRoute(self.__precacheManifest);

registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst()
);

registerRoute(
  new NavigationRoute(createHandlerBoundToURL("index.html"), {
    denylist: [/service-worker\.js$/, /workbox-(.)*\.js$/, /\.auth.*$/, /api.*$/]
  })
);

```

However I hope it exists or you can add a option to change the denylist also through workboxMode 'GenerateSW' as for quasar/WEBPACK.

**Comment by rstoenescu** [comment]
Hello. You have quasar.conf > pwa > extendGenerateSWOptions (). That's its purpose. To extend whatever you need. Example:

```
extendGenerateSWOptions (cfg) {
  cfg.navigateFallbackDenylist = cfg.navigateFallbackDenylist || []
  cfg.navigateFallbackDenylist.push(/* your stuff */)
}
```
