### ISSUE TITLE
Version numbers in quasar.config.js are ignored when building for both iOS and Android under Capacitor 

### ISSUE THREAD

**Issue by skmbr** [quasarframework/quasar#15626]
### What happened?

When building for ios or android using capacitor, the "version" set in the "capacitor" section of quasar.config.js is ignored.

I have to manually edit this in xcode for iOS, and for android I have to manually edit src-capacitor/android/app/build.gradle to update these.

Additionally, under cordova I could set androidVersionCode, which is not documented as an option for Capacitor and also needs to be manually edited in build.gradle

### What did you expect to happen?

For the version option documented in quasar.config.js to be used in the build process for both iOS and Android so that these values do not have to be maintained and edited in multiple places.

Essentially for the same behaviour as building with cordova.

### Reproduction URL

n/a

### How to reproduce?

1. Update "version" in the "capacitor" section of quasar.config.js
2. `quasar build -m capacitor -T android` or `quasar build -m capacitor -T ios`
3. Check `src-capacitor/android/app/build.gradle` or xcode as applicable to verify that the version has not been updated.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Capacitor Mode

### Quasar info output

```Shell
Operating System - Darwin(21.5.0) - darwin/x64
NodeJs - 18.9.0

Global packages
  NPM - 8.19.1
  yarn - 1.22.18
  @quasar/cli - 1.3.0
  @quasar/icongenie - 2.5.4
  cordova - 10.0.0 (cordova-lib@10.1.0)

Important local packages
  quasar - 2.11.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.11 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - 4.1.0 -- state management for Vue.js
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.35.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - 4.7.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 4.7.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 4.7.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 4.7.0 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  *None installed*
```

**Comment by Munaro** [comment]
Same problem here.

**Comment by rstoenescu** [comment]
Hi,

Unfortunately there is no better way than to manually edit the files. Capacitor does not have support through its config file so we can't do much -- and we'd rather not automate this process from our side because you can use any version of Capacitor and the /src-capacitor folders look very different (so this can be messed up really easy, and also it can become out of date too easy).

**Comment by paridao** [comment]
Is it possible to update the documentation here accordingly if versioning isn't supported? https://quasar.dev/quasar-cli-webpack/developing-capacitor-apps/configuring-capacitor

Pointing out a missing feature leads people to believe there's something misconfigured or buggy, and wastes a lot of time researching and debugging.
