### ISSUE TITLE
[BUG] QBtn wrong loading state 

### ISSUE THREAD

**Issue by amgadserry** [quasarframework/quasar#1562]
### Software version

Quasar: 0.14 and 0.15
OS: ubuntu
Node: N/A
NPM: N/A
Browsers: all
iOS: -
Android: -
Any other software related to your bug: no

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/ars1p6yy/1/
### What did you get as the error?
the button became in the loading state
### What were you expecting?
the button in default state following the variable it is bound it
### What steps did you take, to get the error?
change the variable the button is bound to in the click handle back to false 

## Further elaboration on the issue
I will assume that you are watching on the value property and changing a variable in the data to match it which could cause issues since changing your data at the same frame as the one the watcher was triggered in hence the emit that you did in the click event ( watchers cannot fire twice in the same frame due to design implications ) 
## proof 
this fixes the issue
https://jsfiddle.net/erye7rfz/1/
## suggestion 
listening on the property instead of copying it into a data variable and emitting change whenever you want to change the loading variable or let us handle the state even without you changing the loading state on your own

**Comment by amgadserry** [comment]
after going through the source code ... click emit passes along a 2nd argument which is a callback to set loading state back to false you can use that instead of setting the variable bound to the button back to false

**Comment by rstoenescu** [comment]
Hi,

Next v0.15 beta will remove "loader" prop and v-model support, and instead add "loading". The new one is a Boolean, it's controlled from app-space only, so this can't happen anymore. Your usage will be to use "loading" prop instead of v-model. Thanks.
