### ISSUE TITLE
TS Type error

### ISSUE THREAD

**Issue by suzhenghui-sky** [quasarframework/quasar#15638]
### What happened?

TS Type error

### What did you expect to happen?

No error

### Reproduction URL

https://stackblitz.com/edit/quasarframework-vafheq?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?
![图片](https://user-images.githubusercontent.com/48371536/228482579-e838aecc-bab2-4a3a-b061-640454a3823a.png)
![图片](https://user-images.githubusercontent.com/48371536/228482210-6d40dd23-54b0-48ff-bd60-a7235b6edc49.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
And? Fix the function
