### ISSUE TITLE
No scrolling on Firefox Mobile when using Touch Swipe Directive

### ISSUE THREAD

**Issue by alitalaghat** [quasarframework/quasar#15630]
### What happened?

No scrolling on Firefox Mobile when using Touch Swipe Directive on the parent element of the ScrollArea component. If the Directive is removed it works normally

### What did you expect to happen?

The scroll must work normally.

### Reproduction URL

https://codepen.io/alitalaghat/pen/MWqxvbp

### How to reproduce?

1. Go to Reproduction URL with Mobile Browser (Tested with Firefox 110 on Android 12)
2. Try to scroll down the scroll area.
3. See the behavior

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Android

**Comment by pdanpdan** [comment]
It is the same on chrome and it is expected
Tweak your VTouchSwipe to get the needed ballance (eg. `v-touch-swipe:5e-1.mouse="handleSwipe"`)
It would also help if you restrict the movements of swipe to the ones you use
