### ISSUE TITLE
QDate input "range" mode unsets the whole underlying model instead of setting `from` and `to` to null

### ISSUE THREAD

**Issue by arashdalir** [quasarframework/quasar#15633]
### What happened?

as the reference suggests, `Clicking on an already selected day will deselect it.` but this is done - imo - not correctly. instead of setting `to` and `from` properties to the bound model, it sets the whole model to null. this is also visible in the sample provided on the reference page: the whole model is removed from the printed output instead of its `to` and `from` being unset.

https://user-images.githubusercontent.com/2896170/228173542-e5fe53b4-c4d1-4da3-8049-48fb5cef43a3.mp4

the issue shows itself when the model is also used with other objects. for example, if the model is bound to 2 QInput fields to also allow manual input of `datetime`, which are bound to `date.from` and `date.to`, then, as soon as the `deselection` happens, there will be an error thrown because `date` is now null:

https://user-images.githubusercontent.com/2896170/228185119-2238d5ef-46a6-40b2-833b-52ae9e89ae6a.mp4

### What did you expect to happen?

I expected the `date` to still exist, but its properties to be set to null!

### Reproduction URL

https://codesandbox.io/p/sandbox/magical-cori-k63i9r?file=%2Fsrc%2Fpages%2FIndex.vue

### How to reproduce?

here is a sample to reproduce the issue. please be aware that you need to open the "browser view" in a separate window because for some reason the proxy popup doesn't work in the development env of codesandbox. you can [click here](https://k63i9r-8080.csb.app/) to directly open the sample in a new window.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by ming-tsai** [comment]
Hi,
I have the same problem, but in my case, if the QDate is inside of QInput, it throws an exception.
![image](https://github.com/quasarframework/quasar/assets/37890026/3a25679c-af85-43a3-aa9d-0879a49d7850)

**Comment by rstoenescu** [comment]
Hi,

This is by design to reduce code complexity. You can however use the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

**Comment by D-Maledicte** [comment]
Hey dunno I don't know if you found a solution but this worked for me: 
I have my :model-value like this
`<q-input dark borderless dense :model-value="`${dateRangeCreated.from == undefined? '' : dateRangeCreated.from } - ${dateRangeCreated.to == undefined? '' : dateRangeCreated}`" label="Creado" color="orange">`

And I added a watcher to my dateRangeCreated ref variable
`watch: {
    dateRangeCreated(newVal) {
      if (newVal == null) {
        this.dateRangeCreated = [] }},},`
