### ISSUE TITLE
Fontawesome Pro v6 Sharp is not working

### ISSUE THREAD

**Issue by charles-lebrun** [quasarframework/quasar#15635]
### What happened?

I tried to install fontawesome-pro v6 following that guide :
https://quasar.dev/options/installing-icon-libraries#using-fontawesome-pro

But when I try to display simple icon such as :
`<q-icon name="fa-sharp fa-regular fa-folder-gear" />
`
The icon shows class name

### What did you expect to happen?

I expect to get fontawesome v6 pro icons sharp style

### Reproduction URL

https://codesandbox.io/s/fontawesome-v6-pro-r41uce

### How to reproduce?

Just create from scratch a new Quasar project,
Then Follow https://quasar.dev/options/installing-icon-libraries#using-fontawesome-pro steps with your pro token.

Then add icon on from page:
<q-icon name="fa-sharp fa-regular fa-folder-gear" />

And see result.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar Extras (@quasar/extras)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(5.15.49-linuxkit) - linux/arm64
NodeJs - 16.19.0

Global packages
  NPM - 9.3.1
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.7.2 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - 4.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.20.12 -- Babel compiler core.
  webpack - 5.70.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qcalendar - 4.0.0-beta.16 -- A Quasar App Extension for @quasar/quasar-ui-qcalendar

Networking
  Host - 30a1a788c01c
  eth0 - 172.18.0.2
```

### Additional context

resolution should be very similar to this issue i think
https://github.com/quasarframework/quasar/issues/12834

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.11.10 and v1.22.9

**Comment by SkyWalker653** [comment]
I am using Quasar v2.14.2 and I am still experiencing the issue.

**Comment by rstoenescu** [comment]
@SkyWalker653 Hi, Please use the latest version of Quasar first. If it's still a problem, please take a look at all the docs instructions and this ticket. If it's still a problem, then please open a new ticket offering a reproduction codesandbox/repo. Thank you.
