### ISSUE TITLE
ESLint issue with local node modules (using npm link) [Quasar Vite]

### ISSUE THREAD

**Issue by ChristosTanailidis** [quasarframework/quasar#15648]
### What happened?

Building a Quasar Vite project can result to some ESLint errors when using linked node module packages.
This is the error that occurred to me.

```
[plugin:quasar:eslint] C:\Users\LC\Desktop\Projects\xxx\xxx\dist\src\main.es.js
  1:1  error  Parsing error: The keyword 'import' is reserved

✖ 1 problem (1 error, 0 warnings)
```

### What did you expect to happen?

ESLint should ignore node module files.
This occurs only on packages linked locally. Installed packages work fine and are ignored. 

Solution:
This can be ignored when adding the `../../*` entry in the .eslintignore file
```
/dist
/src-capacitor
/src-cordova
/.quasar
/node_modules
.eslintrc.js
/src-ssr
../../*
```

### Reproduction URL

https://github.com/kamnakis/v-pin-input

### How to reproduce?

1. Download and build the package https://github.com/kamnakis/v-pin-input
2. Create a link on the project `npm link`
3. Create a new Quasar project with Vite
4. Install the package using `npm install v-pin-input`
5. Now add the node module package locally with `npm linkv-pin-input`
6. Use the package somewhere in the code (eg: use on boot file)
7. Any linting errors that happen in the package's structure should be displayed when building the quasar project

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Additional context

The problem can be resolved when adding the relative path of the package (or any package) in .eslintignore file.

**Comment by fprijate** [comment]
look at  https://github.com/quasarframework/quasar/issues/15654#issue-1648411400.

Front end errors can be solved (without disable lint) by setting preserveSymlinks in quasar.config.js


```
    build: {
      .....
      extendViteConf(viteConf) {

        viteConf.resolve.preserveSymlinks = true;

      // viteVuePluginOptions: {},
      .... 
    },

```
