### ISSUE TITLE
global event bus doesn't work with v2

### ISSUE THREAD

**Issue by selmanbaskaya** [quasarframework/quasar#15644]
### What happened?

import { EventBus } from 'quasar'

const bus = new EventBus()

bus.on('some-event', (arg1, arg2, arg3) => {
 // do some work
})

bus.emit('some-event', 'arg1 value', 'arg2 value', 'arg3 value')

**The code above is a documentation example and the function that listens for an event is not triggered when it is emitted.**

### What did you expect to happen?

I was expecting the some-event listener to fire when an event is emitted.

### Reproduction URL

https://codepen.io/sbsky/pen/oNPRgEd

### How to reproduce?

1. go to provided reproduction link,
2. see the error

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

**Comment by pdanpdan** [comment]
Your test is not a ref

**Comment by selmanbaskaya** [comment]
I think I have given everything necessary. Also, your create issue form is missing. There isn't even a Quasar utils option for the Areas selectbox..

**Comment by pdanpdan** [comment]
You don't understand :))))
Your `test` variable is not a ref - so there is no such thing as `test.value`
https://codepen.io/pdanpdan/pen/VwGOYVV?editors=1010

**Comment by selmanbaskaya** [comment]
hmm now it's done. my bad, thank you!
