### ISSUE TITLE
Cookies Notify text is not legible when in Light mode

### ISSUE THREAD

**Issue by stephencarico** [quasarframework/quasar#15655]
### Description

When landing on the doc site with cleared Cookies (to prompt the Notify) the text is not legible in Light mode because the `color` property is set to `#fff !important`

<img width="1680" alt="Screenshot 2023-03-30 at 8 43 05 PM" src="https://user-images.githubusercontent.com/32233894/229010169-bd7b6253-520a-4c37-86d9-65609c549f19.png">

### Documentation Section URL

https://quasar.dev/docs

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Thank you for reporting!
Fix will be available on next docs deployment.
