### ISSUE TITLE
Q-File's "max-file-size" and "max-total-size" props don't work.

### ISSUE THREAD

**Issue by userpta005** [quasarframework/quasar#15668]
### What happened?

Q-File's "max-file-size" and "max-total-size" props don't work, in all cases it doesn't pass validation, even putting a smaller file than declared in "max-file-size " and "max-total-size" .

It is possible to test in the documentation itself.
https://quasar.dev/vue-components/file-picker#restricting-files

### What did you expect to happen?

Expected to pass validation when inserting files smaller than the size declared in "max-file-size " and "max-total-size".

### Reproduction URL

https://quasar.dev/vue-components/file-picker#restricting-files

### How to reproduce?

Just try to insert a file smaller than the one declared in "max-file-size " and "max-total-size".

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by pdanpdan** [comment]
Works for me

**Comment by userpta005** [comment]
it really works, I hadn't seen that the values are in bytes.
