### ISSUE TITLE
class="dimmed"  applies  dark overlay over the whole page instead of the element

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#15663]
### What happened?

class="dimmed"  applies  dark overlay over the whole page. 
In the documentation [CSS Visibility](https://quasar.dev/style/visibility) :
Apply dark transparent overlay on **top of your element**.

The error is either in code or in documentation.

### What did you expect to happen?

Dimm only element or fix documentation

### Reproduction URL

https://stackblitz.com/edit/quasarframework-a126bu?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

Go to [stackblitz](https://stackblitz.com/edit/quasarframework-a126bu?file=src%2Fpages%2FIndexPage.vue)
and look at the page

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
The element you want dimmed should have a positioned display mode (anything but static)

**Comment by fprijate** [comment]
Maybe this should be in documentation

**Comment by pdanpdan** [comment]
You can make a PR and add the info at all classes that need it
