### ISSUE TITLE
Small typo in quasar.config.js

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#15666]
### What happened?

Change  = to : in commented lines 

```
    eslint: {
      // fix: true,
      // include = [],
      // exclude = [],
      // rawOptions = {},
      warnings: true,
      errors: true
    },
```

### What did you expect to happen?

Nothing 

### Reproduction URL
https://stackblitz.com/edit/quasarframework-8pb5r6?file=quasar.config.js

### How to reproduce?

nothing to reporoduce

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by rstoenescu** [comment]
Thank you for reporting. Fixed it.
