### ISSUE TITLE
Flex-playground colors

### ISSUE THREAD

**Issue by adgower** [quasarframework/quasar#15677]
### Description

The flex-playground is hard to see, because the colors used are to similar.

https://discord.com/channels/415874313728688138/806171748046733332/1092852530377138227

### Documentation Section URL

https://quasar.dev/layout/grid/flex-playground#introduction

### Flavour

None

### Areas

Style & Identity (quasar)

**Comment by rstoenescu** [comment]
Fixed dark theme for all Grid pages (row, column, gutter, patterns, flex playground).
Will be available in next docs deployment.
