### ISSUE TITLE
chips doesn't toggle in q-dialog-select

### ISSUE THREAD

**Issue by amfine-soft-scheminel** [quasarframework/quasar#1568]
Hi

On the documentation page of the q-dialog-select :
http://quasar-framework.org/components/dialog-select.html

On the exemple "List with chips" (it's the purple one).

If you click on the  (white) chips whith (purple) cross to check off the element you have a "TypeError: t.__toggle is not a function" and the element is not toggle.

The chip I clicked on : 
![](https://user-images.githubusercontent.com/27482865/36097967-76355b20-0ffd-11e8-81ef-542f83685fe2.png)

The error :  
```
TypeError: t.__toggle is not a function
Stack trace:
close@http://quasar-framework.org/quasar-play/android/js/vendor.js:6:162750
e@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6965
[2]/</</t.prototype.$emit@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:43857
click@http://quasar-framework.org/quasar-play/android/js/vendor.js:6:115170
e@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6965
ot/t._withTask@http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6643
 vendor.js:11:6471
	it http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6471
	nt http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6398
	et http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6264
	[2]/</</t.prototype.$emit http://quasar-framework.org/quasar-play/android/js/vendor.js:11:43882
	click http://quasar-framework.org/quasar-play/android/js/vendor.js:6:115170
	e http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6965
	ot/t._withTask http://quasar-framework.org/quasar-play/android/js/vendor.js:11:6643
```

Rewrite of : https://github.com/quasarframework/quasar/issues/1554
Sorry for the mistake and thanks you for the answer

**Comment by rstoenescu** [comment]
Transferred to the right repo. https://github.com/quasarframework/quasar-framework.org/issues/333
Thanks for reporting!
