### ISSUE TITLE
Project doesn't build in PWA mode

### ISSUE THREAD

**Issue by qertis** [quasarframework/quasar#15686]
### What happened?

After building PWA and launching a local server, I see a white screen and a runtime error:

[Error] TypeError: The superclass is not a constructor.

If I build with the mode
target: ['esnext']
Then I see the following error:
[OPEN ERROR](https://user-images.githubusercontent.com/3893228/230395368-b0f49a1a-d2f4-418a-9dec-6c46d318725e.png) 

### What did you expect to happen?

I expected the build to complete successfully and the PWA build to look the same as what I see in dev mode.

### Reproduction URL

https://github.com/qertis/solid-client

## Runtime error:
Open the project https://github.com/qertis/solid-client
Switch to the master branch
1. Install Python3 and NodeJS 18
2. Execute the following commands:
npm install
npm run pwa

3. Open the browser and observe the error:
The superclass is not a constructor.

## Build error:
1. Switch to the solid-client branch
2. Execute the following commands:
npm install
npm run pwa

3. Observe the build error.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SSR Mode

### Platforms/Browsers

Firefox, Safari

### Relevant log output

```Shell
App • WAIT Compiling of PWA UI with Vite in progress [vite: esbuild-transpile] Transform failed with 4 errors:
assets/IndexPage. 7a4693b0.js:6480:18: ERROR: Big integer literals are not available in the configured target environment ("chrome87",
"edge88", "es2019", "firefox78", "safari13.1")
assets/IndexPage.7a4693b.js:6480:24 ERROR: Big integer literals are not available in the configured target environment ("chrome87",
"edge88", "es2019", "firefox78", "safari13.1")
assets/IndexPage. 7a4693b0.js: 6480:41: ERROR: Big integer literals are not available in the configured target environment ("chrome87",
"edge88", "es2019", "firefox78", "safari13.1")
assets/IndexPage. 7a4693b0.js:6480:47: ERROR: Big integer literals are not available in the configured target environment ("chrome87",
"edge88", "es2019",
"firefox78", "safari13.1")
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78",
"safari13.1")
6478|
64791
6480|
} else if (typeof input === 'bigint') {
received = String (input);
if (input > 2n ** 32n || input < - (2n ** 32n)) {
received = addNumericalSeparator (received);
```

### Additional context

I noticed that the issue of the project not building in PWA mode did not occur when using quasar webpack and vuex.

**Comment by rstoenescu** [comment]
Hi,

This has nothing to do with Quasar CLI itself. Whatever you configure as build target is supplied down the line to Vite, which in turn supplies it to esbuild. You would get more help from the esbuild team.

Extract from Vite docs:

> Note the build will fail if the code contains features that cannot be safely transpiled by esbuild. See [esbuild docs](https://esbuild.github.io/content-types/#javascript) for more details.

**Comment by qertis** [comment]
https://github.com/evanw/esbuild/issues/3044

**Comment by rstoenescu** [comment]
Thanks for opening a ticket there.

**Comment by qertis** [comment]
@rstoenescu 
Looks like the bug is still in `@quasar/app-vite`
More details here - https://github.com/evanw/esbuild/issues/3044#issuecomment-1500156962

Please reopen Issue.

**Comment by rstoenescu** [comment]
Unfortunately, it is still a non Quasar issue and only has to do with Vite v2 so we cannot solve in Quasar. Quasar CLI uses the latest Vite v2 which indeed unfortunately uses `@rollup/plugin-commonjs` v21.

We are currently working on upgrading Vite to v4, but it is not so simple due to SSR being supported in ESM format -- which in turn forces us to upgrade the CLI to ESM too and it's no small task. It's a work in progress and not ready yet.

What you could do is to use Yarn v1 as your package manager and add this to your package.json:

```
"resolutions": {
  "@rollup/plugin-commonjs": "^22"
}
```

It may work. More on how "resolutions" work: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

The alternative would be to kindly ask the Vite team to do a new Vite v2 release with the updated `@rollup/plugin-commonjs`.

**Comment by qertis** [comment]
I use npm and I'm trying this:
```
"overrides": {
  "@rollup/plugin-commonjs": "^22.0.0"
},
```

However, it's not working for me. Therefore, I will wait for a new release to upgrade Vite to v4 🙂
