### ISSUE TITLE
package ios ipv6 refuse

### ISSUE THREAD

**Issue by lenvonsam** [quasarframework/quasar#1569]
when i cordova build ios, and submit to ios store, it is always refused by Wi-Fi connected to an IPv6 network error.
![image](https://user-images.githubusercontent.com/10168476/36139471-9af1f398-10d8-11e8-9e01-a537b06882ca.png)
how to solve this problem?
current evn:
Quasar: 0.14.4
OS: 10.13.2
Node: 8.9
NPM: 5.6.0
iOS: 8.0

**Comment by rstoenescu** [comment]
Hi,

1. What does this have to do with Quasar?
2. Investigate what's wrong in your app by using an IPv6 network.
3. Use forum or chat to look for help.

Sorry but closing this as it's got nothing to do with Quasar.
