### ISSUE TITLE
q-item-label won't clamp lines on iOS safari

### ISSUE THREAD

**Issue by lxmfly123** [quasarframework/quasar#15692]
### What happened?

In a q-drawer, I set `:lines="2"` on a q-item-label, it works as expected on desktop chrome, but it display all the text on iOS safari.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/2769678/230715094-d82663ea-3274-4344-ab02-0b18b390a0d2.png">

### What did you expect to happen?

The label should display only the first 2 lines.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/2769678/230715122-2804237d-4fdc-4d0c-8633-13ef5cbd9d56.png">

### Reproduction URL

https://codesandbox.io/p/sandbox/romantic-butterfly-64k24y

### How to reproduce?

1. go to the reproduction link through an iOS 16 safari
2. open the left drawer by tap the menu button

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

iOS

**Comment by pdanpdan** [comment]
Looks like a bug in safara (so all ios)
https://stackoverflow.com/questions/70897195/line-clamp-webkit-not-working-in-safari

Try to add `display: inline` on the QItemLabel

**Comment by lxmfly123** [comment]
I think this bug has more association with the behavior of q-drawer. 

I add a q-item-label to the q-page-container instead of the q-drawer, it works well on both desktop chrome and iOS safari. https://codesandbox.io/p/sandbox/romantic-butterfly-64k24y

- desktop chrome
  ![desktop chrome](https://user-images.githubusercontent.com/2769678/231421399-0475d6a7-a1ee-412b-8428-e24d84f98833.png)

- iOS 16 safari
  <img width="375" alt="ios safari" src="https://user-images.githubusercontent.com/2769678/231421576-81fa0742-6de7-4ed1-b5ea-bd9eb37c253c.png">

Also here is a [codepen](https://codepen.io/tihuan/pen/vYNggzj) about line-clamp bug on iOS safari, but the bug does not get reproduced on iOS 16 safari.

**Comment by pdanpdan** [comment]
I think the only solution is this (if you can use it in your specific case):
https://stackoverflow.com/a/76178447

**Comment by lxmfly123** [comment]
after update to iOS 16.4.1, this issue got resolved.
