### ISSUE TITLE
onClickOutside blocks mousedown

### ISSUE THREAD

**Issue by ddenev** [quasarframework/quasar#15696]
### What happened?

When the options menu for a QSelect is open, the `mousedown` handler for any other element does not trigger.

The reason is that the `onClickOutside` handler stops the propagation of the `mousedown` event.

`QMenu.js`, line 116:
```js
const clickOutsideProps = {
  anchorEl,
  innerRef,
  onClickOutside (e) {
    if (props.persistent !== true && showing.value === true) {
      hide(e)

      if (
        // always prevent touch event
        e.type === 'touchstart'
        // prevent click if it's on a dialog backdrop
        || e.target.classList.contains('q-dialog__backdrop')
      ) {
        stopAndPrevent(e)
      }

      return true
    }
  }
}
```
I believe, the `stopAndPrevent()` call above actually blocks the propagation of the event.

Is there a way to NOT stop the `mousedown` propagation in this case? I need this event in my components, especially when QSelects have their options menu open.

### What did you expect to happen?

I expect the `mousedown` event to be triggered, even when QSelect's options menu is open.

### Reproduction URL

https://codepen.io/ddenev/pen/VwELqeg

### How to reproduce?

1. go to the provided pen
2. click on the input field and see in the console that `mousedown` works
3. now click on the select to open the options menu
4. while keeping it open, click on the input field and see in the console that `mousedown` doesn't work

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Directives (quasar)

**Comment by pdanpdan** [comment]
Use `pointerdown` event
https://codepen.io/pdanpdan/pen/xxyGBzX?editors=1010

The `stopAndPrevent` is on purpose exactly to prevent clicks to register on other elements when the menu is open.

**Comment by ddenev** [comment]
thank you, @pdanpdan !
