### ISSUE TITLE
Debugging in VS Code using Vite

### ISSUE THREAD

**Issue by 46319943** [quasarframework/quasar#15695]
### Description

The configuration for debug in vscode assumes the usage of webpack. However, the config under vite is a little different from that of webpack. 

Such as :
```
// quasar.config.js
devtool: 'source-map'
```
```
// launch.json
  "sourceMapPathOverrides": {
    "webpack://package-name/./src/*": "${webRoot}/*"
  }
```
are both unneccessary to set.

In my case, the only effort to make the debugger work is setting the `url server port` and `webRoot` in `launch.json`
```
  "configurations": [
    {
      "type": "msedge",
      "request": "launch",
      "name": "Launch Edge against localhost",
      "url": "http://localhost:9000",
      "webRoot": "${workspaceFolder}/src"
    }
  ]
```

### Documentation Section URL

https://quasar.dev/start/vs-code-configuration#debugging-a-quasar-project-in-vs-code

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by pdanpdan** [comment]
Can you please make a PR for the docs with what is required for Vite? Thank you

**Comment by 46319943** [comment]
Some annotations have been added to the json file.

**Comment by 46319943** [comment]
Merged in https://github.com/quasarframework/quasar/pull/15707
