### ISSUE TITLE
CLOSE on select is redundant

### ISSUE THREAD

**Issue by mariaczi** [quasarframework/quasar#157]
It is redundant and really useless.
To prove my word, look at other ui libs - you will not find it anywhere in any respected library. It even looks strange.

**Comment by rstoenescu** [comment]
The point of a framework is to offer components as generic as possible with as many features as possible. There may be cases when the developer wants to programmatically open the select popover. The argument that X other framework doesn't do this is not valid. Quasar is better than other frameworks. Please reopen with a solid argumentation.

**Comment by mariaczi** [comment]
You're right. Then, there should be optional parameter 
`close='false'` to disable it or enable - depends which one will be default.
Then Q will be really better than others! :)

**Comment by rstoenescu** [comment]
You've got `disable` Boolean property. Case closed. Q wins :)

**Comment by mariaczi** [comment]
Not that easy! :)
I would really like to be able to not show CLOSE button on the top of options of multiselect ( `type='checkbox`.
I hope you get what I mean?
[https://snag.gy/aOG3Zx.jpg](https://snag.gy/aOG3Zx.jpg)

**Comment by rstoenescu** [comment]
Aha. You are referring to something else. Ok, will add a property. Do you care to make a PR? It's easy.

**Comment by mariaczi** [comment]
Agree - should be shown on small screens as default, but on larger screens we need at least choice :)
