### ISSUE TITLE
Table component displays the selected quantity, internationalization is invalid

### ISSUE THREAD

**Issue by Wangijun** [quasarframework/quasar#15715]
### What happened?

![image](https://user-images.githubusercontent.com/40266995/232083642-ba7edd4b-0154-48d1-92fc-d7ca6599afaa.png)

![image](https://user-images.githubusercontent.com/40266995/232083841-548643a2-0b27-44d7-8e46-bf0e0e2a3b45.png)

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/40266995/232083987-28eed732-f217-442d-a9c7-a8f00e640043.png)

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-9pecfn?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

100% reproduction

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Quasar info output

```Shell
No abnormal information
```

### Relevant log output

```Shell
No
```

### Additional context

NO

**Comment by yusufkandemir** [comment]
You defined a custom label function that overrides the default internationalized labels:
```js
// :selected-rows-label="getSelectedString"
function getSelectedString() {
  return selected.value.length === 0
    ? ''
    : `${selected.value.length} record${
        selected.value.length > 1 ? 's' : ''
      } selected of ${tableData.value.length}`;
}
```
If you want the default i18n labels to work, just don't override `selected-rows-label`.
