### ISSUE TITLE
Vite-plugin-federation causes hot-reload loop

### ISSUE THREAD

**Issue by Kminkjan** [quasarframework/quasar#15711]
### What happened?

When adding vite-plugin-federation as a vitePlugin in the quasar.config.js, the quasar dev command starts in an endless hot reload loop. 

### What did you expect to happen?

Module federation using quasar build works perfectly fine. I would expect using vite-plugin-federation to work with quasar dev as well. (Using it as an host).

As far as I can see, vite-plugin-federation should be usable as long as the vite mode is development.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-6ypbt3

### How to reproduce?

Add vite-plugin-federation to the vitePlugins in the quasar.config.js.
I've provided a stackblitz where you can see it happen after it runs quasar dev.

(The fact the it is using localhost as remote, should not matter in this problem case. As the endless hot reload loop also occurs when that remote was valid on my localhost).

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Additional context

I hope this is the right place to address this issue. Thank you for looking into it.

**Comment by rstoenescu** [comment]
Thank you for reporting this!
Fix will be available in q/app-vite v1.4.2
