### ISSUE TITLE
QSelect in first Dialog focused when 2nd seamless Dialog opens

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#15730]
### What happened?

I have a Dialog open that contains a QSelect. A 2nd Dialog is open in seamless mode and the QSelect in the 1st Dialog that is still open gets focus. The 2nd Dialog has a QInput in it and I am unable to give focus to it as is seems the focus is locked to that QSelect in the 1st Dialog.

### What did you expect to happen?

The opening of the 2nd seamless Dialog not to affect the 1st Dialogs children and to be able to interact with the QInput in the 2nd seamless Dialog.

### Reproduction URL

https://codepen.io/smakinson/pen/RweGGJM?editors=1010

### How to reproduce?

1. Go to the reproduction link
2. notice the first open Dialog on the left and it's QSelect does not have focus.
3. wait 3 seconds
4. notice the 2nd seamless Dialog opens on the top
5. notice the QSelect in the first Dialog has focus
6. try to click in the QInput in the 2nd seamless Dialog
7. notice you are unable to interact with the QInput

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
Operating System - Darwin(20.6.0) - darwin/x64
NodeJs - 16.17.1

Global packages
  NPM - 8.15.0
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.7.2 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.33 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.21.3 -- Babel compiler core.
  webpack - 5.76.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qoverlay - 2.0.1 -- A Quasar App Extension
```

**Comment by rstoenescu** [comment]
Hi,

Add `allow-focus-outside` to your first Dialog, otherwise for accessibility reasons non seamless QDialogs capture focus (one of the many examples: TABbing through focusable elements should not leave the Dialog ones and continue with the rest of the page). But in your case, you actually do not want that default behavior.

So:

```
<q-dialog v-model="d1" full-height no-backdrop-dismiss position="left" allow-focus-outside>
```

Btw, thanks for your continued sponsorship!
