### ISSUE TITLE
BEX build (circular reference bug)

### ISSUE THREAD

**Issue by robert-hoffmann** [quasarframework/quasar#15749]
### What happened?

When you build BEX it generates a zip file
This zip file contains circular references to itself....

Since this morning this has been generating zip files up to 2GO big 😁
Before this morning, it was generating zip files with another useless zip inside it, but that was ok

### What did you expect to happen?

Have a normally "sized" zip file

### Reproduction URL

https://stackblitz.com/edit/quasarframework-m8p9em

### How to reproduce?

1) Reproduction link does not work, as stackblitz does not actually generate the zip
2) Just create a project locally and test

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

BEX Mode

### Platforms/Browsers

Other

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.15.0

Global packages
  NPM - 9.5.0
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - 2.5.1
  cordova - Not installed

Important local packages
  quasar - 2.11.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.32.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - FRML0141
  Ethernet (pc) - 10.13.3.234
  vEthernet (Default Switch) - 172.18.x.x
  vEthernet (WSLCore) - 172.24.x.x
```

### Additional context

platform doesn't really apply ..maybe windows

**Comment by robert-hoffmann** [comment]
Here's some extra info

I was able to fix the problem of it generating 2Go zip files

The problem was i had a json file with data to prepopulate a dexie database which was 350Ko, and that was apparently messing with vite and chunking or something like that

That doesn't change that bex build will actually generate a zip with another useless zip inside of it (maybe this is "part" of the initial problem)

**Comment by rstoenescu** [comment]
Hi,

It is unreproducible with the project folder that you have provided.
However, if you end up with circular references then you're doing something wrong, but I cannot tell what without looking at a reproduction folder. Most likely you are "building" something directly into the source file which ends up packaged and packaged again.

We can help you only if you provide your actual usage, not just an almost barebones bex folder.

**Comment by robert-hoffmann** [comment]
Thanks for the feedback

But stackblitz doesn't even generate an actual zip file

However bex compilation, has always generated a zip inside a zip for me

And even if i do have a problem inside my vue files somewhere, this does not explain how the compiler would make zips inside zips, it should simply package the source and nothing else

![image](https://user-images.githubusercontent.com/5472296/234258831-b3842b77-1d53-4b60-980e-c254767cd8a3.png)

**Comment by rstoenescu** [comment]
Make abstraction of the fact that Stackblitz cannot fully build a zip. This does not matter. If a correct reproduction is supplied, I can download the project folder and play with it locally.

Like I mentioned, most likely you are "building" something directly into the source file which ends up packaged and packaged again.

**Comment by rstoenescu** [comment]
Hmm, reproduced the issue. Investigating.

**Comment by rstoenescu** [comment]
Found the issue. It was due to the newer "archiver" behaving differently.
Fix will be available in `@quasar/app-vite` v1.2.2

Thanks for this ticket.

**Comment by robert-hoffmann** [comment]
Cool, tnx 🙏

**Comment by rstoenescu** [comment]
And just released the new version of q/app-vite

**Comment by robert-hoffmann** [comment]
That was quick 😁
Works fine now 👍
