### ISSUE TITLE
[Request] Add ehanced input number

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#1574]
I'd find useful to have an input number like the one found here: http://element.eleme.io/#/en-US/component/input-number

The buttons to increment and decrement make it easy to use, while the control still offers the possibility to enter the number manually. The buttons acknowledge the min/max constraints and are consistent across browsers (and can be styled if needed).

**Comment by Frondor** [comment]
I'm pretty sure you can already create something like that easily with QInput and `:before` / `:after` props for each QBtn, and two methods (functions)

**Comment by wc-matteo** [comment]
Maybe, still would be nice to have something ready and well polished.

**Comment by wc-matteo** [comment]
Duplicated: https://github.com/quasarframework/quasar/issues/1418
