### ISSUE TITLE
Add quasar into an existing project

### ISSUE THREAD

**Issue by maxime-aubry** [quasarframework/quasar#1576]
Hello.

I would like to know how to add Quasar into an existing project, wich one uses TypeScript !
I created my project with vue-cli 3.0 from vue.js.

Thanks.

**Comment by UnnoTed** [comment]
I got it working by installing `quasar-framework`, then import like:
```typescript
import Quasar from "quasar-framework/dist/quasar.mat.esm";
import "quasar-framework/dist/umd/quasar.mat.css";

Vue.use(Quasar);
```

Importing the component on `.vue`
```html
<template>
  <q-btn label="hello" />
</template>
```

```typescript
import { QBtn } from "quasar-framework/dist/quasar.mat.esm";

export default {
  name: "App",
  components: {
    QBtn,
  },
};
```

you can avoid writing `quasar-framework/dist/quasar.mat.esm` everytime by creating an alias in the webpack's config to route `quasar` to `quasar-framework/dist/quasar.mat.esm`... you can copy the aliases from: https://github.com/quasarframework/quasar-cli/blob/5cf2b99479c066116ec698397f7c0ea761f7d2c9/lib/build/webpack-config.js#L86

**Comment by Kminkjan** [comment]
Great! I use the same setup (vue-cli 3 with quasar 0.15) and i just couldn't get the notify to work. I wish quasar 0.15 played a bit nicer when working with the new Vue cli, as they are both great technologies.

**Comment by hurrycaner** [comment]
@Kminkjan I was having problems with notify, but i found out that the problem is being fixed at #1913
Can you confirm if your problem is this?

**Comment by johnyluyte** [comment]
Got Quasar UMD to work with [Nuxt](https://github.com/nuxt) follwing @UnnoTed 's tips.

In short:

1. `npm install --save quasar-framework`
2.  Edit `nuxt.config.js`
````javascript
plugins: [
  "~/plugins/quasar.js"
]
````
3. create 'quasar.js' in `/plugins/` folder: 

````javascript
import Vue from "vue";
// import "quasar-framework/dist/umd/quasar.mat.css";
import "quasar-framework/dist/umd/quasar.ios.css";

import Quasar, { QLayout, QInput, QBtn } from "quasar-framework/dist/quasar.mat.esm";
Vue.use(Quasar, { components: [QLayout, QInput, QBtn] });
````
4. check out the above thread by @UnnoTed for more tips.

**Comment by nusendra** [comment]
@johnyluyte do you build hybrid mobile app with nuxt? can u share ur code? i dont know how to setup webpack with nuxt for building mobile app. thanks

**Comment by johnyluyte** [comment]
I tried to build a hybrid mobile App with Nuxt and Quasar last week. But I'm too busy to continue. Here are some of my thoughts.

1. Use Quasar CLI
I haven't really tried Quasar CLI, but being able to build hybrid mobile App is one of Quasar's best selling point, so this should work. But I personally don't like being forced to use an opinionated structure, especially we have other community-supported project like Nuxt and Cordova. I might be wrong with this and YMMV. [You should try this first](https://quasar-framework.org/guide/cordova-preparation.html) and see if it suit you well.

2. Use Quasar + Nuxt
It is stated in Quasar's offical [Roadmap](https://quasar-framework.org/guide/quasar-roadmap.html) that they will release a `Quasar + Nuxt starter kit` in Quasar `v1.0`. The release date is still TBA but I'm really looking forward.

3. Use Nuxt + UMD Quasar + Cordova
I haven't tried this but there are some tutorials out there, e.g. [this one](https://itnext.io/make-hybrid-platform-cordova-vue-webpack-2fb7031c4f9b). You have to configure Webpack and Cordova, and Cordova Plugin might be a problem.

4. Nuxt generate + (any Vue UMD) + Cordova
Its like the above method, but with `Nuxt generate` command. This one also seems viable, but Cordova Plugin might also be a problem. [Japanese rticle but the codes are in English](https://qiita.com/yuushimizu/items/f36fecb68a57cf4faec5)

5. Nuxt + (any Vue UMD) + PWA
This is not really a hybrid mobile App, its PWA. But considering how [iOS finally started to work on PWA](https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7), I actually think this is not a bad way to go.

Personally I would start with Nuxt PWA and use UMD Quasar, then jump to Quasar+Nuxt when Quasar v1.0 release. Or substitute Quasar with other framework if it doesn't suit my project well.

I might dive into this again 2 or 3 weeks later. Hope this help.

**Comment by nusendra** [comment]
thanks @johnyluyte for the information.....

**Comment by giona69** [comment]
I tried to integrate quasar with nuxt but I got a lot of errors (window not defined etc) ... it seems many components of quasar aren't ready to be server side rendered ... anyone has a better experience?

**Comment by rstoenescu** [comment]
@giona69 SSR is under works (95% done) ;) also a Nuxt module for Quasar.

**Comment by ttxtosca** [comment]
@rstoenescu that are very good news. I suppose that the nuxt module will be official when SSR is fully working, do you have any idea for the approximated time needed to fill the last 5%?

Congrats for you work! Quasar is a really nice project

**Comment by rstoenescu** [comment]
@ttxtosca targeting end of month, so anywhere around that.

**Comment by slowaways** [comment]
Awesome feature!

**Comment by rstoenescu** [comment]
This should have been closed some time ago. "vue-cli-plugin-quasar" was released a lot of time ago.
```vue add quasar```

**Comment by rulrok** [comment]
Just a note if someone needs to pass global configurations like for [Loading bar](https://v0-17.quasar-framework.org/components/loading-bar.html):

```js
    Vue.use(Quasar, {
        config: {
            loadingBar: {
                color: "primary",
                size: "3px",
            },
        },
        components: [
            ...
        ],
    });
```

**Comment by luckylooke** [comment]
I have tried `vue add quasar` but it does not add quasar CLI to the project, when I install in manually `npm install -g @quasar/cli` I have limited commands as I am not in quasar project. There is only command for creating new project, but I want to augment one created by Vue CLI, is this somehow possible? I would love to see `quasar init` command. Thanks 🙏

**Comment by rstoenescu** [comment]
@luckylooke If you want to use Quasar CLI (recommended) then you should create a project with it. Quasar CLI projects !== Vue CLI projects. Do not mix the two. They are incompatible. Check docs how to install and create a project with Quasar CLI.
