### ISSUE TITLE
QTree expandAll duplicating expanded nodes

### ISSUE THREAD

**Issue by Seamus-Ohhhh** [quasarframework/quasar#15764]
### What happened?

QTree expandAll method duplicating expanded nodes in expanded array. 

issue seems to be in the expandAll function. the const expanded is being set to the current expanded array with each expandable node being added to the array.

currently have to run collapseAll before expandAll to clear out the expanded array

### What did you expect to happen?

nodes to be referenced once in the expanded array

### Reproduction URL

https://codepen.io/seamus-ohhhh/pen/Rwegaqg?editors=1010

### How to reproduce?

1. go to link 
2. note current length of expanded nodes and list displayed (should show length 2, with 2 nodes shown)
3. click 'EXPAND ALL' button
4. note new length of expanded nodes (should show length 5, with 5 nodes shown - 2 duplicates)
5. repeat step 3  with each click of 'EXPAND ALL'  all expandable nodes are appended to array

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron, Other

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.11.11 and v1.22.10
