### ISSUE TITLE
[Request] Add grouped options with titles for QSelect

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#1578]
Like this one: https://developer.microsoft.com/en-us/fabric#/components/dropdown

**Comment by rstoenescu** [comment]
Will do.

**Comment by wc-matteo** [comment]
I don't know if we could reuse titles for this, but having the choice of disabling certain options in the list would be great too! A disabled option would appear different from the others and selecting would clear the current selected option.

**Comment by rstoenescu** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/557
