### ISSUE TITLE
Notify usage is out of sync w.r.t to source code

### ISSUE THREAD

**Issue by agebhar1** [quasarframework/quasar#15789]
### Description

The Notify API and also the 'Basic' example mention the method 'create' which was removed a long time ago at 368667c3049e1b1f0708671aa0bab6bc848a5a49. The file `ui/src/plugins/Notify.js` was updated but `ui/src/plugins/Notify.json` not.

The issue was also mentioned on #14122.

### Documentation Section URL

https://quasar.dev/quasar-plugins/notify#basic

### Flavour

None

### Areas

Plugins (quasar)

**Comment by pdanpdan** [comment]
It was not removed, what do you mean?

**Comment by agebhar1** [comment]
The 'create' method. I forget to mention it.

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/OJBzPbE?editors=0010

**Comment by agebhar1** [comment]
![grafik](https://user-images.githubusercontent.com/2443866/236282270-6d1fed56-7ea9-4720-b816-cbab9cc5ade9.png)

**Comment by pdanpdan** [comment]
Ignore that - it is a bug in the conversion to the codepen that must be fixed

**Comment by agebhar1** [comment]
I do, but that's not the issue. This does not work:

```js
Notify.create({
  message: 'Danger, Will Robinson! Danger!'
})
```
and it's still in the documentation.

**Comment by pdanpdan** [comment]
It works, see updated codepen
Are you sure you installed the plugin?
https://quasar.dev/quasar-plugins/notify#installation

**Comment by agebhar1** [comment]
You're right, it works. My fault. Retried it with a plain project. Last time I might missed to install/register the plugin or something others went wrong. The error was, and if I do not register the plugin it's the same, that 'create is not function' popped up in the error log.

I appreciate your help.

**Comment by zhou-y-j** [comment]
const  Notify } = Quasar

Notify.create('Danger, Will Robinson! Danger!')
// or with a config object:
Notify.create({
  message: 'Danger, Will Robinson! Danger!'
})
——————————————————

![K}F~$Y%9@CHRMSE`)@7CB(Q](https://github.com/user-attachments/assets/f66a530d-26a7-4b66-9779-7167d589ebdd)

It doesn't work
