### ISSUE TITLE
 SyntaxError: redeclaration of import QItemSection

### ISSUE THREAD

**Issue by Tenrys** [quasarframework/quasar#15784]
### What happened?

I am using `autoImportComponentCase: 'combined'` in my `quasar.config.js`, because my project uses both pascal and kebab case for Quasar elements.

My new component which uses pascal case seems to fail to load with this error:

![image](https://user-images.githubusercontent.com/3979239/235909379-17532152-e4bb-4548-bd81-3bb96a5d337c.png)

Not sure how to fix it aside from switching everything to one case only for now.

It seems like having two identical Quasar components with different cases throughout the template makes it import twice.

### What did you expect to happen?

I should be able to use components with interchangeable cases through my component without issue.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-baxkzs?file=src/pages/ExamplePage.vue

### How to reproduce?

1. Go to the provided reproduction link
2. Look in your browser console for the error
3. Check `pages/ExamplePage.vue`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by rstoenescu** [comment]
Thank you for reporting!
Fix will be available in next quasar/vite-plugin & q/app-vite.

**Comment by rstoenescu** [comment]
Available in q/app-vite 1.4.1 and q/vite-plugin 1.3.2
