### ISSUE TITLE
Auto Complete | Intellisense in VSCODE

### ISSUE THREAD

**Issue by matheusmfeitoza** [quasarframework/quasar#15794]
### What happened?

AutoComplete and Intellisense don't work, even using the recommended plugins.
In searches and other tutorials, no solutions were found.
But using VETUR, the same works

OS: Ubuntu 23.04
Node: 18.16.0
Using Vite
VSCODE: 1.78

Plugins: 
Volar
Volar TS ( following the recommends)
Eslint
Prettier
Quasar Docs

![image](https://user-images.githubusercontent.com/26209366/236630169-cc871ef2-35bd-4a90-87f9-ecb12245529a.png)

### What did you expect to happen?

Autocomplete in properties and css classes was expected

### Reproduction URL

https://stackblitz.com/edit/quasarframework-qll9hc?file=src%2Fpages%2FErrorNotFound.vue,.vscode%2Fextensions.json

### How to reproduce?

Create a new project in using QUASAR
Install all recommended extensions;
Try to use intellisense or autocomplete

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

**Comment by yusufkandemir** [comment]
Can't reproduce in VS Code.
![image](https://user-images.githubusercontent.com/6266078/236807635-ecdb3991-6c75-49a4-830a-ba99445f8ec6.png)

**Comment by matheusmfeitoza** [comment]
Can you help me to fix it ?
I followed all  about vscode in quasar 
https://quasar.dev/start/vs-code-configuration/
but not work

**Comment by yusufkandemir** [comment]
Check out `Preferences: Open User Settings (JSON)`
![image](https://user-images.githubusercontent.com/6266078/236822713-e1175756-1b0d-4be8-b00f-fef9de60a636.png)
and make sure it doesn't have unintended/conflicting overrides/options. Make sure the required extensions are correctly enabled and any potentially conflicting extensions are disabled.

**Comment by matheusmfeitoza** [comment]
I did an install using Quasar-cli (npm init quasar) and everything worked perfectly...

In a project started with Vite and manually installed quasar, I can't have autocomplete
Something like this (https://quasar.dev/start/vite-plugin)
