### ISSUE TITLE
Date range picker chashes the browser when locale data is provided

### ISSUE THREAD

**Issue by sklr** [quasarframework/quasar#15797]
### What happened?

In my app I have q-date range selector. Watcher on the v-model variable executes infinite number of times, when I select the first date of the range.

### What did you expect to happen?

The watcher to execute once.

### Reproduction URL

https://codepen.io/sixkiller/pen/vYVdpdm

### How to reproduce?

Select a date range from the picker.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 16.14.2

Global packages
  NPM - 8.5.0
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
Quasar App Extensions
  *None installed*

Networking
...
```

### Additional context

It looks like the problem exists only if custom locale formatting options are provided to the component.

**Comment by pdanpdan** [comment]
Use a stable object for locale - you are using a literal and it forces a redraw each time it is changes and it changes each time it is redrawn
https://codepen.io/pdanpdan/pen/abRqGKv
