### ISSUE TITLE
Floating label for Datetime & Selectbox

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#158]
Would be really nice to get possibility to get floating label for DATETIME component

**Comment by rstoenescu** [comment]
Yes, will look into that ;)

**Comment by rstoenescu** [comment]
This will come to Quasar really soon. Not only for Datetime. For Select too.

**Comment by murbanowicz** [comment]
So good! It will make it really nice to have forms really consistent thanks to Quasar!

**Comment by rstoenescu** [comment]
Consistency is key!

**Comment by rstoenescu** [comment]
Pushed commit.

 * Selectbox performance enhancements
 * Date & Selectbox clear separation of "label" and "placeholder" props
