### ISSUE TITLE
<q-btn> click method doesn't close the left menu on <q-toolbar>

### ISSUE THREAD

**Issue by alexpvieira** [quasarframework/quasar#1580]
### Software version

Quasar: 0.14.9
OS: Windows
Node: 0.14.9
NPM: 5.5.1
Browsers: Chrome
iOS:
Android: 7.1
Any other software related to your bug:

### What did you get as the error?
When using a `<q-btn>` inside a left menu on `<q-toolbar>` the @click method called doesn't close the menu, even using the `this.$refs.layout.hideCurrentSide()` in the method.

### What were you expecting?
The menu to be closed as the button is clicked. This is the comportament when I change a option that is on a `<q-select>` on the same menu. Sometimes the menu closes but most of the time it doesn't.

### What steps did you take, to get the error?
`<q-toolbar slot="header">`
   `<div slot="left">`
    `<q-select v-model="selectedObra" float-label="Selecione uma obra" :options="obras" @change="$refs.layout.hideLeft()"/>` //this one closes the menu
`<q-btn color="primary" class="full-width" @click="logout">Sair</q-btn>` //this one doesn't
`</div>`

`logout() {`
            `this.$refs.layout.hideCurrentSide()`
            `this.$store.dispatch('SET_USER_DATA', ['', '', '', ''])`
           ` this.$router.push({name: 'login'})`
       ` },`

**Comment by rstoenescu** [comment]
Hi,

```js
logout() {
  this.$refs.layout.hideCurrentSide(() => {
    this.$store.dispatch('SET_USER_DATA', ['', '', '', ''])
    this.$router.push({name: 'login'})
  })
}
```

You need to wait for the sidebar to close first, then navigate to a new route.
