### ISSUE TITLE
QSelect set readonly and use-input，focus to field，then press backspace and options which selected would be deleted。

### ISSUE THREAD

**Issue by xiaojun777** [quasarframework/quasar#15808]
### What happened?

QSelect set readonly and use-input，focus to field， then press backspace and options which selected would be deleted。

### What did you expect to happen?

in readonly state, no option can deleted by user input. 

### Reproduction URL

https://codepen.io/onlldvei-the-encoder/pen/LYgdMOE

### How to reproduce?

click on select
press backspace on keyboard

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.12.1 and 1.22.11
