### ISSUE TITLE
Using prop on the component adds additional entries in style attribute

### ISSUE THREAD

**Issue by OlkaB** [quasarframework/quasar#15816]
### What happened?

When adding an attribute `padding="12px"` on `q-btn` component it also adds min-width and min-height automatically to the style attribute of the <button> DOM node. This is unexpected and undesirable behaviour.

### What did you expect to happen?

Only padding is requested to change and only padding should change

### Reproduction URL

https://jsfiddle.net/d5Lmr3wn/3/

### How to reproduce?

Add `padding="12px"` to `q-btn` component and check <button> element style attribiute

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 14.21.2

Global packages 
  NPM - 6.14.17
  yarn - 1.22.4
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time      
  @quasar/app-vite - 1.3.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.35 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.40.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
Hi,

This is not a CLI bug. It's the default design inherited from the Material guidelines. If you wish you can override it with your desired css.
