### ISSUE TITLE
`npm install -g @quasar/cli` failed for node v18

### ISSUE THREAD

**Issue by briansu2004** [quasarframework/quasar#15829]
### What happened?

C:\MyRepoI>npm install -g @quasar/cli
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x\AppData\Local\npm-cache\_logs\2023-05-13T20_29_27_121Z-debug-0.log

C:\CodeHat\MyDaskUI>npm install -g @quasar/cli
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x\AppData\Local\npm-cache\_logs\2023-05-13T20_32_00_973Z-debug-0.log

C:\MyRepoI>nvm list

  * 18.0.0 (Currently using 64-bit executable)
    16.0.0
    14.17.5
    14.17.3

### What did you expect to happen?

npm install no issues

### Reproduction URL

n/a

### How to reproduce?

nvm use 18

npm install -g @quasar/cli

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by briansu2004** [comment]
How to reproduce in - [Codepen](https://codepen.io/), [jsFiddle](https://jsfiddle.net/), [StackBlitz](https://stackblitz.com/), [Codesandbox](https://codesandbox.io/), and [GitHub](https://github.com/).

This is installation related.

**Comment by rstoenescu** [comment]
This is not a Quasar bug, but a bug in npm. Reference: https://stackoverflow.com/questions/70958371/unexpected-token-when-trying-to-run-npm-install

**Comment by briansu2004** [comment]
Ok nice :-)
