### ISSUE TITLE
QCard、QBar、QItem... can`t trigger  onBeforeUpdate\onUpdated function!!! 

### ISSUE THREAD

**Issue by baoerapp** [quasarframework/quasar#15834]
### What happened?

 I want to use onUpdated to manipulate scrollTop of a div, but found that the onUpdated function is not being called. I spent 3 hours troubleshooting the issue and finally found that components such as QCard, QItem, QBar, etc. would cause the onUpdated function not to trigger.

### What did you expect to happen?

I hope that when the data changes in QCard, the onUpdated method can be triggered.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-gbbttz?file=src/pages/Test.vue

### How to reproduce?

look url: https://stackblitz.com/edit/quasarframework-webpack-gbbttz?file=src/pages/Test.vue

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
You are changing something that is rendered in the default slot of QCard.
So if all works well QCard should not be re-rendered
It would have been bad if it would have been re-rendered :)
