### ISSUE TITLE
Missing documentation for adding TypeScript to an existing Vite project

### ISSUE THREAD

**Issue by straurob** [quasarframework/quasar#15852]
### Description

While the documentation contains a detailed description about [Supporting TypeScript with Webpack](https://quasar.dev/quasar-cli-webpack/supporting-ts), that same documentation is missing for the Vite flavor, especially when TypeScript support shall be added to an existing Vite JavaScript project.

Most of the steps might be similar or even identical, but my attempts were laborous. I ended up creating two empty projects, one with JavaScript and one with TypeScript, then comparing all file differences.

A more detailed documentation would have been much appreciated  :slightly_smiling_face: 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

**Comment by pdanpdan** [comment]
Because there is nothing specific to quasar?
You did the diff, what are the differences (except renamed files and TS syntax)?

**Comment by straurob** [comment]
I agree. After having read your comment and inspected the diff between the project skeletons, there is nothing specific to Quasar. As described in the original issue, I was mainly confused as the Webpack section contains a detailed description and I would have expected that there is something similar for Vite.

**Comment by pdanpdan** [comment]
Vite supports TS by default, so everything is easier :)
