### ISSUE TITLE
SSR-Example application required, Docs for SSR are incomplete

### ISSUE THREAD

**Issue by opendeluxe** [quasarframework/quasar#15869]
### Description

Hi. The dlocumentation for SSR seems to be incomplete. It explains many things on an expert-level that probably is required once SSR is already set up successfully. But for the stage before that, some kind of entry level, it is not suitable.

I have enabled SSR in Quasar and implemented a `preFetch`-Method in a component. It will be executed, but the rendering happens client-side. The HTML in my page still don't contain the prefetched data and thus no pre-rendered state is visible. 
So I miss particular things here that are not well documented.

Can someone provide please an example documentation or a tutorial for setting up Quasar in SSR mode?

### Documentation Section URL

https://quasar.dev/quasar-cli-webpack/developing-ssr/introduction

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SSR Mode

**Comment by pdanpdan** [comment]
https://quasar.dev/quasar-cli-vite/quasar-config-js#prefetch

**Comment by opendeluxe** [comment]
As I wrote, I did this already. But it doesn't work as expected and apparently further other steps are still also required. 

The Docs are lacking for SSR to make it work and this was the purpose of my issue here. Is there any tutorial around that contains more then "use prefetch:true in config and write a preFetch-method"?

**Comment by rstoenescu** [comment]
Please provide a barebones reproduction repo with your use-case so we can see what you missed or what we can improve from docs so things will be more clear. Otherwise we don't have anything actionable here and the description is too vague.

**Comment by pdanpdan** [comment]
We'll reopen if feedback is available. Thank you
