### ISSUE TITLE
Stacking multiple 'q-item-section' using the 'column' class will incorrectly add a left margin to some

### ISSUE THREAD

**Issue by BenJackGill** [quasarframework/quasar#15874]
### What happened?

When stacking multiple `q-item-section`'s using the `column` class only the first `q-item-section` is aligned to the left correctly. All others will incorrectly have a left margin added.

```Vue
<q-item class="column">
  <q-item-section>
    First Section - Correct Left Alignment
  </q-item-section>
  <q-item-section>
    Second Section - Incorrect Left Alignment
  </q-item-section>
  <q-item-section>
    Third Section - Incorrect Left Alignment
  </q-item-section>
</q-item>
```

### What did you expect to happen?

I expected all `q-item-section`'s to have a uniform left alignment. I expected there to be no left margin added.

### Reproduction URL

https://codepen.io/thecashbag/pen/ZEqVyXM?editors=101

### How to reproduce?

1. Go to the provided reproduction link
2. See that the `q-item-section`'s do not align on the left due to the left margin of all but the first one

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
`QItem` and `QItemSection` are designed to work in flex row mode (`QItemSection` is using spacing on left)

What is inside `QItemSection` is designed to work in column flow mode

https://codepen.io/pdanpdan/pen/ExdJdya?editors=1010
