### ISSUE TITLE
quasar.config.js with Vite plugin: TypeError: Merging undefined is not supported

### ISSUE THREAD

**Issue by therealcoder1337** [quasarframework/quasar#15871]
### What happened?

After upgrading Quasar, running `quasar dev` results in the error `TypeError: Merging undefined is not supported`, when a Vite plugin is specified without options object.
The Vite plugin definition might look like this:
` vitePlugins: [['vite-svg-loader']]`

A workaround is to provide an empty options object:

` vitePlugins: [['vite-svg-loader', {}]]`

### What did you expect to happen?

The Quasar dev server should start without any error, as it did before.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-ecpqcf?file=package.json%2Cquasar.config.js

### How to reproduce?

1. Open the reproduction link
2. Wait for npm to install and for the dev server to start
3. See it fail with the mentioned error

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Additional context

This was already described on Discord ~10 days ago: https://discord.com/channels/415874313728688138/1106184987876794421/1106184989781012481

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in next q/app-vite.
