### ISSUE TITLE
LTR QSelect and QTree not rendering correctly in RTL app

### ISSUE THREAD

**Issue by heteth** [quasarframework/quasar#15897]
### What happened?

QTree and QSelect render in correctly when marked with dir=ltr in an app set to use RTL (Contrary to the docs https://quasar.dev/options/rtl-support#marking-css-rules-as-exceptions)

### What did you expect to happen?

QTree and QSelect to render correctly.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-px79ij?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Generate a new app
2. Update lang in config to a RTL language such as 'ar' or 'fa'
3. Place a tree or select component under a `<div dir=ltr>` 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
All components are designed to use the `dir` attribute on `html` tag.
https://quasar.dev/options/rtl-support#marking-css-rules-as-exceptions has nothing to to with tat - it explains how to use rules for RTLCSS in you styles

Unfortunately mixing LTR and RTL for components in the same DOM tree is not so easy and would require a lot of extra CSS.
