### ISSUE TITLE
Datetime issue - 24hr format is showing properly, but 'picker' stays 12hr. Include improvement suggestion.

### ISSUE THREAD

**Issue by mariaczi** [quasarframework/quasar#159]
As mentioned in the title:
Datetime picker is showing proper time, but picker stays 12hr.

Source code: 
```
<quasar-datetime
  v-model="event.time"
  type="time"
  format="H:mm"
></quasar-datetime>
```
[Picture](https://snag.gy/EkRxGy.jpg)

SUGGESTION: 
I think it would be good to have an option for arrows only (plus/minus hr and m), without the clock.

**Comment by rstoenescu** [comment]
The format is specifically for the label of the datetime picker, not for the picker itself. Will take into consideration your suggestion though. Thanks!

**Comment by mariaczi** [comment]
Definitely has to handle 24hr time format in the picker. Most of
european people will get confused when they will see AM/PM picker... Q
should be for everyone :) , not only for countries using 12hr time format.

2016-11-03 8:08 GMT+00:00 Razvan Stoenescu <notifications@github.com>:

**Comment by rstoenescu** [comment]
Yes, you are right and this is in the top priority list. It will drop in Quasar soon.

**Comment by mariaczi** [comment]
So good! I appreciate your effort on Quasar

2016-11-03 8:15 GMT+00:00 Razvan Stoenescu <notifications@github.com>:

**Comment by murbanowicz** [comment]
@rstoenescu shouldn't you keep this kind of issues open until solution is implemented? Just to have it recorded and tracked?

**Comment by rstoenescu** [comment]
@murbanowicz The bug reported is invalid. Format is used for the label exclusively. 

What we are talking now is about 24hr material theme popover/dialog (so not talking about label anymore) which is a completely different thing. Take it as an enhancement. If you want you can open a new issue as a feature request, but this is high on the priority list as I need it also on a project, so I can't miss it :)

iOS theme already has 24hr support.
