### ISSUE TITLE
Imported file was passed to wrong loader

### ISSUE THREAD

**Issue by santyelegy** [quasarframework/quasar#15905]
### What happened?

I am new to quasar and I was trying to integrate material web components into my Quasar v1 typescript project following this tutorial:

[https://github.com/material-components/material-web/blob/main/docs/quick-start.md](url)

After I imported `@material/web/checkbox/checkbox.js` in `Index.vue`, I failed to compile with the following error:

```
 error  in ./node_modules/@material/web/checkbox/lib/checkbox.js

Module parse failed: Unexpected token (29:42)
File was processed with these loaders:
 * ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
|      */
|     get name() {
>         return this.getAttribute('name') ?? '';
|     }
|     set name(name) {

 @ ./node_modules/@material/web/checkbox/checkbox.js 8:0-45 24:42-50
 @ ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/ts-loader??ref--3-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=ts&
 @ ./src/pages/Index.vue?vue&type=script&lang=ts&
 @ ./src/pages/Index.vue
 @ ./src/router/routes.ts
 @ ./src/router/index.ts
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js
```
This imported js file was passed to `/loader.transform-quasar-imports.js`, which not seems like a proper loader for this file. I tried to search on the internet, but there are no similar issues. 

### What did you expect to happen?

Expect to successfully import `@material/web/checkbox/checkbox.js` with no compile error.

### Reproduction URL

https://codesandbox.io/s/polished-http-ms3q8v?file=/src/pages/Index.vue

### How to reproduce?

1. build a quasar v1 typescript project with quasar cli
2. use `yarn add @material/web` to add the dependency
3. add  `import '@material/web/checkbox/checkbox.js'` in a vue file
4. get the compile error

OR

1. use the above code sandbox link
2. press `ctrl+s` to save and recompile
3. get the compile error

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by freddy38510** [comment]
@santyelegy which version of Node.js are you using ?

The [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#browser_compatibility) is not supported by Node.js below v14.

I am refering to this line of code: `return this.getAttribute('name') ?? '';` which came from the [`material-web/checkbox` module](https://github.com/material-components/material-web/blob/main/checkbox/lib/checkbox.ts#L67).

Edit: you can fix this by transpiling the material-web components like this:

```javascript
// quasar.conf.js file

module.exports = configure(function (ctx) {
  return {
    // skipped code
    build: {
      // Add dependencies for transpiling with Babel (Array of string/regex)
      // (from node_modules, which are by default not transpiled).
      // Applies only if "transpile" is set to true.
      transpileDependencies: [/@material\/web/],
    },
    // skipped code
  }
})

**Comment by santyelegy** [comment]
@freddy38510 Thanks for your fast reply! My node version is v14.21.3.

The solution works on the code sandbox. But when I tried to do the same things on my local machine (windows system), I got the same error above.

To reproduce this bug, this is the code sandbox URL that work: https://codesandbox.io/p/github/santyelegy/quasar-worked/main?workspaceId=d1bd5d83-9bbc-4cb7-bd16-2ddd3717ed15
You can get the same code from https://github.com/santyelegy/quasar-worked

Step to reproduce on windows:

1. clone the code on windows
2. run `yarn install`
3. run `quasar dev`

I am using node v14.21.3 and yarn 1.22.19. My quasar info on my local machine is as follow:

![image](https://github.com/quasarframework/quasar/assets/49182613/77ecc2cf-aba4-43cd-b65b-1df3ef8bed7a)

**Comment by santyelegy** [comment]
This problem seems to come with the `\` difference with the path in Windows. I change the config to 
```
// quasar.conf.js file

module.exports = configure(function (ctx) {
  return {
    // skipped code
    build: {
      // Add dependencies for transpiling with Babel (Array of string/regex)
      // (from node_modules, which are by default not transpiled).
      // Applies only if "transpile" is set to true.
      transpileDependencies: ['/@material/web/'],
    },
    // skipped code
  }
})
```
And this can work on my computer

**Comment by freddy38510** [comment]
Yeah that's right, I forgot about windows path delimiter :s

If you want to support both windows and posix paths, you can use this RegExp `/@material[\\/]web/`.
