### ISSUE TITLE
Weird line in ssrContext warning section

### ISSUE THREAD

**Issue by Satsukevich-Dzmitry** [quasarframework/quasar#15921]
### Description

In this The ssrContext Object part in warning section you left explanation in parentheses, but it only provides more confusion. I'm not sure if this was intentional to left `true===false`, and if it was, then i guess there should be more then this, because it's confusing :)

![image](https://github.com/quasarframework/quasar/assets/68441313/a1f9bffb-c033-4c25-85b8-ab45da536dcc)

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/developing-ssr/ssr-context#usage

### Flavour

None

### Areas

SSR Mode

**Comment by freddy38510** [comment]
> The `ssrContext` Object is available only on SSR builds, on the server-side compilation (when `process.env.SERVER === true`).

The source of the doc is [here](https://github.com/quasarframework/quasar/blob/dev/docs/src/pages/quasar-cli-vite/developing-ssr/ssr-context.md?plain=1#L11).

I assume that when compiling the documentation the global constant `process.env.SERVER` was [statically replaced](https://v2.vitejs.dev/config/#define) by its value. There may be other places in the documentation where the same issue arises.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Will be fixed on next docs deployment.

**Comment by EgorGumin** [comment]
I can see the same error again in 2.13.0 docs 
![image](https://github.com/quasarframework/quasar/assets/6977652/2300352c-1087-4c16-bdef-0643bd8f0351)

@rstoenescu

**Comment by rstoenescu** [comment]
@EgorGumin 
That instance was never fixed. And missed when looking for similar cases throughout the docs.
Pushed a fix, so thanks for pinging me! Will be available on next docs deployment.
