### ISSUE TITLE
It is recommended to tab switch using show instead of if

### ISSUE THREAD

**Issue by suzhenghui-sky** [quasarframework/quasar#15950]
### What happened?

If I add A form to TAB B and then submit it in option A, the validation mechanism will not react

### What did you expect to happen?

If I add A form to TAB B and then submit it in option A, the validation mechanism will not react

### Reproduction URL

no

### How to reproduce?

no

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

**Comment by pdanpdan** [comment]
Hello. If you want that don't use tab-panels, use some other structures and use v-show.
Also validation of forms is better done on data instead of dom
