### ISSUE TITLE
Q-Select not displaying Label from option that matches v-model value

### ISSUE THREAD

**Issue by timsayshey** [quasarframework/quasar#15967]
### What happened?

Q-Select does not update the Label for matching value. For instance, the v-model value is set to 'google' and there is an option that is { value: 'google', label: 'Google' }, however the q-select just shows 'google' as the selected value, not showing the matching label, Google. Do I need to refresh the q-select component or something? Here's a reproduction of the issue:
https://codepen.io/timsayshey/pen/jOQbExQ
 

### What did you expect to happen?

I expect it to behave like a native HTML select element where it automatically displays the label of the matching form option 

### Reproduction URL

https://codepen.io/timsayshey/pen/jOQbExQ

### How to reproduce?

1. Open the Codepen Example
2. You'll immediately see the select displaying the value instead of the matching Label.

![image](https://github.com/quasarframework/quasar/assets/1148940/4da00634-1b8d-453d-bd62-974bd114d3bc)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Your value is a string. Please check the docs - it's explained and you have all the examples there

**Comment by timsayshey** [comment]
So if I pass in { value: 'google' }, will it find and match to the right option and label or do I have to pass in a copy of the Option I want? Seems like extra unnecessary work.

**Comment by pdanpdan** [comment]
No, it would not. Objects are equal if they are the same.

**Comment by RustyJoeM** [comment]
I believe examples (at least i didn't fine one that matches the case) do not address the case described by OP when "label" is not set explicitly by "label" prop as a "known" string - e.g. when list of options comes from async call...
I hit same problem in the past and haven't resolved yet myself.

In my case i have `value: int -> label: string` as my options array, and q-select shows exactly as OP describes the value instead of label when options array is populated.

(there is no "setLabel" method available?)

**Comment by timsayshey** [comment]
Adding the `map-options` prop to `q-select` solved the issue for me! That is the default behavior I would expect and makes it behave intuitively like native HTML and other libraries.

**Comment by RustyJoeM** [comment]
thanks, i have been using the `map-options` already, but in the end problem was combination of missing `options` ref variable rebind and chrome dev-tools not showing realtime ref value automatically for whatever buggy reason.
apologies for adding a bit of chaos after closing the issue, exiting now :)
