### ISSUE TITLE
QSelect only show ID

### ISSUE THREAD

**Issue by kydner** [quasarframework/quasar#15978]
### What happened?

when i use options array object, emit-value & map-options and model-value only number | string, its work, result on q-select is label from options. but if options is server-side or async, and then model-value is input first before options is ready, the label only show ID from model-value, the label will show when i click the q-select. how handle it?

### What did you expect to happen?

show label from options not ID when options server-side/async

### Reproduction URL

-

### How to reproduce?

![Screenshot_2023-06-14-23-14-40](https://github.com/quasarframework/quasar/assets/40586726/91291ba8-ded7-42d3-8b92-b3aa12de5dc5)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by pdanpdan** [comment]
And how should the label be guessed :D
