### ISSUE TITLE
[Request] Allow to specify Autocomplete setValue "value field" even when not using staticData

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#1597]
At the moment, if you use `staticData` you can choose a single field to be both the one filtered AND the one whose value get set in the parent input. If you don't use `staticData`, you are free to filter however you like BUT the field that get set in the parent input is ALWAYS the one named `value`. I would like to have a say in which field get set automatically.

For example, let's say I have this data:
`[{ label: 'foo', value: '8e4370a7-0a81-4c9a-b669-8f0d8debd87b' }, ...]`

I would use `label` both to filter and as the value of the parent input but I would use `value` in the `selected` event to save somewhere (e.g. state) the id (i.e. the value field) corresponding to that label.

https://github.com/quasarframework/quasar/blob/v0.14.8/src/components/autocomplete/QAutocomplete.vue#L167

**Comment by pdanpdan** [comment]
If you use staticData and you want to search for something else than the value that's going to be set you just have to replace the filtering function. The default one is
```javascript
export default function (terms, {field, list}) {
  const token = terms.toLowerCase()
  return list.filter(item => ('' + item[field]).toLowerCase().startsWith(token))
}
```
But I think it would be strange from a usability perspective to search for something and then display something else.

On the other hand, if you just need the full object selected then you just need to add a listener on the `selected` event:
```javascript
@selected="obj => do_something_with_object(obj)"
```

**Comment by wc-matteo** [comment]
Thanks for the answer. What about when NOT using staticData and I want to use another field other than `value`?

To be more clear, here's quasar framework `setValue` method:
```js
this[`__input${suffix}`].set(this.staticData ? result[this.staticData.field] : result.value)
```

As you can choose the field name with staticData (`this.staticData.field`), I'd like to be able to choose the field name when not using staticData (`result.value`).

**Comment by pdanpdan** [comment]
Generating the data is under your control in that case. Just put the desired value to be set under the value key. It's the same as putting the info to be displayed under label, sublabel, icon, ...

**Comment by wc-matteo** [comment]
Gotcha.
