### ISSUE TITLE
q-select closing when using q-dialog and q-tooltip

### ISSUE THREAD

**Issue by GuilhermeErmel** [quasarframework/quasar#15974]
### What happened?

There is a "bug" when I have one QSelect with one option opening a QDialog.. If inside this QDialog there is a QTooltip, when I clicking after the tooltip is visible, **the select is closing**.

Is hard to explain.. It's easier to using (codepen):
* See the difference when clicking (inside the Dialog) before the tooltip is visible and after.

### What did you expect to happen?

The select/dialog should not close

### Reproduction URL

https://codepen.io/ermel/pen/YzRyYvp

### How to reproduce?

1. Click in Select
2. Click in Button ('Click me')
3. See the difference when clicking (inside the Dialog) before the tooltip is visible and after.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.12.2
