### ISSUE TITLE
The docs should say that you need to specify width property for "ellipsis" class to have effect

### ISSUE THREAD

**Issue by BenJackGill** [quasarframework/quasar#15984]
### Description

More than once I have been confused why the `ellipsis` class is not working.

I read the docs and dig through issues and discussions until I remember that it needs a width property to also be set for it to work.

So it might be helpful to change the text on [this help doc page](https://quasar.dev/style/visibility#introduction) from this:

> Truncates text and shows ellipsis when not enough space available.

To this:

> Truncates text and shows ellipsis when not enough space available. A width must be set for ellipsis to have effect.

### Documentation Section URL

https://quasar.dev/style/visibility

### Flavour

None

### Areas

Style & Identity (quasar)

**Comment by pdanpdan** [comment]
How would you define "not enough space is available"?
You don't need to specify width, but of course the size of the container should not be infinite, else it would always be enough space.

https://codepen.io/pdanpdan/pen/LYXNOzQ?editors=1010
