### ISSUE TITLE
Unsafe Use of Target blank

### ISSUE THREAD

**Issue by Nikhaths7** [quasarframework/quasar#15982]
### What happened?

Unsafe Use of Target blank , In the application, when opening a new page using an <a> HTML element with the "target" 
attribute (with any value), or with window.open() within JavaScript, the new page has some access to the original page through the window.opener object. This may allow redirection to a malicious phishing page.

### What did you expect to happen?

The new page that opens can redirect the original page to another malicious page and abuse the trust of the user to create a very convincing phishing attack

### Reproduction URL

default/js/quasar.js

### How to reproduce?

In the application, when opening a new page using an <a> HTML element with the "target" attribute (with any value), or with window.open() within JavaScript, the new page has some access to the original page through the window.opener object. This may allow redirection to a malicious phishing page.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by bhuyan-pranab** [comment]
![image](https://github.com/quasarframework/quasar/assets/41125721/fd5343dd-12d2-44c5-8e5e-8243e5081a5f)

@pdanpdan No way to provide reproduction URL. However sending you an screen shot. The "window.open" function is highlighted in the screen shot.

Here is the link for Quasar lib: https://cdn.jsdelivr.net/npm/quasar@2.12.0/dist/quasar.umd.prod.js
