### ISSUE TITLE
Replace Ngrok with Tunnelmole in your docs for a FOSS Tunneling solution

### ISSUE THREAD

**Issue by robbie-cahill** [quasarframework/quasar#15985]
### Description

I've noticed you have ngrok as your suggested tunneling solution in a few places in your docs. However, it has a few issues
- Its closed source and proprietary
- It has to be downloaded and installed as an external dependency from [ngrok.com](https://ngrok.com)
- You can't self host ngrok and their paid plans are overpriced

So, i'd like to update your docs to use [tunnelmole](https://www.npmjs.com/package/tunnelmole) instead. It has the following advantages
- Its fully open source/FOSS with a permissive MIT license
- You can self host it for total control or use the hosted service if you want to use it right away
- It's available as an `npm` dependency, making installation and updates a lot easier for any JavaScript developer.

I'd like to update your docs to instruct users to use Tunnelmole for an easier experience.

Here's the difference in terms of set up and usage

#### Ngrok
First, download and install ngrok seperately from [ngrok.com](https://ngrok.com), then run
```js
ngrok http 3000
```

#### Tunnelmole
Install from NPM with `npm install -g tunnelmole`, then run
```js
tunnelmole 3000
```

Or run from code for more advanced setup and automations:
```js
import { tunnelmole } from 'tunnelmole';
const url = await tunnelmole({
    port: 3000
});
// url = https://idsq6j-ip-157-211-195-169.tunnelmole.com
```

Let me know if you'd like me to create a PR with these changes.

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
This would be a great addition to the docs.
Can you PR it, pls? But add it, do not replace ngrok. Our devs should decide on their own. More options is always better.

**Comment by robbie-cahill** [comment]
Sure thing, here is the PR: https://github.com/quasarframework/quasar/pull/16031

**Comment by rstoenescu** [comment]
Thanks for this ticket and the PR!
