### ISSUE TITLE
Unsafe Use of Target blank in QUASAR CDN content.

### ISSUE THREAD

**Issue by bhuyan-pranab** [quasarframework/quasar#15990]
### What happened?

Unsafe Use of Target blank , In the application, when opening a new page using an HTML element with the "target"
attribute (with any value), or with window.open() within JavaScript, the new page has some access to the original page through the window.opener object. This may allow redirection to a malicious phishing page.

### What did you expect to happen?

When invoking an untrusted new window using "var newWindow = window.open()", set "newWindow.opener=null" before setting "newWindow.location" to a potentially untrusted site, such that when the new site is open in the new window, it has no access to its original "opener" attribute.

### Reproduction URL

https://jsfiddle.net/rstoenescu/a2cuzods

### How to reproduce?

1. Go to the provided URL.
2. Open the CDN url of Quasar (https://cdn.jsdelivr.net/npm/quasar@2/dist/quasar.umd.prod.js).
3. Search for "window.open()" in the file content.
<img width="948" alt="Scr1" src="https://github.com/quasarframework/quasar/assets/41125721/3a3b862a-f9f3-4e5c-9ea4-f4db16304f72">

### Flavour

UMD

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Please do not spam here - if you would have checked the code instead of searching for strings you would have seen it is the window that is opened to print the content that is already in the page.
