### ISSUE TITLE
Disabled buttons

### ISSUE THREAD

**Issue by mariaczi** [quasarframework/quasar#160]
Hi,

I found that to have really disabled button - not only looking like disabled, 
I have to use:
```
v-bind:class="{disabled: EventIsNew}"
                        v-bind:disabled="EventIsNew"
```

If there is no `v-bind:class`, hover state is visible on button which will make user confused,
if there is no `v-bind:disabled`, obviously it is not preventing `@click` which is of course bad behaviour.

Is this nature of CSS or it can be fixed ?

***
Sorry for a lot of issues. Just trying to help you make Q awesome! :)

**Comment by rstoenescu** [comment]
Hi,

Don't worry about logging many issues, you are indeed making Q better with each.
`<button>` is not a component but a simple DOM element. This has been designed with performance in mind, just like everything in Quasar. Whenever possible for Vue not to render a component we use a native DOM element. So, for buttons there's no binding to actually make it disabled. You as a developer deal with that. You got `@click` and you got CSS class `disabled` (that can be applied to anything). Let's take your example: you add `disabled` class when EventIsNew is `true`. Your duty is to also take care of dealing with EventIsNew in your `@click` method (`if (EventIsNew) return`).
