### ISSUE TITLE
quasar parent App is undefiend

### ISSUE THREAD

**Issue by xalteropsx** [quasarframework/quasar#16009]
### Description

https://github.com/xalteropsx/parentapp

its working on 2.7.1 
![image](https://github.com/quasarframework/quasar/assets/103671642/ab010b35-67f7-46ef-ad29-d1b55dd0529e)

but on 2.12 it throw this warning 
![image](https://github.com/quasarframework/quasar/assets/103671642/38c4db48-8eec-4da9-ba1a-bdc725232e01)

i not sure which version this bug appear but i directly went from 2.7.1 to 2.12 also i create new quasar project and move my src folder into it so i am pretty sure its an bug 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

**Comment by CatsJuice** [comment]
@xalteropsx  Perhaps you forgot to config `framework.plugins` in your `quasar.config.js`. See docs [here](https://quasar.dev/quasar-plugins/loading#loading-api).

```js
// quasar.config.js
module.exports = configure(function (/* ctx */) {
    return {
        // ...
        framework: {
            plugins: ["Loading"]
        }
    }
}
```

**Comment by xalteropsx** [comment]
@CatsJuice thanks man this work but i get another issue when i try to login
![image](https://github.com/quasarframework/quasar/assets/103671642/a61cc741-d937-4a84-ac47-02ed2f4abf9b)

**Comment by CatsJuice** [comment]
> 

@xalteropsx  
I'm not pretty sure, but it may caused by `hmr`. You can try to restart dev server and reload page.

**Comment by xalteropsx** [comment]
thanks man it solved i notice i given logout link inside login page and it solved >.<  awesome
