### ISSUE TITLE
Quasar components inside templates using PascalCase

### ISSUE THREAD

**Issue by leopiccionia** [quasarframework/quasar#1601]
I've noticed that I can't use Quasar components on templates using PascalCase naming, even though it works with kebab-case.

The issue doesn't occur with my own custom components defined inside Quasar.

### Software version
Quasar: 0.15

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/14frxq99/

### What did you get as the error?
No component shown.

### What were you expecting?
`<QBtn></QBtn>` and `<q-btn></q-btn>` being equivalent.

**Comment by rstoenescu** [comment]
Hi,

This is simply how Vue works. No way around it...

**Comment by leopiccionia** [comment]
Actually, a component registered in PascalCase can be used in kebab-case, but the opposite is not true (see vuejs/vue#5581). I think supporting both (i.e. registering components names in PascalCase) would be a great convenience.

If you allow me, I can prepare a PR.

**Comment by rstoenescu** [comment]
You need to understand that using UMD/standalone you're not taking advantage of vue-loader which compiles your templates into render functions and allow kebab-case/pascal-case conversions as needed. In UMD, you're simply writing HTML that the browser can understand, after which Vue parses the HTML DOM nodes and initialises it.

Can you detail what the PR is about pls?

**Comment by leopiccionia** [comment]
Actually, I first noticed the issue on the a project managed by vue-cli, not on standalone.

---

As I said previously, if a component is registered (either globally via `Vue.component` or locally via `components`) in PascalCase, it can be used inside a template in all PascalCase, camelCase and kebab-case; but, if you register it on kebab-case, it can only be used in kebab-case (see [repro](https://jsbin.com/xurineq/2/edit?html,js,output)).

As I see [here](https://github.com/quasarframework/quasar/blob/7f2bc3252dddcb9a9f155756437491fca5382923/src/install.js#L59), the components are registered globally by the components `name` attribute, and this is kebab-case. So I basically see two ways of solving this:
1. Convert components names to PascalCase before registering.
2. Change all components name to PascalCase. This requires the change of most files, but would be more performatic.

We could benchmark to see which one is more performatic:
1. Check `c.name.startsWith('q-')` and then convert to PascalCase.
2. Check `c.name.match(/^Q[A-Z]/)`.

**Comment by rstoenescu** [comment]
Interesting.

**Comment by leopiccionia** [comment]
Yes, sure. But I'm busy, I'll try to prepare the PR on weekend.

**Comment by rstoenescu** [comment]
Please note that Vue docs say: `When using string templates however, we’re not bound by HTML’s case-insensitive restrictions` -- so it's ONLY when using string templates. JsFiddle/Codepen etc will still not work with `<QBtn>` for example.
