### ISSUE TITLE
getScrollTarget(el) only for 'el' parent

### ISSUE THREAD

**Issue by enforbAlzi** [quasarframework/quasar#16026]
### What happened?

How to get the offsetTop value of an element, but not its parent, but the wrapping element in which the element's parent is located?

HTML
```
<q-form
      ref="form"
      greedy
      no-error-focus
      no-reset-focus
      enctype="multipart/form-data"
      @submit="onSubmit"
      @reset="onReset"
      @validation-success="onValidationSuccess"
      @validation-error="onValidationError"
      class="full-width"
  >
  <div class="row q-mb-lg">
    <q-btn color="primary" icon="check" label="OK" type="submit" />
  </div>
  <q-card bordered class="full-width q-mb-lg">
    <q-card-section>
      <div class="row q-col-gutter-md">
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
      </div>
    </q-card-section>
  </q-card>
  <q-card bordered class="full-width q-mb-lg">
    <q-card-section>
      <div class="row q-col-gutter-md">
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable :rules="[val => !!val || 'Field is required']" />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable :rules="[val => !!val || 'Field is required']" />
        </div>
      </div>
    </q-card-section>
  </q-card>
  <q-card bordered class="full-width">
    <q-card-section>
      <div class="row q-col-gutter-md">
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable />
        </div>
        <div class="col-12">
          <q-input v-model="name" label="Name" stack-label outlined hide-bottom-space clearable  />
        </div>
      </div>
    </q-card-section>
  </q-card> 
</q-form>
```

and onValidationError function:
```
onValidationError(ref) {
      const el = ref.$el;
      setVerticalScrollPosition(getScrollTarget(el), el.offsetTop);
 }
```

But el.offsetTop returns the offsetTop position of the 2nd q-card. But I want the offsetTop position of the form.

### What did you expect to happen?

Possibility to set the parent according to which the offsetTop position should be taken.

### Reproduction URL

https://codepen.io/enforbalzi/pen/jOQmBwQ

### How to reproduce?

1. Go to the provided reproduction link
2. Click on 'OK'
3. The scroll should move to the error element position

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
in vue `ref` is a function that creates a ref
You must use it to create a variable (pick a name), then return that variable in `setup` function and use it in HTML template as `ref="variable_name"`
When you use it in JS you use a ref as `variable_name.value`

Please try to understand the basics first


1. you are masking the global `ref` with a ref variable in function
2. `setVerticalScrollPosition` is not defined
3. you have a `ref="form"` in template but no `form` ref is exported from setup

**Comment by enforbAlzi** [comment]
Event: @validation-error: (ref) => void
ref: Vue reference to the first component that triggered the validation error

So when I call my onValidationError(ref) I should get component where validation error.
And I want to scroll to this component. But offsetTop position is not correct.
