### ISSUE TITLE
vite plugin 1.4 can't find module types error

### ISSUE THREAD

**Issue by kalvenschraut** [quasarframework/quasar#16028]
### What happened?

Error likely only occurs if using bundler or node next/16 module resolution. For these cases need to add a types conditional export to the package.json. Will submit a PR doing so.

![image](https://github.com/quasarframework/quasar/assets/30308012/60e66294-1a53-47d0-ac78-4c638646f85b)

** Note in some cases may need to have a specific .d.cjs along with the .d.ts for module packages. I don't have a cjs project to check if it will cause any issues without one.

### What did you expect to happen?

no error

### Reproduction URL

n/a

### How to reproduce?

n/a

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

TypeScript Support

**Comment by rstoenescu** [comment]
Released quasar/vite-plugin 1.4.1 with the fix.
