### ISSUE TITLE
Error: Cannot find module 'quasar-framework' from '/'

### ISSUE THREAD

**Issue by BellenWalker** [quasarframework/quasar#1602]
Today I’m encountering this error in sandbox  that cannot find quasar-framework module, it’s working fine until this morning.
I removed this dependency and reload it, but still didn’t fix it.

When launching the application, it didn’t scan dependency folder I can see from the error log, but scanned components folder instead, turn out it couldn’t find it.
Any ideas on this? really appreciate it.

Error log:
Error: Cannot find module 'quasar-framework' from '/'
at https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2972
at p (https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2159)
at n (https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2120)
Error: Cannot find module 'quasar-framework' from '/components'
at https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2972
at p (https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2159)

**Comment by BellenWalker** [comment]
![quassar](https://user-images.githubusercontent.com/8969299/36464264-d0250352-1709-11e8-8e6d-cb084bbe8448.png)

**Comment by rstoenescu** [comment]
Hi,

1. Do you have a reproduction repo that I can take a look at? Can't see anything in codesandbox.
2. What version of Quasar are you using?
3. Why are you importing from 'quasar-framework' instead of 'quasar'?

Please reopen if replacing 'quasar-framework' with 'quasar' is not working. Thanks.

**Comment by darkscript** [comment]
not sure if its related but I had to ``publicPath: '/maps/' `` (where ``maps`` is a folder on server) on quasar.conf.js to enable access to a folder on apache server I was deploying.

**Comment by AhmedSayedSk** [comment]
i have same problem with `import Quasar from 'quasar-framework'` ver `0.16`

**Comment by rstoenescu** [comment]
"quasar-framework" npm package does not have a "main" due to the fact that each Quasar theme has its own js. So the path is either quasar-framework/dist/quasar.mat.esm.js or quasar-framework/dist/quasar.ios.esm.js. The CLI (or vue-cli-plugin-quasar) adds a webpack alias ('quasar') which points to the right file based on your theme selection.
