### ISSUE TITLE
SASS/SCSS variables list not displaying (component error)

### ISSUE THREAD

**Issue by Tenrys** [quasarframework/quasar#16043]
### Description

The list of style variables quasar uses stopped displaying at some point, and when checking the console, this is the error that pops up.

![image](https://github.com/quasarframework/quasar/assets/3979239/19b61ca6-aa0c-47e5-9c73-54b0d87d883f)

### Documentation Section URL

https://quasar.dev/style/sass-scss-variables#variables-list

### Flavour

None

### Areas

Style & Identity (quasar)

**Comment by yusufkandemir** [comment]
Thanks for reporting! 👏 The fix will be available in the next docs deployment.

**Comment by PushyPants** [comment]
For anyone coming here to looking from the same thing. They are just pulling the variables for the list directly from their node_modules folder So, if you have a project going, you can just dive into your node_modules folder and get the info you're looking for. 


Inside the doc's SassVariables component:
```
const rawVariables = import.meta.glob('./../../../../node_modules/quasar/src/css/variables.sass', { as: 'raw' })
file.value = rawVariables[ './../../../../node_modules/quasar/src/css/variables.sass' ]
```

In your IDE File Explorer, go to `node_modules/quasar/src/css/variables.sass` and you should see all the variables that used to display in the list.
