### ISSUE TITLE
Broken link on page https://quasar.dev/start/vite-plugin/

### ISSUE THREAD

**Issue by gwene** [quasarframework/quasar#16044]
### Description

On the "Vite plugin for Quasar" doc page (https://quasar.dev/start/vite-plugin/) the following sentence has a broken link:

This page will teach you to use our Vite plugin, but it’s not the same as our full-fledged [Quasar CLI with Vite](https://quasar.dev/quasar-cli-vite) under the hood.

https://quasar.dev/quasar-cli-vite  gives a 404 error.

### Documentation Section URL

https://quasar.dev/start/vite-plugin/

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by yusufkandemir** [comment]
Thanks for reporting. The fix will be available on the next docs deployment.
