### ISSUE TITLE
QSelect taking all the height available in desktop when there are too many items in options

### ISSUE THREAD

**Issue by dev-rfc** [quasarframework/quasar#16072]
### What happened?

After upgrading from 2.12.0 to 2.12.2, the QSelect was affected, it currently fills all the space on the screen when opening and having too many items in options.

![bug](https://github.com/quasarframework/quasar/assets/16182725/405eca74-0d24-4a7a-bdc2-a47c654768e8)

### What did you expect to happen?

It should open and retrains it from occupying all the space on screen

![fix](https://github.com/quasarframework/quasar/assets/16182725/d673e5a9-88a7-4a38-aa15-c42df30a12e4)

### Reproduction URL

https://codepen.io/renan-cavalieri/pen/rNQJxbp

### How to reproduce?

1) Open the reproduction link on desktop
2) Open the QSelect component.
3) The issue should be visible, like in the screenshots.
4) If you need to compare to the previous behavior, check this link instead: https://codepen.io/renan-cavalieri/pen/KKrQVLW

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
There is no need, it's reproductible even in browser using UMD.
```

**Comment by binarytide** [comment]
possibly consider `options-max-height` as a param?

**Comment by dev-rfc** [comment]
could be, but that's not the expected behavior, as it's probably a regression that happened between 2.12.0 and 2.12.2.

**Comment by metalsadman** [comment]
I think this change did it back in 2.12.1 https://github.com/quasarframework/quasar/commit/c9e43faf2f12d23935679522ddce5c50271378c2#diff-d486fe7e47b9fce07ab2252caf361429f339596767385dfdd8b53da0c72150b6R174 which was to fix (https://github.com/quasarframework/quasar/issues/11247), so even if you set `popup-content-style="max-height: 65vh;"` it will get overridden by 100vh or with the computed maxHeight when the engine recalculates.
https://codepen.io/metalsadman/pen/KKbVqVZ?editors=1010
default max-height per qmenu's css is 65vh
q v2.12.1
<img width="485" alt="image" src="https://github.com/quasarframework/quasar/assets/31038838/1d38fce3-dd79-4c37-bb7b-e4efa314b3aa">
q v2.12.0
<img width="485" alt="image" src="https://github.com/quasarframework/quasar/assets/31038838/d6eb2237-8407-41e9-ac8f-07cc23c97838">

**Comment by SeverinSenn** [comment]
Just out of curiosity, did anyone find a solution to this problem?

**Comment by stijnelskens** [comment]
Any solutions for this? I'd like to keep a max-height without it gets overwritten.
As an fixed height is no solution for this..

**Comment by stijnelskens** [comment]
A possible workaround is adding `popup-content-class="max-height-dropdown"` and define the class with `max-height: 40vh !important;`. As this doesn't get overwritten. So this is a temporary solution..

@SeverinSenn

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.17.0

**Comment by cvillagrasa** [comment]
Hi, I'm finding that:

1. Something like `popup-content-class="myClass"` is not working with Vue scoped styles. It does work with non-scoped styles, or by just using Quasar classes such as `bg-blue`, though.
2. Something like `popup-content-style="max-height: 10rem;"` does not work, either. It does work with a specific height, though, which may be related to this issue.

I'm using  Quasar v2.17.4.

**Comment by rajat6235** [comment]
Hi, what worked for me is this very simple solution  
<q-select
    popup-content-style="height: 300px;"
