### ISSUE TITLE
Missing link for download Gradle 

### ISSUE THREAD

**Issue by ikhbalfuady** [quasarframework/quasar#16076]
### Description

I have some issue to report that, when iam accessing this page : 
https://quasar.dev/quasar-cli-webpack/developing-cordova-apps/preparation#windows
https://quasar.dev/quasar-cli-vite/developing-cordova-apps/preparation#windows

in gradle link, its not correct, i found the wrong link, after that i do search manually in google, and there is the correct link
new : https://downloads.gradle.org/distributions/gradle-4.10.3-all.zip
old (in quasar doc) : https://downloads.gradle-dn.com/distributions/gradle-4.10.3-all.zip
 

### Flavour

None

### Areas

Cordova Mode

**Comment by yusufkandemir** [comment]
Thanks for reporting. I also fixed some typos and made small changes. It will be available in the next docs deployment.
