### ISSUE TITLE
q-select @remove not triggering with single selection

### ISSUE THREAD

**Issue by jobdiogenes** [quasarframework/quasar#16079]
### What happened?

when using `<q-select @remove="removeFn"  \>`  the  **removeFn** will be called only if using **multiple** option.

Could be confirmed with this
[Codepen.io](https://codepen.io/jobdiogenes/pen/xxQWOwv)

### What did you expect to happen?

Expected that in `<q-select @remove="removeFn" />`   the **removeFn** be called in standard mode (single) 

### Reproduction URL

https://codepen.io/jobdiogenes/pen/xxQWOwv

### How to reproduce?

1. add `<q-select @remove="removeFN")> </q-select>`
2. add `removeFn(op) { console.log(op) }` at **setup** section of your Vue app/component 
3. add / remove **multiple** option in ` <q-select ...></q-select>`  see console logs

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
UMD, n/a
```

### Relevant log output

```Shell
n/a
```

### Additional context

tested in UMD codepen.io

**Comment by pdanpdan** [comment]
This is how it is designed. The model is not a list so you cannot add it remove

**Comment by jobdiogenes** [comment]
> This is how it is designed. The model is not a list so you cannot add it remove
Yes, I understand that in single option model are not a list.
But, It's about clear the selection, and  even when using single selection you have the cross icon, to clear selection to select another. So, there's no reason to not emit @remove  trigger.

**Comment by jobdiogenes** [comment]
In any way, I could get similar behavior, using @change:model-value, and add a var "lastOption" that trigger changes. in the way that I could know when are cleared.
