### ISSUE TITLE
Vue 2 router scrollBehavior not working for layout views

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar#161]
In `history` mode, Vue 2 router `scrollBehavior` is only working for "top" components not using layout.

@rstoenescu should I open an issue about `scrollBehavior` and nested routes directly on vue-router or do you think it's on the Quasar side?

**Comment by rstoenescu** [comment]
I will make a statement soon about Vue Router's "history" mode. There are some technical limitations that cannot be currently overcome, the most important one being you can't build with history mode for Cordova.

**Comment by rstoenescu** [comment]
You will understand why. It's logical.

**Comment by rstoenescu** [comment]
You will be able to use history mode for websites only though. I'll write a directive for the scroll behavior which will work in both history and hash mode.

**Comment by laurentpayot** [comment]
Thanks @rstoenescu, cordova apps are not my main concern. Specially with progressive apps coming… 😉

**Comment by rstoenescu** [comment]
Then you'll be good ;) There's a progressive app starter kit on the todo list for Quasar.

**Comment by laurentpayot** [comment]
I noticed that. Can't wait! 😄

**Comment by rstoenescu** [comment]
Will update the default starter kit today ("v2") with some improvements for when using history mode. Make sure you update Quasar CLI too to generate a project and check it out.

**Comment by laurentpayot** [comment]
Will do. Will the changes in the template be easy to see so I can just modify my current project or is a start from scratch + pasting code from current project a better option?

**Comment by rstoenescu** [comment]
If you haven't touched the `/build` and `/config` folders you'll be able to simply overwrite them with the new ones rather than checking the commit and applying same changes.

**Comment by laurentpayot** [comment]
Great!

**Comment by rstoenescu** [comment]
Check it now. Commit: https://github.com/quasarframework/app-template-v2/commit/6d3980fdef99618ea609a1cc57867fdc570a2899

**Comment by laurentpayot** [comment]
I overwrote `/build` and `/config` folders, and also added the opn dependency.

Don't you think this issue should be re-opened, waiting for the directive? At least with a "feature" flag…

**Comment by rstoenescu** [comment]
Not reopening as this will duplicate: https://github.com/quasarframework/quasar/issues/72

**Comment by laurentpayot** [comment]
Ah I didn't know #72 . Ok then.

**Comment by Terumi** [comment]
I found this that works just fine 
https://www.npmjs.com/package/vue-scroll-behavior

The only issue with is that you cannot use transitions as the page jump immediately to the stored position.
