### ISSUE TITLE
The q-item within QMenu cannot be selected using the space key.

### ISSUE THREAD

**Issue by Hiroshiba** [quasarframework/quasar#16107]
### What happened?

The q-item within QMenu cannot be selected using the space key. However, selection is possible using the enter key.

### What did you expect to happen?

When the space key is pressed, it should select the item in the same way as the enter key does.

### Reproduction URL

https://codepen.io/Hiroshiba/pen/BaGPwqe

### How to reproduce?

1. Click on the menu.
2. Repeatedly press the tab key to focus on any item.
3. Press the space key.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Do you have a source for this (something official)? Please specify it.
I mean for menu items being activated by space on web.


I think I found it:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role#keyboard_interactions
