### ISSUE TITLE
Table style in doc does not correspond to real

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#16105]
### Description

In q-table I see tables look this:
![image](https://github.com/quasarframework/quasar/assets/1247062/b14b2120-7de0-473e-8160-e521355d14c0)
But in corresponding Codepen https://codepen.io/pen?&editors=111 and on my computer it looks different:
![image](https://github.com/quasarframework/quasar/assets/1247062/619b4a62-2c5b-4197-a69b-a8eb09be5879)

As you scroll bars are very different. Can you please explain to me and to users, how to connect nice looking scrollbars to table, which are already in quasar as I see in q-tree, documentation, but not work.
Why nice looking scrollbars works by default in q-tree, not in table. 

### Flavour

None

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
The scrollbars are global for the docs site.
