### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by Mohanrau** [quasarframework/quasar#1610]
### Software version

Quasar:v0.15.1
OS:win 10
Node:latest
NPM:latest
Browsers:all
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
#1609 Reopen

Everything seems fine but getting above error
Migrate from v0.14.9 using vuex & vuex-router-sync

![5](https://user-images.githubusercontent.com/1044660/36529925-b0006148-17f4-11e8-8eaf-9dc46929eda1.PNG)

sorry for that man.I was depressed do know what to do almost spending 1 full day.Here i attach with more details.

**router/routes.js**
```const MODULE_PATH = '/auth/'

export default [
  {
    path: MODULE_PATH,
    component: () => import('src/application/login/components/Auth'),
    redirect: MODULE_PATH + 'connector',
    name: 'Auth',
    meta: {
      title: 'Login.sideMenu.auth.title',
      menuItem: true,
      requiresNotAuth: true
    },
    children: [
      {
        path: MODULE_PATH + '/reset-password/:key',
        component: () => import('src/application/login/components/ResetPassword'),
        name: 'Reset Password',
        meta: {
          menuItem: false,
          requiresNotAuth: true
        }
      },
      {
        path: MODULE_PATH + 'connector',
        component: () => import('src/application/login/components/Connector'),
        name: 'connector',
        props: true,
        meta: {
          menuItem: false,
          requiresNotAuth: true
        }
      },
      {
        path: MODULE_PATH + 'login/admin',
        component: () => import('src/application/login/components/Admin'),
        name: 'Admin',
        props: true,
        meta: {
          menuItem: false,
          requiresNotAuth: true
        }
      },
      {
        path: MODULE_PATH + 'update/link/:email/:token',
        component: () => import('src/application/login/components/Admin'),
        name: 'Update From Mail Link',
        props: true,
        meta: {
          menuItem: false,
          requiresNotAuth: true
        }
      },
      {
        path: MODULE_PATH + 'reset',
        component: () => import('src/application/login/components/Admin'),
        name: 'Reset',
        props: true,
        meta: {
          menuItem: false,
          requiresNotAuth: true
        }
      },
      // Remove in production
      {
        path: MODULE_PATH + 'register',
        component: () => import('src/application/login/components/Register'),
        name: 'Register',
        meta: {
          title: 'Register',
          icon: 'assignment_ind',
          menuItem: true,
          requiresNotAuth: true
        }
      }
    ]
  }
]
```

**router/index.js**

```import Vue from 'vue'
import VueRouter from 'vue-router'

import { routes } from 'src/application/'
import { requireAuth } from '../services/authService'
import navStore from '../services/navigationService'

Vue.use(VueRouter)

// Init router defaults
const Router = new VueRouter({
  mode: process.env.VUE_ROUTER_MODE,
  base: process.env.VUE_ROUTER_BASE,
  linkActiveClass: 'open active',
  scrollBehavior: () => ({ y: 0 }),
  routes
})

// Capture route transition
Router.beforeEach((to, from, next) => {
  // Scroll top
  // document.documentElement.scrollTop = 0
  // document.body.scrollTop = 0
  // Check meta.requiresAuth if yes allow user to next level
  if (to.matched.some(record => record.meta.requiresAuth)) {
    if (!requireAuth()) {
      return next({path: '/auth'})
    } else {
      return next()
    }
  }
  // Access public pages
  if (to.matched.some(record => record.meta.requiresNotAuth)) {
    if (requireAuth()) {
      return next({path: '/'})
    }
  }
  // Pass selected route details through meta title,icon & etc..
  if (to.meta) {
    navStore.set(to.meta)
  }
  next()
})
export default Router
```

**Component folder structure**

![6](https://user-images.githubusercontent.com/1044660/36530136-3ee3a730-17f5-11e8-8c3a-22739a6b6e71.PNG)

**Comment by Mohanrau** [comment]
Issue solved.
vue-router package clash, since quasar itself by default includes all vue related packages.My bad im upgrading from v0.14.9 forgot to remove vue-router from package.json.

**Comment by stegithub** [comment]
> Issue solved.
> vue-router package clash, since quasar itself by default includes all vue related packages.My bad im upgrading from v0.14.9 forgot to remove vue-router from package.json.

i've this problem with qcheckbox, i don't understand how to solve. I cannot remove vue router, how can i import then?

**Comment by hawkeye64** [comment]
@stegithub You don't need Vue, Vue-router, Vuex, etc, as Quasar includes them automatically for you. If you have these in your package.json, simply remove them and rebuild node_modules.

**Comment by stegithub** [comment]
> @stegithub You don't need Vue, Vue-router, Vuex, etc, as Quasar includes them automatically for you. If you have these in your package.json, simply remove them and rebuild node_modules.

i'm using quasar vue plugin, and if i remove vue-router from package and rebuild i cannot import 'vue-router'...is not found package

**Comment by stegithub** [comment]
i don't understand why q-btn and more others components have not this problem and q-checkbox yes.

**Comment by hawkeye64** [comment]
@stegithub Sorry, I didn't get that it was quasar vue-cli plugin. I think your issue is different from the one originally posted here.
