### ISSUE TITLE
https://quasar.dev always serve old versio.

### ISSUE THREAD

**Issue by mrchoke** [quasarframework/quasar#16125]
### Description

When I open https://quasar.dev/, it always serves me the old version. However, if I press shift + reload, it will show me the new version.

I noticed this behavior while accessing the Quasar website. It seems that the regular way of opening the site displays an outdated version, which can be frustrating when I'm trying to access the latest information or features. Fortunately, I discovered a simple workaround to ensure that I see the most up-to-date version of the website.

By pressing shift + reload (or shift + F5), the browser performs a hard refresh, forcing it to fetch all the resources from the server again, rather than using cached files. This effectively bypasses any locally stored data that might be causing the website to load the old version.

![Screenshot 2023-07-29 at 22 07 14](https://github.com/quasarframework/quasar/assets/3403645/ea830611-3d23-48cd-89f0-6ea18d7f34a3)

### Documentation Section URL

https://quasar.dev/

### Flavour

None

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
You had a bad cache. It could not happen more than once. If it did then check your browser, extensions, proxy, network.
PWAs work by caching the website și that in next reload it loads from cache. After loading it checks for new versions and loads it (it shows a message to reload)
