### ISSUE TITLE
Sorting not working when pagination props is added 

### ISSUE THREAD

**Issue by suraj740** [quasarframework/quasar#16133]
### What happened?

Column sorting is not working as expected when pagination props is added to the table.

### What did you expect to happen?

Sorting should work with pagination props

### Reproduction URL

https://codepen.io/suraj740/pen/vYQbBWN?editors=101

### How to reproduce?

Go to the provided reproduction link,
then click on the sort icons, nothing happens there.

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by pdanpdan** [comment]
- you bind only the prop, without event to update (so pagination is not updated) - this would be important if not using server side requests
- you are using server side requests - you make the data as you want on server-side (outside the component)

**Comment by Suraj-Gupta-ML** [comment]
Thanks for the info @pdanpdan , could you pls tell me which event needs to be added here. so it should work
