### ISSUE TITLE
[0.15] i18n : Components not refreshing?

### ISSUE THREAD

**Issue by sarndt** [quasarframework/quasar#1613]
### Software version

Quasar: 0.15.0
OS: MacOS High Sierra
Node: v9.5.0
NPM: 5.6.0
Browsers: Firefox Dev (59.0b11 (64-Bit)

### JsFiddle (for Quasar v0.15+ only)

I would have given a fiddle here, but i can't seem to get the import for the language files working.

### What did you get as the error?
Using quasar's new i18n features as described in the [docs](http://quasar-framework.org/components/internationalization.html). More precisely, I tried to get dynamically retranslated data tables, that is if I change a language in a selection box (like in the docs), I would expect to instantaniously get a translation for the labels of my quasar component (in this case, a Datatable).

Instead, label update only follows after I use the component.
For the Datatable example, the label for `Rows per page` only updates, when I choose another amount of rows per page via the selection box.

### What were you expecting?
That my data table changes the language to the one I selected instantaniously.

### What steps did you take, to get the error?
1. Create a table component
2. Create an internationalization selection box, like in the [docs](http://quasar-framework.org/components/internationalization.html).
3. Switch languages and watch the table component not update the labels
4. Switch 'rows per page' to some other value
5. Observe label change to selected language

**Comment by rstoenescu** [comment]
It works just fine... http://www.giphy.com/gifs/cPY1QbhiSW7j5chSYm

**Comment by sarndt** [comment]
@rstoenescu I've tried it again, this time with a minimal working example [here](https://github.com/sarndt/bug_quasar_i18n_reactive)

It only updates after I do something with the table, no matter which browser (Chrome, Safari, Firefox) I try. Maybe I misunderstood the docs, but I pretty much did exactly what was written there (see page/index.vue)

**Comment by rstoenescu** [comment]
I think I found something. Will keep you posted. Thanks.

**Comment by rstoenescu** [comment]
Fixed it. Will be available in 0.15.3. There was indeed a issue. Thanks for reporting!

**Comment by sarndt** [comment]
Thanks for fixing it so quickly!
It's a pleasure to work with quasar :)
