### ISSUE TITLE
svg:not(:root) specificity (normalize.sass needs to be updated)

### ISSUE THREAD

**Issue by AlexDaniel** [quasarframework/quasar#16132]
### What happened?

When combining Quasar with BabylonJS, normalize.sass styles are breaking the Node Material Editor in BabylonJS.

### What did you expect to happen?

Quasar's css corrections should be neutral for most other libraries.

### Reproduction URL

.

### How to reproduce?

1. Start a Quasar project
2. Add BabylonJS to it
3. Start the frontend and open the node material editor
4. Drag the nodes around
5. You'll see that the node connections are clipped

Actually, easier said than done… It's pretty straightforward but takes some time. Given that the fix is already in normalize.css, please let me know if I should actually provide something for reproducing this.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Firefox, Chrome

### Additional context

Please see this ticket:
* https://github.com/BabylonJS/Babylon.js/issues/14100

What happens is that BabylonJS is using an `<svg>` element that is arbitrarily sized, and then it expects the rendered elements to overflow.

However, `quasar` sets this style:
```
svg:not(:root)
  overflow: hidden
```

Which seems to change the default expectation. Therefore, content gets clipped.

This issue has been raised in normalize.css:
* https://github.com/necolas/normalize.css/issues/718

And it was resolved by this commit:
* https://github.com/necolas/normalize.css/commit/004d58b2f2e0ac3d03d075f8de46ce7c8234742f#diff-289feb25fbea45a1454d7fe3d646acecfe2a3ee873c72a28b17dd00f1d06f7d6L222

However, that change was not ported to Quasar yet. I think it should be.

**Comment by rstoenescu** [comment]
Hi,

Thanks for bringing this up. Will be fixed in the next release.
