### ISSUE TITLE
Icon documentation seems inaccurate

### ISSUE THREAD

**Issue by R0N1n-dev** [quasarframework/quasar#16137]
### Description

Instructions for webfont icons not working for lineawesome
![Screenshot from 2023-08-02 11-04-14](https://github.com/quasarframework/quasar/assets/83344872/1e47327c-f15e-4d02-b907-5130a3e67fed)
![Screenshot from 2023-08-02 11-12-54](https://github.com/quasarframework/quasar/assets/83344872/35820164-ffb5-4ade-ae6b-f183964efd5c)

### Documentation Section URL

https://quasar.dev/vue-components/icon

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar Extras (@quasar/extras)

**Comment by pdanpdan** [comment]
What instructions? What are you using? What ...?
