### ISSUE TITLE
QMenu styles not being injected in Firefox

### ISSUE THREAD

**Issue by archduck** [quasarframework/quasar#16134]
### What happened?

I have a QBtn with a QMenu as a direct descendant. In Firefox, clicking the QBtn does not open the QMenu. It does not inject the necessary styles into `.q-menu` for this to happen.

In Chromium, when clicking the QBtn, `.q-menu` receives the inline styles `--q-transition-duration: 300ms; top: 71.4844px; left: 1487px; visibility: visible; min-width: 169.719px; max-width: 203px;`. In Firefox, however, the only style which `.q-menu` receives is `--q-transition-duration: 300ms;`.

The class `.q-position-engine` appears together with `.q-menu` and one of its declarations is `visibility: collapse`. This _should_ get overridden by `visibility: visible` when QBtn is clicked, but this style doesn't get injected in Firefox (at least in this case; I haven't systematically investigated every possible scenario).

In addition, because the `top` declaration doesn't get injected, the `.q-menu` is situated below the viewport.

### What did you expect to happen?

When clicking a QBtn with a QMenu descendant, the QMenu should open, regardless of the browser one is using.

### Reproduction URL

https://codepen.io/lekkertje/pen/qBQgWgE

### How to reproduce?

1. Open Firefox
2. Click on a QBtn which has a QMenu inside of it

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by archduck** [comment]
See the codepen at https://codepen.io/lekkertje/pen/qBQgWgE

**Comment by pdanpdan** [comment]
You set `class="flex column"` on QList (the content of the menu) and firefox will make the content 0x0px size

I don't know which is the wrong behaviour, and if it's firefox it'll never be fixed anyway :):
- firefox makes it 0x0px
- chrome-based makes it fill space

But that classes do not make any sense there. If you want to obtain some specific result please specify.

https://codepen.io/pdanpdan/pen/oNQmjpZ
