### ISSUE TITLE
QSelect @new-value event calling done() with no params does not empty the input box as described in the docs

### ISSUE THREAD

**Issue by vincemammoliti** [quasarframework/quasar#16159]
### What happened?

With reference to the docs (https://quasar.dev/vue-components/select#the-new-value-event), on the @new-value event "Calling done() with no parameters simply empties the input box value". However, this is not working as described.

Take the "Generating multiple values" example from the docs (https://quasar.dev/vue-components/select#example--generating-multiple-values). As you type in the input, and hit Enter to add the new value, the input box does not empty, but rather it keeps the typed text, which disrupts the flow for adding additional values.

### What did you expect to happen?

The input box should be cleared, as intended, by calling the done() callback of the @new-value event without parameters, or by supplying _null_ as a parameter as shown in the "Generating multiple values" example from the docs.

### Reproduction URL

https://quasar.dev/vue-components/select#example--generating-multiple-values

### How to reproduce?

1. Go to the "Generating multiple values" example in the QSelect docs.
2. Type in "abc" to the input box.
3. Hit the Enter key.
4. See that "abc" is shown as a QChip. However, the input box is not cleared, which is still also showing "abc".

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fix will be available in next release
