### ISSUE TITLE
q-tab click event handler has no 'go' argument anymore

### ISSUE THREAD

**Issue by jumpapex** [quasarframework/quasar#16151]
### What happened?

we have used q-tabs, q-tab and q-tab-panels to implement something like property pages.
Also we handle q-tab @click event to do some validatation before switch tab panel.

```
e.g.
    async tab_clicked(e, go) {
      e.preventDefault()
      if (this.$refs.generalPage) {
        const generalDone = await this.$refs.generalPage.validate()
        if (generalDone) {
          go()
        }
        return
      }
    ...
  }

```
It works well with quasar 2.7.1, but not work with 2.12.3

Finally, I have found that version 2.12.3 has changed the logic, it just update the tab model anyway and will not call click with 'go' argument.

### What did you expect to happen?

q-tab click event handler should not update the tab model if e.defaultPrevented is set to true and has 'go' argument.
or 
is there any workaround for it(I don't want to use q-route-tab:))

### Reproduction URL

https://codepen.io/tangram7/pen/PoxgRMO?editors=1011

### How to reproduce?

From the URL, 
click "MAIL" tab, should switch to it(but console log 'go' is undefined, and q-tabs switch the tab anyway).
click "ALARM" tab, should not switch to it.
click "MOVIES" tab, should switch to it(but console log 'go' is undefined, and q-tabs switch the tab anyway).

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by metalsadman** [comment]
in the docs @click event is only for QRouteTab, if you want to control navigation use QTabs `:model-value="model" @update:model-value="handler"` do your validation in the handler, and mutate your qtabs model accordingly.
