### ISSUE TITLE
[15.0] vuelidate plugin not working

### ISSUE THREAD

**Issue by mygnu** [quasarframework/quasar#1616]
### Software version

Quasar: 15.0
OS: linux
Node: 8.9.4
NPM: 5.6.0
Browsers: all

### What did you get as the error?
```Error in event handler for "click": "TypeError: this.$v is undefined"```
### What were you expecting?
vuelidate plugin to work, and this.$v to be available in component file, worked fine in 14.9
### What steps did you take, to get the error?
```javascript
// vuelidate.js
// import something here
import Vuelidate from 'vuelidate';
// leave the export, even if you don't use it
export default ({ app, router, Vue }) => {
  Vue.use(Vuelidate);
};

```

```javascript
// config file
module.exports = function(ctx) {
  return {
    plugins: ['axios', 'vuelidate'],
    css: ['app.styl'],
    extras: [
      ctx.theme.mat ? 'roboto-font' : null,
      'material-icons'
      // 'ionicons',
      // 'mdi',
      // 'fontawesome'
    ],.....
```

**Comment by rstoenescu** [comment]
What does this has to do with Quasar?

Most likely the file in which you are using Vuelidate (the one with `$v` doesn't have the proper initialisation required by Vuelidate). If you will copy paste your file here we can help. Otherwise, Vuelidate is working fine....

**Comment by mygnu** [comment]
following is the working code in v0.14.9 I'm trying to port.
according to vuelidate documentation $v.touch() method should be available in components.
https://monterail.github.io/vuelidate/#sub-v-values
```javascript
submit() {
      this.$v.form.$touch();
      if (this.$v.form.$error) {
        // Toast.create.negative('Please review the field[s] and try again.');
        return;
      }
      this.authenticate(this.form)
        .then(({ user }) => {
          // Toast.create.positive('Welcome: ' + user.name);
          this.$router.push({ path: '/' });
        })
        .catch(e => {
          if (e.type === 'Validation errors') {
            e.errors.map(r => {
              if (typeof r.msg === 'string') {
                // Toast.create.negative(r.msg);
              }
            });
          }
        });
    }
```

**Comment by mygnu** [comment]
issue resolved, had a typo in the validations bloc

**Comment by rwrz** [comment]
For anyone appearing here, and is tired, and can't find the reason, there is TWO plugins on quasar.conf.js, one for APP (where vuelidate should be) and one on BUILD (don't put it here). Cya! 💯
