### ISSUE TITLE
Setup function called multiple times with router-views and keep-alive

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#16164]
### What happened?

When using keep-alive with router-views the setup function is called multiple times.
Following structure:
```
-MainLayout
 -AppPage
  -AppOnePage
    -ChildOne
    -ChildTwo
    -ChildThree
  -AppTwoPage
    -ChildOne
    -ChildTwo
    -ChildThree
  -AppThreePage
    -ChildOne
    -ChildTwo
    -ChildThree
```

The problem is that the setup function of all Child pages is called more often than once.

### What did you expect to happen?

The setup function should be called exactly one time for each component.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-2jj1tx?file=src%2Frouter%2Froutes.js

### How to reproduce?

1. Click appOne
2. Click appChildOne -> setup function called 2 times for appChildOne
3. Click appTwo
4. Click appChildOne -> setup function called 3 times for appChildOne
5. From this point on, all setup functions in all childs are called 3 times

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by rstoenescu** [comment]
Hi,

This is at best a Vue problem (Vue itself, or even Vue Router), but has nothing to do with Quasar.
