### ISSUE TITLE
Error update to quasar v0.15.1 not run command " npm run dev "

### ISSUE THREAD

**Issue by diepvv** [quasarframework/quasar#1617]
### Software version
I update to quasar V0.15.1 in order to fix error modal in version 0.14.9. But after I update to V.0.15.1 by comand " npm install --save quasar-framework@latest" is ok. But after I run "npm run dev" comand line show error can't run because 
" These dependencies were not found:
* quasar in ./src/main.js
* quasar/dist/quasar.mat.css in ./src/main.js
To install them, you can run: npm install --save quasar quasar/dist/quasar.mat.css
" 
After I run " npm install --save quasar quasar/dist/quasar.mat.css " but not Ok. 
Please support me. thanks you

**Comment by diepvv** [comment]
![1111](https://user-images.githubusercontent.com/13696409/36577311-261b7d92-1889-11e8-951d-f53ac7e43ef1.PNG)

**Comment by diepvv** [comment]
![image](https://user-images.githubusercontent.com/13696409/36577326-4785c8b6-1889-11e8-9ed9-4599c8a1aa6b.png)

**Comment by pdanpdan** [comment]
http://quasar-framework.org/guide/quasar-upgrade-guide.html#Upgrading-to-Quasar-v0-15

**Comment by rstoenescu** [comment]
Please follow the upgrade guide that @pdanpdan pointed out for upgrading to v0.15. Thanks.

**Comment by ibsenleo** [comment]
if i would like to stick to 0.14 (the case is i change my pc and now have no time to migrate, but i can't find 0.14 quasar-cli version) how can i do it? where can i download it until have some time to migrate
