### ISSUE TITLE
Reactivity issue with q-input append slot for toggling visibility icon

### ISSUE THREAD

**Issue by kkurt** [quasarframework/quasar#16172]
### What happened?

I encountered an issue related to the reactivity of the append slot in the q-input component. Specifically, the problem arises when using the toggle functionality for password visibility, as demonstrated in the [password with toggle example](https://quasar.dev/vue-components/input#example--input-types) in the official documentation.

### What did you expect to happen?

Upon the second click, the icon should revert to the "visibility_off" state, indicating that the password is hidden.
The icon remains in the 'visibility' state, and does not toggle back to the "visibility_off" state.

### Reproduction URL

https://codepen.io/K-rat-Kurt/pen/RwqmLWB
https://quasar.dev/vue-components/input#example--input-types

### How to reproduce?

1. Navigate to the [password with toggle example](https://quasar.dev/vue-components/input#example--input-types).
2. Click on the eye icon in the q-input component to toggle password visibility. The icon successfully changes to the 'visibility' state.
3. Click on the eye icon again to revert the password visibility.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Firefox, Chrome, Safari

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.15.0

Global packages
  NPM - 8.19.2
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.46.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - ***
  Ethernet - 192.168.1.23
  VMware Network Adapter VMnet1 - 192.168.80.1
  VMware Network Adapter VMnet8 - 192.168.174.1
  vEthernet (Default Switch) - 172.29.48.1
  vEthernet (WSL) - 172.26.16.1
```

**Comment by metalsadman** [comment]
I can't reproduce it.

**Comment by rstoenescu** [comment]
Can't reproduce it either.
What browser and (exact version) are you using? Make sure you don't have any browser extensions tampering with the browser.

**Comment by rstoenescu** [comment]
Please reply with the answer to the question above and we will reopen the ticket. Otherwise none of us can reproduce it so nothing can be fixed.
