### ISSUE TITLE
404 when selecting "view source" on quasar site

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#1619]
On the quasar site looking at components/layout and then selecting `view source` the link gets a 404:
https://github.com/quasarframework/quasar-play/tree/master/src/pages/showcase/layout/layout.vue

**Comment by rstoenescu** [comment]
This has already being fixed. Waiting for today's live update along v0.15.2.
Please use the Docs repo to submit bugs regarding the docs website.
