### ISSUE TITLE
Ripple only refers to a type

### ISSUE THREAD

**Issue by freakzlike** [quasarframework/quasar#16190]
### What happened?

After updating quasar from `2.12.2` to `2.12.4` I face several typescript issue in relation with the options and directives. One of the Issues already mentioned in https://github.com/quasarframework/quasar/issues/16046. 

Changing the config from `2.12.2`
```typescript
createApp(App)
  .use(Quasar, {
    directives: {
      Ripple
    }
  })
```

with some type-cast to `2.12.4` still shows `Ripple` with an error message:
```typescript
createApp(App)
  .use(Quasar, {
    directives: {
      vRipple: Ripple
    } as QuasarDirectives
  })
```

`TS2693: 'Ripple' only refers to a type, but is being used as a value here.`

### What did you expect to happen?

Quasar config to not change and still work with

```typescript
createApp(App)
  .use(Quasar, {
    directives: {
      Ripple
    }
  })
```

### Reproduction URL

https://stackblitz.com/edit/github-wnaybl?file=src%2Fmain.ts

### How to reproduce?

1. Open production link 
2. Typescript issue should be displayed directly on `Ripple`
3. You can run `npm run type-check` as well

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Directives (quasar), TypeScript Support

### Additional context

The bundled `index.d.ts` on `2.12.2` had the following code which no longer exists in `2.12.4`
```typescript
// ...
export const Mutation: Mutation;
export const Ripple: Ripple;
export const Scroll: Scroll;
// ...
```

**Comment by yusufkandemir** [comment]
Thanks for reporting, the fix will be available in the next release of the `quasar` package.
