### ISSUE TITLE
Quasar build with parameters

### ISSUE THREAD

**Issue by mlenormand** [quasarframework/quasar#162]
How to build my Quasar app with parameters, for example the API URL to used by the webapp (can be different between environments dev/staging/production) ?

**Comment by rstoenescu** [comment]
Check `config/index.js`. You got `proxyTable: {}`. Then check `build/script.dev.js`. Search for `proxyMiddleware`. Documentation available at https://github.com/chimurai/http-proxy-middleware.
Example:
```js
proxyTable: {
      // proxy all requests starting with /api
      '/api': {
        target: 'https://your-api.url/api',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    }
```

That's only for while developing. For production, it's your responsibility -- you may have to use CORS calls.

Please use the forum for questions. Thanks and hope it helps!

**Comment by mlenormand** [comment]
But how can we have the API URL different in dev mode and in production mode ?
For example while developing the webapp must point to localhost and in production it must point to myapp.com.

**Comment by rstoenescu** [comment]
Use `if (process.env.NODE_ENV === 'production')`

**Comment by thiagoreri** [comment]
I'm having trouble making this setup. Changed the current version of quasar?

**Comment by rstoenescu** [comment]
@thiagoreri Please use Discord for questions. There's a flourishing community that will help you. But before that, read the docs. Thanks.

**Comment by hugetiny** [comment]
Discord can't be accessed even I used a proxy.
Don't know why......

**Comment by smolinari** [comment]
We also have a forum. https://forum.quasar.dev

Scott
