### ISSUE TITLE
QRating color-selected property is typed as NamedColor|undefined

### ISSUE THREAD

**Issue by 1tkd** [quasarframework/quasar#16204]
### What happened?

In Quasar version 2.14.4, when I provided an array like ['green'] to the 'color-selected' property of QRating, I encountered a TypeScript type error.
It seems that the 'color-selected' property is typed as NamedColor|undefined.
However, it used to be string|array, and the latest documentation also indicates string|array.
Furthermore, it appears that NamedColor does not support arrays.
And, the 'color-selected' property is one that needs to be able to specify multiple colors.

### What did you expect to happen?

I expect that no TypeScript errors will occur.

### Reproduction URL

https://I.couldnt.reproduce.the.TypeScript.error

### How to reproduce?

1.create quasar project(npm init quasar + typescript + default) => quasar version == 2.12.4 
2.edit IndexPage.vue like
... ></example-component>
 +   <q-rating
 +    :color-selected="['green']"
 +    >
</p-page>....

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.12.5
