### ISSUE TITLE
Q-Editor erroneous line-break with Firefox and Safari

### ISSUE THREAD

**Issue by dlbass** [quasarframework/quasar#16214]
### What happened?

In Firefox and Safari (including iOS Capacitor builds) Q-Editor has a `<br>` that can only be removed while in the direct editing mode. This allows users to inadvertently save 'empty' values when using a validator like Vuelidate's `required`.

Behavior in Firefox:
<img width="215" alt="image" src="https://github.com/quasarframework/quasar/assets/4282090/fb32e87f-51aa-4f73-a244-9e58afdf3e77">

### What did you expect to happen?

The behavior in Chrome results in an empty string `''` when the user has erased all content. This makes sense, and is easily validated.

Behavior in Chrome:
<img width="245" alt="image" src="https://github.com/quasarframework/quasar/assets/4282090/bad1a129-9317-4173-a241-cc425d869ad2">

### Reproduction URL

https://quasar.dev/vue-components/editor#qeditor-api

### How to reproduce?

1. Go to the provided reproduction link using Firefox or Safari
2. Erase the "default editor" example content
3. See that `<br>` is shown in the raw output

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Safari, iOS

### Quasar info output

```Shell
quasar info

Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.16.0

Global packages
  NPM - 9.5.1
  yarn - 1.22.19
  @quasar/cli - 2.2.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite    
  @quasar/extras - 1.16.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.1.0 -- Official ESLint plugin for Quasar 
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.1
  pinia - Not installed
  vuex - 4.1.0 -- state management for Vue.js
  vite - Not installed
  @capacitor/core - 4.6.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 4.6.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 4.6.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 4.6.1 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  @quasar/quasar-app-extension-qcalendar - 4.0.0-beta.16 -- A Quasar App Extension for @quasar/quasar-ui-qcalendar
```

**Comment by dlbass** [comment]
> Hi @dlbass! 👋
> 
> It looks like you provided an invalid or unsupported reproduction URL. Do not use any service other than [Codepen](https://codepen.io), [jsFiddle](https://jsfiddle.net), [StackBlitz](https://stackblitz.com), [Codesandbox](https://codesandbox.io), and [GitHub](https://github.com). Make sure the URL you provided is correct and reachable. You can test it by visiting it in a private tab, another device, etc. Please **edit your original post above** and provide a valid reproduction URL as explained.
> 
> Without a proper reproduction, your issue will have to get closed.
> 
> Thank you for your collaboration. 👏

You are incorrect, Mr. Bot. 
My reproduction URL is valid. 
I invite you to use your bot skills to recreate the reproduction as you see fit on your own time.

**Comment by rstoenescu** [comment]
Hi,

Like we mentioned a lot of times, QEditor relies on the document.execCommand() to generate/change the editable content. We are the mercy of the browser in regards to this behavior. Nothing we can do to change it.
