### ISSUE TITLE
npx+quasar+electron-builder = bad news

### ISSUE THREAD

**Issue by rotu** [quasarframework/quasar#16228]
### Description

There is a recommendation to run `quasar` under `npx` but this causes the build process to hang if there are native dependencies to rebuild:

https://github.com/electron-userland/electron-builder/issues/6411

I'm not sure whether this needs a fix/workaround in Quasar but it deserves at least a warning.

### Documentation Section URL

https://quasar.dev/start/quasar-cli#running-without-the-global-quasar-cli

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Electron Mode

**Comment by rotu** [comment]
Root cause https://github.com/npm/cli/issues/6662 is now fixed in [npm@10.1.0](https://github.com/npm/cli/releases/tag/v10.1.0)!

**Comment by rstoenescu** [comment]
Closing since it's not a Quasar CLI issue, but an npm one.
Please comment if I am missing anything.

**Comment by rotu** [comment]
@rstoenescu Yes, it's an npm issue that impacts Quasar. As with most software issues, the bug is easy to trip over without knowing the root cause or that it's a bug and not [user error](https://en.wikipedia.org/wiki/User_error).

I added it here because I thought it might merit either:

1. A word in the documentation [which currently mentions running Quasar under `npx`](https://quasar.dev/start/quasar-cli#how-quasar-cli-works).
2. A workaround e.g. by fixing up the environment variable `$npm_execpath` if pointing to something other than an instance of `npm` or `yarn`.
3. A contextual warning if the user is running quasar build and `npm` is <10.1

I trust your judgement in whatever is most in line with Quasar CLI's DX philosophy
