### ISSUE TITLE
Component tests in this repo keeps failing and couldn't pass Vue Ecosystem CI

### ISSUE THREAD

**Issue by haoqunjiang** [quasarframework/quasar#16225]
### What happened?

Vue Ecosystem CI for Quasar has been failing since June 26th. (The June 23rd run passed.)
Cypress Component Testing fails on any non-trivial test files. E.g. `QBtn.cy.js` passes but `QBreadcrumbs.cy.js` fails.

### What did you expect to happen?

All tests should pass.

### Reproduction URL

https://github.com/vuejs/ecosystem-ci/actions/runs/5922157678/job/16055740376#step:7:1393

### How to reproduce?

Checkout this repo, run:

```zsh
yarn
yarn vue-ecosystem-ci:build
yarn vue-ecosystem-ci:test
```

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome, Electron

### Quasar info output

```Shell
N/A
```

### Relevant log output

```Shell
Running:  breadcrumbs/__tests__/QBreadcrumbs.cy.js                                       (5 of 25)
  Failed to load url /@fs/quasar/dist/quasar.esm.js (resolved id: quasar/dist/quasar.esm.js) in /home/runner/work/ecosystem-ci/ecosystem-ci/workspace/quasar/quasar/ui/src/components/breadcrumbs/__tests__/BasicBreadcrumbs.vue. Does the file exist?
  Failed to load url /@fs/quasar/dist/quasar.esm.js (resolved id: quasar/dist/quasar.esm.js) in /home/runner/work/ecosystem-ci/ecosystem-ci/workspace/quasar/quasar/ui/src/components/breadcrumbs/__tests__/BasicBreadcrumbs.vue. Does the file exist?
  
  
    1) An uncaught error was detected outside of a test
  
    0 passing (297ms)
    1 failing
  
    1) An uncaught error was detected outside of a test:
       TypeError: The following error originated from your test code, not from Cypress.
  
    > Failed to fetch dynamically imported module: http://localhost:5173/__cypress/src/@fs/home/runner/work/ecosystem-ci/ecosystem-ci/workspace/quasar/quasar/ui/src/components/breadcrumbs/__tests__/QBreadcrumbs.cy.js
  
  When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
  
  Cypress could not associate this error to any specific test.
  
  We dynamically generated a new test to display this failure.
```

### Additional context

According to the error logs and the comments in this file: https://github.com/quasarframework/quasar/blob/583676d312ef498d69211ebe299303c3c1056098/ui/dev/quasar/dist/quasar.esm.js

It seems that the workaround in that file no longer worked as expected after certain changes between June 23rd and 26th.

**Comment by rstoenescu** [comment]
Hi,

Thanks for opening this ticket. Identified and fixed the issue. Can you test again, please?

**Comment by haoqunjiang** [comment]
Thanks! This error is gone now.
~~There's a new failing test, but I guess it's a real regression from Vue's side that is caught by the CI?
https://github.com/vuejs/ecosystem-ci/actions/runs/5934968486/job/16092649095#step:7:2818~~

**Comment by haoqunjiang** [comment]
I've rerun the test, and everything works like a charm! Thanks for the quick fix!

**Comment by rstoenescu** [comment]
Thank you for opening this ticket!
