### ISSUE TITLE
quasar use capacitor mode not work

### ISSUE THREAD

**Issue by mfinity168** [quasarframework/quasar#16220]
### What happened?

Hi there

I create new project with command "npm init quasar" and choose create step by step
then I use command "quasar mode add capacitor && quasar dev -m capacitor -T ios".
then Xcode open. I run app to open Simulator iPhone.  but it not work . App open but Blank screen and show error

I use quasar v2.12.5 (Vue 3) and more this plugins
"@capacitor/app": "5.0.6"
"@capacitor/cli": "5.2.3"
"@capacitor/core": "5.2.3"
"@capacitor/ios": "5.2.3"
"@quasar/extras": "1.16.5"

See error Image
https://drive.google.com/file/d/1--FSFJ2ZAuB_EM16Zb7WSyzlHiMJ-x2y/view?usp=sharing

Thank you

### What did you expect to happen?

Please check error for help me

Thanks

### Reproduction URL

https://drive.google.com/file/d/1--FSFJ2ZAuB_EM16Zb7WSyzlHiMJ-x2y/view?usp=sharing

### How to reproduce?

npm init quasa
quasar mode add capacitor && quasar dev -m capacitor -T ios
 Xcode open. I run app to open Simulator iPhone

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Capacitor Mode

### Platforms/Browsers

iOS

**Comment by rstoenescu** [comment]
Hi,

Please post another reproduction link (along with your quasar.config file AND the Quasar CLI that you are using + its version). The indicated link is not valid.

We will then reopen or offer more details on what could be wrong. There are 99% chances this is not a bug but a misconfiguration.

**Comment by FelipeSD** [comment]
I was also getting a blank screen running the app on my device, but when I changed the IP address to the other one during prompt `"quasar dev -m capacitor -T android"` it worked for me.

**Comment by toejough** [comment]
I'm still getting a blank screen - trying to chat about it on discord here: https://discord.com/channels/415874313728688138/856517527700766751/1306113958008193054

**Comment by rstoenescu** [comment]
@toejough A blank screen means you are either not using the right IP address or your phone/tablet is not in the same network as the dev machine.

**Comment by toejough** [comment]
Hey thanks for the response! I’m running both ends of this from my laptop,
so it should be the same network.

I’ll do my best to chase this down, but if you have further pointers I’d
appreciate it. All I’ve done at this point is ‘yarn create quasar’ and
‘quasar dev -m capacitor -T ios’ … this should be a pretty vanilla setup.

I’ll start with checking anything is being served up at the address quasar
is showing me, and then dig into where Xcode is actually looking.

**Comment by rstoenescu** [comment]
No need to dig anything into the XCode. Just try to use a mobile browser and see if it can connect to the devserver url

**Comment by toejough** [comment]
thanks! no, it doesn't connect. I've checked - the IP is my local IP on the network. Is there a particular port I should be explicitly pointing at?

**Comment by toejough** [comment]
ok I figured it out. I'm running on a mac and the firewall was enabled. dev server stuff that runs on localhost and is accessed as localhost works just fine, but actual IP addresses from the network, not so much. 

Thank you for the pointers @rstoenescu - it got me working down the right path!!

**Comment by rstoenescu** [comment]
Great to hear that. I expected something to block the connection.
