### ISSUE TITLE
Popover documentation error

### ISSUE THREAD

**Issue by afilic** [quasarframework/quasar#1623]
framework: {  components: ['QPopover'],  // optional if you want to use  // directive `v-close-overlay`  plugins: ['CloseOverlay']}
--

Should be:
directives: ['closeOverlay']

**Comment by rstoenescu** [comment]
Yes. This was already fixed. Will be live after today's update along with v0.15.2. Thanks.

**Comment by rstoenescu** [comment]
Also, please use the https://github.com/quasarframework/quasar-framework.org repo for docs. Thanks.
