### ISSUE TITLE
Docs will sometimes not fully show light mode

### ISSUE THREAD

**Issue by BenJackGill** [quasarframework/quasar#16230]
### Description

If I have previously visited the docs and set the theme to "light mode" then I re-visit the docs from a Google link, the light mode does not work correctly. Some parts are correctly in light mode (background) while others are still stuck in dark mode (menu text, header logo, etc).

**Steps for reproduction:**

1) Visit the docs inner page and set the theme to "light". For example: https://quasar.dev/vue-components/date/
2) Close that tab
3) Open Google and search for "quasar date select". For example: https://www.google.com/search?q=quasar+date+select&oq=quasar+date+select&aqs=chrome..69i57.2507j0j1&sourceid=chrome&ie=UTF-8
4) Click the top link in Google that will take you to the Quasar docs page
5) You will see that the page is not fully in light mode. The background is light, but the menu, headers, and outline for the API cards are still in dark mode style, causing a strange appearance of halfway between light and dark modes.

**This is what is should look like (light mode fully working):**
<img width="1423" alt="Screenshot 2023-08-22 at 2 04 55 pm" src="https://github.com/quasarframework/quasar/assets/2043257/a9c46323-0aac-412e-9723-98fd3b661e3d">

**But this is what it actually looks like (light mode is not working correctly):**
<img width="1420" alt="Screenshot 2023-08-22 at 2 04 44 pm" src="https://github.com/quasarframework/quasar/assets/2043257/b6512cfc-a5af-4bbc-bbfc-660cd20ffd11">

I have the same result on Chrome and Brave browsers. Have not tested others.

### Flavour

None

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
I suppose it was a bad cache. Cannot reproduce
