### ISSUE TITLE
The type of the q-table virtual-scroll event should match the equivalent q-virtual-scroll event

### ISSUE THREAD

**Issue by chrisfoss1** [quasarframework/quasar#16246]
### Description

For the [table component](https://quasar.dev/vue-components/table), both the documentation and the type indicate that the @virtual-scroll event will have a details parameter with 4 properties: `index`, `from`, `to`, and `direction`.

In reality, the details parameter actually matches that of the [virtual scroll component](https://quasar.dev/vue-components/virtual-scroll/), which includes a `ref` as well in the response.

The documentation and the type of the `virtual-scroll` event for the `q-table` should be updated to match what is actually returned.

### Documentation Section URL

https://quasar.dev/vue-components/table

### Flavour

None

### Areas

TypeScript Support

**Comment by chrisfoss1** [comment]
As an aside, I noticed while creating this issue that the link to the Contribution Guide in the Doc Report template for Quasar v2 is broken.

**Comment by yusufkandemir** [comment]
@chrisfoss1 thanks for reporting the broken links in the issue template. Fixed in https://github.com/quasarframework/quasar/commit/208784257981e6b508462ee91f9985b5f746c649

**Comment by yusufkandemir** [comment]
The fix will be included in the next Quasar release and the docs deployment that follows it.
