### ISSUE TITLE
Qtime and Qdate Persian doesn't work in input

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#16254]
### What happened?

[qinput with date and time](https://quasar.dev/vue-components/date#example--qdate-and-qtime-with-qinput) doesn't work in Persian calendar. both component remove each other data.

### What did you expect to happen?

[like this example](https://quasar.dev/vue-components/date#example--qdate-and-qtime-with-qinput) it should work perfectly in Persian mode. if you change the mask to `YYYY/MM/DD HH:mm` it should fixed.

### Reproduction URL

https://codepen.io/miladmeidanshahi/pen/gOZaeLm

### How to reproduce?

check the codepen

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

Unfortunately when dealing with the persian calendar (only) the mask for QDate is enforced to`YYYY/MM/DD`. So you cannot use a duo of QTime + QDate on same model in this scenario.
