### ISSUE TITLE
q-tooltip Unexpected behavior 

### ISSUE THREAD

**Issue by jobdiogenes** [quasarframework/quasar#16274]
### What happened?

While I'm coding a Quasar UI, I found that some q-tooltip 's shows short with scroll, then I try to use "max-width" without success.
After some tests [Click here to See In Code Pen](https://codepen.io/jobdiogenes/pen/qBLZZdV)
I discovery that q-tooltip width could be shorted  depend on type of text. 
And this seem to occur only inside "q-layout / q-footer"

Ex: `Save to Googl1` and `Save to Google` show different 

### What did you expect to happen?

q-tooltip show same size without scrolling   

### Reproduction URL

https://codepen.io/jobdiogenes/pen/qBLZZdV

### How to reproduce?

1. goto provided link
2. move mouse over icons on bottom and see results
3. look to code to confirn

### Flavour

Quasar UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
n/a
```

**Comment by yusufkandemir** [comment]
They look fine
![image](https://github.com/quasarframework/quasar/assets/6266078/43c5c1f6-80a8-4c80-942e-bb95fe855567)
![image](https://github.com/quasarframework/quasar/assets/6266078/6aec2a6b-c305-454f-84e6-9b3775a7abd5)
![image](https://github.com/quasarframework/quasar/assets/6266078/1141fd76-1b7d-4d27-bd7b-905317c22318)
![image](https://github.com/quasarframework/quasar/assets/6266078/90571aa4-8788-499a-a8da-8b4041860d12)
