### ISSUE TITLE
TypeError: Merging undefined is not supported from @quasar/app-vite@1.4.2

### ISSUE THREAD

**Issue by smartcodemotive** [quasarframework/quasar#16279]
### What happened?

When I install @quasar/app-vite@1.4.1, quasar build works.
But when I install @quasar/app-vite@1.4.2, I get following error when run "quasar build".

TypeError: Merging undefined is not supported
    at mergeWithOptions 

...\node_modules\webpack-merge\dist\index.js:52:19

After this commit https://github.com/quasarframework/quasar/commit/c681715b6c04e01b04b89e7139073fa12445a314， it doesn't work.  Please check this.

### What did you expect to happen?

quasar build should work.

### Reproduction URL

https://codepen.io/ChengYuHin99/pen/WNLxNMj

### How to reproduce?

1. quasar build
2. Then gets error.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Latest is v1.4.6. Please try with that and report back if this is still an issue. This was fixed for the next major version of q/app-vite (unreleased to the public yet), but honestly I can't remember if I backported the fix yet to the current version.

**Comment by rstoenescu** [comment]
Just checked. Not fully backported. Backporting now.

**Comment by rstoenescu** [comment]
Fixed and released q/app-vite 1.4.7

**Comment by smartcodemotive** [comment]
Thanks. I confirmed it was resolved in q/app-vite 1.4.7
