### ISSUE TITLE
LocalStorage issue

### ISSUE THREAD

**Issue by beggiatom** [quasarframework/quasar#1628]
### Software version

Quasar: 0.15.1
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: Chrome 64.0.3282.167, Opera 50.0.2762.67, Edge 
iOS: 
Android:
Any other software related to your bug:

### What did you get as the error?
```
// quasar.conf.js
plugins: [
    'Notify',
    'LocalStorage'
]
```
```
// user.js
import { LocalStorage } from 'quasar'

function id() {
  let user = LocalStorage.get.item('user')
  if (!user) return null
  return user.id
}

export {
   id
}
```
```
// index.vue
import { id } from './user'

export default {
  data() {
    return {
      id: id(),
    }
  }
}

```
In console I've got

```
Uncaught TypeError: Cannot read property 'item' of undefined
```

### What were you expecting?
User ID (if any)

### What steps did you take, to get the error?
Only load page

**Comment by pdanpdan** [comment]
Drop item. It's LocalStorage.set(name, value), LocalStorage.get(name)

**Comment by beggiatom** [comment]
With last versione 0.15.2 it working perfectly

**Comment by rstoenescu** [comment]
I'm sure it worked with 0.15.1 too... because nothing changed :|

**Comment by pvencill** [comment]
I'm having the same problem on 0.17.22. Browser is Chrome, all I'm doing is adding it to the plugins in quasar.conf.js as the documentation states, and on rebuild I get that error.

**Comment by rstoenescu** [comment]
@pvencill 

quasar.conf > plugins is for app plugins (your app's mainjs/initialization code in src/plugins)
quasar.conf > framework > plugins is for Quasar's plugins

You're using first instead of the latter to register a Quasar plugin.
