### ISSUE TITLE
PopupProxy sometimes does not show when called from an input inside a menu

### ISSUE THREAD

**Issue by CamilleDrapier** [quasarframework/quasar#16285]
### What happened?

When using Firefox, enabling the "Responsive Design Mode", and choosing one of the "Iphone 12/13" devices (other devicesseem to work as expected), the PopupProxy does not show when it is rendered from an input inside a menu.

### What did you expect to happen?

I would expect the dialog to show.

I do not mind that it does not work in a very specific use case of the Responsive Design Mode of a particular browser with aspecific device simulated; I'm simply raising the issue in case it could be a deeper problem that could have other consequences.

### Reproduction URL

https://codepen.io/camilledrapier-the-flexboxer/pen/ExGywRX

### How to reproduce?

- Use Firefox
- Use the "Responsive Design Mode"
- Use one of the "Iphone 12/13" devices
- (re)Load the codepen page
- Click on the button
- Click on the input

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System        Linux(6.1.49-1-MANJARO) - linux/x64
NodeJs                  18.17.1

Global packages    
  NPM                   9.6.7
  yarn                  Not installed
  @quasar/cli           2.2.3
  @quasar/icongenie     Not installed
  cordova               Not installed
```

### Additional context

I tried to debug a bit the QDIalog component, and it seems that what is happening is that the "show" of the dialog is triggered, but then a "toggle" is immediately triggered which is hiding the dialog. Please note that in this case the `hide` event doesn't seem to be emitted.

A colleague with Firefox on Mac seem to also have the same problem.

**Comment by pdanpdan** [comment]
Firefox mobile emulation is broken - it is emitting events in wrong order or wrong events.
Sorry, we cannot fix firefox and firefox is not fixing that for many years :(

**Comment by CamilleDrapier** [comment]
Thanks a lot for looking into it, and for the feedback!
