### ISSUE TITLE
QDate today-btn, single day selection when range is enabled

### ISSUE THREAD

**Issue by philippebourcier** [quasarframework/quasar#16297]
### What happened?

When using the "today-btn" feature with "range", the object returned is not in the form :
 { "from": "0000/00/00", "to": "0000/00/00" }
but it is instead a simple date string, like this :
"2023/09/04"

### What did you expect to happen?

For better consistency, when clicking on the today-btn or selecting a single day, **when range is enabled**, we should get a range object, like this :
 { "from": "2023/09/04", "to": "2023/09/04" }

I feel this is a bug and not a feature request, but feel free to correct me if I'm wrong... 🤷‍♂️

### Reproduction URL

https://codepen.io/philippebourcier/pen/RwEGYxR

### How to reproduce?

1) Go to provided codepend
2) Click on "today" button, a simple date string is shown while we should get a range with to == from.
3) Click on a date range, a date range will be displayed

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
# quasar info

Operating System - Linux(6.1.0-9-amd64) - linux/x64
NodeJs - 18.13.0

Global packages
  NPM - Not installed
  yarn - 1.22.19
  @quasar/cli - 2.2.3
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.6 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.47.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - devtest
  eth0 - 10.0.3.8
```

**Comment by leoelz** [comment]
Hi @philippebourcier 
You can solve it by adding a computed property
```js
  computed: {
    myDateRange(){
      return 'string' === typeof this.myDate ? { from: this.myDate, to: this.myDate } : this.myDate;
    }
  }
  ```
  and use `{{ myDateRange }}` instead of `{{ myDate }}`
You can [check it in codepen](https://codepen.io/leoelz/pen/vYvdZLa)

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, this is not how the QDate model is designed to behave. When a single day is selected then that is not an interval, so the model becomes that day instead. Furthermore, when clicking on the "today" button and model is empty there is no way to determine what exactly you want the model to be (date or interval).

Check previous comment or add your own button inside the QDate element in your template to handle the scenario exactly the way that you want.
