### ISSUE TITLE
Whats wrong with tabs for indent style and how can I set the indent size to be 4 not 2?

### ISSUE THREAD

**Issue by 7ammer** [quasarframework/quasar#163]
Whats wrong with tabs for indent style and how can I set the indent size to be 4 not 2?

Please help, I can't find where to set this and the .editorconfig has no effect on the linter.

Thanks

**Comment by 7ammer** [comment]
Alternatively how can I disable the linting?

**Comment by rstoenescu** [comment]
.editorconfig is used by some editors. Doesn't intersect with the linter (eslint).
So, edit .eslintrc.js. Documentation for indentation here: http://eslint.org/docs/rules/indent

Please use forum for questions. Thanks and hope it helps!

**Comment by rstoenescu** [comment]
Linting ensures some code quality and even captures some bugs. It's recommended that you use eslint.

Anyway, you can disable linting by editing `build/webpack.base.config.js` and removing the preloaders section entirely.

**Comment by 7ammer** [comment]
Apologies I must have missed the forum link. Thanks for your help.

**Comment by rstoenescu** [comment]
It's in this repo's readme. Here it is for convenience: http://forum.quasar-framework.org

Cheers.
