### ISSUE TITLE
Q-Editor toolbar behaviour if no text is selected

### ISSUE THREAD

**Issue by ThomasKro** [quasarframework/quasar#16301]
### What happened?

1. if no text is selected, you can not select multiple styling options (like bold and italic). The toolbar does not allow selecting both options instead it just switches between them
2. If no text is selected, you can not unselect a selected styling option.

### What did you expect to happen?

1. The toolbar should allow selecting multiple styling option even if no text is selected.
2. The toolbar should allow to unselect a styling option even if no text is selected.

### Reproduction URL

https://codepen.io/ThomasKro/pen/jOXVOPE

### How to reproduce?

1. Try to select Bold and italic without marking text in the editor. 
2. Then try to unselect the selected styling option again.

Can also be reproduced in the docu.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by rstoenescu** [comment]
Hi,

QEditor is relying on `document.execCommand()` to apply the state and `document.queryCommandValue()` to get the current state. What you are experiencing is the native browser behavior which we cannot tamper with.
