### ISSUE TITLE
The "Roadmap" link on the new web site is a 404.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#16309]
### Description

![image](https://github.com/quasarframework/quasar/assets/301525/afc6ad2e-6b77-4281-a8d5-3d8376e5e5fb)

Links to 

- https://github.com/quasarframework/quasar/blob/vue3-work/ROADMAP.md

### Flavour

None

### Areas

Style & Identity (quasar)

**Comment by rstoenescu** [comment]
Fixed
