### ISSUE TITLE
QTable columns sort function is not called for nullish value

### ISSUE THREAD

**Issue by AjiTae** [quasarframework/quasar#16303]
### Source
[https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/table-sort.js#L45-L53](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/table-sort.js#L45-L53)

### Example
Here, I'm trying to sort some field by some other field:
[https://codepen.io/ajitae/pen/MWZbepj](https://codepen.io/ajitae/pen/MWZbepj)
```javascript
const columns = [
  {
    label: 'name',
    name: 'name',
    field: 'name'
  },
  {
    label: 'value',
    name: 'value',
    field: 'value',
    format: (val, row) => val === null ? '-pending-' : val,
    sortable: true,
    sort: (a, b, rowA, rowB) => rowA.sortPosition - rowB.sortPosition
  }
];

const rows = [
  {
    name: 'foo',
    value: null,
    sortPosition: 1
  },
  {
    name: 'bar',
    value: '2 - processed',
    sortPosition: 2
  },
  {
    name: 'buz',
    value: null,
    sortPosition: 3
  }
]
```
In this scenario, the sort function does not get invoked for nullish values, resulting in only `bar` being "sorted", which can be counterintuitive. Now that I understand the reason behind this behavior, I don't consider it a bug; instead, I should implement it some other way. 
However, it would be beneficial to include this behavior in the `sort` field description.

### Documentation Section URL

https://quasar.dev/vue-components/table#defining-the-columns

### Flavour

None

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

I see your point. Implemented "rawSort()" -- which has same signature as "sort", but it will also handle rows with null/undefined as value.

Will be available in Quasar v2.12.8
