### ISSUE TITLE
Docs: Scrolling introductions are misleading

### ISSUE THREAD

**Issue by suzhenghui-sky** [quasarframework/quasar#16310]
### Description

Rolling introductions are misleading；The example should not be overflow-hidden https://quasar.dev/quasar-utils/scrolling-utils

<div class="scroll overflow-hidden" style="height: 100px">
  ...content expanding over the 100px height from container...
</div>

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in next docs deployment.
