### ISSUE TITLE
Extra padding-bottom in QInput when inside QField

### ISSUE THREAD

**Issue by borutjures** [quasarframework/quasar#1631]
### Software version

OS: Darwin(17.4.0) - darwin/x64
Browser: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)

Global packages                 
  NodeJs                     8.9.4
  NPM                           5.6.0
  yarn                          Not available
  quasar-cli                    0.15.1
  vue-cli                       2.9.3
  cordova                       7.0.1

Important local packages        
  quasar-cli                    0.15.1
  quasar-framework              0.15.1
  quasar-extras                 1.0.2
  vue                           2.5.13
  vue-router                    3.0.1
  vuex                          3.0.1
  electron                      Not available
  babel-core                    6.26.0
  webpack                       3.11.0  

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/waugrryy/197/

### What did you get as the error?
No error. It is UI related.

### What were you expecting?
The same spacing for padding-bottom as when QInput is used without the QField.

### What steps did you take, to get the error?
Copy&Pasted the example: http://quasar-framework.org/components/input-textfield.html#Basic-Usage-with-QField

### Research Notes:
There were some changes in the code that could be related to this: https://github.com/quasarframework/quasar/commit/c77f7ab83fbdff635bef1c7733c65128bb0374c3#diff-b8a34ea846af1d8b759d63c8d92bd37b

Mo provided a link to the guidelines: https://material.io/guidelines/components/text-fields.html# Guidelines say it should be 8px. In 0.15  there are 10px. The text is 2px to high

Screenshot:
![q-field-q-input](https://user-images.githubusercontent.com/6814904/36612831-0768fe84-18d8-11e8-84ea-f7b4697efb4a.png)

**Comment by rstoenescu** [comment]
Hi,

Your example is flawed regarding the usage of gutter in the first example. You should wrap content in a `<div>`.

Keeping this ticket opened to fix a true small problem in alignment.
