### ISSUE TITLE
Custom body slot is not hidden when using no-transition prop on Qtree component

### ISSUE THREAD

**Issue by kaslav** [quasarframework/quasar#16318]
### What happened?

Using no-transition prop on Qtree component with custom body slot. This custom body slot is visible even though the node is not expanded.

### What did you expect to happen?

The custom body slot should not be visible if node is not expanded. Basically, the same behaviour as using Qtree without no-transition prop.

### Reproduction URL

https://jsfiddle.net/qwrmshc7/4/

### How to reproduce?

See the example in jsFiddle.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.12.7
