### ISSUE TITLE
"Disabled" toggle still functions when clicked

### ISSUE THREAD

**Issue by mcasto** [quasarframework/quasar#16325]
### What happened?

I have a q-toggle component with the disabled property set to true. The cursor changes and the control grays out as expected, but if I click it, the toggle switches (and, since its state affects other components and, behind the scenes, the database, all of that happens when it should not).

### What did you expect to happen?

When the disabled prop is true, I would expect the component to be inaccessible, and clicking it should do nothing.

### Reproduction URL

https://jsfiddle.net/castoware/f5876zqj/49/

### How to reproduce?

1. Go to reproduction link
2. Click the toggle
3. Notice that the associated value changes

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
Operating System - Darwin(22.6.0) - darwin/x64
NodeJs - 18.17.0

Global packages
  NPM - 9.6.7
  yarn - 1.22.19
  @quasar/cli - 2.2.3
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.5.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.48.0 -- An AST-based pattern checker for JavaScript.
  electron - 26.2.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - CastoBook.local
  en0 - 192.168.0.104
```

### Relevant log output

```Shell
There is no log output triggered by this problem.
```

**Comment by pdanpdan** [comment]
there is no `disabled`, it's `disable`

**Comment by mcasto** [comment]
Oh. LOL. Every time I looked at the documentation, my brain read it as "disabled" because that's the HTML prop. Thanks :D
