### ISSUE TITLE
QMenu, QDialog, QPopupProxy not working when QScrollArea is a descendent

### ISSUE THREAD

**Issue by presiyan-peev** [quasarframework/quasar#16324]
### What happened?

When QScrollArea is a child of QMenu. QDialog or QPopupProxy, the popup doesn't work.

### What did you expect to happen?

When using q-dialog a dialog to appear
When using q-menu a menu to appear
When using q-popup-proxy one of them to appear

### Reproduction URL

https://codepen.io/pressijan/pen/rNojyBG

### How to reproduce?

1. Go to https://codepen.io/pressijan/pen/rNojyBG
2. Click on 'Click here'

When using QMenu or QPopupProxy on a big screen, nothing visible happens. When using QDialog or QPopupProxy on a small screen, an overlay appears.
If you remove <q-scroll-area> you receive the expected behavior

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment]
This is normal and expected - QScrollArea needs dimensions, and when it is in a menu it does not have any dimensions (neither width nor height)
