### ISSUE TITLE
q-tooltip no longer works in inline SVG in vue templates

### ISSUE THREAD

**Issue by annezheng** [quasarframework/quasar#16326]
### What happened?

The following svg code in a vue template shows a tooltip in quasar V1, but not in quasar V2. 
```
<svg viewBox="0 0 150 150" xmlns="http://www.w3.org/2000/svg">         
	<rect width="50" height="50" fill="green">
	  <q-tooltip>
	    SVG Tooltip
	  </q-tooltip>
	</rect> 
</svg>
```

### What did you expect to happen?

I expect the q-tooltip works in quasar V2 just as in quasar V1.  

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

Copy the SVG code in the example codepen for q-tooltip. If you do this in Quasar V1 it works, if you do this in Quasar V2, it does not work.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 18.14.2

Global packages 
  NPM - 9.5.0
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.2
  pinia - 2.1.4 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.43.0 -- An AST-based pattern checker for JavaScript.
  electron - 25.3.2 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 17.1.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
This is due to how Vue 3 works. The solution is for you to wrap your svg in a div/span and put the svg and tooltip as siblings.

**Comment by annezheng** [comment]
Thanks for your advice. The q-tooltip shows with this code. 

```
<span>
  <svg viewBox="0 0 150 150" xmlns="http://www.w3.org/2000/svg">
      <rect width="50" height="50" fill="green"/>
  </svg>
</span>
<q-tooltip>
  SVG Tooltip
</q-tooltip>
```

But my inline SVG has many elements and I want to show tooltip for a specific element, not the whole SVG. For example, in Quasar v1, I can show a tooltip for rect and circle with this code. Is it possible to achieve the same in Quasar v2? Your advice is greatly appreciated!

```
<svg viewBox="0 0 150 150" xmlns="http://www.w3.org/2000/svg">
  <rect width="50" height="50" fill="green">
    <q-tooltip>
      Rect Tooltip
    </q-tooltip>
  </rect>

  <circle cx="50" cy="50" r="50" >
    <q-tooltip>
      Circle Tooltip
    </q-tooltip>
  </circle>
</svg>
```

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/QWzvdPX?editors=1010

**Comment by annezheng** [comment]
I applied your solution to my work project. Now the SVG tooltips show the same as in quasar v1 app. Thanks for your generous help!

**Comment by cfroystad** [comment]
Unfortunately, the codepen linked above is no longer available. Could you please reshare the solution/workaround for qtooltip on elements inside an svg?

**Comment by pdanpdan** [comment]
Put an id on the SVG target element and use it as target in the QTooltip. And QTooltip can be a sibling of svg
