### ISSUE TITLE
q-table,Button disappears when grid

### ISSUE THREAD

**Issue by bibibala** [quasarframework/quasar#16328]
### What happened?

Button disappears when grid
<img width="1408" alt="截屏2023-09-11 09 11 40" src="https://github.com/quasarframework/quasar/assets/57165565/b81df8d1-edc2-484b-91eb-ba2e3076f7aa">
<img width="1422" alt="截屏2023-09-11 09 11 25" src="https://github.com/quasarframework/quasar/assets/57165565/d5d96812-cf78-4bb5-983f-712d8abd9b19">

### What did you expect to happen?

Is that how it's designed, I wonder.

### Reproduction URL

https://codepen.io/bababaZhao/pen/OJrprWK?editors=1010

### How to reproduce?

- Set the configuration properties of the grid of q-table
- gird true / false

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

Yes, you need to also use the "item" scoped slot.
We cannot use the same slots as for the table view (body-cell-* etc etc) because of the strict HTML syntax nature of `<table>` and the use of QTr/QTh/QTd.. Also, the way the content is displayed is different so it's better to separate the two.
