### ISSUE TITLE
QScrollObserver don't work with QCarousel

### ISSUE THREAD

**Issue by reimnm** [quasarframework/quasar#16336]
### What happened?

When QScrollObserver is inside a QCarousel (only one QCarousel per page), @scroll will not be called.

### What did you expect to happen?

QScrollObserver works with QCarousel to let scroll action control the current panel.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-urwtkc?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1.Go to Reproduction URL.
2.When scrolling, the onScroll function will not be called.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Directives (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
There is nothing that scrolls - please adjust your repro so that it shows the problem

**Comment by reimnm** [comment]
> There is nothing that scrolls - please adjust your repro so that it shows the problem

```<q-scroll-observer @scroll="onScroll" /> ``` don't work

**Comment by pdanpdan** [comment]
We'll reopen if the repro can reproduce the problem
