### ISSUE TITLE
Q-Input shadow-text overlaps number value

### ISSUE THREAD

**Issue by freakzlike** [quasarframework/quasar#16330]
### What happened?

When using shadow-text on a `type="number"` input field and entering an invalid or incomplete number value, then `shadow-text` is moved to the front and overlaps the input value.

![image](https://github.com/quasarframework/quasar/assets/11063025/0ec94dfd-60ba-4f5a-b9b4-97beed4a8d70)

### What did you expect to happen?

Not overlapping the input value, regardless if valid or not.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-mzcziy?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Open reproduction link
2. Focus on the input field
3. Input field should show "25Text"
4. Append "." at the input (should be "25.")
5. Shadow text moves to the front of the input field and overlap with "25."

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Additional context

I'm not sure if using the raw value for the shadow-text might fix the issue

**Comment by pdanpdan** [comment]
Inputs with type number, date, datetime, ... do not work well with any special type of processing (shadow text, masks) because they have some restrictions. Use a text type of input and set `inputmode` if you need.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
