### ISSUE TITLE
Datetime input @change gets called on month scan

### ISSUE THREAD

**Issue by mcrady** [quasarframework/quasar#1633]
Go to http://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/datetime/datetime-input

Scroll down to "Lazy input".  Trigger the pop up calendar.  Click the right arrow to scan forward a few months.  

The @change method gets triggered upon the first month change.

**Comment by rstoenescu** [comment]
https://media.giphy.com/media/ZcIHoitFTeVQLggqiC/giphy.gif

It's working as you expect it to work... Can you reopen with a screen video capture too? Thanks.

**Comment by mcrady** [comment]
https://www.useloom.com/share/099ee6eae34b4078a711febd64bd3fab

But I tried it on two other browsers and it's working fine.  Feel free to keep this closed until anyone else reports a problem.

**Comment by mcrady** [comment]
BTW, I'm on Chrome:

Version 65.0.3325.89 (Official Build) beta (64-bit)

But I tried another version 65 of Chrome and it worked fine.
