### ISSUE TITLE
q-btn Icon display abnormality

### ISSUE THREAD

**Issue by bibibala** [quasarframework/quasar#16339]
### What happened?

<img width="94" alt="截屏2023-09-13 15 57 48" src="https://github.com/quasarframework/quasar/assets/57165565/107cd513-2876-4ffa-8d03-e72ec0923e93">
<img width="102" alt="截屏2023-09-13 15 57 54" src="https://github.com/quasarframework/quasar/assets/57165565/2db6c8e2-5084-4c56-84c0-37306165825d">

- q-btn Icon display abnormality
- This will be triggered when the mouse passes and leaves. It seems that it will not trigger when the button is in English.

### What did you expect to happen?

why

### Reproduction URL

https://codepen.io/bababaZhao/pen/bGOREyd

### How to reproduce?

Just mouse over and leave this button

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Cannot reproduce.
What browser (+version), what OS (+version), what compositor, ...

**Comment by bibibala** [comment]
Sorry, it's my browser's plug-in that's causing it,
