### ISSUE TITLE
QInput forces model to empty string

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#16346]
### What happened?

When QInput uses mask and clearable prop, it forces the model into empty string instead of null.

### What did you expect to happen?

Model should be null

### Reproduction URL

https://codepen.io/metalsadman/pen/wvReZaY?editors=1010

### How to reproduce?

Open devtools to see logs

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.12.8
