### ISSUE TITLE
Apollo Integration Failed

### ISSUE THREAD

**Issue by arjitkhullar** [quasarframework/quasar#1634]
added as a plugin
=> In apollo.js
```
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import VueApollo from 'vue-apollo'

export default ({ app, Vue }) => {
  // Register the VueApollo plugin with Vue.
  Vue.use(VueApollo)

  const httpLink = new HttpLink({
    uri: `http://localhost:4000/graphql`
  })
  const link = httpLink

  const apolloClient = new ApolloClient({
    cache: new InMemoryCache(),
    connectToDevTools: true
  })

  const apolloProvider = new VueApollo({
    defaultClient: apolloClient
  })
  app.apolloProvider = apolloProvider.provide()
}
```
=> In index.Vue
tried to query graphql in apollo object but there were no queries fired.

using quasar 0.15+ with default stater pack.

**Comment by arjitkhullar** [comment]
A workaround: 
export apollo client and use to query the database

```
import apolloClient from '../plugins/apollo-client'
import gql from 'graphql-tag'
export default {
async getData(name) {
      const response = await apolloClient.query({
        query: gql`
          query getByName($input: String!) {
            getByName(name: $input) {
              id
              name
              description
              price
            }
          }
        `,
        variables: { input: name }
      })
      console.log(response)
    }
}
```
[Example](https://markus.oberlehner.net/blog/combining-graphql-and-vuex/)

**Comment by Trellian** [comment]
I had a similar problem yesterday. Did you just upgrade from `vue-apollo@3.0.0-alpha.x` to `vue-apollo@3.0.0-beta.x`? It looks like it. 

It seems you are missing the `Vue.use(VueApollo)`  at the end of your script. Try:
```js
export default ({ app, Vue }) => {
  Vue.use(VueApollo)
  app.provide = apolloProvider.provide()
}
```
See https://github.com/Akryum/vue-apollo/issues/220

**Comment by arjitkhullar** [comment]
yes i am using the vue-apollo 3.0.0-beta.4.
I have initialized apollo the same way (first  comment).
the problem is that queries doesn't work when using apollo object.

**Comment by Trellian** [comment]
Did you register the plugin in `quasar.conf.js`:
```js
module.exports = function (ctx) {
  return {
    plugins: [
      'i18n',
      'axios',
      'apollo',
      'vuelidate'
    ],

```

**Comment by Trellian** [comment]
I had the same problem initially on upgrading, but mine works fine now, after the vue-apollo author Guillame Chao kindly helped me get the config right

**Comment by rstoenescu** [comment]
Hi,

Please refer to Apollo author as Trellian indicated. This is not a Quasar issue. Make sure you register your app plugin in `/quasar.conf.js`.

**Comment by arjitkhullar** [comment]
@Trellian I had everything setup the same way. can you share a sample repository. thanks

**Comment by hipertracker** [comment]
Is there any full example? The mentioned code for apollo.js is incomplete. It has unused 'httpLink'
