### ISSUE TITLE
The first row of the q-table component is an exception jump problem

### ISSUE THREAD

**Issue by yansenlei** [quasarframework/quasar#16353]
### What happened?

When the table is set to a height and scrolling is required, the right-click menu hides the problem that causes the first row to jump.

![20230915171205_rec_](https://github.com/quasarframework/quasar/assets/23315895/0ac3de05-05a3-4f1d-aa49-9647b82861b7)

### What did you expect to happen?

The table will not display any exception

### Reproduction URL

https://codepen.io/yansenlei/pen/gOZMxwW

### How to reproduce?

1. Sets the height for the q-table
2. allow the form to scroll
3. Put the first row at the top of the visible range
4. right-click on the menu to trigger an issue

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You need to specify the scroll-padding
```css
.q-table__middle {
  scroll-padding-block-start: 48px
}
```
https://codepen.io/pdanpdan/pen/NWevvxO?editors=1100

**Comment by HarisSpahija** [comment]
Issue can be closed
