### ISSUE TITLE
Use cordova to package H5, click input in IOS to pop up the numeric keyboard, the whole layout is messed up, the head position:fixed is invalid, you can scroll together

### ISSUE THREAD

**Issue by suzhenghui-sky** [quasarframework/quasar#16361]
### What happened?

Use cordova to package H5, click input in IOS to pop up the numeric keyboard, the whole layout is messed up, the head position:fixed is invalid, you can scroll together

### What did you expect to happen?

Head doesn't roll
![图片](https://github.com/quasarframework/quasar/assets/48371536/b4e4308c-deac-4d54-b89d-92e9671aee58)
![图片](https://github.com/quasarframework/quasar/assets/48371536/5a7a30fb-e9ce-4f68-9129-4d2e28accac5)

### Reproduction URL

not link 

### How to reproduce?

1. Create an H5;

2. Create an input component

3. Package cordova as an APP

4. Run on IOS;

5. Click Input to pop up the numeric keypad

6. Slide your fingers up and down

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by jcesarmobile** [comment]
This is not really a Quasar bug but how the iOS `WKWebView` works.
If you want to prevent that behavior you can use some plugin like `cordova-plugin-ionic-keyboard`

**Comment by suzhenghui-sky** [comment]
> This is not really a Quasar bug but how the iOS `WKWebView` works. If you want to prevent that behavior you can use some plugin like `cordova-plugin-ionic-keyboard`

thank you !
