### ISSUE TITLE
Replace the default icons pack to MDI

### ISSUE THREAD

**Issue by insign** [quasarframework/quasar#1637]
Since MDI has dozens of others icons following the material design guidelines and just extends the defaults material icons, it could be more helpful for the devs.

This change probable is easy and almost won't break anything since, as said, extend the default material icons and his names.

MDI is very (extreme) active like font-awesome and easy accept new icons, and has a approach too much more open than font-awesome. BTW, new added icons are very useful.

Default material design lacks many icons and probably will update slowly and based in Google goals.
 
MDI: https://materialdesignicons.com 2000+ growing mterial design icons.

https://github.com/templarian/MaterialDesign/

**Comment by rstoenescu** [comment]
Hi,

This is redundant since you can set the MDI icon set as default in your app through quasar.conf.js. 
Also, loading a heavier icon set by default is not quite good, especially when you build a PWA... you'll notice a few points drop in Lighthouse just for this.

**Comment by insign** [comment]
Fine

Em 24 de fev de 2018 18:36, "Razvan Stoenescu" <notifications@github.com>
escreveu:
