### ISSUE TITLE
In QTable component, when we use Grid mode colsMap item doesnt have 'value' prop.

### ISSUE THREAD

**Issue by DanielIvashev** [quasarframework/quasar#16379]
### What happened?

In QTable component, when we use Grid mode colsMap item doesnt have 'value' prop. But when we use just 'cols' item has a value;

### What did you expect to happen?

We need to add 'value' prop to colsMap item.

### Reproduction URL

https://codepen.io/danielivashev/pen/WNLdyaq

### How to reproduce?

![image](https://github.com/quasarframework/quasar/assets/62364141/04c3d35c-a441-4157-b9cb-ac7ebc550fbc)
![image](https://github.com/quasarframework/quasar/assets/62364141/232fc7db-db27-4102-8d9d-ff88895728c3)

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android

**Comment by DanielIvashev** [comment]
please, respond

**Comment by rstoenescu** [comment]
Hi,

This design is for perf reasons. Since you actually know what to do with the "row" that you are supplied for each "item" then you can compute in the slot whatever value you want (or write a component to do it and use it within the slot).
