### ISSUE TITLE
QBtn Square prop appears not to work

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#16373]
### What happened?

The QBtn `square` property does not appear to affect the buttons appearance any more.

### What did you expect to happen?

The button would be square.

### Reproduction URL

https://codepen.io/dsl101/pen/eYbyYZR

### How to reproduce?

1. Open the codepen.
2. Compare the Square and Default buttons.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by quroom** [comment]
I am not sure whether it's bug or not.
But I am sure there is no defined style in quasar.css for q-btn--square.
That's why it doesn't work.

**Comment by dsl101** [comment]
I'm assuming [this](https://github.com/quasarframework/quasar/blob/0b6a9b0671d654ce3362d9516ef59ad6bea3cdcf/ui/src/components/btn/QBtn.sass#L96) is supposed to do the trick, but hasn't been ported back to 1.22. Curious that the docs got updated though.

Edit: Found it in [this PR](https://github.com/quasarframework/quasar/pull/13912)

**Comment by dongwa** [comment]
see https://github.com/quasarframework/quasar/discussions/15229

**Comment by HarisSpahija** [comment]
This issue can be closed. This is a feature not supported in 1.22
