### ISSUE TITLE
QItemTile not rendering tag property

### ISSUE THREAD

**Issue by rettigd** [quasarframework/quasar#1638]
### Software version

Quasar: 0.15.2
OS: Mac OS
Node: 9.3
NPM: 5.6
Browsers: Chrome
iOS: N/A
Android: N/A
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/waugrryy/238/

### What did you get as the error?
In fiddle, QItem renders as a "a" tag, but QItemTile doesn't

Line 70 in QItemTile.js appears to render a div unless it's an icon

```    return h(this.icon ? QIcon : 'div', data, [ this.$slots.default ])```

**Comment by rstoenescu** [comment]
That's actually an error in docs. But regardless, added the feature :)
Will be available in 0.15.3
