### ISSUE TITLE
The options type of $q.bottomSheet is incorrect; This is an example of the official website I copied

### ISSUE THREAD

**Issue by suzhenghui-sky** [quasarframework/quasar#16381]
### What happened?

The options type of $q.bottomSheet is incorrect; This is an example of the official website I copied

### What did you expect to happen?

Correct type

### Reproduction URL

not url

### How to reproduce?

![图片](https://github.com/quasarframework/quasar/assets/48371536/d3b3f918-83c0-44fd-9749-da326e0b3a38)
![图片](https://github.com/quasarframework/quasar/assets/48371536/4f0c488a-4a77-4d62-aecb-e2d52d8cb20c)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by dongwa** [comment]
Perhaps you should consider updating your Quasar version. I tested this issue with the latest Quasar version and did not encounter any problems. You can update your Quasar packages by using the `quasar upgrade -i` command.



![image](https://github.com/quasarframework/quasar/assets/38457491/3003706b-325e-4305-b384-b310c5c9551f)
![image](https://github.com/quasarframework/quasar/assets/38457491/714374d5-852d-4d3d-aa01-d46a0f2ea851)

my quasar info:
```
quasar info

Operating System - Darwin(21.6.0) - darwin/x64
NodeJs - 20.7.0

Global packages
  NPM - 10.1.0
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - 2.5.3
  cordova - Not installed

Important local packages
  quasar - 2.12.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.46.0 -- An AST-based pattern checker for JavaScript.
  electron - 26.1.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by suzhenghui-sky** [comment]
> Perhaps you should consider updating your Quasar version. I tested this issue with the latest Quasar version and did not encounter any problems. You can update your Quasar packages by using the `quasar upgrade -i` command.
> 
> ![image](https://user-images.githubusercontent.com/38457491/269856967-3003706b-325e-4305-b384-b310c5c9551f.png) ![image](https://user-images.githubusercontent.com/38457491/269857017-714374d5-852d-4d3d-aa01-d46a0f2ea851.png)
> 
> my quasar info:
> 
> ```
> quasar info
> 
> Operating System - Darwin(21.6.0) - darwin/x64
> NodeJs - 20.7.0
> 
> Global packages
>   NPM - 10.1.0
>   yarn - 1.22.19
>   @quasar/cli - 2.0.0
>   @quasar/icongenie - 2.5.3
>   cordova - Not installed
> 
> Important local packages
>   quasar - 2.12.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
>   @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
>   @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
>   eslint-plugin-quasar - Not installed
>   vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
>   vue-router - 4.2.4
>   pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
>   vuex - Not installed
>   vite - 2.9.16 -- Native-ESM powered web dev build tool
>   eslint - 8.46.0 -- An AST-based pattern checker for JavaScript.
>   electron - 26.1.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
>   electron-packager - Not installed
>   electron-builder - Not installed
>   register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
>   @capacitor/core - Not installed
>   @capacitor/cli - Not installed
>   @capacitor/android - Not installed
>   @capacitor/ios - Not installed
> 
> Quasar App Extensions
>   *None installed*
> ```

Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 18.16.0

Global packages
  NPM - 8.19.2
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - 12.0.0 (cordova-lib@12.0.1)

Important local packages
  quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.2 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.0
  pinia - 2.1.1 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.40.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks

**Comment by rstoenescu** [comment]
Upgrade to latest Quasar UI. You are on v2.12.0 and latest is 2.12.7
