### ISSUE TITLE
bug(QVirtualScroll): item is missing a type

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#16389]
### What happened?

https://github.com/quasarframework/quasar/blob/e50e16b59a434e089c0b0241133a14100f338a80/ui/src/components/virtual-scroll/QVirtualScroll.js#L33-L36

### What did you expect to happen?

for item to have a generic type.

### Reproduction URL

no sandbox example link with typescript support

### How to reproduce?

1. Pass typed array to `:items`
2. Hover the `item` variable in slot and see the type of `item` is `any`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

**Comment by bazuka5801** [comment]
Workaround (wrapper)
```vue
<template>
  <q-virtual-scroll v-bind="props">
    <template v-for="(_, slot) of $slots" #[slot]="scope">
      <slot :name="slot" v-bind="scope" />
    </template>
  </q-virtual-scroll>
</template>

<script setup lang="ts" generic="T">
import type { QVirtualScrollProps } from 'quasar'
import { VNode } from 'vue'

const props = defineProps<
  QVirtualScrollProps & {
    items: T[]
    itemsSize: number
  }
>()

type DefaultSlotProps = {
  item: T
  index: number
}

defineSlots<{
  default: (arg: DefaultSlotProps) => VNode[]
}>()
</script>
```

**Comment by rstoenescu** [comment]
@yusufkandemir can you figure this out, pls?

**Comment by yusufkandemir** [comment]
This is not a bug, it's a feature request to introduce generics. But, QVirtualScroll isn't the only component that generics would come in handy, there are a lot of other components such as QTable, QSelect, etc. It's hard/impossible to achieve with the current JSON API, we are aiming to convert it into a TS-first documentation approach, where we can easily add generics.
