### ISSUE TITLE
Brand new Quasar CLI project throws many errors

### ISSUE THREAD

**Issue by anhzf** [quasarframework/quasar#16394]
### What happened?

I began the new Quasar project, followed the Installation guide, started the development server, and threw an error!

Here's an error I've found:
- On package installation at the beginning
```
 WARN  Issues with peer dependencies found
.
├─┬ eslint-config-airbnb-base 15.0.0
│ └── ✕ unmet peer eslint-plugin-import@^2.25.2: found 2.20.1
├─┬ eslint-plugin-import 2.20.1
│ └── ✕ unmet peer eslint@"2.x - 6.x": found 8.10.0
└─┬ @quasar/app-vite 1.3.0
  ├── ✕ unmet peer eslint@^8.11.0: found 8.10.0
  ├── ✕ unmet peer quasar@^2.8.0: found 2.6.0
  ├── ✕ unmet peer vue@^3.2.29: found 3.0.0
  ├── ✕ unmet peer vue-router@^4.0.12: found 4.0.0
  ├─┬ @quasar/vite-plugin 1.5.0
  │ └── ✕ unmet peer quasar@^2.8.0: found 2.6.0
  └─┬ @vitejs/plugin-vue 2.3.4
    └── ✕ unmet peer vue@^3.2.25: found 3.0.0
```
- On development server start:
```
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
```
- Lint files
```
Oops! Something went wrong! :(

ESLint: 8.10.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'import' declared in '.eslintrc.cjs » eslint-config-airbnb-base » /home/projects/stackblitz-starters-cl1adg/node_modules/.pnpm/eslint-config-airbnb-base@15.0.0_eslint-plugin-import@2.20.1_eslint@8.10.0/node_modules/eslint-config-airbnb-base/rules/imports.js': Package subpath './lib/util/glob-util' is not defined by "exports" in /home/projects/stackblitz-starters-cl1adg/node_modules/.pnpm/eslint-plugin-import@2.20.1_@typescript-eslint+parser@5.10.0_eslint@8.10.0/node_modules/eslint/package.json
```

### What did you expect to happen?

I expect to start the code ASAP after scaffolding the project 😊🙏

### Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-cl1adg

### How to reproduce?

Follow the Quasar installation [here](https://quasar.dev/start/quasar-cli) using `pnpm`, not from the provided as in Bug report template (It's resulting in a different scaffold).

here are my options:
- What would you like to build? › App with Quasar CLI, let's go!
- Current directory is not empty. Remove existing files and continue? … yes
- Pick Quasar version: › Quasar v2 (Vue 3 | latest and greatest)
- Pick script type: › Typescript
- Pick Quasar App CLI variant: › Quasar App CLI with Vite
- Pick a Vue component style: › Composition API with <script setup>
- Pick your CSS preprocessor: › Sass with SCSS syntax
- Check the features needed for your project: › ESLint
- Pick an ESLint preset: › Airbnb

I've tried using `npm` on my PC and throws the same, but no error on my reproduction

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36) - linux/x64
NodeJs - 16.20.0

Global packages
  NPM - 9.4.2
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.50.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - stackblitzstarterscl1adg-apuj
  en0 - 192.168.1.104
```

**Comment by yusufkandemir** [comment]
Both pnpm v7 and pnpm v8 using Node v18 works fine on macOS Ventura 13.6. StackBlitz uses pnpm v8.6.10, which is broken. pnpm v8.8.0 works fine. So, there is nothing to be done from our side, you have to wait until StackBlitz updates the pnpm version.

**Comment by anhzf** [comment]
ahh, I didn't check the latest package manager version. It's working now, thank you
