### ISSUE TITLE
QSelect: fill-input does not work when model value is 0 but works for 1 or "0"

### ISSUE THREAD

**Issue by rhaenni** [quasarframework/quasar#16392]
### What happened?

fill-input does not set the QSelect input value if the model value is 0, it works if the value is for example 1 or if the value is "0" (0 as string)

### What did you expect to happen?

fill-input should set the QSelect input value to the value of the model when value is 0

### Reproduction URL

https://codepen.io/notmuy234/pen/GRPxmax

### How to reproduce?

1. Go to the provided codepen
2. Observe that in the first QSelect the value is not correctly to 0, while it works for the next two QSelect where the value is set to 1 or "0"

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

Works as it should... Are you sure that you are not using an old version of Quasar? Latest UI as of writing these lines is 2.12.7.

First one:
![image](https://github.com/quasarframework/quasar/assets/4665641/08bb5f47-c9f3-4706-92e0-3220e78d9764)

Second one:
![image](https://github.com/quasarframework/quasar/assets/4665641/e3fb6203-52d7-47f8-b163-16fabad2c768)

Third one:
![image](https://github.com/quasarframework/quasar/assets/4665641/b78011b5-8af3-4161-b84d-faabb3108baf)

Please reopen or comment here if I am missing something.
