### ISSUE TITLE
breadcrumb separator is displayed even if next breadcrumb element is not visible

### ISSUE THREAD

**Issue by modevelops** [quasarframework/quasar#1639]
### Software version

Quasar: v0.15.2
OS: Win 10 64bit
Node: v9.5.0
NPM: v5.6.0
Browsers: Firefox Nightly, Chrome 64
iOS: -
Android: -
Any other software related to your bug: -

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/v1p4gej7/2/

### What did you get as the error?
Unnecessary separator at the end of the breadcrumb.

### What were you expecting?
I expect the separator not to be displayed, if the next element is not displayed (v-if = false or v-for = empty array)

### What steps did you take, to get the error?
See jsdiddle.

**Comment by rstoenescu** [comment]
Available in 0.15.7
