### ISSUE TITLE
Smaller component prefix suggestion

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#164]
Hi,

I think it would be really helpful to not have to write `<quasar-*>` and get `<q-*>` instead of that.

**Comment by rstoenescu** [comment]
True. Will probably change this so for the first v1.0 beta. Trying to minimize breaking changes as much as possible. Thanks for the suggestion!

**Comment by rstoenescu** [comment]
Please upvote this thread to make myself an idea on how many of you are interested in this. Thanks!

**Comment by dsonet** [comment]
I suggest simplify the css class prefix as well. It would looks much clean, easy to read and write.

**Comment by rstoenescu** [comment]
@dsonet agree on smaller prefix for css classes too

**Comment by rstoenescu** [comment]
v0.9 will have the shorter version of prefix.
