### ISSUE TITLE
Typescript default app does not correctly load

### ISSUE THREAD

**Issue by john-** [quasarframework/quasar#16412]
### What happened?

1.  Installed Quasar (typescript support)
2.  Followed the steps to run dev app
3. Went to Web browser page that was loaded by running dev app
4. Page looks like this:
![quasar_typescript](https://github.com/quasarframework/quasar/assets/2359125/1fe4d59e-f878-46dd-8c59-9450e7707786)

### What did you expect to happen?

Expected the page to look like this page (generated from javascript install on same computer):
![quasar_javascript](https://github.com/quasarframework/quasar/assets/2359125/a80e3529-8e5a-4f80-92ac-f6f9a2b53062)

### Reproduction URL

Issue is reproduced with the application that is installed by default

### How to reproduce?

1.  Installed Quasar (typescript support)
2.  Followed the steps to run dev app
3. Went to Web browser page that was loaded by running dev app
4. Look at page that was loaded in browser

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System - Linux(6.4.15-200.fc38.x86_64) - linux/x64
NodeJs - 18.18.0

Global packages
  NPM - 9.8.1
  yarn - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.7 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.50.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - host
  wlp0s20f3 - 172.16.X.X
```

**Comment by yusufkandemir** [comment]
The generated code is different, so that is to be expected. There is no bug. It looks weird, yes, but it works as expected. We are planning to improve starter kit content in the future.

**Comment by john-** [comment]
Thanks for the response and confirmation!  In support of what you indicate I went in and added other Quasar components and they have all worked as expected.
