### ISSUE TITLE
Error when using vue-i18n

### ISSUE THREAD

**Issue by Gregory-Han** [quasarframework/quasar#16410]
### What happened?

Error when using vue-i18n
Example: 
 success msg: Action was {0} successful => $t("success", ["@]")
 Result: Action was {0} successful

"dependencies": {
    "@quasar/extras": "^1.16.4",
    "axios": "^1.2.1",
    "pinia": "^2.0.11",
    "quasar": "^2.6.0",
    "vue": "^3.0.0",
    "vue-i18n": "^9.0.0",
    "vue-router": "^4.0.0"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.3.1",
    "@intlify/vue-i18n-loader": "^4.2.0",
    "@quasar/app-vite": "^1.3.0",
    "autoprefixer": "^10.4.2",
    "eslint": "^8.10.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^9.0.0",
    "postcss": "^8.4.14",
    "prettier": "^2.5.1"
  },

### What did you expect to happen?

Action was @ successful

### Reproduction URL

no

### How to reproduce?

// This is just an example,
// so you can safely delete all default props below

export default {
  failed: 'Action {0} failed',
  success: 'Action was {0} successful'
}

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Action was {0} successful
```

### Relevant log output

```Shell
No
```

### Additional context

No

**Comment by Gregory-Han** [comment]
You only need to test multiple languages in the default creation.
Debug mode is normal, but there is an error when building.

**Comment by Gregory-Han** [comment]
You only need to test multiple languages in the default creation.
Debug mode is normal, but there is an error when building.

**Comment by pdanpdan** [comment]
It might be related to this: https://github.com/kazupon/vue-i18n/issues/710

Please move the request/discussion to vue-i18n

**Comment by Gregory-Han** [comment]
vitePlugins: [
        [
        ....
          {
...
            runtimeOnly: false,
...
          },
        ],
      ],

It's completed.
