### ISSUE TITLE
Dialog Plugin Bug

### ISSUE THREAD

**Issue by JoseCadenas** [quasarframework/quasar#16415]
### What happened?

I've encountered an issue with a function I've created to simplify the usage of $q.Dialog in my Quasar project. This function provides default settings, including i18n translations and other configurations tailored to my needs. One of these defaults involves setting up logic for a prompt.

However, if no data is provided for the prompt, it defaults to null. This creates a problem because, according to the Dialog API, the prompt parameter must be an object. In JavaScript, null is considered an object, but it lacks the required properties model and isValid, leading to a failure when creating the dialog.

To address this issue, I've added additional logic to remove the prompt key when it's null. Nevertheless, I believe it would be beneficial if Quasar could enhance this logic by ensuring that the prompt parameter is always an object with the necessary data, preventing such issues in the first place.

### What did you expect to happen?

I expected nulled prompt key to be ignored.

### Reproduction URL

https://codepen.io/josecadenas/pen/gOZjbgQ?editors=1111

### How to reproduce?

See codepen simple code to reproduce.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Plugins (quasar)

**Comment by HarisSpahija** [comment]
Wouldnt it be easier to filter out your settings before calling `$q.dialog`?

Lets say

```js
// assume this is what you get back
const settings = {
        title: "Quick example",
        message: "See JS dialog function... prompt is null.",
        prompt: null
      }
      
 const settingsWithoutNullKeys = Object.keys(settings).reduce((obj, key) => {
  if (settings[key] !== null) {
    obj[key] = settings[key];
  }
  return obj;
}, {});
      
const $q.dialog(settingsWithoutNullKeys )
```

Its important to understand the difference between `null` and `undefined`. Null is a value that declares an absence of it. If you try to access something from a null value javascript will by design throw an error. If you pass undefined it will return undefined as its a special value that indicates a declared value that isnt set yet. 

If this would be implemented in Quasar we will run into way more issues for having a special check for null values. I think its easier to implement this fix yourself on your settings generator function.

**Comment by yusufkandemir** [comment]
> This creates a problem because, according to the Dialog API, the prompt parameter must be an object

Yes, with specific properties that you must pass. It doesn't say it supports `null`. If you used TypeScript, it would give an error if you passed `null`:
![image](https://github.com/quasarframework/quasar/assets/6266078/96d59ff4-940f-4602-bff3-210622c0b05a)

We can't add runtime validation to every single place, it would introduce a great overhead and increase maintenance burden. We document the correct usage, add types, etc. so the users can learn how to use it correctly.

So, it works as expected, you need to use it in the way it's supposed to be used. You can filter the null values out as @HarisSpahija suggested above.
