### ISSUE TITLE
@click does not work in q-list

### ISSUE THREAD

**Issue by rofiuddin15** [quasarframework/quasar#1642]
hello, I have a problem in this version (0.15)
when implementing the @click function on q-item in q-list, the function does not work, but this works on previous versions.
```
<q-list link separator>
   <q-item @click="no += 1">
      <q-item-side>
	   <q-item-tile avatar>
		<img src="/statics/boy.png" alt="boy">
	   </q-item-tile>
	</q-item-side>
	<q-item-main>
	   <q-item-tile label>Kambing</q-item-tile>
	   <q-item-tile sublabel>duapah {{ no }}</q-item-tile>
	</q-item-main>	
  </q-item>
</q-list>
```

**Comment by rstoenescu** [comment]
Hi,

`@click.native`. Explanation here: http://quasar-framework.org/guide/quasar-upgrade-guide.html#Some-components-need-native-modifier-for-events-now
