### ISSUE TITLE
q-toggle: emit the new value when the animation ends

### ISSUE THREAD

**Issue by damvaz** [quasarframework/quasar#16429]
### What happened?

In componente QToggle, a `@update-model-value` event handler can perform a very heavy task (like updating a Pinia store or something similar job).

When that happens, there is a delay in the component's animation.

Only when the heavy task is finished, the animation continues.

### What did you expect to happen?

The toggle animation should end. 

Then the value change event should just be emitted in the component.

### Reproduction URL

https://codepen.io/damianvazquezJS/pen/LYMXGzZ?editors=0010

### How to reproduce?

1. Go to the provided reproduction link
2. Click on the toggle
3. Watch the delay in the animation/transition of thumb element

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by metalsadman** [comment]
you are blocking the main thread
