### ISSUE TITLE
breadcrumb - not resetting text-decoration: underline from -webkit-any-link

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/quasar#1643]
### Software version

NodeJs                                  9.5.0

Global packages
  NPM                                   5.6.0
  yarn                                  Not available
  quasar-cli                            0.15.3
  vue-cli                               2.9.3
  cordova                               Not available

Important local packages
  quasar-cli                            0.15.3  (Quasar Framework CLI)
  quasar-framework                      0.15.3  (Simultaneously build desktop/mobile SPA websites & phone/tablet apps with VueJS)
  quasar-extras                         1.0.2   (Quasar Framework fonts, icons and i18n.)
  vue                                   2.5.13  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                            3.0.1   (Official router for Vue.js 2)
  vuex                                  3.0.1   (state management for Vue.js)
  electron                              1.7.9   (Build cross platform desktop apps with JavaScript, HTML, and CSS)
  babel-core                            6.26.0  (Babel compiler core.)
  webpack                               3.11.0  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)

### What did you get as the error?

in:
Chrome 66.0.3346.8 (64-bit)
generated breadcrumb tags "a" had applied css underline decoration from a:-webkit-any-link rule.

### What were you expecting?
generated breadcrumb tags "a" without underline decoration.

### What steps did you take, to get the error?
any breadcrumb markup from quasar shows underline in that browser.

### Workaround

in app.vue:

    <style>
    a:-webkit-any-link {
      text-decoration: none !important;
    }
    </style>

**Comment by rstoenescu** [comment]
Will be available in v0.15.4. Thanks for reporting.
