### ISSUE TITLE
q-select: hide-selected wrong behaviour 

### ISSUE THREAD

**Issue by reitbauer** [quasarframework/quasar#16434]
### What happened?

When an option is selected from the list, the selected item is still displayed in the options list, but nothing is displayed in the q-select itself

<img width="1438" alt="image" src="https://github.com/quasarframework/quasar/assets/31218726/100827fb-6bd5-4bfa-a676-b91c295a07f6">

### What did you expect to happen?

The selected item should be displayed in the q-select itself, but no longer in the options list

### Reproduction URL

https://quasar.dev/vue-components/select#native-attributes-with-use-input

### How to reproduce?

1. Go to the Quasar site (see link)
2. Select an option in the q-select with the label "Hide selected"

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari

**Comment by metalsadman** [comment]
that's the correct behavior

**Comment by reitbauer** [comment]
Ah, okay. That doesn't make sense to me, but if that's the desired behavior, it's okay.
