### ISSUE TITLE
More explicit error messages

### ISSUE THREAD

**Issue by Yaty** [quasarframework/quasar#1644]
### Software version

Quasar: 0.15.3
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: Firefox 58.0.2

### What did you get as the error?

Hi ! I just migrated to 0.15.3, amazing work !!! However I encountered a little problem while migrating and I was thinking it could happen to other people.

I simply forgot to add 'Loading' to quasar.conf / framework / plugins and I had this error : `TypeError: this$1.__Vue is not a constructor`. 

And after some searching I found that this is coming from this  : https://github.com/quasarframework/quasar/blob/7f2bc3252dddcb9a9f155756437491fca5382923/src/plugins/loading.js#L47
So it was then obvious that I simply didn't add 'Loading' inside quasar.conf but it took me some time to find it.

### What were you expecting?

A warning from Quasar to tell me I didn't add the plugin I wanted to use inside quasar.conf.

### What steps did you take, to get the error?

In a vue single file component :

```js
  import {
    Loading,
  } from 'quasar';

  export default {
    mounted() {
      Loading.show();
    },
  };
```

and without 'Loading' inside quasar.conf > framework / plugins.

If you don't mind I'd like to contribute to Quasar by making a PR :).

**Comment by rstoenescu** [comment]
Sure. Please go ahead. Thanks.

**Comment by Yaty** [comment]
https://github.com/quasarframework/quasar/pull/1653

**Comment by rstoenescu** [comment]
Hi, I've re-evaluated the whole thing. I'm going to close this and the PR. While it indeed adds value, it makes the footprint bigger and adds overhead which is a no-go for low end mobiles. I guess it is better to rely on docs alone. A thousand sorry for taking your time to do this PR, but I hope you understand the reasoning :(
