### ISSUE TITLE
Some Quasar's components dont work well on the android EDGE browser.

### ISSUE THREAD

**Issue by Adn12** [quasarframework/quasar#16449]
### What happened?

Some Quasar's components dont work well on the android EDGE browser.
the width of text inside of components gets messed up when loading the page.
I thought there was a problem with my code, but then I observed the problem when browsing quasar's docs on my android device using edge.

![Example from quasar's own docs](https://github.com/quasarframework/quasar/assets/32844172/443de7db-3d6c-487f-8b70-f09b7fbf1f37)
this is apparent in buttons, qinput and qselect, among others.

It gets fixed temporarily if you turn the phone to landscape mode and then to portrait mode, but the problem returns whenever u reload the page.
Note: the problem does not exist on mobile chrome using the same device
Device: Samsung Galaxy s23+
OS: Android 13
OneUI:5.1
Browser: Edge

### What did you expect to happen?

I expected the components to show normally, like this 
![Example](https://github.com/quasarframework/quasar/assets/32844172/395c4f42-2023-46a3-b5e5-aa27100ad000)

### Reproduction URL

https://quasar.dev/options/platform-detection/

### How to reproduce?

1. Use an android device and EDGE browser
2. Go to the provided reproduction link
3. refresh the page 
4. change the page to landscape mode then to portrait to temporarily fix it
5. refresh the page to observe the problem again

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge, Android

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.18.0

Global packages
  NPM - 10.1.0
  yarn - Not installed
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 2.12.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by HarisSpahija** [comment]
Was able to reproduce this on S21 and S9 using Microsoft Edge app. Ill look into this if I can debug it. Desktop based applications and Chrome based apps didnt have this issue.

![image](https://github.com/quasarframework/quasar/assets/22589249/d42e12b7-e999-4700-b01e-401828355548)

**Comment by HarisSpahija** [comment]
So I dove into this issue a bit more, seems like border calculations are happening before fonts are being loaded. The problem is that fonts are always loaded in after the CSS has been loaded in. This is an issue on Microsoft Edge app, not something we can fix on Quasar's side.

**Comment by Adn12** [comment]
> So I dove into this issue a bit more, seems like border calculations are happening before fonts are being loaded. The problem is that fonts are always loaded in after the CSS has been loaded in. This is an issue on Microsoft Edge app, not something we can fix on Quasar's side.

Is there a way I can fix it on my app?

**Comment by pdanpdan** [comment]
Please open a ticket for Edge, with a simple reproduction.
