### ISSUE TITLE
QTime parameters in the event @update:model-value are swaped

### ISSUE THREAD

**Issue by bomb-kst** [quasarframework/quasar#16456]
### Description

According to the docs, https://quasar.dev/vue-components/time in event of API part.

<img width="573" alt="image" src="https://github.com/quasarframework/quasar/assets/118168383/b201dfe7-fe04-49e9-9327-ca2ba702b9e1">

In the meaning I think the value of this should be like '16:30' more than the detail of time but in the return of this. I got value with those props instead.

```
<q-input v-model="form.startTime" mask="time" :rules="['time']" label="เวลาที่เริ่ม">
        <template v-slot:prepend>
          <q-icon name="access_time" class="cursor-pointer">
            <q-popup-proxy cover transition-show="scale" transition-hide="scale" ref="qTimeProxyFrom">
              <q-time v-model="form.startTime" format24h
                @update:model-value="(details, value) => { console.log('details=>', details); console.log('value=>', value); }">
                <div class="row items-center justify-end">
                  <q-btn v-close-popup label="Close" color="primary" flat />
                </div>
              </q-time>
            </q-popup-proxy>
          </q-icon>
        </template>
        <template v-slot:append>
          <q-icon name="close" @click="form.startTime = ''" class="cursor-pointer" />
        </template>
      </q-input>
```

this is the result after I select the time
<img width="262" alt="image" src="https://github.com/quasarframework/quasar/assets/118168383/b1e6101f-5d7f-423f-ad3e-3a519428c075">

**Either the docs or the source code is wrong.**

### Documentation Section URL

https://quasar.dev/vue-components/time#qtime-api

### Flavour

None

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
It's not like if you name the first parameter `details` it will become the second parameter :)

**Comment by bomb-kst** [comment]
@pdanpdan 
> It's not like if you name the first parameter `details` it will become the second parameter :)

Yes, you are correct. It's kind of confusing. Thank you for recheck this. I would like to make this community as perfect sharing.

After change the parameter's position, it's correct as the docs.
```
@update:model-value="(value,` details) => {  console.log('value=>', value); console.log('details=>', details); }"
```
