### ISSUE TITLE
Platform detection no longer works in 0.15 when importing with Webpack

### ISSUE THREAD

**Issue by tmladek** [quasarframework/quasar#1646]
### Software version

Quasar: 0.15.13
OS: Linux (Debian Buster)
Node: v8.9.4
NPM: 5.6.0
Browsers: Firefox, Chrome
iOS: ///
Android: ///
Any other software related to your bug: ///

### JsFiddle (for Quasar v0.15+ only)
Not applicable.

### What did you get as the error?
Firefox:

    TypeError: __WEBPACK_IMPORTED_MODULE_2_quasar__.b.is is undefined

Chrome:

    Uncaught TypeError: Cannot read property 'cordova' of undefined

### What were you expecting?
An object representing the result of Quasar's platform detection.

### What steps did you take, to get the error?
As per the [documentation](http://quasar-framework.org/components/platform-detection.html), I included the `Platform` object outside of a Vue template/component:

    import { Platform } from 'quasar'

And then tried to query the `is` object:

    console.log(Platform.is.cordova)

This worked in 0.14 and the docs haven't changed for 0.15. As the API regarding platform detection hasn't otherwise changed, I am reporting this here, assuming the bug is in the implementation and not in the docs.

**Comment by pdanpdan** [comment]
Did you set Platform as plugin in quasar.conf.js?

**Comment by tmladek** [comment]
I did not as I didn't realize it moved to being a plugin (might be a good idea to mention it in the docs?), however adding it to the `framework.plugins` array did not make a difference:
    framework: {
      components: [
      // snip
      ],
      directives: [
        'Ripple'
      ],
      plugins: [
        'Notify', 'Platform'
      ]
    }

**Comment by rstoenescu** [comment]
Hi,

Please use our Discord channel https://discord.gg/5TDhbDg. You are misusing something. Don't know what, but the community will help you. I can assure you this is fully working. Thanks.
