### ISSUE TITLE
QUploader `extensions` property not working with drag and drop

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#1647]
At the moment, the `extensions` property is only relevant when selecting files with the OS file picker.

**Comment by rstoenescu** [comment]
Fix available in 0.15.4 shortly. Thanks for reporting!

**Comment by wc-matteo** [comment]
@rstoenescu the check is case-sensitive. For obvious reasons, it shouldn't be.

**Comment by rstoenescu** [comment]
Subsequent improvement available in 0.15.7
