### ISSUE TITLE
Chat Message Sanitization missing `name-html`

### ISSUE THREAD

**Issue by danilarb** [quasarframework/quasar#16490]
### Description

The Sanitization example in the Chat Message component shows the HTML code in the name instead of rendering it.

### Documentation Section URL

https://quasar.dev/vue-components/chat#example--sanitized-content

### Flavour

None

### Areas

Components (quasar)

**Comment by danilarb** [comment]
PR available here: https://github.com/quasarframework/quasar/pull/16491

**Comment by pdanpdan** [comment]
That is the idea, to show html because it is untrusted.
