### ISSUE TITLE
FAB - close on scroll

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#1649]
Hi!

Material Design guidelines says about `Speed dial`:
Tapping in the same spot should either activate the most commonly used action or **close** the open menu.

And in `Toolbar` section:
A toolbar that **disappears on scroll**...

So I think it can been useful that opened FAB closes when user start scroll. IMHO when user start scroll after open FAB, that mean "now I looking something other and expect to cancel my previous action".

I can make workaround

https://jsfiddle.net/t76ksc41/21/

that solve that scenario, but I think must be more elegant way, because my solution work always, not only after FAB opened. Or better way to add new property to FAB, like `closeOnScroll` if that behavior needed to developer.

Thanks!

**Comment by rstoenescu** [comment]
That's not a workaround. It's how you actually should do it. There are lots of use cases for FABs and dev should decide the behaviour on their own. Not good to bloat the framework with this.
