### ISSUE TITLE
q-btn `stack` prop weird behavior on undefined

### ISSUE THREAD

**Issue by Dtsiantaris** [quasarframework/quasar#16494]
### What happened?

Created a CustomButton wrapping q-btn and run into a minor styling issue that i thought it was unintentional. So basically i had a condition for the `stack` prop. 
```
 <q-btn
    class="relative"
    color="primary"
    unelevated
    :stack="customStack"
```
 
Where `customStack` was defined like any custom-like boolean prop would:

  ```
  defineProps({
       customStack: {
            type: Boolean,
            default: undefined
  },
```
  
- ### Actual behavior: 
When the condition is met the button stacks vertically, but when not provided, margin between the icon and the label are removed.
![image](https://github.com/quasarframework/quasar/assets/44876922/4ee3ef2f-efb3-4e0c-bb26-0b4842e3b4d1)

- `stack` is `undefined`

    

### What did you expect to happen?

-  ### Expected behavior: 
The q-btn label with its icon would conditionally stack vertically.
![image](https://github.com/quasarframework/quasar/assets/44876922/b9c0ad36-d455-483c-8ef9-e87439689dcb)

- left btn: `stack` is `true`                                                                              
- right btn:  `stack` is `false`

Documentation clearly states that `stack` is of type `Boolean` and not `Boolean | undefined`, but i believed this was maybe unintentional?
![image](https://github.com/quasarframework/quasar/assets/44876922/d6ab033a-c77e-4ac6-8a34-fca54a9bd569)

### Reproduction URL

https://codepen.io/dtsiantaris/pen/VwgwwNv

### How to reproduce?

-  Go to provided codepen link. 3 buttons are already set up.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Additional context

I know that the fix is as simple as this:
```
  defineProps({
       customStack: {
            type: Boolean,
            default: false
  },
```

But i say again, i believe this was unintentional from the Quasar team.

**Comment by rstoenescu** [comment]
The default for a Boolean prop should be `false`, not `undefined`.
Regardless, enhancement will be available on Quasar v2.14.1
