### ISSUE TITLE
Q-Select 'standout' and 'selected' slot not readable

### ISSUE THREAD

**Issue by jsormaz** [quasarframework/quasar#16493]
### What happened?

When using a q-select with the 'standout' prop, content in the 'selected' slot is not readable on focus.

Before focusing, no problem:
![image](https://github.com/quasarframework/quasar/assets/29971327/b96ba585-064f-4367-97a4-e22ba6c8a0b8)

After focusing:
![image](https://github.com/quasarframework/quasar/assets/29971327/08005441-d89b-4abe-8cf2-571cac59b143)

After focusing, dark:
![image](https://github.com/quasarframework/quasar/assets/29971327/e012e327-14c5-431e-bef4-557820d61670)

### What did you expect to happen?

text should remain readable when focused

### Reproduction URL

https://codepen.io/Sormaz/pen/YzBKOvr?editors=1010

### How to reproduce?

1. Go to reproduction link
2. Focus the field. Some text remains visible, some does not
3. Change to dark mode
4. Focus the field again. No text is visible

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You need some CSS - https://codepen.io/pdanpdan/pen/Vwgbwwd
