### ISSUE TITLE
QDate setEditingRange not showing expected view when navigation limitations are set

### ISSUE THREAD

**Issue by Zoey1988** [quasarframework/quasar#16500]
### What happened?

STR 1: 
When `navigation-min-year-month` is set to e.g `2024/01`, and then when we want to use `setEditingRange({ year: 2023, month: 12, day: 3 })` on a `range` date-picker,  date picker goes to December 2024.

STR2:
Same thing happen when `navigation-max-year-month` is set to e.g `2023/12` and we want to use `setEditingRange({ year: 2024, month: 1, day: 3 })`, date picker goes to January 2023.

### What did you expect to happen?

STR1: We expect the date picker to be on January 2024.

STR2: We expect the date picker to be on December 2023.

### Reproduction URL

https://codepen.io/zoey1988/pen/Jjxjxry

### How to reproduce?

1: Go to provided link
2: Note the date picker view not being on min or max navigation year month.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.13.1
