### ISSUE TITLE
$ in code sippets - remove it or skip on copy

### ISSUE THREAD

**Issue by gander** [quasarframework/quasar#16505]
### Description

The "copy snippet" button does not ignore the "$" character at the beginning of the snippet. Why? Apart from that, there must be some logical reason why shell snippets still use this character, so it should be equally logical to automatically omit this character when copying. Otherwise, any use of such a snippet, no matter how long it is, requires going to position 1 and removing the unwanted character.

![image](https://github.com/quasarframework/quasar/assets/421597/2adb6d2c-dfd5-4759-99fc-3d7ba224bd1a)

I've found it in this section for now, but I suspect it's in a lot of places. It's terribly irritating to keep remembering this character when I use copy snippet.

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/developing-browser-extensions/preparation

### Flavour

None

### Areas

BEX Mode

**Comment by rstoenescu** [comment]
Fix will be available on next docs deployment
