### ISSUE TITLE
Docs: rollup-plugin-copy example JSON

### ISSUE THREAD

**Issue by andredifs** [quasarframework/quasar#16508]
### Description

The rollup-plugin-copy example contains a JSON that is not formatted correctly.

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/handling-vite#example-rollup-plugin-copy

### Flavour

None

### Areas

Plugins (quasar)

**Comment by andredifs** [comment]
PR: https://github.com/quasarframework/quasar/pull/16509

**Comment by rstoenescu** [comment]
Thanks for reporting and for PRing!
Changes will be available on next docs deployment.
