### ISSUE TITLE
Icon position display error（material-icons）

### ISSUE THREAD

**Issue by bibibala** [quasarframework/quasar#16515]
### What happened?

Some icons appear normally and some look like the picture.

### What did you expect to happen?

Some icons appear normally and some look like the picture.![微信图片_20231025123413](https://github.com/quasarframework/quasar/assets/57165565/a77745ba-db91-49f9-914c-a242c60f2370)

### Reproduction URL

https://codepen.io/ZSQNightwish/pen/vYbOXLY

### How to reproduce?

just like this pic

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by bibibala** [comment]
> ### What happened?
> Some icons appear normally and some look like the picture.
> 
> ### What did you expect to happen?
> Some icons appear normally and some look like the picture.![微信图片_20231025123413](https://user-images.githubusercontent.com/57165565/277874288-a77745ba-db91-49f9-914c-a242c60f2370.png)
> 
> ### Reproduction URL
> https://codepen.io/ZSQNightwish/pen/vYbOXLY
> 
> ### How to reproduce?
> just like this pic
> 
> ### Flavour
> Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)
> 
> ### Areas
> Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)
> 
> ### Platforms/Browsers
> Chrome
> 
> ### Quasar info output
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Additional context
> _No response_

**Comment by pdanpdan** [comment]
There is no icon with that name on default material icons, so the rest is white space
