### ISSUE TITLE
Comments will cause the QDialog Plugin to throw errors

### ISSUE THREAD

**Issue by carvenl** [quasarframework/quasar#16526]
### What happened?

When customizing components, comments can cause the QDialog component to throw errors：
```
[Quasar] Incorrectly defined Dialog component
```

### What did you expect to happen?

If you delete this comment or write the comment inside QDialog, this Error will not occur.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-bm3tua?file=src%2Fpages%2FIndexPage.vue,src%2Fcomponents%2FMyDialog.vue

### How to reproduce?

1. Clicking the Btn in IndexPage.vue will cause the console to report an error `[Quasar] Incorrectly defined Dialog component`. 
2. If you delete the comments in MyDialog.vue, this Error will not occur.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Plugins (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
duplicate #16153
