### ISSUE TITLE
QAutocomplete - when Popover is showing you can't type space character

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#1652]

**Comment by wc-matteo** [comment]
@rstoenescu now the enter key doesn't work anymore to select the option.
The issue is the the case for enter and space is the same:
```js
case 13: // ENTER key
case 32: // SPACE key
if (this.$refs.popover.showing && !this.inputEl) {
```

**Comment by wc-matteo** [comment]
https://github.com/quasarframework/quasar/pull/1658
