### ISSUE TITLE
QTabs issue when followed by q-form

### ISSUE THREAD

**Issue by alexandretperez** [quasarframework/quasar#16532]
### What happened?

QTabs completely breaks if it is followed by q-form class. E.g:
```
<q-tabs v-model="tab" no-caps align="justify" narrow-indicator class="bg-red text-white shadow-2">
      <q-tab name="mails" label="Mails"></q-tab>
      <q-tab name="alarms" label="Alarms"></q-tab>
      <q-tab name="movies" label="Movies"></q-tab>
</q-tabs>
<form class="q-form">
     <div class="row q-col-gutter-xl">
         <div class="col-12">Hover anywere and try click on it (Completely broken)</div>
     </div>
</form>
```

It partially breaks if q-form class appears in some level.

```
<q-tabs v-model="tab" no-caps align="justify" narrow-indicator class="bg-red text-white shadow-2">
    <q-tab name="mails" label="Mails"></q-tab>
    <q-tab name="alarms" label="Alarms"></q-tab>
    <q-tab name="movies" label="Movies"></q-tab>
</q-tabs>
<div class="q-pa-lg">
    <form class="q-form">
      <div class="row q-col-gutter-xl">
        <div class="col-12">Hover the mouse below the labels (Partially broken)</div>
      </div>
    </form>
</div>
```

### What did you expect to happen?

q-form class should not interfere on QTabs behavior.

### Reproduction URL

https://codepen.io/Alexandre-Toledo-Perez/pen/BaMjrJv

### How to reproduce?

The instructions are described in the reproduction link

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

**Comment by pdanpdan** [comment]
You are using `row q-col-gutter-xl` inside the form element and it generates a `-48px` margin.
`q-form` class only sets `position: relative`, but in your case (the form content is moved in the same space as the QTabs) relative position means it is also above.
