### ISSUE TITLE
quasar d, Unknown command

### ISSUE THREAD

**Issue by wiledd** [quasarframework/quasar#16537]
### Description

hello,
I am installing Quasar 2.13.0 on windows 11 and I can't run the project (quasar d) shows the message "Global Quasar CLI • ⚠️ Error Unknown command "d"".

I tried installing with npm and yarn and I get the same result. I tried quasar buil, also the same result

C:\Users\wiled>npm --version
10.1.0
C:\Users\wiled>node --version
v20.9.0
C:\Users\wiled>quasar --version
@quasar/cli v2.3.0

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by wiledd** [comment]
hello @pdanpdan, please was this topic closed because it was already answered in some other report?

**Comment by pdanpdan** [comment]
You are not in the project folder, or if you are you did not install the packages.

Also try node v18

**Comment by wiledd** [comment]
😳 thanks!!
