### ISSUE TITLE
Quasar not available after npm install -g quasar-cli on mac

### ISSUE THREAD

**Issue by trsiddiqui** [quasarframework/quasar#1655]
### Software version

Quasar: 0.15.3
OS: mac os High Sierra 10.13.3
Node: 9.6.1
NPM: 5.6.0
Browsers: NA
iOS: NA
Android: NA
Any other software related to your bug: might be related to npm on mac, apparently it worked fine on windows earlier.

### What did you get as the error?
-bash: quasar: command not found
### What were you expecting?
to be able to execute quasar dev on quasar-play code base
### What steps did you take, to get the error?
I executed npm install -g quasar-cli, executed it with sudo, executed after updating node npm brew. Same issue. Restarted terminal, laptop but no difference.

**Comment by rstoenescu** [comment]
Hi,

1. This should have gone to Quasar CLI repo.
2. You need to fix your Nodejs + NPM installation. Please look for help on our Discord.

Thanks.

**Comment by trsiddiqui** [comment]
My bad, sorry.

**Comment by rstoenescu** [comment]
No problem. Glad u figured it out.

**Comment by chdzma** [comment]
I have the same problema afer run npm install, any solution for this?

**Comment by rstoenescu** [comment]
@chdzma Hi, join our Discord. Unfortunately simply saying it's not working doesn't help us in helping you.

**Comment by s-light** [comment]
for all that landing here through a websearch:
on discord have a look in the `quasara-cli` or `other` channel.
for example [this is my request](https://discordapp.com/channels/415874313728688138/415882291336839168/589091339682054181) regarding this. (hopefully the link really points to my post ;-) )

and this is what i have found & done;
during installation i saw that it mentioned `/usr/local/Cellar/node/12.04.0/bin/quasar`
i checked with `ls -la /usr/local/bin/` and in there was node with a symlink - but not quasar..
so i added that manually with:
`ln -s ../Cellar/node/12.04.0/bin/quasar /usr/local/bin/quasar`

Please be careful with such manual things... they easily can break at the next update or what ever else ....

**Comment by valjar** [comment]
Same case for me as @s-light reported.

I have manually linked the quasar in my /usr/local/bin/ directory
I have npm packages in my home folder so the command was following
`sudo ln -s /Users/valor/.npm-packages/bin/quasar /usr/local/bin/`

Now it working. Thank you

**Comment by alexphdz** [comment]
Hi!

In my case  i did the following:

1. -Go to /Users/[user]/node_modules/@quasar/cli and there is a "bin" folder
2.- Copy the path of that "bin" folder and added to .zshrc file

Example:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/58675305/203897960-0ea4dfd4-6102-46dc-b335-d86267b05fe8.png">

Hope this will help you :)
