### ISSUE TITLE
How to install and config Karma and mocha to project created by quasar framework?

### ISSUE THREAD

**Issue by diepvv** [quasarframework/quasar#1656]
### Software version
I created a project by quasar cli V0.14.9. Now how do i ? in order to write a class unit test for a componmnet? i dont know config? Can you suggest me to write a unit test for a quasar cli project.

**Comment by rstoenescu** [comment]
Hi, Please redirect this to the appropriate repo. Thanks. https://github.com/quasarframework/quasar-template-default
