### ISSUE TITLE
QMenu max-width bug in a round QBtn included in a QHeader

### ISSUE THREAD

**Issue by Jejec** [quasarframework/quasar#16566]
### What happened?

I create a Qmenu in a round QBtn itself included in a QHeader but when I click on it it returns to the line at the menu level

### What did you expect to happen?

It should not wrap at the menu item level if a minimum size has not been set.
Qmenu adds a max-width that you calculate but the calculation is visibly wrong each time by 1 pixel, because if I add 1 pixel more to the max-width the problem is corrected.
In the example "Item test bug" should be on the same line

### Reproduction URL

https://codepen.io/jcauz/pen/KKJmKgz?editors=1010

### How to reproduce?

To reproduce, simply put a QMenu in a QBtn with the "round" attribute itself in a QHeader.
In the Qmenu I use lists and you have to put an element with at least 2 words to see it

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Use the `no-wrap` property on your QItemSection(s).
The browser itself will dictate how the menu is displayed, unless you tell QMenu that you want a certain width etc.

**Comment by Jejec** [comment]
Indeed the no-wrap corrects the problem but then we have to put it on all QItemSections

**Comment by rstoenescu** [comment]
Put it on all. There cannot be any automatic behavior in regards to this at the framework level.

**Comment by Download** [comment]
I would suggest to re-open as I too see the weird '1 pixel too few' issue, where the content wraps because the `menu` has a width set on it that is 1 pixel less than needed. If I increase that width by just 1 the issue vanishes. It is consistently 1 pixel so there seems to be something off in the calculation of the menu size.

**Comment by ssendev** [comment]
I am on v2.17.1 and have the same 1px to small issue. Unfortunately I can't get it to reproduce on CodePen. A workaround that worked in my case was to append a space to the Item Text.
