### ISSUE TITLE
Api explorer Qfile 404

### ISSUE THREAD

**Issue by dongwa** [quasarframework/quasar#16569]
### Description

![image](https://github.com/quasarframework/quasar/assets/38457491/adcb0fa7-3823-4d02-89a9-378ebb57ac9c)

![image](https://github.com/quasarframework/quasar/assets/38457491/663e0c1e-7c00-49b1-9025-df97f0001873)

it shoule be `/vue-components/file-picker` not `vue-components/file`

### Documentation Section URL

https://quasar.dev/api-explorer

### Flavour

None

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available on next docs deployment.
