### ISSUE TITLE
Can’t access preprocessorOptions in extendViteConf.css

### ISSUE THREAD

**Issue by Valgri** [quasarframework/quasar#16573]
### What happened?

Can’t access preprocessorOptions in extendViteConf.css
using this docs https://quasar.dev/quasar-cli-vite/css-preprocessors

returns undefined in dev mode

### What did you expect to happen?

I can access this variable and extend scss options

### Reproduction URL

//

### How to reproduce?

Install project with quasar cli. Try to access preprocessorOptions in extendViteConf using this 
Configuration from docs
https://quasar.dev/quasar-cli-vite/css-preprocessors

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
That's because Quasar does not injects anything in the `css` so it's not created yet. However, you can create the prop on `viteConf` object.

**Comment by Dean-ZhenYao-Wang** [comment]
> 那是因为类星体没有注入任何东西，所以它还没有被创造出来。但是，您可以在对象上创建道具。`css``viteConf`

extendViteConf (viteConf) {
        viteConf.css.postcss.xxxxxxxx
      },
returns undefined in dev mode

**Comment by Valgri** [comment]
> > 那是因为类星体没有注入任何东西，所以它还没有被创造出来。但是，您可以在对象上创建道具。`` css``viteConf ``
> 
> extendViteConf (viteConf) { viteConf.css.postcss.xxxxxxxx }, returns undefined in dev mode

Thanks, I figured out how to do it.
