### ISSUE TITLE
Quasar init error

### ISSUE THREAD

**Issue by fak1r** [quasarframework/quasar#16575]
### What happened?

I start new project with `npm init quasar` then, after choose settings I have a notice "Quasar • ⚠️  Could not auto install dependencies. Probably a temporary npm registry issue?" and error "npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED". I try `npm install` in project folder, but have same error. I updated my Node js, then I catched new warnings "Unsupported engine", I used version 9.7.2. before and had the same result without this warning.

Log of my trying to init:

`PS D:\Vue\Quasar> npm init quasar

 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

√ What would you like to build? » App with Quasar CLI, let's go!
√ Project folder: ... quasar-project
√ Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
√ Pick script type: » Javascript
√ Pick Quasar App CLI variant: » Quasar App CLI with Vite
√ Package name: ... quasar-project
√ Project product name: (must start with letter if building mobile apps) ... Quasar App
√ Project description: ... A Quasar Project
√ Author: ... fak1r
√ Pick your CSS preprocessor: » Sass with SCSS syntax
√ Check the features needed for your project: »

 Quasar • Generating files...

 - index.html
 - postcss.config.cjs
 - quasar.config.js
 - README.md
 - .editorconfig
 - .gitignore
 - .npmrc
 - jsconfig.json
 - package.json
 - public/favicon.ico
 - src/App.vue
 - .vscode/extensions.json
 - .vscode/settings.json
 - public/icons/favicon-128x128.png
 - public/icons/favicon-16x16.png
 - public/icons/favicon-32x32.png
 - public/icons/favicon-96x96.png
 - src/assets/quasar-logo-vertical.svg
 - src/boot/.gitkeep
 - src/components/EssentialLink.vue
 - src/layouts/MainLayout.vue
 - src/pages/ErrorNotFound.vue
 - src/pages/IndexPage.vue
 - src/router/index.js
 - src/router/routes.js
 - src/css/app.scss
 - src/css/quasar.variables.scss

 Quasar •  SUCCESS  • The project has been scaffolded

√ Install project dependencies? (recommended) » Yes, use npm

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'quasar-project@0.0.1',
npm WARN EBADENGINE   required: { node: '^18 || ^16 || ^14.19', npm: '>= 6.13.4', yarn: '>= 1.21.1' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '9.7.2' }
npm WARN EBADENGINE }
npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! 241C0000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation failed:c:\ws\deps\openssl\openssl\providers\implementations\ciphers\ciphercommon_gcm.c:320:
npm ERR!

npm ERR! A complete log of this run can be found in: C:\Users\rezax\AppData\Local\npm-cache\_logs\2023-11-10T11_31_26_845Z-debug-0.log

 npm FAILED...

 Quasar • ⚠️  Could not auto install dependencies. Probably a temporary npm registry issue?

To get started:

  cd quasar-project
  yarn #or: npm install
  yarn lint --fix # or: npm run lint -- --fix
  quasar dev # or: yarn quasar dev # or: npx quasar dev

Documentation can be found at: https://v2.quasar.dev

Quasar is relying on donations to evolve. We'd be very grateful if you can
read our manifest on "Why donations are important": https://v2.quasar.dev/why-donate
Donation campaign: https://donate.quasar.dev
Any amount is very welcome.
If invoices are required, please first contact Razvan Stoenescu.

Please give us a star on Github if you appreciate our work:
  https://github.com/quasarframework/quasar

Enjoy! - Quasar Team

PS D:\Vue\Quasar> cd quasar-project
PS D:\Vue\Quasar\quasar-project> npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'quasar-project@0.0.1',
npm WARN EBADENGINE   required: { node: '^18 || ^16 || ^14.19', npm: '>= 6.13.4', yarn: '>= 1.21.1' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '9.7.2' }
npm WARN EBADENGINE }
npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! 40200000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation failed:c:\ws\deps\openssl\openssl\providers\implementations\ciphers\ciphercommon_gcm.c:320:
npm ERR!

npm ERR! A complete log of this run can be found in: C:\Users\rezax\AppData\Local\npm-cache\_logs\2023-11-10T11_32_46_120Z-debug-0.log`

### What did you expect to happen?

Create new project with no errors

### Reproduction URL

https://codepen.io/rstoenescu/pen/nolink

### How to reproduce?

1. npm init quasar  
2. choose all default or different settings

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by pdanpdan** [comment]
Use node 18
`npm WARN EBADENGINE required: { node: '^18 || ^16 || ^14.19', npm: '>= 6.13.4', yarn: '>= 1.21.1' },`
