### ISSUE TITLE
Ambiguous q-time options function return type

### ISSUE THREAD

**Issue by Smrtnyk** [quasarframework/quasar#16587]
### What happened?

https://github.com/quasarframework/quasar/blob/dev/ui/src/components/time/QTime.json#L58
This line suggests that returns is null, but example returns a boolean
This causes issue with typescript, in case you create a predicate function and assign it to options prop.

### What did you expect to happen?

It is clarified which one it is, if it is null, then example should be adjusted, otherwise type should be adjusted.

### Reproduction URL

https://github.com/quasarframework/quasar/blob/dev/ui/src/components/time/QTime.json#L58

### How to reproduce?

Go to
https://quasar.dev/vue-components/time
options suggests that it returns void, and in here
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/time/QTime.json#L58 it specifies null,
And example returns a boolean.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.14.1
