### ISSUE TITLE
Carousel  @slide event is not emitting

### ISSUE THREAD

**Issue by vdmani** [quasarframework/quasar#1659]
### Software version

Quasar: v0.15.3
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: Chrome 64.0.3282.186 
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Carousel component's @slide event is not emitting. I can see only slide-direction event in the vue dev tools.

### What were you expecting?
slide event to be emitted so that I can write a method to handle it.
### What steps did you take, to get the error?
I tried with basic example given on the site. When slide to next or previous slides, I can see only slide-direction event being emitted, but not the slide event
![eventconsole](https://user-images.githubusercontent.com/28945999/36724879-8dabb536-1bda-11e8-94de-84dc178aa083.png)

**Comment by rstoenescu** [comment]
Will be available in 0.15.4.
Mind that you can use a v-model + watcher too.

**Comment by vdmani** [comment]
Thank you for fixing it so quickly! 

> Mind that you can use a v-model + watcher too.
Sorry, I am not aware of this. Can you point to any documentation for this?

**Comment by rstoenescu** [comment]
<img width="474" alt="carousel" src="https://user-images.githubusercontent.com/4665641/36731600-01f1d698-1bd4-11e8-90a7-a6354bb3c775.png">


http://quasar-framework.org/components/carousel.html#Using-v-model-amp-some-custom-controls-autoplay-button-progressbar-fullscreen-toggle

**Comment by vdmani** [comment]
Got it. Thanks!

**Comment by SobiaNodesol** [comment]
my quasar slider show spark when  slides end . can you resolve my issue please
