### ISSUE TITLE
Pull To refresh not allowing scroll

### ISSUE THREAD

**Issue by abordeau** [quasarframework/quasar#166]
Hello Everyone.
I have a problem with the Pull To refresh component in my app :
I can't scroll down the list normally when i'm inside this component on my smartphone, but no problem with my laptop and mouse/pad
I run into the same issue in the Quasar Play App. I'm using a Samsung Galaxy s6 on Android 6.0.1.
Does anyone have the same problem with his device ?

**Comment by rstoenescu** [comment]
Confirmed. This was broken in v0.8. Working on a fix. Thanks.
