### ISSUE TITLE
Access-Control-Allow-Origin header force set to * inside ssrMiddleware causing CORS issues

### ISSUE THREAD

**Issue by FadhiliNjagi** [quasarframework/quasar#16609]
### What happened?

I've been scratching my head for the last few days wondering why my CORS configuration does not work with Quasar SSR while it works with ordinary Quasar PWA/SPA + Node API. So I created a new Quasar project and quickly found out that the error was in the `ssrMiddleware` function and not my code.

The `Access-Control-Allow-Origin` header is being set to `*` and all attempts at overriding it did not work. This seems to be happening only within ssrMiddleware as routes outside them are not affected. The headers for the preflight request are correct. However, the main request has an `Access-Control-Allow-Origin` header set to *, even when CORS middleware is removed. This makes the browser block the main request.

![image](https://github.com/quasarframework/quasar/assets/54543510/533cc42f-c102-45ca-9500-5fffc8ef3566)

`server.js`
```js
import express from 'express'
import cors from 'cors'

export const create = ssrCreate((/* { ... } */) => {
  const app = express()
  if (process.env.PROD) {
    app.use(compression())
  }

  app.use(cors({
    origin: true,
    credentials: true
  }))
  app.get('/hi', (req, res) => {
    res.send('Hello World!') // This works fine. Correct CORS headers.
  })

  return app
})
```

`middlewares/myMiddleware.js`
```js
import { ssrMiddleware } from 'quasar/wrappers'

export default ssrMiddleware(({ app, resolve }) => {
  app.get('/hello', (req, res) => {
    res.send('Hello World!')  // Doesn't work right.  Access-Control-Allow-Origin is set to * even when cors is removed. Overwriting the header does not work either.
  })

  app.get(resolve.urlPath('/heya'), (req, res) => {
    res.send('Hello World!')  // Doesn't work right.  Access-Control-Allow-Origin is set to * even when cors is removed. Overwriting the header does not work either.
  })
})
```

### What did you expect to happen?

I expected the Access-Control-Allow-Origin to mirror the origin host when cors is enabled and to be omitted altogether when cors is disabled. I don't think this is intended behavior.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-x18kyd?file=src-ssr%2Fmiddlewares%2Frender.js

### How to reproduce?

1. Go to the provided Stackblitz reproduced link. It's just a fork of the official Quasar StackBlitz with only `server.js` and `middlewares/render.js` modified. That modification entails adding the 3 test routes and the CORS middleware.
2. In the StackBlitx terminal, type `CTRL + C` to stop the dev server then type `quasar dev -m ssr` to start the dev server in SSR mode.
3. On a different tab, navigate to Stackblitz.com [homepage](https://stackblitz.com). Open DevTools and then console. Type the following lines into the console and observe the outcome. Replace the URL in fetch appropriately. This simulates a cross-origin 

**Test 1**
```js
fetch('https://quasarframeworkx18kyd-zihp--9100--6a615fc0.local-corp.webcontainer.io/hi', { method: 'GET', credentials: 'include' }).then(res => res.text()).then(data => console.log(data))
```

**Test 2**
```js
fetch('https://quasarframeworkx18kyd-zihp--9100--6a615fc0.local-corp.webcontainer.io/hello', { method: 'GET', credentials: 'include' }).then(res => res.text()).then(data => console.log(data))
```

**Test 3**
```js
fetch('https://quasarframeworkx18kyd-zihp--9100--6a615fc0.local-corp.webcontainer.io/heya', { method: 'GET', credentials: 'include' }).then(res => res.text()).then(data => console.log(data))
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SSR Mode

**Comment by rstoenescu** [comment]
Hi,

That would be the underlying Vite middleware tampering with the Response Headers.
However, no tampering is done when building and running the production server.

**Comment by FadhiliNjagi** [comment]
@rstoenescu Any idea how I might override Vite middleware settings? I'm new to SSR, and I'm running into a number of issues with preset headers like CORS of 'X-Frame-Options: SAMEORIGIN' and so far my attempts to override them has failed. I never ran into these issues when my API was a separate Express project.

**Comment by pdanpdan** [comment]
Have you tried https://www.google.com/search?q=vite+x-frame-options?

**Comment by FadhiliNjagi** [comment]
`frame-ancestors` CSP directive was the culprit. I just adjusted my helmet configuration:
```js
// server.js

import helmet from 'helmet'
//...
app.use(helmet({
    contentSecurityPolicy: {
      directives: {
        frameAncestors: [process.env.ADMIN_URL, process.env.FRONTEND_URL]
      }
    }
}))
```
As for the CORS middleware, I overrode the Vite server CORS configuration:
```js
 ...
  build: {
    ...
    extendViteConf (viteConf) {
        viteConf.server.cors = false
    }
```
My browser (Brave) and the HMR for Quasar SSR weren't helping either. I was questioning my sanity until I realised they were showing cached versions of the code instead of the most recent versions. Manually restarting the SSR dev server after saving changes to `server.js` worked.

Thanks for the feedback. It helped.
