### ISSUE TITLE
Nesting rows with gutters produces broken  layout

### ISSUE THREAD

**Issue by arnKo** [quasarframework/quasar#16608]
### What happened?

When nesting flex elements with the helper class `q-gutter-X`, the inner elements do not get aligned properly. 
When nesting elements with the helper class `q-col-gutter-X`, the layout is a broken.

### What did you expect to happen?

When nesting flex elements and using the provided helper classes, the elements should be aligned properly.

### Reproduction URL

https://jsfiddle.net/8xrpnq9y/41/

### How to reproduce?

The upper row of elements with red border use `q-gutter-md`. On the second level of nesting, we see that the elements are not aligned in their parent but have an offset to the right and bottom direction.

The lower row of elements with blue border use `q-col-gutter-md`.  The layout is broken. Even the 2. element on the first level of nesting, that is properly aligned in the first example, is completely off.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Quasar info output

```Shell
Operating System - Linux(5.15.0-88-generic) - linux/x64
NodeJs - 16.20.2

Global packages
  NPM - 8.19.4
  yarn - 1.22.10
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.8 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.53.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - host
  br-6d31cd3b2533 - 172.23.0.1
  br-b44fa4fa93fa - 172.24.0.1
  br-3e634fdd1237 - 172.27.0.1
```

**Comment by pdanpdan** [comment]
You mean the big WARNING here https://quasar.dev/layout/grid/gutter#pros-cons-and-how-to-workaround-problems-q-gutter-size-vs-q-col-gutter-size?

Wrap children in div if you want to apply gutter inside
Or define you own gutter classes to use `gap`

https://jsfiddle.net/4k6ecd35/

**Comment by arnKo** [comment]
Indeed, there is a warning that I did not recognize to be the source of my problem.

**Comment by RuudFreshfilter** [comment]
> You mean the big WARNING here https://quasar.dev/layout/grid/gutter#pros-cons-and-how-to-workaround-problems-q-gutter-size-vs-q-col-gutter-size?
> 
> Wrap children in div if you want to apply gutter inside Or define you own gutter classes to use `gap`
> 
> https://jsfiddle.net/4k6ecd35/

I tried modifying this example to create a layout that's kind of rotated 90 degrees (https://jsfiddle.net/msxz8j7e/1/). The probem that I'm getting is that the 2nd horizontal gutter is higher than the first. The issue is solved when removing the gutter in the 2nd col. Do you think you can help me?

**Comment by pdanpdan** [comment]
https://jsfiddle.net/wdpqy0nc/3/

**Comment by RuudFreshfilter** [comment]
> https://jsfiddle.net/wdpqy0nc/3/

Oh thanks! Any way to get rid of the bottom space as well?
