### ISSUE TITLE
[QSlider] Step starts from min instead of inner min, resulting in wrong stepping if using floats

### ISSUE THREAD

**Issue by Tofandel** [quasarframework/quasar#16614]
### What happened?

The slider starts at 4$, when clicking anywhere on it, you get steps always ending with .8

### What did you expect to happen?

Since `innerMin` is the actual minimum selectable value, the steps should be starting from that instead and be whole numbers

### Reproduction URL

https://codepen.io/Tofandel/pen/NWoymZm?editors=101

### How to reproduce?

1. Go to the reproduction link
2. Click anywhere on the slider
3. Notice the value is `x.8 $` and it doesn't match with any of the marker label steps
4. If you click on 3, the slider caps it to inner min and stays at `3 $`
5. If you use the keyboard arrows, then you get the correct behavior

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron

### Additional context

The issue seems to be coming from this function which uses `min` and `max` instead of `innerMin` and `innerMax`
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/slider/use-slider.js#L236-L250

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.14.1
