### ISSUE TITLE
Deploy to zeit with now not working - Missing `start`

### ISSUE THREAD

**Issue by kjetilge** [quasarframework/quasar#1661]
When attempting to deploy my PWA to zeit with now from the root folder I get:
```
Error! Missing `start` (or `now-start`) script in `package.json`. See: https://docs.npmjs.com/cli/start
```
I succeeded when I deployed using script:
```
"deploy-now": "npm run build && cd dist && now ."
```

But I would like for the app to be build on zeit using the now.json file I have in the root. How can this be achieved ?

**Comment by rstoenescu** [comment]
Hi,

Please use our Discord for questions. Github is reserved only for bugs.
Also take a good read on Zeit's docs. In your case, add a "start" script under "scripts" in your package.json. Thanks.
