### ISSUE TITLE
QEditor - Unexpected span while defining list from selection in safari

### ISSUE THREAD

**Issue by juliodctg** [quasarframework/quasar#16624]
### What happened?

In the q-editor (safari only), when selecting some text then making it a list (ordered or unordered), the HTML content is being edited from this : 
Some text
To This:
<ul><li><span style="background: var(--q-dark);">Some text</span><br></li></ul>

### What did you expect to happen?

I was expecting to get this instead:
<ul><li>Some text</li></ul>

### Reproduction URL

https://quasar.dev/vue-components/editor#example--kitchen-sink

### How to reproduce?

1) Go to quasar doc : https://quasar.dev/vue-components/editor#example--kitchen-sink
2) Go to kitchen sink example
3) Enter "Some text" and select it
4) Click on the icon to make it an (un)ordered list.
5) Click on the view source icon (last icon in toolbar)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Safari

### Additional context

Tested only on Safari and Chrome. On Chrome got the expected code.

**Comment by rstoenescu** [comment]
QEditor relies on document.execCommand() under the covers. This means that Quasar is not in charge of the algorithms for creating or parsing the current state for the HTML output. Should you really need your output to be precise, you should look for other Vue components like this one from the Vue ecosystem (there are plenty of wrapper components for well-known WYSIWYG libs).
