### ISSUE TITLE
How to switch from fontawesome to fontawesome PRO icons?

### ISSUE THREAD

**Issue by mjmare** [quasarframework/quasar#1662]
Please include instructions on how to use fontawesome 5 pro icons. TIA

**Comment by rstoenescu** [comment]
Haven't I answered already in Discord? Sorry if I'm making a confusion regarding who you are :)

**Comment by mjmare** [comment]
Maybe you have. I'm sure there is more than 1 FA Pro customer ;-)
Could you add your answer to the docs perhaps? TIA

**Comment by rstoenescu** [comment]
Doc update will include this. Available along 0.15.5 release very soon.

**Comment by rstoenescu** [comment]
Please consider talking to your superiors about backing up Quasar too. It's not only Fontawesome that needs help. Much appreciate it!
