### ISSUE TITLE
v0.15 QDatetime Prevent Prompting of Time when Selecting Just a Date

### ISSUE THREAD

**Issue by snow-drop** [quasarframework/quasar#1663]
I would like to suggest that the QDatetime component with ```type="datetime"``` should prevent prompting for time when a date is clicked on the component because sometimes it becomes annoying especially if you just want to change just the date. The component would still require you to select a time. 

There is a workaround to skip the selection of time by following this procedure:
1. Click on the QDatetime component. This will display the QDatetime component
2. Click the desired date.
3. After clicking the desired date, the component will prompt for time.
4. Navigate your mouse away on the QDatetime component and click on other parts of the web page.

After following this procedure though and clicking again on the QDatetime component, you would still be prompted for time so you would need to click on the month option on the left side of the QDatetime component to change the display from time to date display.

With this, I would like also to suggest that after setting the date (and time if time is set) and clicking on the QDatetime again, the component should reset the display to date display instead of time display and would only display the time display if the user selects/clicks the time option on the left part of the component.

Another suggestion is to use props to set these functionalities so that these will only be set if needed.

These suggestions were only collected from a small number of users but might help other users to use the QDatetime much easier. Thanks!

**Comment by olegvakulenko** [comment]
@snow-drop 
Hi! I agree with you and want to describe my case. In my app user select date with time for event. When it doing for first time (when value `undefined`) than entering data and than time is absolutely correct. But when I try to edit previous value I forced to enter date AND then time and only after that popover close with new value. So I can't change only date or only time. I understand why popover doesn't have `OK/Cancel` button, but it is lack of flexibility. May be it more useful to prompt date with time when current value `undefined`, but when value exist edit only date or only time and close popover, so user decides what part he want to change.
Thanks!

**Comment by snow-drop** [comment]
For the mean time, I develop a custom date time picker using QDatetimePicker and QSlider. See below:

![screenshot_20180305_153634](https://user-images.githubusercontent.com/34905419/36962634-4d3e4382-208b-11e8-83d3-23d257411aac.png)

I based this idea on JQuery UI Date time picker and is easier to use in my opinion.

**Comment by olegvakulenko** [comment]
IMHO this is not Material Design style for DateTime picker.

**Comment by snow-drop** [comment]
@olegvakulenko Yup it is not. I based it on JQuery UI Date time picker. But I found it easier to select time using this. Other users also found it easier so I'll go now for this. :)
