### ISSUE TITLE
nodejs 21.2 quasar/app-vite

### ISSUE THREAD

**Issue by xalteropsx** [quasarframework/quasar#16649]
### What happened?

error @quasar/app-vite@1.6.2: The engine "node" is incompatible with this module. Expected version "^24 || ^22 || ^20 || ^18 || 
^16 || ^14.19". Got "21.2.0"    

### What did you expect to happen?

i want to force install why locked it?

**Comment by rstoenescu** [comment]
Hi,

Like we mentioned in the docs, please use stable versions of Node (even numbered versions). The odd numbered ones are not stable and may lead to unforeseen non-Quasar issues.

**Comment by Sjoerd82** [comment]
True as that is, I found it's sometimes needed to forcibly ignore this, which you can do using Yarn's `--ignore-engines` switch. But use this at your own peril, ONLY on development, and upgrade or downgrade to a stable version before complaining about anything.
