### ISSUE TITLE
Infinite scroll with DOM recycling

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#1664]
Is there any chance to make infinite scroll component recycle DOM nodes? Otherwise it forces me to add other libraries to support it.

**Comment by a47ae** [comment]
Are you sure this isn't already happening? Infinite scroll is jsut watching the height and trggering a handler. When you add content the actual DOM insertion is done by Vue.js and as far as I know, Vue.js reuses DOM nodes as much as it can, by utilizing virtual DOM and diffing to update only what really is changing.

**Comment by panstromek** [comment]
What I mean is using virtual list in infinite scroll. I didn't realize that q-infinite-scroll is just a container in Quasar. Virtual list already in todo list, so I think this will be possible in future..

**Comment by rstoenescu** [comment]
Closing as a ticket for Virtual Lists is already opened.
