### ISSUE TITLE
Support for multiple Electron preload scripts

### ISSUE THREAD

**Issue by Sunleader1997** [quasarframework/quasar#16656]
### Description

i wanna  open a new window by using 
```javascript
    childWindow = new BrowserWindow({
      icon: path.resolve(__dirname, 'icons/icon.png'),
      width: 1000,
      height: 600,
      useContentSize: true,
      frame: false,
      webPreferences: {
        sandbox: false, 
        contextIsolation: true,
        preload: path.resolve(__dirname, 'childpreload.js'),
      },
    });
```
but the '__dirname' is `.quasar\electron\childpreload.js` ,how to load childpreload.js
or Is there any way to compile preload.ts into .quasar\electron?

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Electron Mode

**Comment by rstoenescu** [comment]
Support for multiple Electron preload scripts will be available in the next major version of q/app-vite (v2) and q/app-webpack (v4).

**Comment by rstoenescu** [comment]
The new CLIs have been released: https://github.com/quasarframework/quasar/discussions/16877
