### ISSUE TITLE
QInput css error in the QDialog when it's filled

### ISSUE THREAD

**Issue by liulinbo123** [quasarframework/quasar#16655]
### What happened?

QInput css error in the QDialog when it's filled，However，it‘s ok when i open console
![Uploading 微信截图_20231204144141.png…]()

### What did you expect to happen?

![Uploading 微信截图_B6.png…]()

### Reproduction URL

https://stackblitz.com/edit/quasarframework-czu31c?file=src%2FApp.vue

### How to reproduce?

```
<template>
  <div>Filled Test</div>
  <q-dialog v-model="test" persistent>
    <q-card>
      <q-card-section>
        <q-input filled v-model="text" label="Filled" />
      </q-card-section>
    </q-card>
  </q-dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue';
const text = ref('');
const test = ref(true);
</script>

```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Style & Identity (quasar), SPA Mode

### Platforms/Browsers

Chrome

**Comment by liulinbo123** [comment]
After more tests，QCard cause this problem

**Comment by liulinbo123** [comment]
it's ok! I do anything......

**Comment by yusufkandemir** [comment]
Looks fine, I can't reproduce it. It seems you've attempted to include some screenshots in the issue description, but failed to do so. So, I can't guess the problem either.

Docs examples:
![image](https://github.com/quasarframework/quasar/assets/6266078/3edfe504-f23c-4b10-bbe3-8fd739cfcd7e)
![image](https://github.com/quasarframework/quasar/assets/6266078/1cf8f5b3-252e-48f0-8b2e-4585bb2a0418)

Your reproduction:
![image](https://github.com/quasarframework/quasar/assets/6266078/49b7e662-d9b7-4bae-bc01-47c0306908ec)
![image](https://github.com/quasarframework/quasar/assets/6266078/73af9f31-c1ca-4d09-a4a8-01164f882480)
