### ISSUE TITLE
Implement/enhance keyboard navigation for dropdowns (QBtnDropdown) and more generic for QPopover

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#1665]
- ENTER/SPACE/ARROW_DOWN - open popup when button is selected (partially done - ARROW_DOWN just in QBtnDropdown)
- when popover is open/focused ARROW_KEYS/HOME/END should navigate the options, ESC should close, ENTER/SPACE should select option

**Comment by rstoenescu** [comment]
@kevingermain Done for next Quasar version (through popover-anchor and popover-self new props).
