### ISSUE TITLE
"UI tests" CI workflow Is broken

### ISSUE THREAD

**Issue by rotu** [quasarframework/quasar#16661]
### Description

In contributing #16660, the [GitHub Actions Workflow "UI Tests"](https://github.com/quasarframework/quasar/actions/workflows/tests-on-pr.yml) failed with some messages that don't seem related to my changes:

https://github.com/quasarframework/quasar/actions/runs/7093684313/job/19307646722?pr=16660#step:7:27
> - [2271:1204/230814.664220:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type:

https://github.com/quasarframework/quasar/actions/runs/7093684313/job/19307646722?pr=16660#step:7:28
> Missing baseUrl in compilerOptions. tsconfig-paths will be skipped

https://github.com/quasarframework/quasar/actions/runs/7093684313/job/19307646722?pr=16660#step:7:29

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
> We detected that you have versions of dependencies that are not officially supported:
> 
>  - `vite`. Expected ^2.0.0 || ^3.0.0 || ^4.0.0, found 5.0.0.
> 
> If you're experiencing problems, downgrade dependencies and restart Cypress.

Additionally several of the tests appear to be failing with some timeout:

https://github.com/quasarframework/quasar/actions/runs/7093684313/job/19307646722?pr=16660#step:7:1817
> Timed out waiting for the browser to connect. Retrying...
> 
> Timed out waiting for the browser to connect. Retrying again...
> 
> The browser never connected. Something is wrong. The tests cannot run. Aborting...
> 
> The browser never connected. Something is wrong. The tests cannot run. Aborting...

Additionally, it seems like the test results for Chrome and Firefox aren't being processed right:

> Check failure on line 0 in test-results/test-results-firefox.json
> Error processing result file
> Unsupported file format: test-results/test-results-firefox.json

> [Check failure on line 0 in test-results/test-results-chrome.json]
> Error processing result file
> Unsupported file format: test-results/test-results-chrome.json

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rotu** [comment]
@yusufkandemir

**Comment by rstoenescu** [comment]
Everything works as expected. Please be sure that:

* You've run yarn at the root of the repo -- to make sure that your deps are up to date (we continuously make changes to the yarn.lock file)
* You're not running other Quasar CLI instances which may be using the hard-coded port for testing

Feel free to reopen or comment if the above does not apply.

**Comment by rotu** [comment]
The above does not apply. How do I reopen this issue?

I created a PR https://github.com/quasarframework/quasar/pull/16687 which demonstrates that it's a problem with the workflow, and NOT with the particular changes in #16660: https://github.com/quasarframework/quasar/actions/workflows/tests-on-pr.yml
