### ISSUE TITLE
q-intersection is not working in iframe

### ISSUE THREAD

**Issue by fannyfan414** [quasarframework/quasar#16664]
### What happened?

If I use q-intersection **without iframe** - everything is ok.

If I open docs example (https://quasar.dev/vue-components/intersection/) with **"root"** - empty white screen.
https://codepen.io/fannyfan414/pen/qBgLzKE?editors=111

Chrome 119.0.6045.200

### What did you expect to happen?

q-intersection should work inside iframe

### Reproduction URL

https://codepen.io/fannyfan414/pen/qBgLzKE?editors=111

### How to reproduce?

Open codopen example https://codepen.io/fannyfan414/pen/qBgLzKE?editors=111

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
It's a typo in the example. `:root="listEl"` should be `:root="myListRef"`
Please make a PR to fix the example.

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/WNPPNmy

**Comment by fannyfan414** [comment]
> Collaborator
> https://codepen.io/pdanpdan/pen/WNPPNmy

sry, you are right, now it works, but now in your example q-intersection render all elements immediately (if you scroll - there is no transition="scale" animation

**Comment by pdanpdan** [comment]
yes, the example is broken :(
- the error was not the wrong variable, but that it tried to get `$el` from a HTMLElement not a component
- it also did not have a size limiter

https://codepen.io/pdanpdan/pen/WNPPNmy?editors=1010

**Comment by fannyfan414** [comment]
> yes, the example is broken :(
> 
> * the error was not the wrong variable, but that it tried to get `$el` from a HTMLElement not a component
> * it also did not have a size limiter
> 
> https://codepen.io/pdanpdan/pen/WNPPNmy?editors=1010

thanks!

**Comment by rstoenescu** [comment]
Fixed the example. Was not easy to make both docs and codepen iframe work correctly (and look nice).
Will be available on next docs deployment.
