### ISSUE TITLE
Vite requires absolute path on img:/foo.png

### ISSUE THREAD

**Issue by jaybo** [quasarframework/quasar#16670]
### Description

Converted project from V2 Webpack to V2 Vite using instructions at:
https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite

Images in `<ROOT>/public` referenced by **q-icon** or **q-img** are no longer accessible *if the url contains a route* (eg. `//localhost:44346/foo`.   Urls without a route work fine with either format.

Old working code using Webpack and route `//localhost:44346/foo`
`<q-icon name="img:pilotCharts.png"></q-icon>` 

Additional change required using Vite (leading slash):
`<q-icon  name="img:/pilotCharts.png"></q-icon>` 

Note that the old, Webpack format **WORKS** as long as a route is not included, ie just `//localhost:44346`

Without this change, image loading fails since the image url is `//localhost:44346:/foo/pilotCharts.png`.

### Documentation Section URL

https://quasar.dev/vue-components/icon#image-icons

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

This is the nature of Vite. However, you can add a `<base>` tag yourself to the index.html file in the `<head>`, although we don't recommend it unless you really know what you are doing (can negatively impact Vue Router's behavior).

**Comment by jaybo** [comment]
Yes, I (now) know that's how Vite works.  :)

But I still think this is a Doc bug, since there's no indication in either the instructions at 

`https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite` 
or 
`https://quasar.dev/vue-components/icon#image-icons` 

that using the example from the Doc:

```<q-icon name="img:bla/bla/my.png" />```

won't work when using a route with Vite.

I'm just trying to save other devs from the 2 days I spent tracking down the solution.
