### ISSUE TITLE
Missing weight 900 for the default font Roboto in the description.

### ISSUE THREAD

**Issue by bronisMateusz** [quasarframework/quasar#16681]
### Description

In the description of the default font, the weight 900 is missing. This weight is used for the `text-weight-bolder` class.

### Documentation Section URL

https://quasar.dev/style/typography#default-font

### Flavour

None

### Areas

Style & Identity (quasar)

**Comment by rstoenescu** [comment]
Hi,

Everything seems ok. Can you be more specific on what you are using and what does not works for you? Add as many details as possible (are you using quasar/extras? which version? how are you using it? are you using Quasar CLI and which + version? through quasar.conf.js and what config are you using for it?).

**Comment by bronisMateusz** [comment]
The place I linked to has a description:

> The default webfont embedded is Roboto. But it is not required. You can use whatever font(s) you like.
> 
> Roboto comes with 5 different font weights you can use: 100, 300, 400, 500, 700.
> 
> This is where Roboto font comes embedded by default, if you are looking to remove it:
> 

900 weight for Roboto font is missing here.

It should be:

> The default webfont embedded is Roboto. But it is not required. You can use whatever font(s) you like.
> 
> Roboto comes with 5 different font weights you can use: 100, 300, 400, 500, 700, 900.
> 
> This is where Roboto font comes embedded by default, if you are looking to remove it:
>

**Comment by rstoenescu** [comment]
I see. Fixed it - will be available on next docs deployment.
Thanks!
