### ISSUE TITLE
QResizeObserver does not expose trigger method

### ISSUE THREAD

**Issue by NicolasReibnitz** [quasarframework/quasar#16697]
### What happened?

I hope I'm not missing something. But it seems like the QResizeObserver component doesn't expose its trigger method publicly, except when it uses the old iFrame approach. And even when I change the code to expose it either way, it doesn't seem to do anything.

### What did you expect to happen?

Calling `trigger()` or `trigger(true)` should cause the observer to fire a resize event.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-tvpgpp?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. go to the reproduction link
2. click the "trigger resize" button
3. check the `Uncaught TypeError: theObserver.value.trigger is not a function` in the console

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Quasar info output

```Shell
Operating System - Darwin(22.6.0) - darwin/arm64
NodeJs - 16.20.2

Global packages
  NPM - 8.19.4
  yarn - Not installed
  @quasar/cli - 2.3.0
  @quasar/icongenie - 3.1.1
  cordova - Not installed

Important local packages
  quasar - 2.14.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.8 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.54.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Camazotz.local
  en0 - 10.0.0.149
```

### Additional context

The Quasar version on stackblitz (v2.9.2) isn't up to date. But the same happens with the current version.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar 2.14.2
