### ISSUE TITLE
q-field class="q-gutter-y-md q-pa-sm col" has text overflow

### ISSUE THREAD

**Issue by yu0A** [quasarframework/quasar#16694]
### What happened?

The component below shows text overflow than the filled area.

    <div
      class="q-gutter-y-md q-pa-sm col"
    >
      <q-field type="textarea" class="full-height" filled
        ><div style="height: 70vh">{{ textOutput }}</div></q-field
      >
    </div>
  </div> -->
The defect is as the picture below:

### What did you expect to happen?

The component below shows text should not overflow than the filled area.

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR?editors=1111

### How to reproduce?

1. Make the text in the div of q-field more than 1 line

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
>quasar info

Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 16.19.1

Global packages
  NPM - 8.19.3
  yarn - 1.22.19
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.10 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-45IHAJG
  VirtualBox Host-Only Network - 192.168.56.1
  以太网 - 192.168.1.91
```

**Comment by yu0A** [comment]
![msedge_AYuif2kXQz](https://github.com/quasarframework/quasar/assets/111437058/fad32463-2f79-452b-a4bb-197f55c6b478)

**Comment by rstoenescu** [comment]
Hi,

This is incorrect usage. There is no prop `type` for QField. Do you actually want QInput type="textarea"?
Remember that QField is just a wrapper component, so anything you put inside of it is your responsibility.
