### ISSUE TITLE
Link redirect to 404 page 

### ISSUE THREAD

**Issue by Valgri** [quasarframework/quasar#16691]
### Description

This link https://jannerantala.com/tutorials/quasar-framework-google-tag-manager-and-analytics-setup-for-an-spa-website/

from https://quasar.dev/quasar-cli-webpack/developing-capacitor-apps/managing-google-analytics/

redirect to 404 page.

### Documentation Section URL

https://quasar.dev/quasar-cli-webpack/developing-capacitor-apps/managing-google-analytics/

### Flavour

None

### Areas

App Extension API

**Comment by rstoenescu** [comment]
Thanks for notifying us about this. Unfortunately, the tutorial is no longer available on the internet, so removing it from docs :(
