### ISSUE TITLE
Breaking change from 0.14 to 0.15 in build process - publicPath

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/quasar#1669]
### Software version

Operating System                        Windows_NT(6.1.7601) - win32/x64
NodeJs                                  9.5.0

Global packages
  NPM                                   5.7.1
  yarn                                  Not available
  quasar-cli                            0.15.4
  vue-cli                               2.9.3
  cordova                               Not available

Important local packages
  quasar-cli                            0.15.4  (Quasar Framework CLI)
  quasar-framework                      0.15.4  (Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras                         1.0.2   (Quasar Framework fonts, icons and i18n.)
  vue                                   2.5.13  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                            3.0.1   (Official router for Vue.js 2)
  vuex                                  3.0.1   (state management for Vue.js)
  electron                              1.7.9   (Build cross platform desktop apps with JavaScript, HTML, and CSS)
  babel-core                            6.26.0  (Babel compiler core.)
  webpack                               3.11.0  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server                    2.11.1  (Serves a webpack app. Updates the browser on changes.)

### What did you get as the error?
When building the generated code for index.html has invalid absoluter URL references to files. More info on the forum:
http://forum.quasar-framework.org/topic/1900/breaking-change-in-0-15-quasar-builds-absolute-urls-in-index-html/2

### What were you expecting?
I want to copy dist files to any subdir on www server i.e https://mytestserver.com/build20180226/index.html. Now it's impossible, because some (NOT EVERYTHING) files are referenced by absolute path to root dir "/".

### What steps did you take, to get the error?
quasar build with an option in build property "publicPath" in config omitted or set to empty string "".
publicPath - of String - means public path when deploying.

Evern more - setting "publicPath" option for example to “/build20180226/” wont change every generated relevant link in dist files - for example pwa manifest ignores this setting. So your application would break somewhere also.

Ideal solution would be to set it to empty string - publicPath: ‘’ - BUT - in this case, it is automagically converted to “/” and I think it is this autochange to “/” which breaks default builds. I propose, that when I do not specify publicPath in build options (it is null or undefined), then you can set it for anything default value you want. But if I specify it somehow - even initialize to empty string - please do not change this to default "/".

**Comment by rstoenescu** [comment]
Hi,

1. Are you aware of quasar.conf.js > build > publicPath ?
2. When building for PWA, you need to deploy at root and use the default publicPath, otherwise browsers won’t pick up the manifest.

Explaining the default behavior in details takes a lot of time, but it ensures you don't do mistakes. Mind that you can build for SPA, PWA, Cordova, Electron. Each have their own particularities, especially when dealing with statics. Quasar CLI takes care of all the fuss and makes sure you don't do mistakes. BUT it also allows you to set whatever publicPath you want when building SPA or PWA.

**Comment by rendau** [comment]
Hi,
I want to change path to manifest file

> When building for PWA, you need to deploy at root and use the default publicPath, otherwise browsers won’t pick up the manifest
Can You give some links for detail of that?

**Comment by nothingismagick** [comment]
Well, if you are going to go through the pain of upgrading from 14, then I really recommend you just skip 15,16 and 17 and upgrade directly to 1.0beta

**Comment by rendau** [comment]
But in "1.0beta" version, there is also no variant to change path to manifest.json
