### ISSUE TITLE
Test failed on default build

### ISSUE THREAD

**Issue by davewallace** [quasarframework/quasar#167]
Hi,

Just ran `quasar test` after a nearly fresh, problem-free install on mac os Sierra, and received failed test output.  Prior to that test, I have only updated package.json with my repo details, run `yarn` with no problems, `git init` + pushed to my repo, run `quasar new view layout/form/CreateCharacter` and run `quasar dev mat` - all with no issues (launched in browser, rendered, webpack happy).

Failed test results here: https://gist.github.com/davewallace/39a5f042674b4eb0fb9a4315755eb902

**Comment by rstoenescu** [comment]
Right, this was broken in v0.8 as only Vue 2 runtime is to be installed only. For the test environment the compiler should also be included. Will fix this. Thanks for reporting!

**Comment by davewallace** [comment]
No probs, hey and by the way, this is the first framework I have installed in about 6 months where the installation alone threw no errors, provided a seamless experience lining up with your well-written intro docs, and has so far been... enjoyable. Still boggling, and appreciating, thanks.

**Comment by rstoenescu** [comment]
Pushed a patch to app-template-v2 with a partial fix. It doesn't error out and tests are run correctly but there's still a warning to solve.
