### ISSUE TITLE
[Feature Request] Multiple items per slide in carousel

### ISSUE THREAD

**Issue by l1qu1d** [quasarframework/quasar#1670]
It would be great to be able to have n items per slide in the carousel like in the "multiple items" section in [Slick Carousel](http://kenwheeler.github.io/slick/).

It would be a **double use case** (display multiple items and thumbnail carousel ) as I could turn it into a thumbnail carousel that would then display the selected image above the slider like [Smart Slider 3](https://smartslider3.com/free-thumbnail-slider/) thus solving my current issue.

Having a thumbnail carousel in itself **could also be an additional feature**, but I thought it would be easiest to have multiple items in the carousel vs creating a new component for the current carousel.

Thank you for all the hard work put into Quasar!

Below are the example images so you don't have to go to the links above.

**Slick**
![slick](https://user-images.githubusercontent.com/1037693/36797261-1d90f552-1c6d-11e8-9f67-18aa23bcb01e.PNG)

**Smart Slider 3**
![smart_slider](https://user-images.githubusercontent.com/1037693/36797280-2ce506c4-1c6d-11e8-94f8-6efb4f41d8ce.PNG)

**Comment by Manfred047** [comment]
+1

**Comment by drastik** [comment]
+1
This would be an excellent addition.

**Comment by panstromek** [comment]
+1

**Comment by nicholaszuccarelli** [comment]
+1

**Comment by valterfc** [comment]
+1

**Comment by AdsonCicilioti** [comment]
+1
Show multiple items by slide. responsive option change to to one item slide.

**Comment by rakeshmali** [comment]
Is it still under development? Or possible to disply and slide mulple items at once?

**Comment by RamiAlmofleh** [comment]
+1

**Comment by smolinari** [comment]
Is this sort of what you are looking for? 

https://codepen.io/smolinari/pen/jRRLWE

Scott

**Comment by CheyenneForbes** [comment]
@smolinari I dont believe that's what he was looking for, I was about to make a feature request for this too

[regular multiple items example](https://codepen.io/anon/pen/WdqemV)
[stacked example](http://element.eleme.io/#/en-US/component/carousel#card-mode)

Additional information from the issue I was about to open.

> Additionally, a property called stack-count which would "activate" the stacked layout and decide the max amount of items to be stacked on each side, as an example, I'd say the stack-count of the example in the link above is 1 since the displayed item has 1 item behind it on each side, this would mean if there are two items and the second item is being displayed 1 would be stacked on the left and the right side would be empty since the second item would be in the middle.

**Comment by smolinari** [comment]
@CheyenneForbes - Did you look at the site the OP linked to? 

Scott

**Comment by CheyenneForbes** [comment]
@smolinari not before reading your comment, I was going with:

> Below are the example images so you don't have to go to the links above.

but after reading your comment I went to the links and saw it was a bit different from what I wanted, should I open a new issue or its this issue is enough since it would basically be the same title?

**Comment by smolinari** [comment]
Start a new issue and make a link to this one saying it's similar but different.

Scott

**Comment by romanran** [comment]
+1

**Comment by alexpvieira** [comment]
+1

**Comment by Thanatos23** [comment]
+1

**Comment by Jmbouille** [comment]
+1

**Comment by rmundel** [comment]
+1.25 (I want more than average)

**Comment by rstoenescu** [comment]
We have added an example in docs some time ago on how to add multiple "items" in a single slide. Let's continue the discussion on the QCarousel 2.0 RFC.
