### ISSUE TITLE
Project creation tests failing in Node 18.19

### ISSUE THREAD

**Issue by rotu** [quasarframework/quasar#16701]
### What happened?

Project creation tests are failing in CI.

### What did you expect to happen?

I expect project creation tests to pass in CI

### Reproduction URL

https://github.com/quasarframework/quasar/actions/runs/7201703422/job/19618401053

### How to reproduce?

Run CI.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Project Creation (create-quasar)

### Additional context

Discovered when doing #6699

This seems to be caused by an unfortunate interaction between Node and `tsx`.

see:
- https://github.com/nodejs/node/issues/51048
- https://github.com/privatenumber/tsx/issues/421

Note that bumping `tsx` to version 4 would break compatibility with Node 18.

**Comment by rotu** [comment]
The "obvious" fix is to bump `tsx` (#16719) but this is incompatible with Node 16 (which is out of support). Recommend to change the minimum Node version to 18 and the default to 20 (#16714).

Thoughts, @rstoenescu?

**Comment by yusufkandemir** [comment]
Thanks for reporting. This was fixed in https://github.com/quasarframework/quasar/commit/e6b161c6b8059f75ae1ead8eb01a591651ac8ec3
