### ISSUE TITLE
QRange snaps to integer on dragRange, even if step is 0

### ISSUE THREAD

**Issue by rotu** [quasarframework/quasar#16700]
### What happened?

Dragging a range with `step=0` quantizes the endpoints to integer values.
![video](https://github.com/quasarframework/quasar/assets/119948/48a0d4d0-73f6-4196-99ad-f8688909aa77)

### What did you expect to happen?

Dragging a range should drag smoothly if `step=0` or `snap=false`.

### Reproduction URL

https://codepen.io/rotu-the-bold/pen/eYxajBg

### How to reproduce?

1. Go to the provided link.
2. Drag the midpoint

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by rotu** [comment]
I think it's related to a couple places in `QRange.js` where we call `parseFloat((/*...*/).toFixed(state.decimals.value))`

https://github.com/quasarframework/quasar/blob/f6acc96c12ccab7389f4651736928b6b24ad3e30/ui/src/components/range/QRange.js#L295-L300

I don't quite understand the role `state.decimals` plays, especially since `step` may be an integer. I suspect it's to prevent floating point rounding errors. If so, I think the step should be based on `min` and `max` as well so that e.g. `min=0.5, max=2.5, step=1` and `min=5, max=25, step=10` behave analogously.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.14.2
