### ISSUE TITLE
error when run quasar upgrade

### ISSUE THREAD

**Issue by Zhangshunyao** [quasarframework/quasar#16707]
### What happened?

when run the command 'quasar upgrade'
encounter error as below

 Global Quasar CLI • Gathering information from the NPM registry...

 @quasar/extras: 1.16.8 → 1.16.9
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 104.16.27.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.16.27.34',
  port: 443
}

Node.js v18.17.0

// other information 

I have changed the registry as below

npm get registry
https://registry.npmmirror.com/

// quasar info

Operating System - Darwin(23.2.0) - darwin/arm64
NodeJs - 18.17.0

Global packages
  NPM - 10.1.0
  yarn - 1.22.19
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.46.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - localhost
  en0 - 10.0.0.15

### What did you expect to happen?

successfully upgrade

### Reproduction URL

https://no.valid.here/noinuse/sssss

### How to reproduce?

run quasar upgrade

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

### Quasar info output

```Shell
1111
```

### Relevant log output

```Shell
111
```

### Additional context

111

**Comment by pdanpdan** [comment]
Try to read this part of your logs `Error: connect ETIMEDOUT 104.16.27.34:443` and this part `I have changed the registry as below` - it might happen they are related :D

**Comment by Zhangshunyao** [comment]
Actually I have changed the npm registry from default  to this one, but still met this error

**Comment by Zhangshunyao** [comment]
我看到之前有issue里面提到 更换 npm registry 可以解决这个问题
