### ISSUE TITLE
Pinia HMR in Vite doesn't work with Quasar CLI Vite

### ISSUE THREAD

**Issue by yu0A** [quasarframework/quasar#16709]
### What happened?

Pinia HMR in Vite doesn't work with Quasar CLI

### What did you expect to happen?

Pinia supports HMR to keep previous states. See https://pinia.vuejs.org/cookbook/hot-module-replacement.html

### Reproduction URL

https://github.com/yu0A/vue_quasar_admin/tree/main

### How to reproduce?

Deploy this project
Go to http://localhost:9000/#/pythonWangLuoDaoRu
Click "执行" button, where you can see the text on the the right textfield can change.
Trigger HMR, then click "执行" button, where you can see the text on the the right textfield cannot change.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by pdanpdan** [comment]
Did you implement what is written on the page you referenced?
If you did please provide a reproduction and we'll reopen.

**Comment by yu0A** [comment]
I just uploaded a Quasar CLI Vite project so that you can reproduce this bug.
[vue_quasar_admin](https://github.com/yu0A/vue_quasar_admin/tree/main)

How to reproduce?
1. Deploy this project
2. Go to http://localhost:9000/#/pythonWangLuoDaoRu
3. Click "执行" button, where you can see the text on the the right textfield can change.
4. Trigger HMR, then click "执行" button, where you can see the text on the the right textfield cannot change.

**Comment by pdanpdan** [comment]
You did not add the coffee for her from the points docs: https://pinia.vuejs.org/cookbook/hot-module-replacement.html#HMR-Hot-Module-Replacement-

In this file: https://github.com/yu0A/vue_quasar_admin/blob/main/src/stores/example-store.js

**Comment by yu0A** [comment]
That snippet works. Thanks
