### ISSUE TITLE
Vue CLI Plugin

### ISSUE THREAD

**Issue by WCN-llc** [quasarframework/quasar#16718]
### What happened?

Plugin doesn't work

### What did you expect to happen?

The project starts correctly

### Reproduction URL

https://quasar.dev/start/pick-quasar-flavour

### How to reproduce?

1. Create a clean project  Vue
2. Install the Vue CLI Plugin
3. Start the project

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Plugins (quasar)

### Quasar info output

```Shell
*  Task performance: yarn run serve 

yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...


 ERROR  Failed to compile with 1 error                                                                                             14:19:20

 error  in ./src/styles/quasar.scss

Syntax Error: SassError: Undefined function.
   ╷
43 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 43:9     sin()
  node_modules\quasar\dist\quasar.sass 4602:16  @import
  src\styles\quasar.scss 2:9                    root stylesheet


ERROR in ./src/styles/quasar.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./node_modules/vue-cli-plugin-quasar/lib/loader.scss.js!./src/styles/quasar.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined function.
   ╷
43 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 43:9     sin()
  node_modules\quasar\dist\quasar.sass 4602:16  @import
  src\styles\quasar.scss 2:9                    root stylesheet
 @ ./src/styles/quasar.scss 4:14-306 15:3-20:5 16:22-314
 @ ./src/quasar-user-options.js 1:0-30
 @ ./src/main.js 4:0-54 5:27-44

webpack compiled with 1 error
```

### Relevant log output

```Shell
*  Task performance: yarn run serve 

yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...


 ERROR  Failed to compile with 1 error                                                                                             14:19:20

 error  in ./src/styles/quasar.scss

Syntax Error: SassError: Undefined function.
   ╷
43 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 43:9     sin()
  node_modules\quasar\dist\quasar.sass 4602:16  @import
  src\styles\quasar.scss 2:9                    root stylesheet


ERROR in ./src/styles/quasar.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./node_modules/vue-cli-plugin-quasar/lib/loader.scss.js!./src/styles/quasar.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined function.
   ╷
43 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 43:9     sin()
  node_modules\quasar\dist\quasar.sass 4602:16  @import
  src\styles\quasar.scss 2:9                    root stylesheet
 @ ./src/styles/quasar.scss 4:14-306 15:3-20:5 16:22-314
 @ ./src/quasar-user-options.js 1:0-30
 @ ./src/main.js 4:0-54 5:27-44

webpack compiled with 1 error
```

### Additional context

 * Task performance: yarn run serve 

yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...

 ERROR  Failed to compile with 1 error                                                                                             14:19:20

 error  in ./src/styles/quasar.scss

Syntax Error: SassError: Undefined function.
   ╷
43 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 43:9     sin()
  node_modules\quasar\dist\quasar.sass 4602:16  @import
  src\styles\quasar.scss 2:9                    root stylesheet

ERROR in ./src/styles/quasar.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./node_modules/vue-cli-plugin-quasar/lib/loader.scss.js!./src/styles/quasar.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined function.
   ╷
43 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 43:9     sin()
  node_modules\quasar\dist\quasar.sass 4602:16  @import
  src\styles\quasar.scss 2:9                    root stylesheet
 @ ./src/styles/quasar.scss 4:14-306 15:3-20:5 16:22-314
 @ ./src/quasar-user-options.js 1:0-30
 @ ./src/main.js 4:0-54 5:27-44

webpack compiled with 1 error

**Comment by rstoenescu** [comment]
Use latest sass

**Comment by WCN-llc** [comment]
> Use latest sass

Thank you! :-)
