### ISSUE TITLE
Toggle weird behaviour

### ISSUE THREAD

**Issue by Allihopp** [quasarframework/quasar#16732]
### What happened?

Toggle component looks squished, you know.
![image](https://github.com/quasarframework/quasar/assets/29628160/cfac4c79-f509-4de7-867c-a19a16b7ab67)

### What did you expect to happen?

Work properly, as shown in docs.

### Reproduction URL

cannot reproduce

### How to reproduce?

<q-toggle
    v-model="model"
    label="Cost update"
/>

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Plugins (quasar), Style & Identity (quasar)

### Additional context

Cannot reproduce the problem anywhere else (codepen, jsfiddle). But the problem appears even on blank project on other PC.

**Comment by Allihopp** [comment]
Quasar version 2.14.0

**Comment by yusufkandemir** [comment]
Can't reproduce = Can't fix
