### ISSUE TITLE
Animation modifier classes not mentioned

### ISSUE THREAD

**Issue by danbars** [quasarframework/quasar#16734]
### Description

The [animation](https://quasar.dev/options/animations) docs do not mention the modifier classes that can be used with transition: repeat, repeat-1, repeat-2, delay-1s - delay-5s, slower, slow, fast, faster

I was customizing the delay and duration myself using css, and then saw them in the dev-tools by chance. 

### Documentation Section URL

https://quasar.dev/options/animations

### Flavour

None

### Areas

Components (quasar)

**Comment by nicolasmartinrojo** [comment]
PR Created: https://github.com/quasarframework/quasar/pull/16824

**Comment by rstoenescu** [comment]
Hi,

Thanks for opening this ticket.
Will be available on next docs deployment.
