### ISSUE TITLE
webpack + vue3 + electron, An error occurred in quasar dev -m electron 

### ISSUE THREAD

**Issue by wenbinwumei** [quasarframework/quasar#16741]
### What happened?

I encountered an error while running the Electron development environment. Despite multiple attempts, the error persisted and I don't know what to do

### What did you expect to happen?

I hope it can run normally without affecting the maximum and minimum windows

### Reproduction URL

no

### How to reproduce?

1.quasar dev -m electron
2.[31612:0103/200452.271:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/prot
ocol_client/protocol_client.js (1)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Electron Mode

### Platforms/Browsers

Electron

### Quasar info output

```Shell
[31612:0103/200452.271:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/prot
ocol_client/protocol_client.js (1)
```

### Relevant log output

```Shell
[31612:0103/200452.271:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/prot
ocol_client/protocol_client.js (1)
```

### Additional context

I found an error in the electric-preload. js directory under. quasar. On line 39, module. exports=@ electric/remote; This code was generated at runtime and I changed it to module. exports=require ("@ electron/remote"); It can run normally, but it will be restored every time it is restarted, which is very troublesome. Can this be fixed

**Comment by eqoram** [comment]
I am getting the same error

**Comment by b5414** [comment]
same on `react + vite + electron` (this error from electron I believe)

**Comment by petrnovikov** [comment]
Here's the Electron thread on this error, they closed it to wontfix because it does not seem to affect functionality.
https://github.com/electron/electron/issues/41614

**Comment by Shekhrozx** [comment]
any news ?

**Comment by rstoenescu** [comment]
On the original problem: please use the new CLIs (currently in beta, but pretty close to the final release). https://github.com/quasarframework/quasar/discussions/16877

With q/app-vite v2 especially, since it modernizes the architecture (will use ESM). The problem here will then become obsolete.

**Comment by wenbinwumei** [comment]
@rstoenescu I understand your thoughts and I am also very optimistic about Vue3+vite. However, my team often encounters situations where asynchronous loading is required when using it to develop projects. There is no good solution to this in the vite API, so we can only switch to Vue3+webpack for now because I really need dynamic parameters to load components asynchronously. 'import. meta. global' has a significant performance issue for me, as it loads all components in a modular directory at once, causing one page to load too slowly

**Comment by rtritto** [comment]
@rstoenescu I'm using `vite`, how this problem was fixed? Is there any issue or do you have code/commits?

**Comment by zanzara** [comment]
I'm having the same error 
```
[260597:0717/121459.165454:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[260597:0717/121459.165491:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```
using the latest app-cli and app-vite2.beta   (snippet of `quasar info` below)
```
  @quasar/cli - 2.4.1
  @quasar/icongenie - 2.5.4

Important local packages
  quasar - 2.16.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.0-beta.15 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  vue - 3.4.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.0
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vite - 5.3.4 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  esbuild - 0.23.0 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.3 -- TypeScript is a language for application scale JavaScript development
  electron - 31.2.1 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
```

Which remedies  exists?  Is there a workaround?

Unfortunately this is a show-stopper. I need to go on smh.  Really appreciating sm help.

@rstoenescu  Is this only mitigatable with webpack? Not with vite?

Rem: This is not a new project. I have updated electron and due to ESM now, I also needed to remove @electron/remote
