### ISSUE TITLE
App Extension - UI kit - sass error when running in ui with yarn dev

### ISSUE THREAD

**Issue by benoitbc** [quasarframework/quasar#16746]
### What happened?

I created a new App Extension (ui kit) using the steps found in the documentation.
Then I ran "npm run dev" in the "ui" folder and the following error was thrown:

 ```
App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 5357ms

 App •  ERROR  •  UI  in ../node_modules/quasar/dist/quasar.sass

Syntax Error: SassError: Undefined function.
   ╷
44 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  ..\node_modules\quasar\dist\quasar.sass 44:9     sin()
  ..\node_modules\quasar\dist\quasar.sass 4603:16  root stylesheet


 App •  COMPILATION FAILED  • Please check the log above for details.
```

To fix the error, I replaced:
`"sass": "1.32.0"`
with:
`"sass": "^1.32.0"`
in the package.json of the ui folder.

### What did you expect to happen?

I expected the test application to run after following the procedure in the documentation (https://quasar.dev/app-extensions/development-guide/introduction).

### Reproduction URL

https://quasar.dev/app-extensions/development-guide/introduction

### How to reproduce?

1. "npm init quasar" to create a new App Extension (UI kit).
2. In the newly created folder, "cd ui".
3. Then "npm install".
4. Then "yarn dev".

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

App Extension API

**Comment by sonsu-lee** [comment]
I'm having the same problem and trying to find a solution.

The same thing happens when I increase the sass version to 1.33 or higher.

**Comment by yusufkandemir** [comment]
@sonsu95 to confirm, you are experiencing the same error with the UI kit, but it doesn't go away even if you apply the solution, is that correct?

**Comment by sonsu-lee** [comment]
@yusufkandemir Sorry, I must have tried it the wrong way. 
https://github.com/quasarframework/quasar/commit/8a5927434efe210596ef14722df1504524ba13d4

I redid that part and it works fine. Thank you for asking again.

**Comment by yusufkandemir** [comment]
@sonsu95 thanks for confirming. The fix will be included in the next `create-quasar` release, so you will no longer have to take extra action.

**Comment by idc77** [comment]
where did you replace it?

```
{
  "name": "6s4",
  "version": "0.0.1",
  "description": "Message",
  "productName": "Message",
  "author": "redacted",
  "private": true,
  "scripts": {
    "dev": "quasar dev",
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@dsb-norge/vue-keycloak-js": "^2.4.0",
    "@quasar/extras": "^1.16.9",
    "@vuex-orm/core": "^0.36.4",
    "@vuex-orm/plugin-axios": "^0.9.4",
    "axios": "^1.6.7",
    "core-js": "^3.35.1",
    "quasar": "^2.14.3",
    "vue": "^3.4.18",
    "vue-i18n": "^9.9.1",
    "vue-router": "^4.2.5",
    "vuex": "^4.1.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.13.14",
    "@quasar/app": "^3.3.3",
    "dotenv": "^16.4.1",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-vue": "^9.21.1",
    "eslint-webpack-plugin": "^4.0.1"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 12.22.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}
```
I see no sass

**Comment by yusufkandemir** [comment]
@idc77 your project doesn't look like an app extension, it's a regular app. `@quasar/app` is deprecated, which is the culprit here. Change it to `@quasar/app-webpack` and use the latest 3.x version.

**Comment by idc77** [comment]
@yusufkandemir thank you. That did it.
Yes it wasn't an extension, in all the hurry I searched for the error message in issues and found this issue.
