### ISSUE TITLE
time keep reset official docs also failing 

### ISSUE THREAD

**Issue by neonarc4** [quasarframework/quasar#16749]
their is bug on https://quasar.dev/vue-components/date#example--default-view

```
 <q-date
      v-model="date"
      default-view="Years" //this part not working 
    />

**Comment by neonarc4** [comment]
![image](https://github.com/quasarframework/quasar/assets/140290288/4af3776a-f3b3-48e2-8fca-f30fdf56c210)
something like we want month year day wise versa

**Comment by pdanpdan** [comment]
Please provide a reproduction. I cannot understand what you mean.

**Comment by rstoenescu** [comment]
Please reopen/comment here with a reproduction or a clear explanation of what you want. Thank you.
