### ISSUE TITLE
Click on QField content triggers onClear

### ISSUE THREAD

**Issue by arnKo** [quasarframework/quasar#16757]
### What happened?

When clicking the content of a QField the onClear handler is triggered.

### What did you expect to happen?

The onClear handler should only be called if the clear button was clicked, not on any arbitrary click into the QField component's content.

### Reproduction URL

https://jsfiddle.net/hz3f2cy8/14/

### How to reproduce?

1. Go to the provided reproduction link
2. Click anywhere on the QField except on the clear button directly
3. See that the counter increases although the clear button was not clicked

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Quasar info output

```Shell
Operating System - Linux(5.15.0-91-generic) - linux/x64
NodeJs - 18.19.0

Global packages
  NPM - 10.2.3
  yarn - 1.22.10
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.5 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.56.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  br-93c509841567 - 172.19.0.1
  br-b4d024aff1ba - 172.25.0.1
  br-c66d6e7df8cb - 172.20.0.1
  br-ea638081945e - 172.22.0.1
  br-3e634fdd1237 - 172.27.0.1
  tun0 - 10.3.8.3
```

**Comment by pdanpdan** [comment]
`QField` is rendered by default as a label, and clicking a label triggers a click on its first form component inside.
In your case the first and only form component inside is the clear button.
If you don't want this:
- use `tag` prop to change from `label` to `div` or whatever
- put fome form controls inside
