### ISSUE TITLE
Dialog in Macbook

### ISSUE THREAD

**Issue by PJH-Eric** [quasarframework/quasar#16755]
### What happened?

Equipment: MacBook
Browser: Chrome (Version 120.0.6099.129 (Official Build) (arm64))

Using Chrome on a Mac computer, click on a button to display a popup.
Click on the "X" in the upper right corner of the popup to close it, but the entire browser tab gets closed instead.

### What did you expect to happen?

Clicking on the "X" in the upper right corner of the popup should only close the popup, not the entire browser tab.

### Reproduction URL

https://codepen.io/tzuchuannien/pen/QWoEpBO?editors=1111

### How to reproduce?

using macbook with chrome with dialog

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
Wow, impressive low effort.

**Comment by PJH-Eric** [comment]
Reproduction URL has been updated
