### ISSUE TITLE
[Out of Memory]  I copied the code from the official document, but the browser got stuck and the memory overflowed....

### ISSUE THREAD

**Issue by kissxrl** [quasarframework/quasar#16766]
### What happened?

 I copied the code from the official document, but the browser got stuck and the memory overflowed....

I changed several browsers, but the memory still overflowed.

`

    <div id="q-app">
        <div class="q-pa-md">
            <div class="q-gutter-md" style="max-width: 300px">
                <q-input v-model="text" label="Standard" />

                <q-input filled v-model="text" label="Filled" />

                <q-input outlined v-model="text" label="Outlined" />

                <q-input standout v-model="text" label="Standout" />

                <q-input standout="bg-teal text-white" v-model="text" label="Custom standout" />

                <q-input borderless v-model="text" label="Borderless" />

                <q-input rounded filled v-model="text" label="Rounded filled" />

                <q-input rounded outlined v-model="text" label="Rounded outlined" />

                <q-input rounded standout v-model="text" label="Rounded standout" />

                <q-input square filled v-model="text" label="Square filled" />

                <q-input square outlined v-model="text" label="Square outlined" />

                <q-input square standout v-model="text" label="Square standout" />
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.14.2/dist/quasar.umd.prod.min.js"></script>
    <script>
        const { createApp, ref } = Vue
        const app = createApp({
            setup() {
                return {
                    text: ref('')
                }
            }
        })
        app.use(Quasar)
        app.mount('#q-app')
    </script>

`

![11111111111111](https://github.com/quasarframework/quasar/assets/9613121/ddfc93f5-8a53-4454-aa83-5619fc1be1d1)

### What did you expect to happen?

[Out of Memory]

### Reproduction URL

http://127.0.0.1:5002/vue3.html

### How to reproduce?

[Out of Memory]

### Flavour

UMD

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app), Components (quasar), Directives (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

### Quasar info output

```Shell
[Out of Memory]
```

### Relevant log output

```Shell
[Out of Memory]
```

### Additional context

[Out of Memory]

**Comment by kissxrl** [comment]
http://42.192.225.95:8880/vue.html
view-source:http://42.192.225.95:8880/vue.html

I've provided you with a new link


> Hi @kissxrl! 👋
> 
> It looks like you provided an invalid or unsupported reproduction URL. Do not use any service other than [Codepen](https://codepen.io), [jsFiddle](https://jsfiddle.net), [StackBlitz](https://stackblitz.com), [Codesandbox](https://codesandbox.io), and [GitHub](https://github.com). Make sure the URL you provided is correct and reachable. You can test it by visiting it in a private tab, another device, etc. Please **edit your original post above** and provide a valid reproduction URL as explained.
> 
> Without a proper reproduction, your issue will have to get closed.
> 
> Thank you for your collaboration. 👏

**Comment by pdanpdan** [comment]
you cannot use self closing tags for vue components

**Comment by realpaul** [comment]
I encountered similar problem when using Quasar UMD today, and found solution from: https://github.com/quasarframework/quasar/issues/16768. You may use vue@3.4.12 instead of vue@3 to solve this problem.
