### ISSUE TITLE
BackToTop visibility when component upon it is applied re-renders

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#1676]
### Software version

Quasar: 0.15.4
OS: - jsfiddle
Node: -
NPM: -
Browsers: Chrome (latest), Firefox (latest), IE 
iOS: -
Android: -
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/3y8sqkzf/10/

### What did you get as the error?
 When binding the color prop of q-btn to change the color on demand (while using back-to-top directive ) it forces the button to a visible state. When the button is already visible it's ok.
Please see fiddle, there are two color switch btns to play with.
### What were you expecting?
No change in visbility while switching colors
### What steps did you take, to get the error?
Click the switch color button while at the top of the page. (jfiddle)

Note: Amazing framework!

**Comment by rstoenescu** [comment]
Fix available in 0.15.5. Thanks for reporting.
