### ISSUE TITLE
Sluggish Performance on Firefox for Android - Tested with Dialog Plugin

### ISSUE THREAD

**Issue by tidalvirus** [quasarframework/quasar#16763]
### What happened?

Sluggish/jerky performance when opening a dialog on Firefox 121.0.1 on Android 9 (Samsung Tab A 2017), and Android 10 (Samsung Tab S4).
Same tablets running Chrome on the test site are silky smooth. I think it's possible that other parts of Quasar are also sluggish in FF on Android, but the dialog is a fairly easy way to see (replicate?) the issue.

### What did you expect to happen?

Expected the dialog to open as smoothly as browsers on all other devices I've used it on (FF/Edge on Windows & Mac, Safari and FF on iOS, and of course, Chrome on Android).

### Reproduction URL

https://quasar.dev/quasar-plugins/dialog#usage

### How to reproduce?

1. Go to the docs page linked above, scroll to the dialogs, click on any of the dialogs - 'Stacked Buttons' gives the best indicator of the sluggishness. The dialog will open quite jerkily on FF.

User experience is slow enough on a basic app I made (with a framework called 'Nicegui' which also uses Quasar) to make the user think the button to open a dialog wasn't opened, so the user presses it twice. I created a bug report for Nicegui earlier, where we narrowed the issue down closer to Quasar. - https://github.com/zauberzeug/nicegui/issues/2334

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

### Platforms/Browsers

Firefox, Android

### Additional context

I'm not a JS developer, I came across Quasar via Nicegui (a python webapp framework). I'm not too certain what kind of debug might be available for me to provide you, but I'll do my best to help!

**Comment by pdanpdan** [comment]
Sorry but Firefox for Android is a disaster. In this case it struggles trying to render a css animation. Nothing that can be done.

**Comment by tidalvirus** [comment]
If this can be reproduced with the examples on the documentation pages, do you still require me to work out how to use one of those other services? I'll see if I can do that if you really need, but hopefully not needed? 😅

**Comment by tidalvirus** [comment]
My timing is clearly bad - I see now the comment from pdanpdan - guess there's no fix here? :(

Well, I mean, other than creating a bug with firefox... hmm!

**Comment by pdanpdan** [comment]
On my pixel 7 phone it works ok, but it is much more powerful than the specified devices.
The only solution I can think of is to try to disable animations when showing the dialog.

**Comment by tidalvirus** [comment]
> On my pixel 7 phone it works ok, but it is much more powerful than the specified devices. The only solution I can think of is to try to disable animations when showing the dialog.

I'll close this bug report then, as it seems like it's very much a FF issue. I'll look into potentially reporting a bug there, or investigating FF performance on Android in general.

Thanks for your input. I didn't realise it might be something 'basic' like the browser itself..!

**Comment by tidalvirus** [comment]
Just to add a tiny bit more - for anyone that might come across this. Firefox Beta (122.0b8) at time of writing is as silky smooth as Chrome!
