### ISSUE TITLE
A11y - Improve the Notify plugin accessibility

### ISSUE THREAD

**Issue by Brice155** [quasarframework/quasar#16764]
### What happened?

Hello !

I'm expert in web accessibility in France. I think that the Notify plugin can be improved to be more accessible.

One main subject : the focus :)

**Part 1 :**
I would like to know how to get the focus on a notification (created with the Notify plugin) which is persistent ?
Indeed, for accessibility purposes, when a notification is persistent, users who navigate exclusively by keyboard must be able to close the notification. To do this, it would need to have the focus on the div containing the notification (or on the close button).

It is not a real problem if the page contains 1 or 2 interactive elements. But wehn the page is very complex, tab navigation can be very complex.

Here is the code I started writing. I added some attributes to make the notification accessible (aria-label on the close button). So I miss getting the focus...

```
Notify.create({
    progress: newOptions.progress,
    timeout: newOptions.persistent == true ? 0 : newOptions.timeOut,
    position: newOptions.position,
    message: message,
    icon: 'error',
    actions: [
      {
        icon: 'close',
        color: 'white',
        'aria-label': 'Close the notification',
        title: 'Close the notification',
        name: 'notification-error-close-btn',
        id: 'notification-error-close-btn',
      },
    ],
    color: 'negative',
    textColor: 'white',
    html: newOptions.isHtml,
    badgeClass: 'invisible',
    attrs: {
      name: 'notification-error',
      tabindex: '0'
    },
  });
```

**Part 2 :**
Another subject: I would like to be able to add a class to the action button so that it has an outline when in focus. I succeeded by manipulating the DOM but it would be much simpler if it was possible to add a CSS class to the button(s).
With A11y, the focus on focusabvle element must be perceptible. On solution is to set the outline css property when the element is focused.

### What did you expect to happen?

1/ Immediate focus on persistant notifications (via a new parameter ?)
2/ Add a css class to the button(s) via a new parameter

### Reproduction URL

https://codepen.io/Brayce/pen/mdoOVEo

### How to reproduce?

1. Click on the "Notify" button
2. Tab to the notification

What is expected is to tab on the Notify button, press Enter and the focus must be immediately on the notification.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
You can focus the notification after you open it
https://codepen.io/pdanpdan/pen/BabQYXJ?editors=1010

The problem I see with notifications in general is that most of the time you don't want them to be focused, and to kbd navigate to them is more a joke than something that can be done

**Comment by Brice155** [comment]
Hi @pdanpdan 
Thanks a lot for the solution ! It's working !
In fact, it's very useful for blind people or anyone who only uses the keyboard.
As far as my web application is concerned, in some cases it is necessary to leave the notification displayed indefinitely because it can contain a lot of text. The user must therefore be able to close it without “putting pressure on themselves”

**Comment by pdanpdan** [comment]
I was not disputing the usefulness of being able to focus.
I was just saying that by default, without refocus, it's nearly impossible to get to the notification.

**Comment by Brice155** [comment]
Oh i'm really sorry @pdanpdan !
My english is so bad.... i didn't really understood...
Sorry sorry sorry !!!!
