### ISSUE TITLE
Infinite fetch loop with AjaxBar, XMLHttpRequest and watchEffect (or asyncComputed)

### ISSUE THREAD

**Issue by Dimava** [quasarframework/quasar#16767]
### What happened?

Same as #10780 I've encountered problems with Axios inside asyncComputed(vueuse) causing infinite loop with AjaxBar on

I had a guess that this is not caused by Axios itself and tried to reproduce it without Axios

### What did you expect to happen?

QAjaxBar to not cause infinite request loop when using XMLHTTPRequest

### Reproduction URL

https://codepen.io/dimava/pen/YzgpVOW

### How to reproduce?

Synchronously create `new XMLHttpRequest()` and `.open(...)` it inside a `watchEffect` watcher

```ts
    watchEffect(async () => {
      let xhr = new XMLHttpRequest();
      xhr.open('GET', 'https://jsonplaceholder.typicode.com/todos');
      xhr.send();
    });
```

This will cause infinite fetch loop every second, caused by `onScreen.value` being read synchronously inside `start` and thus being recorded as a dependency by `watchEffect`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.14.3
