### ISSUE TITLE
QButton doesn't work properly when used with QInput with 'hide-bottom-space' attribute and validation rules.

### ISSUE THREAD

**Issue by StasD** [quasarframework/quasar#16776]
### What happened?

Suppose there is a q-button and q-input on a page. q-input has 'hide-bottom-space' attribute and some validation rules.
You click on the q-button, which triggers validation rules on q-input. Because of 'hide-bottom-space' attribute on the q-input, some error message appear below it, which causes the q-button to move down. If it causes mouse cursor to move outside the q-button, the click event handler of the q-button does not run.

### What did you expect to happen?

The click event handler (or ':to' redirection) of the q-button should run even if the cursor moved outside it as a result of form validation.

### Reproduction URL

https://jsfiddle.net/v39aem5x/

### How to reproduce?

1) Make sure focus is on the "Required Field" field.
2) Click the "Click Me!" button.
3) If mouse cursor is closer to the bottom side of the "Click Me!" button, the event handler will run and you will see the alert.
If mouse cursor is closer to the top side of the "Click Me!" button, the event handler will most likely not run and you will not see the alert, which should not be happening.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

**Comment by pdanpdan** [comment]
And I thought this was already a solved problem 30 years ago.
Here is a solution I found now: https://codepen.io/mike1532/pen/WNNWdKN

Now to be serious:
- make a design that does not pull the rug from under the pointer
- what is happening is normal - on field blur it is validated, on validation design changes, the button is not there
