### ISSUE TITLE
Quasar dev generates warning about missing feature flag __VUE_PROD_HYDRATION_MISMATCH_DETAILS__ in Vue 3.4

### ISSUE THREAD

**Issue by damvik** [quasarframework/quasar#16778]
### What happened?

Upon running npm install and executing quasar dev, a warning message is displayed:

`Feature flag __VUE_PROD_HYDRATION_MISMATCH_DETAILS__ is not explicitly defined. You are running the esm-bundler build of Vue, which expects these compile-time feature flags to be globally injected via the bundler config in order to get better tree-shaking in the production bundle.`

This warning suggests a possible issue with the integration of the new Vue 3.4 version, where the mentioned feature flag is not being handled correctly during the build process.

### What did you expect to happen?

I expected the Quasar development server to start without any warning messages related to missing feature flags. The integration with Vue 3.4 should handle these flags properly to ensure smooth operation.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-zpnjyq

### How to reproduce?

Create a new Quasar project: npm init quasar
Navigate to the project folder: cd my-project
Run Quasar development server: quasar dev

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(6.5.0-14-generic) - linux/x64
NodeJs - 18.13.0

Global packages
  NPM - 9.6.3
  yarn - 3.5.0
  @quasar/cli - 2.0.0
  @quasar/icongenie - 3.1.1
  cordova - 12.0.0 (cordova-lib@12.0.1)

Important local packages
  quasar - 2.14.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.13 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.56.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by pdanpdan** [comment]
https://github.com/quasarframework/quasar/discussions/16728
