### ISSUE TITLE
Cordova platform wrongfully detected if served over HTTPS

### ISSUE THREAD

**Issue by ghys** [quasarframework/quasar#1678]
https://github.com/quasarframework/quasar/blob/7f2bc3252dddcb9a9f155756437491fca5382923/src/plugins/platform.js#L157-L165

The above evaluates to true if the app is served over HTTPS - this sets the cordova class on the body element, which leads to at least one nasty side effect; a top margin on the layout headers on iOS:

https://github.com/quasarframework/quasar/blob/b32f9c0e66fe0ea938f9c795635e44c9f07aa597/src/components/layout/layout.mat.styl#L71-L76

**Comment by rstoenescu** [comment]
Thanks for reporting! Available in 0.15.6.
