### ISSUE TITLE
QTable row-click event handler not triggered when using  dynamic directive argument: @[name] ="handler"

### ISSUE THREAD

**Issue by xlaussel** [quasarframework/quasar#16786]
### What happened?

I need to activate/desactivate the on-click event on the QTable and to have the cursor behaving accordingly:  normal if not activated and pointer else.

So I use dynamic directive argument:
`@[name] ="handler"`
with name been `"row-click"` when I want the handler to be activated and else`null` 

With name equals to `"row-click"` the cursor is `pointer`(so the handler is detected by QTable ) but the handler is not triggered when the row is clicked.

### What did you expect to happen?

When name is `"row-click"` the handler should be called

### Reproduction URL

https://stackblitz.com/edit/quasarframework-qcz7we?file=src%2FApp.vue

### How to reproduce?

Open the console and click on any row: "Clicked" should be logged but nothing happens.
Note that the cursor is pointer as wanted

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
This seems to be related to Vue's camelCase/kebab-case interpolation behavior. See the relevant [Vue SFC Playground](https://play.vuejs.org/#eNqdVE2P2kAM/StuLslKC7Ra9ZIC3RZRaauKrmhvTQ8hMWGWyUw6M2FBiP9ez+SDwC5I7S1jP9vPjp/33qei6G9K9EJvqBPFCgMaTVmMI8HyQioDe1C4hAMslczBJ6j/ofVNZF7Ujv7APmwq64/EshSJYVKAFBPOknVwA/tIACRSaMmxz2UW+In1+DeRONgQ66LyJjYs+ca0QYEKRuAr+dyrkA1GYUzJN9hBEcmgg6ScpwkncY58EutujMU7cpR4OKjap8bpYTAveGyQXgBD29l4JoHXoUPX69EH923hUeTVDUfeeI5ZyWN1Je7Xabe/T8JnUvSaTiHdiThnSZsLgjUu4kUvoZZuXkl8PqLT1PP/TXthmP9EPGmijwWGg87EvVvPaPp3S5b1n7QUtJtudSIvITTjqL4XdrV05IXVUllfzLl8/upsRpV429iTFSbrV+xPemttkfeoUKPaYOS1PhOrDE3lnv6Y4Za+W2cu05IT+opzjrTjpeVYwT6XIiXaHZxj++BUxET2U0+3NBzdNGWJWuTB4SOPVGUHdan1I927/p2LI0XRFBtFXhO3HWlpMD1XeKOeQslCk1ZSXDKBj/YVuMJSzGv1tEzMrsAQvtTKr3tV+KdkCtMQljHX1fwtP1JoVQFzZtoCU3rooKPeVaxdEUI0VAO6JaNxxax/pAFvRiOgQbs8qUtx6QjZkoHfBNYH6NoFSNmG7siOI+15TtNmoreQxsg8hHdvC1okByPgoiSrgPsXx+A8XLFsZUJ43wkG2O+P/X4Ev/rI0YcQ/IdMSIXudSC2rtqgKucYO4Pm0sCg4jwg0i+kdfgLTyoKqw==)

So, in your case, you can change `ref('row-click')` to `ref('rowClick')` to make it work. You can file an issue at https://github.com/vuejs/core
