### ISSUE TITLE
install ionic framework in quasar app gives me a blank page on safari only but works fine on chrome

### ISSUE THREAD

**Issue by omarhaya** [quasarframework/quasar#16788]
### What happened?

I used to installed ionic framework with quasar successfully in order to get the benefits of both worlds and I've made it everything works fine until I opened the app on safari I got this blank screen problem with no errors in the console(even in freshly installed quasar app) I inspected the white page and tried to uncheck some things on the html  styling and I've got it work by disabling the display:none:!important at the current width of the page but when I change the width of the screen it turns back to blank by the way when I remove the boot file that boots ionic everything backs to normal so any help?
<img width="1512" alt="Screenshot 2024-01-20 at 10 30 19 AM" src="https://github.com/quasarframework/quasar/assets/64192471/03a84f6e-8a0e-4446-89cd-bfb3544f6595">
```
import { boot } from 'quasar/wrappers'
// import App from 'src/pages/App.vue'
import router from '/src/router';
import { IonicVue } from '@ionic/vue';
/* Core CSS required for Ionic components to work properly */
import '@ionic/vue/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/vue/css/normalize.css';
import '@ionic/vue/css/structure.css';
import '@ionic/vue/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/vue/css/padding.css';
import '@ionic/vue/css/float-elements.css';
import '@ionic/vue/css/text-alignment.css';
import '@ionic/vue/css/text-transformation.css';
import '@ionic/vue/css/flex-utils.css';
import '@ionic/vue/css/display.css';

/* Theme variables */
import '/src/theme/variables.css';


export default boot(async ( { app } ) => {
  app.use(IonicVue).use(router);
})

```

### What did you expect to happen?

a problem in the styling that conflicts with the quasar framework (from ionic) 

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

const { useQuasar } = Quasar

const app = Vue.createApp({
  setup () {
    const $q = useQuasar()

    function notify () {
      $q.notify('Running on Quasar v' + $q.version)
    }
    
    return {
      notify
    }
  }
})

app.use(Quasar, { config: {} })
app.mount('#q-app')

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Safari

**Comment by stany-bns** [comment]
it is because ionic adds a class .md in your html element so it creates  a responsive breakpoint  for quasar.

`document.getElementsByTagName("html")[0].classList.remove("md");` should remove the class and you should not have a blank page anymore but doing it can cause ionic to do not work well

the .md class is linked to  [ionic modes(platform styles),](https://ionicframework.com/docs/theming/platform-styles) you can set your platform style to ios.

createApp(App).use(IonicVue, {
  mode: 'ios',
});

once yo do it, you will not have to remove the .md class like i mentionned before cause the class is replaced by .ios
