### ISSUE TITLE
QInput: Passing null value for mask property leads to TypeError (null.length)

### ISSUE THREAD

**Issue by jhfdevelop** [quasarframework/quasar#16784]
### What happened?

By accident @nataliedemma and I discovered, that passing `null` for the `mask` property of a QInput component, leads to the component throwing an error in the setup step, therefore not rendering at all.

After looking at the code, we believe the the culprit is here: https://github.com/quasarframework/quasar/blob/6512975e46b7b65d379a170712351e5d76026547/ui/src/components/input/use-mask.js#L112C1-L114C25

(mask property is checked for undefined but not for null)

### What did you expect to happen?

The component should not throw an error at this part of the setup process.

We propose the component should disregard null values for the mask property in the same way when the property is not set (undefined or empty string)

### Reproduction URL

https://codepen.io/Natalie-Demmelmaier/pen/gOEgJyw

### How to reproduce?

Set the mask property of a QInput component to null (as demonstrated in the reproduction codepen)

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Relevant log output

```Shell
vue.global.prod.js:6 TypeError: Cannot read properties of null (reading 'length')
    at h (quasar.umd.prod.js:6:263415)
    at m (quasar.umd.prod.js:6:263106)
    at Ks (quasar.umd.prod.js:6:262980)
    at setup (quasar.umd.prod.js:6:270108)
    at Ht (vue.global.prod.js:6:15900)
    at vue.global.prod.js:8:20942
    at vue.global.prod.js:8:21098
    at M (vue.global.prod.js:8:21121)
    at L (vue.global.prod.js:8:19470)
    at y (vue.global.prod.js:8:16609)
```

**Comment by yusufkandemir** [comment]
Then, simply do not pass `null`. It's not part of the API, and it's not a "useful" feature to add either.
![image](https://github.com/quasarframework/quasar/assets/6266078/84e0e199-3b01-4bea-832b-feaafd70491b)

**Comment by jhfdevelop** [comment]
Ok, I understand. Thanks for looking into it anyway
