### ISSUE TITLE
props is not declared in QuasarLanguage interface

### ISSUE THREAD

**Issue by cap1024** [quasarframework/quasar#16790]
### What happened?

`props` identifier is not declared in `QuasarLanguage` interface.
```
Quasar.lang.props.label.close
```
This is actual path to `close` localization from script.

### What did you expect to happen?

```
Quasar.lang.label.close
```
This is path to `close` localization from script according to interfaces declaration.

### Reproduction URL

https://codepen.io/cap1024/pen/ZEPyGJL

### How to reproduce?

`$q.lang.label.close` - from template
`Quasar.lang.props.label.close` - from script

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

**Comment by yusufkandemir** [comment]
Duplicate of #14569
