### ISSUE TITLE
softError.message is undefined when opening tab with control-key

### ISSUE THREAD

**Issue by Zefau** [quasarframework/quasar#16791]
### What happened?

Opening a q-tab with `to` attribute using keyboard control-key (CTRL + click) results in the error message `TypeError: softError.message is undefined`. The error message only appears using the CTRL key. Normally opening it does not lead to an error.

>  Uncaught (in promise) TypeError: softError.message is undefined
    go quasar.esm.js:10508
    promise callback*go quasar.esm.js:10499
    onClick quasar.esm.js:10523
    callWithErrorHandling runtime-core.esm-bundler.js:193
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:201
    invoker runtime-dom.esm-bundler.js:671
    addEventListener runtime-dom.esm-bundler.js:625
    patchEvent runtime-dom.esm-bundler.js:640
    patchProp runtime-dom.esm-bundler.js:705
    mountElement runtime-core.esm-bundler.js:5501
    processElement runtime-core.esm-bundler.js:5448
    patch runtime-core.esm-bundler.js:5316
    componentUpdateFn runtime-core.esm-bundler.js:6004
    run reactivity.esm-bundler.js:176
    update runtime-core.esm-bundler.js:6128
    setupRenderEffect runtime-core.esm-bundler.js:6138
    mountComponent runtime-core.esm-bundler.js:5906
    processComponent runtime-core.esm-bundler.js:5860
    patch runtime-core.esm-bundler.js:5328
    mountChildren runtime-core.esm-bundler.js:5576
    mountElement runtime-core.esm-bundler.js:5483
    processElement runtime-core.esm-bundler.js:5448
    patch runtime-core.esm-bundler.js:5316
    mountChildren runtime-core.esm-bundler.js:5576
    mountElement runtime-core.esm-bundler.js:5483
    processElement runtime-core.esm-bundler.js:5448
    patch runtime-core.esm-bundler.js:5316
    componentUpdateFn runtime-core.esm-bundler.js:6004
    run reactivity.esm-bundler.js:176
    update runtime-core.esm-bundler.js:6128
    setupRenderEffect runtime-core.esm-bundler.js:6138
    mountComponent runtime-core.esm-bundler.js:5906
    processComponent runtime-core.esm-bundler.js:5860
    patch runtime-core.esm-bundler.js:5328
    componentUpdateFn runtime-core.esm-bundler.js:6004
    run reactivity.esm-bundler.js:176

### What did you expect to happen?

Tab opens without error message.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-decghk?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Open stackblitz and "Open in New Tab" (top right)
2. Hold CTRL and click on either one of the two tabs
3. see error message in the console `Uncaught (in promise) TypeError: softError.message is undefined`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 20.10.0

Global packages
  NPM - 10.3.0
  yarn - 1.22.21
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
```

### Relevant log output

```Shell
Uncaught (in promise) TypeError: softError.message is undefined
    go quasar.esm.js:10508
    promise callback*go quasar.esm.js:10499
    onClick quasar.esm.js:10523
    callWithErrorHandling runtime-core.esm-bundler.js:193
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:201
    invoker runtime-dom.esm-bundler.js:671
    addEventListener runtime-dom.esm-bundler.js:625
    patchEvent runtime-dom.esm-bundler.js:640
    patchProp runtime-dom.esm-bundler.js:705
    mountElement runtime-core.esm-bundler.js:5501
    processElement runtime-core.esm-bundler.js:5448
    patch runtime-core.esm-bundler.js:5316
    componentUpdateFn runtime-core.esm-bundler.js:6004
    run reactivity.esm-bundler.js:176
    update runtime-core.esm-bundler.js:6128
    setupRenderEffect runtime-core.esm-bundler.js:6138
    mountComponent runtime-core.esm-bundler.js:5906
    processComponent runtime-core.esm-bundler.js:5860
    patch runtime-core.esm-bundler.js:5328
    mountChildren runtime-core.esm-bundler.js:5576
    mountElement runtime-core.esm-bundler.js:5483
    processElement runtime-core.esm-bundler.js:5448
    patch runtime-core.esm-bundler.js:5316
    mountChildren runtime-core.esm-bundler.js:5576
    mountElement runtime-core.esm-bundler.js:5483
    processElement runtime-core.esm-bundler.js:5448
    patch runtime-core.esm-bundler.js:5316
    componentUpdateFn runtime-core.esm-bundler.js:6004
    run reactivity.esm-bundler.js:176
    update runtime-core.esm-bundler.js:6128
    setupRenderEffect runtime-core.esm-bundler.js:6138
    mountComponent runtime-core.esm-bundler.js:5906
    processComponent runtime-core.esm-bundler.js:5860
    patch runtime-core.esm-bundler.js:5328
    componentUpdateFn runtime-core.esm-bundler.js:6004
    run reactivity.esm-bundler.js:176
```

**Comment by rstoenescu** [comment]
Fix will be available in 2.14.3
