### ISSUE TITLE
"Negative" toast icon change from "whatshot" to "error"

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar#168]
I was surprised to see that the `negative` type toast displays the social icon `whatshot`, and that I can't change it. To display error toasts with the material design icon `error` I have to create toasts with all the options.

Wouldn't an `error` type toast (with the material design icon `error`) be useful along with `info` and `warning`?

**Comment by rstoenescu** [comment]
You already have "info" and "warning" Toast types. Please check documentation.
On the icon I felt it was more appropriate to use "whatshot" instead of "error". "error" icon seems milder than the warning. Anyways, pushed patch for the "negative" Toast to use "error" instead of "whatshot".

**Comment by rstoenescu** [comment]
If there is a solid reason for further changes (let's say like the icon chosen for "negative" Toasts) we can tweak the other "default" types like "info", "warning" and "positive" too.

**Comment by laurentpayot** [comment]
I knew we already have "info" and "warning" Toast types. My only concern was the icon. If "negative" toasts have the real "error" icon then I'm happy 👍
