### ISSUE TITLE
Disabled input breaks links in description 

### ISSUE THREAD

**Issue by ivanjaros** [quasarframework/quasar#16810]
### What happened?

When input is disabled it will receive certain classes to make it so. The problem is that these are applied onto the label element which wraps the footer holding the hint/description. If this text holds a link, it becomes broken/cannot be clicked.

I consider this a bug simply because disabled input should not influence the neighbouring elements.

![obrázok](https://github.com/quasarframework/quasar/assets/64546059/7e98d1b3-a132-4a67-a1a2-8ac1d2ad2c54)

### What did you expect to happen?

Hint area to behave as usual.

### Reproduction URL

https://quasar.dev/vue-components/input

### How to reproduce?

Create any kind of q-input, add hint slot with a link in it. Make the input disabled, try to click on the link in the description.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by nicolasmartinrojo** [comment]
Hi @ivanjaros. I've just taken a look at your PR and I'm seeing that on the q-input class even tho it has the disabled class, it still allows you to click on the label below

![Screen Shot 2024-01-27 at 00 33 25](https://github.com/quasarframework/quasar/assets/583394/b1f3fcbc-a510-46b8-8503-2be1a913a653)
![Screen Shot 2024-01-27 at 00 33 19](https://github.com/quasarframework/quasar/assets/583394/b8f8e052-aeeb-4b41-a8d1-77a494024cbe)

The class that has the no-pointer-events is the one assigned to the label inside the q-input, so in this case it still be able to click on the text below the input.

let me know if I wasn't clear.

**Comment by ivanjaros** [comment]
@nicolasmartinrojo the problem here is that the hint is behind the label's padding so the z-index causes it to be under the disabled area, making the links non-clickable(the green section in your image).

**Comment by pdanpdan** [comment]
Make a codepen

**Comment by ivanjaros** [comment]
Sorry, user error. Somehow `no-pointer-events` class got into the code that made it look like disabled was the problem.
