### ISSUE TITLE
Content moves out of editor with max-height

### ISSUE THREAD

**Issue by martinscholz83** [quasarframework/quasar#1681]
### Software version

Quasar: 0.15.5
OS: macOS 10.13.3
Node: 9.6.1
NPM: 5.6.0
Browsers: Chrome, Safari
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/0zeL269w/5/

### What did you get as the error?
If you set `max-height` for an editor content moves out of editor. See example in jsfiddle.

### What were you expecting?
Editor should show an scrollbar.

**Comment by rstoenescu** [comment]
Available in 0.15.6
