### ISSUE TITLE
Compiled with problems: ERROR in tsconfig.json  TS5023: Unknown compiler option 'verbatimModuleSyntax'

### ISSUE THREAD

**Issue by fengjac** [quasarframework/quasar#16826]
### What happened?

 » App dir................... D:\workspace\quasar-project
 » App URL................... http://localhost:8080
 » Dev mode.................. spa
 » Pkg quasar................ v2.14.3
 » Pkg @quasar/app-webpack... v3.12.3
 » Transpiled JS............. yes (Babel)

ERROR in tsconfig.json
TS5023: Unknown compiler option 'verbatimModuleSyntax'.

### What did you expect to happen?

No error

### Reproduction URL

https://github.com/fengjac/quasar-demo-1

### How to reproduce?

1. pnpm create quasar:
√ What would you like to build? » App with Quasar CLI, let's go!
√ Project folder: ... quasar-project
√ Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
√ Pick script type: » Typescript
√ Pick Quasar App CLI variant: » Quasar App CLI with Webpack
√ Package name: ... quasar-project
√ Project product name: (must start with letter if building mobile apps) ... Quasar App
√ Project description: ... A Quasar Project
√ Pick a Vue component style: » Composition API with <script setup>
√ Pick your CSS preprocessor: » Sass with SCSS syntax
√ Check the features needed for your project: » ESLint, State Management (Pinia), Axios, Vue-i18n
√ Pick an ESLint preset: » Prettier

2. pnpm add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin typescript@5.1.6
3. update tsconfig.json
{
  "extends": "@quasar/app-webpack/tsconfig-preset",
  "compilerOptions": {
    "baseUrl": ".",
    "verbatimModuleSyntax": true
  }
}
4. update .vscode/settings.json
{
  ...,
  "typescript.tsdk": "node_modules/typescript/lib"
}
5. pnpm run dev

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

TypeScript Support

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19041) - win32/x64
NodeJs - 18.17.1

Global packages
  NPM - 9.6.7
  yarn - 1.22.19
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.12.3 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.15 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.23.9 -- Babel compiler core.
  webpack - 5.90.0 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 5.1.6 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
```

**Comment by yusufkandemir** [comment]
app-webpack v3 uses TypeScript v4, and unfortunately, it uses the version it ships, not the one you install. This is changed in app-webpack v4 beta and you will have full control.

With the current stable version, as a workaround, you can add the following to your `package.json`:
```json
{
  "resolutions": {
    "typescript": "5.1.6"
  }
}
```
this way it would ensure all packages that have `typescript` dependency use v5.1.6.
