### ISSUE TITLE
About upgrading from 0.14

### ISSUE THREAD

**Issue by Somefive** [quasarframework/quasar#1683]
Hi, I was using Quasar since 0.14 version. However, recently I found the old configuration - "quasar-framework": "git+https://git@github.com/quasarframework/quasar-edge.git" is missing which disabled me from using 'npm install'.
I wondered how to fix this problem since the newest Quasar repo is using 0.15.

**Comment by rstoenescu** [comment]
Edge and Future repos have been removed.
Replace git+https://git@github.com/quasarframework/quasar-edge.git with 0.14.9.

PS: Please use our Discord for questions. Thanks!

**Comment by Somefive** [comment]
Thanks!
