### ISSUE TITLE
q-select emit-value not work, v-model value is still an object and not a value

### ISSUE THREAD

**Issue by MiracleLinAlpha** [quasarframework/quasar#16845]
### What happened?

`<q-select filled v-model="bid_type" emit-values map-options
    :options="bid_type_options" />

const bid_type = ref(null)

const bid_type_options = ref([
        { value: 'AUTO_BID', label: '自动出价' },
        { value: 'MANUAL_BID', label: '手动出价' },
    ])

`
when select a option, the v-model value bid_type is still an object and not a value, already used 'emit-values' and 'map-options' in q-select

### What did you expect to happen?

the v-model value bid_type is a value in the option item 'value'

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

`
<div id="q-app">
  <q-select filled v-model="bid_type" emit-values map-options :options="bid_type_options"" />
</div>

const { useQuasar } = Quasar

const app = Vue.createApp({
  setup () {
    const $q = useQuasar()
    
    const bid_type = ref(null)

    const bid_type_options = ref([
        { value: 'AUTO_BID', label: '自动出价' },
        { value: 'MANUAL_BID', label: '手动出价' },
    ])
    
    return {
      bid_type,
      bid_type_options
    }
  }
})

app.use(Quasar, { config: {} })
app.mount('#q-app')

`

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

**Comment by pdanpdan** [comment]
Works perfectly fine in your provided repro

**Comment by MiracleLinAlpha** [comment]
My template is "<q-select filled v-model="bid_type" :options="bid_type_options" label="出价类型："emit-values map-options />" don't know why is not display in bug comment, and i find the issue reason is type “emit-value” to “emit-values”, it's not a quasar bug, thank you for your answer.
