### ISSUE TITLE
Icongenie: favicon.ico and favicon.pngs are not generating

### ISSUE THREAD

**Issue by mrkprdo** [quasarframework/quasar#16840]
### What happened?

Ran icongenie to generate icons.
file in public/* is not updated. Tried removing them manually, but then it could not get the files generated.

### What did you expect to happen?

favicon files generated

### Reproduction URL

n/a

### How to reproduce?

install latest icongenie
run `icongenie generate -m cordova -i logo.png -b background.png`
run `icongenie verify` if it says OK, double check the actual files in public/

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Icon Genie CLI (@quasar/icongenie)

### Platforms/Browsers

Other

### Quasar info output

```Shell
n/a
```

### Relevant log output

```Shell
no logs
```

### Additional context

icons missing

**Comment by yusufkandemir** [comment]
As you are generating for `cordova` mode only, you will get the Cordova-specific icons only. They will be generated into `src-cordova/res`. For favicon files, run `spa` mode as well, e.g. `-m cordova,spa`
