### ISSUE TITLE
[Bug] QSelect does not allow white space in filter

### ISSUE THREAD

**Issue by rmandrei** [quasarframework/quasar#1684]
Operating System                Darwin(17.2.0) - darwin/x64
NodeJs                          8.9.1          
  NPM                           5.5.1
  quasar-cli                    0.15.5
  vue-cli                       2.9.3

**What did you get as the error?**
When typing inside the QSelect's filter input, white spaces are not allowed and removed at 'keypress'.  This goes for typing at the end of the string, or inside the string.

**What were you expecting?**
QSelect can have labels that contain white spaces, i expected to use whitespaces when filtering.

**What steps did you take, to get the error?**
Just a normal QSelect with filter enabled.

**Comment by rstoenescu** [comment]
Fix available in 0.15.6
