### ISSUE TITLE
[Bug 0.15.5]  QDateTime after handler not setting popup value via v-model bind

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#1686]
Adjusting the v-model value on a qDatetime via the :after button handler sets the input, but not the popup value.

Code sample showing issue:
https://codepen.io/anon/pen/vdMXJV?editors=1010#0

### What did you get as the error?
No Error

### What were you expecting?
Popup value to reflect change in v-model

#### Suggestion
Also, i'd think a "Today/Now" button in the popup makes more sense from a UI perspective.  Having a "Today" button on the input line isn't as intuitive to me....

**Comment by rstoenescu** [comment]
Seems ok to me??
If indeed it would be a problem, it wouldn't be from Quasar, but due to bad scoping...

![mar-03-2018 05-28-33](https://user-images.githubusercontent.com/4665641/36930155-0d7ad2ee-1ea4-11e8-9b63-876ffa18f086.gif)

**Comment by Lou-Der** [comment]
Try hitting the "Today" button and then clicking the popup calendar.  It has the old value, not the new one from the :after handler.
