### ISSUE TITLE
QExpansionItem does not expand inside QMenu with Vue 3.4.16

### ISSUE THREAD

**Issue by cap1024** [quasarframework/quasar#16876]
### What happened?

QExpansionItem does not expand inside QMenu after update Vue to v3.4.16 but works correctly with Vue v3.4.15

### What did you expect to happen?

QExpansionItem expands inside QMenu after update Vue to v3.4.16 too

### Reproduction URL

https://codepen.io/cap1024/pen/NWJbZbB

### How to reproduce?

**Case 1**
1. Click MENU
2. Click (expand) EXPANSION_1 (initially collapsed)

**Case 2**
1. Click MENU
2. Click (collapse) EXPANSION_2 (initially expanded)
3. Click (expand) EXPANSION_2

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Chrome, Android

**Comment by howbizarre** [comment]
This happens to me too - when return to vue@3.4.15 - expansion goes back to normal.

**Comment by ericrange** [comment]
here the same. still works with 3.4.15

**Comment by ericrange** [comment]
here is reprodution with your expansion examples:
https://codepen.io/theric91/pen/MWxqyEK?editors=101

**Comment by ericrange** [comment]
the problem is that the "display: none" wont disappear:
![image](https://github.com/quasarframework/quasar/assets/1785416/a21626b0-00ab-4a35-a1df-993b53345f36)
dirty workaround:
```
.q-expansion-item--expanded .q-expansion-item__content {
  display: block !important;
}
```

**Comment by amermemic95** [comment]
I've encountered the same issue with `<q-expansion-item>` component after upgrading from Vue version `3.4.15` to `3.4.16`. The `<q-expansion-item>` functionality seems to break with the newer Vue version.

**Comment by EricBrennan247** [comment]
Same issue here, none of our expansion items work, rolling back to a previous version until fix issued

**Comment by rstoenescu** [comment]
Please use Vue 3.4.15 until the Vue team has a chance to fix this issue.

**Comment by howbizarre** [comment]
@cap1024 @rstoenescu
In my case - with Vue v3.4.18 all expansions return to normal.

**Comment by rstoenescu** [comment]
It seems like it. Thanks for posting the resolution and closing the ticket!

**Comment by rstoenescu** [comment]
For completeness, this was the initial culprit in Vue: https://github.com/vuejs/core/commit/9b19f0912104bfccb10c8cf5beab02b21a648935
