### ISSUE TITLE
QField and QInput clear event

### ISSUE THREAD

**Issue by moom-en** [quasarframework/quasar#16871]
### What happened?

When the clear button is clicked, the clear function will not be executed

### What did you expect to happen?

exec clear function

### Reproduction URL

https://jsfiddle.net/4yj32pcf/11/

### How to reproduce?

click clear btn

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Electron

**Comment by DaleMckeown** [comment]
In the fiddle, you're hiding the input on focus, which is a very strange thing to do.

The clear function is properly called when you remove the weird stuff you've done with focus.

https://jsfiddle.net/p3rsuxw1/

**Comment by moom-en** [comment]
> In the fiddle, you're hiding the input on focus, which is a very strange thing to do.
> 
> The clear function is properly called when you remove the weird stuff you've done with focus.
> 
> https://jsfiddle.net/p3rsuxw1/

There is no problem using input and field separately. I discovered this issue by creating a dropdown table using input and Popup Proxy

**Comment by rstoenescu** [comment]
You're activating/showing a popup (so this gets focus) before the click action can get executed on your initial QInput.

You've mentioned something about a dropdown table. Please create a codepen with your exact usage so we can help you. Closing but will reopen when the requested codepen is available.

**Comment by moom-en** [comment]
@rstoenescu @DaleMckeown  I need to define it as a new component (QSelectTable) through QInput+QTable. The QInput input content filters the content in the QTable. The final display is very similar to QSelect (only there is a QTable below). Similar components include QInput+QTree defined as a new component (QSelectTree), but the problem I described was discovered when writing the code. The scenario is as follows: For example, there is the sentence "I like quasar" in QInput. When I click When pressing the clear button, I hope to clear the content of QInput and display the QTable to select values.
