### ISSUE TITLE
Reopening #16227 No way to set a alt tag on QImg 

### ISSUE THREAD

**Issue by wayerger** [quasarframework/quasar#16886]
### What happened?

To comply with Google's Image SEO Best Practices ([https://developers.google.com/search/docs/appearance/google-images#:~:text=When%20writing%20alt%20text%2C%20focus,to%20be%20seen%20as%20spam)]) images should have an alt tag on them.  However, I can not find a way to put an alt tag on a q-img in Quasar so that it is accessible to Google's crawlers.   This is likely to negatively impact the SEO of Quasar sites.

### What did you expect to happen?

I expected to be able to put an alt tag on a q-img.

### Reproduction URL

https://jsfiddle.net/26utwn1s/

### How to reproduce?

<q-img src="https://cdn.quasar.dev/img/parallax2.jpg" alt="Parallax" />

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Thanks for opening this.
Fix will be available in Quasar v2.14.4
