### ISSUE TITLE
Cannot read properties of null (reading 'isCE') 

### ISSUE THREAD

**Issue by Valgri** [quasarframework/quasar#16896]
### What happened?

I get this error after I moved from webpack to vite in my quasar project.

![image](https://github.com/quasarframework/quasar/assets/28981859/13a0ff85-f904-4321-b2f4-4cdc67bc4cb1)

everything works fine just in the vite-vue build here's a [link](https://stackblitz.com/edit/vitejs-vite-r44rzc?file=src%2FApp.vue,package.json,src%2Fcomponents%2FHelloWorld.vue&terminal=dev) to vite-vue, link to quasar-vite in the (reproducible url) section

both of which I use

 "vue": "^3.4.18",
 "vue-slider-component": "^4.1.0-beta.7"

### What did you expect to happen?

No error, the component is rendering

### Reproduction URL

https://stackblitz.com/edit/quasarframework-bfe2lw?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

open Reproduction URL
and run yarn dev.
open dev tools of browser and you will see the error.
Slider you can find on IndexPage.vue (quasar default boilerplate I used for this).

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
This is an issue with Vite 2 (which will not receive any further updates).
Please upgrade to q/app-vite 2.0.0-beta.1 (which has Vite 5). https://github.com/quasarframework/quasar/discussions/16877

It seems to work just fine with it. For the project that you've put a link to, you'd need to do this:

* Rename `/.eslintrc.js` to `/.eslintrc.cjs`
* Rename `/postcss.config.js` to `/postcss.config.cjs`
* Change `/quasar.config.js`:
  ```js
  import { configure } from 'quasar/wrappers';
  export default configure(function (/* ctx */) {
  ```
* Change `/package.json`:
  ```json
  "type": "module",
  "devDependencies": {
    "@quasar/app-vite": "^2.0.0-beta.1",
  ```

**Comment by Valgri** [comment]
Thanks a lot! It works.
