### ISSUE TITLE
Visual problem with inner loading component inside a qCard

### ISSUE THREAD

**Issue by AmosSzust** [quasarframework/quasar#16909]
### What happened?

The upper part of the inner loading component does not follow the card's border radius, the bottom part does. If there was a way for the dimming to cover all the card, it would be even better.

![image](https://github.com/quasarframework/quasar/assets/100950035/d7cd5993-fd99-46f9-be48-0013db688396)

### What did you expect to happen?

I expect all the corners of the inner loading component to be shown with the border radius.

### Reproduction URL

https://codepen.io/amosss/pen/MWxxBOd

### How to reproduce?

https://codepen.io/amosss/pen/MWxxBOd

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Style & Identity (quasar)

### Platforms/Browsers

Microsoft Edge

### Additional context

using quasar 2.14.4

**Comment by rstoenescu** [comment]
Thanks for opening this ticket.
Fix will be available in Quasar v2.14.5

**Comment by AmosSzust** [comment]
Thank you!
