### ISSUE TITLE
QEditor style error after using paragraph-tag prop 

### ISSUE THREAD

**Issue by ageeye-cn** [quasarframework/quasar#16905]
### What happened?

I set paragraph-tag to "p"，The first line is not included within  the P tag.
`<q-editor v-model="content" paragraph-tag="p"></q-editor>`
![微信截图_20240217225253](https://github.com/quasarframework/quasar/assets/1737208/541e60ec-f0a3-4cf3-a1a2-c6db4a105235)
`test1<p>test2</p><p>test3</p>`
![微信截图_20240217225325](https://github.com/quasarframework/quasar/assets/1737208/c4d09447-c39b-4f4e-8150-a2903974eb4f)

### What did you expect to happen?

`<p>test1</p><p>test2</p><p>test3</p>`

### Reproduction URL

https://codepen.io/ageeye-cn/pen/NWJJWgO

### How to reproduce?

browse the codepen demo

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

**Comment by johndegey** [comment]
Hello,

Same problem for me with the default 'div'' with "quasar": "^2.17.4", "@quasar/app-vite": "^1.11.0"
Here what I got in the source `Is there anybody out there ?<div><br></div>`

Seems to work in the codepen example...
Maybe i've missed something.

John

**Comment by rstoenescu** [comment]
Hi,

Unfortunately we have no control over how the browser decides to generate the content. QEditor relies on `document.execCommand()` and `document.queryCommandState()`.
