### ISSUE TITLE
QPageSticky Fixed+Expand behind scrollable content

### ISSUE THREAD

**Issue by robsoncombr** [quasarframework/quasar#1690]
### Software version

Operating System                Linux(4.13.0-36-generic) - linux/x64
NodeJs                          8.9.4

Global packages
  NPM                           5.6.0
  yarn                          Not available
  quasar-cli                    0.15.7
  vue-cli                       2.9.3
  cordova                       8.0.0

Important local packages
  quasar-cli                    0.15.7
  quasar-framework              0.15.6
  quasar-extras                 1.0.2
  vue                           2.5.13
  vue-router                    3.0.1
  vuex                          3.0.1
  electron                      Not available
  babel-core                    6.26.0
  webpack                       3.11.0
  webpack-dev-server            2.11.1

### What did you get as the error?
When using q-page-sticky with fixed to top with expand property, it is placed behind the content as we can see on illustration.

Using:
```<q-page-sticky expand position="top">```
Result: 
![image](https://user-images.githubusercontent.com/923997/36944797-fffbc9c8-1f81-11e8-94e8-23b4dddcf465.png)

### What were you expecting?
I'm expecting to have the fixed q-page-sticky over the content. The temporary workaround was to add style="z-index: 1", need to implement a permanent fix.

Using:
```<q-page-sticky expand position="top" style="z-index: 1">```
Result:
![image](https://user-images.githubusercontent.com/923997/36944798-0a8673d4-1f82-11e8-82e3-3758911c40eb.png)

**Comment by rstoenescu** [comment]
Have you placed QPageSticky after page content? Otherwise you're using it wrong because of CSS specs.
