### ISSUE TITLE
German Abbreviation for March potentially wrong 

### ISSUE THREAD

**Issue by hdrodel** [quasarframework/quasar#16901]
### What happened?

I saw that the Month abbreviations in German are the following:

```
[
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Mai",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Okt",
    "Nov",
    "Dez"
]

```
The German month März (March) would probably have to be Mär instead of Mar. I'm not sure what standard quasar is aiming for. 
According to [this ](https://de.wikipedia.org/wiki/Monat#:~:text=bis%20mehrere%20Erdenjahre.-,Kurzformen,-%5BBearbeiten%20%7C)wikipedia article, the ISO 8601 standard even uses Mrz as abbreviation instead of Mär (to avoid the special character "ä").

### What did you expect to happen?

The abbreviation for March in German should either be Mär or Mrz 

### Reproduction URL

https://codepen.io/hdrodel/pen/MWxZmjP

### How to reproduce?

Have the language set to German and either log `$q.lang.date.monthsShort`or open a datePicker component and select a date in March 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Good point. From my knowledge, both März and Mai should not be abbreviated, but we need something, so using their full form (which is short anyway).

Will be available in Quasar v2.14.4
