### ISSUE TITLE
emit('hide') in q-dialog closes dialog abruptly, lacks fade-out animation

### ISSUE THREAD

**Issue by ShlomoCode** [quasarframework/quasar#16912]
### What happened?

when I close the dialog from the component (`$emit('hide')`), the dialog closes sharply, and not with the default fade-out animation that exists when clicking outside the dialog

### What did you expect to happen?

The closing design will be in a fade out style, like when clicking manually outside the dialog

### Reproduction URL

https://stackblitz.com/edit/quasarframework-dwemrv

### How to reproduce?

In the stackblitz example, click on the "Open Dialog" button and then on the "Close Dialog" button within the dialog

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

This is the exact problem. That you are emitting the `hide` event on your own. You should follow the docs, call `useDialogPluginComponent()` and retrieve onDialogCancel (or onDialogOK) and call that instead. You also have the `v-close-popup` Quasar directive alternative that you can use on your button.

MyDialog.vue is missing some other aspects, so posting here how it should look like:

```vue
<template>
  <q-dialog ref="dialogRef" @hide="onDialogHide">
    <q-card class="q-dialog-plugin">
      <!--
        ...content
        ... use q-card-section for it?
      -->

      <!-- buttons example -->
      <q-card-actions align="right">
        <q-btn color="primary" label="OK" @click="onOKClick" />
        <q-btn color="primary" label="Cancel" @click="onDialogCancel" />
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

<script setup>
import { useDialogPluginComponent } from 'quasar'

const props = defineProps({
  // ...your custom props
})

defineEmits([
  // REQUIRED; need to specify some events that your
  // component will emit through useDialogPluginComponent()
  ...useDialogPluginComponent.emits
])

const { dialogRef, onDialogHide, onDialogOK, onDialogCancel } = useDialogPluginComponent()
// dialogRef      - Vue ref to be applied to QDialog
// onDialogHide   - Function to be used as handler for @hide on QDialog
// onDialogOK     - Function to call to settle dialog with "ok" outcome
//                    example: onDialogOK() - no payload
//                    example: onDialogOK({ /*...*/ }) - with payload
// onDialogCancel - Function to call to settle dialog with "cancel" outcome

// this is part of our example (so not required)
function onOKClick () {
  // on OK, it is REQUIRED to
  // call onDialogOK (with optional payload)
  onDialogOK()
  // or with payload: onDialogOK({ ... })
  // ...and it will also hide the dialog automatically
}
</script>
```

This is all from [docs](https://quasar.dev/quasar-plugins/dialog#sfc-with-script-setup-and-composition-api-variant), so please read them carefully.
