### ISSUE TITLE
QPopupProxy has default background on bigger screens, however has no background on smaller screens.

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#16918]
### What happened?

sample:
`<q-btn push color="primary" label="Handles click">
      <q-popup-proxy>
        <q-tree
      :nodes="simple"
      node-key="label"
    />
      </q-popup-proxy>
    </q-btn>`
the above sample, QTree has default background on bigger screens, has no background on smaller screens.

### What did you expect to happen?

QTree has default background both on bigger screens and on smaller screens.

### Reproduction URL

https://codepen.io/zouzg7829/pen/dyrEWLE?editors=1010

### How to reproduce?

https://codepen.io/zouzg7829/pen/dyrEWLE?editors=1010

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

The QTree has no background color by default to be easily configurable. Attach one (CSS or a `bg-*` class).

**Comment by zouzg7829** [comment]
> Hi,
> 
> The QTree has no background color by default to be easily configurable. Attach one (CSS or a `bg-*` class).

Thanks, but I think this should be a bug about QPopupProxy,  I have changed the issue title, please reconsider it.

**Comment by rstoenescu** [comment]
Reopening for later reasessment.

**Comment by rstoenescu** [comment]
Hi,

This is not a bug.

* On smaller screens, a QMenu is used, which has its own container, so we can give it a default background color.
* On bigger screens (based on the breakpoint of QPopupProxy) a QDialog is used, and this one does not have a "container" of its own. It's just the backdrop and your content, which can be anything.

Usually, it would be a good practice to put your content inside of a QCard (which is what we recommend when using QDialogs anyway).
