### ISSUE TITLE
[Enhancement] Add alternate text to <object> elements

### ISSUE THREAD

**Issue by kpwbo** [quasarframework/quasar#1693]
Hello! :)

`<object>` elements are used in some places, like QResizeObservable, without an alternate text. Lighthouse (Google Chrome 64.0) reports these as accessibility issues. To reproduce, run Lighthouse on this [demo page](http://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/play-with-layout).

It would be great if alternate text could be added to these elements. However, I'm not sure what kind of alternate text would be relevant. Information about this issue can be found [here](https://dequeuniversity.com/rules/axe/3.0/object-alt).

<details>
<summary>Screenshot of relevant Lighthouse results</summary>

![image](https://user-images.githubusercontent.com/5074608/36949436-5bffd172-1fb6-11e8-98e4-9a016a04afb5.png)
</details>

**Comment by rstoenescu** [comment]
Available in 0.15.7
