### ISSUE TITLE
Google Chrome extension does not open after restarting the browser

### ISSUE THREAD

**Issue by gangal86** [quasarframework/quasar#16959]
### What happened?

Google Chrome extension does not open after restarting the browser

### What did you expect to happen?

I want it to open)

### Reproduction URL

no url

### How to reproduce?

1. Open BEX on Chrome

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

BEX Mode

### Platforms/Browsers

Chrome

### Additional context

The problem is in the file src-bex/background.js

I changed this code

---

```
chrome.runtime.onInstalled.addListener(() => {
  chrome.action.onClicked.addListener((/* tab */) => {
    // Opens our extension in a new browser window.
    // Only if a popup isn't defined in the manifest.
    chrome.tabs.create({
      url: chrome.runtime.getURL('www/index.html')
    }, (/* newTab */) => {
      // Tab opened.
    })
  })
})
```

---

to this

---

```
function openExtension() {
  chrome.tabs.create(
    {
      url: chrome.runtime.getURL('www/index.html'),
    },
    (/* newTab */) => {
      // Tab opened.
    },
  );
}

chrome.runtime.onInstalled.addListener(() => {
  openExtension();
});

chrome.action.onClicked.addListener(() => {
  openExtension();
});
```

---

And everything started to work

**Comment by rstoenescu** [comment]
Thanks for reporting this!
Will be available when spawning bex with q/app-vite v1.7.4 & 2.0.0-beta.4 and q/app-webpack 4.0.0-beta.6
