### ISSUE TITLE
Cannot change variables i src/css/quasar.variables.scss with "@quasar/app-webpack": "^4.0.0-beta.4"

### ISSUE THREAD

**Issue by Pietervanhalem** [quasarframework/quasar#16954]
### What happened?

When I create a new app with `npm init quasar` using the new quasar/app-webpack I cannot change variables in  `src/css/quasar.variables.scss` This changed for the new quasar/app-webpack 

### What did you expect to happen?

In previous versions when I changed the values of `$primary` in `src/css/quasar.variables.scss` to red my app would become red. 

### Reproduction URL

https://github.com/VanOord/quasar-variables-bug

### How to reproduce?

1 run `npm init quasar` and select the following options:
    ✔ What would you like to build? › App with Quasar CLI, let's go!
    ✔ Project folder: … quasar-project
    ✔ Pick Quasar version: › Quasar v2 (Vue 3 | latest and greatest)
    ✔ Pick script type: › Javascript
    ✔ Pick Quasar App CLI variant: › Quasar App CLI with Webpack (BETA | next major version - v4)
    ✔ Package name: … quasar-project
    ✔ Project product name: (must start with letter if building mobile apps) … Quasar App
    ✔ Project description: … A Quasar Project
    ✔ Author: … Pieter van Halem <pieter.vanhalem@vanoord.com>
    ✔ Pick your CSS preprocessor: › Sass with SCSS syntax
    ✔ Check the features needed for your project: › ESLint, State Management (Pinia), State Management (Vuex) [DEPRECATED by Vue Team], Axios
    ✔ Pick an ESLint preset: › Airbnb
2. run `npm ci`
3. run `quasar dev`
4. change  `$primary` in `src/css/quasar.variables.scss` to red
5. the app does not update.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Thanks for reporting this!
Fix will be available in v4.0.0-beta.5
