### ISSUE TITLE
i18n in ButtonToggle will affect the CSS

### ISSUE THREAD

**Issue by vanngoh** [quasarframework/quasar#16965]
### It's working charmingly if we define the `options` with static text as below.
```
<div class="col-8">
    <q-btn-toggle
        v-model="col.keyType"
        class="border-primary"
        spread
        no-caps
        rounded
        unelevated
        toggle-color="primary"
        color="white"
        text-color="primary"
        :options="[
          { label: 'key_a', value: 'key_a' },
          { label: 'key_b', value: 'key_b' },
          { label: 'key_c', value: 'key_c' },
        ]"
    />
</div>
```
<img width="500" alt="Screenshot 2024-03-04 at 16 38 47" src="https://github.com/quasarframework/quasar/assets/125730430/bf297636-75af-48c6-ac02-41317a53a717">

### However, if we need the label to support i18n, it will become distorted with the code below.
```
<div class="col-8">
    <q-btn-toggle
        v-model="col.keyType"
        class="border-primary"
        spread
        no-caps
        rounded
        unelevated
        toggle-color="primary"
        color="white"
        text-color="primary"
        :options="[
          { label: $t('key_a'), value: 'key_a' },
          { label: $t('key_b'), value: 'key_b' },
          { label: $t('key_c'), value: 'key_c' },
        ]"
    />
</div>
```
<img width="500" alt="Screenshot 2024-03-04 at 16 41 00" src="https://github.com/quasarframework/quasar/assets/125730430/a544fffd-d9d0-4635-a849-9c45fe2aeb55">
<p>⬆️ It will either have the padding on y-axis if the i18n keys are not found OR</p>

<img width="500" alt="Screenshot 2024-03-04 at 16 41 58" src="https://github.com/quasarframework/quasar/assets/125730430/ddb39e6c-1485-4df0-a5f2-b60513b95eb7">
<p> ⬆️ It will have a wide space at the bottom if all the i18n keys are defined. </p>

### What did you expect to happen?

It should be same as this layout (no extra padding or white space at the bottom) for i18n support.

<img width="500" alt="Screenshot 2024-03-04 at 16 38 47" src="https://github.com/quasarframework/quasar/assets/125730430/bf297636-75af-48c6-ac02-41317a53a717">

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-n7zwnx?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Go to the [Reproduction URL](https://stackblitz.com/edit/quasarframework-webpack-n7zwnx?file=src%2Fpages%2FIndexPage.vue) and wait for the Preview

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari

**Comment by rstoenescu** [comment]
Hi,

This is a really weird one, but remove the "column" class from your QPage. That's the one generating the issue.

**Comment by vanngoh** [comment]
Hi @rstoenescu,

Oh yeah after removed that it works fine now, thanks!
It's really weird, appreciate your help! 🙌
