### ISSUE TITLE
QList not being imported in QUpload

### ISSUE THREAD

**Issue by Darkwolf-359** [quasarframework/quasar#1696]
When importing QUpload directly from `quasar.mat.esm`; vue throws an error as QList isnt being imported directly in the file.

```[Vue warn]: Unknown custom element: <q-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.```

Looks to have been introduced in this commit: https://github.com/quasarframework/quasar/commit/91b7d0b5491d182a918ba954329128f7443dc91c

For now I've fixed the issue by adding QList as a global component in vue using this:
`Vue.use(Quasar, { plugins: [Dialog, Notify], directives: [CloseOverlay], components: [QList] });`

**Comment by rstoenescu** [comment]
Will be available in 0.15.7. Thanks for reporting!
