### ISSUE TITLE
Handling event on a DOM event handler

### ISSUE THREAD

**Issue by ShlomoCode** [quasarframework/quasar#16973]
### Description

https://quasar.dev/quasar-utils/other-utils#handling-event-on-a-dom-event-handler

Shouldn't this be on the "[DOM Utils](https://quasar.dev/quasar-utils/dom-utils)" page and not in "Other Utils"? This is absolutely a DOM utility, just like "[Execute when DOM is ready](https://quasar.dev/quasar-utils/dom-utils#execute-when-dom-is-ready)", and it should be on the DOM utils page

### Documentation Section URL

https://quasar.dev/quasar-utils/other-utils#handling-event-on-a-dom-event-handler

### Flavour

None

### Areas

Plugins (quasar)
* (I could not find a "utils area")

**Comment by rstoenescu** [comment]
Hi,

I guess you're right. Moved it to the DOM utils page.
