### ISSUE TITLE
[Request] use an icon for `action > label` in Notify

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1698]
Just like the old Toast I want to add the `close` material icon as the handler to dismiss a **Notify** dialogue.

Tried cheating with the following, but it didn't work. : D

    actions: [{
      label: '<i aria-hidden="true" class="q-icon material-icons">close</i>',
    }]

Can you add the possibility to do this?

**Comment by rstoenescu** [comment]
Taken from docs. Do you notice the "icon" there? :)

![download](https://user-images.githubusercontent.com/4665641/36980315-a16501ce-2092-11e8-8495-5284dd381897.png)

**Comment by mesqueeb** [comment]
I meant as the label of the `action`.

**Comment by rstoenescu** [comment]
`{ label: 'Snooze', icon: 'map', handler () {} }`

**Comment by mesqueeb** [comment]
@rstoenescu Oh, I see it's possible to use `icon` in the `actions` as well. I'll edit the docs.

**Comment by mesqueeb** [comment]
I meant: `actions: [{icon: 'close'}]`

**Comment by rstoenescu** [comment]
Updated docs. Thanks for wanting to, though!
