### ISSUE TITLE
[CSS bug] blue :focus on Notify `actions: [{icon: 'close'}]`

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1700]
steps to reproduce:
```js
Notify({message:'blabla', actions: [{ icon: 'close' }]})
```
then click the icon → it will get a blue focus.

**Comment by rstoenescu** [comment]
Hi, This is normal for any button. It needs to get a highlight for accessibility purposes aka know where the focus is. This only applies to desktop.
