### ISSUE TITLE
UMD v2.15.1 does not include useInterval

### ISSUE THREAD

**Issue by webgoto** [quasarframework/quasar#17021]
### What happened?

Quasar.useInterval does not exist.
I was able to use Quasar.useTimeout.

useInterval is missing in https://cdn.jsdelivr.net/npm/quasar@2.15.1/dist/quasar.umd.prod.js

### What did you expect to happen?

useInterval exists in Quasar method

### Reproduction URL

https://plnkr.co/edit/5sXGeo0TvkKAJGcA

### How to reproduce?

use Quasar.useInterval

### Flavour

UMD

### Areas

Composables (quasar)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.15.2
