### ISSUE TITLE
$q.platform.is for Edge on windows desktop is wrong

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#17039]
### What happened?

The field for Edge browser is 'edg'.

### What did you expect to happen?

the field should be 'edge'.

### Reproduction URL

https://jsfiddle.net/yarkwnL0/5/

### How to reproduce?

Open the reproduction link in the Edge browser on windows11 desktop, and then click on the "Is Edge?" button.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Plugins (quasar)

**Comment by bigradish** [comment]
On Android, the field is "edge".

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.15.2
