### ISSUE TITLE
[BUG] Page Sticky not generating correct css

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1704]
There is a bug where you add something as Page Sticky, eg.:
```html
<q-page-sticky corner="bottom-left" :offset="[18, 15]">
      something
</q-page-sticky>
```
And you do `Quasar dev`. It shows up correct the first time.

Then you change `bottom-left` to `bottom-right` and the page reloads, but the QPage Sticky won't move to the other side correctly. It'll stay at the initial values.

tested on fresh install

**Comment by rstoenescu** [comment]
Hi, It's not "corner", but "position".
