### ISSUE TITLE
QUploader hide-upload-btn prop

### ISSUE THREAD

**Issue by cirolosapio** [quasarframework/quasar#17049]
### What happened?

using `hide-upload-btn` prop the button is still visible

### What did you expect to happen?

the upload button should disappear

### Reproduction URL

https://stackblitz.com/edit/quasarframework-issue-17049

### How to reproduce?

1. open reprodution
2. see

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
Without the prop (the upload button is visible)
![image](https://github.com/quasarframework/quasar/assets/6266078/a8734554-c948-44f0-8050-3e9dd6497491)
With the prop (the upload button is not there)
![image](https://github.com/quasarframework/quasar/assets/6266078/1c76d5dc-c49d-4214-85a8-d9ceb4bdb9d8)

If you want to hide the "add files" button instead, your best bet is to use the `readonly` prop.
