### ISSUE TITLE
[Bug] QInnerLoading doesn't cover what is below it properly

### ISSUE THREAD

**Issue by kpwbo** [quasarframework/quasar#1705]
Hello! :)

### Software version

Quasar: 0.15.6
Browsers: Google Chrome 64.0

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/d46cygr8/14/

### What did you get as the error?
The background introduced by a visible QInnerLoading isn't above all the elements that it is supposed to be above. For example, in the JsFiddle above, even if the QInnerLoading is visible, we can successfully click on one of the two buttons, but not on the other one. Note that the QInnerLoading is between the two buttons in the template. This is probably a z-index issue. Possibly related but already closed issue: https://github.com/quasarframework/quasar/issues/944

### What were you expecting?
The background should cover the whole section it is supposed to cover in a way that doesn't make it possible to interact with the elements in that section.

### What steps did you take, to get the error?
Simply added a QInnerLoading in a template.

**Comment by rstoenescu** [comment]
https://jsfiddle.net/moug607z/1/

-- Put QInnerLoading, or QPageSticky as last elements. It's just how CSS works.
