### ISSUE TITLE
[Request] FAB extra parameter requests

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1706]
### 1. FAB tooltip visibility control

The ability to have the q-tooltip inside a FAB show only when the FAB is closed, but have an icon for closing. e.g. `hide-on-active` in the q-tooltip.
Note the `icon="none"` only when the FAB is closed.

```html 
<q-fab
  color="primary" dense
  icon="none"
  active-icon="close"
>
  <q-tooltip
    slot="tooltip"
    hide-on-active
  >
    Tooltip in FAB
  </q-tooltip>
```

### 2. FAB size and dense control

I would love the options `dense` and `size` on the FAB main button.
Currently I use a FAB left and a regular sticky button right. The right button is `dense` and `lg`. The FAB's slight difference in appearance/size is really ugly compared to the sticky button:

<img width="406" alt="2018-03-06 15 47 48" src="https://user-images.githubusercontent.com/3253920/37017927-c510cda6-2155-11e8-973f-41979fad9c22.png">

### 3. FAB auto close

Currently:
1. Auto closes on pressing an action.
2. Doesn't close upon clicking anywhere else on the screen.

My request:  (the oposite)
1. Auto closes on pressing anywhere on the screen.
2. Doesn't close upon clicking an action.

Maybe it can also be added as parameters to make the life easy for all Quasar developers. : )

e.g. _default_: `auto-close="action"`
for only auto close on _screen tap_: `auto-close="screen"`
for auto close on both action _and_ screen tap: `:auto-close="['action', 'screen']"` or `auto-close="always"`

**Comment by olegvakulenko** [comment]
https://github.com/quasarframework/quasar/issues/1649

**Comment by mesqueeb** [comment]
@olegvakulenko I understand Quasar doesn't want to bloat the app, but there at least has to be a method to disable the default functionality that closes the FAB:
> Note
Clicking on a QFabAction will automatically close the list of sub-actions and return the FAB to its original state.

I can't figure out how to change this without messing with the Quasar source code...

**Comment by HarisHashim** [comment]
Just to chime in about size. At least there should be workaround using style. Or maybe I did not get it right?

Tried this

```<q-fab style="width:24px; height:24px" class="q-mr-md" color="primary" icon="show_chart" direction="left">```

Resulting to this:

![image](https://user-images.githubusercontent.com/1856131/40908459-5e6d7e86-6819-11e8-902e-a7567a54c300.png)

Appreciate any advise.

**Comment by pdanpdan** [comment]
1. For tooltip control on QFab show/hide you can hook to `@show` and `@hide` and toggle a visibility controlling variable for the tooltip
2. QBtn has 2 props: `fab` and `fab-mini` that generates round buttons the same size as the QFab (or a small version in case of mini)

**Comment by thexeos** [comment]
If you want to have auto-close with QFab, similar to QMenu's auto-close, you can either patch the QFab.vue file directly (my choice of preference), or you can import the directive from [ui/src/components/menu/ClickOutside.js](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/menu/ClickOutside.js) and use it in your parent component (the one that contains QFab). You can see the usage example here:

https://github.com/quasarframework/quasar/blob/a94e3442a9960650cbf8c9fa86ddee46799c5e91/ui/src/components/menu/QMenu.js#L321-L325

Note: if you choose to do this, make sure you check every release for changes to ClickOutside.js file before upgrading.
