### ISSUE TITLE
electron build warning...

### ISSUE THREAD

**Issue by Gregory-Han** [quasarframework/quasar#17063]
### What happened?

Build mode............. electron
 Pkg quasar............. v2.15.2
 Pkg @quasar/app-vite... v1.8.0
 Pkg vite............... v2.9.17
 Debugging.............. no
 Publishing............. no

 App •  WAIT  • Compiling of Electron UI with Vite in progress...
warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-640a320c] {
        │      ^
        ╵      :

warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :

▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:8:5:
      8 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
 App •  DONE  • Electron UI compiled with success • 19651ms

 App •  WAIT  • Compiling of Electron Main with Esbuild in progress...
 App •  DONE  • Electron Main compiled with success • 55ms

 App •  WAIT  • Compiling of Electron Preload with Esbuild in progress...
 App •  DONE  • Electron Preload compiled with success • 7ms

 UI files build summary:

### What did you expect to happen?

I want to remove warning about css and chunk sizes.

### Reproduction URL

None

### How to reproduce?

quasar build -m electron

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode, Electron Mode

### Platforms/Browsers

Chrome, Electron

### Quasar info output

```Shell
"quasar build -m electron
Build mode............. electron
 Pkg quasar............. v2.15.2
 Pkg @quasar/app-vite... v1.8.0
 Pkg vite............... v2.9.17
 Debugging.............. no
 Publishing............. no

 App •  WAIT  • Compiling of Electron UI with Vite in progress...
warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-640a320c] {
        │      ^
        ╵      :


warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :


▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:8:5:
      8 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :



(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
 App •  DONE  • Electron UI compiled with success • 19651ms

 App •  WAIT  • Compiling of Electron Main with Esbuild in progress...
 App •  DONE  • Electron Main compiled with success • 55ms

 App •  WAIT  • Compiling of Electron Preload with Esbuild in progress...
 App •  DONE  • Electron Preload compiled with success • 7ms

 UI files build summary:
```

### Relevant log output

```Shell
Build mode............. electron
 Pkg quasar............. v2.15.2
 Pkg @quasar/app-vite... v1.8.0
 Pkg vite............... v2.9.17
 Debugging.............. no
 Publishing............. no

 App •  WAIT  • Compiling of Electron UI with Vite in progress...
warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-640a320c] {
        │      ^
        ╵      :


warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :


▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:8:5:
      8 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :



(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
 App •  DONE  • Electron UI compiled with success • 19651ms

 App •  WAIT  • Compiling of Electron Main with Esbuild in progress...
 App •  DONE  • Electron Main compiled with success • 55ms

 App •  WAIT  • Compiling of Electron Preload with Esbuild in progress...
 App •  DONE  • Electron Preload compiled with success • 7ms

 UI files build summary:
```

### Additional context

Build mode............. electron
 Pkg quasar............. v2.15.2
 Pkg @quasar/app-vite... v1.8.0
 Pkg vite............... v2.9.17
 Debugging.............. no
 Publishing............. no

 App •  WAIT  • Compiling of Electron UI with Vite in progress...
warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-640a320c] {
        │      ^
        ╵      :

warnings when minifying css:
▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:3:5:
      3 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :

▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:8:5:
      8 │ tbody > tr[data-v-b4babdb2] {
        │      ^
        ╵      :

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
 App •  DONE  • Electron UI compiled with success • 19651ms

 App •  WAIT  • Compiling of Electron Main with Esbuild in progress...
 App •  DONE  • Electron Main compiled with success • 55ms

 App •  WAIT  • Compiling of Electron Preload with Esbuild in progress...
 App •  DONE  • Electron Preload compiled with success • 7ms

 UI files build summary:

**Comment by rstoenescu** [comment]
Regarding the chunk size, there is literally an example with this on the "Handling Vite config" page. https://quasar.dev/quasar-cli-vite/handling-vite#updating-vite-config

Regarding the other issue with CSS, please provide a reproduction repo/sandbox so that we can help you. Will reopen after reproduction is supplied.
