### ISSUE TITLE
[Feature request] Remote preset for Vue CLI 3

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1707]
Since the release of `Vue CLI 3` is [almost here](https://twitter.com/youyuxi/status/970747808784449538), I think it would be awesome if quasar provides a preset so we can stick to `vue cli` as much as we can (in favor of the vue and quasar learning curves).

https://github.com/vuejs/vue-cli/blob/dev/docs/cli.md#remote-presets

Probably this can be the successor of `quasar-cli` in a upcoming version?

**Comment by lbssousa** [comment]
As @rstoenescu has pointed [here](http://forum.quasar-framework.org/topic/1916/vue-cli-3-0-and-the-future-of-quasar-cli/6), both vue-cli and quasar-cli have completely different approaches, so it's unlikely that quasar-cli will evolve to an extension for vue-cli 3. Nevertheless, the later, when it's released, will share much more concepts and functionalities with quasar-cli than current vue-cli 2, so we'll be always tempted to ask if they could merge in the future.

**Comment by Frondor** [comment]
@lbssousa thanks for pointing that discussion up, I wasn't aware of it.
Still, I strongly believe its not a matter of misconceiving this framework's cli, but rather "not embracing" the tools that vue-cli 3 has brought, to make things easier to implement and/or extend.
We can still use webpack for electron, cordova, PWA, SPA, etc...
Not a single piece of functionality is lost by applying current quasar-cli functionality into a vue-cli 3 preset. And in my humble opinion, you're gaining a lot from letting your users stick with what they learned from vue docs and courses.

Quoting Vinkman reply:

> It concerns me that I’m writing a Quasar app instead of an Vue app, as I might want to include some vue cli 3 plugin in the future, which I cannot do when using the Quasar CLI. It isn’t unreasonable to think there might be usefull plugins released that way. It’s a way of futureproofing our work here, because in the end, we’re developing a Vue application.

**Comment by mstaack** [comment]
@Frondor quasar-cli does a lot more in the background as razvan stated on the forum.
So there is just no real need to upgrade & dump everything just for vue-cli.
quasar-cli also uses vue-cli in the background, so this is not a really important/needed change.

**Comment by Frondor** [comment]
I close this in favor of the current discussion in forums, you'll find my reply there
http://forum.quasar-framework.org/topic/1916/vue-cli-3-0-and-the-future-of-quasar-cli/15
