### ISSUE TITLE
Wrong vue-tsc version in app-vite upgrade guide

### ISSUE THREAD

**Issue by w0pp** [quasarframework/quasar#17089]
### Description

The upgrade guide mentions you should add `vue-tsc@^1.0.0`, but if you do that, you get an error after starting `quasar dev`, because `vue-tsc/out/index` is not found. I'm guessing that module was added in a later vue-tsc version.
The docs should probably say you should add `vue-tsc@^1.8.22`, the same version that you get when you use `yarn create quasar`.

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/upgrade-guide#typescript-projects-linting

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

The caret character means "latest semver compatible version" -- which is whatever last v1 version is available. But fine, I will change docs.

**Comment by rstoenescu** [comment]
Will be available on next docs deployment.

**Comment by w0pp** [comment]
> Hi,
> 
> The caret character means "latest semver compatible version" -- which is whatever last v1 version is available. But fine, I will change docs.

Thanks for the clarification. It looks like the issue was actually with Yarn on Windows requiring quotes around the version: yarnpkg/yarn#3270.
