### ISSUE TITLE
0.15.6 IE11/Edge input textarea does not position correctly

### ISSUE THREAD

**Issue by MitchellMonaghan** [quasarframework/quasar#1710]
Was testing web browser compatibility, and noticed the text area is messed up on IE11/Edge. I have prepared a jsfiddle for you to view the issue. For some reason the jsfiddle only works with edge. Doesn't seem to work with ie11 at all. In my production site both browsers have the same issue that you will see when viewing the jsfiddle with edge. Thanks!

Quasar: 0.15.6
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: IE11/Edge

https://jsfiddle.net/h2m0anhx/

**Comment by pdanpdan** [comment]
I think you're not using the IE specific tweaks, as specified here:
http://quasar-framework.org/guide/app-supporting-ie.html

**Comment by rstoenescu** [comment]
Available in 0.15.7

**Comment by MitchellMonaghan** [comment]
Hey guys, saw that you just released 0.15.7. Updated to the new version to see this issue fixed, and the border issue is fixed but if you click in the field and start typing it still has the same issue. The text you type goes in the wrong place just like how it was before. Cleared my cache/ tested dev vs prod. IE is the worst!
