### ISSUE TITLE
Safari version number changed to build number

### ISSUE THREAD

**Issue by mstroeve** [quasarframework/quasar#17111]
### What happened?

We updated Quasar V2 (previous was approx. 2 months ago) but the browser.version is giving different results. 
It used to give a safari version like 17.3 but now its returning a weird (webkit? ) version number instead.

This screenshot below is from a mac device accessing: https://quasar.dev/options/platform-detection

![Scherm­afbeelding 2024-04-15 om 21 43 16](https://github.com/quasarframework/quasar/assets/13969254/2941d4d5-414a-402d-9f1b-78316d357da4)

### What did you expect to happen?

Show the actual safari version number like 17.5

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

Visit https://quasar.dev/options/platform-detection using a macOS/iOS device

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Safari, iOS

**Comment by rstoenescu** [comment]
Nothing changed in Quasar in regards to the version detection, but the UserAgent string changed in Safari itself. Regardless, fix is coming.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.15.3

**Comment by mstroeve** [comment]
Thanks for the quick fix, made a donation. 
We are looking into options for supporting the project in long term.
