### ISSUE TITLE
Error when running quasar build

### ISSUE THREAD

**Issue by syntacticsolutions** [quasarframework/quasar#1712]
I'm running ```quasar build``` with the original configs and this is what I get.

Note: I'm using quasar v0.14

this is the debug log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle quasar-app@0.0.1~prebuild: quasar-app@0.0.1
6 info lifecycle quasar-app@0.0.1~build: quasar-app@0.0.1
7 verbose lifecycle quasar-app@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle quasar-app@0.0.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/miguelcabrera/Apparition/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle quasar-app@0.0.1~build: CWD: /Users/miguelcabrera/Apparition
10 silly lifecycle quasar-app@0.0.1~build: Args: [ '-c', 'node build/script.build.js' ]
11 silly lifecycle quasar-app@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle quasar-app@0.0.1~build: Failed to exec build script
13 verbose stack Error: quasar-app@0.0.1 build: `node build/script.build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid quasar-app@0.0.1
15 verbose cwd /Users/miguelcabrera/Apparition
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error quasar-app@0.0.1 build: `node build/script.build.js`
22 error Exit status 1
23 error Failed at the quasar-app@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

ERROR in js/0.4612483b63a209060f31.js from UglifyJs
Unexpected token: operator (>) [js/0.4612483b63a209060f31.js:3180,32]

**Comment by syntacticsolutions** [comment]
If I take out UglifyJS it works

**Comment by pdanpdan** [comment]
UglifyJs does not support ES6. You either can not use uglify at all or change it to a newer version that supports ES6. But considering that 0.15 was released with new cli that manages webpack config I think you should consider upgrading.

**Comment by rstoenescu** [comment]
Hi, Either replace webpack's own uglifyjs with `uglifyjs-webpack-plugin` or upgrade to 0.15.

**Comment by syntacticsolutions** [comment]
Also if you comment out the ```exclude: '/node_modules/' ```in the webpack config it will work.

**Comment by rstoenescu** [comment]
What this means is that some package that you are importing is not built right. It supplies ES6 code instead of ES5. I'd investigate which package is that and look over its docs to make sure it's being used right... even log them a bug to fix their distributables.
Adding "node_modules" to babel-loader processing may increase the build time considerably.
