### ISSUE TITLE
[BUG] `@change` doesn't work on q-option-group

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1713]
`@change` doesn't work on `<q-option-group>`

Tested on a new build. Please see the pen:
https://codepen.io/mesqueeb/pen/rJXzPO

@change doesn't work.
@input works.

This change was breaking for my app.
I have changed all `@change` to `@input`.
Is there a big difference between the two?

**Comment by pdanpdan** [comment]
http://quasar-framework.org/guide/quasar-upgrade-guide.html#Form-Components

**Comment by mesqueeb** [comment]
@pdanpdan 
What does this sentence mean?
> @change for lazy update. Vue v-model.lazy support is a pending change, so until then you can use the equivalent form (details below).

**Comment by pdanpdan** [comment]
It means that there is a PR in Vue for implementing lazy modifier for v-model on custom components, but it's not yet merged.

**Comment by mesqueeb** [comment]
will the lazy modifier have a different effect than `@input` has?
Is lazy e.g. run at a different timing when the v-model changes?

**Comment by pdanpdan** [comment]
@input event is emitted each time some interaction is performed on the control (even if it's not changing the model). If you use v-model then on each @input the value of the model is changed.
@change event is emitted only when the control changes are considered done (let's simplify and consider on blur) AND when the internal model of the control is different from the external model.
So if you use v-model your internal and external models are always in sync, so no @change is emitted.
If you use `:value="model" @change="val => { model = val; do_something_with(val)}"` then you'll have @change events.

**Comment by OngBona** [comment]
<td class="td">
                    <q-input
                        :value="item.price"
                        @change="val =>
                            { 
                            item.price = val;
                            item.amount=item.qty*item.price
                            }"
                        type="text" />
                </td>
                
                <td class="td">
                    amount= {{item.amount}}
                </td>

**Comment by OngBona** [comment]
```  <td class="td">
                    <q-input
                        :value="item.price"
                        @change="val =>
                            { 
                            item.price = val;
                            item.amount=item.qty*item.price
                            }"
                        type="text" />
                </td>
                <!-- {{item.price}} -->
                <td class="td">
                    amount= {{item.amount}}
                </td>```
