### ISSUE TITLE
unplugin-auto-import no longer working

### ISSUE THREAD

**Issue by Karnith** [quasarframework/quasar#17132]
### What happened?

In previous version of quasar v2 unplugin-auto-import worked and provided imports via d.ts file. Now unplugin-auto-import does not work with quasar, it seems that environment variables get wiped when this plugin is added to vite plugins. Using server: false and client: false do not fix the issue either. When client: false is added, the plugin no longer creates and adds the d.ts file.

This happens in the latest version of quasar cli SPA app and the new beta vite app.

### What did you expect to happen?

It is expected that the vite plugin unplugin-auto-import generates and adds the auto imports into a quasar project.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-5qaesd?file=README.md

### How to reproduce?

1. Create quasar vite app
2. install unplugin-auto-import
3. add unplugin-auto-import to vite plugins
4. app is now broken as environment variables no longer are created

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

You are incorrectly configuring unplugin-auto-import.
Remove `process: [['*', 'process']],` from there.
