### ISSUE TITLE
npm install error: node-waf: command not found (due to zlib dependency) 

### ISSUE THREAD

**Issue by amc1999** [quasarframework/quasar#17157]
### What happened?

Npm install failed on freshly created Quasar v1 CLI project due to [package.json](https://github.com/quasarframework/quasar/blob/v1/app/package.json) dependencies zlib 1.0.5 at line 121.
```
npm error path ........\quasar-project\node_modules\zlib
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-waf clean || true; node-waf configure build
npm error 'node-waf' is not recognized as an internal or external command,
```

That issue was already fixed at least once, merged in by [rstoenescu](https://github.com/rstoenescu), on July 5, 2021 [refactor(app): Remove deprecated zlib package to use from Node.js core (fix: #9942) #9951](https://github.com/quasarframework/quasar/pull/9951)

To fix it again we need to remove "zlib": "1.0.5" on line 121 of [package.json](https://github.com/quasarframework/quasar/blob/v1/app/package.json)

Do you want PR for that?

### What did you expect to happen?

npm install OK

URL below is not a Reproduction URL which required by GitHub bot.
It is a fork with issue fix and PR.
I don't know how reproduce npm install error using Codepen, jsFiddle, etc.

### Reproduction URL

https://github.com/amc1999/quasar

### How to reproduce?

Reproducible at last stable node v20.12.x or higher, tested today using node v22.1.0
```
npm install -g @quasar/cli
npm init quasar
cd quasar-project
npm install
```

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

### Relevant log output

```Shell
npm error code 1
npm error path ........quasar-project\node_modules\zlib
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-waf clean || true; node-waf configure build
npm error 'node-waf' is not recognized as an internal or external command,
```

**Comment by rstoenescu** [comment]
Hi,

Thank you for also providing a PR, however:
* Quasar v1 is out of support for a long time now.
* The fix that you mentioned was meant for Quasar v2 projects. The v1 q/app was never fixed because it is out of support.

However, since you took the effort to provide a PR, I did a quick release for it (`@quasar/app` v2.4.4)
