### ISSUE TITLE
QTable: No data available problem

### ISSUE THREAD

**Issue by jolee11** [quasarframework/quasar#1715]
Assuming you have rowsPerPage set to 10, and currently you have 11 records.

Then, page 1 will have 10 records shown and page 2 will have 1 record shown.
Now, switch to page 2 and we can see one record normally.

If we select the record in page 2 and click a [delete selected record button] 
to dynamically remove the record in page 2,
"No data available" will immediately shown at the bottom of page 2.

I think, the normal behaviour should be automatically switch back to previous page
or next page because actually there are 10 records on page 1.
 
Thank you very much!

**Comment by pdanpdan** [comment]
It's working exactly like this. What version are you using? It was fixed in 0.15.3

**Comment by jolee11** [comment]
Oh! I am so sorry! I am using 0.15.1 ! 
I definitely need to upgrade it!

Thank you very much!
