### ISSUE TITLE
[Feature request] QStepper - flag to disable navigation through header

### ISSUE THREAD

**Issue by Miosss** [quasarframework/quasar#1716]
QStepper is nice component to create wizard-like pages, but it allows users to go to previous steps by clicking on step names in the header. This is a bit inconsistent, because there is no way to go to further steps that way.
Therefore, it is required to use QStepperNavigation with buttons that implement ref.next() / ref.previous().

In some scenarios though, it may be inapriopriate to allow users to go back for some reason - for example, one step commits some transaction and the last step is used for summary - at this point it is very unwanted for the user to have ability to go back. And for each use case, there is still option for using ref.previous().

Current situation - in which user can click on "completed" steps - is a nice feature. To not remove it nor make any breaking decision, I would propose intoducing flag to control this behaviour and to use it like this:

`<q-stepper :header-nagivation="false" />`

(default true to preserve current state)

When the flag is set to false, navigation through header is disabled - cursor is not styled as "pointer" and no onclick action is performed.

**Comment by rstoenescu** [comment]
Available through `no-header-navigation` Boolean prop in 0.15.7
