### ISSUE TITLE
Convert project to Quasar CLI with Vite - no mention of how to handle the package.json file.

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#17176]
### Description

Hi, 

I am looking at this page trying to migrate to vite and there is no mention on how to handle the package.json file. 

Thanks

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite/

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

Follow the instructions and spawn a new project folder then migrate from there. If you insist on using the same project, you could take a look at the package.json from a newly spawned project folder with q/app-vite.
