### ISSUE TITLE
Click on Qfield with a button in the slot after is triggering this one and it shouldn't

### ISSUE THREAD

**Issue by kevingermain** [quasarframework/quasar#17177]
### What happened?

Everything is in the title, the click on the field with an after slot and button inside is trigger the click and it shouldn't: 

You can check with field with an arrow icon on the right
https://quasar.dev/vue-components/field#standard

### What did you expect to happen?

not triggering the button

### Reproduction URL

https://quasar.dev/vue-components/field#standard

### How to reproduce?

Everything is in the title, the click on the field with an after slot and button inside is trigger the click and it shouldn't: 

You can check with field with an arrow icon on the right
https://quasar.dev/vue-components/field#standard

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

It is unclear what exactly you are reporting. Please make a codepen. Show exactly what is triggered (and how).

**Comment by kevingermain** [comment]
Check this input in Qfield Component page, click on it, the ripple is active on the button in the slot after (icon navigation): 
![image](https://github.com/quasarframework/quasar/assets/1334099/de615313-2fa4-4645-9142-b9e96aa135f0)

Go to Qinput for the same field, the behavior is not the same.

I got this regression without touching my code

**Comment by rstoenescu** [comment]
When you say the behaviour is not the same, what exactly are you referring to?
They seem the same for me.

Can we connect on Discord pls to speed this up, please?

**Comment by rstoenescu** [comment]
Wait. I think I see what you mean.

**Comment by rstoenescu** [comment]
What Quasar version have you upgraded from?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.16.2
