### ISSUE TITLE
I can't signup to quasar forum

### ISSUE THREAD

**Issue by Abdelaziz18003** [quasarframework/quasar#1717]
I can't signup to quasar forum. I tried with different emails and different usernames and I am getting the same error always. I did my first try to signup before a month ago and the problem is still persisting.

### What did you get as the error?
![screenshot-2018-3-7 quasar framework](https://user-images.githubusercontent.com/11301627/37095849-50fc4bbc-2217-11e8-99ff-d0c8dbd0bc58.png)

### What were you expecting?
I am expecting a successful signup

### What steps did you take, to get the error?
Just filling up the signup form

**Comment by mstaack** [comment]
hmm weird..can you send me your email on discord? i will create your account manually.

thx

**Comment by mstaack** [comment]
@Abdelaziz18003 created your account and send you an email!
