### ISSUE TITLE
0.15.6 IE11 q-table rows per page control does not show select option text

### ISSUE THREAD

**Issue by MitchellMonaghan** [quasarframework/quasar#1718]
Was testing web browser compatibility, and noticed the rows per page control on the q-table is messed up on IE11. The button icon over laps some of the text and when clicked none of the option text is visible. Edge only has the icon over lap issue which is very minor. This issue can be viewed here:

http://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/table/table-features

Quasar: 0.15.6
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: IE11

I attempted to create a jsfiddle but I cant seem to get the UMD version to work with IE11 at all. I attempted to set Quasar.supportIE = true on the global object but that didn't have any impact. Can we update the jsfiddle/codepen bug templates to support ie? I hope the link I provided is sufficient to reproduce the issue.

Thanks

**Comment by rstoenescu** [comment]
Available in 0.15.7
