### ISSUE TITLE
quasar.dev does not work in Kazakhstan

### ISSUE THREAD

**Issue by krop24** [quasarframework/quasar#17182]
### Description

![image](https://github.com/quasarframework/quasar/assets/106395139/535c4cc4-dfa2-4325-9ffb-a30bdf0cb2c3)
https://quasar.dev/ - does not work in Kazakhstan. Permanent error ERR_TIMED_OUT. The Internet works, I tried the Internet working from different Internet providers, devices did not help

### Documentation Section URL

https://quasar.dev

### Flavour

None

### Areas

Components (quasar), Directives (quasar), Plugins (quasar), Composables (quasar), Style & Identity (quasar)

**Comment by wanderowski** [comment]
I faced the same issue

**Comment by yusufkandemir** [comment]
I don't see any clear reason why they would block our site. Please let us know if it's possible for you or us to contact the government to re-evaluate their decision.

I have found this:
https://kazbt.com/blog/blocked-list.html
![image](https://github.com/quasarframework/quasar/assets/6266078/52d278bd-25a5-48aa-bccf-56ceacb56e5f)

> It is worth considering that after [amendments](http://online.zakon.kz/Document/?doc_id=1049207#pos=1049;-160) were made to the Law “On Communications” in 2015, the Prosecutor General’s Office and the State Control Committee in the field of communications, information and media can block sites without a court decision.
> 
> The website of the same ministry states that the new Communications Committee blocks Internet resources that disseminate information that violates the legislation of the Republic of Kazakhstan, including:
> 
> - Publication of materials and dissemination of information aimed at inciting interethnic and interfaith hatred
> - Propaganda or agitation of the cult of cruelty and violence, social, racial, national, religious, class and clan superiority
> - Propaganda of extremism or terrorism
> - Conducting election campaigning
> - Violation of the integrity of the Republic of Kazakhstan
> - Propaganda or agitation for a violent change of the constitutional order
> - Demonstration of film and video products of a pornographic and special sexual-erotic nature
> - Propaganda of narcotic drugs, psychotropic substances, their analogues and precursors
> - Unfair, false advertising
> - Suicide propaganda
> - Online casino
> - Other

**Comment by darakanoit** [comment]
I have resolved this issue with government agencies, access has been restored, please check.
