### ISSUE TITLE
Using meta tags in SPA mode

### ISSUE THREAD

**Issue by ShlomoCode** [quasarframework/quasar#17185]
### Description

There is a discrepancy in the documents...

quote from https://quasar.dev/options/seo:
>It doesn’t quite make sense to use it for SPA (Single Page Applications) since the meta information in this case will be added at run-time and not supplied directly by the webserver (as on SSR builds).

quote from https://quasar.dev/quasar-plugins/meta:
>It also makes sense to use it for SPA (Single Page Applications). Although the meta information in this case will be added at run-time and not supplied directly by the webserver (as on SSR builds), modern web-crawlers like the Googlebot will render dynamic pages and extract out the dynamically set meta information.

### Documentation Section URL

https://quasar.dev/quasar-plugins/meta, https://quasar.dev/options/seo

### Flavour

None

### Areas

Plugins (quasar)

**Comment by rstoenescu** [comment]
Thanks for pointing this out. Fix will be available on next deployment.
