### ISSUE TITLE
Table component errors out when prop rows is null

### ISSUE THREAD

**Issue by gauravjhs** [quasarframework/quasar#17213]
### What happened?

Create a table and pass rows props as null.
Component crashes and error log is displayed on console.
Cannot read properties of undefined (reading 'length'). 
This works if we pass blank array

### What did you expect to happen?

Null or Empty Array should behave exactly the same showing a blank table

### Reproduction URL

https://codepen.io/gaurav-jhs04/pen/jOoWjbo

### How to reproduce?

Go to the above codepen link. See console.

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Relevant log output

```Shell
vue.global.prod.js:7  TypeError: Cannot read properties of undefined (reading 'length')
    at quasar.umd.prod.js:17:203046
    at ue.fn (vue.global.prod.js:7:14050)
    at ue.run (vue.global.prod.js:7:6593)
    at get value (vue.global.prod.js:7:14297)
    at quasar.umd.prod.js:17:203236
    at ue.fn (vue.global.prod.js:7:14050)
    at ue.run (vue.global.prod.js:7:6593)
    at get value (vue.global.prod.js:7:14297)
    at quasar.umd.prod.js:17:197065
    at ue.fn (vue.global.prod.js:7:14050)
```

**Comment by tegaologe** [comment]
i have the exact problem

**Comment by yusufkandemir** [comment]
It's a required/non-nullable prop. So, that is the expected behavior. You should use an empty array. You can do so by doing this `:rows="nullableResult ?? []"` if you can't handle it anywhere else.
