### ISSUE TITLE
removing all webfont icons results in a lot of missing standard icons in quasar. 

### ISSUE THREAD

**Issue by yeus** [quasarframework/quasar#17247]
### What happened?

I am removed all webfont font packages from my quasar.conf.js in order to speed up my app.  But this resulted in a lot of missing  icons in
the standard components. E.g. arrows for dropdowns, the clearable icon. The sorting icons in q-table etc... 

### What did you expect to happen?

When removing webfont icons, quasar should use their svg equivalents.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-jh7u75?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. go to quasar.conf.js
2. remove all icons packages from "extras"
3. compile into webpage

--> now all icons are missing

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron, Other

### Quasar info output

```Shell
Operating System - Linux(6.1.91) - linux/x64
NodeJs - 21.6.2

Global packages
  NPM - 10.2.4
  yarn - 1.22.19
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.12.3 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.19 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.3.0
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  electron - 17.4.11 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.23.9 -- Babel compiler core.
  webpack - 5.90.3 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 7.0.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 3.0.0-beta.7 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing-e2e-cypress - 6.1.0 -- A Quasar App Extension for Cypress e2e
  quasar-app-extension-ssg - 5.2.0 -- Static Site Generator App Extension for Quasar.

Networking
  Host - tomtuxedo
  wlp1s0 - 192.168.188.111
```

### Additional context

removing webfont icons really make sense, if you want to speed up your app for mobile devices...

**Comment by yeus** [comment]
specifically the icons from q-table are also very hard to change.   I don't know how to exchange the sort icon from it...

**Comment by yusufkandemir** [comment]
You should set the `iconSet` to an SVG variant. See https://quasar.dev/options/quasar-icon-sets#quasar-cli-way
Example:
```js
// quasar.config file
framework: {
  // svg-based example
  iconSet: 'svg-mdi-v7'
}
```

Also, `QTable`'s sort icon's icon set key is `table.arrowUp`. Example: https://github.com/quasarframework/quasar/blob/0cd5f34dd1b206976b8776f790a4c03cae4360f2/ui/icon-set/svg-mdi-v7.js#L205-L206

**Comment by yeus** [comment]
duhhh...   I am so stupid..  only had the documentation for q-icon in front of me:

https://quasar.dev/vue-components/icon#introduction

Thank you @yusufkandemir .
