### ISSUE TITLE
quasar extras ion-icons doesn't work properly for latest v-7 version

### ISSUE THREAD

**Issue by AhmedHamdy-B** [quasarframework/quasar#17252]
### What happened?

can anyone please help me on how to use the latest version of ionicons-v7
whenever I try to add it to my project it shows that the v7 is not available, and I noticed that the ionicons-v7.css is missing in my nodemodules
![image](https://github.com/quasarframework/quasar/assets/56585994/497b1270-d86d-41e3-a141-00895f303e00)

note: I have the latest version of extras:
![image](https://github.com/quasarframework/quasar/assets/56585994/eae67ce9-f4a1-4eca-b704-fcf2f2c4b4df)

thats the error that shows up whenever I try to add v-7 instead of v4 in quasar.config > extras:[
ionicons-v7
]

![image](https://github.com/quasarframework/quasar/assets/56585994/84c52cb3-e7cb-4354-a600-0418d74891e7)
![image](https://github.com/quasarframework/quasar/assets/56585994/83763b6a-fe5e-4942-9be1-ab42710c98b9)

note: some of the icons are working properly and some just doesn't work or appear when I use their names, I think its related to the version of ionicons that is added to the extras, that was my key reason for upgrading it in first place 

  <q-icon color="primary" size="2.2em" name="ion-aperture" />
  <q-icon color="primary" size="2.2em" name="ion-aperture-outline" />
  <q-icon color="primary" size="2.2em" name="ion-arrow-redo" />
  <q-icon color="primary" size="2.2em" name="ion-airplane-outline" />
  <q-icon color="primary" size="2.2em" name="ion-ios-arrow-redo" />

  for example these icons don't all work properly only two or three work and the rest just doesn't show

### What did you expect to happen?

what I expect is to just add ionicons-v7 to my quasar extras without any errors appearing, just as other icon libraries, but it seems that the file ionicons-v7.css is missing for some reason, unlike ionicons-v4 that has all of its files properly

### Reproduction URL

https://codepen.io/AhmedHamdy-B/pen/KKLmxOb

### How to reproduce?

just try to use and icons in the latest ionicons version and most of them wont work as the imported v-7 wont work in extras in quasar.config

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar Extras (@quasar/extras)

### Quasar info output

```Shell
[vite] Internal server error: Failed to resolve import "@quasar/extras/ionicons-v7/ionicons-v7.css" from ".quasar\client-entry.js". Does the file exist?
```

**Comment by yusufkandemir** [comment]
Ionicons v5+ do not have a webfont variant. It only has SVG variants.

https://github.com/quasarframework/quasar/tree/dev/extras
![image](https://github.com/quasarframework/quasar/assets/6266078/43f284c9-3921-413d-856a-e2d2cb04c9f3)

https://quasar.dev/vue-components/icon#ionicons
![image](https://github.com/quasarframework/quasar/assets/6266078/61481cf9-3305-454a-aae3-fb807a79c1d3)

I just pushed a commit to remove contradicting information.

**Comment by AhmedHamdy-B** [comment]
Thank you so much @yusufkandemir, is there a way that I can use these SVG variants in my Quasar app, do we have this available? and how?

**Comment by zhdbk3** [comment]
> Thank you so much [@yusufkandemir](https://github.com/yusufkandemir), is there a way that I can use these SVG variants in my Quasar app, do we have this available? and how?

Yes, there is. Please see https://quasar.dev/vue-components/icon#svg-icons.

Here is a simple example:

```vue
<template>
  <q-icon :name="ionLogoGithub" />
</template>

<script setup>
import { ionLogoGithub } from '@quasar/extras/ionicons-v8';
</script>
```

I hope it is helpful to you!
