### ISSUE TITLE
Installation error: error create-strapi-app@4.15.5: The engine "node" is incompatible

### ISSUE THREAD

**Issue by MrsBookik** [quasarframework/quasar#17256]
### What happened?

When trying to create a new quasar app using the commend:

```yarn global add @quasar/cli```

I get the following error:

```
error create-strapi-app@4.15.5: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "22.2.0"
error Found incompatible module.
```

### What did you expect to happen?

that I can install the application

### Reproduction URL

https://github.com/quasarframework/quasar/issues/new?

### How to reproduce?

1. open the terminal
2. yarn global add @quasar/cli

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Project Creation (create-quasar)

### Platforms/Browsers

Other

### Quasar info output

```Shell
Operating System   	Darwin(23.4.0) - darwin/arm64
NodeJs             	22.2.0

Global packages
  NPM              	10.7.0
  yarn             	1.22.19
```

### Relevant log output

```Shell
❯ yarn global add @quasar/cli
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
⠂ @quasar/cli(node:81100) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2/4] 🚚  Fetching packages...
error create-strapi-app@4.15.5: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "22.2.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by rstoenescu** [comment]
Hi,

We do not use `create-strapi-app` as a dependency.

You could try to install any other package globally and you might stumble upon the same error. This is one of the reasons why we advertise to use only LTS (long-term-support) versions of Node.js. Until v22 becomes LTS, please use Node.js v20.

This error has nothing to do with our global CLI.
