### ISSUE TITLE
vite-plugin incorrectly relies on vite mode

### ISSUE THREAD

**Issue by yurks** [quasarframework/quasar#17267]
### What happened?

`vite build --mode qa` (or any other mode except 'production') produces a bundle with development import of quasar.

<img width="506" alt="image" src="https://github.com/quasarframework/quasar/assets/4581398/5b23c6f2-e9a2-4c65-be28-45f054101d9b">

### What did you expect to happen?

Only `vite` command is used for development and running `vite build` command should produce production bundle for any mode:

<img width="505" alt="image" src="https://github.com/quasarframework/quasar/assets/4581398/5e21fe5d-7cc7-4f3a-a40d-1d55265274d0">

### Reproduction URL

https://github.com/yurks/quasar-vite-issue

### How to reproduce?

1. fork provided repo
2. run `yarn build` to check correct production build
3. run `yarn build:qa` to check incorrect production qa build

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Additional context

Vite [modes](https://vitejs.dev/guide/env-and-mode#modes) is a bit tricky and it's not always obvious that `production` mode is not the same with `NODE_ENV=production`. That means we can run vite build with different modes, but suppose to have production build as a result.

Quasars `vite-plugin` relies on vite mode [here](https://github.com/quasarframework/quasar/blob/dev/vite-plugin/src/plugin.js#L98) and [here](https://github.com/quasarframework/quasar/blob/dev/vite-plugin/src/vite-config.js#L35) which makes impossible to have production build with `vite build --mode qa`, for example. It would be more correct to rely on `build` value of vite env config [command](https://vitejs.dev/config/#conditional-config) property.

**Comment by rstoenescu** [comment]
Hi,

| Vite command | viteConf.command | viteConf.mode |
| --- | --- | --- |
| serve | serve | development |
| build | build | production |
| preview | serve | production | 

If not relying on "mode" then the "vite preview" command will confuse our plugin and produce a hybrid compilation (dev + prod parts combined).

**Comment by yurks** [comment]
@rstoenescu is this fixed somewhere?

// just commented in https://github.com/quasarframework/quasar/pull/17272

**Comment by rstoenescu** [comment]
Let's continue conversation on the PR. I have just noticed the comment there.

**Comment by rstoenescu** [comment]
For anyone landing here: this is now actually fixed on dev by 9097449ed. The plugin decides the build flavor from Vite's resolvedConfig.isProduction (NODE_ENV driven) instead of the mode name, so `vite build --mode qa` (or any custom mode) produces a correctly treeshaken production bundle. Ships with the next @quasar/vite-plugin release. See #17272 for the details.
