### ISSUE TITLE
cannot find module when update quasar version

### ISSUE THREAD

**Issue by mrGhamari** [quasarframework/quasar#17262]
### What happened?

i updated quasar version to 2.16.4 and i cant run my project

### What did you expect to happen?

my project is runned

### Reproduction URL

none URL

### How to reproduce?

install latest version of quasar and run project

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
You didn't provide a reproduction, not even an error message. So, we can't provide any help. All I can recommend is that check the release notes. As written there, ensure `@quasar/app-vite`/`@quasar/app-webpack`/`@quasar/vite-plugin` packages are updated as well.
