### ISSUE TITLE
button group is not responsive

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#1727]
Not a great experience when having a lot of buttons in a button group on mobile. Basically you end up with a horizontal scrolling.

For example QTabs component handles that case in a nicer way.

Here is a fiddle with the example: https://jsfiddle.net/dvxb0axe/9/

**Comment by pdanpdan** [comment]
But what would be the use case for what you tried?  If there are many buttons and long ones you should use something else.

**Comment by BenoitRanque** [comment]
Proposed fix [here](https://github.com/quasarframework/quasar/pull/1749)

**Comment by jean-moldovan** [comment]
Closing this one as I don't know how this should be fixed.
