### ISSUE TITLE
Not really a bug but I think should be addressed

### ISSUE THREAD

**Issue by Erik-Bjerke** [quasarframework/quasar#17290]
### What happened?

It would be nice if you get this sorted

![image](https://github.com/quasarframework/quasar/assets/54407345/f6dedc54-5513-4bdb-b25c-dbedafd7fbcd)

### What did you expect to happen?

I expect to not have the above warning

### Reproduction URL

Irrelevant, yes I read the "don't use this" but this was preventing me from submitting and this is not needed at all in this case.

### How to reproduce?

Start Quasar problem with latest Quasar.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox, Chrome

**Comment by exninja** [comment]
Hi @TheProcedural 

Inflight isn't part of the Quasar installation.
The messages you're seeing are produced by NPM not Quasar.

See the NPM page for the same author's notice: [https://www.npmjs.com/package/inflight](https://www.npmjs.com/package/inflight)

i.e. anyone that uses that module, whether Quasar or not, will see the same npm deprecation / memory leak message.

As an example, here's a StackOverlow link with someone experiencing the same issue with React.
[https://stackoverflow.com/questions/78527247/have-used-npm-create-vitelatest-but-after-finishing-the-compilations-am-getting](https://stackoverflow.com/questions/78527247/have-used-npm-create-vitelatest-but-after-finishing-the-compilations-am-getting)

Solution: You could follow the module author's recommendation and switch to another module.

**Comment by TheProcedural** [comment]
@exninja, workbox is part of the Quasar installation, isn't it?

![image](https://github.com/quasarframework/quasar/assets/54407345/ebb03b28-00eb-4b7c-800e-9c1ed6d8b74e)

**Comment by yusufkandemir** [comment]
workbox-build is peer dependency which you manage yourself in your project. If a new version of workbox-build that addresses this problem gets released, you can update it. You can also patch dependencies or enforce specific versions of nested dependencies yourself. We can't do anything about this from the Quasar CLI side.
https://github.com/quasarframework/quasar/blob/27ce4f8efa9d5f16e7f499e1ab335c8ad16076a6/app-vite/package.json#L99-L110

**Comment by TheProcedural** [comment]
Can you all stop being condescending morons and stop assuming you know best? @exninja was clearly wrong by saying inflight was not part of quasar setup and @yusufkandemir you clearly didn't read the message in which I suggest they "address" the issue with peer dependencies. What make you think I haven't already done this on my project? Holy shit people you really have ego problems.

**Comment by exninja** [comment]
Wow, there are tons of people here who aren't part of the Quasar team and are merely trying to help. Sorry, I was wrong because I didn't delve far enough into the dependencies of a module that is not core Quasar. Maybe you're barking up the wrong tree and should be addressing your frustration at worker-build.  Great representation of your company BTW. Signed. A moron.

**Comment by TheProcedural** [comment]
Barking at those who started the fire, presenting the company exactly how I want to be presented given we only work with hand-picked clients, and thank you very much for the confirmation signature.

**Comment by yusufkandemir** [comment]
> you clearly didn't read the message in which I suggest they "address" the issue with peer dependencies. What makes you think I haven't already done this on my project? Holy shit people you really have ego problems.

I just explained the problem relative to Quasar CLI. You can create an issue in workbox-build to propose a solution, or just wait until they release a fix. In any case, Quasar CLI won't cause a problem when you want to update the dependency as it's not part of the Quasar CLI dependencies, it's a peer dependency.

I didn't assume or state you haven't done anything in your project to address the problem or created an issue. I think you are a bit aggressive or stressful these days or in general. You are being disrespectful for no apparent reason.

**Comment by TheProcedural** [comment]
I'll just make my own Quasar with blackjack and hookers.
