### ISSUE TITLE
QInput with type "date" (<q-input type="date" />) in the standard format "dd/mm/yyyy"

### ISSUE THREAD

**Issue by Matheus-Oberziner** [quasarframework/quasar#17302]
### Description

I'm using QInput and it is defined with the type "date" `<q-input type="date">`, the default date format is "dd/mm/yyyy". However, the year mask ("yyyy") should accept a maximum of 4 characters, but if you do tests, the mask allows you to receive up to 6 characters.

![image](https://github.com/quasarframework/quasar/assets/109804214/e6f53982-f4b0-4865-8124-de6a8da421d0)

This print comes from the official Quasar documentation.

I expect the component to only accept 4 characters when it comes to the year of the date.

### Documentation Section URL

https://quasar.dev/vue-components/input#input-types

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
Please see and interact with the example here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value
It's the native `<input type="date">` behavior.
![image](https://github.com/quasarframework/quasar/assets/6266078/73dd7e3d-290c-4baa-bb90-1c5a1554ef25)

You can use something like `max="2099-12-31"` to alter the behavior. You can also use QDate instead if you want an even more customized experience.

**Comment by yusufkandemir** [comment]
Also, `dd/mm/yyyy` is not a standard. It depends on the browser and user locale. As you can see, it's `dd.mm.yyyy` in my case.

![image](https://github.com/quasarframework/quasar/assets/6266078/9e83096a-f4fa-4918-bcdf-358c8666c970)
