### ISSUE TITLE
BEX chrome extension default content script produces javascript errors

### ISSUE THREAD

**Issue by radiantone** [quasarframework/quasar#17300]
### What happened?

I tried using the default content script that quasar creates for my extension, but it doesn't work at all. First, was this error
```
SyntaxError: Cannot use import statement outside a module (at my-content-script.js:4:1)
then this error
```
then
```
SyntaxError: Unexpected token 'export'
```

### What did you expect to happen?

No errors

### Reproduction URL

https://codepen.io/Darren-G/pen/QWRmNjw

### How to reproduce?

Load a skeleton chrome extension with quasar bex (provided sample) content script

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

BEX Mode

**Comment by rstoenescu** [comment]
Hi,

I've just tested with the q/app-vite v2 beta and it works correctly. 
Please provide more information on what you are doing and a reproduction repo, otherwise there is nothing actionable here. Thanks for understanding.
