### ISSUE TITLE
How to add quasarframework to VueJS

### ISSUE THREAD

**Issue by diepvv** [quasarframework/quasar#1730]
### Software version
Hi everyone. Quasar is a greate framework. 
I have a question . I want add and config quasar to project which is created by Vue CLI. 
Quasar : V0.15.6
Vue CLI : 2.9.3
OS: Win 7
Node: 8.9.4
NPM: 5.6.0
Browsers: Chorme

**Comment by pdanpdan** [comment]
And the question is?

**Comment by laurentpayot** [comment]
@diepvv http://quasar-framework.org/guide/embedding-quasar.html
