### ISSUE TITLE
Website not accessible going straight to a subroute!

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1731]
With the old URI scheme Quasar always had `/#/` as first subroute.
I was happy to see that this was gone with 0.15.

However, I use Firebase as backend, and before I could go straight to subroutes with a URL like so: `mywebsite.com/#/menu`

Now, with the new scheme, it works when going from the homepage to the menu page, but not when opening the menu page directly.
So when I go straight to: `mywebsite.com/menu` I get the following Firebase error:

> Page Not Found
This file does not exist and there was no index.html found in the current directory or 404.html in the root directory.

Maybe not entirely Quasar's fault, but if anyone knows how to handle this that would be a great help!

**Comment by BenoitRanque** [comment]
This has nothing to do with quasar. Keywords you want to google:  Vue, Vue-Router, History mode

**Comment by pdanpdan** [comment]
http://lmgtfy.com/?q=firebase+spa+config

**Comment by mesqueeb** [comment]
Dear Community
Anyone who had this problem.

This is because the `firebase.json` file needs to be configured differently after Quasar 0.15.
The best way is to delete `firebase.json` and do `firebase init` in your directory again.
Then setup as a SPA.

Your `firebase.json` requires these lines:
```
"rewrites": [ {
  "source": "**",
  "destination": "/index.html"
} 
```
The answer was found here:
https://stackoverflow.com/questions/37667626/firebase-cli-configure-as-a-single-page-app-rewrite-all-urls-to-index-html

Thanks to @BenoitRanque and @pdanpdan for helping me find this solution!
