### ISSUE TITLE
 Implementing RTL Direction in Quasar Components

### ISSUE THREAD

**Issue by mohamad68** [quasarframework/quasar#17338]
### What happened?

I have configured my project with RTL as the default direction. using Quasar framework and PostCSS with rtlcss.  I'm encountering an unintended behavior where styles such as margin-right are automatically converted to margin-left. This is not the desired outcome for my project.
![image](https://github.com/quasarframework/quasar/assets/16140647/d438bb6d-0d69-4612-aeda-21d5990b5bde)

### What did you expect to happen?

i am seeking guidance on how to exclusively adjust the direction of Quasar's built-in components to RTL without affecting other styles or functionalities in my application.

### Reproduction URL

 https://codepen.io/mohamad/pen/abrrLML?editors=1010

### How to reproduce?

1-Added rtlcss to the PostCSS configuration.
2-Specified lang="fa-ir" in the Quasar configuration.
3-Set dir="rtl" on the HTML tag.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by mohamad68** [comment]
It appears that the Quasar framework may be facing challenges, as there are currently over 500 open issues.? is it deprecated?

**Comment by rstoenescu** [comment]
Please follow the guide at https://quasar.dev/options/rtl-support
Notice that you also need to configure Quasar with an RTL Quasar language pack.

![image](https://github.com/user-attachments/assets/b85d3850-3580-4ae2-81eb-971551cbef55)

**Comment by mohamad68** [comment]
@rstoenescu

**Comment by mohamad68** [comment]
@rstoenescu 
First, thank you for your response. The configuration you mentioned does indeed transform the code to RTL, but my aim is to write RTL code directly, without relying on transformations. The issue I'm encountering is that Quasar components are inherently coded in LTR, and they only switch to RTL through transformation.

To clarify, if I want to use Quasar components in RTL, I am forced to apply the transformation using the guidelines you've provided. However, this approach affects all the code, not just the Quasar components, which isn't what I want.

Unfortunately, due to this issue, the usage of the Quasar framework is quite rare in countries that primarily use RTL languages.

For a better understanding, I suggest creating a project and trying to code with an RTL base directly, so you can see the challenge in action.

**Comment by mohamad68** [comment]
@rstoenescu 
First, thank you for your response. The configuration you mentioned does indeed transform the code to RTL, but my aim is to write RTL code directly, without relying on transformations. The issue I'm encountering is that Quasar components are inherently coded in LTR, and they only switch to RTL through transformation.

To clarify, if I want to use Quasar components in RTL, I am forced to apply the transformation using the guidelines you've provided. However, this approach affects all the code, not just the Quasar components, which isn't what I want.

Unfortunately, due to this issue, the usage of the Quasar framework is quite rare in countries that primarily use RTL languages.

For a better understanding, I suggest creating a project and trying to code with an RTL base directly, so you can see the challenge in action.
