### ISSUE TITLE
404 for source code of textarea

### ISSUE THREAD

**Issue by neorganic** [quasarframework/quasar#1733]
In documentation page http://v0-13.quasar-framework.org/components/textarea.html

the link to source code is broken (404) : 
https://github.com/quasarframework/quasar-framework.org/edit/dev/source/components/textarea.md

**Comment by rstoenescu** [comment]
Hi, You can inspect branch v0.13 of Quasar Play: https://github.com/quasarframework/quasar-play/tree/v0.13
Due to the tight schedule a re-release for v0.13 docs is currently impossible. Sorry.
