### ISSUE TITLE
rounded floating q-badge not "round" when working with q-icon

### ISSUE THREAD

**Issue by haaah** [quasarframework/quasar#17342]
### What happened?

I have created a rounded floating badge in between q-icon, the badge come out "stretch". It works fine when paired with q-btn

### What did you expect to happen?

the rounded floating q-badge should be round.

### Reproduction URL

https://jsfiddle.net/2p4oLs1b/10/

### How to reproduce?

1. Go to the reproduction link
2. Click Run

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Style & Identity (quasar), SPA Mode

### Platforms/Browsers

Chrome

**Comment by haaah** [comment]
Is there a workaround for this?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.16.9
