### ISSUE TITLE
help me,how to start this project,there is no doc to explain it

### ISSUE THREAD

**Issue by li161** [quasarframework/quasar#17350]
### Description

help me,how to start this project,there is no doc to explain it

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by TobyMosque** [comment]
there is a doc ([quasar.dev](https://quasar.dev)), but if that is blocked to you, you can clone this repo and execute the docs locally: 
```bash
git clone https://github.com/quasarframework/quasar.git
cd quasar/doc
# pnpm dev:ssr
pnpm dev
```

**Comment by li161** [comment]
thank you very much,this can be run in windows? i failed it in my windows computer

**Comment by TobyMosque** [comment]
as long u had git, node and pnpm installed. that would work
https://gitforwindows.org
https://nodejs.org/en (LTS)
https://pnpm.io/installation

But I'm starting to think u're in the wrong project, maybe u're looking for the quasar store (who isn't related to the quasar framework)
