### ISSUE TITLE
QInput returns empty string for number model

### ISSUE THREAD

**Issue by ymarcon** [quasarframework/quasar#17359]
### What happened?

When using the QInput to capture numbers, deleting the entry sets the model's value to an empty string, which is not a number as expected.

### What did you expect to happen?

Deleting the number input entry manually or using the clearable icon should give the same result: a null value

### Reproduction URL

https://codepen.io/yop12/pen/NWZWQdK

### How to reproduce?

1. use codepen link and open console
2. enter a number and delete it manually (resp. using the clearable) and check the output in the console: the model's number value is an empty string (resp. a null value).

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
Hi, unfortunately, it's how Vue behaves. You will get the same behavior if you use a native `<input>` as well.
https://github.com/vuejs/vue/issues/4742
https://github.com/vuejs/core/issues/8214

It's a bit annoying, but you can workaround it by using something like `:model-value="model"` + `@update:model-value="value => { model = value === '' || value === null || value === undefined ? null : parseFloat(value); }"`

**Comment by ymarcon** [comment]
Oh ok I see... I have this kind of workaround already but I thought it could be integrated into the component. Anyways thx @yusufkandemir for your answer.
