### ISSUE TITLE
Terser error "digital enveloper outines::unsupported" when using build: { minify: false }

### ISSUE THREAD

**Issue by kirschkern** [quasarframework/quasar#17372]
### What happened?

I want to disable minification of my build. So I set `minify: false` in the `build` section of my quasar.conf.js file.
When I run "quasar build", I get the error

js/69.763c7054.js from Terser
  Error: error:0308010C:digital envelope r
  outines::unsupported

When setting minify: true, it runs without errors.
This happens for both pwa and spa applications.

I've run "npm update" and "npm audit fix --force" but still get the error.

Any idea how to disable code minification for my quasar 1 project?
Thanks
Daniel

### What did you expect to happen?

Creating a build with the original code (not minified)

### Reproduction URL

https://codepen.io/daniel-kirsch/pen/mdZJzdv

### How to reproduce?

My quasar.conf.js can be seen in the codepen

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

**Comment by rstoenescu** [comment]
Please type "quasar info" inside of your project folder in the terminal and copy/paste the output.
Otherwise it's unclear what Quasar CLI (and which version) you are reporting the bug for.

**Comment by kirschkern** [comment]
Operating System - Windows_NT(10.0.22621) - win32/x64       
NodeJs - 21.1.0     

Global packages     
  NPM - 10.2.0
  yarn - Not installed
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed     
  cordova - Not installed

Important local packages
  quasar - 1.22.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time   
  @quasar/app - 2.4.4 -- Quasar Framework local CLI
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations      
  eslint-plugin-quasar - Not installed  
  vue - 2.7.16 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.6.5 -- Official router for Vue.js 2        
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed     
  electron-builder -
 Not installed      
  @babel/core - 7.24.8 -- Babel compiler core.
  webpack - 4.47.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 5.1.4 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.    
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 5.5.3 -- TypeScript is a language for application scale JavaScript development       
  @capacitor/core - Not installed       
  @capacitor/cli - Not installed        
  @capacitor/android - Not installed    
  @capacitor/ios - Not installed        

Quasar App Extensions
  *None installed*  

Networking
  Host - Daniel     
  WLAN - 192.168.178.20

**Comment by rstoenescu** [comment]
You are on Quasar v1, which is out of support for some time now. We've announced the end of life for v1 years ago then still supported it a few more years. Please upgrade to Quasar v2 -- you can find the upgrade guide on the docs website: https://quasar.dev/start/upgrade-guide#migrate-to-v2-from-v1

**Comment by kirschkern** [comment]
Yes, the project is huge and the transition to Vue 3 would take several weeks (without the transition to the composition API).
Thanks anyway for looking into this.

**Comment by rstoenescu** [comment]
You don't need to transition to composition API if you don't want to. The Options API is still supported in Vue 3.

However, if your company would be willing to contribute financially towards Quasar development we could make the extra effort for the v1 fix. If you want to talk about this, please DM me on Discord.
