### ISSUE TITLE
Error when introducing Quasar build in Vitepress  , Error: __QUASAR_SSR_SERVER__ is not defined

### ISSUE THREAD

**Issue by waversky** [quasarframework/quasar#17381]
### What happened?

vitepress 引入 Quasar 报错 Error: __QUASAR_SSR_SERVER__ is not defined

### What did you expect to happen?

我在一个空文件夹初始化 vitepress 并引入 Quasar ，
按照Vite plugin的指引安装到项目中，
预览没有问题，但是编译时报错 Error: __QUASAR_SSR_SERVER__ is not defined

### Reproduction URL

https://stackblitz.com/edit/vite-x5s5gg

### How to reproduce?

在控制台中执行
npm run docs:build

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Other

### Relevant log output

```Shell
✓ building client + server bundles...
⠋ building client + server bundles...build error:
__QUASAR_SSR_SERVER__ is not defined
Error: __QUASAR_SSR_SERVER__ is not defined
    at _evaluate (https://vitex5s5gg-uh0g-m0jrlexf.w-corp-staticblitz.com/blitz.41692973.js:40:793812)
```

**Comment by yusufkandemir** [comment]
The reproduction you've included works without any errors. So, I can't reproduce the issue.

**Comment by Fulbert** [comment]
Hello, if I run `npm run docs:build` as mentionned by OP, I can reproduce.

I have the same problem but with the following versions : 
```json
"dependencies": {
  "@quasar/extras": "^1.17.0",
  "quasar": "^2.18.6",
},
"devDependencies": {
  "@quasar/vite-plugin": "^1.10.0",
  "vitepress": "^2.0.0-alpha.15",
},
```

Here is a reproduction with latest version of the 4 dependencies: 
https://stackblitz.com/edit/vite-uuopflbg?file=package.json
