### ISSUE TITLE
q-table disables mouse hover effect

### ISSUE THREAD

**Issue by 3168304181** [quasarframework/quasar#17396]
### Description

Each row in q-table will have a default background color when you hover over it. How to remove this default effect?
This default effect will cause me to set tbody tr:hover {
tbody tr:hover {
background-color: #fff ! important;
}
} When this style is used, the actual color missing is #f7f7f7
![Snipaste_2024-07-25_11-39-49](https://github.com/user-attachments/assets/27ba83e8-b85b-476c-8553-cb22ab5adfe1)

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

You can use QTable prop `no-hover` (Boolean)
