### ISSUE TITLE
Floating label won't float if input is disabled (even if it contains value)

### ISSUE THREAD

**Issue by skyrpex** [quasarframework/quasar#174]
There's an edge case where floating label won't float if input is disabled even if it contains value. The result is that the label stays over the input value.

The reason is that `:valid` doesn't "work" if the input is disabled.

Maybe we should implement a `quasar-textfield` component that handles blur events, or maybe is there some other way by just changing the default floating state (by using `:not(:valid)` and `:not(:disabled)`).

**Comment by rstoenescu** [comment]
Thanks for reporting this. Will fix it really soon.

**Comment by rstoenescu** [comment]
I tend to avoid creating components in cases where a simple HTML markup coupled with some CSS would suffice. This is for performance. Will analyze if CSS can be fixed, and if not, I'm afraid a component will be needed.

**Comment by skyrpex** [comment]
Yes, I agree with you: having components for everything would bloat too much, but I'm afraid there's no reliable way in CSS to check that an input has value (when it's disabled). :disappointed:

**Comment by rstoenescu** [comment]
PR is being worked on by @CookieJon

**Comment by rstoenescu** [comment]
Will be available in v0.14
