### ISSUE TITLE
QInput is not providing control slot

### ISSUE THREAD

**Issue by stryaponoff** [quasarframework/quasar#17414]
### What happened?

I want to use custom mask processor for QInput using the `control` slot [according to docs](https://quasar.dev/vue-components/input#using-third-party-mask-processors).

This is not working and if I correctly understand the code, it will not work by design.
```javascript
if (state.getControl !== void 0) {
  // `getControl` function is defined inside QInput component, so we're always selecting this branch
}
// internal usage only:
else if (slots.rawControl !== void 0) {
  // ...
}
else if (slots.control !== void 0) {
  // Unreachable code, because `getControl` is always defined in the `state` object.
}
```

### What did you expect to happen?

`control` slot is working as described in docs

### Reproduction URL

https://codepen.io/Kirill-Stryaponov/pen/WNqjqYy

### How to reproduce?

1. Insert this block to template:
```
<q-input>
  <template v-slot:control>
    Hello world
  </template>
</q-input>
```
2. Ensure that slot contents are not used

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
You start from **QInput** and convert it to a **QField** as described in the docs
![image](https://github.com/user-attachments/assets/6519bffe-16ea-4cae-800f-e2cb30379a7a)
