### ISSUE TITLE
Quasar timeline SSR

### ISSUE THREAD

**Issue by jimhill21** [quasarframework/quasar#1742]
Hello,

We had to start migrating to Vuetify because we need SSR.  We would absolutely stay and support Quasar if SSR can be functional.  At this point even if we could get something Beta for 0.15 that would be good enough.

We would be willing to commit to a monthly donation just so we don't have to use Vuetify :pray:

**Comment by rstoenescu** [comment]
Hi, SSR is a top priority for Quasar. Can you connect with me on Discord pls? Thanks.
