### ISSUE TITLE
Components inside default slot of QImg not working correctly

### ISSUE THREAD

**Issue by Dtsiantaris** [quasarframework/quasar#17426]
### What happened?

While using the default slot inside a `q-img` component, things inside the slot itself seem to be broken. Styles sometimes break and events are not emitted correctly.

Behavior below can be reproduced with other elements too(i.e. a `a` tag).

### What did you expect to happen?

The components/valid HTML inside the default slot to render and behave correctly

### Reproduction URL

https://codepen.io/dtsiantaris/pen/abgyYVP

### How to reproduce?

1. Go to the provided link
2. Click on the `Test Btn` inside the image
3. You will notice that the event is never fired and the value of the `testRef` never changes.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

**Comment by stefanvanherwijnen** [comment]
Wrap the `q-btn` in a `div`:
https://codepen.io/stefanvh/pen/BagdgPQ

Also, your button wasn't linked to `testClick` :grin: .

**Comment by rstoenescu** [comment]
Cannot reproduce. Button works correctly. Even if it didn't, it wouldn't have to do with Quasar but with Vue itself.
