### ISSUE TITLE
sockjs is using the quasar.conf.js defined port which is really a local port and so when added to any urls it returns a connection error because of nginx/apache expecting 80/443

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#1743]
### Software version

Quasar: 0.15.9
OS: Linux mint 18.1
Node: 8.9.1
NPM: 5.7.1
Browsers: Chrome
iOS: n/a
Android: n/a
Any other software related to your bug: sockjs, webpack, the one that comes with webpack

### What did you get as the error?
https://gyazo.com/dc562d0006b3c6ccefe79bbd93631b2d
### What were you expecting?
it to use no port, or to be allowed to set the port for it to use, and not use the port set in quasar.conf.js because that's a local port really
### What steps did you take, to get the error?
just configured my project with a custom port, 8888, and I set up a socket.io plugin but I don't think it's the plugin which is causing this, because I think that quasar uses sockjs by default..? I think?

**Comment by rstoenescu** [comment]
Hi,

This has to do with HMR (Hot Module Reload) provided by Webpack dev server. I think you need to use another port than the dev-server's one for your socket.io. That's already being used. Your own server needs another channel to communicate.

**Comment by lopugit** [comment]
but the dev server gets it's port from the quasar.conf.js file? As in it'll always use what you define there? So the only way to change the port it uses is to edit node_modules/webpack-dev-server/client/index.js I believe? 

`{
port: undefined
}`

fixed it for me and kept hot reloading

**Comment by mstaack** [comment]
@lopugit you can change dev servers config within quasar.conf!

there is a dev server part where you can also change the port:
```
 devServer: {
      // https: true,
      // port: 8080,
      open: true, // opens browser window automatically
      proxy: {
        '/api': {
          target: 'http://localhost:8000',
          changeOrigin: true,
          pathRewrite: {
            '^/api': ''
          }
        }
      }
```

**Comment by rstoenescu** [comment]
I think it's best to bring this up to webpack guys... Quasar's not in control of what webpack-dev-server does, other than the params from quasar.conf > devServer which get passed to it -- these params can be found here: https://webpack.js.org/configuration/dev-server/

**Comment by waelio** [comment]
Guys, try running "quasar dev" using the debug console and set it to catch uncaught exceptions. You'll see the bug. Mine was in amplify trying to access unauthorized Cognito account.
