### ISSUE TITLE
v-close-popup directive not imported automatically in 2.16.x 

### ISSUE THREAD

**Issue by rasmus0201** [quasarframework/quasar#17466]
### What happened?

Hi, first of all thank you for an amazing package - great work!

When using `v-close-popup` inside a `QDialog` to close the dialog, it fails due to the directive no longer being automatically/globally registered and thus the dialog will remain open. This is not mentioned anywhere in the docs, nor could I find any information of this in the changelog for the 2.16.x versions, and making this change in a minor version would not be fair since IMO would consider it a breaking change.

You can't "just upgrade" quasar from e.g. `2.15.4` to `2.16.9`. In `2.16.x`. You either have to:

- import the directive globally yourself in the quasar options for directives (which works, but gives TS type error unless you provide the full list of directives, which isn't necessarily needed in the app) 
- import the directive in every used component using `import { ClosePopup as vClosePopup } from "quasar"`, this is also tedious if used a lot

Hence I think it is breaking semver, including this change in a minor version. If you want the users to do either of these it should be in the new major and the docs should be updated.

### What did you expect to happen?

`v-close-popup` directive should still be automatically, globally registered directive, as it was in `2.15.x`. 

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-36xdmn?file=src%2FApp.vue

### How to reproduce?

1. Go to reproduction
2. Click `Show dialog`
3. Attempt to click `Close`
4. Nothing happens. 
5. Try the same on my [2.15.4 reproduction](https://stackblitz.com/edit/vitejs-vite-tp7dvo?file=src%2FApp.vue) - here it works

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Directives (quasar)

**Comment by rstoenescu** [comment]
Hello,

First of all, we cannot automatically register everything that Quasar supplies because that will break the tree-shaking. So it's up to the user to request whatever features it wants.
The fact that it previously worked doesn't means it was a correct usage. The explanation is a long one, so let's get to the solutions instead:

1. **Highly recommended!** Use our Vite plugin. https://quasar.dev/start/vite-plugin You won't have to manually import anything in your vue files. And tree-shaking will fully work.

2. The other option is continuing to not use our Vite plugin (but be careful that tree-shaking will not quite work along other features) and add the following, directly in your main.ts file:

```ts
import { Dialog, ClosePopup } from 'quasar'; // notice ClosePopup

const quasarUserOptions = {
  config: {},
  plugins: { Dialog },
  directives: { ClosePopup }, // <<<<<<------
  lang,
};

createApp(App).use(Quasar, quasarUserOptions).mount('#app');
```

What this does is register the directive globally in Vue. You can do the same with components too.

**Comment by rasmus0201** [comment]
Hi thanks for your reply

1. won't really work us as we are still stuck to webpack (and we can't move to Vite quite yet)
2. As i specified, this solution does work, but TypeScript errors when not providing the full list of directives:

```
No overload matches this call.
  Overload 1 of 2, '(plugin: Plugin<[options: Partial<QuasarPluginOptions>]>, options: Partial<QuasarPluginOptions>): App<Element>', gave the following error.
    Argument of type '{ config: {}; plugins: {}; directives: { ClosePopup: ClosePopup; }; }' is not assignable to parameter of type 'Partial<QuasarPluginOptions>'.
      Types of property 'directives' are incompatible.
        Type '{ ClosePopup: ClosePopup; }' is missing the following properties from type 'QuasarDirectives': vClosePopup, vIntersection, vMorph, vMutation, and 7 more.
  Overload 2 of 2, '(plugin: Plugin<[options: Partial<QuasarPluginOptions>]>, options: [options: Partial<QuasarPluginOptions>]): App<Element>', gave the following error.
    Argument of type '{ config: {}; plugins: {}; directives: { ClosePopup: ClosePopup; }; }' is not assignable to parameter of type '[options: Partial<QuasarPluginOptions>]'.
``` 

**So I guess my request is to fix the interface to allow a partial directives list** .

Let me what you think about this. 


Edit: 

doing this:

```
const quasarUserOptions: QuasarPluginOptions = {
  config: {},
  plugins: {},
  directives: { vClosePopup: ClosePopup }
};
``` 

gives the following TS error: 

```
Type '{ vClosePopup: ClosePopup; }' is missing the following properties from type 'QuasarDirectives': vIntersection, vMorph, vMutation, vRipple, and 6 more.
```

So `QuasarPluginOptions["directives"]` should allow a partial list IMO
