### ISSUE TITLE
Tab Panels: @transition emits before component transitioned to a new panel

### ISSUE THREAD

**Issue by piyapanw** [quasarframework/quasar#17479]
### What happened?

From the documentation about Tab panels, @transition event should be emitted after component transitioned to a new panel. However, it is emitted before the component transition to a new panel.

### What did you expect to happen?

@transition event should be emitted after component transitioned to a new panel

### Reproduction URL

https://codepen.io/piyapanw/pen/Bagqrep?editors=1010

### How to reproduce?

1. Go to the provided link.
2. Click at any option.
3. The alert dialog shows up before the transition to a new panel.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Tab Panels: Basic - Quasar v2.16.9
```

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.16.12
