### ISSUE TITLE
QCheckbox have a memory leaks issue.

### ISSUE THREAD

**Issue by yeyuqh** [quasarframework/quasar#17485]
### What happened?

It’s not just QCheckbox; QRadio, QSpace, and other components also use this approach.

```
import { defineComponent, h } from 'vue'

 // This kind of implementation in the component creates a global VNode, which will not be collected by GC.
const prefixNode = h('span', { class: 'prefix' }, 'prefix') 

export default defineComponent({
  name: 'ListItem',
  props: ['index'],

  setup(props) {
    return () => (
      h('div', { class: 'item' }, [prefixNode, `Item ${props.index}`])
    )
  },
})
```
In some cases, this can cause the entire page’s DOM to not be collected by GC.

### What did you expect to happen?

```
import { defineComponent, h } from 'vue'

export default defineComponent({
  name: 'ListItem',
  props: ['index'],

  setup(props) {
	const prefixNode = h('span', { class: 'prefix' }, 'prefix') // I believe it should be placed in the setup function.

    return () => (
      h('div', { class: 'item' }, [prefixNode, `Item ${props.index}`])
    )
  },
})
```

### Reproduction URL

•

### How to reproduce?

![CleanShot 2024-09-05 at 16 14 45@2x](https://github.com/user-attachments/assets/341d322b-8629-4e9a-b635-59e27894d141)
![CleanShot 2024-09-05 at 16 21 14@2x](https://github.com/user-attachments/assets/bc32f399-fe3f-4bab-9803-572b3e3f54e6)

Clicking the Toggle button multiple times to show/hide it reveals that there are always 500 nodes that cannot be collected by GC.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Safari

**Comment by rstoenescu** [comment]
Hi,

Thank you for creating this ticket and the reproduction setup!
You are indeed right. Seems like the GC doesn't clean up with those global nodes.

Fix will be available shortly in Quasar v2.16.11
