### ISSUE TITLE
Quasar project created with 「npm init quasar」 uses outdated Quasar version from 2022 v2.6.0

### ISSUE THREAD

**Issue by jacktanxd** [quasarframework/quasar#17481]
### What happened?

When initializing a new Quasar project using the command npm init quasar, the generated project references an outdated version of Quasar from 2022 v2.6.0 rather than the latest stable version. This could lead to compatibility issues, missing features, and security vulnerabilities associated with the older version.

<img width="299" alt="image" src="https://github.com/user-attachments/assets/18a90006-932b-41e8-9d0e-776b36cd120a">

### What did you expect to happen?

The generated project should use the latest stable version of Quasar v2.16.19.

### Reproduction URL

[https://quasar.dev/start/quasar-cli](url)

### How to reproduce?

1. Run the command npm init quasar in a terminal.
2. Complete the setup prompts.
3. Inspect the package.json file to see the Quasar version installed.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

Please note the caret character (`^`) in front of the version. This instructs your package manager to install the **latest** version (with no breaking changes). So it installs whatever Quasar version is latest.
