### ISSUE TITLE
Platform.is.electron and other properties are undefined

### ISSUE THREAD

**Issue by FKPSC** [quasarframework/quasar#17482]
### What happened?

`Platform.is.electron` returns `undefined`

same for other properties of is such as `Platform.is.kindle`

this also applies for `$q.platform.is.*`

### What did you expect to happen?

`platform.is.electron` to return `true` or `false` as advertised by the documentation:

same for other properties of is such as `Platform.is.kindle`

this also applies for `$q.platform.is.*`

https://quasar.dev/options/platform-detection#properties

### Reproduction URL

https://jsfiddle.net/pt49kcgn/2/

### How to reproduce?

1. Open provided URL
2. Notice `undefined` value

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
As can be seen in the docs here, it would return the relevant properties, not all:
https://quasar.dev/options/platform-detection#usage
![image](https://github.com/user-attachments/assets/df754f96-3ea3-44d8-a9e6-049d3fcb3f35)

So, it's natural for `Platform.is.electron` to be undefined if the app not running on Electron.

Our TypeScript types also reflect this:
![image](https://github.com/user-attachments/assets/7bf27dbe-8622-4819-a142-84527dd9dd5b)

> platform.is.electron to return true or false as advertised by the documentation

The docs don't explicitly say it's `true` or `false`. But, I guess you deduce it from the type column mentioning `Boolean`. So, I am converting this issue to clarify the docs.

**Comment by FKPSC** [comment]
Right, only `nativeMobileWrapper` is explicitely mentioned to be potentially undefined
![image](https://github.com/user-attachments/assets/fe43ce65-4d3e-4574-8dda-8743453352c6)

If those booleans were initialized as `false` they would all be present, directly usable and with more simplified typing. That note in the docs could also be removed.

This would be a slight improvement, right?

**Comment by rstoenescu** [comment]
Hi,

We were previously not embedding all "false" valued props for a lower js footprint. The one prop (nativeMobileWrapper) was explicitly specified as being "undefined" because it was the only one that is a String, as opposed to all other ones being a Boolean.
However, for consistency, we'll be embedding all Boolean props now (even the ones which should be "false". This will be available in Quasar v2.17+
