### ISSUE TITLE
QIcon font awesome v6 class 'fa-classic' causes QIcon to render incorrectly

### ISSUE THREAD

**Issue by mjwlist** [quasarframework/quasar#17483]
### What happened?

The valid Font Awesome v6 class 'fa-classic' causes the QIcon component to render incorrectly.
For example:
` <q-icon name="fa-classic fa-regular fa-calendar-days" size="5rem" />`
Will render:
`<i class="q-icon notranslate material-icons" aria-hidden="true" role="presentation" style="font-size: 5rem;">fa-classic fa-regular fa-calendar-days</i>`

Without the 'fa-classic' class it will render correctly.
For example:
` <q-icon name="fa-regular fa-calendar-days" size="5rem" />`
Will render:
`<i class="q-icon fa-regular fa-calendar-days" aria-hidden="true" role="presentation" style="font-size: 5rem;"> </i>`

### What did you expect to happen?

When the 'fa-classic' class is included the icon should render correctly.

For example:
` <q-icon name="fa-classic fa-regular fa-calendar-days" size="5rem" />`
Should render:
`<i class="q-icon fa-classic fa-regular fa-calendar-days" aria-hidden="true" role="presentation" style="font-size: 5rem;"> </i>`

It looks as though this is down to some Font Awesome class validation regex in the QIcon component.
Adding 'classic' to this as follows would appear to fix this issue.

For example:
`const faRE = /^(fa-(classic|sharp|solid|regular|light|brands|duotone|thin)|[lf]a[srlbdk]?) /
`

### Reproduction URL

https://jsfiddle.net/54jtxhac/

### How to reproduce?

1. Go to the provided reproduction link.2
2. Look in the inspector to see the rendered output of the two QIcon components. One with and one without the the 'fa-classic' class included.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari

### Additional context

Happy to submit a pull request for this but want to check if it would be welcomed first.

We have some api's returning the 'fa-classic' class along with the other parts of the icon classes and this is causing us a number of client side headaches so keen to resolve if possible.

Additional screenshots for context..

![Screenshot 2024-09-04 at 16 16 19](https://github.com/user-attachments/assets/7f625672-7d32-4f26-ae31-a5924039c9a0)
![Screenshot 2024-09-04 at 16 14 50](https://github.com/user-attachments/assets/a57fdaf5-76d5-46d5-b7a6-8616c088cd89)
![Screenshot 2024-09-04 at 16 15 10](https://github.com/user-attachments/assets/5be650da-1c56-4dfd-8c88-09d7ef6db941)

**Comment by yusufkandemir** [comment]
Hi, you can omit `fa-classic` and just use `fa-regular fa-calendar-days`. But, since you can't easily omit `fa-classic` and it's a valid value regardless, you can submit a PR. Thanks for explaining the situation in detail.

**Comment by mjwlist** [comment]
Ok thanks.
PR submitted: #17486
