### ISSUE TITLE
[Request] Resizable div component (like a calendar event)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1748]
I'm making a one-day calendar application.

I'm going to create something that clicking on an event once will show two small dots on the top and the bottom of the event-div and dragging those will make the div larger / smaller.

Then I need feedback how many pixels the user dragged up/down, calculate that against the `height` of "5 minutes" on my current screen, and send the feedback to the server.

If there's any plan to make this a Quasar component, please let me know. If not, I'll try and share what I come up with here.

I'd add little dots on top and on the bottom of the calendar event after the user taps on it. Just to get an idea: 
<img width="469" alt="2018-03-12 17 39 09" src="https://user-images.githubusercontent.com/3253920/37273178-5b3055d4-261c-11e8-839b-ac554e8ff25c.png">
(dots to be added)

**Comment by rstoenescu** [comment]
Hi,

Use TouchPan directive for this. You got everything you need by using it to create your component: http://quasar-framework.org/components/touch-pan.html

**Comment by mesqueeb** [comment]
Dear Razvan, I studied the TouchPan directive. It seems very good! 

I wanted to ask : Do you have any hints for me as to how to move or resize the actual div with the touchPan directive?
 this seems tricky! :D

**Comment by rstoenescu** [comment]
Wish I could have time to guide, but I'm on a tight schedule :(

**Comment by mesqueeb** [comment]
![2018-03-13 16 30 25](https://user-images.githubusercontent.com/3253920/37328062-13e43fe0-26dc-11e8-9ebe-6b3f75a6722e.gif)

Just to let the world know:
I was able to create it with summing the `delta` value of the scroll feedback, and every time I want to show the drag animation I would reset the total delta value and reflect the changes to the element's css.

You can also do something similar where you use css translate to do + or - pixels in a direction.

**Comment by Olafxso** [comment]
@mesqueeb I also like to resize the calendar event, Can you share your code to achieve that?
Thanks in advance!

**Comment by mesqueeb** [comment]
@Olafxso I'm afraid I won't be able to help you.
This is a very old app of mine I'm not even working on anymore.

The thing is, this was not the Quasar Calendar component or UI extension, it was a 100% self-written calendar component.
So I was able to attach `v-touch-pan` to the drag handlers, and then just update a value in the component template, and make sure the CSS is transformed to reflect that change.
That's all.

Good luck!

**Comment by Olafxso** [comment]
@mesqueeb . I figured it out. I need to get the height usin: this.$refs.calendar_event.$el.clientHeight

So the full method is now: 
```Vue
    handlePan ({ evt, ...info }) {
      this.$refs.calendar_event.$el.style.height = this.$refs.calendar_event.$el.clientHeight + info.delta.y + 'px'
    }
```
