### ISSUE TITLE
Stepper - allow to select alignment/position

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#175]
Hi,

I am just implementing the first stepper.
It is great, but in my opinion does not look good on big screen when it is in the middle.
I agree that some people can like it, but a lot will not, so can you please let us choose, maybe between LEFT/MIDDLE/(RIGHT) ? 

Also would be nice to be able to choose the color as primary will not always work.

PS
In docs you have everything inside <quasar-transition>, but I found that it is applying slide without it which is nice. Are you aware of that?

**Comment by rstoenescu** [comment]
Will enhance it to allow alignment/position. Thanks for the suggestion!

As for the `<quasar-transition>`: it's not required, but in the Quasar Play example it is there because after stepper finishes I hide it and show the "Ok, you finished going through all steps". So the transition applies to Stepper itself as a whole (it doesn't have to do with animating each step).

**Comment by rstoenescu** [comment]
This has become obsolete. v0.14 will contain a revamp of Stepper, following Material design guide by the letter. Will be available as horizontal and vertical.

**Comment by odranoelBR** [comment]
Hi,
im using something to alignt left before 0.14

@media only screen and (min-width: 601px){
    .adv-form-one .timeline-badge {
      right: auto !important;
      left: auto !important;
    }
    .adv-form-one .timeline-content {
      margin-left: 3.9rem;
    }
    .adv-form-one .timeline-item {
      width: 100% !important;
    }
    .adv-form-one .timeline-title {
      text-align: inherit !important;
      margin-left: 3.9rem;
    }
    .timeline:before {
      left: 1.6rem;
    }
  }

OBS: wrap your stepper whit div class ".adv-form-one", or change this css class name.

**Comment by Underzzoo** [comment]
How did you put the back line to the left with this CSS ? Thanks man !
