### ISSUE TITLE
application unable to install

### ISSUE THREAD

**Issue by Seamus-Ohhhh** [quasarframework/quasar#17509]
### What happened?

Using Quasar as an imported module the application is failing to mount due to error thrown when installing quasar.

since the upgrade to v.2.16.0 Quasar tries to install in SSR mode. this is due to __QUASAR_SSR_SERVER__ returning true when the application is building. the install function is expecting 3 arguments.

### What did you expect to happen?

application mounts as normal in client mode

### Reproduction URL

https://codesandbox.io/p/sandbox/vue3-base-forked-vxxvpp

### How to reproduce?

1. open link
2. 2. wait for app to load 

### Flavour

UMD

### Areas

SPA Mode

### Platforms/Browsers

Firefox, Chrome, Safari

### Relevant log output

```Shell
Ff
https://vxxvpp.csb.app/node_modules/quasar/dist/quasar.server.prod.cjs:7:19686
install
https://vxxvpp.csb.app/node_modules/quasar/dist/quasar.server.prod.cjs:127:19345
use@https://vxxvpp.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.cjs.js:3763:18
$csb$eval
https://vxxvpp.csb.app/src/main.js:8:5
```

### Additional context

same issue as one previously raised https://github.com/quasarframework/quasar/issues/17190

**Comment by rstoenescu** [comment]
Hi,

The Vue-CLI has been deprecated for a while.
Also, you should have been using our vue cli plugin (https://quasar.dev/start/vue-cli-plugin). However, that is in maintenance mode and hasn't been updated yet (due to people not actually demanding it since there are much better alternatives).

Can't run the project that you indicated, but still, we'll make an effort to update the vue-cli-plugin-quasar to the Quasar v2.16+ specs.

As a side-note, before vue-cli-plugin-quasar is updated, you could try to manually configure the underlying Webpack to include DefinePlugin with the following (by no means it ensures that your setup will work and will lack a lot of features that our plugin supplies):
```
__QUASAR_VERSION__: `'2.16.11'`,
__QUASAR_SSR__: false,
__QUASAR_SSR_SERVER__: false,
__QUASAR_SSR_CLIENT__: false,
__QUASAR_SSR_PWA__: false
```

Also, please try to at least upgrade to the latest vue cli (v5).

<img width="871" alt="image" src="https://github.com/user-attachments/assets/3f7eb516-25c9-473c-b9ec-bf6742968b53">

**Comment by Seamus-Ohhhh** [comment]
Hi,

Thank you for your response and the suggestions.

I attempted to manually configure the DefinePlugin (configureDefinePlugin in my case as I'm using Symfony Encore Webpack) with the provided constants (__QUASAR_VERSION__, __QUASAR_SSR__, etc.) in my Webpack setup. Unfortunately, this approach did not resolve the issue. The problem persists when the application is being mounted. 

Is there some config that can be passed to the app.use() function when adding quasar to force it away from SSR? 

```
import { createApp } from 'vue';
import App from './App.vue';
import { Quasar } from 'quasar';

const app = createApp(App);

// Configuring Quasar with the necessary settings
app.use(Quasar, {
  config: {
    ssr: false,
    // Other configuration settings
  },
});

// Mount the app
app.mount('#app');
```

Thanks again for your help, I understand that our use of the library is unconventional.

**Comment by yusufkandemir** [comment]
@Seamus-Ohhhh you can try configuring a Webpack alias that maps `quasar` to `quasar.esm.prod.js` instead of `quasar.server.prod.cjs`. That should eliminate the need for the 3rd parameter and possibly some other SSR stuff.
See: https://webpack.js.org/configuration/resolve/, this should work:
```js
{
  $quasar: 'quasar/dist/quasar.esm.prod.js'
}
```

**Comment by Seamus-Ohhhh** [comment]
@yusufkandemir thanks for your suggestion. I have looked into the build files but it seems that there is no esm build files available. Up to v2.15.4 (version we are currently on) that file is available and there is no issue with mounting. from v2.16+ the esm files are gone with added quasar.server.(.prop).js files in the folder.

is there a way to force it to generate the esm build files?

**Comment by yusufkandemir** [comment]
Sorry for the confusion, the correct file is `quasar.client.js`.

**Comment by rstoenescu** [comment]
My bad. I've already upgraded vue-cli-plugin-quasar to work with Quasar v2.16+.
Started with the project that you mentioned, added our vue cli plugin, upgraded deps for vue cli v5 and all other relevant ones. Had the project working as expected.

[vue-cli-project.zip](https://github.com/user-attachments/files/17026899/vue-cli-project.zip)

**Comment by Seamus-Ohhhh** [comment]
@yusufkandemir i was able to get it working using this suggestion. Had a slight issue with the registration of components and directives but but just need to manually import them and pass as part of the config which thankfully allows us to stay up to date with the library.

```
import { createApp } from "vue";
import { 
    Quasar,
    QBtn,
    Ripple,
} from "quasar/dist/quasar.client.js";
import App from "./App.vue";

const app = createApp(App);

const quasarConfig = {
    components: {
        QBtn,
    },
    directives: {
        Ripple,
    }
};

app.use(Quasar, quasarConfig);

app.mount("#app");
```

Again, thank you both for your help with the issue.
