### ISSUE TITLE
Needs a update to fix the depreciated meta tag: apple-mobile-web-app-capable

### ISSUE THREAD

**Issue by skgadi** [quasarframework/quasar#17521]
### What happened?

This is not a bug. I think a simple update is required.
The generated PWA is giving the following warning.

```
<meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
```

### What did you expect to happen?

I expect no warning.

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

1. Go to the website: [https://quasar.dev/vue-components/list-and-list-items](https://quasar.dev/vue-components/list-and-list-items)
2. Open the developer tools > console.
3. You will notice the warning message.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

PWA Mode

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

This has already been taken care of, just waiting to be released.
