### ISSUE TITLE
@quasar/cli - upgrade command (v2.4.1)

### ISSUE THREAD

**Issue by tinohager** [quasarframework/quasar#17533]
### What happened?

When I execute the command `quasar upgrade` an failure throw

```
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:433:7)
    at Object.app (file:///C:/Users/user1/AppData/Roaming/npm/node_modules/@quasar/cli/lib/app-paths.js:42:17)
    at file:///C:/Users/user1/AppData/Roaming/npm/node_modules/@quasar/cli/lib/app-pkg.js:6:33
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v20.9.0
```

### What did you expect to happen?

An update to the current version or a message that I am on the current version :)

### Reproduction URL

-

### How to reproduce?

Execute `quasar upgrade`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

What OS are you on? And which terminal (needed only if you are on Windows)?

**Comment by tinohager** [comment]
Windows 11, Command Line and Powershell the same.

**Comment by rstoenescu** [comment]
@tinohager One more question. What is the full path to your project folder?

**Comment by tinohager** [comment]
I try the command on this path

`C:\temp>quasar upgrade`

![image](https://github.com/user-attachments/assets/6b935f56-91b5-4b44-85fe-5c8797e1a34e)

**Comment by tinohager** [comment]
I have tried to output the variable here, it seems that an `undefined` is returned.


**app-paths.js**
```js
const { appDir, quasarConfigFilename } = getAppInfo()
const cliDir = fileURLToPath(new URL('..', import.meta.url))
console.log(appDir);
```

> quasar upgrade
undefined
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

**Comment by tinohager** [comment]
debug points added

```js
function getAppInfo () {
  let appDir = process.cwd()
  console.log(`debug1 - ${appDir}`)

  while (appDir.length && appDir[ appDir.length - 1 ] !== sep) {
    for (const name of quasarConfigFilenameList) {
      const filename = join(appDir, name)
      console.log(`debug2 - ${filename}`)
      if (existsSync(filename)) {
        return { appDir, quasarConfigFilename: filename }
      }
    }

    appDir = normalize(join(appDir, '..'))
    console.log(`debug3 - ${appDir}`)
  }

  return {}
}
```

Output
```
debug1 - C:\Users\user1
debug2 - C:\Users\user1\quasar.config.js
debug2 - C:\Users\user1\quasar.config.mjs
debug2 - C:\Users\user1\quasar.config.ts
debug2 - C:\Users\user1\quasar.config.cjs
debug2 - C:\Users\user1\quasar.conf.js
debug3 - C:\Users
debug2 - C:\Users\quasar.config.js
debug2 - C:\Users\quasar.config.mjs
debug2 - C:\Users\quasar.config.ts
debug2 - C:\Users\quasar.config.cjs
debug2 - C:\Users\quasar.conf.js
debug3 - C:\
```

**Comment by yusufkandemir** [comment]
Where is your project located? e.g. `C:\Users\user1\projects\my-project`
Where are you executing the command from? e.g. `C:\Users\user1`

Just a sanity check: you should run `quasar upgrade` in your project directory (root or subfolders), so that it can detect whether your project has up-to-date dependencies or not. So, if you run it in an arbitrary directory, it won't find your project, and thus won't work properly.

**Comment by tinohager** [comment]
Okay, the command does not allow me to update the quasar-cli in this case.
