### ISSUE TITLE
QSelect filter does not update correctly on mobile on 2.17.0

### ISSUE THREAD

**Issue by GArecoT** [quasarframework/quasar#17536]
### What happened?

QSelect filter only updates when space is pressed or a word is erased. This only happens in Android.

https://github.com/user-attachments/assets/28af57d1-404f-4693-9707-2190858a323a

### What did you expect to happen?

It should update as the user types. 

This is how it behaved in 2.16.6

https://github.com/user-attachments/assets/82106a4a-1a2d-4ee4-b1bf-77e8240723ce

### Reproduction URL

https://github.com/GArecoT/quasarselectbug

### How to reproduce?

Go to the link on a android device and use select 

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.17.1
