### ISSUE TITLE
QTable: expanding a row expands all rows on the table

### ISSUE THREAD

**Issue by monicaaikorice** [quasarframework/quasar#1753]
![qdatatable_rowexpand_bug](https://user-images.githubusercontent.com/2080375/37315303-4260c602-2616-11e8-95e0-a26e212af1de.gif)

### Software version

Quasar: v.0.15.6
OS: Mac OSX High Sierra 10.13.3 x64
Node: 9.8.1
NPM: 5.6
Browsers: Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### JsFiddle (for Quasar v0.15+ only)
[https://codepen.io/mishmomo/pen/KodyGP](https://codepen.io/mishmomo/pen/KodyGP)

### What did you get as the error?
No error, but expanding one row expands all rows on the table

### What were you expecting?
If I expand one row, I only expect that row to expand

### What steps did you take, to get the error?
I used the code [found here](http://quasar-framework.org/components/datatable.html#Custom-header-amp-rows-with-selection-amp-expandable-rows) for the table template. The logic I used is in the codepen.

Is this a slot or slot-scope issue?

**Comment by rstoenescu** [comment]
Hi,

Notice you're using `row-key="name"` which tells Quasar to identify each row by the "name" property. But all your rows have the same value for "name" prop. You need unique values.

**Comment by rstoenescu** [comment]
Example: https://codepen.io/rstoenescu/pen/LdpeLB

**Comment by monicaaikorice** [comment]
I see what I did, I apologize for opening this issue, will research more next time.

**Comment by rstoenescu** [comment]
It's ok. No worries. Was a quick one.
