### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by george-kar** [quasarframework/quasar#1754]
Is there any ready made login form layout? Of course I can create a new one from scratch but if there's anything already it will save me time.

Example: https://codesandbox.io/s/github/vuematerial/examples/tree/master/examples/login

**Comment by mesqueeb** [comment]
You could use firebase and firebase-ui. : )

Github: https://github.com/firebase/firebaseui-web
Demo: https://fir-ui-demo-84a6c.firebaseapp.com

**Comment by george-kar** [comment]
No, I mean html code (front-end) for login layout. No backend code, database or authentication manage.

**Comment by rstoenescu** [comment]
Hi, Please use Discord or forum. Github is reserved for filing in issues or requests. Thank you.
