### ISSUE TITLE
QSelect exception on null options!

### ISSUE THREAD

**Issue by mbtolou** [quasarframework/quasar#17547]
### What happened?

` const virtualScrollLength = computed(() => props.options.length)`

when options is empty . QSelect Exception Occurs!

### What did you expect to happen?

page not loaded!

### Reproduction URL

https://codepen.quasar.dev/

### How to reproduce?

QSelect with null options.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System                Windows_NT(10.0.22631) - win32/x64
NodeJs                          21.1.0

Global packages
  NPM                           10.8.2
  yarn                          1.22.19
  pnpm                          Not installed
  bun                           Not installed
  @quasar/cli                   2.4.1
  @quasar/icongenie             Not installed
  cordova                       Not installed

Networking
  Host                          sys3258
  Ethernet 2                    192.168.60.10
  vEthernet (Default Switch)    172.30.240.1
```

### Relevant log output

```Shell
QSelect.js:174  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at ComputedRefImpl.fn (QSelect.js:174:62)
    at refreshComputed (reactivity.esm-bundler.js:369:1)
    at get value (reactivity.esm-bundler.js:1687:1)
    at ReactiveEffect.getter [as fn] (reactivity.esm-bundler.js:1785:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:222:1)
    at watch (reactivity.esm-bundler.js:1907:1)
    at doWatch (runtime-core.esm-bundler.js:6168:30)
    at watch (runtime-core.esm-bundler.js:6100:1)
    at setup (QSelect.js:448:10)
    at callWithErrorHandling (runtime-core.esm-bundler.js:199:1)
```

**Comment by yusufkandemir** [comment]
It's supposed to be an array, not null
![image](https://github.com/user-attachments/assets/2d9b2ee2-c1ec-4da0-8648-04baa9c3e03e)

You can use the [nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) like this:
`:options="nullableOptions ?? []"`

**Comment by alexandre-le-borgne** [comment]
Yarn upgrade quasar 2.16 > 2.17

![image](https://github.com/user-attachments/assets/183aa780-b64d-4a9d-9d47-b19a8fb3d551)

nice welcome. An error like "QSelect options expects an array, not null" would have been more helpful

**Comment by yusufkandemir** [comment]
We configure the prop type here:
https://github.com/quasarframework/quasar/blob/1a259ff89dfa6cdae3780b242cd6f5901bd8a661/ui/src/components/select/QSelect.js#L61-L64

Vue normally warns you if you pass wrong type, but it doesn't do it if you pass `null`
https://github.com/vuejs/core/blob/29de6f8b0bb1a604f247b0712daac29e93aa6f3e/packages/runtime-core/src/componentProps.ts#L458

So, if you pass `undefined` or `[]`, you won't face this.
