### ISSUE TITLE
Application crash after latest google chrome update

### ISSUE THREAD

**Issue by mirkofisic** [quasarframework/quasar#17558]
### What happened?

I am using Quasar 2.17.0, and after the latest Google Chrome update (version 129.0.6668.90 (Official Build) (arm64)), my application just stopped working. SSR (Server-Side Rendering) executes successfully, and there are no errors on the server. However, when the client-side should activate, the application freezes, and I don't get any errors in the browser console. Has anyone experienced something similar?

### What did you expect to happen?

to work normally

### Reproduction URL

https://zip.radio

### How to reproduce?

go to provided link and app will freez whne client side need to be activated.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SSR Mode

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
Everything is covered by the drawer backdrop, so your clicks don't pass through:
![image](https://github.com/user-attachments/assets/8774c5a0-9b8e-43bd-8b5c-480284faef8a)
You can check out your layout/drawer-related code and confirm they work correctly.

It's not specific to the latest Chrome update, you can try it out with other browsers if you wish.

**Comment by mirkofisic** [comment]
@yusufkandemir the issue I'm experiencing is not related to the drawer itself. The problem appears when I update Chrome: the drawer, the map, and several other components are missing, but there are no visible errors in the console or on the server.

The strange part is that I haven’t deployed any changes; the application has been running fine all this time. However, after updating Chrome, it seems to break the rendering of these components.

Additionally, when I run the application in development mode with SSR (server-side rendering) enabled, Chrome constantly refreshes the index page, and I can’t figure out the cause. This constant refreshing only happens in Chrome, while other browsers (like Firefox) seem to work fine.

Could you provide insights or suggestions on why Chrome is behaving this way and what might be causing these missing components or constant refreshes?

**Comment by yusufkandemir** [comment]
@mirkofisic I would check `Platform` and `Cookies` plugin usage. I would also check for any pending logic, e.g. API calls, timers, logic that waits until an element is loaded in the DOM or grows to a certain size (e.g. ScrollObserver)
