### ISSUE TITLE
[carousel] Unexpected scrollbars appear

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar#1755]
Quasar: v0.15.6
OS: Windows
Node: 9.6.1
NPM: 5.6.0
Browsers: chrome

Unexpected scroll bar appears when using fit class

````
    <q-carousel
      arrows
      class="fit"
      style="height: 100%"
    >
      <q-carousel-slide
        v-for="n in 7" :key="`car-${n}`"
        class="fit"
        style="height: 100%"
      >
        <img src="xxxxx" class="fit" style="height: 100%">
      </q-carousel-slide>

   </q-carousel>
````

https://github.com/quasarframework/quasar/blob/dev/src/components/carousel/QCarouselSlide.js

````
      staticClass: 'q-carousel-slide relative-position scroll',
````
? scroll

**Comment by pdanpdan** [comment]
Please provide a reproducible test case using one of:
- https://jsfiddle.net/rstoenescu/waugrryy/ (jsFiddle - Material theme)
- https://jsfiddle.net/rstoenescu/7gu065yg/ (jsFiddle - iOS theme)
- https://codepen.io/rstoenescu/pen/KQRZJg (Codepen - Material theme)
- https://codepen.io/rstoenescu/pen/paVpBN (Codepen - iOS theme)

as per the issue template.

**Comment by pinghe** [comment]
https://github.com/pinghe/issues/blob/master/README.md

a reproducible test case:
https://github.com/pinghe/issues.git

Referring to https://stackoverflow.com/questions/7049875/height-100-not-working content, I added style="height:100%" to all parent elements of carousel.

Modified the following files:

````
Index.template.html
App.vue
Default.vue
Index.vue
````

The final effect is as follows:
https://github.com/pinghe/issues/blob/master/README.md

**Comment by pdanpdan** [comment]
Just missuse - check https://github.com/pinghe/issues/pull/1

**Comment by pinghe** [comment]
thk
