### ISSUE TITLE
Quasar plugin options allow partial directives list

### ISSUE THREAD

**Issue by rasmus0201** [quasarframework/quasar#17554]
### What happened?

Kind of a continuation of https://github.com/quasarframework/quasar/issues/17466 - and the suggested solution https://github.com/quasarframework/quasar/issues/17466#issuecomment-2349227283. 

When registering directives for global usage, TypeScript complains when we only need to register some of the directives Quasar has. It doesn't make sense that you can't register a single directive for global usage.

TypeScript gives the following explanation: `Type '{ vClosePopup: ClosePopup; }' is missing the following properties from type 'QuasarDirectives': vIntersection, vMorph, vMutation, vRipple, and 6 more.`

### What did you expect to happen?

No TypeScript error and the ability to only register some directives. 

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-tgtwe3?file=src%2Fmain.ts

### How to reproduce?

1. Go to the provided reproduction
2. Look at the TypeScript error in `main.ts`

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

TypeScript Support

**Comment by yusufkandemir** [comment]
The correct way is `{ ClosePopup }`/`{ ClosePopup: ClosePopup }`. So, the problem was not just everything being required. But, it will now be correctly typed in both aspects, thanks for reporting.

The fix will be included in `quasar` v2.17.1.

**Comment by rasmus0201** [comment]
Thank you!
