### ISSUE TITLE
QPageScroller doesn't work when inside QScrollArea

### ISSUE THREAD

**Issue by iamjuanguillermo** [quasarframework/quasar#17569]
### What happened?

I'm trying to place a QPageScroller inside a QScrollArea. When rendering, only a commented line appears in the spot where the QPageScroller should be rendered.

When I change the `<q-scroll-area>` to `<q-infinite-scroll>` or even to `<div>`, the QPageScroller renders and works fine

### What did you expect to happen?

I hope to be able to use QPageScroller inside a QScrollArea, or at least understand why it doesn't work.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-bumksg?file=src%2Flayouts%2FMainLayout.vue

### How to reproduce?

This is the example code I'm using, inside MainLayout.vue:

```
<template>
  <q-layout view="lHh Lpr lFf">
    <q-page-container>
      <q-page padding>
        <q-scroll-area style="height: 100vh">
          <p v-for="n in 15" :key="n">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit nihil
            praesentium molestias a adipisci, dolore vitae odit, quidem
            consequatur optio voluptates asperiores pariatur eos numquam rerum
            delectus commodi perferendis voluptate?
          </p>

          <q-page-scroller
            position="bottom-right"
            :scroll-offset="150"
            :offset="[18, 18]"
          >
            <q-btn fab icon="keyboard_arrow_up" color="accent" />
          </q-page-scroller>
        </q-scroll-area>
      </q-page>
    </q-page-container>
  </q-layout>
</template>
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
» Dev mode............... spa
 » Pkg quasar............. v2.17.0
 » Pkg @quasar/app-vite... v1.10.0
 » Browser target......... es2019|edge88|firefox78|chrome87|safari13.1
```

### Additional context

I've tested it with Quasar 1.6.0 and 1.7.0, and it doesn't work with either version.

**Comment by rstoenescu** [comment]
Hi,

Sorry, but the QPageScroller is meant to be used for the QPage itself, not for inner self-containers.
