### ISSUE TITLE
build-electron offline

### ISSUE THREAD

**Issue by firstdeepfeel** [quasarframework/quasar#17579]
### What happened?

When I package an electron in an offline model, I get the error 'electron/packager could not build' Getaddrinfo ENOTFFOUND GitHub. After successfully packaging it on a computer with a network, I copied the npm cache and npm to the internal network computer, as well as the node modules All offline resources are ready
/`npm WARN config production Use `--omit=dev` instead.

added 182 packages in 13m

14 packages are looking for funding
  run `npm fund` for details
 App • Bundling app with electron/packager...

 App • ⚠️   FAIL  electron/packager could not build

RequestError: getaddrinfo ENOTFOUND github.com

undefined

 App • ⚠️   FAIL  Failed to finalize build (check the log above)`

### What did you expect to happen?

build successful

### Reproduction URL

https://codesandbox.io/p/devbox/ywtlc4?file=%2Fpackage.json

### How to reproduce?

1. Copy the packaged NPC cache to an offline computer
2. Copy the packaged node modules to an offline computer
3. Run build electron with an offline computer

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Electron Mode

### Platforms/Browsers

Electron

### Relevant log output

```Shell
npm WARN config production Use `--omit=dev` instead.

added 182 packages in 13m

14 packages are looking for funding
  run `npm fund` for details
 App • Bundling app with electron/packager...


 App • ⚠️   FAIL  electron/packager could not build

RequestError: getaddrinfo ENOTFOUND github.com

undefined

 App • ⚠️   FAIL  Failed to finalize build (check the log above)
```

**Comment by rstoenescu** [comment]
Hi,

This should be reported to the `@electron/packager` team. We have no control over it. Thank you.
