### ISSUE TITLE
The icon named 'r_mobiledata' in 'material-icons' could not display

### ISSUE THREAD

**Issue by capjck** [quasarframework/quasar#17575]
### Description

Cause of the name 'r_mobiledata' start with 'r_', it was replaced to 'mobiledata'

### Flavour

None

### Areas

Components (quasar), Quasar Extras (@quasar/extras)

**Comment by yusufkandemir** [comment]
`r_mobiledata` is not in `material-icons`, it's in `material-icons-round`.

https://quasar.dev/vue-components/icon#webfont-usage
![image](https://github.com/user-attachments/assets/c4ee7580-07af-4127-afe5-ae02079b450e)

Not sure what specific problem you are facing or what you mean as you didn't give any context. So, no further action can be taken unless you provide more information.
