### ISSUE TITLE
QEditor - Toolbar Button Requires Typing to Disable

### ISSUE THREAD

**Issue by ZyataIT** [quasarframework/quasar#17570]
### What happened?

If I enable a toolbar button in the QEditor, it cannot be disabled until I type a character. 

### What did you expect to happen?

It should be possible to disable the button without having to type, for example, if I decide not to write in bold.

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

Open a QEditor field, such as the one on https://quasar.dev/vue-components/editor/
Click on the bold button in the toolbar.
Without typing any character, click the bold button again.
Result: The bold button does not get disabled.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

We are relying on the native document.queryCommandState() for the retrieving the current state and document.execCommand() to apply the state, so we depend on the browser implementation. Unfortunately we cannot change this.
