### ISSUE TITLE
CodeSandBox template broken

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#17576]
### Description

On the [Quasar Playground page](https://quasar.dev/start/playground/) the [CodeSandBox template](https://codesandbox.quasar.dev/) does not work:

![image](https://github.com/user-attachments/assets/fdc3919e-cc8d-4ff0-a5e7-5318975b465d)

### Documentation Section URL

https://quasar.dev/start/playground/

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

Thanks for notifying us. The template had many obsolete things in it.
Fixed it and upgraded it to the latest & greatest.
