### ISSUE TITLE
Dialog  -  persistent close focus issue

### ISSUE THREAD

**Issue by maulik231** [quasarframework/quasar#17585]
### What happened?

I have used q-dialog with persistent below is my code

<q-dialog v-model="showTaskModal" persistent>
  <q-card>
    <q-card-actions>
      <q-btn square
          dense
          label="Edit"
          @click="editEvent">
        </q-btn>
        <q-btn square
          dense
          label="Add"
          @click="addEvent">
        </q-btn>
          <q-btn square
          dense
          v-close-popup
          label="close"
          @click="closeEvent">
        </q-btn>
    </q-card-actions>
    etc...
  </q-card>
</q-dialog>

When I click outside of the modal then its focus first button (edit button) abuse is the portability to focus close icon

### What did you expect to happen?

when using dialog with persistent and clicking outside, focus on the close button, not any other buttons because I use persistent which means to focus on the v-close-popup button

### Reproduction URL

https://codepen.io/maulik-gaming/pen/PoMjmzb

### How to reproduce?

When opening a dialog with a persistent modal and clicking outside, the focus should shift from the first button to the close button.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Hi,

From a framework perspective, we cannot reliably infer what button or element to focus in this scenario. That would be a Chat-GPT problem due to the complexity of possible Dialog content :)

What gets focused is the first "focusable" element (of any type) of the Dialog. Hope you can now see why.
