### ISSUE TITLE
[Datetime Input] The cancel button changes the value

### ISSUE THREAD

**Issue by poncot** [quasarframework/quasar#1758]
### Software version

Quasar: 0.15.6

### What did you get as the error?

The cancel button of the Datetime Input changes the value.

**Comment by pdanpdan** [comment]
Can you please provide a code to check? Use one of the preconfigured ones in issue template

**Comment by rossity** [comment]
https://jsfiddle.net/hesu7sbx/1/

If you "set" anything like a new day/hour/etc. and then click cancel it still sets the model info. Also "change" events are being fired just when changing anything in the component as opposed to only after clicking the "Set" button.

**Comment by rstoenescu** [comment]
Fixed in 0.15.7.
