### ISSUE TITLE
Can't find stylesheet to import in 'sassVariables' after update @quasar/vite-plugin from v1.7.0 to v1.8.0.

### ISSUE THREAD

**Issue by howbizarre** [quasarframework/quasar#17592]
### What happened?

After updating @quasar/vite-plugin, it is starting to show an error: [plugin:vite:css] [sass] Can't find stylesheet to import.
If the version reverts to 1.7.0, everything starts working normally.

### What did you expect to happen?

Don't get an error.

### Reproduction URL

https://codesandbox.io/p/devbox/practical-architecture-x4lygw?file=%2Fsrc%2Fmain.ts%3A1%2C1

### How to reproduce?

I have a Vite with Vue app with Quasar added.

```
 "dependencies": {
    "@quasar/extras": "^1.16.11",
    "axios": "^1.6.8",
    "pinia": "^2.1.7",
    "quasar": "^2.15.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@quasar/vite-plugin": "^1.6.0",
    "@types/node": "^22.0.0",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vue/tsconfig": "^0.5.1",
    "sass": "^1.79.5",
    "typescript": "^5.4.5",
    "vite": "^5.2.8"
  }
```

After update it seas that `Can't find stylesheet to import` from quasar option in vite.config.ts
```
    quasar({
      sassVariables: "./src/sass/quasar/_quasar.scss",
    }),
```

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System                        Windows_NT(10.0.19045) - win32/x64
NodeJs                                  20.12.2

Global packages
  NPM                                   10.9.0
```

**Comment by rstoenescu** [comment]
Hi,

This is an unforeseen side-effect of latest Sass. Please use the full path instead (use `path.resolve()` etc.)

**Comment by howbizarre** [comment]
@rstoenescu cool... thank you.

**Comment by joesavage-silabs** [comment]
FYI the documentation needs to be updated to show the right way to reference the path.

Currently still shows

`quasar({
    sassVariables: 'src/quasar-variables.sass'
  })`
