### ISSUE TITLE
QSelect lazy loading example

### ISSUE THREAD

**Issue by Bjornvdb** [quasarframework/quasar#17598]
### Description

The lazy loading example for QSelect on the documentation page does not work.

This is a screenshot of the example:
<img width="623" alt="image" src="https://github.com/user-attachments/assets/8bb45f44-4bfd-40bf-b556-aa78029ae437">

Looking at the console, there is an error that is getting logged.

<img width="557" alt="image" src="https://github.com/user-attachments/assets/0cb41839-1080-4c19-9ebb-56762e56c482">

I also tried to open the codepen link of the example, but no QSelect is being rendered.

### Documentation Section URL

https://quasar.dev/vue-components/select#lazy-loading

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.17.2
