### ISSUE TITLE
body styles ignored on default.vue layout

### ISSUE THREAD

**Issue by george-kar** [quasarframework/quasar#1759]
I have tried to add body background change on layout default.vue

<style lang="stylus">
body
    background-color: red
</style>

and it doesnt work. I manually created a new layout and I assigned to login route

{
        path: '/login',
        component: () =>
            import ('layouts/loginlayout')
    },

On loginlayout.vue I can overwrite the body background. But why its not working on default.vue?

**Comment by pdanpdan** [comment]
Because I think the css is scoped in that component. Use a bg-color class on body or put that style in the global css
