### ISSUE TITLE
Left icon with full width button

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#176]
First, I have to congratulate you for the excellent work you have been doing with the Quasar Framework. It looks beautiful and functional! The VueJS community thanks you for all your hard work. Very good!

Now comes the question: How do I get the icon on the left side of a button with "full-width" class?

Thank you for your feedback.

**Comment by xereda** [comment]
[http://g.recordit.co/61Y5Xcge2L.gif](url)

**Comment by rstoenescu** [comment]
Please use the forum for questions http://forum.quasar-framework.org/

Here's the answer. It's a bit heavy on markup to build your example, but you can make a component if you use it throughout the UI:

```html
<button class="primary row items-stretch" style="width: 100%">
   <div><i>book</i></div>
   <div class="auto row items-center justify-center">Some text</div>
</button>
```
