### ISSUE TITLE
Change default v-touch-hold duration until event

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1760]
Currently at 800ms before the `v-touch-hold` handler event runs. I'd like to set this to 600ms.

**Comment by dennythecoder** [comment]
Tend to agree.  Had to implement my own to get around it.  Maybe it'd be good to make configurable?  800ms as a default is a bit lengthy though IMO.

**Comment by mesqueeb** [comment]
I think so too... 600 ms is much better IMO.

**Comment by pdanpdan** [comment]
You should just use v-touch-hold:600="handler"
