### ISSUE TITLE
iconMapFn not working when using in Quasar Vue plugin options

### ISSUE THREAD

**Issue by crazynds** [quasarframework/quasar#17612]
### What happened?

Funtion passed for map icons is not beeing called.

### What did you expect to happen?

The function beeing called.

### Reproduction URL

https://codepen.io/Crazynds/pen/ZEgoyga

### How to reproduce?

1. Set iconMapFn in `app.use(Quasar, { iconMapFn: () => { /* ... */ } })` like [this docs](https://quasar.dev/vue-components/icon#custom-mapping) said.
2. Test that this function is never called.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by rstoenescu** [comment]
Hi,

Yes, it's a mistake in the docs. It's actually:

```
app.use(Quasar, {
  config: {
    iconMapFn: icon => { ... }
  },
```

**Comment by rstoenescu** [comment]
Fix will be available in docs on next deployment.
