### ISSUE TITLE
Unable to add authorization header in QUploader

### ISSUE THREAD

**Issue by mike392** [quasarframework/quasar#1761]
### Software version

Quasar: 0.14.4
OS: Win 7 x64
Node: 8.4.0
NPM: 5.3.0
Browsers: Chrome 64.0.3282.186
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
I got an unauthprized response (401) when trying to upload locally a file to Spring REST endpoint.
When I try to make request.getHeader("Authorization") on BasicAuthenticationFilter there is null.

### What were you expecting?
I'm expecting to add a header to request - {Authorization: Basic ...}

### What steps did you take, to get the error?
Here's the code of a Vue-component:

![image](https://user-images.githubusercontent.com/16647651/37340260-91d1a270-26ce-11e8-8d5c-52bc57341f66.png)

I've tried various stuff with settings :headers option but no luck. In the debugger 
I tried to add other headers as well.
![image](https://user-images.githubusercontent.com/16647651/37341543-d2dbb284-26d2-11e8-919a-6d147a96628d.png)

But all I can see is that access-control-request-headers is set to Authorization and stuff.
![image](https://user-images.githubusercontent.com/16647651/37341504-a89a8964-26d2-11e8-859f-af5d63c1a6a7.png)

Can you, please, advise how can I upload files directly via Quploader passing the authentication?

**Comment by pdanpdan** [comment]
What you are inspecting in java is the preflight request (the one with method OPTIONS).
You should process preflight requests in your application and send the correct response (including CORS header response).
It has nothing to do with Quasar.

**Comment by mike392** [comment]
Surely this is similar to what was here - https://stackoverflow.com/questions/41075850/how-to-configure-cors-and-basic-authorization-in-spring-boot

Thank you!
