### ISSUE TITLE
disabled q-file show hidden html original input with opacity 0.6 in version 2.17.1

### ISSUE THREAD

**Issue by 313ava** [quasarframework/quasar#17616]
### What happened?

When I disabled a q-file, the original HTML input with type file is showed with opacity 0.6 near the label. This bug comes with 2.17.1 where in 2.17.0 everything was OK.

### What did you expect to happen?

the original HTML input should not be shown.

### Reproduction URL

https://codepen.io/313ava/pen/YzmjPWB

### How to reproduce?

visit the provided link

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.17.2.
