### ISSUE TITLE
QSelect document label and html props under #option slot scope

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#17619]
`html` and `label` is available in the scope:
https://github.com/quasarframework/quasar/blob/a6b812ee1ce2e0147c6326546204579fa94dc09e/ui/src/components/select/QSelect.js#L360-L361

but, it's not documented in the JSON API

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in Quasar v2.17.3
