### ISSUE TITLE
QExpansion SSR mismatch on style

### ISSUE THREAD

**Issue by opsec-infosec** [quasarframework/quasar#17626]
### What happened?

Expansion causes a hydration mismatch on style.

<img width="1162" alt="Screen Shot 2024-11-07 at 18 16 58" src="https://github.com/user-attachments/assets/7d023cc4-2222-4448-8d77-f09a20eb25c5">

### What did you expect to happen?

No mismatch error

### Reproduction URL

https://stackblitz.com/edit/quasarframework-stackblitz-templates-cgbpbv?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1.  compile in production
2. quasar build -m ssr
3. cd dist/ssr
4. node index.js
5. open chrome console and verify error

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(5.0 (Macintosh)) - linux/x64
NodeJs - 18.20.3

Global packages
  NPM - 10.2.3
  yarn - 1.22.19
  pnpm - 8.15.6
  bun - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.0-beta.24 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.13 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.12 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.5
  pinia - Not installed
  vuex - Not installed
  vite - 5.4.10 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 8.57.1 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.24.0 -- The cross-platform WebAssembly binary for esbuild, a JavaScript bundler.
  typescript - Not installed
  workbox-build - Not installed
  register-service-worker - Not installed
  electron - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - quasarframeworkstackblitztempl-0ixd
  en0 - 192.168.1.104
```

### Additional context

The mismatch only shows up during production mode and will not show with quasar dev -m ssr

**Comment by rstoenescu** [comment]
This is a Vue bug https://github.com/vuejs/core/issues/12162
Please use Vue 3.4.20 until this regression gets a fix. Thank you.
