### ISSUE TITLE
button toggle styling breaking when selecting last element

### ISSUE THREAD

**Issue by Seamus-Ohhhh** [quasarframework/quasar#17621]
### What happened?

When user selects the last element in a button toggle the borders at top-right and bottom right are getting set to 0. 
it seems to be due to a hidden input getting added within the button group causing the final button item to not be last-child anymore. 

This is only seems to happen when the button is inside a form and can be see in the [documentation](https://quasar.dev/vue-components/button-toggle#native-form-submit) example for native form submit

pre selection
![image](https://github.com/user-attachments/assets/5a38eaf8-ed88-43d9-8932-cd993c69913c)

post selection
![image](https://github.com/user-attachments/assets/508fdeb8-dc54-4d4b-9193-0f34d3fdb7cc)

### What did you expect to happen?

button borders styling should not change when button is selected or not

### Reproduction URL

https://jsfiddle.net/7z4wqpoj/

### How to reproduce?

1. click on the last item in both button toggle groups
2. see that toggle group inside of the form is adding hidden input

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron, Other

### Quasar info output

```Shell
Operating System        Linux(6.8.0-47-generic) - linux/arm64
NodeJs                  20.17.0

Global packages    
  NPM                   10.8.3
  yarn                  1.22.22
  pnpm                  9.9.0
  bun                   Not installed
  @quasar/cli           2.4.1
  @quasar/icongenie     Not installed
  cordova               Not installed
```

### Relevant log output

```Shell
N/A
```

### Additional context

I've had a play around locally and if i change the quasar styling selectors that is causing this from 

`.q-btn-group > .q-btn-item:not(:last-child)`

to

`.q-btn-group > .q-btn-item:not(:last-of-type)`

the issue is not visible but then this causes issues when using the button group component with a button [dropdown](https://quasar.dev/vue-components/button-group#example--with-qbtndropdown)

**Comment by rstoenescu** [comment]
Should be fixed in v2.17.2 (just released it an hour ago)
