### ISSUE TITLE
[q-expansion-item] expand-separator is only visible when surrounded by other elements

### ISSUE THREAD

**Issue by microrache** [quasarframework/quasar#17629]
### What happened?

In a `<q-expansion-item>` the attribute `expand-separator` only displays visible horizontal separators in expanded-state, when the `<q-expansion-item>` itself is surrounded by other HTML-elements. If the `<q-expansion-item>` is the first element within its parent, the top separator is invisible. The same occurs to the bottom separator if the `<q-expansion-item>` is the last element within its parent.

### What did you expect to happen?

The expand-separators being visible independent of its position within its parent-element.

### Reproduction URL

https://jsfiddle.net/au94L8kr/

### How to reproduce?

1. Visit the provided Reproduction URL
2. Expand the four provided expansion-items
3. Inspect which separators are visible and which aren't (also described in the caption)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Microsoft Edge

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22635) - win32/x64
NodeJs - 18.16.1

Global packages
  NPM - 8.12.1
  yarn - Not installed
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.10.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.13 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.12 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.5
  pinia - 2.2.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.18 -- Native-ESM powered web dev build tool
  eslint - Not installed
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
Hi,

The QExpansionItem is designed to be surrounded by other QExpansionItems, just like we are showing in docs. But you're breaking that by wrapping in QCardSection. Btw, if that's all you want, you can directly place QExpansionItem under QCard and it'll play nicely.

However, if you really want it to work like in your example, you could play with the `q-expansion-item--expanded` CSS class that gets attached to the QExpansionItem when it is expanded.
