### ISSUE TITLE
Sass deprecation warning in  "quasar 2.15.4"

### ISSUE THREAD

**Issue by aroojishfaq** [quasarframework/quasar#17636]
### What happened?

I recently updated quasar from version 2.0.0 to  "quasar": "2.15.4".
Everything seems fine except for the warning I am getting:
 App •  WARNING  •  UI  in ./node_modules/quasar/dist/quasar.sass

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 3425, column 2 of file:///D:/Projects/Monolets%20Latest/cloud-systems-web-ui/node_modules/quasar/dist/quasar.sass:3425:2:
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

3425 |   box-sizing: border-box

..\..\..\quasar\dist\quasar.sass 3426:3  root stylesheet

### What did you expect to happen?

Not get any warnings or errors.

### Reproduction URL

- https://codesandbox.io/ (dummy)

### How to reproduce?

- Try using quasar 2.15.4 and check if the same sass deprecated issue occurs.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

**Comment by yusufkandemir** [comment]
That specific issue was fixed in v2.16.6. To ensure everything related SASS works fine, ensure your `quasar` package and `@quasar/app-vite`/`@quasar/app-webpack` is up-to-date. Also, remember to check the release notes.

Please do not open such issues without testing the latest version, thanks.
