### ISSUE TITLE
Route change from <q-btn> inside <form>

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1763]
### Software version

Quasar: 0.15.6

### What did you get as the error?

The app performs a full reloading and goes back to the current route.

### What were you expecting?

Working redirect to another route.

### What steps did you take, to get the error?

1. Add a `<form>...</form>` element
2. Add a `<q-btn @click="$router.push('/...')"/>` inside the form element
3. Click on the button

**Comment by rstoenescu** [comment]
You probably wrapped it in a `<form>` element. In such case, you need to disable the default browser behavior on it.

`<form @submit.prevent>`

**Comment by zuck** [comment]
Yes, this is actually the reason. The point is that I think we should add a note to the docs about that.
