### ISSUE TITLE
Pinch-to-zoom not working on Android Chrome; scrolling occurs instead

### ISSUE THREAD

**Issue by quillcraftsman** [quasarframework/quasar#17643]
### What happened?

Hello,

I have encountered an issue where "pinch-to-zoom" functionality does not work on my website built with Vue and Quasar when accessed on Android devices using the Chrome browser. Instead of zooming in or out, the page scrolls. I have the same problem on [quasar.dev](https://quasar.dev/)

### What did you expect to happen?

The page should zoom in or out as expected.

### How to reproduce?

Open the website [quasar.dev](https://quasar.dev/)  on an Android device using the Chrome browser.
Attempt to zoom in or out using the "pinch-to-zoom" gesture.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Android

### Additional context

Quasar version: `2.16.4`
Chrome browser version:`131.0.6778.39`
Android version: `14`

**Comment by quillcraftsman** [comment]
I've deleted the reproduction URL because it's not about code but about interacting with the devices.

**Comment by FangHanZreo** [comment]
This issue might be related to the meta configuration in the index.template.html file.

```
<meta
      name="viewport"
      content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width<% if (ctx.mode.cordova || ctx.mode.capacitor) { %>, viewport-fit=cover<% } %>"
    />
```

**Comment by rstoenescu** [comment]
Changing that may have undesirable effects on the QLayout, but tweaking that meta tag in the index html file will do the trick. However, beware of the effects.

**Comment by quillcraftsman** [comment]
Got it, thanks. I will try it soon as possible and come back with feedback.

**Comment by quillcraftsman** [comment]
> This issue might be related to the meta configuration in the index.template.html file.
> 
> ```
> <meta
>       name="viewport"
>       content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width<% if (ctx.mode.cordova || ctx.mode.capacitor) { %>, viewport-fit=cover<% } %>"
>     />
> ```

It works fine. Thanks a lot for your help.

**Comment by Vv-vfx** [comment]
> Changing that may have undesirable effects on the QLayout, but tweaking that meta tag in the index html file will do the trick. However, beware of the effects.

This helps, but the problem is that now when focusing on the input field, autozoom works. And after the input is finished, reverse zoom does not work. Device - iPhone
