### ISSUE TITLE
svg<type>Grade removed. Use svg<type>Star. Used in iconsets as "rating".

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#17640]
### Discussed in https://github.com/quasarframework/quasar/discussions/17632

<div type='discussions-op-text'>

<sup>Originally posted by **yaourt** November 10, 2024</sup>
I'm trying to change the iconSet in quasarconfig to `'svg-material-symbols-outlined'` but then it gives me the following when doing a `quasar dev` or `quasar build`:

`node_modules/.pnpm/quasar@2.17.2/node_modules/quasar/icon-set/svg-material-symbols-outlined.js:64:2: ERROR: No matching export in "node_modules/.pnpm/@quasar+extras@1.16.13/node_modules/@quasar/extras/material-symbols-outlined/index.mjs" for import "symOutlinedGrade"`

Is there a mistake on my side ?
or is this an issue with the icon named `grade` in `material-icons` that does not exist anymore in `material-symbols-*` ?</div>

**Comment by hawkeye64** [comment]
Will be resolved in the next release.

**Comment by yaourt** [comment]
Thanks for this update 👍 

But I'm wondering if quasar-extras needs also an update.

I'm trying to not use material-design-icons font at all, and instead use the svg-material-symbols-outlined iconSet.

This gives me:

`node_modules/.pnpm/quasar@2.17.3/node_modules/quasar/icon-set/svg-material-symbols-outlined.js (64:2): "symOutlinedGrade" is not exported by "node_modules/.pnpm/@quasar+extras@1.16.13/node_modules/@quasar/extras/material-symbols-outlined/index.mjs", imported by "node_modules/.pnpm/quasar@2.17.3/node_modules/quasar/icon-set/svg-material-symbols-outlined.js".`

**Comment by yaourt** [comment]
Oh, in fact there is no change in the dev branch.

There is a warning at the top of the modified files saying that those files are generated, the edit should have been in material-symbols-<type>.js (and not in their svg- counterparts) !

**Comment by rstoenescu** [comment]
Will be fixed in Quasar v2.17.4

**Comment by hawkeye64** [comment]
> Will be fixed in Quasar v2.17.4

Nice catch!
