### ISSUE TITLE
App extension with symbolic link in package.json throws error App Extension "generic-components-service" has missing index script...

### ISSUE THREAD

**Issue by bizmarker** [quasarframework/quasar#17655]
### What happened?

When running `quasar prepare`, an app extension that is linked via file:// in package.json throws exception that there is a missing index script. 

### What did you expect to happen?

prepare would complete with success

### Reproduction URL

Cannot use reproduction URL for app extension issue

### How to reproduce?

1. npm add --save-dev file:../../Code/CommonLib/WebClientLib/quasar/app-extensions/generic-components-service
2. quasar ext invoke generic-components-service
3. quasar prepare

Error thrown:

App • ⚠️  App Extension "generic-components-service" has missing index script...

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

App Extension API

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Linux(5.14.0-284.30.1.el9_2.x86_64) - linux/x64
NodeJs - 20.18.0

Global packages
  NPM - 10.8.2
  yarn - Not installed
  pnpm - Not installed
  bun - Not installed
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.0-rc.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.13 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.13 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.5
  pinia - 2.2.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 5.4.11 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 8.57.1 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.24.0 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.4 -- TypeScript is a language for application scale JavaScript development
  workbox-build - Not installed
  register-service-worker - Not installed
  electron - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-vitest - 1.1.0 -- A Quasar App Extension for running tests with Vitest
  quasar-app-extension-generic-components-service - 0.0.1 -- Web client common library
```

### Additional context

package.json:

`{
  "name": "testwebclient",
  "version": "0.0.1",
  "description": "Test Web Client",
  "productName": "Test Web Client",
  "author": "test@test.com",
  "type": "module",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.ts,.vue ./",
    "format": "prettier --write \"**/*.{js,ts,vue,scss,html,md,json}\" --ignore-path .gitignore",
    "test": "echo \"No test specified\" && exit 0",
    "dev": "quasar dev",
    "build": "quasar build",
    "postinstall": "quasar prepare"
  },
,
  "dependencies": {
    "@quasar/extras": "^1.16.4",
    "axios": "^1.2.1",
    "pinia": "^2.0.11",
    "quasar": "^2.16.0",
    "vue": "^3.4.18",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@intlify/unplugin-vue-i18n": "^2.0.0",
    "@quasar/app-vite": "^2.0.0-rc.3",
    "@quasar/quasar-app-extension-testing-unit-vitest": "^1.1.0",
    "@types/node": "^20.5.9",
    "@typescript-eslint/eslint-plugin": "^7.16.0",
    "@typescript-eslint/parser": "^7.16.0",
    "autoprefixer": "^10.4.2",
    "eslint": "^8.57.1",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-vue": "^9.0.0",
    "prettier": "^3.0.3",
    "quasar-app-extension-generic-components-service": "file:../../Code/CommonLib/WebClientLib/quasar/app-extensions/generic-components-service",
    "typescript": "~5.5.3",
    "vite-plugin-checker": "^0.8.0",
    "vitest": "^2.1.5",
    "vue-tsc": "^2.0.29"
  },
  "engines": {
    "node": "^24 || ^22 || ^20 || ^18",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}
  
`
quasar.extensions.json:
`{
  "@quasar/testing-unit-vitest": {
    "options": [
      "ui"
    ]
  },
  "generic-components-service": {}
}
`

**Comment by Dtsiantaris** [comment]
Did you find a solution to this?

I am getting same error when trying to build inside a CI

**Comment by yusufkandemir** [comment]
> Cannot use reproduction URL for app extension issue

Cannot provide help with no useful information. You can create a GitHub repo and put a project and AE code there, or at least provide some AE code.

All I can say is that, if your extension is ESM-based, depending on your needs, either don't specify `exports` or make sure it matches this structure: https://github.com/quasarframework/quasar/blob/a0e0c7602ddb88595d5e277f2952628f9b9bda43/create-quasar/templates/app-extension/ae-ts/BASE/app-extension/_package.json#L17-L28

**Comment by DouglasCalora** [comment]
any news?

**Comment by yusufkandemir** [comment]
@DouglasCalora, there is no info or reproduction. So, unless someone provides one, there won't be any news.
