### ISSUE TITLE
Unit Tests in Repo

### ISSUE THREAD

**Issue by dennythecoder** [quasarframework/quasar#1765]
Howdy!

I've been developing with Quasar since 0.13 and I absolutely love it.  Diving into the source, I can't seem to find any tests and I was hoping that I might be able to contribute to the project by writing some. 

I created a fork+branch at https://github.com/dennythecoder/quasar/tree/add-test with added dependencies for testing with Jest and vue-test-utils.  I wrote one small test for the QBtn component.  

If this is an acceptable course of action, I'll keep going.  I'm not married to the proposed configuration.  So, I am willing to contribute tests with other libraries.

If you clone it, install and use "jest" in the command line to run the test.

**Comment by rstoenescu** [comment]
Yes, please go ahead and continue. Thanks! Will close this ticket for now.
