### ISSUE TITLE
build a new quasar with vite  not working with httpd

### ISSUE THREAD

**Issue by luoyunpeng** [quasarframework/quasar#17661]
### What happened?

my dev environment as follow:

node： v22.11.0
npm ： 10.9.0
pnpm ： 9.14.2
quasar: @quasar/cli v2.4.1

just follow the official document "https://quasar.dev/start/quick-start" to scaffold a new quasar project using vite with nothing change , and run 'quasar build', then copy the build package  to the httpd directory,

get errors: 

> GET http://ip:port/assets/index-DMBtmvYF.js net::ERR_ABORTED 404 (Not Found)

seems the request url is not right, but if i recreate the project with webpack, rebuild  and deploy to the httpd, it works
here is my code:

> https://github.com/luoyunpeng/quasar-demo

### What did you expect to happen?

build with vite, and deploy to httpd, nothing miss, all url of js and css file are correct.

### Reproduction URL

https://github.com/luoyunpeng/quasar-demo

### How to reproduce?

1, install  the node v22.11.0 on windows 11
2. create the demo packgae with 'npm init quasar@latest'
3. choose 'App with Quasar CLI'
4. Quasar v2(Vue3)
5. JS
6. Quasar App CLI with vite2
7. Composition API with <script setup>\
8. Sass with SCSS 
9. Prettier
10. use npm

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

**Comment by rstoenescu** [comment]
Hi,

Clear the browser cache. But more important, configure your webserver’s cache more appropriately.

**Comment by luoyunpeng** [comment]
> Hi,
> 
> Clear the browser cache. But more important, configure your webserver’s cache more appropriately.

the issue has nothing to do with the browser cache and the webserver's cache config, the vite package the asset dir as the root absolute path, but the webpack package the asset dir as the relative path, so i change 'publicPath' in 'quasar.config.js' to the right absolute path, then every thing works.

**Comment by rstoenescu** [comment]
There can be multiple reasons why your problem can arise, but none related to a bug in Quasar is what I am saying.

**Comment by luoyunpeng** [comment]
thx for anwsering, by the way, how can i change the assert 'href' to the relative path? i tried to configure the base value(base: './') in 'quasar.config.js' but it does not work,
