### ISSUE TITLE
Renamed a Component, ran 'quasar dev', unknown command dev

### ISSUE THREAD

**Issue by JHeroGR** [quasarframework/quasar#17667]
### What happened?

I renamed a component from 'TodosList' to 'TodoList', renamed every other reference to it, and then I ran the command 'quasar dev' to run the UI, and was greeted with the Error Unknown command dev.

### What did you expect to happen?

After renaming the components and references, I ran the command 'quasar dev', and I should've gotten a localhost:9000/# run.

### Reproduction URL

https://github.com/JHeroGR/quasar-todo-list

### How to reproduce?

1. create quasar project
2. enter new component command (e.g. quasar new component TodosList)
3. reference the TodosList
4. rename the component name and any references from TodosList to TodoList
5. run quasar dev

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

### Quasar info output

```Shell
Operating System        Linux(5.15.167.4-microsoft-standard-WSL2) - linux/x64
NodeJs                  20.13.1

Global packages    
  NPM                   10.5.2
  yarn                  Not installed
  pnpm                  Not installed
  bun                   Not installed
  @quasar/cli           2.4.1
  @quasar/icongenie     Not installed
  cordova               Not installe
```

### Relevant log output

```Shell
quasar dev


 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

  Running @quasar/cli v2.4.1

  Example usage
    $ quasar <command> <options>

  Help for a command
    $ quasar <command> --help
    $ quasar <command> -h

  Options
    --version, -v Print Quasar CLI version

  Commands
    info      Display info about your machine
                   (and your App if in a project folder)
    upgrade   Check (and optionally) upgrade Quasar packages
                   from a Quasar project folder
    serve     Create an ad-hoc server on App's distributables
    help, -h  Displays this message

  --------------
  => IMPORTANT !
  => Trigger this inside of a Quasar project (and npm/yarn/pnpm/bun install) for more commands.
  --------------


 Global Quasar CLI • ⚠️   Error  Unknown command "dev"
```

### Additional context

i have also removed node_modules and package-lock.json and did a npm cache clean --force, and then re-ran npm install, i still got the same error as before.

**Comment by yusufkandemir** [comment]
You don't have `@quasar/app-vite` or `@quasar/app-webpack` installed in your `package.json`. You've probably removed it by mistake.

**Comment by JHeroGR** [comment]
I didn't even touch the package.json when I renamed the component.

**Comment by yusufkandemir** [comment]
In your commit `first init, added Update, Add, and Delete functionality`, you removed it:
![image](https://github.com/user-attachments/assets/540c4e83-ee5c-4c70-a0e4-d69f937a2fe0)

As I said, it's probably by mistake and is not related to renaming the component. Just add it back, install deps, and you can continue as usual.

**Comment by JHeroGR** [comment]
that is so weird, never touched it for sure, but ok thank you
