### ISSUE TITLE
Incorrect file referenced in app-vite v2 upgrade guide

### ISSUE THREAD

**Issue by abraxxa** [quasarframework/quasar#17679]
### Description

At the end of section 2.4 the Pinia stores/index.ts file should be changed but the docs refer to it as `/src/router/index.ts` twice.

### Documentation Section URL

https://quasar.dev/quasar-cli-vite/upgrade-guide#beginning-of-the-upgrade-process

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by abraxxa** [comment]
One additional weird thing about this section is that it states that the router property is augmented automatically, but the src/stores/index.ts file generated for a new project still contains it. Might be an oversight there.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fixed both. Docs are redeploying.
