### ISSUE TITLE
ERR_WORKER_OUT_OF_MEMORY when using quasar dev with a vendor folder inside the app root

### ISSUE THREAD

**Issue by binsky08** [quasarframework/quasar#17677]
### What happened?

I tried to bootstrap a new quasar project within the root of my existing laravel project directory.
To simplify the behaviour I have tested it with a simpler composer.json creating a vendor folder with the **problematic phpunit dependency**, within the root of a new default quasar project (see reproduction URL).

Every time I start the dev server with `quasar dev` or `npm run dev`, the dev server takes 100-400% CPU usage and increases it's memory usage for about a minute until it crashes with a `ERR_WORKER_OUT_OF_MEMORY` error. (see log output)

Without the vendor folder containing the phpunit dependencies, the dev server does not crash.

### What did you expect to happen?

The dev server should run for hours without any "out of memory" caused crash.

A vendor folder within the app root should not cause the dev server to crash.

### How to reproduce?

I was not able to reproduce in a StackBlitz or Codesandbox environment.

Problematic composer.json:
```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "simplified version to get only the problematic dependencies in vendor",
    "license": "MIT",
    "require": {
        "php": "^8.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^11.0.1"
    }
}
```

1. Use any quasar project (new example project)
2. Change to the cloned folder and run `npm install`
3. Create the composer.json with the content above and run `composer install`
4. Open `htop` in a second terminal window and filter for `quasar`
5. Run `quasar dev` and wait (take a look at the cpu and memory usage in htop)
    - cpu usage of the process should be way more than idle
    - it should increase it's memory usage every ~5 seconds and crash after some minutes with `ERR_WORKER_OUT_OF_MEMORY`
6. Optional: Remove the vendor folder and run `quasar dev` again, to validate everything is fine (usual cpu and memory usage)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Platforms/Browsers

Firefox, Other

### Quasar info output

```Shell
Operating System - Linux(6.11.0-105009-tuxedo) - linux/x64
NodeJs - 23.2.0

Global packages
  NPM - 10.9.0
  yarn - Not installed
  pnpm - 9.12.3
  bun - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.0-rc.4 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.14 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.13 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.5.0
  pinia - 2.2.8 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 5.4.11 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 8.57.1 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.24.0 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.4 -- TypeScript is a language for application scale JavaScript development
  workbox-build - Not installed
  register-service-worker - Not installed
  electron - 32.2.6 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  @electron/packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - ttux14
  wlp1s0 - 192.168.120.75
  br-5dfab177f4a8 - 172.20.0.1
```

### Relevant log output

```Shell
> quasar-project@0.0.1 dev
> quasar dev


 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

 App • Using quasar.config.ts in "ts" format

 App • ⚠  Setting port to closest one available: 9001


 » Reported at............ 3.12.2024 10:16:24
 » App dir................ /home/............./quasar-project
 » App URL................ http://localhost:9001/
                           http://192.168.120.75:9001/
                           http://172.20.0.1:9001/
 » Dev mode............... spa
 » Pkg quasar............. v2.17.4
 » Pkg @quasar/app-vite... v2.0.0-rc.4
 » Browser target......... es2022|firefox115|chrome115|safari14

 App • Opening default browser at http://localhost:9001/


[vue-tsc] Found 0 errors. Watching for file changes.
node:events:485
      throw er; // Unhandled 'error' event
      ^

Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
    at [kOnExit] (node:internal/worker:313:26)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
Emitted 'error' event on Worker instance at:
    at [kOnExit] (node:internal/worker:313:12)
    at Worker.<computed>.onexit (node:internal/worker:229:20) {
  code: 'ERR_WORKER_OUT_OF_MEMORY'
}

Node.js v23.2.0
```

### Additional context

The first idea was, that the file watcher could be the problem, but even if is disable the watch option or just allow the 3 required folders to access, the problem persists.

```
          viteConf.server = mergeConfig(viteConf.server, {
              watch: null,
              fs: {
                  allow: [
                      './src',
                      './.quasar',
                      './node_modules',
                  ],
              }
          });
```

Even if I search for "vendor" in the output of `DEBUG=vite:* quasar dev` I don't get any result.

In this screenshot, the process took >4GB memory short time before the crash.
![image](https://github.com/user-attachments/assets/6ca13f78-1637-41f0-84cd-d9cae0bf781c)

Also tried:
  - with 6GB heap size with the same result
  - on my os (TUXEDO OS 3, Release 22.04, Linux(6.11.0-105009-tuxedo))
  - on an ubuntu 24.04 in docker
  - with node versions 23, 20, 18 (on both systems)
  - on a new digitalocean droplet with ubuntu 24.10 and node v20

**Comment by rstoenescu** [comment]
Hi,

This is not a Quasar CLI issue. It must be related to vite-plugin-checker which uses workers. Tamper with the ESLint configuration to ignore your /vendor folder.

**Comment by binsky08** [comment]
what the hell, it took me hours and now the solution is just a

`/vendor` in `.eslintignore`

Thank you so much @rstoenescu :heart: 
saved my day :)

**Comment by rstoenescu** [comment]
Glad I could help.
