### ISSUE TITLE
[15.7] Incorrect text position in IE11 for textarea inputs

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#1768]
Setting rows > 1 moves the text position of entry upwards the higher you set it.

Try this on IE11 at:   https://jsfiddle.net/wrw07e1k/3/

![capture](https://user-images.githubusercontent.com/27252610/37379758-5fdcea94-26f2-11e8-9541-207662aa9b8e.PNG)

Looks fine in chrome.

**Comment by pdanpdan** [comment]
I found it, it'll be in the next release.
