### ISSUE TITLE
quasar build --mode bex -T [chrome|firefox] build product does not contain www directory

### ISSUE THREAD

**Issue by LetFree** [quasarframework/quasar#17683]
### What happened?

quasar build --mode bex -T [chrome|firefox] build product does not contain www directory

### What did you expect to happen?

build bex success

### Reproduction URL

none

### How to reproduce?

@quasar/app-vite v2.0.0
quasar build --mode bex -T chrome

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

BEX Mode

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in q/app-vite 2.0.1 & q/app-webpack 4.0.1
