### ISSUE TITLE
The content of the QTabPanel component is always rendered twice when it is loaded for the first time.

### ISSUE THREAD

**Issue by FrostYen** [quasarframework/quasar#17698]
### What happened?

The content of the QTabPanel component is always rendered twice when it is loaded for the first time. This is a serious bug.

### What did you expect to happen?

The content of the QTabPanel component only needs to be rendered once.  

### Reproduction URL

https://codepen.io/FrostYen/pen/OPLROOE

### How to reproduce?

![image](https://github.com/user-attachments/assets/07a95411-d6a9-4fbf-8404-d06a6a2e56c6)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron, Other

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.17.5. The bug also impacts QCarousel & QStepper.
