### ISSUE TITLE
VueStore issue after upgrade from quasar/app-vite 2.0.0-rc.4 to 2.0.1

### ISSUE THREAD

**Issue by petr-panek** [quasarframework/quasar#17691]
### What happened?

After upgrade to from quasar/app-vite 2.0.0-rc.4 to 2.0.1 tha application can't run, showing error:

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'store.getters')
	logError (chunk-RO6UVCNO.js:2549)
	handleError (chunk-RO6UVCNO.js:2536)
	callWithErrorHandling (chunk-RO6UVCNO.js:2482)
	callWithAsyncErrorHandling (chunk-RO6UVCNO.js:2487)
	(anonymous function) (chunk-RO6UVCNO.js:4388)
	flushPostFlushCbs (chunk-RO6UVCNO.js:2657)
	render2 (chunk-RO6UVCNO.js:7226)
	mount (chunk-RO6UVCNO.js:5277)
	(anonymous function) (chunk-RO6UVCNO.js:12738)
	(anonymous function) (client-entry.js:117)

### What did you expect to happen?

Application run without errors.

### Reproduction URL

-

### How to reproduce?

-

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Safari

**Comment by petr-panek** [comment]
I will not provide reproduction URL, I don's have time to play with that.
I just wanted to warn you that something is wrong in last version compared to rc4.

**Comment by rstoenescu** [comment]
Hello,

This seems to be an error within Pinia. Nothing to do with Quasar itself. However, without a reproduction, we don't have anything to act on to determine what is actually wrong. Nothing changed from rc.4 to 2.0.1 in regards to Pinia or the boot files. Please provide a reproduction and I will reopen. Thank you.

**Comment by petr-panek** [comment]
The source of this issue is that you did "breaking change" between rc4 and stable version. 
Changes from rc4: Dropped support for Vuex
Unbeliavable :-(

**Comment by rstoenescu** [comment]
Vuex has been deprecated for years and is no longer maintained by the Vue/Vuex team. Its last release was 3.5 years ago (middle of 2021).

We've announced the deprecated use of Vuex starting with q/app-vite v1 (although we still supported it). It is time to migrate to Pinia and it will receive as much love from us as from the Vue team, ...meaning none. We should have removed support for Vuex starting with the first alpha version of q/app-vite v2.

I'm sorry that you are now being forced to switch to Pinia (it's not hard though!), but we will not hold back on dropping support for ancient & no longer maintained packages if that hinders the modernization and development of our CLIs. I hope that you understand.

**Comment by petr-panek** [comment]
Razvan, thank you for detailed response.
It's not problem to switch to Pinia. I was just surprised that this "breaking" change was done in "rc to stable version" upgrade. That's not expected. I'm sure you understand.
Let's close this.

**Comment by rstoenescu** [comment]
True. Dropping from rc can be seen as surprising. However, we should have dropped it from first alpha version. And to be completely honest, if we would have not hit a roadblock with TS for it (compounded problems) during the rc phase, we’d have made the effort to continue to support it.
