### ISSUE TITLE
import.meta.url is undefined in electron-preload.ts

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#17690]
### What happened?

Trying to get the public folder in electron-preload.ts with this code:
```Javascript
import path from 'path'
import { fileURLToPath } from 'url'

const currentDir = fileURLToPath(new URL('.', import.meta.url))

const publicFolder = path.resolve(currentDir, process.env.QUASAR_PUBLIC_FOLDER)
```

And got this error: TypeError: Failed to construct 'URL': Invalid URL

It turns out that import.meta.url is undefined.
This code runs correctly if called in electron-main.ts

### What did you expect to happen?

It should get currentDir and publicFolder as mentioned here: https://quasar.dev/quasar-cli-vite/developing-electron-apps/electron-accessing-files

### Reproduction URL

https://stackblitz.com/edit/quasarframework-stackblitz-templates-datymtds?file=src-electron%2Felectron-preload.js

### How to reproduce?

Just run `quasar dev -m electron` and the error will show in console.
Note StackBlitz doesn't allow electron js project so it actually won't run on the web page.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Electron Mode

### Platforms/Browsers

Electron

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22631) - win32/x64
NodeJs - 22.11.0

Global packages
  NPM - 10.9.2
  yarn - 1.22.19
  pnpm - Not installed
  bun - Not installed
  @quasar/cli - 2.2.3
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.15 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.13 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.5.0
  pinia - 2.3.0 -- Intuitive, type safe and flexible Store for Vue
  vite - 6.0.3 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 9.16.0 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.24.0 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.4 -- TypeScript is a language for application scale JavaScript development
  workbox-build - Not installed
  register-service-worker - Not installed
  electron - 33.2.1 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  @electron/packager - 18.3.6 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - MY-DESKTOP
  Ethernet - 192.168.68.68
```

### Relevant log output

```Shell
VM4 sandbox_bundle:2 Unable to load preload script: C:\Users\xxx\Documents\dev\clean-new-quasar-project-v2\.quasar\dev-electron\preload\electron-preload.cjs
VM4 sandbox_bundle:2 TypeError: Failed to construct 'URL': Invalid URL
    at <anonymous>:8:48
    at runPreloadScript (VM4 sandbox_bundle:2:151984)
    at VM4 sandbox_bundle:2:152281
    at VM4 sandbox_bundle:2:152436
    at ___electron_webpack_init__ (VM4 sandbox_bundle:2:152440)
    at VM4 sandbox_bundle:2:152563
```

**Comment by rstoenescu** [comment]
Hi,

Electron currently does not supports ESM for the preload script. Only in main thread. So you can use __dirname instead of constructing currentDir with import.meta.url.

**Comment by nycki93** [comment]
> Hi,
> 
> Electron currently does not supports ESM for the preload script. Only in main thread. So you can use __dirname instead of constructing currentDir with import.meta.url.

I just tried this while following a different tutorial, and __dirname is not defined in the preload script.
