### ISSUE TITLE
[suggestion] Let the initial app construct an example app

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#177]
Quasar is awesome, but for a not so experienced dev like myself, getting "into" it and understanding how the concepts work is a bit hard. The way things are constructed currently is obviously for more experienced front-end devs to take off running building an application, which is great. However, to broaden the base of acceptance, I feel the door to Quasar needs to opened a bit wider.  

My suggestion is to allow the dev to build, like PHP's Symfony frameworks offers, an example app, which can be installed through npm. (or is this already possible???)

So, what a developer would get is a simple SPA, which demonstrates 

1. How page navigation works. 
2. What implemented concepts like developed views (pages), layouts, and components look like, when they are brought together. 
3. How components interoperate between each other. 
4. How to develop with Quasar in general. 
5. And whatever other important concepts I might have missed.

I know this is a "nice to have", but I feel a novice's pathway to the inner workings and concepts is important for the growing success of any framework. I am sure it would also help even advanced developers to "dig in" faster. Obviously, documentation should accompany such an app to basically take the hand of someone new to the framework and lead them down the path to a full blown SPA. 

The example doesn't need to be a complicated app. Maybe even just a to-do app, which has two different pages and maybe a "faked" simple sign-on, I don't know. I am just throwing out ideas here. :smile: 

I am positive such an example app would be good for the framework's acceptance.

I'd also be willing to start working on this. It would be good practice for me to learn myself and instead of having 100s or even 1000's ( :smile: ) more do the same work, I can share it and possibly save a lot of people a lot of time. 

What do you think?

Scott

**Comment by rstoenescu** [comment]
Go for it. It's a good exercise for you.
Will try to make some time for a todo app myself. Will include your demo app too if you have time for it.

Will close this bug as it duplicates #3

**Comment by smolinari** [comment]
Ah. Sorry about that. I guess I could have searched if this was already suggested. 

Scott

**Comment by rstoenescu** [comment]
Don't worry ;)

**Comment by smolinari** [comment]
I'll also probably be hitting you up in the gitter chat with questions. Hopefully not too many though. :wink: Hope you won't mind.

Scott
