### ISSUE TITLE
Public assets path changes with @quasar/app-webpack v4

### ISSUE THREAD

**Issue by CamilleDrapier** [quasarframework/quasar#17708]
### What happened?

After completing the initials steps of migrating to app-webpack4 (from 3.15.0), the images in my application that are served from the "public" path do not show anymore, unless I prefix the path with `/`

### What did you expect to happen?

The images should continue showing without changing the way I use them in my scripts. 

Alternatively, there could be an entry added in the migration, and some adaptations to the "App Handling Assets" guides, stating that the `/` prefix is now the way to go? 

### Reproduction URL

https://codepen.io/camilledrapier-the-flexboxer/pen/azoJmpd

### How to reproduce?

1. Go to the provided URL
2. Check the network console
3. The two images (that can't be loaded) should have the same GET URL, and it should be directly under the domain ("public path"). Instead of this the `url2` seems to be fetched from the public path while `url1` seems to be relative to the current/parent-window URL

(I'm not sure if this test is relevant, as it might not use webpack directly?, and maybe we would have the same behavior with prior version in codepen as well)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System - Darwin(24.1.0) - darwin/arm64
NodeJs - 20.18.1

Global packages
  NPM - 10.8.2
  yarn - Not installed
  pnpm - Not installed
  bun - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 4.0.2 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.13 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.13 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.5
  pinia - 2.2.6 -- Intuitive, type safe and flexible Store for Vue
  eslint - 8.57.1 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.21.5 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.4 -- TypeScript is a language for application scale JavaScript development
  @babel/core - 7.26.0 -- Babel compiler core.
  webpack - 5.96.1 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 5.2.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 7.3.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - Not installed
  electron - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 3.0.3 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing-e2e-cypress - 6.1.0 -- A Quasar App Extension for Cypress e2e

(Please note that I am still in the middle of migrating to app-webpack4, and have not changed the eslint version yet)
```

### Relevant log output

```Shell
https://cdpn.io/cpe/boomboom/test.png // url1
https://cdpn.io/test.png // url2
```
```


### Additional context

I do not know if this is an intended change or not, but before the migration to app-webpack4, my public path references that were not prefixed with `/` appropriately were resolved to the public folder // started from the domain. I did not update anything else than `app-webpack4` in my current changes/branch.

According to [this documentation](https://quasar.dev/quasar-cli-webpack/handling-assets/#static-assets-public) the `/` prefix might work but is discouraged.

I did not find much about `asset` // `public` changes in the [migration guide](https://quasar.dev/quasar-cli-webpack/upgrade-guide), but it is possible I missed it in one of the linked resource.

**Comment by rstoenescu** [comment]
Hi,

Yes, this is the new behavior. We previously had a `<base>` tag auto-injected into the `<head>` which magically handled the paths. While this was a good feature, it also made other use-cases impossible to handle. We removed it. It now works as with q/app-vite.

However, should you want the old behavior, simply edit your /index.html and add the `<base>` tag yourself (with the same publicPath as in quasar.config -- `/` is the default) in the `<head>` of the document.

**Comment by CamilleDrapier** [comment]
Thank you for your quick response! Understood, since it is the new recommended behavior, I will change my resource references to use it! 👍 

THanks for the potential workaround as well!
