### ISSUE TITLE
Expected identifier but found "import"

### ISSUE THREAD

**Issue by cirolosapio** [quasarframework/quasar#17716]
### What happened?

i've created a new project with `pnpm create quasar`
when i run `pnpm run dev` it ends up with the error `Expected identifier but found "import"`

![image](https://github.com/user-attachments/assets/c359be51-e02d-4e78-a1c0-12838ba29fb7)

### What did you expect to happen?

app starts normally

### Reproduction URL

https://stackblitz.com/edit/quasar-issue

### How to reproduce?

1. open repro
2. pnpm run dev
3. see error

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
Noticed it too while deploying the Quasar docs.
Fixed it already in q/app-vite v2.0.4 & q/app-webpack v4.0.4

Seems to be a regression in esbuild and we instructed to always install "latest"
