### ISSUE TITLE
Touch pan directive not wokring with q-input or input elements.

### ISSUE THREAD

**Issue by Dtsiantaris** [quasarframework/quasar#17713]
### What happened?

Applying the `v-touch-pan`  on `q-input` or a simple input element(or a container that contains these elements) does not capture the swipe event. 

### What did you expect to happen?

The directive should capture the swipe events like any other element.

### Reproduction URL

https://codepen.io/dtsiantaris/pen/xbKqypY?editors=1111

### How to reproduce?

1. Go to reproduction link.
2. Trying swiping inside the grey are div.
3. Notice that when your swipe gestures start from a `q-input` or `input` the event is not captured.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Directives (quasar)

**Comment by Dtsiantaris** [comment]
I found this in the source code for the directive:

![image](https://github.com/user-attachments/assets/2cf0681f-5f80-4d9c-8345-7b5d926fc4c3)

Does this mean that touch pan is supposed to NOT work with inputs?

**Comment by rstoenescu** [comment]
Hi. Yes. It is so by design. Otherwise it would interfere with the input elements in unpredictable ways. Especially on iOS, it would be hell on Earth.
