### ISSUE TITLE
Opening Model / Drawer causes layout change

### ISSUE THREAD

**Issue by sagikarni** [quasarframework/quasar#1771]
When opening a dialog / Model or a drawer the content area are greyed out a bit (with opacity) AND the document scroll is disapearing.
This causes a slight "jump" sue to the layout change/resize.
At first glance it does not look like big issue , However from a **UX** perspective 
this is certainly a big issue.
It would be great if next release will include a fix.
Thanks
Sagi

**Comment by sagikarni** [comment]
Hi, 
Take a look at the attached files.
The first shows the page layout before the model was opened. You can see the scroll and the width of the navbar.
The second image shows the page after the model was opened. You can see that the scroll does not exists any more ans there for the nav width (and the document cotent) changed its width.
This results a behaviour which is highly not recomended from UX point of view - there is a small jump / layout change every time a model / alert / drawer are opened or closed/
![__before](https://user-images.githubusercontent.com/16361670/37430275-59a2b594-27da-11e8-966c-74e67f270788.png)
![__after](https://user-images.githubusercontent.com/16361670/37430282-5f615382-27da-11e8-9d4f-5971e8bd31b6.png)


Thx

**Comment by rstoenescu** [comment]
I had this taken care of. Then people argued it was horrible to add padding to layout when scrollbar dissapears. Now you say "put it back". What should I do? :)

**Comment by sagikarni** [comment]
What i'm saying is that the fact that the scroll changes its visibility and as a result the document body width is changing accordinaly ,really damages in the user expirience.
I would highly advise to fix this issue .
I can also say thatbi have presented this behaviour to some of my colleagues (also with great deal of expirience in development and/or ux) and they all agreed .
Thx
Sagi

**Comment by sagikarni** [comment]
#2 is certainly not an option.
the best option is #1.  yes , it means that user can still scroll , but there is no layout change that causes a flicker in the user's eyes..
I can tell you for sure that from a UX percpective option #1 is much better rhan the current implementation (personally , i would not use those components now). and I had explored it a bit and realized that most of the UI components / frameworks i know follow #1 rule. (kendoui, syncfusion,vuetify , react and so on...)

**Comment by sagikarni** [comment]
Any news ?

**Comment by rstoenescu** [comment]
Working on it for 0.15.9. If someone complains about the new behavior I will go mad :)

**Comment by sagikarni** [comment]
Hi, 
I think there is option #3.
go to facebook and share a post.
In this case the layout does not change while the scroll is still visible.
It looks like facebook are diabling the scoll rather then removing it. Hence the layout is OK and the scroll is not active.
Thx
Sagi

**Comment by rstoenescu** [comment]
Can you share a video capture with what you saw pls?

**Comment by sagikarni** [comment]
![facebook1](https://user-images.githubusercontent.com/16361670/37769899-4995c93c-2ddb-11e8-8ad3-cff30a150a51.png)
![facebook2](https://user-images.githubusercontent.com/16361670/37769900-49b929a4-2ddb-11e8-90c5-b7eea6fbe244.png)
![vuetify](https://user-images.githubusercontent.com/16361670/37769901-49d700a0-2ddb-11e8-9f10-dbaf2b373e9c.png)

**Comment by sagikarni** [comment]
Any thoughts ?

**Comment by danikane** [comment]
I remember the discussions regarding this in  v0.14. :)
You can't make everyone happy. 😆
