### ISSUE TITLE
QTable - typeof number

### ISSUE THREAD

**Issue by neatpro** [quasarframework/quasar#1775]
Working with QTable, we use QInput in a cell. Now, if that field is a number and it is a current sort field, once value is changed Vue throws following warning:

`[Vue warn]: Error in getter for watcher "pagesNumber": "TypeError: t.toLowerCase is not a function"`

Watcher "pagesNumber" should check if typeof !number before applying toLowerCase

**Comment by neatpro** [comment]
Solution to convert number to string for sorting purposes will not work. 
For example, if we have 10, 20, 100, it will sort as 10, 100, 20.

**Comment by rstoenescu** [comment]
Yes, but this (a few lines above) does:

```js
if (isNumber(A) && isNumber(B)) {
   return (A - B) * dir
}
```

Are you experiencing any issues?
