### ISSUE TITLE
[15.7] QTable "Rows per page" dropdown label spacing in IE11 issue

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#1776]
Problem can be seen on play app at:
http://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/table/table-features

In IE11, if you select any 2 digit "Rows per page" the number positions itself over the dropdown icon.

![capture](https://user-images.githubusercontent.com/27252610/37427880-d5204aae-2787-11e8-894a-85a5c0286c3a.PNG)

Looks fine in Chrome

Thanks!

**Comment by rstoenescu** [comment]
Is this on Quasar 0.15.7?

**Comment by Lou-Der** [comment]
yes.... i assume quasar-play is current? :)

**Comment by jayudhandha** [comment]
@rstoenescu, Thank you for this awesome framework.

Is this fixed? 

If yes, Then from which version?

**Comment by aprixon01112017** [comment]
Same on 0.16.4, Edge:

![image](https://user-images.githubusercontent.com/33280703/40914170-703c8a48-67f7-11e8-9239-ae10c8bead3a.png)

**Comment by Lou-Der** [comment]
I went back and checked on the latest version 0.16.4.   Seems width and a position its still slightly off compared to chrome.   I'm seeing same positioning issue in quasar-play and custom apps.

![ie11 rows](https://user-images.githubusercontent.com/27252610/40922343-d0aa347e-67c6-11e8-8a75-2ebcf26c0f83.PNG)

![ie11 rows 2](https://user-images.githubusercontent.com/27252610/40923249-29bab654-67c9-11e8-9ca2-b527d78b684f.PNG)

 This is on Win7 ie11.0.96.
