### ISSUE TITLE
[ios] Search component align

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#178]
Hi,

The value of a placeholder is not centered in the text field. Note that it gets weird with larger texts.
Thanks for the feedback.

http://g.recordit.co/FaLnHf1DB8.gif

Jackson

**Comment by rstoenescu** [comment]
I see. Right, will get this fixed soon.

**Comment by xereda** [comment]
Tks!

**Comment by xereda** [comment]
Note that it also does not let you click on the left side of the field.

**Comment by rstoenescu** [comment]
Thanks for reporting this!

**Comment by rstoenescu** [comment]
Left side issue fixed.

**Comment by xereda** [comment]
When could I upgrade Quasar to my project?

**Comment by rstoenescu** [comment]
Finalizing the next release. This week or the next one. Just consider this working until next release.

**Comment by xereda** [comment]
Perfect!
