### ISSUE TITLE
IOS: User has TWO times push close buttons to close dialog or modal (IOS emulator or physical device)

### ISSUE THREAD

**Issue by maxprog** [quasarframework/quasar#1781]
### Software version

Quasar: 0.15.8
OS: IOS
Node: 8.9.4
iOS: Mobile Applications

### What did you get as the error?

On mobile Application for IOS: emulators or physical device, close popups (modal,dialog) doesn't work correct: user has TWO times push close buttons to close dialog or modal. 
Closing popup windows (dialog, modal) works fine only on browser, android symulator or phones

### What were you expecting?

popup should close after one time push button close

### What steps did you take, to get the error?

 `<q-modal  v-model="layoutModal" :content-css="{minWidth: '80vw', minHeight: '80vh'}">
      <q-modal-layout>
        <q-toolbar slot="header">
          <q-btn
            flat
            round
            dense
            @click="layoutModal = false"
            icon="reply"
            wait-for-ripple
          />
          <q-toolbar-title>
           {{selectedSong.name}}
          </q-toolbar-title>
        </q-toolbar>
        <q-toolbar slot="footer">
          <q-toolbar-title>
           <q-btn color="primary" @click="layoutModal = false" wait-for-ripple label="Zamknij" />
          </q-toolbar-title>
        </q-toolbar>
        <div class="layout-padding">
             TEXT
        </div>
      </q-modal-layout>
    </q-modal>`

**Comment by rstoenescu** [comment]
Pushed clean workaround for iOS. Will be available in 0.15.9.

commit 1fae69e67bf57615c0dedefc5d60aa98ee6364f4 (HEAD -> dev, origin/dev, origin/HEAD)
Author: Razvan Stoenescu <razvan.stoenescu@gmail.com>
Date:   Mon Mar 19 21:44:50 2018 +0200

    fix: iOS touch/hover issue on Modals & derivates (Dialog, etc)
