### ISSUE TITLE
AddressbarColor.set() doesn't set default primary color

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1784]
### Software version

Quasar: 0.15.6
OS: Linux/Android
Android: 5.1

### What did you get as the error?

When I use `AddressbarColor.set()` to set addressbar to theme's primary color, it doesn't show any color.

It works as expected if I pass the color value as argument (`AddressbarColor.set('#ff0000')`).

### What were you expecting?

To have addressbar colored by theme's primary color. 

### What steps did you take, to get the error?

Create an `addressbar-color.js` plugin as described in docs.

### Other info

I propose to replace current hidden behavior with a more explicit and powerful one:

```
AddressbarColor.set('primary')
AddressbarColor.set('secondary')
AddressbarColor.set('neutral')
AddressbarColor.set('positive')
AddressbarColor.set('#ff0000')
AddressbarColor.set('red')
```

Or at least support named and theme's colors and fallback to primary color if no argument is specified.

**Comment by rstoenescu** [comment]
1. From docs:
![download 1](https://user-images.githubusercontent.com/4665641/37530137-983d14ee-2941-11e8-88f7-da5ff96bb6a8.png)

Example (notice a **mobile browser**):
![download2](https://user-images.githubusercontent.com/4665641/37530244-cbe0f4be-2941-11e8-98a0-b96dbe031d14.png)

For Cordova use the Cordova plugin.

2. AddressbarColor.set() -> notice no params -> sets the primary color

**Comment by zuck** [comment]
The point 2. is exactly what doesn't work for me on Chrome on Android.

**Comment by rstoenescu** [comment]
Which was added in 0.15.7 -> https://github.com/quasarframework/quasar/releases/tag/v0.15.7
