### ISSUE TITLE
Carousel height is not determined by the slide with the biggest height

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1787]
### Software version

Quasar: v0.15.7
OS: Linux Mint 18.2
Node:
NPM:
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/9g79jmc3/8/

### What did you get as the error?
No error
### What were you expecting?
Expect Carousel height is determined by the slide with the biggest height
### What steps did you take, to get the error?
Just using it.
However,  we wish if the Carousel width(and the images within it) become 100% of the container width and the height dynamically changes per image height.

**Comment by rstoenescu** [comment]
The new features from QCarousel cannot accomodate with this, unfortunately, so you'll need to set a height for yourself. Sorry for this inconvenience. Wish there was an automatic way to do it.
