### ISSUE TITLE
[Proposal] QPagination - @change event.

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#1788]
In `Input` component we have event `@change(newVal) - Triggered on lazy model value change.`
Is it possible to add same event on QPagination?
Or suggest a code example to track changing of model.
Thanks.

**Comment by olegvakulenko** [comment]
http://quasar-framework.org/components/pagination.html

In documentation there is no events at all.
But `@input` works.

@dennythecoder What I missed in Quasar or Vue to understand this?
@rstoenescu Is it useful to add this to documentation?

**Comment by rstoenescu** [comment]
All form components support `@input` and `@change`, including QPagination. Please read  https://github.com/quasarframework/quasar/issues/1803#issuecomment-374334078 for more details.
