### ISSUE TITLE
How to use this in existing Vue Webapp

### ISSUE THREAD

**Issue by mimani** [quasarframework/quasar#179]
Hi,

We have already developed an Vue webapp, I want to integrate this framework in that. How easy will that be?

As I see most of the places use of quasar-cli, but I didn't found any documentation which can help in using this in already created app.

It will be helpful if this is also gets added in Getting Started guide.

**Comment by rstoenescu** [comment]
Hi,

Please use forum for question: http://forum.quasar-framework.org/

Use CLI to generate a project folder and then port your app file by file. Make sure you read Quasar's documentation inside-out.

Cheers.
