### ISSUE TITLE
[Feature Request][QUploader] Allow to programmatically upload files

### ISSUE THREAD

**Issue by mcorbe** [quasarframework/quasar#1791]
As part of our product workflow, we need to be able to upload files that creates new web elements allowing themselves to upload more files. To achieve this, we need to be able to programmatically add files to a QUploader. I suggest to have a public "add" function to complete the QUploader API that could look like:

`
  add(files) {
    this.__add(null, files);
 }
`

Let me know your thoughs, I can follow up with a pull request of course.``

**Comment by rstoenescu** [comment]
Hi, Available in next 0.15.8.
