### ISSUE TITLE
SyntaxError: Unexpected token '>' and ReferenceError: Can't find variable: webpackJsonp

### ISSUE THREAD

**Issue by jvmonjo** [quasarframework/quasar#1792]
Hi. I'm using the new quasar 0.15 template.

I have a blank page on safari under iOS 9.3.5 (can't be update more than that).

When I inspect it with safari devtools I see 2 errors:

`SyntaxError: Unexpected token '>'` in vendor chunk
`ReferenceError: Can't find variable: webpackJsonp` in app chunk

I think it is related to es6 support. At least the first error I think it refers to arrow function =>

Is there any way to support this browser with some babel configuration?

**Comment by rstoenescu** [comment]
Hi,

1. You are using an ES6 version of a library you are importing, instead of the ES5 version. "node_modules" do not go through Babel.
2. This should go to the CLI repo.

**Comment by jvmonjo** [comment]
That was it. Both errors are gone after I've replaced the problematic library.

Thank you.
