### ISSUE TITLE
Context menu remains hidden behind popover list on mobile

### ISSUE THREAD

**Issue by jvmonjo** [quasarframework/quasar#1793]
In desktop works just as expected. The context menu opens on top of the popover list. But in mobile it opens as a modal in the middle of the screen and it remains behind the popover so it can't be clicked.

You can test it opening this jsfiddle on a mobile browser, and try to delete one of the messages displayed when you click on the top right icon:

https://jsfiddle.net/fa8jqhms/60/

**Comment by rstoenescu** [comment]
Hi,

Do not nest Popups-related components, like in this case: QContextMenu inside QPopover. This is a limitation.
