### ISSUE TITLE
quasar load font before vue rending

### ISSUE THREAD

**Issue by ajayashuba** [quasarframework/quasar#1795]
the workspace looks little ugly initially for sometimes  with some letter,words hanging in random location initially . i guessed it might be because of font loading .What is your review for the same ?

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, this is out of Quasar's control. However there are some links that may help you do this:
* https://stackoverflow.com/questions/12312323/how-to-know-if-a-font-font-face-has-already-been-loaded
* https://blog.typekit.com/2013/02/05/more-reliable-font-events/
* https://github.com/typekit/webfontloader
