### ISSUE TITLE
this.$q.notify (Quasar Notify Plugin) not available in main App Vue instance

### ISSUE THREAD

**Issue by kevinmarrec** [quasarframework/quasar#1797]
### Software version

Quasar: 0.15.8
OS: Windows 10
Node: 9.8.0
NPM: 5.6.0
Browsers: Chrome

### The Error
```
TypeError: this.$q.notify is not a function
```

### What I was expecting

A Notification with the message `Test` should be displayed without errors

### Steps to reproduce

Having this following code in `App.vue` file
```html
<template>
  <div id="q-app">
    <router-view />
  </div>
</template>

<script>
export default {
  name: 'App',
  created () {
    this.$q.notify('Test')
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Available in 0.15.9

**Comment by khom-outsourcify** [comment]
I  have the same issue with Quasar 0.15.10

I import Quasar this way 
`import Quasar from 'quasar-framework/dist/quasar.mat.esm'`

But notify is not in this.$q

**Comment by rstoenescu** [comment]
@khom-outsourcify why are you importing Quasar like that? Use Quasar's starter kit instead. Look for guidance on Discord if you need to.

**Comment by khom-outsourcify** [comment]
@rstoenescu Sorry my English is limited, I use Symfony with API platform and Vue.JS + Quasar framework + webpack(encore) for frontend.

Do you have a best way to importing Quasar ?
