### ISSUE TITLE
QSelect only displays label prop for selected option even if it has an icon available

### ISSUE THREAD

**Issue by techiedod** [quasarframework/quasar#1800]
The `QSelect` component ignores the `icon` prop when displaying the chosen option.

I'm sending an array of options to it and each option has an `icon` prop. The icon is displayed properly next to the `label` in the dropdown list when `QSelect` is open. However, once you select one of them, the input only displays the label, ignoring the `icon`. This is expected since the `actualValue` computed prop on `QSelect` is taking its value from the option's `label` and then it's simply [displayed on the page through `fakeInputValue`](https://github.com/quasarframework/quasar/blob/dev/src/components/select/QSelect.vue#L54).

I don't think this is the intended behavior, but please let me know if it is. If it's a bug, I'm down to fix it since I need to use it in a project ASAP.

**Comment by rstoenescu** [comment]
Hi,

The icon, letter, avatar etc are for dropdown usage only. It does not reflect in the value being displayed in the QSelect input. However, you can make use of the "before" / "after" props to also show an icon should you wish. I'm currently already in the process of improving this with no breaking changes, but it will take a while since the todo pile is huge at the moment. Until then, you can stick to "before"/"after" props. Hope this makes sense.

**Comment by techiedod** [comment]
@rstoenescu I was thinking `before` / `after` props were for showing icons that represent the concept of that specific QSelect element, not of the selected value. I did consider this way before posting, but it didn't seem right since I would have to do an additional lookup of the selected value in the options array (this is already done once on QSelect, so I'm basically duplicating code). In my current use case, I can accomplish the lookup in constant time, but I'm not sure that will always be the case for everyone.

IMO, the props that affect the display of an option should be shown together or at least it should be possible to choose between hiding the metas (icon, letter, avatar, etc.) in the QSelect input or displaying them. At least this is how it makes sense to me.

Anyway, thanks for your answer. If you need help with the todo list, I can try to give you guys a hand.

**Comment by rstoenescu** [comment]
Like I said, it's gonna get improved. But you are looking for a quick thing now, right?

**Comment by techiedod** [comment]
Yeah, that's fine for now.
