### ISSUE TITLE
[Bug]The "number" q-input can enter the letter e

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#1801]
### Software version

Quasar: v0.15.8
OS: Windows 10 build 1703
Node: v8.9.4
NPM: v5.6.0
Browsers: Chrome  65.0.3325.162

### JsFiddle
[jsfiddle](https://jsfiddle.net/fdsg50az/5/)

### What did you get as the error?
When I set q-input component type to “number”, the leter 'e' can be entered.
### What were you expecting?
Only number or dot can be entered.
### What steps did you take, to get the error?
`<q-input type="number"/>`

**Comment by olegvakulenko** [comment]
https://www.w3schools.com/jsref/jsref_obj_number.asp

var x = 123e5;    // 12300000

As I understand, 'e' valid character for numbers.

**Comment by rstoenescu** [comment]
@olegvakulenko is correct.
