### ISSUE TITLE
[Request] Touch-Pan delta direction

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1802]
Currently the pan `direction` only points into the direction **based on the pan start point**.
http://quasar-framework.org/components/touch-pan.html

I require in my app the `delta` direction. In other words, every time the user starts panning up it should give me `up` and every time he starts panning down it should give `down`, no matter the start point of the pan.

**Comment by rstoenescu** [comment]
Hi,

Calculating every possible scenario is not an option as it would slow down the directive processing time. But the directive gives you all necessary information to determine your needed additions which should go into the handler.

In your case, a delta.x < 0 means going to left while delta.x > 0 means going to right. Same analogy for delta.y < 0 - up, delta.y > 0 - down.
