### ISSUE TITLE
[REQUEST] Q-Chips-Input:  Add Duplicate Entry Event or warning

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#1805]
When entering into q-chips-input the field automatically stops you from entering duplicate arrays into the v-model.   However a user may  not understand why the button or enter key is not working.

If the component would emit an event that would allow us to show a warning or some hint to the user that it is a duplicate there wouldn't be any confusion.

Thanks!

**Comment by rstoenescu** [comment]
Added `@duplicate(value)` event. Available in v0.15.9. Thanks for suggesting this.
