### ISSUE TITLE
Suggestion: allow QDialog as component to prevent close when using default buttons

### ISSUE THREAD

**Issue by omrihar** [quasarframework/quasar#1808]
In Quasar 0.15 `QDialog` exists in two flavors - as a component and as a method. The component form of `QDialog` allows to customize it to include forms and other components. When the dialog does include forms, it is useful to have it not be closed before validation passes. This is currently not supported when using the default buttons since the `@ok` and `@cancel` event handlers get called __after__ the dialog is closed. 
It is currently possible to implement this close prevention by using a "buttons" slot with event handlers that then consequently close the dialog. It would be very convenient to allow the dialog to prevent closing also with default buttons.
This could be done possibly by allowing the `ok` and `cancel` props to receive a `preventClose` property such as the ones in the method form of the dialog.

Thanks for the great work!
Omri

**Comment by pdanpdan** [comment]
You can check a working example here: https://github.com/quasarframework/quasar/blob/2c3b4f0c0d8ed52013a35a86450736985a927e56/dev/components/global/dialog.vue#L78

**Comment by rstoenescu** [comment]
It would be convenient to add this to the default buttons, but in doing so it will be harder in other use-cases, plus a small perf penalty which we definitely want to avoid.
Sorry, but go with the buttons slot. It's the best option, trust me.
