### ISSUE TITLE
Feature request / Ability to disable a splitted dropdown independently

### ISSUE THREAD

**Issue by catalintoma** [quasarframework/quasar#1813]
Currently, when disabling a dropdown button it also disables the arrows

It would be a nice feature to be able to disable them independently
In my case, I use the arrows as a context menu so disabling it doesn't make sense

**Comment by bloodf** [comment]
Why dont you use it as a button groups, adding a simple button disabled and a button with the arrow icon on the side?

**Comment by rstoenescu** [comment]
This is available in v1 beta.18
