### ISSUE TITLE
[Feature Request] Uploader Changes

### ISSUE THREAD

**Issue by l1qu1d** [quasarframework/quasar#1814]
Requests as follows:

- Make URL optional

- Allow me to define upload success or failure per file

- Allow me to set upload percentage per file

I use [Firebase ](https://firebase.google.com/) and specifically the [Firebase storage](https://firebase.google.com/docs/storage/web/start?authuser=0) for my projects and I don't need a separate page to send and handle uploads as I use the single page structure for VueJs. I have a utility library that handles  async uploads so all I have to do is call the function in my page when the q-uploader events are triggered --this also handles all  failures and upload percentages. By requiring me to use the URL property and it being required, throws an error.

**Comment by thugic** [comment]
Did you find a solution to this?

**Comment by rstoenescu** [comment]
Hi,

This is already possible in future Quasar v0.16.1, so closing this.
