### ISSUE TITLE
@change not firing on Datetime on desktop (except when type='date')

### ISSUE THREAD

**Issue by j623415** [quasarframework/quasar#1815]
https://s.codepen.io/Jak6519/debug/mxRmmX/VJMxxZDGejyM

change handler is supposed to "notify" the new value

Datetime mode and time only mode in desktop does not fire @change.
Date only mode does.
On smaller viewports that show the "SET" button, @change always fires on @click of SET

**Comment by pdanpdan** [comment]
Can you please repost the sample - the link is not available anymore.

**Comment by rstoenescu** [comment]
Please reopen with a valid codepen.

**Comment by j623415** [comment]
Sorry, I posted the debub view link earlier. https://codepen.io/Jak6519/pen/mxRmmX

Make sure you use the debug view. Otherwise you have the "SET" buttons. There is no issue when you have the SET buttons

**Comment by rstoenescu** [comment]
Hi, Thanks for the pen.
Same explanation here: https://github.com/quasarframework/quasar/issues/1803#issuecomment-374334078

**Comment by j623415** [comment]
Got it. Thanks
