### ISSUE TITLE
[Request] Date picker `minimal` prop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1818]
I love the standard Android date picker, however my whole app is built upon the iOS theme.
I would like a prop that forces `android` css for the date picker. Is there any way I can do this now?

One extra little request I have is a `hide-top` property on the date picker that will hide the top part and only show the minimalistic calendar:

<img width="331" alt="2018-03-22 13 46 55" src="https://user-images.githubusercontent.com/3253920/37751851-16eb886c-2dd8-11e8-91ef-6990d4421ca5.png">

**Comment by rstoenescu** [comment]
1. Cannot use material datepicker on ios theme and ios datepicker on material theme.
2. Added "minimal" Boolean prop which removes the header. Available in 0.15.9.
