### ISSUE TITLE
when I refresh the page,then datetime component will flash first then disappear

### ISSUE THREAD

**Issue by KrisyOne** [quasarframework/quasar#1823]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Any video screen capture please? I cannot reproduce.
A jsfiddle would also be wonderful as it might help me reproduce this faster.

**Comment by slowaways** [comment]
@KrisyOne More detail please!

**Comment by rstoenescu** [comment]
Closing as no details have been provided.
