### ISSUE TITLE
Escape-key propagating from Q-uploaders' file-select to underlying modal

### ISSUE THREAD

**Issue by shandrolis** [quasarframework/quasar#1826]
### Software version

Quasar: 0.15.8
OS: windows
Node: n/a
NPM: n/a
Browsers: chrome/firefox/opera (NOT Edge)
iOS: not tested
Android: not tested
Any other software related to your bug: n/a

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/v6xutwmv/26/

### What did you get as the error?
Modal closing
### What were you expecting?
Modal not closing
### What steps did you take, to get the error?
1. Place `<q-uploader>` inside a `<q-modal>`
2. Open the uploaders' file-select
3. press escape
4. the 'escape' key propagates from the file-select to the underlying modal, closing them both.

See Jsfiddle.

**Comment by rstoenescu** [comment]
Confirmed it is reproducible only on Windows.

**Comment by rstoenescu** [comment]
Hi,

We've tested a few fixes, but none is perfect. Every approach has its flaws. Each browser has its own implementation of the file picker dialog behavior and it may even change in the future. There's no reliable method to determine when the file picker dialog gets closed.
So we recommend disabling the Escape key for Modals through `no-esc-dismiss` prop in scenarios like yours.
