### ISSUE TITLE
[Enhancement] Provide way to target the <span> element in a QTree

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#1827]
I would like to be able to create a hierarchy of 'settings' for my app, and QTree is great in principle for this. However, I need each leaf to be a checkbox, a string input, a slider, etc. I've done this by using a custom header and the slots, and all is working well.

However, I cannot target the right element for a string input to make the input full width. See [this pen](https://codepen.io/anon/pen/EEXqdE), where `class="full-width"` is applied to both the q-tree and the q-input being used for the header.

Looking at the DOM, there is a span created by line 462 in QTree.js which seems to prevent the input expanding. If I manually add `full-width` to this span in dev tools, the input is as I would like. But I can't see a way to add this class via props.

**Comment by pdanpdan** [comment]
You can target this with CSS: https://codepen.io/anon/pen/MVrZxg

**Comment by dsl101** [comment]
Yes, I was about to comment that I'd ended up using
```
<q-tree class="tree-full-width">

.
.
.

.tree-full-width >>> span
  width 100%
```
I still think it might be better for the component to enable this though, because:
- Adding `class="full-width"` to the tree and/or leaves _ought_ to not require extra custom CSS
- Your CSS ties the app into the specific structure of q-tree (`.q-tree-node-header > span`) which might change and then break
- My CSS is probably too broad, and could mess up other `<span>` elements which were _not_ part of the tree's structure.

**Comment by panstromek** [comment]
Bump. I need to set exactly this on header, too.

Thx for temporary solution.

**Comment by pdanpdan** [comment]
Closing this to track it in https://github.com/quasarframework/quasar/issues/6959
