### ISSUE TITLE
QDateTime on IOS shows incorrect static date due to timezone

### ISSUE THREAD

**Issue by MoacirSchmidt** [quasarframework/quasar#1828]
Software version

Quasar: 0.15.8
iPhone 7
IOS 11.2.6

QDateTime on IOS (safari) shows incorrect static date due to timezone:

static date: 19/03/2018
date shown: 18/03/2018

https://jsfiddle.net/wsadbokn/8/

I noticed that "incorrect shift" is equal to browser local timezone. On "GMT-" timezones we have date changing to yesterday

This happens only on IOS SAFARI (browser or cordova)

**Comment by rossity** [comment]
+ Spent all day trying to fiogure this out, which was supremely difficult since I don't have a Mac. This is a breaking bug.

**Comment by rstoenescu** [comment]
To avoid the Safari bug, specify date like this: '2018/03/19 00:00:00' instead of the ISO format '2018-03-19T00:00:00'. Unfortunately, there's nothing Quasar can do.

**Comment by rstoenescu** [comment]
Further reading: http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html

**Comment by rstoenescu** [comment]
Also good to read: https://stackoverflow.com/questions/4310953/invalid-date-in-safari
