### ISSUE TITLE
Uploader ability to set xhr.withCredentials=true

### ISSUE THREAD

**Issue by osalabs** [quasarframework/quasar#1829]
Please consider ability to set xhr fields for the file uploads.
Specifically it would be great to be able set `xhr.withCredentials=true`
Either have a `prop` for that or more flexible way would be to create xhr object for each file _before_ event `@add(files)` called, so it would be possible to access `files[i].xhr` and do the necessary changes.

**Comment by rstoenescu** [comment]
Hmm, this has been added for some time. Try Quasar v0.17.8. QUploader has `with-credentials` Boolean prop. Sorry for not closing sooner.
