### ISSUE TITLE
 Displacement of the main container

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#183]
Hi,

The displacement of the main container, as shown below, occurs only in the browser, correct?

http://g.recordit.co/uFW3GUaifn.gif

Tks

**Comment by rstoenescu** [comment]
Yes, emulators are not perfect. Chrome dev tools in particular is just a shallow emulator.

Anyways, I cannot reproduce that in my browser. I'm running Chrome 52.0.2743.82 (64-bit). What's your Chrome version and OS? Thanks.

**Comment by xereda** [comment]
I am using mac os x and google chrome as following illustration:

![captura de tela 2016-11-12 as 14 28 12](https://cloud.githubusercontent.com/assets/14337850/20239300/86e617ba-a8e4-11e6-9a70-bbce08569d86.png)

**Comment by xereda** [comment]
What do you advise from simulator to test applications?

**Comment by rstoenescu** [comment]
Recommended way to go when you want a simulator is to continue using Google Chrome dev tools, but with a stable version only. At the time of writing this, 53 is the latest stable version. It's recommended you use only stable releases. Using 53 you won't bump into that issue.

Please reopen if you feel something is indeed broken. Thanks for reporting this anyway.
