### ISSUE TITLE
Problems with built android .apk only on samsung and golcever smartfones and tablets (tested on tablet SM-T235 i smatfon GT-I9060I samsung) 

### ISSUE THREAD

**Issue by maxprog** [quasarframework/quasar#1832]
### Software version

QSoftware version

Quasar: 0.15.12
OS: android
Node: 8.9.4
NPM: 5.7.1
Browsers: -
iOS: ---
Android: problem with built apk only on samsung smartfones and tablets (tested on  tablet SM-T235 i smatfon GT-I9060I samsung) and goclever smartphone
Any other software related to your bug:

### What did you get as the error?
use quasar init to generate new raw project or use quasar-play source codes  and build to apk and install on samsung smartfon or tablets. Problems: can't close menu and come to main screen with logo image (not possible to close main menu left bar).  Internal Size of menu seems  not adjusted correctly. Problem with Interaction with keyboard or buttons smartfone to close menu. Problem with redirection using routing in [q-item to="/path "] - sample source codes quasar-play 
Maybe the same problem like in case interaction with close menu

tested on smartphones and tablets (tested on  tablet SM-T235 i smatfon GT-I9060I samsung) and goclever smartphone

The same problem when You use quasar-play 

### What were you expecting?
generated apk should works like on samsung

### What steps did you take, to get the error?

use quasar init to generate new raw project or use quasar-play source codes  and build to apk and install on samsung smartfon or tablets and run application

**Comment by maxprog** [comment]
Solved

**Comment by rstoenescu** [comment]
@maxprog what was the issue and fix?

**Comment by maxprog** [comment]
Problem regarding icons - some icons have impact on routing, rendering side e.g icons mdi with spaces in names... and some icons with undersscore - when I replaced then start works

**Comment by maxprog** [comment]
I published professional app bases on quasar on google play - if You want I can send You as sample of app as case of use Your framework :-)

**Comment by maxprog** [comment]
Quasar is amazing - I reduced time of creation from 1 month to 1 week :-)

**Comment by rstoenescu** [comment]
Wish you could tweet that to `@quasarframework` and `@vuejs` so I can retweet :)
Also, please submit a link to your work on https://github.com/quasarframework/quasar-awesome
