### ISSUE TITLE
[Request] Setting CSS variables helper (other than colors)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1835]
We all love the possibility to set CSS color variables through: `colors.setBrand('light', '#DDD')`

But if Quasar could have a JS method that can set other CSS variables as well that would be truly powerful!

e.g. `css.setVar('boxHeight', '100px')`

**Comment by rstoenescu** [comment]
Hi, Sorry but unfortunately won't do it too soon as the CSS footprint would go up a lot. This will be available only when all targeted browsers have CSS variables support.

**Comment by rstoenescu** [comment]
It's not so great for mobile apps. Plus IE is missing.
