### ISSUE TITLE
[windows] Firefox and Quasar 0.15.8 Drawer "close event" response Problem ... 

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#1836]
Quasar: 0.15.8 - fresh install / plain
OS: Win 8.1. 64 Bit

Browsers: Firefox Quantum
59.0.1 (64-Bit)

After opening a Left-sided Drawer with the plain 0.15.8 Quasar Version and
marked the quasar logo the drawer cannot be closed.

Screensize is choosen, so that the left-side drawer is overfloating the menu / hamburger icon.

i made a real-life video about this issue .. which is very showstopping 
(on chrome there seems to be no issue)

https://vimeo.com/261709995

Best regards
Jochen

**Comment by rstoenescu** [comment]
I've got two VMs installed, one with Windows 7 and one with Windows 10. Can't reproduce on either of them with Firefox 59.0.1...

**Comment by ibrainventures** [comment]
Tested with 6 different machines, 8.0 win, 8.1 sp 1 win, 10 Win, 7.0 win .. always with the actual firefox quantum edition (59.0.1) .. always running into the same "point of no return" .. i am holding the left mouse button 1-2 secs. with scrolling inside the "content area" .. and then it is stillstand .. no reaction on the mouse click (as seen in my video) ..

may we should make a teamviewer session ?

**Comment by ibrainventures** [comment]
to be secure .. holding left mouse button and turning the scroll wheel ... (6 different machines but same mouse ) ..

**Comment by ibrainventures** [comment]
left drawer open -> fast double click inside content area -> the content area is getting a scroll-bar after this action -> reaction by user is now content aread dedicated (scrolling etc.) -> no closing for the drawer possible ... (for this test you should (if you are using the plain 0.15.8 setup ) close the complete window to scrolling reactivity)

**Comment by ibrainventures** [comment]
between the fast double click move the mouse .. (i know ..  this sounds like a crazy people action :-)  .. but this issue happens to me and my colleagues 3 of 10 times ... so we are stuck inside our development ..)

**Comment by ibrainventures** [comment]
Hi Razvan,

some more details:

No Problem with Chrome : Version 65.0.3325.181 (Offizieller Build) (64-Bit)

The issues also not happend on Quasar 14.x 

No Addons or something else specials inside Firefox activated.

No Problem with Firefox Developer Edition (60.0b6 (64-bit))

After some staging through the vue Events there seems to be a timing problem.

The <body class tag is losing his   -> with-layout-drawer-opened <- attribute, but
the drawer is still open...

may this helps ..

**Comment by rstoenescu** [comment]
Finally reproduced it. Investigating and fixing for 0.15.9.

**Comment by ibrainventures** [comment]
perfect (this sounds strange) .. but .. i saw myself carrying 6 machines to romania to reproduce the issue ;-) .. hope you find the workaround ... timing / promise for the drawer / ... :-)

**Comment by rstoenescu** [comment]
Fix available in 0.15.9. Thanks for reporting!

**Comment by rstoenescu** [comment]
If you are a company, please consider visiting the [Patreon campaign](https://www.patreon.com/quasarframework).

Releasing 0.15.9 in a few hours.

**Comment by ibrainventures** [comment]
Hi razvan,

we updated to 0.15.10 this morning and the issue / bug is away !!!
You are a hero :-)

Thank you very much for this fast response ... and yes we are Patreon since 6 Months .. (webstudio / jochen geiger)
