### ISSUE TITLE
Errors while adding RTL & i18n support to existing Quasar app

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1838]
### Software version

Quasar: 0.15.6
OS: Windows 10
Node: v9.9.0
NPM: 5.6.0
Browsers: Google Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
```
This dependency was not found:

* quasar-framework/i18n/ar in ./.quasar/quasar.js

To install it, you can run: npm install --save quasar-framework/i18n/ar
```

And when I run `npm install --save quasar-framework/i18n/ar` I get:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "quasar-framework\i18n\ar" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohammed\AppData\Roaming\npm-cache\_logs\2018-03-26T10_54_59_771Z-debug.log
```
### What were you expecting?
I expect to add RTL & i18n support to my new 0.15.6 Quasar without errors.
### What steps did you take, to get the error?
I'm working on upgrading my Quasar 0.14.4 to 0.15.6 I completed about 70% of the upgrading process and now I want to add RTL & i18n support to it so I added:
```
build: {
  rtl: true
}
```
And
```
framework: {  i18n: 'ar'}
```

To `/quasar.conf.js` now when I run `quasar dev` I get the above errors.

**Comment by MohammedAl-Mahdawi** [comment]
Note I said `N` to this option `Use Vue-i18n? (recommended if you support multiple languages) (y/N)` when created my app but now I want to add it, how, please?

**Comment by rstoenescu** [comment]
NPM messed up.

```bash
$ npm cache clean
$ rm -rf node_modules package-lock.json
$ npm install
```
... or the equivalent yarn commands.

For vue-i18n, just follow their docs :)

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu thank you for your reply, I did it but still same errors appear!

**Comment by rstoenescu** [comment]
Can you connect with me on Discord pls? This is not a fault in Quasar, but with NPM.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu should I create `i18n` folder or do something else?

**Comment by rstoenescu** [comment]
Ah, wait. You are referring to arabic i18n. This will be available in 0.15.9, which hasn't been released yet...

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu  how should I now use Arabic in `Datetime` month-names/days-names component for example?

**Comment by rstoenescu** [comment]
When 0.15.9 will be available you'll just have to set Quasar i18n to arabic and that's it. No further config necessary.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu  Thank you so much for your help and time, I really appreciate that, could you please just tell me the estimated release date?

**Comment by rstoenescu** [comment]
A few hours :) Wrapping up the release and re-testing it.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu WOW awesome, thank you so much.
