### ISSUE TITLE
q-checkbox and q-toggle not updating UI

### ISSUE THREAD

**Issue by sophalch** [quasarframework/quasar#1839]
My app requires cloning of a vuex object before showing on a form so that original state is preserved until the user clicks the save button. The problem arises when binding q-toggle or q-checkbox to a boolean property of the cloned object; the control's UI is not usable, but the stored value is changed.

This doesn't happen with regular checkbox.

### Software version
Quasar: v0.15.10

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/waugrryy/958/

### What did you get as the error?
- When q-toggle or q-checkbox is clicked, the UI is not changed, but the value is after clicking save button
- Multiple clicks on either of them have the same effect

### What were you expecting?
- q-checkbox and q-toggle's UI should be updating after clicked like regular checkbox

### What steps did you take, to get the error?
Please see jsfiddle link above

**Comment by rstoenescu** [comment]
Hi,

Several issues with your example:

1. You are using a computed property as model. Definitely against how Vue works. Please read up on what computed properties are and how they work.
2. You're defining "toggle" prop and actually using "value".
3. `let obj = {name: 'test', toggle: true}; return Object.assign({}, obj)` -> why the extra Object.assign when you can directly return your object

https://jsfiddle.net/rstoenescu/waugrryy/966/

**Comment by rstoenescu** [comment]
You're completely dismissing point no 1, which is the "root of evil". Computed properties should not be changed under any form. Construct a variable in your data() based on vuex store instead and change that.

**Comment by sophalch** [comment]
Thanks. I've made some changes: https://jsfiddle.net/waugrryy/997/

When q-toggle or q-checkbox is bound to non-existent object property, its value is updated on click but not reflected on the UI. This could be due to the property not being reactive (Vue 2 intention), not quasar's problem.

It can be avoided by either giving initial value to the property or using Vue.set, which is fine for a few properties, but in reality it could be more than that.

I understand it's not your problem to fix. It's just nicer to have those quasar controls to behave like regular checkbox - i.e. update it's UI on click regardless of what it's bound to.

Thanks anyway.

**Comment by thomhickey** [comment]
> You're completely dismissing point no 1, which is the "root of evil". Computed properties should not be changed under any form. Construct a variable in your data() based on vuex store instead and change that.

Not sure what the author's original jsfiddle code was, but vuejs docs are clear that you can use computed setters: https://vuejs.org/v2/guide/computed.html#Computed-Setter ... just have to be careful when you do, but I do this all the time to get/set into the store.
