### ISSUE TITLE
Drawer wrong in iOS landscape

### ISSUE THREAD

**Issue by kael777** [quasarframework/quasar#184]
Hi there ,I use 
![img_0098](https://cloud.githubusercontent.com/assets/19182628/20242953/e444e268-a97c-11e6-8e8c-a1d29c514f20.PNG)
iphone 6s to watch quasar play in safari,but layout is wrong left side is not hidden

**Comment by rstoenescu** [comment]
If width passes a certain point (and on landscape it does), the drawer is designed to be displayed.
