### ISSUE TITLE
Feature Request: QSelect with QInfiniteLoader

### ISSUE THREAD

**Issue by FerrielMelarpis** [quasarframework/quasar#1840]
### Use Case
- Using QSelect for paginated options.

### Code Sample
```vue
<template>
  <q-select
    infinite
    :options="options"
    :handler="loadMore"
     ...
  />
</template>
<script>
...
methods: {
  async loadMore(index, done) {
    const additionalOptions = await someAsyncCall({
      page: index + 1
    })
    this.options = this.options.concat(additionalOptions)
    done()
  }
}
</script>
```

### Workaround
- My current workaround is using `QPopover` with `QInfiniteLoader` inside that loads the options as `QItem` inside a `QList`. Would be a good feature though if it's already implemented with `QSelect` or a separate component say `QInfiniteSelect`. :smile: 
I would be happy to submit a PR.
- Another workaround is to just use a different component like `QInput` with `QAutocomplete`. Depending on the data that you are handling, I think this would suffice on most use cases.

**Comment by rstoenescu** [comment]
Done for v1.0
