### ISSUE TITLE
QTable - rowsPerPageOptions - UMD

### ISSUE THREAD

**Issue by neatpro** [quasarframework/quasar#1842]
When using UMD version, vue is throwing warning:

Prop "rowsperpageoptions" is passed to component <Anonymous>, but the declared prop name is "rowsPerPageOptions". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "rows-per-page-options" instead of "rowsPerPageOptions".

Using `:rows-per-page-options="pagination.options"` resolves this issue.

**Comment by rstoenescu** [comment]
Hi,

Vue enforces kebab-case for component props when using UMD. It does not apply when using vue-loader though. Furthermore, when using eslint-plugin-vue with the strictest ruleset, it also notifies you about the kebab-case.

Bottom line, source code is correct. Usage must be just as you highlighted -- for all props.

**Comment by rstoenescu** [comment]
![download](https://user-images.githubusercontent.com/4665641/37977340-3067065a-31ec-11e8-8b4c-f86e3ac6b80b.png)
