### ISSUE TITLE
Feature Request: qtab label lowercase

### ISSUE THREAD

**Issue by oliviermorpa** [quasarframework/quasar#1843]
Requests as follows:
   dont change to uppercase the label in q-tab

maybe with an option UPPERCASE if we want uppercase.if not, dont chane the case
![1](https://user-images.githubusercontent.com/9378538/37969820-5c100d8e-3204-11e8-8e45-b82444e9f040.png)

**Comment by olegvakulenko** [comment]
Material Design spec:

https://material.io/guidelines/components/tabs.html#tabs-specs

`All caps`

**Comment by oliviermorpa** [comment]
thanks for answer.
i answer myself :-)
need to add this in variables
$tabs-text-transform = false

**Comment by vinidiktov** [comment]
Have a look at Google Maps. It uses lower case labels for tabs.

**Comment by vinidiktov** [comment]
Actually, I stand corrected. In Google Maps those are not tabs, but bottom navigation items.

**Comment by DamisFloris** [comment]
> Requests as follows: dont change to uppercase the label in q-tab
> 
> maybe with an option UPPERCASE if we want uppercase.if not, dont chane the case ![1](https://user-images.githubusercontent.com/9378538/37969820-5c100d8e-3204-11e8-8e45-b82444e9f040.png)

It is actually now possible to disable all-uppercase text.
Just add **:no-caps="true"** inside the <q-tabs> tag, like that:
`
<q-tabs v-model="selectedTab"  :no-caps="true">
      <q-tab
          v-for="x in y"
          :name="x.name"
          ></q-tab>
  </q-tabs>
`
