### ISSUE TITLE
unpkg.com - undefined date

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#1848]
https://unpkg.com/quasar-framework@0.15.10/
Date of all files is undefided: 1970-01-01T00:00:00.000Z

But here:
https://unpkg.com/quasar-framework@0.15.5/
date is normal: 2018-03-01T18:12:23.000Z

I have no idea where is problem and how much it important, but early it work correct.
Thanks.

**Comment by rstoenescu** [comment]
Hi, unfortunately, nothing can be done. It's all unpkg.com here.. maybe a bug in their system?
