### ISSUE TITLE
[Feature request/proposal] External custom point to disable arbitrary dates  

### ISSUE THREAD

**Issue by devel-pa** [quasarframework/quasar#1849]
Hi Razvan, is full of templates and guides around here. Nice framework, thou'

This is just a feature proposal:
https://github.com/devel-pa/quasar/commit/56016b93c5c3a99612842fefed4fc4c10ad009cc

Salutari,
Paul

**Comment by slowaways** [comment]
Best to send a PR?

**Comment by devel-pa** [comment]
@slowaways a PR was sent some time ago
https://github.com/quasarframework/quasar/pull/1938
In the meantime I started using another library, so probably both the issue and the PR should be closed.
