### ISSUE TITLE
new quasar version not comfortable ios8 native web browser

### ISSUE THREAD

**Issue by lenvonsam** [quasarframework/quasar#1850]
I have used last version quasar framework of 0.15.10, and then bulid spa, using http-server build a client server.
But when i using iphone 5 with ios8 system, write down the url  and the safari show white screen, no problems, how to slove it?
 
### Software version

Quasar: 0.15.10
OS: 10.13.2 (17C88)
Node: 8.9.4
NPM: 5.6.0
Browsers: AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0
iOS: iPhone OS 8_3

**Comment by lenvonsam** [comment]
is it link preload, fetchload not support for ios8?

**Comment by pdanpdan** [comment]
Try to provide console messages from the browser on the phone.
https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by lenvonsam** [comment]
![image](https://user-images.githubusercontent.com/10168476/38029027-4cac3e6c-32c7-11e8-8f04-bcc6b52d87f9.png)
I have looked up some document, so i want to know how to close preload via quasar.conf.js in quasar framework 0.15.10 ?  @pdanpdan  @rstoenescu

**Comment by rstoenescu** [comment]
Hi,

Please follow pdandan's recommendation and see if there are any errors on the console. Thanks.

**Comment by lenvonsam** [comment]
i have followed pdandan's recommendation, and occured two probloms
![image](https://user-images.githubusercontent.com/10168476/38071965-cf4a4140-3356-11e8-8634-61e2faf3491c.png)
please help me solve those, thx @rstoenescu

**Comment by rstoenescu** [comment]
What this means is that some package that you are importing is not built right. It supplies ES6 code instead of ES5. I'd investigate which package is that and look over its docs to make sure it's being used right... even log them a bug to fix their distributables.

**Comment by luatnd** [comment]
My team has this issue too.
I have to enable debug, and configure quasar to turn on source map.
`quasar build --debug`

Then I located the error is caused by some of node_modules in ES6.

Look at [#build-Property](https://quasar-framework.org/guide/app-quasar.conf.js.html#build-Property)
Thanks to the very flexible quasar configuration. My solution is to configure `quasar.conf.js`:
```
{
  build: {
    /**
       * Add dependencies for transpiling with Babel (from node_modules, which are by default not transpiled)
       */
      transpileDependencies: [
        'strict-uri-encode',
        'query-string',
        'other-node-modules',
      ],
  }
}
```
