### ISSUE TITLE
QDialog message property can't set HTML tag.

### ISSUE THREAD

**Issue by Zuolon** [quasarframework/quasar#1851]
Software version

Quasar:0.15.10
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
QDialog message property can't set HTML tag.
### What were you expecting?
I hope it can be support HTML, because i want set "<br/>" to wrapping lines. "\r\n" also is not valid.

**Comment by pdanpdan** [comment]
For this you can use it as a component. Due to security reasons you cannot use HTML markup in message.

**Comment by rstoenescu** [comment]
Hi, Preventing XSS attacks by default, so HTML markup is not supported. However, use the QDialog component instead.
