### ISSUE TITLE
QContextMenu does not close when another QContextMenu is opened

### ISSUE THREAD

**Issue by simshaun** [quasarframework/quasar#1852]
### Software version

Quasar: v0.15
OS: Windows
Browsers: Firefox

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/simshaun/re3gpxhu/

### What steps did you take, to get the error?

Right-click each colored block. Previous context menus remain visible. 

### What were you expecting?

As each context menu is opened, previous context menus should be hidden.

I can work around this behavior by manually dispatching events and calling `.hide()`, but thought I'd report this issue as it seems like a bug to me. It's especially problematic in my case since I'm building a spreadsheet-like editor where every cell has a context menu.

**Comment by pdanpdan** [comment]
What you have in the example is 4 distinct context menus. They do not communicate with each other in any way.
You should either register the active one and hide it when another is activated or use only one context menu on the whole parent and customize it according to the target clicked.

**Comment by simshaun** [comment]
Gotcha, thanks

**Comment by rstoenescu** [comment]
Fix available in 0.15.11
