### ISSUE TITLE
QListHeader bad padding inside popover

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#1856]
Hey again!

I think the title is self explanatory. Here is a jsfiddle: https://jsfiddle.net/d8hy8f3m/7.

Thanks
![screen shot 2018-03-28 at 17 35 27](https://user-images.githubusercontent.com/3635352/38036099-9eb887a6-32ae-11e8-90b2-c4a40853bee8.png)

**Comment by pdanpdan** [comment]
It's the same padding (none) used for normal lists.
But you can put a `q-pr-md` on the QListHeader.

**Comment by jean-moldovan** [comment]
Okay, that helps, thanks @pdanpdan !

Maybe `q-list-header` should have `padding-right` by default for consistency?

Thanks again!

**Comment by jean-moldovan** [comment]
Feel free to close this if you prefer to keep it as it is (no padding right)

**Comment by rstoenescu** [comment]
Fixed padding. Available in 0.15.11.
