### ISSUE TITLE
Context Menu API not working

### ISSUE THREAD

**Issue by simshaun** [quasarframework/quasar#1858]
Following #1852, I created a single context menu and I'm trying to open it programmatically when any of the cells are right-clicked.

![image](https://user-images.githubusercontent.com/379519/38070625-e64bb3e0-32ea-11e8-85fe-f95f8fea2823.png)

[According to the docs](http://quasar-framework.org/components/context-menu.html#Vue-Methods), calling `.show()` or `.hide()` on a context menu reference should work.

### Software version

Quasar: v0.15
OS: Windows
Browsers: Firefox

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/simshaun/ujpsna67/

### What did you get as the error?
`this.$refs.contextMenu.show is not a function`

### What were you expecting?
The context menu to open.

### What steps did you take, to get the error?
Try to call `.show()` or `.hide()` on a context menu ref.

I've also tried calling `.show()` on the underlying popover by `this.$refs.contextMenu.$refs.popover.show();` but even that throws an exception: `uncaught exception: null`

Edit: I ended up getting `this.$refs.contextMenu.$refs.popover.show()` to work by passing the mouse event to it.

**Comment by pdanpdan** [comment]
I think you want something like this:
https://jsfiddle.net/b94w5oyf/43/

**Comment by simshaun** [comment]
The show/hide API still needs to work (or the documentation removed.) I did get everything working how I needed -- just not with the documented context menu API.

It's kind of difficult to explain all I need, but I'll try:

### Goals:

1) Left-click arrow in header cell opens a normal popover menu (not a context menu).
2) Right-click a header cell opens a normal popover menu.
3) Right-click a header cell closes the context menu.
4) Left-click a data cell closes the header cell popover menu.
5) Left-click a data cell closes the context menu.
6) Right-click a data cell opens the context menu.
7) Context menu must not open when right-clicking empty space to the right of header cells.
8) Context menu must close when clicking empty space to the right of header cells.
9) Context menu must not open when right-clicking empty space to the right or bottom of data cells.
10) Context menu must close when clicking empty space to the right or bottom of data cells.

Most of those goals are already solved by just letting Quasar do its thing with its own click event handlers.

Goals 7 and 9 are tricky, because to stop the context menu from opening, I have to intercept the contextmenu event and stop propagation. Unfortunately, that means some of the other goals are no longer handled by Quasar.

It's easiest (imo) if I can setup all of my own click/contextmenu event handlers and call Quasar's API methods as I need them. The problem is, the documented API methods aren't working here. :(
