### ISSUE TITLE
List with larger avatars

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#186]
Proposal: List with larger avatars

Have you thought about creating a list option with the biggest avatar? I feel that the current option the person's face ends up getting very small. Look at the list of groups for whatsapp and telegram applications. The image gets sharper, identifiable, do you agree?

Thanks in advance for any consideration.

![captura de tela 2016-11-14 as 16 23 35](https://cloud.githubusercontent.com/assets/14337850/20277525/18bee44c-aa88-11e6-869e-3bf6ff8f87b6.png)

![captura de tela 2016-11-14 as 16 26 56](https://cloud.githubusercontent.com/assets/14337850/20277502/01cb7c1e-aa88-11e6-9424-54f37f629d80.jpg)

**Comment by rstoenescu** [comment]
Agreed. Will add bigger avatar option.

**Comment by xereda** [comment]
As a palliative, what do you suggest from css to create an element whose avatar is larger? My concern is not to affect the responsiveness of the list in your presentation. Is there something simple to add in <style>, to allow you to use "Multi-line Items" as a basis?

Thanks in advance for any help.

**Comment by rstoenescu** [comment]
Will be available in v0.14.

**Comment by xereda** [comment]
Will the documentation be updated?

**Comment by rstoenescu** [comment]
Yes, as always, when target (in this case v0.14) is released.
