### ISSUE TITLE
Fresh installation app QR code not generating

### ISSUE THREAD

**Issue by arifhussain353** [quasarframework/quasar#1864]
### Software version
Quasar: 0.15.14

### Steps 
I follow these step for installation of `Quasar` cli : 
1) `$ npm install -g vue-cli`
2) `$ npm install -g quasar-cli`

After that i started server with following command : 
`sudo quasar dev --play`

I got this result after running above command: 
![image](https://user-images.githubusercontent.com/12670763/38089620-8db3d3ea-3379-11e8-9bdd-d6e64648e778.png)

### What were you expecting?
Generate `QR code`   for live debugging with `quasar play`

**Comment by pdanpdan** [comment]
There is no more --play.
Please read docs: http://quasar-framework.org/guide/cordova-introduction.html

**Comment by arifhussain353** [comment]
@pdanpdan i found this command on Quasar official documentation

**Comment by arifhussain353** [comment]
What i want is to work code and test live on `quasar play` in my phone. `quasar play` need QR code or  local ip url with 8080 port. Both method is not working for me.

**Comment by pdanpdan** [comment]
Can you please give me the link in the documentation where you found this?

**Comment by arifhussain353** [comment]
@pdanpdan  I am sorry i didn't see the version of Quasar on current url http://v0-13.quasar-framework.org/guide/quasar-play-app.html. Can you please tell me how to do same way with latest version of Quasar?

**Comment by pdanpdan** [comment]
http://quasar-framework.org/guide/cordova-build-commands.html

**Comment by rstoenescu** [comment]
Quasar Play is not required anymore with Quasar v0.15+. The CLI will run your app directly on a phone or in emulator.
