### ISSUE TITLE
Tree nodes don't open

### ISSUE THREAD

**Issue by zagreusinoz** [quasarframework/quasar#1866]
### Software version

Quasar: 0.15
OS: Windows
Node: 8.9.4
Browsers: Chrome

### What were you expecting?
When the prop selected is not supplied on the component then clicking a branch will open that branch, however when it is supplied the branch is not opened.

I would expect that the action would be consistent, it makes it quite fiddly to have to click the arrow icon especially in a mobile environment.

I haven't provided a jsfiddle because this can be seen in quasar play itself:
http://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/tree

**Comment by rstoenescu** [comment]
Hi,

1. Are you confusing "expanded" with "selected"? Two different things. You're talking about selected but then mention about opening a branch.
2. Are you using "sync" modifier for expanded/selected ? Example: `selected.sync`.
3. Everything seems to be working as expected. http://recordit.co/DG21LgttfP

Please do provide a jsfiddle so I can correct your misunderstanding. Thank you.

**Comment by zagreusinoz** [comment]
Hi Razvan

There are inconsistent behaviours:

1. When you click on a branch when there is no selected prop defined then the parent node expands automatically

1. When you click on a branch when there is a selected prop defined then the parent node does not expand automatically 

Here is a short screen recording showing the different behaviours of the tree:
http://recordit.co/8kr8d8LGxx

**Comment by rstoenescu** [comment]
This is the design, yes. How else would you differentiate between selected and expanded? When using selected, expand/collapse is done by clicking/tapping on the arrow. You cannot have them both on the same node triggering in the same way for obvious reasons.

**Comment by rstoenescu** [comment]
Some explanation as to why this is obvious. We're discussing the trigger when using both selected and expanded. You can't have same trigger (click anywhere on a node) for both. Imagine this scenario: one node is already expanded but not selected. User wants to select it, so he/she clicks on it. It's now selected but not expanded anymore. What if the user wants both selected and expanded? It would be impossible. This is why QTree is using different triggers when both features are needed.

**Comment by CheyenneForbes** [comment]
@rstoenescu what about checking if `selectable` and `tickable` were set on a per node basis then making the entire thing "click to expand"?
