### ISSUE TITLE
proposal - create milestone docs for coming dev plan

### ISSUE THREAD

**Issue by aidao** [quasarframework/quasar#1867]
proposal - create milestone docs for coming dev plan so that users can get a big picture of this framework

**Comment by rstoenescu** [comment]
Hi,

This should have gone to docs repo (
But in any case, we're using a feature of Github which lets us set milestones. Click on it. Notice "opened" and "closed".

![milestones](https://user-images.githubusercontent.com/4665641/38125269-f69a0f4c-33f0-11e8-9b83-21e1cc26ae94.png)
