### ISSUE TITLE
Inconsistent Tree Node Behaviours

### ISSUE THREAD

**Issue by zagreusinoz** [quasarframework/quasar#1868]
Hi Razvan

Following on from #1866, the issue is that there are inconsistent behaviours:

1. When you click on a branch when there is no selected prop defined then the parent node expands automatically
2. When you click on a branch when there is a selected prop defined then the parent node does not expand automatically

Here is a short screen recording showing the different behaviours of the tree:
http://recordit.co/8kr8d8LGxx

**Comment by rstoenescu** [comment]
Hi,

This is the design, yes. How else would you differentiate between selected and expanded?

**Comment by zagreusinoz** [comment]
Hi Razvan

You differentiate between selected and expanded because selected is highlighted and expanded shows a different icon and the children are shown.  

You can have them both on the same node at least conceptually - i don't know if this is technically possible - you click on a parent node and it both expands (or collapses) the branch and changes the select prop.  See the attached screencast of Windows Explorer in action.
http://recordit.co/w919NiVn0y

As you see, click on a tree node and it both expands and selects the node.

**Comment by rstoenescu** [comment]
We're discussing the trigger when using both selected and expanded. You can't have same trigger (click anywhere on a node) for both. Imagine this scenario: one node is already expanded but not selected. User wants to select it, so he/she clicks on it. It's now selected but not expanded anymore. What if the user wants both selected and expanded? It would be impossible. This is why QTree is using different triggers when both features are needed.

**Comment by lyb12358** [comment]
Is it possible to have a prop that a node can be selected only when it does not has any child node

**Comment by rstoenescu** [comment]
You can make use of "selectable", "expandable" etc per node properties in your tree model.
