### ISSUE TITLE
v-close-overlay bug when using with pug

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#1871]
![image](https://user-images.githubusercontent.com/25447231/38134678-b851b5ea-3446-11e8-9e10-070758bc9204.png)

```pug
q-popover
            q-list(separator link)
              q-item(v-for="(child,index) of auth.children" :key="index" @click.native="getParentChild(child.id)", v-close-overlay)
                q-item-main
                  q-item-tile(label) {{ child.firstname }} {{ child.lastname }}
```

when i'm using this i'm getting the error above

its like on the render function trying to find _vm.v + _vm.close + _vm.overlay on from template to render function

**Comment by rstoenescu** [comment]
I fail to see how Pug affects this. Can you please provide a jsfiddle? Cannot investigate without one....

**Comment by rstoenescu** [comment]
Seems like a recurrent issue with Pug. Check this: https://github.com/vuejs-templates/webpack/issues/524

**Comment by ralphchristianeclipse** [comment]
@rstoenescu thanks
