### ISSUE TITLE
Checkbox inside Carousel slide causes extra scrolling

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#1872]
Basically, if I set slide padding to 0 (via $carousel-padding or in styles explicitly) and add a checkbox inside, I'd get some unexpected scrolling within a slide.

Here is a fiddle: https://jsfiddle.net/oadguLsg/15/

Thanks!

**Comment by jean-moldovan** [comment]
Probably caused by Ripple effect

**Comment by rstoenescu** [comment]
Hi,

It is indeed an effect of the radial ripple on QCheckbox. Unfortunately, nothing that can be done for it. Or at least nothing that I can think of at the moment. I recommend you add those margins or go with a bigger offset.
