### ISSUE TITLE
Q-Modal bug when root element for  a route

### ISSUE THREAD

**Issue by jimmityglick** [quasarframework/quasar#1873]
Here is a fiddle that reproduces the issue, the steps to reproduce are described in the fiddle:
https://jsfiddle.net/ryan12G/xf0h3qq6/12/

### What did you get as the error?
Component B did not show for Route B after visiting route A which shows a q-modal ( see fiddle )
### What were you expecting?
Component B to show for Route B ( see fiddle) regardless of visiting route A
### What steps did you take, to get the error?
see fiddle

If you wrap the q-modal in a div, the bug does not occur.

**Comment by rstoenescu** [comment]
Hi,

Modals are not meant to be root elements for a route. Conceptually it does not make any sense.
