### ISSUE TITLE
q-btn-dropdown set icon

### ISSUE THREAD

**Issue by ymoreiratiti** [quasarframework/quasar#1876]
### Software version

Quasar: 0,15,10
OS: Windows 10
Node: 8.9.4
NPM: 5.7.1
Browsers: Chrome

### JsFiddle (for Quasar v0.15+ only)
http://jsfiddle.net/YuriTiti13/1pveecta/4/

### What did you get as the error?
Set the icon didn't apply on QBtnDropdown. They keep showing the 'arrow_drop_down' instead of the applyed icon.

### What were you expecting?
On set `icon="more vert"` change the icon of dropdown arrow

**Comment by rstoenescu** [comment]
Hi, The icon refers to the button content itself, not to the arrow.
The arrow comes from Quasar icon set (icon.input.dropdown)
