### ISSUE TITLE
QItemSide letter prop validation with emoji

### ISSUE THREAD

**Issue by ttv20** [quasarframework/quasar#1878]
I try this:
`<q-item-side letter="😃">`
and I got warn:
_`[Vue warn]: Invalid prop: custom validator check failed for prop "letter".`_
I look at the source code (src/components/list/QItemSide.js):
```
letter: {
      type: String,
      validator: v => v.length === 1
    },
```
and then I discover that:
`"😃".length // -> 2`

someone has a solution?
thanks

**Comment by ttv20** [comment]
I found a solution [here](http://blog.jonnew.com/posts/poo-dot-length-equals-two)

**Comment by ttv20** [comment]
the solution [(base on this)](http://blog.jonnew.com/posts/poo-dot-length-equals-two) is replace 'src/components/list/QItemSide.js' line 10 with
```
letter: {
      type: String,
      validator: v => {
        const joiner = "\u{200D}"
        const split = v.split(joiner)
        let count = 0
        for(const s of split){
          const num = Array.from(s.split(/[\ufe00-\ufe0f]/).join("")).length
          count += num
        }
        return count / split.length === 1
      }
    },
```
I didn't open PR because I didn't have time to test this properly

**Comment by bloodf** [comment]
The problems with Emoji is that they may have a more complicated character as 👨‍👩‍👧‍👦, so there is no way to check every node module to see if it's a valid proposition.

**Comment by rstoenescu** [comment]
Why not use the default scope:

```html
<q-item-side>😃</q-item-side>
```
