### ISSUE TITLE
QTable serverside pagination extra request

### ISSUE THREAD

**Issue by dmig** [quasarframework/quasar#1879]
### Software version

Quasar: 0.15.10

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/dmig/yec2a9kL/36/

### What did you get as the error?
When first request `https://fiddle.jshell.net/echo/json/?p=1&l=25&s=&d=0` returns empty list, `QTable` fires another one: `https://fiddle.jshell.net/echo/json/?p=0&l=25&s=&d=0`

### What were you expecting?
QTable won't fire request with `p=0`, because `page=0` breaks pagination counter: it shows `-24-0 of 6` with `p=0` and page size=25
### What steps did you take, to get the error?
Open fiddle and watch network requests

**Comment by rstoenescu** [comment]
This has already been fixed in future 0.15.11.

**Comment by dmig** [comment]
@rstoenescu is there a way to use `dev` version in jsfiddle? This would be useful for testcases.

**Comment by rstoenescu** [comment]
Hi, the "dev" version of Quasar isn't released to NPM, so unfortunately can't use in jsfiddle through CDN, sorry.
