### ISSUE TITLE
Labels of different sizes

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#188]
Labels of different sizes

I'm using labels to illustrate quantity within items in a list. The problem is they are getting disproportionate.

How do I implement this in a more elegant way?

Thank you.

Note: Below is an illustration and part of the code.

![captura de tela 2016-11-14 as 17 29 50](https://cloud.githubusercontent.com/assets/14337850/20279670/8ba7c76e-aa90-11e6-89d7-091a2b5f87c5.png)

```html
<template>
  <div>
    <div slot="header" class="toolbar primary">
      <quasar-search v-model="search" class="primary"></quasar-search>
    </div>
    <div class="layout-padding">
      <div class="list item-delimiter" >
        <div class="item" v-for="esp in listaComFiltro">
            <div class="item-content">
              {{ esp.nome }}
            </div>
            <div class="item-secondary stamp">
              <span class="label circular bg-primary text-white">{{ esp.total }}</span>
            </div>
        </div>
      </div>
    </div>

  </div>
</template>
```

**Comment by rstoenescu** [comment]
Please use forum for questions. Thx.
