### ISSUE TITLE
QDatetime UTC

### ISSUE THREAD

**Issue by erikcunha** [quasarframework/quasar#1882]
Date seems to be formated on q-datetime component when receiving date like 2018-03-03 format, but isn't actually needed or i guess the component must give the option to format or don't, ex: 

https://codepen.io/erikcunha/pen/zWLGKe?page=1&
![image](https://user-images.githubusercontent.com/27955793/38261674-515b28e6-3741-11e8-9d6f-c358f8f7ef85.png)

When picking another date it works normally.

**Comment by rstoenescu** [comment]
But there is `format` prop: http://quasar-framework.org/components/datetime-input.html#Vue-Properties

Please reopen if I am missing something. Thanks.

**Comment by erikcunha** [comment]
@rstoenescu can i show me on codepen fixed ?

**Comment by rstoenescu** [comment]
Have you changed your initial Pen?

Anyway, a few corrections to it:
https://codepen.io/rstoenescu/pen/BrPwLW?page=1&

![time](https://user-images.githubusercontent.com/4665641/38275240-ecb9ab2a-3799-11e8-988a-ca021c8451a2.png)

What is the issue?

**Comment by erikcunha** [comment]
@rstoenescu  when you start the screen without changing anything on date comes like this: 
![image](https://user-images.githubusercontent.com/27955793/38279715-f6d1d06e-3777-11e8-8a09-21ef85cfcad1.png)

when it's wrong for me, i guess it is the i18n and timezone

**Comment by rstoenescu** [comment]
Why did you not specify you're viewing with Safari?
Updated the codepen. Use "/" instead of "-" as date separator.

**Comment by rstoenescu** [comment]
Reference: http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html

**Comment by erikcunha** [comment]
i'm in chrome, my api uses - instead /, it's not possible change this model :/

**Comment by erikcunha** [comment]
but thanks razvan, now i know more what is going on lol

**Comment by rstoenescu** [comment]
Also good to read: https://stackoverflow.com/questions/4310953/invalid-date-in-safari

**Comment by erikcunha** [comment]
The docs says that does not make difference for moment - and /, will return the same thing. QDatetime is using moment right ? shouldn't this case related be all working fine ? 
https://momentjs.com/docs/#/parsing/string-format/

**Comment by rstoenescu** [comment]
No, moment.js is too bloated. Quasar has its own [date utils](http://quasar-framework.org/components/date-utils.html) which rely on the Javascript Date object. Read the links above to understand more on how they work.

**Comment by rstoenescu** [comment]
You can use a Vue computed property with a getter and a setter to translate "-" into "/" back and forth if you can't do it from the API.

**Comment by erikcunha** [comment]
I thought about that but wanted to avoid this path. but thanks Raz
