### ISSUE TITLE
QPullToRefresh causing scroll issues with large tables inside QScrollArea

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar#1884]
### Software version

Quasar: 0.15.10
OS: Mac OS
Browsers: Chrome, Safari, Firefox
- issue seems to exist in chrome, firefox and safari, but it causes the most problems for me in safari.

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/qnokyxdy/20/

### What did you get as the error?
Scroll indicator is moving too fast, causing window scroll, when a large table is wrapped with q-pull-to-refresh. May exist with other content, I noticed it with a table.

### What were you expecting?
Same scroll behavior as "scroll 1" in jsfiddle...

### What steps did you take, to get the error?
1) Load the jsfiddle
2) scroll through "scroll 1" -- you will see scroll indicator move smoothly from abc to abv and reach bottom at abv -- not triggering outer frame scroll attempt until it reaches bottom
3) now scroll through "scroll 2" -- you will see the scroll indicator hits bottom by abi or so (this actually depends on your outer frame height, so make browser window smaller if needed)... once it hits bottom, it triggers a scroll event on the frame and indicator is stuck at bottom and is jittery all the way through the rest of the scroll...

The only difference for these two examples is the second is wrapped in a QPullToRefresh...

**Comment by pdanpdan** [comment]
Isn't it ok if you use it like this?
https://jsfiddle.net/nuth6xp5/4/

**Comment by mattwright** [comment]
@pdanpdan -- thanks, that is very helpful, as it fixes the scroll issue, but has now introduced another bug into the example:

If you look at my fiddle and your fiddle, you will see that mine has the "Running Quasar v0.15.10" directly under the scroll area, while your fiddle now has that text shifted down the page by what I think is the height of the "pull down to refresh" div... -- why does the pull to refresh push this content further down the page than the scroll area it encapsulates?
