### ISSUE TITLE
Q-Table - sort by non visible column

### ISSUE THREAD

**Issue by cjpit** [quasarframework/quasar#1886]
When using q-table, if a non-visible column is used to sort, (using visible-columns), initial pagination sorting does not work.  Making the column visible, and the sort works.

eg

<q-table
      :data="results"
      :columns="columns"
      :loading="busy"
      :pagination.sync="pagination"
      :visible-columns="visiblecolumns"
    >

data () {
      return {
        pagination: {
          sortBy: 'isownconsignment', // String, column "name" property value
          descending: true,
          page: 1,
          rowsPerPage: 5 // current rows per page being displayed
        },
        visiblecolumns: ['pn','description','warehouse','condition_code','qty_oh','unit_price'],
        columns: [
          {
            name: 'isownconsignment',
            field: 'is_own_consignment',
            sortable: true,
            label: 'consignment'
          },
          {
            name: 'pn',
            label: 'PN',
            field: 'pn',
            sortable: true,
            align: 'left'
          }, ................

**Comment by cjpit** [comment]
Sorry about that...
https://jsfiddle.net/d5feev1j/14/

if you then add consignment to the visible-columns, the initial sort works as expected..

Thank you!

**Comment by rstoenescu** [comment]
Sorry it took so long. Totally forgot about this :(
Will be available in 0.17 to be released in a few days.
