### ISSUE TITLE
Change "const Router" by "Vue.router" for Vue-Auth compatibility.

### ISSUE THREAD

**Issue by slegouffe** [quasarframework/quasar#1889]
Hi there ! 

Thanks a lot for your amazing work in Quasar 0.15. 
After some test, I can use vue-auth for authentification in Quasar 0.15. 
In order to respect the new "App Plugins" feature introduce in 0.15 and for vue-auth can work, is it possible to change `Const Router = ` by `Vue.router = ` in `router/index.js` ? 
By exporting a constant, vue-auth do not understand that the router is configured. 

Thanks !

**Comment by rstoenescu** [comment]
Hi,

`src/router/*` files can be edited freely to suite particular needs, so I don't think this should be changed in the starter kit.
