### ISSUE TITLE
Quasar play showing blank page?

### ISSUE THREAD

**Issue by 7ammer** [quasarframework/quasar#189]
I use the QR code to get the correct url, however when trying to connect I just get a spinner loading, stopping and then a white blank screen.

Any advice? I'm not sure how to debug this.

To add to this I've also run `quasar serve` and both the local and external url's show a blank page with the text `Cannot GET /`. UI works fine though.

`quasar dev` works fine.

**Comment by rstoenescu** [comment]
Steps to follow:

1. "quasar dev --play"
2. Select interface if required (Quasar CLI will ask for it)
3. Make sure your phone and the machine you are running is on **SAME network**. Simple test: opening the URL indicated by "quasar dev" in a phone browser should load it. If you can't load it it means your phone is NOT on the same network. Using same router as access point from the machine and phone?
4. Scan QR code with Quasar Play.

You must be running "quasar dev" (without throwing any error) while you use Quasar Play.

**Comment by 7ammer** [comment]
Thanks for the steps.

I've worked out why I was seeing a blank page. I had the below comment at the top of my `index.html` file. Removing this made things work again.

```
<!--<!DOCTYPE html>
<html>
  <head>
  
  </head>
  <body>
  
  </body>
</html>-->
```

`quasar serve` is still showing the text `Cannot GET /` not sure why. Getting the error `Failed to load resource: the server responded with a status of 404 (Not Found)` when trying to go to the url's
* Local: http://localhost:3000
* External: http://192.168.1.102:3000

**Comment by rstoenescu** [comment]
`quasar serve` is meant to make an ad-hoc web server with its root being the folder you specify as parameter. So you can serve the `dist` folder for example **after** you build your app.

Example of using quasar serve:
* you are in the root folder of your app project folder
* Make a production build of your app: `quasar build`
* Make an ad-hoc web server on the production build, located now at `/dist`: `quasar serve dist`
* Open one of the indicated URLs in your browser

One more thing to mention: `quasar serve` is not the same thing as `quasar dev`.

**Comment by rohyadav** [comment]
i also facing same issue and i tried every steps that above mentioned also both PC and device are connected same wifi network and scanned QR code but still showing blank page in my device. 

Please help me out.

**Comment by jheruty** [comment]
@rohyadav Are you running on Windows? I am on Windows 10, and have to disable Windows Firewall in order for the application to load on my mobile device. 

I have tried inbound and outbound rules with no luck, but will update if I find a better solution.
