### ISSUE TITLE
[Feature request] Input (Textfield): add Vue Property lower-case

### ISSUE THREAD

**Issue by bertvandeneynde** [quasarframework/quasar#1892]
Hello.
Feature request
Regarding component: Input (Textfield)
I would like to have an extra Vue Property "lower-case" that does the exact oposite of the "upper-case" property.

upper-case | Boolean | Transform input to upper case.
lower-case | Boolean | Transform input to lower case.

greetings, Bert from Synbits

**Comment by bloodf** [comment]
Made a PR for it https://github.com/quasarframework/quasar/pull/2117

**Comment by rstoenescu** [comment]
Available in 0.16.1

**Comment by bertvandeneynde** [comment]
*High five
