### ISSUE TITLE
[Feature request] Add support to $q.platform.is.electron

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1894]
I was surprised **Electron** is not currently supported by `$q.platform.is` syntax on **v0.15.x** (while it's used by CSS visibility helpers)

**Comment by rstoenescu** [comment]
But it is there...

**Comment by zuck** [comment]
So maybe is it just not documented?

**Comment by rstoenescu** [comment]
Updated docs. You are right. It was missing from docs.
