### ISSUE TITLE
QTabPane activated/deactivated hooks

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#1899]
### Software version

Quasar: 0.15.10
OS: Ubuntu 16.04
Node: 8.9
NPM: 5.6
Browsers: Chrome latest
iOS: -
Android: -
Any other software related to your bug:

### What did you get as the error?
QTabPane with keep-alive prop does not trigger nested components activated/deactivated hooks. So this doesn't work
```
      <q-tab-pane keep-alive name="tab-1">
          <my-nested-comp />
      </q-tab-pane>
```
This works. But the q-tab-pane is destroyed now so it's sadly useless
```
      <q-tab-pane name="tab-1">
        <keep-alive>
          <my-nested-comp />
        </keep-alive>
      </q-tab-pane>
```

### What were you expecting?
Working activated/deactivated hooks, as i need condiditional subscribe/unsubscribe to data streams
### What steps did you take, to get the error?
Use q-tab-pane with keep-alive prop and watch the activated/deactivated hooks at nested components

In the end i am not sure if this is possible to implement

Thank you

**Comment by rstoenescu** [comment]
Hi,

Sorry for the delay. Quickly looked for a solution but I didn't find one unfortunately. Would accept a PR though.

**Comment by emahuni** [comment]
## Here is the solution to this issue, please reopen this. 

This issue does not affect this component only, it's in a lot of components (I tried doing this for other components, even app components; didn't work) if not the whole of Quasar; see this [Fiddle](https://jsfiddle.net/emahuni/vmke39sb/53/), that's on the root app.

Was struggling with this also until I saw [this](https://github.com/vuejs/vue/issues/4205). This comment by [You](https://github.com/vuejs/vue/issues/4205#issuecomment-260642629) sums it up. 

Apparently Vue doesn't trigger these hooks as long as a component is hidden, it uses the existing hidden instance. I think Quasar components or Quasar app does something that make it fall victim of this, I am not sure what exactly, but I think Quasar dev vets should know.

**Comment by emahuni** [comment]
Any news on this?

**Comment by pdanpdan** [comment]
This is implemented and working in the v1 for some time. Are you still having problems?

**Comment by emahuni** [comment]
Hi. Yes it's not working check out the [Fiddle](https://jsfiddle.net/emahuni/vmke39sb/53/). I am using the latest Quasar version RC5 last time i checked, besides that fiddle is just picking up the CDN version Fiddle uses.

**Comment by pdanpdan** [comment]
You forgot to save the fiddle.

**Comment by emahuni** [comment]
That's funny, I can access it without an issue. Anyway, I added a few chars and saved. can you check now?

**Comment by pdanpdan** [comment]
I was talking about keep-alive in tabs.  What you are talking about is something related to vue. We cannot do anything.

**Comment by emahuni** [comment]
you see for you said:
> QTabPane with keep-alive prop does not trigger nested components activated/deactivated hooks.
of which activated and deactivated hooks are not triggering Quasar-wide, and it's coz of that reason. Which means there needs to be a lookout on Quasar structure as to why it is falling in this conundrum.
