### ISSUE TITLE
Router link

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#190]
Router link

Hello,

When you enable a "router link" tag, the list becomes unconfigured.

What is the correct way to add link in a simple list?

See the attached illustration.

Thank you.

```html

<template>
  <div>
    <div slot="header" class="toolbar primary">
      <quasar-search v-model="search" class="primary"></quasar-search>
    </div>
    <div class="layout-padding">
      <div class="list item-delimiter" >
        <div class="item" v-for="esp in listaComFiltro">
          <router-link to="/porMedico">
            <div class="item-content">
              {{ esp.nome }}
            </div>
            <div class="item-secondary stamp">
                <span class="label bg-grey-4 text-grey-8 ">{{ esp.total }}</span>
            </div>
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

```

unconfigured:

![captura de tela 2016-11-14 as 21 19 03](https://cloud.githubusercontent.com/assets/14337850/20286851/07e5c5dc-aab0-11e6-920d-1b620abcb8b1.png)

After comment router-link lines (disable links):

![captura de tela 2016-11-14 as 21 20 39](https://cloud.githubusercontent.com/assets/14337850/20286892/3f3b5c4a-aab0-11e6-9c08-7476e3885fb6.png)

**Comment by rstoenescu** [comment]
`<router-link>` has a `tag` property which you can use. Your template should look like this:

```html
<template>
  <div>
    <div slot="header" class="toolbar primary">
      <quasar-search v-model="search" class="primary"></quasar-search>
    </div>
    <div class="layout-padding">
      <div class="list item-delimiter">
        <router-link tag="div" class="item item-link" v-for="esp in listaComFiltro" to="/porMedico">
          <div class="item-content">
            {{ esp.nome }}
          </div>
          <div class="item-secondary stamp">
              <span class="label bg-grey-4 text-grey-8 ">{{ esp.total }}</span>
          </div>
        </router-link>
      </div>
    </div>
  </div>
</template>
```

Notice `<router-link tag="div" class="item item-link" v-for="esp in listaComFiltro" to="/porMedico">` instead of `<div class="item" ...> <router-link ...> <div class="item-content">.... `

**Comment by xereda** [comment]
Very good!!
That is lack of knowledge in the VueJS on my part. Am sorry!

**Comment by rstoenescu** [comment]
Glad I can help!

**Comment by RoelRoel** [comment]
Accupuncture is proven quackery and should not be promoted!
