### ISSUE TITLE
Feature Request: Datetime picker ( Calendar ) Add Support for multiple active days

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#1900]
Add support for active days on QDatetime picker

**Comment by rstoenescu** [comment]
Hi, Can you elaborate a little?

**Comment by ralphchristianeclipse** [comment]
@rstoenescu we can just reuse the date time picker for calendar purposes

which is good for showing data based on multiple dates and will highlight it depending on a legend color or range color

same as quasar-calendar

**Comment by pdanpdan** [comment]
Close this issue - please follow up in unified #5052
