### ISSUE TITLE
QEditor breaks on Firefox mobile (Android) after a new line

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#1903]
### Software version

Quasar: v.015.10
OS: Android
Browsers: Firefox
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/uojy0Ltr/11/

### What did you get as the error?

The QEditor continues to visually update, but no longer emits an input event and as such the model is never again updated

### What steps did you take, to get the error?

If you type any string into the editor it works, but as soon as you press "return" (going to a new line) on Firefox Mobile on Android, no more input is emitted from the editor, and as such nothing is added to the v-model of the q-editor

so this works:
```
 Hello
```

this does not
```
Hello 
Goodbye
```

the latter only displays `Hello` and the model doesn't update even if you remove everything from the q-editor

edit: more info -- if I press the return key _first_, it works, but focus seems to be taken off of the editor, however as soon as I type text and press the return key it breaks again

**Comment by nothingismagick** [comment]
But the editor itself does continue to work. For the record, this appears to only be an issue on Android Firefox

**Comment by rossity** [comment]
Yes, forgot to mention the above. The QEditor continues to visually update, but no longer emits an input event and as such the model is never again updated.
