### ISSUE TITLE
[Feature Request] emit event using a single param

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar#1904]
For example Carousel components

````
@slide-trigger(oldIndex, newIndex, direction)
````

The rxjs fromEvent stream output only one value, in this case merge them as object {oldIndex, newIndex, direction}

**Comment by rstoenescu** [comment]
Hi,

1. `@slide-trigger="(oldIndex, newIndex, dir) => doSomething({oldIndex, newIndex, dir})"`
2. Define a method in your Vue file `doSomething(oldIndex, newIndex, dir) { ... runSomething({oldIndex, newIndex, dir})... }` then `@slide-trigger="doSomething"`
