### ISSUE TITLE
QInput @change event doesn't work

### ISSUE THREAD

**Issue by llin55** [quasarframework/quasar#1906]
### Software version

Quasar: 0.15.10
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/2skym112/

### What did you get as the error?
QInput does not emit `@change` events - please see the example code above

**Comment by rstoenescu** [comment]
Explanation on proper usage: https://github.com/quasarframework/quasar/issues/1803#issuecomment-374334078

**Comment by llin55** [comment]
I don't see how this explanation is related to the issue. The problem that the `@change` event is NOT being envoked at all, doesn't matter whatever function we define there.

Have you seen my fiddle example?

**Comment by ldenblyd** [comment]
dont forget to change 'v-model' props into ':value'.
https://jsfiddle.net/2nfkes79/
