### ISSUE TITLE
[REQUEST] More customisation of variables in quasar.mat.styl

### ISSUE THREAD

**Issue by afonsoa00** [quasarframework/quasar#1909]
### In the stylus file _quasar.mat.styl_, can we have more customisation?

**### THE PROBLEM:**
We are making a gradual transition to Quasar and need styles to be in sync, namely header tags and breakpoints. The way these variables are set, does not allow me to override them, in the right way. 

E.G:
$flex-gutter = {
  none: 0,
  xs: $flex-gutter-xs,
  sm: $flex-gutter-sm,
  md: $flex-gutter-md,
  lg: $flex-gutter-lg,
  xl: $flex-gutter-xl
}

**### SOLUTION:**
Allow these to be overridden. All it's needed is a '**?**'

$flex-gutter **?**= {
  none: 0,
  xs: $flex-gutter-xs,
  sm: $flex-gutter-sm,
  md: $flex-gutter-md,
  lg: $flex-gutter-lg,
  xl: $flex-gutter-xl
}
$sizes **?**= {
  xs: 0,
  sm: $breakpoint-xs + 1, 
  md: $breakpoint-sm + 1, 
  lg: $breakpoint-md + 1, 
  xl: $breakpoint-lg + 1  
}
$breakpoint-xs-min **?**= 0
$breakpoint-xs-max **?**= $breakpoint-xs
$breakpoint-sm-min **?**= $sizes[sm]
$breakpoint-sm-max **?**= $breakpoint-sm
$breakpoint-md-min **?**= $sizes[md]
$breakpoint-md-max **?**= $breakpoint-md
$breakpoint-lg-min **?**= $sizes[lg]
$breakpoint-lg-max **?**= $breakpoint-lg
$breakpoint-xl-min **?**= $sizes[xl]
$breakpoint-xl-max **?**= 9999px

$headings **?**= {
  display-4: {
    size: 112px,
    weight: 300,
    opacity: .54,
    line-height: $min-line-height,
    letter-spacing: -.04em
  },
  display-3: {
    size: 56px,
    weight: 400,
    opacity: .54,
    line-height: 1.35,
    letter-spacing: -.02em
  },
  display-2: {
    size: 45px,
    weight: 400,
    opacity: .54,
    line-height: 48px,
    letter-spacing: normal
  },
  display-1: {
    size: 34px,
    weight: 400,
    opacity: .54,
    line-height: 40px,
    letter-spacing: normal
  },
  headline: {
    size: 24px,
    weight: 400,
    opacity: .87
    line-height: 32px,
    letter-spacing: normal
  },
  title: {
    size: 20px,
    weight: 500,
    opacity: .87
    line-height: $min-line-height,
    letter-spacing: .02em
  },
  subheading: {
    size: 16px,
    weight: 400,
    opacity: .87
  },
  body-2: {
    size: 14px,
    weight: 500,
    opacity: .87
  },
  body-1: {
    size: 14px,
    weight: 400,
    opacity: .87
  },
  caption: {
    size: 12px,
    weight: 400,
    opacity: .54
  }
}

**Comment by rstoenescu** [comment]
Ok. Would you be so kind to provide a PR?

**Comment by slowaways** [comment]
What's the status of this Issue?

**Comment by afonsoa00** [comment]
The pull request has been created - waiting for it to be merged to production.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kunigaikstis** [comment]
@rstoenescu will these be merged in any time soon?

**Comment by rstoenescu** [comment]
@Kunigaikstis merged. Will be available in v0.17.9 in a few days.
