### ISSUE TITLE
popover in the slot header

### ISSUE THREAD

**Issue by ceau** [quasarframework/quasar#191]
when I put a button  with popover in the slot header, the popover will toggle when click anywhere in the header

**Comment by rstoenescu** [comment]
Popovers (and new Tooltips) have been redesigned to work in ANY scenario in next Quasar version.

**Comment by ceau** [comment]
this is my code , i use the latest version
`<quasar-layout>
      <div slot="header" class="toolbar">
        <button  class="primary">
          <i class="on-left" ref="target1">add</i>
        </button>
       <quasar-popover ref="popover" anchor-ref="target">
  <div class="list item-delimiter highlight">
    <div
      class="item item-link"
      @click="doSomething(), $refs.popover.close()"
    >
      ...
    </div>
  </div>
</quasar-popover>
        
        <quasar-toolbar-title :padding="1" class="text-center">
          动态<i style="font-size:1.5rem" @click="refresher">autorenew</i>
        </quasar-toolbar-title>
      </div>
</quasar-layout>`

**Comment by rstoenescu** [comment]
Yes, I mentioned it will work with **next** Quasar version which will be released soon.

**Comment by ceau** [comment]
excited
