### ISSUE TITLE
Carousel strange behavior with tabs

### ISSUE THREAD

**Issue by gideoncatz** [quasarframework/quasar#1910]
I'm making a wizard with q-carousel, with each slide containing a few controls.
I am interested to be able to go to the next slide only by clicking "next" (so that I can control it based on input validations).

However, I noticed two unexpected behaviors:
1. By hitting "Tab" several times, the user can just go through the slides uncontrollably.
2. Hitting "Shift+Tab" sometimes causes the transition between slides to "stop in the middle".
    For example, in the following jsfiddle, see what happens when you tab until the 3rd slide and then shift-tab back.

https://jsfiddle.net/w9hxrfpo/9/

Thanks,
Gideon

**Comment by votuanphong1983** [comment]
i have exactly the same this issue :(. When we focus on the last control of current page and tab => this bug will occur

**Comment by rstoenescu** [comment]
Hi,

This is out of Quasar's scope as it is a browser behaviour.

However, you can prevent default browser behaviour by catching the TAB key on first and last focusable element in each slide. Example: https://jsfiddle.net/918htke2/3/ -- this example only prevents the TAB key on "Next" button and it's only a starting point. Things left to do: catch if SHIFT is also pressed and add handlers for first elements on each slide.
