### ISSUE TITLE
ESLint Option in fresh install breaks transpiling of assets in Chrome 41

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#1919]
This is a really big deal because the Chrome version that Google Bot uses to [render all sites while crawling is Chrome 41](https://moz.com/blog/google-shares-details-googlebot). Meaning that if you use ESLint on your project, Google won't crawl your site correctly and won't pick up _any_ content for indexing in search results.

### Software version
Quasar: v0.15.10
OS: Windows
Node: Current
NPM: Current
Browsers: Chrome 41 

### What did you get as the error?
`Uncaught SyntaxError: Unexpected token =>` 
(meaning the file wasn't transpiled correctly because it can't recognize the fat arrow function)
The whole page is broken

### What steps did you take, to get the error?
Download mini installer for Chrome 41 Here
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/310958/

Select "Use ESLint" in fresh Quasar starter kit install

quasar dev mat

Open it in Chromium 41

**Comment by rstoenescu** [comment]
ESLint is a tool that highlights if you got linting errors. It's not part of the production distributables. It does not adds any code to the distributables. It does not interfere with the code itself. I fail to see the connection here.

**Comment by nothingismagick** [comment]
I think that the problem is actually a collaboration between ESLint and Babel - this was discussed in great detail today on the Discord server. Note - I have not tried to reproduce the issue, but did find some relevant discussion over at the eslint repo.

https://github.com/eslint/eslint/issues/9848

**Comment by rossity** [comment]
Also, I'm essentially reporting that a fresh install of Quasar is completely broken on Chrome 41 by just choosing "yes" on ESLint when you `quasar init`

That doesn't seem like intended behavior

**Comment by pdanpdan** [comment]
I think it's a clash of package versions. Npm tries to use one that satisfies all, and chooses one with an untranspiled fat arrow. Yarn on the other side puts the good versions (by luck or by good design).

**Comment by nothingismagick** [comment]
That might be one huge reason to switch the recommended package-builder to yarn from npm...

**Comment by rstoenescu** [comment]
Is this still reproducible with CLI v0.16? Try and use yarn with it.
