### ISSUE TITLE
[request] basic select option search

### ISSUE THREAD

**Issue by dmig** [quasarframework/quasar#1923]
### Software version
Quasar: 0.15.10

It'd be very handy to have basic search like native select has:
- if select if unfilterd:
  - typing selects first matching option, no matter if dropdown is open or closed
  - typing break > e.g. 500ms resets internal search field (this may be configurable)
  - more advanced version: allow user to specify search function
- if filtered:
  - typing opens dropdown and focuses filter field

**Comment by rstoenescu** [comment]
Hi,

This outside of Quasar's scope at the moment due to the heavy-load as-is. Will consider it for the future though. Sorry for any inconveniences.
