### ISSUE TITLE
[request] datatable serverside filtering w/o pagination

### ISSUE THREAD

**Issue by dmig** [quasarframework/quasar#1924]
### Software version
Quasar: 0.15.10

Right now filtering and pagination are closely tied together. To filter data on server side I have to enable server side pagination.
I want to use serverside filtering with local pagination. Right now this can be achieved with hack:
1. specify custom `filter-method`
2. _make sure rowset isn't empty before performing search_ -- this is awful, but doesn't work otherwise 
3. inside filter method make request and return values

**Comment by dmig** [comment]
Here is the condition which forces to use hack, on line 76: https://github.com/quasarframework/quasar/blob/27258b57b0b3aebe00bfd907745d2aebebff4eba/src/components/table/QTable.js#L76-L81

**Comment by dmig** [comment]
BTW, isn't that an error in line 83? Missing `rowsNumber` prop?

**Comment by rstoenescu** [comment]
No such hacks are required. Put a reference on the QTable then on your "request" method check **if filter changed**, and if so, then `tableData = this.$refs.yourRefName.filterMethod(rows, props.filter)` and return early before sending data to server.
