### ISSUE TITLE
Toolbar additional classes not working - coloring

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#193]
Hi!
When using in layout: 
`<div slot="header" class="toolbar secondary">`
only toolbar class survives build and it is impossible to apply color in this way.

**Comment by rstoenescu** [comment]
Hi,

You are definitely misusing something. This definitely works. Paste your layout template so I can help you. Closing bug meanwhile.

**Comment by murbanowicz** [comment]
```
<quasar-layout>
        <div slot="header" class="toolbar secondary">
```
I can replace secondary with any color - not working

**Comment by rstoenescu** [comment]
You mean one of the colors from the Color Palette? (http://quasar-framework.org/api/css-color-palette.html#Stylus-Color-Variables).
Give some examples of what colors you tried. I am 100% this has no issues. Use chrome dev tools to check if your CSS messes up Quasar's or copy-paste your layout template here to identify what is wrong in your usage. Thanks!
