### ISSUE TITLE
QModal maximized issue with forms in Chrome & Safari on iOS

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#1931]
### Software version

Quasar: v0.15.10
OS: iOS
Node: 8.9.4
Browsers: Chrome / Safari
iOS: 11.3

Test link: https://ignite.cdnrg.com/files click on Arrow > beside first form

### What did you get as the error?
Caret moving around on scroll. Text inputs showing blank when typing in them. Once you scroll the letters re-appear.

### What were you expecting?
Inputs to accept and show text like normal inputs.

### What steps did you take, to get the error?
Create a QModal and place a long form inside.

![image-2](https://user-images.githubusercontent.com/1187622/38687935-b94d190e-3e2c-11e8-8ca3-26d12b422b10.png)
![image-1](https://user-images.githubusercontent.com/1187622/38687936-b96d21f4-3e2c-11e8-9c6b-0c2b70e7cc2d.png)
![image](https://user-images.githubusercontent.com/1187622/38687937-b986c622-3e2c-11e8-9d54-eacebf12ce0d.png)

**Comment by pdanpdan** [comment]
I think this might be related to this:
https://github.com/quasarframework/quasar/pull/1008

If you can test please try https://github.com/quasarframework/quasar/pull/1819 and tell me if it fixes the problem.

**Comment by cdnrg** [comment]
Thanks pdanpdan,

I tried remote debugging to verify the visibility was changed in Safari and still get the same issue. 

![image](https://user-images.githubusercontent.com/1187622/38692080-99d9dd04-3e37-11e8-8d9c-30010150349b.png)
![image-2](https://user-images.githubusercontent.com/1187622/38692209-ef0cec26-3e37-11e8-8868-3c12480753bb.png)
![image-1](https://user-images.githubusercontent.com/1187622/38692210-ef2588ee-3e37-11e8-8412-a8c1c45fc4d4.png)

**Comment by rstoenescu** [comment]
The UIWebView that is by default used is very very buggy. This is one of those impossible issues.
To alleviate, please try to install WkWebView which is far superior: https://github.com/apache/cordova-plugin-wkwebview-engine
