### ISSUE TITLE
QScrollArea problem on Android devices

### ISSUE THREAD

**Issue by alexpvieira** [quasarframework/quasar#1937]
### Software version

Quasar: 0.15.14
OS: Windows 10
Node: 8.9.4
NPM: 5.6.0
Browsers: Chrome 65.0.3325.181
iOS:
Android: 7.1.1 / 6.0.1
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/7urtx8sc/6/

### What did you get as the error?
The scroll area doesn't work as it should on cordova mode / android devices. Haven't tested on iOS. It's woking fine in the browser or in the device if you use the mouse to scroll the page.

### What were you expecting?
The scroll area to be responsive. The scroll only work if you keep scrolling up and down for a while.

### What steps did you take, to get the error?
Fiddle above. I'm using a q-list inside of a q-scroll-area inside of a q-tabs

**Comment by alexpvieira** [comment]
I've made a video showing the problem.

https://drive.google.com/file/d/1VCD1eHBTbFRTUU7JyfvMeHdOQDjr1FmS/view?usp=sharing

**Comment by nothingismagick** [comment]
Are you sure the problem is q-scroll and not q-list?

**Comment by alexpvieira** [comment]
@nothingismagick how can I be sure that the problem is on the q-list?

**Comment by nothingismagick** [comment]
If you remove q-scroll, does the problem persist?

**Comment by rstoenescu** [comment]
Seems to work with Quasar v0.17, so closing.
