### ISSUE TITLE
Tree is not expandable when labels are equal

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#1940]
Please see: https://jsfiddle.net/9qv1n4uk/22/

### What did you get as the error?
The 'foo' subtree is not shown and therefore not expandable.
The 'bar' subtree is shown properly, and expanded by default, as it should.
This is caused by 'node-key' set to 'label', and label not being unique.

### What were you expecting?
II would expect an error of some sort

### What steps did you take, to get the error?
Renamed the children's label to be equal to the parent's label

**Comment by rstoenescu** [comment]
Hi, Use `node-key` property to specify unique values for each node. If label is the same, then specify some other prop of nodes that is unique.
