### ISSUE TITLE
QEditor on MSIE 11

### ISSUE THREAD

**Issue by KEYELEMENTS** [quasarframework/quasar#1943]
It seems that QEditor does not update model on MSIE 11. It's easy to test e.g. http://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/editor  and try to change  a text in a qeditor.   The changes are not propagated to other qeditors although the model is the same.

**Comment by rossity** [comment]
@rstoenescu does this fix also address #1903 ?

**Comment by pdanpdan** [comment]
@rossity #1903
I'm not very sure.
Can you please try to debug your app and provide any console output?

**Comment by rossity** [comment]
@pdanpdan I hooked up mobile debugger and no console logs/errors pop up at all after QEditor model stops updating
