### ISSUE TITLE
 CSS Quasar Inputs Like jsfiddle.net

### ISSUE THREAD

**Issue by porgamador** [quasarframework/quasar#1948]
Hey guys,
Would, by any chance, there be the possibility to define the input components of Quasar close to those of jsfiddle.net? IE ( https://jsfiddle.net/user/settings/ )

Thank you very much!

Pessoal tudo bem,
Haveria  possibilidade de definir o estilo dos componentes de input do quasar semelhante aos do jsfiddle.net, exemplo:
https://jsfiddle.net/user/settings/
Obrigado!!

![quasar](https://user-images.githubusercontent.com/34717525/38884874-5d65f47a-4247-11e8-9b33-235f279c29bd.png)

**Comment by rstoenescu** [comment]
Hi, We are following Material Guidelines and this would deviate a lot from the specs, so sorry. But, it can be done in app-space by adding a few CSS lines.
