### ISSUE TITLE
q-btn-toggle @change is missing

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#1950]
Well, I think it's kind of useful to have `@change` event supported by `q-btn-toggle`. Good old `q-toggle` already does that.

Thanks!

**Comment by pdanpdan** [comment]
It's not missing.
If you use `:value="model" @change="val => { model = val; doSomethingWithVal(val); }"` it's going to work.
If you use `v-model="model"` the model is kept in sync, so we don't emit a change event.

**Comment by jean-moldovan** [comment]
Thanks for clarification, @pdanpdan !

**Comment by marianpa** [comment]
The `@change` event should be emitted whether or not the model is bind to component. The same way as it is in `q-input`. For now looks like there is inconsistent behavior. Another argument why it should work this way is that Vue works exactly this way for `input` elements (eg. `<input type="checkbox" [...] />`). For now, the `<input type="checkbox"` is the only way to achieve that (so without quasar component).

**Comment by anktx** [comment]
This works:
```
        <q-btn-toggle
          @update:model-value="valueChanged"
        />
```
