### ISSUE TITLE
Options to disable QSelect items and set classes for them

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1953]
Hi,

We have a QSelect component to list the sizes of the current product, however after the users bought some sizes these sizes become out of quantity, we want to make these items `disabled` and  set `text-decoration: line-through`

All the best,
Mohammed

**Comment by floresj** [comment]
Disclaimer: *I've been only using this framework for about three days so my suggestion is probably not optimal. I'm curious as to what the correct solution is for this.*

But in any case, it seems that `QSelect` under the hood uses the [```<q-popover />```](https://github.com/quasarframework/quasar/blob/dev/src/components/select/QSelect.vue#L71) component. You could create a component that utilizes the ```<q-popover />``` and simply implement your own custom logic with your styling needs with `<q-list></q-list>` For instance, you could reference one of the `<q-popover>` examples [here](https://github.com/quasarframework/quasar-play/blob/master/src/pages/showcase/popups/popover.vue#L41). I had a similar situation where I wanted to add some additional customization to the items in the dropdown. However, the `q-popover` is rendered outside of the immediate component and directly rendered in the `<body>` so I didn't see where I could add a custom css class to customize the contents of the `<q-popover>` from a `<q-select>`.

**Comment by Manfred047** [comment]
For disable an specified item from q-select, use disable in option list:

```
const items = [
        {
            label: 'option1',
            value: '0',
            disable: true
        },
        {
            label: 'option2',
            value: '2',
            disable: false
        }
    ];
```

**Comment by zanzara** [comment]
Sorry for disturbing this ancient post, but I'm really not an expert in CSS/SCSS/SASS and would ask here what Stylesheet Overwrite I could do to achieve this `text-decoration: line-through`  format when option is disabled.
In the inspector it looks like this is the selector:

![Bildschirmfoto zu 2020-12-14 17-21-41](https://user-images.githubusercontent.com/7381054/102107019-8b84fc00-3e31-11eb-88af-dbad4fa4661f.png)
