### ISSUE TITLE
QActionSheet does not re-render

### ISSUE THREAD

**Issue by ftKnox** [quasarframework/quasar#1954]
### Software version

Quasar:v0.15.10
OS: MacOS
Node: 8
NPM:
Browsers: Safari
iOS: Safari
Android:
Any other software related to your bug:

### What did you get as the error?
QActionSheet sheet does not seem to re-render on changes to actions property. Is this the expected behavior? If so, I couldn't find anything in the documentation stating as such.

### What were you expecting?
Action sheet to re-render on actions property changes

**Comment by pdanpdan** [comment]
Please provide a jsfiddle

**Comment by ftKnox** [comment]
crap, sorry it does re-render. next time I will try a fiddle out before posting an issue. here is js fiddle for posterity

https://jsfiddle.net/akygwr93/24/
