### ISSUE TITLE
Vue non-single file fails on App.vue

### ISSUE THREAD

**Issue by JCKodel** [quasarframework/quasar#1957]
### Software version

Quasar: 0.15.10
OS: Windows 10
Node: 8.9.3
NPM: 5.8.0
Browsers: Chrome 65
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

Not applicable.

### What did you get as the error?
A blank page, no errors on console.

### What were you expecting?
A functional app.

### What steps did you take, to get the error?
1) Create the app with quasar init
2) Separating the javascript from each .vue file into its own .js file (and setting `<script src="./fileName.js" />` accordingly.
3) Setting `build.vueCompiler: true` on quasar.conf.js
4) Changing each `import` from routes.js to add the `.vue` extension (as the .vue file is the root one)

When App.vue has inline javascript (one-file template), the page renders itself ok.
When App.vue has an `<script src="./App.js"/>` and the App.js file contains `export default { name: "App" }`, a blank page is rendered.

And, yes, I don't like single-file templates (as my IDE has limited support for it).

**Comment by rstoenescu** [comment]
Hi,

This is more of a question for Vue team. It is out of Quasar's scope. Single file Vue components are handled by vue-loader which does a lot of "magic" under the covers.

If you wish to not use .vue files, then:
1. You still need to import your js file (do not simply add a script tag in your index.html)
2. Manually register the Vue component (`Vue.component(..., { ... })`)
3. You can either have a template specified (and yes, build.vueCompiler needs to be set to "true"), or use render functions directly.

**Comment by JCKodel** [comment]
It's not about not using .vue files, it's about how to load them.

In normal webpack projects, all I would need to do is `import App from "./App.vue";` (notice the .vue extension)

The problem is that Quasar encapsulates that kind of configuration (the main.js).

So, in the Quasar way, how can I load the correct App root file (.vue, in my case).

In other words:
`import App from "./App";` => Requires and work with a single-file .vue
`import App from "./App.vue"; => Allows to load .vue files with separated .js files (non single-file).
