### ISSUE TITLE
[Request] auto-grow for q-input horizontally

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1958]
Currently q-input has `auto-grow` for text-areas vertically.

I require an option that my (non-textarea) inputs auto-grow horizontally.

**Comment by rstoenescu** [comment]
It already grows to the available horizontal space... Did I miss anything? jsFiddle pls.

**Comment by mesqueeb** [comment]
@rstoenescu
This is what I meant:
![2018-07-20 11 29 26](https://user-images.githubusercontent.com/3253920/42980015-45deb946-8c10-11e8-914d-b00c3044250d.gif)

The ability to set a `min-width` and make the input auto grow based on the content.

I use it all the time in a lot of places throughout my apps and websites.
I usually use this small package:
https://github.com/yuanqing/autosize-input

Then I wrapped that in a directive:
```js
  import autosizeInput from 'autosize-input'

  Vue.directive('autowidth', {
    inserted(el, binding) {
      Vue.nextTick(function () {
        autosizeInput(el)
      })
    }
  })
// and use it like v-autowidth on an <input>
```

However, it doesn't work with inputs wrapped in <q-input> because the directive is not applied on the correct element.

Could I implement this functionality and make a PR for you? I would use that package as dependency, unless you want me to build it from scratch, I can give it a shot, make a PR.
What do you think?

**Comment by mesqueeb** [comment]
@rstoenescu Can you re-open this issue?

This feature request of mine still stands, as it's very important for my app! : D

**Comment by mesqueeb** [comment]
I still require the autogrow feature for text input fields with the ability to grow horizontal.
The current "[autogrow](https://v1.quasar-framework.org/vue-components/input#Example--Autogrow)" in V1 gives me new lines.

I require the actual div to grow horizonally:
![2018-07-20 11 29 26](https://user-images.githubusercontent.com/3253920/42980015-45deb946-8c10-11e8-914d-b00c3044250d.gif)

**Comment by mesqueeb** [comment]
@rstoenescu
Since this is still very high on my wish list and not yet implemented, can you re-opens this Request, or should I copy the contents into a new issue?

I need vertical autogrow with both QInput as QSelect.

**Comment by leonardoalvesprodepa** [comment]
<template>
  <q-page class="flex flex-center">
    <q-input
      **:input-style="{width: `${text.length/2}em`, maxWidth: '300px', minWidth: '50px'}"**
      outlined
      v-model="text"
    />
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  data () {
    return {
      text: 'adfasd asdfasdf fdfdf df kjkfjdkjdkfjkdf difdhfidhifhidh f '
    }
  }
}
</script>

**Comment by leonardoalvesprodepa** [comment]
` <q-input
      :input-style="{width: `${text.length/2}em`, maxWidth: '300px', minWidth: '50px'}"
      outlined
      v-model="text"
    />`

**Comment by Tofandel** [comment]
I made a plugin with a directive for it

`vAutoGrow.js`
```js
const calcTextWidth = (input, text) => {
  const span = document.createElement('span');
  span.textContent = text;
  span.classList = input.classList;
  span.style = input.style;
  Object.assign(span.style, {
    maxWidth: 'none',
    width: 'auto',
    whiteSpace: 'nowrap',
    position: 'absolute',
    opacity: '0',
    visibility: 'hidden',
  });
  input.after(span);
  const width = span.getBoundingClientRect().width;
  span.remove();
  return width;
};

export default {
  install(app) {
    app.directive('autogrow', (el, binding) => {
      const input = el.querySelector('input');
      if (input) {
        let  width = calcTextWidth(input, input.value);
        if (!width) {
          width = typeof binding.value === 'string' || typeof binding.value === 'undefined' ?
            calcTextWidth(input, binding.value || input.placeholder) : binding.value || 10;
        }
        input.style.width = width + 'px';
      }
    });
  },
};
```

Usage

```js
vue.use(vAutoGrow);
````

```vue
<QInput placeholder="When empty the min width is the placeholder size" v-autogrow/>

//With custom empty width
<QInput v-autogrow="60"/>
```
