### ISSUE TITLE
Quasar"export 'vuelidate' was not found in 'quasar'

### ISSUE THREAD

**Issue by adrianofoschi** [quasarframework/quasar#1959]
### Software version

Quasar: 0.15.14
OS: Linux 4.16.2
Node: 9.11.1
NPM: 5.8.0
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
I'm trying to include "vuelidate" plugin as documention
http://quasar-framework.org/components/form-validation.html#Installation-of-Vuelidate

### What were you expecting?
The plugin should be included.

### What steps did you take, to get the error?
Quasar dev compilation return me this error:
"export 'vuelidate' was not found in 'quasar'

**Comment by rstoenescu** [comment]
Hi, please read the doc page again. It's very clear on what you should do. Pay attention to details... like importing vuelidate from vuelidate, not Quasar.
