### ISSUE TITLE
[Feature] Built-in support for copying files to dist/ in CLI

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1960]
In order to let my SPA/PWA to work correctly on [Netlify](https://www.netlify.com/), I had to add a `_redirects` file to the root folder of my `dist/`.

In order to do it, I configured my `quasar.conf.js` this way:

```
build: {
  // ...
  extendWebpack(cfg) {
    //...

    // copy _redirects file
    const CopyWebpackPlugin = require('copy-webpack-plugin')
    cfg.plugins.push(
      new CopyWebpackPlugin([
        {
          from: 'src/_redirects',
          to: cfg.output.path
        }
      ])
    )
  }
}
```

But it means I had to add one more dev dependency to my app (`copy-webpack-plugin`) while **Quasar CLI** already included it. 

My proposal is to add a new entry in `quasar.conf.js` to let devs specify a list of "copying patterns" using the same format of `copy-webpack-plugin`, e.g.:

```
build: {
  files: [
    { from: 'source', to: 'dest' }
  ]
}
```

**Comment by jean-moldovan** [comment]
What if you use npm scrips to do that?
In package.json:
```
    "build": "quasar build && cp web.config dist"
```

**Comment by zuck** [comment]
Yes, I could do it, but I still think we should add built-in support to `quasar.conf.js`: Quasar is already doing the very same thing for the `statics` folder (opinionated). Adding this feature would handle `statics` folder just like any other file/folder the dev want to copy to the final build _as is_, making it explicit:

```
// ...
build: {
  // ...
  files: [
    { from: 'statics' },
    // Other files/folders here...
  ]
}
```

**Comment by nothingismagick** [comment]
I think it is a really good idea. @rstoenescu - what do you think? @zuck - fancy making a pull request that references this issue?

**Comment by rstoenescu** [comment]
You don't need to npm install `copy-webpack-plugin`. It's already in node_modules due to Quasar CLI.

The webpack 4 CLI will have a build > chainWebpack () method which will make it reaaallly easy to change Quasar's default webpack config using [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain). As a result, you'll be able to add your copy-webpack-plugin options there.
Looking ahead, there's no reason to bloat the default config with this option.

**Comment by turigeza** [comment]
@zuck thank you for the example
