### ISSUE TITLE
navigateFallback in SWPrecacheWebpackPlugin

### ISSUE THREAD

**Issue by mattisback** [quasarframework/quasar#1963]
Quasar:  0.15 Starter Kit 1.0.2

PWA fallback using the navigateFallback option in SWPrecacheWebpackPlugin cannot be set in webpack-config.js because it's auto generated..

Here's the webpack-conf.js code for generating SWPrecacheWebpackPlugin.
```js
if (cfg.ctx.mode.pwa) {
      const SWPrecacheWebpackPlugin = require('sw-precache-webpack-plugin')

      webpackConfig.plugins.push(
        // service worker caching
        new SWPrecacheWebpackPlugin({
          cacheId: cfg.pwa.cacheId,
          filename: cfg.pwa.filename,
          staticFileGlobs: [`${cfg.build.distDir}/**/*.{${cfg.pwa.cacheExt}}`],
          minify: cfg.build.minify,
          stripPrefix: cfg.build.distDir + '/'
        }),

        // write manifest.json file
        {
          apply (compiler) {
            compiler.plugin('emit', (compilation, callback) => {
              const source = JSON.stringify(cfg.pwa.manifest)

              compilation.assets['manifest.json'] = {
                source: () => new Buffer(source),
                size: () => Buffer.byteLength(source)
              }

              callback()
            })
          }
        }
      )
    }
```

We want to insert
`navigateFallback: '/index.html'` into `new SWPrecacheWebpackPlugin({})` so that the service worker can fall back to index.html on routes that aren't index.html whilst offline.

For example, if you're offline an using PWA and you navigate to 'myapp.com' it works, but if you navigate to 'myapp.com/route1' and you're offline, the serviceworker doesn't have a fallback activated an so you get a 404 error.  

Adding `navigateFallback` into the SWPrecacheWebpackPlugin config would fix this.

**Comment by mattisback** [comment]
I've tested this and adding `navigateFallback` as mentioned above does fix the issue.  Is there some way to allow the `SWPrecacheWebpackPlugin` config to be extended?  Or could we automatically add `navigateFallback` if `vueRouterMode` is set to `history`?

**Comment by rstoenescu** [comment]
Hi,

Will add a prop in quasar.conf to be able to extend the webpack plugin's config.

Please also note that a webpack 4 along with workbox is almost ready to be released. Workbox is the successor of sw-precache and the future of PWAs.

**Comment by mattisback** [comment]
Thanks,
I figured it might not make sense to update with workbox being almost ready but it would make sense to allow a similar option with it.

**Comment by rstoenescu** [comment]
Moved to the appropriate repo: https://github.com/quasarframework/quasar-cli/issues/112
