### ISSUE TITLE
V0.15.10 -  No Cancel and Set buttons are shown-IOS theme- Viewed in android chrome.

### ISSUE THREAD

**Issue by trendchaser4u** [quasarframework/quasar#1972]
No Cancel and Set buttons are shown in Date time and colour picker. Please find the attachment below

![screenshot_20180424-181410](https://user-images.githubusercontent.com/8087340/39188392-516da054-47ed-11e8-80fc-cce59f4cf4d7.png)

![screenshot_20180424-181445](https://user-images.githubusercontent.com/8087340/39188402-568689fc-47ed-11e8-8abe-ae6fc44def52.png)

Along with above bug, No colour area found in colour picker PFA

![screenshot_20180424-181825](https://user-images.githubusercontent.com/8087340/39188444-765123d2-47ed-11e8-9200-098472dae866.png)

![screenshot_20180424-181830](https://user-images.githubusercontent.com/8087340/39188448-78cc9d1c-47ed-11e8-8bc2-c75e449e2bd6.png)

Tested platform info

![screenshot_20180424-181836](https://user-images.githubusercontent.com/8087340/39188484-8e278078-47ed-11e8-9ce2-de69d6a7dc04.png)

**Comment by pdanpdan** [comment]
Please check the colours for the buttons with inspector and also provide any console errors.
For the missing colour picker also check console.

**Comment by trendchaser4u** [comment]
@pdanpdan it seems CSS issue. I found one solution to date picker. Please remove the class *.relative-position* in the modal header (cancel and set) it will fix the bug. am working on color picker and let u know if any progress :)

**Comment by trendchaser4u** [comment]
@rstoenescu Android version 7.0 , Webview -> chrome stable. i couldn't found the exact webview  version.

**Comment by trendchaser4u** [comment]
Issue fixed and closed.
