### ISSUE TITLE
[Request] Notify Offset

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#1973]
Pretty simple request but it would be nice to have an `offset` object as a part of the Notify plugin.

Example: 
```
this.$q.notify({
  message: `A text with your alert's awesome message`,
  timeout: 3000,
  type: 'positive',
  color: 'positive',
  position: 'top-right', // 'top', 'left', 'bottom-left' etc
  offset: {
   top: '30px',
   right: '-30px',
   left: '-30px'
  }
})
```

This would make it much easier to account for header and footer toolbars, since oftentimes it looks better for the notification to not appear directly over the toolbar (which can cover tabs etc.).

**Comment by rstoenescu** [comment]
Hi,

The Notify plugin unfortunately does not allow this. The "position" prop injects a notification into the respective position batch (there's groups for each position), so the nice animations can work correctly. As a result, you can't have each notification with its own offsets. Closing this & sorry for any inconveniences.

**Comment by Landen13** [comment]
+1 for this

**Comment by BasitCode** [comment]
I met this problem too, had to write a global style for this
```
.q-notifications__list--bottom {
   bottom: 50px;
}
```
