### ISSUE TITLE
[wish] add "animate-pulse" class

### ISSUE THREAD

**Issue by nahuel** [quasarframework/quasar#1979]
Currently the only continuous animations defined are `animate-spin animate-spin-reverse animate-blink animate-bounce`. From these only `animate-bounce` is good to attract attention to some icon, but the jumping fx can be annoying in some situations. It will be good to add `animate-pulse` implementing an effect like http://materializecss.com/pulse.html or https://codepen.io/jtype/pen/GqqNgm . Nicer if you can also apply the animation to rectangular buttons.

**Comment by rstoenescu** [comment]
Hi,

The current work-load is very heavy and no hopes of getting lighter in the future too. If you feel like it, would you be so kind to provide a PR on this? Currently this is by no means "critical", so closing it but waiting for a PR. Thanks and sorry for any inconveniences.

**Comment by stefanvanherwijnen** [comment]
The easiest solution seems to be:
```
.animate-pulse
  animation q-pulse 2.7s infinite /* rtl:ignore */

@keyframes q-pulse
  0%
    box-shadow: 0 0 0 0px rgba(0, 0, 0, 0.2)
  100%
    box-shadow: 0 0 0 15px rgba(0, 0, 0, 0)
```
However, I think this is quite CPU expensive. Is this a problem?
