### ISSUE TITLE
Tooltip in FAB button

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#198]
New feature suggestion.

Enable tooltip addition on an internal button (quasar-small-fab) of a FAB button.

Notice the FAB button in the Inbox app (new Gmail).

desktop:
![p1ks2afhyx](https://cloud.githubusercontent.com/assets/14337850/20348461/aedd62b8-abec-11e6-8488-95aea6ff3e67.gif)

app ios:
![3hajjirnvc](https://cloud.githubusercontent.com/assets/14337850/20348750/421a3be0-abee-11e6-8d76-55435e69656a.gif)

**Comment by rstoenescu** [comment]
Haven't tested yet, but with the new Tooltips on v0.9 this will be possible.

**Comment by xereda** [comment]
The deadline for this version is this year yet?

**Comment by rstoenescu** [comment]
Next week.

**Comment by rstoenescu** [comment]
![screenshot from 2016-12-18 16 41 51](https://cloud.githubusercontent.com/assets/4665641/21294253/2df0ba74-c541-11e6-8ec4-8ab86e0065c4.png)

Next Quasar version will allow injecting a Tooltip. Sample:
``` html
<q-small-fab class="secondary" @click.native="toast('alarm')" icon="alarm">
   <q-tooltip anchor="center left" self="center right" :offset="[-20, 0]">Alarm</q-tooltip>
</q-small-fab>
```
