### ISSUE TITLE
[Bug] Error when navigating to other page while select component is still open

### ISSUE THREAD

**Issue by anhnhoktvn** [quasarframework/quasar#1980]
### Software version

Quasar: v0.15
OS: Linux
Node: 8.9
NPM: 5.7
Browsers: Chrome
iOS: 
Android: 
Any other software related to your bug:

### What did you get as the error?
I found an error with select component in v0.15 . If I change route while the select component is still open, it will cause error. See image included.

### What were you expecting?
No error emited in console panel.
### What steps did you take, to get the error?
- Create 2 pages and a select component. 
- Open the dropdown menu of select component
- Change to other page while the dropdown menu is still open.
- Error will be show in the console panel (developer tools)

### Image
[https://imgur.com/a/gE7peIq](https://imgur.com/a/gE7peIq)

**Comment by rstoenescu** [comment]
Hi, what error. Give some details pls...

**Comment by anhnhoktvn** [comment]
Sorry, can not reproduce it.
