### ISSUE TITLE
There is no RTL boolean in Arabic i18n

### ISSUE THREAD

**Issue by marekkaczkowski** [quasarframework/quasar#1981]
Please compare **Hebrew** lang
https://github.com/quasarframework/quasar/blob/dev/i18n/he.js
and **Arabic**
https://github.com/quasarframework/quasar/blob/dev/i18n/ar.js

there is no `rtl: true` for Arabic.

**Comment by rstoenescu** [comment]
Pls PR if you would be so kind. Thank you.
