### ISSUE TITLE
[Data table]  What happened to the resposive mode in the version 0.15?

### ISSUE THREAD

**Issue by FredericoSFerreira** [quasarframework/quasar#1983]
### Software version

Quasar: 0.15
OS: Linux Mint
Node: 9.11.1
NPM: 5.6.0
Browsers: google crhome 64.0.3282.119
iOS:
Android:
Any other software related to your bug:

In version 0.14 I used to resposive true it generated me the table of the form according to the image, which is great for cell phones, as I do I leave my dataTable in version 0.15 in the same way, I see that the responsive property has been removed for what reason have withdrawn this incredible resource?

![0 14](https://user-images.githubusercontent.com/5566899/39304251-7ab15756-492f-11e8-9aed-83a689cb6320.png)

![015](https://user-images.githubusercontent.com/5566899/39304261-8348bf08-492f-11e8-8478-b5b527459b40.png)

**Comment by rstoenescu** [comment]
Hi,

This was a feature of v0.14 DataTable only. Unfortunately, people wanted DataTable to be able to fully customisable, and the new architecture of the component does not allow this feature anymore due to technical issues. Sorry for any inconvenience.
