### ISSUE TITLE
clearable for q-input inside q-collapsible not working

### ISSUE THREAD

**Issue by joerg-walter-de** [quasarframework/quasar#1984]
<q-collapsible icon="lock" label="title">
        <q-input
            v-model="varName"
            type="textarea"
            clearable
            class="full-width"
        />
      </q-collapsible>

**Comment by pdanpdan** [comment]
What is not working?
https://codepen.io/anon/pen/xjRZxg

**Comment by aprixon01112017** [comment]
Sorry. It is working!
