### ISSUE TITLE
[QStepper] QStepperNavigation breaks on small screens due to fixed height

### ISSUE THREAD

**Issue by Miosss** [quasarframework/quasar#1985]
### Software version

Operating System                        Windows_NT(10.0.16299) - win32/x64
NodeJs                                  9.11.1

Global packages
  NPM                                   5.8.0
  yarn                                  Not available
  quasar-cli                            0.15.14
  vue-cli                               2.9.3
  cordova                               Not available

Important local packages
  quasar-cli                            0.15.14 (Quasar Framework CLI)
  quasar-framework                      0.15.10 
  quasar-extras                         1.0.2   (Quasar Framework fonts, icons and i18n.)
  vue                                   2.5.16  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                            3.0.1   (Official router for Vue.js 2)
  vuex                                  3.0.1   (state management for Vue.js)
  electron                              Not available
  babel-core                            6.26.0  (Babel compiler core.)
  webpack                               3.11.0  
  webpack-dev-server                    2.11.1  (Serves a webpack app. Updates the browser on changes.)

Browsers: Chrome 60+ and probably others with small screens (telephones with Chrome for sure)

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/k3fskmLt/

or bit more complex, but breaks on wider screens:
https://jsfiddle.net/30qhqu5s/

### What did you get as the error?
If  u use one of the fiddles and set very narrow screen (I mean really narrow, like 100-150px) you can see that content of the layout stop pushing footer down - instead it becomes hidden belowe footer and thus unusable.
Fiddle is only to observe the case - in my app this situation happens under around 370px - which is normal width for many phones, like Samsung Galaxy S5.

From what I observe, to reproduce this bug you need QLayout + QStepper and then buttons with texts long enough to become unwrappable with given width of the screen. I use QStepperNavigation with 2 buttons with short texts and it is enough to break. In the fiddle the texts are long so it is easier to see.

My guess is that QPage dynamic page calculation break with QStepper + unbreakable texts on buttons + tall footer. But in my app such config makes app unuasble, because buttons are at the end of the site which gets hidden under footer.

### What were you expecting?

Normal site height growth + vertical scrollbar, as in all other situations.

### What steps did you take, to get the error?

Described already + fiddles.

**Comment by Miosss** [comment]
Screenshot of the case beggining to occur when shinking the window - when shrunk more, the buttons fall down further and are invisible.

![image](https://user-images.githubusercontent.com/8083959/39326649-fc5f8596-4995-11e8-98d4-acc42a81f459.png)

**Comment by rstoenescu** [comment]
The fixed height on QStepperNavigation was the problem.
Small change included: you now need to specify a spacing class on your buttons inside QStepperNavigation.

Available in 0.15.11
