### ISSUE TITLE
Dialog.create() support html tag

### ISSUE THREAD

**Issue by johncloud200** [quasarframework/quasar#1987]
Can you please support html tag for `Dialog.create({message: '<em>quasar</em>'})`

like the older version

![untitled](https://user-images.githubusercontent.com/29952776/39349654-ea64611e-4a25-11e8-9f9e-98706b44ae11.png)

**Comment by a47ae** [comment]
It was decided to not allow HTML in any Quasar component to circumvent XSS attacks.

However, you can use the Dialog as a component as described here: http://quasar-framework.org/components/dialog.html#Basic-Usage-As-a-Component which gives you the ability to style your content the way you want it.
