### ISSUE TITLE
Pass method ( "this" -> VueJS) to the handler of a "Confirm Dialog". 

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#199]
Pass method ( "this" -> VueJS) to the handler of a "Confirm Dialog".

How can I send a local method to be executed after a successful action in the "confirm dialog"?

http://quasar-framework.org/components/dialog.html

**Comment by rstoenescu** [comment]
Please please use forum :)

**Comment by xereda** [comment]
sorry sorry!!! 👍
