### ISSUE TITLE
Infinite scroll load more delay

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#1990]
Hello,

What was the reason for infinite scroll to have 50ms delay when making the first poll?
https://github.com/quasarframework/quasar/blob/dev/src/components/infinite-scroll/QInfiniteScroll.js#L74

This makes loading state a bit harder to manage.
Here is an example:
https://jsfiddle.net/waugrryy/1731/

When the page loads:
1) Displays 'No items to display' for 50ms
2) Displays 'Loading' while making async call
3) Displays 'No items to display' after call is made

This results in unnecessary flickering. Doesn't look that nice.

Expected:
1) Displays 'Loading' right away
2) Displays 'No items to display' after call is made

Thanks!

**Comment by a47ae** [comment]
I think simply setting the `immediate` parameter to true in this line https://github.com/quasarframework/quasar/blob/dev/src/components/infinite-scroll/QInfiniteScroll.js#L74 should solve this, I also see no obvious reason why it should be debounced on the first call.

**Comment by rstoenescu** [comment]
Available in future 0.15.11

**Comment by jean-moldovan** [comment]
Thanks!

@rstoenescu Does it make sense not to debounce the first poll after resume as well?
