### ISSUE TITLE
[Request ] GoToBottom Directive

### ISSUE THREAD

**Issue by kevinmarrec** [quasarframework/quasar#1993]
Would be nice to have a built-in Quasar directive like 'BackToTop' http://quasar-framework.org/components/back-to-top.html, like implementing a 'GoToBottom' which can do the same to 'BackToTop' but going to the bottom instead of the top. And a 'AutoGoToBottom' which do it automatically when DOM is changing (item added).

So all is about creating a directive which will allows us to scroll down automatically.

I'll do it by myself, I open this issue there and will work on it soon, @rstoenescu you can assign me to this request if you are able to.

Here in the comments you can suggest some name(s) for the directive(s), or simply thumbs up if you're interested to have this directive on the go in Quasar Framework :)

**Comment by kevinmarrec** [comment]
@rstoenescu I began to work on it, and finally I think that we shouldn't really define a new directive, but instead add an option to the ScrollArea component :
http://quasar-framework.org/components/scroll-area.html
http://quasar-framework.org/quasar-play/apple/index.html#/showcase/scrolling/scroll-area

Like 
```html
<q-scroll-area ref="scroll" style="width: 400px; height: 500px;" :auto-scroll="true">
</q-scroll-area>
```

The directive would be needed only if people do a custom scrollable area or simply want to use something else than the ScrollArea component.

**Comment by kevinmarrec** [comment]
I'm just gonna code something and then we'll discuss further

**Comment by kevinmarrec** [comment]
https://github.com/kevinmarrec/quasar/commit/8b104fdc4e9466b16b1717d719877f304d75d7d6

This works really good, but I need to implement something that prevent scroll down when user has scrolled up. Like you are reading old messages in a Chat conversation, and your conversation suddenly scroll down cause you got a new message => You don't really want this behaviour, or you want to decide when this behaviour should happened or not, using your component props (ScrollArea prop in our case).

**Comment by mygnu** [comment]
@kevinmarrec any progress on this? this would be really nice in chat.

**Comment by kevinmarrec** [comment]
Hi @mygnu, was busy and I'm not really aware about what people really want. Cause in fact, maybe the behaviour of having the chat scrolling down should be done calling the public method "setScrollPosition" of the component.

**Comment by tohagan** [comment]
If you pass by here ... have a look at https://github.com/theomessin/vue-chat-scroll
