### ISSUE TITLE
[Proposal] clearable & clear-value behaviour

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#1994]
If element has `clearable` & `clear-value` property, is it possible to hide clear button when current value equals `clear-value`?
I think this useful, because shows that user select/enter not default value.

**Comment by a47ae** [comment]
Hey, I hope I understand your proposal correctly, but what you describe is very easily doable in userland. That's why I think adding another prop would only be confusing.

You can see this JSFiddle for a small demo of how you can implement this yourself.
https://jsfiddle.net/a47ae/waugrryy/1749/

**Comment by olegvakulenko** [comment]
https://jsfiddle.net/zqdjy76d/

No, there is no need to add new property.
In my example I want to hide clear icon, when current value equal to `clear-value` property.
Is my explanation enough for understand?

**Comment by olegvakulenko** [comment]
BTW, `clear-value` is not exist in documentation, my PR not confirm at this moment.

**Comment by a47ae** [comment]
@olegvakulenko Did you take a look at my JSFiddle?
Enter `test` and you notice that the clear button disappears.

Your proposal would need for a `clear-value` property on all inputs, which in my opinion is unnecessary, as you can do it in userland like shown in my JSFiddle.

**Comment by olegvakulenko** [comment]
https://github.com/quasarframework/quasar-framework.org/pull/446

**Comment by olegvakulenko** [comment]
`clear-value` property already exist in JS.

**Comment by a47ae** [comment]
Ah sorry, did not notice that :)
Sorry for misunderstanding your intentions, but now makes sense to me. :+1:

**Comment by olegvakulenko** [comment]
IMHO, `clearable` & `clear-value` very useful properties.
