### ISSUE TITLE
[Bug] v-close-overlay: "$parent is undefined"

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1995]
error:
> quasar.ios.esm.js?4ec1:18253 Uncaught TypeError: Cannot read property '$parent' of undefined
    at HTMLButtonElement.handler 

`vm` is undefined at `vm.$parent`:
```js
var closeOverlay = {
  name: 'close-overlay',
  bind: function bind (el, binding, vnode) {
    var handler = function () {
      var vm = vnode.componentInstance;
      while ((vm = vm.$parent)) {
        var name = vm.$options.name;
        if (name === 'QPopover' || name === 'QModal') {
          vm.hide();
          break
        }
      }
    };
    el.__qclose = { handler: handler };
    el.addEventListener('click', handler);
  },
  unbind: function unbind (el) {
    var ctx = el.__qclose;
    if (!ctx) { return }
    el.removeEventListener('click', ctx.handler);
    delete el.__qclose;
  }
}
```

**Comment by rstoenescu** [comment]
Please provide a jsfiddle.

**Comment by mesqueeb** [comment]
@rstoenescu 
Yes, sorry, here is the codePen:
https://codepen.io/mesqueeb/pen/ergGVe

**Comment by mesqueeb** [comment]
Just had a report from a user:
the bug is also present with pop-overs, not just modals! Should I update the codepen to add a pop-over?

**Comment by rstoenescu** [comment]
`v-close-overlay` can only work when applied directly to a Vue component. In your case, you are applying it to a DOM Element.

This is a limitation due to how Vue works under the covers. Going to document this on Quasar's website.

**Comment by mesqueeb** [comment]
isn't it something to attach on the close button?
