### ISSUE TITLE
Cannot clear number input box with backspace

### ISSUE THREAD

**Issue by cslee** [quasarframework/quasar#1996]
### Software version
Quasar: 0.15.10
Browsers: Chrome / Firefox

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/hdyn1b93/

### What did you get as the error?
Enter backspace to clear all the digits from the input box. The first digit cannot be removed from the model. The issue occurs for number type only.

**Comment by sraksh** [comment]
Is this issue resolved in Quasar 0.17? Am currently facing the same issue.
