### ISSUE TITLE
 focus mixin for input acts on 'input' refs only ( mixins/input.js)

### ISSUE THREAD

**Issue by sedatyilmazer** [quasarframework/quasar#1997]
In mixins/input.js, all actions are applied to ref 'input' instead of actual ref. look at the code below, from inputs.js mixin

  methods: {
    focus () {
      if (!this.disable) {
        this.$refs.**input**.focus()
      }
    },
    blur () {
      this.$refs.**input**.blur()
    },
    select () {
      this.$refs.**input**.select()
    }
...
..

all actions are on 
this.$refs.input object ( which can be re written as this.$refs['input'] which assumes that the object has the ref 'input' which I do not have.

if I ref my input 'myinput' and in my code do

this.$refs.myinput.focus()
this calls the mixin focus, which tries to focus on the element with the ref  'input'

Regards
Sedat

**Comment by rstoenescu** [comment]
Hello,

Mixins are for internal usage only. If you indeed want to use them, simply put the "input" ref to your element.
