### ISSUE TITLE
Tree crashing when removing last child of the leaf

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#1999]
Quasar: latest

1. Create the three with some structure where at least one node has 2 or more children.
2. In one branch with children remove children one by one. 
3. It is working fine until there are any children.
4. When you delete last one - tree crashed and keep showing last child which is already deleted.

**Comment by rstoenescu** [comment]
Hi, jsfiddle pls

**Comment by rstoenescu** [comment]
Please reopen with jsfiddle. Thanks.
