### ISSUE TITLE
Electron starter kit

### ISSUE THREAD

**Issue by Atinux** [quasarframework/quasar#2]
Hi there,

Before, I want to say that you did an amazing job with Quasar Framework 👍 

Do you plan to add the support of Electron to develop desktop applications in the future?

Thank you

**Comment by rstoenescu** [comment]
Hi,

Thanks for your kind words.

It's an excellent idea. I will put Electron support on my to-do list :+1:

**Comment by Atinux** [comment]
👏👏👏

**Comment by mlenormand** [comment]
+1

**Comment by rstoenescu** [comment]
Will make an electron starter kit soon.

**Comment by ErickPetru** [comment]
It's like the project https://github.com/SimulatedGREG/electron-vue is becoming more mature every day. Just leaving it here in case joining efforts makes sense.

**Comment by rstoenescu** [comment]
Making progress with the starter kit ;)

**Comment by rstoenescu** [comment]
Electron coming to Quasar. Finalized first beta, will write documentation and release it very soon.

**Comment by rstoenescu** [comment]
Released wrapper. Update to latest Quasar CLI and issue `$ quasar wrap electron` from your project folder. You'll get all instructions from the CLI. Documentation on the official website will follow soon, but for now the CLI instructions will suffice.
