### ISSUE TITLE
Deprecated datetime format. Invalid prop: type check failed for prop "value"

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#200]
Hi,

MomentJS is throwing this warning: http://momentjs.com/guides/#/warnings/js-date/

I don't think it is anyhow caused by app, because  am basically passing to date/time components:
`var now = moment().toString()`
and this is assigned to data which then go to `v-model`.

It has to be somehow related to datetime logic with MomentJS in quasar components.

Second issue is:
`vue.common.js?e881:2643 [Vue warn]: Invalid prop: type check failed for prop "value". Expected String, got Undefined. (found in component <quasar-datetime>)`
Can be somehow related?

**Comment by rstoenescu** [comment]
Use moment().format()
