### ISSUE TITLE
[BUG] 15.10  QTooltip stays visible on window focus loss with CloseOverlay Directive

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#2002]
Not a big bug, but something I thought you might want to fix.

Try clicking the "popWindow" button here:  https://codepen.io/anon/pen/ELmWdV

After you do, switch back and you'll see the tooltip still active,  Clicking elsewhere on the page doesn't clear the tooltip.  You have to hover over and exit the button before it clears.

Thanks for all the hard work!

**Comment by hawkeye64** [comment]
I tested this. Works as you said, except I could click anywhere on the page and the tooltip did go away.

**Comment by Lou-Der** [comment]
Yea, I don't know what changed, but the tool tip is now disappearing now.     

Which is weird since it was happening in my code and the codepen consistently last week...
