### ISSUE TITLE
[Request] Event on QKnob with current dragging value

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2004]
QKnob would benefit from having an `@drag` event with the value passed through, otherwise you get things like this:

![Drag value issue](https://i.imgur.com/vZW27Pp.gif)

Noticed how the initial value of 6 gets skipped while dragging.

Codepen: https://codepen.io/anon/pen/BxRMzG

**Comment by rstoenescu** [comment]
Available in future 0.15.11.
