### ISSUE TITLE
[Request] Slide transition events

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2008]
I want to use events similar to Vue's <transition> events on QSlideTransition element. Enter, AfterEnter, Leave, AfterLeave would be enough IMO.

I already started implementing it, let me know if I should continue and submit PR. I would basically just delegate events from inner transition element.

**Comment by panstromek** [comment]
Satisfied by 85572ac , Thx ;)

**Comment by rstoenescu** [comment]
Ah, sorry. I missed this somehow. Available in 0.15.13.
