### ISSUE TITLE
QSelect need v-html or need customization v 0.15.10

### ISSUE THREAD

**Issue by aqualaguna** [quasarframework/quasar#2011]
Iam making description into sublabel into qselect and this what i got. btw the description is from q-editor
![screenshot from 2018-05-04 15-01-10](https://user-images.githubusercontent.com/16866837/39618101-51956d2a-4fac-11e8-8e27-6c74e4ad53ac.png)
the html tag is printed digustingly please make v-html ready or customization.
the QTable is fine because there is customization.
quasar v 0.15.10

**Comment by stgunholy** [comment]
generally it is impossible to style popover of q-select. Would be nice to have possibility to add classes for it and/or to be able to specify slots for list-items

**Comment by rstoenescu** [comment]
Done for v1.0
