### ISSUE TITLE
q-spinner-mat is not working properly in rtl mode

### ISSUE THREAD

**Issue by reyhansoft** [quasarframework/quasar#2012]
### Software version

Quasar: v0.15.10
Browsers: ALL

Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/veLgds3e/

### What did you get as the error?
[dir="rtl"] .q-spinner-mat {
    animation: q-spin-rtl 2s linear infinite;
}
q-spin-rtl keyframes is not defined
### What steps did you take, to get the error?
1. Fork [Material Theme jsFiddle](https://jsfiddle.net/rstoenescu/waugrryy/) from [UMD Starter Kit - CDN install](http://quasar-framework.org/guide/embedding-quasar.html)
2. remove quasar.mat.min.css from Resources
3. add quasar.mat.rtl.min.css and i18n.he.umd.min.js to Resources and put Quasar.i18n.set(Quasar.i18n.he) at top of Javascript section [this example](http://quasar-framework.org/components/rtl-support.html#Handling-Quasar-UMD)
4. run

**Comment by rstoenescu** [comment]
Fix available in future 0.15.11
