### ISSUE TITLE
unintentional yarn global add quasar results unexpected

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#2013]
```bash
$ yarn global add quasar
yarn global v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
warning "quasar@0.0.18" has no binaries
✨  Done in 5.77s.
```

Perhaps a minor bump might be in order...

**Comment by rstoenescu** [comment]
"quasar" package is not affiliated with Quasar Framework.
I think you meant "quasar-cli"

**Comment by nothingismagick** [comment]
I know what I meant. :) It was merely an accident. But perhaps it would make sense to start think about a mono-repo, like how vue et. al. do things. like `@quasar/app-base` for example.
