### ISSUE TITLE
Missing offset-0 and col-0 classes

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2018]
In some cases, like if I set `.offset-xs-2`, but I want to stop propagating that offset on larger screens (which happens automatically, if you don't set different offset for sm, md, lg or xl), I would set `.offset-sm-0` on the same element. Currently I don't see a way how to do that without binding to screen size which kinda kills the point of flex css.

**Comment by pdanpdan** [comment]
For offset-??-0 it's clear, but what would col-0 do?

**Comment by panstromek** [comment]
Just a consistency with offset-0 I guess.. I didn't really think about this TBH, I have no use in mind now. But you added it anyway, thanks ;)
