### ISSUE TITLE
QEditor has no error option

### ISSUE THREAD

**Issue by DeroSavage** [quasarframework/quasar#2021]
Hey, im working with QEditor for a textarea field and i saw that there is no error option at all. I tried to connect it with Qfield but thats not working. 

Maybe there is already a workaround for that, if not this is a feature request :D

**Comment by rossity** [comment]
QField around QEditor works for me, can you provide some code?

**Comment by DeroSavage** [comment]
@rossity nevermind it works now. I needed to add @input="$v.text.$touch". After that qfield shows the error.
