### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by nuykon** [quasarframework/quasar#2024]
I installed quasar just now.
$ quasar init test
$ cd test
$ quasar dev
Open http://localhost:8080 - good, show main page
Open http://localhost:8080/asdfg - bad, don't show 404, redirect to main page

**Comment by rstoenescu** [comment]
Hi,

1. Why does it matter what dev does? I mean, of what importance would this be? The dev server is not the production server.
2. This should have gone to quasar-cli repo.
