### ISSUE TITLE
Use new material design guidelines

### ISSUE THREAD

**Issue by nklayman** [quasarframework/quasar#2028]
Google recently updated their material design guidelines at Google I/O. You can see the new guidelines at [material.io](https://material.io). They focus heavily on customizability and theming, while making base changes from the original versions. It would be nice to see quasar's material theme be updated to match these new guidelines and theming.

**Comment by rstoenescu** [comment]
The new material design is a living creature which gets frequent updates. Quasar will follow them as close as possible.
If you are referring the customisability and theming, well, we're dealing with web code, so yes you can already customise it! Stylus variables included, if necessary.
