### ISSUE TITLE
Buttons, inline label with icon and progress bug

### ISSUE THREAD

**Issue by onurkose** [quasarframework/quasar#2029]
Quasar: quasar-framework@0.15.10
OS: mac os
Node: 9.11.1
NPM: 6.0.0
Browsers: Firefox Dev
iOS:-
Android:-
Any other software related to your bug:-

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/6czjq129/6/

### What did you get as the error?
I believe it's just a documentation typo.

The Basic Usage section [explains](http://quasar-framework.org/components/button.html#Basic-Usage) the loading state of QBtn. Then the Button with Progress [section](http://quasar-framework.org/components/button.html#Button-with-Progress) makes it little bit confusing because lack of information about label attr. usage and it's relation to icon attr.

If you check the jsfiddle, you'll see three buttons with label usage differs from each. When label attr. used with icon, no problem. But if I use with inline label with icon attr. "on-left" class name dissapears.

### What were you expecting?
Since the documentation gives the example of usage of Loading state, I think the QBtn.js has no bug. Documentation may need to be updated about the usage with icon, and relations to rectangle button and label tag. Or QBtn.js might import inline label string to it's this.label option.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this. Fixed docs. Will be available on next doc update scheduled soon.
Correct usage:

```html
<q-btn :loading="loading" @click="simulateProgress" label="Button Label">
    <!--
      Notice slot="loading". This is optional.
      If missing, the default theme spinner will be used.
    -->
    <span slot="loading">Loading...</span>
  </q-btn>
```
