### ISSUE TITLE
[Request] limit number of items in QSelect with filter property

### ISSUE THREAD

**Issue by hurrycaner** [quasarframework/quasar#2030]
I'm using a QSelect to show a list of cities and users can pick multiple cities...
My list can get over 200 items easily... and when a QSelect has lots of items, it gets very laggy!!
Is it possible to create a new property limiting the number of items shown if 'filter' property is set?

For example:
When i click on QSelect, it would show the first 10 items and maybe a count showing (10/212...), and when i write something in the filter... it shows (10/14...)

**Comment by hurrycaner** [comment]
I would like to know if is any workaround to this...

**Comment by pdanpdan** [comment]
For the moment just QAutocomplete, or a QSelect with variable options list

**Comment by rstoenescu** [comment]
All solved in v1.
