### ISSUE TITLE
QTab's count and alert attributes look bad when QTabs's align is set to justify

### ISSUE THREAD

**Issue by johnyluyte** [quasarframework/quasar#2032]
### Software version
Quasar: 0.15
OS: Windows 10
Browsers: Chrome, Firefox, Edge, IE

### JsFiddle (for Quasar v0.15+ only)
https://codepen.io/ChunNorris/pen/PeevMo

### What were you expecting?
The `count` and `alert` icons are aligned to the top-right corner of `q-tab`.
But they look weird when q-tabs is set to `align="justify"`. 
To make it look normal, `count` and `alert` should align to the top-right corner of "label" or "icon". 

### Current behavior
![qtab1](https://user-images.githubusercontent.com/4846501/39957475-2c260416-5626-11e8-8f84-c3ebb63b355a.png)

### Expected behavior
![qtab2](https://user-images.githubusercontent.com/4846501/39957480-3e1f0fe6-5626-11e8-9061-21c29a13766b.png)

**Comment by rstoenescu** [comment]
Fix available in future Quasar v0.16.1
