### ISSUE TITLE
how to make buttons custom size and stay consistent

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2033]
When reading the docs it seemed to me that making a button change size (with all its aspects, e.g.: icons-size, ripple-size, etc.) would be as simple as changing the size attribute. However this does not work. I managed the get the desired behavior by making a custom component [as documented here](https://stackoverflow.com/questions/50171579/icon-in-quasar-button-component-does-not-change-size/50308457#50308457). Is this indeed how it 'needs to be done'?

**Comment by BenoitRanque** [comment]
What do you mean "does not work" ? Also if your problem is the icon/button size aspect ratio, use the `dense` prop, or set the padding on the button yourself

**Comment by musicformellons** [comment]
Expected behavior: when you set the size attribute of the button it shows all aspects (button, icon, padding,  ripple) in that size or relative to that size.
Actual behavior: when you set the size attribute of the button to a large size, the icon stays the same (i.e. small). So you need to fiddle with CSS to get it right.

**Comment by BenoitRanque** [comment]
I'm not sure what you mean by "it stays the same"
https://jsfiddle.net/fh7rjkrd/

**Comment by musicformellons** [comment]
You have 'the expected behavior' as well when you use webpack-babel compiled version (not UMD)? My setup is:
- webpack-babel etc.
- mdi icons (but I think I had same behavior using default material icons).

Everything works fine except the behavior as brought forward above.

**Comment by rstoenescu** [comment]
A simple example of some predefined sizes below. It's definitely something in your CSS messing things up.

![btn](https://user-images.githubusercontent.com/4665641/41096923-ddf3d92e-6a5e-11e8-89ec-c4f4ece6b53f.png)
