### ISSUE TITLE
[Bug] Button/ButtonDropdown stays stays on hover color after click

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2035]
After click and ripple, Button and ButtonDropdown (maybe some other similar components, too) changes color back to :hover color instead of base color and stays with it until I click somewhere else.

I noticed it first after updating to quasar 0.15.10 from 0.14 and now I forked dev branch and it's not working there, too. 

I am on Windows 10, Chrome or Firefox. 

Somehow it works on my co-worker's Mac Book on Firefox , if I noticed correctly, but I can't check now.

EDIT: I just checked and it is not working in official documentation, too

**Comment by rstoenescu** [comment]
Hi,

It's not a bug. It's accesibility in action. User must have a way to tell which element is focused. This does not apply to mobile, where user can't use TAB/Shift+TAB.

**Comment by panstromek** [comment]
Ah, ok. Sorry, then. Thanks for the info.

**Comment by dmklsv** [comment]
it does not look like standard behavior for the web, how do I disable this feature?

**Comment by rstoenescu** [comment]
@dmklsv maybe you didn't notice it. but even native browser `<button>` DOM elements have it. Not designing with accessibility in mind is not the way to go anymore. Even [Lighthouse](https://developers.google.com/web/tools/lighthouse/) PWA tool has accessibility tests by default, even though the PWA concept doesn't intersects with accessibility necessarily.
