### ISSUE TITLE
[request] Add "key" property to QSelect options prop

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#2040]
Currently QSelect uses Array.includes to determine if an option value should be inlcuded in the component model
https://github.com/quasarframework/quasar/blob/dev/src/components/select/QSelect.vue#L263

This works fine for most primitive values. However when the value is an object, we can run into issues:

```html
 <q-select multiple v-model="model" :options="options"></q-select>
```

```js
  data: function () {
    return {
    	model: [ { name: 'item_1' }  ],
        options: [
      	{ label: 'Item 1', value: { name: 'item_1' } },
	{ label: 'Item 2', value: { name: 'item_2' } },
      	{ label: 'Item 3', value: { name: 'item_3' } }
      ]
    }
  }
```
https://jsfiddle.net/qwLa07dz/43/

This is because while the value objects are equivalent, they are _not the same object_
We can solve it like so:

```js
  var opt1 =  { name: 'item_1' }

  data: function () {
    return {
    	model: [ opt1 ],
        options: [
      	{ label: 'Item 1', value: opt1 },
	{ label: 'Item 2', value: { name: 'item_2' } },
      	{ label: 'Item 3', value: { name: 'item_3' } }
      ]
    }
  }
```
https://jsfiddle.net/qwLa07dz/44/

However there are times this is not practical.

I propose adding a `key` prop which if present would be used as a unique identifier. The proposed api looks like this:
```html
 <q-select multiple v-model="model" :options="options" :key="key"></q-select>
```
```js
  data: function () {
    return {
    	model: [ { name: 'item_1' }  ],
        key: 'name'
        // alternative
        key: item => item.name
        options: [
      	{ label: 'Item 1', value: { name: 'item_1' } },
	{ label: 'Item 2', value: { name: 'item_2' } },
      	{ label: 'Item 3', value: { name: 'item_3' } }
      ]
    }
  }
```

We still perform the same checks as before, but if the check fails and the key prop is present, we also check for the key

Toughts and comments?

**Comment by BenoitRanque** [comment]
TBH I'm quite unsure if this is even a good idea

**Comment by pdanpdan** [comment]
There's no way we could use `key` :) (it's handled by vue)

**Comment by BenoitRanque** [comment]
Duh! Option-key?
