### ISSUE TITLE
ask: q-pagination set :max attribute

### ISSUE THREAD

**Issue by johncloud200** [quasarframework/quasar#2041]
quasar-framework : 0.15.10

```
<q-pagination input
                    v-model="pagination.current_page"
                    :max="pagination.last_page"
                    @input="getDataFromApi()" />
```

```
created () {
   let response = this.getDataFromApi()
   this.pagination.last_page = response.last_page
}
```

I got doubled hit getDataFromApi(), because when I set **this.pagination.last_page = response.last_page** that will hit @input event

any trick, how I can set **:max** from Api without hit @input?

**Comment by rstoenescu** [comment]
Hi,

Please use Discord or forum for questions. Github is reserved exclusively for bugs and feature requests. Thank you.

**Comment by johncloud200** [comment]
Oops sorry @rstoenescu ,

bytheway this is bug or not?
@input fired when I do **this.pagination.last_page = response.last_page**

Thanks.

**Comment by jadeOnProg** [comment]
same issue I encountered do you have any solution for this?
