### ISSUE TITLE
Electron issue thisCompilation of undefined

### ISSUE THREAD

**Issue by Zyles** [quasarframework/quasar#2046]
I am not getting the electron stuff to work.

````$ quasar dev -m electron -t mat````

```Error: TypeError: Cannot read property 'thisCompilation' of undefined```

Quasar-cli: 0.15.14
npm: 6.0.1
node: v10.1.0
webpack: 4.8.3

**Comment by Zyles** [comment]
Nevermind I just did a fresh project install and now it works. Not sure what was wrong.

**Comment by rstoenescu** [comment]
Do not manually install webpack.
