### ISSUE TITLE
Deploy Heroku

### ISSUE THREAD

**Issue by Felipecs26** [quasarframework/quasar#2050]
### Software version

Quasar: 0.15.15
Node: 8.9.0
NPM: 5.6.0

I have a problem in deploy, all time i try deploy in heroku and i get this error

![image](https://user-images.githubusercontent.com/25541664/40181118-bbfe2280-59be-11e8-8f81-6ed15f4d71db.png)

**Comment by rstoenescu** [comment]
https://quasar-framework.org/guide/app-deploying-spa.html#Deploying-with-Heroku

**Comment by Felipecs26** [comment]
i followed these steps but it did not work.

**Comment by rstoenescu** [comment]
Maybe something changed in Heroku since the help doc was written. Have you read about Heroku deployment on their website too? I'd love a PR on docs with some updated info if it's possible.

**Comment by rstoenescu** [comment]
Btw, what port are you serving your app on? The demo script in the docs say 5000, but you are trying to access port 80.

**Comment by Felipecs26** [comment]
Thank you, problem solved. In gitignore was the folde dist
