### ISSUE TITLE
[request] q-route-tab amendment

### ISSUE THREAD

**Issue by joshuagamboa** [quasarframework/quasar#2052]
The documentation says that we cannot use a model for q-route-tab. So the only way the tab gets selected/highlighted is when user clicks/taps on it or when we use router.push({path: 'toexactroute'}). However, I am also passing 'query' into the route and somehow q-route-tab does not recognise this and fails to select the proper route.

To illustrate:
router.push({path: 'search'}) selects the tab with to="/search".
router.push({path: 'search', query: {some params here}}) does not select the tab for 'search'
(eg. http://localhost/search?param1=val1&param2=val2&param3=val3)

Is it possible we can add this feature or is there a better approach than what I am doing? Thanks!

**Comment by rstoenescu** [comment]
The "to", "exact", ..., are borrowed from `<router-link>` Vue component supplied by Vue Router. As a result, you can use something like:

```<q-route-tab :to="{ path: 'register', query: { plan: 'private' }}" ....>```
