### ISSUE TITLE
[Proposal] Rename .col to .fr

### ISSUE THREAD

**Issue by tegola** [quasarframework/quasar#2053]
I'm having a hard time trying to remember flexbox classes. The major issue is that the `col` class is ambiguous and easily mistaken with the `column` class. Furthermore, `col` is also used vertically, breaking the semantic term.

My proposal is lend the term from grid layout and rename `col` to `fr`, and keep the size variations, like `fr-1`, `fr-2`, and so on.

### Examples

3 columns with equal width:
```html
<div class="row">
  <div class="fr">Column 1</div>
  <div class="fr">Column 2</div>
  <div class="fr">Column 3</div>
</div>
```

2 rows, one of which extends to fill all empty space:
```html
<div class="column" style="height: 100vh">
  <div class="fr-2">Column 1</div>
  <div class="fr">Column 2</div>
</div>
```

**Comment by rstoenescu** [comment]
Hi,

1. The flexbox CSS classes names were chosen to mimick Bootstrap's ones. It makes it easy for people coming from it (a LOT).
2. "fr" might get some into the idea that flexbox are actually connected to grid CSS, which would be wrong.
3. Changing flexbox CSS classes would be a huge breaking change, one which we definitely want to avoid. It would make upgrades be a real pain for our developers.

Sorry for any inconveniences, but try to adapt to the "col".

**Comment by tegola** [comment]
No worries, it was just a proposal.
