### ISSUE TITLE
DataTable filter broken when using serverside pagination

### ISSUE THREAD

**Issue by dmig** [quasarframework/quasar#2056]
### Software version

Quasar: 0.15.15

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/yec2a9kL/39/

### What did you get as the error?
Changing `filter` field doesn't trigger `request` method because row count is less than 1 page

### What were you expecting?
Changing `filter` field triggers `request` method and loads data from server

### What steps did you take, to get the error?
1. open fiddle
2. open console
3. change filter field

**Comment by rstoenescu** [comment]
Invalid. Supply the "filter" prop to QTable, otherwise how should it know filter changed?

https://jsfiddle.net/ucucykLt/1/
