### ISSUE TITLE
QDataTable - Single selection with problems

### ISSUE THREAD

**Issue by ianclever** [quasarframework/quasar#2057]
In single selection mode, datatable is checking all rows, although it effectively selects only one object.

https://drive.google.com/file/d/1X8k6SCyujpEZKuTjOhcblTmeA6zl1bbo/view?usp=sharing

**Comment by rstoenescu** [comment]
Hi,

1. Please do not discard the github issue template.
2. Have you correctly used "row-key" prop? It should specify a property of each row that is unique.

**Comment by ianclever** [comment]
Really, it fails me.
I had not noticed that.
Thank you.
