### ISSUE TITLE
[Request] QBtn router handling ("to" and "replace" props)

### ISSUE THREAD

**Issue by joerg-walter-de** [quasarframework/quasar#2058]
QBtn (as well as other button-like components) should support the same router properties as QItem: to, exact, ...

Both are clickable. Both are natural tools for creating links

**Comment by rstoenescu** [comment]
Available in future 0.16.0 in a few days.
Only "to" and "replace" props, since the other ones don't make sense as QBtn doesn't have a state to hook into.
