### ISSUE TITLE
Unknow system Error 120

### ISSUE THREAD

**Issue by Arstman** [quasarframework/quasar#2060]
### Software version

Quasar: latest
OS: centos 6.5
Node: 8.11.2 (NVM)
NPM: 6.0.1 
Yarn: 1.6.0
Browsers:
iOS:
Android:
Any other software related to your bug:

**it always report error after run"npm install" such as below:**

> npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/EvalDevToolModuleTemplatePlugin.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/neo-async-a963ae6e/priorityQueue.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/EvalSourceMapDevToolModuleTemplatePlugin.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/ajv-95ac8447/lib/refs/data.json'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/neo-async-a963ae6e/queue.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/EvalSourceMapDevToolPlugin.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/ajv-95ac8447/lib/refs/json-schema-draft-04.json'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/buffer-e115aebd/test/node/test-buffer-indexof.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/neo-async-a963ae6e/race.js'
npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/concat-map/example'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/ExportPropertyMainTemplatePlugin.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/ajv-95ac8447/lib/refs/json-schema-draft-06.json'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/neo-async-a963ae6e/README.md'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/ExtendedAPIPlugin.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/ajv-95ac8447/lib/refs/json-schema-draft-07.json'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/concat-map/index.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/ExternalModule.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/concat-map/LICENSE'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/ExternalModuleFactoryPlugin.js'
npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/ajv-95ac8447/scripts'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/concat-map/package.json'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/webpack-20898b21/lib/ExternalsPlugin.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/concat-map/README.markdown'

npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/console-control-strings'
npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/console-control-strings'
npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/core-util-is'
npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/core-util-is'
npm WARN tar ENOENT: no such file or directory, lstat '/home/cabox/workspace/quasar2nd/node_modules/.staging/fsevents-16f35734/node_modules/core-util-is'

**if run "yarn install", then reports:**

> yarn install
> yarn install v1.6.0
> info No lockfile found.
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/quasar-framework/-/quasar-framework-0.15.15.tgz: Unknown system error -122: Unknown system error -122, open '/home/cabox/.cache/yarn/v1/npm-quasar-framework-0.15.15-96942ed29512aeb8592b3258e354c22afa785458/dist/core.variables.styl'".
> 

I have tried every solution like clean cache, update npm even change to node v10, none of them works.

please kindly help.

thanks
B.regards Aaron

**Comment by rstoenescu** [comment]
Hi,

Have you googled in for "Unknown system error -122"? After a quick search I've ended on https://github.com/npm/npm/issues/16604. Seems like you have exceeded your disk quota.

**Comment by Arstman** [comment]
hi, @rstoenescu ,
yes it works.

thanks.

B.regards Aaron

**Comment by x-yuri** [comment]
```
$ find / -xdev -printf '%h\n' | sort | uniq -c | sort -nk1
```

https://unix.stackexchange.com/a/117094/29867

**Comment by nothingismagick** [comment]
This is one of the most abstract issues I have EVER seen. I assume your
linux system is complaining that you don't have enough inodes, but if you
seriously want us to help you with this (and I doubt it is a quasar issue
per sé) then you absolutely MUST give us more information about your OS and
what is happening so that you get some weird system error 120... (which is
definitely not from Quasar).

>
