### ISSUE TITLE
Webworkers broken upstream @ https://github.com/webpack/webpack/issues/6642

### ISSUE THREAD

**Issue by disarticulate** [quasarframework/quasar#2062]
See: https://github.com/webpack/webpack/issues/6642
affects quasar v 0.16.0
 - Webworkers won't be available to HMR.
 - Global object unavailable to webworkers (worker-loader) unless webpack output config is set:

https://github.com/quasarframework/quasar-cli/pull/123

**Comment by rstoenescu** [comment]
Quasar allows devs to extend the default Webpack config (required for webworkers):

```js
// quasar.conf.js

build: {
  extendWebpack (cfg) {
    cfg.output.globalObject = 'this'
  }
}
```

**Comment by rstoenescu** [comment]
Would you be so kind to provide a PR on docs to specify this case though?

**Comment by disarticulate** [comment]
https://github.com/quasarframework/quasar-framework.org/pull/470/commits

**Comment by disarticulate** [comment]
Reopened, not sure why it was cloed:
https://github.com/quasarframework/quasar-framework.org/pull/470/
