### ISSUE TITLE
Missing weights on roboto-font in v0.16

### ISSUE THREAD

**Issue by AndreAce1** [quasarframework/quasar#2064]
After updating v0.16 (which actualized the robot-font), it looks like a shadow was placed on top of each letter and it got very strange.
But the problem is, i can no longer use the 5 variations as stated in the documents ('Roboto comes with 5 different font weights you can use: 100, 300, 400, 500, 700'), only the normal size and bold are working.

**Comment by rstoenescu** [comment]
Working on this.

**Comment by rstoenescu** [comment]
Fixed. Update to Quasar CLI v0.16.1.
