### ISSUE TITLE
Font Awesome Icon not Loaded Properly

### ISSUE THREAD

**Issue by aqualaguna** [quasarframework/quasar#2066]
i'm using fontawesome icon in my project.
also i already added it to quasar.conf.js
when using q-icon component
the icon become
![screenshot from 2018-05-21 23-36-44](https://user-images.githubusercontent.com/16866837/40318768-ea140ccc-5d4f-11e8-8eda-dd0c000b3418.png)
the trash icon is material icon.
please fix it!
quasar v 0.16
this is the piece code
```
  <q-btn
            class="primary"
            @click='view(cell.props.row)'
            color="grey"
            width="10px"
            key="add">
            <q-icon
              name="fab fa-eye"
              size="15pt"/>
            <q-tooltip>
              {{ 'detail' | locale-text }}
            </q-tooltip>
          </q-btn>
          <q-btn
            class="primary"
            @click='deleteRow(cell.props.row)'
            color="red-11"
            width="10px"
            key="edit">
            <q-icon
              name="delete"
              size="15pt"/>
            <q-tooltip>
              {{ 'delete' | locale-text }}
            </q-tooltip>
          </q-btn>
```

**Comment by rstoenescu** [comment]
Offer more details. Please copy-paste your QIcon tag. Also your quasar.conf.js. Thanks.

**Comment by rogeriomq** [comment]
define a "fa" before fa-ICON aquala...
Sample:
`
 <q-icon
              name="fab **fa** fa-eye"
              size="15pt"/>

`

**Comment by rstoenescu** [comment]
There's no "fab fa-eye". I see only "fas fa-eye", "far fa-eye", and fontawesome-pro: "fal fa-eye".

**Comment by jean-moldovan** [comment]
Font awesome icons have stopped working after upgrading to Quasar v16
https://jsfiddle.net/waugrryy/2697/

**Comment by rstoenescu** [comment]
@jean-moldovan https://jsfiddle.net/34g6jnza/1/
Of course they stop working if:
1. they're not included (as a CDN style tag or through quasar.conf.js > extras: [...., 'fontawesome'])
2. non-existent icon is used "fa-edit" (this is a pre Fontawesome v5 icon)
:)

**Comment by jean-moldovan** [comment]
Was there a breaking change actually?

**Comment by jean-moldovan** [comment]
I can confirm that fontawesome is included in quasar.conf

**Comment by rstoenescu** [comment]
From v0.15 to v0.16: nope. Just updated from Fontawesome 5.0.4 to latest 5.0.13.
Just read https://quasar-framework.org/components/icons.html
There's even a cheatsheet section there to help you out.

**Comment by jean-moldovan** [comment]
Okay, thanks. Moving the discussion over to Discord.
