### ISSUE TITLE
6000

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#2068]
![screen shot 2018-05-22 at 04 01 16](https://user-images.githubusercontent.com/35242872/40338464-69192fb4-5d75-11e8-9dcc-ae2327a8b08e.png)

**Comment by trongdong** [comment]
Thanks for such a great framework!  @rstoenescu   
With the coding quality, performance and application architecture, I do think that quasarframework deserve to gain more popularity.  
Let's aim for another milestone and take quasar to a next level <3
