### ISSUE TITLE
Timepicker - one more version

### ISSUE THREAD

**Issue by EmilMoe** [quasarframework/quasar#207]
I would love the timepicker look more like this rather than the clock thing

http://element.eleme.io/#/en-US/component/time-picker

**Comment by IniZio** [comment]
I think the current one fits more for mobile interface though?

**Comment by EmilMoe** [comment]
You might be right about that, but I don't think it's perfect for the desktop at least.

**Comment by rstoenescu** [comment]
Will have this in mind. Although there's a lot to talk about. Are we following material design or not? I agree a simpler datetime would be useful. Got to ponder on this well. Maybe a new component with simpler datetime.

**Comment by murbanowicz** [comment]
Also we are still missing 24hr format support. 
AM/PM is not understand by people in many countries using 24hr time.

**Comment by AlexanderKoehn** [comment]
Is the 24 h format an active issue? If not, I would work on that.

**Comment by smolinari** [comment]
I'd say it is covered in v0.14. 

![image](https://cloud.githubusercontent.com/assets/3314957/26438453/6c783156-4123-11e7-8be6-f0dd2cc36dc0.png)

😄 

Scott

**Comment by AlexanderKoehn** [comment]
Where can I see this? Cant find a 0.14 branch. And the Screenshot does not look material design conform. After selecting the hour one can select the minute within an inner circle. 
Thanks,
Alex

**Comment by AlexanderKoehn** [comment]
I have to correct myself. The 24 hours are split across 2 circles. After selecting the hour, the circles are replaced by a minutes circle.

**Comment by smolinari** [comment]
Right. Quasar's 24h version is only one circle of numbers. 

Scott

**Comment by zinwalin** [comment]
> Will have this in mind. Although there's a lot to talk about. Are we following material design or not? I agree a simpler datetime would be useful. Got to ponder on this well. Maybe a new component with simpler datetime.

We can use https://amsul.ca/pickadate.js/time/ as a reference. it's brilliant.

**Comment by smolinari** [comment]
Beauty is in the eye of the beholder. 😉 

Scott

**Comment by hawkeye64** [comment]
Sounds like a candidate for an App Extension.

**Comment by rstoenescu** [comment]
Available in 1.0 through https://github.com/quasarframework/app-extension-qscroller (more details/demo/etc to come).
