### ISSUE TITLE
[Bug] QSelect throws an error when container block disappears

### ISSUE THREAD

**Issue by VitalyEmelyanov** [quasarframework/quasar#2071]
### Software version

Quasar: Latest (0.16 and below)
Browsers: Chrome v63

### What steps did you take, to get the error?

1. Click on select component
2. When the items list popover is displayed, click on button to hide the container block

### What did you get as the error?

Component throws `Cannot read property 'hide' of undefined` into console

### What were you expecting?

Popover of QSelect component should be correctly disposed

![may-23-2018 11-42-52](https://user-images.githubusercontent.com/15330670/40413452-85a60df0-5e7e-11e8-857c-c183454e6fc6.gif)

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in v0.16.1.

**Comment by Hamdan85** [comment]
I think it's happening again with q-modal
