### ISSUE TITLE
QSelect with objects value

### ISSUE THREAD

**Issue by brunofmeurer** [quasarframework/quasar#2073]
### Software version
Quasar: Latest (0.16 and below)
Browsers: Chrome v63
Android: android 6.0 and below, etc.

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/ktu0u11L/

### What did you get as the error?
Don't loaded the starter value of component q-select

### What were you expecting?
I need use value with objects, but dinamic load value dont work.

### What steps did you take, to get the error?
1. view load the page, the select dont have a initial value
2. if selected a option, work fine.

**Comment by rstoenescu** [comment]
Hi,

Objects are stored by reference in Javascript. If you write:
```js
const one = { a: true }
const two = { a: true }
// then one === two is FALSE, because each Object has a different reference in memory
```

So use this JS knowledge. Rework of your jsFiddle: https://jsfiddle.net/xwgoj67n/1/
