### ISSUE TITLE
[Request] Numpad

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2078]
Similar to [vue numkeyboard](https://github.com/brucejcw/vue-numkeyboard) but I'd like a few more options which buttons next to 0 and if extra button row left, right or top.
Also round / square buttons would be nice.

**Comment by rstoenescu** [comment]
Hi,

Sorry but this is out of the scope of Quasar. You can however use the vue plugin that you indicated and suggest some improvements on their github page.

**Comment by mesqueeb** [comment]
Ok! If I ever get around to creating a sharable one I'll present the code as a suggestion to add!
