### ISSUE TITLE
Bug: q-layout-drawer > q-input: Invalid prop

### ISSUE THREAD

**Issue by matrixOnline** [quasarframework/quasar#2079]
Got following Error by coding this:

> Invalid prop: type check failed for prop "value". Expected Boolean, got InputEvent.

`<q-layout-drawer side="left" v-model="layout.left">
      <q-input v-model="inputModel" />
    </q-layout-drawer>`

quasar-cli                    0.16.1

**Comment by rstoenescu** [comment]
Hi, Like the vue erro says, in your vue scope, `layout.left` is not a Boolean. If you would have provided a jsFiddle (like the github issue template requires) I would have gladly forked it to offer you the correct version for your code.

**Comment by matrixOnline** [comment]
@rstoenescu  thanks for your quick reply

I set the model as a boolean, but when i put some text in the input-field, the v-model from q-layout-drawer changes to an object: { "isTrusted": true }

**Comment by rstoenescu** [comment]
jsFiddle please. There is 100% an error in your code.

**Comment by matrixOnline** [comment]
Before the update, i had no error ...

Okay: [https://jsfiddle.net/dav3online/wuzbuLd3/](url)

You can see the result, by typing "test": 

![image](https://user-images.githubusercontent.com/29035126/40577818-7576509a-610b-11e8-9e72-39929a477756.png)

**Comment by rstoenescu** [comment]
I cannot reproduce on either Chrome, FF, Safari or Opera. What browser are you using?
If this is indeed a bug, it's 1000% not related to Quasar, but to Vue most likely.

**Comment by matrixOnline** [comment]
thats strange... 
i used vivaldi - but now testet on edge, simular error (got an empty object)

![image](https://user-images.githubusercontent.com/29035126/40578076-fa5ec02e-610d-11e8-8b9d-cddc5a1fcdda.png)

**Comment by rstoenescu** [comment]
I just installed and tested on Vivaldi. Doesn't reproduce there either :|

**Comment by rstoenescu** [comment]
Worked on Edge too.

Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

But the thing is that this doesn't makes sense. There's 0% chance of one component affecting some other variable in the vue scope of the same component, unless you're supplying it with that variable, which is not the case here.

**Comment by matrixOnline** [comment]
I did some tests with my second PC - and there are no errors.
You're right, it does not make sense ... maybe it's because my laptop is touch-enabled?

Nevertheless, many thanks for your help. I'm sorry if I wasted your time.

Incidentally, I'm a big fan of Vue and Quasar ;-)

**Comment by rstoenescu** [comment]
Tested on a touch-enabled laptop for the sake of it, but couldn't reproduce either.
Quasar is one of the very few frameworks developed with laptop/desktop with touch screen in mind too :)
