### ISSUE TITLE
Action Sheet Dismiss

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#208]
Action Sheet Dismiss

The event considered by the "dismiss" is executed only when the cancel button is executed. Eventually, we need to know if the user aborted the choice of an action within the Action Sheet, but today we have no way of knowing that.

What do you suggest to get around this !? Is there anything foreseen for the next releases? For example, implement a new handler, something like "abortAction".

Look at the image below. It illustrates what the current behavior.

Thanks in advance for an answer.

![actionsheet](https://cloud.githubusercontent.com/assets/14337850/20428241/1fc4a5a8-ad6f-11e6-8b50-9435ee4af9d6.gif)

**Comment by murbanowicz** [comment]
Use forum. This is not an issue, this is a question.

2016-11-18 11:12 GMT+00:00 Jackson Ricardo Schroeder <
notifications@github.com>:

**Comment by xereda** [comment]
Yeah, this is a issue! This is a proposal.

**Comment by rstoenescu** [comment]
Agreed. This needs to be implemented.
