### ISSUE TITLE
[Bug]Mini layout drawer animate like normal mode when it hide automatically

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#2080]
### Software version

Quasar: v0.16.0
Browser: Chrome 66.0.3359.181

### What did you get as the error?
 When the drawer is set to mini mode and hide automatically by resizing the browser window, it closed with animating like normal mode.

### Screenshot
![image](https://i.loli.net/2018/05/26/5b097bec40d44.gif)

### What were you expecting?
Mini drawer closed animation acts normal

**Comment by rstoenescu** [comment]
Fixed in future Quasar v0.16.1
