### ISSUE TITLE
v-scroll-fire get fired when reload the page

### ISSUE THREAD

**Issue by raxor123** [quasarframework/quasar#2081]
I was adding some functionality to my site with your v-scroll-fire and I realized that when you are below the tag that have v-scroll-fire assigned and reload the page, that function get fired even if the tag isn't in the view port

I cannot use any tool like jsfiddle to reproduce the bug because need to be test it directly in the browser

To reproduce the issue you can simply add this code to the App.vue file in a new quasar project 

```
<template>
  <div id="q-app">
    <div class="first">

    </div>
    <div v-scroll-fire="executeFunction">
      This container should fire the "v-scroll-fire"
    </div>
    <div class="first">

    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  methods: {
    executeFunction () {
      alert('Fired')
    }
  }
}
</script>

<style lang="stylus">
.first
  height 1500px
  background: aliceblue
</style>
 ```

### Explanation

This execute the function that trigger a javascript alert when the second div is in the view port

### Software version

Quasar: 0.16.1
OS: Ubuntu 16.04
Node: 10.2.1
Yarn: 1.6.0
Browsers: Chrome 66 and Firefox

### What were you expecting?

I was expecting to only fire when the element gets in the viewport

### What steps did you take, to get the error?

Reload the page below the second div trigger the v-scroll-fire function

![test2](https://user-images.githubusercontent.com/25715337/40582900-64a97842-6150-11e8-8803-457724b47242.gif)

**Comment by rstoenescu** [comment]
Fixed in future 0.16.1. Thanks for reporting.
