### ISSUE TITLE
[Bug] QTabs no bottom border/line

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2083]
QTabs doesn't have the line underneath the tabs in latest version.

<img width="660" alt="2018-05-28 14 58 47" src="https://user-images.githubusercontent.com/3253920/40599338-a474784a-6287-11e8-866d-7c2300481c44.png">

CodePen: https://codepen.io/mesqueeb/pen/XqGMMd

**Comment by rstoenescu** [comment]
That's the iOS theme, which has no underline... Only Material has it.

**Comment by mesqueeb** [comment]
@rstoenescu 
Thank you for your elaboration.

In my opinion I'd be very grateful if Quasar Framework would offer the ability to choose iOS/Material theme on a component base.

- For one app our team needs to have the underline of Material but iOS based design for all other components.
- For another app I personally need the time picker of Material but iOS based design for all other components.

Is there any way I could manually do this?

**Comment by venkyvb** [comment]
@mesqueeb Dont know if this is still relevant for you.
 You could just use a local style to handle this scenario. E.g. if you want to have the underline for the Tab you could just create CSS style (e.g.):
```
.tab-label-active {
  font-weight: bold;
  font-size: 1.5rem;
  border: 2px solid currentColor;
  border-bottom-width: 2px;
  border-top-width: 0px;
  border-right-width: 0px;
  border-left-width: 0px;
}

.tab-label-inactive {
  font-size: 1.5rem;
}
```
and use the same in your tab definition:
```
      <q-route-tab
        label="Test"
        class="tab-label-active"
        :to="{name: 'test'}"
        exact
        slot="title"
      />
```

**Comment by mesqueeb** [comment]
@venkyvb 
Thank you very much!
