### ISSUE TITLE
Load env var from process

### ISSUE THREAD

**Issue by devRoshan** [quasarframework/quasar#2086]
Hi guys,
I want to load base url of api for the quasar app ,which is set from docker and use this var in quasar.conf.js. 
can anyone  help ?

**Comment by rstoenescu** [comment]
There are a few things wrong with this ticket based on the fact that you totally dismissed the github issue template:

1. Github tickets are used exclusively for bugs or feature requests
2. Questions are for our Discord server or forum. We recommend the [Discord](http://chat.quasar-framework.org) way.
3. You are asking a question without checking documentation first. https://quasar-framework.org/guide/app-quasar.conf.js.html#Example-setting-env-for-dev-build

Time is precious for both you & us, so please help us deliver quality services by eliminating these kind of questions without first investigating if they are already documented or not.
