### ISSUE TITLE
vue-cli as a dependency, should be verifyed

### ISSUE THREAD

**Issue by maxi032** [quasarframework/quasar#2087]
I am trying to install it in my vagrant box (Ubuntu 16). I have node 10.2.1 and yarn 1.6.0
I've installed quasar-cli with yarn but it does not find the vue-cli.
<pre>quasar init myquasarapp
 Running command: vue init 'quasarframework/quasar-starter-kit' myquasarapp
 app:init â ï¸ Something went wrong... Try running the "vue init" command above manually. +0ms
 app:init Reasons for failure: Package @vue/cli and @vue/cli-init are not installed globally, specified template is unavailable or it failed to download. +2ms </pre>

**Comment by rstoenescu** [comment]
vue-cli is not managed by Quasar CLI and it's not a dependency of it. It is just used on "init" command. This scenario is similar to "cordova" global, which must be installed by the developer. So install vue-cli globally like Quasar CLI suggests.

**Comment by maxi032** [comment]
Thanks for your fast reply. 
I've done that but I still get an error
<pre>
 Installed "@vue/cli@3.0.0-beta.11" with binaries:
      - vue
Done in 5.99s.
vagrant@phalcon:~/workspace$ quasar init myquasarapp
 Running command: vue init 'quasarframework/quasar-starter-kit' myquasarapp

  Command vue init requires a global addon to be installed.
  Please run yarn global add @vue/cli-init and try again.

 app:init â ï¸ Something went wrong... Try running the "vue init" command above manually. +0ms
 app:init Reasons for failure: Package @vue/cli and @vue/cli-init are not installed globally, specified template is unavailable or it failed to download. +1ms
</pre>
