### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#209]
Hi,

It would be worth to create long time roadmap for Q.
It would make Quasar more serious and could convince some people to use it as it will then look more as long time project instead of another github package which will stop being maintained without any explanation.

**Comment by rstoenescu** [comment]
Agreed.

**Comment by xereda** [comment]
Excelent idea.

**Comment by rstoenescu** [comment]
Done! https://github.com/quasarframework/quasar/projects/3
