### ISSUE TITLE
[Request] "Swipe down to close" on modal from bottom.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2096]
Recently a lot of services (eg. Google Maps.) have these modals from bottom that you can swipe up to expand or swipe down to close or contract.

I'd love a similar component, or this "swipe up to make full screen" / "swipe down to close" function on the [Modal from bottom](https://quasar-framework.org/components/modal.html)

**Comment by rstoenescu** [comment]
Hi,

This would complicate QModal a lot and make it hard to maintain. Sorry for any inconvenience, but closing this.
