### ISSUE TITLE
[Request] Inline image/video support for Chat component.

### ISSUE THREAD

**Issue by felixis-1** [quasarframework/quasar#2097]
The fact that Quasar comes out-of-the-box with a chat component is great. If only it could be enhanced to have images/videos display inline as well along with chat messages, this can be useful for many use cases. This would include having another attribute on the component for image and video and it shows clubbed together with any text if that is available as well.

**Comment by nothingismagick** [comment]
@felixis-1 - this is one of those deep applications of lots of business logic (including upload / link rendering, etc.) that is complex depending on your backend and your needs. I would recommend you check out the section of our documentation about [building (and extending) reusable components.](https://quasar-framework.org/components/building-reusable-components.html)

**Comment by pdanpdan** [comment]
QChatMessage allows you to use anything as content, so you can put image/video there.
