### ISSUE TITLE
[request] Expose rowsPerPage in QDataTable as property

### ISSUE THREAD

**Issue by u2ros** [quasarframework/quasar#2098]
Currently, there is no way to set initial rowsPerPage in a QDataTable, which is set at 5 rows currently. It would be great if one could set this as an exposed property for example:

`<q-data-table rows-per-page="20" />`

**Comment by Lou-Der** [comment]
This is in the current framework, not sure what version your running though:

https://quasar-framework.org/components/datatable.html#Pagination

**Comment by u2ros** [comment]
You are right, i missed it somehow (was looking at a single property i could set for this)
