### ISSUE TITLE
[REQUEST] Slider/Range reverse option so slider can go from max to min

### ISSUE THREAD

**Issue by skmbr** [quasarframework/quasar#2099]
It would be great if we could reverse the direction of a slider or range component so that the max value is on the left and the min value on the right.

At the moment I am doing this with a computed value on a slider, but this is a bit messy and becomes even messier on a Range.

The ideal solution for me would be a "reverse" option that just swaps min and max.

I tried flipping and rotating the slider in CSS as I'm not using labels, but this just resulted in the slider handle moving in the opposite direction to the mouse :(

**Comment by rstoenescu** [comment]
What is the use case for this? Is it related to RTL? If so, please close this ticket and take a look at https://quasar-framework.org/components/rtl-support.html -- because it's part of the full RTL support that Quasar already offers ;)

**Comment by skmbr** [comment]
Can I apply RTL to a single slider dynamically? If so that might do what I need.

But that's not why i'm doing it.  The slider relates to the position of things on a diagram and from a UX perspective it makes more sense for the lower numbers to be on the right.

In more detail the slider relates to the number of boards on a tenpin bowling lane.  If you're right handed you count the boards from right to left, if you're left handed you count from left to right.

So based on this.handed being "left" or "right" I would change the direction of the slider.

**Comment by pdanpdan** [comment]
Closing this one to follow in #5691.
