### ISSUE TITLE
[Request] q-input: Mask number separator (eg. 5,000,000)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2101]
On [q-input](https://quasar-framework.org/components/input-textfield.html) I currently require the function to mask the number input as a price.

eg.
`¥5,000`
or
`$50.00`

Prefix and decimals are already an option, so now I'd just need the option to set `,` to show every 3 numbers.

**Comment by rstoenescu** [comment]
Duplicate of v
