### ISSUE TITLE
Suggestion for a quasar popup component

### ISSUE THREAD

**Issue by darkscript** [quasarframework/quasar#2104]
Quasar: 0.16.0
OS: 
Node: 8.9.0
NPM: 5.6.0
Browsers: Mozilla and Chrome 
iOS:
Android: 7.1.1
Any other software related to your bug: No

### What did you get as the error?
No errors, more of an improvement

### More Description
It would be great to have an extra component which have a pointer div and a cancel button, floats on top of q-pages or other components and unlike the popover, it will only be closed if the cancel button is clicked. It should have the behaviour similar to the one [here](https://leafletjs.com/examples/quick-start/example.html). It should also be possible to have several of them floating on a component. I attached an image below to show what it should look like.
![popup](https://user-images.githubusercontent.com/13992858/40766709-1229969e-64b9-11e8-9053-28f6ce49d952.png)

**Comment by nothingismagick** [comment]
As with my comment at #2105 - this too is a UI feature that would be nice to have, but someone needs to write the code for it. Where I come from, the person who has the idea is always responsible for making sure that it is realized. So make a PR (or trick someone else into doing it for you) and then we can see if it is something to bring into the project.

**Comment by darkscript** [comment]
@nothingismagick did add some more info, not sure if there is any more entry relevant to this issue/enhancement

**Comment by rstoenescu** [comment]
Merged with https://github.com/quasarframework/quasar/issues/2105 so closing this issue.
