### ISSUE TITLE
[Request] QDialog Improvements

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2108]
I'd like to suggest a few improvements to QDialog:

## 1) Allow `message` to be rendered as HTML whether optionally or by default.

Currently the `message` property always renders as a literal string, so you cannot do things like:
```javascript
this.$q.dialog({
  title: 'Destroy everything',
  message: `Are you sure you want to destroy everything? 
    This is super dangerous and <em><strong>cannot be undone.</strong></em>.`,
})
```
**without having to create a custom QDialog component.**

You can see how this would be useful
![Not emphasized](https://i.imgur.com/MtuODiU.png)
vs
![Emphasized](https://i.imgur.com/CRBQzq9.png)

Something like this could be useful:
```javascript
this.$q.dialog({
  title: 'Destroy everything',
  message: {
    body: `Are you sure you want to destroy everything?
      This is super dangerous and <em><strong>cannot be undone.</strong></em>.`,
    asHtml: true
  }
})
```
## 2) Don't show console error by default on cancel

Currently, when you cancel a QDialogue, it emits a console error:
`Error: Unhandled promise rejection`

In order to fix this, each `this.$q.dialog` has to have a `.catch(() => { })` chained onto it even if you don't want to do anything with the error. It would be nice to handle the rejection by default.

**Comment by olegvakulenko** [comment]
https://github.com/quasarframework/quasar/issues/1851

**Comment by rossity** [comment]
Hmm, then what about markdown? Even if there were just simple tags.

```javascript
this.$q.dialog({
  title: 'Destroy everything',
  message: {
    body: `Are you sure you want to destroy everything?
      This is super dangerous and **_cannot be undone._**`,
    asHtml: true
  }
})
```

Would that be too large of a scope?

**Comment by nothingismagick** [comment]
As in the response of @pdanpdan in the **closed** issue linked by @olegvakulenko, this is not going to change. If you need to make modifications to existing components, I recommend following the procedure here: http://quasar-framework.org/components/building-reusable-components.html

That said, XSS is not something you can just ignore - even if you are targeting electron (e.g. what happened with the Signal desktop app recently).

Finally, please close this issue and make a new issue that is explicitly about the point you addressed in 2. above. Then make a PR against dev and we'll talk about it when it lands. Thanks!

**Comment by rossity** [comment]
@olegvakulenko thanks for the link! great info.

And will do @nothingismagick.
