### ISSUE TITLE
DateTime issue - if v-model is missing, should be initiated with moment()

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#211]
Hi,
I am again and again struggling with issues with DateTime.
It basically has serious issues if v-model is not initiated since the beginning which is giving issues with dynamic data.
E.g. it is not throwing ANY ERROR but not working - it is shown, but I can't change the date (even if it looks like value in component is changing).
It becomes live when I will close editing div which is based on `v-if` and go back again to edit the same element.
It is really strange behaviour, to be honest. I am even initiating missing data before `v-if` which is on the parent of datatime gets true, but it still doesn't help.

I do not have issue with other datetimes which are inside `v-if` and have similar data connection, so I am not sure what is causing this issue to be honest.

**Comment by rstoenescu** [comment]
Fixed already in v0.9. With v0.9 either use empty string or a moment formatted string.

**Comment by murbanowicz** [comment]
Can you publish dev versions to npm? I would like to update to see if it cures this described issue or not as it is really annoying. 
Another thing is that would be good if datetime wouldn't crash anyhow if `v-model` variable is undefined so, in this case, it would initiate with default value to prevent unwanted behaviour, What you think?

**Comment by murbanowicz** [comment]
Can I get 0.9 from npm anyhow to see if it is solving this issue which I have?
