### ISSUE TITLE
[Request] Don't show console error by default on cancelling QDialog

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2110]
Currently, when you cancel a QDialogue, it emits a console error:
`Error: Unhandled promise rejection`

In order to fix this, each this.$q.dialog has to have a `.catch(() => { })` chained onto it even if you don't want to do anything with the error.

It would be nice to have the component handle the rejection by default.

**Comment by pdanpdan** [comment]
And how would the user know the dialog was canceled?

**Comment by shandrolis** [comment]
@pdanpdan Why would you possibly want to throw an error to let the user know a dialog was canceled? Like @rossity mentions, ideally the component would handle this so that we don't have to. Don't throw errors for what could very well be intended behaviour.

**Comment by pdanpdan** [comment]
A dialog cancel if not the intended behavior, but an expected behavior, and should be treated - in the same way that 4xx response should be.
