### ISSUE TITLE
[bug]  "export 'axios' was not found in 'quasar'`

### ISSUE THREAD

**Issue by dkebler** [quasarframework/quasar#2111]
sorry to make a bug report but this seems like a .16 bug at least with 10+ since all i did was follow exactly the guide using the supplied axios plugin code.

see third entry in this post for details
https://forum.quasar-framework.org/topic/2326/16-custom-plugin-not-found-webpack/3

Quasar: .16.x
OS: LInux Ubuntu 16.04
Node: 10+
NPM: 6+ and latest yarn
Browsers: firefox, chrome

### What did you get as the error?
`17:235-240 "export 'axios' was not found in 'quasar'`

### What were you expecting?
no warning/error

### What steps did you take, to get the error?

Just follow the plugin instructions using your axios example from the guide

**Comment by rstoenescu** [comment]
'axios' should be under:
```js
return {
   // app plugins (/src/plugins)
   plugins: [ 'axios' ]
}
```

NOT under:
```js
framework: {
  plugins: {...}
}
```

You're using an app plugin, not a Quasar plugin.

**Comment by dkebler** [comment]
I finally figured this out before your reply.

Suggestion the docs could be altered because of the two plugin keys in the config file may cause confusion (like in my case)

Include the part above the `return` in the docs so it definitely won't be confused with the plugin key under framework

````
module.exports = function (ctx) {
  return {
    // app plugins (/src/plugins)
    plugins: [
      'mypluginfilename'
    ],
```
