### ISSUE TITLE
[Request] Modal: position top + maximised option

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2112]
In reference to #2106
I require a modal coming down from the top but still be maximised.

Currently it's only possible to have either one of the two. I request the ability to have them both. : )

**Comment by rstoenescu** [comment]
Coming down from top, as in when you show the Modal to animate from top? Then use the animation props on QModal...

**Comment by alterhu2020** [comment]
@rstoenescu  why closed this issue , i met this issue when I want to show a modal dialog from bottom and also maximized, but as you pointed in https://github.com/quasarframework/quasar/issues/2106 ,it only can either `position` or `maximized`.
So how can I achieve as @mesqueeb  met here?

```
<q-modal v-model="currentShow" position="bottom" maximized>
      <q-modal-layout>
        <q-toolbar slot="header">
          <q-btn
            flat
            round
            dense
            @click="currentShow = false"
            icon="reply"
          />
          <q-toolbar-title>
            Header
          </q-toolbar-title>
        </q-toolbar>
        <div class="layout-padding">
          <q-btn color="primary" @click="currentShow = false" label="Close" />
        </div>
      </q-modal-layout>

```
Thanks .
