### ISSUE TITLE
Number input, enter not handled correctly

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2113]
Based on https://github.com/quasarframework/quasar/issues/1996

Use case:
1) Type in 123
2) Remove everything with a backspace
3) Submit the form by pressing enter
4) 1 gets submitted instead of an empty value

https://jsfiddle.net/hdyn1b93/68/

Thanks!

**Comment by Lou-Der** [comment]
Yes, not intuitive behavior IMO, but your submitting a single input via enter.  

If it was blur'd from another button or field before submit it would update correctly.   The stranger part is that this isn't a issue in "text" type inputs, only number.  Must be something in the number validation code on q-input.

As a work around  for a single input submit try changing it to:
    <q-input type="number" v-model="number" @keyup.enter="number= $event.target.value ; submit()" />

**Comment by rstoenescu** [comment]
This IS duplicate of https://github.com/quasarframework/quasar/issues/1996
Same explanation here....

**Comment by jean-moldovan** [comment]
@rstoenescu In your opinion value reset on enter should be handled outside of Quasar (app  logic) ?

**Comment by cslee** [comment]
Submitting by pressing a button requires special handling too. When user clicks a submit button, the valid value is not updated to the model until the blur event. But I found that the blur event of the input box can come 100ms+ after clicking the submit button. So I had to add a 200ms delay in handling the submit action. Not sure if there is a better way to handle this kind of problem.
