### ISSUE TITLE
Request: Add unified documentation for slots / slot property

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#2115]
I was looking for documentation about slots usable with tables.No luck.

I propose a dedicated paragraph about usable slots on each and every relevant component doc page.

**Comment by rstoenescu** [comment]
Please open this to the right repo: https://github.com/quasarframework/quasar-framework.org/issues
Thanks.

Also, take a look at the demo and source code. It's 99% of the use cases.
