### ISSUE TITLE
Textarea height issue

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#212]
Hi,

Quasar is automatically applying quite big height for textarea.
It should be based on `rows` property to make it usable.
Currently it is not responding for any change of rows which in my case makes it impossible to get 3 rows textarea,

Hope you agree with that.

**Comment by joaopaulofilho** [comment]
You could fix it with css.

**Comment by murbanowicz** [comment]
Agree, but as you said - FIX.
It should not need FIX, it should work out of the box :)

**Comment by joaopaulofilho** [comment]
Isn't there a PR about it?

**Comment by rstoenescu** [comment]
This one was extremely easy to "fix". Please help me out (whenever you can) with a PR on things so easy so I have more time for the hard ones. Thanks.
