### ISSUE TITLE
Tooltip for button that opens dialog re-appears after dialog is closed

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#2121]
With16.4, Edge

I have a button with tooltip. On click a dialog is opened. The tooltip appears. I click. I move the pointer away from the button. Tooltip disappears. I close the dialog by clicking on close button. the tooltip for the button re-appears without the pointer being near to it. It stays visible until I move the pointer back on the button or click somewhere.

**Comment by rstoenescu** [comment]
Hi, jsfiddle please.

**Comment by pdanpdan** [comment]
This is related to refocusing after the dialog is closed. I would say it's the normal behavior, because after dialog close the button has focus again and the tooltip shows on focus also.

**Comment by aprixon01112017** [comment]
In this situation I can have two tooltips - one on the opening button and one on another GUI element.
