### ISSUE TITLE
QAutocomplete does not work properly on latest iOS version when scrolling

### ISSUE THREAD

**Issue by darknessm0404** [quasarframework/quasar#2125]
Quasar 0.16.0

Reproductible within the [website Quasar Play]( https://quasar-framework.org/quasar-play/apple/index.html#/)
  quasar-cli                    0.15.1  (Quasar Framework CLI)
  quasar-framework              0.16.0  (Build responsive websites, PWAs, hybrid mo
iOS: 11.3.1

### What did you get as the error?
No error. The items that autocompletes displays have a wrong offset once you touch and scroll the display of the iOS device.

### What were you expecting?
On previous version, the offset was correct (it worked on 0.15 Quasar versions)

### What steps did you take, to get the error?
Open anything that uses the autocomplete and displays more than one autocomplete items on an iOS device (you need to have enough items to display so you can scroll) then try to scroll with your finger, and you will see that the offset position of the list of items is bad (it's either going too high or down depending on the scroll movement and the original position)

**Comment by rstoenescu** [comment]
Nothing changed in that area, so most likely more bugs from the new iOS version... Will investigate.

**Comment by 37ch4** [comment]
Incase it helps here is a screen shot.

![autocomplete-alignment](https://user-images.githubusercontent.com/19803755/41380363-93cf742e-6f19-11e8-9253-837b48da2f1a.png)

**Comment by amant** [comment]
Any idea on when v0.16.1 will be released ?

**Comment by rstoenescu** [comment]
@amant Beginning of next month.

**Comment by rstoenescu** [comment]
Went into v0.17 eventually.
