### ISSUE TITLE
[Proposal] Modify q-item-label css attributes for better drawer mini mode rendering

### ISSUE THREAD

**Issue by onurkose** [quasarframework/quasar#2126]
Hi folks,

The new drawer mini mode is fantastic.
Bu when you switch mini mode to full mode with mouse events, you may also witness menu item label texts have a multi-line > single-line conversion effect, which makes drawer inner height looks longer for a couple of miliseconds, and then backs to normal height once the drawer completes expanding.

So I've figured out a workaround by adding this;

`.no-wrap-parent .q-item-main > .q-item-label {
  white-space: nowrap;
}`

But this workaround **will not work** if you add the white-space nowrap tweak to the .q-layout-drawer-mini css class. Because q-layout-drawer-mini removes itself from drawer's class list immediately once mouseevent is detected. So my suggestion is to add a transition class something like q-layout-drawer-mini-expanding with extended coverage of white space nowrap.
Thanks.

**Comment by rstoenescu** [comment]
Fix will be available in beta.5.
