### ISSUE TITLE
[Request] Add a max number of chips to component <q-chips-input>

### ISSUE THREAD

**Issue by Matteus54** [quasarframework/quasar#2127]
Hello everyone,

i have to used a <q-chips-input> component to store tags on commentaries. The problem is, i can't add a max input number. I would like to store max 3 of them. At this number, the user should only be able to delete chips, and then add again.

My current line of code is like that
`<q-chips-input float-label="Mots-clés*" class="margin-top-2" v-model="ifthen.keywords" />`

and it would be awesome to add something like this
`<q-chips-input max="3" float-label="Mots-clés*" class="margin-top-2" v-model="ifthen.keywords" />`

I think this feature could be nice to add.

Thanks for your return !

Matt

EDIT:

At this moment, i have a trick to handle this feature

`<q-chips-input float-label="Mots-clés*" class="margin-top-2" v-model="question.keywords" @input="checkKeywords"/>`

`checkKeywords () {
      if (this.question.keywords.length > 3) {
        this.$q.notify({
          message: 'Trois mots-clés au maximum sont autorisés',
          icon: 'warning'
        })
        this.question.keywords.splice(3, 1)
      }
    }`

**Comment by pdanpdan** [comment]
Maybe it would be more flexible if we add props to disable add and delete (noAdd, noDelete).
That way it would just be:

```html
<q-chips-input  v-model="model" :no-add="model.length > 2" />
```

And this will also allow other use cases, like checking if some values are present.

**Comment by ilyablbnv** [comment]
Hi, is there a plan to implement this feature? I could barely imagine chips input without this extremely useful prop :(

**Comment by rstoenescu** [comment]
@ilyablbnv it will have it, but for v1.0.

**Comment by rstoenescu** [comment]
Done for future v1.0 through the smarter QSelect (which includes QChipsInput with a LOT more features and flexibility).
