### ISSUE TITLE
[Feature Request] Carousel thumbnails visibility

### ISSUE THREAD

**Issue by cjpit** [quasarframework/quasar#2133]
Hi there, just started using your new thumbnails feature for the carousel.  Would it be possible to have a prop to always show the thumbnails, so the user doesnt have to click the button to enable it up in the corner?

Thanks

**Comment by schniper** [comment]
You can add this method, add a ref to your carousel (mine is gallery) and call it from a mounted() handler; the reason for the iterations is that depending on the nesting level of your carousel, its ref appears not to be ready after the first $nextTick.

```
enableGallery(retries = 10) {
      this.$nextTick(() => {
        // $refs seems to be ready around the 4th $nextTick
        if (!this.$refs.gallery) {
          if (retries > 0) {
            return this.enableGallery(retries - 1)
          }
          return false
        }
        this.$refs.gallery.viewThumbnails = true
        return true
      })
    }
```

**Comment by rstoenescu** [comment]
Hi,

On future v1.0 there's a prop called `thumbnails`. If you set it to `true` it will always display thumbnails.
