### ISSUE TITLE
[Regression] Dialog is not blurring input element in v0.15.15/v0.16

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar#2137]
### Software version

Quasar: 0.15.15 / 0.16
Browsers: Chrome

### JsFiddle (for Quasar v0.15+ only)
correct behavior in 0.15.0: https://jsfiddle.net/09kwm3fd/1/
regression behavior in 0.15.15: https://jsfiddle.net/wo2arjb0/

### What did you get as the error?
Dialog is not blurring the input element that triggered it when dialog is presented

### What were you expecting?
Dialog to take focus

### What steps did you take, to get the error?
1) Click on the jsfiddle with 0.15.0 correct behavior above.
2) Focus the input element and then hit 'enter' on your keyboard
3) A dialog appears, and at the same time, the dialog is focused and the input field is blurred

4) Click on the jsfiddle with 0.15.15 regression behavior above.
5) Focus the input element and then hit 'enter' on your keyboard
6) A dialog appears, but the input remains focused and hitting enter again causes a second dialog.

I realize noRefocus was added between these versions (but not used in this example), and I think the dialog should still blur the input field when it appears.

**Comment by rstoenescu** [comment]
Available in future Quasar v0.16.1
