### ISSUE TITLE
[Bug] Dropdown popover appears above QSelect and jumps around when filtered 

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2142]
Example of bug:
![Dropdown Bug](https://i.imgur.com/tBw79gj.gif)

It would be nice to be able to force the drop-down to always appears below the select box, and it would also be nice to be able to give a max-height of the drop-down (popover).

How to reproduce:
```
<q-select
  v-model="state"
  :options="stateOptions"
  filter
  filter-placeholder="Start typing to search..."
  autofocus-filter
  float-label="State"
/>
```

**Comment by rstoenescu** [comment]
Fixed in future v0.16.1.

**Comment by tncho** [comment]
@rstoenescu Hey there! I'm encountering this issue (I thought it might be related to [#338](https://github.com/quasarframework/quasar/issues/338) as well, and I can't afford to upgrade to 0.16 atm (currently working with 0.14).  Basically the q-select dropdown menu appears from the top of the viewport on iOS and not below the input.
Do you happen to know a solution for this that doesn't involve library updating as a whole? If not, no worries.
Thank a million

**Comment by rstoenescu** [comment]
@tncho Hi, sorry, but it indeed would involve a new v0.14 release, which is currently impossible due to time constraints :(
