### ISSUE TITLE
non-functional electron builder configuration

### ISSUE THREAD

**Issue by yanvigdev** [quasarframework/quasar#2148]
How can I add extraResources when building an "electron" application with quasar?

I added extraResources in the "electron" > "builder" part of the "quasar.conf.js" file but I have the impression that it is not applied.

```js
electron:   {
            extendWebpack(cfg) {
            },
            packager: {
            },
            builder:  {
                extraResources: ['**/plip/plop.txt']
            }
        }
```

**Comment by rstoenescu** [comment]
Hi,

1. This should have been opened on the Quasar CLI repo.
2. I don't see that you also tell Quasar to use the electron-builder, so it defaults to electron-packager. Unless you're specifying the bundler by using its command line parameter?

In any case, add this to your quasar.conf:

```js
electron: {
  bundler: 'builder'
```
