### ISSUE TITLE
[Feature request] Input (Textfield): add debounce property 

### ISSUE THREAD

**Issue by bertvandeneynde** [quasarframework/quasar#2150]
Hello.
Feature request
Regarding component: Input (Textfield)
I would like to have an extra Vue Property "debounce"
Working exactly as it does for QSearch

I know you have the utilty, but for input it would also be very nice as property.

greetings, Bert from Synbits

**Comment by bertvandeneynde** [comment]
Fyi, using QSearch (with no-icon property) as alternative now

**Comment by jean-moldovan** [comment]
Looks like they could be merged in this case (Input and Search) as I don't see that big of a difference (apart from search icon, but this is minor).
