### ISSUE TITLE
Microsoft Edge layout issues

### ISSUE THREAD

**Issue by blaluc** [quasarframework/quasar#2151]
### Software version
quasar-cli: 0.16.4
quasar-framework: 0.16.0 

Microsoft Edge 42.17134.1.0

### What did you get as the error?
Using Microsoft Edge There are some issues in the layouts (e.s. components overalpping, wrong positioning, etc.). Don't know if it's somehow related to the flexbox support.

E.g.:

If you go to the official quasar showcase
https://quasar-framework.org/quasar-play/apple/index.html#/showcase/grouping/table/table-features
in the section named: "Filter, Column selection, Separators, Toggle fullscreen", you'll get the following (the search field does not appear and cannot be edited, while some other components are overlapped) :
![image](https://user-images.githubusercontent.com/4599417/41229670-2686e098-6d7d-11e8-9113-bb2d077912e2.png)

**Comment by rstoenescu** [comment]
Fixed already in future 0.16.1
