### ISSUE TITLE
[Request] Status based colors on QStepper

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2154]
Currently QStepper has the ability to set icons for each stage of the step

| Vue Property | Type | Description |
| --- | --- | --- |
| `done-icon` | String, Boolean | Used to change the display of the Step icon, when the step is finished. Default is the "check" icon. |
| `active-icon` | String, Boolean | Used to change the icon, when a Step is selected. Default is the "edit" icon. |
| `error-icon` | String / Boolean | Used to change the icon, when there is an error in a Step. Default is the "warning" icon. |

It would be nice to be able to change these to be in line with your color themes.

| Vue Property | Type | Description |
| --- | --- | --- |
| `done-color` | String, Boolean | Used to change the color of the Step icon, when the step is finished. Default is `primary`. |
| `active-color` | String, Boolean | Used to change the color, when a Step is selected. Default is `primary`. |
| `error-color` | String / Boolean | Used to change the color, when there is an error in a Step. Default is the `danger`. |

example:
![Example](https://i.imgur.com/htQYW8f.png)

**Comment by nothingismagick** [comment]
Wouldn't this be really easy to do with the 'color' plugin and a watch on the v-models?

**Comment by rossity** [comment]
Yep! And I've already implemented it in my project. I'm mainly posting here as I think it's an idea worth considering for the main framework so others don't have to do the same.

Right now the step only turns `danger` if their are errors, which is great, but there should be a way to change the step color if it's completed or active too. It just makes sense because you can already change the icon for those states.

I'll submit a PR when I can get to it, I posted it here for now so I can get it out of my head and written down somewhere.

**Comment by rstoenescu** [comment]
Implemented for v1.0.
