### ISSUE TITLE
QAutocomplete bad popover positioning

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2157]
Hello,

This happens when you have a popover with a long list of items that opens from bottom to the top.

Here is a fiddle:
https://jsfiddle.net/oj6gc8hq/1308/ < - type in 1, then 11

Thanks!

**Comment by MitchellMonaghan** [comment]
Hi guys saw that you fixed this for staticData but this will still be broken for non staticData. I think this needs to be added to line 130 in QAutocomplete.js

this.$nextTick(() => this.$refs.popover.reposition())

I can do a pull request if you like but I have never done one before.
