### ISSUE TITLE
QAutocomplete keyboard navigation on long lists

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2158]
Hello!

This is an interesting case: https://jsfiddle.net/waugrryy/2907.

When you have a long list of items with scrolling and try to navigate to the last item via keyboard, scroll stays at the same position and you sort of loose highlighting:

![screen shot 2018-06-12 at 14 51 27](https://user-images.githubusercontent.com/3635352/41288804-4256f2c6-6e50-11e8-9dfb-5b33c7bb25f3.png)

**Comment by pdanpdan** [comment]
I'll take a look on this and #2156 - it wasn't designed with scroll in mind in the beginning.
