### ISSUE TITLE
[Enhancement] Provide global 'tickable' setting for QTree

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#2162]
I'm using a QTree to display a set of hierarchical labels which are several levels deep, and normally they are 'tickable' via `tick-strategy="strict"` to allow the user to choose which apply. But I'd also like to offer a 'read-only' version of the tree, which looks the same but can't be changed.

The `tickable` setting on the node does achieve what I'm after, but it's quite expensive and cumbersome to flip that on _every single node_—indeed I can't see a way to do it with a simple `map()` type operation, as it requires recursing into each (possibly absent) `children` array.

I tried changing the `tick-strategy` at the QTree level to `none`, but that removes the checkboxes completely, which isn't what I want.

Therefore, I'd like to propose having a `tickable` property at the QTree level, as well as at the nodes level. It could work like `tickStrategy`, which can be set globally, and then overridden at the nodes level if needed.

**Comment by pdanpdan** [comment]
There is enough to set `tickable: false` on the root node. If the children nodes do not have `tickable: true` then all will be un-tickable.

**Comment by dsl101** [comment]
I'm confused what you mean by the 'root' node, as it's an array. I made a code-pen [here](https://codepen.io/dsl101/pen/MWYJpGB). Could you alter it to show what you mean? What I need is a 'read-only' display of which items are ticked. I set `tickable: false` on the first element, which does stop 'Top level 1' being changed, but still allows all its children to be changed. I'd like to avoid having to iterate through what in my app is a very large structure setting `tickable: false` on every node...

**Comment by pdanpdan** [comment]
Sorry, I didn't see you were using tickStrategy strict.
Here is how it's done: https://codepen.io/pdanpdan/pen/WNbRjML?editors=1010
The ':ticked.sync="tickModel"' modifier is a syntactic sugar for `:ticked="tickModel" @update:ticked="v => tickModel = v"`

**Comment by dsl101** [comment]
That's even better, as I have a handler for ticked changing attached to `@update:ticked`! Now I can simplify everything :). I knew there'd be a better way. Many thanks.

The only benefit I could see of this being in the component as a prop is to change the visual of the checkbox to `disable` so the user can tell clicking would have no effect. Is there way of doing that without iterating the nodes and adding `tickable: false` to each?

**Comment by pdanpdan** [comment]
I updated the demo with CSS to disable the ticks: https://codepen.io/pdanpdan/pen/WNbRjML

**Comment by dsl101** [comment]
Thanks Dan. Sure I can't convince you that this should be in the component? Needing `!important` in the app style seems like a workaround :)

Anyway, at least I can get the look & functionality I need. Tx.

**Comment by pdanpdan** [comment]
The !important was there to be the exact same style a disabled QCheckbox has - it works without it.

**Comment by dsl101** [comment]
I don't see the 'disable' pointer effect (in FF 71 or Chrome 80), if that's what you meant—either with or without `!important`... I presume it would also need some hover CSS to change the pointer?

![image](https://user-images.githubusercontent.com/900542/71085894-6fa03900-2190-11ea-9e31-d8a471423919.png)

**Comment by pdanpdan** [comment]
Ok, refresh the codepen.

**Comment by dsl101** [comment]
Great—looks and behaves well now. But that CSS does seem very hacky on the app side. Could this functionality still be considered for an enhancement to QTree?
