### ISSUE TITLE
Feature request: horizontal scroll

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2163]
See e.g. [here](https://forum.quasar-framework.org/topic/909/q-scroll-area-dosen-t-work-for-horizontal).

**Comment by slowaways** [comment]
Already implemented in v0.17.0! Please, close this issue!

**Comment by Eencsio** [comment]
where is the documentation for this feature?

**Comment by onexdata** [comment]
@rstoenescu & @slowaways ... 0.17.0 only implemented horizontal scroll in q-modal.  No work was ever done to the q-scroll-area component as this request is asking for.  This was closed by mistake.

This does not address horizontal scroll in q-scroll-area
https://github.com/quasarframework/quasar/issues/2450

**Comment by rstoenescu** [comment]
Will be available in 1.0-beta.5.
