### ISSUE TITLE
QSearch focus() inside of QModal not triggering iOS keyboard display

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar#2167]
### Software version

Quasar: 0.16.0
OS: iPhone
Browsers: Mobile Safari
iOS: 11.4

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/oj4msev1/7/

### What did you get as the error?
Focusing a QSearch component inside of QModal does not trigger iOS keyboard display.

### What were you expecting?
Behavior similar to focusing a QSearch component outside of the QModal

### What steps did you take, to get the error?

Correct behavior:
1) Load the jsfiddle above on an iPhone (may need to be landscape to see)
2) Click the 'Focus Normal' button
Result: QSearch is focused, and iPhone keyboard displays for user input.

Incorrect behavior:
1) Load the jsfiddle above on an iPhone
2) Click the 'Focus Modal' button
Result: Modal pops open, QSearch is focused, but iPhone keyboard does not display for user input.

**Comment by pdanpdan** [comment]
Can you please check if this works:
https://jsfiddle.net/gbv9um28/

**Comment by mattwright** [comment]
Nope -- 'Focus modal' still not popping up the keyboard on iOS 11.4 Mobile Safari, although the 'focus normal' button does... An additional tap on the modal's search field does popup the keyboard. In both instances, the fields do appear to be focused in terms of the underline css on the input field... 

I acknowledge this may be more of an iOS-specific issue than a Quasar issue, in which case you can feel free to close it. I was just hoping it had an easy fix.

**Comment by pdanpdan** [comment]
Can you please try this one:
https://jsfiddle.net/gbv9um28/1/
Maybe play with the timeout value

**Comment by mattwright** [comment]
Yeah, still not popping it up. That was one of the curious things -- I had tested this with even a three second timeout value to call back so that the modal would definitely be popped up and visible. What happens is the modal pops up, then you can later see the field focus once the timeout fires (css effects applied so that the colored underline animation for a focused field happens), but the keyboard is never triggered in iOS. Without the qmodal, the keyboard does trigger immediately.

I'm starting to think it may just be an iOS thing... When I delay the focus by 100 milliseconds, even on the non-modal qsearch, iOS also fails to popup the keyboard. So iOS may require that the focus happens synchronously in relation to the touch before it pops up the keyboard (and so any callbacks after the modal pops up therefore causes the keyboard not to pop)...

Here is an example showing that: https://jsfiddle.net/oj4msev1/17/

I'm going to close this, since it appears that it's not related to the QModal. Thanks for looking into it, sorry I didn't test the delayed callback to the non-modal version, I hadn't thought of that.
