### ISSUE TITLE
[ios] Insufficient margin in the Drawer header.

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#217]
Insufficient margin in the Drawer header.

The lack of margin at the top of the application header is resulting in a poor usability experience. When I try to access the menu, the access button (hamburger / 3 lines) gets very close to the cell status bar, which results in its inoperability most of the time. I need to keep trying to hit the button to get the sidemenu to open.

I think we should, by default, increase this distance between the Drawer Quasar header and the cell phone status bar.

To illustrate this, I took some applications as an example.

quasar app:
![no_space](https://cloud.githubusercontent.com/assets/14337850/20458236/71597f84-ae86-11e6-89e6-638bc67a9156.jpg)

zocdoc:
![zocdoc](https://cloud.githubusercontent.com/assets/14337850/20458237/7b976902-ae86-11e6-8b19-30d40af5d292.png)

google inbox (new gmail):
![inbox_google](https://cloud.githubusercontent.com/assets/14337850/20458283/ac17c40e-ae87-11e6-8905-7fa2cc18d87a.jpg)

made in ionic1:
![ionic1](https://cloud.githubusercontent.com/assets/14337850/20458286/c7fcee38-ae87-11e6-9fbb-b110d1944a07.jpg)

google drive:
![google_drive](https://cloud.githubusercontent.com/assets/14337850/20458294/f9aba230-ae87-11e6-819b-1babdf8a53fb.jpg)

These are just a few examples. All of them have a larger margin between the header and the cell bar status.

Another issue I believe affects the sensitivity of the burger button, is its size. It should be a little bigger. Close to 20% ... what do you think !?

**Comment by robmpreston** [comment]
Yes, I had to manually adjust the size of the burger button and the margin on my production apps. Was hard to trigger it, especially on my 6+.

**Comment by rstoenescu** [comment]
Confirmed. Will get fixed.

**Comment by xereda** [comment]
@robmpreston In what class did you increase the margin?

**Comment by xereda** [comment]
I'm trying to palliate this need, but it's not getting good. The header buttons and title are centered, and that's not what we need. We need only a padding to occur at the top of the header.

**Comment by rstoenescu** [comment]
Just please wait for the fix. It should be easy. Didn't have time for it yet. Consider this solved. It will get into v0.9 which I'll release this week. Thanks.

**Comment by xereda** [comment]
Tks.

**Comment by sunnygill31** [comment]
@rstoenescu I think this is again broken with iPhone X.

**Comment by rstoenescu** [comment]
@sunnygill31 iPhoneX changes a few things. The new starter kit for v0.15 takes care of the problem. Will do a final test before v0.15 is released (really soon).
