### ISSUE TITLE
[BUG] Select component filter pressed down freeze browser

### ISSUE THREAD

**Issue by Benjaming1312** [quasarframework/quasar#2170]
When Use select component and use filter.
Then key in some word is not in selector options and pressed keyboard down,
It will freeze the browser.
![select bug](https://user-images.githubusercontent.com/21982513/41390524-984975ae-6fc8-11e8-879f-4cd33e3d1c34.gif)

**Comment by pdanpdan** [comment]
Fixed by  #2159. It'll be in the next release
