### ISSUE TITLE
Weird interaction between QScrollArea and QModal

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar#2173]
### Software version

Quasar: 0.16.0
OS: Mac OS X
Browsers: Chrome

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/k4wyx95r/23/

### What did you get as the error?
I found a workaround for my use-case, but I thought I would report this weird interaction between QScrollArea and QModal as it took me a bit to track down what was happening... I understand that using QModal inside of QScrollArea may be unsupported, in which case just close this ticket and maybe add that note to the docs somewhere...

How to reproduce weird behavior:
1) Click on the JsFiddle above...
2) Click 'Add' button first... This is normal, clicking 'add' adds items to the scroll view...
3) Can now click 'Show' and close and add button still works...

4) Re-run/load the JsFiddle above...
5) Click 'Show' button first to show the QModal
6) Close the modal
7) Click 'Add' button -- items do not appear in list...

Removing the &lt;div&gt;header&lt;/div&gt; at the top of my jsfiddle scroll area or moving the QModal outside of the QScrollArea both solve this issue -- but it is very odd to me that clicking on the Modal before any items are added would cause different behavior to clicking on it at any time after there is at least one item...

**Comment by rstoenescu** [comment]
Hi,

It's actually related to a v-for followed by a QModal, which should be avoided, due to how Vue and QModal work. Will add to docs.
