### ISSUE TITLE
Some stylus variables are not available

### ISSUE THREAD

**Issue by camilosw** [quasarframework/quasar#2174]
### Software version

Quasar: 0.16.0
OS: OSX
Node: 8.9.1
NPM: 5.7.1
Browsers: Chrome

### What did you get as the error?

I'm trying to use some style variables from here https://quasar-framework.org/components/stylus-variables.html in app.styl. I found that some variables are not available when imported. This is my code:

```
@import '~variables'

.border-1
  border 1px solid $form-autofill

.border-2
  border 1px solid $item-separator-color
```

.border-1  works as expected, in the browser I got `border: 1px solid #ff9800;`

.border-2 doesn't works, this is the result in the browser: `border: 1px solid $item-separator-color;`

I tried with other variables with mixed results, some work fine others do not work.

### What were you expecting?

I want to use all the variables available here https://quasar-framework.org/components/stylus-variables.html when importing with `@import '~variables`

**Comment by rstoenescu** [comment]
Hi,

Only the core variables are available through the `variables` webpack alias, so not the theme specific one.

**Comment by camilosw** [comment]
I still see some issues here.

The documentation isn't clear about what variables are exposed. How I know $form-autofill is core and $item-separator-color is theme specific?

If there is any way to access the theme specific variables, that's not documented and I think it's useful to access that variables. If I create a new component, I want it to have the same look and feel of the available components reusing the same variables.

Thanks

**Comment by rstoenescu** [comment]
* Core variables: https://github.com/quasarframework/quasar/blob/dev/src/css/core.variables.styl
* Theme specific:
  * mat: https://github.com/quasarframework/quasar/blob/dev/src/css/variables.mat.styl
  * ios: https://github.com/quasarframework/quasar/blob/dev/src/css/variables.ios.styl

You might want to also `@import 'quasar-framework/src/css/variables.mat/ios.styl'`.
There are some theme specific variables that apply only to one of the two themes, so if you build for both themes you need to have this in mind.

**Comment by camilosw** [comment]
Your import failed but it guided me in the right direction, this worked for me `@import '~quasar-framework/src/css/variables.mat.styl'`

**Comment by rstoenescu** [comment]
The `mat/ios` was meant for you to pick one theme :)
