### ISSUE TITLE
[Request] QAutocomplete / autocomplete : allow min-characters to be zero

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#2175]
Currently the following code will open the select box when the first character is typed.

`<q-input v-model="value" float-label="Value">
            <q-autocomplete
              :min-characters="0"
              :static-data="{field: 'value', list: values}"
            />
          </q-input>`

which is the same behaviour as with :min-characters="1".

I propose that the value "0" results in the select box opening as soon as the field gets the input focus.

**Comment by pdanpdan** [comment]
Already done, will be in the next release
