### ISSUE TITLE
Luminosity function fails

### ISSUE THREAD

**Issue by Krlinhos** [quasarframework/quasar#2177]
Hello!

There is an error in Colors utils. The function luminosity has a guard: 
`if (typeof color !== 'string' || color.r === void 0) {
    throw new TypeError('Expected a string or a {r, g, b} object as color')
  }`

But when you try to use with a string like luminosity('#FF9900') it fails. I think should be && instead ||

Thanks! :)

**Comment by rstoenescu** [comment]
Thanks for reporting!
