### ISSUE TITLE
QIcon - __THEME__ is not defined (upgrade 0.15.15 to 0.16.0)

### ISSUE THREAD

**Issue by Manfred047** [quasarframework/quasar#2178]
After updating to last version I get this error after compiling.

[here](https://imageshack.com/a/img922/6136/GGFAbv.png)

I'm not using Quasar CLI, I'm using laravel mix 2.11 in my project.

This is my config:

```
import Quasar, * as All from 'quasar-framework/dist/quasar.mat.esm';
Vue.use(Quasar, {
    components: All,
    directives: All,
    plugins: All,
    animations: All
});
```

**Comment by rstoenescu** [comment]
Hi,

1. There is no mention of `__THEME__` in quasar-framework/dist/quasar.mat.esm
2. There is no "animations" prop to be supplied as you did
3. Are you importing from quasar-framework/src instead of the file mentioned above? The latter is the right way.
