### ISSUE TITLE
[ios] App is not fixed in webview

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#218]
The default structure of a Quasar application is getting loose in the webview. How do I make the basic structure of the application hang and not allow what happens in the illustration below?

This only occurs in the iOS version.

iOS simulate (not fixed): https://appetize.io/app/4e57ypqffca2k3cpfmzr22q00m?device=iphone5s&scale=75&orientation=portrait&osVersion=9.3

Android simulate (ok, fixed): https://appetize.io/app/jhkxqdje3zxeq2jczd0trfvkz8?device=nexus5&scale=75&orientation=portrait&osVersion=7.0

Animation illustrating the non-fixed structure in iOS:

![painel_solto](https://cloud.githubusercontent.com/assets/14337850/20501135/b02909ba-b01f-11e6-8131-e2eb644b594a.gif)

Thank you for your help.

**Comment by xereda** [comment]
I solved this by adding the following property in the Cordova project's config.xml:

<Preference name = "DisallowOverscroll" value = "true" />

Look at this simulation:

https://appetize.io/app/c60un12gvxkn1c6jcp9nx82n5g?device=iphone5s&scale=75&orientation=portrait&osVersion=9.3

**Comment by rstoenescu** [comment]
I was absolutely sure the rubber band effect can be disabled through a setting or something, just didn't have time to search for it. Closing issue and opening one for documentation. Thanks!
