### ISSUE TITLE
Chrome warnings showing up in Cypress

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#2184]
I am seeing several WARNING regarding inputs in cypress, this kind of error never shows up in a normal chrome browser (I double checked to make sure). 

### Software version

```
  NPM                           5.6.0
  quasar-cli                    0.16.4
  quasar-framework              0.16.0
```
Any other software related to your bug:
Cypress 3.0.1 (Chrome 67)
Vue Devtools (Electron)

### What did you get as the error?
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event  handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 - quasar.mat.esm.js?e083:4772 

[DOM] Input elements should have autocomplete attributes (suggested: autocomplete='email', confirm at https://goo.gl/6KgkJg) [edit: this was not technically part of Quasar]

(Attached the "full stack trace" from chrome devtools)
[localhost-1529277061499.log](https://github.com/quasarframework/quasar/files/2109505/localhost-1529277061499.log)

### What were you expecting?
Not to see these errors, because I never see them in a normal browser.

### What steps did you take, to get the error?
Running an e2e test with a properly constructed quasar .vue SFC that does not display these warnings in the same version of a non-rigged browser.

**Comment by adamkpurdy** [comment]
@nothingismagick In regards to the DOM input elements that you're pointing out. I can confirm those can be cleared up when the autocomplete prop on inputs are supplied with values from here: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-name

**Comment by nothingismagick** [comment]
The reference in our code is in Touchpan.bind regading touchstart and touchmove:

```js
    el.addEventListener('touchstart', ctx.start, evtOpts);
    el.addEventListener('touchmove', ctx.move, evtOpts);
```

The troubling thing is that the adding of these event listeners are happening twice...

This page has the exact reference material:
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

```
  addEventListener(document, "touchstart", function(e) {
    console.log(e.defaultPrevented);  // will be false
    e.preventDefault();   // does nothing since the listener is passive
    console.log(e.defaultPrevented);  // still false
  }, Modernizr.passiveeventlisteners ? {passive: true} : false);
```

**Comment by nothingismagick** [comment]
This was an error in the usage of a custom directive.
