### ISSUE TITLE
[Enhancement] QContextMenu: Add an @activated handler

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#2185]
Here's the situation I just ran into. We have the QDataTable, but the rows are being added at the top (to see newest information as it becomes available). I wanted to add a context-menu handler to the row. This works, but if new data comes in, then because of the reactive properties, the context menu changes (because it's based on the data from that row). With an `@activated="someFunc(props.row)" handler, I'd be able to make a copy of the data, and then the q-context-menu UI would be based off of the copied data.
Just a suggestion, but I think it could really help. Possibly could even use a @deactivated handler, for clean up,  as well.

**Comment by hawkeye64** [comment]
https://jsfiddle.net/Hawkeye64/px5zL93m/33/

**Comment by hawkeye64** [comment]
@rstoenescu Did you take a peek at the fiddle?

**Comment by hawkeye64** [comment]
anything?

**Comment by rstoenescu** [comment]
Hi,

Sorry for the late reply. Preparing the SSR release, so busy to the extreme currently. Would accept a PR if you think something should be added.

-Razvan
