### ISSUE TITLE
lazy load import problem on production build

### ISSUE THREAD

**Issue by muratak18** [quasarframework/quasar#2186]
### Software version
Operating System        	Darwin(17.6.0) - darwin/x64
NodeJs                  	10.3.0

Global packages
  NPM                   	6.1.0
  yarn                  	1.7.0
  quasar-cli            	0.16.4
  vue-cli               	3.0.0-rc.3
  cordova               	8.0.0

Important local packages
  quasar-cli            	0.16.4
  quasar-framework      	0.16.0
  quasar-extras         	2.0.2
  vue                   	2.5.16
  vue-router            	3.0.1	
  vuex                  	3.0.1	
  electron              	Not installed
  electron-packager     	Not installed
  electron-builder      	Not installed
  babel/core           	7.0.0-beta.49
  webpack               	4.9.1
  webpack-dev-server    	3.1.4
  workbox-webpack-plugin	3.2.0

### What did you get as the error?
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at t (app.4e8dcdae.js:1)
    at a.lang (vendor.7198f4d2.js:38)
    at sn.Kw5r.sn.run (vendor.7198f4d2.js:33)
    at en (vendor.7198f4d2.js:33)
    at Array.<anonymous> (vendor.7198f4d2.js:33)
    at MessagePort.rt (vendor.7198f4d2.js:33)

### What were you expecting?
I was expecting to load language file dynamically. It works for dev but not prod build.
There is also a similar issue for lazy load components mentioned on the forum 
[same issue](https://forum.quasar-framework.org/topic/2358/quasar-v16-build-n-e-is-not-a-function)

### What steps did you take, to get the error?
[Dynamically Changing Language](https://quasar-framework.org/components/internationalization.html#Dynamically-Changing-Language)
When I use the code below I get the error 
`watch: {
    lang (lang) {
      // dynamic import, so loading on demand only
      import(`quasar-framework/i18n/${lang}`).then(lang => {
        this.$q.i18n.set(lang.default)
      })
    }
  },`

So what should I do?
Thank you in advance.

**Comment by rstoenescu** [comment]
Hi,

Quasar i18n is bulletproof. It must be something in your app, but can't tell only by the information that you supplied. Can you contact me on Discord pls? I'd like to use Teamviewer to see what's going on. Thank you.
