### ISSUE TITLE
[ios] App does not open on Iphone 4s

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#219]
App does not open on Iphone 4s

I have not tested on a real device yet, but I believe there are issues with opening the application on the Iphone 4s model. The simulation I did was with the website appetize.io.

Note:

https://appetize.io/app/ftfjahc9nfjgyu00jv04u7ed7w?device=iphone4s&scale=75&orientation=portrait&osVersion=9.3

**Comment by rstoenescu** [comment]
I believe the link is not working.

**Comment by xereda** [comment]
https://appetize.io/app/ftfjahc9nfjgyu00jv04u7ed7w?device=iphone4s&scale=75&orientation=portrait&osVersion=9.3

**Comment by rstoenescu** [comment]
Ok, researched a bit. Seems like iPhone 4S has 5% market share. So currently no plans to support it.

**Comment by xereda** [comment]
But what do you think should be the cause of the problem? Could it be something with Cordova?

**Comment by rstoenescu** [comment]
Sorry but don't have time to investigate it. Maybe in the following weeks, but I doubt I'll have time to spare. Unfortunately I got too many things to do (just look at the tickets left)... Need some help on this one.

**Comment by xereda** [comment]
It's all right. We see this later.

Thank you for now.
