### ISSUE TITLE
[Proposal] Use Material Design breakpoints as default

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2190]
Hi!

I'd like to have a discussion about the pros and cons of using Material design's breakpoint standards over Quasar's current ones.

These are quasar's current defaults:

Token | Max window width | Description / When it applies
-- | -- | --
xs | 576px | Extra small sized window
sm | 768px | Small sized window
md | 992px | Medium-sized window
lg | 1200px | Large sized window
xl | Infinite | Extra large sized window

[These are the defaults for material design:](https://material.io/design/layout/responsive-layout-grid.html#breakpoints)

Token | Max window width | Description / When it applies
-- | -- | --
xs | 599px | Extra small sized window
sm | 1023px | Small sized window
md | 1439px | Medium-sized window
lg | 1919px | Large sized window
xl | Infinite | Extra large sized window

There is a pretty large discrepancy between the two, and I'm not sure many people would consider 1200px an "extra large" screen. I'm curious where the current defaults are coming from, or the reasoning behind them. 

I know Quasar follows material design guidelines on a lot of things, but it's odd that it seems to follow [Bootstrap's breakpoints.](https://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints)

[Bulma has another cool idea](https://bulma.io/documentation/overview/responsiveness/), but to me it's a little too many breakpoints.

Also, **I know how extraordinarily easy it is to change the default breakpoint size** but I still think it's a discussion worth having.

**Comment by rstoenescu** [comment]
Done for v1.0.
