### ISSUE TITLE
Datetime Picker doesn't adapt to available space

### ISSUE THREAD

**Issue by camilosw** [quasarframework/quasar#2191]
### Software version

Quasar: 0.16.0
OS: OSX
Node: 8.9.1
NPM: 5.7.1
Browsers: Chrome

### What did you get as the error?

Datetime Picker has fixed width for different break points and doesn't adapt to available space. In this example I put a row with two columns. QChatMessage adapt to their 50% column width, but QDatetimePicker not.

````html
<div class="row">

  <div class="col-6">
    <q-datetime-picker type="date"/>
  </div>

  <div class="col-6">
      <q-chat-message
        v-for="(msg, index) in messages"
        :key="`reg-${index}`"
        :label="msg.label"
        :sent="msg.sent"
        :text="msg.text"
        :stamp="msg.stamp"
      />
  </div>

</div>

````

![image](https://user-images.githubusercontent.com/1142037/41671932-2b8e5fd2-747e-11e8-89a8-bee067da6144.png)

**Comment by pdanpdan** [comment]
Hi. This should be fixed by https://github.com/quasarframework/quasar/pull/2523.

Will be available on the next version.

**Comment by rstoenescu** [comment]
Done for v1.0.
