### ISSUE TITLE
Blank margin appears to the right of page content below toolbar

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#2194]
I observed it in anothe rproject as well:

![image](https://user-images.githubusercontent.com/33280703/41709490-924da0e6-7543-11e8-87fe-e07e6aaad4e6.png)

Chrome shows no content to the right of the table

**Comment by rstoenescu** [comment]
The Quasar Layout is bulletproof.

Please reopen with some details so I can help. Fill in the github issue template, copy-paste the template that you're using or better yet make a jsfiddle... Basically your initial description is not something I can work with.
