### ISSUE TITLE
QScrollArea unable to select text inside

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2197]
Hello!

Here is a fiddle:
https://jsfiddle.net/waugrryy/3396/

Expected: content inside scroll area should be selectable.

Thanks!

**Comment by slowaways** [comment]
This is because the class "q-touch" is added in QSrollArea when imported the directive TouchPan:
https://github.com/quasarframework/quasar/blob/472983e7d1419f17dc1986ada9076275ce393c11/src/directives/touch-pan.js#L167
