### ISSUE TITLE
footer didn't show properly after wrap q-page with q-pull-refresh

### ISSUE THREAD

**Issue by johncloud200** [quasarframework/quasar#2198]
https://jsfiddle.net/ukmqa1vn/8/

**Comment by pdanpdan** [comment]
https://jsfiddle.net/ukmqa1vn/23/

**Comment by johncloud200** [comment]
Hi Thanks,

I see the difference is loop edited from **100** to only **2** and change **lfr** to **lFr** but still ugly

![quasar v0 15 - material theme - jsfiddle](https://user-images.githubusercontent.com/29952776/41785955-592a27c2-766e-11e8-8732-74fc87654584.jpg)

**Comment by pdanpdan** [comment]
For the moment you need to use fixed header and footer in order to work, and there's a padding missing on the bottom.
This is fixed in the upcoming version.

**Comment by johncloud200** [comment]
Ok thanks buddy
