### ISSUE TITLE
minor: moving root app dir polutes .quasar/artefacts.json

### ISSUE THREAD

**Issue by oger000** [quasarframework/quasar#2204]
Operating System        Linux(4.4.0-128-generic) - linux/x64
NodeJs                  10.4.1

Global packages.........
  NPM                   6.1.0
  quasar-cli            0.16.4
  vue-cli               2.9.6

Important local packages
  quasar-cli            0.16.4
  quasar-framework      0.16.0
  quasar-extras         2.0.2
  vue                   2.5.16
  @babel/core           7.0.0-beta.49
  webpack               4.9.1
  webpack-dev-server    3.1.4
  workbox-webpack-plugin3.2.0

### What did you get as the error?
When moving the app directory to another place the "folder" array in ".quasar/artefacts.json" file was not cleaned up, but only the new folder added. So some entries point to not-existing directories.

### What were you expecting?
Only the last valid directory should be present. At least non-existing paths should be removed. 
Maybe relative paths would help?
If this inconsistency does not call for trouble in further development its nothing to me.

### What steps did you take, to get the error?
Do a fresh quasar install using starter kit as described in "getting started"
do a quasar build
move the project root to another location
do another quasar build

**Comment by rstoenescu** [comment]
Hi,

1. When you build something, it cleans the destination before building, so no worries there for you.
2. Full path is used in artifacts before some developers set the build folder outside of the project folder. The artifacts are used for "quasar clean" command only.
