### ISSUE TITLE
[Feature Request] Download component

### ISSUE THREAD

**Issue by marcelo-rebello** [quasarframework/quasar#2208]
I would like that quasar includes a "Download" component, analogous to the upload one.
Is a quite common use case when you have a button/link/table row/icon that when a user clicks it makes a server request (or call a Vuex action that make it) and then the file is automatically saved on the filesystem.
Usually using some code like:
```javascript
async download (url, data, options) { 
    const response = await this.$http.get(url, data, {responseType: 'blob'}) // GET, POST, PUT... 
    const filename = response.headers['x-suggested-filename']
    const link = document.createElement('a')
    link.href = window.URL.createObjectURL(new Blob([response.data]))
    link.setAttribute('download', filename)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
}
```
I am awere that this implementations can have some issues with mobile devices, and encapsulates all situations is another reason to create this component.
Quasar is an awesome framework with lots of amazing components! Hope this fits in the framework philosophy.

Regards
Marcelo

**Comment by pdanpdan** [comment]
There is already https://www.npmjs.com/package/file-saver that covers a lot of edge cases. Just import and use it.
