### ISSUE TITLE
Disabled on q-tab does not work.

### ISSUE THREAD

**Issue by mkhanal** [quasarframework/quasar#2209]
### Software version

Quasar:
OS: MacOS high sierra - 10.13.5 
Node: v8.11.1
NPM: 6.1.0
Browsers: firefox/chrome
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/mkhanal/nogk1at4/

### What did you get as the error?
Usage of disabled in `<q-tabs>` and `<q-tab>`. A disabled `<q-tab>` can still be selected. It shows the disabled mouse pointer, but is clickable and on click selects the disabled tab.

### What were you expecting?
Expected behaviour is when a `<q-tab>` is disabled, click or a tap action on it should have no effect and it should not be selectable by the user.

### What steps did you take, to get the error?
please check the fiddle.

**Comment by rstoenescu** [comment]
It's "disable" not "disabled".

**Comment by mkhanal** [comment]
Oh thanks...that was a bad one on my part.
