### ISSUE TITLE
Proposal: High top bar. 

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#221]
Hi,
It is really popular across material design.
Please take a look: https://material.uplabs.com/posts/company-dashboard-material

**Comment by smolinari** [comment]
Maybe a stupid question, but what should I be looking for?

Scott

**Comment by rstoenescu** [comment]
I'm confused too. If you are talking about the top bar, that's something that can be done easily with current Quasar. So no need to write a specific component for this.

**Comment by rstoenescu** [comment]
Hi, Please offer some some details on what you mean. Thanks!

**Comment by rstoenescu** [comment]
Please reopen with explanations.
