### ISSUE TITLE
QSelect throws error on sequentially clicking between two QSelects

### ISSUE THREAD

**Issue by mrKoujou** [quasarframework/quasar#2211]
QSelect throws error on sequentially clicking between two QSelects or on sequentially clicking on three QSelects sequentially.

### Software version
Quasar: 0.16.0
Browsers: Chrome, Firefox, Opera

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/zs70dur5/

### What did you get as the error?
QSelect not opened on click after reproduction steps.
In Chrome and Opera there is error in console (in FF behavior is the same, but no error in console):

quasar.mat.umd.min.js:6 Uncaught (in promise) null
e.showPromiseReject @ quasar.mat.umd.min.js:6
hide @ quasar.mat.umd.min.js:6
hide @ quasar.mat.umd.min.js:6
(anonymous) @ quasar.mat.umd.min.js:6
setTimeout (async)
__onBlur @ quasar.mat.umd.min.js:6
blur @ quasar.mat.umd.min.js:6
i @ vue.min.js:6
Rr.t._withTask.o._withTask @ vue.min.js:6
__onClose @ quasar.mat.umd.min.js:6
hide @ quasar.mat.umd.min.js:6
i @ vue.min.js:6
cn.$emit @ vue.min.js:6
e.hidePromiseResolve @ quasar.mat.umd.min.js:6
__hide @ quasar.mat.umd.min.js:6
hide @ quasar.mat.umd.min.js:6
__bodyHide @ quasar.mat.umd.min.js:6

### What were you expecting?
QSelect to lose focus on clicking other QSelect and QSelect to be opened on any click.

### What steps did you take, to get the error?
We have two QSelects on a page with focus and blur handlers (just to see what happens in console).
1. Click "First" QSelect (it is opened, events in console: focus 1)
2. Click "Second" QSelect (it is opened, but "First" is not lost focus, events in console: focus 2, blur 1, focus 1, blur 2, focus 2, blur 1)
3. Click "First" QSelect ("Second" lost focus, "First" have focus, but "First" not opened, events in console: blur 1, focus 1, Uncaught (in promise) null, blur 2)

Strange thing is when in adaptive mode in Chrome problem is not reproduced (also not reproduced in FF with sensor input enabled).

**Comment by rstoenescu** [comment]
Hi,

It's already fixed in the next Quasar version.
