### ISSUE TITLE
Documentation: q-uploader additional fields. Format is not clear. (may be a bug in fact)

### ISSUE THREAD

**Issue by geoidesic** [quasarframework/quasar#2212]
https://quasar-framework.org/components/uploader.html#Vue-Properties

Says: "Additional fields to send along the upload request. Useful for authentication and so on. Array of Objects containing name and value props."

This isn't really clear to a newbie. Not even to me and I've been using Quasar for more than a year. An example showing the declarative formatting of name / value props would help.

Also having searched through the quasar code there's absolutely no reference to 'additional-fields', so I'm not sure where this is implemented and thus cannot get my answer from the source. Also couldn't find anything in the Vue docs. So it's a grand mystery.

I should add that what I'm trying to do is solve an error where the upload is failing because I haven't sent an authentication token along with the POST request. From the docs it sounds like this would be the place for it but it's not clear how.

I tried it like this:

```
<q-uploader
            ref="uploader"
            :url="url"
            @add="fileDump"
            multiple
            auto-expand
            :addFileFactory="addFileFactory"
            :additional-fields="additionalFields"
          ></q-uploader>
```
```
data() {
      return {
        // path: []
        url: 'http://192.168.33.10:8080/api/upload_item_attachment/1',
        files: [],
        additionalFields: [{
        token: this.token}]
      }
  },
```
... but I can see that there's nothing being added to the request headers. So actually I think this may be a bug.

**Comment by pdanpdan** [comment]
As it's specified in the documentation each object should have name and value properties.
So `[{name: 'name', value: 'value'}]`

**Comment by geoidesic** [comment]
Ok so you mean like this?:

```
<q-uploader
            ref="uploader"
            :url="url"
            @add="fileDump"
            multiple
            auto-expand
            :addFileFactory="addFileFactory"
            :additional-fields="[{name: 'name', value: 'value'}]"
          ></q-uploader>
```

**Comment by pdanpdan** [comment]
`<q-uploader
            ref="uploader"
            :url="url"
            @add="fileDump"
            multiple
            auto-expand
            :add-file-factory="addFileFactory"
            :additional-fields="[{name: 'name', value: 'value'}]"
          />`

**Comment by geoidesic** [comment]
Great tx. I think that example would be super handy in the docs mentioned. It's easy when you know how but the point of the docs is that they are for people who don't know how.

**Comment by namanchauhan8998** [comment]
data(){
      return{
        **image:''**
      }
    },
    props:{
      AlbumId: '',

    },
    methods:{
      Upload:function () {
        console.log("my image  "+this.image[0])
        **let formData=new FormData();
        formData.append('image',this.image[0]);**

        Axios
          .post(this.$store.state.requestUrl+'/photos/upload?albumId='+this.AlbumId,formData,{headers:{Authorization:this.$store.state.token}},
          )
          .then(res=>{
            console.log(res.data)
            this.$q.notify({message:'Image Uploaded',type:'positive'})
          })
          .catch(err=>{
            console.log(err)
            this.$q.notify({message:'Error While Uploading the image',type:'negative'+err})
          })
      }
    }
  }


//So I want this to be done by q-Uploader but I am unable to send files using formData
