### ISSUE TITLE
Delete QuasarDatetimeRange from the doc or precise that it has been drop since 0.15

### ISSUE THREAD

**Issue by foufrix** [quasarframework/quasar#2214]
Hi,

Just for futur user maybe just precise that the feature has been drop on the doc. Just had the problem earlier and found the info here : https://forum.quasar-framework.org/topic/1833/quasar-v0-15-is-out

Not as straitforward as in the docs :D 

Anyway thanks for all the work you put in quasar !!

**Comment by rstoenescu** [comment]
Hi,

1. DatetimeRange does not exists in docs....
2. When upgrading, devs should read the upgrade guide (your link for example), where it is explicitly said that QDatetimeRange has been dropped..

Am I missing something?
