### ISSUE TITLE
[Bug] QSelect / q-select : clearable button visible when the v-model variable holds a value that is not in the options

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#2218]
```
<q-select
                v-model="x"
                radio
                filter
                autofocus-filter
                :options="xarray"
                clearable
              />


```
when x = 'A' and xarray = [ 'B', 'C']
then the clearable button is visible although no option is selected.

**Comment by pdanpdan** [comment]
Even if the value is not among the available options the field has a value and it can be reset to the clearValue (default [])

**Comment by aprixon01112017** [comment]
the value field in this case is empty:

https://jsfiddle.net/a6wr2409/10/

**Comment by pdanpdan** [comment]
No, the value is 'A' - it cannot be displayed as it's not in the list of options, but it's set

**Comment by rstoenescu** [comment]
@aprixon01112017 In your case, the v-model is not undefined or null. It is something ('A'). QSelect is already bloated, so for perf reasons, will not add an extra check and will ask you to correctly initialise the "x" model.
