### ISSUE TITLE
[Enhancement] QChip: handler for {label, value} when using with QAutocomplete

### ISSUE THREAD

**Issue by marekkaczkowski** [quasarframework/quasar#2219]
Hey,

TLDR; Option for chips input to accept autocomplete values.

**PROBLEM**
I'm struggling with QChip+QAutocomplete data handling
```html
<q-chips-input
  v-if="field.chips"
  :color="color"
  placeholder="QChip with QAutocomplete"
  :value="getChip(field.id)"
  @input="setFilter(field.id, $event)"
>
  <q-autocomplete
    :filter="fuzzyFilter"
    :selected="getChip(field.id)"
    :static-data="{ field: 'label', list: chips(field.id) }"
    @selected="setChip(field.id, $event)"
  />
</q-chips-input>
```
so when I select suggestion from autocomplete, `{label, value}` is pushed to `value: []` for autocomplete.
OK, looks cool... except chip value - which is `{label, value}` instead of `value`.

**SOLUTION**
As `:value` expects array of strings(chips),
`:autocomplete-value` or `:display-value` should accept array of objects `{label, value}`.

**Comment by pdanpdan** [comment]
Please make a fiddle with what you want to obtain.

**Comment by rstoenescu** [comment]
Please reopen with a jsfiddle showing your usecase and what goes wrong.
