### ISSUE TITLE
"Stepper" translation

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#222]
"Stepper" translation

The labels for the "continue" and "back" buttons can not be changed. This should be treated normally by the "stepper", do not you think !?

**Comment by rstoenescu** [comment]
Agreed.

**Comment by xereda** [comment]
I believe it can be two optional "props" in the main component.

**Comment by rstoenescu** [comment]
Yep. This is how it's going to be "fixed".

**Comment by xereda** [comment]
I'm sorry that I can not, at the moment, change the sources and release suggestions with "PR". I am in the middle of a project and unfortunately I can not help at this level. I hope you understand.


I see it's a lot of work for one person. I hope that the community is helping you.

**Comment by xereda** [comment]
I just deal with the "select" component. It also needs support for translation.

**Comment by rstoenescu** [comment]
Yes, and this is part of Internationalization #100

**Comment by rstoenescu** [comment]
`<q-stepper>` will have (in next Quasar version) 3 new props: `back-label`, `next-label`, `finish-label`
