### ISSUE TITLE
Error when Bulding Production Electron App with MySQL or MySQL2 Lib

### ISSUE THREAD

**Issue by lsascha** [quasarframework/quasar#2220]
I am having big issues using MySQL or MySQL2 Libraries for NodeJS
https://www.npmjs.com/package/mysql or https://www.npmjs.com/package/mysql2

When using `mysql` the application gets build, but when starting the application and trying to connect to a mysql database, i get the error `PROTOCOL_INCORRECT_PACKET_SEQUENCE`. Starting the application in Dev mode works flawlessly.

When using `mysql2` it does not even compile in production mode. I get the error
`ERROR in js/vendor.ce2c0702.js from UglifyJs
undefined`
Again, using dev mode works flawless.

I tried many different things, disabling uglifyjs etc, but nothing helped so far.

My Project is available here:
https://git.software-sl.de/root/dsgvo-cleaner/tree/master

_quasar info:_
Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.11.3
  NPM                           6.1.0
  yarn                          1.7.0
  quasar-cli                    0.16.4
  vue-cli                       2.8.2
  cordova                       Not installed
...
  quasar-framework              0.16.0
  electron                      2.0.0
  electron-packager             12.1.0
  electron-builder              20.17.1
  @babel/core                   7.0.0-beta.49
  webpack                       4.9.1

**Comment by rstoenescu** [comment]
Please open to the appropriate repo: https://github.com/quasarframework/quasar-cli
Thanks.
