### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by Jayzhanscar** [quasarframework/quasar#2222]
Please add a feature

timer-range-selset

thank you very much

love you

**Comment by pdanpdan** [comment]
If you need a new feature can you please at least describe the desired feature?

**Comment by Jayzhanscar** [comment]
Thank you very much for being able to see this suggestion. Okay, I want a component that can slide filter the time. For example, I need to select the range of a certain time period to combine the slider with the time selector，Thanks again！

**Comment by smolinari** [comment]
With the components available (range, datetime input or picker), couldn't you do this yourself?

Scott

**Comment by rstoenescu** [comment]
Hi,

Like @smolinari correctly suggested, you can do it yourself. This is too specific for your app so won't add it to the framework.
