### ISSUE TITLE
[Feature Request]: Multi level menus

### ISSUE THREAD

**Issue by playersun** [quasarframework/quasar#2223]
Hello
As more components or pages become available, single level menus are too high, making operation inconvenient.  Is there a plan to develop a component Multi level menus like AdminLTE？
https://adminlte.io/themes/AdminLTE/index2.html
![tim 20180702173144](https://user-images.githubusercontent.com/6895430/42156506-d3801750-7e1d-11e8-9144-ff2f2cab4019.png)

**Comment by pdanpdan** [comment]
Just use collapsible in your menu and you'll get exactly that.
Can you provide a fiddle where you tried to do it and you had problems?

**Comment by rstoenescu** [comment]
https://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/collapsible
