### ISSUE TITLE
QDatetimePicker wrong date selected when using UTC as a model

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2229]
Hello!

This is a pretty common scenario when you would use UTC date string as a model. In a timezone that I've been testing it shows the day before.

https://jsfiddle.net/waugrryy/3534/

![screen_shot_2018-06-29_at_02 31 47](https://user-images.githubusercontent.com/3635352/42306208-d9fa1534-8036-11e8-995c-54e1195832d3.png)

![screen_shot_2018-06-29_at_02 31 53](https://user-images.githubusercontent.com/3635352/42306213-df730304-8036-11e8-8d31-73bdac32681c.png)

Thanks!

**Comment by pdanpdan** [comment]
Use date as string: format-model="string"

**Comment by jean-moldovan** [comment]
Sorry, it doesn't help. Previous day gets selected on init.

**Comment by jean-moldovan** [comment]
I'd expect datepicker not to add any offset when using UTC date as a model.

**Comment by rstoenescu** [comment]
Internally, Quasar uses the Javascript Date() Object. Long story short, on the part where you refer to year month day --> use "YYYY/MM/DD" --> instead of "YYYY-MM-DD". http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html

**Comment by jean-moldovan** [comment]
@rstoenescu Can we configure Datepicker not to add time offset when working with dates only? I want this to be UTC always.

UTC input > Datepicker > UTC output

**Comment by jean-moldovan** [comment]
Well, I guess I can strip that manually.

**Comment by jean-moldovan** [comment]
![screen shot 2018-07-05 at 05 28 11](https://user-images.githubusercontent.com/3635352/42323219-1074bb6a-8068-11e8-94d5-c3d28ccce2b0.png)

**Comment by pdanpdan** [comment]
And with this one: https://jsfiddle.net/94c0fos7/7/

**Comment by jean-moldovan** [comment]
This one is good across different timezones. Thanks!
No need to support anything like that out of the box in your opinion @pdanpdan ?

**Comment by pdanpdan** [comment]
@rstoenescu, @jean-moldovan 
If we want to implement it out of the box I would suggest this:
- when `type="date"`
  - the default `format-model` will be `string`
  - the default `format` will be `YYYY/MM/DD`

The processing would only kick in when:
- `type="date"`
- `format-model="string"`
- `typeof value === 'string' || [null, undefined].indexOf(value) > -1`
- the emitted value will be formatted using `format`
