### ISSUE TITLE
Minor: Add activeClass prop to QBtnToggle

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2238]
Hello!

This is super useful in a scenario where you would need to add custom styles to the button selected (border-bottom or whatever).

Currently only color and text-color can be customized.

Thanks.

**Comment by nkoik** [comment]
Check `rstoenescu` answer #2310

**Comment by rstoenescu** [comment]
```<q-btn v-model="flag" :class="flag ? 'some-class' : ''" .../>```
