### ISSUE TITLE
[REQUEST] Key press should select item in QSelect

### ISSUE THREAD

**Issue by kerbo** [quasarframework/quasar#2239]
Enable key press selection for QSelect field.

I should be able to tab into a QSelect field and select an item using a key press. Basically duplicate the behavior of the HTML Select element.

**Comment by rstoenescu** [comment]
Already in v0.17. Check forum @ announcements. You can help beta test it. Thanks.

**Comment by kerbo** [comment]
I finally tried key press selection for QSelect in 0.17 and it doesn't work. In fact, I scanned the release notes and I can't find anything saying the feature was added.

**Comment by rstoenescu** [comment]
@kerbo works just fine....

**Comment by kerbo** [comment]
I've tried it with the 17.9 showcase. If you set focus to one of the QSelects, pressing "G" should select "Google". It doesn't.  If I select "Google" with the mouse, pressing "F" should select "Facebook".

Once a Select is expanded I can move up and down the list with the arrow keys, but pressing a letter of the name doesn't do anything.

**Comment by rstoenescu** [comment]
Use a filter for that. By keypress we refer to the ENTER key.
