### ISSUE TITLE
QInfiniteScroll concurrency issue

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2241]
Hello!

Here is an interesting case when refreshing inf scroll list:
1) Initial load is fired
2) Click 'Foo' filter and then click back to 'Bar' right away
3) List is refreshed only one time, second filter is being ignored

https://jsfiddle.net/waugrryy/3845/

Expected:
1) Click 'Foo', load is fired
2) While 'Foo' is loading, click 'Bar'
3) Once 'Foo' is loaded, list is refreshed once again, 'Bar' applied correctly

**Comment by rstoenescu** [comment]
Hi, Got it figured out. Fix will be available in v0.17.

Your watcher should be like this:
```js
watch: {
  filter () {
    // we stop Infinite Scroll
    this.$refs.inf.stop()
    // we reset it, preparing to start again
    this.$refs.inf.reset()
    // we abort our current fetch, otherwise it gets executed anyway
    clearTimeout(this.timer)
    // we reset the items
    this.items = []
    // let Vue update the DOM, so that when
    // we resume Infinite Scroll it will detect that it can load more content
    this.$nextTick(() => {
       // we finally resume Infinite Scroll
       this.$refs.inf.resume()
    })
  }
}
```
And in `load()` we have:
```js
this.timer = setTimeout(() => {
```

**Comment by jean-moldovan** [comment]
For axios users: https://github.com/axios/axios#cancellation.
This is how you would cancel request.

Thanks again!

**Comment by StasD** [comment]
https://github.com/quasarframework/quasar/issues/2241#issuecomment-406450986
This algorithm should be in the official documentation...
