### ISSUE TITLE
[REQUEST] Adjustable Column Widths for QTables

### ISSUE THREAD

**Issue by kerbo** [quasarframework/quasar#2248]
There should be an option specify column widths in a QTable. This means there should also be an option to specify the table width.

There are many use cases where tables don't have to be flex based.

**Comment by 1083970440** [comment]
OK,I will try it!

**Comment by 1083970440** [comment]
So can you tell me what is the flex based？

**Comment by kerbo** [comment]
The entire table seems to be. The table width will stretch to fit the page and column widths adjust to a width that seems to be even spacing. This is probably what you want on a mobile device but on a browser with more screen area, you want the ability to better format the appearance of the table.

For example, if I have a column with a number and column with a long text description, there is no way to make the number column narrow and the text column wide.

**Comment by pdanpdan** [comment]
Please provide a fiddle/codepen

**Comment by kerbo** [comment]
ok, here is the link:

https://jsfiddle.net/kerbo/vyk1xL2u/

The table has two columns: ID (number) and Description.

When displaying the first time, the ID column takes up about 40% of the table width. Why 40%? What I want (since ID is a number) is about 15% for the ID and the rest for the description.

There is an "Add New Row" button. This button adds a row to the table and the description column has more text than the other rows. What happens is:

1. The columns resize. I DON'T want this. Columns should stay the same width.

2. The new column widths are still not right. The ID column is still too wide and the text in the description column truncates. Looks stupid.

Generally table columns widths should be configurable to a fixed width and remain consistent. 

For text that can't fit in a column, there should be two options: truncate the text and add an "..." at the end to indicate more text or wrap the text (which increases the row height).

I think most people want tables to act like tables in Excel. Column widths are fixed however the user can drag the column separator to increase/decrease the width.

**Comment by pdanpdan** [comment]
Is there a problem with the normal approach?
https://jsfiddle.net/qukw45gc/12/

**Comment by kerbo** [comment]
Yes, the problem is I have to apply CSS styling to do something as simple as setting the column widths. External CSS shouldn't be needed to change the behavior of a component. Appearance maybe, but not behavior. This is the reason we have components and component frameworks. 

BTW, I appreciate the tip on how to set the column widths in CSS.

**Comment by pdanpdan** [comment]
Column width is not behavior, is presentation :) - it belongs in CSS.

**Comment by kerbo** [comment]
I think you agree the ability so set column widths is useful for a table. I'm hoping this feature becomes part of the component rather than the requiring the developer to understand how to do it via CSS.

**Comment by kerbo** [comment]
I don't have the depth of knowledge with this component to say. Maybe just internally implement the CSS you posted in Fiddle. You would add a width property to the columns definition to set the width. With regard to spanned columns, I'm not asking for that. I'm sure that would be useful but for now, column widths would help greatly.

**Comment by rstoenescu** [comment]
Hi,

1. You could define the header and apply a style with your width there (as width needs to be specified on thead > th in order to be taken into consideration).
2. Pushed a commit to add "classes" and "style" to the column definition. Will be available in 0.17.9.

**Comment by kerbo** [comment]
I'm confused. This issue was closed because a style property was added to the column definition and the new property would allow specifying a column width.

Do I have to do something else to make column widths work?

**Comment by smolinari** [comment]
This is what the docs for the two new props says.
```
....
> // v0.17.9+; if using scoped slots, apply this yourself instead

    style: 'width: 500px',
    classes: 'my-special-class'
....
```
And using scoped slots, I believe, means using the item slot [in grid mode](https://quasar-framework.org/components/datatable.html#Grid-Mode). I could be wrong though.

Scott

**Comment by kerbo** [comment]
If so, then the Issue should not have been closed. I think the QTable should provide a configuration option where the developer can specify the column widths as the current default does not do a very good job. 

This is a commonly asked for feature and will be the source of many questions going forward especially now that there is a mention of "width" in the column docs.

**Comment by kerbo** [comment]
I appreciate the help. My css skills are basic which is why I'm using Quasar. I've built quite of lot of functionality without needing _one_ line of css. QTable has been the only exception.

And as I said, I think column widths should be part of the component like many of the other configuration options for QTable. A simple example is the "align" property for the column. Why have the property? Just make the user write css. I think you will agree its much simpler for the developer to set the align property rather deal with css. It should work the same for column widths. 

I'm pretty sure anyone using QTables for web apps will have an issue with column widths. Why make it harder than it needs to be?

But hey, I've got the css stuff to work so I can move on. But again, this issue won't go away. Other developers will have the same questions. In fact they already have. Its in the forum. I know because I looked there before creating this issue.

**Comment by kerbo** [comment]
I apologize if I sound like I'm being critical of the framework or the effort you've put into building it. Quasar is really good and more people should be using it. My only reason for creating this issue was to make QTables better. I honestly didn't think there would be this much debate about something I thought was a simple request and one that would make the component easier to use.

To close, I was unaware there is an "Edit" link on the docs page. I will look into it. Thanks.

**Comment by kerbo** [comment]
I looked at "edit" and that requires you to Fork the repository and submit a Pull request for a doc change. Creating a full blown example of a feature would take much time than 2 mins for most people.

What would be easier is providing a Comments section in the Docs. A section for each component would be great. I have no idea how hard this will be to implement but having a spot for users to provide usage comments would be quick and very useful.

**Comment by smolinari** [comment]
I'm about where you are, when it comes to front-end development @kerbo. I was more a backend developer and Vue and Quasar has brought light into what used to be a void in frontend development for me, because I can relate to them both a lot from my past experience. However, JavaScript isn't the answer to all things on the frontend (as React would like us to believe 😄). There is still HTML and CSS to be learned and mastered. Once I have them under my belt, I know I will see things differently. 

In the past, I would have also nagged to get such a feature into Quasar. But, I've also learned to trust Razvan's far greater experience and to know to let go of an idea, when he says, "it isn't going to happen." 😄 

And P.S. I'm part of their team now. For good or bad. 😊 

Scott
