### ISSUE TITLE
[BUG] QInput $data.model isn't updated timely.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2251]
Here I have explained the bug and how to replicate in the PEN:
https://codepen.io/mesqueeb/pen/XqGMMd?editors=1010

**Comment by mesqueeb** [comment]
The fix is to wrap the `name` update inside a setTimeout of `1ms`

**Comment by pdanpdan** [comment]
Check this: https://codepen.io/anon/pen/OwPOpK?editors=1010
You are not really updating name - it's a string, and you are setting it to the same value it had before.
You first need to set it to a new value (the one with icon) and then (in next tick) set it to the value withot icon.
