### ISSUE TITLE
Quasar v0.16 Autocomplete Display/Error

### ISSUE THREAD

**Issue by tmccary9207** [quasarframework/quasar#2252]
### Software version

Quasar: v0.16
OS: Windows
Node: v8.11.1
NPM:  v5.6.0
Browsers: Chrome, FireFox, IE
iOS: Haven't tested.
Android: Haven't tested.
Any other software related to your bug: None

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/b0p7udnz/

### What did you get as the error?
[Vue warn]: Invalid prop: type check failed for prop "active". Expected Boolean, got String.

### What were you expecting?
My coloring was set to a light grey so I could see the data but it was formatted incorrectly. On a white background no results are displayed.

### What steps did you take, to get the error?
Just loading up some data via AJAX and using a static-list in autocomplete. It worked for other components (same setup but fewer items in the static-list) but I have no real idea what is causing the error aside from a lot of data, static-list and autocomplete being put together.

**Comment by pdanpdan** [comment]
You have the autocomplete in the drawer - it's fixed in the new version (in beta, to be released soon)

**Comment by tmccary9207** [comment]
The fiddle was indeed incorrect (in my private source I was setting the label and value props). The problem was a property on the object I was wrapping for autocomplete. It has a property (wait for it) named active.

`
// My data object
{
  name: 'Fop',
  memberSince: '01-01-2017',
  active: 'Y'
}
`

Thus, the error of active being a String instead of boolean is thrown. The autocomplete element documentation makes no mention of a prop called active. Perhaps, a note/recommendation about using autocomplete to select objects should suggest wrapping the object to stop any potential property name collisions. I'm going to close my issue with this as I have found the problem was my data. However, I highly recommend a note in the documentation to wrap objects into the value property to avoid collisions like this (`@select(({value}) => {}` if you want the data object instead of the select-list item).

**Comment by pdanpdan** [comment]
I'll need some more help - where were you using that selected value (having active).
Because the only active property in the framework is in QItem.
