### ISSUE TITLE
cordova apps exit right after click the backbutton on index page

### ISSUE THREAD

**Issue by lemonwong** [quasarframework/quasar#2253]
### Software version

NodeJs                          8.9.4
Global packages
  NPM                           5.6.0
  yarn                          1.7.0
  quasar-cli                    0.16.4
  vue-cli                       2.9.3
  cordova                       7.1.0
Important local packages
  quasar-cli                    0.16.4  (Quasar Framework CLI)
  quasar-framework              0.16.0  (
Any other software related to your bug:

### What did you get as the error?
Hi there,I build a cordova project via quasar-cli. When I click the back button on android at the root page,the app just exits. I add a eventListener at the root page through 
```javascript
  document.addEventListener('backbutton', onBackKeyDown, false)
``` 
at the mounted hook of the root .vue file and remove it at the beforeDestroy hook by 
```javascript
document.removeEventListener('backbutton', onBackKeyDown)
```
the onBackKeyDown function is defined globally.
### What were you expecting?
I want to call the onBackKeyDown function when I click the backbutton on android 
### What steps did you take, to get the error?
it do call the onBackKeyDown function  ,but the app exits right after the function finished. Is it possibile not to exit the app until I want to exit it (by calling navigator.app.exitApp())? Thanks.

**Comment by rstoenescu** [comment]
Hi,

There is a "backbutton" event listener registered by Quasar too (to allow the closing of Modals/Dialogs/ActionSheets instead of navigating to previous page, and to exit app when on index page).

For v0.16 there's no way to disable this default behaviour, but in the v0.17 beta there is through quasar.conf > framework > config > cordova > backButtonExit: false --> more info on the v0.17 beta (do not use in production yet, though): https://forum.quasar-framework.org/topic/2481/quasar-quasar-cli-v0-17-aka-ssr-developer-preview

**Comment by lemonwong** [comment]
Thanks for the reply first.
I tried the .17beta18quasar-cli about the problem.Here comes another issue:
The scene is that when I switch to the index page through ` this.$router.push('/') ` , on index  page when i click back button,it calls the callback function but switch the previous page at the same time .Can I stop the default page switch myself or is it possibile to do just what i write in the callback function of the backButton event when i set  cordova ` backButtonExit: false` in the quasar config file?
When I use ` this.$router.replace('/')` it just switch to the prev prev page (if exists). 
Thanks.
@rstoenescu
