### ISSUE TITLE
QTooltip is not working with QSelect

### ISSUE THREAD

**Issue by dheerajw** [quasarframework/quasar#2255]
Operating System        	Darwin(17.6.0) - darwin/x64
NodeJs                  	8.11.1

Global packages         	
  NPM                   	6.1.0
  yarn                  	1.5.1
  quasar-cli            	0.16.4
  vue-cli               	2.9.6
  cordova               	8.0.0
Any other software related to your bug: Nope

Codepen Link: https://codepen.io/dheerajw/pen/YjyPzB

**Comment by dheerajw** [comment]
Also, is there a way to align selected text to the right side of the box? Is it possible to have a template for each item, just like QList?

**Comment by dheerajw** [comment]
Just noticed its not working for QBtnDropdown, updated the codepen.

**Comment by smolinari** [comment]
Interested in the reply. :smile: 

Scott

**Comment by pdanpdan** [comment]
For QSelect the default slot is not passed into the component.
For QBtnDropdown the default slot is the dropdown and it is placed in the popover, so the tooltip will should when the dropdown is open.

The best solution would be to wrap your desired component in a div having the tooltip.

https://codepen.io/anon/pen/xJwgXr?editors=1010

**Comment by dheerajw** [comment]
Thanks a ton @pdanpdan, you saved my day 👍.
Just wondering if there is any way to center align text in a select box.

**Comment by smolinari** [comment]
Ahhh! 

I've added an addition to the docs. I hope it is correct. :smile: 

https://github.com/quasarframework/quasar-framework.org/pull/511

Scott

**Comment by amplexdenmark** [comment]
Thanks for the explanation! I had the same problem with QBtnDropdown in a QBtnGroup.
Unfortunately wrapping a QBtnDropdown in a \<div> inside a QBtnGroup does not go down very well.

Would anyone have advise regarding this? (tia)
