### ISSUE TITLE
Populate q-select with axios.

### ISSUE THREAD

**Issue by pazfelipe** [quasarframework/quasar#2264]
I'm facing a trouble with axios and q-select.  It's populate when my component is created because it's my axios callback function. So, I got this code:

```
getHours() {
	axios.get('rh')
	.then( res => {
		let hours = res.data
		for(var i = 0; i < hours.length; i++) {
			this.workHours[i] = { label: "Horário - " + (i + 1), value: hours[i]._id };
	        }
	}).catch( err => {
		console.warn(err);
	})
} 
```

And in the created() I call this method. The problem is it doesn't working at all. My select is populated only when I put information manually in

```
data() {
   return {
      options: [{label: 'Option1', value: 'value1}]
   }
}
```
How to solve that?

**Comment by rstoenescu** [comment]
Hi,

Please use Discord server for questions (http://chat.quasar-framework.org). Supply a jsFiddle because your description is not enough for us to give an answer. Thanks!
