### ISSUE TITLE
backbutton event not working using quasar dev in cordova mode with android 5.1

### ISSUE THREAD

**Issue by x1y9** [quasarframework/quasar#2267]
When using debug version(quasar dev -m cordova -T android) with an android 5.1 phone, I can not register backbutton event using following code
```
mounted () {
    if (this.$q.platform.is.cordova) {
      document.addEventListener('backbutton', this.onBackButton, false)
    }
}
```
onBackButton method never get fired when I pressed the back button, but in quasar release version or change a phone with android 7.0, it's ok.

### Software version
Operating System                Windows_NT(6.3.9600) - win32/x64
NodeJs                          8.11.2

Global packages
  NPM                           5.6.0
  yarn                          1.7.0
  quasar-cli                    0.16.4
  vue-cli                       2.9.6
  cordova                       8.0.0
  quasar-cli                    0.16.4  
  quasar-framework              0.16.0  
  quasar-extras                 2.0.2   
  vue                           2.5.16  
  vue-router                    3.0.1  
  vuex                          3.0.1

### What did you get as the error?
onBackButton method never get fired 

### What were you expecting?
onBackButton method should be triggered when I press back button

### What steps did you take, to get the error?
* just using quasar starter kit
* add the backbutton event callback
* using quasar dev -m cordova -T android with an android 5.1 phone

**Comment by nothingismagick** [comment]
Is this issue still relevant?

**Comment by Penayo** [comment]
Why this issue is closed? where is the solution?

**Comment by anandtripathi5** [comment]
Still facing the issue

**Comment by rstoenescu** [comment]
Backbutton is described in [the docs](https://quasar.dev/vue-directives/go-back#Cordova%2FCapacitor). Just disable it for Cordova then you can handle it yourself.

**Comment by anandtripathi5** [comment]
I already went through the docs, cordova backButtonExit is already set to false

```
framework: {
      iconSet: "material-icons", // Quasar icon set
      lang: "en-us", // Quasar language pack
      config: {
        screen: {
          bodyClasses: true // <<< add this
        },
        cordova: {
          backButtonExit: false
        },
        capacitor: {
          // Quasar handles app exit on mobile phone back button
          // Requires Quasar v1.9.3+ for true/false, v1.12.6+ for '*' wildcard and array values
          backButtonExit: false
        }
      },
}
```

**Comment by hawkeye64** [comment]
@anandtripathi5 Have you tried adding your own event listener? Like this: https://gist.github.com/kuldipem/6acfc65dbbbb61e11e2dea95fbb37227#gistcomment-2303741

**Comment by anandtripathi5** [comment]
@hawkeye64 already did

methods: {
    onKeyDown() {
      console.log("hello"); -------> This is not printing the logs on back button
      return false;
    },
    deviceReady() {
      console.log("ready ready"); ------> This is printing on the console
      document.addEventListener("backbutton", this.onKeyDown, false);
      return false;
    }
  },
  computed: {},
  mounted() {},
  created() {
    document.addEventListener("deviceready", this.deviceReady, false);
  }

**Comment by hawkeye64** [comment]
@anandtripathi5 I don't see a a listener attached to your onKeyDown method

**Comment by anandtripathi5** [comment]
@hawkeye64 
Please check on `deviceready` event I have added `deviceReady` function
and on `backbutton` event I have added `onKeyDown` function

I don't know what I'm missing. onKeyDown function is never being called cause there are no logs in the console

**Comment by anandtripathi5** [comment]
Its solved in [7827](https://github.com/quasarframework/quasar/issues/7827) issue.
