### ISSUE TITLE
[0.17 beta] Feature request: add option in quasar.conf for user agent

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2269]
Since SSR uses a lot of CPU, on one of our servers we render just for a specific user agent like for exaple if the user agent is `twitterbot`, we use Nginx to make the decision like(the following is Nginx configurations code snippet):

```
if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
    set $prerender 1;
}
```

I wish if I can specify in `quasar.conf` file for which user agent we want to use the SSR but for the others send them the SPA/PWA files as static files without rendering them.

Can you add this feature, please?

**Comment by rstoenescu** [comment]
Hi,

If you're building SSR, then you can do that yourself in src-ssr/index.js -- which is where content gets served. It's basically the production server and you can change this part:

```js
app.get('*', (req, res) => {
   if (req.headers['user-agent'] ....) {
     res.status(301).redirect("https://new-address.com")
     return
   }
   // ... the rest of initial app.get
})
```
Did I miss anything?

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu thank you for the quick reply, no I don't want to make any redirect, this redirect means we should have to maintain two websites/apps(this is the current situation for one of my apps and it makes me tired).

I wish if we can in Quasar have an option to disable the server side rending for a specific user agent(s) without making a redirect or anything like that.

**Comment by rstoenescu** [comment]
When you build for SSR then the distributable code is SSR specific (as it needs to be). You can't just serve the created "www" folder without it being rendered within a SSR context.

However, you can create two builds (one for SSR, one for SPA/PWA), put them on your server, then mangle with the production server (mentioned earlier - src-ssr/index.js) to distribute the requests accordingly to the User Agent. Make some Google searches on express if it's too foggy or you don't know where to begin.

This pretty specific request cannot be managed from a quasar.conf property, unfortunately, so you have to do it yourself in src-ssr/index.js.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu thank you so much, I understand, I'm going to work on this and will update here when I get any progress in case if anyone faced a similar issue in the future.

**Comment by zicklag** [comment]
@MohammedAl-Mahdawi Another option that seems to work great for me in my first pass is [Rendora](https://github.com/rendora/rendora). It uses headless Chrome to SSR your app based on the user-agent or other factors, but leaves the SPA functionality untouched for your users. I use it with Quasar in SPA mode with no changes in Quasar.
