### ISSUE TITLE
Out of Memory at server dev

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#2270]
### Software version

Quasar: 0.16.0
OS: Windows 10
Node: 8.9.4
NPM: 6.1.0
YARN: 1.7.0
Browsers: ---
iOS:---
Android:---
Any other software related to your bug:

Some hours working...until any save...

 [==================  ] 90% (chunk assets processing)
<--- Last few GCs --->

[8972:000001E99E474410] 15671573 ms: Mark-sweep 1398.3 (1462.5) -> 1398.3 (1463.5) MB, 309.7 / 0.0 ms  allocation failure GC in old space requested
[8972:000001E99E474410] 15671940 ms: Mark-sweep 1398.3 (1463.5) -> 1398.2 (1430.0) MB, 366.9 / 0.0 ms  last resort GC in old space requested
[8972:000001E99E474410] 15672269 ms: Mark-sweep 1398.2 (1430.0) -> 1398.2 (1427.5) MB, 328.9 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001896FBA5EE1 <JSObject>
    2: replace(this=0000028A9FBBC489 <Very long string[1451198]>,0000010F2B876F89 <String[32]: var HTML_WEBPACK_PLUGIN_RESULT =>,0000026629602471 <String[0]: >)
    4: evaluateCompilationResult [C:\Users\Luiz\Documents\byii\vital\app2\node_modules\html-webpack-plugin\index.js:240] [bytecode=0000010F2B877309 offset=40](this=00000178380E9499 <HtmlWebpackPlugin map = 000000517EB0CD31>,compilation...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::Smi::SmiPrint
 6: v8::internal::AllocationSpaceName
 7: v8::internal::SlicedString::SlicedStringGet
 8: v8::internal::compiler::Pipeline::AllocateRegistersForTesting
 9: 0000000155D047A1

this occurs one or two twices a day

**Comment by rstoenescu** [comment]
Hi,

1. This should be reported to CLI repo.
2. It's a webpack issue, not a Quasar one.
3. Ticket already opened for this: https://github.com/quasarframework/quasar-cli/issues/122

**Comment by LuizLeite** [comment]
sory.
