### ISSUE TITLE
QTable Sumary

### ISSUE THREAD

**Issue by scalarerp** [quasarframework/quasar#2271]
Have an example to add a footer row with sumary, or total from columns?

How disable pagination?

**Comment by rstoenescu** [comment]
Hi,

Please use our Discord server for questions.

To quickly answer your questions:
1. https://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/table/table-features > "Row selection, Extra top/bottom rows, Loading state"; source code: https://github.com/quasarframework/quasar-play/blob/master/src/pages/showcase/grouping/table/table-features.vue#L64-L118
2. Use `pagination` prop; set rowsPerPage to 0. Don't forget the ".sync" modifier. https://quasar-framework.org/components/datatable.html#Pagination
