### ISSUE TITLE
q-btn at right can't click then at chrome 67 and Firefox 61

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#2273]
### Software version

Quasar: 0.16.0
OS: Win 10 64x
Node: 8.9.4
NPM: 6.1.0
YARN: 1.7.0
Browsers: Chrome 67
iOS: ---
Android: ---
Any other software related to your bug:

I cant click at q-btn with offset less than 35 of right, and cursor dont change to pointer.

**Comment by rstoenescu** [comment]
Please provide a jsFiddle... your description is very vague. Thank you.

**Comment by LuizLeite** [comment]
Hi.
Create a simple page and than put a q-btn at right position.
You will see that it does not work with zero margin at right.
At left, center or other than runs ok.
But the right does not.
Simple that.
Luiz Leite
 

    Em terça-feira, 17 de julho de 2018 08:08:13 BRT, Razvan Stoenescu <notifications@github.com> escreveu:  
 
 
Please provide a jsFiddle... your description is very vague. Thank you.

**Comment by rstoenescu** [comment]
Are you using QPageSticky, are you not using QPageSticky -- then what are you using? There's a million ways one can interpret your description.

Example of it working:

![btn_sticky](https://user-images.githubusercontent.com/4665641/42816581-fb768ee4-89d3-11e8-94ee-6697601bda76.png)

Help me skip the "figuring out what your use case is" game by providing a jsFiddle. Saves both of us time. Thanks.

**Comment by rstoenescu** [comment]
Closing due to no reply.
