### ISSUE TITLE
[Request] Apply CSS Properties in Batch to an element array

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2275]
I love the Quasar function to [Apply CSS Properties in Batch](https://quasar-framework.org/components/dom-utils.html#Apply-CSS-Properties-in-Batch).

I find myself all the time looping through arrays of elements to apply the CSS to multiple elements. If the function could also accept an element `array` instead of just the single element, I'd be really grateful!

**Comment by imdanielpiva** [comment]
Well, I've got a humble suggestion: you could add a function to your utils which implements this feature by composing with the one that already exists 😉

Example:

```javascript
import { dom } from 'quasar';

const { css } = dom;

function cssBatch(elements = [], style = {}) {
   elements.forEach(el => css(el, style));

  // or
  return elements.map(el => css(el, style));
}
```

**Comment by rstoenescu** [comment]
Hi,

This will go into v1.0. Credits go to @imdanielpiva , thanks!
