### ISSUE TITLE
[0.17 beta] preFetch() run only on the server in the first load of the page

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2277]
### Software version

Quasar:0.17.0-beta.13
OS: Windows 10
Node:10.2.1
NPM:6.1.0
Browsers:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
No error
### What were you expecting?
I expect `preFetch()` to run twice one on the server and another one when the page loaded in the browser.
### What steps did you take, to get the error?
I'm using `quasar-cli: 0.17.0-beta.19` the `preFetch()` only run on the server when we load the page at the first time but after that for example if I navigate to a route(in browser by clicking on it) that contains `preFetch()` it works correctly, just when making the first load like reloading the page it works only on the server.

**Comment by rstoenescu** [comment]
Hi,

Yes. This is exactly how it should work. It would have been a bug if it ran both on server and on client on first page view. The purpose of preFetch() is to fetch some data and inject into the store, validate the page through store state (like is the user logged in etc etc) then redirect to some other route if necessary, all of which is already done on the server on first page view. The store state is injected automatically from the server into the client-side. So there's no need to "fetch" again as you'd just duplicate the same action, wasting resources and delaying page start.
