### ISSUE TITLE
Selecting an option from QSelect hosted on a QPopover closes the popover without v-close-overlay directive

### ISSUE THREAD

**Issue by dheerajw** [quasarframework/quasar#2278]
Operating System        	Darwin(17.6.0) - darwin/x64
NodeJs                  	8.11.1

Global packages         	
  NPM                   	6.1.0
  yarn                  	1.5.1
  quasar-cli            	0.16.4
  vue-cli               	2.9.6
  cordova               	8.0.0

Important local packages	
  quasar-cli            	0.16.4	(Quasar Framework CLI)
  quasar-framework      	0.16.0	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras         	2.0.2	(Quasar Framework fonts, icons and i18n.)
  vue                   	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router            	3.0.1	(Official router for Vue.js 2)
  vuex                  	3.0.1	(state management for Vue.js)
  electron              	Not installed
  electron-packager     	Not installed
  electron-builder      	Not installed
  @babel/core           	7.0.0-beta.49	(Babel compiler core.)
  webpack               	4.9.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server    	3.1.4	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin	3.2.0	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)

Networking              	
  Host                  	users-MacBook-Pro-2.local
  en0                   	192.168.1.5

Per the documentation...
**Handling Popover Dismissal**
By default, clicking/tapping outside the QPopover content will close it. But if you’d like elements from the QPopover content to close it, then use the v-close-overlay Quasar directive.

We didn't add the "v-close-overlay" directive but still selecting an option from the qselect box closes the popover. We are expecting the popover to remain open and all click events are stopped from propagating to other controls on the page. I tried with @click.stop.prevent="", but it didn't work. The idea is the selected text in div should retain text selection after an item selected in QSelect

**Codepen Link**
https://codepen.io/dheerajw/pen/vaKrpq

**Comment by hawkeye64** [comment]
Popovers close after selection, click outside of the popover, or ESC. Use a modal if you want it to stay until directed to close.

**Comment by rstoenescu** [comment]
@dheerajw  Hi,

Popovers in Popovers (like your case) are not supported (yet). So please follow @hawkeye64 's suggestion and use a Modal instead.
