### ISSUE TITLE
Bug: Hot Module not recognizing file change in directory

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar#2279]
### Software version

Operating System                Linux(4.15.0-23-generic) - linux/x64
NodeJs                          10.6.0

Global packages                 
  NPM                           6.1.0
  yarn                          1.7.0
  quasar-cli                    0.16.0
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages        
  quasar-cli                    0.16.0  (Quasar Framework CLI)
  quasar-framework              0.16.0  (Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras                 2.0.0   (Quasar Framework fonts, icons and i18n.)
  vue                           2.5.16  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      1.7.9   (Build cross platform desktop apps with JavaScript, HTML, and CSS)
  electron-packager             9.1.0   (Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI)
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.46   (Babel compiler core.)
  webpack                       4.8.3   (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.4   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.2.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)

Networking                      
  Host                          MatanYad
  wlp2s0                        192.168.1.115

### What did you get as the error?
no error
### What were you expecting?
after file change, hot module to relaunch webpack proccess
### What steps did you take, to get the error?
my file structure is
- pages
--- app
----- index.vue (works fine)
----- inner-directory
------- inner-index.vue (hot module not updating)
--- auth

the reason it happening is only the inner directory
in old cli version i used to use quasar watch-poll

**Comment by rstoenescu** [comment]
Hi,

1. This would be a Webpack bug, not Quasar.
2. If there's a bug for the CLI, pls report it on the CLI repo: https://github.com/quasarframework/quasar-cli/issues
3. Are you sure you are importing (even with lazy-load) the inner-index.vue file somewhere in your code?

Please let's continue with a ticket on the CLI repo. Usually the devil is in the details, so a minimal  reproduction repo might help a lot.

Thank you.
