### ISSUE TITLE
Quasar 9.1 migration - one issue with STYL

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#228]
Hi,
Provided guide 

> Simply make a project-wide replace of 'quasar-' to 'q-' then replace 'q-framework' to 'quasar-framework'.

Causes issue with `app.mat.styl`

Line 30 has to be then changed again to `@import '~quasar-framework/dist/quasar.mat.styl'`
because after project-wide replacement it is becoming `@import '~quasar-framework/dist/q.mat.styl'` which does not exist.

**Comment by rstoenescu** [comment]
How can a 'quasar-' (notice dash at the end) replacement affect 'quasar.' (notice dot at the end)?

**Comment by murbanowicz** [comment]
Oh! Damn! My mistake! That's why I had to fix some other small stuff after replacement... 
but it is working!
I will use opportunity to point issue which is still there:
- card button - still not getting hover below `card-media` div or with other way of putting content in card, it can be not visible.
