### ISSUE TITLE
[0.17 beta] Can't get the currentRoute in preFetch() under quasar dev

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2280]
### Software version

Quasar:0.17.0-beta.13
OS: Windows 10
Node:10.2.1
NPM:6.1.0
Browsers:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
No error
### What were you expecting?
Expect to get the current route
### What steps did you take, to get the error?

I have the following route:

```
  {
    path: '/p',
    component: () => import('components/Categories/Category'),
    children: [
      {
        path: '',
        props: { id: 'all' },
        redirect: '/'
      },
      {
        path: ':id',
        component: () => import('components/Products/ProductDetail'),
        props: true,
        name: 'ProductDetail',
      }
    ]
  }
```

I'm using `quasar-cli: 0.17.0-beta.19` when I use `quasar dev` I cant get the `id` in `ProductDetail` in `preFetch()` using `currentRoute`, the `params` is empty and there is no way to get it!
However, if I used the SSR mode(on the server) I can get the `id` in `params`!

**Comment by rstoenescu** [comment]
Hi,

Yes, fixed it a few hours ago. Thanks for reporting though!

**Comment by rstoenescu** [comment]
Released beta.21 which has the fix. Please read the upgrade guide at the end of forum post if using SSR. Let me know how it goes.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu, thank you, I just updated to beta.21 and will continue my test now.

**Comment by kwarnkham** [comment]
Cannot get currentRoute.query in prefetch when in desktop
