### ISSUE TITLE
Custom classes for q-tab-panes in QTab

### ISSUE THREAD

**Issue by Valianton** [quasarframework/quasar#2281]
Hi, and why I can not add custom class for default slot in QTab component? 

I needed to make a scrollable area in the QTab and the slot="header" should stay fixed.
For example, if i add .scroll classes for q-tab-panes, it's fine works, but i can manipulate  .q-tab-panes =\

**Comment by rstoenescu** [comment]
Hi,

Any jsFiddle to highlight what you want, pls?

**Comment by Valianton** [comment]
Hm, ok then - https://codepen.io/Valianton/pen/GBjdzX

As you see, scroll area belong in block with class ".q-tabs-panes"

**Comment by rstoenescu** [comment]
The PR was merged some time ago. Closing.
