### ISSUE TITLE
q-select error when component removed

### ISSUE THREAD

**Issue by l1v3** [quasarframework/quasar#2282]
Hey, first time reporting here. Hope everythings ok :)

Quasar: v0.16.0
OS: osx 10.12.4
Node: 8.11.3
NPM: 6.1.0
YARN: 1.7.0
Browsers: latest chrome

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/wzcvn5gs/2/

### What did you get as the error?
Uncaught TypeError: Cannot read property 'hide' of undefined
    at VueComponent.hide (quasar.mat.esm.js?523e:15188)
    at eval (quasar.mat.esm.js?523e:15272)

or on jsfiddle:

Uncaught TypeError: Cannot read property 'hide' of undefined
    at o.hide (quasar.mat.umd.min.js:6)
    at quasar.mat.umd.min.js:6

### What were you expecting?
no error

### What steps did you take, to get the error?
- use a q-select that will not render after a value change
- change the value (jsfiddle example, select the second option error)

**Comment by rstoenescu** [comment]
Hi,

Welcome and thanks for reporting! This is already fixed in v0.17 beta, so closing.
