### ISSUE TITLE
[0.17 beta] Using Cookies Quasar plugin in app plugins

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2285]
### Software version

Quasar:0.17.0-beta.15
OS: Windows 10
Node:10.2.1
NPM:6.1.0
Browsers:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:
Quasar-cli:0.17.0-beta.21

### What did you get as the error?
No error
### What were you expecting?
I expect to get Cookies plugin to work in my app plugin
### What steps did you take, to get the error?
This issue appeared on SSR, on `quasar dev` everything looks fine, I used `import { Cookies } from 'quasar'` in one of my app plugins then used `Cookies.get('x-auth')` but this doesn't work.

**Comment by rstoenescu** [comment]
Hi,

It's a long discussion here, that will be available in docs. The SSR needs to take care of the singleton issue, so your import won't work since it's global. However, for SSR I've added a Cookies.parseSSR(ssrContext) method (ssrContext is a param of app plugins or preFetch and available only on serverside). This method returns the cookies specific to the user's session request.

```
const cookies = Cookies.parseSSR(ssrContext)
// now use `cookies` just like you would do with Cookies Quasar import.
```

If you want cookies on a Vue component, you can still use `this.$cookies` just like you did with earlier Quasar versions.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu , thank you so much, I use `import { Cookies } from 'quasar'` in my Vuex store modules files as well, because I have a file for each module, what should I do here? should I also use `const cookies = Cookies.parseSSR(ssrContext)`?

**Comment by MohammedAl-Mahdawi** [comment]
For example the following:

```
    login: ({ commit, state }, payload) => {
        commit('setAuthFetching', true);

        Vue.http.post('users/login', payload).then(response => {
            const token = response.headers.map['x-auth'][0];
            const currentUser = response.body;
            Vue.http.options.headers = { 'x-auth': token };
            Cookies.set('x-auth', token, {expires: 365, path: '/'});
            commit('setToken', token);
            commit('setCurrentUser', currentUser);
            commit('setAuthFetching', false);
            commit('setAuthenticated', true);
            commit('resetLoginErrors');
            bus.$emit('successLogin', response)
        }, response => {
            // error callback
            commit('setAuthFetching', false);
            commit('addLoginError', response.body);
            bus.$emit('successLogin', response)
        });
    }
```

Is the login action in my auth.js module

**Comment by rstoenescu** [comment]
This only means you're doing some initialization work, so it makes sense to do it in App.vue > preFetch ({ store, ssrContext }) -- because this is one reason preFetch exists :)

In any case, for completeness, it also exists `ssrContext` as parameter in both the Store and Router default export function:

```js
export default function ({ ssrContext }) { ... }
```

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu thank you so much, is it possible to get `ssrContext` in the module actions like for example:
```
login: ({ commit, state, ssrContext }, payload) => {
}
```

**Comment by MohammedAl-Mahdawi** [comment]
Or maybe making ssrContext a global variable in order to be accessible across all the app files?

**Comment by rstoenescu** [comment]
The module actions are supplied by Vuex, not Quasar. And unfortunately, ssrContext absolutely cannot be made a global variable, as we'd end up in the singleton issue. You need to be aware of this principle throughout your whole app. Please make sure you read this: https://ssr.vuejs.org/guide/structure.html#avoid-stateful-singletons

However, like I mentioned, your store creating function (/src/store/index.js) receives the "ssrContext" as parameter. Now, you need a bit of refactoring for your modules. You can create a function for each module (to which you can pass the ssrContext received above in store/index.js) and return your ssrContext-aware module from there. OR, you can just define the module directly in store/index.js. Does this makes sense to you?

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu, thank you so much, I went ahead and created a function for each module that needs `ssrContext`.

**Comment by spot0** [comment]
Hello @MohammedAl-Mahdawi can you explain how you manage do add ssrcontext to your module ?
thank you

**Comment by spot0** [comment]
i have done this but my module didn't get the ssrContext
`  requireModule.keys().forEach(fileName => {
    if (fileName === './index.js') return
    const moduleName = fileName.replace(/(\.\/|\/index\.js)/g, '')
    modules[moduleName] = {
      namespaced: true,
      ...requireModule(fileName).default,
      ssrContext
    }
  })`

**Comment by rajasa** [comment]
hi @MohammedAl-Mahdawi can you share what the code would look like when trying to pass on ssrContext to the vuex module. I'm stuck with the same problem and rather confused. Thank you in advance.

**Comment by kalim7rings** [comment]
@rajasa Have you got any solution for your problem ?   If yes kindly show your code what you have implemented.

@MohammedAl-Mahdawi  can you share your code. I am also stuck on same problem.

**Comment by kalim7rings** [comment]
@rstoenescu can you share some code example for above problem ?
     I want to access ssrContext  in state.js to check if cookie already set or not ? if set then use already set values else initialize with new value.

**Comment by romain130492** [comment]
any response to this? , thanks
