### ISSUE TITLE
Microphone icon showing two icons at the same time

### ISSUE THREAD

**Issue by Abuntxa** [quasarframework/quasar#2289]
### Software version

Operating System                                                                Windows_NT(10.0.16299) - win32/x64
NodeJs                                                                          10.4.0

Global packages
  NPM                                                                           6.1.0
  yarn                                                                          1.7.0
  quasar-cli                                                                    0.16.4
  vue-cli                                                                       2.9.6
  cordova                                                                       8.0.0

Important local packages
  quasar-cli                                                                    0.16.4  (Quasar Framework CLI)
  quasar-framework                                                              0.16.0  (Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras                                                                 2.0.2   (Quasar Framework fonts, icons and i18n.)
  vue                                                                           2.5.16  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                                                                    3.0.1   (Official router for Vue.js 2)
  vuex                                                                          3.0.1   (state management for Vue.js)
  electron                                                                      Not installed
  electron-packager                                                             Not installed
  electron-builder                                                              Not installed
  @babel/core                                                                   7.0.0-beta.49   (Babel compiler core.)
  webpack                                                                       4.9.1   (Packs CommonJs/AMD modules for
the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server                                                            3.1.4   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin                                                        3.2.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/gj154t2L/1/

### What did you get as the error?
Whenevet I try to use the microphone icon appear 2 icons:
* microphone icon
* telephone icon

### What were you expecting?
Only the microphone icon

### What steps did you take, to get the error?
<q-btn icon="microphone" />
See the jsfiddle.

**Comment by rstoenescu** [comment]
There's no "microphone" icon. There's "mic" and there's "phone". Being a ligature font, Material Icons shows the mic, doesn't know to interpret "ro" (so weird space) then displays the "phone".
