### ISSUE TITLE
Rename Stylus variables $layout-aside-background, $layout-aside-left-width, $layout-aside-right-width, $layout-aside-shadow.

### ISSUE THREAD

**Issue by sontis3** [quasarframework/quasar#2291]
Hello!
  Now there is inconsistent part "...-aside-..." in stylus variables:
 $layout-**aside**-background, $layout-**aside**-left-width, $layout-**aside**-right-width, $layout-**aside**-shadow.

So my suggestion is to rename to
 $layout-**drawer**-background, $layout-**drawer**-left-width, $layout-**drawer**-right-width, $layout-**drawer**-shadow
Thanks.

**Comment by rstoenescu** [comment]
Done for v1.0 -- $layout-drawer-*
