### ISSUE TITLE
Implementation of new Material Design guidelines?

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#2292]
Hi,

You probably noticed recent updated of MD.
I took a look at key updates here: https://blog.usejournal.com/android-p-changes-in-new-material-design-ffb61e6112f9

I know some of the components can be done by some play with current quasar components but I don't think all of them.

+ Banner
+ Backdrop
+ Filter chips
+ Middle dividers
+ Image lists (different variants etc)
+ Standard bottom sheet - similar to modal which we have but not disabling the bottom layer
+ Additional input style (outlined)

Would be nice to discuss what has to be changed / created

**Comment by rstoenescu** [comment]
Short message: New Material in Quasar is coming.

**Comment by rstoenescu** [comment]
Mostly done for v1.0.
