### ISSUE TITLE
[Bug] QSelect / select / q-select : dropdown box of second select will not open in some cases / focus error

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#2293]
https://jsfiddle.net/ykastc5r/6/

Click (WIn10, Edge) in first select field to open dropdown box
click in second select field

(dropdown box of second select field opens, BUT first select field still is drawn as focused)

Click again in first select field.

(First dropdown box WILL NOT open)

**Comment by rstoenescu** [comment]
Fixed in upcoming 0.17 release already.
