### ISSUE TITLE
Q-tooltip doesn't show automatically with q-fab-action on mobile

### ISSUE THREAD

**Issue by TatiTheFreaK** [quasarframework/quasar#2294]
### Software version

Quasar: 0.16
OS: MacOSX, Win10
Node: 9.7.1
NPM: 6.1.0
Browsers: Chrome, Firefox (Responsive Mode on both)
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/vsba6d4r/

### What did you get as the error?
The q-tooltip only shows when I click on q-fab-action, while it closes the "submenu". The same behavior doesn't happen on q-fab itself, that shows the q-tooltip automatically. (Please see image below)
![unnamed](https://user-images.githubusercontent.com/11199668/43017641-39751c50-8c2d-11e8-9fcf-c8b627a22569.png)

### What were you expecting?
I believe that it should show a q-tooltip on the side of a q-fab-action, and it should open automatically when I click on the q-fab (to be more easier for the mobile users to understand what the icons do).

I've tried to look in the documentation and add `slot="tooltip"` on q-tooltip, with no success.

**Comment by TatiTheFreaK** [comment]
Workaround: https://jsfiddle.net/vsba6d4r/73/ (Code by TobyMosque on Quasar Discord)

**Comment by pdanpdan** [comment]
Or you can use this variant: https://jsfiddle.net/vsba6d4r/92/
Almost the same thing, with one variable to rule them all :)
