### ISSUE TITLE
[0.17 beta] Using the exported Axios instance inside the JavaScript files in SSR

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2295]
Is using the exported Axios instance inside the JavaScript files like how it is described [here](https://quasar-framework.org/guide/app-plugins.html#Accessing-data-from-plugins) with SSR will end up in the singleton SSR issue? if yes then what is the solution?

**Comment by rstoenescu** [comment]
That's safe. You can reuse it.
