### ISSUE TITLE
[0.17 beta] preFetch function of one of the child components never called

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2298]
### Software version

Quasar:0.17.0-beta.15
OS: Windows 10
Node:10.2.1
NPM:6.1.0
Browsers:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:
Quasar-cli:0.17.0-beta.21

### What did you get as the error?
No error
### What were you expecting?
I expect the preFetch function to work just fine
### What steps did you take, to get the error?
I have the following route:

```
  {
    path: '/a',
    component: () => import('components/Addresses/Addresses'),
    children: [
      {
        path: '',
        component: () => import('components/Addresses/AddressList'),
        name: 'AddressList',
      },
      {
        path: 'new',
        component: () => import('components/Addresses/AddressEdit'),
        name: 'AddressNew',
      },
      {
        path: ':id/edit',
        component: () => import('components/Addresses/AddressEdit'),
        props: true,
        name: 'AddressEdit',
      },
      {
        path: ':id',
        component: () => import('components/Addresses/AddressDetail'),
        props: true,
        name: 'AddressDetail',
      }
    ]
  }
```
The template of the `Addresses` component is:
```
<template>
<router-view></router-view>
</template>
```
And some of the `AddressList` component template is:

```
<template>
    <app-addess-item  v-for="i in getAddresses" :key="i._id" :item="i"></app-addess-item>
</template>
```
Now when I got to `http://localhost:8080/a` the `preFetch` function of the `AddressItem` component(the app-addess-item component above) is never called, I think for both the SSR & `quasar dev`!

**Comment by rstoenescu** [comment]
Hi,

I guess I missed explaining the following on the forum post on v0.17: preFetch only works for the components being used for the routes. So it doesn't go all the way down to all components, due to performance reasons.
