### ISSUE TITLE
q-drawer-link - not getting active on '' path

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#230]
Hi,
Simple like that: don't know why, but `q-drawer-link` does not get active state on home `"/"` path with nested routes (don't know if it's the same with not nested)

**Comment by rstoenescu** [comment]
Are you using `:to="{path: '/', exact: true}"` ? Notice the "exact" there. If so, remove it as you are not trying to match "/" exactly because you have nested routes.

**Comment by rstoenescu** [comment]
Please reopen and answer the question above.  Thanks. Can't replicate your issue. Might be a misuse somewhere but I need your reply.

**Comment by murbanowicz** [comment]
Hello again,

now I have it almost working but... link to main route is always active when any subroute is active.

I have my routes:
```
{
      path: '/panel',
      component: panel,
      beforeEnter: reqAuth,
      children: [
        { path: '', component: epPanelHome },
        { path: 'events', component: epPanelEvents },
        { path: 'groups', component: epPanelGroups }
      ]
    },
```

and links:
```
<q-drawer-link icon="dashboard" to="/panel" exact>
              Panel
            </q-drawer-link>
            <q-drawer-link icon="assignment" to="/panel/events">
              Events
            </q-drawer-link>
            <q-drawer-link icon="people" to="/panel/groups">
              Groups
            </q-drawer-link>
```

It is the same with and without `exact` ...

**Comment by rstoenescu** [comment]
Documentation says: http://quasar-framework.org/components/drawer.html#Drawer-Content
Note `:to="{path: '/home/help', exact: true}"`.

`exact` has to be a prop of `to` instead of a standalone attribute.

**Comment by murbanowicz** [comment]
Ah, you made an update recently because it was copied from docs :)

4 gru 2016 13:42 "Razvan Stoenescu" <notifications@github.com> napisał(a):

**Comment by rstoenescu** [comment]
Please always check documentation when something seems to not work. Saves us both time :)

**Comment by Zolotov88** [comment]
I have same problem right now. 
This gives active class:
```
<router-link 
  to="/users" 
  tag="div" 
  class="item item-link drawer-closer"
>
  <div class="item-content">
    Пользователи
  </div>
</router-link>
```
but this:
```
<q-drawer-link to="/users">
  Пользователи
</q-drawer-link>
```
or this:
```
<q-drawer-link :to="{path: '/users', exact: false}">
  Пользователи
</q-drawer-link>
```
don't.
Do I making something wrong?
