### ISSUE TITLE
Unable to set xhr's withCredentials flag in request for QUploader

### ISSUE THREAD

**Issue by chaitanya-plylabs** [quasarframework/quasar#2305]
Is there is a way to set withCredentials flag in q-uploader's XmlHttpRequest ?

**Comment by pdanpdan** [comment]
In the next version: check https://github.com/quasarframework/quasar/pull/2093

**Comment by rstoenescu** [comment]
QUploader new prop in v0.17: "with-credentials" (Boolean).
