### ISSUE TITLE
[Request] Truncate text in QInput

### ISSUE THREAD

**Issue by Valianton** [quasarframework/quasar#2307]
`<q-input
    type="text"
   class="ellipsis"
/>`

Hi, class="ellipsis" into q-input doesn't work.
But, if manually put this class into `<input>`, work fine
See, https://codepen.io/Valianton/pen/OwmBXx

I would like to have a property for a ellipsis in a q-input

**Comment by nkoik** [comment]
This is happening because classes aren't inherited to nested elements.
```html
Component
---
<q-input type="text" class="ellipsis" />

DOM
---
<div class="q-if row no-wrap items-end relative-position q-input ellipsis">
    <div class="q-if-inner col row no-wrap relative-position">
        <input step="any" type="text" class="col q-input-target q-no-input-spinner">
    </div>
</div>
```
You can try this in your stylesheet `.ellipsis .q-input-target`

@rstoenescu 
May we could add an extraClass prop or get vnode staticclasses?

**Comment by Valianton** [comment]
Yeap, but if style have scoped attribute, this is not working

**Comment by rstoenescu** [comment]
Will be available in v0.17.9 by default. Thanks for reporting!

**Comment by Valianton** [comment]
_Hey, what about truncate text in QInput in Quasar 1.7?_ 
I lost the ability to add ellipsis in the input field. Or is there another way to do this?
Ellipsis - visibility class does not work =\

**Comment by pdanpdan** [comment]
@Valianton In v1 you can pass any class to the internal input with `input-class`: https://codepen.io/pdanpdan/pen/BayVExN
