### ISSUE TITLE
QAutocomplete display label, but use value as a model

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2309]
Hello!

This is based on `https://github.com/quasarframework/quasar/issues/1780`

Use case:
1) List of users (name, id)
2) When user is selected, name is displayed in the input, model is id

One of the workarounds is to use object property as a model as described in the ticket from the above:
https://jsfiddle.net/waugrryy/4067/

Although this doesn't work when you want to open popup by clicking inside the input:
`this.$refs.autocomplete.trigger()`

1) Click inside input, select 'Foo' -> Foo is displayed
2) Click again, select 'Foo' -> 1 is displayed
Expected: 'Foo' should be displayed

Thanks!

**Comment by pdanpdan** [comment]
I don't understand how this should work.
What happens if you type something outside of the list?

A working example: https://jsfiddle.net/drajtzLy/21/

**Comment by jean-moldovan** [comment]
If you type in something outside of list label gets reverted  to the previous Fooinvalid -> Foo and model doesn't change
