### ISSUE TITLE
Grid layout - width allowing content to grow up the parent div

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#231]
I have a simple grid inside my view.
```
<div class="row sm-column gutter">
    <div class="width-3of4">content...</div>
    <div class="width-1of4">looooooong content...</div>
</div>
```

Content is basically card, one per parent div with width.
When I will put long text in 1of4 div, it becomes wider and wider instead of wrapping text to new line...

What is wrong with the grid css?

**Comment by murbanowicz** [comment]
I found the article how it should be resolved. I did want to fix it with PR but I don't know where to put it as it is not simple class...

https://css-tricks.com/flexbox-truncated-text/

We are missing in `width` class:
```
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
```

**Comment by rstoenescu** [comment]
Hi, Just add `.ellipsis` CSS class for that. No change in Quasar required.
