### ISSUE TITLE
Refresh data in datatable after modify array

### ISSUE THREAD

**Issue by thiagoreri** [quasarframework/quasar#2311]
How to Refresh data in datatable interface after modify array?

**Comment by hawkeye64** [comment]
How was the array modified? Vue can detect the change (if done right) and it will automagically work.

Excerpt from https://vuejs.org/v2/guide/list.html:
```
Array Change Detection
Mutation Methods
Vue wraps an observed array’s mutation methods so they will also trigger view updates. The wrapped methods are:

push()
pop()
shift()
unshift()
splice()
sort()
reverse()
```

**Comment by rstoenescu** [comment]
Closing as this is 100% a misusage in your app and not in Quasar. Please use our Discord for help.
