### ISSUE TITLE
Tooltip showing despite false

### ISSUE THREAD

**Issue by Zyles** [quasarframework/quasar#2312]
### Software version

Quasar: 0.16.4
OS: Win 10
Node: 8.11.3
NPM: 6.1.0
Browsers: Chrome

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/056u43qg/

### What did you get as the error?
Tooltip showing despite v-model being set to false.

### What were you expecting?
The tooltip not to show.

Not sure if I understood the tooltip component right.

But I want it to be hidden until I change the value to "true". Right now it shows on hover even when the v-model is set as default to false.

Am I doing it wrong?

**Comment by Valianton** [comment]
I should use v-if in tooltip

`<q-tooltip v-model="someModelTooltip" v-if="showBuyValueTooltip">
    {{ buyValueTooltip }}
  </q-tooltip>`

**Comment by panstromek** [comment]
or `disable` prop

**Comment by panstromek** [comment]
tooltip v-model is set both ways - thats why it is v-model. Tooltip changes model variable, too

**Comment by panstromek** [comment]
anyway @rstoenescu I already needed to deal with  full programatic control of tooltip. Would it be possible somehow?

**Comment by pdanpdan** [comment]
@panstromek What do you mean? You don't have to use v-model, you can use :value and set it as you wish.

**Comment by panstromek** [comment]
@pdanpdan yea, that's right. I didn't think about this.. thanks
