### ISSUE TITLE
QCollapsible custom header link prop

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2316]
Hello!

When using QCollapsible with a custom header there is no way to add highlighting.
Tried using an inner QItem as a workaround, but that doesn't highlight the entire header:

https://jsfiddle.net/waugrryy/4228/

Thanks!

**Comment by panstromek** [comment]
I think it could be also useful to have something like 'highlight' CSS helper class that would highlight on hover the same way it works on q-btn, q-item etc

**Comment by pdanpdan** [comment]
I suppose you need this: https://jsfiddle.net/ruL7dc20/1/

**Comment by jean-moldovan** [comment]
yes, indeed!

**Comment by jean-moldovan** [comment]
@pdanpdan , Although it doesn't respect $item-base-color. Is there a stylus variable to controls the color?

**Comment by pdanpdan** [comment]
Just put a color on .q-focus-helper
https://jsfiddle.net/ruL7dc20/3/

**Comment by jean-moldovan** [comment]
Okay, that'll do, thanks again! 👍
