### ISSUE TITLE
Q-select and two way bindings

### ISSUE THREAD

**Issue by julienvedebe** [quasarframework/quasar#2318]
Hello,

When I use two way bindings with a computed vars coming from state the q-select value don't change but the state change.

Part of vue page  

```
<form>
      <q-field helper="Height">
        <q-select inverted-light color="lime"
        v-model="height" :options="heightOptions" />
      </q-field>
      <select v-model="height">
        <option v-for="option in heightOptions" v-bind:value="option.value"
        v-bind:key="option.value">
          {{ option.label }}
        </option>
      </select>
    </form>
```

```
// Computed part
computed: {
    height: {
      get() {
        return this.$store.state.auth.User.userStats.height;
      },
      set(value) {
        this.$store.commit('auth/SAVE_USER_PROP', { prop: 'height', value });
      },
    },
    heightOptions() {
      const heightArray = [];
      for (let pas = 100; pas < 251; pas += 1) {
        heightArray.push({ value: pas, label: pas.toString() });
      }
      return heightArray;
    },
  },
```

```
//store part 
export const SAVE_USER_PROP = (state, val) => {
  state.User.userStats[val.prop] = val.value;
};
```

Simple select works, it's value change and update also the state using mutation but the q-select don't work, it's value don't change but update the state.

I could use single way binding with :value and @input but wanted to use v-model for consise code.

Thanks

### Software version

Quasar: 0.15.20
OS: Windows 10
Node: 9.11.2
NPM: 5.6.0
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
q-select didn't update it's value

### What were you expecting?
q-select update from state

### What steps did you take, to get the error?
see description

**Comment by rstoenescu** [comment]
Please provide a jsFiddle to speed things up and eliminate the guessing game. Thanks.

**Comment by julienvedebe** [comment]
Yes sorry, 

Here is the codePEN: https://codepen.io/neige/pen/XBaJRz

Playing with the codePen I see that it works if I have property directly rather than nested objects.

Thanks

**Comment by hawkeye64** [comment]
First, you should read this: https://vuejs.org/v2/guide/reactivity.html
A direct property is a first-class citizen. Vue puts a watch on it. If you use a nested object (second-class citizen), the watch won't pick it up. Therefore, you have to let vue know there is a change by setting it like this (from my own code) in my mutations.js:
```
export const setSideListSelected = (state, selected) => {
  Vue.set(state.sideList, 'selected', selected)
}
```
sideList is a nested object with 'selected' being one of the items. The third parameter is the value to set the nested property.

Hope that helps!

**Comment by julienvedebe** [comment]
Thanks hawkeye64 for explanation, yes I have read that link I thought there was an issue as the std select works.
I wander if there is a proper way to deal with that case using Vuex and v-model.

**Comment by julienvedebe** [comment]
I understand the root cause, in my state i don't declare the full nested objects as the result the reactive observers are not created.

Sorry for non-issue reporting.
