### ISSUE TITLE
Bug with a link color in list

### ISSUE THREAD

**Issue by artem0071** [quasarframework/quasar#2319]
F. e we have component:
```
<q-list
    no-border
    link
    inset-delimiter
    :dark="isDark"
  >
    <q-item link to="/">
      <q-item-main label="Go test" />
    </q-item>
  </q-list>
```

If it would be dark theme the title of link will have black color instead of white.
That happened because a.q-link have black color with !important attribute.
So, if to delete this attribute, in dark mode link will have white color

**Comment by rstoenescu** [comment]
Can you supply a jsFiddle pls?

**Comment by pdanpdan** [comment]
`a.q-link` has `color: inherit !important` so just set the right color on the list

**Comment by artem0071** [comment]
@pdanpdan yes, it help.
@rstoenescu hmm, i can't do it in jsFiddle, but I just upgrade project v.0.16 -> v.0.17. And the only thing was changed is `color: inherit !important` in `a.q-link`
