### ISSUE TITLE
HTML Symbols/Entities are no longer rendered in q-select 

### ISSUE THREAD

**Issue by FascistDonut** [quasarframework/quasar#2320]
In Quasar <0.15, I was able to use HTML entities such as `&sup3;` inside of q-select option labels. 

These are no longer functioning now that I have updated to 0.16. I have also tried it in 0.17 and it doesn't work there either. 

Here is an example fiddle using 0.17:  https://jsfiddle.net/5fpdg72o/

**Comment by lei-cao** [comment]
This is also a problem for clearable. The 'x' icon is showing now by default. 
I didn't create a separated issue but made a fork from current issue https://jsfiddle.net/nofL1645/

**Comment by rstoenescu** [comment]
Hi,

1. Embedding HTML was removed due to possible XSS attacks in all components.
2. You are explicitly using "clearable" prop which adds the "x" icon you mentioned.

**Comment by lei-cao** [comment]
hi @rstoenescu ,

In previous version if no option selected, the "x" icon is not showing which make sense.
But now even if the option is empty, the "x" always showing.

**Comment by rstoenescu** [comment]
@lei-cao Hi, are you sure you are coordinating "clearable" with "clear-value"? "clear-value" is by default `[]` (for multiple selection) and `null` for single selection, and is matched against current value to establish if the icon is displayed or not. If you're using a custom value like an empty string (`''`) and haven't set the `clear-value` to same thing it obviously won't work.
