### ISSUE TITLE
Bug with q-app detection

### ISSUE THREAD

**Issue by Boid-John** [quasarframework/quasar#2323]
Quasar CLI........ v0.17.0
 Quasar Framework.. v0.17.0

![image](https://user-images.githubusercontent.com/30223943/43236701-284d8f34-904c-11e8-8b39-fbc7060767a8.png)
This is valid syntax according to official pug documentation
https://pugjs.org/language/attributes.html#id-literal

However, the Quasar cli throws an error:

```
 app:quasar-conf Reading quasar.conf.js +0ms

⚠️  Your newer Quasar CLI requires a minor change to the root component:
   /Users/boid/Dev/boid/boidapp/src/App.vue

  Please add: id="q-app"
  to the outermost HTML element of the template.

Example:
  <template>
    <div id="q-app">
      ...
    </div>
  </template>
```
If I use a more verbose pug syntax:
![image](https://user-images.githubusercontent.com/30223943/43236802-932081f4-904c-11e8-9dd1-a3217e929887.png)

Then quasar compiles correctly.

Also interesting to note: If you change the syntax while the webpack dev server is running, it recompiles with no issue. The error is only thrown when starting the dev server or performing a final build. I did not receive this error with previous quasar builds.

**Comment by rstoenescu** [comment]
Hi,

Would you be so kind to open the ticket on the CLI repo pls, since this is a CLI bug? https://github.com/quasarframework/quasar-cli/issues

Thanks!
