### ISSUE TITLE
[Request] QTimeline always one-sided

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#2324]
Making a request to allow the QTimeline to remain only one-sided. If I leave them all right-sided, there is massive margin on the left-side (on desktop).

Also, on the docs:
https://quasar-framework.org/components/timeline.html

It says that QTimelineEntry _side_ is a _boolean_, whereas it should be a string "left"|"right"

**Comment by rossity** [comment]
Do you mean when you get to the iPad screen sizes? If so, I agree, because the timeline becomes off-center. I think It would be nice if we could decide the breakpoints.

![img](https://i.imgur.com/0qUEE6m.png)

**Comment by nicholaszuccarelli** [comment]
Hi Ross.
I do. And on desktop screens too. 
Typically you align the items on the left and right for the effect, however I want the timeline items to appear on the right, but this leave a massive gap on the left - similar to the image you supplied.

**Comment by smolinari** [comment]
Can't the alignment be fixed with CSS?

Scott

**Comment by nicholaszuccarelli** [comment]
Most likely. I'm going to play around with the CSS tomorrow to see what I can do :)

**Comment by nicholaszuccarelli** [comment]
Hi ajarti,

I haven't created a solution yet, but I do plan on looking in to it soon. 
Once I have a working CSS solution, I'll post it here :)

**Comment by ajarti** [comment]
Hi @nicholaszuccarelli thanks, I just removed the 2 breakpoints from the CSS as delivered the CSS from my site instead of the CDN.  The default is on the left, so works nicely.  

But, I will just have to keep doing this as I upgrade the CSS which is not optimal, so a setting force the lefthand layout get's my upvote! :)

**Comment by rstoenescu** [comment]
Added `responsive` Boolean prop. When it's not used, QTimeline is not responsive. Available in 0.17.7
