### ISSUE TITLE
Q-Icon font size conflict

### ISSUE THREAD

**Issue by PauloFerreira25** [quasarframework/quasar#2327]
Hello. In the Quasar.mat.style file at line 1074, there is a conflict with another style.
Could you please remove this line?
![captura de tela de 2018-07-26 07-24-23](https://user-images.githubusercontent.com/1591772/43257019-f3b273f8-90a4-11e8-8234-f05a24d12a76.png)

Evidence:
![captura de tela de 2018-07-26 07-20-17](https://user-images.githubusercontent.com/1591772/43256894-9a0a6338-90a4-11e8-8cf6-2ae805898119.png)

Reality:
![captura de tela de 2018-07-26 07-21-04](https://user-images.githubusercontent.com/1591772/43256900-9c8db0f6-90a4-11e8-9920-16bd52f6e947.png)

Expectancy:
![captura de tela de 2018-07-26 07-20-52](https://user-images.githubusercontent.com/1591772/43256903-9e2a68fa-90a4-11e8-8545-2e0449b316fc.png)

This happens I believe that since version 0.14
This problem happens when you put a Q-Button inside and a <span slot = "subtitle"> inside a <q-card-title>

Thank you very much for your attention.
Quasar is wonderful.

**Comment by PauloFerreira25** [comment]
Never mind, I understand why it's like this:
![captura de tela de 2018-07-26 07-33-39](https://user-images.githubusercontent.com/1591772/43257463-3e2062a0-90a6-11e8-8e87-d6a4ef2b5415.png)
The stars of the quasar example were assembled with this.

**Comment by panstromek** [comment]
this font size is just default anyway, so you can change it (size prop). You can also specifiy icon right on the button instead of using q-icon tag
