### ISSUE TITLE
[Bug] Quasar 0.17.2 platform plugin is not transpiled causing error in Edge/IE11

### ISSUE THREAD

**Issue by solaris7791** [quasarframework/quasar#2331]
Hello,
with quasar 0.17.2 Edge and IE11 get script errors in platform.js in parseSSR function.
Problem is cause by the spread operator 
      is: getPlatform(),
      ...getClientProperties()

**Comment by rstoenescu** [comment]
Hi,

This should go in Quasar CLI repo.
Fixed with Quasar CLI v0.17.3.

**Comment by solaris7791** [comment]
great, works :) 👍
