### ISSUE TITLE
q-autocomplete keyboard arrow navigation trigger @selected event

### ISSUE THREAD

**Issue by Mohanrau** [quasarframework/quasar#2333]
### Software version

Quasar:0.17.2
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
q-autocomplete keyboard arrow navigation trigger @selected event automatically without pressing enter key

### What were you expecting?
Trigger @selected event on enter key

### What steps did you take, to get the error?
HTML
```
<q-search 
      v-model="terms"
      inverted-light
      class="no-shadow custom-input-border"
      color="white text-grey-6"
      clearable
     @input="resetTree">
    <q-autocomplete @search="search" @selected="selected"/>
</q-search>
```
CODE
```
search (terms, done) {
  let query = {
          search_text: this.terms,
          limit: 10
     }
    this.getMemberSearchAction(query).then(res => {
       done(this.membersSearchData.list)
    })
},
selected (item) {
   this.terms = item.sublabel
   this.user_id = item.userID
   this.getMemberMultiFunctionalTree()
},
```

**Comment by pdanpdan** [comment]
Yes. Now @selected has 2 parameters
- first: selected item
- second: true if keyboard navigation

You can check for the second parameter and skip processing.
