### ISSUE TITLE
preFetch is not getting called at the beginning of app bootup

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar#2334]
### Software version

Quasar: v0.17.2
Node: v9.4.0
NPM: 5.6.0

### What were you expecting?
I have removed boot.js from my quasar app as it is deprecated. I have added preFetch in my App.vue by assuming that it should be called at the beginning of the App startup, 
But i observed that my `beforeCreate` and `mounted` methods are executing before `preFetch`. 

### What steps did you take, to get the error?
Below is the overview of my code

```
export default {
  name: 'admin',
  data () {
      return {
        delay: 50,
        speed: 350,
        color: 'primary',
      }
  },
  preFetch ({ redirect }) {
    console.log("*** preFetch ***");
  },
  beforeCreate: function() {
    console.log("*** beforeCreate ***");
  },
  mounted : function() {
        console.log("*** mounted ***");
    }
}
```

I have large amount of code in boot.js (Authentication mechanism using amazon cognito).

What should be the good way to replace that code of boot.js using preFetch?

Thanks!

**Comment by rstoenescu** [comment]
Have you enabled the preFetch feature? quasar.conf > preFetch: true

**Comment by jayudhandha** [comment]
Yes I have enabled this.

**Comment by rstoenescu** [comment]
Any repo I can take a look, pls?

**Comment by jayudhandha** [comment]
Note have any repo for the moment. But I will update soon.

You can try by adding above code in script tag of `App.vue`

**Comment by panstromek** [comment]
+1

**Comment by rstoenescu** [comment]
I was under the impression that `preFetch` does not gets called at all. In any case, for non-SSR builds, it is perfectly normal for App.vue's beforeCreate() and mounted() hooks to be called before preFetch(). But just for App.vue.

Replacing boot plugin with preFetch in App.vue:
```js
// App.vue
export default {
  preFetch ({ redirect }) {
    // return a Promise if doing something async...

    // and call redirect(false) at any point if you want to
    // stop your app from getting rendered. BUT App.vue always
    // gets rendered (with no router-view children!),
    // otherwise Quasar cannot tap into the app's Router!
  }
}
```

**Comment by jayudhandha** [comment]
Hi @rstoenescu thanks for your prompt reply on this.

https://quasar-framework.org/guide/app-prefetch-feature.html#Redirecting-Example

In this docs of redirect using preFetch in App.vue, I have read the comment below
`// We assume here we already wrote the authentication logic`

Can you explain me where should this authentication logic should come? 
I want to make my whole authentication process + save tokens in store after successful authentication.

Than my Vue app should start.

But if i put preFetch in my App.vue than i am not able to achieve this.

Let me know if i can provide you anything on here or I am available in Discord as well.

Thanks!

**Comment by rstoenescu** [comment]
What's your boot plugin now? I'll just rewrite it with preFetch for you.

**Comment by jayudhandha** [comment]
I have sent you a message on Discord
Id: jayudhandha
