### ISSUE TITLE
infinite scroll not workin on jsfiddle

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2336]
Here I expect burst of lorem ipsum until the page is filled up. 

https://jsfiddle.net/mkce1rfp/5/

I don't if I should do anything else in this setup to make it work.. I only use cli based project. Found this when trying to reproduce 'infinite scroll not working together with pull to refresh'

**Comment by pdanpdan** [comment]
https://jsfiddle.net/mkce1rfp/37/

**Comment by panstromek** [comment]
omg, I misspelled 'infinite'..  anyway, I tried to put it inside q-pull-to-refresh and it works in fiddle, so it is probably something on my end
