### ISSUE TITLE
[Request] QCarousel/QEditor/QTable emit event on fullscreen change

### ISSUE THREAD

**Issue by euphemism** [quasarframework/quasar#2338]
It would be nice to have an event like _@fullscreen-toggle(isFullscreen)_ where _isFullscreen_ would be a boolean.  My use case being that I would like to bind _handle-arrow-keys_ to the output of the event allowing arrow key navigation only when the carousel is fullscreen.  I am sure there would be other use cases for this.

**Comment by rstoenescu** [comment]
Added `@fullscreen` event for QCarousel/QEditor/QTable. Extended to QEditor & QTable too. Available in future Quasar v0.17.7.
