### ISSUE TITLE
Quasar with PM2 Watch & SSR

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2340]
### Software version

Quasar:0.17.2
OS: Ubuntu16.04(Linux(4.15.13-x86_64-linode106) - linux/x64)
Node:10.7.0
NPM:6.1.0
Browsers: Google Chrome
iOS:
Android:
Any other software related to your bug:
PM2: 3.0.3
### What did you get as the error?
The error different from place to place
### What were you expecting?
I didn't expect these issues
### What steps did you take, to get the error?
I have a script that automatically updates my server scripts when I make a change on my computer and commit it.

For the Nodejs apps I use PM2 with `--watch` so when my script update the repositories and build for example my Quasar app, PM2 restart the Nodejs server/script and use the latest files.

Today I found my app that runs Quasar SSR has `502 Bad Gateway` error on its page, after debugging the issue here is how to reproduce it.

1. Run `quasar build -m ssr -t mat`
2. Run `cd dist/ssr-mat/`
3. Run `sudo pm2 start index.js --name Quasa --watch`
4. Run ` cd ..` twice.
5. Say now I updated some files in my app and I want to rebuild it.
6. Run `quasar build -m ssr -t mat`

Now the working PM2 process is broken so I must run `sudo pm2 delete Quasa` and then repeat everything in order to get it to work, so the watch of PM2 does not work anymore with SSR!

I think the issue because Quasar deletes the folder that PM2 watch.

**Comment by rstoenescu** [comment]
Hi,

Stop PM2, build, start PM2 again.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu thank you, but I don't want my website to be down for the building time, because I push a lot of commits per day, so what I did is creating a new folder say `quasar-ssr` then copy the files from `dist/ssr-mat/` to it then run the PM2 commands in this new folder, and programmed my script to do this automatically and now everything is fine.
