### ISSUE TITLE
vue Chrome debugger is disabled by default with quasar dev

### ISSUE THREAD

**Issue by lei-cao** [quasarframework/quasar#2345]
### Software version
    App URL........... http://localhost:8081/
    Dev mode.......... spa
    Quasar theme...... mat
    Quasar CLI........ v0.17.5
    Quasar Framework.. v0.17.4

### What did you get as the error?
![image](https://user-images.githubusercontent.com/136104/43392304-e053acbc-9425-11e8-8cd0-f81632d3fdeb.png)

### What were you expecting?
The vue Chrome debugger should work by default in dev mode.

### What steps did you take, to get the error?
Upgrade from my old project from 0.16 which having vue chrome debugger working.

Not sure if anything need to be done when upgrading.

Cheers,
lei

**Comment by pdanpdan** [comment]
Are you sure you don't have:
`Vue.config.devtools = false` in your code?
How do you start your app in dev mode? You should use `quasar dev`.

**Comment by pdanpdan** [comment]
@lei-cao Can you please provide some more details?

**Comment by rstoenescu** [comment]
`Vue.config.devtools` is automatically set to `true` when on dev mode. So check your code if it overwrites this value.
