### ISSUE TITLE
How to totally block application without boot plugin?

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar#2348]
### Software version

Quasar: v0.17.2
Node: v9.4.0
NPM: 5.6.0

Its not an bug, But i have question after seeing boot plugin that is being deprecated because of preFetch feature.

I know when `preFetch` with **redirect(false)** is called , it aborts the current route navigation.

But i want to abort/block the flow of my application if my user is not authenticated.

This authentication mechanism i was handling with awesome feature called boot, Which was doing whole authentication before calling `new Vue()`

How can i achieve without boot?

There is no meaning to do any async call (which do this authentication) in preFetch, as my `beforeCreate` and `mounted` are being called before `preFetch`.

Can i block `beforeCreate`?

I have tried by returning promise and using async.

Thanks!

**Comment by stgunholy** [comment]
Generally, current way of bootstrapping is pain in the ass for any advanced case. I solved it like this: 
1) bootstrap.js file:
`import environmentsService from "srv/environmentsService";
import authService from "srv/authService";
import startupService from "srv/startupService";

environmentsService.loadEnvironment().then(() => {
    authService.discoverToken();
})
.catch(function (e) {
    console.error(e);
})
.then(function () {
    startupService.init().then(() => {
        console.log("Starting jobpulz app...");
        require("./entry.js");
    });
});
`
Here I am doing all the checks and initializing all services I need BEHOREHAND
2) In quasar.conf.js : 
 extendWebpack(cfg) {
                const fs = require("fs");
                const path = require("path");
                fs.createReadStream("./src/bootstrap.js").pipe(fs.createWriteStream("./.quasar/bootstrap.js"));
                cfg.entry.app[cfg.entry.app.length - 1] = "./.quasar/bootstrap.js";

Really hacky, but does what is needed.

**Comment by rstoenescu** [comment]
The way boot files (previously knows as plugins in 0.17) work in 1.0 should make your scenario possible to totally block app.
