### ISSUE TITLE
Include unit-test and e2e-test config

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#235]
This a feature request. It used to be included in quasar (like the vue boilerplate). As I remember it, it used to work for my setup, but somehow probably because of npm package updates I now get all kinds of errors which I can not seem to get rid of.

**Comment by rstoenescu** [comment]
Please open this ticket for app-template-default repo as requested in Quasar's readme.

Make sure you port your app to webpack 2 setup correctly. It shouldn't give you any errors.

**Comment by musicformellons** [comment]
You're right, should have opened it there... But before I do so, do I understand correctly that you suggest that when I use webpack 2 combined with the karma&nightwatch build scripts that were used before it 'should work'. If yes, i will try before I open a feature request...
