### ISSUE TITLE
Ability to customize entry.js

### ISSUE THREAD

**Issue by tmladek** [quasarframework/quasar#2350]
Hello,
I'm in the process of migrating my project to TypeScript, and as it stands, it demands quite a lot of customization, especially in the creation of the root Vue instance, plugin loading, etc.

Technically speaking, I could manage this with only the "special Boot plugin", but seeing as it is deprecated and will be removed, I don't consider it a viable option.

Being able to specify a path to my custom `entry.js` (or the template it's built from, even) would not break anything else, and allow for more specialized use-cases of Quasar.

**Comment by jayudhandha** [comment]
+1

**Comment by rstoenescu** [comment]
In v1, every boot file (formerly known as app plugin) can be async or stop the app loading procedure (so essentially every boot file can act as the boot plugin in 0.17). Furthermore, there's active development for v1 to support TS out of the box. Keep an eye for TS updates. Thanks.
