### ISSUE TITLE
Add a way to allow 'disableRotRule' for the router

### ISSUE THREAD

**Issue by roccolangeweg** [quasarframework/quasar#2352]
### Software version

Quasar: 16
OS: MacOS
Node: v9.4.0
NPM: 6.1.0
Browsers: Chrome / ALL
iOS: -
Android: -
Any other software related to your bug:

### What did you get as the error?

With the abstraction of webpack config's into quasar.conf.js, there is no option to add webpack rules to `disableDotRule` for the history fallback, this makes it unable to use certain params (such as JWT tokens or e-mailadresses (encoded)) as params.

### What were you expecting?

I'm expecting a file to be available to add the following snippet:
```
app.use(require('connect-history-api-fallback')({
  disableDotRule: true,
  rewrites: [
    {from: /\/app.js/, to: '/app.js'}
  ]
}))
```

### What steps did you take, to get the error?

I tried to apply above script in quasar.conf.js but there is currently no way to get this working.

**Comment by smolinari** [comment]
Not sure if this will help, but have you looked at this?

https://quasar-framework.org/guide/app-quasar.conf.js.html#Extending-Webpack-Config-Object

Scott

**Comment by rstoenescu** [comment]
1. Are you referring to the dev server only?
2. Are you building SSR?

**Comment by roccolangeweg** [comment]
Yeah, it's something I have to apply on the dev server, it's equivalent to the following issue for v0.14:
https://github.com/quasarframework/quasar-template-default/issues/51

Not using SSR.. whenever I $router.push it works, but when I directly go to the URL with a dot in it, it breaks.

**Comment by rstoenescu** [comment]
I'm not sure why nobody reads the Guide > quasar.conf documentation page.
But anyway, the answer to your question: quasar.conf > devServer is equivalent to Webpack's dev-server. More specific to your case: https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback

**Comment by paolodina** [comment]
for reference https://forum.quasar-framework.org/topic/5838/dot-rule-in-vue-router?_=1603982478017

**Comment by renaudham** [comment]
IF somebody still has issue with Quasar and history mode
you need also to check in quasar.conf.js for this
 build: {
      vueRouterMode: 'history', // available values: 'hash', 'history'

For me by default it was on hash, and putting hte router to history was not enough.
