### ISSUE TITLE
[Request] Allow shadow color and elevation to be overridable

### ISSUE THREAD

**Issue by HenriqueSPin** [quasarframework/quasar#2357]
In `src/css/core.variables.styl` the shadow color has a var, but it isn't used in the elevation composition.

```stylus
$shadow-color ?= black
$shadow-transition ?= box-shadow .28s cubic-bezier(.4, 0, .2, 1)
$inset-shadow = 0 7px 9px -7px alpha($shadow-color, .7) inset
$elevation-umbra = rgba(black, .2)
$elevation-penumbra = rgba(black, .14)
$elevation-ambient = rgba(black, .12)
```

I think we could do a little tweak to allow us to override the color and the elevation vars. That should look like:

```stylus
$shadow-color ?= black
$shadow-transition ?= box-shadow .28s cubic-bezier(.4, 0, .2, 1)
$inset-shadow = 0 7px 9px -7px alpha($shadow-color, .7) inset
$elevation-umbra ?= rgba($shadow-color, .2)
$elevation-penumbra ?= rgba($shadow-color, .14)
$elevation-ambient ?= rgba($shadow-color, .12)
```

So users have more possibilities of customization.

**Comment by rstoenescu** [comment]
Available in next Q version (0.17.5)

**Comment by kirinnee** [comment]
How is this done? I can't find any information searching elevation on the documentation :<

**Comment by hawkeye64** [comment]
@kirinnee Look here: https://quasar.dev/style/sass-scss-variables#Quasar%E2%80%99s-CSS and at `Variables list` right below it.

**Comment by kirinnee** [comment]
is there a simpler way to have dynamic shadows?

**Comment by rstoenescu** [comment]
This is already simple...
