### ISSUE TITLE
[Bug] Writing into QAutocomplete with Chromedriver results in no triggered popover

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#2358]
### Software version

Quasar: Quasar v0.17.4
OS: Linux  4.17.9-1-ARCH
Node: v9.11.1
Yarn: 1.7.0
Browsers: Chromium
iOS: - 
Android: -
Any other software related to your bug: ChromeDriver 2.38

### What did you get as the error?

When running integration Tests which utilize ChromeDriver the Popover from the QAutocomplete component does not get triggered when typing into the Input.

This behavior seems not to be entirely reproducible, because during some runs it works as expected on some inputs.

A workaround is to first type something else into the Input and then type the real input.

This happens **only** during automated testing, I could not reproduce this with human input.

### What were you expecting?

That input from ChromeDriver results in the same result as human input.

### What steps did you take, to get the error?

Use ChromeDriver to type into an QAutocomplete.

**Comment by pdanpdan** [comment]
Can you please also show the code (just the input with autocomplete) to see the settings (static or dynamic data, min chars, ...)

**Comment by a47ae** [comment]
Looks like it is already fixed, but still here is one of the inputs :laughing: 
```html
<q-field :error="errors.has(name)" :error-label="errors.first(name)">
    <q-search
      v-model="countryName"
      :name="name"
      :placeholder="placeholderText"
    >
      <q-autocomplete @selected="selected" @search="handleCountrySearch" :debounce="defaultSearchDebounce"/>
    </q-search>
</q-field>
```
