### ISSUE TITLE
Cordova build shows blank page

### ISSUE THREAD

**Issue by obonyojimmy** [quasarframework/quasar#236]
Hi , have being strugling with this issue past 2 days : 

Steps
1.App runs ok on dev with no errors `npm run dev`
2.App is built succesfully with cordova no issues or errors or anything here 
3.Generated Apk shows blank page

Code
Am using vue-router with `beforeEnter` hook which basically checks if a token is set on the session , if not redirects to login module , check sample below : 

```
export default new VueRouter({
  routes: [
    {
        path: '/',
        component: load('index'),
        beforeEnter: guardRoute
    },
  {
        path: '/home',
        component: load('home'),
        beforeEnter: guardRoute
    },
   {
        path: '/login',
        component: load('login')
    },
 ]
}) 

function guardRoute (to, from, next) {
  console.log(SessionStorage.has('token'))
  if (!SessionStorage.has('token')) {
    console.log('not loged')
    next({
      path: '/login',
      query: { redirect: to.fullPath }
    })
  }
}
```

Any ideas , to solve this ?

**Comment by laurentpayot** [comment]
Did you try debugging with Chrome console? http://quasar-framework.org/guide/cordova-wrapper.html#Tips

**Comment by rstoenescu** [comment]
Hi.

There must be an issue with your App. This is more of a question for your own app, so the forum would be a better place to get help. So please do open a thread in forum (http://forum.quasar-framework.org/).

Investigate with Chrome Remote Debugging (@laurentpayot gave you a good link above).

Thanks.

**Comment by obonyojimmy** [comment]
Seems like one of my routes was not configured correctly , fixing the route issue solved my problem
