### ISSUE TITLE
Problems with Min Max DateTime Picker

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#2362]
### Software version

Quasar: 0.17.4
OS: Win 10 Pro
Node: 8.11.3
NPM: 5.6.0
Browsers: Chrome latest
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

The 32nd of July is showing in the Min Max DateTime Picker.
![image](https://user-images.githubusercontent.com/3314957/43483660-85589538-950c-11e8-8da7-576a19422bce.png)

### What were you expecting?

The last date to be the 31st. 

### What steps did you take, to get the error?

Playing with Min Max version of the DateTime Picker in the Playground. 

There are two more quirks with this version of the DateTime Picker. 
1. The months view doesn't show anything, although 3 months should be pickable. 
![image](https://user-images.githubusercontent.com/3314957/43483885-2327d8e6-950d-11e8-9b37-b3ed5f5feec1.png)

2. The year view shows 2017, when it should only show 2018. 
![image](https://user-images.githubusercontent.com/3314957/43483868-0f04a06a-950d-11e8-8b6e-2fd86becfa73.png)

I'm trying to fix these. I've fixed the first issue. I'll work on the others tomorrow. I'm also screwing around with trying to do this suggestion: https://forum.quasar-framework.org/topic/2539/show-only-available-dates-qdatetime-feature-request

Scott

**Comment by smolinari** [comment]
I've gotten the issues mentioned above solved. Well, at least it seems like I have. 😄 

Question. I've also got code mixed in currently for the feature of having an array of available dates to choose from. I am certain I am making a mistake, as I should be doing two different pull requests. One for these issues and one for the added feature. But can I, this one time, do one pull request, once I'm finished with the feature? Pretty please? 😍 

Scott

**Comment by ikromy** [comment]
sorry, this is already merged ?
because version 0.17.8 bugs still there

**Comment by smolinari** [comment]
@ikromy - No, it's not merged yet. It needs a review. 

Scott

**Comment by rstoenescu** [comment]
Any jsfiddle highlight the issue?

**Comment by smolinari** [comment]
Hi Razvan @rstoenescu, 

Here you go: https://jsfiddle.net/smolinari/haoxb2ts/

Click on the month, it should offer August and September.
Click on the year, it shouldn't offer 2017.

Scott
