### ISSUE TITLE
QModal and body prevent scroll

### ISSUE THREAD

**Issue by Valianton** [quasarframework/quasar#2363]
HI there!
Look this: https://codepen.io/Valianton/pen/pZaXBV

Well, when you click on button at the center body - must show QModal and must preventing any wheel scroll on body. And everything works fine, but... 

But, if i add to body a style `overflow-y: auto` wheel preventing ONLY up direction

If add `overflow-y: auto` for body and html all whell preventing not working.

It's a bug or...

**Comment by pdanpdan** [comment]
Why do you want to add `overflow-y: auto`?
It's going to change the way the framework is designed to work.
