### ISSUE TITLE
TypeError: Cannot read property '$on' of undefined in q-ajax-bar

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar#2366]
### Software version

Quasar: v0.17.2
Node: v9.4.0
NPM: 5.6.0

### What did you get as the error?

> Error in mounted hook: "TypeError: Cannot read property '$on' of undefined"

### What were you expecting?
Smooth execution without of App.vue rendering without this error.

### What steps did you take, to get the error?
I am manipulating ajax bar using start/stop event.

**Template:**
`<q-ajax-bar ref="loadingBar" :delay="delay" :speed="speed" :color="color" />`

**Script:**
```
this.$refs.loadingBar.$on('stop', () => {
      console.log("ajax-bar stop");
    });
this.$refs.loadingBar.$on('start', () => {
       console.log("ajax-bar start");
      }
    });
```

This issue is coming after i removed `boot.js` plugin and moved to quasar v17.

Any help?
Thanks!

**Comment by pdanpdan** [comment]
You should first check if the ref is available in your component. So use:
```
if (this.$refs.loadingBar) {
  this.$refs.loadingBar.$on('stop', () => {
    console.log("ajax-bar stop");
  });
}
```

And also check where in the vue lifecycle you're trying to acces it.

But you already have events emitted, so the normal way is:
```
<q-ajax-bar :delay="delay" :speed="speed" :color="color" @start="doSomethingOnStart" @stop="doSomethingOnStop" />
```

**Comment by jayudhandha** [comment]
It works.

Thanks!
