### ISSUE TITLE
Font Awesome Icons Not Centerd in FAB 

### ISSUE THREAD

**Issue by dcantatore** [quasarframework/quasar#2367]
### Software version

Quasar:  0.17.5
Node: 8.11.1
Browsers: Chrome 63

### What did you get as the error?
The font awesome icons do not center when used in FABs

### What were you expecting?
The icons to be centered

### What steps did you take, to get the error?
```
<q-fab
                    icon="fas fa-ellipsis-h"
                    active-icon="fas fa-ellipsis-v"
                    direction="up"
                    outline
>
```

**Comment by pdanpdan** [comment]
Please create a fiddle to show the problem.

**Comment by dcantatore** [comment]
Attached fiddle:

[https://jsfiddle.net/9zb73msg/](https://jsfiddle.net/9zb73msg/)

**Comment by rstoenescu** [comment]
If using UMD, include the style tag for fontawesome before Quasar's one.
If using Quasar CLI, I just tested and it seems fine.

https://jsfiddle.net/rstoenescu/9adLkf8o/

Feel free to reopen if I missed anything.

**Comment by dcantatore** [comment]
@rstoenescu  Thanks for the fast reply.

That solves it if importing as shown in the fiddle. With that in mind I went to my projects main.js file with the imports and moved it to the top. This was from using the cli, here is the code from main.js, might want to have this noted in docs or something along those lines. 

```
import Vue from 'vue';
import App from './App.vue';
import router from './router';

import 'quasar-extras/fontawesome';
import './styles/quasar.styl';
import 'quasar-framework/dist/quasar.ie.polyfills';
import 'quasar-extras/animate';
import 'quasar-extras/roboto-font';
import 'quasar-extras/material-icons';

import Quasar, * as All from 'quasar';

Vue.use(Quasar, {
  components: All,
  directives: All,
  plugins: All,
});
```

also, is there a docs repo anywhere that I can make contributions to?

**Comment by rstoenescu** [comment]
@dcantatore Sure. https://github.com/quasarframework/quasar-framework.org
But you can also edit pages in browser, without the need to fork + clone. Just hit the pencil at top right of pages or the "Edit" link at bottom of pages. Thanks!
