### ISSUE TITLE
q-chat-message XSS vulnerability

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2369]
You can put html inside `:text` which might be users typed content

see here: https://jsfiddle.net/mkce1rfp/138/

**Comment by rstoenescu** [comment]
This is the only component that allows HTML to be rendered. Otherwise it would be a useless component. It's developer's duty to sanitize the params.

**Comment by panstromek** [comment]
Ok, I see, But it should be in the docs. I will PR that
