### ISSUE TITLE
:after icon model is ignored

### ISSUE THREAD

**Issue by darknessm0404** [quasarframework/quasar#2370]
(previous issue was closed however not fixed, for information https://github.com/quasarframework/quasar/issues/2017)

### Software version
Quasar: 0.17.5
OS: All

### CodePen link to reproduce the error
https://codepen.io/Myka_Eyl/pen/mLBvXm
(to reproduce the error, remove the content of the search input, and see that the first icon is shown even if its model is still false)

### What did you get as the error?
 I found an inconsistent behavior of :after class inside "q-search", sometimes (when the input is empty) the content Model is ignored (usually it works one time, then you focus out of the input, and then focus in and the content Model is totally ignored (the icon is shown even if the content model === false)

### What were you expecting?
As stated in the documentation the icon should be hidden if the model == false 

>  // Optional. Show icon button
>   // if model has a value
>   content: Boolean,

### What steps did you take, to get the error?
Show two icons with `:after`, make one bound to a property that is == false and the other == true.
When the search is empty, it will show the first icon even if model value is empty.

**Comment by pdanpdan** [comment]
Each item (object) in the list for `before` and `after` has some boolean properties that determine when to show the icon:

- condition
- content
- error
- warning

The icon is shown when the boolean value is the same with the condition it checks.

So:

- condition = true => visible
- condition = false => hidden

- content = true => visible when field has content (model has content)
- content = false => visible when field has no content (model has no content)

- error = true => visible when field has error
- error = false => visible when field has no error

In your fiddle you have `content: false` so the trash can icon is visible when you have no content in field

**Comment by darknessm0404** [comment]
@pdanpdan thank you **so much** for the explanation !
On the doc there is no mention of the "condition".

I'll add that in the quasar-framework.org repo, where the :after and :before options are available (QSearch, QInput,...)
