### ISSUE TITLE
QAutocomplete does not work properly on latest iOS version when scrolling

### ISSUE THREAD

**Issue by darknessm0404** [quasarframework/quasar#2371]
(previous issue was closed however not fixed in the latest release, ref:  https://github.com/quasarframework/quasar/issues/2125)

Quasar 0.17.5

Reproductible within the [website Quasar Play](https://quasar-framework.org/quasar-play/apple/index.html#/)
quasar-framework 0.17.5
iOS: 11.4.1 (and even with 11.3.1)

What did you get as the error?
No error. The items that autocompletes displays have a wrong offset once you touch and scroll the display of the iOS device.

What were you expecting?
On previous version, the offset was correct (it worked on 0.15 Quasar versions)

What steps did you take, to get the error?
Open anything that uses the autocomplete and displays more than one autocomplete items on an iOS device (you need to have enough items to display so you can scroll) then try to scroll with your finger, and you will see that the offset position of the list of items is bad (it's either going too high or down depending on the scroll movement and the original position)

**Comment by jeremyZX** [comment]
Same issue, iOS 10.3.3.  The initial offset is worse depending on how much of the page has scrolled, so much so that the last autocomplete example renders completely offscreen on iPad.

**Comment by rstoenescu** [comment]
The default UIWebView used on iOS is extremely buggy and Quasar cannot compensate all of webview's faults. This is why it is recommended to replace UIWebView with WKWebView: https://github.com/apache/cordova-plugin-wkwebview-engine (this is only for iOS).

**Comment by jeremyZX** [comment]
I can't speak for @darknessm0404, but this issue isn't limited to apps built with Cordova.  It's apparent while using Safari while visiting the quasar play website.
