### ISSUE TITLE
component not getting rendered in IE11

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar#2374]
### Software version

Quasar: v0.17.5 
Quasar-cli: v0.17.6
Node: v9.4.0
NPM: 5.6.0
Browsers: IE11

### JsFiddle (for Quasar v0.15+ only)
http://jsfiddle.net/eywraw8t/233942/

### What did you get as the error?
No error in console if i run my UI. But if i run this JsFiddle than i am unable to run in IE11 with error 

> SCRIPT5009: 'Cookie' is undefined

> Invalid character at: `#tabs [data-lang="${this.options.name}"]`);t&&!t.classList.contains("modified")&&t.classList.add("modified")`

### What were you expecting?
I should be able to see the toolbar with menu.

### What steps did you take, to get the error?
Just run my code in IE11.

Thanks!

**Comment by jayudhandha** [comment]
Hi,
I have updated quasar-cli to v0.17.7 which says that they have fixed few css isseus in IE11 and its true totally.

But i am facing issue with CSS `min-height` which i set to `auto` for my toolbar.

If i am applying this CSS style then my toolbar is not appearing in IE11, If i remove this css than everything works.

Any help?

Thanks!

**Comment by rstoenescu** [comment]
Hi,

There's so much to comment on your fiddle. I'm sorry, but I'm gonna call it by its name: a mess. You're creating an unnecessary number of DOM nodes and it ends in a CSS spaghetti. Here's why:

1. Are you trying to actually mimic QTabs with QRouteTab?

2. You got:
```html
<q-toolbar class="gt-xs menu-header">
 <div class="row justify-between items-center no-wrap header-container">
```
Why? QToolbar is already a flex row....

3. Then even for that `<div class="row">` you add a child to it with inline-flex (btw, Quasar has `flex inline` CSS helper class), which breaks the reason of existence for the parent...
```html
 <div class="row justify-between items-center no-wrap header-container">
   <div style="display:inline-flex">
```

4. Router-link over div.
```html
<router-link class="menu-link" to="/usermanagement">
  <div class="menu">
    <q-icon name="supervisor_account" />
    <span>User Management</span>
  </div>
</router-link>
```
Why creating an extra DOM node, when you can attach `@click="$router.push('/usermanagement')"` or even:
```html
<router-link tag="div" class="menu-link" to="/usermanagement">
  <q-icon name="supervisor_account" />
  <span>User Management</span>
</router-link>
```

5. You're also reporting an error on Cookies, but it's not used anywhere. Then you're reporting an error on `#tabs [data-lang="...` -- where is this being used / created?

6. I don't see the min-height set anywhere, but why do you set the `min-height` to `auto`? It doesn't makes sense. At least set it to '0' to workaround a known flex bug in IE11: https://github.com/philipwalton/flexbugs#flexbug-3 

Overall, I don't get what you are actually reporting for Quasar and it feels like your proprietary code is not IE compliant, so closing this.
