### ISSUE TITLE
/* rtl:ignore */ not working when building for SSR and Cordova

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2377]
### Software version

Quasar: 0.17.5
OS: Ubuntu 18.04
Node: 10.7.0
NPM: 6.1.0
Browsers: Google Chrome Version 68.0.3440.84 (Official Build) (64-bit)
iOS:
Android: 6.1, 8.0
Any other software related to your bug:
Quasar-CLI: 0.17.6

### What did you get as the error?
No error
### What were you expecting?
I expect `/* rtl:ignore */` to work as expected
### What steps did you take, to get the error?
I use `/* rtl:ignore */` in `app.styl` and in `.vue` files and now it doesn't work properly when I build for SSR or Cordova.

The command that I used to build are:

```
quasar build -m ssr -t mat
quasar build -m cordova -T android
```

**Comment by pdanpdan** [comment]
Did you set build/rtl to true in quasar.conf?

**Comment by MohammedAl-Mahdawi** [comment]
Hi @pdanpdan thank you for your reply, sure, here is the build settings:

```
    build: {
      env: ctx.dev
        ? { // so on dev we'll have
          API: JSON.stringify('http://localhost:3030')
        }
        : { // and on build (production):
          API: JSON.stringify('https://app.romionline.com')
        },
      rtl: true,
      scopeHoisting: true,
      vueRouterMode: 'history',
      // gzip: true,
      // analyze: true,
      // extractCSS: false,
      // useNotifier: false,
      extendWebpack(cfg) {
      }
    }
```

**Comment by rstoenescu** [comment]
@MohammedAl-Mahdawi 

RTL processing is handled by `postcss-rtl` package which uses `rtlcss`.
Here is the usage: https://rtlcss.com/learn/getting-started/why-rtlcss/#processing-directives

If something does not works, please open up a ticket for those packages.

From my own experience, it only works like this (just an example):
```stylus
.top
    left 0 /* rtl:ignore */
    right 0 /* rtl:ignore */
```

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu thank you, so what should I do is create an issue at `postcss-rtl` and telling them that when I `build` in Quasar nothing work but in `dev` everything is fine? and this issue appeared in the latest Quasar updates, because before that everything was fine and they will know the issue?

**Comment by rstoenescu** [comment]
1. They might not be accustomed to Quasar, so they'll probably close it instantly.
2. You might want to try recreating on a barebones repo with a simple webpack setup only, no Quasar. 

Let me know how it goes. Thank you!
