### ISSUE TITLE
Dark Themes

### ISSUE THREAD

**Issue by gizocz** [quasarframework/quasar#238]
It would be nice to have a dark theme version of the default themes.
Thank You.

**Comment by rstoenescu** [comment]
Good idea. Will see about this.

**Comment by smolinari** [comment]
How hard would it be to create something like this? 

https://jqueryui.com/themeroller

I am not asking for it. I'd just like your professional opinion on the amount of effort it would take to make something like it. 

Scott

**Comment by rstoenescu** [comment]
@smolinari It's pretty hard. Would take a huge amount of effort and rethinking of the way themes work..

**Comment by smolinari** [comment]
Hmm.....ok. I guess I'll have to dig into the code to understand the difficulty. Thanks for the answer. 

Scott

**Comment by CookieJon** [comment]
Weird, I just came here to raise an issue suggesting a theme roller, while I remembered.  And it's not even one day after @smolinari had the same idea.  

I was thinking about this last night... it could certainly be a big effort, but I reckon a short-term win would be simply a page like [this one]( http://quasar-framework.org/api/css-stylus-variables.html ) that auto-generates inputs for each variable, and then just update some sample controls on the page and finally spit out raw text for the user can paste into their project.  

Doesn't sound so hard, and I think would be useful, or am I just deluded?!  (Also, I suspect being able to fiddle around with a theme roller is a big selling point... a lot of bang for your buck, as they say)

My 2 cents only. :-)

**Comment by smolinari** [comment]
To be honest, my actual "dream" is a lot farther away. It would be to offer a special menu in the UI (needs a Quasar server of course 😉), and when you open it, you move into "administrative editing mode" (different from content editing). Basically, whatever page the admin is on, with this menu, she would be able to change her app in many different ways. The selections in the sidebar would be "Format", "Style", "Data","Translation", and "Behavior". When a selection is clicked, the page highlights what is editable (with very smalls button next to each component) I could go into more detail, but for this discussion, the "Style" selection would hold the design details. When you click on a component, you get to change it's style like colors, fonts, etc.. Of course, the changes also cascade, or you can define a new class for that component. The changes are then propagated back to the server and are stored. 

This CMS is sort of heading in that direction (but not quite 😉). 

http://demo.getrelax.io/admin/login

username: demo
pass: demo

This CMS is using React. 

Scott

**Comment by smolinari** [comment]
This is a lot more like it! 😄 

https://www.youtube.com/watch?v=O7yHCoyozVk

Scott

**Comment by CookieJon** [comment]
Oh that'd be a fun way to destroy time.

**Comment by smolinari** [comment]
😄 In what way? As a developer developing such a tool or as a user playing around with the style of a site? Or both? 

Scott

**Comment by CookieJon** [comment]
well I was thinking the former, but in fact applies to both i guess.

**Comment by CookieJon** [comment]
FWIW, I;'ve dealt with tonnes of custom-themed jQuery sites, and I've never used the Theme Roller for anything other than mucking around with it to see what it does

**Comment by smolinari** [comment]
Right. A theming tool should be simple, but at the same time offer a "path" to the css. In fact, I believe any tool which allows a novice to alter stuff under the hood, should also lead the way to the actual code being altered and if at all possible, make is a learning experience. Because, no matter what, at some point that person (or someone for them) is going to have to code, to get exactly what he or she wants. 
😄
Scott

**Comment by llin55** [comment]
Is a dark theme somewhere on the roadmap?

**Comment by rstoenescu** [comment]
I can now say: "yes". Quasar will have equivalent dark themes for both Material and iOS themes.

**Comment by rstoenescu** [comment]
Part of the implementation is done in v0.14. There's still a lot to do left, but it's a good start. Check "dark" props in v0.14 beta under forms.

**Comment by aldanor** [comment]
> Quasar will have equivalent dark themes

Wondering if that's still on the roadmap? :)

**Comment by rstoenescu** [comment]
Instead of full-blown themes, Quasar components support "dark" attribute. Cleaner and much more maintainable.

**Comment by eminpala** [comment]
How can we use different theme of Material icons? Such as outlined?

**Comment by smolinari** [comment]
@eminpala - [check the docs](https://quasar-framework.org/guide/introduction-to-quasar.html). Material is one of two themes you can use and it is the standard theme. There is also the possibility of [using different icon sets](https://quasar-framework.org/components/icons.html).

**Comment by rstoenescu** [comment]
@eminpala Google hasn't released the "outline" version in webfont format yet.
