### ISSUE TITLE
[Bug] QSlideTransition not working with <span>

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2385]
If the content is in `<span>` element, it only only appears without animation and then never disappears.

jsfiddle: https://jsfiddle.net/waugrryy/4613/

Checked in devtools and elements are removed from Vue's virtual DOM tree but not from actual DOM.

**Comment by rstoenescu** [comment]
This is a misusage. `<span>` is an inline element. Apply `display: 'inline-block'` or `display: 'block'` to it, otherwise the browser can't animate it.
