### ISSUE TITLE
Fontawesome icons don't fit timeline icons

### ISSUE THREAD

**Issue by dcantatore** [quasarframework/quasar#2386]
### Software version

Quasar: 0.17.5

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/eptb4u5r/

### What were you expecting?
The icons to work like the native ones

**Comment by rstoenescu** [comment]
Fix available in future v0.17.7.

**Comment by rstoenescu** [comment]
Thanks for reporting!
