### ISSUE TITLE
[Material Design] Input fields floating labels with error states should have the default font color

### ISSUE THREAD

**Issue by Billybobbonnet** [quasarframework/quasar#2389]
Hello!

First, congrats for designing such a nice framework. I really like it.

Accordingly to Google implementation of Material Design guidelines, input fields floating labels with error states should have the default font color, the negative color should be displayed only on `:focus` :

![image](https://user-images.githubusercontent.com/8236816/43764944-0e4c7914-9a2f-11e8-832d-76be62dc6118.png)

But it turns out that Quasar makes them red. Shouldn't it be the same than above?

![image](https://user-images.githubusercontent.com/8236816/43764801-bbc84772-9a2e-11e8-8298-bf38f1c06503.png)

**Comment by rstoenescu** [comment]
Hi,

Where does it say that in the Material Guidelines?
PS: Don't pick one of Google's products and assume it's 100% following their Material Guidelines, because I have countless counter-examples on this :)

**Comment by Billybobbonnet** [comment]
@rstoenescu Indeed, they don't say anything about that in the [guidelines](https://material.io/design/components/text-fields.html#anatomy).

I also agree that it can't be taken for granted that all their products follow their Material Guidelines. 

It would then turn out to be a feature request. 

Just to make my point, the error icon behavior is not the same, i.e. it turns grey when the input lose focus. While it makes sense to have the label stay red when the input is filled, It becomes a little "too red" on an empty submit. That's a subjective statement.

Are PR welcome for this?

**Comment by rstoenescu** [comment]
Only problem is that if you use a QInput (without wrapping it in a QField), then if the label isn't red it's very hard to notice the error -- the only marker available remains the red underline which is way too subtle. From a framework perspective, where all use cases must be taken into account, it's best to also show the label in red. I'm afraid you're going to overwrite the CSS in your case if you feel the whole thing is too redish...

Thank you for thinking of proposing a PR though!
