### ISSUE TITLE
[Bug] Select popup changes position when using a filter

### ISSUE THREAD

**Issue by jost-s** [quasarframework/quasar#2393]
### Software 
Quasar: 0.16.4
OS: Windows 8.1
Node: v8.10.0
NPM: v6.2.0
Browsers: Chrome 68.0.3440.84
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
**Select component**: When using a filter/search, with little space in the browser below the component, the selector popup will appear above it. Then, entering characters in the filter and therefore reducing the list, there will be enough space below the component again and the popup will jump down. Deleting the filter will again make it jump up as the list grows larger.

### What were you expecting?
The popup to remain in one place, in this case above the selector.

### What steps did you take, to get the error?
 For an example go to https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/select and scroll to "Filter/Search" so that the component is almost at the bottom of the window with little space below.

**Comment by rstoenescu** [comment]
Hi,

A QPopover is used, which tries to get displayed on the available screen space. If there's enough space at the bottom, it gets shown there, otherwise it tries putting it up. Am I missing something?

**Comment by jost-s** [comment]
You're right, what I find confusing as a user about that behaviour is that especially for long lists the popup jumps from above to below and back. I think it should stay either above or below based on where it was upon opening.
Bringing it up on Discord smolinari considered it a bug and asked me to file it here.

**Comment by nothingismagick** [comment]
Um - is that because it is triggering everything on the page and making a reflow? Or am I not really understanding the issue here?

**Comment by nothingismagick** [comment]
And furthermore, I really wonder if this is actually something that you should consider in your design decision - and not place this element on a page where the mobile user would have issues when the keyboard pops up on their screen

**Comment by rstoenescu** [comment]
1. This is not a bug.
2. The up/down placement needs to remain dynamic. What if user scrolls meanwhile? Shouldn't it reposition the popup? There's many UX details that only work correctly with this current behaviour. This design is solid.

**Comment by jost-s** [comment]
Alright, thanks for clarifying.

**Comment by smolinari** [comment]
Just a suggestion and what I think the improvement would need to be. If the popup goes north of the select, then it would make better UX sense to have the input field for the filter be at the bottom of the pop-up, instead of the top. I looked at the code and realize this isn't easy to implement though. At least not for me. 

😄 

Scott

**Comment by jost-s** [comment]
Yes, that's a good suggestion. The other thing is if, like in the screenshots, there's enough space to keep the popup in the same position where it was, it should stay there, and not by render at the bottom.

**Comment by smolinari** [comment]
@jost-s - I think it would be a wee bit disconcerting for the user to see the selection popup shrink upwards away from the anchor point where the popup was first opened. Just a wee bit maybe. :)

Scott

**Comment by jost-s** [comment]
@smolinari Agreed, that would be strange. I didn't mean the direction in which the the popover should shrink. I'm referring to the popover's position relative to the anchor point. If it's above, stay above if possible, if it's below, stay below if possible.

**Comment by rstoenescu** [comment]
@jost-s will implement your suggestion

**Comment by jost-s** [comment]
@rstoenescu Brilliant, thanks! I look forward to that release

**Comment by smolinari** [comment]
Ahh..Ok. I get what you are saying. And sorry, I didn't notice the drop below the field in either your images nor my playing with the playground. I had scrolled so the field was just above the bottom of my screen, so the selection was always on top. Now I see it drops below the field, if there is enough room. 

Glad Razvan understood. 😄 

Scott
