### ISSUE TITLE
Unable to override color of QRouteTab

### ISSUE THREAD

**Issue by sustained** [quasarframework/quasar#2394]
### Software version

Quasar: 0.17.6
Quasar CLI: 0.17.7
Quasar Extras: 2.0.4
Vue: 2.5.17
Vue Router: 3.0.1
VueX: 3.0.1
Vue CLI: 2.9.6
OS: Fedora 27
Node: 8.10.0
NPM: 5.6.0
Browsers: Chrome 66
iOS: N/A
Android: N/A
Any other software related to your bug: N/A

### CodeSandbox

- [Demo](https://y0z2mz4x99.codesandbox.io/#/issue-2394)
- [Code](https://codesandbox.io/s/y0z2mz4x99?module=src/layouts/issue2394.vue) (line 22)

### What did you get as the error?

Having an odd issue where I can't apply a color override to a `QRouteTab` locally (SPA mode). It works fine with QTab though.

I forked the JSFiddle and the issue doesn't even appear there (same versions)? Odd.

After taking a look at the dev tools, looks like `a.q-link` is overriding `.text-red` because of this rule - `color: inherit !important;`? That doesn't happen on JSFiddle.

### What were you expecting?
 A red `QRouteTab`.

### What steps did you take, to get the error?

1. Create/edit a layout with the structure `q-layout > q-layout-header > q-tabs > q-route-tab`
2. Set the `color` on one of the `QRouteTab`s to `red`.

### Image demonstration

![image](https://user-images.githubusercontent.com/5995080/43814201-fbe254e6-9ac0-11e8-80f1-1a120d1c9e7a.png)

**Comment by sustained** [comment]
Issue demo [here](https://y0z2mz4x99.codesandbox.io/#/issue-2394).
Issue source [here](https://codesandbox.io/s/y0z2mz4x99) (see `src/layouts/Issue2394.vue`, line 22).

**Comment by sustained** [comment]
Issue updated with CodeSandbox demo (unable to reproduce via JSFiddle).

**Comment by rstoenescu** [comment]
Thanks for reporting! Will be available in Quasar v0.17.7.

**Comment by sustained** [comment]
Excellent! :+1:
