### ISSUE TITLE
More flexibility with SSR server generation

### ISSUE THREAD

**Issue by devinholloway** [quasarframework/quasar#2396]
I've started playing around with SSR recently, and so far, I really like it. I would, however, like some additional flexibility with how the server express app gets generated (from quasar build -m ssr). Specifically, I need to integrate it with AWS SAM, which means I need to do the following:

- Modify the package.json. I need to add a couple more npm libs. I've noticed that if I add them to the application's package.json, they get copied over to the SSR's package.json. That works for now, but ideally, I'd prefer to manage the SSR package.json separately. I'd also like to be able to edit the npm scripts section of the SSR package.json. I'm not sure how to do that.

- Add files to the SSR root (dist/ssr-mat).  I see that I can add files to the dist/ssr-mat/server (adding them src-ssr/, but ideally, I'd like to add a couple files (such as a template.yaml) to the dist/ssr-mat.

- Modify files in SSR root. I'd like to be able to change the code in dist/ssr-mat/index.js

I can do what I need without any of these things, but it would make my life easier if some of these items were implemented.

**Comment by rstoenescu** [comment]
Hi,

This is what scripts are for. Let's take this one by one:

1. Make a script file (bash, js for node, whatever fits you best) where you call the Quasar build command then read-edit-write_back package.json. It's easy.

2. With the script above, you can also copy whatever files you need in the root of the distributable folder. My question is why would you need that?

3. Generally speaking, you don't need to edit `dist/ssr-mat/index.js`. If there's something in particular that you want for your ssr server, there's the /src-ssr for it.

Please use the Quasar CLI [repo](https://github.com/quasarframework/quasar-cli) if you want to continue the conversation, or connect with me directly on Discord. Thanks!

**Comment by rstoenescu** [comment]
Will keep this thread in mind for future CLI versions though.
