### ISSUE TITLE
[Request] QCollapsible: Ability to colour arrow_drop_down icon.

### ISSUE THREAD

**Issue by sustained** [quasarframework/quasar#2397]
There is no way to control the colour of the arrow on the right for `QCollapsible`, which would be nice? You can set the `dark` property to make it `#bbb` but that doesn't look good on many background colours and with some colours neither option works.

It would be best if you could simply specify a colour.

I couldn't find any issues nor any google results for this, so opening an issue.

**Comment by rstoenescu** [comment]
Hi,

But you can do this by overriding the CSS. Target the icon. Trying not to bloat the components and keep the footprint low.

-Razvan

**Comment by sustained** [comment]
Okay, if it's possible already then that's great - I'll go over the docs again, thanks.

**Comment by sustained** [comment]
If anyone else ends up finding this via Google and wants to know what to do, there are very specific CSS classes so simply the following works -

```css
i.q-collapsible-toggle-icon {
  color: white;
}
```
