### ISSUE TITLE
Anomalous @change events fired on q-input

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#2398]
### Software version

Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.10.0

Global packages
  NPM                           6.0.1
  yarn                          Not installed
  quasar-cli                    0.17.5
  vue-cli                       2.9.3
  cordova                       Not installed

Important local packages
  quasar-cli                    0.17.5  (Quasar Framework CLI)
  quasar-framework              0.17.4  (Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras                 2.0.4   (Quasar Framework fonts, icons and animations)
  vue                           2.5.16  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.53   (Babel compiler core.)
  webpack                       4.16.3  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.5   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.4.1   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.4.1   (Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)

https://codepen.io/dsl101/pen/QBZXyr

### Desired behaviour
This is actually part of a firebase-backed app, and so the update method actually sends a call to firebase. That's why I'm using `:value` and `@change`. I don't want to fire updates on every keystroke, hence not using `@input`. 

What I would like is for the user to be able to enter text, which is saved on leaving the input field. They also have the option of using a default value by clicking the button.

The use case which doesn't work is if they select all the text, delete it, and then click the `Default` button. This only works _every other time_. It seems the events get out of order somehow.

### Steps to reproduce
1. Select the entire initial text input and type '1', then click `Default` → model is now 'Default'
2. Select the entire 'Default' input and type '2', then click 'Default` → model is now '2' (should be 'Default')
3. Repeat this process typing '3', '4', etc. Every _other_ time, it is correct.

The console output shows that some `@change` events are fired, and some aren't, and when they _are_ fired, they come _after_ the Default `@click` event, which mangles the model.

**Comment by smolinari** [comment]
I see what you are seeing. However, it is clear to me what is happening and I wouldn't call it anomalous. 

In other words, the lazy change to the model is working as expected. However, with your addition of the button to reset the model to "Default", you don't want that lazy change to happen after setting it to Default. 

I'm not sure how to make it work either though. :blush: 

Scott

**Comment by pdanpdan** [comment]
Hi. The @change event is emitted delayed after the @input event is fired in order to wait and check if it needs to be emitted any more. So in your specific case please add a delay before setting the default value on the model in @click.

**Comment by rstoenescu** [comment]
This will be improved in v1.0, but in the meantime, follow @pdanpdan's advice.

**Comment by dsl101** [comment]
I'm always very wary of timing-based fixes, especially in asynchronous code which mine is due to firebase. But I updated the codepen with a workaround. It's horrible but seems to work. I do look forward to something more elegant.

**Comment by dsl101** [comment]
And annoyingly that fix doesn't even work in my situation, because when you include firebase into the equation, the fact the underlying model hasn't changed means firebase doesn't trigger its own update event. In my workaround, it's setting the model to `''` and then to the correct value in the `setTimeout()` callback which trigger the q-input to update its display to what the model contains. But I've no way of doing that when the `q-input` is bound to a Vuex state object which in turn is bound to firebase. All very frustrating.
