### ISSUE TITLE
[Bug?] Unable to use QScreen in computed properties due to it being an Object

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#2399]
### Software version

Quasar: 0.17.7

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/mvqbcs03/

### What did you get as the error?
The `greaterThanSmall` computed property does not update, due to `this.$q.screen.gt` being an object and computed properties not watching for deep nested changes in Objects.

### What were you expecting?
To be able to use QScreen in computed properties

### What steps did you take, to get the error?

Resize the white demo part of the fiddle, you'll see the color of the text change correctly but not the actual value.

**Comment by rstoenescu** [comment]
Thanks for reporting!
