### ISSUE TITLE
[Bug] QSlideTransition not working correctly after fast toggling when using with v-if

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2401]
#### Steps
1. open fiddle
2. click fast on toggle button
#### Expected
Transition should work
#### Actual
Transition doesn't work and its content is visible even when it should be hidden

#### Reproduction link
https://jsfiddle.net/waugrryy/4777/

#### Info
```
Quasar v 0.17.7
```

**Comment by rstoenescu** [comment]
It's still not perfect with v-if when fast toggling for the slide-down animation (starts from scratch), but it's because of how Vue's transition works and this commit is best there can be done. The slide-down works flawless if not fast toggled though, so it's a step into the right direction.

**Comment by panstromek** [comment]
as long as the error state is avoided I think that's ok - some debouncing or delayed execution can be done in userland

**Comment by panstromek** [comment]
or using  v-show

**Comment by panstromek** [comment]
Maybe using some hack like ..

```
<div v-show="showThisSecond">
     <div v-if="showThisFirst">
```

That's an edge case anyway... 
That significant performance improvement is more important then some beauty details IMO
