### ISSUE TITLE
q-input:   1. native 'size' doesn't work 2. 'maxlength' doesn't work with type='number'

### ISSUE THREAD

**Issue by makorne** [quasarframework/quasar#2405]
Good Day,
First off, many thanks to developers for this great framework!

1. Quasar docs say that all DOM attributes that apply to a native input can be used with q-input. However, I cannot limit the visible input box size exactly to a certain number of characters using 'size'. 
2. 'maxlength' property doesn't seem to work for input type 'number', although it works for other types like 'text' or 'tel' Are those 2 bugs or could I be doing smth wrong? 

```
      <q-input 
      v-model="id"
      class="q-display-2 text-center"
      color="green-8"
      maxlength="6"
      inverted
      type="number"
      size="6"
      />
```
Btw, 'text-center' class won't work here either, although it works for a common HTML input.

**Comment by rstoenescu** [comment]
Hi,

From MDN documentation on `<input>`:
> If the value of the type attribute is text, email, search, password, tel, or url, this attribute specifies the maximum number of characters (in Unicode code points) that the user can enter; for other control types, it is ignored.

For input type=number use min and max.

For sizing the input, use CSS and set a width on it.

**Comment by makorne** [comment]
**rstoenescu**, thank you very much! Adding 'width: 7ch'  to input CSS style seems like a working alternative to size="6" property.
