### ISSUE TITLE
Remove (@remove) event not documented in Q-Chips-Input page

### ISSUE THREAD

**Issue by Jasqui** [quasarframework/quasar#2406]
Good Day. 

Just wanted to point out that the event @remove for Q-Chips-Input isn't documented in https://quasar-framework.org/components/chips-input.html#Vue-Events. 

According to the source code it emits this event whenever you remove a chip by either pressing the close button or by deleting with backspace but it isn't anywhere documented on the page I mentioned. 

Thanks in advance and thank you for the awesome framework :)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Added it in docs. Will be visible on next update.
