### ISSUE TITLE
footbar with img always show a gap to bottom

### ISSUE THREAD

**Issue by Zhangshunyao** [quasarframework/quasar#2407]
below is the code

  <q-page-container>
      <router-view/>
    </q-page-container>

    <q-layout-footer>
       <img src="statics/go.gif" @click="zopengo" class="full-width">
    </q-layout-footer>

  </q-layout>

When run it, there is always a gap to the bottom. How to fix it? Many thanks
screenshot can be found in the attachment

[1.zip](https://github.com/quasarframework/quasar/files/2274872/1.zip)

**Comment by rstoenescu** [comment]
Hi, https://dev.to/christiankaindl/the-strange-img-gap-in-html
