### ISSUE TITLE
quasar build error Cannot find module '@babel/runtime/core-js/get-iterator'

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#2408]
Version : quasar-cli 0.17.7

![image](https://user-images.githubusercontent.com/25447231/43941634-793308e0-9ca7-11e8-8cb3-48e4f01c5392.png)

**Comment by rstoenescu** [comment]
Hi,

Can you move this to the appropriate repo pls? https://github.com/quasarframework/quasar-cli
Thank you.
