### ISSUE TITLE
How to simply resize all elements of my app

### ISSUE THREAD

**Issue by Savorld** [quasarframework/quasar#2409]
### Software version

Quasar: 0.17.7

Hi, I found that all the elements of my app are a bit big, I want to scale all the page elements and fonts down, but I don't want to modify the css of the elements one by one, I tried to modify the stylus variable according to the documentation, but it's hard to make them look coordinated, so how can I achieve this in the easiest way?

**Comment by rstoenescu** [comment]
Hi,

Sorry, there is currently no other way other than adjusting them one by one. I might enhance this for v1.0 though.
