### ISSUE TITLE
Data table features

### ISSUE THREAD

**Issue by Vaerum** [quasarframework/quasar#241]
Hi,
like working with quasar and just looked into the new data table component. I'm missing some features before I can migrate to this new data table, therefore I would like to here if they are in the pipeline.

- server side data request.
- - appending parameters (custom filters) to server side.
- export table to CSV or excel.

Best regards,
Rasmus

**Comment by rstoenescu** [comment]
**Exporting to CSV or excel is a good idea and will do it.** Opening a new ticket for this (#244).

Server side request must be managed by the developer. There are multiple reasons for this:
 1. Flexibility. There are multiple ways of doing Ajax requests: through the router hooks for a page, or in page's VM lifecycle hooks, or something else fancy. Don't want to force any of these ways onto the developer.
 2. Code footprint should be as low as possible. Doing server side requests implies writing a home-grown Ajax solution or using an external library (axios, vue-resource, ...) which adds additional dependencies to any app. Also, choosing one external library is also not an option as some developer might want to use X ext lib while others Y ext lib. Forcing a lib limits the options for the developer which is to be avoided.

**Comment by smolinari** [comment]
I have to agree. The server side connectivity within Quasar depends on the server solution. For instance, I'd like to work on a Quasar-GraphQL API solution at some point. That would take Quasar in a totally different direction than someone who wants to use a REST interface. 

@rstoenescu - I would also hope Quasar itself is built in such a way, that any server-side solution can be plugged into Quasar without any bigger difficulties?

Scott

**Comment by rstoenescu** [comment]
@smolinari Yes, of course. This is why I avoided implementing any server-side solution so far. Quasar should be able to work with any server-side solution.

**Comment by hverlin** [comment]
Hi,

Thanks for this nice component.

I don't know if I should open a new issue, but I think that there is a feature that should be added to allow this component to be used with a server. 

Ideally, we there should be: 
- a handler for sorting operations, in order to sort server side
- a handler for filtering, in order to filter server side
- a handler for pagination changed, in order to paginate server side. We should also be able to specify the real number of results for the pagination module.

What do you think? 

(I have used a similar component for angular2 that is doing that http://www.primefaces.org/primeng/#/datatable)

**Comment by rstoenescu** [comment]
@hverlin Hi, no need to open another one. There's one already for this and it's on the roadmap anyway. Thanks for taking time to make the suggestions!

**Comment by pablozabo** [comment]
Hi @rstoenescu, is there a way to handle pagination changed event?

**Comment by pribilinskiy** [comment]
@rstoenescu I can't find it on roadmap. 
We are in the process of selecting a UI framework for a new Vue app and we need "lazy tables". `Vuetify` already has that functionality https://vuetifyjs.com/components/data-tables#api

**Comment by rstoenescu** [comment]
@pribilinskiy DataTables are going to be revamped first thing when I get back from my vacation. There are many github tickets requesting features and all are going to be implemented.

**Comment by r03** [comment]
I also need external pagination. Is this a feature for the near future?

**Comment by smolinari** [comment]
@r03 - The config property array contains pagination controls. See here:

http://quasar-framework.org/components/datatable.html#Config-Property

Scott

**Comment by r03** [comment]
Yes, but I need an event to start an ajax request to get the rest of the data. For me the purpose of pagination is to not request all the data on the first request.

**Comment by smolinari** [comment]
Ah, I see what you mean now. Depends on one's needs I guess. As I see it, currently data table is only built for modest amounts of data, but then it also offers its own filtering of that data set, which is a feature you'd lose with a triggered call for paged data. The data would need to be filtered on the server prior to it being called with a trigger. 

Hmm....interesting dilemma. 

I don't see the current data-table being able to support a server-side pagination. But, that might just be my own inexperience. I'd certainly like to see it possible, especially where the user/ userland could create her/ their own filter criteria to pass to the server. But, that is a totally different "list-view" kind of data-table and it would need to be smartly done, so any server-side client interface (like feathers, meteor or apollo client ) can be used with it. 

Scott

**Comment by r03** [comment]
No problem. I'll keep using Vuetify for the moment then. 
But keep up the good work with Quasar. You have some nice components.

**Comment by 2bj** [comment]
+1

**Comment by creeve** [comment]
+1

**Comment by c0013r** [comment]
+1 for more flexible pagination

**Comment by rstoenescu** [comment]
Flexible pagination in v0.15.
