### ISSUE TITLE
[BUG]Close modal component will focus on button

### ISSUE THREAD

**Issue by Benjaming1312** [quasarframework/quasar#2412]
When I click the button and open modal and close It, It will focus on the button before I clicked.
Please help me, how to fixed it.

![quasr-bug](https://user-images.githubusercontent.com/21982513/43994521-03cf5fc4-9dd1-11e8-8964-e7d4248636cd.gif)

Tooltip, Modal

Quasar: 17.9
OS: MAC
Browsers: Chrome

**Comment by rstoenescu** [comment]
Use the `no-refocus` prop on the Modal.

This is part of the Accessibility, which eases using only keyboard to navigate.
