### ISSUE TITLE
Encounter the issue of flexible not work under card of timeline

### ISSUE THREAD

**Issue by Zhangshunyao** [quasarframework/quasar#2413]
Issue description:
I have user the timeline component and then use a card in it, then in the card-action area, I put two icon with some text, but they just crowded to the left. How to get two div just in the center of the two parts(col-6)
the html can be found in the text file attached
[html code.txt](https://github.com/quasarframework/quasar/files/2280680/html.code.txt)

Below is the screenshot
<img width="318" alt="00" src="https://user-images.githubusercontent.com/33653539/43997787-45e4777c-9e18-11e8-8016-361d814e6375.png">

**Comment by rstoenescu** [comment]
Hi,

Please use our Discord or forum for questions. Thanks.

Making an exception just this once and posting the answer you are looking for: https://jsfiddle.net/rstoenescu/f8guomLn/
