### ISSUE TITLE
Make sure the clearable icon is only showing when there is a selection in QSelect

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#2414]
Reference this issue: #2320 

The clearable icon shouldn't show, when there is nothing selected.

Scott

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Hi, are you sure you are coordinating "clearable" with "clear-value"? "clear-value" is by default [] (for multiple selection) and null for single selection, and is matched against current value to establish if the icon is displayed or not. If you're using a custom value like an empty string ('') and haven't set the clear-value to same thing it obviously won't work.
