### ISSUE TITLE
QModalLayout header - unable to override bg-primary

### ISSUE THREAD

**Issue by FrancescoMussi** [quasarframework/quasar#2416]
### Software version

Quasar: 0.16.0
OS: Mac
Node: 9.4.0
NPM: 6.3.0
Browsers: Chrome

I am unable to override the bg-primary of the header of the QModalLayout.

I have tried several ways:
```
<q-modal-layout header-class="my-custom-class">
<q-modal-layout header-style="background-color: red;">
<q-modal-layout header-class="{'bg-primary': false, 'my-custom-class': true}">
```

But none of them is working. The header show its own default bg-primary.

Do you know why?
I am doing something wrong?

**Comment by rstoenescu** [comment]
Hi,

1. Can you provide a jsFiddle (as it was required when opening a ticket)? I will fork it and show you the answer to your question.
2. Github is reserved exclusively for tickets on bug reports or feature requests. Questions are handled on our Discord server or forum.

Thank you.

**Comment by FrancescoMussi** [comment]
Okay here is the jsFiddle:

https://jsfiddle.net/w35hLmka/8/

As you can see I have set the prop `header-class` of the `q-modal-layout`as shown in the [documentation](https://quasar-framework.org/components/modal.html#QModalLayout) but it doesn't work.

That's why I have opened the ticket. Since I was expecting that it should work as stated in the docs.

**Comment by rstoenescu** [comment]
https://jsfiddle.net/rstoenescu/6rf3s92p/

Emphasis on: 
```html
<q-modal-layout>
    <q-toolbar slot="header" color="red">
```

When you're using a component with color property, don't try to override it.

**Comment by FrancescoMussi** [comment]
Okay thanks for your time.

Just the last thing.

Can you please check this fiddle:

https://jsfiddle.net/ndhe7zm0/

I have tried to create my own custom color by creating these two classes:

```
.text-customblue {
    color: #4680A8;
  }
  .bg-customblue {
    color: #4680A8;
  }
```

and then applying it: `color="customblue"` but it doesn't work

**Comment by rstoenescu** [comment]
```
.bg-customblue {
    background: #4680A8;
  }
```

**Comment by FrancescoMussi** [comment]
Yes I get it :)

But as you can see, I have done it in the Fiddle: https://jsfiddle.net/ndhe7zm0/4/

But the color has not been applies

**Comment by rstoenescu** [comment]
That's a jsfiddle, that's not a vue SFC (single file component)...
Correct fiddle: https://jsfiddle.net/rstoenescu/n9edL1x7/

And you've used `color` CSS prop instead of `background` which is not what I said:
```
.bg-customblue {
    color: #4680A8;
  }
````

**Comment by FrancescoMussi** [comment]
Oh I see.. Stupid mistake that..

Thank you very much!
