### ISSUE TITLE
[Suggestion] Add arrows to the tooltip popup. 

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#2418]
Currently the tooltip looks like this:

![image](https://user-images.githubusercontent.com/3314957/44078967-23b3a0d8-9fa8-11e8-921c-e808eefcf45e.png)

How about it look like this?

![image](https://user-images.githubusercontent.com/3314957/44078930-0b14f59a-9fa8-11e8-9cc8-7b8d86d3914e.png)

Scott

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Duplicate of #2105
