### ISSUE TITLE
[Req] Data Table - Class/Style formatters similar to value formatter

### ISSUE THREAD

**Issue by Async0x42** [quasarframework/quasar#242]
Can support be added for overriding a cell class/style with a function, similar to the value formatter?

Component support is nice, but for simple cases where we just need to modify the background colour based on a cell value, it's overkill.

i.e. 
```
formatClass (value) {
  switch(value) {
    case 'Ready': return 'green';
    default: return 'red';
   }
}
```

 This would be passed the formatted value as a param, and the return value would be appended to the classes/style config option.

**Comment by rstoenescu** [comment]
Will do.

**Comment by rstoenescu** [comment]
Column configuration "style" and "classes" props can now be methods too,
    taking one parameter (value of cell).
    
    Example:
    {
      label: 'Message',
      field: 'message',
      classes (val) {
        return val.charAt(0) === 'L' ? 'bg-red' : 'bg-yellow'
      },
      sort: true,
      width: '500px'
    }

**Comment by robsontenorio** [comment]
Is it possible to override default data table css?
Ex: I cant override <TH> classes by writing custom css (index.html --> app.css)

**Comment by solovieff** [comment]
So, this was removed in v1? ):
