### ISSUE TITLE
Safe Area for iOS when QModal in 'maximized'

### ISSUE THREAD

**Issue by steveclarke** [quasarframework/quasar#2421]
When QModal uses 'maximized' flag with a QModalLayout, it doesn't get top/bottom padding adjusted for iPhoneX. See screen shot. I was able to fix it with:

```
 padding-top: env(safe-area-inset-top)
 padding-bottom: env(safe-area-inset-bottom)
```
But it would be nice for it to work out-of-the-box like other components.

![2018-08-14 at 5 12 pm](https://user-images.githubusercontent.com/1305/44114289-526f7a22-9fe5-11e8-8321-0f5b8f41108f.png)

### Software version

Operating System         	Darwin(17.7.0) - darwin/x64
NodeJs                   	9.11.2

Global packages          	
  NPM                    	6.3.0
  yarn                   	1.9.4
  quasar-cli             	0.17.9
  vue-cli                	2.9.6
  cordova                	8.0.0

Important local packages 	
  quasar-cli             	0.17.9	(Quasar Framework CLI)
  quasar-framework       	0.17.8	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras          	2.0.5	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.16.5	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.5	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.4.1	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.4.1	(Script for registering service worker, with hooks)

Networking               	
  Host                   	mac.local
  en0                    	192.168.77.7

**Comment by rstoenescu** [comment]
Available in future Quasar v0.17.9
