### ISSUE TITLE
Allow manual input for "Datetime Input" component

### ISSUE THREAD

**Issue by chaitanya-plylabs** [quasarframework/quasar#2423]
Currently, there is no provision to enter a date manually, have to incorporate the same.

**Comment by smolinari** [comment]
Do you mean like this?

https://quasar-framework.org/components/datetime-input.html

Scott

**Comment by rstoenescu** [comment]
Hi,

**This is scheduled for v1.0**.

This ticket is duplicate of another one (more complex) -- but don't have time to look for it to post it here.
