### ISSUE TITLE
[Request] Transition handling for QSlider

### ISSUE THREAD

**Issue by postaid** [quasarframework/quasar#2424]
Hi! Can you add a prop for `<q-slider/>` component that handle slider transition?

See, [https://codepen.io/anon/pen/RBmKyd](https://codepen.io/anon/pen/RBmKyd)

**Comment by rstoenescu** [comment]
Hi,

Trying to not bloat components with all kinds of props. If you need something specific, please take a look at Slider's CSS and search for `transition` then override that with your custom one.

Material: https://github.com/quasarframework/quasar/blob/dev/src/components/slider/slider.mat.styl
iOS: https://github.com/quasarframework/quasar/blob/dev/src/components/slider/slider.ios.styl
