### ISSUE TITLE
QAutocomplete bad popover positioning unless static data

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2427]
Hello!

This is based on https://github.com/quasarframework/quasar/issues/2157.

The fix you made works great, but only for static data.

Expected: same fix should be applied to non-static data.

Example: https://jsfiddle.net/waugrryy/5194/ < - type in 1, then 11

Thanks!

**Comment by rstoenescu** [comment]
Will be available in future v0.17.9 (scheduled for this Friday).
