### ISSUE TITLE
Table Scrollable Body, Frozen Column / Rows

### ISSUE THREAD

**Issue by dietrichg** [quasarframework/quasar#2428]
The DataTable component scrolls  the entire grid. It would be nice if like in previous versions we could have frozen rows / columns support. Also the header being separate from the table body would be nice too so that we can scroll and keep the table headers in place.

**Comment by rstoenescu** [comment]
Hi,

This has long been a subject of discussion and I'm not gonna reiterate it over again. Please search the forum for similar requests.

It can now be done by using [position: sticky](https://developer.mozilla.org/en-US/docs/Web/CSS/position) carefully applied to scoped slots or through CSS, targeting the right DOM nodes.
