### ISSUE TITLE
[Request] Ability to get rid completely of rows-per-page-options in QTable.

### ISSUE THREAD

**Issue by HenriqueSPin** [quasarframework/quasar#2429]
Even when an empty array is passed to this prop, the select still renders. Our suggestion is to check if the array has items and hide the control when it's empty or falsie (null, false, 0, []).

**Comment by rstoenescu** [comment]
Hi,

It's where `hide-bottom` Boolean property kicks in to help you. https://quasar-framework.org/components/datatable.html#QTable-Vue-Properties

**Comment by HenriqueSPin** [comment]
Hi Razvan @rstoenescu ! Thank you for the feedback. 

I already do that. But I have to remake the bottom to have the pagination, etc. And all I want is get rid of the rows per page selection. So, even setting an empty array to this prop, the select still renders with no options inside. 

Maybe this makes sense for more devs... or maybe not.

**Comment by rstoenescu** [comment]
@HenriqueSPin So basically you'd expect just "x-y of z" banner? With no QSelect and no navigation buttons, right? It doesn't quite even makes sense to display "x-y of z" banner. More like "z entries" at most. Please make me understand better so I can offer a solution or finally implement one if it turns out it's needed. Thank you.

**Comment by smolinari** [comment]
From what I understand of the request, the rows-per-page selection should not be present, if the userland dev wants all rows to be shown all of the time. 

How about adding a "-1" in the `rows-per-page-options` array to hide the selection and show all rows, all of the time?

Scott

**Comment by rstoenescu** [comment]
@HenriqueSPin Tomorrow (August 23rd) I'm gonna do a release on Quasar and I'd like to solve your issue too until then. Can you take a look at my question above please? Contact me on Discord to speed things up. Thank you.

**Comment by smolinari** [comment]
I'd like to change my idea above. Instead of a "-1", the logic is if there is only one number (not 0) in the `rows-per-page-options` array, then that means there shouldn't be the selection for the user and the number of rows to be shown is limited by that number. If there is more than one number, then the selection should be shown. 

Scott

**Comment by HenriqueSPin** [comment]
I'm so sorry @rstoenescu. I was completely offline in the last two days with personal health problems. Thats right: No QSelect. But... the page navigation needs to be there. 

@smolinari Theres one thing: The number of rows per page (that controls the quantity of rows that are shown in the table) ad the OPTION (rows-per-page-options) that allows the user to change the first one. Sometimes, we don't want this possibility.

**Comment by smolinari** [comment]
Yeah. How about this? If just one number is in the `rows-per-page-options` array it basically is saying to Quasar, this is the _only_ number of rows to show and thus the "Records per Page" selection should be hidden too. 

Scott

**Comment by HenriqueSPin** [comment]
Thank you @smolinari. But the pagination object already holds this info:

```javascript
pagination: {
      sortBy: null, // String, column "name" property value
      descending: false,
      page: 1,
      rowsPerPage: 5 // current rows per page being displayed
    }
```

**Comment by smolinari** [comment]
Ok. Then then `rows-per-page-options` array just needs to be empty.

Scott

**Comment by rstoenescu** [comment]
It will work by specifying: `:rows-per-page-options="[]"` in future Quasar v0.17.11.

**Comment by smolinari** [comment]
I've also added a PR for the docs to note the change.

Scott
