### ISSUE TITLE
DataTable - Firefox issue

### ISSUE THREAD

**Issue by maced0n** [quasarframework/quasar#243]
If any of the following Configuration values is set to some parameter other than None the DataTable layout is broken
Selection  | Left Sticky Columns | Right Sticky Colums

Browser: latest Firefox 50
OS: Linux
Reproduce: Open [the documentation ](http://quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/data-table) with Firefox in desktop view.

![dtff](https://cloud.githubusercontent.com/assets/817544/21091254/4c696a1a-c045-11e6-9328-2af64cc17642.jpg)

**Comment by rstoenescu** [comment]
Confirmed. Will fix it.
