### ISSUE TITLE
Use htmlWebpackPlugin to add metas in index.template in Quasar 0.17

### ISSUE THREAD

**Issue by sbstnplcn** [quasarframework/quasar#2430]
Hi !
before, great framework, thanks to you to develop quasar.

I need to add special meta to my app, with environment variable. 
With quasar 0.15 i use :
```
pwa: {
     manifest: {
        companyName: 'test name'
    }
}
```
```
<title><%= htmlWebpackPlugin.options.pwaManifest.companyName %></title>
```
And it working well.

But since I update to Quasar 0.17, I have "cannot read companyName of undefined"
I try to use something like that : 
```
<title><%= htmlWebpackPlugin.options.companyName %></title>
```
with that config in quasar.conf.js
```
extendWebpack (cfg) {
        cfg.companyName = 'test name'
}
```
but it's not working... 

Have you any idea how i can do that ?

Thanks

**Comment by rstoenescu** [comment]
Hi,

1. This should have been reported to the CLI repo.
2. Will be available in CLI v0.17.10 through quasar.conf > htmlVariables: { ... } -- scheduled to be released today.

Thanks for reporting.

**Comment by sbstnplcn** [comment]
Thanks for your response.

I have to add it like that ?
```
cfg.htmlVariables = {
        title: 'test name'
}
```
When i do that, impossible to build project with Quasar 17.11
Thanks

**Comment by rstoenescu** [comment]
```js
// quasar.conf
module.exports = function (ctx) {
  return {
    htmlVariables: { title: 'test name' }
```

```
// src/index.template.html
<title><%= htmlWebpackPlugin.options.title %></title>
```

What config were you adding htmlVariables to?

**Comment by sbstnplcn** [comment]
Working ! thanks a lot ;)
