### ISSUE TITLE
miss in icons/fontawesome.js

### ISSUE THREAD

**Issue by evemarco** [quasarframework/quasar#2431]
in file icons/fontawesome.js, there is an error.

Line 135 :

  table: {
    arrowUp: 'fas fa-long-arrow-up',

must be corrected to

  table: {
    arrowUp: 'fas fa-long-arrow-alt-up',

You can check free fontawesome here :
https://fontawesome.com/icons?d=gallery&q=long%20arrow

**Comment by rstoenescu** [comment]
Thanks for reporting! Fix will be available shortly in Quasar v0.17.9.
