### ISSUE TITLE
Autocomplete not working with QInput

### ISSUE THREAD

**Issue by hkizilhan** [quasarframework/quasar#2434]
### Software version

Quasar: 0.17.9     UMD  / Standalone mode
Browsers: Firefox 61, Chromium 68

### Codepen link
https://codepen.io/hakan486/pen/xaKrbb

### What did you get as the error?
Autocomplete not working with QInput
Probably related with https://github.com/quasarframework/quasar/issues/1370

Browser console says:
```
[Vue warn]: Error in nextTick: "TypeError: t.inputEl is undefined"

found in

---> <QAutocomplete>
       <QInputFrame>
         <QInput>
           <QTabPane>
             <QTabs>
               <QPageContainer>
                 <QLayout>
                   <Root>
```

### What were you expecting?
Working Autocomplete

### What steps did you take, to get the error?
Get sample Autocomplete code from documentation.

**Comment by rstoenescu** [comment]
Hi,

This works. Cannot reproduce your error.
Although, taking it a bit further, your static data does not contain "value" props, which makes the input get emptied on any selection.

**Comment by hkizilhan** [comment]
"value" did the trick, thanks...
