### ISSUE TITLE
QCard border is clipped when inside a QField

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#2446]
### Software version

$ quasar info

Operating System                Darwin(17.7.0) - darwin/x64
NodeJs                          10.7.0

Global packages                 
  NPM                           6.2.0
  yarn                          1.9.2
  quasar-cli                    0.17.11
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages        
  quasar-cli                    0.17.11 (Quasar Framework CLI)
  quasar-framework              0.17.9  (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.5   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.16.5  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.5   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.4.1   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.4.1   (Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)
https://codepen.io/tomers-the-encoder/pen/gdbJOZ

### What did you get as the error?
The card shadow in its lower part is clipped

### What were you expecting?
I expect to see the card's shadow

### What steps did you take, to get the error?
Put QCard inside QField.
When there is any other object after the QCard, its shadow shows correctly.

**Comment by pdanpdan** [comment]
Either wrap the QCard in a <div> with padding or add a margin to QCard.

**Comment by rstoenescu** [comment]
Or `<q-card class="q-ma-xs">`.
