### ISSUE TITLE
<q-input type="textarea"> inside <q-field> not auto-grow in IE11

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#2447]
### Software version
Quasar Framework: v0.17.9
Quasar CLI: v0.17.11
OS: Windows 7
Node: v10.8.0
NPM:
Browsers: IE11
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
JsFiddle not working in IE11 so I pasted the Vue code here:
```
<template>
  <q-field label='label' >
    <q-input type="textarea" v-model="value"></q-input>
  </q-field>
</template>

<script>
export default {
  name: 'page-test',
  data () {
    return {
      value: 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'
    }
  },
}
</script>
```

### What did you get as the error?
<q-input type="textarea"> inside <q-field> does not auto-grow in IE11. When the text is long, there will be a horizontal scroll bar blocking the input area. No issue in Chrome.

![image](https://user-images.githubusercontent.com/5996531/44468734-e7d60900-a5f3-11e8-940b-d2b6c1be931c.png)

### What were you expecting?
It should auto-grow

### What steps did you take, to get the error?
Type in long text in q-input

**Comment by pdanpdan** [comment]
I just checked and it looks fine. Can you check if you have IE compatibility flat turned on in quasar.conf?

**Comment by pdanpdan** [comment]
Sorry, I was testing it on the current branch, not on the released one. It's fixed by Razvan and it will be available in the next release.

**Comment by topvis** [comment]
Thanks.
