### ISSUE TITLE
event or method to trigger for adding new item on list on Chips Input with Autocomplete

### ISSUE THREAD

**Issue by rlynjb** [quasarframework/quasar#2448]
Hi all,
I went through the quasar documentation regarding chips input field with autocompletion. This component works perfectly fine. it provides vue methods i can use to add, remove, clear, reset items, but it seems to lack an event/method for triggering the Add icon for when adding a new item on the list.

https://quasar-framework.org/components/chips-input.html

So my question is, is there an event for this trigger? i might have probably just missed it.. if not.. this would be a good feature to add on this component.

Thank you

### Software version

Quasar: 0.17
OS: mac
Node: 10.8.0
NPM:6.2.0
Browsers: chrome
iOS: -
Android: -

**Comment by rstoenescu** [comment]
It's `@add(val)` -- added it to the docs, it was missing.
