### ISSUE TITLE
Extend icons + support other icon libs

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#245]
There's an extended list of Material Icons that should replace current lib: https://materialdesignicons.com/. That's just for starters. Support for Font-Awesome etc will be added too.

**Comment by murbanowicz** [comment]
Font Awesome is best choice I think. In my opinion it fits perfectly fine with Material Design

**Comment by nerijunior** [comment]
Or a simple way to create a icon resource.

**Comment by murbanowicz** [comment]
any progress? 
we are missing icon sizing as well

**Comment by rstoenescu** [comment]
Icon sizing is done through font-size.

**Comment by spectrolite** [comment]
Is there still something on the roadmap here? It seems the current quasar-extras covers this issue pretty well.

**Comment by rstoenescu** [comment]
Already in v0.14. Closing this.
