### ISSUE TITLE
Element in QModal doesn't scroll horizontally

### ISSUE THREAD

**Issue by kkojaeh** [quasarframework/quasar#2450]
### Software version

Quasar: 0.17.9
OS: Darwin(17.7.0) - darwin/x64
Node: 9.6.1
NPM: 6.4.0
Browsers: Chrome
iOS:
Android:

Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://codepen.io/kkojaeh/pen/LJVOyo
### What did you get as the error?

Horizontally long elements in the modal can not scroll horizontally.

### What were you expecting?

I expect to expose `src/utils/prevent-scroll.js` file or consider horizontal scrolling in the` shouldPreventScroll `function

**Comment by kkojaeh** [comment]
It's fine in Windows OS, but it's not possible mouse wheel scroll.
Scrollbar is not visible in OSX OS.

- OSX 
  - Safari : invisible scrollbar, mouse wheel scroll(X) 
  - Chrome : invisible scrollbar, mouse wheel scroll(X)
- Windows
  - Edge :  visible scrollbar, mouse wheel scroll(X)  
  - Chrome : visible scrollbar, mouse wheel scroll(X)

**Comment by rstoenescu** [comment]
Fix available in future Quasar v0.17.11
