### ISSUE TITLE
Flexbox row doesn't collapse properly after v0.17

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2453]
Hello!

This has been working ok until v0.17. Steps to reproduce:
1) add a container with `.row` class
2) add two children with `.col-sm-6`
3) narrow the window down
4) children width is of the size of the content

Expected: children should have full width.

Example v0.16: https://jsfiddle.net/waugrryy/5818/ <- works as expected
Example v0.17: https://jsfiddle.net/waugrryy/5819/ <- works incorrect

Thanks!

**Comment by pdanpdan** [comment]
`.col-sm-6` means from `sm` upwards make it 50%
But there is no specification on what to do when below `sm`.
You should add a `col-12` if you want it full-with below - the behavior in 0.16 was inconsistent, as it can be seen in https://jsfiddle.net/hf4qbcdw/2/ (below breakpoint the 2 rows should have been identical)

**Comment by jean-moldovan** [comment]
Seems like a small breaking change to me, but I'm ok with it. Feel free to close the issue if you say this is the correct behaviour from now on.

Thanks!

**Comment by rstoenescu** [comment]
It's no breaking change. It always was this way.
