### ISSUE TITLE
vue-cli v3.0 SSR document is not defined if --mode=production

### ISSUE THREAD

**Issue by luozhihua** [quasarframework/quasar#2454]
I'm try to add quasar-framework to a project that using typescript and created by vue-cli 3.0; Every things is ok now, but `mode=production` has some problem;

production mode built successfully, and run `node server.js --port=9999` also successfully,

When I browse url `localhost:9999`, `server.js` threw out an error:
```
ReferenceError: document is not defined
server.js:96
    at js/main.9de4b3dd.js:1:775
```

vue-cli: 3.0
vue: 2.5.17
Quasar: 0.17.9
OS: Mac 10.14 beta
Node: 10.8.0
NPM: 6.2.0

**Comment by rstoenescu** [comment]
Please redirect this to the appropriate repo: https://github.com/quasarframework/vue-cli-plugin-quasar -- note that for the SSR experience it is recommended you use Quasar CLI.

Also fill more info. Having an error at `js/main.9de4b3dd.js:1:775` is not helping at all. What options did you choose when creating your Vue app, then what vue cli plugins did you add to your project?
