### ISSUE TITLE
Add capability to control options labels display in QSelect

### ISSUE THREAD

**Issue by genyded** [quasarframework/quasar#2455]
n earlier versions of Quasar, html entities used to work as part of an options label for QSelect options, but that is not longer the case. There needs to be a way to support odd characters and/or “bold”, indentation, or whatever dynamically on options in QSelect. 

BTW - all of this can be done with a standard html select:
```
<select>
  <option value="volvo" disabled>Volvo</option>
  <option value="saab">&nbsp;&nbsp;Saab</option>
  <option value="vw">VW&#x00B3;</option>
  <option value="audi" style="font-weight: bold;">Audi</option>
</select>
```

**Comment by panstromek** [comment]
Please include jsfiddle to demonstrate the issue. you can fork this https://jsfiddle.net/waugrryy

**Comment by genyded** [comment]
This is a feature request, so there is no issue to demonstrate and we cannot fiddle something that does not yet exist.

**Comment by rstoenescu** [comment]
Hi,

* Duplicate of https://github.com/quasarframework/quasar/issues/2011
* This is due to our concern on XSS attacks. HTML content is no longer allowed.

**Comment by panstromek** [comment]
@genyded Sorry for misunderstanding

**Comment by genyded** [comment]
The options labels are under the complete control of the application/developer and as such XSS should not be a concern (much like Vue's v-html directive). We've invested heavily in Quasar and would hate to have to abandon it or bring in another framework just for this, but we cannot meet our clients requirements without this. I'll have to meet with the team and decide on the best course of action. Just about every other Select component out there supports this including Vuetify.

**Comment by nothingismagick** [comment]
@genyded - this has been added to the milestones for 1.0 - no need to be concerned. We will get to it ASAP

**Comment by rstoenescu** [comment]
@genyded Added back the ability to render HTML to the QSelect. Please be careful sanitizing the labels. Will be available in v0.17.10 (to be released in a few hours).

**Comment by genyded** [comment]
Thanks! And yes we'll sanitize if we let user append values, bu so far we do not.

**Comment by rstoenescu** [comment]
Please consider visiting our [Patreon campaign](https://www.patreon.com/quasarframework) if you haven't already. It would really help us. Thanks.
