### ISSUE TITLE
Sorting Boolean Values in the QTable Component

### ISSUE THREAD

**Issue by mmport80** [quasarframework/quasar#2460]
Sorting a column containing boolean values does not work out of the box.

adding a sort method to the column definition fixes this, e.g.:

`sort: (a, b) => a -b,`

**Comment by rstoenescu** [comment]
It does work. Both values have to be Booleans. Is one of them undefined?

**Comment by mmport80** [comment]
FYI, I checked each value, in case one wasn't a Boolean, and all were Booleans.. But maybe I am missing something!

**Comment by andreyakuf** [comment]
I have same issue. All values are Booleans
this change solved it
if (typeof A === ‘boolean’ && typeof B === ‘boolean’) {
return (( A === B ) ? 0 : A ? -1 : 1) * dir
}
