### ISSUE TITLE
enhancement: add prop to q-select to hide or change arrow 

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#2465]
in readonly state the q-select is showing the arrow. it would be nice to have a prop to hide it. this can be done by accepting an empty string as icon. this way the prop can also be used to have a custom icon.

**Comment by smolinari** [comment]
Hi @kasperfish, 

When we discussed this, the idea was just to hide the arrow icon, when in read only mode. Adding another icon is actually possible already with the `after` prop. 

I've got both working too. PR is done. :smile: 

Now to see if the maestro also agrees with this change. 😊  

Scott

**Comment by kasperfish** [comment]
thanks, I hope it will be merged.

**Comment by HenriqueSPin** [comment]
#2420 is similar
