### ISSUE TITLE
Error using meta: bodyAttr

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#2467]
### Software version

Quasar: ^0.17.0
OS: Ubuntu 16.04
Node: 8.11.3
NPM: 5.6.0
Browsers: Chrome 68.0.3440.106

Trying to use the Meta plugin with bodyAttr:

### What did you get as the error?

`<body class="mat desktop no-touch platform-mat" %%Q_BODY_ATTRS%%>%%Q_BODY_TAGS%%`

Uncaught TypeError: Cannot read property 'remove' of null
    at VueComponent.updateClient (meta.js?4293:150)

### What were you expecting?

`<body class="mat desktop no-touch platform-mat has-navbar-fixed-top">`

### What steps did you take, to get the error?

    meta: {
      bodyAttr: {
        class: 'has-navbar-fixed-top'
      }
    }

**Comment by smolinari** [comment]
Hi,

From what I understand of the newest meta plugin code, it is actually designed [with a filter to avoid what you are expecting] (https://github.com/quasarframework/quasar/blob/739cb82bd4f86c707bdf61a890199a5765955235/src/plugins/meta.js#L43).

I've tested with the newest version in both SPA and SSR modes and neither cause this error. So, I can only explain the error you are getting being possibly from an older version of 0.17. The filter was added at a later point.

Scott

**Comment by devinholloway** [comment]
I just installed quasar yesterday, so I'm not sure how it could be out of date. Running 'quasar info' I get this.

`Operating System                Linux(4.15.0-33-generic) - linux/x64
NodeJs                          8.11.3

Global packages                 
  NPM                           5.6.0
  yarn                          Not installed
  quasar-cli                    0.17.13
  vue-cli                       3.0.0
  cordova                       Not installed

Important local packages        
  quasar-cli                    0.17.13 (Quasar Framework CLI)
  quasar-framework              0.17.10 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.6   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.16.5  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.5   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.4.1   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.4.1   (Script for registering service worker, with hooks)

Networking                      
  Host                          devin-Precision-5520-Anniversy
  wlp2s0                        192.168.0.85
  enx1065308e216e               192.168.0.83
`

**Comment by devinholloway** [comment]
I put the meta plugin back in to see if I could reproduce the error, and now it seems like the bodyAttr doesn't function at all.

`    meta: {
      htmlAttr: {
        class: 'test'
      },
      title: 'This is a test',
      bodyAttr: {
        class: 'has-navbar-fixed-top'
      }
    },`

The htmlAttr and title are working just fine, but my body tag is rendered as:
`<body class="mat desktop no-touch platform-mat" >` (missing 'has-navbar-fixed-top' class)

So... I'm not sure what's going on.

**Comment by smolinari** [comment]
Try doing something else, like 

```
bodyAttr: {
  some: 'value'
}

And see if `some="value"` is injected into the `body` tag. `class` and `style` are specifically filtered out to not be injected.

Scott

**Comment by devinholloway** [comment]
You're right. bodyAttr: {some: 'value'} works fine. Since this was designed to specifically to filter out class/style, would it be worth making an enhancement request to change that?  I've noticed that if I add a class to the index.template.html, it works. The end result is my class plus the other that get injected by quasar. However, in my use case, I only want a special class injected for certain routes (I'm doing SSR), so modifying index.template.html isn't a very good solution.

**Comment by smolinari** [comment]
Well, at first I thought with SSR, that style and class attributes could be "injectable". I'll speak with Razvan about what was the actual design decision and get back to you. 

Scott

**Comment by rstoenescu** [comment]
Is this still valid with latest?
