### ISSUE TITLE
[REQUEST] Please add "filter-method" into q-select with filter

### ISSUE THREAD

**Issue by leopradac** [quasarframework/quasar#2468]
Hi eveyone, I am using q-select component and i'd like to import data from server so everytime user type into searchbox it makes a ajax call and receive the filtered selectable list. I don't know if there's a way to achieve it right know, if there is i'd appretiate any help.

However would be great adding this filter-method as prop, q-table already has it.

**Comment by smolinari** [comment]
I believe this is similar to: https://github.com/quasarframework/quasar/issues/2435

Scott

**Comment by rstoenescu** [comment]
Hi,

`filter` prop can be a Function too. Example:

```js
// <q-select :filter="myFilter" ....

function myFilter (terms, obj) {
  return obj.label.toLowerCase().indexOf(terms) > -1
}
```

Updated docs.

**Comment by leopradac** [comment]
@rstoenescu thank you for answering, I hadn't noticed it was possible, even though I tested it and don't gives the option of modifying the complete method, just lets modify the rule inside an already running bucle of an already formed array. As i said i was expecting to make an ajax call THEN filter the response and return the filtered object. Do you know any way to achieve it?

**Comment by botura** [comment]
I also miss this function in q-select. Would be very usefull if implemented!

**Comment by yaliv** [comment]
I have an example here: https://github.com/quasarframework/quasar/issues/943#issuecomment-429610400
