### ISSUE TITLE
Installation error:       command failed: yarn

### ISSUE THREAD

**Issue by stlbucket** [quasarframework/quasar#2470]
vue add quasar

📦  Installing vue-cli-plugin-quasar...

yarn add v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-quasar@0.17.0
info All dependencies
└─ vue-cli-plugin-quasar@0.17.0
✨  Done in 3.65s.
✔  Successfully installed plugin: vue-cli-plugin-quasar

? Select Quasar Theme: Material Design
? Allow Quasar to replace App.vue, About.vue, Home.vue and (if available) router.js? Yes
? Import all Quasar components, directives and plugins? No
? Use RTL support? No
? Choose Icon Set Material Icons
? Quasar i18n lang - one from https://github.com/quasarframework/quasar/tree/dev/i18n en-us
? Select features: Animations, Material Icons

🚀  Invoking generator for vue-cli-plugin-quasar...
📦  Installing additional dependencies...

yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error quasar-framework@0.17.10: The engine "yarn" is incompatible with this module. Expected version ">= 1.6.0".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/Users/buckfactor/bucketco/philede/philede-web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn

**Comment by rstoenescu** [comment]
Hi,

So these lines don't ring any bells? :)
```
yarn add v1.5.1
...
error... The engine "yarn" is incompatible with this module. ****Expected version ">= 1.6.0"****.
```

Upgrade your yarn :)
