### ISSUE TITLE
q-popover @show & @hide events trigger 2 times

### ISSUE THREAD

**Issue by Mohanrau** [quasarframework/quasar#2473]
### Software version

Quasar: v0.17.10
OS:
Node:
NPM: latest
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
q-popover @show & @hide events trigger 2 times after latest update

### What were you expecting?
single trigger
### What steps did you take, to get the error?
**HTML**
```
<q-popover
            :disable="filterData.countryID < 1"
            @show="toggleIBOSearchPopoverSection(toggleMainPageDim)"
             @hide="toggleIBOSearchPopoverSection(toggleMainPageDim)"
             ref="popover"
             anchor="bottom right"
             self="top right"
             fit>
</q-popover>
```

**FUNCTION**
```
toggleIBOSearchPopoverSection(x) {
        if (x) {
          console.log('@show event triggered')
        } else {
          console.log('@close event triggered')
        }
        this.toggleMainPageDim = !x
      }
```
**IMAGE**
![q-popover](https://user-images.githubusercontent.com/1044660/44639991-8c3fbd00-a9f1-11e8-8051-e4b19a82f6ac.PNG)

**Comment by smolinari** [comment]
Confirmed. 

https://jsfiddle.net/gbn79qa1/

The promises in togglemixin for `show` and `hide` are triggering the show and hide events a second time. Testing, I commented the two lines out and the popover still works. I am uncertain of any secondary unwanted effects of doing this at this point.

I also noticed the toggle function doesn't seem to be working as (I think) it should. It toggles the popover to show, but it doesn't allow it to hide like with QTooltip. So in general, I think there seems to be some sort of mixup in the logic for QPopover. 

Scott

**Comment by pdanpdan** [comment]
The duplicate event it's going to be removed, thanks for spotting.

@smolinari 
The reason for toggle not working is simple: when you click on the toggle button the popover starts to hide, and then the toggle sends the command to toggle, so the popover shows again.
In this case you should use `persistent` prop on q-popover like in https://jsfiddle.net/2hujktwr/2/

**Comment by smolinari** [comment]
@pdanpdan 

Hey Dan. 

Thanks for the explanation. I appreciate it. I see it was the emits in the component itself that were one too many. Cool.  :sunglasses: 

Also on the toggle. Makes sense. I was almost certain I was missing something and `persistent` was it. Maybe add `persistent` [to the the example](https://github.com/quasarframework/quasar/blob/9da4a4d38ec2e96f10ef7a43481584a08719ff01/dev/components/components/popover.vue#L13) in the `dev/popover.vue`?

Scott
