### ISSUE TITLE
Broken animations on selection of q-tree node

### ISSUE THREAD

**Issue by altShiftDev** [quasarframework/quasar#2475]
### Software version
Operating System        	Darwin(16.7.0) - darwin/x64
NodeJs                  	9.8.0

Global packages
  NPM                   	6.4.0
  yarn                  	1.9.2
  quasar-cli            	0.16.4
  vue-cli               	2.9.6
  cordova               	8.0.0

Important local packages
  quasar-cli            	0.16.4	(Quasar Framework CLI)
  quasar-framework      	0.16.0	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras         	2.0.2	(Quasar Framework fonts, icons and i18n.)
  vue                   	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router            	3.0.1	(Official router for Vue.js 2)
  vuex                  	3.0.1	(state management for Vue.js)
  electron              	2.0.0	(Build cross platform desktop apps with JavaScript, HTML, and CSS)
  electron-packager     	12.1.0	(Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI)
  electron-builder      	20.25.0	(A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box)
  @babel/core           	7.0.0-beta.49	(Babel compiler core.)
  webpack               	4.9.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server    	3.1.4	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin	3.2.0	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/Lc0hs73o/6/

### What did you get as the error?
Odd animation on selection applies a fully opaque box animation temporarily using the color selected in the color attribute. See video here: https://gfycat.com/LeanInconsequentialFallowdeer

### What were you expecting?
A more subtle animation such as a ripple.

### What steps did you take, to get the error?
Error seems to not be present in the latest versions of firefox, safari or opera but is present in chrome (latest).
```
          <q-tree
            default-expand-all
            :expanded.sync="propsExpanded"
            :nodes="profiles"
            color="secondary"
            :selected.sync="selected"
            node-key="label">
            <div slot="default-header" slot-scope="prop">
              <span class="capitalize">{{ prop.node.label }}</span>
            </div>
          </q-tree>
```

**Comment by rstoenescu** [comment]
Are you sure it's not your GPU at fault here? Can't reproduce your issue. The effect IS a ripple, but yours looks like GPU is not doing it right.

**Comment by altShiftDev** [comment]
I disabled hardware acceleration in chrome and it stopped, odd. I don't have another Macbook to test on but I'd be surprised if I was the only one affected by this, my setup isn't unique and I'm using modern hardware with the latest software versions.

**Comment by rstoenescu** [comment]
It's pretty straightforward CSS. I'm on a Mac too. Asked around, nobody can reproduce this...

**Comment by altShiftDev** [comment]
Just found out what this was. I had my q-tree in a q-card and the card had the class "fixed-center" which apparently causes all kinds of instabilities for animations in child components.

By removing the "fixed-center" class animations stabilized. Others were getting the glitches too but this solved the issue completely.

**Comment by rstoenescu** [comment]
Glad it's working for you now.
