### ISSUE TITLE
Request: Improve selection of nodes in the q-tree component

### ISSUE THREAD

**Issue by altShiftDev** [quasarframework/quasar#2476]
### Software version
Operating System        	Darwin(16.7.0) - darwin/x64
NodeJs                  	9.8.0

Global packages
  NPM                   	6.4.0
  yarn                  	1.9.2
  quasar-cli            	0.16.4
  vue-cli               	2.9.6
  cordova               	8.0.0

Important local packages
  quasar-cli            	0.16.4	(Quasar Framework CLI)
  quasar-framework      	0.16.0	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras         	2.0.2	(Quasar Framework fonts, icons and i18n.)
  vue                   	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router            	3.0.1	(Official router for Vue.js 2)
  vuex                  	3.0.1	(state management for Vue.js)
  electron              	2.0.0	(Build cross platform desktop apps with JavaScript, HTML, and CSS)
  electron-packager     	12.1.0	(Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI)
  electron-builder      	20.25.0	(A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box)
  @babel/core           	7.0.0-beta.49	(Babel compiler core.)
  webpack               	4.9.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server    	3.1.4	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin	3.2.0	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)

### What did you get as the error?
I have a situation where my unique key needs to be ID but the user actually needs to select the label, and I need to know which label was selected. I've done a workaround by creating my own @click on the `default-body` custom element in the tree so I can pass the full node that was clicked. Without this shortcut I'd have to create a custom tree traversal method until I find the ID that was selected and my tree's can get very large...

### What were you expecting?
I see two possible workarounds that would make the tree component more versatile for selection:

1. Allow the user to specify their `node-key="id"` for the unique ID and another optional attribute if they desire the selection to be different than the node-key such as: `selection-key="label"`.

In the example here, my goal is to receive the `label` string on click but I must use `id` as the unique key since `label` is not necessarily unique:

```
               {
                 "children":[  
                     {  
                        "hasChildren":false,
                        "label":"label1",
                        "id":"123"
                     },
                     {  
                        "hasChildren":false,
                        "label":"label2",
                        "id":"456"
                     }
                  ]
               },
               {
                  "hasChildren":false,
                  "label":"label1",
                  "id":"678",
                  "children":[]
               }
```
2. Another option, and my preference by far since it handles all possible use cases, is to allow the selected prop to receive the entire clicked node. Example: 

`:selection-strategy="node"` vs the current which seems to be the equivalent of `:selection-strategy="node-key"`

With this method I'd receive the full node that was clicked and it's children and could easily create a method to grab the label, id or any other custom element I need.

**Comment by rstoenescu** [comment]
There's the `getNodeByKey(key)` method on the QTree that you can use.
All your ideas seem very useful, but they break down performance unfortunately.

**Comment by altShiftDev** [comment]
Hi Raz, I wasn't aware of this feature. I can't find any documentation for it on the quasar site, do you have a link? Thanks!

**Comment by rstoenescu** [comment]
I added it and will be visible along the next update to docs. Just put a reference on your QTree and use the getNodeByKey(key) method. Giving you a link to a preview of what will get added to docs: https://github.com/quasarframework/quasar-framework.org/blob/dev/source/components/tree.md#vue-methods
