### ISSUE TITLE
QSelect Width Error when Floating-Label is used

### ISSUE THREAD

**Issue by JoseMancebo** [quasarframework/quasar#2478]
### Software version
Quasar: 0.17.10
OS: Windows
Browsers: Chrome, IE, Edge (Tested)

### Codepen with reproducible issue
https://codepen.io/josemancebo/pen/mGEGVY

### What did you get as the error?
Using the Q-Select with Floating-Label, when item is selected the width of the Select is increased with he Floating-label width.

### What were you expecting?
The width of the QSelect shouldn't be incremented with the floating-label width when a item is selected select.

### What steps did you take, to get the error?
On codepen:
Selected an option and see the problem...

**Comment by pdanpdan** [comment]
You should use some class/style on the fields in order to specify the width if you place them inside `.row`.
Like adding `class="col"` on `QSelect`

**Comment by rstoenescu** [comment]
We are investigating. A fix will be available in Quasar v0.17.11.
