### ISSUE TITLE
QSelect show undefined on clear 

### ISSUE THREAD

**Issue by JoseMancebo** [quasarframework/quasar#2479]
### Software version
Quasar: 0.17.10
OS: Windows
Browsers: IE,Edge,Chrome (tested)

### Codepen with reproducible issue
https://codepen.io/josemancebo/pen/aaZQJp

### What did you get as the error?
When you clear the selection on a QSelect, this shows undefined.

### What were you expecting?
When you clear the selection on a QSelect, it will appear empty.

### What steps did you take, to get the error?
On codepen sample:
1- Select an option
2- Clear selection with the clear button.

**Comment by rstoenescu** [comment]
Thanks for reporting this regression. Fix will be available in Quasar v0.17.11
