### ISSUE TITLE
QTable row-key not working with nested properties.

### ISSUE THREAD

**Issue by lesharris** [quasarframework/quasar#2480]
### Software version

Quasar: 0.17.10
OS: Mac OS X High Sierra
Node: 10.9.0
NPM: Yarn 1.9.4
Browsers: Chrome
iOS: n/a
Android: n/a
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/lesharris/9xycLhf1/2/

### What did you get as the error?
`row-key` is set to `"id"`.  There exists a column named `id` defined as:
```javascript
        {
          name: 'id',
          label: 'ID',
          field: row => row.properties.uuid
        }
```

The table data contains the properties.uuid value:
```javascript
        {
          name: 'Cupcake',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          sodium: 87,
          calcium: '14%',
          iron: '1%',
          properties: {
            uuid: '2'
          }
        }
```

However, selection and row expansion acts as though no row-key is set: All rows are selected when one is, all rows are expanded when one is.

### What were you expecting?
For the QTable to respect the row-key and have selection and expansion work.

### What steps did you take, to get the error?
See the fiddle for an example.

**Comment by rstoenescu** [comment]
Hi,

`row-key` refers to each row's unique id, not to a column name. So if `row-key` is set to "something" then QTable looks for each row's "something" prop -- which should be unique. By default, `row-key` is set to "id" (unless you change it) -- meaning it expects each row to have an "id" property.

Example set of data when setting row-key to "name" (which must be unique for each row):
```json
       {
          name: 'Cupcake',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          sodium: 87,
          calcium: '14%',
          iron: '1%'
        }
```
