### ISSUE TITLE
QInput with icon, visibility issue inside QInnerLoading

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2484]
Hello!

When I put input inside QInnerLoading it works ok, input is faded out and I'm unable to click inside.
However, if I add an icon to an input, icon seem to displayed on top of loading container, and, when clicking on an icon input gets focused.

Example: https://jsfiddle.net/waugrryy/5960/
1) Click inside input, nothing happens 👍 
2) Click on an icon, input gets focused 👎 

Expected:
1) Click inside input, nothing happens 👍 
2) Click on an icon, nothing happens 👍 

Thanks!

**Comment by rstoenescu** [comment]
Thanks for reporting!
