### ISSUE TITLE
[Bug] QInput - wrong cursor on hover when using float-label

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2488]
#### Steps
1. Create Qinput with `type="text"` or any non-textarea with `float-label`
2. Hover on label
#### Expected
Cursor change to caret
#### Actual
Cursor is still default

#### Reproduction link
https://jsfiddle.net/waugrryy/6015/
#### Info
Quasar Version: 0.17.10
Build mode: SPA

**Comment by panstromek** [comment]
Used issue helper, let me know how you like the structure ;) 

It's super minimal to include only important info and less noise ;)

**Comment by pdanpdan** [comment]
According to this https://material.io/design/components/text-fields.html the cursor should be pointer on hover.

**Comment by panstromek** [comment]
oops, I confused the names, I meant that it stays on default.
