### ISSUE TITLE
auto close previous notify when new one appear

### ISSUE THREAD

**Issue by channimol** [quasarframework/quasar#2490]
Is there a way to close the previous notify before the new one appear? because right now, I set notify timeout to 0, so it can only dismiss when the user click on it. the problem is when user does not close the first notify and then next notify continue appear many on the screen.

Example: for internet connection, i set quasar notify to appear when device lost connection. user can click on option on notify to retry the connection but if they don't dismiss it, and instead they click to another pages, the new notify appear on the top of previous notify (I want it to notify the connection in every page). Here is the code

      checkConnection () {
          if (this.connection === false) {
             `Notify.create({
              message: 'Lost Connection',
              timeout: 0,
              actions: [
                  {
                         label: 'Try again...',
                         handler: () => {
                                     this.connection = true
                                     this.checkConnection.call(this.checkConnection)
                         }
                  }
           }
     }

**Comment by pdanpdan** [comment]
`Notify.create` or `this.$q.notify` return a function that can be called to dismiss the notification.
So just keep the return value in a variable and call it before showing the new notification.

**Comment by channimol** [comment]
@pdanpdan could you show me in the example?

**Comment by pdanpdan** [comment]
Sure, create a fiddle and I'll change it for you.

**Comment by channimol** [comment]
this is the code I added. https://jsfiddle.net/qump874w/4/  please check it @pdanpdan

**Comment by pdanpdan** [comment]
you have errors in your fiddle, please fix them first

**Comment by channimol** [comment]
thank you @pdanpdan, I will follow your sample.

**Comment by romain130492** [comment]
damn... thats messy as a solution..

**Comment by rstoenescu** [comment]
@channimol @romain130492 

Use the "group" feature for Notifications. That's exactly what it's meant for.
No need to save the returned function.

https://quasar.dev/quasar-plugins/notify#grouping

**Comment by pdanpdan** [comment]
It was for quasar 0.15 :)

**Comment by romain130492** [comment]
i see, what about the last version then? thanks

**Comment by rstoenescu** [comment]
Already answered for Qv2

**Comment by bhagyatharindu** [comment]
const myNotification = Notify.create({
        message: "Requesting new password...",
        type: "ongoing",
        position: "top",
        actions: [
          {
            label: "dismiss",
            color: "white",
            handler: () => {
              myNotification();
            },
          },
        ],
      });
      
       myNotification();
       
       try this
