### ISSUE TITLE
[Proposal] vue-fontawesome support

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#2493]
Hi!

Is it possible to use Fontawesome as component or with Quasar components (icon on button)?
For example, like this:

`<font-awesome-icon icon="coffee"></font-awesome-icon>`

https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs

**Comment by pdanpdan** [comment]
Use QIcon

**Comment by rstoenescu** [comment]
Please read the Quasar docs on QIcon.
