### ISSUE TITLE
[Bug] In the 0.17 release, the vue VM level has changed.

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar#2496]
After upgrading from 0.16 to 0.17, the VUE vm level has changed.
At 0.16    $root vm = App.vue
At 0.17    $root vm = \<Root\>
                    App.vue = children

Content previously accessed via $root is unreachable。

**Comment by pdanpdan** [comment]
What content? Can you provide an example of what you were trying to do?

**Comment by pinghe** [comment]
The problem is solved, the Ajax Bar is replaced with a LoadingBar and configured in quasar.conf.js.
