### ISSUE TITLE
[Feature Request] QSplitter

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#2497]
In my current project I'll need a Splitter control so I'll have to reach outside of Quasar to use either [VueSplitter](https://github.com/rmp135/vue-splitter) (Basic feature) or [Split.js](https://nathancahill.github.io/Split.js/) (more advanced features) how ever I think having a QSplitter component as  part of the Quasar suite would be an exciting and valued addition.

The downside of both of these implementations is that they don't respond to touch gestures on mobile/tablet devices. So my feature request would be to port one of these to Quasar as a new `QSplitter` component and enhance it with touch gesture support so they'd work on desktop & mobile.

I'm new to developing with VueJS and Quasar but very much enjoying the experience so far.  Thanks for your awesome efforts. Deeply appreciated!

**Comment by rstoenescu** [comment]
Hi,

Will be available in v1.0. Thanks for suggesting it!

**Comment by tohagan** [comment]
Wonderful! Thanks for Quasar. I'm a new convert :).

**Comment by rstoenescu** [comment]
@tohagan Welcome to Quasar! :)
