### ISSUE TITLE
[Request] QBtn customazible icon ratio

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2498]
Hello and sorry to bother! 

I think it would be super useful to be able to change QBtn icon size (ratio) in a nice way via stylus variable.

Currently:
```
  .q-icon, .q-spinner
    font-size 1.4em
```

This is low priority of course. What do you guys think?

**Comment by rstoenescu** [comment]
Hi Jean,

I tend to agree with you, but we'd be diverging too much from Material specs. The current ratio is carefully chosen for the perfect design. Best would be to add two ratios, one for rectangle-shaped and one for round-shaped, adding additional CSS that 99.99% of the devs won't need.

I think it's best if this is taken care of in app-space and not in framework-space. Example:

```
.q-btn-rectangle
  .q-icon, .q-spinner
    font-size 2em
```

Sorry for any inconvenience.
