### ISSUE TITLE
Broken Mouse Wheel scroll when drawer is opened in small width screen

### ISSUE THREAD

**Issue by JoseMancebo** [quasarframework/quasar#2499]
### Software version
Quasar: 0.17.11
OS: Windows, Android
Browsers: Chrome, Edge (tested)

### Sample Url for reproduce it
https://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/play-with-layout

### What did you get as the error?
In small width screen (Drawer is auto collapsed), when you open the drawer and close it, then the scroll with the mousewheel doesn't work on the content page. In some mobiles cause normal scroll doesn't work.

### What were you expecting?
When you open and close drawer, the scroll with mousewheel should be work.

### What steps did you take, to get the error?
1- Open the sample link.
2- Reduce de window width size to lest than 1000px for force drawer autoclose
3- Open the drawer
4- Close it
5- The mousewheel scroll doesn't work.
6- If you refresh the browser the mousewhell will work
7- If you open the drawer and close it, the mousewhell will not work.

**Comment by rstoenescu** [comment]
Thank you for reporting this regression!
