### ISSUE TITLE
[Proposal] Improvement for QDatetime with property 'format24h'

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#2504]
Hi!

First of all, thanks for new hour picker.
I want to ask about one detail. It about `'00'` label. In 12 hour mode we don't have `'00'` label. But with property `format24h` this label exist, and placement of this label IMHO little confusing, because day starts in 0 (middle of the night).

Let's see on image.
I try to explain how on my opinion time lasts. We start day at `'00'` and move to 1, 2, ..., 12, 13, ..., 22, 23. So with current layout we move across hours in day by confusing trajectory.

![d1](https://user-images.githubusercontent.com/30389307/44933933-ad970500-ad73-11e8-843f-512c7e281d86.png)

I propose to swap `'00'` and `'12'` labels, so label `'00'` place on top (visually at start of day) and we move with more logical trajectory.

![d2](https://user-images.githubusercontent.com/30389307/44933934-ad970500-ad73-11e8-8b44-86c82eb111a7.png)

What do you think about such improvement?

P.S. This is very strange, but for now I can't find Datetime picker component in Material Design guide...

**Comment by pdanpdan** [comment]
Hi. You can try the clock on Android. It's the same design. In 12h format you have no 0, there is 1 to 12, and no leading 0. In 24h format that's the order on the native clock, with 0 leading.

**Comment by smolinari** [comment]
@olegvakulenko - If you look at some real world 24h analog clocks with just 12 hours showing around the dial, the "00" hours is shown as either "24" or "00" and underneath the "12" hour position. The 1-12 on the outside fashions a normal analog 12 hour clock. And, as Dan pointed out, there aren't 12 hour clocks with "00" at the top.  

So, with the concept of "findability" often mentioned in the Material Design specs, the user should be able to quickly find what they are looking for on the clock and that can only happen with a regular 12h clock. In other words, with your suggestion, finding "12" o'clock becomes more difficult and I'd personally say more difficult than finding "00" in the current version too, which I believe your suggestion is trying to improve. 

Just my 2 cents and I hope that makes sense. 😄 

Scott

**Comment by rstoenescu** [comment]
Updated and will be available in v1.1.1.
Seems like latest Android has the clock wheel changed.

![time](https://user-images.githubusercontent.com/4665641/64495395-1461cf00-d2a2-11e9-8c2b-2e057f3c13d7.png)
