### ISSUE TITLE
QSelect & clearable with v-model showing clear button on ""

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#2505]
### Software version

Quasar: 0.17.12
OS: OSX
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://codepen.io/smakinson/pen/qMRGRM

### What did you get as the error?
When the v-model is set to an empty string "", when the QSelect is first rendered it shows the clear button even though there is nothing to clear if its an empty string. This only seems to happen on first load, so be sure look right after load with no interaction in the codepen.

### What were you expecting?
No clear button when v-model is ""

### What steps did you take, to get the error?
Load the page

**Comment by olegvakulenko** [comment]
Use `clearable` with `clear-value` property.

https://quasar-framework.org/components/input-textfield.html

**Comment by smakinson** [comment]
What should clear-value be set to for this scenario? I tried a couple things in the pen:
clear-value=""
:clear-value="''"

I see the clear button with those. Should it be something else to have it hide when the model is an empty string?

**Comment by olegvakulenko** [comment]
https://codepen.io/anon/pen/aapgOx

It work if model is array.

**Comment by olegvakulenko** [comment]
It strange error at first sight, because now I check on my project without arrays and all works fine.

**Comment by olegvakulenko** [comment]
https://codepen.io/anon/pen/pORXRZ

It seems problem when default value is `''` and `clear-value=''`.

**Comment by pdanpdan** [comment]
Yes, it looks like it. I'll fix it on Monday and it'll be available in the next release.

**Comment by olegvakulenko** [comment]
1. model and clear-value are empty arrays -> work.
2. model and clear-value are same NON EMPTY string -> work.
3. model and clear-value are EMPTY string -> DOESN'T work.

@pdanpdan Please, confirm my assumptions.

**Comment by pdanpdan** [comment]
It's an error in checking the presence of the clearValue.
