### ISSUE TITLE
tickStrategy could have a "leafParent" option too

### ISSUE THREAD

**Issue by bebekar** [quasarframework/quasar#2508]
I required to disable all parent selection except the one above the leaf. "leafParent"
This would help me select all leaves or deselect all selected leaves

**Comment by nothingismagick** [comment]
Is this something that is resolved in v1?

See:
https://v1.quasar-framework.org/vue-components/tree#Selection-vs-ticking%2C-expansion
https://v1.quasar-framework.org/vue-components/tree#Tick-strategy
https://v1.quasar-framework.org/vue-components/tree#Custom-filter-method

**Comment by bebekar** [comment]
Yes, Done. Thanks
