### ISSUE TITLE
Can I use `npm install -g @vue/cli` to install vue-cli3.0 instead of `npm install -g vue-cli` to install vue-cli2.0?

### ISSUE THREAD

**Issue by zwl1619** [quasarframework/quasar#2510]
The docs said: https://quasar-framework.org/guide/index.html
```
# make sure you have vue-cli globally installed
$ yarn global add vue-cli
# or:
$ npm install -g vue-cli

# Node.js >= 8.9.0 is required.
$ yarn global add quasar-cli
# or:
$ npm install -g quasar-cli
```

After running `npm install -g vue-cli`, the version of vue-cli is 2.9.6,can I install vue-cli 3.0 with `npm install -g @vue/cli` and then `npm install -g quasar-cli`？
```
λ npm install -g vue-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
C:\Users\dell\AppData\Roaming\npm\vue -> C:\Users\dell\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\dell\AppData\Roaming\npm\vue-init -> C:\Users\dell\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
C:\Users\dell\AppData\Roaming\npm\vue-list -> C:\Users\dell\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list
+ vue-cli@2.9.6
added 253 packages from 220 contributors in 34.256s
```

**Comment by smolinari** [comment]
Also, in general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by rstoenescu** [comment]
Quasar uses Vue CLI (and it specifies that in the console) to scaffold a Quasar project folder from Quasar template (through vue init command). If you have a project already, the only need is to install Quasar CLI and you don't need vue cli at all.

Other than this, let me make it extremely clear that there is no connection between vue cli and quasar cli.

**Comment by rstoenescu** [comment]
Quasar uses Vue CLI (and it specifies that in the console) to scaffold a Quasar project folder from Quasar template (through vue init command). If you have a project already, the only need is to install Quasar CLI and you don't need vue cli at all.

Other than this, let me make it extremely clear that there is no connection between vue cli and quasar cli.
