### ISSUE TITLE
QDatetimePicker unable to detect date selection

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2516]
Hello!

This is a pretty common scenario when would want to detect that date has been selected.

Im my example, I want to close the popup once date is clicked:
https://jsfiddle.net/waugrryy/6201/

Was unable to do this using `@input` or `@change` events because they also fire when you navigate between months.

Maybe add an additional event `@selected`?

Here is an example from similar component:
![screen shot 2018-09-04 at 11 20 38](https://user-images.githubusercontent.com/3635352/45019273-99355f80-b034-11e8-919c-e60cc001a5f3.png)

Thanks!

**Comment by ninjamonz** [comment]
I guess better if we remove auto select date when month changed.
Imagine when we have selected date and we change the month w/o select the date, Quasar **_force_** us to change the date also T___T

like other does, for example :
- https://vuematerial.io/components/datepicker
- https://muse-ui.org/#/en-US/date-input
- https://buefy.github.io/#/documentation/datepicker
- etc...

**Comment by ninjamonz** [comment]
I guess better if we remove auto select date when month changed.

Imagine when we have selected date(from flight API) and accidentally click next month(w/o desire for change the date, just for check what the day is in the next month), but Quasar **_force_** us to change the date also.

like other does, for example :
- https://vuematerial.io/components/datepicker
- https://muse-ui.org/#/en-US/date-input
- https://buefy.github.io/#/documentation/datepicker
- etc...

by the way others also can back to the selected date after re-popup (in case we canceling our desire to change the date)

**Comment by pdanpdan** [comment]
This was addressed in https://github.com/quasarframework/quasar/pull/2523, will be available in the next release.

The month navigator in day view (on top) will not change the selection anymore.

**Comment by jean-moldovan** [comment]
Thanks, @pdanpdan !
