### ISSUE TITLE
[SSR] Cannot use set() or clear() with LocalStorage on client side

### ISSUE THREAD

**Issue by devinholloway** [quasarframework/quasar#2517]
### Software version

Quasar: 0.17.13
OS: Linux(4.15.0-33-generic) - linux/x64
Node: 8.11.3
NPM: 5.6.0
Browsers: Chrome

The LocalStorage errors anytime I call the set() and clear() functions. It looks like the exact same problem as in this reported issue:
https://github.com/quasarframework/quasar/issues/1680

I'm also using this in a store action. Although I'm using the latest version quasar. Has this just not been fixed yet?

### What did you get as the error?
quasar_framework_src_plugins_local_storage_js__WEBPACK_IMPORTED_MODULE_3__.default.set is not a function

**Comment by pdanpdan** [comment]
Can you please upgrade to the latest version and provide code?

**Comment by devinholloway** [comment]
Didn't realize there was a new version recently released. But I just upgraded. quasar info now reports:
  quasar-cli                    0.17.15 
  quasar-framework              0.17.12 

An as a store action:

```
import {LocalStorage} from 'quasar';

export function login() {
  try {
    LocalStorage.set('test', 'value');
  } catch (e) {
    console.log('error:', e.message);
    debugger;
  }
}
```
And I get the error:
quasar_framework_src_plugins_local_storage_js__WEBPACK_IMPORTED_MODULE_1__.default.set is not a function

**Comment by pdanpdan** [comment]
1. check if you have LocalStorage in quasar.conf.js
```
framework: {
  ...
  plugins: [
    'LocalStorage',
    ...
  ]
}
```

2. use a `console.error('error:', e, LocalStorage)` instead of `console.log('error:', e.message)` to see more details - please post here the output

3. check the places where this `login` function is called, and follow the calls to identify if it's called on server side also

**Comment by devinholloway** [comment]
I was definitely defining the plugin in the framework/plugins section. I don't think I would get the type of error I was if quasar wasn't loading it as a framework plugin. Unfortunately, due to time restrictions, I had to move forward with a 3rd party storage npm module. But I may come back and look at this a little later.

**Comment by rstoenescu** [comment]
Fixed issue. Will be available in Quasar v0.17.13.

**Comment by solovieff** [comment]
@rstoenescu is this pushed to current v1? I have the same error while trying to use SSR in ^1.0.0-rc.5:

TypeError: quasar__WEBPACK_IMPORTED_MODULE_4__.LocalStorage.getItem is not a function

**Comment by nothingismagick** [comment]
Are you importing it properly?
```
framework: {
  ...
  plugins: [
    'LocalStorage',
    ...
  ]
}
```

**Comment by solovieff** [comment]
Yeah, looks correct to me at this point
```
framework: {
      // all: true, // --- includes everything; for dev only!
      components: [
     ...
      ],

      directives: ['Ripple', 'ClosePopup'],

      // Quasar plugins
      plugins: ['Loading', 'Notify', 'Dialog', 'LocalStorage'],

      iconSet: 'fontawesome-v5',
      lang: 'en-us' // Quasar language
    },
```

**Comment by solovieff** [comment]
https://github.com/quasarframework/quasar/issues/4501

**Comment by nothingismagick** [comment]
Please continue the conversation at that issue. Thankyou!

**Comment by rstoenescu** [comment]
Local Storage is a web technology that runs on client side only. This issue was related to a problem on client side which was fixed.

**Comment by devlamine** [comment]
Please help,
I switched to SSR mode for an existing project but had the same error:
[view-router] uncaught error during route navigation:
TypeError: quasar__WEBPACK_IMPORTED_MODULE_2 __. LocalStorage.getItem is not a function
how can I fix that? I used LocalStorage.getItem in several places of my code.
quasar v1

**Comment by pdanpdan** [comment]
Did you read the docs, the first part about installation of the plugin?

**Comment by devlamine** [comment]
for the LocalStorage plugin it is indicated that:

Note about SSR

When running the server-side code on SSR builds, this feature can not work. Web Storage is a browser API only. You can do this on the client-side with SSR.

but how to do it on the code is not indicated

When building for SSR, use only the $ q.cookies form. If you need to use it {Cookies} from 'quasar', then you'll need to do it like this:

import {Cookies} from 'quasar'

// you need access to `ssrContext`
function (ssrContext) {
   const cookies = process.env.SERVER
     ? Cookies.parseSSR (ssrContext)
     : Cookies // otherwise we're on client

   // "cookies" is equivalent to the global import as non-SSR builds
}

it's the same for localStorage?

**Comment by rstoenescu** [comment]
It's indicated right below :) The whole page describes how to do it client-side -- since it only makes sense there.

Just guard your access so you won't access LocalStorage on server-side. And plan accordingly so you won't bump into hydration errors.

**Comment by devlamine** [comment]
thank you for your response:
Indeed I am still beginner in quasar framwork, you can help me please adapt it in my boot:

```
import { LocalStorage } from 'quasar'
import { onFail } from '../session/logout'
import appSetup from './app-setup'
import config from '../config'

var authorized = false

export default () => {
  if (config.localStorage.enableListener) {
    window.addEventListener('storage', (e) => {
      if (!authorized) {
        console.warn('Unauthorized local storage change')
        switch (config.localStorage.unauthChange) {
          case 'block':
            if (e.key === 'null' || e.key === null) {
              reload()
            } else {
              _LocalStorage.setNative(e.key, e.oldValue)
            }
            break
          case 'clear':
            reload()
            break
          default:
            reload()
            break
        }
      }
    }, false)
  }
  return Promise.resolve(true)
}

const reload = () => {
  onFail().then(success => appSetup())
}

export const _LocalStorage = {
  setNative (key, value) {
    authorized = true
    localStorage.setItem(key, value)
    authorized = false
  },
  set (key, value) {
    authorized = true
    LocalStorage.set(key, value)
    authorized = false
  },
  remove (key) {
    authorized = true
    LocalStorage.remove(key)
    authorized = false
  },
  clear () {
    authorized = true
    LocalStorage.clear()
    authorized = false
  },
  get (key) {
    return LocalStorage.getItem(key)
  }
}

```

**Comment by devlamine** [comment]
In DOC : When building for SSR, use only the $q.platform form. If you need to use the import { Platform } from 'quasar' (when on server-side), then you’ll need to do it like this:


When I use $q.localStorage he shows me an error: $q not found

**Comment by devlamine** [comment]
It's just for the SSR I imagine the problems that I will have after the build to ios and android
