### ISSUE TITLE
error in documantation

### ISSUE THREAD

**Issue by fuzzybook** [quasarframework/quasar#2518]
Documentation error:
let date = addToDate(new Date(), { days: 7, months: 1 })

correct:
let date = addToDate(new Date(), { days: 7, month: 1 })

months are more semantic but Date Object has methods GetMonth and setMonth

**Comment by pdanpdan** [comment]
Please make a PR on the documentation. On the documentation page click the pen icon.

**Comment by elyohan14** [comment]
It works for me! Thank you
