### ISSUE TITLE
"Property or method "_c" is not defined on the instance but referenced during render." on v0.10.2

### ISSUE THREAD

**Issue by eliashdezr** [quasarframework/quasar#252]
I was getting this issue in my project, but then I created a blank template using the CLI and I see the same error on the console.

![2016-12-14 03_26_44-quasar app](https://cloud.githubusercontent.com/assets/6153607/21176701/8e8d9e5c-c1ad-11e6-9c75-0df70e614131.png)

**Comment by rstoenescu** [comment]
Something got messed up within rollup, rollup-plugin-vue and Vue 2.1.5+ packages. Working on a solution.

**Comment by rstoenescu** [comment]
Released v0.10.3 (which is v0.10.2 repackaged). Please npm update to it and tell me if this issue persists. Thanks!
