### ISSUE TITLE
[Request] Edge-to-edge Jumbotron

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2520]
"full-width" option to stretch the jumbotron edge to edge.

**Comment by pdanpdan** [comment]
I don't undestand the request? Do you need `<q-jumbotron class="q-px-none"...`?

**Comment by mesqueeb** [comment]
yeah I think so!
I don't personally need it, but I imagine a lot of people wanting something similar to [Bootstrap's "fluid" jumbotron](https://getbootstrap.com/docs/4.0/components/jumbotron/).

I'm sure it can easily be done with CSS, but there's the small curved borders as well and most people would appreciate it as a boolean prop I reckoned.

That's why I suggested it : )
