### ISSUE TITLE
QCollapsible in 'accordion' mode stops working if section 'disable' prop changes

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#2524]
### Software version

Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.10.0

Global packages
  NPM                           6.0.1
  yarn                          Not installed
  quasar-cli                    0.17.15
  vue-cli                       2.9.3
  cordova                       Not installed

Important local packages
  quasar-cli                    0.17.15 (Quasar Framework CLI)
  quasar-framework              0.17.12 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.6   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.17.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.7   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.4.1   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/2v9tc08s/6

### What did you get as the error?
If a collapsible which is part of a group is open and then its `disable` state changes through being bound to some parent prop or variable, that section becomes stuck open, even when other collapsibles in the group are opened, breaking the accordion behaviour.

### What were you expecting?
That the disabled section would close.

**Comment by pdanpdan** [comment]
This is related to how we are considering a disabled component - now you cannot change the visibility state (neither show nor hide).

**Comment by dsl101** [comment]
I was originally discussing on the discord channel that I think if an expanded collapsible state changes to disabled, it should `hide()`, but I couldn't easily implement that since once the disabled state is changed, you can't change it's view. Personally I think if a collapsible is set disabled, it should be hidden / collapsed, and that would solve this problem too. But I realise that might not be how others are using it...

**Comment by rstoenescu** [comment]
Hi,

Disabling a QCollapsible means exactly freezing its state. Regardless if it's part of a group or not. However, after fixing some mistakes in your fiddle: https://jsfiddle.net/tka5n2pj/
