### ISSUE TITLE
[Request] QDropdownBtn with <div slot="label"> instead of label-prop (for custom html)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2525]
The [QDropdownBtn](https://quasar-framework.org/components/button-dropdown.html) is very nice.

I require to use custom HTML for the label of the button.
So instead only the `label` prop, I'd love the ability to pass html with a `slot="label"`.

**Comment by rstoenescu** [comment]
Will be available in beta.21
