### ISSUE TITLE
Popup Edit can't be disable

### ISSUE THREAD

**Issue by botura** [quasarframework/quasar#2527]
### Software version

Quasar: 0.17.12
OS: Windows 10
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/botura/7yzfLjs1/
### What did you get as the error?
According to [documentation ](https://quasar-framework.org/components/popup-edit.html) QPopupEdit has a `disable` property. But setting it has no effect.
### What were you expecting?
The popup edit should not open if this property is true, so user can't edit it.
### What steps did you take, to get the error?
Add  `disable` property to [documentation code](https://github.com/quasarframework/quasar-play/blob/master/src/pages/showcase/popups/popup-edit.vue) and run it as showed in the fiddle above.

**Comment by rstoenescu** [comment]
'disable' --> 'disabled'

**Comment by rstoenescu** [comment]
Will add disabled prop to it.

**Comment by botura** [comment]
Wow, that was quick!

Thanks.
