### ISSUE TITLE
[Request] Add browser to platform detection - $q.platform.is.browser

### ISSUE THREAD

**Issue by fruitangdan** [quasarframework/quasar#2528]
It would be great if a browser check could be added to the platform detection. I.E - detect if the app is running in any browser, rather than in Electron or Cordova, to make it easier to have browser-only elements / code.

To achieve this I currently do this:

```
<web-only-header v-if="!$q.platform.is.electron && !$q.platform.is.cordova">
    This header appears on the website, but not in the apps
</web-only-header>
```

Which is fine, but it would be neater if we could do this:

```
<web-only-header v-if="$q.platform.is.browser">
    This header appears on the website, but not in the apps
</web-only-header>
```

Cheers!

```
Quasar CLI........ v0.17.7
Quasar Framework.. v0.17.6
```

**Comment by rstoenescu** [comment]
Hi,

"browser" is an unfortunate name as both electron and cordova still run the code in a browser :)
However, you can add a variable in your scope and use it:

```js
export default {
  data () {
    return {
       website: !this.$q.platform.is.electron && !this.$q.platform.is.cordova
```
```html
<web-only-header v-if="website"> ...
```
