### ISSUE TITLE
Pull To refresh scroll  not smoothly on ios

### ISSUE THREAD

**Issue by ceau** [quasarframework/quasar#253]
Hello Everyone.
I have a problem with the Pull To refresh component in my app :
I can't scroll down and up  the list smoothly when i'm inside this component on ios system , but no problem with my android
I run the official demo [pull to refresh](http://quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/pull-to-refresh),the problem also existed
Does anyone have the same problem ?

**Comment by rstoenescu** [comment]
Will look into it. Thanks for reporting.

**Comment by ceau** [comment]
I tested the new code, the problem existed. I can scroll when the scrollbar  appears. I can't scroll when the scrollbar disappear. I touch the element for a  longer time , the scrollbar will appear. I think this is a 300 ms delay problem. Please check this. Thx

**Comment by edgarciametro** [comment]
Same here, pull to refresh on ios brings the header with it and doesnt work randomly.

**Comment by rstoenescu** [comment]
Which versions are you testing with?
