### ISSUE TITLE
Prop called 'persistent' not documented in Popup Edit page

### ISSUE THREAD

**Issue by Jasqui** [quasarframework/quasar#2535]
Good day.

I'm here again with my little contribution regarding documentation.

While using the component Popup Edit with DateTimePicker I found this useful prop in the source code but it isn't documented in its page https://quasar-framework.org/components/popup-edit.html. Just like Popover's persistent prop, it prevents the Popup Edit from closing when clicking something else.

The reason I needed the prop (if anyone's curious) is because the Popup Edit is closed by default when you click anything in the DateTimePicker since it's considered out of the component. 

Thanks in advance!

**Comment by rstoenescu** [comment]
Thx for reporting!
