### ISSUE TITLE
Using router.beforeEach in app plugin fails with SSR

### ISSUE THREAD

**Issue by devinholloway** [quasarframework/quasar#2536]
### Software version

Quasar:   quasar-cli  0.17.15  framework 0.17.12

### What did you get as the error?
No error

### What were you expecting?
beforeEach to execute

### What steps did you take, to get the error?

With the following app plugin: 

```
export default ({router}) => {
  console.log('guard plugin');
  console.log('server:', process.env.SERVER);

  router.beforeEach((to, from, next) => {
    console.log('beforeEach');
    next();
  })
}
```

When this plugin executes on the server, the only things output to the console are:
guard plugin
server: true

When executed on the client, the output is 
guard plugin
server: true
beforeEach

So, the plugin itself is executing server side, but it won't execute the router.beforeEach or any code inside.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting! Just a note though: for CLI related issues please use the [CLI repo](https://github.com/quasarframework/quasar-cli)

Fix will be available in next Quasar CLI version (v0.17.16).
