### ISSUE TITLE
[Request] Ability to choose another arrow icon for q-btn-dropdown

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2537]
I'm using [dropdown buttons](https://quasar-framework.org/components/button-dropdown.html) all the time, but my boss often asks me to use a different arrow design. : D There's currently (to my knowledge) no possible way to do this with Quasar. So I'm doing some hacking with element swapping after `mounted()`, not ideal...

Would be great if that is a possibility to have an `arrow-icon` prop where we can pass a different arrow icon by name.

Partially related: #1876

**Comment by rstoenescu** [comment]
Tell Quasar to use your favorite icon: `this.$q.icon.input.dropdown = 'some-icon'`.

**Comment by mesqueeb** [comment]
Amazing!!! Thanks so much!!

**Comment by anahoua16** [comment]
How can I remove the arrow?

**Comment by rstoenescu** [comment]
@anahoua16 if you remove the arrow you have a QBtn with a QPopover (v0.17) or QMenu (v1.0) in it... so use that.

**Comment by armedoctopus** [comment]
this.$q.icon.input.dropdown = "" 
@anahoua16

**Comment by mesqueeb** [comment]
Since I often am tasked with changing the dropdown arrow to a chevron like this:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/3253920/58675453-5ae48b00-838f-11e9-9f34-b77c3c2dc564.png">

maybe we could add something to the documents on the best way to do this
