### ISSUE TITLE
[Bug] Uploader doesn't obey disabled prop

### ISSUE THREAD

**Issue by HenriqueSPin** [quasarframework/quasar#2538]
https://jsfiddle.net/rp5da41o/

**Comment by rstoenescu** [comment]
Fixed in next Quasar v0.17.13

**Comment by HenriqueSPin** [comment]
@rstoenescu Works great! Thank you!

But, the field itself, doesn't look disabled. Maybe adding the disabled class to the frame is all that really is missing. Thank you.
