### ISSUE TITLE
Usage of Meta Plugin makes Production Audits fail

### ISSUE THREAD

**Issue by kevinmarrec** [quasarframework/quasar#2539]
I'm using the Meta Plugin to provide a meta description around my pages.

I figured that Google Lighthouse was warning me I didn't have a meta description.

That's why :
![screenshot_33](https://user-images.githubusercontent.com/25272043/45264253-06ccfb80-b43a-11e8-9c55-8cb833aae694.png)

Lighthouse reads the first one and assume the meta description is empty.

I think not only Lighthouse will think this way, and it may cause issues deploying apps that won't have meta descriptions, keywords, etc.. recognized by services if they think with the same logic.

Is there a way to `replace` the meta html tag instead of just adding it in the DOM ?
If yes, we should fix this issue doing some changes around the Meta Plugin to make it replacing the DOM instead of just adding elements to it.

**Comment by kevinmarrec** [comment]
Well, deploying it on Now.sh result in

![screenshot_34](https://user-images.githubusercontent.com/25272043/45264393-2bc26e00-b43c-11e8-9a38-3fa0653a23d8.png)

So the audit is not failing

But Lighthouse local builds and other Deployment than Now could result in the issue I mentioned (having meta fields defined twice)

**Comment by nothingismagick** [comment]
Did you remove the <meta name="description"> from the index.template.html

This one:
```
    <meta name="description" content="<%= htmlWebpackPlugin.options.productDescription %>">
```

**Comment by kevinmarrec** [comment]
Thanks @nothingismagick ! I Didn't think about this stuff ...
