### ISSUE TITLE
Suggestion for improvement - Documentation of integration with Cordova.

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#254]
Suggestion for improvement - Documentation of integration with Cordova.

Create or enhance documentation related to Apache Cordova integration. I keep a group on the Telegram that deals with the Quasar Framework. In it, a redundant issue is the lack of documentation on how to integrate Quasar with Apache Cordova. I needed also and the documentation is very sparse.

Is there any study of this possibility?

Thank you very much for your attention.

**Comment by rstoenescu** [comment]
Please open up this issue and let's discuss what is needed on documentation repo: https://github.com/quasarframework/quasar-framework.org/issues

Thanks!

**Comment by xereda** [comment]
https://github.com/quasarframework/quasar-framework.org/issues/45
