### ISSUE TITLE
QSlideTransition unable to customize duration

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2541]
Hello.

I think it would be very nice for QSlideTransition to have a customizable duration.

https://jsfiddle.net/waugrryy/6486/

Looking at the source I can see that the component has a duration prop (which doesn't seem to work):
https://github.com/quasarframework/quasar/blob/dev/src/components/slide-transition/QSlideTransition.js#L5

Thanks!

**Comment by rstoenescu** [comment]
That's because it was pushed recently and it's part of next Quasar version.
