### ISSUE TITLE
[carousel req] q-carousel-track adding a custom class

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar#2544]
After upgrading to 0.17, the carousel dom element hierarchy has changed. I hope to support adding a custom class in q-carousel-track, for example, the following figure, I hope to add row class

![image](https://user-images.githubusercontent.com/377955/45414042-1b64fa00-b6ad-11e8-9728-f436df87ac59.png)

Otherwise the following flex layout will not take effect.

Can  add a track-class attribute to the q-carousel component?

**Comment by rstoenescu** [comment]
Hi,

I fail to see what exactly you want, because:

1. You shouldn't need to change anything on div.q-carousel-track -- what would be the purpose?
2. div.q-carousel-track is already a flex row.

Please reopen with a detailed explanation. Thank you.

**Comment by pinghe** [comment]
I want to switch the slide to the q-carousel-slide element instead of everything under q-carousel-track

https://codepen.io/pinghe/pen/NLMEWp/
