### ISSUE TITLE
[Feature Request] q-layout-drawer / QLayoutDrawer: Combine overlay layout with mobile behavior

### ISSUE THREAD

**Issue by joerg-walter-de** [quasarframework/quasar#2545]
with behavior="mobile" the drawer closes when the area outside the drawer is clicked.
With overlay the drawer is located BELOW any toolbar in the layout.

I propose to combine the clicking behavior of the mobile mode with the layout of the overlay property set.

**Comment by joerg-walter-de** [comment]
as an option

**Comment by rstoenescu** [comment]
Hi,

Let me see if I got it right. You want the drawer acting as current overlay mode, but with a (transparent?) backdrop on which user can click in order to "hide" it.

**Comment by joerg-walter-de** [comment]
Yes. Right now the drawer in overlay mode is closed when I click (a) on an item or (b) again on the menu open button. Why not allow closing it by clicking outside the drawer?

**Comment by pdanpdan** [comment]
Try to add `behavior='mobile'` on `q-layout-drawer`

**Comment by rstoenescu** [comment]
Setting this for v1.0 (next version) research.

**Comment by rstoenescu** [comment]
Hi, sorry but this is not possible without some serious hacking and error-prone code... Closing and sorry for any inconvenience.

**Comment by thomhickey** [comment]
Sorry, I know this is closed but I don't understand the "hacking and error-prone code" statement when this is already done for mobile mode? How was that accomplished without hacking and error-prone code? Thanks! Love Quasar, by the way.
