### ISSUE TITLE
QCard assumes any color it's set to is dark

### ISSUE THREAD

**Issue by tmladek** [quasarframework/quasar#2546]
### Software version
Operating System         	Linux(4.17.0-3-amd64) - linux/x64
NodeJs                   	8.11.4

Global packages          	
  NPM                    	6.4.0
  yarn                   	1.9.4
  quasar-cli             	0.17.13
  cordova                	8.0.0

Important local packages 	
  quasar-cli             	0.17.13	(Quasar Framework CLI)
  quasar-framework       	0.17.10	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras          	2.0.6	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)

Browsers: Firefox, Chrome

### JsFiddle
https://jsfiddle.net/mo65bq0n/
https://jsfiddle.net/gb8h79o1/4/

### What did you get as the error?
No matter what color I pass as the `color` prop to QCard, it colors the text white and adds a `q-card-dark` class to the outermost `<div>` of the QCard, which also causes the separator to be white.

This happens even when setting the color to white, which means the QCard appears completely blank.

Text color can be overriden using the `textColor`, but this doesn’t change the color of the separator.

### What were you expecting?
The card's text and separator to remain black.

This happens to multiple people apparently: https://forum.quasar-framework.org/topic/2681/qcard-assumes-any-color-i-set-is-dark

**Comment by rstoenescu** [comment]
Added a Boolean `dark` prop to QCard, to be used only when color is dark. Will be available in Quasar v0.17.13.

**Comment by tmladek** [comment]
Thank you! However, I hope this won't break any projects which rely on the fact that QCard does in fact assume that and will be missing the `dark` prop.

**Comment by tmladek** [comment]
Hello again, this issue is still not fixed (or maybe broken again?) in the current version (v.0.17.17), as you can see by re-running the JSFiddles, this time not because of the `q-card-dark` class, but because of the `text-white` class. The `dark` prop seems to have no effect.

What happened?
