### ISSUE TITLE
In textarea you have to press TAB key twice to edit value or navigate to next field

### ISSUE THREAD

**Issue by piotrh** [quasarframework/quasar#2550]
You can see the behavior right here:
https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/input

Select a field with $ icon on the right (last one before "Textarea (auto-grows)" section) and then press TAB key. You should be able to navigate to textarea and edit value. Instead, you need to press TAB for a second time to get cursor and underline on that field.

**Comment by pdanpdan** [comment]
What browser are you using, what OS? I cannot reproduce it.
The $ icon is on the left, not right. Are you by any chance using RTL?
There is a reason for the template for bug reports - to reduce the guessing.

**Comment by piotrh** [comment]
I'm sorry for the mistake - of course $ icon is on the left.
The problem with TAB occurs in Mozilla Firefox 62.0 and Firefox Developer Edition 63.0b4.

![textarea](https://user-images.githubusercontent.com/4834124/45475884-e8b71200-b73d-11e8-9f43-93e6c38aaccb.png)


My configuration:

Operating System:  Windows 7
NodeJs: 8.11.1

Global packages                  	
  NPM                            	5.6.0
  yarn                           	1.9.4
  quasar-cli                     	0.17.15
  vue-cli                        	2.9.1
  cordova                        	Not installed

Important local packages         	
  quasar-cli                     	0.17.15	(Quasar Framework CLI)
  quasar-framework               	0.17.12	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                  	2.0.6	(Quasar Framework fonts, icons and animations)
  vue                            	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                     	3.0.1	(Official router for Vue.js 2)
  vuex                           	3.0.1	(state management for Vue.js)
  electron                       	Not installed
  electron-packager              	Not installed
  electron-builder               	Not installed
  @babel/core                    	7.0.0-beta.54	(Babel compiler core.)
  webpack                        	4.17.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server             	3.1.7	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin         	3.4.1	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker        	1.5.2	(Script for registering service worker, with hooks)

**Comment by pdanpdan** [comment]
I got it, thanks for reporting.
