### ISSUE TITLE
Modal closing on mouseup

### ISSUE THREAD

**Issue by AndreAce1** [quasarframework/quasar#2551]
### Software version
Quasar CLI: 0.17.15
Node: 8.9.4
NPM: 6.1.0

### What did you get as the error?
Modal gets closed incorrectly.

### What were you expecting?
Modal to stay open.

### What steps did you take, to get the error?
Same thing reported in issue #755. Click anywhere inside the modal and drop the click outside of the modal. It will close. **This only happens on Chrome**. In firefox it works correctly.

You can test it using the current docs:
https://quasar-framework.org/quasar-play/android/index.html#/showcase/popups/modal

**Comment by pdanpdan** [comment]
I can reproduce the problem - the most annoying is the reverse: mouse-down outside and mouse-up inside.
From the perspective of expected behaviour mouse-down inside and mouse-up outside is expected.
But I think it would be safest to require both down and up outside to trigger close.
