### ISSUE TITLE
[request - QField] - keep a space when label helper's empty

### ISSUE THREAD

**Issue by ninjamonz** [quasarframework/quasar#2552]
demo : https://jsfiddle.net/rzq2cwLj/

expected example : 
- https://vuetifyjs.com/en/components/text-fields#example-custom-validation
- https://vuematerial.io/components/input
- https://muse-ui.org/#/form-validation

**Comment by thearabbit** [comment]
I still problem, with dynamic `error label`.
It don't have `bottom space` when the first time (open form)
(I base on `vee-validate`)
https://jsfiddle.net/theara/amf1qLru/
