### ISSUE TITLE
[Bug] QSelect with multiple: Hover/focus coloring not correct 

### ISSUE THREAD

**Issue by joerg-walter-de** [quasarframework/quasar#2555]
Dev mode.......... spa
 Quasar theme...... mat
 Quasar CLI........ v0.17.15
 Quasar Framework.. v0.17.12

on Chrom on Windows 10

![image](https://user-images.githubusercontent.com/33499391/45474371-e357c880-b739-11e8-9988-a3d27e7c9746.png)

![image](https://user-images.githubusercontent.com/33499391/45474378-e9e64000-b739-11e8-9335-188e19fb9559.png)

![image](https://user-images.githubusercontent.com/33499391/45474402-fec2d380-b739-11e8-803d-182171c6cc17.png)

![20180913_094845](https://user-images.githubusercontent.com/33499391/45474578-68db7880-b73a-11e8-9994-9936c6b55b0d.gif)

I navigated directly from checkbox to checkbox. When checking the last box the hover coloring went to the first item.

**Comment by pdanpdan** [comment]
Sorry, I cannot reproduce.
Please create a fiddle where you can reproduce it.
Also in the animation there is something (a black bar like scroll) on the right - what is it?

**Comment by joerg-walter-de** [comment]
that's an artifact created by the recording tool

**Comment by rstoenescu** [comment]
Please reopen with a jsfiddle (fork this: https://jsfiddle.net/rstoenescu/waugrryy/). Thank you.
