### ISSUE TITLE
Docs update vue install

### ISSUE THREAD

**Issue by fmp777** [quasarframework/quasar#2560]
Sorry if you don't want documentaiton issues here, didn't notice any other place for them.

There's a new package name for vue-cli 3x

Doc: https://quasar-framework.org/guide/index.html
replace:
```
$ yarn global add vue-cli
# or:
$ npm install -g vue-cli
```
with:
```
$ yarn global add @vue/cli
# or:
$ npm install -g @vue/cli
```

In accordance with:
https://cli.vuejs.org/guide/installation.html

When using *vue-cli* via npm I ended up with version 2.5.17

**Comment by rstoenescu** [comment]
`vue-cli` OR `@vue/cli` & `@vue-cli/init` is fine either way. It's being used only by "quasar init" command to generate the project folder.

**Comment by fmp777** [comment]
Not my actual experience - maybe its true with yarn, but not npm
![image](https://user-images.githubusercontent.com/2659615/45512541-3a22c980-b75d-11e8-864d-9d11830f23e0.jpeg)

**Comment by rstoenescu** [comment]
Like I said, having either `vue-cli` or `@vue/cli` (+ `@vue/cli-init`) is fine and you'll be able to "quasar init" a project folder. If you already have a project or either vue packages are globally installed, you can skip this step.

**Comment by fmp777** [comment]
OH I see what you mean.  Yes the quasar init worked even so, but the docs stated to be sure we have v3x so, i rolled it back and went with latest.

Then I noticed on quasar init it failed because I also needed to do
```
npm install -g @vue/cli-init
```

**Comment by rstoenescu** [comment]
This requirement will be gone in v1.0 anyway, which is next in line.
