### ISSUE TITLE
[Request] QBtn auto-loading

### ISSUE THREAD

**Issue by VitalyEmelyanov** [quasarframework/quasar#2567]
I've noticed that there's a common pattern when making a button with loading state. It looks something like that: **[JSFiddle](https://jsfiddle.net/VitalyEmelyanov/gvyq91nf/)**

I suggest to add a native QBtn feature that will automatically switch loading state. It can enable loading after click, and then automatically disable it after click handler is resolved.

Here is a small **[demo](https://jsfiddle.net/VitalyEmelyanov/gdmj7knu/)**

**Comment by pdanpdan** [comment]
This was implemented some time ago and the solution was not flexible. There are a lot of cases where it would fail.
The current solution is simple and allows any use case.
