### ISSUE TITLE
Popup Edit acts weird when keyboard comes up

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#2568]
### Software version

Quasar: Latest
Browsers: Android built-in browser, Chrome for Android

### What did you get as the error?
Popup Edit break the layout and bring screen splash when keyboard comes up

### GIF
![](https://i.loli.net/2018/09/14/5b9bb7fd55872.gif)

**Comment by pdanpdan** [comment]
What version of quasar? The one from today?

**Comment by yuanyesong** [comment]
quasar: Found it on v0.17.3. And I test it on v0.17.4, the problem still exists.

**Comment by pdanpdan** [comment]
Yes, I saw it also.

**Comment by rstoenescu** [comment]
Fix available in future Quasar v0.17.15
