### ISSUE TITLE
Being able to use Google Fonts CDN

### ISSUE THREAD

**Issue by eliashdezr** [quasarframework/quasar#257]
Currently I'm having issues with Azure and the fonts with some 404 errors:
![fonts](https://cloud.githubusercontent.com/assets/6153607/21244881/38b739dc-c2e5-11e6-8c77-ac4f3c045f86.png)

Since the fonts referenced in the final CSS output use the "hash" included, using CDN fonts would not work either. Would be nice to have the option to not use the npm package `roboto-fontface`, saving with that space in the bundle too.

**Comment by rstoenescu** [comment]
Fonts were added mainly for Cordova apps as using a CDN can break your app when you're offline. However, it's a good idea to be able to use CDN when building a website, so will make this possible soon.
Thanks for opening this!

**Comment by rstoenescu** [comment]
In your /src/themes/app.mat.styl and /src/themes/app.ios.styl add this definition before importing Quasar's Stylus:

`$quasar-dont-import-fonts = true`

Will be available in next Quasar version.

**Comment by eliashdezr** [comment]
@rstoenescu 
I added the variable to both files and the output is still using the local fonts. Should I remove the npm package for roboto fonts?

This is the CSS output when using  `quasar build mat`

```
@font-face {
    font-family: Roboto;
    font-weight: 200;
    src: url(fonts/Roboto-Thin.90d3804.woff) format("woff")
}
@font-face {
    font-family: Roboto;
    font-weight: 300;
    src: url(fonts/Roboto-Light.37fbbba.woff) format("woff")
}
@font-face {
    font-family: Roboto;
    font-weight: 400;
    src: url(fonts/Roboto-Regular.081b11e.woff) format("woff")
}
@font-face {
    font-family: Roboto;
    font-weight: 500;
    src: url(fonts/Roboto-Medium.303ded6.woff) format("woff")
}
@font-face {
    font-family: Roboto;
    font-weight: 700;
    src: url(fonts/Roboto-Bold.ad140ff.woff) format("woff")
}
```

**Comment by rstoenescu** [comment]
@eliashdezr 
1. Have you specified `$quasar-dont-import-fonts = true` BEFORE the Quasar import statement?
2. Are you using at least Quasar v0.11?

**Comment by eliashdezr** [comment]
@rstoenescu 

This problems persist on quasar `v0.13.1`

Here's an image of what it looks the in the code. 

![2017-02-15 00_13_42-app mat styl - ui - visual studio code](https://cloud.githubusercontent.com/assets/6153607/22962646/df6ea2b6-f313-11e6-8e81-a742cd2e1569.png)

I used the same line in the ios style but still producing the same result, using local fonts.

**Comment by rstoenescu** [comment]
@eliashdezr are you sure you're using the custom style build? check top of `src/main.js`.

**Comment by jperelli** [comment]
@eliashdezr don't forget to change ".css" to ".styl" in top of `src/main.js` read this documentation http://quasar-framework.org/guide/quasar-theming.html#Build
