### ISSUE TITLE
How to choose theme programmatically at the begining?

### ISSUE THREAD

**Issue by maxzhou0** [quasarframework/quasar#2570]
Is there a way let android devices use mat theme ios devices use ios theme?
and how to set ios theme?(the project default is mat)

**Comment by rstoenescu** [comment]
Hi,

You can make an intermediate page to detect platform then redirect to either the "mat" or "ios" build. Please use Discord for help. Thank you.

**Comment by fansanelli** [comment]
Dear @maxzhou0 did you find a way to switch theme programmatically? I could be interested, can you share some info?
I think this kind of thing could be pulled in the docs: https://quasar-framework.org/guide/quasar-theming.html

**Comment by smolinari** [comment]
@fansanelli - It is!

https://quasar-framework.org/components/internationalization.html#Dynamically-Changing-Language

Scott

**Comment by fansanelli** [comment]
Dear Scott, we are talking about theme, aren't we? @smolinari

**Comment by smolinari** [comment]
Oops. Have no idea why I was thinking language. 

As Razvan mentioned, The app needs to be built with the different themes and the user redirected according to platform. There is no dynamically changing the theme per app. 

Scott

**Comment by mapkbalaji** [comment]
Isn't there anything yet?

**Comment by smolinari** [comment]
My 2 cents, but to allow for a dynamic theme in a SPA/PWA, which is possible, for something a user might change once in a very long while, would mean a whole lot of bloat added to your apps, for little reason. I'd suggest thinking twice about wanting it. This kind of feature, seen in apps like Wordpress, is much easier for a server generated multi-page app as the server can change the styling "on the fly". Pushing that capability to the client/ browser is a bad idea. 

Scott
