### ISSUE TITLE
QPopover can not dismiss by mouse click in touchable notebook

### ISSUE THREAD

**Issue by hicdre** [quasarframework/quasar#2571]
Quasar: v0.17.14
Browsers: Chrome 68.0

In touchable notebook, the QPopover only listen body touch event. So When we use mouse, the dismiss can not work.
https://github.com/quasarframework/quasar/blob/40f89466dfc6e5c5dae12e46a568c755fbec0353/src/components/popover/QPopover.js#L81

**Comment by rstoenescu** [comment]
Hi,

Yes, this has already been taken care of. Will release Quasar v0.17.15 shortly with the fix.
