### ISSUE TITLE
[Request] QEditor - Template Plugin

### ISSUE THREAD

**Issue by ymoreiratiti** [quasarframework/quasar#2573]
Add a routine that allow insert custom templates on HTML. For example: I'am developing a Report Designer, where you insert/format document (QEditor WYSIWYG) and can insert custom mustache templates. This text is save on backend. 

When you wanna print this document, the backend replace the mustache strings with the correct value then send to the user.

A routine that insert custom template, will allow display all the mustache strings to the user who is creating the document

A example is the [TinyMCE Template Plugin](https://www.tiny.cloud/docs/plugins/template/)

**Comment by rstoenescu** [comment]
Hi,

This can and should be done in devland rather than in Quasar. Sorry for any inconvenience.
