### ISSUE TITLE
Quasar v1.0 - Feature freeze in effect for v0.17

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#2575]
Hi All Quasarians,

It's been a long, winding road up until this point, but I'm finally working with the team on a solid Quasar v1.0, after which there will be no further breaking changes.

To do this, I’ve decided to feature-freeze v0.17 in order to fully focus on v1.0. This means that v0.17 is the last pre 1.0 release - and there will only be fixes merged and no new features. The only exception to this is to honour agreements with partners or main sponsors who require the integration of critical functionality or features.

When 1.0 lands, the Quasar you know and love will have been polished to a mirror’s sheen. The UI design will be perfect - and if you think Quasar's rendering speed is fast today, you will be glad to know that all of its components will be ruthlessly curated for the best performance possible, the most logical ease of use and the smallest footprint. Furthermore, all of the pain points (no matter how trivial) are being addressed and will be resolved.

The documentation website is also being rebuilt using Quasar SSR, where you'll be able to see live examples and also the source code for them in one place, optionally playing with the example in Codepen - just by clicking on a button.

You can expect more announcements on v1.0 as we inch closer to the release. The plan is to publish it as soon as possible, but without affecting the quality -- we want you to rest easy in the knowledge that everything is perfect and you can trust Quasar 100%. That said, it seems like the stars are aligning for a release candidate late this year.

Thanks,
Razvan Stoenescu

**Comment by nothingismagick** [comment]
![quasar-1](https://user-images.githubusercontent.com/35242872/45617347-55018080-ba72-11e8-91f9-a6fbfe827f43.png)

**Comment by FrancescoMussi** [comment]
Great news!

**Comment by swingcat** [comment]
Really thrilled to see 1.0 coming !!

**Comment by donPuerto** [comment]
hip2x hurry

**Comment by thearabbit** [comment]
💯

**Comment by mesqueeb** [comment]
@rstoenescu I'm curious what will happen to iOS/Material themes in v1.0. A while ago I think there was some discussion on wether or not iOS theme is used enough to keep? Will there be any changes to this or not?

**Comment by trsiddiqui** [comment]
> @rstoenescu
> 
> I'm curious what will happen to iOS/Material themes in v1.0. A while ago I think there was some discussion on wether or not iOS theme is used enough to keep? Will there be any changes to this or not?
> 
> Also will `boot.js` be depreciated before v1.0?

I only use iOS theme in all my quasar desktop applications. I am not sure if it is due to ripples or anything else, android theme can get painfully slow if you have too many components on a page. I have seen drastic change in performance just by switching from android to ios. FYI, I have a complex layout in my application that have several levels of table (using q-table expand props) and trees. I am ok with the time it takes to render the components once data is loaded, but the time it takes for a button or checkbox to be clicked was causing delays and looked like a performance issue.

**Comment by trsiddiqui** [comment]
@rstoenescu please tell me iOS theme is not going to be discontinued please...!

**Comment by rstoenescu** [comment]
Quasar v1.0 beta released!
https://medium.com/quasar-framework/quasar-1-0-reaching-for-the-stars-284e7716625a
