### ISSUE TITLE
QPopupEdit. Esc key don't cancel edit.

### ISSUE THREAD

**Issue by sontis3** [quasarframework/quasar#2577]
Hi.
Quasar Framework 0.17.12
In standard use (in QTable) after open QPopupEdit and edit value I can not cancel with key "Esc". Popup closed and the value gets saved.
When popup have not Cancel Button then have not possibility discard edited value.

**Comment by rstoenescu** [comment]
Hi, Can you use latest Quasar v0.17.15 and report back? Thank you.

**Comment by sontis3** [comment]
I upgraded Quasar to 0.17.15 and CLI to 0.17.18. The issue exist.
