### ISSUE TITLE
can't scroll with horizontal view

### ISSUE THREAD

**Issue by yeegeek** [quasarframework/quasar#258]
##scroll will not work when flip the phone to horizontal, doesn't work on both safari and chrome

**Comment by rstoenescu** [comment]
Hi, Android or iOS? It should work on both.

**Comment by yeegeek** [comment]
Only tested on IOS, also mac desktop chrome 

![image](https://cloud.githubusercontent.com/assets/3314621/21257215/cf8ee7de-c3b1-11e6-8d69-d649139ce1e9.png)

**Comment by rstoenescu** [comment]
Ok, will investigate.
