### ISSUE TITLE
Touch/Mouse hold issue with Apple Magic Mouse

### ISSUE THREAD

**Issue by tegola** [quasarframework/quasar#2587]
I can't get the touch hold directive to work properly on a Apple Magic Mouse. It's reproducible even in the directive's demo page: https://quasar-framework.org/components/touch-hold.html

After some research I found that the `abort` method gets called after a `mousemove` event. I noticed that clicking the mouse button with a pen the touch-hold handler works every time, so it might be something related to micro movements on the mouse touch panel when keeping the button pressed that may trigger the event.

It might need a move threshold, maybe?

**Comment by dsonet** [comment]
It can't even work well on Chrome desktop (version 70). Also not stable on Safari(iOS 12.1).
Can reproduce in the demo page:
https://quasar-framework.org/quasar-play/apple/index.html#/showcase/touch-directives/touch-hold

**Comment by rstoenescu** [comment]
Hi,

Please reopen if it still reproduces with v1 (I think not).
Thanks.

**Comment by tegola** [comment]
It works properly on v1.

**Comment by rstoenescu** [comment]
@tegola Thanks for confirming!
