### ISSUE TITLE
infinity loop with :="" inside an attribute

### ISSUE THREAD

**Issue by kevingermain** [quasarframework/quasar#2588]
I was searching why I have to kill NodeJS multiple times when I tried to launch my app.
I found that if I forget  :="" in attribute of q-btn for exemple, nodejs will start a loop forever.
It's not a big deal but I lost one hour to find it why.

**Comment by rstoenescu** [comment]
Is this related to https://github.com/quasarframework/quasar-cli/issues/183 ?
Cause I just fixed it and Quasar CLI v0.17.19 is available.

**Comment by kevingermain** [comment]
Not really because I have 0.17.19 and it still happen.

**Comment by rstoenescu** [comment]
Ok, then open up a ticket on the [CLI repo](https://github.com/quasarframework/quasar-cli), but offer a reproduction repo. Thank you.
