### ISSUE TITLE
DataTable: Being able to pass the full object in the format column property

### ISSUE THREAD

**Issue by eliashdezr** [quasarframework/quasar#259]
Like DataTables.net
https://datatables.net/examples/advanced_init/column_render.html

Instead of passing just 1 argument, would be handy to pass also the full object in case you want to mix different values in the same cell.

DevExtreme has also similar, but using an object with multiple properties:
https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#cellTemplate

**Comment by rstoenescu** [comment]
Right, will do. Thanks for the suggestion.

**Comment by smolinari** [comment]
Something to dream about on my part is also an inline editing feature. :smile: But, I know.....one small step at a time. The datatable component itself is really cool! :+1: 

Scott

**Comment by rstoenescu** [comment]
@smolinari Inline editing is something you can do yourself with a custom renderer (through scoped slots). You can use the `q-state` component for this ;)

**Comment by rstoenescu** [comment]
Next Quasar version will allow you to call: `style(cell, row)` and `classes(cell, row)`. Notice the second parameter `row`.
