### ISSUE TITLE
[Request] Tree list - Item actions (with icons)

### ISSUE THREAD

**Issue by AthosB** [quasarframework/quasar#2592]
I am creating an application that requires a listing of nested items (quasar Tree component) but with the ability to add actions next to each items.

```
treeData: [
            label: 'Satisfied customers',
            header: 'root',
            children: [
              {
                label: 'Good food',
                actions: [
                  { 
                    label:'action 1 to item', 
                    icon: 'add Child to Item', 
                    action: addChild(selectedItem)
                  },
                  { 
                    label:'action 2 to item', 
                    icon: 'edit Item', 
                    action: editItem(selectedItem)
                  },
                  { 
                    label:'action 3 to item', 
                    icon: 'rate Item', 
                    action: rateThisItem(selectedItem)
                  },
                  ...
                ],
                header: 'generic',
                children: [
                   ...
                ]
              },
                  ...
            ]
```

I really don't know what the best way/syntax would be to implement this. I just hope the idea/feature request is clear enough. Also I don't know what would be best way to add the function you want to call on button(action) click - string or direct function name?. I came across the need for such a feature several times.
I know there is a workaround which I already implemented on my project:
- Added a panel next to the Tree component and displayed those icons and actions to be performed on the selected item from the tree list but it takes up a lot of space and it's bad UX to have to look around to perform short actions on items on the Tree list
- I think it would be much easier and 'tidy' to just have some icon buttons next to each item (Icons can appear on Item hover) and display the description of the action on a q-tooltip (on icon button hover)

**Comment by AthosB** [comment]
@smolinari  There is the option to customize nodes of the Tree component, and this 'request' might be solved using that in a much easier way( I am not sure when this was added, but couldn't find it when looking for a way to customize the Tree component). I will have to run some tests to see if that is the case, otherwise I can request to reopen the issue

**Comment by smolinari** [comment]
@AthosB - Thanks for the explanation. Yes, there are the header and body slots. Theoretically you can use them to build out a new tree component with crud capabilities. 

Scott

**Comment by smolinari** [comment]
This is a start....:smile:

https://jsfiddle.net/0jzo4scn/

Scott

**Comment by AthosB** [comment]
Thank you! I managed to integrate some customization as you indicated with some 'hiccups', I moved to the quasar forum to seek help from others to see if there is a perfect way to develop what I wanted. If I stumble upon any bugs or feature enhancements I will update the issue. Thank you again for your help
