### ISSUE TITLE
Q-modal("position=bottom") doesn't work in Safari

### ISSUE THREAD

**Issue by artem0071** [quasarframework/quasar#2596]
### Software version
Quasar: 0.17
OS: MacOS / IOS
Browsers: Safari

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/hat94yrn/1/

### What did you get as the error?
In Chrome browser there is all good. But when open this example in Safari browser there will be only dark background when you click on button.

### What were you expecting?
Expecting working modal in Safari as it is in Chrome

### What steps did you take, to get the error?
Click on button
Profit)

### Comment
I found that it is something wrong with modal div(.modal-content .column .no-wrap)
If manually change the height, it will show modal (default is 'auto')
So I think that something wrong with calculating of height in Safari...

Nevertheless I don't know why it is working in Chrome and doesn't in Safari

**Comment by pdanpdan** [comment]
Hi.

Can you please try this one and report back: https://jsfiddle.net/hat94yrn/16/show/

I don't have safari, but this works in chrome, firefox and IE.

**Comment by rstoenescu** [comment]
I cannot reproduce on Safari.

**Comment by artem0071** [comment]
@pdanpdan no, it doesn't work..
https://ibb.co/ehKWUz

**Comment by artem0071** [comment]
@pdanpdan also on iphone
https://ibb.co/ccQc2K

**Comment by artem0071** [comment]
@rstoenescu Don't know.. May be there different versions
MacOS: 10.12.6 (16G29)
Safari: 10.1.2 (12603.3.8)
IOS: 10.3.2 (14F89)

**Comment by artem0071** [comment]
Remove "position=bottom" and it is working
But needed this attribute..

So, I still think that it is css calculating error on Safari..

**Comment by rstoenescu** [comment]
Seems like it is reproducing only on iOS Safari.
Indeed, you need to set a height when using position and a QModalLayout in order for it to work correctly on iOS, otherwise we bump into iOS flex issues. No way to work around this unfortunately :(

Example: `:content-css="{minHeight: '40vh'}"`
