### ISSUE TITLE
DataTable: Asign cell value type to enhance sorting

### ISSUE THREAD

**Issue by eliashdezr** [quasarframework/quasar#260]
Without this, dates and formatted numbers cannot be sorted correctly.

**Comment by rstoenescu** [comment]
@eliashdezr Hi, what do you have in mind? A new prop for each column definition to say which type of field is it (String, Number, Array etc)?

**Comment by rstoenescu** [comment]
Enhanced sorting a lot. The commit above will be available in Quasar v0.11.
