### ISSUE TITLE
iOS Safari QSearch with QAutocomplete list below keyboard

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#2600]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers: safari
iOS: 11.4.1
Android:
Any other software related to your bug:

### What did you get as the error?
When I tap the search field, it gets focus and the keyboard opens. The field is scrolled up as expected and I can type to search. The autocomplete list shows up but if ends up under the keyboard too much ( like in landscape ) and I try to close the keyboard using the button on the keyboard ( not by touching in safari ) so I can pick an item in the autocomplete, the list is closed.

### What were you expecting?
I expected the list to remain open unless I touched inside the safari browser.

**Comment by rstoenescu** [comment]
Fixed in future v0.17.17.
