### ISSUE TITLE
Step content is inserted multiple times when switching from Vertical to Horizontal

### ISSUE THREAD

**Issue by sskwrl** [quasarframework/quasar#2601]
### Software version
```
Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.11.4

Global packages
  NPM                           5.6.0
  yarn                          1.9.4
  quasar-cli                    0.17.19
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages
  quasar-cli                    0.17.19 (Quasar Framework CLI)
  quasar-framework              0.17.16 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.6   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)
```

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/sskwrl/hn7mpc0s/76

### What did you get as the error?
When I switch the stepper from vertical to horizontal, the contents of the step block are inserted without clearing the existing contents resulting in multiple copies of the nearly same contents.  (The down chevrons indicate which were left over from the vertical stepper and the right chevron is the new one.  The right chevron is the only one that will actually work when clicked.)

![image](https://user-images.githubusercontent.com/42022576/45900475-eabc4900-bdad-11e8-8fb9-7dd8f16d1243.png)

### What were you expecting?
One copy of the step contents

![image](https://user-images.githubusercontent.com/42022576/45900652-60281980-bdae-11e8-97f2-40c8529ac897.png)

### What steps did you take, to get the error?
1. Create Stepper with vertical set to false
2.  set vertical true
3.  set vertical false <-- This is when the error happens
4.  repeat steps 2 and 3 to see the error multiple times.

**Comment by rstoenescu** [comment]
Fixed in future 0.17.17
