### ISSUE TITLE
Upgradin v0.16 to v0.17

### ISSUE THREAD

**Issue by devlamine** [quasarframework/quasar#2607]
After upgrading to 0.17 I have this error :
`Error: babel-plugin-transform-imports: import of entire module quasar not allowed due to preventFullImport setting.`
I wante to change value for preventFullImport in the file babelrc.js but it’s extended and crashed by quasar-cli in the file /home/devlamine/sites/pr/client/node_modules/quasar-cli/lib/webpack/create-chain.js /:

```
line 113

    .use ( 'Babel-loader')
      .loader ( 'Babel-loader')
        .Options ({
          extends: appPaths.resolve.app ('babelrc'),
          plugins: cfg.framework.all! == true? [
            [
              'transform-imports', {
                quasar: {
                  transform: `quasar-framework / dist / babel-transforms / imports. $ {cfg.ctx.themeName} .js`,
                  preventFullImport: true
                }
              }
            ]
          ]: []
```
When I change prevent Full Import: true by false it works !!
I can do framework.all: true in file quasar.conf.js ? there will be no impact in the other functionality ?

**Comment by rstoenescu** [comment]
Hi,

`import { Quasar } from 'quasar'` instead of `import Quasar from 'quasar'` when you are setting quasar.conf > framework: 'all'
