### ISSUE TITLE
Disable Rounded corners on QTabs

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#2608]
In some cases, the rounded corners of the QTabs plugin can actually "break a design".

![screen shot 2018-09-24 at 15 43 26](https://user-images.githubusercontent.com/35242872/45956062-ebedb000-c011-11e8-958a-09d4c4b151ff.png)

Proposal: allow the dev to turn this styling off with a prop.

**Comment by codenamezjames** [comment]
I ran in to this my self the other day and just used CSS but it would be cool to have a prop or a class

**Comment by rstoenescu** [comment]
Done for v1.0
