### ISSUE TITLE
q-numeric with 0.1 step lacks rounding

### ISSUE THREAD

**Issue by caex** [quasarframework/quasar#261]
Hi,

````
<q-numeric :min="9" :max="199" :step="0.1" v-model="foo"></q-numeric>
````
foo === 22.1

Click the **+** button

### What is expected ?
foo === 22.2

### What is actually happening ?
foo === 22.200000000000003

Cheers

**Comment by rstoenescu** [comment]
Will fix it. Thanks for reporting!

**Comment by vuchl** [comment]
Yes the step attribute is not paassed down to the input
https://github.com/quasarframework/quasar/blob/dev/src/vue-components/numeric/Numeric.vue#L4-L16

**Comment by rstoenescu** [comment]
@vuchl it doesn't have to be passed to the input. Look down the file.

Who cares for an easy PR on this?

**Comment by vuchl** [comment]
@rstoenescu hmm. for me the code looks good. can't spot it. but if you allready identified the cause, why not commit the fix yourself?

**Comment by rstoenescu** [comment]
You can't even imagine how many things I am handling. Eventually I'll make a fix myself for this if no one takes it, but it would speed up things if easier tickets are taken from my queue.

For this ticket there's the Javascript floating point issue occuring (Google it). The fix would be something like `parseFloat(number).toPrecision(X)` when updating the model (where X is the precision of the step).
