### ISSUE TITLE
Request - Menu for toolbar with Hierarchy feature.

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#2613]
Hello Team;

Could you please offer a standard Menu component that can be used on tool bar which offers hierarchy children?  Generally these menu types are very useful when developing Line of Business application, which we can give access to many parts of the app to users with minimum amount of space taken and minimum number mouse clicks.

Hope this helps!
..Ben

**Comment by smolinari** [comment]
It is possible with OOB stuff. :smile: 

https://forum.quasar-framework.org/topic/856/solved-q-toolbar-dropdown-menu-possible/3

Scott

**Comment by smolinari** [comment]
Aha! Quasar has that too. It's just not called a menu. :smile: 

https://quasar-framework.org/components/button-dropdown.html

Notice the built in router syntax sugar. I realize that isn't what you are looking for exactly either, but you can easily form those buttons to look like tabbed navigation. :wink:  

Scott

**Comment by rstoenescu** [comment]
@BenHayat Those are QBtns with QPopover with QList items. It is redundant to build a QMenu then add a million properties to it to be able to customize everything. Take a look at QPopover (works as direct child of any element/component). It's more powerful than what other frameworks have.

**Comment by BenHayat** [comment]
@rstoenescu 
No problem Sir. I'll look into your recommendations.
A small sample would be a great addition.

Thanks!

**Comment by BenHayat** [comment]
@smolinari 
Thanks Scott!
