### ISSUE TITLE
0.17.16 uploader dont trigger @add, @start ...

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#2614]
### Software version

Quasar: 0.17.16
OS: Windows 10
Node: 8.9.4
YARN: 1.7.0
Browsers: Chrome
iOS: - 
Android: - 
Any other software related to your bug:

**Comment by pdanpdan** [comment]
It looks like it does emit both @add and @start
https://codepen.io/pdanpdan/pen/rZEvBo?editors=1011

**Comment by rstoenescu** [comment]
Please reopen with at least a jsfiddle. Thank you.
