### ISSUE TITLE
0.17.16 uploader dont trigger @add, @start when have extensions - [reopened]

### ISSUE THREAD

**Issue by LuizLeite** [quasarframework/quasar#2615]
Hi again.
See codepen now with a updated.
When have extensions dont work.

https://codepen.io/LuizLeite/pen/ZMdVwg?editors=1011

**Comment by rstoenescu** [comment]
The correct way to use extensions is: `extensions=".jpg,.png"`, NOT `extensions="*.jpg,*.png"`

**Comment by LuizLeite** [comment]
OK, Sory.
