### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.$el.contentDocument.defaultView')

### ISSUE THREAD

**Issue by 123mitnik** [quasarframework/quasar#2619]
After creating clean project 

`quasar init client`

and then

`quasar dev -m ssr --history`

` Dev mode.......... ssr`
` Quasar theme...... mat`
` Quasar CLI........ v0.17.19`
` Quasar Framework.. v0.17.16`
` Debugging......... enabled`

on  QResizeObservable.js 65 -  i receive : `TypeError: undefined is not an object (evaluating 'e.$el.contentDocument.defaultView')`
<img width="1084" alt="screen shot 2018-09-26 at 22 04 34" src="https://user-images.githubusercontent.com/1234337/46104040-0030d900-c1db-11e8-9806-d4d1ff272870.png">

if inside quasar.conf.js add `framework: 'all'` OR `animations: 'all'` (even i remove them later)
i start receiving the same on load - quasar.mat.esm 
<img width="1079" alt="screen shot 2018-09-26 at 22 15 35" src="https://user-images.githubusercontent.com/1234337/46104047-0626ba00-c1db-11e8-936b-37248ff5c14c.png">

Can You please advice on how to battle this

**Comment by rstoenescu** [comment]
Hi,

What is the browser are you using in this case?

**Comment by rstoenescu** [comment]
Hi,

Please reopen with more details. A reproduction repo helps us a lot in helping you, otherwise we are just wasting time for everybody.

**Comment by otemnov** [comment]
The issue occurs for me with SSR during google mobile bot index process.

**Comment by marcos-vinicius-dev** [comment]
Hi,
The issue occurs for me too. Exactly in this document QResizeObservable.js. @rstoenescu

**Comment by marcos-vinicius-dev** [comment]
![Captura de Tela 2019-06-17 às 11 51 11](https://user-images.githubusercontent.com/37404158/59614926-0c0d5400-90f8-11e9-84a7-fbb1701289d8.png)
@rstoenescu

**Comment by rstoenescu** [comment]
> Please reopen with more details. A reproduction repo helps us a lot in helping you, otherwise we are just wasting time for everybody.

Unfortunately, without a reproducing repo, I can only make a blind fix (see above). Please check rc.5 when it's released. Thank you.

**Comment by otemnov** [comment]
@rstoenescu I can't reproduce the issue using any local env I have. But it can be reproduced in google search console. this is the main reason why it should be fixed :)

1. create a page with this component
2. enable SSR
3. open https://search.google.com, and use Test Live Url feature
4. open Mobile Usability report, and check javascript console messages.

**Comment by rstoenescu** [comment]
@otemnov Is https://search.google.com working for you? I get a 404 page.

**Comment by rstoenescu** [comment]
Opened their console. Looked at https://quasar.dev -- seems like it's got 0 errors. But anyway, guarded that unfortunate line so it should not report any problem with it anymore with rc.5 (to be released in a few hours max).
