### ISSUE TITLE
screen prefixes not working with button size?

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#262]
Hi,
I have fab in modal (with layout).
Looks like `gt-md-big` totally not working. Any idea why? Is it bug in Q stylus file?

**Comment by rstoenescu** [comment]
Hi, `gt-md-big` does not exist. http://quasar-framework.org/api/css-grid-layout.html#Visibility

**Comment by murbanowicz** [comment]
Prefix is `gt-md` so it should work with `big` for button ?
Or it works only for grid elements ?

**Comment by rstoenescu** [comment]
You can use `gt-md` (and all other visibility CSS classes) on any element. But `gt-md-big` does not exists. I believe what you want is `gt-md big` (2 CSS classes, not one linked by the hyphen).
