### ISSUE TITLE
QInput with type="number" doesn't prevent from inputting "abc" on Safari

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2626]
Hello!

QInput with type="number" works inconsistently across Chorme and Safari https://jsfiddle.net/waugrryy/7032/

In Chrome:
1) type in "abc"
2) "abc" is ignored 👍 

In Safari:
1) type in "abc"
2) "abc" is NOT ignored 👎 
3) "abc" is removed on blur

Thanks!

**Comment by pdanpdan** [comment]
Try adding pattern, like here
https://jsfiddle.net/waugrryy/7034/

**Comment by jean-moldovan** [comment]
Thanks for your reply. Is this issue Quasar related?

**Comment by pdanpdan** [comment]
No, Safari feature :imp: 
https://github.com/angular/material/issues/8502
