### ISSUE TITLE
Documentation on how to import components just using quasar-framework in existing application

### ISSUE THREAD

**Issue by brokenalarms** [quasarframework/quasar#263]
This does not exist at all and I am needing to hunt through the source code / install the CLI to try and set it up...

Copying some of the code showing how to instantiate Quasar from the template app, I have:

```javascript
import App from './App.vue';
import Quasar from 'quasar-framework';

Vue.use(Quasar);

Quasar.start(function(){
    new Vue({ // eslint-disable-line no-new
        el: '#q-app',
        render: (h) => h(App)
    })
})
```
...but this errors on `Vue.use`:
```
Uncaught TypeError: _c is not a function
    at Proxy.render (quasar.common.js:1109) 
```

I just want to import `<q-checkbox>` haha! Is the component portion reliant on the whole Webpack/CLI build chain?

**Comment by Omniwoof** [comment]
There was an issue with one of the dependencies for Quasar and this issue got fixed with 0.10.3: https://github.com/quasarframework/quasar/issues/252

If you update Quasar with NPM it will get fixed.

**Comment by brokenalarms** [comment]
I'm using 0.10.3 of `quasar-framework`, I installed it this morning...

**Comment by rstoenescu** [comment]
Hi all,

1. You also need Vue 2.1.6.
2. You can't import just one of the components. Currently it's all or nothing.

@brokenalarms Is 2. what you are looking for?

**Comment by brokenalarms** [comment]
Thank you, updating to Vue 2.1.6  fixes this particular issue so given this is required the `package.json` probably should be updated to save people running into this issue in future some time. Though this Vue update breaks my entire app since it no longer seems to support exporting Vue.components, that's no longer an issue for you. Thank you for your fast update on this!

**Comment by brokenalarms** [comment]
sorry to revive but also not present is how to import the needed css for these components. Is there a built version for iOS or does this require the build system to prepare the `.styl` files?

**Comment by rstoenescu** [comment]
@brokenalarms I believe the default template explains it in `src/main.js`:

```js
// === DEFAULT / CUSTOM STYLE ===
// WARNING! always comment out ONE of the two require() calls below.
// 1. use next line to activate CUSTOM STYLE (./src/themes)
// require(`./themes/app.${__THEME}.styl`)
// 2. or, use next line to activate DEFAULT QUASAR STYLE
require(`quasar/dist/quasar.${__THEME}.css`)
// ==============================
```

__THEME is replaced by the theme you make a build with. (`quasar dev mat` or `quasar dev ios` -- same for `quasar build [theme]`)

**Comment by brokenalarms** [comment]
Hrm, well yes I saw that - but it still isn't really clear enough for my use case which I'd thought was reasonably standard (just using the components in an existing project, not taking the whole build system/cli or starting with the template app):

- that's `main.js` in the template app, which requires installing template app to see/get that explanatory line;
- it `require`s a css file that  doesn't appear to exist in `node_modules/quasar-framework` and so must be put there by the `quasar-cli` build system;
- requiring the css itself needs browserify/webpack rule etc
- uses a global `_THEME` variable that wouldn't be present when just importing (or is it just meant to be a placeholder?)

And so on. To be clear - is it not possible to just do the following without using the template/cli?

```javascript
<template>
  <q-checkbox /> // I can get this to appear but with no styles applied - thought they would just be applied care of qcheckbox.vue having a <style> tag but appears to not be the case?
</template>
<script>
import Quasar from 'quasar-framework';

Vue.use(Quasar);

function(){
    new Vue({
        el: '#q-app',
    })
}
</script>
```

Thanks very much for your help with this. I'm just trying to understand whether quasar can be used as a component toolkit, or whether it needs all the cli etc which we can't really switch to mid-project.

**Comment by rstoenescu** [comment]
@brokenalarms Quasar cannot be progressively added to a project. It's an all or nothing deal.

1. If you're not using a Quasar app template / boilerplate then yes, some of the files may appear as if they do not exist. But in the template they do.
2. All webpack rules are in the default app template.
3. _THEME is a token that gets replaced by webpack (if you're using the default Quasar app template) so it's not even a variable.

Bottom line, **sorry but you cannot cherry-pick components from Quasar**. All Quasar code is written with performance in mind, and this sometimes leads to not being able to cherry-pick. There are a lot of reasons, most important one being that Quasar is not just a component library. It deals with much much more. Themeing assumes there are some CSS classes attached to the body. Cordova needs its own JS to be included and Quasar deals with starting a Cordova app with the help of `Quasar.start()` method. Reasons after reasons. Won't go into details as this would take me a day :)

**Comment by brokenalarms** [comment]
OK, thank you very much for that clarification. That's all totally fair -
but given I spent a day trying to bring this into our project to make use
of the components, as it seemed a reasonable proposition given the separate
quasar-framework portion, I think it would be great to put something in the
readme to this effect.

I'm going to try and use this in a personal project from scratch...Now if I
can just figure out how to stop eslint from completely blocking production
by overlaying the browser window whenever there is a single lint error!

**Comment by rstoenescu** [comment]
Not recommended, but here it is: http://quasar-framework.org/guide/app-linter-configuration.html (see remove linter section)

**Comment by brokenalarms** [comment]
Great, thank you! Well, I'll always auto fix with lint before I push code,
but if I'm trying to rapidly create something then I don't want the whole
thing blocked and have to fix/reload just for missing a semi colon (or
adding it, as the case may be here by these rules, which also means fully
configuring eslint to your style before again being able to just start work
since this makes the project so dependent on everything being perfect in
setup first).

Don't find it that helpful when an auto fix option exists anyway, and in
the CLI it also pushes more important actual breaking issues out of sight,
so good to have the option. I understand the reasoning though but am just
trying to add some differing use case info. Thanks again.

On Sun, Dec 18, 2016, 9:31 AM Razvan Stoenescu <notifications@github.com>
wrote:

Not recommended, but here it is:
http://quasar-framework.org/guide/app-linter-configuration.html (see remove
linter section)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/quasarframework/quasar/issues/263#issuecomment-267834394>,
or mute the thread

**Comment by rstoenescu** [comment]
Glad to be able to help!

**Comment by BrennaEpp** [comment]
> @brokenalarms Quasar cannot be progressively added to a project. It's an all or nothing deal.
> 
> Bottom line, **sorry but you cannot cherry-pick components from Quasar**. All Quasar code is written with performance in mind, and this sometimes leads to not being able to cherry-pick. There are a lot of reasons, most important one being that Quasar is not just a component library. It deals with much much more. Themeing assumes there are some CSS classes attached to the body. Cordova needs its own JS to be included and Quasar deals with starting a Cordova app with the help of `Quasar.start()` method. Reasons after reasons. Won't go into details as this would take me a day :)

@rstoenescu Is this still the case? I'm trying to understand all what Quasar deals with in terms of Cordova and whether I can get rid of Quasar's themeing while keeping other stuff, or if I can at least just use vue-cli-plugin-cordova + some quasar components
