### ISSUE TITLE
Bug: q-context-menu show method doesn't work anymore

### ISSUE THREAD

**Issue by flopail** [quasarframework/quasar#2633]
Hi all,
:)

In my Quasar app, I added a button which permits to open context menu with a simple left click and not only with right click (basic usage).  My code below has been working with Quasar v0.17.12 until I upgrade to v.0.17.16. Some idea?

```html
<q-context-menu ref="ctxmenu">My context menu...</q-context-menu>
...
<q-btn @click="openCtxMenu()">Show menu</q-btn>
```
```js
methods: {
  openCtxMenu () {
    this.$refs.ctxmenu.$refs.popup.show()
  }
}
```
Thanks.

**Comment by pdanpdan** [comment]
It should work, even if it's not supported and recommended.
Why don't you just show the menu as a popover? You can put it in a component and reuse it.
Anyway, please provide a fiddle showing the problem.

**Comment by pdanpdan** [comment]
You are using refs in a v-for - this will create an array of refs - this is a vue thing, it has nothing to do with Quasar.

I updated the fiddle for you: https://jsfiddle.net/kaLrdn81/58/

You have `show(event)` method on `QContextMenu` so you don't need to go deeper and call `show` on popover.

**Comment by flopail** [comment]
Thank you very much @pdanpdan!

**Comment by smolinari** [comment]
https://jsfiddle.net/smolinari/sk7t2d1c/

It works, if you put a `[0]` as an array key. However, the menu/ popover doesn't show in the right position. 

Why do you want this functionality? A context menu is supposed to be opened with the right mouse button, not the left. If you want a menu to open with a left mouse button, use a straight q-popover. 

Scott
