### ISSUE TITLE
Q-Select does not receive .focus in ref

### ISSUE THREAD

**Issue by douglasfabianob** [quasarframework/quasar#2639]
I try to add the focus() in ref but it does not work.
Ex: this.$refs.select.focus()
JsFiddle: https://jsfiddle.net/n2sbgrd6/1/

But with elementById it works.
Ex: document.getElementById('select').focus()
JsFiddle: https://jsfiddle.net/sh3tujov/2/

**Comment by douglasfabianob** [comment]
I would like it when you confirm a form, it would stay in a specific select to continue filling.

**Comment by smolinari** [comment]
Should the select be open for selection?

Scott

**Comment by smolinari** [comment]
Also, if the form has a confirmation button, I would imagine that is a chance to add a method to open the selection?

Scott

**Comment by douglasfabianob** [comment]
Yes, that can solve the problem. Thank you.
