### ISSUE TITLE
[ios] Search component input text slightly misaligned

### ISSUE THREAD

**Issue by cj** [quasarframework/quasar#264]
![](http://image.prntscr.com/image/48111dac7eff46b5af5c9b6721d025ef.png)

Safari Version: `10.0.2`

**Comment by rstoenescu** [comment]
Hi. Already fixed. Will be available in next Quasar version. See #220

**Comment by cj** [comment]
Great.  I'll work off the github repo.

**Comment by cj** [comment]
@rstoenescu there's still one issue with it, unlike the other browsers the input its self isn't center aligned ![](http://image.prntscr.com/image/f3922993924d46e998892bac6c7b7067.png)

**Comment by cj** [comment]
Here's what it looks like in chrome:

![](http://image.prntscr.com/image/1a78e44d03174e0da9481b4fc3dd40ef.png)

**Comment by rstoenescu** [comment]
Hmm, will look into it. Thx for reporting.

**Comment by cj** [comment]
Not a problem.

**Comment by rstoenescu** [comment]
Safari iOS sux bad :) it's the new IE.
