### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT in android dev mode

### ISSUE THREAD

**Issue by SiveriaST** [quasarframework/quasar#2640]
I try to run my app on android in the dev mode and I use the command: quasar dev -m cordova -T android

But I get the ERR_CONNECTION_TIMED_OUT (http://10.51.243.28:8080/) alert error.

**Here is the log of the build:**

```
Dev mode… cordova
Quasar theme… mat
Quasar CLI… v0.17.16
Quasar Framework… v0.17.13
Debugging… enabled

app:quasar-conf Reading quasar.conf.js +0ms
app:external-ip Detected external IP 10.51.243.28 and using it +12ms
app:dev Checking listening address availability (10.51.243.28:8080)… +1ms
app:webpack Extending Cordova Webpack config +955ms
app:generator Generating Webpack entry point +70ms
app:dev-server Booting up… +21ms
```

**Here is my ipconfig log:**

```
Connection-specific DNS-Suffix . . . . . :
Link-local IPv6 Address . . . . . . . . . . . .: fe80::bd9a:5369:ee79:30d9%4
IPv4-Address . . . . . . . . . . . . . . . . . . . . : 10.51.243.28
Subnet Mask . . . . . . . . . . . . . . . . . . . . : 255.255.255.248
Default Gateway . . . . . . . . . . . . . . . . . : 10.51.243.25
```
So as I understand it picks the correct IP… have to note that at https://www.myip.com/ I get totally another one: 213.87.144.115

Now in src-cordova config.xml loadUrlTimeoutValue is 700000 and after timeout the android displays the connection error.

**And curious that if I build the apk it works totally correct.**

I can’t debug my android… really need help!

**Comment by SiveriaST** [comment]
I have found out the reason of the issue. This behavior was because I used the external GPRS modem with my note... And when I connected to Internet through the common wi-fi it connected to the IP without any problems... It looks like there are some limitations by my provider for making bridge for third-party devices.

There is only one problem... For some reason it doesn't load the code sources but the DOM and console are ok...

**Comment by rstoenescu** [comment]
Hi,

Are you referring to sourcemaps? Sourcemaps are handled by Webpack entirely. They had a lot of problems with browser vendors on them in the sense that some webpack sourcemap types don't always work (even though they should!). Might be worth taking a look at [webpack's devtool](https://webpack.js.org/configuration/devtool/) and trying out different types until you find the right one for you.

Changing devtool:
```js
// quasar.conf

extendWebpack (cfg) {
  cfg.devtool = '...'
}
```

Thank you.
