### ISSUE TITLE
Mobile keyboard over text field

### ISSUE THREAD

**Issue by manelclos** [quasarframework/quasar#2641]
Hi,

Mobile keyboard covers textfield, you can't see what you are typing. This seems to be a regression as per #406 it was fixed on 0.14.

I also tried proposed flex changes in #406 but didn't work. Tried both q-page with fullscreen class and a custom fullscreen layout. The page won't "scroll up" so the textfield(s) are always covered.

### Software version
0.17.10 and 0.17.16 (updated to check if was fixed)

Operating System         	Darwin(17.7.0) - darwin/x64
NodeJs                   	10.6.0

Global packages          	
  NPM                    	6.1.0
  yarn                   	1.7.0
  quasar-cli             	0.17.19
  vue-cli                	2.9.6
  cordova                	8.0.0

Important local packages 	
  quasar-cli             	0.17.19
  quasar-framework       	0.17.16

**Comment by manelclos** [comment]
Invalid: the q-tab-pane had the fixed attribute. Sorry.

**Comment by syshex** [comment]
@manelclos what does this mean? "Had the fixed attribute"

I'm having the same problem with a page that has Tabs and q-tab-panes in it, particularly on ios

**Comment by rstoenescu** [comment]
@syshex The rendering engine on iOS is extremely buggy and seems like the Apple developers are not making any progress on fixing the numerous bugs on "position: fixed" or when the keyboard gets shown on screen. We highly recommend installing and using WkWebview https://github.com/apache/cordova-plugin-wkwebview-engine to replace the default webview on iOS. However this comes with a few gotchas (info on the link).

**Comment by syshex** [comment]
@rstoenescu sounds good, gave it a try and I'm having problems with the axios calls to a few ws I require for the app. Will try to debug tomorrow to see if I can get it to work.

**Comment by manelclos** [comment]
Hi @syshex, I had something like this:
`<q-tab-pane class="bg-blue-grey-1 fit fixed" name="entra" v-touch-swipe.horitzontal="handler">`

See the "fixed" class. I removed it and that fixed the problem.
