### ISSUE TITLE
Feature request: 'allow-duplicates' for chips-input

### ISSUE THREAD

**Issue by mame82** [quasarframework/quasar#2644]
I have a use case, where I need to dynamically change the content of an `Int32Array`, including adding and removing elements.

Quasars chips-input is the optimal solution (when a computed property with getter and setter is used to convert from VM string Array to the Int32Array and back).

Now the array I'm managing is allowed to hold duplicated values, which I only partially could do with quasar. My first intention was to use the `duplicate` event to trigger the `add` method of chips-input, like below:

```
<q-chips-input v-model="SequenceValuesWithDuplicates" ref="allowdups" @duplicate="this.$refs.allowdups.add($event)"></q-chips-input>
```

This, unfortunately, but not surprisingly, ends up in a recursive loop.
Thus I added a custom method to the parent component, which adds the needed element to backing Int32Array of my computed property, which serves a v-model for the chips-input.

```
<q-chips-input v-model="SequenceValuesWithDuplicates" @duplicate="SequenceValuesWithDuplicatesAddToBackingArray($event)"></q-chips-input>
```

It turns out adding duplicates this way works quite well, but has two remaining issues:
- The `add` method of chips method is bypassed
- If a value is typed to a chips-input and added afterwards, the "textfield input" is cleared and a chip added to the field. If a duplicate is added (by manipulating the backing array of the computed property which serves as v-model), the chip is added to the input, but the entered value isn't cleared from the textfield.

Using arrays with duplicated elements seems to be a valid use case to me. It could be avoided to bypass the add method of chips-input, if a property `allow-duplicates` would be introduced, which could be used like this.

```
<q-chips-input v-model="SequenceValuesWithAllowedDuplicates" allow-duplicates></q-chips-input>
```

This wouldn't break current functionality of chips-input.

**Comment by mame82** [comment]
![quasar-issue-chips-inpu](https://user-images.githubusercontent.com/13119970/46279832-84cc8000-c56a-11e8-8976-2861ae39aec7.png)

The image shows the "hack" I'm currently using. Pressing enter or the add icon, allows adding another value `1`, but the input isn't cleared. Pressing enter multiple times adds multiple `1` values. This is due to bypassing the chip-input component logic for adding values

**Comment by metalsadman** [comment]
use @duplicate(val) event, `<q-chips-input v-model="SequenceValuesWithAllowedDuplicates" @duplicate="dupe" />`  then at methods `dupe` push the duplicate value in your model.

**Comment by mame82** [comment]
Exactly what I described, but when the input is added as chip it doesn't get cleared from the input field (in contrast to a non duplicate input which is cleared after the chip is added).

**Comment by metalsadman** [comment]
> Exactly what I described, but when the input is added as chip it doesn't get cleared from the input field (in contrast to a non duplicate input which is cleared after the chip is added).

oh i see, sorry didn't see that. anyway the work around is to put a ref for your q-chips-input, then on your duplicate method call `this.$refs.yourQchipsInputRef.input = ''`, that should clear the duplicate value. https://codesandbox.io/s/v8y7p86793

**Comment by rstoenescu** [comment]
This is now allowed (unless configured otherwise) in future v1.0 through the smarter QSelect (which includes QChipsInput functionality with a LOT more features and flexibility).
