### ISSUE TITLE
Feature request: AutoComplete with scoped slot for search result items.

### ISSUE THREAD

**Issue by maciekkus** [quasarframework/quasar#2649]
QAutoComplete - by default search results items are QItemsWrapper components with label and sublabel passed in.
Could we have slot for custom content of search result?
In my project, along with label and sublabel I would like to display extra informations related to found items.

**Comment by rstoenescu** [comment]
Hi,

This is scheduled for v1.0 (next version).

**Comment by rstoenescu** [comment]
Done in v1.
