### ISSUE TITLE
[BUG] date.getWeekOfYear returns wrong week number for 12-31-2018

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#2653]
quasar-cli: 0.17.19
OS: Windows 10
Node: 10.6.0
Browsers: Chrome

### What did you get as the error?
```Javascript
import { date } from 'quasar'
let newDate = new Date(2018, 11, 31) // December 31th, 2018
let week = date.getWeekOfYear(newDate)
```
week 1 is returned.

### What were you expecting?
week should be 53

**Comment by pdanpdan** [comment]
This returns the ISO week number.
See https://www.epochconverter.com/weeks/2018
https://en.m.wikipedia.org/wiki/ISO_week_date

**Comment by smolinari** [comment]
Dan was faster.... 👍 Was looking up the ISO Week. 

Scott

**Comment by topvis** [comment]
Thank you all.
