### ISSUE TITLE
How to config the Q-uploader limit size?

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [quasarframework/quasar#2659]
Hey guys,

I upload a file by q-uploader. There is a problem is the component just can upload file < 2M.
But, I want to upload a big file which size > 1G. So how can I config the Q-uploader limit size?

Thx.

**Comment by pdanpdan** [comment]
There is no size restriction in QUploader. Can you please add some details on what problem do you have?
Server side implementation for accepting uploaded files, errors you have in browser, ...

**Comment by rstoenescu** [comment]
@Shaunchenzhaojin Use the `filter` Function prop on QUploader to filter out unwanted files to be uploaded -- this function is called when user adds file(s).

**Comment by Shaunchenzhaojin** [comment]
Thanks @pdanpdan and @rstoenescu .
I config my nginx server side and problem was solved !
