### ISSUE TITLE
why depend 'moment'?

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#266]
the `package.json` generated by `quasar-cli` has a dependency of `moment`, but it seems there is no place in the project to use `moment`.

**Comment by smolinari** [comment]
It is needed in the Datetime component, as one example. 

https://github.com/quasarframework/quasar/blob/dev/src/vue-components/datetime/Datetime.vue

Scott

**Comment by beeplin** [comment]
got it. Thanks~
