### ISSUE TITLE
Reduce number of errors on missing required property (q-select)

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#2662]
This bug is a bit tedious, so please close it if you think it is stupid...
I forgot to add _options_ property to a _q-select_, and noticed that I many errors in the console, from which only the first one was helpful, and the other are just a result of the cause described by that first error message.

### Software version

$ quasar info

Operating System                Darwin(17.7.0) - darwin/x64
NodeJs                          10.11.0

Global packages                 
  NPM                           6.4.1
  yarn                          1.10.1
  quasar-cli                    0.17.19
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages        
  quasar-cli                    0.17.19 (Quasar Framework CLI)
  quasar-framework              0.17.16 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.6   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/tomers/v8mb0uf1/

### What did you get as the error?
I got:
`vue.runtime.esm.js?2b0e:587 [Vue warn]: Missing required prop: "options"` <-- this is perfect
But also got a bunch of other errors:
`vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in getter for watcher "visibleOptions": "TypeError: Cannot read property 'map' of undefined"`
This is due to code such as:
```
visibleOptions () {
      let opts = this.options.map((opt, index) => Object.assign({}, opt, { index }))
```

### What were you expecting?
I wonder if there is an elegant way to hide all the other errors other than `Missing required prop`. All the other errors originate from the first one, so they are basically just noise...

### What steps did you take, to get the error?
Create _q-select_ item without _options_

**Comment by rstoenescu** [comment]
Hi,

Creating a QSelect with no options has no meaning. Fill it with an empty array at least.
