### ISSUE TITLE
Non Passive Event Listener in touch-pan.js

### ISSUE THREAD

**Issue by m0dch3n** [quasarframework/quasar#2665]
I get the following error:
`
touch-pan.js?6642:173 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
`

## Software version

Quasar: 0.17.17
Browsers: Chrome 69.0

In [touch-pan.js](https://github.com/quasarframework/quasar/blob/e043d5e43ffbef78e9ad671ec4019a059920a57f/src/directives/touch-pan.js#L173) `touchstart` and `touchmove` need to be adapted...

**Comment by m0dch3n** [comment]
I investigated a little, it seems, the passive mode is already handled.

https://github.com/quasarframework/quasar/blob/e043d5e43ffbef78e9ad671ec4019a059920a57f/src/directives/touch-pan.js#L81

I'm using a QCarousel with 3 Slides and because `preventDefault` is true, the passive mode is not added...

**Comment by m0dch3n** [comment]
The error is also shown in your [examples](https://quasar-framework.org/quasar-play/android/index.html#/showcase/media/carousel), or in this [codepen](https://codepen.io/modchen/full/BqWvpa/)

**Comment by rstoenescu** [comment]
If you are using event.preventDefault() in your handler, use the "mightPrevent" modifier. Otherwise, for performance reasons (smooth scroll) the directive assumes you won't call preventDefault().
