### ISSUE TITLE
table rows per page bug in IE11

### ISSUE THREAD

**Issue by huyang271** [quasarframework/quasar#2666]
Quasar Version: v0.16.0,

![image](https://user-images.githubusercontent.com/32186505/46727073-5cebc380-ccb2-11e8-879d-9025ef5bed8a.png)

help me,please!!!

More details:
 1. The second phase of the project, and the first phase is developed by jQuery.

 2. I have used Quasar UMD Kit in the second of the project.

 3. This proble happened in IE11, and i user iframe like this:
![image](https://user-images.githubusercontent.com/32186505/46727721-bdc7cb80-ccb3-11e8-8047-c6eb6333da24.png) 

 4. When i open Quasar UMD project alone, it's fine.When i open in IE11 and in a iframe, problem like this:

**Comment by pdanpdan** [comment]
I don't understand, what is the problem?

**Comment by huyang271** [comment]
@pdanpdan  sorry, the problem is when i click this,
![image](https://user-images.githubusercontent.com/32186505/46773476-38363100-cd30-11e8-9c9f-e552159e420f.png), and the page changed like this
![image](https://user-images.githubusercontent.com/32186505/46773519-6451b200-cd30-11e8-8958-34f15e38ccd0.png) , thank u!!!

**Comment by pdanpdan** [comment]
And the expected or desired aspect is? Please describe in words what is wrong.

**Comment by huyang271** [comment]
My English is not very good, I hope you can understand what I said.
From the beginning. I 'm developing the second phase of the project with Quasar UMD, and the first phase of the project was developed by JQuery. 
![roj nlpn kj1q_h 1 4](https://user-images.githubusercontent.com/32186505/46789380-dba63680-cd6e-11e8-9b11-62929eaabf1c.png)

**The problem is:** when I open my project, it should like this
![w _xa4qde c5ho q 2aevb](https://user-images.githubusercontent.com/32186505/46788886-c381e780-cd6d-11e8-92c2-ad346861401b.png)

But actually when i click，It is shown like this:

![image](https://user-images.githubusercontent.com/32186505/46789064-34c19a80-cd6e-11e8-85f7-e9b1ab0ad0a1.png)

I have no idea what happened. **This situation happened in IE11, and in chorme, it's fine. ** 

**I appreciate your help！If I do not speak clearly enough，you  can send a Email to me, 570827303@qq.com. and I can provide you online preview address and account for more details!**

**Thank you !**

**Comment by pdanpdan** [comment]
I think you just need to set the width on the iframe

**Comment by pdanpdan** [comment]
Try to start from here:
- https://stackoverflow.com/questions/23216934/flex-iframe-doesnt-stretch-in-ie11
- https://www.sitepoint.com/community/t/cant-get-iframe-to-fill-div-in-ie-works-fine-in-ff/9715

But it has nothing to do with Quasar.
