### ISSUE TITLE
Timeline item avatar

### ISSUE THREAD

**Issue by MatanYadaev** [quasarframework/quasar#2669]
Currently only icon is available on timeline item, I think avatar could be good feature.

**Comment by nothingismagick** [comment]
Please see v1. Now you can put anything in the icon
https://v1.quasar-framework.org/vue-components/timeline

Also there is the official q-activity app-extension
https://quasarframework.github.io/app-extension-qactivity/demo/dist/spa/#/

**Comment by rstoenescu** [comment]
Will be available in future v1.0.0-beta.24
