### ISSUE TITLE
[Request] Prevent click propagation outside pop-over elements

### ISSUE THREAD

**Issue by p3v9d5ui** [quasarframework/quasar#2670]
Clicking outside of a pop-up element, such as a QSelect, causes the pop-up to close, which is expected behaviour. But, the click event also propagates to the other elements of the DOM which can cause unexpected/undesirable behaviour. 

For example, I have a Popover which appears above a table of clickable elements. If I click outside the Popover it closes, the but click event is captured by the elements below, which then causes a route to another page. This is the behaviour that I'd like to block.

It would be helpful for QSelect/Modal/Context Menu/etc. items to provide an option to block click event propagation.

**Comment by joerg-walter-de** [comment]
I have maybe a similar problem right now. I have a table on a tab pane with clickable rows. A click opens a popup. After Closing it I now observe that clicking on another tab the popup opens

**Comment by bagithub** [comment]
You can achieve what you need with less effort by binding v-model for a popover with v-model for a modal

<q-popover v-model="opened">...</q-popover>
<q-modal v-model="opened">...</q-modal>

You can even prevent outside clicks from closing the q-popover adding some properties:
<q-popover v-model="opened" persistent>...</q-popover>
<q-modal v-model="opened" no-backdrop-dismiss>...</q-modal>

If you don't need the backdrop effect. Just set it's opacity to 0 (I don't recommend this)

Done.

**Comment by p3v9d5ui** [comment]
@bagithub , who are you answering? My original question or @bagithub ? In my case, I'm referring to all elements that have a pop-over effect, including form selects, modals, etc.

**Comment by bagithub** [comment]
I haven't done any test with q-select but I'm answering your request about the popover (you already said **For example, I have a popover ... This is behavior that I'd like to block**

According to your request, you're trying to make QSelect behave like a modal and it's better done with background overlay. Just request a new feature if you think it's necessary.

**Comment by metalsadman** [comment]
same problem on tooltip, i have a tooltip on the rows of a datatable inside a modal, when i click a row which chooses that item i then close the modal, but the tooltip lingers at the top right corner of my page. i have an ugly solution to remove the tooltip from the DOM after the modal closes >.<

**Comment by bagithub** [comment]
I suppose that no one will answer your questions and it's better to close this issue for these reasons:
1- The subject isn't an issue and you can achieve what you need using 'persistent' as described before.
2- metalsadman is claiming about something different that's not related to the subject that isn't considered an issue. he can still achieve what he need by using 'persistent' when the the popover is visible.

**Please close this issue.**

**Comment by tegola** [comment]
A common case scenario is the one I'm working on right now: a small screen showing a complex form with a few QSelects (at least 3).

After clicking on a Select to open its popup I have no way to click outside to close it without hitting another Select, which in turn will open, creating a vicious circle.

Popups really need a way to stop click propagation when open.

**Comment by nothingismagick** [comment]
This has been (to my knowledge) resolved in v1.

**Comment by tegola** [comment]
> This has been (to my knowledge) resolved in v1.

On a mobile screen, Selects appear as modal with an overlay, so yes, it is fixed.

However, on big screens selects open as dropdowns with no overlay, so this issue is still valid.

**Comment by pdanpdan** [comment]
This will be fixed in the next release (v1.1.0)

**Comment by rstoenescu** [comment]
This is not yet fixed for desktop.

**Comment by vinniimiranda** [comment]
I don't think this is the same issue, but i want to open the popup edit only when the user gives a dlbclick, how can i achieve this?

This framework is amazing btw.

**Comment by pdanpdan** [comment]
This should work pretty good now, both on mobile and desktop.
On mobile the click outside is not triggering an event on the target, and on desktop (more precision) it is allowed.

If there are still problems please reopen.

Thank you.

**Comment by brms2021** [comment]
This issue is still occurring for me.
I have a q-dialog with some q-select elements.
The q-dialog is using "`persistent`". 
If I click on the q-select, the menu opens.
If I click outside the q-select to close it, the q-dialog also closes, even though it has the `persistent` prop
