### ISSUE TITLE
[QDateTime] bad layout from am/pm format

### ISSUE THREAD

**Issue by mam-ijinus** [quasarframework/quasar#2671]
### Software version

Quasar:17.7
OS:Windows
Node: 8.11.3
NPM: 6.1.0
Browsers:Chrome

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/waugrryy/7262/
The web view must be as larger as possible

### What did you get as the error?
AM PM are cropped:

![image](https://user-images.githubusercontent.com/41424406/46867585-c0e2c900-ce25-11e8-8256-763ab0553cc4.png)

### What were you expecting?
no cropping :)

### What steps did you take, to get the error?
* use of QDateTime as time.
* click on it

**Comment by pdanpdan** [comment]
Hi. For the moment add this style:

```stylus
.modal-content, .q-popover
  > .q-datetime > .q-datetime-header
    min-width 175px
```

**Comment by mam-ijinus** [comment]
thanks for the reactivity :)
