### ISSUE TITLE
mdi-account-details icon does not work

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2675]
I can reference mdi icons fine, just the 'mdi-account-details' does not work/ show somehow... What's wrong?  On mdi side [it seems ok](https://github.com/Templarian/MaterialDesign/issues/3619).

**Comment by rstoenescu** [comment]
Hi,

They probably released a new version which includes it very recently and I didn't get to update quasar-extras to its new version yet. Please move this to quasar-extras repo so I won't forget. Thanks.

https://github.com/quasarframework/quasar-extras
