### ISSUE TITLE
How to use external libraries ? (like vidyo.io)

### ISSUE THREAD

**Issue by sivakavi** [quasarframework/quasar#2676]
How to use external libraries ? (like vidyo.io)

**Comment by sivakavi** [comment]
how to attach the external libraries with function call in quasar web app ?

<script src="https://static.vidyo.io/4.1.24.11/javascript/VidyoClient/VidyoClient.js?onload=onVidyoClientLoaded"></script>

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
