### ISSUE TITLE
Drawer in Mini mode centers icons before hiding

### ISSUE THREAD

**Issue by andreixk** [quasarframework/quasar#2678]
### Software version

Quasar: 0.17.17
OS: Mac OS X 10.13.6
Node: 10.11.0
NPM: 6.4.1
Browsers: Chrome 69.0.3497.100

### What did you get as the error?
When the drawer is set to mini mode, it shrinks in animation. However, right before it shrinks, the text disappears and the icons jump to the middle of the drawer, creating an unpleasant view.

### What were you expecting?
Text disappears, drawer slides to appropriate size.

### What steps did you take, to get the error?
No custom modifications, just default setup with quasar

**Comment by rstoenescu** [comment]
Fixed some time ago. v1 beta.4 should have the fix.
