### ISSUE TITLE
These relative modules were not found in node_modules

### ISSUE THREAD

**Issue by foufrix** [quasarframework/quasar#2679]
### Software version

Quasar: 0.17.16
OS: Linux
Node: 10.12.0
NPM: 6.4.1
Browsers: Chrome

### What did you get as the error? (directly at build time)

> These relative modules were not found:
> 
> * ./types/other in ./node_modules/mime/index.js
> * ./types/standard in ./node_modules/mime/index.js
> 

### What were you expecting?
I tried to install a dependencies and use it (leboncoin-api : https://github.com/thomacdo/leboncoin-api)

### What steps did you take, to get the error?
Initialize new quasar app and install dependencies with yarn. Try to use it and got the error.
(I tried with create-react-app with same step and it's working).

Look like the file in mime are not found, they look like this : 
```javascript
'use strict';

var Mime = require('./Mime');
module.exports = new Mime(require('./types/standard'), require('./types/other'));
```
Look like it can be a problem with babel config, i did not touch quasar.conf.js for the moment (only tried to remove exclude: /node_modules/, in extendWebpack, but not working got the same error).

Got no idea where to watch next, thanks in advance for the help !

**Comment by pdanpdan** [comment]
Usually this has nothing to do with quasar but with the package manager. Until last week I would have bet on yarn, but I had some major failures. Try to delete node_modules and install with yarn. If it still fails repeat but install with Mom install.

**Comment by pdanpdan** [comment]
@foufrix Did you manage to solve the problem?

**Comment by foufrix** [comment]
@pdanpdan  Hi sorry for the delay, did not had the time to try.

I tried both with yarn and npm with deleting node_modules each time, still the same error unfortunately :(

**Comment by rstoenescu** [comment]
Hi,

Would you be so kind to redirect this issue to the [appropriate repo](https://github.com/quasarframework/quasar-cli) pls? Thank you.
