### ISSUE TITLE
Change build path

### ISSUE THREAD

**Issue by hariprasath-p** [quasarframework/quasar#2680]
How to modify build path for fonts, css and js folders
i want to set the above-given folders build path to inside the static folder

### Software version

Quasar: 0.17.17
OS: Windows_NT(10.0.17134) - win32/ia32 (Windows 10 64-bit)
Node: 9.0.0
NPM: 5.5.1

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by hariprasath-p** [comment]
OK Sure thank You
