### ISSUE TITLE
[FEATURE REQUEST] Table/Data Grid "EpandRow"

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#2683]
Hello Team;

Many of the existing Data Grids in the market provide "Row Expansion" grid where the developer can attach a "Detail form" for that row or show another child grid under that row.  Further more, the child grid can also be expanded just like the parent. Here is a sample.

https://demos.telerik.com/kendo-ui/grid/angular

This will help a lot for apps with hierarchical data to keep the user in one form and allow them quickly to see details without moving to another form and then returning back again.

Hope this helps!

**Comment by rstoenescu** [comment]
Hi,

It's already available.
Demo (last example from): https://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/table/table-customize
Source: https://github.com/quasarframework/quasar-play/blob/master/src/pages/showcase/grouping/table/table-customize.vue#L143-L189

**Comment by BenHayat** [comment]
Thanks Razvan;

I must have missed the "Table Customization" section being at the end of the list.
Thank you for your reply, which now allows me to plan to use this feature.
