### ISSUE TITLE
Ignore dev env in quasar.conf.js when running quasar build

### ISSUE THREAD

**Issue by forgotpw1** [quasarframework/quasar#2694]
The dev and build commands are both outstanding. Including SSL support on dev is outstanding.

We've been building on various environments (remote linux dev server, VM images, and macos) and like to keep the quasar.conf.js file under version control. 

There is a little point on inconvenience when we want to run 'quasar build' on remote servers or mac os, where were aren't running 'quasar dev', and need to install 'fake' ssl certs to satisfy the conditions for 'quasar dev' 

I suggest not validating dev env settings when running build since build env settings don't pick up any 'env'. 

I've been using 0.16.4 and plan to upgrade to 1.0. Maybe this has been addressed in newer versions.

**Comment by rstoenescu** [comment]
Hi,

Would you be so kind to test the latest v1 beta and see if this is still an issue? It shouldn't.
Thanks in advance.
