### ISSUE TITLE
the icon with the name "globe" can not show

### ISSUE THREAD

**Issue by giovannaVillanuevaRodriguez** [quasarframework/quasar#2695]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Hello,

That's because there isn't any? https://material.io/tools/icons/?style=baseline
Am I missing something?

**Comment by giovannaVillanuevaRodriguez** [comment]
Hello.
In my case, I use this one https://ionicons.com/
It's important in quasar-cli to use prefix for this type of icons when using (https://quasar-framework.org/components/icons.html#Cheatsheet)
Thanks Razvan

**Comment by giovannaVillanuevaRodriguez** [comment]
> Hello,
> 
> That's because there isn't any? https://material.io/tools/icons/?style=baseline
> Am I missing something?

Hello.
In my case, I use this one https://ionicons.com/
It's important in quasar-cli to use prefix for this type of icons when using (https://quasar-framework.org/components/icons.html#Cheatsheet)
Thanks Razvan

**Comment by rstoenescu** [comment]
Ok. You didn't specified the icon library so I assumed it is Material icons. For more info on how to use icons you can take a look at this cheatsheet: https://quasar-framework.org/components/icons.html#Cheatsheet
