### ISSUE TITLE
Question: How to disable flexbox classes

### ISSUE THREAD

**Issue by SephVelut** [quasarframework/quasar#2699]
Quasar places row and col classes on components I need to style very specifically. How do I disable the flexbox grid styling but leave all other styles?

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
