### ISSUE TITLE
Allow infinite scroll to work in "reverse" mode

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#2705]
Infinite scroll currently works loading elements when reaching the bottom side of the screen, but for many purposes like a chat or any communication app, the old messages should be retrieved when reaching the top (position 0) of the scroll

**Comment by pdanpdan** [comment]
duplicate of https://github.com/quasarframework/quasar/issues/2612

**Comment by louisameline** [comment]
@jigarzon please close this issue as it's a duplicate
