### ISSUE TITLE
[QInput] suffix is misplaced when the width is forced

### ISSUE THREAD

**Issue by mam-ijinus** [quasarframework/quasar#2706]
### Software version

Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.11.3

Global packages
  NPM                           6.1.0
  yarn                          1.7.0
  quasar-cli                    0.17.20
  vue-cli                       3.0.5
  cordova                       8.0.0

ON FIREFOX

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/waugrryy/7375/

### What did you get as the error?
With Firefox
![image](https://user-images.githubusercontent.com/41424406/47513025-b5f45380-d87d-11e8-8b5d-b50b6ab46242.png)

### What were you expecting?
The suffix to be just after the input (like with chrome):
![image](https://user-images.githubusercontent.com/41424406/47513144-ea680f80-d87d-11e8-99ad-c2bd3ac59bab.png)

### What steps did you take, to get the error?
use a q-input:
``<q-input style="width:30px" suffix="h"></q-input>``
open page into firefox (no issue with chrome) 

And thanks for this great framework !

**Comment by mam-ijinus** [comment]
same with edge:
![image](https://user-images.githubusercontent.com/41424406/47555558-66109d80-d90c-11e8-832a-72355a22b693.png)

#### for information:

Firfox version: 62.0.3
Edge version: 42.17134.1.0 and Microsoft EdgeHTML 17.17134
Chrome:  69.0.3497.100

**Comment by mam-ijinus** [comment]
Apparently the `width: auto` from `col` of input is not manage the same way in firefox and in Chrome... 

A work around is to set directly the input width:

`input.q-input-target
    width: 75px`

But with this solution q-input with and without unit don't have the same width...

PS: with the version 45 of firefox I have no issue...

**Comment by rwuttke** [comment]
This problem is also seen on the [Quasar Layout Demo](https://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/play-with-layout) with the two Bkpt fields, the first field runs into the second field.

This is with Firefox Quantum 64.0 (64-bit) on Windows 10.

And just to add, my Edge version, which is the same version as @mam-ijinus has the following:

- The codepen above works as described with the same flaw.
- The Quasar Layout Demo works correctly.

**Comment by smolinari** [comment]
Not sure this helps, but I did a fiddle for someone else's problem about putting a QInput inline with text. Have a look. 

http://jsfiddle.net/smolinari/8go1wnku/

Scott

**Comment by drasill** [comment]
I encounter the same problem.

Here is my quick fix (stylus):
```styl
.q-input
	input.q-input-target
		width 100%
```

**Comment by samcassar** [comment]
This is still an issue with the v1.0 docs

![chrome-issue](https://user-images.githubusercontent.com/25423886/52530803-d24bcb80-2d5a-11e9-8e43-d9717f2e4893.png)
![firefox-issue](https://user-images.githubusercontent.com/25423886/52530804-d5df5280-2d5a-11e9-9b95-c89f3fc3f9ff.png)
