### ISSUE TITLE
QSelect will not trigger dropdown unless already focused in Firefox

### ISSUE THREAD

**Issue by ebaliatico** [quasarframework/quasar#2707]
### Software version

Quasar: v0.17.17
OS: Windows 10 Pro
Browsers: 
- Chrome Version 70.0.3538.67 (Official Build) (64-bit)
- Firefox Quantum 63.0 (64-bit)

### JsFiddle
https://jsfiddle.net/f6g5d981/

### What did you get as the error?
- Select focused OR select has value
    - Behavior is consistent, click anywhere in either browser triggers dropdown
- Select not focused, select value is null or blank
    - Click on label (cursor shows as text on hover)
        - Behavior is consistent, dropdown triggered
    - Click on field outside of label (cursor shows as pointer on hover)
        - Chrome: dropdown triggered
        - Firefox: select gains focus, but dropdown is not triggered

### What were you expecting?
Behavior should be consistent across browsers. Personal preference is a click triggers the dropdown regardless of click location.

### What steps did you take, to get the error?
Vary focus state and click location in both browsers as described above.

**Comment by rstoenescu** [comment]
This shouldn't be a problem in Quasar v1.
