### ISSUE TITLE
non-default QTabPane(s) are not in the Dom on mount (using keep-alive)

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2708]
I am putting Stripe elements (i.e. iframes) in QTabPane elements with the property 'keep-alive'. The Stripe element shows properly in the default QTabPane (i.e. the one that is opened initially). In the other QTabPane elements I get an error from Stripe saying it does not find the element (in which it needs to put its iframe) in the dom, so apparently these only exist after being clicked/opened. 
Is this desired behavior? Also with the keep-alive property? 
If yes, what is a decent 'work-around' for my issue, use the router and when routed to a QTabPane mount the Stripe element from that child component or something?

**Comment by rstoenescu** [comment]
Added a new prop (Boolean) for QCarousel/QTabPanels/QStepper: `keep-alive`.
Will be available in beta.22.
