### ISSUE TITLE
How to prevent screen to pull down on ios (iPhone). when you scroll the finger on touch screen

### ISSUE THREAD

**Issue by mMarcos208** [quasarframework/quasar#2713]
### Software version

Quasar: 0.17.11
Node: v8.11.3
NPM: 6.4.1
iOS: 11.4.1

### Bug 

I have noticed that as I run my finger pulling the APP down a white screen appears, this has left my entire layout confusing.

**Comment by rstoenescu** [comment]
Hi,

This is called the "rubber band effect" on iOS. You can disable it by configuring your `src-cordova/config.xml` file. Please google for "disable rubber band cordova" and see what you need to add to the Cordova config file.

**Comment by mMarcos208** [comment]
Thank you!

This is what you need :)
