### ISSUE TITLE
QSelect: autofocus-filter has no effect

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#2715]
### Software version

OS: Windows 10 win32/x64
NodeJs: 8.9.4
yarn : v1.7.0
quasar-cli : v0.17.20

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/81s7m50d/

### What did you get as the error?
QSelect Property 'autofocus-filter' has no effect

**Comment by yuanyesong** [comment]
On mobile, keboard would comes up when filter in select, i think it's not a good user experience.

**Comment by yuanyesong** [comment]
Update the documents, if removed. Thx！

**Comment by rstoenescu** [comment]
This will get much better in v1.0.
