### ISSUE TITLE
dense q-table with selection adds a scrollbar to the table rows

### ISSUE THREAD

**Issue by burningTyger** [quasarframework/quasar#2716]
### Software version

Operating System                Linux(4.18.14-arch1-1-ARCH) - linux/x64
NodeJs                          10.9.0

Global packages
  NPM                           6.4.1
  yarn                          1.10.1
  quasar-cli                    0.17.20
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages
  quasar-cli                    0.17.20 (Quasar Framework CLI)
  quasar-framework              0.17.17 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.8   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      3.0.6   (Build cross platform desktop apps with JavaScript, HTML, and CSS)
  electron-packager             12.2.0  (Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI)
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/1oxa3ycw/

### What did you get as the error?
There's a scrollbar on the right which does nothing
![image](https://user-images.githubusercontent.com/263378/47704253-5e5e3b00-dc23-11e8-809a-a799c75de3e9.png)

### What were you expecting?
no scrollbar

### What steps did you take, to get the error?
added dense to a table and selection properties

**Comment by metalsadman** [comment]
@burningTyger 
same issue as this https://forum.quasar-framework.org/topic/2899/q-table-selection-shows-y-scrollbar/2, see link for the workaround.

**Comment by burningTyger** [comment]
@metalsadman nice, this works. I tried something similar but that didn't work.

**Comment by rstoenescu** [comment]
This has been recently fixed in v1 beta.
