### ISSUE TITLE
QLayoutHeader offsets to middle of screen if user scrolls up while iOS keyboard is visible

### ISSUE THREAD

**Issue by mattabdi** [quasarframework/quasar#2718]
The QLayoutHeader is still sitcky but its position gets shifted by the iOS keyboard becoming visible onscreen. I have a QLayoutFooter as well and my QLayout view is <q-layout view="hHh Lpr lFf">
Steps:
1) Pic of screen before keyboard visible: https://drive.google.com/file/d/1Ca_ifH_sidIidWjjVOlgNishsTmayVE_/view?usp=sharing

2) Pic of screen with keyboard visible: https://drive.google.com/open?id=1ENGPdr9RJ3ZYBp6Y2IgE-HAg9Fx0deBi

3) Pic of scrolling up while keyboard is visible (visible error): https://drive.google.com/open?id=1SO71tjIHOGqtRBcqJqUpo_OFQwErl9sq

4) Pic of the iOS screen after keyboard closed and everything reverts back to normal: https://drive.google.com/open?id=1J8tIDYAL8d7BruXmxPVQPcooopDqIWaw

Quasar: 0.17.20
iOS: 12.0.1

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce with earlier iOS versions. Will check iOS 12 is a few days. Must be a new iOS bug.

**Comment by rstoenescu** [comment]
There is a bug in iOS that when keyboard shows up on screen, "position: fixed" will heavily misbehave. It's a known issue in iOS (has been reported a thousand times to them) and Apple seems to refuse to fix this.

As a workaround, please use https://github.com/apache/cordova-plugin-wkwebview-engine
