### ISSUE TITLE
QTooltip lingers in the page after parent modal gets closed.

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#2723]
### Software version

Quasar: v 0.17.17 cli 0.17.20
OS: Windows 7

Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
(codesandbox)
https://codesandbox.io/s/pk884o79p0

Screenshot.
https://postimg.cc/mcz9mmh1

### What did you get as the error?
Tooltip lingers in the page when parent modal has closed.

### What were you expecting?
Tooltip should not linger in the page when datatable row is clicked.

### What steps did you take, to get the error?
I have datatable with tooltip on each row inside a modal, selecting a row will choose the selection and close the modal.

**Comment by metalsadman** [comment]
yep, i also did that in my project beside the dom manipulation that I went for, but i don't think it should be the proper way, since this bug doesn't only happen in this case, it's a tooltip issue when its parent get removes while tooltip is currently showing or about to be shown (animating thru the delay you set) that it doesn't destroy itself but lingers in the dom. looking at qtooltip.js maybe probably somewhere in the beforeDestroy hook, since it either lingers where it is currently showing (or probably anchored), or shows at top left of the page when parent closes and the tooltip is animating to be shown but the parent has already been removed as you can see in one of my screenshot. but for now yep, both solution should work until maybe they changed it internally or someone who understands the component more and gives a pr.

**Comment by smolinari** [comment]
I'm no expert, but this looks like a case for needing [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), so QTooltip knows it's parent was removed. 

Scott

**Comment by rstoenescu** [comment]
Fixed in v1.0. QTooltip works on another principle entirely now.
