### ISSUE TITLE
Inconsistent cursor when QPopover is inside QInput

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2727]
Hello!

When you put QPopover inside an input element it adds pointer cursor around.
See example:
https://jsfiddle.net/waugrryy/7400/ -> mouseover somewhere near the top/bottom border of the second input in my example to see that the cursor changes

Thanks!

**Comment by jean-moldovan** [comment]
@metalsadman , thanks but this does not seem to be working, see:
https://jsfiddle.net/waugrryy/7411/ I still see pointer cursor here

**Comment by metalsadman** [comment]
sorry jsfiddle doesn't seem to work on my browser. https://codesandbox.io/s/pkv9q2yqlj

**Comment by rstoenescu** [comment]
This has been taken care of in v1 beta.
