### ISSUE TITLE
QPopover inside input with an icon

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2729]
Hello!

When you use a q-popover inside input with an icon, clicking on an icon doesn't trigger popover as it does by simply clicking inside the input. I think this should be consistent.

Example: https://jsfiddle.net/waugrryy/7405/
1) Click inside the input -> popover is shown 👍 
2) Click on an input icon -> popover is not shown 👎 

Thanks!

**Comment by metalsadman** [comment]
to give action to your before or after icon, you need to give it a handler prop which is a function. https://codesandbox.io/s/xvxw36lkmz

**Comment by jean-moldovan** [comment]
I see your point, @metalsadman , although I still think that popover should be shown by default when clicking on an icon. The reason being is that, if you click on an icon, input gets focused as if you clicked inside, currently:
1) click inside input -> input is focused + popover shown
2) click on an input icon -> input is focused + popover is NOT shown

Thanks!

**Comment by smolinari** [comment]
@jcperez-ch - the idea behind the left and right icons is to give your input a secondary feature. If clicking on the icon were to open the popup and there is also some activity with the secondary feature, it would be bad UX. So, it is up to you. If your intention is to have the icon clickable for the same exact feature you've built for the input focus, then you need to give it that functionality as a secondary feature.  

Scott

**Comment by jean-moldovan** [comment]
okay, @smolinari , thanks for your reply.
