### ISSUE TITLE
QToggle : [Violation] Added non-passive event listener to a scroll-blocking ...

### ISSUE THREAD

**Issue by ggregg** [quasarframework/quasar#2730]
### Software version

Quasar: 0.17.20
Browsers: Chrome 70.0.3538.77

**Chrome** notify this warning in console verbose mode [warning](https://www.chromestatus.com/feature/5745543795965952) when i use QToggle.

To reproduce it's easy, go on [quasar components page](https://quasar-framework.org/components/toggle.html) and just have a look in the javascript console.

Thank's :)

**Comment by pdanpdan** [comment]
I cannot reproduce it on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle, Chrome 72.

**Comment by ggregg** [comment]
Hello, i understand,
1 - open page
2 - open chrome développement tools
3 - refresh the page

![quasar_play](https://user-images.githubusercontent.com/2576033/48047160-72f88100-e197-11e8-9fb9-f732b0c9196b.png)

**Comment by ggregg** [comment]
> I cannot reproduce it on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle, Chrome 72.



> I cannot reproduce it on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle, Chrome 72.

**Comment by MadeMyDay** [comment]
@ggregg Why have you closed it? Having the exact same issue.

**Comment by MadeMyDay** [comment]
But opening the 
https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle results in lots of errors in latest Chrome (Mac), too. So how can this be an error on your part? ;-)

**Comment by msinkgraven** [comment]
See: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners.
It seems as though the origin of the error comes from a scroll-blocking touch event on `q-toggle`. I'd be happy to open a PR with a fix.

**Comment by pdanpdan** [comment]
Please make the PR

**Comment by rstoenescu** [comment]
This has been thoroughly taken care of in v1 beta.
It's due to browsers suddenly making a breaking change in the web standards which flip the way passive listeners are registered.
