### ISSUE TITLE
QTab scrolling not init

### ISSUE THREAD

**Issue by VIMHaos** [quasarframework/quasar#2731]
Hi,
On Android old version (less 6)
1. Qtab scrolling not initialize, where tabs more, and shown all items on each other.
2. Sometimes vizually selectable more one tabs, may activave 2 or 3 tabs by 4 items, but in data state all been ok.

And has some problem with styles by QModal, when props position=bottom (modal content is not show) but it other issue ..

Best regards, Vasyl Mazur

------------------
Quasar-cli: 0.17.19
Quasar theme: mat
Vue-cli: 2.9.6
Cordova: 8.1.2
OS: Android 5.0
  
Node: 8.11.3
NPM: 5.6.0
------------------

**Comment by rstoenescu** [comment]
Hi,

It's hard to understand what you mean so it's hard to help identify your issue. Can you post a jsfiddle (as requested in the Github bug template) to actually see what your are trying to do pls? Thank you.

**Comment by rstoenescu** [comment]
This shouldn't be a problem now.
