### ISSUE TITLE
Logo.png not found (404)

### ISSUE THREAD

**Issue by mMarcos208** [quasarframework/quasar#2732]
### Software version

Quasar: 0.17.11
OS: Windows 10
Node: v8.11.3
NPM: 6.4.1
Browsers: Google Crome
iOS: 12
Any other software related to your bug:

### Logo.png not found

When I launch my application through IOS a white screen appears until the home page appears. 

_Would that be a bug?_

`$cordova run browser`

 I see that the quasar try to display a **logo.png** that does not exist.

**[Print IOS Iphone](https://imgur.com/B0jy3EH)**

**[Print Browser](https://imgur.com/umLT4So)**

**Comment by rstoenescu** [comment]
Hi,

Kindly asking you to fill out more details. Your description does not help in identifying what you are doing (and how) and if something doesn't works as expected or it's a misinterpretation. Also, I cannot see the second screenshot. Please look for help on our [Discord server]()http://chat.quasar-framework.org) first then post a detailed bug if it's indeed the case. This would help identify your potential problem. Thank you.

**Comment by mMarcos208** [comment]
@rstoenescu This background image is not showing up. As indicated in the second image.

**Comment by mMarcos208** [comment]
@rstoenescu inspect browser: https://imgur.com/lCSTh5g

**Comment by rstoenescu** [comment]
Running "cordova run browser" won't work as you'd like to. Use `$ quasar dev -m -T android/ios/etc` and it will pop up the emulator. That's not Quasar trying to display an image.. that's Cordova trying to display that image. In any case, your details are still too vague. Please use our Discord server so you can understand more of Quasar and Cordova. Thank you.
