### ISSUE TITLE
[Request] Modal: position bottom+ maximized option can work together

### ISSUE THREAD

**Issue by alterhu2020** [quasarframework/quasar#2734]
### Software version

Quasar:  quasar-framework@0.17.17
OS: Win 10 
Node:  v8.9.3
NPM: v5.5.1
Browsers: Chrome mobile emulator for iphone x
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
The `modal` popup shows from the right and cannot show from the bottom, if I give the position as `bottom` ,then the popup modal cannot maximize 
### What were you expecting?
1. The `modal` popup and maximized from the bottom, not from the default right.
### What steps did you take, to get the error?
2. the `modal` always comes from the right, see the references had raised before:
2.1 https://github.com/quasarframework/quasar/issues/2112
2.2 https://github.com/quasarframework/quasar/issues/2106

![https://user-images.githubusercontent.com/5029046/48068288-61ea5700-e20d-11e8-83ba-b7e09cc4e3d5.png](https://user-images.githubusercontent.com/5029046/48068288-61ea5700-e20d-11e8-83ba-b7e09cc4e3d5.png)

**Comment by alterhu2020** [comment]
@rstoenescu  any update for this ?

**Comment by rstoenescu** [comment]
Seems to me that the only important part for this is the animation? **You want it to be animated from the bottom and not from one side. If this is correct, then simply write your animation and use the `animation` prop which is specifically added for this purpose.**

`maximized` and `position` are different behaviours and you can't have them both. One means "cover all screen" and the other means "stick and cover one of the four sides".

Like I keep saying, on v1.0 there will be a lot of predefined animations and everything is simplified regarding Dialog/Modal. Until v1 is released you can write your own Vue animation and use it --  it's quite easy.

On the other hand, if you want the modal to be positioned on the bottom, but you are interested in it having "full width / 100% width" of the screen, then write a CSS class and apply it to your QModal.

Feel free to reopen this if I missed something, although I honestly doubt it. Thanks.

**Comment by alterhu2020** [comment]
thanks @rstoenescu , I had fixed it as you suggestion here.
