### ISSUE TITLE
QKnob's drag-value event does not trigger a click in mobile mode.

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2735]
In docs it says:
@drag-value(val) | (v0.15.11+) Triggered while dragging (or clicking) on Knob.

I'm on Quasar v0.17 and when using QKnob when I do:
```@drag-value="() => {myClickMethod(cardIndex)}"```

In Desktop mode it reacts fine on both clicks and drags. However it only reacts on drag when in Chrome mobile mode. This is most obvious when clicking with the mouse (as in touchmode your finger easily  makes it a drag when a click is intended), but also with a steady click with my finger it does not trigger a click.

**Comment by rstoenescu** [comment]
This has been taken care of in v1.
