### ISSUE TITLE
Router Transition - Choppy performance on first route change

### ISSUE THREAD

**Issue by stuartcusackie** [quasarframework/quasar#2739]
### Software version
Quasar: 0.17.17
OS: Android

### Problem

I am experiencing choppy animations on the first transition of router-view. The animations are fine after the first transition.

I have a home screen with a login button:
- Clicking the login button on open the app results in a delayed and staggered animation.
- Once the first page is loaded, going backwards or opening a new page results in a smooth animation.

Layout snippet: 

```
<transition 
v-on:appear="fadeIn"
v-on:enter="slideIn"
v-on:leave="slideOut"
v-bind:css="false">

<router-view />

</transition>
```

Index page snippet:
```
<div class="buttons">
  <p>
    <q-btn rounded color="primary" size="13px" class="full-width" label="Log in" to="/login" />
  </p>
  <p>
    <q-btn rounded color="secondary" size="13px" class="full-width" label="Sign up for free" to="/register" />
  </p>
</div>
```

I would post my transition functions but I don't think the problem lies in them. I was having the same problem when using CSS based Vue transitions, and now I'm getting the same problem with two different JS animation packages (Velocity and GreenSock). Hence why I don't think it's transition performance related.

My best guess is that there's something within Vue Router than doesn't get loaded until the first click. 

Possibly useful information:
- I am not using Lazy Loading in my routes file.
- My Layout and QPage components contain a little CSS in the style block.
- My login page imports Vuelidate validators
- I'm testing my app by installing the APK on my phone manually.

Any ideas?

**Comment by stuartcusackie** [comment]
my description dissappeared :(

I'll rewrite when I get time.

**Comment by rstoenescu** [comment]
Hi,

Please re-route this to the Vue Router repo. This has nothing to do with Quasar. Thank you.

**Comment by rstoenescu** [comment]
Also pls note you can use quasar-extras animations, which already have "fadeIn" and "fadeOut".

```js
// quasar.conf
module.exports = function (ctx) {
  return {
    // ...
    animations: ["fadeIn", "fadeOut"],
    // ...
  }
}
```

```html
<transition enter-active-class="animated fadeIn" leave-active-class="animated fadeOut" mode="out-in" :duration="300">
      <router-view/>
    </transition>
```

**Comment by stuartcusackie** [comment]
Thanks. I might just leave this one here until I investigate Vue Router a bit further.
