### ISSUE TITLE
q-select highlighting only checked array's options with lowest index

### ISSUE THREAD

**Issue by otavio515** [quasarframework/quasar#2740]
### Software version

Quasar: 0.17.20 CLI / 0.17.17 Framework
OS: Linux(4.15.0-36-generic) - linux/x64
Node: 9.9.0
NPM: 6.1.0
Browsers: SPA
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/r26mzu1j/

### What did you get as the error?
Having more options than what can be shown on screen,
![example1](https://user-images.githubusercontent.com/11263232/48150503-0324ec00-e2a6-11e8-9cbe-85ee51f0d02f.png)
[ Last option is shown when I scroll down ]

When I checked any option below 11:00 (highlighted), none of it get highlighted, as if they were last clicked

![example2](https://user-images.githubusercontent.com/11263232/48151374-45e7c380-e2a8-11e8-8fe2-e1a8dca5ea25.png)

but if it's above, it get highlighted and the last highlighted option get back to be unhighlighted (seems that it's considering checked options with lowest index to highlight

![example3](https://user-images.githubusercontent.com/11263232/48151483-8a735f00-e2a8-11e8-844d-7c55df52b12c.png)

![example4](https://user-images.githubusercontent.com/11263232/48151529-a37c1000-e2a8-11e8-9dd5-1e7f7ee28de5.png)

and also if I check the first option (08:00)

![example5](https://user-images.githubusercontent.com/11263232/48151684-0e2d4b80-e2a9-11e8-9416-da4f3480c4c2.png)

when I check any option which is not shown on screen (17:00) I get straight redirected to the highlighted option, it means that I would have to scroll down again before select any option that isn't showing.

When I click 17:00 option

![example7](https://user-images.githubusercontent.com/11263232/48152137-36697a00-e2aa-11e8-8dde-d01ff95275ae.gif)

### What were you expecting?

Is it supposed to highlight last clicked option?

**Comment by pdanpdan** [comment]
This happens because you always send a new set of options. Also you fiddle is not working.
Check this one: https://jsfiddle.net/njpmubso/
