### ISSUE TITLE
How to enable workbox strategy `networkFirst` for index.html of all routes?

### ISSUE THREAD

**Issue by luatnd** [quasarframework/quasar#2743]
**Problem**
Hi, I built a project in `PWA` mode and I notice that when I deploy a new version. All resource files are still cached and loaded from service worker.
It seems to be cached forever?
So every deployment, my client needs to clear site data to clear service worker cache.

**My temporary solution is:**
Disable index.html entry in `dist/pwa-mat/precache-manifest.*.js` then add workbox option:
```
  pwa: {
      workboxOptions: {
        runtimeCaching: [
          {
            // match all url that is not files *.*
            urlPattern: /(\/|\/#|\/#\/|\/[^./]+)$/g,
            handler: 'networkFirst'
          }
        ]
      },
  }
```
I'm using `hashed` routes, so that all routes was pointed to index.html with networkFirst right now.

**But I have a question:**
If I want all client can see the newest version right after deployment, how should I do with Quasar?

Thanks.

**Comment by jean-moldovan** [comment]
Hello, in my understanding your SPA consists of a single index.html which is an entry point for all routes (`/` or `/products` or whatever). Check your dist folder after build command.

So basically if you disable caching for index.html (or use network first) your clients should see latest version after each deployment.

Hope this helps!

**Comment by luatnd** [comment]
Hi @jean-moldovan , I've already done it in **My temporary solution**, but I need to manually modify the `dist/pwa-mat/precache-manifest.*.js` to remove index.html precaching. Can Quasar support an easy way to configure `precache-manifest.*.js`? Or another workaround?

**Comment by luatnd** [comment]
Thank @jean,
the `exclude` option works fine. I read the workbox doc also.
But I faced another issue: https://github.com/quasarframework/quasar/issues/2777

**Comment by luatnd** [comment]
> @luatnd you mean @jean-moldovan but I think he already got a notification 😁

Sorry about that 😁
