### ISSUE TITLE
Run build on Netlify

### ISSUE THREAD

**Issue by scalarerp** [quasarframework/quasar#2744]
How can run 'quasar build' on Netlify, or how migrate a project from quasar-cli to vue-cli to use npm run.. or yarn run...

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by panstromek** [comment]
To answer anyway. You can really just add it as a build script. Yarn version was important for me.. It has older version by default. (or at least it had when I was setting it up)

![image](https://user-images.githubusercontent.com/25121817/48191808-65352e00-e346-11e8-80cc-c61289d9d018.png)
