### ISSUE TITLE
Pass additional arguments to @save event handler of the QPopupEdit

### ISSUE THREAD

**Issue by sontis3** [quasarframework/quasar#2747]
Hi!
I have QPopupEdit that is used to edit a value “in place” a cell in a QTable.

        <q-table  :columns="columns" :visible-columns="visibleColumns" row-key="name" :data="ds">
        .......
          <q-tr slot="body" slot-scope="props" :props="props">
            <q-td v-for="col in props.cols" :key="col.name" :props="props">
        .......
              <template v-else-if="col.classes === 'popup-edit'">
                {{ col.value }}
                <q-popup-edit v-model="props.row[col.field]" @save="UpdateDocument">
                </q-popup-edit>
              </template>
            </q-td>
          </q-tr>
        .......
        </q-table>
After submit QPopupEdit i would like to send request for update the document. For this action i need documentId and some fields, wich stored in row of QTable, but handler UpdateDocument receive only "val" and "initialValue".
If I will write <q-popup-edit v-model="props.row[col.field]" @save="UpdateDocument(props.row)"> then i can send update request, but in case of update error can not restore old value of table cell.
How pass additional arguments into @save handler? For example 
@save="UpdateDocument(val, initialValue, props.row)
Like problem discussed in [https://forum.quasar-framework.org/topic/2725/qpopupedit-how-to-pass-own-argument](url)

**Comment by metalsadman** [comment]
yep would be nice to do that, solution for now is add a unique ref on your q-popup-edit and pass it as argument in one of its events in your case on-save like so `@save="UpdateDocument($event, $ref[myUniqueRef].initialValue, props.row)`. the $event is the new value (I don't know why it is so, maybe emitted the value from the child input in the q-popup-edit, it would've been nice if the $event would reference the q-popup-edit so no need to pass a $ref IMO).

**Comment by pdanpdan** [comment]
You can use `<q-popup-edit :value="props.row[col.field]" @input="val => UpdateDocument(col.field, val)">`

**Comment by sontis3** [comment]
**@pdanpdan**, thanks.
In my case solution is
`<q-popup-edit :value="props.row[col.field]" @save="(val, initialValue) => UpdateDocument(val, initialValue, props.row)">`
Arrow function helped to solve the problem of additional arguments.

**Comment by metalsadman** [comment]
good to know there are other ways, i don't like ref way much, specially if it's from something out of a loop.

**Comment by YGoldking** [comment]
感谢  已解决   神奇的quasar

**Comment by hawkeye64** [comment]
Translation: "Thanks resolved magical quasar"
