### ISSUE TITLE
[Enhancement] QUploader - handle image rotation

### ISSUE THREAD

**Issue by fansanelli** [quasarframework/quasar#2750]
Hello,

on Android and iOS, when I take a picture from camera, it gets uploaded rotated...
Should this be handled inside uploader code?
I found a project that handles the exif rotation as feature:
https://github.com/blueimp/JavaScript-Load-Image
What do you think?
Cheers
Francesco

**Comment by metalsadman** [comment]
you can add it as a plugin https://quasar-framework.org/guide/app-plugins.html

**Comment by fansanelli** [comment]
Hello,
can someone check this approach?

https://github.com/fansanelli/quasar/commit/5920db938933ef18d61790c02f0fc8dd4a63a3f8

Currently this fixes the preview only, btw.
Francesco

**Comment by nothingismagick** [comment]
yeah - my feeling here is that if the user uploads a jpg you WILL be losing image quality by rotating it that way (via canvas). Voting to close
