### ISSUE TITLE
QTabs Swipeable breaks vertical scrolling on iOS-Safari

### ISSUE THREAD

**Issue by fansanelli** [quasarframework/quasar#2752]
### Software version
$ quasar info

Operating System         	Linux(4.15.0-38-generic) - linux/x64
NodeJs                   	8.11.3

Global packages          	
  NPM                    	6.4.1
  yarn                   	Not installed
  quasar-cli             	0.17.22
  vue-cli                	2.9.6
  cordova                	8.1.2 (cordova-lib@8.1.1)

Important local packages 	
  quasar-cli             	0.17.22	(Quasar Framework CLI)
  quasar-framework       	0.17.18	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras          	2.0.9	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.25.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.10	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.6.3	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.5.2	(Script for registering service worker, with hooks)

### What did you get as the error?
I used swipeable:
```
    <q-tabs animated swipeable inverted align="justify">
                     ^^^^^^^^^
```

### What were you expecting?
That the tab-pane can vertically scroll.

### What steps did you take, to get the error?
Open in browser from an iPhone5 (Safari 10 on iOS 10.3).

**Comment by fansanelli** [comment]
I did some more testing and confirm the same issue is still present on:
iPhone6 with Safari 10 on iOS 10.3
iPhone6S with Safari 12 on iOS 12.1
I've noticed that I'm able to scroll vertically only holding for some second before to swipe...

**Comment by miketrebilcock** [comment]
We're experiencing similar behaviour with Chrome on Android.  Vertical scrolling still works but is really slow and unresponsive.

**Comment by fansanelli** [comment]
@miketrebilcock After updating to latest version (v0.17.19) tabs are broken on iOS.
I'll try to dig this issue...

**Comment by fansanelli** [comment]
@miketrebilcock UPDATE: I found the piece of code that broke the tabs for me:
```
            <q-item>
              <q-item-main>
                <q-input
                  stack-label="Vision"
                  v-model="form.vision"
                  type="textarea"
                  ^^^^^^^^^^^^^^^
                />
              </q-item-main>
            </q-item>
            <q-item-separator />
```
switching to "text" fixed a problem that disallow switching from a tab to another on iOS-Safari.

**Comment by rstoenescu** [comment]
"swipeable" cannot be accommodated to also work with touch-capable devices. You either enable it for non-touch capable (`:swipeable="!$q.platform.has.touch"`) devices or you don't use it at all. Sorry...
