### ISSUE TITLE
Old Android Support Issues. q-layout-drawer

### ISSUE THREAD

**Issue by yahao87** [quasarframework/quasar#2753]
After Quasar v0.17.13 & CLI v0.17.16
cordova, android

After installing the initial app, the menu does not appear even if the menu tab is clicked in Android 4.4.2 version.(Samsung Galaxy note 2)
<br />
`MyLayout.vue`
```
<q-layout-drawer
      v-model="leftDrawerOpen"
      :content-class="$q.theme === 'mat' ? 'bg-grey-2' : null"
    >
      <q-list
        no-border
        link
        inset-delimiter
      >
```

This issue occurs from Quasar v0.17.13 & CLI v0.17.16.
"Quasar v0.17.12 & CLI v0.17.15" works normally.

**Comment by rstoenescu** [comment]
Hi,

For Android <5.0 (but strictly for pre v5) builds, please use the Cordova Crosswalk plugin. In your `/src-cordova` folder (which is a Cordova project folder:

```cordova plugin add cordova-plugin-crosswalk-webview```

**Comment by yahao87** [comment]
Using crosswalk increases the file size by 20mb.
This function worked well.
But suddenly it will not work after the update and it is strange to use crosswalk.
This framework should be marked as incompatible with the android 4.x version.
