### ISSUE TITLE
QTree UI has issues when in a Layout Drawer

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#2754]
### Software version
 Dev mode.......... electron
 Quasar theme...... mat
 Quasar CLI........ v0.17.22
 Quasar Framework.. v0.17.18
 Debugging......... enabled
quasar info

Operating System                Linux(4.15.0-38-generic) - linux/x64
NodeJs                          8.12.0

Global packages
  NPM                           6.4.1
  yarn                          1.12.3
  quasar-cli                    0.17.22
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages
  quasar-cli                    0.17.22 (Quasar Framework CLI)
  quasar-framework              0.17.18 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      3.0.8   (Build cross platform desktop apps with JavaScript, HTML, and CSS)
  electron-packager             12.2.0  (Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI)
  electron-builder              20.34.0 (A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box)
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.25.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.10  (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.6.3   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

Networking
  Host                          jeff-ubuntu
  enp2s0                        10.10.2.106

### JsFiddle (for Quasar v0.15+ only)
https://codepen.io/Hawkeye64/pen/wQgpOQ

### What did you get as the error?
There are a couple of issues:
1) The UI text in the QTree starts to wrap when it hits the edge of the Layout Drawer
2) If you keep expanding QTree nodes, the selected (the selection background color) node's UI will not exeed past the Layout Drawer width, even though the hortizonal scrollbar shows up.

### What were you expecting?
For all nodes, the same behavior

### What steps did you take, to get the error?
Keep expanding nodes until the horizonal scrollbar shows up
![qtree-ui-issues](https://user-images.githubusercontent.com/10262924/48423074-283db280-e71d-11e8-96fe-2c00a4c352a9.png)

**Comment by rstoenescu** [comment]
This should be fixed in latest v1.
