### ISSUE TITLE
QPopover removeChild exception

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2756]
Hello!

Sorry for this strange jsfiddle, it was sort of hard to reproduce this issue.
Basically, what happens is that parent element is removed before popover is fully initialized.

https://jsfiddle.net/7Luvnzc8/1/
1) Press toggle a couple of times until exception happens (need to catch that race condition)

Thanks!

**Comment by jean-moldovan** [comment]
![screen shot 2018-11-14 at 18 54 19](https://user-images.githubusercontent.com/3635352/48494534-2409b600-e83f-11e8-9957-09fba5ff07f6.png)

**Comment by rstoenescu** [comment]
Fixed in v1.0 due to a smarter implementation.
