### ISSUE TITLE
Quasar Developer Operations [WIP][RFC-Zero-2]

### ISSUE THREAD

**Issue by PhearZero** [quasarframework/quasar#2759]
# Quasar Developer Operations [RFC-Zero-2]
### Overview:
  Add basic Vagrant, Docker, and Docker-Compose examples for downstream apps. 
  Outline developer operations for internal framework components. Introduce deployments
  to the cli pipeline
### Quasar-Cli Goals: 
  - [ ] New top level script 'deploy' for ```quasar deploy``` 
  - [ ] Adopt 'modes' for deployment runner ```quasar deploy mode -a Amazon```
      - [ ] ****Azure**** - Azures Websites Deployment (SSR would be optional Cloud Function)
      - [ ] ****Amazon**** - Amazon Simple Website S3 Service (SSR would be optional Lambda)
      - [ ] ****GoogleSites**** - Google Apps Sites (SSR would be optional Cloud Function)
      - [ ] ****Firebase**** - Google Firebase Hosting (SSR would be optional Cloud Function) quasarframework/quasar-cli#200 quasarframework/quasar-cli#201
      - [ ] ****GithubPages**** - GitHub Page Hosting (SSR not available without another deploy target)
      - [ ] ****Docker**** - Any valid docker host (SSR would be optional scaleable container)
      - [ ] ****Other**** - Abstraction to add 'deployment plugins/hooks'
  - [X] Dockerize the CLI as quasar/cli
### Quasar-Framework Goals:
  - [ ] Dockerize the framework build with optional Vagrant
  - [ ] Dockerize RFC-Zero-1 Testting quasarframework/quasar#2758 for local test running

**Comment by smolinari** [comment]
If I can help with Docker stuffs in some way, please let me know.

Scott

**Comment by PhearZero** [comment]
@smolinari Will do! You can find the very beginnings of Docker over at fansanelli/quasar-webdriver/#2 It's a WIP but some of the features will end up here from #2758. Long term goal is to be able to run quasar-framework-dist builds/tests in a container as part of the CI/DevOps pipeline with shorter term goal of containerized testing utilities like headless browsers/Selenium Grid and quasar-cli. 

The hope here is to EYODF where the quasar-framework uses the same build/deploy tools as downstream Quasar-Apps, Docker being optional. Here is an [old travis build](https://travis-ci.org/Barnstorm-Online/Dashboard/builds/446956268) for a project that I'm going to be bringing along for the ride! If we stick to OSX images on Travis then we should be able to build for all targets. 

Some other things are on my list to update here like js/esdoc where we can move some of the documentation workload to the codebase via [jsdoc-vuejs](https://github.com/Kocal/jsdoc-vuejs) assuming that they/we can either add vue-mixins and vue-events. This would allow for the framework to be the "source of truth" and would be in addition to the current documentation. It would also require to port/merge quasar-docs to a js/esdoc theme like [minami](https://github.com/nijikokun/minami). Luckily they both support markdown and we would just need to remove the props/events and port the theme.

This RFC is just a place to dump ideas for now!
