### ISSUE TITLE
QInfiniteScroll listener is not removed properly

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2763]
Hello!

Sorry for not being able to provide a proper jsfiddle.
What I'm seeing in my app is that after QInfiniteScroll is destroyed, `poll` function is still fired on scroll.

To reproduce:
1) add log to quasar inf scroll source code to debug
```
methods: {
  poll () {
    console.log('inf scroll poll')
  ...
  }
}
```
2) navigate to the page that has inf scroll
3) navigate away to the page that doesn't have inf scroll (get's destroyed)
4) `poll` function is still fired

Thanks!

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce. Looking at the source code, everything is fine.
Please reopen with a reproduction repo or jsfiddle.

Thank you.

**Comment by jean-moldovan** [comment]
Hello!

@rstoenescu , I've added a test repo so that we can investigate:
https://github.com/jean-moldovan/quasar-inf-scroll-demo

What's in there:
1) added a simple log command
https://github.com/jean-moldovan/quasar-inf-scroll-demo/blob/master/node_modules/quasar-framework/src/components/infinite-scroll/QInfiniteScroll.js#L28
2) added QInfiniteScroll component to the page, added v-if flag
https://github.com/jean-moldovan/quasar-inf-scroll-demo/blob/master/src/pages/Index.vue

How to reproduce:
1) press 'Destroy this!', `beforeDestroy` hook is triggered, event listener is supposed to be removed
2) scroll the page, `poll` is still fired

![screen shot 2018-11-20 at 14 02 37](https://user-images.githubusercontent.com/3635352/48769668-44b58e00-eccd-11e8-9582-04fc9d38acf6.png)

Thanks!

**Comment by jean-moldovan** [comment]
Tested on Chrome Version 70.0.3538.77
