### ISSUE TITLE
Configure <link rel=prefetch> for each route ?

### ISSUE THREAD

**Issue by luatnd** [quasarframework/quasar#2764]
Hi,
I built Quasar app in PWA mode and I got my `dist/pwa-mat/index.html`:
```
...
  <link href=/css/0ad6dc67.34889729.css rel=prefetch>
  <link href=/css/2bdeb058.439f2c9c.css rel=prefetch>
  <link href=/css/3ba5a92e.6576ecf7.css rel=prefetch>
  .... And so many other css files ....
  <link href=/js/0ad6dc67.d1e8d483.js rel=prefetch>
  <link href=/js/23d245c0.99f13075.js rel=prefetch>
  <link href=/js/2bdeb058.882fbd89.js rel=prefetch>
  .... And so many other js files ....
...
```
It takes a lots unnecessary prefetching files, seem **all files** in my app.

So how can I configure the prefetch files per route?
Or just disable prefetching feature above? (because my necessary files are already handled and cached by the service worker.)

**Comment by rstoenescu** [comment]
Hi,

quasar.conf.js > build > preloadChunks: false
It's not a good idea to disable it though due to how service worker works.
