### ISSUE TITLE
Promise not defined

### ISSUE THREAD

**Issue by tomspiegl** [quasarframework/quasar#277]
Current release does not work in IE 11 v0.10.3
Error: Promise not defined

Is there a way to get it running in IE 11?

**Comment by rstoenescu** [comment]
Quasar doesn't uses Promises. Can you confirm that this is from Quasar's code indeed or is it from another library that you are using?

**Comment by tomspiegl** [comment]
Maybe it's just the components page that is not working on IE 11.

[http://quasar-framework.org/components/label.html](http://quasar-framework.org/components/label.html)

**Comment by rstoenescu** [comment]
Seems to be in Webpack's bundling code. Use es6-polyfill until I figure it out with guys over at Webpack.
Npm install and `require('es6-promise').polyfill()` in main.js at the top.

Thanks!

**Comment by tomspiegl** [comment]
Thanks will give it a try

**Comment by rstoenescu** [comment]
Instructions on how to add the Promise polyfill will be available on the documentation website after v0.11 release.
