### ISSUE TITLE
Doc enhancement: provide details on how to add a web pack loader to Quasar toolchain

### ISSUE THREAD

**Issue by mjmare** [quasarframework/quasar#2778]
It would be very useful to have some more information on how to include additional web pack loader to the Quasar config files. 

See here for some background for my request.
https://forum.quasar-framework.org/topic/2922/how-to-integrate-python-webpack-loader

(BTW Thanks for creating Quasar!)

**Comment by smolinari** [comment]
You'll probably want to make this suggestion in the docs repo. 

https://github.com/quasarframework/quasar-framework.org

Scott

**Comment by mjmare** [comment]
Ah OK. I have created an entry there. Thx.
