### ISSUE TITLE
Tabs css sharing

### ISSUE THREAD

**Issue by rof20004** [quasarframework/quasar#278]
Hi all,

I am new with Quasar and it is very interessant, I tested the Tabs component, I see something(I do not know if it's wrong). 

1. My first tab has a particular CSS, when I select the second tab(that has another particular CSS) the second tab take all the first tab CSS. I wanna that each tab have your particular CSS.

Example:

1. First tab has width: 50%
2. Second tab has no width setted or width 100%

When I change from first tab to second, the width take 50%, but I declared 100% for second tab.

First tab:
```
.card-title
  text-align: center
  font-size: 24px

.card-content input
  margin-bottom: 20px

@media screen and (min-width: 960px)
  .card
    width: 50%
    margin: 0 auto
```

Second tab:
```
button
  margin-top: 10px
```

Thanks and Regards,

Rodolfo Azevedo

**Comment by rstoenescu** [comment]
Hi,

I believe what you are searching for is `justified` CSS class that can be applied to `<q-tabs>` (Quasar v0.11 required). Lose the width in percentage as it won't work. Tabs use flexbox under the covers.

Please use forum for questions ;)

Cheers,
Razvan
