### ISSUE TITLE
q-datetime: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by Clemens-B** [quasarframework/quasar#2788]
### Software version

Quasar: v0.17.17
OS: Windows, Linux, iOS
Node: latest
NPM: latest
Browsers: Chrome, Firefox, Edge

### JsFiddle (for Quasar v0.15+ only)
https://codepen.io/anon/pen/zMaXJX

### What did you get as the error?
`quasar.mat.umd.min.js:6 Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at o.__scrollView (VM2820 quasar.mat.umd.min.js:6)
    at VM2820 quasar.mat.umd.min.js:6`
### What were you expecting?
No error
### What steps did you take, to get the error?
Douple click on one of the modal buttons

### More Context

It happens only with default-view=year.
The datepicker is inside a component and a v-if-statement. Happens when routing between views or inside modals. Doesn't affect the functionality, but not really nice to have it in the exception logs...

**Comment by zeidanbm** [comment]
The problem is that datetime picker didn't render yet as you are using v-if and wrapping q-modal. You can use v-show so that datetime will mount on load or better you actually don't need to wrap q-modal and cause v-model on q-modal handles that for you.
