### ISSUE TITLE
How to use skeleton page loading in quasar

### ISSUE THREAD

**Issue by deepuprajapati** [quasarframework/quasar#2797]
I need to data loading placeholder (skeleton) like facebook or linkedin
how could i use it.

**Comment by rstoenescu** [comment]
There's an entire section on this in the docs (called "Progress"):

* https://quasar-framework.org/components/loading.html
* https://quasar-framework.org/components/spinner.html
* https://quasar-framework.org/components/ajax-bar.html
* https://quasar-framework.org/components/loading-bar.html
* https://quasar-framework.org/components/inner-loading.html
* https://quasar-framework.org/components/progress-bar.html
