### ISSUE TITLE
add eva icons

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2798]
Would be nice to add these:
https://akveo.github.io/eva-icons/#/

**Comment by dkabracadabra** [comment]
AFAIK for now the workaround is to use icon font and start icon name with a prefix icon-* e.g. icon-dummy
`<q-btn icon="icon-dummy eva eva-github">test</q-btn>`
No svg icons support so far:(

**Comment by rstoenescu** [comment]
Will be available in future v0.17.19.
Also delivered through `quasar-extras`.
