### ISSUE TITLE
Prevent q-btn loading state from resizing the button

### ISSUE THREAD

**Issue by kyriediculous** [quasarframework/quasar#2799]
Hi,

I'm using the `:loading=<boolean>` prop of `q-btn` regularly. 

The button resizes when the spinner appears because it fits the content.

When I have a button with text on it I expect the button to keep it's original width. 

Example: 
![afbeelding](https://user-images.githubusercontent.com/22256858/49171063-f42dd880-f33d-11e8-9111-8d9dcfe81b42.png)

![afbeelding](https://user-images.githubusercontent.com/22256858/49171075-fd1eaa00-f33d-11e8-9fb6-d71aadd7addc.png)

**Comment by pdanpdan** [comment]
Then set that width on the button, it should work.

**Comment by kyriediculous** [comment]
That's not a solution even thought it "should work". 

That means I would manually have to fix size every button with a loading state.

**Comment by pdanpdan** [comment]
I don't understand. What size should the button keep? How could it know what size you want. It can fit to size or respect the size you provide.

**Comment by rstoenescu** [comment]
There is a way to do it. I'll push a commit soon.

**Comment by rstoenescu** [comment]
@pdanpdan Can you port my v1.0 commit above to v0.17? Thanks.

**Comment by pdanpdan** [comment]
Sure

**Comment by rstoenescu** [comment]
Scheduled for Quasar v0.17.19.
