### ISSUE TITLE
blank screen cordova

### ISSUE THREAD

**Issue by donnygunawan93** [quasarframework/quasar#280]
Hello Q(^_^)Q

I download your default template, on browser it work, then i try on quasar play it work also.
But when I try to install apk only showing white screen.
I try to installing apk with ionic starter it work.
I do not know what causes, any hint?

**Comment by rstoenescu** [comment]
Hi,

This is more of a question for forum first. I can confirm everything works with the default template. Ionic apk deployment to a phone/tablet is a wrapper of cordova. So basically same command runs when deploying a Quasar app with cordova directly.

What you can do is use remote debugging to find out what is causing your issue: http://quasar-framework.org/guide/cordova-wrapper.html#Remote-Debugging

Please reply with your findings (eventual error message). Thanks!

**Comment by donnygunawan93** [comment]
Sorry, my bad, just missing dependecies

**Comment by DengnisR** [comment]
hi-- what dependencies do you need to be able to remove this error?--
