### ISSUE TITLE
[Bug] Date Utils formatDate i18n not using the supplied day and month names

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#2805]
### Software version

Operating System         	Linux(4.18.16-arch1-1-ARCH) - linux/x64
NodeJs                   	11.1.0

Global packages          	
  NPM                    	6.4.1
  yarn                   	1.12.3
  quasar-cli             	0.17.22
  vue-cli                	2.9.6
  cordova                	Not installed

Important local packages 	
  quasar-cli             	0.17.22	(Quasar Framework CLI)
  quasar-framework       	0.17.18	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras          	2.0.9	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.25.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.10	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.6.3	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.5.2	(Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/waugrryy/7483/

### What did you get as the error?
The formatted date shows the default English day and month names.

### What were you expecting?
The formatted date should display the day and month names according to the given input of the arrays.

### What steps did you take, to get the error?
`date.formatDate(Date.now(), 'MMMM - dddd', {
        dayNames: ['Zondag', 'Maandag', 'Dinsdag', 'Woensdag', 'Donderdaqg', 'Vrijdag', 'Zaterdag'],
        monthNames: ['Januari', 'Februari', 'Maart', 'April', 'Mei', 'Juni', 'Juli', 'Augustus', 'September', 'Oktober', 'November', 'December']
      })`

**Comment by rstoenescu** [comment]
Scheduled for Quasar v0.17.19.
