### ISSUE TITLE
Unhandled promise rejection TypeError:

### ISSUE THREAD

**Issue by patrickmonteiro** [quasarframework/quasar#2810]
I have an error trying to access the build through the internet explore. Where the "from" property is not found.

![image](https://user-images.githubusercontent.com/13258255/49235206-5804df80-f3d8-11e8-8737-77ed95a316ca.png)

![image](https://user-images.githubusercontent.com/13258255/49235300-8edaf580-f3d8-11e8-8f5f-5a27eb8ca9b3.png)

**Comment by rstoenescu** [comment]
Hi,

Quasar has been tested for IE compatibility thoroughly. So isn't this a problem in your code? Screenshotting a cryptical error without us having a reproduction case does not help at all.

Please reopen with something that can be investigated. Thank you.
