### ISSUE TITLE
Feature request: left/right selection area list thingy (see image)

### ISSUE THREAD

**Issue by rconstantine** [quasarframework/quasar#2811]
See screenshot of a feature we've been using in a windows app.

![screenhunter_346 nov 29 08 16](https://user-images.githubusercontent.com/8312587/49236873-ec0f8080-f3b1-11e8-9ce5-731e028db680.jpg)

**Comment by fansanelli** [comment]
Hello @rconstantine 
I could be interested in this feature. Did you start to implement it?
Cheers
Francesco

**Comment by rconstantine** [comment]
No, I haven't had time to start this. It'll be some time before I'll be free to do so due to project deadlines.

**Comment by fansanelli** [comment]
Dear @rconstantine 
Monday I'll share a component I did starting from your screenshot, so you can help me to maintain it if you will...
For me the main goal is iOS look and perfect fit on iPhone.
Have a nice weekend
Francesco

**Comment by fansanelli** [comment]
Hi @rconstantine 
here my attempt:
https://github.com/fansanelli/quasar-comp-selection

![schermata del 2018-12-06 17-10-54](https://user-images.githubusercontent.com/13917866/49717135-51872b00-fc56-11e8-8b64-fe7ada9b669e.png)

please let me know what you think
Cheers
Francesco

**Comment by smolinari** [comment]
Ciao Francesco. 

Looks pretty slick. Good job! :+1: 

Scott

**Comment by rstoenescu** [comment]
Hi,

You can create an App Extension with this component in v1. I'd be glad to see one.
https://quasar.dev/app-extensions/introduction
