### ISSUE TITLE
Textarea render (maybe a bug)

### ISSUE THREAD

**Issue by marcelo-rebello** [quasarframework/quasar#2812]
Hi,
First of all, congrats for Quasar! It is an amazing framework.

But I found one issue related with the way a textarea QInput is render in the browser DOM that maybe is a bug...

I am writing some Cypress e2e tests for an SPA using Quasar and get stuck with a super simple component test. I was not able to check if a value sent to the component was rendered by a  QInput textarea.
Digging in Quasar code, I found this render function in file 
`https://github.com/quasarframework/quasar/blob/dev/src/components/input/QInput.js - line 298`

```
        h('textarea', {
          ref: 'input',
          staticClass: 'col q-input-target q-input-area',
          attrs: Object.assign({}, attrs, {
            placeholder: this.inputPlaceholder,
            disabled: this.disable,
            readonly: this.readonly
          }),
          domProps: { value: this.model },
          on: {
            input: this.__set,
            focus: this.__onFocus,
            blur: this.__onInputBlur,
            keydown: this.__onKeydown,
            keyup: this.__onKeyup,
            paste: this.__onPaste
          }
        })
      ])
```

So, the model value is rendered thought a value HTMLDom property. (`domProps: { value: this.model }`)

But an HTML textarea element does not treat value property like all other input fields.
When I inspect the generated code in browser I can not see the model value anywhere in HTML code, nor is Cypress able to test for its presence (just because it is not there).

If I just change line 298 to 
```
domProps: { innerHTML: this.value }
```
looks like everything works fine, the content shows in HTML and Cypress tests works...
I only test this Chrome, so I do not know if this change breaks something in other browsers/platforms, but would be nice if Quasar renders it in a more testable way...

Regards
Marcelo

**Comment by rstoenescu** [comment]
Hi,

It's not a bug. It's how it should be. You can use .getAttribute('value') on the $refs.input.
