### ISSUE TITLE
[Request] QChatMessage  : dense prop or size prop

### ISSUE THREAD

**Issue by florentpeyrard** [quasarframework/quasar#2820]
Hi,

that would very useful on mobile to have a `dense` prop or `size` prop. Currently, the messages are rather big, which implies we can only display a few of them on mobile. This is mainly due to the avatar size, and the text could be more dense as well.

**Comment by pdanpdan** [comment]
you can change the `$chat-message-text-padding`, `$chat-message-distance`, and `$chat-message-avatar-size` Stylus/SCSS variables to set the desired padding, distance and avatar size.
