### ISSUE TITLE
LoadingBar - unable to set default properties in UMD version.

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#2822]
I try different settings, but I can't set defaults with method `LoadingBar.setDefaults({...})`, like says in documentation:

https://quasar-framework.org/components/loading-bar.html#Setting-Up-Defaults

I try this:
`Quasar.plugins.LoadingBar.setDefaults({ position: 'bottom', color: 'light-green-8' });`
`this.$q.loadingBar.setDefaults({ position: 'bottom', color: 'light-green-8' });`

https://jsfiddle.net/Lwe1sdvm/

**Comment by huyang271** [comment]
@olegvakulenko 
I had the same problem, but it was solved.

**Here is the code，I hope it can help you:**
![image](https://user-images.githubusercontent.com/32186505/50274316-e9b3ba00-0477-11e9-8687-45889e4857a3.png)

**Comment by rstoenescu** [comment]
@huyang271's way is the correct way to do it.
