### ISSUE TITLE
[Proposal] LoadingBar - indeterminate (and other) property

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#2823]
Hi!

IMHO, this is useful to have ability to customize `LoadingBar` like `QProgress`.

Thanks!

**Comment by mkarras** [comment]
Would be great! Is there a chance that the feature will come (soon) @pdanpdan ?

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
