### ISSUE TITLE
[Enhancement] Custom QTree tickStrategy

### ISSUE THREAD

**Issue by patforg** [quasarframework/quasar#2826]
I just started using the QTree component and can't get the functionality I need with the current tickStrategies and can't seem to find an easy way to get this done.

I would like to recursively tick parents on when I click a child node.
I do not want to alter tick status of child nodes.

The use case is I have a hierarchy of categories.   If a sub category is ticked, I want to tick all parent categories.  I also want to be able to select a non leaf category on it's own (without ticking its children)

It's basically stict startegy but also ticking parents automatically.

Example:
```
Tree
-- 1
  |-- 1.1 
  |-- 1.2
  |---- 1.2.1
  |---- 1.2.2
  |-- 1.3
-- 2
  |-- 2.1
  |-- 2.2
  |-- 2.3
```

Suppose we start with no ticked nodes.

if user  ticks node 1.2 tree would also have node 1 ticked.
if user  ticks node 1.2.1 tree would also have node 1.2 and 1 ticked.
if user  ticks node 1 tree would not change any status of sub nodes. 

Un-ticking nodes would do nothing else that removing tick on current node.

**Comment by nothingismagick** [comment]
Can you confirm if this behavior is present and what you want in v1?
https://v1.quasar-framework.org/vue-components/tree#Selection-vs-ticking%2C-expansion

**Comment by rstoenescu** [comment]
This should be in v1 already. Please reopen if I missed something. Thanks.
