### ISSUE TITLE
QUploader - progress stuck on 99% after finishing uploading

### ISSUE THREAD

**Issue by kchrzanowski** [quasarframework/quasar#2829]
### Software version

quasar info

Operating System                Darwin(16.7.0) - darwin/x64
NodeJs                          8.12.0

Global packages                 
  NPM                           6.4.1
  yarn                          1.9.4
  quasar-cli                    0.17.20
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages        
  quasar-cli                    0.17.20 (Quasar Framework CLI)
  quasar-framework              0.17.17 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.8   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)

QUpload.js file, function in line 90:
`progress () {
      return this.totalSize ? Math.min(99.99, this.uploadedSize / this.totalSize * 100) : 0
},`

### What did you get as the error?
Stuck on 99% uploading - process finished

### What were you expecting?
have 100% no stuck/error uploading

### What steps did you take, to get the error?
upload file using q-uploader

**Comment by rstoenescu** [comment]
Can you make a jsfiddle or something so I can reproduce your scenario?

**Comment by kchrzanowski** [comment]
I forked from your fiddle, but not rendering
https://jsfiddle.net/7kr0ateu/
this has all logic I am using for this component, method from jersey endpoint returns status code 200 and there is no xhr pending in network

**Comment by rstoenescu** [comment]
```js
return this.$axios
        .post('http://localhost:8080/api/logo', fd, { headers: { 'Content-Type': 'multipart/form-data' } })
```

Reason: upload-factory needs to be a function returning a Promise. Since you weren't returning anything, the awaited Promise never fulfils.

**Comment by kchrzanowski** [comment]
And what with updateProgress?
When there is no "then" I return unresolved promise and I can't updateProgress as you see in the fiddle. Without function updating progress it is stuck on 0%

![image](https://user-images.githubusercontent.com/612824/49503977-fed5f980-f878-11e8-98c7-b86835c6e601.png)

**Comment by klimentLambevski** [comment]
@rstoenescu upload gets stuck if the result of the promise returned in uploadFactory is not File.

**Comment by apmcodes** [comment]
@klimentLambevski can you please elaborate on what kind of file to return from the promise. Facing similar issue #2893
