### ISSUE TITLE
There are No navbar?

### ISSUE THREAD

**Issue by AhsanAbrar** [quasarframework/quasar#283]
this is really awesome framework but i can't see navbar option here.

i mean navbar component for both desktop version and mobile version and collapsible too.

maybe you are working on this or already exists?

**Comment by murbanowicz** [comment]
Please read DOCS or ask this kind of questions on forum.

http://quasar-framework.org/components/toolbar.html

**Comment by caex** [comment]
With a Layout component, you can put a Tabs component in the Navigation slot and get something like this : 
http://quasar-framework.org/quasar-play/android/index.html#/showcase/layout/tabs

Is it what your looking for ?


By collapsible do you mean something like this ? http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_navbar_collapse&stacked=h
(it's responsive)

If so I'm not aware of such component in Quasar.
But the tabs can be horizontally scrolled by touch on mobile, and you can use the Drawer component to display a longer menu.

As I see it it would still be 'easy' to replicate the boostrap example yourself thanks to : 
_ Navigation (or Header ?) slot
_ Collapsible component
_ Popover component
_ `sm` and `gt-sm` classes for the conditional rendering
