### ISSUE TITLE
[Request] QRange : constraints on range

### ISSUE THREAD

**Issue by florentpeyrard** [quasarframework/quasar#2830]
My need is to prevent the user from setting a range (difference between actual min slider and max slider) below a value set as a prop. 

For instance : if the new prop is called minRange and we set it to 5, the user can set the min slider to 1 and the max slider to 7 but if the user tries to move the max slider below 6, the max slider doesn't move any more, it sticks to 6, and only moves again if the user drags it above 6.

Probably having a maxRange slider could be helpful as well.

**Comment by nothingismagick** [comment]
I understand what you want, but feel like this can be addressed simply with a method triggered on input in v1.

See what I mean here:
https://codepen.io/nothingismagick/pen/vwKjPz?editors=1111

@florentpeyrard
