### ISSUE TITLE
touchstart event handler in QModal causes performance warning and scroll jank in mobile

### ISSUE THREAD

**Issue by onexdata** [quasarframework/quasar#2832]
### Software version
Operating System                        Windows_NT(10.0.17134) - win32/x64
NodeJs                                  8.11.3

Global packages
  NPM                                   6.0.0
  yarn                                  1.9.4
  quasar-cli                            0.17.20
  vue-cli                               3.2.1
  cordova                               7.0.1

Important local packages
  quasar-cli                            0.17.20 (Quasar Framework CLI)
  quasar-framework                      0.17.17 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                         2.0.8   (Quasar Framework fonts, icons and animations)
  vue                                   2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                            3.0.1   (Official router for Vue.js 2)
  vuex                                  3.0.1   (state management for Vue.js)
  electron                              Not installed
  electron-packager                     Not installed
  electron-builder                      Not installed
  @babel/core                           7.1.2   (Babel compiler core.)
  webpack                               4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server                    3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin                3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker               1.5.2   (Script for registering service worker, with hooks)

### What did you get as the error?
Excessive jank on mobile when scrolling within QModals.

### What were you expecting?
Buttery liquid smoothness.

### What steps did you take, to get the error?
Chrome Rendering Tab, checkbox "Scrolling performance issues" lists everything within QModal components as having performance issues (i.e. any touchable controls like buttons, etc. greatly slow things down).

## Fix:
in QModal.js, removing "on: { touchstart: this.__stopPropagation }" (currently line 304) fixes the issue; Chrome no longer shows QModal as being a performance issue, and mobile scrolling in QModals is buttery smooth like native.

I can create a PR, but I am unsure if doing this affects something else within Quasar, although I have not seen any issues with the change.  Can I get some feedback on this?

**Comment by onexdata** [comment]
As additional information, I tracked down this issue by reading this article on passive event listeners and letting the browser decide if touch scrolling is occuring (this may impact a decision on removing touchstart vs making it passive, not sure). 

https://developers.google.com/web/updates/2016/06/passive-event-listeners#learn_more

**Comment by codingfriend1** [comment]
I was able to get a quick fix adding these styles to my page

.q-responsive-modal
  overflow auto !important

.q-body-fullscreen-mixin, 
.q-body-prevent-scroll
  overflow auto !important

**Comment by rstoenescu** [comment]
This has been thoroughly taken care of in v1 beta.
