### ISSUE TITLE
[Request] Toggle size prop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2833]
I have a form which has a lot of smaller elements, but only the toggle size is big.

I'd love the possibility to change the toggle size through a `size` prop on q-toggle.

**Comment by rstoenescu** [comment]
Hi,

Sorry, but this is not going to be implemented any time soon.

**Comment by pintaf** [comment]
Hi! As a quick hack you an use this:
style="transform : scale(1.3, 1.3);"
more than one will increase size, less will reduce

**Comment by mesqueeb** [comment]
Yeah I'm currently using scale to make the toggle bigger, but it gives very blurry results sadly...
I'd still love to be able to set a bigger size for quasar components like the toggle ;)
