### ISSUE TITLE
QPopover position shifted when no scroll on page

### ISSUE THREAD

**Issue by mrKoujou** [quasarframework/quasar#2834]
### Software version
quasar-framework                      0.17.18
Browsers:                                    Chrome, FireFox, maybe any

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/wmxu6cz5/1/
Open the Right tab and notice empty space between popover content and right side of the screen.

### What did you get as the error?
Popover is shifted to the left from the right side of a screen when there is no scrollbar on the page.
Looks like scroll width is saved on page start and always taken into account inside repositionIfNeeded function. Even when there is no scroll on page.

### What were you expecting?
Expecting for the popover content's top right corner to be just under the right bottom corner of the anchor (in example - q-tab). So that popover will be close up to the right side of the screen.

**Comment by rstoenescu** [comment]
This should no longer be an issue in v1.
