### ISSUE TITLE
Hardcoded english in DataTable

### ISSUE THREAD

**Issue by caex** [quasarframework/quasar#284]
Hello,

just integrated the DataTable component and it's great.
However one problem is the hardcoded english, unfortunately my WebApp is in french.

There are the culprits :
(DataTable.vue line 20)
````
static-label="Columns"
````
(lines 30-31)
````
{{ rowsSelected }} item<span v-show="rowsSelected > 1">s</span> selected.
  <button class="primary clear small" @click="clearSelection()">Clear</button>
````
(TablePagination.vue line 4)
````
Rows
````

Would be great if we could customize it through Props or Slots.

Or to have just one lang="en" prop and let the community build a language file for each language, with fallback to english 👍 

Cheers

**Comment by rstoenescu** [comment]
Yes, part of Internationalization #100 . Will soon be fixed.

**Comment by rstoenescu** [comment]
Internationalization as a whole might take a while, so adding config.labels to handle this.
