### ISSUE TITLE
[BUG] q-datetime :max Error

### ISSUE THREAD

**Issue by antoxxxa-2** [quasarframework/quasar#2841]
Quasar: 0.17.18
OS: Mac OS
Node: 10.3
NPM: 6.1.0
Browsers: All
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/xs37jq4b/2/

### What did you get as the error?
When :max params goes before :value month, Calendar still opened on :value month and shows 32 and more days in it.

### What were you expecting?
Calendar should be open on :max month with correct days

### What steps did you take, to get the error?
in jsfiddle 2 examples: first with :max in the current month and second with described problem behavior

![image](https://user-images.githubusercontent.com/1327258/49587952-805f8180-f976-11e8-8586-6ea0614eafef.png)

**Comment by vinicius73** [comment]
Same error here.

**Comment by rstoenescu** [comment]
Hi,

This has been taken care of in v1. Closing.
