### ISSUE TITLE
strange behavior of drawer when resize from xs to lg

### ISSUE THREAD

**Issue by DenniLa2** [quasarframework/quasar#2843]
Quasar: 0.17.18
OS: macOs / windows
Node: v8.11.3
NPM: 6.4.1
Browsers: chrome

### repo with code
https://github.com/DenniLa2/quasar-drawer

### What did you get as the error?
![animated gif](https://user-images.githubusercontent.com/9018493/49635309-fe1f9d80-fa07-11e8-85e1-510c8862ee87.gif)
After resize width of browser drawer opened full height

### What were you expecting?
Drawer under header

### What steps did you take, to get the error?
1. resize to xs
2. open drawer
3. resize to lg

**Comment by olegvakulenko** [comment]
https://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/play-with-layout

Try change this:
 ```
<q-layout
      class="app-layout__wrapper"
      view="HHh Lpr lFf"
    >
```

to this:

 ```
<q-layout
      class="app-layout__wrapper"
      view="hHh Lpr lFf"
    >
```

**Comment by DenniLa2** [comment]
Nothing changed. Drawer puts on a header (

**Comment by olegvakulenko** [comment]
Try to fork and reproduce this with

[jsfiddle.net](https://jsfiddle.net/rstoenescu/waugrryy/)

or 

[codepen](https://codepen.io/rstoenescu/pen/KQRZJg)

**Comment by rstoenescu** [comment]
Hi,

There is a mistake in your example. Why are you changing the `behavior` prop of Drawer based on screen width? That's what `breakpoint` is for...
