### ISSUE TITLE
[BUG] Model toggle mixin doesn't respect v-bound value, modals close when they shouldn't

### ISSUE THREAD

**Issue by tmas** [quasarframework/quasar#2845]
### Software version

Quasar: 0.17.17
OS: Linux(4.18.0-11-generic) - linux/x64
Node: 10.13.0
NPM: 6.4.1
Browsers: Chrome, Firefox
iOS: N/A
Android: N/A
Any other software related to your bug: N/A

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/tlord/9b27njLv/16/
### What did you get as the error?
Modal closes when escape is pressed or the user clicks outside the modal, despite its v-bound value not changing. It subsequently cannot be reopened without reloading the page.

The dialog intended to confirm the user's intent to close the modal shows on the page, but is irrelevant because the modal has already closed itself.
### What were you expecting?
In the provided JSFiddle, the modal should only close when allow_close is set to true or the user chooses "Yes" in the confirmation dialog.

The modal should only close when the parent element responds to its input event by changing the bound value. Currently the model-toggle mixin maintains both the value prop and a data value called "showing", which has at best a loose relationship to the actual value prop. The mixin should ideally follow the prop exactly (e.g. only show/hide the component when the value changes, not when it's expected to change), or at least provide a way to run a handler before closing the modal so that the parent element can cancel the close event.
### What steps did you take, to get the error?
Click the Open Modal button, then hit escape. The confirmation dialog will open, but the modal will close despite its value not being updated by the parent component.

**Comment by smolinari** [comment]
Hi @tmas,

If I am understanding your issue correctly, this is normal behavior. The v-model to open and close the modal is also controlled by the modal itself, for the actions you are implying should not work, if the parent is changing v-model. 

The features you are actually looking for are built into QModal, however. [You should refer to the docs and the props lists of components](https://quasar-framework.org/components/modal.html#Vue-Properties), before writing any issues. It might save you some time. 😄 Of course, I am saying this assuming I am understanding your issue correctly. I hate to say RTFM, because it does mean I am making assumptions. 

At any rate, see if [this is what you are expecting](https://jsfiddle.net/smolinari/bwud0gjs/). I also used the `minimized` prop, so you can also see the `no-backdrop-dismiss` prop in action.

Scott

**Comment by tmas** [comment]
Hey @smolinari,

Thanks for the answer. I did actually read the docs (pretty thoroughly) before posting. The problem I'm running into is that, while the modal does use `this.$emit('input', value)` to update the v-model, it also maintains an entirely separate copy of its state called `showing`. This means that when the parent changes the state the modal reacts properly, but the parent doesn't actually maintain full control over the state as it's supposed to.

The specific behavior I was trying to demonstrate with my JSFiddle is that, when the modal attempts to close itself, it calls `this.$emit('input', false)` (as it should). Rather than waiting for the parent to update the bound value, however, it also calls `this.showing = false`. The variable actually controlling the visibility is not `value`, but `showing`. Here's one example of the problem code from /src/mixins/model-toggle.js:
    

    this.showing = false

    if (this.value === true) {

        this.$emit('input', false)

    }


My real-world goal with all this is to have a modal with a form that allows users to edit data. I want to allow users to close the modal by clicking the backdrop or by hitting the escape key, but when they do that I want to check whether they have unsaved changes. If they do, I want to show a dialog warning them about the unsaved changes. If they click cancel, the modal should stay open to allow them to review/save their changes. If they click close, the modal should close.

Being able to do things like this relies on the modal never closing itself unless the parent actually updates the bound value, which I think is the most reasonable expected behavior for this feature since that's the whole mechanic for v-model.

Alternatively, if there's a reason why `showing` has to be the actual variable controlling the visibility of the modal and not just a tracker to detect whether `value` has changed from the current displayed state, I could see an onClose or beforeClose handler filling the gap. I've seen example of this working in ElementUI - the way they handle it is by having the prop `before-close` on their dialog accept a function `done`, which is passed another function as its argument. Calling `done` inside the beforeClose handler is what causes the modal to actually close, so it allows the close to be essentially canceled based on some arbitrary logic.

I considered just setting up a dev environment and committing changes, but I'm not familiar enough with the project as a whole to understand the repercussions of changing the `model-toggle` mixin's behavior. Even if somebody can just confirm that changing this behavior won't break something I'm not aware of, I'd be happy to put in the legwork to get it working.

**Comment by smolinari** [comment]
Ahh...ok. I think I understand now. I've edited my fiddle to show you how I think the functionality you are looking for can work. Notice I've changed to a simple v-model. 

https://jsfiddle.net/smolinari/bwud0gjs/

Note: v1.0 will be improving on this a bit too. 😃 

Scott

**Comment by tmas** [comment]
That's definitely a lot closer to what I'm looking for. I think for now we're just going to disable other methods of closing the modal until we can get a real solution in place. Can you elaborate on the improvements in v1.0 at all? It'd be good to know if the exact functionality we're looking for is planned or if I should just figure out the dev environment for quasar and submit a PR.

Thanks!

**Comment by smolinari** [comment]
What is missing in the fiddle in terms of functionality? I'd like to know, to understand your use case better. 

I'd actually also do it differently. I'd create a modal with logic for the input form and the popup warning modal as a self-contained component.  

The best way to see the differences between the current version and version 1.0 is to clone the quasar repo twice and keep one copy on the dev branch and checkout the "v1-work" branch in the other copy. Then compare the two sets of components. 😄 

Scott

**Comment by tmas** [comment]
The goal is to have the same behavior on any close attempt via the escape key / clicking the background as you would get by clicking the close button (open the dialog and prompt rather than just canceling with no message). In theory I could add additional listeners for the escape key and maybe even figure out how to listen for the click on the background, but if there will be a beforeClose handler or the v-model will fully control the visibility in the future I'd rather just wait for that (or PR it to quasar myself) rather than building a workaround.

I'll check out v1-work and see what the changes look like so far.

**Comment by metalsadman** [comment]
> The goal is to have the same behavior on any close attempt via the escape key / clicking the background as you would get by clicking the close button (open the dialog and prompt rather than just canceling with no message). In theory I could add additional listeners for the escape key and maybe even figure out how to listen for the click on the background, but if there will be a beforeClose handler or the v-model will fully control the visibility in the future I'd rather just wait for that (or PR it to quasar myself) rather than building a workaround.
> 
> I'll check out v1-work and see what the changes look like so far.

You can use `@keyup.native.esc="checkIfSomethingChangedThenShowDialog"` and `@click.native="checkIfSomethingChangedThenShowDialog"` in your q-modal to emulate same behavior as clicking cancel button in your modal when something has changed hence displaying the confirmation dialog.

**Comment by smolinari** [comment]
Nice @metalsadman. Thanks for that! 😃 

Scott
