### ISSUE TITLE
QSelect support loading + slot popover

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2850]
Hello!

This is quite common when you load / refresh select options async while select component is being displayed. I suggest we add support for "loading" prop.

I'm also unable to display custom QPopover when select is disabled / readonly.

See fiddle for example:
https://jsfiddle.net/hbnkqojx/1/

1) Loading should be supported for QSelect 
2) I should be able to apply custom QPopover via slot when select is readonly

Thanks!

**Comment by rstoenescu** [comment]
Done for future v1.0.

**Comment by jean-moldovan** [comment]
Ok cheers everybody!
