### ISSUE TITLE
[Request] QScrollArea : props for the style

### ISSUE THREAD

**Issue by florentpeyrard** [quasarframework/quasar#2852]
Currently we can't easily style the scrollbar appearance and it looks very basic. Some props (color, rounded, transparency,...) woul be very nice. Use cases : all scroll area uses cases, actually.

**Comment by rstoenescu** [comment]
There's `thumb-style`, `content-style` and `content-active-style` props for this...

**Comment by florentpeyrard** [comment]
Ok, my bad.
