### ISSUE TITLE
Error in nextTick: "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

### ISSUE THREAD

**Issue by mings1** [quasarframework/quasar#2853]
Quasar: 0.17.4
Vue: 2.5.16
OS: Windows 8.1
Browsers: Chrome

What did you get as the error?
After pressing the month in datetime picker :
<img width="326" alt="error_after_clicked" src="https://user-images.githubusercontent.com/29059851/49730147-71e4d300-fcb2-11e8-9984-a3553d44632a.PNG">

<img width="421" alt="datetime_picker_month" src="https://user-images.githubusercontent.com/29059851/49730137-642f4d80-fcb2-11e8-9e05-cc9435da5e9c.PNG">

What were you expecting?
Expect to show December only for current year

What steps did you take, to get the error?
<template>
	<div>
      <q-datetime
        class="q-mb-lg"
        type="date"
        v-model="date9"
        :min="yesterday"
        :max="tomorrow"
        stack-label="Pick a date & time in an interval"
      />
	</div>
</template>

<style>
import {
    QDatetime,
} from '/node_modules/quasar-framework/dist/quasar.mat.esm.js';

import { date } from '/node_modules/quasar-framework/dist/quasar.mat.esm.js'

const today = new Date()
const { startOfDate, addToDate, subtractFromDate } = date

export default {
  data () {
    return {
      date9: null,
      tomorrow: addToDate(today, { days: 1 }),
      yesterday: subtractFromDate(today, { days: 1 }),
	}
  },
    components: {
    QDatetime,
    },
}
<style>

**Comment by mings1** [comment]
Here is my code:

`<template>
	<div>
      <q-datetime
        class="q-mb-lg"
        type="date"
        v-model="date9"
        :min="yesterday"
        :max="tomorrow"
        stack-label="Pick a date & time in an interval"
      />
	</div>
</template>

<style>
import {
    QDatetime,
} from '/node_modules/quasar-framework/dist/quasar.mat.esm.js';


import { date } from '/node_modules/quasar-framework/dist/quasar.mat.esm.js'

const today = new Date()
const { startOfDate, addToDate, subtractFromDate } = date


export default {
  data () {
    return {
      date9: null,
      tomorrow: addToDate(today, { days: 1 }),
      yesterday: subtractFromDate(today, { days: 1 }),
	}
  },
    components: {
    QDatetime,
    },
}
<style>`

**Comment by panstromek** [comment]
Can you create jsfiddle please? 😉  It's hard to reproduce when we don't know how exactly is the component used...

**Comment by rstoenescu** [comment]
This shouldn't be a problem in v1.
