### ISSUE TITLE
Feature Request: Quasar theme stylus using Material Colour tool

### ISSUE THREAD

**Issue by anandbaskaran** [quasarframework/quasar#2854]
I am developing an app using the material theme of Quasar. While the stylus is very useful to easily customize the app, it would be great if the stylus variables are synchronous with [google's material color tool.](https://material.io/tools/color/#!/?view.left=0&view.right=0 ).

**Comment by rstoenescu** [comment]
https://v1.quasar-framework.org/style/theme-builder
