### ISSUE TITLE
QDateTime: clearable icon is shown when date is empty

### ISSUE THREAD

**Issue by fansanelli** [quasarframework/quasar#2858]
### Software version
Operating System         	Linux(4.15.0-42-generic) - linux/x64
NodeJs                   	8.11.3

Global packages          	
  NPM                    	6.5.0
  yarn                   	Not installed
  quasar-cli             	0.17.22
  vue-cli                	2.9.6
  cordova                	8.1.2 (cordova-lib@8.1.1)

Important local packages 	
  quasar-cli             	0.17.22	(Quasar Framework CLI)
  quasar-framework       	0.17.18	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras          	2.0.9	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.25.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.10	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.6.3	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.5.2	(Script for registering service worker, with hooks)

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/jf8kpm45/

### What did you get as the error?
The clearable icon is shown when date is empty

### What were you expecting?
The clearable icon is shown only when field is not empty

### What steps did you take, to get the error?
Init with empty string the input date

I did a PR too: https://github.com/quasarframework/quasar/pull/2857

**Comment by metalsadman** [comment]
you tried initializing your date to null instead of an empty string?

**Comment by fansanelli** [comment]
Hi,
I did that way.. but my first attempt was empty string and it looked like a bug to me...

**Comment by rstoenescu** [comment]
Not a bug. There's `clear-value` prop to set the "unconfigured" value to match against, which in your case can be the empty string.

**Comment by fansanelli** [comment]
Right. i closed pr too
