### ISSUE TITLE
Drawer - Bug on Open

### ISSUE THREAD

**Issue by JeremyBYU** [quasarframework/quasar#287]
Hi, 
Love the project! However I just wanted to share a small bug I found.  When you use `q-drawer` and attempt to open by swiping with your thumb starting from the left and *finish almost all the way to the right* then the drawer does **not** open and the screen turns black.   This is running it with the cordova wrapper, not sure if it exists just using chrome.

Attached is a GIF demonstrating this.  The first swipe shows the bug, with the thumb extending almost all the way to the right.  The second swipe shows it correctly where you only slide to about halfway. The final swipe shows the bug again (let the gif run through once, sometimes it choppy the first time it runs).

![bug-quasar-framework](https://cloud.githubusercontent.com/assets/6628085/21528119/24a4b974-ccfe-11e6-867d-dbc1bd6f7c7c.gif)

Version Numbers:
```
 "dependencies": {
    "babel-runtime": "^6.0.0",
    "fastclick": "^1.0.6",
    "material-design-icons": "^3.0.1",
    "moment": "^2.15.0",
    "quasar-framework": "^0.11.0",
    "roboto-fontface": "^0.6.0",
    "velocity-animate": "^1.2.3",
    "vue": "2.1.7",
    "vue-router": "^2.0.0"
  },
```
Also here is the relevant code:

```
<template>
  <q-layout>
    <div slot="header" class="toolbar">
      <button class="hide-on-drawer-visible" @click="$refs.leftDrawer.open()">
        <i>menu</i>
      </button>
      <q-toolbar-title :padding="1">
        Alexa Love Notes
      </q-toolbar-title>
    </div>
    <q-drawer ref="leftDrawer">
      <div class="toolbar light">
        <q-toolbar-title :padding="1">
            Menu
        </q-toolbar-title>
      </div>
      <div class="list no-border platform-delimiter">
        <q-drawer-link icon="help" to="/about/">
          About
        </q-drawer-link>
        <hr>
        <q-drawer-link icon="list" to="/notes/">
          My Notes
        </q-drawer-link>
      </div>
    </q-drawer>
    <router-view class="layout-view">
</template>
```

**Comment by rstoenescu** [comment]
Will investigate. Thanks!

**Comment by rstoenescu** [comment]
Confirmed. This is next on my list of fixes.

**Comment by JeremyBYU** [comment]
Wow that was fast! I'll give it a shot and see if it works.  How should I get the fix? Pull from master?
```
"quasar-framework": "^0.11.0",
```
to 
```
"quasar-framework": "git://github.com/quasarframework/quasar.git#master",
```

**Comment by rstoenescu** [comment]
Easy fix :)
Instructions here for nightly build: http://quasar-framework.org/guide/quasar-nightly-build.html
Make sure you delete node_modules/quasar-framework before npm installing nightly (this needs to be added to docs).

Enjoy!

**Comment by JeremyBYU** [comment]
Fixed worked perfectly! Thank you!
