### ISSUE TITLE
Momentum scrolling in maximized modals

### ISSUE THREAD

**Issue by klimentLambevski** [quasarframework/quasar#2874]
The maximized modals use overflow:auto that adds additional scroll in the view. This scrolling experience on ios is not smooth.

I override the modal-content class using the following guide and it is scrolling smoothly now
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by rstoenescu** [comment]
Will be available in 1.0.0-beta.9. Thanks for reminding about it -- was on the todo list for a long time but totally forgot about it.
