### ISSUE TITLE
Why Ajax Bar is used by default?

### ISSUE THREAD

**Issue by huyang271** [quasarframework/quasar#2875]
Hi,
  As my title, **when i make a Ajax request, the Ajax Bar automatically appears!** But I never set it! 

  oh, In Quasar version 0.17.18

  Thanks!!!

**Comment by JoshEvanJohnson** [comment]
The component must be rendered in your layout somewhere. If its rendered it will automatically show for all ajax calls in what ever library you use for ajax.

Just remove the ajax-bar from your layout if you don't want it.

**Comment by pdanpdan** [comment]
Look here, search for loadingBar: https://forum.quasar-framework.org/topic/2532/quasar-quasar-cli-v0-17-0-are-out-ssr-arrived

**Comment by huyang271** [comment]
> Look here, search for loadingBar: https://forum.quasar-framework.org/topic/2532/quasar-quasar-cli-v0-17-0-are-out-ssr-arrived

I have read this document. But I still can't hide default loading. I'm using quasar-umd v0.17.18 development. I try config it by `window.quasarConfig = { ... }` ,but failed! Can you show me the code about how to config it? Thank you!!!

**Comment by metalsadman** [comment]
check if you set framework object to 'all' in your config file.

**Comment by huyang271** [comment]
> check if you set framework object to 'all' in your config file.

 I'm using **quasar-umd (not quasar-cli)** v0.17.18 development, so where i can find it.

**Comment by metalsadman** [comment]
> > check if you set framework object to 'all' in your config file.
> 
> I'm using **quasar-umd (not quasar-cli)** v0.17.18 development, so where i can find it.

Haven't tried using it with UMD so better check the docs https://quasar-framework.org/guide/embedding-quasar.html#Quasar-Global-Object. it's the framework settings. unto the plugins portion you can set it to an array of quasar plugins that you'll only use. I assume it passes everything if you didn't specify something in it like `plugins: ['Notify']`.

**Comment by huyang271** [comment]
> > > check if you set framework object to 'all' in your config file.
> > 
> > 
> > I'm using **quasar-umd (not quasar-cli)** v0.17.18 development, so where i can find it.
> 
> Haven't tried using it with UMD so better check the docs https://quasar-framework.org/guide/embedding-quasar.html#Quasar-Global-Object. it's the framework settings. unto the components portion you can set it to an array of quasar component names that you'll only use. I assume it passes everything if you didn't specify something in it like `components: [''] // only specify quasar components that you will use`.

Yes, I have read [this doc](https://forum.quasar-framework.org/topic/2532/quasar-quasar-cli-v0-17-0-are-out-ssr-arrived) and try to resolve it by setting config object, but failed. I don't know what's wrong . If you can send out the code ，I'll be very grateful to you!

**Comment by metalsadman** [comment]
Quoted from your link:
The Quasar UMD version will define the following before including the Quasar script tag:
```
<script>
  window.quasarConfig = { 
   // your config here
     loadingBar: { //this takes QAjaxBar Props
         skipHijack: true // set this
     }
     .....
 }
 
</script>
// set the above before adding your quasar cdn
<script src="https://unpkg.com/quasar-framework@^0.17.0/dist/umd/quasar.mat.umd.min.js"></script>
```

**Comment by huyang271** [comment]
@metalsadman 
**I just tried it and it worked. Thank you very much, buddy.**
