### ISSUE TITLE
[Request] make QInfiniteScroll smart for not infinite lists

### ISSUE THREAD

**Issue by fansanelli** [quasarframework/quasar#2876]
Hello,
in my projects I'm repeating the same code around QInfiniteScroll (do a loop keeping in mind loaded elements, start and stop the scrolling, add the spinner...) and I'd love to avoid it for simple (but long) lists.
Is something possible to rethink this component (or do a variant) to load a static array using a template? I may need some event like "loaded" or "done" and be able to change the number of elements to load on "loadmore" (but could be enough a sane default)...

Many thanks
Cheers,
Francesco

**Comment by JoshEvanJohnson** [comment]
Create a component MyInfiniteScroll which includes infinite scroll within its template. This will give you the ability to pass all the props you have as "default" and include the props you want to change.

If you're including .env you could set those defaults in MyInfiniteScroll with that for quick adjustment later.

**Comment by louisameline** [comment]
+1
True that this component could be improved to support out of the box a predefined number of items and the number of items per batch loaded.
I could make a PR for that maybe.

**Comment by rstoenescu** [comment]
Hi,

You're in full control over your content (aka "predefined number of items") and how many items you load per batch (aka your handler) and when you configure QInfiniteScroll to work or halt. This is not a problem with Quasar but with your usage of QInfiniteScroll.

**Comment by louisameline** [comment]
I think you miss the point. We can already achieve what we want yes by writing our own code, but the component could be smarter and ask us to write less code for the same result. It would be nice to be able to just provide a finite array and a number of batch elements and boom, it would work. No custom code.

**Comment by rstoenescu** [comment]
Then you can use the power of Vue components. Make a wrapper over QInfiniteScroll and you're done. You don't need to repeat code over and over again ;)
