### ISSUE TITLE
QSelect go to option

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2877]
Hello!

Native select element has a very important feature when you can go to the option by pressing the first letter of it on the keyboard.

Example: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
1) Click on the select
2) Press "A" to go to "Audi"
3) Press Enter. "Audi" is selected

I think it is very important for QSelect to support this.

Thanks!

**Comment by jean-moldovan** [comment]
@pdanpdan I suggest we add this to the roadmap of the new v1.0

**Comment by smakinson** [comment]
One other thing I recently noticed that is somewhat related to this issue, when a QSelect has a value and I click it to open the auto complete list, it should probably highlight the choice that matches its current value. I realized this as I was verifying an old webpage that had a standard select and was able to just keep using the down arrow and for QSelect it was not an option.

**Comment by pdanpdan** [comment]
This is possible now in v1.1.0 using `scrollTo (index)`.
