### ISSUE TITLE
BackButton does not work?

### ISSUE THREAD

**Issue by mMarcos208** [quasarframework/quasar#2878]
### Software version

Quasar: 0.17.11
OS: Windows 10
Node: v10.14.2
NPM: 6.5.0
Android: Oreo
Any other software related to your bug:

### JsFiddle

```
mounted () {
    document.addEventListener('deviceready', this.deviceReady, false)
}
onBackKeyDown: function () {
      console.log('botaoVoltar')
      this.fecharModal()
      console.log('botaoVoltar')
 },
 deviceReady: function () {
      console.log('adicionandoListener de voltar')
      document.addEventListener('backbutton', this.onBackKeyDown, false)
      console.log('adicionandoListener de voltar2')
 }
```
`console.log('adicionandoListener de voltar')` is displayed on the screen.
`console.log('botaoVoltar')` not work.

How to register a linester for the back button?

**Comment by metalsadman** [comment]
https://quasar-framework.org/components/handling-back-button.html

**Comment by mqdev** [comment]
First, check if you have this on your config;
`cordova: {
        backButtonExit: true/false
      }`
Then on the framework directives:
`framework: {
  directives: ['GoBack']
}`

Then attach the directive `v-go-back=" '/' "` to the component that do the same thing. Like on your code, the button to close the modal. Change the `'/'` for the close modal function.
