### ISSUE TITLE
the layout-content covered by the layout-header when the content has scroll in some mobile browser

### ISSUE THREAD

**Issue by ceau** [quasarframework/quasar#288]
Hello Everyone.
I have a problem with the layout component in my app :
the layout-content is covered by the layout-header when the content has scrollbar in ios 9 safari and android chrome 40, but it works in ios 10 and chrome 50+.
![ios](https://cloud.githubusercontent.com/assets/7630878/21534940/6bba82fc-cda9-11e6-9ed7-a8842bfb50c6.png)
![android](https://cloud.githubusercontent.com/assets/7630878/21534943/8e4c50c0-cda9-11e6-92c4-32ffbc0a2c41.png)
Does anyone have the same problem ?

**Comment by rstoenescu** [comment]
Yes, this is a CSS flexbox related bug in older browsers. Will look for a workaround.
