### ISSUE TITLE
QTree lazy note is not loaded and expanded upon click when selected is synced

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#2880]
### Software version
Quasar v0.17.18 (see JSFiddle)

### JsFiddle

https://jsfiddle.net/tomers/7gu065yg/240/

### What did you get as the error?
When clicking a tree node that has `lazy: true` property, nothing happens in case `selected.sync` is specified. If `selected.sync` is not specified, the behavior is normal.

### What were you expecting?
When clicking a tree node that has `lazy: true` property, it suppose to lazy-load and expand the children that are the result of the lazy loading. This should happen regardless of whether `selected.sync` is specified

### What steps did you take, to get the error?
Click a tree node that has `lazy: true` property set.

**Comment by tomers** [comment]
I think that `selected` property should have a watch, which calls `__onExpandClick` on the selected node.

**Comment by pdanpdan** [comment]
This is normal and expected - clicking on a node when that node can be selected should select deselect it, not collapse/uncollapse children. There is the arrow in front to do this.
