### ISSUE TITLE
[BUG] Cordova Touch Failing Most of Times

### ISSUE THREAD

**Issue by Hamdan85** [quasarframework/quasar#2883]
### What did you get as the error?
When I run my app in browser, everything works fine, but when I do in a device (cordova) the navigation is erratic.. sometimes it does trigger events (like drawer toggle or drawer swipe) and most of the times it doesnt. I tought it was a UI problems (that the button was too small - default q-btn size in toolbar) but enlarging it doesnt seems to help. 
It takes some time to load stuff too... 

### What were you expecting?

I was expecting that the performance would be at leas equal to the browser... 
Other swipe components like q-carousel seems to work fine... 
The problem seems to be exclusively the **drawer** and **navigation**.

### What steps did you take, to get the error?
Started the app in cordova and tried to open drawer through menu toggle (3 bars) or swipe right several times... 80% of the times it didnt worked.

Operating System                Darwin(18.2.0) - darwin/x64
NodeJs                          10.10.0

Global packages                 
  NPM                           6.5.0
  yarn                          Not installed
  quasar-cli                    0.17.22
  vue-cli                       2.9.6
  cordova                       8.1.2 (cordova-lib@8.1.1)

Important local packages        
  quasar-cli                    0.17.22 (Quasar Framework CLI)
  quasar-framework              0.17.18 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.25.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.10  (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.6.3   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

Using a Motorola X2 on Android 9

Thanks in advance.

**Comment by fansanelli** [comment]
Hi,
Smartphones aren't usually fast as desktops and you have to limit the number of draws in your app.
Btw, did your app works on the Android emulator? Other developers may not have your same phone so please share an example that triggers your problem on it.
I fear without it this issue will be closed and you will be addressed to discord.

**Comment by rstoenescu** [comment]
Hi,

What Android is this phone running?

**Comment by Hamdan85** [comment]
C'mon guys. I wrote it.
It happens navigating (Changing routes and with toggle menu in drawer). 

And I also said that it's running on a Motorola X2.

I installed fastclick and it seems to have improved, but needing this also seems odd.

**Comment by rstoenescu** [comment]
Maybe I wasn't clear with my question so I'll rephrase.
I was looking for more than Android 9. Like the full version. (9.x.y...)

**Comment by Hamdan85** [comment]
Android 9
PP 29.69-26
Last security path from November 1th

**Comment by mstaack** [comment]
@Hamdan85 please check settings->info which `exact` version of android you are using, as raz said ;)

**Comment by Hamdan85** [comment]
As I said, the version is PPW29.69-26.
That is what's written on my phone info.

I'm also available for a Hangouts in order to show you guys. What do you think about it?

**Comment by mstaack** [comment]
looks like 9.0 Pie

**Comment by Hamdan85** [comment]
Android 9 (Pie) API 28
This info is from android studio.

**Comment by rstoenescu** [comment]
We are currently on a high workload preparing v1.0. You'll have to wait until we can thoroughly investigate this issue. Sorry for any inconvenience.

**Comment by Hamdan85** [comment]
No inconvenience at all...just trying to help.
Thanks for the amazing work on the framework

**Comment by mesqueeb** [comment]
@Hamdan85 Can you try again with v1?

**Comment by Hamdan85** [comment]
Is it production ready @mesqueeb?
And I didn't manage to find and upgrade from existing project guide. Is it available?

**Comment by mesqueeb** [comment]
@Hamdan85 It's on a stable API now. If it's production ready or not I'll leave up to you to decide. 😉

The upgrade guide was just released and you can read it here:
https://v1.quasar-framework.org/start/upgrade-guide

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1 (production ready), which I recommend to upgrade to as soon as possible.

If your business requires this fix in 0.17, let me know. But just to paint the bigger picture: fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this otherwise it is very detrimental to Quasar to halt working on v1.

Thanks.
