### ISSUE TITLE
iOS PWA mode camera and audio doesn't works

### ISSUE THREAD

**Issue by iparrabb** [quasarframework/quasar#2884]
Hi,

PWA with iOS on Safari works fine but doesn't works fine accessing directly from the shortcut, any idea?
The problem appears with native features, camera, audio etc.

### Software version

Quasar Framework: 0.17.18
Quasar Cli: 0.17.22
OS: iOS
Node: 10.7.0
NPM: 6.1.0
iOS: 12.1

**Comment by rstoenescu** [comment]
Hi,

Isn't this an iOS issue instead of a Quasar bug?

**Comment by iparrabb** [comment]
Yeah, I'm sure, but I preferred to ask before here.
Thanks @rstoenescu

**Comment by bcnbit** [comment]
Hello 

The question is why from the HomeScreen shortcut the app does not have access to Camera and Mic, but It does not happen when opened from Safari? 

Is there any workaround that we can implement?

Regards,

**Comment by rstoenescu** [comment]
This is because Apple decided to use an old version of Safari when running PWAs, and NOT the Safari iOS installed on the mobile phone. Seems like that old version does not support Camera and Microphone, so there's no way around it, no matter what technology you use to build a PWA...
