### ISSUE TITLE
[Enhancement] Support for QButton slot in QButtonDropdown

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#2885]
### Software version

Quasar: Running Quasar v0.17.18

### JsFiddle

https://jsfiddle.net/tomers/7gu065yg/252/

### Enhancement
Today there is no way to get to QBtn's default slot from QBtnDropdown, so there is no way to customize it.
Adding a 'button' (or any other name) slot would be very helpful.

**Comment by rstoenescu** [comment]
Will be available in beta.21
