### ISSUE TITLE
left-menu-drawer transition missbehavior on opening on Android and iOS

### ISSUE THREAD

**Issue by carlesar** [quasarframework/quasar#2887]
### Software version

Quasar: 0.17.18
OS: Linux(4.9.0-8-amd64) - linux/x64
Node: v9.11.2
NPM: 5.6.0
Browsers: 
iOS: iphone 6/7
Android: 7

### JsFiddle
https://jsfiddle.net/aragonet/1Lnpghwy/

### What steps did you take, to get the error?
This issue only happens when launching the app on Android and iOS devices (with the versions specified above). On browser there is no missbehavior.

When the user unfolds the left menu, the animation is really slow and not even smooth. This effect makes a really bad impact to the final users. (I mean it is not just a little bit lagged transition)

Tried to rollback Quasar versions and the same happened with versions from 0.14 to 0.17. But, unexpectedly, this behavior does not occur with version 0.13, where the animation of the left menu is constant, smooth und nice.

### What solution did you find?
The transition that causes this missbehavior is _transition-generic_ so the solution I found was to modify the file _app.styl_ and add the following lines:
```
.q-layout-drawer.transition-generic {
  transition: none !important;
  -webkit-transition-property: none !important;
}
```

With this little change, the left menu opens perfectly on all the platforms.

Probably this is not the best way to solve this issue and I am sure I am not the only one that is dealing with it.

Hope you can fix it for the next versions. :smiley:

**Comment by rstoenescu** [comment]
Hi,

Thank you for the detailed explanation. I'm happy to announce that this has already been taken care of in v1.0 codebase.
