### ISSUE TITLE
Pune si tu $1 - $2 - $5 pe Patreon

### ISSUE THREAD

**Issue by acstan** [quasarframework/quasar#2888]
Pune si tu $1 - $2 - $5 pe Patreon

**Comment by jean-moldovan** [comment]
![screen shot 2018-12-20 at 10 34 00](https://user-images.githubusercontent.com/3635352/50270493-ccb0c400-0442-11e9-84a7-f6708901f1c7.png)

**Comment by rstoenescu** [comment]
Salut, voi adauga. Dar nimeni nu e impiedicat sa doneze chiar si $1 daca vrea (sunt cativa care fac asta).

Hi, I will. Note that people can donate $1 as it is now also (there are already people doing this).
