### ISSUE TITLE
Can't resolve 'quasar-framework'

### ISSUE THREAD

**Issue by darrenfei** [quasarframework/quasar#2889]
### Software version

Quasar: 0.15.17
OS: windows10
Node: 8.11.1
NPM: 5.6.0
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
import Quasar from 'quasar-framework'
Vue.use(Quasar, {
  theme: 'ios'
})
### What were you expecting?
How to import quasar?
### What steps did you take, to get the error?
npm install quasar-framework

**Comment by smolinari** [comment]
https://quasar-framework.org/guide/

Scott

**Comment by darrenfei** [comment]
Please help me with the picture below
![_15453080271553](https://user-images.githubusercontent.com/22699815/50284469-0d84f900-0494-11e9-98cb-77f30921f29a.png)
![_15453080383731](https://user-images.githubusercontent.com/22699815/50284472-0e1d8f80-0494-11e9-8124-61f6906ed0c2.png)
![_15453080483050](https://user-images.githubusercontent.com/22699815/50284473-0e1d8f80-0494-11e9-946d-62d2ac215820.png)

**Comment by metalsadman** [comment]
@darrenfei 
you can follow UMD installation here https://quasar-framework.org/guide/embedding-quasar.html
or get cdn resources from this site also https://cdnjs.com/libraries/quasar-framework.

one thing to note when using UMD is you can't use quasar component self closing tags.
so in your example, your q-input tag should have an open and closing tags ie: `<q-input ...></q-input>`.

**Comment by darrenfei** [comment]
After I imported all the links in https://quasar-framework.org/guide/embedding-quasar.html#Usage, it can noy work.
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-darren-test</title>
    
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet"
      type="text/css">

    
    <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">

    
    <link href="https://cdn.jsdelivr.net/npm/ionicons@^4.0.0/dist/css/ionicons.min.css" rel="stylesheet">

    
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@^2.0.0/css/materialdesignicons.min.css" rel="stylesheet">

    
    <link href="https://cdn.jsdelivr.net/npm/animate.css@^3.5.2/animate.min.css" rel="stylesheet">


    
    <link href="https://cdn.jsdelivr.net/npm/quasar-framework@0.15.15/dist/umd/quasar.mat.min.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div id="app"></div>
    
    <script src="https://cdn.jsdelivr.net/npm/quasar-framework@0.15.15/dist/umd/quasar.ie.polyfills.umd.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/vue@latest/dist/vue.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/quasar-framework@0.15.15/dist/umd/quasar.mat.umd.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/quasar-framework@0.15.15/dist/umd/i18n.pt-br.umd.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/quasar-framework@0.15.15/dist/umd/icons.fontawesome.umd.min.js"></script>

    <script src="/dist/build.js"></script>
    
    <script>
      // if using a Quasar language pack other than the default "en-us";
      // requires the language pack style tag from above
      Quasar.i18n.set(Quasar.i18n.ptBr) // notice camel-case "ptBr"

      // if you want Quasar components to use a specific icon library
      // other than the default Material Icons;
      // requires the icon set style tag from above
      Quasar.icons.set(Quasar.icons.fontawesome) // fontawesome is just an example

      /*
        Example kicking off the UI.
        Obviously, adapt this your specific needs.
       */
    </script>
  </body>
</html>
`
`<q-input
    v-model="input"
    >
    </q-input>
  </div>`
