### ISSUE TITLE
How to publish a npm package with Quasar?

### ISSUE THREAD

**Issue by darrenfei** [quasarframework/quasar#2892]
### Software version

Quasar: 0.15.15
OS: windows10
Node: 9.11.1
NPM: 5.6.0

### What did you get as the error?
I found that it is too hard to publish a npm package with vue-cli and quasar.
I tried some methods to import Quasar, and wrote some components, and I give up now.
### What were you expecting?
Would you please tell me how to publish a npm package with quasar? I want to use the qasar npm packages in my projects(without quasar), and open souce.
### What steps did you take, to get the error?
1. npm install quasar-framework
2. in main.js: 
    ~import 'quasar-framework/dist/quasar.ie.polyfills.js'
    ~import Quasar from 'quasar-framework/dist/quasar.ios.esm.js'
    in webpack.config.js:
    ~ `plugins: [
            new webpack.ProvidePlugin({
            Quasar: "quasar"
          })
         ]`

**Comment by smolinari** [comment]
Um, npm is for publishing libraries, not full applications, which is what Quasar allows you to do. You seem to have a complete misunderstanding of how to work with Quasar and to be honest, I have no idea where to start to get you going on the right track other than, to again, point you to the documentation. 

https://quasar-framework.org/guide/introduction-to-quasar.html

Scott

**Comment by darrenfei** [comment]
Thanks for your help. It's my fault.
