### ISSUE TITLE
[Request] inline-svg directive

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2894]
When working with SVG's  `<img src="~assets/example.svg" />` is the easiest way, but you cannot color the path of the SVG anymore.

Vue-cli has a plugin called [vue-svg-inline-loader](https://github.com/oliverfindl/vue-svg-inline-loader). It would be great if quasar could have this as well!

Then you can just do:
`<img svg-inline src="~assets/example.svg" />`

Which will change the img tag into an actual svg tag, which is much easier to work with!

**Comment by rstoenescu** [comment]
Hi,

It's not a vue-cli plugin. It's a webpack loader. So install the package and extend the webpack config as in their docs and you'll be able to use it.

**Comment by mesqueeb** [comment]
@rstoenescu 
I tried adding these lines under the first rule push in Quasar:

```
cfg.module.rules.push({
          test: /\.vue$/,
          use: [
            {
              loader: 'vue-loader',
              options: { /* ... */ }
            },
            {
              loader: 'vue-svg-inline-loader',
              options: { /* ... */ }
            }
          ]
        })
```
but it breaks the app. Says "render function not defined"

Any advice much appreciated!

**Comment by mesqueeb** [comment]
@rstoenescu 
It works if I delete the `vue-loader` part and only leave the `'vue-svg-inline-loader'` part!

The only problem that remains is, **I cannot use `~assets/` anymore.** I need to write out a hard-coded path depending on the vue file's location!

Is there any workaround for this you can foresee?
Thanks so much!

**Comment by mesqueeb** [comment]
Related [Loading SVG from Alias Path not working](https://github.com/oliverfindl/vue-svg-inline-loader/issues/4#issuecomment-452991108)

**Comment by ThiefSoul** [comment]
I know that it's a closed thread but maybe it will help somebody.
I added `exclude` like you can see below and it fixed my problems with aliases/paths/imports/whatever.

This is the only change I made in `quasar.conf.js`
```
cfg.module.rules.push({
    test: /\.vue$/,
    loader: 'vue-svg-inline-loader',
    exclude: /(node_modules|quasar)/
})
```

**Comment by mesqueeb** [comment]
I was able to get it to work with this in my quasar.conf on quasar pre v1
```js
cfg.module.rules.push({
          test: /\.vue$/,
          use: [
            {
              loader: 'vue-svg-inline-loader',
              options: {svgo: false}
            }
          ]
        })
```
