### ISSUE TITLE
Does quasar support fixed columns？

### ISSUE THREAD

**Issue by huyang271** [quasarframework/quasar#2913]
Quasar: v0.16.x - UMD
OS: win10

### What were you expecting?
Fixed columns are a common scenario, but I don’t know how to use quasar to implement it. Has anybody achieved it yet?

Thanks!!!

**Comment by rstoenescu** [comment]
Hi,

Please use our [Discord](http://chat.quasar-framework.org) or [Forum](https://forum.quasar-framework.org) for questions.

Also, can you be more specific? Are you referring to https://quasar-framework.org/components/flex-css.html ?
