### ISSUE TITLE
[Suggestion] Make QInfiniteScroll work in both directions. 

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#2919]
Hi,

For a standard list, where there is a beginning and some end, but where the data set is not necessarily too large, QInfiniteScroll works great to show the data in chunks upon scrolling down or swiping up. 

There are use cases however, where it is interesting to start in the middle of the data set to show a certain item of the data. This means, the user might also want to scroll up, to see more of the data. Currently to do this, all the data would need to be loaded until that certain item and depending on where that certain item is and how big the data set is, loading all the data can become unwieldy.

This suggestion is to be able to load a set amount of data from the middle of the data set and be able to scroll in both directions to load more data. 

I have no idea how to get this done, or if making QInifiniteScroll have this capability is the right direction to take in the first place, but I've seen this need more than a couple of times, especially with the QChat component. An example of how it would work best can be seen in the Discord channels. 

Thanks for any consideration in advance.

Scott

**Comment by rstoenescu** [comment]
This has been implemented in recent betas.
