### ISSUE TITLE
Option for Modal to appear from edges

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#293]
Hi,
would be nice to have this kind of modal. You can take a look at http://materializecss.com/modals.html
It is nice and user friendly. I suppose it can be done just with css and options with current modal, so no new additional modal would be necessary?
What you think?

**Comment by rstoenescu** [comment]
Yep. The Action Sheet component itself uses a Modal that is configured in a specific way. It probably wouldn't hurt to just make a property or something to tell the Modal to act like an action sheet. Just to ease the configuration so you won't have to remember specific CSS for it. So will do.

**Comment by rstoenescu** [comment]
A new "position" prop was added ('top', 'left', 'right', 'bottom'). Available in next Quasar version after v0.12 or in Quasar edge.
