### ISSUE TITLE
[Feature Request] Scroll Area: be able to click on "page down/up" regions

### ISSUE THREAD

**Issue by abeltodev** [quasarframework/quasar#2932]
would be very useful :)

**Comment by rstoenescu** [comment]
Hi,

I believe your previous ticket includes this, so gonna close this one.
https://github.com/quasarframework/quasar/issues/2931

**Comment by abeltodev** [comment]
Well, actually is not the same. The feature I'm talking about is to be able to click on "page up/down regions". Please, see the picture attached (is not so easy to define :)

![dropdown parts](https://user-images.githubusercontent.com/7636148/50538967-ebb50180-0b78-11e9-8545-4f2ac803d44e.gif)

Thanks for your work

**Comment by rstoenescu** [comment]
I thought you were referring to page up/down keys :)

**Comment by pdanpdan** [comment]
Link this one to follow in #5699

**Comment by pdanpdan** [comment]
This was added in v1.5.0 (except top and bottom arrows)
