### ISSUE TITLE
qlayout header foot non fixed in ios

### ISSUE THREAD

**Issue by zwmyxzs** [quasarframework/quasar#2944]
### Software version

Quasar:0.17.18
OS:Mac
Node:10.14.2
NPM:6.4.1
Browsers:Chrome 71.0.3578.98
iOS:12
Android:n/a

The q-layout-header and q-layout-footer is non fixed in ios. When you drag down, the header will also go down. When you drag up, the footer will also go up.

The android version is fine.

**Comment by rstoenescu** [comment]
Jsfiddle/Codepen pls, as requested.

**Comment by zwmyxzs** [comment]
Jsfiddle/Codepen very slow.

For example, Quasar-Play app have the same problem. We can use the IOS App Store to download Quasar-Play app,  go to Quasar Showcase--Drawer Panels page, then you can drag down or drag up page, the problem can be repeated.


drag up
![img_20190103_104052](https://user-images.githubusercontent.com/11973406/50621913-2e455800-0f44-11e9-889f-30189c9bc2aa.jpg)

drag down
![img_20190103_104038](https://user-images.githubusercontent.com/11973406/50621916-3604fc80-0f44-11e9-867f-9b7137fe2683.jpg)

**Comment by rstoenescu** [comment]
There is no **official** Quasar Play in App Store. If it exists, it's not managed by Quasar and it definitely uses a very old Quasar Framework version.

So please write a jsfiddle/codepen as requested in the issue template.

**Comment by zwmyxzs** [comment]
### JsFiddle
https://codepen.io/zwmyxzs/pen/oJpOmr

But running is ok, because that is a web page. If you're running in a Mac emulator or an IOS app, to find the problem.

**Comment by mesqueeb** [comment]
@zwmyxzs Are you talking about this?

See screenshot from my Cordova iOS app below:

![img_1233](https://user-images.githubusercontent.com/3253920/51009893-42690500-1595-11e9-9afa-cfd836d11e31.jpg)


If this is the case it's probably out of Quasar Framework's control, as it's the way UIWebKit works.
I haven't tried with WKWebKit yet (there's a cordova plugin for that), but if I do I'll let you know how it goes.

But really, there's no fuss, as when you scroll up, it will be fixed. It only gets pulled down like that if you try to pull the screen down even though you're at the top. So there's no big deal.

**Comment by zwmyxzs** [comment]
@mesqueeb 
Thank you very much for your help, problem solved.

Thank you.
