### ISSUE TITLE
Add "tablet" to platform detection

### ISSUE THREAD

**Issue by pshendry** [quasarframework/quasar#295]
A common use case for mobile UIs is to display content differently on large screens (e.g. tablets) vs smaller screens; for example, a tabbed interface on a phone might be shown as a 2- or 3-column view on a tablet.

As far as I can tell there's no such platform distinction for mobile devices right now. The suggestion would be to pick a reasonable screen size threshold at which a mobile platform is also considered a tablet.

**Comment by rstoenescu** [comment]
Will do. Thanks for the suggestion!

**Comment by rstoenescu** [comment]
Adding "Platform.is.tablet" is really hard and adds a lot of overhead, so dropping this.
Check http://quasar-framework.org/api/css-visibility.html#Window-Width-Related instead. `medium` would be tablet.
