### ISSUE TITLE
[Bug] i18n.set does not change locale

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#2950]
### Software version

Operating System         	Linux(4.18.16-arch1-1-ARCH) - linux/x64
NodeJs                   	11.1.0

Global packages          	
  NPM                    	6.4.1
  yarn                   	1.12.3
  quasar-cli             	0.17.22
  vue-cli                	2.9.6
  cordova                	Not installed

### JsFiddle
https://jsfiddle.net/stefanvh/s4pyxcaw/2/

### What did you get as the error?
getLocale() returns the initially set locale (i.e. the locale was not changed by i18n.set())

### What were you expecting?
getLocale() should return the locale which was set with i18n.set()

**Comment by rstoenescu** [comment]
`getLocale()` returns the client browser locale, not the Quasar i18n set one.
For determining the Quasar i18n currently set, you have `$q.i18n.name`

**Comment by stefanvanherwijnen** [comment]
I couldn't get it to work in my project, and it didn't seem to work in UMD either so I figured it was a bug. Thanks for the help.

**Comment by rstoenescu** [comment]
https://quasar-framework.org/components/internationalization.html
