### ISSUE TITLE
will you update sample dev project to v0.15+?

### ISSUE THREAD

**Issue by sonygod** [quasarframework/quasar#2954]
https://github.com/quasarframework/quasar/tree/dev/quasar

current this project is old version and no docs how to config something from 

https://quasar-framework.org/guide/app-quasar.conf.js.html

will you update sample dev project to v0.15+? 

or how to update to use quasar-cli?

For Quasar pre v0.15 projects, npm uninstall -g quasar-cli; npm i -g quasar-cli@0.6.5?

quasar/quasar# quasar dev
 app:paths ⚠️  Error. This command must be executed inside a Quasar v0.15+ project folder. +0ms
 app:paths For Quasar pre v0.15 projects, npm uninstall -g quasar-cli; npm i -g quasar-cli@0.6.5 +6ms

**Comment by metalsadman** [comment]
dev is for a wip for quasar version 1 i believe. the upgrade guide from pre v0.15 in the docs https://quasar-framework.org/guide/quasar-upgrade-guide.html#Upgrading-pre-v0-15-to-Quasar-v0-15.
