### ISSUE TITLE
Add cordova safe-areas to modals (like action-sheet)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2956]
Part of components that utilise css class `.fullscreen` or any `100vh` property have problem in Cordova with the safe areas.
Eg. the bottom of [Action sheet](https://quasar-framework.org/components/action-sheet.html) is too low on iPhone X because of its [reliance on `.fullscreen`](https://github.com/quasarframework/quasar/blob/7186dab1c8dc914c64f97195c1f5fa110acb0547/quasar/src/css/core/positioning.styl#L66).

Adding margin to `.fullscreen.modal .modal-content` does the trick:
```css
margin-bottom constant(safe-area-inset-bottom)
margin-bottom env(safe-area-inset-bottom)
```
But would need some extra testing on other components that rely on this.

**Comment by zabaat** [comment]
+1

**Comment by rstoenescu** [comment]
This has been taken care of in v1. Closing.
