### ISSUE TITLE
Prevent scroll on modal backdrop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2957]
I feel like the backdrop of a modal should still be tappable, but not be scrollable.
It's more natural to have the page behind it unscrollable as long as the modal is open.

This can be achieved by adding this code:
```js
// each time a modal is shown / opened
const backdropElement = // target the backdrop
backdropElement.addEventListener('touchmove', e => { e.preventDefault() }, false)
```

Would be a nice addition to the great Quasar Framework

**Comment by masterzorx** [comment]
suggest https://github.com/willmcpo/body-scroll-lock

**Comment by mesqueeb** [comment]
I'm not sure [7.6kb, 300 lines](https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js) just for scroll lock on the backdrop modal seems a little overkill. We wanna keep Quasar as light as possible, and my two lines work on cordova and browsers as well so should be enough in my opinion.

**Comment by rstoenescu** [comment]
This shouldn't be a problem for v1.
