### ISSUE TITLE
QTable 'Records Per Page' not set back on server error

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#2959]
### Software version

$ quasar info

Operating System                Darwin(17.7.0) - darwin/x64
NodeJs                          11.5.0

Global packages                 
  NPM                           6.4.1
  yarn                          1.12.3
  quasar-cli                    0.17.23
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages        
  quasar-cli                    0.17.23 (Quasar Framework CLI)
  quasar-framework              0.17.19 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.25.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.14  (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.6.3   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### What did you get as the error?
Nothing.

### What were you expecting?
I expected 'Records Per Page' to set back to proper value

### What steps did you take, to get the error?
QTable with Server-side Pagination, I set 'Records Per Page' to 'All', then the server responded with error (there were too many records for it, so it failed).
I expected this combo-box to revert to its previous value. Instead, it is now set on 'All'.
I notice that the entries server-side pagination implementation is not promise based, thus server errors are not handled well by the UX. This is merely a single example.

**Comment by metalsadman** [comment]
shouldn't your server call be a promise base though and reset your per page in the catch?

**Comment by rstoenescu** [comment]
As @metalsadman said above.
