### ISSUE TITLE
Ability to hide header in Data Grid

### ISSUE THREAD

**Issue by mjawaids** [quasarframework/quasar#296]
There should be an option in Data Grid config to set the visibility of header. If set to false Data Grid shouldn't display the header.

**Comment by rstoenescu** [comment]
Will do.

**Comment by rstoenescu** [comment]
Are you referring to hiding the table header only or table header along with all toolbars above the table?

**Comment by mjawaids** [comment]
I was referring to hiding the table header only. I saw that you've done the changes in code. Have you released it as new version? Also, what's the difference between hasHeader and noHeader in your code? Shouldn't only one property be enough? Thanks for the changes by the way.
