### ISSUE TITLE
devserver shall be capable to open app not only in default system browser

### ISSUE THREAD

**Issue by jerome-mare** [quasarframework/quasar#2960]
## Issue to solve 

When using the quasar-cli to launch the dev server, it opens the operating system default browser.

## Feature requested

It will be interesting to be able to launch the browser of our choice with specific command line option. For example Google canary in incognito mode.

## Proposed technical solution

opn is able to handle that scenario : https://github.com/sindresorhus/opn#readme
`opn('https://localhost:8080/', {app: ['google canary', '--incognito']});`

With quasar-cli, it will be possible to enhance the source file `dev-server.js`to pass the option to opn

```
function openBrowser (url, options = {} ) {
  const opn = require('opn')
  opn(url, options)
}

// ....

 if (cfg.devServer.open && ['spa', 'pwa'].includes(cfg.ctx.modeName)) {
          const browser = cfg.devServer.browser || {} 
          openBrowser(cfg.build.APP_URL, browser)
  }
```

In this case, with the option `browser` of the devServer section, we can define the target browser, for example : `{app: ['google canary', '--incognito']}`

**Comment by rstoenescu** [comment]
Will do.

**Comment by rstoenescu** [comment]
Would you mind making a PR for this with your solution?

**Comment by jerome-mare** [comment]
Yes i can.
I can modify quasar-cli codebase and send a PR. May i also PR the documentation in quasar repository ?

**Comment by jerome-mare** [comment]
I'm working on it but it don't seems to work the opn call in dev-server.js (function openBrowser - line 11) seems to be never called.

Will I do a PR on documentation website too to explain the option ?

**Comment by rstoenescu** [comment]
Sorry it took so long. Lots going on. Available in beta.10.

Using `open` prop to open with a specific browser and not with the default browser of your OS:

```
// quasar.conf.js

devServer: {
  open: 'firefox'
}
```

**Comment by jerome-mare** [comment]
Sorry, the pull request is here https://github.com/quasarframework/quasar-cli/pull/220.
The issue was related with the quasar-cli and not quasar, my mistake

**Comment by rstoenescu** [comment]
Hi,

Can you instead port https://github.com/quasarframework/quasar/commit/4636d3a161d28efd4f4d18b28db243f22b39e450 and test it out on legacy 0.17 quasar-cli?

Currently dealing with 1.0 stuff. Sorry for the inconvenience.

**Comment by rstoenescu** [comment]
Assuming you want it for 0.17?

**Comment by jerome-mare** [comment]
Hi,
I don't need it for 0.17. I can wait for the v1 stable.
But there was a feature in my pull request that is not in your commit.
The feature is to pass command line parameters to the target browser.
Can you integrate this too in quasar-cli v1 ?

I'm testing quasar v1 in a new side project for a week. It's a great work ! thank you !

**Comment by rstoenescu** [comment]
Sure it is.

devServer: {
  open: 'firefox'
}

or open: { .... }

**Comment by jerome-mare** [comment]
Sorry, i cannot make it work (cf. screenshoot)

<img width="977" alt="Capture d’écran 2019-03-11 à 14 29 19" src="https://user-images.githubusercontent.com/3762970/54127514-3de09180-440a-11e9-88b2-5029d575fd46.png">

I remember that it was not possible to pass an object to open property and i finally use the property "browser" of the "devServer" section. I think that webpack-dev-server cannot pass object to opn component,but i don't really remember why. All is in my pull request. If you want i can create a new PR on quasar v1

**Comment by rstoenescu** [comment]
@jerome-mare `open: ['google chrome']` --> no need to wrap it with { app: [....] }
