### ISSUE TITLE
Machine Learning application based on TensorFlow library on Quasar Framework

### ISSUE THREAD

**Issue by maxprog** [quasarframework/quasar#2961]
### Software version

Quasar: 0.17.23
OS: Mac Os X
Node: v8.9.4
NPM: 6.5.0
Browsers: Yes

Any other software related to your bug:

### What did you get as the error?
Currently I work on Machine Learning application on Quasar Framework. I made sample on vue and works perfect - You can see my solution on youtube - ( https://www.youtube.com/watch?v=LH3ECvJcPgI )  and blog: ( http://maxprog.net.pl/artifficial-intelligence-in-practice/vue-2-machine-learning-artificial-intelligence-in-practice/ ).
 The same solution I’d like make in Quasar also as mobile app. But after implementation I see that Quasar has a problem with standard tensoflow library, that works perfect on vue, react and angular. 
Problem is with code (described on https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd ):
import "@tensorflow/tfjs";
import * as cocoSsd from "@tensorflow-models/coco-ssd”;
const img = document.getElementById('img');
  // Load the model.
  cocoSsd.load().then(model => {
    // detect objects in the image.
    model.detect(img).then(predictions => {
      console.log('Predictions: ', predictions);
    });
  });

### What were you expecting?

Because of that code works perfect on vue, react and angular, so I'm thinking problem is in architecture quasar framework

### What steps did you take, to get the error?

Just only insert this code:
import "@tensorflow/tfjs";
import * as cocoSsd from "@tensorflow-models/coco-ssd”;
const img = document.getElementById('img');
  // Load the model.
  cocoSsd.load().then(model => {
    // detect objects in the image.
    model.detect(img).then(predictions => {
      console.log('Predictions: ', predictions);
    });
  });
<img width="2555" alt="screenshot 2019-01-08 at 18 22 47" src="https://user-images.githubusercontent.com/13249768/50884021-047bad80-13ea-11e9-9fde-33f4b2bdba7f.png">
[ml-quasar.zip](https://github.com/quasarframework/quasar/files/2739790/ml-quasar.zip)

[App.vue.txt](https://github.com/quasarframework/quasar/files/2739792/App.vue.txt)

**Comment by maxprog** [comment]
I placed before  invalid vue file with source code. Here is correct version 
[Index.vue.txt](https://github.com/quasarframework/quasar/files/2739805/Index.vue.txt)

**Comment by nothingismagick** [comment]
Not sure why you are doing this:
`import "@tensorflow/tfjs";` => that is not part of the documentation you linked to.
Also, I would try with async / await instead of using .then() 

I have a hard time believing this is not working in quasar, but without a stacktrace there's no way to know what is going on here.

**Comment by rstoenescu** [comment]
Please reopen with proof of Quasar "malfunctioning".
