### ISSUE TITLE
openURL broken on Cordova with WkWebView

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2962]
Quasar's openURL doesn't work when installing [WkWebView](https://github.com/apache/cordova-plugin-wkwebview-engine).

Steps to reproduce is just init quasar, add cordova, add platform ios, don't forget to add a build.json to be able to launch with latest xcode.

Then install WkWebView, and the default app won't be able to open the url's in the Quasar side bar anymore.

required build.json
```
{
  "ios": {
    "debug": {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
    },
    "release": {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
    }
  }
 }
```

**Comment by rstoenescu** [comment]
Posting from Discord where you also mentioned it (for others to see my reasoining):

```
have you installed the cordova plugin for this?
there's one specifically for opening URLs
Quasar tries to see if it's installed, and if not, it defaults to the JS way of win.open
```

**Comment by mesqueeb** [comment]
Have made sure I had the 4 lines above in the config.xml.

Any old document reference at Cordova to `window.open` now points to the [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/index.html) page. So I am going to try and install this one.

Otherwise I found this plugin, but it's not an official one by apache: [cordova-plugin-open-scheme-url](https://github.com/thomaslindstrom/cordova-plugin-open-scheme-url#readme). Thought I'd just post it here for now.

Related [open bug](https://github.com/apache/cordova-plugin-wkwebview-engine/issues/72) at WkWebView plugin.

**Comment by mesqueeb** [comment]
Apparently it's a known issue in the [Apache Cordova issue tracker](https://issues.apache.org/jira/browse/CB-12228?jql=project%20%3D%20CB%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20wkwebview-known-issues) without a fix for now.

Using [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/index.html) works alright!

**Comment by danicholls** [comment]
This would be good to include in the util docs. It seems to say Quasar handles it all for you, but’s not really so if you lack the plugin, though the actual functionality makes sense.

**Comment by mesqueeb** [comment]
@danicholls the quasar docs have an “edit” button. Would greatly appreciate your suggested changes.
