### ISSUE TITLE
how to set the small size small than size='xs' on button?

### ISSUE THREAD

**Issue by sonygod** [quasarframework/quasar#2964]
how to set the small size small than xs on button?

 <q-btn  class="on-left"  size="xs" icon="remove"/>

I want to set size small than xs, but not work 

size="1px"? not work.

**Comment by BboyAkers** [comment]
you'll probably have to customize that yourself inside the css/app.styl file and then apply a custom class to that element.

**Comment by rstoenescu** [comment]
Hi,

The `size` prop (works with String defining CSS units including unit name!) refers to the size of the label/icon (and button gets a padding relative to that size also). If you want to override the padding too then just set that on the button through CSS also (hint: you could use  "q-pa-none" CSS helper class to set no padding).

**Comment by rstoenescu** [comment]
Hi,

The `size` prop (which DOES work with String defining CSS unit and unit name!) refers to the size of label/icon within, but the button always has a padding relative to label/icon size. You can override that padding too through CSS (hint: you can use `q-pa-none` etc CSS helper classes to remove/configure any padding, or write a CSS with your specific padding).

**Comment by rstoenescu** [comment]
Hi,

The `size` prop (which DOES work with String defining CSS unit and unit name!) refers to the size of label/icon within, but the button always has a padding relative to label/icon size. You can override that padding too through CSS (hint: you can use `q-pa-none` etc CSS helper classes to remove/configure any padding, or write a CSS with your specific padding).
