### ISSUE TITLE
v-ripple directive does not work on some quasar elements (q-checkbox, q-btn, etc)

### ISSUE THREAD

**Issue by trsiddiqui** [quasarframework/quasar#2965]
### Software Version
Operating System                        Windows_NT(10.0.17134) - win32/x64
NodeJs                                  8.9.4

Global packages
  NPM                                   5.6.0
  yarn                                  1.12.3
  quasar-cli                            0.17.22
  vue-cli                               2.9.6
  cordova                               Not installed

Important local packages
  quasar-cli                            0.17.22 (Quasar Framework CLI)
  quasar-framework                      0.17.18 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                         2.0.9   (Quasar Framework fonts, icons and animations)
  vue                                   2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                            3.0.1   (Official router for Vue.js 2)
  vuex                                  3.0.1   (state management for Vue.js)
  electron                              Not installed
  electron-packager                     Not installed
  electron-builder                      Not installed
  @babel/core                           7.0.0-beta.54   (Babel compiler core.)

Any other software related to your bug:
Chrome, IE

### JsFiddle
https://jsfiddle.net/uftp1g9m/1/

### What did you get as the error?
v-ripple directive did not work as expected on button and checkbox (See attached jsfiddle)

### What were you expecting?
The element should not ripple when v-ripple is disabled on it

### What steps did you take, to get the error?
Used v-ripple directive on different elements.

**Comment by rstoenescu** [comment]
Hi,

QBtn and QCheckbox already have a v-ripple attached to them by default. If you attach it again that doesn't override the inner ripple. In v0.17 this is not possible, but fortunately v1.0 (to be released very soon) has this ability to configure underlying ripple.

**Comment by rstoenescu** [comment]
Hi,

QBtn and QCheckbox already have a v-ripple attached to them by default. If you attach it again that doesn't override the inner ripple. In v0.17 this is not possible, but fortunately v1.0 (to be released very soon) has this ability to configure underlying ripple.
