### ISSUE TITLE
[Feature Request] Floating/Fixed DataTable Header When Header out of View on scroll

### ISSUE THREAD

**Issue by trsiddiqui** [quasarframework/quasar#2966]
Like in [DataTables ](https://datatables.net/extensions/fixedheader/examples/options/show-hide.html) implementation (select 100 records and scroll down).

**Comment by JoshEvanJohnson** [comment]
Could also use a Fixed footer for easy full page listings when the pagination footer is to far down the page to utilize.

**Comment by rstoenescu** [comment]
Hi,

This can be achieved in app devland by using the CSS [position: sticky](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning). Right now we are working on v1.0 documentation so really really busy (otherwise would have popped an example), but pls do also Google for position sticky examples to understand how it works and how powerful it is. Unfortunately, this feature is supported only by the modern browsers.

**Comment by mohanzeal** [comment]
This codepen link [sticky table header](https://codepen.io/mohanzeal/pen/eoQqGQ) can help you

**Comment by rstoenescu** [comment]
@mohanzeal would you be so kind to add this example on QTable docs? I've been meaning to write one for a long time.

**Comment by mohanzeal** [comment]
I will be very much glad to contribute to this awesome framework @rstoenescu.

Could you please guide me on how to pull the docs repo.. so that I can raise a pull request.

Thanks.

**Comment by nothingismagick** [comment]
1. Fork this repo.
2. Go to the docs folder
3. Create a branch like `feat/docs/task`
4. Make your changes
5. Set up a remote tracking branch at quasarframework/quasar, I call it
upstream
6. Checkout dev branch
7. `git fetch upstream`
8. `git merge upstream dev`
9. Checkout your branch
10. Merge dev into your branch
11. Push to your fork
11. Make a PR to upstream dev branch

**Comment by mohanzeal** [comment]
thanks @nothingismagick. Will raise a PR once I complete it.

**Comment by nothingismagick** [comment]
sry - made a typo in point 8: it should read:
```
8. `git merge upstream/dev`
```

**Comment by mohanzeal** [comment]
Hi Team,

I have raised a PR, please merge it #4039

**Comment by rstoenescu** [comment]
@mohanzeal thx. merged it and made some additions. @nothingismagick can you (or assign someone from our team) show him how to run the docs and make additions to pages pls? Thanks.

**Comment by nothingismagick** [comment]
Sure, care to join us on the discord server? I can help you understand
exactly how the docs work better than in the comments of an issue. :)
