### ISSUE TITLE
q-tabs dynamically loaded from JSON, or using v-show require window resize to show scrolling arrows in desktop browsers

### ISSUE THREAD

**Issue by SMen1** [quasarframework/quasar#2974]
The issue occurs when dynamically loading data for the q-tabs, or when using a v-show or v-if condition on q-tabs. When dynamically loading it is resolved by over-writing data pre-loaded with say a white background switching to the desired color when loaded, or manually resizing the browser window.

Tested on Chrome, Firefox and Edge. Quasar v 17.* to 17.9

Example code:

Offices are loaded and used to control data displayed for each office. 

`<q-tabs color="dark" underline-color="amber-10" align="justify" v-model="officeId">
    <q-tab
    v-for="offices in offices"
    :key="offices.officeId"
    slot="title"
    :name="offices.officeId"
    @click="fetchJobs(offices.officeId)">{{offices.officeName}}</q-tab>
  </q-tabs>`

As a side issue when using in UMD mode with cdn, the underline-color does not over-ride the default.
This happens whether or not using q-tab-pane.

Hopefully I have not missed something obvious, but I am pretty sure this is an issue. It was also raised by someone on discord but no solution found / given as far as I can tell.

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Hi,

This has been taken care of in v1. Closing.
