### ISSUE TITLE
PROPOSAL - Circle percentage component

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#298]
I think we definitely missing this component:
http://www.cssscript.com/wp-content/uploads/2015/04/Pure-CSS-Circular-Percentage-Bar.jpg
http://www.jqueryscript.net/images/Minimalist-Graphical-Progress-Indicator-with-jQuery-Canvas-circleGraphic.jpg
http://www.jqueryscript.net/images/Create-Percentage-Circles-with-jQuery-CSS3-percircle-js.jpg

**Comment by rstoenescu** [comment]
You mean http://quasar-framework.org/components/knob.html ?

**Comment by murbanowicz** [comment]
I thought I've seen it some day.. Just couldn't find it really long so I thought I am wrong.. Sorry!

**Comment by murbanowicz** [comment]
but.. could you add possibility to use it just for presentation (so disabled but not with light colors?

**Comment by rstoenescu** [comment]
Sure!

**Comment by rstoenescu** [comment]
Done. Added "readonly" prop. Available in future v0.12.1 and Quasar edge.
