### ISSUE TITLE
[Request] Data Table - Allow add event to rows

### ISSUE THREAD

**Issue by eliashdezr** [quasarframework/quasar#299]
Something in the configuration object that could allow us to add an event to the row when is tapped/clicked.

**Comment by rstoenescu** [comment]
Would the single selection mode help in your situation?

**Comment by eliashdezr** [comment]
@rstoenescu 

I don't think so since single selection adds an extra column and doesn't work in the entire row.

**Comment by eliashdezr** [comment]
@rstoenescu

In the meantime, is there a way to create a custom cell that can listen a click event? I tried something like this but doesn't register the event:

```
            format (value) {
              return `<span v-on:click="doSomething(value)">${value}</a>`
            }
```

**Comment by rstoenescu** [comment]
@eliashdezr `format()` should return a string indeed but that string is no compiled with Vue. Instead, see "Rendering with Component" on http://quasar-framework.org/components/data-table.html#Formatting-a-Cell

**Comment by honzo0481** [comment]
i have a few use cases for applying v-on to data-table rows too. not only click but drag and drop events as well.

**Comment by rstoenescu** [comment]
Added `@rowclick` event which takes one parameter which is the selected row.
Available in future v0.14.

**Comment by KaisNeffati** [comment]
Hello there , could we have this `@rowclick` in version v0.13 !

**Comment by aprixon01112017** [comment]
@rowclick  - is this implemented? I don't find it in the docs. I find: https://quasar-framework.org/components/datatable.html#Alternative-custom-rows

**Comment by rstoenescu** [comment]
@aprixon01112017 use a row scoped slot and add whatever native events you need ;)

**Comment by kenng** [comment]
@rstoenescu I think this scenario is pretty common in data table. Example, lists the users in data table, when it is clicked, open a full user details. Rather than define the slot with no change in styling or for additional processing, emit an click event can really helpful, as it simplifying the workflow. Hope this can be re-considered again ;)
