### ISSUE TITLE
[v1] QToggle - keep-color not working without 'color' prop

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#2990]
code:
```vue
    <q-toggle keep-color v-model="value"/>
    <q-toggle color="green" keep-color v-model="value"/>
    <q-toggle color="yellow" keep-color v-model="value"/>
    <q-toggle color="red" keep-color readonly v-model="value"/>
```
output:
![image](https://user-images.githubusercontent.com/25121817/51205411-23a49e80-1906-11e9-948e-ce6b6c5737f8.png)

**Comment by panstromek** [comment]
similar thing happens when clicking on disabled toggle

![image](https://user-images.githubusercontent.com/25121817/51205717-d412a280-1906-11e9-8b6c-8166ee32c2d8.png)

**Comment by rstoenescu** [comment]
`keep-color` is supposed to be working along with a color. It's by design. It **keeps** a color :)

**Comment by panstromek** [comment]
hmm... ok .. it's not colorless by default though - it is blue (primary I guess)
