### ISSUE TITLE
Incorrect handling of an event on the mouse wheel inside the modal block (Firefox)

### ISSUE THREAD

**Issue by ajkyru** [quasarframework/quasar#2992]
### Software version
Quasar: 0.17.23
OS: Mac Os X / Windows 10
Node: v10.6.0
Yarn: 1.12.3
Browsers: Yes

Any other software related to your bug:
**The problem is reproducible only in Firefox**

### JsFiddle
https://jsfiddle.net/zapililkin/u8qya5b9/

### What did you get as the error?
The editor does not fire on the wheel event.
If the editor is inside a scrolling block, it will sometimes trigger, but the movement will only be in one direction until the content reaches the start/end.

### What were you expecting?
Scroll handling as in other browsers.

### What steps did you take, to get the error?
Try to scroll the mouse wheel on the block with the editor inside modal.

**Comment by rstoenescu** [comment]
Hi,

This has been taken care of in v1. Closing.
