### ISSUE TITLE
[v1] QInput with type=number label will not float with default value

### ISSUE THREAD

**Issue by nklayman** [quasarframework/quasar#2995]
![image](https://user-images.githubusercontent.com/12448243/51212545-a3624700-18cd-11e9-8d05-80cba386fe39.png)

### Software version

Quasar:1.0.0-alpha.11
OS: Ubuntu 18.10
Node: 10.15.0
NPM: 5.10.0
Browsers: Chrome 71
Any other software related to your bug: On Quasar docs site

### JsFiddle

https://jsfiddle.net/noahklayman/jcavgfLs/

### What did you get as the error?
The label in the input is not floating

### What were you expecting?
The label should float when there is a default value
### What steps did you take, to get the error?
Create a q-input, type=number, and give it a default value

edit:
Tel, password, url, time, and date also cause the label to not float.

**Comment by natxocc** [comment]
I confirm.
Also, it's not necessary to put type=number. If v-model detects is a number, it's not floating.

**Comment by rstoenescu** [comment]
Fixed. Will be available shortly in next alpha release. Thanks for reporting.
