### ISSUE TITLE
Example apps

### ISSUE THREAD

**Issue by ecerroni** [quasarframework/quasar#3]
Do you have any production apps using the framework? Any example from real world apps would be great.

Anyway amazing job you did here.

**Comment by rstoenescu** [comment]
Thank you for your kind words.

Currently I only have some basic demo apps which are not published, but I plan on developing some apps and publish them to the app stores. As soon as I do this, I will add a "Showcase" section to the [official website](http://quasar-framework.org).

**Comment by martinhearn** [comment]
The [Demo App](http://quasar-framework.org/demo-app/) and [source code](https://github.com/rstoenescu/quasar-site/tree/master/demo-app) is a good starting point...

Great framework!

**Comment by rstoenescu** [comment]
https://github.com/rstoenescu/quasar-play is an example app.

**Comment by ecerroni** [comment]
Quasar-Play covers all cases available completed with source code. It's exactly what I meant having.

**Comment by spekulatius** [comment]
subscribe

**Comment by rstoenescu** [comment]
Will do some after we reach v1.0. For now, Quasar Play would suffice.
