### ISSUE TITLE
quasar dev error

### ISSUE THREAD

**Issue by match08** [quasarframework/quasar#3006]
![error_](https://user-images.githubusercontent.com/616730/51385267-bab56480-1b59-11e9-9176-aa25aaf48d17.png)

**Comment by rstoenescu** [comment]
Hi,

That's related to ESLint. Did you install all ESLint packages? In any case, without looking at your project folder I can't help you. Try to engange with our community on [Discord chat](http://chat.quasar-framework.org) or [forum](https://forum.quasar-framework.org) for help on your project.
