### ISSUE TITLE
[v1 Request] QDate Mouse wheel scroll to select months

### ISSUE THREAD

**Issue by natxocc** [quasarframework/quasar#3009]
Would be comfortable to select the months on QDate using the mouse scroll.
When the mouse is on the DatePicker, enable the scroll inside the calendar. When is off, the scroll is on the page.

**Comment by pdanpdan** [comment]
I think that the best way is to implement it on the user side - I added an example here (uses a few internals but should be safe): https://codepen.io/pdanpdan/pen/qBdExzK?editors=1010
