### ISSUE TITLE
Can't remove toolbar shadow

### ISSUE THREAD

**Issue by lhy1149** [quasarframework/quasar#301]
in my template:

class="toolbar no-shadow"
or
class="toolbar shadow-0"

the toolbar still has shadow, change 'no-shadow' to 'inset-shadow' take effect

**Comment by lhy1149** [comment]
figure out:

shadow caused by q-layout, so add 'no-shadow' to q-layout class

**Comment by lhy1149** [comment]
adding no-shadow to q-layout has no effect, use this:

  .layout-header {
    box-shadow: none;
  }

this maybe a  bug, cause header slot is generated by quasar-framework

**Comment by lhy1149** [comment]
same problem on q-search: 

`<q-search :model.sync="search" class="primary no-shadow"></q-search>` has no effect

`.q-search-input {
    box-shadow: none;
  }
` works

**Comment by smolinari** [comment]
This is all new to me, but there are the Stylus variables you can also alter, AFAIK. 

http://quasar-framework.org/api/css-stylus-variables.html

Search for "shadow". 

Scott

**Comment by rstoenescu** [comment]
`$layout-header-shadow` and `$layout-footer-shadow`. Set them to `none`.

**Comment by Narmer23** [comment]
Sorry to necropost, but I'm experiencing the same problem with modal footers and headers. It is true that setting `$layout-header/footer-shadow` to `none` removes the shadow, but it removes it everywhere, while what it should be is to have the shadow everywhere BUT on desktop modals, as per Material Design specs. 

For refererence cfr [Confirmation Dialogs](https://material.io/design/components/dialogs.html#confirmation-dialog) (which can be seen as desktop modals, no shadow) with [Full Screen Dialog](https://material.io/design/components/dialogs.html#full-screen-dialog) (for mobile, with shadows).

Neverthless everything can be achieved with some stylus/CSS, although a bit messy.

**Comment by rstoenescu** [comment]
Dropping a short note: v1 makes these kind of problems non-existent.

**Comment by Narmer23** [comment]
> Dropping a short note: v1 makes these kind of problems non-existent.

Looking forward for v1.0 then!! Rumors say that the RC1 will be available this week... Seriously, the wait is thrilling me! :tada: :tada:

**Comment by tpoxa** [comment]
For v1 its $layout-shadow = "none"

**Comment by rstoenescu** [comment]
v1 layout has some header/footer props now (bordered, elevated).. no need to change CSS
