### ISSUE TITLE
Drawer should be hidden on small AND MEDIUM

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#303]
Drawer should be hidden on small and medium screens, not only on small. (if not on big too)
If you wil just rotate the phone, drawer becomes visible which is bad as taking almost half of width then.

**Comment by murbanowicz** [comment]
or can be a possibility to specify visibility. Sometimes we can want to not show drawer by default at all to use most possible screen area.

**Comment by rstoenescu** [comment]
For second use case you got "swipe-only" attribute that you can use. http://quasar-framework.org/components/drawer.html#Vue-Properties
