### ISSUE TITLE
possible to use quasar inside of NUXT?

### ISSUE THREAD

**Issue by dohomi** [quasarframework/quasar#304]
Hello,
I just playing around with https://nuxtjs.org/ and really enjoy the simplicity of it. Is it possible to use the quasar components inside of that, for example the material design component kit for render a SPA? Thanks

**Comment by rstoenescu** [comment]
Hi, please use forum for questions (http://forum.quasar-framework.org).

**Comment by rlam3** [comment]
@dohomi Did you find your answer. I'm also stumbling into this as well.

**Comment by dohomi** [comment]
@rlam3 you might be lucky with using the SPA mode of Nuxt but I haven't tried it

**Comment by rlam3** [comment]
@dohomi Do you have a demo or a repo of an example of this? Thnks!
