### ISSUE TITLE
form desktop version

### ISSUE THREAD

**Issue by wormen** [quasarframework/quasar#305]
where I can see how to create forms for the desktop version?

**Comment by murbanowicz** [comment]
no difference to mobile. Works for all, but.. for questions please use forum.

**Comment by wormen** [comment]
@murbanowicz the difference may not have, but there is no example in the documentation how to create and align forms

**Comment by murbanowicz** [comment]
on the preview 'phone' you have 'desktop view'. Then you can use 'view source code' to find how it is coded.
On the other side - please use forum, other users will help you (inc me :) )
