### ISSUE TITLE
How can I use my own icon images

### ISSUE THREAD

**Issue by Younghun-Jung** [quasarframework/quasar#3075]
### Software version

Quasar: v0.17.19
OS: macOS Mojave
Node: v10.15.0
NPM: v6.4.1

Hi, I'm testing my project using Quasar Framework.
I got question about using custom icon images.

How can I use my custom icon image through background-image(CSS property)
For example, Using Qcollapsible component, some style is applied from quasar.mat.styl.
![2019-01-23 6 57 00](https://user-images.githubusercontent.com/19387972/51598384-c1205380-1f40-11e9-85e3-434912b04cb1.png)
![2019-01-23 6 59 32](https://user-images.githubusercontent.com/19387972/51598516-0a70a300-1f41-11e9-842b-8ec180709ade.png)

Instead to use 'i' element with 'q-icon' class, I want to use my own icon image.
```
// HTML code example
<div class="q-item-side q-item-section q-item-side-right">
   <span class="some-class"></span>
</div>

// CSS code example
.some-class {
  display: inline-block;
  width: 15px;
  height: 15px;
  background-image: url(SOME_PATH_FOR_MY_OWN_ICON_IMAGE)
  ...
}
```
How can I do this.

Thanks.

**Comment by bloodf** [comment]
Could you please post the Vue that you are using to generate the select?

**Comment by mesqueeb** [comment]
You can now provide custom svg icon's everywhere in quasar. Please see the release notes of beta 14 if I remember correctly.

**Comment by rstoenescu** [comment]
Hi,

This is only possible with 1.0 beta, since QIcon supports images as well (svg, png, ...any type).

**Comment by musicformellons** [comment]
Can you also make webfonts of your own icons and use these? I am no expert, so maybe there is no advantage over using them as svg icons?!

**Comment by rstoenescu** [comment]
RFC to watch: https://github.com/quasarframework/quasar/issues/6027
