### ISSUE TITLE
[BUG]  QSelect float-label not displayed correctly on IE and Edge

### ISSUE THREAD

**Issue by JoseMancebo** [quasarframework/quasar#3078]
### Software version
quasar-framework 0.17.19
IE: 11: 11.253.17763.0
Edge: 44.17763.1.0

### Codepen
https://codepen.io/josemancebo/pen/GzJaBW

### What did you get as the error?
On IE and Edge, the float-label of an QSelect not displayed if doesn't have any option selected. In chrome works correctly.
Edit:
The problem seems to be from this style:
@supports (-ms-ime-align:auto)
.q-if-label-spacer{
width: 0px;
} 

### What were you expecting?
I expect the qselect adapting to the float-label width

### What steps did you take, to get the error?
See the codepen link, and compare the result openning with Edge and Chrome.

**Comment by rstoenescu** [comment]
Pointing out that this has been fixed in 1.0.

**Comment by rstoenescu** [comment]
Please upgrade to v1 as now it's become latest.
