### ISSUE TITLE
q-table, safari, ios

### ISSUE THREAD

**Issue by Lin84** [quasarframework/quasar#3079]
Problem with "q-table" component in safari or ios.
if you scroll to the end for right of table, the border will disappear. 
in case for checkable table, user will not even see what row is selected

https://quasar-framework.org/components/datatable.html

Video demo (open link to q-table component above in safari):
https://monosnap.com/file/x7YwMqTq1dwChK5TKMjY3ixoswBHHb

![image](https://user-images.githubusercontent.com/7355572/51684198-d4d4c400-1feb-11e9-9342-96a12bd1447c.png)

**Comment by Lin84** [comment]
After some investigation.
FYI creator of Quasar:
the problem I described above is caused by "td" has style 'position: relative'

as hot fix for problem:
set 'position:static' for "td" inside "q-table"

Video to demo:
https://monosnap.com/file/GHZVDTRkplbnMvnyywswfW9ZGLfzyV

Big thx to Creators of Quasar :) for creating this nice framework, Keep it up :)

**Comment by Lin84** [comment]
I am not sure about your process further with this discovery, I will keep this issue opened for now. @rstoenescu please close this after proper solution,

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting and also investigating. Fixed it for v1 with the commit above. If you need this fast for 0.17, would you be so kind to port this fix to "v0.17" branch?

Many thanks,
Razvan
