### ISSUE TITLE
Form CSS

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#308]
CSS for aligning forms. Can easily be done without Quasar specific CSS, but a default way to go would be a nice enhancement.

**Comment by wilcorrea** [comment]
I did something like this to use the amazing components into forms to this wip https://github.com/phpzm/jaqa
The form classes:
https://gist.github.com/wilcorrea/f8d712d66800a9d190e949c16933140d

**Comment by rstoenescu** [comment]
Will take a look and prolly merge your work too. Thanks for this!

**Comment by wilcorrea** [comment]
I think a fuzzy demo of this can sounds like https://gist.github.com/wilcorrea/f8d712d66800a9d190e949c16933140d#file-form-vue

**Comment by rstoenescu** [comment]
Making good progress. This will include a lot of features for form components.

**Comment by rstoenescu** [comment]
Will be available in v0.14. Really excited about it.

**Comment by murbanowicz** [comment]
When you expect 0.14 ? You made me very excited about it too :)

**Comment by rstoenescu** [comment]
@murbanowicz don't have a fixed date yet. but yeah, v0.14 is gonna bring Quasar to the next level ;)

**Comment by wilcorrea** [comment]
+1 to excited : )
