### ISSUE TITLE
When using custom header in QCollapsible, can't using QCollapsible as a Router Link.

### ISSUE THREAD

**Issue by icksky** [quasarframework/quasar#3083]
### Software version

Quasar: 0.17.19

### JsFiddle

[jsfiddle demo](https://jsfiddle.net/0fpv9dw4/3/)
### What did you get as the error?
When using custom header in `QCollapsible`, can't using `QCollapsible` as a Router Link.

**Comment by rstoenescu** [comment]
Thank you for providing a PR! Will be available in 0.17.20
