### ISSUE TITLE
Copy-Paste QTable headers not working properly

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#3109]
# Problems
 - headers are not highligted on selection (but they are still copied)
 - icon texts are pasted too
 - Headers on their own cannot be selected at all (it will drag them) - they are buttons in the end but maybe it would be useful to make it possible, too..

# Reproduction
![table_paste](https://user-images.githubusercontent.com/25121817/51807660-3f0a9480-228a-11e9-940b-03e54ba82e26.gif)

# Info
Windows 10, Chrome 71
Quasar 1.0.0-alpha.15

**Comment by panstromek** [comment]
Copy-pasting `dark` table will paste it as white text.. Not sure if that is intended or no 🤔

**Comment by rstoenescu** [comment]
This is perfectly normal.

* Headers are not "selectable" because they could get auto-selected while you click to change sorting.
* The copy functionality that you are using is a browser feature, and it copies HTML. Depending on the program you paste it too, it interprets that HTML or not.

**Comment by panstromek** [comment]
if you say so... It's just a feature I already needed before..
