### ISSUE TITLE
Quasar create using a local kit on windows doesn't work

### ISSUE THREAD

**Issue by gregory-latinier** [quasarframework/quasar#3112]
### Software version

Operating System                Windows_NT(10.0.16299) - win32/x64
NodeJs                          10.12.0

Global packages
  NPM                           6.4.1
  yarn                          1.12.3
  @quasar/cli                   1.0.0-alpha.6
  cordova                       8.1.2 (cordova-lib@8.1.1)

### What did you get as the error?

On windows when I use the following command: 

` quasar create test --kit ./my-starter-kit`

The path is not found. The cli append #master at the end which mess up the pathname for windows because it is looking for the folder `my-starter-kit#master`

To temporarly fix it on my computer I simply removed this line:

https://github.com/quasarframework/quasar/blob/dev/cli/bin/quasar-create#L92

**Comment by rstoenescu** [comment]
Thanks for reporting. Should be working now with @quasar/cli v1.0.0-alpha.7
