### ISSUE TITLE
hot-reload

### ISSUE THREAD

**Issue by Vaerum** [quasarframework/quasar#312]
Hi,
I am having a hard time getting hot-reload working. Just made a new 'Quasar init test', and run 'Quasar dev'. This is the output:

```
keywords if/then/else require v5 option
 Starting dev server with "mat" theme...
 Will listen at http://localhost:8080
 Browser will open when build is ready.

 [==                  ] 10% (building modules)webpack: wait until bundle finished: 
Build completed in 8.491s

webpack built 930036d56f7c51bb29b2 in 8496ms
Hash: 930036d56f7c51bb29b2
Version: webpack 2.1.0-beta.28
Time: 8496ms
                                   Asset       Size  Chunks           Chunk Names
          fonts/Roboto-Thin.90d3804.woff    87.8 kB  [emitted]  
fonts/MaterialIcons-Regular.012cf6a.woff    57.6 kB  [emitted]  
         fonts/Roboto-Light.37fbbba.woff    89.2 kB  [emitted]  
        fonts/Roboto-Medium.303ded6.woff    89.7 kB  [emitted]  
       fonts/Roboto-Regular.081b11e.woff    89.4 kB  [emitted]  
          fonts/Roboto-Bold.ad140ff.woff    89.2 kB  [emitted]  
             img/quasar-logo.2f3aed5.png    50.4 kB  [emitted]  
            js/0.c7905e75fce3d9a746a7.js    24.5 kB  0[emitted]  
            js/1.8b06b921327c687eaf9b.js    21.2 kB  1[emitted]  
                               js/app.js    5.69 MB  2[emitted]  app
                              index.html  578 bytes  [emitted]  
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.48 MB       0  
webpack: bundle is now VALID.
```

When I make changes in ex. index.vue nothing is happening. 

I have the newest CLI installed.

Best regards,
Rasmus

**Comment by murbanowicz** [comment]
try to add few enters and save again. Watcher from webpack does not always
see small changes in Vue files (no idea why).
This is not quasar related issue at all

2017-01-10 14:00 GMT+00:00 Vaerum <notifications@github.com>:

**Comment by Vaerum** [comment]
Thank you for the quick reply. 
I have now tried making some bigger changes without any success. The terminal is not reacting at all. 
I also had a suspicion it was not Quasar related, but have not found any solution on google.

Any other suggestion?

//Rasmus

**Comment by rstoenescu** [comment]
@Vaerum what OS, NPM and Node versions are you using?

**Comment by Vaerum** [comment]
Ubuntu 16.04
NPM 3.5.2
Node v4.2.6

**Comment by rstoenescu** [comment]
Moving discussion to appropriate repository: https://github.com/quasarframework/app-template-default/issues/10

**Comment by Vaerum** [comment]
Found a solution. Read here: https://github.com/quasarframework/app-template-default/issues/10
