### ISSUE TITLE
force contractable stepper 

### ISSUE THREAD

**Issue by ldenblyd** [quasarframework/quasar#3126]
hello how to force contractable stepper ? 

i put a stepper in q-layout-drawer and activate contractable in q-stepper and that dont work

![image](https://user-images.githubusercontent.com/23713069/51958566-c7d32d00-2450-11e9-9a51-98148d5b5b43.png)

**Comment by ldenblyd** [comment]
![image](https://user-images.githubusercontent.com/23713069/51958593-e9341900-2450-11e9-9193-1370646e9419.png)

**Comment by rstoenescu** [comment]
Hi,

v0.17 does not supports that. However, v1.0 will.

**Comment by ldenblyd** [comment]
@rstoenescu cool thanks, when do you think she will be available ?

**Comment by rstoenescu** [comment]
Beta in a few days.

Should mention, for v0.17, apply this CSS to your Stepper: https://github.com/quasarframework/quasar/blob/v0.17/src/components/stepper/stepper.mat.styl#L146-L157

**Comment by ldenblyd** [comment]
great !!
