### ISSUE TITLE
Modal overlay / scroll issue on iOS

### ISSUE THREAD

**Issue by boyd91** [quasarframework/quasar#313]
There seems to be a bug in the modal component on iOS. It is present in both iOS and Material theme **when viewed on an iOS device**.

The parents layout is being displayed over the modal, but it should be underneath it. Also scrolling is glitchy and not 'locked' inside the modal.

I can confirm:
- Bug is present in Cordova app on iOS
- Bug is present in Safari on iOS
- Bug is **not present** in Chrome / Safari on OSX.
- Bug is **not present** on Android 

See screencast of the modals behaviour here: https://giphy.com/gifs/GCJMZ52ZPa9zy

Let me know if I can help debug this issue any further.

**Comment by rstoenescu** [comment]
Will look into it.

**Comment by rstoenescu** [comment]
Fix available in Quasar edge. Will also be available on next Quasar version.
Thank you so much for reporting this!

**Comment by boyd91** [comment]
Awesome! Any details on why this was only occurring on iOS devices? I'm curious.

**Comment by rstoenescu** [comment]
Main reason would be that iOS safari sux bad. It's the new IE. It isn't compliant regarding `z-index` in certain situations.
