### ISSUE TITLE
Select form with search

### ISSUE THREAD

**Issue by Vaerum** [quasarframework/quasar#314]
Hi,
Great job on quasar. Keep up the good work. I have a proposal to the form select.

It good be nice to have a static label that counts the selected elements in a select form. There is a static label in the current, but you do not know have many items that have been selected.

Ex. Countries: 4 selected

And a last proposal would to add a search in the select form.

**Comment by murbanowicz** [comment]
I think it is easily done by yourself like {{
nameOfYourModelForSelect.length }} so there is no sense to make it in the
component.

Although, search in select component makes great sense! It would be so
good.
I would see that like Select 2 multiple, when you just type the name,
select, get the chips with selected and can type another.

2017-01-11 8:47 GMT+00:00 Vaerum <notifications@github.com>:

**Comment by thearabbit** [comment]
Could example on `jsFiddle` or any?

**Comment by smolinari** [comment]
@thearabbit - No, unfortunately, it's not possible to jsfiddle with Quasar. 

Scott

**Comment by thearabbit** [comment]
thanks, where we can?

**Comment by smolinari** [comment]
Because of how a Quasar app runs/ is built, it isn't possible to add it into such a site and fiddle or play with it programmatically directly. There's been discussion about creating a special kind of fiddle site for Quasar, but that is further down on the to-do list.

Scott

**Comment by rstoenescu** [comment]
Moved to v0.14.
