### ISSUE TITLE
need improvement in documentation to custom service worker integration

### ISSUE THREAD

**Issue by eeerrrttty** [quasarframework/quasar#3140]
Quasar do not shows a proper configuration in using custom service worker.

in a normal vuejs app you would change the vue.conf file, but where to change it on quasar?

**Comment by rstoenescu** [comment]
Hi,

First question is: do you really need a custom service worker?

Setting for Quasar apps are set within /quasar.conf.js (https://quasar-framework.org/guide/app-quasar.conf.js.html#Options-to-Configure and the pwa config: https://quasar-framework.org/guide/pwa-configuring-pwa.html)
