### ISSUE TITLE
[Feature request] Allow “mini” mode of QLayoutDrawer in “mobile” behavior.

### ISSUE THREAD

**Issue by german-jablo** [quasarframework/quasar#3147]
I've tried to do it changing the line 265 of QDrawer.js from

`return this.mini && !this.mobileView`
to
`return this.mini`

But it was not enough. I do not know what else I should change.

I think it would be useful for the following reasons:
-Mainly sometimes you want to make a mini drawer for the mobile.
-The documentation is simplified by eliminating that unnecessary restriction.
-The code of the component is simplified by eliminating that unnecessary restriction.

Thank you very much.

**Comment by rstoenescu** [comment]
Hi,

This assumes way too many complications within the Drawer code and would lead to a lot of other issues due to the nature of differences between desktop and mobile. Sorry...
