### ISSUE TITLE
q-editor: text overflows, when height is set

### ISSUE THREAD

**Issue by ircop** [quasarframework/quasar#3157]
### Software version
v0.17.19

### CodePen
https://codepen.io/anon/pen/rPGaPm

  NPM                           6.7.0
  yarn                          1.5.1
  quasar-cli                    0.17.23
  vue-cli                       3.2.3
  quasar-cli                    0.17.23 (Quasar Framework CLI)
  quasar-framework              0.17.19 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)

### What did you get as the error?

Large text is overflowing editor div, when q-editor :height is set

### What were you expecting?

Text must be hidden outside an editor

### What steps did you take, to get the error?

See codepen

**Comment by nothingismagick** [comment]
Is this still happening in latest 0.17.20?

**Comment by rstoenescu** [comment]
This has been fixed in 1.0
