### ISSUE TITLE
[v1 QSelect] Can't create new values with filtering

### ISSUE THREAD

**Issue by natxocc** [quasarframework/quasar#3166]
### Software version

Quasar: 1.0 alpha 23
OS: Win 10
Node: 10
Browsers: Chrome

### JsFiddle
https://codepen.io/natxocc/pen/ErwzLL

### What did you get as the error?
Try to write on QSelect and press ENTER (nothing happens). If I change the focus to anthoner component, the value dissapears

### What were you expecting?
After Press ENTER, the value must be on select field. When I lost focus, the value need to maintain.

**Comment by rstoenescu** [comment]
the second one is an example of filtering, which means if it doesn't pass the filter it's not added.

**Comment by natxocc** [comment]
Ok. Thanks for the information. I didn't understand the example.
