### ISSUE TITLE
Numeric component with minor bug (only Firefox)

### ISSUE THREAD

**Issue by Vaerum** [quasarframework/quasar#317]
Hi
I have found out that the Firefox browser make a validation error (a red border around the input field) when using the numeric component with steps. It is only visual. Chrome is all good.

Tom describe the issue here: https://www.isotoma.com/blog/2012/03/02/html5-input-typenumber-and-decimalsfloats-in-chrome/

It can be fixed by adding the tag step="any" in the numeric component. Like this: 

```
<template>
  <div class="q-numeric textfield row inline items-center" :class="{disabled: disable, readonly: readonly}">
    <i @click="__setByOffset(-1)">remove</i>
    <input
      class="no-style auto q-input-field"
      type="number"
      v-model.number="model"
      @blur="__updateValue()"
      @keydown.enter="__updateValue()"
      @keydown.up="__setByOffset(1)"
      @keydown.down="__setByOffset(-1)"
      @keydown.esc="model = value"
      :disabled="disable"
      :readonly="readonly"
      :style="{width: (''+model).length * .7 + 'em'}"
      step="any"
    >
    <i v-show="value !== model && model !== ''">check</i>
    <i @click="__setByOffset(1)">add</i>
  </div>
</template>
```
// Rasmus

**Comment by rstoenescu** [comment]
Thanks for reporting this and also supplying a solution!
Care for a PR? Things would go much faster.

**Comment by Vaerum** [comment]
Done

**Comment by rstoenescu** [comment]
Thanks for the PR!
