### ISSUE TITLE
[v1 Request] Allow configuration of "index" page for back button in cordova

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#3171]
Currently, you can enable the ability to have the "back" button on Android (Cordova) exit the app when it's on the index `/` page.

It would be nice to be able to configure exactly which page is the index page, because for instance my "index" page for authenticated users is at `/app` instead of `/`

Even better would be if we could supply multiple index pages, such as `['/', '/app', '/admin']`! And if the path matches it exactly it considers it an index page and the back button exits the app.

**Comment by rstoenescu** [comment]
This can also be done in devland by using vue router hooks.
