### ISSUE TITLE
Having lerna installed causes the quasar create to bail out [1.0]

### ISSUE THREAD

**Issue by nurkkala** [quasarframework/quasar#3186]
### 1.0.0-beta.0

As requested by @nothingismagick.

Having `lerna` installed globally causes the `quasar create` to bail out after asking whether to run npm/yarn.

**Comment by mstaack** [comment]
@nurkkala this was your error right?

```
? Should we run `npm install` for you after the project has been created? (recommended) yarn
   Quasar CLI · [.eslintrc.js] Missing helper: "if_eq"
```

**Comment by nurkkala** [comment]
Yes, exactly.

**Comment by rstoenescu** [comment]
I've done some work in @quasar/app beta.19. Please reopen if this still happens.

**Comment by salsa2k** [comment]
Hi @rstoenescu,

I'm using 1.0.0-beta.6 and I get the same error.

`
? Project name (internal usage for dev) test
? Project product name (official name; must start with a letter if you will build mobile apps) test
? Project description test
? Author My Name
? Check the features needed for your project: ESLint, Vuex, Axios, Vue-i18n
? Pick an ESLint preset Prettier
? Cordova id (disregard if not building mobile apps) org.cordova.quasar.app
? Should we run `npm install` for you after the project has been created? (recommended) yarn
  Quasar CLI · [.eslintrc.js] Missing helper: "if_eq"
`

**Comment by nothingismagick** [comment]
what does `quasar info` tell you @salsa2k

**Comment by salsa2k** [comment]
@nothingismagick 

Operating System        Darwin(18.5.0) - darwin/x64
NodeJs                  11.9.0

Global packages 
  NPM                   6.4.1
  yarn                  1.13.0
  @quasar/cli           1.0.0-beta.6
  cordova               Not installed

**Comment by AGPDev** [comment]
Hi, i have this problem yet

[![https://imgur.com/JRCZbs8.png](https://imgur.com/JRCZbs8.png)](https://imgur.com/JRCZbs8.png)

[![https://imgur.com/oAk4EeA.png](https://imgur.com/oAk4EeA.png)](https://imgur.com/oAk4EeA.png)

**Comment by AGPDev** [comment]
Sorry about that.

Initial i make install by `yarn global add @quasar/cli`
After search in Discord i found pinned message of **Hawkeye64** saying "Hey, no problem. We've seen so many issues with NPM, that we recommend Yarn for your local packages, but still use NPM for globals (esp. if you use a Node version manager like NVM)."

After that i uninstall `yarn global remove @quasar/cli` and install by npm `npm install -g @quasar/cli` and problem solved.

**Comment by nothingismagick** [comment]
That's a huge relief.

>
