### ISSUE TITLE
Docs suggestion: First usage then installation

### ISSUE THREAD

**Issue by burningTyger** [quasarframework/quasar#3189]
Looking at the great new v1 docs I noticed I always have to scroll to see what the component is about. 

I usually install a new component after reading about what it does, check the examples and the API and then how it's installed (you can even guess how it works after installing two or three components)

So the preferred order would be: 

* introduction
* usage
* api
* installation

**Comment by mesqueeb** [comment]
+1

**Comment by rstoenescu** [comment]
While many may agree with this, it is imperative for people just getting to know Quasar to realise there is an install step necessary. So it is better than putting Install after Usage.

**Comment by mesqueeb** [comment]
How about making the installation section collapsable, and remembering this setting in a cookie?
So that when a user collapses it, it will be collapsed for all pages.
