### ISSUE TITLE
q-editor when print, are not breaking lines

### ISSUE THREAD

**Issue by juppdes** [quasarframework/quasar#3190]
### Software version
v1.0 beta

### CodePen
https://codepen.io/Jupp/pen/MLQzVv?&editable=true&editors=101

NPM 6.7.0
yarn 1.5.1

### What did you get as the error?
The lines are usually breaking here in the text editor, but when it prints, it hides the text beyond the size of the page, that is, it is not breaking as it appears in the edit.

### What were you expecting?
Breaking lines when print

### What steps did you take, to get the error?
See codepen

**Comment by rstoenescu** [comment]
Grouping with https://github.com/quasarframework/quasar/issues/4349

**Comment by GhazalNikmanesh** [comment]
Hello world
Bye world

**Comment by GhazalNikmanesh** [comment]
// quasar.conf.js 

  

framework: { 

  plugins: [ 

    'Notify' 

  ] 

}
