### ISSUE TITLE
Quasar dev command fails in monorepo [1.0]

### ISSUE THREAD

**Issue by nurkkala** [quasarframework/quasar#3191]
### Software version
Operating System - Darwin(18.2.0) - darwin/x64
NodeJs - 11.9.0
Global packages
  NPM - 6.5.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.0
Browsers:
  Chrome

### What did you get as the error?

When running `quasar dev`, get the following:
```
   internal/modules/cjs/loader.js:611
    throw err;
    ^

  Error: Cannot find module '.../packages/projector/node_modules/quasar/package.json'

  - loader.js:609 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:609:15
```

### Diagnosis

I am running in a Yarn-managed monorepo where the `project` directory's `node_modules` is empty except for symlinks from the `./bin` directory. Modules are installed in the top-level `node_modules` of the monorepo.

The error stems from line 4 of `banner.js`:
```
quasarVersion = require(appPaths.resolve.app('node_modules/quasar/package.json')).version
```
Because `quasar` is actaully installed in `../../node_modules`, the call to `resolve.app` returns a bogus path, causing `version` to dereference a bogus value.

### Analysis

The issue stems from the hardwired relative path to `package.json`. Is this strictly necessary? It seems like using the normal Node module resolution strategy would work here.

### Work around

Can work around the problem using `yarn link`.

* `cd` to top-level `node_modules/quasar`
* `yarn link`
* `cd`back to `packages/projector`
* `yarn link quasar`

**Comment by rstoenescu** [comment]
This should be fixed with quasar/app beta.19
