### ISSUE TITLE
Theme builder - can't select right side drawer border option as it's out of view [v1.0]

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#3192]
As you can see in the picture below, the third option for selection is hidden.

![image](https://user-images.githubusercontent.com/10404747/52524980-e7612580-2c9a-11e9-8135-ae856e9f3fc6.png)

This is my format:

![image](https://user-images.githubusercontent.com/10404747/52524990-0069d680-2c9b-11e9-9ac9-1f9c5d2a0410.png)

With these options selected:

![image](https://user-images.githubusercontent.com/10404747/52524998-15df0080-2c9b-11e9-80af-e9d7cd7b8381.png)

**Comment by rstoenescu** [comment]
Fixed (will be live tomorrow). Thanks for reporting!
