### ISSUE TITLE
[Request] Khmer Language

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar#3204]
I would like to request the `Khmer Language`

[lang.zip](https://github.com/quasarframework/quasar/files/2849895/lang.zip)

**Comment by pdanpdan** [comment]
Can you please make a PR with the files? It would help us a lot.

**Comment by thearabbit** [comment]
OK I will try

**Comment by rstoenescu** [comment]
Added. Will be available in beta.1. Thanks!

**Comment by thearabbit** [comment]
Very thanks, I will try PR later.
