### ISSUE TITLE
[v1-bug] babel error on build on QRange

### ISSUE THREAD

**Issue by nanov** [quasarframework/quasar#3205]
### Software version

Quasar: 1.0.0-beta.0
@quasar/app (v1+ only): 1.0.0-beta.2
OS: Darwin(18.2.0) - darwin/x64
Node: 11.4.0
NPM: 6.7.0

### What did you get as the error?
When ```QRange``` is included, I get the following error on build:
```
Syntax Error:   SyntaxError: /Users/mitkonanov/Projects/FRONTEND/team-backend-quasar/node_modules/quasar/src/components/range/QRange.js: Unexpected reserved word 
'let' (183:6)
    181 | 
    182 |     __getDragging (event) {
  > 183 |       let
        |       ^
    184 |         { left, width } = this.$el.getBoundingClientRect(),
    185 |         sensitivity = this.dragOnlyRange ? 0 : this.$refs  [33m.minThumb.offsetWidth / (2 * width),
    186 |         diff = this.max - this.min
```

### What were you expecting?
Well, the app to build normally.

### What steps did you take, to get the error?
Added ```QRange``` to ```quasar.conf.js```.

A fix would be to move the first variables declarations into the same line as ```let```.

**Comment by rstoenescu** [comment]
Fixed in beta.1 (releasing later today).
