### ISSUE TITLE
[v1.0] QSelect use-input not capturing enter key

### ISSUE THREAD

**Issue by smcassar** [quasarframework/quasar#3207]
QSelect with use-input and multiple prop submits the form its wrapped in when adding a new value with enter.

Quasar: 1.0.0-beta.0
@quasar/app (v1+ only): 1.0.0-beta2
OS: Darwin(18.2.0)
Node: 10.6.0
NPM: 6.1.0

### JsFiddle
https://jsfiddle.net/cfunkvw5/

**Comment by rstoenescu** [comment]
Just fixed today. Releasing beta.1 later today. Thanks for reporting.
