### ISSUE TITLE
Dialog hides scrollbar [1.0]

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#3212]
### Software version
Quasar: 1.0.0-beta.0
Browsers: Chrome 71, IE 11, Firefox 61

### What did you get as the error?
- When you open e.g. Alert, Confirm or Prompt it shows a dialog window but it hides a browser window scrollbar = window width is changed.
- It is causing shifting objects on the page to the right when opening a back left when closing. I think this is a bit distracting (example)[https://v1.quasar-framework.org/vue-components/dialog#Usage].
![image](https://user-images.githubusercontent.com/37825539/52557861-f659ec00-2df0-11e9-9afb-e0db08be33b6.png)
![image](https://user-images.githubusercontent.com/37825539/52557847-efcb7480-2df0-11e9-8614-b1fd1584ca99.png)

### What were you expecting?
The same behaviour as previous version - do not hide browser scrollbar.

With Quasar 0.17 scrollbar stays visible so the dialog window doesn't cause page objects changes their positions (example)[https://quasar-framework.org/quasar-play/android/index.html#/showcase/popups/dialog].
![image](https://user-images.githubusercontent.com/37825539/52557811-d5919680-2df0-11e9-8afd-0be5eb0298b9.png)

**Comment by pdanpdan** [comment]
If you like it more with scrollbar then you can add
```stylus
.q-body--dialog
  overflow auto
```
to your app.styl file

**Comment by m0jimo** [comment]
I don't mind about scrollbar visibility but I'm not very happy when objects behind dialog are changing their position because of hiding/showing scrollbar.

Thank you for your css tips.

**Comment by rstoenescu** [comment]
Hi,

Thanks for pointing this out!
Fix will be available in v1.0 beta.2

**Comment by rstoenescu** [comment]
I recommend you don't change the CSS and wait for beta.2.
