### ISSUE TITLE
UMD cdn links and docs for 1.0 beta not working

### ISSUE THREAD

**Issue by tanthammar** [quasarframework/quasar#3213]
All comments below are found on this documentation page:
https://v1.quasar-framework.org/start/umd

1.  None of the referred JS "quasar@^1.0.0-beta.1" links are working.
Returns error: Couldn't find the requested release version ^1.0.0-beta.1

2. The JS fiddle link, loads Quasar v0.15 - not v1.0

3. The CodePen link loads Quasar v0.17.19 - not v1.0

4. The CLI command "quasar **create** <folder_name> --kit umd" generates a page with v0.17.19 syntax As it is using "create", I expected a v1.0 template.

I am new to Quasar which means I don't recognise the difference between v0.17 and v1.0 syntax.
Spent hours to figure out why I could nott get anything to work.

Anyone else reading this in need of a quick fix, i finally solved it by removing the version in the urls, which returned the latest version.

Example
Change this:
https://cdn.jsdelivr.net/npm/quasar@^1.0.0-beta.1/dist/quasar.umd.min.js
to
https://cdn.jsdelivr.net/npm/quasar/dist/quasar.umd.min.js

OR
beta.0 is available when I post this.

**Comment by rstoenescu** [comment]
Hi,

1. beta.1 is not released yet. beta.0 is latest. Agreed that the https://v1.quasar-framework.org/start/umd needs a fix to point to beta.0. Fixing it right now.

2. Where did you click on the jsfiddle/codepen links? They correctly point to 1.0.

**Comment by rstoenescu** [comment]
Ok, I see now point 2 too. Fixed and will be available along with next release (beta.1).
Thanks for reporting!
