### ISSUE TITLE
[Proposal] Server Side Rendering with Streaming

### ISSUE THREAD

**Issue by josemanuelp** [quasarframework/quasar#322]
It would be so great that the framework boilerplate considers SSR with Streaming.

There is https://github.com/vuetifyjs/vuetify project that is more younger than quasarframework but implement it very good.

**Comment by yieme** [comment]
https://github.com/nuxt/nuxt.js ![](https://img.shields.io/github/stars/nuxt/nuxt.js.svg?label=%E2%98%85) may be another approach which like vuetify ![](https://img.shields.io/github/stars/vuetifyjs/vuetify.svg?label=%E2%98%85) has a generic starter template but also has templates for ExpressJS and [AdonisJS](https://github.com/nuxt/adonuxt).

**Comment by josemanuelp** [comment]
Quasar plus Nuxt would be mindblowing....

Btw, it would be theoretically possible to run quasar components inside Nuxt boilerplate? Has anyone ever tried?

**Comment by smolinari** [comment]
I'm betting Razvan (and whoever else can help him) is going to have to build an SSR solution for Quasar. Both Quasar and Nuxt are already too opinionated to mix and match them. That is my less then very experienced opinion of course.  

What I'd also like to understand is, what is meant by "SSR with streaming"? 

Scott

**Comment by nconf-base** [comment]
Streaming appears to be short for Response Streaming for the rendering Vue components. See [Vue SSR Guide Response Streaming](https://vuejs.org/v2/guide/ssr.html#Response-Streaming).

Nuxt is a framework specifically for VueJS and Server Side Rendering (SSR). Streaming is on their roadmap [1.0 roadmap](https://github.com/nuxt/nuxt.js/issues/26)

**Comment by smolinari** [comment]
Ah. Ok. Understand now. Thanks @nconf-base.

Scott

**Comment by emahuni** [comment]
any news on this, I dying to use Quasar + Nuxt

**Comment by yieme** [comment]
@emahuni preliminary work-in-progress scaffolding https://github.com/quasarframework/quasar-template-nuxt/ 

Not ready yet, as per [issue #2](https://github.com/quasarframework/quasar-template-nuxt/issues/2)

**Comment by Charuru** [comment]
This is absolutely necessary in 2017, soon to be 2018...

**Comment by tomexx** [comment]
any update on integrating Nuxt + Quasar? Thanks

**Comment by rstoenescu** [comment]
Are you guys aware of https://forum.quasar-framework.org/topic/2481/quasar-quasar-cli-v0-17-aka-ssr-developer-preview ?

Nuxt module will come after v0.17 release (which is days away), but I really don't see any need now for this, since you'll be able to use your current Quasar app and simply build a SSR with it through Quasar CLI :)

**Comment by smolinari** [comment]
@rstoenescu - So Quasar doesn't use Nuxt? Or is it integrated some other way? 

What would be great is a conceptual article on how Quasar does SSR under the hood. :smile: 

Scott

**Comment by rstoenescu** [comment]
Check out Quasar v0.17. I've just released it.

**Comment by rstoenescu** [comment]
@smolinari These are some common misconceptions. Quasar does not use Nuxt under the hood, nor does it use Vue CLI.

**Comment by smolinari** [comment]
@rstoenescu - I think that misconception might have come from some discussion in the past about Quasar partnering with Nuxt or something to that effect. It isn't important. 

So the open question remains (in my mind at least), how does Quasar do SSR? :smile: Doesn't need an explanation here. A Medium article would be better, I think. :wink: 

Scott
