### ISSUE TITLE
[v1] dot-prop cannot be resolved in electron builds

### ISSUE THREAD

**Issue by burningTyger** [quasarframework/quasar#3223]
### Software version
@quasar/app@1.0.0-beta.3

Operating System - Linux(4.20.7-arch1-1-ARCH) - linux/x64
NodeJs - 11.9.0

Global packages
  NPM - 6.7.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.0
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.1 -- Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.3 -- Quasar Framework App CLI
  @quasar/extras - 1.0.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.5 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - 3.1.3 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 13.0.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @babel/core - 7.2.2 -- Babel compiler core.
  webpack - 4.29.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.1.14 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.0 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
Any other software related to your bug:

### What did you get as the error?
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'dot-prop'
```
### What were you expecting?
no error
### What steps did you take, to get the error?

    quasar build -m electron

### Fixed the error

I had to add `dot-prop` to my `package.json`s dependency list

**Comment by rstoenescu** [comment]
Hi,

This is perfectly normal. If your project imports a dependency then it needs to be specified in "dependencies" in package.json. Even if that dependency is part of @quasar/app. When building there is a pruning system in place so that the whole process takes way less time.
