### ISSUE TITLE
Language packs en-UK

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3226]
Hello team,
Congrats! Excellent job indeed!

My point is that the language pack supports 'en-UK' which is not a valid ISO code. Instead, the actual code returned by all browsers is 'en-GB'. So, using the relevant result of the new Quasar.lang.getLocale() function in import(`quasar/lang/${lng}`) throws an error.

A possible workaround could be to include in the languages a new file (en-gb.js) with the same content as en-uk.js (so as not to affect legacy applications).

Thanks,
Elias

**Comment by rstoenescu** [comment]
Hi, Thanks for pointing this out. v1.0 beta.2 will have this corrected.
