### ISSUE TITLE
Wrong QInput margin on mobile

### ISSUE THREAD

**Issue by lucasfernog** [quasarframework/quasar#3227]
### Software version

Quasar:
@quasar/app (v1+ only): docs
Android: 7.0

### What did you get as the error?

Wrong QInput margin on docs page (mobile)

### What were you expecting?

Same margin-right as margin-left

### What steps did you take, to get the error?

Just open the docs and scroll to "Standard" or "Filled" QInput example

![screenshotcapture_2019_02_10_15_38_10_008](https://user-images.githubusercontent.com/20051258/52628385-b3eee880-2e9e-11e9-8ec3-8cccd3fad051.jpg)

**Comment by rstoenescu** [comment]
Fix will be available on next docs deployment.
