### ISSUE TITLE
Imported component translations (VueI18n) do not work in QDialog

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#3234]
### Software version

Operating System - Linux(4.20.7-arch1-1-ARCH) - linux/x64
NodeJs - 11.9.0

Global packages
  NPM - 6.7.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.0
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.1 -- Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.4 -- Quasar Framework App CLI
  @quasar/extras - 1.0.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.6 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.2.2 -- Babel compiler core.
  webpack - 4.29.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.1.14 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### What did you get as the error?
When I use an imported component which contains a vuei18n translation in a QDialog, I receive the error "TypeError: i18n is undefined".

E.g.:
TestComponent
```
<template>
  <div>
    {{ $t('test') }}!!!
  </div>
</template>
```
QDialog
```
<q-dialog
  v-model="opened"
  persistent
>
  <test-component/>
  {{ $t('test') }}
</q-dialog>
```
The translation between the braces will work, but the imported component gives the error. It only seems to happen when used in a QDialog.

### What were you expecting?
i18n should be defined in such cases.

### What steps did you take, to get the error?
See above

**Comment by rstoenescu** [comment]
Fix will be available in beta.2.
