### ISSUE TITLE
[v1] Q-input enable/disable resize grip

### ISSUE THREAD

**Issue by wvansl** [quasarframework/quasar#3239]
### Software version
quasar-framework 1.beta.4

### Images
https://media.discordapp.net/attachments/543560902675398665/544986596806623233/unknown.png
https://media.discordapp.net/attachments/543560902675398665/544986892031098906/unknown.png

### What did you get as the error?
- The resize grip (bottom right) is not good visible when using cordova (or emulated mobile). It looks like dirt on a screen.
- The resize grip (bottom right) moves when there is an error using form validation

### What were you expecting?
I expect that the resize grip should have an option to be visible or not and to be resizable or not (true/false).
Maybe by default it should not show on mobile devices

### What steps did you take, to get the error?
See the screenshots, standard q-input type="text-area"

**Comment by pdanpdan** [comment]
You know you put a empty codepen and you have no title :) ?

**Comment by wvansl** [comment]
> You know you put a empty codepen and you have no title :) ?
Sorry I must have been still sleeping...
Codepen, I will have to make again, appearantly (most?) the codepen under the q-input docs are not working (are empty)

**Comment by rstoenescu** [comment]
Fix will be available on beta.2
