### ISSUE TITLE
[v1] QUploader headers not working

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3241]
### Software version

Quasar:
@quasar/app (v1+ only):
OS: All
Node: All
NPM: All
Browsers: All
iOS: All
Android: All
Any other software related to your bug:

### JsFiddle
https://codepen.io/anon/pen/exjBQX?&editable=true&editors=101

### What did you get as the error?
The headers aren't used.

### What were you expecting?
The headers to be used.

### What steps did you take, to get the error?
Specified headers.

**Comment by rstoenescu** [comment]
Fix will be available in quasar v1.0.0-beta.2
