### ISSUE TITLE
[v1] - QInput on IE 11

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3250]
### Software version

Quasar:
@quasar/app (v1+ only):
OS: All
Node: All
NPM: All
Browsers: IE 11
iOS: All
Android:
Any other software related to your bug:

### What did you get as the error?
Border goes above label on focus
![ie-qinput](https://user-images.githubusercontent.com/1173770/52742793-45d42e00-3024-11e9-9400-13bf37db53cf.png)

### What were you expecting?
Border to behave the same as Chrome / Webkit

### What steps did you take, to get the error?
Just used a QInput with a label

**Comment by rstoenescu** [comment]
IE11 support has been added in beta.2 (to be released in a day or two).
