### ISSUE TITLE
[v1] - QMenu not working on IE 11

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3251]
### Software version

Quasar:
@quasar/app (v1+ only):
OS: All
Node: All
NPM: All
Browsers: IE 11
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Javascript error when trying to open the menu when in a QToolbar
```SCRIPT5007: Unable to set property 'maxHeight' of undefined or null reference```

### What were you expecting?
The menu to open

### What steps did you take, to get the error?
Clicked on the menu trigger

**Comment by rstoenescu** [comment]
IE11 support has been added in beta.2 (to be released in a day or two).
