### ISSUE TITLE
[v1] Toggle inside list item does not change when clicking on the toggle itself

### ISSUE THREAD

**Issue by wvansl** [quasarframework/quasar#3253]
### Software version
v1-beta1

### Codepen
https://codepen.io/anon/pen/JxBgML?&editable=true&editors=101#anon-login

### What were you expecting?
I create a toggle in a list item (exactly the same as Quasar docs example). 
Now, clicking on the list item row changes the toggle value. But clicking on the Toggle itself does nothing (toggle doesnt change).

I would prefer/think that clicking on the toggle would also change the toggle value. Otherwise it will be very confusing for users

### What steps did you take, to get the error?
Standard docs example

**Comment by rstoenescu** [comment]
Fix will be available in beta.2
