### ISSUE TITLE
[V1] Proyect creation fails when using airbnb or pretier eslint profiles + vuex

### ISSUE THREAD

**Issue by marcorivm** [quasarframework/quasar#3258]
### Software version

❯ quasar info

Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.6.0

Global packages
  NPM - 6.1.0
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.1
  cordova - 8.0.0

Important local packages
  quasar - 1.0.0-beta.1 -- Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.4 -- Quasar Framework App CLI
  @quasar/extras - 1.0.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.6 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.2.2 -- Babel compiler core.
  webpack - 4.29.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.1.14 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Any other software related to your bug:
ESLint, Vuex

### What did you get as the error?
When trying to create a new project using the `-b dev` option and choosing the ESLint (Airbnb or prettier), and Vuex options the example store files for actions, mutations and getters trigger ESLint errors that cannot be auto-fixed, this breaks the install process, you can go into the new folder and fix those issues manually.
```
yarn run v1.12.3
$ eslint --ext .js,.vue src --fix

D:\experiments\airbnb-app-yarn\src\store\module-example\actions.js
  1:1   error  Prefer default export                import/prefer-default-export
  1:28  error  'context' is defined but never used  no-unused-vars

D:\experiments\airbnb-app-yarn\src\store\module-example\getters.js
  1:1   error  Prefer default export              import/prefer-default-export
  1:28  error  'state' is defined but never used  no-unused-vars

D:\experiments\airbnb-app-yarn\src\store\module-example\mutations.js
  1:1   error  Prefer default export              import/prefer-default-export
  1:30  error  'state' is defined but never used  no-unused-vars

✖ 6 problems (6 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 yarn install FAILED... Possible temporary npm registry issues?
 Please try again later...
```

### What were you expecting?
Install should consider changing those files so eslint is ok with them or expect eslint error and allow the user to fix those without failling the install process.

### What steps did you take, to get the error?
Installation Options:
```
❯ quasar create airbnb-app-yarn -b dev

  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|



? Project name (internal usage for dev) airbnb-app-yarn
? Project product name (official name) Quasar App
? Project description A Quasar Framework app
? Author Marco Rivadeneyra <marcorivm@gmail.com>
? Check the features needed for your project: ESLint, Vuex
? Pick an ESLint preset Airbnb
? Cordova id (disregard if not building mobile apps) org.cordova.quasar.app
? Should we run `npm install` for you after the project has been created? (recommended) yarn
```

### Sugestions
I see the value on having the example stores created, and that in a real-world scenario those files would have more than one export so ESLint would be fine with that, there is already prescedence on the `module-example/index.js` file, where getters, mutations and actions are commented, so the functions inside the example files for the store could also be commented, ESLint doesn't have an issue with the files containing only comments.

**Comment by rstoenescu** [comment]
Fixed. Thanks for reporting.

**Comment by Theorian** [comment]
Just happened to me now

**Comment by Theorian** [comment]
Nevermind I just had to install yarn I guess

**Comment by smolinari** [comment]
@Theorian - Yes, we highly recommend Yarn for local package management i.e. for Quasar projects you build and NPM for global package management ie. for installing and upgrading the CLI.

Scott
