### ISSUE TITLE
[v1] Date Picker - Vertical scrollbar shouldn't appear

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3259]
Sorry my English is poor :-(
There is enough space at the bottom of the page but the scroll bar still appears.（The max avail height of my browser page is about 600 px）
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-date-1.png)

In addition, I think the date picker should have a fixed height, rather than changing with the page.
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-date-2.png)

**Comment by QQ34205037** [comment]
hi, Thank you for your work on this issue, but it's still not very good in v1.0-beta.2

![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-date-7.png)
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-date-8.png)

why can't the date picker have a fixed height?

**Comment by rstoenescu** [comment]
Fix will be available in beta.4
