### ISSUE TITLE
Collapsibles which act as Accordion (opening one closes the siblings)

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#326]
Thanks to @fsgiudice for starting this.

**Comment by rstoenescu** [comment]
All one need to do is to wrap the group of `q-collapsible` into a `q-collapsible-accordion` component. Use case:

```html
<q-collapsible-accordion class="list">
  <q-collapsible icon="explore" label="First" opened>
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </q-collapsible>
  <q-collapsible icon="perm_identity" label="Second">
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </q-collapsible>
  <q-collapsible icon="shopping_cart" label="Third">
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </q-collapsible>
</q-collapsible-accordion>
```

**Comment by rstoenescu** [comment]
Updated API to make usage even easier and have even lower footprint. If you want to group collapsibles to act as an accordion, just specify "group" attribute with a unique string (same string for all collapsibles that you want to group):

``` html
<q-collapsible group="somegroup" icon="explore" label="First">...</q-collapsible>
<q-collapsible group="somegroup" icon="explore" label="Second">...</q-collapsible>
<q-collapsible group="somegroup" icon="explore" label="Third">...</q-collapsible>
```

**Comment by fsgiudice** [comment]
I prefer version with a tag to envelope the group. You don't have to specify a unique name for all items.
And, I didn't try, what happens if I use same unique group name between different groups?

**Comment by rstoenescu** [comment]
There are a few advantages over the first version (with an extra component):

- Lighter with lower footprint, faster (js execution-wise), no extra dummy component
- More flexible:
  - you can leave out some collapsibles opened by not including them in the group
  - you can even make a group with collapsibles that are not siblings in DOM
  - you can make multiple groups within sibling collapsibles
- You can use same group name for multiple collapsibles as long as the parent Vue component (not talking about DOM parent node) is not the same
- No additional markup (like a DOM node) that should wrap a group of collapsibles

I think the flexibility should be a key point when creating a framework and the flexibility offered by the first version superseeds the minimum HTML syntax overhead to specify an attribute for each collapsible. Can we agree on this one?
