### ISSUE TITLE
[v1] Date Picker（With QInput） - How to quickly select a date？

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3260]
In v1, how can the Date Picker（With QInput） quickly select a date, such as double-click or click an OK button? At present, I can only click on the blank area of the page to close the pop-up.
Sorry for my English.

**Comment by pdanpdan** [comment]
Please create a fiddle and we'll check.

**Comment by QQ34205037** [comment]
@pdanpdan Thanks for your code tips, I'll try later.
