### ISSUE TITLE
[v1 web site] Add Search function to the Quasar web site

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#3270]
![image](https://user-images.githubusercontent.com/5996531/52790317-3f4db280-3034-11e9-94eb-1ab3e03d7886.png)
On the previous version of the [web site](https://quasar-framework.org/components/), there is a search function for global search. It's missing on the v1 web site. It would be good to have it on the v1 web site.

In additional to that, is it possible to add another search box on the left Nav bar for searching the titles on the Nav bar? For example, if I type in "Table" in the search box, only items containing "Table" will show up. It will help find the information faster.

**Comment by rstoenescu** [comment]
Hi, It's definitely on the todo list. No need for a ticket.

**Comment by topvis** [comment]
Sounds good.
It would be good to have a todo list somewhere so we don't need to raise issues if they are already on the todo list.
