### ISSUE TITLE
Modal get closed when clicking on device backbutton. Not possible to prevent it.

### ISSUE THREAD

**Issue by FrancescoMussi** [quasarframework/quasar#3271]
In my app I have a fullscreen setup modal. It's important that it must not be closed by the device backbutton (I am testing on Android at the moment).

This is the modal:
```
<q-modal
    v-model="showSetupModal"
    maximized
    no-backdrop-dismiss
    no-esc-dismiss
    no-route-dismiss
    class="modalSetup"
  >
```
I have tried setting `backButtonExit ` to `false` as shown [here](https://quasar-framework.org/components/handling-back-button.html#Cordova-Use-Case). In this way the closing of the app through the backbutton is prevented, but **the modal still get closed**.

```
framework: {
      config: {
        cordova: {
          backButtonExit: false
        }
```

I am trying to listening to the `backbutton` event and `preventDefault` or `stopPropagation`:
```
document.addEventListener('backbutton', (e) => {
  console.warn('backbutton clicked')
  console.log(e)
  e.stopPropagation()
  e.preventDefault()
  console.log('showSetupModal')
  console.log(this.showSetupModal)
}, false)
```
 but **the callback is triggered right after the modal get closed**. As is shown in the console. (Since the v-model of the modal is a stored state, I even get the error that it cannot be set directly)

![screen shot 2019-02-14 at 15 54 20](https://user-images.githubusercontent.com/5312907/52791536-db49df00-3071-11e9-89af-9fc18126e5e2.png)

### Software version
Quasar:  	0.17.18
OS: MacOS High Sierra
Node: 10.12.0
NPM: 6.7.0
Android: X

### What did you get as the error?

`Computed property "showSetupModal" was assigned to but it has no setter.`

### What were you expecting?

I would like to be able to prevent the closing of the modal when clicking on the backbutton device button.

There is a way to do that in Quasar?

Thanks

**Comment by rstoenescu** [comment]
Hi, unfortunately stopping user from navigating is impossible with current web standards....
