### ISSUE TITLE
[v1] Allow clickable components in header slot without node expansion in QTree

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3274]
This is a feature request. 

Description:
If I put some clickable component (for example a q-checkbox) inside the header slot, the QTree triggers a node expansion or collapsing (it depends if the node is open or not) when the component is clicked, so I cannot check the component without tree changing. 
I think that should be allowed to choose the behaviour of the node when the header is clicked (for example making only the arrow clickable) so I can put every sort of clickable component in the header slot.

**Comment by rstoenescu** [comment]
Hi,

Put a `@click.stop` on each such component. Cannot do it automatically from Quasar because it would break forms.

**Comment by willypuzzle** [comment]
Ok, thank you
