### ISSUE TITLE
[v1] Validation triggers on next step when animated is not set in stepper

### ISSUE THREAD

**Issue by ungchy** [quasarframework/quasar#3275]
### Software version

Quasar: 1.0.0-beta.1
@quasar/app: 1.0.0-beta.4
OS: Linux
Node: 11.8.0
yarn - 1.13.0
Browsers: Chrome

### CodePen

https://codepen.io/anon/pen/aXaRjX?editors=1010

### What did you get as the error?
When the animated prop is not set and the next step is clicked
the Quasar validation is triggered and all fields in the next step are in error.

### What were you expecting?
When clicking next and a validation rule is set on the next page
it should not be in error

### What steps did you take, to get the error?
Enter something in the field on step 1 in the codepen example then click next

**Comment by rstoenescu** [comment]
This sure looks like a Vue bug. Will investigate deeper with first chance I get.

**Comment by DaedalusDev** [comment]
I thinks this isn't a vue bug.
You just have to add a `key` attr on your steppers to do the trick.
If you don't, vue may did a partial re-render especialy for same sibling components (vNode shadow renderer)

See https://vuejs.org/v2/style-guide/#v-if-v-else-if-v-else-without-key-use-with-caution

**Comment by rstoenescu** [comment]
Fix will be available on beta.8.
