### ISSUE TITLE
[v1] q-select doesn't show correctly inside q-table 

### ISSUE THREAD

**Issue by aldozumaran** [quasarframework/quasar#3276]
Quasar: v1.0.0-beta.0
@quasar/app (v1+ only): v1.0.0-beta.2
OS: Ubuntu
Node: 9.11.1
NPM: 6.4.1
Browsers: Chrome

https://codepen.io/aldozumaran/pen/ErerRO

### What did you get as the error?
when you open the Q-Select of the last row, the table stretches and the select doesn't go over it.
### What were you expecting?
the q-select when open should go over the table without stretching, also there should be some space at the bottom
### What steps did you take, to get the error?
i've put a q-select inside a table column, and tried to open it

**Comment by rstoenescu** [comment]
Fix will be available in beta.14

**Comment by rstoenescu** [comment]
Delaying this a bit. Not yet "production ready". Didn't went into beta.14.

**Comment by rstoenescu** [comment]
Please follow https://github.com/quasarframework/quasar/issues/3242 for updates.
