### ISSUE TITLE
[v1] [Feature Request] some props with default value

### ISSUE THREAD

**Issue by lucasfernog** [quasarframework/quasar#3277]
I think it would be nice to have props such as "dark", "dense" to have a default value provided through $q, so we would setup this.$q.dense = true at boot time and it would propagate to components. This way we could have a dark theme or a dense theme

**Comment by panstromek** [comment]
Just so you know that this is active - few people already requested something similar and we are trying to find the best way to integrate these `defaults`, together with the theming system ;)

Currenctly the focus on getting 1.0 stable out, so we will focus on this later ;)

**Comment by duurland** [comment]
A temporary solution would be [injection](https://vuejs.org/v2/api/#provide-inject) through a [boot file](https://quasar.dev/quasar-cli/cli-documentation/boot-files)
```js
export default async ({ Vue }) => {
  Vue.mixin({
    inject: {
      dark: { default: true },
      dense: { default: true }
    }
  });
};
```

**Comment by rstoenescu** [comment]
Same as https://github.com/quasarframework/quasar/issues/3968, so closing.
