### ISSUE TITLE
date.adjustDate with day key return an error

### ISSUE THREAD

**Issue by drkwolf** [quasarframework/quasar#3278]
date.adjustDate(new Date(), {day: 10}) throw an error, the doc should be update, the key 'day' should be replaced by date 
this works : date.adjustDate(new Date(), {date: 10})

### Software version

Quasar:
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers: Firefoix
iOS:
Android:
Any other software related to your bug:

### JsFiddle
https://codepen.io/anon/pen/wNELmj?editors=1111
### What did you get as the error?
TypeError: n[("" + s + i)] is not a function
    at VM398 quasar.umd.min.js:6
    at Array.forEach (<anonymous>)
    at oi (VM398 quasar.umd.min.js:6)
    at bn.created (VM471 pen.js:12)
    at Fe (VM397 vue:6)
    at Xt (VM397 vue:6)
    at bn.t._init (VM397 vue:6)
    at new bn (VM397 vue:6)
    at VM471 pen.js:1
### What were you expecting?
valide date

**Comment by rstoenescu** [comment]
Thanks for supplying a PR for this!
