### ISSUE TITLE
[v1]QBtnDropdown - a problem with the location of the dropdown menu

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3283]
### Versions and Environment
**Browsers:** Chrome 72.0.3626.96
**OS:** Mac OS 10.14.3

### Reproduction Link
https://v1.quasar-framework.org/start （The dropdown menu on the right side of the toolbar）
or
https://codepen.io/qq34205037/pen/BMqpBW?editors=1010

When the page scrolls, there is a problem with the location of the dropdown menu.
It seems to recalculate the position, but offset by 1 px.
Strangely, both the "v1.0.0-beta.1" menu and the "Support" menu have this problem, but the "Quick Links" menu has no problem.
In safari, this problem doesn't seem to exist！
Speaking English feels terrible to me :(
#### step 1.Open the dropdown menu
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-btn-dropdown-1.png)

#### step 2.Do not close the dropdown menu and scroll the scrollbar
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-btn-dropdown-2.png)

**Comment by rstoenescu** [comment]
Hi,

Please reopen if it's still not fixed in current deployed version. Thanks.
