### ISSUE TITLE
Add JSS Support

### ISSUE THREAD

**Issue by Patrick-Spiegel** [quasarframework/quasar#3285]
### Problem to solve
When you are using third party components in your  apps, which sandbox your environment with an iframe then you need the ability to control, where quasar renders its style to. 
Quasar currently does not offer you any support for specific component rendering in an iframe. 

### Proposed solution
https://material-ui.com/customization/css-in-js/

In Material UI you have an approach called JSS. That lets you inject style fragments where ever you want. 

    const jss = create({
      ...jssPreset(),
      // We define a custom insertion point that JSS will look for injecting the styles in the DOM.
     insertionPoint: doc.head
    });

jssPreset is provided by mui.

**Comment by nothingismagick** [comment]
"where vuetify renders its style to" - I am a little confused here. Did you copy this issue from another project to see who solves it for you first???

**Comment by Patrick-Spiegel** [comment]
Exactly. Forgot to edit that out :). Anyway none of those frameworks offers it yet.

**Comment by rstoenescu** [comment]
https://vue-loader.vuejs.org/guide/css-modules.html#usage

There you go. Quasar has it.

**Comment by Patrick-Spiegel** [comment]
That is something different.
