### ISSUE TITLE
[v1] QSelect - Autocomplete delete last selected option

### ISSUE THREAD

**Issue by labs20** [quasarframework/quasar#3286]
When implementing autocomplete on the new QSelect, loading data from server, after the first time you choose an option and want to search again, the former selection wont get deleted by backspace and the new search param is placed after it.

![captura de tela 2019-02-12 as 15 22 59](https://user-images.githubusercontent.com/4047789/52855856-cde03380-3109-11e9-9006-cc78e9fa5137.png)

**Comment by rstoenescu** [comment]
Use `hide-selected` prop.
