### ISSUE TITLE
Ability to set Drawer backdrop opacity

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#329]
I do not quite get why this is not a variable, but 'hardcoded':
const backdropOpacity = {mat: 0.7, ios: 0.2}

overhere:
https://github.com/quasarframework/quasar/blob/dev/src/vue-components/drawer/Drawer.vue

**Comment by rstoenescu** [comment]
Care for a PR to add "backdropOpacity" as a prop? It would speed up things.

**Comment by musicformellons** [comment]
Tried... but could not get it workin... sorry.

**Comment by rstoenescu** [comment]
Available in Quasar edge and in next v0.13

**Comment by rstoenescu** [comment]
Implemented through `backdrop-opacity` new prop.

**Comment by oktayaa** [comment]
Was this removed? I can only find it in old documentation.

**Comment by hawkeye64** [comment]
@oktayaa Yes. You  can use `content-class` or `content-style` to achieve this now.
