### ISSUE TITLE
Leak in explanation on how import 'on created' method in new quasar structure

### ISSUE THREAD

**Issue by eeerrrttty** [quasarframework/quasar#3293]
Documentation leaks in explanations on how to import plugins and the folder structure.

Example: I couldn't find ANY information about what 'boot' folder is. Any explanation about older 'plugin' folder was substituted for.

No explanation on how import important things like firebase.

**Comment by nothingismagick** [comment]
Hi, thanks for your comment, unfortunately the word "leak" is incorrect in this context. No worries.

We're working on improving the docs for the beta, and your feedback is greatly appreciated. We know that the v1 docs are really missing the "search" feature, that is coming very, very soon.

Regarding plugins (that we call "boot files"): https://v1.quasar-framework.org/quasar-cli/cli-documentation/boot-files

Regarding "important things" like [firebase obviously](https://github.com/firebase/firebase-js-sdk/issues/1512), please remember that this is beta and there are literally hundreds of things that people are likely to think are "important". Bear with us as we put that stuff together.

If you want to talk with someone from the staff, please join us at discord: https://discord.gg/5TDhbDg
