### ISSUE TITLE
[v1] QBtnToggle - Icon-Text-Margin missing

### ISSUE THREAD

**Issue by enpasos** [quasarframework/quasar#3294]
On a ToggleButton I am missing a margin that used to put a distance between icon and text using class=“q-icon someIcon on-left” with
```
.on-left {
margin-right: 12px;
}
``` 
[ok in [v0.17.19]](https://codepen.io/enpasos/pen/BMPabE)
[not ok in [v1.0.0-beta.0]](https://codepen.io/enpasos/pen/gqjpvm)

**Comment by rstoenescu** [comment]
Fix will be available in beta.3.
