### ISSUE TITLE
[v1] QCarouselSlide cannot handle name="0".

### ISSUE THREAD

**Issue by wvansl** [quasarframework/quasar#3295]
### Software version

Quasar:
V1.beta.1

### Description
What I noticed (and differs from before) is that you need to have a v-model on the carousel property and the slide needs a name property.
But I think the bug is that if the name property = 0 (which you will most likely have when you do a v-for to generate carousel images) and you set your model to slide = 0 then the image doesnt get displayed. Instead you see just 0.

### CodePen
https://codepen.io/wvansl/pen/gqQoEB?&editable=true&editors=101
(Exactly the same as in Quasar docs example but instead of counting from name=1 I changed it from name=0).

**Comment by rstoenescu** [comment]
Fix will be available in beta.3
