### ISSUE TITLE
[v1]QDate - What day of the week is incorrect

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3297]
### Versions and Environment
**Browsers:** Chrome 72.0.3626.96
**OS:** Mac OS 10.14.3
### Reproduction Link
https://v1.quasar-framework.org/vue-components/date

### Steps to reproduce
Choose 2020 and choose any day.
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-date-3.png)

**Comment by rstoenescu** [comment]
Fix will be available in beta.3
