### ISSUE TITLE
QDialog does not accept class attribute

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3299]
### Software version
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.14.1

Global packages
  NPM - 6.4.1
  yarn - Not installed
  @quasar/cli - 1.0.0-beta.0
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.1
  @quasar/app - 1.0.0-beta.2
  @quasar/extras - 1.0.0
  vue - 2.6.4
  vue-router - 3.0.2
  vuex - 3.1.0
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.2.2 
  webpack - 4.29.3

Quasar App Extensions
  *None installed*

### Codepen
https://codepen.io/anon/pen/ZwVzNX

### What did you get as the error?
(a) the backdrop is the usual one and 
(b) no "test" class is added to the main element:
`<div class="q-dialog fullscreen no-pointer-events">`

### What were you expecting?
A red backdrop and a class "test" in the above  div.

In this case I just tried to apply a transparent backdrop so as to have a **modal** dialog with no shading. This is easily achieved by applying the following rule:
.q-dialog__backdrop {
  background-color: transparent
}
However, I couldn't find any elegant way to programmatically choose when I need shading or not. BTW I also tried :class="'test'" with no success.

**Comment by rstoenescu** [comment]
Fix available in beta.3 through new props (`content-class` and `content-style`).
