### ISSUE TITLE
[v1] QSelect v-model show a Object if :options is array of objects rather than the value

### ISSUE THREAD

**Issue by natxocc** [quasarframework/quasar#3300]
### Software version

Quasar: 1.0 beta 2
@quasar/app (v1+ only):
OS: WIndows 10
Node: 10
NPM:
Browsers: Chrome 72

### JsFiddle
https://codepen.io/anon/pen/XOomOG

### What were you expecting?
I think v-model must be the value not the object

**Comment by rstoenescu** [comment]
Hi,

Please take a good look at all the examples. For some cases you need the model to be the Object itself (like if you use selection slots, but not limited to it) and for some you don't (for the latter, see `emit-value` and `map-options`). For best render performance, avoid `map-options` (and 'emit-value' as a consequence) and just use a subprop of the model (that holds the value) wherever you need to use what the user has selected.

Remember that `options` can also be an array of Strings... again, take a look at the examples in doc.

If you need help, we welcome you on our Discord server. But read docs first and also notice the QSelect API section.

-Razvan
