### ISSUE TITLE
How to set own alias

### ISSUE THREAD

**Issue by liub1934** [quasarframework/quasar#3306]
I used this,it not work

```
extendWebpack (cfg) {
    cfg.resolve.alias = {
      ...cfg.resolve.alias, // This adds the existing alias

      // Add your own alias like this
      '@': path.resolve(__dirname, './src'),
    }
  }
```
I used
```
import { getTopics } from '@/api/index.js'
```
And the Error
![image](https://user-images.githubusercontent.com/29849550/52938944-e6687c00-339d-11e9-8caa-ddf1b1e4d11b.png)

**Comment by rstoenescu** [comment]
Hi,

1. Don't use '@' as alias because that is always problematic with webpack due to the npm organization packages which start with '@'.
2. There's already the `src` alias that points to what you want (`import { getTopics } from 'src/api/index.js'`)

**Comment by liub1934** [comment]
> Hi,
> 
> 1. Don't use '@' as alias because that is always problematic with webpack due to the npm organization packages which start with '@'.
> 2. There's already the `src` alias that points to what you want (`import { getTopics } from 'src/api/index.js'`)

Thanks

**Comment by rstoenescu** [comment]
Full list of aliases: https://v1.quasar-framework.org/quasar-cli/cli-documentation/handling-webpack#Webpack-Aliases
