### ISSUE TITLE
V1: Qstep with :disable='false' will reset the stepper to step1 when next is triggered.

### ISSUE THREAD

**Issue by paulvanbladel** [quasarframework/quasar#3307]
Note, setting :disable on a QStep works fine. It only fails when the :disable prop is set via code or directly :disable='false'

What i see happing is that the panelIndex prop of the QStepper goes to -1 when the :disable='false' prop is encountered.

The problem occurs when the next step is triggered after the step that has the :disable='false' prop.

**Comment by rstoenescu** [comment]
Any jsfiddle or codepen pls? The devil is in the details. Trying to accurately understand your scenario.

**Comment by rstoenescu** [comment]
Nevermind. Figured it out. :) Will push a fix for beta.3.
Thanks for reporting!

**Comment by rstoenescu** [comment]
Fix will be available in beta.3.

**Comment by paulvanbladel** [comment]
@rstoenescu Thanks a lot. I'll make sure to report potential future issues with a JsFiddle. Nothing worsers than an unclear error report :)
