### ISSUE TITLE
[v1] Dialog docs, maximized demo breaks page if closed after minimizing

### ISSUE THREAD

**Issue by carlfarrington** [quasarframework/quasar#3310]
This may just relate to the docs, rather than the QDialog component itself.

If you open up the 'maximized' demo (https://v1.quasar-framework.org/vue-components/dialog#Example--Maximized ).
Then minimize it (then it becomes a normal dialog in the middle of the window).
Then close it.
The page is no longer scrollable.

**Comment by rstoenescu** [comment]
Fix will be available on beta.3.
