### ISSUE TITLE
[0.15] Quasar cannot run on android lower than 7.0.0 

### ISSUE THREAD

**Issue by channimol** [quasarframework/quasar#3312]
I dont know if anyone happen to have the same problem. android which has lower version than 7.0.0 return blank screen when I run.
I use: 

In root-project/package.json
"quasar-cli": "^0.15.20",

In src-cordova/package.json
"license": "Apache-2.0"
"cordova-android": "^7.0.0"

could anyone tell me the problem and how to let lower versions can run the app?

**Comment by rstoenescu** [comment]
Hi, Have you used remote debugging to determine what the problem is with your app? Join our Discord channel for help.
