### ISSUE TITLE
[v1] q-input does not work with vue.min.js

### ISSUE THREAD

**Issue by tanthammar** [quasarframework/quasar#3313]
https://codepen.io/anon/pen/NooBmp?editors=1111

q-input renders blank page and "object-error" when using minified version of Vue js.
###  **vue.min.js**
If I use the dev version, **vue.js**, it works.

Tried with and without self-closing tag.

**Comment by rstoenescu** [comment]
The codepen seems wrong in the first place. You're using a model which isn't declared.

```
data: function () {
    return {
      text: '', // <<<<<<<<<<<<< add it
      version: Quasar.version
    }
  }
```

**Comment by tanthammar** [comment]
Stupid me,
missed to return text: ''
