### ISSUE TITLE
[v1] q-select multiple with chips doesn't lock disabled entries

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3314]
As you can see in this [codepen](https://codepen.io/willypuzzle/pen/vbVvrj) the selected item is disabled but it is not locked. I can click on the x of the chips to remove it from the select. This differs from the behaviour that this kind of select had in precedent versions. I think is more useful make the chips locked when they are disabled or maybe add some option relative to it.

**Comment by rstoenescu** [comment]
Fix will be available in beta.3
