### ISSUE TITLE
[v1] Implement @focus as a "common" event

### ISSUE THREAD

**Issue by labs20** [quasarframework/quasar#3317]
### What did you get as the error?
The lack of `@focus` event on many components

### What were you expecting?
To be able to listen `@focus` at very least on any "form" component, but ideally on every one. 

And some components like `q-option-group` or `q-btn-toggle` should fire two events `@focus` (only once when arriving at the component) and `@focus-item` (at individual inside focus change)

**Comment by pdanpdan** [comment]
The QInput emits vue type `focus` event. The other form elements should emit the native `focus` event, so you can listen on them with `onNative` in render functions or with `on.native` in templates.

Do you have a specific example for where it's not working?
If you have please add a codepen with what is not working.

Thank you.

**Comment by labs20** [comment]
Hi!

Well, I need to catch "on focus" on QSelect, on QExpansionItem, on QBtnGroup, QBtn... and so on and on with all the rest...

Maybe I'm doing something wrong but neither
`q-select(@focus="myHandler")` nor `q-select(@focus.native="myHandler")` did the trick. 

Not to mention QExpansionItem and others.

If my end user uses the tab key and end up in some comp (and by that I meant his perception of a comp as displayed by its layout), I should be able to listen to a "focus" event to do my things about it.

**Comment by pdanpdan** [comment]
Please create a codepen with something you want to do and we'll try to help.

**Comment by labs20** [comment]
Here: https://codepen.io/labs20/pen/YBbxGg

Please note that I do not put every comp on that pen, just a few to give you the idea, ok?

Thanks

**Comment by nothingismagick** [comment]
nice codepen - that helps understand

**Comment by pdanpdan** [comment]
I made a few enhancements (added native): https://codepen.io/anon/pen/jdoGzv

Please add elements that you find are not working.

For the moment it's:
- QSelect
- QExpansionItem

I'll also look at the codebase and try to add focus events emitting where required.

**Comment by labs20** [comment]
Hi, ok! 

Well, while on this matter, I'd like to call attention to [this conversation](https://forum.quasar-framework.org/topic/3158/v1-events-context-acessing-the-component-itself-inside-event-handler) as it is somewhat related and I think very pertinent.

Thanks

**Comment by pdanpdan** [comment]
I've made some enhancements: https://codepen.io/anon/pen/jdoGzv?editors=1010

By combining `@focusin.native`, `@focusout.native`, `@focus`, and `@blur` you can get info about all elements (that I tested).

**Comment by labs20** [comment]
Right! Well done. 

This means that as it is, it's already possible to achieve focus awareness. 

I think a good step forward would be encapsulate those mixed ways in a standard quasar level focus event. Maybe even bring together my suggestion at the post above about add a last default parameter on every event handler call, passing the emitter of the event to the handler. 

Thanks!
