### ISSUE TITLE
DialogSelect component errors out with Number as option value

### ISSUE THREAD

**Issue by alexey2baranov** [quasarframework/quasar#332]
I tryed to test q-dialog-select, copy paste simple code from manual except initial select=undefined and get this errors

> Uncaught TypeError: Cannot read property 'includes' of null
>     at eval (eval at <anonymous> (http://localhost:8080/js/app.js:1498:1), <anonymous>:6663:30)
>     at Array.map (native)
>     at VueComponent.pick (eval at <anonymous> (http://localhost:8080/js/app.js:1498:1), <anonymous>:6659:34)
>     at Object.click [as fn] (eval at <anonymous> (http://localhost:8080/js/app.js:1498:1), <anonymous>:6588:15)
>     at HTMLDivElement.eval (eval at <anonymous> (http://localhost:8080/js/app.js:730:1), <anonymous>:2229:16)

And more it throws error when option.value of integer (not string) type
> at eval (eval at <anonymous> (http://localhost:8080/js/app.js:1498:1), <anonymous>:6663:31)
>     at Array.map (native)
>     at VueComponent.pick (eval at <anonymous> (http://localhost:8080/js/app.js:1498:1), <anonymous>:6659:34)
>     at Object.click [as fn] (eval at <anonymous> (http://localhost:8080/js/app.js:1498:1), <anonymous>:6588:15)
>     at HTMLDivElement.eval (eval at <anonymous> (http://localhost:8080/js/app.js:730:1), <anonymous>:2229:16)
> (anonymous) @ quasar.common.js?e3df:6663
> pick @ quasar.common.js?e3df:6659
> click @ quasar.common.js?e3df:6588
> (anonymous) @ vue.runtime.common.js?d43f:2229

**Comment by rstoenescu** [comment]
Thanks for reporting. Will fix this.

**Comment by rstoenescu** [comment]
Fixed the Number issue.

As for the first one, you can't use `undefined` as v-model value. You need to bind it to an actual scope variable. Using empty string is a way to make the component not select anything by default, since empty string is different than any option value.
