### ISSUE TITLE
Wrong logic of infinite scroll

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#3322]
Hello,

The fact that the container must already be overflowing for the component to start working is an issue.

For example I have 20 items in my container. On a phone, they overflow the container, so the infinite scroll starts working fine. On a tablet with a bigger screen, the 20 items are not big enough to overflow the container, so the component does not start working. Am I supposed to make calculations myself and load enough items before initializing Infinite Scroll?

I think the logic should rather be: start working even if the container is empty, until the container is overflowing with enough offset.

This brings me to my second remark: we should be able to say which is the scrolling container.
The fact that the component requires the scrolling container to be overflowing AND to have the `scroll` class is a double issue. In my case, I use infinite scroll on a container which is provided by another component, so I cannot easily add the class. I'd rather give a Vue `ref` to Infinite Scroll rather than let it guess (wrong).

Thank you

**Comment by pdanpdan** [comment]
For the first part that's the way it's implemented - are we talking v0.17 or v1.beta?
Can you please try v1 and if you encounter the same problem please make a codepen from docs (https://v1.quasar-framework.org/) showing the problem?

For the second part (the scroll container) it looks for the closest parent that has one of `.scroll`, `.scroll-y`, or `.overflow-auto`.

Maybe it would be an idea to add a way to specify it.

**Comment by louisameline** [comment]
Great thank you I will switch to v1 and give feedback.

**Comment by louisameline** [comment]
What's the recommended way to switch to v1 please? I can't find the info.

**Comment by nothingismagick** [comment]
The recommended way is to do a step-by-step import of 0.17 project pieces
into a freshly created 1.0 project. Upgrading in place is likely to be
frustrating. We will be announcing the guide with complete cross-reference
and steps for the bold in the next several days.

**Comment by louisameline** [comment]
I'll definitely upgrade my project to v1, I'll wait for instructions then. Thank you.

**Comment by rstoenescu** [comment]
Will be available in beta.10
