### ISSUE TITLE
[v1]QDate - Two buttons overlap

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3324]
### Versions and Environment
**Browsers:** Chrome 72.0.3626.96
**OS:** Mac OS 10.14.3
### Reproduction Link
https://v1.quasar-framework.org/vue-components/date
### Steps to reproduce
1.Choose 2020
2.Open the Year Selection View again
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-date-9.png)

**Comment by rstoenescu** [comment]
Fix will be available in beta.4
