### ISSUE TITLE
[v1] [Win + IDEA] CLI behaviour changes depending on where you start the terminal

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#3328]
Just putting this here so we can track it, I will do more exploration.

IDEA starts the CMD/Powershell in the project folder. `quasar info` shows `@quasar/cli` as `undefined`.

![image](https://user-images.githubusercontent.com/25121817/53082024-52f98d00-34fc-11e9-90ab-20f90b25e4c3.png)

If you then go outside the folder, Local CLI is used instead. `quasar` shows:
![image](https://user-images.githubusercontent.com/25121817/53082150-8b00d000-34fc-11e9-908e-7236ec4a440c.png)

And `quasar info`:
![image](https://user-images.githubusercontent.com/25121817/53082248-bc799b80-34fc-11e9-9d70-68c36e4fff27.png)

If you start the CMD/Powershell in v17 project folder, local CLI is used from that project and you can't run new commands in other projects.

This is because in IDEA, you have a setting:
![image](https://user-images.githubusercontent.com/25121817/53082590-783acb00-34fd-11e9-9da8-6d28671171e2.png)

This means that your local CLI is added to the path and used during the whole session. If you turn it off, it works.

I am not sure if the CLI should somehow deal with this, or we just instruct users to turn the setting off, which is a not too great as it worked out of the box before.

**Comment by rstoenescu** [comment]
Hi @panstromek 

Any updates on this? Is there something we can do to better the developer's experience with this IDE?

**Comment by panstromek** [comment]
I turned off that setting and never had a problem after that, so maybe just a notice in the docs would be cool - it's a minor problem anyway and I've never seen anyone reporting it. 

I suspect this was a hidden problem even before 1.0 but just showed up when the cli's got more separated.

**Comment by rstoenescu** [comment]
Care to add a warning on docs? @panstromek

**Comment by rstoenescu** [comment]
Will close this, but thanks for pointing it out. Let me know if you got a bit of time for the PR. Would appreciate it.

**Comment by panstromek** [comment]
ok ;) np
