### ISSUE TITLE
[v1] drawer overlaps toolbar, wrong shadow

### ISSUE THREAD

**Issue by lucasfernog** [quasarframework/quasar#3331]
### Software version
Global packages
  NPM                   6.4.1
  yarn                  1.12.3
  @quasar/cli           1.0.0-beta.0

Quasar:
@quasar/app (v1+ only): v1.0.0-beta.7
OS: Windows_NT(10.0.17763) - win32/x64
Node: 11.4.0
NPM: 6.4.1
Browsers: Chrome 72.0.3626.109

### JsFiddle
https://github.com/hawkeye64/quasar-layouts/

### What did you get as the error?

Drawer overlapping toolbar's shadow

### What were you expecting?

The toolbar shadow to present full width

### What steps did you take, to get the error?

Just try out https://github.com/hawkeye64/quasar-layouts and check google news layout

![screenshot_1](https://user-images.githubusercontent.com/20051258/53114827-74ba3a80-3523-11e9-917a-5f268207e696.png)

**Comment by rstoenescu** [comment]
Shadow must be applied to drawer too (elevated prop).

**Comment by nothingismagick** [comment]
@lucasfernog 

![screen shot 2019-02-20 at 19 28 34](https://user-images.githubusercontent.com/35242872/53115175-d25f7e80-3545-11e9-82fb-1597ad7def98.png)

Why didn't you post this there at that repo?
