### ISSUE TITLE
[v1] drawer hover effect overlap scrollbar

### ISSUE THREAD

**Issue by lucasfernog** [quasarframework/quasar#3332]
### Software version
Quasar current docs

### JsFiddle
https://v1.quasar-framework.org/introduction-to-quasar

### What did you get as the error?

Drawer hover effect overlapping scrollbar

### What were you expecting?

The hover effect end before the scrollbar

### What steps did you take, to get the error?

Just try out https://v1.quasar-framework.org/introduction-to-quasar and hover a drawer item with scrollbar visible
![screenshot_3](https://user-images.githubusercontent.com/20051258/53115069-fca04480-3523-11e9-9ad2-96732460857d.png)

**Comment by smolinari** [comment]
Is this really a problem? I see it as the scroll bar being opaque, which it is. 😄 

![image](https://user-images.githubusercontent.com/3314957/53149679-ae845300-35ae-11e9-9325-3d4b255e8783.png)

Scott
