### ISSUE TITLE
[V1] Get Crossbrowser CSS Transform Property

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3335]
I used this helper function of Quasar 0.17 all the time:
[Get Crossbrowser CSS Transform Property](https://quasar-framework.org/components/dom-utils.html#Get-Crossbrowser-CSS-Transform-Property).

I would love to have it back in V1, as it's gone! : D

**Comment by pdanpdan** [comment]
```javascript
const prefix = ['-webkit-', '-moz-', '-ms-', '-o-']
export function cssTransform (val) {
  let o = {transform: val}
  prefix.forEach(p => {
    o[p + 'transform'] = val
  })
  return o
}
```

**Comment by rstoenescu** [comment]
Btw, u don't need it anymore, which is why it's been removed anyway.

**Comment by mesqueeb** [comment]
@rstoenescu Why don't I need it anymore?

**Comment by rstoenescu** [comment]
No prefixes needed now: https://caniuse.com/#search=transform
