### ISSUE TITLE
[V1] BUG: dropdown default value doesn't show label

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3336]
See codepen:
https://codepen.io/mesqueeb/pen/vbwYbQ

**Comment by pdanpdan** [comment]
https://codepen.io/anon/pen/gqJbQr

If your model is the value and the options have objects then you need to use `map-options`.
If your options have objects and you want to have just the value in model then use `emit-value`.

I put in the pen the 3 most common use cases.

**Comment by mesqueeb** [comment]
@pdanpdan Thanks a lot!!!
