### ISSUE TITLE
[V1] Label of QSlider does not always provide full content

### ISSUE THREAD

**Issue by paulvanbladel** [quasarframework/quasar#3337]
I have a slider going op to 10000
When 9537:
![image](https://user-images.githubusercontent.com/4886272/53154861-fe1d4b80-35bb-11e9-98e5-1f89a1cf7636.png)

When: 10000
![image](https://user-images.githubusercontent.com/4886272/53154830-ef369900-35bb-11e9-9e61-9facdfde2f70.png)

**Comment by rstoenescu** [comment]
Fix will be available in beta.11
