### ISSUE TITLE
[v1] Float label overlaps with browsers autocomplete

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#3338]
Happens on the page load if you have saved credentials.

![image](https://user-images.githubusercontent.com/25121817/53154549-5a33a000-35bb-11e9-8b22-0c7d54cfe21e.png)

I tried to repliacate it in the pen but it's pretty hard, so try this: https://codepen.io/anon/pen/gqJaBE?&editable=true&editors=101

fill in something, press enter, browser ask if you want to save the credentials, hit yes, and reload the page. Browser should autocomplete them.

This only happens under some circumstances, not sure when - but if I just click on the page anywhere, float labels correctly floats away. In other cases it does so automatically after load.

**Comment by thugic** [comment]
Yeah, same here.

Also, if you use the Chrome autofill feature, the pale-yellow background overflows borders on outlined q-input.

Here's a screenshot.

![blurrred](https://user-images.githubusercontent.com/22091704/53167280-cae8b580-35d7-11e9-9c1e-33eb97d7eea6.png)

A solution to my issue was using this CSS, though I have tested only on Chrome/Linux:

`
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus
textarea:-webkit-autofill,
textarea:-webkit-autofill:hover
textarea:-webkit-autofill:focus {
  -webkit-text-fill-color: green;
  transition: background-color 5000s ease-in-out 0s;
}
`

**Comment by rstoenescu** [comment]
Fix will be available in beta.4.

For the area that gets yellow there's no generic fix at the moment and it needs custom CSS like yours. The input is not overflowed -- that's actually the area that it occupies.
