### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#3340]
This might be a good idea.

[This package](https://www.jsdelivr.com/package/npm/quasar) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by rstoenescu** [comment]
"module" is sufficient. No reason to add the others.

**Comment by nothingismagick** [comment]
https://www.jsdelivr.com/package/npm/quasar
![screen shot 2019-02-21 at 10 29 56](https://user-images.githubusercontent.com/35242872/53158351-ab479200-35c3-11e9-8de9-0a999314f078.png)

**Comment by rstoenescu** [comment]
So? They don't know how it's used.
