### ISSUE TITLE
[Modal] a workaround to programmatically open custom modal

### ISSUE THREAD

**Issue by sandrotaje** [quasarframework/quasar#3343]
Hello,

i've created a workaround to open programmatically a custom modal.

I've created a mixin that open the modal 
```javascript
Vue.mixin({
      methods: {
        $openModal(props, component) {
          let Modal = Vue.extend(component);
          let instance = new Modal({
            i18n,
            propsData: props
          });
          instance.$mount();
          this.$el.appendChild(instance.$el);
          instance.$children[0].show();
          instance.$on("hide", () => {
            instance.$el.remove();
          });
          return instance;
        }
      }
    });
```

In this way you can, in the component that use modal, listen on javascript code the event, and if you are in a loop, change directly the model you pass.

```javascript
import ModalComponent from "where is modal component";

openModal(w) {
      this.$openModal({prop1: "hello"}, ModalComponent)
        .$on("save", (data) => {
          console.log(data);
        });

    }

```

i18n is passed because if not you cannot use translation inside modal.
So in this way you can open custom modal.

I hope that a similar thing will be added in the Quasar API.

Thanks for the excellent job.

**Comment by stefanvanherwijnen** [comment]
Isn't programmatically opening a modal as simple as setting the opened prop to true?

**Comment by sandrotaje** [comment]
Yes, for sure, but if you are inside a loop, is more convenient, in my opinion, to open in this way. 

Because, in a loop, you have to use a internal variable to set the selected thing to pass inside the modal and that manage the return from the modal( if for example in the modal you modify something) and is easier in this way.

**Comment by hawkeye64** [comment]
This feels as if it was added to the wrong repo.

**Comment by rstoenescu** [comment]
Hi,

This has been suggested in another ticket too. Can't find it at the moment but I am sure of it. Closing this. It will get implemented.

**Comment by rstoenescu** [comment]
Here's the other ticket: https://github.com/quasarframework/quasar/issues/3289
