### ISSUE TITLE
[v1] State not retained between QCarousel, QStepper and QTabPanel

### ISSUE THREAD

**Issue by uberpu** [quasarframework/quasar#3345]
Prior to 1.3 a QCarousel, QStepper and QTabPanel all would hide thier content. It seems to be re-rendering for each panel/frame now

**Comment by pdanpdan** [comment]
If you want to keep state wrap the panels in `keep-alive` (https://vuejs.org/v2/api/#keep-alive).

**Comment by uberpu** [comment]
Happens on the keep alive as well

https://codepen.io/uberpu/pen/qvZKVd

**Comment by uberpu** [comment]
Sooo... nothing?

**Comment by pdanpdan** [comment]
Sorry, I forgot about this. I'll take a look tomorrow morning.

**Comment by uberpu** [comment]
Thx

**Comment by pdanpdan** [comment]
I looked into the problem and I'm sorry to say that keep-alive is not going to work.
For the normal situations it's easy to keep state (use store), but for the specific issue of input file you will not be able to refill the list.
Please leave this open and if we can think of something we'll post here.

**Comment by uberpu** [comment]
@pdanpdan .. thanks for keeping this alive. I know this is a tough one, considering the philosophy of Vue 2 (~em`allandletdeveloperssortitout), which eliminates the consideration of latency to simplify the narrative in the virtual DOM. 
Did you find anything workable?

**Comment by rstoenescu** [comment]
Added a new prop (Boolean) for QCarousel/QTabPanels/QStepper: `keep-alive`.
Will be available in beta.22.
