### ISSUE TITLE
[Feature Request] Gauge component

### ISSUE THREAD

**Issue by srsalute** [quasarframework/quasar#3346]
Feature suggestion/request
=======================
--> What about a gauge component? i see that have knob component, but knob is a input form, i dont know if is a good way use knob as a gauge. 

some gauges from https://framework7.io/vue/gauge.html
![gauge](https://user-images.githubusercontent.com/14018087/53181641-b526c080-35d6-11e9-8647-e9e702ff0fac.PNG)

**Comment by pdanpdan** [comment]
You can use:

- Knob with readonly (https://v1.quasar-framework.org/vue-components/knob)
- CircularProgress (https://v1.quasar-framework.org/vue-components/circular-progress)
