### ISSUE TITLE
[v1] Date is not properly formatted  on selection when using defaultYearMonth with an empty model

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#3348]
### Software version

Quasar:  1.0.0-beta.3 

### JsFiddle
https://codepen.io/stefanvh/pen/exaQag

### What did you get as the error?
An extra 0 is added to the month when the first date is selected on an empty model. Any subsequent selections seem to work fine.
### What steps did you take, to get the error?
Select a date on the datepicker in the codepen. It results in "1964/008/08" for example.

**Comment by rstoenescu** [comment]
Fix will be available in beta.5
