### ISSUE TITLE
stacked-label with q-dialog-select seems ugly

### ISSUE THREAD

**Issue by alexey2baranov** [quasarframework/quasar#335]
```html
    <div class="stacked-label">
      <q-dialog-select type="radio"  class="full-width" v-model="model.ADDRESS.TOWN" :options="model.towns" ok-label="OK"
                       cancel-label="Отмена" title="Ваш населенный пункт" @input="town_input"></q-dialog-select>
      <label>some label</label>
    </div>
```

**Comment by rstoenescu** [comment]
Stacked label is not meant to be used with Dialog Select component. You got a lot of options built into the component itself (placeholder, label etc). Please read the docs.

**Comment by alexey2baranov** [comment]
I see. It would be good if you add stacked-label for Dialog Select in the future to have unique UI across all  component.

**Comment by rstoenescu** [comment]
It's on the works.
