### ISSUE TITLE
QChatMessage Can this component add an avatar click event?

### ISSUE THREAD

**Issue by BysunLin** [quasarframework/quasar#3351]
QChatMessage

Currently, you can only add events to the slot. You can't add an avatar click event. Can the author consider adding it?

**Comment by hawkeye64** [comment]
You mean like this: https://codepen.io/Hawkeye64/pen/BbBLGg

**Comment by BysunLin** [comment]
Yes, great, this is exactly what I need, maybe I should refer this part of the code to the quasar documentation.
