### ISSUE TITLE
[v1]QDate - the transition effect seems to be a little slow

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3352]
When you change the year, the transition effect seems to be a little slow, do you have this feeling? In addition, when testing on my mobile phone, I can clearly see the blank when switching.
```
  &--slide-right,
  &--slide-left,
  &--slide-up,
  &--slide-down

    &-enter-active, &-leave-active
      transition transform .6s cubic-bezier(.86, 0, .07, 1)
```
When I changed 0.6 to a smaller value, or removed the transition effect, it performed much better on the phone.

**Comment by rstoenescu** [comment]
It's not a matter of "performaning"/"performance". It's just timing transitions to be faster.
Which will be available in beta.11
