### ISSUE TITLE
[v1]QScrollArea - When the scrollbar is hidden, the cursor effect should not take effect

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3353]
When the scrollbar is hidden（ .q-scrollarea__thumb--invisible { opacity: 0!important;}）, the cursor effect still works（grab  and grabbing ）
https://codepen.io/qq34205037/pen/ZwdWYo

**Comment by rstoenescu** [comment]
Fix will be available in beta.5.
