### ISSUE TITLE
[v1] QSelect options covering the Input

### ISSUE THREAD

**Issue by burningTyger** [quasarframework/quasar#3358]
### Software version

Operating System - Linux(4.20.7-arch1-1-ARCH) - linux/x64
NodeJs - 11.9.0

Global packages
  NPM - 6.8.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.0
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.7 -- Quasar Framework App CLI
  @quasar/extras - 1.0.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.6 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - 3.1.4 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 13.1.0 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @babel/core - 7.2.2 -- Babel compiler core.
  webpack - 4.29.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.1.14 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### JsFiddle
can't reproduce in Fiddle or Codepen. I tried.
https://github.com/schild-report/schild.report/blob/master/src/layouts/default.vue#L9

### What did you get as the error?
The options upon entering the first letters start covering the input field.
The options div is not styled with `top: 100%`.
Entering a more letters adds the necessary style.
![image](https://user-images.githubusercontent.com/263378/53229154-c7126d00-3683-11e9-8043-9ffc3b2c929c.png)

### What were you expecting?
The options div never covers the input
![image](https://user-images.githubusercontent.com/263378/53229108-9b8f8280-3683-11e9-8f91-57cf7377f38a.png)

### What steps did you take, to get the error?
is this related to me using the `update()` function asynchronically?

**Comment by panstromek** [comment]
Have you tried using `expand-besides` prop?

**Comment by rstoenescu** [comment]
Fix will be available in beta.14

**Comment by rstoenescu** [comment]
Delaying this a bit. Not yet "production ready". Didn't went into beta.14.

**Comment by rstoenescu** [comment]
Please follow https://github.com/quasarframework/quasar/issues/3242 for updates.
