### ISSUE TITLE
q-dialog-select: options not related to data when dialog opened

### ISSUE THREAD

**Issue by alexey2baranov** [quasarframework/quasar#336]
Let imagine client open q-dialog-select when options are fetching from server. At this moment dialog is empty. 

Next moment options fetching finished. I expect to see this options in opened dialog but they are not appear. Client need to reopen q-dialog-select one more time to see them.

Another issue is when client open q-dialog-select with options and they are changed by another thread. if options are not related to data, client will see broken options set.

**Comment by alexey2baranov** [comment]
in clear html 

```html
<select >
 <option v-for="option in options" :value='option.value' :label='option.label'>
</option>
</select>
```

will works as expected

**Comment by rstoenescu** [comment]
For reactive data use Select component instead.
