### ISSUE TITLE
[feature request][v1] Use the new hook `serverPrefech` in vue v2.6 to enhance ssr

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#3360]
Currently Quasar provides a prefetch option which is normally used for prefetching data for **route components** when doing SSR. 

Vue 2.6+ provides a new hook `serverprefetch` which can be used for prefetching data in **ANY** components (even non-route components) during SSR. (https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components)

Any considerations to use this new hook to enable ssr prefetching for all components? `vue-apollo` has already done this in its newest beta.

**Comment by rstoenescu** [comment]
You can freely use this in v1 as we are keeping up with latest Vue versions through `@quasar/app`. However, note that Quasar's `preFetch` is still more powerful than than Vue's own version.

**Comment by Hamedamz** [comment]
How to use Quasar's `preFetch` inside mixins?

**Comment by GregorioLopezO** [comment]
> How to use Quasar's `preFetch` inside mixins?

Hi, Hamedamz.

Did you find the solution for adding common funcionality to the `preFecht `hook of several route components?
