### ISSUE TITLE
[v1][bug] long label/caption breaks QExpansionItem

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#3361]
### Software version

Quasar: v1.0.0-beta4
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers: Chrome/Firefox
iOS:
Android:
Any other software related to your bug:

### JsFiddle

https://codepen.io/anon/pen/OdewWZ

### What did you get as the error?

![image](https://user-images.githubusercontent.com/13058150/53250427-53a94380-36f5-11e9-8dc0-dfbc1f9c5ae9.png)

### What were you expecting?

Should have something like `ellipsis` in CSS, or quasar-provided 1-line/2-line ellipsis class.

**Comment by rstoenescu** [comment]
Fix will be available in beta.5
