### ISSUE TITLE
[v1] QUploader upload raw file like in #1133

### ISSUE THREAD

**Issue by martinflorek** [quasarframework/quasar#3362]
I am migrating to v1.0.0 and I am stuck on uploading a raw file to Amazon S3, which was possible in v0.17 via the `send-raw` property. I tried setting the `Content-Type` header which changes the content type but still sends the data as multipart. I checked the `uploader-xhr-mixin.js` source code and it always creates and sends a form.

Can you add the `send-raw` property into v1.0 please, like in the issue #1133? Thank you.

**Comment by rstoenescu** [comment]
Will be available in beta.5. Thanks for reporting!
