### ISSUE TITLE
Pug is not working on Quasar 1.0

### ISSUE THREAD

**Issue by LuisEnMarroquin** [quasarframework/quasar#3364]
### Software version

Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          10.12.0
Global packages
  NPM                           6.4.1
  yarn                          1.13.0
  @quasar/cli                   1.0.0-beta.2
  cordova                       You have been opted out of telemetry. 

### Issue 

Can't install packages pug and pug-plain-loader

### Steps to reproduce

```shell
yarn add --dev pug pug-plain-loader
```

### Error

Trace: 
  Error: EPERM: operation not permitted, scandir 'C:\Users\myself\Pictures\cms-frontend\node_modules\@types'

yarn add v1.13.0
warning ..\..\package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info idb-connector@1.1.8: The platform "win32" is incompatible with this module.
info "idb-connector@1.1.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@quasar/app > babel-loader@8.0.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@quasar/app > webpack > ajv-keywords@3.4.0" has incorrect peer dependency "ajv@^6.9.1".
error An unexpected error occurred: "EPERM: operation not permitted, scandir 'C:\\Users\\myself\\Pictures\\cms-frontend\\node_mod
ules\\@types'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\myself\\Pictures\\cms-fron
tend\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by pdanpdan** [comment]
This has nothing to do with quasar. It's related to Windows permissions and intermittent and random errors with npm and/or yarn.
