### ISSUE TITLE
viewing the beta docs on IOS the menu doesn't work.   

### ISSUE THREAD

**Issue by Jeremywhiteley** [quasarframework/quasar#3367]
Steps to reproduce.   

On IOS iPhone 10 running the latest IOS, when viewing the beta docs at this web address.   The menu doesn't work.   I have the same exact issue on my iPad mini as well.   

Go here on the IPhone.   https://v1.quasar-framework.org/start/pick-quasar-flavour

Then click on the menu button at the top.   Then click on Style & Identify.   

Then the menu on the IPhone goes blank. You can't access any of the sub menu's.   

It does work just fine with Safari on My iMac, even when I make the screen small like an iPhone.  Just not on the actual iPhone or Ipad.   I did clear the cache on my iPhone as well.    

![unknown](https://user-images.githubusercontent.com/1545134/53276905-6ce2cd80-36be-11e9-8aaf-3d19adbb4c1e.jpeg)

**Comment by hawkeye64** [comment]
Is this an emulator? Working on latest iOS, on real hardware, for me.

**Comment by hawkeye64** [comment]
https://cdn.discordapp.com/attachments/549346505132343309/549346644387168276/image0.png

**Comment by Jeremywhiteley** [comment]
No, it's not an emulator.  It's doing it on two different iPhones and a Ipad mini.   All three are running the latest beta of 12.2.   Attached is a video of the behavior.    

[IMG_9740.mov.zip](https://github.com/quasarframework/quasar/files/2898435/IMG_9740.mov.zip)

**Comment by smolinari** [comment]
I have an iPhone 6 and it works perfectly. My wife has an iPad mini. Works perfectly. I have an old iPad, works perfectly. 

Strange.... 🤷‍♂️ 

Scott

**Comment by Jeremywhiteley** [comment]
Oh well.

**Comment by pdanpdan** [comment]
Can anyone test it in a safari with tabs? It might be related to this.

**Comment by nothingismagick** [comment]
On iPad with iOSv11.4.11 using Safari, Chrome or Firefox this does not
happen.

**Comment by smolinari** [comment]
@pdanpdan - What do you mean by "with tabs"?

Scott

**Comment by pdanpdan** [comment]
In the video it looks like safari has tabs on top (browser tabs).

**Comment by smolinari** [comment]
Ah. Ok. I could have guessed that. I had tabs on my wife's iPad mini. My iPad and my iPhone didn't. Just tested my iPhone 6 with web sites in other tabs. No issues either. 

Scott

**Comment by Jeremywhiteley** [comment]
It does it both on my iPhone X and iPad Mini version 3.  Both are running the latest public beta of IOS 12.2.  It’s important to test on the latest versions.  

This might help 

https://link.medium.com/UMf3NMmAEU

**Comment by pdanpdan** [comment]
@Jeremywhiteley Can you please do some inspection in the console and report if you have errors/warnings. Also inspect the menu and try to find out what looks wrong.

Thank you for helping us with this beta version of IOS.

**Comment by Jeremywhiteley** [comment]
I can't even get the web inspector to work with IOS 12.2 on my iMac.  However I just tested it on an iPhone 6s running IOS 12.1.2. So I think the issue is with IOS 12.2 beta.    I will look at it later today.   

I say just keep your eyes out on this issue but don't make it a bit priority. There must be something wrong with IOS 12.2 since web inspector isn't working.
