### ISSUE TITLE
input: floating-label not works when input is not required

### ISSUE THREAD

**Issue by alexey2baranov** [quasarframework/quasar#337]
this code from example works
```html
    <div class="floating-label">
      <input required class="full-width" >
      <label>Номер квартиры</label>
    </div>
```

this not
```html
    <div class="floating-label">
      <input class="full-width" >
      <label>Номер квартиры</label>
    </div>
```

**Comment by rstoenescu** [comment]
It is supposed to have `required` prop. Otherwise CSS won't work. This is a CSS based solution for performance reasons and to avoid overhead of a component.

**Comment by alexey2baranov** [comment]
you should point about required into documentation

**Comment by rstoenescu** [comment]
The example has the `required` prop there. Will probably put a notice too.
