### ISSUE TITLE
How can I handle position of Popover from QSelect? 

### ISSUE THREAD

**Issue by Younghun-Jung** [quasarframework/quasar#3370]
### Software version

Quasar: v0.17.19
@quasar/app (v1+ only):
OS: macOS Mojave
Node: v8.12.0
NPM: 6.4.1
Browsers: Chrome

### What were you expecting?
I use QSelect component on my project.
How can I set position of popover shown by clicking or tapping input field?

Default case is that popover is located on input field (overlap).
So, Can I handle css property 'top' of 'q-popover' ?

**current**
![2019-02-23 8 53 08](https://user-images.githubusercontent.com/19387972/53286121-20c28680-37ad-11e9-82f3-7e3fed4c99e1.png)

**I need**
![2019-02-23 8 53 24](https://user-images.githubusercontent.com/19387972/53286128-28822b00-37ad-11e9-81e1-50dc09eeb6a7.png)

Is there any option of QSelect?

**Comment by panstromek** [comment]
There is an option `expand-besides` in 1.0 version, which does exactly that..
