### ISSUE TITLE
q-input counter displays number 4 when the model is null

### ISSUE THREAD

**Issue by 123mitnik** [quasarframework/quasar#3371]
when q-input counter prop is set to true. and the model value is null it displays 4

![image](https://user-images.githubusercontent.com/1234337/53286147-a70da700-3772-11e9-9e09-f943f6b607ae.png)

`Operating System - Darwin(18.2.0) - darwin/x64
NodeJs - 11.3.0

Global packages
  NPM - 6.4.1
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.8 -- Quasar Framework App CLI
  @quasar/extras - 1.1.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.7 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.3 -- Babel compiler core.
  webpack - 4.29.5 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*`

**Comment by rstoenescu** [comment]
Fix will be available in beta.5
