### ISSUE TITLE
[v1 feature]toolbar add back-link for mobile app

### ISSUE THREAD

**Issue by alterhu2020** [quasarframework/quasar#3375]
The feature is that can you provide a navbar functionality like this : http://framework7.io/docs/navbar.html ,currently the toolbar only has the `title` slot and also the title's default font size is too big in mobile device. if you can support the toolbar like below screenshot, 
it contains below features:
* back link with icon
* custom back link behavior, like navigation or click event.

![image](https://user-images.githubusercontent.com/5029046/53296239-2cae5700-3846-11e9-8de0-1f3d2973ac7b.png)

**Comment by rstoenescu** [comment]
You mean [this](https://codepen.io/rstoenescu/pen/OqLyrZ?&editable=true&editors=101)?
And put it into a QHeader (with `bordered` prop) in a QLayout.

For handling back button, especially on mobile: https://v1.quasar-framework.org/vue-directives/go-back
