### ISSUE TITLE
Notify - throw error when timeout param is invalid

### ISSUE THREAD

**Issue by iMakedonsky** [quasarframework/quasar#3376]
### Software version

Operating System         	Darwin(18.2.0) - darwin/x64
NodeJs                   	11.6.0

Global packages          	
  NPM                    	6.5.0
  yarn                   	1.13.0
  quasar-cli             	0.17.23
  vue-cli                	3.2.1
  cordova                	Not installed

Important local packages 	
  quasar-cli             	0.17.23	(Quasar Framework CLI)
  quasar-framework       	0.17.19	(Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras          	2.0.9	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.17	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.25.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.14	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.6.3	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.5.2	(Script for registering service worker, with hooks)

Networking               	
  Host                   	Oleksanders-MacBook-Pro.local
  en0                    	192.168.1.2

### JsFiddle
https://jsfiddle.net/uL26hs4t/5/

### What did you get as the error?
No error produced
### What were you expecting?
Either an error thrown because it works only with numbers, or coercing it silently
### What steps did you take, to get the error?
pass `timeout: '1'` argument to notify

**Comment by rstoenescu** [comment]
Enhanced for v1.0.
Do you need this badly for 0.17? Because at this point focus is still 100% on the v1 release.
