### ISSUE TITLE
[v1] re-enable custom icons for q-checkbox

### ISSUE THREAD

**Issue by apasov** [quasarframework/quasar#3378]
In v0.17 q-checkbox had **checked-icon** and **unchecked-icon** props that allowed using custom icons for checkbox states.
For some reason in v1 this feature is dropped. Please re-enable it. 
There is a full description of this issue with images and code examples in Quasar forum: https://forum.quasar-framework.org/topic/3182/q-checkbox-custom-icons-removed

**Comment by rstoenescu** [comment]
Hi,

In order for an accurate Material Design on checkboxes, this had to be dropped. However, you could use QToggle with icons.
