### ISSUE TITLE
q-select opens option list on top of window when options count more then one screen

### ISSUE THREAD

**Issue by alexey2baranov** [quasarframework/quasar#338]
It seems than q-list opens list in wrong y-coordinate = 0 when options count more then some value;

In short list i did not see same behaviour

**Comment by rstoenescu** [comment]
Don't quite get what you mean. Any screenshots pls?

**Comment by alexey2baranov** [comment]
![incorrect](https://cloud.githubusercontent.com/assets/19248996/22141076/fe1a2606-df11-11e6-992f-78042cb7cad7.png)

**Comment by alexey2baranov** [comment]
![correct](https://cloud.githubusercontent.com/assets/19248996/22141106/2164041a-df12-11e6-8b44-44ba36c26194.png)

**Comment by rstoenescu** [comment]
Oh, yes. It tries to use the screen real estate as best as possible. This is not a bug.

**Comment by alexey2baranov** [comment]
mmmm... it is very smart on mobile but looks ugly on desktop imho. hope you improve this in a future

**Comment by rstoenescu** [comment]
It will improve ;)

**Comment by itaysmalia** [comment]
and if I don't want it at mobile also?

**Comment by pdanpdan** [comment]
Then you read the docs and discover the behavior prop

**Comment by itaysmalia** [comment]
> Then you read the docs and discover the behavior prop

I read the docs, there ia no prop related to that problem in the q-select docs.

**Comment by pdanpdan** [comment]
I thought you want to use the menu instead of dialog on mobile. Then please explain more what you want.

**Comment by itaysmalia** [comment]
> I thought you want to use the menu instead of dialog on mobile. Then please explain more what you want.

found it, thank you.
`
<q-select behavior="menu" />
`
