### ISSUE TITLE
[v1] When setting overlay on a QDrawer it hides it by default

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#3381]
See this codepen:

https://codepen.io/webnoob/pen/gEYwOz?&editable=true&editors=101

If you remove the `overlay` prop, it will show the QDrawer properly based on the initial value of the `v-model`.

The code:
```
showing = this.behavior !== 'mobile' && this.breakpoint < this.layout.width && !this.overlay
        ? largeScreenState
        : false
```

Doesn't really make sense in this instance as overlay should only mean it goes over elements, not affect it's state.

**Comment by hawkeye64** [comment]
Agreed, overlay prop should not affect initial state set by developer.

**Comment by webnoob** [comment]
I'll do a PR soon.

**Comment by rstoenescu** [comment]
Hi,

This has been discussed many times. The current behavior is correct.
