### ISSUE TITLE
[v1] q-table single selection/table template issue

### ISSUE THREAD

**Issue by birchb** [quasarframework/quasar#3382]
### Software version

Quasar: 1.0.0-beta.4
@quasar/app (v1+ only): 1.0.0-beta.8
OS: Darwin(18.2.0) - darwin/x64
Node: 10.15.0
NPM: 6.8.0
Browsers: Chrome 72.0.3626.119, Firefox Developer Edition v 66.0
iOS:
Android:
Any other software related to your bug:

###  Codepen

https://codepen.io/birchb/pen/aMopMd

### What did you get as the error?
I have three tables in the codepen:

1. Just a simple table with two columns. I've attempted to implement single selection according to the example in the docs, and it works.
2. This is the same table, except that each q-tr has been defined in a template. It seems as if the column for the selection has been created (dev tools confirms this), but the column containing the selection box, e.g., [√], has not. I have not ruled out that this is the result of my error.
3. Finally, this is the point of defining each q-tr: so that I can customize the q-td. The q-select works correctly here, but I am yet unable to select the entire row. 

### What were you expecting?
I was expecting the selection box to appear in each row before the name so that that row could be selected. Is there a way to define the selection column in the columns array?

### What steps did you take, to get the error?
I asked a few questions on the v1-beta Discord channel. After a bit of work, @hawkeye64 suggested that I file an issue.

**Comment by rstoenescu** [comment]
Hi,

Since you are using a template for the body, you also need to include a column for the selection (wherever you want, or you can even not add it at all).

See: https://v1.quasar-framework.org/vue-components/table#Example--Expanded-row-and-custom-selector

```html
<template v-slot:body="props">
        <q-tr :props="props">
          <q-td auto-width>
            <q-toggle dense v-model="props.selected" />
          </q-td>
```

**Comment by birchb** [comment]
See also https://v1.quasar-framework.org/vue-components/table#Example--Expanded-row-and-custom-selector for a complete example. 
Also, remember to add QCheckbox to your components array in quasar.conf.js even though it does show when using selection="single" :selected.sync="selected" without self-defining the table body in a template.
