### ISSUE TITLE
[v1] QInput/QSelect styles in dense mode

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#3383]
### Software version

Quasar: v1.0.0-beta.4
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### JsFiddle

https://codepen.io/beeplin/pen/JzPWJJ

### What did you get as the error?
![image](https://user-images.githubusercontent.com/13058150/53308809-1dc7b300-38df-11e9-93f1-9bfd9d61e0e1.png)

### What were you expecting?

1. in the `rounded` mode the floating label should have a left padding to prevent overlapping with the round border (the red arrow in the pic above)

2. the floating label should have a larger top margin. Now it's too close to the top border line.

**Comment by rstoenescu** [comment]
Fix will be available in beta.5
