### ISSUE TITLE
[v1 document] Group the component document

### ISSUE THREAD

**Issue by alterhu2020** [quasarframework/quasar#3384]
Could you put all the components in the document site: https://v1.quasar-framework.org/vue-components , like in old document site: https://quasar-framework.org/components/ .
Also the new document site i saw missing this component site: https://v1.quasar-framework.org/vue-components/date 

Please take a look at it ? thanks.

**Comment by surmind** [comment]
QDate is not missing, It's at `Form Components - Date Picker`

**Comment by rstoenescu** [comment]
Hi,

While the structure of the menu has changed, we feel this new one is better. We don't have any reasons to change it in the future, so while it may take a bit to get adjusted to it, it's gonna be worth it.

Sorry for any inconveniences.
