### ISSUE TITLE
[v0.17.15] autocomplete under IE 11 issue

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#3386]
From @framfrwork / Discord - #ie11 - PDan asked for issue and he'll look into it

I have a problem with autocomplete under IE 11.
When I have an autocomplete that opens without entering a character, the selection of a value is not taken into account and the list is re-opened indefinitely.
I reproduced the problem directly on the quasar website:
https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/autocomplete
The problem is on the field Trigger search on focus (if no value is set) / Focus me too.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 0.17.20.
