### ISSUE TITLE
q-list and q-list-dialog crop their content when Chrome.options.font-size=Large or Very Large

### ISSUE THREAD

**Issue by alexey2baranov** [quasarframework/quasar#339]
q-list and q-list-dialog crop their content when Chrome.options.font-size=Large or Very Large
![font-size-large](https://cloud.githubusercontent.com/assets/19248996/22141497/25e4f59c-df14-11e6-883f-e988f0a35ccb.png)

**Comment by rstoenescu** [comment]
Who does touch those Chrome options? :)
Not planning on fixing this. At least not soon.
