### ISSUE TITLE
QPopover: Error in nextTick: "TypeError: Cannot read property 'removeChild' of null"

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#3390]
Here is the breakdown for SPA project:
1) We have a QLayoutDrawer
2) Sometimes it is not to be displayed at all, so there is a v-if on it
3) The drawer has a QBtn that wraps a QPopover
4) When the drawer is hidden, then again displayed via the v-if, the following error occurs:
```
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'removeChild' of null"

found in

---> <QPopover>
       <QBtn>
         <QToolbar>
           <DashboardToolbar> at src/components/DashboardToolbar.vue
             <QLayoutHeader>
               <QLayout>
                 <LayoutDefault> at src/layouts/default.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?2b0e:587
logError @ vue.runtime.esm.js?2b0e:1733
globalHandleError @ vue.runtime.esm.js?2b0e:1728
handleError @ vue.runtime.esm.js?2b0e:1717
(anonymous) @ vue.runtime.esm.js?2b0e:1835
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
Promise.then (async)
microTimerFunc @ vue.runtime.esm.js?2b0e:1802
nextTick @ vue.runtime.esm.js?2b0e:1846
Vue.$nextTick @ vue.runtime.esm.js?2b0e:4513
value @ model-toggle.js?b885:20
run @ vue.runtime.esm.js?2b0e:3229
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:2977
(anonymous) @ vue.runtime.esm.js?2b0e:1833
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
vue.runtime.esm.js?2b0e:1737 TypeError: Cannot read property 'removeChild' of null
    at VueComponent.eval (QPopover.js?5b9a:84)
    at Array.eval (vue.runtime.esm.js?2b0e:1833)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1754)
```
It is happening in this code for QPopover:
```js
  mounted () {
    this.__updatePosition = frameDebounce((_, event, animate) => this.reposition(event, animate))
    this.$nextTick(() => {
      this.anchorEl = this.$el.parentNode
      this.anchorEl.removeChild(this.$el)
```
The `this.$el.parentNode` is `null`.
The `this.$el` is `div.q-popover.scroll`
The `this.$el.$options.propsData` is 'q-popover'
The `this.$el.$options._propsKeys` are:
```
_propKeys: Array(14)
0: "value"
1: "anchor"
2: "self"
3: "fit"
4: "cover"
5: "persistent"
6: "keepOnScreen"
7: "maxHeight"
8: "touchPosition"
9: "anchorClick"
10: "offset"
11: "noFocus"
12: "noRefocus"
13: "disable"
```
The `this.$el.$options._parentElm` is null (`_parentElm: null`)
The `this.$el.$options._renderChildren` is:
`0: VNode {tag: "vue-component-12-QList", data: {…}, children: undefined, text: undefined, elm: div.q-list.q-list-link, …`

$ quasar info

Operating System                Linux(4.15.0-45-generic) - linux/x64
NodeJs                          8.12.0

Global packages          
  NPM                           6.5.0
  yarn                          1.12.3
  quasar-cli                    0.17.23
  vue-cli                       2.9.6
  cordova                       Not installed

Important local packages 
  quasar-cli                    0.17.23 (Quasar Framework CLI)
  quasar-framework              0.17.19 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.25.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.14  (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.6.3   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

I tried to replicate this in codepen, but it's working, so I am missing something more complex with our app.
https://codepen.io/Hawkeye64/pen/WmNQwE

Razvan, I hope this is enough to go on. If not, hit me up. This is causing issues in production code. I would do a PR, but I don't think I'd get it right on this one. Thanks.

**Comment by hawkeye64** [comment]
Maybe the popover also needs a v-if? Or, perhaps I should be using v-show?

**Comment by rstoenescu** [comment]
Use v-show pls.

**Comment by hawkeye64** [comment]
That didn't work. What I did find out is that the behavior of on QPopup seems to be affecting the behavior of another QPopup on the toolbar (of which I have many). So, when the error occurs I no longer have to Dropdown list in QPopup because that code crashed. I'll investigate on my end why this one in particular is being affected.
So, can we adjust the code to check for null?

**Comment by hawkeye64** [comment]
ok, putting a v-show on the other popup worked. No issues.
