### ISSUE TITLE
avatars don't show in QDrawer when there is no accompanying QItemSection's on that QItem

### ISSUE THREAD

**Issue by codenamezjames** [quasarframework/quasar#3394]
### Software version

Quasar:
@quasar/app (v1+ only):
OS: Mac 10.14.3
Node: v10.15.1
NPM: 6.5.0
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### JsFiddle

https://codepen.io/anon/pen/KEKWaY

### What did you get as the error?
It doesn't show the icons when collapsed

### What were you expecting?
To see the icons all the time

### What steps did you take, to get the error?
make a drawer with some items and remove <q-item-section> from the any of the items and the icon doesn't show up on mini

**Comment by codenamezjames** [comment]
PR #3400 should fix this issue

**Comment by rstoenescu** [comment]
Fix will be available in beta.5. Thanks for the PR!
