### ISSUE TITLE
Error on vue 2.6.7 with scoped slots using hmr

### ISSUE THREAD

**Issue by hailwood** [quasarframework/quasar#3397]
### Software version

Quasar: 1.0.0-beta.4
Vue: 2.6.7

### What did you get as the error?
![image](https://user-images.githubusercontent.com/709773/53380233-8beca280-39d1-11e9-9810-b468541fa738.png)

### What were you expecting?
No Error

### What steps did you take, to get the error?
Using code straight out of https://v1.quasar-framework.org/vue-components/slide-item
When I make a change that causes an HMR reload, I get the error above.

This seems related to this issue https://github.com/vuejs/vue/issues/9553
Which means we should be able to just rebuild against the 2.6.7 runtime to fix the error.

**Comment by rstoenescu** [comment]
Hi.

Which means to use @quasar/app beta.8 (currently latest) and also follow the forum for announcements (https://forum.quasar-framework.org/topic/3180/quasar-app-1-0-0-beta-8-and-quasar-babel-preset-app-1-0-1-released-v1-only) :)

**Comment by rstoenescu** [comment]
If you have manually added "vue" as dependency, remove it. This is highly NOT recommended.

**Comment by nghiepit** [comment]
I have a problem with Nuxt.js
