### ISSUE TITLE
Violation - added non passive listener

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#3398]
@pdanpdan here it is.. ;)

I see this from time to time. It's even on Quasar docs introduction page.

![image](https://user-images.githubusercontent.com/25121817/53396272-55e4f980-39a4-11e9-8bb8-12d4ab8487ae.png)

It resolves to here in vendor. There is one more place, I'll try to find it.

![image](https://user-images.githubusercontent.com/25121817/53396422-b2481900-39a4-11e9-95fb-6daf81b6e2a7.png)

Win10, Chrome.

**Comment by pdanpdan** [comment]
The problem is I cannot reproduce.
Can you associate the warnings with some action you do in the page?

**Comment by panstromek** [comment]
@panstromek 🤔 It is just a page load. Just open the docs and go to `get started`. And new Violation is thrown on almost everytime you to some other page..

**Comment by panstromek** [comment]
Wait.. now I can't reproduce it either. It doesn't throw these anymore...

**Comment by pdanpdan** [comment]
I hope it was because an old version of the scrips that were cached. The problem was present but it should have been fixed in beta 2. If it happens again please comment here.

**Comment by panstromek** [comment]
I guess we can close this for now and reopen if it appears again
