### ISSUE TITLE
[v1] QDate - Excluding dates

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#3399]
v1 supports the options prop to limit the selection of a QDate to certain dates. This works great for limiting to a few dates, but if you want to disable for example 1 day in an entire year you would need to provide a huge array as option.

This can be done with an options function, but I think performance wise this is a bad idea.
I think it is easy to solve so I am willing to make a PR if the devs agree with my reasoning.

**Comment by rstoenescu** [comment]
Use the Function form of `options`.
https://v1.quasar-framework.org/vue-components/date#Example--Options

**Comment by stefanvanherwijnen** [comment]
Sorry, you are right. I thought the options function was just a filter on an array, my bad.

**Comment by Arthemide** [comment]
Hello, I have the same issue, and I don't follow you. 
What do you mean by `Use the Function form of options` ?
Thanks for the response.

**Comment by stefanvanherwijnen** [comment]
Instead of `options=excludedDates`, use `:options=yourFunction`.
See https://quasar.dev/vue-components/date#Limiting-options
