### ISSUE TITLE
Infinite Scroll & Tap Panels

### ISSUE THREAD

**Issue by matrixOnline** [quasarframework/quasar#3401]
### Software version

Quasar:  v1.0.0-beta.4
@quasar/app (v1+ only):  v1.0.0-beta.7
OS: Windows
Node: v8.9.4
NPM: 6.8.0
Browsers: Chrome

### Codepen

https://codepen.io/anon/pen/MxYyvj

### What did you get as the error?
Loads items all the time.
I think the issue gets by the "scroll" class (automatic added by the tab panel)

### What were you expecting?
Same results as infinite scroll without tap panels

### What steps did you take, to get the error?
combined components "infinite scroll" and "tap panels"

**Comment by rstoenescu** [comment]
Will be available in beta.10

**Comment by yexing** [comment]
The issue not fixed in v1.0.0 beta23

**Comment by rstoenescu** [comment]
@yexing Specify your custom scroll target. @pdanpdan do you have a bit of time to explain, pls?

**Comment by rstoenescu** [comment]
Fix will be available in beta.25.
