### ISSUE TITLE
i18n-es.js  orthographic error in translation

### ISSUE THREAD

**Issue by kelthaz** [quasarframework/quasar#3403]
**table: {
    noData: 'Sin datos disponibles',
    noResults: 'No se econtraron resultados',
}**

Here is the error in the translation that i found in the component data-table.

![error-quasar](https://user-images.githubusercontent.com/25802013/53443924-ce66ad00-39da-11e9-8c3b-51ce084495af.png)

**Comment by rstoenescu** [comment]
encontraron? I don't know Spanish so a little help pls? :)

**Comment by smolinari** [comment]
Google translate: No se han encontrado resultados

:grin:

Scott

**Comment by rstoenescu** [comment]
I can do Google Translate too, but that's not always accurate. Best is if a Spanish speaking person confirms what the correct translation is.

**Comment by rstoenescu** [comment]
Fix will be available in beta.5
