### ISSUE TITLE
[v1] Disabled button with v-close-dialog closes QDialog

### ISSUE THREAD

**Issue by dmig** [quasarframework/quasar#3404]
I have a `QDialog` with form in it. Dialog submit button has both `v-close-dialog` and `disable` property. The latter is connected to simple validation _computed_ which ensures all fields are filled.

### Software version

Quasar: v1.0.0-beta.4
@quasar/app (v1+ only): v1.0.0-beta.8
OS: Linux(4.18.20-041820-generic) - linux/x64
Node:	10.2.1
NPM:	6.8.0
Browsers:	Chromium 71.0.3578.98
Any other software related to your bug:

### JsFiddle
https://jsfiddle.net/dmig/4sqkf8n1/6/

### What did you get as the error?
Clicking "submit" button closes dialog even when it's disabled.

### What were you expecting?
Clicking "submit" button does nothing.

### What steps did you take, to get the error?
See fiddle

**Comment by rstoenescu** [comment]
Enhancement will be available in beta.5.
