### ISSUE TITLE
Datatable(q-table) in q-step doesn't show horizontal scroll bar with FireFox.

### ISSUE THREAD

**Issue by udgw** [quasarframework/quasar#3405]
Quasar: quasar-framework@0.17.8 umd
OS: Ubuntu
Node: I don't use
NPM: I don't use
Browsers: Firefox 65.0.1 64bit

https://jsfiddle.net/dkfywmn2/

### What did you get as the error?
Datatable with overflowed content doen't show horizontal scrollbar inside q-step.

### What were you expecting?
The Datatable shows horizontal scroll bar.

### What steps did you take, to get the error?
- I put datatable inside q-step.
- And I set data rows to the datatable, It just occured.
- With chromium 71.0, No problem.
- When I explictly wrote style="width: 100%; overflow-x: scroll" in q-step, DataTable shows horizontal scrollbar.
- In other ocassion (without q-step), I didn't see the error.

**Comment by rstoenescu** [comment]
This should be fixed in latest v1 betas.
