### ISSUE TITLE
add passive to scroll and touch event

### ISSUE THREAD

**Issue by icfr** [quasarframework/quasar#341]
[event listener options](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

this will help on scrolling when an heavy task run

if i have time i would do a PR (not before march ...)

**Comment by rstoenescu** [comment]
This would be a nice addition for the "scroll" modifier. Thanks!

**Comment by Trellian** [comment]
Hi @rstoenescu , is there any news on this? I'm still experiencing these warnings.

**Comment by rstoenescu** [comment]
This will get done. I can assure you on that. Sorry it takes so long (the todo pile is huge).

**Comment by Trellian** [comment]
Thanks @rstoenescu . No problem, I understand!  Thanks again for the wonderful Quasar framework

**Comment by rstoenescu** [comment]
Will be available starting with 0.15.0-beta.11, so closing this.
