### ISSUE TITLE
[v1] - QInput - Dark

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3416]
### Software version

Quasar: 
 NPM - 6.8.0
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.0
  cordova - 8.0.0

Any other software related to your bug:

Whenever you place a ```<q-input dark label="Test Label"/>``` inside a container with a background, the float label uses the primary color when you focus on the field. This causes the label to disappear when using bg-primary and also have some major contrast issues when used with other colors. Can we please have an option to set the label color, or text color to white?

CodePen: https://codepen.io/anon/pen/JzYrKK

Cheers,
Ben

**Comment by pdanpdan** [comment]
Can you please create a small codepen showing the problem? Thank you.

**Comment by rstoenescu** [comment]
Use `color` prop on QInput.
