### ISSUE TITLE
 framework: 'all' not work?

### ISSUE THREAD

**Issue by sonygod** [quasarframework/quasar#3417]
### What did you get as the error?

 framework: 'all' not work?  

when I config  framework: 'all'  ,and rebuild use

    **quasar dev**

### What were you expecting?

<q-header> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
.....

and seem lots of componets is not included?

### What steps did you take, to get the error?
    1:quasar init mydemo

    2: copy layout from git examples folder  
   
   3: change framework: 'all' 
        
      change  component: () => import('../layout/layout.vue'), in routes.js

   
  4 :save and build 
.
      quasar dev

    

  5:got erros like that.

    App URL........... http://localhost:13000/
    Dev mode.......... spa
    Quasar theme...... mat
    Quasar CLI........ v0.17.23
    Quasar Framework.. v0.17.19

6,it's seem " framework" node is not work not matter what you change. 

![image](https://user-images.githubusercontent.com/748320/53565329-2268c180-3b94-11e9-8cde-ef21eb73caf6.png)

**Comment by rstoenescu** [comment]
"framework: { all: true }" works just fine...

**Comment by maows** [comment]
> "framework: { all: true }" works just fine...

How Vue cli 3 use framework:all ?

**Comment by rstoenescu** [comment]
Create a vue-cli app, add quasar plugin to it and:
* answer "no" to "Treeshake Quasar?" (if installing the v1 vue-cli-plugin-quasar@beta)
* answer "yes" to "Import all Quasar components, directives and plugins?" (if installing the 0.17 vue-cli-plugin-quasar)
Then check your main.js

**Comment by maows** [comment]
> Create a vue-cli app, add quasar plugin to it and:
> 
> * answer "no" to "Treeshake Quasar?" (if installing the v1 vue-cli-plugin-quasar@beta)
> * answer "yes" to "Import all Quasar components, directives and plugins?" (if installing the 0.17 vue-cli-plugin-quasar)
> 
> Then check your main.js

Thank you very much. The problem has been solved.
