### ISSUE TITLE
add a tip for hmr in cordova app in docs

### ISSUE THREAD

**Issue by icfr** [quasarframework/quasar#342]
just add in the doc:

> if you want hmr in cordova app change 
>
> `<content src="index.html" />`
> to
> `<content src="http://ip.of.dev.pc:port" />`

**Comment by rstoenescu** [comment]
Hi,

For documentation please use the appropriate repo: https://github.com/quasarframework/quasar-framework.org/issues
Redirecting bug there.

Best way would be to use Quasar Play app though.
Will also include this tip. Thanks!
