### ISSUE TITLE
[0.15-?] Edge Promise.finally not defined

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#3427]
### Software version

Quasar: 0.15.5
@quasar/app (v1+ only):
OS: Windows 10
Node: v8.9.3
NPM: 5.5.1
Browsers: Microsoftt Edge 17
iOS: N/A
Android: N/A
Any other software related to your bug:

### JsFiddle

https://jsfiddle.net/1oqygeh9/2/

### What did you get as the error?
`object doesn't support property or method finally`

![image](https://user-images.githubusercontent.com/7946730/53611425-82fbfc80-3b9c-11e9-9435-4db815bee72f.png)

### What were you expecting?
I was expecting to see the message `Finally fired` like
![image](https://user-images.githubusercontent.com/7946730/53610885-9f973500-3b9a-11e9-9cd4-e335d31930c4.png)

The [polyfill](https://github.com/quasarframework/quasar/blob/v0.15/src/ie-compat/ie.js) do not seems to work properly.

**Could it be** because the polyfill only fill when Promise is not supported at al instead of also test for only missing `finally` method ? If yes, this could be the source of the problem, because Edge < 18 support Promise but not the method `finally`.

### What steps did you take, to get the error?
I load the jsfiddle page with Microsoft Edge 17 and I simply get the error. 

I have two workmates with Windows 10 who their Windows 10 is not in developer mode and they seem to be stuck at Edge version 17, Windows update says it is up to date!

For Edge version 18, this is working properly but as I know the `Promise.finally` is now natively supported. Ref [ChakraCore #3520](https://github.com/Microsoft/ChakraCore/issues/3520)

![image](https://user-images.githubusercontent.com/7946730/53614272-631e0600-3ba7-11e9-915e-7307f574c91a.png)
Ref: https://en.wikipedia.org/wiki/Microsoft_Edge

---
I'm still using an old version of quasar, but for now we are stuck and can't update to new version. Maybe in a couple of week we will.

Also, I already set the IE support flag in `quasar.conf.js`.
```js
module.exports = ctx => ({
  supportIE: true,
});
```

**Comment by pdanpdan** [comment]
supportIE only polyfills what quasar uses. Just replace `.finally(something)`, which is not well supported, with `.then(something, something)` or with `.catch(() = {}).then(something)`

**Comment by purell** [comment]
> supportIE only polyfills what quasar uses. --@pdanpdan

This is weird as the IE polyfill contains the prototype for adding the `finally` method but quasar does not use them at all. I search in all the code of the quasar repo and no trace of `finally` usage... Why put that in ?

> .catch(() = {}).then(something) --@pdanpdan

From what I've read and test, this version will not work for a special case that I have. I need to throw an error in the catch, so the next `then` will not be fired. **BUT**, when using a `finally` it get fired properly.

Do you know another way to get it working as a finally ?

**Comment by pdanpdan** [comment]
In your case just hide loading message in catch before throw.

**Comment by purell** [comment]
Yes, your're right @pdanpdan, this is a solution I had considered, but I would have liked to avoid duplicate code. Now I've no choice.

Is there a chance the polyfill [ie-compat](https://github.com/quasarframework/quasar/blob/v0.15/src/ie-compat/ie.js) be fixed to test for the support of "Promise.finally" instead of only testing for the support of Promise ?

I would be more than please to make the PR but I'm not sure to really understand how this polyfill work and how it detect the missing support.

**Comment by panstromek** [comment]
Usual workaround for `.finally` is to put `.then(onFinally, onFinally)` (from [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally))
after the last catch clause.

I would suggest you to not bet on polyfills when the workaround is that simple. Polyfilling and transpilation is very complex. Adding such a simple thing is not really worth it considering the risk of possible breakage.

Another thing is that 0.15 is really old version and full focus is on 1.0 now. We can't spend time patching legacy version.

**Comment by purell** [comment]
>Usual workaround for .finally is to put .then(onFinally, onFinally) (from mdn)
after the last catch clause.  – @panstromek 

Thank you, but did you [read this reply](https://github.com/quasarframework/quasar/issues/3427#issuecomment-468556640) ? I' can't use `.then(onFinally, onFinally)`, this will clearly not work for my needs. But thank you for your help.

> Another thing is that 0.15 is really old version and full focus is on 1.0 now. We can't spend time patching legacy version. – @panstromek 

As for the version 1.0 of quasar, I already explained that I can't update for now.

**Comment by panstromek** [comment]
@purell I've read your reply, but I think I mean something different.

This behaves exactly the same as your `finally` version 😉
```js
Promise.resolve()
   .then( () => ) {
       // Show a loading message...
       throw new Error('foo');
    })
   .catch((ex) => {
       // Log the error...
       
       // Rethrow it
       throw ex;
   })
   .then(() => {
       // Hide the loading message...
    }, () => {
       // Hide the loading message...
    })
```
(better to extract the function of course)

The only difference for `finally` are params and return values - to make this behave exactly the same as finally, you would need to re-throw the error in last callback and return resolved value in previous one, this is because `finally` passes values through, but `then` callbacks passes what you return from them. But from my understanding you don't need this last bit.

**Comment by purell** [comment]
So to be clear, both versions are working **but** both duplicate the code anyway :( I would have liked to see `finally` worked.

1. You version
```js
Promise.resolve()
   .then(() => {
       // Show a loading message...
       throw new Error('foo');
    })
   .catch((ex) => {
       // Log the error...
       
       // Rethrow it
       throw ex;
   })
   .then(() => {
       // Hide the loading message...
       console.log('Hide message 1');
    }, () => {
       // Hide the loading message...
       console.log('Hide message 2');
    });
```

2. Other version with duplicate
```js
Promise.resolve()
   .then(() => {
       // Show a loading message...
       throw new Error('foo');
    })
   .catch((ex) => {
       // Log the error...

       // Hide the loading message...
       console.log('Hide message');
       
       // Rethrow it
       throw ex;
   })
   .then(() => {
       // Hide the loading message...
       console.log('Hide message');
    });
```

**Comment by nothingismagick** [comment]
@purell - if you can you confirm that this is still happening in quasar 0.17, then I imagine we would dig into it after 1.0 launches. We have no plans to continue to support 0.15 

On a side note, .finally is called REGARDLESS of a catch, that's why its called finally.
```
The finally() method can be useful if you want to do some processing or cleanup once the promise is settled, regardless of its outcome. 
```
