### ISSUE TITLE
Cannot extend QUploaderBase because it is not exposed in 'quasar'

### ISSUE THREAD

**Issue by LuciaEllan** [quasarframework/quasar#3428]
### Software version

quasar - 1.0.0-beta.5
@quasar/app - 1.0.0-beta.4
OS: Windows_NT(10.0.17134) - win32/x64
Node: 10.7.0
NPM: 6.1.0
Browsers: N/A
iOS: N/A
Android: N/A
Any other software related to your bug: N/A

### What did you get as the error?
When I try to extend `QUploaderBase` as stated in the [document](https://v1.quasar-framework.org/vue-components/uploader#Supporting-other-services), I get following error:
```
 ERROR  Failed to compile with 1 errors
 error  in ./src/components/FirebaseUploader.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Unknown import from Quasar: QUploaderBase

  - imports.js:162 module.exports
    [quasar]/[quasar]/dist/babel-transforms/imports.js:162:11

  - index.js:64 transform
    [quasar]/[babel-plugin-transform-imports]/index.js:64:16

  - index.js:138
    [quasar]/[babel-plugin-transform-imports]/index.js:138:39

  - Array.forEach

  - index.js:121 PluginPass.ImportDeclaration
    [quasar]/[babel-plugin-transform-imports]/index.js:121:35

  - visitors.js:193 newFn
    [quasar]/[@babel]/traverse/lib/visitors.js:193:21

[more error stack trace output truncated]
```

### What were you expecting?
Expecting the mixin work, effectively extending `QUploaderBase` which is defined in `src/components/uploader/uploader-base-mixin.js` of `quasar` module.

### What steps did you take, to get the error?
I tried to extend `QUploaderBase` as stated in the [document](https://v1.quasar-framework.org/vue-components/uploader#Supporting-other-services) to implement uploading to Firebase storage
The file `FirebaseUploader.js` looks like this:
```
import { QUploaderBase } from 'quasar'
import firebase from 'firebase/app'
import 'firebase/storage'

export default {
  name: 'FirebaseUploader',
  props: {
    pathPrefix: {
      type: String,
      default: ''
    }
  },
  mixins: [ QUploaderBase ],
...
```

### Temporary workaround
I managed to expose `QUploaderBase` by adding following line to `node_modules/quasar/dist/babel-transforms/imports.js`:
```
  "QUploaderBase": "src/components/uploader/uploader-base-mixin.js",
```
As that file is managed by NPM, I cannot rely on this workaround, though...

If you're interested, please consider adding this extension code to the doc as an example. This extends `QUploaderBase` to work with Firebase storage (assuming you have right permissions)
```
import { QUploaderBase } from 'quasar'
import firebase from 'firebase/app'
import 'firebase/storage'

export default {
  name: 'FirebaseUploader',
  props: {
    pathPrefix: {
      type: String,
      default: ''
    }
  },
  data () {
    return {
      storage: firebase.storage().ref(),
      activeTasks: []
    }
  },
  mixins: [ QUploaderBase ],
  computed: {
    isIdle () {
      return this.activeTasks.length === 0
    },
    isUploading () {
      return this.activeTasks.length > 0
    }
  },
  methods: {
    abort () {
      this.activeTasks.forEach(task => {
        task.cancel()
      })
      this.activeTasks = []
    },
    upload () {
      if (this.disable || !this.queuedFiles.length) { return }
      this.queuedFiles.forEach(file => {
        this.__uploadSingleFile(file)
      })
    },
    __uploadSingleFile (file) {
      let pathPrefix = this.pathPrefix || ''
      const fileRef = this.storage.child(pathPrefix + file.name)
      this.__updateFile(file, 'uploading', 0)
      const uploadTask = fileRef.put(file)
      this.activeTasks.push(uploadTask)
      // Listen for state changes, errors, and completion of the upload.
      uploadTask.on(
        firebase.storage.TaskEvent.STATE_CHANGED, // or 'state_changed'
        snapshot => {
          // Get task progress, including the number of bytes uploaded and the total number of bytes to be uploaded
          if (file.__status !== 'failed') {
            const loaded = Math.min(snapshot.totalBytes, snapshot.bytesTransferred)
            this.uploadedSize += loaded - file.__uploaded
            this.__updateFile(file, 'uploading', loaded)
          }
        }, error => {
          // A full list of error codes is available at
          // https://firebase.google.com/docs/storage/web/handle-errors
          this.queuedFiles.push(file)
          this.__updateFile(file, 'failed')
          this.__emit('failed', { file, error })
          this.uploadedSize -= file.__uploaded
          this.activeTasks = this.activeTasks.filter(t => t !== uploadTask)
        }, () => {
          // Upload completed successfully, now we can get the download URL
          uploadTask.snapshot.ref.getDownloadURL().then(downloadURL => {
            const fullPath = uploadTask.snapshot.ref.fullPath
            const fileName = uploadTask.snapshot.ref.name
            this.uploadedFiles.push(file)
            this.__updateFile(file, 'uploaded')
            this.__emit('uploaded', { file, downloadURL, fullPath, fileName })
            this.uploadedSize += file.size - file.__uploaded
          }).catch(error => {
            this.__emit('failed', { file, error })
          })
          this.activeTasks = this.activeTasks.filter(t => t !== uploadTask)
        }
      )
    }
  }
}

```

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in beta.6

**Comment by saro-saravanan** [comment]
I'm getting a similar error now trying to use QFirebaseUploader. Any thoughts on how to fix without munging node_modules?


 » Dev mode.................. spa
 » Pkg quasar................ v2.6.6
 » Pkg @quasar/app-webpack... v3.5.1
 » Transpiled JS............. yes (Babel)

 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 713ms

 App •  ERROR  •  UI  in ./src/components/QFirebaseUploader.vue?vue&type=script&lang=js

Error: QUploaderBase

  - import-transformation.js:6 module.exports
    [app]/[quasar]/dist/transforms/import-transformation.js:6:11

  - loader.js.transform-quasar-imports.js:23
    [app]/[@quasar]/app-webpack/lib/webpack/loader.js.transform-quasar-imports.j    s:23:78

  - Array.map

  - loader.js.transform-quasar-imports.js:10
    [app]/[@quasar]/app-webpack/lib/webpack/loader.js.transform-quasar-imports.j    s:10:8

  - String.replace

  - loader.js.transform-quasar-imports.js:7 Object.module.exports
    [app]/[@quasar]/app-webpack/lib/webpack/loader.js.transform-quasar-imports.j    s:7:30



 App •  COMPILATION FAILED  • Please check the log above for details.
