### ISSUE TITLE
[v1] QStepper model gets set to object [InputEvent] when QInput is used inside it

### ISSUE THREAD

**Issue by sskwrl** [quasarframework/quasar#3429]
### Software version
  quasar - 1.0.0-beta.5  (It works in beta.4)

### JsFiddle
https://codepen.io/skwrl/pen/yweMqj?&editable=true&editors=101

### What did you get as the error?
As soon as you type a character in a q-input contained in a qstepper, the entire content of qstep is removed from the DOM because the step value is set to the emitted InputEvent

### What were you expecting?
The character I typed to be displayed in the QInput and step to remain unchanged

### What steps did you take, to get the error?
Type any character in the QInput.
To recover from the step being InputEvent push the "Continue" button in the step.

**Comment by sskwrl** [comment]
Different symptom of what I assume to be the same bug mentioned in discord chat:

![image](https://user-images.githubusercontent.com/42022576/53622480-eea78f00-3bc7-11e9-8512-58431283e840.png)

**Comment by pdanpdan** [comment]
It's related to d04c723b393a2e89d9488e25746ac5c0720d0d30 I think. I'll check.

**Comment by rstoenescu** [comment]
Thank you for reporting! Fix will be available in beta.6 -- trying to embed some more work into beta.6 for other issues as well and release it ASAP.
