### ISSUE TITLE
Clicking a modal close button multiple times quickly will send you back a page

### ISSUE THREAD

**Issue by jsfeldman** [quasarframework/quasar#343]
If you click a modal close button multiple times quickly you will be sent back a page instead of just closing the modal. I believe what is happening is that the close event from hitting the close modal button is triggered as well as the close event from clicking outside of the modal.

Let me know if you're not experiencing it or if you need any other information.

**Comment by rstoenescu** [comment]
Are you using edge or v0.12?

**Comment by rstoenescu** [comment]
Fixed for v0.13 and in edge.

**Comment by jsfeldman** [comment]
I'm using v0.12. Awesome! Thanks.
