### ISSUE TITLE
Error in mounted hook: "TypeError: hx.Main is not a constructor"

### ISSUE THREAD

**Issue by sonygod** [quasarframework/quasar#3430]
<!--

### What did you get as the error?

Error in mounted hook: "TypeError: hx.Main is not a constructor"

### What were you expecting?

there are no error output

### What steps did you take, to get the error?

may be webpack error? 

here is my [test files](https://gist.github.com/sonygod/c48092a4b90ffc9db0abac7c8bb722a2)

I've tested ok in node,but throw error in quasar dev

**Comment by nothingismagick** [comment]
@sonygod - What is this? You don't tell us anything about the context, platform, build type etc. Please update your issue.
