### ISSUE TITLE
may be webpack error? which version webpack use in quasarframework?

### ISSUE THREAD

**Issue by sonygod** [quasarframework/quasar#3431]
### What did you get as the error?
vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in mounted hook: "TypeError: hx.Main is not a constructor"
### What were you expecting?

do not show error 
### What steps did you take, to get the error?

build an run [this](https://gist.github.com/sonygod/c48092a4b90ffc9db0abac7c8bb722a2) code . I've tested in node.js ,it's ok .

**Comment by rstoenescu** [comment]
Is this your code? Because there's no `hx.Main` in Quasar. If it's your code, please use our Discord or forum to request for help. Github is reserved exclusively for bug reports.
