### ISSUE TITLE
[v1] QSelect use-input doesn't replace precedent v-model value

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3432]
### What did you get as the error?
I cannot overwrite the string formerly set

### What were you expecting?
I expect to overwrite the string or cancel it with backspace when QSelect is selected

### What steps did you take, to get the error?
Put the cursor inside the QSelect and press backspace, the string won't be erased.

CodePen:
https://codepen.io/willypuzzle/pen/KEVXxY

**Comment by pdanpdan** [comment]
It's a select - you're not using the use-input for anything.
It is not expected to delete the model if you press backspace if you don't make it do so.

**Comment by willypuzzle** [comment]
What the usefulness of use-input if I cannot overwrite the text?

**Comment by pdanpdan** [comment]
What are you using it for now?
You can use it to filter or you can use it to add new values.
Check https://v1.quasar-framework.org/vue-components/select#Filtering-and-autocomplete
and https://v1.quasar-framework.org/vue-components/select#Create-new-values.

**Comment by willypuzzle** [comment]
I was using it to filter but in both cases has no sense the current behaviour, it overloads my code with avoidable code (I have to reset the model every time I began to filter)

**Comment by pdanpdan** [comment]
In the sample you linked to you did nothing with the input.
Also why would you need to reset model when you start to filter? The model should change on selection, not on filtering (in the normal usage).

**Comment by willypuzzle** [comment]
Se you the difference:

This is the codepen without model resetting https://codepen.io/willypuzzle/pen/NJxybM?editors=1111

This is the codepen with model resetting https://codepen.io/willypuzzle/pen/OqMQgQ

**Comment by pdanpdan** [comment]
I can see. From the point of view of expected functionality the second example is a nightmare - why would you want to do this? If you click on a standard html select do you expect to lose the value? The model should only change if you select another option, not if you change the subset of options you see in the list.

**Comment by willypuzzle** [comment]
But what if I want to do filtering?

**Comment by rstoenescu** [comment]
@willypuzzle Hi, Please read the doc page more carefully and join the Discord channel for help. You are misusing this component. Thank you.
