### ISSUE TITLE
[v1] QInput error-message doesn't work

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3434]
### What did you get as the error?
The error Message is not displayed 

### What were you expecting?
To see the error message

### What steps did you take, to get the error?
set the prop error to true, fill the prop error-message with text

Codepen:
https://codepen.io/willypuzzle/pen/KEVorM

**Comment by pdanpdan** [comment]
https://v1.quasar-framework.org/vue-components/input#External-validation

**Comment by willypuzzle** [comment]
Correct, what I need was adding bottom-slots prop to the component
