### ISSUE TITLE
QSelect standout displays black background on focus

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3436]
When a QSelect with standout display gets the focus the background becomes black and the text white, which is rather inconsistent with other components' behavior.

**Comment by rstoenescu** [comment]
This is actually the point with it. To "stand out" (with regular or `dark`). Examples (with QInput, but works the same with QSelect too): https://v1.quasar-framework.org/vue-components/input#Example--Standout-in-QToolbar
