### ISSUE TITLE
[v1] QDialog finer control over dismiss behaviour

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#3437]
I'm pretty sure we've been here before in 0.17, but I can't figure out how to do this in 1.0. I have a QDialog which I would like to ignore backdrop clicks, _but_ with the Esc key able to act as the Cancel button. In 0.17, this was easy through `no-backdrop-dismiss`. But with 1.0 `persistent`, I can't also set `:no-esc-key="false"` (which in any case is quite a confusing double negative) to re-enable the Esc key.

Could there instead be 2 props, `esc-key-dismiss` and `backdrop-dismiss`, defaulting to `true`, with `persistent` just being a convenience prop to set both to `false`? Then in my case I would only set `backdrop-dismiss` to `false`, preserving the Esc key behaviour.

**Comment by smolinari** [comment]
I think we just need to add the prop `no-backdrop-dismiss` again. That should be all you need for your scenario. 

`no-esc-key` is the same as the old `no-esc-dismiss` and `persistent` is the replacement for `prevent-close`.  

Scott

**Comment by dsl101** [comment]
Yes, I’m sure that would be workable.

I was also proposing to use ‘positive’ props (I.e. avoiding using the ‘no-‘
prefix which inverts the meaning of the boolean value passed in). I realise
that’s a much bigger issue than this one thing but might be worth
considering across Quasar as a whole?

We will then have solved one of the two hard problems :)
https://martinfowler.com/bliki/TwoHardThings.html

**Comment by smolinari** [comment]
Thing is, the idea of having negative worded props is to only have to add the prop name as an attribute and the feature the prop controls will start working as required. With positive wording as you are proposing, everyone would need to add `="false"` to get the feature to work, which would be sort of a mini-anti-pattern from all of the rest of the props within Quasar. :)

Scott

**Comment by rstoenescu** [comment]
Available in beta.8.

```js
"persistent": {
      "type": "Boolean",
      "desc": "User cannot dismiss Dialog if clicking outside of it or hitting ESC key; Also, an app route change won't dismiss it"
    },

    "no-esc-dismiss": {
      "type": "Boolean",
      "desc": "User cannot dismiss Dialog by hitting ESC key; No need to set it if 'persistent' prop is also set"
    },

    "no-backdrop-dismiss": {
      "type": "Boolean",
      "desc": "User cannot dismiss Dialog by clicking outside of it; No need to set it if 'persistent' prop is also set"
    },

    "no-route-dismiss": {
      "type": "Boolean",
      "desc": "Changing route app won't dismiss Dialog; No need to set it if 'persistent' prop is also set"
    },
```
