### ISSUE TITLE
quasar/app does not permit getting rid of vue-router

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3438]
### Software version

Dev mode.......... spa
Pkg quasar........ v1.0.0-beta.5
Pkg @quasar/app... v1.0.0-beta.8

### What did you get as the error?
Module build failed (from ./node_modules/eslint-loader/index.js):
  Error: ENOENT: no such file or directory, open '...\src\router\index.js'

### What were you expecting?
I have developed a custom router since my app has some special needs and I don't use the vue-router. However I can't get rid of the directory "src/router" due to the above error. The application is built even if the file router/index.js is completely empty, so no big deal, but I am not sure whether the tree shaking process cleans the unused vue-router library.

**Comment by smolinari** [comment]
Out of curiosity, what special needs do you have that Vue-router can't handle?

Scott

**Comment by eliaspanagiotidis** [comment]
Scott the application uses multiple paths simultaneously, each path with its own history. Maybe vue-router could handle this requirement somehow, but I already treat it absolutely satisfactory in combination with the relevant data requests in a very simple manner. And I don’t want to complicate things just to leverage the functionality of the vue-router.

Elias

**Comment by RohanTalip** [comment]
When I was migrating my project to quasar, I was also surprised that the router code had to be in a specific location, but at the time I just wanted it to work so I moved my router code from ./router.js to ./router/index.js and moved on.

Is there a reason that this check is done?

**Comment by eliaspanagiotidis** [comment]
It seems that several components of Quasar are designed to work side by side with the vue-router (tabs, QItems etc.). However, it would be maybe better if its use was optional (as vuex is, for instance).

**Comment by rstoenescu** [comment]
Hi,

I'm sorry to inform this, but it's how things stand: vue-router is required in order for all the build modes to work correctly/consistently/automatically. Getting rid of vue-router would require us a lot of time and energy and funds (which we currently do not have for this). We are focusing on bringing final v1 build shipped. I'd say we may ponder on this after v1, if resources allow. Sorry for any inconvenience.

**Comment by eliaspanagiotidis** [comment]
Fair enough. Thanks anyway!
