### ISSUE TITLE
[v1] [Feature request] To add list of stylus variables to docs.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3444]
In my styles I need to use some of Quasar stylus variables.
All of them are located there - https://github.com/quasarframework/quasar/blob/dev/quasar/src/css/variables.styl

But there is no its names in docs, like it was on old docs [here](https://quasar-framework.org/components/stylus-variables.html) .

For example I want to do this

```
.q-title {
  margin: 0 0 $flex-gutter-sm !important;
}
```

But need to go to link on source code to locate needed variable.

Minimally to make somewhere link to sourcefile with varaiables definitions in docs. where it can be easily located.

**Comment by rstoenescu** [comment]
Will be available along with beta.7.
