### ISSUE TITLE
[v1][docs] Suggestion: add a working example for Persian calendar in QDate page

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#3445]
Current example for Persian calendar in `QDate` page in docs has two issues that cause it look like it's broken:
1. It is LTR
2. The language is `en-us` therefore month names are from Gregorian calendar. 

While I understand that since all other examples and components in the docs are LTR and with default language it is not reasonable to change the lang pack just for one example, I think it is better to remove the example and, maybe, add an embedded Codepen or a link to a Codepen with a working example for Persian calendar. (`fa-ir` lang pack and `rtl` css loaded)

I have prepared a Pen for this : https://codepen.io/behnoodk/pen/xBVgEg

**Comment by rstoenescu** [comment]
Thanks! Updated (will be visible with beta.7).
