### ISSUE TITLE
[V1] QSelect "hide-dropdown-icon" leaves an unnecessary div

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3446]
### Software version

Dev mode.......... spa
    Pkg quasar........ v1.0.0-beta.5
    Pkg @quasar/app... v1.0.0-beta.8

### codepen
https://codepen.io/anon/pen/XGdgKd

### What did you get as the error?
In cases QSelect with "hide-dropdown-icon" property is used along with the slot "selected" to display a QItem, an increased padding-like effect appears on the right due to an additional div that is not needed in this case.

### What were you expecting?
Identical left and right "margins" when hide-dropdown-icon is true.

**Comment by rstoenescu** [comment]
Thanks for the excellent codepen highlighting the issue.
Fixed and will be available in beta.7.

**Comment by eliaspanagiotidis** [comment]
Thank you for sharing such great work!
