### ISSUE TITLE
[v1] Invalid prop: type check failed for prop "value". Expected Number, String, got InputEvent

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#3447]
See this codepen:

https://codepen.io/webnoob/pen/ZPWJor?editors=1010

When typing in the input, it raises an error:

`[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, String, got InputEvent `. Clicking on a tab then resets the tabs `v-model` and allows you to see the panel again.

I've seen another issue relating to this which is closed: https://github.com/quasarframework/quasar/issues/3429

Dev mode.......... spa
Pkg quasar........ v1.0.0-beta.6
Pkg @quasar/app... v1.0.0-beta.9

**Comment by rstoenescu** [comment]
Previous fix unfortunately was applicable when "animated" was set to `true`. Corrected the mistake. Final fix available in beta.7.

**Comment by webnoob** [comment]
Ah right. I'll apply the animate prop for now then.
Thanks for your hard work.
