### ISSUE TITLE
[v1][bug] QBtn is resized when the icon changes

### ISSUE THREAD

**Issue by egyel** [quasarframework/quasar#3449]
### Software version

Quasar: v1.0.0-beta 7
@quasar/app (v1+ only):
OS: Windows
Node:
NPM:
Browsers: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### JsFiddle
https://jsfiddle.net/hse3uj5L/

### What did you get as the error?
The width of the button doubles when the icon changes. Click on the button in the attached jsfiddle for a more visual explanation.

### What were you expecting?
as a SPA

### What steps did you take, to get the error?
see jsfiddle

**Comment by rstoenescu** [comment]
It's `bookmark_outline`, not `bookmark_outlined`.
