### ISSUE TITLE
Unable to Run "Quasar dev" in electron dir

### ISSUE THREAD

**Issue by Kwickell** [quasarframework/quasar#345]
I just went through the quickstart guide.

1. Updated NPM/node
2. installed quasar-cli
3. Installed the deps
4. Ran "quasar dev" in root (worked fine)
5. Ran "quasar wrap electron"
6. "npm install" in electron dir
7. Tried to run "quasar dev" in electron dir..

It throws this message and results in the npm log below.

Not really sure where to start debugging?
Hopefully someone has seen this before or have an idea as to why i'm unable to start the app. 😜 

**Error Message**

> - quasar-electron-app@0.0.1 dev /Users/#username#/Sites/Tools/#AppName#/electron
> - cross-env NODE_ENV=development node_modules/electron/dist/electron electron.js
> 
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn node_modules/electron/dist/electron ENOENT
>     at exports._errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Module.runMain (module.js:607:11)
>     at run (bootstrap_node.js:420:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:535:3
> 
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
> npm ERR! node v7.4.0
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> npm ERR! quasar-electron-app@0.0.1 dev: `cross-env NODE_ENV=development node_modules/electron/dist/electron electron.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the quasar-electron-app@0.0.1 dev script 'cross-env NODE_ENV=development node_modules/electron/dist/electron > electron.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the quasar-electron-app package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     cross-env NODE_ENV=development node_modules/electron/dist/electron electron.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs quasar-electron-app
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls quasar-electron-app
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/#username#/Sites/Tools/#AppName#/electron/npm-debug.log

**Content of npm-debug.log**

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'owner',
> 1 verbose cli   'ls',
> 1 verbose cli   'quasar-electron-app' ]
> 2 info using npm@4.0.5
> 3 info using node@v7.4.0
> 4 silly mapToRegistry name quasar-electron-app
> 5 silly mapToRegistry using default registry
> 6 silly mapToRegistry registry https://registry.npmjs.org/
> 7 silly mapToRegistry data Result {
> 7 silly mapToRegistry   raw: 'quasar-electron-app',
> 7 silly mapToRegistry   scope: null,
> 7 silly mapToRegistry   escapedName: 'quasar-electron-app',
> 7 silly mapToRegistry   name: 'quasar-electron-app',
> 7 silly mapToRegistry   rawSpec: '',
> 7 silly mapToRegistry   spec: 'latest',
> 7 silly mapToRegistry   type: 'tag' }
> 8 silly mapToRegistry uri https://registry.npmjs.org/quasar-electron-app
> 9 verbose request uri https://registry.npmjs.org/quasar-electron-app
> 10 verbose request no auth needed
> 11 info attempt registry request try #1 at 9:09:56 PM
> 12 verbose request id 56aecadd36f39874
> 13 http request GET https://registry.npmjs.org/quasar-electron-app
> 14 http 404 https://registry.npmjs.org/quasar-electron-app
> 15 verbose headers { 'content-type': 'application/json',
> 15 verbose headers   'cache-control': 'max-age=0',
> 15 verbose headers   'content-length': '2',
> 15 verbose headers   'accept-ranges': 'bytes',
> 15 verbose headers   date: 'Wed, 25 Jan 2017 20:09:57 GMT',
> 15 verbose headers   via: '1.1 varnish',
> 15 verbose headers   age: '0',
> 15 verbose headers   connection: 'keep-alive',
> 15 verbose headers   'x-served-by': 'cache-bma7021-BMA',
> 15 verbose headers   'x-cache': 'MISS',
> 15 verbose headers   'x-cache-hits': '0',
> 15 verbose headers   'x-timer': 'S1485374996.616600,VS0,VE464',
> 15 verbose headers   vary: 'Accept-Encoding' }
> 16 silly get cb [ 404,
> 16 silly get   { 'content-type': 'application/json',
> 16 silly get     'cache-control': 'max-age=0',
> 16 silly get     'content-length': '2',
> 16 silly get     'accept-ranges': 'bytes',
> 16 silly get     date: 'Wed, 25 Jan 2017 20:09:57 GMT',
> 16 silly get     via: '1.1 varnish',
> 16 silly get     age: '0',
> 16 silly get     connection: 'keep-alive',
> 16 silly get     'x-served-by': 'cache-bma7021-BMA',
> 16 silly get     'x-cache': 'MISS',
> 16 silly get     'x-cache-hits': '0',
> 16 silly get     'x-timer': 'S1485374996.616600,VS0,VE464',
> 16 silly get     vary: 'Accept-Encoding' } ]
> 17 error owner ls Couldn't get owner data quasar-electron-app
> 18 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/quasar-electron-app
> 18 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
> 18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/> request.js:280:14)
> 18 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
> 18 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
> 18 verbose stack     at emitTwo (events.js:106:13)
> 18 verbose stack     at Request.emit (events.js:191:7)
> 18 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
> 18 verbose stack     at emitOne (events.js:96:13)
> 18 verbose stack     at Request.emit (events.js:188:7)
> 18 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
> 19 verbose statusCode 404
> 20 verbose pkgid quasar-electron-app
> 21 verbose cwd /Users/#username#/Sites/Tools/#AppName#/electron
> 22 error Darwin 15.6.0
> 23 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "owner" "ls" "quasar-electron-app"
> 24 error node v7.4.0
> 25 error npm  v4.0.5
> 26 error code E404
> 27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/quasar-electron-app
> 28 error 404
> 29 error 404 'quasar-electron-app' is not in the npm registry.
> 30 error 404 You should bug the author to publish it (or use the name yourself!)
> 31 error 404 Note that you can also install from a
> 32 error 404 tarball, folder, http url, or git url.
> 33 verbose exit [ 1, true ]

**Comment by rstoenescu** [comment]
Redirecting issue to appropriate repo.

**Comment by Kwickell** [comment]
I guess the right repo for this issue is quasar-cli then?

**Comment by rstoenescu** [comment]
Check reference above :) will investigate this tomorrow.
