### ISSUE TITLE
Tooltip gets stuck when using v-close-overlay in combination with modal

### ISSUE THREAD

**Issue by stevebor1** [quasarframework/quasar#3450]
### Software version

  quasar-cli                    0.17.23
  vue-cli                       2.9.6
  cordova                       8.0.0
  quasar-cli                    0.17.23 (Quasar Framework CLI)
  quasar-framework              0.17.19 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)

### JsFiddle
https://codepen.io/stevebor1/pen/pYyOob
![dab92663-5de7-478f-a62e-b181772838a2](https://user-images.githubusercontent.com/1202448/53687906-d6329400-3cef-11e9-830b-0ad3ff82c9e9.gif)

### What did you get as the error?
when using a combination of tooltip on an element, with v-close-overlay, the tooltip gets stuck when triggering a modal to be displayed

### What were you expecting?
Either the tooltip closes before the modal is displayed, or it is removed after modal goes away

### What steps did you take, to get the error?
I initially started with the v-close-overlay to initiate the close of the popover, then added a click event to trigger the modal display. Combining both caused the issue described. I did notice that removing the v-close-overlay was not needed as closing the modal made all other overlays to close. Maybe right behavior, but not to sure. I also tested in 0.17.20 and it is reproducible there too.

**Comment by nothingismagick** [comment]
Happens on touch too (android Chrome)

>

**Comment by stevebor1** [comment]
Actually, removing v-close-overlay makes the tooltip go away, haveever the popup remains. Also found this other related bug: https://github.com/quasarframework/quasar/issues/3451

**Comment by rstoenescu** [comment]
This should no longer happen in v1.
