### ISSUE TITLE
Popover is active when modal is open

### ISSUE THREAD

**Issue by stevebor1** [quasarframework/quasar#3451]
### Software version
quasar-cli 0.17.23
vue-cli 2.9.6
cordova 8.0.0
quasar-cli 0.17.23 (Quasar Framework CLI)
quasar-framework 0.17.19 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)

### JsFiddle
https://codepen.io/stevebor1/pen/vPGzmM
![cb41db2f-8e42-4dfa-8d06-21e3f38aa3bc](https://user-images.githubusercontent.com/1202448/53688032-24489700-3cf2-11e9-90c9-8a962c28f7e4.gif)

### What did you get as the error?
From a popover, a modal was opened. The popover remained active.

### What were you expecting?
Since the modal consumes the screen, I would expect the popover not to be active or above the modal overlay.

### What steps did you take, to get the error?
From a popover trigger a modal to open. The popover remains 'on top' and the contents is selectable. Also reproducible on 0.17.20

**Comment by rstoenescu** [comment]
This is no longer an issue on v1.
