### ISSUE TITLE
[V1 docs] Improve Layout > QPageSticky

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3452]
Do we still need to post documentation related issues in the documentation repo? Since the docs are now this same repository.

https://v1.quasar-framework.org/layout/page-sticky

This is what scrolling looks like on this preview page in Safari:

![scrolling qpagesticky](https://user-images.githubusercontent.com/3253920/53691661-fb91d180-3dc5-11e9-8408-03d6761d8e06.gif)

Very clunky and the right side menu disappears.

I know the actual components work perfect and it's just a problem with these previews, but maybe we should think about not showing a live preview for just this page.

**Comment by rstoenescu** [comment]
The right side menu was fixed some time ago.
Unfortunately, nothing can be done for the other issue due to heavy Safari bugs.
