### ISSUE TITLE
Does not recognize .npmrc configs with self-signed certificates or http proxies

### ISSUE THREAD

**Issue by klauern** [quasarframework/quasar#346]
I am working behind a corporate proxy, and when I try to use this tool, it won't work, as it gets an error regarding our internal certificate servers:

```sh
$  quasar init somewhere

 ℹ Generating Quasar App...

 ✖ Failed to download App template @quasarframework/app-template-default: Error: self signed certificate in certificate chain
```

However, I have in my `.npmrc` a config setting that both Yarn and NPM/Node recognize:

```cfg
;;;;
; npm userconfig file
; this is a simple ini-formatted file
; lines that start with semi-colons are comments.
; read `npm help config` for help on the various options
;;;;

prefix=/home/user/.node_modules
; strict-ssl=false
; my cafile with my company's internal certs
cafile=/etc/ssl/cert.pem
; also have my internal server's proxy servers configured
proxy=http://my-internal-server.somewhere.com:80
https-proxy=http://my-internal-server.somewhere.com:80
```

It appears that this tool also does not recognize nor support any of the HTTP proxy settings.  Attempting to `quasar list` to get a list of templates, I get the following:

```sh
$ quasar list

 ✖ Could not retrieve App template list: [object Object]
```

**Comment by rstoenescu** [comment]
Redirecting to appropiate repo: https://github.com/quasarframework/quasar-cli/issues/17
Let's continue the talk there. Thanks!

**Comment by klauern** [comment]
Oh, sorry about that.  This was the first one I saw.  I was wondering where the CLI calls were being made (not here, apparently...lol).
