### ISSUE TITLE
[Request] Smooth scroll to element util

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3462]
In the [current V1 documents on scrolling utils](https://v1.quasar-framework.org/quasar-utils/scrolling-utils#Scrolling-to-an-element) the only way to scroll to an element is for the dev to recreate a "scrollToElement" function manually.

Since this is such a common feature in many websites I would like to request:
- an official function that can be used right out of the box
- with support for not just scrolling over x ms, but also **with an ease-is-easy-out feature**, so it's really smooth.

Related is original topic #996 where a "scrollToElement" util was requested but ended up in just adding that manual function in the docs. Requested here again for V1.

**Comment by mstaack** [comment]
cant you use https://github.com/quasarframework/quasar/blob/066a6bbd94628005fcc66a487339e36cd97b6ecb/quasar/src/utils/scroll.js#L29 ?

**Comment by mesqueeb** [comment]
@mstaack Do you know what I would have to set `to` to in that function? I tried to understand the source code but couldn't.

The manual code I'm using is:
```js
function scrollToElement (el, duration = 200) {
  const target = getScrollTarget(el)
  const offset = el.offsetTop
  setScrollPosition(target, offset, duration)
}
```

But I guess in the end this doesn't support `ease-in-ease-out`. Do you think it's really resource heavy to add `ease-in-ease-out` to a scrollTo function?

**Comment by rstoenescu** [comment]
It would be cpu intensive++. But take a look at 0.17 code in that area to see how it's done.
