### ISSUE TITLE
[v1] q-icon left and right swap

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#3464]
### Software version
quasar 1.0.0-beta.8

### What did you get as the error?
Q-icon component.
When add "left" prop margin will add to the right side. When add "right", then left margin added.
About left docs said: "Apply a standard margin on the left side. Useful if icon is on the right side of something."

### What were you expecting?
Apply left margin when left prop added.

### What steps did you take, to get the error?
Just play with this props and u will see.

**Comment by rstoenescu** [comment]
The API description was wrong. Correct one:

```js
"left": {
  "type": "Boolean",
  "desc": "Useful if icon is on the left side of something: applies a standard margin on the right side of Icon"
},

"right": {
  "type": "Boolean",
  "desc": "Useful if icon is on the right side of something: applies a standard margin on the left side of Icon"
}
```
