### ISSUE TITLE
[Feature]QChipsInput: add prop label-field when value is Object

### ISSUE THREAD

**Issue by icksky** [quasarframework/quasar#3465]
### Software version

Quasar:
@quasar/app (v0.17.20):
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:
#2219
### JsFiddle

https://jsfiddle.net/f48jemra/5/
### What were you expecting?
I want to show a speial field which from `QAutocomplete`'s item on `QChipsInput`'s QChip. So, may be add prop `label-field` to` `QChipsInput` .

When QChipsInput's value's item is an object, `label-field` is also helpful.

**Comment by pdanpdan** [comment]
Replaced by QSelect from v1
