### ISSUE TITLE
[v1] Icon not scaling with button size in q-item-section with prop avatar or side

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#3467]
Codepen: https://codepen.io/nothingismagick/pen/NJrLer

`<q-item-section side> / <q-item-section avatar>`

    <q-item
      v-for="size in sizes"
      :key="`item_${size}`"
    >
      <q-item-section>
        <q-item-label>
          Size '{{ size }}'
        </q-item-label>
      </q-item-section>
      <q-item-section side>
        <q-btn
          icon="camera"
          round
          color="primary"
          :size="size"     
        >
        </q-btn>
      </q-item-section>
    </q-item>

What happens:  
![screen shot 2019-03-04 at 10 58 00](https://user-images.githubusercontent.com/35242872/53725517-7281a580-3e6c-11e9-93b7-ce791b34be69.png)

Desired rendering (but on the right hand side):
![screen shot 2019-03-04 at 10 50 44](https://user-images.githubusercontent.com/35242872/53725742-e1f79500-3e6c-11e9-848f-ee5af766d688.png)

On a side note, adding the dense prop to the q-btn results in a vertical misalignment of the icon:
![screen shot 2019-03-04 at 11 02 15](https://user-images.githubusercontent.com/35242872/53725822-0bb0bc00-3e6d-11e9-8409-13275af6249e.png)

**Comment by rstoenescu** [comment]
Will be available in beta.9.
