### ISSUE TITLE
Open method for QSelect elements

### ISSUE THREAD

**Issue by damvaz** [quasarframework/quasar#3468]
Open method for QSelect elements
=======================
It would be wonderful if this element had an open() or show() method, so that the options can be displayed from another code.

Example:
```
<script>
export defaults {
  methods: {
     myCustomMethod() {
        this.$refs.mySelect.open()
     }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
`showPopup()` and `hidePopup()` will be available in beta.23
