### ISSUE TITLE
Range Component remains active if dragging mouse pointer out of window

### ISSUE THREAD

**Issue by sganz** [quasarframework/quasar#347]
Found something, not sure if known behavior. A few of the JS sliders I tried this on are not affected when dragging completely out of the window/browser.

If you are dragging (changing the value by mouse) a range slider and continue to drag out of the browser window with mouse left down, when returning back into the browser with the left mouser UP, the sliders still tracks the mouse movement when returning into the browser even though mouse is not selecting it any more. 

I think the default behavior should be if exit then the slider should stop tracking, but not sure.

Running on Linux Mint 18 / FF browser.

**Comment by smolinari** [comment]
Confirmed. The range slider does the same on Windows 10 Pro and Chrome.

Scott

**Comment by rstoenescu** [comment]
Ok, will fix it.
