### ISSUE TITLE
[V1] make toggle non text-selectable

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3470]
If I click the toggle twice (fast) it will try to select text like so:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/3253920/53771737-234c7b00-3f27-11e9-8214-46b11b1f43c7.png">
(yes my highlight colour is pink 😂)

#### Maybe we can add some CSS that prevents this at all costs.

**Comment by smolinari** [comment]
Can you note browser and OS? For instance, I don't have this issue with Win10 Pro and Chrome, Firefox or Edge.

Scott

**Comment by mesqueeb** [comment]
Sorry!
macOS latest version
Safari latest version

**Comment by rstoenescu** [comment]
Fix will be available in beta.12
