### ISSUE TITLE
q-scroll-area

### ISSUE THREAD

**Issue by ghf1990525** [quasarframework/quasar#3472]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
onWheel @ quasar.ios.esm.js?69e3:1422

**Comment by rstoenescu** [comment]
Hi,

This has already been fixed and will be available in 1.0-beta.10

**Comment by lunne** [comment]
I need to fix this in 0.17, the job to bump to 1.0 is to big right now.
Is the fix for 1.0 usable for 0.17 aswell?
