### ISSUE TITLE
[V1 - docs] Upgrade to newer Quasar version

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3474]
The old docs had a section called **"Upgrading to a newer Quasar version"**

I always forget if we need to do `npm i update` or `npm i quasar-cli@latest` or what the npm command for this was.

I know it's (probably) really straightforward but adding this information to the V1 documentation is really important I think. (I'm probably still on beta v1 :P)

**Comment by rstoenescu** [comment]
https://v1.quasar-framework.org/start/upgrade-guide

**Comment by rstoenescu** [comment]
Good point. Added info.
