### ISSUE TITLE
could we have a Audio visualization component such as waveform as a feature

### ISSUE THREAD

**Issue by bebekar** [quasarframework/quasar#3475]
Could we have a visualization component for Audio 
such as  https://www.npmjs.com/package/vue-audio-visual

**Comment by nothingismagick** [comment]
Maybe something for 1.0 in combination with the QMediaPlayer app-extension from @hawkeye64

**Comment by rstoenescu** [comment]
Why not use `vue-audio-visual` component directly?

**Comment by bebekar** [comment]
Yes @rstoenescu, I have used it directly but it works well on windows browsers Firefox but does not work on electron or codova. something sticky happening and the waveform gets stuck. 
Secondly, it is a beautiful component for Quasar to have.

**Comment by rstoenescu** [comment]
Added to the "nice to have pile". If it's gonna see the light of day, it's definitely gonna be through an app extension and not in core.

Thank you for the suggestion.
