### ISSUE TITLE
[v1] QDialog: Toggling 'maximized' property while hidden still locks scroll

### ISSUE THREAD

**Issue by abruere** [quasarframework/quasar#3478]
Thanks for Quasar!

This is a minor issue related to maximized dialog. I’m submitting a PR too.

This is loosely related to #3310.

### quasar-v1.0.0-beta.8

Operating System - Linux(4.4.0-142-generic) - linux/x64
NodeJs - 8.11.2

Global packages
  NPM - 5.6.0
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.2
  cordova - Not installed

Any other software related to your bug:

### JsFiddle

Codepen: https://codepen.io/anon/pen/YgGMqe?editors=1010

### What did you get as the error?

Toggling `maximized` on a hidden QDialog locks body scroll.

### What were you expecting?

Scroll lock should only apply when QDialog is visible. Maximized can be toggled in background depending on layout or screen size.

### What steps did you take, to get the error?

Please have a look at the codepen, where I reproduce using:
- Screen size based `maximized` property
- Manual toggle

**Comment by nothingismagick** [comment]
Can you confirm that this is still happening with Quasar v1.0.0-beta.8 ?

>

**Comment by abruere** [comment]
Yes I’ve just updated the codepen (forked from components docs) from v1.0.0-beta.7 to v1.0.0-beta.8, thanks.

**Comment by rstoenescu** [comment]
@abruere Thx for working on a PR! Will be available in beta.9

**Comment by abruere** [comment]
Thanks for building Quasar @rstoenescu!
