### ISSUE TITLE
Uncaught Error: Cannot find module "quasar/dist/quasar.win32.css"

### ISSUE THREAD

**Issue by Underzzoo** [quasarframework/quasar#348]
Hello there, excelent work with the framework, i'm testing here, when i use the commando quasar build, everything is compiled right, but when i try to load the page from a http-server, the console return this error:

```
Uncaught Error: Cannot find module "quasar/dist/quasar.win32.css"
    at app.js:1
    at Object.148 (app.js:1)
    at r (manifest.js:1)
    at window.webpackJsonp (manifest.js:1)
    at app.js:1
```

NOTE: first, i get another error in vue-loader, i uninstall using npm and install again, after that, the build run with no other problems.

Thanks.

**Comment by rstoenescu** [comment]
There's no quasar.win32.css file. Never was. Can you explain what exactly is that you did? What OS, NPM and node versions are you running, what commands you typed in the console etc. Thanks!

**Comment by rstoenescu** [comment]
Also, what did you reinstall exactly?

**Comment by Underzzoo** [comment]
I think that the great problem is me, i rebuild everything to put the informations that you require and now everything is working fine with http-server module for nodejs (from dist folder).

I'm sorry for taking your time... anyway, the informations is bellow.

My OS:
Windows 10 Pro - v 1511 (32-bits)

My NPM Version:
3.10.10

My NodeJS version:
v6.9.4

Running build commands (using MS Powershell):
```
PS C:\Projetos\quasar\desktop-app> quasar build


> quasar-app@0.0.1 build C:\Projetos\quasar\desktop-app
> node build/script.build.js

 Built files are meant to be served over an HTTP server.
 Opening index.html over file:// won't work.

 WARNING!
 Do NOT use VueRouter's "history" mode if
 building for Cordova or Electron.

 Cleaned build artifacts.

 Building Quasar App with "mat" theme...

Build completed in 56.428s

Hash: ce8934de4908c8e31407
Version: webpack 2.2.0
Time: 56436ms
                                   Asset       Size  Chunks                    Chunk Names
        img/nsw-generic-logo.cfa4460.png    15.4 kB          [emitted]
fonts/MaterialIcons-Regular.012cf6a.woff    57.6 kB          [emitted]
         fonts/Roboto-Light.37fbbba.woff    89.2 kB          [emitted]
        fonts/Roboto-Medium.303ded6.woff    89.7 kB          [emitted]
       fonts/Roboto-Regular.081b11e.woff    89.4 kB          [emitted]
          fonts/Roboto-Thin.90d3804.woff    87.8 kB          [emitted]
          fonts/Roboto-Bold.ad140ff.woff    89.2 kB          [emitted]
                            js/vendor.js     535 kB    0, 2  [emitted]  [big]  vendor
                               js/app.js    12.1 kB    1, 2  [emitted]         app
                          js/manifest.js    1.43 kB       2  [emitted]         manifest
app.44cdb1c6fd2d3720b59afa60f0c8f795.css     246 kB    1, 2  [emitted]         app
                              index.html  634 bytes          [emitted]
```

What i reinstall: 
(brazilian here, bad english, sorry) I was trying to build the app like i did above, and getting a error (i can't remember right now). So, i reinstall ONLY the vue-loader module with the commands:

npm uninstall --save-dev vue-loader

reinstall:

npm install --save-dev vue-loader

**Comment by rstoenescu** [comment]
No worries. If you can isolate this problem on the future feel free to contact me again. Thanks!
