### ISSUE TITLE
[v1] QUploader - Factory function - Promise support

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#3481]
In v0.17:
> url-factor: Function (with file object received as parameter) which returns a Promise that resolves to a URL.

In v1:
> url:
>  Type: String | Function
>  Description: URL or path to the server which handles the upload. Takes String or factory function, which returns String. Function is called right before upload

As part of my migration effort it seems that I need to change the URL factory method I have from returning a promise to return a value. I guess it could be a good idea to support receiving of a promise also.

**Comment by rstoenescu** [comment]
Good point. Will do.

**Comment by rstoenescu** [comment]
Will be available in beta.9. Excerpt from beta.9 docs:

```
There is a `factory` prop you can use which must be a Function. This function can return either an Object or a Promise resolving with an Object (and in case the Promise fails, `@factory-failed` event is emitted).

The Object described above can override the following QUploader props: `url`, `method`, `headers`, `fields`, `fieldName`, `withCredentials`, `sendRaw`). The props of this Object can be Functions as well (of form `(file[s]) => value`):

[Factory Promise example]

You can also use the `factory` Function prop and return immediately the same Object. This is useful if you want to set multiple props (described above) simultaneously:

[Immediate return example]
```
