### ISSUE TITLE
[v1] BUG: Table Search Server-side is glitching when typing

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#3483]
This bug can be seen in the documentation (https://v1.quasar-framework.org/vue-components/table). 
Go to "Server side pagination, filter and sorting" and try to type in search.

Demo Video:
https://cdn.discordapp.com/attachments/543560902675398665/552659241769369600/Table___Quasar_Framework_-_Google_Chrome_06_03_2019_01_09_34.mp4

Codepen:
https://codepen.io/ajcastro/pen/dLPwpd?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Hi,

This was due to a problem in QInput. Has been fixed a few betas ago, but forgot to close this ticket.
