### ISSUE TITLE
[v1 - wish] QField could be very useful if its API was intended to remain stable

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3485]
QField was/is a very useful component permitting developers to inherit consistent and well designed behavior to custom components. If there is no purpose to abolish it or radically modify its API in the near future it will be great if it remains documented in V1.

**Comment by rstoenescu** [comment]
It will become public API soon ;)

**Comment by eliaspanagiotidis** [comment]
Perfect news!

**Comment by nothingismagick** [comment]
@eliaspanagiotidis - you need to be careful about replying from email, because the entire header of the email (including your email address) is visible in the reply.

**Comment by eliaspanagiotidis** [comment]
You are right... Many thanks!

**Comment by tegola** [comment]
I rely a lot on `QField` on 0.17 for showing error messages below every form widget, and in general for having a consistent look.

Is it really becoming a standalone component in 1.0? Because that will really help with the migration.

Also, since `QInput` and `QSelect` already implement `QField`, wouldn't be strange to mix them to custom `QField`s in a form?

**Comment by rstoenescu** [comment]
1. Yes, it will be standalone too, for creating custom "fields".
2. You won't be needing QInput or QSelect to be wrapped in QField. In fact, you shouldn't. In v1.

**Comment by simplygood** [comment]
Please bring back QField! Today I tried to upgrade to v1, and this turned out to be a huge roadblock. I used it a lot with vuelidate, and QInput cannot simply replace it. :(

**Comment by rstoenescu** [comment]
@simplygood I assure you 1000% that for QInput it can fully replace it. Don't despair, join our Discord and request a bit of help if v1 docs are not enough, although I doubt it.

**Comment by simplygood** [comment]
@rstoenescu I could not able to find a relevant example to create a QField with the new QInput. Could you provide an example that can do the following example in the old version? [https://quasar-framework.org/components/field.html#Validations-with-Vuelidate](https://quasar-framework.org/components/field.html#Validations-with-Vuelidate) Or, could you point me to some relevant resources? Thanks!

**Comment by rstoenescu** [comment]
Isn't https://v1.quasar-framework.org/vue-components/input enough? It has all examples there, including validations (internal or external).

**Comment by simplygood** [comment]
@rstoenescu What I often found useful about QField and used a lot is its ability to do "Wrapping form components". I could create various consistent input form components not only with QInput but also with others form components. V1 QInput seems to be able to replace (QField + QInput) but not (QField + other form components).

**Comment by rstoenescu** [comment]
@simplygood I'm not contradicting that. I already said it's going to get documented. It's available as we speak but it's not currently 100% "curated" to work with any content (doesn't mean it won't work, just that I haven't analyzed it for the other use-cases yet).

People wanted v1-beta ASAP, and didn't get a chance to do my curation on it yet, so published without documenting it for this reason. But it will come soon.

**Comment by simplygood** [comment]
@rstoenescu I read the v1 QInput documentation carefully and could not figure out how to do "Wrapping form components" for input components that are not a text input component. Look forward to seeing complete documentation or example soon. Thanks!

**Comment by simplygood** [comment]
@rstoenescu Could you provide a simple example of QInput wrapping other form components (e.g. QBtnToggle)? Or, roughly when can I expect to see it in the official documentation? I was not able to figure it out myself. Thanks,

**Comment by rstoenescu** [comment]
Will be documented in beta.14

**Comment by simplygood** [comment]
Thanks!

**Comment by tegola** [comment]
Can't seem to find QField's documentation in the latest version. I have just upgraded to beta 14:

```
$ quasar upgrade -i

Quasar CLI · Gathering information...

quasar: 1.0.0-beta.13 → 1.0.0-beta.14
@quasar/app: 1.0.0-beta.13 → 1.0.0-beta.15

...
```

**Comment by rstoenescu** [comment]
Vue components > Form components > Field
https://v1.quasar-framework.org/vue-components/field

**Comment by tegola** [comment]
Thanks.

BTW, the search doesn't show any result about "QField", except for the Upgrade guide, which says that QField has been removed:

https://v1.quasar-framework.org/start/upgrade-guide#QField

**Comment by rstoenescu** [comment]
Hehe, I've just updated the upgrade guide then saw this message :)

It takes up to 24 hrs for search results to get updated (Algolia's job) and up to 24 hrs for CDN to get updated (jsdelivr.net's job). Both out of Quasar's reach.
