### ISSUE TITLE
[v1 - request] QBtnToggle: Optional QTooltips for each button

### ISSUE THREAD

**Issue by arjanski** [quasarframework/quasar#3487]
While QBtnToggle is made up of QBtn's, it currently does not allow to add QTooltips for each button (as you would be able to with a single QBtn).

It would be fantastic if we could somehow assign QTooltips to specific buttons, maybe using a slot or a specific child component that could target a button via a `name` attribute.

**Comment by mroes** [comment]
I would also appreciate this possibility

**Comment by rstoenescu** [comment]
Will be available in beta.21. You'll now be able to customize the buttons content too, not just rely on "label" and "icon" in "options" Object. Example:

```html
<q-btn-toggle
  v-model="model"
  push
  glossy
  toggle-color="teal"
  :options="[
    {label: 'One', value: 'one', slot: 'one'},
    {label: 'Two', value: 'two', slot: 'two'},
    {label: 'Three', value: 'three', slot: 'three'}
  ]"
>
  <template v-slot:one>
    <q-tooltip>One!</q-tooltip>
  </template>

  <template v-slot:two>
    <q-tooltip>Two!</q-tooltip>
  </template>

  <template v-slot:three>
    <q-tooltip>Three!</q-tooltip>
  </template>
</q-btn-toggle>
```
