### ISSUE TITLE
[v1 - request] Add QTreeSelect component

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3489]
There is QSelect component.
And QTree component.
Them has big great functionality, but it is not easy to make custom QTreeSelect from existing code now.

I think it is good idia to make QTreeSelect inside Quasar, or tree list inside QSelect or some easy mechanics to to it by custom way.

**Comment by pdanpdan** [comment]
It's already implemented in QTree: https://v1.quasar-framework.org/vue-components/tree#Selection-vs-ticking%2C-expansion

Just use `selected.sync` to use it as single selection or `icked.sync` o use it multiple selection.

**Comment by Dmitrij-Polyanin** [comment]
But how to integrate it inside select interface.
QTree is working fine. I know. I already used it. But not easy to make it like QSelect design.

**Comment by Dmitrij-Polyanin** [comment]
I mead thomething like select with menu with tree popup.
![image](https://user-images.githubusercontent.com/10674646/55001391-8e004c00-4fe5-11e9-8a5f-252994f6ca62.png)

**Comment by pdanpdan** [comment]
Here is a simple example: https://codepen.io/anon/pen/BbEveq?editors=1010

**Comment by Dmitrij-Polyanin** [comment]
Very cool! That is what I need! Thanks.
But may be to make docs for QField?

**Comment by pdanpdan** [comment]
It's WIP, still need to solve some small details like the QField losing focus when you focus the QTree.
But I agree it would be a nice example.

**Comment by Dmitrij-Polyanin** [comment]
I think I will wait this docs to migrate my code.

**Comment by rstoenescu** [comment]
Use example from Dan's [codepen](https://codepen.io/anon/pen/BbEveq?editors=1010).
Should work with latest beta.
