### ISSUE TITLE
QTable  - strange __index property

### ISSUE THREAD

**Issue by bezany** [quasarframework/quasar#3490]
### Software version

Quasar: all versions since Dec 6, 2017 ([this commit](https://github.com/quasarframework/quasar/commit/f0b84dd36fe088ef910596e60ead474d1dc4c6e4))

### JsFiddle
v1: https://jsfiddle.net/bezanyu/945mbLns/
v0.15-17: https://jsfiddle.net/bezanyu/noqt956x/

### What did you get as the error?

See console output and compare column `__index` in `originalData` with table data.

### What were you expecting?

`__index` property not change.

### Comment

I found this problem when compare table rows with deep equality for detect user's changes. And found that all rows changed.

### How to fix

I not found usage `__index` property in code. Look like [this map call](https://github.com/quasarframework/quasar/blob/f0b84dd36fe088ef910596e60ead474d1dc4c6e4/src/components/table/QTable.js#L72) may be removed.

**Comment by rstoenescu** [comment]
Hi,

The `__index` prop is a helper. Helps to know at which index within your data you are. Useful (and just giving out a random  example) for when using slots and you want to add a button to remove the row (you need to know at which index to remove).

**Comment by moander** [comment]
I'm binding QTable data to Vuex and I get warnings about state being modified directly. I tracked it down to __index being added to the data. 

Is it possible to stop this from happening?

**Comment by rstoenescu** [comment]
Removed the addition of this property. The change will be available in "quasar" v1.4.4.

**Comment by faizshukri** [comment]
> The __index prop is a helper. Helps to know at which index within your data you are. Useful (and just giving out a random example) for when using slots and you want to add a button to remove the row (you need to know at which index to remove).

This is my exact use case, and now it breaks after I upgraded quasar. :(

@rstoenescu Is there any alternative to get index inside slot?

Thanks

**Comment by pdanpdan** [comment]
See here: https://github.com/quasarframework/quasar/issues/5694

**Comment by faizshukri** [comment]
@pdanpdan 

Awesome :tada:
