### ISSUE TITLE
[v1] QSelect won't show completely when used in combination with QStepper

### ISSUE THREAD

**Issue by sebas7dk** [quasarframework/quasar#3492]
### Software version

Quasar: v1.0.0-beta.8
@quasar/app (v1+ only): 1.0.0-beta.10
OS: Linux
Node: 11.6.0
NPM: 6.7.0
Browsers: Chrome and Firefox

### Codepen

https://codepen.io/sebas7dk/pen/QodMPL

### What did you get as the error?
Q-select doesn't display in full when used inside of the q-stepper component.
### What were you expecting?
Pre v1.0.0 this used to work and the q-select dropdown was displaying on top of the q-stepper component.
### What steps did you take, to get the error?
See the Codepen and the reason it doesn't work is because of the css below:
` .q-stepper--vertical .q-stepper__step {
    overflow: hidden;
}`

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting. We are aware of this. It will be fixed.
Same reason as for https://github.com/quasarframework/quasar/issues/3276 so closing.

**Comment by sn0rcha** [comment]
Same problem exists with horizontal stepper.
