### ISSUE TITLE
[v1] QPopupProxy: Flex grid does not work in Dialog mode

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#3493]
### JsFiddle

https://codepen.io/stefanvh/pen/KEaZME

### What did you get as the error?
When a dialog is opened as popup, the flex grid CSS is ignored. Using a QLayout and QPageContainer with a flex grid seems to work better, but still not as expected: 
https://codepen.io/stefanvh/pen/OqWjeq

Also, for smaller widths the columns do seem to be converted to rows.

**Comment by rstoenescu** [comment]
Hi,

You don't need a QLayout.
QPopupProxy should contain one node only. So place your DIVs into a "parent" DIV.

```
<q-popup-proxy ...>
  <div>
     ..your divs, content...
  </div>
</q-popup-proxy>
```
