### ISSUE TITLE
[Feature] Electron drag window class

### ISSUE THREAD

**Issue by arkhenstone** [quasarframework/quasar#3494]
Electron frameless windows doesn't have any window decoration. By default, you can't move them around in the window manager. Since there is now a QBar component in Quasar, some of the demos feature the layout of a title bar, close to the one of MacOS or Windows window decoration. 

To make a component a draggable area for the window to move around, this is a simple CSS : 
```
.q-electron-draggable {
  -webkit-user-select: none;
  -webkit-app-region: drag;
}
.q-electron-draggable > :not( [ insert clickable components selector]) {
  -webkit-app-region: no-drag;
}
```
To get a quick demo of this : 
Create an electron project
Add all in quasar.conf.js
In `electron-src/electron-main.js` replace : 
```
mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    useContentSize: true,
  })
```
by
```
mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    useContentSize: true,
    frame: false
  })
```
In `src/layouts/MyLayout.vue` add this  : 
```
<q-bar dark class="bg-grey-10 text-white q-electron-draggable" >
        <q-img src="statics/quasar-logo.png" style="height: 18px; width: 18px;margin-right:1rem"></q-img>
        <span>Draggable Window</span>

        <q-space />

        <q-btn dense flat icon="minimize"  />
        <q-btn dense flat icon="crop_square" />
        <q-btn dense flat icon="close"  />
      </q-bar>
```
And add to it the style above. It should be able to move on the QSpace component and the "title" (the span), depending of what selector may be appropriate in the :not part.

Gif demo : 
![deepin-screen-recorder_desktop_20190306154310](https://user-images.githubusercontent.com/17592744/53902970-ba5a2580-4042-11e9-9c4c-c5205ee356b0.gif)

@nothingismagick (as asked by you)

**Comment by nothingismagick** [comment]
Thanks for requesting this and the excellent writeup. Will give it some thought.

**Comment by rstoenescu** [comment]
This is really a nice and useful idea.
Can you test if it works correctly with:

```
.q-bar
  -webkit-user-select none
  -webkit-app-region drag

.q-bar > *
  -webkit-app-region no-drag
```

I'll create a prop for QBar specifically for this, but I need confirmation that it would work correctly first.

**Comment by nothingismagick** [comment]
I can confirm that this works splendidly on Mac Electron 3 & Electron 4.

**Comment by arkhenstone** [comment]
I'll add that most title bar have title, and you must be capable to drag the window if you click on it. I take as example VS code (which is electron based), there is a menu in the bar, an icon, 2 spaces, a title and buttons (min max close). Most people expect the drag event to be at least accessible on either space and title. Which .q-bar > * will make title undraggable. That's why I suggested a class, since you could apply the class to the title also and it'll works nice.

**Comment by rstoenescu** [comment]
Took a bit more time to think this through. I think the best option is to simply have 2 classes that can be applied on any element. So not just on QBar.

So, added `q-electron-drag` and `q-electron-drag--exception` CSS classes.

I will also add some basic info for beginners on the event handlers for minimize, maximize/unmaximize and close buttons.
