### ISSUE TITLE
QSplitter warning and incorrect functionality if textarea is inside

### ISSUE THREAD

**Issue by helloslava** [quasarframework/quasar#3495]
### Software version

Quasar: 1.0.0-beta.8
@quasar/app (v1+ only): 1.0.0-beta.10
OS: Darwin(18.2.0) - darwin/x64
Node: 8.15.0
NPM: 6.4.1
Browsers: all

### JsFiddle

I can't reproduce it in JsFiddle, only in the project.

### What did you get as the error?

`[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number with value NaN, got InputEvent` found in `QSplitter` and after this, I can't even move splitter separator.

### What steps did you take, to get the error?

1. Start new app `quasar create test -b dev`
2. Modify `MyLayout.vue` to

```
<template>
  <q-splitter v-model="splitter" :limits="[20, 50]" style="height: calc(100vh - 100px)">
    <template v-slot:before>
      <textarea v-model="test"></textarea>
    </template>
    <template v-slot:after>
        <p>after</p>
    </template>
  </q-splitter>
</template>

<script>
export default {
  name: 'Test',
  data: () => ({
    splitter: 50,
    test: ''
  })
}
</script>
```

3. Then try to input something in textarea. And you will get: `[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number with value NaN, got InputEvent` found in `QSplitter`. In chrome vue-dev-tools you can see that `q-splitter` value prop is set to `InputEvent`

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in beta.9
