### ISSUE TITLE
[V1 - request] Button Toggle + full-width

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3497]
### What I'm trying to build is something that looks like:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/3253920/53943878-6e21ea80-4101-11e9-8f68-9357882f0e4b.png">

### What I'm getting is:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/3253920/53943936-9a3d6b80-4101-11e9-9b9b-493b979a8ff9.png">

### Template code:
```html
<q-btn-toggle
  v-model="model"
  class="my-toggle full-width"
  unelevated
/>
```
### CSS:
```stylus
.my-toggle
  border thin solid $primary
  color $primary
  font-size 19px
  border-radius 8.5px
  overflow hidden
```

I'd like to request the **button toggle** to work with the `full-width` css class! : )

**Comment by rstoenescu** [comment]
`spread` prop will be available in beta.10, for both QBtnGroup and QBtnToggle.

Example that looks identical to what you want to build:
```
<q-btn-toggle
        v-model="secondModel"
        spread
        class="my-custom-toggle"
        no-caps
        rounded
        unelevated
        toggle-color="primary"
        color="white"
        text-color="primary"
        :options="[
          {label: 'Option 1', value: 'one'},
          {label: 'Option 2', value: 'two'}
        ]"
      />

.my-custom-toggle
  border 1px solid $primary
```
