### ISSUE TITLE
[V1] inconsistency 'outline' & 'outlined'

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3498]
To use an "outline" design we can use a special prop on certain components.

However in V1...
- the [input](https://v1.quasar-framework.org/vue-components/input) prop is called **`outlined`**
- while the [button](https://v1.quasar-framework.org/vue-components/button) prop is called **`outline`**

I think it makes more sense if this is both outline or both outlined and made consistent throughout all Quasar.

**Comment by nothingismagick** [comment]
I believe we caught this already.

**Comment by rstoenescu** [comment]
It may seem as inconsistency, but "outlined" is the term Material Design 2 is using for inputs.
We can't make this drastic change on QBtn (& co) and QChip and so on as this would break a lot of people's apps on v1. We need to have a stable API. So probably this should go into v2.

**Comment by mesqueeb** [comment]
Maybe support `outlined` on q-btn as well and change documentation to that
But while continuing to support `outline` as well only under the hood

**Comment by rstoenescu** [comment]
I really want final v1.0.0 build to be fresh and clean, not bloated with different stuff. Sorry.
