### ISSUE TITLE
[V1] Possibility to input the same values into QSelect in chips input mode

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3499]
Going here - https://v1.quasar-framework.org/vue-components/select#Example--No-filtering

And try this

![image](https://user-images.githubusercontent.com/10674646/53947848-a280b100-40d7-11e9-8ea0-16de7d6ff95f.png)

see the same values in input
But on docs
![image](https://user-images.githubusercontent.com/10674646/53947897-bd532580-40d7-11e9-859f-289d38a9c5f9.png)

**Comment by nothingismagick** [comment]
If this isn't a bug, here is a codepen for that issue:
https://codepen.io/nothingismagick/pen/YgZpvd?editors=1011

**Comment by rranganathan** [comment]
This happens in the official demo  for select with filter without multiple or chip also. see 
![duplicate](https://user-images.githubusercontent.com/29101582/54013807-78df8c80-41a0-11e9-8efd-e4926102a372.jpg)

**Comment by rstoenescu** [comment]
Will be available in beta.10
