### ISSUE TITLE
[v1 - Request] Make chips input with QSelect more easy

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3500]
Realting to this talks - https://github.com/quasarframework/quasar/issues/3499

I need to make some custom code to make QSelect work as chips input

```
methods: {
    createValue (val, done) {
      if (val.length > 0) {
        if (this.model && this.model.indexOf(val) !== -1) {
          return false
        } else {
          done(val)
        }
      }
    }
  }
```

But it is not good to write this any time i need to use chips input.

I think it will be good if i can write just like this, or other simple way

```
 <q-select
        v-model="material.tags"
        use-input
        use-chips
        multiple
        :label="$t('addEditMaterial.tags')"
        hide-dropdown-icon
        input-debounce="0"
        chips-input
      />
```

And all goes work out of the box.

**Comment by rstoenescu** [comment]
Will be available in beta.10
