### ISSUE TITLE
[v1] preFetch doesn't work when a component is wrapped in Vue.extend

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#3501]
A component like the one below (used for TypeScript)

```js
export default Vue.extend({
  nane: 'DefaultLoggedInLayout',
  preFetch ({ store, currentRoute, previousRoute, redirect, ssrContext }) {
    console.log('Prefetch')
  }
}
```
Won't have preFetch triggered.

I have a fix for it so will sort a PR.

**Comment by ValRush** [comment]
Applied this changes in my project. It works alright in SPA mode with **Vue.extend()**, but yet doesn't work in SSR mode, so I guess some more changes should be done on top of it.

**Comment by webnoob** [comment]
I'm not sure this would be related TBH. The code added to this shouldn't have an effect on SSR. There might be another issue causing problems with it though.

**Comment by ValRush** [comment]
You are right. So I am just saying that something must be done on top of your changes, but I don't know even where to start looking. Tried to find any clue on how to fix the issue, but I am just not competent enough.

**Comment by webnoob** [comment]
So it turns out there is also a `server-entry.js` file (SSR version I think). This might be the reason you've seen issues.

**Comment by rstoenescu** [comment]
Sorry, I've commented on the PR rather than here. Check https://github.com/quasarframework/quasar/pull/3502 for my comments there.
