### ISSUE TITLE
[v1 request] bring back clearable prop for QInput/QSelect

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#3503]
I see that the QInput component used to have a clearable property in v0.17.* :
https://quasar-framework.org/components/input-textfield.html#Vue-Properties

However it was removed in the upgrade to v1:
https://v1.quasar-framework.org/start/upgrade-guide#QInput

I have been using the append slot of q-input elements and specifying a close icon, with code to clear the variable used by the q-input v-model property, however it is tedious and could be simplified with a single clearable prop in QInput.

Would you consider bringing the clearable property back?

Those people who want more customisation could continue to use the append slot.

**Comment by rstoenescu** [comment]
Hi,

Yes, it's been on my mind for a few days now. It will get back in beta.10.

**Comment by RohanTalip** [comment]
Awesome, thanks @rstoenescu !

**Comment by rstoenescu** [comment]
Will be available in beta.12

**Comment by alexdee2007** [comment]
Would be nice if clearable icon hide and appear when mouse hover...
