### ISSUE TITLE
[V1 - BUG] unelevated q-btn-group has shadow on :active

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3504]
even if you choose "unelevated" on `q-btn-toggle` it will have the elevated **box-shadow** on `:active`
```html
<q-btn-toggle
        v-model="model"
        :options="options"
        unelevated
      />
```

<img width="771" alt="screenshot 2019-03-08 09 56 38" src="https://user-images.githubusercontent.com/3253920/53999925-ba643d80-4188-11e9-9dcf-8cb9cfc19486.png">

this shadow appears to be active on the underlying active button's `::before` element.

**Comment by rstoenescu** [comment]
Fix will be available in beta.10
