### ISSUE TITLE
Put a search feature in documentation

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#3505]
I have noticed that it's not easy to find documentation on anything quickly enough. Can you please put a search functionality in Quasar documentation to make easier for referencing.

**Comment by rstoenescu** [comment]
Is this not enough? 

<img width="543" alt="search" src="https://user-images.githubusercontent.com/4665641/54005804-7ca0ee00-4163-11e9-914d-76019505dd46.png">

Or if you're still on 0.17:

<img width="873" alt="search2" src="https://user-images.githubusercontent.com/4665641/54005832-a1956100-4163-11e9-8707-1232f5a96e96.png">
