### ISSUE TITLE
[V1 - BUG] Dialog won't close on ESC in brave-browser

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3507]
So there is a really weird bug in Brave Browser.
I'm using Brave Browser because it's the same chromium engine as Google Chrome but is just faster.

When I open the [dialog from the docs](https://v1.quasar-framework.org/vue-components/dialog#QDialog-API) **in codepen** it works just as expected on brave browser:
- hit esc and the dialog closes

But when I **create a quasar project** on latest beta and open dev server **on brave browser**, it does not work:
- hit esc and nothing happens

While the console log shows the same keycode being detected nothing happens.

### This is a gif showing just that in the Brave Browser
![2019-03-08 13 23 17](https://user-images.githubusercontent.com/3253920/54007584-df1ade00-41a5-11e9-853c-e92b099c95bf.gif)

### Steps to reproduce:
- download and install brave browser (https://brave.com)
- quasar create on beta branch
- add a dialog

**Comment by pdanpdan** [comment]
Please provide a codepen with your code.

**Comment by mesqueeb** [comment]
@pdanpdan 
Sorry I don't see why I should do this. As I explained above:
> When I open the [dialog from the docs](https://v1.quasar-framework.org/vue-components/dialog#QDialog-API) **in codepen** it works just as expected on brave browser:
> - hit esc and the dialog closes

I think Codepen uses other key recognition that allows it to work properly. 😅

**Comment by pdanpdan** [comment]
Then I don't see how I can see the problem.

**Comment by mesqueeb** [comment]
This is the code I use in `pages/Index.vue`

```vue
<template>
  <q-page class="flex flex-center">
    <q-dialog v-model="dialog">
      <div class="bg-white">test modal</div>
    </q-dialog>
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  data () { return { dialog: true } }
}
</script>
```

Just add this on a fresh install of Quasar beta and try closing the dialog through ESC inside Brave Browser. It will not work...

**Comment by nothingismagick** [comment]
Nope, I cannot replicate and I followed your directions. It works as
intended in Brave.

>

**Comment by mesqueeb** [comment]
💥😃🔫

omg whyyyy 😭 another one of those "only on my computer" mysteries.

I guess I'll close it and just pray it magically solves itself. 😳
