### ISSUE TITLE
[V1 - request] `dense` on QTabPanels

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3508]
I require no padding on my panels inside [QTabPanels](https://v1.quasar-framework.org/vue-components/tab-panels#QTabPanels-API).

I'd love to have a `dense` prop that removes all padding.

**Comment by pdanpdan** [comment]
you can add `q-pa-none` on the tab panels
https://codepen.io/anon/pen/JzNJJm?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Let's keep it simple and fast. Adding a prop would make CSS harder to customize. Like pdandan showed you, you can easily choose padding as it is now, thorugh q-p* classes or through a class of your own or through direct style attribute.

**Comment by mesqueeb** [comment]
Ok! 😉
