### ISSUE TITLE
[v1] QPopupProxy does not expose events

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#3509]
### Software version
Dev mode.......... spa
    Pkg quasar........ v1.0.0-beta.9
    Pkg @quasar/app... v1.0.0-beta.8

### codepen
https://codepen.io/anon/pen/MxmEGy?editors=1010

### What did you get as the error?
The @before-show event is not triggered in case of using PPopupProxy, while it works OK with PMenu.

### What were you expecting?
According to the documentation, the events of the underlying components are exposed by PPopupProxy.

**Comment by rstoenescu** [comment]
Fix will be available in beta.10.
