### ISSUE TITLE
Validation rules do not kickin on q-select  with lazy-rules option set

### ISSUE THREAD

**Issue by rranganathan** [quasarframework/quasar#3510]
### Software version

Quasar: 1.0-beta-9

### JsFiddle
https://codepen.io/ravi-codepen/pen/drWVNZ

### What did you get as the error?
With lazy-rule option set on q-select, if i choose an option I expect the 'Please fill  value' error to disappear. In the above codepen, first click on submit to see the validation error and then  choose a select option.
### What were you expecting?
Expect that on a selecting a  value, the validation error to disappear, just like if you type a value in q-input

### What steps did you take, to get the error?
See above codepen. I modified the example form validation code in your docs. Please note, in the codepen if you remove the lazy-rules prop, then it works as expected.

**Comment by rstoenescu** [comment]
Will be available in beta.10
