### ISSUE TITLE
[V1] QSelect overlay

### ISSUE THREAD

**Issue by oliviermorpa** [quasarframework/quasar#3511]
the size of the component is wrong when using 2 <div class="row">
and when using "use-input"

if i remove 'use-input", then it's working.
if i do only one <div class="row">

![image](https://user-images.githubusercontent.com/9378538/54025019-3d5eb580-41d4-11e9-9587-fb7f2b33d511.png)

https://codepen.io/anon/pen/wOdrYL?editors=1010

**Comment by rstoenescu** [comment]
Hi,

What browser or platform (ios, android -- and version!) are you viewing with? Fill in more details please because your codepen looks fine for me:

<img width="382" alt="select" src="https://user-images.githubusercontent.com/4665641/54038072-52cde280-41c8-11e9-90af-e9f1a20be718.png">

**Comment by rstoenescu** [comment]
Fix will be available in beta.10.
