### ISSUE TITLE
q-uploader doesn't work

### ISSUE THREAD

**Issue by ddgll** [quasarframework/quasar#3512]
Hello,

I'm using @quasar/app v1.0.0-beta.10 in srr mode on windows 10 with node 8.10.0 and npm 6.4.1.
I'm developping on the last version of Chrome 72.xxx)

I'm trying to use q-upload but this error occurs on component first loading "The computed property "fields" is already defined as a prop.". 

I've tryed to remove all attributes but url but the error is always here

https://jsfiddle.net/x8skz3o5/

Thank's for your great work ! I'm using quasar for 2 years now and it's the best !
Reguards.

**Comment by pdanpdan** [comment]
Where are you getting the error? On server side or on client side, and in dev or build mode?
What is the exact code you are using?

**Comment by ddgll** [comment]
On client side in development 😉

**Comment by rstoenescu** [comment]
The offender is `:fields="null"` --> either specify it and assign it a Function or Array, or don't specify it at all. Either way, `null` is an invalid value. It should be `undefined`/`void 0` instead.

Please reopen if I missed something. Thank you.

**Comment by ddgll** [comment]
OK ! I think I found my problem, it was because vee-validate by default add a prop named "fields" (fieldsBagName). I've changed this vee-validate config in my vee-validate boot file and the q-uploader work perfectly.
I'm not sure if you have to do somethin but a message in the FAQ or q-uploader DOC may same you some issues ;)

Reguards. Thank You

**Comment by nothingismagick** [comment]
Thanks for the feedback. Its hard for us to know about all the ways things
can break when third party code units are integrated into quasar. If you
think this would be a help, please make a PR on the docs and include this
language. It would be much appreciated.

>
