### ISSUE TITLE
[v1] Split in QDropdownButton causes menu to not display correctly

### ISSUE THREAD

**Issue by Patrick-Spiegel** [quasarframework/quasar#3515]
### Software version

Quasar:
Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.12.0

Global packages
  NPM                           6.8.0
  yarn                          Not installed
  @quasar/cli                   1.0.0-beta.2
Browsers: Chrome

### JsFiddle
https://codepen.io/anon/pen/vPmVrr?&editable=true&editors=101

### What did you get as the error?
The Dropdown is opened in a complete different spot than expected. Not even touching the button. Other Anchor positions aren't working either. 

### What were you expecting?
The drodown opens near the button

### What steps did you take, to get the error?
1. Include the split attribute in a QDropdownButton
2. Set menu-anchor and menu-self
3. Now only bottom-right and top-left are working as expected

**Comment by rstoenescu** [comment]
Hi,

Always check the console for errors. In your case, you are supplying an invalid value for menu-anchor.
`menu-anchor="bottom center"` --> correct is `menu-anchor="bottom middle"`

Play with the positioning of the menu to get correct values: https://v1.quasar-framework.org/vue-components/menu#Positioning

**Comment by rstoenescu** [comment]
Your error is https://monosnap.com/file/vwsX146yAsmJ9T3kQ43uodP0XhYZg2

**Comment by Patrick-Spiegel** [comment]
Hello @rstoenescu,

I have edited the property. Nevertheless it doesn't resolve the actual issue. I have updated the codepen using the middle property instead :)

**Comment by rstoenescu** [comment]
The position is as reference to the arrow button, not the whole group. If you want the menu to reference the whole group, then don't use `split` prop. This is by design.
