### ISSUE TITLE
[V1] CloseMenu directive not working inside QDialog

### ISSUE THREAD

**Issue by rewmike** [quasarframework/quasar#3520]
The `v-close-menu` directive does not work as expecting when used within a `q-dialog`.

### Software version
OS: Windows 10
Browsers: Chrome

### JsFiddle
https://codepen.io/anon/pen/rRmXxq

### What were you expecting?
Menu to close after clicking an item

### What steps did you take, to get the error?
1. Go to: https://codepen.io/anon/pen/rRmXxq
2. Click on the Dialog button to open dialog
2. Click on the Menu to open list of items
3. Click on any list item that is available

**Comment by rstoenescu** [comment]
Hi,

v-close-menu is for QMenu.
v-close-dialog is for QDialog.

**Comment by rewmike** [comment]
Hi @rstoenescu! I should have been more clear on the expected use case here. This is an issue when using `QMenu` nested in `QDialog`.

The expectation is that clicking a `<q-item v-close-menu>` will close the parent `<q-menu>` - even when nested within `<q-dialog>`.

To further explain, I've included a breakdown of what is being attempted.

This is example of a *working* `<q-menu>` in action:

```vue
<q-btn label="Menu" color="primary">
  <q-menu>
    <q-list>
      <q-item v-for="n in 5" :key="n" v-close-menu clickable>
        <q-item-section>Menu Item {{n}}</q-item-section>
      </q-item>
    </q-list>
  </q-menu>
</q-btn>
```

With the help of  `v-close-menu`, the menu is closed when clicking any of the items.

Now, taking this working menu and placing it inside of `<q-dialog>` will break this expected behavior:

```diff
+<q-dialog :value="true">
  <q-card>
    <q-btn label="Menu" color="primary">
      <q-menu>
        <q-list>
          <q-item v-for="n in 5" :key="n" v-close-menu clickable>
            <q-item-section>Menu Item {{n}}</q-item-section>
          </q-item>
        </q-list>
      </q-menu>
    </q-btn>
  </q-card>
+</q-dialog>
```

I am able to work around this by removing `v-close-menu` and managing the state within the component itself, however would prefer not to bother with all that extra code. Example:

```diff
<q-dialog :value="true">
  <q-card>
    <q-btn label="Menu" color="primary">
-      <q-menu>
+       <q-menu v-model="menu">
        <q-list>
-          <q-item v-for="n in 5" :key="n" v-close-menu clickable>
+          <q-item v-for="n in 5" :key="n" @click="menu = false" clickable>
            <q-item-section>Menu Item {{n}}</q-item-section>
          </q-item>
        </q-list>
      </q-menu>
    </q-btn>
  </q-card>
</q-dialog>
```

You can see these examples in CodePen here: https://codepen.io/anon/pen/rRmXxq

Is this a bug or is it just a warning for developers when using QMenu (and this directive) within QDialog?

**Comment by rstoenescu** [comment]
Reopening for an analysis at a later time.

**Comment by rranganathan** [comment]
I ran into this issue today too. The issue label shows closed but the comment above shows it is reopened. Like rewmike suggested,  will use the model route for now but prefer a cleaner fix

**Comment by rstoenescu** [comment]
Fix will be available in beta.11.
