### ISSUE TITLE
[V1] QCarousel height through CSS

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#3521]
I'm not sure if this is considered a bug or feature request, but if I use a css class to specify the  height on QCarousel the slides do not fill the height of it. I would like to be able to use css breakpoints to adjust the QCarousel height. This was working on 0.17.

### Software version
Quasar:
@quasar/app (v1+ only):  1.0.0-beta.10
Operating System - Darwin(17.7.0) - darwin/x64
NodeJs - 10.13.0
NPM - 6.4.0
yarn - 1.13.0
Browsers: chrome, safari, firefox
iOS:
Android:
Any other software related to your bug:

### Codepen
The differences can be seen here:
https://codepen.io/smakinson/pen/LaLYRB

### What did you get as the error?
The height of QCarouselSlide does not fill 100% of QCarousel.

### What were you expecting?
The height of QCarouselSlide will fill 100% of QCarousel.

### What steps did you take, to get the error?
Instead of using the height property on QCarousel, I used a class name that specifies a height.

**Comment by rstoenescu** [comment]
Fix will be available in beta.10.
