### ISSUE TITLE
[v1] Documentation page for QDate is broken

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#3522]
No examples show up on https://v1.quasar-framework.org/vue-components/date

This is in Chrome's console:
```
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

In Safari's console, I see this:
```
Unhandled Promise Rejection: HierarchyRequestError: The operation would yield an incorrect node tree.
```

I think this is a recent breakage.  I think it was working a few days ago and maybe even as recent as yesterday or earlier today.

**Comment by RohanTalip** [comment]
In Firefox's console, I see this:
```
Unhandled promise rejection DOMException: "Node cannot be inserted at the specified point in the hierarchy"
```

**Comment by rstoenescu** [comment]
This is a hydration error. Start from another page within docs then visit Date page.
Thanks for reporting.

**Comment by rstoenescu** [comment]
Fix will be available with next deployment.
