### ISSUE TITLE
[v1][Uploader][tip] property "fields" is already defined with vee-validate

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#3523]
quasar beta 9.

I use vee-validate. Q-Uploader uses "fields" prop. Vee-validate uses the same prop named "fields". It gets a error: The computed property "fields" is already defined as a prop. Vee-validate can change prop name on init: fieldsBagName: 'veeFields' - in options.

I place this in issues as tip to help other peoples whos get this error. And maybe you can place tip in the quasar docs?

**Comment by mstaack** [comment]
was done here: https://github.com/quasarframework/quasar/pull/3534/files

this can be closed.
