### ISSUE TITLE
[v1] Proposal - openPhone() for cordova + PWA

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#3524]
Many users are trying to use openURL() to pass a `tel:12345896` and expecting the phone app to open. This does not work, and it seems that we should create a function for them to use, because this is likely to break on SSR + PWA: `window.location.href = 'tel:' + this.phone`...

https://github.com/quasarframework/quasar/blob/dev/quasar/src/utils/open-url.js#L8

**Comment by rstoenescu** [comment]
Devs should directly use `<a href="tel:12344">` tags or `<QBtn type="a" href="tel:123455">`, and not openURL() in order to benefit from how Cordova handles this.
If it's not clear, it should be in docs. @nothingismagick care to add this pls?

**Comment by nothingismagick** [comment]
#3567
