### ISSUE TITLE
[v1]QPopupProxy - Does not follow the parent component

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3528]
In a div with a calc height, QPopupProxy does not follow the parent component when the div scrolls.
### Reproduction Link
https://codepen.io/qq34205037/pen/NJvgzq?editors=1010

#### step 2.Don't close it and scroll the page(div)

**Comment by QQ34205037** [comment]
I guess Quasar only calc the location of QPoupProxy when the page (HTML body) scrolls, but sometimes you don't want to see the global scrollbar, What's the best way to solve this problem?

**Comment by pdanpdan** [comment]
QPopupProxy searches for a parent with overflow class.
Add an `overflow-auto` class like here: https://codepen.io/anon/pen/moMXGp?editors=1010

**Comment by QQ34205037** [comment]
Great, Thank you very much. @pdanpdan
