### ISSUE TITLE
[suggestion] default margin paragraph

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3529]
The default margin-bottom under a paragraph `<p>` is defined like so:
```styl
p
  margin: 0 0 $spaces.md.y
```
which translates to `margin-bottom 16px` by default.

However, I feel that if we have paragraphs with smaller text-sizes (like 14px) the padding seems really large.

I think that just for `<p>` the margin is better expressed in `em` as it will adjust to the actual paragraph's text size.

The screenshot below shows the default margin of 16px vs a margin of 1em:

<img width="359" alt="Screenshot 2019-03-11 15 36 09" src="https://user-images.githubusercontent.com/3253920/54104472-6751eb00-4413-11e9-9edc-77a0f16a887e.png">

I just think 1em looks much better. : )

**Comment by rstoenescu** [comment]
Hi,

This is per Material guidelines. If they changed it in the mean time (it may happen as they update the specs weekly), please let me know.

Otherwise, you can just override that CSS to make it custom.
