### ISSUE TITLE
Incorrect ripple location for router-link in toolbar

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#3530]
### Software version

Quasar v1.0.0-beta.9

### What did you get as the error?

Ripples appear in the top-left of the toolbar, not on the router-link itself.

### What were you expecting?

The ripples would appear on the router-link itself.

### What steps did you take, to get the error?

See https://codepen.io/RohanTalip/pen/LajORe

**Comment by pdanpdan** [comment]
Add a `relative-position` class on `router-link` - it has no styling by default.
Like this: https://codepen.io/anon/pen/xBLYOb

**Comment by rstoenescu** [comment]
From [Ripple](https://v1.quasar-framework.org/vue-directives/material-ripple#Introduction) docs:

```
WARNING
Make sure that your DOM element or component has CSS position: relative or Quasar CSS helper class relative-position attached to it.
```

**Comment by RohanTalip** [comment]
Thanks!
