### ISSUE TITLE
[V1 - documentation] use utils in UMD

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3531]
Add a section how to use utils, eg. [Date utils](https://v1.quasar-framework.org/quasar-utils/date-utils) in Codepens / UMD version.

Perhaps it's written somewhere in another place, but I can't find it. 😳 so a link to how to use utils at the top of each util page would be great!

IF they are not available in codepens / UMD, we might consider writing that at the top of each util page.

**Comment by pdanpdan** [comment]
https://v1.quasar-framework.org/start/umd#Quasar-Global-Object
