### ISSUE TITLE
[v1][QDialog] Bring back chainable hide() and show()

### ISSUE THREAD

**Issue by tegola** [quasarframework/quasar#3532]
In v0.17 QModal hide() returned a promise, so I was able to wait for the animation to end before continuing, e.g.:

```javascript
onCancel () {
  this.$refs.modal.hide().then(() => {
    ...
  })
}
```

The new QDialog doesn't support such behavior, so everything after `hide()` gets called while the dialog is hiding, which is not what I want.

**Comment by pdanpdan** [comment]
You can use the `@hide` listener on the QDialog - it is triggered after the dialog is done hiding.

**Comment by rstoenescu** [comment]
this.$refs.modal.$once('hide', () => { ..... })
this.$refs.modal.hide()

**Comment by tegola** [comment]
@pdanpdan Yes! I was just answering my own question, but since I need different behavior every time, I'm using it like this:

```javascript
onCancel () {
  this.$refs.modal.hide()
  this.$refs.modal.$once('hide', () => {
    ...
  })
}
```

Thanks

**Comment by ajcastro** [comment]
IMO, I believe promise chains are always better because they are more readable and code become more concise
