### ISSUE TITLE
[0.17] QTable sorting does not work if no pagination

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#3541]
Hello!

Steps to reproduce:
1) Create a table
2) Disable pagination
3) Test sorting https://jsfiddle.net/f1ku2ten/ - does not work
4) Remove pagination prop - works ok

Thanks!

**Comment by rstoenescu** [comment]
`pagination` needs to have `.sync` modifier as per docs.
Set a variable in your data() and point to it. `:pagination.sync="myPagination"`
