### ISSUE TITLE
[v1] Button still go on `to` when disabled.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3542]
If click on `QBtn` with `disabled` it still goes on `to`

**quasar** - 1.0.0-beta.9
**@quasar/app** - 1.0.0-beta.10

**Comment by nothingismagick** [comment]
Thanks for the report. Can you please include a codepen showcasing this error.

**Comment by pdanpdan** [comment]
`disable`, not `disabled`

**Comment by Dmitrij-Polyanin** [comment]
Tried `disable` and `disabled`, both not working.
Both affect style, but still goes on `to`

**Comment by Dmitrij-Polyanin** [comment]
@nothingismagick I can not. Router I think can not work in sendbox environment like jsfiddle or codepen

**Comment by nothingismagick** [comment]
fine, then please post a code example here.

**Comment by Dmitrij-Polyanin** [comment]
This code
```
   <q-btn :disable="true" to="/mytestpath"   label="TestBtn">
```
The same is with `disabled`

**Comment by Dmitrij-Polyanin** [comment]
I think it will be very helpfull to make playground with full set working, router vuex and all main

**Comment by pdanpdan** [comment]
Ok, I found it, I'll make a PR soon.
