### ISSUE TITLE
[V1][Request] Add slot to QStepper for common messaging across steps

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#3543]
On v0.17 I was using a div as a child of QStepper (along with the QSteps) to include a header and error messaging for a stepped donation form. In v1 the div is ignored, so I thought it might be useful for a slot that would allow including the messaging again. It would render just below the navigation.

**Comment by rstoenescu** [comment]
Hi,

But you can use the navigation slot for that error too.. Am I missing something?

**Comment by smakinson** [comment]
@rstoenescu I could be missing something, I'm trying add it just below the QStep tabs at the top and also take up space ( not use absolute positioning ) It does show if I put it in the navigation slot, but down at the bottom.

**Comment by rstoenescu** [comment]
Ok, I'll add a slot for this.

**Comment by smakinson** [comment]
Thank you!

**Comment by rstoenescu** [comment]
QStepper slot "message" -- will be available in beta.11.
