### ISSUE TITLE
q-page-sticky not showing (correctly) in q-layout-drawer - jsfiddle attached

### ISSUE THREAD

**Issue by trsiddiqui** [quasarframework/quasar#3544]
I am using the standard jsfiddle from the latest Quasar playground section in documentation. 

If you look at the markup at [THIS JSFIDDLE](https://jsfiddle.net/985t73qd/1/), q-page-sticky is placed inside a q-layout-drawer (side = right). However, if you try opening the drawer in the application, you will see a button travelling quickly from right to left but it doesn't stay. There is also a scrollbar due to extra whitespace in the right drawer no matter what the height of your window is.

**Comment by rstoenescu** [comment]
Hi,

Why would you use a QPageSticky inside of a QDrawer? QPageSticky is meant for the... page.
Just use CSS on your button with `position: absolute; right: 16px; bottom: 16px`
