### ISSUE TITLE
QRouteTab incorrect active tab on redirects

### ISSUE THREAD

**Issue by GrandUltimate** [quasarframework/quasar#3545]
### Software version

Quasar: 1.0.0-beta.9
@quasar/app (v1+ only):
OS: Ubuntu
Node: 8.10.0
NPM: 6.8.0
Browsers: Firefox 65.0.1, Chromium 72.0.3626.121

### What did you get as the error?
QRouteTab doesn't doesn't always correctly set selected tab relative to route when the route has a redirect:

### What were you expecting?
Selected  QRouteTab should always reflect the current route

### What steps did you take, to get the error?
QRouteTab Tab with `name="routeName"` reached by
```
redirect: { name: 'routeName' }
```

**Comment by pdanpdan** [comment]
Sorry, I cannot reproduce it. Can you please provide a codepen, or a repo to check?

**Comment by rstoenescu** [comment]
Please reopen with a barebones repo so we can check, otherwise this ticket is going to hang on forever. Thank you.
