### ISSUE TITLE
QEditor in MSIE 11 does not output formatting tags (bold/unorderd list...)

### ISSUE THREAD

**Issue by NicoP-S** [quasarframework/quasar#3547]
Quasar: 
Quasar CLI........ v0.17.24
Quasar Framework.. v0.17.20
OS: Windows 10
Node: v8.15.0
NPM: 6.4.1
Browsers: IE 11

### JsFiddle
https://jsfiddle.net/ek2zcb4o/4/ 

### What did you get as the error?
In Internet Explorer (11) the q-editor does not output the formatting like bold or unorderd list.
In firefox and chrome it runs well.

### What were you expecting?
The same output in all Browsers

### What steps did you take, to get the error?
Just start the jsfiddle in IE and try to make text bold or an unorderd list. 
The model does not contain the tags.

**Comment by mstaack** [comment]
you did not add the ie11 polyfill. check https://quasar-framework.org/guide/embedding-quasar.html

**Comment by NicoP-S** [comment]
@mstaack you are right. I added the ie11 polyfill but it's still the same.
Updated jsfiddle: https://jsfiddle.net/sutyfam1/

nevertheless i am using quasar with webpack and IE11 is enabled in quasar conf

**Comment by rstoenescu** [comment]
Fix will be available in beta.14
