### ISSUE TITLE
[v1] QSelect did not show label properly if model change in code 

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3550]
Here is [fiddle](https://jsfiddle.net/45fwudb8/).

```
 <q-select label="TestingSelect" v-model="selectValue" :options="[
 {label:'One',value:'1'},
 {label:'Two',value:'2'},
 {label:'Three',value:'3'},
 ]" />
```
```
  created() {
      this.selectValue = "2";
  }
```
Showes "2", not "Two".

If I mannualy set model value of QSelect it showes value in field, but not label.

In this example I think it should thoes "Two", not "2".

In previous versions code works in normal way and showes "Two".

**Comment by pdanpdan** [comment]
Use `emit-value` and `map-options` like here:
https://jsfiddle.net/2wknjdut/

or like in the docs
https://v1.quasar-framework.org/vue-components/select#Affecting-model

**Comment by Dmitrij-Polyanin** [comment]
Thanks!
