### ISSUE TITLE
[v1 - Request] QTree to make option to disable unselecting already selected item

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#3551]
If I have QTree with standart selection mode (not tiked).

I can select some node and then second click on the same node and it will deselect it and reset QTree selection state to null.

It is very strange. QSelect, for example on 2 ckick on the same item just stay selected on it.

I think it needed to disable 2 click on item with unselecting it.
Or if this behavior is suspected, to do option to disable it.

Why I need it?

Is very usual case when i have to choose one of tree and not null.

Now to make this functionality bu custom is difficult.

My code to make work it:
```
<q-tree @update:selected="categorySelected" 
                  :selected.sync="treeSelectValue"
                  :nodes="nodes" />

categorySelected(key) {
    if(!key)
    {
        let old = this.treeSelectValue;
        this.$nextTick(() => {this.treeSelectValue = old});
    }
}
```

But I think this need to be done more clear, simple and natively has to be natively

**Comment by gillisig** [comment]
I had the same use case and your code worked perfectly.  Thanks @Dmitrij-Polyanin

**Comment by yarox** [comment]
I also had the same problem, but made it work watching the `treeSelectValue` variable:

```
...
watch: {
    treeSelectValue: function (newVal, oldVal) {
      if (!newVal) {
        this.treeSelectValue = oldVal
      }
    }
  },
...
```

**Comment by Dmitrij-Polyanin** [comment]
Very good, more clean then my code.

**Comment by pdanpdan** [comment]
It's very simple:

```html
<q-tree :nodes="nodes" :selected="selected" @update:selected="updateSelected" />
```

```javascript
updateSelected (key) {
  if(key !== null) {
    this.selected = key
}
```
