### ISSUE TITLE
[v1] v-slot:append in QSelect breaks layout

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#3554]
See pen:

https://codepen.io/tomers-the-encoder/pen/JzOYpN

**Comment by pdanpdan** [comment]
Yep, it's fixed in the next release.
I just put here (https://codepen.io/anon/pen/ZPaVjJ?editors=1000) the fix (CSS tab, the only rule there) so if you need it right now you can use this.

**Comment by rstoenescu** [comment]
Will be available in beta.10.
