### ISSUE TITLE
[v1] Getting v-close-menu and v-ripple to work together

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#3555]
Pen below showing the challenge. A popup menu containing a checkbox to toggle the state of something and also close the menu. It doesn't seem possible to allow the ripple effect and checkbox state change to be clearly seen by the user before the menu is closed. Is there a way the ripple can complete _before_ the close event is processed?

https://codepen.io/dsl101/pen/BbmWRa

Also not 100% clear why the middle 2 options don't actually change the state of the 'thing', but I assume it's because of the order of event handling.

Not sure if this would break anything else, but could `v-ripple` have 'precedence over `v-close-menu` (and ideally also over a menu with `auto-close` prop), so that if the 2 are used together, `v-ripple` gets to complete first? And would this solve the non-functioning of the middle two methods in the pen above?

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, making these kind of workarounds just to fit one scenario is not optimal.
If you want this to work, then use a v-model on the Popup and add your own `@click` handler which delays Popup model change a bit so that v-ripple is shown.
