### ISSUE TITLE
[v1] QPopupProxy isn't hide when value prop is updated to false

### ISSUE THREAD

**Issue by TobyMosque** [quasarframework/quasar#3556]
### Software version

@quasar/app (v1+ only): 1.0.0-beta.9
OS: Windows
Browsers: Opera
Any other software related to your bug:

### JsFiddle
https://codepen.io/tobias-mesquita/pen/EMboqe?&editable=true&editors=101

### What did you get as the error?
`QPopupProxy` didn't close/hide after your `value` prop update to false

### What were you expecting?
The popup would close when u `value` is updated to false

### What steps did you take, to get the error?
Open the popup clicking in the `Handles Click` button, so try to dismiss the popup clicking in the `Close` button.

**Comment by rstoenescu** [comment]
Fix will be available in beta.11
