### ISSUE TITLE
[v1] ? Race condition in q-route-tab setting active state

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#3564]
I've really struggled to recreate this in Codepen I'm afraid, as I think it is a timing issue which is affecting my 'live' app, but not showing up in a dummy small test case. For reference, here's the template source with extraneous class stuff taken out

```
<q-tabs dense align="left" active-color="primary">
  <q-route-tab label="Dashboard" to="dashboard" />
  <q-route-tab label="Members" to="members" />

  <router-link tag="q-btn" to="dashboard" active-class="text-red">Dashboard</router-link>
  <router-link tag="q-btn" to="members" active-class="text-red">Members</router-link>
</q-tabs>
```

This is how it should look, and does when first landing on the app (route is /foo/dashboard):

![image](https://user-images.githubusercontent.com/900542/54299617-2f81a980-45b3-11e9-8c1d-fb5436998ef5.png)

But when I navigate to a different route (programmatically) , I end up with this (route is /bar/members):

![image](https://user-images.githubusercontent.com/900542/54299966-e120da80-45b3-11e9-9bf9-cb8eb1ae89d0.png)

Note how the `router-link` component active state is correct (the red highlight matches the route), but the `q-route-tab` is still on 'Dashboard'. I've found that I can 'fix' this by changing the QRouteTab.js `watch.$route()` function like this:

```
watch: {
  $route () {
    this.$nextTick(() => {
      setTimeout(this.__checkActivation, 100)
    })
  }
},
```

i.e. delaying the call to `__checkActivation()`. It seems that function bases its decision on applied classes, and those are not set up in time for the immediate call. But delaying it by 100ms or so is enough to get round the problem.

Clearly that's a hack not a fix, but hopefully points to the race condition?

**Comment by pdanpdan** [comment]
I need you to check something.
Reverse the order of tabs (first Members then Dashboard) and tell me which of them remains on the wrong option.

**Comment by dsl101** [comment]
I behaves the same:
![image](https://user-images.githubusercontent.com/900542/54378221-c4050e00-467e-11e9-9d3e-613eb5b7c43c.png)
and
![image](https://user-images.githubusercontent.com/900542/54378241-d0896680-467e-11e9-8ddf-5068e8308b64.png)

To clarify, say I have a QDrawer with links that route to one of /foo/dashboard, /bar/members, or /baz/dashboard, then whichever tab was active 'previously' stays active, regardless of the route. So going from /foo/dashboard to /baz/dashboard, the tab is 'correct', because it should be Dashboard for both. But going from /foo/dashboard or /baz/dashboard to /bar/members, the Dashboard q-route-tab stays active (when the router-link changes).

The order of the tabs doesn't not seem to make any difference to this behaviour.

Also, _sometimes_, the correct tab is displayed, and that's what I found in a codepen. Lots of data is loaded (some asynchronously from firebase) by the main page component, and the Dashboard / Members components. So I do think timing is a key issue here. Here's the full head of the template, so you can also see there are some conditionals in there which add to the complexity:
```
<template>
  <h5 v-if="isLoading" style="padding-left: 20px">Loading...</h5>
  <h5 v-else-if="!isValidEvent()" style="padding-left: 20px">No such event.</h5>
  <div v-else>
    <div v-if="!isAdmin()" class="layout-padding">
      <p>When pages are added to this event, they can be accessed from the menu button at the top left.</p>
    </div>
    <div v-else>
      <!-- Setting Tabs -->
      <q-tabs v-if="!isValidPage()" dense align="left" active-color="primary">
        <q-route-tab label="Members" to="members" />
        <q-route-tab label="Dashboard" to="dashboard" />

        <router-link tag="q-btn" to="members" active-class="text-red">Members</router-link>
        <router-link tag="q-btn" to="dashboard" active-class="text-red">Dashboard</router-link>
```

**Comment by pdanpdan** [comment]
Please make a short test for me - add `"quasar": "https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.10-gitpkg",` in your application's `package.json` under `"dependencies"`.

Do a `yarn && quasar dev` and tell me if you can still reproduce it.

**Comment by dsl101** [comment]
Yes, I'm afraid so. I added `<pre>{{$route.fullPath}}</pre>` above the tabs to double-check:

![image](https://user-images.githubusercontent.com/900542/54418482-f8b7aa80-46fc-11e9-8659-53dc2e659d08.png)

I also added a `console.log(this.$route)` right before the `setTimeout()` call in the watch function of `QRouteTab.js`, and this is the output:

![image](https://user-images.githubusercontent.com/900542/54418614-59df7e00-46fd-11e9-88b2-02dba18c0c3f.png)

So it's being called 3 times, but even on the first time the navigation is confirmed and the route is updated.

Let me know if there's anything else I can try. The app is semi-public so I can probably give you access to the front end if that's useful.

**Comment by pdanpdan** [comment]
Can you please try again with `"quasar": "https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.10.1-gitpkg",`

**Comment by dsl101** [comment]
Sorry, no joy. Now with `<pre>{{version}}: {{$route.fullPath}}</pre>` to check I'm using the update:

![image](https://user-images.githubusercontent.com/900542/54431958-b489d180-471f-11e9-8d65-5e23f2acf9fa.png)

**Comment by pdanpdan** [comment]
I need the `to` and `fullPath` for all 3 tabs.

**Comment by dsl101** [comment]
Sorry, not sure which '`to`' you're asking for. Do you mean in the template, or as passed into the route guards, or something else? The `$route.fullPath` for all 3 tabs is:
```
/-LD7DBdsqpxlCoqmcTsy/dashboard
/-LD7DBdsqpxlCoqmcTsy/members
/-LD7DBdsqpxlCoqmcTsy/pages
```

**Comment by pdanpdan** [comment]
The `:to` set in each QRouteTab (and also if you set `exact` on them)

**Comment by dsl101** [comment]
Regarding the `:to`, if that's not what's in the template source at the top of this issue (I added a third, but the problem is unchanged), I'm still unsure what you're after. This is how the template looks now:
```
<q-tabs v-if="!isValidPage()" dense align="left" active-color="primary">
  <q-route-tab label="Dashboard" to="dashboard" />
  <q-route-tab label="Members" to="members" />
  <q-route-tab label="Pages" to="pages" />

  <router-link tag="q-btn" to="dashboard" active-class="text-red">Dashboard</router-link>
  <router-link tag="q-btn" to="members" active-class="text-red">Members</router-link>
  <router-link tag="q-btn" to="pages" active-class="text-red">Pages</router-link>
```
The links for each QRouteTab look correct:

Dashboard: http://localhost:8080/-LD7DBdsqpxlCoqmcTsy/dashboard
Members: http://localhost:8080/-LD7DBdsqpxlCoqmcTsy/members
Pages: http://localhost:8080/-LD7DBdsqpxlCoqmcTsy/pages

And via devtools, if I inspect each element I see this.

Dashboard:
```
<a data-v-7dcafda6="" href="/-LD7DBdsqpxlCoqmcTsy/dashboard" class="q-tab relative-position self-stretch flex justify-center text-center q-router-link--exact-active q-router-link--active q-tab--inactive q-focusable q-hoverable cursor-pointer" data-vivaldi-spatnav-clickable="1" tabindex="0" role="tab"><div class="q-focus-helper"></div><div class="q-tab__content flex-center relative-position no-pointer-events non-selectable column"><div class="q-tab__label">Dashboard</div></div><div class="q-tab__indicator absolute-bottom"></div></a>
```

Members:
```
<a data-v-7dcafda6="" href="/-LD7DBdsqpxlCoqmcTsy/members" class="q-tab relative-position self-stretch flex justify-center text-center q-tab--inactive q-focusable q-hoverable cursor-pointer" data-vivaldi-spatnav-clickable="1" tabindex="0" role="tab"><div class="q-focus-helper"></div><div class="q-tab__content flex-center relative-position no-pointer-events non-selectable column"><div class="q-tab__label">Members</div></div><div class="q-tab__indicator absolute-bottom"></div></a>
```

Pages:
```
<a data-v-7dcafda6="" href="/-LD7DBdsqpxlCoqmcTsy/pages" class="q-tab relative-position self-stretch flex justify-center text-center q-tab--active text-primary q-focusable q-hoverable cursor-pointer" data-vivaldi-spatnav-clickable="1" tabindex="-1" role="tab" aria-selected="true"><div class="q-focus-helper"></div><div class="q-tab__content flex-center relative-position no-pointer-events non-selectable column"><div class="q-tab__label">Pages</div></div><div class="q-tab__indicator absolute-bottom"></div></a>
```

**Comment by dsl101** [comment]
Btw, switching _between_ tabs on a single event is fine. That's not the issue. It's switching between events which is the problem. I'm just gathering the relevant info for that. I can send you a pen which shows how it's set up, but _doesn't_ have the same symptoms, which is what led me to think it's a timing issue. Please wait a few minutes for me to find it.

**Comment by pdanpdan** [comment]
I have one more idea. Are you changing to more than one route one after another very fast from code?

**Comment by dsl101** [comment]
I was in the middle of a big explanation, but yes :). The Event component has a guard and redirects to a sub-component based on where the user was last. See this pen which has the same setup (fast redirect) but _not_ the problem: https://codepen.io/dsl101/pen/aMJQdj

I've hard-coded it so that Event 1 redirects to Component 1, and Event 2 redirects to Component 2.

I understand in my case that fetching the last tab from firebase will be slow, and hence I think the 2 get out of step.

**Comment by dsl101** [comment]
Wait, is it fixed? Is there a pkg I can try?

**Comment by pdanpdan** [comment]
No, sorry, it was autoclosed, please reopen.

**Comment by rstoenescu** [comment]
Fix will be available in beta.11

**Comment by pdanpdan** [comment]
Ok, time for `https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.10.2-gitpkg`

**Comment by dsl101** [comment]
Sad face. Navigating from:

`http://localhost:8080/-LJZVx_wTH2UyNGwvXLv/pages` to
`http://localhost:8080/-LD7DBdsqpxlCoqmcTsy`

causes the route guard to look up the last active tab for the new event (`-LD7DBdsqpxlCoqmcTsy`), and then run `next('-LD7DBdsqpxlCoqmcTsy/dashboard')` and so the final URL is

`http://localhost:8080/-LD7DBdsqpxlCoqmcTsy/dashboard`

and results in:

![image](https://user-images.githubusercontent.com/900542/54444872-84e8c280-473b-11e9-9b77-9dd0e7bd974c.png)

The reason the Pages QRouteTab is active is because it was active on the first URL. If that URL had ended `/members`, it would be the Members tab that was active. Again, I can still fix this by delaying the call to `__checkActivation()` in QRouteTab.js:
```
  watch: {
    $route () {
      setTimeout(this.__checkActivation, 100)
    }
  },
```
I notice there is a small delay in the RouterLink active class being applied (i.e. the text for those additional buttons is all black when the page first loads, and then one of them changes to red). That's what gave me the idea it was a timing issue. Clearly 100ms is just randomly OK for my current app / network conditions and so not a fix. But still unsure what the cause is. Anything else I can do to help debug, please do let me know.

**Comment by pdanpdan** [comment]
Can you replace on that last version
``` javascript
  watch: {
    $route () {
      this.__checkActivation()
    }
  },
```
with 

``` javascript
  watch: {
    $route () {
      this.$nextTick(this.__checkActivation)
    }
  },
```

**Comment by pdanpdan** [comment]
Or better, replace it with

```javascript
  watch: {
    $route () {
      this.__checkActivation()
    },
    to () {
      this.__checkActivation()
    },
    append () {
      this.__checkActivation()
    }
  },
```

**Comment by dsl101** [comment]
Results:
```
 watch: {
    $route () {
      this.$nextTick(this.__checkActivation)
    }
  }
```
= no change.

```
$route () {
      this.__checkActivation()
    },
    to () {
      this.__checkActivation()
    },
    append () {
      this.__checkActivation()
    }
```
= no change

Using object `:to` in conjunction with above:
```
        <q-route-tab label="Dashboard" :to="{name: 'dashboard'}" />
        <q-route-tab label="Members" :to="{name: 'members'}" />
        <q-route-tab label="Pages" :to="{name: 'pages'}" />
```
= no change

The router guard in Event.vue is this
```
  const loadTab = (to, from, next) => {
    console.log('to.name:', to.name)
    if (to.name === 'Event') {  // We landed on the project 'home', so move to whichever tab is default
      const lastTab = store.getters.lastTab(to.params.event) || 'dashboard'
      console.log('to.fullPath:', to.fullPath)
      console.log('lastLoc:', lastTab)
      console.log(`calling next(/${to.params.event}/${lastTab})`)
      next(`/${to.params.event}/${lastTab}`)
    } else {
      console.log('calling next()')
      next()
    }
  }
```

`loadTab()` is called by both `beforeRouteEnter()` and `beforeRouteUpdate()` in Event.vue. The console output for that above navigation looks like this:
```
16:39:04.878 Event.vue?abcc:157 to.name: Event
16:39:04.878 Event.vue?abcc:160 to.fullPath: /-LD7DBdsqpxlCoqmcTsy/
16:39:04.878 Event.vue?abcc:161 lastLoc: dashboard
16:39:04.878 Event.vue?abcc:162 calling next(/-LD7DBdsqpxlCoqmcTsy/dashboard)
16:39:04.878 Event.vue?abcc:157 to.name: dashboard
16:39:04.879 Event.vue?abcc:165 calling next()
```

Don't know if that sheds any further light on it...

**Comment by pdanpdan** [comment]
Oh, shit - you don't have name on `QRouteTab`.
```javascript
<q-route-tab name="unique_name_in_parent_q-tabs" to="..." exact label="..." />
```

**Comment by pdanpdan** [comment]
`https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.10.3-gitpkg`

It's a debug build.
Please clear console and perform a navigation. I would like the details in the console.

**Comment by dsl101** [comment]
I added `name`, but no difference:
```
        <q-route-tab name="dashboard" label="Dashboard" exact :to="{name: 'dashboard'}" />
        <q-route-tab name="members" label="Members" exact :to="{name: 'members'}" />
        <q-route-tab name="pages" label="Pages" exact :to="{name: 'pages'}" />
```

Here's the console output doing that same navigation as before:
```
17:41:32.644 Event.vue?abcc:157 to.name: Event
17:41:32.644 Event.vue?abcc:160 to.fullPath: /-LD7DBdsqpxlCoqmcTsy/
17:41:32.644 Event.vue?abcc:161 lastLoc: dashboard
17:41:32.644 Event.vue?abcc:162 calling next(/-LD7DBdsqpxlCoqmcTsy/dashboard)
17:41:32.644 Event.vue?abcc:157 to.name: dashboard
17:41:32.644 Event.vue?abcc:165 calling next()
17:41:32.885 QRouteTab.js?7867:22 watch $route {name: "dashboard", meta: {…}, path: "/-LD7DBdsqpxlCoqmcTsy/dashboard", hash: "", query: {…}, …} {name: "dashboard"}
17:41:32.887 QRouteTab.js?7867:22 watch $route {name: "dashboard", meta: {…}, path: "/-LD7DBdsqpxlCoqmcTsy/dashboard", hash: "", query: {…}, …} {name: "members"}
17:41:32.888 QRouteTab.js?7867:22 watch $route {name: "dashboard", meta: {…}, path: "/-LD7DBdsqpxlCoqmcTsy/dashboard", hash: "", query: {…}, …} {name: "pages"}
17:41:32.898 QTabs.js?429b:154 __activateRoute 1407 (2) [{…}, {…}] {name: "pages", selectable: true, exact: true}
```

I've also expanded the objects out:
![image](https://user-images.githubusercontent.com/900542/54451070-ddbf5780-4749-11e9-8cf5-f3f288f6e041.png)

**Comment by pdanpdan** [comment]
`https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.10.4-gitpkg`

**Comment by dsl101** [comment]
Yes, yes, yes! I really want to see the diff though :).

Working as expected now.

**Comment by pdanpdan** [comment]
https://github.com/quasarframework/quasar/pull/3592

**Comment by rstoenescu** [comment]
Fix will be available in beta.11.

**Comment by pdanpdan** [comment]
@dsl101 
Hi.

Can you please check this version in your app: https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.10.3-gitpkg

Tell me if I broke something - it should refine the selection more and fix some problems with redirects.

**Comment by dsl101** [comment]
Of course, but I am working away now so it will be several days before I’m back in the office. I will update here as soon as I can. Tx.

**Comment by dsl101** [comment]
I don't see any difference with this version and the previous one which fixed the bug (which I'm assuming is a good sign :). But I'm not sure if there's anything specific I can test, or whether you were just wanting to make sure in my case the redirect & tab matching still worked. If so, then yes, all is good. Tx.

**Comment by pdanpdan** [comment]
Just checking I didn't break your case :). Thank you, it's good.
