### ISSUE TITLE
[v1] Split in QDropdownButton causes menu to not display correctly

### ISSUE THREAD

**Issue by Patrick-Spiegel** [quasarframework/quasar#3569]
Duplicate of #3515. However, it looks like its just getting ignored while it is closed.

### Software version

Quasar:
Operating System                Windows_NT(10.0.17134) - win32/x64
NodeJs                          8.12.0

Global packages
  NPM                           6.8.0
  yarn                          Not installed
  @quasar/cli                   1.0.0-beta.2
Browsers: Chrome

### JsFiddle
https://codepen.io/anon/pen/vPmVrr?&editable=true&editors=101

### What did you get as the error?
The Dropdown is opened right of the splitter instead of the whole button group.

### What were you expecting?
The drodown opens near the button

### What steps did you take, to get the error?
1. Include the split attribute in a QDropdownButton
2. Set menu-anchor and menu-self
3. Now only bottom-right and top-left are working as expected

**Comment by rstoenescu** [comment]
"The Dropdown is opened right of the splitter instead of the whole button group." --> this is how it's designed to work when using `split` prop.
If you want it for the whole "group" don't use `split`. This is not a bug.
