### ISSUE TITLE
[Request] DataTable Filter Column Headers

### ISSUE THREAD

**Issue by Async0x42** [quasarframework/quasar#357]
This is similar to SharePoint functionality for data tables, basically for each column header (if filterable), you'd get a pretty select dropdown to choose, integrated into the data table. My demo here doesn't support multi-select, but an option to single or multi-select filters would make this perfect.

![filter dropdown](https://cloud.githubusercontent.com/assets/3268854/22409750/05571f1c-e65d-11e6-9290-c33b4ebfe96c.gif)

**Comment by rstoenescu** [comment]
Nice idea. Will see about it.

**Comment by kdmon** [comment]
I would like to add that it would be great if the column headers and filters could be designed so that they are also reachable via keyboard/tab browsing.

**Comment by colinmollenhour** [comment]
I find that in many cases using column headers is too limiting and you want to filter by something that isn't visible. Also this ties the filtering to the presentation and you run into issues where the filter needs more width than the column and so you are wasting table width for wide filters. A huge improvement IMO is using chips and a list of filter options. An excellent example is seen on Intercom.com's user list:

![image](https://user-images.githubusercontent.com/38738/42704259-2eedb9bc-869d-11e8-8fdb-81a217493035.png)

Note, a component implemented in this way would be useful for more than just tables, it could be used for filtering lists, points on a map, a grid full of tiles, etc. So I think not only is it more powerful and user-friendly, it is also more re-usable.

**Comment by rstoenescu** [comment]
Hi,

The new QTable (introduced in v0.14 if I'm not mistaken) allows for total customization, so this can be done in app-space now.

**Comment by kevrousso** [comment]
@rstoenescu Can you elaborate on this? I need to create column filters that will work with the search filter as well.
