### ISSUE TITLE
[v1] - 1.0-beta.10 no access inside <style..> on  Stylus variables like $breakpoint-xl-min

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#3570]
Operating System - Linux(3.16.0-7-amd64) - linux/x64
NodeJs - 11.10.0

Global packages
  NPM - 6.9.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.3
 quasar - 1.0.0-beta.10 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybr                     id Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.11 -- Quasar Framework App CLI
  @quasar/extras - 1.1.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.8 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.3 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD 

I have this little stylus media checker inside my .vue file:

```
> 
> <style lang="stylus">
>   @import '~quasar-variables'
>   @media (min-width $breakpoint-xl-min)
> 
>     .layout-toolbar
>       max-width 400px
>       margin 0 auto
> 
> </style>
```

on v.0.17 this works fine (with the v.0.17 @import  uri) but on 1.0 the $breakpoint-xl-min is not filled with data ...

If i hardcode instead of $breakpoint-xl-min -> 600px .. it works ..

No Errors in console.
See discord. v1-discussion part Thursday, 14.03 - 11:00 O´Clock ..

**Comment by rstoenescu** [comment]
Hi,

I would be surprised this doesn't works. It's being used on the docs (which are Quasar SSR) too. I just tested with a brand new project folder and works correctly.

Please DM me on Discord. Thanks.
