### ISSUE TITLE
[V1] QToggle + fontawesome = bad icon position

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#3571]
### Software version
Quasar v1.beta.10

### JsFiddle
https://codepen.io/daedalusdev/pen/LaQere

### What did you get as the error?
Bad icon position
### What were you expecting?
A good icon position

**Comment by rstoenescu** [comment]
Hi,

Thank you for offering a PR. However, went with a slightly different approach, and fixed a glitch for IE11 too. I hope you don't mind.

Fix will be available in beta.11.
