### ISSUE TITLE
InjectManifest stuck at 95% with workboxOptions

### ISSUE THREAD

**Issue by wannymiarelli** [quasarframework/quasar#3573]
### Software version

**Global packages**
  NPM - 6.4.1
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.3
  cordova - You have been opted out of telemetry. To change this, run: cordova telemetry on.
8.1.2 (cordova-lib@8.1.1)

**Important local packages**
  quasar - 1.0.0-beta.10 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.11 -- Quasar Framework App CLI
  @quasar/extras - 1.1.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.8 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.3 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

**Quasar App Extensions**
  *None installed*

### What did you get as the error?

The dev command is stuck at InjectManifest 95% with pwa mode

### What were you expecting?

The dev command to launch the application in the browser

### What steps did you take, to get the error?

- Created a clean  quasar project with quasar create
- added the pwa mode running quasar dev -m pwa
- set workboxPluginMode to InjectManifest
- added the workboxOptions workboxOptions: { skipWaiting: true, clientsClaim: true }
- run the quasar dev -m pwa to start the dev server

**Comment by rstoenescu** [comment]
This is a problem with workbox itself.

Tried to do a build with your config and:

```
 app:build Building... +2ms

  PWA ███████████████████████   chunk asset optimization [92%] TerserPlugin

(node:97747) UnhandledPromiseRejectionWarning:   ValidationError: "skipWaiting" is not a supported parameter.. "clientsClaim" is not a supported parameter.
  
  - errors.js:190 Object.exports.process
    [app]/[joi]/lib/errors.js:190:19
  
  - index.js:668 internals.Object._validateWithOptions
    [app]/[joi]/lib/types/any/index.js:668:31
  
  - index.js:702 internals.Object.validate
    [app]/[joi]/lib/types/any/index.js:702:21
  
  - validate.js:20 module.exports
    [app]/[workbox-build]/build/entry-points/options/validate.js:20:33
  
  - get-manifest.js:36 _callee$
    [app]/[workbox-build]/build/entry-points/get-manifest.js:36:23
  
  - new Promise
  
  - _export.js:36 new F
    [app]/[core-js]/library/modules/_export.js:36:28
  
  - get-manifest.js:57 getManifest
    [app]/[workbox-build]/build/entry-points/get-manifest.js:57:17
  
  - inject-manifest.js:160 InjectManifest._callee$
    [app]/[workbox-webpack-plugin]/build/inject-manifest.js:160:24
  
  ```

Notice: ```ValidationError: "skipWaiting" is not a supported parameter.. "clientsClaim" is not a supported parameter.```

**Comment by nothingismagick** [comment]
Research from Discord by danieldoliev:

> After searching a lot, I think I might have solved it, I added this, so far so good in iOS is getting the latest version every time (close the app, after a while, even in reboot).

> I set the workboxPluginMode: 'InjectManifest' and comment out the workboxOptions:
```
    pwa: {
      workboxPluginMode: 'InjectManifest',
      // workboxOptions: {
      // },
      // ... rest of your configuration
```
> Then in my custom-service-worker.js I added this:

```
workbox.core.setCacheNameDetails({prefix: "your-app-prefix-name"}); // check the prefix of your app cache and set this accordingly

workbox.core.skipWaiting();

workbox.core.clientsClaim();

self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});
```
