### ISSUE TITLE
[v1] QInput inside QTree loses focus on mouse-up event

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#3578]
Demo is here: https://codepen.io/dsl101/pen/jJZXeE

The QInput will not keep focus when clicked on. Using Tab key to move focus works, as does holding down the mouse button and then typing.

**Comment by pdanpdan** [comment]
Hi. Just add a `@click.stop` on `<q-input ...`

**Comment by dsl101** [comment]
Is that a permanent solution (like needs documenting), or will there be a fix at some point?

**Comment by pdanpdan** [comment]
The header in QTree allows tree item selection on click.
It is up to you in userland to know if the custom header should allow selection or not.

If you want to allow selection on click (default) then all controls in the header will lose focus because the focus goes to tree item.

If you want to allow controls in header the you need to prevent click event propagation.

**Comment by dsl101** [comment]
I made a new pen, as QSelect doesn't work immediately with that fix:

https://codepen.io/dsl101/pen/eXMXWL?editors=1010

How to do that for a QSelect?

**Comment by pdanpdan** [comment]
Just wrap the controls in a `div` container with `@click.stop`
https://codepen.io/anon/pen/VRXRdv?editors=1010

**Comment by dsl101** [comment]
Thanks—don't know if this is connected, but I can't now enter 'tags' that have a space in them. As soon as I hit the spacebar, the focus is lost again. Is that a different problem?

**Comment by pdanpdan** [comment]
A, but of course. Click, SPACE and ENTER selects the item.

```javascript
<div @click.stop @keyup.13.32.stop>
```

**Comment by dsl101** [comment]
Thanks. That's working in my app, although in both your codepen and mine, it won't add new values for some reason. But never mind :).

**Comment by dsl101** [comment]
Hi @pdanpdan This fix has stopped working in a more recent version of Quasar I think. Your code pen no longer allowed spaces in the input component, and my app has also stopped since upgrading. Any ideas on what's changed? It looks like it could be something else, as even taking out the `@keyup.13.32.stop` in the input tag, I still can't enter spaces...

**Comment by pdanpdan** [comment]
The listener was moved on `@keypress`.
So now use `@keypress.13.32.stop` - example https://codepen.io/pdanpdan/pen/BaBbrxQ?editors=1010

**Comment by dsl101** [comment]
Ah. Thanks.

**Comment by dsl101** [comment]
Sorry, meant to say, is there any reference to this somewhere in the docs? Because when checking for meta keys, this doesn't work so well:
```
<!-- Works -->
<q-editor
  v-model="editedContent"
  @keyup.enter="handleEnter"
/>
<!-- Works -->
<q-editor
  v-model="editedContent"
  @keypreses.enter="handleEnter"
/>

handleEnter (e) {
  if (e.ctrlKey) {
    this.handleEdit()
  }
}
```
That doesn't work with `@keypress`, so I'm curious why the change. It seems that CTRL+Enter doesn't fire the `@keypress` event, whereas it does fire the `@keyup` event. Perhaps it's just a missing check, as SHIFT+Enter _does_ fire `@keypress`?

**Comment by dsl101** [comment]
Sorry if you got my half finished comment. I've been rewriting and doing a code pen. It seems some key modifiers don't work with `@keypress`, so now I have to use a combination of `@keyup` and `@keypress` depending on the circumstances. For example, I want to trap 'CTRL+Enter' in a q-editor, but that doesn't work with `@keypress`, whereas the issue above only works _with_ `@keypress`. Quite confusing. Is there any documentation to help? See https://codepen.io/dsl101/pen/MWgxGVd?editors=1011 and try using modifiers (CTRL, ALT) with Enter in the `@keypress` editor. Only SHIFT seems to work...

**Comment by pdanpdan** [comment]
The original issue was related to preventing a quasar component to react on some keypresses, and that meant to prevent the event to reach the listener (in that case we are listening for keypress).

What you are talking about in QEditor is how key events are processed by browser + vue + quasar.

First check what events are emitted by using a focusable div, and attach listeners to it for all key events, with logging. I cannot tell right now if QEditor catches and processes Ctrl+enter.
