### ISSUE TITLE
[request] preload spinner for img tags

### ISSUE THREAD

**Issue by beebase** [quasarframework/quasar#358]
http://forum.quasar-framework.org/topic/198/add-preload-spinner

**Comment by spectrolite** [comment]
This would be real cool, can we somehow do it with 0.14 beta already ?

**Comment by danikane** [comment]
What about the new Inner Loading?
http://beta.quasar-framework.org/quasar-play/android/index.html#/showcase/progress/inner-loading

**Comment by rstoenescu** [comment]
Yes, I think we can add it to v0.14.

**Comment by slowaways** [comment]
What's the status of this feature?

**Comment by rstoenescu** [comment]
It's gonna get in soon. Was busy with other things but I think I can schedule this for a v0.17.x release.

**Comment by rstoenescu** [comment]
Done for v1.0 -- QImg
