### ISSUE TITLE
Disabled button the type is submit can sitll click in a form

### ISSUE THREAD

**Issue by Aiyibooo** [quasarframework/quasar#3580]
### Software version

Quasar: v1.0.0-beta.9
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers: chrome  73.0.3683.75
iOS:
Android:
Any other software related to your bug:

### CodePen
https://codepen.io/Aiyibooo/pen/JzLPRv

### What did you get as the error?
Disabled button the type is submit can sitll click in a form.

### What were you expecting?
Do not trigger the click event.
### What steps did you take, to get the error?
Click the disabled button in codepen.

**Comment by rstoenescu** [comment]
Fix will be available in beta.11.
