### ISSUE TITLE
[v1] [doc] q-btn icon-right is wrong

### ISSUE THREAD

**Issue by manelclos** [quasarframework/quasar#3581]
https://v1.quasar-framework.org/vue-components/button#QBtn-API

Same description/example as for icon:

Description
Icon name following Quasar convention; make sure you have the icon library installed

Examples
map
ion-add

**Comment by rstoenescu** [comment]
Hi,

The definition is that of an icon, so yes, it's the same. But the name of the prop differs, which is key to understanding it. Won't change all icon props definitions because of this. Props like "icon-top" or "icon-message" etc etc have the explanation in their names already...
