### ISSUE TITLE
[v1 request] QEditor add option to make multiline toolbar 

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3582]
Now toolbar is one line even for PC.
It looks not native for pc when there is more buttons and horisontal scrollbar.

![image](https://user-images.githubusercontent.com/10674646/54416225-d5e2c180-470f-11e9-945e-afaecbbabde8.png)

Realy more space around, and toolbar buttons will look more native and user friendly if placed in 2 or more lines.

I think need some functionality / options to select row count or rows wraping to QEditor toolbar.

**Comment by rstoenescu** [comment]
Will be available in beta.19

**Comment by Dmitrij-Polyanin** [comment]
Now is 19?
I tried to find how to make noral llok for pc, but nothing found about it

**Comment by rstoenescu** [comment]
Current is beta.18
Are you confusing with @quasar/app version?

**Comment by Dmitrij-Polyanin** [comment]
Thanks! Working. But there is some strange behavior on PC.
Size of toolbar jumping bigeer or smaller.
