### ISSUE TITLE
[V1] QSlider handle does not complete its animation when released

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#3586]
QSlider handle does not complete its animation when released. Or is this intentional?

Codepen:
https://codepen.io/smakinson/pen/ywKKVK

### Software version

Quasar: beta 9, beta 10
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers: Chrome, Safari, Firefox
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
The handle stays semi transparent and large when letting go until another location is clicked.
### What were you expecting?
The handle to return to normal when released.
### What steps did you take, to get the error?
Drag the handle normally to change its value.

**Comment by rstoenescu** [comment]
This is not a bug. This is part of the Accessibility work. It shows that the QSlider has focus. You can use TAB key to focus on QSlider and when it's focused, left/right arrow keys.
