### ISSUE TITLE
[v1][RTL] QTable wrong default text align

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#3590]
When using an RTL language, like `fa-ir`, if the `align` property of `columns` is not set, it is set to `right` which is correct. However, all css properties are flipped by PostCSS so a `td` or `th` ends up like this: 
 ```html
<td class="text-right">نام سازمان</td>
```
so far so good, but:
```css
[dir=rtl] .text-right {
    text-align: left;
}
```
So the default align should not be changed to `right` when in `rtl` mode because alignment will be taken care of by flipped css.
the problem can be seen here:  https://codepen.io/behnoodk/pen/Gexwop

**Comment by rstoenescu** [comment]
Hi,

It is set to "right" default because most tables are considered to contain values. So it's a helper and according to Material Design guideline (last time I checked). For columns containing text, you should set alignment to "left" --> which when converted to RTL will do what you want.
