### ISSUE TITLE
Resize Observer no longer resizes window contents on desktop browsers when enlarging the window vertically

### ISSUE THREAD

**Issue by mwarren2** [quasarframework/quasar#3594]
v1.0.0-beta10 on mac

We're talking about a map that takes up basically all of the window, and adapts to the size of the window. **Will post an example soonest.**

If you enlarge any browser window downwards **vertically** the resize no longer kicks in and I just get white space where the enlarged window should be.
Any slight movement horizontally of the window works, it's the vertical movement downwards that shows the problem.

I've seen this on both Chrome and Firefox.

`<q-resize-observer @resize="resizeMap" />`

I have verified that the `@resize` event is actually not calling my `resizeMap` function at all for vertical window movements downwards.

**Comment by rstoenescu** [comment]
Works perfectly. Please post the example.

**Comment by mwarren2** [comment]
@rstoenescu I can't get the umd version working in a browser to produce a simple example. Crazy but true. This is a limitation of mine, not yours.

I'm not worried about desktop for my purposes so I'll just close this. Thanks for now.

**Comment by mwarren2** [comment]
P.S.
I did a lot of gardening at the weekend and cleared the brain of overwork.

QResizeObserver is of course fine.
I needed to watch the parent component, not the one I was watching.
