### ISSUE TITLE
[V1] q-space not working as self-closing-tag

### ISSUE THREAD

**Issue by bitmandk** [quasarframework/quasar#3595]
In the documentation for v1 BETA - a self-closing q-space (<q-space />) is shown. But when used -  it seems to eliminate all elements to the right of the self-closing q-space.

If q-space is ended with a normal end: <q-space></q-space> - it works.

Shown in this fiddle:
https://jsfiddle.net/bitman_dk/c1fevtyo/15/

**Comment by rstoenescu** [comment]
https://v1.quasar-framework.org/start/umd

Do not use self-closing tags when in UMD. Please read above.

**Comment by rstoenescu** [comment]
Also this -> https://v1.quasar-framework.org/start/how-to-use-vue#Self-Closing-Tags

**Comment by bitmandk** [comment]
Ahh - missed that when I read the documentation ;-)
Maybe it's a good ide NOT to use self-closing-tags in the docs - as some people (me included) copy the syntax from the docs and use the copied examples as base for work.

**Comment by rstoenescu** [comment]
Hit the "Codepen" button and you'll get a working UMD code that you can copy-paste.
Most devs go with Quasar CLI which can have vue eslinting packages (which depending on the level that you select, may enforce self-closing tags). For these devs, it would be a shame to make them "learn" closing each tag as it would be a waste of time on their part.

**Comment by lucasfernog** [comment]
Maybe we could create a "Copy for UMD" option since a lot of devs are misusing that
