### ISSUE TITLE
[v1] vueRouterMode 'history' does not honor build.publicPath on ctx.dev

### ISSUE THREAD

**Issue by bompus** [quasarframework/quasar#3596]
### Software version
Quasar: 1.0.0-beta.10
@quasar/app (v1+ only): 1.0.0-beta.11
OS: Linux(4.15.0-46-generic) - linux/x64
Node: 11.12.0
NPM: 6.7.0

### What did you get as the error?
Accessing /dev/ outputs ```<base href='/'></head>```

### What were you expecting?
It should output ```<base href='/dev/'></head>```

### What steps did you take, to get the error?
in quasar.conf.js:
```
build: {
      vueRouterMode: 'history',
      publicPath: ctx.dev ? '/dev/' : '/prod/'
}
```

I believe the cause is https://github.com/quasarframework/quasar/blob/8429368f1740e65e98f0fbdb9421132f1c213f9e/app/lib/quasar-config.js#L428-L434 which appears to override the cfg.build.appBase to '/' if you are not on ctx.prod

I'm using nginx to proxy /dev/ to the 127.0.0.1:8080 devServer, with publicPath set. Everything works fine in hash mode, but history mode is broken solely by the incorrect base href '/' being output. I was able to do this on Vuetify, but it appears to be either a bug of maybe expected behavior in Quasar? Let me know.

**Comment by rstoenescu** [comment]
Hi,

What are you building? For cordova and electron build modes it doesn't makes any sense to use a publicPath. So are you building SSR?

**Comment by bompus** [comment]
SPA in a subfolder. For example, subfolder will be /dev/ if ctx.dev or /prod/ if ctx.prod

Thanks for the super quick reply.

**Comment by rstoenescu** [comment]
You've updated your description. What would be the point in a publicPath for dev mode? You're on a dev server  developing your app. There's lots of complications if I enable publicPath for dev too that I do not have time to go into at the moment, but I can't really find any use for that.

What you could do, since you are using another server (nginx) to redirect to the dev server is that you could configure nginx to strip down the "/dev" part from the URL when requesting Quasar dev server.

**Comment by rstoenescu** [comment]
Also keep into account that Quasar is a powerhouse and supports spa/pwa/ssr/ssr+pwa/electron/cordova using the same codebase, as opposed to all other frameworks. Using publicPath for dev has serious implications and everything becomes overcomplicated for basically almost nothing.

**Comment by bompus** [comment]
I'm building a CMS. The homepage (public pages) will be at / , but the CMS back-end itself would be at /cms/. I suppose I could try to use a subdomain for the back-end, but I was hoping to get it to work the same way I had it working on Vuetify.

**Comment by rstoenescu** [comment]
At the end of the day, you can use whatever publicPath you need for the production build. And also set up a proxy for the /cms while developing (https://v1.quasar-framework.org/quasar-cli/cli-documentation/api-proxying#Introduction).

Please join our Discord server if you bump into trouble.

-Razvan
