### ISSUE TITLE
[v1] slider, label => no label-value option?

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#3597]
Reference: https://forum.quasar-framework.org/topic/3283/v1-slider-label-no-label-value-option

**Comment by rstoenescu** [comment]
And added label-value prop back for QSlider and left-label-value and right-label-value for QRange.
Will be available in beta.11

**Comment by KPKoch** [comment]
Thanks for this - and that it works with 0.17 code out of the box. I still do have to report back: currently it is show as bubble / circle which results in problems with slightly longer words. Would it be possible to make it chosable to also get the legend back in rectangle form, which would scale greatly with any text.

**Comment by rstoenescu** [comment]
@KPKoch will be available in beta.15.
