### ISSUE TITLE
[ios] Image gallery slider is below header & footer in fullscreen mode

### ISSUE THREAD

**Issue by Sopamo** [quasarframework/quasar#360]
On iOS (with the cordova wrapper) the image gallery is still below the header & footer when the fullscreen mode is enabled. This cuts of parts of the image and also prevents the user from exiting the fullscreen mode because the fullscreen icon is overlapped by the footer.

Reproduction:
 - Create a new quasar project
 - Add the cordova wrapper
 - Place the following code in the Index.vue component:

```html
  <q-layout>
    <div slot="header" class="toolbar">
      <q-toolbar-title :padding="0">
        Quasar Framework v{{quasarVersion}}
      </q-toolbar-title>
    </div>
    <div class="layout-view">
      <q-gallery-slider class="main-gallery" :src="['https://placekitten.com/1000/2000']"></q-gallery-slider>
    </div>

    <q-tabs slot="navigation" ref="mainTabs">
      <q-tab icon="home" route="/" exact replace>Home</q-tab>
      <q-tab icon="restore" route="/a" replace>A</q-tab>
      <q-tab icon="favorite" route="/b" replace>B</q-tab>
      <q-tab icon="bookmark" route="/c" replace>C</q-tab>
    </q-tabs>
  </q-layout>
```

 - Run the app on ios and click on the fullscreen icon

Tested on iOS 9 & 10.

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting.

**Comment by rstoenescu** [comment]
Fixed in edge and next Quasar version (which most likely is v0.13.1).
@Sopamo thank you for supplying with example code, it helps a lot.
