### ISSUE TITLE
[v1] Feature request: add keep-alive prop to QTabPanels

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#3601]
In v0.17, QTabPane used to have a keep-alive property:
https://quasar-framework.org/components/tabs.html#QTabPane-Child-Component

I don't see anything equivalent in QTabPanels in v1:
https://v1.quasar-framework.org/vue-components/tab-panels

Are there plans to add this back in v1?

**Comment by pdanpdan** [comment]
Track that one instead: https://github.com/quasarframework/quasar/issues/3345

**Comment by rstoenescu** [comment]
Added a new prop (Boolean) for QCarousel/QTabPanels/QStepper: `keep-alive`.
Will be available in beta.22.
