### ISSUE TITLE
Implement table features of element.eleme.io/

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/quasar#3602]
It would be great to see quasar with all these table features (especially the grouped table heads, I need this)
http://element.eleme.io/#/en-US/component/table

**Comment by nothingismagick** [comment]
Hey @CheyenneForbes - have you seen the latest table additions in v1? They should be landing in quasar v1.0.0-beta.24

https://github.com/quasarframework/quasar/commit/73bbc7d466e8cf05ae33bda99885b68f17db6387
https://github.com/quasarframework/quasar/commit/359909b799b00081646149d61b5927220adf6bd2
https://github.com/quasarframework/quasar/commit/fdf48b150eabc734fc4a6fff75d938cb30190f91

**Comment by CheyenneForbes** [comment]
Hey @nothingismagick have a look at this feature, tried to find it in quasar but couldnt

https://element.eleme.io/#/en-US/component/table#grouping-table-head

**Comment by nothingismagick** [comment]
Wow - that is a little more complex than i expected (didn't see it before to be honest). My thought here is that you are going to have to build it with the header slot and somehow do mapping from your data source.

**Comment by nothingismagick** [comment]
My advice would be to stop by our discord server and ask for some help in the #v1-beta channel.
