### ISSUE TITLE
[v1] QSelect is missing a blur event

### ISSUE THREAD

**Issue by satyavh** [quasarframework/quasar#3604]
QSelect doesn't have and therefor doesn't trigger a blur event. This makes it difficult to hook up with for example vuelidate, or custom form validation.

### Software version
1.0.0-beta.8

Quasar:
Operating System - Darwin(16.7.0) - darwin/x64
NodeJs - 9.8.0

Global packages
  NPM - 5.6.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.8 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.10 -- Quasar Framework App CLI
  @quasar/extras - 1.1.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.7 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.5 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 3.6.3 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0-beta.14 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing-e2e-cypress - 1.0.0-beta.5 -- A Quasar App Extension for Cypress e2e
  @quasar/quasar-app-extension-testing - 1.0.0-beta.7 -- A Quasar App Extension for managing Test Harnesses

### What did you get as the error?
There's no error

### What were you expecting?
Expecting a form component such as a select to support a blur event.

### What steps did you take, to get the error?
Use a QSelect element with `@blur="blurTest"` prop, nothing is triggered when blurring the select field.

Note that a QSelect with an `use-input` prop should probably have a blur event on the child input component.

**Comment by pdanpdan** [comment]
Use `focusin` an `focusout` events like explained here: https://github.com/quasarframework/quasar/issues/3317

**Comment by satyavh** [comment]
Thanks, that works! 👍
