### ISSUE TITLE
[v1 request] dotenv environment variables like vue clie 3

### ISSUE THREAD

**Issue by manelclos** [quasarframework/quasar#3605]
Having configuration values in dotenv files is very convenient:
https://cli.vuejs.org/guide/mode-and-env.html

I haven't found this documented in quasar v1 docs, it would be great to have it listed when comparing quasar cli to vue cli 3 here: https://v1.quasar-framework.org/start/pick-quasar-flavour

**Comment by smolinari** [comment]
Check out this app extension.

https://github.com/quasarframework/app-extension-dotenv

Scott

**Comment by rstoenescu** [comment]
Like Scott mentioned, we have an app extension for that. Check it out if you are interested.
