### ISSUE TITLE
[v1][Feature Request] QBtn left & right props?

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#3609]
As I am laying some thing out and using both QIcon and QBtn with only an icon ( no label )I thought I'd see if you guys think that QBtn should also have the left & right properties  like QIcon since QBtn with only an icon and no label is similar to using an icon by itself. Just thinking about it as a consistency thing.

**Comment by rstoenescu** [comment]
Hi,

It only makes sense for QIcon because it adds a specific padding according to Material Design guidelines. For all other components, there are the `q-p*` and `q-m*` CSS helper classes.
