### ISSUE TITLE
[v1] Unable to scroll QSelect if wrapped in QPullToRefresh

### ISSUE THREAD

**Issue by NicksonYap** [quasarframework/quasar#3610]
### Software version

Quasar:
@quasar/app (v1+ only): 1.0.0-beta.9
OS: Windows 10 Pro
Node: 10.14.2
NPM: 6.4.1
Browsers: Chrome
iOS:
Android: Samsung One UI
Any other software related to your bug:

### Codepen

https://codepen.io/NicksonYap/pen/xBzMMX

### What did you get as the error?

On Mobile, (tested on chrome browser with code pen, and also my cordova app)
Unable to scroll the expanded QSelect when wrapped in QPullToRefresh

The scroll is captured by QPullToRefresh so nothing happens in QSelect (just truncated)

### What were you expecting?

To be able to scroll QSelect when expanded, and ignore QPullToSelect

### What steps did you take, to get the error?

Click / Tap the QSelect, and try to scroll the options.
The page scroll instead of the options, overflowed options remain trimmed/hidden

**Comment by rstoenescu** [comment]
Fix will be available in beta.12

**Comment by NicksonYap** [comment]
Great!
