### ISSUE TITLE
[v1] Failed to resolve directive: close-popup

### ISSUE THREAD

**Issue by manelclos** [quasarframework/quasar#3611]
### Software version

Quasar: v1.0.0-beta.11
@quasar/app (v1+ only): v1.0.0-beta.12

Getting INFO about deprecation:

`[Quasar] info: please rename v-close-menu (deprecated) with v-close-popup`

Changed v-close-menu to v-close-popup. Now getting WARNings:

`[Vue warn]: Failed to resolve directive: close-popup`

**Comment by rstoenescu** [comment]
https://v1.quasar-framework.org/vue-directives/close-popup

**Comment by rstoenescu** [comment]
See the Installation. Need to add ClosePopup to your quasar.conf.js
