### ISSUE TITLE
[v1]QDate - years gets fighting for a place

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#3613]
Beta 11.
All browsers.
Years gets fighting for a place.
https://pasteboard.co/I62sUjI.jpg

**Comment by pdanpdan** [comment]
Please provide a codepen with your code. Also what os, what browser.
Here everything looks good: https://v1.quasar-framework.org/vue-components/date

**Comment by pdanpdan** [comment]
@emprove Can you provide more details, please? Else we'll just close this as cannot reproduce.

**Comment by emprove** [comment]
I use $flex-cols = 24 variable. With default value = 12 its ok.

**Comment by pdanpdan** [comment]
Very funny :)
Ok, good point - I'll take a look.

**Comment by rstoenescu** [comment]
Fix will be available in beta.12
