### ISSUE TITLE
[v1 bug] Placeholder shows up only on focus when using input with stack-label, should be always visible

### ISSUE THREAD

**Issue by robsoncombr** [quasarframework/quasar#3614]
### Software version

Operating System - Linux(4.15.0-1032-aws) - linux/x64
NodeJs - 8.15.0

Global packages
  NPM - 6.8.0
  yarn - 0.32
  @quasar/cli - 1.0.0-beta.3
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.11 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.12 -- Quasar Framework App CLI
  @quasar/extras - 1.1.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.9 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - 3.1.6 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### What did you get as the error?

When using q-input with placeholder and stack-label it causes the placeholder to show up only when the input gets on blur it gets hidden, it does not happen when stack-label is removed.

### What were you expecting?

Placeholder has to be always visible. Placeholder has to behave the same when using stack-label or not.

### What steps did you take, to get the error?

```
<q-input label="Label" placeholder="Placeholder" hint="show only on focus" stack-label />
<q-input label="Label" placeholder="Placeholder" hint="always visible" />
```

**Comment by rstoenescu** [comment]
Thanks for reporting this.
Fix will be available in beta.12
