### ISSUE TITLE
Additional features for q-table

### ISSUE THREAD

**Issue by b-y-t-e** [quasarframework/quasar#3615]
I would like to thank you very much for your efforts, Quasar is a great framework and we're preparing to use it in our next projects. I would like to request for additional features for q-table component:
 + 'rowClick' event with parameter containing row data / selection 
`<q-table @rowClick="onRowClick">`
 + something like 'selectOnRowClick' attribute, that would mark the row as selected if you click on it
`<q-table selectOnRowClick >`
 + 'doubleRowClick' event (same as 'rowClick' but executed if you double click on row)
 + ability to style selected rows differently than just showing checkbox as a first column (selected rows may have different background), for example:
`<q-table selectedRowBackground='#ccc' >`
 + ability to make focus on certain row + related events and methods (like 'onFocusedRowChanged' /  'getFocusedRow' / 'setFocuedRow') 
`<q-table focusedRow="focusedRow" @onFocusedRowChanged="focusedRowChanged" >`
 + ability to move thought grid using old fashioned keyboard keys (arrows + pageup + pagedown) 
 + alibility to handle keypress for example: 'space' key on focused row to select him + related methods (like 'selectRow(rowItem)' / 'deselectRow(rowItem)' )
`<q-table onkeypress="onKeyPress" >`
Best regards :)

**Comment by rstoenescu** [comment]
Hi,

You haven't specified the version of Quasar that you are using, so assuming latest v1 beta (https://v1.quasar-framework.org)

* 'rowClick' event with parameter containing row data / selection --> use `body` slot
* something like 'selectOnRowClick' attribute, that would mark the row as selected if you click on it --> achievable through `body` slot
* ability to style selected rows differently than just showing checkbox as a first column (selected rows may have different background) --> Use dev-tools and override the specific CSS
* ability to handle keypress for example: 'space' key on focused row to select him + related methods --> achievable through `body` slot

Will take into consideration the rest of the items. I recommend reading the docs (link at beggining of my comment) on QTable and checking out the examples. Thanks.

**Comment by b-y-t-e** [comment]
I'm using latest v1 beta. I've just realized that I've missed some knowledge related to scopedslots of q-table :)
Thank you for your response. 
Best regards!
