### ISSUE TITLE
[v1] QSlideItem can not slide back

### ISSUE THREAD

**Issue by snowyu** [quasarframework/quasar#3620]
### Software version

Quasar: 1.0.0-beta.11
@quasar/app (v1+ only): 1.0.0-beta.10
OS: Linux(4.18.0-16-generic) - linux/x64
Node: 10.15.1

### JsFiddle

https://codepen.io/snowyu/pen/PLBBdw

### What did you get as the error?

Slide the item(QSlideItem) , and try to slide it back.
It should calculate the width of the slot's content, and slide out the contents, not fill all space.

### What were you expecting?

![](https://user-images.githubusercontent.com/3253920/40763237-3237177e-64df-11e8-86b8-30de5572d16d.gif)

**Comment by rstoenescu** [comment]
Hi,

You are misunderstanding QSlideItem. User should keep touching the screen (or holding the mouse) on QSlideItem. When he/she lifts the finger or releases the mouse, QSlideItem checks if the left or right parts are fully visible and in such case it considers that the user has triggered the respective action. If the left/right parts are not fully visible, it aborts and QSlideItem is reset into the initial state (covering the left/right parts).
