### ISSUE TITLE
QRouteTab no longer matches child routes

### ISSUE THREAD

**Issue by GrandUltimate** [quasarframework/quasar#3623]
### Software version

Quasar: 1.0.0-beta.12
@quasar/app (v1+ only):
OS: ubuntu
Node: 8.10.0
NPM: 6.8.0
Browsers: chrome, firefox

### What did you get as the error?
QRouteTab no longer matches child routes

### What were you expecting?
QRouteTab should match child routes
When on route 'childRoute1' QTabs v-model should equal 'tab1'

### What steps did you take, to get the error?
```
export default [
  {
        name: 'parentRoute1',
        path: '/path',
        component: () => import('pages/aPage'),
        children: [
          {
            name: 'childRoute1', // QRouteTab 'tab1' should match this route
            path: 'path1',
            components:  () => import('components/component1')
          },
          {
            name: 'childRoute2', // QRouteTab 'tab1' should match this route
            path: 'path2',
            components: () => import('components/component2')
          }
    }
]
```
```
<q-tabs v-model="toolbarTabs">
          <q-route-tab
            name="tab1"
            label="Tab 1"
            :to="{name: 'parentRoute1'}"
            :key="'-tab'"
          />
          <q-route-tab
            name="tab2"
            label="Tab 2"
            :to="{name: 'parentRoute2'}"
          />
        </q-tabs>
```

**Comment by pdanpdan** [comment]
Can you check with the latest version? The matching algorithm was changed.

**Comment by GrandUltimate** [comment]
Sorry that version listed '1.0.0-beta.3' is Quasar cli version. I'm using quasar '1.0.0-beta.11'

**Comment by rstoenescu** [comment]
There is no quasar 1.0.0-beta.12. Latest Quasar is v1.0.0-beta.11
You're confusing with @quasar/cli (global install) and @quasar/app (local project dependency).
The UI for which you are logging a bug is the "quasar" package in your project folder.

Run "quasar info" in the console and paste it here. Make sure "quasar" package is at 1.0.0-beta.11. Otherwise upgrade to it. "quasar upgrade"  in your project folder.

**Comment by GrandUltimate** [comment]
Ah, sorry for the confusion... quasar info output:
```
Global packages
  @quasar/cli - 1.0.0-beta.3

Important local packages
  quasar - 1.0.0-beta.11 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.12 -- Quasar Framework App CLI
  @quasar/extras - 1.1.0 -- Quasar Framework fonts, icons and animations
```

**Comment by pdanpdan** [comment]
I just checked and it works fine. I hope you are aware that the model on `QTabs` is read-only when you use `QRouteTabs`.
So if you have `<q-tabs v-model="model"...>` you'll only get an updated model when you navigate to another URL, but you won't be able to change route by changing the model (you'll only change the selected tab).

What are you trying to obtain, what is the problem you have, and why are you using the tab model instead of `$route`?

**Comment by GrandUltimate** [comment]
I'm using the tabs to switch between different sections of a dashboard. I was using the tabs `v-model` to toggle different menu items for each section.
I realized the issue has to do with a redirect form the parent route to one of it's children.
The child route that the parent route redirects to is the only one that `QRouteTab` shows as active when on that child's route. If I remove the redirect on parent then all child tabs register as active when on that route.
This behavior started with the last update and doesn't seem correct.

```
export default [
  {
    path: '/management',
    name: 'managementRoot',
    redirect: { name: 'manageStores' },
    component: () => import('layouts/management'),
    children: [
      {
        name: 'manageStores',
        path: 'store',
        redirect: { name: 'manageStoresCreate' },
        component: () => import('pages/Management/Market/MarketManageController'),
        children: [
          {
            name: 'manageStoresAll',
            path: 'all',
            components: {
              default: () => import('components/Market/StoresManage')
            }
          },
          {
            name: 'manageStoresCreate', // only route that QRouteTab correctly registers as selected
            path: 'create',
            components: {
              default: () => import('components/Market/StoreForm')
            }
          },
          {
            name: 'manageMerchantAccounts',
            path: 'merchant-accounts',
            components: {
              default: () => import('pages/Management/Market/MerchantAccounts')
            }
          }
        ]
      }
    ]
  }
]
```

**Comment by pdanpdan** [comment]
I need also the QRouteTabs used.

**Comment by GrandUltimate** [comment]
```
<q-tabs v-model="toolbarTabs" class="tabs" color="transparent" text-color="white" align="justify">
          <q-route-tab
            name="storesTab"
            label="Store"
            :to="{name: 'manageStores'}"
          />
          <q-route-tab
            name="analyticsTab"
            label="Analytics"
            :to="{name: 'manageAnalytics'}"
          />
          <q-route-tab
            name="mediaTab"
            label="Media"
            :to="{name: 'manageMedia'}"
          />
        </q-tabs>```

**Comment by pdanpdan** [comment]
I have reproduced your setup here.
https://codepen.io/anon/pen/GeYxwz

It looks like it's working as expected.
Please adjust the codepen to show your problem.

**Comment by GrandUltimate** [comment]
@pdanpdan thanks for taking the time to reproduce the setup.
I've modified your codepen https://codepen.io/anon/pen/NJOMmg
If you click the new link `Go to child link` you can see the `store` tab is no longer active and `toolbarTabs` is blank

**Comment by pdanpdan** [comment]
@GrandUltimate 
Please make a short test for me - add "quasar": "https://github.com/pdanpdan/quasar#quasar-v1.0.0-beta.11.1-gitpkg", in your application's package.json under "dependencies".

Do a yarn && quasar dev and tell me if you can still reproduce the problems.

**Comment by GrandUltimate** [comment]
My `package.json` has these Quasar dependencies:
```
"dependencies": {
    "@quasar/extras": "^1.0.0",    
    "quasar": "^1.0.0-beta.11",    
  }
```

**Comment by GrandUltimate** [comment]
@pdanpdan That did the trick! We have since decided not to use QRouteTabs for this particular use case (nothing to do with this issue) but I'm glad to help report this bug. Thanks for all your alls work on Quasar!

**Comment by nothingismagick** [comment]
@GrandUltimate - Thankyou for reporting. Its people like you that help open source evolve. Keep it up and see you around!

**Comment by rstoenescu** [comment]
Fix will be available in beta.12

**Comment by mncoldsmoke** [comment]
I can't get the codepens to work. But I am having the same problem. I am using the newest version and when I navigate to a child route of a QRouteTab, it jumps back to my home tab, and doesn't recognize that it is a child of the tab it is on.

I am probably going to just stop using QRouteTab which seems to have years of the same flaw, and spin up my own routing with the generic tab. Very disappointing.
