### ISSUE TITLE
q-input textarea word didn't wrap when col-x smaller than 3

### ISSUE THREAD

**Issue by haaah** [quasarframework/quasar#3626]
### Software version

Operating System                Darwin(18.2.0) - darwin/x64
NodeJs                          11.10.0

Global packages          
  NPM                           6.8.0
  yarn                          1.13.0
  quasar-cli                    0.17.23
  vue-cli                       3.4.1
  cordova                       Not installed

Important local packages 
  quasar-cli                    0.17.23 (Quasar Framework CLI)
  quasar-framework              0.17.19 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.29.5  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.14  (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.6.3   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### JsFiddle
https://jsfiddle.net/41nersau/7/

### What did you get as the error?
The text didn't wrap according to the grid size of col-3

### What were you expecting?
The text should wrap 

### What steps did you take, to get the error?
Please refer to jsfiddle

**Comment by pdanpdan** [comment]
Please add this to your CSS file:

```styl
.q-if-inner > .row
  max-width 100%
```

This if you stick with v0.17.x.
It is fixed in v1 beta.

**Comment by haaah** [comment]
The solution works. 
Thanks for the support and amazing framework
