### ISSUE TITLE
quasar.conf   fallback for open in browser

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3627]
If I'm using:
```js
devServer: {
  open: 'Safari'
},
```
But my colleague doesn't have eg. Safari, it will error and he won't be able to start the dev server.

I would love support for this syntax:
```js
devServer: {
  open: ['Safari', 'Google Chrome']
},
```
that makes it so it will open automatically in Safari for me, but fall back to Google Chrome when that browser is not available.

**Comment by rstoenescu** [comment]
You can request it here: https://github.com/sindresorhus/opn
Thanks.

**Comment by mesqueeb** [comment]
Hi @rstoenescu 
I saw in the latest update: **feat: Failsafe when trying to open browser**

Is this related to this thread?

**Comment by rstoenescu** [comment]
@mesqueeb No. It's related to something else -- it won't break the CLI when `opn` fails now.
