### ISSUE TITLE
[v1] en locale in language packs

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3632]
It could be a good idea to provide a language pack just with 'en' as locale, it should be a copy of en-us or en-gb.
This because some browser (such as Firefox) provides the 'en' locale as language. So when I get the locale from the browser I could use it to get directly the package.
I didn't do a pull request because It's just a copy.

**Comment by rstoenescu** [comment]
"en" is not a valid ISO language name. It's either "en-US" or "en-GB". This should be considered as a bug in Firefox. Until they fix it (they should!), you could just compute the locale before requesting it from Quasar.
