### ISSUE TITLE
[v1] [request] Add on blur option

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#3635]
Hello,

the new QSelect API don't give an option to `add on blur`

### First feature
The only way to select/add and option is to press `Enter` button. But a lot of user prefer press `Tab` button.

### Second feature
When option is find on autocomplete and use `Arrows` on keyboard to focus an option, a lot of user prefer press `Tab` button also.

Do you think it's possible ?

Thanks.

**Comment by rstoenescu** [comment]
Should be available in beta.13.

**Comment by picbenoit** [comment]
Do you plan to add an **keyup event** to input select too ?
I currently migrate a quasar project to v1.
I used before a q-chips-input that allow to listen all input event, that not is case of qselect with an input.
For example, I want to add value on blur but also if user input specifics chars (My example is an input mail destination => if user input ";" or "," that means this is a new email).

**Comment by DaedalusDev** [comment]
@rstoenescu

> Should be available in beta.13.

Hi,

has i told in #5037, the feature didn't work has well. The only available key to select an option on a QSelect, is to press `Enter`.

I this a feature regression or a rejected feature ?

Thanks.

**Comment by rstoenescu** [comment]
@picbenoit keyup/keydown/keypress just added and will be available in v1.1.1
@DaedalusDev this is as designed and I've explained it numerous times, however you will be able to tap into keyup/keydown/keypress in v1.1.1
