### ISSUE TITLE
Q-select - Text exiting out in multiple mode

### ISSUE THREAD

**Issue by patrickmonteiro** [quasarframework/quasar#3638]
Quasar: 0.17.20
OS: Windows
Node: 8.9.3
NPM: 6.4.1
Browsers: Chrome, Firefox

When I use multiple mode with many options, they end up leaving the component.

![image](https://user-images.githubusercontent.com/13258255/54726737-2b293380-4b53-11e9-9268-948f752494e1.png)

**Comment by pdanpdan** [comment]
Check if this helps you:
https://github.com/quasarframework/quasar/issues/3626
