### ISSUE TITLE
[v1] QItem: Maximum call stack size exceeded error when enabling a component

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#3639]
https://codepen.io/tomers-the-encoder/pen/VREJdX

In this pen I have a disabled list item (through a disabled data attribute) that has a click handler which sets the disabled data attribute to false (enabling it). On first click it works, and the item gets enabled. On the second click I get the following error in console: `RangeError: Maximum call stack size exceeded`.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this.
Fix will be available in beta.12.

Note that if you disable a QItem no `@click` event will be emitted (which is one of this prop's purposes).
