### ISSUE TITLE
[v1] Feature Request: pass Vue class to createStore and createRouter

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3640]
I got an issue, in my particular architecture it happens that the Vue instance inside the route or the store index module is different from the original Vue instance. So in my system, I have different Vue instances. So when I import Vue instance normally is not guaranteed that the instance is the same.
For this reason I have the need to receive the original Vue instance in createStore and createRouter functions (these functions are located in .quasar/app.js) for example in .quasar/app.js file we could have:

```
import {Vue} from './import-quasar.js'

...
const store = typeof createStore === 'function'
    ? createStore({Vue})
    : createStore

  const router = typeof createRouter === 'function'
    ? createRouter({store, Vue})
    : createRouter
...
```

this is not a breaking change and add some functionality. I hope this is possible. It introduces changes only in the generation of file import-quasar.js and app.js.

**Comment by rstoenescu** [comment]
Hi,

Assumption based on your description: "Vue instance" -> "Vue instance of App"

Unfortunately this is not possible. The Vue instance of the App needs the instances of Vuex Store and Vue Router when getting instantiated. (`new Vue({ store, router, ... })`). The store and router need to get instantiated before we instantiate the App. It's how Vue works.

However, can you be more specific on what your needs are? Try to use the appropriate terminology so we can be on the same page. Also, what are you building? (spa/pwa/ssr/...)

Thanks.

**Comment by willypuzzle** [comment]
I express myself badly, it is not the Vue instance but the original Vue class, the same you pass at the boot components.
I need to share the same class in functions.
I'm building a spa.

**Comment by rstoenescu** [comment]
Are you referring to `import Vue from 'vue'`? Cause that would suffice.

**Comment by willypuzzle** [comment]
Not in my case because I've stored the route instantiation code in a different package (I use the same codebase in more than one project) so what I import with ```import Vue from 'vue'``` differs

**Comment by rstoenescu** [comment]
Pushed a commit to add this, but I'd really be interested in checking out your repo to see what you are exactly doing.

Will be available in beta.12
