### ISSUE TITLE
Header Size on IE11 & Edge

### ISSUE THREAD

**Issue by altShiftDev** [quasarframework/quasar#3641]
### Software version
Quasar: CLI: v0.17.23 & Framework: v0.17.19
OS: Windows 10, 8.1 & 7
Node: 9.8.0
Yarn: 1.10.1
Browsers: IE11 & Edge
Any other software related to your bug: (I'm using quasar in SSR mode)

### JsFiddle

Sorry, couldn't get q-layout, q-layout-header or q-toolbar to render in the fiddle...

### What did you get as the error?
CSS prevents the header from growing beyond 50px
### What were you expecting?
Header to scale to content height like it does in Chrome, Firefox, Safari, etc.
### What steps did you take, to get the error?
Make a header similar to the following with images and padding that force the header to be greater than 50px:

```
  <q-layout view="hhh Lpr fff">
  <q-layout-header class="no-shadow">
    <q-toolbar color="primary" inverted class="justify-around wrapping-toolbar q-px-lg-none q-py-none">
      <q-toolbar-title class="row justify-between items-center col-12 q-px-xl-xxl q-px-lg-xxl q-px-md-xl q-px-sm-lg q-px-xs-md q-my-sm-none q-my-xs-md">
        <span class="cursor-pointer">My Site Title</span>
      </q-toolbar-title>

      <div class="q-px-xl-xxl q-px-lg-xxl q-px-md q-py-sm q-pt-xs-md print-hide">
        <span class="col-auto q-subheading q-pl-sm">Powered by...</span>
        <div class="row justify-around items-center col-12 bg-white">
          <div class="col-md-8 col-xs-12 row justify-sm-between justify-xs-around collaborators q-py-lg">
            <img src="statics/logos/logo1.svg" alt="Logo 1" class="col-sm-auto col-xs-6 q-pa-sm-xs q-pa-md-none">
            <img src="statics/logos/logo2.svg" alt="Logo 2" class="col-sm-auto col-xs-6 q-pa-sm-xs q-pa-md-none">
            <img src="statics/logos/logo3.svg" alt="Logo 3" class="col-sm-auto col-xs-6 q-pa-sm-xs q-pa-md-none q-my-sm-none q-my-xs-md">
            <img src="statics/logos/Logo 4.svg" alt="Logo 4" class="col-sm-auto col-xs-6 q-pa-sm-xs q-pa-md-none q-my-sm-none q-my-xs-md">
          </div>
          <div class="col-auto text-info q-subheading">French</div>
        </div>
      </div>
    </q-toolbar>

  </q-layout-header>
</q-layout>
```

The offending CSS seems to be this: 
```
@media all and (-ms-high-contrast:none), screen and (-ms-high-constrast:active)
  .q-actionsheet-title, .q-field-label-inner, .q-toolbar {
    height: 0px;
  }
```
Unfortunately it's harder to fix than that since `.q-layout-page-container` has its style edited to include sufficient top padding to accommodate the header height but they become out of sync when you force the height to be unset or auto.

**Comment by pdanpdan** [comment]
If you can provide a codepen or some online place where I can check I'll take a look.

**Comment by altShiftDev** [comment]
@pdanpdan thanks. I can confirm the fix works well!
Even though it's a dumb little bug, still think it would be good to update the quasar global css for the toolbar so it doesn't happen to others on IE/Edge.
```
.q-toolbar {
  height: auto;
}
```

**Comment by rstoenescu** [comment]
Fix will be available in beta.14.
