### ISSUE TITLE
[v1] Request: q-item 'disable' property works just like as q-btn 

### ISSUE THREAD

**Issue by botura** [quasarframework/quasar#3643]
`q-item disable` property change only the appearence, item is still clickable.

I think it should works the same way as `q-btn`.

If staff consider it is implemented correcttly, I suggest to change the description of `disable` property in both components, so user can know what is expected from this property. And also add some examples of `q-menu` using `q-btn` (all examples use `q-item`).

Disable menu items is a pretty common function on business app, where some items should be disabled under specific conditions (user level, closed invoice, etc).

[Here is a code pen to verify](https://codepen.io/botura/pen/ywRdem?editors=1010)

**Comment by nothingismagick** [comment]
Thanks for this write-up! I am pretty confident that it SHOULD actually disable the click, but hopefully @rstoenescu can confirm and triage.

**Comment by rstoenescu** [comment]
Already fixed this. Will be available in beta.12
