### ISSUE TITLE
[v1] Cannot highlight (to edit) filter text in QSelect

### ISSUE THREAD

**Issue by robopeter** [quasarframework/quasar#3645]
### Software version
v1.0.0-beta.11

### JsFiddle
Any of the existing "Select" > "Filtering and autocomplete" Fiddles in the documentation.

### What did you get as the error?
N/A

### What were you expecting?
After typing in a filter value, I was expecting to be able to highlight with the mouse some or all of the text I just typed in order to edit / delete / copy whatever it. 

### What steps did you take, to get the error?
Type some text in a QSelect filter, try to click-and-drag highlight it with the mouse.

**Comment by robopeter** [comment]
Reproduces on Chrome and Edge (current versions) on a Windows PC. Does not seem to be a problem in Chrome on Android.

**Comment by rstoenescu** [comment]
Fix will be available in beta.12
