### ISSUE TITLE
[v1] [Feature Request] "type" property for QSelect filter

### ISSUE THREAD

**Issue by robopeter** [quasarframework/quasar#3646]
### Software version
v1.0.0-beta.11

### What were you expecting?
I was using a QSearch with a QAutocomplete in v.17 with a "type" property on the QSearch to specify if it should autocomplete with a string or number. I have moved to using a QSelect with filtering as described in the upgrade documentation, however, there now seems to be no way to specify what type of input the filter should be. 

### Request
Please allow specifying a "type" for the filter behavior of a QSelect.  Thank you!

**Comment by rstoenescu** [comment]
Hi,

Please upgrade to latest beta (21 as of writing these lines). The "type" will go as attribute on the inner "native" input (along with any other attributes you specify). One caveat though: When you filter with your function, cast the value to Number.
