### ISSUE TITLE
A QTree's node children aren't observable when using lazy loading

### ISSUE THREAD

**Issue by delucasvb** [quasarframework/quasar#3650]
### Software version

Quasar: 0.17.22
@quasar/app (v1+ only):
OS: Ubuntu 16.04
Node: v10.15.3
NPM: 6.4.1
Browsers: Chrome
iOS: /
Android: /
Any other software related to your bug:

### What did you get as the error?
This is not my bug, just context: I want to use lazy loading combined with checkboxes on all nodes, but the checkboxes should always be visible, not only when its subtree has been loaded.
The bug: I use a custom template as the `default-header` that looks like this:
```
<div
  slot="default-header"
  slot-scope="prop"
>
  <q-checkbox
    :value="prop.node.ticked"
    @input="treeCheckboxChanged($event, prop.node)"
  />
  <span>{{ prop.node.label }}</span>
</div>
```
For nodes that are already in the tree (no lazy loading required), this works fine. However, when a node's children are lazy loaded, the `done` method sets the children like this:
```
if (children) {
  node.children = children
}
```
Which is not observable by Vue. So checking/unchecking the checkbox doesn't work.

### What were you expecting?
That all of `prop.node`'s properties were observable. They are for nodes that are preloaded, so they should be for lazy loaded nodes as well.

### What steps did you take, to get the error?
Code is above.
I fixed it by not passing the children to the `done` method directly, but instead letting Vue set them:
```
let children = await this.loadChildren(node.key)
Vue.set(node, 'children', children)
done()
```

**Comment by rstoenescu** [comment]
Fix will be available in beta.12
