### ISSUE TITLE
How can i access dev server from intranet device?

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#3652]
I've tried to configure the server port in "quasar.conf.js", but faild when i visit ‘192.168.2.XXX:8080’. And my backend api services is ok. sth wrong ？

`devServer: {
host: '0.0.0.0'
}`

Quasar: 1.0.0-beta.11
@quasar/app: 1.0.0-beta.10
OS: Windows 10 x64 1809
Node: 10.15.3
NPM: 6.9.0

**Comment by rstoenescu** [comment]
Hi,

Please use our Discord or forum for questions. Thank you.
