### ISSUE TITLE
[V1 documentation] add release notes

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3657]
We should have a link to release notes in the docs.

And preferably the [Github releases page](https://github.com/quasarframework/quasar/releases) > forum release notes, because on the Github one you can actually click on issues. 🌝

**Comment by rstoenescu** [comment]
Will be available on next deployment.

**Comment by mesqueeb** [comment]
@rstoenescu I saw the release notes added to the docs.
I was actually more thinking in the direction of adding it somewhere like here:

<img width="308" alt="Screenshot 2019-03-26 15 41 53" src="https://user-images.githubusercontent.com/3253920/54976489-dc115180-4fdd-11e9-8b78-d431bc112848.png">

I think it makes a lot of sense when we check the "versions" menu to also have a link to "release notes" in there.
When people come to the site and see in the top right:
> Oh! the version is higher than before!
they might feel compelled to actually tap that version and there they could find a link to the release notes.
