### ISSUE TITLE
[Quasar v1] Issue with the error display with icons

### ISSUE THREAD

**Issue by mohanzeal** [quasarframework/quasar#3658]
I am using fontawesome icons in my project. 

**Error description:**
**when I have an error in the form error icon is displaying on side by side, please check the screenshot. I think exlamation icon should replace default input icon** .. 

![error](https://user-images.githubusercontent.com/5113135/54863628-14f8be80-4d71-11e9-979b-546a79c7fe71.png)

sample code:
`<q-input
  ref="email"
  v-model="loginForm.email"
  @blur="$v.loginForm.email.$touch"
  :error="$v.loginForm.email.$error"
  :placeholder="$t('general.emailPlc')"
  type="email"
  filled
  :label="$v.loginForm.email.$error ? 
  $t('general.emailVldn') : $t('general.emailLbl')"
>
  <template v-slot:append>
    <q-icon name="fa fa-envelope"/>
  </template>
</q-input>`

I am using the latest quasar beta version
    "@quasar/extras": "^1.0.0"
    "quasar": "^1.0.0-beta.11"
    "@quasar/app": "^1.0.0-beta.12"

**What might be the error?**

**Comment by smolinari** [comment]
@mohanzeal - If I understand you correctly, if the exclamation icon replaces the other icon on the right, this would have issues with the functionality that icon may have as a button. Think about date inputs or time inputs or even the view password function in the example you show above. If the exclamation icon replaced that icon (button), then that function would be missing. 

Scott

**Comment by mohanzeal** [comment]
@smolinari  thanks a lot for correcting my understanding approach... I was thinking in generic way and didn't go with the higher overview..

Considering your approach, I have fixed it by having a simple if condition on the append slot.
**v-if="!$v.loginForm.email.$error"**
 
`<q-input
  ref="email"
  v-model="loginForm.email"
  @blur="$v.loginForm.email.$touch"
  :error="$v.loginForm.email.$error"
  :placeholder="$t('general.emailPlc')"
  type="email"
  filled
  :label="$v.loginForm.email.$error ? 
  $t('general.emailVldn') : $t('general.emailLbl')">
  <template v-slot:append v-if="!$v.loginForm.email.$error">
    <q-icon name="fa fa-envelope"/>
  </template>
</q-input>`
