### ISSUE TITLE
[documentation] Touch-hold .prevent.stop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3661]
In the [Touch-hold documentation](https://v1.quasar-framework.org/vue-directives/touch-hold) at the bottom: **API**

At "modifiers" it only says `mouse`, but **if we're able to use `.prevent.stop`** as well, I think it might be really helpful if they are listed there as well!

If we are **NOT able to use `.prevent.stop`**, i'd love to ask this to be added as a new feature.

**Comment by rstoenescu** [comment]
If we add prevent and stop then user won't be able to select text. It's pretty complicated to explain all the reasoning (takes pages), but regardless, if you need it you can evt.preventDefault() and evt.stopPropagation() yourself in the handler, at the right time.
