### ISSUE TITLE
[V1 - request] Delay focus event with `touch-hold`

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3662]
I'm using Quasar [touch-hold](https://v1.quasar-framework.org/vue-directives/touch-hold#API) on a button, and I need to delay the element being focussed until the hold event actually fires.

Is there any way I can do this?

If not I'd love to request this functionality.

**Comment by mesqueeb** [comment]
This request might be too "hacky" and perhaps it's better not to mess with the .focus which is handled by the browser...

**Comment by rstoenescu** [comment]
Hi, the focus is browser based. If we tamper with it then the directive won't work correctly... Sorry.
