### ISSUE TITLE
Label overlaps when not focused and value isn't set <q-input type="date

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/quasar#3663]
### Software version

Quasar: v1.0.0-beta.11 (and .13 on codepen)
@quasar/app: v1.0.0-beta.12
OS: All
Node: All
NPM: All
Browsers: All

### Codepen
https://codepen.io/anon/pen/VRgQvq

### What did you get as the error?
Similarly to #2995, the label overlaps when the `q-input` field is not focused and not set when the type is `date` or `time`

### What were you expecting?
The label not to overlap as with other input types

### What steps did you take, to get the error?
Just added the field, label, type and v-model

**Comment by pdanpdan** [comment]
As it's written in the docs use `stack-label`.
The tip in the docs uses the exact example you have: https://v1.quasar-framework.org/vue-components/input#Input-types
