### ISSUE TITLE
[V1] QMenu: position + context-menu

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3665]
I need a QMenu with these props:
- `anchor="top middle" self="bottom middle"`
- `context-menu`

However, by adding `context-menu` to enable it to only be called on right click, it looses the anchor & self positioning...

Is there any way around this to use both `anchor`, `self` **and** `context-menu` ?

**Comment by rstoenescu** [comment]
Hi,

Context menus are designed to respond to right click and show at the position where the event occurred on screen. Not going to change that.
