### ISSUE TITLE
[v1] QSelect - options-value is being ignored

### ISSUE THREAD

**Issue by TobyMosque** [quasarframework/quasar#3672]
### Software version

Quasar:  1.0.0-beta.13
@quasar/app (v1+ only):
OS: 
Node:
NPM:
Browsers: Opera
iOS:
Android:
Any other software related to your bug:

### JsFiddle
https://codepen.io/tobias-mesquita/pen/jJJZYM?&editable=true&editors=101

### What did you get as the error?
`option-value` property is being ignored when `options` is a array of objects.
in the codepen, u'll notice than `single` and `multiple` is a object instead of a integer.

### What were you expecting?
`value` property respect the `option-value`.
in the codepen, `single` would be a integer and `multiple` a array of integers.

### What steps did you take, to get the error?
open the codepen and watch `single` and `multiple` fields.

**Comment by pdanpdan** [comment]
It's `option-value` and `option-label` - singular.

**Comment by TobyMosque** [comment]
@pdanpdan thx, i corrected the typo, but since `label` and `value` are the default values of `option-label` and `option-value`, so that wouldn't affect the sample.

**Comment by pdanpdan** [comment]
Then you got it wrong. What you want is emit-value and map-options - then you can specify option-value. If you have no emit-value then the whole object is emitted.

**Comment by TobyMosque** [comment]
@pdanpdan i noticied that too.
