### ISSUE TITLE
[v1] QTable - custom template row with field function

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#3673]
### Software version

Quasar: 1.0.0-beta.13
@quasar/app (v1+ only):
OS: Win 10
Node: v10.15.3
NPM: 6.4.1
Browsers: Chrome, iOS Safari,
### JsFiddle
https://jsfiddle.net/mojimo/5cbzodjr/

### What did you get as the error?
If I use template with columns and rows ```field``` value is not calculated but used original value.
```
   field: (row) => "field calculated"
```
```
<q-table :columns="table" :data="acfts" row-key="name" title="Table B">
    <template v-slot:body="props">
      <q-tr :props="props">
        <q-td :props="props" key="rte">{{ props.row.rte }}</q-td> 
        <q-td :props="props" key="star">{{ props.row.star }}</q-td> 
      </q-tr>
    </template>
  </q-table>
```
![image](https://user-images.githubusercontent.com/37825539/54922481-861eaa00-4f08-11e9-9e17-537d70133b75.png)

### What were you expecting?
I expected value to be calculated as with simple QTable: row should contain "field calculated"
```
<q-table :columns="table" :data="acfts" row-key="name" title="Table A"></q-table>
```
![image](https://user-images.githubusercontent.com/37825539/54922444-6e472600-4f08-11e9-801b-5f977e4ae6f3.png)

**Comment by rstoenescu** [comment]
``{{ props.cols[<columnIndex>].value }}`` (from memory; to get accurate, just check `props.cols`)
``props.row`` is reserved for the original data, in case you need to use it.

**Comment by m0jimo** [comment]
It means ```field/format: (row) =>`${val}%`"``` can only be used for simple table and values in templates needs to be processed via custom function. It makes sense now. Thanks.
