### ISSUE TITLE
[v1] q-drawer with q-scroll-area scroll issues on iOS

### ISSUE THREAD

**Issue by martinflorek** [quasarframework/quasar#3674]
### Software version
v1.0.0-beta.13

Quasar:
@quasar/app (v1+ only):
OS: iOS 12.1
Node:
NPM:
Browsers: Safari
iOS: 12.1
Android:
Any other software related to your bug:

### JsFiddle
[JSFiddle](https://jsfiddle.net/130wx4a6/1/)

### What did you get as the error?
Swiping over q-drawer randomly scrolls the whole web page, the q-page's content and q-drawer's content. Slow swipe, fast swipe and fling all have random behaviour of what will scroll.

Tested on iPhone X, iPad pro 12.9 and iPad pro 12.9 simulator. All with iOS 12.1. We did not test on older iOS versions.

### What were you expecting?
Swipe over q-drawer should scroll just the drawer's content.

### What steps did you take, to get the error?
We have a q-drawer with a q-scroll-area inside for scrollable side menu. This works OK on all platforms except on the iOS. We have a mini drawer with a button that expands it.

iPad in landscape mode so the menu is collapsed, then click the small arrow button at the bottom to expand it. Scrolling the expanded drawer randomly scrolls the drawer, the page content or the whole webpage.

**Comment by rstoenescu** [comment]
Hi,

This is due to iOS and unfortunately there's no way around it. Sorry for any inconvenience.
