### ISSUE TITLE
[Request] Display avatars/thumbs as horizontal list below slider/image gallery

### ISSUE THREAD

**Issue by hatavan83** [quasarframework/quasar#368]
I want to display avatars/thumbs as horizontal list below slider/image gallery. Can we custom dots as same as custom action ? Could you please guide me how to config or implement them ?

**Comment by murbanowicz** [comment]
For this kind of questions please use forum. Github is for issues only.

2017-02-03 6:31 GMT+00:00 HaTa <notifications@github.com>:

**Comment by rstoenescu** [comment]
Added `horizontal-quick-view` Boolean prop for GallerySlider.
Available in future v0.14.
