### ISSUE TITLE
[v1][QBtn] icon margin not applied when default slot used instead of label prop

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#3683]
When using `QBtn` if I use the default slot instead of `label` prop, `margin-right` on `icon` is not applied.
Pen: https://codepen.io/behnoodk/pen/XGGwdR

**Comment by rstoenescu** [comment]
This is normal. When using default slot you are in charge of handling the content. For ease of use, you can use the `right` or `left` props on QIcon.

**Comment by rstoenescu** [comment]
Fix will be available in beta.14
