### ISSUE TITLE
Dialog:  TypeError: Cannot read property 'mobile' of undefined

### ISSUE THREAD

**Issue by zinwalin** [quasarframework/quasar#3685]
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'mobile' of undefined"

**Comment by rstoenescu** [comment]
Hi,

There's a reason why we ask everybody to fill in the github issue template.
The description is not helpful at all. What Quasar version are you using? What Quasar mode are you developing/building with? SPA/PWA/SSR/Cordova/Electron....? Please reopen with a Codepen or jsFiddle. Thanks.
