### ISSUE TITLE
[Documentation Request] List of available Named Slots for each Component

### ISSUE THREAD

**Issue by haaah** [quasarframework/quasar#3689]
Currently within the document there isn't a dedicated area where we can find what's the available named slot for each component. The only way is to study through the code or through example given.

Would like to have a table within the documentation with the following format
<img width="765" alt="Screenshot 2019-03-26 at 2 27 47 PM" src="https://user-images.githubusercontent.com/8482031/54975844-643e2980-4fd3-11e9-9cee-2cc5b0ad04e0.png">

**Comment by smolinari** [comment]
@haaah - That image is from the "old" docs.

[Check this out from the new docs for v1.0.](url)https://v1.quasar-framework.org/vue-components/table#QTable-API

Scott

**Comment by haaah** [comment]
Glad to know that this is available in V1.0.

Thanks.
