### ISSUE TITLE
[Request] Set color/event for dates and multi selection/range selection on DatePicker/Calendar component 

### ISSUE THREAD

**Issue by hatavan83** [quasarframework/quasar#369]
I want to set colors/events for dates when initialize the calendar (ex: 1-1-2017 is red, 21-1-2017 is blue) and and multi selection/range selection dates on DatePicker/Calendar. Could you please guide me how to config or implement them ??

**Comment by murbanowicz** [comment]
For this kind of questions please use forum. Github is for issues only.

2017-02-03 6:34 GMT+00:00 HaTa <notifications@github.com>:

**Comment by rstoenescu** [comment]
What I suggest is adding a special CSS class (that you write on your app) on the calendar binded on a computed value that takes into account calendar's model. Let me know if you need further details although I think this should be easy.
