### ISSUE TITLE
[V1] Pull to refresh - pull down UI elements

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3690]
So I understand the **pull to refresh** is a simple and effective component of Quasar.

However, all pull to refresh implementations I see around **actually pull down the UI to have a refresh arrow appear.** This is sometimes the entire UI, or sometimes the part of the UI that's actually "being pulled" by your finger.
(see google news, google search app, spark the email client, google chrome mobile browser, .........)

With Quasar I think it feels really weird that the actual content isn't pulled down and just a refresh arrow appears on top of the content out of nowhere. Or am I using it wrong?

I'd like to request some form of this functionality. It seems rather tricky to do so.

**Comment by simonwangtx** [comment]
Yeah, it is weird only showing an arrow while the whole content doesn't move!

**Comment by rstoenescu** [comment]
The description matches perfectly how this component works in v1. So closing this ticket.

**Comment by mesqueeb** [comment]
I'm sorry, I meant this issue to be a request.

- Everywhere on the web "Pull to refresh" drags the actual content down.
- Quasar just reveals a refresh arrow on top of the content and the content stays put.

I think it makes much more sense **for the actual page content to be pulled down as well**.

(I could make an app extension that does this, but I feel it is behaviour that everyone would want, so it should be a default feature of Quasar in my opinion.)

**Comment by rstoenescu** [comment]
This would be against Material specs. https://material.io/design/platform-guidance/android-swipe-to-refresh.html#usage

Current way it works fulfills the Material Guidelines.

**Comment by mesqueeb** [comment]
I see!!
Ok then if I want the UI itself to be dragged down as well, I'll think of making an app-extension for it. : )

**Comment by rstoenescu** [comment]
@mesqueeb sounds good
