### ISSUE TITLE
q-tab-panel not rendering inside separate component

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#3694]
I am using QTabs with QTabPanels however, if I render my <q-tab-panel> components inside of separate components, they will not render inside of ```<q-tab-panels>``` at all (they aren't mounted either).

For example:

```
          <q-tabs v-model="selected" inline-label align="center">
            <q-tab icon="mdi-account" name="clientDetails" label="Client" />
            <q-tab icon="mdi-paperclip" name="additionalDetails" label="Additional" />
          </q-tabs>
```
```
<q-tab-panels>
   <q-tab-panel name="clientDetails">this works!</q-tab-panel>
</q-tab-panels>
```

However:
ClientPartial:
```
<template>
  <q-tab-panel name="clientDetails">this won't work!</q-tab-panel>
</template>
```

```
<q-tab-panels>
   <ClientPartial /> <!-- This won't render! -->
</q-tab-panels>
```

**Comment by pdanpdan** [comment]
The direct children of QTabPanels must have a `name` property and this must be unique.
This is what QTabPanel enforces (and some styles, but these are not so important).
What you did was to provide QTabPanels with no child with a `name` prop.

The expected way would be to use it like:

```html
<q-tab-panels v-model="current_tab">
  <q-tab-panel name="name1">
    <client-partial .... />
  </q-tab-panel>
</q-tab-panels>
```

with `ClientPartial` implementing the panel content.

**Comment by nicholaszuccarelli** [comment]
Given that ClientPartial's first element is a q-tab-panel, wouldn't this render as a direct child?

What if I gave a name attribute to ChildPartial?

**Comment by nicholaszuccarelli** [comment]
Thanks for the help there.
I'll close this issue but I then come across the issue with keep-alive attribute for tab panels (which I used previously) and has been logged as an issue already.
Thanks :)
