### ISSUE TITLE
q-route-tab navigates when disabled

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#3697]
Setting `disable` on a `q-route-tab` looks correct visually, but still navigates when clicked.

Codepen: https://codepen.io/dsl101/pen/bZJPBw

`q-tab` doesn't seem to exhibit this behaviour, only `q-route-tab`.

**Comment by rstoenescu** [comment]
Fix will be available in beta.14.

**Comment by mauroartizzu** [comment]
Hello, I think this still doesn't work as expected. I am facing the same beaviour both in master and dev branches

**Comment by pdanpdan** [comment]
I just tested the codepen in the OP and all is good. Please provide codepen and all the details required to reproduce.

**Comment by mauroartizzu** [comment]
nvm I misspelled disable. The style was working both with disable and disabled so I thought it was correct. I also saw the codepen was working. Sorry and thanks!
