### ISSUE TITLE
Modal with Layout on IOS

### ISSUE THREAD

**Issue by bboywulong** [quasarframework/quasar#370]
on IOS, Modal with Layout hierarchy problems

**Comment by rstoenescu** [comment]
Hi, can you be more specific pls? Also include a screenshot and your layout code. Thx!

**Comment by rstoenescu** [comment]
Please reopen with my requests. I see no issue with it. Thanks!

**Comment by bboywulong** [comment]
This is my cord
![cordbug](https://cloud.githubusercontent.com/assets/17426924/22615051/821c1f84-eac7-11e6-8fc9-dfbb3510bc42.png)

On android
![android1](https://cloud.githubusercontent.com/assets/17426924/22615060/a89e1d6a-eac7-11e6-9376-20cb20da5f30.PNG)
![android2](https://cloud.githubusercontent.com/assets/17426924/22615061/ade05824-eac7-11e6-8a69-bf1943399fa3.PNG)

On IOS, modal layout can't cover main layout
![ios1](https://cloud.githubusercontent.com/assets/17426924/22615065/bc968280-eac7-11e6-9eba-412cde690a96.PNG)
![ios2](https://cloud.githubusercontent.com/assets/17426924/22615068/c10f62d2-eac7-11e6-81d7-dab3a3dd10b1.PNG)

**Comment by rstoenescu** [comment]
Will investigate it.

**Comment by bboywulong** [comment]
I find when your quasar-play is well
![qq20170206-102900](https://cloud.githubusercontent.com/assets/17426924/22632850/b9d2ad9e-ec57-11e6-88f4-c75e23f1f37d.png)
![qq20170206-103000](https://cloud.githubusercontent.com/assets/17426924/22632897/0b25eecc-ec58-11e6-9d2d-bb3d9521bb1f.png)

On my app
![qq20170206-103134](https://cloud.githubusercontent.com/assets/17426924/22632912/28d87e4e-ec58-11e6-87c7-4c71579eaf9b.png)
![qq20170206-103323](https://cloud.githubusercontent.com/assets/17426924/22632915/31506abe-ec58-11e6-9e3f-78ff2b8dc267.png)

if I copy your quasar-play modal.vue in my app, have the same problem, I think my layout or view have problem?

**Comment by rstoenescu** [comment]
Ah, please upgrade to at least v0.13. You'll find that this issue is fixed.
