### ISSUE TITLE
[v1] [Request] q-select with multiple and clearable

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#3703]
I prefer the position of the icon when using `clearable`, which doesn't seem possible using `<template v-if="model" v-slot:append>` and implementing via a `q-icon` as per the documentation.

But, when using `multiple`, much of the rest of my app depends on the model being an empty array (not `null`) when nothing is selected.

I guess there are three possible ways to solve it (in order of preference for me, but I realise option 1 may surprise other people):
1. When the `q-select` has a `multiple` prop, change the clear value automatically to `[]` rather than `null`. Note this would also need the `v-if` of the `clearable` icon changing too, as `[]` is truthy, so `v-if="model"` would always show the icon.
2. Introduce a `clear-value` prop (default to `null`) which would allow changing the value which represents a 'cleared' state. This may also be useful for the case where an empty string is preferred over `null` in a regular (i.e. non-`multiple`) select.
3. Provide another named slot which could position the icon in the same place as `clearable` does (i.e. before the drop arrow in the select box).

**Comment by pdanpdan** [comment]
Just replace `v-model="model"` with `:value="model" @input="val => model = val === null ? [] : val"`

**Comment by rstoenescu** [comment]
Hi,

This is what happens when playing nice and adding **a helper** feature. People start doing requests until using the slot becomes irrelevant. There is the slot which can fulfill custom usage. The documentation has examples with `clearable` then equivalent with slot, side by side. All I am trying to is to keep the render speed to be as fast as possible.

**Comment by dsl101** [comment]
The example in the documentation clearly shows the difference between `clearable` and via the slot:
![image](https://user-images.githubusercontent.com/900542/55173214-3263c900-5173-11e9-8009-c128f0c433dd.png)
That was the essence of the request. In this case, I can happily use @pdanpdan's solution, but it ties my app code closely to the internals of the QSelect—unlikely, but if the implementation of `clearable` changed from setting the model to `undefined` instead, the app would break.

**Comment by pdanpdan** [comment]
Then just use `:value="model" @input="val => model = Array.isArray(val) ? val : []"` and you are safe no matter the implementation.

**Comment by dsl101** [comment]
Tx for both of those :)
