### ISSUE TITLE
[UI] hr's don't align well

### ISSUE THREAD

**Issue by Async0x42** [quasarframework/quasar#371]
I'm not sure if this should be an issue or not; but if you lay out two side-by-side hr's, the edges of them curve a little and don't line up.

![image](https://cloud.githubusercontent.com/assets/3268854/22615199/b58b7b5e-ea5d-11e6-8d13-867b74d72fef.png)

Would there be a real negative impact from just making the hr's a straight line, vs curving at the edges? In the docs ( http://quasar-framework.org/guide/app-pre-processors.html#Using-Pre-Processors-inside-Components ) it's just a bottom border, so I'm wondering if there should really be a different or not.

(I've replaced mine with border-bottom's, this is just for discussion)

**Comment by rstoenescu** [comment]
Hi,

It's unclear to me what your issue is.
1. Is it an issue with Quasar, an issue with the docs or just a discussion?
2. Is the link above correct? It points to CSS preprocessors which have nothing to do with hr.

Waiting for your reply.

If

**Comment by Async0x42** [comment]
Sorry I should have made that much clearer when I wrote it! You can disregard this; I was using <hr> in a way that a border would make more sense after thinking about it. (The link was just referencing the border style on the headers, not the text content)
