### ISSUE TITLE
[v1] QTabs flicker bug on hover

### ISSUE THREAD

**Issue by Blaconix** [quasarframework/quasar#3713]
### Software version

Quasar:
@quasar/app (v1+ only): 1.0.0-beta.13
OS: Windows 10 1809 x64
Node: 11.12.0
NPM: 6.7.0
Browsers: Google Chrome Version 73.0.3683.86 (bug happens on Edge as well)

### JsFiddle
https://codepen.io/anon/pen/rRgEPK?
The issue doesn't actually happen in codepen. But happens with quasar-cli.

Here's a repo: https://github.com/Blaconix/quasar-tabs-flicker-bug

### What did you get as the error?
QTabs flicker on hover. Only happens when the text color is red.
I tried with `text-blue` and `text-yellow` and the flicker doesn't happen. Seems to only be happening with shades of red like `text-red`.

### What were you expecting?
No flicker on hover.

### What steps did you take, to get the error?
Created a new v1 project with quasar create, added the components to quasar.conf.js, added tabs in toolbar with `shrink` property and changed the class of QTabs to `text-red`. Also changed the toolbar background for contrast.

Here's an example gif showing the flickering. Focus on any tab and see how the font weight looks like it's changing but the property value always remains the same.
![flicker](https://user-images.githubusercontent.com/48924790/55075538-e3973000-509b-11e9-9d5f-e0a04c7398e9.gif)

Disclaimer: It might only happen to me. But nevertheless, it seems like an interesting bug, and because it only happens when using a red color, it leads me to believe there's something more deep involved.

**Comment by mountash** [comment]
It happens not only with red color.
Maybe it is somehow connected with CSS `outline` property. Every user agent adds its styles to components.
So Chrome for example adds `outline: -webkit-focus-ring-color auto 5px;` 
even it is overriden  in .q-focusable
`body.desktop .q-focusable, body.desktop .q-manual-focusable, body.desktop .q-hoverable {
    outline: 0;
}`
If you add in styles `outline auto 5px -webkit-focus-ring-color` to .q-focusable, it adds ugly border but stops flickering. 
I didn't find a solution yet, how to fix that 😞

**Comment by nothingismagick** [comment]
@Blaconix & @mountash - Can you confirm that this is still an issue in quasar v1.0.0-beta.23?

**Comment by Blaconix** [comment]
Just did a `quasar upgrade -i` on my repo above. Still happens.
![image](https://user-images.githubusercontent.com/13063686/57581452-40ba3a00-74c0-11e9-8a6f-e1eb8cde9f63.png)

**Comment by rstoenescu** [comment]
This should no longer happen in future v1.1.1.
