### ISSUE TITLE
[v0.17] electron date picker doesn't select

### ISSUE THREAD

**Issue by darknessm0404** [quasarframework/quasar#3714]
```
 Build mode........ electron
 Quasar theme...... ios
 Quasar CLI........ v0.17.23
 Quasar Framework.. v0.17.19
```

On Electron only, quasar date pickers can't change the current date.
The date picker element shows up correctly, everything is fine (year/day/months are scrollable), but clicking on one element does not change the date and does not close the date picker.
It does nothing until you click out of the picker, it closes the date picker without changing the date.

Thanks :)

**Comment by darknessm0404** [comment]
Solution: a switch to the Material theme fixes the problem as the date becomes selectable again.

**Comment by rstoenescu** [comment]
This is soon becoming obsolete as final v1 build closes in. Please switch to v1.
