### ISSUE TITLE
[v1 request] add flexible multiline chips

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#3715]
Sometimes, we have no available space to display chips with long text (in q-select, for example). Will be cool to add property like "multiline" for flexible height, width and word-wrap.

**Comment by rstoenescu** [comment]
Hi,

Please use some other method of displaying other than QChips if it does not meet your requirements. You are not required to use QChips only. Display as string or even write your own component to display the selection.

Unforuntately, changing QChips for multiline supports would break Material Guidelines and also introduce lots of problems with the avatar scaling.

Sorry for any inconvenience.
