### ISSUE TITLE
QDialog is not mounted in tests when used with mount()

### ISSUE THREAD

**Issue by dufia** [quasarframework/quasar#3717]
Follow up on this Discord chat: https://discordapp.com/channels/415874313728688138/450312684790087691/560449585307320322

I am using 1.0.

If used with `shallowMount()`, it mounts the stub fine. If used with `mount()` the `wrapper.html()` doesn't have any mention of the `<q-dialog>` component.

Some Quasar components run in their own context (QDialog, QMenu, QTooltip). I am not sure, but maybe this is somehow causing this problem.

Usually, I would just full mount the component that uses Quasar components and then trigger the events on components like QBtn. Currently, I can't do that.

My component:

```
<template>
  <div>
    <q-dialog
      v-model="sendFailureModalOpened"
      persistent
      :maximized="true"
      transition-show="slide-up"
      transition-hide="slide-down"
      content-class="dark-modal"
    >
       // HTML, Vue components and other Quasar components
    </q-dialog>
  </div>
</template>
```
My test:

```js
import { mount, createWrapper } from '@vue/test-utils';
import SendFailure from '@/components/Modals/SendFailure';
import { localVue, i18n } from '@/helpers/SetupLocalVue';
import Vuex from 'vuex';
import * as All from 'quasar'
const { Quasar, date } = All;

const components = Object.keys(All).reduce((object, key) => {
  const val = All[key]
  if (val && val.component && val.component.name != null) {
    object[key] = val
  }
  return object
}, {})

describe('SendFailure component', () => {
  let store;

  localVue.use(Quasar, { components });

  beforeEach(() => {
    store = new Vuex.Store();
  });

  it('renders and matches snapshot', () => {
    const wrapper = mount(SendFailure, {
      i18n,
      localVue,
      store,
    });

    expect(wrapper.element).toMatchSnapshot();
  });
});

```

Snapshot output:

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`SendFailure component renders and matches snapshot 1`] = `
<div>
  <!---->
</div>
`;
```

**Comment by rstoenescu** [comment]
Hi,

The QDialog, QMenu and QTooltip components do not mount in the same place that they are used. They are mounted at the end of `<body>` **when they are opened** through a Quasar Portal.

What you should do is to use `content-class` prop, trigger QDialog to show, wait for it to be opened (attach a Vue ref and `@show` event handler -- `this.$refs.dialog.$once('show', handlerFn)`) then look in DOM for that class --> that would be your DOM node that has the QDialog content.

**Comment by dufia** [comment]
@rstoenescu 

I've tried it, although I can tell the dialog is being opened somewhere, I cannot find a way of selecting any of its children.

In my tests, `wrapper.vm.$refs.dialog` exists, the dialog is opened when I set `sendFailureModalOpened` to true. I just cannot find a way of finding the elements within it. `wrapper.find(selector)` won't work obviously.

Thanks for trying to help!
