### ISSUE TITLE
QTable column sort function should be able to work with the rows itself

### ISSUE THREAD

**Issue by Ironirc** [quasarframework/quasar#3718]
**Situation now:**
example:
{
          name: 'date',
          label: 'Date',
          field: row => date.formatDate(row.date, 'DD/MM/YYYY'),
          sort: (a, b) => complicatedCompare(a, b),
          sortable: true
        }

The arguments a and b take the formatted values.
In this case '01/02/2019'
The compare function is complicated, because it has to parse the formatted strings back to a date, and compare those.

**Desired:**
Ability to take the row objects for sorting
{
          name: 'date',
          label: 'Date',
          field: row => date.formatDate(row.date, 'DD/MM/YYYY'),
          sortRaw: (rowA, rowB) => rowA.date - rowB.date,
          sortable: true
        }

**Comment by rstoenescu** [comment]
Hi,

There is "sort-method" prop for this on QTable. Point to a method. Look into the QTable API section and use the filter (type "sort-method") there. ;)

**Comment by Ironirc** [comment]
Hi Razvan,

First of all congratulations with your framework, an amazing achievement! 

If I understand it correctly this "sort-method" is a table-global sort method?
That's not really what I was after.

I managed to solve my problem by using a format function on the column.

Still, I think that my proposal would offer a more generic way to do custom sorting.
Instead of introducing a new column sort function, it would be easier to add 2 optional arguments?
sort: (a, b, rowA, rowB) => myCompareFunction(rowA, rowB)

**Comment by rstoenescu** [comment]
@Ironirc Good point. Will be available in beta.14.

**Comment by Ironirc** [comment]
Thanks Razvan!
