### ISSUE TITLE
[v1] tabindex is rendered twice on input fields

### ISSUE THREAD

**Issue by Peter-Krebs** [quasarframework/quasar#3725]
### Software version
Quasar: Tested on v1.0.0-beta.1, v1.0.0-beta.13, 0.15.15+
OS: Windows
Node: v8.11.4
NPM: 5.6.0
Browsers: Tested in Chrome, probably not browser related

### JsFiddle
v1: https://jsfiddle.net/PeterKrebs/bpmn0cju/6/
v0.15.15 (same bug): https://jsfiddle.net/PeterKrebs/rt4jLyse/4/

### What did you get as the error?
The tabindex attribute is rendered twice on a q-input component. Once on the `.q-field` div tag and then on the input tag itself. May be the case for other form components as well.

```html
<div class="q-field row no-wrap items-start q-input q-field--standard q-field--labeled" tabindex="2">
  <div class="q-field__inner relative-position col self-stretch column justify-center">
    <div class="q-field__control relative-position row no-wrap">
      <div class="q-field__control-container col relative-position row no-wrap q-anchor--skip">
        <input tabindex="2" aria-label="Tabindex: 2" type="text" class="q-field__native">
        <div class="q-field__label no-pointer-events absolute ellipsis">Tabindex: 2</div>
      </div>
    </div>
  </div>
</div>
```

This means pressing tab the first time focuses the div with the tabindex attribute. Pressing tab once more then focuses the input field.

### What were you expecting?
Pressing tab should focus the input field immediately.
Removing the tabindex from the `.q-field` div should resolve this.

### What steps did you take, to get the error?
Setting the tabindex attribute on a q-input - regardless of directly setting the attribute with `tabindex="1"` or dynamically via `:tabindex="tabindex"`.
This may also be true for other form components. Focusing first (get it?) on the input field for now.
Resolving this for other form components should be the same solution.

Edit: wording

**Comment by rstoenescu** [comment]
Fix will be available in beta.14.

**Comment by Peter-Krebs** [comment]
Thanks!
