### ISSUE TITLE
[IOS8, IOS9, Android4.4] Tabs component, layout have scroll bar

### ISSUE THREAD

**Issue by bboywulong** [quasarframework/quasar#373]
![ccf6ff86-2aaa-4ce3-af90-cc530bb147b5](https://cloud.githubusercontent.com/assets/17426924/22634261/0074fda0-ec63-11e6-8ba1-b95fec3c1c83.png)
![17a56d4e-2a07-44db-a7fe-3f8cdcf6a1f0](https://cloud.githubusercontent.com/assets/17426924/22634272/188dd0ec-ec63-11e6-8f2a-403e4d14e9f0.png)

**Comment by rstoenescu** [comment]
Hi,

Can you provide more details? What phone are you using, what Android version. Is it a bug in Quasar Play app? Are you using Quasar Play app or are viewing the documentation examples in a phone browser?
Are you using a layout of your own (in which case please copy-paste it here pls).

Thanks!

**Comment by bboywulong** [comment]
can you tell me IOS and android Minimum support version

**Comment by bboywulong** [comment]
Test on IOS 9.0 and android 5.0 can use, low version can't use

**Comment by rstoenescu** [comment]
Android 4.4 and iOS 6 (lower versions have very low market share anyway).
Can you tell me your phone's Android version is?

**Comment by bboywulong** [comment]
I use android 4.4 image and IOS 8.4 image
<img width="979" alt="qq20170207-175532 2x" src="https://cloud.githubusercontent.com/assets/17426924/22686434/1a98de48-ed5f-11e6-8ba0-e73cd575046b.png">
<img width="355" alt="qq20170207-175704 2x" src="https://cloud.githubusercontent.com/assets/17426924/22686452/2be38c8e-ed5f-11e6-8fab-7e3d9e75c9b4.png">
<img width="376" alt="qq20170207-175822 2x" src="https://cloud.githubusercontent.com/assets/17426924/22686477/3c4de204-ed5f-11e6-9165-4e4a36362745.png">
this page layout can move, IOS 8.4 and 9.3 have the same problem

**Comment by bboywulong** [comment]
I find with .layout class

have -webkit-flex error
<img width="1349" alt="err" src="https://cloud.githubusercontent.com/assets/17426924/23197541/f76f3f22-f8fb-11e6-9a9b-a6135b2884e7.png">

have -webkit-box correct
<img width="1350" alt="right" src="https://cloud.githubusercontent.com/assets/17426924/23197553/099e8d4c-f8fc-11e6-9957-7370ad80fe8c.png">

**Comment by rstoenescu** [comment]
Fixed the layout "moving" today. Available in edge and future v0.13.2

**Comment by rstoenescu** [comment]
Those mentioned earlier are not errors. They are part of first flexbox CSS version.

**Comment by rstoenescu** [comment]
Can you test with the edge version to see if there is anything else to fix, pls?

**Comment by bboywulong** [comment]
ok,I try

**Comment by rstoenescu** [comment]
@bboywulong is everything ok? can we close this?

**Comment by rstoenescu** [comment]
Please reopen if you still experience the layout issue. Seems fixed to me in edge version.

**Comment by bboywulong** [comment]
I test android various versions is ok, but on IOS8 and IOS9
if ```.layout``` set ```display: flex``` or ```display: -webkit-flex``` still have the layout issue.
```.layout``` set ```display: -webkit-box``` is ok

**Comment by rstoenescu** [comment]
@bboywulong like I said, the 3 CSS lines are needed to cover most browser versions. Don't worry if one of them has the "attention" mark on it. That means that the property is ignored. The 3 lines of CSS are standard and must always go together for the cross-browser support to be available.

What I am asking is: do you experience the same issue of layout margins getting partially hidden? From my tests this is not the case anymore. Want your confirmation too so then I can release v0.13.2 with this and other fixes.

**Comment by bboywulong** [comment]
Oh, There are no other questions yet
