### ISSUE TITLE
[v1][RTL] Incorrect QSpinner animation

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#3736]
### Software version

Quasar: beta-13
@quasar/app (v1+ only): beta-13

### JsFiddle
This problem does not affect UMD builds.

#### RTL in dev mode:
![rtl-dev](https://user-images.githubusercontent.com/12370595/55214906-a2c32680-5215-11e9-8183-e721c342dae8.gif)

#### RTL after build:
![rtl-buil gif](https://user-images.githubusercontent.com/12370595/55214925-b1114280-5215-11e9-842a-7388e8a77afb.gif)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this!
Fix will be available with `@quasar/app` beta.15 and quasar beta.14
