### ISSUE TITLE
Select and search does not have the same height?

### ISSUE THREAD

**Issue by conx13** [quasarframework/quasar#374]
(and font-size) Or this is not issue?
![screen shot 2017-02-06 at 10 49 25](https://cloud.githubusercontent.com/assets/2715581/22640262/8503f0ca-ec5a-11e6-95d5-c58eb09e2045.png)

**Comment by rstoenescu** [comment]
Hmm, will fix this. They should be of same height although this slipped out.

**Comment by hatavan83** [comment]
@conx13 How to add search icon in left of input component :)

**Comment by conx13** [comment]
This is not just input component, but [search component](http://quasar-framework.org/components/search.html) ;-)

**Comment by rstoenescu** [comment]
Please wait for the new Quasar version. This version enhances forms a lot. Your issue will be fixed in it. Simply go ahead and continue your work on your app and later this week you'll be able to upgrade to the new Quasar version and everything will work as expected.

**Comment by rstoenescu** [comment]
Fixed in future v0.14
