### ISSUE TITLE
[v1 request] QInput should allow using parent font size

### ISSUE THREAD

**Issue by AllenPan** [quasarframework/quasar#3747]
I want my page base font size to be 16px.  so I change the body font-size to 16px. But QInput has the .q-field__native class hard coding font-size 14px, which prevent body font-size  taking effect.  

Global packages
  NPM - 6.8.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.3
  cordova - 8.1.2 (cordova-lib@8.1.1)

Important local packages
  quasar - 1.0.0-beta.13 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.14 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js

**Comment by rstoenescu** [comment]
Forgot to close this. It's definitely available in current latest beta.

`<q-input style="font-size: 1em" ...` or add a CSS class which applies font-size then use it on QInput. Works for QInput/QField/...
