### ISSUE TITLE
[Documentation] Add "stylus variables" to each component page

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3749]
## What
Add per component page in the documentation, underneath the Component API (or inside the API as a new tab) **information on if the component has Stylus Variables which can be changed**.

## Motivation
I often find myself targeting inner component classes to change CSS of Quasar components. However this is **bad practice**. To avoid that a developer _should_ every time check if there are stylus variables set for the component or not.

While having all stylus variables in one long list might be handy as well, ... 
having each component show information on which stylus variables can be edited, right there on the component page seems like a VERY GOOD IMPROVEMENT to the docs!

## Suggestion

<img width="799" alt="Screenshot 2019-03-30 14 47 56" src="https://user-images.githubusercontent.com/3253920/55272110-d75cde00-52fa-11e9-9fb0-0312acc3abf4.png">

**Comment by rstoenescu** [comment]
Will consider this in the future.
