### ISSUE TITLE
[Request] Data Table select event

### ISSUE THREAD

**Issue by robbertvc** [quasarframework/quasar#375]
Is it possible to create a `select `event on the data table?

Right now the selected data is only available in the scoped selection slot. This means it is not possible to interact with the selected data outside of the table component. (It is also possible to directly reference the table and the selected data using `$refs.[tableReference].selectedRows` but $refs is not watchable in VueJS. Therefore this method cannot be used to continuously update data outside of the table based on the selected table data.) 

I hope I made the reason for the existence of such a `select` event clear enough.

BTW, many thanks for this awesome framework.

**Comment by rstoenescu** [comment]
Yes, will do! Thanks for suggesting this.

**Comment by rstoenescu** [comment]
Added `@selection` event which takes two parameters: number of rows selected and the actual rows that have been selected.

Available in future v0.14.

**Comment by jayudhandha** [comment]
@rstoenescu Is there any way to modify the "1 selected row." message that is coming when we click on any single checkbox.

I want to change from "1 selected row." to "1 row selected."

Thanks!

**Comment by jayudhandha** [comment]
@rstoenescu For the moment, I am trying to manually change this using above mentioned code.

Am I doing something wrong in that?

**Comment by jayudhandha** [comment]
@rstoenescu I am not sure this is existing issue or mine.

But the count of Rows per page in getting overlapped on the drop down.

Please find attached screenshot.

Thanks!
![countoverlap](https://user-images.githubusercontent.com/5781316/39287993-ddbd2334-4943-11e8-9dc8-c89f0e44059a.PNG)

**Comment by Luciden** [comment]
Can you update the documentation? I'm attempting to implement this with the latest version of Quasar. Using Typescript 3

`<q-table
                    selection="single"
                    :selected.sync="selectedItems"
                    :data="tableData"
                    :columns="columns"
                    row-key="OrgID"
                    @selection="selection"
                    />`

`public selection (number: number, rows: number) {
      console.log(`selected ${number}: ${rows}`)
    }`

**Comment by smolinari** [comment]
Ok. The docs do need to be updated with this event, but the best docs can also be had by [reading the source code](https://medium.com/quasar-framework/wip-look-at-the-source-code-please-1b905ea4906).  

From `QTable.js` or rather from the `table-row-selection` mixin.
```js
  methods: {
    isRowSelected (key) {
      return this.selectedKeys[key] === true
    },
    clearSelection () {
      this.$emit('update:selected', [])
    },
    __updateSelection (keys, rows, adding) {
      if (this.singleSelection) {
        this.$emit('update:selected', adding ? rows : [])
      }
      else {
        this.$emit('update:selected', adding
          ? this.selected.concat(rows)
          : this.selected.filter(row => !keys.includes(row[this.rowKey]))
        )
      }
    }
```
I think with that, you can see your mistake or rather where Razvan's comment above is just a bit misleading. 😄 

Scott
