### ISSUE TITLE
Feature request: QLayout limit width on large screens

### ISSUE THREAD

**Issue by boustanihani** [quasarframework/quasar#3750]
Please allow an option to limit the width of QLayout on large screens.

It does not always look good if QLayout expands to full width, sometimes it looks much better if the whole site including headers, footers & drawers stay centered in the middle on large screens, like only take 60% or 70% of the screen and the sides remain empty...

**Comment by rstoenescu** [comment]
Learn about "container" prop.
Then check out: https://codepen.io/rstoenescu/pen/zXOVPo?&editable=true&editors=101

**Comment by boustanihani** [comment]
Thank you for the provided example, but don't you think that something like `v-container` `fluid` (like in vuetify) would be much simpler? ( https://vuetifyjs.com/en/framework/grid )

I am comparing frameworks and features and that is why I suggested this feature...

**Comment by rstoenescu** [comment]
QLayout does a lot more than just a simple v-container fluid... All those features cannot be accommodated into such a simple component. Play with the QLayout here (especially the "Configure Layout Pats"): https://v1.quasar-framework.org/layout-builder

Also, not sure if it's relevant to this issue, but posting it anyway: the grid system in Quasar https://v1.quasar-framework.org/layout/grid/introduction-to-flexbox

**Comment by rulrok** [comment]
Hi @rstoenescu 

I'd like to ressurge with this discussion.
Just like bootstrap does, it is very important and helpful to have a 'containers' with a `max-width` for content at given screen widths.

[See the responsible containers of bootstrap 4](https://getbootstrap.com/docs/4.4/layout/overview/#containers)

Quasar grid system it good enough but it _lacks_ the container piece to hold it together within a bounded area :)

The container doesn't need to be a component; it's just css classes really setting a `max-width`.

**Comment by Manieck** [comment]
Hi

Recently, I had the same problem that I didn't want the application to be the full width of the screen.
I searched the web and no found solution, but came across this thread.

I did a little workaround by adding a class page-wrapper 
```
.page-wrapper {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
```
to q-page-container
```
<q-page-container class="page-wrapper">
    <q-page class="bg-green-3">
        Page Content
    </q-page>
  </q-page-container>
```

...and a few lines of JS

 ```
setDrawersPosition () {
      this.setDrawerPosition('left');
      this.setDrawerPosition('right'); // if you add
    },
    setDrawerPosition (site) {
      const pageContainer = this.$el.querySelector('.q-page-container');
      if (pageContainer) {
        const drawer = this.$el.querySelector(`.q-drawer--${site}`);
        if (drawer) {
          const style = getComputedStyle(pageContainer);
          drawer.style[site] = style[`margin-${site}`];
        }
      }
    }
```

It's all here
https://codepen.io/manieck_pl/pen/BaQgGdz

Regards

**Comment by rbutus** [comment]
I solved this issue a different way:
```
<template>
  <div class=bg-primary>
    <q-layout
      view="hHh lpR fFf"
      container
      class="layout-container">
    </q-layout>
  </div>
</template>

<style>
.layout-container {
  height: 100vh;
  max-width: 1200px;
  margin: auto;
 }
 </style>
 ```

**Comment by rhues** [comment]
The excellent approach used by @rbutus is documented here: https://quasar.dev/layout/layout#containerized-qlayout
