### ISSUE TITLE
Autocomplete on edit page

### ISSUE THREAD

**Issue by sotnaspina** [quasarframework/quasar#3755]
Hello!

Using the Autocomplete (q-input + q-autocomplete) component, when opening the edit page, what is the best way to set the item that has already been registered.

Note: On the edit page the field with autocomplete displays the "Id" instead of the "Name".

Quasar v. 0.17.20
Thankful!

**Comment by rstoenescu** [comment]
Hi,

Please join our Discord server or use the forum for questions. Github is reserved only for bugs.
Thanks!
