### ISSUE TITLE
[V1] incorrect rendering of style-fn offset

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3757]
# Problems with q-layout & headers that change when changing routes

### reactivity problem
Both the two features below:
- QPage: `:style-fn="myTweak"`
- QPageContainer: `padding-top` and `padding-bottom`  which is added to that element's style

Are both **not reactive!** And the biggest problem is:
- The size of the header + footer are calculated **BEFORE** Vue.nextTick...

The following layout is a **big no-no**:
```html
<template>
  <q-layout view="lHH lpr lFf">
    <q-header>
      <header-one v-if="$route.name === 'a'" />
      <header-two v-if="$route.name === 'b'" />
    </q-header>
   ...
```
A setup as above will consistently break your page padding-top, hiding elements underneath.

### Other problem
Also related, but a different problem:
`100vh` in iPhone X in cordova logs `817.59375px`... While it should be `812px`.

But using
```js
import { Screen } from 'quasar'
Screen.height // returns 812 correctly
```

In order to avoid many problems with Cordova I would avoid to use the term `vh` entirely.

**Comment by mesqueeb** [comment]
## Work-around / Solution to all above problems

Every time you use `q-page`, be sure to do it like so:
#### 1. Reset incorrect padding on `.q-page-container`
```stylus
// in app.styl
.q-page-container
  padding-top 0 !important
  padding-bottom 0 !important
```
#### 2. Use a style tweak on all Q-Pages
```html
<q-page :style-fn="myTweak">...</q-page>
```
#### 3. Define style tweak
Because we reset the padding on `.q-page-container` we'll add padding to `.p-page` instead.
→ And this time with the correct one!
```js
function myTweak (offset) {
      // offset is incorrect in many occasions! DO NOT USE IT
      const heightHeader = Number(document.querySelector('.q-header').clientHeight)
      const heightFooter = Number(document.querySelector('.q-footer').clientHeight)
      const correctOffset = heightHeader + heightFooter
      const paddingTop = heightHeader + 'px'
      const paddingBottom = heightFooter + 'px'
      const minHeight = (Screen.height - correctOffset) + 'px'
      return { minHeight, paddingTop, paddingBottom }
}
```

**Comment by mesqueeb** [comment]
There is still a bug with Cordova, whereas there's the possibility that the immediate watcher is executed before `deviceReady` and again, the header is not calculated properly.

You can fix this by adding:
```js
  mounted () {
    if (!window.cordova) return
    document.addEventListener('deviceready', this.setPageTweaks, false)
  },
```

I have updated the post above

**Comment by rstoenescu** [comment]
I think this can be put to rest starting with the final 1.0.0 build (to be released tomorrow). The layout system no longer uses vh and vw units.
