### ISSUE TITLE
[Request] Drag and droppable Lists and Tree

### ISSUE THREAD

**Issue by micheleangioni** [quasarframework/quasar#376]
Hi,
first of all my congrats for the awesome work, I'm already using Quasar in a couple of new projects.

An interesting feature that is missing is be the possibility to have drag and drop in some of the existing components, such as the lists and the tree.
More than once I had the necessity to add something like [this](https://angular-ui-tree.github.io/angular-ui-tree/#/basic-example) because that's (probably) the easiest way to have editable ordered lists.

Do you think that could be feasible? :)

**Comment by rstoenescu** [comment]
Hi,

There are a bunch of Vue components that you can use for drag'n'drop. Please refer to https://github.com/quasarframework/quasar/issues/99

If you find a scenario where existing drag'n'drop Vue components don't fulfill a need, please report back. Thanks!

**Comment by micheleangioni** [comment]
I didn't know about Dragula and Vue-Dragula, it seems really interesting. I'll definitely try it!
Maybe you could add a "Drag and Drop" section under "Development" in the documentation that recommends Vue-Dragula, or even provide a Quasar Component wrapper to Dragula, not relying on the existing Vue-Dragula.

Thanks for your quick answer and keep up the good work!
