### ISSUE TITLE
[V1] Vue file Autocomplete not working

### ISSUE THREAD

**Issue by stefnotch** [quasarframework/quasar#3763]
### Software version

Operating System - Windows_NT(10.0.17763) - win32/x64
NodeJs - 10.15.1

Global packages
  NPM - 6.9.0
  yarn - Not installed
  @quasar/cli - 1.0.0-beta.3
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.13 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.14 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - 4.0.5 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Any other software related to your bug:
**Visual Studio Code 1.32.3**

### What did you get as the error?
The basic Vue Intellisense in VSCode does not work. With a simple Vue project (created with the Vue CLI), the Intellisense does work.

Related: [Quasar Forum Post](https://forum.quasar-framework.org/topic/2935/should-i-not-have-basic-vue-intellisense-in-vue-files-i-have-it-vue-cli-projects-but-not-in-quasar-cli)

### What were you expecting?
![image](https://user-images.githubusercontent.com/10220080/55291800-72c97e00-53e3-11e9-9eff-1e75b8ed94ed.png)

**This seems to be caused by the package.json not having `vue` as a dependency!**

### What steps did you take, to get the error?
1) I created a new Quasar project `quasar create <folder_name> -b dev`
2) I opened it with Visual Studio Code (Vetur and ESLint extensions installed)
3) I created a basic Vue Single File Component `quasar new c Index`

4) The standard Vue IntelliSense does not work
![image](https://user-images.githubusercontent.com/10220080/55291763-f9319000-53e2-11e9-8ded-0274e7c460f9.png)
![image](https://user-images.githubusercontent.com/10220080/55291770-11091400-53e3-11e9-8b9a-af552f21a3d4.png)

**Comment by rstoenescu** [comment]
Reference https://github.com/vuejs/vetur/pull/1273

**Comment by pdanpdan** [comment]
This should work now. Please reopen if there are still problems.
