### ISSUE TITLE
[V1] QInput with template q-date and v-close-popup :  closing template when click add/remove months/years

### ISSUE THREAD

**Issue by oliviermorpa** [quasarframework/quasar#3767]
### Software version

Quasar:
@quasar/app (v1+ only): v1.0.0.-beta.15
OS: windows
Node: 10.15.2
NPM: 6.9.0
Browsers: all
iOS:
Android:
Any other software related to your bug:

### JsFiddle
https://codepen.io/anon/pen/NmWeRP?&editable=true&editors=101

### What did you get as the error?
using a q-input with q-date as popup and want to autoclose the popup when the user click on a date.
no error. the popup poxy is closing when click button to add/remore months/year because v-close-popup is set

### What were you expecting?
dont close popup when click buttons. only when click a date/panel

**Comment by pdanpdan** [comment]
https://codepen.io/anon/pen/jROoya?editors=1010

**Comment by oliviermorpa** [comment]
great. its working but should i close this issue or need to change the behavior ?

**Comment by pdanpdan** [comment]
You can close the issue - auto-close is designed to close on any click, it cannot be customized.
