### ISSUE TITLE
[V1] QBtnDropDown - dropdown does not appear with Enter key

### ISSUE THREAD

**Issue by mam-ijinus** [quasarframework/quasar#3768]
Quasar: 1.0.0-Beta14

https://codepen.io/pen/?&editable=true&editors=101

### steps
1. Select button with tabulation
2. Press Enter
3. Dropdown appear

### What did you get as the error?
First element is not selected and I can't select on with keyboard up and down key

### What were you expecting?
First element is selected and I can select on with keyboard up and down key

**Comment by rstoenescu** [comment]
Seems fine to me. Just tested.
Hit "Save" on your Codepen before you post it. The link above contains an empty pen.

**Comment by mam-ijinus** [comment]
Arf...: in code pen (https://codepen.io/anon/pen/oOgvJj)  we don't have the same behavoir that into https://v1.quasar-framework.org/vue-components/button-dropdown

In code pen the dropdown does appears... And it does in the documentation.

BUT there is another issue: the first element of the dropdows is not selected at open, so we can't select item with keyboard. The same behavior appear with q-menu in a q-btn.

**Comment by mam-ijinus** [comment]
the example of a q-menu into a q-btn:
https://codepen.io/anon/pen/GLgKGN

**Comment by mam-ijinus** [comment]
I update the bug description.

**Comment by rstoenescu** [comment]
Fix will be available in beta.16.
Opening a menu (click / enter / space key) will focus the QMenu's wrapper, allowing you to tab through the QMenu content.
