### ISSUE TITLE
LocalStorage.get.item() returns a function?

### ISSUE THREAD

**Issue by fiee** [quasarframework/quasar#377]
import { LocalStorage } from 'quasar'
    let item = LocalStorage.get.item('somekey')
    console.log(item)

logs

    function boundFn(a) {
        var l = arguments.length;
        return l
          ? l > 1
            ? fn.apply(ctx, arguments)
            : fn.call(ctx, a)
          : fn.call(ctx)
      }

Something’s wrong – might still be at my side.

**Comment by rstoenescu** [comment]
Hi,

It's definitely on your end. This feature has been tested over and over again. 
Also, there's no boundFn() in whole Quasar code. Can you check your app code and see what exactly are you setting as value in the first place? You might have stored a function which got stringified at some point. Would be an idea to remove the key from LocalStorage and do another spin of tests.

Please reopen if Quasar is somewhere at fault. Thanks!

**Comment by fiee** [comment]
Of course you’re right. The function must have been a leftover from first tests. Don’t know where it comes from, it’s not from my code. Sorry for the noise and thank you for your work!

**Comment by rstoenescu** [comment]
No problem. Glad it got solved!
