### ISSUE TITLE
[V1] QFab + fontawesome = bad icon position

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#3772]
### Software version

Quasar:
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### JsFiddle

https://codepen.io/daedalusdev/pen/OGPpVd

### What did you get as the error?
The icon is too hight

**Comment by rstoenescu** [comment]
Thanks for reporting this regression issue.
Fix will be available in beta.15.
