### ISSUE TITLE
[v1] quasar mode add cordova "CordovaError: Error validating project name. Project name must not begin with a number"

### ISSUE THREAD

**Issue by MichaelJCole** [quasarframework/quasar#3774]
I followed the instructions here:

https://v1.quasar-framework.org/quasar-cli/developing-mobile-apps/preparation

`quasar mode add cordova` ran fine, but set productName to start with a number.

`cordova platform add android` did not like the productName starting with a number and failed:

```
Adding cordova-plugin-whitelist to package.json
CordovaError: Error validating project name. Project name must not begin with a number
```
It's not a big deal, but `quasar`shouldn't configure the cordova project with invalid settings or it's not really helping.

**Comment by MichaelJCole** [comment]
https://stackoverflow.com/questions/53192000/cordovaerror-project-name-must-not-begin-with-a-number

**Comment by rstoenescu** [comment]
Will be available in quasar/app beta.20.
Thanks for pointing this out.
