### ISSUE TITLE
[V1] Request: allow heading to work with body prop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3777]
## Request:
Make timeline-entry `heading` also available as a "prop" of a regular entry.

## Reason:
We cannot do a single `v-for` on the timeline-entry if we have some entries that require a heading in between two entries.

## Reason explained:
The current implementation of a QTimeline requires us to order our slot elements like so:
- heading
- entry times 𝑥
- heading
- entry times 𝑥
etc...

However, in most applications we probably have our data inside a big list like so:
```js
const timelineEntries = [
  {title, subtitle, date, body},
  {title, subtitle, date, body},
  {title, subtitle, date, body},
  {title, subtitle, date, body},
]
```
With the current implementation of the timeline **we need to provide data like so:**
```js
const timelineEntries = [
  {heading, body},  // heading: true, body: 'March'
  {title, subtitle, date, body},
  {title, subtitle, date, body},
  {heading, body},  // heading: true, body: 'April'
  {title, subtitle, date, body},
  {title, subtitle, date, body},
]
```

**But it's much easier if we can provide data like so:**
```js
const timelineEntries = [
  {title, subtitle, date, body, heading}, // heading: 'March'
  {title, subtitle, date, body},
  {title, subtitle, date, body, heading}, // heading: 'April'
  {title, subtitle, date, body},
]
```
If we can add the heading as a `string` to a regular entry we hardly need to shuffle around our data.
Also, **setting up the actual template becomes much easier**:
```js
<q-timeline >
      <q-timeline-entry
        v-for="entry in timelineEntries"
        :heading="entry.heading"
        :title="entry.title"
        :subtitle="entry.subtitle"
      >
        <div>{{ entry.body }}</div>
      </q-timeline-entry>
</q-timeline >
```

Now we have to write so much more code to split our entry array into multiple smaller arrays, re-arrange them per heading, have a double nested v-for with the timelines, etc.etc.

All examples in the docs have the data hard coded. So it leaves me scratching the best way to set up the data...

**Comment by rstoenescu** [comment]
Enhancements will be available in beta.15.
New prop ("body"), new slots: "title", "subtitle"
