### ISSUE TITLE
[v1] Inconsistent focus change when working with QField/QMenu/QDialog

### ISSUE THREAD

**Issue by euphemism** [quasarframework/quasar#3778]
I would like to preface this with acknowledging that my problem could be caused entirely by my inexperience with Vue/Quasar and not an actual issue with this framework.

### Software version
Quasar: v1 beta 14
@quasar/app - 1.0.0-beta.15
Operating System - Windows_NT(10.0.18343) - win32/x64
NodeJs - 11.11.0
 NPM - 6.7.0
Browsers: Firefox 66.0.2

### JsFiddle
https://codepen.io/euphemism/pen/jREjvJ

### What did you get as the error?
Focus is being applied to incorrect elements, at least from an intuitive standpoint.

### What were you expecting?
I was expecting focus to jump to the input field of the QDialog upon spawning it.

### What steps did you take, to get the error?
One issue:
1. Click on the component
2. Click on 'Other'
3. Observe menu disappears, focus is applied to QField containing component and not to the input field of spawned dialog

Another:
1. Click on the component
2. Tab to the 'Other' option
3. Press Enter
4. Observe menu does not close, but focus is correctly applied to input field of spawned dialog

**Comment by pdanpdan** [comment]
What happens is the field gets the focus back when the menu hides.
You can:
1) not use `auto-close` and close from inside `addItem` (https://codepen.io/anon/pen/wZaBjV)
2) delay the dialog opening
3) use no-refocus on QMenu

**Comment by euphemism** [comment]
Thank you, the changes you made in your codepen seem to have the desired effect. Sorry for the bother.
