### ISSUE TITLE
[v1 request] Include field mask in locale

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#3779]
Actually, the `date` mask is `####/##/##` and is a static variable.

I suggest to include this format in locale files.

Thanks for your great job.

**Comment by nothingismagick** [comment]
This should be landing in v1.0.0-beta.24
https://github.com/quasarframework/quasar/commit/2213c8c9572766f17aae4bdc026f6af498bad8ff

**Comment by irongomme** [comment]
How is it supposed to work @nothingismagick  ?

**Comment by rstoenescu** [comment]
The QInput named masks are there for convenience. Should you want another format you can use your own. Also watch for future Quasar 1.0.0-beta.24 as it will improve QInput mask. Will be documented.

Sidenote: In future Quasar 1.0.0-beta.24 the QDate and QTime will also receive `mask` and even `locale` props... major improvements and way easier to work with them. Stay tuned for the docs.
