### ISSUE TITLE
Wrong $q.bottomSheet, $q.dialog, $q.appVisible and $q.notify typescript definitions

### ISSUE THREAD

**Issue by Abuntxa** [quasarframework/quasar#3780]
### V1.0.0-beta.14

Operating System - Windows_NT(10.0.16299) - win32/x64
NodeJs - 10.15.2

#### Global packages
  NPM - 6.4.1
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

#### Important local packages
  quasar - 1.0.0-beta.14 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.15 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support
loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

#### Quasar App Extensions
  @quasar/quasar-app-extension-typescript - 1.0.0-alpha.13 -- A Quasar CLI Extension

### JsFiddle
It's a typescript compilation problem. No execution problems so far.

### What did you get as the error?
> TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'BottomSheet' has no compatible call signatures.

The problematic code is the following one
```ts
this.$q.bottomSheet({
      title: 'myTitle',
      message: 'myMessage',
      grid: false,
      actions: myActionsArray
    })
```
The typescript definition in  '.\node_modules\quasar\dist\types\index.d.ts' says that bottomSheet is of type BottomSheet:
```ts
export const QVueGlobals: QVueGlobals
export interface QVueGlobals {
    addressbarColor: AddressbarColor
    fullscreen: AppFullscreen
    appVisible: AppVisibility
    bottomSheet: BottomSheet
    cookies: Cookies
    dialog: Dialog
    loading: Loading
    loadingBar: LoadingBar
    localStorage: LocalStorage
    notify: Notify
    platform: Platform
    screen: Screen
    sessionStorage: SessionStorage
}
```
Where BottomSheet is defined as: 
```ts
export const BottomSheet: BottomSheet
export interface BottomSheet {
    create(opts : {
        className? : String | [] | any
        style? : String | [] | any
        title? : String
        message? : String
        actions? : []
        grid? : Boolean
        width? : String
        color? : String
        seamless? : Boolean
        persistent? : Boolean }): {
        onOk? : Function
        onCancel? : Function
        onDismiss? : Function
        hide? : Function }
}
```
While the real implementation of the bottomSheet is a function:

[BottomSheet.js](https://github.com/quasarframework/quasar/blob/dev/quasar/src/plugins/BottomSheet.js)
```js
import BottomSheet from '../components/bottom-sheet/BottomSheet.js'
import globalDialog from '../utils/global-dialog.js'

export default {
  install ({ $q }) {
    this.create = $q.bottomSheet = globalDialog(BottomSheet)
  }
}
```

### What were you expecting?
Correct typescript compilation and appropriate intellisense help

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in beta.15.
