### ISSUE TITLE
Wrong argument in typescript definition for the LocalStorage plugin set method

### ISSUE THREAD

**Issue by Abuntxa** [quasarframework/quasar#3781]
### v1.0.0-beta.14
Operating System - Windows_NT(10.0.16299) - win32/x64
NodeJs - 10.15.2

#### Global packages
  NPM - 6.4.1
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

#### Important local packages
  quasar - 1.0.0-beta.14 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.15 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support
loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

#### Quasar App Extensions
  @quasar/quasar-app-extension-typescript - 1.0.0-alpha.13 -- A Quasar CLI Extension

### JsFiddle
There aren't any execution errors so far. Only typescript compilation errors.

### What did you get as the error?
> TS2345: Argument of type 'IDashboardElement[]' is not assignable to parameter of type 'String'.  Type 'IDashboardElement[]' is missing the following properties from type 'String': charAt, charCodeAt, localeCompare, match, and 32 more.

The problematic code (just in compilation) is the following one:
```ts
this.$q.localStorage.set('dashboardDefinition', this.dashboardDefinition)
```
[In the documentation](https://v1.quasar-framework.org/quasar-plugins/web-storage) says that the plugin is able to store back and forth with the original type.

The current plugin definition is as follows ('.\node_modules\quasar\dist\types\index.d.ts')
```ts
export const LocalStorage: LocalStorage
export interface LocalStorage {
    has(key : String): Boolean
    getLength(): Number
    getItem(key : String): any
    getIndex(index : Number): any
    getAll(): any
    set(key : String, value : String): void
    remove(key : String): void
    clear(): void
    isEmpty(): Boolean
}
```
The set method only takes strings as arguments.

**Comment by rstoenescu** [comment]
Fix will be available in beta.15.
