### ISSUE TITLE
[V1] QInput - prefix and input no longer aligned when label is set.

### ISSUE THREAD

**Issue by BritishHumor** [quasarframework/quasar#3785]
Quasar: 1.0.0-Beta14

https://codepen.io/LiamHolmes1508/pen/wZaEGQ

### Description
As title says, when you create a QInput with just a prefix, the input aligns correctly with the prefix, however when you added a label the input is now slightly higher than the prefix or the prefix is slightly lower.

**Comment by pdanpdan** [comment]
I'll attach a variant - it's easier to check: https://codepen.io/anon/pen/ROPvZX

**Comment by rstoenescu** [comment]
Fix will be available in beta.16.
