### ISSUE TITLE
[v1] 1.0.0-beta.14 TypeScript QForm type error

### ISSUE THREAD

**Issue by wsmith-nwfsc** [quasarframework/quasar#3791]
### 1.0.0-beta.14
Running Quasar via the Vue CLI Plugin, using Typescript (in a lerna monorepo.)

OS: Win10
Quasar:
"quasar": "1.0.0-beta.14",
...
Node :v10.15.3
NPM: 6.5.0
Browsers: Chrome
Any other software related to your bug:
"vue-cli-plugin-quasar": "^1.0.0-beta.0",

### What did you get as the error?
```
node_modules/quasar/dist/types/index.d.ts
[2m751:17[22m Generic type 'Promise<T>' requires 1 type argument(s).
    749 | export interface QForm extends Vue {
    750 |     autofocus? : Boolean
  > 751 |     validate(): Promise
        |                 ^
    752 |     resetValidation(): void
    753 |     focus(): void
    754 | }
```
### What were you expecting?
All good up to beta 13. Rolling back to 1.0.0-beta.13 fixes the issue.

### What steps did you take, to get the error?
yarn install quasar@1.0.0-beta.14

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. This has already been fixed in future beta.15.
