### ISSUE TITLE
[V1] QInput - outlined : doesn't show errormessage on error

### ISSUE THREAD

**Issue by SamuelLeclerc33** [quasarframework/quasar#3792]
### Software version

Quasar: v1 UMD

Browsers: chrome

Any other software related to your bug:

### JsFiddle

you can see it here : https://codepen.io/anon/pen/jRbMJE?&editable=true&editors=101

### What did you get as the error?
I got this while exploring around with outlined inputs

### What were you expecting?
to see the error appear under the text ? 

### What steps did you take, to get the error?
Check the codepen.
Take a outlined qinput
set error at true
add an error message

**Comment by pdanpdan** [comment]
Don't forget to add `bottom-slots` prop if you use external validation.
