### ISSUE TITLE
[v1] text is clipped in pagination input field

### ISSUE THREAD

**Issue by Teodorko** [quasarframework/quasar#3794]
quasar info

Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.15.1

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.2
  cordova - 8.1.2 (cordova-lib@8.1.1)

![image](https://user-images.githubusercontent.com/20430124/55478383-451f4780-5624-11e9-8afb-ffc117dc9257.png)

Hello!

Text is clipped in pagination input field. In the table in the pagination slot.
[https://codepen.io/anon/pen/mgezea](https://codepen.io/anon/pen/mgezea)

**Comment by rstoenescu** [comment]
Fix will be available in beta.16.
