### ISSUE TITLE
[v1] QBtn click event not called after it being enabled

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#3795]
Quasar Version: 1.0.0-beta.15

When in _QDialog_, the following button's click handler is not called (assume `text` gets set with a value):
`<q-btn v-close-popup @click="onSetText" :disable="!text">Click</q-btn>`

When removing the `:disable` directive, the button works as expected:
`<q-btn v-close-popup @click="onSetText">Click</q-btn>`

Here is a Codepen that demonstrates the issue:
https://codepen.io/tomers-the-encoder/pen/bJVKqN?editors=1011

In case the button is placed outside of _QDialog_ (no `v-close-popup` directive), it works as expected:
https://codepen.io/tomers-the-encoder/pen/NmGEww?editors=1011

**Comment by smolinari** [comment]
I believe the use of v-close-popup is causing the issue. If you remove it and just use the method to close the dialog, your expected result happens. 

https://codepen.io/smolinari/pen/gyaqyp

Scott

**Comment by lucasfernog** [comment]
Also, you could use @click.native as a workaround... I couldn't find the issue in code

**Comment by smolinari** [comment]
@lucasfernog - I was thinking of suggesting the same thing, however, QBtn offers the @click event through propagation.

From the docs: "All native events are being propagated (you don't need the '.native' modifier)" 

Scott

**Comment by tomers** [comment]
Thanks for the workaround suggestions, but isn't this still a bug?

**Comment by rstoenescu** [comment]
Fix will be available in beta.16.
