### ISSUE TITLE
[v1] Remove legacy build flag for Cordova iOS builds

### ISSUE THREAD

**Issue by andreipopovici** [quasarframework/quasar#3796]
Where: https://github.com/quasarframework/quasar/blob/95d755720cb4505da4ee489c53459795beb93e40/app/lib/cordova/index.js#L40

Since [cordova-ios@5.0.0 has been released](https://cordova.apache.org/announcements/2019/02/09/cordova-ios-release-5.0.0.html), which supports the new build system, the CLI can stop enforcing this flag.

As per other threads, I tried including a `build.json` file in `src-cordova/` with the following contents:

```json
{
  "ios": {
    "debug": {
      "buildFlag": [
        "-UseModernBuildSystem=1"
      ]
    },
    "release": {
      "buildFlag": [
        "-UseModernBuildSystem=1"
      ]
    }
  }
}
```
in an attempt to override the flag set by the CLI.

However, the `build.json` file is not picked up:

```
app:cordova-conf Updated Cordova config.xml +19s
 app:spawn Running "cordova run ios --buildFlag=-UseModernBuildSystem=0" +0ms

Reading build config file:
Building for iPhone X Simulator
Building project: <my project path>.xcworkspace
	Configuration: Debug
	Platform: emulator
Adding xcodebuildArg: -UseModernBuildSystem=0
```

Is there another way to pass arguments to the `quasar dev -m cordova -T ios` CLI command, to override the legacy build flag?

[update] I see there was a conversation with @rstoenescu [in this commit](https://github.com/quasarframework/quasar/commit/982f60b3242a264a77b69e4efd3abbba656bb631), but I'm still unclear whether there's a way to override the flag set by the CLI when using `quasar dev`. Simply having the `build.json` file present should have been enough. I did not manually modify the XCode project to change build systems.

**Comment by rstoenescu** [comment]
Added quasar.conf.js > cordova > noIosLegacyBuildFlag (set it to "true" to disable the flag).
Will be available shortly in quasar/app beta.19

**Comment by mesqueeb** [comment]
My opinion would be `UseModernBuildSystem` should be `true` by default and only be disabled if a user manually adds a `build.json` file which disables it.

### Motivation
Cordova
- has `-UseModernBuildSystem=1` by default
- and `-UseModernBuildSystem=0` has to be enforced

Quasar
- has the opposite from the above, which just feels counter intuitive...

**Comment by mesqueeb** [comment]
On the other hand, I just read @rstoenescu reasoning [here](https://github.com/quasarframework/quasar/commit/982f60b3242a264a77b69e4efd3abbba656bb631#commitcomment-32478629), and I guess that makes sense as well...

> You mean `cordova-ios`?
> 
> I tested with v5 and that still requires the build flag. If you open the .xcodeproj file in XCode you can also manually set the build mode, but what I am interested is in everything working out of the box, which is what this commit does.
> 
> Also, for some reason, with latest cordova CLI, a newly scaffolded cordova project folder comes with cordova-ios v4.
