### ISSUE TITLE
[v1] Bug QSelect filter with `map-options` & `emit-value`

### ISSUE THREAD

**Issue by spyke113** [quasarframework/quasar#3797]
### Software version

Quasar: v1.0.0-beta.15

### Codepen
https://codepen.io/spyke113/pen/bZZJYQ

### What did you get as the error?
Labels of selected options reset to its values

### What steps did you take, to get the error?
Start typing "go" in input

**Comment by pdanpdan** [comment]
You cannot use map-options because you would not have all the options available.
You need to use a scoped slot for the chips and provide the desired display value in it.
Example: https://codepen.io/anon/pen/zXrbxW?editors=1010

**Comment by spyke113** [comment]
I can solve this without a slot, for example, like this:
https://codepen.io/spyke113/pen/bJEyEJ
I just would like to know if this issue can be solved somehow by modifying the component?

**Comment by pdanpdan** [comment]
No, it's not possible. In order to map options you need the full list of options (at least of selected ones).
