### ISSUE TITLE
[v1] Plugin: QDialog Confirm Hitting Enter

### ISSUE THREAD

**Issue by marco-quintella** [quasarframework/quasar#3801]
I'm using quasar in a school management application and would be very useful to have an option on the confirm type dialogs to do the confirmation with the enter press.

Example: You will erase some row in a table, the system prompts a dialog asking if you are sure about erasing this data. You press enter or click on OK to confirm the data erase.

When this task is more repetitive, it's cool to have the confirmation on entering key press. Saves time for the person doing the job, just pressing enter than getting the mouse and clicking on OK.

**Comment by mqdev** [comment]
#3802 

I made an additional prop for the component called `enterConfirm`. When this is true, any type of dialog can be confirmed with the enter key.

**Comment by pdanpdan** [comment]
Implemented for some time. Forgot to close the issue.
