### ISSUE TITLE
[v0.17] layout header does not reliably calculate min-height

### ISSUE THREAD

**Issue by MartinMuzatko** [quasarframework/quasar#3803]
### Software Info
```
> # quasar info                                                                                                                              
Operating System                Linux(4.4.0-17763-Microsoft) - linux/x64
NodeJs                          10.8.0

Global packages
  NPM                           6.9.0
  yarn                          1.2.1
  quasar-cli                    0.17.24
  vue-cli                       3.2.1
  cordova                       7.1.0

Important local packages
  quasar-cli                    0.17.24
  quasar-framework              0.17.20
  vue                           2.5.17
  vue-router                    3.0.1
  vuex                          3.0.1
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54
  webpack                       4.25.1
  webpack-dev-server            3.1.14
  workbox-webpack-plugin        3.6.3
  register-service-worker       1.5.2
```
Any other software related to your bug:

### JsFiddle

I am not sure if I am able to reproduce this in a simple jsfiddle. will look for a code sandbox.

This is how I use q-layout:

``` html
    <q-layout view="lHh Lpr lFf">
        <PageSidebar v-if="!('frameless' in $route.query)" />
        <q-layout-header>
            <q-tabs class="full-width" color="dark" align="justify" v-if="!('frameless' in $route.query)">
                <q-route-tab slot="title" icon="power" item to="/" :count="deviceCount">Devices</q-route-tab>
                <q-route-tab slot="title" icon="apps" item to="/apps">Apps</q-route-tab>
            </q-tabs>
        </q-layout-header>
        <q-page-container>
            <router-view />
        </q-page-container>
    </q-layout>
```

And the router-view implements a 
``` html
<q-page class="q-pa-lg">...</q-page>
```

### What did you get as the error?

Sometimes the q-layout-page gets the correect min-height calculated based on the q-layout-header height. Sometimes not!

![image](https://user-images.githubusercontent.com/2950505/55562567-7e26ed00-56f4-11e9-83c5-f7ad64488489.png)

### What were you expecting?

reliably set min-height

### What steps did you take, to get the error?

I can't find a pattern.. I can do a hard-reload without cache, I can do a simple reload or route change. But one thing is certain: No matter if the bug comes or not, every subsequent route change has the same behavior.

**Comment by mesqueeb** [comment]
@MartinMuzatko Perhaps related is #3757 

While this post is focussed on V1, my second post in that thread has a solution that should work on 0.17 as well.

**Comment by MartinMuzatko** [comment]
Workaround works - thanks!

**Comment by mesqueeb** [comment]
@MartinMuzatko 
In my workaround I think I made a mistake. I wrote:
```stylus
.q-page
  min-height initial !important
```
But it requires this to work properly:
```stylus
.q-page
  min-height inherit !important
```

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1, which I recommend to upgrade to as soon as possible.
If your business requires this fix in 0.17, let me know. But just to paint the bigger picture: fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this otherwise it is very detrimental to Quasar to halt working on v1.

Thanks.

**Comment by MartinMuzatko** [comment]
@rstoenescu Are we able to use v1 with material design 1 instead of 2 ? :P Then it is no problem.
Right now we want to stay away from new material design.
But maybe it is easer to write a material design 1 style then (mat1 mat2)

**Comment by mesqueeb** [comment]
@MartinMuzatko
as I mentioned, my workaround should work on v0.17 as well! However, perhaps the classes of `q-header` and `q-footer` are called `q-layout-header` and `q-layout-footer` instead.
Please take note.

Another problem with the calculation I have found in the case of Cordova:
<hr>
iOS cordova still has problems where **the page height is not calculated properly** in the QPage and QLayouts.

_The previous problem I had found:_
- a dynamic header/footer that might change the height after render

**Another problem I have found:**
- iOS cordova has automatic hiding of the splashscreen, which in my case caused the height of the header/footer to be calculated incorrectly by quasar.

You'll have to manually hide the splashscreen and add a short delay to the calculation of your header and footer after your layout mounts.

I have described the detailed solution in [this post](https://github.com/quasarframework/quasar/issues/3757#issuecomment-478316287).

**Comment by MartinMuzatko** [comment]
It is fine for my case. I have fixed it for our case. 👍
