### ISSUE TITLE
[v1] Expansion of menu items in official docs stutters and lags

### ISSUE THREAD

**Issue by Ragura** [quasarframework/quasar#3804]
### Version
Unknown, what the official v1 site is using at the moment.

### What did you get as the error?
The expanding menu items in the official v1 docs stutter and lag when you open them. On clicking, it stutters for a (noticeable) microsecond, then it expands but sometimes flickers slightly while doing so. The text usually jumps from blurry to sharp while the animation is in progress.

Since the docs are built with Quasar, it worries me that it may happen when using the components that drive them in my own projects.

I have tested this on Chrome and Edge so far, exact same result.

### What were you expecting?
A smooth transition that feels responsive when you click it.

### What steps did you take, to get the error?
Click any expanding menu item, like for example "Layout and grid".

**Comment by nothingismagick** [comment]
Is it possible that this is due to the type of ease-in ease-out animation?

**Comment by nothingismagick** [comment]
Slide transition uses this
```
      el.style.transition = `height ${this.duration}ms cubic-bezier(.25, .8, .50, 1)`
```

**Comment by nothingismagick** [comment]
But I don't see any blurring or flickering on MacOS with Chrome, Safar, Brave or on Firefox Developer.

I guess you are using Windows, right? @Ragura

**Comment by Ragura** [comment]
My apologies, I should have mentioned I'm on Windows 10, yes. The blurring and flickering is extremely vague and shortlived, not always visible. Could be random browser rendering, so I first didn't even include that in the issue and focused on the lagging part. I then changed my mind because they all might be related and I tried to offer as much information as possible.

**Comment by nothingismagick** [comment]
It sounds to me like the flicker is an outliying issue with your graphics card, because I just tested on Linux and I don't see any rendering problems whatsoever. However, I think the "jump" that you are noticing is the separator being added and then removed - it isn't the transition.

**Comment by nothingismagick** [comment]
Can you make a video screencapture of the event you are witnessing?

**Comment by Ragura** [comment]
Recorded it.

![menulag](https://user-images.githubusercontent.com/16363147/55570103-07452080-5703-11e9-9ed4-df31e6b2a36c.gif)

The recording doesn't show the flicker that I see in the browser, nor does it show up on my ipad. So let's forget about that for now and chalk it up to my configuration (hard or software). But it does show the delay in opening it and a small irregular slowdown near the end when it's closing. So I guess it could indeed be something being added/removed? It's not that it's a breaking issue, but I've shown it to other people in my house (to make sure I'm not crazy) without telling them what it was about and they all noticed the apparent "unresponsive" feeling of opening it due to the delay/slowdown.

**Comment by nothingismagick** [comment]
This "jump" is because of the separator being added and removed.
```
      if (this.expandSeparator) {
        node.push(
          h(QSeparator, {
            staticClass: 'q-expansion-item__border q-expansion-item__border--top absolute-top',
            props: { dark: this.dark }
          }),
          h(QSeparator, {
            staticClass: 'q-expansion-item__border q-expansion-item__border--bottom absolute-bottom',
            props: { dark: this.dark }
          })
        )
      }
```

One solution might be to add a negative margin to the separator...

**Comment by Ragura** [comment]
Anything to mitigate it would be welcome. Thanks for looking into it!

**Comment by nothingismagick** [comment]
So I think I found it. There is an errant 2px of padding in the .q-expansion-item__content css - but the good news is that this is *only* in the stylus for the docs themselves. Thanks for bringing it up though!

PR here: https://github.com/quasarframework/quasar/pull/3807

**Comment by Ragura** [comment]
Excellent, thanks again for the super fast reply and fix!

**Comment by nothingismagick** [comment]
To be clear, this is not a behaviour in the "stock component", but something that snuck its way into the docs site. Please compare: https://v1.quasar-framework.org/vue-components/expansion-item

**Comment by Ragura** [comment]
Correct. Although I still notice a slight 200ms or so delay after clicking to open. It's not a problem, but I "feel" it's there. For example in the Basic Usage block on the expansion item documentation page. You click, then a slight delay, then the sliding animation starts. Maybe that's just how it's always been and I'm focusing too much on it now? As I said, it's not a problem and the described behaviour of this topic is not there on the component page!

**Comment by nothingismagick** [comment]
Like I said at the beginning, this is probably due to:
```
      el.style.transition = `height ${this.duration}ms cubic-bezier(.25, .8, .50, 1)`
```

**Comment by Ragura** [comment]
No problem, not too familiar with cubic bezier transitions so I didn't grasp the connection to it. Can always toy with the styling when I get to building the part in the project that needs it.
