### ISSUE TITLE
Add 'avatar' slot for QChatMessage

### ISSUE THREAD

**Issue by ymhr** [quasarframework/quasar#3806]
Currently, it only takes a string for a prop (a url).

It would be nice if this could be provided in a slot, so that we can use a different component for the avatar (e.g. the `QAvatar` component). It could look something like this:
```vue
<q-chat-message sent name="me">
  <template>
    Default content
  </template>
  <template #avatar>
    <q-avatar color="primary" text-color="white">J</q-avatar>
  </template>
</q-chat-message>
```

We already have something similar this available in `QListItem` by using `<q-item-section avatar>...</q-item-section>`

**Comment by rstoenescu** [comment]
Hi,

There is actually an "avatar" slot already for QChatMessage. Missed to add it to the API files and will do so along the next deployment of docs.
