### ISSUE TITLE
Persistent files in QUploader queue

### ISSUE THREAD

**Issue by diegomagikal** [quasarframework/quasar#3808]
### Software version
Quasar: 1.0.0-beta.14
Node: 10.15.1
NPM: 6.4.1
Browsers: Chrome
OS: Win7

### JsFiddle
https://codepen.io/diegomagikal/pen/xeVrKj

### What did you get as the error?
When q-tab changes, the @added files in q-uploader disappear

### What were you expecting?
I expect that the @added files are still loaded in the queue

### What steps did you take, to get the error?
From JsFiddle:
1. Load some files to q-uploader
2. Click on second tab
3. Returns to first tab
4. The loaded files are missing

My idea is upload the files programmatically when the user clicks on "Save". But if he loads files and changes the tab, the files will be lost.

**Comment by smolinari** [comment]
This issue might be resolved with/ is related to this: https://github.com/quasarframework/quasar/pull/3634

Scott

**Comment by diegomagikal** [comment]
Yes! This solves the problem. Thanks @smolinari.

@pdanpdan, could you turn this proof in a real PR for quasar?

**Comment by rstoenescu** [comment]
Added a new prop (Boolean) for QCarousel/QTabPanels/QStepper: `keep-alive`. This will also solve this ticket.
Will be available in beta.22.
