### ISSUE TITLE
[v1] q-toggle should keep colors after disabling

### ISSUE THREAD

**Issue by willypuzzle** [quasarframework/quasar#3810]
q-toggle loses its colors when it is disabled but there are occasions where should be useful it keeps colors even if it is disabled. For example when you want to show a list of selected boolean items but you don't want them to be modified.
Maybe you could add a prop such as 'readonly', in order to do this. As in q-input.

**Comment by rstoenescu** [comment]
Hi,

You will be able to use `keep-color` Boolean prop for this.
Fixed some CSS related to QRadio/QCheckbox/QToggle and will be available in beta.16.
