### ISSUE TITLE
[v1] Submit on form with "enter" generates 2 requests

### ISSUE THREAD

**Issue by lbenevenuto** [quasarframework/quasar#3812]
### @quasar/app... v1.0.0-beta.15

Operating System - Linux(4.18.0-17-generic) - linux/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.14 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.15 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - pc-avell
  wlo1 - 192.168.0.107

### What did you get as the error?
An "enter" on form.
![image](https://user-images.githubusercontent.com/3451320/55635629-8b48e800-5797-11e9-9615-4244a8fdfa21.png)

### What were you expecting?
Just one request

### My code
![image](https://user-images.githubusercontent.com/3451320/55635770-e4b11700-5797-11e9-8309-e51b460192b1.png)
![image](https://user-images.githubusercontent.com/3451320/55635800-f4306000-5797-11e9-824f-d03a0959cfa9.png)

Thanks for the amazing job.
This project is awesome !!!!!!!!!

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in beta.16.
