### ISSUE TITLE
[v1] Tabs scroller Display Exception

### ISSUE THREAD

**Issue by autukill** [quasarframework/quasar#3815]
### Software version

Quasar:
@quasar/app (v1+ only): 1.0.0-beta.13
OS: Windows 10 1803 x64
Browsers: Chrome73.0.3683.103

### CodePen
https://codepen.io/autukill/pen/rbLYqd

### What did you get as the error?
When the width value is odd, the scroll bar disappears (or appears).
When the width value is even, the scroll bar appears (or disappears).

### What were you expecting?
The scroll bar is always displayed when the tab overflows

### What steps did you take, to get the error?
![8Dwtkxq3Gb](https://user-images.githubusercontent.com/5186639/55664170-9e71bb80-585c-11e9-9479-554059759560.gif)

1. Tab is overflowing
2. Resize tabs width. 
3. When the width value is odd, the scroll bar disappears (or appears).
4. When the width value is even, the scroll bar appears (or disappears).

**Comment by mountash** [comment]
Created a PR #3818

**Comment by rstoenescu** [comment]
Made a small change and pushed. Thanks for investigating and contributing!!
Will be available in beta.16.
