### ISSUE TITLE
Prevent the 'quasar dev -p' from clearing the screen after build including QR code

### ISSUE THREAD

**Issue by Sfinx** [quasarframework/quasar#382]
Hi,

Set the appropriate option for the FriendlyErrorsPlugin()

```
--- build/webpack.dev.conf.js.orig	2017-02-09 02:38:48.423426618 +0200
+++ build/webpack.dev.conf.js	2017-02-09 02:35:21.677428870 +0200
@@ -33,7 +33,9 @@
       template: 'src/index.html',
       inject: true
     }),
-    new FriendlyErrorsPlugin()
+    new FriendlyErrorsPlugin({
+      clearConsole: false
+    })
   ],
   performance: {
     hints: false
```

**Comment by rstoenescu** [comment]
Hmm, good point here. Will do.

**Comment by rstoenescu** [comment]
Done. `config/index.js` has a new variable for dev called "clearConsoleOnRebuild" which is by default set to `false`.

**Comment by Sfinx** [comment]
Thanks ! At least it must be false when called with -p or the QR code will be lost ;)

**Comment by rstoenescu** [comment]
Yep. You're perfectly right. Totally missed that on the template update a few days ago when I added FriendlyErrorsPlugin.
