### ISSUE TITLE
q-btn can't correctly show the page with :to

### ISSUE THREAD

**Issue by FPNL** [quasarframework/quasar#3822]
### Software version

Quasar: 1.0.0-beta.14
@quasar/app (v1+ only): 1.0.0-beta.15
OS:  Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.4.1
Browsers: Chrome 73.0.3683.86
Any other software related to your bug:

### What did you get as the error?
`<q-btn to="/test" />`
This is quite normal, nothing wrong.

but 
When i use
`<q-btn :to="{name: 'test'}" />`
URL indeed changed, but nothing comes out.
I need to refresh the page, then it will show something what is right.
### What were you expecting?
After clicked the q-btn with `:to`, it can be correctly show what I write.

### What steps did you take, to get the error?
1. `quasar create new-web`
2. add a q-btn with `:to` on Index.vue
3. I add this code in router.js
```js
const routes = [
...,
{
    path: '/test',
    name: 'test',
    component: () => import('layouts/MyLayout.vue'),
    children: [
      { path: '', component: () => import('pages/lang_and_i18n/Index.vue') }
    ]
  }
]
```

**Comment by mountash** [comment]
Hi,
I'm trying to reproduce the issue. Added two buttons to beta.15 and it is working as expected.

https://github.com/mountash/quasar/blob/8e8e452249ed66bd033c8555a8f7d5845eadc4b8/quasar/dev/components/components/button.vue#L660-L664

**Comment by FPNL** [comment]
I think I found the problem.
Below is my original code, and `name` should put into children.
```js
const routes = [
...,
{
    path: '/test',
    name: 'test',
    component: () => import('layouts/MyLayout.vue'),
    children: [
      { path: '', component: () => import('pages/lang_and_i18n/Index.vue') }
    ]
  }
]
```

**Comment by rstoenescu** [comment]
@FPNL yes, exactly.
