### ISSUE TITLE
[v1] PWA should not use manifest value of background_color to also specify apple-mobile-web-app-status-bar-style

### ISSUE THREAD

**Issue by ssuess** [quasarframework/quasar#3828]
### Software version

Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 11.11.0

Global packages
  NPM - 6.9.0
  yarn - Not installed
  @quasar/cli - 1.0.0-beta.4
  cordova - 8.1.2 (cordova-lib@8.1.1)

Important local packages
  quasar - 1.0.0-beta.15 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.15 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - ssuess-pro
  en0 - 193.0.21.208
  utun2 - 193.0.22.3

### What did you get as the error?
The problem is that when building a quasar pwa, quasar will take the background_color value defined in the pwa manifest area and apply it to the content value of the meta tag `apple-mobile-web-app-status-bar-style`

### What were you expecting?
`apple-mobile-web-app-status-bar-style` contains one of three settings for content (default, black, and black-translucent).  Any other value will be ignored. 

There should either be a separate manifest value specifically for the `apple-mobile-web-app-status-bar-style` meta, or it should not be added as a meta tag by quasar, but can be added manually by the developer into the index.template.html file.

**Comment by rstoenescu** [comment]
Thank you fore reporting this!
Fix will be available in `@quasar/app` v1.0.0-beta.17. The fix consists in adding support for a new prop in quasar.conf.js > pwa > metaVariables. Example (values are the default ones):

```js
  // variables used to inject specific PWA
  // meta tags (below are default values)
  metaVariables: {
    appleMobileWebAppCapable: 'yes',
    appleMobileWebAppStatusBarStyle: 'default',
    msapplicationTileColor: '#000000'
  }
```
