### ISSUE TITLE
v1 qUploader @finish event missing 

### ISSUE THREAD

**Issue by turigeza** [quasarframework/quasar#3829]
As per the discussion here
https://forum.quasar-framework.org/topic/3388/uploader-finish-removed-v1-replacement

This event was very useful if you were not using the batch option with qUploader. 
It would be nice to have this event back in v1. Thank you!

**Comment by rstoenescu** [comment]
`@start` and `@finish` coming back in beta.19

**Comment by turigeza** [comment]
Thank you !
