### ISSUE TITLE
[v1] beta.15 QInput with prefix incorrect line-height

### ISSUE THREAD

**Issue by carlesar** [quasarframework/quasar#3830]
### Software version

Quasar: 1.0.0-beta.15
@quasar/app (v1+ only): 1.0.0-beta.15
OS: Debian 4.9.144-3 x86_64 GNU/Linux
Node: 9.11.2 
NPM: 5.6.0
Browsers: Chrome and Firefox

### Codepen
https://codepen.io/anon/pen/xeRORd

### What were you expecting?
The prefix and the input value should be aligned.
Nowadays, the prefix is 2 pixels down from the input value.

### What steps did you take, to solve the error?
Setting the property line-height to 0px to the class q-field__prefix.

Don't know if that's a good work around, though.

**Comment by rstoenescu** [comment]
Hi,

This has already been fixed in future beta.16.
