### ISSUE TITLE
How to send 404 page from component in PreFetch (SSR mode)

### ISSUE THREAD

**Issue by vasilyman** [quasarframework/quasar#3831]
How to send 404 page from component in PreFetch (SSR mode)

**Comment by rstoenescu** [comment]
Hi,

Please use the Discord server or the forum for questions. Github is reserved exclusively for bug reports.

1. Create a route for your 404 page.
2. Use the `redirect` function param from preFetch to redirect to that route: https://v1.quasar-framework.org/quasar-cli/cli-documentation/prefetch-feature#Redirecting-Example
