### ISSUE TITLE
[v1] Add theming for QIcon Component on Material Icons

### ISSUE THREAD

**Issue by ezioadsr** [quasarframework/quasar#3832]
I'm using a Quasar to develop an App and I'm using material-icons in my project. However, a want to use dual-tone theme.

Add `theme` prop or similar on QIcon component to choose  theme of 'Material Icons' or some configuration on quasar.conf...:
- **Filled**: class 'material-icons' at source https://fonts.googleapis.com/icon?family=Material+Icons (default)
- **Outlined**: class 'material-icons-outlined' at https://fonts.googleapis.com/icon?family=Material+Icons+Outlined
- **Two-Tone**: class 'material-icons-two-tone' at https://fonts.googleapis.com/icon?family=Material+Icons+Two+Tone
- **Round**: class 'material-icons-round' at https://fonts.googleapis.com/icon?family=Material+Icons+Round
- **Sharp**: class 'material-icons-sharp' at https://fonts.googleapis.com/icon?family=Material+Icons+Sharp

```` html
<i class="material-icons">donut_small</i>
<i class="material-icons-outlined">donut_small</i>
<i class="material-icons-two-tone">donut_small</i>
<i class="material-icons-round">donut_small</i>
<i class="material-icons-sharp">donut_small</i>
````

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, Google hasn't released the webfont versions for outlines, two-tone, round and sharp. Might be a good idea to request it on [their repo](https://github.com/google/material-design-icons).

**Comment by ezioadsr** [comment]
Their repository is on low maintenance and out of date. 
:(

**Comment by rstoenescu** [comment]
Just FYI, we use the CDN version for `@quasar/extras` because of this.
Without them releasing the webfont variants we can't really do anything, so push them regardless of their activity. I know many people would subscribe to such a request, including me.
