### ISSUE TITLE
[v1] Checkbox lists - clicking item (instead of checkbox) does not check/uncheck box on PWA

### ISSUE THREAD

**Issue by ssuess** [quasarframework/quasar#3836]
### Software version
Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 11.11.0

Global packages
  NPM - 6.9.0
  yarn - Not installed
  @quasar/cli - 1.0.0-beta.4
  cordova - 8.1.2 (cordova-lib@8.1.1)

Important local packages
  quasar - 1.0.0-beta.15 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.15 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - ssuess-pro
  en0 - 193.0.21.208
  utun2 - 193.0.22.87

### What did you get as the error?
When viewing a PWA in mobile safari, clicking on the list item next to a checkbox will correctly check/uncheck that box. However, after adding the PWA to the home screen on the device (which will cause it to launch as a PWA instead of in-browser), clicking on the list items does NOT check/uncheck the box (although one can click on the box itself and it will check/uncheck)

### What were you expecting?
Was expecting (as when viewing in web browser) that clicking on list item next to checkbox would cause box to be checked/unchecked

### What steps did you take, to get the error?
used following structure to create list and checkboxes:
````
<q-list bordered padding class="pwidget">
        <q-item-label header>App prefs</q-item-label>

        <q-item tag="label" v-ripple>
          <q-item-section side top>
            <q-checkbox v-model="show_advsearch_types" @input="savePref('show_advsearch_types', show_advsearch_types)" />
          </q-item-section>

          <q-item-section>
            <q-item-label>Advanced Search Types</q-item-label>
            <q-item-label caption>
              Adds type selector to search box.
            </q-item-label>
          </q-item-section>
        </q-item>
        <q-item tag="label" v-ripple>
          <q-item-section side top>
            <q-checkbox v-model="show_advsearch_dates" @input="savePref('show_advsearch_dates', show_advsearch_dates)" />
          </q-item-section>

          <q-item-section>
            <q-item-label>Advanced Search Dates</q-item-label>
            <q-item-label caption>
              Adds date range to search box.
            </q-item-label>
          </q-item-section>
        </q-item>
      </q-list>
````

**Comment by nothingismagick** [comment]
Um - I dunno what's going on here. 
https://codepen.io/nothingismagick/pen/JVWBab?editors=1111

I just copied your code (removing the @input methods) and clicking on the label works. I really don't understand why PWA would not be working...

**Comment by ssuess** [comment]
I also think it is odd. Because like your example, if I am viewing in a regular web browser context, it works fine. It only fails once the PWA is added to homescreen and launched separately.

**Comment by rstoenescu** [comment]
@nothingismagick Because PWAs don't use the WebView of the host OS -- iOS I'm looking at you especially. They use a much older WebView, which might have bugs regarding `<label>` + `<input>`.

The reporter doesn't mention the platform with which he is testing, but I bet it's iOS. The actual version might help.

**Comment by ssuess** [comment]
You are right, it is iOS (albeit the latest version, 12.2)

**Comment by rstoenescu** [comment]
I'm sorry to say, but unless the Apple people fix bug of theirs in their specific PWA browser (different than iOS safari), we cannot do absolutely anything from Quasar code.

You could however play with some workaround, like adding `@click.capture` on QItem and changing the model from there.

Wish we could do more, but when the browser itself misbehaves so badly we're essentially left out in the dark..
