### ISSUE TITLE
add vuex-orm by default

### ISSUE THREAD

**Issue by HenryTabima** [quasarframework/quasar#3837]
Before the existence of SPA's, developers used to use ORM in the backend to manage easily their data from their database. now that the business logic has been moved to the frontend it makes sense to have a standard and easy way to CRUD data in the store just defining models instead of been writing by hand all your crud methods (state, getters, actions and mutations) for each model you have in your app.

https://vuex-orm.github.io/vuex-orm/guide/prologue/what-is-vuex-orm.html#what-is-it-like-to-use-vuex-orm

I chose this framework for my app because I wanted to build a medium-large project, then I met vuex-orm and I thought this would be implemented from the beginning. 

this feature should be easy to include and I think this is going to add a lot of value to this project.

**Comment by nothingismagick** [comment]
An interesting idea, but instead of moving this to core my recommendation is to create an app-extension.
https://v1.quasar-framework.org/app-extensions/development-guide/introduction

**Comment by HenryTabima** [comment]
alright it could take some time but I guess it's worth

**Comment by rstoenescu** [comment]
The app extension is best way to go. Closing this.
