### ISSUE TITLE
QEditor needs generic-border-radius applied

### ISSUE THREAD

**Issue by gorango** [quasarframework/quasar#3842]
Currently, if you apply a border radius to the QEditor, the following will happen:

![image](https://user-images.githubusercontent.com/5211330/55848598-7663b000-5b1b-11e9-9f1e-0112717ac59d.png)

The corners get cut off by the background color of the toolbar and content.

I have easily updated the CSS but I believe that the editor should have the `$generic-border-radius` applied to the border and corners of the conflicting elements.

I'm happy to make this PR, just wanna open it up to discussion first.

**Comment by nothingismagick** [comment]
Go for a PR!

**Comment by rstoenescu** [comment]
Will be available in beta.19
