### ISSUE TITLE
[V1] - QInput error icon

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3843]
In the latest version of V1, the error icon was changed on QInput and QSelect. Is it possible to specify your own error icon instead of being forced to the one that it is currently. 

The previous versions had a much less intrusive icon. I noticed there is a prop "no-error-icon" which is great :) - Would be awesome to be able to specify your own.

Many thanks for this great framework btw!

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. 

To answer your question, you can use the Quasar object to set the icon in a component. 

https://codepen.io/smolinari/pen/WWQybN

Scott

**Comment by rstoenescu** [comment]
Hi,

We are trying to follow Material Design guidelines as close as possible. That being said, the new icon is the one that is recommended.

However, you can change that icon (previous one was `priority_high`):
`this.$q.iconSet.field.error = <your icon>`

**Comment by sn0rcha** [comment]
Many thanks for your comments and help :)

**Comment by smolinari** [comment]
Testing, it's `this.$q.iconSet.type.warning`.(?)

https://codepen.io/smolinari/pen/WWQybN

Scott

**Comment by rstoenescu** [comment]
Sorry, I was referring to beta.16 which is not yet released (but will be today/tomorrow)...
