### ISSUE TITLE
[v1 bug] Placeholder is gone, not showing up for Q-Select

### ISSUE THREAD

**Issue by robsoncombr** [quasarframework/quasar#3844]
### Software version

$ quasar info

Operating System - Linux(4.15.0-1032-aws) - linux/x64
NodeJs - 8.15.0

Global packages
  NPM - 6.9.0
  yarn - 0.32
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.15 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.15 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### What did you get as the error?
Placeholder is gone on v1 and does not show up, why was it decided to remove placeholder from select? It worked until 0.17.x .

### What were you expecting?
I would really appreciate to have placeholder back for select on v1, but the fact that I need it on my applications and worked until v1, I consider that because it is a native property for select element it should be implemented and supported and this is why I'm requesting as a bug and not a new feature.

### What steps did you take, to get the error?
Just try to add placeholder to a q-select, ex: 
`<q-select label="no placeholder" placeholder="test" :options="['no', 'placeholder']" stack-label />`

**Comment by robsoncombr** [comment]
for the record, refer to https://github.com/quasarframework/quasar/issues/3614

**Comment by rstoenescu** [comment]
For QSelect, the placeholder only has meaning if using `use-input` prop, which also renders an input. Otherwise there's no place to attach the placeholder. So simply use the label or hint.

**Comment by robsoncombr** [comment]
use-input worked to me, thanks.

**Comment by mesqueeb** [comment]
@robsoncombr can you share what you did?

I'm trying to add a placeholder to a q-select that doesn't uses a label.

**Comment by mesqueeb** [comment]
I solved it by doing:
```html
<q-select
  v-model="value"
  :label="value ? undefined : 'please select'"
/>
```
But it feels rather hacky...

I'd love a regular `placeholder` prop!
