### ISSUE TITLE
[v1] QSelect scroll jumps up when the mouse is moved

### ISSUE THREAD

**Issue by Jon-Salmon** [quasarframework/quasar#3848]
I have a QSelect which contains enough object to cause the it to scroll. If I scroll the QSelect down to the bottom and then move the mouse over the QSelect, the scroll within the QSelect jumps up a bit. As such it is impossible to select element at the bottom of the QSelect with the mouse!

![2019-04-10_17-30-05](https://user-images.githubusercontent.com/26483285/55896537-6c42bf80-5bb6-11e9-964c-72e209b7594d.gif)

Using Quasar 1.0.0-beta.16

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in beta.17.
