### ISSUE TITLE
[v1] QSelect Autocomplete on more than 2 chars example not working properly

### ISSUE THREAD

**Issue by Alsekar** [quasarframework/quasar#3850]
### Software version
Operating System - Linux(4.15.0-38-generic) - linux/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.16 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all
simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.16 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loader
s to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### What did you get as the error?
In the example Autocomplete on more than two chars, on typing two characters to filter options,  the characters get highlighted and removed on typing a third character.
### What were you expecting?
Issue was not present in beta.15
### What steps did you take, to get the error?
Tried the example given in docs
https://v1.quasar-framework.org/vue-components/select#Example--Autocomplete-on-more-than-2-chars

**Comment by rstoenescu** [comment]
Fix will be available in beta.17.
