### ISSUE TITLE
QScrollArea is available on Doc but app crashes on boot when included in components

### ISSUE THREAD

**Issue by Hamdan85** [quasarframework/quasar#3851]
### Software version

Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 11.12.0

Global packages
  NPM - 6.9.0
  yarn - Not installed
  @quasar/cli - 1.0.0-beta.3
  cordova - 8.1.2 (cordova-lib@8.1.1)

Important local packages
  quasar - 1.0.0-beta.16 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.16 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### What did you get as the error?
Added "QScrollArea" ([link to doc](https://v1.quasar-framework.org/vue-components/scroll-area)) in quasar.conf.js

### What were you expecting?
Be able to use QScrollArea component

### What steps did you take, to get the error?
Application starts normally and after building console gets empty and nothing happens. Server is unavailable in browser

ps: guys, I'm not trying to bother, only to help. Tell me if I aint doing so.

**Comment by metalsadman** [comment]
you probably should show your `quasar.conf.js` file.

**Comment by Hamdan85** [comment]
@metalsadman I could, if you get an initial quasar project and add QScrollArea, it happens already, so I didnt. As I told in the issue, I only added the component and the server just went unresponsive. By removing it came back to normal.

**Comment by rstoenescu** [comment]
@Hamdan85 I just created a new project folder. Doesn't happen. Can you create a repo that I can take a look at, please? Thanks.

**Comment by pdanpdan** [comment]
Are you using dev or build, PWA, SPA, SSR, electron, cordova?

**Comment by Hamdan85** [comment]
@rstoenescu I surely can give you temporary access to this project's repository on bitbucket.
Ill call you on discord!

**Comment by rstoenescu** [comment]
@Hamdan85 Are you adding it twice or more times? It says `Identifier 'QScrollArea' has already been declared`...

**Comment by Hamdan85** [comment]
No, I'm not adding it twice. I read the error and checked.

**Comment by rstoenescu** [comment]
It shouldn't be specified twice in quasar.conf.js > framework > components. You definitely have it defined twice there. That's all, if QScrollArea is manually imported this doesn't count.

The compilation error comes from `import { Something, Something } from ...` which can only mean that "Something" is defined twice in the quasar.conf.js > framework > components. Are you using any App Extensions which might wrongly tamper with quasar.conf.js?

**Comment by Hamdan85** [comment]
@rstoenescu Im assuring you that I dont have it twice on my quasar.conf.js or have imported it on the component... 

Just by adding it on my conf it stops my server... Im not using ANY extensions

**Comment by rstoenescu** [comment]
@Hamdan85 May I take a look at your repo pls?

**Comment by Hamdan85** [comment]
Sure,
can you send me your bitbucket username/email please?

Em seg, 15 de abr de 2019 às 17:31, Razvan Stoenescu <
notifications@github.com> escreveu:

**Comment by Hamdan85** [comment]
Just upgraded for beta.17 and it's fixed... lol...

Em ter, 16 de abr de 2019 às 02:45, Gabriel Hamdan <ogabrielhamdan@gmail.com>
escreveu:
