### ISSUE TITLE
在IE浏览器上，Date Utils  formatDate 错误

### ISSUE THREAD

**Issue by zhangzongshan** [quasarframework/quasar#3852]
我使用IE浏览器的时候，Date Utils formatDate错误，date.formatDate(row.create_time, 'YYYY/MM/DD HH:mm:ss'))，结果变成了0NaN/NaN/NaN NaN:NaN:NaN
其他浏览器正常

**Comment by pdanpdan** [comment]
Translation:
When I use IE, Date Utils formatDate error, date.formatDate(row.create_time, 'YYYY/MM/DD HH:mm:ss')), the result becomes 0NaN/NaN/NaN NaN:NaN:NaN
Other browsers are normal

@zhangzongshan Was it a specific value of `row.create_time`?

**Comment by mountash** [comment]
@zhangzongshan and what kinf of IE? IE 11, Edge, IE 6 😄

**Comment by pdanpdan** [comment]
@zhangzongshan I think this is related to some other processing problem - your value in `row.create_time` is wrong (I would expect Infinity).

**Comment by rstoenescu** [comment]
Fix will be available in beta.17.

@zhangzongshan please answer @pdanpdan's question to ensure the fix is right for your use case too.
