### ISSUE TITLE
[v1] QInput Outlined White or Black "Overlay" overshaddows the component color.

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#3853]
### Software version

Quasar:
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
After upgrading quasar to v1.0.0-beta.15/16 the QInput's 'outlined' white or black overlay (more noticeable in dark mode) looks more prominent/very noticeable now than the component's normal color.
### What were you expecting?
QInput color should look more prominent.
### What steps did you take, to get the error?
Upgrading quasar v1 beta to latest version.

See codepen. https://codepen.io/metalsadman/pen/GLmoYL

**Comment by rstoenescu** [comment]
Hi, This is per Material specs. To short this back and forth that I am envisioning, please contact me on Discord. Thanks.
