### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by siauderman** [quasarframework/quasar#3857]
Hi, when I installed via npm install -g @quasar/cli, I got version 1 beta 4 rather than the latest version of 1 beta 16.

Thereafter, after I ran quasar dev, the version inexplicably got downgraded to 0.17. This is verified by quasar --version. Running quasar --version before quasar dev returned version 1 beta 4 which was the correct version installed.

Can anyone help?

**Comment by rstoenescu** [comment]
You probably have quasar-cli globally installed too. Follow the docs: first, uninstall the old global "quasar-cli" then install `@quasar/cli`.

```bash
$ npm uninstall -g quasar-cli
$ npm install -g @quasar/cli
```

Running "quasar" from outside a project folder tells the version of the global installation, while running "quasar" from within a project folder tells the version of the local `@quasar/app` which it defers to.

**Comment by rstoenescu** [comment]
Furthermore, the global installation does not affect the project's Quasar version.. and it shouldn't. Please use our Discord if this doesn't makes sense to you yet.

**Comment by smolinari** [comment]
The beta 4 is for the global Quasar CLI version. Beta 16 would be for the Quasar core software version. 

If you are creating a new project with the new v1 CLI, then you need to add the `-b dev` options to the end of the command, until v1 is final. If you don't, you end up with a 0.17 project version of Quasar. 

This is how you create a v1 project. 

`$ quasar create <my-new-shiny-v1-app> -b dev`

Scott

**Comment by siauderman** [comment]
Thanks a lot for your help! Problem solved.
