### ISSUE TITLE
Spinners not working in Edge 

### ISSUE THREAD

**Issue by bitmandk** [quasarframework/quasar#3858]
Spinners listed under "Other Spinners", "Coloring" and "Size" on  the Quasar documentations page (https://v1.quasar-framework.org/vue-components/spinners) is not working (spinning) in Microsoft Edge.

They work perfectly in Chrome and Firefox. 

Tested and Not working in Microsoft Edge 44.17763.1.0 - Microsoft EdgeHTML 18.17763

**Comment by rstoenescu** [comment]
@bitmandk do they work or not? I see that you closed the ticket.

**Comment by bitmandk** [comment]
Well they do not work on the documentations page, but I read that IE/edge default is not supported - so I supposed that was the problem)

**Comment by rstoenescu** [comment]
IE and Edge are supported. Where did you read otherwise?
IE11 for example does not supports svg animations (no way around it), so we animate the opacity instead only.

**Comment by bitmandk** [comment]
I read that it was not default supported:
"// Uncomment the following lines if you need IE11/Edge support
// require(`quasar/dist/quasar.ie`)
// require(`quasar/dist/quasar.ie.${__THEME}.css`)"

**Comment by rstoenescu** [comment]
Ah, yes. It is not by default supported but can be enabled from quasar.conf.js > supportIE: true

**Comment by bitmandk** [comment]
OK - also possible for UMD?

**Comment by rstoenescu** [comment]
Add the following html tag before the vue and quasar one:

```html
<!-- for v1 -->
<script src="https://cdn.jsdelivr.net/npm/quasar@1.0.0-beta.16/dist/quasar.ie.polyfills.umd.min.js"></script>

<!-- for v0.17 -->
<script src="https://cdn.jsdelivr.net/npm/quasar-framework@^0.17.0/dist/umd/quasar.ie.polyfills.umd.min.js"></script>
```

**Comment by rstoenescu** [comment]
Pick the one that matches your Quasar version. Do not add both :)

**Comment by rstoenescu** [comment]
Also, thoroughly read the UMD doc page (assuming you're on v1): https://v1.quasar-framework.org/start/umd

**Comment by bitmandk** [comment]
Yes I'm on the latest BETA of 1.0
