### ISSUE TITLE
Weird Autofill style when using chrome

### ISSUE THREAD

**Issue by BritishHumor** [quasarframework/quasar#3860]
**Quasar:** 1.0.0-Beta16

### Issue
When autocomplete is enabled on inputs, chrome causes some really weird background color to appear when a autocomplete option is selected.

![image](https://user-images.githubusercontent.com/5392255/55967545-67dbdc80-5c72-11e9-90dc-893bb3c5e655.png)

Previously, on the none beta build of quasar, the same inputs used to have the following autocomplete style.

![image](https://user-images.githubusercontent.com/5392255/55967612-84781480-5c72-11e9-8a0c-cff0f5d4ea0f.png)

Nothing regarding styling has been changed and no custom style was set this is how it functions pretty much out of the box.

Does anyone else experience similar issues?

NOTE: I tried to edit it using `:-webkit-autofill` css selector, I was able to change things such as text colours, but when I tried to change background color (using `!importnat`) it wouldn't change.

**Comment by pdanpdan** [comment]
If you need to hide the autofill bg use this in your CSS:

```styl
.q-field__native
  &:-webkit-autofill, &:-internal-autofill-selected
    background-clip content-box
      &, &:hover, &:focus
         transition background-color 5000s ease-in-out 0s
```

**Comment by rstoenescu** [comment]
Better style will be available in beta.17

**Comment by arieltoledo** [comment]
Hi, Im having trouble with this issue again .

Operating System - Linux(4.15.0-30deepin-generic) - linux/x64
NodeJs - 13.14.0

Global packages
  NPM - 6.14.4
  yarn - Not installed
  @quasar/cli - 1.0.5
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.5 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.7 -- Quasar Framework App CLI
  @quasar/extras - 1.1.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

**Comment by pdanpdan** [comment]
Yes, there is a change in Crome that does not allow changing the bg anymore. There is a bug open at Chrome, nothing that can be done.

If you have problems with the borders in fields add this to your CSS:

```scss
.q-field__control
  &:before,
  &:after
    z-index: 1
```

**Comment by arieltoledo** [comment]
@pdanpdan Hi, Dan! thanks for answer, well the issue is exactly the one described above. 
**This is how its rendered now** 
![imageshack](https://imagizer.imageshack.com/v2/320x240q90/924/J7OA6S.png)
**This is how it should be rendered** 
![imageshack](https://imagizer.imageshack.com/v2/320x240q90/923/68It4F.png)

BTW: I updated quasar to the last version.

**Comment by pdanpdan** [comment]
There are some things you can try, but they are not generic.
Try setting `mix-blend-mode: hue` or `mix-blend-mode: overlay`,(play with the value) on the internal input and maybe `isolation: isolate` on a parent.
As far as I remember `hue` results in no bg highlight but no text visible either, but there is one value that almost works.

**Comment by moghthalkushal** [comment]
q-select + chrome + autocomplete still gives me issues

TypeError: getOptionValue.value(...).toLocaleLowerCase is not a function
    at fn (QSelect.js?ddd8:628)
    at Proxy.find (<anonymous>)
    at onTargetAutocomplete (QSelect.js?ddd8:629)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?9e79:163)
    at HTMLInputElement.invoker (runtime-dom.esm-bundler.js?8886:333)

![Bug](https://user-images.githubusercontent.com/5137212/122641237-58f0ee80-d147-11eb-88fe-73de6aad131e.gif)

**Comment by Sfinx** [comment]
Still seeing this weird autofill white chrome sh.t. This works for me

```
input, select {
  color: $input-text-color !important;
  -webkit-text-fill-color: $input-text-color !important;
  -webkit-background-clip: text !important;
  background-clip:  text !important;
}
```

**Comment by pdanpdan** [comment]
@Sfinx 
Hello.

Please make a codepen so we can also check.
And if you want you can try to make a PR for this - but please check not to break something else.

**Comment by Sfinx** [comment]
> @Sfinx Hello.
> 
> Please make a codepen so we can also check. And if you want you can try to make a PR for this - but please check not to break something else.

It is not quasar issue but chrome one - do not see any reason to dig it further. Just left the workaround here to help people that stuck with this too.

**Comment by pdanpdan** [comment]
if it works consistently it can be added either in the QInput component or in the docs :)

**Comment by aryan-myrtle** [comment]
> Still seeing this weird autofill white chrome sh.t. This works for me
> 
> ```
> input, select {
>   color: $input-text-color !important;
>   -webkit-text-fill-color: $input-text-color !important;
>   -webkit-background-clip: text !important;
>   background-clip:  text !important;
> }
> ```

man! I owe you a dinner.

**Comment by shotwn** [comment]
> Still seeing this weird autofill white chrome sh.t. This works for me
> 
> ```
> input, select {
>   color: $input-text-color !important;
>   -webkit-text-fill-color: $input-text-color !important;
>   -webkit-background-clip: text !important;
>   background-clip:  text !important;
> }
> ```

Thank you ! 
This was causing me a proper amount of headache.

Also in dark mode $input-text-color doesn't match the white font color. So an additional override solved the problem completely.

scss:
```scss
.q-field--dark {
  input, select {
    color: #fff;
    -webkit-text-fill-color: white;
    -webkit-background-clip: text !important;
    background-clip:  text !important;
  }
}
```

**Comment by Emiliano-Barboza** [comment]
Nice! Thank you so much @shotwn 
I owe you a coffee :)

Just to add both solutions I end your solution on this way:


` .q-field--dark {
  input, select {
    color: #fff;
    -webkit-text-fill-color: white;
    -webkit-background-clip: text !important;
    background-clip:  text !important;
  }
}

.q-field:not(.q-field--dark) {
  input, select {
    color: $input-text-color !important;
    -webkit-text-fill-color: $input-text-color !important;
    -webkit-background-clip: text !important;
    background-clip:  text !important;
  }
} `

**Comment by nodescan-admin** [comment]
Thanks. These comments helped. Here is another useful snippet to change the color of the small auto-complete icon on Safari.  Ref. https://stackoverflow.com/questions/43517932/safari-webkit-contacts-autofill-button-icon-change-color-on-empty

.q-field--dark {
  input:not(input:-webkit-autofill)::-webkit-contacts-auto-fill-button {
    background-color: #fff;
  }
}

Can be combined with the selector above (by @Emiliano-Barboza)
