### ISSUE TITLE
[V1] QDrawer loses backdrop color when opening below the breakpoint and widening the window above it

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#3861]
Quasar:
@quasar/app (v1+ only): 1.0.0-beta.16
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Browsers: Chrome 73.0.3683.103

### JsFiddle
https://codepen.io/anon/pen/oOWQzX

### What did you get as the error?
QDrawer remain overlay state without shadow layer when widen the page.

### What were you expecting?
Left drawer keep overlay state with shadow layer, or occupies space on screen, or get closed.

### What steps did you take, to get the error?
1. narrow the page
2. click menu button to open left drawer
3. resize the page from narrow to wide till the layout width exceed breakpoint
error occured: Left drawer still remain overlay state without shadow layer, does not occupies space on screen.

**Comment by rstoenescu** [comment]
Confirmed.

**Comment by rstoenescu** [comment]
Fix will be available in beta.17.
