### ISSUE TITLE
[V1][Feature request] Tick for ChipInput with QSelect

### ISSUE THREAD

**Issue by aislerGitHub** [quasarframework/quasar#3866]
Hi,

We are using QChipsInput in an app we built based on version 0.XX. I saw that this component is removed in V1 and that there is a workaround with q-select.

I’m missing something on this component. The user does not see that he has to hit enter or that he can click on a “tick” to add the value to the chip input field, as in the old version:
![image](https://user-images.githubusercontent.com/46974963/55972448-ccebfe00-5c83-11e9-9ff8-88ad27b6579c.png)

As requested by @rstoenescu [here](https://forum.quasar-framework.org/topic/3407/q-select-as-chip-input/2) I create this feature request. Would be great to see this "tick" reappear in a beta release soon.

Thanks & Best Regards
Andreas

**Comment by smolinari** [comment]
Just FYI, I created a pen to simulate as close as possible the functionality that is missing. But, it lacks in some areas. It might also be my usage/ coding. 

https://codepen.io/smolinari/pen/bJWEaX

But, this is what I'm missing:

1. The appended "check" icon isn't centered vertically or rather aligned with the chips/ the input. 
2. The append slot adds width to the input field, when the icon shows. How can I "keep" the width, so the slot doesn't affect it?

Edit: I've moved the v-if to the template, and it is still not too kosher. 😃 

Scott

**Comment by aislerGitHub** [comment]
@smolinari beside the visual issue you describe the pen misses the function of actually adding the new value as a chip. 

Would be great if this would get integrated into V1.

**Comment by smolinari** [comment]
@aislerGitHub - Check it out now. https://codepen.io/smolinari/pen/bJWEaX

Not sure that is the best method, but it works.

Scott

**Comment by aislerGitHub** [comment]
@smolinari  Cool! Thanks a lot that works! In case Quasar does not consider to implement the feature in V1 we might use your workaround

@rstoenescu is there a chance that you will include this in V1?

**Comment by smolinari** [comment]
Actually, I wouldn't call it a workaround, but rather a solution (well I would, if I were confident it is robust and within best practices. I'm not the best front-end programmer ya know....:grin:). 

You see, Quasar has taken a step back from providing such solutions itself and has left it up to us devs to provide them. For instance, I could make an app extension of the component with a short name like "scotts-enhanced-chip-input" and offer it to the Quasar dev community. After that, it would be a matter of you (and other devs) entering the command

`$ quasar ext add scotts-enhanced-chip-input`

into the CLI to get it loaded into your app and ready to use. :smiley:  

Scott

**Comment by leob** [comment]
Great solution, but I have a problem when running it with Quasar 1.03 (or with Quasar 1.05 for that matter). I think after Quasar 1.0.0-beta.16 something was broken (or changed at least).

The problem I have is that, after I click the icon, the "chip" value is added, however the input value isn't cleared ... so, it then looks like now the value is there 2 times, first as a chip and then as a value in the input field.

I have this problem on my local dev system, but when I click "settings" in the Codepen and I run it with Quasar 1.03 (so with https://cdn.jsdelivr.net/npm/quasar@1.0.3/dist/quasar.umd.min.js), or with Quasar 1.05, then the problem described above also appears - identical code, only a different (newer) Quasar version.

Tried a lot of things but I'm unable to work around the issue (adding a chip value by pressing the ENTER key works fine).

**Comment by smolinari** [comment]
Not sure what changed, but this seems to work now. 

https://codepen.io/smolinari/pen/KOaqvw

Scott

**Comment by leob** [comment]
Fantastic!

So the trick was to call "this.$refs.myChipInput.updateInputValue('')" ... where did you get that from, is that documented somewhere in the Quasar docs? by the way on a different note, I see that internally Quasar is now coded using Vue "render functions" instead of Vue templates ...

Oh and by the way, @keyup.tab.native didn't work for me, I had to change that to @keydown.tab.native ...

**Comment by leob** [comment]
Fantastic! Thanks a lot for the quick solution.

So the trick was to call "this.$refs.myChipInput.updateInputValue('')" ... where did you get that from, is that documented anywhere in the Quasar docs? By the way on a different note, I see that internally Quasar is now coded using Vue "render functions" instead of Vue templates ...

Oh and by the way, @keyup.tab.native didn't work for me, I had to change that to @keydown.tab.native ...

**Comment by smolinari** [comment]
I got it from the API in the docs. 

https://quasar.dev/vue-components/select#undefined

Scott

**Comment by leob** [comment]
Ouch, how could I have overlooked that ... the docs are simply superb, the best I've seen, I just want you to know that!
