### ISSUE TITLE
[V1] high cpu from QImg spinner

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#3868]
### Software version

Quasar:
@quasar/app (v1+ only): beta.16
OS: OSX
Node:
NPM:
Browsers: all
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
In working on a project, I noticed my fan coming on and high cpu and went back to adding `window.onanimationiteration = console.log` for a bit which showed ongoing AnimationEvent's  and I realized it is from a QImg I have in the footer while its hidden because the src is null since it had not been set. Made me wonder if possibly the spinner for QImg should not be shown unless the src is a string. What do you think?

### What were you expecting?
No cpu spike

### What steps did you take, to get the error?
I had a QImg whose src was null.

**Comment by rstoenescu** [comment]
Improvements & fixes will be available in beta.19
