### ISSUE TITLE
List botom borders without <hr> tag

### ISSUE THREAD

**Issue by mrapogee** [quasarframework/quasar#387]
Hey, awesome work here! So much functionality.

The docs recommend using `<hr>` outside the element to add bottom borders to list items. This is pretty inconvenient, because if you want to use `v-for` you need to use a template and you need to add a conditional to the last element so you don't have a border at the end. 

Could a class be added that adds the border to each element?

**Comment by rstoenescu** [comment]
Search for "Delimiter within Items": http://quasar-framework.org/components/list.html

```html
<div class="list item-delimiter">
  <div class="item" v-for="n in 3">
    <div class="item-content">
      List Item
    </div>
  </div>
</div>
```

**Comment by mrapogee** [comment]
Awesome! Sorry I missed that. Thank you for the info.
