### ISSUE TITLE
feature request: q-select with q-scroll-area instead of native scroll bar.

### ISSUE THREAD

**Issue by piecesnbits** [quasarframework/quasar#3871]
would be nice to have custom scroll bars in the q-select component.
![image](https://user-images.githubusercontent.com/44613132/55983494-902c0100-5c9b-11e9-865e-83949c45742c.png)

**Comment by piecesnbits** [comment]
btw would be also nice if v0.17 receives this update too :-)

**Comment by oskarmaxa** [comment]
Hi, has this been considered? Even if a custom look for select scrollbars consistent with scroll areas can be hacked together with CSS, at least for Webkit browsers (see #5993), the restyled scrollbar still takes up space and is constantly visible, unlike scroll area's which is overlaid and appears only on hover.

Not sure how feasible it is, but having an option for consistent customized scrollbars across an entire quasar app would be great.
