### ISSUE TITLE
QBreadcrumbs "artifacts" 

### ISSUE THREAD

**Issue by colo** [quasarframework/quasar#3872]
### Software version
quasar version: v1.0.0-beta.15
Node: v8.11.3
NPM: 5.10.0

On QBreadcrumbs.render function there is a for ...in loop

```javascript
    for (const i in node) {
      const comp = node[i]
```

that works just fine with stock Quasar.

But including in your project a library like **mootools**, I guess because modifies Array.prototype (I know, it shouldn't), or because "for ...in" indexes aren't guarateed to be in consistent order if modified while modified, as stated on:

[MDN for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

*Given that for...in is built for iterating object properties, not recommended for use with arrays, and options like Array.prototype.forEach() and for...of exist, what might be the use of for...in at all?*

Breadcrums render with "artifacts" at the end like:
![quasar-breadcrums-artifacts](https://user-images.githubusercontent.com/137627/55988723-0409e180-5c7b-11e9-8ebf-43ef856f4bf5.png)

But replacing the "for...in" with a "for..of" like 

```javascript
   for (const i of node) {
      const comp = i
```
[MDN for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)

Eveything render just fine:
![quasar-breadcrums-fixed png](https://user-images.githubusercontent.com/137627/55988831-49c6aa00-5c7b-11e9-946a-6bed26a006c7.png)

From MDN:
*The for...in statement iterates over the enumerable properties of an object, in an arbitrary order.*

*The for...of statement iterates over values that the iterable object defines to be iterated over.*

**As a final note Quasar v1 beta is astonishing!! Keep up the good work!!**

**Comment by rstoenescu** [comment]
Hi,

for..of would require a polyfill, so forEach() is better.
Will be available in beta.17.
