### ISSUE TITLE
Putting anything in Quasar Config->build->env causing a crash

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#3873]
### Software version
Quasar:

Operating System - Darwin(18.2.0) - darwin/x64
NodeJs - 11.3.0

Global packages
  NPM - 6.7.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.16 -- High performance, Material Design 2, full front end stack with Vue.js 
  @quasar/app - 1.0.0-beta.16 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

### What did you get as the error?
```js
QTabs.js:331 Uncaught SyntaxError: Unexpected token ,
    at Object../node_modules/quasar/src/components/tabs/QTabs.js (app.js:7042)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (import-quasar.js?0b67:1)
    at Module../.quasar/import-quasar.js (app.js:950)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (app.js?9992:1)
    at Module../.quasar/app.js (app.js:915)
    at __webpack_require__ (app.js:767)
```

### What were you expecting?
`process.env.newVar` to be in available in app

### What steps did you take, to get the error?
I am trying to put a var "newVar"  into `process.env` as explained in the documentation [Example setting env for dev/build](https://v1.quasar-framework.org/quasar-cli/quasar-conf-js), but the moment I put anything in quasar.config.build.env eg: 
```js
{
  build: {
    env: {
       newVar: 'new var content'
    }
  }
}
```
I get the above error in the browser. The build process works well, but the browser will just throw that error and the app won't go any further.

however if I do: 
```js
{
  build: {
    env: {
       newVar: JSON.stringify('new var content')
    }
  }
}
```
it works as expected. Is there a reason why the values should be stringified? I so, won't it be a convenience to just do that internally and allow passing of normal obj to env. It's so annoying when you go through it the first time and trying to figure out what's especially since the documentation doesn't warn of the syntax and issue. It's also not convenient  to write.

**Comment by rstoenescu** [comment]
Hi,

We inherit this from [webpack.DefinePlugin](https://webpack.js.org/plugins/define-plugin/). Read more on webpack.DefinePlugin's doc page to understand its subtleties.

One of its ideas is that it replaces the value "as is". So there's a difference between `{ env: { VAR: 'something' } }` and `{ env: { VAR: JSON.stringify('something') } }` (or the equivalent: `{ env: { VAR: '"something"' } }`). The first just places `something` into the code (which will most likely be interpreted by JS parser as a variable or expression name, while the latter places the String `"something"` into the code. Major difference with the two approaches when the following code goes through DefinePlugin: `if (VAR === 'something')`. First approach transpiles into `if (something === 'something')` while second approach transpiles into `if ('something' === 'something')`. Notice the quotes as it makes a world of difference. This is an example why this can't be automated as it would not be possible to allow all use cases.

I beg to differ on the Quasar docs not warning about [this](https://v1.quasar-framework.org/quasar-cli/quasar-conf-js#build-Property):
<img width="823" alt="Screenshot at Apr 12 00-55-51" src="https://user-images.githubusercontent.com/4665641/55995697-ddb96580-5cbd-11e9-8378-554a7b24dcba.png">

I must admit the errors when you don't take this into account can sometimes look cryptic, but they are being reported by Webpack and are out of Quasar's reach.

**Comment by hawkeye64** [comment]
@emahuni You may also be interested in using one of these app extensions:
1) https://github.com/quasarframework/app-extension-dotenv
2) https://github.com/quasarframework/app-extension-qenv

**Comment by LiamKarlMitchell** [comment]
```js
// config/envparser.js
const parsedEnv = require('dotenv').config({ path: process.env.DOTENV_CONFIG_PATH })
// console.log('parsed env:')
// console.log(parsedEnv)
// console.log('process env:')
// console.log(process.env)
// process.exit(1)

// webpackDefinePlugin brings in the enviroment variable replacement as as-is replacements.
// See: https://github.com/quasarframework/quasar/issues/3873
// So we need to stringify strings putting into the Quasar config enviroment variables.
module.exports = function () {
  var output = {}
  // Let's stringify our variables
  for (key in parsedEnv.parsed) {
    if (typeof parsedEnv.parsed[key] === 'string') {
      output[key] = JSON.stringify(parsedEnv.parsed[key])
    }
  }
  console.log(output)

  return output
}
```

Usage example.
In quasar.conf.js
```js
// import at the top.
const envparser = require('./config/envparser')

// In build: part
// ...
  build: {
  // ...
   env: envparser(),
  }
```

**Comment by DeroSavage** [comment]
@LiamKarlMitchell I like this approach, but unfortunately it seems that the require statement is not working at all. I can change whatever i want inside envparser and it don't force quasar to reload. You have any advice?
