### ISSUE TITLE
[V1 - Request] v-touch-hold-end directive

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3876]
I need to have a way to detect `'touchend'` after the v-touch-hold function has fired.

### My use case:
Currently we have a way to use `v-touch-hold` to do something after x ms.
In my case I am using it to add a class "is elevated"
```html
v-touch-hold:200.mouse.stop.prevent="_ => elevated = true"
```
IF the **user starts dragging**:
- I use `v-touch-pan` to translate the element and after the pan event I can manually set `elevated = false`.

IF the **user decides not to drag**:
- I need to have a way to detect `'touchend'` to turn `elevated = false` again.

**Comment by rstoenescu** [comment]
Hi,

This is a very special case and should be handled without the v-touch directives. Simply add touchstart, touchmove, touchend event listeners.

**Comment by mesqueeb** [comment]
In case anyone comes looking here.

To anyone who wants to detect `touchend` after `v-touch-hold`:

(eg. create a hover effect on `v-touch-hold` and remove again on `touchend`)

What I learned:

### Don't
- add `touchstart` or `click` or `mousedown` events when you also use Quasar's `v-touch-hold`.
  - because adding additional `touchstart` or `click` or `mousedown` events will cause many problems and sometimes break the quasar one.

### Do
- use traditional `v-touch-hold.mouse` to apply your desired initial effects
- set up extra manual listeners **only to detect `touchend` and `mouseup`!**

Eg.
```js
created () {
    this.$el.addEventListener('mouseup', this.stopHovering)
    this.$el.addEventListener('touchend', this.stopHovering)
}
```
This code will allow your vue component to trigger a function called `stopHovering` where you can write your logic to remove any classes that make an element look like it's "hovering".

In case you also have a `v-touch-pan` you need to additionally call `stopHovering` on `isFinal` of your pan handler. (see the [TouchPan documentation](https://v1.quasar-framework.org/vue-directives/touch-pan#Installation).

**Comment by nothingismagick** [comment]
Can you add this advice to the docs? Hate to lose it here...

**Comment by mesqueeb** [comment]
@nothingismagick made a PR #4529
