### ISSUE TITLE
[v1] adding quasar to webpack externals

### ISSUE THREAD

**Issue by manelclos** [quasarframework/quasar#3879]
### Software version

Quasar: 1.0.0-beta.16
@quasar/app (v1+ only): 1.0.0-beta.16
OS: Max OS X
Node: 11.0.0

Hi, I'm trying to get quasar out of my library bundle:
```
     extendWebpack (cfg) {
          cfg.externals = [
            'quasar',
            'vue',
            'vuex'
          ]
    }
```

When running `quasar build` Vue and Vuex are not included in the min.js file, but quasar is. Using Webpack Bundle Analyzer, I can see `node_modules/quasar/src` inside `src` which is strange, like quasar being part of my code.

Any hints appreciated.

**Comment by manelclos** [comment]
Found that the included code from quasar is because of `import { Notify } from 'quasar'`, we have changed this import and are using `Vue.prototype.$q.notify()` and now the crash is gone, but there are still other two javascript files included: `Platform.js` and `open-url.js`.

**Comment by manelclos** [comment]
Finally got rid of all the quasar code, but we depend on using the `quasar.conf.js` file for importing components. If we try using `import { QBtn } from 'quasar'`, we see the code being attached to lib.js, this is, 'quasar' in externals seems to have no effect.

**Comment by rstoenescu** [comment]
Also set `quasar.conf.js > framework: { all: true }` then your externals containing 'quasar' will work as you intended.

Explanation: If `all: true` is not present, then Quasar is imported differently (using babel import statement transformations pointing to quasar/src) so that a true tree shaking can occur. Otherwise, "quasar" is pointed towards `quasar/dist/quasar.esm.js` and so specifying `quasar` in the externals list will have effect.

Besides the point and for my own curiosity only, I'd be interested in knowing what you are building since you need specifying these externals :)

-Razvan

**Comment by manelclos** [comment]
Hi Razvan, good explanation, thanks a lot.

We are building a geoportal. It was built with VueJS and several other libraries and we just rebuilt it using Quasar v1. Nice cleanup. We customise it for different customers, so in the past the best path seemed to have it as a library. Hopefully we found how to do the same with the Quasar build system. We export the high level components into a library for reuse: https://github.com/giscube/giscube-geoportal-vuejs/blob/quasar/src/lib.js

**Comment by nothingismagick** [comment]
Or you could consider making an app-extension...

https://v1.quasar-framework.org/app-extensions/introduction

**Comment by manelclos** [comment]
Hi @nothingismagick, I read a guide on app-extension, but haven't got the time to experiment. I just tried to mimic existing webpack configuration into the Quasar build system: https://github.com/giscube/giscube-geoportal-vuejs/blob/quasar/quasar.conf.js#L102

It would be great to know if you think that a "lib" mode for building the lib would be possible using an app-extension.

**Comment by nothingismagick** [comment]
Yes, this is explicitly one of the purposes for which we created the app
extension system.
