### ISSUE TITLE
v-link calling route redirect function

### ISSUE THREAD

**Issue by oswaldomilet** [quasarframework/quasar#388]
`<button v-link="'/logout'">Logout</button>`

```
routes: [
    ...
    {
      path: '/logout',
      redirect: to => {
        console.log('this function is being called even without click on button')
        return '/'
      }
    }
  ]
})
```

If I use default router.push() this behavior doesn't happen:
`<button @click="$router.push('/logout')">Logout</button>`

**Comment by rstoenescu** [comment]
`v-link` in your case calls `$router.push()`... so it's the same thing. Please reopen with a more detailed case. Thanks!

**Comment by oswaldomilet** [comment]
If I start my application, the console.log() line is immediately called even if button was not clicked, what doesn't happens if I use $router.push(), so I believe it's NOT the same thing.

So, guess I gave you all details you need.

**Comment by rstoenescu** [comment]
@oswaldomilet `v-link` adds a 'click' event listener and does a $router.push(). This is what I mean. https://github.com/quasarframework/quasar/blob/dev/src/vue-directives/link.js#L19-L28

Do you have a repo I can take a look at?

**Comment by rstoenescu** [comment]
Also, use `<router-link>` for your case. It's faster & more efficient.

**Comment by oswaldomilet** [comment]
I think it's a Vue bug, cause when I switched from v-link to router-link the wrong behavior came back, so I'll keep $router.push()

**Comment by rstoenescu** [comment]
Can you create a repo so I can reproduce pls? Simple, barebone one. I am very interested to see what's going on with Vue router. I think it's good we do a Vue router PR on this. But I can't reproduce. So help?
