### ISSUE TITLE
[V1] QSlider long label display error

### ISSUE THREAD

**Issue by MechJosh0** [quasarframework/quasar#3887]
### Software version
Quasar: v1.0.0v1.0.0-beta.16
Browsers: Chrome

### JsFiddle
https://codepen.io/mechjosh0/pen/VNMYRz?&editable=true&editors=101
Forked from the documentation: https://v1.quasar-framework.org/vue-components/slider#Example--Custom-label-value

### What did you get as the error?
The badge for displaying the label is warped.
![image](https://user-images.githubusercontent.com/11144798/56092103-8b3f9b00-5eaf-11e9-8a3c-7b1cb8c2fd1e.png)

### What were you expecting?
The entire label should be on a single line and readable.

### What steps did you take, to get the error?
```js
:label-value="value + ' pixels'"
```
The `label-value` key must have 5 characters including 1 space to cause the display error.

**Comment by rstoenescu** [comment]
Fix will be available in beta.17
