### ISSUE TITLE
LocalStorage problem when cookies are disabled

### ISSUE THREAD

**Issue by 123mitnik** [quasarframework/quasar#3888]
when Cookies are disabled inside the browser and app is using localstorage the page can't load and inside the console you can see

> quasar.esm.js?b178:6 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

![image](https://user-images.githubusercontent.com/1234337/56092928-54777e00-5ecb-11e9-93c5-fed2d318fee3.png)

![image](https://user-images.githubusercontent.com/1234337/56093024-6574bf00-5ecc-11e9-9061-26ca0951b55a.png)

Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 11.3.0

Global packages
  NPM - 6.9.0
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.3
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.11 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.12 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.9 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.2 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.29.6 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.2.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.1.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

**Comment by rstoenescu** [comment]
Fixed LocalStorage and SessionStorage guard.
Will be available in beta.17. Thanks for reporting!

**Comment by muoimouse** [comment]
[i](url) have same error and i using quasar 17
