### ISSUE TITLE
Changing variables in app.variables.styl does not do anything?

### ISSUE THREAD

**Issue by 7ammer** [quasarframework/quasar#389]
I've changed a few variables to the `src/themes/app.variables.styl` file however upon page reload or re-running `quasar dev` I see no change. Am I missing something here?

I would assume that the css should be rebuilt on file edit but webpack doesn't detect a change.

**Comment by rstoenescu** [comment]
Check top of `/src/main.js` (which is the entry point of your app):

```js
// === DEFAULT / CUSTOM STYLE ===
// WARNING! always comment out ONE of the two require() calls below.
// 1. use next line to activate CUSTOM STYLE (./src/themes)
// require(`./themes/app.${__THEME}.styl`)
// 2. or, use next line to activate DEFAULT QUASAR STYLE
require(`quasar/dist/quasar.${__THEME}.css`)
// ==============================
```

You need to uncomment 1. and comment 2.

**Comment by rstoenescu** [comment]
Also for reference: http://quasar-framework.org/guide/quasar-theming.html#Build

**Comment by 7ammer** [comment]
That did it, cheers.
