### ISSUE TITLE
[v1] Submenus not possible on context menu

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#3890]
See Pen:
https://codepen.io/tomers-the-encoder/pen/YMrOdV?&editable=true&editors=101

Tested on Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
@tomers The problem is with your usage. You're using `auto-close` with context-menu. Which means any click, anywhere will close the menu.

Also, doesn't makes sense to also use `touch-position` along with `context-menu`, as this is implicit.
