### ISSUE TITLE
[v1][Feature Request] q-btn-dropdown: Ability to disable split button but not dropdown

### ISSUE THREAD

**Issue by fancellu** [quasarframework/quasar#3892]
https://forum.quasar-framework.org/topic/3421/q-btn-dropdown-how-do-i-disable-it-for-click-but-not-its-drop-down

https://codepen.io/fancellu/pen/YMrmXy

For example, the state of the dropdown model might making submitting undesirable, hence I would like to disable the button, but still allow access to the dropdown, so that it can be changed. Currently disabling the button disables both parts, so can't access the dropdown model in order to make submitting valid

**Comment by rstoenescu** [comment]
Added "disable-main-btn" and "disable-dropdown" Boolean props.
Will be available in beta.18
