### ISSUE TITLE
[v1.17] Can't compile

### ISSUE THREAD

**Issue by KPKoch** [quasarframework/quasar#3898]
### Software version

Operating System - Linux(4.15.0-47-generic) - linux/x64
NodeJs - 10.8.0

Global packages
  NPM - 6.9.0
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.17 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.17 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.4 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.2.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### What did you get as the error?
After encountering the following problem, I removed all used extensions, but with the same result:
When trying dev or build, CPU spikes for a a while and then:When trying dev or build, CPU spikes for a a while and then I get the following stack trace. Someone any idea?

<--- Last few GCs --->

[20197:0x33f7cb0]   685856 ms: Scavenge 1365.1 (1435.1) -> 1352.7 (1437.1) MB, 11.9 / 0.0 ms  (average mu = 0.361, current mu = 0.384) allocation failure 
[20197:0x33f7cb0]   685926 ms: Scavenge 1366.8 (1437.1) -> 1354.3 (1439.6) MB, 9.0 / 0.0 ms  (average mu = 0.361, current mu = 0.384) allocation failure 
[20197:0x33f7cb0]   685991 ms: Scavenge 1368.4 (1439.6) -> 1356.0 (1442.6) MB, 10.0 / 0.0 ms  (average mu = 0.361, current mu = 0.384) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2dc5d3b041bd]
Security context: 0x2d1801a9e789 <JSObject>
    1: doResolve [0x2345c40df7d1] [/var/www/html/eu.greatreef.www/client/node_modules/enhanced-resolve/lib/Resolver.js:~189] [pc=0x2dc5d437906a](this=0x24be0dcaa019 <Tapable map = 0x390795d06981>,hook=0x24be0dca6629 <Object map = 0x390795d0a291>,request=0x30f3b5b1fb11 <Object map = 0x390795d0fb99>,message=0x1c2525f02201 <null>,resolveContext=0x30f3b5b1fa39 <...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8b8210 node::Abort() [node]
 2: 0x8b825c  [node]
 3: 0xac1d1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xac1f38 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeb11f2  [node]
 6: 0xebd14a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 7: 0xebdab4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xec03e5 v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 9: 0xe888c4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
10: 0x112a2ae v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
11: 0x2dc5d3b041bd 
Aborted (core dumped)

### What steps did you take, to get the error?
yarn upgrade
quasar dev

/client$ quasar dev    

 Dev mode.......... spa
 Pkg quasar........ v1.0.0-beta.17
 Pkg @quasar/app... v1.0.0-beta.17
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8083)... +5ms
 app:webpack Extending SPA Webpack config +524ms
 app:generator Generating Webpack entry point +9ms
 app:dev-server Booting up... +3ms

  SPA ██████████████            building [55%] 379/428 modules 49 active

**Comment by nothingismagick** [comment]
One thing I can recommend is to debug with the build.
```
$ quasar build -m spa --debug
```

**Comment by nothingismagick** [comment]
Two other notes:
- your node version is out of date - it should be 10.15.3
- it seems to me that you are running several other instances of quasar (hence the 8083) - consider shutting them down because you may actually be running out of memory / swap.

**Comment by KPKoch** [comment]
Thanks for the help.

The 8083 is indeed the only one and "custom confed" for historic reasons.

Operating System - Linux(4.15.0-47-generic) - linux/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

I updated node and tried with the command you wrote. Sadly no change. build or dev, it gets stuck kind in the middle. Any support how to debug welcome.

**Comment by nothingismagick** [comment]
Did you build your app's local node modules with npm or yarn? If the former, remove the entire node_modules folder and run `yarn`.

**Comment by KPKoch** [comment]
global node was installed with: nvm install 10.15
local, I removed it and used yarn install.
Same result, it still hangs somewhere - I'm relly eager to know where. It seems to vary around something.
SPA █████████████             building [49%] 325/389 modules 64 active

**Comment by nothingismagick** [comment]
The next thing to triage are your boot files. I would remove them from your quasar.conf.js one by one in the hopes of isolating it. My guess is that you have a cyclical reference in there somewhere, but without seeing your repository its just kind of hard to tell.

**Comment by nothingismagick** [comment]
Something else that can happen is if you are using the backtick notation to render js values - and forget to close the backtick like:

```
  myMethod () {
    return `Something ${stupidOrSmart}
  }
```

**Comment by KPKoch** [comment]
I rolled back for testing, first quasar - no luck, then also quasar/app, both to 1.16 and
DONE  Compiled successfully in 21303ms                                                                                                                                                            8:54:33 AM


 N  App dir........... /var/www/html/eu.greatreef.www/client
    App URL........... http://localhost:8083/
    Dev mode.......... spa
    Pkg quasar........ v1.0.0-beta.16
    Pkg @quasar/app... v1.0.0-beta.16
  
 app:dev-server Opening default browser at http://localhost:8083/ +22s

**Comment by KPKoch** [comment]
I rolled back for testing, first quasar - no luck, then also quasar/app, both to 1.16 and
DONE Compiled successfully in 21303ms 8:54:33 AM

N App dir........... /var/www/html/folder/client
App URL........... http://localhost:8083/
Dev mode.......... spa
Pkg quasar........ v1.0.0-beta.16
Pkg @quasar/app... v1.0.0-beta.16

app:dev-server Opening default browser at http://localhost:8083/ +22s

**Comment by nothingismagick** [comment]
That doesn't sound good. Can you please look at the release notes for both modules and see if you have a component / plugin that is being referenced there?

https://github.com/quasarframework/quasar/releases

**Comment by KPKoch** [comment]
I do have some problems to answer that. The quick answer would be: most of them.
I fostered the project from the early 0.13 days, so I do have "some" boot configs and also most of the components in use and not "steamlined" it as much as it could be - so the conf and files are a bit cluttered. Until now I was able to adapt to each update including v0.13 -> v1.16.

Any ideas, which information would be most helpful?

**Comment by KPKoch** [comment]
App URL........... http://localhost:8083/
    Dev mode.......... spa
    Pkg quasar........ v1.0.0-beta.17
    Pkg @quasar/app... v1.0.0-beta.16
  
 app:dev-server Opening default browser at http://localhost:8083/ +22s


So, I assume it is the app update.

**Comment by nothingismagick** [comment]
Yeah, that helps me narrow it too. My first guess is stylus imports.

Are you importing the quasar variables into your SFC <style> templates?

**Comment by nothingismagick** [comment]
Also: Are you using webpack chain in your quasar.conf.js ?

**Comment by KPKoch** [comment]
uhm, can you give me an example what to look for?
quasar.conf.js returns also:
 css: [
      'quasar.variables.styl'
    ],

//which is currently only filled with comments and no active code, replaced by 
config: {
        brand: {
          primary:
in conf.

  build: {
      scopeHoisting: true,
      vueRouterMode: 'history',
      // gzip: true,
      // analyze: true,
      // extractCSS: false,
      // useNotifier: false,
      extendWebpack (cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules|quasar|src)/
        })
        cfg.module.rules.push({
          test: /\.(gql|graphql)$/,
          loader: 'graphql-tag/loader'
        })
      }
    },

(graphql is a left over, replaced by my own API implementation)

**Comment by nothingismagick** [comment]
with stylus i mean are you importing the quasar stylus variables anywhere in files like App.vue

**Comment by nothingismagick** [comment]
Its good to know that this isn't webpack.chain related.

**Comment by nothingismagick** [comment]
Have you tried disabling all of your boot files?

**Comment by KPKoch** [comment]
Upgrading and testing. brb

**Comment by KPKoch** [comment]
sadly, even with an empty boot:[] it'll get stuck.

**Comment by KPKoch** [comment]
found the reason! 
WITHOUT (in quasar.conf.js): 
css:[
'quasar.variables.styl'
]
it works. Everything else didn't improve.
css/quasar.variables.styl content is: 
// Quasar Stylus Variables
// --------------------------------------------------
// To customize the look and feel of this app, you can override
// the Stylus variables found in Quasar's source Stylus files.

// Check documentation for full list of Quasar variables

// It's highly recommended to change the default colors
// to match your app's branding.
// Tip: Use the "Theme Builder" on Quasar's documentation website.

//$primary   = #ababab
//$secondary = #ababab
//$accent    = #ababab
//$positive  = #ababab
//$negative  = #ababab
//$info      = #ababab
//$warning   = #ababab

(colors changed)
Somehow this was enough to stale / break the build.
 css: [
      //'quasar.variables.styl'
    ],
works

**Comment by KPKoch** [comment]
And many thanks for your time and help. I am not that deep into node that I know why this has happend or how special this problem is to my setup, but as early adopter I am always glad if I can help.

**Comment by nothingismagick** [comment]
You're welcome. I know we just changed the quasar.variables approach - so stylus stuff was my hunch. Please close this issue if you are satisfied.

**Comment by KPKoch** [comment]
And many thanks for your time and help. I am not that deep into node that I know why this has happend or how special this problem is to my setup, but as early adopter I am always glad if I can help.

regarding of import of quasar stylus vars, I think it is only within quasar.conf.js. Nothing alike in App.vue, just normal use in template code like color="primary".
Also I am currently do define them in quasar.conf.js directly for the reason jetbrains color picker works there ;)
config: {
brand: {
primary: '#ababab',
secondary: '#ababab',
accent: '#ababab',

      positive: '#ababab',
      negative: '#ababab',
      info: '#ababab',
      warning: '#e6e600'
    }
  },


Again, thanks for your great support. If my project will have success, I'll contribute more.
