### ISSUE TITLE
[v1].beta17 iOS QHeader does not respect addressbar

### ISSUE THREAD

**Issue by carlesar** [quasarframework/quasar#3899]
### Software version

Quasar: 1.0.0-beta.17
@quasar/app (v1+ only): 1.0.0-beta.17
OS: Debian 4.9.144-3 x86_64 GNU/Linux
Node: 9.11.2
NPM: 5.6.0
iOS: iPhone 6/7/8
Any other software related to your bug:

### What did you get as the error?
After creating a new quasar project with the comand: `quasar create demo -b dev`. And compile it with `quasar build -m cordova -T ios`. The app launches successfully but the QHeader component is not respecting the addressbar, as seen in the picture.
This is happening with all iphone versions that do not have notch. With iPhone X is ok. Maybe that's the problem.

![image](https://user-images.githubusercontent.com/20858599/56194552-899ee000-6033-11e9-9414-ab53f8a4ead4.png)

**Comment by nothingismagick** [comment]
Also note: this issue was reported with iOS 12.1 - also @steveclarke mentioned something similar

**Comment by steveclarke** [comment]
I have a couple of iOS quirks regarding header and footer. I have a replicable issue. Should I do it up as a separate report?

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in beta.18.
