### ISSUE TITLE
Columns added to Data Table are disabled by default

### ISSUE THREAD

**Issue by oraknabo** [quasarframework/quasar#390]
I'm initializing a Data Table with an empty array, then replacing the data from an API call and building the column list based on the incoming data. Everything works fine but all of the new columns are disabled unless I set columnPicker true and manually activate each one after everything loads. 

Is there a boolean field that can be set (like filter & sort) in the column definition that will force it to be visible at creation?

**Comment by rstoenescu** [comment]
Will add a field for this very son. I think there's another issue raised on this as well. Will close it if it's duplicate.
Until the new field is available just v-if your grid and display a loading message or something.

**Comment by oraknabo** [comment]
Thanks. I found this https://github.com/quasarframework/quasar/issues/246 similar issue, maybe that's what you're thinking of.

My table data is definitely changing properly, it's just that I have to manually turn on each new column.

**Comment by jrandall16** [comment]
@rstoenescu I'm getting the same problem on the beta branch. The workaround I came up with for now was this: (test is the q-datatable ref)
```for (let col of this.columns) {
     columnSelection.push(col.field)
}
this.$refs.test.columnSelection = columnSelection```

they only become disabled if not initialized with the component, if the component is initialized with the columns data they are all enabled.

**Comment by rstoenescu** [comment]
DataTable revamp is in progress for v0.15. It will include this. Thanks for your patience.

**Comment by rstoenescu** [comment]
Closing as it's ready in future v0.15.
