### ISSUE TITLE
[v1][Feature Request]q-stepper: Content icon => add accept numbers

### ISSUE THREAD

**Issue by MaxCrasy** [quasarframework/quasar#3903]
https://codepen.io/leonardo-morais/pen/axELam?editors=1011

I have 10 more steps and the icon can't overpass number 9, I already conversed with @Denjell (EN/DE-eu)

Maybe change de Content Icon in to a Template or add another type of Content(index)?

**Comment by rstoenescu** [comment]
Step component new prop (String/Number): `prefix` (max 2 characters shown instead of an icon for each step’s header). This will be displayed if the step is not currently being edited and it isn’t marked with error or as “done”.

Will be available in beta.22
