### ISSUE TITLE
[v1] QInput type="file" not working in Microsoft Edge

### ISSUE THREAD

**Issue by mountash** [quasarframework/quasar#3907]
### Software version

Quasar: v1.0.0-beta.17
OS: Windows_NT(10.0.17134) - win32/x64
NPM - 6.4.1
yarn - 1.15.2
Browsers: Microsoft EdgeHTML 17.17134
Any other software related to your bug:

### JsFiddle

Can be reproduced in docs https://v1.quasar-framework.org/vue-components/input

### What did you get as the error?
Selecting any file results an empty input
### What were you expecting?
Filename appears in input
### What steps did you take, to get the error?
Open https://v1.quasar-framework.org/vue-components/input in Edge
Find any input with type="file"
Select file

**Comment by rstoenescu** [comment]
Hi,

Thanks for opening this ticket. Pushed a commit which fixes usage when type="file". Will be available in beta.18. Please also read the explanation below which will be in next deployment of docs:

<img width="559" alt="type-file" src="https://user-images.githubusercontent.com/4665641/56314200-0da0b700-615d-11e9-8205-f7d61e108fac.png">
