### ISSUE TITLE
Docs reference incorrect function name "Utils.format.humanSize"

### ISSUE THREAD

**Issue by adam-zpos** [quasarframework/quasar#391]
On the formatters page, http://quasar-framework.org/api/js-utils.html#Formatters, the function `Utils.format.humanSize` was causing compilation errors. Upon reading the source, it would appear this function should be named `Utils.format.humanStorageSize`

**Comment by rstoenescu** [comment]
Pushed patch on the doc site. Will be visible for next Quasar version. Thanks for reporting this!
