### ISSUE TITLE
[v1][QBtn][iOS] submit button tap does not work

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#3911]
### Software version

Quasar: v1.0.0-beta.17
Browsers: Safari
iOS:12.2

### JsFiddle

https://v1.quasar-framework.org/vue-components/button#Controlling-the-button-for-form-submission

### What did you get as the error?
`QBtn` with type `submit` does not fire the `submit` event of the form when tapped. It works when using the iOS keyboard to submit the form though.

### What were you expecting?
When submit button is tapped, `submit` event should fire.

**Comment by rstoenescu** [comment]
Fix will be available in beta.18.
