### ISSUE TITLE
[v0.17][doc] QTable rowsPerPageOptions

### ISSUE THREAD

**Issue by kamekazemaster** [quasarframework/quasar#3912]
Please add some documentation also for `rowsPerPageOptions` in `QTable`. I had to look it up in the source code itself ;)

**Comment by rstoenescu** [comment]
Hi. Use the API card :)

<img width="838" alt="rows-per-page-options" src="https://user-images.githubusercontent.com/4665641/56368793-d257c400-6200-11e9-999f-7e6992eb4ee8.png">

**Comment by nothingismagick** [comment]
Is this about v0.17.x or v1.0.0-beta.17?

**Comment by kamekazemaster** [comment]
@nothingismagick As I state in the title it's about v0.17.x ;)

@rstoenescu You are right for the v1 branch/docs. To be honest now I found the option also in the docs... I just overlooked them sorry! Here they are:
![image](https://user-images.githubusercontent.com/3775931/56374614-e81ab880-6203-11e9-900c-16851c39b497.png)

**Comment by nothingismagick** [comment]
But now I am confused.
