### ISSUE TITLE
[v1][Feature Request] q-input: Ability to configure 'standout' prop style

### ISSUE THREAD

**Issue by nachodd** [quasarframework/quasar#3914]
The main idea is to add an 'easy' way to configure 'standout' input style. I get the idea about the 'standout' prop, but I think that sometimes the black backgorund is a little bit.. ugly? (or doesn't align with the rest of the UI)

I manage to do this by CSS:
[https://codepen.io/nachodd/pen/pBawGE](https://codepen.io/nachodd/pen/pBawGE)

Maybe by passing some value to standout prop, it'll be configurable.

**Comment by rstoenescu** [comment]
QInput/QSelect/QField -> standout is now a Boolean or String. When it is String, it can specify CSS classes (example: "bg-primary text-white") that apply when focused.

Will be available in beta.19

**Comment by engtiago** [comment]
> QInput/QSelect/QField -> standout is now a Boolean or String. When it is String, it can specify CSS classes (example: "bg-primary text-white") that apply when focused.
> 
> Will be available in beta.19

Not working, i can't use text-dark for example

**Comment by rstoenescu** [comment]
Oh it's working.. It's for the focused state. If you're looking for the unfocused state then maybe "input-class" prop is for you?
