### ISSUE TITLE
[v1]QSelect showing dialog not selectable sometimes on mobile device

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#3915]
Quasar: v1.0.0-beta.17
@quasar/app (v1+ only):v1.0.0-beta.18

### What did you get as the error?
QSelect showing dialog on mobile is still not working properly，not selectable sometimes
### What steps did you take, to get the error?
Test with real mobile devices： https://v1.quasar-framework.org/vue-components/select

**Comment by rstoenescu** [comment]
Can you pinpoint a specific example? What mobile device (iOS, Android?) and which version.

**Comment by pdanpdan** [comment]
Can you please offer some more details:
- what kind of select
- on what mobile device (type, iOS version :))
- what is not working

**Comment by yuanyesong** [comment]
When I'm ready to record a gif animation for showing the bug, i can't reproduce it, sorry(⊙︿⊙). I will report it if i reproduce the bug again.

**Comment by rstoenescu** [comment]
**Please reopen** when you have more data. And please answer the questions above. Thank you.
