### ISSUE TITLE
[v1] QInput within QDialog painting/scrolling issue

### ISSUE THREAD

**Issue by usu** [quasarframework/quasar#3919]
### Software version
Quasar: 1.0.0-beta.17
@quasar/app (v1+ only): 1.0.0-beta.18
OS: iOS 12.1.4
Browsers: Safari

### JsFiddle
https://jsfiddle.net/usuppiger/bhguktp5/19/

### What did you get as the error?
A bit difficult to explain/reproduce but I try.
1. Open the JSFiddle on iPhone. The Dialog should be small enough to trigger scroll bars.
2. Scroll the dialog a bit down (does not matter how much, but do not stay at the top)
3. Enter something in the input
4. The first character appears properly, the others appear as whitespace only (or sometimes the character appears partially)
5. Scroll a bit up down (triggers a repainting)
6. All the characters appear properly

Also works with deleting characters --> characters are not actually deleted until a repaint is triggered with scrolling

### What were you expecting?
All the entered character to appear immediately

Could only reproduce this on Safari on iOS. Works properly on Android and on Desktop.

Also: Works properly if QDialog is not scrolled at all.

**Comment by rstoenescu** [comment]
Hi,

Thank you for the effort put into describing the issue!
Unfortunately, there's nothing much that we can do from Quasar's perspective. This is a known bug for safari iOS folks but they seem to not fix it...
