### ISSUE TITLE
Context Menu broken in Firefox

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#392]
Hey, I was playing around with the components on the showcase site and noticed, that the "Context Menu" component is broken in Firefox.
When a user performs a right click, the conext menu appears shortly but does not stay. Only when the user presses the right mous button and hovers over the context menu it stays. When testing the same page on Chromium it does work with a single klick.
Also I noticed that when a context menu is already open and the user does perform a right click somewhere other on the site, the conext menu suddenly jumps to the upper left corner and stays there. My expected behavior would be that the context menu changes place to the new mouse position. The last error happend on Chromium and Firefox.

Page: [http://quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/context-menu](http://quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/context-menu)
Firefox: 51.0.1 (64-bit) - Linux
Chromium: 56.0.2924.87 (64-bit) - Linux

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting!

**Comment by a47ae** [comment]
Glad if it helps improving Quasar. Keep up the good work! :)

**Comment by rstoenescu** [comment]
Available in edge and future v0.13.2
