### ISSUE TITLE
[V1] CSS Q-Chip Square has incorrect border radius

### ISSUE THREAD

**Issue by cdnrg-rt** [quasarframework/quasar#3920]
Can be seen directly in the file
https://github.com/quasarframework/quasar/edit/dev/quasar/src/components/chip/chip.styl

![image](https://user-images.githubusercontent.com/18314457/56337515-8b16f800-615a-11e9-9338-fe51374abe90.png)

I'm guessing it was meant to be 0 like other components with square

**Comment by rstoenescu** [comment]
Hi,

No, it's actually correct from a design perspective. Making it 0 looks very ugly. `$generic-border-radius` is 4px, so close.

**Comment by cdnrg-rt** [comment]
Thanks @rstoenescu! I would then suggest we change the wording on the QChip API for square as it indicates the border-radius is removed.

![image](https://user-images.githubusercontent.com/18314457/56373250-6f8d0b00-61b5-11e9-8018-766f90149eb0.png)

**Comment by rstoenescu** [comment]
Done. Will be available in beta.18.
Thanks!
