### ISSUE TITLE
[v1] QInput doesn't check the native validation of the underlying input element

### ISSUE THREAD

**Issue by copying** [quasarframework/quasar#3921]
### Software version
Quasar: quasar@1.0.0-beta.17
OS: Ubuntu, Mac OS
Browsers: Firefox, Google Chrome, Safari, Vivaldi

### CodePen
https://codepen.io/anon/pen/eoMgwg?&editable=true&editors=101

### What did you get as the error?
Quasar validated values that are invalid for the type given and returns an empty string as value.

That happens because if the `input`'s value is invalid for its type, its value becomes an empty string.

### What were you expecting?
I'd expect the QInput to use the native validation on the underlying `input` element before validating the custom rules.

### What steps did you take, to get the error?
 - Open the [CodePen example](https://codepen.io/anon/pen/eoMgwg?&editable=true&editors=101)
 - Add a value that is not a number like `1.....2.....3.....4` (in some browsers you can only use a restricted set of characters but you should still be able use this value)
 - Click validate
 - In the notify you can see that quasar says it is a valid value (because the value becomes an empty string) but that the native validation fails

**Comment by rstoenescu** [comment]
Hi,

It's not meant to use .checkValidity() method. It's meant to validate against the rules you tell it to. So add a rule to check if input is a number along with the error message.

This would suffice:

```html
<q-input
  v-model.number="model"
  type="number"
  :rules="[
    val => !!val || 'Type a valid number'
  ]"
/>
```

**Comment by copying** [comment]
Hi,

Thank you for responding this fast :)

In my application I need to allow empty values because some fields are not required. It doesn't seem possible to differentiate them just by value (unless using the native validation).

The other solution is to not use the `type` prop and do manual validation of the value. This implies that, specially in phones, the input method may be way less convenient for the user.

PS: I just realized that using native validation would also check for the `required` attribute without changing anything else.
