### ISSUE TITLE
[v1] QTable (dense & selectable) scrollbar after selecting last row

### ISSUE THREAD

**Issue by adsultana** [quasarframework/quasar#3922]
### Software version
Quasar: 1.0.0-beta.17
@quasar/app (v1+ only): 1.0.0-beta.18
OS: Windows 7
Browsers: Chrome 73

### JsFiddle
https://jsfiddle.net/xfq6wzvu/

### What did you get as the error?
When the last item of a dense table is selected, the ripple effect caused by a click is larger than then height of the table row, causing a scrollbar to appear in the table. This does not occur when the first row of the table is selected.

### What were you expecting?
No scrollbar to appear in the table.

### What steps did you take, to get the error?
Select the last row of the table. When focus of the selecting checkbox is lost, the scrollbar disappears.

**Comment by mountash** [comment]
Created PR #3925

**Comment by mountash** [comment]
@rstoenescu there was an indent issue in a5d3b88
See PR #4038
