### ISSUE TITLE
[V1] - PWA Custom Service Worker on Dev

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#3928]
### Software version

Quasar:
@quasar/app (v1+ only):
OS:  Darwin(17.7.0) - darwin/x64
Node: 10.13.0
NPM - 6.4.0
yarn - 1.13.0
@quasar/cli - 1.0.0-beta.4
cordova - 7.1.0
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
I do not see the custom service worker code in dev, no error.
However at the recommendation of a support conversation I tried it via ngrok to my local server and I do see the console log then.

### What were you expecting?
A console log to show.
I do see: [Quasar] Forcing PWA into the network-first approach to not break Hot Module Replacement while developing.

### What steps did you take, to get the error?
Add PWA mode.
set: workboxPluginMode: 'InjectManifest' in quasar.conf.js
add a console.log statement in custom-service-worker.js
run `quasar dev -m pwa`
check for console log

**Comment by rstoenescu** [comment]
Tested and it works correctly.
Are you sure you've set skipWaiting or reloaded the page (to ensure latest service-worker is installed and activated -- may require some tweaking from Dev Tools > Application)?

**Comment by rstoenescu** [comment]
Some info to get you started: https://developers.google.com/web/fundamentals/codelabs/debugging-service-workers/

**Comment by nothingismagick** [comment]
I believe this is related to the issue I am also facing in Chrome on MacOS
- in fact, it was my idea for Shawn to try out the ngrok link. This should
definitely be reopened.

**Comment by rstoenescu** [comment]
Reopening, but it's 99% outside of Quasar's reach. Most likely it's an issue with workbox or webpack workbox plugin.

**Comment by nothingismagick** [comment]
So, it seems that you need to use https to properly load service workers, so after setting:
```
 devServer: {
      https: true,
```
in the quasar.conf.js I was able to remove the warnings about not being able to access the service workers in chrome and firefox on mac.

If you need to setup a local https cert, you can use this approach - reportedly it works fine:
https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/
