### ISSUE TITLE
[v1] Request: Change QPopupEdit background color

### ISSUE THREAD

**Issue by aoltra** [quasarframework/quasar#3929]
Hi!

I wish change the background color of a _qpopupedit_. Using _class_ I can change it in _QInput_, but not in its parent, _QPopupEdit_, leaving a white frame that comes from a _QMenu_ component. My idea is to do something similar to the following code

```
<q-popup-edit v-model="props.row.lang1" class="bg-secondary">
    <q-input class="bg-secondary" color="info1" dark v-model="props.row.lang1" content dense autofocus counter />
 </q-popup-edit>
```
that is, to add a _class_  (or a _content-class_) attribute that allows the change of the background color.

**Comment by rstoenescu** [comment]
Added "content-class" (String) and "content-style" (String|Array|Object) props.
Will be available in beta.18
