### ISSUE TITLE
Autocomplete - Full Search

### ISSUE THREAD

**Issue by mbackonja** [quasarframework/quasar#393]
Hi,

Thanks for this great framework!

It will be cool if You add some boolean parameter to autocomplete which will switch between 'startWith' and some sort of 'contains'. Let me explain.

If my autcomplete contains this:
'This is example'
I **must** type 'thi' to see that... But I also want to see that if I type 'exa' or 'is'.

Best regards!

**Comment by rstoenescu** [comment]
Will do. Thanks.

**Comment by danikane** [comment]
@mbackonja Wait a minute, friend.
Is this about the provided example?
Maybe I misunderstood your proposal, but I think Autocomplete is about how YOU implement the search handler with the terms provided.
For example I have a backend serving Mongo documents and my autocomplete handler does a Regex search by name - case insensitive and matching the terms no matter where they are (start, middle or end) .
Then you can format the results any way you like.
Cheers!

**Comment by qq7** [comment]
@danikane not exatly. Even if your backend responds with ["yo@example.com", "hey@example.com"] when you write "xample" into the search field, neither of these strings will appear in autocomplete unless you write "yo..." or "hey..."

**Comment by rstoenescu** [comment]
On v0.14 you'll be able to supply a custom matching handler function.

**Comment by rstoenescu** [comment]
In v0.14 beta.
