### ISSUE TITLE
q-card-actions and button spacing classes

### ISSUE THREAD

**Issue by arutz74** [quasarframework/quasar#3935]
### Software version

Quasar: **1.0.0-beta.18**
@quasar/app: **1.0.0-beta.19**
Browser: Firefox

### Issue

The _`<q-card-actions>`_ section doesn't respect the spacing helper classes for buttons. I can make a button larger in _`<q-card-actions>`_ via **size** however **`class="q-px-lg"`** doesn't work. Under _`<q-card-section>`_ the issue doesn't come up.

Eg. 
```
<q-card class="bg-purple text-white">
   <q-card-section>
     <div class="text-h6">Our Changing Planet</div>
     <div class="text-subtitle2">by John Doe</div>
    </q-card-section>
  
    <q-card-actions>
      <q-btn class="q-px-lg" flat>Action 1</q-btn>
      <q-btn flat>Action 2</q-btn>
    </q-card-actions>
</q-card>
```

**Comment by rstoenescu** [comment]
QCardAction's purpose is to follow Material guildelines. As a result, the combination of `align` and possibly `vertical` props set a predefined space between buttons.

If you want some something custom, either use "style" attribute directly (to override the default classes) on that button or use a QCardSection where you can align stuff however you want.

**Comment by arutz74** [comment]
Thanks for the explanation!
