### ISSUE TITLE
[v1][Feature Request] Set search filter programmatically without triggering request event

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#3936]
I would like to set the `filter` props programatically without triggering `request` event. Currently if I set the `filter` directly it triggers the `request` event. 

Here is a sample codepen. 
https://codepen.io/ajcastro/pen/eoGEMw?editors=1010

**Comment by rstoenescu** [comment]
Don't set `rowsNumber` prop on pagination (which enables server-side requests). And remove `@request="onRequest"` from QTable. Call `onRequest()` on mount only.

https://codepen.io/rstoenescu/pen/qwyWQv?editors=1010
