### ISSUE TITLE
Crosswalk end of life

### ISSUE THREAD

**Issue by micheleangioni** [quasarframework/quasar#394]
Hi,
I've just noticed that Crosswalk [won't be developed anymore](https://crosswalk-project.org/blog/crosswalk-final-release.html).

Perhaps the [documentation](http://quasar-framework.org/guide/cordova-wrapper.html#Wrap-your-App) should remove the suggestion to install it with Cordova as it will become soon outdated.

**Comment by rstoenescu** [comment]
Guess you are right, but will leave it for a few months more. Probably put a notice that it's only required for old devices. Thanks for this!
