### ISSUE TITLE
@quasar/cli create command uses quasar-cli version ^0.17.x and quasar-framework version 0.17.x, where is the v1 declaration??

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#3942]
I'm updating from v0.17 to v1 beta and I'm confused how the changes are implemented, I install `@quasar/cli` in comparison to `quasar-cli` to run `quasar create app`, but the dependancies for quasar-cli and quasar-framework stay at version 017 in the newly created `./app` quasar app folder?? so where are the changes imlemented because the fundamental `quasar-cli` and `quasar-framework` dependancies in package.json and package-lock.json are still v0.17.x ??

**Comment by nothingismagick** [comment]
you need to `$ quasar create app -b dev`

**Comment by rstoenescu** [comment]
Temporary, until v1 is final, the command is "quasar create <folder_name> -b dev" --> uses "dev" branch (which is v1) instead of "master" which is still 0.17

**Comment by lopugit** [comment]
> Temporary, until v1 is final, the command is "quasar create <folder_name> -b dev" --> uses "dev" branch (which is v1) instead of "master" which is still 0.17

ohhh damn cool soz it literally says it in the docs page I read, I skimmed over the install part lmfao and just say `quasar create <folder_name>` 

sorryyyy

**Comment by lopugit** [comment]
> Temporary, until v1 is final, the command is "quasar create <folder_name> -b dev" --> uses "dev" branch (which is v1) instead of "master" which is still 0.17. Otherwise it would break 0.17 cli.

just want to take this opportunity to tell you how incredibly beautiful this project is, it will change the world

**Comment by rstoenescu** [comment]
@lopugit Please consider becoming a Patreon with your company (if you haven't already) so we can do more cool stuff. Changing the world to the better is our target.

**Comment by lopugit** [comment]
@rstoenescu I was a $50 patreon for a few months, I'm low on money atm but I will again in the future <3
