### ISSUE TITLE
[v1] [Request] QTable Event showing which row was selected/unselected

### ISSUE THREAD

**Issue by TatiTheFreaK** [quasarframework/quasar#3946]
I've been trying to link the table to vuex, but as far as I know there is no method to know which row got selected/unselected individually. (In my case, multiple tables would fill the same store so I could persist the state, so it would be interesting to know which row got unselected)

It could work like @selectedRow -> function(selectedValue), @unselectedRow -> function(unselectedValue)

**Comment by metalsadman** [comment]
there's a `update:selected` event http://localhost:9090/vue-components/table#QTable-API`.
https://codepen.io/metalsadman/pen/xezENj

**Comment by smolinari** [comment]
Here is the link: https://v1.quasar-framework.org/vue-components/table#API--QTable

Scott

**Comment by TatiTheFreaK** [comment]
This method returns the entire array... What I am asking for is a method
that shows the new selected/unselected row individually.

Example: You select "Eclair", it returns only the eclair object, even
though other rows are selected.

Em qua, 24 de abr de 2019 05:35, Scott <notifications@github.com> escreveu:

**Comment by TatiTheFreaK** [comment]
I see, thanks for your code, it will help me a lot.

**Comment by rstoenescu** [comment]
Simplified this by adding the `@selection` event (takes Object { rows: Array, keys: Array, added: Boolean}). Will be available in beta.19.

@metalsadman thanks for supplying an alternative here!
