### ISSUE TITLE
[v1] Adding "to" Attribute To q-btn Sometimes Messes With Styling / Rendering

### ISSUE THREAD

**Issue by helgardferreira** [quasarframework/quasar#3947]
Quasar: 1.0.0-beta.18
@quasar/app (v1+ only): 1.0.0-beta.19
OS: Linux(4.15.0-47-generic) - linux/x64
Node: 11.3.0
NPM: 6.9.0
Browsers: Chrome, Firefox
iOS:
Android:
Any other software related to your bug:

### CodePen

https://codepen.io/papaamazon/pen/ZZjPNZ

### What did you get as the error?
The styling/rendering of the <q-btn/> goes a bit wonky.
Adding the to="" changes the <button> into an <a> and in some cases (like mine) results in weird styling issues.

https://i.imgur.com/Itl1lRq.gif

### What were you expecting?
The button to look identical where the only difference is that when you click on the button it redirects you to another page.

### What steps did you take, to get the error?
Adding custom CSS to <q-btn/> as well as a to="" attribute.

P.S. I already raised the issue with Danjell on Discord. Just posting the issue here on GitHub as well.

**Comment by nothingismagick** [comment]
The to prop is forcing an <a> element that adds some styling that is not appropriate but 
![Screen Shot 2019-04-22 at 22 39 33](https://user-images.githubusercontent.com/35242872/56531028-9ea7d180-6553-11e9-951b-e0db0b47436f.png)

Maybe this: https://github.com/quasarframework/quasar/blob/dev/quasar/src/components/btn/btn-default.styl#L20-L21

**Comment by nothingismagick** [comment]
After looking through your CSS changes, I am pretty confident that it has to do with the way you are modifying the font-size. I think a more focussed approach to styling on your part would resolve this problem on your end.

Here's the thing: you are breaking the material design spec with your modification.

**Comment by rstoenescu** [comment]
If it's what Denjell says (so custom style applied to `<a>` tags, with CSS selectors not specific enough), then this bug is invalid.
