### ISSUE TITLE
QSelect innerLoading data property 

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#3949]
I'm using `QSelect` with `use-input` and `hide-selected` and `@filter` to update the selected value based on the users input.

I'm running into an issue where the `innerLoading` data property of the `QSelect` component gets stuck as always spinning, I've tried running the `update()` and `abort()` functions from within the `@filter='function'` function but nothing gets rid of the QSpinner component due to the `innerLoading` data property, even setting the prop `loading` to false on `QSelect` doesn't work.

any advice?

**Comment by rstoenescu** [comment]
Any codepen please?

**Comment by lopugit** [comment]
So the problem seems to be it only clears the loading icon if the QSelect is focused, but with chrome autocomplete the field is never selected

```javascript
if (this.focused === true && this.filterId === filterId) {
            clearTimeout(this.filterId)
            typeof fn === 'function' && fn()
            this.$nextTick(() => {
              this.innerLoading = false
              if (this.menu === true) {
                this.__updateMenu(true)
              }
              else {
                this.menu = true
              }
            })
          }
```

It's hard to do a codepen because the problem relies on chrome autofilling so

**Comment by lopugit** [comment]
I was only doing `update()` not `update(()=>{})` but still the `this.focused` part makes the loading spinner unclearable without selecting the field.

I'd suggest a property like `allow-autofill` and make the update function

```javascript
if ((this.focused === true || this['allow-autofill']) && this.filterId === filterId) {
            clearTimeout(this.filterId)
            typeof fn === 'function' && fn()
            this.$nextTick(() => {
              this.innerLoading = false
              if (this.menu === true) {
                this.__updateMenu(true)
              }
              else {
                this.menu = true
              }
            })
          }
```

**Comment by lopugit** [comment]
ignore the last 20 seconds of this gif lol, the autofill completely stopped working lol

https://gyazo.com/3b9c4c49eb4b3c78ad62c193a1488a3f

**Comment by lopugit** [comment]
`
q-select.border-1.q-br-rd-sm.no-shadow.q-input-4.q-ml-xsm.q-mr-xsm(
                    label="State/Province"
                    filled
                    square
                    :value="gosmart($store, 'state.app.entity.alopu.carts.0.addresses.shipping.state', undefined)"
                    @input="setsmart($store, 'state.app.entity.alopu.carts.0.addresses.shipping.state', $event)"
                    :error="getsmart($v, 'state.app.entity.alopu.carts.0.addresses.shipping.$invalid', false) && getsmart($v, 'state.app.entity.alopu.carts.0.addresses.shipping.state.$anyError', false)"
                    use-input
                    :input-debounce="0"
                    hide-selected
                    @filter=`testy`
                    :options=`gosmart($store, 'state.app.geos.countries.Australia.states',
                      [
                        "ACT",
                        "JBT",
                        "NSW",
                        "NT",
                        "QLD",
                        "SA",
                        "TAS",
                        "VIC",
                        "WA",
                      ]
                    )`
                  )
`
`
methods: {
    // getObjects(opts){
    //   this.$socket.emit('getObjects', opts)
    // }
    testy(val, update, abort){
      this.setsmart($store, 'state.app.entity.alopu.carts.0.addresses.shipping.state', val)
      // update(()=>{
      // })
      update(()=>{
        // this.innerLoading = false
      })
      // abort()
      return
      // console.log(args)
    }
  },
`

**Comment by lopugit** [comment]
`gosmart` stands for get or set smart, `getsmart` gets something from a path or returns the 3rd argument/default value, `setsmart` sets something at a path, and `gosmart` gets something from a path or sets the 3rd argument/default value and returns it just incase you were wondering

**Comment by lopugit** [comment]
@rstoenescu maybe a jsfiddle with work with autofill
https://codepen.io/anon/pen/Pgdzjb?editors=1111

**Comment by lopugit** [comment]
nup https://jsfiddle.net/v5er98pz/

**Comment by lopugit** [comment]
```
                    ref="stateappentityalopucarts0addressesshippingstate"
                    @filter=`(val, update)=>{
                      this.setsmart(this.$store, 'state.app.entity.alopu.carts.0.addresses.shipping.state', val)
                      this.setsmart(this.$refs, 'stateappentityalopucarts0addressesshippingstate.innerLoading', false)
                      update(()=>{})
                    }`
```

ayeee lmao

**Comment by rstoenescu** [comment]
:))
