### ISSUE TITLE
Electron build failure with private git repo

### ISSUE THREAD

**Issue by rgruenewald** [quasarframework/quasar#3950]
### What did you get as the error?
```
npm ERR! code E404
npm ERR! 404 Not Found: modulename@1.2.3
```

### What were you expecting?
Successful installation of the node module

### What steps did you take, to get the error?
- Add private git repo to package.json. e.g. 

```
  "dependencies": {
    "modulename": "git+ssh://git@bitbucket.org:company/modulename.git#commitHash",
  }
```

- Run
`quasar build -m electron`

It looks like line 11 in https://github.com/quasarframework/quasar/blob/dev/app/lib/webpack/electron/plugin.electron-package-json.js is replacing the "git link" string with the appropriate node module version but as this module is not public available the installation fails with 404.

### Software version
Operating System - Windows_NT(10.0.17763) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - Not installed
  @quasar/cli - undefined
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.17 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.18 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.4 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - 4.1.4 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 13.1.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 20.40.2 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.28.4 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.2.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

**Comment by rstoenescu** [comment]
Thanks for reporting. Will get this fixed in quasar/app beta.20

**Comment by rstoenescu** [comment]
Fix will get into quasar/app beta.20 (to be released tomorrow).
