### ISSUE TITLE
[v1][bug] - autogrow, does not work properly when inside a QExpansionItem

### ISSUE THREAD

**Issue by victorborgaco** [quasarframework/quasar#3953]
![Peek 23-04-2019 10-05](https://user-images.githubusercontent.com/9022512/56583159-51594d80-65af-11e9-9e6e-8fbd69e8f2a2.gif)
when an input textarea with the autogrow active property is inside a QexpasionItem component that starts autogrow only works when the model is changed.

https://codepen.io/victorborgaco/pen/GLXQQL

**Comment by mountash** [comment]
As a workaround tie the `v-model` of QExpansionItem and `:autogrow` of input

https://codepen.io/anon/pen/eoQdro

**Comment by gruppler** [comment]
This is a decent workaround, but it causes significant performance degradation if there are a lot of autogrow inputs.

**Comment by rstoenescu** [comment]
Hi,

Fix will be available in "quasar" v1.9.0.
