### ISSUE TITLE
[v1][Feature Request] QSelect on key tab save entry

### ISSUE THREAD

**Issue by bjbk** [quasarframework/quasar#3955]
**Current behaviour:** entry into a QSelect field is not saved on tab (keycode 9) rather, the field reverts to null and the focus changes to the next field or element.
Current Code:
```js
//QSelect
// escape, tab
      if (e.keyCode === 27 || e.keyCode === 9) {
        this.__closeMenu()
        return
      }
```

**Desired behaviour:**  on tab, save the entry and move to the next field or element

Much like is already done currently in QSelect with enter key
Code excerpt:
```js
if (this.menu === true) {
    this.dialog !== true && this.__closeMenu()
}
   else if (this.innerLoading !== true) {
     this.updateInputValue('')
     if (this.$listeners.filter === void 0) {
        this.menu = true
     }
}
```

**Comment by rstoenescu** [comment]
Hi,

The current behaviour is consistent with all use-cases.

One example (out of many) that would make for an inconsistent and buggy-like behaviour if we change how TAB key works: QSelect can also have chips, and these chips are (and need to be) focusable. So imagine you open up the menu, focus on something from it with arrow keys, then hit shift+tab --> it will focus on last chip but also add your menu-focused selection to the model.

**Comment by bjbk** [comment]
Makes perfect sense. I’ll re-think my use case. I was trying to force QSelect to act more like a QInput that can be pre-filled from a data store.
