### ISSUE TITLE
[v1] QItemLabel lines prop doesn't work when parent is a QItemSection side

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#3958]
### Software version

Quasar:
@quasar/app (v1+ only): v1.0.0-beta.18
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Long text not being truncated in QItemLabel inside a QItemSection "side"
### What were you expecting?
Text should be truncated same as when it's on the left side.
### What steps did you take, to get the error?
https://codepen.io/metalsadman/pen/pBxWjz?editors=1010

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in beta.19.
