### ISSUE TITLE
Select component not have the same height with other component

### ISSUE THREAD

**Issue by hatavan83** [quasarframework/quasar#396]
When i use select component the same line with input text, the border-bottom of selection component is not the same line with input text
How can I change the size of select component when I want it with smaller size?

**Comment by hatavan83** [comment]
The select value is not changed when apply placeholder

**Comment by conx13** [comment]
This is similar? #374

**Comment by hatavan83** [comment]
I think so :)

**Comment by conx13** [comment]
at the moment just css: 
`.q-picker-textfield {height: inherit}; .textfield {font-size: 0.5rem;}`
and popover 
`.item { font-size: 1.5rem !important; line-height: inherit;}` ? But i'm a beginner :-)

**Comment by hatavan83** [comment]
@conx13 
Should not change css from framework directly because it will effect to all component in app, I just want to change at my component :(
I add css to change the select component by set font-side but I cannot change the css of popover in my component :(
@rstoenescu Do you have any idea ?

**Comment by conx13** [comment]
> Should not change css from framework directly because it will effect to all component in app, I just want to change at my component :(
> 
I agree...

**Comment by rstoenescu** [comment]
Please wait for the new Quasar version. This version enhances forms a lot. Your issue will be fixed in it. Simply go ahead and continue your work on your app and later this week you'll be able to upgrade to the new Quasar version and everything will work as expected.

**Comment by rstoenescu** [comment]
Closing this as it's kind of duplicate for #374
