### ISSUE TITLE
Quasar app is not working on Windows 10

### ISSUE THREAD

**Issue by averri** [quasarframework/quasar#3965]
### Software version

```
PS C:\Users\ealverr\goodluck> quasar info

Operating System                Windows_NT(10.0.16299) - win32/x64
NodeJs                          10.15.3

Global packages
  NPM                           6.4.1
  yarn                          1.15.2
  @quasar/cli                   1.0.0-beta.4
  cordova                       Not installed
```

Quasar App Extensions
  *None installed*

### What did you get as the error?
The command `quasar dev` is not recognized.

Detailed steps
```
PS C:\Users\ealverr> quasar create goodluck -b dev
```
```
  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|



? Project name (internal usage for dev) goodluck
? Project product name (official name; must start with a letter if you will build mobile apps) Quasar App
? Project description A Quasar Framework app
? Author ealverr
? Check the features needed for your project: (Press <space> to select, <a> to toggle all, <i> to invert selection)ESLint
? Pick an ESLint preset Standard
? Cordova id (disregard if not building mobile apps) org.cordova.quasar.app
? Should we run `npm install` for you after the project has been created? (recommended) yarn

  Quasar CLI · Generated "goodluck".


 [*] Installing project dependencies ...

yarn install v1.15.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @quasar/app > workbox-webpack-plugin > workbox-build > joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning @quasar/app > workbox-webpack-plugin > workbox-build > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning @quasar/app > workbox-webpack-plugin > workbox-build > joi > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning @quasar/app > workbox-webpack-plugin > workbox-build > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning Resolution field "ajv@6.8.1" is incompatible with requested version "ajv@^6.9.1"
warning Resolution field "ajv@6.8.1" is incompatible with requested version "ajv@^6.9.1"
[3/5] Fetching packages...
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@quasar/app > babel-loader@8.0.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@quasar/app > webpack > ajv-keywords@3.4.0" has incorrect peer dependency "ajv@^6.9.1".
warning " > eslint-loader@2.1.2" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 46.18s.


 [*] Running eslint --fix to comply with chosen preset rules...


yarn run v1.15.2
$ eslint --ext .js,.vue src --fix
Done in 1.92s.

 [*] Quasar Project initialization finished!

To get started:

  cd goodluck
  quasar dev

Documentation can be found at: https://v1.quasar-framework.org

Quasar is relying on donations to evolve. We'd be very grateful if you can
take a look at: https://www.patreon.com/quasarframework
Any amount is very welcomed.
If invoices are required, please first contact razvan@quasar-framework.org

Please give us a star on Github if you appreciate our work:
https://github.com/quasarframework/quasar

Enjoy! - Quasar Team
```
```
PS C:\Users\ealverr> cd .\goodluck\
PS C:\Users\ealverr\goodluck> quasar dev
```
```
 Error Unknown command "dev"


  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|



  Example usage
    $ quasar <command> <options>

  Help for a command
    $ quasar <command> --help
    $ quasar <command> -h

  Options
    --version, -v Print Quasar CLI version

  Commands
    create        Create a project folder
    info          Display info about your machine
                    (and your App if in a project folder)
    upgrade       Check (and optionally) upgrade Quasar packages
                    from a Quasar project folder
    serve         Create an ad-hoc server on App's distributables
    help          Displays this message

  --------------
  => IMPORTANT !
  => Trigger this inside of a Quasar project for more commands.
```

### What were you expecting?
I expect the command `quasar dev` to work as intended.

### What steps did you take, to get the error?
Steps described above.

**Comment by nothingismagick** [comment]
I seem to remember a while back someone else had a similar problem because
they were trying to install on windows in a similar path
- try making a folder like C:\Users\ealverr\projects and creating a new
quasar project there.

**Comment by averri** [comment]
@nothingismagick, thanks for that, but it didn't work.

**Comment by rstoenescu** [comment]
There is definitely something wrong with your setup, because I got confirmation from multiple Windows 10 users (and also tested myself on a Win 10 in a VM) that it works correctly.

What does goodluck contain? Can you post the output of a `dir` command inside of it? Quasar seems to not recognize that newly created folder as a quasar project.

**Comment by nothingismagick** [comment]
This is currently in discussion right now in #v1-beta

**Comment by averri** [comment]
This is the contents of the goodluck dir:
```
PS C:\temp\goodluck> ls


    Directory: C:\temp\goodluck


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       24/04/2019     23:09                node_modules
d-----       24/04/2019     23:08                src
-a----       24/04/2019     23:08            147 .editorconfig
-a----       24/04/2019     23:08              6 .eslintignore
-a----       24/04/2019     23:08           1348 .eslintrc.js
-a----       24/04/2019     23:08            258 .gitignore
-a----       24/04/2019     23:08            200 .postcssrc.js
-a----       24/04/2019     23:08            815 .stylintrc
-a----       24/04/2019     23:08             69 babel.config.js
-a----       24/04/2019     23:08            901 package.json
-a----       24/04/2019     23:08           3598 quasar.conf.js
-a----       24/04/2019     23:08             20 README.md
-a----       24/04/2019     23:09         337264 yarn.lock
```

**Comment by genievot** [comment]
=> Trigger this inside of a Quasar project for more commands.
So far I just pointed out you are not in quasar directory, Or what quasar-cli thinks.
Can you share the package.json file?

**Comment by smolinari** [comment]
Are you running git bash as admin? On my Win 10 system, I had to make sure any programs I run for development need to be ran in admin mode. 

Scott

**Comment by genievot** [comment]
@smolinari That's also a good point, But just to inform that am using quasar v1 and mostly use PowerShell without admin mode.

**Comment by averri** [comment]
> Are you running git bash as admin? On my Win 10 system, I had to make sure any programs I run for development need to be ran in admin mode.
> 
> Scott

Yes, I have tested using admin mode and the same issue happens. Thanks for commenting.

**Comment by averri** [comment]
> => Trigger this inside of a Quasar project for more commands.
> So far I just pointed out you are not in quasar project directory, Or what quasar-cli thinks.
> Can you share the package.json file?

Yes sure, this is the contents:
```json
{
  "name": "goodluck",
  "version": "0.0.1",
  "description": "A Quasar Framework app",
  "productName": "Quasar App",
  "cordovaId": "org.cordova.quasar.app",
  "author": "ealverr",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue src",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "quasar": "^1.0.0-beta.0"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0-beta.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.10.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "strip-ansi": "=3.0.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ],
  "resolutions": {
    "ajv": "6.8.1"
  }
}
```

**Comment by averri** [comment]
I have tested Quasar v1-beta with Node 12 and it's working fine:

```
PS C:\Users\ealverr\projects\goodgod> quasar info
```

```
Operating System - Windows_NT(10.0.16299) - win32/x64
NodeJs - 12.0.0

Global packages
  NPM - 6.9.0
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.18 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.19 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - IE-00000617
  vEthernet (DockerNAT) - 10.0.75.1
  Ethernet - 159.107.167.234
  vEthernet (Default Switch) - 172.17.44.209
  vEthernet (nat) - 172.28.240.1
```

```
PS C:\Users\ealverr\projects\goodgod> quasar dev
```

```
 Dev mode.......... spa
 Pkg quasar........ v1.0.0-beta.18
 Pkg @quasar/app... v1.0.0-beta.19
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +5ms
 app:webpack Extending SPA Webpack config +541ms
 app:generator Generating Webpack entry point +17ms
 app:dev-server Booting up... +5ms


  SPA █████████████████████████ [100%] in ~6s



 DONE  Compiled successfully in 6239ms                                                                                                                                                                                             1:34:06 PM


 N  App dir........... C:\Users\ealverr\projects\goodgod
    App URL........... http://localhost:8080/
    Dev mode.......... spa
    Pkg quasar........ v1.0.0-beta.18
    Pkg @quasar/app... v1.0.0-beta.19

 app:dev-server Opening default browser at http://localhost:8080/ +6s
```

**Comment by rstoenescu** [comment]
@averri 

Ok, thanks for answering and ruling out all of the obvious things. I'll prepare some changes in quasar/cli but can we sync together tomorrow (Friday) so we can do a teamviewer session to try some fixes directly on your machine pls? Would take 30-40 minutes of your time but I'd appreciate this very much. I can't reproduce on any Win 10 machine that I touched.

In my mind, the culprit is resolve-from underlying package which I will replace with my own code.

**Comment by averri** [comment]
Hi Razvan,

you're welcome. I can help with that, just let me know the best time for
you. I'll be available from 10am to 5pm Irish time.



Em qui, 25 de abr de 2019 às 15:32, Razvan Stoenescu <
notifications@github.com> escreveu:

**Comment by rstoenescu** [comment]
@averri please ping me on Discord. Preparing a bulletproof approach for quasar/cli and will need you to test it. Thanks for your time!

**Comment by rstoenescu** [comment]
Seems like didn't sync. @averri Can you install latest `@quasar/cli` (1.0.0-beta.5) and report if any errors? `npm i -g @quasar/cli@latest`. I've enhanced the way quasar/cli deferrs to local quasar/app.

Thanks.

**Comment by averri** [comment]
Hi @rstoenescu, I have tested the new `@quasar/cli@1.0.0-beta.5` and it's working fine on Windows 10 with Nodejs 10.x. I even tested `nvm`, and now I can easily switch Node versions and quasar/cli is working fine. Great!

**Comment by averri** [comment]
Hi Razvan,

are you online on Discord? I can't find you.

Yes, I'll try the latest quasar beta with Node 10.x (the one I was having
issues).

Em sex, 26 de abr de 2019 às 17:02, Razvan Stoenescu <
notifications@github.com> escreveu:

**Comment by averri** [comment]
Good news: the new version is working fine on my Windows 10, with Nodejs
10.x.
I'm even using nvm, so I can easily switch Node versions.
Nice!

Em sex, 26 de abr de 2019 às 20:02, Alexandre Verri <
alexandreverri@gmail.com> escreveu:

**Comment by rstoenescu** [comment]
Thanks for reporting!

**Comment by shakeelosmani** [comment]
I am facing the same issue on windows 10, Did this on my mac and worked fine, however, I have the same issue like op on windows 10

![windowsissuequasar](https://user-images.githubusercontent.com/9120484/59245847-579b9b80-8be8-11e9-85bd-2ca3887522bc.PNG)

**Comment by smolinari** [comment]
@shakeelosmani - can you please take your issue to either either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg)?. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by shakeelosmani** [comment]
@smolinari thanks for the tip, Iasked the same question on the discord channel. Fingers crossed.

**Comment by Arman-Ahmed-Jony** [comment]
I am having exactly the same problem.

**Comment by nothingismagick** [comment]
Try removing node and reinstalling 10LTS @Arman-Ahmed-Jony

**Comment by Arman-Ahmed-Jony** [comment]
[solution]

**step 1:** run into cmd/command line
`npm install`

**step 2:** 
`quasar dev
`
if errors like bellow comes
 [error] 1:23  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

use the following command
 `npm run lint -- --fix`

that's how i solved this problem.
i hope this will help you

**Comment by cashmisa** [comment]
> I have tested Quasar v1-beta with Node 12 and it's working fine:
> 
> ```
> PS C:\Users\ealverr\projects\goodgod> quasar info
> ```
> 
> ```
> Operating System - Windows_NT(10.0.16299) - win32/x64
> NodeJs - 12.0.0
> 
> Global packages
>   NPM - 6.9.0
>   yarn - 1.15.2
>   @quasar/cli - 1.0.0-beta.4
>   cordova - Not installed
> 
> Important local packages
>   quasar - 1.0.0-beta.18 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
>   @quasar/app - 1.0.0-beta.19 -- Quasar Framework App CLI
>   @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
>   vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
>   vue-router - 3.0.6 -- Official router for Vue.js 2
>   vuex - 3.1.0 -- state management for Vue.js
>   electron - Not installed
>   electron-packager - Not installed
>   electron-builder - Not installed
>   @babel/core - 7.3.4 -- Babel compiler core.
>   webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
>   webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
>   workbox-webpack-plugin - 4.3.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
>   register-service-worker - 1.6.2 -- Script for registering service worker, with hooks
> 
> Quasar App Extensions
>   *None installed*
> 
> Networking
>   Host - IE-00000617
>   vEthernet (DockerNAT) - 10.0.75.1
>   Ethernet - 159.107.167.234
>   vEthernet (Default Switch) - 172.17.44.209
>   vEthernet (nat) - 172.28.240.1
> ```
> 
> ```
> PS C:\Users\ealverr\projects\goodgod> quasar dev
> ```
> 
> ```
>  Dev mode.......... spa
>  Pkg quasar........ v1.0.0-beta.18
>  Pkg @quasar/app... v1.0.0-beta.19
>  Debugging......... enabled
> 
>  app:quasar-conf Reading quasar.conf.js +0ms
>  app:dev Checking listening address availability (0.0.0.0:8080)... +5ms
>  app:webpack Extending SPA Webpack config +541ms
>  app:generator Generating Webpack entry point +17ms
>  app:dev-server Booting up... +5ms
> 
> 
>   SPA █████████████████████████ [100%] in ~6s
> 
> 
> 
>  DONE  Compiled successfully in 6239ms                                                                                                                                                                                             1:34:06 PM
> 
> 
>  N  App dir........... C:\Users\ealverr\projects\goodgod
>     App URL........... http://localhost:8080/
>     Dev mode.......... spa
>     Pkg quasar........ v1.0.0-beta.18
>     Pkg @quasar/app... v1.0.0-beta.19
> 
>  app:dev-server Opening default browser at http://localhost:8080/ +6s
> ```

Had the same issue with node 8.9.* (but not with 8.10.*), found this thread and upgraded nodejs and problem solved.

Thanks for sharing

**Comment by cashmisa** [comment]
Had the same issue with node 8.9.* (but not with 8.10.*), found this thread and upgraded nodejs and problem solved.

Thanks for sharing

**Comment by grb2015** [comment]
share my case .

I clone a repo from github. run quasar and the same error occor. In my case , I run npm install / or yarn install  . finally ,everything goes well.

**Comment by engbaher77** [comment]
i have same issue , 
Fixed with updating node version to v12.18.1

**Comment by disarticulate** [comment]
Just ran into this issue w/v2. Leaving this note for the google searches:
---
```
  quasar - 2.7.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.3 -- Quasar Framework local CLI
  @quasar/extras - 1.15.0 -- Quasar Framework fonts, icons and animations
```
---
On windows, it looks like Quasar creates `quasar.config.js` and on Unix, it creates `quasar.conf.js`

I copied the windows app, freshly made, to unix and ran `quasar dev` and got the warning. I then created a new app to port over and when copying the files, found the name difference.

**Comment by Maiconph** [comment]
> => Trigger this inside of a Quasar project for more commands. So far I just pointed out you are not in quasar project directory, Or what quasar-cli thinks. Can you share the package.json file?

tnks guy i want a this respost ty
