### ISSUE TITLE
[v1] HMR is slow (~5sec on fresh install)

### ISSUE THREAD

**Issue by denis-gorin** [quasarframework/quasar#3966]
I have a fresh installation according to the instructions (https://v1.quasar-framework.org/quasar-cli/installation)
Then run `quasar dev`
And when I change markup in ex. Index.vue in demo project I've got freeze for an 5 sec

### Terminal Output

```
 WAIT  Compiling...                             11:53:18

  SPA █████████████████████████ [100%] in ~6s

 DONE  Compiled successfully in 6007ms          11:53:24
```

It seems that previous build ( ~ quasar - 1.0.0-beta.14) was ok, no freezes

### Software version

```
Operating System - Windows_NT(6.1.7601) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.18 -- Hig...
  @quasar/app - 1.0.0-beta.19 -- Qua...
  @quasar/extras - 1.1.1 -- Qua...
  vue - 2.6.10 -- Reac...
  vue-router - 3.0.6 -- Offic..
  vuex - 3.1.0 -- sta...
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Ba....
  webpack - 4.30.0 -- Pack...
  webpack-dev-server - 3.3.1 -- Serv...
  workbox-webpack-plugin - 4.3.0 -- A plu...
  register-service-worker - 1.6.2 -- Scri...

Quasar App Extensions
  *None installed*
```

**Comment by lopugit** [comment]
windows nt??

**Comment by rstoenescu** [comment]
HMR is taken care of by webpack + vue-hot-reload-api, so out of Quasar's reach.

**Comment by denis-gorin** [comment]
> HMR is taken care of by webpack + vue-hot-reload-api, so out of Quasar's reach.

yes I thought so, but checking another Vue project bult on vue-cli3 I'v got faster results...

**Comment by nicholaszuccarelli** [comment]
I'm having the same problem.
I was using beta16 and my recompilation was taking ~1s but since upgrading it is taking me around ~5.7s.

**Comment by denis-gorin** [comment]
@nicholaszuccarelli
> I'm having the same problem.

hi, you are right
I'have roll back to beta16

and I have 

```
 WAIT  Compiling...                                 10:46:33

  SPA █████████████████████████ [100%] in ~736ms

 DONE  Compiled successfully in 739ms               10:46:34
```

just compare with `@latest` versions

```
 WAIT  Compiling...                                 10:14:50

  SPA █████████████████████████ [100%] in ~13s

 DONE  Compiled successfully in 12694ms             10:15:03
```

**Comment by denis-gorin** [comment]
the problem starts from 
`@quasar/app... v1.0.0-beta.17`

as @rstoenescu says hmr is out of Quasar - I think reason in dependencies for `@quasar/app... v1.0.0-beta.17`:
```
info All dependencies
├─ @quasar/app@1.0.0-beta.17
├─ @types/events@3.0.0
├─ @types/glob@7.1.1
├─ @types/minimatch@3.0.3
├─ @types/node@11.13.8
├─ autoprefixer@9.5.1
├─ compression@1.7.4
├─ connect-history-api-fallback@1.6.0
├─ del@4.1.1
├─ html-entities@1.2.1
├─ html-minifier@4.0.0
├─ is-path-cwd@2.1.0
├─ is-path-in-cwd@2.1.0
├─ is-path-inside@2.1.0
├─ is-plain-obj@1.1.0
├─ killable@1.0.1
├─ loglevel@1.6.1
├─ mini-css-extract-plugin@0.6.0
├─ normalize-url@2.0.1
├─ open@6.1.0
├─ opn@5.5.0
├─ p-map@2.1.0
├─ path-is-inside@1.0.2
├─ portfinder@1.0.20
├─ prepend-http@2.0.0
├─ query-string@5.1.1
├─ selfsigned@1.10.4
├─ serve-index@1.9.1
├─ sort-keys@2.0.0
├─ strict-uri-encode@1.1.0
├─ style-resources-loader@1.2.1
├─ vue-router@3.0.4
├─ webpack-chain@5.2.4
├─ webpack-dev-middleware@3.6.2
├─ webpack-dev-server@3.3.1
├─ webpack@4.30.0
├─ workbox-build@4.3.0
├─ workbox-webpack-plugin@4.2.0
├─ yargs-parser@11.1.1
└─ yargs@12.0.5
```

and for comparison 

```
info All dependencies
├─ @quasar/app@1.0.0-beta.16
├─ autoprefixer@9.5.0
├─ compression@1.7.4
├─ connect-history-api-fallback@1.6.0
├─ decamelize@2.0.0
├─ del@3.0.0
├─ html-entities@1.2.1
├─ is-path-cwd@1.0.0
├─ is-path-in-cwd@1.0.1
├─ is-path-inside@1.0.1
├─ killable@1.0.1
├─ loglevel@1.6.1
├─ mini-css-extract-plugin@0.5.0
├─ opn@5.5.0
├─ p-map@1.2.0
├─ path-is-inside@1.0.2
├─ portfinder@1.0.20
├─ selfsigned@1.10.4
├─ serve-index@1.9.1
├─ vue-router@3.0.2
├─ webpack-chain@5.2.3
├─ webpack-dev-middleware@3.6.2
├─ webpack-dev-server@3.2.1
├─ webpack@4.29.6
├─ workbox-build@4.3.0
├─ workbox-webpack-plugin@4.1.1
├─ xregexp@4.0.0
├─ yargs-parser@10.1.0
└─ yargs@12.0.2
```

**Comment by denis-gorin** [comment]
![image](https://user-images.githubusercontent.com/3963911/56879387-b2d35d80-6a82-11e9-92c9-a9c5c4b0f604.png)

this peace of code is the reason of freeze

**Comment by rstoenescu** [comment]
I would suggest really looking at the release notes each time when upgrading. Starting with beta.17, you no longer need the `import '~quasar-variables'`, so if you have any in your app, remove them.

@denis-gorin Please do this then report back. Also, copy-paste the output of `quasar info` here. Thanks.

**Comment by denis-gorin** [comment]
Hi,
1. As I said before I have a fresh installation and run demo project (`quasar create v1_freshinstall -b dev`)
2. there is no `import '~quasar-variables'`
3. HMR 
```
 WAIT  Compiling...                                          16:25:30

  SPA █████████████████████████ [100%] in ~5s

 DONE  Compiled successfully in 5300ms                       16:25:35
```

4. HMR without inject Stylus variables automatically
```
 WAIT  Compiling...                                          16:31:12

  SPA █████████████████████████ [100%] in ~377ms

 DONE  Compiled successfully in 379ms                        16:31:13
```

5. `quasar info`
```
Operating System - Windows_NT(6.1.7601) - win32/x64
NodeJs - 11.14.0

Global packages
  NPM - 6.7.0
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.5
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.19 
  @quasar/app - 1.0.0-beta.20
  @quasar/extras - 1.1.1
  vue - 2.6.10 
  vue-router - 3.0.6
  vuex - 3.1.0 
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4
  webpack - 4.30.0
  webpack-dev-server - 3.3.1
  workbox-webpack-plugin - 4.3.0
  register-service-worker - 1.6.2

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
@nicholaszuccarelli what about u? Did u also try this with a fresh install and what's the output of `quasar info` for you? thanks.

**Comment by nicholaszuccarelli** [comment]
Unfortunately I’m not going to have access to a PC for the next few days, but once I am back working I’ll be able to report back.

**Comment by rstoenescu** [comment]
Improved build startup, build speed and HMR speed.
Will be available in quasar/app beta.21

**Comment by rstoenescu** [comment]
@nicholaszuccarelli @denis-gorin Please report back after I release quasar/app beta.21 in a few days. Thank you!

**Comment by nicholaszuccarelli** [comment]
Thank you @rstoenescu. I’ll be able to report back on Friday with my results.

**Comment by denis-gorin** [comment]
@rstoenescu Thanks, now it works like a charm!

```
 WAIT  Compiling...                                       11:54:00

  SPA █████████████████████████ [100%] in ~573ms

 DONE  Compiled successfully in 577ms                     11:54:00


Dev mode.......... spa
Pkg quasar........ v1.0.0-beta.20
Pkg @quasar/app... v1.0.0-beta.21
```

**Comment by nicholaszuccarelli** [comment]
Finally been able to do the update you provided and the problem is now gone :)

Thanks a lot!

**Comment by rstoenescu** [comment]
Thanks for getting back and confirming it now works as expected!

**Comment by aislanmaia** [comment]
I'm in this route with compilation times more and more increasing.
I'ts about 21secs now.
Using version `1.9.4`

**Comment by smolinari** [comment]
@aislanmaia - Please try to get support in the forum or Discord chat first. Adding a comment like this to an old issue will get you no help whatsoever. Thanks.

Scott

**Comment by aislanmaia** [comment]
@smolinari many thanks my friend. I'll be more careful next time.

**Comment by nicholaszuccarelli** [comment]
One of the solutions for me (back in the day) when I had this issue was to upgrade NodeJS. At the time I think I was using Node 8, and when I upgraded to Node 10, the problem went away.
