### ISSUE TITLE
Can‘t use dark style with Dialog plugin

### ISSUE THREAD

**Issue by florianlink** [quasarframework/quasar#3967]
We are using a dark style, so we need to set the dark property on all components.
When using the Dialog plugin, this is not possible, because it is not possible to pass the dark flag to the components that are created by the Dialog internally.

I would propose to add a „dark“ flag to the options of the Dialog, which is passed to all child components.

**Comment by rstoenescu** [comment]
Thanks for opening this ticket.
Dark mode (through "dark" Boolean prop) will be available in beta.20.

**Comment by florianlink** [comment]
Thanks for the quick reaction!
