### ISSUE TITLE
Checkbox and toggle components are not accessible using keyboard

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#397]
Hello.

Both the checkbox and the toggle components should allow to be toggled using the keyboard (at least with space/enter keys).

Thank you,
Dan Popescu

**Comment by rstoenescu** [comment]
Will do. Thanks for pointing this out.

**Comment by rstoenescu** [comment]
Any ideas how to highlight checkoxes, radios and toggles? From a design perspective. For both themes.

**Comment by pdanpdan** [comment]
Sorry for the delay.
In chrome the toggle, checkbox and radio are formatted by browser stylesheet with:
```
:focus {
    outline: -webkit-focus-ring-color auto 5px;
}
```
On the toggle it looks really good.
On the checkbox it's a little bit too light.
But I think the general ideea to put an outline when in focus is good.
On iOS theme I'm sorry, I'm not used to it, but I'll try to see how it shows native.

**Comment by rstoenescu** [comment]
Thanks for the tips!

**Comment by rstoenescu** [comment]
Will be available in v0.14
