### ISSUE TITLE
Why is this repo called quasar which then has ./quasar ?? should be quasarhome/quasar or quasarframework/quasar and then give ./quasar it's own repository

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#3970]
Why is this repo called quasar which then has ./quasar ?? should be quasarhome/quasar or quasarframework/quasar and then give ./quasar it's own repository

know what I mean?

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by rstoenescu** [comment]
Renamed `/quasar` folder to `/ui` for a more appropriate name.

**Comment by lopugit** [comment]
@rstoenescu @smolinari awhhhhhhhh yeahhhhhhhhh

thanks heaps, ocd ftw
