### ISSUE TITLE
Electron build in non standard distFolder with custom .npmrc

### ISSUE THREAD

**Issue by Lukino2000** [quasarframework/quasar#3973]
Hi, I'm using FontAwesome 5 Pro, so I created .npmrc file.
I also need distFolder for build command not in subfolder of my project so I edited quasar.conf.js and added build.distFolder and set it like '../../../distributionFiles/myapp'

when i run 'quasar build -m electron'

it tells me 'error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2ffontawesome-pro: Not found"'

probably you should copy .npmrc in unpackaged folder before running yarn

**Comment by rstoenescu** [comment]
Enhancement will be available in quasar/app beta.21.
Thanks for pointing this out!

**Comment by GhyslainBruno** [comment]
Hi ! 

Any news about this issue ? I'm currently facing the same issue :-/ 

@rstoenescu is the modification available ? 

Thanks for your help

**Comment by rstoenescu** [comment]
This was fixed long ago. What version of quasar/app are you on?

**Comment by GhyslainBruno** [comment]
I'm using 1.1.7 version of quasar

Here is my ```quasar info```  output : 
````
Operating System - Darwin(19.0.0) - darwin/x64
NodeJs - 10.15.1

Global packages
  NPM - 6.4.1
  yarn - 1.19.2
  @quasar/cli - 1.0.0
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.1.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.1.4 -- Quasar Framework local CLI
  @quasar/extras - 1.3.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - 5.0.11 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - 21.2.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @babel/core - 7.6.3 -- Babel compiler core.
  webpack - 4.41.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.8.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-typescript - 1.0.0-beta.1 -- A Quasar CLI Extension
  @quasar/quasar-app-extension-testing - 1.0.0 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0 -- A Quasar App Extension for running Jest tests

Networking
  Host - Ghyslains-MacBook-Pro.local
  en4 - 10.2.47.96
````

The issue is that I'm using an azure npm registry (so using a personal .npmrc file) for some npm packages I forked. 

When I run ```quasar dev -m electron``` it works perfectly fine, the issue is occurring only when I try to build an electron app :-/.

**Comment by GhyslainBruno** [comment]
Ok, so I really don't know why, but I am actually using **yarn** on my project, and I created a **.npmrc** file instead of a **.yarnrc** file (your PR made me think about that, so thank you :-)

Anyway, the thing is, using a .yarnrc file solved the issue (the weir thing is that it really was the exact same error as mentioned by @Lukino2000 )

Thanks again for your help and time @rstoenescu
