### ISSUE TITLE
[v1 Beta] Inset prop on item label applies class but not styling

### ISSUE THREAD

**Issue by smcassar** [quasarframework/quasar#3977]
### Software version
Quasar: 1.0.0-beta.19
@quasar/app (v1+ only): 1.0.0-beta.20
OS: Darwin(18.2.0) - darwin/x64
Node: 10.6.0
NPM: 6.1.0
Browsers: Brave / Chromium

### JsFiddle
https://jsfiddle.net/7uhafbse/

I tried to inset an item label by adding the `inset` prop to `q-item-label` and while it applies the `q-item__label--inset` class however it appears this class doesnt have any styling attached to it

To my knowledge there should be a `margin-left: 72px` or something similar in this file for the class:
https://github.com/quasarframework/quasar/blob/dev/quasar/src/components/list/list.styl

For now I've gotten around this thanks to @smolinari suggesting the `inset-level` prop on `q-item`

Basic reproduction:
```
<q-list bordered>

    <!-- No Inset -->
    <q-item>
      <q-item-section avatar>
        <q-icon name="person"></q-icon>
      </q-item-section>
      <q-item-section>
        <q-item-label>User</q-item-label>
      </q-item-section>
    </q-item>

    <!-- Gets inset correctly -->
    <q-item class="bg-primary text-white" inset-level="1">
      <q-item-section>
        <q-item-label >This should be inset</q-item-label>
      </q-item-section>
    </q-item>
    
    <!-- Doesnt seem to get inset --> 
    <q-item class="bg-primary text-white">
      <q-item-section>
        <q-item-label inset>This should be inset</q-item-label>
      </q-item-section>
    </q-item>
  </q-list>
```

(apologies if this has already been reported, I did a search and couldn't find anything that looked related)

**Comment by rstoenescu** [comment]
Hi,

Correct usage is though `<q-item inset-level`. The `inset` prop should not be there in QItemSection and removed it. Thanks for reporting this.

https://jsfiddle.net/rstoenescu/7jco0ude/4/
