### ISSUE TITLE
Popup Editor doesn't emit save and cancel event

### ISSUE THREAD

**Issue by yockii** [quasarframework/quasar#3978]
### Software version

Quasar: 1.0.0-beta.19
@quasar/app (v1+ only): 1.0.0-beta.20
OS: macOS
Node:  8.11.3
NPM: 5.6.0
Browsers: chrome
iOS: -
Android: -
Any other software related to your bug:

### JsFiddle

https://codepen.io/yockii/pen/BEvgJX

### What did you get as the error?
QPopupEditor do not emit event:  @save, @cancel
### What were you expecting?
emit @save when click set, and @cancel when cancel click

**Comment by yockii** [comment]
should use v-model, not :value

**Comment by smolinari** [comment]
https://codepen.io/smolinari/pen/qwLeeB

You have to make a change, for the save and cancel events to fire. Works as designed.

Scott
