### ISSUE TITLE
QDate without a day of the month

### ISSUE THREAD

**Issue by mr-koww** [quasarframework/quasar#3979]
What about QDate without day of the month (only year, month)? 
![2019-04-26_13-52-10](https://user-images.githubusercontent.com/6480930/56803128-88876300-682a-11e9-9848-086fb3dfba7e.png)

**Comment by rstoenescu** [comment]
Hi,

This is equivalent to 2 QSelects: one for month, one for the year. So doesn't quite makes sense to do it for QDate -- and it woudn't be Material Guidelines compliant anyway.

**Comment by mr-koww** [comment]
@rstoenescu, thank you
