### ISSUE TITLE
Cannot sort null values in Data Table

### ISSUE THREAD

**Issue by Vaerum** [quasarframework/quasar#398]
Hi
I am struggling with sorting NULL values in the DataTable component. It returns this error, when there is NULL values in the data output: TypeError: a is null

I have located it to the file sort.js line 68:
`rows.sort((a, b) => dir * sortFn(a[field], b[field]))`

Should it not be possible to sort null values as empty values? I could of cause check the output from the backend before outputting, but I would prefer the fronted to sort null values, instead of stopping the site of missing values.

/Rasmus

**Comment by rstoenescu** [comment]
Forgot about mentioning, but this should work with v0.14 beta.
