### ISSUE TITLE
 [V1 - Feature requset for Docs] After going to search result to highlight currect article location on left side menu.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3980]
Now when searched on Q1 docs,after opening article I don't know which section it belongs.

It is very bad, because I can not navigate other items on section i dont know.

And the second problem is that I can not memorise article section.

Feature request is to highlight current section and current item on left menu and possibly open all collapses on article path.

**Comment by valasek** [comment]
I would love to see this implemented. Confusing for reader. If this is easy to start with, give me a few hints and I will check if I can implement.

**Comment by nothingismagick** [comment]
I believe this has been resolved and we're just waiting for the docs-site update. @smolinari - that's right, right?

**Comment by rstoenescu** [comment]
Deployed new version of docs. It has this feature.

**Comment by smolinari** [comment]
@nothingismagick - I did one version of a solution. Then the master came in and did a much more elegant and smarter solution. 😁  

Scott
