### ISSUE TITLE
[v1] update Razvan's avatar on github

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#3981]
Hello!

With this new v1 coming out, I think that it would be nice to have Razvan's avatar updated on github, patreon, discord and likes.

Steps to reproduce:
1) Go to https://github.com/rstoenescu
2) Review the avatar
3) Very outdated and low quality

This is low priority, of course.

Thanks!

**Comment by thgick** [comment]
I'd say that's Razvan's private affair :)

**Comment by jean-moldovan** [comment]
@thgick , Sure, although I think new avatar can have a positive marketing impact. You can never underestimate small things like that.

**Comment by nothingismagick** [comment]
```html
<div  blunt  v-sarcasm.type="british-humour">
  <div slot="title">
    You might be going a little too far.
  </div>
  <div slot="content">
     Nobody is telling you to stop using a stock image for your avatar on 
     github @jean-moldovan. Although, now that I think about it, you 
     could add at least a smile to your avatar because its really hard to 
     read your emotions from that picture
   </div>
   <div slot="link">
     https://tineye.com/search/c42e8816e26d7008a6cf08b3797f3eec3400dc0c?page=1
   </div>
</div>
```

**Comment by jean-moldovan** [comment]
Sorry, didn't mean to offend anyone. Thought it was going to be good to have some fun.

**Comment by rstoenescu** [comment]
Yeah, no problem. You're right on the pic :) Will make some time to take a more quality photo and replace current one. Cheers.

**Comment by hawkeye64** [comment]
This is the best issue - EVER!!
Love it. :)
