### ISSUE TITLE
[v1] Bug QSelect - @new-value not work with "options" props

### ISSUE THREAD

**Issue by felipesdias** [quasarframework/quasar#3984]
@new-value doesn't trigger when "options" props is set

Quasar: v1.0.0-beta.18
@quasar/app (v1+ only): 1.0.0-beta.19
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.14.0
NPM: 6.4.1
Browsers: Chrome Version 74.0.3729.108 (32 bits)

**CodePen:** https://codepen.io/felipesdias/pen/wZNgVa

**Comment by rstoenescu** [comment]
Filtering missing. https://v1.quasar-framework.org/vue-components/select#Using-menu-and-filtering

**Comment by felipesdias** [comment]
@rstoenescu 

I think filtering missing is not the problem. It is possible to use "@new-value" without "@filter".

Here a new copy and past CodePen from quasar page:
https://codepen.io/felipesdias/pen/gyqWyz?&editable=true&editors=101

Thanks

**Comment by rstoenescu** [comment]
The codepen includes filter, as I've said. Am I missing something?

**Comment by felipesdias** [comment]
@rstoenescu 
Yes, the @new-value is not triggered. So when an item is added the method "createValue" is not called and the "alert" is not shown

**Comment by rstoenescu** [comment]
`createValue` is called when creating a new value, not when adding a value that's in the menu (so not a "new" one). There's `@add` and `@remove` events being triggered when a value has been added/removed from the model. Does this makes sense to you?
