### ISSUE TITLE
[v1] Selected item not showing up in QSelect with hide-selected prop

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#3985]
### Software version
Quasar: quasar@1.0.0-beta.19
Browsers: Chrome

### JsFiddle
https://codepen.io/topvis/pen/vMbxKq?&editable=true&editors=101

### What did you get as the error?
When QSelect has a property hide-selected, the selected item won't show up in the underlying input component. I think it's a bug because there was no this issue in the previous version (beta.18).

### What were you expecting?
The selected item should show up in the underlying input component.

### What steps did you take, to get the error?
Refer to the codepen link. Select any item from the drop down list of the QSelect component.

**Comment by rstoenescu** [comment]
This is now working as per new design which was discussed. `hide-selected` will no longer tamper with the native input. It just hides the "selected" part.
