### ISSUE TITLE
Q-Select with use-input does not show selected option

### ISSUE THREAD

**Issue by beatwiz** [quasarframework/quasar#3988]
### Software version

Quasar: quasar-v1.0.0-beta.19
@quasar/app (v1+ only): v1.0.0-beta.20
OS: Win10
Node: Latest
NPM:
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### JsFiddle
https://codepen.io/beatwiz/pen/rbPRaV

This code was working fine on .18.

It allowed you to view and delete the selected option label

On .19 it doesnt show the label.

Is this supposed to be this way?

Thanks in advance

**Comment by rstoenescu** [comment]
Remove `hide-selected` which does exactly what you say: it removes the selected part.
More explanations here: https://github.com/quasarframework/quasar/issues/3987#issuecomment-487273887
