### ISSUE TITLE
[V1] - QBadge floating location and transparency

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/quasar#3989]
Hello, I have a feature request about the QBadge component. For floating props It would be great to have the option of choosing where the badge would float (top-left, bottom-left, top-right, bottom-right, left, right, top, bottom). It would be good to have the ability to choose the transparency too. 
Thank you again for the great work

**Comment by rstoenescu** [comment]
Hi,

Just apply a style or class to it.
https://codepen.io/rstoenescu/pen/dLrpyq?&editable=true&editors=101
