### ISSUE TITLE
A new logo for Quasar Framework

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#399]
Hi all,

I'm working on a new logo for **Quasar Framework**, as my personal contribution to the project.

It's fully _vector_ and _square-bounded_. If you like it, I could provide you the **.svg** file.

Comments and suggestions are welcome!

![quasar-logo](https://cloud.githubusercontent.com/assets/1370938/23089653/1c34053a-f58d-11e6-8f81-62712c6f3ecf.png)
![test-logo](https://cloud.githubusercontent.com/assets/1370938/23089656/259898d4-f58d-11e6-8044-abc04ce38a9c.png)

**Comment by oraknabo** [comment]
Don't forget the  [X-ray jet](https://en.wikipedia.org/wiki/Astrophysical_jet)!

**Comment by smolinari** [comment]
That is pretty cool. 👍 

It might be hard to do, but could you also add a bit of perspective to it? Quasars float in space and it would give the image a bit more of a floating effect, if it were slanted a bit.

Scott

**Comment by rstoenescu** [comment]
@zuck I love it. Thanks a lot for this! Being svg and squared, I just couldn't ask more out of it. Let's also see what the community has to say about it.

**Comment by han2015** [comment]
I like the old one.

**Comment by adam-zpos** [comment]
It's nice. I think too many jagged edges make it look too over the top, and too complicated for what is meant to be representing something to simplify cross platform development.

**Comment by smolinari** [comment]
I agree with the too many edges suggestion. With less edges, the logo would probably look sleeker, which Quasar definitely is. :smile: 

Scott

**Comment by rstoenescu** [comment]
@zuck Can you try a version with less edges? Or even better maybe 5 edges but not split into half at the end? Would this be hard?

**Comment by samhowley** [comment]
I love the new logo, looks fantastic.

But since feedback was requested : 

What about simplifying and instead of making them pointy spiky arms coming out make them like gears, which implies practical functionality and the concept that in the higher gear you can move faster.

Like : 
http://www.bikecyclingreviews.com/images/1/M30415_2.jpg

**Comment by samhowley** [comment]
Hah, I had totally forgotten the tie in the space theme in the name Quasar, my idea is kind of mixing metaphors :)

**Comment by rstoenescu** [comment]
@samhowley I like your idea with the gears.

**Comment by zuck** [comment]
Hi all,

thanks for your feedback and suggestions!

A couple of new concept iterations:

![quasar-logo-2](https://cloud.githubusercontent.com/assets/1370938/23094692/0377b1a6-f5fe-11e6-8226-5953cbcdb317.png)

**Comment by zuck** [comment]
Another little revision of last proposal (which merge both metaphors as suggested by @samhowley):

![quasar-logo-3](https://cloud.githubusercontent.com/assets/1370938/23094830/392f7cbe-f600-11e6-9bf8-3dcfc782566e.png)

**Comment by smolinari** [comment]
I like this one the best. 

![image](https://cloud.githubusercontent.com/assets/3314957/23094963/8a4c0fde-f602-11e6-97f0-ed75c3113c07.png)

How about some perspective? Is that possible?

Scott

**Comment by druppy** [comment]
I agree with Scott :-)

It is a neat shape, yet simple and unique.

**Comment by zuck** [comment]
@smolinari The problem with perspective is that it'll lose regular shape. A regular shape (something that fit inside a square or a circle) is, in general, a good thing because it guarantees simpler life when it has to be used as an icon or similar...

Still experimenting with merging metaphors and simplifying shapes: this is IMHO the final iteration on that path, which adds a very useful feature: it now works also with just two colors without visual problems.

![quasar-logo-4](https://cloud.githubusercontent.com/assets/1370938/23095156/9b816abc-f605-11e6-9677-065d21a2d20f.png)

**Comment by zuck** [comment]
Or, without back circle on dark backgrounds:

![quasar-logo-5](https://cloud.githubusercontent.com/assets/1370938/23095207/56442a1a-f606-11e6-891b-8cf082522f2c.png)

**Comment by dheerajvs** [comment]
Some inspiration from other places (respecting copyrights, of course):

- https://pbs.twimg.com/profile_images/470514506691383298/jSoWQBpt.jpeg
- http://telin.ugent.be/~sdonn/template_images/quasar_icon.svg

**Comment by zuck** [comment]
@dheerajvs Actually the first link you posted has a quite nice and smart concept! Unfortunately, it's already taken and used, so better to keep following another path for this project... Nice catch, by the way!

**Comment by bboydflo** [comment]
I like the last ones @zuck presented. I think they are simple and nice. Good job!

**Comment by Sfinx** [comment]
What about adding some orange colors ? The black-blue palette can become boring quickly

**Comment by zhennann** [comment]
I love the  old  one

**Comment by rstoenescu** [comment]
@zuck 
I simply love the last two examples. Can we experiment a little on the following ideas?
* Use Vue's colors? My sketch below shows an example but I don't quite like it.
* "Close" the spinning spikes with a thin line (with the lighter color).
* Use multiple colors (same as Google logo palette)

I'm not much of a designer, so just throwing ideas. Made a sketch for the "close the spinning spikes with a thin line". Please forgive the quality, it's made in GIMP by hand :)

![screenshot from 2017-02-19 11 10 48](https://cloud.githubusercontent.com/assets/4665641/23101094/8466ad7a-f695-11e6-8bc4-85c869c555ff.png)

**Comment by zuck** [comment]
@rstoenescu I like the idea to use a different color for the center (which, by the way, it's a black hole, so if we don't want to use plain black, we should at least keep a quite dark color).

I don't really like the idea of thin lines to close the spike because:
  1. They simply disappear at small sizes (e.g. favicon, logo in a toolbar, normal icon, etc.) making it visual identical to the one with open spike.
  2. Keeping the spike open breaks the gear shape in small chunks that could represent the "Component" metaphor used by Quasar Framework (small chunks of codes that, merged and ordained together, generates a software system). If we close it, we lose this visual metaphor and it's meaning.
 3. Visually, makes the shape less interesting: what do you see? A spike in a gear or small elements orbiting around a black hole?

For these reasons, I would keep on the last presented shape, maybe experimenting a little bit more on colors as you and others suggested (all chosen colors are already taken from Material palette with the only exception of Vue colors):

![quasar-logo-6](https://cloud.githubusercontent.com/assets/1370938/23107779/d0111b8e-f703-11e6-9bf1-e1787e6ba012.png)

Personally, I suggest to keep on light blue palette in order to keep a visual legacy with old (current) logo and project identity: this is my preferred choice.

My second choice would to use Vue palette in order to visually express the link between the two projects (but loosing a little bit in terms of "self-identity").

**Comment by smolinari** [comment]
I agree with the blue "heritage". I like the blue. 😄 

I like the idea of the closing of the spiral (i.e. turning the white spiral 2-3 px to the left?), as Rasvan suggested, because it gives the logo a less flat look and more depth. If we (I 😄 ) can't have a  perspective that would be the next best thing. Could you please try to implement that suggestion and also demonstrate what it would look like down to favicon size? If it flattens out in smaller sizes, is that really a problem? That is the question that needs visual answering. 

I personally don't see the "togetherness" (merging/ ordaining) with the separate gear chunks. It looks more like separate gear chunks. How about this suggestion? Twist the spiral so much, that only one or two pixels are left. In other words, the spikes of the spiral go to much more pointed ends? 

As for the "black hole", in the quasar galaxy metaphor, the dark grey looks good. I was thinking maybe also give it a slight radiant from white to the grey to a smaller black hole in the middle? That would give the hole more "life" and help with the depth of the logo too. If the logo gets flattened at smaller sizes, that isn't so bad, I'd imagine. Again, would need to see it though to judge. 

Scott

**Comment by rstoenescu** [comment]
@zuck Thanks for the clear (and logical) explanation. I totally agree. The second one is simply brilliant.
I'd also like to see a try with @smolinari's suggestion too if possible. Just wondering how that would look like.

**Comment by beebase** [comment]
My honest opinion. I think the quasar/gear combo is too busy. Also stay away from jagged lines. I would go for a logo with 1 color that is as simple as possible but still captures the essence of a quasar. Like icons on airports/ traffic /public buildings. Simple logos are often the best communicators. 1 color also sticks out in promotional material. (Think of multiple sponsor logos on an event page, being a speaker somewhere etc.

I like the directions Dheerajvs suggested. 
http://telin.ugent.be/~sdonn/template_images/quasar_icon.svg

Esthetics are key here, since where talking about a beautiful GUI framework :-) My first associations are balance, clarity, clean, organized, not too bulky.
I have always leaned toward minimalistic design, so I am very biased I guess.

**Comment by zuck** [comment]
@beebase I agree in general, but honestly the gear/quasar combo, at the end, is just a circle with a pattern shape tiled around it. From a geometrical point of view _is_ visually simple and a kind of solution used in many successful and famous logos. Some examples:

- [Ubuntu](http://design.ubuntu.com/wp-content/uploads/ubuntu-logo32.png)
- [Picasa](http://vignette4.wikia.nocookie.net/logopedia/images/d/d4/Picasa.png/revision/latest?cb=20110905092017)
- [Chrome](https://i.github-camo.com/448f9c5b64bd6d2f3367f53812e54be31e0644c2/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f313433363237312f31323636383233362f63323333613463302d633639372d313165352d386262612d3838323239316462336636352e706e67)

Furthermore, normally a colored shape is visually more distinctive than a bunch of lines as in the linked suggestion you and Dheerajvs reported, especially at small sizes.

These are the requested variations:

![quasar-logo-7](https://cloud.githubusercontent.com/assets/1370938/23121987/c7e57bb2-f762-11e6-9346-5dd5994ff214.png)

I still think the best option should be **n.1** with the following color variations for specific use cases:

![quasar-logo-8](https://cloud.githubusercontent.com/assets/1370938/23122200/8446eebc-f763-11e6-83a2-a5d0fdae5bc2.png)

**Comment by rstoenescu** [comment]
At this point I vote to go with **no.1** too. Simple, metaphoric, meaningful.

**Comment by beebase** [comment]
@zuck  I see what you mean, but still, the picasa and chrome logo are easier on the eye, shapewise, compared to the quasar/gear combo.  (Ubuntu logo, I just don't like)
Maybe using a stick and a ring, experimenting with different dimensions, would be an idea for a simple abstract design.
Anyway, I hope guys don't mind me being critical. (I am NOT a designer, but trying to stay constructive at all times). 
Taste is has always been an endless debate ;-) but I'm sure you'll end up with something good, just like Quasar framework is. 
![img_20170220_124650](https://cloud.githubusercontent.com/assets/446089/23124310/a2838954-f76c-11e6-8172-7762ea855823.jpg)

**Comment by smolinari** [comment]
Yup, nr. 1 looks the best to me too now. 

Scott

**Comment by zuck** [comment]
@beebase I see your point. I tried to follow your idea but honestly, also due to poor perspective distortion support in Inkscape, I was not able to produce any visually good result with that shape (a ray crossing a circle). About your sketches: the first one is obviously too unbalanced but the second was quite interesting, even if 3D always add some troubles when we go fully flat and monochrome...

So, this is my final version with all the use-case variations. Thanks for all you suggestions and contribution!

In order: 

1. _colored with gradient_
2. _bicolor_
3. _one color_
4. _one color inverted_

![quasar-logo-9](https://cloud.githubusercontent.com/assets/1370938/23126596/b087ac46-f777-11e6-9e11-338c321ed0fd.png)

**Comment by zuck** [comment]
Some integration examples:

![quasar-logo-10](https://cloud.githubusercontent.com/assets/1370938/23127472/7c015018-f77b-11e6-9d45-6b47d35562a5.png)
![quasar-logo-11](https://cloud.githubusercontent.com/assets/1370938/23127486/81ca74de-f77b-11e6-881b-87f05b3d797b.png)
![quasar-logo-12](https://cloud.githubusercontent.com/assets/1370938/23127487/81ee45a8-f77b-11e6-9c32-0c682a3ba341.png)
![quasar-logo-13](https://cloud.githubusercontent.com/assets/1370938/23127488/82006846-f77b-11e6-92cd-23a3348c2af7.png)

**Comment by smolinari** [comment]
You know what would be really cool too? A spinner with that logo, where the spiral in the middle turns. 😄 

Scott

**Comment by rstoenescu** [comment]
@zuck, created Quasar Art github repo: https://github.com/quasarframework/quasar-art and added read-write permissions for you. Let's store the sources (in a new /src folder) and the end-result graphics (in a /dist folder) there.

Can you generate png, jpg, favicon etc? Some ready to use graphics with our brand new smart logo at different sizes for different platforms. One with the logo for a lighter background and one for a darker one, just like in your examples. And one with transparent background? Uh oh, I'm asking a lot. Please bare with me :)

**Thanks for your amazing and brilliant work and efforts. And thanks to all who contributed with ideas.**

![screenshot from 2017-02-20 17 55 49](https://cloud.githubusercontent.com/assets/4665641/23132670/01e998fa-f797-11e6-8d11-4c26e557b212.png)

Just look at it. Beauty and smarts in one place :)

**Comment by zuck** [comment]
@rstoenescu Done. Please, check it out!

Thank you all for your help and contribution, I'm glad to have offered something back to the awesome **Quasar Framework** community!

Thank you @rstoenescu for your amazing work!

I think we could now finally mark this issue as _fixed_! :smiley:

**Comment by rstoenescu** [comment]
@zuck please drop me an email or contact me on Gitter when you have time.

**Comment by dobromir-hristov** [comment]
TO be honest, I was thinking of doing a logo design from the moment I started using Quasar, never got to it ☹️ I dont know why, but the cogwheel is not my thing though.

**Comment by odranoelBR** [comment]
Very nice !!! @zuck

**Comment by boriscy** [comment]
Anytime this new logo will arrive?, I like it :smile:

**Comment by matheus-rossi** [comment]
Definitely a new logo is needed, i liked this last option too.

**Comment by smolinari** [comment]
It will arrive soon. 😄 

Scott
