### ISSUE TITLE
[V1] QEditor toolbar size jumping.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#3990]
Looks very strange, while typing text or moving cursor size of toolbar is jumping.

Before
![image](https://user-images.githubusercontent.com/10674646/56866814-87029a00-69e6-11e9-913b-0119598b032c.png)

After
![image](https://user-images.githubusercontent.com/10674646/56866819-941f8900-69e6-11e9-8b04-b8399cc947ec.png)

I think all toolbar buttons need to be with fix width.

**Comment by rstoenescu** [comment]
Use `dense` prop for having toolbar on one row only. Introduced in beta.19.

**Comment by Dmitrij-Polyanin** [comment]
I fixed with fixedLabel: true, on all buttons with text. And now not jumping.
Thanks for help and all huge work on Quasar!
