### ISSUE TITLE
[v1.0.0-beta.19 update] q-editor fullscreen not getting focussed back to editor on fullscreen exit

### ISSUE THREAD

**Issue by mohanzeal** [quasarframework/quasar#3991]
Hi Team,

I have updated my project to **quasar v1.0.0-beta.19** and since then i have found this issue in q-editor where after exiting fullscreen, app is not getting focused back to the editor area but going down

**Reproduce Steps:**
1. Navigate  to https://v1.quasar-framework.org/vue-components/editor#Example--Kitchen-sink (Current doc page is running on quasar v1.0.0-beta.19.)
2. Go to Kitchen sink example.
3. Focus inside the q-editor and press CTRL+F. It should open the q-editor in full screen mode.
4. Press CTRL+F again, it will take you to the bottom of the page but not to the editor.

**Comment by rstoenescu** [comment]
Feature will be available in beta.20.
Thanks for reporting.
