### ISSUE TITLE
[V1] new project default header: glossy → gradient

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3993]
The current default header on new projects:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/3253920/56872233-983cbc80-6a61-11e9-9e6c-9a9acb8594dc.png">

I would suggest going for a gradient, just like the official docs:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/3253920/56872236-a7bc0580-6a61-11e9-9401-c5912edb583a.png">

Looks much more modern in my opinion! 😉

**Comment by rstoenescu** [comment]
I agree with you, but there are lots of developers who don't change any colors, and I don't want Quasar apps to resemble the Quasar docs. Quasar docs should be unique :)

**Comment by mesqueeb** [comment]
I see!
In this case I would opt for flat non-glossy, but that's just a personal preference. 🙃
I think glossy looks a bit 2000's.

**Comment by rstoenescu** [comment]
Removed "glossy".

**Comment by mesqueeb** [comment]
Oh wow! Much appreciated 😊
