### ISSUE TITLE
[v1] beta.19 Slider lazy input @change not called on Android

### ISSUE THREAD

**Issue by ANPetru** [quasarframework/quasar#3995]
### Software version

Quasar: 1.0.0-beta.19
@quasar/app (v1+ only): 1.0.0-beta.20
OS: Linux Arch
Node: 11.12.0
NPM: 6.7.0
Android: 8

### What did you get as the error?
The missfunctiolallity appears when using an slider on lazy mode.
When clicking on it, the slider pointer changes but the @change event is not fired, so the value is not updated.

### What were you expecting?
When user clicks, the event should be called. This behaviour works correctly on browser.

When user slides then realeses, it works correctly.

**Comment by rstoenescu** [comment]
May I ask for a codepen with your exact usage, pls?

**Comment by ANPetru** [comment]
https://codepen.io/anon/pen/YMMbLX

The issue happens when clicking once (not sliding), on Android

**Comment by rstoenescu** [comment]
@ANPetru on your codepen you don't feed the model to the component in any way. Something missing?

**Comment by ANPetru** [comment]
With the @change event I call the method that changes the variable's value. I need the value from before the user started sliding and after he stopped sliding

**Comment by rstoenescu** [comment]
@ANPetru QSlider needs to be fed a model, regardless of what you do afterwards. Your usage is incorrect. Create a model (put minimum value in it), then feed it to QSlider.
Right now, your usage is: "I got a QSlider with no model, but I want to x, y, z"
I was especially interested in finding out how you feed the model (through `:value` or through `v-model`), so I can explain more.

**Comment by rstoenescu** [comment]
Correct usage as per my comments above: https://codepen.io/rstoenescu/pen/zXVNJO?&editable=true&editors=101
Please reopen if the above example does not works. I've tested it on all platforms and it does work.

**Comment by rstoenescu** [comment]
Ok, I saw what you mean. Will fix it.

**Comment by rstoenescu** [comment]
Fix will be available in beta.21.
Thanks for reporting.
