### ISSUE TITLE
[v1] beta.19 App launches not full screen on iPhone X

### ISSUE THREAD

**Issue by carlesar** [quasarframework/quasar#3996]
### Software version

Quasar: v1.0.0-beta.19
@quasar/app (v1+ only): v1.0.0-beta.20
OS: Debian 4.9.144-3 x86_64 GNU/Linux
Node: 9.11.2
NPM: 5.6.0
iOS: 12.1
Devices: iPhone X/XS (iPhones with notch)

### What did you get as the error?
![image](https://user-images.githubusercontent.com/20858599/56884350-ce7e3a00-6a69-11e9-8437-b9da1572ffc5.png)

The app is not launching in full screen mode. This happens exclusively on all iOS devices that have notch.

### What steps did you take, to get the error?
The error can be found creating a new clean project and compiling it with cordova.
`quasar create ios -b dev`
`quasar build -m cordova -T browser`

**Comment by rstoenescu** [comment]
As per cordova docs, you need to add a big resolution [splashscreen](https://github.com/apache/cordova-plugin-splashscreen#readme) (example: 2732x2732px) to your app.

<img width="454" alt="ios_notch_fullscreen" src="https://user-images.githubusercontent.com/4665641/56885737-d80d9f00-6a75-11e9-965a-24b6afdfa202.png">

**Comment by carlesar** [comment]
Shouldn't it be added by default?

**Comment by nothingismagick** [comment]
This is something I've been meaning to address in the @quasar/icon-factory
app extension. But I think the point is also valid, we should ship at least
a quasar themed splash screen - I thought we were...

**Comment by nothingismagick** [comment]
@carlesar - I am working on this right now, please ping me on Discord if you have time. I'd love to make sure I get the icon-factory working for you.

**Comment by rstoenescu** [comment]
Reference: https://github.com/quasarframework/app-extension-icon-factory/issues/49
