### ISSUE TITLE
[V1]Q-editor link option gives an error on use.

### ISSUE THREAD

**Issue by Sambaja** [quasarframework/quasar#3998]
### Software version

Quasar:
@quasar/app (v1+ only): V1.19

Codepen (it's the one on the guide)
https://codepen.io/pen/?&editable=true&editors=101

### What did you get as the error?
I got this https://puu.sh/DlBVk/31fab99668.png. It is easily reproductible in the guide for q-editor.

### What were you expecting?
I was expecting to get a popover to let me choose the link to apply on my text. 1.17 was ok.

### What steps did you take, to get the error?
select text that is not already a link and click on the link icon in the option bar of the editor.

**Comment by rstoenescu** [comment]
Please hit "save" on your codepen. The link you copy-pasted has an empty codepen. Thanks.

**Comment by rstoenescu** [comment]
Fix will be available in beta.20.
Thanks for reporting.
