### ISSUE TITLE
[V1] improve animation on infinite QCarousel

### ISSUE THREAD

**Issue by m0dch3n** [quasarframework/quasar#3999]
### JsFiddle
https://codepen.io/modchen/pen/LvwqMJ

### What steps did you take, to get the error?

Just swiping always to the next slide...

### What were you expecting?

When swiping "next" on the last slide (3), the transition get inverted to "prev", so it "jumps" back to (1) instead of continuing the transition to next slide. 

This breaks the infinite feeling, and it looks like, 1 is not next to 3 but before...

https://github.com/quasarframework/quasar/blob/a762d771505bdd99b0f014fdb491088cfad736f4/quasar/src/mixins/panel.js#L67

This line of code needs to take care of the "infinite" option

**Comment by smolinari** [comment]
@m0dch3n - Your fiddle doesn't seem to work.

Scott

**Comment by m0dch3n** [comment]
@smolinari

you need to "swipe" on the number 1,like you would do on a smartphone,so hold the number and pull it always to left i.e... 

the last slide, the transition will not correspond to your swipe movement...

**Comment by smolinari** [comment]
Ah. Ok. Here is maybe a better pen for demonstration. 😄 https://codepen.io/smolinari/pen/jRRLWE

The swipe on the last slide demonstrates the problem. 

Btw, if you know what the issue is in the code, you could offer a PR to fix it. You'll probably get it added faster. 👍 

Scott

**Comment by m0dch3n** [comment]
@smolinari

yes, on yours with background color the wrong transition is better visible

I can do the PR, but as I've not looked so much on the source code, I'm not sure if this will not break other components behaviours too? This code is in a mixing, so I suppose it's used more often...

**Comment by m0dch3n** [comment]
There is the PR  😄

**Comment by m0dch3n** [comment]
As the PR was closed, my current latest approach is now finished and viewable under

https://github.com/quasarframework/quasar/compare/dev...m0dch3n:transitionTest

**Comment by rstoenescu** [comment]
Fix wil be available in beta.22.

@m0dch3n thanks again for such a great effort!
