### ISSUE TITLE
[v1] QUploader raw upload in beta 19 uploads a text file with "[object File]" text instead of the picked file

### ISSUE THREAD

**Issue by martinflorek** [quasarframework/quasar#4000]
Quasar: v1.0.0-beta.19
OS: Windows, macOS
Browsers: Chrome

### What did you get as the error?
After uploading one file, it was not the file picked in QUploader but a text file with text "[object File]".

### What were you expecting?
Correctly uploaded file.

### What steps did you take, to get the error?
Upload a file with QUploader as raw.

I have noticed that `uploader-xhr-mixin.js` does not have method specific for upload a single file, so probably the general method that works with file array has an issue?

**Comment by mountash** [comment]
Created PR #4011 
See ⚠️ in Other information of PR

**Comment by rstoenescu** [comment]
Fix will be available in beta.21.
@mountash thx for the PR!
