### ISSUE TITLE
QSlider circle marker missing when `label-always` enabled

### ISSUE THREAD

**Issue by 2x2xplz** [quasarframework/quasar#4002]
This was mentioned on Discord, and it was requested to open a new issue.

When `label-always` is enabled, the circle marker on the QSlider is not visible "at rest" or while sliding. It appears briefly after letting go of the slider, then it disappears again. 

This behavior is viewable in the docs page for `QSlider`, in the section for "always display label." 

(On Chrome/Android, the marker doesn't even show up briefly, in my test.)

### Software version

Quasar: 1.0 beta 19
@quasar/app (v1+ only):
OS: 
Node:
NPM:
Browsers: Chrome, Firefox on Windows, Chrome on Android
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Hi, this is per design and as per Material Guidelines at some point (I see no mention of this in the guidelines at the moment I am writing though).

**Comment by rstoenescu** [comment]
The change will be available in Quasar beta.21. Thanks for doing a PR!

**Comment by drogerie21** [comment]
Hi, 
need this functionality. we want to display the thumb always, wheater the thumb is moved or not! Above the thumb-always option is mentioned but in quasar 2 this option is not documented and it doesn´t work!
Any chance this feature will be implemented?

**Comment by rstoenescu** [comment]
@drogerie21 Please check the QSlider API card on the docs. I think that you are looking for label-always prop. There are examples of it throughout the QSlider page too.

**Comment by drogerie21** [comment]
> @drogerie21 Please check the QSlider API card on the docs. I think that you are looking for label-always prop. There are examples of it throughout the QSlider page too.

I configured my slider with the label-always property. The problem i have is that the thumb disappears when i click on the thumb and move it. This is - for me - an unwanted behaviour. So i want to have an option like "thumb-always" that doesn't hide the thumb when moving it. in quasar v2 there is no such option, altough it says above that this has been added.

**Comment by MichaelUray** [comment]
The point at the slider just disappears if it gets clicked/dragged by the mouse.
![ezgif-2-304d0b0f64](https://github.com/quasarframework/quasar/assets/25169478/296862d5-2a07-4bd8-a46c-5f4ef58e3b2f)

I don't think that this is the desired behavior.

**Comment by rstoenescu** [comment]
This is exactly what Material Design Guidelines wanted....

**Comment by MichaelUray** [comment]
> This is exactly what Material Design Guidelines wanted....

What is actually the benefit of this behavior if it is wanted?

**Comment by rstoenescu** [comment]
To see where the user is dragging. Especially useful on mobile.

**Comment by MichaelUray** [comment]
> To see where the user is dragging. Especially useful on mobile.

I mean that the blue point disappears which is located directly on the slider.

The user would see his dragging better if the point would be visible.
On a mobile device the user does not see very much from it since it is then covered by his finger, so it would not matter for him, but by a mouse operation it does.

**Comment by drogerie21** [comment]
@MichaelUray  is right. In fact there is no point in hiding the dot when the user is dragging the dot on a touch device, the finger is covering the dot anyway. But it doesn´t bother either. Quite the opposite is the case if you dragging the dot with a mouse. then it should be visible. Therefore at least an option like "always-visible" would be nice to have.
