### ISSUE TITLE
[v1] beta.19 QDrawer do not respect header on mobile view

### ISSUE THREAD

**Issue by carlesar** [quasarframework/quasar#4004]
### Software version

Quasar: v1.0.0-beta.19
@quasar/app (v1+ only): v1.0.0-beta.20
OS: Debian 4.9.144-3 x86_64 GNU/Linux
Node: 9.11.2
NPM: 5.6.0
Browsers: Chrome and Firefox
Android: 7 and 8
iOS: 12

### What did you get as the error?
The layout was configured as `<q-layout view="lHh Lpr lFf">`.
When working on website everything works fine, but on small views or devices but the right menu does not respect the header.

![image](https://user-images.githubusercontent.com/20858599/56956997-12467180-6b46-11e9-8683-caa32b8b94f2.png)

### What were you expecting?
This behavior is the expected one and it's the one applied when the screen is bigger.
![image](https://user-images.githubusercontent.com/20858599/56957038-32763080-6b46-11e9-89f5-7e28d6b05df5.png)

**Comment by rstoenescu** [comment]
This is by design.
Mobile drawers occupy full height of mobile screen.

**Comment by rstoenescu** [comment]
Takes a lot of time to explain, but changing current behaviour would have downsides to app perf and can introduce lots of bugs in app code.

**Comment by carlesar** [comment]
Understand, do not worry.
I've found a work around to keep the behavior as in previous versions:
When the event @before-show is triggered, get the header height and then apply that to the style attribute top of the "#myQDrawer aside" element.
(It adds a little animation when the menu opens for the first time, but works fine)
