### ISSUE TITLE
[V1] [Proposal] Date Utils - add ability to parse String value

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#4005]
Hi!

With Date Utils we can format `Date` object to `String` with format tokens, but there is no backward operation to convert `String` value to `Date` object.

In my case, I use two `QInput` (Begin, End) with values in format `"DD/MM/YYYY HH:mm"` and I want to calculate duration between this two dates.

Is this possible with Quasar?
If this operation impossible for now I propose to add this ability to avoid using other libs or make custom solution.

P.S. I would like to be able to set the Timezone offset if it is not explicitly specified in tokens.

Thanks!

**Comment by rstoenescu** [comment]
Hi,

getDateDiff(date1, date2, unit) --> this difference is not a date (it's a difference. it may be 1 second)
String to Date --> new Date(string)

Am I missing something?

**Comment by olegvakulenko** [comment]
JavaScript Date constructor can't parse custom format.
For example, I have value `'02/05/2018 23:55'`.

`new Date('02/05/2018 23:55') -> Mon Feb 05 2018 23:55:00 GMT+0200 (Eastern European Standard Time)`

But, in my field I have 2 of May!
So I ask about parse custom string.

**Comment by olegvakulenko** [comment]
BTW, I did exactly as you say in v.0.17.
But in v1 QDate component can't work with timestamp value, only 'YYYY/MM/DD', so I search other solution for my needs.
