### ISSUE TITLE
[v1] Drawer in overlay or desktop modes cannot be initially open

### ISSUE THREAD

**Issue by manelclos** [quasarframework/quasar#4006]
### Software version

Quasar:  v1.0.0-beta.19

QDrawer does not respect initial v-model value when on overlay or desktop mode:

Codepen: https://codepen.io/anon/pen/axrpNo?editors=1010

When QDrawer is on "normal" mode, you can set initial visibility without problems:

Codepen: https://codepen.io/anon/pen/axrpad?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Hi,

This has been reported over and over. This is by design. If it's overlay, then it hides part of the page, and we can't have that. If you really want this, then add a mount() hook and flip the drawer model to `true` there.

**Comment by manelclos** [comment]
Ok thanks, we will try that.

Maybe if you allow it to work like people expect, they would stop asking again and again ;)

**Comment by rstoenescu** [comment]
If I start to explain the reasoning (pages long), then maybe everybody will understand why things should work this way. Meanwhile, there's a ton of other tickets that need to get solved and most people don't even think about [donating](https://www.patreon.com/quasarframework) so we can expand as Quasar deserves and currently needs.

**Comment by manelclos** [comment]
Sure thing Razvan, we appreciate the quality of the framework, that's why we are using it. We try to be polite when asking for changes. We try to get the framework fixed in things that don't work as *we* expect, that's better than including workarounds in our code. If more developers hit the same problem, it would be nice to leave the door open for a change, so people can send PRs. Like in our case the overlay is on top of a map so there is no problem in covering a part of the page. While we wait to have revenue from the products we build using Quasar, we'll continue to try to make it better :) Keep up the good work!
