### ISSUE TITLE
QSelect mobile mode disable option

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#4007]
Is it possible to turn off the mobile popup style for QSelect and always use desktop mode?

this

https://gyazo.com/856067138622e64b994df6fa6f3045fe

to this

https://gyazo.com/7f69823b09d3e5715ddb723a22b8f775

I got the desktop mode working by first loading the desktop version and then turning on chrome device viewer

**Comment by rstoenescu** [comment]
Hi,

The mobile popup is there for a reason. Using desktop mode for mobile too will mess it up, especially because of iOS keyboard bug which breaks `position: fixed` (Apple doesn't want to fix this years old bug).

You won't be able to experiment the "horrific" experience by using the browser emulator. Would need a real iPhone to test with to see what I mean.

Note that when you use the browser emulator and switch between desktop to a mobile (and back), you need to refresh page. The platform detection is not "reactive" (and it shouldn't be anyway).

**Comment by lopugit** [comment]
> Hi,
> 
> The mobile popup is there for a reason. Using desktop mode for mobile too will mess it up, especially because of iOS keyboard bug which breaks `position: fixed` (Apple doesn't want to fix this years old bug).
> 
> You won't be able to experiment the "horrific" experience by using the browser emulator. Would need a real iPhone to test with to see what I mean.
> 
> Note that when you use the browser emulator and switch between desktop to a mobile (and back), you need to refresh page. The platform detection is not "reactive" (and it shouldn't be anyway).

ty makes sense

ima restyle it so it's on the bottom not top I think that's a better UX?

**Comment by rstoenescu** [comment]
Wait for me to release the next Quasar version. Has some tweaks and fixes for QSelect. Don't want you to lose time twice on your restyling.

The reason for appearing at the top is because of the keyboard which comes from the bottom.

**Comment by lopugit** [comment]
Check out how I got autofill working lmao

You probs saw my pull request for the `instantRules` prop, that was a bit dumb because the functionality I realised I was actually trying to get was watching `:rules` on `inputValue` change not just on created, because I realised that `:rules` only gets triggered on blur. But using the `:error` prop and then the error slot works real nice for reactive errors.

Maybe make the `:rules` prop as reactive as `:error` prop?
 

```
                    q-select.border-1.q-br-rd-sm.no-shadow.q-input-4.q-mr-xsm(
                      label="Country"
                      filled
                      square
                      :value=`
                        gosmart($store, 'state.app.entity.alopu.carts.0.addresses.billing.country', undefined)
                      `
                      @input=`
                        setsmart($store, 'state.app.entity.alopu.carts.0.addresses.billing.country', $event)
                        setsmart($refs, 'stateappentityalopucarts0addressesbillingcountry.inputValue', $event)
                      `
                      @input.native=`
                        setsmart($store, 'state.app.entity.alopu.carts.0.addresses.billing.country', $event.target.value)
                        setsmart($refs, 'stateappentityalopucarts0addressesbillingcountry.inputValue', $event.target.value)
                      `
                      bottom-slots
                      :error=`
                        (getsmart($v, 'state.app.entity.alopu.carts.0.addresses.billing.$error', false) && getsmart($v, 'state.app.entity.alopu.carts.0.addresses.billing.country.$anyError', false))
                      `
                      hide-selected
                      use-input
                      keep-input
                      :input-debounce="0"
                      ref="stateappentityalopucarts0addressesbillingcountry"
                      @filter=`(val, update)=>{
                        this.setsmart(this.$refs, 'stateappentityalopucarts0addressesbillingcountry.innerLoading', false)
                        this.setsmart(this.$store, 'state.app.entity.alopu.carts.0.addresses.billing.country', val)
                        this.setsmart(this.$refs, 'stateappentityalopucarts0addressesbillingcountry.inputValue', val)
                        update(()=>{

                        })
                      }`
                      :options=`gosmart($store, 'state.app.geos.countries.strings',
                        [
                          "Australia"
                        ]
                      )`
                    )
                      template(v-slot:error) {{ 
                        | (getsmart($v, 'state.app.entity.alopu.carts.0.addresses.billing.$error', false) && getsmart($v, 'state.app.entity.alopu.carts.0.addresses.billing.country.$anyError', false)) ? 'This value is required' : true 
                        }}

```

https://gyazo.com/91ac25cf4359a4395ce5e597eb8e3190

I couldn't get overwriting after manual input to work for some reason though :O
