### ISSUE TITLE
After update to v1.0.0-beta.20 I am getting fontawesome-v5.js Unexpected token export error

### ISSUE THREAD

**Issue by mohanzeal** [quasarframework/quasar#4012]
Hi Team,

I have updated my app to latest version v1.0.0-beta.20. Now I am getting 500 error  showing trace to quasar node_modules. Please check below screenshot.

![error-after-update](https://user-images.githubusercontent.com/5113135/57009405-01fcc800-6c14-11e9-909a-425aeb7e8527.png)

Environment:
1. Quasar launched in Docker
2. Quasar version v1.0.0-beta.20
3. Quasar app version v1.0.0-beta.21
4. App is using ssr mode.
5. Please check screenshot for the stracktrace.

I was working on this project from past 3 months in the docker environment, it was working fine until yesterday where i have updated to version v1.0.0-beta.20. Error is displayed at the fontawesome export. 

Any suggestions on what went wrong.

Thanks.

**Comment by mohanzeal** [comment]
Hi Team,

I am able to reproduce this issue on the fresh build.

**Steps to reproduce error.**
1. Install latest qusar app with this commend ( quasar create <folder_name> -b dev)
2. Change quasar.conf.js
...
 extras: [
      'roboto-font',
      'fontawesome-v5',
    ],
...
...
iconSet: 'fontawesome-v5'
...

I was tring to add font-aswesome as default icons here.

3. Run application in ssr mode (quasar dev -m ssr)

You will get a 500 error.

Environment
1. Operating system:Ubuntu 16.04
2. Quasar verions: v1.0.0.beta.20
3. Quasar App version v1.0.0.beta.21

Please check into this.

Screenshots:
![Screenshot from 2019-05-01 13-54-14](https://user-images.githubusercontent.com/5113135/57010136-bc8ec980-6c18-11e9-83e2-22e7a5adcf6d.png)

![Screenshot from 2019-05-01 13-58-06](https://user-images.githubusercontent.com/5113135/57010211-3030d680-6c19-11e9-9263-ec6d7c394447.png)

 Thanks.

**Comment by rstoenescu** [comment]
Thanks for reporting. Will fix this asap.

**Comment by rstoenescu** [comment]
Fix will be available in beta.22 (to be released in 1 hour).

**Comment by rstoenescu** [comment]
quasar/app beta.22 is available and it has the fix.

**Comment by mohanzeal** [comment]
Hi Razvan,

Thanks for a quick response and fix. You are doing great job man.

Thanks,
Mohan Bane.
