### ISSUE TITLE
[V1][FUNDAMENTAL BUG] bad Vue lifecycle behaviour in Quasar compound components

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/quasar#4013]
### Software version
Quasar: V1

### JsFiddle
https://jsfiddle.net/zoeqw421/2/

### What did you get as the error?
There are tabs, on each tab there is a component with input. Write some text into that input and switch tabs. Returning to previous tab will clear text.

### What were you expecting?
The text should remain in input component on the other tab.

### Why I consider this "FUNDAMENTAL BUG"?

1. Because it is against Vue philosophy of "keep-alive". Whenever you put those tags it will just not work with quasar1.0.0 beta 20 on the tabbed/compound components.

2. It breaks also Vue component lifecycle guarantees. "Mounted" event is fired every time, because those components are instantiated every time they're newly visible.

3. It effectively stops any attempt to migrate quasar 17 projects to V1, becuase it is a fundamental issue and compound components in non trivial older applications will just not work as expected.

### Is it known bug?

Yes, it was reported before and it is an open issue, but there were no definitive, enough frightening, fiddle example and IMHO there were no strong accent of how fundamental this bug is, and how big impact it could have on migration and testing process.

### Why is it so important to resolve this bug as soon as possible?

Because it is a framework condition, which defines mechanics of the layout/data elements of every application. So, after such a fundamental change in Quasar behaviour between v0.17 and v1, it will be necessary to (manually?) test whole application if it will still work after this change. This is a lot of work, and it should be possible to plan ahead. If it would not be possible to resolve this issue in Quasar I think it would be a strong argument for many developers to migrate existing apps into another solutions. Leaving it as is, would also create a need, for a big rewrite of existing apps and base panel persistence on something else - I don't know - on Vuex with custom in-app persistence layer? Who would be able to write and test such a thing? You would need to "unlearn" some of the Vue basics and need to remember where the Quasar behaviour in specific elements is different. So, based on above it seems as a rather important issue.

**Comment by rstoenescu** [comment]
Hi,

The way you put it seems like a bug in Quasar regarding Vue lifecycle hooks, which is not the case. It's rather a functionality missing in Vue that doesn't takes into account a scenario with keep-alive. This is under the radar however: https://github.com/quasarframework/quasar/pull/3634

**Comment by nothingismagick** [comment]
Not sure what you are referring to regarding the fundamental property of
keep-alive. Are you talking about vue 1.0?

https://vuejs.org/v2/guide/migration.html#keep-alive-Attribute-replaced

**Comment by qyloxe** [comment]
@rstoenescu @nothingismagick 

It rather seems as a bug in Quasar unfortunately. Please look here:

https://vuejs.org/v2/guide/components-dynamic-async.html#keep-alive-with-Dynamic-Components

There should be a possibility to put such a combination of &lt;keep-alive&gt; tags on new QTabs. QTab, QTabPanels, QTabPanel components, that they would retain their state and not emit a lifecycle event "mounted". It was possible in 0.17 and in 1.0 is not possible.

Please consider TYPICAL not trivial use case - you have an editor with many qinputs.  You will create a form with tabs and one submit button. And in V1 it would not be (trivially) possible, because every time you switch tab, you will lose data on other tabs of the same form. It is a serious issue, which will be even more serious when more people will try to migrate their code from 0.17 IMHO.

**Comment by rstoenescu** [comment]
It's not a bug in Quasar. Rather, how Vue keep-alive works. We've got our hands full at the moment and spending time explaining why it's so would not be useful to anyone. We'd rather spend time improving Quasar. I hope you agree.

Like I said, this is under the radar.

**Comment by qyloxe** [comment]
@rstoenescu Sure, I'm not nagging or anything - writing in good faith of course.

Just another use case for consideration - let's assume that you have on three tabs your own q-components - not Vue - for example q-trees. And with the actual behaviour of v1.0, even if you could manage to synchronize state of the tree nodes (by vuex or anything), than regardless of that, Quasar WILL rerender whole q-tree component and all the nodes. And lets imagine, that every q-tree has 2000 nodes and user wants to switch tabs several times a minute (on a mobile phone). We need to rely on virtual DOM, that those trees will not t rerender themselves every time.

So OK, I will not call it a "bug" just "difference in behaviour" between 0.17 and 1.0. Thanks for your comments!

**Comment by rstoenescu** [comment]
Was not sure if it's in good faith at some point.
Regardless, we listen to devs, and there will be a solution for this.

Thanks for your patience.
