### ISSUE TITLE
[V1][Bug] QEditor - Toolbar of Qeditor in Edge

### ISSUE THREAD

**Issue by Sambaja** [quasarframework/quasar#4014]
### Software version

@quasar/app (v1+ only): 1.20
OS: Windows 10
Browsers: Edge

### JsFiddle

https://codepen.io/anon/pen/qwzRJb?&editable=true&editors=101

### What did you get as the error?
The toolbar is reformated when you use the align buttons and the lists (ordered and unordered).

### What were you expecting?
Not be reformated.

### What steps did you take, to get the error?
To reproduce this you just have to be on edge and click the align buttons or the list ones. This is exclusive to edge. I noticed that the q-editor__toolbar was moved out of the q-editor

before : [https://puu.sh/DmsM9/038d17997c.png](url)
after : [https://puu.sh/DmsM9/038d17997c.png](url)

**Comment by rstoenescu** [comment]
Confirmed. Edge browser is erroneously messing with the DOM outside of the content target -- and it shouldn't! Looked for a solution all day but could not find it yet.

**Comment by mountash** [comment]
I think the problem here is the variable name. If you change editor to something else all is working.

https://codepen.io/anon/pen/YbKoqg?&editable=true&editors=101

**Comment by mountash** [comment]
Maybe something with closing tags. If model contains `<div></div>` at the end. All is working.

https://codepen.io/anon/pen/XwrLRE?editors=1010

**Comment by mountash** [comment]
@rstoenescu take a look at the ugly hack [here](https://github.com/mountash/quasar/commit/3f4f071ba22ed9b64450732fbbd9885fa735bc97) 😈

**Comment by nothingismagick** [comment]
Not an ugly hack, almost a polyfill. I did something like this in the past.
Nice one

**Comment by mountash** [comment]
So, then PR #4047

**Comment by rstoenescu** [comment]
Fix will be available in beta.21
