### ISSUE TITLE
Date Utils

### ISSUE THREAD

**Issue by mqdev** [quasarframework/quasar#4015]
I am working a lot with Dates lately and so I decided to ask if it's a good idea to expand the Date library of quasar. Keeping it simple and direct as it is but still relying on the Date standard constructor of javascript.

You guys agree with that I can begin to work on that. Adding some small commits with new functions. Or even if you prefer to keep it lighter, make an extension for the Date Utils.

What do you guys think?

**Comment by rstoenescu** [comment]
Hi,

First of all, sorry for the delay. The past few days have been really crazy.

I'd go with an extension. If it proves valuable to most devs, then we can even integrate it into core. Ping me when it's ready and I can take a look to make an initial assesment.

And thanks for wanting to contribute! Much appreciate it!
