### ISSUE TITLE
Uploader additional Fields

### ISSUE THREAD

**Issue by delueg** [quasarframework/quasar#402]
Hey,

i enhanced the Uploader Component with the possibility to pass additional form fields. I needed it as for example cloudinary want's some extra fields.

I wanted to do a pull request but don't know how to do that correctly

https://github.com/delueg/quasar/commit/d1bb33c5fe2813043a23b7975035cdc120292729?diff=unified

**Comment by rstoenescu** [comment]
@delueg Hi, great! On Quasar's repo github page (this one), hit fork. Then clone your fork, do those changes, git push. On github page of your fork, hit create PR (pull request). Looking forward to integrate your addition.
