### ISSUE TITLE
[V1] QInput mask + type="number"

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4022]
cannot type more than 2 numbers because <code>type="number"</code> and <code>mask="###,###,###"</code>

https://codepen.io/mesqueeb/pen/VNovaZ?&editable=true&editors=101

**PS:** What is the best method to create an `input` that automatically has `,` every 3 0's but keeps the `v-model` to the number.

eg. it's showing `1,000,000,000` but the v-model is `1000000000`. I thought a QInput mask, but that only works with `type="text"`

**Comment by rstoenescu** [comment]
Hi,

"mask" should be used only on type="text". What you are looking to do should be rethought in your app. Sorry for any inconvenience.
