### ISSUE TITLE
[V1] QEditor style bug when fullscreen

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#4023]
If I make QEditor fullscreened with fullscreen button I has transparent background.

![image](https://user-images.githubusercontent.com/10674646/57081574-af97d600-6cfd-11e9-929b-c9af8a88b155.png)

Result:

![image](https://user-images.githubusercontent.com/10674646/57081481-7b241a00-6cfd-11e9-8957-646af334f673.png)

Quasar version: 1.0.0-beta.20
Yandex browser (Chromium)

**Comment by rstoenescu** [comment]
Hi,

Somewhere along the parent chain of your QEditor, you've assigned a "background: transparent". And QEditor inherits the background color (to be as generic as possible).

To fix this, just add a `class="bg-white"` to your QEditor.

**Comment by rstoenescu** [comment]
On second thought, I'm setting default bg to white from Quasar code. If you want a different background, just add a `class="bg-*"`.
Will be available in beta.21.
