### ISSUE TITLE
[v1] QUploader get File/s Ref for external upload

### ISSUE THREAD

**Issue by nachodd** [quasarframework/quasar#4024]
I have a normal Form with multiple fields, among of these, I have to upload multiple files. I'm using the QUploader control to display the files selected, it's preview and more. But I don't want to upload the files immediately. The files will be uploaded when the form is submitted. With this in mind... Is there a way to access the raw files (maybe a ref to the input type file)?, so with it I build a FormData object to submit...
I looked into the docs, but there's no such method to do this. 
Thanks in advance!

**Comment by rstoenescu** [comment]
Hi,

Listen for the `@added` and `@removed` events that the uploader emits and store those files (received as params) somewhere.
