### ISSUE TITLE
@quasar/extras mdi icon set needs updating

### ISSUE THREAD

**Issue by space-dweeb** [quasarframework/quasar#4025]
MDI version in Quasar is outdated. Spoke to @smolinari on Discord, who asked me to make an issue here.

MDI version in Quasar is 3.4.93. The current version is 3.6.95. 

Several of the icons available don't work in Quasar because they are 3.4.93+. MDI's site doesn't track "version introduced", though, so it's a hit-or-miss trying to use MDI icons right now.

**Comment by rstoenescu** [comment]
Updated all icon libs. Available in `@quasar/extras` v1.1.2:

| Package | quasar.conf.js extras name | Changes | Version | Description |
| --- | --- | --- | --- | --- |
| Roboto Font | `roboto-font` | **Updated** | CDN v19 | Recommended font along Material theme |
| Roboto Font Latin Extended | `roboto-font-latin-ext` | **Updated** | CDN v19 | Recommended font along Material theme |
| [Material Icons](https://material.io/icons/) | `material-icons` | **Updated** | CDN v47 | Material icons font |
| [MDI](https://materialdesignicons.com/) (Material Design Icons) | `mdi-v3` | **Updated** | 3.6.95 | Extended Material Design icons font |
| [Font Awesome](https://fontawesome.com/icons?d=gallery) | `fontawesome-v5` | **Updated** | 5.8.1 | Fontawesome icons font |
| [Ionicons](http://ionicons.com/) | `ionicons-v4` | **Updated** | 4.5.5 | Ionicons font |
| [Eva Icons](https://akveo.github.io/eva-icons) | `eva-icons` | 1.1.1 | Eva Icons font |
| [Themify Icons](https://themify.me/themify-icons) | `themify` | 1.0.0 | Themify Icons font |
| [Animate.css](https://daneden.github.io/animate.css/) | Use `animations` prop | 3.5.2 | Bundle of animations you can use in your website/app |
