### ISSUE TITLE
[v1] QSelect does not accept data attributes anymore since beta-20

### ISSUE THREAD

**Issue by satyavh** [quasarframework/quasar#4027]
Since beta-20 QSelect does not accept `data` attributes anymore, for example, prior to beta-20:

```
QSelect(
 ...
 data-cy="select-element"
)
```

would apply the data-cy attribute to the select. Since beta-20, the data-cy attribute is not added anymore to the element in the DOM.

1.0.0-beta.20 

Global packages
  NPM - 6.9.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.20 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.22 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0-beta.14 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing-e2e-cypress - 1.0.0-beta.5 -- A Quasar App Extension for Cypress e2e
  @quasar/quasar-app-extension-testing - 1.0.0-beta.7 -- A Quasar App Extension for managing Test Harnesses

## Pen
https://codepen.io/anon/pen/NmQZWr

**Comment by rstoenescu** [comment]
Hi,

All attributes are attached to the inner `<div class="q-field__native">`. Along many other benefits, this allows the input (if using one) to receive autocomplete attributes.

**Comment by satyavh** [comment]
I'm sure it has benefits, but from a dev perspective it's very inconvenient that custom attributes are attached to a components' inner elements. In Quasar's case, such elements are often deeply nested and when implementing a component a dev has no idea where these attributes end up - making them fairly unusable.

(not to mention that structure and classes of components seems to still change constantly while being in beta).

**Comment by rstoenescu** [comment]
It's only the case with QField/QInput/QSelect. There's no other way than to add it the inner element. Otherwise we can't supply other features. It may be an inconvenient at first, I agree, but it's the way how things can actually work.
 
We're sorry about the constant change of inner elements (which should end with beta.20), but a) it's beta, and b) we are constantly strangled by iOS limitations (especially iOS limitations), Android limitations, and funky browser bugs (that most devs aren't even aware) and so we need to adapt to the issues that we encounter. There's a LOT of effort put into this so that the end result to work flawlessly on all possible platforms and with all possible use-cases. I hope you appreciate this.

**Comment by satyavh** [comment]
For anyone in need of a solution, just hack the thing like this

```
import { QSelect } from 'quasar';

export default {
  functional: true,
  components: { QSelect },

  render(createElement, context) {
    return createElement('div', {
      attrs: {
        'data-cy': context.data.attrs['data-cy'],
      },
    },
    [createElement(QSelect, {
      ...context.data,
    }]
})}};
```

**Comment by satyavh** [comment]
> It may be an inconvenient at first, I agree, but it's the way how things can actually work.

You could enable outer and input attr props, example
```
input-attr="some-data-attribute"
outer-attr="some-data-attribute"
```
inner will be applied to `q-field__native`, and outer to the outer div

**Comment by satyavh** [comment]
Or better, just keep attaching any `data-*` to the outer div and `input-attr` props to `q-field__native`, enabling things like autocomplete. 
Then it's clear for everyone what's going on.

**Comment by satyavh** [comment]
Or maybe you have another alternative? `data-cy` attributes are used for automated testing with Cypress. So this kind of broke all our tests :-|

**Comment by nothingismagick** [comment]
I totally get where you are coming from @satyavh - and this is something that needs to be resolved for both e2e and unit testing. We'll find a way! Thanks for your diligence

**Comment by rstoenescu** [comment]
Filtering attrs is what I initially thought. But it definitely wouldn't be good perf-wise.
However, what about having an `outer-attr` prop? Specifying attributes without passing through this prop would maintain current behaviour (no breaking changes). And if you use that new prop, you'll get those attributes passed to the outermost div. Sounds good?

**Comment by nothingismagick** [comment]
We need to touch the real input field in the dom - the best would be without selector madness like data-cy="email_input_verify" > div > div > input or whatever (because if the dom ever changes, tests will fail)

**Comment by satyavh** [comment]
> However, what about having an outer-attr prop?
You mean a boolean prop right? Yeah that would def work for now, but as I understand there might be cases you'd want both attrs on outer and the native input. So might be limiting

@nothingismagick I also agree with that. We've been updating our tests with a lot of beta releases. But that's also the risk of using beta ;-)

**Comment by nothingismagick** [comment]
So - after a quick discussion with Razvan, I'm going to be building out some tests using nightwatch for our e2e (and will use cypress as well to make sure that we have you covered). I know that this is technically an issue with the way that we are rigging the components in core, but I would prefer to track this over at https://github.com/quasarframework/quasar-testing (see link above)

**Comment by satyavh** [comment]
Awesome!

**Comment by nothingismagick** [comment]
Are you currently using the @quasar/testing app-extension @satyavh ?

**Comment by satyavh** [comment]
yes
