### ISSUE TITLE
[v1] BottomSheet handling of missing icon inconsistent with other components

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#4029]
### Software version

Operating System - Windows_NT(10.0.17763) - win32/x64
NodeJs - 11.9.0

Global packages
  NPM - 6.7.0
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.20 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.22 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### JsFiddle

https://codepen.io/dsl101/pen/pBMMaB

### What did you get as the error?
When the `icon` property within the `actions` array is `undefined` or `null`, a square icon is shown.

### What were you expecting?
Many other components (e.g. QBtn, QExpansionItem) treat `undefined` or `null` as meaning 'no icon'. In my app, the icon is dynamically calculated based on content, so I can't use the same function with BottomSheet. It seems the only way to get _no_ icon is to specify the string 'none`.

Is there some reason for this difference? Could BottomSheet be aligned with other components and treat `undefined` or `null` as a request for no icon?

**Comment by rstoenescu** [comment]
Hi,

BottomSheet is supposed to work with icons/avatars/images. But regardless, improved it when these are missing. Enhancement will be available in beta.21.
