### ISSUE TITLE
Possiblity for chunk uploads with REST API

### ISSUE THREAD

**Issue by prodigy7** [quasarframework/quasar#4031]
For bigger files (and to bypass limitation in upload size) it made sense, implementing a upload API which works by splitting a file into chunks and sending them to the server. Is there any possiblity, implementing that in the upload component?

**Comment by rstoenescu** [comment]
Hi,

This is pretty custom. For custom usage you can create your own upload logic. Just follow doc  [instructions](http://localhost:9090/vue-components/uploader#Supporting-other-services).
