### ISSUE TITLE
I am having trouble using the dateTime Input component.

### ISSUE THREAD

**Issue by hamiltongabriel** [quasarframework/quasar#4032]
I did the implementation of the dateTime Input component, but when I do the build (quasar build) in the browser (google-chrome) when I open the calendar and click once on the date, it arrows that information in my input and works perfectly, however, in the browser (firefox) when I click to open the calendar and I click once on the date it does not inform, I have to double click on the date for it to inform, and this happens only when I do 1 project build, when it is running locally it works perfect shape in both browsers.

Quasar: any (quasar-play)
OS: Debian, Windows, Mac
Browsers: Firefox and Chrome and Safari

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
