### ISSUE TITLE
[V1][bug] Drawer can't be closed by swiping on the drawer itself 

### ISSUE THREAD

**Issue by jvmonjo** [quasarframework/quasar#4033]
In previous versions to v1 drawer could be closed by swiping on the drawer itself. Now you have to swipe outside the drawer to be able to close it.

Since I haven't found anything in the documentation I assume this is a regression.

You can check this behavior from any mobile browser:

V1: https://codepen.io/jvmonjo/pen/wbwzEE

V0.17: https://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/play-with-layout

**Comment by rstoenescu** [comment]
This was by design for v1, but re-analyzed and it can be added back and connected with the `no-swipe-close` Boolean prop (which was doing nothing; bug!).

Extract from addition to docs:
> By default, QDrawer has touch actions attached to it. If this interferes with your drawer content components, disable it by specifying the Boolean `no-swipe-close` property.

Thanks for raising this ticket.

**Comment by rstoenescu** [comment]
Fixed through https://github.com/quasarframework/quasar/commit/e335e1d7b1fec502b5dfb8cd1cc4f0ee9fe8854c

**Comment by rstoenescu** [comment]
Will be available in beta.21
