### ISSUE TITLE
[V1 - low priority] zebra prop QTable

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4037]
I need a "zebra" table for a project.
Like so:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/3253920/57175021-f7476a80-6e81-11e9-9794-f186f5d1e69d.png">

- I could try my hand at **a PR on the source** for QTable and QMarkupTable
- IF rather not in main repo, I could try my hand at **an extension**
- Or we could simply wait until after V1 😉

```html
<q-markup-table zebra>
  ...
</q-markup-table>
```
Or
```html
<q-markup-table :row-colors="['lightgrey', 'grey']">
  ...
</q-markup-table>
```
If I get the go, i'll make it.

**Comment by pdanpdan** [comment]
This is much easier to implement in CSS than in code. Please use CSS for this.
