### ISSUE TITLE
[api] Method in QSelect missing QSelect.json

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#4040]
There is a method, `updateInputValue` in QSelect, which isn't in `QSelect.json`. 

Scott

**Comment by rstoenescu** [comment]
Good catch. Please click on "Create PR" so I can merge it :)

**Comment by smolinari** [comment]
@rstoenescu - I'm not sure what you mean.

Scott

**Comment by rstoenescu** [comment]
I couldn't access your PR. Maybe a glitch in github? Anyway, it's merged now. Thx!
