### ISSUE TITLE
向下拖拽的时候，Table表头行复选框按钮会重复

### ISSUE THREAD

**Issue by lhzhou180606** [quasarframework/quasar#4049]
向下拖拽的时候
![TIM图片20190505234154](https://user-images.githubusercontent.com/39972617/57196437-6f4f8680-6f8f-11e9-935c-cee5150acffa.png)
，Table表头行复选框按钮会重复

**Comment by lhzhou180606** [comment]
hen you drag down, the table header row checkbox button repeats

**Comment by lhzhou180606** [comment]
![image](https://user-images.githubusercontent.com/39972617/57196488-dbca8580-6f8f-11e9-9ea7-8baa7d05283f.png)

**Comment by rstoenescu** [comment]
Hi,

What browser are you viewing with? Because I cannot reproduce.

**Comment by lhzhou180606** [comment]
我用的是谷歌浏览器，但是我发现所有的浏览器都是这样的  搜索网络
I'm using a Google browser, but I find that's what all browsers do. 

![TIM图片20190506085700](https://user-images.githubusercontent.com/39972617/57203713-00048180-6fe5-11e9-9a97-e2a0fce23fe0.png)

**Comment by mohanzeal** [comment]
Hi @lhzhou180606 ,

I think adding a  z-index css property can fix issue.

  .q-table__top,
  .q-table__bottom,
  thead tr:first-child th /* bg color is important for th; just specify one */
    background-color #f5f5dc
    z-index: 1000 // this will fix your problem

As you scroll the check boxes of other rows are passing below 1st th.

Please check this [codepen link](https://codepen.io/mohanzeal/pen/YbzJOa).
