### ISSUE TITLE
[v1] QDate - Emit month/year change

### ISSUE THREAD

**Issue by tegola** [quasarframework/quasar#4057]
It looks like QDate only emits the input event when clicking on a specific day. This is perfectly fine for selecting a day, but I'd like to use it as a "month picker", in which I move between months/years and then tap a button to reload my view with that month selected.

See the screenshot below:

![calendar](https://user-images.githubusercontent.com/1868590/57234981-285ea100-7022-11e9-98c8-ed594866441d.png)

The page behind shows all events for the specified month with the ability to move back and forth between months. However, I need a way to shortcut to a specific month of a specific year, so I put a QDate on a modal panel. As it stands though, I need to click a day to emit the input event and pick the selected date.

Possible solutions to this would be:

a. Have an option to decide when the input should be emitted (on day change, on month change, or on year change)
b. Always emit view changes separately from the input event (e.g. inner-input or view-change, along) with the current value

What do you think?

**Comment by rstoenescu** [comment]
Would events like `picked-month`/`picked-year` help you?

**Comment by tegola** [comment]
Yes, as long as I get the current internal value and not just the event.

**Comment by rstoenescu** [comment]
Following changes on QDate will be available in beta.22:

* New prop (Boolean): emit-immediately --> Emits model when user browses month and year too
* `@input` event pushes two more arguments; full description:
    "value" (the model), "reason" (String: "year"/"month"/"day"/"today"), "details" (Object: {year,month,day})

For your use-case, add `emit-immediately` prop and add a listener for `@input` event:
```js
onInput (value, reason, details) {
   if (reason === 'month') ......... details.month
   if (reason === 'year') ....... details.year
   .....
}
```

**Comment by tegola** [comment]
Will try it out once is released, thanks!

**Comment by rstoenescu** [comment]
It's released :)

**Comment by tegola** [comment]
Well, then I'm going to try it right now :D

**Comment by tegola** [comment]
Works as expected, thank you :)

**Comment by rstoenescu** [comment]
Great.

Please consider [becoming a Patron](https://www.patreon.com/quasarframework) if you haven't already. Any cent counts and it really helps pushing Quasar further.
