### ISSUE TITLE
[v1][Feature] `option-value` & `option-label` props in `QOptionGroup`

### ISSUE THREAD

**Issue by spyke113** [quasarframework/quasar#4059]
### Software version
@quasar: `1.0.0-beta.21`

I don't find `option-value` & `option-label` props in `QOptionGroup` (like in `QSelect`).
Is it possible to add them in the next beta?

P.S. Huge respect for such awesome framework!

**Comment by Jillzee** [comment]
I was just looking for the same thing :)

**Comment by rstoenescu** [comment]
Hi,

We're trying to keep the runtime speed of the components as fast as possible. Adding this to QOptionGroup would mean unnecessary overhead regardless if the developer uses a custom options object or not, and it's not ideal.
However, the right way to do it is very simple through a computed property that maps your original data into the structure required for QOptionGroup:

```js
computed: {
    // feed this as options:
    normalizedOptions () {
      // this.myOptions would be your source
      return this.myOptions.map(opt => {
        val: opt.some.prop.value,
        label: opt.some.other.prop.string,
        // ...
      })
    }
  }
```
