### ISSUE TITLE
Question: possibility to use parcel instead of WebPack

### ISSUE THREAD

**Issue by 123mitnik** [quasarframework/quasar#4063]
just out of curiosity i would like to ask did you tried using quasar with Parcel - [https://parceljs.org/](url)

and if so how it can be done 

Thanks !

**Comment by rstoenescu** [comment]
Hi,

Please use our Discord or forum for questions. Github is reserved for bug reporting. Thank you.
http://chat.quasar-framework.org
https://forum.quasar-framework.org
