### ISSUE TITLE
[Electron] hot reload stopped working

### ISSUE THREAD

**Issue by 123mitnik** [quasarframework/quasar#4064]
i was able to fix it by inserting 

`      watchOptions: {
        poll: true
      }`

inside quasar.conf devServer options

`Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 11.3.0

Global packages
  NPM - 6.9.0
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.21 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.22 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*`

**Comment by nothingismagick** [comment]
I wonder - is this perhaps related to limit of open file handles on mac.

What does this report?
```
$ launchctl limit
```

See this link for a mitigation: https://stackoverflow.com/a/5378206

**Comment by rstoenescu** [comment]
Delete node_modules and yarn.lock/package-json.lock then reinstall. If problem persists, please reopen this ticket.

**Comment by NZX-DeSiGN** [comment]
Can we reopen this issue ?
I've the same bug after v1.0.0-beta.26 (tested on latest rc5) when dev with electron.

### What were you expecting?
Working live reload / hmr when dev with electron.

### What steps did you take, to get the error?
- Install latest quasar-cli
- Create a new project : ```quasar create test```
- Launch electron dev command : ```quasar dev -m electron```
- Change title in ```src/Layouts/MyLayout.vue```

### Temporary fix
- Revert ```@quasar/app``` to 1.0.0-beta.26 in package.json
- Not dev with electron ```quadar dev```

### Software version
**Operating System** - Windows_NT(10.0.17134) - win32/x64
**NodeJs** - 10.15.1

**Global packages**
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-rc.2
  cordova - 8.1.2 (cordova-lib@8.1.1)

**Important local packages**
  quasar - 1.0.0-rc.4 
  @quasar/app - 1.0.0-rc.5 
  @quasar/extras - 1.1.2 
  vue - 2.6.10 
  vue-router - 3.0.6 
  vuex - 3.1.1 
  electron - 4.2.3 
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 
  webpack - 4.32.2 
  webpack-dev-server - 3.4.1 
  workbox-webpack-plugin - 4.3.1 
  register-service-worker - 1.6.2 

**Quasar App Extensions**
  *None installed*

**Comment by nothingismagick** [comment]
I have created a vanilla electron app just now, and HMR works for me. Can you please remove your `yarn.lock` and `node_modules` and report back @NZX-DeSiGN ?

```
$ quasar info

Operating System - Darwin(16.7.0) - darwin/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-rc.2
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - 4.2.3 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
```

**Comment by nothingismagick** [comment]
Ok, I spoke too soon. So HMR is being retriggered in that the CLI recompiles, but changes are not propagated to the electron dev window.

**Comment by rstoenescu** [comment]
Please upgrade `@quasar/app` to rc.6 and report back if everything is ok now.
Seems like webpack-dev-server broke HMR on Electron from its v3.3.1 to v3.4.1, so rolled back webpack-dev-server to 3.3.1.

**Comment by NZX-DeSiGN** [comment]
Just tested rc6, it works perfectly, changes are propagated ! Thank you

**Comment by DataHippo93** [comment]
Does anyone here know how the 123mitnik  was able to get workbox working inside electron? I haven't been able to get it to add anything to cache storage

**Comment by Stefano1990** [comment]
This problem persists btw. I have deleted node_modules and reinstalled. Hot reloading still not working. It used to work and then one day it stopped.

```
Operating System - Windows_NT(10.0.18362) - win32/x64
NodeJs - 12.13.1

Global packages
  NPM - 6.12.1
  yarn - 1.19.2
  @quasar/cli - 1.1.0
  cordova - Not installed

Important local packages
  quasar - 1.14.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.9.6 -- Quasar Framework local CLI
  @quasar/extras - 1.3.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - 7.3.3 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 14.2.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.11.6 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.9.7 -- TypeScript is a language for application scale JavaScript development

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 1.0.0 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.1 -- A Quasar App Extension for running Jest tests

Networking
  Host - LAPTOP-VSR55IL2
  Ethernet 3 - 10.20.1.69
  VirtualBox Host-Only Network - 192.168.56.1
```

**Comment by hawkeye64** [comment]
@Stefano1990 
`@quasar/app - 1.9.6` you need to upgrade to `@quasar/app@2.1.1`
Make sure you follow the [Upgrade Guide](https://quasar.dev/quasar-cli/app-upgrade-guide#What%E2%80%99s-new-in-v2)

**Comment by Stefano1990** [comment]
@hawkeye64 thx, I have upgraded now but as soon as I edite a vuex module as an example my electron window refreshes and remains blank.

**Comment by hawkeye64** [comment]
@s51983 I agree (as probably do most others), upgrading Electron sucks. Find a version that work for you and then pin it to save yourself future issues.
