### ISSUE TITLE
No electron version found if you build in non app subfolder

### ISSUE THREAD

**Issue by Lukino2000** [quasarframework/quasar#4065]
hi,

if you set, in quasar.conf.js, `build/distDir` pointing to a folder outside app folder, lets say `"../dist"`

and try building for electron using `quasar build -m electron`

you receive

```
 app:electron Bundling app with electron-packager... +590ms
 app:electron ⚠️  [FAIL] electron-packager could not build +0ms
Error: Unable to determine Electron version. Please specify an Electron version
```

this is because in UnPackaged folder you don't have any electron version installed, in contrast to what is actually present in app's folder, so `electron-packager` could not find it.

the workaround solution at the moment is setting, in quasar.config.js, `electron/packager/electronVersion` equals to the version you are actually using (see [here](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#electronversion))

probably you should take correct version from app's `package.json` and setting `electronVersion` variable forcing it during spawn of electron-packager

**Comment by rstoenescu** [comment]
Fix will be available in `@quasar/app` beta.23.
Thanks for reporting!
