### ISSUE TITLE
How do I use quasar to listen for finger touch elements and quickly release them

### ISSUE THREAD

**Issue by eventao** [quasarframework/quasar#4067]
How do I use quasar to listen for finger touch elements and quickly release them

**Comment by eventao** [comment]
![Uploading touch-pan.png…]()

**Comment by rstoenescu** [comment]
https://v1.quasar-framework.org/vue-directives/touch-swipe
https://v1.quasar-framework.org/vue-directives/touch-pan

There's also:
https://v1.quasar-framework.org/vue-directives/touch-hold
https://v1.quasar-framework.org/vue-directives/touch-repeat
