### ISSUE TITLE
[V1][Feature] Better a11y support (low prio)

### ISSUE THREAD

**Issue by solaris7791** [quasarframework/quasar#4068]
Hello,
currently only some aria attributes are set in quasar components.
It would be great if all quasar components (like radio buttons, selects, buttons, tabs, etc.) would provide correct aria tags.
Additionally it would be nice to enable setting additonal aria attributes on existing components, to allow using aria-role for application parts.
thx

**Comment by nothingismagick** [comment]
This is also on my wishlist - and my plan is actually make an app-extension that will do this, potentially with some changes to the core API and core itself - but these will be forward changes for after the RC lands.

**Comment by MechJosh0** [comment]
@pdanpdan Is this open for community PRs? I've noticed `tooltip` needs `role` attribute and happy to do a PR for it and others I find.

**Comment by pdanpdan** [comment]
It would be a great help for us if you can do PRs for this. Thank you.

**Comment by mberrisford** [comment]
Ideally (or in the meantime), it would be useful to be able to set attributes directly to the native elements in a component. For instance, the q-select component does allow me to set something like `aria-required="true"` or `role="combobox"` for the autocomplete versions however the attributes get set to the parent div as well as the native element instead of just on the native input element where it belongs. 

```
<q-select
          filled
          v-model="model"
          use-input
          hide-selected
          fill-input
          input-debounce="0"
          :options="options"
          @filter="filterFn"
          hint="Basic autocomplete"
          style="width: 250px; padding-bottom: 32px"
          aria-required="true"
          role="combobox"
        >
```
DOM:
```
<div aria-required="true" role="combobox" class="q-field__native row items-center">
<input type="search" aria-required="true" role="combobox" tabindex="0" id="qf_8fcead78-c077-923f-cb01-12db51073779" class="q-select__input q-placeholder col"></div>
```

**Comment by pdanpdan** [comment]
Link to #5266
