### ISSUE TITLE
IE 11 Table分页显示问题

### ISSUE THREAD

**Issue by zhangzongshan** [quasarframework/quasar#4069]
IE 11 Table 组件在DEV环境下正常显示，但是在build以后，分页挤在一起，其他浏览器上显示正常

**Comment by nothingismagick** [comment]
Can you please use English for your issues? And provide your environment as supplied with `$ quasar info`? We appreciate the report, but if you don't follow minimum requirements for filing (like what version you are using) we can't help you.

**Comment by mountash** [comment]
Translation: The IE 11 Table component is displayed normally in the DEV environment, but after the build, the paging is squeezed together and the other browsers display normal.

**Comment by rstoenescu** [comment]
Did a lot of improvements to QTable and improved these examples. Will be available in docs along with the future beta.24 release.
