### ISSUE TITLE
Error message have 'absolute-bottom' class in input

### ISSUE THREAD

**Issue by nth-zik** [quasarframework/quasar#4070]
Why in beta 19 all Form Components have this class,
this make css error

![image](https://user-images.githubusercontent.com/22862747/57370553-99d15780-71ba-11e9-830c-180cdc543ceb.png)

**Comment by rstoenescu** [comment]
Hi,

Please reopen with a proper Codepen. I don't understand the screenshot... seems like it's the docs on the left, but on the top-left there's something not from docs.

Looking at QField/QInput/QSelect everything seems fine.

Note 1: You are behind with the beta version. Please upgrade to latest first.
Note 2: The absolute-bottom is there for a reason. If you don't want the current behavior (booking up space on the bottom + animations for hint/error etc) then specify `hide-bottom-space` Boolean prop.

**Comment by nth-zik** [comment]
I use Beta 22 and this not fix số i decided open this ticket. On beta 19 this just happened to me. I rolled back to beta 18 and just fine.

**Comment by rstoenescu** [comment]
Please reopen with a proper Codepen like required. Also, please don't dismiss my other comments.

**Comment by nth-zik** [comment]
Can't public this. Many thanks for your response.

**Comment by rstoenescu** [comment]
I'm not asking to share your app. I'm just asking you to create a Codepen highlighting the issue in Quasar. https://codepen.io/rstoenescu/pen/VgQbdx (fork and save then share here).

**Comment by nth-zik** [comment]
I have deleted node_modules and re install, this issue have been fixed.
