### ISSUE TITLE
[v1][bug] - stepper header first and last child dots not centered in contracted mode

### ISSUE THREAD

**Issue by parappathekappa** [quasarframework/quasar#4072]
### Software version

Operating System	Darwin(18.2.0) - darwin/x64
NodeJs          	11.14.0

Global packages 	
  NPM           	6.9.0
  yarn          	1.15.2
  @quasar/cli   	1.0.0-beta.4
  cordova       	9.0.0 (cordova-lib@9.0.1)

Networking      	
  Host          	Bryans-MacBook-Pro-2.local
  en0           	10.0.1.50

### JsFiddle
https://jsfiddle.net/parappathekappa/tsyf05o6/12/

### What did you get as the error?
When using the q-stepper component in 'contracted' mode, the first and last dots in the header are not centered in the __tab divs.  It's only obvious when you have enough q-steps that the tab width becomes fairly small, or even small enough that the dots start to run over the edge of the __tab parent div.

Live demo:
https://youtu.be/yatUbvuv34I

### What were you expecting?
I was expecting the dots to be centered in the __tab div, so that you could add any number of q-steps and the header icons would still be centered and spaced evenly (until you have too many to fit on the screen, of course).  The dots are hard coded with 24px height and width.

### What steps did you take, to get the error?
Embed a q-stepper component with about 7 q-steps inside of it.  Use the 'contracted' option on the q-stepper component.  To visualize the dot spacing better you can add a border styling to the .q-stepper__tab class. :
.q-stepper__tab
  border 1px solid black;

All of the changes were made in the &--contracted section of the stepper.styl file.

**Comment by mountash** [comment]
PR #4112

**Comment by rstoenescu** [comment]
Sorry, but this would break other use-cases. We need to keep it as generic as possible.

**Comment by parappathekappa** [comment]
Really?  I took out :first-child and :last-child translate assignments and
replaced them with universal justify-content assignments.  My solution
seems more generic imho.

-Bryan

**Comment by rstoenescu** [comment]
Well it's great that it worked in your scenario. But from a framework perspective we need to cover all possible use-cases.

**Comment by parappathekappa** [comment]
Hi there,

I totally understand.  I just feel like :first-child and :last-child
translate is a much less generic approach than centering elements within
their divs.  But for sure, I don't have a full understanding how css
styling is structured across the entire application.

Thanks again for the great framework!  It's been a pleasure to work with.

-Bryan
