### ISSUE TITLE
deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

### ISSUE THREAD

**Issue by storkweb** [quasarframework/quasar#4076]
Hi,

for quite some time now coffee-script as been deprecated and should be updated to coffeescript without hyphen.... Can you please change it for the next update ?

Thanks

**Comment by rstoenescu** [comment]
Hi,

We are not using coffeescript. There's a dependency of a dependency [of a dep...] that uses that.
Also, you are not specifying if you're using 0.17 or 1.0, but regardless of that, it makes no difference for your website/app. We keep our direct dependencies up to date.
