### ISSUE TITLE
[v1][Request] "Disable" prop for QFabAction

### ISSUE THREAD

**Issue by HaisojYellams** [quasarframework/quasar#4079]
I apologize in advance if this has been previously addressed, as I was unable to find any discussion on this topic.

Would it be possible to have QFabActions have the "disable" prop (which is then passed to the child QBtn)? I currently have a "save" button within a QFab and would like to be able to disable the button if/when there are not changes to the form. I could use the "disabled" attribute on the component, but that also removes the ability to use a QTooltip on the component.

Thanks for your work on this project. I am a huge fan!

**Comment by rstoenescu** [comment]
"disable" for QFab & QFabAction will be available in beta.24
