### ISSUE TITLE
[v1] Placeholder color is not correct for dark filled input controls

### ISSUE THREAD

**Issue by outofmemoryagain** [quasarframework/quasar#4080]
The placeholder text for form components (reproduced on QInput and QSelect) does not display in a lighter color when the background is a dark color and the dark attribute is set to true.  The text color is changed as expected, but not the placeholder. 
https://codepen.io/anon/pen/yWexmo?&editable=true&editors=101

Version:
Operating System - Windows_NT(10.0.17763) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.23 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.24 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js

**Comment by lucasfernog** [comment]
I have something to fix this, don't know if its good but I can PR it later today so we can discuss. We will need to wait for Razvan and the team, they seem very busy lately.

**Comment by outofmemoryagain** [comment]
I can look at your PR and see if it works for me, altough I may not know all the side effects of it.  I just wanted to get the issue logged, and once I get freed up I was going to see if I could put together a PR myself.

**Comment by lucasfernog** [comment]
Alright, then you see my approach and make your suggestions. Will get some screenshots to attach to the PR now

**Comment by rstoenescu** [comment]
Fix will be available in beta.24

**Comment by outofmemoryagain** [comment]
As always, thanks for the quick fix!
