### ISSUE TITLE
[V1.23][bug] Qselect on mobile Error

### ISSUE THREAD

**Issue by Sambaja** [quasarframework/quasar#4081]
### Software version

Quasar:
OS: Android + Windows 10 (mobile browser mode)
Browsers: Chrome on both

https://codepen.io/anon/pen/PvZyzZ

### What did you get as the error?
I get a RangeError from quasar at the new function showPopup.

![image](https://user-images.githubusercontent.com/15348072/57476509-c17cfa00-7264-11e9-9baa-cc7d943310ef.png)

### What steps did you take, to get the error?
Open the code pen on a mobile browser and get the error. I don't get it on desktop mode. This seems to be related to use-input, because when i remove it the error goes away.

**Comment by rstoenescu** [comment]
Fix will be available in beta.24.
Thanks for reporting!
