### ISSUE TITLE
[v1.b23] Array as value in table data seems 'filtered'

### ISSUE THREAD

**Issue by KPKoch** [quasarframework/quasar#4083]
The q-table component seems to filter (unlink/delete) arrays.
Table data gets a array list with objects. 
If the value of the key is an array, it seems to be deleted from the object.
If the value of the key is an object (or primitive), it doesn't get deleted.

Expected behavior: also the array survives as data value.

I learned it the hard way as by reference it altered my store data.

Current workaround: assigning the data as deep copy.  = JSON.parse(JSON.stringify(data))

**Comment by pdanpdan** [comment]
Do you have an example code showing this?

**Comment by KPKoch** [comment]
Need to check it. This may be a problem on my side. Will report back.

**Comment by rstoenescu** [comment]
Hi,

Please reopen if you are absolutely sure there's an issue in Quasar, otherwise we have our hands full already. Thanks.
