### ISSUE TITLE
How to start standalone development without node ?

### ISSUE THREAD

**Issue by albert-kam** [quasarframework/quasar#409]
Hi, awesome library !

I'm still skimming the guides, but it seems very node centric right now. 

Is there any guide on how to start standalone development (only in browsers), like what files to include, how to get the latest js builds ?

Thank you !

**Comment by rstoenescu** [comment]
Hi,

Please use forum for questions (http://forum.quasar-framework.org/)
Standalone version is not ready yet (no ETA yet). This does not hinder you from developing websites though.

-Razvan
