### ISSUE TITLE
[v1] Incorrect folder name for SQLite native dependency in production mode

### ISSUE THREAD

**Issue by aoltra** [quasarframework/quasar#4090]
Quasar: 1.0.0-beta.20
OS: Linux(4.15.0-47-generic) - linux/x64
Node: 10.15.0
NPM: 6.4.1

I have a rather strange problem and I'm not sure if it's a problem of mine, of Quasar or of electro-builder. :|

I'm developing an electron application that connects to a SQLite database.  To be able to work with it I have added in the file _package.json_, in the scripts section

`postinstall": "install-app-deps"`

Besides. in _quasar.conf_, the function _extendWebpack_  becomes in 
```
extendWebpack (cfg) {
  cfg.externals = {
      sqlite3: 'commonjs sqlite3'
   }
}
```
When I run _npm install_, 2 folders are created: _./node_modules/sqlite3/lib/binding/electron-v4.0-linux-x64_ and _./node_modules/sqlite3/lib/binding/electron-v4.0-linux-x64_. Besides in develop mode _(quasar d -m electron)_ everything works fine.

But when I build in production mode (_quasar build -m electron_) in the _app.asar_ (or in de _UnPackaged_ folder) within  _./node_modules/sqlite3/lib/binding_ the folder created is _electron-v5.0-linux-x64_ (It changes the 4 number for a 5 :O ) and my app does not work.

To reproduce the issue you have to puts somewhere _const sql = require('sqlite')_

My _package.json_ is:

"dependencies": {
    "@quasar/extras": "^1.0.0",
    "aws-sdk": "^2.432.0",
    "electron-builder": "^20.40.2",
    "quasar": "^1.0.0-beta.13",
    "sqlite3": "^4.0.6",
    "vue-i18n": "^7.3.3"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0-beta.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "devtron": "1.4.0",
    "electron": "4.0.3",
    "electron-debug": "2.1.0",
    "electron-devtools-installer": "2.2.4",
    "electron-packager": "^13.1.0",
    "electron-rebuild": "^1.8.4",
    "eslint": "^5.10.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "strip-ansi": "=3.0.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ],
  "resolutions": {
    "ajv": "6.8.1"
  }

I am working with quasar 1.0.0-beta20

**Comment by nothingismagick** [comment]
Look into using electron.require

This is not likely a problem with quasar. Generally with this type of issue
regarding implementation of third party libraries we prefer you seek
support at the forum or the discord server.
