### ISSUE TITLE
QTable doesn't update the row props when data changes

### ISSUE THREAD

**Issue by aislanmaia** [quasarframework/quasar#4091]
I'm using Quasar v.1-beta-16

The table data gets updated, but the row data doesn't reflect that.

This is my `<q-table>` code:
```
<q-table
    :data="contacts"
    :columns="contact_columns"
    row-key="id"
    noDataLabel="Sem contatos para exibir"
  >
    <q-tr v-slot="header">
      <q-th :props="props" v-for="col in props.cols" :key="col.name">
        <div>{{ col.value }}</div>
      </q-th>
    </q-tr>
    <q-tr
        slot="body"
        slot-scope="props"
        :props="props"
        class="cursor-pointer"
        @dblclick.native="rowClickEdit(props.row)"
      >
        <q-td key="name" :props="props" auto-width class="q-pr-lg">{{ props.row.name }}</q-td>
        <q-td key="phone" :props="props" auto-width class="q-pr-lg">{{ props.row.phone }}</q-td>
        <q-td key="actions" :props="props" auto-width class="q-pr-lg">
          <q-btn flat label="Editar" text-color="primary" @click.native="rowClickEdit(props.row)"/>
        </q-td>
      </q-tr>
 </q-table>
```

My `<script>` code:

```
export default {
  name: 'CustomerContactsPanel',
  components: {
    ContactForm: () => import('components/Customers/ContactForm.vue'),
  },
  props: {
    contacts: {
      type: Array,
      default: () => [],
    },
  },
  data() {
    return {
      contact: {},
      showDialog: false,
      contact_columns: [
        {
          name: 'name',
          label: 'Nome',
          field: 'name',
          align: 'center',
          rowClick: this.rowClick,
        },
        {
          name: 'phone',
          label: 'Telefone',
          field: 'phone',
          align: 'center',
        },
        {
          name: 'actions',
        },
      ],
    }
  },
```

I'm using the `rowClickEdit` to fires up a dialog with a Form, passing the row data selected. In the form I update the data emiting a event back to the parent (which contains and render the `<q-table>` above)

Now I have the local data array `contacts` in the parent component updated, but my <q-table> doesn't reflet that. In the `vue-devtools` I can see that the `QTable` data field get updated correctly, but the props row data doesn't. 

Any help would be appreciated.

**Comment by smolinari** [comment]
Hello,

Please update to the latest beta `quasar upgrade -i`. 

Also, please create a codepen reproducing the issue. 

To help get you started....
https://codepen.io/smolinari/pen/wbWwWK

Thanks!

Scott

**Comment by aislanmaia** [comment]
Thanks for the information @smolinari !!

**Comment by rstoenescu** [comment]
Hi,

Your usage is not correct.

Do not directly change `props.row`. Instead change `contacts[props.row.__index]`. This violates Vue's approach of not directly changing properties from within a component.

Also, `data.sync` has no purpose. QTable doesn't emits any `update:data` event.

**Comment by aislanmaia** [comment]
@rstoenescu I know this `data.sync` doesn't make effect. This was just experiments I was doing in the attempts to make it works. I forgot to remove it out there. 
But I don't understand where I'm directly changing the `props.row`.
I'm changing the data thas is passed in to the `<q-table>` `s data property.
If you can point me out, I would be grateful.

Thanks!

**Comment by smolinari** [comment]
This is version 0.17, but the concept of updating or adding data to a table should still work for 1.0. 

https://jsfiddle.net/smolinari/jtez6cgh/

Scott

**Comment by aislanmaia** [comment]
> Hello,
> 
> Please update to the latest beta `quasar upgrade -i`.
> 
> Also, please create a codepen reproducing the issue.
> 
> To help get you started....
> https://codepen.io/smolinari/pen/wbWwWK
> 
> And lastly in the future, please use either our [forum](http://forum.quasar-framework.org/) or [discord channel](https://discord.gg/5TDhbDg) for solving your problems, and to determine if there is a bug or not. If there is a bug, then you can report it with much more exact information to speed up triage and resolution.
> 
> Thanks! 
> 
> Scott

Okay!! Trying to signup in the forum returns for me that my email is suspecious :disappointed: : What????

**Comment by aislanmaia** [comment]
![image](https://user-images.githubusercontent.com/2199137/58766602-f116dd80-8556-11e9-9fef-c4a9d3cd3224.png)
