### ISSUE TITLE
[feature req] q-date allow format with '-', not only slashes

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#4093]
It's too complicated to working with q-date format (YYYY/MM/DD). In databases dates stored with '-' and it need additional steps to convert '-' to '/'. Please, can you add second date format YYYY-MM-DD? Or maybe you can show simplest way to do so?

**Comment by pdanpdan** [comment]
text.split('-').join('/')

**Comment by rstoenescu** [comment]
This relates to https://github.com/quasarframework/quasar/issues/3214.
Closing. Please follow that thread. Thanks.
