### ISSUE TITLE
Is it possible to use a custom prefix?

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/quasar#4094]
Say for example I want to use `custom-button` instead of `q-button`

**Comment by smolinari** [comment]
Hi,

Check my article out: https://medium.com/quasar-framework/component-building-with-quasar-fc101b6730ae

And learn more about Vue (at 12 bucks it is a steal): https://www.udemy.com/vuejs-2-the-complete-guide

And lastly and in general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
