### ISSUE TITLE
[v1 Feature Request] QTable with out of the box tree support

### ISSUE THREAD

**Issue by lhzhou180606** [quasarframework/quasar#4099]
![image](https://user-images.githubusercontent.com/39972617/57585053-3f672c80-7515-11e9-8928-c2dadc7c45d6.png)
可否增加一个Tree Table
Can you add a Tree table like this

**Comment by aleksandrmelnyk** [comment]
That would be gr8 feature!

**Comment by svitch** [comment]
Up for that!
Currently, QTree and QTable both have great features but what if they can be combined in a single component? Sorting, lazy loading child nodes, filtering etc.

**Comment by pdanpdan** [comment]
Please use one of:
- https://github.com/pratik227/quasar-qhierarchy
- https://github.com/Narcis13/quasar-grouped-table
