### ISSUE TITLE
Easy way to update framework without updating everything?

### ISSUE THREAD

**Issue by genyded** [quasarframework/quasar#410]
First and foremost - AWESOME UI framework for Vue! 

Is there or are there plans to provide something along the lines of `quasar update` that would update the framework and it's dependencies without having to try and remember them all or without updating ALL node modules?

If we just update quasar itself then we get unmet Vue and or other dependencies and have to do them too - kind of a pain to get the latest.

**Comment by rstoenescu** [comment]
Hi, that's a feature for NPM to handle. Simply `npm install --save quasar-framework@latest`. If it complains about some dependencies, then install those too.

**Comment by y00rb** [comment]
@rstoenescu But I have question about SSR, I used `0.14.1` in project, then I need new feature SSR, Is it not enough if only upgrade framework, right? Do you have guide or example how to upgrade framework and CLI?

**Comment by smolinari** [comment]
Hi,

Please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. 

Thanks. 😄 

Scott
