### ISSUE TITLE
[v1] QInput types and masks

### ISSUE THREAD

**Issue by kpwbo** [quasarframework/quasar#4102]
### Codepen
Open with Google Chrome.
https://codepen.io/anon/pen/RmRvvb?editors=1010

### What did you get as the error?
In the console, I get the following error whenever I type something in the field.
DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection

### What were you expecting?
No errors.

### What steps did you take, to get the error?
Open the Codepen in Google Chrome, open the console, and type something in the field.

It seems that, with the way masks are currently implemented, we get an error when the type of the QInput is not supported by setSelectionRange. According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange, "Note that accordingly to the WHATWG forms spec selectionStart, selectionEnd properties and setSelectionRange method apply only to inputs of types text, search, URL, tel and password." 

Perhaps we should add a note in the QInput's masks documentation which indicates that masks are only meant to be used with types text, search, URL, tel, and password (or only text ?).

**Comment by rstoenescu** [comment]
Fix will be available in beta.24.
Thanks for reporting!
