### ISSUE TITLE
I used the component <q-popover> in the for loop, and there was an error

### ISSUE THREAD

**Issue by ZealWhiteMouse** [quasarframework/quasar#4103]
I used the component `<q-popover>` in the for loop, and there was an error

TypeError: Cannot read property 'classList' of null

`<span v-for="(item, ndIndex) in chipList" :key="ndIndex">
                            <q-chip :ref="ndIndex"
                                @click.native="flowClick(item, ndIndex)"
                                class="q-mt-xs" small 
                                v-text="item.nodeName == '' ? 'node':item.nodeName" >
                                
                                <q-popover v-model="item.selectVis">
                                    <q-list separator link no-border>
                                        <q-item v-close-overlay @click.native="handleNode('','',ndIndex)">
                                            <q-item-main label="superior" />
                                        </q-item>
                                        <q-item v-close-overlay @click.native="clickFlexPosi(nodeIndex)">
                                            <q-item-main label="position"/>
                                        </q-item>
                                        <q-item v-close-overlay @click.native="openAddUser(nodeIndex)">
                                            <q-item-main label="username"/>
                                        </q-item>
                                        <q-item v-close-overlay @click.native="removeNode(nodeIndex)">
                                            <q-item-main label="deleteNode"/>
                                        </q-item>
                                    </q-list>
                                </q-popover>
                            </q-chip>
                            <q-icon 
                                name="trending_flat" 
                                class="q-mt-xs" 
                                color="light"
                            />
</span>
                        `

**Comment by pdanpdan** [comment]
Can you please provide a codepen showing the issue?

**Comment by rstoenescu** [comment]
Please reopen with a [codepen](https://codepen.io/rstoenescu/pen/VgQbdx) as requested in the github issue template. It saves both you and us time. Thank you.

**Comment by ZealWhiteMouse** [comment]
[//codepen.io/zealwhitemouse/embed/preview/ZNBbex/?height=353&theme-id=0&default-tab=html,result](url)  
This is my codepen, please help me solve the problem of q-popover

**Comment by ZealWhiteMouse** [comment]
> Please reopen with a [codepen](https://codepen.io/rstoenescu/pen/VgQbdx) as requested in the github issue template. It saves both you and us time. Thank you.

//codepen.io/zealwhitemouse/embed/preview/ZNBbex/?height=353&theme-id=0&default-tab=html,result
This is my codepen, please help me solve the problem of q-popover

**Comment by ZealWhiteMouse** [comment]
[//codepen.io/zealwhitemouse/embed/preview/ZNBbex/?height=353&theme-id=0&default-tab=html,result](url)
Please copy and paste this link in your browser before opening it

**Comment by shash8787** [comment]
I'm getting this, too. I've no self-closing tags. Any ideas?
