### ISSUE TITLE
Modal footer strange behavior on iOS

### ISSUE THREAD

**Issue by SnitchRUS66** [quasarframework/quasar#4106]
### Software version

Quasar: ^0.17.19
OS: iOS
Browsers: Safari

### Repository to reproduce

https://github.com/SnitchRUS66/quasar-playground

### What did you get as the error?

Need to click/tap twice on button in modal footer to close it if iOS bottom bar hidden. Tap one and iOS bar appears. Tap two and modal closes.

### What were you expecting?

Click/tap once and modal closes.

### What steps did you take, to get the error?

Look repo and gif.
![quasar-issue](https://user-images.githubusercontent.com/3971226/57613398-32d3ea00-7590-11e9-8fbc-0634fa8fc6e7.gif)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
This has been fixed in future v1.1.0.
