### ISSUE TITLE
Notify in 1.0, no detail..

### ISSUE THREAD

**Issue by xeor** [quasarframework/quasar#4108]
### Software version
Quasar: quasar - 1.0.0-beta.21

### Whats wrong
Pre 1.0, Notify had both `message` and `detail`, where `detail` could be used to show some additional context of the message. This is gone in v1>

### What were you expecting?
Either a `detail` option, or a way to use html when using `Notify`. Anything that could do the same would do.

### What steps did you take, to get the error?
Trying to port over old code to v1

**Comment by nothingismagick** [comment]
Have you looked at this example:

https://v1.quasar-framework.org/quasar-plugins/notify#Example--Positioning-%26-different-options

![Screen Shot 2019-05-13 at 21 17 41](https://user-images.githubusercontent.com/35242872/57647970-9d9f1880-75c4-11e9-85d1-82df4509b0ff.png)

Also, please visit the Discord server or use the Forum for questions of usage.

**Comment by xeor** [comment]
Thanks for the tip.. I did look at all the options before making this issue. The multiline option is not doing it when you want more context in your notification..

The detail option before was a bare minimum, now there are no way of making the notification pretty unless you don't hear a lot of text..

Might be forced to move to an external notice lib :(

**Comment by nothingismagick** [comment]
Well, without getting too political and hopefully you don't take this the wrong way - but:

1. we are still in beta and 
2. no one here is forcing you to do anything

In accordance with free and open source software, you are free to use this framework or not - as you feel it helps you do the stuff you need getting done. You are also free to help us by filing issues and making pull requests. You are also free to include other libraries if you need something that we can't or are unable to provide. 

So the point is - you a free to use an external lib. Not forced. You can also help us make quasar better, but we are not required to do anything just as you are not entitled to anything. This is a community where we all pull on the same rope.

**Comment by xeor** [comment]
Sorry, but my comment was not ment as a trigger for a heated discussion. I am well aware how this all works..

I did file it as an issue, because there was something that was working well im the old version, but I hoped wasn't out of scope for a final 1.0 release..

I'm not sure what an elegant solution would be. A template or a useHtml boolean both feels like something that doesn't quite fit the design..

Do you want the notification plugin to be used to a bare minimum, or are you open for discussions?

I'm fine with an external lib, it just feel like that little 'detail' attribute was something I was going to use a lot..

Thanks for the great work you guys are doing

**Comment by nothingismagick** [comment]
> Sorry, but my comment was not ment as a trigger for a heated discussion. I
> am well aware how this all works.
>
It's all good, I am just a little sensitive about the ecosystem and I hate
it when people seem like they're going to give up. Glad to see you're not
that type of dev!

As far as what we want, well I don't know offhand why another prop couldn't
be added. Did you look at the source code? Why not make a proposal?

>

**Comment by xeor** [comment]
I did look at the source (https://github.com/quasarframework/quasar/blob/4691db529a1b4055b2c198888f6c9eb6f1fdf484/ui/src/plugins/Notify.js#L193), but havent used the `render` function that much, so I fell off a quick-fix... :)

Doing a `detail` property might work in most cases, but a `useHtml` bool would be much more powerfull (however, should come with a security warning).. What do you think? Or maybe both?

My usecase is something like this:

```
Notify.create({
  type: 'negative',
  position: 'top',
  message: `Error talking to backend:<br>
  Unable to talk to our backend (${networkError})..
  `,
  timeout: 0,
  actions: [
    {
      label: 'Refresh page',
      noDismiss: true,
      handler: () => {
        location.reload()
      }
    }
  ]
})
```

Not sure if `useHtml` would be able to inject the `networkError` tho..

**Comment by rstoenescu** [comment]
`html: true` prop can now be used for rendering HTML in v1
