### ISSUE TITLE
[Request] Various Toast position and animation

### ISSUE THREAD

**Issue by reignmaker** [quasarframework/quasar#411]
Would be great to have an option to show Toast not only at the bottom of the screen.
For example i want to show toast at the top with appropriate animation.

Thank you for your great efforts to make such a comprehensive UI framework.

**Comment by rstoenescu** [comment]
Will do, but it may take some time.

**Comment by vitaly-ignatovich** [comment]
Are there any plant to implement this functionality?

**Comment by rstoenescu** [comment]
Yes. In v0.14 there will be possible to also use a new component called Alert (does not replace Toast), which can be placed in any corner and the animation is customizable.

**Comment by vitaly-ignatovich** [comment]
When V0.14 release is expected?

**Comment by rstoenescu** [comment]
http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list

**Comment by rstoenescu** [comment]
Alert in v0.14 beta has all these.
