### ISSUE TITLE
[Feature Req] Add "IsValid" method to form controls

### ISSUE THREAD

**Issue by codegrue** [quasarframework/quasar#4111]
They currently have a "validate(value)" method, which can be used to derive an "IsValid", but it requires that you know and pass in the control's current value. IsValid would be cleaner with less boilerplate.

**Comment by lucasfernog** [comment]
If you don't pass the value, it uses the control model, like you want
https://github.com/quasarframework/quasar/blob/dev/ui/src/mixins/validate.js#L79

**Comment by codegrue** [comment]
Good to know! Thanks.
