### ISSUE TITLE
q-select QSelect autocomplete not displaying selected "label" value

### ISSUE THREAD

**Issue by wsmith-nwfsc** [quasarframework/quasar#4114]
### Software version
"quasar": "1.0.0-beta.23"
Windows 10
Node 10

### JsFiddle

https://jsfiddle.net/c1pv0ojh/5/

### What did you get as the error?
Upon selection, the q-select is not displaying the selection (but the model updates)
### What were you expecting?
This was working fine in beta-16, but  current update seems to have broken it.
I haven't upgraded in a while, so not sure when it crept in (so, tested in beta 23.)

### What steps did you take, to get the error?
See jsfiddle.
Make a selection or type a character, and click on the item.
Expected: the selected item displays whatever the "label" is set to (previously worked.)
Actual: the model is updated, but the label display is broken.

**Comment by wsmith-nwfsc** [comment]
This appears to be happening on https://v1.quasar-framework.org/vue-components/select as well, under "Autocomplete on more than 2 chars"

Thanks for looking at this!

**Comment by rstoenescu** [comment]
Use `fill-input` prop for that.

**Comment by wsmith-nwfsc** [comment]
I see, thanks! It appears the sample code needs to be updated since this behavior changed https://v1.quasar-framework.org/vue-components/select ("Autocomplete on more than 2 chars" is broken)

**Comment by rstoenescu** [comment]
Hi,

It's not broken. It just doesn't uses fill-input which is a valid choice. But regardless, added it. Thanks.
