### ISSUE TITLE
can't save an map in sessionstore

### ISSUE THREAD

**Issue by hiep164** [quasarframework/quasar#4118]
### SessionStoreWrapper.ts
![sessionStore](https://user-images.githubusercontent.com/41747511/57680425-c9b7a980-7657-11e9-94de-97ef23dee739.png)

### ProductList.vue
`private cartMap = new Map();`
![productList](https://user-images.githubusercontent.com/41747511/57680486-ef44b300-7657-11e9-9006-c92a19280b2a.png)

### Chorme Console
![console](https://user-images.githubusercontent.com/41747511/57680517-01beec80-7658-11e9-9dbf-6819c97be5cb.png)

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, Map type is unsupported for LocalStorage or SessionStorage.
