### ISSUE TITLE
[v1][Feature Request] Optionally focus errors on QForm

### ISSUE THREAD

**Issue by smcassar** [quasarframework/quasar#4119]
Based on a recent discord conversation, I'd like to make focusing on the first error in a QForm optional.

This would allow developers to call the validate function on a form to simply see if the form is valid without disrupting user interaction.

An example of this would be to listen to the blur event of an input to check if the entire form is valid and then toggling the submit button between enabled/disabled.

A basic (non functional) example of this can be seen here: https://jsfiddle.net/kq1bth90/

personal suggestion:
  * Add a `focus-errors` prop that allows error focusing to be disabled on submit
  * Add a `shouldFocus` argument to the `validate` method to handle manual calls to the method

**Comment by rstoenescu** [comment]
Will be available in future 1.0.0-beta.24 for QForm: new props ("no-error-focus", "no-reset-focus"); validate(shouldFocus) param as requested.
