### ISSUE TITLE
Calendar - after choosing year/month should go back to full calendar view with selected date

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#412]
After choosing year/month, Calendar should go back to full calendar view with selected date by default.
It is what is expected intuitive by people.
Hope you agree.

**Comment by rstoenescu** [comment]
I remember a ticket at some point requesting the opposite :)

**Comment by murbanowicz** [comment]
I don't but maybe discuss it. Almost every calendar over web does it...

**Comment by rstoenescu** [comment]
Ok, seeing that too. Will change it back.

**Comment by rstoenescu** [comment]
Will be available in v0.14.
