### ISSUE TITLE
Using quasar as a VUE plugin

### ISSUE THREAD

**Issue by acamenhas** [quasarframework/quasar#4125]
Hi all,

I've created a VUE project, thru vue cli and installed quasar.

I'm receiving this error in main.ts file, but seams everything working ok on the browser:

```
Module '"../../../../../Users/arturcamenhas/Projects/base/node_modules/quasar/dist/types"' has no exported member 'Quasar'.
    10 | import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
    11 | import {
  > 12 |   Quasar, 
       |   ^
    13 |   QLayout,
    14 |   QHeader,
    15 |   QDrawer,
```

How can i fix this? I'm using quasar beta.

Thank you

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by acamenhas** [comment]
Hi Scott,
My bad, i'm sorry.
I'll use other ways to put my doubts.

Thanks again
