### ISSUE TITLE
[v1] Scroll issues with containerized Layout inside Dialog on iOS

### ISSUE THREAD

**Issue by tegola** [quasarframework/quasar#4127]
I'm using a `<q-layout container>` inside a `<q-dialog>` on a Cordova iOS app, and I noticed a couple bad scrolling issues.

After investigating a little bit I noticed that even the demo on the docs has the same issues: https://v1.quasar-framework.org/vue-components/dialog#Example--With-containerized-QLayout

Here's a screen cap: https://imgur.com/a/TAr14xf

As you can see, the toolbar is cut off and, when at start/end of the scroll view, the view behind is scrolled instead.

On a desktop browser and on Chrome on Android there are no such issues.

**Comment by fergusmeiklejohn** [comment]
I also see this issue

**Comment by lxmfly123** [comment]
The background content should not scroll when a dialog popped.

**Comment by lxmfly123** [comment]
The solution below fix the problem on iOS Safari.

https://github.com/willmcpo/body-scroll-lock

**Comment by tegola** [comment]
Thanks, I'll try it ASAP, I'm actually busy with another section of my app.

@rstoenescu are you aware of this? Is it something you want to include in quasar?

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6

**Comment by rstoenescu** [comment]
Sorry, one more problem needs fixing. Reopening.

**Comment by summerinsect** [comment]
I got this issue on Android

**Comment by rooneyl** [comment]
Wondering if we have a workaround for this until it gets fixed?

**Comment by ibrainventures** [comment]
to get / work there some progress .. only for the "records":

flickering: (all from the quasar doc pages):

  containerized qlayout :  .> inside the lorem ipsum content area
  not flickering : inside the qdrawer element

not flickering also on basic scroll and fixed size dialogs

tested on ios 12.1x and 12.2  / ipads and iphones

**Comment by 9527Lin** [comment]
## An easy solution to the jitter problem at the head and tail of the layout layout in the dialog:

* 1: Register the following code as a global directive

* 2: Add a **div** under the **q-page** element and add the **v-fixLayoutJitter** 

### example

[https://youtu.be/mxFkz0KqX4s](url)

### html template：
```html
    <q-layout view="hHh Lpr fFf" container>
        <q-header>...header content</q-header>
        <q-footer>...footer content </q-footer>
        <q-page-container>
            <q-page>
                <div v-fixLayoutJitter="{bottom:64}">
                  ...page content
                </div>
         </q-page>
        </q-page-container>
    </q-layout>
```

### fix code:
```javascript
import Vue from 'vue'
    Vue.directive('fixLayoutJitter', function(el, binding, vnode) {
        // The bottom and top values are defined according to the height of the q-header and q-footer
        const value = binding.value
        const top = value ? value.top : 0
        const bottom = value ? value.bottom : 0
        el.style.position = 'fixed'
        el.style.width = '100%'
        el.style.top = `${top}px`
        el.style.bottom = `${bottom}px`
        el.style.height = 'auto'
        el.style.overflow = 'auto'
    })
```

### Tips
**It's not a particularly elegant solution, but it solves the problems that are currently encountered. I hope the official can solve this bug and make quasar even better.**

**Comment by janne-rantala** [comment]
None of the above mentioned fixes didn't work for me, but I managed to find a work-around solution:

Just add this CSS line to main css file and it will affect to all containerized QLayouts, including those that are embedded in QDialog:

`.q-layout-container .q-layout.q-layout--containerized {
    position:unset !important;
}`

Also, this CSS might help as well for IOS touch screen:

`<q-layout view="hHh Lpr fFf" container style="overflow-y:scroll;-webkit-overflow-scrolling:touch">`

**Comment by ibrainventures** [comment]
may we can use this issue to collect all ideas :-)

to prevent the ios safari toolbar / footerbar to occur .. and limit the content area:

  .q-body--prevent-scroll {
    position: unset !important;
  }

i dont know about the influence on the core ...

**Comment by ibrainventures** [comment]
@janne-rantala  i also extented to:

  .q-body--prevent-scroll {
    position: -webkit-sticky !important;
  }
to get rid of the ios safari tab/toolbar .. so may we got some progress here ..
did your css-ing also helps to slide up the dialog for input fields (not hidden by the virtual keyboard) ?

This is my last - but majored problem with "non seamless" dialogs .. (container / uncontainized ..)

**Comment by rstoenescu** [comment]
This should have been closed long time ago (commit above).
We've done all that we can, given the buggy iOS platform. Unfortunately, it's still not perfect but it's the best that can be done.
