### ISSUE TITLE
[v1] quasar describe case sensitive

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#4130]
Based on the following line, I get why this is the case but I think it would be nice if it wasn't. I assume it's only case sensitive on *nix systems because it's trying to get the file path.

https://github.com/quasarframework/quasar/blob/5d2fb6c96bff6095236f8ca6fe07a037e32e06b3/app/bin/quasar-describe#L90

I'd be happy to do a PR for this but TBH I'm not sure the best way to go about changing it. The only way that comes to mind is to loop the `quasar/dist/api/` dir, find the folder that matches (regardless of case) and then require that folder as it's named.

**Comment by rstoenescu** [comment]
@webnoob I think we can do the other way around, which is to transform the command line parameter to the right case first, then leave the rest of the logic as is. What do you think?
