### ISSUE TITLE
[v1] Unwanted padding/element in q-table header

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4132]
Hello!

This is quite common scenario when you want to have something rendered inside q-table header conditionally.

Steps to reproduce:
1) Hide table's "top" slot via v-if
2) Unwanted padding is added (due to empty element `<div class="q-table__top relative-position row items-center"></div>`)

Example: https://codepen.io/anon/pen/rgmNmj
![Screen Shot 2019-05-16 at 16 38 19](https://user-images.githubusercontent.com/3635352/57858105-1be40080-77f9-11e9-841b-5b84172b4184.png)

Expected:
No padding should be added if slot is disabled.

Thanks

**Comment by rstoenescu** [comment]
Use Vue's new slot syntax (`<template v-slot:.......`).
https://codepen.io/rstoenescu/pen/mYmdvY

**Comment by JoepLijnen** [comment]
I apologize for necroing an old thread, but I just ran into this and want to leave some advice for posterity; while neither me nor a colleague managed to use the vue slots to get "rid" of the empty element I did manage to do so using this construction in css:


`  div.q-table__top {
    display: none;
  }`
  
  ideally, the above should of course be prefixed/be made specific to a class that you've assigned to the specific q-table, such that the style is not applied to all q-tables. (unless that is your intention)
