### ISSUE TITLE
default-year-month prop of QDate not working as expected

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#4133]
Currently the `default-year-date` prop of QDate does not seem to be working at all.

This can be seen in the [docs](https://v1.quasar-framework.org/vue-components/date#Example--Default-year-month)

Issue filed after suggestion by @nothingismagick

**Comment by rstoenescu** [comment]
1. It's called `default-year-month`
2. It works as designed. When model is empty then the view shows the year and month indicated.

This does not works as you might think. If you need a default model, just initialize the model with that value, otherwise it doesn't makes any sense.

**Comment by rstoenescu** [comment]
It has nothing to do with the model.
