### ISSUE TITLE
QDialog does not get data-v-* attribute for scoped styles

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#4141]
### Software version

Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 10.15.0

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.3
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.0.0-beta.24 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.26 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.4 -- Babel compiler core.
  webpack - 4.28.4 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### Code

Contrived/simplified example in a Single File Component (SFC) :
```
<template>
  <q-dialog content-class="dialog" v-model="showDialog">
    <q-card>
      <q-card-actions class="justify-center">
        <q-btn v-close-popup>Cancel</q-btn>
        <q-btn v-close-popup>OK</q-btn>
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

<style scoped>
.dialog {
  width: 100px;
}
</style>
```

### What was the problem?

No data-v-* attributes show up on the divs with either q-dialog or q-dialog__inner as a class, which means that the "dialog" CSS class definition has to be in a non-scoped style block, even though most of the other components have the data-v-* attribute (from being in the scoped style block).

(This is not a high-priority issue, as I have worked around it.  Just thought I would report it.)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Unfortunately, this cannot be overcome by using vue-loader's scoped feature. QDialog (and QMenu) use Quasar Portals (required due its many other benefits, including fixes for iOS). However, you should indeed use a custom CSS class name instead of relying on `scoped` for browser paint render speed too.
