### ISSUE TITLE
Multi-line hint text extends beyond bottom of input container

### ISSUE THREAD

**Issue by baggachipz** [quasarframework/quasar#4142]
https://codepen.io/anon/pen/BeZbdq

When a field's hint is too long, it wraps according to the column width but overflows out of the rendering box for the input element container. Ideal behavior would be to stretch the input container so that subsequent elements aren't overlapped.

**Comment by nothingismagick** [comment]
From the SPEC: https://material.io/design/components/text-fields.html

1. Helper text
Helper text conveys additional guidance about the input field, such as how it will be used. It should only take up **a single line**, being persistently visible or visible only on focus.

2. Error message
When text input isn’t accepted, an error message can display instructions on how to fix it. Error messages are displayed below the input line, replacing helper text until fixed.

**Comment by baggachipz** [comment]
Understood, This is not a bug if that's the MD spec. Thanks for the attention.

**Comment by vkurko** [comment]
This is a very common case when you have multi-line hints, especially in multilingual applications, where the translation of a phrase can be much longer than the English version.

In Vuetify multi-line hints work fine.

Please provide a solution in Quasar.

**Comment by rstoenescu** [comment]
@vkurko 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/4665641/147445087-3ae15b46-cbd8-4cff-8c80-ef0830cee67f.png">
