### ISSUE TITLE
Persian Calendar has issue with today, yesterday and tomorrow

### ISSUE THREAD

**Issue by alphaelf** [quasarframework/quasar#4147]
i check [codepen example of persian calendar](https://codepen.io/rstoenescu/pen/wOGpZg) and realize it has issue with today, yesterday and tomorrow when selecting them it adds 3 days to selected date

**Comment by rstoenescu** [comment]
Hi,

What is the problem exactly? Can you specify step by step instructions please? Thanks.

**Comment by alphaelf** [comment]
i make a video to describe the issue, it's very clear
[Quasar persian calendar issue](https://drive.google.com/open?id=1sFg8FYGOgJJ8zpLu6KsCS7IFYxMkQzfV)

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting. Fixed the regression in future v1-rc.1.
