### ISSUE TITLE
QBtnDropdown requires Material Design icons

### ISSUE THREAD

**Issue by JavierElices** [quasarframework/quasar#4148]
Unless I am missing something, the use of the `QBtnDropdown` component requires the inclusion of Material Design icons. When not including them the text `arrow_drop_down` shows instead of the "caret down" icon. The API allows for an `icon` and an `icon-right` but these only add an icon before of after the `label`.

  In order to avoid the inclusion of the Material Design icons, either the control should adapt to the icon libraries present or it could add a new property like `icon-caret` to the API. For instance, using Font Awesome v5, you would use `icon-caret="fas fa-caret-down"`.

  I have tested this with v1.0.0-beta-24 and everything else up to date as of today, but I believe that the same is happening with previous versions.

  So to reproduce any icon library may be tried; for instance in `quasar.conf.js`:

    ...
    extras: [
      'roboto-font',
      //'material-icons', // optional, you are not bound to it
      // 'ionicons-v4',
      // 'mdi-v3',
      'fontawesome-v5'
      // 'eva-icons'
    ],
    ...

**Comment by rstoenescu** [comment]
Hi,

You've installed an icon library. That's great. But if you want Quasar to use that icon library for itself too, you need to specify it: https://v1.quasar-framework.org/options/quasar-icon-sets

**Comment by JavierElices** [comment]
Yes, you are totally right. I missed that bit in the documentation. Thank you for pointing it out!

**Comment by smolinari** [comment]
If your issue starts with "Unless I am missing something", it's better to use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions or getting certainty. You'll get answers there for sure and if it ends up a bug, then you can report it here. 

Thanks. 😄 

Scott
