### ISSUE TITLE
[v1] Incorrect label when using emit-value on QSelect

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4149]
Hello!

When using an array of objects as select options you can use `emit-value` prop to update the model with the value only and not the entire object. In this scenario label is displayed incorrectly. Value is displayed instead.

Steps to reproduce:
1) Use array of objects as select options [{ value: 0, label: 'Foo' }]
2) Select element
3) Value is displayed inside select. Should be label instead

Example: https://jsfiddle.net/pkobm7xL/1/

Thanks!

**Comment by pdanpdan** [comment]
Also use `map-options` if you want to find the objects from values.

**Comment by jean-moldovan** [comment]
@pdanpdan , Thanks, I don't see why Quasar wouldn't do it for me if label is present.
Label should be displayed consistently regardless of `emit-value` prop if and object has a label.

**Comment by pdanpdan** [comment]
Because we expect the full selected option, not only the value, and you have to tell QSelect what kind of info you have on model.

**Comment by jean-moldovan** [comment]
I suggest that `emit-value` prop affects model only and not how the label is displayed. Seems more consistent that way.

Default:
1) Select an option
2) Model is updated with object
3) Label is taken from `label` prop if present

With `emit-value` set to true:
1) Select an option
2) Model is updated with value prop of an object
3) Label is taken from `label` prop if present

**Comment by rstoenescu** [comment]
Please use emit-value along with map-options for your use case. If we do map-options automatically not only do we lose a bit of perf at runtime, but we also break other use-cases of QSelect.

**Comment by rathga** [comment]
Just to add to this, I agree with the OP that it is counterintuitive and inconsistent to be emitting one thing on @input and taking a different thing for :value.  It even says in the API docs that emit-value changes the MODEL to value, which it doesn't - it only changes the emit.  It's taken me quite some time today to figure this out.

**Comment by rstoenescu** [comment]
@rathga The property name is "emit-value"... "emit-*". The description says "Update model with the value of the selected option instead of the whole option" ---> update model because "input" event is part of how v-model works (:value - input pair).

Regarding emitting one thing and taking different thing for value -> there are use-cases for this and if I'm not mistaken they are in the docs already.

**Comment by rathga** [comment]
Noted - but can I at least suggest referring to map-options in the API docs entry for emit-value given they will be frequently used together (just as the entry for map-options already does for emit-value).  Otherwise I'm sure some people will be repeating the same digging.

Cheers
