### ISSUE TITLE
q-toogle to initiate with false if got udefined

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#415]
Q-toogle should initiate with false if got undefined with prop. Much easier to work with and not necessary to add additional code every time to handle it and prevent crashed. 
Hope you agree.

**Comment by rstoenescu** [comment]
Hi,

I think you're talking about v-model being undefined, right?
In such case, what's the use of any form component if you can't control it (don't make any scope variable binded to it)?

I tend to make all components as lightest as possible to maintain runtime performance. Adding additional logic to handle this case would decrease perf a little, but it counts when you got lot of form components on a page and running on a mobile phone.

I would only add this if there is a solid case for it. Won't add it just to make scaffolding easier. Please explain your case.

**Comment by rstoenescu** [comment]
Please reopen with solid case. Thanks!

**Comment by NothingWeAre** [comment]
Hello.
I may have valid usecase for support of `undefined` as initial values in toggles and checkboxes.

I have model 
```
counterparty = {
client: Boolean,
contractor: Boolean
}
```
Which is ok, if i reciving it from server. But to simplify creation of new object i prever settin initial value as `{}`
In this case both properties initial state is `undefined`.
By the way, in my case back-end consider non present options as false.

Another situation in which initial values can be `undefined` is if component displayed before data loaded from ajax query.

**Comment by rstoenescu** [comment]
Hi,

Case 1. Not receiving enough data from server.
===
When you receive data, initialize your scope ($data) with the correct data, meaning put a boolean prop there if it's missing from the server response. It's a bit more work to do, but it's the right way to do it as it guarantees your app is in a healthy state.

Case 2. Data not yet loaded.
===
You should NOT display any UI part to the user if it's not ready. Use [spinners](http://quasar-framework.org/components/spinners.html) or [Loading](http://quasar-framework.org/components/loading.html) components to show user something is happening under the covers (ajax requests etc) and combine with `v-if`s. Vue Router's documentation also offers a nice alternative in its guide (https://router.vuejs.org/en/advanced/data-fetching.html).

---

Displaying an unusable toggle (or any other form component for this matter) is not something any user would expect. I hope you agree.

Cheers,
Razvan
