### ISSUE TITLE
[v1] Popup Edit persistent property not working as expect (closing with escape key)

### ISSUE THREAD

**Issue by botura** [quasarframework/quasar#4150]
v1.0.0-beta.24

According to documentation `persistente` prop denies the user from closing the popup with the escape key or clicking/ tapping outside of the popup.

That is not happening in the example
[https://v1.quasar-framework.org/vue-components/popup-edit#Example--Persistent-edit%2C-and-with-buttons](https://v1.quasar-framework.org/vue-components/popup-edit#Example--Persistent-edit%2C-and-with-buttons)

Clicking on Carbs prop to edit, user can close the popup with escape key.

I think that the persistente prop should also block user to click any other component while popup is open. Not sure if this is the actual desired behavior and is bug too.

**Comment by pdanpdan** [comment]
About `persistent` allowing dismissal by `ESC` it's a bug, will get fixed.
About blocking other popups to open think about if you have a QSelect or a QBtnDropdown inside the QPopupEdit :)

**Comment by rstoenescu** [comment]
Fix will be available in v1-rc.1
