### ISSUE TITLE
Long Label overlaps clearable button in Q-Select (0.17.24)

### ISSUE THREAD

**Issue by stevebor1** [quasarframework/quasar#4156]
### Software version
Operating System                Windows_NT(10.0.17763) - win32/x64
NodeJs                          10.14.2

Global packages
  NPM                           6.9.0
  yarn                          1.12.3
  quasar-cli                    0.17.24
  vue-cli                       2.9.6
  cordova                       8.0.0

Important local packages
  
### JsFiddle
https://codepen.io/stevebor1/pen/PvJQyG

### What did you get as the error?
The display of the selected option's label appears to overlap the clear button and select drowpdown icon

### What were you expecting?
The label should be truncated

### What steps did you take, to get the error?
Created a Select field in a width-constrained div, then add an option to the select field with a very long name.

![image](https://user-images.githubusercontent.com/1202448/58056537-5067fd00-7b16-11e9-83dd-53aa48d1366a.png)

**Comment by rstoenescu** [comment]
FYI: This has been fixed in v1.

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1, which I recommend to upgrade to as soon as possible.
If your business requires this fix in 0.17, let me know. But just to paint the bigger picture: fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this.

Thanks.

**Comment by stevebor1** [comment]
I've ended up limiting the number of characters for the display value. So that workaround is fine. Regarding upgrading to v1; I recently built this app on .17 and will have to evaluate the upgrade processes and general style changes, but I hope to upgrade soon after it is released.
