### ISSUE TITLE
[v1] QDate doesn't work correctly with mask="x" (or mask="X")

### ISSUE THREAD

**Issue by qcfe** [quasarframework/quasar#4157]
### Software version

Quasar: 1.0.0-beta.24
OS: Windows 10 1903
Node: v10.15.3
NPM: 6.4.1
Browsers: Firefox, Chromium based

### JsFiddle
https://codepen.io/qcfe/pen/YbreBX

### What did you get as the error?
The QDate value is set correctly but then the component breaks, showing various undefined/nulls in the header, and the day selection gets lost.

### What were you expecting?
Normal behavior of QDate.

### What steps did you take, to get the error?
Click on a date on the QDate component.

**Comment by rstoenescu** [comment]
Fix will be available in v1-rc.1
