### ISSUE TITLE
[V1] Request for QDate / QTime options improvments

### ISSUE THREAD

**Issue by irongomme** [quasarframework/quasar#4160]
In the current state, QDate options let us define wich dates are selectables, and it work fine ! But, it is a common job to restrict dates against another date field, to have a range. If we have 2 QDate combined with 2 Qtime, we have to write 4 methods to achieve this. 

So, what about to have a second argument in the options function, to reference the caller component, and let us do this in a more dynamic way ?

**Comment by pdanpdan** [comment]
You can use a single options function and pass the second argument as desired:

```html
<q-date ... :options="date => isDateSelectable(date, 'start') />
<q-date ... :options="date => isDateSelectable(date, 'end') />
```
