### ISSUE TITLE
beta.24 QUploader factory is not working

### ISSUE THREAD

**Issue by jiaxincui** [quasarframework/quasar#4165]
beta.24 QUploader factory is not working

**Comment by nothingismagick** [comment]
Thanks for reporting @jiaxincui , but please provide at least the basic information requested in the issue template, like OS and the results of `quasar info`. Merely saying it is not working does not help us to triage the issue.

**Comment by jiaxincui** [comment]
sorry!

when i use factory, When I try to return to a promise, it doesn't work.
And there's no error message, just stay in the process.
And I also saw this problem in doc.

https://v1.quasar-framework.org/vue-components/uploader


```
Operating System - Linux(3.10.0-957.12.1.el7.x86_64) - linux/x64
NodeJs - 8.16.0

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.6
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.24 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.26 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - localhost.localdomain
  enp3s0 - 192.168.1.120
```

**Comment by nothingismagick** [comment]
First of all:
your quasar cli is outdated. run:
`$ npm install -g @quasar/cli`

Next:  have you installed the local dependencies with npm? If so:
Remove node_modules and package-lock.json and run
```
$ yarn install
```

Next: Please consider upgrading to node 10LTS - this is not likely to be your problem, but I have to recommend it because 8LTS is coming to the end of its lifetime.

**Comment by nothingismagick** [comment]
Also, do you have a backend to receive the files?
![Screen Shot 2019-05-21 at 12 00 38](https://user-images.githubusercontent.com/35242872/58087077-21a66100-7bc0-11e9-8d54-9ba695c1e9e3.png)

**Comment by jiaxincui** [comment]
The back end did not receive any requests.
and chrome browser did not any request

**Comment by rstoenescu** [comment]
@jiaxincui Please post your usage and handlers.

**Comment by jiaxincui** [comment]
@rstoenescu 

on docs https://v1.quasar-framework.org/vue-components/uploader at factory section,

docs source code is follows
```
 factoryFn (files) {
      // returning a Promise

      return new Promise((resolve) => {
        // simulating a delay of 2 seconds
        setTimeout(() => {
          resolve({
            url: 'http://localhost:4444/upload'
          })
        }, 2000)
      })
    }
```


i try upload a pic, when click upload btn , there's no error message, just stay in the process.
In fact, you should send a request.

but , i open chrome dev tool no requests were sent.

**Comment by jiaxincui** [comment]
> First of all:
> your quasar cli is outdated. run:
> `$ npm install -g @quasar/cli`
> 
> Next: have you installed the local dependencies with npm? If so:
> Remove node_modules and package-lock.json and run
> 
> ```
> $ yarn install
> ```
> 
> Next: Please consider upgrading to node 10LTS - this is not likely to be your problem, but I have to recommend it because 8LTS is coming to the end of its lifetime.

@nothingismagick 

I have followed your instructions,but the problem still exists.
This problem also occurs in documents.
Specific description I mentioned in my last reply。
https://github.com/quasarframework/quasar/issues/4165#issuecomment-494612656

**Comment by rstoenescu** [comment]
Fix will be available in v1-rc.1
