### ISSUE TITLE
Possible bug in QImg and a request to be able to reset hasError

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#4167]
I am having trouble using QImg as described in [this stackoverflow](https://stackoverflow.com/questions/56224266/javascript-image-triggers-errors-when-downloading-unclear-why) issue (with a [codesandbox](https://codesandbox.io/s/quasar-v1-qimg-onerror-in-chrome-6pcqp?fontsize=14)). Is this a Quasar bug? If not, then at least it would be nice to be able to [reset](https://github.com/quasarframework/quasar/blob/6b7fd29a344b1ddaa02ebd5319a3bb6877ed14e7/ui/src/components/img/QImg.js#L86) the `hasError` to `false`, as now the image does get a succesful upload (probably after failing first) but the status of `hasError` remains `true`.

**Comment by rstoenescu** [comment]
Hi,

Looked at your example. In Example.vue, you should reference the `src` prop correctly:

```js
// before, incorrect
:src="pic"

// after, correct
:src="pic.id"
```

**Comment by musicformellons** [comment]
Thanks for looking into it. The pictures do not load at all after you suggested change!? Could you have another look please?

**Comment by musicformellons** [comment]
Here a more lightweight [jsfiddle](https://jsfiddle.net/musicformellons/8acqs30f/10/) showing exact same behavior.

**Comment by rstoenescu** [comment]
Dan root caused it. It's due to image.decode(). Will get a fix in rc.1.

**Comment by rstoenescu** [comment]
Fix will be available in v1-rc.1.

If you are using big-sized image files, I suggest you also take advantage of the `placeholder-src` prop to display a very small image while the big one is getting loaded.

Also, seems like Chrome changed the caching algorithm for images. So you'll see a trashy performance when developer tools are opened (or you've checked the "disable cache" option).
