### ISSUE TITLE
[V1] [Request] Date Utils - getDateObject function

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#4169]
@rstoenescu 

Hi!

We discuss this in Discord chat and as I can understand you says, that in b24 will be new function in Date utils: `getDateObject(str[, mask[, locale]])`.
In my case, I have `QInput` with custom string in format `"DD/MM/YYYY HH:mm"` and I want to build  Date object from this string.
Unfortunately, I can't find this function in UMD version.
Also, I can't find function `splitDate(str[, mask[, locale]])`.
This functions will be available latter in RC?

Thanks!

**Comment by pdanpdan** [comment]
The public function is `extractDate`. The split function is internal.

**Comment by rstoenescu** [comment]
@olegvakulenko Hi, yes, what you are looking for is `extractDate`, documented [here](https://v1.quasar-framework.org/quasar-utils/date-utils#Extract-Date). For UMD: `Quasar.utils.date.extractDate`
