### ISSUE TITLE
[Request] Notify- Reconsider to allow to display html tag

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#4171]
I just want to create new issue to make sure to my comment will be noticed. 
From the issue https://github.com/quasarframework/quasar/issues/2077#issuecomment-494668444 _([Request] Notify- Suggest allow to display html tag)_ .

There are also valid use-cases for adding html in Notify, like the ff:

1. Adding `<b></b>` or `<strong></strong>` for emphasis
2. Adding an anchor link `<a></a>` for external links
3. Controlling line breaks by adding `<br>` tags

I guess adding a button like "Show More" is quite overkill for those use-cases.
What if we can have a boolean option that can enable this feature so that it will not be a security flaw,
and the developer should make sure to sanitize the data they bind.
`{ html: true } // default: false`

**Comment by rstoenescu** [comment]
Will be available in v1-rc.1
