### ISSUE TITLE
[v1] Bad layout when setting gutter for row

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#4173]
Quasar version 1.0.0-beta.24

The layout seems to be messed up when setting gutter for a row. Please see the following pen:
https://codepen.io/tomers-the-encoder/pen/ZNagNO?editors=1010

**Comment by pdanpdan** [comment]
Read here, please: https://v1.quasar-framework.org/layout/grid/gutter#Pros%2C-cons-and-how-to-workaround-problems---%E2%80%9Cq-gutter-%7Bsize%7D%E2%80%9D-vs.-%E2%80%9Cq-col-gutter-%7Bsize%7D%E2%80%9D

**Comment by tomers** [comment]
Thanks. Understood. The documentation is very thorough
