### ISSUE TITLE
[Feature] Allow QDate to have separate input and output masks

### ISSUE THREAD

**Issue by ymhr** [quasarframework/quasar#4176]
Currently we can add a `mask` prop to `QDate` to change the format of the date, and this is great. However, it would be nice to have a separate mask for the input and the output, which would allow, for example,  dates to be stored in ISO 8601, but displayed in a more human readable way, such as `DD/MM/YYYY`.

**Comment by pdanpdan** [comment]
QDate and QTime need to be able to read what they write, so the mask has to be the same. But you can always convert it to anything you want. Just hook into `@input` and convert and store the converted value.
