### ISSUE TITLE
[v1 - beta.24] QTooltip not showing on button with "disable" prop

### ISSUE THREAD

**Issue by HaisojYellams** [quasarframework/quasar#4179]
### Software version

Quasar: v1.0.0-beta.24
@quasar/app (v1+ only): v1.0.0-beta.26

### JsFiddle
v1 fiddle: https://jsfiddle.net/HaisojYellams/c1ryzjvp/3/

old v0 fiddle: https://jsfiddle.net/smolinari/30f2hdvn/1/

### What did you get as the error?
Tooltips do not show on buttons with the "disable" prop

### What were you expecting?
Tooltips to show on a button with the "disable" prop.

### What steps did you take, to get the error?
Put a tooltip on a button with the "disable" prop. See fiddle above. I know this worked in previous versions (see the v0 fiddle above).

**Comment by pdanpdan** [comment]
It was an error in the previous version - the button was not disabled.
It will still work if you use `type="a"` to the button.
If you need a `type="button"` the solution is to wrap the button in a div and put the tooltip inside that div too.

**Comment by HaisojYellams** [comment]
Thanks for the quick response! 

In case anyone else looks here with the same issue, the `type="a"` solution won't work on disabled QFabAction elements, but the div wrapping method seems to work just fine.

**Comment by rstoenescu** [comment]
This is due to disabled native buttons not emitting almost any kind of events.

**Comment by Powersource** [comment]
Fun fact, the tooltip *does* show in firefox, but not chrome :grin:
