### ISSUE TITLE
QUploaderAddTrigger import failure (Q-Uploader Custom Header)

### ISSUE THREAD

**Issue by daniel-rau** [quasarframework/quasar#4184]
I am working on a Vue/Quasar (v.1.0 beta) project right now where I want to customize the headers for q-uploader.  When I try to add "QUploaderAddTrigger" to my quasar.conf.js file, I get the following error.

`Failed to compile.
./.quasar/import-quasar.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Unknown import from Quasar: QUploaderAddTrigger`

When I try to use <q-uploader-add-trigger /> without "QUploaderAddTrigger" imported, I get an error that says that <q-uploader-add-trigger /> is an unknown custom element.

Is there another way that I can do custom headers for q-uploader that has not been added to the docs yet, or is this a bug?

**Comment by rstoenescu** [comment]
Hi,

Upgrade to latest version of Quasar. `quasar` package should be at at least version beta.24.

**Comment by daniel-rau** [comment]
Thank you for the help.  This works for me now (I was on beta.11).

**Comment by rstoenescu** [comment]
It is paramount to keep dependencies up to date until final v1.
