### ISSUE TITLE
q-table locked to defined rows in pagination 

### ISSUE THREAD

**Issue by hounded** [quasarframework/quasar#4186]
### Software version

quasar - 1.0.0-beta.24 
codebase
  @quasar/app - 1.0.0-beta.26 -- Quasar Framework App CLI

### JsFiddle

https://codepen.io/anon/pen/wbywQa

### What did you get as the error?
Defining rowsPerPage in q-table, once defined won't let you select any other selection, or page

### What were you expecting?
To be able to define the default amount of rows and have the user still be able to select a different amount of rows and page

### What steps did you take, to get the error?
added the following to q-table
```javascript
      :pagination="{
        rowsPerPage:10
      }"
```

**Comment by pdanpdan** [comment]
https://v1.quasar-framework.org/vue-components/table#Pagination

First green block.

**Comment by hounded** [comment]
Thank you 

:astonished: 101 read the docs from the top
