### ISSUE TITLE
QVideo in Dialog component not allowing Vimeo thumbnail to be full width

### ISSUE THREAD

**Issue by fergusmeiklejohn** [quasarframework/quasar#4187]
### Software version

Quasar:
Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.9.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.24 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.26 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
Any other software related to your bug:

### CodePen
Quasar Framework v1 https://codepen.io/fergusmeiklejohn/pen/KLQKRQ
Click on the card button to launch the dialog
### What did you get as the error?
In a Dialog component, the QVideo component is not allowing the thumbnail to be full-width if I embed Vimeo
### What were you expecting?
The same full width thumbnail I see with a YouTube Embed

**Comment by rstoenescu** [comment]
Hi,

This is not a problem with Quasar, but with Vimeo embedded iframe. It applies the following style to the content DIV: `max-width: calc(189.63vh); height: calc(52.7344vw);`. And Quasar cannot override that.

I suggest you check out the Vimeo guide on embedding a video. Maybe there's a parameter on the URL that you can supply to QVideo so that the style I mentioned above won't be applied.

**Comment by nothingismagick** [comment]
you could also check out the QMediaPlayer app extension:

https://github.com/quasarframework/app-extension-qmediaplayer
