### ISSUE TITLE
[v0.17] Number input wrong behavior

### ISSUE THREAD

**Issue by VitalyEmelyanov** [quasarframework/quasar#4188]
### Software version

Quasar: v0.17.20
OS: Any
Browsers: Any

### JsFiddle

[HERE](https://jsfiddle.net/VitalyEmelyanov/xsja5Lot/)

### What did you get as the error?

When you delete the last character in the input with `type="number"`, the model is not updated and stays with the last value. It will update only when you focused out.

This causes errors when trying to validate the form. In JsFiddle you can clear the field and then click the Submit button (do not focus out the input).

With default input type it works properly

### What were you expecting?

The input with `type="number"` should clear model when it is empty

### What steps did you take, to get the error?

1. Focus on input
2. Type 1
3. Delete input with backspace (the model will still be 1)
4. You can click Submit button (without focusing out of the input)
5. Repeat the same with default input - it works properly.

![May-23-2019 12-17-01](https://user-images.githubusercontent.com/15330670/58240978-b93cb880-7d54-11e9-854f-54b36274c8c6.gif)

**Comment by rstoenescu** [comment]
Hi,

This is not a bug. QInput waits until it gets a valid number (or input loses focus). If we don't wait, then users will never be able to type "0.002" or "1." etc etc.. Parsing numbers is a very complex subject.

However, v1 works a bit different (relies entirely on Vue's v-model with its `.number` modifier) and you'll no longer experience this.
