### ISSUE TITLE
How to make bottom toolbar in left Drawer panel? Right margin - Bug

### ISSUE THREAD

**Issue by bigperson** [quasarframework/quasar#419]
Hi, how to make bottom toolbar in left Drawer panel? I use
```
 <q-drawer ref="leftDrawer">
  <div class="toolbar fixed-bottom">
    left Drawer toolbar
  </div>
</q-drawer>
```
But, i have bug in google chrome http://prntscr.com/edi7xy - right margin, which disappears when the browser window resize

This method is the same bug:
```
 <q-drawer ref="leftDrawer">
<div class="item fixed-bottom bg-primary text-white no-margin">
    <div class="item-content">
      left Drawer toolbar
    </div>
 </div>
```
Class `absolute-bottom` not working also

**Comment by rstoenescu** [comment]
Possible with v0.14. Check beta.
