### ISSUE TITLE
clicking outside a persistent dialogue makes the card remain blurry with a horizontal line

### ISSUE THREAD

**Issue by fergusmeiklejohn** [quasarframework/quasar#4191]
### Software version

Operating System - Darwin(18.5.0) - darwin/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.9.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.24 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.26 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

### Codepen
https://codepen.io/fergusmeiklejohn/pen/joZYbK

Can't reproduce well on Codepen

### What did you get as the error?
When I click outside a persistent dialog box the content stays slightly blurred with a horizontal line through it. clicking on a button in the dialogue returns it all sharp again. These two pics are blurry and normal for comparison.
![Blurry after clicking outside dialog box](https://user-images.githubusercontent.com/11864025/58255742-3b060380-7da0-11e9-8a20-9ba8d318600d.png)
![Normal](https://user-images.githubusercontent.com/11864025/58255743-3b060380-7da0-11e9-8c01-bd65274f05bb.png)

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1
