### ISSUE TITLE
[v1] QField with QRadio / QCheckbox does not look nice

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4192]
Hello!

When you put QRadio / QChackbox / QOptionGroup inside QField, the field label almost overlaps control. I think this needs to be improved.

Example: https://jsfiddle.net/rstoenescu/rmaodk0f

![Screen Shot 2019-05-23 at 16 22 03](https://user-images.githubusercontent.com/3635352/58256158-311bda80-7d77-11e9-94ee-2fc93faf0bb5.png)

Thanks!

**Comment by rstoenescu** [comment]
Hi,

Please fork then save the jsfiddle. The link that you indicated is the default jsfiddle. Thanks.

**Comment by jean-moldovan** [comment]
Sorry, https://jsfiddle.net/Le8r0f4m/

**Comment by rstoenescu** [comment]
Thanks for the second jsFiddle.

Well, this is somewhat obvious. QField doesn't manage your content. You should instead use `stack-label` along with `label` prop.

**Comment by rstoenescu** [comment]
https://jsfiddle.net/rstoenescu/9wz360px/2/
