### ISSUE TITLE
prevent body scroll with dialog on iOS

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#4194]
I test on browserstack and all iOS platforms get strange behaviour with q-dialog: body scrolls, but modal content periodically not scrolls. I found https://github.com/willmcpo/body-scroll-lock, but this package prevent both: body and modal scrolling. I cant understand how to cook this.

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, due to how iOS Safari works, this is not possible. We either disable any type of scrolling (which is out of the question) or leave it as is... Apple knows about this but won't fix...

**Comment by mesqueeb** [comment]
I came here because I'm experiencing:
Scrolling on a non-scrollable Q-Dialog will scroll the body content below it.

I tried adding `@touchstart.stop` to the wrapper div, but it didn't work.

Is this the same problem, a problem because of iOS Safari?

**Comment by rstoenescu** [comment]
The reported problem has been fixed and will be available in 1.1.0. Some serious engineering and innovation was required!
