### ISSUE TITLE
Animate Issue on IE11

### ISSUE THREAD

**Issue by dragospaulpop** [quasarframework/quasar#420]
Line 23 in animate.js causes an error in IE11. The browser doesn't know about the stop() function. Maybe  calling start.stop() would solve the issue. Chrome doesn't call stop either (as far as I can tell), it just silently fails.

Link to reproduce (stop should be called twice): http://jsbin.com/catopuzuja/edit?js,console,output

**Comment by rstoenescu** [comment]
Good catch. Will fix it and include in v0.13.2.

**Comment by smolinari** [comment]
Hey @dragospaulpop 

What were you trying to do, when you got the error?

Scott

**Comment by dragospaulpop** [comment]
@smolinari Testing the Drawer component in IE 11. Try it on the documentation page and you'll see it doesn't work (http://quasar-framework.org/components/drawer.html).

**Comment by rstoenescu** [comment]
Available in edge version and future v0.13.2
