### ISSUE TITLE
quasar-variables not imported in imported .styl files

### ISSUE THREAD

**Issue by steveclarke** [quasarframework/quasar#4201]
Quasar 1.0.0-beta.24

As of a recent fairly recent beta, Quasar stylus variables are automatically imported when the presence of a $ is detected (thus suggesting that a Stylus variable is referenced).

This works for .vue files and in the `css/app.styl` file, but does not work when variables are referenced in Stylus files imported from the `app.styl` file. i.e.

``` stylus
// app global css
@import './typography'
@import './layout'
```

This is because the imports aren't parsed when reviewing the content for the `$`.

A workaround is to reference a variable in the `app.styl` file or at least place a commented out `//$`.

**Comment by rstoenescu** [comment]
Caveat added in docs. Will be available on next docs deployment.
