### ISSUE TITLE
Unable to use css-loader in extendWebpack in quasar.conf.js

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/quasar#4202]
```
      extendWebpack (cfg) {
        cfg.module.rules.unshift(
          {
            test: /\.css$/,
            exclude: /node_modules/,
            "use": [
              {
                loader: 'css-loader',
                options: {
                  // enable CSS Modules
                  modules: true,
                  // customize generated class names
                  localIdentName: '[local]_[hash:base64:8]'
                }
              }
            ]
          }
        )
      },

```
 I get the error:
```
  CssSyntaxError: 
 Unknown word
  > 1 | // extracted by mini-css-extract-plugin
      | ^
```

**Comment by rstoenescu** [comment]
Hi,

There's already a css rule in place. Better use the `quasar inspect` command and tap into the current rule through `chainWebpack` in your quasar.conf.js.

Ultimately, use our [Discord](https://chat.quasar.dev) or [Forum](https://forum.quasar.dev) to get more details if you stumble into any trouble.

Regards,
Razvan

**Comment by CheyenneForbes** [comment]
Hey I asked on both but it was ignored on discord and on the forum I was basically told that what I was doing is unnecessary even though I stated my own reason which is based on my own experience

I tried the following code in the config but its not working

```
      chainWebpack (chain) {
        chain.module.rule("obfuscateStyles").test(/\.css$/).use('css-loader').options({
          'localIdentName': '[local]_[hash:base64:8]'
        })
      }
```

**Comment by CheyenneForbes** [comment]
👀

**Comment by CheyenneForbes** [comment]
Hi @rstoenescu can you assist me with this, please?
