### ISSUE TITLE
QDate's today-btn does not always update the calendar view to current month+year

### ISSUE THREAD

**Issue by modevelops** [quasarframework/quasar#4203]
### Software version

Quasar: v1.0.0-beta.24
@quasar/app (v1+ only): v1.0.0-beta.26
OS: Win10
Node: v8.11.2
NPM: v5.6.0
Browsers: Firefox Nightly 69.0a1 (2019-05-24) (64-Bit)

### JsFiddle
https://jsfiddle.net/9dmzweu5/2/

### What did you get as the error?
The today button in a QDate calender does not switch to its month and year, if the current selected date is already today.
### What were you expecting?
The today button should always update the selected month and year, even if the selected date is already today. 
### What steps did you take, to get the error?
It's quite common that the default selected date is today and the user browses through the calendar and wants to go back to today with only one click.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.3
