### ISSUE TITLE
[V1] QPopupProxy does not work reliably in IE11

### ISSUE THREAD

**Issue by dkr88** [quasarframework/quasar#4208]
Quasar 1.0.0 RC2 (also affects beta 24, earlier versions not tested)

In Internet Explorer 11, the popup content in a QPopupProxy sometimes does show. Inspecting the DOM reveals that the content is appended to the body and removed quickly before it is rendered. Sometimes the popup shows correctly. Failure rate seems to vary, but in the linked jsfiddle is about 50%.

This only affects desktop mode. In mobile mode, where the QPopupProxy renders as a dialog, it works fine.
 
https://jsfiddle.net/3vtnLm7z/2/embedded/result,css,html,js

**Comment by rstoenescu** [comment]
Fix will be available in rc.3.
