### ISSUE TITLE
Support v-bind:ref for q-tab's tagetElement

### ISSUE THREAD

**Issue by zhangweis** [quasarframework/quasar#421]
In http://quasar-framework.org/quasar-play/android/index.html#/showcase/layout/tabs, when I replace x-tab ref divs with following
`          <div v-for='tab in xTabsOptions' :key='tab.value' v-bind:ref="tab.value">
            Tab {{tab.label}} - {{tab.value}}
          </div>
`
I got following error when using v-bind:ref on q-tab ref div.
`Cannot set property 'display' of undefined
    at VueComponent.setTargetVisibility (eval at <anonymous> (app.js:1581), <anonymous>:7515:42)` 

After some inspection, I found it's caused by the way to get targetelement in /vue-components/tab/Tab.vue:71 where it's an array of div instead of div element.

**Comment by rstoenescu** [comment]
No longer relevant in v0.14. Tabs have been greatly improved and don't use Vue refs anymore.
