### ISSUE TITLE
 high severity vulnerabilities relating to  fstream and tar regarding Arbitrary File Overwrite

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#4211]
upgraded quasar to 1.0.0-rc.2 and now get: "found 12 high severity vulnerabilities" relating to  fstream and tar regarding 'Arbitrary File Overwrite'. `npm audit fix` can not fix it. After googling it seems to me dependencies need updating?!

Details (sorry for the scrambled layout...):
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > libcipm > │
│               │ npm-lifecycle > node-gyp > fstream                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > libcipm > │
│               │ npm-lifecycle > node-gyp > tar > fstream                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > libnpm >  │
│               │ npm-lifecycle > node-gyp > fstream                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > libnpm >  │
│               │ npm-lifecycle > node-gyp > tar > fstream                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > node-gyp  │
│               │ > fstream                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > node-gyp  │
│               │ > tar > fstream                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm >           │
│               │ npm-lifecycle > node-gyp > fstream                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm >           │
│               │ npm-lifecycle > node-gyp > tar > fstream                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > libcipm > │
│               │ npm-lifecycle > node-gyp > tar                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > libnpm >  │
│               │ npm-lifecycle > node-gyp > tar                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm > node-gyp  │
│               │ > tar                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/app [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @quasar/app > webpack > chrome-trace-event > npm >           │
│               │ npm-lifecycle > node-gyp > tar                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting. I would like to point out our official way of reporting security issues: https://quasar.dev/security/report-a-vulnerability

This seems to be an issue with a webpack dependency and I can confirm it got fixed.
Please upgrade to @quasar/cli and @quasar/app 1.0.0-rc.2 to ensure you have the latest and greatest (and check release notes). I can confirm that yarn audit now reports 0 vulnerabilities.

Regards,
Razvan Stoenescu
