### ISSUE TITLE
QSelect broken style in mobile view

### ISSUE THREAD

**Issue by larajulious** [quasarframework/quasar#4212]
I am trying to run the basic q-select using this [example](https://quasar.dev/vue-components/select#Filtering-and-autocomplete) but the output is this.

![image](https://user-images.githubusercontent.com/38279359/58397577-2ec1c500-8084-11e9-8256-8d3d6fc01b40.png)

I just copy and paste exactly in the example.

**Comment by pdanpdan** [comment]
Browser, OS, codepen showing the problem?

**Comment by larajulious** [comment]
> Browser, OS, codepen showing the problem?

I think the problem is the browser. when I try to run in edge it is working. but in chrome the style is broken.

**Comment by pdanpdan** [comment]
Please provide some codepen so we can check. We cannot guess what you're talking about.
Also I asked you for some more details, like browser (what version of chrome).

**Comment by larajulious** [comment]
> Please provide some codepen so we can check. We cannot guess what you're talking about.
> Also I asked you for some more details, like browser (what version of chrome).

Version no. 74.0.3729.157
Windows 64bit

[Codepen](https://codepen.io/pen/?&editable=true&editors=101)

**Comment by pdanpdan** [comment]
Common, you attached an empty codepen??? :)

**Comment by larajulious** [comment]
> Common, you attached an empty codepen??? :)
> Also from the image it looks like you're using mobile view from Chrome, is it right?

Sorry I updated the codepen :)
yes I am using the chrome in mobile view.

**Comment by larajulious** [comment]
I just observed right now. if the browser is in desktop view it is working fine. but if in mobile mobile the style broken. 

Chrome Version no. 74.0.3729.157

**Comment by rstoenescu** [comment]
@larajulious Hi, can you put into words what exactly seems wrong in the mobile mode? Thank you.

**Comment by larajulious** [comment]
> @larajulious Hi, can you put into words what exactly seems wrong in the mobile mode? Thank you.

Hi @rstoenescu the style in mobile view of qselect is broken. please see the screenshot below. here is the steps to see the bug. 
- Load the component in desktop view
- Change to mobile view then refresh the page while in mobile view.


**Desktop view**
![image](https://user-images.githubusercontent.com/38279359/58426157-4c1b8100-80ce-11e9-812d-286fb36b44fb.png)


**Mobile view**
![image](https://user-images.githubusercontent.com/38279359/58426229-7e2ce300-80ce-11e9-9157-5732a59cf01f.png)

**Comment by rstoenescu** [comment]
Hi, I saw the screenshots. But what is your expectation and what is actually happening. Saying "is broken" doesn't offer details. Is one pixel off? Is the header wrong, .... specify in words pls. Thanks.

**Comment by miketrebilcock** [comment]
It's not just mobile view - if you set screen resolution to 1024 x 768, it happens then too. At this resolution I would expect the dropdown to appear under the input field, but instead it appears at the top of the screen.

**Comment by pdanpdan** [comment]
When you put Chome's DevTools in mobile emulation mode, even in responsive mode, the default emulation is mobile with touch, so Quasar uses the path for mobile.

The problem is that neither I nor Razvan can reproduce the glitch in your image.

Can you inspect the CSS for the bottom blue border of the input box on top and tell us what is there?

I suppose that the problem you want to talk about is that the blue line is not stretching the full width?

But what I don't understand is why we cannot reproduce it and why the blue color in that screenshot does not look like the right blue. Do you have some extra CSS that you didn't put in the codepen?

**Comment by rstoenescu** [comment]
When on a mobile then the QSelect (with an input) is designed this way. To appear on top, and keyboard will pop up from bottom, offering the best UX for small screens.
