### ISSUE TITLE
QSelect backspace issue when use-input is set (and multiple isn't)

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4214]
### Issue
When any option from option list is selected, then backspace will not delete last character of selected option. 

### Purpose
Add option to select from predefined option list, create new one and modify it. 

### JsFiddle
https://jsfiddle.net/4Lwp5zte/2/

### Version
Quasar:  v1.0.0-rc.2

**Comment by pdanpdan** [comment]
This is the expected behavior. After you select an option the filter is empty (so you cannot delete it) and you have a selected option.

**Comment by natxocc** [comment]
But, how we can use a filter list autocomplete but add a new value if we want.... and remove it with with backspace if we write in mistake, like a simple combo can do?

**Comment by pdanpdan** [comment]
You have to implement the delete from list - there is no way around it. 
For a text box with fill from list - check the example in docs: https://quasar.dev/vue-components/select#Example--Text-autocomplete
