### ISSUE TITLE
QScrollArea doesn't work on Windows tablets

### ISSUE THREAD

**Issue by pavel-mironchik** [quasarframework/quasar#4215]
### Software version

Operating System - Linux(4.15.0-20-generic) - linux/x64
NodeJs - 11.15.0

Global packages
  NPM - 6.7.0
  yarn - Not installed
  @quasar/cli - 1.0.0-rc.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.2 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.4 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-dotenv - 1.0.0-beta.10 -- Load .env variables into your quasar project

### CodePen
https://codepen.io/professor_pavel/pen/VOdPyB?&editable=true&editors=101

### What did you get as the error?
QScrollArea in the quasar v1.0.0-rc.2 doesn't scroll on Windows devices with a touch screen.

### What were you expecting?
That it will scroll as expected and as it worked in the quasar v1.0.0-beta.18.

### What steps did you take, to get the error?
I upgraded quasar from v1.0.0-beta.18 to v.1.0.0-rc.2

### Additional information
To reproduce this bug you'll need a Windows device with a touch screen. QScrollArea in the latest quasar release works well on an android phone, iPhone X and Windows desktop computer (using a mouse). It doesn't react on user swipes at all on two (different) Windows tablets that I have.
On your Windows tablet open the basic example of using QScrollArea from the documentation or use the provided CodePen (it is just a fork of the aforementioned example). Try to scroll - it will not work. Then on the same device open an example of using a QScrollArea from the quasar v0.17: https://v0-17.quasar-framework.org/quasar-play/android/index.html#/showcase/scrolling/scroll-area. Try to scroll - it will work as expected.

**Comment by pdanpdan** [comment]
Can you please help us with the browser, browser version and UserAgent? I think we are not detecting it as a mobile device.

**Comment by pavel-mironchik** [comment]
On one of my Windows tablet it is:

Chrome 74.0.3729.169 (32 bit)
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

On my Windows desktop computer it is:

Chrome 74.0.3729.169 (64 bit)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

Seems these user agent strings are not too different, and also there is no clue in a user agent string that a device has a touch screen.

**Comment by pavel-mironchik** [comment]
I also checked CSS classes in the CodePen example (using my tablet), the body tag has: `desktop no-touch within-iframe`. It seems your guess was right.

**Comment by pdanpdan** [comment]
Can you please make a short test for me and check the return value for the following on the tablet:

```javascript
!!('ontouchstart' in document.documentElement)
```

```javascript
window.navigator.msMaxTouchPoints > 0
```


```javascript
!!('ontouchstart' in window)
```

```javascript
!!('touchstart' in window)
```

**Comment by pavel-mironchik** [comment]
Here it is:

```
!!('ontouchstart' in document.documentElement)
false
window.navigator.msMaxTouchPoints > 0
false
!!('ontouchstart' in window)
false
!!('touchstart' in window)
false
```

Not good?

**Comment by pdanpdan** [comment]
:) not good
Can you also test this and tell me the detailed output: https://zeno.github.io/mobile-detect-demo/

**Comment by pavel-mironchik** [comment]
Mobiledetect.js page said: "You are on a desktop browser. Mobile-Detect is mainly meant for mobile device detection." Then I clicked the "OK, still show me the results" button:

```
mobile()=
├─ phone()=
└─ tablet()=
mobileGrade()=A
os()=
userAgent()=
is('WebKit')=true
version('Chrome')=74.03729169
version('Safari')=537.36
version('Webkit')=537.36
version('Windows NT')=6.3
```

Other tests:

```
window.navigator.pointerEnabled
undefined
window.navigator.msPointerEnabled
undefined
window.navigator.maxTouchPoints
5
```

I recall I read somewhere that often a windows driver of touch screen just emulates a mouse or a touchpad (which I guess also emulates a mouse).

**Comment by pdanpdan** [comment]
Let's hope `window.navigator.maxTouchPoints` is the winner. It will be available in the next release.

**Comment by rstoenescu** [comment]
v1 rc.3 will contain this.
