### ISSUE TITLE
[v1] QInput API - select method is missing

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4216]
Hello!

From what I remember in v 0.17 you could access input's `select` method to select text inside control. Does not seem to be available in v1. I propose we add it back.

See https://jsfiddle.net/jy60x5r1/.

Native input methods: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#Methods

Thanks!

**Comment by pdanpdan** [comment]
Check docs - https://quasar.dev/vue-components/select#QSelect-API

updateInputValue ([value, noFilter]) => void 0

**Comment by jean-moldovan** [comment]
I'm sorry, I think that exposing `select` method on QInput should be sufficient enough. Please let me know if I misunderstood your answer.

**Comment by rstoenescu** [comment]
Will be available in rc.3
