### ISSUE TITLE
[v1] QUploader adds space when made to take card width

### ISSUE THREAD

**Issue by bunya017** [quasarframework/quasar#4217]
I wanted QUploader to take QCard width in a QDialog, so I put it in a `div` with `row` class
and added `col` class to the QUploader component as in this pen: https://codepen.io/bunya017/pen/yWPJJq and it worked. Upon upgrading to v1-beta.24, the QUploader adds unnecessary 
padding to its right as in this pen: https://codepen.io/bunya017/pen/oRpXYM.

**How do I get rid of the space?**

I think the QUploaderAddTrigger as required in the [docs](https://quasar.dev/vue-components/uploader#Slots) is responsible for the extra space.

### `quasar info` output
Operating System - Windows_NT(6.1.7601) - win32/ia32
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - Not installed
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.24 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.26 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

**Comment by rstoenescu** [comment]
Hi,

First, let me clarify something. You don't need QCard. Use QUploader directly. In your use case, it makes no sense to also wrap QUploader in anything else.
https://codepen.io/rstoenescu/pen/QRxqNx

Secondly, what browser are you using? Or are you seeing your issue (can't reproduce myself) on a mobile device? In this case, specify if it's in Cordova and what platform (Android, iOS) and which version.

Thanks.

**Comment by bunya017** [comment]
Thanks for the reply.

> First, let me clarify something. You don't need QCard. Use QUploader directly. In your use case, it makes no sense to also wrap QUploader in anything else.
> https://codepen.io/rstoenescu/pen/QRxqNx

I'm actually using the the dialog to collect product information, I thought it'll look better if all the input fields take the width of the card. See the gif below:

![productForm](https://user-images.githubusercontent.com/26235763/58425011-a3026580-8090-11e9-959f-ca0aa128b567.gif)


### After the beta.24 upgrade

![v1-beta 24](https://user-images.githubusercontent.com/26235763/58424368-2de26080-808f-11e9-8004-5a884553e943.gif)


### Before the beta.24 upgrade, there no additional space by the right side

![v1-beta 21](https://user-images.githubusercontent.com/26235763/58424191-d0e6aa80-808e-11e9-9b03-025d80c84bcc.gif)

> Secondly, what browser are you using? Or are you seeing your issue (can't reproduce myself) on a mobile device? In this case, specify if it's in Cordova and what platform (Android, iOS) and which version.


I'm using Firefox 67, SPA mode on windows desktop.

**Comment by rstoenescu** [comment]
Thanks for the details and for reporting.
Fix will be available in rc.4
