### ISSUE TITLE
Include list of "embedded" validation rules supported by QInput

### ISSUE THREAD

**Issue by borie88** [quasarframework/quasar#4218]
The docs for QInput mention that there are embedded rules for internal validation, but they are not explicitly listed on that page.

You can find some of them scattered throughout the various form components, such as the ColorPicker, DatePicker, etc., but it would be great to have a complete list of the internal rules supported somewhere

Thanks!

**Comment by rstoenescu** [comment]
Will be available on next docs deployment.

**Comment by hspaay** [comment]
@rstoenescu, thank you for fixing this. Interestingly, in version 2.4.2 of the docs for QInput and QSelect both mention 'embedded validation rules' without explaining what that is. It also isn't explained what the 'val' parameter is. 
Is this a regression?

**Comment by rstoenescu** [comment]
@hspaay Of course it details them. Check the validation > internal validation section.

**Comment by hspaay** [comment]
@rstoenescu ah I see what you are referring to now. Originally I looked at QSelect which has no such section but I understand that duplicating this is not ideal. Maybe a reference to QInput validation rules would be helpful to people that are new to this.

For others that might stumble here, this line in the QInput internal validation section refers to the embedded rules:

>There are helpers for QInput rules prop: full list. 

... where 'full list' is a link to the list of embedded rules.

Thank you kindly for the quick reply.

**Comment by marques620** [comment]
Hey there,

@rstoenescu Is there a way that I can add a custom rule to this list of embedded rules?

Thanks for the help!

**Comment by rstoenescu** [comment]
@marques620 Hi, there isn't, mainly because you can create a file with all your custom rules then import and use them wherever you need them.

**Comment by Sintogu** [comment]
@rstoenescu I checked the validation > internal validation section as you wrote, but didn't find a list of methods using as validate function. Such as "email()" in the example [:rules="[ (val, rules) => rules.email(val) || 'Please enter a valid email address' ]"]

**Comment by MilosPaunovic** [comment]
https://github.com/quasarframework/quasar/blob/21a5717dcb92da0c8b02db66726cd0a6623b65c0/ui/src/utils/patterns.js#L11

**Comment by Sintogu** [comment]
I see, thank you very much!
