### ISSUE TITLE
[v1] QSelect filter function overcomplicated

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4221]
Hello!

Back in v0.17 days you would have a filter function with `(val, done)` on your QAutocomplete. Very intuitive and easy to use: `done(filteredItems)`.

In v1 this seems somewhat overcomplicated. In the examples in the docs https://quasar.dev/vue-components/select#Filtering-and-autocomplete you would override `this.options` to display the list of filtered results, which is a bit different.

In a lot of cases `this.options` will come from the outside as a prop. With the current approach you have to maintain a local copy of that, which makes things a little harder to manage. I think this can be avoided if we use old `done(filteredItems)` signature.

Example: https://jsfiddle.net/jy60x5r1/3/
1) Click inside the input
2) Start typing
3) Only first option should be displayed

Thanks!

**Comment by rstoenescu** [comment]
Hi,

We have two goals with QSelect: make it as fast as possible while allowing 3 times more features. The current architecture allows this, and there is a nice video going around showing v1 is 20x faster than its v0.17 counterpart. Some decisions had to be made and not going to revert them.

I hope you care about performance the same way we do.
