### ISSUE TITLE
[v1] QSelect autocomplete unable to clear

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4222]
Hello!

I like how we can mimic autocomplete using QSelect in v1. However, I think user should be able to clear the value from the input itself (without clearable icon). Currently the value is restored as if it was combobox and not basic autocomplete. I think these are two different use cases autocomplete vs combobox.

Google search bar is a good example of autocomplete.

Example: https://codepen.io/anon/pen/qGKKpZ?&editable=true&editors=101

Steps to reproduce:
1) Select 'Google'
2) Click inside the input, remove everything with a 'backspace'
3) Click outiside
4) 'Google' is restored

Expected: Google should be removed for a basic autocomplete, Google should be restored for a combobox.

**Comment by jean-moldovan** [comment]
Also, one important feature of autocomplete in my opinion is that even if you don't get any matches typing `asdasdasda sadasd`, model is still updated to that value. Again, see Google search bar as an example.

**Comment by rstoenescu** [comment]
Use `hide-selected` prop ;)

**Comment by jean-moldovan** [comment]
@rstoenescu , you can see that `hide-selected` is used in the exmaple https://codepen.io/anon/pen/qGKKpZ?&editable=true&editors=101. Please review steps to reproduce once again.

**Comment by rstoenescu** [comment]
https://codepen.io/rstoenescu/pen/QRxZyr?&editable=true&editors=101

`hide-selected` + `fill-input`.
Take some time to look at the API card and examples. Once QSelect starts to "tick" for you, you'll be amazed by what you can do with it.
