### ISSUE TITLE
quasar info shows @quasar/cli as undefined inside app folder, shows correct cli version outside app folders

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#4224]
### Software version

Quasar: 1.0.0-rc.2
@quasar/app (v1+ only): 1.0.0-rc.4
@quasar/cli: 1.0.0-rc.2
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Yarn: 1.16.0

### What did you get as the error?
Inside a Quasar app folder, `quasar info` shows @quasar/cli as `undefined` under **Global packages** and CLI commands such as `quasar upgrade` are unknown/missing from the command list. 
  
Outside a Quasar app folder, `quasar info` shows the expected @quasar/cli version and commands. 

### What were you expecting?
To see the correct @quasar/cli version and be able to run @quasar/cli commands such as `quasar upgrade`. 

### What steps did you take, to get the error?
On Windows 10, used npm to install @quasar/cli globally.
`quasar create` to create the app folder (selected  yarn).
`quasar info` to see quasar info with missing CLI version.
  
Ran into this because I was trying to do `quasar upgrade` from a v1.0.0-beta25 project as per the documentation and received 
>unknown command "upgrade".

Tried reinstalling yarn, node/npm, deleting yarn.lock, deleting node_modules, etc.

**Comment by webnoob** [comment]
I have this exact issue but assumed it was just my environment.

**Comment by rstoenescu** [comment]
Can you confirm that you've globally uninstalled the old "quasar-cli" package?

**Comment by rstoenescu** [comment]
Also, @GordonBlahut : are you running the command in a genuine terminal or in a code editor terminal?

**Comment by webnoob** [comment]
I've just been through this again and it seems it's working correctly when you use a genuine terminal i.e CMD or GitBash CMD. It's only when I opened Webstorm that it failed. When checking the terminal type in Webstorm (settings | Search "terminal") did it show it was using powershell.

**Comment by webnoob** [comment]
From what I can see, webstorm is prioritizing the locally installed Quasar package over the global one. Running `node C:\Users\ME\AppData\Roaming\nvm\v11.9.0\node_modules\@quasar\cli\bin\quasar upgrade` in webstorm does work correctly because I'm forcing it to look at the global package which then tries to look for the local package.

Now I understand where Webstorm is failing, I'll try to find a way around it.

**Comment by webnoob** [comment]
I've got some more information on this now. For webstorm at least, there is an option in Settings | Terminal called:

![image](https://user-images.githubusercontent.com/10404747/58441352-4d9e7680-80d9-11e9-96fa-99b5531ff59d.png)

This is enabled by default and I believe registers the local quasar package as the global one. Quasar relies on the global one to trigger first and it in turn calls the local app version.

Unticking this option has fixed my issue.

**Comment by GordonBlahut** [comment]
@rstoenescu I am using PowerShell to run commands. If you mean the old pre-v1 CLI, I only ever started with the v1 betas.

**Comment by webnoob** [comment]
@GordonBlahut How have you installed your global deps? Did you use yarn or npm? We *always* recommend **npm** for globals `npm install -g package` and **yarn** for local deps.

Depending on which version of yarn you're using, you could be falling foul of this issue: https://github.com/yarnpkg/yarn/issues/6902

**Comment by rstoenescu** [comment]
@GordonBlahut You're not answering all of our questions. Please read the thread. Are you in the same situation as @webnoob ? Meaning you're using the terminal in a code editor? And which? And make sure it doesn't automatically pick up `node_modules/.bin` before picking up the global installation of `@quasar/cli`.  Please reopen with these answers if they don't apply to you. Thanks.

**Comment by GordonBlahut** [comment]
Sorry it was the middle of the night where I am when some of these questions were asked. I thought I answered everything but I'll confirm below. Let me know if you still need additional information.

> Can you confirm that you've globally uninstalled the old "quasar-cli" package?  

Are you talking about the ~0.17 version of the package? If so, I never used anything before @quasar/cli-v1.0.0-beta.7. I used npm to upgrade from @quasar/cli-v1.0.0-beta.7 to @quasar/cli-v1.0.0-rc.2  

> are you running the command in a genuine terminal or in a code editor terminal? 

I am running the command using PowerShell. I use Visual Studio 2017 and Visual Studio Code for editing, depending on if I am doing server or client stuff. I do launch the PowerShell process from a context menu in VS 2017 though for convenience.

> How have you installed your global deps? Did you use yarn or npm? We always recommend npm for globals npm install -g package and yarn for local deps.  
  
I use npm for globals and yarn for locals.  
  
> Depending on which version of yarn you're using, you could be falling foul of this issue: yarnpkg/yarn#6902  
  
I am using Yarn 1.16.0. I did try creating a new app folder using npm for locals just to see if it was a yarn issue for locals and ran into the same issue. If I am understanding that issue correctly, it appears to be an issue when using yarn to install global packages, which I am not doing and appears to have been resolved in 1.15.2 so I don't think this is it. 
  
> And make sure it doesn't automatically pick up node_modules/.bin before picking up the global installation of @quasar/cli.   
  
Ah, this appears to be exactly what's happening in my case. `.\node_modules\.bin` is injected right at the top of my PATH if I launch PowerShell from VS. If I launch PowerShell directly, `.\node_modules\.bin` is not injected. 
  
Now to figure out why it's doing that and how to change it, but it does not appear to be a Quasar concern, unless you want to detect cases where the local package is invoked without the global one and print warnings or something.

**Comment by webnoob** [comment]
This is what Webstorm was doing as well - I found a setting to control it. Perhaps VS has the same option.

**Comment by mpacary** [comment]
Same issue here, with using the genuine terminal (Windows 10 cmd).

Turned out I had to do some cleaning in my PATH env variable. Maybe some editor (I use VS Code) has injected `.\node_modules\.bin`.

Tip: run command `where quasar` in your project directory to know where quasar binary is run from 👍

**Comment by webnoob** [comment]
@mpacary Thanks for that info
@rstoenescu Do you think it's worth another note on the docs for that part (https://quasar.dev/quasar-cli/cli-documentation/commands-list#upgrade). If the users are using VSCode, don't untick that option in there about the path bu then try to use the normal cmd, they will run into the same issue because it exists the in the %PATH%.
