### ISSUE TITLE
Q1 - QUploader IE 11

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#4228]
Quasar:
quasar - 1.0.0-rc.3 
quasar/app - 1.0.0-rc.4 

### What did you get as the error?
Clicking the plus symbol in IE 11 doesn't do anything. You can drag files onto the QUploader and it will work.

### What were you expecting?
File browser like Chrome.

### What steps did you take, to get the error?
Click the plus symbol

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.4.

**Comment by sn0rcha** [comment]
This problem has re-appeared in the latest version of Quasar in both IE 11 and IE Edge:

quasar - 1.2.5 
@quasar/app - 1.2.2

**Comment by rstoenescu** [comment]
And just got solved. Fix will be available in "quasar" v1.2.6.
