### ISSUE TITLE
Quasar.dev and documentation site is down for > 24hrs

### ISSUE THREAD

**Issue by satyavh** [quasarframework/quasar#4229]
https://v1.quasar-framework.org redirects to https://quasar.dev/ and throws `ERR_CONNECTION_REFUSED`

As such, site can't be reached. This is very annoying, we need docs!
Is there a backup site where the docs can be viewed?

**Comment by StationMaster** [comment]
https://quasar.dev/

**Comment by satyavh** [comment]
Nevermind, I figured it out. Some artefacts left on my system when .dev wasn't owned by Google :-(

**Comment by LeslieLei** [comment]
how to resolve it

**Comment by pdanpdan** [comment]
Check your hosts file.

**Comment by nothingismagick** [comment]
If you were using .dev for your local development environment, you'll need
to remove that. There's a number of ways to do that and number of OS's out
there, so you're probably going to be on your own here.

**Comment by rstoenescu** [comment]
Possible way to fix it: https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain
