### ISSUE TITLE
[v1] QPopupProxy does not work inside QInput

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4230]
Hello!

Back in v0.17 days you could use Popup inside QInput just by throwing it into input's default slot. Was super useful in scenarios when you wanted to display a popup hint after user clicks on a readonly input.

This does not seem to be working that way in v1. Examples in the docs only show how to use popup in combination with QIcon inside QInput, which is a bit different.

I'd love to be able to use QInput as a parent component without specifying selectors or anything like that.

Demo https://jsfiddle.net/yfpz13vs/2/.

Thanks!

**Comment by smolinari** [comment]
@jean-moldovan 

https://codepen.io/smolinari/pen/RmBVVo

Like that?

Scott

**Comment by jean-moldovan** [comment]
@smolinari , can we have it attached to the parent input element?

![Screen Shot 2019-05-28 at 13 00 55](https://user-images.githubusercontent.com/3635352/58469707-b1ac5380-8148-11e9-8cd6-86b27b84005c.png)

**Comment by jean-moldovan** [comment]
I like how intuitive was the old signature:
```
<q-input>
  <q-popup-proxy>foo</q-popup-proxy>
</q-input>
```
Do you think this can be added back?

**Comment by smolinari** [comment]
Is my codepen now what you are looking for?

Scott

**Comment by rstoenescu** [comment]
@jean-moldovan adding `readonly` or `disable` really disables any UI interaction with the QInput's control slot. Otherwise your QPopupProxy would work as you wrote it. But @smolinari 's solution is the way to go in this case.

**Comment by jean-moldovan** [comment]
Posting v0.17 example https://jsfiddle.net/mLh2yv5k/

**Comment by wc-matteo** [comment]
@rstoenescu `QPopupProxy` _does_ work inside a `QInput` as you say, but there are some issues.

For instance, the popup behaves like `QMenu`'s `:fit="true"` was present:

#### QMenu (GOOD)
https://codepen.io/anon/pen/agKJYN

#### QPopupProxy (desktop) (BAD)
https://codepen.io/anon/pen/BgVWZx

Is this a bug?

**Comment by wc-matteo** [comment]
@rstoenescu should I create a new issue with this?

**Comment by pdanpdan** [comment]
@wc-matteo QPopupProxy treats QDate, QTime, QCarousel and QColor as special components and shows them as `cover: true`.
If you don't want this just wrap it in a div - https://codepen.io/anon/pen/XLvgRz

**Comment by wc-matteo** [comment]
awesome! Thank you :) @pdanpdan
