### ISSUE TITLE
[v1] QInput number step validation

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4232]
Hello!

When using number input there is no way to specify step attr. This triggers native form validation. Is this something that need to be configurable or maybe set to step="any"?

Example: https://jsfiddle.net/vypzL35n/

See: https://stackoverflow.com/questions/34057595/allow-2-decimal-places-in-input-type-number

Thanks!
![Screen Shot 2019-05-28 at 13 06 27](https://user-images.githubusercontent.com/3635352/58470453-6a26c700-814a-11e9-818b-eddb09fbc1e6.png)

**Comment by rstoenescu** [comment]
`<q-input type="number" step="any" v-model="amount" />`

Any attributes get assigned to the native inner `<input>` automatically ;)
