### ISSUE TITLE
[v1] QSelect autocomplete display text updated incorrectly

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4235]
Hello!

https://codepen.io/anon/pen/jopZrZ?&editable=true&editors=101

Scenario:
User reads an array of options from the api based on the input. Once new results are applied, display value is restored back.

Steps to reproduce:
1) Click inside select
2) Start removing "Goo"
3) Wait for options to load
4) "Google" text is restored inside the input

Expected: display text inside select should not change ("Goo") unless option is selected.

This is probably due to the fact that options is overridden with the new array of results:
```
          this.options = JSON.parse(JSON.stringify(options)) <- does not work correctly
          //this.options = this.options <- works correctly
```

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.4.
