### ISSUE TITLE
[v1] QSelect autocomplete freeze when applying options

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4237]
Hello!

Wanted to raise an interesting case right here.
https://codepen.io/anon/pen/eajKYj?&editable=true&editors=101 When you apply a bunch of options on update function, CPU goes crazy and the browser basically hangs. However, if you use setTimeout, it works ok.

Start typing inside control:
https://codepen.io/anon/pen/eajKYj?&editable=true&editors=101

Same, but with setTimeout, works ok:
https://codepen.io/anon/pen/oRMMXZ?&editable=true&editors=101

Thanks!

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.4.
