### ISSUE TITLE
QSelect: Blur event is not fired

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4238]
### Issue
When user  manually type a new option (which is not in a options list and the option list will disappear), then the blur event will not be called.

### Steps to reproduce
Please type "gg" in demo and click outside of q-select => the blur event will not be fired.

### JsFiddle
https://jsfiddle.net/n5xr3mw4/8/

### Version
Quasar v1.0.0-rc.3

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.4.
