### ISSUE TITLE
Quickstart app/demo inspired by Ultima/PrimeNG & CovalentUI/Teradata

### ISSUE THREAD

**Issue by cyparu** [quasarframework/quasar#424]
First of all, my congrats 👍 to @rstoenescu for all such great & polished components!

While Quasar-Play app provide a very comprehensive overview for all available components, it will be great to structure a more realistic skeleton app to better demonstrate all the capabilities (ex: admin theme fitting the ElectronJS support as well) . My suggestion in this regard would be to look for inspiration to the following quickstart apps:
- [**Ultima** - PrimeNG theme for Angular 2](http://www.primefaces.org/ultima-ng/#/) => [**blog**](http://blog.primefaces.org/?cat=12), [**twitter**](https://twitter.com/Prime_NG)  
![image](https://cloud.githubusercontent.com/assets/6412318/23451225/ae3627a0-fe67-11e6-9022-dd61498950c2.png)
- [**CovalentUI** - Angular 2 Material Design Components](https://teradata.github.io/covalent-quickstart/) => [**blog**](https://medium.com/covalent-ui/) , [**code**](https://github.com/Teradata/covalent-quickstart), [**twitter**](https://twitter.com/KyleLedbetter)  
![image](https://cloud.githubusercontent.com/assets/6412318/23451559/186a2490-fe69-11e6-8575-7dcae27cfdec.png)

**Comment by rstoenescu** [comment]
http://beta.quasar-framework.org/quasar-play/android/index.html#/showcase
http://beta.quasar-framework.org/quasar-play/apple/index.html#/showcase
