### ISSUE TITLE
QUploader upload success but trigger failed

### ISSUE THREAD

**Issue by muei** [quasarframework/quasar#4241]
Operating System - Linux(4.15.0-51-generic) - linux/x64
NodeJs - 10.15.0

Global packages
  NPM - 6.8.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
```
q-uploader(
          label="Filtered (for < 1M size)"
          flat
          bordered
          accept=".xls, .xlsx"
          style="width: 100%"
          @uploaded="handleUploaded"
          @failed="handleFailed"
          )

....

methods: {
    factoryFn(files) {
      return {
        url: process.env.uploadURI,
      }
    },
    handleUploaded(info) {
      console.debug('uploaded success', info)
    },
    handleFailed(err, files) {
      console.debug('uploaded failed', err, files)
    },
  },
```
The upload request success, and response status is 200, but trigger the `handleFailed` methods, but also this, the `handleFailed` method's parameters not *err, files*, is the successed parameter *info*

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce.

Can you offer more details pls? What platform are you testing on? Cordova, mobile browser, desktop browser, Electron -- and which version of those. What mode are you building? Are you using UMD or standard Quasar CLI? A [codepen](https://codepen.io/rstoenescu/pen/VgQbdx) would be great (fork and save).

Also, I see factoryFn is not used in the template, so maybe missing a detail on the writeup? Assumed you also added `:factory="factoryFn"` but just want to make sure nothing else is missing.

**Comment by muei** [comment]
It's so strange, I test online, it works well. But same code in my local (spa mode), it exist the problem too.
https://codepen.io/rstoenescu/pen/VgQbdx

The full quasar env info:
Operating System - Linux(4.15.0-51-generic) - linux/x64
NodeJs - 10.15.0

Global packages
  NPM - 6.8.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-dotenv - 1.0.0-beta.10 -- Load .env variables into your quasar project

**Comment by rstoenescu** [comment]
Your code pane is exactly mine. Hit fork, update it, then hit save and post it again here.
I cannot reproduce your issue and you still haven't answered my questions above.

**Comment by muei** [comment]
Sorry my mistake, the problem I find is that, I subscribe the uploaded message, then I route to another parameter page, now the *uploaded* triggered, and trigger the wrong method. I will colse this issue, thanks very much. Below is the source code:
### Template
```
<div id="q-app">
  <div class="q-ma-md">
    Fork and make your own!
    Do NOT use self-closing tags here on Codepen.
  </div>
  
  <div class="q-ma-md">
    <q-btn label="Notify" color="primary" @click="notify"></q-btn>
  </div>

  <div class="q-ma-md">
    Running Quasar v{{ version }}
  </div>

  <div class="q-ma-md">
    <q-btn label="Open" color="primary" @click="visible = true" />
  </div>
  <q-dialog v-model="visible">
    <q-card>
      <q-uploader
                  label="Custom header"
                  :factory="factoryFn"
                  :form-fields="formFields"
                  @uploaded="handleUploaded"
                  @failed="handleFailed"
                  >
        <template v-slot:header="scope">
          <div class="row no-wrap items-center q-pa-sm q-gutter-xs">
            <q-btn v-if="scope.queuedFiles.length > 0" icon="clear_all" @click="scope.removeQueuedFiles" round dense flat >
              <q-tooltip>Clear All</q-tooltip>
            </q-btn>
            <q-btn v-if="scope.uploadedFiles.length > 0" icon="done_all" @click="scope.removeUploadedFiles" round dense flat >
              <q-tooltip>Remove Uploaded Files</q-tooltip>
            </q-btn>
            <q-spinner v-if="scope.isUploading" class="q-uploader__spinner">
            </q-spinner>
            <div class="col">
              <div class="q-uploader__title">Upload your files</div>
              <div class="q-uploader__subtitle">{{ scope.uploadSizeLabel }} / {{ scope.uploadProgressLabel }}</div>
            </div>
            <q-btn v-if="scope.canAddFiles" type="a" icon="add_box" round dense flat>
              <q-uploader-add-trigger />
              <q-tooltip>Pick Files</q-tooltip>
            </q-btn>
            <q-btn v-if="scope.canUpload" icon="cloud_upload" @click="scope.upload" round dense flat >
              <q-tooltip>Upload Files</q-tooltip>
            </q-btn>

            <q-btn v-if="scope.isUploading" icon="clear" @click="scope.abort" round dense flat >
              <q-tooltip>Abort Upload</q-tooltip>
            </q-btn>
          </div>
        </template>
      </q-uploader>
    </q-card>
  </q-dialog>
</div>
```
### Script
```js
new Vue({
  el: '#q-app',
  data: function () {
    return {
      version: Quasar.version,
      visible: false
    }
  },
  computed: {
    formFields() {
      const { customerID, brandID, yearID, seasonID } = this
      return [
        { name: 'customerID', value: 'customerID' },
        { name: 'brandID', value: 'brandID' },
        { name: 'yearID', value: 'yearID' },
        { name: 'seasonID', value: 'seasonID' },
      ]
    },
  },
  methods: {
    notify: function () {
      this.$q.notify('Running on Quasar v' + this.$q.version)
    },
    factoryFn(files) {
      return {
        url: 'http://localhost:5000/upload',
      }
    },
    handleUploaded(info) {
      console.debug('uploaded success', info)
    },
    handleFailed(err, files) {
      console.debug('uploaded failed', err, files)
    },
  }
})
```
