### ISSUE TITLE
[V1] Scalable UI

### ISSUE THREAD

**Issue by joshuadavidson** [quasarframework/quasar#4246]
#### Background
Our team is using Quasar (v1.0.0-beta.1) for an engineering application with the need for a high UI density (lots of data needs to be viewed simultaneously). We are loving the flexibility of the components but have found some issues with scaling the overall UI to accommodate our app.

#### Problem
I have overridden all of the exposed Quasar stylus variables to use rem (rather than px) so that we could scale our app using the HTML font-size but it appears as though there is a large quantity of components that have hard coded px font-sizes, padding, margin, etc. For example the table component does not scale it's td font size--it's always 13px. With these hard coded values it is impossible to correctly scale Quasar without 1) forking it and changing those hard coded values or 2) overriding all of the Quasar CSS classes.

#### Potential Solution
It would be great if Quasar could scale its UI similar to how Bootstrap 4/Bootstrap-Vue does with variables and rem units throughout. 

#### Benefits
- This would allow for consistent look to all components no matter the UI scale
- This would allow users to customize all of the currently hard coded px values throughout the component styles to make the style truly their own.
- Users could dynamically scale their app by simply changing the root element font size.

#### Potential Implementation Road-map
This is quite a request but I feel as though it could be implemented in stages:
1. Convert all Quasar stylus variables to default to rem rather than px (this allows for a base level of UI scaling using root element font-size as I have seen in my testing).
2. Convert all hard coded px values to rem units (within reason) in component style sheets (this would achieve consistent UI scaling by allowing users to set root font-size).
3. Expose these component based hard coded values as quasar variables to allow users to truly customize the UI.

This feature request is similar in nature to #3443 but applies to all CSS properties affecting UI scale (margin, padding, line height etc).

**Comment by nothingismagick** [comment]
I totally agree with the idea in principle, and you're right - that's a massive thing to undertake. There's more than a few use-cases here that make this a very important thing to put on our roadmap.

We'll need to talk about this in the team and figure out a good strategy here. I think once there's an approach we can agree to this could probably be done step by step.

Am I to understand that you would be willing to contribute in this effort?

**Comment by joshuadavidson** [comment]
Great! Yes, either myself or the engineering team here would be willing to contribute. Do you have an estimated timeline so that we can plan the work from our end? Just keep us in the loop where possible.

**Comment by nothingismagick** [comment]
Can you join us at the discord server - find me: @nothingismagick

**Comment by joshuadavidson** [comment]
Closing. Issue handled on #4274 RFC.
