### ISSUE TITLE
Uploader missing input field

### ISSUE THREAD

**Issue by stegithub** [quasarframework/quasar#4247]
macOS 10.14.4
npm v6.4.1
node v10.0.0

"@quasar/extras": "^1.0.0"
"quasar": "^1.0.0-rc.4"
"vue": "^2.5.17"

devDependencies:
"vue-cli-plugin-quasar": "^1.0.0-rc.1"
"@vue/cli-service": "^3.0.4"

Hi,
i've this problem using component QUploader. 
I correctly import and use it simply with:
q-uploader/   but nothing happens when clicking on '+' button.
In the following screen you can see that input hidden field is not present. (screen with input field is from quasar doc).
Suggestions?
Thanks

<img width="322" alt="Schermata 2019-05-29 alle 21 38 08" src="https://user-images.githubusercontent.com/19598492/58585863-0e4b6380-825a-11e9-89a3-310b6023205d.png">

<img width="423" alt="Schermata 2019-05-29 alle 21 36 44" src="https://user-images.githubusercontent.com/19598492/58585774-dcd29800-8259-11e9-8c4d-562806199cbe.png">

<img width="393" alt="Schermata 2019-05-29 alle 21 37 13" src="https://user-images.githubusercontent.com/19598492/58585798-ee1ba480-8259-11e9-9c5b-fe837fb41433.png">

**Comment by rstoenescu** [comment]
Hi,

What is your vue template?

**Comment by stegithub** [comment]
> Hi,
> 
> What is your vue template?

<template>
  <div class="upload">
    <q-uploader label="Custom header"/>
  </div>
</template>

I'm also using vue-material v1.0.0-beta-10.2, but i will remove it.

**Comment by stegithub** [comment]
<template>
  <div class="upload">
    <q-uploader label="Custom header"/>
  </div>
</template>

I'm also using vue-material v1.0.0-beta-10.2, but i will remove it.

**Comment by stegithub** [comment]
> Hi,
> 
> What is your vue template?

template
   div class="upload">
         q-uploader label="Custom header"

I'm also using vue-material v1.0.0-beta-10.2, but i will remove it.

**Comment by rstoenescu** [comment]
@stegithub Hi, does this still happen with latest Quasar (1.0.5)?

**Comment by stegithub** [comment]
> @stegithub Hi, does this still happen with latest Quasar (1.0.5)?

Yes it happens, and also into a <q-layout> the render is always empty:
        'div class="q-layout q-layout--standard"'  !----!---- /div

my code is the same of quasar sample layout

**Comment by rstoenescu** [comment]
Hi,

I double-checked the code for QUploader. It is impossible for it not to also contain the inner input field. Unless you are using a custom header, in which case I think that you forgot to also add QUploaderTrigger component, like in the docs example: https://quasar.dev/vue-components/uploader#Example--Custom-header

```
<q-btn v-if="scope.canAddFiles" type="a" icon="add_box" round dense flat>
            <q-uploader-add-trigger />
            <q-tooltip>Pick Files</q-tooltip>
          </q-btn>
```
