### ISSUE TITLE
q-transition has no support for transition groups

### ISSUE THREAD

**Issue by tiberiuichim** [quasarframework/quasar#425]
I'm getting this error in the console when wrapping a ``<li>`` in a q-transition

[Vue warn]: <transition> can only be used on a single element. Use ``<transition-group>`` for lists. 
(found in component ``<q-layout>``)

**Comment by tiberiuichim** [comment]
As far as I understand, there should be a transition-group component available in q-layout. It would be nice to have it documented. I'll try to see if I can figure out how to use it.

**Comment by rstoenescu** [comment]
Yes, q-transition is supported only for one element (uses Vue `transition` component under the covers). Either wrap your elements with a new dom element or use Vue's `transition-group` by writing your own transition.
