### ISSUE TITLE
[v1][Bug] QSelect shows value instead of label

### ISSUE THREAD

**Issue by sujatinov** [quasarframework/quasar#4250]
QSelect shows value instead of label in specific setup. Please refer to codepen link.

### Software version

Quasar: v1.0.0-rc.4
@quasar/app (v1+ only): v1.0.0-rc.5
OS: MacOs, Windows
Node: v11.4.0
NPM: 6.9.0
Browsers: Chrome, Safari

### JsFiddle
https://codepen.io/anon/pen/arRjXN?editors=1010

### What did you get as the error?
IDs (values) are shown in QSelect when using filtering

### What were you expecting?
Labels still should be shown when using filtering

### What steps did you take, to get the error?
1. Select few options QSelect
2. Start typing in QSelect to filter options list. Enter a filter that filters out already selected options.

BUG: Previously selected options start displaying as values (IDs), instead of labels.

**Comment by pdanpdan** [comment]
When you have this case the best approach is to use a computed property, like here:
https://codepen.io/anon/pen/WBaLQW?editors=1010

**Comment by sujatinov** [comment]
Thanks for the solution!

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.5

**Comment by ddiazepam** [comment]
> Fix will be available in "quasar" v1.5.5

Hello, is this already fixed? I have same issue on newest version of quasar
