### ISSUE TITLE
[v1] slots do not check for null

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4251]
Hello!

I've seen this with some of the v1 components. Wanted to get your opinion on this. Usually slot visibility depends on some prop. If prop is `undefined`, slot is not rendered. How about we do not render slot for `null` and '' (empty string) as well?

Here is a quick example:   https://jsfiddle.net/6xqatwe7/3/

There are more examples like this (Input, Select, etc)

Thanks!

**Comment by pdanpdan** [comment]
Null and '' are values.

**Comment by jean-moldovan** [comment]
Okay, agreed. Thanks four your input.
