### ISSUE TITLE
[V1] - Vertical Tab not highlighted style when tab is active in IE11

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#4254]
```
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.3 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.4 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  quasar-app-extension-ide-helper - 0.0.5 -- Quasar framework extension which enables IDE features like autocomplete by generating helper files for IDE to index.
  @quasar/quasar-app-extension-icon-factory - 1.0.0-rc.2 -- A Quasar CLI Extension
```

### JsFiddle
See docs [https://quasar.dev/vue-components/tabs#Example--Vertical-(example-with-QSplitter)](https://quasar.dev/vue-components/tabs#Example--Vertical-(example-with-QSplitter))

### What did you get as the error?
IE doesn't show full height line when the tab is active:
![image](https://user-images.githubusercontent.com/37825539/58637170-3ab2be80-82f2-11e9-94c7-ba2c0b6e1a95.png)

### What were you expecting?
same result as in Chrome:
![image](https://user-images.githubusercontent.com/37825539/58637192-49997100-82f2-11e9-8135-0c2c17b7eb79.png)

### What steps did you take, to get the error?
Open a link in IE11.

-------
Sorry guys, I know IE11 is obsolete but unfortunately not in our company. Anyway, You did a really great job with IE11 support.

**Comment by pdanpdan** [comment]
It would be a great help for us if you could test as much as you can on IE11 and open issues here.
We'll try to at least make it work (if we can't make it look perfect).
As far as I remember only QLayout in container mode is not going to work, so skip it :).

Thank you.

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
