### ISSUE TITLE
[v1] placeholder for QSelect

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4255]
Hello!

In v0.17 QSelect supported placeholder. I understand that native select does not have placeholder attr, but it was kind of useful to have it in Quasar anyway. Is there any chance we can have it back?

In my scenario I'm creating a wrapper component, which would have a label outside of select control. For the select itself, I'd love to have a placeholder!

v0.17 Example: https://codepen.io/anon/pen/joeowm

Thanks!

**Comment by pdanpdan** [comment]
You can have placeholder if the QSelect has `use-input`

**Comment by jean-moldovan** [comment]
How about regular select? Would it make sense semantically to have it supported?

**Comment by pdanpdan** [comment]
I think you can use the slots to customize it. I have to check.
