### ISSUE TITLE
date.formatDate gives wrong value

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/quasar#4256]
I using the date utility but not getting the desired results

`date.formatDate(new Date("2019-05-31T04:56:00.000Z"), 'yyyy-MM-ddThh:mm')`

outputs:

`"yyyy-05-ThT11:56"`

**Comment by pdanpdan** [comment]
Check the case of letters. YYYY-MM-DD

**Comment by CheyenneForbes** [comment]
Thank you.. it is now `"2019-05-30T11:56"` how do I get the hour to be correct?

**Comment by pdanpdan** [comment]
HH
https://quasar.dev/quasar-utils/date-utils#Format-for-display

**Comment by pdanpdan** [comment]
`formatDate` uses local/client timezone.

`new Date("2019-05-31T04:56:00.000Z")` reads the date with the correct timezone (UTC), so you'll have a conversion to the current/local time.

If you only need to display the text you can do it like this:

```javascript
date.format(new Date("2019-05-31T04:56:00.000Z".split('-').join('/').slice(0, 23)), 'YYYY-MM-DDTHH:mm')
```

**Comment by tinohager** [comment]
I would recommend -1 instead of 23 :)

> 2019-05-31T04:56:00.000Z
> 2019-05-31T04:56:00.000000Z

```js
date.format(new Date("2019-05-31T04:56:00.000Z".slice(0, -1)), 'YYYY-MM-DDTHH:mm')
```
