### ISSUE TITLE
Error when running development server for electron wrapper: port 8080 already in use

### ISSUE THREAD

**Issue by Chmood** [quasarframework/quasar#426]
Hi,

I must be missing something about running the development server for the Electron wrapper on a Quasar fresh install (`nodejs: v7.3.0 / quasar: v0.5.1`)

[The documentation](http://quasar-framework.org/guide/electron-wrapper.html#Development-with-Electron) says to execute `quasar dev` both at the root of the projet, and then in the `electron` folder at the same time (I may misunderstand this point though).
But once the first root server is launched, the second command fails to run and I get this (kind of logical) error:

`⚠ The port 8080 is already in use. Halting Quasar dev server startup. ℹ To fix: Stop the process currently using port 8080 or set your config to a different port.`

If I execute `quasar dev` only in the electron folder, the app opens up, but with a white screen of death.

As I couldn't find any place for tweaking port configuration in the electron folder, I assume that I'm doing something wrong or silly. By the way, the wrapper installation went well and even building the app works fine.

So what's the proper way to start the development server with electron wrapper ?

Any help appreciated, I already love this framework !

**Comment by rstoenescu** [comment]
Ah, you are perfectly right. This was on oversight due to a recent change in CLI. Will fix it asap. Thanks for reporting!

**Comment by Chmood** [comment]
Great to know. Keep us the good work!

**Comment by rstoenescu** [comment]
Update to Quasar CLI v0.5.2 which fixes this. Thanks!
