### ISSUE TITLE
[v1] Submit button inside dialog does not click in Safari

### ISSUE THREAD

**Issue by andypotion** [quasarframework/quasar#4262]
When a `q-form` is inside a `q-dialog`, the submit `q-btn` is not clickable in Mac Safari (12.1.1 on macOS 10.14.5). It works fine when the form is not inside a dialog, but the click does not work inside a dialog.

### JsFiddle
https://jsfiddle.net/andypotion/g0x6df2n/

### Software version
Quasar v1.0.0-rc.4

Operating System - Darwin(18.6.0) - darwin/x64
NodeJs - 12.3.1

Global packages
  NPM - 6.9.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-rc.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

**Comment by pdanpdan** [comment]
Please perform 2 tests for me:

1. Add a `<q-btn type="reset">Reset</q-btn>` inside the form and a `@reset="..."` that does something on `<q-form` and tell me if the rest button works.

2. Fill all the fields in the form with correct values and try to click on submit button and tell me if it works.

Thank you

**Comment by andypotion** [comment]
1. Reset works
2. It fails even after all the form fields contain valid data

I've modified the JsFiddle to add the reset button:

https://jsfiddle.net/andypotion/g0x6df2n/6/

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.5

**Comment by andypotion** [comment]
Thank you for the fix and the wonderful framework.
