### ISSUE TITLE
[v0.17][v1] Safari scrolls back to the QInput when focused

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4264]
Hello!

This one is Safari specific. Tested on Quasar v0.17. Safari version 12.1.

I'm not 100% sure that something is wrong with the QInput. However, was unable to reproduce it for a native input. When you have a bunch of inputs on a page, and one of them is focused, if you scroll down, Safari scrolls back up to that input. The harder you try, the faster Safari goes. A game that you can never win.

https://jsfiddle.net/qnase9dg/1/

Steps to reproduce:
1) Click inside second input
2) Scroll down and wait
3) Safari takes you back to that input
4) Uncomment native input, try again. Works ok.

![safari-q-input](https://user-images.githubusercontent.com/3635352/58693577-c0d61000-8399-11e9-9336-c7bfa1a66218.gif)

Thanks!

**Comment by jean-moldovan** [comment]
Happening on v1 as well https://jsfiddle.net/b3yt60kw/2/.

**Comment by rstoenescu** [comment]
Hi,

Should no longer happen in Quasar v1.1.0. Please reopen if I missed something.

**Comment by jean-moldovan** [comment]
@rstoenescu , I'm still able to reproduce on v1.1.0: https://jsfiddle.net/b3yt60kw/2/
![test](https://user-images.githubusercontent.com/3635352/64940984-157c9880-d86e-11e9-8ffb-4e23075bd575.gif)

**Comment by jean-moldovan** [comment]
![Dec-02-2019 15-28-09](https://user-images.githubusercontent.com/3635352/69959522-679d9380-1518-11ea-8402-42056ced1a18.gif)
Still seeing this on v1.5.2

**Comment by pdanpdan** [comment]
Yes, it's still open, sorry.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.10. Unfortunately, it can only be fixed for iOS 13+

**Comment by jean-moldovan** [comment]
This is still an issue on desktop Safari 13.0.4 and Quasar v1.5.11

![q-safari](https://user-images.githubusercontent.com/3635352/71347065-82dd4b00-257a-11ea-9425-7a9771677226.gif)
