### ISSUE TITLE
Playground of the v1.0 ?

### ISSUE THREAD

**Issue by george-kar** [quasarframework/quasar#4265]
Where is the playground (full features) of the latest version 1.0 ? There is no such link on the site.

**Comment by rstoenescu** [comment]
The playground is the docs website itself, since you now have Example cards with both code and running example. Should you wish, you can hit the Codepen button and play with the respective examples directly on Codepen.

**Comment by george-kar** [comment]
Pity, such bad decision. It was much better when you have all together as playground rather than navigating the documents.
