### ISSUE TITLE
Can you access process.env/build.env in store files?

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#4266]
### Software version

Quasar:
@quasar/app (v1+ only): true
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

I can't seem to access process.env from store files, mutations.js, actions.js etc.. 

It seems that quasar.conf.js build/env might be getting applied after store files are required? 

### What were you expecting?

process.env access inside src/store files

### What steps did you take, to get the error?

I did `build: { env: { woo: JSON.stringify('ayo') } }`

**Comment by nothingismagick** [comment]
Are you using the @quasar/qenv or @quasar/dotenv app-extensions?

https://quasar.dev/app-extensions/discover#Project-Rigging

**Comment by lopugit** [comment]
@nothingismagick nup, I like doing `env=prod quasar dev` and etc.. it shouldn't matter should it? or do the extensions inject into more than what quasar.conf.js can?

**Comment by lopugit** [comment]
huh, I can't breakpoint anything in store/index.js through chrome debugger ? interesting

**Comment by nothingismagick** [comment]
@quasar/qenv is actually a little more flexible than dotenv in my opinion. Regarding your breakpoint concern, please either open another issue or visit us on the discord server.

**Comment by lopugit** [comment]
@nothingismagick I need to be able to pass env variables as CLI arguments, and QENV only let's you set an environment which loads a file based on that environment.

Have you never had to access environment variables in the store index.js file?

**Comment by rstoenescu** [comment]
@lopugit Hi, What doesn't seem to tick for you with the description here? https://quasar.dev/quasar-cli/quasar-conf-js#Example-setting-env-for-dev%2Fbuild

**Comment by lopugit** [comment]
@rstoenescu nothing that's how I do it! But the variables aren't available in any src/store files :O

**Comment by rstoenescu** [comment]
I just did a test and it works. It would have been a big surprise if it didn't :/
Are you importing the vuex modules into src/store/index.js?

**Comment by lopugit** [comment]
@rstoenescu hmm yeah I am but process also isn't available in src/index.js so, I'll make a test repo real quick too

**Comment by lopugit** [comment]
@rstoenescu 
can you try this out? 

https://github.com/lopugit/quasarEnvTest

**Comment by smolinari** [comment]
Works fine. https://codesandbox.io/s/v1templateapp-xku6p

![image](https://user-images.githubusercontent.com/3314957/58788360-0ab63480-85ec-11e9-88ca-ee1ddd821150.png)

Scott

**Comment by rstoenescu** [comment]
@lopugit You need to explicitly reference what you are using from `process.env` so webpack can replace that reference with the actual content. Otherwise, it'll be just some Object in memory while webpack pre-parses the js files.

**Comment by lopugit** [comment]
Ohhh I see, that makes sense because I use a boot plugin to set window.env
to process.env, but plugins are loaded after the store is, and I was only
console logging process not process.env

I get it now! Woo
