### ISSUE TITLE
[v1] QInfiniteScroll does not stop after deactivation

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4268]
Hello!

Here is the scenario:
1) You have two pages, List with QInfScroll and another
2) When you navigate away from the List, you want to cache it via `keep-alive`
3) While inf scroll is deactivated, it still triggers load events, even though you are on a completely different page

Example: https://codepen.io/anon/pen/Pvxrjp
1) Open up console. It displays 'load' logs as expected
2) Go away to another route by pressing `Go Away but keep list cached`
3) Scroll down and see that `load` is still triggered.

Question: Do you think this is something that needs to be taken care of manually in the app land? Or maybe Quasar can send the inf scroll to "sleep" when component is deactivated?

Thanks!

**Comment by pdanpdan** [comment]
You have a lot of problems in your codepen.
I made a working fork: https://codepen.io/anon/pen/zQbEXz?editors=1010
And yes, it's your job to disable the QInfiniteScroll when you deactivate the component and to enable it back when you activate.

**Comment by jean-moldovan** [comment]
Okay, thanks for clarification!
