### ISSUE TITLE
npmjs.com not finding readme

### ISSUE THREAD

**Issue by ajmas** [quasarframework/quasar#4269]
npmjs.com is not finding the readme for the project. it displays the message:

> "Unable to find a readme for @quasar/cli@1.0.0-rc.2"

see attached screenshot.

![Screenshot 2019-05-31 at 12 10 00](https://user-images.githubusercontent.com/682269/58719210-1364fb80-839d-11e9-9a14-e013a11c2d29.png)

**Comment by nothingismagick** [comment]
That's a really good point. We're using a monorepo type of structure, but you're right we should at least have a placeholder.

**Comment by rstoenescu** [comment]
Thanks for reporting! Pushed READMEs and will be available on npm when we release a new version of each package.
