### ISSUE TITLE
[Request] More css grid width options

### ISSUE THREAD

**Issue by stephentuso** [quasarframework/quasar#427]
It would be nice to have the option of more than 5 columns - Bootstrap has up to 12. I can always manually add it in my styles, but I think it would be convenient to have a few more built in. Even just one more would be nice, but 8 seems like a good number if that wouldn't make the CSS bloated.

**Comment by rstoenescu** [comment]
I agree. Will do.

**Comment by stephentuso** [comment]
Awesome, thanks

**Comment by zuck** [comment]
Most CSS frameworks use 12, I'd go for that...

**Comment by stephentuso** [comment]
Column number is now configurable - see comments on #497
