### ISSUE TITLE
Mask DD/MM/YYYY does not work q-date

### ISSUE THREAD

**Issue by mMarcos208** [quasarframework/quasar#4270]
### Software version

Quasar: v1.0.0-rc.2
@quasar/app (v1+ only):
OS: MAC OS
Node: v12.1.0
NPM: 6.9.0
Browsers: chrome

### Code
`
<q-date mask="DD/MM/YYYY"...`

### What did you get as the error?

![image](https://user-images.githubusercontent.com/14351491/58723913-a0b24b00-83b1-11e9-886f-563c520a447c.png)

### What were you expecting?

`31/05/2019`

**Comment by rstoenescu** [comment]
Hi. Codepen pls!

**Comment by mMarcos208** [comment]
https://codepen.io/mMarcos208/pen/GaPggO

**Comment by rstoenescu** [comment]
You're confusing the [QInput mask](https://quasar.dev/vue-components/input#Mask) with the [QDate mask](https://quasar.dev/vue-components/date#Model-mask). They're not the same. And if you use one of QInput's hardcoded masks ("date"), then that is "####/##/##" instead of your "##/##/####" (to match DD/MM/YYYY).

https://codepen.io/rstoenescu/pen/YbdPyQ

**Comment by mMarcos208** [comment]
Okay, Tank's.

Sorry for my lack of attention.

**Comment by rstoenescu** [comment]
No problem. We only care that the developers get Quasar right and build awesome websites/apps with it :)

**Comment by swapcom** [comment]
[rstoenescu](https://github.com/rstoenescu) I am sorry but I did not understood you answer, in order to make the date being displayed as DD/MM/YYYY i need to put a mask only in qdate and not in the qinput ? which mask do I need to write there ?

**Comment by ccalvarez** [comment]
> Okay, Thank's.
> 
> Sorry for my lack of attention.

Hi @mMarcos208, how did you manage to validate that the QInput is entered in DD/MM/YYYY format?

Thanks.

**Comment by mMarcos208** [comment]
Hi @ccalvarez.

I'm not using quasar any more. I don't remember.
