### ISSUE TITLE
[v1] $store is undefined in QPopupProxy

### ISSUE THREAD

**Issue by morlz** [quasarframework/quasar#4272]
### Software version

Quasar:
Quasar v1.0.0-rc.4

### JsFiddle
https://jsfiddle.net/d1jk94rm/9/

### What did you get as the error?
```
vm.$store === undefined
vm.$router === undefined
```
inside QPopupProxy when create Dialog

### What were you expecting?
```
vm.$store is an instance of Vuex.Store
vm.$router is an instance of VueRouter
```

### What steps did you take, to get the error?
1. Create a Dialog when the page is loaded
2. Check $store inside QPopupProxy

**Comment by morlz** [comment]
#3881 with jsfiddle

**Comment by smolinari** [comment]
@morlz 

Please check the docs: https://quasar.dev/quasar-plugins/dialog#Dialog-API

Read about the create method and using the `component` and `root` properties. It even mentions needing to access Vuex there. 😄 

https://jsfiddle.net/smolinari/ncrku29g/

We'd also recommend to developers, like yourself, to ask for confirmation on validity of an issue on [discord channel](https://discord.gg/5TDhbDg)  or the [forum](http://forum.quasar-framework.org/) first, so as not to waste developer time here answering what should be that question.

Thanks for your understanding. 

Scott
