### ISSUE TITLE
[v1] QExpansionItem style bug with rounded borders

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#4273]
Display bug for this style of QExpansionItem with rounded borders.

Watch corners.

`style="border-radius: 20px; margin-top: 30px; border: 1px solid silver" header-style="background-color: #e4e4e4"`

![image](https://user-images.githubusercontent.com/10674646/58750933-d5e99680-84a0-11e9-8e10-f7b99bd60c6b.png)
![image](https://user-images.githubusercontent.com/10674646/58750934-dc780e00-84a0-11e9-8f5a-e317b779f78e.png)

Before some time all works as expected

**Comment by rstoenescu** [comment]
Add `overflow-hidden` Quasar CSS helper class.
There's even an example in docs with rounded borders: https://quasar.dev/vue-components/expansion-item#Example--Handling-events

**Comment by Dmitrij-Polyanin** [comment]
Thanks!
