### ISSUE TITLE
[v1] QSelect's updateMenuPosition method not found

### ISSUE THREAD

**Issue by lucasfernog** [quasarframework/quasar#4278]
### Software version
v1.0.0-rc-4

The QSelect.json API file has a definition for a "updateMenuPosition" method, but when i tried to call it, i got undefined. https://github.com/quasarframework/quasar/blob/dev/ui/src/components/select/QSelect.json#L525

**Comment by rstoenescu** [comment]
Thanks for pointing this out. Fix will get into rc.5.
