### ISSUE TITLE
q-table doesn't updates when data is updated

### ISSUE THREAD

**Issue by aislanmaia** [quasarframework/quasar#4283]
Opening another issue here since I cant signup in the forum because it thinks my email is supecious... so I asking for help for a problem I think the table has in a somehow obscure manner. 

`quasar` version is 1.0.0-rc.4
`quasar/app` is 1.0.0-rc.6

I have a `<q-table>` with the following structure:

```
      <q-table
        ref="table"
        :data="customers"
        :columns="columns"
        row-key="id"
        rowsPerPageLabel="Registros por página"
        noDataLabel="Sem dados para exibir"
        :pagination.sync="pagination"
        selection="multiple"
        :selected-rows-label="getSelectedString"
        :selected.sync="selected"
        @request="request"
      >
```

I have implemented a delete feature and my parent data is updated correctly when the server response is returned, but somehow the `computedRows` from the `<q-table>` is not updated correctly.

I have take a look in the properties and values from `<q-table>` in the chrome inspector to see what is happening into the table. The `<q-table>` has a computed key with `computedRows` and object `computedData.rows` that doesn't get the data updated when the `<q-table>` 's data updates. 
One example: I have `customers` in the page 1 from the table. I delete one, my parent's data decrease to 9 items. The same happens to `<q-table>` data, but the computed row values keeps with 10 items stalled there. In the docs, doesn't exist um API to change this values, and I'm lost trying to get this table to work properly. Really annoying.

Any help will much appreciated. Sorry if this is the only place I'm finding to get in contact. :fearful:

**Comment by jean-moldovan** [comment]
@aislanmaia , would you be able to provide a jsfiddle with an example please?

**Comment by aislanmaia** [comment]
Forget about it. What happened was that Vue is somehow obscure in how to treat the reactivity in variables on the vuex store. Because I didn't spread an array, the Vue doesn't triggered the data to the components in the hierarchy. 

Example:

Code failing to trigger reactivity:
```
Vue.set(state, "customers", arrayOfCustomers) 
```

Code triggering reactivity correctly:
```
Vue.set(state, "customers", ...arrayOfCustomers)
```
Ugly way of Vue to treat its reactive mechanism that take me out hours of my time.
