### ISSUE TITLE
Can you add delay for dialog show when overlay is showing

### ISSUE THREAD

**Issue by aokihu** [quasarframework/quasar#4284]
### What were you expecting?

Can you add some delay at render dialog when overlay is showing

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
