### ISSUE TITLE
quasar build is not a command

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar#4285]
`
quasar -v
1.0.0-rc.2
lopu@lopu:/things/prestatics/growlights.com.au$ quasar build

 Error Unknown command "build"

  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|

  Running @quasar/cli v1.0.0-rc.2

  Example usage
    $ quasar <command> <options>

  Help for a command
    $ quasar <command> --help
    $ quasar <command> -h

  Options
    --version, -v Print Quasar CLI version

  Commands
    create        Create a project folder
    info          Display info about your machine
                    (and your App if in a project folder)
    upgrade       Check (and optionally) upgrade Quasar packages
                    from a Quasar project folder
    serve         Create an ad-hoc server on App's distributables
    help          Displays this message

  --------------
  => IMPORTANT !
  => Trigger this inside of a Quasar project (and npm/yarn install) for more commands.
  --------------

lopu@lopu:/things/prestatics/growlights.com.au$
`

Hmmm ?

**Comment by dylanglockler** [comment]
npm install 

then quasar build
