### ISSUE TITLE
[V1 - css bug] maximized modal on cordova 

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4286]
On cordova, if a modal is `maximized` we're still seeing a gap underneath the iOS status bar because `env(safe-area-inset-top)` is applied on `.q-dialog__inner` and whatever the user passes as slot content will receive the actual box-shadow of the dialog.

See screenshot:
===================================
![IMG_0732421B5B14-1](https://user-images.githubusercontent.com/3253920/58778610-377b4380-860e-11e9-8f60-9e4d1dd01164.jpeg)
===================================
and the problematic css:

<img width="766" alt="Screenshot 2019-06-03 14 44 37" src="https://user-images.githubusercontent.com/3253920/58778591-24687380-860e-11e9-93cc-2e323fe08062.png">

even if we apply a white BG via `content-style` we'll still see the box-shadow of the dialog. just underneath the status bar.

**Comment by rstoenescu** [comment]
This is by design. Otherwise the top bar can overlap content.

**Comment by mesqueeb** [comment]
Ok! I'll work around it manually then. Thanks for the heads up!
