### ISSUE TITLE
How to add assets images for Build Electron? 

### ISSUE THREAD

**Issue by aijun198600** [quasarframework/quasar#4287]
My quasar projects add some images in render assets folder, but after build, the images lost. How to add assets images to copy in electron?
![image](https://user-images.githubusercontent.com/4506518/58790277-a2367a00-8622-11e9-8488-7b84d11241e8.png)

**Comment by aijun198600** [comment]
for Vue.js, It should put the images in ```statics``` folder, not ```assets ``` folder.

**Comment by rstoenescu** [comment]
https://quasar.dev/quasar-cli/cli-documentation/handling-assets
...and also: https://quasar.dev/quasar-cli/developing-electron-apps/electron-static-assets
