### ISSUE TITLE
[v1] QSelect not able to tell if disabled

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4289]
Hello!

I'm not sure what material spec says on that, but currently disabled select has the same style/look as enabled.

See https://codepen.io/anon/pen/MdLLaY?&editable=true&editors=101

Should be more faded perhaps?

Thanks!

**Comment by rstoenescu** [comment]
Use "readonly" too?

**Comment by jean-moldovan** [comment]
@rstoenescu , I'm sorry, I'd say that readonly is a separate thing on it's own and has a different meaning semantically. Maybe we can avoid mixing both?

Please see the native select disable look:
![Screen Shot 2019-06-03 at 20 53 01](https://user-images.githubusercontent.com/3635352/58823194-cbb2ce00-8641-11e9-8556-734e16b9e292.png)
