### ISSUE TITLE
QSelect use-input cordova

### ISSUE THREAD

**Issue by josejachuf** [quasarframework/quasar#4290]
@quasar - 1.0.0-rc.4 
@quasar/app - 1.0.0-rc.6
@quasar/extras - 1.1.2

  <q-select
    v-model="foo-model"
    :options="optStringsFoo"
    label="Foo"
    ref="foo"
    use-input
    @new-value="createFoo"
    :rules="[val => !!val || 'Required']"
    />

I have a select that shows a list of options (optStringsFoo), when I put the use-input attribute, in cordova-android two things happen:
1) Do not show me the items that were in optStringsFoo
2) Yes it allows to add a new items

In spa and electron works as I expect (show optStringsFoo and add items), but fails in cordova (android)

Jose

**Comment by rstoenescu** [comment]
Hi,

Please reopen by supply a codepen or jsfiddle as requested in the issue template. Saves both you and me a lot of time. Thank you.
