### ISSUE TITLE
Quirck in Ellipsis class breaks layout

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#4294]
When _ellipsis_ class exists, the layout breaks. The following pen demonstrates the issue:
https://codepen.io/tomers-the-encoder/pen/byZWbm?&editable=true&editors=111

**Comment by pdanpdan** [comment]
You have to give the div a max width in order for ellipses to work. In your case just add a `full-width` class on the parent `.col`: https://codepen.io/anon/pen/dErzRG?editors=1010

**Comment by tomers** [comment]
Thanks!
