### ISSUE TITLE
[Bug] QTime AM/PM is not correctly set when using model with mask of "hh:mm A"

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#4295]
### Software version

Quasar:
@quasar/app (v1+ only):
OS: Windows 10
Node: 10.15.1
NPM: 6.4.1
Browsers: Chrome

### JsFiddle
https://codepen.io/ajcastro/pen/OYqmpa?editors=1010

### What did you get as the error?
When you click the clock icon to open the QTime popup, you will see the selected is AM even though the model is in PM and the used model is in `"hh:mm A"` format

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
