### ISSUE TITLE
[Request] Add input mask to support selection between characters like AM/PM

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#4296]
I encountered to create a time-picker where the input time model is using the format of `"hh:mm A"`  e.g.
`08:00 AM`, `01:00 PM`. I would like to create a mask where I can let the users enter either `AM` or `PM`. I have imagined something like this:
```
<q-input mask="##:## [A|P]M" />
// or like this
<q-input mask="##:## [AM|PM]" />
```
This looks like an `or` regex allowing the possible characters only

**Comment by rstoenescu** [comment]
QInput usage on docs for these type of use-cases was added. Will be visible on next deployment.
