### ISSUE TITLE
[V1] QSelect outlined + multiple chips selection

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4305]
I need the outlined QSelect but with the multiple chips selection.

Currently the multiple chips selection is not compatible with "outlined".

Codepen: https://codepen.io/mesqueeb/pen/byJoGM

**Comment by pdanpdan** [comment]
If you remove filled it's going to work

**Comment by mesqueeb** [comment]
Good catch!!!
So embarrassing 😅
