### ISSUE TITLE
[v1 feature request] To make system to compile styles separetly to make separeate themes

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#4306]
It will be very helpfull If we can compile styles separetly from site.

For my site engine I want to make themes system with different styles. And users can make  there own styles. But how to compile them separetly from site? Is it possible for now, and how?

If is not, mabe to make plugin to compile styles separetly.

PS: It will be very good if I can write style not in 2 files but just in one if needed. 2 files themes not so clear as 1 file theme.

**Comment by digiproductmarketer** [comment]
Hi Dmitrij, 

I'm not a member of the team, so can't answer your question directly, but I am aware that there are discussions and investigations being undertaken by the team to address this, and I have just raised an issue to help the team formalise discussion among users about requirements for this.

**Comment by digiproductmarketer** [comment]
Hi Dmitrij

Can you add some details about this issue to the other issue

https://github.com/quasarframework/quasar/issues/4320

We are trying to get some initial comments on that so that the Quasar Team can do something by Sunday to begin a formal discussion on providing a suitable path forward on these issues.

Thanks

**Comment by nothingismagick** [comment]
Please close this issue, being tracked here: https://github.com/quasarframework/quasar/issues/4320

**Comment by hawkeye64** [comment]
@Dmitrij-Polyanin

**Comment by lucasfernog** [comment]
Closing this as it's being tracked here #4320
