### ISSUE TITLE
QSelect filter event is fired when new value is created

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4307]
When user will create / type a new value, than filter event should not be fired (because when value is selected from existing options, than the filter event is not called)

### How to reproduce
a) Type something new in q-select
b) Press enter

### Demo
https://jsfiddle.net/42ushv3y/2/

### Version
v1.0.0-rc.4

**Comment by pdanpdan** [comment]
The way it works now is correct, after you add the new value it is expected you want to see the full list, because there is no filter set. What would you expect to happen?

**Comment by woloda375** [comment]
I expected, that after enter, there will be the new option selected and the popup will be closed and no filter event will be called.

**Comment by metalsadman** [comment]
@woloda375 you can force to close the pop up by adding a ref on your q-select when `@new-value` is emitted. ie. `@new-value="(iv,dfn) => { yourNewValMethod(iv,dfn); $nextTick(()=>{ $refs.yourQselect.hidePopup();}) }"`.

**Comment by pdanpdan** [comment]
@woloda375 You are right - what I described as normal behavior was the normal for `multiple` QSelect.
In case of single selection it should close. I'll take a look.

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
