### ISSUE TITLE
QSelect Could be added a old value for filter events?

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4308]
It will be nice if filter event will have an old value of filter too. It will help distinguish if user will not type anything and will click on dropdown arrow(filter event is fired in this scenario too) or if user will removed last character of text in q-select.

### Demo
https://jsfiddle.net/f5dmLe9c/

### Version
v1.0.0-rc.4

**Comment by pdanpdan** [comment]
You can always store the old filter value, compare it in filter function and return as you better see fit.

**Comment by woloda375** [comment]
I understand it. This is a feature request and it is up to you if the feature will be implemented or not.

**Comment by nothingismagick** [comment]
My feeling is that this component is really complicated enough as it
stands. It has more props than some other frameworks have components, and
adding stateful history to a filter fn seems like its not worth the bloat
for core and a perfect fit for devland.
