### ISSUE TITLE
QSelect filter method

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4309]
Calling filter method will not change a filtering value in QSelect. My expectation is that it should behave like as user press that text direct into qselect

Demo
https://jsfiddle.net/236naw0u/11/

Version
v1.0.0-rc.4

**Comment by pdanpdan** [comment]
`filter` method filters the options without changing the input field (and the options list must be already open.
What you want is to something like this I think: https://jsfiddle.net/xqog8n5t/3/

**Comment by woloda375** [comment]
Yes, you are right. Thank you.
