### ISSUE TITLE
[v1] QSelect inconsistent disable style

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4312]
Hello!
This is related to: https://github.com/quasarframework/quasar/issues/4289

Please review the fiddle:
https://codepen.io/anon/pen/mYgYYK?&editable=true&editors=101
1) QInput value is greyed out when disabled 👍 
2) QSelect value is not greyed out when disabled 👎 

Expected: should be consistent

**Comment by olegvakulenko** [comment]
Is this Codepen correct? QInput fields not exist.

**Comment by jean-moldovan** [comment]
Updated the fiddle, sorry about the confusion!

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
