### ISSUE TITLE
[Docs] - Reference or copy relevant HTML5 element and attributes relevant for Quasar component

### ISSUE THREAD

**Issue by valasek** [quasarframework/quasar#4321]
First of all, thank you Quasar, it is amazing !

I had an issue with entering q-input for decimals - https://quasar.dev/vue-components/input#Input-of-number-type.

![decimal](https://user-images.githubusercontent.com/1046787/59010239-de3f2a00-8830-11e9-8d66-e2f3d7bc9382.png)

I solved it using HTML5 step attribute but had to raise a question on Discord.
```
<q-input :value="props.row.hours" type="number" step="0.1" dense
  @change="val => onUpdateHours({id: props.row.id, hours: val.target.value})"/>
```

I propose to:

1. In section https://quasar.dev/vue-components/input#Input-of-number-type
Add a note, that you can use additional HTML5 attributes for type number (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number).
E.g. to enter decimals you can use step attribute and specify nin and max value.

2. To enhance Quasar component's documentation and add, where relevant, which HTML5 attribute component is generating and if any/all HTMT5 attributes can be used and add a link to relevant MSDN sections.

This will be useful for newcomers. Feel free to close the issue if not relevant.

**Comment by rstoenescu** [comment]
Will be available in docs on next deployment.
