### ISSUE TITLE
[v1] - QTab icon position

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#4323]
### Software version
```
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  quasar-app-extension-ide-helper - 0.0.5 -- Quasar framework extension which enables IDE features like autocomplete by generating helper files for IDE to index.
  @quasar/quasar-app-extension-icon-factory - 1.0.0-rc.2 -- A Quasar CLI Extension

```
### JsFiddle
[https://jsfiddle.net/mojimo/rho3zyjg/](https://jsfiddle.net/mojimo/rho3zyjg/)

### What did you get as the error?
Icon "collections_bookmarks" is aligned a bit to the left. I have a feeling from the DOM inspector that it is caused because of aria-label text which shift the icon to the left.
![image](https://user-images.githubusercontent.com/37825539/59026791-8ec02480-8857-11e9-9786-cd0c031fdd10.png)
![image](https://user-images.githubusercontent.com/37825539/59026799-91bb1500-8857-11e9-8a99-c043e695a913.png)
If you replace "collections_bookmarks" with "collections" icon is aligned in the center.

### What were you expecting?
Icon "collections_bookmarks" to be align in the center of tab.
### What steps did you take, to get the error?
Open the JsFiddle above.

**Comment by pdanpdan** [comment]
Check the icon name. I think it is collections_bookmark.

**Comment by m0jimo** [comment]
It shows the icon correctly. Problem is that icon position depends on its name length. Try to rename or remove the aria-hidden element and icon is align correctly.
![image](https://user-images.githubusercontent.com/37825539/59028793-be256000-885c-11e9-8db3-b7973ae8bbee.png)

**Comment by pdanpdan** [comment]
It's collection_bookmark, without s. Remove the final s

**Comment by m0jimo** [comment]
I see. You are right. It finds the correct icon because it match **collections_bookmark** but I used **collections_bookmarks** and in this case it shifts the icon. 
Thanks. I think it can be closed.
