### ISSUE TITLE
[v1] - QTab with badge - position based on the text length not icon

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#4324]
### Software version
```
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  quasar-app-extension-ide-helper - 0.0.5 -- Quasar framework extension which enables IDE features like autocomplete by generating helper files for IDE to index.
  @quasar/quasar-app-extension-icon-factory - 1.0.0-rc.2 -- A Quasar CLI Extension

```
### JsFiddle
[https://jsfiddle.net/mojimo/rho3zyjg/](https://jsfiddle.net/mojimo/rho3zyjg/)

### What did you get as the error?
Badge position in TAB depends on the text length. If the text is short than the badge covers the icon.
![image](https://user-images.githubusercontent.com/37825539/59027239-c9768c80-8858-11e9-86d1-3ab330b85269.png)
![image](https://user-images.githubusercontent.com/37825539/59027249-d1cec780-8858-11e9-9067-1eb0ec548bb4.png)

### What were you expecting?
Badge should not cover the icon if there is no or short text for the tab.

### What steps did you take, to get the error?
Open JsFiddle

**Comment by rstoenescu** [comment]
Hi,

Well, unfortunately there's no "golden" path that we can take. Badges are absolutely positioned and so they cannot influence the size of the tab content. If we go with setting a hardcoded right-side position then bigger tabs will look very weird (we actually had a ticket regarding this). What you can do is to use the default slot to set your custom content, including a badge..

We will look into this in the following days, but currently I see no generic way to handle all use cases for this...
