### ISSUE TITLE
Filtering tree prevents expanding child nodes

### ISSUE THREAD

**Issue by wwwizzarrdry** [quasarframework/quasar#4326]
You cannot access any child nodes once you apply a filter to the tree component. 
I would expect that, once a user has filtered the tree, they could then resume exploring the remaining child nodes of the filter set.

**Apply Filter**
<img width="315" alt="filter_tree_1" src="https://user-images.githubusercontent.com/2218144/59043120-57b43800-8884-11e9-9156-ab35650cf4a1.PNG">

**Click a filtered node to expand and it fails to reveal children**
<img width="316" alt="filter_tree_2" src="https://user-images.githubusercontent.com/2218144/59043133-5daa1900-8884-11e9-8d6d-9a1952c35f7e.PNG">

**How it ought to behave**
<img width="311" alt="filter_tree_3" src="https://user-images.githubusercontent.com/2218144/59043149-64389080-8884-11e9-9d46-c66c246c0676.PNG">

**Comment by pdanpdan** [comment]
Having no example of code and data from your side I would guess none of the leafs that are under Bob Marley node have the string 'bob' so they are filtered out - check how you build and filter your data.

**Comment by wwwizzarrdry** [comment]
Yeah, example code isn't even necessary. You already see the problem with the filter function.

Correct Behavior:
If a parent node is found to contain a match on the filter, then all child nodes of that parent should be included in the result set - not filtered out.

**Comment by smolinari** [comment]
The correct behavior is to filter all the nodes with the filter that is applied, not just the top level ones. In other words, the filter you offer is recursively applied across all the nodes in the whole tree. What you want is a filter of the first level of nodes only, as @pdanpdan mentioned.  

Scott

**Comment by MacMaru** [comment]
@smolinari I don't think just top level is the issue here: for any match on any level, if there are children, they should not disappear because _they_ don't match the filter. See for @wwwizzarrdry's desired behavior the way VTreeView implements a BFS: https://vuetifyjs.com/en/components/treeview#searching-a-directory.

**Comment by smolinari** [comment]
@MacMaru - let me put my comment above another way. If you want the nodes to filter at only the first level, then you need to build your filter to do that. Quasar has no control over how you filter your nodes. My comment was an extension of Dan's quoted below.

> I would guess none of the leafs that are under Bob Marley node have the string 'bob' so they are filtered out - check how you build and filter your data.

Scott
