### ISSUE TITLE
[v1] Quasar LocalStorage do not restore Date object after get

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#4338]
I have object

```
import {LocalStorage} from 'quasar';

const obj = {
   prop1: "hi",
   prop2: new Date()
}

LocalStorage.set("key",obg);
const newObj = LocalStorage.getItem("key");
```

If I store it with quasar LocalStorage, and after it get from it.
Object prop2 Date field become string.
But have to be Date.

**Comment by metalsadman** [comment]
i think coz you stored it inside an object, try setting it on a different key as is.

**Comment by Dmitrij-Polyanin** [comment]
This is not solution, because if it is all automated it is simple. But if I have complex object with many properies some of them are Dates, it will be painfull and not a solution.

**Comment by metalsadman** [comment]
while you are right, the api only knows the type by each key which they are assigned, in your case is an object, it doesn't traverse deep inside it to encode/decode the inner properties in their respective type.

**Comment by Dmitrij-Polyanin** [comment]
Ok. It is clear.
So I propose feature to investigate object graph deep and to retreave the same object as placed in localStorage.

**Comment by rstoenescu** [comment]
Store the Date on a separate key and restore using your own logic which includes new Date(..).
