### ISSUE TITLE
[v1] `this.$q.lang.getLocale()` is misleading

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#4340]
I've been using `setLocale()` to set the language the user has selected in my app but when checking this against `getLocale()` it doesn't match. I understand this is because `getLocale()` always returns the users locale (based on browser) but the name is misleading.

I propose it gets changed to `getBrowserLocale()` or `getUserLocale()`.

I'm aware I can get the information I need from `$q.lang` - this issue is merely to clear up confusion.

**Comment by rstoenescu** [comment]
I agree with you, but at this point, there will be no breaking changes in v1.
So what we can do is enhance the docs instead. Care to PR something?

**Comment by webnoob** [comment]
Sure I'll sort a PR.

**Comment by rstoenescu** [comment]
Thanks!
