### ISSUE TITLE
Context menu does not stay open in Safari v1 Mac 

### ISSUE THREAD

**Issue by turigeza** [quasarframework/quasar#4343]
Quasar: 1.0.0-rc.4
OS: Mac High Sierra 10.13.4
Browsers: Safari 11.1

### JsFiddle
https://codepen.io/turigeza/pen/OYKdag?&editable=true&editors=101
Above is exactly the same as the example in the docs. 

### What did you get as the error?
No errors

### What were you expecting?
Context menu should stay open after ctrl + click yet it closes after the release of the touchpad. 

### What steps did you take, to get the error?
Ctrl click on the image as you would to get the context menu showing. Context menu will not stay open unless you drag your cursor onto it.

Let me know if it make sense or you need more info. Thank you !

**Comment by rstoenescu** [comment]
Hi,

I think there is a misunderstanding. If you use `v-close-popup` then any type of click, even if it a CTRL + click will still close the menu... If you don't want the menu to be closed or you have a particular case for your app, skip using `v-close-popup` and use a v-model instead on the menu then control it yourself by adding events to elements within the menu.

Please reopen if I didn't understand your ticket. Thanks.

**Comment by turigeza** [comment]
Hi,

If you have a mac take look. The context menu is unusable on Safari.  
Otherwise let me try and explain.

1. Right Click = Ctrl Click on Mac. This action is used to open a context menu.
2. v-close-popup has not got anything to do with it sorry. I am not clicking on the menu items
3. I am clicking on the area where the context menu is placed. I am trying to bring up the context menu. The context menu opens then immediately closes.

I will do a video for you ...

**Comment by nothingismagick** [comment]
Doesn't happen for me...

**Comment by turigeza** [comment]
@nothingismagick Maybe it is limited to this 11.1 version ? Let me check on an other computer.

**Comment by turigeza** [comment]
@nothingismagick It happens on 12.1.1 as well. Just checked on a different computer different operating system very diff hardware. It isn't seem to be version or hardware related. 

Don't drag your cursor onto the menu. You might be doing that. In that case the menu stays open. 

Just right click (ctrl+click) on the area should keep the menu open. Yet it doesn't.

**Comment by nothingismagick** [comment]
Nope. I am on a desktop using a mouse with right-click and cannot replicate
your issue. It works for me as intended.

>

**Comment by turigeza** [comment]
Ok well let me try with a mouse but I am using a touchpad and I CTRL + click.
Tried 2014 mapbook 13" pro built in. No force touch.
2015 macbook pro magic trackpad force touch. Both does the same.

**Comment by turigeza** [comment]
@nothingismagick It happens with an apple mouse too. Maybe it's the weather : ) I don't know ... What is it you are trying it with? iMac + Apple Mouse ? 

Are you dragging the cursor onto the menu ?

**Comment by nothingismagick** [comment]
No, I right click and the mouse is automatically on top of the menu. (Using
a Mac Pro)

>

**Comment by turigeza** [comment]
I had one more attempt to see if it works on my friend's computer in case it has something to do with safari syncing settings. Because the previous computers were both mine. So this is yet an other computer Safari 12.0 and the shows the same issue.

**Comment by nothingismagick** [comment]
Wow thanks for digging in. Hmm, will have to look into it next week.
