### ISSUE TITLE
Add 'label' slot for QChatMessages

### ISSUE THREAD

**Issue by jlanzarotti** [quasarframework/quasar#4345]
I have a case where I would like to create more complex labels between chats. Is it possible to add a slot to do something like this: 

```
q-chat-message
    template(slot="label")
    ... complex_label()
```

**Comment by smolinari** [comment]
@jlanzarotti - Complex in what sense? Can you expand on your use case?

Scott

**Comment by jlanzarotti** [comment]
Sure!

Content generated from a vue templete, basically a table with data that works like announcements to the chat users.

Basically now I can do this with raw HTML and JS, but it would be nice to generate this in another way.

Thanks!

**Comment by smolinari** [comment]
How about just calling it a "Bot" and using the message default slot as so many other chats do? 😁 

Scott

**Comment by jlanzarotti** [comment]
I though about it, but it didn't fly. The label in the q-chat is well centre between messages and perfect to read these events or announcements.

**Comment by jlanzarotti** [comment]
I guess this will be the change needed in QChatMessage.js to support the slot

```
      h('div', {
        staticClass: 'q-message-label text-center'
      }, [
        this.$scopedSlots.label !== void 0
          ? this.$scopedSlots.label()
          : (
            this.label
              ? h('div', {
                domProps: { [this.labelSanitize === true ? 'textContent' : 'innerHTML']: this.label }
              })
              : null
          ),
        ]),
```

However, there is another way to achieve the same without using slots 😃
Thanks!
