### ISSUE TITLE
Babel issue after installing Quasar plugin via Vue-cli

### ISSUE THREAD

**Issue by utlamn** [quasarframework/quasar#4346]
I've installed quasar plugin (`vue-cli-plugin-quasar@1.0.0-rc.1`) via `vue-cli`. After installing when building the dev with `npm run dev` i'm getting this error:

```
 error  in ./node_modules/quasar/src/index.esm.js

Module parse failed: Unexpected token (13:2)
You may need an appropriate loader to handle this file type.
| 
| export default {
|   ...VuePlugin,
|   install (Vue, opts) {
|     VuePlugin.install(Vue, {

 @ ./src/main.js 12:0-160
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

```
line 13 is `...VuePlugin,`; here is the full file:

> import VuePlugin from './vue-plugin.js'
> 
> import * as components from './components.js'
> import * as directives from './directives.js'
> import * as plugins from './plugins.js'
> 
> export * from './components.js'
> export * from './directives.js'
> export * from './plugins.js'
> export * from './utils.js'
> 
> export default {
>   ...VuePlugin,
>   install (Vue, opts) {
>     VuePlugin.install(Vue, {
>       components,
>       directives,
>       plugins,
>       ...opts
>     })
>   }
> }

I'm assuming it is a babel issue, but as it is being from a `quasar` file I'm reporting here. I'm stuck on this for a long time, any hint would be really appreciated.

**Comment by Jiujiale** [comment]
I have the same problem, have fix it ?

**Comment by rstoenescu** [comment]
Hi, Do you have Babel installed into your vue-cli project?

**Comment by cattlesheep** [comment]
i have the same problem.

**Comment by rstoenescu** [comment]
Please install babel too. It is a requirement.

**Comment by rstoenescu** [comment]
Also, hope you are using v2 of the vue-cli-plugin-quasar

**Comment by VadimCeretean** [comment]
babel is installed but problem not fixed

**Comment by rstoenescu** [comment]
@VadimCeretean use latest vue-cli-plugin-quasar. Delete any babel config related to Quasar (it's no longer necessary now). The Quasar usage in main.js should be like in the "auto-import" version.
