### ISSUE TITLE
How can I find a real cross-platrom app on github？

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#4347]
I can't find an Electron，Cordova，PWA integrated project on Github.
Are there any recommendations?

**Comment by rstoenescu** [comment]
Lately I see a lot of companies using Quasar, and this means that the code for their apps is private.

However, you can check out https://github.com/quasarframework/quasar-awesome where there are some links to source code on github.

Generating an Electron, Cordova and/or PWA is easy with Quasar.. just use the right parameter (`-m <mode>`) when you build your app.
