### ISSUE TITLE
[v1] Drawer click event does not fire on overlay mode

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#4348]
### Software version

Quasar:
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Drawer click event does not fire when drawer goes overlay mode in browser.
### What were you expecting?
drawer links should fire without needing to change the screen size.
### What steps did you take, to get the error?
https://quasar.dev/introduction-to-quasar you can test it on the doc site, open inspect, narrow the width so drawer goes overlay mode, click on links (will sometime work after a fresh change in dimension), click again then no events fired, change the size clicks will work again, rinse and repeat.

**Comment by metalsadman** [comment]
Never mind this issue, seem like it was my browser or some extension messing with the routing.

**Comment by nothingismagick** [comment]
@metalsadman - can you jump on the Quasar Discord server - need to ask you something.
