### ISSUE TITLE
[v1] QEditor has some bugs

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#4349]
Hi!

I am using QEditor on my site an noticed many bugs here.
I think it will be good by Q team to make full human test of QEditor in different situations.

I write here some bugs I noticed.

1. On fullscreen editor when use any style button area on editor scrols on top. But need to stay on its place. Very anoing.
2. If i used some style, for example `code` on some line of conetnt and then moved caret to another place, button `code` showes like pressed as I am using `code` here, but `code` was on previous position.  You need to update putton toge info when caret position changed.
3. `Clear format` working very strange some code format clear, some not. Some times I need to remove text fully, and then to paste as text to reset code style, because `clear format` not working as expected.
4. I tried to copy as html all code in QEditor to another QEditor, and all code becode broken.
My content tags was mixed, and no way to clear them with `clear format`.

5. I need to make custom styles for h1-h6 tags, and I can use content-class="my-content-class" to QEditor. And it works. But new h1-h6 styles not affecting styles on toolbar.
In conent I see my styles, on toolbar hemu h1-h6 I senn not styled elements.

Sorry that I can not write each bug in separate issue, it is huge work.
I can connect with skype with someone from Q team and show on my editor all bugs i noticed to explain.

And thank you Razvan and all team for huge and perfect work on Quasar project!
I wish Quasar team and Quasar project to get through problems and to ssucced with your wishes!

**Comment by Dmitrij-Polyanin** [comment]
Little up.
Many new bug + old ones. Now it is impossible to work with this component.

**Comment by rstoenescu** [comment]
Grouping with the above tickets.

**Comment by Dmitrij-Polyanin** [comment]
+ Bug with code editing mode.
After return fro "code edit mode" history broken to all edits before "code edit mode" and inside "code edit mode"

**Comment by rstoenescu** [comment]
For upcoming "quasar" v1.5.10:

1,2 Fixed
3,4 Browser behavior, cannot change/fix

Not sure what you mean by 5.

**Comment by mathiasonea** [comment]
Hey guys, the issue #5057 was not fixed and still this issue is closed? Is it possible that it was forgotten?

**Comment by rstoenescu** [comment]
@mathiasonea QEditor relies on document.execCommand and the native browser support for contentEditable. If the browser leaves a `<br>` tag, it's nothing Quasar can do. However, you can add a button to clear content. Sorry for any incoveniences.

**Comment by mathiasonea** [comment]
Thank you @rstoenescu for your quick response. I will do what you propsed.
Keep up the good work, it's amazing OSS work :-)

Cheers,
Mathias
