### ISSUE TITLE
QTabs in QToolbar constantly redraw themselves at certain positions in chrome

### ISSUE THREAD

**Issue by KnowZero** [quasarframework/quasar#4350]
Quasar: v1 rc4
@quasar/app (v1+ only):
OS: Windows 10 and Linux Mint

Browsers: Chrome

### What did you get as the error?

I am having a weird issue with QTabs on chrome (not on firefox) in Windows 10 and Linux Mint. Where the tabs would recalculate themselves infinitely. (looks like they are jumping back and forth when the last tab is partly covered). FireFox is perfectly fine though.

The issue seems to be dependent on the resolution (or more accurately the container)

https://codepen.io/anon/pen/wLvJoR?editors=1010

Is this the same issue you are having?

![](https://i.imgur.com/091TMby.gif)

### What were you expecting?

For it to be stable

### What steps did you take, to get the error?

It seems to be related when the last tab is partly hidden, the container has to be just right for this to happen. This is why I set the width to 1080 on the parent div to better demonstrate it.

**Comment by digiproductmarketer** [comment]
I had almost the same issue, but my issue occured on Windows 7 but was not replicable on Windows 10.

Here's where I re-opened it 

https://github.com/quasarframework/quasar/issues/4236

and here's the original issue

https://github.com/quasarframework/quasar/issues/4209

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
