### ISSUE TITLE
[REQUEST] QSelect text alignment

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4351]
Could you please add support for right side text alignment for value, label and options?

Demo
https://jsfiddle.net/fvqs1n5y/6/

Version
v1.0.0-rc.4

**Comment by pdanpdan** [comment]
You have access to slots for both selected and options, so you can align the text as you wish.

**Comment by woloda375** [comment]
Thank you @pdanpdan, but I could not see a slot for "Label" section on top, which could have a option for text alignment. Changes: in https://jsfiddle.net/hd9cg8rL/

**Comment by rstoenescu** [comment]
New props (input-class, input-style) available in "quasar" v1.1.7.

**Comment by JokerMartini** [comment]
Unless i missing something, the input-class and input-style do not appear to affect anything in the latest build.

**Comment by pdanpdan** [comment]
Detail on version, reproduction codepen?

**Comment by grojguy** [comment]
> Detail on version, reproduction codepen?

@rstoenescu and @pdanpdan - This is not working, as far as I can tell.

I have same results as @JokerMartini... `:input-style` has no effect on the `q-select`.

It's easy to reproduce, just insert the example from the Quasar docs `:input-style="{ backgroundColor: '#ff0000' }` in the codepen example here: https://codepen.io/pen?&editors=101   (tried on 1.22.9 and 2.11.10)

```
      <q-select clearable filled color="purple-12" v-model="model" :options="options" 
        :input-style="{ backgroundColor: '#ff0000' }">
      </q-select>

```

No input property I try has any effect on the q-select.   Conversely, `:input-style` works fine on a q-input.

**Comment by pdanpdan** [comment]
- no codepen attached (as you can see from url it is empty)
- you are not using `use-input` on QSelect, so there is not input to style
