### ISSUE TITLE
Can't find a disabled q-select by name or data-name

### ISSUE THREAD

**Issue by Ricky-rick** [quasarframework/quasar#4352]
Quasar: 
@quasar/app (v1+ only):

### JsFiddle

https://codepen.io/anon/pen/ydLQMq?&editable=true&editors=101

### What did you get as the error?
In my cypress end to end test i want to check if a given q-select is disabled. So i gave the disabled  q-select a (data-)name.
When i look into the dom, i can't find the q-select because quasar does not set the (data-)name on any html element.

### What were you expecting?
The disabled q-select should set the a (data-)name attribute on a html element in the dom.

**Comment by nothingismagick** [comment]
I can confirm your issue, and until Razvan gets back from vacation I am not sure what exactly we can do about this. 

One temporary workaround would be to wrap the select in a div and give that div a `data-wrapper-name="nameWrapper"` prop and then test for the `.q-field--disabled` class.

I think that in the grander scope of things it isn't exactly clear WHERE the data prop should be placed. What do you think about having an empty placeholder span where the real input area would be?

**Comment by Ricky-rick** [comment]
the diferences in the dom are minimal. 
**disabled**
```html
  <div class="q-field row no-wrap items-start q-select q-field--auto-height q-select--without-input q-field--standard q-field--float q-field--disabled">
    <div class="q-field__inner relative-position col self-stretch column justify-center">
      <div tabindex="-1" class="q-field__control relative-position row no-wrap">
        <div class="q-field__control-container col relative-position row no-wrap q-anchor--skip">
          <div class="q-field__native row items-center">
            <span>Google</span>
	  </div>
        </div>
        <div class="q-field__append q-field__marginal row no-wrap items-center q-anchor--skip"><i
          aria-hidden="true"
          class="material-icons q-icon q-select__dropdown-icon"
        >arrow_drop_down</i></div>
      </div>
    </div>
  </div>
```
vs **enabled**
```html
  <div class="q-field row no-wrap items-start q-select q-field--auto-height q-select--without-input q-field--standard q-field--float">
    <div class="q-field__inner relative-position col self-stretch column justify-center">
      <div tabindex="-1" class="q-field__control relative-position row no-wrap">
        <div class="q-field__control-container col relative-position row no-wrap q-anchor--skip">
          <div tabindex="0" name="enabled" data-name="data-enabled" class="q-field__native row items-center">
            <span>Google</span>
          </div>
        </div>
        <div class="q-field__append q-field__marginal row no-wrap items-center q-anchor--skip"><i
          aria-hidden="true"
          class="material-icons q-icon q-select__dropdown-icon"
        >arrow_drop_down</i></div><!---->
	</div>
    </div>
  </div>
```

the difference is in the parent of the span with the model value ("Google"). 
This div should also have a data-name and/or name property when the select is disabled.

I made a PR #4357
