### ISSUE TITLE
[v1.1 request] To make style (skin) compiler 

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#4354]
### My thoughts.

I am building skin system for my site engine, and on now technologies it is difficult to achieve.
I think this is common case for many projects, to apply customs skins.

**What is skin?** 
Some aditional css styles above Qausar CSS.

**To build custom skin I need**
1. Some command to compile my stylus skin file. It may be extension.
I dont know the extensions syntax but it can be something like this
`quasar compile-skin my-skin.styl`
And this command produce css code in one file => `my-skin.css`
2. I need to apply `my-skin.css` to the site, so Quasar Api need to have function to apply
```
import {applySkin} from "quasar"
applySkin("MySkin", "/somedir/my-skin.css");  //  1 parameter is skin name, it needed to remove skin by name.
```

3. And to remove skin
`removeSkin("MySkin")`
4. Ability to add many skins at one time. 
```
applySkin("MySkin", "/somedir/my-skin.css");
applySkin("Skin2", "/somedir/my-skin2.css");
applySkin("Skin3", "/somedir/my-skin3.css");
```
It needed to skin different components separetly if I want.

5. Ability to remove many skins
```
removeAllSkins()
removeSkins(["MySkin","Skin1"]);
```

This is my vision of how skins have to work.

**Comment by nothingismagick** [comment]
Please close this issue. It will be addressed in the RFC for theming.
