### ISSUE TITLE
QInput type="number" with two decimal places, started by "." 

### ISSUE THREAD

**Issue by erickhcs** [quasarframework/quasar#4355]
By typing ".15" I can get the number 0.15 as desired. But by typing ".015" the input converts the number to zero by typing ".0", without waiting for the rest of the number. Would that be an issue?

**Comment by pdanpdan** [comment]
QInput type="number" with four decimal places, started by "."

**Comment by rstoenescu** [comment]
Just to be sure, this is the right "syntax": `<q-input type="number" v-model.number="model"`.
Fix will be available in rc.5
