### ISSUE TITLE
[0.15 and >] QInput decimals unwanted behavior

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#4359]
### Software version

Quasar: 0.15 but maybe on newer too 
OS: N/A
Node: v8.9.3
NPM: 5.5.1
Browsers: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
iOS: N/A
Android: N/A
Any other software related to your bug:

### JsFiddle

https://jsfiddle.net/m19L45s0/

### What did you get as the error?
Declare a QInput to handle floating numbers.
```jsx
<q-input
  type="number"
  :decimals="3"
  v-model.trim="val1"
  :color="'primary'"
  align="center" />
```

I noticed a couple of bugs related to the way the decimals validation is done.
1. It would be more pleasant if the limitation of the decimals is realized directly when entering a key of the keyboard rather than waiting for the box to lose the focus, otherwise the user has a surprise when he sees the number he has entered changing from `0.9994329432949949929` to` 0.999`. Ex

   ![1](https://user-images.githubusercontent.com/7946730/59318797-49a45400-8c96-11e9-8e9b-befa227be404.gif)

   Here, I entered some random keys, then changed the focus to the right box. The left box saw its content truncated.

2. Entering `0.9999` is magically converted to `1`, instead of being truncated to `0.999`. I want 3 decimals max, not a float ceiling.

   ![quasar-input-decimals-error-0 999 became 1](https://user-images.githubusercontent.com/7946730/59318967-fda5df00-8c96-11e9-9e0b-094f6df23b4c.gif)

3. Start by entering the number `0.666` and then continu to hit the key `6`. 

   ![quasar-input-decimals-error-666-repeated](https://user-images.githubusercontent.com/7946730/59319023-36de4f00-8c97-11e9-8212-c69487721ada.gif)

   The number get rounded and truncated at each key hit.

I think the way the `decimals` property [is handled](https://github.com/quasarframework/quasar/blob/v0.15/src/components/input/QInput.vue#L300) could be much better and less aggressive for the user.

### What were you expecting?
* Restricting decimals on key down event.
* Mostly, do not round the number.

### What steps did you take, to get the error?
N/A

**Comment by rstoenescu** [comment]
Hi,

v0.15 is out of support for quite some time... Please upgrade to v1 as soon as possible. Sorry for any inconveniences. Halting v1 development and fixing a bug for v0.15 + making a v0.15 release is not ideal for Quasar at the moment. Hope you understand..

**Comment by purell** [comment]
From what I've saw, you replaced the `decimal` property by [Mask](https://quasar.dev/vue-components/input#QInput-API) in version 1.0. 

But this not working properly too, take a look
![image](https://user-images.githubusercontent.com/7946730/59777888-73a3da80-9283-11e9-8fba-f3292883ade1.png)

I succeed to enter more number than the mask allows :(

**Comment by pdanpdan** [comment]
This is by design if you use fill mask in reverse. If you don't set reverse it's respecting the number of digits in mask.
