### ISSUE TITLE
<i> tag incompatibility with Medium editor

### ISSUE THREAD

**Issue by mrapogee** [quasarframework/quasar#436]
First of all, this framework is awesome! So much functionality!

But, I think there's a few problems right now when it comes to assumptions. The biggest problem is probably the `<i>` tag. The `<i>` tag is defined as the italics tag, and many tools and editors assume it to be so. For example, I'm using the medium editor and it uses the italics tag to represent italics, like it's supposed to. Quasar assumes that `<i>` means icon, breaking this.

I recommend changing it to something like `<q-i>`, and I also strongly advise changing all other "naked" tags ie `input` to `q-input` for similar reasons, I've run into problems with compatibility.

**Comment by rstoenescu** [comment]
There's going to be a "q-input" component in v0.14, indeed. Will think about your case. A workaround for you is to write a CSS class to overwrite font declaration prop on <i> tags and apply it to the medium editor container.

**Comment by rstoenescu** [comment]
Fontawesome uses the `<i>` tag too. Not sure about if a breaking change should be introduced or not. Rather, a CSS class like I mentioned earlier would suffice. Will ponder on this more.

**Comment by mrapogee** [comment]
Yup, but both material and font awesome use a class. 

I think it's fine to use the `i` tag, but if it's used it should have a class. That way you don't have to manually opt-out.

**Comment by rstoenescu** [comment]
Fixed in future v0.14.
