### ISSUE TITLE
[META] Issue and PR Templates

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#4360]
It seems that there is a "new" method for creating issue and pr templates.

![Screen Shot 2019-06-12 at 10 26 50](https://user-images.githubusercontent.com/35242872/59335331-adf9fe80-8cfc-11e9-993e-e653cc32a794.png)

https://github.com/quasarframework/quasar/blob/dev/.github/ISSUE_TEMPLATE.md

https://help.github.com/articles/about-issue-and-pull-request-templates

**Comment by rstoenescu** [comment]
Fixed.
