### ISSUE TITLE
q-select width use-input bug when put model {label, value}

### ISSUE THREAD

**Issue by ldenblyd** [quasarframework/quasar#4362]
hello everyone, i have an issue for adding and object model on a select width use-input

it's work but i cannot remove element after selected

example: 
https://codepen.io/anon/pen/rEabKO?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Use `clearable` Boolean prop.

**Comment by ldenblyd** [comment]
i add it but dosen't work 
https://codepen.io/anon/pen/rEabKO?&editable=true&editors=101
