### ISSUE TITLE
IE11: Pagination overlap issue

### ISSUE THREAD

**Issue by blaluc** [quasarframework/quasar#4363]
IE 11 (v. 11.0.9600.19356)

The 'records per page' dropdown overlaps the page counter. The below picture is from the quasar rc.4 documentation page (https://quasar.dev/vue-components/table).

![image](https://user-images.githubusercontent.com/4599417/59356988-4e1a4c80-8d2a-11e9-9bd8-56fb65036075.png)

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
