### ISSUE TITLE
IE 11: form/layout issue

### ISSUE THREAD

**Issue by blaluc** [quasarframework/quasar#4364]
The below picture shows how the doc section "input types" in the page https://quasar.dev/vue-components/input, is wrongly rendered on IE 11:

![image](https://user-images.githubusercontent.com/4599417/59357844-d3523100-8d2b-11e9-8950-ce8fec6ab718.png)

The same in Chrome is correctly showed:
![image](https://user-images.githubusercontent.com/4599417/59358066-3774f500-8d2c-11e9-91f3-ac9502f4f4b2.png)

**Comment by webnoob** [comment]
Worth noting, I've pulled latest Quasar and run locally - this doesn't happen. I can reproduce the issue on live but it's Ok with a local build.

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
