### ISSUE TITLE
IE 11: flex/layout

### ISSUE THREAD

**Issue by blaluc** [quasarframework/quasar#4365]
In IE11, the navigation links at the bottom of each page in doc site, appear as the following:

![image](https://user-images.githubusercontent.com/4599417/59358807-87a08700-8d2d-11e9-9cce-3fca31ea9c63.png)

Could it be an issue related to the flex layout?

(from quasar/docs/src/components/DocPage.vue)

```
 .doc-page-nav.text-primary.q-pb-xl(v-if="nav !== void 0")
    .text-h6.q-pb-md Ready for more?
    .q-gutter-md.flex
      router-link.q-link.doc-page-related.doc-page-related-bordered.rounded-borders.q-pa-md.cursor-pointer.column.justify-center.bg-white(
        v-for="link in nav"
        :key="link.category + link.path"
        :to="link.path"
      )
        .row.no-wrap.items-center
          q-icon.col-auto(
            :name="`chevron_${link.dir}`"
            v-if="link.dir !== void 0"
            :class="link.dir === 'right' ? 'order-last q-pl-md' : 'order-first q-pr-md'"
          )`
```

**Comment by webnoob** [comment]
Worth noting, I've pulled latest Quasar and run locally - this doesn't happen. I can reproduce the issue on live but it's Ok with a local build.

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
