### ISSUE TITLE
[v1]-QUploader - How to show a tooltip when the selected file is too large

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#4370]
When the selected file is too large, it may be better to display a prompt than to do nothing.
I did not find the right event in the document.

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by QQ34205037** [comment]
@smolinari Thank you for your reply.
I just found out that maybe I should use ':filter' instead of ':max-file-size'

**Comment by QQ34205037** [comment]
```
:filter="checkFileSize"
```
```
checkFileSize(files) {
      return files.filter(file => {
        file.size < this.fileMaxSize ||
          this.$q.notify({ message: `File[${file.name}] is too large` });
        return file.size < this.fileMaxSize;
      });
    }
```
It's enough to solve my problem.
