### ISSUE TITLE
[v1] .text-truncate missing

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#4373]
Minor issue.

I noticed `.text-truncate` is not working when I tried to use it and I don't see it in https://github.com/quasarframework/quasar/blob/dev/ui/src/css/core/typography.styl

Removed by accident?

Also should a `.text-strike` with `text-decoration:line-through` be added?

**Comment by hawkeye64** [comment]
Fyi, @rstoenescu This in the documentaion for "Upgrade guide", "Typography" and "Visibility". Cannot find it in source at all.

**Comment by rstoenescu** [comment]
Hi,

I think you are referring to `ellipsis` / `ellipsis-2-lines` / `ellipsis-3-lines` CSS classes (but the latter two work only on webkit browsers).

But added `text-strike` (will be available in rc.5).

**Comment by smakinson** [comment]
Thanks! The `.text-truncate` I was attempting to use is mentioned in the list here: https://quasar.dev/style/typography#CSS-Helper-Classes, sorry I should have included that in the issue.

**Comment by rstoenescu** [comment]
Yep, saw it. Fixed the docs.
Thanks for reporting!
