### ISSUE TITLE
Q-input autofocus keeps the focus even when you are done typing.

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#4374]
Once you hit the magnifying glass (search button) on the keyboard after you are done typing ( in case of type=search ) , the keyboard should hide and the q-input field should loose focus. This doesn't happen and the field still is in focus if you set autofocus='true'

Even if its a regular q-input and not search , hitting the return on the android/ios keyboard should enter focus on the input field. This does not happen. 

Autofocus= true forces focus on the field until you hit the android back button or somewhere in the middle of screen. As I said earlier, the focus should be lost when you hit search or return on keyboard.

**Comment by pdanpdan** [comment]
Works for me.

**Comment by rachitpant** [comment]
![issue-search](https://user-images.githubusercontent.com/1474415/59461110-9e5ae280-8dee-11e9-955d-bf7880ea086f.gif)

**Comment by rachitpant** [comment]
Towards the end of the video above you would see , even when I click the search button multiple times on the keysboard , the keyboard doesn't hide ( nor do i loose focus on the q-input ). There is no submit , or server involved in the above search functionality , its entirely client side by writing to a vuex variable and using it to filter data.
If you see the gmail app on your phone , the keyboard hides once you click on search button, which makes sense, You dont need keyboard when you think you are done typing and want the search results.

**Comment by rstoenescu** [comment]
Hi,

Please upgrade to Quasar v1. We'd rather be spending time on v1 as a bug such as this one for 0.17 requires a whole lot of effort to fix + make a new release.

Please tell us if this is a stop-ship for you and upgrading is out of the question at the moment... but pls pls be sure this is the case. I cannot stress enough what a hassle would be for us to halt v1 development and fix this for v0.17.

Thank you.
