### ISSUE TITLE
[v1 request] Add way to stack many headers in layout.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#4378]
Request is to add way to make many Layout Headers with different settings.

This is an example I want to achieve - https://codepen.io/anon/pen/bPVmaJ
But in example code is strange and buggy (custom z-index, custom top position)

Possibility to make two headers lines where
1 line always show
2 line with reveal property (hide on scroll)

Now if I make 2 headers, the second hides on 1 back, but I think It will be good to stack next line as on example (but nativly, without custom css).

It is common case when there is more then 1 headers and one is always stiky ans the second hides on scroll.

And the same I think need to be with footer.

**Comment by metalsadman** [comment]
Achievable using qpage sticky https://codepen.io/metalsadman/pen/PrZaRB?&editable=true&editors=101. What i would like to see though, is the android native behavior on parralax actionbar/toolbar/ collapsing toolbar.

**Comment by Dmitrij-Polyanin** [comment]
Thank you!
Is it possible to make sticky not 2 line, but 1?

**Comment by Dmitrij-Polyanin** [comment]
On your example top line disapiars and second is sticky.
But how to make second line disapear, when first is showes alwais?
