### ISSUE TITLE
[Request] Form inputs feedback.

### ISSUE THREAD

**Issue by NothingWeAre** [quasarframework/quasar#438]
* It would be great if there is place to put vlidation feedback that will be displayed automatically when input has errors. 
Maybe move class "has-error" to container div for easy implementation.
For example
```
 <div class="floating-label">
   <input id="password" required class="full-width" v-bind:class="{'has-error': loginError}" type="password" v-model="password">
   <label for="password">Password</label>
   <small class="field-feedback">Wrong username or password</small>
 </div>
```

* I think that labels should respect field state, and change colors if field has errors
* Maybe more field state classes would be useful(when classes affect field accent, label, feedback message), for example:
```
field-positive
field-negative
field-info
field-warning
```

**Comment by rstoenescu** [comment]
Hi, way ahead of this with v0.14. I'm glad many of these kind of requests are already implemented. Stay tuned for v0.14.

**Comment by NothingWeAre** [comment]
Hi. that's very good news for me, thanks. 
Small suggestion though. Maybe leave this issues open, but with tags (release in v....), so that people will see that some feature already has been requested.

**Comment by rstoenescu** [comment]
Yes, you can check milestones. I set the milestone for each github ticket.
