### ISSUE TITLE
QInput mask freezes browser on input

### ISSUE THREAD

**Issue by thugic** [quasarframework/quasar#4381]
**Describe the bug**
When using an input mask and keep on typing in the input field, browser window freezes for some time (depending on input mask length, as far as I could test).

**Codepen/jsFiddle (required)**
[JSFiddle](https://jsfiddle.net/nbzo7ah4/1/)

**To Reproduce**
1. Go to JSFiddle link
2. Paste text you find there or input your own
3. Keep on tyiping digits
4. See browser freezing

**Expected behavior**
Should stop accepting input when user input is longer than input mask.

**Platform (please complete the following information):**
OS: Linux / Android
Browsers: Chrome Mobile, Chrome Desktop, Firefox Desktop

**Additional context**
This behavior has also been confirmed by users on the Discord channel.

**Comment by nothingismagick** [comment]
This looks like a an rDoS (regex denial of service). Can confirm on MacOS Chrome.

**Comment by Hamdan85** [comment]
I can confirm the same behaviour here... will provide codebase if necessary

**Comment by rstoenescu** [comment]
Fix will be available in final 1.0.0
