### ISSUE TITLE
Full-height is not working properly

### ISSUE THREAD

**Issue by jarlos3** [quasarframework/quasar#4383]
Hi guys...

I'm setting the class "full-height" (and "fit") to a q-card contained in a q-page, but I can't to do the card have the full height of the q-page.... Am I missing something?

Thanks in advance!

![asdf](https://user-images.githubusercontent.com/46208250/59526743-8aff5400-8e8e-11e9-804f-eb171cfc1a04.png)

**Comment by rstoenescu** [comment]
https://codepen.io/rstoenescu/pen/vqLmRd

Emphasis on: 
```html
<q-page-container>
      <q-page class="column">
        <q-card class="col my-card text-white"
```

The CSS helper class `full-height` simply applies `height: 100%`.. but CSS does not work like you'd expect in all scenarios... Best approach in this case is to use the [Quasar Flex Grid](https://quasar.dev/layout/grid/introduction-to-flexbox) like highlighted above.

**Comment by kidox** [comment]
I'm facing the same problemes here. Code working fine in Quasar v0.17 stopped working in Quasar 
Quasar v1.0.0-rc.4.

I tried what you say @rstoenescu but with no luck. Elements doesn't take fit & full-height into account.

I tried different code and different conditions and I can ensure that it its working fine in Quasar v0.17 but when moving code to Quasar v1.0 it does not work, no matter what you try. In most of the cases functionality is broken.

Here a clear example:
![image](https://user-images.githubusercontent.com/5457704/59589425-30623400-90ea-11e9-8280-e15c05e2dc04.

![image](https://user-images.githubusercontent.com/5457704/59589454-4112aa00-90ea-11e9-8174-16459e9c357e.png)

**Comment by rstoenescu** [comment]
@kidox Create a codepen and I'll show you how to do it.

**Comment by kidox** [comment]
@rstoenescu here you are: https://codepen.io/kidox/pen/MMyLXd

**Comment by rstoenescu** [comment]
@kidox https://codepen.io/rstoenescu/pen/XLdGMN

Notice:

```html
<q-page class="column justify-start">
    <div class="col column">
      <q-btn class="col" ...
```

**Comment by kidox** [comment]
Thank you @rstoenescu.

Thus I understand that since fit/full-height are responding different in Quasar v1.0 and in 0.17 it's better to play around with "col" and "column" classes, right?

**Comment by jarlos3** [comment]
@rstoenescu thank you for your suggestion!

@kidox try this:

`<q-page-container>
	<q-page class="column justify-start">
		<div class="column col absolute-full">
			<div class="col-5 column">
				<q-btn class="col" color="cyan-7" size="16px">Btn1</q-btn>
			</div>
			<div class="col-5">
				.col-5
			</div>
			<div class="col">
				.col
			</div>
		</div>
	</q-page>
</q-page-container>`

**Comment by kidox** [comment]
@jarlos3 thanks! It works flawlessly.

**Comment by JokerMartini** [comment]
thanks for this. same issue i had
