### ISSUE TITLE
QTabs internal model does not respect value prop

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#4386]
QTabs `value` prop is not respected. The internal model will update even if the `@input` event is not handled at all.

Example:
```html
    <q-tabs value="A">
      <q-tab name="A">A</q-tab>
      <q-tab name="B">B</q-tab>
    </q-tabs>
```
Navigation to tab B should be impossible, as q-tabs receives a `value` prop but the `input` event is no handled. Yet the tab still navigates to B.

Tested in [codepen](https://codepen.io/anon/pen/GboeYV) from the docs website.

Use case: conditional navigation. I'm atempting to have the user confirm navigation to another tab if the current tab has unsaved changes. I should be able to do this by handling the `input` event myself.

Possibly related PR: [4372](https://github.com/quasarframework/quasar/pull/4372)

**Comment by pdanpdan** [comment]
In next version QTabs will respect the model passed in `value` IF you also have an `@input` listener set (or if you use `v-model`, of course).

But for your example you'll only provide the initial tab value - when you click on a tab it will change. Later, if you modify the model from outside and it is different from the selected tab the new tab will be selected.

**Comment by BenoitRanque** [comment]
@pdanpdan Perfect! I'm aware my example did not have an input handler for simplicity's sake, but my actual use case is handling the input even myself, and either updating the value or not. So this should work.

**Comment by rstoenescu** [comment]
rc.5 released which has the fix.
