### ISSUE TITLE
QInput disable autocomplete (for type password)

### ISSUE THREAD

**Issue by mkomod** [quasarframework/quasar#4387]
**Issue**
Is it possible to create a prop that disables autocomplete on the QInput field, I'm making a change password form and believe it may be a security issue to have the old password autocomplete

**Describe the solution you'd like**
A prop that disables / enables browser autcomplete for input of type password 

**Describe alternatives you've considered**
Have the form clear on created for ex the following code works but does not resolve the issue directly resulting in the old password to be filled momentarily

```
  created() {
    setTimeout(() => {
      this.form.old_password = "";
    }, 0)
  }
```

**Comment by rstoenescu** [comment]
Hi,

You can use the "autocomplete" native attribute on QInput. [More info](https://duckduckgo.com/?q=input+autocomplete+off&atb=v149-1&ia=web).

**Comment by rstoenescu** [comment]
Also, https://quasar.dev/vue-components/form#Turning-off-Autocompletion

**Comment by mkomod** [comment]
thank you, I added this beforehand but wasn't seeing it take effect during local development. However all is good in production :) 

many thanks again
