### ISSUE TITLE
i18n does not allow me to change the language of the dataTable headers

### ISSUE THREAD

**Issue by clixmat** [quasarframework/quasar#4389]
Hello, when you place in the columns this. $t('name') and execute the function to change the language by means of i18n it does not have any effect, they change all the others except the columns of the dataTable.

![image](https://user-images.githubusercontent.com/41817274/59562472-ea767480-8ff2-11e9-931a-3e9a6af074d3.png)

**Comment by rstoenescu** [comment]
Make your `columns` variable computed, otherwise it's content is evaluated at component startup and Vue has no way of catching any updates.

```
computed: {
  myColumns () {
    return { name: 'customer', label: this.$t('s_customer'), .... }
  }
}

<q-table :columns="myColumns" ...
```
