### ISSUE TITLE
[v1] [ios] all devices - wild flickering in q-dialog containerized 

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#4391]
**Describe the bug**

After opening a containerized dialog on iPad or iPhone the header and footer flickers
wild during scrolling.

See:
https://vimeo.com/342568468

No codepen required, it is see-able inside / with the doc pages examples.

https://quasar.dev/vue-components/dialog#Example--With-containerized-QLayout

Also happens with the maximized param.

On Android Devices it seems not flickering.

**Comment by tegola** [comment]
Duplicate of #4127.

**Comment by ibrainventures** [comment]
a little cleanup for this old issue.
since ios 13 the flickering is away. i happens still on ios 12, but there are workarounds. 
thank you for taking attention to this ios-specific problem.
