### ISSUE TITLE
QSelect should start on selected option

### ISSUE THREAD

**Issue by yagmin** [quasarframework/quasar#4394]
When an option is selected (or pre-selected) in a default HTML dropdown, the option list opens at the location of the selection. QSelects don't do this and instead open at the top of the options list every time, which can be confusing, especially with longer options.

For example, a QSelect for U.S. states, with MA selected. The dropdown opens at the top of the options instead of directly at the selected MA. Here is a CodePen showing the issue: https://codepen.io/jyagmin/pen/PrZLLw

**Comment by Outflank-Australia** [comment]
This is indeed a problem for my application which uses QSelects to input times. If the user wants to select the next time in the list, they have to first find the position in the menu where the current selection exists. 

This functionality was present in AngularJS material (from which I am upgrading to Quasar) and even vanilla HTML selects will open where the selected option is visible. 

It seems as though this should be default behaviour, not a "feature".

**Comment by rstoenescu** [comment]
It's coming in final 1.0.0.

**Comment by rstoenescu** [comment]
Will be available in final 1.0.0.

**Comment by gcarpi** [comment]
Is it possible to disable this functionality with some property?

I'm using the example of [Dynamic Loading Options](https://quasar.dev/vue-components/select#example--dynamic-loading-options) and when I populate the select with more options the scroll is reset to the first selected.

I believe that the usability is not good for this case, so I would like to disable it.

**Comment by pdanpdan** [comment]
@gcarpi 
Can you please open an issue for this - it's hard to track it in this old closed one?

**Comment by gcarpi** [comment]
@pdanpdan Opened

https://github.com/quasarframework/quasar/issues/13694

**Comment by DouglasCalora** [comment]
@pdanpdan the issue was created!
