### ISSUE TITLE
QBtn unable to open in a new tab

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4395]
Hello!

This is quite common scenario when you would want to use QButton as a link (`to`). When using `target="_blank"` attr, it is added to the DOM correctly, although does not seem to work.

Example:
https://codepen.io/anon/pen/QXNxLm
1) Click on a router-link -> Opened in a new tab 👍 
2) Click on a button -> Does not open in a new tab 👎 

Thanks!

**Comment by pdanpdan** [comment]
You can try setting `type="a"` on QBtn.

**Comment by jean-moldovan** [comment]
I'm sorry I missed the section in the docs: https://quasar.dev/vue-components/button#More-options.

Thanks for you help!

**Comment by rodrigoklim** [comment]
<q-btn
  @click="openURL(url)
/>

</script>
import { openURL } from 'quasar'

...
methods: {
openURL
}

**Comment by zunnzunn** [comment]
> <q-btn @click="openURL(url) />
> </script> import { openURL } from 'quasar'
> 
> ... methods: { openURL }

In my case, the QBtn was nested within a QInput's `prepend` slot. Neither the `type` nor the `href` or `target` props helped, but this elegant `openURL` util function did!
