### ISSUE TITLE
Unexpected return to the line with suffix on q-input

### ISSUE THREAD

**Issue by FlorentinGremy** [quasarframework/quasar#4396]
Hi,
I recently upgrade from V0.17 to V1.
Since V1 my q-input suffix return to the line when using a space.
When i was using V0.17 this doesn’t happend.

Here is an example :
![q-input_suffix_spaces](https://user-images.githubusercontent.com/22290080/59586657-b4fd8400-90e3-11e9-97e5-98744f14b628.PNG)

Here is a [Codepen](https://codepen.io/FGremy/pen/MdMWBe) showing it.

Thanks.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in rc.5

**Comment by cashmisa** [comment]
Hi has this issue been resolved? I have upgraded to 1.0.0-rc.5 but still having this problem... Thanks!

![image](https://user-images.githubusercontent.com/26920266/60776838-7b0f2300-a161-11e9-943f-cb6a5a442f0e.png)


> Thanks for reporting!
> Fix will be available in rc.5
