### ISSUE TITLE
Unable to start electron    Missing .babelrc file...

### ISSUE THREAD

**Issue by afx919** [quasarframework/quasar#4398]
step:
1. quasar init test
2. cd test
3.  quasar mode -a electron
4. quasar dev -m electron

**Describe the bug**
⚠️  Missing .babelrc file...

![log](https://user-images.githubusercontent.com/32212573/59592507-c44ff200-9122-11e9-88b2-7f46bdb7a67a.jpg)

**Platform (please complete the following information):**
OS: win32
Node:v10.15.3
NPM:6.4.1
Yarn:1.16.0
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

v1 has officially become "latest", so in order for you to scaffold a 0.17 project, you have two options:

1. (Not recommended) Keep the old cli (`quasar-cli`) and hit `quasar init <folder> -v 0.17`
2. (**Recommended**) Globally remove `quasar-cli` package and replace it with `@quasar/cli`.
Then hit `quasar create <folder> --branch 0.17` (for 0.17 projects), or simply `quasar create <folder>` for v1.0 projects.
