### ISSUE TITLE
change primary styles

### ISSUE THREAD

**Issue by Lee182** [quasarframework/quasar#440]
so i ran these commands 
```bash
$ npm install -g quasar-cli
$ quasar dev
```

i then changed the title in `/src/components/Index.vue` and that live reloaded,
i then changed the color `$primary = #6e3124` in `/src/themes/app.variables.stylus`, color change did not live reload and then after quiting the dev server, to run `quasar build`, changes did not build.

no error from the cli was given.

**Comment by rstoenescu** [comment]
Enable custom theme. Check head of src/main.js

**Comment by Lee182** [comment]
cheers should have just read the head of the `app.varibles.stylus`
