### ISSUE TITLE
QInput: explicit aria-label not rendered

### ISSUE THREAD

**Issue by rmehner** [quasarframework/quasar#4401]
**Describe the bug**

```vue
<q-input aria-label="label" />
```

used to render the aria-label attribute on the wrapping div. Since Beta 19 it stopped doing that. Works on Beta 18 and before.

**Codepen/jsFiddle (required)**
https://jsfiddle.net/a0153kjd/1/

**To Reproduce**

1. Go to https://jsfiddle.net/a0153kjd/1/
2. See Aria label found: true
3. Change script tag in editor to include beta 19
4. See Aria label found: false

**Expected behavior**

It should still render the aria label attribute.

**Additional context**

I've looked through the changes from [18 to 19](https://github.com/quasarframework/quasar/compare/quasar-v1.0.0-beta.18...quasar-v1.0.0-beta.19) and if I'm seeing correctly, I suspect this change https://github.com/quasarframework/quasar/commit/86a307ccb1b60c885166c2be3d410ddf64b9a211 to be the culprit as it removes the passing of `attrs`, but I'm not certain :)

I couldn't find any docs on how to set up a local dev environment or tests, so I couldn't open a PR directly, but with a bit more time, I might be able to set something up. If anyone has some pointers, it would be much appreciated :) Thanks all around!

**Comment by rstoenescu** [comment]
Thanks for reporting!

By default, the "label" is used as aria-label, but it was wrongly set to overwrite an explicit "aria-label". Fix will be available in rc.5.
