### ISSUE TITLE
[Feature Request] Datetime Input/picker

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4405]
When the QInput's type prop is set to 'date' or 'time', it's better to show QDate or QTime.
And a better solution is add a option to the 'type' prop: 'datetime'. When the input is clicked/tapped, first show QDate, **and then** show QTime (not simultaneously).
Thanks.

**Comment by rstoenescu** [comment]
Hi,

QInput's "type" prop is handled natively by the browser (as indicated in docs) and outside of Quasar's reach. [More info](https://quasar.dev/quasar-cli/cli-documentation/handling-process-env#Import-based-on-process.env).

If however, you are talking about the prepend/append slots where you may add a QDate/QTime, so [this example](https://quasar.dev/vue-components/date#With-QInput), then those are totally under your control for your custom use cases (use `v-if` on them).

**Comment by bigradish** [comment]
@rstoenescu Thank you so much. You do a great job. :)
