### ISSUE TITLE
QSelect based chips input should support separation by space for model mutation

### ISSUE THREAD

**Issue by Abroxa** [quasarframework/quasar#4410]
When using a QSelect based chips input, e.g., for letting a user add tags to something, I would like to use the space bar for directly separating the entered tags. Currently, the Enter key is the only way to push to the current list since it is hardcoded in QSelect.

I suggest a simple boolean prop 'space-separation' (or something more meaningful than that) which is valid only if use-input (and eventually also use-chips?) is turned on. This way, pressing the space bar during input would automatically create a an input (and chip) and mutate the list.

An alternative would be to specify the exact key that can be used for model mutation (push), but I think that it would be too generic and normal letter keys wouldn't make much sense.

**Comment by stgunholy** [comment]
Comma can make sense as well

**Comment by pdanpdan** [comment]
In v 1.1.1 you'll be able to hook into `@keydown`, `@keyup` and `@keypress` events of the text field in QSelect, so you can trigger the required actions on whatever key you want.

**Comment by gaby64** [comment]
is this actual?
