### ISSUE TITLE
[v1 - QSelect] - filterFn is called when the user select an item on mobile

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#4412]
On mobile only, when the user pick an element from the  `QSelect`, the filterFn is triggered.
Note that this occured only when the props `fill-input` is `true`

**Codepen/jsFiddle (required)**
https://codepen.io/daedalusdev/pen/EBgZEg

**To Reproduce**
1. Go to https://codepen.io/daedalusdev/pen/EBgZEg
2. Toggle the navigator into device mode (make sure to initialize the app in device mode to use the mobile mode)
3. Type "Goo" and select "Google"
4. The console will show "filterFn Goo" and then on select "filterFn Google"

**Expected behavior**
In my case, the filterFn call and Ajax fn to an API. So i would like to save some http request.

**Platform (please complete the following information):**
Chrome

**Comment by rstoenescu** [comment]
Fix will be available in final 1.0.0
