### ISSUE TITLE
What does this all:true mean in quasar\docs\quasar.conf.js ?

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#4413]
``` 
   framework: {
      all: true,

      config: {
        loadingBar: {
          color: 'amber'
        }
      }
    },
```
What does this all:true mean in quasar\docs\quasar.conf.js .There is no document about this option

**Comment by hugetiny** [comment]
If it means to include everything, will it package everything to production when i use quasar build

**Comment by rstoenescu** [comment]
Hi,

It means that it will add all Quasar components, directives and Quasar plugins. And yes, this means that it will include all those in the production build.
