### ISSUE TITLE
The use of QInfiniteScroll's methods is inconvenient

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4415]
For example, when no more data can be loaded, the 'stop' method should be called, this requires first getting the QInfiniteScroll's instance in 'load' event handler.
I think a better solution is adding a parameter to 'done' callback of the load event handler to indicate whether there are more data.
Thanks.

**Comment by rstoenescu** [comment]
Thanks for this ticket.
Will be available in final 1.0.0 (next version). Calling `done(true)` will also stop QInfiniteScroll.

**Comment by bigradish** [comment]
@rstoenescu Thank you very much.
Would you add an option that shows a text to let users know "no more data" to improve user experience?

**Comment by rstoenescu** [comment]
@bigradish That would be the dev's responsibility, and it's quite easy to do. From Quasar's perspective, I cannot assume that stopping QInfiniteScroll means only "there's no more data".

**Comment by bigradish** [comment]
@rstoenescu Thank you for your response.
I mean adding an option (e.g., via slot or prop), and developers can decide whether to use the option.
