### ISSUE TITLE
[v1] QInput Number - Bug with increment/decrement arrows

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#4416]
**Describe the bug**
The value of the QInput starts automatically incrementing/decrementing really fast by just hovering over the arrows with the mouse.

**Codepen/jsFiddle (required)**
https://codepen.io/anon/pen/VJKgZO?editors=1010

**To Reproduce**
1. Set a validation rule for minimum and/or maximum value on a QInput of type "number".
2. Trigger the validation rule by clicking at least twice in quick succession on one of the increment/decrement arrows.
3. Triggering the validation rule results in an error icon appearing and displacing the increment/decrement arrows to the left.
3. Hover over the same arrow that was clicked in step 2 with the mouse
4. The value starts incrementing/decrementing by itself automatically.

**Expected behavior**
This behavior should not happen obviously.

**Platform (please complete the following information):**
OS: Linux
Browsers: Chrome, Opera
I could not reproduce this in Firefox.

**Additional context**
If the QInput is allowed to grow, then the error icon will extend the field to the right and this bug will not happen.

In any case I would like to suggest that any toggle-able icons appear on the left, rather than on the right, of the increment/decrement arrows. This behavior would match how the QSelect works and also any of the examples where custom icons are appended to the field (Password and DatePicker QInputs).

**Comment by pdanpdan** [comment]
The increment/decrement arrows are native to the browser control and use it's implementation - that means we cannot put the icons between the text and the buttons.
It looks like it's a browser error specific to Chrome engine on Linux, because I cannot reproduce it on Windows (Chrome 77.0.3824.6).

**Comment by MartinManev** [comment]
I ran some tests on Windows 10 and I could not reproduce it in Chrome or Firefox. Edge does not show increment/decrement arrows at all. IE11 is not supported by codepen. But I did manage to reproduce it on Opera.

**Comment by MartinManev** [comment]
> The increment/decrement arrows are native to the browser control and use it's implementation - that means we cannot put the icons between the text and the buttons.

Are there any plans to add custom controls instead of using the native ones?

**Comment by rstoenescu** [comment]
@MartinManev
Hi,

Like we wrote on the [docs](https://quasar.dev/vue-components/input#Input-types), the "Support and behavior is the subject entirely of the browser rendering the page and not Quasar’s core code" when you specify the `type` prop.

If you want something specific, why not use the `prepend` and `append` slots to add buttons of your own. You can even use the [TouchRepeat](https://quasar.dev/vue-directives/touch-repeat) directive to enhance the functionality.
