### ISSUE TITLE
[v1] failed on Electron v5 dev mod  

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar#4417]
**Describe the bug**

```
>> quasar dev -m electron

 app:electron Booting up Electron process... +11ms
 app:spawn Running "/myprg/node_modules/electron/dist/electron --inspect=5858 /myprg/.quasar/electron/electron-main.js" +2ms

[13553:0619/164714.793697:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /myprg/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.


 app:electron Electron process was killed. Exiting... +0ms
```

**Platform (please complete the following information):**
OS: 
NPM - 6.9.0
yarn - 1.16.0
@quasar/cli - 1.0.0-rc.2
quasar - 1.0.0-rc.4
@quasar/app - 1.0.0-rc.6
@quasar/extras - 1.1.2
Electron: electron - **5.0.4**

**Additional context**
I solved this problem by modifying this file.

```
@quasar/app/lib/electron/index.js

 __startElectron () {
    log(`Booting up Electron process...`)
    this.pid = spawn(
      require(appPaths.resolve.app('node_modules/electron')),
      [
        '--inspect=5858',
        appPaths.resolve.app('.quasar/electron/electron-main.js')
      ],

to

 __startElectron () {
    log(`Booting up Electron process...`)
    this.pid = spawn(
      require(appPaths.resolve.app('node_modules/electron')),
      [
        '--inspect=5858',
        '--no-sandbox',
	'--disable-setuid-sandbox',
        appPaths.resolve.app('.quasar/electron/electron-main.js')
      ],

```

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting and even suggesting a fix.

I think the proper way is to not change anything in `@quasar/app` but rather overcome the breaking change in Electron 5 regarding the instantiation of the BrowserWindow:

```
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    useContentSize: true,
    webPreferences: { // <<<<<<<
      nodeIntegration: true // <<<<<<<
    }
  })
```

Will investigate further and update the docs.

**Comment by rstoenescu** [comment]
Yes, we'll go the path above. Simply add the webPreferences: nodeIntegration.

**Comment by pinghe** [comment]
This path cannot fix this bug.

```
20471:0620/110504.116022:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /myprj/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by rstoenescu** [comment]
@pinghe Hi, I've tested it extensively. Maybe I missed something?
Can you check this thread on Electron repo pls? https://github.com/electron/electron/issues/17972 Some are saying that the --no-sandbox is a hack. I tend to agree, since it's also a security issue if you disable sandbox.

I'll keep on researching and I think that the best way is for Quasar to allow passing custom params also, in case something like this is temporarily needed.

**Comment by vladimiry** [comment]
Just setting `nodeIntegration: true` won't solve the issue. 

> the --no-sandbox is a hack

It's a hack. But in the same issue you referenced also listed better workarounds that allow keeping sandbox enabled.

**Comment by rstoenescu** [comment]
In final 1.0.0 of `@quasar/app`, passing extra parameters to the underlying "electron" (and also "cordova") executable will be possible. Example:

```bash
# passing extra parameters and/or options to
# underlying "cordova" or "electron" executables:
$ quasar dev -m ios -- some params --and options --here
$ quasar dev -m electron -- --no-sandbox --disable-setuid-sandbox
```
