### ISSUE TITLE
Datatable template slot not working

### ISSUE THREAD

**Issue by ahmetorhans** [quasarframework/quasar#4418]
Hi,
i use quasar as standalone/umd (v1.0.0-rc.5)
Custom header not showing in the q-table.  

`
<q-table title="cari" :filter="filter" :pagination.sync="pagination" :data="dataSourceCari" :columns="cariCols" row-key="id">
                    <template v-slot:top>
                        <q-btn flat dense color="primary" :disable="loading" label="Add row" @click="addRow" />
                    </template>

                    <q-tr slot="body" slot-scope="props" :props="props" @click.native="rowClick(props.row)" class="cursor-pointer dtHeight">
                        <q-td v-for="col in props.cols" :key="col.name" :props="props">
                            {{col.value}}
                        </q-td>
                        <q-td>
                            asd
                        </q-td>

                    </q-tr>
                </q-table>
`

**Comment by rstoenescu** [comment]
Hi,

Use the new Vue syntax for slots. `<template v-slot:body="props" ...`

**Comment by ahmetorhans** [comment]
Hi,
tried with new code but did not

New code
```
<q-table title="cari" :filter="filter" :pagination.sync="pagination" :data="dataSourceCari" :columns="cariCols" row-key="id">
                    <template v-slot:top-right>
                        <q-input borderless dense debounce="300" v-model="filter" placeholder="Search">
                            <template v-slot:append>
                                <q-icon name="search" />
                            </template>
                        </q-input>
                    </template>

                </q-table>```

**Comment by pdanpdan** [comment]
What doesn't work for you?
Here is an example: https://codepen.io/anon/pen/wLowWo?editors=1010

**Comment by ahmetorhans** [comment]
i found the problem.
i use two vue instance.
if i use pre tag, v-slot not showing.
```
<div id="app" v-pre>
             @yield('content')
    </div>
...
new Vue({
  el : '#app',
..
