### ISSUE TITLE
QInput: aria-label rendered on different element than in betas

### ISSUE THREAD

**Issue by rmehner** [quasarframework/quasar#4419]
**Describe the bug**

This is a continuation of #4401 (thanks for the very quick fix btw.)

Before, the aria label was rendered on the wrapping div, now it's rendered directly on the input.

To be honest, that sounds absolutely reasonable for me, just want to make sure that this doesn't fall through the cracks, as we have some tests that rely on it and I want to know what the correct way going forward is :)

Are you planning to change this or keep as is, that is: keep the aria-label on the input itself?

Thanks again!

**Codepen/jsFiddle (required)**

https://jsfiddle.net/au0qmyhc

**To Reproduce**

1. Go to https://jsfiddle.net/au0qmyhc/
2. See Aria label found: false
3. Change script tag in editor to include beta 18
4. See Aria label found: true

**Comment by rstoenescu** [comment]
Hi,

Yes. I can confirm that this is the behaviour that we want.
