### ISSUE TITLE
slot not working in the component

### ISSUE THREAD

**Issue by ahmetorhans** [quasarframework/quasar#4426]
**slot not working in the component**

if import component in the template, slot not showing. when i use slot without component then work.

```
...
 <component-a></component-a>
...
import ComponentA from "./App.vue";

new Vue({
  el : '#qapp',
  components: {
    'component-a': ComponentA,
  },
  data: function () {
    return {
      lefMenu:false,
    }  },
  })
--from .App.vue
<q-table  title="asd" :filter="filter" :pagination.sync="pagination" :data="dataSourceCari" :columns="cariCols" row-key="id">
                    <template  v-slot:top-right>
                        <q-input borderless dense debounce="300" v-model="filter" placeholder="Search">
                            <template v-slot:append>
                                <q-icon name="search" />
                            </template>
                        </q-input>
                    </template>

                </q-table>
`

**Comment by rstoenescu** [comment]
Hi,

I assure you this is working flawlessly (see docs, see docs codepens), so it must be some misunderstand on your part. I'd suggest you ask about it on our [Discord](https://chat.quasar.dev) server.

I do not understand what you are trying to say by "when i use slot without component then it works". If you're not using the component then what works? Slots are bound to components :)
