### ISSUE TITLE
Autocomplete display issue in Chrome

### ISSUE THREAD

**Issue by fajaryanw** [quasarframework/quasar#443]
I try autocomplete component from source https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/form/autocomplete.vue with some change. 

I got problem with the position of `q-popover` that generated by `q-autocomplete`. 
After inspect the DOM, I found :

**Chrome**
inline style the left property value 0px
``` html
<div class="q-popover animate-scale" style="transform-origin: left top 0px; max-height: 65vh; top: 44px; left: 0px;">
```
**Firefox**
the left property value 12px
``` html
<div class="q-popover animate-scale" style="transform-origin: left top 0px; max-height: 65vh; top: 44px; left: 12px;">
```
## Issue
This display issue happens only in **Chrome** desktop

![quasar](https://cloud.githubusercontent.com/assets/6999559/23594832/b8330098-024f-11e7-9008-7aec2749fdd2.png)
in **Firefox** desktop display properly

![quasar2](https://cloud.githubusercontent.com/assets/6999559/23594865/01143aa2-0250-11e7-8354-7908c2c0fa01.png)
**Default Browser** and **Chrome** In my **Android** Phone display properly too.
## Reproduce Issue

1. In terminal do `quasar init <folder name>`
2. edit file in _\<folder name\>/package.json_, change dependencies quasar-framework with edge version
``` json
...
"quasar-framework": "git+https://git@github.com/quasarframework/quasar-edge.git"
...
```
3. do `npm install`
3. In your _\<folder name\>_ Add this [file](https://raw.githubusercontent.com/quasarframework/quasar/dev/dev/data/autocomplete.json) in  _/data/autocomplete.json_
4. Edit file in below

- **src/components/Index.vue**

``` vue
<template>
  <q-layout>
    <div slot="header" class="toolbar primary">

      <q-autocomplete v-model="terms" @search="search" @selected="selected" :delay="0" :max-results="20" class="full-width">
        <q-search v-model="terms" placeholder="Start typing a country name" />
      </q-autocomplete>

    </div>
  </q-layout>
</template>

<script>
import { Utils, Toast } from 'quasar'
import countries from 'data/autocomplete.json'
const icons = ['alarm', 'email', 'search', 'build', 'card_giftcard', 'perm_identity', 'receipt', 'schedule', 'speaker_phone', 'archive', 'weekend', 'battery_charging_full']

function getRandomIcon () {
  return icons[Math.floor(Math.random() * icons.length)]
}
function getRandomStamp () {
  if (Math.floor(Math.random() * 50) % 3 === 0) {
    return `${Math.floor(Math.random() * 10)} min`
  }
}
function getRandomSecondLabel () {
  if (Math.floor(Math.random() * 50) % 4 === 0) {
    return `UID: ${Utils.uid().substring(0, 8)}`
  }
}
function parseCountries () {
  return countries.map(country => {
    return {
      label: country,
      secondLabel: getRandomSecondLabel(),
      icon: getRandomIcon(),
      stamp: getRandomStamp(),
      value: country
    }
  })
}

export default {
  data () {
    return {
      terms: '',
      countries: parseCountries()
    }
  },
  methods: {
    search (terms, done) {
      setTimeout(() => {
        done(Utils.filter(terms, {field: 'value', list: parseCountries()}))
      }, 500)
    },
    selected (item) {
      Toast.create(`Selected suggestion "${item.label}"`)
    }
  }
}
</script>
```

### P.S.
**Ubuntu** 16.04.2 (64-bit)
**Chrome** 56.0.2924.87 (64-bit)
**Firefox** 51.0.1 (64-bit)
**Quasar Framework** 0.13.2
**Quasar CLI** 0.5.2

**Comment by rstoenescu** [comment]
Should be fixed in future v0.14
