### ISSUE TITLE
Notify plugin width incorrect on IE

### ISSUE THREAD

**Issue by outofmemoryagain** [quasarframework/quasar#4430]
I'm seeing a pretty odd issue in IE and Notify.  In debug everything looks fine, but after deploying a production build, a css class style style value for width: 0% is changed to width: 0px.  It causes the value notification div to wrap much early than otherwise. 

I tried to work around the issue my overriding to class value and setting the width myself, but the same thing happens to my class.  The value of width is changed from "0%" to "0px"

**To Reproduce**
I would provide a targeted codepen, but the site understandably doesn't work in IE.  

1. Go to the docs site example https://quasar.dev/quasar-plugins/notify#Positioning
2. Click one of the bottom or top positioning example buttons until you get the "Lorem ipsum" notification.  
3. In IE it wraps b/c the width is pretty narrow despite a wide screen size, in any other browser it doesn't wrap at all on the desktop.

**Expected behavior**
The notification does not wrap unless the screen size forces it to, which is consistent with other browsers.

**Screenshots**
IE
![image](https://user-images.githubusercontent.com/16638153/59867273-6a823e80-9353-11e9-807a-4fc81953723b.png)

Chrome
![image](https://user-images.githubusercontent.com/16638153/59867417-c2b94080-9353-11e9-802e-c69bc9c29628.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: 10.16.0
NPM: 6.9.0
Yarn: 1.13.0
Browsers: IE 11

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in final 1.0.0 (needs update of both `quasar` and `@quasar/app` package to this version).
