### ISSUE TITLE
Spacing behaving unexpectedly on QInput bottom-slot

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#4433]
**Describe the bug**
The bottom-slot spacing on QInput is not sensitive to the content it contains.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/whoacowboy/pen/NZdLQP

**To Reproduce**
The codepen shows it

**Expected behavior**
The space would flex depending on the content of the bottom-slot.

**Additional context**
That's it.

**Comment by rstoenescu** [comment]
Hi,

Use `hide-bottom-space` prop.
