### ISSUE TITLE
Quasar build could allow custom dist path

### ISSUE THREAD

**Issue by saulmmendoza** [quasarframework/quasar#4434]
Context: I'm unning/deploying quasar with the nodejs heroku example ([link](https://v0-17.quasar-framework.org/guide/app-deploying-spa.html#Deploying-with-Heroku)) inside a **Docker** container with a **docker volume** connected to the `dist` path (some weird reasons because we have a docker volume for a static site, this is not the ideal scenario)

**Is your feature request related to a problem? Please describe.**
- We get a downtime of 1-4~ minutes everytime someone makes a commit and the CI/CD runs a `quasar build`, so I did cocaine like Sherlock Holmes to dive deep into the abyss:
- The dist path is currently mapped to a Docker volume so we need to run `quasar build` after building the image to update the volume files (or after `docker-compose up` or `docker run`)
- but while the command its running we get an `ENOENT error not file found` or something like that because it runs `quasar clean` automatically
- I spent hours working about what makes the downtime until I read this line from `quasar build` 😆 
`app:artifacts Cleaned build artifact: "/path/to/dist/spa-mat" +3ms`

**Describe the solution you'd like**
A simple solution would be to add a parameter to `quasar build` to specify another path instead of `dist`, so I can make a `quasar build dist-updated` and then move the new files to `dist`

**Describe alternatives you've considered**
I think that splitting quasar build and quasar clean would solve the problem for me but for other people may bring problems I dont know

**Additional context**
- Everything runs on Docker containers using Docker Compose
- Dist files have a docker volume :/

**Comment by rstoenescu** [comment]
Hi,

I think that you are looking at this the wrong way. Let Quasar build your project, and when it's done, copy the distributables to the folder which is used for the running server. There is no need to serve directly from the folder that Quasar builds to.
