### ISSUE TITLE
q-icon does not display icon when use font-family

### ISSUE THREAD

**Issue by florensiuslaylim** [quasarframework/quasar#4437]
**Describe problems**
I was use q-icon but does not display icon. 

**Little Background**
I created navbar and sidebar and i put some icons at them. But when i was run my project, it does not display the icons. 

**What i've tried**
I removed and followed my codes with the documentation in my template. But it still does not display the icons. I removed my script and style one by one and i got the reason why my icons does not diplay. I was realized it when i remove my font-family and my icons appear in my screen.    

Am i got wrong in my app.styl codes?
This is my codes :

**app.styl**
![app styl2](https://user-images.githubusercontent.com/37322368/59908864-92979d80-9438-11e9-94ec-337bce00277e.png)

**my font-family location**
![myPath2](https://user-images.githubusercontent.com/37322368/59908724-43516d00-9438-11e9-912e-92d4007c981a.png)

**style in my vue**
![style](https://user-images.githubusercontent.com/37322368/59908501-c2927100-9437-11e9-9489-058c8ea1a990.png)

**Comment by yusufkandemir** [comment]
`q-icon` uses web fonts to display icons. As you are overriding it by `* { font-family: 'Latto'; }`, it will not display as pleased.

If you want to use Latto font as the main font across your application, please refer to [documentation for stylus variables](https://quasar.dev/style/stylus-variables#Variables-list). You can add `$typography-font-family  ?= 'Lato', '-apple-system', 'Helvetica Neue', Helvetica, Arial, sans-serif` to your `src/css/quasar.variables.styl` file if you want to achieve that.

**Comment by florensiuslaylim** [comment]
okey, i see. Thank you so much for your help @yusufkandemir

**Comment by rstoenescu** [comment]
Thanks for supplying the information, @yusufkandemir . Much appreciate it.
