### ISSUE TITLE
QTable - Choosing the progress bar color in loading state

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#4438]
**Is your feature request related to a problem? Please describe.**
When QTable is in loading state, the progress bar color seem to be hard-coded to `text-grey-8`. It is particularly problematic for "dark" mode (it is grey on grey, the progress bar is barely visible).

**Describe the solution you'd like**
Provide a property to change that color

**Describe alternatives you've considered**

**Additional context**

**Comment by smolinari** [comment]
@philfontaine - Try using the `color` prop. It should change the loading bar color too. Let us know if that does what you expect.

Scott

**Comment by philfontaine** [comment]
Yes it does. Sorry, I assumed color would change the table color, which is not what I wanted.

Thank you.
