### ISSUE TITLE
[v1]QEditor - Cannot read property 'isCollapsed' of undefined

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#4439]
**Describe the bug**
When the editor content is empty, an error occurs when you click the link button.
TypeError: Cannot read property 'isCollapsed' of undefined

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/qq34205037/pen/OepbKX?editors=1010

**To Reproduce**
1. Click on 'link'

**Platform (please complete the following information):**
OS: macOS Mojave 10.14.5
Node: v8.11.1
NPM: 6.9.0
Yarn: 1.16.0
Browsers: Chrome 75.0.3770.100

**Comment by rstoenescu** [comment]
This should already be in latest published version of Quasar.
Should have closed this.

@QQ34205037 please feel free to reopen if the bug persists. thank you!
