### ISSUE TITLE
Cordova.js Uncaught Error: cordova already defined

### ISSUE THREAD

**Issue by billouboq** [quasarframework/quasar#444]
Hi, 

is cordova imported somewhere in this framework?

I'm using the basic quasar project, but when I'm launching the app in an android device I have this error 

> cordova already defined

And in my index.html I can see that cordova.js is defined twice

<img width="658" alt="screen shot 2017-03-06 at 12 20 54 pm" src="https://cloud.githubusercontent.com/assets/7765196/23607976/69475462-0267-11e7-9d57-4c59bc12b770.png">

My index.html before building it with webpack : 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">

    <title>Quasar App</title>
    <link rel="shortcut icon" type="image/x-icon" href="statics/favicon.ico">

  </head>
  <body>
    <div id="q-app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>
```

**Comment by rstoenescu** [comment]
Can't reproduce this. Also seems like something that can't happen by looking at code...
Quasar takes care of many things, including adding cordova lib if running under Cordova environment.. but only once.

Please tell me the exact steps that you followed, your OS, NPM and Node versions. Did you change anything in the folder created by CLI? Thanks.

**Comment by billouboq** [comment]
Thanks for being that responsive, I think I changed something so problem is on my side.

Can you explain what is "quasar wrap cordova" doing?
Do I have to use it each time I want to test my app in a device?

**Comment by rstoenescu** [comment]
It uses cordova CLI to create the `/cordova` folder and Quasar CLI maps it to your app. You only use that once. Then you can issue cordova commands from within the `/cordova` folder, like `cordova run`, `cordova platforma add android` etc.

Please make another test but this time don't change any line of code. Generate project folder, make a build, wrap with cordova, run on a device/emulator. If problem persists, please reopen. Thanks!
