### ISSUE TITLE
[Feature request] We still need a Quasar-play like example to get familiar with quasar layouts and components

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#4440]
We still need a quasar-play-like example to get familiar with quasar layouts and components.
I hope quasar-play repository could continue

**Comment by Dmitrij-Polyanin** [comment]
Yes. And some multy files templates to get started and to show/test/share code.

**Comment by nothingismagick** [comment]
Have you seen this?

https://quasar.dev/start/playground#Codesandbox-Template

**Comment by rstoenescu** [comment]
A "Layout Gallery" page (mimicking some well known layouts like Whatsapp, Youtube, ... with source code available) will be released tomorrow along with the final 1.0.0 build.

We'll do everything possible considering current resources available.
