### ISSUE TITLE
'class' for custom buttons in q-editor's toolbar

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#4442]
Add prop 'class' to custom button in q-editor's toolbar. This will allow flexible formatting like coloring 'Cancel' and 'Upload'.

Also 'disabled' prop would be nice as well. The above commands would only work when some changes were made.

**Comment by rstoenescu** [comment]
Hi,

This is what slots are for... for total customization.
Check out: https://quasar.dev/vue-components/editor#Example--Using-toolbar-slots

**Comment by rstoenescu** [comment]
Also, take a look at: https://codepen.io/rstoenescu/pen/JQNWGd?&editable=true&editors=101

**Comment by Nice2Work** [comment]
The code pen link does not work anymore (404). I like the ideas I am seeing. But a more simple example would be appreciated. 

Right now the insert comes with a button, to cancel out the insert, which is great, but a simpler HTML insert would be nicer, it is easier to build from the bottom, then 'undress' from the top.
