### ISSUE TITLE
q-badge can't bind event when floating

### ISSUE THREAD

**Issue by green-mike** [quasarframework/quasar#4444]
**Describe the bug**
q-badge can't add event when floating

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/greenmike/pen/OemgxR

**To Reproduce**
1. click the first badge, the notify does not trigger
2. Click the second badge, the notify trigger

**Expected behavior**
click events have been trigger both. I try the mouseover that can't work too.

**Platform (please complete the following information):**
Browsers: Codepen

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.0

**Comment by nothingismagick** [comment]
In the meantime you can also position it yourself:
https://codepen.io/nothingismagick/pen/MMmvPg

>

**Comment by green-mike** [comment]
I learn it! great :)  Thanks for your help.
