### ISSUE TITLE
QInfiniteScroll emits load event continually when used with QPullToRefresh

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4446]
The code is as follows:

```
<template>
  <div class="q-pa-md scroll">
    <q-pull-to-refresh @refresh="refresh">
			<q-infinite-scroll @load="onLoad" :offset="250">
      <div v-for="(item, index) in items" :key="index" class="q-mb-sm">
        <q-badge color="secondary">
          {{ items.length - index }}
        </q-badge>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      </div>
			</q-infinite-scroll>
    </q-pull-to-refresh>
  </div>
</template>

<script>
export default {
  data () {
    return {
      items: [{}, {}, {}, {}, {}, {}, {}, {}, {}]
    }
  },

  methods: {
    refresh (done) {
      setTimeout(() => {
        this.items.push({}, {}, {}, {}, {}, {}, {})
        done()
      }, 1000)
    },
		
		onLoad (index, done) {
      setTimeout(() => {
        if (this.items) {
          this.items.push({}, {}, {}, {}, {}, {}, {})
          done()
        }
      }, 2000)
    },
  }
}
</script>

<style>
</style>
```

**Comment by pdanpdan** [comment]
You have to tell `QInfiniteScroll` where to look for the scroll container.

See a working example here: https://codepen.io/anon/pen/JQyydz?editors=1010

**Comment by bigradish** [comment]
@pdanpdan Thanks for your response.
In your example code, if change `:scroll-target="windowRef"` to `:scroll-target="$refs.scrollTarget"`, the load event is still emitted continually.

**Comment by pdanpdan** [comment]
That's normal. If you want to use ref.scrollTarget then add a CSS maxHeight or height to it.

**Comment by bigradish** [comment]
@pdanpdan Thank you.
I already added CSS:
```
.scroll {
	max-height: 100%;
	overflow: auto;
}
```
You can have a try.

**Comment by pdanpdan** [comment]
Set a height :) 100% will keep increasing. You just make the scroll container scroll, else you just keep adding lines to it and it's extending.

**Comment by bigradish** [comment]
@pdanpdan Thank you.
Could you give me the CSS code? Thanks again.

**Comment by pdanpdan** [comment]
:D I hope it is a joke (`height: 100px;`).
https://codepen.io/anon/pen/OejYaB?editors=1010

**Comment by bigradish** [comment]
@pdanpdan Suppose this situation:
A page has a toolbar and a bottom navigation, and in the middle has a list ocuppying the whole remaining space. The list needs the "pull to refresh" and "infinite scrolling" functions. The page needs to be responsive on mobile, desktop, pad, etc. How to set the scroll target height for the list?
Thank you very much.

**Comment by pdanpdan** [comment]
Make a codepen example.
