### ISSUE TITLE
QInput - property "upper-case" is missing

### ISSUE THREAD

**Issue by 549393092** [quasarframework/quasar#4448]
Please see below link, thanks!
https://forum.quasar-framework.org/topic/3834/v1-qinput-property-upper-case-is-missing

**Comment by pdanpdan** [comment]
Just implement it yourself.

```html
<q-input :value="model" @input="m => { model = typeof m === 'string' ? m.toUpperCase() : m }" class="text-uppercase" />
```

**Comment by 549393092** [comment]
so could you please add this feature to the future request, then I can wait for the next release.

**Comment by pdanpdan** [comment]
Why don't you implement it in your code? It makes no sense to be at the library level - you might want uppercase, lowercase, titlecase, propercase, and the same code should go in the library even if it's not going to be used.
