### ISSUE TITLE
Floating label text and label not on input line`

### ISSUE THREAD

**Issue by genyded** [quasarframework/quasar#445]
I have a simple template:

```html
<template>
  <div class="layout-padding">
    <h2>Create Account<h2>
      <div class="floating-label">
        <input required class="full-width" type="text">
        <label>First/Given Name</label>
      </div>
      <div class="floating-label">
        <input required class="full-width" type="text">
        <label>Last/Family/Surname</label>
      </div>
  </div>
</template>
```

...but if you look below you can see both the label and text are quite a bit above the line for the input:

![quasar](https://cloud.githubusercontent.com/assets/3081676/23617381/95c9b8a0-0252-11e7-8d9c-7a74f38f2245.png)

Any idea why? The css has not been altered at all.

**Comment by rstoenescu** [comment]
Hi, this is obsolete now as future v0.14 has a redesign for forms, including input textbox (through a new q-input component). I believe it's better to focus on the new version to release it as soon as possible rather than spend time on this.

**Comment by genyded** [comment]
Cool - when is 14 expected to be released? Is it usable now?

**Comment by rstoenescu** [comment]
Not usable yet. Lots of work still needs to be done (outside of the form components). Don't have an exact release date. Working to release asap.
