### ISSUE TITLE
QTable exit fullscreen after querystring changed

### ISSUE THREAD

**Issue by luozhihua** [quasarframework/quasar#4452]
**Describe the bug**
I using QTable with server side pagination & sort, so I save pagination & search parameters in $router.query, so the Issue is when I call `$router.push({ query: {...} })`, QTable is exit fullscreen mode automatically, I found `exitFullscreen()` is called in [/mixins/fullscreen.js#L16](https://github.com/quasarframework/quasar/blob/f70bf797301002fc9c0f0403a44c574dc2559062/ui/src/mixins/fullscreen.js#L16)

**Comment by luozhihua** [comment]
@hawkeye64 Great work! Thanks!

**Comment by rstoenescu** [comment]
New Boolean prop will be available in "quasar" v1.1.7: "no-route-fullscreen-exit"
