### ISSUE TITLE
[v1] - QTab alert aligned to top right of container not icon

### ISSUE THREAD

**Issue by jukieb0x** [quasarframework/quasar#4454]
**Describe the bug**
The alert and floating badges align to the top right corner of the container rather than the icon.

**To Reproduce**
See the code snippet below - Codepen

```
<div id="q-app">
  <q-tabs
        class="text-primary">
    <q-tab
         icon="folder_shared"
         alert="true"
         label="Much Longer Label">
    </q-tab>
  </q-tabs>
  <div class="q-ma-md">
    Running Quasar v{{ version }}
  </div>
</div>
```

**Expected behavior (as seen in V0.17)**
<img width="201" alt="Screenshot 2019-06-24 at 14 44 33" src="https://user-images.githubusercontent.com/17595312/60019625-a4727e00-968e-11e9-8c88-14b3033f73b2.png">

[Reproduction link](https://codepen.io/anon/pen/MMEwwx)

**Actual behavior (as seen in V1.0.0-rc.7)**
<img width="201" alt="Screenshot 2019-06-24 at 14 44 06" src="https://user-images.githubusercontent.com/17595312/60019685-c23fe300-968e-11e9-9ea8-2e1c87e32a25.png">

[Reproduction link](https://codepen.io/anon/pen/XLebmv)

**Platform (please complete the following information):**
OS: MacOS
Node: 12.4.0
NPM: 6.9.0
Yarn: - 
Browsers: -
iOS: -
Android: 27
Electron: -

**Additional context**
a [similar issue](https://github.com/quasarframework/quasar/issues/2032) was fixed in 0.17,  but was linked to q-tabs' alignment (not the case here)

**Comment by metalsadman** [comment]
https://quasar.dev/vue-components/tabs#Example--Tab-notifications. maybe provide link on your codepen.

**Comment by m0jimo** [comment]
Issue related to badge and tab was reported and there is a sugestion how to solve it but I haven't tried slot as sugested,  yet.
https://github.com/quasarframework/quasar/issues/4324

**Comment by rstoenescu** [comment]
Hi,

The behavior in v0.17 caused a lot of grief for a lot of devs who requested this change. Like m0jimo mentioned, this can be done with a slot or a CSS overwrite. Sorry for any inconvenience.
