### ISSUE TITLE
Combine Quasar inside Builds

### ISSUE THREAD

**Issue by albilia** [quasarframework/quasar#446]
Hello, recently I started to create Wizards for building builds in favor of Kodi. I wonder if it is possible to combine the Quasasr in the - Build. However, since the file hierarchy changes from one to another streamer. I would like to know whether it is possible or appropriate scripts need to recognize the hierarchy of files and extracts them in accordance with the operating system installed on Kodi / streamer.
Thanks in advance,
Nissim.

**Comment by rstoenescu** [comment]
Hi,

What is Kodi? Can you give a little background on what you want to achieve pls? Thanks!

**Comment by rstoenescu** [comment]
Please reopen with more details. Would love to fix any potential issue and support Kodi.
