### ISSUE TITLE
Quasar variables to be used with SCSS/SASS pre-processors

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4461]
**Is your feature request related to a problem? Please describe.**
Need to use Quasar internal variables into SCSS style

**Describe the solution you'd like**
Same variables, but with SCSS. Possibly with the same automatic import feature.

**Describe alternatives you've considered**
There really aren't, if using Stylus is not an option for the developer

**Additional context**
I saw the Stylus vs SCSS war already took place here, I won't jump in it with my opinions.
I made a [SCSS version](https://gist.github.com/IlCallo/8b56f91344e27a9c0acb85ed158b2fad) of the Stylus variables that Quasar uses internally and I'm here to share it, for who may be interested.

The transformation should probably be automated at every build to keep it in sync and SCSS version should be saved inside the framework with Stylus version, surely there is a Stylus-to-SCSS tool somewhere.

User overwrites of the defaults are the real problem here. For my case I'll just keep it in sync manually, but adding a CLI command to perform the transformation could be a nice workaround

**Comment by hawkeye64** [comment]
@IlCallo Have you seen this? https://github.com/txs1992/stylus-converter

You could even write a Quasar App extension that does this in the `beforeDev`/`beforeBuild` hooks.

**Comment by IlCallo** [comment]
Interesting, I'm currently working on TS integration now, I can see what I can do about this, even if I found other priorities (TS linting with ESLint, Jest+TS, etc etc)

**Comment by IlCallo** [comment]
Closing in favor of #5049
