### ISSUE TITLE
Random code into Quasar default Stylus variables

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4462]
**Describe the bug**
https://github.com/quasarframework/quasar/blob/f70bf797301002fc9c0f0403a44c574dc2559062/ui/src/css/variables.styl#L477-L481

These lines seem like dead dummy code, they don't seem to do anything.
They should probably be removed.

**Comment by pdanpdan** [comment]
It's used here: https://github.com/quasarframework/quasar/blob/f70bf797301002fc9c0f0403a44c574dc2559062/ui/src/components/chat/chat.styl#L58
:)

**Comment by IlCallo** [comment]
That doesn't really make sense tho...
[`max(a, b)`](http://stylus-lang.com/docs/bifs.html#maxa-b) is a built-in Stylus function, why redefining it?

**Comment by IlCallo** [comment]
Other strange thing

https://github.com/quasarframework/quasar/blob/f70bf797301002fc9c0f0403a44c574dc2559062/ui/src/css/variables.styl#L498

Here [`alpha()`](http://stylus-lang.com/docs/bifs.html#alphacolor-value) is used, while everywhere else [`rgba()`](http://stylus-lang.com/docs/bifs.html#rgbacolor--rgba) is used, which with the same arguments return the same result.
This should probably be changed too

**Comment by pdanpdan** [comment]
Can you please make a PR?
