### ISSUE TITLE
Integration with Loopback.io api

### ISSUE THREAD

**Issue by consultantcraig** [quasarframework/quasar#4468]
I love how easy it is to build an app with Quasar but finding information about how to inject an authentication layer is proving to be challenging.  All of the auth starter kits use an older version for one.  And I'm using Loopback for my api to my database (which is MongoDB).  Would be nice if I could just add a 'QLoginLoopback' component or type a Quasar command that steps through creating and linking a login form for my Loopback API.

**Comment by pdanpdan** [comment]
I use a HapiJS API. Somebody else will use Google/Facebook/Firebase/... OAuth.
It's something that is specific to your application.

**Comment by hawkeye64** [comment]
@consultantcraig 
This sounds like it'd be a good candidate for a Quasar App Extension, which is exactly why the AE API was created. Extend Quasar without modifying core.

**Comment by webnoob** [comment]
@consultantcraig Hit DavidWatson up on discord, he might have something that would help here as I know he was looking into Loopback stuff.

Closing as this isn't something core would implement as a feature.
