### ISSUE TITLE
$event is undefined when use QForm with @submit.prevent.stop modifier

### ISSUE THREAD

**Issue by JavaFellow** [quasarframework/quasar#4469]
when I use **QForm** with @submit.**prevent**.**stop** modifier:
> <q-form @submit.prevent.stop="onSubmit">

Click the submit button, browser's console throws "**Error in v-on handler: TypeError: Cannot read property 'preventDefault' of undefined**".

demo: https://codepen.io/daniel_cn/pen/ewEvRQ?editors=1011

**Platform (please complete the following information):**
OS: Windows 10 1809
Node: 10.16.0
NPM: 6.9.0
Browsers: Chrome 69

**Comment by pdanpdan** [comment]
Thanks for reporting. But it doesn't make any sense to use `.prevent` or `.stop` because the event is already stopped.

**Comment by rstoenescu** [comment]
Will get into final 1.0.0
