### ISSUE TITLE
Automatically add kebab-cased class to components for styling

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4470]
**Is your feature request related to a problem? Please describe.**
Is good practice to put a class identifying the component on the root element to ease styling from outside.
I saw you already do this manually with a "staticClass" property, this can probably be automated starting from the component name, also to enforce this good practice.

**Describe the solution you'd like**
I created a global mixin which does this automatically.

```ts
import Vue from 'vue';
import { kebabCase, isEmpty } from 'lodash-es';

export const ApplyComponentNameAsClass = Vue.extend({
  mounted() {
    if (
      isEmpty(this.$options.name) ||
      this.$el.nodeType !== Node.ELEMENT_NODE
    ) {
      return;
    }

    this.$el.classList.add(kebabCase(this.$options.name));
  }
});

```

**Additional context**
I saw you use BEM, so inner components sometimes have a class with BEM style instead of plain kebab-cased version, this can complicate things.

It could be an opt-out feature, managed by a global configuration which every component can override to disable it locally.
It could also accept different transformation styles (kebab-case, BEM, etc) for the component name or a custom function which will be used to transform the component name.
Because Quasar components will get the global mixin too, a disclaimer should be put or user-defined transformation  should not be applied on Quasar components.

Like the idea?

**Comment by rstoenescu** [comment]
Hi,

Thanks for wanting to contribute!

Unfortunately, I'd have to disagree with this approach. Yes, it's hard-coded, but it's way better for performance rather than running a hook for this, and we want to squeeze every bit of perf that we can. Hope you can agree.

**Comment by IlCallo** [comment]
Yeah, no problem, was just a suggestion 👍

**Comment by rstoenescu** [comment]
And thank you for it, though! Looking for more. We're all here to make web developer better.
