### ISSUE TITLE
Applying dimmed to QSplitter dims entire page

### ISSUE THREAD

**Issue by figuernd** [quasarframework/quasar#4473]
Applying the "dimmed" class to a q-splitter element or the parent of a q-splitter results in most of the page being dimmed. My workaround was to dim the top level items within the q-splitter panels, but this leaves the resize divider between panels undimmed.

Reproduced here: https://codepen.io/anon/pen/MMvGjG?editors=1010

**Comment by pdanpdan** [comment]
Add a position-relative class to the element.
