### ISSUE TITLE
[v1 feature request] To add on QList menu current location on expansion item support

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#4476]
I have QList main site menu with QExpandionItem.

And when I am on current route it highlight menu item, but if it is under QExpansion Item QExpansionItem do not highlighted.

I think it will be very useful feature if set in options to highlight QExpansionItem if inside if highlighted QItem.

And option to autoexpand this items.

**Comment by pdanpdan** [comment]
This is something you need to manage in your application, it cannot be done automatically.
