### ISSUE TITLE
QInput - Wrong timestamp data type in the demo 

### ISSUE THREAD

**Issue by 549393092** [quasarframework/quasar#4477]
https://github.com/quasarframework/quasar/blob/dev/ui/dev/components/form/date-time-timestamp-test.vue
In the above link, it is defined as **timestamp: '1558626538737'**,
however in real case it should be **timestamp: 1558626538737**, could you please check it?

**Comment by rstoenescu** [comment]
It's not a mistake. Cast to string (`'' + timestamp), since QInput deals with strings.
