### ISSUE TITLE
'.bold' has bugs under some consoles

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#448]
`.bold` method is used in many places in `/build/scirpt.*.js`, but under some consoles it brings bugs: some texts after the `.bold` text are missing, like this:

![image](https://cloud.githubusercontent.com/assets/13058150/23737766/144d48d4-04d0-11e7-90a8-6367ddf5c956.png)

comparing with the normal output: 
![image](https://cloud.githubusercontent.com/assets/13058150/23737777/257557fa-04d0-11e7-93c7-52714b2e88cc.png)

or

![image](https://cloud.githubusercontent.com/assets/13058150/23737805/45271228-04d0-11e7-9401-c07c566aa3f8.png)
 and
![image](https://cloud.githubusercontent.com/assets/13058150/23737815/53ecf660-04d0-11e7-970f-73b3d98bc675.png)

My suggestion: get ride of `.bold` would be all OK.

(I am using cmder as console)

**Comment by rstoenescu** [comment]
Hi,

Can you do a quick test with `chalk` package instead of current `colors` and see if that works for you? Thanks!

**Comment by beeplin** [comment]
`chalk` has the same issue: 

```js
chalk = require('chalk')

console.log(' Starting dev server with "' + chalk.bold(process.argv[2] || env.platform.theme) + '" theme...')
console.log(' Will listen at ' + chalk.bold(uri))
if (config.dev.openBrowser) {
  console.log(' Browser will open when build is ready.\n')
}
```

gives:
![image](https://cloud.githubusercontent.com/assets/13058150/23745303/aeddce4c-04f2-11e7-9cd8-ee9f567b85fd.png)

and if use `chalk.blue` instead of `chalk.bold`:
![image](https://cloud.githubusercontent.com/assets/13058150/23745354/cf88d524-04f2-11e7-8fa7-b97f25d0fd17.png)

note that the text after the blue parts turns to bright white. Still buggy. 
I guess this is related to some incompatibilities between cmder/conemu and the coloring mechanism used by `colors` and `chalk`.

**Comment by rstoenescu** [comment]
Moving to appropriate repo. https://github.com/quasarframework/app-template-default/issues/15
