### ISSUE TITLE
Local mock API

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4480]
**Is your feature request related to a problem? Please describe.**
When starting using Quasar, it would be lovable to have some options to get a fully working local in-memory or json server to stub connections with axios (REST) or apollo-client (GraphQL).

**Describe the solution you'd like**
I'm talking about something like https://github.com/angular/in-memory-web-api from Angular.
That automatically hi-jack the requests and send them to an in-memory script, in our case I found some json-based options which can be useful: [REST](https://github.com/typicode/json-server), [GraphQL](https://github.com/marmelab/json-graphql-server).

The thing I don't like from those solutions is that they suggest to install the packages at global level, but I guess it's totally possible to install them as dev dependencies and create an ad-hoc quasar command to launch each of them.
Or an option over `quasar dev`, like `quasar dev [--fake-rest] [--fake-graph-ql]`, which in turns need to allow full configuration of the underlying packages, so probably a config file is needed somewhere.

Everything should work offline, so online services were automatically discarded from my search.

Like the idea? I did something similar on a previous work with Angular and it helped a lot speeding up fast prototyping

**Comment by lucasfernog** [comment]
That's a nice idea, but I think it should be an app extension.

**Comment by nothingismagick** [comment]
I agree with Lucas. This is a nice idea but really an edge case. I can see
how it would be nice fit with @quasar/testing though...

**Comment by rstoenescu** [comment]
I agree with an app extension for this. Would fit perfectly!

* Introduction to development of an App Extension: https://quasar.dev/app-extensions/development-guide/introduction
* Introduction to what App Extensions are: https://quasar.dev/app-extensions/introduction

You in? @IlCallo

**Comment by lucasfernog** [comment]
That's an app extension i'd like to work with, but I don't have the time right now. If @IlCallo wants to do it, I can help with any issues.

**Comment by IlCallo** [comment]
I'm in :)
But I cannot commit to any timeframe, I'm still exploring the Quasar ecosystem and trying to figure out some problems with Typescript and WebPack configuration for my project.
We can start defining the API in the meantime :P

`quasar dev [--fake-rest] [--fake-graph-ql]` is something that you may accept? And where should the configuration files be put?
What is the best way to manage these kind of extension, if there were similar ones?

**Comment by genuinefafa** [comment]
any news on this? i'ld love an extension...

**Comment by IlCallo** [comment]
Still hadn't a project where I really needed this for now, because I ended up using Firebase for the current project and I worked on getting better support for Firebase testing in Quasar instead.

I'll probably take this on when I'll need to setup a new project where I need a real backend service, which I'm afraid is an even pretty far in time (_maybe_ a new project coming in in February)

**Comment by rstoenescu** [comment]
Would love to see an App Extension on this.
But closing ticket as it doesn't has anything to do with core.

**Comment by rstoenescu** [comment]
Please feel free to continue discussion here.

**Comment by IlCallo** [comment]
Found and interesing project for this: https://github.com/miragejs/miragejs
