### ISSUE TITLE
Location of preload scripts for Electron webviews

### ISSUE THREAD

**Issue by burningTyger** [quasarframework/quasar#4481]
**Is your feature request related to a problem? Please describe.**
Beginning with Electron 6 the preload scripts for webviews must be on available on `app.getPath()` The static directory seems inaccessible and therefore the app wikk throw an error when trying to access the preload script.

**Describe the solution you'd like**
There should be a var like `__statics` that lets us store a preload script which is accessible to electron. It doesn't necessarily need to be compiled with webpack (in my situation even better without) but it has to be on the electron path.

**Describe alternatives you've considered**
I tried and tinkered but xouldn't find a simple solution to solve this problem. It's not really clear to me how files are moved around in the build process. Maybe add some documentation on that instead?

**Additional context**

**Comment by rstoenescu** [comment]
Should have closed this one some time ago. Preload script support has been added to q/app.
