### ISSUE TITLE
[v1] Numeric value not displayed when using mask

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4484]
Hello!

Example: https://codepen.io/anon/pen/VJraMK?&editable=true&editors=101

1) '####' + string '2019' works ok
2) '####' + numeric 2019 does not work (value is not displayed)

Thanks!

**Comment by pdanpdan** [comment]
If the PR goes in the main branch please watch out, because:

WARNING: when using numeric values numbers with different number of decimals from the number of decimals in the mask will generate problems.

**Comment by rstoenescu** [comment]
Will be available in 1.0.6
