### ISSUE TITLE
Image not showing in some android devices

### ISSUE THREAD

**Issue by thami-bn** [quasarframework/quasar#4492]
My application does not display images from the server in other android devices, however on the browser and some devices it does show the image perfectly.

```
<q-img
      :src="blogPost.image_url"
>
                   <template v-slot:loading>
                    <div class="text-subtitle1 text-white">
                      <q-spinner-ios color="primary" />
                      <div class="q-mt-md">Laden...</div>
                    </div>
                  </template>  
                   <template v-slot:error>
                    <div class="absolute-full flex flex-center bg-negative text-white">
                      cannot display image
                    </div>
                  </template>
                </q-img>
```
the image url returned from the server is valid if i copy it to the browser it does show the image.

**Comment by nothingismagick** [comment]
Can you please post the results of

quasar info

**Comment by thami-bn** [comment]
@nothingismagick 
![Screenshot20190628100008](https://user-images.githubusercontent.com/48582283/60327225-9cb32200-998b-11e9-9213-ceaeb7aa38a9.jpg)

**Comment by nothingismagick** [comment]
This is as I expected, your Quasar dependencies are very out of date.
Please do the following:

```
$ npm install -g @quasar/cli
$ quasar upgrade -i
```

**Comment by thami-bn** [comment]
@nothingismagick 
i have tried the above however still the image is not showing in my android device it only shows on the browser side

**Comment by nothingismagick** [comment]
You know, we have an issue template so that we don't have to ask all these
questions everytime like EXACTLY what OS and build target is broken.
Otherwise triaging for 'some OS' and maybe Cordova is just not tenable.
Please make it easier for us to help you. :)

**Comment by rstoenescu** [comment]
@thami-bn This is not a Quasar issue. A few things to keep in mind:

1. If you are using URLs for your images then your Cordova app depends on an Internet connection -- you might not want that. Better use 'assets' or 'statics' for your image.
2. Have you used the remote debugging tool ([Android](https://quasar.dev/quasar-cli/developing-mobile-apps/troubleshooting-and-tips#Android-remote-debugging), [iOS](https://quasar.dev/quasar-cli/developing-mobile-apps/troubleshooting-and-tips#iOS-remote-debugging)) to see why it doesn't works? At best it's a matter of Cordova configuration.

Please use our forum or Discord to seek for help, after you've used remote debugging. Thanks.

**Comment by csongithub** [comment]
I am using a cordova camera feature in my app. The camera is working fine and storing the image in SD card at some location (in my case it is app location)

Image Location: file:///storage/emulated/0/Android/data/com.client.workly.app/cache/1595418462506.jpg

But same when I'm trying to use in in <q-img>, it is not showing the image

<q-img rc="file:///storage/emulated/0/Android/data/com.client.workly.app/cache/1595418462506.jpg"  />

I am testing my app in emulator.

Any help will be appreciated.

Thanks

**Comment by webnoob** [comment]
@csongithub This is not a quasar problem so you won't find a solution here. Your issue is specific to your app.
