### ISSUE TITLE
[v1.0.0rc5] In MS Edge a floating badge on a button jumps when button is clicked

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#4493]
In MS Edge a floating badge on a button changes position (to the inner of the button) when the button is clicked.

How to reproduce:

Click on button here:
https://quasar.dev/vue-components/badge#Example--Floating

![image](https://user-images.githubusercontent.com/33280703/60329545-d9354c80-9990-11e9-8ac6-5e0c587b16c4.png)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.2.
