### ISSUE TITLE
infinite scroll enless loop

### ISSUE THREAD

**Issue by ldenblyd** [quasarframework/quasar#4495]
hello guys i have a issue with infinite scroll component 
i donc know why loadMore is trigger event if im not at the bottom of the page

![image](https://user-images.githubusercontent.com/23713069/60343887-99cd2700-99b5-11e9-9a6d-b056f3f7286a.png)

**Comment by ldenblyd** [comment]
the exemple work only in i put it in racine 
in child component it's not working

**Comment by ldenblyd** [comment]
ok i just understand, the parent need to be the scrollable element.

**Comment by rstoenescu** [comment]
Hi,

There's some props related to targeting a specific node for scrolling events. Always check out the API card for the components that you are using.

If you feel that docs can be improved, please PR it.

Thanks!

**Comment by ldenblyd** [comment]
hello rstoenescu, thanks for your work, you do a amazing job on quasar ! 

is it possible to target a div from double parent component ?
