### ISSUE TITLE
prevent scroll will not work on Iphone

### ISSUE THREAD

**Issue by jehadja** [quasarframework/quasar#4497]
prevent scroll class which used on open dialog for example have overflow:hidden ; 
which is quit correct for browser and windows .
unfortunately its will not work for iPhone 9 + 
its a famous bug 
reference
https://stackoverflow.com/questions/3047337/does-overflowhidden-applied-to-body-work-on-iphone-safari
```
.q-body--fullscreen-mixin, .q-body--prevent-scroll {
overflow: hidden !important;
}
```
i just add fixed for layout on open dialog etc... 
and it works perfectly  
```
.q-body--prevent-scroll
  .q-layout
    position: fixed

```
i actually need it for putting carousel inside dialog which was not working correctly because scroll can go x,y 
![image](https://user-images.githubusercontent.com/17106547/60370525-83e45400-99ff-11e9-958f-98cbd3754add.png)
now every thing work correct hope it will help !

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6
