### ISSUE TITLE
Quasar Project initialization problem

### ISSUE THREAD

**Issue by ZealWhiteMouse** [quasarframework/quasar#4502]
This is an error message
   **error  Extra semicolon  semi**

Writing is too strict. How can I be less strict

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by ZealWhiteMouse** [comment]
> Hi,
> 
> In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience.
> 
> Thanks. 😄
> 
> Scott

thanks

**Comment by rstoenescu** [comment]
[Remove ESlint](https://quasar.dev/quasar-cli/cli-documentation/linter#Disabling-Linter) or [configure it](https://quasar.dev/quasar-cli/cli-documentation/linter#Lint-Rules) to suit your needs.

**Comment by linyangcong** [comment]
I want to know why i init project ,then it reports  Missing .babelrc file..., 
thank you~

**Comment by smolinari** [comment]
@linyangcong - as I said above, if you have questions, please ask them on our forum or discord chat channel. 

Scott
