### ISSUE TITLE
How to access component methods from parent?

### ISSUE THREAD

**Issue by danikane** [quasarframework/quasar#451]
First of all, many thanks to Razvan for this amazing framework and yet another release!
Does anyone know how to access the component methods described in the docs?
For example: 
http://quasar-framework.org/components/slider.html
has **goToSlide** and **toggleFullscreen()**

http://quasar-framework.org/components/pull-to-refresh.html
has **@trigger**
Can I invoke those programmatically from within the parent component?

**Comment by jonafrankbrimma** [comment]
Give the function definition for trigger inside the child component and bind it to @trigger 
From the parent , give a reference to the child component by defining ref="<child_ref_name>"

Then you can trigger the trigger event by calling $refs.<child_ref_name>.toggleFullscreen() This should work 👍

**Comment by rstoenescu** [comment]
Hi, please use forum for questions. Thanks!

**Comment by danikane** [comment]
@jonafrankbrimma Thanks :)
@rstoenescu Yes, sorry about that.
