### ISSUE TITLE
Error is shown when using endOfDate

### ISSUE THREAD

**Issue by marcelodelta** [quasarframework/quasar#4516]
Error is shown when using endOfDate

**Screenshots**
<img width="547" alt="Captura de Tela 2019-06-30 às 22 16 56" src="https://user-images.githubusercontent.com/2933264/60405222-3396fe80-9b85-11e9-945d-a2f5798e31e2.png">
![Captura de Tela 2019-06-30 às 22 17 12](https://user-images.githubusercontent.com/2933264/60405226-38f44900-9b85-11e9-8128-1800c3a1fee0.png)

**Platform (please complete the following information):**
OS: MacOs Majove 10.14.5
Node: v10.15.3
NPM: 6.9.2
Yarn: 1.15.2
Browsers: Google Chrome

**Comment by lucasfernog** [comment]
Date.now returns an integer, and the endOfDate function expects a Date object. Please use `let newDate = new Date()` instead.

**Comment by marcelodelta** [comment]
Thank you. It work.
