### ISSUE TITLE
Loading.show() not working in vue file method

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#4521]
I believe something is wrong with Loading.show()... or I don't understand how/where to properly use Loading.show()

My use case is a Login page.  Is simply want to show the spinner at the start of a "submitForm" method and hide it at the end of an *action* promise is done.

Here is the minimal reproduce-able example:  
https://codesandbox.io/s/codesandbox-app-otnhl
 Dev mode.......... spa
 Pkg quasar........ v1.0.0-rc.5
 Pkg @quasar/app... v1.0.0-rc.7

Put "/login" as your URL and and take a look at **Login.vue**
I have my action where I try to fake out a long-running operation.  Console messages seem to fire off exactly when expected!  Loading.show() and Loading.hide() just aren't working.

One weird quirk... if I add a setTimeout to submitForm method... I can indeed get Loading.show() to fire.  It's almost like it doesn't fire because it's going out of scope?  I also tried using @click handlers instead of @submit on the form--but form submission doesn't seem to be the blame.  Any help appreciated... love Quasar!

**Comment by metalsadman** [comment]
@rfox12 when using in vue file you invoke it `this.$q.loading`, it's in the docs https://quasar.dev/quasar-plugins/loading#Usage.

**Comment by smolinari** [comment]
It works, if you put `Loading` inside your login function. 

https://codesandbox.io/s/codesandbox-app-3txsz

Scott

**Comment by rfox12** [comment]
@metalsadman Thank you--I did indeed try that initially.  It still doesn't work for me... see updated https://codesandbox.io/s/codesandbox-app-otnhl

@smolinari Thank you--your way is working for me.  But my preference would be to keep UI manipulation logic in the Login.vue page if possible...

**Comment by metalsadman** [comment]
> @metalsadman Thank you--I did indeed try that initially. It still doesn't work for me... see updated https://codesandbox.io/s/codesandbox-app-otnhl
> 
> @smolinari Thank you--your way is working for me. But my preference would be to keep UI manipulation logic in the Login.vue page if possible...
> 
> I think something is broken with my action return/promise.. I'll dig into it. I was convinced this was a bug.

It didn't work coz you were immediately hiding the loader as soon as it got shown.
fixed some code in your repro, and added some comments https://677i5.sse.codesandbox.io/login
and here for the source.

**Comment by rfox12** [comment]
@metalsadman wow... thank you so much!  I had modified my code significantly to use centralized state but I like the promise/reject() option--learned a lot form your code.  If you ever need testing to make something idiot-proof give me a shout.  ;)
