### ISSUE TITLE
Material icons aren't displaying using IE 11 during production

### ISSUE THREAD

**Issue by LuisEnMarroquin** [quasarframework/quasar#4523]
**Describe the bug**
Material icons don't display correctly using IE 11 in production mode

**To Reproduce**
* In Development mode (displaying correctly)
1. Run `quasar dev`
* In Production mode (displaying incorrectly)
1. Run `quasar build`
2. Run `node app.js`
* app.js
```javascript
const
  express = require('express'),
  serveStatic = require('serve-static'),

const app = express()

app.use(serveStatic(serveStatic('./dist/spa')))
app.listen(port)
```

**Expected behavior**
Show material icons on both modes, development and production

**Screenshots**
![image](https://user-images.githubusercontent.com/35376824/60484104-d327c000-9c5d-11e9-9f13-1e518c5c2641.png)

**Platform**
OS: Windows 10
Node: 10.4.1
NPM: 6.1.0
Yarn: 1.13.0
Browser: Internet Explorer 11

**Comment by webnoob** [comment]
Just to confirm, you do have IE mode enabled in the quasar.conf.js file, yes?

**Comment by LuisEnMarroquin** [comment]
Yes, I have supportIE enabled
![image](https://user-images.githubusercontent.com/35376824/60514906-13a82d80-9ca0-11e9-86ec-5d2f3277de35.png)

**Comment by rstoenescu** [comment]
Looks fine. And also thoroughly tested with the help of some team members.

Are you sure you don't have any plugins or Edge config that breaks the download of the Material font file? Please join us on Discord. Thanks.

<img width="814" alt="monty" src="https://user-images.githubusercontent.com/4665641/60770197-14e2bb80-a0e1-11e9-8a86-d764faffb296.png">

**Comment by LuisEnMarroquin** [comment]
In Edge works fine, but I am saying that in Internet Explorer 11 doesn't

**Comment by rstoenescu** [comment]
* I've downloaded your test app, built it, and served it in IE11 (picture below).
* I also noticed that for some reason, when accessing https://monty.marroquin.dev with IE11 the font files have 396B, which is definitely wrong. It may have something to do with your server where you've deployed the website, so please investigate.
* https://quasar.dev is running fine in IE11

<img width="1066" alt="monty" src="https://user-images.githubusercontent.com/4665641/60819478-57230000-a1a8-11e9-8cf4-95dd2bca91c2.png">

**Comment by LuisEnMarroquin** [comment]
Great, I'm going to check that
Thank you
