### ISSUE TITLE
Create Quasar Testing Approach

### ISSUE THREAD

**Issue by valasek** [quasarframework/quasar#4524]
# Success Criteria
1. Tests will run against every PR and test coverage report will be automatically available as a part of each PR
2. All build targets on all platforms will be covered or document the reasons why not covered
3. Proposed test approach can cover all components
4. At least 3 test cases per each test type are created and a starting point for the community
5. The proposed approach gives Quasar developers high flexibility during refactoring without the need to rewrite the majority of tests
    - how to verify this was achieved?
6. Documentation is updated:
    - [PULL_REQUEST_TEMPLATE.md](https://github.com/quasarframework/quasar/blob/dev/.github/PULL_REQUEST_TEMPLATE.md) - describe mandatory test updates
    - [CONTRIBUTING.md](https://github.com/quasarframework/quasar/blob/dev/.github/CONTRIBUTING.md) - describe mandatory test updates
    - [README.md](https://github.com/quasarframework/quasar/blob/dev/README.md) - will contain the link to overall test coverage
    - Contribution guide (link to the docs will be added when published) - describe how to run test suite manually and how to add new test per each test type

# Expected benefits from the change
1. Guarantee stability during the refactoring
2. Starting place for new contributors

I believe that this should be led by one of the core team members as I have seen 2-3 unmerged community attempts and respecting current dev priorities. Can be started after v1 is out + 1 week for stabilization.

# Other Information

## Related PRs
* feat(test) Introduction of test harnesses, #3976
* [v1-research] CI and Smoke Tests, #2872
* Adding Some Unit Tests, #1796
* fix: Correct component test instantiation (fix: #3894), #3895

## Related Issues
* Local mock API, #4480

## Inspiration
[An Overview of JavaScript Testing in 2019](https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2019-264e19514d0a)
Vue.js - [tests](https://github.com/vuejs/vue/tree/dev/test), [coverage](https://codecov.io/github/vuejs/vue?branch=dev)
Nuxt.js - [tests](https://github.com/nuxt/nuxt.js/tree/dev/test), [coverage](https://codecov.io/gh/nuxt/nuxt.js)
Element - [tests](https://github.com/ElemeFE/element/tree/dev/test), [coverage](https://coveralls.io/github/ElemeFE/element?branch=master)

**Comment by rstoenescu** [comment]
Hi,

This is an internal process and I'd like we use the internal system to track this. Thanks.
