### ISSUE TITLE
[v1] Browser auto complete bad value in QSelect with use-input

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#4527]
**Describe the bug**
When I have a form with a QSelect that has the use-input prop set and the form has at least one other QInput field, when the browser offers to autofill the form fields for you from the QInput and it puts a value into the input of the QSelect also, the value may not match any of the choices for the QSelect and the text remains in the QSelect's input field. Once I click into the QSelect input field, the label slides up and the text that did match any of the choices goes away when I click back out of its input field.

Quasar v0.17 did not have this issue since the QSelect's input field for filtering did not seem to pick up the autofill since it only shows after the user opened the list of choices.

autocomplete="off" did not seem to prevent the QSelect from being autofilled.

The code pen does not include the vuelidate validation, but I found that after the QSelect's input had a value from autofill, the validation failed, but the input itself did not show the error indication ( red outline, etc )

For now the work around is to not use the use-input prop.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/smakinson/pen/PreaBo

**To Reproduce**
1. Go to https://codepen.io/smakinson/pen/PreaBo
2. Click on the QInput and hopefully receive a menu from the browser for autofill
3. Choose your auto fill value, probably an address.
4. Notice a value auto filed into the QSelect's input and the label out of place and it does not match since its not an object like the stateOptions list.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS: OSX
Browsers: Chrome, possibly others if they have autofill info.

**Additional context**

**Comment by metalsadman** [comment]
@smakinson autocomplete is a native attribute that only works for elements form and input which QSelect isn't, since it uses the native select element. what you can do is wrap your form inputs in a `form` or a `q-form` and set your autocomplete="off" there https://quasar.dev/vue-components/form.

**Comment by smakinson** [comment]
Hmm, could go that route, just thinking I know users don't like filling out forms, so I am hoping to leave at least partial autocomplete as to avoid deterring donations.

**Comment by rstoenescu** [comment]
Use `autocomplete="off"` and the other required HTML attributes (if any) to disable autocomplete. All attributes on QSelect are applied to the native input. No need for `<form>`.
