### ISSUE TITLE
Less Strict Parallax Speed property

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#4530]
**Is your feature request related to a problem? Please describe.**
The parallax component has its quarks which I will open issues for, but immediate simple thing is that it is too strict on the speed prop 0 - 1. This may sound fishy, but hear me out, 2.5 or 1.7 or any number beyond 1.5, creates a weird nice effect. Where the image viewport grows vertically then shrinks to nothing as it reaches midpoint or upper part of the page depending on the speed set. problem is it shouts a validation error on the prop, though it works.

**Describe the solution you'd like**
Don't restrict it to between 0 - 1, let the dev be free to use whatever value they desire without throwing an error. Recommend in the docs that the proper value is 0 - 1, anything above gives other effects.

**Comment by rstoenescu** [comment]
Hi,

Sorry but we'd like not to create more trouble than we are solving with the framework. Yes, we can relax the prop validation and add a big flashy banner about it, but it's really easy to introduce a mistake somewhere in your code and QParallax will appear as if it's malfunctioning. Which is not what we want. More tickets to waste everyone's time. Hope you can understand and sorry for replying sooo late on this one.
