### ISSUE TITLE
Allow QDialog to use promise chain 

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#4532]
This is my scenario. 
The user has two(2) available actions which are "save" and "finalize".
Save just saves the record but allows the user to update it again later.
Finalize also saves the record but it makes the record permanent and cannot be updated again.

In my UX design, the "save" action immediately sends the post request in the rest api, 
while the "finalize" action needs a confirmation first before sending the post request.

In my example I created a wrapper `$confirm` to shorten usage of QDialog. Its return value is just the same with `this.$q.dialog(...)`

My current code looks like this:
```js
methods: {
    action(action) {
        let promise = Promise.resolve()

        if (action === 'finalize') {
            promise = new Promise((resolve) => {
                this.$confirm('Are you sure to finalize record?').onOk(resolve)
            })
        }

        promise.then(() => {
            return axios.post(...)
        }).then(({ data }) => {
            this.data = data
        })
    }
}
```
If using chainable promise, the code can be like this:
```js
methods: {
    action(action) {
        let promise = Promise.resolve()

        if (action === 'finalize') {
            promise = this.$confirm('Are you sure to finalize record?')
        }

        promise.then(() => {
            return axios.post(...)
        }).then(({ data }) => {
            this.data = data
        })
    }
}
```

### Other code improvements

```js
// Current QDialog design
// This introduces 2 level of indentions
methods: {
    action(action) {
        this.$confirm('Are you sure to finalize record?').onOk(() => {
            axios.post(...).then((data) => {
                this.data = data
            })
        })
    }
}
```
__vs__
```js
// Proposed QDialog with chainable promise
// This can keep 1 level of indention
methods: {
    action(action) {
        this.$confirm('Are you sure to finalize record?').then(() => {
            return axios.post(...)
        }).then((data) => {
            this.data = data
        })
    }
}
```
__Also__, promises are useful in async/await methods.

### Similar methods in Promises

The methods `onOk`, `onCancel` and `onDismiss` can be respectively the same with
Promise methods `then`, `catch` and `finally`.

```js
this.$q.dialog(...).onOk(() => {
  // called when ok is clicked
}).onCancel(() => {
  // called when cancel is clicked
}).onDismiss(() => {
  // always called on both onOk and onCancel
})
```
__vs__

```js
this.$q.dialog(...).then(() => {
  // called when ok is clicked
}).catch(() => {
  // called when cancel is clicked
}).finally(() => {
  // always called on both on ok and cancel
})
```

### Compatibility

It will be backward incompatible if we replace the return values with promises. 
For compatibilty purpose, I suggest we can create a method like `toPromise()` 
that will convert the return type to a chainable promise. This way we can choose the promise approach.

```js
this.$q.dialog(...).toPromise().then(() => {
// some code
})

```

**Comment by rstoenescu** [comment]
Hi,

In previous versions we used to return a Promise, but it turned out that it involved a lot of overhead which was noticeable on lower end phones. If we are to pick between 1 and 2 level of indentation vs performance, it's best to go with performance. Can't "simulate" Promises either because we'll create confusion and a lot of grief for developers in many scenarios. Sorry for any inconvenience.
