### ISSUE TITLE
Change the method of the stylus variables to use "background" rather than "background-color"

### ISSUE THREAD

**Issue by StuffBySpencer** [quasarframework/quasar#4535]
**Is your feature request related to a problem? Please describe.**
Not such a **major** problem, *per say*, however I noticed that in some update you must have changed how the stylus variables [ *$primary, $secondary, $accent, etc.* ] were being applied.

Before, they must have been applied using either `background: "";` *or* `background-image: "";`

The nice thing about this was it allowed us to set a gradient to those variables.

**For instance:**
I used to set my `$primary` variable to:
`$primary   = linear-gradient(to right, #5496FF, #8739E5)`

This no longer works, however, because the variable looks to be applied using `background-color` which doesn't accept `linear-gradient` as a value.

**Describe the solution you'd like**
Instead of applying the variables with `background-color`, apply them using `background`.

**Describe alternatives you've considered**
We can of course set our own css to accomplish this, but using the build in variables saves a lot of hassle.

**Additional context**
*I know that using gradients in our main color variables might be tacky, but I like the look of them ;^)*

**Comment by hawkeye64** [comment]
If you would like to learn how to re-skin a Quasar component to take gradients, check out this codesandbox I wrote. I think it's exactly what you want (depending on the component): https://codesandbox.io/s/codesandbox-app-7m5uu

**Comment by StuffBySpencer** [comment]
Thanks for the response, however, I already know how to apply gradients via normal css classes.

What I'm specifically asking for with this issue is being able to use the **internal quasar styling variables** [ *such as `primary`, `secondary`, and `accent`* ] to apply the gradients. I've outlined why this isn't possible in my submission above.

It's a small change, but it'd be nicer to use the already provided, built-in variables, rather than having to write up an additional class.

**Comment by rstoenescu** [comment]
Hi,

I'm sorry, but changing to "background" can cause other problems, including when devs also want a background-image applied. However you put it, something's gotta give. However, you can override the Quasar CSS classes for these to fit your purpose (text-primary, bg-primary etc).
