### ISSUE TITLE
QSelect standout wrongly positioned in responsive mobile

### ISSUE THREAD

**Issue by Hamdan85** [quasarframework/quasar#4536]
**Describe the bug**
The QSelect standout shows wrongly on mobile layout... 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/hamdan85/pen/WqyRrR

**To Reproduce**
1. Load the codepen
2. Open the Chrome Inspection
3. Simulate a mobile device
4.Reload the window
5.Focus the QSelect

**Expected behavior**
Field standout should be within the field itself or, if it pops out, in the center of the screen with the classes specified on standout property

**Screenshots**
<img width="1792" alt="Screen Shot 2019-07-03 at 10 37 01" src="https://user-images.githubusercontent.com/1886026/60596036-8b4c8a00-9d7e-11e9-85ae-918886d5ce2e.png">

**Platform (please complete the following information):**
Operating System - Darwin(18.6.0) - darwin/x64
NodeJs - 12.3.0

Global packages
  NPM - 6.9.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.4
  cordova - 8.1.2 (cordova-lib@8.1.1)

Important local packages
  quasar - 1.0.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.0 -- Quasar Framework local CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

**Comment by Hamdan85** [comment]
It seems to be something about the filter event and v-slot:no-option. When I remove these two it shows correctly (even giving me 'Stack Size Exceeded' error), but it shows correctly ate least.

**Comment by rstoenescu** [comment]
As long as you have a menu on it and use an input with it, this is the actual required behavior. It can't be in the middle of the screen because on mobile there's the keyboard popping out from the bottom. Moreover, and the main reason: due to many years ago reported iOS rendering bugs (that Apple simply doesn't want to fix), the UI would become a mess without this separate behavior for mobile.
