### ISSUE TITLE
QDialog with QLayout doesn't open

### ISSUE THREAD

**Issue by informatious** [quasarframework/quasar#4537]
**Describe the bug**
When trying to open a QDialog with containerized QLayout the background blurs (OK) but the dialog itself doesn't (always) show (NOK).
Mostly the dialog doesn't show, however in some rare cases I was able to see it.
Even specifying the width (as defined in the docs) the dialog doesn't show.
This used to work in rc5.
I'm able to reproduce the issue with the example in the docs.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/dialog --> "With containerized QLayout"

**To Reproduce**
1. Click on the button that opens the QDialog with QLayout
2. Notice that the background blurs, but the dialog doesn't show (even if defining width and height)
3. In the rare case it does open, close the dialog and retry with step 1

**Expected behavior**
The dialog should be visible

**Screenshots**
<img width="1680" alt="beforeclick" src="https://user-images.githubusercontent.com/50235714/60604576-41809580-9db8-11e9-8cac-db1ac574362b.png">

<img width="1680" alt="afterclick" src="https://user-images.githubusercontent.com/50235714/60604575-41809580-9db8-11e9-8178-6c3c038f0850.png">

**Platform (please complete the following information):**
OS: MacOS
Browsers: Safari & Chrome (latest)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fixed in 1.0.2.
