### ISSUE TITLE
QInput focus after it no longer exists (autofocus)

### ISSUE THREAD

**Issue by copying** [quasarframework/quasar#4545]
**Describe the bug**
QInput autofocus an error `TypeError: this.$refs.input is undefined` if destroying doing it fast. Event a `$nextTick` is not enough to prevent it.

**jsFiddle**
https://jsfiddle.net/tvqw85fn/

**To Reproduce**
Open the example and the error should apear in the console.

**Expected behavior**
It should not try to focus if the input does not exist.

**Platform:**
OS: MacOS 10.14.5
Browsers: Firefox 67.0.4 (64-bit), Google Chrome 75.0.3770.100

**Additional context**
Looking at the code for possible reasons I found that [QField autofocus uses setTimeout instead of $nextTick](https://github.com/quasarframework/quasar/blob/e89db648444a670bd06b67b69220ac7b95b4b3af/ui/src/components/field/QField.js#L465). Changing this line makes my application work, but I don't know how to test it any further.

**Comment by rstoenescu** [comment]
Fix will be available in quasar 1.0.4
