### ISSUE TITLE
The global stylus file (i.e. src/css/app.styl) didn`t work

### ISSUE THREAD

**Issue by ryan3216** [quasarframework/quasar#4549]
**Describe the bug**

I wrote a function of stylus in local scope. It worked well.
like this:
```
// component/test.vue
<style lang="stylus" type="text/stylus" scoped>
px2rem(p)
  $fontSize = 37.5
  (p / $fontSize)rem

.ebook
  position: relative;   // 使用相对布局
  .read-wrapper
    .mask
      .left
        flex:  1 1 px2rem(100)
        background-color #faa0b1
</style>
```
But if the function removed to src/css/app.styl , It didn`t work.
```
// css/app.styl
px2rem(p)
    $fontSize = 37.5
    (p / $fontSize)rem
// component/test.vue
<style lang="stylus" type="text/stylus" scoped>
.ebook
    position: relative;   // 使用相对布局
    .read-wrapper
      .mask
        .left
          flex:  1 1 px2rem(100)
          background-color #faa0b1
</style>
```
So, I think the global css setting file(i.e. src/css/app.styl) is not work, please fix.  Thanks.

**Screenshots**

![image](https://user-images.githubusercontent.com/4034792/60691447-47828d80-9f02-11e9-932e-182078260fb3.png)

![image](https://user-images.githubusercontent.com/4034792/60691478-739e0e80-9f02-11e9-92e9-54c8fc5a6c79.png)

**Platform (please complete the following information):**
OS:         windows 7
Node: v8.12.0
NPM:    6.4.1
Yarn: 1.9.4
Browsers:  chrome 75.0.3770.100 x64
Quasar:  1.0.0-rc.7

**Comment by lucasfernog** [comment]
You pasted <style> tags into the app.styl file. Use only Stylus code there, as it is a pure .styl file. The code should be something like

```styl
// css/app.styl
px2rem(p)
    $fontSize = 37.5
    (p / $fontSize)rem
// component/test.vue
.ebook
    position: relative;   // 使用相对布局
    .read-wrapper
      .mask
        .left
          flex:  1 1 px2rem(100)
          background-color #faa0b1
```

Also, please use our Discord server for questions before issuing here, because you may find out that what you are experiencing is not a bug. 

Thank you.

**Comment by ryan3216** [comment]
Hi lucasfernog , 
I did not past <style> tags into the app.styl file.  Maybe I did not express clear.  
Please looked at my comment. It indicated where is the code  in.
For instance,  
```
// css/app.styl
px2rem(p)
    $fontSize = 37.5
    (p / $fontSize)rem
```
The comment of "// css/app.styl"  mean that the follow code is in css/app.styl  .

**Comment by ryan3216** [comment]
> Use

Hi lucasfernog ,
I did not paste <style> tags into the app.styl file. Maybe I did not express clear.
Please looked at my comment. It indicated where is the code in.
For instance,

```
// css/app.styl
px2rem(p)
    $fontSize = 37.5
    (p / $fontSize)rem
```
The comment of "// css/app.styl" mean that the follow code is in css/app.styl .

So, the follow code is in "component/test.vue" . I want to call px2rem() in test.vue. But it didn`t work.

```
// component/test.vue
<style lang="stylus" type="text/stylus" scoped>
.ebook
    position: relative;   // 使用相对布局
    .read-wrapper
      .mask
        .left
          flex:  1 1 px2rem(100)
          background-color #faa0b1
</style>
```

**Comment by webnoob** [comment]
2 things:

1. Try removing `scoped`
2. Add (just below the opening style tag) `// $` - This will force quasar to add the import variables to this section - I don't think it'll help in this case but I'm curious.

**Comment by webnoob** [comment]
In fact, as @lucasfernog pop into discord - it'll be easier to triage there.
