### ISSUE TITLE
Slider - issue with slides count on component initialize

### ISSUE THREAD

**Issue by danikane** [quasarframework/quasar#455]
Hi there, I noticed this weird bug (currently on 0.13.4).

When slider is loaded slidesNumber is uninitialized yet:
```
slidesNumber:0
```
As soon as any action is taken (full-screen, swipe, click on arrow) they get initialized.
```
slidesNumber:6
```
Dots are not shown yet because the component thinks there are no slides.
If you click on right arrow just after slider is ready will result in empty slide.
You can even experience this occurrence in 0.13.3 showcase:
http://quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/slider

Weird enough on 0.13.1 looks fine!
Thanks!

**Comment by rstoenescu** [comment]
This has just been fixed a few minutes ago in edge version.

**Comment by danikane** [comment]
Many thanks! After I started watching the repo I saw your discussion on the relevant PR.
Great job!
