### ISSUE TITLE
[docs] Cordova iOS command to deploy to simulator

### ISSUE THREAD

**Issue by mpacary** [quasarframework/quasar#4550]
On MacOS 10.14, with XCode 10.2, after creating an empty project using `quasar create`, installing cordova mode, adding platform iOS, when I do:

`quasar dev -m cordova -T ios -e iPhone-X,com.apple.CoreSimulator.SimRuntime.iOS-12-2`

The build fails with error:

> Error: Unhandled error. ('[ios-sim] Device id for device name "iPhone X" and runtime "com.apple.CoreSimulator.SimRuntime.iOS-12-2" could not be found, or is not available.\n')

When running `cordova run --list` I get a bunch of supported simulators like `iPhone-X, 12.2`

Then I’ve tried to run this, and build succeeds & simulator opens:

`quasar dev -m cordova -T ios -e "iPhone-X, 12.2"`
Maybe [this doc section](https://quasar.dev/quasar-cli/developing-mobile-apps/troubleshooting-and-tips#Device-type-not-found) should be updated?

See also: https://github.com/ios-control/ios-sim/issues/253

**Comment by rstoenescu** [comment]
Hi,

Docs are correct.
Only thing is that you shouldn't use a `space` character in the --e param.

Good: `quasar dev -m cordova -T ios -e iPhone-X,12.2`
Bad: `quasar dev -m cordova -T ios -e "iPhone-X, 12.2"`

**Comment by rstoenescu** [comment]
Updated docs though. Thank you.
