### ISSUE TITLE
[ios] using ionic wkwebview: error when enabling HTTPS 

### ISSUE THREAD

**Issue by mpacary** [quasarframework/quasar#4551]
**Describe the bug**
On a fresh new project, when using Ionic WKWebView plugin as described [here](https://quasar.dev/quasar-cli/developing-mobile-apps/preparation#Option-1%3A-Ionic-Webview-Plugin), enabling HTTPS in `quasar.conf`, and deploying to simulator with `quasar dev`, an error is displayed when at app loading (see screenshot) then the screen stays blank.

For search engines, here is the "plain text" error message:

> Failed to load webpage with error: The certificate for this server is invalid. You might be connecting to a server pretending to be "192.168.137.177" which could put your confidential information at risk.

No other info / error is displayed in Safari Developer console.

**Codepen/jsFiddle/Codesandbox (required)**
N/A (Mac required / CLI only)

**To Reproduce**
1. Create new project with `quasar create`
2. Add mode Cordova
3. Add platform iOS
4. [Add Ionic plugin for WKWebView](https://quasar.dev/quasar-cli/developing-mobile-apps/preparation#Option-1%3A-Ionic-Webview-Plugin)
5. Run `quasar dev -m cordova -T ios -e "iPhone-X, 12.2"`

**Expected behavior**
No error message, default Quasar App content showing (logo + drawer menu)

**Screenshots**
![image](https://user-images.githubusercontent.com/705663/60712529-88d16800-9f17-11e9-9e2e-e604bcc2c529.png)

**Platform (please complete the following information):**
OS: MacOS 10.14.5, XCode 10.2
quasar info gives
```
Operating System - Darwin(18.6.0) - darwin/x64
NodeJs - 12.5.0

Global packages
  NPM - 6.9.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.0.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.1 -- Quasar Framework local CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  ...
  @babel/core - 7.5.0 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Networking
  Host - UtilisateursAir.mshome.net
  en0 - 192.168.137.177
```

**Comment by mpacary** [comment]
Tested right now with [WKWebView plugin provided by Cordova](https://quasar.dev/quasar-cli/developing-mobile-apps/preparation#Option-2%3A-Cordova-WkWebviewEngine-Plugin), when enabling HTTPS I get a blank page at app loading, without any error message.

**Comment by rstoenescu** [comment]
It works without ionic webview or wkwebview.
Will investigate what is wrong for the two.

Thanks for reporting!

**Comment by mpacary** [comment]
You're welcome 😉

FWIW, [this issue from Ionic's GitHub](https://github.com/ionic-team/ionic-cli/issues/3305) might provide helpful info.

**Comment by rstoenescu** [comment]
Fixed in `@quasar/app` v1.0.2.
Thanks for reporting!

**Comment by mpacary** [comment]
Thanks for the very fast fix !! tested with `@quasar/app` v1.0.2, I can confirm that now running on dev mode with HTTPS enabled, does work as expected, with both WKWebView plugins 👏 👏

**Comment by rstoenescu** [comment]
Thanks for confirming! And enjoy Quasar :)

**Comment by rstoenescu** [comment]
If it's possible, please take a look at https://donate.quasar.dev
