### ISSUE TITLE
[v1] Cannot add class or style to QMenu

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#4553]
**Describe the bug**
Class and style attributes do not propagate to the QMenu. 

Trying to recreate the FAB to Menu Material Design concept: 
See *Transform into a menu with the related actions* section at [Material Design](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions)

[Video direct link](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1pdXG8K2i6IR9i5V5raflvDwuADXdUACM%2Ffab-transitions-menu-1.mp4)

**Codepen**
https://codepen.io/anon/pen/gNdwNX

**To Reproduce**
1. Open the Codepen.
2. Click on the FAB.
3. The menu scales from its center and its DOM element does not have the class that was added to the `<q-menu>` element.

**Expected behavior**
The menu has the "origin-bottom-right" class applied and the scale animation originates from the bottom right

**Platform**
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Yarn: 1.16.0
Browsers: Firefox
Quasar: 1.0.3
@quasar/app: 1.0.1

**Comment by metalsadman** [comment]
Why not use this tho https://quasar.dev/layout/floating-action-button#Introduction ?

**Comment by metalsadman** [comment]
Why not use this tho https://quasar.dev/layout/floating-action-button#Introduction https://quasar.dev/layout/floating-action-button#Example--With-QPageSticky?

**Comment by rstoenescu** [comment]
Hi,

Use `content-class` or `content-style` props. Always check the API cards too if you need something.

**Comment by kirschkern** [comment]
> Use `content-class` or `content-style` props. Always check the API cards too if you need something.

Good to know. 

NOTE: The latest API cards for qmenu doesn't contain these props as this seem to has changed in Quasar V2.
In V2 you may just use the class attribute.
There is a styling example here: [https://quasar.dev/vue-components/menu#sizing-and-styling](https://quasar.dev/vue-components/menu#sizing-and-styling)

For V1 the content-class prop is the way to go.
[https://v1.quasar.dev/vue-components/menu](https://v1.quasar.dev/vue-components/menu)

Cheers
