### ISSUE TITLE
Expose QBackdrop as a component or API or add as option for QMenu

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#4554]
**Is your feature request related to a problem? Please describe.**
Trying to recreate the FAB to Menu Material Design concept: 
See *Transform into a menu with the related actions* section at [Material Design](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions)

[Video direct link](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1pdXG8K2i6IR9i5V5raflvDwuADXdUACM%2Ffab-transitions-menu-1.mp4)

The Material Design concept has a backdrop behind the menu, but QMenu does not support this ability.

**Codepen**
https://codepen.io/anon/pen/gNdwNX

**Describe the solution you'd like**
It would be nice to have an easy way to add a backdrop behind the QMenu like in the Material Design video above. Either as an option on QMenu (like QDialog) or a separate component/API that could be called, or both.

**Describe alternatives you've considered**
Creating a custom backdrop solution based on the source code in QDialog.

**Comment by lucasfernog** [comment]
Hi @GordonBlahut , please take a look at this app extension: https://github.com/quasarframework/app-extension-qoverlay

Please join our Discord server if you have any other question.
