### ISSUE TITLE
Bring back Min and Max options for QDate

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4556]
The new Date picker is nice, including the possibility to pass a function as `options` to disable certains dates.
However the `min` and `max` options were useful. I don't need to let users browse through the months of 2020 and beyond, when I know that my max date is 2019 December 31st.
I wish `min` and `max` were brought back to the component to prevent going too far or too early in the calendar.
Thank you

**Comment by lucasfernog** [comment]
You can just use something like `:options="(date) => date <= 'my-max-date'"` instead of the min/max

**Comment by louisameline** [comment]
I already do, that's not the point. This is about blocking the calendar view beyond certain dates, not just preventing a date to be selected.

**Comment by tohagan** [comment]
Yes! I agree. This is an essential feature for many business apps that I work on.

**Comment by brianwhu** [comment]
I concur. The UI needs to respect date restrictions and disallow users from navigating into months/years that are not allowed. Instead of min and max, though, I'd rather have the UI follow the current, more dynamic `options` setting. Such would make it possible to build something like a date range picker.

**Comment by pdanpdan** [comment]
Closing this as it's really not necessary. Just pass the options function and it's all done.

**Comment by louisameline** [comment]
Please read this discussion as this has been discussed, and reopen. Thank you

**Comment by pdanpdan** [comment]
You want the user not to be able to navigate to some months?
I'll reopen it, but I don't see it as a good ideea.

**Comment by tohagan** [comment]
@pdanpdan From business cases I would disagree. we often wish to restrict a date to a limited period of time and thus disable dates outside that range.  Another example ... disallow a set of dates ... like weekends, bank holidays, public holidays.

**Comment by louisameline** [comment]
@tohagan disabling certain days is already possible, they get greyed and non-clickable.

@pdanpdan it's UX 101 to prevent browsing through useless interfaces. If the user can only book 3 months in advance for example, there is no point in letting him browse after that, it's just a waste of time to him, while it's obvious he can't when the calendar is blocked.

**Comment by leoelz** [comment]
This feature would help to reach this component
![image](https://user-images.githubusercontent.com/3853621/83969889-e64d0200-a8a8-11ea-9109-05e0b2d3bc6f.png)
I've made a [demo](https://leoelz.github.io/quasar/#/form/date) with a date range picker at bottom that would be improved with the max min options.

**Comment by rstoenescu** [comment]
New props (navigation-min-year-month and navigation-max-year-month) will be available in Quasar v1.13.0

**Comment by felipeHondaMatrix** [comment]
But what if I need to restrict the day too?

**Comment by leoelz** [comment]
> But what if I need to restrict the day too?

Hi @felipeHondaMatrix, maybe you should look at the `options` property
https://quasar.dev/vue-components/date#limiting-options

**Comment by felipeHondaMatrix** [comment]
Thx a lot @leoelz !
