### ISSUE TITLE
New build option for embedding widgets on legacy or WordPress sites.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#4559]
I think a new Widget build option would really add a competitive edge to Quasar as I believe this is a common requirement. 

**Is your feature request related to a problem? Please describe.**

Right now I'm developing an app which I need to run either standalone (SPA/PWA/AppStore) or as an embedded Widget on WordPress pages (e.g. pop up as a side bar for desktop or full screen on mobile devices).  

I've had other cases where I similarly needed to just replace a part of a legacy jQuery web site with a Vue widget (e.g. dashboard, timeline for a conference etc etc) so I think this is a common requirement for many Vue developers. 

**Describe the solution you'd like**

I'd like to see Quasar offer an additional build option designed specifically for embedding in legacy web sites with least number of build output files making insertion into the web site easier.  It needs to use fixed output file names that don't change between builds so that the WordPress team is not having to constantly update pages.

I think the best webpack output would be *single* JS+CSS files + *single* Vue run-time JS/CSS files (4 files in total) all **with fixed file names**. Another useful option would be just one single JS file. I think there's benefit in splitting out the Vue run-time as its typically the largest part and if we're embedding multiple widgets on a page or placing different widgets on different WordPress/legacy web pages they can then share the cached run-time JS/CSS files. You might want a Widget build option to place vendor exports into either the app or runtime build files as I think there are cases for both.

To embed the widget you add a `<div id="app">` element onto the legacy web site and add references to the output build files on each legacy web page.  We don't use the `index.template.html` file.  I'd also typically rename `app` ID with a new widget ID. I think you really want the Widget builder to do this so other builder wrappers (SPA/PWA etc) are not affected by this change.

I think you'd  want a way to configure each instance of the widget (args) and ideally also be able to call methods or emit events from to/from legacy code via something like a Widget.vue wrapper - much like with Electron and Cordova wrappers.  That's not needed for v1 but nice to have on the Roadmap.

**Describe alternatives you've considered**

- For a chat app project I found this example demo app for which the webpack build outputs a singe JS file.  https://github.com/mattmezza/vue-beautiful-chat/tree/master/demo   This project includes a Launcher.vue component that solves the pop up side bar (desktop) or full screen (mobile) trick. Something similar in Quasar would compliment a Widget builder.  I found I needed to adjust position/margin on mobiles to work with existing WordPress mobile top menu.

- [Vuidget](https://itnext.io/vuidget-how-to-create-an-embeddable-vue-js-widget-with-vue-custom-element-674bdcb96b97) uses a custom element.  This works for some projects but I'm dealing with Legacy Land and old browsers on public web sites. You could polyfill to support custom elements but that just unnecessarily complicates the problem when there's a obvious simpler solution ( `<div id="app" />` ) .  However this article confirms the need for a Widget build type!

- [Portal-Vue](https://portal-vue.linusb.org/) is also worth a look.

- iframe an SPA build - I need to make widgets interactive directly on the page so an iframe solution just complicates the problem as I now have to split app logic into Vue App iframe and non-Vue code that resides on each legacy page. Communications between the two is very messy and I'm stuck doing it in old school JS.  iframes have the benefit of easily supporting client side routing and a dynamic iframe can lazy loading your SPA app - so they may yet be a preferred wrapper option if you generate the embedding and communications logic with your Widget.vue wrapper in the builder.

**Additional context**

I suspect there's a performance benefit in keeping the CSS files separate (not including in JS file). If I'm wrong then you'd just merge them into the JS files and reduce the build file counts.

You want to ensure that you can still test the legacy site with a dev build (hot reloading) embedded widget.

**Icing on the Cake**

Include WordPress/Joomla plugins to embed your new widget.  
Now you've tapped into a whole new market!

**Comment by nothingismagick** [comment]
One single JS file is ironically the holy grail.

**Comment by panstromek** [comment]
Just to note, we recently used the iframe solution to embed Quasar app inside Magento site.

It's kinda messy but does the job. The most problematic part is syncing dimensions of the app + syncing the route with postMessage communitation. Luckily for us, we didn't need any complicated communitation between the two. Other than that, it mostly works fine, just Safari is constantly messing up something.

**Comment by pdanpdan** [comment]
You can also use the UMD version of quasar. No other option except that or iframes.
