### ISSUE TITLE
apk is quite big?

### ISSUE THREAD

**Issue by fayland** [quasarframework/quasar#456]
Well, just follow something like

```
quasar init xxxxx
cd xxxxx 
npm install
quasar build
quasar wrap cordova
? Install Crosswalk WebView plugin for Android Apps (HIGHLY recommended) Yes
cd cordova 
cordova platform add android
cordova build android
```

and the final apk size is

 33M	/Users/fayland/tmp/xxxxx/cordova/platforms/android/build/outputs/apk/android-x86-debug.apk

why it's so big? I was using framework7 and it's only less than 3M.

**Comment by rstoenescu** [comment]
Because of Crosswalk, which will become obsolete quite soon. Crosswalk is used for compatibility with older Android versions. If you don't care about Android 4.X, then skip Crosswalk and your apk will be comparable to framework7's.

**Comment by fayland** [comment]
Yes. just tried.

without that, it's

2.5M	/Users/fayland/tmp/xxxxx/cordova/platforms/android/build/outputs/apk/android-debug.apk

Thanks.
