### ISSUE TITLE
[docs] QSelect : placeholder

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4561]
The placeholder prop of QSelect is currently not documented. Where is the API documentation in the repo? I can't find it to create a PR. Thank you.

**Comment by webnoob** [comment]
It's auto generated based on JSON files for each component:

https://github.com/quasarframework/quasar/blob/dev/ui/src/components/select/QSelect.json

**Comment by pdanpdan** [comment]
It's already documented: https://quasar.dev/vue-components/select#Native-attributes-with-use-input

**Comment by louisameline** [comment]
There's no mention of it because it's a native attribute, ok I get it. It's a bit annoying  
though when you're in a hurry because you search for "placeholder" in the page with ctrl+f and find nothing. I'd personaly add the word there but it's up to you. Thank you

**Comment by jean-moldovan** [comment]
Related: https://github.com/quasarframework/quasar/issues/4255

**Comment by jean-moldovan** [comment]
Native select does not seem to have 'placeholder' attr.

**Comment by rstoenescu** [comment]
@jean-moldovan if you have QSelect with 'use-input' the native attributes get on the underlying input, which has 'placeholder'.

**Comment by rstoenescu** [comment]
Will add more info for this on docs, as suggested.
