### ISSUE TITLE
QSelect: bad UX when filtering

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4565]
I just migrated to v1. Whole lots of good new stuff! But the new design for filtering on QSelect kind of lets me down. So I have my QSelect:

![image](https://user-images.githubusercontent.com/371814/60759763-74ca5b00-a02a-11e9-8cb5-3073c2f1c39a.png)

And when I click on it for the first time, it shows my options. It's visually ugly by default but at least the UX is still good.

![image](https://user-images.githubusercontent.com/371814/60759778-a93e1700-a02a-11e9-84ce-c2a6d8e31bfb.png)

So I chose Alaska. Then I tried to select another one and found this:

![image](https://user-images.githubusercontent.com/371814/60759839-b8719480-a02b-11e9-8d38-a64553458074.png)

I entered "backspace" hoping that it would clear the field to type something else, and I thought there was a bug because it didn't do anything.

I eventually started typing, and saw that the filter value shows up next to the selected value:

![image](https://user-images.githubusercontent.com/371814/60759862-130af080-a02c-11e9-973b-688b1c4778cf.png)

There is no visual difference here between the selected value and the filtering value, it is confusing. It makes me believe I am in a multiple selection field and that I'm entering a second value. It should be clearly stated that it's a filter feature.

Also, there is no easy way to close when I don't want to tap an option, because it takes most of the screen on mobile and there is no close button, and the Enter button of the phone does not close it. We have to tap at the edge of the screen, this is not handy.

The filter feature in Quasar was clearer before v1 in my opinion. The selected value was hidden (just highlighted in the list), the filter feature was obvious and it was easy to step out of it:

![image](https://user-images.githubusercontent.com/371814/60760027-857cd000-a02e-11e9-9560-31234e5645ea.png)

Thank you

**Comment by rstoenescu** [comment]
Hi,

Then use `hide-selected` prop. Or `use-chips`. Please take a closer look at all the examples on QSelect page and at its API card.

**Comment by louisameline** [comment]
Thanks for the fast response, but I did spend the whole day on the doc of v1.
`use-chips` is not appropriate when you want a single value.
`hide-selected` hides the selected value when selecting a new value, but I want the value to be shown in the normal display state (I'm not sure who would want to hide the selected value then?).
If nothing is going to be done about this, I'll have to work without a QSelect on this one.
Thanks

**Comment by rstoenescu** [comment]
I assure you that there are use cases for each prop :)

Are you looking for this? https://quasar.dev/vue-components/select#Example--Basic-autocomplete
Notice `fill-input`.

**Comment by louisameline** [comment]
It has its pros and cons. But it's still not good enough, let me explain.

![image](https://user-images.githubusercontent.com/371814/60761599-55442a00-a04c-11e9-81cd-c82036aa4b1f.png)

Pros:
-  The ability to delete the word "Facebook" and type another one is more intuitive than typing a filter next to it (like my screenshot with Alaska)

Cons:
- I have to delete "Facebook" myself before I can type something else. If I clicked on the field in the first place, it was obviously to change its value, so I wish Facebook was cleared without user interaction
- If I add `clearable` to make it easier, it adds an icon, but I wish it wasn't there when the select is not focused (only when the options are displayed). And ideally I want to clear the filter, not the model...
- I tried to empty the model upon the `@filter` event to clear immediately, it doesn't work properly. The clear icon  is removed but the values stays in the field.
- If I want a label/hint/prefix/placeholder/icon in the field, I also wish it wasn't there when the select is not focused

I think that right now qSelect is no longer the solution for me, although it was a fine solution before v1.
I think I'll use my own instead. I've done it for something else, it looks like this:

![image](https://user-images.githubusercontent.com/371814/60761885-b1aa4800-a052-11e9-843b-17e7da047c6a.png)

I'll adapt it to make it look more compact and contextualized, like a select.

**Comment by rstoenescu** [comment]
You could use the slots to define a custom clear button that only shows when QSelect is focused and deletes the filter:

1. A QIcon on "append" slot.
2. Add a class (for the sake of the example: "X") to the QIcon and another one to the QSelect (let's say "Y"), then add to your CSS: `Y:not(.q-field--focused) Y { display: none }`
3. Attach a Vue ref on QSelect (let's say "myRef") and an event to your QIcon for `@click` that points to a method which essentially does `this.$refs.myRef.updateInputValue()`

**Comment by louisameline** [comment]
I went for a QPopupProxy to emulate a QSelect. I have all control over without the feeling to hack my way through QSelect. Thank you for your help though.

![image](https://user-images.githubusercontent.com/371814/60771388-d7cdf780-a0e7-11e9-8c9c-5fe7fef92e65.png)

**Comment by nothingismagick** [comment]
@louisameline - that's great. I was wondering if you would share your code with us. I am considering making a "QSimpleSelect" - and this sounds like a legit starting point.

**Comment by louisameline** [comment]
@nothingismagick sure, something like this: https://codepen.io/anon/pen/vqoJyN?&editable=true&editors=101

**Comment by nothingismagick** [comment]
@louisameline - thankyou
