### ISSUE TITLE
QSelect: bug when using both `use-input` and `emit-value`

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4567]
`use-input` and `map-options` + `emit-value` don't work well together.

Reproduce: 
1. go to https://codepen.io/anon/pen/rEZEej?&editable=true&editors=101
1. select a value
1. start typing another value

See how the model is no longer displayed by its label but by its value.

![image](https://user-images.githubusercontent.com/371814/60760606-3fc50500-a038-11e9-8048-087103276b8a.png)

**Comment by rstoenescu** [comment]
Hi,

Use `map-options` too then. Otherwise QSelect displays exactly what the model is.
Please take a closer look at all the examples on QSelect page and at its API card.

**Comment by rstoenescu** [comment]
Wait. I misread. Bug confirmed. Will fix it.

**Comment by rstoenescu** [comment]
Started investigated. This is a misusage. QSelect should be used without `emit-value`, since options are dynamically changed and so at some point QSelect won't have any mapping available for current selected value.

https://codepen.io/rstoenescu/pen/LKgbZN?&editable=true&editors=101

**Comment by louisameline** [comment]
Ok I see. Might be worth a note in the documentation. If you ask me, the fact that the filter feature of QSelect asks us to edit the options directly doesn't sound right. Anyway I won't rely on QSelect for that kind of things anymore, a QPopupProxy and some custom code is by far my preferred choice. Thank you
