### ISSUE TITLE
QInput of type="number" produces data of string type

### ISSUE THREAD

**Issue by igorvolnyi** [quasarframework/quasar#4569]
I create QInput in my component, specify type="number", v-model="data.number", everything as documented. I type something like 111 (obviously a number). But when I submit, data.number appears to be a string '111'.
Verified using console.debug(typeof this.data.number).

**Comment by lucasfernog** [comment]
Hi Igor,

You need to use `v-model.number="data.number"` so Vue converts your model to numeric values.

**Comment by lucasfernog** [comment]
https://vuejs.org/v2/guide/forms.html#number

**Comment by igorvolnyi** [comment]
Oh... Umm... Okay.
