### ISSUE TITLE
Wrong Platform detection for Android Edge browser

### ISSUE THREAD

**Issue by lucasfernog** [quasarframework/quasar#4573]
**Describe the bug**
Quasar platform detection is detecting Edge as Chrome on Android

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. Go to Platform on Quasar docs
2. Go to "your platform" section

**Expected behavior**
Platform should detect browser as Edge

**Screenshots**
![WhatsApp Image 2019-07-07 at 22 57 24](https://user-images.githubusercontent.com/20051258/60778335-0e6a3900-a10d-11e9-805f-e023cecc228c.jpeg)

**Platform (please complete the following information):**
OS: Android
Node:
NPM:
Yarn:
Browsers: Edge
iOS:
Android: 7.1

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.4
