### ISSUE TITLE
[docs] How can I update from v0.17 to v1.0

### ISSUE THREAD

**Issue by icksky** [quasarframework/quasar#4575]
congratulations for the v1.0.0 stable has been released.
I just completed a project with v0.17.  and I wonder how to update 0.17 to the newest version.
Thanks.

**Comment by rstoenescu** [comment]
Hi,

https://quasar.dev/start/upgrade-guide

**Comment by nothingismagick** [comment]
But make sure to scroll past the top part to this:
https://quasar.dev/start/upgrade-guide#Best-Practices
