### ISSUE TITLE
input autogrow (textarea) shows a scrollbar on high dpi displays

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#4580]
With a high dpi display and a scaling of 125% on Windows, input controls with autogrow and a label, show a scrollbar by default.

https://codepen.io/anon/pen/EBOYJK

##### 100% scaling
![chrome_x2Un1kLF6l](https://user-images.githubusercontent.com/10562635/60810530-a7d92f80-a18d-11e9-97bb-966e2f9276e9.png)

#### 125% scaling
![chrome_DCxqfABesQ](https://user-images.githubusercontent.com/10562635/60810581-bf181d00-a18d-11e9-99df-d7182aa6c279.png)

OS: Windows 10 (1809)
Node: 11.13.0
NPM: n/a
Yarn: 1.16.0
Browsers: Chrome 75.0.3770.100 (Official Build) (64-bit)

**Comment by scarry1992** [comment]
+1, if q-input drawed first time in hidden element I get same situation.

**Comment by scarry1992** [comment]
temporary fix for me:
```css
.q-textarea--fix.q-textarea.q-field--labeled textarea.q-field__native
    min-height 27px
```

**Comment by momt99** [comment]
my solution
`.q-textarea--autogrow .q-field__native {
  resize: none;
  overflow: hidden;
}`

**Comment by rstoenescu** [comment]
Is this still valid with latest?
