### ISSUE TITLE
Caption in QExpansionItem does not respect colors used in `header-class`

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#4581]
**Describe the bug**
In code, create a QExpansionItem component. Add `header-class` with text and background colors.
Example:
```
        <q-expansion-item
          expand-separator
          default-opened
          group="somegroup"
          icon="fas fa-cogs"
          label="The Label"
          caption="The Caption"
          header-class="text-white bg-primary"
        >
```

In this case, the background is blue, the label text and icon are white, but the caption is black.

![image](https://user-images.githubusercontent.com/10262924/60812756-76417380-a14f-11e9-8ffa-01fc5e6af1e3.png)

It is caused by this in quasar.styl:
```
    &--caption
      color rgba(0, 0, 0, .54)
```
Of course, someone can override this with CSS, but the expected result would be the caption would adhere to the passed color in `header-class` property.

**Comment by rstoenescu** [comment]
`<q-expansion-item dark`

**Comment by hawkeye64** [comment]
ugh, of course.

**Comment by mickey58github** [comment]
Has this really been fixed? I still get expansion items that have captions in black when labels are white, with Quasar 1.5.11.

**Comment by rstoenescu** [comment]
@mickey58github if you're asking this then something is misunderstood. pls supply a codepen

**Comment by mickey58github** [comment]
@rstoenescu - please have a look here: [https://codepen.io/mickey58/pen/XWJVdoa](https://codepen.io/mickey58/pen/XWJVdoa)

**Comment by hawkeye64** [comment]
@mickey58github Add property 'dark'
https://codepen.io/Hawkeye64/pen/KKwZMpa

**Comment by mickey58github** [comment]
Thanks - sorry, I misunderstood that one needs to specify "dark" as a prop to get it. 

It would be worth to mention in the API doc for q-expansion-item that "dark" has this intended "side-effect" on the caption color, [https://quasar.dev/vue-components/expansion-item#QExpansionItem-API](url)

**Comment by rstoenescu** [comment]
@hawkeye64 `:dark="$q.dark.isActive"` is implicit
