### ISSUE TITLE
Shadow not applied in Toolbar inside Card

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#4583]
**Describe the bug**
Shadow in the QToolbar inside the QCard doesn't work

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/embed/codesandbox-app-6kshl

**To Reproduce**
1. Create a card with a toolbarn in top
2. Apply shadow class to the toolbar

**Expected behavior**
The toolbar have a shadow around her

**Screenshots**
This is without shadow
![image](https://user-images.githubusercontent.com/19597708/60816308-ba596600-a199-11e9-88fe-64f7037f8944.png)

The result may be like this(vuetify)
![image](https://user-images.githubusercontent.com/19597708/60816327-cb09dc00-a199-11e9-8e4c-a3930942e758.png)

**Comment by rstoenescu** [comment]
Hi,

Just wrap the toolbar in a div with `overflow-hidden` CSS class (equivalent to `overflow: hidden`). The explanation is that due to other QCard features and use-cases, shadow is disabled for direct descendants of QCard.

```html
<div class="overflow-hidden">
  <q-toolbar class="bg-primary text-white q-mb-md q-pa-md q-pl-lg shadow-4" align="left">
    <q-toolbar-title>Login</q-toolbar-title>
    <q-space></q-space>
  </q-toolbar>
</div>
```
