### ISSUE TITLE
[v1] Possible touch/drag issue in Firefox when using QPullToRefresh or QSlideItem around QItem with route

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#4585]
**Describe the bug**
In Firefox (Chrome seems to be fine) when using `QSlideItem` around a `QItem` that has a route specified, the slide/swipe feature is very difficult to operate. The drag gets stick after a few pixels and does not resume until you release the mouse button, at which point it oddly resumes without the mouse button pressed.  
  
Not sure if this is something with my machine, or I'm doing something wrong, or if it's a bug with Firefox, or Quasar. 

**Codepen/jsFiddle/Codesandbox (required)**
Codesandbox: https://xek67.sse.codesandbox.io/list

**To Reproduce**
1. Open the above link in Firefox (I'm using 67.0.4).
2. Try swiping left on a odd-numbered item (no route), should work fine.
3. Try swiping left on an even-numbered items (with route), drag seems to get interrupted. If you release the mouse button, then the drag continues without the mouse button pressed.

**Expected behavior**
Slide action should work even if a route is specified.

**Platform (please complete the following information):**
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Yarn: 1.16.0
Browsers: Mozilla Firefox 67.0.4 (64-bit)

**Additional context**
Seem to have a similar issue when using `QPullToRefresh` around a `QList` with routed `QItem`s too.

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.4
