### ISSUE TITLE
Bug: App-Extension compiling template strings and causing issues

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#4586]
**Describe the bug**
It seems like app extension 'install' is causing 'app-extension/templates' components with `template strings` to fail on installation when it is asked to render the templates.

Take a look at the component definition in /quasar-app-extension-my-ext/src/templates/src/TheComponent.vue

eg in codesandbox: 
```js
// app extension component in: src/templates/src/components/TheComponent.vue
<template>
  <div :id="`${proper}TheID`">
    Any interpolation is going to cause the issue as it will try to interpolate outside of
    Vue VM scope ie: "proper" instead of "vm.proper"
    The above :id=... will coz the issue so as that => {{ ` interpolated in ES6 template string ${proper}` }}
  </div>
</template>

<script>
export default {
  name: 'TheComponent',

  data() {
    return {
      proper: 'yes'
    }
  }
}
</script>

```

That is normal and works in a normal component. But trying to use this in an app-extension component will cause that component not to render and fail the installation as it throws an error saying `proper` is undefined. It's trying to use `proper` during rendering of which it shouldn't. It should just leave it as is and render it without interpolating it. So escaping or something is needed before the render function is called.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/codesandbox-app-iffur
I have done so, but it seems like codepan is limited. I can't make the example app find the app-extension installation in the sandbox. It links sandboxed packages fine, but can't find them when trying to use them as with `quasar ext invoke my-ext`. But you can take a look and you will quickly see what's going on.

**To Reproduce**
1. create an app-extension with that component
2. create a test app
3. install the component into the test app
4. now invoke the ext using `quasar ext invoke my-ext`
5. issue should occur

```js
(node:15287) UnhandledPromiseRejectionWarning:   ReferenceError: proper is not defined
  
  
  - Extension.js:78 renderFolders
    [projects]/[@quasar]/app/lib/app-extension/Extension.js:78:36
  
  - next_tick.js:77 process.internalTickCallback
    internal/process/next_tick.js:77:7
  

(node:15287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
                                                               
```

**Expected behavior**
There shouldn't be any error that interpolation is supposed to happen as the component use that string instead of when rendering.

Quasar v1.0.3

**Comment by rstoenescu** [comment]
Thank you for reporting!
Fix will be available in `@quasar/app` 1.0.3
