### ISSUE TITLE
consider adding circle checkbox?

### ISSUE THREAD

**Issue by panzailiang** [quasarframework/quasar#4587]
I see some great app using circle checkbox. Are quasar going to consider add the freature of circle checkbox?

**Comment by smolinari** [comment]
A round checkbox possible with a small change in the css.

https://codepen.io/smolinari/pen/gNQBWW

Scott

**Comment by panzailiang** [comment]
Thx for the trick. But I think the UI effect can be more beautiful if as the checkbox in ios mode in previous quasar version.

**Comment by smolinari** [comment]
And, ios "theming" is up to devland now as of v1.0. So, it's a matter of doing it on your own. I highly doubt round check boxes will become a standard part of Quasar.  

https://material.io/design/components/selection-controls.html

Material UI denotes clearly between checkboxes and radio buttons by making checkboxes square and radios round. If you want it any differently, it's up to you. 

Scott

**Comment by rstoenescu** [comment]
Quasar UI is a Material one at its base, with the default design. There will be iOS themes and more (installable as app extensions in the near future), but until then, if you need something tweaked you can now easily do, since the CSS is years ahead in customization ability vs 0.17.
