### ISSUE TITLE
[bug] QResizeObserver

### ISSUE THREAD

**Issue by KnorienChang** [quasarframework/quasar#4588]
[Vue warn]: Error in beforeDestroy hook: "TypeError: this.curDocView.removeEventListener is not a function. (In 'this.curDocView.removeEventListener('resize', this.trigger, _utils_event_js__WEBPACK_IMPORTED_MODULE_2__["listenOpts"].passive)', 'this.curDocView.removeEventListener' is undefined)"

found in

---> <QResizeObserver>
       <QHeader>
         <QLayout>
           <LayoutMain> at src/layouts/Main.vue
             <App> at src/App.vue
               <Root>

jump pages with vue-router

**Screenshots**
https://static.knorien.cn/others/WeChat140cf8cad51a64f9ec66d1d2cff848be.png

**Platform (please complete the following information):**
OS:macOS Mojave v10.14.5
Node:v10.16.0
NPM:6.9.0
Yarn:1.17.0(default)
Browsers:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
iOS:iOSv10.3.3(14G60)

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.4
