### ISSUE TITLE
QTooltip ignores model

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#4595]
**Describe the bug**
I want to manually control when the tooltip is shown through v-model. I don't want it to attach event listeners to any DOM element. So I set v-bind:target="false" and expect to toggle the tooltip via the model. Unfortunately the tooltip remains hidden, regardless of model value.

In addition, if I leave the target prop to its default value (true) and set v-bind:value="true" then the tooltip is initially shown. But if I hover over the parent/reference element, then the tooltip reverts to its default behavior of showing on mouse over and hiding on mouse out.

It seems that the model is not the source of truth for whether the tooltip is shown or hidden.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/RzEWKQ?editors=1010

**Platform (please complete the following information):**
Quasar: v.1.0.3
OS: Linux
Browsers: Chrome, Firefox, Opera

**Comment by louisameline** [comment]
For the record, I stumbled maybe on the same bug. I set `:target=false` and there was no way to make it show up with the methods.

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6.
