### ISSUE TITLE
[BUG] npm install gets stuck

### ISSUE THREAD

**Issue by micheleangioni** [quasarframework/quasar#460]
Hi,
I'm trying to run `npm install` with a fresh installation of the last version of Quasar, but it gets stuck at extract:core-js and never completes..

Quasar: v0.13.6
OS: Ubuntu 16.04.2
Node: 6.10.0
NPM: 3.10.10

```
:~/XXX$ quasar init app
:~/XXX$ npm install
[...]
:/ extract:core-js: verb gentlyRm don't care about contents; nuking /XXX
```

Can someone reproduce the problem?

Thanks

**Comment by rstoenescu** [comment]
Happens from time to time. This is an issue with NPM servers...

**Comment by micheleangioni** [comment]
Thanks for the super fast reply, I'm quite astonished that NPM has such problems... maybe you could try to get in contact with them to find some sort of solution.
Thanks again for the explanation, I just hope it gets fixed soon!

**Comment by rstoenescu** [comment]
It usually gets fixed in a day or so. Will try to contact them. This is not a problem with Quasar specifically. Can be with any package. Read the github page of Material Icons.. it's one similar issue reported there with A LOT of people complaining :(

**Comment by micheleangioni** [comment]
Ok, really astonished by this.. but in this exact moment it seems it completed the `npm install` that I left stuck several minutes ago! This time probably they have already fixed it, or maybe they have some sort of queue or are exceeding their current server capacity to handle requests.

**Comment by danikane** [comment]
It may happen if npm eats up all your memory.

**Comment by micheleangioni** [comment]
@danikane interesting, that might be the reason
