### ISSUE TITLE
ExpansionItem ignores active-class when active state

### ISSUE THREAD

**Issue by onurkose** [quasarframework/quasar#4602]
**Describe the bug**
Expansion item may be turn into active state just like the list item component. But it ignores active-class prop when active state.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/RzEXjd

**To Reproduce**
1. Just look, very east to notice

**Expected behavior**
When expansion item's active prop is true, it's expected to have the active-class prop also.

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers: FF, Safari
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Hi,

The codepen is the default one. Hit "fork", make changes then hit "save" and share it again here, please. Thanks in advance.

**Comment by onurkose** [comment]
Sorry, forgot to save the pen. Now it's ok.

**Comment by rstoenescu** [comment]
Thank you for updating the codepen.

`active-class` relates to when you apply a route link to it (`to` prop), not when you toggle the QExpansionItem

**Comment by rstoenescu** [comment]
Also, there is no `active` prop.
