### ISSUE TITLE
All the document of Developing Cordova Apps pages are broken

### ISSUE THREAD

**Issue by stanleylu3216** [quasarframework/quasar#4604]
**Describe the bug**
`https://quasar.dev/quasar-cli/developing-cordova-apps/*`
All the cordova-apps pages are broken

![image](https://user-images.githubusercontent.com/48779712/60960424-8a969380-a33c-11e9-9d82-ab69b68101f4.png)

**Comment by nothingismagick** [comment]
confirmed. thanks for reporting!

>

**Comment by nothingismagick** [comment]
![Screen Shot 2019-07-10 at 12 13 20](https://user-images.githubusercontent.com/35242872/60961336-34116100-a30c-11e9-872e-d44c0925edd5.png)

**Comment by nothingismagick** [comment]
the folder name was changed to 

docs/src/pages/quasar-cli/developing-**mobile**-apps

**Comment by nothingismagick** [comment]
Changing this back to

docs/src/pages/quasar-cli/developing-**cordova**-apps

is a confirmed fix

**Comment by nothingismagick** [comment]
Fixed. https://github.com/quasarframework/quasar/commit/219db1d6381425361d686d3b7de635e9cc6f99d0

**Comment by nothingismagick** [comment]
Thankyou @stanleylu3216 for the warning!

**Comment by nothingismagick** [comment]
Deploying now.

**Comment by rstoenescu** [comment]
Deployed.
