### ISSUE TITLE
QDialog & VueRouter nested routes duplicate

### ISSUE THREAD

**Issue by AjiTae** [quasarframework/quasar#4608]
**Describe the bug**
When we have nested router-view's inside q-dialog, the parent route component is somehow duplicated.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/MMLjMv?editors=1010

**To Reproduce**
Open codepen example, click "show dialog & simple div".

**Expected behavior**
"simple div" in the codepen example.

**Platform (please complete the following information):**
any

**Additional context**
Maybe some VueRouter bug, but I don't think so.

**Comment by rstoenescu** [comment]
Hi,

QDialog is not meant to be used with `<router-link>`. It's not supported and can't be, due to the fact it is required to use Quasar Portal to render elsewhere on the DOM (required otherwise iOS would break completely). Sorry for any inconvenience.
