### ISSUE TITLE
QDrawer leaves space on safari Mac OS X and iPad iOS when opening and closing.

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#4611]
**Describe the bug**
When opening and closing the drawer on iPad and Mac OS x Safari, the page leaves a space to the left on the contained QPage.

**Expected behavior**
I expect the page to slide back into place.

**Movie**
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/MxEw6CyPJa4/0.jpg)](https://youtu.be/MxEw6CyPJa4)

**Platform (please complete the following information):**
Browsers: Safari
iOS: Yes

**Comment by rstoenescu** [comment]
That's not an empty space. That's Safari with an empty scrollbar.

**Comment by whoacowboy** [comment]
@rstoenescu Sorry, it isn't. The space will expand the more you open and close the QDrawer. This behavior only happens on Safari.

**Comment by rstoenescu** [comment]
Please supply a jsFiddle. Thank you.

**Comment by whoacowboy** [comment]
@rstoenescu 

[Code Sandbox](https://codesandbox.io/s/codesandbox-app-tohdi)

**Comment by rstoenescu** [comment]
Thank you. I see what you mean now. This is a Safari browser rendering bug. Will investigate how to workaround it.

**Comment by whoacowboy** [comment]
I think so too. Thanks.

**Comment by nothingismagick** [comment]
Can confirm that it happens as described on iOS and Safari.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix (along with a perf improvement) will be available in 1.0.5.
