### ISSUE TITLE
Load icons from individual svg as opposed to woff

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#4612]
**Is your feature request related to a problem? Please describe.**
I would like to mix and match some icons across various libraries, material, ion, fa etc. With the current method you have to load the entire font file. 

**Describe the solution you'd like**
I would use a similar approach as these libraries.
https://github.com/robcresswell/vue-material-design-icons
https://github.com/mazipan/vue-ionicons
https://github.com/FortAwesome/vue-fontawesome

**Describe alternatives you've considered**
I use the above libraries and do not use the QIcon which lightens my load-time considerably.

**Comment by nothingismagick** [comment]
This is something @hawkeye64 and I have discussed. Have you seen the QIcon App Extension?

https://quasarframework.github.io/app-extension-qiconpicker/docs

Maybe this issue is a better fit there at that repo.

**Comment by whoacowboy** [comment]
@nothingismagick That looks cool but it feels a bit overkill. 

It would be awesome if we could add to the QIcon component.
```
<q-icon name="fas fa-heart-broken" svg></q-icon>
<q-icon name="ion-ios-heart" svg></q-icon>
```
or create a QIconSVG.

**Comment by nothingismagick** [comment]
The point is that this is not something that I see us adding to core as its
natural place in the ecosystem is in an app extension.

>

**Comment by whoacowboy** [comment]
Understood. 

I think if we are mindful of the load times for the core app it will make Quasar a better framework, so please keep it in the back of your mind when you are architecting future versions because this feels like an easy win.

Thanks, james

**Comment by nothingismagick** [comment]
> If we are mindful of load times
I challenge you to find such a full featured framework that cares so much about load times. Everything we do screams performance. If it feels like an easy win, then please evaluate the process for making an app extension and show us how easy it is. I really look forward to seeing it.

:)

**Comment by whoacowboy** [comment]
@nothingismagick I did not mean to offend. I think Quasar is a fantastic framework. 

Right now I have a solution that meets my needs and a tight deadline. Once I have some time I will create one.

**Comment by nothingismagick** [comment]
No offense taken - it's just that we really do care about performance. I'd love to review your work if you come up with a solid app-extension!

**Comment by whoacowboy** [comment]
@nothingismagick That would be great. Thanks again for checking this out.

**Comment by tohagan** [comment]
I'm finding that font files frequently are a key reason I get lower lighthouse scores. I'd guess you can use [IconMoon](https://icomoon.io/) to manually fix this but it would be a very cool extension to identify all the icons used in a Quasar app, top up the list with any dynamically selected icons and then extract just the ones in use from each font file and patch them into Quasar so they "just work" using the same names.  

[Font blast](https://github.com/eugene1g/font-blast) can convert a font file into individual SVGs so might be handy for this.

**Comment by rstoenescu** [comment]
RFC to watch: https://github.com/quasarframework/quasar/issues/6027
