### ISSUE TITLE
Header on page

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#4613]
It's good to have on option to set the header on page liker overlay

![Image of Yaktocat](https://miro.medium.com/max/1200/1*xORrYQsY266q2yhcLHpqXw.png)

**Comment by rstoenescu** [comment]
You mean, like this: https://quasar.dev/layout/gallery/whatsapp
Click on "source" to see it.

Layout > [Layout Gallery](https://quasar.dev/layout/gallery) in docs.

**Comment by miladmeidanshahi** [comment]
like this exactly https://codepen.io/miladmeidanshahi/pen/zVeaNL

**Comment by nothingismagick** [comment]
Hi @miladmeidanshahi - Quasar has a very robust system called App Extensions where you can build this kind of thing yourself. Its incredibly simple and extremely powerful.

https://quasar.dev/app-extensions/introduction

**Comment by rstoenescu** [comment]
Hi @miladmeidanshahi ,

Not sure what you are asking. Use Quasar's [grid](https://quasar.dev/layout/grid/introduction-to-flexbox) system. And if you want the boxed layout like in your picture, you got https://quasar.dev/layout/gallery/whatsapp as example.

You can get help on the above from our community on [discord](https://chat.quasar.dev) or [forum](https://forum.quasar.dev) if you get stuck. Github tickets are to be used for reporting bugs. Thank you.

**Comment by lucasfernog** [comment]
I guess he means transparent and fixed at top... something like 2 Quasar CSS classes does that, isn't it?

**Comment by miladmeidanshahi** [comment]
@rstoenescu @lucasfernog
I don't think so can be solved by the grid system
please check this link https://codepen.io/miladmeidanshahi/pen/zVeaNL

**Comment by arcadeJHS** [comment]
I had a similar requirement, and solved it this way: https://codepen.io/arcadejhs/pen/gObvKBB
