### ISSUE TITLE
QDrawer artifacts at iOS/Android

### ISSUE THREAD

**Issue by Sfinx** [quasarframework/quasar#4614]
Using the stock default app at mobile. Build for iOS/Android. Run both apps in appropriate emulator. Press Menu button to open left drawer, next close it by pressing at some other area. After some time you will get this:

![Screenshot_20190710-224315](https://user-images.githubusercontent.com/1393676/61003177-ff34f680-a36b-11e9-9164-a3784b0cfb91.png)

Node: 12.6.0
NPM: 6.10.0
Browsers: stock Cordova
iOS: > 11
Android: 7.1.1
Latest Quasar & App (1.0.4)

The iOS behaviour is reproducable nearly each click with no DevTools connected. The Android behaviour is reproducable after 5-10 drawers click only when remote Chrome DevTools connected and screencast  is enabled. Can't reproduce this artifact at Android with disabled screencast in Chrome DevTools.

**Comment by pdanpdan** [comment]
Can you please check the link? I cannot open it.

**Comment by Sfinx** [comment]
Select it manually with the mouse and paste to the browser. Do not click

**Comment by nothingismagick** [comment]
Can you please use an alternative source... I don't even know what that
file is.

>

**Comment by Sfinx** [comment]
its png.

[https://mega.nz/#!uokAUIDb!vyGhwUs3bTV3sSOBnWwmFuDuPvKpAsmZfr-CKG15sOI](https://mega.nz/#!uokAUIDb!vyGhwUs3bTV3sSOBnWwmFuDuPvKpAsmZfr-CKG15sOI)

**Comment by nothingismagick** [comment]
I think that this is being tracked here:

FYI - You can just drag and drop a png from your device filesystem and attach them to issues
![Screenshot_20190710-224315](https://user-images.githubusercontent.com/35242872/61002996-1fac8300-a363-11e9-866f-ae01e7ed6793.png)
...

**Comment by nothingismagick** [comment]
#4611 

In the future please look at the issues to see if other people are facing the same or similar problem.

Also, please consider reviewing our contribution guidelines:

https://quasar.dev/start/contribution-guide

**Comment by Sfinx** [comment]
I think you did not read the issue attentively. first: It is not related to the iOS only but to Android too. second: it is not leaving the space from the right as at #4611 but do not closes completely from the right.

**Comment by nothingismagick** [comment]
I think that the underlying issue is similar because we are seeing a problem with the drawer. You may be right that it is not entirely related - but I think the fix is the same.

**Comment by Sfinx** [comment]
No - they are totally different. I'm seeing 100% reproducible behavior for the both platforms. But Android can be easily reproducible even at real device (!) (I've tested with 7.1.1 tablet) only with connected DevTools + screencast. I guess screencast adds delay to the render engine and iOS emulator is very slow - this can be the real reason.

**Comment by nothingismagick** [comment]
I am not going to argue with you - because until we've tracked down the rendering bug we won't know what the exact cause is. 

However, suddenly similar behaviour appearing at the same time on different webkit renderers using the same component makes it *seem* to be related.

**Comment by nothingismagick** [comment]
BUT - thankyou for reporting. This helps us get to the bottom of it.

**Comment by Sfinx** [comment]
I just want to help too. I'm having very slow Mac - its mojave under qemu running ios emulator inside it ;) This is the slowest sh#it I've ever saw. But I would never reported this bug if it was not reproducible at Android too.

**Comment by nothingismagick** [comment]
Mojave under qemu emulating ios omg. Wow. Anyway, it sounds to me a little bit like a memory leak.

**Comment by metalsadman** [comment]
I do get this, but not often, drawer gets stuck and no matter how i try to drag it to close but it wont. I need to close app and remove it from the background to open a fresh page :(, coz the drawer overlay renders the page useless, coz even if i choose an item in the drawer to change route, the drawer still wont hide. Happens in my old and new android phone *hard to reproduce.

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.5.
Thanks for reporting!
