### ISSUE TITLE
Missing and Wrong typedef in validation of form components

### ISSUE THREAD

**Issue by marco-quintella** [quasarframework/quasar#4616]
**Describe the bug**
The  validate.json file for the validate mixin is assuming the prop error as the test result. Following the code in the component, the prop error and errorMessage should be used for external validation and the computed hasError returning the validation result, both external and internal. The code in the js file it's ok, but in the json that generates the typedef files and docs it's wrong.

Also in the first examples of QInput usage in the documentation, it shows the use of hasError as the only way to validate the fields without QForm. So probably this computed was forgotten when QForm was created.

**Expected behavior**
The computed hasError should be in the json as the return of validation tests. And error and errorMessage as the prop used to input the external validation data.

**Comment by outofmemoryagain** [comment]
@marco-quintella Regretfully there currently is no support computed properties in the API declaration files.  This means that your current PR will not work.  I have started a branch that adds support for computed properties in the API files, and added the code required to generate a read only property as part of the Type Definitions for that type.  I have not submitted an MR just yet b/c I need to look into updating the API docs themselves to determine if they require additional changes to display computed properties in the API documentation on Quasar.dev.

It would be great if you could take a look at my [Branch](https://github.com/outofmemoryagain/quasar/tree/fix_4616).  And see if this meets your needs at least for the type generation.

**Comment by marco-quintella** [comment]
I did not have look into de the build files. My PR was a proposition, but as I see your branch will solve the type definition for the computed. You can close my PR in benefit of yours.

I'm currently working in project custom typedef for QInput and QSelect. As soon your branch is merged I'll test.
