### ISSUE TITLE
Make docs site PWA, just like VueJs docs

### ISSUE THREAD

**Issue by bunya017** [quasarframework/quasar#4619]
**Is your feature request related to a problem? Please describe.**
I live in Nigeria, where access to good and reliable internet is an issue. Assuming one has an 
internet bundle, the ISP might go down for days without prior notice and this takes toll on my 
productivity. It'd be really nice if the quasar documentation site is made into a PWA like the way 
the VueJs, router, vuex docs are. The quasar docs used to work like a semi-PWA, in that if you 
open the docs then disconnect internet, you'd still be able to navigate through the docs on the 
same page as long as you do not end the session/close page/close browser.

**Describe the solution you'd like**
Make the docs a PWA

**Describe alternatives you've considered**
1. Clone the quasar repo, run `yarn install` and serve the docs locally as recommended [here](https://forum.quasar-framework.org/post/11541)
   I haven't tried this approach yet, I did use the offline docs with v0.17 and I liked it.

2. Download the quasar docs with `wget`

**Comment by rstoenescu** [comment]
Should have closed this one some time ago. It's done ;)
