### ISSUE TITLE
[Request] Input boxes with mask

### ISSUE THREAD

**Issue by epx34** [quasarframework/quasar#462]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by spectrolite** [comment]
there’s also a nice Vue plugin in the meantime…
https://github.com/probil/v-mask … but until #723 is integrated I’m not sure it’ll work that easily with q-input

**Comment by spectrolite** [comment]
a custom directive like this one could solve it elegantly in the meantime https://jsfiddle.net/0Lgb6r3s/

**Comment by Isarstyle** [comment]
#723 is integrated, but still having problems using the v-mask prop.. is there a solution?

**Comment by cbullokles** [comment]
Why mask was closed? I want a mask for phone or other data types, it is not documented at least in version 0.17...

**Comment by rstoenescu** [comment]
Because it was implemented for v1.0.

**Comment by Donnylai** [comment]
When v1.0 will be available?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ajcastro** [comment]
@rstoenescu  I didn't see in the docs how can I implement this? or did I just miss it? any help please?
