### ISSUE TITLE
1920px wide desktop screen is not lg and also not xl

### ISSUE THREAD

**Issue by lukasztyszko** [quasarframework/quasar#4622]
1920px wide screen is not recignized by Quasar a large or the xlarge type

https://codepen.io/anon/pen/vqPygq

Go to codepen link and change window width by resising in developer tools

We are expecting that screen type recognition should be continous from zero px to infinity

Example: 
```
{
  "width": 1920,
  "height": 368,
  "sizes": {
    "sm": 600,
    "md": 1024,
    "lg": 1440,
    "xl": 1920
  },
  "lt": {
    "sm": false,
    "md": false,
    "lg": false,
    "xl": false
  },
  "gt": {
    "xs": true,
    "sm": true,
    "md": true,
    "lg": true
  },
  "xs": false,
  "sm": false,
  "md": false,
  "lg": false,
  "xl": false
}
```

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.5
