### ISSUE TITLE
QTooltip inside QTab not working

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#4625]
**Describe the bug**
When a `QTooltip` is placed inside a `QTab`, it is expected that when the tab is hovered, the tooltip is shown but it is not the case right now. I thought maybe `QTooltip` is not supported inside a `QTab` but checking the docs for `QTab` it suggests `QTooltip` and `QMenu` for the default slot.
So it looks like either the docs should be updated to say this is not supported or it is actually a bug.
Or maybe I'm doing something wrong :).

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/WqmjmE?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.5
