### ISSUE TITLE
Slow transitions on mobile

### ISSUE THREAD

**Issue by lobosan** [quasarframework/quasar#463]
Hi, I want to use quasar for my next project and I need to create a responsive layout, however when I test the showcase v0.13.6 on my mobile (Samsung Galaxy S3), all the transitions aren't fluid and instead appear or disappear by parts. Examples of this behavior are layout, tabs and slide transition.

Is this something that has been pointed out or considered to be improved?

Thanks in advance for your help

**Comment by rstoenescu** [comment]
Yes, definitely. Animations will be improved quite a lot, with new features too. Targeting for v0.14.

**Comment by rstoenescu** [comment]
Also, please confirm you are experiencing this with v0.13.6.

**Comment by lobosan** [comment]
I see, thanks for your quick response. I just updated the description of the issue. 
By the way is there any approximate date when you expect to release the 1.0 version?

**Comment by rstoenescu** [comment]
Fixed in future v0.14.
