### ISSUE TITLE
[v1] QSlideTransition inside v-show calculates incorrect 0px height if outer element is hidden

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#4630]
**Describe the bug**
Given a `q-slide-transition` inside a `v-show` like below:
```html
<q-slide-transition>
    <div v-show="outerCondition"> // outer must be v-show
        // ...
        <q-slide-transition>
            <div v-if="innerCondition"> // inner can be v-if or v-show
                // ...
            </div>
        </q-slide-transition>
    </div>
</q-slide-transition>
```
And both `outerCondition` and `innerCondition` evaluate to `false`, if `innerCondition` is first set to `true` and then `outerCondition` is set to `true`, the `innerCondition` div has a 0px height and is not shown after the `outerCondition` transition.

In this case I've got an outer `QSlideTransition` as well but that's not required for the issue to happen. I assume this would happen if the ancestor was hidden for any reason, `v-show` or otherwise.

**Codesandbox**
https://codesandbox.io/s/quasar-portal-input-49lug?fontsize=14

**To Reproduce**
1. Open the code sandbox above
2. **Open the left menu and click on "Transition test"** (note: Level 2 is set to true inside a `beforeRouteEnter` guard to simulate an API load)
3. Check "Show level 1"
4. Notice that "Show level 2" is checked off, but Level 2 is not visible.

If you uncheck "Show level 2" and re-check it, then Level 2 is visible.

Note that if `innerCondition` is initialized in `data(`) as `true` instead of being set from `false` to `true`, then Level 2 is visible as expected once Level 1 is visible because the transition did not fire on initial render. If `innerCondition` is initialized as `true` in `data()` and `appear` is used on the inner `QSlideTransition`, then Level 2 is once again not visible once Level 1 is.

**Expected behavior**
Level 2 to be visible once Level 1 is visible.

Not sure how it could be fixed because I'm assuming it's impossible for the inner `QSlideTransition` to calculate a height when it's inside the collapsed outer element. If there was a way to conditionally disable a `QSlideTransition` animation (so it just lets the child `v-if`/`v-show` do its thing) then that could help because I could disable the inner transition based on the outer condition. Since it's hidden anyway, the animation is not necessary:
```html
<q-slide-transition>
    <div v-show="outerCondition">
        // ...
        <q-slide-transition animate="outerCondition">
            <div v-if="innerCondition">
                // ...
            </div>
        </q-slide-transition>
    </div>
</q-slide-transition>
```
Or if a new prop is not desired (it's a bit of an edge case, I'll agree), perhaps if the duration is 0, the height calculation could be skipped since the animation is effectively useless at that duration anyway? Then it could be used like: 
```html
<q-slide-transition>
    <div v-show="outerCondition">
        // ...
        <q-slide-transition :duration="outerCondition ? 300 : 0"
            <div v-if="innerCondition">
                // ...
            </div>
        </q-slide-transition>
    </div>
</q-slide-transition>
```
Then that would just be like a performance tweak that could also happen to be used as a workaround.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Yarn: 1.16.0
Browsers: Mozilla Firefox 67.0.4 (64-bit)

**Additional context**
The example Codesandbox is contrived to illustrate the issue. In the real world I'm using a modified `QStepper` that keeps all the `QStep`s in the DOM using `v-show`, so that my VeeValidate `ValidationObserver` can keep track of validation for all steps at the same time (and also allows the `QStep` to not be a direct child of `QStepper` so I can wrap the steps in `ValidationObserver`s).

In some steps, there are `QSlideTransition`s based on other conditions and those components are not being shown once their step is visible, which is how I came across this issue originally.

I can't just use the default `QStepper`/`Qstep` because the `ValidationObserver` cannot observe inactive components.

**Comment by rstoenescu** [comment]
Fix willl be available in 1.0.5.
Thanks for reporting!
