### ISSUE TITLE
QInput on iOS scrolls header out of view

### ISSUE THREAD

**Issue by douglance** [quasarframework/quasar#4631]
**Describe the bug**

**To Reproduce**
1. Add QInput to default Quasar build
2. Make sure there is Header in layout
3. Build for iOS device
4. Tap QInput 
5. Keyboard pops up and pushes header out of view

**Expected behavior**
I expect the header to be locked to the top of the view when the keyboard pops up.

**Video**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4741454/61134175-030c6a00-a48d-11e9-8d65-9091467a125b.gif)

**Platform (please complete the following information):**
iOS 11.4.1

**Additional context**

NodeJs - 12.1.0

Global packages
  NPM - 6.9.0
  yarn - 1.15.2
  @quasar/cli - 1.0.0
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.0.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.3 -- Quasar Framework local CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  @babel/core - 7.5.0 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0-beta.22 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing-e2e-webdriver - 1.0.0-beta.7 -- A Quasar App Extension for Webdriver e2e
  @quasar/quasar-app-extension-testing-quality - 1.0.0-beta.6 -- A Quasar App Extension for Code Quality
  @quasar/quasar-app-extension-testing-security - 1.0.0-alpha.3 -- A Quasar App Extension for Application Security
  @quasar/quasar-app-extension-testing - 1.0.0-rc.5 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-icon-genie - 1.0.0 -- A Quasar CLI Extension for Making All Your Icons

**Comment by douglance** [comment]
Added video of issue to description.

**Comment by rstoenescu** [comment]
Hi,

Thank you for the detailed description and for the video.
Unfortunately, there are lots of rendering browser rendering bugs iOS that Apple just doesn't want to fix (years old bugs on the "fixed" position of elements). This falls into this category and cannot be handled by Quasar. We've gone at great lengths to workaround many of the iOS problems (lots and lots that developers aren't even aware when using Quasar, because "things work"), but this is not something we can fix. Sorry for any inconvenience.
