### ISSUE TITLE
Material Icons Outlined/Round/Sharp support

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#4635]
I would like to use this icon: mdi-camera-plus-outline. Could you maybe update?:
https://github.com/Templarian/MaterialDesign/issues/1568#issuecomment-510704623

**Comment by rstoenescu** [comment]
Hi,

Thanks for bringing this into our attention. I was about to reply that the Google folks haven't released yet the webfonts for Outline/Round/Sharp, but I just checked and now they do exist.

So updated @quasar/extras (v1.2.0). Pushed a commit for QIcon support on them which will be available in 1.0.5.

**Comment by rstoenescu** [comment]
PS: have not included Two Tone because it shows no difference between regular Material Icons and this flavour when using a webfont.
