### ISSUE TITLE
Supporting slider with no default value (null)

### ISSUE THREAD

**Issue by RoelRoel** [quasarframework/quasar#4637]
**Is your feature request related to a problem? Please describe.**
I want to use the slider in a survey where I want no bias by suggesting an initial value.

**Describe the solution you'd like**
When the value of a slider is null it should display no handle. Now it displays it as if it is set to the minimum value.

**Describe alternatives you've considered**
Add css visibility: hidden; to the knob when value is null.

**Comment by rstoenescu** [comment]
This will be available in 1.1.1
