### ISSUE TITLE
[Request] Apply CSS class to Data Table Row

### ISSUE THREAD

**Issue by glittle** [quasarframework/quasar#464]
Please add a way to set the CSS class for a row based on the row’s data object?

[Dicussion in the forum](http://forum.quasar-framework.org/topic/153/data-table-row-class)

**Comment by dewdad** [comment]
I need a dynamic height for each row based on the tallest cell's height for cells with lists. I guest my requirement applies to this.

**Comment by rstoenescu** [comment]
Will do.

**Comment by rstoenescu** [comment]
Closing as code is ready in future v0.15 datatable revamp.

**Comment by Davilink** [comment]
What happen with this request ?
