### ISSUE TITLE
translate3d from xxxx-center css causes blurriness

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#4641]
Hi,

Looking at this example

https://codepen.io/smolinari/pen/YoRdWB

remove the "#" in the CSS and watch the blurriness go away on the first two toolbar titles texts. 

You can also see the blurriness on the Quasar website's 404 page too.

https://quasar.dev/not-found

I'm not sure the change from `transform: translate3d(-50%,-50%,0);` to `transform: translate(-50%,-50%);` is a proper fix, but it seems to work.

I'm using Chrome latest version on Win10 pro. 

Scott

**Comment by ibrainventures** [comment]
@pdanpdan is there solution avaible ? 
.. As Scott writes, this happens on Win 10 and Chrome .. (a very huge target-group ...) ...   
`<div class="fixed-center text-center">` .. is the "trigger" and it happens also on the default 404 - // Error404.vue Page ...

**Comment by hawkeye64** [comment]
This is an interesting read on the translate/translate3d in different browsers ad possible solution
https://martinkool.com/post/27618832225/beware-of-half-pixels-in-css

**Comment by ibrainventures** [comment]
@hawkeye64 really interesting ...
@pdanpdan .. to get a impression, if you dont have a win/chrome setup, i added a screenshot:

![grafik](https://user-images.githubusercontent.com/8803626/63674466-e6cb4f00-c7e6-11e9-9ded-54dcd359efc0.png)

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1

**Comment by avesus** [comment]
What is the purpose of Quasar doing this?

**Comment by rstoenescu** [comment]
@avesus Quasar doing what exactly?

**Comment by hawkeye64** [comment]
@avesus Seems self-explanatory in the reasoning of the ticket.
