### ISSUE TITLE
new material design fonts in extras don't display properly

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#4642]
The handling of the new fonts in QIcon needs to be released in order to use the new material-design icons (when searching for 'o_', 'r_' and 's_').

**Comment by rstoenescu** [comment]
I quote from the quasar extras release notes:

> QIcon component will support these in Quasar 1.0.5 (unreleased yet, so watch out for it).

The code is already there. It's just not released yet.

**Comment by froschi123** [comment]
still not released? Its not working in 2.5.5.

**Comment by rstoenescu** [comment]
@froschi123 lol. Of course it works. But did you load the material icons variant?  (check docs, it's easy)

**Comment by hawkeye64** [comment]
> still not released? Its not working in 2.5.5.

You can see a good representation of it working here: https://iconexplorer.app

**Comment by froschi123** [comment]
Thanks for the fast answer ... i found the trick :-) But.

In my application, the result of switching to oc_... is quite disturbing ...

I set the extras to:
```
extras: [
      "roboto-font", // optional, you are not bound to it
      "material-icons", // optional, you are not bound to it
      "material-icons-outlined", // optional, you are not bound to it
    ],
```

and i am using q-icon in this way:
`<q-btn dense flat icon="oc_save" :label="$t('buttons.save')"></q-btn>`

With this result:
![image](https://user-images.githubusercontent.com/46695287/157060565-64e38111-750e-4264-a3ed-06e754d45264.png)

if i switch to oc_save for the icon, it looks like this:
![image](https://user-images.githubusercontent.com/46695287/157060750-25d2377a-ebf2-4ca6-aa7f-c2e3cc6ca83c.png)

Same for avatar icons etc. In chrome dev-tools it looks like this:
![image](https://user-images.githubusercontent.com/46695287/157062661-7a418538-00f8-46a3-b146-f44808bb0c01.png)

So it seems to be still the material-icon (not the oc_ one) but it is not aligned to the left.

Any idea?

Thanks, good to see the fast reaction :-)

Bernd

**Comment by pdanpdan** [comment]
Any special reason to add the extra `c` char in the prefix?

**Comment by hawkeye64** [comment]
@pdanpdan is correct. The prefix for Material Outline is just `o_`
