### ISSUE TITLE
[v1] ios q-input focus method not (re) activating the input field

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#4646]
V 1,05 quasar - latest version

After submitting the input, i am re-activating the input with the .focus method.

No Problem under firefox, chrome, android .. 
Ios not (re) activating the input state.
I made a video, where you can see the problem / difference.
First part - firefoxy
second part - ipad 

https://vimeo.com/347894116

Best regards
Jochen

**Comment by nothingismagick** [comment]
Hi Jochen, 
Can you please provide a codepen showing what you are doing, and the output of `quasar info`?

Also, I have some security issues about the approach you are using that I would like to talk with you about, but it's not appropriate here in a public discussion. Please feel free to join us on our discord server by following this link: https://chat.quasar.dev

**Comment by nothingismagick** [comment]
I know you solved this issue, would appreciate it if you would share your solution.

**Comment by ibrainventures** [comment]
After Some googling, this seems to be a ios "feature"

IOS/Safari only "accepts" the focus when inside a touch event handler. 

I tested a little workaround, which helds the KEyboard open.

Instead of submitting by button, i used a second qinput - made it optical to a submit button 
and take the @focus event from his input. then i re-focus by the focus method back to input field one ..
it works .. but it is for this project to much workaround :-)
