### ISSUE TITLE
Passing emulator options to `quasar dev` doesn't work.

### ISSUE THREAD

**Issue by geoidesic** [quasarframework/quasar#4653]
**Describe the bug**
The docs here: https://quasar.dev/quasar-cli/developing-cordova-apps/build-commands
State that one can pass emulator options as part of the build or dev commands. However this doesn't seem to work. I'm trying to pass the `-dns-server` options to the Android emulator but it doesn't work. The docs are a bit ambiguous about the actual format for doing so and don't provide examples, so I'm not 100% sure if it's a but or if I'm just doing it wrong. 

**Codepen/jsFiddle/Codesandbox (required)**
N/A

**To Reproduce**
1. Setup for android emulator as per quasar docs instructions. 
2. Then issue the command:
`quasar dev -m android -- -dns-server 192.168.0.10` or whatever your local DNS server is.

**Expected behavior**
It should pass the options through to the emulator.
It should be equivalent to starting the emulator directly like so:
`emulator -avd Pixel_2_API_29 -dns-server 192.168.0.10`

**Platform (please complete the following information):**
OS: Mac OS X Mojave 10.14.5
Node: 12.6.0
NPM: 6.9.0
Yarn: 1.16.0
Browsers: Android emulator chrome
iOS:
Android: yes
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

The additional parameters are passed to the `cordova` command, not to the `emulator`. So please check cordova CLI command that does what you want.

**Comment by geoidesic** [comment]
Cordova doesn't seem to have such an option as far as I can tell. How can I see the actual Cordova command that `quasar dev -m android` will run? Is there a way I can output that as a string? That way I at least have a basis for further investigation via Cordova.

**Comment by geoidesic** [comment]
Actually never mind the string is already output by Quasar: `cordova run android`.
