### ISSUE TITLE
Qdialog not updating properties on component in synch

### ISSUE THREAD

**Issue by cjmendoza** [quasarframework/quasar#4654]
**Describe the bug**
Have a qdialog with component inside with properties being passed. When qdialog is fired, the properties inside the component are not being passed. Subsequent to that, if I close the dialog and open it again, the properties are then passed.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS: linux
Node:
NPM:
Yarn:
Browsers: chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Please add a fiddle so we can understand what you are talking about. Also please clean all the text you ignored in the original issue template - this way at least it's going to be more easy for us to see the content.

**Comment by pdanpdan** [comment]
If you have any input for this issue please feel free to open a new issue with the details. Thank you.
