### ISSUE TITLE
QSelect - selected-item index

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#4655]
**Describe the bug**
In selected-item slot in QSelect the prop index doesn't change. If you see the data of the element selectedScope, not change the index prop when select options.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/EBzpMJ

**To Reproduce**
1. Create a q-select
1. Added slot in selected-item and use scope.index
1. Selects differents options

**Expected behavior**
Update the item displayed with the current index

**Comment by pdanpdan** [comment]
`scope.index` available for the `selected-item` slot is the index in the list of selected items (not in the list of available options) - it wouldn't be possible to use the index in the list of options (think of having a preselected options list but an updated list of options).
