### ISSUE TITLE
QSelect in Cordova doesn't pass keydown event

### ISSUE THREAD

**Issue by robopeter** [quasarframework/quasar#4657]
**Describe the bug**
A QSelect with a @keyup.native property does not seem to trigger the specified function in cordova (though it does in a PWA).  I've also tried @keyup, @keydown, and @keydown.native with the same results. 

This codepen behaves as expected, though the same code compiled to a Cordova app (Android or IOS, though I've done a lot more testing on Android than IOS) doesn't ever trigger the mykeyup function. 

https://codepen.io/anon/pen/gNJEXP

**Expected behavior**
Same as PWA but in a Cordova app.

OS: Linux
Node: v10.16.0
NPM: 6.10.11

**Comment by robopeter** [comment]
A possibly related issue that that the keydown event isn't triggered when an "Enter" is pressed. Interestingly, I can see the keydown event being processed in the "__onTargetKeydown" method in QSelect, however the event never makes its way to my code :-(

**Comment by robopeter** [comment]
quasar info

Operating System - Linux(4.15.0-42-generic) - linux/x64
NodeJs - 10.16.0

Global packages
  NPM - 6.10.1
  yarn - Not installed
  @quasar/cli - 1.0.0
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.0.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.4 -- Quasar Framework local CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.7 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.5.4 -- Babel compiler core.
  webpack - 4.35.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 1.0.0 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing-e2e-cypress - 1.0.0-beta.10 -- A Quasar App Extension for Cypress e2e
  @quasar/quasar-app-extension-testing-e2e-webdriver - 1.0.0-beta.9 -- A Quasar App Extension for Webdriver e2e
  @quasar/quasar-app-extension-testing-quality - 1.0.0-beta.8 -- A Quasar App Extension for Code Quality
  @quasar/quasar-app-extension-testing-security - 1.0.0-alpha.8 -- A Quasar App Extension for Application Security, using OWASP ZAP
  @quasar/quasar-app-extension-testing-security-antivuln - 1.0.0-alpha.1 -- A Quasar App Extension for checking that no packages are vulnerability threats
  @quasar/quasar-app-extension-icon-genie - 1.0.1 -- A Quasar CLI Extension for Making All Your Icons

**Comment by rstoenescu** [comment]
Hi,

Should be fixed in 1.1.0 through our own fastclick fork. Please reopen if you experience it with future 1.1.0. Thank you.

**Comment by robopeter** [comment]
It seems I do not have permission to re-open this as requested.

However, it seems this issue is not resolved with 1.1.0, and perhaps might even be worse. The same codepen linked above is now using 1.1.0, but still does not receive keydown / keyup events. It is now sufficient to simply open the codepen in Chrome on Android, type in the text box, and see that no events are recorded.

**Comment by pdanpdan** [comment]
Let my try to summarize (this is what I understand, please correct me if I'm wrong):

- you have a QSelect with use-input
- you want to listen for the key events inside the input text field in the QSelect
- this is working while testing it on desktop (or large screens) where the list of options show as a menu
- this is not working while testing it on mobiles (small screen) where the list of options show as a dialog

If this

**Comment by robopeter** [comment]
Yes, that is a good summary!

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1

**Comment by robopeter** [comment]
For those who might find this in the future, this fix DOES NOT work for the codepen as recorded above.  You have to remove the ".native" to make it work as expected on Chrome mobile (and possibly others)
