### ISSUE TITLE
fullscreen wrapper 'does not recognize fullscreen mode'

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#4664]
In my app I use the quasar fullscreen wrapper. I manage to go in- and out of fullscreen mode fine using the wrappers own commands and `this.$q.fullscreen.isActive` corresponds to the actual mode. However when in mobile mode (using Chrome, which supports fullscreen mode, so `$q.fullscreen.isCapable: true`) I go into fullscreen mode by dragging the page up (so not using the wrappers commands) the value of `this.$q.fullscreen.isActive` remains `false`. 

Is this intentional? How do I keep track of such changes to fullscreen mode?

**Comment by rstoenescu** [comment]
Hi,

AppFullscreen Quasar plugin is a wrapper over the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). I'm a bit confused of what you are referring to when you say that "you drag the page up". Are you sure that your app goes into the same fullscreen mode as the Fullscreen API describes?

**Comment by musicformellons** [comment]
The 'fullscreen' feature seems -in general- rather messy. What I am referring to is Mobile Chrome giving you more screen estate by making the url box disappear when you scroll up. But the native upper bar with clock etc of your phone still remains. So I think you are right, my case is probably not part of the 'fullscreen api'. Looks like in the 'fullscreen api' experience that upper bar has to just be black... (not giving you more screen estate BTW, but less distraction). 

My experiences using AppFullscreen were also different after recompiling my app as then it seems the AppFullscreen completely blocks scrolling somehow. Probably I need to chance my css or something to get this right?! Anyway I think I can manage to hack my use-case by comparing `window-innerwidth` with `screenwidth` like suggested [here](https://stackoverflow.com/a/52160506/3294412). I don't really like it, but it's the best option in my case I think. Luckily 'fullscreen' is better when using the app as PWA.
