### ISSUE TITLE
Context menu cannot be opened programmatically

### ISSUE THREAD

**Issue by lbausch** [quasarframework/quasar#4665]
**Describe the bug**
There are serveral context menus defined inside a v-for loop. All of them share the same `ref`.
When a button is clicked the corresponding context menu should appear. This is done by calling a function which identifies the correct menu component and calling `show()` on it.
The menu does not appear.

The loop/ref idea was borrowed from https://github.com/vuejs/vue/issues/4952

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/LKKzZL

**To Reproduce**
1. Define context menus inside a `v-for` and assign them a `ref`
2. Determine the menu component inside a loop
3. Call `.show(event)` on menu component
4. Menu does not appear (it appears when right clicking on the item though)

**Expected behavior**
Menu should appear when `.show(event)` is called on it

**Platform (please complete the following information):**
OS: Linux
Node: v10.16.0
NPM: 6.10.1
Yarn: -
Browsers: Chrome 75
iOS: -
Android: -
Electron: -

**Comment by hawkeye64** [comment]
You can do something like this:
```js
var element = document.getElementById('yourElement');
if (window.CustomEvent) {
    element.dispatchEvent(new CustomEvent('contextmenu'));
}
```

**Comment by pdanpdan** [comment]
https://codepen.io/anon/pen/orrodR

**Comment by lbausch** [comment]
@pdanpdan Thank you very much for your fast reply and this clever solution. Works like a charm :)
