### ISSUE TITLE
Screen and CSS breakpoints documentation

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4668]
It's very good that `$q.screen.gt.xs` is consistent with CSS `.gt-xs`. However the screen props: `sizes` and `setSizes` work a little bit different from the CSS:

- `$q.screen.sizes` shows the **minimum** breakpoint. Eg. `600` for `sm`.
- [documentation on CSS related breakpoints](https://quasar.dev/style/visibility) shows the **maximum** breakpoint. Eg. `1023` for `sm`.

Because Quasar encourages to think in "maximum" breakpoints when it comes to CSS, but for the `Screen` directive we can only get the "minimum" breakpoints on the `sizes` prop, and the `setSizes` function allows us to change these "minimum" breakpoints, it gets a bit confusing.

Maybe it might be interesting to provide additional information on the `Screen` directive that allow us to check the `minimum` breakpoints as well.

Or maybe we could add some clarification on the `sizes` prop in the documentation at least, stating clearly that this is showing the `minimum` breakpoints as opposed to the `maximum` breakpoints explained in the CSS docs.

**Comment by rstoenescu** [comment]
Hi,

Well, as long as you can also use gt (greater than) and lt (lower than), you can achieve anything that you want. If you think docs can be improved, please PR it. I'll improve the API JSON. Thanks!
