### ISSUE TITLE
Calling dialog from drawer list link closes dialog when drawer is closed

### ISSUE THREAD

**Issue by genyded** [quasarframework/quasar#467]
### Software version

Quasar: 0.5.2
OS: Win 10
Node: 6.9.5
NPM: 
Browsers: All
iOS: N/A
Android: N/A
Any other software related to your bug: N/A

### What did you get as the error?
No error
### What were you expecting?
Dialog should stay open when drawer closes
### What steps did you take, to get the error?
Have a method that creates a dialog and closes a drawer when a list item on the drawer menu is clicked:
```
...
showLoginDialog () {
  this.$refs.accountDrawer.close()
  this.$store.dispatch('auth/toggleLogin') // <- creates the dialog 
}
....
```
This is getting fired and the dialog is getting created, but if immediately dismissed when the drawer close event fires for some reason.  If I comment out the drawer close, the dialog works fine. With the drawer close in, the dialog closes when the drawer does (whether the drawer close is before or after the dialog) and the dialogs dismiss method executes instead of the dialog showing.

**Comment by rstoenescu** [comment]
```
showLoginDialog () {
  this.$refs.accountDrawer.close(() => {
   this.$store.dispatch('auth/toggleLogin')
  })
}
```

Dispatch after Drawer is closed. Both Drawer and Dialog tamper with window history (so you can use the  cool feature of "back" button closing Drawer/Dialog/Modal etc).

Not sure if `close()` supports a handler for v0.5.2. I'd have to take a look. If it doesn't, just add a setTimeout and call the dispatch.

Please upgrade to latest Quasar or wait for v0.14 and upgrade then.

**Comment by genyded** [comment]
That works great and thanks as usual for the fast response. Also we are waiting (patiently) for v0.14.
