### ISSUE TITLE
i18n file- BCP 47?

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar#4670]
Language tag syntax is defined by the IETF's BCP 47. In the past it was necessary to consult lists of codes in various ISO standards to find the right subtags, but now you only need to look in the IANA Language Subtag Registry. We will describe the new registry below.

BCP stands for 'Best Current Practice', and is a persistent name for a series of RFCs whose numbers change as they are updated. The latest RFC describing language tag syntax is RFC 5646, Tags for the Identification of Languages, and it obsoletes the older RFCs 46463066 and 1766.

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

zh-hans zh-hant is Deprecated.

Type: redundant
Tag: zh-Hant
Description: traditional Chinese
Added: 2003-05-30

Type: redundant
Tag: zh-Hans
Description: simplified Chinese
Added: 2003-05-30

Many of these registered tags were made redundant by the advent of either RFC 4646 or this document.  A redundant tag is a grandfathered registration whose individual subtags appear with the same semantic meaning in the registry.  For example, the tag "zh-Hant" (Traditional Chinese) can now be composed from the subtags 'zh' (Chinese) and 'Hant' (Han script traditional variant).  These redundant tags are maintained in the registry as records of type 'redundant', mostly as a matter of historical curiosity.

zh-hans and zh-hant should be changed to cmn-hans and cmn-hant

**Comment by yusufkandemir** [comment]
> zh-hans and zh-hant should be changed to cmn-hans and cmn-hant

They got changed to zh-CN and zh-TW accordingly in Quasar v2, as can be seen here: https://quasar.dev/start/upgrade-guide#quasar-language-packs
> We have changed the language pack filenames to reflect the standard naming used by browsers.

I don't know much when it comes to this topic, but most of the languages like en-US or en-GB don't even exist in The Language Subtag Registry. So, it may be a better idea to comply with naming strategies used by major browsers in this case.
