### ISSUE TITLE
QSelect triggers data change multiple times

### ISSUE THREAD

**Issue by Monkey-D-Pixel** [quasarframework/quasar#4671]
**Describe the bug**
QSelect triggers the model data change multiple times when a different option is selected.
when there are several (n) other QSelect components, the time will add by n.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/monkey-d-pixel/pen/WqVrdz

**To Reproduce**
open console panel to see the logs
1. select another option in the first select box
2. uncomment second QSelect in html editor and repeat step1

**Expected behavior**
one option pick operation only triggers data change once.

**Platform (please complete the following information):**
OS: Linux
Node: /
NPM: /
Yarn: /
Browsers: Chrome 75, Firefox 68
iOS: /
Android: /
Electron: /

**Comment by pdanpdan** [comment]
You know `data` in Vue should be a function returning the state?
https://codepen.io/anon/pen/GbVNwY?editors=1010

**Comment by Monkey-D-Pixel** [comment]
> You know `data` in Vue should be a function returning the state?
> https://codepen.io/anon/pen/GbVNwY?editors=1010

No, but only knew it's a must when writing a component.
Learned something new. Thanks.
