### ISSUE TITLE
`quasar serve` doesn't serve my files after running `quasar build`

### ISSUE THREAD

**Issue by jippy89** [quasarframework/quasar#4672]
**Describe the bug**
I am trying to use `quasar serve` however it seems to keep sending me on 404 | Page Not Found.

**Codepen/jsFiddle/Codesandbox (required)**
Sorry, I tried forking a codesandbox, however I can't seem to reproduce it. I tried installing `yarn global add @quasar/cli` however when I try to `quasar build` it doesn't even recognize `quasar`. But I don't want to waste my time for that.. Here's the [sandbox](https://codesandbox.io/s/codesandbox-app-ggte4) to another problem. You can check `yarn.lock` that I have installed `@quasar/cli`.

**To Reproduce**
1. Run `quasar build`
2. Run `quasar serve`
3. Go to `localhost:4000` 
4. See `404 | Page Not Found`

**Expected behavior**
Seeing my SPA alive as told in CLI `localhost:4000`

**Platform (please complete the following information):**
OS: Manjaro Linux Illyria 18.0.4
Node: 10.15.3
NPM: 6.9.0
Browsers: Mozilla Firefox 67.0.4 (64-bit)

**Additional context**
I had no idea, no errors seen. I thought I run `quasar build` perfectly since I can use the build files to and serve it to an express server. However after knowing that quasar can be standalone by itself, I was trying to serve it on its own and separate my REST totally from my SPA. 

Logs when serving:
```
 Quasar CLI.......... v1.0.0-beta.3
 Listening at........ http://localhost:4000
 Web server root..... <project-directory>
 Gzip................ enabled
 Cache (max-age)..... 86400
 Micro-cache......... 1s

GET / [127.0.0.1] Wed Jul 17 2019 00:01:34 GMT+0700 (Western Indonesia Time)
  404 on /
```

Please do tell me if you need anymore info about my problem. Thanks!

**Comment by m0jimo** [comment]
Have you tried goto ```http://localhost:4000/dist/spa/index.html```

**Comment by pdanpdan** [comment]
As per docs it's `quasar  serve path_where_the_files_are`.

So in your case `quasar  serve dist/spa`

**Comment by windroldev** [comment]
On my case I forgot to run `yarn install` or `npm install` inside the created project folder since it failed due to network failure.

**Comment by ccencisoj** [comment]
Try `quasar serve dist/spa --history`. 

With the flag `--history` all requests fallback to /index.html
