### ISSUE TITLE
stepper styles don't contain colors as css custom properties

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#4673]
The styles for the stepper component don't contain colors as css custom properties (css variables). So, for instance, setting these colors from js with `colors.setBrand()` has no effect within the component.

E.g. https://github.com/quasarframework/quasar/blob/a4067bdcb8a0273372b9aab096a4fc7c8c911dc5/ui/src/components/stepper/stepper.styl#L41

**Comment by rstoenescu** [comment]
Hi,

This is why there are properties on QStepper and QStep that refer to colors.

**Comment by wc-matteo** [comment]
yes but why using a stylus variable without a css variable? either no variable or both, I thinkOn Jul 16, 2019 13:13, Razvan Stoenescu <notifications@github.com> wrote:Hi,
This is why there are properties on QStepper and QStep that refer to colors.

**Comment by rstoenescu** [comment]
Yes, you are right. It's got fixed and will be available in 1.0.6.
