### ISSUE TITLE
QDate/ QTime Slot for adding additional stuff, i.e. buttons

### ISSUE THREAD

**Issue by m0dch3n** [quasarframework/quasar#4675]
**Is your feature request related to a problem? Please describe.**
It would be nice, to easily add Cancel/OK Buttons to QDate/QTime

**Describe the solution you'd like**
Please add a slot on the bottom therefore, like on this image

![image](https://user-images.githubusercontent.com/11309824/61292491-9a492880-a7d1-11e9-976b-a72f1e6ddcca.png)

**Comment by m0dch3n** [comment]
are there any news on this ?

**Comment by rstoenescu** [comment]
Hi,

Will be available in "quasar" v1.2.7 through the default slot of QDate/QTime.
