### ISSUE TITLE
More control over behaviour when press enter key inside q-popup-edit

### ISSUE THREAD

**Issue by ActiveBusinessSolutions** [quasarframework/quasar#4678]
**Is your feature request related to a problem? Please describe.**
We are going to let users input multi-line text in q-editor component on the q-popup-edit but once they press on the enter key, editing just ends up so they can't input multi-line text such as description

**Describe the solution you'd like**
I took a look at the QPopupEdit. I think we can control the keyup listener in the render function using props variables.
such as setOnKeyEnter=true/false

**Comment by rstoenescu** [comment]
Hi,

On the textarea/multi-line input, stop propagating enter key. Example: `<q-input @keyup.enter.stop .....`.

@pdanpdan care to add this to the QPopupEdit doc page, pls?
