### ISSUE TITLE
Discussion about typescript types for dialog plugin

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#4679]
I was thinking we might try something along this lines (use a discriminator with the component name on derived definitions of components).

```typescript
type QDialogPluginNoComponent = {
  qDialogPluginOwnProperty?: boolean,
};

type QDialogPluginComponent = QDialogPluginNoComponent & {
  component: string,
};

type InputValue = string | number | null;

type QInput = {
  value: InputValue,
  "@input": (value: InputValue) => void,
};

type QBtn = {
  label?: string,
  "@click": ( event: Event ) => void,
};

type QInputComponent = QInput & {
  component: "QInput",
};

type QBtnComponent = QBtn & {
  component: "QBtn",
};

type QDialogPlugin = QDialogPluginNoComponent | ( QDialogPluginComponent & ( QInputComponent | QBtnComponent ) );

const test1: QDialogPlugin = {
  qDialogPluginOwnProperty: true,
};

const test2: QDialogPlugin = {
  component: "QBtn",
  qDialogPluginOwnProperty: true,
  "@click": ( event ) => { console.log( event ); },
};

const test3: QDialogPlugin = {
  component: "QInput",
  // qDialogPluginOwnProperty: true,
  value: 123,
  "@input": ( val ) => { console.log( val ); },
};
```

**Comment by outofmemoryagain** [comment]
This feels related to #4411. Extending the interface `QDialogOptions ` to add custom properties and then using that derived type to pass the values works without an issue. 
```
interface MyCustomInterface extends QDialogOptions {
  aProp: string
  ...
}
...
this.$q.dialog({
  component: CustomComponent,
  aProp: "aprop val"
} as MyCustomInterface )
```
I'm not sure I fully understand the scope of the Dialog Plugin which may help me to better understand the need beyond documenting the above.

The other consideration is that our types are generated from the API JSON documents, and will require some updates to support any significant changes to what we have today.  I'm aware that the API files in some cases are lacking detail.  Such as specifying type of "Array" when the type should be more specific in "string[]" or should be "Object[]" with the object definition as part of the file (for example QTable.options.columns).

Let me know your thoughts on it.  I would like to start a Typescript Documentation section for the main docs site soon, which would include a lot of these types of examples.
