### ISSUE TITLE
Show AE important local packages with Quasar CLI info

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4683]
**Is your feature request related to a problem? Please describe.**
All important local packages and their versions are listed using `quasar info`, but it includes only packages for Quasar core, not for App Extensions.
This is expecially important due to the fact that Quasar doesn't use peer dependencies mechanism (#4606), so important packages won't be listed into the `package.json`.

**Describe the solution you'd like**
All important dependencies (jest, typescript, every AE should expose its ones) should be listed with `quasar info` too.

**Describe alternatives you've considered**
Using `yarn --pattern <package-name> --depth=0` you can get a list of all packages matching a certain name.

**Comment by rstoenescu** [comment]
A lot has changed since this ticket was submitted. Have only implemented showing the TS version in "quasar info", since TS comes with "@quasar/app" now.

**Comment by IlCallo** [comment]
Thank you!
