### ISSUE TITLE
Add breakpoint to QFooter like in QDrawer

### ISSUE THREAD

**Issue by realtebo** [quasarframework/quasar#4684]
**Is your feature request related to a problem? Please describe.**
It's not blocking, but usefull. I used to have both QDrawer and QFooter, and using QDrawer's breakpoint prop I can hide for mobile.
It should be available also for QFooter, even I thinks that for consistance it should be present all around the framework widget

**Describe the solution you'd like**
Add breakpoint prop to QFooter 

**Describe alternatives you've considered**
Actually I'm using scoped style in my layout and adding a media query

**Additional context**
Thanks for all your work !!!!

**Comment by pdanpdan** [comment]
If you want too hide the QHeader/QFooter based ob breakpoint use `this.$q.screen`.
To hide the footer on mobiles: `<q-footer v-if="$q.screen.gt.sm">...`

**Comment by rstoenescu** [comment]
Or use the v-model combined with the Screen plugin. You can even specify custom behavior through the width from Screen plugin.
