### ISSUE TITLE
[docs] Please, add default to props documentation

### ISSUE THREAD

**Issue by realtebo** [quasarframework/quasar#4685]
Each API has a lot of props. 

But if I see 100 booleans, which of these are default true and which default false!?

For example: https://quasar.dev/vue-components/list-and-list-items#QItem-API 

The clickable prop is enabled or disabled by default? 

I run into this question because I am following a very good course and the teacher always point we to the (excellent ! really ! ) docs. But a student asked ... but... which is the default of all of these props?

"Nice question", said the teacher

I said "By default, if not set, Vue boolean props are false'.

"Yes, but the clickable is defaulted to true ... sorry "

**Comment by pdanpdan** [comment]
The props are marked with the default value when it is not the expected one.
And QItem's `clickable` is default false.

**Comment by realtebo** [comment]
Ok, thanks.
Also, I found a double mistake is class code, mine and also in teacher's one !
