### ISSUE TITLE
Stuck building... Multi q-card component causing freeze

### ISSUE THREAD

**Issue by stuartcusackie** [quasarframework/quasar#4688]
**Describe the bug**
When I run quasar dev or build the "building..." process freezes. It seems to only happen when I add more than one q-card to a component which is imported on a page. If I remove the second card it works again.

The "building..." process freezes at a different point each time (50%, 62%, etc.) 

I am using quite a lot of Quasar components (37 in total). Maybe that's a factor?

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/bXGWWL

**Screenshots**
![image](https://user-images.githubusercontent.com/20210934/61445623-a2c27000-a945-11e9-8169-bca9ebf7cf71.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: 10.15.3
NPM: 6.4.1
Yarn: 1.15.2
Browsers: Chrome

**Additional context**
I have run yarn upgrade and restarted my machine.
How would I go about debugging this?

**Comment by stuartcusackie** [comment]
Forget it. Stupid mistake: 'template can contain only one root element'.

The console did not warn me about this though. Is that a bug?

**Comment by hawkeye64** [comment]
That's something eslint would warn you about. I have seen it several times because it's easy to forget you can't do that.
