### ISSUE TITLE
QTabs and shrink aren't reliable with zoom

### ISSUE THREAD

**Issue by KnowZero** [quasarframework/quasar#4689]
**Describe the bug**
Shrink doesn't seem to be working all the time with zoom on qtabs.

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/anon/pen/xvxLoN?editors=1010

(make sure the code is on top and not on the right, you can still see the failure regardless, just it would be slightly different zoom levels)

**To Reproduce**

Assuming use of Chrome and 1920x1080 resolution: 

100% you see no arrows. 
110%, no arrows.
125%, arrows (shrink failed)
150%, no arrows, shrink worked!
175%, no arrows, shrink worked!
200%, arrows, this one is normal

**Expected behavior**
Shrink should work at all zoom levels

**Screenshots**

![image](https://user-images.githubusercontent.com/1638787/61452726-6f261c80-a92a-11e9-8d75-c9477a870224.png)

**Platform (please complete the following information):**
OS: Linux Mint 19.1
Browsers: Both chrome and firefox

**Additional context**

**Comment by pdanpdan** [comment]
This should be fixed in the latest release.
