### ISSUE TITLE
QDrawer mini to overlay when not bordered

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#4690]
**Describe the bug**

When using a QDrawer exactly the same way as shown in this example, it works correctly.
https://quasar.dev/layout/drawer#Mini-to-overlay

However, as soon as we remove the `bordered` property, we see the icons moving left/right by 1 pixel when hovering.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/MNWVwg?&editable=true&editors=101

**To Reproduce**
1. Mouse the cursor over the drawer to make the overlay open. The icons will move 1px to the left.
2. Move the cursor out of the drawer. The icons will move 1px to the right.

**Expected behavior**
The icons should not move, as is the current behavior when q-drawer is bordered.

**Platform (please complete the following information):**
OS: Windows
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
You need to specify the `mini-width`: in your case it's `:mini-width="56"`
Like here: https://codepen.io/anon/pen/OKJapa?&editable=true&editors=101
