### ISSUE TITLE
[v1] QToolbar - Scrolling behavior

### ISSUE THREAD

**Issue by acfatah** [quasarframework/quasar#4694]
**Is your feature request related to a problem? Please describe.**
Please refer to this [material.io](https://material.io/design/components/app-bars-top.html#behavior) website. It is trivial to be implemented but it is not guaranteed to work across devices. I think quasar development team have more expertise about this matter.

**Describe the solution you'd like**
New behaviors maybe like "scroll-fixed" - Upon scroll, QToolbar increase elevation and let content scroll behind it, "scroll-hide" - The QToolbar disappears upon scrolling up, and appears upon scrolling down, and "scroll-prominent" - When scrolling up, prominent top QToolbar can transform into normal toolbar.

**Describe alternatives you've considered**
Or maybe released as a quasar plugin.

**Additional context**
None.

**Comment by rstoenescu** [comment]
Hi,

This is pretty custom behavior. It can be done by listening to the `@scroll` and triggering an animation (written in CSS) for hiding, changing content of header, then showing it again. It just doesn't feel right to add this in a framework. Sorry for any inconvenience.
