### ISSUE TITLE
[v1] QPullToRefresh inside QPanel event trigger

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#4695]
**Describe the bug**
QPullToRefresh `@refresh` event triggers even when the page scroll is not on top of page inside a QTabPanel.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/metalsadman/pen/mNyORE?editors=1010

**To Reproduce**
1. Click 'Table' Tab
2. Scroll to bottom of page
3. Drag the content downwards
4. QPullToRefresh `refresh` event is fired

**Expected behavior**
QPullToRefresh `refresh` event should only fire when QTabPanel page scroll is at the top.

**Comment by pdanpdan** [comment]
Close this issue - please follow up in unified #5051
