### ISSUE TITLE
Allow JS manipulation into install API

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4696]
**Is your feature request related to a problem? Please describe.**
I'm trying to update TypeScript linting from deprecated TSLint to ESLint TypeScript plugin.
To do so, I have to update `.eslintrc.js` file, but there isn't an API to do so, like there is for JSON files. Such API could even not be possible, due to the dynamic nature of JS.
The process is tricky, because I should remove some entries, probably rearrange their order and add some in a specific order, which also dependes from linting options defined at install time (Prettier? Default? AirBnB?).

**Describe the solution you'd like**
I don't really have a solution, in this particular case probably the best idea is to integrate TypeScript tooling directly into the core and make it install at startup when we know about other inserted linting options. That's true especially because linting has not be thought as an AE (as far as I can see), so I have no way to know which linter preset I should prepare for, unless I manually try to detect it.

**Describe alternatives you've considered**
The most efficient thing I can do atm is to just copy/paste a prebuild `.eslintrc.js` file with all options I used, which is based on Prettier.

**Additional context**
See https://github.com/quasarframework/app-extension-typescript/issues/18

**Comment by IlCallo** [comment]
This should be mitigated by ESLint into core updates when it lands
https://github.com/IlCallo/quasar/tree/eslint-into-core

**Comment by rstoenescu** [comment]
This needs an AST engine and is outside of the scope of Quasar CLI...
