### ISSUE TITLE
[v1] esc button for $q.notify  close (as option) (when using timeout = 0)

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#4697]
i twould be nice, if there is would be a easy option for handling a notify close by
pressing esc .. I am often using "timeout: 0" and there is no option (as on dialog) to
activate this behaviour.

o mie de mulțumiri

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, this would have a huge impact on the page itself. Notifications are spawning on top of your page. If we add a global handler on the page, then we're essentially making a counter-intuitive behavior that breaks user's flow. Notifications should not interfere with the page in any way. Sorry if this is not what you wish to hear.

**Comment by ibrainventures** [comment]
No problem, thanks for throw a eye on this little request.
