### ISSUE TITLE
Expansion Item - add collapse-icon

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#4699]
I want to use different icons for expand and collapse. Now I can either use the default icon or use a custom one that will inherit a rotating effect. 

Adding an optional prop: `collapse-icon` will offer more flexibility.

**Comment by matthiasmeier** [comment]
I would call it `expanded-icon` instead. From a user / UI point of view these arrows are not necessarily seen as "actions" / buttons (expand/collapse) but as indicators for the current state (collapsed/expanded).

This is also the reason why there are many discussions whether the solution with the downwards arrow for collapsed state and upwards arrow for expanded state are "correct" (read: "feel right") or confusing. Even though this approach is used in a huge number of websites and apps (including Material Design and Quasar) it feels wrong for many users (including myself) depending on the visual appearance of the element.

Personally, I usually see it more as an indicator of the current state when the icon is part of the design of the clickable element (e.g. default behaviour in Quasar). Therefore I would also prefer it to point towards the parent element’s text when collapsed and downwards when expanded.
BUT: When only the icon itself is clickable and triggers the action (as when used with `expand-icon-toggle` in Quasar) AND the design is clear in that way (e.g. the icon is styled like a button) – I also prefer the downwards/upwards approach that is currently implemented. (As it then indicates the action that will happen, WHEN you click that button/icon.)

A good read on that topic is this article on Smashing Magazine: 
https://www.smashingmagazine.com/2017/06/designing-perfect-accordion-checklist/

**Comment by rstoenescu** [comment]
Hi,

Thanks to both of you for the discussion over it.
Added "expanded-icon" prop (which, when used, it also disables the rotating animation -- because the rotation doesn't makes any sense anymore). Will be available in "quasar" v1.4.5.
