### ISSUE TITLE
[Request] UTC timezone mode for date/datetime picker

### ISSUE THREAD

**Issue by NothingWeAre** [quasarframework/quasar#470]
I would like to request a setting to use single instance of datepicker in UTC mode.
I have project where backend (which i cannot control) expects UTC date, but with timezone aware datepicker selected date can change depending on user timezone and current time.
Which is unexpected behavior for datepicker (without time selection).

Example with Europe/Kiev timezone:
Time of test: `22:24:26`
selected date: `2017-03-01 `
MODEL: `2017-03-01T20:24:26.000Z`

Time of test: `01:36:49`
selected date: `2017-03-01 `
MODEL: `2017-02-28T23:36:49.000Z`

and even daylight saving plays with data (different time delta):
Time of test: `01:46:11`
selected date: `2017-04-01`
MODEL: `2017-03-31T22:46:11.000Z`

PS. it would be good if there was an option to accept selected date by click on "day" number. Without needing to press "set" button

**Comment by rstoenescu** [comment]
Sounds like a good idea. Will do.

**Comment by rstoenescu** [comment]
Done for v1.0.
