### ISSUE TITLE
Qeditor component ordered list tool always applies to first element instead of cursor on Safari

### ISSUE THREAD

**Issue by geoidesic** [quasarframework/quasar#4700]
**Describe the bug**
Qeditor component ordered list tool always applies to first element instead of the element at cursor position. Only occurs in Safari.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/noeldacosta/a9rdm3pj/2/

**To Reproduce**
1. Open the fiddle in Safari
3. Click inside the editor
2. Type 3 paragraphs of text
3. Select the last paragraph
4. Click the ordered list tool
5. Notice that the first paragraph becomes an ordered list

**Expected behavior**
The paragraph nearest to the current cursor position should be the element that is altered to become an ordered list.

Same applies to unordered list.

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: OS X Mojave 10.14.5 (18F203)
Node: v12.6.0
NPM: 6.9.0
Yarn: 1.16.0
Browsers: Safari only v12.1.1 (14607.2.6.1.1)
iOS: (haven't tried it)
Android: (haven't tried it)
Electron: (haven't tried it)

**Additional context**
Issue only occurs in Safari

**Comment by rstoenescu** [comment]
Grouping with https://github.com/quasarframework/quasar/issues/4349
