### ISSUE TITLE
Wrong formatting Japanese for QDate header

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4701]
I'm seeing this on the default QDate header on Japanese:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/3253920/61532178-f925d080-aa63-11e9-9a6e-cad7acc071a8.png">

However, instead of:
```
金, 7月 19
```
it should be:
```
7月19日（金）
```
With those brackets included, this is the only way dates with the short form of the day is written in Japanese. Not the other way around and not without brackets.

Is it possible to set the formatting for the header of QDate for Japanese somewhere in the language files maybe? **I will PR if someone can point me to the correct file.**

**Comment by rstoenescu** [comment]
Hi,

Doing an equivalent thing (check link below) for the required Quasar language pack would solve this.

https://github.com/quasarframework/quasar/blob/dev/ui/lang/zh-hans.js#L24

Thanks for wanting to contribute!

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.0
