### ISSUE TITLE
Layout drawer not working properly when overlay in Chrome

### ISSUE THREAD

**Issue by cashmisa** [quasarframework/quasar#4704]
This bug happens when I test on chrome, doesn't happen in firefox
When drawer overlay the content (e.g. open in a smaller screen) , I found a number of items not working.  And all of the problems goes away in full screen mode

Here are some problems you can see even via [quasar page](https://quasar.dev/layout/drawer) when you are in a smaller screen mode
1. When click on the clickable q-items, it doesn't navigate to the route specified
2. Doesn't expand/collapse with q-expansion-item (It works sometimes but I can't seem to find the pattern)
3. Unable to type in the top search box; If typed a search term in the drawer search box in full screen mode, then resize the browser causing drawer menu to overlay, search term is still there but unable to edit.
4. Button works half of the time (can't find the pattern either..)
5. Drawer menu doesn't hide when click on backdrop

Thanks for your time!

**Comment by pdanpdan** [comment]
Please reopen with information about desktop/tablet/mobile, OS and browser (and version) please.

I cannot reproduce any of the problems in the list, neither on desktop (windows chrome/firefox/IE) nor on mobile (android chrome).

Please also check if you have errors in the console.

**Comment by cashmisa** [comment]
Thanks for looking into this. It happened only in my Chrome (version 75.0.3770.142 Official Build 64-bit). I have tried all of the above again and realized that errors happen only whenthe input mode of the page is using a specific software (Sogou Pinyin). No error in console but warning of `[Violation] Forced reflow while executing JavaScript took <N>ms`

When I change to Window's default input in english/chinese, it goes away. So there is no need to reopen this. Thanks again!

**Comment by enpasos** [comment]
I'm experiencing the same problem on my browser - unfortunately I do not have the option to change to a different browser. My experience: 
```
Quasar v.1.1.0
Google Chrome
Version 76.0.3809.132 (Offizieller Build) (64-Bit)
https://quasar.dev/start
Reduce size of browser window until left drawer dissapears.
Click on toolbar button to open left drawer. It opens, but then it is more ore less unresponsive, e.g. it does not close when clicking on the page.
```

**Comment by rstoenescu** [comment]
@enpasos I have the exact same Chrome build, but cannot reproduce... Anyone else seen this behavior?

**Comment by enpasos** [comment]
after resetting settings
chrome://settings/reset
it seems to work like a charm
no idea which setting was causing the behaviour
