### ISSUE TITLE
[v1] Feature request: QSelect autocomplete

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#4708]
**Is your feature request related to a problem? Please describe.**

QSelect offers no full support for autocomplete.

**Describe the solution you'd like**

In Google, when you partially type your query and then navigate with the arrow keys in the autocomplete popup menu to select one of the query suggestions, the focused query suggestion is placed in the search textbox replacing the partial query.

When you then continue typing, the typed text gets appended to the replaced partial query.

For example, if you want to query for "quasar qselect", in google it is enough to type "quas", then navigate to "quasar", then continue by typing "qsel" and navigate to "quasar qselect".

In Quasar QSelect, when you navigate the results of a partial query, the textbox remains unchanged, therefore not allowing you to continue to compose a more fine grained query.

See the following example:
https://codepen.io/danielfaust/pen/KOgJxP?editors=1010#0

**Describe alternatives you've considered**

Maybe this issue could be solved if an option would be added which enables a Google-like behavior.

The problem which will most likely be encountered is that when changing the bound variable value on each menu entry focus change (in order to update the UI) is that each change would then trigger a new query, which is absolutely not desired, as it would change the contents of the options list just by navigating the menu entries.

The JQuery Autocomplete example at https://jqueryui.com/autocomplete/ may be somewhat helpful.

**Additional context**

Google:
![B8DE8D05-6396-4353-A4A1-370F96B26569](https://user-images.githubusercontent.com/320098/61579746-82dba980-ab09-11e9-9f48-b11b7155bd05.GIF)

QSelect
![42367C25-CE5E-49F1-8223-796BD72870A9](https://user-images.githubusercontent.com/320098/61579775-abfc3a00-ab09-11e9-94d7-982aad5b00a9.GIF)

**Comment by rachitpant** [comment]
@danielfaust Would you mind sharing your code to achieve the `q-select-and-filter-as-you-type` functionality you showed above. I wanted to achieve the same thing , and was able to do that earlier with q-autocomplete but with the newer q-select , I get a popup modal on top of the screen where this happens , instead of happening in place like you are doing above.
To better understand my issue : https://github.com/quasarframework/quasar/issues/4732
I am wondering if that modal shows up only on mobile apps.

**Comment by danielfaust** [comment]
@rachitpant Yes, I will try to adapt the code in order to give you an example in CodePen. Give me some time. But I can tell you that yes, that modal is showing up only on mobile. The animated gif is made on a desktop.

**Comment by danielfaust** [comment]
@rachitpant Here it is: https://codepen.io/danielfaust/pen/KOgJxP?editors=1010#0

I changed it to Wikipedia, since Google has CORS issues (I proxy my Google queries and add the `access-control-allow-origin: *` in the proxy, but that can't be done with CodePen and the like)

Feel free to add this to the examples (probably after cleaning it up a bit)

**Comment by rachitpant** [comment]
Thanks , really cool example , but looks like on phone the modal always shows.

**Comment by rstoenescu** [comment]
`use-input` and `fill-input` will have this behavior in 1.0.6.

**Comment by danielfaust** [comment]
Just upgraded, works like a charm. Thank you!
