### ISSUE TITLE
IOS search Input field bug

### ISSUE THREAD

**Issue by 7ammer** [quasarframework/quasar#471]
Hello, found a bug :)

IOS version of the [search component](http://quasar-framework.org/components/search.html) has a delay of about a 1.5 second before the FIRST key input is recognised. This means the user needs to wait after typing the first key before typing the rest of a word. If the user doesn't wait then the first key isn't recorded and you end up with values like "ello" instead of "Hello".

Android's search input field does not have this issue. 

This bug is evident on the main site: [search component](http://quasar-framework.org/components/search.html)

**Comment by rstoenescu** [comment]
Confirmed. Will be fixed in v0.14.

**Comment by rstoenescu** [comment]
Fixed in future v0.14.

**Comment by 7ammer** [comment]
Hello :) Quick question. Is this fix in v0.13.9? I believe you've stated else we're that v0.13.9 is practically the same as v0.14 right now. If so I'm still seeing this issue.

**Comment by rstoenescu** [comment]
Hi, v0.13.x has nothing to do with v0.14. Wait for the v0.14 release to see this fix. Thank you!
