### ISSUE TITLE
Theme Builder in FF: color selection box unstable on smaller screen

### ISSUE THREAD

**Issue by danicholls** [quasarframework/quasar#4710]
**Describe the bug**
In the Theme Builder, opening a color-section box will make it flicker between different sizes if your screen is not large (e.g., under 1300 px wide, or 580px tall). I've tried it in Firefox and Chrome, and only had it happen in Firefox.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/style/theme-builder

**To Reproduce**
1. Make sure your window is below 1300px or narrower (or 580px or shorter).
2. Go to https://quasar.dev/style/theme-builder .
3. Click on any of the color selection boxes, like Primary.
4. The box will rapidly alternate between sizes/states.

**Expected behavior**
It will just sit there, like a good color-selection box.

**Screenshots**
![image](https://user-images.githubusercontent.com/5094893/61586429-cc87bc80-ab28-11e9-9a5c-e2a7f8087db8.png)
![image](https://user-images.githubusercontent.com/5094893/61586436-e9bc8b00-ab28-11e9-80bc-729a3b3acf1b.png)

**Platform (please complete the following information):**
OS: Windows
Node: n/a
NPM: n/a
Yarn: n/a
Browsers: Firefox
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**
None. Is there a repo to just report stuff for the site? Great work, keep it up!

**Comment by rstoenescu** [comment]
Hi @danicholls ,

Thanks for reporting! Does it happen anymore? I can't get to reproduce, but I'm on a mac and so the platform that I am testing with may slightly differ.

**Comment by danicholls** [comment]
Yep! Still happens. (Still only in FF.)

**Comment by danicholls** [comment]
It is a little inconsistent, though. And sometimes resizing the height triggers it.

**Comment by rstoenescu** [comment]
Thank you for the details. Will investigate.

**Comment by ejez** [comment]
Same, Firefox 69.0.2 (64-bit) in ubuntu
![theme-builder-issue](https://user-images.githubusercontent.com/48388358/68101000-6c9d0200-fedc-11e9-92d5-3e88b4b631ee.gif)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.3.1 (thanks to @ejez).

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.2
