### ISSUE TITLE
a problem about quasar dev

### ISSUE THREAD

**Issue by danzhoua** [quasarframework/quasar#4712]
**Describe the bug**
hi,my vue-cli version is 3.2.2,quasar-cli version is 0.17.26,eveything is ok until working on quasar dev. The project cannot be opened automatically while working on quasar dev. May I ask what's wrong.

**Codepen/jsFiddle/Codesandbox (required)**

![image](https://user-images.githubusercontent.com/15057816/61627992-a6425800-acb3-11e9-8601-480fbc2428f5.png)

![image](https://user-images.githubusercontent.com/15057816/61628184-2cf73500-acb4-11e9-890f-c391238e3c4e.png)

**Comment by rstoenescu** [comment]
Hi,

Seems like you're mixing a 0.17 project with a 1.0 one? Please visit our Forum or Discord to get help. Thank you.
