### ISSUE TITLE
Wrapping custom QTree header in a div <div @click.stop @keyup.13.32.stop> doesn't prevent expanding of leaf when space is pressed

### ISSUE THREAD

**Issue by Sonit90** [quasarframework/quasar#4715]
**Describe the bug**
My header looks like this:
<template v-slot:default-header="prop" >
                <div class="q-gutter-x-md" @mouseover="showByIndex =prop.node.id" @mouseleave="showByIndex =null">
                    <div class="row items-center node-container" >
                        <img :src="imgUrl(prop.node.img)" class="custom-avatar q-mr-sm" v-if="prop.node.img">
 
                    <q-input @click.stop  autofocus dense
                            v-if="editable===prop.node.id" hide-bottom-space
                            @keyup.13="doneEditing" v-model="prop.node.title" class="text-weight-light text-black tree-label" />
                    <span v-on:dblclick="edit(prop.node)" v-else class="text-weight-light tree-label">{{prop.node.title}} </span>
                    <transition name="fade">
                    <q-btn-group rounded v-show="showByIndex === prop.node.id" class="text-black button-group">
                        <q-btn @click.stop="addNode(prop.node)" color="grey-3" icon="add" rounded size="xs" text-color="black"/>
                        <q-btn @click.stop="edit(prop.node)" v-show="editable!==prop.node.id"  color="grey-3" icon="edit" rounded size="xs" text-color="black"/>
                        <q-btn v-show="editable===prop.node.id" @click.stop="doneEditing" color="grey-3" icon="check" rounded size="xs" text-color="black"/>
                        <q-btn @click.stop="removeNode(prop.node,prop.node.id)" color="grey-3" icon="remove" rounded size="xs" text-color="black"/>
                    </q-btn-group>
                    </transition>
                </div>
                </div>
            </template>
When i edit the input and press space, my leaf trigger expanded state, but i want it to put space inside input. Wrapping header in div from docs doesn't work, as well as attaching @keyup.32.stop to the input, or div

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/LwpPwY

**Expected behavior**
Space doesn't trigger expand, when QTree is wrapped in a div

**Platform (please complete the following information):**
OS: Windows 10
Node:  v10.15.3
NPM: 6.4.1
Yarn: 1.17.3
Browsers: Google chrome 75

**Comment by pdanpdan** [comment]
- use `@keypress.13.32.stop`
- you use `label` as `nodeKey` and you try to modify the label

Updated codepen: https://codepen.io/anon/pen/OKRyQy?editors=1010
