### ISSUE TITLE
Custom arrow color and icon in QBtnDropdown

### ISSUE THREAD

**Issue by pavchip** [quasarframework/quasar#4717]
**Is your feature request related to a problem? Please describe.**
It would be nice to change the arrow icon and its color for `q-btn-dropdown` not globally (through `this.$q.icon.input.dropdown` property), but individually.

**Describe the solution you'd like**
Add `arrow-icon` and `arrow-icon-color` properties to `q-btn-dropdown` component.

**Describe alternatives you've considered**
At the moment I have to changing the icon and its color with Stylus which in my opinion is not convenient.
```stylus
.btn-dropdown__arrow-icon .q-icon
  color blue
  display inline-block
  overflow hidden
  text-indent -9999px

  &:before
    content 'keyboard_arrow_down'
    text-indent 0px
```

**Comment by sebastien-prudhomme** [comment]
@pavchip I think this is done since v1.1.6 for the icon part.

There is now a `dropdown-icon` option in the component.

**Comment by rstoenescu** [comment]
Yes it is. Closing ticket.
