### ISSUE TITLE
QInput - autoselect property

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#4718]
**Is your feature request related to a problem? Please describe.**
When working with text fields, it is often necessary to completely update the field value. This is especially noticeable when working with monetary values. Additional inconveniences arise when working on the virtual keyboard of a smartphone, when in order to replace an existing value, it must first be erased.

**Describe the solution you'd like**
A possible simplification of this type of interaction could be the addition of an `autoselect` property (by analogy with `autofocus`). So if this property is specified, the value of the text field will be selected immediately after this field was selected by the user.

**Describe alternatives you've considered**
Today, the solution of this situation can be the simultaneous use of `ref` and `@focus="$refs.NAME.select()"` event, but this is more verbose and requires the use of `ref`.

https://codepen.io/anon/pen/PMZEoQ?&editable=true&editors=101

**Comment by pdanpdan** [comment]
You can simply use the `event.target` from the focus event, like here: https://codepen.io/anon/pen/jgMbOW?editors=1010
