### ISSUE TITLE
Quasar does not work in embedded/hosted Internet Explorer

### ISSUE THREAD

**Issue by tavi-cacina** [quasarframework/quasar#4719]
**Describe the bug**
Empty content is shown when opening a Quasar App in an embedded Internet-Explorer window, despite Edge-compatibility setting in meta header. A vue.js app is working fine. Also in a regual InternetExplorer window, Quasar is working fine. I suppose some 'window.' property is queried, that in hosted context is missing. Since Vue.Js is working, hopefully is not something too serious.

**Codepen/jsFiddle/Codesandbox (required)**
Not applicable.

**To Reproduce**
1. Unpack the attached IEHost.zip, this is a basic application that was generated by the WTL App-Wizard. Only the URL was changed to open 'http://localhost:8080/'
2. Generate a quasar app, enable IE support in the assistant.
3. Add in the index.template.html in head section the `<meta http-equiv="X-UA-Compatible" content="IE=edge">`
4. Start quasar dev
5. Start IEHost/Release/IEHost.exe, it will open the http://localhost:8080/
6. Notice that the page is empty, only a small scrollbar is shown in the top/right corner.

**Expected behavior**
The Qasar App should be shown in the hosted IE window.

**Platform (please complete the following information):**
OS: Windows 10
Node: v10.14.2
NPM: 6.4.1
Browsers: Internet Explorer 11 Embedded/Hosted in Edge compatibility mode.

**Additional context**
[IEHost.zip](https://github.com/quasarframework/quasar/files/3421752/IEHost.zip)

**Comment by tavi-cacina** [comment]
Because Edge based on Chromium will be released at some point and it provides embedding capabilities, I do not think is important to search a solution for this.

**Comment by marcelo-rebello** [comment]
I having a really similar issue and need to run Quasar embedded in an old windows32 App that depends on IE installed on the machine.
App looks like is running, but no response from mouse or most keyboard events.
Still working navigation with tabs, but components do not get focus (so the form is useless)
enter is also ignored.

PS it doesn't work with `<meta http-equiv="X-UA-Compatible" content="IE=edge">`
