### ISSUE TITLE
q-menu inside q-item does not work.

### ISSUE THREAD

**Issue by softlan** [quasarframework/quasar#4720]
**Describe the bug**
q-menu inside q-item does not work if q-item has a clickable property.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/2uw4agh8/1/

**To Reproduce**
1. Go to https://jsfiddle.net/2uw4agh8/1/
2. Click the button to the right

**Expected behavior**
The menu should open.

**Platform (please complete the following information):**
Browsers:

**Comment by pdanpdan** [comment]
Just add a `.stop` modifier on the `@click` like here: https://jsfiddle.net/81zocd9L/

**Comment by softlan** [comment]
Thank!
