### ISSUE TITLE
Inverted colors for Qtabs[docs]

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#4721]
It would be nice if the document included some information on how to implement the inverted property in quasar v1.
I was upgrading a legacy project to v1 , and couldn't find information on how to make a Q-tab show with inverted colors. ie. bg white and icons and text with primary color.
In legacy quasar , this could be implemented with simply inverted=true.

In general, if with in the upgrade guide you can provide more information on alternatives for attributes that have been removed ( just like you mention the alternatives for components that are removed ).

**Comment by metalsadman** [comment]
@rachitpant ios theme isn't supported out of the box in v1, what you could do is use helper classes to achieve those, classes like `bg-white text-primary` for example. https://quasar.dev/style/color-palette#Using-as-CSS-Classes. see this one for example https://quasar.dev/layout/header-and-footer#iOS-look-and-feel

**Comment by rachitpant** [comment]
Thanks , that was helpful.
