### ISSUE TITLE
Mobile Responsive Table not working with action items

### ISSUE THREAD

**Issue by piyush-multiplexer** [quasarframework/quasar#4724]
**Describe the bug**
The issue is in <q-table> component with responsiveness. When i use action items or custom rendering mechanism in column fields but when i resize window, and it convert to card it causes the issue in card rendering. In card action items not showing up, or custom html not rendering.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/piyush-multiplexer/pen/eqZBPG

**To Reproduce**
1. Go to codepen link
2.resize browser window for small window size because of sm grid config
3. As result only name field not rendering but action field is being rendered in place of name while in my project action buttons are not rendering in action field but other fields are rendering.

**Expected behavior**
Result should be when resize window to any screen size fields should be mapped to their value without missing any value in web and mobile size both.

**Screenshots**
Original Table in Web
![image](https://user-images.githubusercontent.com/18528418/61765629-730ae080-adfb-11e9-9914-fa035e599b79.png)
Responsive Table in Mobile Resolution[with missing action field values]
![image](https://user-images.githubusercontent.com/18528418/61765670-a5b4d900-adfb-11e9-941e-30f38cef29f5.png)

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 8.11.3
NPM: 6.8.0
Yarn: 1.12.3
Browsers: Chromium

**Comment by metalsadman** [comment]
@piyush-multiplexer fixed your q-separator (self closing tag don't work in codepen/jsfiddle), added v-if so your action only shows in your header.
https://codepen.io/metalsadman/pen/KOzvxj?editors=1010

**Comment by piyush-multiplexer** [comment]
thanks for response,
i get it that conditional rendering for header but we have to code for mobile responsive cards in table while quasar should able to handle automatically.

[https://codepen.io/piyush-multiplexer/pen/EqyoyB](https://codepen.io/piyush-multiplexer/pen/EqyoyB)

In this Pen i didn't write code for responsive table but only write basic table only but it didn't convert to cards.

**Comment by metalsadman** [comment]
I dont see why it should, once you are overriding a slot. The grid props does only default settings which is to grab what your colums definition not the component that you added like your actions, so youll definitely have to override the items too peryour initial pen.
