### ISSUE TITLE
`q-scroll-area` inside `q-drawer` bug on macbook Safari

### ISSUE THREAD

**Issue by iMakedonsky** [quasarframework/quasar#4725]
`q-scroll-area` inside `q-drawer` bug on macbook Safari browser on quasar docs page.
Please see video: https://drive.google.com/file/d/1gejLm8QTz9dNGHzR1e7gClDk1lwJpEKq/view?usp=sharing
When i try to scroll inside the drawer, it scrolls inside page container instead.

Macbook has the latest MacOs/Safari updates.
It works well in mobile safari though.

**Comment by nothingismagick** [comment]
@iMakedonsky - I can confirm that this is happening.

**Comment by rstoenescu** [comment]
Hi,

This can be done, but would decrease performance. The algorithm is very CPU intensive. We would rather leave it as is as the drawbacks far outweigh the benefits. Sorry for any inconvenience.
