### ISSUE TITLE
[Request] Multiple dates in DatePicker

### ISSUE THREAD

**Issue by RobbeVorsselmans** [quasarframework/quasar#4727]
Hi all,

I was hoping to use a DatePicker that could select multiple dates, but this seems to be impossible in Quasar. I'm looking for the same functionality as in [Vuetify](https://vuetifyjs.com/en/components/date-pickers). (multiple option)
In the ideal case there would be a maximum number of dates to pick and a possibility to drag in order to select a range, but that's not realy necessary. Just clicking multiple dates and recieving them in an array would be nice.

Kind regards and thanks for taking a look.
Robbe

**Comment by metalsadman** [comment]
@RobbeVorsselmans your link is pointing back to quasar github page btw.

**Comment by RobbeVorsselmans** [comment]
> @RobbeVorsselmans your link is pointing back to quasar github page btw.

Thanks for your comment. I fixed it.

**Comment by metalsadman** [comment]
@RobbeVorsselmans you can try with q-select chips https://codepen.io/metalsadman/pen/oKLzdY?editors=1011. the only missing is q-date plotted dates.

**Comment by RobbeVorsselmans** [comment]
Thank you for the suggestion, this could definetely work for an MVP.
But having a visual feedback (all picked dates in a blue circle) seems essential to me.

**Comment by metalsadman** [comment]
> Thank you for the suggestion, this could definetely work for an MVP.
> But having a visual feedback (all picked dates in a blue circle) seems essential to me.

yep, while this isn't available yet. what you could do for now is also set the `event` prop with the selected dates array, at least it has some sort of indicator that it's already selected. updated the pen https://codepen.io/metalsadman/pen/oKLzdY.

**Comment by RobbeVorsselmans** [comment]
What a great idea! Apart from being able to simply remove a selected date by clicking it again, this behaves exactly as intended when keeping the qDateProxy from closing after a date was selected.
Thank you very much @metalsadman. As this was the only thing stopping me for choosing Quasar for my next project I'll certainly will give it a go!

Anyhow, I'd like to keep this request open, since I still think it would be a great function with lots of user cases that I'm sure the community would appreciate.

**Comment by pdanpdan** [comment]
Close this issue - please follow up in unified #5052
