### ISSUE TITLE
QDate: let the `locale` prop be a string

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4728]
When we need to localize the QDate calendar, we currently need to provide an object with the name of days, months, short days etc..

Browsers know these things already and we don't need to clutter our code with them, we should be able to provide a string for a locale, such as `de-DE` or `ar-EG`, and Quasar would internally use `Date.prototype.toLocaleDateString()` to figure out the names.

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Date/toLocaleDateString

Providing an object to the `locale` could stay as a bonus for people who don't want to use standard names.

**Comment by pdanpdan** [comment]
Is is used when you want to parse the time from localized formatted string values.

**Comment by louisameline** [comment]
`toLocaleDateString` can be used to translate to any locale passed to it, I don't understand why you're saying this.

**Comment by pdanpdan** [comment]
For formatting yes, but not for parsing. We need to be able to parse also.

**Comment by louisameline** [comment]
I see. The parsing part feels clunky to me though.  

1. I bet it's useless computation for most people, as dates should be manipulated in a raw format and formatted only for display. The component should ask a standard format for input, parseable by the native `Date.parse`, it would be much quicker.

2. Parsing/formatting of dates should be left to the date util, if necessary.  

The `mask` prop on qDate feels like a gimmick, Quasar is reinventing the wheel for not much. A single component doesn't have to do everything. Asking for day and month names in this component really feels silly.

And as a side note, I love the project but it feels like tickets (not just this one) get closed before there was a chance to discuss the topic. Maybe the team is too busy for to hear feedback from users? I could understand that but it doesn't make me want to get involved to be honest. Thank you for your work anyway.

**Comment by nothingismagick** [comment]
I am sorry to hear that you feel like the team is too hasty to close issues
without enough discussion. You are definitely not the first person to
complain about our date implementation, it's been hotly debated a number of
times and in great detail. At the moment I am mobile or I'd search through
the closed issues and dig you out a few.

I would be interested however in continuing the discussion with you in a
more real time manner, perhaps on our discord channel where you might be so
kind as to afford me the chance to listen to your concerns.

**Comment by louisameline** [comment]
Absolutely, thank you, I'd love to know more. It's 2am here and I'm going to sleep but I'll come visit Discord soon if that's where discussion is happening. Thank you
