### ISSUE TITLE
Floating point error for q-range control

### ISSUE THREAD

**Issue by likecao** [quasarframework/quasar#473]
### Software version

Quasar:0.52
OS:Windows10
Browsers:Chrome56.0.2924.87
Any other software related to your bug:

### What did you get as the error?
`<q-range v-model="number" :min="0.1" :max="1.0" :step="0.1" snap></q-range>`
Console error:Range error: step must be a divisor of max - min undefined 0.1 1 0.1.
If change range，number: 0.7999999999999999 or  0.30000000000000004.

**Comment by rstoenescu** [comment]
Will investigate.

**Comment by rstoenescu** [comment]
Available in future v0.14.
