### ISSUE TITLE
[v1] QSlideTransition animation ends prematurely if you hover over or click certain elements (QInput, QBtn, QCheckbox, etc.)

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#4731]
**Describe the bug**
If a `<q-slide-transition>` contains certain elements (`<q-input>`, `<q-btn>`, `<q-checkbox>` at least) and you hover over and/or click them, the animation ends immediately. Seems to be anything that causes a content change on hover/click?

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/mNEyjq

**To Reproduce**
1. open the CodePen above
2. Click on the "Show" checkbox.
3. Notice the slow (10s) animation.
4. Hover over the contained input, button, or click on the contained checkbox before the animation finishes naturally.
5. Notice the animation ends almost immediately.

**Expected behavior**
The animation continues for the expected duration.

**Platform (please complete the following information):**
OS: Windows_NT(10.0.17763) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Yarn: 1.17.3
Browsers: Firefox 68.0.1, Chrome 75.0.3770.142

**Additional context**
This makes it impossible to have a "collapse/close" button within a `<q-slide-transition>` with a smooth animation because the animation will end almost immediately.

**Comment by pdanpdan** [comment]
You have elements that emit `transitionend` events inside the content. I'll make a PR to solve this, but untill then you can just wrap the content inside the `<div v-if="show">` in a `<div @transitionend.stop="log">`.

https://codepen.io/anon/pen/OKgoLw?editors=1010

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in 1.0.6.
