### ISSUE TITLE
Q-Select is not able to replace Q-Autocomplete UI.

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#4732]
While I appreciate the great efforts put in to release v1 , there are some components that are not so polished in v1 . We have a cordova app out with v0.17 and wanted to keep similar UI , However with the new v1 , we are not able to achieve similar UI for auto-complete fields.
eg. Here is how the auto-complete with q-autocomplete looked like before:

Old code:
```
  <q-chips-input v-model="recipientsNames" float-label="To" class="input" @remove="removePeople" >
    <q-autocomplete @search="searchPeople" @selected="selectPeople" value-field="label" />
  </q-chips-input>
```

![image](https://user-images.githubusercontent.com/1474415/61826152-da428800-ae2f-11e9-856d-c55607af7782.png)

Everything works perfectly fine above. Problem starts when I replace the now defunct q-autocomplete with q-select to implement the ajax dropdown, I see a new modal that comes on top of the page , instead of showing the filtered possible select values in place , like you see above. We are showing the same information , once in the foreground modal , and second time in the actual page doesn't make sense. The foreground modal does go away when you click somewhere, but still ? Can't it be in place.

Plus, there is another issue, once you make a selection , the letters you have typed in do not clear up even after you make a selected. eg. I selected Ryan from the dropdown after typing in 'Rya' , however you still see 'Rya' along with the q-chip for 'Ryan Koors'.

The new code:

`<q-select multiple v-model="recipientsNames" label="To" @filter="searchPeople" :options="recipientOptions" @selected="selectPeople" use-input use-chips />`

![image](https://user-images.githubusercontent.com/1474415/61826388-4fae5880-ae30-11e9-9cc4-afb940c04aef.png)

Even if you want to make the q-select more powerful, why not let the q-autocomplete still be there. Would save a lot of people a few hours.

**Comment by rstoenescu** [comment]
New prop will be available in 1.0.6 for QSelect: `behavior`.

**Comment by rachitpant** [comment]
Thanks for the fix for the first issue , I am not sure how to get around the second issue highlighted here. Once user selects something , what you have typed so far , starts showing to the right of the selection. There is a hide-selected property , but it doesn't work with 'multiple'. ( Which should work , once i select "ryan koors" above after typing "Rya" , there is no reason why those three letters should still show ) . Thank you for your efforts.

**Comment by rstoenescu** [comment]
The `hide-selected` prop refers to the left-side where's the enumeration of the currently selected values. It does not interfere with what the user has typed.
Furthermore, what the user typed should remain as-is (when `multiple`) in order to not change/reset the options displayed below (which would make further selecting adjacent options -- the most common usage -- a hassle).

**Comment by rstoenescu** [comment]
![hide-selected](https://user-images.githubusercontent.com/4665641/64487447-8ce57300-d243-11e9-8c81-bbe88c02816a.png)
