### ISSUE TITLE
Explanation around quasar-bogus-chunk for workbox?

### ISSUE THREAD

**Issue by hailwood** [quasarframework/quasar#4733]
Right now there's something interesting going on in the pwa build when you run `quasar dev`
https://github.com/quasarframework/quasar/blob/56cd7fb09afe0cfb2389ab4b5065c90ab21d4068/app/lib/webpack/pwa/index.js#L68-L72 where it pushes on a bogus chunk (named quasar-bogus-chunk)

I'm looking for an explanation around what it's actually doing?

Workbox V5 is around the corner (and actually works with Quasar as is!) but this technique will cause a compilation warning as it now explicitly checks for chunks that do not exist (see https://github.com/GoogleChrome/workbox/issues/1287 for context)

https://github.com/GoogleChrome/workbox/blob/v5.0.0-alpha.1/packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js#L94-L101

I've asked the workbox team about the issue and here's what they had to say

![image](https://user-images.githubusercontent.com/709773/62014602-425de900-b1f7-11e9-89d4-7b84920805b0.png)

I'm wondering now if we are best to as suggested by @jeffposnick skip the serviceworker all together on dev builds (and why we're currently not), and whether the `quasar-bogus-chunk` is an odd attempt to do this?

/ I'm not sure bug was the most appropriate option, but figured it's a potential future bug?

**Comment by nothingismagick** [comment]
Hi Hailwood, 

You can remove this chunk in your PWA workbox settings:

```
pwa: {
  workboxOptions: {
    excludeChunks: true,
  }
}
```

I didn't write this code, but my assumption is that it is a shim. Of course its only an issue with the development environment. If you were seeing bogus chunks in a build I think we would all have grounds to be concerned.

Will leave this open until Razvan can have a chance to look at it.

**Comment by hailwood** [comment]
Hey @nothingismagick I don't think that will have any effect since on a dev build we seem to be explicitly wiping out the `excludeChunks` options?

```
if (opts.excludeChunks) { 
   delete opts.excludeChunks 
 } 
```

Side note, I've updated the original issue with more information.

**Comment by rstoenescu** [comment]
This one has become obsolete starting with "@quasar/app" v1.8 as it no longer uses this strategy.
