### ISSUE TITLE
Recompiling and App hot update fail after fixing object typo error

### ISSUE THREAD

**Issue by linhtranvu** [quasarframework/quasar#4734]
**Describe the bug**

Recompiling and App hot update fail if array mistake

**To Reproduce**

0. Disable linting
1. Have a mis typo: Eg `object.` (without property)
2. Save vue file, error and need to fix
3. Fix to `object.name`
4. Recompiling and App hot update does not work anymore. Need to stop and start app again

**Platform (please complete the following information):**
OS: Window 7
Quasar: 1.0.5

**Comment by rstoenescu** [comment]
Is this still valid?
