### ISSUE TITLE
roperty 'install' is missing in type 'typeof import

### ISSUE THREAD

**Issue by pupupu-land** [quasarframework/quasar#4736]
** dist/types/index.d.ts did not declare install **

This error appears when calling Vue.use(Quasar) with typescript

`Property 'install' is missing in type 'typeof import("d:/pro/jingrise/dmce-erp/browser/node_modules/quasar/dist/types/index")' but required in type 'PluginObject<{ config: { loadingBar: { color: string; }; }; }>'.ts(2345)`

We can solve this problem by declaring install in index.d.ts. Can you implement it?

**Comment by outofmemoryagain** [comment]
@pupupu-land based on your request description this was introduced in #4645.  Please verify and close.

**Comment by rstoenescu** [comment]
Thank you, @outofmemoryagain and @pupupu-land for getting a resolution on this one!
