### ISSUE TITLE
QEditor @blur event when clicking on toolbar

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#4737]
**Describe the bug**
QEditor losing focus when toolbar buttons are pressed.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/SharpBCD/pen/aeZgEj

**Expected behavior**
Not losing focus when clicking the toolbar. 
In the implementation I use, I render the html text in a simple QPanel div. When clicked, it turns into an editor (for users with edit rights). When the user move to another field it should reverse to simple div to save space.
Now it works except when tooldbar is used and `@blur` event is called.

**Screenshots**
![simple-html-rendering-panel](https://user-images.githubusercontent.com/31144210/61883799-c10b0b80-af03-11e9-96f1-c17e849979b4.png)
![turn-into-qeditor](https://user-images.githubusercontent.com/31144210/61883801-c10b0b80-af03-11e9-9741-f5ba03e98c81.png)

**Comment by rstoenescu** [comment]
Grouping with https://github.com/quasarframework/quasar/issues/4349

**Comment by tylerlumea** [comment]
Is there a modern equivalent to the @edtior-focus that seems like it was added/proposed?  I don't see it anywhere in the docs or [code](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/editor/QEditor.js). 

I'm trying to save on blur of the whole editor component, but with @blur it gets triggered by pressing any of the buttons in the toolbar, saving it without the formatting.
