### ISSUE TITLE
[docs] `q-select` with `v-slot:selected-item`

### ISSUE THREAD

**Issue by iMakedonsky** [quasarframework/quasar#4739]
One thing is not mentioned in `q-select` docs.
And that is, if you use custom `options` with `multiple` and `v-slot:selected-item`, like 
```
[
  ...,
  {
    id: <id>,
    username: <username>
   },
   ...
]
```
In that case, you have to add `option-value="id"` or something similar to your `q-select`, so that internal `:key="opt.value"` binding works correctly.

Otherwise trying to select multiple items causes bugged behavior: selecting any item causes previously selected item to de-select etc.

**Comment by thantoanthang** [comment]
Thank you very much. I've got a mess for all day due to this bug

**Comment by pdanpdan** [comment]
This is already specified in the docs here: https://quasar.dev/vue-components/select#Custom-prop-names.

But if you feel there should be more details added please make a PR for the docs.

Thank you.
