### ISSUE TITLE
[Request] Ability to disable Dialog UI elements

### ISSUE THREAD

**Issue by Sfinx** [quasarframework/quasar#474]
Hello,

It will be good to have ability to enable/disable the Dialog elements (inputs, radios buttons, etc.) using the simple id selector.

```
let dlg = new Dialog(form: { comments_input: {} } … buttons[id:‘agree_button’, disabled: true …])
…
dlg.id('comments_input').disable()
dlg.id(‘agree_button’).enable()
```

**Comment by Sfinx** [comment]
May be it will be good idea to add generic **id** access interface to most Quasar components ? Something like uiComponent.id['some_children'].some_children_method(). So it will be very easy to add the above enable/disable methods or even not to add them if they already exist ;)

**Comment by rstoenescu** [comment]
Hi, Closing this as v0.15 now has an extra component (QDialog) with which you can tweak the content to your specific needs.
