### ISSUE TITLE
QSplitter error on clicking separator button to "close" side

### ISSUE THREAD

**Issue by pw4rn3r** [quasarframework/quasar#4740]
**Describe the bug**
_Occasionally_, when I click on a qsplitter separator button I receive the following console error:

```
Invalid prop: type check failed for prop "value". Expected Number with value NaN, got Undefined 
```

Clicking the button is supposed to change the splitter model to 100 so that it hides the right side.  Instead, when this error occurs nothing happens.  Clicking the separator button again works as usual.

This is a very hard bug to reproduce.  It occurs roughly once in every 15 tries.

This is most similar to issue #3495, but this issue is focused on using the separator button for changing the splitter model.  Also, instead of using a text area inside `qsplitter` my setup has a template that includes a `qcard `with embedded `qscroll-area` with a `q-tree` inside of that.

**Codepen/jsFiddle/Codesandbox (required)**
I am unable to provide my project code.

**To Reproduce**
1. Click on the qsplitter separator button to "close" a right pane (sets splitter model to 100)

**Expected behavior**
Splitter model changed to 100 to "close" right pane

**Screenshots**
N/A

**Platform (please complete the following information):**
Quasar: 1.0.5
OS: Windows
Node: 10.11.0
NPM: 6.4.1
Browsers: Google Chrome 75.0.3770.142

**Comment by pdanpdan** [comment]
Please provide a codepen where we can reproduce the problem. Thank you.
