### ISSUE TITLE
升级后报错无法运行(Error: Unknown import from Quasar: QProgress)

### ISSUE THREAD

**Issue by aiplat** [quasarframework/quasar#4742]
版本从0.16.4升级到1.0.0报错无法运行
很多如QProgress等组件均在quasar.conf.js配置了，但是所有如 import { QProgress } from 'quasar';都提示如Error: Unknown import from Quasar: QProgress

 @ ./src/pages/mine/index.vue?vue&type=script&lang=js& 1:0-178 1:194-197 1:199-374 1:199-374
 @ ./src/pages/mine/index.vue
 @ ./src/router/mine/index.js
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

 error  in ./src/pages/mine/index.vue?vue&type=script&lang=js&

Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Unknown import from Quasar: QProgress

  - imports.js:167 module.exports
    [newQuasar]/[quasar]/dist/babel-transforms/imports.js:167:11

  - index.js:64 transform
    [newQuasar]/[babel-plugin-transform-imports]/index.js:64:16

  - index.js:138
    [newQuasar]/[babel-plugin-transform-imports]/index.js:138:39

  - Array.forEach

  - index.js:121 PluginPass.ImportDeclaration
    [newQuasar]/[babel-plugin-transform-imports]/index.js:121:35

  - visitors.js:193 newFn
    [newQuasar]/[@babel]/traverse/lib/visitors.js:193:21

  - context.js:53 NodePath._call
    [newQuasar]/[@babel]/traverse/lib/path/context.js:53:20

  - context.js:40 NodePath.call
    [newQuasar]/[@babel]/traverse/lib/path/context.js:40:17

  - context.js:88 NodePath.visit
    [newQuasar]/[@babel]/traverse/lib/path/context.js:88:12

  - context.js:118 TraversalContext.visitQueue
    [newQuasar]/[@babel]/traverse/lib/context.js:118:16

  - context.js:85 TraversalContext.visitMultiple
    [newQuasar]/[@babel]/traverse/lib/context.js:85:17

  - context.js:144 TraversalContext.visit
    [newQuasar]/[@babel]/traverse/lib/context.js:144:19

  - index.js:94 Function.traverse.node
    [newQuasar]/[@babel]/traverse/lib/index.js:94:17

  - context.js:95 NodePath.visit
    [newQuasar]/[@babel]/traverse/lib/path/context.js:95:18

  - context.js:118 TraversalContext.visitQueue
    [newQuasar]/[@babel]/traverse/lib/context.js:118:16

  - context.js:90 TraversalContext.visitSingle
    [newQuasar]/[@babel]/traverse/lib/context.js:90:19

package.json为
"dependencies": {
    "@quasar/extras": "^1.0.0",
    "axios": "^0.18.1",
    "cross-env": "^5.2.0",
    "cssnext": "^1.8.4",
    "downloadjs": "^1.4.7",
    "postcss-salad": "^2.0.1",
    "quasar": "^1.0.0",
    "v-distpicker": "^1.0.21",
    "vue": "^2.5.16",
    "vue-i18n": "^8.0.0",
    "vue-ios-pickers": "^1.4.7",
    "vue-video-player": "^5.0.2",
    "vuelidate": "^0.7.4"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0",
    "@vue/eslint-config-airbnb": "^4.0.0",
    "ali-oss": "^6.0.1",
    "awe-dnd": "^0.3.4",
    "babel-eslint": "^10.0.1",
    "eslint": "^4.15.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "md5": "^2.2.1",
    "mescroll.js": "^1.3.8",
    "qrcode": "^1.2.2",
    "socks": "^2.2.2",
    "store": "^2.0.12",
    "v-distpicker": "^1.0.21",
    "vue-awesome-swiper": "^3.1.3",
    "vue-lazyload": "^1.2.6",
    "vue-loader": "^15.7.1",
    "vue-scroller": "^2.2.4",
    "vue-template-compiler": "^2.5.16",
    "vuedraggable": "^2.17.0",
    "vuex": "^3.0.1",
    "weixin-js-sdk": "^1.3.2"
  },

但是旧的package.json运行是正常的：
"dependencies": {
    "axios": "^0.18.0",
    "cross-env": "^5.2.0",
    "cssnext": "^1.8.4",
    "downloadjs": "^1.4.7",
    "postcss-salad": "^2.0.1",
    "v-distpicker": "^1.0.21",
    "vue": "^2.5.16",
    "vue-i18n": "^7.3.3",
    "vue-ios-pickers": "^1.4.7",
    "vue-video-player": "^5.0.2",
    "vuelidate": "^0.7.4"
  },
  "devDependencies": {
    "ali-oss": "^6.0.1",
    "awe-dnd": "^0.3.4",
    "babel-eslint": "^8.2.2",
    "emoji": "^0.3.2",
    "eslint": "^4.15.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "md5": "^2.2.1",
    "mescroll.js": "^1.3.8",
    "qrcode": "^1.2.2",
    "quasar-cli": "^0.16.4",
    "socks": "^2.2.2",
    "store": "^2.0.12",
    "v-distpicker": "^1.0.21",
    "vue-awesome-swiper": "^3.1.3",
    "vue-lazyload": "^1.2.6",
    "vue-scroller": "^2.2.4",
    "vuedraggable": "^2.17.0",
    "vuex": "^3.0.1",
    "weixin-js-sdk": "^1.3.2"
  },

**Comment by aiplat** [comment]
ERROR  Failed to compile with 1 errors                                                                                                                           11:32:06

 error  in ./.quasar/client-entry.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL] D:\mine\h5app\updateDir\newQuasar\.quasar\client-entry.js: The 'polyfill' option has been removed. The @babel/runtime module now skips polyfilling by d
  efault. (While processing: "D:\\mine\\h5app\\updateDir\\newQuasar\\node_modules\\@babel\\plugin-transform-runtime\\lib\\index.js")

  - index.js:165
    [newQuasar]/[@babel]/plugin-transform-runtime/lib/index.js:165:13

  - index.js:19
    [newQuasar]/[@babel]/helper-plugin-utils/lib/index.js:19:12

  - full.js:165
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:165:14

  - caching.js:33 cachedFunction
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/caching.js:33:19

  - full.js:200 loadPluginDescriptor
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:200:28

  - full.js:69
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:69:20

  - Array.reduce

  - full.js:67 recurseDescriptors
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:67:38

  - full.js:108 loadFullConfig
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:108:6

  - transform.js:28
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/transform.js:28:33



 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

**Comment by pdanpdan** [comment]
`QProgres` has been replaced in quasar@1. Please check the upgrade guide here: https://quasar.dev/start/upgrade-guide#QProgress

**Comment by aiplat** [comment]
> 
> 
> `QProgres` has been replaced in quasar@1. Please check the upgrade guide here: https://quasar.dev/start/upgrade-guide#QProgress

now is this: 
ERROR Failed to compile with 1 errors 11:32:06

error in ./.quasar/client-entry.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] D:\mine\h5app\updateDir\newQuasar.quasar\client-entry.js: The 'polyfill' option has been removed. The @babel/runtime module now skips polyfilling by d
efault. (While processing: "D:\mine\h5app\updateDir\newQuasar\node_modules\@babel\plugin-transform-runtime\lib\index.js")

    index.js:165
    [newQuasar]/[@babel]/plugin-transform-runtime/lib/index.js:165:13

    index.js:19
    [newQuasar]/[@babel]/helper-plugin-utils/lib/index.js:19:12

    full.js:165
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:165:14

    caching.js:33 cachedFunction
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/caching.js:33:19

    full.js:200 loadPluginDescriptor
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:200:28

    full.js:69
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:69:20

    Array.reduce

    full.js:67 recurseDescriptors
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:67:38

    full.js:108 loadFullConfig
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/config/full.js:108:6

    transform.js:28
    [newQuasar]/[_@babel_core@7.5.5@@babel]/core/lib/transform.js:28:33

@ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js
