### ISSUE TITLE
Drag-and-drop image from browser to QUploader (or via URL)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4744]
**Is your feature request related to a problem? Please describe.**

Currently it's not possible to drag an image directly from the browser onto QUploader in another browser window.

**Describe the solution you'd like**

I'd like a specific event that can capture such a drag-and-drop. (eg. drag an image from google images into QUploader).

I thínk that it should be possible to "recognise" the **direct url** of an image that's dragged like this.
If an event could broadcast that url, the dev can write their own logic to upload images from this direct URL.

**Describe alternatives you've considered**

I can't think of any.

**Comment by pdanpdan** [comment]
Sorry, you can only select what an `<input type="file" />` accepts.
