### ISSUE TITLE
Q-rating - outlined icons on not selected values

### ISSUE THREAD

**Issue by rafaelkloss** [quasarframework/quasar#4745]
My suggestion is to make possible something like Uber model see the image:
![Screen Shot 2019-07-26 at 4 05 11 PM](https://user-images.githubusercontent.com/6857475/61979055-26750000-afc9-11e9-8558-ccd18f2ac799.png)

**Comment by rstoenescu** [comment]
Will be available in 1.0.6 (`icon` can be an array too; also, new prop `icon-selected`)
