### ISSUE TITLE
Add scoped slot for "No data available" message in q-table

### ISSUE THREAD

**Issue by jorgy343** [quasarframework/quasar#4746]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When a table does not have any data, an optional scoped slot should allow for customized content in place of the default "No data available" message.

**Describe alternatives you've considered**
Only showing the table when there exists data and showing a different component when there is no data. It requires slightly more work and is thus a slight inconvenience.

**Additional context**
This is purely a convenience feature since there is an alternative.

**Comment by rstoenescu** [comment]
New slot for this ("no-data") will be available in v1.1.1
