### ISSUE TITLE
Passive event listeners in touch-hold

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4747]
The touch-hold directives uses non-passive event listeners, and I know it's because there is a `stopAndPrevent(evt)` involved at some point.

But I made the test to turn them passive, and honnestly it seems to work perfectly fine in my use case (I just call a dialog when an item is pressed for a while). What is the reason behind using active listeners? Could we consider leaving them passive when active is not required? Thanks

**Comment by pdanpdan** [comment]
The only listener that would allow using passive listeners would be `touchstart` in `v-touch-hold`.
I don't think it would bring any speed improvement.

All other listeners may arrive in the `stopAndPrevent` branch, so they must not be passive.

**Comment by louisameline** [comment]
I will test tonight to make only this one passive and let you know if it's better. Thank you

**Comment by louisameline** [comment]
A passive touchstart doesn't help indeed.

I cannot consider using the directive with active listeners, scrolling is too laggish. 

Could you please enlighten me on what could go wrong if I make the listeners passive? In my tests I can't find an issue. Thanks

**Comment by pdanpdan** [comment]
I'll do some tests.

**Comment by pdanpdan** [comment]
Please make a short test for me - add "quasar": "pdanpdan/quasar#quasar-v1.0.5-test.10-gitpkg", in your application's package.json under "dependencies".

Do a yarn && quasar dev and tell me if you can still reproduce the problems.

**Comment by louisameline** [comment]
Sorry, been pretty busy on my app. I was going to ask you how to install your code, you anticipated my question, thanks

**Comment by louisameline** [comment]
It works like a charm, congrats and thank you very much.

**Comment by pdanpdan** [comment]
Good to hear. I think it will land in the next official release.

**Comment by louisameline** [comment]
Awesome!

**Comment by pdanpdan** [comment]
This is now implemented starting with v1.1.5
