### ISSUE TITLE
Action sheet icons not well rendered

### ISSUE THREAD

**Issue by ddela-cr** [quasarframework/quasar#475]
### Software version

Quasar: 0.13.4
Browsers: Chrome 56.0.2924.87

Action Sheet component doesn't render some icons correctly

```
ActionSheet.create({
    title: 'Saisie',
    actions: [
    {
        label: 'Supprimer',
        icon: 'delete',
        handler: this.handleSupprimer
    },
    {
        label: 'Modifier',
        icon: 'mode-edit',
        handler: this.handleEdit
    }
    ]
})
```

![capture d ecran 2017-03-21 a 16 36 23](https://cloud.githubusercontent.com/assets/16035265/24155813/20891a54-0e55-11e7-89b3-d4458807867c.png)

I found out that this bug occurs on icons with a composed name. I might be wrong though

**Comment by rstoenescu** [comment]
Hi, use "underscore" character as stated in the Material Icons documentation website. Examples: `mode_edit`, `card_travel`.

**Comment by ddela-cr** [comment]
Thanks, worked fine
