### ISSUE TITLE
Make a loader to register Quasar components automatically

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4750]
It's hard to register all Quasar components used in a project manaully. It will be better to develop a loader to load them automatically like Vuetify 2.0 does.
Thanks.

**Comment by lucasfernog** [comment]
Hi,

We are working on it, please take a look here: https://github.com/webnoob/app-extension-qautomate

**Comment by hawkeye64** [comment]
💓 QAutomate app extension!

**Comment by rstoenescu** [comment]
Hi @bigradish 

This will be available through `@quasar/app` v1.1. More info here: https://github.com/quasarframework/quasar/issues/5080
