### ISSUE TITLE
Auto expand for lazy QTree node

### ISSUE THREAD

**Issue by linhtranvu** [quasarframework/quasar#4751]
**Is your feature request related to a problem? Please describe.**
When using lazy node,   :expanded="['Node 1',  'Node 2']" does not work

**Describe the solution you'd like**
Based on order of node, tree will lazy load node, wait node finish and continue to expand

**Describe alternatives you've considered**

I make my own coding here, so hope it could be embed to QTree

https://forum.quasar-framework.org/topic/4033/not-solved-by-quasar-but-manual-coding-auto-expand-for-lazy-qtree-node/2

**Comment by MacMaru** [comment]
Hi @linhtranvu ,

Had a similar requirement with a dynamic tree with >100k items.
What worked for me was to differentiate between children or lazy in the lazyLoad handler.

Assuming you have `:expanded.sync="expanded"` and `node-key="key"` on your tree component:

```
methods: {
  lazyLoadChildren({ node, done }) {
    done(this.getChildren(node.key));
  },

  getChildren(key) {
    let children = []; // Do your Axios call here
    children.forEach(child => {
      if (this.expanded.includes(key)) {
        child.children = this.getChildren(child.key); // Prefetch your expanded child's children here 
      } else {
        child.lazy = true;
      }
    });
  },
}
```

The inner workings of the component will correctly expand the tree for you.

**Comment by pdanpdan** [comment]
Closing this to track it in https://github.com/quasarframework/quasar/issues/6959
