### ISSUE TITLE
QTable: Using q-th or columns[..] for define table header, not both

### ISSUE THREAD

**Issue by linhtranvu** [quasarframework/quasar#4752]
**Is your feature request related to a problem? Please describe.**

I want to build a table with tag instead of JSON define (I dont like define JSON for rendering html). So I am trying to use `q-th`. However, I find that I cannot remove `columns: [..]`. I must define columns for q-th to work.

**Describe the solution you'd like**

When using q-th, it mean we do not use columns anymore, every definition from columns go into q-th

**Comment by rstoenescu** [comment]
Hi,

Those columns are required because there's "stuff" happening under the covers. If there would be no columns definition it would be impossible to supply some of QTable's features. Sorry for any inconvenience.
