### ISSUE TITLE
HTML tag in columns[..] of QTable not working

### ISSUE THREAD

**Issue by linhtranvu** [quasarframework/quasar#4753]
**Describe the bug**

I am playing with QTable and columns[…] and want to format field with html tag. However I fail here

  columns: [
    { name: 'name',  label: 'Name', align: 'center', sortable: true,
    field: row => (`${row.name} <b>abcd </b>`),  
    format: val => `<b> ${val} </b>`
    },
]

I try to embed html code in field and format attribute. However in browser html code is not run, still print out <b> tag as text 

**Expected behavior**

Embed html code in field, format attrinute inside QTable column should be printed out

**Comment by pdanpdan** [comment]
If you want custom html you can use `QTr`, `QTh` and `QTd`: https://quasar.dev/vue-components/table#QTd-API

**Comment by garbinmarcelo** [comment]
I ended up coming across this. So it's not possible to use HTML in the format, is that it? What would be the function of this format and field in the case?

For example, I have a table with several columns, but I would like to edit only 1 with HTML, how could I do this without having to repeat the code inside the slot of the other columns that will not be changed? Was that possible? (For example a column with action buttons)

sorry for any questions, i am new to quasar.

**Comment by rstoenescu** [comment]
@garbinmarcelo https://quasar.dev/vue-components/table#Example--Body-cell-%5Bname%5D-slot
