### ISSUE TITLE
Uploader not working on iOS Safari

### ISSUE THREAD

**Issue by oswaldomilet** [quasarframework/quasar#476]
### Software version

Quasar: 0.13.7
OS: iOS
Browsers: Safari
iOS: 10.2.1

### What did you get as the error?

When I click "+ PICK FILE" button in q-uploader component nothing happens (just in iOS Safari).

### What were you expecting?

I except same behavior of macOS Safari

**Comment by oswaldomilet** [comment]
I have a half solution for this. Following code works cross-browser, except the `change` event is not being triggered in iOS:

**Comment by oswaldomilet** [comment]
I did a workahound here, the only solution I found to work cross-browsers:

**Comment by rstoenescu** [comment]
Fixed. Available in future v0.14.
Also added an "abort()" method.

**Comment by ceau** [comment]
very nice, thx

**Comment by edudesouza** [comment]
@oswaldofreitas Hi Oswaldo, I am experiencing the same issue. Could share your code?

**Comment by oswaldofreitas** [comment]
@edudesouza very sorry, it's a very old issue and I'm not using Quasar anymore. I think it was already fixed, did you try to update Quasar version?

**Comment by edudesouza** [comment]
Hi @oswaldofreitas thanks for the quick reply! I will update, but not now ... there is so many layout changes in the new framework version.
