### ISSUE TITLE
QDate marks dates of adjacent months as non-selectable

### ISSUE THREAD

**Issue by tiltec** [quasarframework/quasar#4760]
**Describe the bug**

QDate marks dates of adjacent months as non-selectable. This is especially confusing when other dates are _really_ non-selectable, by being disabled with the `options` prop.

Example: all upcoming dates are selectable, but it shows 1st, 2nd and 3rd of August as non-selectable (until you switch to August, obviously...):

![image](https://user-images.githubusercontent.com/4410802/62068396-36dde280-b236-11e9-92f7-2686e97ac3c9.png)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tiltec/pen/jgyjob

**Expected behavior**
Mark selectable options of adjacent months as selectable, and select them when clicking on them.

Alternatively, you could revert to v0.17 behavior of not showing days of adjacent months. This fits with this Material Design screenshot: https://material.io/design/components/pickers.html

(I left out the other bug report form sections on purpose because I don't think they describe the problem any further. I hope that judgement was correct!)

**Comment by pdanpdan** [comment]
Yes, I think not showing them should be the right approach.

**Comment by rstoenescu** [comment]
Will be available in 1.0.6.
