### ISSUE TITLE
Add other login ways for Quasar forum

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4761]
For some reason, I can't get the Captcha when registering Quasar forum (https://forum.quasar-framework.org/), and so can't register on it.
Could you add other login ways to the forum, e.g., using Github account?
Thanks.

**Comment by nothingismagick** [comment]
@bigradish - Please join the discord community at https://chat.quasar.dev

Please use the issue tracker just for Issues and Feature Requests for the code libraries.

Nevertheless, I was worried the Captcha was broken, so I tried it and fulfilled the challenge of the Captcha, so I am closing this issue.
![Screen Shot 2019-08-07 at 22 41 47](https://user-images.githubusercontent.com/35242872/62656508-9c338100-b964-11e9-9e82-bf6c38a0135f.png)
