### ISSUE TITLE
Add Nucleo Icons support (free and licensed versions) for icon component

### ISSUE THREAD

**Issue by mykee3991** [quasarframework/quasar#4762]
**Is your feature request related to a problem? Please describe.**
Unfortunately I don't see nucleo icons library supported in the icon component. Most of my projects use this icon library due to its very high amount of neat looking icons and its actually look great on material design too.

**Describe the solution you'd like**
Adding the nucleo icons library free and licensed versions in the icon component. Having this icon library would be a great addition to the icon component.

**Describe alternatives you've considered**
I don't have alternatives in mind, the proper way to implement these icons in quasar is through icon component

**Additional context**
Link of free version [Nucleo Icons (free)](https://nucleoapp.com/free-icons)

Screenshot of having a licensed version
![image](https://user-images.githubusercontent.com/47663260/62095075-d8eee080-b2b1-11e9-9d8d-e98d17af17cb.png)

**Comment by rstoenescu** [comment]
Hi,

You can already do this: https://quasar.dev/vue-components/icon#Custom-mapping

We'd love to add as many icon libraries "out of the box" but there's also a maintenance cost involved that is simply not feasible at this point. Sorry for not hearing what you want in regards to this, but there's the custom mapping available and it shouldn't be hard.
