### ISSUE TITLE
[docs] themebuilder uses some quasar utils to automatically change the text colors according to the color's luminosity, but it never mentioned

### ISSUE THREAD

**Issue by Forux** [quasarframework/quasar#4766]
The themebuilder uses some quasar utils to automatically change the text colors according to the color's luminosity, but it never mentioned!

So it looks like it is part of the framework, and colors must be changed like in a builder automatically, but it does not!

Please mention in builder how it works so people will not face it as a bug.

**Comment by rstoenescu** [comment]
Hi,

It is mentioned in the docs: https://quasar.dev/quasar-utils/color-utils#Color-Processing

And of course, the code for the docs is opensource too (docs are a Quasar app so it should be familiar), and can be found in this repo under /docs folder. For this particular effect that I wrote on the builder page, you can check out: https://github.com/quasarframework/quasar/blob/dev/docs/src/components/page-parts/theming/ThemeBuilder.vue#L237
