### ISSUE TITLE
Vuex outside undefined

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#4768]
**Describe the bug**
I cannot use store outside Vue components.
> Uncaught (in promise) TypeError: Cannot read property 'commit' of undefined
> 	at validateErrors (axios.js:30)
> 	at eval (axios.js:67)

**Code**
Here is `boot/axios.js`
```
require('dotenv').config();

import Vue from 'vue';
import { Notify } from 'quasar';
import axios from 'axios';

axios.defaults.baseURL = process.env.MIX_API_URL;

function processResponse(response) {
	//console.log('interceptors.response', response);
}

function validateErrors(response) {
	if(! response) {
		Notify.create('Error response undefined');
		Vue.prototype.$store.commit('server/updateServerState', 'no-reponse');
		console.log('Error response undefined');
		return;
	}
	//
}

axios.interceptors.response.use(function (response) {
	processResponse(response);
	return response;
}, function(error) {
	validateErrors(error.response);
	console.error(error);
	return Promise.reject(error);
});

export default ({ Vue }) => {
	Vue.prototype.$axios = axios
}
```

`store/index.js`
```
...
import server from './server'
...
const store = new Vuex.Store({
	modules: {
		server
	},
	strict: process.env.DEV
});
```

`store/server/mutations.js`
```
export const updateServerState = (state, status) => {
	state.serverState = status
}
```

`store/server/state.js`
```
export default {
	serverState: 'on'
}
```

**Expected behavior**
I want to show "fallback" page when API is not available.

**Screenshots**
http://prntscr.com/ombzgu

**Platform (please complete the following information):**
OS: Win10
Node: 12.7.0
NPM: 6.10.2

**Comment by metalsadman** [comment]
See this example how you can get context of your store in a boot file. https://quasar.dev/quasar-cli/cli-documentation/boot-files#Anatomy-of-a-boot-file

**Comment by matro-skin** [comment]
@metalsadman I saw that article, but sorry it doesn't help me...
Please give me advice what I should do

**Comment by matro-skin** [comment]
Have done, thanks)
I added
`import store from "../store";`
and changed to
`store.commit('server/updateServerState', 'no-response')`
and added store to export
`export default ({ Vue, store }) => {`
am I right?
looks like it works now
