### ISSUE TITLE
QSelect: options dropdown positioned incorrectly when adding separator to the custom option

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4769]
Hello!

When you lazy load custom options and add a q-separator inside, options dropdown positioned incorrectly:

https://codepen.io/anon/pen/oKWMqZ?&editable=true&editors=101

1) Press inside select
2) Wait for the options to load
3) Dropdown position incorrectly
4) Click one more time, dropdown position is ok now

![Screen Shot 2019-07-31 at 13 31 28](https://user-images.githubusercontent.com/3635352/62208605-aa4b3580-b397-11e9-92b7-30ebf80067c4.png)

Thanks!

**Comment by pdanpdan** [comment]
Please make a short test for me - add "quasar": "pdanpdan/quasar#quasar-v1.0.5-test.9-gitpkg", in your application's package.json under "dependencies".

Do a yarn && quasar dev and tell me if you can still reproduce the problems.

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6.
