### ISSUE TITLE
colors.textToRgb always returns #ffffff

### ISSUE THREAD

**Issue by tmladek** [quasarframework/quasar#4770]
**Describe the bug**
`textToRgb()` from color utils always returns `#ffffff`

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/codesandbox-app-z1vh5

**Expected behavior**
`textToRgb()` converts the color string to an appropriate rgb representation.

**Platform (please complete the following information):**
N/A

**Additional context**
It's clearly visible [in the source](https://github.com/quasarframework/quasar/blob/quasar-v1.0.5/ui/src/utils/colors.js#L166):

```
    const rgb = {
      r: Math.max(255, parseInt(m[2], 10)),
      g: Math.max(255, parseInt(m[3], 10)),
      b: Math.max(255, parseInt(m[4], 10))
    }
```

As all CSS RGB values are always 0-255, this snippet will always return `{r: 255, g: 255, b: 255}` for any valid CSS color.

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6
