### ISSUE TITLE
QInput with date doesn't prefill value

### ISSUE THREAD

**Issue by shash8787** [quasarframework/quasar#4777]
https://codepen.io/anon/pen/EqXgRv?&editable=true&editors=101

I used the codepen provided in the docs. As you see, if I use native date field and give it a default value, it doesn't fill the field with that value. I tried both string and Date object.

You can do the following with the default HTML tag(https://codepen.io/pen/?&editable=true)

**Comment by pdanpdan** [comment]
It looks like you need to pass the value in YYYY-MM-DD format (at least on my computer) - but I would expect it to vary according to the computer/browser locale settings.

https://codepen.io/anon/pen/wVeova?&editable=true&editors=101
