### ISSUE TITLE
q-toggle q-checkbox q-btn & q-item need a prop to prevent 'keyup.enter' event

### ISSUE THREAD

**Issue by bichikim** [quasarframework/quasar#4778]
**Is your feature request related to a problem? Please describe.**
There is not a way to stop toggling the @input event by a 'keyup.enter' event.

**Describe the solution you'd like**
```vue
<q-toggle prevent-enter v-model="toggle"></v-toggle>
```

**Describe alternatives you've considered**
```vue
<q-toggle prevent-event="keyup.enter" v-model="toggle"></v-toggle>
```

**Additional context**

**Comment by pdanpdan** [comment]
What is the use case for this? What is the problem?

**Comment by bichikim** [comment]
the use case is 
![image](https://user-images.githubusercontent.com/13829322/62345088-bf58cd80-b52b-11e9-85a4-41b412add0d6.png)

1. click "A" to switch
2. press enter  to save & close B but A is switched again owing to focusing A

**Comment by mesqueeb** [comment]
This problem might be similar to my problem.
I also need to prevent `keyup.enter` !!!

#4795

**Comment by pdanpdan** [comment]
For QToggle/QCheckbox in QPopupEdit just wrap the element in a div like this:
```html
<q-popup-edit v-model="model">
  <div @keydown.enter.capture.stop>
    <q-toggle v-model="model" autofocus />
  </div>
</q-popup-edit>
```

For QBtn and QItem ENTER prevention would be funny :) - one can navigate without pointing devices and I don't see the use.

**Comment by bichikim** [comment]
@mesqueeb You can create own your QToggle and others to prevent it by the Vue Extends 
@pdanpdan Your solution does not look good

**Comment by cvillagrasa** [comment]
> For QToggle/QCheckbox in QPopupEdit just wrap the element in a div like this:
> 
> ```
> <q-popup-edit v-model="model">
>   <div @keydown.enter.capture.stop>
>     <q-toggle v-model="model" autofocus />
>   </div>
> </q-popup-edit>
> ```
> 
> For QBtn and QItem ENTER prevention would be funny :) - one can navigate without pointing devices and I don't see the use.

When not inside a QPopupEdit, I've found the wrapping trick not to work. Solved it by running this @ click:

```javascript
if (document.activeElement instanceof HTMLElement)
    document.activeElement.blur()
``` 

Referring to the QToggle template ref (say `toggle`) as `toggle.value.$el.blur()` doesn't work. It seems to be a different HTMLElement than the focused one.
