### ISSUE TITLE
I am using the uploader component, how can I upload file direct when the file been added, with out click any button?

### ISSUE THREAD

**Issue by qwIvan** [quasarframework/quasar#478]
```
  methods: {
    add: function (file) {
      this.$refs.uploader.files.push(file)
      this.$refs.uploader.upload()
    }
  }
```
```
<q-uploader ref="uploader" @add="add" />
```
My backend server can not get the correct file.

**Comment by qwIvan** [comment]
Okay, I was resolved it just now.
```
  methods: {
    add: function (files) {
      let uploader = this.$refs.uploader
      uploader.files = uploader.files.concat(files)
      uploader.upload()
    }
  }

```

**Comment by rofiuddin15** [comment]
can you give me full script of your code?

**Comment by Akashaj09** [comment]
Here is the code for uploading multiple files. I don't know if the syntax is correct oris there any better way but it works for me

`uploadFile: function (file, updateProgress) { 
	this.loading = true
	let files = this.$refs.files.files.concat(file);
	let formData = new FormData(); 
	for( var i = 0; i < files.length-1; i++ ){
		let file = files[i];
			formData.append('files[' + i + ']', file);
		} 
		formData.append('caption', this.caption) 
		this.$axios.post(postUrl, formData, {headers: fHeader(), processData: false,  contentType: false,})
					.then((response) => {
		        this.loading = false
			if(response.data.error){
				this.$q.notify({
					message: response.data.message,
					type: 'negative',
					color: 'negative',
					icon: 'fas fa-exclamation-triangle'
				})
			}
		}, (response) => {
			this.loading = false
		})
	}`

**Comment by Afrojakabir** [comment]
![download](https://user-images.githubusercontent.com/47172384/62761330-32bc8b00-baa8-11e9-9201-c3c6aa2a3ba9.jpg)

**Comment by haizad** [comment]
Does 'hide-upload-button' on your code really hide the q-uploader upload button?

**Comment by R1dyk** [comment]
> Does 'hide-upload-button' on your code really hide the q-uploader upload button?

It does for me 👍

**Comment by ks-hassam** [comment]
How to hide quasar uploader icon?
Use `hide-upload-btn` in q-uploader.

```
<q-uploader
  url=""
  multiple
  no-thumbnails
  @added="fileSelected"
  style="width: 100%"
  hide-upload-btn
/>
```

**Comment by ruanpin** [comment]
> How to hide quasar uploader icon? Use `hide-upload-btn` in q-uploader.
> 
> ```
> <q-uploader
>   url=""
>   multiple
>   no-thumbnails
>   @added="fileSelected"
>   style="width: 100%"
>   hide-upload-btn
> />
> ```

using `hideUploadBtn` instead of `hide-upload-btn` props
