### ISSUE TITLE
Handling android back button?

### ISSUE THREAD

**Issue by UmarBilanov** [quasarframework/quasar#4781]
I try to navigate from Example.vue to Example2.vue by android back button my code works for os under android 8.0. On devices android upper 8.0 the back button works by history.Do you have any idea to do it?

onClickBackButton() {
      this.$router.replace({'path': '/example2'});
      }

mounted() {
      if (this.$q.platform.is.cordova) {
        document.addEventListener("backbutton", this.onClickBackButton, false)
      }
}

**Platform:**
Android:

**Comment by metalsadman** [comment]
You should do it with your vue router's beforeRouteLeave, as you can only override backbutton when your app has no more history records in it thus overriding the behavior that your app would close. https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard
