### ISSUE TITLE
QMenu / QPopupProxy / QDialog should support VueJS provide/inject dependency injection

### ISSUE THREAD

**Issue by florianlink** [quasarframework/quasar#4784]
I am using VueJS provide/inject dependency injection in my Quasar-based framework to provide some context information to (deeply nested) child components. It works well with the normal Quasar components, but I found that the injection does NOT propagate into components inside of a QMenu/QPopupProxy/QDialog.

The following codepen shows the problem:

https://codepen.io/anon/pen/eqRarM

It would be great if QMenu etc. could somehow support the forwarding of the injected data into the components that are shown in the Portal.

**Comment by hawkeye64** [comment]
@florianlink I have spent a significant amount of time on this and now have a solution.
Basically, when a portal is created, this is a new Vue $root. It has no context of the previous Vue $root which all your normal components are drawn within.
The fix, would be to put the `<component-provide>` tag inside the QMenu slot, so the context of that provider is within the new Vue $root.
I have updated your codepen to show you: https://codepen.io/Hawkeye64/pen/mNqJNZ?editors=1010

**Comment by hawkeye64** [comment]
This needs to be updated in docs.

**Comment by hawkeye64** [comment]
I have updated an example for AE QWindow to show the issue and remediation: https://hawkeye64.github.io/app-extension-qwindow/examples#Provide%2FInject

**Comment by hawkeye64** [comment]
Also of note, this from the Vue docs:
```
This pair of options are used together to allow an ancestor component to serve as a dependency injector for all its descendants, regardless of how deep the component hierarchy is, as long as they are in the same parent chain. If you are familiar with React, this is very similar to React’s context feature.
```
The key take-away from this is: `as long as they are in the same parent chain`

**Comment by florianlink** [comment]
Yes, I understand the problem and your workaround proposal.
But in my case, I have a complex deep template tree and a context object is injected on the root component of my template (and the same components are used with different context objects on the root). Since the templates are deeply nested, I use dependency injection, so that I don't have to pass the context object down on each child manually. Your workround would force me to add an extra dependency provider into each QMenu that is used somewhere and the user has to know what the context is at that point in the template tree, which is contradictory to the idea of dependency injection being injected on the root of the whole tree.

Since QMenu is a "normal" child in the Vue template tree, I think it is many a technical implementation detail of the Portal code (which uses its own root to render the content of QMenu). To the user of QMenu it looks like it is part of the right tree and should have access to the dependency injection.

So my proposal is to fix this by "forwarding" the dependency injections from the tree where QMenu is located to the Portal root component, which is created in portal.js Mixin and already forwards all directives and components of the other tree:
```

beforeMount () {
    const obj = {
      inheritAttrs: false,

      render: h => this.__render(h),

      components: this.$options.components,
      directives: this.$options.directives
      // TODO: add some code here that copies or forwards the dependency injections of this
      // to the new root object
    }

```
I don't know Vue deep enough how to copy or forward dependency injections, maybe someone with deep Vue knowledge can have a look? I will also investigate and post any results.

**Comment by hawkeye64** [comment]
I was looking for something to forwad, but never did find anything that stood out.

**Comment by florianlink** [comment]
Yeah, I had a look at the injection code of Vue and it just follows the $parent chain...
If Vue would support something like a $provideParent which is also followed, it would be easy and we would just have to add such a parent to the root object of the portal, forwarding to the QMenu parent.

But since Vue does not support this, the only way would be to collect all "provide" dictionaries on the parent chain of QMenu up to the root in a new object and add it as "provide" object to the beforeMount() root object. That should be doable.

**Comment by rstoenescu** [comment]
Fix will be available in 1.1.0.
Major refactor of portal including significant performance improvements.

**Comment by florianlink** [comment]
Thanks for the fix! I did not expect the fix to be that simple, great!

**Comment by wooliet** [comment]
Running into "injection not found" problems when using code that generates the `QGlobalDialog` instance, and this 4+ year old issue seemed the most relevant.

Is provide/inject expected to work in Quasar 2.x with Vue 3 and composition?

**Comment by wooliet** [comment]
I went ahead and opened a new issue:

https://github.com/quasarframework/quasar/issues/16806
