### ISSUE TITLE
[docs] QTooltip trigger on mobile

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4785]
For QTooltip, the doc says
> When hovering the mouse over the target element (or **quickly tapping on mobile platforms**), the tooltip will appear.

But actually on mobile it's more after a brief touch-hold, maybe the sentence needs to be edited, what do you think?

But I don't know if there is a bug behind this. I would actuelly prefer if the tooltip showed up after a tap, and not a touch-hold. Not sure if it was the intended behavior.

**Comment by metalsadman** [comment]
Touch hold is native behavior in mobile for showing a tooltip. Prolly a typo.

**Comment by rstoenescu** [comment]
The brief touch-hold is indeed what was designed. So yes, we need to edit that in docs. Anyone interested in PRing the docs, pls?

**Comment by smolinari** [comment]
Docs updated in #5011. 

Scott

**Comment by stefan-hoelzl** [comment]
The [current documentation](https://quasar.dev/vue-components/tooltip#qtooltip-api) still shows the wrong wording `or quickly tapping on mobile platforms`

**Comment by rstoenescu** [comment]
@stefan-hoelzl thanks for reporting. fixed that as well.
