### ISSUE TITLE
Form validates inputs in a wrong order when there are custom components

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#4787]
**Describe the bug**
Form validates inputs in a wrong order when there are custom components

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/eduardodgarciac/pen/pMwXbK

**To Reproduce**
1. Submit the form

**Expected behavior**
The first input should be validated first

**Platform (please complete the following information):**
OS: Linux
Node: 12.5.0
NPM: 6.9.2
Yarn: 1.16.0
Browsers: Chrome Versión 75.0.3770.142 (64 bits)
iOS:
Android:
Electron:

**Additional context**
I think the problem can be resolve here "quasar/src/utils/vm.js:30" in the getAllChildren function.
The validate method get all childrens components recursevely. So, the idea is to put childrens of childrens in the array next right to his parent. Replacing that line with this: `children = children.splice(index + 1, 0, ...getAllChildren(child))` could work but I dont know how to test it.

**Comment by rstoenescu** [comment]
Thank you for reporting.
Fix will be available in 1.0.6.
