### ISSUE TITLE
[Request] v-model support for toggleable components

### ISSUE THREAD

**Issue by genyded** [quasarframework/quasar#479]
It seems that for components such a Modal. it might be better to have an isOpen boolean property toggle the display. The current open and close methods cannot be derived from a single Vuex boolean state property (such as showLogin). Using the current toggle method would require knowing if the modal was currently open or not and that is messy/tricky.

This can be worked around but not without extra code making it more complex to use and increase the size of the app. I use modal as an example here, but any component that can be toggled applies here.

See [forum post here](http://forum.quasar-framework.org/topic/311/some-components-not-really-vuex-friendly)

**Comment by rstoenescu** [comment]
Will do.

**Comment by laurentpayot** [comment]
In v0.14 beta, q-layout v-model is working for medium/big screens, but not for small screens. Everything is fine when using "traditional" `$refs.layout.toggleLeft()` for instance.

**Comment by laurentpayot** [comment]
@rstoenescu should I open a v0.14-specific issue for this ?

**Comment by murbanowicz** [comment]
@laurentpayot what you mean?

**Comment by laurentpayot** [comment]
@murbanowicz  v-model support for toggleable components is planned for v0.15. Razvan added v-model support for q-layout in 0.14 (that's cool!) but there is a bug for small screens. Should I open an issue with the [v0.14] tag?

**Comment by smolinari** [comment]
@laurentpayot - yes. Start a new issue, if you think you've found a different problem.

Scott

**Comment by rstoenescu** [comment]
This is NOT a issue. `v-model` is supposed to work to be able to set the visibility state on large windows only. It is working as expected.

**Comment by laurentpayot** [comment]
Why on large windows only? I'm trying to use `v-model` with vuex so that the UI is a direct function of the state, whatever the device is. What makes small and medium screens an exception?

**Comment by rstoenescu** [comment]
@laurentpayot 

There are two separate states for the siderbar panels:
* One, which keeps the window width breakpoint into account and shows/hides the panels when threshold is below/above. This behavior is automatic, until:
* The second state is when the user specifically says: look, I want this panel out of the way, even if above threshold. This overrides the threshold and makes it always "hidden" or "visible", based on this state -- and we're using `v-model` for this state.

Please tell me if you need further information or I haven't explained clear enough.

**Comment by laurentpayot** [comment]
@rstoenescu 

Thanks for your answer, it is more clear now. So if I understand you correctly the layout `v-model` is only here to handle the mere preference of the drawer being visible or not by default on large screens. Right?

I would like to open/close the drawer using a vuex state  property to avoid passing props and to avoid using the global event bus. For a screen that could be _of any size_ do you mean I have to use
```html
<q-layout ref="layout" view="hHr LpR lFf" :left-breakpoint="myVuexStateLeftBreakpoint">
```
and to have a mutation to set `myVuexStateLeftBreakpoint` to `0` when I want to display the drawer, and another mutation to set it to `Number.MAX_VALUE` (to include insanely wide screens 😉 ) to hide it?

If so, wouldn't it be far more simple to use the `v-model` property to show/hide panels on all screens? Or another property if you want.

**Comment by laurentpayot** [comment]
#729 was opened for the same reason I wanted to open an issue. It looks like an obvious feature...

**Comment by rstoenescu** [comment]
It may look obvious, but it's not. Will comment more when I get back from my vacation.

**Comment by laurentpayot** [comment]
Passing the drawer toggle function in props is not that bad. `v-model` it more needed for modals (I'm using `$store.watch` on created hook of my components as a workaround).

The more I'm applying v0.14 features the more I think it's a fantastic release. Enjoy your vacations Razvan, you deserved them!

**Comment by rstoenescu** [comment]
Already in latest v0.14. Just forgot to close this.
