### ISSUE TITLE
feat(docs): idea for API card

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#4793]
A personal taste, but I believe the amount of props belonging to each category looks way better _behind_ the category 😄  :

## Current implementation:
<img width="359" alt="current" src="https://user-images.githubusercontent.com/3253920/62339956-cde9b980-b518-11e9-9a5f-42b1932bb0d2.png">

## Proposed implementation:
<img width="359" alt="proposed" src="https://user-images.githubusercontent.com/3253920/62339963-d5a95e00-b518-11e9-97ec-19572afaf3b8.png">

**Comment by hawkeye64** [comment]
This looks cleaner and actually easier to read (for LTR users).
@lucasfernog What do you think?

**Comment by lucasfernog** [comment]
Nice point about LTR/RTL, maybe it should respect it. For LTR its better to have the label on left because that's the primary info there.

**Comment by mesqueeb** [comment]
Let's make it happen guys!!!! Thanks for the positive feedback!!!

**Comment by rstoenescu** [comment]
Anyone willing to take care of this? Shouldn't be hard, but please make sure IE11 is also tested.

**Comment by lucasfernog** [comment]
I have a couple of other things in mind for the weekend, but if no one is willing to do this then I'll do it

**Comment by rstoenescu** [comment]
Implemented. Will be available in next docs deployment.
