### ISSUE TITLE
[docs] Teach use of Quasar with Laravel

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#4794]
Lov'n Quasar but I'm disappointed to see that other Vue frameworks still getting greater mind/market share.  So this "feature request" is really an idea to improve your market share.  I'm sure you're thinking this stuff every day - yeah?

In recent "Vue" job searches I've found that by far most Vue IT shops were using Laravel.  React seems to be more popular with the .NET and Java camps.  SO ... I think Quasar needs to get more traction with the Laravel community who already have Vue baked into their mindset and SDK.

## Ideas: 
- You could do a starter kit but they tend to get dated rather fast.  Maybe creating a PHP compose plugin for Laravel would be smarter - very familiar and really what's expected for this community. No time? Outsource or call for volunteers if you have to.

- You could ask to be invited to do a (short) Laracast series on using Quasar with Laravel. There are existing Laracasts on doing basic Vue components so no need to start there. They'd love to get taught by the Quasar author!  Great chance to show off all your .. hmm features 💪.

**Comment by tohagan** [comment]
Another idea ...

Add each of your component pages into https://vuejsexamples.com  so Vue devs will find you!

**Comment by nothingismagick** [comment]
Why don’t you come and visit us on the discord server and share some of these ideas there. I’d love to sit down with you and talk shop.

**Comment by ibrainventures** [comment]
@tohagan .... you read my minds ... i always thought in the last 16+ Month .. why is there no git repro with a rtr complete boilterplate / stack : laravel, quasar, user-auth and may some ssr / seo / payment connector extras ..  

there are some nice quasar-app-extensions (coming) out there with e.g. helping to solve the jwt workarounds and many more ..  and ..

let lara 6.0.1 come and maybe we (!) together find a way to make this happen ?!

**Comment by tohagan** [comment]
Yep!  Needs a starter kit for Firebase too!  I'm not a Laravel expert but was loaned out to Laravel project for a few months ago but working on a Firebase/Quasar app today.

Another observation ... Lots of legacy .NET/C# apps were built using jQuery/Knockout (we have one in my day job). Knockout used be to standard starter project in Visual Studio. Why do we care? Because a killer feature of Vue is computed properties and guess where that idea came from? Knockout!  So porting all these old Kockout apps into Vue makes much more sense than porting them into React.  Most .NET devs don't know much about Vue.  Needs an article or two on Medium to show then the way to Vue and then Quasar and demo how you'd take a legacy Knockout project and refactor the old logic into Vue components.

**Comment by tohagan** [comment]
OK ... just found all the starter kits ... 
https://forum.quasar-framework.org/topic/4031/list-of-starter-kits-per-programming-language-and-the-backend-framework

**Comment by tohagan** [comment]
Ok I'm also a ASP.NET / C# Visual Studio coder by day - my "bread and butter" stuff.  Visual Studio 2019 ships with "New Project" templates built in for Angular and React but none for Vue! What?? 
No wonder Vue is loosing market share.  So build 'em a Vue/Quasar one :) . 

Get started here ... 
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates?view=vs-2019

**Comment by rfox12** [comment]
I think Microsoft included those templates for the sake of completeness.  I think you can probably count the number of Angular and React coders who use Visual Studio on one hand.  Visual Studio *Code* on the other hand, has had amazing traction and usage.  Regarding this quote... "No wonder Vue is loosing market share" do you have numbers to back that up?

**Comment by TobyMosque** [comment]
Personally, beside NodeJS, I don't think that a deep integration with any back-end language/framework would be a good ideia. I'm opening a exception here to NodeJS, because of how SSR works.

So any doc with titles like `Quasar for %backend_framework% developers` or `How to integrate %backend_framework% to Quasar` will look very similar.

I don't think you need anything beside that to get started:
1. a REST API developed with your preferred framework, here some possibilities.:
Lavavel with [Swagger PHP](https://github.com/zircote/swagger-php)
Spring with [Springfox](https://github.com/springfox/springfox)
ASP.NET Core with [Swashbuckle](https://swagger.io/tools/open-source/open-source-integrations/)
ExpressJS with [Swagger Express Middleware](https://github.com/krakenjs/swaggerize-express)

2. How to call a REST API from your front-end

**Comment by tohagan** [comment]
I agree that PHP would be the priority.  

My suggestion for Visual Studio is not about integration with back ends. Within the C# community, large numbers of commercial projects are switching to React or Angular. My evidence for this is in the job market for C# developers. Just do a job search for C# and React, now try C# and Vue. 

Many C# coders follow Microsoft like sheep. They'd love to ditch their old ASP.NET UIs for a shiny new one.  They start out by finding what "New Project" options are in VS with the expectation that these are the stacks that will be "supported".  Adding a Quasar one should not be too hard.  Just fork the Vue one from Microsoft and integrate Quasar CLI.  Like most devs, I'm a big fan of VS Code for new projects but forced to stick with VS for many legacy apps.

**Comment by tohagan** [comment]
@TobyMosque and I'd add GraphQL to the list ...

Client:
* [https://github.com/vuejs/vue-apollo](Apollo's Vue GraphQL Client)

Servers: 
* . NodeJS [Apollo](https://www.apollographql.com/)
* .NET with [HotChocolate](http://hotchocolate.io) - I'm doing one of these today!
* Postgres with [Graphile](https://www.graphile.org/postgraphile/)

Etc:
* [Awesome GraphQL](https://github.com/chentsulin/awesome-graphql)

**Comment by j209** [comment]
Hi
[Masonite](https://github.com/MasoniteFramework/masonite) is a new python web framework that has a [built in](https://docs.masoniteproject.com/whats-new/masonite-2.3#added-preset-command) integration [with vue](https://github.com/MasoniteFramework/masonite/issues/183).
I think deep integration between masonite and quasar can be a good idea

**Comment by smolinari** [comment]
@j209 - Don't spam issues please.

Scott

**Comment by pdanpdan** [comment]
This is not something we should do - it's up to the community to make docs/articles about how they can use their language/framework of choice.
