### ISSUE TITLE
QSelect RangeError on mobile

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4799]
`RangeError: Maximum call stack size exceeded`

Happens in the docs of QSelect https://quasar.dev/vue-components/select in mobile mode when giving the focus to the field of "New value mode":

![image](https://user-images.githubusercontent.com/371814/62398730-cd353f80-b579-11e9-9d0e-157e6abcc6fd.png)

Looks very much like https://github.com/quasarframework/quasar/issues/4081

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6.
