### ISSUE TITLE
Contribute a wheel picker plugin for quasar framework

### ISSUE THREAD

**Issue by lenvonsam** [quasarframework/quasar#480]
screenshots:
![image](https://cloud.githubusercontent.com/assets/10168476/24237665/2f4fa56a-0fe2-11e7-8679-e8b2a68b6043.png)
![image](https://cloud.githubusercontent.com/assets/10168476/24237671/378f42b2-0fe2-11e7-91f7-d01f77247d7a.png)

phone live demo
![image](https://cloud.githubusercontent.com/assets/10168476/24237686/42896152-0fe2-11e7-9602-fc10fde886b8.png)

[source link](https://github.com/lenvonsam/Quasar-Wheel-Picker-Plugin) https://github.com/lenvonsam/Quasar-Wheel-Picker-Plugin

**Comment by murbanowicz** [comment]
1. Nice
2. If possible please translate to English
3. How would it work on desktop? Quasar is meant to be cross-platform.

**Comment by lenvonsam** [comment]
@murbanowicz 
hi, think for your advise.
This plugin is also in English , exclude city picker, and it has the same way to work on desktop.
good luck
best wishes~!

**Comment by rstoenescu** [comment]
Hi, let's continue this on forum. Thanks!
