### ISSUE TITLE
CSS files as exceptions in RTL

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#4800]
Hi,
How to ignore a CSS file to prevent RTL rules, for example, I’m using leaflet map in RTL project when I load the CSS files quasar add RTL rules to leaflet CSS and it’s brake and not work correctly.

I read this link https://quasar.dev/options/rtl-support#Marking-CSS-rules-as-exceptions but it works on CSS property, not files.

**Comment by M6stafa** [comment]
Hi,
I think the rtl process is based on [RTLCSS](https://rtlcss.com/).
you can ignore multiple rules by using `/* rtl:begin:ignore */` and `/* rtl:end:ignore */`.
For example use it at he start and end of your file for ignore all rules.

**Comment by rstoenescu** [comment]
Indeed it is (based on rtlcss) and not related to Quasar per se.
Mind you that from my own experience, they still have a few bugs to squash and it may not be perfect.
