### ISSUE TITLE
How to access app extension prompts

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#4802]
**Is your feature request related to a problem? Please describe.**
I am trying to access the prompts answers that were answered during my extension's installation outside of the extension's index file. This could be in the extension itself or in appLand.

**Describe the solution you'd like**
Access to extension APIs outside of the extension's index.js etc files.

**Describe alternatives you've considered**
I am currently doing this in one of my boot files for my extension (created a small util to do this):
```js
import extensionsPrompts from 'app/quasar.extensions.json';

async extPrompts (id) {
    return extensionsPrompts[id.replace('quasar-app-extension-')];
},
```
so I use that to get any extension prompts I need anywhere in my app.
[edit] like so:

```js
extPrompts('@emanimation/em-qui'); // '@emanimation/em-qui' is my extension id
// > { prompt1: 'foo', .... } 
```

**Additional context**
I wish extension index.js, prompts.js, uninstall.js and install.js were esm modules so that I could do other custom exports without messing with Quasar. That's what I tried doing initially, by trying to export the context of the API. But I see that this is pre compile stage, outside of the app code or something, so somehow this has to be done in common js code.

**Comment by hawkeye64** [comment]
In your App Extension's index.js, you should have a function like this:
```js
module.exports = function (api) {
```
When the user's app is build, you have access to the prompts **specific** to your app extension via **api.prompts**.

**Comment by emahuni** [comment]
Thank you for your response, however, that isn't the issue here. I am trying to access the prompts outside the index file, specifically in `actions.js` of a vuex module. I need to know the paths that were given during extension installation? This is the use case I am asking for here.

**Comment by nothingismagick** [comment]
These responses are available in quasar.extensions.json

**Comment by emahuni** [comment]
> These responses are available in quasar.extensions.json

exactly, that's where I am getting them from, so I am asking for some Quasar-wide adoption of that little util I guess, so that it can be used from anywhere in the app like so;
```js
import { extPrompts } from 'quasar';

extPrompts('@emanimation/em-qui'); // '@emanimation/em-qui' is my extension id
// > { prompt1: 'foo', .... } 
```

or maybe a way to expose the prompt API or Index API etc of the current extension

**Comment by nothingismagick** [comment]
Sorry for being dense - I understand that you are interested in using it similarly to how e.g. dotenv works, in that you can access these values anywhere within your app, am I right?

If so, I can see two ways of doing this today. The first is maybe not the most elegant way to do it, but why not simply require the json file and then parse for their prompt responses and cast to an object? This can be done in any component as things stand.

The other way would be to actually do this import process as an extension-specific bootfile in where the object is just exported.   

Nevertheless - I can still see how this could be useful in App Space as e.g.

```
const prompts = this.$q.ae.prompts['@emanimation/em-qui']
```

**Comment by lucasfernog** [comment]
> Sorry for being dense - I understand that you are interested in using it similarly to how e.g. dotenv works, in that you can access these values anywhere within your app, am I right?
> 
> If so, I can see two ways of doing this today. The first is maybe not the most elegant way to do it, but why not simply require the json file and then parse for their prompt responses and cast to an object? This can be done in any component as things stand.
> 
> The other way would be to actually do this import process as an extension-specific bootfile in where the object is just exported.
> 
> Nevertheless - I can still see how this could be useful in App Space as e.g.
> 
> ```
> const prompts = this.$q.ae.prompts['@emanimation/em-qui']
> ```

This could be a nice app extension.

**Comment by emahuni** [comment]
@nothingismagick  Yes, I am already doing that by importing the json file.

> const prompts = this.$q.ae.prompts['@emanimation/em-qui']

That is exactly what I am talking about! in addition we would need to access this in non-component files such as in vuex modules for instance;

Take a look at this extension in this file:
https://github.com/stefanvanherwijnen/quasar-app-extension-authentication-token-based/blob/master/src/templates/auth/src/store/auth/actions.js

He clearly didn't have any elegant way of getting those prompts. They were asked on installation, but they are now useless in the extension's codebase. @stefanvanherwijnen  actually ignored them and typed them manually instead:

```js
const REGISTER_ROUTE = '/auth/register'
const VERIFICATION_ROUTE = '/auth/verify'
const LOGIN_ROUTE = '/auth/login'
const FETCH_USER_ROUTE = '/auth/user'
const PASSWORD_FORGOT_ROUTE = '/auth/password/forgot'
const PASSWORD_RESET_ROUTE = '/auth/password/reset'
```

These are the exact prompts that he asked for on installation:

https://github.com/stefanvanherwijnen/quasar-app-extension-authentication-token-based/blob/master/src/prompts.js

But accessing them in that store was a huge problem.

My solution was the above alternative; import the json file and parse it extracting the extension's prompts. That way I can use the actual prompt answers provided at installation.

**Comment by stefanvanherwijnen** [comment]
@emahuni 
I actually forgot to render those route values, thanks for pointing it out.
https://github.com/stefanvanherwijnen/auth-token-based/commit/8ad601384adc8eb63915ef125e0771a3f510265f

I also was a bit confused on how to use the prompt values at first, but I think rendering them on installation is the correct way (correct me if I'm wrong). I believe the values in quasar.extensions.json are just for reference and shouldn't be changed manually. Thus, there is no advantage in extracting the values from the json vs rendering the prompts once on installation.

**Comment by hawkeye64** [comment]
This file available only during build time, not runtime. In package.json, in the scripts, you'd have to add build quasar app AND copy extensions file to something like statics. Now you can import/require it for your use.

**Comment by emahuni** [comment]
@hawkeye64  Thanks for pointing this out, it flew over my head. Is there no way of including it using Webpack?

**Comment by hawkeye64** [comment]
@emahuni Yes, just import/require it and it'll get rolled up by webpack. Exactly the same way you can import/require package.json to at at the `version` item.
