### ISSUE TITLE
Project creation should create a jsconfig.json with import aliases

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#4803]
**Is your feature request related to a problem? Please describe.**
Webstorm, somewhat, supports the webpack config, including aliases. But it can't read the webpack config as defined by Quasar and other frameworks, making auto-importing of aliases unavailable.

**Describe the solution you'd like**
Much like VSCode, the latest version of Webstorm (2019.2) will now read import aliases from a jsconfig.json. It would be nice if, upon project creation, a jsonconfig.json was created with all the quasar aliases already defined.

**Comment by panstromek** [comment]
This is a good point - but one catch is that you can add your aliases dynamically, so we would need to rewrite this file on every `quasar dev`.

One thing you can do to make it work though (and I do it in my projects) is to just create fake `webpack.config.js` and let idea resolve the aliases for you from it.

I generate it during build simply like this:
```js
  extendWebpack (cfg) {
        if (!fs.existsSync('webpack.config.js')) {
          fs.writeFileSync('webpack.config.js', `
/* eslint-disable */
/**
 * DON'T EDIT THIS FILE!!
 *
 * This file is generated to help WebStorm resolve Webpack aliases. It is never run in the app.
 * If you need to extend your webpack config, put your code in quasar.conf.js into extendWebpack function
 */
module.exports = ${JSON.stringify(cfg)}
`)
        }
      }
```
You can drop the warning, of course 😄.


I will integrate it in `ide-helper` eventually. Didn't have much time for it recently 😉

**Comment by devinholloway** [comment]
I'm not sure I understand. The quasar-specific aliases aren't dynamic. I'm referring to aliases like src, app, components, layouts, pages, etc.

I used to do the same as you, as far as dropping a webpack.config.js file in my project root with defined aliases. But the officially supported way of doing this in webstorm now is by using a jsconfig.json file. As of now, every time a new project is started, one has to create that file and define all the quasar aliases. Seems like something the CLI could do for you. You can always additional stuff to it if you want.

**Comment by panstromek** [comment]
I think your request is valid, just that there will still be friction when you add your own aliases.

Nevertheless, I've put it "fake" webpack config in `ide-helper`. It will be in next release. See https://github.com/panstromek/quasar-ide-helper/issues/9

**Comment by ejez** [comment]
PR merged, check  https://github.com/quasarframework/quasar-starter-kit/pull/87
