### ISSUE TITLE
QSelect Input event doesn't emit after select

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#4805]
**Describe the bug**
QSelect only emit the input event in first select, after any change is emited

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Indiegame/pen/RXLXjZ

**To Reproduce**
1. Create a QSelect
2. Change the props to use a json propertie
3. Select 1 option, the value change and the log is showed in the console
4. Select 1 option again, the value doesn't change, the input fire doesnt emited

**Expected behavior**
The input event is emited in every option selected

**Platform (please complete the following information):**
OS: Windows
Node: 12.7.0
Electron: ^5.0.8

**Comment by metalsadman** [comment]
Se option-value https://codepen.io/metalsadman/pen/BXmoaN

**Comment by pdanpdan** [comment]
https://codepen.io/anon/pen/RXjgEW?editors=1010

You have to use `option-label="name" option-value="name" map-options emit-value` because you have non-standard label, value and you don't store the whole selected object but just the value.
