### ISSUE TITLE
Validation in QSelect's add-unique mode

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#4808]
When using QSelect with add-unique mode, as in the documentation example at https://quasar.dev/vue-components/select#The-new-value-mode-prop, there is no validation on the input.
For example, I would like to prevent the use from entering values that contains commas.
I would like to have a validation similar to QInput's validation
```
    <q-select
      v-model="model"
      :rules="[ val => !val.includes(',') || 'Commas are not allowed']"
      label="Label"
      filled
      use-input
      use-chips
      multiple
      hide-dropdown-icon
      input-debounce="0"
      new-value-mode="add-unique"
    />
```

I mitigated this by setting `@new-value="onNewValue"`:
```
  methods: {
    onNewValue (inputValue, doneFn) {
      if (!inputValue.includes(',')) {
        doneFn(inputValue, 'add-unique')
      }
    }
  }
```
However, I would still want to have a visual validation error as in QInput:
![image](https://user-images.githubusercontent.com/83443/62437968-0aeac180-b74e-11e9-8fc4-2b6f7ad743a9.png)

**Comment by pdanpdan** [comment]
And what is preventing you from setting the error prop if you detect the comma?

**Comment by metalsadman** [comment]
Do it on your handler method, https://codepen.io/metalsadman/pen/OKOjOz?editors=1010

**Comment by tomers** [comment]
> And what is preventing you from setting the error prop if you detect the comma?

I would like to have this feature for consistency with the way validation in _QInput_ works.

This is a reasonable syntax:
```
    <q-input
      v-model="model"
      label="Maximum 3 characters"
      :rules="[ val => val.length <= 3 || 'Please use maximum 3 characters']"
    />
```

Versus this cumbersome syntax of the same functionality with QSelect:

```
      <q-select
        v-model="model"
        label="Maximum 3 characters"
        use-input
        use-chips
        multiple
        hide-dropdown-icon
        input-debounce="0"
        @new-value="createValue"
        :error="error"
      />

...

methods: {
    createValue (val, done) {
      if (val.length > 3) {
        this.error = true
      } else {
        this.error = false
        done(val, 'add-unique')
      }
    }
  }
```

**Comment by rstoenescu** [comment]
Hi,

I'm sorry but QSelect is overly complex as is. We can't just add custom use cases to it as it'll become a nightmare to explain how it works and a nightmare to maintain. It allows the functionality that you want already (as has been discussed), so best bet to reduce the boilerplating is to use one of the most powerful features in Vue: create a component which uses QSelect in your desired way. Then you can reuse it.
