### ISSUE TITLE
q-tooltip with parent v-if causes error

### ISSUE THREAD

**Issue by oswaldomilet** [quasarframework/quasar#481]
When I put a `v-if` in q-tooltip parent tag, an error is triggered in QTooltip beforeDestroy hook.

https://github.com/quasarframework/quasar/blob/dev/src/vue-components/tooltip/Tooltip.vue#L122-L128

If I switch from v-if to v-show don't get error, I guess it's because parent element doesn't exist in DOM when v-if condition is false.

**Comment by rstoenescu** [comment]
Will look into it. Thanks for reporting.

**Comment by rstoenescu** [comment]
Submitted issue and PR to Vue for this: https://github.com/vuejs/vue/issues/5321 and https://github.com/vuejs/vue/pull/5322

**Comment by rstoenescu** [comment]
PR submitted to Vue has been merged in. Will look for when this gets into an official Vue release and post it here.
