### ISSUE TITLE
q-input autogrow readonly shows disabled cursor

### ISSUE THREAD

**Issue by cashmisa** [quasarframework/quasar#4810]
**Describe the bug**
When input has autogrow attribute and readonly=true, input area cursor becomes disabled

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/cashmisa/pen/aeVqqw?editors=1010

**Expected behavior**
readonly cursor instead of disabled cursor

Thanks!

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6.
