### ISSUE TITLE
When using lazy-change in input, qmenu deletes input

### ISSUE THREAD

**Issue by Gnopps** [quasarframework/quasar#4813]
**Describe the bug**
When setting the input-field to use lazy-changes: 
`@change="e => { message = e.target.value }"` qmenu will delete the contents of the input-field when opened.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Gnopps/pen/wVPQVd

**To Reproduce**
1. In above Codepen, enter any value in the qinput and end with hyphen ("-"). There is a trigger to open qinput when hyphen is pressed.
2. Qinput will open and value typed in qinput will disappear

**Expected behavior**
When qmenu is opened the value in the qinput should be kept.

**Screenshots**
![GIF](https://user-images.githubusercontent.com/16313148/62465761-57f38580-b798-11e9-9a7e-1d78c627766f.gif)

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Firefox 68.0.1

**Additional context**
Code:
```<div id="q-app">
  <div class="q-pa-md">
      <div class="q-gutter-md" >
        <q-input @keydown="checkKeyPress"  :value="text"
      @change="e => { text = e.target.value }" label="Type something and then hyphen (-) to open qmenu" >
    <q-menu
      auto-close
      no-parent-event
      no-focus
      v-model="showQmenu"
    >
      <q-list dense style="min-width: 100px">
        <q-item clickable dense>
          <q-item-section>AAAA</q-item-section>
        </q-item>
        <q-item clickable dense>
          <q-item-section>BBBB</q-item-section>
        </q-item>
        <q-item clickable dense>
          <q-item-section>CCCC</q-item-section>
        </q-item>
      </q-list>
    </q-menu></q-input>
  
       
      </div>
    </div>
</div>```

**Comment by pdanpdan** [comment]
When the menu is opened the QInput is re-rendered, and because the model is unchanged from the initial value you'll get an empty content.

You have to manage the internal value management yourself, like here:
https://codepen.io/anon/pen/KOyber?editors=1010
