### ISSUE TITLE
App extension render function not copying dot files eg: `.gitkeep`

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#4814]
**Describe the bug**
App extension render function not copying dot files eg: `.myrc`. I have a dir structure that only contains dot files that I need to render to main app land during extension installation and the render function isn't copying them and completely omitting the dir structure altogether.

**To Reproduce**
1. Create extension
2. Create a file named `subdir/.myrc` in the templates dir
3. Put the render function in the index file 
```js
   // index.js
   module.exports = function (api) {
     api.render('./templates');
   }
```
4. Install the extension in a host app
5. The render function didn't copy the dot file nor the empty subdir.

**Expected behavior**
Copying of the dot file into the main app

**Platform (please complete the following information):**
Quasar 1.0.5

**Comment by nothingismagick** [comment]
Correct, dotfiles won't be copied from your template folder. All files that begin with a `.` will be ignored. The proper way to do this is to use an `_` instead. 

```
_gitignore
```

I thought that was in the documentation, but can't find it right now. Will dig in and post a link as soon as I find it.

**Comment by nothingismagick** [comment]
https://quasar.dev/app-extensions/development-guide/install-api#Filename-edge-cases

**Comment by emahuni** [comment]
Oh ok, thanks man. May I ask why there is that edge case, it seems artificial?

**Comment by nothingismagick** [comment]
```
dotfiles are ignored when publishing your plugin to npm
```
