### ISSUE TITLE
Split Button menu is not displayed in menu button

### ISSUE THREAD

**Issue by ceyhunkerti** [quasarframework/quasar#4816]
Can not display split button's menu that is located under menu button

[https://codepen.io/anon/pen/ymPWjY?editors=1010](https://codepen.io/anon/pen/ymPWjY?editors=1010)

**Comment by pdanpdan** [comment]
Add a `@click.stop` on the section that has the button, so that the click on the button is not propagated on the QItem that is clickable.
https://codepen.io/anon/pen/KOyOdo?editors=1010
