### ISSUE TITLE
Splitter component flickers badly (or disappears) when hovering over (or dragging) it

### ISSUE THREAD

**Issue by lucklouis** [quasarframework/quasar#4818]
**Describe the bug**
When hovering over a Splitter component, the mouse cursor flickers badly on Windows 10 (haven't tried on Mac) and completely disappears if the mouse is held still.   It continues to flicker badly once you begin to move the splitter bar.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pen/?&editable=true&editors=101

**To Reproduce**
As described above.

**Expected behavior**
The mouse cursor shouldn't flicker or disappear.  It ruins the otherwise excellent Quasar UI experience.  Other JS splitter libraries (e.g. SplitJS) somehow manage to get around this.

**Platform (please complete the following information):**
OS: Windows 10 Professional
Node: 10.16.0
NPM: 6.9.0
Yarn: 1.17.3
Browsers: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
Electron: 5.0.0

**Comment by pdanpdan** [comment]
I cannot reproduce on chrome . Please provide a codepen that shows the problem. Also please try if you can reproduce on another computer with different video card.

**Comment by lucklouis** [comment]
Strange - I tried recording a screen grab on Camtasia.  Camtasia records the cursor with no issues and the Splitter behaves perfectly.  It also works on a Macbook.    I took a video with my iPhone of the screen though.  I've sent it by email directly since I can't add video here.  Please check there.  

Video card and hardware information: 
MB:  ASUS Prime Z390-P
Video: NVIDIA GeForce GTX 1060
CPU: Intel Core i5-8600k

**Comment by lucklouis** [comment]
Hi again.  Video was too big.  Another try...

**Comment by pdanpdan** [comment]
As the screen grabbing application does not record any problem it must be something related to the video card or some extension in browser or some application running on the computer.

Please reopen if you can reproduce it on another computer. Thank you.

**Comment by lucklouis** [comment]
Will do.  Thanks for looking into this.
