### ISSUE TITLE
[docs]Electron build with Electron Forge example

### ISSUE THREAD

**Issue by lucklouis** [quasarframework/quasar#4819]
Please add a detailed example of how to package an Electron application built in Quasar for distribution using the excellent Electron Forge tool (https://www.electronforge.io/).   Your documentation is *excellent* to get an Electron app built but it stops just short IMHO at delivering an .exe.

Could you please document how to use Electron Forge to distribute a full "setup.exe" to actually install the executable on an end-user's computer for a better end-user experience (rather than just X-copying the folder manually)?

Quasar and Electron Forge seem like a match made in heaven and would make developer's lives a lot easier in distributing the final build.

Keep up the great work.

**Comment by metalsadman** [comment]
i use this to make an .exe installer https://quasar.dev/quasar-cli/developing-electron-apps/build-commands#Publishing-(electron-builder-only) . without the publish options.

**Comment by lucklouis** [comment]
Hi, thanks for the reply.  I'm not by my computer right now.  Do I have to
specify a path or will the .exe installer appear in the "dist" folder?
Also, will the same workflow work on a Mac?

Many thanks and terrific framework!

**Comment by metalsadman** [comment]
@lucklouis yes the installer will be in your dist folder, about mac sorry only tried this in windows, you can checkout their docs about it tho https://www.electron.build/.

**Comment by lucklouis** [comment]
Thank you for your help.  It worked brilliantly.  Strangely enough, the same code works on the Mac to create a dmg installer.  No edits.  Just worked. Thanks again.

**Comment by exauce-mwililikwa** [comment]
thank for help
