### ISSUE TITLE
~assets alias not working in icon property of the q-btn

### ISSUE THREAD

**Issue by Forux** [quasarframework/quasar#4820]
**Describe the bug**
"~assets" alias not working in icon property of the q-btn element, it just remains as is

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/forux/pen/BXJvLp

**To Reproduce**
1. Open https://codepen.io/forux/pen/BXJvLp
2. Look at img src in the browser dev tools
3. You will find 'src="~assets/sad.svg"'

**Expected behavior**
On step 3 it must be something like 'src="assets/sad.svg"' and  also it must be correct on build

**Platform (please complete the following information):**
OS: Windows
Node: v11.6.0
NPM: v11.6.0
Browsers: Chrome 76.0.3809.87

**Comment by Forux** [comment]
Actually, even 404 page from the base project does not build correctly, the assets folder do not appear in the build

**Comment by rstoenescu** [comment]
Hi,

Webpack only interprets "src" for native elements. When using a Vue component, you need to force this behavior:

`<q-btn :icon="img:require('assets/sad.svg')"`
