### ISSUE TITLE
QAvatar: Add simple size options

### ISSUE THREAD

**Issue by devinholloway** [quasarframework/quasar#4821]
**Is your feature request related to a problem? Please describe.**
Be able to size the avatar using friendly labels (just like QButton) rather than specific values/units

**Describe the solution you'd like**
`<a-avatar` size="xs|sm|md..."/>`

**Comment by pdanpdan** [comment]
Why? it's the same thing, it's more flexible, and it's only 2 chars more.

**Comment by devinholloway** [comment]
How about.... consistency? When I need a 'medium' sized Avatar, it would be nice to not have to go back and look up the exact size I'm using for medium avatars elsewhere.  Not to mention that there's only a handful of common avatar sizes anyway, and one could always override with a specific size if needed. 

And it's not "the same thing", or it wouldn't have made sense to do that with Button.

Also, when someone suggests a quality of life enhancement, is it now the new norm for the Quasar team to just ask 'why?' then immediately close the ticket without any further debate? Or is that just how you roll? Because Razvan never did that to me.

**Comment by pdanpdan** [comment]
Do you have a reference to some standard material avatar sizes? If you do please reopen and attach the reference.

**Comment by rstoenescu** [comment]
Hi @devinholloway ,

Implementing xs|sm|md|lg|xl sizes for QIcon, QAvatar, QCircularProgress and more. Will be available in 1.0.6.

**Comment by rstoenescu** [comment]
Standard sizes (xs|sm|md|lg|xl) for "size" prop on QAvatar, QCircularProgress, QIcon, QKnob, QLinearProgress, QRating, QSpinner --- will be available in 1.0.6.

**Comment by zecar** [comment]
So how can we override those values for xs/sm/md/lg/xl ?

**Comment by rstoenescu** [comment]
@zecar You're not bound only to xs|sm|md|lg|xl. Just specify your desired value (including CSS unit); example: '22px'

**Comment by zecar** [comment]
but i want to use xs|sm|md|lg|xl

i just want different values there... if i want later to modify a size i don't want to have to modify everywhere
