### ISSUE TITLE
[Request] Add classes for form component styling without using component

### ISSUE THREAD

**Issue by Gnopps** [quasarframework/quasar#4822]
**Is your feature request related to a problem? Please describe.**
Sometimes I prefer (e.g. due to performance issues) to not use the Quasar-component, but would rather just style HTML-native elements using quasar-classes. 

**Describe the solution you'd like**
For for example inputs I would like to have the option to either do `<q-input outlined>` or `<input class="quasar-input outlined">`. For the end user they would look the same, but difference would be that the first has all the functionality whereas the latter has styling only. 
This would apply to all native HTML-inputs with corresponding Quasar-inputs.

**Describe alternatives you've considered**
Other UI-frameworks support this. For example Buefy allows you to either use the component or just Bulma-styling.

**Comment by pdanpdan** [comment]
You can apply the classes without any problem, except you'll need to provide the same HTML structure as in Quasar component. Just take a look at the style files for QField, QInput, QSelect on github.

**Comment by Gnopps** [comment]
Alright, thanks. I did try [asking for this ](https://forum.quasar-framework.org/topic/4080/possible-to-use-css-classes-only-for-style-but-no-components)and based on the answer thought it was not possible. 

How about documenting this then?

**Comment by pdanpdan** [comment]
They are very complex, both the css and the html structure. And doing this is an advanced task.
