### ISSUE TITLE
Unable to Loop through Table body-cell-{$property} slots due to required :key

### ISSUE THREAD

**Issue by nateiler** [quasarframework/quasar#4824]
Perhaps I'm going about this the wrong way; I'm attempting to manipulate a various (user defined) cell data.  I attempted to loop through the columns and perform a slot override, but I get two types of errors:

https://jsfiddle.net/8Lokc4w1/1/
Note: The fiddle doesn't throw the strict warnings that my IDE + linting does.

I took a quick look at the source and this seems to be part of the issue: https://github.com/quasarframework/quasar/blob/4691db529a1b4055b2c198888f6c9eb6f1fdf484/ui/src/components/table/QTd.js#L21

**Platform:**
Quasar: 1.0.5
Vue: 2.6.10

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in 1.0.6
