### ISSUE TITLE
v-model for the q-form component

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#4828]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to have the v-model support for the q-form component. The model would indicate if the whole form is valid. That would allow interface to react more responsive, disable the submit button when the form is invalid, for example.

**Describe alternatives you've considered**
The only way (as i see it) to achive such behavior now is to call q-form's validate method each time we change one of the input's model. That means we should manually declare a watcher for each model we have in the form. This makes the whole form less supported and much harder to declare.

**Additional context**
The behavior like this is implemented in vuetify. https://vuetifyjs.com/en/components/forms. This is achived with the provide/inject mechanism. The form component provides itself to the children and each input component injects the form into itself and subscribes the form for it's changes.

**Comment by pdanpdan** [comment]
`QForm` emits `validation-success` and `validation-error` events.

`v-model` is bidirectional, and it makes no sense, because you do not want to tell `QForm` if it is valid or not.

Just add listeners for the events and set your desired form validation state variable, like this:

`<q-form @validation-success="formValid = true" @validation-error="formValid = false" ...`

**Comment by 1001v** [comment]
@pdanpdan these events doesn't solve the issue, because they fires only when the validate method is calles for the form. It means what we should manually call for validate through watchers. 
The v-model is just an example, it could be and event or a sync property, which wouldn't fire lazy.

**Comment by pdanpdan** [comment]
They are triggered when the form validation is checked. How would you know the form validity status if you're not checking it?

**Comment by 1001v** [comment]
@pdanpdan why the form can't validate itself each time the change of child inputs happen?

**Comment by pdanpdan** [comment]
Because it would be very bad for the performance. If you want complex model monitoring you should use vuelidate or something similar.

**Comment by 1001v** [comment]
@pdanpdan why it would be bad for performance?

**Comment by pdanpdan** [comment]
Please open a new issue specifying you want qform validation update on child field change.
