### ISSUE TITLE
<q-img> maybe has a bug

### ISSUE THREAD

**Issue by derekwin** [quasarframework/quasar#4831]
<q-img>  src    maybe a bug

I use < q-img > to insert pictures, but the ‘src’ address does not recognize the local image path and only works for the network path.

pic path :   assets/bg_pic/pic.jpg
vue file path :   views/Home.vue

I use quasar via   vue cli
quasar version 1.0.5
vue version 3.10.0

<q-img src="../assets/bg_pic/pic.jpg">
          <div >
          </div>
 </q-img>

it does work.

**Comment by rstoenescu** [comment]
So, for Vue CLI:

`<q-img :src="require('@/assets/logo.png')" />`
Webpack catches "src" attribute on native "<img>" tags only, so you need to force this on a component.
