### ISSUE TITLE
QPullToRefresh not working in touch mode on scrollable divs on quasar v1.0.5

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#4832]
In previous versions of quasar v1 (beta) the issue was that QPullToRefresh was preventing scrolling in overflowing divs.

In the newer versions the issue is different - scrolling in touch mode QPullToRefresh is not triggered when pulling down. Touch scrolling works as expected. Using a mouse on a desktop PC works.

Steps and code to reproduce is available in the previous issue #3644

The fix in #3644 was solved by @pdanpdan

**Comment by pdanpdan** [comment]
Close this issue - please follow up in unified #5051
