### ISSUE TITLE
[v1-bug] Scrollbar appears in IE when input is focused inside the QDialog

### ISSUE THREAD

**Issue by mountash** [quasarframework/quasar#4839]
**Describe the bug**
When QDialog has a QCard with width set and input field inside it, a scrollbar appears when user puts focus to the input field or writes smth in it.
**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/hyxLj91k/6/

**To Reproduce**
1. Go to https://jsfiddle.net/hyxLj91k/6/ using IE or Edge
2. Click on 'OPEN DIALOG' button 
3. Focus the input field or write smth there
4. Scrollbar appears

**Expected behavior**
Scrollbar must not appear

**Screenshots**
![dialog_bug](https://user-images.githubusercontent.com/6277925/62682873-71294b80-b9bd-11e9-9f09-3fdeabcc160f.gif)

**Platform (please complete the following information):**
Operating System - Windows_NT(10.0.17763) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

Important local packages
  quasar - 1.0.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.4 -- Quasar Framework local CLI
  @quasar/extras - 1.2.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.7 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.5.0 -- Babel compiler core.
  webpack - 4.35.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess
files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  quasar-app-extension-ide-helper - 0.0.5 -- Quasar framework extension which enables IDE features like autocomplete by generating helper files for IDE to index.

**Comment by rstoenescu** [comment]
Fix will be available in 1.0.6.
