### ISSUE TITLE
[v1] QDate - No event when selecting the same value

### ISSUE THREAD

**Issue by mlaroche** [quasarframework/quasar#4841]
**Is your feature request related to a problem? Please describe.**
Kind of. I try to reproduce the behaviour of the v0.17 QDateTime Input but i'm not able to do so because no event is triggered when the user clicks on the already selected day. So it's impossible to always hide the QDate component after any user interaction.

**Describe the solution you'd like**
I would like the QDate component to emit an Event (either the already existing input event or a new one) when the user clicks on the already selected day. 

**Describe alternatives you've considered**
 - Bring back the good old (and cherished) v0.17 QDateTime Input component ;-)
(Besides, I clearly understand the modularization path you've taken with v1, but I really miss the 'ready to use' high level components philosophy)
 - Use the [TobyMosque DatePicker](https://github.com/TobyMosque/app-extension-qdatetimepicker) but I don't like the idea of buttons (set and cancel)

**Additional context**
Here's a codepen to demonstrate what I want to achieve : https://codepen.io/anon/pen/dxdXwa

**PS**
For your information, we've chosen Quasar as our component library to build our Framework UI layer based on VueJS (with an MPA paradigm). Here's the link to the Github repo if you're interested and want to take a look : https://github.com/vertigo-io .
So, thanks for the amazing work and please keep building the UMD version in the future (SPAs are not ideal for every usage !).

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1
