### ISSUE TITLE
QSelect native like auto complete

### ISSUE THREAD

**Issue by lajuffermans** [quasarframework/quasar#4849]
Native selects have the ability to type to an option which is very handy in cases you already know what to select.

e.g., you have to fill in your address, focus on the select and start typing a country, Native selects (and Vuetify as well) start focusing the typed country.

I know this can probably be done with filters etc. but personally I think it should be default behaviour in QSelect.

**Comment by danielfaust** [comment]
+1, but this needs to be restricted to the cases where `new-value-mode` is not set. Else trying to add "Test" to a set which contains "Testable" would end up selecting "Testable" instead of adding "Test".

**Comment by pdanpdan** [comment]
Use a QSelect with filtering, and then you can just navigate to the first option using arrow down.
It looks like exactly the same behavior google has for search.
This way you are key away from the first matched option and you have the freedon to type whatever you want.
