### ISSUE TITLE
Platform.is in chrome extension detects cordova

### ISSUE THREAD

**Issue by mbouclas** [quasarframework/quasar#485]
Trying to build a chrome extension and quasar is having problems detecting the right Platform.

So, the problem is in `quasar.common.js` here
```
else if (window._cordovaNative || document.location.href.indexOf('http') !== 0) {
    browser.cordova = true;
  }
```

Apparently, when in chrome extension `document.location.href.indexOf('http') !== 0` is true, so browser.cordova becomes true and then it tries to load the `cordova.js`  which leads to a 404 and a hard crash. 

The `document.location.href` in the chrome extension is `chrome-extension://aglafcallenphbbcjembaodlpenkalfn/index.html#/main`

Maybe add a new environment for extensions or change the check somewhat?

**Comment by rstoenescu** [comment]
Hi,

Saw the forum thread and was about to make the necessary changes. Thanks for specifying the document location URL for a Chrome Extension, made my life a little bit easier :)

Pushed commit to add the right support. Available in edge version and future v0.14.
Besides fixing this issue, you can now also detect if code is running as chrome extension by looking at `Platform.is.chromeExt`.

Thanks!

**Comment by rstoenescu** [comment]
@mbouclas let me know if you find any other problems when running as Chrome extension. It's completely untested in such environment, but other than this issue here (pushed commit earlier) there shouldn't be any other problems.

**Comment by mbouclas** [comment]
Will do, first time trying chrome extension with quasar as well. Can you push the changes to npm?

**Comment by rstoenescu** [comment]
Please use edge version (http://quasar-framework.org/guide/quasar-nightly-build.html) until v0.14 is released. Looking forward to your findings!

**Comment by mbouclas** [comment]
cheers
