### ISSUE TITLE
Table marge

### ISSUE THREAD

**Issue by fjl280855990** [quasarframework/quasar#4852]
Are there any implementations of merging table headers, rows and columns?

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by metalsadman** [comment]
Into a grid of some sort? Please give more info or example of what youre trying to request.

**Comment by fjl280855990** [comment]
thanks


------------------ 原始邮件 ------------------
发件人: "Aldrin Marquez"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 晚上8:57
收件人: "quasarframework/quasar"<quasar@noreply.github.com>;
抄送: "Moomba"<280855990@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [quasarframework/quasar] Table marge (#4852)




Into a grid of some sort? Please give more info or example of what youre trying to request.
