### ISSUE TITLE
Using Quasar as Nuxt(VUE) plugin - but icon-set isn't showing on QBtn (icon="mail"), how can correct it?

### ISSUE THREAD

**Issue by arioch74** [quasarframework/quasar#4854]
Hello! I use:

_plugins/quasar.js_
```
import Vue from 'vue';
import "quasar/dist/quasar.css";

import Quasar, { QBtn } from "quasar";
Vue.use(Quasar, { components: [QBtn] });
```

_pages/index.vue_
```
<template>
  <div class="container">
    <q-btn color="primary" icon="mail" label="On Left" />
  </div>
</template>
```

on clear Nuxt+Quasar ($ npm install --save quasar) installation

QBtn is working fine, but icon is not showing. 

I try many config-tricks like https://quasar.dev/options/quasar-icon-sets#Vue-CLI-Way && https://quasar.dev/options/quasar-icon-sets#Quasar-CLI-Way - not working.

What can I do with it. 

Thank you!

//When I install Quasar as stand-alone framework ($ quasar create <folder_name>) - icon-set is showing fine even without any configuration.

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by arioch74** [comment]
Ok) but it is not a bug?

I need to integrate Quasar to existing Vue-project, and can not do this :(

**Comment by smolinari** [comment]
That's exactly the problem. We don't know if it is a bug or if you are doing everything correctly or not. For instance, did you install [Quasar as a Vue plugin](https://quasar.dev/start/vue-cli-plugin)? That's what we'll work out with you in the forums or chat. Once we boil it down to a bug, we'll ask you to then place it here. 

Scott
