### ISSUE TITLE
Change what "Disabling" a QSplitter means

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#4855]
Right now if you set "disabled=true" on QSplitter you get your entire screen space in left and right areas dimmed and the disabled mouse icon on everything.  It would be nice if disabling just froze the splitter position (and didn't react [change cursor] on mouseovers).  I think most users would expect / want this behavior.

**Comment by pdanpdan** [comment]
Makes sense :)

**Comment by rfox12** [comment]
Here's a workaround for now!

      <q-splitter
        v-model="screenSplitValue"
        :separator-style="(folderViewVisible?'cursor: col-resize;':'cursor: default;')"
        :limits="(folderViewVisible?[20, 60]:[screenSplitValue,screenSplitValue])"
        class="full-height"
      >

**Comment by rstoenescu** [comment]
Hi,

The actual property is `disable` not `disabled`. This is same for ALL Quasar components.
If you specify `disabled` (ends with 'd') then it gets applied as a HTML attribute.
