### ISSUE TITLE
q-table support for GraphQL cursors?

### ISSUE THREAD

**Issue by timneedham** [quasarframework/quasar#4857]
**I :heart: Quasar!** `{"quasar": "^1.0.0"}` 

**Is your feature request related to a problem? Please describe.**

I'm using a GraphQL endpoint to bring data into a Quasar app. The server-side capabilities of `q-table` are 99% perfect for what I need to do (list the results as rows, in a tabular form but with [server-side pagination/filtering/sorting](https://quasar.dev/vue-components/table#Server-side-pagination%2C-filter-and-sorting)).

However, [Relay-style cursors](https://facebook.github.io/relay/graphql/connections.htm) are in use on the backend, so there's no real concept of "pages" or "page numbers" (i.e. the SQL-style limit/offset implementation supported by `q-table`).

**Describe the solution you'd like**
Assuming Relay-style GraphQL endpoints can provide content like this as part of its results:

``` json
{
     "pageInfo": {
        "startCursor": "WyJwcmltYXJ5X2tleV9hc2MiLFswXV0=",
        "hasPreviousPage": false,
        "hasNextPage": false,
        "endCursor": "WyJwcmltYXJ5X2tleV9hc2MiLFs2MzkwMl1d"
      },
      "totalCount": 2
}
```
Just like `rowsNumber` (still usable in a cursor context), it would be great to have some additional props to support a "cursor style" too:

* `style`:  (`enum`)... `page` (the default) or `cursor`
* `hasNextPage` (`boolean`)... if `true`, activates a little **>** somewhere.
* `hasPreviousPage` (`boolean`)... if `true`, activates a little **<** somewhere.
* `startCursor` (`string`)... a value to pass in the server request for things "before" (i.e. when the **<** button is clicked).
* `endCursor` (`string`)... a value to pass in the server request for things "after"  (i.e. when the **>** button is clicked).

With the increasing popularity of GraphQL, and cursor-style pagination for Twitter-like feeds, this seems a valuable additional capability for `q-table`... especially as such a large-chunk of the server-side stuff is already there for the "page style"? 

**Describe alternatives you've considered**

* Rolling-our-own using `q-markup-table`, but that feels like re-inventing a lot of the server stuff?
* Using `q-pagination`.... but that's page orientated too?

**MVP?**

* Failing full cursor support, a simple way to provide **<** and **>** pagination controls, without the need to have "page numbers"?

**Additional context**

**Comment by metalsadman** [comment]
Imo idunno gql, but with those props of your cursor, pretty sure you can work it out with qtables pagination, since you can control what it calls at request event, and just assign the values of pagination props equivalent to what props in your cursor when it resolves in the client still inside the request function. You dont have to reinvent just implement the pagination properly.

**Comment by timneedham** [comment]
Hi @metalsadman , thanks for this. Yeah, I'm sure you're right. I think it boils down to not being able to easily remove the current-page-number in the table, is all?

* I'm thinking of just creating a new component that's more Twitter-like, with "Get latest" and "Get more" functionality - which is more list-y/cursor-y.

**Comment by rstoenescu** [comment]
Hi,

Sorry but we need to keep code maintainable and as performant as possible. Supporting custom services should be done through [App Extensions](https://quasar.dev/app-extensions/introduction) or custom components. Alternatively, try to write an adapter to translate from/to QTable's requirements, although I must admit that it might not be possible given your requirements.
