### ISSUE TITLE
Use icons outside the Material.io

### ISSUE THREAD

**Issue by mbouclas** [quasarframework/quasar#486]
Is there a way to use local svg icons in addition to the default material ones?

reply

**Comment by rstoenescu** [comment]
v0.14 adds the ability to use multiple font icons, so not only Material like now.

**Comment by mbouclas** [comment]
Is that on the nightly and if so any examples?

**Comment by rstoenescu** [comment]
Nope, not on nightly (edge). Only on v0.14 which is currently not ready for an alpha/beta release.

Examples:

Ionicon: `<q-icon name="ion-arrow-down-a" />`
Material: `<q-icon name="alarm" />`
Fontawesome: `<q-icon name="fa-bath" />`

Specific icons for each Quasar theme: `<q-icon mat="cloud" ios="fa-bath" />` (renders different icon when built with each theme)

**Comment by mbouclas** [comment]
Don't know how far down the implementation you are, but maybe it's worth adding another directive like so `<q-icon svg-src="/statics/icon.svg" />`

This would make the whole thing a lot more versatile when it comes to small/medium projects where you only need an extra one or two icons

**Comment by rstoenescu** [comment]
@mbouclas You can use `<img src="/statics/icon.svg">` instead. Icon component will only work with font files for consistency and design predictability.
