### ISSUE TITLE
Images used in Q-Img tags are not being copied by `quasar build` 

### ISSUE THREAD

**Issue by usmcamp0811** [quasarframework/quasar#4861]
The images used in my `<q-img>` tags are not being copied over when I run `quasar build`. 

Example code:
`<q-img src="../assets/resume/meinfallujah.jpg" class="fallujah" usemap="#palehorse"></q-img>`

If I convert it to a normal `<img>` tag the images get copied over. 

Am I doing something wrong or is this a bug? 

Also this `<img v-bind:src="'../assets/resume/' + schools.image">` doesn't seem to copy images over either.. 

And yes all the images are working when I run `quasar dev`

**Comment by rstoenescu** [comment]
Hi,

`<q-img :src="require('assets/....')"`
