### ISSUE TITLE
Github Layout from Layout gallery not really responsive 

### ISSUE THREAD

**Issue by vsirghii** [quasarframework/quasar#4863]
Hello,
I'm trying code for Github layout from quasar/docs/src/layouts/gallery/github.vue and it works as expected on desktop. But on Mobile view horizontal navigation links ('Pull requests', 'Issues', 'Marketplace' and 'Explore') collapse and there is no hamburger mobile menu toggle button to access those disappeared links. Whereas the real Github app has that hamburger icon in mobile view. 
Is there a way in code to enable toggle button?

**Comment by vsirghii** [comment]
![image](https://user-images.githubusercontent.com/26068474/62824962-31579500-bb72-11e9-8206-4535860b2a10.png)

**Comment by rstoenescu** [comment]
Hi,

You can add a menu yourself (button on toolbar and a QDrawer on layout). These layouts offer a starting point / inspiration so don't expect you'll get a full fledged Github website (or 1:1 copy) with full functionality there. Doesn't mean it can't be done of course, but it's outside of the scope of layout examples. You can take a look at the other layouts which have a drawer to get inspiration. Thank you.
