### ISSUE TITLE
Possibility to have 2 toggle colors

### ISSUE THREAD

**Issue by FreddyCrugger** [quasarframework/quasar#4873]
Hello,

It would have been create to be able to set 2 colors for the toggle buttons.

In many case, the user may need  an "on or off", on  = green and off = red.

At the moment, the off is grey.

Thank you.

**Comment by metalsadman** [comment]
Can only do this https://codepen.io/metalsadman/pen/PMMBjp?&editable=true&editors=101

Im on mobile, try to inspect the page you can prolly override the class for the circle thing and give it a conditional class to add or remove the class same as what i did with the color props in the pen.

**Comment by FreddyCrugger** [comment]
Thank you so much for the very fast reply.
I will give it a shot for the circle.

**Comment by metalsadman** [comment]
> Thank you so much for the very fast reply.
> I will give it a shot for the circle.

see updated pen https://codepen.io/metalsadman/pen/PMMBjp.
