### ISSUE TITLE
Unmasked QInput text overlays

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#4875]
![image](https://user-images.githubusercontent.com/10262924/62894018-19fee000-bd09-11e9-8c7e-6b6f9b5beb62.png)

size for first one is: 244x15
size for second one: 244x20

The seond one is missing reference to this class:
```
.q-field--float .q-field__label {
    transform: translate3d(0,-40%,0) scale3d(0.75,0.75,0.75);
    right: -33.33333%;
}
```
This is the css needed.
```css
    &.q-field--float .q-field__label
      transform translate3d(0, -30%, 0) scale3d(.75, .75, 1)
```
QField.js (see last item):
```js
    classes () {
      return {
        [this.fieldClass]: this.fieldClass !== void 0,

        [`q-field--${this.styleType}`]: true,
        'q-field--rounded': this.rounded,
        'q-field--square': this.square,

        'q-field--focused': this.focused === true || this.hasError === true,
        'q-field--float': this.floatingLabel,
...
```

**Comment by hawkeye64** [comment]
Disregard the reference above. I messed up and used the wrong one.

**Comment by hawkeye64** [comment]
This next reference is good.

**Comment by hawkeye64** [comment]
any traction on this?

**Comment by rstoenescu** [comment]
Hi,

I'm a bit confused by this, because bleeding edge works correctly. Investigated a bit and the floating label logic does not seem to need any fixes.

`floatingLabel` computed prop looks at (amongst other things):

```
(
          this.inputValue !== void 0 && this.hideSelected === true
            ? this.inputValue.length > 0
            : this.hasValue === true
        )
```

In this case, it takes `hasValue`, which in turn looks at `innerValue` which is correctly filled.

Can you re-test with bleeding edge pls? What am I missing?

**Comment by hawkeye64** [comment]
Will do.

**Comment by rstoenescu** [comment]
Thx. I mean, nothing changed to this respect into the code for some time. So wondering if I am missing something.

**Comment by hawkeye64** [comment]
Either way, I just built with bleeding edge (yarn build in ui, copy to node_modules/quasar/dist in docs, quasar dev, etc) and it no longer appears to be an issue:
![image](https://user-images.githubusercontent.com/10262924/63637191-f86df480-c636-11e9-9c6e-0125fc59c251.png)
