### ISSUE TITLE
Missing `lang` property in QVueGlobal interface

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#4877]
**Describe the bug**
Interface QVueGlobals in `node_modules/quasar/dist/index.d.ts` does not contain `lang` property

**To Reproduce**
1. Install typescript extension
2. Type `this.$q.lang`

**Screenshots**
![2019-08-13_00-24-59](https://user-images.githubusercontent.com/11452353/62901175-d043e300-bd64-11e9-9e97-0bc2ec9d0089.png)

**Comment by rstoenescu** [comment]
Fix will be available in 1.1.0
