### ISSUE TITLE
Multiple Column Sorting in table

### ISSUE THREAD

**Issue by rutvij2292** [quasarframework/quasar#4881]
Hello Quasar Framework Community,

Thanks for an amazing framework. I really appreciate of each and everyone. I've a question regarding multiple column sorting in table.

Since last 2 days I was playing with **QTable API** to implement **multiple column sorting**. If anyone has implemented this feature, please share code snippets, I would really appreciate that.

Thanks & Best Regards,
Rutvij :)

**Comment by hawkeye64** [comment]
@rutvij2292 Have you tried to ask this question on the firum or Discord channels? You're likely to get more traction there then in the repor issues area.

**Comment by rutvij2292** [comment]
@hawkeye64 Jeff I haven't. Okay, I'll ask this question directly in the forum/discord channels. Thanks for quick reply. 👍
