### ISSUE TITLE
[1.0.5] - IE all versions padding in toolbars

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#4884]
**Describe the bug**
The padding for toolbars in all versions of IE does not match chrome/firefox/safari

**Codepen/jsFiddle/Codesandbox (required)**
View the toolbars in the docs in any version of IE - https://quasar.dev/vue-components/toolbar

**To Reproduce**
View the toolbars in the docs in any version of IE - https://quasar.dev/vue-components/toolbar

**Expected behavior**
Expect them to have the same padding

**Comment by rstoenescu** [comment]
Fix will be available in 1.1.0
