### ISSUE TITLE
In a QTree node, when no header is present, shift up content

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#4889]
**Describe the solution you'd like**
When a QTree node has no header, to prevent a space, shift up the content.

This could be considered a `bug` instead of a `feature` request depending on your perception.

https://codepen.io/Hawkeye64/pen/XWrXgOM?&editable=true&editors=101

**Comment by pdanpdan** [comment]
Closing this to follow in https://github.com/quasarframework/quasar/issues/6959

**Comment by pdanpdan** [comment]
There is no practical way to determine if there is going to be a header slot or not, so the best solution is to place a class on the content of the body slot when you know there is not going to be a header.
https://codepen.io/pdanpdan/pen/PoPyJZB
the class should by default have a `margin-top: -19px`
