### ISSUE TITLE
Cookies.set ignores Date object in "expires" option

### ISSUE THREAD

**Issue by xnoybis** [quasarframework/quasar#489]
### Software version

Quasar: 0.5.2
OS: Ubuntu 16.04
Node: 4.2.6
NPM: 3.5.2
Browsers: All

### What did you get as the error?
No indication/error thrown.

### What were you expecting?

Cookies.set method to set expiration for the cookie, using Date object.

Documentation (http://quasar-framework.org/api/js-cookies.html) states the following:
"Define lifetime of the cookie. Value can be a Number which will be interpreted as days from time of creation or a Date object. If omitted, the cookie becomes a session cookie."

Method handles only the Number scenario, when a Date object is passed it is ignored and cookie expires with session.

### What steps did you take, to get the error?

`import { Cookies } from 'quasar'`

`let expiryDate = new Date();`
`Cookies.set('bigsecret', 'foo', { expires: expiryDate });`

**Comment by rstoenescu** [comment]
Hi, will investigate. Thanks for reporting.

**Comment by rstoenescu** [comment]
Pushed fix. Available in edge version and future v0.14.
