### ISSUE TITLE
Mororepo setup

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4890]
**Is your feature request related to a problem? Please describe.**
I must start a new project which will fit nicely with a monorepo style: a dashboard app plus a widget mainly thought for Electron, both using Quasar.
I currently created a monorepo using yarn workspaces and Lerna, then I created multiple Quasar apps inside the `packages` folder, plus some utility workspaces.
Problem with this setup is that all nice out-of-the-box stuff should be moved up one level, at Lerna root, and this doesn't seem to be the way to do stuff within Quasar.

Also, extension system check for already installed one seems to act weirdly when two Quasar apps are installed into the same monorepo, marking as installed extensions added only to the paired app (could be because of yarn hoisting, if the check is done on the package being present into node_modules).

**Describe the solution you'd like**
I'd like to use Quasar in a monorepo fashion, keeping same linting, typescript, testing and CSS configuration for all apps.
Something like Narwhal Nx does with Angular, superpowering its monorepo capabilites and lifting all the work.
I actually can't wrap my head around which is the best way to accomplish this, my aim with this issue is to gather ideas and opinions about the subject, and eventually guidance.

I already took a look to some Quasar monorepo (quasar-testing for example), but linting and other stuff is mainly setup only in tests folder.

**Describe alternatives you've considered**
Maybe finding some way to add a double electron target within the same Quasar project, but this scenario doesn't seem to be supported as well.
The only other option is to go full redundant and copy-paste stuff around.

**More context**
I think an optional multi-app setup inside a single Quasar project, like Angular does, can be a nice solution, allowing to advance Quasar version and dependencies for all apps at once.

Is this a scenario you already considered/discussed?

**Comment by rstoenescu** [comment]
Hi,

This should work correctly. At least with latest `@quasar/app` (v1.0.4).
If you tested with earlier versions, please update and redo the test.
If you tested with latest, then please share a reproduction repo along with instructions.

Thanks!

**Comment by rstoenescu** [comment]
Kind ping @IlCallo

**Comment by IlCallo** [comment]
Hi! Sorry, I forgot to answer.
I currently paused my trials on a monorepo version and left them in a side branch for when I'll have more time.

When I tested it, I was using latest quasar app version, which was the 1.0.4 at the time.

In October I'll get to it again and see if updating stuff solve something or if the error was transitory.
If you want to close the issue to keep everything clean, feel free to do so: in that case I will open a other one if I meet that bug again.

**Comment by rstoenescu** [comment]
Sounds good. Please open another one if it will be the case. There's been done a lot of work for the monorepo setup to work correctly. So interested when you have time (October, December, ...) on your feedback if something still doesn't works. Cheers.
