### ISSUE TITLE
Footer and Header in Q-SELECT

### ISSUE THREAD

**Issue by Denis-String** [quasarframework/quasar#4892]
**Is your feature request related to a problem? Please describe.**
We don't have a practical way to add an element at the beginning and end of the list, rendered inside the ``v-slot="options"``

**Describe the solution you'd like**
Has two new slots to use inside the ``q-select`` being Footer and Header

**Additional context**
![image](https://user-images.githubusercontent.com/37001469/62983734-d8545f00-be06-11e9-8833-80976533c1aa.png)

**Comment by pdanpdan** [comment]
This will be available in the next release (1.1.0) - there will be 2 new slots (`before-options` and `after-options`).
