### ISSUE TITLE
Input component has no outlined border.

### ISSUE THREAD

**Issue by xcc2** [quasarframework/quasar#4893]
**Describe the bug**
Input component has no outlined border.

**To Reproduce**
Go to offical website, and scroll to the form-input component.

**Screenshots**
![image](https://user-images.githubusercontent.com/16175145/62991860-e98f8100-be83-11e9-84ec-8fdc24b60319.png)

**Platform (please complete the following information):**
OS: Windows10
Chrome: 76.0.3809.100

**Comment by pdanpdan** [comment]
Please check if you have browser specific styles or extensions. Inspect the element in DevTools to see who is removing the border.

**Comment by smolinari** [comment]
WIn 10 Pro. Same browser version here.

![image](https://user-images.githubusercontent.com/3314957/62999698-85fb5880-be6f-11e9-9cf2-b5aea54ce6cb.png)

Scott
