### ISSUE TITLE
CLI sends cordova platform 'browser' to malformed URL

### ISSUE THREAD

**Issue by danicholls** [quasarframework/quasar#4894]
**Describe the bug**
`quasar dev -m cordova -T browser` ends up opening `http://localhost:8000/<url>` (like `http://localhost:8000/http://xxx.xxx.x.x:8080/`) instead of `<url>`. (Using the latest CLI, but with the v0.17 branch.)

**Codepen/jsFiddle/Codesandbox (required)**
N/A. This is for the CLI, not the Framework.

**To Reproduce**
1. `npm install -g @quasar/cli`
2. `quasar create q-cordova-dev -b v0.17` (select Yarn install at end)
3. `quasar mode -a cordova`
4. `cd src-cordova && cordova platform add browser`
5. `cd .. && quasar dev -m cordova -t ios -T browser`

Compare by then doing: `cd src-cordova && cordova run browser` (which works, but doesn't have any Quasar hot reloading etc.).

**Expected behavior**
I expected a browser window to open up at the detected IP address.

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: Windows 10 (inside or outside of Linux subsystem)
Node: 8.10.0
NPM: 3.5.2
Yarn: 1.17.3
Browsers: Firefox
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**
Used to use this all the time with `quasar-cli`, so I think it's a new issue. Using 0.17.26 now (maybe a few versions before, when using `quasar-cli` instead of `@quasar/cli`).

**Comment by danicholls** [comment]
My current `quasar info`:

```
Operating System                Linux(4.4.0-18362-Microsoft) - linux/x64
NodeJs                          8.10.0

Global packages
  NPM                           3.5.2
  yarn                          1.17.3
  quasar-cli                    0.17.26
  vue-cli                       Not installed
  cordova                       9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar-cli                    0.17.26 (Quasar Framework CLI)
  quasar-framework              0.17.20 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.9   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)    
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.25.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.14  (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.6.3   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)
```

Should note that I am not sure I was using Cordova 9 before, when I didn't see this bug.

**Comment by webnoob** [comment]
I'm going to look into why this happening but why are you using Cordova's browser mode over building a standard SPA in Quasar?

**Comment by danicholls** [comment]
It is the easiest way to test Cordova and iterate quickly and I build in the cloud.

**Comment by dev-steverob** [comment]
I also have this problem, Cordova as some plugins which also work in the browser so helps keep one code base.

**Comment by rstoenescu** [comment]
Hi,

Kindly please upgrade to v1. We currently do not have the time resources necessary to investigate this for v0.17. Sorry for inconveniences :(

**Comment by danicholls** [comment]
Thanks, I understand. It’s quite easy to work around, so not a big problem.
