### ISSUE TITLE
Make datetime (and range) use JS Date class too

### ISSUE THREAD

**Issue by druppy** [quasarframework/quasar#490]
It would be really nice to make it possible to use the build in Date class as arguments for the `q-datetime` component (and range that uses this too), along with letting go of the direct dependency of `MomentJS`.

The cheap version is to just change the interface, and make the formatting by hand formatting it, and then let the user either provide a custom format function, or event better a scoped slot as with the data table.

I would gladly contribute this myself (if Razvan has not done it already in 0.14) , but I like to know if there are other ideas we may take to hart.

/BL

**Comment by rstoenescu** [comment]
Will see if this can go into v0.14 or we delay a little for right after v0.14. This is an excellent suggestion.

**Comment by rstoenescu** [comment]
In v0.14. Check beta. Momentjs removed completely.
