### ISSUE TITLE
Nasty resize effect on SSR mode

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#4900]
**Describe the bug**
In SSR mode, after page load I can see for a little while:
1) The top bar doesn't show
2) The left drawer appears

After a few milliseconds (but easily perceptible) the top bar appears and the left drawer animates to the left and disappears
I've attached a GIF on the Screenshots section

**Codepen/jsFiddle/Codesandbox (required)**
Its in SSR mode and I couldnt figurate how to put it on fiddles

**To Reproduce**
1. Load the Index.vue route ("/") with F5 (or Refresh)

**Expected behavior**
The top bar appears on the first sight and the drawer doesn't.
**Screenshots**
![Peek 14-08-2019 23-37](https://user-images.githubusercontent.com/9467722/63069554-b4b81400-beed-11e9-9e74-bae3b612a59c.gif)

**Platform (please complete the following information):**

Operating System - Linux(4.19.62-1-MANJARO) - linux/x64
NodeJs - 11.15.0

Global packages
  NPM - 6.10.2
  yarn - 1.17.3
  @quasar/cli - 1.0.0-rc.2
  cordova - Not installed

Important local packages
  quasar - 1.0.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.4 -- Quasar Framework local CLI
  @quasar/extras - 1.2.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.7 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.5.5 -- Babel compiler core.
  webpack - 4.35.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - juanilab
  wlp0s20f3 - 192.168.1.108

**Additional context**
SSR mode: `quasar dev -m ssr`

**Comment by rstoenescu** [comment]
Hi,

Improved a lot on future 1.1.0.
