### ISSUE TITLE
Let the mousedown event trigger the ripple instead of the click

### ISSUE THREAD

**Issue by ODtian** [quasarframework/quasar#4901]
**Is your feature request related to a problem? Please describe.**
Let mousedown trigger the ripple, which makes the experience feel smoother and is the choice of most ui frameworks.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Triggering on mousedown doesn't feel right. More information: https://github.com/quasarframework/quasar/issues/878
