### ISSUE TITLE
q-input type number and password

### ISSUE THREAD

**Issue by laurohen** [quasarframework/quasar#4902]
I'm going through a problem that I haven't found a solution yet.
How do I make an input with numeric type and password active?
I need that in App mobile the password field appears numeric keypad and password active at the moment I type password.

**Comment by pdanpdan** [comment]
Sorry, it's not possible in `QInput` if it's not possible with a plain HTML `input`. If you can find a way to do it with plain `input` it should work the same with `QInput`.

But you can try to workaround it by using a fake input field and a custom numeric keypad on page.
