### ISSUE TITLE
q-uploader: invalid or no URL specified

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#4903]
https://quasar.dev/vue-components/uploader#QUploader-API
tells me that url is not required
but this code

```
<q-uploader :label="label" :multiple="multiple" class="full-width" auto-expand
            :auto-upload="autoUpload" :factory="uploadFactory"
            accept=".jpg, .png, .gif, image/*" ref="Uploader">
</q-uploader>
```

tells me

> q-uploader: invalid or no URL specified

here is _uploadFactory_

```
uploadFactory(file) {
                        let vm = this,
                            data = new FormData();           
                        return new Promise((resolve, reject) => {            
                            this.$axios.post('/upload', data, {            
                                    headers: { 'Content-Type': 'multipart/form-data' }            
                                })            
                                .then(response => {                                        
                                    resolve(file);            
                                })            
                                .catch(error => reject(error))            
                        });            
                    }
```

**Comment by rstoenescu** [comment]
Hi,

The `factory` prop should return an Object with QUploader config or a Promise resolving with the QUploader config, unless you explicitly declare those props. It's not meant to do the actual upload... this is taken care of by the component itself.

Please take a look again at the examples (https://quasar.dev/vue-components/uploader#Factory-function) and at the API card (https://quasar.dev/vue-components/uploader#QUploader-API).

**Comment by matro-skin** [comment]
I changed `resolve(file)` to `resolve({ url: '/upload' })`
And now see duplicate sending...
The first time with axios (that I use inside Promise), and then again after that
I need to send the file with specific key and with another data (some info about sender, for example)
How can I do it?

**Comment by rstoenescu** [comment]
By default, each file is uploaded in its own thread. If you are looking to upload all files using only one thread (so in a single batch), then use the `batch` prop.

**Comment by matro-skin** [comment]
No, I send single file, it's ok
But I need to use axios, and attach some formdata to the file

**Comment by matro-skin** [comment]
Interesting… In my code above, I changed `resolve(file)` to `resolve(null)`
It works, axios sending and no errors in console
