### ISSUE TITLE
Allow Quasar CLI to install specific branches of Quasar extensions

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#4911]
### Suggested change
When writing to `quasar.extensions.json`, the cli should write the extension name correctly, even if that extension was installed using a specific branch. This currently almost works
### Context
I recently had a need to install the `dev` branch of a quasar extension. Currenlty this is possible by following a few steps. Here I will use QCalendar, but this probably applies to other extensions too:
#### 1. Install the extension
We must specifiy the banch during the install.
```bash
quasar ext add  @quasar/qcalendar#dev
```
#### 2. Correct `quasar.extensions.json`
Quasar cli incorrectly adds the branch to the extension name. We must fix that
Before:
```json
{
  "@quasar/qcalendar#dev": {}
}
```
After:
```json
{
  "@quasar/qcalendar": {}
}
```
#### Done!
As you can see, out of the box support is almost there.

The suggested change would be for quasar cli to remove the branch when writing to `quasar.extensions.json`
I'm unfamilliar with the cli but here is a regex that will capture the last `#` in a string, and everything after until the end of the string.
```
/#[^#]+$/
```
#### Uninstalling
I was able to verify that uninstalling works, but you must not revert the change in `quasar.extensions.json` nor specify the branch in the remove comand.
```
quasar ext remove @quasar/qcalendar
```
#### Conflict with other branches of same extension
I was able to install a specific branch while already having the main branch installed. I am unsure of the actual behavior, but expected behavior would be for an error to be thrown "Another branch of this extension already installed" or similar

**Comment by rstoenescu** [comment]
Hi,

The official way to do it is to when you have custom AE package:
1. Manually install the custom App Extension package that you want (even install from git repo directly if you want).
2. Call `$ quasar ext invoke <ext_id>`.

**Comment by BenoitRanque** [comment]
Alright. Will close the issue.
