### ISSUE TITLE
Feature request for QImg: Add the ability to disable the loading spinner animation

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#4912]
**Is your feature request related to a problem? Please describe.**
I want to use QImg for showing a placeholder image until the real image has been downloaded but I don't want to see the spinner animation.  I would like to just see the placeholder image without the spinner animation initially and then the real image gets shown when ready, with or without a transition.

**Describe the solution you'd like**
Maybe something like `loading="false"` or `show-loading="false"` would work, with the default being `true`.

**Describe alternatives you've considered**
I've considered just doing this using img tags or background images and JavaScript, but it would be easier if Quasar supported this 😄

**Comment by rstoenescu** [comment]
Will be available in 1.1.0

**Comment by RohanTalip** [comment]
Awesome, thanks @rstoenescu !
