### ISSUE TITLE
graphql-codegen plugin for quasar

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [quasarframework/quasar#4913]
Hey.
The api standard becomes graphql
And the product https://github.com/hasura/graphql-engine for its generation is very popular.
But schemes need to be turned into client schemes, and it does
https://github.com/dotansimha/graphql-code-generator

For it, plugins are needed, now there is a reaction.

Can the community develop a plugin for quasar, as well as make a “sample” how to use the result with the framework?

https://github.com/dotansimha/graphql-code-generator/issues/1539

**Comment by rstoenescu** [comment]
Hi,

This is what [App Extensions](https://quasar.dev/app-extensions/introduction) are meant for. You can get started by reading the [development guide](https://quasar.dev/app-extensions/development-guide/introduction).

Try use a descriptive name for your app extension, like "graphql-code-generator". Please feel free to use our [Discord](https://chat.quasar.dev) if you get stuck at any point.

Looking forward to see this happening!
-Razvan
