### ISSUE TITLE
QToolbar min-height was overwritten by other style on IE11&Edge

### ISSUE THREAD

**Issue by yuanyesong** [quasarframework/quasar#4914]
overwritten by the style:
`.flex, .row{
     min-height:0%;
} `

Look at [Quasar Docs](https://quasar.dev/start/pick-quasar-flavour)

Screenshot (Edge)
![批注 2019-08-17 222506](https://user-images.githubusercontent.com/7038265/63213375-5c2b8580-c13e-11e9-93a7-e9d6cbc964de.png)

Screenshot (IE11)
![批注 2019-08-17 223203](https://user-images.githubusercontent.com/7038265/63213434-eaa00700-c13e-11e9-881c-ff688f939d9c.png)

Screenshot (√Chrome)
![image](https://user-images.githubusercontent.com/7038265/63213544-4028e380-c140-11e9-9207-23149e0706c3.png)

**Comment by rstoenescu** [comment]
Hi,

This has been fixed already in future v1.1.0.
