### ISSUE TITLE
QPopupEdit: pass positional arguments to QMenu

### ISSUE THREAD

**Issue by gorango** [quasarframework/quasar#4916]
**Is this feature request related to a problem?**
I would like to use `QPopupEdit` outside of just a table context - what makes this difficuly is the lack of control over positional props.

**The solution I'd like**
Pass positional arguments (`cover`, `anchor`, `self`, `offset`) through to the [QMenu which wraps the component](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/popup-edit/QPopupEdit.js#L143-L146).

**Alternatives I've considered**
Currently, I'm using a modified version of the `QPopupEdit` component which wraps `QMenu`.

**Comment by rstoenescu** [comment]
Hi,

Good point.
Will be available in v1.1.0.
