### ISSUE TITLE
Nuxt routing

### ISSUE THREAD

**Issue by mygithubid1** [quasarframework/quasar#4917]
**Is your feature request related to a problem? Please describe.**
Routing inside a quasar app requires defining the routes manually.

**Describe the solution you'd like**
Nuxtjs routes are file based. So, there's no need to explicitly create a router.

**Additional context**
https://github.com/quasarframework/quasar/issues/522

Thanks.

**Comment by lucasfernog** [comment]
This feature request is being discussed on #5378
