### ISSUE TITLE
[v1] QDate - Localization Wrong Week Day

### ISSUE THREAD

**Issue by renanBritz** [quasarframework/quasar#4921]
**Describe the bug**
When localizing the QDate, the days are positioned in the wrong week day column.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/date#Custom-ad-hoc-locale

**To Reproduce**
1. Open documentation link above (Custom ad-hoc locale section)
2. Select current date (e.g August 19).
3. Notice the week day: August 19 should be Monday (Lun), but it displays as Thursday (Jue).

**Expected behavior**
Expected day to be in the correct week day column.

**Screenshots**
![Captura de Tela 2019-08-19 às 10 20 33](https://user-images.githubusercontent.com/5933645/63269105-fb9a6680-c26b-11e9-8abe-4bdbec8a7999.png)

**Platform (please complete the following information):**
All platforms

**Comment by renanBritz** [comment]
Setting first-day-of-week to -3 seems to be a workaround for now.

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this.

You should also set `:first-day-of-week="0"` (or what it needs to be).
Will fix the example and will also introduce firstDayOfWeek for the "locale" property too, since it makes sense and eases the usage.

**Comment by rstoenescu** [comment]
And since I am at it, will also add "format24h" to the locale prop. The two will overwrite first-day-of-week and format24h props IF they are present in the locale too.

**Comment by rstoenescu** [comment]
The reason why things appear broken is that most likely you have the default Quasar lang set (en-us), which has first day of the week set to 1. So what Quasar does is that it uses the locale that you are giving it but since `first-day-of-week` is not present, it takes it from the current Quasar lang, which is 1 instead of 0.

**Comment by renanBritz** [comment]
Thank you

Regards!

**Comment by rstoenescu** [comment]
Wow, I must be really tired. Wanted to implement the functionality right now, but as it turns out, I already did it. What's wrong here is the example in docs only.

Simply add "firstDayOfWeek: 1" in the locale Object. (Sunday - 0, Monday - 1, etc..)
