### ISSUE TITLE
[docs] Deploy Now 2.0

### ISSUE THREAD

**Issue by Ragura** [quasarframework/quasar#4923]
The documentation to deploy an SPA with the `now` command is outdated. It's no longer possible to switch to version 1.0 to deploy a project for "new" users (since the beginning of 2019?).

I'd like to add that I was able to use V2.0 by changing the distPath build option in the quasar config file to "public/". This, on top of adding the `"build": "quasar build"` script in `package.json`, seemed to be all that was needed, but the 404 path no longer works. Additionally, changing the distPath each time we want to deploy with Now is quite annoying, as normally the mode is added to the folder structure.

Any way out of this? If not, perhaps remove or edit the docs to reflect the new reality.

**Comment by dheeraj2dj** [comment]
Am also in need of this. Please prioritise this!

**Comment by rstoenescu** [comment]
Prioritizing this for next week.

**Comment by rstoenescu** [comment]
@Ragura "distPath"?

**Comment by rstoenescu** [comment]
And why adding the "quasar build" script? Are you not cd-ing into the dist folder and deploying from there?

**Comment by dheeraj2dj** [comment]
> @Ragura "distPath"?

may be `distDir`

**Comment by Ragura** [comment]
> And why adding the "quasar build" script? Are you not cd-ing into the dist folder and deploying from there?

There was no reason. I had never worked with Now before, so didn't really know what I was doing. Now I understand that building the project out first would make more sense and keep the folder structure intact (and save time). Still have a lot to learn about deployment. The curse of too much local development in isolation...

Glad you're looking into it!

**Comment by tomers** [comment]
Please review changes in https://github.com/quasarframework/quasar/commit/bc58f9641536ceb9451cfbfc7e72ccfaae8ed02c#diff-9ec38618f7236aa16b08b2bc56073263

I since that the tip added there regarding distDir should resolve this ticket.
I managed to deploy using Now 2.0

P.S in the `now.sh` configuration file I gave as an example, I omitted the `"version": 2` field for brevity. We should consider explicitly writing it.
