### ISSUE TITLE
Virtual option for the table component

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#4924]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Could you please provide the virtual rows feature for data-table? This would allow to display a pretty big amount of data without pagination, like it is in select component https://quasar.dev/vue-components/select#Render-performance 

**Describe alternatives you've considered**
The external plugins such as vue-virtual-scroller are not a very good solution since we must define the whole table's body markup ourselves (if it even work).

**Additional context**
https://github.com/Akryum/vue-virtual-scroller

**Comment by pdanpdan** [comment]
It will be available in the next release (1.1.0) (by wrapping a QMarkupTable).

**Comment by 1001v** [comment]
@pdanpdan i was talking about advanced table.
