### ISSUE TITLE
QSelect empty val in filterfn() when value in updateInputValue() is the same as is in a model

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4926]
QSelect has use-input property and do not use chips. When updateInputValue() is called with the same value as is in a model, then filterFn is fired with incorrect empty val.

How to reproduce the issue
1) click on BAD button
2) observe js console log("filterFn called with val: "), where val value is empty

What is expected behaviour 
1) click on OK button
2) observe correct js console log

Demo
https://jsfiddle.net/w1q5ktu9/3/

Version
v1.0.5

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1
