### ISSUE TITLE
[docs] Don't use yarn to run quasar-cli, instead use node_modules/.bin/quasar directly

### ISSUE THREAD

**Issue by DarrenCook** [quasarframework/quasar#4927]
I'm using yarn, not npm, and chose not to install the quasar cli globally.

I've been running it with e.g. `yarn quasar dev`. However that has a problem, described below, so I'm now always using `node_modules/.bin/quasar dev`

The difference between the two can be seen by trying each of:

```
yarn quasar dev -m electron -- --no-sandbox
node_modules/.bin/quasar dev -m electron -- --no-sandbox
```

The second one works fine, and correctly passes along `--no-sandbox`. But the first one makes the SPA, and doesn't make the Electron app at all. If they look the same, this can be hard to spot! Yarn itself gives a warning about ignoring `--`, but quasar does not give any errors or warnings.

**Comment by hawkeye64** [comment]
1) For your first example, using an argument prefixed with two dashes (`--`) tells `yarn` to pass this in directly to the node instance. Quasar never see it.
2) For the second example, Quasar has no such capability built in to do this. In fact, it can't, as it is already running under the Node instance that would have received the arguments (unless it spawned yet another instance of Node, but that's a whole lot of trouble there already).

You can probably accomplish the same thing yourself by doing this:

```json
  "scripts": {
    "dev": "node --no-sandbox node_modules/.bin/quasar dev -m electron"
}
```

**Comment by pdanpdan** [comment]
If you don't have a very old npm you can also use `npx quasar ...`.
As a rule, `npm/npx` need `--` to separate arguments that should be passed to the command and `yarn` does not need it.
