### ISSUE TITLE
QSlider - access to unstepped value

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#4929]
**Describe the solution you'd like**
I would like to be able to have the value of QSlider update as the slider is moved as if there is no step or snap, but also provide a step and use snap so that when the slider is released it snaps to a step. The purpose is to allow something  else on the page to move in response to the slider drag, but then go back if it did not hit the snap/stepped location. Maybe this would be a new property like `always-update-value` or maybe an event instead. Thoughts?

**Describe alternatives you've considered**
Potentially using no step/snap and manually creating the steps& value snapping using events.

**Comment by pdanpdan** [comment]
You can use it without step, and on value change set it to your desired value (rouded to step)

**Comment by smakinson** [comment]
true, that sounds like a good way to do it manually.
