### ISSUE TITLE
missing fonts in UMD starter kit

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#4934]
```bash
$ quasar create umd --kit umd

  ___                             
 / _ \ _   _  __ _ ___  __ _ _ __ 
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |   
 \__\_\\__,_|\__,_|___/\__,_|_|   
 


? Project name umd
? Author Jeff Galbraith
? Use minified dependencies? (recommended) Yes
? Use RTL support? No
? Choose Icon Library (Use arrow keys)
❯ Material Icons (recommended) 
  Fontawesome 
  Ionicons 
  MDI 
  Eva Icons 
```
Missing in the UMD kit:

> Material Design Outlined
Material Design Round
Material Design Sharp
Themify

Additionally, I could not figure out how to use these fonts from jsdelivr

I tried like this in codepen (css settings):

https://cdn.jsdelivr.net/npm/quasar@v1.0.5/dist/icon-set/material-icons-round.umd.min.js

https://codepen.io/Hawkeye64/pen/NWKbGrg?editors=1010

**Comment by rstoenescu** [comment]
@hawkeye64 , please ping me on Monday for this one. thx!

**Comment by hawkeye64** [comment]
Ahh, didn't see your message until I wanted to reference. Well, hope this is what you wanted: https://github.com/quasarframework/quasar-starter-kit-umd/pull/1

**Comment by rstoenescu** [comment]
Fixed, so closing.
Awesome work, @hawkeye64 !
