### ISSUE TITLE
QPopupEdit: quick edit after open sticks even when cancelled

### ISSUE THREAD

**Issue by oskarmaxa** [quasarframework/quasar#4936]
If text is input immediately after a QPopupEdit is opened, cancelling afterwards doesn't do a full reset, i.e. some of the characters stick. It's as if QPopupEdit sets its internal "initial value" too late.

**Steps to reproduce:**
1. Open a QPopupEdit with a QInput.
2. Input some characters quickly after that.
3. Press Escape.
4. See that not all of the added characters were cancelled.

**Expected behavior:** The model should revert to its original value without any of the added characters.

**Demo:** https://jsfiddle.net/Lrj91bm8/

**Quasar versions:** 1.0.5, 1.1.0

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in v1.1.1
