### ISSUE TITLE
QTaab and QTabPanel should reflect their name as a class

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#4937]
**Is your feature request related to a problem? Please describe.**
When using tabs and tabs panels, you usually also need to reference them into CSS and JS.

**Describe the solution you'd like**
Many other libraries take the provided UUID name and use it to build up a class for styling.
Generating a `q-tab[-panel]--<uuid>` or `q-tab[-panel]__<uuid>` or `q-tab[-panel]-<uuid>` or a similar variant should be easy.

Es.
```html
<q-tab name="pizza"></q-tab>
<q-tab-panel name="pizza"></q-tab-panel>

<!-- Generated as (simplified) -->

<div class="q-tab q-tab-pizza"></div>
<div class="q-tab-panel q-tab-panel-pizza"></div>
```

**Describe alternatives you've considered**
Adding all classes manually.

**Comment by rstoenescu** [comment]
Hi,

99% of the devs don't actually need this. And if they'd need it, it would be simple to just add a class to each tab/tab-panel themselves. Rather than bloating the framework with specificities like this, it is better to keep the footprint low and runtime fast. Sorry for any inconvenience.
