### ISSUE TITLE
QItem allow click when is disabled

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#4938]
**Describe the bug**
QItem with a checkbox/radio/toggle allow to click them when is disabled

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/eduardodgarciac/pen/LYPbOJE?editors=1010

**To Reproduce**
1. Click a disabled QItem

**Expected behavior**
Stop click event

**Comment by pdanpdan** [comment]
Just add disable prop to the QCheckbox/QToggle. There are cases when you want to be able to interact with the content (like showing a QTooltip.

The `disable` prop on QItem just changes the aspect to a disabled state one and prevents router navigation.
