### ISSUE TITLE
enhance mobile browser address bar coloring

### ISSUE THREAD

**Issue by ag-coder** [quasarframework/quasar#494]
Make this optional so every developer can choose to color the addressbar with primary color (default) or another color, or opt out of coloring the address bar

**Comment by rstoenescu** [comment]
New usage:

```js
import { AddressbarColor } from 'quasar'
AddressbarColor.set() // sets primary color
AddressbarColor.set('#b023fe')
```

Addressbar color is only injected if platform supports it.
