### ISSUE TITLE
Tooltip should not show when its text is empty

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#4940]
**Describe the bug**
When the the (computed) tooltip text is empty, the tooltip should not show itself at all.

**Codepen**
https://codepen.io/tomers-the-encoder/pen/zYOoQLP?&editable=true&editors=101

**Expected behavior**
Instead, a weird empty tooltip is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/83443/63497423-634eec80-c4cc-11e9-81e5-594721875aaf.png)

**Comment by tomers** [comment]
I know that I can use `v-if="tooltipText"` to fix this, but I think the framework should support this case.

**Comment by rstoenescu** [comment]
Hi,

I gently disagree with the claim. You as a developer are in control of the tooltip's default slot. From a performance perspective, rather than having the framework check the slot for its content (which would be very costly), it's way better that you put a v-if on it instead.

**Comment by pfuetzma** [comment]
This is not a good solution for dynamic content:
`<q-tooltip v-if="!!getTooltip(a, b)" :delay="1000">
   {{ getTooltip(a, b) }}
 </q-tooltip>`
getTooltip is called twice.

**Comment by rstoenescu** [comment]
@pfuetzma Leaving function calls directly in the template is also not good. But you can use a computed value -> way better for the rendering function itself and also it solves your second issue.

**Comment by pfuetzma** [comment]
The tooltip is in a loop, e.g. a table, and is created from the values of the column and row. How can you use a computed value here?

`interface Column {
  ...
  tooltip?: string | ((row: Row) => string);
  ...
}`

`const getTooltip = (col: Column, row?: Row) => (typeof col.tooltip === "string" ? col.tooltip : col.tooltip?.(row));`
