### ISSUE TITLE
Use Cordova Electron

### ISSUE THREAD

**Issue by dev-steverob** [quasarframework/quasar#4941]
**Is your feature request related to a problem? Please describe.**
The ability to add the Electron platform via Cordova to take advantage of the Cordova plugins which either support electron or browser platforms. This way all apps can use Cordova and associated plugins and also keeps the apps both mobile and desktop together?

**Describe the solution you'd like**
 If I could use `cordova platform add electron` and `quasar dev -m cordova -T electron` etc

https://cordova.apache.org/docs/en/latest/guide/platforms/electron/

**Comment by rstoenescu** [comment]
Hi,

Enabled "electron" as a cordova target (will be available in quasar/app v1.0.7). However:

**Will not work until https://github.com/apache/cordova-electron/pull/81 goes into cordova-electron release (at the time of writing this, it seems to be planned for cordova-electron v1.2).**
