### ISSUE TITLE
[docs] Grid Row "Self Alignment" section appears to contain errors in the sample image.

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#4942]
While trying to align the height of buttons with varying amounts of text in a q-card-section, I came across this issue:

https://quasar.dev/layout/grid/introduction-to-flexbox#Self-Alignment

The following appears to be the correct layout, since Self Alignment is supposed to override the "item-*" attribute.

https://codepen.io/danielfaust/pen/OJLbKjv

**Comment by rstoenescu** [comment]
Hi,

But the image only depicts self-start and self-end.

**Comment by danielfaust** [comment]
Ah, ok. I misunderstood the image. You're right, under my assumption self-baseline would then also be missing.
