### ISSUE TITLE
[docs] Availability of process environment variables

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4943]
When using the Quasar CLI, if I have:

```
data () {
	return {
		process: process,
		env: process.env
	}
},
```

and in the template:

```
{{ process.env.DEV }} / {{ env.DEV }}
```
it ouputs : ` / true` (seen in the browser and in cordova)

So AFAIK it means that `process` or `env` itself is reassigned at some point, and only keeping a direct reference to the `process.env` object at the creation of the component works.

This is the console log of `process` later on when the `env` object is empty:

![image](https://user-images.githubusercontent.com/371814/63509148-b8dec580-c4db-11e9-85ad-419dea051dcd.png)

If it's not a bug I believe it should be documented on this page: https://quasar.dev/quasar-cli/cli-documentation/handling-process-env.

Thank you

**Comment by MartinManev** [comment]
The `process` object is only available in the context of a node.js application. Webpack automatically removes it for you.

For Vue CLI there is some documentation here: https://cli.vuejs.org/guide/mode-and-env.html#modes

> Note that only variables that start with VUE_APP_ will be statically embedded into the client bundle with webpack.DefinePlugin.

How WebPack's DefinePlugin works is explained here: https://webpack.js.org/plugins/define-plugin/

The Quasar CLI works a bit differently than the Vue CLI, but I believe the idea is the same. There is even a section that explains how Webpack strips out code when running in different modes: https://quasar.dev/quasar-cli/cli-documentation/handling-process-env#Stripping-out-code

**Comment by louisameline** [comment]
Thank you for the response. It does work when I reach it the way I explained above with `env: process.env` though. Should I stop doing that and reproduce the same functionality another way? It's handy to have these predefined.

**Comment by MartinManev** [comment]
I don't know about using `process.env` itself. It might not be safe but I can't be sure until I do some more research.

The intended idea is that Webpack will detect and swap any members of `process.env` with their compile-time value. And maybe do some optimization on top, like the code stripping idea. For Vue CLI, only variables starting with `VUE_APP_` will be made available, so `process.env.VUE_APP_MY_VARIABLE` is good, but Quasar CLI doesn't seem to have this limitation.

So if you write `process.env.MODE`, then after compiling, it will become either `spa`, `pwa`, `electron` or whatever else it can be. If you write `process.env.MODE === 'electron'` the whole expression will be swapped with either `true` or `false`.

One possible use for this feature is, as stated, to change the functionality and behavior of your app when running in different modes. So you could add a lot of debug messages and extra pages when compiling for development mode, but strip them entirely in production. And of course, you can define any variable you want in your quasar.conf.js file and use it in your compiled application.

As to wether to use `process.env` itself directly, again, I'm not sure.

**Comment by MartinManev** [comment]
I did a test in Vue CLI. `process.env` can be used directly, but I think Webpack swaps it with an inlined object literal.

Take a look at this:
```
let obj = process.env;
console.log(obj);// Prints the object contents...
console.log(process.env);// Exactly the same as above, no difference
console.log(obj === process.env);// false
console.log(process.env === process.env);// false
console.log(obj === obj);// true
```

**Comment by louisameline** [comment]
I get it thank you, it makes sense. Maybe a note in the docs for people like me who naively think they can manipulate this object like any other would be helpful.

**Comment by nothingismagick** [comment]
Be careful, especially if you are using either of the @quasar/qenv or @quasar/dotenv app extensions in the Quasar CLI (which is what we recommend).

While @MartinManev makes a good point, he is comparing Vue CLI to Quasar CLI. They are very different things.

**Comment by louisameline** [comment]
I realized something today.

When I write
```javascript
console.log(process);
console.log(process.env);
```

For the first command, the console will show an object where `process.env` is empty.
For the second command, the console will show the expected properties of `process.env`.

So I guess `process.env` doesn't get reassigned. It's just a weird object that the console can't let you inspect like a normal object.

So writing
```javascript
data () {
  return { process }
}
```
and then trying to use `process.env` in the template doesn't work. `process` object probably doesn't like being spread into another object or something like that. I do not understand what causes this, but now I know that the env variables are not actually gone, it's just `process` which can't be manipulated as I'd expect.

So I'll keep writing
```javascript
data () {
  return { env: process.env }
}
```
to use it in templates.
