### ISSUE TITLE
[v1] When change QInput rules hope could trigger validate once

### ISSUE THREAD

**Issue by wordgold** [quasarframework/quasar#4945]
Sometimes I need change QInput rules and cant trigger validate method, like this case could QInput trigger validate once by itself

**Comment by wordgold** [comment]
In quasar/ui/src/mixins/validate.js watch part add rules actions.

**Comment by louisameline** [comment]
You might change the rule before the user has done anything, and you wouldn't want to validate at this stage. The question is why can't you trigger the validate method yourself?

**Comment by wordgold** [comment]
Sometimes input in list.
I find another way is wrap input to  a component, trigger resetValidation when the rules changed.
Closed
