### ISSUE TITLE
Color Prop on QPopupEdit doesn't work

### ISSUE THREAD

**Issue by lucklouis** [quasarframework/quasar#4952]
**Describe the bug**
The Color prop doesn't seem to have any effect on QPopupEdit. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luckman88/pen/KKPNEOB).  

**To Reproduce**
Please see code

**Expected behavior**
Expect the background of the QPopupEdit to change to the specified color.

**Platform (please complete the following information):**
Quasar: 1.0
OS: Windows and Mac
Node: 12.8.0
NPM: 6.10.2
Yarn: 1.17.3
Browsers: Chromium (inside Electron app) 
iOS: N/A
Android: N/A
Electron: 5.0.0

**Comment by rstoenescu** [comment]
Hi,

That's what `content-class` is for.
Example: https://codepen.io/rstoenescu/pen/PoYWWRz

**Comment by lucklouis** [comment]
Thanks for the reply!

**Comment by rstoenescu** [comment]
No problem. Glad I could help.
