### ISSUE TITLE
Please upgrade mdi fonts to v4，Thanks very much！

### ISSUE THREAD

**Issue by wordgold** [quasarframework/quasar#4955]
Please upgrade mdi fonts to v4，Thanks very much！

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this!

Released a new version of `@quasar/extras` with latest MDI v4.1.95. quasar.conf.js name for it on the `extras` array is `mdi-v4`.

The mdi-v4 Quasar icon set is going to be available along with Quasar v1.1 release, although it seems that current one (mdi-v3) still works with MDI v4. (Referring to the icon set definitions used by Quasar components, from quasar.conf.js > framework > iconSet)
