### ISSUE TITLE
Build a Quasar project as lib/component

### ISSUE THREAD

**Issue by VasilisNikiforidis** [quasarframework/quasar#4956]
I am currently working on a project created with quasar, and I want to include another project I was working on inside this one, as an external lib or component. (Both project include their respective store, components etc)

My problem is that I can not seem to figure out how to build a quasar project to use as a component, since the cli script `quasar build`, creates a SPA project.

Is there any way to build a quasar project as a standalone component (SFC (?)) to be used in another project, using the quasar cli preferably, or if it is not possible with it, any other way?

**Desired end result** would be the ability to do sth like `import ... from ...`, after installing it either from local folder or from my private gitlab repo, and use my project as a component like with other npm libs etc.

**Comment by rstoenescu** [comment]
Hi,

The purpose of a project folder is not to build a component, but a website/app.

Building a component can be achieved with a relatively small setup of rollup or webpack over your component...
