### ISSUE TITLE
QInput with type number loses reactivity to the model

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4974]
**Describe the bug**

Here, some special characters like `e` or `.` mess with the way Quasar handles its model on QInput with type number. It's hard to explain, you'll understand better when you see it: https://codepen.io/Louis99/pen/MWgpomo?&editable=true&editors=101

and also, it can happen this way too without the special characters:
https://codepen.io/Louis99/pen/yLBMjMq?&editable=true&editors=101

It doesn't seem like much but I believe it's the source of other issues I've had that stem from this, where the reactivity of the component fails.
Any thoughts on this? Thank you

**Comment by rstoenescu** [comment]
Hi Louis,

Please also use the `.number` modifier with v-model, as in: `v-model.number="variable"`. Otherwise it won't interpret that as a number but a String.

**Comment by louisameline** [comment]
Hi Razvan, actually it does not make a difference, it still happens: https://codepen.io/Louis99/pen/MWgpomo?&editable=true&editors=101
In my app I had it already set as well.
Not a major issue though ^^

**Comment by rstoenescu** [comment]
The letter `e` has special meaning for a number. Example: '3.4e5' means 3.4 times ten to the fifth power, which is 340000.

Reopening to revise the algorithm within Quasar and see if it's Quasar at fault. Naturally, the model handling is done by Vue in this case through v-model with its 'number' modifier, but will revise how everything is put together again.

**Comment by louisameline** [comment]
The model is actually fine as shown in my pen, it's the field which does not get updated. Thank you

**Comment by rstoenescu** [comment]
Got it. Will analyze the algorithm behind it. Thank you for the details and for reporting!

**Comment by louisameline** [comment]
You're most welcome, many thanks to you

**Comment by louisameline** [comment]
Actually it's not just about a special character like `e` or `.`, I have setup another Codepen, I updated the first message of this issue with its URL. Thank you

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1
