### ISSUE TITLE
q-input bindet to nested object loses value

### ISSUE THREAD

**Issue by KPKoch** [quasarframework/quasar#4975]
If I use:
<template v-for="(dataitem, datakey) of items" 
<q-input
                  v-model="items[datakey]"
>

I can enter the values and see them in the correct object, but q-input has no value.
It get's 'lost' after entering.

If I instead use some plain variable as v-model everything works as expected.
e.g. <q-input
                  v-model="item"
>
(latest version of quasar, just updated)

**Comment by louisameline** [comment]
Hello, could you please setup a codePen to reproduce the issue please?
If items is an object and has not been made iterable, it might be normal. Use a "for ... in" loop instead

**Comment by rstoenescu** [comment]
Like Louis said, we'd need a codepen in order for us to be able to help you. This certainly isn't a bug in Quasar or Vue, but I think it's a bit of a misunderstand / usage issue.

**Comment by smolinari** [comment]
Works, if you use the `dataitem` broken down via the v-for directive (or in my example the input item of the inputs array). It's basic v-for usage for Vue. 

https://codepen.io/smolinari/pen/pozWJwV?editors=1010

https://vuejs.org/v2/guide/list.html 

Please also use our [Forum](https://forum.quasar.dev) or [Discord server](https://chat.quasar.dev) when you aren't certain you've found a bug or have a direct suggestion for improvement. We'll help you get to either a better understanding or the clear bug description, which you can then enter here.

Thanks for your understanding.

Scott
