### ISSUE TITLE
Access to the ssr variable inside the ssr extension

### ISSUE THREAD

**Issue by dmitry** [quasarframework/quasar#4976]
While sending the `POST` request on specific `URI` I'd like to be able to render application via ssr extension (so it work in both: webpack-dev-server and ssr build).

At the moment extension only receives `app`, while it might receive both `app` and `ssr` to be able to `renderToString` the application contents even while the `POST` method received by the server.

Solution is to provide `ssr` for the `webpack-dev-server` and build server.

Then it could be used in the extension the following way:

```javascript
module.exports.extendApp = function ({ app, ssr }) {
app.post('/signup', (req, res) => {
  res.setHeader('Content-Type', 'text/html')

  ssr.renderToString({ req, res }, (err, html) => {
    if (err) {
      res.status(500).send('500 | Internal Server Error')
    }
    else {
      res.send(html)
    }
  })
}
}
```

One of the workarounds for the moment might be to store the data in the cookies and point redirect to the `GET` where using the quasar `Cookies.get` tool it might be passed to the form.

Required changes:

- webpack-dev-server: https://github.com/quasarframework/quasar/blob/6d1f3e2143831267291fb593806d6d4fc18f48ad/app/lib/dev-server.js#L257
- ssr build template: https://github.com/quasarframework/quasar/blob/56cd7fb09afe0cfb2389ab4b5065c90ab21d4068/app/templates/ssr/index.js#L40
- some docs have mentions to the `extendApp`

**Comment by rstoenescu** [comment]
This is a nice addition. Thanks for reporting on it.
Will be available in quasar/app 1.0.6.
