### ISSUE TITLE
[Request] Stationary Header for Lists

### ISSUE THREAD

**Issue by rkedward** [quasarframework/quasar#498]
I am really enjoying using quasar framework.  It would great if lists had an option to add a stationary  header that stayed fixed during scrolling.  I nice option is if the header retracts when the user scrolls up and appears when when the user scrolls down.

**Comment by rstoenescu** [comment]
This should be implemented in app-space. There's no golden design for this to fit any scenario possible. Every developer should write this functionality to best suite his/her needs...
