### ISSUE TITLE
QSlider label text color on dark background with white label

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#4980]
**Describe the bug**
Unless I am missing it, we are unable to set the labels text color on a slider without overriding quasar styles and if I have a white slider with a white label, the label text is also white and not readable.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/smakinson/pen/oNvWejR

**To Reproduce**
1. Go to https://codepen.io/smakinson/pen/oNvWejR
2. Drag the slider
3. Notice the labels text is not readable when the label is white.

**Expected behavior**
I would be able to set the label text color to allow it to show  or it would happen because of the `dark` prop.

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi @smakinson ,

Thanks for reporting this. It will be available shortly in v1.1.0 through new `label-text-color` prop for QSlider.

**Comment by rstoenescu** [comment]
v1.1.0 is released
