### ISSUE TITLE
Missing type property validation for QVirtualScroll component

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#4983]
**Describe the bug**
QVirtualScroll component allows to pass any string value as type

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/1001v/pen/eYOWxWq?editors=1011

**To Reproduce**
1. Pass the wrong value to type property
2. See that there's no prop validation error

**Expected behavior**
Expected validation to work

**Platform (please complete the following information):**
Any

**Additional context**
Missing ```.includes(v)``` on 18 line: https://github.com/quasarframework/quasar/blob/dev/ui/src/components/virtual-scroll/QVirtualScroll.js

**Comment by rstoenescu** [comment]
Hi @1001v 

Thanks for reporting! Will be fixed in v1.1.1
