### ISSUE TITLE
QLayout is not mandatory,so can i use other UI frameworks  like element-ui in Quasar?

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#4985]

**Comment by hugetiny** [comment]
I imported element-ui in App.vue
but got this
```
[Vue warn]: Unknown custom element: <el-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <MoMain> at src/components/Main.vue
       <App> at src/App.vue
         <Root>
```

**Comment by rstoenescu** [comment]
Hi,

We'd rather have questions in our [Discord](https://chat.quasar.dev) or [Forum](https://forum.quasar.dev).

But to answer your question: yes. But if not using QLayout, then it also means not using QHeader/QFooter/QDrawer/QPage/QPageSticky/QPageScroller. All other components do not depend on QLayout.

**Comment by hugetiny** [comment]
@rstoenescu  Thank you
