### ISSUE TITLE
[Feature Request]More Capacitor Intergration

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#4988]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think the most improved parts from Cordova to Capacitor is Unified API and editable iOS/Android native projects.
Capacitor includes a number of Native APIs that are available to all Capacitor apps. These can be thought of as Capacitor "core plugins," and they make it easy to access commonly needed functionality on each platform.

Quasar provides a Unified UI for different platforms, but not with Unified (native) API,
If Quasar provides Quasar's Unified (native) API would be a great feature.

**Describe alternatives you've considered**
Quasar support Capacitor's Unified API on PWA/web, electron, ios, android(Capacitor supported platforms)

**Comment by hugetiny** [comment]
Plugins like @quasar/universal-fslaunch wrap the filesystem interface for web, Cordova and electron with one abstraction is great.
I think we would like to  wrap **more** for web, cordova and electron with one abstraction

**Comment by rstoenescu** [comment]
More abstraction will come as our time & human resources allow.
Everyone reading this, kindly please help with [donations](https://donate.quasar.dev)...
