### ISSUE TITLE
[Request] Multi select for list elements with action bar

### ISSUE THREAD

**Issue by rkedward** [quasarframework/quasar#499]
It would be great if the list component allowed multi list element selections.  In some apps that I use, when the list is long pressed, check boxes on the left appear in each list element with an action bar  to perform some action on the selected elements.  Having this feature would allow batch processing of selected list items.

**Comment by rstoenescu** [comment]
This sounds like something very specific. And it can be done without bloating Quasar with it. This would rely heavily on app-code specificities so it's not a good idea to embed it in the framework. Sorry.
