### ISSUE TITLE
QVirtualScroll with grid based system (row - col)

### ISSUE THREAD

**Issue by ewol123** [quasarframework/quasar#4990]
**Is your feature request related to a problem? Please describe.**
  QVirtualScroll can only be used with one item per row.

**Describe the solution you'd like**
It would be awesome If I could use QVirtualScroll with a grid based system, not with lists, for example with multiple QCards / row.  I forked the repo and tried to implement it myself with some luck, but I still have issues with the indexing. I recalculated the padding values and when the next batch of items should appear based on how many cards are on a single row, taking into account different screen sizes so it can be responsive, but my data is rendered incorrectly on the cards for some reason. I guess it's because the indexing, but I might be wrong.

I can prepare a public repository with the changes I made so far if necassary. 

**Describe alternatives you've considered**
Add DOM recycling to QInfiniteScroll, with that I can use a grid based system, but If I load a lot of QCards the performance gets really bad.

Any other suggestions are welcome.

**Comment by pdanpdan** [comment]
If you want to use QVirtualScroll with multiple elements on row try to use the `:items-fn` form, provide the number of rows as the `items-size` and for each row generate the content you need.

Something like this: https://codepen.io/pdanpdan/pen/MWgEaMy?editors=1010
