### ISSUE TITLE
Loading plugin - possible race condition?

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#4992]
Hello!

In my scenario I need to show/hide loading overlay several times in a sync manner:
show 1
doSmth
hide1
...
show 2
doSmth
hide 2

In this case I'm experiencing a what looks like a race condition. Seems like first loading overlay is hidden with a delay, which results in a second loading overlay not being shown.

Example:
https://codepen.io/jean-moldovan/pen/rNBwdXG?editors=1011

![loading](https://user-images.githubusercontent.com/3635352/63945252-a801f700-ca7b-11e9-93f1-56c69cdc4d1c.gif)

**Comment by rstoenescu** [comment]
Thank you for reporting!
Fix will be available in 1.1.1
