### ISSUE TITLE
iOS: QDialog with inputs covered by keyboard causes screen to shift

### ISSUE THREAD

**Issue by wooliet** [quasarframework/quasar#4993]
**Describe the bug**
When using a native iOS build:
* If there is an input contained by a dialog, and
* The phone's keyboard hides (partially or completely) the input, then

Any key event in the input causes the entire screen to rapidly shift up (to try and display the input) and then immediately back down (to its original position).

**To Reproduce**

On native iOS build of a Quasar app:
1. Create a QDialog with a list of inputs
1. Click on the last input
1. Start typing

I believe the main precondition is that the input is in some way covered by the native keyboard.

**Expected behavior**

After a text input receives focus, and while typing input:
1. The input remains visible
1. The screen remains stationary

**Screenshots**

In this screen capture, I open a dialog, scroll to the input labelled "Registration number", and type four characters. Each time I type a character, the screen shifts up to show the input, and then immediately shifts back down.

![dialog-input-shift-defect](https://user-images.githubusercontent.com/1421908/63975291-4be7a480-ca74-11e9-9fb1-835634a01d6a.gif)

**Platform (please complete the following information):**
OS: 10.14.6
Node: 8.16
NPM: 6.11
Yarn: n/a
Browsers: n/a
iOS: 12.4
Android: n/a
Electron: n/a

**Additional context**

Build mode........ cordova
Pkg quasar........ v1.1.0
Pkg @quasar/app... v1.0.5
cordova - 9.0.0 (cordova-lib@9.0.1)

This exact defect does not exist in the web version. However, the input (when covered by the keyboard), is completely inaccessible. I could not use my password manager to paste the text into an input due to this behavior.

This issue was not observable in the previous Quasar version.

**Comment by rstoenescu** [comment]
Hi,

Due to UIWebView on iOS this is not fixable. We highly recommend installing the ionic wkwebview: https://quasar.dev/quasar-cli/developing-cordova-apps/preparation#Option-1%3A-Ionic-Webview-Plugin
It makes a huge difference.

**Comment by wooliet** [comment]
Thanks for the suggestion @rstoenescu . [Last time we tried using iconic webview we ran into a bunch of problems.](https://github.com/quasarframework/quasar/issues/4337#issuecomment-505195420). We will consider giving it another shot though.

**Comment by rstoenescu** [comment]
There was a lot of work done for iOS in v1.1 and it works wonderfully with the ionic webview.
