### ISSUE TITLE
ssr pwa workboxPluginMode: 'InjectManifest' breaks build

### ISSUE THREAD

**Issue by MitchellMonaghan** [quasarframework/quasar#4998]
Attempted to add custom-service-worker for push notifications. Everything seems to work in pwa mode but when I use ssr pwa the build fails to complete and gets stuck.

```
Client ████████████████████████  emitting [95%] InjectManifest
 Server █████████████████████████ [100%] in ~400ms
```

**Platform (please complete the following information):**
OS: Windows 10
Node: v10.15.1
NPM: 6.4.1
Yarn: 1.7.0
Browsers: Chrome

Using quasar 1.1.0 that was just released.
"quasar": "^1.1.0",

**Comment by rstoenescu** [comment]
Hi,

It seems that the [Workbox Webpack Plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) silently fails if the workbox options (quasar.conf.js > pwa > workboxOptions) are not appropriate for the InjectManifest. This is outside of Quasar's reach.

So please revise them against the [official list](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_injectmanifest_config).

Will improve Quasar's docs over this, so thank you for reporting!

**Comment by MitchellMonaghan** [comment]
Hi Razvan,

I saw your commit here (https://github.com/quasarframework/quasar/commit/5b344d55f346869eff593dcedd4f6f4e986ca757), but I'm still confused. The only required workboxOption I see in the documentation is the swSrc and I still seem to have the issue when I populate that.

```
workboxPluginMode: 'InjectManifest',
workboxOptions: {
  swSrc: 'src/src-pwa/custom-service-worker.js'
}
```

I also tried moving the service worker to just the src directory and still had the same issue.

It seems if I now use the workboxOptions it now no longer builds for ssr or pwa modes when previously it worked for pwa. Maybe I'm missing something.

Thanks,
Mitch

**Comment by rstoenescu** [comment]
You can comment out the swSrc (that is getting filled out by Quasar automatically). It should then work.

**Comment by MitchellMonaghan** [comment]
Removing swSrc fixes it for pwa mode but ssr mode still has the build getting stuck issue.

**Comment by rstoenescu** [comment]
Confirmed.

Fix for this will be available in quasar/app 1.0.6.
Thank you for the feedback and helping me bulletproof this!

**Comment by MitchellMonaghan** [comment]
Tested your change locally and everything is working now with ssr mode :). Looking forward to quasar/app 1.0.6.

Thanks!

**Comment by rstoenescu** [comment]
It will be released shortly (tomorrow or the day after tomorrow).
Thanks for also testing.
