### ISSUE TITLE
QExpansionItem fails draw subitems when @input is set

### ISSUE THREAD

**Issue by Maksio** [quasarframework/quasar#5001]
I've updated Quasar to 1.1.0 and my drawer menu get broken... After some tests I determine that problem is in @input event handler. When I set it QExpansionItem does not show me expansion area.

**Comment by pdanpdan** [comment]
Please provide a codepen showing the problem.

**Comment by pdanpdan** [comment]
Maybe you need to add a `@input.stop` on the element inside the QExpansionItem, but my crystal ball is not working as well as it used to :).

Please reopen with a codepen showing the problem.

Thank you.
