### ISSUE TITLE
slide transition of tabs lagging with QVirtualScroll in tab

### ISSUE THREAD

**Issue by aprixon01112017** [quasarframework/quasar#5002]
Dev mode.......... spa
    Pkg quasar........ v1.1.0
    Pkg @quasar/app... v1.0.5

I am trying out the basic example https://quasar.dev/vue-components/virtual-scroll#Basic

in tabs with a virtual scroll in one tab. When the tab with the virtual scroll is sliding in, the rendering of the scroll creates lagging of the slide process.

Perhaps wait with rendering elements until slide process is completed?!

**Comment by pdanpdan** [comment]
The QVirtualScroll cannot know that it's container is animating. Just add a v-if in the user-land code to delay showing the list.

**Comment by pdanpdan** [comment]
This is an example on how you can delay the QVirtualScroll display:
https://codepen.io/pdanpdan/pen/zYOEaXV?editors=1010
