### ISSUE TITLE
QSelect width collapses when into flex row container and unknown other causes

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#5004]
**Describe the bug**
As per title, QSelect width collapses, instead of showing label or selected value, when it's container has display flex with direction row AND some other causes I cannot replicate into a JSFiddle. But the behaviour is reproducible in the Design Overview Docs example for QSelect, using DevTools.

**Codepen/jsFiddle/Codesandbox (required)**
Tryed to recreate my scenario, but could not reproduce in JSFiddle.
https://jsfiddle.net/ws0nr83h/6/

**To Reproduce**
1. Go to [Docs Design Overview](https://quasar.dev/vue-components/select#Example--Design-Overview) example
2. Add `row` class to the select components container
3. See error

**Expected behavior**
Should expand to the label length (or option with maximum length?)

**Screenshots**
![image](https://user-images.githubusercontent.com/10036108/64040854-3c448a80-cb5e-11e9-80e0-1a067ed0e83e.png)
---
![image](https://user-images.githubusercontent.com/10036108/64040800-20d97f80-cb5e-11e9-8681-02556141680d.png)
---
![image](https://user-images.githubusercontent.com/10036108/64040068-6f861a00-cb5c-11e9-889a-a667657a37e2.png)

**Platform (please complete the following information):**
OS: W10
Node: 10.x
NPM: 6.4.1
Yarn: 1.16
Browsers: Chrome, others not tested
iOS: Not tested
Android: Not tested
Electron: Not tested

**Additional context**

**Comment by pdanpdan** [comment]
If it has no content then it collapses to the minimum size. Provide it with a minimum required width, or set a `col-xxx` class to the field components.

**Comment by natxocc** [comment]
How can we avoid go to minimum size?
Why for q-input it's not the case and for q-select yes?

I tried to create a flex with differents q-input q-select and happen same to IICalIo

```
<div class="col-xs-12 col-sm-6 col-md-4 q-gutter-xs row">
  <template v-for="(val, ind) in columnDefs" :key="ind">
    <q-input v-if="val.type == 'text'" :label="val.field" v-model="editData[val.field]" />
    <q-input v-if="val.type == 'number'" :label="val.field" v-model="editData[val.field]" type="number" />
     <q-select v-if="val.type == 'select'" :label="val.field" v-model="editData[val.field]" :options="val.values" />
  </template>
</div>
```
![image](https://user-images.githubusercontent.com/1172351/137349777-b526dd41-6c21-41b7-b52d-ddfb075d1c05.png)

It's a responsive system so I can't not put minim width. How I need to do to have a responsive with q-input and q-select with same size?

**Comment by rstoenescu** [comment]
Use col-* classes on your QInput and QSelect. You already have "row" class on the container

**Comment by pdanpdan** [comment]
To clarify:
- QInput always has a native input inside it, and in all browsers that input has a default min-width, so the minimum width of empty QInput is that of the input inside
- QSelect most often does not have an input inside it, so the minimum width of QSelect with nothing selected is very small

**Comment by natxocc** [comment]
Yes, it works perfectly!!!

I change code to (as you recomended):


```
<div class="row">
  <template v-for="(val, ind) in columnDefs" :key="ind">
    <q-input class="col-xs-12 col-sm-6 col-md-4 q-gutter-xs" v-if="val.type == 'text'" :label="val.field" v-model="editData[val.field]" />
    <q-input class="col-xs-12 col-sm-6 col-md-4 q-gutter-xs" v-if="val.type == 'number'" :label="val.field" v-model="editData[val.field]" type="number" />
     <q-select class="col-xs-12 col-sm-6 col-md-4 q-gutter-xs" v-if="val.type == 'select'" :label="val.field" v-model="editData[val.field]" :options="val.values" />
  </template>
</div>
```

Thanks for your great work and help!!!!!!!

**Comment by pdanpdan** [comment]
drop all the `q-gutter...` on QInput and QSelect - they are of no use, you don't have flex children of them to space them.

**Comment by natxocc** [comment]
Thanks for the recomendation!
