### ISSUE TITLE
[docs] Remove `round` prop from `QBtnDropdown` API

### ISSUE THREAD

**Issue by zv3** [quasarframework/quasar#5005]
The `round` prop in the `QBtnDropdown` API no longer works and it appears to have been intentionally removed (commit 2ceb978ff4360eec7cb6f98f50d7cc7505f0d2ff) but the documentation still lists it as prop that can be set.

**Comment by rstoenescu** [comment]
Fix will get into v1.1.1

**Comment by rstoenescu** [comment]
Thanks for reporting!
