### ISSUE TITLE
While SSR mode pass to the boot files the redirect function

### ISSUE THREAD

**Issue by dmitry** [quasarframework/quasar#5010]
Working on integration of vue apollo on SSR mode. Need to control user authentication errors, in case when there are unauthenticated code returned by one of the GraphQL queries I need to redirect user to the login page. 

**TL;DR** Solution is to add `redirect` to the `bootFiles[i]`, like:

```javascript
        await bootFiles[i]({
          app,
          router,
          store,
          Vue,
          redirect,
          ssrContext: context
        })
```

Currently it's only allowed in `preFetch` function of the Vue component, like:

```
        c.preFetch({
          store,
          ssrContext: context,
          currentRoute: router.currentRoute,
          redirect
        })
```

But I need to receive this possibility inside the boot files, while I'm initializing the apollo client:

```
        await bootFiles[i]({
          app,
          router,
          store,
          Vue,
          ssrContext: context
        })
```

To accomplish that, it's required to receive `redirect` function which raises `reject` to the express HTTP server:

```
      let routeUnchanged = true
      const redirect = url => {
        routeUnchanged = false
        reject({ url })
      }
```

So the browser could redirect as of:

```
  ssr.renderToString({ req, res }, (err, html) => {
    if (err) {
      if (err.url) {
        res.redirect(err.url)
```

On the client I could do the:

```
                    router.push({
                      name: 'login',
                      query: {
                        redirect: router.currentRoute.fullPath
                      }
                    });
```

But on the server side (while `process.env.SERVER`) I need to do the following:

```
redirect(router.currentRoute.fullPath)
```

Hopefully that's enough for rationale of this feature to be added to the plugins.

**Comment by rstoenescu** [comment]
Hi,

This is already available, although in another form. The boot files can be async, which means you can return a Promise, and if the promise fails with an Object of form `{ url: '...' }`, then it redirects the user.

Examples:

```js
export default () => {
  // ....
  if (/* something something not authorized */) {
    return Promise.reject({ url: '/sign-in' })
  }
}
```

```js
export default () => {
  return new Promise((resolve, reject) => {
    // ...
    if (/* something something not authorized */) {
      reject({ url: '/sign-in' })
    }
  })
}
```

Seems like I missed this in docs, so will add it.

**Comment by dmitry** [comment]
@rstoenescu thank you so much for the quick response!

**Comment by rstoenescu** [comment]
Added "urlPath" prop (String) and "redirect" method for convenience, in **quasar/app v1.0.7**. (**So this is not available yet, but writing here for completeness**).

And a new section on the boot files doc page:

### Redirecting to another page

```js
export default ({ urlPath, redirect }) => {
  // ...
  const isAuthorized = // ...
  if (!isAuthorized && !urlPath.startsWith('/login')) {
    redirect('/login')
    return
  }
  // ...
}
```

As it was mentioned in the previous sections, the default export of a boot file can return a Promise. If this Promise gets rejected with an Object that contains a "url" property, then Quasar CLI will redirect the user to that URL:

```js
export default ({ urlPath }) => {
  return new Promise((resolve, reject) => {
    // ...
    const isAuthorized = // ...
    if (!isAuthorized && !urlPath.startsWith('/login')) {
      reject({ url: '/login' })
      return
    }
    // ...
  })
}
```

Or a simpler equivalent:

```js
export default () => {
  // ...
  const isAuthorized = // ...
    if (!isAuthorized && !urlPath.startsWith('/login')) {
    return Promise.reject({ url: '/login' })
  }
  // ...
}
```

**Comment by dmitry** [comment]
Awesome @rstoenescu!
