### ISSUE TITLE
Tap delay in chrome mobile

### ISSUE THREAD

**Issue by syonip** [quasarframework/quasar#5015]
**Describe the bug**
There seems to be a tap delay when using chrome mobile. I noticed this at first in a cordova app on android, but chrome mobile (without cordova) behaves the same.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/button

**To Reproduce**
1. Go to https://quasar.dev/vue-components/button from Chrome on an Android device
2. Tap any button
3. Experience the tap delay

**Expected behavior**
Should behave like here: https://vuetifyjs.com/en/components/buttons#buttons

**Screenshots**
https://www.youtube.com/watch?v=36ywg1b57nU

**Platform (please complete the following information):**
OS: Android 9
Browsers: Chrome (76.0.3809.111)

**Additional context**
I don't think this is related to fastclick, as it should not be an issue with new Chrome versions.

**Comment by pdanpdan** [comment]
Quasar starts the ripple when on touchend/mouseup/keyup. This might look like a delay.

**Comment by syonip** [comment]
By the way, on iOS Safari there is no delay.

**Comment by pdanpdan** [comment]
As far as I remember on iOS there is no ripple.

**Comment by syonip** [comment]
@pdanpdan I'm seeing the same ripples happening on my iphone (ios 12) as in android.

Correcting my previous comment, I think there's the same delay on mobile Safari when testing on quasar's demo page, but no delay in a new ios cordova app I just made.

But in android it's the same behaviour in both cordova android and mobile chrome.

**Comment by pdanpdan** [comment]
Can you please make a test and see if this improves things for you - add these in a boot file (and add the boot file to quasar conf) or try to add it on top of App.vue if it's simpler (just for testing):

```javascript
import FastClick from '@quasar/fastclick'
FastClick()
```

**Comment by syonip** [comment]
Sure, just tested by adding those two lines in `App.vue` :
``` 
import FastClick from '@quasar/fastclick'
FastClick()

export default {
  name: "App",
  ...
```

Still the same delay.

I'm testing on an android device with `quasar dev -m android`

**Comment by rstoenescu** [comment]
@syonip Are you referring to the ripple itself or to the button action? The button action works without any delay (that may be due to the 300ms browser delay, because that's no longer a problem in chrome browsers). But if it's due to ripple not triggering immediately on touchstart or mousedown, then this is by design. And more information on this can be found here: https://github.com/quasarframework/quasar/issues/878 

Please reopen if I am missing something here.

**Comment by syonip** [comment]
@rstoenescu Thanks for looking into this.
I think that even if it's only the ripple effect, it's still quite detrimental to the user experience.
Especially in a cordova app, the response should be native-like.

#878 seems to be addressing an edge-case of tapping and moving, but I don't think it's a good trade-off to add a delay to all taps just to address an edge case.

Have you tried tapping on vuetify's buttons from an android device? Is there a downside to making the ripple behave like that? https://vuetifyjs.com/en/components/buttons#buttons

**Comment by syonip** [comment]
By the way, native android apps do show the ripple when tapping and moving. I recorded an example :)
https://youtu.be/LPwg9iuQQis

**Comment by rstoenescu** [comment]
Yes, it has a downside. The behavior you've seen elsewhere requires [a lot more event listeners](https://github.com/material-components/material-components-web/blob/master/packages/mdc-ripple/foundation.ts#L49-L50) and state management (event to start and corresponding event to stop must be in sync; furthermore, there's touchstart being called then mousedown also -- on mobile too! -- so additional logic to not overlap these two event listeners). State management is the most costly of all. And all this adds up when you use it on a page on a lot of elements (and there's high chances of this happening). The perf downside is quite noticeable. The ripple's runtime logic should be as fast as possible. Moreover, the philosophy with ripples in Quasar is a little different: we want to show the user when it has successfully triggered an action, not before the action is triggered or the user tried to do something else (like scrolling the page).

**Comment by syonip** [comment]
I understand. I guess it's more complicated than it seems.

So to summarise my thoughts on this: currently quasar cordova apps have what is experienced as a tap delay, even if it's not really that. I think Quasar is awesome, but this is quite a deal-breaker when choosing a mobile UI framework, at least for me.

Of course, you can decide if this is a bug or a feature :)

Thanks again for looking into this.
