### ISSUE TITLE
Browser freeze on QDialog open

### ISSUE THREAD

**Issue by vuras** [quasarframework/quasar#5022]
After upgrading to Quasar 1.1 from 1.0.5 I stumbled upon a critical issue to my application. Browser tab freezes when I click on a button which is opening QDialog

Usage sample:
https://codepen.io/vuras/pen/ExYwLpQ

**Comment by pdanpdan** [comment]
Is this codepen working for you?

**Comment by vuras** [comment]
Sorry, it is not working, I just pasted the code sample to be more readable.

**Comment by rstoenescu** [comment]
Please help us understand your scenario by updating the codepen to a working one. Thank you.

**Comment by pdanpdan** [comment]
Do you have errors in the console? What is your component doing? Try to make a codepen that works and shows the problem.

**Comment by vuras** [comment]
No errors in the console, it just freezes on the button click and does nothing until the browser times it out.

**Comment by pdanpdan** [comment]
Try to replace your component with something simple (a div with text) and start from there.

**Comment by vuras** [comment]
Looks like i found out the problem. It was a bug in my code. QDialog was wrapped inside the QTable row and after pressing the button it was making an axios request for every row in the table before opening a dialog. I moved it outside the table and it works now correctly, but I guess something changed somewhere because it was working on older version of Quasar.
