### ISSUE TITLE
Problem: Assets resources 404 NOT FOUND (“Pkq quasar = v.1.1.0; Pkg @ quasar / app = v1.0.5”))

### ISSUE THREAD

**Issue by 9223000** [quasarframework/quasar#5031]
After upgrading to v.1.1.0, when starting project as command “quasar dev”, assets resources were no longer available.

For example:
http://localhost:8080/assets/logo.svg

Result:
Cannot GET /assets/logo.svg
Status Code: 404 Not Found

On quasar version 1.0.5, everything worked great!
-----
Dev mode = spa
OS: Windows

The problem only appeared when upgrading to “Pkq quasar = v.1.1.0; Pkg @ quasar / app = v1.0.5”

On the version “Pkq quasar = v.1.0.5; Pkg @ quasar / app = v1.0.4” everything works fine!

If the resources are moved to the statics folder, then the request will succeed.
http: // localhost: 8080 / statics / logo.svg

but the request to assets on the version “Pkq quasar = v.1.1.0; Pkg @ quasar / app = v1.0.5” is not successful:

http: // localhost: 8080 / assets / logo.svg
Cannot GET /assets/logo.svg
Status Code: 404 Not Found

I did a simple experiment:

created a clean project using “quasar create” on the version of “Pkq quasar = v.1.1.0; Pkg @ quasar / app = v1.0.5”
put the file “test.png” in the “assets” folder
Launched the quasar dev project
The project with the main page started successfully
fulfilled the request in the browser “http: // localhost: 8080 / assets / test.png”
Result:
Cannot GET /assets/test.png
Status Code: 404 Not Found

**Comment by rstoenescu** [comment]
Hi,

If it worked before, it doesn't mean it was working correctly :) Let me explain: "assets" folder purpose is for it to be linked/resolved by webpack, while "statics" is to be served as-is. More info: https://quasar.dev/quasar-cli/cli-documentation/handling-assets

Being able to serve /assets "as-is" while quasar dev-ing in previous quasar/app version was a side-effect of an underlying bug. This could fool you into thinking /assets will work on production too, which is not the case.

Please spend some time on the doc page that I indicated above to understand the difference between the two ("assets" vs "statics").
