### ISSUE TITLE
https://quasar.dev/ not working for a few days now

### ISSUE THREAD

**Issue by Tonvdpol** [quasarframework/quasar#5036]
Hi guys,

Are you aware that the website is https://quasar.dev/ is down for a few days now?

Ton

**Comment by rstoenescu** [comment]
Hi,

If the website would have been down we'd know from the first minute. The uptime is 99.99%.
Are you aware of this? https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain

**Comment by Tonvdpol** [comment]
Ok. The weird thing is that I only have a problem with quasar.dev. Other .dev-domains are working fine.

**Comment by rstoenescu** [comment]
You can use this to verify: https://www.uptrends.com/tools/uptime

It must be some setting specific to your machine. Would love to know what it is when you figure it out.

**Comment by Tonvdpol** [comment]
I got the cause. My provider offers a setting to block sites they consider to provide malware. When I enable that option, I cannot connect to quasar.dev. When I disable the option I can connect.

Looks like quasar.dev is on their blocklist.

**Comment by rstoenescu** [comment]
Wow... speechless... What is your provider? I'd like to contact it.

**Comment by Tonvdpol** [comment]
This morning I switched the filter on again and now quasar.dev is still working. Maybe it is not on the list anymore. Anyway, my provider is [www.xs4all.nl](https://www.xs4all.nl). A Dutch company.

**Comment by Tonvdpol** [comment]
And again I cannot. So the filter is still blocking. You might want to check it out with them.
