### ISSUE TITLE
[QSelect] The dropdown did'nt open on focus event

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#5037]
**Describe the bug**
When a user press `Tab` to switch from a field to another, the select don't open his dropdown when he receive the focus

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/select#Design

**To Reproduce**
1. Go to https://quasar.dev/vue-components/select#Design
2. Click on the first QSelect with `Standard` label
3. Press `Tab`
4. The next `QSelect` visually get the focus but didn't open his dropdown

**Expected behavior**
Typically, when user type inside a form, he move from a field to another using `Tab` button.
When the user focus a `Select`, he navigate between the options using keyboard, then press `Tab` again to switch to the next field, etc... #3635 was supposed to fix this feature.

**Additional context**
Thanks for you great job !

**Comment by pdanpdan** [comment]
You must open the list by pressing ENTER or KEY DOWN.
This is the expected behaviour and is consistent with how the navide select element works in browsers (focus does not mean action - check here: http://nativeformelements.com/).

**Comment by MrugankDeshingkar** [comment]
@DaedalusDev [this ](https://github.com/quasarframework/quasar/discussions/12628)link can be helpful. 
its a workaround with @filter method.
Hope this is helpful. 
thanks
