### ISSUE TITLE
Qselect multiple clear selection.

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#5041]
**Describe the bug**
Refering issues #5038,  #4600 and #4732. When selecting multiple items in a `q-select` , after selecting an item , there is no way for the user to clear the input value. While the reasoning behind having this behaviour makes sense , ultimately it should be the app developer who should be able to override this behaviour (  through a property like 'hide-selected' ).
Framework designers shouldn't limit an app developers use-case. Please make the `hide-selected` property available in case of `multiple`

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/rachitpant/pen/mdbpvda

**To Reproduce**
1. In the above code pen , type App and select Apple , app remains in the input box. 

**Expected behavior**
The app developer should be able to override this behaviour thorugh `hide-selected`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1474415/64445159-cd0def80-d0a3-11e9-9978-fa8a84de947e.png)

**Additional context**
I appreciate the framework developers idea that the user can / and should be able to select Apple1 , Apple2 and so on , after typing App . However there is no reason why the app developer should not be able to override it through `hide-selected` property. Also the hide-selected property is exactly for this purpose , **_developer should be able to use this in all cases , without having to use any callbacks or methods to clear input._**

**Comment by rachitpant** [comment]
@rstoenescu

**Comment by rstoenescu** [comment]
Hi,

I've already answered your question in #4732 . You are confusing what "hide-selected" does.
