### ISSUE TITLE
Virtual scroll (type table): show padding height 0

### ISSUE THREAD

**Issue by jesusvilla** [quasarframework/quasar#5042]
**Describe the bug**
In QVirtualScroll, the self-generated tbody to perform the calculation of the remaining height (`.q-virtual-scroll__padding`) at the beginning and at the end (when the height is zero) is displayed due to the padding generated by `.q-table tbody td`.

**Fixed**
Adding in the file from line 16 as a child of `&__padding` [virtual-scroll.styl](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/virtual-scroll/virtual-scroll.styl#L16)

```stylus
.q-table &
            td
                padding 0
```

**Comment by pdanpdan** [comment]
Good catch. Can you please make a PR to fix it? Thank you.

**Comment by jesusvilla** [comment]
Ok, thanks.

**Comment by jesusvilla** [comment]
#5044 Ready

**Comment by rstoenescu** [comment]
Merged. Thank you!
This will go into v1.1.1.
