### ISSUE TITLE
Q-Input clearable doesn't work with readonly

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#5043]
**Describe the bug**
If you keep a `q-input` field readonly ( because you dont want the user typing there ) , the field cannot be cleared by adding a clearable property.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/rachitpant/pen/zYOpbaV

**To Reproduce**
Select a date and time , the clear tip does not appear.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1474415/64451167-a060d480-d0b1-11e9-80fc-3aa49425c3ce.png)

**Code for the screenshot above**
```
<q-input
      readonly
      v-model="sentDate"
      label='Time'
      clearable
    >
      <template v-slot:append>
        <q-icon
          name="access_time"
          class="cursor-pointer"
        >
          <q-popup-proxy
            transition-show="scale"
            transition-hide="scale"
          >
            <q-time
              v-model="sentDate"
              mask="YYYY-MM-DD HH:mm"
              format24h
            ></q-time>
          </q-popup-proxy>
        </q-icon>
        <q-icon
          name="event"
          class="cursor-pointer"
        >
          <q-popup-proxy
            transition-show="scale"
            transition-hide="scale"
          >
            <q-date
              v-model="sentDate"
              mask="YYYY-MM-DD HH:mm"
            ></q-date>
          </q-popup-proxy>
        </q-icon>
      </template>

      <template v-slot:after>

      </template>
    </q-input>
```

**Additional context**
In my case( screenshot above )  it was important to keep the field readonly , Not just to preserve date format , but also because otherwise , the date , time popup would not render correctly because of the phone virtual keyboard that would show up and take the space. So making the q-input readonly was my solution , but now i cannot clear. In my screenshot above , there is no default date ( unlike the codepen )

**Comment by rstoenescu** [comment]
Hi,

1. The `clearable` prop is designed to make the "clear" icon not appear when using "readonly" (because, well, the value is readonly and this would break its purpose).

2. For your usage, you can add your own "clear" icon, like in docs:

```html
<template v-slot:append>
  <q-icon v-if="sentDate" name="cancel" @click.stop="sentDate = null" class="cursor-pointer" />
</template>
```

**Comment by rachitpant** [comment]
However as shown in your examples you can add a date/ time button and
change the v-model of the q-input ( even if its read-only ). So if the user
is able to change the value of a read-only q-input , he should also be
“clear” it.

Read only q-input should only mean user cannot type into it.

**Comment by rachitpant** [comment]
However as shown in your examples you can add a date/ time button and change the v-model of the q-input ( even if its read-only ). So if the user is able to change the value of a read-only q-input , he should also be “clear” it.

Read only q-input should only mean user cannot type into it.
