### ISSUE TITLE
TouchSwipe, impossible to pass args (+ move detection on touch issue)

### ISSUE THREAD

**Issue by eyedean** [quasarframework/quasar#5048]
**Describe the bug**
Based on the [documentation](https://quasar.dev/vue-directives/touch-swipe#API) for `TouchSwipe`, it should be possible to pass velocity, mobile-min-distance, and desktop-min-distance as args.  The example [provided](https://github.com/quasarframework/quasar/blob/dev/ui/src/directives/TouchSwipe.json#L60) is `v-touch-swipe:0.07:10:100="fnToCall"`.

There are two problems with it:

1. For the sensitivity, the decimal dot will make anything after it (i.e. `07:10:100`) to be parsed as a "modifier" by Vue, and only the `0` before the dot will be passed as "arg".  The workaround I came up with was to pass it as `v-touch-swipe:7e-2:10:100="fn"`.

2. The function used to parse this in the code is `parseInt`, which will parse any velocity below 1, as zero.  It should be replaced with `parseFloat` in https://github.com/quasarframework/quasar/blob/dev/ui/src/directives/TouchSwipe.js#L14

---

**Move detection issue on Touch**
Also, I found that the code is making a judgment call only based on the first `move` event -- if it doesn't detect any direction immediately, it will abort: https://github.com/quasarframework/quasar/blob/dev/ui/src/directives/TouchSwipe.js#L186.  

That's why on my phone (Pixel 3XL, Android 9, Chrome) playing with the documentation example I can never get an X distance more than 20px even when I do it super fast.  It just picks up the first out of tens or hundreds of events.  To compare, using [hammer.js's swipe](https://hammerjs.github.io/recognizer-swipe/) example in [their codepen sample](https://codepen.io/choskim/pen/rGZqxa) I can easily get from -200 to 200 (my phone's width is 412px).

I think the correct logic should be to abort only if the velocity drops below the threshold or min-distance is not met.

Please let me know if I should open a separate ticket for this issue.

Thanks!

**Comment by rstoenescu** [comment]
Hi,

Thank you for the detailed report!

1. You are perfectly right about the argument parsing. Fixed it. And will be available in v1.1.1.
2. We cannot change the current behavior because we need to know immediately if this will be a swipe or not (and in the right direction) in order to prevent page scrolling. However, you can tweak the arguments, so the sensitivity of the algorithm.

**Comment by eyedean** [comment]
Thanks for your prompt response, @rstoenescu!

1. It [looks great](https://github.com/quasarframework/quasar/commit/8750b70b7ddd77a121a5c45bfd9b8cb1e3c06e94) to me.

2. What you said makes total sense.  However, there are cases that the quality of the detection matters more that [StopAndPrevent](https://github.com/quasarframework/quasar/blob/dev/ui/src/directives/TouchSwipe.js#L170), either because that will be handled at the application level, or the possibility of scrolling is not even the case.(e.g. Horizontal Swipe on a full width mobile website.)
I am wondering if an ideal solution would be to provide an optional Prop of `nonImmediate` (or a similar name) to let the developer decided whether they want a non-immediate swipe detection based on all the `touchmove` ones (like what Hammer.js is doing), over the existing one.
Also, until then, I think we can add one of those very helpful info banners to let developers know that swipe on touch currently works only off of the first `touchmove`.  I don't regret that I spent 3 hours last night reading and debugging Quasar's code (and learning a ton from it!); Just not everyone might be able to afford that. :)

Thanks again, and cheers!
