### ISSUE TITLE
Quasar in Sass/SCSS form

### ISSUE THREAD

**Issue by TheJaredWilcurt** [quasarframework/quasar#5049]
Depending on the survey you find, somewhere between 75-95% of the industry uses Sass/SCSS. And the satisfaction rating for it is typically 90+%.

* https://2019.stateofcss.com/technologies

Sass also has better support for [modern CSS](https://dev.to/thejaredwilcurt/who-want-s-to-date-a-pre-processor-game-show-edition-4lfd).

There is a history of large projects that use Less/Stylus being switched over to Sass/SCSS.

* Bootstrap
  * v1 - Creator was friends with the creator of Less who asked him to use it on the project. Users immediately create an unofficial Sass port.
  * v2 - Seeing that the community wanted Sass over Less, both versions were maintained officially in version 2. This was cited as being a painful process
  * v3+ - Officially only supporting Sass
* Inkline
  * v1 - Initial release is praised for it's polish, but community asks to switch from Stylus to Sass
  * v1 - Creator quickly switches to Sass, dropping Stylus support.

The main lessons to learn from these case studies are:

* Sass is popular and desired, due to it's ecosystem, tooling, and integration with existing code.
* Switching becomes more painful as codebases and usage increase, for both the maintainer, and the users.

**Comment by rstoenescu** [comment]
Hi,

It so happens that we already started doing work for this! **No breaking changes will occur**.

Using Sass/SCSS is possible even [today](https://quasar.dev/quasar-cli/cli-documentation/handling-webpack#SASS%2FSCSS), just that you won't be able to use Quasar variables like with Stylus. **This is going to change**.

What we are currently working on:
* Support for a src/css/quasar.variables{.sass|.scss} file in `@quasar/app`. When that file exists in a project folder, it will enable you to use Quasar style variables in your `<style lang="scss">` or `<style lang="sass">` too.
* Replacing current src/css/quasar.variables.styl with a src/css/quasar.variables{.sass|.scss} will be supported. Quasar style itself will also compile using the new file instead.
* Offer Quasar's style source in the form of Sass (can be used seamlessly with SCSS too).
* Quasar app cli will support Stylus and Sass/SCSS out of the box (no additional packages will need to be installed for Sass/SCSS like it is required now).
* The starter kit will ask what is your "main" preprocessor of choice (Stylus or Sass/SCSS).
* **No breaking changes necessary in your project folders**.

Will keep everyone updated here as we make progress.

**Comment by M6stafa** [comment]
Do you want to drop stylus support?

**Comment by rstoenescu** [comment]
In Quasar v2 (so long into the future), Stylus will also be available. And work with the src/css/quasar.variables.styl file. The only difference will be that src/css/quasar.variables{.scss|.sass} will be required, because that's with what Quasar's CSS will be built with (only). So minimal impact over one's project folder. Functionality will be maintained. Let me know if I need to put this into better words.

**Comment by rstoenescu** [comment]
A few of the new possibilities (notice Quasar variables file can be even left out -- increased build speed):

![unknown](https://user-images.githubusercontent.com/4665641/64692065-dc72ab80-d49c-11e9-8c74-42ee07512ff6.png)

**Comment by rstoenescu** [comment]
<img width="265" alt="variables" src="https://user-images.githubusercontent.com/4665641/64693881-fadaa600-d4a0-11e9-88ee-ad2a9339e70f.png">

**Comment by rstoenescu** [comment]
<img width="543" alt="cli-question" src="https://user-images.githubusercontent.com/4665641/64700525-ba365900-d4af-11e9-8e9c-f11b17439894.png">

**Comment by rstoenescu** [comment]
Closing as this is entering final internal beta stage.
Will be available with quasar/app 1.1.0 and next Quasar version.

**Comment by rstoenescu** [comment]
Available through "@quasar/app" v1.1.0 and "quasar" v1.1.2. Both released today.

**Comment by dariodepaolis** [comment]
is there any chance to have this update also through Vue CLI?

**Comment by rstoenescu** [comment]
@dariodepaolis 
It will get updated eventually. But our current focus is Quasar CLI.
