### ISSUE TITLE
Quasar CLI: updating to @quasar/app 1.0.6 breaks "devServer.proxy"

### ISSUE THREAD

**Issue by arcadeJHS** [quasarframework/quasar#5053]
**Describe the bug**
For development purposes I am proxy my API calls to local .json files inside `assets/mock/` folder.
For instance, when my app calls `/login` the proxy return the file `assets/mock/login.json`.

@quasar/app 1.0.5 works as expected: the browser calls `/login`, and get the content of `login.json` file as a response.

Upgrading to version 1.0.6 the browser calls `/login`, and receive a `404 Not Found` error, with a `Cannot GET /assets/mock/login.json` as a response.

**`devServer` part of my `quasar.conf.js`**
```
devServer: {
    open: true, // opens browser window automatically
    // https: false,
    // port: 8080,
    proxy: {
        '/login': {
            target: 'http://localhost:8080',
            secure: false,
            pathRewrite: function (p, req) {
                req.method = 'GET';
                return 'assets/mock/login.json';
            }
        }
    }
}
```

**`login.json` file**
```
{
    "token": "asdfjhasdjkfjalkdsfkas"
}
```
**To Reproduce**
1. Add the `login.json` file in `assets/mock/`folder.
2. Add the devServer proxy config to `quasar.conf.js` file.
3. Add a button in your app code to call your API `/login` (I call it through `axios`).
4. Run `quasar dev` and press the "login button".

**Expected behavior**
As for version 1.0.5, also version 1.0.6 should resolve devServer proxy, and return content in `login.json` file.

**Platform:**
OS: OS X 10.14.1
Node: tested with v8.9.1 e v10.16.3
NPM: 6.9.0
Browsers: Chrome

**Additional context**
Rolling back to Quasar 1.0.5 fixes the issue. To test the issue I updated `@quasar/app`only, no other dependencies.

**Comment by rstoenescu** [comment]
Hi,

Please put the file in the /src/statics folder. That should be the only folder served "as-is" in dev mode.
