### ISSUE TITLE
Parallax

### ISSUE THREAD

**Issue by VladAndHanna** [quasarframework/quasar#5054]
Hi,
Please add a function - auto-adjust the height and width of the parallax picture.
Similarly, as in CSS - background-size: auto, cover, contain.
...............................................................
Example:
` <q-parallax>
      <template v-slot:media>
        <img src="../assets/images/parallax-bg.jpg">
      </template>
</q-parallax>`

.................................................................
If the image (parallax-bg.jpg) is wider than the screen, then it goes beyond the borders of the screen. The picture is not fully visible (cropped) and begins the "dance with a tambourine" :-)

Thanks!

**Comment by pdanpdan** [comment]
You can apply custom CSS if you want on the `.q-parallax__media > img` selector and it will be applied on the image.

**Comment by VladAndHanna** [comment]
Ok,
Thanks! :-)
