### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by VladAndHanna** [quasarframework/quasar#5055]
Hello,
I would suggest improving typography based on breakpoints.
Example:
Has already: .text-h2 - font size: 3.75rem;
Add:
.text-h2-xs - font size: ...
.text-h2-sm - font size: ...
.text-h2-md - font size: ...
.text-h2-lg - font size: ...
.text-h2-xl - font size: ...

Similarly:
- font weight;

And the ability to change it in the stylus variables.
This will allow quickly make settings for different screens out of the box.

Now:
1. I put the font size (computer screen);
2. For mobile devices, the font is very large.

Thanks :-)

**Comment by pdanpdan** [comment]
You can override the default classes and define the font size based on breakpoints if you need to.

You can either define specific classes (like `.text-h2-xs`) and use computed classes based on screen size (see #5056) or override the default in @media blocks in CSS.

**Comment by VladAndHanna** [comment]
Ok
Thanks!
