### ISSUE TITLE
CSS Positioning Classes

### ISSUE THREAD

**Issue by VladAndHanna** [quasarframework/quasar#5056]
Hi,
Maybe I didn’t see how to do it right ..

Your site has a page: https://quasar.dev/style/positioning
Great features!

But I need settings:
1. on a computer screen - place the item on the left.
2. on the mobile screen - place the item on the center.
I suggest: do with breakpoints (xs, sm, md, lg, xl)

Thanks :-)

**Comment by pdanpdan** [comment]
Generate the classes bases on the screen size: `<div :class="$q.screen.gt.sm ? 'fixed-left' : 'fixed-center'">...`
But move the calculated class in a computed property (here I put it inline because is simpler in the example).

**Comment by VladAndHanna** [comment]
Hi,
Got it!
Thank you very much!
Have a nice day!
