### ISSUE TITLE
[v1.1.0] <q-editor> BUG - <br> Tag in props.value when clearing out textarea

### ISSUE THREAD

**Issue by mathiasonea** [quasarframework/quasar#5057]
When deleting the content of the `<q-editor>` WYSIWIG component, the value is set to a `<br>` tag. This is so confusing, as I see an empty textarea and expect it to be really empty. And if I ask `if(value === '')` of course it fails, because there is the `<br>`"string in the value.

**To Reproduce**
1. Type something into the `<q-editor>` component.
2. Delete everything out of the `<q-editor>` component.
3. Inspect the element with the Vue Dev Tools
4. See that the value is not an empty string, but a `<br>` Tag

The value should be an empty string, if the content is deleted out of the editor box.

OS: Mac OS Mojave 10.14.5
Node: 12.10.0
NPM: 6.11.3
Yarn: 1.17.3
Browsers: Firefox Quantum 69.0 (64-Bit)

**Comment by rstoenescu** [comment]
Grouping with https://github.com/quasarframework/quasar/issues/4349
