### ISSUE TITLE
Cypress e2e Testing "locks" up with @quasar/app@1.0.6

### ISSUE THREAD

**Issue by rwuttke** [quasarframework/quasar#5059]
**Describe the bug**
Cypress hangs before it outputs RUN: Running e2e tests with cypress

**Codepen/jsFiddle/Codesandbox (required)**
None supplied as this is purely a command line driven issue.

**To Reproduce**
1. Install quasar cli `npm install -g @quasar/cli`
2. Create an application `quasar create cypress-test
3. Accept all defaults
4. Use npm instead of yarn
5. Change into the cypress-test directory `cd cypress-test`
6. Install the testing harness `quasar ext add @quasar/testing`
7. Select Cypress e2e testing
8. Select extra "scripts" in your package.json
9. Run cypress tests `quasar test --e2e cypress`
10. This _locks up_. On Linux, **Ctrl+c** works, but on Windows the terminal locks completely.
11. Remove @quasar/app@1.0.6 `npm remove @quasar/app@1.0.6`
12. Install @quasar/app@1.0.5 `npm install @quasar/app@1.0.5`

**Expected behavior**
The default test of the <title> tag to be run to completion, ie home/init.spec.js

**Screenshots**

This image shows where Cypress stops when @quasar/app@1.0.6 is installed. I have left it like this for > 6 minutes and nothing changes.

![Cypress Lockup 1 0 6](https://user-images.githubusercontent.com/2321176/64579885-9dbcf280-d3c3-11e9-8b46-9ba3defc182c.png)

This images shows that Cypress continues when @quasar/app@1.0.5 is installed.

![Cypress Continues 1 0 5](https://user-images.githubusercontent.com/2321176/64579899-a6152d80-d3c3-11e9-9e11-d2beb51bc756.png)

**Platform (please complete the following information):**
OS:  Windows 10 1903 and Ubuntu 18.04.03
Node: 10.16.3
NPM: 6.11.3
Yarn: N/A
Browsers: N/A
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
I have tested on both Windows and Linux (Ubuntu) and the same behaviour can be observed.

**Comment by rstoenescu** [comment]
Hi,

This should be reported to [quasar-testing repo](https://github.com/quasarframework/quasar-testing). And there's a ticket there already on this issue: https://github.com/quasarframework/quasar-testing/issues/105
