### ISSUE TITLE
Autocomplete component upper alignment

### ISSUE THREAD

**Issue by wilcorrea** [quasarframework/quasar#506]
### Software version

Quasar: 0.13.1
OS: Ubuntu 14.04
Node: v7.3.0
NPM: 3.10.10
Browsers: Chrome
iOS: N/A
Android: N/A
Any other software related to your bug: N/A

### What did you get as the error?
The popover of Autocomplete is getting over the reference input. There is any setting to adjust this?

![image](https://cloud.githubusercontent.com/assets/803733/24723333/8ec03682-1a1d-11e7-9286-f55ea16e3e97.png)

### What were you expecting?
Align the component imediatly above the input

### What steps did you take, to get the error?
I am using the component inside the layout to forms

**Comment by rstoenescu** [comment]
Will look into this. Thanks for opening!

**Comment by mstaack** [comment]
i can't reproduce this with http://quasar-framework.org/quasar-play/android/index.html#/showcase/form/autocomplete  on ubuntu and chrome ..

**Comment by rstoenescu** [comment]
@wilcorrea can you try with v0.13.6 again pls?

**Comment by wilcorrea** [comment]
I will see if there is any interferences in my environment. Thanks guys ; )

**Comment by rstoenescu** [comment]
Please reopen if it seems like something's wrong.

**Comment by Diferno** [comment]
Hi, I'm just facing a similar problem with autocomplete when viewing it on an iPhone 7. 

In my webapp (step 2 of the wizzard), just becomes un selectable [alarmios.com](http://alarmios.com) 

_Quasar framework I'm using is 0.13.1_
