### ISSUE TITLE
[docs][request] Example of how to listen to ServiceWorker events in Vue

### ISSUE THREAD

**Issue by Phr33d0m** [quasarframework/quasar#5060]
Hello,

Please include in the docs a simple example of how we can listen to service worker events so we can communicate better with our users.

I thought of this while looking at the banner example:

![image](https://user-images.githubusercontent.com/1591486/64605463-74509680-d3c4-11e9-9448-83477059203e.png)

And thought that it'd be nice if I could show it when my PWA users go offline. I've currently achieved this by using another root vue instance at window.Event ([as per Jeffrey Way's example here](https://laracasts.com/series/learn-vue-2-step-by-step/episodes/13)) but I don't feel this is the ~~right~~ quasar way, rather than a vue-centered approach. [I also found a simpler method just using the Event class](https://stackoverflow.com/questions/53680243/inform-app-vue-a-service-worker-event-is-being-called).

Thanks!

**Comment by rstoenescu** [comment]
Hi,

There's a much cleaner and better way which is embedded already into Quasar: https://quasar.dev/quasar-cli/developing-pwa/handling-service-worker

**Comment by Phr33d0m** [comment]
Hi, I was talking exactly about that doc page and that file you linked. How would you tell your App.vue component about any of those events?

It's not very obvious for newcommers to vue and quasar.

Thanks.
