### ISSUE TITLE
QInput with mask not updating content after clearing and setting a new value

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#5061]
**Describe the bug**
I have defined a custom date input component (wraps QInput), which uses a custom date picker component (wraps QDate). In order to use v-model with two-way binding, I have a standard setup of passing the prop down and emitting events up. The input can also be clearable and I need to use a custom mask for the dates. Everything works as expected except for one problem:

After using the clearable icon, the first time I pick a date from the popup calendar, the model changes correctly, but the content of the input field is not updated. The only visual indication that I observe is a quick flash of the cursor. Subsequent picks from the calendar work as normal.

If I remove the mask property on QInput, then everything works fine again. So I suspect the mask might be involved in some racing condition. But also, If I don't use the v-model setup then the problem doesn't occur either. This can be tested by using a codepen from the docs. Codepen is currently out of service, but I can submit an example later if needed.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/embed/vue-template-jb9f4

**To Reproduce**
1. Pick a date from the calendar.
2. Clear the field via the clearable icon.
3. Pick another date from the calendar.
4. The model is changed, but the input field is blank. This happens only the first time after clearing.

**Expected behavior**
The input field reflects the model.

**Platform (please complete the following information):**
OS: Linux
Node: 10.16.3
NPM: 6.11.3
Browsers: Chrome, Firefox, Opera

**Comment by pdanpdan** [comment]
Hello.

Replace the calculated localValue with this:

```javascript
    localValue: {
      get() {
        return this.value === null ? "" : this.value;
      },
      set(value) {
        this.$emit("input", value === "" ? null : value);
      }
    },
```

The input field emits an `@input` with null on pressing on clear button and the picker emits an `@input` with "" when opened, but both are translated to null in the component, and the QInput is not notified of the change (from null to ""). By keeping it internally as "" you avoid problems.

**Comment by MartinManev** [comment]
Hi, pdanpdan,

Thank you for the quick response. The proposed solution does work, but it looks very fishy to me. I hope you can review the quasar internals and see if there isn't a better way to go about this technicality.
