### ISSUE TITLE
how to registe  Global component  v1.0.5

### ISSUE THREAD

**Issue by ray-zyh** [quasarframework/quasar#5062]
sorry !I made a mistake in operation.  how to registe  global component?  my version   v1.0.5.
 I add a  myBoot.js to  /src/boot/  
 /** myBoot.js **/
import Vue from 'vue'
import notify from '../components/global/notify.js'
Vue.use(notify)

/*  notify.js*/
import {
  Notify
} from 'quasar'
const notify = {
  install: function (Vue) {
    function fun (position, msg, bg) {
      Notify.create({
        position: position,         
        textColor: 'white',
        timeout: 3000,
        message: msg,
         })
    }
    Vue.prototype.notity = {
      top: function (msg) {
        fun('top', msg, 'primary')
      },
     
    }
  }
}
export default notify

When I call  this.notify.top('this top notify')  , will prompt:  Cannot read property 'top' of undefined

**Comment by pdanpdan** [comment]
And the issue is?

**Comment by ray-zyh** [comment]
> And the issue is?
sorry !I made a mistake in operation. I hvae updated

**Comment by pdanpdan** [comment]
I suppose it has something to do with all the misspelled names you use (notity/notify).
Also please use code blocks, like
````
```javascript
...your javascript code here
```
````
