### ISSUE TITLE
QInput minlength

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5073]
We have `maxlength`, it would be great if we could also have `minlength`!

**Comment by pdanpdan** [comment]
It looks like `minlength` is supported, at least in the specification.
Please check here (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#Additional_attributes) for the list of supported attributes.

**Comment by mesqueeb** [comment]
@pdanpdan I meant for QInput! 😉 
Currently when I search the API card for `length` it only shows `maxlength` 😖

**Comment by rstoenescu** [comment]
But it also specifies that any attributes get attached internally. @mesqueeb

**Comment by mesqueeb** [comment]
@rstoenescu I see. But why then would we _only_ include maxlength on the API card, and not all of the native ones?

Or is there a reason to only include `maxlength` on the API card and not `minlength` ?

<img width="469" alt="image" src="https://user-images.githubusercontent.com/3253920/64905954-7a26de80-d71a-11e9-963b-594a2bdbcefa.png">

**Comment by rstoenescu** [comment]
Because it's the most important of all (many devs have requested it repeatedly). So, to make docs more explicit.
