### ISSUE TITLE
QTable: Displaying the icon chat_bubble_outlined in the last column causes a horizontal scrollbar to appear

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#5076]
**Describe the bug**
I am using the material design icons. The icon `chat_bubble_outlined` is part of the standard (filled) set, so I don't need to also import the outlined set. If I put a different icon in the last column of a QTable, then everything renders OK. But if the icon is specifically `chat_bubble_outlined` then a horizontal scrollbar appears as if the icon takes up more space for which the table doesn't account for.

If I use a QBtn with the icon, then the problem persists, BUT in the codepen I noticed that the icon is not centered correctly.

I haven't tested if any other icons can cause this problem.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/manev/pen/gOYKzdm?&editable=true&editors=101#anon-signup

**To Reproduce**
See the codepen. Play around with the commented lines.

**Expected behavior**
The horizontal scrollbar doesn't appear. The QTable recalculates the column widths correctly. The icon does not cause problems.

**Platform (please complete the following information):**
Quasar: 1.1.0
Quasar Extras: 1.3.1
Browsers: Chrome, Firefox, Opera

**Comment by pdanpdan** [comment]
This means that the icon is not identified as it should. The material icons use ligatures, and in your case the non outlined icon is rendered, and after it a space is rendered

**Comment by MartinManev** [comment]
Hi, pdanpdan,

I tried with `insert_chart_outlined`. There are no problems there.

> and in your case the non outlined icon is rendered

I'm not sure I understand. I'm seeing the correct icon displayed.

**Comment by pdanpdan** [comment]
Try to remove the _outlined. You might see the same icon without space

**Comment by MartinManev** [comment]
> Try to remove the _outlined. You might see the same icon without space

Yes, I know, but that is a different icon. I actually wanted to use both at the same time. The filled one when there is content, and the outlined one when there is no content.

It is not a problem for me to use different icons, but that doesn't mean the issue doesn't exist.

**Comment by pdanpdan** [comment]
The icons name is `chat_bubble_outline` (without a `d` in the end)

**Comment by MartinManev** [comment]
(lots of curses thrown at google)

Thanks :)
