### ISSUE TITLE
Utils/throttle.js: rest operator is not necessary

### ISSUE THREAD

**Issue by jesusvilla** [quasarframework/quasar#5078]
Using rest operator in the function is not necessary, since in babel it would generate an unnecessary transformation of `arguments` in an array (see [babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABFAFgJzlKAbApogCmDABpFsYBbGKRAXkQCYBWABgEpEBvAKEXNy0A7gEMa9RMBHYAzrjJpcMkNih9EiqCDRJQkWAkIA6EyLQBzGZ179-MYIQCEomtfW3EL2gyhoQud1s5KAAVKlw4ECgCAk46AD5uQI8vCSlZAI9-AF8yCmoodmSNJRVvSTAjEQAHauwATwJUGBkyM0sij2zAzW0kRWVVdW7unh49aHgkVAwsPAA5XCFCYjyqcQYARjY3fjxhMXL0uQVSof5enUlwScNYpI97Jy9drNSfP0ys4LDKCKiYnFEjYsvx3pJpHJirlyOtCsUBmU0pUanVGs1Woh2iA_mAoFZAt0PJd-mc1DkeNkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2016%2Ces2015-loose&prettier=false&targets=&version=7.6.0&externalPlugins=)) when the `apply` method already accepts arguments.
Check #5077

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1.
Thanks for also PRing it!
