### ISSUE TITLE
Make numeric localizable

### ISSUE THREAD

**Issue by petrroda** [quasarframework/quasar#508]
Hi,

it will be cool if you could make q-numeric formatable and localisable. 
Maybe based on Numeral.js (http://numeraljs.com).

Greets
Petr

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
I think the good way to go is for the developer to be able to specify the formatting in his/her app through whatever package he/she wants to use. I generally want to avoid relying on third party packages to add additional dependencies for Quasar core. Quasar footprint should be as low as possible. So will add this formatting option and devs can choose however they want to format their numeric values. Thanks for opening this!

**Comment by lyquocnam** [comment]
+1
in my country, we usually use number like this: 1,000,000 and higher.... so this option is important.
