### ISSUE TITLE
CLI - auto-import needed Quasar components & directives

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#5080]
### Intro
As we continuously improve the Quasar experience, we finally tackled one pain point, which is the need for you to tamper with /quasar.conf.js > framework > components/directives every time you add or remove the use of a Quasar component or directive.

### What is it about?
Introducing the auto-import feature. The CLI will detect what Quasar components and Quasar directives you are using in your .vue file templates and will import them on your behalf. No more going back and forth to /quasar.conf.js to add/remove something from framework: components/directives properties. And the treeshaking of Quasar is still there.

### How to enable?
In your /quasar.conf.js, go to `framework` and add this:

```js
framework: {
  all: 'auto'
}
```

### Requirements
This feature will be available through `@quasar/app` v1.1.0+ (and you'll also need `quasar` v1.1.1+). **Both are unreleased at the time of writing this**. It is a new feature supplied by the Quasar App CLI.

**Comment by rstoenescu** [comment]
Available through "@quasar/app" v1.1.0 and "quasar" v1.1.2. Both released today.

**Comment by dsl101** [comment]
This really is fantastic. Are there plans to extend it to the `plugins` section also?

**Comment by rstoenescu** [comment]
@dsl101 Hi, plugins reside outside of Vue's scope, so unfortunately it's not currently doable unfortunately. Not sure if the overhead would be worth it either. There are only a handful of Quasar plugins.
