### ISSUE TITLE
Select component - Add @onMenuOpen/@onMenuClose events

### ISSUE THREAD

**Issue by Elvanos** [quasarframework/quasar#5081]
**Is your feature request related to a problem? Please describe.**
Sometimes when working with very specific and detailed selects, I am in the need of events that would signal if the dropdown menu with items has been opened or closed.
This is mostly caused by the fact that the escape key or clicking outside the menu doesn't defocus the whole `Select` element if an `input` is used for text input, but instead just closes the menu without defocusing the whole component.

**Describe the solution you'd like**
Add events to the Select components:
`@onMenuOpen` - Fires when the menu opens.
`@onMenuClose events` - Fires when the menu closes.
**OR**
Defocus the whole element including the input when the menu closes (might make more sense in some ways).

**Describe alternatives you've considered**
I considered using the `@focus` event instead, but that only fixed half of my problem since the element does NOT defocus when the dropdown menu closes.

**Additional context**
Don't think so, I hope my description is good enough.

**Comment by smolinari** [comment]
Was this your thread in the forum? 

https://forum.quasar-framework.org/topic/4266/how-to-access-overwrite-internal-menu-component-from-qselect

Scott

**Comment by Elvanos** [comment]
No, that is someone completely different suggesting this, but I will attempt to apply these solutions to my issue.

Either way, I still think the `close/hide` events would be quite helpful in some cases.

**Comment by pdanpdan** [comment]
You can use `@popup-show.native` and `@popup-hide.native` to hook on showing/hiding the list of options.

**Comment by smolinari** [comment]
Holy cow. Where did that gem of information come from? 😁 Need to add that in the docs for sure. 

Scott

**Comment by pdanpdan** [comment]
@smolinari please add it to the docs. Both events receive an event object with target the comment that is the placeholder for the portal

**Comment by smolinari** [comment]
Should they be entries in the API.json?

Scott
