### ISSUE TITLE
Unable to view page images with firefox https://quasar.dev/vue-components/img#Usage

### ISSUE THREAD

**Issue by bebekar** [quasarframework/quasar#5082]
the following link of Quasar link does not render in **Firefox** displaying images.
Chrome displays it as well  
https://quasar.dev/vue-components/img#Usage
 
The same happens when I use q-img in my application 

i am using Firefox 69.0 (64-bit) on windows 7

**Comment by pdanpdan** [comment]
All looks good on Windows 10 / Firefox 70 developer.

Can you check if you have errors in console?

**Comment by olegvakulenko** [comment]
Windows 7 / Firefox 69.

Images are rendered normally.

**Comment by jesusvilla** [comment]
All good on Windows (7 & 10) / Firefox 69

**Comment by metalsadman** [comment]
@bebekar looks fine here win7 / firefox 69
![image](https://user-images.githubusercontent.com/31038838/65010760-74601180-d943-11e9-9881-f19142793fc1.png)
check if you have some rogue extension messing the page.

**Comment by bebekar** [comment]
Checked the console for errors, none
This is how it look with me
[image: image.png]

**Comment by pdanpdan** [comment]
@bebekar please check the image.

**Comment by bebekar** [comment]
![imageErr](https://user-images.githubusercontent.com/3948155/65030855-e8a7ae80-d95d-11e9-8728-bc17ef0cae51.JPG)

**Comment by rstoenescu** [comment]
@bebekar Do you have any FF extensions that can interfere with images?

**Comment by bebekar** [comment]
I removed all just to check. no change. inspected the code and could not see the src.

**Comment by bebekar** [comment]
okay, removed DuckDuckGo . then Privacy Badger. I guess the Privacy Badger was doing the blocking
Its working now. 
need to understand why Privacy Badger would block some images?

**Comment by pdanpdan** [comment]
Closing this as it's related to user installed extension.
