### ISSUE TITLE
Popup proxy's size is incorrect in internet explorer 11

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#5084]
The following link in the documentation shows examples of popup proxys. All other browser I tried made it well, but it seems there is an issue with IE11: https://quasar.dev/vue-components/popup-proxy

I am using Internet Explorer 11 (11.356.18362.0) on Windows 10

![Capture](https://user-images.githubusercontent.com/17769074/65020798-2856a200-d92e-11e9-974e-39a8ba8a22a5.PNG)

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.3.
