### ISSUE TITLE
Loading doesn't display on subsequent loading.show calls

### ISSUE THREAD

**Issue by TheCheat** [quasarframework/quasar#5085]
**Describe the bug**
Quasar Loading plugin doesn't display loading if "show" was called synchronous (or with small interval)

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/z6tybms8/

**Expected behavior**
I was expecting to display loading at least on 2nd call of loading.show

**Comment by rstoenescu** [comment]
Hi,

This has already been fixed in v1.1.1 (to be released today).
Reference https://github.com/quasarframework/quasar/issues/4992
