### ISSUE TITLE
[docs] Missing info on local storage?

### ISSUE THREAD

**Issue by rconstantine** [quasarframework/quasar#5086]
The API docs at the bottom of this page: https://quasar.dev/quasar-plugins/web-storage both have number in chips on the Injection tab that indicates quite a few entries, but each only has one entry for ‘Name’. Should there be more there?

**Comment by rstoenescu** [comment]
Hi,

Aren't you getting this?

<img width="839" alt="web-storage" src="https://user-images.githubusercontent.com/4665641/65146163-d55f1680-da23-11e9-932c-391f926936e9.png">

**Comment by rconstantine** [comment]
I should have taken a screenshot. Yesterday, both Local and Session INJECTION chips said 12, not 1. METHODS both said 9, like your screenshot. Weird.
