### ISSUE TITLE
Less Compilation is failing with Quasar version 1.1.1

### ISSUE THREAD

**Issue by aljones15** [quasarframework/quasar#5087]
**Describe the bug**

```
Less compilation failed workerPid=21168, details={
  "message": "Property '$editor-button-gutter' is undefined",
  "type": "Name",
  "filename": "/node_modules/quasar/dist/quasar.css",
  "index": 38758,
  "line": 1875,
  "column": 9,
  "callLine": null,
  "extract": [
    "  position: absolute;",
    "  left: -$editor-button-gutter;",
    "  top: 4px;"
  ]
}
```

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

the issue is that this command is failing on your quasar.css file:
`less.render(src, cfg.options, callback)`

**Expected behavior**
Before the version 1.1.1 release our post-install script would use quasar's css file
along with our own less based style sheets to create one css file. So I expect to be able to
combine less and css style sheets into one css file.

**Screenshots**$editor-button-gutter

The existing npm error explains the issue. I can not even get quasar
and less style sheets to cooperate in the latest release so can not even
get to the UI right now.

**Platform (please complete the following information):**
OS: ubuntu
Node: 11.15.0
NPM: 6.7.0
Yarn: none
Browsers: none
iOS: none
Android: none
Electron: none

**Additional context**

The primary issue appears to be a sass variable `$editor-button-gutter` is in `dist/quasar.css` now. if that variable is not there less compilation is fine. I also saw that you are deprecating less support.

**Comment by rstoenescu** [comment]
Hi,

Sass not getting deprecated.
Minor issue in quasar/app. Will fix it.

**Comment by rstoenescu** [comment]
Quasar v1.1.2 released (package "quasar"). Please upgrade to it.

**Comment by rstoenescu** [comment]
Thanks for reporting!

**Comment by aljones15** [comment]
no problem will test it out in a moment.

**Comment by aljones15** [comment]
is working fine here thanks man.
