### ISSUE TITLE
framework all: 'auto' possible conflict with global component registration in boot files?

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5088]
**Describe the bug**
When I use framework: `{ all: 'auto' }` in quasar.conf.js, some of my pages do not find globally-registered components (registered using boot files). I get the **Unknown custom element: <portal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.** console message.

Some routes/pages work fine while others don't find the global components, which makes no sense to me. Which routes/pages work and which fail to find the global components is consistent with each build.

Everything works as expected if use framework `{ components: [...] }` with manually specifying Quasar components.

**I can't seem to reproduce in a simple codesandbox yet but wanted to at least document it in case anyone else comes across a similar issue with components not being found and doesn't immediately make a connection to the new loading option.**

For now I am sticking with manually specifying components in quasar.conf.js.

Sample boot files:

(using Portal Vue plugin)
```typescript
import PortalVue from "portal-vue"

export default async ({ Vue }) => {
  Vue.use(PortalVue)
}
```

(using a custom page-wrapper component)
```typescript
import { AppPage } from "@/components"

export default async ({ Vue }) => {
  Vue.component("AppPage", AppPage)
}
```

**Codepen/jsFiddle/Codesandbox (required)**
Can't seem to recreate the issue in a codesandbox, I suspect a simple sample is just too simple to cause any issues. Will report back if/when I can reliably reproduce in codesandbox.

**To Reproduce**
N/A at this point, working on it.

**Expected behavior**
Global components to just work from all components.

**Platform (please complete the following information):**
Global packages 
  NPM - 6.9.0
  yarn - 1.17.3
  @quasar/cli - 1.0.0
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.1.1
  @quasar/app - 1.1.0
  @quasar/extras - 1.3.1
  vue - 2.6.10
  vue-router - 3.1.3
  vuex - 3.1.1
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.5.5
  webpack - 4.39.3
  webpack-dev-server - 3.8.0
  workbox-webpack-plugin - 4.3.1
  register-service-worker - 1.6.2

Quasar App Extensions
  @quasar/quasar-app-extension-qoverlay - 1.0.0-beta.3
  @quasar/quasar-app-extension-icon-genie - 1.0.2

**Additional context**
It's possible there's a different root error but "Unknown custom element"  is the only info exposed at run time.

**Comment by rstoenescu** [comment]
Hi,

Just to be clear: the auto-import feature works for Quasar components & directives only and only in .vue files. It does not works for components/directives outside of Quasar's.

Can you offer a barebones reproduction repo that I can take a look, pls?

**Comment by GordonBlahut** [comment]
> Just to be clear: the auto-import feature works for Quasar components & directives only and only in .vue files. It does not works for components/directives outside of Quasar's.

Yep, I understand that. That's why I'm still registering non-Quasar components in boot or in .vue files themselves. 

> Can you offer a barebones reproduction repo that I can take a look, pls? 
  
Trying to reproduce it in a barebones setup. I will report back once I have something more concrete.

**Comment by rstoenescu** [comment]
Please feel free to reopen with the barebones setup.
