### ISSUE TITLE
Q-Table click-row feature (instead of checkbox)

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#5089]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem.

**Describe the solution you'd like**
I will love if you put an attribute for QTable to select a row clicking on TR, without using checkboxes (or emit @selection always, even if I'm not on selection mode)

**Describe alternatives you've considered**
The alternative is to use a @click.native on TR, but I have to rewrite both header and body:
```javascript
<template v-slot:header="props">
  <q-tr :props="props">
    <q-th v-for="col in props.cols" :key="col.name" :props="props">
      {{ col.label }}
    </q-th>
  </q-tr>
</template>

<template v-slot:body="props">
  <q-tr :props="props" @click.native="props.selected = !props.selected">
    <q-td v-for="col in props.cols" :key="col.name" :props="props">
      {{ col.value }}
    </q-td>
  </q-tr>
</template>
```

**Comment by smolinari** [comment]
It's a nice solution with the slots. Isn't it? It gives you, as the developer, absolute control. You can then create your own custom-built selectable QTable component with it. Something like `MySelectTable`. (like, with your custom component, you'll only have to program those slots once).  😁 

Like this: 

https://codepen.io/smolinari/pen/eYOPZoa?editors=1010

Scott

**Comment by dariodepaolis** [comment]
Sure I can create my own component and program the slots once, but sometimes, as developer, we are really lazy and want to use a component with zero code 😛 something like: 
```<q-table :data=... :columns=... selection="single-row" :selected.sync="selected"/>```

**Comment by smolinari** [comment]
It's ok to think in terms of convenience, where it makes sense, but not in terms of letting devs be "really lazy" IMHO. :D If Quasar did that, there would be 100s of different props for all of the different ways QTable could be used. Nah, instead, scoped slots are the smart solution, putting the control in your hands to do whatever you'd like. 

The only thing that I can fathom that might be useful for the use-case of customizing single row selection is a prop to stop the rendering of the selection column. That way, the need for the header column would be avoided and it would be a 100% clear handover to the dev to make a custom row for selection.  So, maybe something like `hide-selection-column` or `custom-selection`. 😄  

Scott

**Comment by CrawfordW** [comment]
I'm with smolinari on this. Being able to select one or several rows in a sorted report to trigger some action is a very common design pattern. I'm not lazy, but just learning Quasar - I spent 2 days fiddling with slots before I got it to do this with one row selected. Still haven't figured out how to do multiple rows!

**Comment by smolinari** [comment]
@CrawfordW 

Not sure my code for selection and de-selection is as elegant as it can be, but you should get the gist of it. :)

https://codepen.io/smolinari/pen/WNvWMvB?editors=1011

Scott

**Comment by CrawfordW** [comment]
Thanks. That helps. But ideally clicking another row should unselect existing one unless user presses shift key first. I still think the table widget should provide this behaviour without having to fiddle with slots.

**Comment by smolinari** [comment]
You can take the challenge to make it as you wish it. :grin:

And just as you came up with what you think should be the functionality, I think differently. So, it's not fiddling, it's doing what you want. There are 1000s of different "ways" to want things to get done in the data table. And, if we added every feature that every dev would like to have, it would become an ugly bloaty component. I'd argue, it's already doing too much. But, that is just me. :grin:

Scott

**Comment by CrawfordW** [comment]
OK I accepted the challenge!
Here's a codepen based on your code with a few changes...
You can select or de-select a single row by clicking on it.
You can select or de-select multiple rows with Ctrl-click.

[https://codepen.io/crawfordw/pen/oNXOMKg?editors=1011](url)

I wanted to be able to use Shift-click to select a contiguous block of rows, but would need to be able to get the index of each row as displayed (after sort) and have no idea how to do that. Also, shift-click causes all the intermediate data values to get highlighted!
I also wanted to be able to select single rows using the keyboard up/down arrow keys, but again would need the displayed row indices.

Anyway, some progress.
Crawford

**Comment by pdanpdan** [comment]
You can check here for keyboard navigation: https://github.com/quasarframework/quasar/issues/6590

**Comment by CrawfordW** [comment]
Thanks.

**Comment by smolinari** [comment]
@CrawfordW - Your codepen link is messed up. :)

Scott

**Comment by CrawfordW** [comment]
Sorry. Try this...
https://codepen.io/crawfordw/pen/oNXOMKg

**Comment by smolinari** [comment]
@pdanpdan - I'm not seeing how to get the index of a particular row. Is there a way? Is it even necessary for what @CrawfordW is needing? I'm not seeing it myself. 

Scott

**Comment by danbars** [comment]
Got here after fiddling with this myself and failed to achieve the desired behavior.
I've read all this thread, and I think @dariodepaolis and @CrawfordW have a point here.
Of course components should not do every permutation of behavior that anyone would ever want. But they do have to encapsulate common behaviors in a good way that consider things as accessibility, keyboard navigation and common-expected-ux-patterns such as ctrl+click and shift+click. Otherwise, what's the point of having components at all? We can just work with div's and get whatever we we want in the most flexible way.

I think this is really hard to achieve by custom code (I've tried) using existing events (for example, the index of the row that was clicked in `row-clicked` event is missing), and I think that since row selection is really commonly needed in tables, it should be part of the component. 

Can we re-open this ticket and re-consider adding this?

Thanks

**Comment by CrawfordW** [comment]
@pdanpdan Sounds good. Thanks! When will version 1.13 be available for general use?

**Comment by AntonioLl24** [comment]
Hi, I may have missed something but, is there a way to get the value of a single cell selected ? index and value or value only ???

**Comment by wt0m** [comment]
Hello, I need this too in a few tables and it would be great to achieve this without rewriting the row implementation every time

**Comment by CrawfordW** [comment]
This is how I solved it. (each table row must be assigned a unique id when created).
Allows for single selection, multiple non-contiguous selections using ctrl-click, or block of selection using shift-click...
```
<template v-slot:body="props">
   <q-tr class="cursor-pointer"
        :props="props"
        @click.stop="selectRow(props.row, $event)"
        @dblclick.stop="viewFormula()"
        @mouseup.right="selectRow(props.row, $event, true)"
    >
....
selectRow (newRow, event, right = false) {
      if (right && this.selected.includes(newRow)) { // don't change selection - popup menu will show
        return
      }
      if (!event.ctrlKey && !event.shiftKey) {
        this.selected = [newRow] // Only single selection so remove any previous
      }
      // Save the selection and get the id of the selected item
      if (event.ctrlKey) { // Add or remove one selection
        if (this.selected.includes(newRow)) { // Remove it unless right-clicking
          this.selected = this.selected.filter(x => x !== newRow)
        } else { // Add it
          this.selected.push(newRow)
        }
      } else if (event.shiftKey) { // May be selecting a block of rows
        const displayedRows = this.$refs.table.computedRows
        // First remove any selections except the first
        if (this.selected.length > 0) {
          this.selected = this.selected.slice(0, 1)
          // Get the display index of this selection
          const startIndex = displayedRows.findIndex(row => row.id === this.selected[0].id)
          // And get the index of this new selection
          const endIndex = displayedRows.findIndex(row => row.id === newRow.id)
          if (endIndex > startIndex) { // End is below Start
            for (let i = startIndex + 1; i <= endIndex; i++) {
              this.selected.push(displayedRows[i])
            }
          } else { // End is above Start
            for (let i = endIndex; i < startIndex; i++) {
              this.selected.push(displayedRows[i])
            }
          }
        } else { // No previous selection, so just add this one
          this.selected = [newRow]
        }
      }
      // Update the list of selected Ids
      this.selectedIds = []
      this.selected.forEach(item => {
        this.selectedIds.push(item.id)
      })
}
```

**Comment by snupsband** [comment]
> It's a nice solution with the slots. Isn't it? It gives you, as the developer, absolute control. This gives you the ability to waste your time implementing a custom solution to do something simple that should've been the default behavior.

100%. Why do I have to write 50 lines of JavaScript to remove a checkbox and allow my users to click on a row in a table?

This is why I use PrimeVue instead in all of my new projects. Perhaps I can convince my customer to allow me to switch this UI over to a modern UI toolkit.

EDIT: I found a better solution somewhere else:
```
      <template #header="props">
        <q-tr :props="props">
          <q-th v-for="col in props.cols" :key="col.name" :props="props">
            {{ col.label }}
          </q-th>
        </q-tr>
      </template>
      <template #body="props">
        <q-tr
          class="cursor-pointer"
          :props="props"
          @click="props.selected = !props.selected"
        >
          <q-td v-for="col in props.cols" :key="col.name" :props="props">
            {{ col.value }}
          </q-td>
        </q-tr>
      </template>
```
Sorry about the formatting; Prettier is pretty opinionated.
