### ISSUE TITLE
Allow for manual platform setup

### ISSUE THREAD

**Issue by mbouclas** [quasarframework/quasar#509]
The way platform detection works right now, is fine for the web, but it creates a bunch of problems when targeting other platforms. Since, automatic detection is a complicated matter, i suggest we allow for a user defined global which will make things simpler.

Example:

Developing on cordova and using the [cordova-simulate plugin](https://github.com/Microsoft/cordova-simulate) is a time saver for quasar. It allows local development simulating the cordova plugins. The problem is, that cordova.js is not included during build simply because of this
```
if (Platform.is.cordova && !Platform.within.iframe) {
```
The result of `Platform.is` when running the simulator
```
{
  "chrome": true,
  "version": "44.0.2403.133",
  "versionNumber": 44,
  "android": true,
  "mobile": true,
  "webkit": true,
  "name": "chrome",
  "platform": "android"
}
```

If i could have a global flag (could be set in webpack or even in my code, doesn't matter much) like 
`window.Platform = 'cordova'` that would allow us to test easier and more accurately (for every case you detect now, we can override)

Thoughts?

**Comment by rstoenescu** [comment]
Hmm, that cordova-simulate plugin seems quite interesting. Will add a way for the developer to be able to override the default platform detection in order to force "simulate" other environments. Thanks for opening this!

**Comment by mbouclas** [comment]
We could even set it from the environment come to think of this. Like 
```
process.env.platform = 'cordova'
```

I feel it's much cleaner and testable this way. Then, we can alias it on webpack like so
```
aliases: {
   platform : process.env.platform || 'chrome'
```

or something of this nature anyway

**Comment by rstoenescu** [comment]
Yes, thinking of something similar too.

**Comment by rstoenescu** [comment]
Hi,

I think this is obsolete now since Quasar v0.15 has been released. It allows for HMR (along with cordova plugins!) directly in the emulator or on a real phone -- no longer needing Quasar Play app.
