### ISSUE TITLE
Makes absolute paths for bundles on history router mode

### ISSUE THREAD

**Issue by Maksio** [quasarframework/quasar#5091]
Hi,

when I set  `vueRouterMode: 'history'` in `quasar.conf.js` and build my project it makes absolute paths of bundles:

`<link href="/css/06da87e0.97503d38.css" rel="prefetch"><link href="/css/2fb11fcc.af6c7153.css" rel="prefetch">`

Is it a feature or bug? I want to use history mode with relative paths.

Please help

**Comment by rstoenescu** [comment]
Hi,

You cannot use relative paths, because the path is changing.... '/users/dashboard', '/user/account'. If you'd be using relative paths, then browser would try to download /css/hash.css from /user/dashboard/css/hash.css etc...
