### ISSUE TITLE
QInput console error in file selection input after upgrading to quasar-v1.1.1

### ISSUE THREAD

**Issue by apasov** [quasarframework/quasar#5092]
**Describe the bug**
When clicking 'Choose file(s)' button in `<q-input @input="val => { someFile = val[0] }" type="file" />`
file selection dialog opens properly but dev console displays these errors:
`DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.`

I believe it started happening after commit a77f73438d1cc9d333eacf654a278077813de80d
The error is triggered at this line: https://github.com/quasarframework/quasar/blob/d4923a36df8254f55485f2b9e566399d135a79af/ui/src/components/input/QInput.js#L205

**Expected behavior**
No error in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/28765662/65146980-71d1ea80-da1d-11e9-8bee-d40358b6a32d.png)
![image](https://user-images.githubusercontent.com/28765662/65147044-8f06b900-da1d-11e9-805b-2307fa72650f.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: latest
Yarn: latest

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.3.
