### ISSUE TITLE
Calls to router push/replace to handle promise rejection in case the navigation is aborted.

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#5093]
**Is your feature request related to a problem? Please describe.**
In the newer versions of vue-router the push/replace functions return a promise. If the navigation is aborted, then the promise is rejected and, if not handled, produces an error in the console: `Uncaught (in promise)`. The error doesn't actually break anything, but is annoying to see.

See this comment: https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378

The `<router-link>` component doesn't generate an error when the navigation is aborted. The `QBtn` component, on the other hand, does. It calls $router.push / replace without handling the rejection and it generates the error.

I think there are other components which have a link prop, for example QItem. They should be updated too.

**Describe the solution you'd like**
Handle the promise rejection to prevent the error.

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrainventures** [comment]
Hi .. if you upgrade to 1.1.1 / 1.1.2 .. this is fixed ..

fix(QBtn): Adapt to newer vue-router behavior of throwing error when navigating to same route

**Comment by rstoenescu** [comment]
Yep, upgrade "quasar" package to v1.1.2.

**Comment by MartinManev** [comment]
Awesome. I haven't upgraded yet and so I missed the change.
