### ISSUE TITLE
Virtual Scroll Fullpage-Pagemode possible / planned ?

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5097]
**Is your feature request related to a problem? Please describe.**

If i right understand the actual behaviour of the qvirtualscroll i can use it inside
a "classic" ScrollArea .. 

If i need a Webpage with scrolling downside - as we know by facebook etc. - 
for e.g. a Timeline with Images / Text it would be for this case more intuitive to have a
Fullpage-Pagemode as i saw on:
https://akryum.github.io/vue-virtual-scroller/#/recycle
(check PageMode and FullPage) 

Is this actually possible with this Quasar Component ? (get a natural scroll-slider wrapped
around the complete layout )  , if not is this planned, or is this "far out of scope" ? 

Thanks for your great Work.

**Comment by pdanpdan** [comment]
Check the docs, second paragraph: https://quasar.dev/vue-components/virtual-scroll#Scroll-target
