### ISSUE TITLE
Dialog doesn't autofocus "ok" button if called from a QBtnDropdown

### ISSUE THREAD

**Issue by renancavalieri** [quasarframework/quasar#5099]
If you click on a QBtnDropdown thats open a Dialog using Dialog Plugin, it doesn't focus the "ok" button, and when you do the same with a button, it works properly.

https://jsfiddle.net/9b2oLarg/2/

Tested in Chrome 75, running Quasar 1.1.2 on jsfiddle.

**Comment by pdanpdan** [comment]
Just open the dialog in a $nextTick to allow the focusing to work. I'll take a look, but it's such a corner case.

**Comment by renancavalieri** [comment]
Yes, it is indeed a corner case, nothing serious, just an enhancement.
However, I had to put inside a setTimeout (100ms), because $nextTick doesn't worked too.

https://jsfiddle.net/svd769cm/

**Comment by pdanpdan** [comment]
I found it, thank you for pointing it out.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.1.3.
