### ISSUE TITLE
i can't using stylus colors variables in components

### ISSUE THREAD

**Issue by alioygur** [quasarframework/quasar#510]
the quasar docs says that "you can use stylus colors variables in your app code" but i can't do it.

http://quasar-framework.org/api/css-color-palette.html

```
div
  color $red-1
  background-color $grey-5
```

**Comment by rstoenescu** [comment]
Use can use them through `bg-[color]` or `text-[color]` CSS classes, or you can import Quasar Stylus definition files by adding the following code to your "style" tag in *.vue files:
`
@require 'quasar-framework/src/themes/quasar.core.variables.styl'
`

**Comment by alioygur** [comment]
@rstoenescu thank you dear!

**Comment by alioygur** [comment]
btw, i think you have missed the '~' begining of path.

@require '~quasar-framework/src/themes/quasar.core.variables.styl'

**Comment by rstoenescu** [comment]
Yes, right. Editing.
