### ISSUE TITLE
Data Table does not support Vue's fetching after navigation

### ISSUE THREAD

**Issue by genyded** [quasarframework/quasar#511]
### Software version

Quasar: 13.6
OS: Win 10
Node: 6.9.5
NPM: 4.4.1 
Browsers: All 
iOS: N./A
Android: N/A
Any other software related to your bug: Vue JS 2.8.1

### What did you get as the error?
`quasar.common.js?e3df:3265 Uncaught TypeError: Cannot read property 'clientWidth' of undefined
    at eval (eval at <anonymous> (app.js:2700), <anonymous>:3265:45)`

### What were you expecting?
Data table should support fetching after navigation (probably by checking for Vue create() before clientWidth)

### What steps did you take, to get the error?

1.  Fetch data using Vue fetching after navigation as described [here](https://router.vuejs.org/en/advanced/data-fetching.html)
2. 2. This fetches async remote data in the Vue created() method of the component
3. 3. The data table tries to get the clientWidth before the data is returned, displays the error and fails to load
4. 4. I think waiting for the component to be created before calling clientWidth will address this
5. if AFTER the component is loaded and you switch between mobile and desktop (in Chrome) the data table will show up without errors and with the data
6. If you refresh the page (or load in a new page) the error is back and the component fails to load
7. If you use static data or fetch before navigation the problem does not happen but that alters the user experience for the app 

Below is what should be a data table with 2 simple rows and the raw data in JSON format below it:

With fetch after navigation (no data table and error):
![image](https://cloud.githubusercontent.com/assets/3081676/24917255/36cfe13c-1ea2-11e7-816d-6a03d555f1e2.png)

Same screen simply switch to mobile view (in Chrome dev tools) - data table shows up and no error:
![image](https://cloud.githubusercontent.com/assets/3081676/24917360/834ef7b4-1ea2-11e7-93b1-6e520f3ccacd.png)

Same screen switch back to desktop view - data table still shows up and no error:
![image](https://cloud.githubusercontent.com/assets/3081676/24917407/b792a476-1ea2-11e7-94b9-b472173f55c3.png)

Refresh the page and the data table will not longer render and the error will occur. None of this happens when fetching before navigation, using static data, or data from a local file, so it looks like Quasar is not waiting for created() completion before trying to get clientWidth when fetching after navigation. It should work in any of the scenarios Vue supports.

Thanks!

**Comment by rstoenescu** [comment]
Option 1. Initialize datatable data with empty array by default in your component. After fetching data replace empty array with real data.

Option 2. It's a general rule of thumb to not display parts of UI that are not ready yet to be consumed by the user. Display a spinner or a message or something indicating data is being fetched instead. Put a `v-if` on datatable so that it doesn't gets rendered if no data is yet available.

**Comment by genyded** [comment]
Thanks! The empty array does not seem to work (we we're already doing that), but `v-if="entity && entity.length"` on the element does.
