### ISSUE TITLE
QDialog not resetting focus on hide (or components not reflecting focus state)?

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5111]
**Describe the bug**
`QDialog` does not seem to correctly refocus the original element/component on hide even though `no-refocus` is not set. This makes for difficult keyboard navigation when opening/closing dialogs.

If you set `no-focus` to `false` then at least the original element retains focus when the dialog is hidden, however this means the dialog is difficult to navigate with a keyboard since it's not focused.

It looks like it tries to set focus (reported active element changes via observing focusin on the document) but the focus is not reflected in the UI appearance.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gordonblahut/pen/dybQMQP?editors=1111

**To Reproduce**
1. Click on the `QField`, dialog opens
2. Click on "Close" or otherwise dismiss the dialog
3. `QField` no longer shows focused appearance, yet the active element appears to be the focusable div inside the field, 
4. Click on the "Show dialog" button, dialog opens
5. Click on "Close" or otherwise dismiss the dialog
6. Button no longer shows focused state, but this is a bit weirder than the field since the active element after the dialog closes is set to the `<div tabindex="-1" class="q-focus-helper"></div>` element inside the `button` and that element cannot be focused due to the tabindex so even if `QDialog` did reset the focus, calling focus on that element would do nothing. 

**Expected behavior**
Focus to return to previously-focused element when dialog was opened, and UI appearance to reflect focused field.

**Platform (please complete the following information):**
v1.1.2 on codepen

**Additional context**
"Focus field" button shows that calling focus() on the div (as opposed to the `QField itself) does indeed make the `QField` appear focused - so it should work when called from the `QDialog`

`QBtn` does not have a `focus` method, so I'm not sure of the proper way to set focus to a button. I used `$el.focus()` in the "Focus button" button which does set the button to a focused appearance, but that seems to be inconsistent with the active element after the dialog is dismissed.

**Comment by pdanpdan** [comment]
Thank you for the report, it was very good :)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.1.3.

**Comment by GordonBlahut** [comment]
Wow, you guys work fast! Thanks!
