### ISSUE TITLE
Background styles for q-carousel_slide are inline css instead of in .q-carouselslide class

### ISSUE THREAD

**Issue by sskwrl** [quasarframework/quasar#5117]
**Describe the bug**
background-size and background-position are generated as inline style declarations for q-carousel_slide's div instead of in .q-carouselslide

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/skwrl/pen/oNvGpya

**To Reproduce**
1. Create a Carousel with a slide
2. Add a css class that overrides background position or size
3. See they don't take effect
4. View source to observe the background properties are inline on the slide instead of in class

**Expected behavior**
Properties in class so they can be overridden with another class

**Screenshots**

**Platform (please complete the following information):**
OS: Win/Ubuntu
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by sskwrl** [comment]
I'm fixing this issue but can't assign it to myself at the moment.

**Comment by pdanpdan** [comment]
this was fixed in aa9fa1c951f16d32d5dfabd8c832dff77ce382ad

**Comment by sskwrl** [comment]
Well, that explains why I couldn't find the code that was putting the attributes on the div when I tried to debug it this weekend!  I am too slow for @rstoenescu!
