### ISSUE TITLE
QDrawer -> emit event when enter / leave minimode

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5118]
It would be great to have a event emitted (like @show etc.) on the qdrawer api
when the minimode is triggered .. We use the minimode with some screensize changes and it would be get the event when the minimode is accessed. 

It would great to have this feature .. if possible.

Thank you very much

**Comment by rstoenescu** [comment]
Hi,

Nobody can refuse when asked so nicely :))
Will be available in "quasar" v1.1.3 through the `@mini-state` event (payload is Boolean).

Cheers.
