### ISSUE TITLE
Progressive Web App template

### ISSUE THREAD

**Issue by matthewpull** [quasarframework/quasar#512]
I know that this is already on the roadmap, but do you have a rough idea of when we can see the Progressive Web App template?

I ask this because I am trying to choose a framework for a large SPA and am torn between many options. The only thing holding back Quasar is its size, which could take a while to load on poor WiFi networks. I really like its functionality though, especially all of the utility methods.

However, I will not be making use of the mobile wrappers as I believe that a PWA will keep more users than having to download an app, so the app will only ever be loaded as a website.

What loading time issues should I be aware of and what can I do to minimise them?

Many thanks for making an awesome library,
--Matthew

**Comment by rstoenescu** [comment]
Hi, please use forum for questions. Currently working on v0.14 which will make Quasar tree shakable, so smaller size. You can take a look at the progress here: http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list

**Comment by mstaack** [comment]
@matthewpull i am working on an spa app right now...its really fast when you  run quasar build and everything is  minimize...shouldn't be your problem

**Comment by matthewpull** [comment]
@mstaack Thanks for the tip :)
If it's really fast now then it should be lightning fast with tree-shaking.
