### ISSUE TITLE
QTable with VirtualScroll

### ISSUE THREAD

**Issue by jesusvilla** [quasarframework/quasar#5120]
**Is your feature request related to a problem? Please describe.**
When you have many records in the `QTable`, and then you select in 'all' rows per page, this becomes very slow.

**Describe the solution you'd like**
There is the VirtualScroll table type but it would be convenient not to lose all the functionality offered by `QTable`. I think that when the user defines all rows to be displayed on a single page, he should use VirtualScroll.

**Describe alternatives you've considered**
I am preparing this, but I don't know if it will be used that way, or it is better to define the behavior of the `QTable` by adding a `virtual` property or something.

**Comment by 1001v** [comment]
Virtual property would be nice.

**Comment by jesusvilla** [comment]
Here it is: #5127. Adding 'virtual' property to enable virtual-scroll in `QTable` does not work with the `grid` mode or with the slots: `top-row` and `bottom-row`

**Comment by rstoenescu** [comment]
Closing as this will be available in "quasar" v1.2.0.
