### ISSUE TITLE
Uploader drag-and-drop issue

### ISSUE THREAD

**Issue by udoewich** [quasarframework/quasar#5121]
**Describe the bug**
With the Uploader component in single file mode, a second drag-and-drop operation is allowed but results in "TypeError: this.__getFileInput(...) is undefined".

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/udoewich/pen/aboPobY

**To Reproduce**
1. Drag-and-drop an image onto the Uploader
2. Drag-and-drop a second image onto the Uploader
3. See the console for the error message

**Expected behavior**
Either block the second attempt, or replace the file waiting to be uploaded.

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this!
Fix will be available in "quasar" v1.1.3.
