### ISSUE TITLE
Re-Bump / Flicker (ios) on Containered Dialog / Help needed ?

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5123]
Sorry, dear Raz and Dan,

my intention is no to double / dribble a known Bug-Issue, its a way / offering for help on a (for us) mayor Problem:

https://github.com/quasarframework/quasar/issues/4391
https://github.com/quasarframework/quasar/issues/4127

We are going close to public with our Plattform and we are gapping some Features (Messaging , Content-Creation, ...) with a Dialog for not destroying the current Listview for the customers. 
So this Dialog is a really importing and scrolling inside this dialog is a mess (in my earlier Bug-Issue i have a video of whats happening) ..

We are pixel-postioning all kind of UI things - to get a great customer experience, but when he goes into the modules .. its flickering .. and not the best reference.

What can i (we) do for making here some process ? .. If you say : okay .. this will be at it is (flickering) may we go a other way .. (but also tabs etc. are flickering .. so its the problem global) ..

Can you make some example codes for cross-testing (if recap of the problem on ios is the problem) or what can we do?

Best and warm greetins from the developer-front

**Comment by ibrainventures** [comment]
on ios13 there were inside the changenotes some points:

https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes

**Comment by rstoenescu** [comment]
Hi,

Please let's not duplicate tickets. It makes things worse for triage. Let's talk on those already opened tickets instead. Thanks.
