### ISSUE TITLE
QLayout and infinite drawer open/close

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#5124]
**Describe the bug**
The left drawer gets into a repeated close/open toggle when the browser window is sized down.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar-drawer-bug-report.netlify.com

**To Reproduce**
1. Go to https://quasar-drawer-bug-report.netlify.com
2. Size your browser fairly tall and wide enough to show the left drawer
3. Slowly make the browser width smaller until the left drawer closes and causes a vertical scrollbar on the browser at the same time and then the drawer gets stuck opening and closing.

**Expected behavior**
Drawer to stay closed

**Screenshots**
Video here: https://quasar-drawer-bug-report.netlify.com/statics/Untitled.mov

**Platform (please complete the following information):**
Quasar:  1.1.3
OS: mac
Browsers: chrome

**Additional context**
Layout code: https://github.com/quasarframework/quasar/blob/dev/docs/src/layouts/gallery/youtube.vue

Index.vue code:
```
<template>
  <q-page>
    <div class="bg-purple" style="height: 300px"></div>
    <div class="q-px-md">
      <div v-for="(i, index) in rows" :key="i">
        <header>
          <h1 class="text-h5 text-weight-medium">Row</h1>
        </header>

        <div class="flex q-gutter-sm q-pa-sm">
          <article
            v-for="n in 7" :key="n"
            style="height: 113px; width: 200px"
            class="flex items-center justify-center bg-grey"
          >
            16/9 PLACEHOLDER
          </article>
        </div>
        <q-separator v-if="index < rows.length-1" class="q-my-md"/>
      </div>
    </div>
  </q-page>
</template>
<script>
export default {
  name: 'PageIndex',
  data () {
    return {
      rows: ['One', 'Two']
    }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Hi,

Fix will be available in "quasar" v1.4.4.
Thanks for reporting!
