### ISSUE TITLE
[docs] How to make max for q-input type number

### ISSUE THREAD

**Issue by pc-mon** [quasarframework/quasar#5128]
hello 
thank you guys for this great work
I just ask about max number of input 
such if I have a shopping cart and I just have 400 pcs of goods, I don't want custommer to write more than 400
thank you

**Comment by pc-mon** [comment]
I'm looking to make it such like this if possible 
`<input type="number" name="quantity" min="1" max="5">`
I've tried max attrabitude but doesn't work

**Comment by smolinari** [comment]
The `min` and `max` of a number input doesn't stop the user from putting in a larger or smaller number. It stops them from "keying" the number up or down above or below those values. If you want to definitely make sure of the input being inside those values, you'll need to build out some validation. See here. You can enter a bigger number than 10, for instance, but if you use the arrow keys up or down, it will stop the number from going over 10.

https://codepen.io/smolinari/pen/XWroYBq?editors=1010 

Also, in general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by mncoldsmoke** [comment]
@smolinari This **is** a bug.

**Comment by mourad1081** [comment]
I do it via `@update:model-value`. 

Example: 


```vue

const val = ref()

<q-input
  v-model.number="val"
  @update:model-value="ensureValLimits"
/>
             
...

function ensure_amount_is_within_limits(value) {
  if (value < myMin) {
    val.value = myMin;
  }
  else if (value > myMax) {
    val.value = myMax;
  }
}
```
