### ISSUE TITLE
QInput - Add "red star" to indicate it is a required field

### ISSUE THREAD

**Issue by 549393092** [quasarframework/quasar#5129]
Dear Quasar team,

Sincerely hope that you could add this feature.
https://forum.quasar-framework.org/topic/4222/solved-v1-qinput-how-to-add-red-star-to-indicate-it-is-a-required-field

Best Regards,
Stanley

**Comment by pdanpdan** [comment]
You can very easily solve it with CSS:
https://codepen.io/pdanpdan/pen/LYPqEQL

**Comment by 549393092** [comment]
It's cool. Thanks a lot!

**Comment by smolinari** [comment]
Hello Stanley,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for (further) questions. 

Thanks. 😄 

Scott

**Comment by metalsadman** [comment]
> Hi pdanpdan,
> 
> Could you please give a SASS version?
> In addition, is it possible to add red star for table column label?
> Thanks a lot for your help.

``` sass version
.q-field__native[required] ~ .q-field__label:after
  content: '*'
  color: red
```

**Comment by emirozmen07** [comment]
> > Hi pdanpdan,
> > Could you please give a SASS version?
> > In addition, is it possible to add red star for table column label?
> > Thanks a lot for your help.
> 
> ```sass
> .q-field__native[required] ~ .q-field__label:after
>   content: '*'
>   color: red
> ```
> 
> For your 2nd question, same concept, or use header slot and override how you display your th's.

This works but it shows asterisk on the select fields even when they are `:required="false"`

**Comment by metalsadman** [comment]
> > > Hi pdanpdan,
> > > Could you please give a SASS version?
> > > In addition, is it possible to add red star for table column label?
> > > Thanks a lot for your help.
> > 
> > 
> > ```sass
> > .q-field__native[required] ~ .q-field__label:after
> >   content: '*'
> >   color: red
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For your 2nd question, same concept, or use header slot and override how you display your th's.
> 
> This works but it shows asterisk on the select fields even when they are `:required="false"`

:required="condition ? true : void 0"

**Comment by emirozmen07** [comment]
> > > > Hi pdanpdan,
> > > > Could you please give a SASS version?
> > > > In addition, is it possible to add red star for table column label?
> > > > Thanks a lot for your help.
> > > 
> > > 
> > > ```sass
> > > .q-field__native[required] ~ .q-field__label:after
> > >   content: '*'
> > >   color: red
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For your 2nd question, same concept, or use header slot and override how you display your th's.
> > 
> > 
> > This works but it shows asterisk on the select fields even when they are `:required="false"`
> 
> :required="condition ? true : void 0"

Thanks! Also it wasn't appearing in the QCheckbox, so i created the one below for the checkbox:

```
.q-form-checkbox[required="true"] .q-checkbox__label:after
  content: ' *'
  color: red
```

Note that i add a class name to my checkbox, so i can separate my form checkbox from other checkboxes
`class="q-form-checkbox"`
