### ISSUE TITLE
This relative module was not found:  * ./client-prefetch.js in ./.quasar/client-entry.js

### ISSUE THREAD

**Issue by oldmember** [quasarframework/quasar#5130]
**Describe the bug**
Hi, 
I got above error when adding **preFetch: true** to quasar conf file.

**Screenshots**
https://i.imgur.com/CIsIQwf.png

**Platform (please complete the following information):**
OS: Windows x64
Node: 10.16.3
NPM: 6.9.0

How to fix it ?

**Comment by rstoenescu** [comment]
Hi,

Please use the genuine terminal/console instead of your IDE. The terminal from IDEs inject some paths and do some additional things which can break the usage of the CLI..
