### ISSUE TITLE
QMenu not re-rendering on data scope change

### ISSUE THREAD

**Issue by msm4net** [quasarframework/quasar#5131]
**Describe the bug**

Using quasar 1.1.3:

q-toggle or q-checkbox does not update visible state when changing its model either using v-model or :value/@input combination when used inside a q-menu

**Codepen/jsFiddle/Codesandbox (required)**

N/A

**To Reproduce**

Go to q-menu quasar 1.1.3 documentation, and see section of Basic -> Idea for content

Inside q-menu there are two toggles that don't update its visible state

**Expected behavior**

A q-toggle or q-checkbox should update its visible state when used inside a q-menu, as it was with quasar 1.0.5 - 1.1.0

**Platform (please complete the following information):**
OS: Ubuntu 18.04 / Windows 10
Node:8.15.0
NPM:6.4.1
Yarn:N/A
Browsers:Chrome desktop browser Versión 71.0.3578.98 (Build oficial) (64 bits)
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix available in "quasar" v1.1.4
