### ISSUE TITLE
Q-Drawer glitch with scrolling

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#5138]
**Describe the bug**
 I dunno if it's a known glitch, but also in the layout builder with simple layout it happens. I made a codepen to fix this I have to set overflow to hidden to .scroll inside .q-drawer **(__content)** that by default is set on auto.
Here's a [video](https://streamable.com/6v77e) to see the glitch

**Codepen**
https://codepen.io/dariodepaolis/pen/KKPJoPq 

**To Reproduce**
1. Go to layout builder
2. Create a simple setup with a left drawer
3. Scroll up & down to reproduce the glitch
4. See the video and the pen to understand better

**Expected behavior**
Overflow must be hidden on q-drawer__content to hide the native scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/6792464/65495999-eee6df00-deb7-11e9-9898-7e935bdedc29.png)

**Platform (please complete the following information):**
OS: Mac OS Mojave 10.14.6
Node: 10.15.3
NPM: 6.4.1
Browsers: Chrome 76

**Comment by pdanpdan** [comment]
Looks like it's fixed in the current versions (1.8.5 at least).
