### ISSUE TITLE
Hex color prop for Chip

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#5141]
**Is your feature request related to a problem? Please describe.**
I want use own hex colors for Chips, cause YandexMap placemarks accepts only hex colors. Now i need to map quasar color pallete to hex and it is dirty approach.

**Describe the solution you'd like**
`<q-chip color="#000000" />` or `<q-chip :color="'#000000'" />`

**Comment by rstoenescu** [comment]
https://codepen.io/rstoenescu/pen/ZEzNEbL?&editable=true&editors=101

```js
<q-chip icon="event" size="10px" style="background: #ff0000">Add to calendar</q-chip>
```

**Comment by ncutt010** [comment]
> https://codepen.io/rstoenescu/pen/ZEzNEbL?&editable=true&editors=101
> 
> ```js
> <q-chip icon="event" size="10px" style="background: #ff0000">Add to calendar</q-chip>
> ```

Wondering how hard this would be for the `color` props to accept a hex value as well?  Coming from Vuetify, it is major annoyance that hex values need to be used via the `style` attribute.  If I get time, I can write an PR for this.  Shouldn't be too hard

**Comment by Ekscentricitet** [comment]
Is there any progress on this? I also come from Vuetify and this is annoying.
