### ISSUE TITLE
Better keyboard support for QSelect

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5142]
**Is your feature request related to a problem? Please describe.**
Implement more typical `<select>` keyboard behaviour for `QSelect`.

**Describe the solution you'd like**
1. If an item is highlighted in the options pop-up, <kbd>Tab</kbd> should input the highlighted item. This helps when quickly tabbing through form fields.
2. (if `use-input` is not enabled) <kbd>Space</kbd> should open the options pop-up. This is more consistent with `select` than <kbd>Enter</kbd>. Users may be more apprehensive about pressing <kbd>Enter</kbd>, as it is commonly used to submit forms.
3. Keyboard jumping to options without `use-input`
    1. Type a letter to jump to first option starting with that letter
    2. Type additional letters to further jump to other options (e.g. <kbd>C</kbd>, <kbd>O</kbd> would jump to the first item starting with CO (with timeout to clear the buffer)
    3. Same letter multiple times jumps to next item starting with letter (e.g. <kbd>B</kbd>, <kbd>B</kbd>, <kbd>B</kbd> would jump to third item starting with B.

    This is a pain point compared to a standard `<select>` because you can't quickly jump to an item with keyboard. `use-input` can help but don't always want the overhead of implementing autocomplete filters or hiding items for simple selects. For this one, the type-jumping could possibly happen without even opening the pop-up like a standard `<select>` but it would also be ok if it did open because that's consistent with arrow keys already opening the pop-up (which they do not do in standard `<select>`.

**Describe alternatives you've considered**
Capturing keyboard events with custom logic (it appears `QSelect` emits keyboard events, though this does not appear to be in the docs?).

**Additional context**
`QSelect` is generally awesome! But I do find myself getting tripped up by these.

Codepen to compare `QSelect` with `<select>`: https://codepen.io/gordonblahut/pen/zYOeVYa

**Comment by pdanpdan** [comment]
Native select works in a different way:

- when you do keyboard navigation the option is selected on navigation, not on blur determined by the TAB key
- for letter pressing navigation, there should at least be some way to define in what to search for (native select has the advantage of not having options of what to show :) )

**Comment by GordonBlahut** [comment]
> when you do keyboard navigation the option is selected on navigation, not on blur determined by the TAB key  

Fair enough. Is there a reason `QSelect` doesn't select on keyboard navigation? Performance concern? Maybe I'll see if I can intercept the keycodes/events to get it working the way I want as it does not seem intuitive to select an option and tab out without the value updating.
  
I notice with a native `<select>` that although the display in the select changes immediately on keyboard navigation, the bound v-model itself is still not updated until the element loses focus.

I see the "Enhanced" versions of the [Material Components for the Web Select](https://material-components.github.io/material-components-web-catalog/#/component/select) behaves the same way as `QSelect` on <kbd>Tab</kbd> and doesn't commit the selection. Actually tabbing out with the Material component version completely screws up the focus within the document. That's disappointing. 

The Material Component Select does open/select items on <kbd>Space</kbd>. So that may be worth considering at least.

> for letter pressing navigation, there should at least be some way to define in what to search for (native select has the advantage of not having options of what to show :) ) 
  
I did think this could pose a problem too. Maybe another property of the options that must be a plain string, or using `textContent` on the rendered option? I don't know the performance impact of the latter though and less control for the dev.

**Comment by pdanpdan** [comment]
@rstoenescu 
My opinion on this:

1. for highlighted option selection on <kbd>Tab</kbd> I would say that it might work if it is limited to the following conditions:
  - single selection mode
  - `fill-input` set
  - maybe also `hide-selected` set ??
  - there is an option in the list selected and the selection was done by kdb (not by mouse)
2. <kbd>Space</kbd> to open list when `use-input` is not used should be OK
3. kbd navigation
  - for kbd navigation with options list closed I would say NO WAY :)
  - it would be nice
  - we have to find a way to define in what to search for
  - search should be case insensitive and from the start only
  - I have a problem to understand how native `<select>` decides if a repeated key should go to the next match starting with the same letter or should be added to the search buffer as a new letter

**Comment by metalsadman** [comment]
maybe it's time to spawn other functionalities into their own component imo. atm qselect has quite a huge api, it's doing so much. maybe QSelect, as the name suggest should just do what a native select does, while others into autocomplete etc...

**Comment by smolinari** [comment]
Or, maybe make a "master prop" like `type`, where it requires an object of the necessary sub-props required for that type. That will kind of help the user in feature selection. I'm thinking like

single, multiple, autocomplete, etc. etc.

Theoretically, the list of sub-props in a `type` prop would be fewer than needed without the `type` prop too,  as the intended functionality is then clear and thus a given. 

Just brainstorming here. 😄 

Also, with this direction, we won't break the current API and it would only add one more prop. 

Again, just thinking out loud. I do realize that is a lot easier said than done.😊 

Scott

**Comment by smolinari** [comment]
https://github.com/quasarframework/quasar/issues/5157

Scott

**Comment by marcelo-rebello** [comment]
IMHO An HTML5 like select component focus on ease of use would be an awesome addon to Quasar.
QSelect is too complex now and with LOTS of performance improvements, which is good.
But you also have space for some simple components that just do the basics...
Maybe a QBasicSelect that mimics HTML5 with build-in filter/option groups/keyboard navigation would be awesome!

**Comment by pdanpdan** [comment]
Please don't polute this issue with unrelated comments.
