### ISSUE TITLE
Pressing 'Esc' in a `QSelect` with options pop-up open inside `QDialog` also dismisses the dialog

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5143]
**Describe the bug**
Pressing <kbd>Esc</kbd> in a `QSelect` with options pop-up open inside `QDialog` also dismisses the dialog.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gordonblahut/pen/WNePqYd

**To Reproduce**
1. Click on 'Open dialog'
2. Click on the `QSelect` inside the dialog so that the options pop-up opens
3. Press <kbd>Esc</kbd>
4. The `QSelect` pop-up closes and the dialog is dismissed at the same time

**Expected behavior**
If the `QSelect` pop-up is open, I would expect the first <kbd>Esc</kbd> to close the `QSelect` pop-up only, and a subsequent <kbd>Esc</kbd> to dimiss the dialog. If the `QSelect` is focused but the options pop-up is not open, then the first <kbd>Esc</kbd> would dismiss the dialog. Basically once something handles an <kbd>Esc</kbd> it should not traverse to higher levels.

**Platform (please complete the following information):**
v1.1.4 on Codepen

**Additional context**
This may be intended behaviour? On the other hand if a dialog opens another dialog, <kbd>Esc</kbd> only dismisses the inner-most dialog, which makes sense.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fix will be available in "quasar" v1.1.5
