### ISSUE TITLE
Horizontal q-tab-panels

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5144]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to request horizontal q-tab-panels. So that the tab selection bar is not _on top_ of the panels, but _to the left_ of the panels.

**Describe alternatives you've considered**
Writing a plugin! But I'm not so confident about this one :D
Also, I always feel, if I write a plugin I'd only help myself. It's hard to really get it out there, have people know about it and use it and spend time marketing the plugin.

**Additional context**
example:
![2019-09-25 10 25 11](https://user-images.githubusercontent.com/3253920/65561806-caa20580-df7e-11e9-9110-37bf9b431be3.gif)

**Comment by pdanpdan** [comment]
I don't understand the request. https://quasar.dev/vue-components/tabs#Example--Vertical-(example-with-QSplitter)

**Comment by mesqueeb** [comment]
@pdanpdan I see!
I was searching in the Tab Panels documentation:
https://quasar.dev/vue-components/tab-panels

Completely overlooked that that feature was explained in the regular "Tabs" page...

Since this is more of a "Tab Panels" feature, shouldn't we move that into that page?

Thanks either way!
