### ISSUE TITLE
[Docs] Theme Builder colour picker loops class adjustments

### ISSUE THREAD

**Issue by khionu** [quasarframework/quasar#5145]
**Describe the bug**
At 160% zoom on a 1080p screen, the colour picker on the [theme builder page](https://quasar.dev/style/theme-builder) loops though adjusting some alignment

**To Reproduce**
1. Go to https://quasar.dev/style/theme-builder
2. Click on any of the colour pickers
3. Observe

**Screenshots**
![](https://files.khionu.net/ss/2019-09-24_22-39-08.gif)
![](https://files.khionu.net/ss/2019-09-24_22-42-57.gif)

**Platform (please complete the following information):**
OS: Windows 10 Pro x64
Browsers: Firefox 69.0.1

**Additional context**
The issue does not exist at zooms lower than 160%

**Comment by khionu** [comment]
(If someone knows how to make those embeds smaller, I would appreciate it)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.3.1 (thanks to @ejez).

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.2
