### ISSUE TITLE
QTable grid mode cant't showing the header even hide-header=false

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar#5147]
**Describe the bug**
QTable grid mode cant't showing the header even hide-header=false

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Can you please describe the problem?

**Comment by zknic** [comment]
![QQ图片20190925145250](https://user-images.githubusercontent.com/11263870/65576254-2cc13180-dfa4-11e9-8bfd-91d5c80df5c4.png)

**Comment by pdanpdan** [comment]
What header would you want? You have no columns in grid mode, so you cannot have header columns for the non-existing columns.

**Comment by zknic** [comment]
![QQ图片20190927103730](https://user-images.githubusercontent.com/11263870/65737981-d9212600-e112-11e9-83c8-a8d0b6cfaf1d.png)

**Comment by rstoenescu** [comment]
This was removed on purpose due to some problems.
But now it's ready to have a comeback.

Will be available in "quasar" v1.1.6 through Boolean prop "grid-header".
