### ISSUE TITLE
QDate flat mode

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5148]
Not critical.

Would be nice for QDate to support flat mode similar to other components. Currently box-shadow is applied by default.

In my example box shadow is applied to both q-popover and q-date
![Screen Shot 2019-09-25 at 10 17 53 AM](https://user-images.githubusercontent.com/3635352/65578059-c2959600-df7d-11e9-9e81-8b08264738d8.png)

**Comment by smolinari** [comment]
You can wrap QDate or QTime in a QCard and give the QCard the styles you are asking for. 

https://codepen.io/smolinari/pen/dybrNmb

Scott

**Comment by jean-moldovan** [comment]
Thanks. Please feel free to close this request if you think adding `flat` prop does not have much value.

**Comment by smolinari** [comment]
Not saying there isn't any merit in the suggestion. Just trying to help with a solution. 😄 

Scott

**Comment by pdanpdan** [comment]
Just add `class="shadow-0 no-border-radius"` (use both classes or only what you need) on QDate.

**Comment by rstoenescu** [comment]
flat/bordered/square props for QDate/QTime will be available in v1.1.5.
