### ISSUE TITLE
Floating Action Button not appearing on IE11

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#5149]
**Describe the bug**
On the Quasar docs website, there are examples of floating action buttons. The simple ones are invisible as seen on the picture. As a quickfix, we can use the fab property of q-btn for now.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/layout/floating-action-button

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17769074/65582129-0e940b00-df7d-11e9-97cc-3aa45e400ce9.PNG)

**Platform :**
I am using Internet Explorer 11 (11.356.18362.0) on Windows 10

**Comment by pdanpdan** [comment]
That example uses QLayout as container, and that is not supported in IE11.
In in normal use case (QLayout in non-container mode) it would work.
