### ISSUE TITLE
QDrawer (no-swipe-close from outside a drawer content)

### ISSUE THREAD

**Issue by titanlizard** [quasarframework/quasar#5150]
**Is your feature request related to a problem? Please describe.**
A QDrawer can be closed from outside the drawer content by click or swipe gesture. Closing by click can be sometimes very frustrating. Click event is not always fired, because there may occur small vertical movement at the same time.

**Describe the solution you'd like**
Provide a new property (_no-swipe-close-outside_) to prevent swipe-close initiated from outside the drawer content.

**Additional context**
https://codepen.io/titanlizard/pen/yLBwXBb

**Comment by rstoenescu** [comment]
Hi,

Thanks for proposing this.
Boolean prop "no-swipe-backdrop" will be available in "quasar" v1.1.7.
