### ISSUE TITLE
Issues with QInput when type="file"

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#5151]
**Describe the bug**
When QInput is used with type="file" a button is displayed with "Choose File". However, clicking anywhere on the QInput will bring up the file selection dialog.

This causes an issue is you use the "clearable" property because if you try to click the "clear" icon, the file selection dialog is then displayed.

Here is a codepen
https://codepen.io/Hawkeye64/pen/vYBbwpv?&editable=true&editors=101

Note, I can not get the "clear" icon to show using "clearable" in the codepen.

![image](https://user-images.githubusercontent.com/10262924/65601849-1ee9bd00-df60-11e9-857f-66218dc47609.png)

**To Reproduce**
1. Click anywhere on the QInput, except the "Choose File" button
2. The file selection dialog is displayed

**Expected behavior**
Only if the "Choose File" button is clicked should the file selection dialog be displayed.

**Comment by hawkeye64** [comment]
It just occured to me that the reason the "clear" icon is not showing up is because the icon font is missing from the codepen. Regardless of that, the click issue is still valid.

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.5.
