### ISSUE TITLE
Add @clear event to QInput and other clearable components

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5153]
**Is your feature request related to a problem? Please describe.**
The request is rather simple: Add a new @clear event to components that implement the _clearable_ attribute.

My use case is that I use `value` property instead of `v-model`, and I implemented hooks for `@blur` and `@keyup.enter`, but would also like to capture the `@clear` event, instead of  having to use the `@input` event which triggers on each keystroke (in case of QInput).

```
@blur="evt => onCustomChanged(evt.target.value)"
@keyup.enter="evt => onCustomChanged(evt.target.value)"
@clearr="onCustomClear"
```
**Describe alternatives you've considered**
As Tobias suggested in _patreons-help-only_ discord channel, I can alternatively use
```
<q-input :value="model" ref="input" label="Type here">
  <template v-slot:append>
    <q-icon class="cursor-pointer" :icon="$q.iconSet.field.clear" @click="clearInput" />
  </template>
</q-input>

export default {
  methods: {
    async clearInput () {
      this.value = ""
      await this.$nextTick()
      this.onQInputChanged(this.value)
    }
  }
}
```

**Comment by TobyMosque** [comment]
#5140 already implemented.

**Comment by tomers** [comment]
Thanks! You guys are such a great developer team!
