### ISSUE TITLE
Remove compression middleware from dist/ssr/package.json if not required

### ISSUE THREAD

**Issue by streof** [quasarframework/quasar#5154]
**Is your feature request related to a problem? Please describe.**
After removing the compression middleware from `src-ssr/index.js` I saw that express does not perform gzip compression any more (as expected). However, after building my project, I noticed that the compression middleware is still included into `dist/ssr/package.json` although none of the files under `dist/ssr` requires it anymore.

**Describe the solution you'd like**
It would be nice if quasar automatically detects whether the compression middleware is required or not instead of including it into `dist/ssr/package.json` by default. 

**Describe alternatives you've considered**
I'm aware that it is possible to remove packages from the vendor chunk (as described [here](https://quasar.dev/quasar-cli/quasar-conf-js#Options-to-Configure)), but this will only remove the package during the quasar build. In production I only use the files from `dist/ssr` and install the required packages using yarn.

An alternative would be to remove the line containing the compression middleware from `dist/ssr/package.json` in my Dockerfile which is definitely possible but not a very elegant solution in my opinion.

**Additional context**
In my case, the compression is carried out by a load balancer

**Comment by rstoenescu** [comment]
In "@quasar/app" v1.9.5 you'll be able to add/remove/change anything from the production generated package.json through quasar.conf.js > ssr > extendPackageJson (pkg)
