### ISSUE TITLE
Responsive breakpoints relative to a container

### ISSUE THREAD

**Issue by HenriqueSPin** [quasarframework/quasar#5156]
Sometimes we face situations where you need a responsive layout, but instead of using the viewport as the root for breakpoint calculations, we need it to be relative to the container.

E.g.: A QSplitter, each side with a grid of its own. As we resize the splitter columns, the contents of each respects the xs, sm, md, lg, xl breakpoints relative to the column container.

My suggestion is that we have a "QResponsiveContainer" that force every breakpoint related classes nested into it to react to its container dimensions instead of viewports dimensions.

Here are an example of this already working:
https://philipwalton.github.io/responsive-components/

**Comment by rstoenescu** [comment]
Hi,

Use containerized QLayout. https://quasar.dev/layout/layout#Containerized-QLayout
