### ISSUE TITLE
QPopupEdit - add "before-show" and "before-hide" events

### ISSUE THREAD

**Issue by snoop31** [quasarframework/quasar#5160]
**Is your feature request related to a problem? Please describe.**
I think quasar team forgot add "before-show" and "before-hide" events to QPopupEdit.
In some point its so important to have full control on this component.

**Describe the solution you'd like**
```
before-show: () => {
   this.validated = false
    this.initialValue = clone(this.value)
    this.watcher = this.$watch('value', this.__reposition)

    this.$emit('before-show') // Add this line
 }
before-hide: () => {
  this.watcher()
  if (this.validated === false && this.__hasChanged()) {
    this.$emit('cancel', this.value, this.initialValue)
    this.$emit('input', this.initialValue)
  }

  this.$emit('before-hide') // Add this line
}
```
Thanks.

**Comment by smolinari** [comment]
How about making a PR?

Scott

**Comment by snoop31** [comment]
> How about making a PR?
> 
> Scott

U got it 😄 [#5168](https://github.com/quasarframework/quasar/pull/5168)

**Comment by rstoenescu** [comment]
@snoop31 Cool! Thanks for contributing!

This will go into "quasar" v1.1.5.
