### ISSUE TITLE
QInput blur event does not send value properly

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5161]
**Describe the bug**
When defining `@blur="evt => onChanged(evt.target.value)"` to capture blur event, the value received in the callback is empty.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tomers-the-encoder/pen/YzKgYgr?editors=1010

**To Reproduce**
1. Hook `@blur` to a custom callback
2. Initiate blur event
3. Notice in the callback that the value is empty

**Expected behavior**
The value should have the current text in the QInput

**Comment by smolinari** [comment]
Stick with v-model. No need to go to value, as the value will be negated on blur. You can use @input or @change as you like with v-model too. 

https://codepen.io/smolinari/pen/OJLGMzO?editors=1010

Scott

**Comment by metalsadman** [comment]
@tomers nothing wrong with blur, it's your `@input` handler which has a flawed logic, since you are blocking the assignment to value. see my edit when I commented your `if` block. https://codepen.io/metalsadman/pen/MWgMVGj?editors=1011.

**Comment by pdanpdan** [comment]
`@blur` event does not emit the value, but the target element that was blurred.

**Comment by tomers** [comment]
@metalsadman, my `@input` handler in my real application performs API call, thus I do not want it to be triggered on each keystroke, but only when the focus is lost or the user presses Enter. So although I know I can use `@input` to achieve the model update, as you suggested, this method is not adequate for my requirement of minimizing updates (and I/O calls).

I tried to work this through but couldn't due to this behavior which seems like a bug to me. I will reopen this issue because I think this bit of information is important to understand it. I would be grateful if you could review it again in light of this information.

**Comment by pdanpdan** [comment]
Use a model to keep the value (you can create another variable to keep it) using `v-model` / `:value`+`@input` and only perform the action on `@blur` / `@keyup.13`
