### ISSUE TITLE
QInnerLoading does not cover the menu inside an object that is masked by it

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5162]
**Describe the bug**
As title says.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tomers-the-encoder/pen/rNBbOMp?&editable=true&editors=101

**To Reproduce**
1. Cause QInnerLoading to show from a menu item inside a component that is covered by the inner loading.

**Expected behavior**
I think the expected behaviour is that the spinner should cover the menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/83443/65685532-da971380-e06a-11e9-9be5-fbfe7322fcb6.png)

**Comment by rstoenescu** [comment]
Hi @tomers 

It works as expected. Covers the parent. But QMenus are not part of the same DOM tree as its parent (for a billion reasons). Best is to also close the menu. Will supply more details if needed.
