### ISSUE TITLE
[docs] Improve readability of docs, for developers

### ISSUE THREAD

**Issue by stevebor1** [quasarframework/quasar#5165]
First of I would like to say that the docs section looks extremely beautiful and the style guide is just about the cleanest that I have seen, however, as a developer, this version is super tuff to consume and quickly gain knowledge versus the pre 1 docs.

Please take my criticism constructively :)

1. Docs is a long, scavengerous read.
2. Source, configuration, event and examples are all hidden and require the user to actively select or tab though visible panes.

**What I absolutely loved with pre 1 docs**

1. Demo and Docs/Specs were on **separate pages**
2. Docs provided **visible** component code sample (HTML, Vue, Vuex)
3. Props, Events, Methods where clearly **listed** out and not hidden
4. Many code samples were included at the end of the docs.

I have been developing for a long time and with the help of the pre 1 docs, I have been able to whip up new apps insanely fast. My goal is to do the same with the v1 release, with upgrading and implementing new apps, as fast as I did before. Thanks again @rstoenescu !

**Comment by rstoenescu** [comment]
Hi,

Thanks for the feedback. Will take into account.
