### ISSUE TITLE
QBtnDropdown split button and border radius

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#5166]
**Describe the bug**
When I use a `q-btn-dropdown` with `stretch` the button has no border radius, which is what I expect, but if I use `stretch split` the additional button used for the arrow has a border radius set on the right when I expected it to remain square. Is this a bug or intentional?

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/smakinson/pen/xxKedjL?editors=1010

**To Reproduce**
Quasar v1.1.4

**Comment by smakinson** [comment]
`:rounded="false"` doesn't seem to affect it, but I can override the styles.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in "quasar" v1.1.6.
