### ISSUE TITLE
Support Electron v6.*

### ISSUE THREAD

**Issue by bestog** [quasarframework/quasar#5172]
**Is your feature request related to a problem? Please describe.**
I cannot upgrade the electron dependency from 5.* to 6.* 
If I have updated to the 6.0 version and want to start the electron app, no window appears.
To use the latest feature of electron in quasar I need the 6.0 version.

Thank you.

**Comment by webnoob** [comment]
I've tested this locally and it's working without issue. As discussed in DM, try purging node_modules and yarn.lock then `yarn` and see if it's still an issue.

**Comment by hawkeye64** [comment]
@bestog Pinging for results...is this still an issue?

**Comment by rstoenescu** [comment]
@bestog Just upgrade "electron" dep in your project folder.

**Comment by bestog** [comment]
@hawkeye64 @webnoob @rstoenescu Thank you for your support. 

i emptied the node_modules folder and reinstalled it with yarn. and now it worked. =)

**Comment by rstoenescu** [comment]
Waiting on this issue to be fixed upstream in Electron before installing Electron v6 by default: https://github.com/electron/electron/issues/19468

**Comment by bestog** [comment]
Thanks @rstoenescu, for the matching issue from the Electron project.
Can reproduce it on my Win10 (dark mode). Tested on a Mac 2 days ago.
I'm waiting for Electron's fix before I upgrade to Electron 6.
