### ISSUE TITLE
QPopupEdit style props have no effect

### ISSUE THREAD

**Issue by jblyberg** [quasarframework/quasar#5173]
**Describe the bug**
The offset and color style props seem to have no effect with the QPopupEdit components.

**Codepen/jsFiddle/Codesandbox (required)**
Here's an example of the problem reproduced: https://codepen.io/jblyberg/pen/bGbJZzB

**Expected behavior**
Popup box should be offset 10x10 px and be red

**Platform (please complete the following information):**
All

**Comment by rstoenescu** [comment]
Hi,

https://codepen.io/rstoenescu/pen/GRKaKYY
