### ISSUE TITLE
Qtabs to auto slide to selected tab if selected tab is not visible because of a set width

### ISSUE THREAD

**Issue by amack2u** [quasarframework/quasar#5174]
Feature Request/Maybe bug?
Horizontal Qtabs to auto slide to selected tab if selected tab is not visible because of a set width...
For example:
 If its showing only 4 tabs because you have a width of 400px and the route changes causing the 5th tab to be selected.

expected behavior:
It should slide/scroll to position making selected tab visible

**Comment by rstoenescu** [comment]
Hi,

It's already doing this??

**Comment by amack2u** [comment]
Hello,
For me it is not i have to hit the right arrow to see the selected tab. Could i be doing something wrong?

**Comment by rstoenescu** [comment]
Hi,

I rechecked. It's working correctly. So most likely it's a problem with your usage.
Please visit our https://forum.quasar.dev or https://chat.quasar.dev to seek for help.
