### ISSUE TITLE
[Question] how to use QPopupProxy in script?

### ISSUE THREAD

**Issue by kawais** [quasarframework/quasar#5175]
the code in vue file like this, how to write in script? I want to show a popup after click a button.
```
          <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
            <q-date v-model="date" @input="() => $refs.qDateProxy.hide()" />
          </q-popup-proxy>
```

**Comment by smolinari** [comment]
Hi,

https://quasar.dev/vue-components/popup-proxy

You just make QPopupProxy the child of the button. See first example. 

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
