### ISSUE TITLE
Add Style Label outlined for q-input

### ISSUE THREAD

**Issue by 9223000** [quasarframework/quasar#5176]
It would be nice to be able to make such a Label display style for q-input
![img-2019-09-28-19-10-25](https://user-images.githubusercontent.com/12157862/65817695-ea0d8c80-e223-11e9-9175-115576563260.png)

**Comment by 9223000** [comment]
This style is here:
https://vuetifyjs.com/ru/components/text-fields

**Comment by smolinari** [comment]
This is already an issue. 

https://github.com/quasarframework/quasar/issues/3262

Scott
