### ISSUE TITLE
Date Picker with QInput and Font Awesome Pro

### ISSUE THREAD

**Issue by jimcreate78** [quasarframework/quasar#5177]
**Describe the bug**
There's a artifact "-->" and the proxy popup is broken when using the Date Picker with QInput and Font Awesome Pro.  The same code functions normally when using the Material icons.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/kpntxco1/1/
_* I couldn't load FontAwesomePro in the framework.iconSet of the fiddle_

quasar.conf.js
```
framework: {
      iconSet: 'fontawesome-v5-pro',
}

```
**To Reproduce**
1. Configure the fontawesome iconSet in quasar.conf.js
2. Copy the code from fiddle into your local
3. Load the code and you'll see a "-->" artifact in the first input and the popup won't work.
4. In the second input you'll see it works as expected.

**Expected behavior**
The first input should behave like the second input.

**Screenshots**
![image](https://user-images.githubusercontent.com/10968908/65818333-83598600-e1c5-11e9-8c6b-0418cac598be.png)

**Platform (please complete the following information):**
Pkg quasar........ v1.1.5 (issue experienced in earlier versions)
Pkg @quasar/app... v1.1.2
OS: Windows
Node: v10.16.3
Yarn: 1.13.0
Browsers: Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
Hi,

There's no reason from within Quasar that this would break.
Here's an example with non-pro version: https://jsfiddle.net/rstoenescu/pbzy20xk/3/

From the looks of it, I'd say you have an error in your template...

**Comment by rstoenescu** [comment]
Also note that the icon you are using is not part of the icon-set... cause it doesn't comes with the framework -> you're specifying by hand in your template.

Have you also loaded the fontawesome pro icon lib into your app? Maybe you are confusing icon-sets with installing an icon lib. 

https://quasar.dev/options/installing-icon-libraries

https://quasar.dev/options/quasar-icon-sets

Please reopen if I missed something.

**Comment by jimcreate78** [comment]
In the documentation I can only add it as a iconSet.  I get the following error when trying to add it in the extra's area as 'fontawesome-v5-pro'...

client?f1f8:159 ./.quasar/client-entry.js
Module not found: Error: Can't resolve '@quasar/extras/fontawesome-v5-pro/fontawesome-v5-pro.css' in 'C:\Users\jimhi\documents\reviews\frontend\.quasar'

**Comment by jimcreate78** [comment]
@rstoenescu I resolved the issue.  In another area someone said to use fontawesome-pro put the 
following in a boot file...
```
import '@fortawesome/fontawesome-pro/js/all.min'
```

The code above actually causes that issue.  The resolution was to use the following in the boot file...
```
import '@fortawesome/fontawesome-pro/css/fontawesome.css'
import '@fortawesome/fontawesome-pro/css/light.css'
```

**Using the fontawesome js file instead of css works fine in many cases but here it is a problem**

**Comment by rstoenescu** [comment]
Don't. Just import the css files from it.
Glad it worked out.
