### ISSUE TITLE
QBtnToggle fires no 'input' event when readonly="undefined"

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5179]
**Describe the bug**
adding `:readonly="undefined"` to q-btn-toggle prevents the `input` event from being fired. While `:readonly="false"` works as expected.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mesqueeb/pen/LYPoxJX?&editable=true&editors=101

**Expected behavior**
Have the `input` event still fire even though `:readonly="undefined"`

**Platform (please complete the following information):**
OS: macOS
Browsers: chrome

**Comment by smolinari** [comment]
For my curiosity, why are you sending undefined into a boolean prop or rather, why should the component care you might do that?

Scott

**Comment by rstoenescu** [comment]
I totally agree with @smolinari on this one.
But since there's no perf penalty involved to make it work and it's quick to change it, I'm letting it slide this time :)

**Comment by rstoenescu** [comment]
This will go into "quasar" v1.1.6.

**Comment by mesqueeb** [comment]
@rstoenescu @smolinari Thanks for the fix and your messages.
As for the reason:
In a certain vue file I'm attaching Quasar props dynamically via `v-bind`. I'm providing certain keys for props in the object I'm passing to `v-bind`, but do not want to set a default value for them to make sure Quasar will still use its default value.
Eg.
```
v-bind="{readonly: undefined, disable: undefined}"
```
I could of course pass `false` as default value, but the dynamic props go beyond just those I listed above, and I don't want to have to check the documentation each time for which default prop I should pass.

I hope you understand my reasoning ;)
