### ISSUE TITLE
Material Design Icons: do not use ligatures in quasar components

### ISSUE THREAD

**Issue by aleksanderzubkov** [quasarframework/quasar#518]
On old android devices with standard browser (not Chrome) ligatures supported badly and icon results are unpredictable.

So it's preferable to use numeric character references in quasar components.

For example, Toast should use `<i>&#xE5CD;</i>` in place of `<i>close</i>`.

**Comment by aleksanderzubkov** [comment]
Also: 
- `keyboard_arrow_down` replace to `&#xE313;`
- `keyboard_arrow_right` replace to `&#xE315;`

**Comment by rstoenescu** [comment]
Will do. Only thing is that it makes Quasar components templates harder to reason about. Care for a PR on v0.14 branch?

**Comment by aleksanderzubkov** [comment]
Yes. Will do.

**Comment by aleksanderzubkov** [comment]
q-icon supports numeric character references?

**Comment by rstoenescu** [comment]
Yes. QIcon supports that.

**Comment by rstoenescu** [comment]
Pushed commit for this.

**Comment by rstoenescu** [comment]
Seems like by using the numeric character references the icons don't display right on desktop Chrome (just an example). In my quick investigation it seems that replacing any of the icons on their [documentation website](https://material.io/icons) with num char ref is also not working. Am I missing something?
Reverting PR until this gets figured out as it currently breaks the framework.
