### ISSUE TITLE
[v1.1.5][QSelect] Options menu popup raises virtual-scroll event when shown

### ISSUE THREAD

**Issue by adamborys** [quasarframework/quasar#5181]
**Describe the bug**
After clicking on QSelect the options menu popup is shown and the popup-show event is raised. Regardless of whether all options are displayed at once or the scroll bar is displayed - the virtual-scroll event is raised immediately after popup-show event.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/adamborys-the-flexboxer/pen/RwbmZxR

**To Reproduce**
1. Click on QSelect component
2. Check the console

**Expected behavior**
Only popup-show event is raised.

**Platform:**
OS: Windows 10
Node: 12.9.0
Yarn: 1.17.3
Browsers: Google Chrome

**Comment by rstoenescu** [comment]
Hi,

That's by design. It's the initial scroll event so you can correctly have the needed data. This should not be removed.
