### ISSUE TITLE
QInput with field type "number" debounce not working when clicking on "browser step widget" (up/down arrows)

### ISSUE THREAD

**Issue by rbuc** [quasarframework/quasar#5182]
**Describe the bug**
Debouncing does not work in QInput type "number" when changing the number by clicking on the arrows of the "browser step widget" (up and down arrows to the right of the field). 

Debouncing works when typing the number with the keyboard into the field.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/rbuc/pen/yLBWpGR

**To Reproduce**
1. Go to provided codepen
2. Enter a number in the field
3. The model will update after 2000ms as expected (debounce 2000ms) as shown above the field.
4. Click on up or down arrow displayed in the field to in-/decrease the number
5. The model will change immediately (no debounce)

**Expected behavior**
Model should debounce when using up or down arrows to in-/decrease number

**Screenshots**

**Platform (please complete the following information):**
OS: macOS
Browsers: Safari 13.0.1, Chromium 76.0.3809.100
![Screenshot 2019-09-29 at 10 10 14](https://user-images.githubusercontent.com/3257025/65829037-7742f680-e2a1-11e9-82fd-420ad512d6fa.png)

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, that is the browser native control for which there is no control over...
Sorry for any inconveniences.
