### ISSUE TITLE
QLayout error

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#5187]
**Describe the bug**
When screen width shrinks  to certain size   QDrawer covers QHeader, even when 
`
<q-layout view="hHh LpR fFf">
` 

**Platform:**
OS: Win10
Node: 12.11
NPM: 0.11.3

Browsers: Firefox, Chrome , Electron

![img](https://user-images.githubusercontent.com/1025131/65862239-1c2b0580-e36e-11e9-953c-01686c8d766e.png)

**Comment by rstoenescu** [comment]
Hi,

That's not an error. QDrawer enters "mobile mode", which covers the entire height of screen and has a backdrop over the page. This is as per specifications.

**Comment by fprijate** [comment]
Thanks.
But there is a problem. When window's width is "mobile size" you have to click toolbar twice 
to hide QDrawer (hamburger is hidden).  Also sometime ( not always) you have to click list element 
(QExpansionItem,NavItem) twice.
[Layout Gallry](https://quasar.dev/layout/gallery/quasar-classic)
Resize the window until qDrawer is hidden, click hamburger, and try few times with facebook and twitter. (sometime it take a few trials)
