### ISSUE TITLE
Q-Btn-Toggle ripple false doesn't work

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#5190]
**Describe the bug**
In q-btn-toggle the usual :ripple="false" doesn't work es expected

**Codepen**
https://codepen.io/dariodepaolis/pen/xxKobyo

**Expected behavior**
Ripple disabled when boolean is false

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.1.7.
