### ISSUE TITLE
Issue with QIcon and text-h3 class applied directly to it

### ISSUE THREAD

**Issue by FragsterAt** [quasarframework/quasar#5191]
**Describe the bug**
If you add some classes to q-icon, strange thigs will happen, it brokes jsfiddle or your app icons at all in some cases.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/tn0uw4vo/8/

**To Reproduce**
1. Go to js fiddle
2. Look at different and missing icons

**Expected behavior**
Same icons, if classes in both cases (in q-icon and in outer element)

**Screenshots**
broken tab: https://imgur.com/a/h4gbyvE

**Platform (please complete the following information):**
All

**Additional context**
Sometimes it broke all content in entire tab on load or tab change (firefox, don't check other browsers)

**Comment by hawkeye64** [comment]
Currently jsfiddle is down, so will have to look at this later
```
504 Gateway Time-out
```

**Comment by pdanpdan** [comment]
This is related to how the specific icon fonts implement font variants (in your case it's font-weight). The icon fonts don't usually implement bold fonts.

**Comment by rstoenescu** [comment]
https://jsfiddle.net/rstoenescu/pL0wrgk7/2/

The order of stylesheets matter. Put it after the Quasar's one.

**Comment by rstoenescu** [comment]
Also, note on using @quasar/extras from CDN.

**Comment by FragsterAt** [comment]
@rstoenescu 
> The order of stylesheets matter. Put it after the Quasar's one.

issue presents in quasar cli / vue cli app, jsfiddle is only for reproducing

**Comment by FragsterAt** [comment]
@rstoenescu if it can be fixed in "cdn" version by right order of stylesheets, may be it posibble to fix it in cli version?

**Comment by rstoenescu** [comment]
@FragsterAt My bad with the order. The current order is the correct one, even if it "fixes" your issue (while breaking many other things). What I am saying is that you should wrap your QIcon if you're applying a class that changes font-weight.
