### ISSUE TITLE
QTable sticky header column label overlap

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5192]
Steps to reproduce:
1) Go to example in the docs https://quasar.dev/vue-components/table#Example--Sticky-header-and-column
2) Scroll horizontally
3) Labels overlap each other

Tested on Chrome Version 77.0.3865.75 (Official Build) (64-bit)

![Screen Shot 2019-09-30 at 5 51 03 PM](https://user-images.githubusercontent.com/3635352/65890204-2c150a80-e3ab-11e9-80dc-e31a40d6a6f3.png)

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fixed example and redeploying docs.
