### ISSUE TITLE
Feature extension for tooltip component

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#52]
Extension of tooltips component to have it on left/ right/ bottom. And maybe it is also possible to have it then shift (from top to right in this example) in case it does not fit the viewport, see:
![image](https://cloud.githubusercontent.com/assets/10334123/18000967/fb3ce27a-6b80-11e6-8454-8afe3a022bff.png)

**Comment by rstoenescu** [comment]
Meanwhile you can use Popovers ;)

**Comment by musicformellons** [comment]
Maybe this is useful:
https://github.com/antongorodezkiy/vue-popper-component?utm_campaign=Revue%20newsletter&utm_medium=Newsletter&utm_source=revue

**Comment by rstoenescu** [comment]
Will look into this too. Thanks for the suggestion. I think tooltips deserve a respawn with more capabilities.

**Comment by rstoenescu** [comment]
Fixed in v0.9. Will release soon.
