### ISSUE TITLE
Drawer is very slow in phone & tablet

### ISSUE THREAD

**Issue by EmadAdly** [quasarframework/quasar#520]
#### Firstly thanks for the great framework
Please be informed that the `drawer` is very slow. in production test in `phone` & `tablet`
How i speed control or there is another reason that might lead to this.

Thanks in advance

**Comment by rstoenescu** [comment]
Fixed in future v0.14

**Comment by EmadAdly** [comment]
thanks @rstoenescu 
npm ERR! notarget a package version that doesn't exist.

When will it become available v0.14 ?

**Comment by rstoenescu** [comment]
http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list
