### ISSUE TITLE
QTable styles are applied to a nested table

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5203]
Hello,

steps to reproduce:
1) Go to codepen https://codepen.io/jean-moldovan/pen/wvwLQJZ?&editable=true&editors=101
2) Click on the first row
3) Review nested table: q-table styles are applied

Expected: q-table styles should not be applied to the nested table unless I add a q-table class.

Thanks!

![Screen Shot 2019-10-01 at 2 33 50 PM](https://user-images.githubusercontent.com/3635352/65958780-e747ad00-e458-11e9-8f13-b132129ef58a.png)

**Comment by rstoenescu** [comment]
Hi,

We're sorry, but "fixing" this would increase the CSS footprint on QTable three-fold.
We recommend using a popup (QMenu, QDialog) to show your inner table.

Sorry for the inconveniences.
