### ISSUE TITLE
Add option to disable default styles / adding Quasar UI

### ISSUE THREAD

**Issue by RauppRafael** [quasarframework/quasar#5204]
**Is your feature request related to a problem? Please describe.**
I'm only using quasar to build cross platform applications, i'm not using any of it's components, and there is no way to remove/disable it's default styles.

**Describe the solution you'd like**
Would be great to add a `disableDefaultStyles` option to `quasar.conf.js`

**Comment by pdanpdan** [comment]
I really don't understand. You're not using the styles or the components. Just build your project and you should be good to go.

**Comment by RauppAndPony** [comment]
It's not that simple.

The reason i need quasar for is to build the app for any platform.

But the styles that quasar adds by default have two major issues:

1. They use some classes with the same name as i do (from tailwind), but with different behaviors.
2. They increase the bundle size, therefor more loading time.

**Comment by ivan006** [comment]
legends have it there is a way... frodo of the shire. Simply dont import vendor.css into your final build.
