### ISSUE TITLE
Ajax bar manual increment issue.

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#5205]
I have tried to make the most sense out of increment method in Ajax bar.
When I do the regular start and stop everything works fine , I am building a little file explorer , and am using Ajax bar when user opens a folder ( to show that we are fetching folder contents )
All is good when I do simple `start` and `stop` for ajax bar. I have a vuex state `loading` that I am watching to update the loading state.
```
    loading: function (newVal, oldVal) {
      if (newVal === true) {
        this.$refs.bar.start()
      } else if (newVal === false) {
        this.$refs.bar.stop()
      }
    }
```
**This is now the problem part**

When I want to actually download a file  , I do not want to simply do a `start` and `stop` , I want to show the bar corresponding to actual download percent , for this , Here is the code that `watches` downloadPercent:
```
downloadPercent: function (newVal, oldVal) {
      console.log('WATCHER CALLED, oldVal: ' + oldVal + ' ,newVal: ' + newVal)
      if (newVal === 0) {
        this.$refs.bar.start(0)
      }
      if (newVal - oldVal > 0) {
        this.$refs.bar.increment(newVal - oldVal)
      }
      if (newVal === 100) {
        this.$refs.bar.stop()
      }
    }
```

The issue here is that the ajax bar quickly runs to the end , and stays there , untill the new value is finally 100. eg. if it takes 10 seconds to download a 10GB file , The ajax bar will reach the end after 2 seconds and stay there , untill after 8 seconds `stop()` gets called in the condition above.

I have printed the values of oldValue and newValue on console as you can see in the code above. Here is whats printed.
'WATCHER CALLED, oldVal: 100 ,newVal: 0     -- > First time when download starts
'WATCHER CALLED, oldVal: 0 ,newVal: 1
'WATCHER CALLED, oldVal: 1 ,newVal: 2
'WATCHER CALLED, oldVal: 2 ,newVal: 3 
.
.
'WATCHER CALLED, oldVal: 99 ,newVal: 100 . -- > -- > Last time when watcher is called.

I have tried commenting out `start()` and `stop()` and have tried only calling `increment` , that does not give expected result either. The above code calls `increment(1)` 100 times , but I do not see it working correctly as a download indicator.
Pretty positive this is a bug. Unless I am not understanding what the `increment` method is suppsoed to do. ( As per my understanding from the documentation , increment(1) will move it little  bit to the right . and calling it 100 times will move it to the very right.

**Comment by rstoenescu** [comment]
Will be available on "quasar" v1.1.7.
