### ISSUE TITLE
q-input with autogrow out of window border jumps

### ISSUE THREAD

**Issue by Natulux** [quasarframework/quasar#5207]
Hey.

I use the q-input as textfield with the autogrow flag. Once the size automatically grows out of visible browser range, the focus starts jumping back to top on each keyboard hit (on each new line (enter) as well as each other character not creating new lines). Actually, this only happens, if there is not already a scrollbar, but only if the scrollbar is created by the autogrow textfield.

[https://jsfiddle.net/2j81xzLv/3/](url)

Reproduce:
1. Open Fiddle-Link 
or 
create a fresh project, copy the quasar doc example of autogrow q-input into <q-layout view><q-page-container> (to simulate .vue page with router)
2. Focus the textfield and hit enter, until it grows out of visible browser space

I would have expected, that the focus stays with the line, that I work at. Instead it jumps to the top.

NPM - 6.9.0
yarn - 1.17.3
@quasar/cli - 1.0.0
OS: Windows10x64
Browsers: Google Chrome, Mozilla Firefox
NodeJs - 10.16.3

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.1.7.
