### ISSUE TITLE
Extend q-chips component to support other textbox events

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#521]
I'm building a 'profile editor' component for a user account, and things like Name are easily handled with regular `<input>` elements. I'd like an 'Interests' field, and `<q-chips>` seemed like the way to go. However, I have a 'write on blur' save approach which works fine for regular HTML elements, but `q-chips` doesn't seem to emit that. Could it be updated easily to 'bubble up' other `input` element events, other than just `@input`?

I have a feeling that changing line 23 in Chips.vue to:

        @blur="active = false; $emit('blur')"

would have the desired effect.

**Comment by rstoenescu** [comment]
Already implemented in future v0.14.
