### ISSUE TITLE
[docs] Documentation for adding webpack aliases doesn't work for linux

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#5211]
The documentation shows adding a webpack alias like this:

`myalias: path.resolve(__dirname, './src/somefolder')`

In linux (Ubuntu 18.04) I could not get that to work. What finally worked was:

`myalias: path.resolve(__dirname, 'src/somefolder/')`

I don't know if my solution works on other platforms as well, for I don't have the hardware to test it. If not, it might be worth adding an additional note in the docs for linux users.

**Comment by metalsadman** [comment]
@shinynet can provide more info? cause it's working fine on my end `ubuntu 18.04`
![image](https://user-images.githubusercontent.com/31038838/66102374-bc8a5f80-e5e4-11e9-979e-8c62e82255f7.png)

**Comment by shinynet** [comment]
You're right. I tried again and it worked.  I must've done something stupid on the first attempt.
