### ISSUE TITLE
QSplitter fails to snap to set ratio

### ISSUE THREAD

**Issue by hlb8122** [quasarframework/quasar#5212]
**Describe the bug**
Implementing a snap to 0 for the splitter produces unexpected behaviour after the first snap.

Once the splitter has been snapped to 0, then it's moved to a value < 20 it will fail to be snapped again. Once it's touched momentarily it then snaps immediately to 0 from 0 < x < 20.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/hlb8122/pen/wvvwvbL

**To Reproduce**
1) Pull the splitter to <20 or >80 ratio. 
2) Observe first snap
3) Pull the splitter to <20 or >80 ratio.
4) Observe no snap.

**Expected behavior**
Snaps to 0 in expected ranges.

**Platform (please complete the following information):**
OS:
- Android
- Ubuntu
Node:
v10.15.2
NPM:
6.11.3
Yarn:
1.19.0
Browsers:
- Firefox (PC)
- Chrome (Android)
iOS:
Android:
9

**Additional context**
When using different methods such as setting the ratio on mouseup etc the same result occurs

**Comment by pdanpdan** [comment]
When the splitter is snapped to 0/100 the model will be 0/100.
Then when you move it and set it to a value that should snap again to 0/100 you are in fact not changing the model.
So first set the model to the current value and in the $nextTick make the snap.

https://codepen.io/pdanpdan/pen/OJJLPRK?editors=1010
