### ISSUE TITLE
Conflict autofocus with select text

### ISSUE THREAD

**Issue by bodamat** [quasarframework/quasar#5217]
Input focused, but text not selected. When I focus manually text selected.

https://codepen.io/bodamat/pen/rNNBWzo

Fix or help this, please

**Comment by pdanpdan** [comment]
Please provide a valid codepen

**Comment by bodamat** [comment]
I don't understand. I provide a component.

`<template>
	<div class="row q-mb-sm">
		<q-input
			:value="name"
			ref="select"
			label="Task name"
			class="col"
			@focus="selectAll"
			@input="$emit('update:name', $event)"
			@clear="$emit('update:name', '')"
			:rules="[val => !!val || 'Field is required']"
			clear-icon="close"
			clearable
			autofocus
			outlined
		></q-input>
	</div>
</template>

<script>
import { selectAll } from "src/directives/directive-select-all";

// import mixinSelectAll from 'src/mixins/mixin-select-all'

export default {
	// mixins: [mixinSelectAll],
	props: ["name"],
	methods: {
		selectAll() {
			this.$refs.select.select();
		}
	},
	directives: {
		selectAll
	}
	// mounted() {
	// 	this.$refs.select.focus();
	// }
};
</script>`

**Comment by bodamat** [comment]
https://codepen.io/bodamat/pen/LYYPbXp

**Comment by bodamat** [comment]
https://codesandbox.io/embed/codesandbox-app-8pjch
This code work, but I use in components in my code, than don't work

**Comment by bodamat** [comment]
https://github.com/bodamat/awesome-todo
This is my project

**Comment by pdanpdan** [comment]
Just wrap the selection code in `this.$nextTick`

```javascript
selectAll() {
  this.$nextTick(() => this.$refs.select.select());
}
```

**Comment by bodamat** [comment]
Thanks! Where can I learn this and more?

**Comment by hawkeye64** [comment]
@bodamat https://vuejs.org/v2/api/#Vue-nextTick
