### ISSUE TITLE
QSelect content position

### ISSUE THREAD

**Issue by vinniimiranda** [quasarframework/quasar#5219]
I am having a position problem with the QSelect. I am using two QSelect in a form and the first one  dropdown the options to DOWN, while the second one it's dopring the content to UP.

I don't know how to fixed, already try to set the postion manually using the class "q-menu scroll"

Here is: 

First one that work the way it should:
`<div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 q-pa-sm">
                    <q-select
                      filled
                      dark
                      label="Selecione o cliente"
                      required
                      v-model="form.customerId"
                      :options="customers"
                      option-value="customerId"
                      option-label="name"
                      emit-value
                      map-options
                      :rules="[val => val !== null && val !== '' || 'Campo obrigatório! Selecione o cliente do pedido']"
                    />
                  </div>
                </div>`
![image](https://user-images.githubusercontent.com/33462844/66177149-b1601f80-e636-11e9-8c17-4aaf8f01c66d.png)

Second one that's opening the options list to UP:
`<div class="row" v-for="(product) in form.products" :key="product.productId">
                  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 q-pa-sm">
                    <q-select
                      input-debounce="250"
                      @filter="filterFn"
                      filled
                      use-input
                      hide-selected
                      fill-input
                      :virtual-scroll-slice-size="10"
                      dark
                      label="Selecione o Produto"
                      :options="productsOptions"
                      v-model="product.productId"
                      option-value="productId"
                      option-label="codigo"
                      emit-value
                      map-options
                      :rules="[val => val !== null && val !== '' || 'Campo obrigatório! Selecione o produto desejado']"
                    >
                      <template v-slot:no-option>
                        <q-item>
                          <q-item-section class="text-grey">Nenhum resultado encontrado</q-item-section>
                        </q-item>
                      </template>
                    </q-select>
                  </div>
                  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 q-pa-sm">
                    <q-input
                      filled
                      dark
                      label="Quantidade (Unidades)"
                      v-model="product.quantity"
                      @keyup="product.quantity = product.quantity.replace(/\D/, '')"
                      :rules="[val => val !== null && val !== '' || 'Campo obrigatório', val => val && val > 0  || 'Mínimo de quantidades 1']"
                    />
                  </div></div>`
![image](https://user-images.githubusercontent.com/33462844/66177176-d0f74800-e636-11e9-9dce-e1c802ac74ca.png)

If someone has a solution for that it would be very nice to use it.

Thanks.

**Comment by pdanpdan** [comment]
The menu first try to get displayed on bottom. If it cannot fit fully opened on bottom then it finds the greatest space available (on top or on bottom).
In your example it looks like it does a really good job on choosing - it would be pretty strange to show a 1 row dropdown on bottom when you have the full screen space on top.

**Comment by vinniimiranda** [comment]
Thnks for the quickly reply.

I see. Can i set the number of options displayed on the dropdown? If so it should solve my problem.
