### ISSUE TITLE
usage with Nuxt server

### ISSUE THREAD

**Issue by guumaster** [quasarframework/quasar#522]
Does this framework allow usage as a standalone components? If you have a [Nuxt](https://nuxtjs.org) project, how would you add `quasar-framework` components? Is it possible?

Let's say you start the project with:
```
vue init nuxt/starter <project-name>
```
How can you add `Quasar` afterward?

Thanks!

PS: Related to #515

**Comment by rstoenescu** [comment]
Hi, please use forum for questions. Thanks.
http://forum.quasar-framework.org/

**Comment by guumaster** [comment]
Thanks, but I cannot post without registering. I don't want to register to ask a question.

**Comment by smolinari** [comment]
> Does this framework allow usage as a standalone components?

No, currently it doesn't. 

Scott

**Comment by guumaster** [comment]
That's the answer I was looking for. Thanks. And sorry to know that I need to change framework.

**Comment by smolinari** [comment]
It isn't a framework really, when support for only using components is offered. When you get that, it is a [component library](https://github.com/vuejs/awesome-vue#ui-components) or [a component collection](https://github.com/vuejs/awesome-vue#component-collections). If you are using these things, you will end up finding that you are building a framework around them. Or, if you don't build those framework like things, you'll be missing a lot of features frameworks offer, which make the developer's life better. 😄 

Scott

**Comment by kristianmandrup** [comment]
Check out [quasar-template-nuxt](https://github.com/quasarframework/quasar-template-nuxt) 
... and help make it even better!! So awesome :) :) :)

**Comment by mesqueeb** [comment]
@guumaster With the newest updates of Quasar it can now be used as a component library. 
Also Nuxt boilerplate is in the works!

**Comment by smolinari** [comment]
@mesqueeb 

Hey Luca,

When you say "it", do you mean Quasar? If yes, is there a link to any documentation about the Nuxt integration? I've been keeping up on the release accouncements in the forum and didn't see anything about Nuxt. 

Scott

**Comment by mesqueeb** [comment]
@smolinari 
I meant: "Quasar can now also be used as a component library, not just as a fully fledged framework."
Quasar as a component library is called **Quasar UMD**.
Here are the [docs](http://quasar-framework.org/guide/#UMD-Standalone-uses-CDN).

Nuxt is in development behind the scenes. No further news at this point.
