### ISSUE TITLE
Slide-Item top slot not working properly

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#5220]
**Describe the bug**
When you define both top and bottom slots, and programmatically remove the top slot, you can still slide the item down while getting the error:

Uncaught TypeError: Cannot read property 'style' of undefined
    at VueComponent.__pan (QSlideItem.js?e45e:119)
    at HTMLDivElement.move (TouchPan.js?75c3:189)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/DevinHolloway/pen/BaaBVgJ

**Expected behavior**
When programmatically removing a slide-item slot, it should disable the sliding behavior for that slot.

**Additional context**
The issue appears to only occur with the top slot, and only when also defining a bottom slot. If you remove the bottom slot from code, the top slot sliding is correctly disabled.  Or, if you define both slots, but only programmatically remove the bottom slot, it still works as expected.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.1.7.
