### ISSUE TITLE
QChatMessage avatar can display too wide

### ISSUE THREAD

**Issue by dlbass** [quasarframework/quasar#5226]
**Describe the bug**
If the avatar image provided to a QChatMessage is not square, the container stretches to contain the image, resulting in an oval.

**To Reproduce**
1. Create a QChatMessage
2. Supply a non-square image as the avatar
3. See that it is not a circle

**Expected behavior**
The avatar should display a circle no matter the supplied image, as QAvatar does.

**Screenshots**

![image](https://user-images.githubusercontent.com/4282090/66219926-ac7c8980-e691-11e9-8991-423bca149ff0.png)

**Possible solution**
I poked around in dev tools and found that removing the `col-auto` class from the avatar seems to solve the issue.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.1.7.

**Comment by dlbass** [comment]
Hey @rstoenescu,

We just updated to v1.1.7 and the avatar is always showing round as expected!

But, there's a new issue for us that the avatar circle always shows up even if we are not sending an avatar to be shown. The avatar shape also shows up for the chat label. We wonder if it is related to the new min-width being applied, but haven't found a workaround so far.

![image](https://user-images.githubusercontent.com/4282090/66335349-801a7480-e900-11e9-9202-22ebd2229859.png)

**Comment by wooliet** [comment]
As a workaround for now, we are applying this rule to our chat component:
```
img:not([src]) {
  display: none;
}
```
