### ISSUE TITLE
Dark Label in Toggle

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#5227]
**Describe the bug**
With the prop dark in toggle the label still being black

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Indiegame/pen/mddbZvL

**To Reproduce**
1. Make a dark background
2. Create a toggle with the dark attribute and a label

**Expected behavior**
The label use white or grey color for label text

**Comment by rstoenescu** [comment]
Hi,

The label inherits the color of the page for consistency. The dark prop for QToggle refers to the design of the control itself. Apply a "text-white" css class on it or one of the containers.
