### ISSUE TITLE
Feature request: extract alert dot out of QTab into its own component

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#5229]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use the alert dot on a button or an icon.

**Describe the solution you'd like**
I'd like to be able to use the alert dot outside of a tab, e.g. on a button or on an icon.

**Describe alternatives you've considered**
I considered using QBadge, but it doesn't seem to be quite the right fit (wrong shape, don't need text inside).

**Comment by rstoenescu** [comment]
Hi,

It's too simple for the framework. Here's why:

```html
<div class="my-dot"></div>
```
```styl
.my-dot
    position absolute
    top 7px
    right -9px
    height 10px
    width 10px
    border-radius 50%
    background #00ffff
```

**Comment by RohanTalip** [comment]
OK, thanks for the tip.
