### ISSUE TITLE
Dialog with containerized QLayout: Scrollbars beside toolbar instead only in content

### ISSUE THREAD

**Issue by getriebesand** [quasarframework/quasar#5237]
**Describe the bug**
If I use a dialog with a layout and toolbar like in the docs, the scrollbar is beside toolbar and footer. This is very ugly. In v0.17 the scrollbar is correct only in content area

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/getriebesand/pen/QWWWjOz?&editable=true&editors=101

**To Reproduce**
Implement dialog with containerized QLayout like explained in the docs

**Expected behavior**
The scrollbar on the right should only be in the content area, not right of toolbar and footer

**Screenshots**
![image](https://user-images.githubusercontent.com/5921286/66244265-f011da80-e707-11e9-90d4-53958f173759.png)

**Platform (please complete the following information):**
OS: Kubuntu
Node:10.16.3
NPM: 6.9.0
Yarn: 1.19.0
Browsers: Chromium

**Comment by rstoenescu** [comment]
Hi,

This is not a bug. This is actually intended and cannot work otherwise.
Should you wish that the scrollbar appear only besides the content, you could play with the flex classes to create your own "layout".
