### ISSUE TITLE
[QDrawer] - QDrawer's backdrop doesn't have class `no-pointer-events` on first show on mobile

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#5241]
**Describe the bug**
QDrawer's backdrop doesn't have class `no-pointer-events` on first show on mobile

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.quasar.dev

**To Reproduce**
1. Go to https://codesandbox.quasar.dev
2. Turn your navigator in responsive mobile display
3. Refresh
4. Try click on the menu `hamburger` a first time (wont work)
4. Try click on the menu `hamburger` a second time (it work's)

**Expected behavior**
The `hamburger` menu must work at first time.

**Screenshots**
![Image of QDrawer](https://i.ibb.co/tXs3DLY/QDrawer.png)

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this!
Fix will be available shortly in "quasar" v1.1.7.
