### ISSUE TITLE
[docs] /layout/page wrong URL for Layout Builder

### ISSUE THREAD

**Issue by bartduisters** [quasarframework/quasar#5245]
When clicking on Layout Builder on the bottom of https://quasar.dev/layout/page.
![image](https://user-images.githubusercontent.com/43420049/66258192-6cf19280-e7a2-11e9-99c7-8e276db1e075.png)

It redirects to https://quasar.dev/layout/layout-builder, while it should redirect to https://quasar.dev/layout-builder.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Will be fixed in next docs deployment.
