### ISSUE TITLE
QTable pagination's pagesNumber bug

### ISSUE THREAD

**Issue by cashmisa** [quasarframework/quasar#5251]
**Describe the bug**
To return all records in 1 page, pagination.rowsPerPage is to be set to 0. But when pagination.rowsPerPage === 0, pagination slot props.pagesNumber returns Infinity.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/cashmisa/pen/JjjjVEJ

**To Reproduce**
1. "Records per page" select "All"

**Expected behavior**
props.pagesNumber should return 1 when pagination.rowsPerPage === 0.

**Additional**
I will create a PR to fix this minor bug

**Comment by rstoenescu** [comment]
Thanks for reporting and supplying a PR for this!
This will go into "quasar" v1.2.0.
