### ISSUE TITLE
QTime / IE11 / UMD :  closing unexpectedly while selecting time

### ISSUE THREAD

**Issue by shashane** [quasarframework/quasar#5255]
**Describe the bug**
on IE11, when user open QTime component (UMD mode), component closes unexpectedly when user try to select time

**Expected behavior**
on IE11, user opens QTime component and select time

**Platform (please complete the following information):**
OS: Windows 10
Browsers: IE11

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.2.0.

**Comment by ravimule22** [comment]
Hello @rstoenescu  I used quasar.ie.polyfills.umd.min.js for UMD/Standalone project to support it in IE 11 but still it not support in IE11. I placed this script before the vue and qusar tag.
Ex - 
<body>
<script src="https://unpkg.com/quasar-framework@0.17.20/dist/umd/quasar.ie.polyfills.umd.min.js"></script>
 

	<div id="app" v-cloak >		
		<form id="userLogout" action="<%=apiURL%><%=pageURL%>" method="post"></form>
	
	<q-dialog v-model="dialog.show" :persistent="dialog.showCancel" >
        
      </q-dialog>
    	
	</div>

     
    <script src="https://cdn.jsdelivr.net/npm/quasar@17.20/dist/quasar.ie.polyfills.umd.min.js"></script> 
  
 	<script src="./common/vue/js/vue-2.6.js"></script>
 
 	
 	
 	<script src="https://cdn.jsdelivr.net/npm/quasar@1.1.0/dist/quasar.umd.min.js"></script>
        Functions..................
     </body>

**Comment by rstoenescu** [comment]
@ravimule22 please do not cross-post.
