### ISSUE TITLE
q-card-action  events are being propagated q-card led to repeat event call

### ISSUE THREAD

**Issue by OK0X** [quasarframework/quasar#5257]
**Describe the bug**
q-card-action  events are being propagated q-card .thus, if q-card-action and q-card all have theirs events, when user click btn in q-card-action, the event is also  being propagated q-card,
it makes repeat call ,how to avoid repeat this call

**Codepen/jsFiddle/Codesandbox (required)**
`<template>
  <q-page class="mypage">
    <q-card class="my-card" @click="test2(1)">
      <q-card-section style="display:flex;flex-direction: column;">
        <span style="font-family: '\5FAE\8F6F\96C5\9ED1';font-size: 2rem;">title</span>
        <span style="color:gray">author: e444</span>
      </q-card-section>
      <q-separator />
      <q-card-section>{{ lorem }}</q-card-section>
      <q-separator />
      <q-card-actions align="right">
        <q-btn flat round color="red" icon="favorite" @click="test" />
        <q-btn flat round color="teal" icon="bookmark" />
        <q-btn flat round color="primary" icon="share" />
      </q-card-actions>
    </q-card>
  </q-page>
</template>

<script>
/* eslint-disable */
export default {
  data() {
    return {
      lorem:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
    };
  },
  methods: {
    test() {
      toast("ddd");
    },
    test2(data){
      toast(data)
    }
  }
};
</script>
<style scoped>
.my-card {
  width: 100%;
  max-width: 837px;
}
</style>
`

**To Reproduce**
1. Click on 'favorite icon'
2. toast twice

**Expected behavior**
toast only once ,test2 shoud not be called

**Screenshots**
![Snipaste_2019-10-08_12-44-33](https://user-images.githubusercontent.com/48879766/66368051-68f38980-e9c9-11e9-9b72-7e35ca28a500.jpg)

**Comment by rstoenescu** [comment]
Hi,

Use `@click.stop` on your buttons. It stops the propagation (calling event.stopPropagation() under the covers).
