### ISSUE TITLE
[Request] Add a clickable/ touchable feature to the q-chip component

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#526]
According to [the material design spec](https://material.io/guidelines/components/chips.html#), the "contact chip" should offer a means to open up the underlying data of the contact for infomational or for selection purposes. I'd like to suggest adding only the ability to make the chip clickable in general and leave it up to userland to add whatever is wanted on the click event. In other words, why limit chips to only contact information? 😄 

Once 0.14 is out, I'd like to work on this, should the feature be approved.

Scott

**Comment by rstoenescu** [comment]
Green light.

**Comment by smolinari** [comment]
Oh dang! I was hoping I could do it. Actually, I completely forgot I had made this suggestion. Thanks for adding it Razvan. One more nice detail, that makes Quasar rock! 😄 

Scott
