### ISSUE TITLE
Is it possible to pass some sensitive parameters through ssrContext?

### ISSUE THREAD

**Issue by luozhihua** [quasarframework/quasar#5260]
**Is your feature request related to a problem? Please describe.**
no related problem.

**Describe the solution you'd like**
Passing the JWT security key or other parameters that are only visible on the server through ssrContext, sometimes I need to decrypt the JWT Token in preFtech to get some information about the user context like user ID.

**Describe alternatives you've considered**
There are two alternatives I can think of now, but there are some problems:

Option 1, what can be done is to store the user ID in the cookie, and then get it through `ssrContext.req.headers.cookies`, but the user ID is also redundant in the JWT Token, and the cookie may be tampered with. The user ID in the JWT Token is relatively safe and reliable, so it is more desirable to be able to decode the user ID from the JWT.

Option 2, through process.env.JWT_SECRET, but webpack will replace some of the process.env parameters;

**Additional context**
ssr preFetch

**Comment by TobyMosque** [comment]
if u need to share sensitive data between the client and the server, u would use cookies to that.
normally, i store user related fields (like token, user preferencies, etc) in a single vuex, so i use vuex-persistedstate to save them in a Cookie.

```
yarn add vuex-persistedstate
quasar new boot persist
```
**./src/boot/persist.js**
```js
import { Cookies } from 'quasar'
import createPersistedState from 'vuex-persistedstate'

export default function ({ store, ssrContext }) {
  const cookies = process.env.SERVER
    ? Cookies.parseSSR(ssrContext)
    : Cookies

  createPersistedState({
    paths: ['app'],
    filter ({ type }) {
      return type.startsWith('app')
    },
    storage: {
      getItem (key) {
        return JSON.stringify(cookies.get(key))
      },
      setItem (key, value) {
        cookies.set(key, value)
      },
      removeItem (key) {
        cookies.remove(key)
      }
    }
  })(store)
}
```
so store your token and other user preferencies in the app module.

**Comment by luozhihua** [comment]
Thanks for your reply, I am not talking about sharing data between client and ssr. Instead, I hope that some security data can only be read in the ssr context, instead of exposing it to the client, ssrContext is only defined in the server side, so I think it is a very good solution to share data between the backend server and the SSR through ssrContext. Unfortunately, there is currently no way to extend the ssrContext in the backend server (maybe I have not found it).

I said that there are some differences between SSR and Backend server(Koa), Backend server is using for serve api requests and SSR;

After research, I found some clues:

```typescript
// My app.ts
import * as Koa from 'koa';
const app = new Koa();
const ssr = require('../ssr'); // => ${appRoot}/dist/ssr/ssr.js

app.use(async (ctx) => {
  const { req, res } = ctx;
  res.setHeader('Content-Type', 'text/html')
  await new Promise(resolve => {
    const ssrContext = { 
      req, 
      res, 
      customData: { ... } // => passing some custom data which is named `customData` to ssr.renderToString();
    };
    ssr.renderToString(ssrContext, (err: any, html: string) => {
      ctx.body = err ? '500 error' : html;
      resolve();
    }
  });
});
app.listen(3000);
```

```typescript
//  ${appRoot}/dist/ssr/ssr.js   (Should be generated by `quasar build -m ssr`)
...
module.exports.renderToString = function ({ req, res }, cb) {
  const ctx = { req, res, url: req.url};  // Lost `customData` here.

  renderer.renderToString(ctx, (err, html) => {
    if (err) { cb(err, html) }
    else { cb(err, ctx.$getMetaHTML(html)) }
  })
}
...
```

**Comment by jigarzon** [comment]
I have the same request. Did you solve this somehow @luozhihua ? I need the process.env variables in server side preFetch, but they are hidden (it looks like the environment of SSR is isolated from the node.js serving app.)

**Comment by rstoenescu** [comment]
@luozhihua The whole context will be passed to renderToString(), but only for production. There's no way to be able to do this on dev because you don't access to the underlying express instance and handling.
