### ISSUE TITLE
Fullscreen on custom elements

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#5262]
I would like to emulate the "fullscreen" option that we see on Quasar tables on my custom components (i.e. an arbitrary div).

I have tried setting a div to have classes "fullscreen" and "z-maz" but it doesn't work.  After inspecting QTable it seems that a new 'table container' element is inserted higher in the HTML hierarchy (after the body tag).  

This request is important to me!  I understand that nesting this functionality may prove problematic.  I'm OK with the functional limitation of only 1 thing fullscreen at a time.  Thank you for your consideration!

**Comment by bebekar** [comment]
please see app-extension-qzoom

**Comment by rfox12** [comment]
I'm not sure app-extension-qzoom will work for my needs.  I need full interactivity as per the original Vue component hierarchy.  QZoom seems to do a (hopefully cheap) clone and overlay it.

**Comment by hawkeye64** [comment]
You could look at the app extension QMediaPlayer. It implements fullscreen.

**Comment by rfox12** [comment]
This is my current hack (I'm using QLayout)
`        if (fullscreen) {
          // append to body
          var myContentDiv = document.querySelector("#myContent")
          var layoutDiv = document.querySelector("#q-app div.q-layout")
          var appDiv = document.querySelector("#q-app")
          layoutDiv.style.display = 'none';
          appDiv.appendChild(myContentDiv);
        } else {
          // append to original place
          var myContentDiv = document.querySelector("#myContent")
          var layoutDiv = document.querySelector("#q-app div.q-layout")
          var myContentParentDiv = document.querySelector("#myContentParent")
          layoutDiv.style.display = 'block';
          myContentParentDiv.appendChild(myContentDiv);
        }
`

**Comment by pdanpdan** [comment]
You can use the Fullscreen API (AppFullscreen plugin - https://quasar.dev/quasar-plugins/app-fullscreen#AppFullscreen-API)
