### ISSUE TITLE
QDate - Go to Months view after a year is selected from Years view

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5267]
**Is your feature request related to a problem? Please describe.**
`QDate` currently jumps to the `Calendar` view after selecting a year from the `Years` view. Maybe this makes sense for the current year, but if someone is selecting a year, they probably want/expect to select a month next.
  
Imagine a "Birthday" field with `default-view="Years"`. If I chose 1963, it doesn't really make sense to jump to October 1963.

**Describe the solution you'd like**
Selecting a year from `Years` view goes to `Months` view. Either always, or as a configurable option. Or expose an event when the view changes so that this can be implemented by the developer calling `setView()`.

**Describe alternatives you've considered**
Custom date picker.

**Additional context**
I don't want to `emit-immediately` because I wouldn't want the underlying model to change until the full date is selected, in case the user cancels by clicking outside the date picker.

**Comment by rstoenescu** [comment]
Will be available in 'quasar' v1.2.2
