### ISSUE TITLE
QEditor javascript blur function doesn't work

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#5268]
**Describe the bug**
If you put focus on the QEditor, it works, but then you can't remove the focus from it with the function blur().

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/medhyena/pen/jOOPGar

**To Reproduce**
1. focus() on the editor
2. blur() on the editor

**Expected behavior**
It should remove focus from QEditor.

**Comment by rstoenescu** [comment]
Hi,

QEditor component has no "blur()" method....
