### ISSUE TITLE
QSelect: TypeError: Cannot read property 'sanitize' of null' when using selected-item slot

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5270]
**Describe the bug**
When the `options` to _QSelect_ is falsy, and `v-slot:selected-item` is used, we get the following error:
> TypeError: Cannot read property 'sanitize' of null'

 **Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tomers-the-encoder/pen/qBBdQLE?editors=1011

**Comment by rstoenescu** [comment]
Hi Tomers,

```
[Vue warn]: Invalid prop: type check failed for prop "options". Expected Array, got Boolean with value false.
```

The options needs to be an Array (even if empty!).

**Comment by mayankkataria** [comment]
I'm facing the same error. Did anybody found any solution??

**Comment by rstoenescu** [comment]
@mayankkataria 

<img width="483" alt="image" src="https://user-images.githubusercontent.com/4665641/151679800-629fdccc-b0d8-45d8-b419-6035faa98323.png">
