### ISSUE TITLE
[docs] QChip - size attribute

### ISSUE THREAD

**Issue by jaredthirsk** [quasarframework/quasar#5271]
There is a code example under the 'dense' section:
`<q-chip dense icon="event" size="10px">Add to calendar</q-chip>`

But I do not see size mentioned in the API section and it doesn't seem to have any effect, and the size="10px" is rendered to HTML.

What should the docs say for the size attribute?

**Comment by rstoenescu** [comment]
Hi,

There is no "size" prop for QChips. Marked this as a feature request.

**Comment by rstoenescu** [comment]
"size" prop for QChip is now available in "quasar" v1.2.2.
