### ISSUE TITLE
.env file changes can't reflect after production build

### ISSUE THREAD

**Issue by nibhatt9** [quasarframework/quasar#5272]
Create SPA app in quasar containing server and client logic in it on my machine <192.168.1.1>. Created a production build and deploying it to another host machine <192.168.1.7>, This server is accessed through browser from other clients on the network. I am able to connect to the server for pages however it tries to fetch data from the local (browser) machine and not from the server. This could be due to some config setting required. It may be something to do with dotenv.

**Comment by rstoenescu** [comment]
Hi,

Please use the https://forum.quasar.dev or https://chat.quasar.dev for questions. Thanks.
