### ISSUE TITLE
QDate within QInput

### ISSUE THREAD

**Issue by FascistDonut** [quasarframework/quasar#5275]
**Describe the bug**
After upgrading to Quasar 1.2.0, the Qdate within QInput does not seem to be working. You can see it on both the documentation and the associated codepen.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/fascistdonut/pen/ZEEbyba?&editable=true&editors=101

**To Reproduce**
1. Go to https://quasar.dev/vue-components/date
2. Scroll down to "With QInput"
3. Click icon to try and open date input.

**Expected behavior**
The date input should open and allow us to select a date, which will be represented as a string in q-input.

**Screenshots**
![image](https://user-images.githubusercontent.com/8247632/66591273-64ed7600-eb47-11e9-8a9a-a642247ad860.png)

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Chrome

**Comment by userdude** [comment]
I can confirm on Windows 8.1 Chrome and Firefox, and Mac Chrome. No errors in the console.

Here's a fiddle: https://jsfiddle.net/xp3uq1e5/

The interesting part is that if you pull the window chrome up, at a point around the height of the popup it suddenly shows up.

![image](https://user-images.githubusercontent.com/424917/66619612-1c63a600-eba3-11e9-9d0f-a21b4d6aecb3.png)

https://imgur.com/l3g5k8n

**Comment by userdude** [comment]
I don't think it's CSS; the dialog stays up if you pull the chrome down. It looks like something in `transition-show` or another handler is pruning it if the window is taller than the dialog's height.

**Comment by JavaFellow** [comment]
@FascistDonut 
I got the same problem with U, it just happend after update  to 1.2.0

**Comment by rstoenescu** [comment]
Thanks for reporting. Will investigate and fix.

**Comment by rstoenescu** [comment]
Fix will be available shortly in "quasar" v1.2.1.
