### ISSUE TITLE
Errors trying to run capacitor for the first time (requires yarn)

### ISSUE THREAD

**Issue by ssuess** [quasarframework/quasar#5278]
While using the command `quasar dev -m capacitor -T ios` I am greeted with the following errors:

```
myuser$ quasar dev -m capacitor -T ios

 Dev mode.......... capacitor
 Pkg quasar........ v1.2.0
 Pkg @quasar/app... v1.2.0
 Debugging......... enabled
 Running mode...... IDE (manual)

 app:mode-capacitor Adding Capacitor platform "ios" +0ms
 app:spawn [sync] Running "/Users/myuser/Documents/myproject/src-capacitor/node_modules/@capacitor/cli/bin/capacitor add ios" +1ms

✖ Installing iOS dependencies: 
✖ add: 
[error] /bin/sh: yarn: command not found


 app:spawn ⚠️  Command "/Users/myuser/Documents/myproject/src-capacitor/node_modules/@capacitor/cli/bin/capacitor" failed with exit code: 1 +0ms
```

**To Reproduce**
1. Install capacitor with `quasar mode add capacitor`
2. Try to run with `quasar dev -m capacitor -T ios`

**Expected behavior**
That it would work/launch and I could try out capacitor

**Platform (please complete the following information):**
Operating System - Darwin(18.7.0) - darwin/x64
NodeJs - 11.11.0

Global packages
  NPM - 6.12.0
  yarn - Not installed
  @quasar/cli - 1.0.0
  cordova - 8.1.2 (cordova-lib@8.1.1)

Important local packages
  quasar - 1.2.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.2.0 -- Quasar Framework local CLI
  @quasar/extras - 1.3.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.6.4 -- Babel compiler core.
  webpack - 4.41.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.8.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-icon-genie - 1.1.1 -- A Quasar CLI Extension for Making All Your Icons

**Additional context**
It would seem strange that yarn is a requirement (since quasar allows npm or yarn everywhere else), but at least it should be noted in the docs somewhere I guess.

**Comment by rstoenescu** [comment]
Thanks for reporting!
It was a glitch in the src-capacitor template.

Please upgrade to "@quasar/app" v1.2.1 and remove then add capacitor mode OR edit /src-capacitor/capacitor.config.json on the "npmClient" prop (set it to "npm").

**Comment by ssuess** [comment]
Thanks!
