### ISSUE TITLE
[Request] Slider: emitting direction too on @slide event

### ISSUE THREAD

**Issue by dobromir-hristov** [quasarframework/quasar#528]
The Slider's `slide` event is fine and all, but I think it should emit the action we are sliding, `next`, `prev` or `left`, `right`. Currently I was trying to compare indexes but that didn't help much when dynamically adding items to the slider.
This would be a breaking change if we do it in the `slide` event because currently it only emits the new current index, and if we emit an object we could break someone's code. 
Another way is to emit a whole new event, which is kind of redundant as it will emit on the same time.
Also I don't know if it should emit a `slide` event even if we try to go `next` but there are no other slides so the slider stays where it is, meaning it doesn't change its `currentSlide` position. 
Are some of these things in consideration or should I hop into it and try to do a PR? I ended up to these "walls" so to say when trying to do a dynamic infinite slider with preloading the prev and next slides.

**Comment by rstoenescu** [comment]
Hi, emit works with multiple parameters so we don't break compatibility. '$emit(slide, direction)'. If you want to make a PR that would be great. Do it on v0.14 branch. Let me know if you need any help.

**Comment by rstoenescu** [comment]
Merged https://github.com/quasarframework/quasar/pull/530
Will be available in future v0.14
