### ISSUE TITLE
Unexpected end of JSON input while parsing near '...shint":"2.8.x","nock"'

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#5281]
**Describe the bug**
Can't create new project.
I appeared after 1.2.0 has been released.
Two days ago it worked correctly.
Here is log file: https://pastebin.com/s5qycyNx

**To Reproduce**
Run `quasar create test`

**Expected behavior**
Just create new project

**Screenshots**
https://prnt.sc/phxuz1

**Platform:**
OS: win10
Node: 12.7.0
NPM: 6.12.0

**Comment by rstoenescu** [comment]
Hi,

This has nothing to do with '@quasar/app'... It's definitely coming from the node/npm installed on your machine. Try to upgrade both versions.

**Comment by matro-skin** [comment]
I have same error if I run `quasar create test` at empty dir
