### ISSUE TITLE
Sticky column

### ISSUE THREAD

**Issue by cn-xufei** [quasarframework/quasar#5282]
**Describe the bug**
Hello, I met a bug on ios.【Sticky column】，After rolling for a certain distance horizontally, the sticky fails.
You can see that the first column is no longer stickying.
![image](https://user-images.githubusercontent.com/14144811/66655102-1981b780-ec6e-11e9-8fae-b795a6744267.png)

**Platform (please complete the following information):**
Browsers: chrome,safari
iOS: 13

**Additional context**

**Comment by cn-xufei** [comment]
![image](https://user-images.githubusercontent.com/14144811/66655837-6619c280-ec6f-11e9-93fd-c96cdded00e6.png)

**Comment by cn-xufei** [comment]
![image](https://user-images.githubusercontent.com/14144811/66656000-b6912000-ec6f-11e9-9ead-31349fa61a40.gif)

**Comment by cn-xufei** [comment]
![图像](https://user-images.githubusercontent.com/14144811/66656040-c7da2c80-ec6f-11e9-8131-7786c1b79bb0.gif)

**Comment by metalsadman** [comment]
@cn-xufei see here https://caniuse.com/#search=sticky, so you'll have to change something in your sticky css class

**Comment by rfox12** [comment]
I would be great if this (sticky columns) was an official feature of quasar (as a component property).  Avoiding the need to know complex css tricks is one of the things I would appreciate

**Comment by cn-xufei** [comment]
> @cn-xufei see here https://caniuse.com/#search=sticky, so you'll have to change something in your sticky css class

Thank you, but I still haven't found a solution.😂
For example, some css hack...
I'm curious that there's no such problem with vertical rolling.

**Comment by metalsadman** [comment]
@cn-xufei it's not a bug btw, the docs did have a warning https://quasar.dev/vue-components/table#Sticky-header%2Fcolumn, if you check the link i gave you (which was also coming from the same warning block). then you'll have to prefix it with `-webkit-position: sticky;`.
taking this example from docs https://quasar.dev/vue-components/table#Example--Sticky-column.
try add this in the style (i haven't tested this myself)
```html
<style lang="sass">
.my-sticky-column-table
  /* specifying max-width so the example can
    highlight the sticky column on any browser window */
  max-width: 600px

  /* bg color is important for th; just specify one */
  thead tr:first-child th:first-child
    background-color: #fff
    opacity: 1

  td:first-child
    background-color: #f5f5dc

  thead tr:first-child th:first-child,
  td:first-child
    position: sticky
    -webkit-position: sticky
    left: 0
    z-index: 1
</style>
```

**Comment by cn-xufei** [comment]
> @cn-xufei it's not a bug btw, the docs did have a warning https://quasar.dev/vue-components/table#Sticky-header%2Fcolumn, if you check the link i gave you (which was also coming from the same warning block). then you'll have to prefix it with `-webkit-position: sticky;`.
> taking this example from docs https://quasar.dev/vue-components/table#Example--Sticky-column.
> try add this in the style (i haven't tested this myself)
> 
> ```
> <style lang="sass">
> .my-sticky-column-table
>   /* specifying max-width so the example can
>     highlight the sticky column on any browser window */
>   max-width: 600px
> 
>   /* bg color is important for th; just specify one */
>   thead tr:first-child th:first-child
>     background-color: #fff
>     opacity: 1
> 
>   td:first-child
>     background-color: #f5f5dc
> 
>   thead tr:first-child th:first-child,
>   td:first-child
>     position: sticky
>     -webkit-position: sticky /* add this line */
>     left: 0
>     z-index: 1
> </style>
> ```
> 
> https://codepen.io/metalsadman/pen/qBBZKxr
@metalsadman 
Yeah，it's not a quasar bug 😅
I would like to have friends who have the same problems to discuss solutions
Vertical scrolling is OK
I've added `-webkit`
I think it's the WebView kernel compatibility of IOS
