### ISSUE TITLE
QLayout problem.

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#5285]
There is a problem with QLayout . When window's width is resized to "mobile size" you have to click toolbar twice to hide QDrawer (hamburger is hidden). Also sometime ( not always) you have to click list element (QExpansionItem,NavItem) twice.
[Layout Gallery](https://quasar.dev/layout/gallery/quasar-classic)
Resize the window until qDrawer is hidden, click hamburger, and try few times with facebook and twitter. (sometime it take a few trials)

**Comment by fprijate** [comment]
[video](https://streamable.com/xkiiv)

**Comment by rstoenescu** [comment]
For the life of me, I cannot reproduce.
Running Firefox 69.0.3 (64-bit).

Can anyone else reproduce?

**Comment by TobyMosque** [comment]
I wasn't able to reproduce too.

Microsoft Edge - 44.18362.387.0 (Microsoft EdgeHTML 18.18362)
Microsoft Edge - Based on Chromium - Version 78.0.276.17 (Official build) beta (64-bit)
Opera - Version 63.0.3368.107
Opera GX - LVL1 (core: 63.0.3368.56078)
Google Chrome - Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by webnoob** [comment]
I've recreated once on FF but can't do it again ... 🤔

**Comment by webnoob** [comment]
I'm managing to get this into a state where the overlay is present but the drawer is closed. I think this is related.

**Comment by webnoob** [comment]
RE: Clicking twice. @fprijate Are you sure you're not holding down a little a dragging a tiny bit on click? It's very sensitive.

**Comment by metalsadman** [comment]
try clearing / clean or reset settings of your browser.

**Comment by fprijate** [comment]
Here is my electron app [video](https://streamable.com/zpw4u).
It always works when window is big enough. When window is resized, it sometimes work, sometimes not. ( semotimes it takes a time, sometimes there is error first time you try).
No mater which browser Firefox, Chrome or Electron (which is Chrome of course) I select, there is same behaviour. Maybe you have to try more combinations.

**Comment by fprijate** [comment]
I have also changed a mouse, but no difference.

**Comment by fprijate** [comment]
> 
> 
> RE: Clicking twice. @fprijate Are you sure you're not holding down a little a dragging a tiny bit on click? It's very sensitive.

No. In bigger window it works all the time on smaller sometimes works sometimes not .As I know my clicking is not dependent on the window size .

**Comment by pdanpdan** [comment]
Are you on the latest quasar version. I remember there were some fixes for 2 versions ago.

**Comment by fprijate** [comment]
> 
> 
> Are you on the latest quasar version. I remember there were some fixes for 2 versions ago.

Yeap
"@quasar/extras": "^1.3.2",
"quasar": "^1.2.1"

**Comment by fprijate** [comment]
> 
> 
> RE: Clicking twice. @fprijate Are you sure you're not holding down a little a dragging a tiny bit on click? It's very sensitive.

When dragging (even little) hand shows. As you can see from both videos there is no hand showing.

**Comment by fprijate** [comment]
I just added  :breakpoint="10" to q-drawer (anyhow it's desktop app) and everything works fine.

**Comment by rstoenescu** [comment]
Haven't been able to reproduce this, but the latest "quasar" (v1.5.9 as of writing this line) shouldn't have any such problems.

**Comment by fprijate** [comment]
Thanks . It's working OK.
