### ISSUE TITLE
Have QSplitter work with absolute sizes (in addition to percentages)

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#5286]
I'm using QSplitter to create a collapse-able panels.  I'd like the option to keep the left or right slots fixed in terms of px instead of %.  My hack right now with involves un-normalizing the percentage and it's not a great solution--my UI jitters like crazy when resized.

**Comment by hawkeye64** [comment]
@rfox12 Using a percentage makes sense for most users, especially for mobile where a user can rotate their device from portrait to landscape. I presume your use-case is you have a fixed width and height?

**Comment by rfox12** [comment]
I'm basically trying to achieve somethings like Quasar's expansion item (https://quasar.dev/vue-components/expansion-item) with left-expand-right or right-expand-left.

**Comment by rstoenescu** [comment]
"reverse" Boolean prop and "unit" ('%' or 'px') will be available in "quasar" v1.2.6.

**Comment by rfox12** [comment]
It works perfectly.  Thank you!!!!
