### ISSUE TITLE
QDialog : wrong position in iframe

### ISSUE THREAD

**Issue by sebastienroul** [quasarframework/quasar#5288]
**Describe the bug**
When using css `positon: fixed` in iframe it is relative to the iframe, not to the window - so Qdialog displayed "somewhere" (on top, middle or bottom) of the iframe.
Most of the time user cant see the QDialog, cause it appears not where he is in the scroll (when iFrame is height).

**Codepen/jsFiddle/Codesandbox (required)**
Sorry, no code pen cause iframe is hard to integrate

**To Reproduce**
1. Integrate a quasar app in an iFrame and set style="height:3000px"
2. In th integrated document
   2.1 Create a button to show the QDialog (with a margin top 500px)
   2.2 Add the code for QDialog (with position="top")
3. Run everything and click on the button
4. QDialog is displayed at the top of the iFrame and not visibile without scrolling

**Expected behavior**
QDialog should be visible at the current scrollY of the parent window

**Screenshots**

**Platform (please complete the following information):**
OS: All
Node: All
NPM: All
Yarn: All
Browsers: All
iOS: 
Android:
Electron:

**Additional context**
I found a "hard hack" : on the @show of QDialog add the following code
```
if (document.querySelectorAll('.q-dialog>.q-dialog__inner')[0]) {
      document.querySelectorAll('.q-dialog>.q-dialog__inner')[0].setAttribute('style', 'top:' + (window.top.scrollY + 50) + 'px')
}
```
But not very clean :o)

**Comment by rstoenescu** [comment]
Hi,

This is a pretty particular case. Unfortunately, we cannot account for use-cases where Quasar is used in an iframe. What I recommend is embedding your work-around in the app-space.. Sorry for any inconveniences.

**Comment by sebastienroul** [comment]
Hi @rstoenescu,

No problem for me - workaround will be embeded

Just two points of view : 

- I'm totally disagree with your think about "iframed app" are "pretty particular case"
- I'm totally respecting your choice to not want to fix it.

All enterprise have legacy spa and most of them cant upgrade everything all the time - then micro-frontends architecture appears : [https://martinfowler.com/articles/micro-frontends.html
]
Just to give you an example, today, we have allmost 20 vue-quasar apps integrated in our legacy front end (angular/bootstrap) : it works perfectly

Cause of the 20 apps, we can't upgrade all of them for each release of vue, quasar, etc - so as Martin FOWLER wrote, iFrame offers a perfect "isolation" level.
Take a look at Jira, Zendesk, Confluence, GMail, Facebook and maybe thousand other have iFrame for embedding features, apps or resolve "legacy compatibility" problem.

Anyway, it's just a point of view, AND really, there no problem for me if it's not fixed. Just think how not excluding new developper (or project) from Quasar just cause of bad Y positionning in iFrame :o)

Have a good evening, and really all congratulations for the HUGE job of you and your team.

**Comment by adrian-e** [comment]
Hi @sebastienroul I have the same problem you did two years ago! Using Quasar inside an iframe for exactly the same reasons (migrating in parts a legacy app).
Could you please tell me how you managed to solve it if you could? Have you kept your solution up to date with latest versions?
Regards!

**Comment by Davo911** [comment]
Same

**Comment by sebastienroul** [comment]
@adrian-e - Sorry for delay :)

Yes, we managed all of them qDialog, notify, etc... with : 
  1. Sometimes writing our own (ex. $dialog) with UGGGLY css think
  2. Sometimes writing stupid "MutationObserver" to catch the boxes and put them at the right place.

As @rstoenescu  said, we put it in a "common" folder for all project (we have more than 100).. and as Quasar has no more breaking change, it doesnt cost us a lot - even if it's very uggly.

Bye
