### ISSUE TITLE
Utils.openURL

### ISSUE THREAD

**Issue by kasp1** [quasarframework/quasar#529]
The `Utils.openURL` doesn't seem to work on iOS app exported with Cordova. I only tried in the emulator with iPhone SE. Cordova 6.5.0.

What I get in the console:
```
TypeError: undefined is not an object (evaluating 'navigator.app.loadUrl')
```

The standard way to open URLs externally in Cordova seems to be the inAppBrowser plugin https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser

Perhaps this function could first check whether the inAppBrowser plugin is available and if not, try the current way of opening URLs?

**Comment by rstoenescu** [comment]
Fix available in future v0.14.
