### ISSUE TITLE
Add features to QBtnDropdown/QTabs

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#5293]
Quasar allows you to use QBtnDropdown along side Tabs. It's be nice, if QBtnDropdown could work a little more cohesively with tabs.

1. Allow tab indicator with QBtnDropdown
2. Allow QTabs to control look of QBtnDropdown
  a. QTabs `inline-label` prop would let QBtnDropdown show normally
  b. Without QTabs `inline-label` prop, QBtnDropdown would use "stack" prop to mimic look of a QTab

Alternatively, a new QTabDropdown component could be created that essentially has the same behavior as QBtnDropdown

**Comment by hawkeye64** [comment]
Is it possible to put QBtnDropdown in the default slot so it shows up and you still get the selection underline? I would test this but just got out of the hospital and laying flat on my back with leg elevated so no access to my computer for the time being. Just mobile.

**Comment by smolinari** [comment]
It sort of works. 

https://codepen.io/smolinari/pen/VwweJzg?editors=1010

Scott

**Comment by hawkeye64** [comment]
Thanks for that @smolinari ! I'll give it a try.

**Comment by hawkeye64** [comment]
@smolinari Works great for what I am doing.

![image](https://user-images.githubusercontent.com/10262924/66765580-74333300-ee69-11e9-941f-0aa2ac981bc3.png)

Using stack on the QBtnButton didn't exactly woork out, so had to go with the slot. Yes, it's bit messy and wish it was a bit more stream-lined:

```html
        <q-tab
          v-if="isLoggedIn && checkFeature('remote-access')"
          name="remote-access"
          @click="remoteAccessMenu = true"
          style="max-width: 100px;"
        >
          <q-btn-dropdown
            v-model="remoteAccessMenu"
            auto-close
            stretch
            flat
          >
            <template #label>
              <div>
                <div class="row items-center justify-around no-wrap">
                  <q-icon name="fas fa-desktop" />
                </div>
                <div class="row items-center no-wrap">
                  Access
                </div>
              </div>
            </template>
```
Will close this ticket.

**Comment by hawkeye64** [comment]
The QBtnDropDown is still about 2 pixels too high compared to other tabs.
