### ISSUE TITLE
Swipe on QDrawer doesn't work in SSR mode

### ISSUE THREAD

**Issue by pirelle** [quasarframework/quasar#5300]
**Describe the bug**
Swipe-to-close on QDrawer doesn't work in SSR mode. In SPA mode works fine

**To Reproduce**
1. Create bootstrap project with quasar-cli
2. Run in SSR mode (like `quasar dev --mode ssr` or build)
3. See that swipe-to-close is not working

**Platform (please complete the following information):**
OS: linux
Node: 12.11.1
NPM: 6.11.3
Browsers: Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.2.2
