### ISSUE TITLE
How to remove "import 'quasar/dist/quasar.sass'" in .quasar/client-entry.js?

### ISSUE THREAD

**Issue by varjay** [quasarframework/quasar#5301]
Quasar will introduce all the css at once, it is recommended not to do anything, and often not so much content.

I have set "all: 'false'" in "quasar.conf.js", but will still introduce all quasar.sass.

Please help me, thank you.

**Comment by th3l0g4n** [comment]
As the Issue is closed I suppose you managed to remove the quasar.sass.
How did you do that?
