### ISSUE TITLE
extractDate returns wrong date

### ISSUE THREAD

**Issue by rmehner** [quasarframework/quasar#5305]
Hey there :wave:

**Describe the bug**
When using `extractDate` from Quasar.date, the returned date can be wrong.

```js
Quasar.date.extractDate('2019-09-26', 'YYYY-MM-DD'); // => Thu Sep 26 2019 00:00:00 GMT+0200 (Central European Summer Time)
Quasar.date.extractDate('2019-09-26T09:24:47.142Z', 'YYYY-MM-DD'); // => Sun Dec 31 1899 00:00:00 GMT+0100 (Central European Standard Time)
```

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/rmehner/pen/bGGpVEG

**To Reproduce**
1. Go to the codepen above

**Expected behavior**

I'd expect extractDate to be able to extract the correct date from the provided string, given that the pattern matches. Or do I understand something wrong?

**Additional context**
My current timezone ist CEST.

Have a great day and thanks for all the work so far!

**Comment by rstoenescu** [comment]
Hi,

The problem is that you don't specify the full mask for your input, but just the starting year-month-day.
However, I see the benefit on also having partial matching on the start of the input, as is your case. So this will be available in "quasar" v1.2.2.
