### ISSUE TITLE
QSelect closes QMenu since v1.2.0

### ISSUE THREAD

**Issue by MildConcussion** [quasarframework/quasar#5308]
**Describe the bug**
Choosing an option from QSelect, which is wrapped in QMenu, closes the QMenu. Introduced in v1.2.0.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Raaasmus/pen/abbNNwm

**To Reproduce**
1. Go to https://codepen.io/Raaasmus/pen/abbNNwm
2. Click on Notify
3. Choose an option from QSelect
4. QMenu closes

**Expected behavior**
Expected it to work as prior to v1.2.0. That selecting QSelect option inside QMenu would not close QMenu.

**Platform (please complete the following information):**
OS: macOS
Node: v12.11.1
Yarn: 1.19.1
Browsers: Vivaldi & Safari

**Comment by rstoenescu** [comment]
Fix will be available on "quasar" v1.2.2.
