### ISSUE TITLE
QList with QExpansionItem in SSR mode doesn't match virtual DOM

### ISSUE THREAD

**Issue by pirelle** [quasarframework/quasar#5310]
**Describe the bug**
This example from documentation https://quasar.dev/vue-components/expansion-item#Usage gives a warning in SSR mode:

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

**Comment by rstoenescu** [comment]
Hi,

1. Have you first investigated the source of the hydration error? It's highly unlikely that a Quasar component would generate one (it goes through a lot of testing before a version is released). However, I re-tested manually most of the examples in the QExpansionItem page and have not found any cause for the hydration error.
2. The source of the problem must be in your template. Please follow the steps here to investigate where is the issue in your template: https://quasar.dev/quasar-cli/developing-ssr/client-side-hydration#Handling-Hydration-Errors
