### ISSUE TITLE
QBtn: Long press handler

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#5311]
**Is your feature request related to a problem? Please describe.**
While OS-native buttons are capable of triggering on a long-press event, q-btn is not.

**Describe the solution you'd like**
Add an event handler for long presses on a button

**Describe alternatives you've considered**
https://blog.logrocket.com/building-a-long-press-directive-in-vue-3408d60fb511/

**Comment by pdanpdan** [comment]
Use `v-touch-hold` or `v-touch-repeat` on the QBtn
