### ISSUE TITLE
Prevent unsafe style inline on startup new app

### ISSUE THREAD

**Issue by streof** [quasarframework/quasar#5312]
**Is your feature request related to a problem? Please describe.**
After creating and building a new app, quasar dynamically styles 4 html elements with css on startup. When setting CSP headers, this behavior requires `style-scr: 'unsafe-inline'` which I think is unnecessary. A sample app can be found [here](https://github.com/stefan8888/quasar-helmet-test) and [this file](https://github.com/stefan8888/quasar-helmet-test/blob/master/src-ssr/index.js) contains the CSP settings.

**Describe the solution you'd like**
I would like to (at least manually) be able to prevent this kind of behavior. I had a quick look at the source code but could not find how to remove/undo the dynamically created styling. 

Another solution would be to include the styling as static css when a new app is created. Following this approach when building the app the css would automatically be extracted with `extractCSS` (which is already the case for any css added after creating a new app).

**Describe alternatives you've considered**
I am not aware of any feasible alternatives. Suggestions / other solutions are highly appreciated. 

**Additional context**
These are the 4 html elements that get dynamically styled:

`<div class="q-layout q-layout--standard" style="min-height:0px;">`

`<aside class="q-drawer q-drawer--left q-drawer--bordered fixed q-drawer--on-top q-drawer--mobile q-drawer--top-padding" style="width:300px;">`

`<div class="q-page-container" style="padding-top:50px;">`

`<main class="q-page flex flex-center" style="min-height:calc(100vh - 50px);">`

**Comment by rstoenescu** [comment]
Hi,

Sorry but there is no technical solution that would allow us to not use the style on some components.
