### ISSUE TITLE
Virtual Scroll stuck on fast scrolling

### ISSUE THREAD

**Issue by ttv20** [quasarframework/quasar#5313]
**Describe the bug**
When `scroll-target="body"`:
When trying to scroll fast or jump to the end of the list, in mobile and desktop the list is back to top or not rendering

**Codepen/jsFiddle/Codesandbox (required)**
copied from the example on the docs and add `scroll-target="body"`
https://jsfiddle.net/vumwaxp0/

**To Reproduce**
try to scroll as fast as you can, in mobile and desktop
or try to scroll with  the scrollbar to the end and then scroll to the top

**Expected behavior**
just work

**Platform (please complete the following information):**
Chrome 77 on Linux and Android

**Additional context**
I think this related, when I'm route from the list to other page and back it jump 10-30 items ahead

**Comment by pdanpdan** [comment]
You cannot define a maxHeight on the QVirtualScroll but set scrollTarget on body. Remove the maxHeight from the QVirtualScroll or remove scrollTarget.

**Comment by ttv20** [comment]
about the second problem (the last row), can you give me jsfiddle with router?
