### ISSUE TITLE
Virtual Scroll with router jump ahead

### ISSUE THREAD

**Issue by ttv20** [quasarframework/quasar#5314]
**Describe the bug**
when I'm using virtual scroll with `scroll-target="body"` go to another page and return back to the virtual scroll page it jump ahead

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/pfv83zq2/1/

**To Reproduce**
1. Scroll down and remember the first item number on the screen
2. Click on item
3. Click 'go back'
4. See that the first item number is greater then the previous  

**Expected behavior**
back to the same scroll location

**Platform (please complete the following information):**
Chrome 77 on Android and Linux

**Comment by pdanpdan** [comment]
If you need reproductible scroll positions use a `virtual-scroll-item-size` as close as possible to the real item size (in your case `:virtual-scroll-item-size="32"`).

Also please use the forum for help requests, and we have a pretty good documentation.

**Comment by ttv20** [comment]
@pdanpdan what about this case - https://quasar.dev/vue-components/virtual-scroll#Different-templates

**Comment by pdanpdan** [comment]
you cannot have the cake and eat it too :)

I'm that case you'll have scroll offset when you come back on the page.

But QVirtualScroll emits @virtual-scroll event, and you can save the scroll position and restore it when you come back on the page with scrollTo.

https://quasar.dev/vue-components/virtual-scroll#Scroll-to-position
