### ISSUE TITLE
Quasar brand colors don't fully map to MD style guides

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#5316]
**Is your feature request related to a problem? Please describe.**
When translating a MD style guide to a Quasar brand palette, it can be a bit confusing on how to map some colors.

- Quasar provides Primary but omits Primary-Light and Primary-Dark
- Quasar provides Secondary but omits Secondary-Light and Secondary-Dark
- Quasar provides Accent and it's unclear what this would map to on a  style guide. Based on the Quasar ThemeBuilder, I think it would typically be Secondary or Secondary-Dark.
- MD style guides define Background and Surface colors.
- MD style guides define several text/content colors, such as On-Primary, On-Secondary, On-Primary-Light/Dark, On-Seconary-Light/Dark, On-Background, On-Surface, On-Error, etc.

**Describe the solution you'd like**
I understand that you can add any additional variables you want, so it's not difficult to provide a more complete mapping to style guides. However, since Quasar is based on Material Design, I think it would be beneficial to have a more complete list of theme variables available out of the box for quicker theme setup and configuration.

What would be a killer feature is if Quasar would, by default, calculate some of these variables for you (with the option to override).  For example, when setting Primary, Quasar could auto-calculate Primary-Light, Primary-Dark, On-Primary-Light, On-Primary-Dark variables and so on. Many of the MD color palette generators do this for you.

**Comment by shinynet** [comment]
As a bonus, it would be cool if when specifying a color for a component, it would by default, pick the corresponding text color. For example,

`<q-btn color="primary">`
would, by default, set the text to on-primary and be the equivalent of:
`<q-btn color="primary" text-color="on-primary">`

**Comment by tomers** [comment]
> As a bonus, it would be cool if when specifying a color for a component, it would by default, pick the corresponding text color. For example,
> 
> `<q-btn color="primary">`
> would, by default, set the text to on-primary and be the equivalent of:
> `<q-btn color="primary" text-color="on-primary">`

In case maintainers would be reluctant to implicitly set text-color according to color, we could at least create an ESLint suggestion rule to hint the user that she may explicitly set the appropriate text-color.
