### ISSUE TITLE
Too many Jumping when virtual scroll Table contains image.

### ISSUE THREAD

**Issue by muthu32** [quasarframework/quasar#5317]
**Describe the bug**
When Virtual table contains dynamic height Images, then scrolling beyond index 100, result in too many jumping.

**https://codepen.io/muthu32/pen/abbvbpP**

**To Reproduce**
1. Scroll beyond index 100
2. Too many jumping will occur.
3. Watch the console that each index of image will automatically increase.

**Expected behavior**
Please provide a method to include image in virtual table without Jumping.

**Platform (please complete the following information):**
OS: mac os high sierra
Browsers:
Chrome 77

**Additional context**
Please provide on load recompute feature on Image load.

**Comment by pdanpdan** [comment]
A slightly improved version: https://codepen.io/pdanpdan/pen/GRRqmyy?editors=1010
I'll think of something.

**Comment by rstoenescu** [comment]
Not perfect, but better.
Improvement will go into "quasar" v1.4.1
