### ISSUE TITLE
QSelect doesn't call filter function on cyrillic characters on mobile devices

### ISSUE THREAD

**Issue by D5T** [quasarframework/quasar#5318]
**Describe the bug**
QSelect doesn't call filter function when entering cyrillic characters on mobile devices. There is probably an issue with change detection logic. Entering non-cyrillic characters (e.g. space, numbers) proceeds normal behaviour.

**Demo link**
https://quasar.dev/vue-components/select#Example--Basic-autocomplete

**To Reproduce**
1. Open the provided link on a mobile device
2. Click on autocomplete
3. Enter a cyrillic character (do not paste it), e.g. "б", "ю"
4. Check filter state

**Expected behavior**
Entering cyrillic characters should call the filter function, but it doesn't.

**Platform:**
OS: Android 10
Browsers: latest Chrome (77.0.3865.116), latest Mozilla.

**Comment by pdanpdan** [comment]
Can you please test the same with a QInput - check if the model is updated after each character.

It might be related to composition. Also please tell what keyboard are you using.

Thank you.

**Comment by D5T** [comment]
@pdanpdan The same issue with QInput, model doesn't update until the keyboard is being closed or the search button pressed. Using the latest version of Gboard.

**Comment by pdanpdan** [comment]
Thank you very much. One more test, if you can - do you have another device with Android 9? Is there the same problem? Because we don't have a device with 10 to test.

**Comment by D5T** [comment]
@pdanpdan Same problem on Android 9.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.2.3
