### ISSUE TITLE
QColor + QPopupProxy bug - random closing

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#5319]
I've been using QColor (which is awesome) but I've noticed that when I use it in conjunction with a QPopupProxy (like here: https://quasar.dev/vue-components/color-picker#With-QInput) that if you click enough different colors eventually the popup will close automatically--its like it's losing focus automatically somehow.

You can reproduce this bug here: https://quasar.dev/vue-components/color-picker#With-QInput

I'm in Chrome (windows desktop)

1) Click the dropper icon to bring up the QColor component.
2) Click around random colors, but keep focus on the QColor
(sometimes you have to click only a few times, sometimes I had to click 35 times... but it will always close eventually without explanation.

Expected result: popup *only* closes when losing focus.

**Comment by rfox12** [comment]
@metalsadman  You're right!  Thanks for the clarification here.  Looks like pdanpdan is working.  Hopefully we can allow drag-click without closing the popup?  Is that the plan?

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "quasar" v1.2.3
