### ISSUE TITLE
Display issue with focused QSelect in Firefox [v1.2.2]

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5320]
**Describe the bug**
There is a visible artifact to the left of focused `QSelect` controls in Firefox. It looks kinda like a backtick.

**Codepen/jsFiddle/Codesandbox (required)**
You can see it in the docs: https://quasar.dev/vue-components/select

**To Reproduce**
1. Go to https://quasar.dev/vue-components/select in Firefox
2. Click on any QSelect

**Expected behavior**
It shouldn't be there.

**Screenshots**
![image of QSelect](https://imgur.com/CVWxt9F.png)

**Platform**
Quasar:1.2.2
OS: Windows_NT(10.0.18362) - win32/x64
Browsers: Firefox 69.0.3

**Additional context**
Screenshots from Windows but also verified present in Firefox on macOS.
Seems to be caused by the `<div>` inside `.q-field__native`, highlighted here:
![image of Firefox devtools](https://imgur.com/ouUbZgw.png)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "quasar" v1.2.3
