### ISSUE TITLE
QSlideItem doesn't work with Firefox in mobile simulation.

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#5334]
**Describe the bug**
QSlideItem doesn't function when running in Firefox mobile view when touch simulation is turned on. I've tested in Chromium and it appears to work in all situations: desktop, mobile, touch simulation turned on or off. I have not tested in any other browsers.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/DevinHolloway/pen/YzzGLeo

**To Reproduce**
1. Go to the above codepen in Firefox
2. Verify that the single item in the list can be clicked on as well as slid to the left.
3. Open developer tools and enable "Responsive Design Mode"
4. Select any mobile platform, such as Nexus 5X
5: Make sure "Touch Simulation" is turned on

Sliding the list item no longer works. In addition, the item must be double-clicked in order to trigger the click event.

If you then disable touch simulation, all functionality is restored.

**Platform (please complete the following information):**
OS: Linux(5.0.0-31-generic) - linux/x64
Browsers: Firefox DE 71.0b1 (64-bit)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.2.3
