### ISSUE TITLE
q-tooltip / Input event fires also after hiding

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5337]
**Describe the bug**

This is a catchup from a discord Discussion Channel Components
Wednesday : 16.10.2019 - >18:20 
(myself was not included .. so may there are some more details from
metalsadman)

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/metalsadman/pen/zYYBjqj?&editable=true&editors=101

**To Reproduce**

Scrolling down the event is multiple fired

This was a workaround to make a delay for the hiding. As there is a option for
showing delay - it would be nice to have a option also for the hiding delay.
(i would also open a feature request for this)

**Comment by pdanpdan** [comment]
I suppose you want something like this: https://codepen.io/pdanpdan/pen/XWWjYOr?editors=1010
Just use `:value` instead on `v-model`

**Comment by ibrainventures** [comment]
thanks for this super-super-fast response ... only for understanding:
you made a better event toggling but this input event is constantly fired 
during scrolling .. i think this was more worry about this issue ..

Is this for performance reason no problem?

**Comment by pdanpdan** [comment]
Thanks for reporting, I found the problem.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.2.3
