### ISSUE TITLE
Add option to persist loading indicator for QInfiniteScroll to make scroll stable

### ISSUE THREAD

**Issue by haivp3010** [quasarframework/quasar#5339]
**Is your feature request related to a problem? Please describe.**
The current implementation shows the loading indicator whenever loading happens and hides it as soon as the loading is complete. This causes a problem when you set loading offset to a very small number and scroll to the very end, at which point the loading indicator got appended to the DOM and *hidden* below unless you scroll a little bit to fully see it.
I feel it frustrating to scroll down to the end just to be pushed up back because a loading has been added, and I can't even see the beauty of the loading bar.

**Describe the solution you'd like**
I'd like to have an option to make the loading static regardless of the actual loading state. For example, we could have a boolean `static-loading` props to tell whether to keep the loading in the DOM tree or not. When we have nothing more to load, we simply change the boolean to `false` to hide the loading.
This way, the scroll position and DOM tree is not disturbed from time to time.

**Describe alternatives you've considered**

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Good idea here. It won't require any new prop as I think this should actually be the default behavior. Will be available in "quasar" v1.2.8.

Thank you for filling this ticket.

**Comment by Demivan** [comment]
@rstoenescu Can this be changed to require prop or at least have a prop to disable this behavior?
Now when scroll finishes there is a blank space in place of a loader. https://codepen.io/demivan/pen/MWYwQxx
I have created issue for it: #5804

**Comment by pdanpdan** [comment]
I'll comment in the main issue.
