### ISSUE TITLE
Google Map component

### ISSUE THREAD

**Issue by Nelzio** [quasarframework/quasar#5342]
**Is your feature request related to a problem? Please describe.**
I need a component that use google map.

**Describe the solution you'd like**
Component that use google map where is possible to indicate a position (Lat, Long) with props.

**Describe alternatives you've considered**
https://vuejs.org/v2/cookbook/practical-use-of-scoped-slots.html
https://www.npmjs.com/package/vue2-google-maps

**Comment by rstoenescu** [comment]
Hi,

Why not use those? Quasar doesn't needs to reinvent the wheel on them..
