### ISSUE TITLE
Memory leak on q-select (important)

### ISSUE THREAD

**Issue by furyscript** [quasarframework/quasar#5343]
If you try to search on a `q-select` with static values, it break the page (goes on memory leak).

Try to press some letter after dropdown of the first element is shown and click fast outside:
https://quasar.dev/vue-components/select#Example--Design-Overview

It's a very blocking bug for applications!
We have last chrome version.

**Comment by LovaBP** [comment]
I have same issue +1

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.2.3.
