### ISSUE TITLE
Uploader pickFiles() don't open file dialog in Chrome

### ISSUE THREAD

**Issue by caiotarifa** [quasarframework/quasar#5346]
**Describe the bug**

Trying to make my own implementation of the button to open the dialog box for choosing a file, the pickFiles method has no effect.

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/caio/pen/LYYbEpm

**To Reproduce**

Click in the "add" button.

**Expected behavior**

Open system's file dialog.

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Chrome

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/uploader#Slots
