### ISSUE TITLE
Cordova fail build to .apk

### ISSUE THREAD

**Issue by d0peCode** [quasarframework/quasar#5355]
I'm trying to build my quasar project to .apk.

Within my app I do several http call to my NodeJS API which lays on heroku server. I made sure that I call correct URLs (my heroku server).

My config.xml is in src-cordova is:

    <?xml version='1.0' encoding='utf-8'?>
    <widget id="app.mobile.quickmargo.cordova.id" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
        <name>quickmargo</name>
        <description>app for quickmargo mobile</description>
        <author email="dev@cordova.apache.org" href="http://cordova.io">
            Apache Cordova Team
        </author>
        <content src="index.html" />
        <plugin name="cordova-plugin-whitelist" spec="1" />
        <access origin="*" />
        <allow-intent href="http://*/*" />
        <allow-intent href="https://*/*" />
        <allow-intent href="tel:*" />
        <allow-intent href="sms:*" />
        <allow-intent href="mailto:*" />
        <allow-intent href="geo:*" />
        <platform name="android">
            <allow-intent href="market:*" />
            <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
                <application android:usesCleartextTraffic="true" />
            </edit-config>
        </platform>
        <platform name="ios">
            <allow-intent href="itms:*" />
            <allow-intent href="itms-apps:*" />
        </platform>
    </widget>

When I run my project as development to Android Studio AVD emulator everything works fine. 

When I build my app I get app-release-unsigned.apk and app-debug.apk when I try to run first one nothing happen I just got meaningless info that file is broken but when I try to run app-debug.apk I got error:

> net::ERR_CONNECTION_REFUSED (http://192.168.0.106:8080/)

[![enter image description here][1]][1]

( screenshot is from BlueStacks emulator )

I was looking for this error in SO and I found [this answer][2] which I totally don't understand. What I have wrong?

<hr>

I was trying several things and now build don't even give me app-debug.apk anymore.. I see `debugging....... no` when i `run quasar build -m android`.

  [1]: https://i.stack.imgur.com/wSw03.png
  [2]: https://stackoverflow.com/a/42017362/8425145

**Comment by rstoenescu** [comment]
Hi,

Opening tickets for non-Quasar questions is not ok. Also not specifying which Quasar package versions you are using (as requested per Github ticket template) is again not ok and creates a lot of back and forth friction.

Please use our https://forum.quasar.dev or https://chat.quasar.dev for questions.

As a sidenote, you don't need this part in your config if you are using `@quasar/app v1.2+`
```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
    <application android:usesCleartextTraffic="true" />
</edit-config>
```
