### ISSUE TITLE
template's button not submitted

### ISSUE THREAD

**Issue by bodamat** [quasarframework/quasar#5358]
Good evening! I find a bug!
I use component input with send button. I add attribute type=“submit” to q-btn and add @submit to q-form. When I click button form not submitted, but when q-btn outside the <template> and <q-input> form submitted. Can you help me, please?
Quasar v1.2.4

It worked in latest version. I see in video, where version 1.0.5. 
This video: https://youtu.be/gw4bSyBgZsQ?t=752

https://codesandbox.io/embed/codesandbox-app-7bs6u (in 'pages/Index.vue')

P.S. When you uncomment q-btn out q-input than it work, but button needs in q-input.

**Comment by pdanpdan** [comment]
Click event is prevented now to propagate outside of append, prepend, before and after slots.
Just add a `@click` event that calls `sendMessage` like here https://codesandbox.io/s/codesandbox-app-m958u

**Comment by bodamat** [comment]
Thank you very much!

**Comment by smolinari** [comment]
I just want to note, I also asked @bodamat to post the issue. I had thought about just adding the @click event to the button, but wasn't certain, as the video had shown it working before without it. Thank you Dan for sorting the solution out. 

Scott
