### ISSUE TITLE
Template's button not submitted

### ISSUE THREAD

**Issue by bodamat** [quasarframework/quasar#5359]
**Describe the bug**
Good evening! I find a bug!
I use component input with send button. I add attribute type=“submit” to q-btn and add @submit to q-form. When I click button form not submitted, but when q-btn outside the and form submitted. 
Can you fix this problem, please?

It worked in latest version. I see in video, where version 1.0.5.
This video: https://youtu.be/gw4bSyBgZsQ?t=752

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/embed/codesandbox-app-7bs6u (in 'pages/Index.vue')

P.S. When you uncomment q-btn out q-input than it work, but button needs in q-input.

**To Reproduce**
1. Q-btn in q-input
2. Click the button with type="submit"
3. Form not submitted

**Platform (please complete the following information):**
OS: All
Node: 12 
Browsers: All
Quasar: 1.2.4

**Comment by pdanpdan** [comment]
Click event is prevented now to propagate outside of append, prepend, before and after slots.
Just add a @click event that calls sendMessage like here https://codesandbox.io/s/codesandbox-app-m958u

**Comment by bodamat** [comment]
Thank you! Sorry to be alarmed
