### ISSUE TITLE
keep-alive doesn't works with QTabPanels

### ISSUE THREAD

**Issue by ryhn** [quasarframework/quasar#5363]
I'm using this code block with keep-alive prop. But it is not working. When the tab change all content in tab-panels re-renders.

Can you confirm "keep-alive" prop is working or what can I be doing wrong

```
<q-tabs v-model="activeTab">
      <q-tab name="tab1" label="Hard Drives" />
      <q-tab name="tab2" label="CPU" />
</tabs>
<q-tab-panels v-model="activeTab" keep-alive>
      <q-tab-panel name="tab1">
            //////
      </q-tab-panel>
     <q-tab-panel name="tab2">
            //////
      </q-tab-panel>
</q-tab-panels>

```

**Comment by pdanpdan** [comment]
Please provide a codepen showing the problem and details on version of quasar. They are requested in the issue template.

**Comment by ryhn** [comment]
Quasar: v1.2.4
Sorry, I can't provide codepen sample now.  

The issue can be seen in the browser dev-tool elements tab.  QTabsPanel content completely removed and refreshing to a new content

**Comment by pdanpdan** [comment]
Try to add a key to each QTabPanel

**Comment by pdanpdan** [comment]
Any news on this?

**Comment by rstoenescu** [comment]
The content is removed, but the component is kept alive in memory... which is what keep-alive does as per designed....

**Comment by ryhn** [comment]
Adding a key fixed the re-render issue.  
But my problem is using <object> tag for svg view like <object src="image.svg">
The <object> element parent class changed to visibility hidden or display:none always fetch .svg file. I think this is a browser  issue

Thanks.
