### ISSUE TITLE
Support 'append' anywhere 'to' is supported

### ISSUE THREAD

**Issue by shinynet** [quasarframework/quasar#5365]
**Is your feature request related to a problem? Please describe.**
My specific need is for QBtn, but it would makes sense for any component that integrates with vue-router. Similar to the current support of 'replace', I'd like to see support for 'append'

**Describe the solution you'd like**
When on a route such as /products, and the need to navigate to a specific product, one needs to do something similar to:
`<q-btn to="products/123">`
For simplicity, I'd like to be able to use:
`<q-btn to="123" append>`

If taken into consideration, also consider adding some additional vue-router features that could be useful, such as exact, active-class, etc.

**Comment by pdanpdan** [comment]
Short summary of current situation:

```javascript
{
  to: [String, Object],
  exact: Boolean,
  append: Boolean,
  replace: Boolean,
  activeClass: String,
  exactActiveClass: String
}
```

Are already supported on:
- QBreadcrumbsEl
- QExpansionItem
- QItem
- QRouteTab

Partially supported for:
- QBtn and derivates (to, replace)
- QFabAction (uses QBtn)
- QPagination (in PR, uses QBtn)
- GoBack (to as value, always replace)

The reason for partial support is that QBtn does not use use <router-link> directly.

For the moment you can wrap the QBtn as scopedSlot in a <router link> (see https://router.vuejs.org/api/#v-slot-api-3-1-0).

I put this summary here in order to evaluate the existing situation and possible evolution paths.

**Comment by shinynet** [comment]
Thanks for the explanation. And using router link slot is a good way to handle it for now.

**Comment by rstoenescu** [comment]
https://quasar.dev/vue-components/button#Example--Scoped-slot-of-RouterLink

Not "for now". This IS the way to do it. That if you care about performance.

**Comment by shinynet** [comment]
A bit odd (and confusing) to support just a partial implementation of router-link. I'd suggest either making the router-link wrapper approach the only way to integrate with vue-router (and deprecate the 'to/replace' attributes from button) or possibly adding a new button variation (QBtnRouter) that does work with router.

**Comment by rstoenescu** [comment]
It's not odd at all. To+Replace are just syntactic sugar and are calling $router.push/replace() under the covers. That's the value in it. Unfortunately, Vue Router does not allow the append feature in the programmatic way too. Also no link state. Using RouterLink is overkill if you just want to go to a route (albeit without append). We take performance into account and also the footprint. There's no real value to add another component just to catch 2-5% of the use cases, when there's a reasonable approach (see link in my previous comment).

**Comment by shinynet** [comment]
Yeah, I get how that all works, I just fail to see the difficulty, so I assumed you were making a philosophical argument rather than a technical one. Like, just glancing through the source code, it seems like a one line addition:

```
      const go = () => {
        const to = this.append ? this.$router.currentRoute.path + this.to : this.to
        const res = this.$router[this.replace === true ? 'replace' : 'push'](to)
      }
```
But not like I've tested that or anything, so maybe there's more to it than what it seems.

**Comment by rstoenescu** [comment]
Unless the "to" prop is in Object format. Or the Object form has a "name" prop in it. Or maybe when the current route also has query string. Or.... And so the hell breaks loose :)
Things can slightly improve is we only take the String format, but then there's going to be a lot of confusion out of the box when it will work and when it won't. Lots have to be added to docs...

What I do appreciate is your willingness to improve Quasar <3

**Comment by shinynet** [comment]
Good call on the multiple shapes that 'to' can be defined as. I could see a situation where there existed a common mixin, that correctly parsed all that, for components that integrate with router... but you've convinced me it's probably not worth the effort when router-link slots work and are painless to implement.

**Comment by rstoenescu** [comment]
Yes, exactly. And Quasar's footprint can remain low.
