### ISSUE TITLE
q-separator invisible inside column

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#5371]
**Describe the bug**
If I put a separator as direct child of a .column layout, its not visibile cause 0 height.

The reason is that it inherits following rule:
```
.column > .col, .flex > .col, .column > .col-auto, .flex > .col-auto, .column > .col-grow, .flex > .col-grow, .column > .col-shrink, .flex > .col-shrink, .column > .col-xs, .flex > .col-xs, .column > .col-xs-auto, .column > .col-0, .column > .col-xs-0, .column > .col-1, .column > .col-xs-1, .column > .col-2, .column > .col-xs-2, .column > .col-3, .column > .col-xs-3, .column > .col-4, .column > .col-xs-4, .column > .col-5, .column > .col-xs-5, .column > .col-6, .column > .col-xs-6, .column > .col-7, .column > .col-xs-7, .column > .col-8, .column > .col-xs-8, .column > .col-9, .column > .col-xs-9, .column > .col-10, .column > .col-xs-10, .column > .col-11, .column > .col-xs-11, .column > .col-12, .column > .col-xs-12, .flex > .col-xs-auto, .flex > .col-0, .flex > .col-xs-0, .flex > .col-1, .flex > .col-xs-1, .flex > .col-2, .flex > .col-xs-2, .flex > .col-3, .flex > .col-xs-3, .flex > .col-4, .flex > .col-xs-4, .flex > .col-5, .flex > .col-xs-5, .flex > .col-6, .flex > .col-xs-6, .flex > .col-7, .flex > .col-xs-7, .flex > .col-8, .flex > .col-xs-8, .flex > .col-9, .flex > .col-xs-9, .flex > .col-10, .flex > .col-xs-10, .flex > .col-11, .flex > .col-xs-11, .flex > .col-12, .flex > .col-xs-12, .column > .col-xs-grow, .flex > .col-xs-grow, .column > .col-xs-shrink, .flex > .col-xs-shrink {

    height: auto;
    min-height: 0;
    max-height: 100%;

}
```
If I change that rule to min-height: 1px it appears.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jigarzon/pen/RwwKONM

**Platform (please complete the following information):**

Operating System - Linux(4.19.79-1-MANJARO) - linux/x64
NodeJs - 12.11.1

Global packages
  NPM - 6.12.0
  yarn - 1.19.1
  @quasar/cli - 1.0.0
  cordova - Not installed

Important local packages
  quasar - 1.2.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.2.1 -- Quasar Framework local CLI
  @quasar/extras - 1.3.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.6.4 -- Babel compiler core.
  webpack - 4.41.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.8.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

**Comment by rstoenescu** [comment]
Hi,

Please put `style="height: 1px"` on QSeparator there. The problem is with `height: auto`, which is absolutely required when using `column`. However, in this case the side-effect is that it squashes the QSeparator.
