### ISSUE TITLE
QTd QTh auto-width with cell separator removes cell border

### ISSUE THREAD

**Issue by rvyas** [quasarframework/quasar#5374]
**Describe the bug**
When QTable separator is cell and applying auto-width on QTd (other than last column), it does apply auto-width however removes the cell border

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/rvyas/pen/MWWpyjv

**To Reproduce**
1. define QTable with separator as cell
2. body slot, define tr and td
3. set q-td tag with auto-width
4. Check cells with auto-width does not display cell border

**Expected behavior**
Cell border should be visible with auto-width on QTd.

**Screenshots**
No cell border for protien, sodium, calcium columns
![image](https://user-images.githubusercontent.com/2732444/67338079-33789100-f4dd-11e9-8113-759c8f8fa4ae.png)

**Platform (please complete the following information):**
OS: Linux
Node:  10.15.3
NPM: 
Yarn: 1.13.0
Browsers: Chrome

**Additional context**
Cell border stays if applying auto-width on last column.

**Comment by rstoenescu** [comment]
Hi,

It was on purpose, because of a previous requirement that is now obsolete.
Fix will be available in "quasar" v1.2.6.

**Comment by rvyas** [comment]
Thank you for quick fix.
