### ISSUE TITLE
too long title of q-step break icons

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#5380]
**Describe the bug**
too long title of `q-step` breaks icon

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/matro-skin/pen/YzzZZzr

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Chrome

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
This will go into "quasar" v1.2.6.

**Comment by matro-skin** [comment]
Not fixed in 1.2.6...
http://prntscr.com/poed8g

**Comment by pdanpdan** [comment]
It looks good here: https://codepen.io/pdanpdan/pen/JjjJNYy

**Comment by matro-skin** [comment]
btw, I've updated framework to 1.2.6 and see the same...
ok, I'll to use short labels

**Comment by metalsadman** [comment]
Restart your dev server.

**Comment by matro-skin** [comment]
of course I've done... what can I check more? maybe any css property?
