### ISSUE TITLE
Q-Dialog Side Effect over Q-Select

### ISSUE THREAD

**Issue by Pr3d4dor** [quasarframework/quasar#5381]
**Describe the bug**
When you open a Q-Dialog anywhere inside a Quasar app, the label of all the Q-Selects behave in a weird way.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/helker/pen/mddWXrZ

**To Reproduce**
1. Create a Q-Dialog
2. Create a Q-Select inside the Q-Dialog with a label.
3. Open the Q-Dialog and see the Q-Select label.

**Expected behavior**
The label of the Q-Select must be show in a correct way.

**Platform (please complete the following information):**
OS: Ubuntu 16.04
Node: 10.16.0
NPM: 6.10.0
Yarn: 1.17.3
Browsers: Firefox and Google Chrome
iOS: -
Android: -
Electron: -

**Additional context**
Not only the Q-Select inside the Q-Dialog behave in weird way, but all the Q-Select of the app become weird after opening a Q-Dialog.

**Comment by pdanpdan** [comment]
ASL PLS :) There is a reason Quasar version is required in the issue template.

Can you reproduce it in the latest version?
I updated the codepen for you.

Also weird is not a description of what we should look for.

**Comment by Pr3d4dor** [comment]
The label of the Q-Select is not displayed inside the Q-Dialog.

I'm using
Pkg Quasar v1.2.5
Pkg @quasar/app v1.2.2

**Comment by pdanpdan** [comment]
Sorry, I forgot to put the updated URL: https://codepen.io/pdanpdan/pen/YzzZeBz

I suppose you mean that if you don't put a min-width on the QSelect and it is empty then the width is very small and you can't see the label. Just add a min-width.

**Comment by Pr3d4dor** [comment]
Sorry for the late feedback but we managed to solve the problem.

The css min-width did help but it wasnt the sole problem.

Thanks for the help.

**Comment by smolinari** [comment]
What was the cause of the problem and how did you solve it?

Scott

**Comment by Pr3d4dor** [comment]
The cause of the bug was one or more packages of our package.json

We deleted node_modules and installed all the dependencies again and the bug was fixed.
