### ISSUE TITLE
Issue extendending quasar's webpack default loader

### ISSUE THREAD

**Issue by furyscript** [quasarframework/quasar#5382]
I have a problem extending webpack.
I need to override a default loader (`url-loader`) used by quasar, but the only way I've found is to access directly to the array `module/rules` like this:
```
build: {
      extendWebpack (cfg) {
        cfg.module.rules[2].use[0].options.name = 'img/[path][name].[ext]'
        console.log('==>', cfg.module.rules[2].use)
      }
    },
```
At position 2 there is `url-loader`.
**Any idea to do it better without access to the index directly?**

Another question that can I reference to another repository, is that quasar don't use `[path]` for `url-loader`.
I think this not a good idea, because some external vue module doesn't think about it.
See for example error I got using this plugin: https://github.com/lipis/flag-icon-css/issues/627
It's because the image assets file have the same name in 2 different folder, but webpack compile into one.
**Ok, I can override quasar's `url-loader`, but maybe quasar can have it by default, no?**

Thanks!

**Comment by rstoenescu** [comment]
Hi,

Please use our https://forum.quasar.dev or https://chat.quasar.dev for questions.
