### ISSUE TITLE
prop "disable" in qtooltip

### ISSUE THREAD

**Issue by elperro123** [quasarframework/quasar#5385]
**Is your feature request related to a problem? Please describe.**
Would be useful to disable a qtooltip e..g based on the current state of a qmenu that overlaps. Having a prop in the qtooltip would make the problem easy to solve in a smooth way i.e. v-bind the prop to the v-model of the qmenu. This probably makes sense on other components too.

**Describe the solution you'd like**
Add a disable prop to Qtooltip.

**Comment by smolinari** [comment]
You can use the target prop and just target it to false. 

https://codepen.io/smolinari/pen/LYYWJOz?editors=1010

Scott

**Comment by elperro123** [comment]
Well, using target I go this:
https://codepen.io/elperro88/pen/abbJaeV?editors=1010
i.e. the tooltip wouldnt close on the qmenu open.

**Comment by elperro123** [comment]
could also handle events to solve the issue e.g. trigger hide on the open of the qmenu, but yes, might be a nice to have to have a sort of disable property just for convenience in some situations.

**Comment by pdanpdan** [comment]
Check here: https://codepen.io/pdanpdan/pen/gOOmBaN?editors=1010

**Comment by elperro123** [comment]
Hmm thanks, didnt know could use the value prop like that, but yes, still not fully smooth as it allows to then see the tooltip if hover the button while the menu is still open.

Well, is not a big deal, the small issue can be solved, but it is just a proposal for a prop to be considered in the future (low prio) as could facilitate some scenarios.

**Comment by elperro123** [comment]
e.g. using both recommendations the result could be achieved with a better result that I had before handling events:
`<q-tooltip :target="!is_profile_menu_open" :value="is_profile_menu_open ? false : void 0">Account</q-tooltip>`

Please close the issue if dont see as necessary to add the prop, was just a quick idea for a nice to have.

**Comment by rstoenescu** [comment]
Hi,

There is no need for a "disable" prop. Just use "v-if" on it. From a performance perspective, it doesn't makes sense to still have it in memory if it's not being used. This is why I am enforcing the use of "v-if" and will not implement "disable" prop.

https://codepen.io/rstoenescu/pen/zYYwGBE?editors=1010

**Comment by smolinari** [comment]
🤦‍♂ v-if? OMG, why didn't think of that! 😊 

Scott

**Comment by elperro123** [comment]
damm, v-if heh. Thanks :D
