### ISSUE TITLE
Add img native lazy loading + fallback

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#5386]
**Is your feature request related to a problem? Please describe.**
Need of optimizing critical path of websites deferring load of multimedia below the fold.

**Describe the solution you'd like**
Implement https://web.dev/native-lazy-loading best practices for lazy loading, now that native lazy loading is a real thing on Chrome 76 at least.

[This article](https://www.smashingmagazine.com/2019/05/hybrid-lazy-loading-progressive-migration-native/) also presents a _sort of polyfill_ ([lazyload](https://github.com/verlok/lazyload)) in vanilla JS which seems to be well known and with an extensive documentation.

Usage of `loading="lazy"` could be detected at build time (via a webpack loader?) and, if found:
- add global feature detection and fallback library;
- for every images/videos/iframe where lazy loading is requested, trigger rewriting of `src`, `srcset`, etc into corresponding `data-src`, `data-srcset`, etc.

The tricky part could be to manage dynamically loaded pages, because the fallback library checks images at load or calling its `update` moment at the right time.

This could directly become the default because it would be opt-in by design (no `loading="lazy"`, no code to manage it).
Chrome will probably switch its `loading="auto"` default to be `lazy` instead of `eager` in a while, hopefully other browsers will follow it providing native lazy loading for everyone :)

Maybe also adding a `lazy` prop on `QImg` could be a good idea, which would just resolve in adding `loading="lazy"` if the previously described webpack loaded takes care of everything else.

**Describe alternatives you've considered**
Same stuff, but non directly integrated into Quasar, maybe with an app-extension.

**Additional context**
---

**Comment by hawkeye64** [comment]
@IlCallo 
Not sure if it is exactly applicable, but v1.3 of Quasar (unless something changes) will have the `v-intersection` directive. Which means, you can load elements and components as they come into the visible viewport area. Similar idea to lazy-loading. If this will suffice, then close this issue. Thanks.

**Comment by hawkeye64** [comment]
Btw, you can also use the scroll-fire directive now, to achieve the same thing.

**Comment by IlCallo** [comment]
My suggestion was to automatically enable the behaviour for all developers so that everyone can get lazy loading with 0 config on their size, making Quasar app better than other apps framework by default.

Something similar to when someone started applying prefixer by default to avoid devs the hurdle of manually adding CSS rule prefixes :)

Let apart implementation (of course you can use Quasar-native features to manage intersection), are you interested into adding this kind of feature into Quasar core or you'd prefer to keep it in an app extension and make devs search for it by themselves?

**Comment by hawkeye64** [comment]
That would be a question for @rstoenescu to answer.

**Comment by lmfmaier** [comment]
I would very much support the idea of having a lazy prop on QImg. 

My app is heavily relying on infinite scrolls (in fact, every list is wrapped in an infinite scroll container). I noticed that the new intersection component doen't really work well within an infinite scroll container (I will probably open another issue on this).

I will try the scroll fire directive

**Comment by rstoenescu** [comment]
Why not try with [QIntersection](https://quasar.dev/vue-components/intersection) or [Intersection directive](https://quasar.dev/vue-directives/intersection)?

**Comment by IlCallo** [comment]
Point of my proposal was to start a discussion about appling the lazy loading behaviour by default (or conditioned to a particular attribute presence), not on how to do it.
I know it's fairly simple to achieve it in multiple ways, but I think that if it is enabled by default it's one less thing devs should think about when they get to optimizations :)

Like codebases are now minified and uglified by default, CSS rules are prefixed by defaults, etc.

**Comment by eladcandroid** [comment]
What about image fallback feature itself on Q-Img? Can we achieve it currently?

**Comment by pintaf** [comment]
+1, would love to see this integrated by default.
