### ISSUE TITLE
Q1 - QUploader IE 11/Edge

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#5390]
**Quasar:**
quasar - 1.2.5
@quasar/app - 1.2.2

**What did you get as the error?**
Clicking the plus symbol in IE 11/Edge doesn't do anything. You can drag files onto the QUploader and it will work.

**What were you expecting?**
File browser like Chrome.

**What steps did you take, to get the error?**
Click the plus symbol

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.2.6.

**Comment by sn0rcha** [comment]
Many thanks for fixing :)
