### ISSUE TITLE
Close dialogs and drawer with back button in PWA (browser)

### ISSUE THREAD

**Issue by renancavalieri** [quasarframework/quasar#5394]
It would be very useful if we could close dialogs and drawers using back button while on PWA. This feature is present on Cordova, but not on PWA (browser). 

**Why this feature is important?**
This allow us to create PWA applications that feels like Cordova, that can be installed through the browser (Chrome on Android, at least). Basic applications that don't depend on any Cordova plugin can be easily replaced by PWA, also the updates are much more easy to handle. In my case, I'm using Cordova **only** because the back button handling. It's a very important to UX.

**Alternatives**
If this cannot be done in Quasar, an alternative is to expose some method to allow check if there is any opened dialog and then close dialogs globally, so we can implement our own back button handling using popstate (for example). I found a way close the drawer globally but didn't find none to close dialogs. 

Sorry if this seems to be a bad idea, I really don't know how Quasar works internally, but for UX is very important, especially when PWA applications are becoming more popular.

**Comment by renancavalieri** [comment]
Thank you, I implemented something similar and is working fine.

**Comment by MHassanSaqib** [comment]
Any update on it? Did quasar provide any recommendation for doing it?

**Comment by mrtdeh** [comment]
I strongly need this feature, any update on it?

**Comment by dilungasr** [comment]
Any updates.... 2022?

**Comment by pdanpdan** [comment]
You can do both of them by default as long as you have a route for opening the drawer/dialog

check other independent solutions:
https://stackoverflow.com/questions/43329654/android-back-button-on-a-progressive-web-application-closes-de-app
https://discourse.wicg.io/t/set-back-button-url-in-pwas/4112/6
https://9to5answer.com/android-back-button-on-a-progressive-web-application-closes-de-app

**Comment by drogerie21** [comment]
need the same functionality. users on mobile browsers use the backbutton to close (or cancel) dialogs. this would be a great feature if it comes out of the box of quasar!
