### ISSUE TITLE
[QSelect] - IE11 - Menu does not open.

### ISSUE THREAD

**Issue by huy-tran** [quasarframework/quasar#5395]
**Describe the bug**
Going to the Quasar Documentation https://quasar.dev/vue-components/select on IE11, clicking on select boxes doesn't give you options menu unless you click on `use-input` **q-select**.

`q-select` works perfectly on other browsers but IE11.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/select

**To Reproduce**
1. Go to https://quasar.dev/vue-components/select
2. Click on any `q-select` component except `use-input` ones
3. Options menu does not show.

**Expected behavior**
Options menu should show on click.

**Platform (please complete the following information):**
OS: `Windows`
Node: `10.10.0`
NPM: `6.4.1`
Yarn: `1.12.3`
Browsers: IE11
iOS:
Android:
Electron:

---

The issue on IE is because of the click event does take effect on this last DOM element  
```html
<div tabindex="0" id="qf_f461b682-fa45-21a0-5c3e-0e93a60ebf45" class="no-outline"></div>
``` 
This then triggers the click event listener and then toggle the options menu.

Cheers!

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.2.6.
