### ISSUE TITLE
Vertical QSeparator is misplaced in Firefox when inset="true"

### ISSUE THREAD

**Issue by drank** [quasarframework/quasar#5397]
**Describe the bug**
The vertical separator is misplaced in Firefox.

**To Reproduce**
1. Go to https://quasar.dev/vue-components/separator#Example--Vertical in Firefox
2. Check the vertical separators that are set to inset

**Screenshots**
![image](https://user-images.githubusercontent.com/1393766/67573983-3fb15800-f742-11e9-8736-f6da0e61e98b.png)
![image](https://user-images.githubusercontent.com/1393766/67573994-44760c00-f742-11e9-9cfd-5dc21cf7c8b3.png)

**Platform (please complete the following information):**
Firefox 69.0 on Windows 7 64-bit

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in "quasar" v1.2.6.
