### ISSUE TITLE
Comply with CSP when building SSR app with data store

### ISSUE THREAD

**Issue by stefan8888** [quasarframework/quasar#5398]
**Is your feature request related to a problem? Please describe.**
Building SSR app with data store results in final state injection in the form of an embedded script containing the `window.__INITIAL_STATE__` state.  This behavior is not inline with CSP and I would like my app to be compliant with CSP.

**Describe the solution you'd like**
I would like to be able to add a `nonce` to the context variable of the ssr template. This will automatically add a `nonce` attribute to the embedded script in Vue 2.6.0+ ([link](https://ssr.vuejs.org/api/#template)).

**Describe alternatives you've considered**
At the moment I've manually implemented the solution described above (see example app [here](https://github.com/stefan8888/quasar-csp-nonce-example/blob/master/src-ssr/index.js)) by dynamically generating a nonce and binding it to to `res.locals`. The resulting `res.locals.nonce` is then added to the ssr template and Vue automatically takes care of the rest.

This solution works, but might not be the most elegant one. An alternative might be implementing this feature by leveraging the global `__webpack_nonce__` variable in webpack (see [link1](https://github.com/styled-components/styled-components/issues/887) and [link2](https://stackoverflow.com/questions/49639625/how-do-i-integrate-the-value-of-webpack-nonce-with-my-content-security-poli))

**Additional context**
Some more background information:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
- https://github.com/helmetjs/csp

**Comment by rstoenescu** [comment]
Hi,

Create a boot file, define it in quasar.conf.js to run only on server side (`{ path: 'my-boot-file', client: false }`), and take advantage of the [ssrContext parameter](https://quasar.dev/quasar-cli/cli-documentation/boot-files#Anatomy-of-a-boot-file): `ssrContext.nonce = true`.

**Comment by stefan8888** [comment]
Hi @rstoenescu , thank you for the swift response.

Based on your answer, I think I didn't explain the concept of `nonce` correctly. 

It is not a static/boolean attribute that can only be set once. As explained [here](https://stackoverflow.com/questions/42922784/what-s-the-purpose-of-the-html-nonce-attribute-for-script-and-style-elements) for each server request a new unique cryptographic `nonce` is generated (e.g. `nonce=EDNnf03nceIOfn39fn3e9h3sdfa`) on the server.

In order to reach to client, for each server request the `nonce` has to be bound to the server response (for Express.js this means binding to `res.locals`). I don't think this can be achieved using boot files as it has to be included into the ssr template before rendering. 

Therefore, in my current implementation the context of the `renderToString` function looks something like:

```javascript
  const ctx = {
    nonce: res.locals.nonce || null,
    url: req.url,
    req,
    res
  }
```

My proposal was to either extend the (context of) ssr template to order to support this kind of functionality or take advantage of the `__webpack_nonce__` variable (see links above) which I have not tried to implement yet and don't know exactly how it works.
