### ISSUE TITLE
Support to load app via file:// on the phone would be useful.

### ISSUE THREAD

**Issue by gokul-hashlearn** [quasarframework/quasar#540]
Currently, if a quasar app generated index.html + vendor.js is loaded via file:// on the phone,  the cordova detection mentioned here (https://github.com/quasarframework/quasar/issues/485) kicks in and so the app fails to load, since cordova.js is not present.
If local loading of a quasar app via file:// is supported, then packaging a quasar JS app, that can be delivered via a webview, with a native webapp becomes possible. May be a switch to 'quasar build' or an env variable can prevent that cordova.js injection being done in the vendor.js file?

**Comment by rstoenescu** [comment]
Will look on this after v0.14 release. Thanks and sorry the delay!

**Comment by janson** [comment]
To follow up, I've found this same issue on macOS desktop as well (Chrome 58, Safari 10, and Firefox 53). 

Opening up the generated build's index.html via file:// results in cordova detection (#458) and the app fails to load.

**Comment by rstoenescu** [comment]
@janson hi. can you be more specific on what you are doing? what do you mean by "opening up the generated build's index.html"? how are you opening it? what are you referring to by opening? You double click on index.html? Be as specific as you can, including tools etc etc. Thanks.

**Comment by rstoenescu** [comment]
Hi, please reopen with the details needed by my previous comment. Thanks!

**Comment by glacjay** [comment]
@rstoenescu I encounter the same problem when I double click `dist/index.html` file to test. It shall be useful to load this statically on a phone with or without cordova.

**Comment by rstoenescu** [comment]
You even get the warning when building:
```
 Build complete with "mat" theme in "/dist" folder.

 Built files are meant to be served over an HTTP server.
 Opening index.html over file:// won't work.
```

This is normal. "file://" protocol is not the same as "http://" or "https://". Every protocol has its security restrictions and way of working. Serve in a web server, or if you are building a cordova app use Quasar Play or build your app and run it on a mobile.
