### ISSUE TITLE
Button icons on left side are broken in 1.2.6

### ISSUE THREAD

**Issue by Niko2040Belich** [quasarframework/quasar#5408]
**Describe the bug**
Default left icons on buttons draws in right side in 1.2.6.

**Codepen/jsFiddle/Codesandbox (required)**
Bug appers even in default jsfiddle template https://jsfiddle.quasar.dev

**To Reproduce**
Add QBtn with icon property.

**Expected behavior**
Icon draws in left side of button.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/54798556/67622911-e3c0ff00-f827-11e9-8036-f6d10a333e1f.png)

**Platform (please complete the following information):**
OS: Debian Linux Unstable
Node: v10.17.0
NPM: 6.12.0
Yarn: 0.32+git
Browsers: Firefox, Chrome, Firefox Preview on Android, Chrome for Android
iOS: -
Android: -
Electron: -

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this regression.
Will be fixed shortly in v1.2.7.
