### ISSUE TITLE
WYSIWYG toolbar item selection don´t work corectly

### ISSUE THREAD

**Issue by MungardM** [quasarframework/quasar#5417]
**Describe the bug**
The WYSIWYG editor remove prevíous selected items like bold, italic, underlined...
after click on a free space in toolbar.

**Codepen/jsFiddle/Codesandbox (required)**
You can reproduce that issue in the docu: [https://quasar.dev/vue-components/editor#Examples](https://quasar.dev/vue-components/editor#Examples)

**To Reproduce**
1. Go to [https://quasar.dev/vue-components/editor#Examples](https://quasar.dev/vue-components/editor#Examples)
2. choose an editor on the examples site
3. Click on italic
4. Click on bold
5. Click on empty space in toolbar
6. Click on underlined
7. See the error: all previous selected items will deselected

**Expected behavior**
The click on a free space in toolbar should not deselect all selected items

Browser:
Chrome Version 77.0.3865.120

**Comment by rstoenescu** [comment]
#4349 also contains this.
