### ISSUE TITLE
Add a native css atrribute to QItemLabel

### ISSUE THREAD

**Issue by 549393092** [quasarframework/quasar#5423]
Dear,

As you know, we can a red star to the label of QInput because it has a css property q-field__native.
Please see this link. https://github.com/quasarframework/quasar/issues/5129
I am not sure if it can be supported by QItemLabel. If it is possible, could you please give me an example, thanks!

**Comment by pdanpdan** [comment]
Can you please explain with more details what is the request?
What native css attribute? And what does QItemLabel has to do with the red star?

**Comment by 549393092** [comment]
Hi 
Sorry, what I mentioned may confuse you.
I would put it simple, as you know we can add red star to the label of QInput, so is it possible to add red the star to QItemLabel?

**Comment by pdanpdan** [comment]
I still don't understand the problem.

```html
<q-item-label>
  Text <sup class="text-negative">*</sup>
</q-item-label>
```

**Comment by 549393092** [comment]
@pdanpdan It looks cool. Thanks!
