### ISSUE TITLE
[Feature Request] Define custom entries for background services

### ISSUE THREAD

**Issue by Arsync** [quasarframework/quasar#5426]
**Is your feature request related to a problem? Please describe.**
Conceptual.

**Describe the solution you'd like**
Need an option to have independent entry points for background services like oidc-client silent token renewal process (runned within iframe).  It takes package from node_modules for client side and doesn't use Quasar or Vue, but uses its own html file. This entries must not being included into index.html as part of main entry (app) with HtmlWebpackPlugin default option 'chunks: all'. 
https://github.com/quasarframework/quasar/blob/dev/app/lib/webpack/inject.html.js

I think, it's closer to MPA behavior. But additional page builded without Vue.

**Additional context**
Related to [this question](https://github.com/quasarframework/quasar/issues/4999)

**Comment by rstoenescu** [comment]
This sounds like a separate project (not created by Quasar CLI) is needed with a basic custom webpack setup which will generate your extra assets.

**Comment by Arsync** [comment]
Main app authentication is not working without this thing - I've put it to empty VueComponent for 'silent-renew' router path. It will be always loaded within iframe at all pages of the main app for background communications to IdentityServer with redirects, staying on current page.
