### ISSUE TITLE
QTable - ability to apply style and classes via callback

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#5427]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have an option to pass some styles or classes to qtr/tr inside QTable. It would be also useful if this options supports the callback. My suggestion is to name this options *table-row-style* and *table-row-class*. Having this options we can achive striped table style. Example:
```html
<q-table :table-row-class="props => props.row.__index % 2 ? 'white' : 'grey'"></q-table>
```

**Describe alternatives you've considered**
There're at least two options to achive striped table style now.
1) Use css. This approach is pretty simple, but it is incompatible with virtual-scroll property, because in a virtual table the order of rows changes when a slice of data disappears, so stripes move.
2) Markup the whole body. I'm not sure anybody wants to do it.

**Additional context**
Possibly related to #4037

**Comment by 1001v** [comment]
@TobyMosque, thanks for your response. The function is necessary if we want to form classes/styles due to row's specific data, such as index. But if it would accept object, array and string as well, that would be great too. About using the v-for inside the body slot: i see some issues with this approach. What if we want to decorate a single cell in the middle of the table? Normally we would achive this via  body-cell-name slot, but now we have markuped the whole body and need to make conditions inside v-for. That is much less clean code. The second: would the mobile grid view still work when the body is redefined via slot?

**Comment by TobyMosque** [comment]
regarding the callback function, u're right.

I'm undestand your point of view, in that particular case, the `body-cell-name` slot will produce a more clean code, but combine the `body` slot with a `computed` property  is far from be a dirt one.

https://codepen.io/tobias-mesquita/pen/JjjrzMv?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Hi,

This is what QTable's slots are for... full customization on any scenario.
Example: https://codepen.io/rstoenescu/pen/rNNYeRx?&editable=true&editors=101

Notice:
`<q-tr :props="props" :class="myTrClass(props)">`
`<q-td key="calories" :props="props" :class="myTdClass(props.row.calories)">`
and
```js
methods: {
    myTrClass (props) {
      if (props.row.calories === 159) {
        return 'bg-grey-3'
      }
 
      return props.row.__index % 2 === 0
        ? 'bg-yellow-2'
        : ''
    },
    
    myTdClass (calories) {
      return calories % 2 === 0
        ? 'bg-warning'
        : ''
    }
  }
```

**Comment by synner7forever** [comment]
Please can you tell me how I modify the slot so styles only affect a determinated column?
Thanks for your help

**Comment by DetonatorB** [comment]
For posterity: for Quasar 2.x this might be done quite easily with css:

* add  
```
<q-table
...
table-class="zebra"
...
>
```

and 

```
<style scoped>
:deep(div.zebra table tr:nth-child(even))
{background-color: #ff0000;}
</style>
```

please do change the color
