### ISSUE TITLE
Errors in PWA mode: js/fastclick.js.LICENSE and js/vendor.js.LICENSE

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5429]
Hello!

Started to see the following errors after Quasar switched to Workbox v4:

![Screen Shot 2019-10-31 at 2 44 25 PM](https://user-images.githubusercontent.com/3635352/67945718-a88c4a80-fbf0-11e9-9c20-ede8339a2524.png)

![Screen Shot 2019-10-31 at 2 50 42 PM](https://user-images.githubusercontent.com/3635352/67945727-ade99500-fbf0-11e9-81af-7c8a7be297c3.png)

![Screen Shot 2019-10-31 at 2 50 48 PM](https://user-images.githubusercontent.com/3635352/67945728-ae822b80-fbf0-11e9-8e27-8fc073bf6eb3.png)

What are these  js/fastclick.js.LICENSE and js/vendor.js.LICENSE files for?

 PWA config is as follows:
```
      workboxPluginMode: 'GenerateSW',
      workboxOptions: {
        exclude: [/\.html$/]
      },

```

Perhaps related: https://github.com/rishabh3112/gridsome-plugin-pwa/pull/5

Thanks!

**Comment by rstoenescu** [comment]
Hi,

This is due to a recent Terser plugin feature. Disabled the creation of .LICENSE files.
Fixed in "@quasar/app" v1.2.3
