### ISSUE TITLE
Ipad 13.1 considered as mac desktop

### ISSUE THREAD

**Issue by matthieuowlie** [quasarframework/quasar#5430]
**Describe the bug**
When using an Ipad in 13.1 version, the Platform plugin of quasar considered the Ipad as a mac desktop

**To Reproduce**
1. Use Platform from 'quasar'
2. Use Platform.is
3 Platform.is.mac is true
4 Platform.is.desktop is true

**Expected behavior**
Platform.is.mac should be false
Platform.is.desktop should be false
Platform.is.ipad should be true

**Screenshots**
![platform](https://user-images.githubusercontent.com/56551343/67949654-5d6e3980-fbe8-11e9-99af-d789b0d65699.png)

**Platform (please complete the following information):**
Node: v10.16.3
NPM: 6.9.0
Browsers: Safari
iOS: 13.1
Platform: iPad

**Comment by pdanpdan** [comment]
Uncheck the option to always request desktop site in iPad.

**Comment by iperiago** [comment]
While @pdanpdan comment is right, this has some implications though : when you use viewport units in your css (like height: 100vh for instance), it's a well known issue that iOS doesn't treat this correctly. If you rely on Quasar Platform to detect iOS and react accordingly, this will create a bug in this particular case as iOS won't be detected. My solution was to check if both Platform.is.mac and Platform.has.touch are true - it's obviously not perfect though.

**Comment by mrvictorn** [comment]
@pdanpdan 

> Uncheck the option to always request desktop site in iPad.
--
This does not work for iPad PWA. No way to uncheck it.
Also asking users to uncheck something is not best way to treat them,
right @rstoenescu ?
