### ISSUE TITLE
QSelect options intermittently require two clicks on Safari 

### ISSUE THREAD

**Issue by geoidesic** [quasarframework/quasar#5431]
**Describe the bug**
`q-select` doesn't always work on first click on Safari. Seems fine on Chrome. On Safari it intermittently seems to require a second click on the option before it will take. It seems pretty random, can't find a specific trigger but it happens roughly about 50% of the time when clicking on a select option. For example, any of the selects here:  https://quasar.dev/vue-components/select

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/geoidesic/pen/xxxPPBj

**To Reproduce**
1. Go to 'https://codepen.io/geoidesic/pen/xxxPPBj'
2. Click on the select (it's the only element in view)
3. Try click 'One', then option 'Two' 
4. Repeat this ten times and note that sometimes you have to click the option twice before it will take.

**Expected behavior**
Should only require one click to select an option

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: Mac OS X Mojavi 10.14.6 (18G103)
Node: N/A
NPM: N/A
Yarn: N/A
Browsers: Safari Version 13.0.3 (14608.3.10.10.1)
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
N/A

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce...

**Comment by rstoenescu** [comment]
Please help with reproducing. Tried on different setups and could not reproduce.

**Comment by geoidesic** [comment]
Hi, 

It happens to me on my MacBook Pro (15-inch, 2018) Mojave 10.14.6 (18G1012) with the Safari browser Version 13.0.3 (14608.3.10.10.1). Choose any of the QSelects on the Quasar Docs page: https://quasar.dev/vue-components/select#QSelect-API. If I click the select it shows the options. Around half the time when I click on an option it doesn't do anything on the first click; l requires a second click.

On my MacBook Air (Mojave 10.14.6 (18G95) with Safari Version 13.0.3 (14608.3.10.10.1) it works fine.

**Comment by pdanpdan** [comment]
Are you sure it's not the broken finger? In this case the mouse/touchpad?

(
  A patient comes to a MD.
  P: Please, all my body hurts. Look, if I put my finger here it hurts, if I put my finger there it hurts, ...
  MD: Ok, I'll fix your broken finger
)

**Comment by geoidesic** [comment]
If that were the case then I'd expect the same behaviour on all browsers but it's only on Safari.
Still I guess if it's only affecting me... then there's not much we can do.
