### ISSUE TITLE
[docs]Inconsistency with slot props names

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5435]
In documentation of Vue.js, slotProps are named `slotProps`:
```
<template v-slot:default="slotProps">
    {{ slotProps.user.firstName }}
  </template>
```
https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

However, in Quasar's documentation, they sometimes called `prop` and sometimes `props`. I would suggest to change it to `slotProps` anywhere.

### QTree
https://quasar.dev/vue-components/tree#Customize-content
`<template v-slot:default-header="prop">`

### QTable
https://quasar.dev/vue-components/table#Body-slots
`<template v-slot:body="props">`

**Comment by rstoenescu** [comment]
Hi,

The scope variable name can be anything, so it doesn't matter what name it has..
