### ISSUE TITLE
[Request] Webview/IFrame component

### ISSUE THREAD

**Issue by kokizzu** [quasarframework/quasar#544]
Google Login/Account or some other OAuth provider sites requires redirection, it would be nice if Quasar also have a webview (iframe) component, so we can intercept redirection without have to redirect the SPA itself.

or webview/iframe inside form/dialog component would be nice

**Comment by rstoenescu** [comment]
There's nothing stopping you from using an `<iframe>` tag in any place of your app...

**Comment by kokizzu** [comment]
ah yeah, my bad, i didn't notice before that there is [modal](http://quasar-framework.org/components/modal.html) component, i only remember [dialog](http://quasar-framework.org/components/dialog.html) (that cannot contain iframe).
