### ISSUE TITLE
q-tabs not horizontally scrollable until changing window width on desktop

### ISSUE THREAD

**Issue by ceyhunkerti** [quasarframework/quasar#5443]
This is mentioned [here](https://forum.quasar-framework.org/topic/2410/q-tabs-not-horizontally-scrollable-until-changing-window-width-on-desktop)

To solve this issue i re-render component but, re-rendering scrolls the tabs to start.
Is there a way to call **scrollToEnd** after re-rendering ?

**To Reproduce**
add tabs programmatically

**Comment by metalsadman** [comment]
@ceyhunkerti within the forum link you referenced, have you checked my comment in there? because that's the link i provided in my comment does the trick, here it is in action https://codepen.io/metalsadman/pen/wvvjepy?editors=1011.

**Comment by pdanpdan** [comment]
Adding a ref pull to close when done: https://github.com/quasarframework/quasar/pull/3113/files

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.4.1.
