### ISSUE TITLE
QBtn error position icon with to link

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#5448]
**Describe the bug**
When use the `to` prop in a QBtn in a small size the icon is in wrong position.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/codesandbox-app-818eb

**To Reproduce**
1. Create a q-btn
2. Set the size around in a few px (like 20-30)
3. Add a icon
4. Add to prop

**Expected behavior**
Set in the middle of the button, using `to` prop or not.

**Comment by pdanpdan** [comment]
It looks like it needs a `flex-direction: column`

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.0.
