### ISSUE TITLE
Justify prop in table grid

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#5449]
**Is your feature request related to a problem? Please describe.**
I have a table with grid mode, when I have few element they are aligned to the left, leaving blank space in the right, I wanna to center the grid.

**Describe the solution you'd like**
Use a `justify` prop, following the classes uses in flexbox in [quasar](https://quasar.dev/layout/grid/introduction-to-flexbox#Alignment)

**Describe alternatives you've considered**
Apply a custom class with `table-class` prop, but it's didn't apply in grid mode (possible bug?)

**Comment by smolinari** [comment]
Hi,

If you want to do more with grid mode, there is the `item` scoped slot available, which will allow you to do anything you want in grid mode. 

Scott

**Comment by rstoenescu** [comment]
Hi,

New props will be available in "quasar" v1.3.1: `card-container-class` and `card-container-style`.
