### ISSUE TITLE
[Request] Add --fix to lint-on-save by default

### ISSUE THREAD

**Issue by kokizzu** [quasarframework/quasar#545]
I think showing error (failing build) for improper codestyle is not practical

**Comment by rstoenescu** [comment]
1. Having a linter is highly recommended as it makes code more readable and also makes you as a developer avoid certain mistakes.
2. Linting on save has to do with developer's editor of choice, and not with the framework itself.
3. Linting can be disabled if for some reason the developer thinks it gets in the way. But I recommend having a linter in place. Makes you more organized. How to disable it though: http://quasar-framework.org/guide/app-linter-configuration.html

**Comment by smolinari** [comment]
I too, at first, thought linting was a pain. Then I added it to my editor and now I wouldn't want to miss it.

Scott
