### ISSUE TITLE
1.3.0: QInfiniteScroll error / no initial load when initialized with empty array 

### ISSUE THREAD

**Issue by lmfmaier** [quasarframework/quasar#5452]
**Describe the bug**
QInfinite scroll doesn't trigger the initial @load, but throws errors when initialized with an empty array. 

"[Vue warn]: Error in render: 'TypeError: Cannot read property 'concat' of undefined'"
"[Vue warn]: Error in mounted hook: 'TypeError: t.closest is not a function'

This worked pre-1.3.0.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/lmfmaier/pen/qBBpKBz

**Expected behavior**
The component should trigger the initial @load

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.3.1.

**Comment by hellokvn** [comment]
Same here. My QInfiniteScroll is broken since 1.3.0.

**Comment by iJosephY** [comment]
The problem is not fixed yet ..
i tried to new code and there is a new error : 
`[Vue warn]: Error in render: "TypeError: Cannot read property 'push' of undefined"
`

**Comment by pdanpdan** [comment]
@iJosephY please attach a stack trace

**Comment by iJosephY** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/42868470/68365369-c0078e00-0130-11ea-8426-f80b01dd4474.png)

**Comment by pdanpdan** [comment]
Did you compile your own quasar with the patch applied and used it in the project? Because the new release is not published yet.

**Comment by rstoenescu** [comment]
@iJosephY u prolly updated only QInfiniteScrolll.js and missed out on the src/utils/slot.js update. Works just fine...

**Comment by iJosephY** [comment]
i'm so sorry
yeah it's working now 

i was to lazy to compile quasar so i only updated the file ..

thank you <3
