### ISSUE TITLE
QCarousel  not working 

### ISSUE THREAD

**Issue by qiufeihai** [quasarframework/quasar#5453]
**Describe the bug**
QCarousel    Missing required prop: "value"

**Screenshots**
![image](https://user-images.githubusercontent.com/16067334/68082931-c1e5fe80-fe5d-11e9-92a8-52d958d37c7d.png)

**Comment by smolinari** [comment]
A couple of things. 

1. You should talk to us on Discord or the forum, before creating an issue. We'll be able to determine together if there is an issue or your use of the component needs looking at.

2. You need to add some sort of code to the issue or a codepen demonstrating the issue. Until you do, nothing will be considered a bug.

So, please either add a reproducible code or a codepen or go to the forum or Discord channel and discuss the problem with us. 

https://forum.quasar.dev
https://chat.quasar.dev

Closing. You can reopen this should you add code examples/ codepen or we discuss your problem and deem it an issue on Discord or the Forum. 

Thanks. 

Scott
