### ISSUE TITLE
QResizeObserver not capturing height change over iframe

### ISSUE THREAD

**Issue by mechanicalgux** [quasarframework/quasar#5454]
**Describe the bug**
QResizeObserver stops capturing window height when the resize occurs over an iframe.

**Codepen**
https://codepen.io/mechanicalgux/pen/ZEEvZgR

**To Reproduce**
1. Add a QResizeObserver in a QPage
2. Add an iframe in this page
3. Compare QResizeObserver size and actual window object size

**Expected behavior**
QResizeObserver size should be the same as window object size

**Platform**
OS: Win10
Node: 12.3.1
Yarn: 1.17.3
Browsers: Chrome, Firefox

**Comment by pdanpdan** [comment]
QResizeObserver is telling the size of the parent element, not that of the window. And the QPage will be at least as high as the window, but it can be higher if there is enough content.

**Comment by hks2002** [comment]
Does this issue be fixed? 
at the https://codepen.io/mechanicalgux/pen/ZEEvZgR
the iframe's height doesn't equal its parent's height.

**Comment by pdanpdan** [comment]
What issue? Did you read the comment just above yours?

**Comment by hks2002** [comment]
See here
![image](https://user-images.githubusercontent.com/8808496/72240070-edcfee00-361d-11ea-9b01-40a2f6fe40eb.png)
iframe's heigt always be 267, even I resize the window.

**Comment by pdanpdan** [comment]
Did you read the comment just above yours?

**Comment by hks2002** [comment]
Thanks very much.
