### ISSUE TITLE
[Request] 24-hour format on q-inline-datetime component

### ISSUE THREAD

**Issue by kokizzu** [quasarframework/quasar#546]
The Datetime and [Inline Datetime](http://quasar-framework.org/components/inline-datetime.html) component doesn't reflect behavior on phones that uses 24-hour format.

component from clock app on android
![screenshot_20170503-141934](https://cloud.githubusercontent.com/assets/1061610/25651251/3ffdaf02-300c-11e7-9c49-c1e4db737564.png)

12/24-hour format usage across countries
![image](https://cloud.githubusercontent.com/assets/1061610/25651253/4299780e-300c-11e7-88bb-b575c5b36e3a.png)

**Comment by mstaack** [comment]
i think it has been fixed on dev branch
see: https://github.com/quasarframework/quasar/commit/382a86e4e8d46e918a0793d1e991f6e5360583cc

so use bleeding edge or waitn for new release

**Comment by rstoenescu** [comment]
24 hour format will be available (although in a slightly different manner than these screenshots) in v0.14.
