### ISSUE TITLE
Improve QItem inset-level

### ISSUE THREAD

**Issue by gkraser** [quasarframework/quasar#5463]
Const value `56` and `16`:
```js
// QItem.js
...
    style () {
      if (this.insetLevel !== void 0) {
        const dir = this.$q.lang.rtl === true ? 'Right' : 'Left'
        return {
          ['padding' + dir]: (16 + this.insetLevel * 56) + 'px'
        }
      }
    }
...
```
Constants break layout with inset-level for items without icon, while changing `min-width` for `.q-item__section--avatar`,

I understand that such constants are specified in styles, for example:

```sass
// QList.sass
...
    &--avatar
      color: inherit
      min-width: 56px

    &--thumbnail
      img
        width: 100px
        height: 56px
...
```
It would not be a bad thing to put these values in the variables in sass and js.

**Comment by rstoenescu** [comment]
Hi,

This is for consistency within the whole framework. Also follows Material Guidelines.
But regardless, just add your own padding directly on the QItem (through style or class)...
