### ISSUE TITLE
[docs] Add warning to 'Cordova -Preparation' section

### ISSUE THREAD

**Issue by jippy89** [quasarframework/quasar#5464]
Could you guys add a warning to this [section](https://quasar.dev/quasar-cli/developing-cordova-apps/preparation#Windows)?

Because it replaces ALL my path files. I know that I shouldn't be adding random commands which I didn't know. But since I already trusted `quasar` it's kind of just what I do. This will of course also be a lesson to me since I have to add my path files one by one again.

Thank you.

**Comment by rstoenescu** [comment]
Hi,

But the command shouldn't replace your current path, since `setx path ">>>>>%path%<<<;%ANDRO...`

**Comment by jippy89** [comment]
Hm.. weird. 
I thought it was because of that my CLI commands was gone. Since everything was doing fine before I installed things up. Ok, sorry about that. I guess it's not from `quasar`. I thought since my path was exactly the same as what's in the doc, it replaces it or something. It might be because of the Windows update then. Thanks, I will close it now.

**Comment by denovodavid** [comment]
Uhhh... Just ran into this kind of issue.
`setx` has max length of `1024` characters. It didn't delete my path, but it truncated it.
I ran it in `cmd` on Windows 10 while setting up capacitor.
Had to fix my path manually through Windows UI.
