### ISSUE TITLE
Select Input - clear selection

### ISSUE THREAD

**Issue by FlorinBadea** [quasarframework/quasar#5468]
Is it possible to clear the selection when you select all text in the input and click delete/backspace?
Or to trigger the clearable event?

Atm only using the clearable icon works(resets the  model to null)

Case: if I select the entire selection -> delete it -> press tab(or click outisde input) => the selection is added back

https://quasar.dev/vue-components/select#Example--Autocomplete-on-more-than-2-chars

**Comment by smolinari** [comment]
Hi,

https://codepen.io/smolinari/pen/JjjpvVe?editors=1010

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott

**Comment by FlorinBadea** [comment]
> Hi,
> 
> https://codepen.io/smolinari/pen/JjjpvVe?editors=1010
> 
> In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience.
> 
> And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here.
> 
> Thanks. 😄
> 
> Scott

Alright, thanks
Yeah, it looks more like a bug

**Comment by smolinari** [comment]
@FlorinBadea - What looks like a bug?

Scott

**Comment by FlorinBadea** [comment]
> @FlorinBadea - What looks like a bug?
> 
> Scott


[clear-selection.zip](https://github.com/quasarframework/quasar/files/3808402/clear-selection.zip)

A video with the issue (in that case)

**Comment by smolinari** [comment]
Ok. I see what you mean. But, it's up to you to make that happen. It's not a bug. 

https://codepen.io/smolinari/pen/gOOeYjg?editors=1010

Scott

**Comment by FlorinBadea** [comment]
Oh, I see, I didn't think about that.

In my case, I am using this select input as a filter to filter in a list, _options and the list are based on API calls triggered by actions on this select input_ (I thought there is a prop or something to cover that).

Thanks, Scott

Florin
