### ISSUE TITLE
[Request] q-data-table with server side sorting and paging

### ISSUE THREAD

**Issue by kokizzu** [quasarframework/quasar#547]
Current q-data-table implementation requires all rows to be given to the component, what if the data too large (500k+) for the phone or for the server to query/deliver? It would be nice if there's a handler that triggered every `sort`, `goto-page` or `change-page-size` event:

- orderpage (`order`, `page`, `rowsPerPage`, `updateCallback`), where: 
  - `order` is the column order, something like: `["+foo","-bar"]` or  `[{asc:true,key:"foo"},{asc:false,key:"bar"}]` for multicolumn sorting, 
  - `page` is the page requested (`1`..`ceil(data.length/rowsPerPage)`), 
  - `rowsPerPage` is the paging size, 
  - and `updateCallback` is the function that update function, that requires 4 arguments:
    - `rows`, for updating/replacing `data` property
    - `currentPage`, for case when user trying to go to page that not exists
    - `totalRows`, for calculating last page 
    - `rowsPerPage`, for case when user trying to send improper `rowsPerPage`, updating the `options.pagination.rowsPerPage`

**Comment by rogeriomq** [comment]
NICE!

**Comment by Hoagiex** [comment]
This is the most important missing feature for us.

This is a feature, that if not implemented, would force us to move away from quasar as a framework, because it's key in almost every application we make/will make.

**Comment by rogeriomq** [comment]
@Hoagiex... Be quasar patreon and help him grow! Questioning is easy, I want to see ...

**Comment by leo108** [comment]
any update?

**Comment by kruello** [comment]
Hi,

Have you added this feature to v0.14 ?

**Comment by rstoenescu** [comment]
This will go to v0.15. It's getting there. DataTable revamp is 95% done.

**Comment by rstoenescu** [comment]
Closing as code is ready in future v0.15 datatable revamp.

**Comment by luozhihua** [comment]
@rstoenescu  What the time to publish v0.15? It seems v0.15 has a lot of nice features that I can’t wait for it!

**Comment by rstoenescu** [comment]
Hi @luozhihua , Doing my best to release it this month.

**Comment by luozhihua** [comment]
👍 Really looking forward to
