### ISSUE TITLE
Feature: Popup component as a Quasar Plugin (like Dialog)

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#5474]
**Is your feature request related to a problem? Please describe.**
I am using a calendar-like component. It is not written in Vue and has limited options for extending its functionality. It uses a container where each calendar 'event' is positioned absolutely with top/left properties and it is possible to swipe the view in any direction to reveal more events. For each calendar event, when selected (clicked), I'd like to be able to show a popup, e.g. QMenu or QPopupProxy. The click is handled internally by the calendar component - not a native click. The popup will contain a menu with specific operations for the given event and will be intricately animated.

Another possible problem is the fact that QMenu/QPopupProxy requires a CSS selector for its target, but the calendar events do not have their own HTML ids set. It would be great if you could pass an HTML element as the target. This isn't as important though as there is a workaround by setting the HTML id property dynamically.

Also, because the view can be swiped, the calendar events' coordinates can change, but any visible popups will remain in place. It would be great if there was an option to follow the target and move with it, triggering the positioning engine if needed. If this is not feasible, then another possible solution would be an option to close the popup on a mousedown event instead of on a mouseup event. Not ideal, but still better.

**Describe the solution you'd like**
- Dynamically create QMenu/QPopupProxy (or similar component) via quasar plugin, just like QDialog.
- (Optional) Set the target with either a CSS selector OR an HTML element directly.
- (Optional) Option to automatically reposition the popup as the target element's absolute coordinates change.

**Describe alternatives you've considered**
Using a dialog (plugin) for now, but possibly implementing my own solution.

**Additional context**
I am open to suggestions on how to achieve this with the current tools at hand.

**Comment by lucasfernog** [comment]
Did you take a look at quasar's calendar component? https://github.com/quasarframework/quasar-ui-qcalendar

Also, I think you can have a QMenu on the page and use the offset prop to show it where your calendar was clicked.

**Comment by MartinManev** [comment]
> Did you take a look at quasar's calendar component? https://github.com/quasarframework/quasar-ui-qcalendar

I did take a look at it. I'm trying to do is something similar to a calendar, but not quite. So QCalendar is not suitable. The current choice for the 'calendar' is set in stone.

> Also, I think you can have a QMenu on the page and use the offset prop to show it where your calendar was clicked.

I have experimented with a single pre-existing QMenu, but the approach is very cumbersome. One of the problems for example was with the animations - in order to trigger the animations I need to destroy and recreate the QMenu. There is also a problem with the state - I need each QMenu to have its own state and not be shared. There are just too many issues to find workarounds for.

**Comment by mesqueeb** [comment]
I need exactly the same thing as @MartinManev 
+1 😉

**Comment by rstoenescu** [comment]
The request is interesting. Will give it a thought soon.

**Comment by mesqueeb** [comment]
@rstoenescu thank you so much!! I can't wait 😍 😍 😍 😍 
tell me if you need some help.

**Comment by mesqueeb** [comment]
@rstoenescu I need the QMenu as plugin in the next 2 weeks, so I will start building it.

Do you want me to look at the QDialog plugin code and try to replicate that code for QMenu in a PR for Quasar?

**Comment by hawkeye64** [comment]
I think this would be a great plugin for Quasar, myself. :+1:

**Comment by rstoenescu** [comment]
Given it some thought. One can create a component and use it as content for QMenu. Creating a similar QDialog <-> Dialog functionality would require tremendous effort and honestly I don't think it's worth it given the current workload. Would love to see some app extension / package for Quasar on this though.

**Comment by hawkeye64** [comment]
Totally agree! A wrapper would be just as good and makes sense to be in an app-extension.
