### ISSUE TITLE
Qinput event bug

### ISSUE THREAD

**Issue by huanling7731** [quasarframework/quasar#5479]
**Describe the bug**
Blur/focus event of Input component cannot be triggered in MAC firefox version 50.1

**Codepen/jsFiddle/Codesandbox (required)**
Examples of component source code can be reproduced
![image](https://user-images.githubusercontent.com/23035180/68272484-ce0cce80-009e-11ea-81c3-de2c9ae83c57.png)

**Platform (please complete the following information):**
OS:mac
Browsers: firefox version 50.1

**Additional context**
Add following code  to function __onFinishEditing is one of solution.
`this.$emit('blur')`

**Comment by pdanpdan** [comment]
Sorry. We cannot reproduce it.
If you can provide a codepen showing the problem or a better description please reopen.

Thank you.
