### ISSUE TITLE
QTr no events propagate

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#5481]
**Describe the bug**
QTr events not working.

**To Reproduce**
Place event like <q-tr @click="myMethod"></q-tr> and try to click on the table row - nothing happens.

I look into source code of the QTr and found at line 19:
`: { ...on, class: this.props.__trClass },` - if we change to `: { on, class: this.props.__trClass },` events start to work properly.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available shortly in "quasar" v1.4.0.

**Comment by emprove** [comment]
Thanks, you are awesome.
