### ISSUE TITLE
QImg very occasionally has a height of 0px

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#5487]
**Describe the bug**
I have a QImg in my project that, about 1 in 10 times it will have a height of 0px. Looking at the HTML, the only thing that differs in this 1 in 10 occurance is the div: 
`<div style="padding-bottom: 60%;"></div>` is instead `<div></div>`.

**Codepen**
https://codepen.io/Fanvadar/pen/jOOxVeG

This issue occurs in the Codepen much more frequently than in my project. 

**To Reproduce**
1. Go to the Codepen (https://codepen.io/Fanvadar/pen/jOOxVeG)
2. If the image has a height of 0px, rerender the display section by removing a character from the HTML code then replace it. This should make the QImg have a height > 0px. 
3. Otherwise refresh page. 
4. Once the QImg is rendering, if you open the Codepen a second time in another tab it will render immidiately. 

**Expected behavior**
I expected the QImg to render with a height > 0px every time. 

**Screenshots**
![bug capture](https://user-images.githubusercontent.com/11305093/68355042-bfcfb880-0159-11ea-83bd-67a2f6964d80.PNG)
![bug capture normal](https://user-images.githubusercontent.com/11305093/68355026-b8a8aa80-0159-11ea-975f-67368939bab4.PNG)

**Platform (please complete the following information):**
OS: Windows
Node: v10.16.3
NPM: 6.9.0
Yarn: N/A
Browsers: Chrome
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
This may not be a Quasar problem as I am fairly inexperienced, apologies if this is the case.

**Comment by metalsadman** [comment]
@Fanvadar tried in chrome and ff, didn't get the behavior you mentioned.

**Comment by Fanvadar** [comment]
@metalsadman seems like you're right, can't even reproduce it myself now. Must be specific to my project.
