### ISSUE TITLE
QDrawer : Overlay stay activated

### ISSUE THREAD

**Issue by joevinH** [quasarframework/quasar#5492]
Hello, 

The QDrawer overlay stay activated when i switch from normal to landscape view and then to normal view again view with q-drawer open.

To Reproduce
1. Go to [Layout builder](https://quasar.dev/layout-builder) and add only a left drawer and a Qheader in pick layout part.
2. Then in configure layout parts activate overlay mode.
3. Open browser dev console -> mobile toolbar -> ipad (on chrome)
4. Open the left drawer
5. Rotate to landscape with drawer open
6. Rotate again to normal view
7. The overlay stay activated while the drawer disapear

**Expected behavior**
The overlay should disapear or the drawer should be open.

**Screenshots**
![image](https://user-images.githubusercontent.com/52457156/68379094-885b0f00-014d-11ea-9ed0-3499ebb778c4.png)

**Comment by rstoenescu** [comment]
Hi,

@joevinH Are you sure that you've refreshed browser window after selecting "ipad" from the dev tools top menu? The Platform detection is not "reactive".

Anyone else, can you reproduce the above?

**Comment by joevinH** [comment]
@rstoenescu yes i refreshed my browser on the layout builder page after selecting the ipad display. 
But you have to activate the overlay mode (wich desactivate itself after the browser refresh) and then the bug appears

**Comment by joevinH** [comment]
Here is a [video]( https://www.loom.com/share/092cf4007aa34f6896aaf5cd35be7f92)

**Comment by rstoenescu** [comment]
Confirmed. Thank you for the video!
Will fix it asap.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "quasar" v1.4.1
