### ISSUE TITLE
QMarkupTable changed `dark` color since dark mode release

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#5493]
I upgraded quasar from "1.2.4" to "1.3.0" and dark tables changed colors.

QMarkupTable with prop `dark` set used to be colored with `#424242`:
![image](https://user-images.githubusercontent.com/25121817/68379916-1e436980-014f-11ea-9c83-0297ba0aef80.png)

In last release with dark mode, the color changed to `#1d1d1d`.
![image](https://user-images.githubusercontent.com/25121817/68379980-3f0bbf00-014f-11ea-9ea0-91227e3dca98.png)

It seems to be caused by `q-dark` class having duplicated background, one set via variable and one set directly.
![image](https://user-images.githubusercontent.com/25121817/68380048-65315f00-014f-11ea-8bfc-8b6030f54f04.png)

Not a big deal but kind of breaking change. Not sure if this is intentional

**Comment by rstoenescu** [comment]
This is intentional for consistency.

**Comment by panstromek** [comment]
Ok. I also noticed all my dialogs changed colors.

For anyone wondering, one quick way to fix this is to change the $dark variable in css/quasar.variables.styl:

```styl
$dark = #424242
```
