### ISSUE TITLE
node-wifi connect issue

### ISSUE THREAD

**Issue by GhyslainBruno** [quasarframework/quasar#5495]
**Describe the bug**
- 

*Hi to alI, firstly I would like to say that I am a beginner in term of quasar use. Then, I know it looks like a* *library issue (node-wifi) but I'm not really sure about this.*

I try to connect to a wifi network inside an electron app, using [node-wifi](https://github.com/friedrith/node-wifi) npm library. Pretty straight forward, but it doesn't work at all. 

Here is the code I run : 
```
import wifi from 'node-wifi';

wifi.init({
  iface: null
});

...

// In a "connect" function : 
await wifi.connect({ ssid: ssid, password: password});
```

This is the error I get : 
```
Error: spawn networksetup ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246)
    at onErrorNT (internal/child_process.js:429)
    at processTicksAndRejections (internal/process/task_queues.js:81)
```

As I understand, this means that "networksetup" has not been found by the system (I am on a MAC - and using TypeScript). Why not. 
But the thing is: 
- If I try to run the same code inside an electron app (**not** made using quasar) --> it works ! 
- If I try to run the same code inside a NodeJS app --> it works ! 
- If I use this library using their CLI --> I works ! 

- If I run this code inside an electron app **made** by quasar (with or without using TypeScript) --> It Fails ! 

BUT : 

- If I run the code from the node-wifi library directly inside my electron app (**made** by quasar) instead -->  it works ! : 
```
import { execFile } from 'child_process';

... 

// In a "connect" function : 
const args = [];
      args.push('-setairportnetwork');
      args.push('en0');
      args.push('wifi_ssid');
      args.push('wifi_password');

      execFile('networksetup', args , function(err, resp) {
        console.log(err);
        console.log(resp);
      });
```

*Codepen/jsFiddle/Codesandbox (required)*
*I don't know how I could use a Codepen or jsFiddle or even CodeSandbox for such a thing, as the thing* 
*I am trying to achieve is to use wifi of the machine I am working on... *

# Steps to reproduce : 
- ```quasar create wifi_electron_test```
- ...Press ENTER until the end...
- ```cd wifi_electron_test```
- ```npm i node-wifi```
- ADD this code in router/index.js file (juste before ```Vue.use(VueRouter)``` : 
```
import wifi from 'node-wifi'

// Initialize wifi module
// Absolutely necessary even to set interface to null
wifi.init({
  iface: null // network interface, choose a random wifi interface if set to null
})

// Connect to a network
wifi.connect({ ssid: 'SSID_OF_YOUR_CHOICE', password: 'PASSWORD_OF_YOUR_CHOICE' }, function (err) {
  if (err) {
    console.log(err)
  }
  console.log('Connected')
})
```
- save + exit file
- run ```quasar dev -m electron``` and watch the console of chrome dev tools, you should see the error : 
```
Error: spawn networksetup ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246)
    at onErrorNT (internal/child_process.js:429)
    at processTicksAndRejections (internal/process/task_queues.js:81)
```

**Expected behavior**
This error should not happen, and the computer used should be connected to the desired wifi. 

**Platform (please complete the following information):**
OS: Mac OS Catalina
Node v12.0.0
Yarn: 1.19.1
Chromium v73.0.3683.121
Electron v5.0.11
v8 v7.3.492.27-electron.0

**Additional context**
Pretty much here.
I would just add that quasar is amazing, and that'd be bad a shame if my co-workers and I won't be able to use this framework for our app project :-/. 

I hope you guys can help me in any way, because it's been several days working on this issue, and I don't really know how to be able to connect to a wifi access point with an electron app made by quasar as far as I understand :-/. 

Anyway, thanks a lot for your time and help :-).

**Comment by GhyslainBruno** [comment]
**ADDITIONNAL info :** 

I tried a few more things to investigate this strange behaviour, and it appears that if I provide the full path of the "networksetup" utility (directly inside the code of the library), it actually works as expected ! 

So, instead of : 
```
execFile('networksetup', args, { env }, function(err, resp) { ...
```

I changed for : 
```
execFile('/usr/sbin/networksetup', args, { env }, function(err, resp) { ...
```

So it looks more and more a node-wifi library issue, but I still can't understand why it doesn't work **ONLY** when the electron app is made using quasar. 

I suspect that it has a relationship with the **warning** on this [quasar docs page](https://quasar.dev/quasar-cli/quasar-conf-js) : 

> /quasar.conf.js is run by the Quasar CLI build system, so this code runs under Node directly, not in the context of your app. This means you can require modules like ‘fs’, ‘path’, ‘webpack’ and so on. Make sure the ES6 features that you want to write this file with are supported by the installed version of your Node (which should be >= 8.9.0).

**Comment by pdanpdan** [comment]
Try something along this line: https://github.com/electron/electron-packager/issues/603
Sorry, but it's not related directly to Quasar.
