### ISSUE TITLE
Quasar Cli - quasar create doesn't work

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#5496]
**Describe the bug**
After updating the quasar cli to v1.0.1, if I try to create a new project, it download the starter kit and then nothing. I also tried to reinstall.

**To Reproduce**

1. quasar create <folder_name>
2. See error

**Platform (please complete the following information):**
OS: Windows_NT(10.0.18362) - win32/x64
Node: 10.16.3
NPM: 6.12.0
Yarn: 1.17.3

**Comment by rstoenescu** [comment]
Hi,

What error are you experiencing?

**Comment by rstoenescu** [comment]
Found it. It was due to a bug in an updated package ("ora").
Reference: https://github.com/sindresorhus/ora/issues/136

Released "@quasar/cli" v1.0.2 by downgrading this package.

**Comment by heartbeatLV** [comment]
Hi, thanks for the quick fix!
and sorry for my english

**Comment by rstoenescu** [comment]
Thanks for reporting!
