### ISSUE TITLE
Quasar fails to copy cordova android build to dist if using Android App Bundle (.aab) format

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5499]
**Describe the bug**
`quasar build` fails for Android App Bundle (.aab format). It appears to be looking for the apk folder to copy to dist, but the apk folder won't exist:

```
BUILD SUCCESSFUL in 55s
44 actionable tasks: 42 executed, 2 up-to-date
Built the following bundle(s): 
        D:\myapp\src-cordova\platforms\android\app\build\outputs\bundle\release\app.aab
```
```
(node:24420) UnhandledPromiseRejectionWarning:   Error: ENOENT: no such file or directory, stat 'D:\myapp\src-cordova\platforms\android\app\build\outputs\apk\release'
```
**Codepen/jsFiddle/Codesandbox (required)**
N/A it's cordova-specific

**To Reproduce**
1. quasar build -m android -- -- --packageType=bundle
2. See error

**Expected behavior**
.aab should be supported since it's Google's recommended format for distribution on Google Play. .aab is supported in cordova-android as of 8.1.0.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows_NT(10.0.18362) - win32/x64
Node: 10.15.3
NPM: 6.9.0
Yarn: 1.19.1
cordova: 9.0.0 (cordova-lib@9.0.1)
cordova-android: 8.1.0

**Additional context**
Maybe copy from both `\build\outputs\apk\release` and `\build\outputs\bundle\release` and don't fail on a missing folder or add support for specifying the bundle format directly to `quasar build` so that quasar is aware of which format is being used and decide path based on that?

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!

It's just the final step that issues the build error, which tries to copy a folder which does not exist when building with `--packageType=bundle` parameter.

Fixed both cordova and capacitor on this issue.

Fix will be available in "@quasar/app" v1.2.4.
