### ISSUE TITLE
QSelect - keep users's input on focusout event

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#5503]
**Is your feature request related to a problem? Please describe.**
I use q-select as simple search input with dropdown options as visual showing query results also with availability to click on option, but users's input clear after blur/focusout.

**Describe the solution you'd like**
Keep users's input on focusout event.

**Describe alternatives you've considered**
Maybe... autoselect first available option. But it's not intuitive and what to do if no options.

**Comment by pdanpdan** [comment]
If you use `use-input` and add the `@filter` listener you'll get a call each time the typed value is changed.
Just store this value and do what you want (set the model) when the QSelect is blurred.
