### ISSUE TITLE
QInfScroll preserving space for no reason

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5504]
Hello!

Not sure why this was changed so that q-inf-scroll always takes some space even if not loading / empty.

https://codepen.io/jean-moldovan/pen/xxxzZKZ?&editable=true&editors=101
![Screen Shot 2019-11-08 at 12 24 56 PM](https://user-images.githubusercontent.com/3635352/68465075-cf670400-0222-11ea-9c29-bc9fef6cee73.png)

![Screen Shot 2019-11-08 at 12 28 21 PM](https://user-images.githubusercontent.com/3635352/68465305-469c9800-0223-11ea-8955-9e6c70f431a9.png)

In my opinion, inf scroll component should not take extra space when empty / not loading. This can cause an unwanted vertical scroll (especially on mobile).

**Comment by pdanpdan** [comment]
I made a PR to hide the loading indicator when the component is disabled.
If you want to hide it when the component is enabled then add this to you CSSs:

```stylus
.q-infinite-scroll__loading.invisible
  display none
```

**Comment by jean-moldovan** [comment]
Thanks, could you please elaborate on why it is important to preserve loading space for inf-scroll component when loading indicator is not shown?

**Comment by pdanpdan** [comment]
To prevent changing scroll position when it is shown/hidden.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.1.
