### ISSUE TITLE
Intersection not properly working with infinite scroll

### ISSUE THREAD

**Issue by lmfmaier** [quasarframework/quasar#5506]
**Describe the bug**
As per documentation, the v-intersection directive should fire an event when an the respective element is scrolled into view. I use the feature to implement lazy loading on images within a infinite scroll container but noticed that the intersection event is fired for ALL child elements of the scroll container as soon as they are loaded/appended, regardless of their visibility (whicht loads all the images in a not so lazy way). When scrolled into view, the intersection event is fired again even when using the "once" modifier.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/lmfmaier/pen/YzzvqVB

**To Reproduce**
When the intersection event is triggered it logs the ID of its element to the console, you can clearly see that all children have their intersection event fired upon @load, regardless of their scroll position/visibility. When scrolling down the event is triggered again. When the scroll container loads new content upon reaching the offset, all new children immediately fire their intersection event

**Expected behavior**
Intersection event should fire when element scroll into view

**Comment by pdanpdan** [comment]
Intersection observer emits when the state changes, and always emits when it starts observing a target.
You have to check the `isIntersecting` property of the entry to see if the element is visible or not.

See here:https://codepen.io/pdanpdan/pen/wvvXWyP

**Comment by lmfmaier** [comment]
My bad, didn't notice that. Thanks, it's working now when checking for isIntersecting
