### ISSUE TITLE
q-drawer-link not getting active class on child routes.

### ISSUE THREAD

**Issue by Zolotov88** [quasarframework/quasar#551]
I have [same](https://github.com/quasarframework/quasar/issues/230) problem right now. All `<q-drawer-link>` gets active class only at exact route. `<router-link>` works normal. Construction with `<router-link>` chnges page but it go back when I closing drawer on mobile.
This gets active class at '/users/new':

```
<router-link to="/users" tag="div" class="item item-link drawer-closer">
  <div class="item-content">
    Пользователи
  </div>
</router-link>
```
but this:
```
<q-drawer-link to="/users">
  Пользователи
</q-drawer-link>
```
or this:
```
<q-drawer-link :to="{path: '/users', exact: false}">
  Пользователи
</q-drawer-link>
```
don't.
Am I doing something wrong?

**Comment by rstoenescu** [comment]
Hi, I would gladly investigate this for v0.13, but the lack of time and v0.14 release date is pressuring me. v0.14 has flawless implementation in all components using routes though. Working hard to release v0.14. Thank you!

**Comment by Zolotov88** [comment]
=(

**Comment by rstoenescu** [comment]
@Zolotov88 use your first version:
```html
<router-link to="/users" tag="div" class="item item-link drawer-closer">
  <div class="item-content">
    Пользователи
  </div>
</router-link>
```
It's perfectly equivalent to what drawer-link should do.

Please help Quasar by supporting it so I can spend even more time developing it. https://www.patreon.com/quasarframework Every cent counts!

**Comment by christosf** [comment]
The equivalent to what drawer-link does, does not work on devices that the drawer is not visible and opens like sidebar

**Comment by rstoenescu** [comment]
This has been reworked in v0.14, so it's no longer relevant. All components using routes will work the same way router-link does.

**Comment by christosf** [comment]
when is v0.14 coming out?

**Comment by rstoenescu** [comment]
@christosf Hi, you can read all about it here: http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list
