### ISSUE TITLE
QInfScroll - multiple loading nodes in the DOM

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5512]
Hello!

Unfortunately I was unable to create a proper codepen for this one.
What I see is that sometimes there are multiple loading nodes in the tree for q-inf-scroll.

![Screen Shot 2019-11-08 at 4 01 44 PM](https://user-images.githubusercontent.com/3635352/68479213-ddc51800-0242-11ea-93b7-2e68c186ca00.png)
![Screen Shot 2019-11-08 at 4 01 53 PM](https://user-images.githubusercontent.com/3635352/68479214-de5dae80-0242-11ea-8c03-4aafbda1b393.png)

I'm using a simple wrapper around q-infinite-scroll component:
```
<template>
  <div>
    <slot name="empty" />

    <q-infinite-scroll
      ref="infiniteScroll"
      :offset="300"
      @load="load"
    >
      <div>
        <slot />
      </div>

      <template v-slot:loading>
        loading...
      </template>
    </q-infinite-scroll>
  </div>
</template>

<script>
  export default {
    methods: {
      load (i, done) {
        this.$emit('load', { i, done })
      },
      reset () {
        this.$refs.infiniteScroll.reset()
      },
      stop () {
        this.$refs.infiniteScroll.stop()
      },
      poll () {
        this.$refs.infiniteScroll.poll()
      },
      resume () {
        this.$refs.infiniteScroll.resume()
      }
    }
  }
</script>

<style scoped>

</style>
```

Thanks!

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fixed through https://github.com/quasarframework/quasar/commit/a02202f9f791596b63cd79fbf339742d78c022d8
