### ISSUE TITLE
Error in QSelect component during asynchronous filtering

### ISSUE THREAD

**Issue by haasz** [quasarframework/quasar#5513]
**Description**

The `QSelect` component with an input field during asynchronous filtering, if you type slowly (that is, if there are multiple requests/answers), clicking on the dialog list throws an error and freezes.

The error only occurs when you click the list item in the dialog box if you retrieve the result list asynchronously at least twice. Otherwise, there is no error (eg, there is only one request/response or the response is not delayed).

**Fix**

The error occurs in the `QSelect.js` file at this line:

https://github.com/quasarframework/quasar/blob/f9898c88a80df257106478dc49454c88e16b2c5f/ui/src/components/select/QSelect.js#L343

The following change fixes this error:

```js
        this.$refs.target !== void 0 && this.$refs.target.focus()
```

You might want to do the same for this line:

https://github.com/quasarframework/quasar/blob/f9898c88a80df257106478dc49454c88e16b2c5f/ui/src/components/select/QSelect.js#L1097

**Platform:**

Quasar: v1.3.0, v1.4.0

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "quasar" v1.4.1
