### ISSUE TITLE
QTable with hide-header and virtual-scroll doesnt works

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#5514]
**Describe the bug**
The QTable doesnt works when hide-header is used alogn with virtual-scroll

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/eduardodgarciac/pen/NWWzjNP

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fixed through https://github.com/quasarframework/quasar/commit/a02202f9f791596b63cd79fbf339742d78c022d8
