### ISSUE TITLE
QSlideItem css override the QItem background color on Dark mode

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#5515]
**Describe the bug**
QSlideItem css override the QItem background color on Dark mode

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/heartbeatlv-the-bashful/pen/ZEERKja](https://codepen.io/heartbeatlv-the-bashful/pen/ZEERKja)

**Expected behavior**
QItem keeps the original background color

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.4.1
