### ISSUE TITLE
[docs] Quasar.dev appears to be down

### ISSUE THREAD

**Issue by holtalanm** [quasarframework/quasar#5518]
was unable to ping it, or run a tracert (just getting request timed out).  Browser is unresponsive when navigating to quasar.dev.

checked on [isitdownrightnow](https://www.isitdownrightnow.com/quasar.dev.html) and it looks like it is down for everyone, not just me.

**Comment by lucasfernog** [comment]
Hi holtalanm,

The documentation website is down due to our hosting.

Please follow our Discord server for the annoucement when it gets fixed.

**Comment by holtalanm** [comment]
okay, thanks!

**Comment by rstoenescu** [comment]
Waiting on propagating the new DNS settings. https://quasar.dev/ should be up in a few hours max. Sorry for any inconveniences.

Temporary address: https://quasardev-ijurxbbaxj.now.sh

**Comment by tohagan** [comment]
If your files are all static, you might consider Firebase hosting to all but remove this risk.
- For **99.999%** uptime you can elect to host as replicated to 3 or 5 data centres. Select this "data center" option when you create the project.
- Deployment is trivial => `firebase deploy --only hosting` - which only uploads changed files.
- Configure hosting to retain multiple deployment versions so you can rollback.
- All the other Firebase stuff!

**Comment by tohagan** [comment]
If your files are all static, you might consider Firebase hosting to all but remove this risk.
- Global CDN 
- 99.999% uptime for databases and storage
- Deployment is trivial => `firebase deploy --only hosting` - which only uploads changed files.
- Configure hosting to retain multiple deployment versions so you can rollback.
- All the other Firebase stuff!

**Comment by rstoenescu** [comment]
The docs are running on Quasar SSR, so not static I'm afraid..

**Comment by suneetjain** [comment]
quasar.dev is down again from last 1 hour

**Comment by rstoenescu** [comment]
Our website is temporarily down. We apologize in the name of our hosting provider. They are working towards fixing the problems.

**Comment by rstoenescu** [comment]
Website is up again.
