### ISSUE TITLE
q-tabs infinite loop on align property

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#5522]
same as https://github.com/quasarframework/quasar/issues/5145 , and https://github.com/quasarframework/quasar/issues/4710

![q-tabs-issue](https://user-images.githubusercontent.com/48388358/68524160-73f54e80-02d4-11ea-8457-a40865c9ded0.gif)

can be solved in a similar way to https://github.com/quasarframework/quasar/pull/5466 , but we should find the root cause with q-tabs or else, instead of solving the side effects

can be reproduced here: https://www.browserling.com/browse/win/7/firefox/68/https%3A%2F%2Fquasar.dev%2Fstyle%2Ftheme-builder

**Comment by pdanpdan** [comment]
Hi. can you please tell me the width of the document where this can be reproduced?

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.2.
