### ISSUE TITLE
q-footer

### ISSUE THREAD

**Issue by ArkIv** [quasarframework/quasar#5525]
![qfooter](https://user-images.githubusercontent.com/8625530/68528344-740c4300-0302-11ea-979a-6d36434c6335.jpg)

Build mode........ spa
 Pkg quasar........ v1.4.0
 Pkg @quasar/app... v1.2.3
 Debugging......... no
 Publishing........ no

Why so it turns out?

Clean installation, template from Layout Builder
my actions:
npm install -g @quasar/cli
quasar create xxx
cd xxx
npm install
...
quasar build

**Comment by pdanpdan** [comment]
Because you have not added QFooter component to quasar.conf or set all to auto

**Comment by ArkIv** [comment]
thanks!
