### ISSUE TITLE
Unexpected console statement  no-console

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#5529]
**Describe the bug**
Eslint `no console` errors when running `quasar build`

**To Reproduce**
1. `quasar create myapp` (with default options)
2. `cd myapp`
3. `quasar build -m pwa`
```sh
ERROR in ./src-pwa/register-service-worker.js
Module Error (from ./node_modules/eslint-loader/index.js):

/path/to/myapp/src-pwa/register-service-worker.js
  16:7  error  Unexpected console statement  no-console
  22:7  error  Unexpected console statement  no-console
  28:7  error  Unexpected console statement  no-console
  34:7  error  Unexpected console statement  no-console
  40:7  error  Unexpected console statement  no-console
  46:7  error  Unexpected console statement  no-console
  52:7  error  Unexpected console statement  no-console

✖ 7 problems (7 errors, 0 warnings)

 @ ./.quasar/client-entry.js 22:0-48
 @ multi ./.quasar/client-entry.js


 app:build [FAIL] Build failed with errors. Check log above. +0ms
```

This is because in `.eslintrc.js` we have:
```js
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
```
Console calls should not be disabled in `node` (https://eslint.org/docs/rules/no-console#when-not-to-use-it)

Instead, if the objective was: not to have `console` calls in the compiled production code, the way to go is configure Terser plugin to drop all console calls:
https://github.com/terser/terser#compress-options

`quasar.conf.js`:
```js
module.exports = function (ctx) {
  return {
  ...
    build: {
    ...
      uglifyOptions: {
        compress: { drop_console: true }
      }
    },
  }
}
```

(same bug reported here: https://github.com/quasarframework/quasar/issues/5095#issuecomment-533181140)

@rstoenescu

**Comment by rstoenescu** [comment]
Hi,

Yes. The uglifyOptions would be a nicer thing to do. Unfortunately, it doesn't works as expected :)
But merged your PR on the starter kit.
