### ISSUE TITLE
tips: Render q-tooltip when overflowhiden 

### ISSUE THREAD

**Issue by rogeriomq** [quasarframework/quasar#553]
Render q-tooltip when template span (slot = cell), css overflow hidden attribute equals true!
Otherwise I would not need to display a q-tooltip.
 sample:
`...
<template slot="col-nome" scope="cell">
          <span>
            {{cell.data}}
            <q-tooltip>{{cell.data}}</q-tooltip>
          </span>
        </template>
...`
In the case above the q-tooltip only be used if the overflow happened.
xD

**Comment by rstoenescu** [comment]
Please use the github template in place. If this is a tip for others, use forum "Show and Tell" section. Thank you.
