### ISSUE TITLE
Electron mode build with non default bundler

### ISSUE THREAD

**Issue by Lukino2000** [quasarframework/quasar#5530]
in https://github.com/quasarframework/quasar/blob/051302a2ed1dd7fceb515458210f3697f6ceb334/app/lib/helpers/ensure-argv.js#L66

you assume that if no bundler command line is specified you should use 'packager', but in quasar.conf.js you permit to change the default bundler.

I think that if no bundler is specified in command line you should first check config file, or alternatively remove the possibility of specify it

in my case i changed the bundler in config to 'builder' and when i try to build using

`quasar build -m electron -T win -A x64`

it tells me

`app:ensure-argv ⚠️  Unknown target "win" for electron-packager`

but for bundler 'builder' target 'win' is OK

if I use

`quasar build -m electron -b builder -T win -A x64`

it works correctly, but i think it's strange set default in config and use -b switch

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available shortly in "@quasar/app" v1.4.4.
