### ISSUE TITLE
Support for Electron >4 on Linux

### ISSUE THREAD

**Issue by mYnDstrEAm** [quasarframework/quasar#5531]
I'm trying to get the latest version of Electron to work with the Quasar Framework under GNU/Linux with npm because I'd like to use the latest electron features, partly because that might be needed to support [the upcoming Librem 5 GNU/Linux device](https://forum.quasar-framework.org/topic/4614/will-the-quasar-framework-support-the-librem-5-new-gnu-linux-smartphone-with-pureos-and-gnome-or-plasma-mobile).

The problem seems to be related to: https://github.com/quasarframework/quasar/issues/5172 - it seems to be the same issue except that I also can't get the v5 build to work with electron-packager and that it doesn't work after deleting the node_modules folder and updating/reinstalling the electron dependency.

With v5 I can test the app with `quasar dev -m electron` but I can't run the app built with `quasar build -m electron` and an unchanged quasar.conf.js: I'm getting the message `Trace/breakpoint trap` shown in the console. That's the same error message I'm getting with electron-packager@13 and electron@7 and any combination of these. Earlier version of electron-packager don't work either.

It only worked with electron@5, electron@6 and electron@7.1.1 after setting [bundler to 'builder' in quasar.conf.js](https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron#Packager-vs.-Builder).

In all cases of electron >4 I needed to first run `sudo chown root` and `sudo chmod 4755` on the chrome-sandbox. The error message prompts the user to make these changes: 

> FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that [...]/dist/electron/Packaged/linux-unpacked/chrome-sandbox is owned by root and has mode 4755.

----

So the solution to this is either getting electron-packager to work with GNU/Linux or to change the documentation and/or default-configuration of the electron bundler setting.

**Comment by rstoenescu** [comment]
It should work with latest "@quasar/app"
