### ISSUE TITLE
QColor inside QPopupProxy+QDialog closes on drag

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5532]
**Describe the bug**
QColor used inside a QPopupProxy which is inside a QDialog closes when you drag the color picker pointer. Note: A single click does not close it. 
**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/edeltraud/atv6r594/11/

**To Reproduce**
1. Open Dialog in fiddle and try to use QColor
2. It closes on drag

**Expected behavior**
QColor should not close when used inside a QDialog+QPopupProxy

**Platform (please complete the following information):**
OS: Windows 7
Node: 10.16
NPM: 6.9
Yarn: 1.19
Browsers: Chrome 78

Thank you Quasar team

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.2.
