### ISSUE TITLE
Long text on QBtn with "ellipsis" class does not truncate text

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#5533]
**Describe the bug**
If a QBtn is used, with long text, but the button is constrained to a fixed width, it would be expected that the text would be truncated when using the "ellipsis" calss.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Hawkeye64/pen/KKKBVGj?editors=1010

**Expected behavior**
The "ellipsis" class added to the QBtn would have some affect.

**Comment by pdanpdan** [comment]
Please use the default slot to render special case QBtns. Like

```html
<q-btn ...>
  <div class="ellipsis">
    This is some very long text that is expected to be truncated
  </div>
</q-btn>
```

**Comment by rstoenescu** [comment]
Added an example to docs. Will be available on next deployment.

**Comment by hawkeye64** [comment]
Ah, such an easy fix. Thanks.
However, most would think this is something that should be natively done in the in the component.
Using perhaps an 'ellipsis' prop?

**Comment by anli-xsigns** [comment]
This example is unfortunately not working together with stack property: https://codepen.io/anli-xsigns/pen/abLoJbG
You have to add elipsis and full-width to the div.

**Comment by motla** [comment]
Unfortunately this doesn't work with q-btn-dropdown. Ellipsis should maybe be the default behavior for button labels, I don't see a use case where the label should overflow...

---

[EDIT] You can make it work with this workaround:

```html
<q-btn-dropdown style="width: 100%">
  <template v-slot:label>
    <div class="ellipsis">
      This text is waaaaaaaaaay too long
    </div>
  </template>
  <q-list>
    // ...
  </q-list>
</q-btn-dropdown>
```
