### ISSUE TITLE
[docs] Landing on QDate doesn't load examples and spits a JS error

### ISSUE THREAD

**Issue by eyedean** [quasarframework/quasar#5535]
Repro: 
* Land on https://quasar.dev/vue-components/date
* It doesn't load the example components, also clicking on the hamburger menu (to expand sidebar) causes additional errors.  (See the screenshot)
<img width="439" alt="image" src="https://user-images.githubusercontent.com/5694695/68553376-670c5400-03d5-11ea-84d5-d69a0bbcf23a.png">

Additional Notes:
* It happens on both Firefox and Chrome, and both Cellular and WiFi.
* Landing on another page (say q-btn at https://quasar.dev/vue-components/button) and then navigating to qdate using side nav doesn't cause this issue.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fixed hydration errors and redeploying docs.
