### ISSUE TITLE
QMenu: re-apply target listeners/custom position

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5540]
**Is your feature request related to a problem? Please describe.**
I want to use QMenu with QColor. At the same time i want to show the current selected color for the element that opens the QMenu.
 - Mutating data while selecting a color re-renders also the QMenu when used as a child.
 - If QMenu is placed outside of the re-render the target listeners are lost

**Describe the solution you'd like**
 - ~Use `QMenu.updatePosition()` to re-apply target listeners~
 - Another idea: Use `QMenu.updatePosition(x,y)` with the x/y coods from a `@click` event or custom values

**Additional context**
Here a screenshot of the scenario. Currently you can click on a color field and than click at the card section (background) with the listener attached to open the picker next to the mouse
![cpfeat](https://user-images.githubusercontent.com/15967679/68584938-2e29b900-0481-11ea-8a78-9097482b2576.PNG)

Please share your ideas :)

Edit: The first idea is probably weird. As you need to update them continuous in some way

**Comment by pdanpdan** [comment]
Please add a codepen with the problem in order to test it. Thank you.

**Comment by brindosch** [comment]
I understand, not clear enough.
https://jsfiddle.net/edeltraud/q8pbz3cn/28/

Issue: Display QColor within a QMenu that opens on click at a color div that displays the current color (use while source data mutates)

 - In fiddle QMenu uses the parent div, but the parent shouldn't be the target.
 - The target should be the color div. But the re-renders destroy the listeners set from QMenu.
 - QMenu can't be a child of each div, as it would re-render during QColor use (Or is there a way to block?)
 -  Probably i miss something. Can the click events be captured from the parent by QMenu? That would be also a solution.

Thank you for your advice

**Comment by pdanpdan** [comment]
I think you want something like this: https://jsfiddle.net/n4vhbp5j/

**Comment by brindosch** [comment]
Genius!
Countless hours and the solution is so simple. It seems i need more think-in-vue. Thank you, next time i should visit the forum first :)
