### ISSUE TITLE
Text "cursor" going back in mobile

### ISSUE THREAD

**Issue by natajonasdacoliveira** [quasarframework/quasar#5542]
Mobile bug in which the text-cursor goes back one character when you type after any dot. It happens with masked inputs and is generally fixed with "type='tel'", however, with the auto grow property, this is not being fixed, probably due to auto grow being essentially a text-area instead of a input.

Using q-input with auto grow;

**Expected behavior**
The text should be filled without the cursor going back as I type;

Android:Android 7

**Additional context**
There's a know issue of android keyboard bug where you set the input tel to fix the behavior of the text cursor, which goes back when a dot is reached. 
Example: (as you are typing) text cursor -> | 
a: 212.|
b: 212.|2
c 212.1|2

these are the masks i'm using
'###########-# ###########-# ###########-# ###########-#' 
'#####.##### #####.###### #####.###### # ###############'

Here is the rule for mask application 
          

```
         <q-input
              bottom-slots 
              v-model="codigoBarra"
              label="Digite ou toque na câmera"
              type="tel" 
              maxlength="55"
              :mask="codigoBarraMask"
           />

        codigoBarraMask: function() {
          console.log(this.codigoBarra[0])
          console.log(typeof(this.codigoBarra[0]))
          if(this.codigoBarra[0] === '8') {
             return '###########-# ###########-# ###########-# ###########-#'
          } else {
            return '#####.##### #####.###### #####.###### # ###############'
          }
       }

```
UPDATE: As I can see in the web browser, it has the same issue, so it's not limited to platforms...

**Comment by pdanpdan** [comment]
Try to use a fill mask (`fill-mask="#"` should be good) - it's going to help with masks changing while you type.

And please provide a codepen where the problem can be reproduced.

Thank you.

**Comment by pdanpdan** [comment]
In the current version it should be as fixed as possible :)
You'll still get problems if you change the mask while beeing on a mask separator, but the rest should be ok.
