### ISSUE TITLE
[docs] Dark mode page not discoverable from search

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5543]
See screenshot. I tried to find info about the new dark mode, and couldn't find it. Had to go back to the release notes to find the link (yeah I could use my browser find functionality...)

![image](https://user-images.githubusercontent.com/83443/68601769-ae661380-04ad-11ea-9edd-d944c674ba15.png)

**Comment by rstoenescu** [comment]
Hi Tomers,

Refine the search.

![dark-mode-search](https://user-images.githubusercontent.com/4665641/68602385-e6ba2180-04ae-11ea-910c-c0d2d2af09f7.png)
