### ISSUE TITLE
https://quasar.dev is down?

### ISSUE THREAD

**Issue by educob** [quasarframework/quasar#5545]
Hi.

For several days now https://quasar.dev is down.

What's wrong?

Thanks.

**Comment by metalsadman** [comment]
> Hi.
> 
> For several days now https://quasar.dev is down.
> 
> What's wrong?
> 
> Thanks.

https://forum.quasar-framework.org/topic/4670/unable-to-load-quasar-dev-weekend-10-9-10-10/4

**Comment by rstoenescu** [comment]
The docs website is up and running. We had problems with our hosting and they were solved the same day.
If you still experience down time, please flush your DNS cache.

https://www.isitdownrightnow.com/quasar.dev.html

**Comment by educob** [comment]
Hi. I told a friend to load the site and it didn't work.
I disconnected my phone from wifi (never tried to open the site before on my phone) and it didn't work.
Something is going on with the website.

**Comment by pdanpdan** [comment]
Can you try to resolve quasar.dev? You should get 34.65.228.161

**Comment by educob** [comment]
Hi. I get 34.65.177.142.

When I enter 34.65.228.161in the browser I get this error:
`The deployment could not be found on ZEIT Now.`

**Comment by pdanpdan** [comment]
Check your dns resolver. And you cannot access virtual sites with ip, especially over https.

**Comment by ejez** [comment]
@educob can you check by changing your dns resolver (to [opendns](https://www.opendns.com/) for example)

https://support.opendns.com/hc/en-us/sections/206253647-Computer-Configuration

(Your dns resolving might be by default provided by you ISP, which might have an old cache)
