### ISSUE TITLE
QImg not work "src" for img to the project folder

### ISSUE THREAD

**Issue by dorcilio** [quasarframework/quasar#5546]
**Describe the bug**
I want to use QImg with images inside the project folder too, but it doesn't work.

**Example**
`  <q-img
            src="../../assets/logo-500.png"
            style="width: 500px"
            spinner-color="white">
            <template v-slot:error>
              <div class="absolute-full flex flex-center bg-negative text-white">
                Cannot load image
              </div>
            </template>
          </q-img>`

**Comment by pdanpdan** [comment]
Use the image from statics. Check https://quasar.dev/vue-components/img#QImg-API  - Model / src
