### ISSUE TITLE
text-uppercase class in q-input make uppercase validation error message too

### ISSUE THREAD

**Issue by nulele** [quasarframework/quasar#5548]
**Describe the bug**
When you insert text-uppercase class in q-input and the field fails validation, both the error message and the label are uppercase too.

<q-input class=text-uppercase" ... />

**Platform:**
OS: iOS for cordova App

**Comment by pdanpdan** [comment]
Use `input-class="..."` to apply a class to the input field. Check the docs.

**Comment by nulele** [comment]
Yeah! Didn't know...

Thanks!
