### ISSUE TITLE
Proposal for a q-form component

### ISSUE THREAD

**Issue by claustres** [quasarframework/quasar#555]
Quasar has a nice dynamic form generation from a JS configuration object when using a dialog, it would be great to reuse the same system in more view types such as standard modals or crude pages.

I looked at the dialog code and it reuse the modal component, maybe a first step in that direction is to make the modal class customizable so that we can create forms showing fullpage. Then the content of the modal in the dialog as today could become a **q-form** component that could be included in a dialog, a modal or a page.

**Comment by rstoenescu** [comment]
Hi, already in v0.14.

**Comment by claustres** [comment]
Really nice, all of you do a great job integrating user requirements, do you have any pointer on code/doc for this future feature because I looked in the quasar repo dev branch but could not find anything related (however I am not familiar with Quasar internals)

**Comment by rstoenescu** [comment]
Unfortunately not yet.
