### ISSUE TITLE
[Feature request]Add custom icon library settings to quasar.conf

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5554]
**Is your feature request related to a problem? Please describe.**
Custom icon library needed.

**Describe the solution you'd like**
Write the remote/local custom icon library address in quasar.conf and Quasar do the work automatically to different platforms.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pdanpdan** [comment]
What do you mean by `Write the remote/local custom icon library address in quasar.conf and Quasar do the work automatically to different platforms`? What should happen?
Just load the icon font for that custom library and use the icons (for usage in QIcon see https://quasar.dev/vue-components/icon#1.-Support-for-custom-icon-library)
