### ISSUE TITLE
On Linux, make Quasar search android studio executable also in snap path

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#5555]
**Is your feature request related to a problem? Please describe.**
On Linux, Android Studio executable is not found by clean install of Capacitor via Quasar, if it has been installed as a Snap package.

**Describe the solution you'd like**
Add `/snap/android-studio/current/android-studio/bin/studio.sh` in the below array, ideally at top, being Snaps the new standard way of installing apps in Linux to minimize installation problems.

https://github.com/quasarframework/quasar/blob/ad499e84e03b51f62f9fd189f7b0365056c7bafc/app/lib/helpers/open-ide.js#L44-L47

**Describe alternatives you've considered**
Into `quasar.config.js`:

```js
bin: {
 linuxAndroidStudio: "/snap/android-studio/current/android-studio/bin/studio.sh"
},
```

**Additional context**
As described [here](https://snapcraft.io/docs/snap-format), Snap applications are mounted into `/snap/<snap-name` and then versioned, with a symlink pointing to current version.

**Comment by pdanpdan** [comment]
The alternative you mentioned is the only one that can work for everybody. Sorry, but we cannot cover all the paths where some os puts the files.

**Comment by IlCallo** [comment]
After a brief research, you're right and Snaps aren't yet enough popular to be considered the new standard.
I'll come back at this if new statistics on its usage will show increased adoption in the future.

At last now the use case is documented somewhere :)

**Comment by akndako** [comment]
it was helpful. thanks

**Comment by mivas654** [comment]
I fixed it by creating `ln -s` to one of canonical paths))
