### ISSUE TITLE
quasar dev -m capacitor command fails to open android studio on windows

### ISSUE THREAD

**Issue by SylvesterNielsen** [quasarframework/quasar#5556]
**Describe the bug**
When running the command `quasar dev -m capacitor -T android` on windows, Android studio is expected to open but fails due to an unescaped path with special characters. Space character in the _Program Files_ part when using the default path.

`const studioPath = 'C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe'`

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
1. run `quasar dev -m capacitor -T android` on windows with android studio installed in default path
2. See error

**Expected behavior**
I expect Android studio to open the capacitor project.

**Screenshots**
![quasar-open-ide-error](https://user-images.githubusercontent.com/2431914/68695181-da02ff80-057a-11ea-8546-1c94e1e42b19.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: v10.13.0
NPM: 6.4.1
Yarn: 1.12.3
Browsers: NA
iOS: NA
Android: NA
Electron: NA

**Additional context**
PR created: https://github.com/quasarframework/quasar/pull/5557

**Comment by pdanpdan** [comment]
You need to escape the space also, I think.

Can you try by setting `quasar.conf.js > bin > windowsAndroidStudio` to

`windowsAndroidStudio: 'C:\\Program\ Files\\Android\\Android Studio\\bin\\studio64.exe'`

or to

`windowsAndroidStudio: '"C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe"'`

**Comment by SylvesterNielsen** [comment]
> You need to escape the space also, I think.
> 
> Can you try by setting `quasar.conf.js > bin > windowsAndroidStudio` to
> 
> `windowsAndroidStudio: 'C:\\Program\ Files\\Android\\Android Studio\\bin\\studio64.exe'`
> 
> or to
> 
> `windowsAndroidStudio: '"C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe"'`

Both of the above solutions were attempted without luck.
Since the default path is found, any additional configuration is skipped.

The returned path can be seen at: https://github.com/quasarframework/quasar/blob/6d3ff82628ff084ee1b4be5816861711ee6f0fef/app/lib/helpers/open-ide.js#L90

The solution I suggested is to add the quotes at the open command:
https://github.com/quasarframework/quasar/blob/6d3ff82628ff084ee1b4be5816861711ee6f0fef/app/lib/helpers/open-ide.js#L121

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "@quasar/app" v1.2.4.

**Comment by dvbianculli** [comment]
As a heads up, Im running into the same issue here on v1.2.4. I fixed it locally for myself by changing the path to
`const studioPath = 'C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe'`

and then 

`app: `"${studioPath}"``

in that open command like @SylvesterNielsen suggested. That solved the issue for me

**Comment by 2x2xplz** [comment]
Please re-visit, this fix was not included in 1.2.4. Thanks!

**Comment by rstoenescu** [comment]
New PR will be included in "@quasar/app" v1.2.5.

**Comment by JayteeNZ** [comment]
Hi guys,

I seem to be having this issue on the latest release of quasar.

It was working fine, then all of a sudden, it couldn't open Android Studio (along with some IDE errors when opening Android Studio manually). No matter what I did, studio would not open.

I've just re-installed Windows on my PC, in hopes that it was just something gone wrong somewhere, but again, have an issue opening Android Studio on a fresh install of everything.

**Specs:**:

- Windows 10 Build 1903
- Capacitor
- Pkg quasar........ v1.9.13
- Pkg @quasar/app... v1.6.1

**Comment by matamune94** [comment]
me too, how can fix ?

Specs::
Windows 10 Build 1903
Capacitor
Pkg quasar........ v1.9.14
Pkg @quasar/app... v1.6.2

**Comment by rstoenescu** [comment]
@matamune94  There was a new problem and it will be fixed in "@quasar/app" v1.7.0
