### ISSUE TITLE
problem with RTL

### ISSUE THREAD

**Issue by omaralwi** [quasarframework/quasar#5558]
you say in doc to add RTL , To enable it, you need to edit /quasar.conf.js:
I am using quasar with laravel this project https://github.com/HansSchouten/Laravel-Vue-Quasar-SPA
I did not found quasar.conf.js
please any idea about that.?
OR if you can help me how to use Quasar in [this project ](https://github.com/tuandm/laravue)

**Comment by pdanpdan** [comment]
https://quasar.dev/options/rtl-support#Handling-Quasar-UMD
