### ISSUE TITLE
[QDate] - Mask is not used for the options callback argument

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar#5559]
**Describe the bug**

When a specific mask is set for the `QDate` component, the `options` callback does NOT provide a date with the same format.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/erakis/pen/oNNGVRm?editors=1010

**To Reproduce**

1. Go to the [exemple](https://codepen.io/erakis/pen/oNNGVRm?editors=1010).
2. Click on a calendar date and look at the two label under.

**Expected behavior**

Getting the same format as the mask. Unless it's meant to be `yyyy-mm-dd` all the time for a specific reason ?

**Screenshots**

Note that mask is `MM/DD/YYYY` but on the options function callback we received a date with a different format `YYYY-MM-DD`.

![image](https://user-images.githubusercontent.com/7946730/68701264-63eba200-0554-11ea-9545-98f11345bd48.png)

**Platform (please complete the following information):**

OS: N/A
Node: N/A
NPM: N/A
Yarn: N/A
Browsers: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

N/A

**Comment by pdanpdan** [comment]
This is by design. The mask can by dynamic, different for different clients of the same application.
The functions called for `options` and `events` are called lots of times and must be efficient.

See here for more details: https://github.com/quasarframework/quasar/issues/4560

**Comment by purell** [comment]
@pdanpdan Thanks you so much, the answer make sens and this is what I tought.

I think that mention it the documentation would be clearer and would avoid this question to be asked again soon.

**Comment by lucianobosco** [comment]
Sorry for writing here 2 years later, but I'm facing same situation.
Having 2 q-date elements with `mask="DD/MM/YYYY"` I want to enable dates for second input while dates are before the selected one from first q-date
How could I achieve this?
```
:options="date => date >= filter.date_from"
```
