### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by paranoid-android** [quasarframework/quasar#556]
Personally, I work primarily in Windows 10. I would love it if the Quasar Framework added UWP support as a target.

**Comment by rstoenescu** [comment]
Will take this into consideration. Thanks for filing this.

**Comment by rhyek** [comment]
I support this righteous endeavor.

**Comment by rstoenescu** [comment]
Hi,

I'm afraid there's not enough interest into this, so dropping it, at least for now. Sorry for any inconvenience.
