### ISSUE TITLE
FR: Update local files on "quasar upgrade" rather than on "quasar dev" or post a warning message

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#5560]
**Is your feature request related to a problem? Please describe.**

I was somewhat surprised after I had upgraded quasar to find that running `quasar dev` had changed the viewport meta tag in my index.template.html file.  I don't expect running a webserver or a development environment to make changes to the files that are being served.

**Describe the solution you'd like**

I would have preferred for the file to be upgraded when running `quasar upgrade` or instead for a warning to be posted that is persistent in the terminal (i.e. underneath where it says "DONE  Compiled successfully in XYZms"), something along the lines of "run this command: xyz" or "a change to index.template.html is needed; see http://quasar.dev/changelog or https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fextras-v1.3.3" .

The "Updated viewport-fit in /src/index.template.html to latest Quasar specs" message in my terminal was easily missed by me the first time, since I wasn't expecting to have to look for such a message.

I am going to commit the change that was made (to my local repository) but in general the approach I've described above (or something similar) would be less surprising to developers using Quasar, i.e. if similar changes need to be made in the future.

**Additional context**

See https://github.com/quasarframework/quasar/blame/48661136f5f02951942a3facaa171a97f0ae2965/app/lib/app-files-validations.js#L28-L38

**Comment by rstoenescu** [comment]
Hi,

We will improve this. Right now, due to the heavy load, all we want is to ensure that the apps are consistent with the specs so that everything "simply works".

Thanks for your write-up.
