### ISSUE TITLE
[Feature Request] QPageScroller support scroll direction (inverted)

### ISSUE THREAD

**Issue by cnk789** [quasarframework/quasar#5561]
**Is your feature request related to a problem? Please describe.**
Some applications (e.g. Messaging apps) may add new content to the bottom of a page.  When a user scrolls upward to see old content, QPageScroller should allow them to scroll back down to the bottom of the page.

**Describe the solution you'd like**
A optional property on QPageScroller to specify the scroll direction.  [direction="up|down"].  "Up" would be the current default functionality, while "down" would scroll the user to the bottom of the element.

**Comment by rstoenescu** [comment]
Feature will be available in "quasar" v1.9.0 through "reverse" Boolean prop.
