### ISSUE TITLE
Datepicker: navigate with touch events (swipe)

### ISSUE THREAD

**Issue by getriebesand** [quasarframework/quasar#5562]
**Is your feature request related to a problem? Please describe.**
Changing month on smartphones is hard only with the arrow buttons.

**Describe the solution you'd like**
I want to swipe left and right on calendar to change month (like other apps with date picker on android)

**Describe alternatives you've considered**
I could implement it by my self, but i think it will be a nice feature for quasar with focus on mobile apps

**Additional context**

**Comment by pdanpdan** [comment]
I think that the best way is to implement it on the user side - I added an example here (uses a few internals but should be safe): https://codepen.io/pdanpdan/pen/qBdExzK?editors=1010
