### ISSUE TITLE
Electronic has been upgraded to 7.1.1, can quasar update the new version?

### ISSUE THREAD

**Issue by xiaoer3301** [quasarframework/quasar#5564]
It is recommended to upgrade the updated version for ease of use. Otherwise, we need to look through the old version and not use the new api.
Quarar is still using 5.0.11, and the latest version of electron is already 7.1.1.

**Comment by xiaoer3301** [comment]
Manually install the latest version of electron, there will be problems when using quasar cli, I hope to get quasar official support!

**Comment by TobiasTao** [comment]
related #5455

**Comment by mYnDstrEAm** [comment]
also related https://github.com/quasarframework/quasar/issues/5531

**Comment by rstoenescu** [comment]
Done with "@quasar/app" v1.3.0.
