### ISSUE TITLE
Dark plugin doesn't exist

### ISSUE THREAD

**Issue by KolCrooks** [quasarframework/quasar#5565]
I have tried to create a dark mode with
`import { Dark } from "quasar";`
and
`this.$q.dark.set(true);`
but in both cases it says that dark is not defined. I am not sure why this is happening as I have the latest version of quasar installed (1.4.3). I am using the quasar vue plugin.

**Comment by KolCrooks** [comment]
I found out that quasar is running version 1.2.7. This was weird to me because my package.json says that I am using version "^1.4.3".  How do i update to the latest version?

**Comment by metalsadman** [comment]
> I found out that quasar is running version 1.2.7. This was weird to me because my package.json says that I am using version "^1.4.3". How do i update to the latest version?

run `quasar upgrade -i`.

**Comment by pdanpdan** [comment]
There are 2 parts, quasar-cli and quasar framework. Update the deps.

**Comment by KolCrooks** [comment]
I am running a vue project and am using the vue quasar plugin to get the quasar components.
Looking through my package-lock.json I found 3 relevant quasar packages:
```Json
    "@quasar/extras": {
      "version": "1.3.2",
      "resolved": "https://registry.npmjs.org/@quasar/extras/-/extras-1.3.2.tgz",
      "integrity": "sha512-EGBvl4By7Cv/WFGD4dc2FX+iLA+GX7YOnDj8AH92Df4pSMDKxP3TdvpXRnKs3V6bfHKyafc3VklVdf30hT5EoA=="
    },

    "quasar": {
      "version": "1.4.3",
      "resolved": "https://registry.npmjs.org/quasar/-/quasar-1.4.3.tgz",
      "integrity": "sha512-0647iJgyF52R35RWQcIHfWz8phA5XbCb46TM2R93JnyguYxoxBpG7vIU5ltgc8huKcRYpvlz+DHUd317WjsMPw=="
    },

    "vue-cli-plugin-quasar": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/vue-cli-plugin-quasar/-/vue-cli-plugin-quasar-1.0.0.tgz",
      "integrity": "sha512-15Jeu/NaGsPAlxf9Q+w1TnF+gUbcJfbgz94f8Mcs3zqBLnSl9VIOFWsYmaeVFc/nwCCkKeVohCCRa/IQBfTC7A==",
      "dev": true
    },
```
Everything is up to date except the extras package but this isn't the part that I am having trouble with.

Should I try and convert my vue project to a quasar project? How I even do that?
I just installed the cli version and it doesn't allow me to update quasar using `quasar upgrade -i` because it is a vue project.
