### ISSUE TITLE
Function 'endOfDate' with unit 'year' in utils don't work properly

### ISSUE THREAD

**Issue by tequila99** [quasarframework/quasar#5568]
When I try to get the result (end of the year) and use the date as a parameter, which month can be Feb, Apr, Jun, Sept or Nov - I will get the wrong result.

https://codepen.io/tequila99/pen/xxxaJpy

In order to fix this issue I suggest to replace this code in the function **endOfDate**:

`t.setDate(daysInMonth(date))`

on that code:

`t.setDate(daysInMonth(t))`

It will solve this issue.

Thanks.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.4.4.
