### ISSUE TITLE
[Request] Add $q.dark.toggle()

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#5572]
Instead of tedious `@click="$q.dark.isActive ? $q.dark.set(false) : $q.dark.set(true)"` it would be great if there would be a standard toggle function: `@click="$q.dark.toggle()"`

**Comment by pdanpdan** [comment]
`@click="$q.dark.set($q.dark.isActive === false)`

**Comment by rstoenescu** [comment]
$q.dark.toggle() will be available in "quasar" v1.4.4.

**Comment by tomers** [comment]
Thanks @rstoenescu !

P.S. @pdanpdan, I would write it in a more concise way than I wrote in the description `@click="$q.dark.set(!$q.dark.isActive )"` (the original code was lazily copied from elsewhere)

**Comment by rstoenescu** [comment]
Write it as `@click="$q.dark.toggle"` with v1.4.4+
