### ISSUE TITLE
print-only and print-hide do not work

### ISSUE THREAD

**Issue by Alfgar** [quasarframework/quasar#5573]
**Describe the bug**
These two classes do not work.

They are apparently defined as:

@media (screen) {
    .print-only {
      display: none !important; } }
  
  @media (print) {
    .print-hide {
      display: none !important; } }
  
--

I was able to fix the problem by redefining as follows in my own CSS:

@media screen {
    .print-only {
      display: none !important; } }
  
  @media print {
    .print-hide {
      display: none !important; } }

**Comment by rstoenescu** [comment]
Fixed the Sass implementation.
Will be available in "quasar" v1.4.4.
