### ISSUE TITLE
Can't access quasar.dev from Brazil

### ISSUE THREAD

**Issue by PedroBatista333** [quasarframework/quasar#5575]
**Describe the bug**
Can't access quasar.dev from Brazil. When I use some proxy, in order to access from other country, it works.

**Comment by supakornkim** [comment]
I also cannot access from Cambodia

**Comment by pdanpdan** [comment]
You're using a bad DNS resolver - probably your internet provider does not respect the caching TTLs.
There is nothing we can do, but you can switch to using a good DNS resolver, there are a lot of them.
