### ISSUE TITLE
Cookies.set expires with other units

### ISSUE THREAD

**Issue by relaxdays-bewerbung** [quasarframework/quasar#5576]
**Is your feature request related to a problem? Please describe.**
Security cookies usually don't last for days. Creating a cookie that lasts 15 minutes is a pretty common use case for security tokens.
Honestly I was a bit confused about the number value being interpreted as days, since the common JavaScript unit is milliseconds.

**Describe the solution you'd like**
Allow strings for Cookies.set expires option that contain a number + a unit.
Example:
* '15m'
* '1h'
* '13d'
* '1d 15m'

**Describe alternatives you've considered**
Of course it works fine with giving a Date object, this is just about extending the comfotabillity.

**Comment by rstoenescu** [comment]
Hi,

Thanks for the suggestion.
Will be available in "quasar" v1.6.2.
