### ISSUE TITLE
Allow Users to set 'nodeIntegration' to false in electron mode.

### ISSUE THREAD

**Issue by newCodeRunner** [quasarframework/quasar#5577]
**Describe the bug**
Quasar is an exceptionally good tool. However, Quasar does not allow users to set 'nodeIntegration' to false in electron mode as the documentation already states that it should be set to true in
https://quasar.dev/quasar-cli/developing-electron-apps/troubleshooting-and-tips.

**Expected behavior**
When set to 'true', webpack should not require 'electron' or other node modules in renderer process. Instead it should allow users to use an Electron 'Preload' Script as a static asset (to require node-modules), which the users can then use to preload node modules while maintaining the highest levels of security.

Note: Electron preload scripts can 'require' node modules even with nodeIntegration set to false.

If someone has a work around for this, any help would be highly appreciated.

**Comment by newCodeRunner** [comment]
Removing these lines from the client-entry.js in .quasar folder (during development mode)
`
import electron from 'electron'
Vue.prototype.$q.electron = electron
`


and setting webpack externals (native node modules) and target to 'web' in quasar.conf.js seems to work with 'nodeIntegration: false' for Electron Mode. 

`
build: {
extendWebpack(cfg) {
if (ctx.mode.electron) cfg.target = 'web';
cfg.externals = ['better-sqlite3', 'electron-updater', 'serialport', 'dot-prop'];

// Rest of the config Options go here
}
}
`

But i am still stuck, since I cant find a way to edit client-entry.js before build process during the 'quasar build' cli command.

Is there a hook to manually edit client-entry.js before webpack building process occurs? Or is there
a way to customize what Quasar puts in the client-entry.js file.

**Comment by newCodeRunner** [comment]
To anyone interested, solved the issue by commenting out the following code in node_modules\@quasar\app\templates\entry\client-entry.js

Feels hacky, unless the Quasar team decides to enable nodeIntegration to true by default, or allows customization for preload and renderer-scripts separately. Security comes first.

<% if (ctx.mode.electron) { %>
// import electron from 'electron'
// Vue.prototype.$q.electron = electron
<% } %>

**Comment by rstoenescu** [comment]
More info will be available here (after the next docs deployment and quasar/app v1.3.0 release): https://quasar.dev/quasar-cli/developing-electron-apps/node-integration

**Comment by rstoenescu** [comment]
Some changes for the quasar/app v1.3.0:
* node integration remains "on" by default
* new flag in /quasar.conf.js > electron > nodeIntegration (which must be kept in sync with configuration from main thread).
