### ISSUE TITLE
[Feature request]Drag and drop with Qtable

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5579]
**Is your feature request related to a problem? Please describe.**
I tried Vue.Draggable with q-table and v-slot, got failed

**Describe the solution you'd like**
Drag and drop with Qtable.

**Comment by pdanpdan** [comment]
And the details about what you want to be implemented with drag'n'drop?
Can you please specify some of them?

Can you also make a codeped showing what you did and what problems have you encountered?

Thank you.

**Comment by hugetiny** [comment]
I use q-list and q-card instead, and Vue.Draggable works
