### ISSUE TITLE
Drawer not closing on drawer-link click in iOS theme

### ISSUE THREAD

**Issue by boyd91** [quasarframework/quasar#558]
### Software version

Quasar: 0.13.6
OS: iOS

### What did you get as the error?
The drawer is not closing when a `<drawer-link>` was clicked when using the iOS theme.
- This issue does only appear when building with iOS theme.
- This does only happen when using the iOS theme. Everything works as expected in the material design version.
- It seems to be a CSS issue as the `active` class is properly removed from the drawer element.

### What were you expecting?
That the drawer was closed.

### What steps did you take, to get the error?
1. Have a drawer containing a `<drawer-link>`
2. Build with iOS theme.
3. Click a `<drawer-link>`
4. Watch the drawer not being closed.

**Comment by rstoenescu** [comment]
Hi,

`drawer-close` class is not required on a `<drawer-link>`. Check example here: https://github.com/quasarframework/quasar-play/blob/dev/src/components/showcase/layout/layout.vue#L34-L36

Please reopen if I misunderstood.

**Comment by boyd91** [comment]
I know, but I was only referring to the underlying implementation. I'm not using it on the `<drawer-link>` in my vue template, I just saw that it was the mechanism that closes the drawer after a click on a drawer link.

I mentioned it because the issue does not appear when I try to close it by calling `$refs.drawer.close()`.

**Comment by rstoenescu** [comment]
It looks nothing wrong on Quasar Play app (http://quasar-framework.org/quasar-play/apple/index.html#/showcase/layout/toolbar --> resize to a small width window). Maybe it might be something in your implementation. Any repo I can take a look to reproduce, pls? Thanks!
