### ISSUE TITLE
QPullToRefresh with nested QSlideItem?

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5587]
**Describe the bug**
Love the fixes for #5367 via #5441. Is it possible to get it working with nested `q-slide-item`s?

Not 100% sure if this is considered a bug because I don't know if nested `q-slide-item` are even supported (but they seem to work fine).

Imagine a component with items grouped by headings where you can swipe an individual item to delete, or swipe the heading to delete the entire group (kinda like how OS notifications work). With `q-pull-to-refresh` around it, the pull-to-refresh works fine if you drag from a heading, but not if you drag from a sub-item.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gordonblahut/pen/xxxyymd

**To Reproduce**
1. Go to the codepen above
2. Drag down from a "group" row
3. See pull to refresh fire
4. Drag down from a nested "item" row
5. Pull to refresh does not fire
6. (optional) Swipe to the left on a heading or nested item row to see that slide item works for group or individual item

**Expected behavior**
Pull to refresh works anywhere since none of the items have a "down" template.

**Platform (please complete the following information):**
Quasar 1.4.3 on Codepen
Tested in Firefox and Chrome on Desktop Windows 10

**Comment by pdanpdan** [comment]
It's a feature :) Thank you very much for catching it, it'll be fixed in the next release, sorry.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.4.
