### ISSUE TITLE
Data Table: Make Table Headers Within <q-data-table> Show Title By Default

### ISSUE THREAD

**Issue by joelhickok** [quasarframework/quasar#559]
#### Data Table Component

By default, text within `<th>` elements in a Data Table is truncated if it overflows the width of the column.  The `title` attribute should be applied to `<th>` elements by default so that the full text is displayed when the user rolls over the column header.

See image below which corresponds to the HTML examples.

`<th class="sortable" title="Projected Unpaid"><i class="cursor-pointer">import_export</i><span>Projected Unpaid</span></th>`

###### OR

`<th class="sortable"><i class="cursor-pointer">import_export</i><span title="Projected Unpaid">Projected Unpaid</span></th>`

If the use of the `title` attribute is not the preferred method for displaying the full inner `<th>` contents, then another approach may be useful.

<img width="214" alt="screenshot 2017-05-09 06 04 10" src="https://cloud.githubusercontent.com/assets/6742308/25852684/085e692a-347f-11e7-9f6d-07b1fa9e6898.png">

**Comment by rstoenescu** [comment]
Will be available in v0.13.8 (releasing it in a few hours) and future v0.14.

**Comment by rstoenescu** [comment]
Available in v0.13.8 (just released it).

**Comment by joelhickok** [comment]
Great thanks!
