### ISSUE TITLE
Selected value colors in QSelect

### ISSUE THREAD

**Issue by martinpare** [quasarframework/quasar#5590]
Your framework is awesome.

I suggest that the selected value colors in the dropdown of the QSelect (by default, blue on light-blue background) should be consistent with the **color** prop when it is specified in the component props.

Thanks

**Comment by rstoenescu** [comment]
Hi,

Thanks for the suggestion.
Will be available in "quasar" v1.4.4.

**Comment by martinpare** [comment]
Thank you very much.
