### ISSUE TITLE
QEditor text styles naming

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#5593]
QEditor text styles should be named "Heading 1, Heading 2,..." instead of ""Header 1, Header 2,...",

Header in html has a different meaning.

https://html.spec.whatwg.org/multipage/sections.html#the-header-element
https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements

**Comment by pdanpdan** [comment]
Can you please try to create a PR for this. Thank you.

**Comment by ejez** [comment]
will do

**Comment by ejez** [comment]
One issue to note is that some translations might be based on the word "Header" instead of "Heading", and therefore might not be precise. An example was the Arabic translation, which I already submitted a [PR](https://github.com/quasarframework/quasar/pull/5592) for it.
