### ISSUE TITLE
[docs] Inifinite Scroll with scroll area

### ISSUE THREAD

**Issue by pereslava** [quasarframework/quasar#5599]
Hello. I've looked to q-scroll-area, which is great for for lists in dedicated view port, and to the q-inifinite-scroll, which is very great to create some infinite lists.

Each one is great tool, but a have not found the way to use it together.
In few words I want to implement the infinite scroll inside the scroll area.
I tried to use scroll area inside infinite scroll and infinite scroll inside the scroll area. All of this are outside of layout and outside of the page container.
Actually the "load" of the infinite scroll is calling, but list is not rendering.

This is just a question can i use is together?

**Comment by pdanpdan** [comment]
Please create a codepen with QInfiniteScroll inside a QScrollArea and put the url here (don't forget to save)

**Comment by pereslava** [comment]
Strange, but in codepen with plain js it is working. could be my bad...

**Comment by Pranav-Bobde** [comment]
@pereslava i'm facing issue implementing the same, can you please share your code (codepen, etc.) how you did it. I really need it ASAP.

**Comment by Naskalin** [comment]
A minimal working example, everything works out of the box. Hope it saves someone some time :)

```
<template>
    <q-scroll-area style="height: 500px; max-width: 300px;">
        <q-infinite-scroll @load="onLoad" :offset="250">
            <div v-for="(item, index) in items" :key="index" class="caption">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum repellendus sit voluptate voluptas eveniet porro. Rerum blanditiis perferendis totam, ea at omnis vel numquam exercitationem aut, natus minima, porro labore.</p>
            </div>
            <template v-slot:loading>
                <div class="row justify-center q-my-md">
                    <q-spinner-dots color="primary" size="40px" />
                </div>
            </template>
        </q-infinite-scroll>
    </q-scroll-area>
</template>

<script setup lang="ts">
import {ref} from "vue";
const items = ref([ {}, {}, {}, {}, {}, {}, {} ])
const onLoad = (index: any, done: any) => {
    setTimeout(() => {
        items.value.push({}, {}, {}, {}, {}, {}, {})
        done()
    }, 500)
}
</script>
```
