### ISSUE TITLE
[Request] select all rows in Data Table

### ISSUE THREAD

**Issue by llin55** [quasarframework/quasar#560]
Could you please add a possibility to select all visible rows in Data Table with a checkbox in a header?
Thank you in advance!

**Comment by rstoenescu** [comment]
Will do. Thanks for filing this.

**Comment by lyquocnam** [comment]
+1 :)

**Comment by ygorcf** [comment]
hi, i'm find a solution: 
this is the function for select all:
function selectAll() {
        this.$refs.dtable.clearSelection()
        this.$refs.dtable.selectedRows.push(this.$refs.dtable.rows[0])
        this.$refs.dtable.selectedRows.push(this.$refs.dtable.rows[1])
        this.$refs.dtable.rowSelection[0] = true
        this.$refs.dtable.rowSelection[1] = true
        // this.$refs.dtable.rowsSelected = 2
        // this.$emit('selection', this.rowsSelected, this.selectedRows)

        // this.$refs.dtable.$emit('selection', this.$refs.dtable.rowsSelected, this.$refs.dtable.selectedRows)
        this.$refs.dtable.toolbar = 'selection'
}
and the data-table component:
<q-data-table ref="dtable" :data="table" :config="config" :columns="columns">

**Comment by lyquocnam** [comment]
@ygorcf we need a checkbox on header too 💃

**Comment by rstoenescu** [comment]
Closing as code is ready in future v0.15 datatable revamp.

**Comment by laonawuli** [comment]
@rstoenescu Hi! When will v0.15 be out? Thanks!

**Comment by apappas1129** [comment]
Is there an event for when you click the select-all checkbox from the header?
