### ISSUE TITLE
Text wrapping in q-slider

### ISSUE THREAD

**Issue by yajam** [quasarframework/quasar#561]
### Software version

Quasar: v0.13.6

Any other software related to your bug:

### What did you get as the error?
Text wrapping in q-slider does not work.

### What were you expecting?
If text in each slide is longer than the size of the slide text should wrap, instead it is displayed in one line.

### What steps did you take, to get the error?
q-slider with long text below an image in each slide

**Comment by rstoenescu** [comment]
Fix was available in edge version, so just published v0.13.7 which addresses this issue.
