### ISSUE TITLE
QTabPanels background

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5610]
**Is your feature request related to a problem? Please describe.**
 - QTabPanels shouldn't provide it's own background (`#fff`).
 - Instead it should inherit from the parent. To be more inline with dark/**light** mode global css. If you want a specific background, just add as before.
 - In my case the body color for **light** isn't white, so i need to overwrite the white. If i remove that color, it inherits from body.
https://jsfiddle.net/edeltraud/npjh58wb/11/

**Comment by pdanpdan** [comment]
The problem with inherit on background is that it only inherits from the direct parent (so you must make sure the whole chain of parent elements have `background: inherit` or a background set).
You can always do something like this:
https://jsfiddle.net/gntd57ho/3/
