### ISSUE TITLE
QTree styling

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#5614]
Although QTree does support scoped slots for this purpose, it does't yet allow adequate customized styling without playing hardly with css.

Take a look at the picture below.

![QTree](https://user-images.githubusercontent.com/37274701/68993629-dc1ed400-0882-11ea-99b4-2c6451bba277.png)

What looks rather odd to me is that:

(a) When a disabled item is the last child of a parent, then the angle of the link line follows the color of the disabled item breaking the vertical line in two parts. I'd expect all paths (at least the vertical borders) to have the same color regardless of whether they connect enabled or disabled nodes.

(b) The node "Calibration" and the leaf "Create documentation", although they belong to the same level, there is not a straightforward way to align them. Yes, I could use a scoped slot to increase the indentation of nodes, but this would (a) leave huge space between arrows and their corresponding labels and (b) increase the width of the tree. It could be nice to have a way of customizing indentation, so as leaves' icons to be aligned with nodes' arrows.

Lastly, a "dense" mode would be very useful.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.10.
