### ISSUE TITLE
Empty QTabs shows extra chevron buttons

### ISSUE THREAD

**Issue by npokr** [quasarframework/quasar#5616]
**Describe the bug**
Empty QTabs shows useless chevron buttons on Chrome and Quasar 1.4.3. 

**To Reproduce**
1. Open Chrome (Firefox is ok)
2. Go to https://quasar.dev/vue-components/tabs#Dynamic-update
3. Click on checkbox to hide all tabs
4. See button with chevron_right icon at right side of toolbar.

**Expected behavior**
No chevron buttons as it was in version 1.4.1 and earlier

**Platform (please complete the following information):**
OS: Windows 10 64 1903
Browsers: Google Chrome 78.0.3904.97 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.4.4.
