### ISSUE TITLE
Incorrect / undefined values from this.$q.screen

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#5622]
**Describe the bug**

Quasar 1.4.3  - Latest

**To Reproduce**
Steps to reproduce the behaviour:

1. Run a Quasar 1.4.3 app
1. Open Chrome debugger and set screen mode to Responsive and adjust screen width to 675 pixels.
1. Set a break point in the component being test.
1. In Chrome debug console I checked these values .... 

this.$q.screen.gt.sm
**false** <<< NO!
this.$q.screen.lt.sm
false

this.$q.screen.lt.md
true
this.$q.screen.gt.md
false

this.$q.screen.gt.xs
true
this.$q.screen.lt.xs
**undefined**  <<< HUH?

this.$q.screen.lt.lg
**true**
this.$q.screen.gt.lg
**false**

**Expected behavior**
- this.$q.screen.gt.sm should be true. 
- this.$q.screen.lt.xs should not be undefined

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Chrome  78.0.3904.97

**Comment by pdanpdan** [comment]
Only true values are guaranteed by the plugin. Non true values can be false or undefined (as with the Platform.is ). lt.md true and gt.sm false is correct. You wanted to say gt.xs?

**Comment by pdanpdan** [comment]
I rechecked your case:

1. this.$q.screen.gt.sm === false is correct (default sm breakpoint is from 600 to 1023)
2. this.$q.screen.lt.xs === undefined is correct (there is no such thing, xs is the first breakpoint, nothing can be smaller)

Maybe you didn't understand the idea of the breakpoints:

- the first defined breakpoint is xs and starts from 0 up to the next breakpoint start -1
- .gt.xx means the size is greater than the maximum value for that breakpoint
- .lt.xx means the size is smaller than the minimum value for that breakpoint
- .xx means the size is between minimum and maximum value for that breakpoint

**Comment by tohagan** [comment]
Thanks ... I think the range concept was not clear from documentation.
