### ISSUE TITLE
Capacitor platform detection not working (android)

### ISSUE THREAD

**Issue by aidan-mundy** [quasarframework/quasar#5626]
**Describe the bug**
Sideloaded apps (via `quasar dev -m capacitor -T android`) have platform detected as chrome rather than capacitor. All other platform types are correct as far as I can tell. Not tested in prod, not tested with ios.

(cant be replicated with any of the code running websites provided as they don't run capacitor)

**To Reproduce**
1. Make an app for capacitor
2. Use a `<div v-if="!$q.platform.is.capacitor"></div>` to hide an element on an android app (doesnt have to be done this way. Just examining the value of `$q.platform.is.capacitor` is sufficient)
3. Build it with `quasar dev -m capacitor -T android` to a real device or the emulator (same result)
4. Notice that the element will not be hidden even though it should be
5. Try it with `!$q.platform.is.chrome` (still in a capacitor app and same build command) instead and it will be hidden even though it shouldn't be
6. Cry

**Expected behavior**
`$q.platform.is.chrome` should return false
`$q.platform.is.capacitor` should return true

**Platform (please complete the following information):**
OS: Windows 10 Pro 1803
Node: v12.12.0
NPM: 6.13.0
Yarn: Not installed
Browsers: N/A
iOS: N/A
Android: 9 and 10
Electron: N/A

**Comment by aidan-mundy** [comment]
So, after doing some research on another problem, I came across an interesting tidbit that may explain at least part of this issue: In android 7 and above, devices with the Chrome browser installed will use Chrome to render Webview apps rather than Webview. If the platform detection detects Webview as $q.platform.is.capacitor, it will be false (and $q.platform.is.chrome will be true) on updated android devices with chrome installed 
(and basically everyone on android has chrome installed).

**Comment by metalsadman** [comment]
@aidan-mundy just tested on android 9 emulator. it's detecting correctly
```js
CAPACITOR APP::: {userAgent:mozilla/5.0 (linux; android 9; android sdk built for x86_64 build/psr1.180720.093; wv) applewebkit/537.36 (khtml, like gecko) version/4.0 chrome/69.0.3497.100 mobile safari/537.36,is:{chrome:true,version:69.0.3497.100,versionNumber:69,android:true,mobile:true,webkit:true,name:chrome,platform:android,capacitor:true,nativeMobile:true,nativeMobileWrapper:capacitor},has:{touch:true,webStorage:true},within:{iframe:false}}
```

**Comment by rstoenescu** [comment]
Everything looks ok on both dev and production with Android API v29.

**Comment by yusufkandemir** [comment]
@aidan-mundy I am not sure if you have noticed but you are using `!` to negate the result.
`<div v-if="$q.platform.is.capacitor"></div>` will be shown only on Capacitor
`<div v-if="!$q.platform.is.capacitor"></div>` will be shown on everything except Capacitor.

You are explaining the right thing in `Expected Result` section but using the reverse in your example.

**Comment by jcesarmobile** [comment]
Do you have `EnableHttpsSelfSigned.enable(findViewById(R.id.webview));` in your `MainAcitivity.java`?

That prevents Capacitor from being injected and uses web plugins instead of native plugins, probably causing this platform detection problems too.

**Comment by pdanpdan** [comment]
Hello. I just tested again and the detection looks fine.
Please reopen if you still have problems.
Thank you.
