### ISSUE TITLE
npx quasar dev - Failed to open default browser - Ubuntu WSL

### ISSUE THREAD

**Issue by oronbz** [quasarframework/quasar#5627]
**Describe the bug**
When running `npx quasar dev` from a brand new SPA project in WSL (Ubuntu) it cannot open windows browser:
```
 app:dev-server Opening default browser at http://localhost:8080 +8s

 app:dev-server ⚠️  Failed to open default browser +29s
```

And then a windows alert showing up (See screenshots below)
When browsing manually to `http://localhost:8080` everything seems to work.

**To Reproduce**
1. Use WSL/WSL2 Ubuntu
2. Generate new project using `$ quasar create <folder_name>`
3. Run `$ npx quasar dev`

**Expected behavior**
Chrome or another default browser opens with `http://localhost:8080`

**Screenshots**
![image](https://user-images.githubusercontent.com/1288090/69031579-143d2880-09e3-11ea-8c20-3802ff6dae8d.png)
![image](https://user-images.githubusercontent.com/1288090/69031595-1c956380-09e3-11ea-9ca7-fceb09836528.png)
![image](https://user-images.githubusercontent.com/1288090/69031624-3040ca00-09e3-11ea-888d-67de62a7b3c4.png)

**Platform (please complete the following information):**
OS: Ubuntu on WSL2
Node: v12.13.0
NPM: 6.12.0
Yarn: -
Browsers: Chrome
iOS: - 
Android: - 
Electron: -

**Comment by rstoenescu** [comment]
Hi,

What version of "@quasar/app" are you using?

**Comment by oronbz** [comment]
> Hi,
> 
> What version of "@quasar/app" are you using?

`1.2.4`

**Comment by rstoenescu** [comment]
Please try again with "@quasar/app" v1.4.1.
This is a bug with the "open" npm package.

**Comment by oronbz** [comment]
@rstoenescu I've tried using v1.4.3 and the error still exists:
![image](https://user-images.githubusercontent.com/1288090/71562843-bfcfa300-2a8e-11ea-9c94-eb221dfd3156.png)

**Comment by hawkeye64** [comment]
@oronbz I am curious where the starting backslash is coming from...

The code that builds out the url does not have it (also indicated in the console output). Just the error dialog has it. Any insights?

Here's the code that builds the url:
```js
cfg.build.APP_URL = `http${cfg.devServer.https ? 's' : ''}://${host}:${cfg.devServer.port}${cfg.build.publicPath}${urlPath}`
```

**Comment by BBoysCluj** [comment]
Hi, 

I am facing the same issue when running quasar dev from WSL.

![image](https://user-images.githubusercontent.com/56302655/71917096-f80a6c00-3187-11ea-9fab-2e70a9969a40.png)
