### ISSUE TITLE
Browser with touch pinch-zoomed: Many q-components are loosing the parent-dedicated offset position

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5629]
Browser with touch pinch-zoomed: Many q-components are loosing the parent-dedicated offset position

Go onto quasar.dev and pinch / touch zoom the safari browser (only a little is enough)

Now many components, after triggering are getting a de-positionated issue:

Only tested some components, but the effect is always the same:

QPopupEdit
QTooltipp
QMenue
...

The on those triggered occuring Elements are positioned away or complete out
of view. So no usage is possible.

Tested on Ipad , Iphone, ios 12 and ios 13

**Comment by ibrainventures** [comment]
with the 1.5.4 i saw the new viewport-position-controlling. Great! Thank you.
I tested QMenu and Qtooltip on the Ipad and the position are now correct / perfect.
(the programmatic delay got some hickup / defect, but no show-stopper..)

As i have no Android Tablet or better Android Mobilephone where i cant test the viewport-
behaviour on those Browsers / os. May some other quasarian can test and feedback this?

**Comment by pdanpdan** [comment]
What do you mean with "the programmatic delay got some hickup / defect"? Can we have more details on what is wrong?

About Android, from our tests Chrome (even if it allows zooming/scaling) positions fixed elements in the right place by default, so the fixes are only for iOS.

**Comment by ibrainventures** [comment]
The custom-delay is no problem of quasar its more a "feature-handling" with the default ios 13 ipad safari browser.  

If you long-touch, the safari-browser try to force a User-Select on any near text-element. So it intereferes with the upsliding tooltip and prevents the tooltip / hides it (its random).

there are some webkit specific css rules:

```
  -webkit-user-select: none
  -webkit-tap-highlight-color: transparent
  -webkit-touch-callout: none
```

where this may can prevented, but this is not the right way for a common quasar app. 
So this is only for "edge-cases" and no error / failure of quasar.

Great btw. bad to hear that it was only a iOS (once again) issue ..

**Comment by ibrainventures** [comment]
hi @pdanpdan 
in the absolute happiness this morning i forget to test the offset / viewport issue with the ipad iPadOs 13 with the factory-default delivered : "render as desktop" option.
So i tested it now, and the offset issue comes again in this mode.
If i remember right, there was a detection routine for this use-mode, may this mode is actually ignored in the viewport detection / calculation routine?

**Comment by ibrainventures** [comment]
Detection difference between Ipad Ios 13+ with "render as desktop" and "normal mode (like iphone).

Ipad **render as Desktop:**

![grafik](https://user-images.githubusercontent.com/8803626/70191760-1947ea80-16fa-11ea-9f87-b93ddf1a7b3c.png)

----

Ipad **normal mode**

![grafik](https://user-images.githubusercontent.com/8803626/70191792-35e42280-16fa-11ea-82cf-38b727fecadd.png)

**Comment by ibrainventures** [comment]
the ios property get lost on the render desktop, may thats the culprit.
