### ISSUE TITLE
[BUG] q-select @input event fired 2 times

### ISSUE THREAD

**Issue by damosse31** [quasarframework/quasar#563]
### Software version

Quasar: 0.13.7
OS: Windows 10
Node: 7.9.0
NPM: 4.2.0
Browsers: tested on Chrome 58.0 and Firefox 53.0
Any other software related to your bug: 

### What did you get as the error?
@input event fired two times for q-select component

### What were you expecting?
event fire 1 time

### What steps did you take, to get the error?
Gif reproducing the bug : 
![q-select](https://cloud.githubusercontent.com/assets/16171524/25997461/6236b2be-371c-11e7-9af0-ecb31f9c041b.gif)

Code to reproduce : 
```
<template>
  <q-select type="list" 
    v-model="selectModel" 
    :options="selectOptions" 
    @input="selectInput">
  </q-select>
</template>

<script>
  export default {
    data () {
      return {
        selectModel: 1,
        selectOptions: [
          {
            label: 'Option 1',
            value: 1
          },
          {
            label: 'Option 2',
            value: 2
          }
        ]
      }
    },
    methods: {
      selectInput (value) {
        console.log(value)
      }
    }
  }
</script>
```

**Comment by rstoenescu** [comment]
Can you reproduce with latest v0.13.7?

**Comment by damosse31** [comment]
Sorry I confirm it's with v0.13. (I edited my post)

**Comment by rstoenescu** [comment]
Will fix it later this evening and release 0.13.8. Thanks for reporting!

**Comment by damosse31** [comment]
Multumesc mult ;)

**Comment by rstoenescu** [comment]
Available in v0.13.8 (just released it).

**Comment by damosse31** [comment]
I confirm problem solved since v0.13.8

Thanks !!

**Comment by rstoenescu** [comment]
Please help support Quasar (https://www.patreon.com/quasarframework) so I can spend even more time developing it. Every cent counts!

**Comment by lyquocnam** [comment]
i do same like this tutorial, but trigger `@input` not fire, @rstoenescu please help !

**Comment by rstoenescu** [comment]
@lyquocnam are you using 0.13.9?
