### ISSUE TITLE
q-menu context-menu on mobile opens onTouchEnd

### ISSUE THREAD

**Issue by gruppler** [quasarframework/quasar#5638]
**Describe the bug**
A q-menu with context-menu no longer opens on long-press, but now opens on touch end, even when scrolling. Experienced on Android 10 (Pixel 3) using Brave and Chrome.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/menu#Example--Context-Menu

**To Reproduce**
1. Tap on the image (without long-pressing)
2. See menu

**Expected behavior**
Menu should open only on long-press (right-click).

**Platform (please complete the following information):**
OS: Android 10
Node: v12.11.0
NPM: 6.13.0
Browsers: Brave, Chrome
Android: 10

**Comment by metalsadman** [comment]
Tested on android 9 chrome 78, got the same behavior as what the OP described.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix for this regression will be available in "quasar" v1.4.5.
