### ISSUE TITLE
[Request] Minor improvement to script.clean.js

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#564]
The current implementation of `script.clean.js` means that if you have a terminal _in_ the `/dist` folder, you need to change to another directory and back again after each build. Is there any harm in this instead?

    shell.rm('-rf', path.resolve(__dirname, '../dist/*'))

It means the actual `/dist` directory doesn't get deleted and recreated,

**Comment by rstoenescu** [comment]
Hi,

This is more of a thing for https://github.com/quasarframework/quasar-template-default rather than this repo.

Pushed commit to the default template. The complete solution is:
```js
shell.rm('-rf', path.resolve(__dirname, '../dist/*'))
shell.rm('-rf', path.resolve(__dirname, '../dist/.*'))
```

-Razvan
