### ISSUE TITLE
[Feature request] why not for q-tree Node component add 'parent()' function?

### ISSUE THREAD

**Issue by 625781186** [quasarframework/quasar#5642]
![image](https://user-images.githubusercontent.com/30521429/69126363-01aa1880-0ae3-11ea-972e-4f868dea916d.png)

Some time , I need get `Quality ingredients` node's all parent ,but `window.vm.$refs.qtree.getTickedNodes()` only get `Quality ingredients`.

**Comment by pdanpdan** [comment]
Closing this to track it in https://github.com/quasarframework/quasar/issues/6959
