### ISSUE TITLE
Button label align with link is always centered

### ISSUE THREAD

**Issue by asmaps** [quasarframework/quasar#5645]
**Describe the bug**
When using to "to" property or type="a" (aka the button is a link) with a q-btn the label is always centered no matter what's set in the align property.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/asw42/pen/XWWOgzd

**To Reproduce**
Create a button with a width wider than the label (eg. "full-width" or fixed width) and set align="left". As soon as you add type="a" the label will be centered and not aligned to the left anymore.

**Expected behavior**
The label should still be aligned left according to the align property

**Screenshots**
Check CodePen

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 8.16.0
NPM: 6.4.1
Yarn: 1.6.0
Browsers: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
iOS: not tested
Android: not tested
Electron: not tested
Quasar: 1.4.4
@quasar/app: 1.2.4

**Additional information**
I recently upgraded from 1.2 to 1.4 which seems to have introduced the issue.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.4.5.
