### ISSUE TITLE
QTable sorting with virtual scroll is broken since 1.4.4

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#5648]
**Describe the bug**
I don't know if this is related with the removal of __index, but sorting the rows using pagination no longer works since 1.4.4. I tested with all versions before, including 1.4.3, and everything works fine. 

In my code, it simply does not do anything, but there are no errors in the console. In this [example](https://quasar.dev/vue-components/table#Example--Virtual-scroll-with-sticky-header) from the docs, it outputs a bunch of errors in the console.

**Codepen/jsFiddle/Codesandbox (required)**

Forked from the above example:
https://codepen.io/philfontaine/pen/MWWLVdy?&editable=true&editors=111

**To Reproduce**
1. Click on one of the headers to sort the rows, e.g. Calories

**Expected behavior**
It should work as before

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by philfontaine** [comment]
After investigating, the errors in the example are due to the Object.Freeze, but it works fine without it, so it does not look like this is the problem. I will continue looking into it on my end.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix for this regression will be available tomorrow through "quasar" v1.4.5.

**Comment by philfontaine** [comment]
Curious to see if this will fix my issue. After debugging with vue dev tools, everything works fine when inspecting components (the data is sorted correctly) but the DOM is not refreshed until I scroll enough so that the virtual scroll kicks in and refreshes the data. Does that ring any bell to you? I'm afraid that this is a different issue, and I can't seem to reproduce it in the codepen.
