### ISSUE TITLE
[Improvements] Header tooltip on q-data-table

### ISSUE THREAD

**Issue by damosse31** [quasarframework/quasar#565]
Hi,

1. since latest release (v0.13.8) every hovering a column header in q-data-table show a tooltip. I think it could be nice if the tooltip is desactivated by default and we can choose if we want to show the tooltip or not.

2. check if column header is not empty to avoid showing empty tooltip (screenshot below) : 
![screenshot_3](https://cloud.githubusercontent.com/assets/16171524/26023992/9795dc30-37c8-11e7-91ab-f10663a508a2.png)

**Comment by rstoenescu** [comment]
Available in v0.13.9 (just released it). Thanks for filing this.

**Comment by damosse31** [comment]
Checked and released in 30 mins !

Thanks 👍

**Comment by rstoenescu** [comment]
Actually I saw this 4 minutes ago, otherwise it would have been even faster :)

**Comment by damosse31** [comment]
I checked from my post time but yeah... you're fast 👍
