### ISSUE TITLE
[QSelect] props 'option-value' doesn't use the mentioned property

### ISSUE THREAD

**Issue by jippy89** [quasarframework/quasar#5652]
**Describe the bug**
`option-value` props seem to be not doing its job. I have tried it on JSFiddle and on my own desktop (same version).

**Codepen/jsFiddle/Codesandbox (required)**
You can check it on this [jsfiddle](https://jsfiddle.net/du7zcaj2/)

**To Reproduce**
1. Go to the jsfiddle link (You can directly copy-paste it)
2. Select an option
3. See the problem.

**Expected behavior**
It's supposed to emit the property of the object. In the example, then instead of emitting the whole object, it supposed to emit `id` prop.

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.11.0
NPM: 6.11.3
Browsers: Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Additional context**
I do have tried using 
```
:option-value=(thing) => {
  console.log('doing stuff')
  return thing.id
}
```
And it seems to be spamming something, however it changes nothing. Try it out in the JSFiddle. Of course, there's an alternative to this, but I just want to let you guys know.

Thank you! You guys have done a great job with Quasar!

**Comment by pdanpdan** [comment]
It's not supposed to emit the value. Check `emit-value` and `map-optiond`

**Comment by rstoenescu** [comment]
Hi,

`option-value` tells where to look in each option Object to get its value. It has nothing to do with emitting the property of the object, unless you also use `emit-value`.

Please join our Discord for getting more info, if this is still unclear to you.
Thanks.
