### ISSUE TITLE
`framework: { all: auto }` doesn't merge current component array from AE's

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#5654]
**Describe the bug**
If an AE is using `conf.framework.components.push('QMenu')` and the consuming quasar app is using `framework: { all: auto }` then the QMenu won't be included in the auto import.

**Codepen/jsFiddle/Codesandbox (required)**
Not possible in this instance.

**Expected behavior**
`components: []` to be merged with auto result.

**Additional context**
I understand we're moving to the new ui kit which will resolve this issue but this will make the change backwards compatible for AE's not moved over.

**Comment by rstoenescu** [comment]
This is irrelevant. If an AE uses a Quasar component then it should directly import it and declare it in the SFC script > export default > components

**Comment by hawkeye64** [comment]
Just a follow up question @rstoenescu 
How would a Quasar Plugin be handled from an AE in order to be initialized properly?

**Comment by rstoenescu** [comment]
`conf.framework.plugins.push()`. Those are handled differently and should work.

**Comment by hawkeye64** [comment]
It should, because Plugins are not handled by the auto import. Thanks for clearing that up @rstoenescu  :+1:
