### ISSUE TITLE
IE 11: containerized QLayout

### ISSUE THREAD

**Issue by poradz** [quasarframework/quasar#5655]
**Describe the bug**
Containerized QLayout on ie doesn't render correctly. I can see this in my project, it is quite custom implementation of quasar, so I thought this is my fault, but you can observe this behaviour even in your documentation (links below). I guess the problem is your flex implementation, which could work different on ie, see https://caniuse.com/#feat=flexbox. 

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/layout/gallery/whatsapp
https://quasar.dev/vue-components/dialog#Example--With-containerized-QLayout

**To Reproduce**
Open links above.

**Expected behavior**
Containerized QLayout should behave on ie correctly.

**Screenshots**
Whatsapp
![image](https://user-images.githubusercontent.com/31520119/69228654-3de18580-0b84-11ea-85ac-acb51b564e43.png)
![image](https://user-images.githubusercontent.com/31520119/69228747-6c5f6080-0b84-11ea-8c8e-eb514245bd13.png)

**Platform (please complete the following information):**
OS: Windows 10

**Comment by pdanpdan** [comment]
First red box here :)
https://quasar.dev/layout/layout#Containerized-QLayout

Sorry, nothing that can be done about it.

**Comment by poradz** [comment]
Thanks for quick answer, the red box is it. :)

Are you sure that there nothing can be done? Could you tell me, what is the problem? Maybe I will try to solve it by myself :)

**Comment by rstoenescu** [comment]
You could try, but the fix would be making fixed position in IE11 actually work like on w3c specs :)

**Comment by poradz** [comment]
Ok, I'll consider this. Thanks for your time @rstoenescu :)
