### ISSUE TITLE
QColor/QTime props

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5658]
**Is your feature request related to a problem? Please describe.**
I noticed that QTime and QColor might need additional props to handle dark/light app mode better. This is a multi-request. Pick up what you like.

**Describe the solution you'd like**
 -  QColor: Get (partly) style props from QTime: `flat`, `square`, `bordered (?)`
 - QTime/QColor: New prop to define background color: `background` or `dark-background` Issue: See screenshot

**Describe alternatives you've considered**
-

**Additional context**
When QTime dark matches your dark background used as a Popup.
![dark-backgruond](https://user-images.githubusercontent.com/15967679/69262088-19f16480-0bc3-11ea-902b-cb214f5c7abd.PNG)

**Comment by rstoenescu** [comment]
Hi,

Added QColor into the group of components (QTime, QCard, QStepper, ...) with bordered/flat/square props.
Will be available in "quasar" v1.5.2.

Regarding the dark color, you can either change the `$dark` Sass/Stylus variable, or override its CSS classes (text-dark, bg-dark) or directly override QTime's CSS.
