### ISSUE TITLE
Theme Plugin

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5661]
**Describe the solution you'd like**
Inspired by the Dark plugin. Provide base support for multiple themes ( `mat`, `ios`, `win`). Quasar components should enable/disable props based on the current selected theme. 

Key points
 - Can be switched during runtime (like Dark)
 - Allow global css per theme (Dark: dark body background/light body background)
 - Component props can still be overwritten on demand (Like now with dark prop)

This will probably never be a full theme solution, but it will push you faster into the desired direction. For example if you want to create an ios like interface, you need to apply all the props that are required by hand again and again.

Following the idea of multi platform and the catch-all-in idea of Quasar this fits perfectly

**Please share your thoughts**

**Comment by pdanpdan** [comment]
Just create an object with your desired properties and apply it on all components with v-bind or object assign on props.

**Comment by brindosch** [comment]
Thank you for your stance on this. It was never a matter of doing it by hand :+1:
