### ISSUE TITLE
Odd QImg corners with width == height == 2 * border-radius

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#5662]
**Describe the bug**
When a q-img element has the width and height equal and the border-radius set to half of these (i.e. to make a circle), in Chrome 78.0.3904.97 the bottom left corner of the image shows briefly and in Safari 13.0.1 all for corners show briefly before the image is displayed as a circle.  This is on a Mac, in case it makes any difference.

(It works as expected in Firefox 70.0.1)

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/RohanTalip/pen/yLLwXvd

**To Reproduce**
1. Go to https://codepen.io/RohanTalip/pen/yLLwXvd in Chrome or Safari.
2. Click on the IMAGE tab and observe the weird behaviour in the corner(s).
3. Click on the NO IMAGE tab.
4. Click on the IMAGE tab and observe the weird behaviour in the corner(s).
5. Click on the CHANGE IMAGE button and observe the weird behaviour in the corner(s) : in Chrome, the bottom left corner appears twice, once briefly before the  image is changed, and again after the image has changed; in Safari all 4 corners appear while the image is being changed.
5. Click on the NO IMAGE tab.
6. Go to step 2.

**Expected behavior**

The image in the q-img element should have the border radius applied without any weird effects in the corners.

**Screenshots / videos**

Strangely, when I recorded this behaviour using the Nimbus extension for Chrome, it was the top left corner that was recorded as acting weirdly.  (In reality it looked even more glitchy when I was using Nimbus; what was recorded was not quite as glitchy but still bad.)

Switching tabs:
https://youtu.be/rv37HumYfnE

Changing the image:
https://youtu.be/0cclbo5XP40

**Platform (please complete the following information):**
OS: Mac
Node:
NPM:
Yarn:
Browsers: Chrome, Safari
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.7.0
