### ISSUE TITLE
q-drawer aboveStyle should be optional

### ISSUE THREAD

**Issue by evazc** [quasarframework/quasar#5663]
Sometimes we need the aboveStyle always be there, not to be determined by breakpoint or behavior.

**Describe the solution you'd like**
Add a prop so we can configure if the aboveStyle be there.

**Comment by rstoenescu** [comment]
Hi,

Then either set `:breakpoint="0"` or `behavior="desktop"`. This disables the "mobile" mode.

**Comment by evazc** [comment]
@rstoenescu 

Thanks for your response!

But I need both of the "mobile" mode and aboveStyle, 
that's why I said we need the aboveStyle always be there.

I think the existence of the aboveStyle should be able to be configured.

That's more flexible.

**Comment by evazc** [comment]
As I need both of the "mobile" mode and aboveStyle,

I have to set the `to` and `bottom` of the `.q-drawer` manually.

**Comment by rstoenescu** [comment]
You can't have both. It doesn't makes any sense... The "aboveStyle" is only specific to the drawer when it's in desktop mode. What am I missing?

**Comment by evazc** [comment]
Alright, maybe it looks weird for having both.

But that's what our UI needs 🙁.
