### ISSUE TITLE
QChip removable icon not displaying

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#5666]
**Describe the bug**
If you use v-text or v-html instead of using {{ }} in the QChip, the removable button doesn't appear.

**Codepen/jsFiddle/Codesandbox (required)**
(1st example with v-text, 2nd example with v-html, 3rd example is the working way)
https://codepen.io/medhyena/pen/wvvOQQY

**To Reproduce**
1. Check the codepen.io
2. Implement QChip with either v-text or v-html and removable
3. ???

**Expected behavior**
It should display the removable button/icon whether or not there is content in the QChip

**Comment by rstoenescu** [comment]
Hi,

This is to be expected. By using v-text or v-html you are essentially overwriting the component's own DOM tree.

What you're looking for is actually:
```html
<q-chip ....>
  <span v-html="htmlContent" />
</q-chip>
```
