### ISSUE TITLE
Inconsistent Button events

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#5667]
**Describe the bug**
There are 3 types of Quasar buttons: 1) QBtn, 2) QBtnGroup and 3) QBtnDropdown
When clicking on the button all three will give you an event with target as BUTTON. However, clicking on the text of QBtnGroup or QBtnDropdown will give you and event with target DIV. And, if there is an associated icon, on all three, the event will give you target of I.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Hawkeye64/pen/mddovMJ?&editable=true&editors=101
https://codepen.io/Hawkeye64/pen/OJJqdjX?&editable=true&editors=101
https://codepen.io/Hawkeye64/pen/gOOEqPb?&editable=true&editors=101

**To Reproduce**
1. Go to the codepens
2. Click on each button to get the nodeName to be displayed for the event->target
3. See different events associated with the same button

**Expected behavior**
The only event that should occur is the one with event->target->nodeName = BUTTON

With QBtn, when clicking on the text, you will always get BUTTON. The other 2 should be consistent with this.
As for the "I" (as nodeName) when clicking on an icon, I think a button should always be BUTTON, regardless of other content in the button.

**Comment by rstoenescu** [comment]
This fix will be available in "quasar" v1.5.0
