### ISSUE TITLE
[Request] Toast appear infinity

### ISSUE THREAD

**Issue by nak1114** [quasarframework/quasar#567]
An error occurs and the app wants to recognize the error contents to the user, but the app does not want to interrupt the user's operation.
In this case use Toast instead of Modal. And I don't want Toast to disappear automatically.
I propose to change so that the above is possible by setting the timeout option of Toast to 0.

example:
```
fetch('http://example.com/something.json')
 .then(responseSomething)
 .catch(res => Toast.create.negative({html: res.message, timeout: 0}))
```

I created this patch, but I don't have any iOS device, so I can not test it.
https://github.com/nak1114/quasar

**Comment by rstoenescu** [comment]
Alerts will be available in v0.14. These, as opposed to Toasts, must be dismissed by the user.
