### ISSUE TITLE
QTabPanels keep-alive doesn't works for panels with iframes

### ISSUE THREAD

**Issue by dexif** [quasarframework/quasar#5674]
**Describe the bug**
keep-alive does not save iframe state

**Codepen**
https://codepen.io/dexif/pen/eYYoBWV

**To Reproduce**
1. Go to https://codepen.io/dexif/pen/eYYoBWV
2. Click on Android2
3. Click on Android1
4. You can see iframe reloads every time

**Expected Behavior**
At 0.17 it works fine because dom elements are not deleted

**Comment by pdanpdan** [comment]
It is not expected to keep alive iframes, sorry. What you can do is to get a ref to the iframe and save and restore it yourself.

**Comment by rstoenescu** [comment]
Hi,

This is due to how browsers (& Vue) works. We keep the components "alive" in memory, but when we render their content again, browsers re-load the iframes.. No way around it, except if you create your own tab panels component which simply sets opacity to 0 for tabs that should not be visible.

**Comment by dexif** [comment]
I know how it works.  I just described the problem, the functionality was present on version 0.17 and stopped working on 1.x.  If you think that now tabs work more correctly - well, I will write my own component.  This is not a big problem for me.  But, in my opinion, you are killing some of the functionality of your components.

**Comment by dexif** [comment]
For now, we should write our own datetime input wrapper component, the panels component, the autocomplete component, and select wrapper component, because they do not work the way it worked in the past.

Just a few more of components and it turns out that with the switch to a new version - everyone will write their own framework. :)

You have done a really great job.  This is really cool.  But at the same time, part of the functionality stopped working and this is very disappointing.

**Comment by rstoenescu** [comment]
I'm sorry to say this, but what's disappointing for me reading your lines above is that you're looking at an older version and disregarding the ton of improvements and new features in v1 while render speed is 10x and customization is way easier, just because of a pretty custom use case that doesn't fit your profile. A framework is about balance and about the needs of the majority. And the majority is ecstatic about what they can now do in v1 ("I didn't know it could be so much better until I tried v1"). But I digress. We can't satisfy 100% of the people. Would be interested in hearing why you wrote wrappers around the datetime input and especially around autocomplete (which through QSelect is capable of fitting all possible use-cases). Can you write me an email describing this pls, if your time allows it?

**Comment by dexif** [comment]
@rstoenescu 

Sorry for dissapointing you. I like your changes in new version. It's very cool. Really fast and smooth framework. But switching to new version is very painful for us. We know firsthand how difficult it is to satisfy all users. And i just describe my problems with migration from 0.17. 

In my case for example we use tabs for youtube videos. And if user plays a video, then stops it, then switches tabs - he loses his video position. And new iframe says to the browser that it wants to load video (that's increase in traffic usage).

New qselect with autocomplete now works not like qinput with qautocoplete. It doesn't allow user to send inputted (custom, not from list) value without pushing "enter". If qselect losts focus - that loses inputted data.
To fix that i will use a hack with adding inputted value on focus lost. But after that i can't edit inputted value as just a string. Then i use focus event to set current value to inputValue and clear model to hide duplicate value.

        @blur="$refs.aaaa.add($refs.aaaa.inputValue)"
        @focus="$refs.aaaa.inputValue = model || '', model = ''"

But then i lose functionality to choose value from the list :( I know i can find the way to bring it to work. But it looks like a crutch. 
https://codepen.io/dexif/pen/Pooveay

You removed lovely qdatetimeinput and split it to QDate and QTime. Now we created our own component based on qinput with popup with qdate + qtime. Also we can't put timestamp directly to qinput with format. Now we should use wrapper to convert timestamp values to datetime.

It's just our cases and i do not require you to fix that. I'm just sharing my pain. I repeat, I am very inspired by the new version. Great work is done. And in general, everything is very cool!
