### ISSUE TITLE
Make disabled state more contrast by default

### ISSUE THREAD

**Issue by Maksio** [quasarframework/quasar#5681]
In my opinion disabled components are not contrasty enough, maybe set color to #e0?

`.disabled, [disabled] 
   opacity 0.6
   color #e0e0e0`

They looks more cute with high contrast I think.

![image](https://user-images.githubusercontent.com/5869118/69475155-ceb19e80-0dda-11ea-8ae4-7237a067d149.png)

**Comment by pdanpdan** [comment]
Set that rule in your css. It should work nicely.
