### ISSUE TITLE
webpack `output.path` is not set according to quasar `distDir` in dev mode

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#5682]
Looking at https://github.com/quasarframework/quasar/blob/dev/app/lib/webpack/create-chain.js#L37

```js
  if (cfg.ctx.prod || cfg.ctx.mode.ssr) {
    chain.output
      .path(
        cfg.ctx.mode.ssr
          ? path.join(cfg.build.distDir, 'www')
          : cfg.build.distDir
      )
      .publicPath(cfg.build.publicPath)
      .filename(`js/[name]${fileHash}.js`)
      .chunkFilename(`js/[name]${chunkHash}.js`)
  }
```

Reveals that quasar.conf.js settings `distDir` and `publicPath` are ignored in `dev` mode, I wonder why is that?

When [`devServer.writeToDisk`](https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-) is used, the generated files will be in an unexpected location (`./dist` instead of `distDir`) and the links inside them will be incorrect (due to ignored `publicPath`)

I am using `chainWebpack` in `quasar.conf.js` to correct this.

If this is done in purpose, the docs should mention that distDir does not affect dev mode (and possibly the reasoning behind it)

**Comment by rstoenescu** [comment]
Hi,

Indeed distDir is ignored on dev, because everything is kept in memory.
If you configure writeToDisk then obviously you should change the distDir behavior too. But this is your customization and it makes no sense to change distDir behavior for everybody...
