### ISSUE TITLE
q-drawer fires x-hundred mouseout/mouseover/moseleave/mouseenter .. events on little mousemove

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5684]
**Describe the bug**
I have two normal qdrawer with some text-divs, images etc, on both-sides.

At any minimal mousemovement between the elements / above the qdrawer elements there are many events fired. My usage is with desktop-mode / no breakpoint, and no mouseover-controlled-elements.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/8803626/69501423-103e6880-0f05-11ea-8b66-5d4afd294ca9.png)

Is there a easy way to stop / remove those listeners?

Firefox Browser
Windows

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.5.0

**Comment by ibrainventures** [comment]
thank you and @pdanpdan for looking and solving this issue very much 🥇
