### ISSUE TITLE
QRouteTab: text-weight-* classes ignored in active-class property 

### ISSUE THREAD

**Issue by nahuel** [quasarframework/quasar#5685]
`text-weight-*` classes seems to be ignored in the `QRouteTab` `active-class` property, but for example `bg-blue` works ok. Surprisingly, `text-italic` works ok.

```html
<q-tabs>
  <q-route-tab to="/info" label="Info" active-class="text-weight-bolder bg-blue"/>
<q-tabs>
```

**Comment by pdanpdan** [comment]
Can you please make a codepen showing the problem?

**Comment by pdanpdan** [comment]
Closing this one because lack of feedback and reproducible case.
Please reopen if you have more details.
