### ISSUE TITLE
When a dialog is shown, the underlying page will scroll to start (on Android browers)

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#5686]
On Andriod phone, use Chrome or firefox, scroll a page, then open a dialog on this page, the page will scroll to start.

**Comment by pdanpdan** [comment]
Can you please make a codepen showing the problem?

**Comment by bigradish** [comment]
Hi @pdanpdan ,

I made a codepen, but this issue can not be seen there.
Have you met any issues like this before?
If not, could you tell some possible reasons?
Thank you very much.

**Comment by pdanpdan** [comment]
I need the code to see what's happening, because in my tests it doesn't happen.

**Comment by pdanpdan** [comment]
Closing this one because lack of feedback and reproducible case.
Please reopen if you have more details.
