### ISSUE TITLE
Electron crash on reload

### ISSUE THREAD

**Issue by aldozumaran** [quasarframework/quasar#5687]
After compiling the app if editing the files (like electron-main.js for example) the app crashes.
Tried with fresh installation with different configurations and PCs. This didn't happen on linux or mac OS. 

**To Reproduce**
1. quasar create test-electron
2. quasar dev -m electron
3. edit anything in electron-main.js

**Expected behavior**
The app should reload

**Screenshots**
![Screenshot from 2019-11-25 10-26-47](https://user-images.githubusercontent.com/3183704/69528228-23395300-0f6e-11ea-9db0-d3773346bb5a.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: 12.13.0  
NPM: 6.13.1
Yarn: 1.19.1
Browsers:
iOS:
Android:
Electron: 5.0.12 (tested with vers.4 aswell)

**Comment by mahwd** [comment]
i have this issue too

**Comment by pdanpdan** [comment]
Follow here: https://github.com/quasarframework/quasar/issues/5949
