### ISSUE TITLE
Data Table not rendered correctly in IE 11

### ISSUE THREAD

**Issue by blaluc** [quasarframework/quasar#569]
The Data Table in the Showcase site is not correctly rendered in IE 11 (see doubled 'Date' and 'Source'  columns in the attached image).
![image](https://cloud.githubusercontent.com/assets/4599417/26033123/9f2a6f4c-38a4-11e7-936f-ab354486ffe7.png)

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by mstaack** [comment]
have you included http://quasar-framework.org/guide/app-troubleshoot-and-tips.html#Adding-support-for-IE11?

**Comment by blaluc** [comment]
It is a problem on the official web site, http://quasar-framework.org/quasar-play/android/index.html#/showcase/web-components/data-table
I suppose that it has been built with all the needed polyfills, as no errors are shown in the IE 11 console.

**Comment by rstoenescu** [comment]
Not ignoring this, but currently no time for it. Help is appreciated.
A revamp of DataTable will be first thing after v0.14, with lots of new features including this one and server-side management.

**Comment by daniel-shuy** [comment]
Just to chip in, I noticed that only Sticky Columns are not properly rendered.

A workaround that I'm using, is to simply disable sticky columns if the browser is IE:
```js
import {Platform} from 'quasar'

data () {
    return {
        config: {
            // ...
            leftStickyColumns: Platform.is.ie ? 0 : 1,
            rightStickyColumns: Platform.is.ie ? 0 : 2
        }
    }
}
```

@rstoenescu I'm really looking forward to the revamped Data Table!
