### ISSUE TITLE
[Request] Allow QSlider to work in "reverse"

### ISSUE THREAD

**Issue by drank** [quasarframework/quasar#5691]
Could you extend the QSlider component so that a slider can start from the right?

I must point out that this is NOT an RTL-related request. I am aware of the RTL support in Quasar but the use case that I have does not involve RTL at all. An eventual RTL application could similarly require an LTR slider (which they already have available) without needing to switch to full LTR support.

**Use case (heavily simplified)**:
A have an analytics app and a data filter component. In that filter I want to express **the threshold value** of "greater than" and "less than" conditions with sliders. I would use a regular slider for the "less than" condition and the "reverse" slider for the "greater than" condition.

Here is an example of a "greater than" condition taken from a Tableau filter:
![image](https://user-images.githubusercontent.com/1393766/69546249-116ea480-0f9c-11ea-94ce-9670ea80e158.png).

I see that a similar request was already posted (https://github.com/quasarframework/quasar/issues/2099) and was scheduled for v1.0 but I couldn't manage to find this in v1.4.5.

**Comment by rstoenescu** [comment]
Hi,

This will be available in "quasar" v1.5.0.

**Comment by drank** [comment]
Thank you very much for implementing this! I continue to be amazed every day by the Quasar framework and by the team behind it!
