### ISSUE TITLE
Qtable row click __index problem

### ISSUE THREAD

**Issue by ahmetorhans** [quasarframework/quasar#5694]
**Qtable row click __index problem**
__index does not appear when I call the row-click event(version : 1.4.4 and 1.4.5).

version  1.4.3 is working properly

**Comment by rstoenescu** [comment]
Hi,

It has been removed due to several reasons, as per the release notes: https://github.com/quasarframework/quasar/releases/tag/quasar-v1.4.4 

However, the index can be computed like below:
```js
const index = tableData.indexOf(row)
```
