### ISSUE TITLE
Ehance uploader with a model

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#5696]
The current QUploader is not very useful because Its targeted to handle multiple uploads (because it looks like a list), but it hasn't a model behind.
Most applications would find this component useless, because the common use case cannot be easily fulfilled. The common use case, in my opinion, is: I have an entity that can have multiple attachments. what happens when I edit that entity? I cannot force to have a initial list of already uploaded documents. The component is just to add new ones. And that makes the experience bad, because the user will have two list of documents: the existing ones, and the new ones, and also for the developer its a lot of work.

**Describe the solution you'd like**
I would let the q-uploader have a `v-model` consisting in a List of "File like" objects. I say "File Like" because Its not easy to create instances of real File objects to inject as an initial. I think that just the name, and URL are needed, and maybe an optional size.

**Describe alternatives you've considered**
I used the list slot inside <q-uploader> to inject my own files for an initial render... instead of iterating with the scope.file property, I iterate over two arrays.

**Comment by pdanpdan** [comment]
It's not that it's not easy to create "File Like" objects, it is impossible - it's one of the main security concerns of the browser.
The model is useless except when you create some file content in the browser and want to display it there.
