### ISSUE TITLE
Virtual scroll in tables

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#5698]
**Describe the bug**
The table scrolls down the header height when there is 'virtual-scroll' enabled. That is visible in Documentation example as well.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/table

**To Reproduce**
1. Go to https://quasar.dev/vue-components/table
2. The table will be scrolled the but in docs example

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.0.

**Comment by pikil** [comment]
Thank you Razvan!
