### ISSUE TITLE
Search and control buttons do not apply to 'scroll-area'

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#5699]
**Describe the bug**
The browser does not scroll 'scroll-area' element to top/bottom when using navigational buttons (Ctrl+Up/Ctrl+Down) when focused, also the search is not scrolling to found element as well when using standard browser's Ctrl+F.

**jsFiddle**
https://jsfiddle.net/ybj9wu5m/

**To Reproduce**
1. Go to https://jsfiddle.net/ybj9wu5m/
2. Focus on 'Render result' block
2a. Hit Ctrl+Up
2b. Hit Ctrl+Down
2c. Hit Ctrl+F and try to search this sentence 'Etiam porta'
3. 'Render result' block does not scroll to any direction

**Expected behavior**
The default browser's scrolling behaviour should take place

**Platform:**
OS: Windows, MacOS
Browsers: Chrome, Firefox

**Comment by pdanpdan** [comment]
Not really a bug as this is not advertised as working, but definitely a good feature.

**Comment by pikil** [comment]
Hi pdanpdan,
Yes, agree - that has nothing to do with incorrect coding, sorry. Should be a feature request for sure :)
Thanks!

**Comment by rstoenescu** [comment]
Hi,

Enhancement will be available in "quasar" v1.5.0.

**Comment by pikil** [comment]
Thank you Razvan!
