### ISSUE TITLE
QSelect options are not updated

### ISSUE THREAD

**Issue by luciazaliberova** [quasarframework/quasar#5707]
**Describe the bug**
I have QSelect control initially displayed with no options. There is no-option slot with refresh button. When refresh button is clicked, options are added to the array, but they are not visible.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luciazaliberova/pen/PoorvbX

**To Reproduce**
1. Open dropdown
2. Click Refresh button
3. no options are dispalyed

**Expected behavior**
Available options should be visible when refresh is clicked.

This is expected after refresh:
![ExpectedRefreshClicked](https://user-images.githubusercontent.com/9720119/69718138-dee4b900-110d-11ea-8a19-f4f1c1f27161.png)

This is actual after refresh:
![RefreshClicked](https://user-images.githubusercontent.com/9720119/69718156-ed32d500-110d-11ea-9712-d72ebd11b6fc.png)

**Platform (please complete the following information):**
Browsers: Chrome

**Comment by lucasfernog** [comment]
The problem is that the QSelect is not rerendering the menu on options change. When you close the menu and opens it again, it shows the options.

**Comment by luciazaliberova** [comment]
Is there some workaround, how to display menu in this case (immediately when refresh is clicked) ?

**Comment by pdanpdan** [comment]
You must put a ref on the QSelect and call the internal method `__updateMenu(true)`

https://codepen.io/pdanpdan/pen/dyyBBxo

**Comment by luciazaliberova** [comment]
Great thanks !

> You must put a ref on the QSelect and call the internal method `__updateMenu(true)`
> 
> https://codepen.io/pdanpdan/pen/dyyBBxo

Great, thanks !!

**Comment by lucasfernog** [comment]
Shouldn't that method become public instead of `__`? @pdanpdan

**Comment by hassam-saeed** [comment]
@pdanpdan The link is not working. Can you please check it again?

**Comment by MilosPaunovic** [comment]
> @pdanpdan The link is not working. Can you please check it again?

https://codepen.io/milospaunovic/pen/eYrQweg

**Comment by yashar-vasegh** [comment]
How about 
this.$refs.YourSelect.refresh()

works better for me

**Comment by lastboy** [comment]
It is an old post but I just solved my case that is similar.
Create a component to display your items that has a <slot - that will force the options to get the changes
