### ISSUE TITLE
QUploader component - Quasar v1.5.0 - Button that displays the Open File dialog box so a file can be added does nothing.

### ISSUE THREAD

**Issue by gmalignon** [quasarframework/quasar#5712]
**Describe the bug**
On the QUploader component, button that displays the browser file open dialog so a file can be added does nothing.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/azazellov/pen/BaaXzXR?&editable=true&editors=101#anon-signup

**To Reproduce**
Just click on the Add (+) button, nothing happens.

**Expected behavior**
Clicking on the Add (+) button is supposed to bring up file open dialog box.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10 Version 2004, build 19033.1
Node: latest
NPM: latest
Yarn: latest
Browsers:
Chrome 80 or 78 x64
iOS:
Android:
Electron:

**Additional context**

I have both the previous version and the latest version of Quasar (v1.5.0) and the previous version works fine.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix is available in "quasar" v1.5.1.
