### ISSUE TITLE
QColor - color palette not emitting anything other than #ffcccc

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#5715]
The bug is also present on the Quasar docs:
https://quasar.dev/vue-components/color-picker

Selecting any color from the color palette is always emitting the value #ffcccc. 
The spectrum and tune views work normally.

![image](https://user-images.githubusercontent.com/13761766/69774093-0066a300-11e9-11ea-842d-99335bf33381.png)

This was happening to me on 1.5.0

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting!
Fix will be available in "quasar" v1.5.1 shortly.
