### ISSUE TITLE
Why not design it to set the input box size

### ISSUE THREAD

**Issue by swirldawn** [quasarframework/quasar#5718]
**Is your feature request related to a problem? Please describe.**
 为什么不设计成可设置输入框大小 
我计划使用quasar来开发admin系统 但是input大部分都很大 有点占网页空间

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pdanpdan** [comment]
Hello. Please use english :)

> Why not design it to set the input box size
I plan to use quasar to develop the admin system, but most of the input is very large and it takes up a bit of web space

You can use `dense` prop and if that is not enough you can adjust it to your liking, like here:

https://codepen.io/pdanpdan/pen/OJJKOPL
