### ISSUE TITLE
[feature request]Platform detection for Electron Main process

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5722]
**Describe the bug**
Platform  plugin should provide information for Electron Main process from node os module.

**Codepen/jsFiddle/Codesandbox (required)**
In Electron Main process

**To Reproduce**
1. import { Platform } from 'quasar'
2. console.log(Platform.is)
3. undefined printed

**Platform (please complete the following information):**
OS:Windows10
Node:10.16.3
NPM:6.9.0
Yarn:1.19.1
Browsers:-
iOS:-
Android:-
Electron:Yes

**Comment by rstoenescu** [comment]
Hi,

The main process does not have the same access points as the UI (you cannot run UI code on the nodejs process).
