### ISSUE TITLE
QBtn with the .prevent and .stop modifiers is not captured when it is in another QBtn

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#5723]
**Describe the bug**
QBtn with the `.prevent` and `.stop` modifiers is not captured when it is in another QBtn.

**Codepen/jsFiddle/Codesandbox (required)**
[codepen](https://codepen.io/heartbeatlv-the-bashful/pen/abbeEpe)

**To Reproduce**
1. Click on second button
2. See error

**Expected behavior**
Using `.prevent` and `.stop` the click on the second button should be captured, but the first one is captured instead.

**Comment by pdanpdan** [comment]
Add a ` class="all-pointer-events"` on the button inside button.

**Comment by rstoenescu** [comment]
Just upgrade to Quasar v1.5.1.
It will work. No need to add any class to it.
