### ISSUE TITLE
Improve .gitignore for Capacitor Mode

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#5728]
**The problem**
The Capacitor mode doesn't have a .gitignore configuration, [unlike Cordova mode](https://github.com/quasarframework/quasar-starter-kit/blob/63dccab47559911d3d22bed1ac4b3d58d33ad579/template/.gitignore#L9-L13). This causes some version control pollution.

**The solution**
Updating the [.gitignore template in quasar-starter-kit]. I think at least `src-capacitor/www` should be ignored, because it is getting changed every time `quasar build -m capacitor ...` is called.

**Alternative**
The users can add this ignores to their codebase manually, but this could make it easier and I see no harm implementing this since lots of useful ignores for other things are already added. But there are also some potential barriers to implement it manually, see additional context section.

**Additional Context**
Capacitor checks for `www` folder and `www/index.html` before building and adding a platform. Quasar adds the platforms on-demand before building. Capacitor throws an error when building for a platform for the first time(because of the platform adding process). This creates a potential barrier, where the user pulled the repo(with the `www` folder ignored) and wants to add a new platform.

**Solving Steps**
- https://github.com/quasarframework/quasar/blob/a9545e19c9614e91c952e19610d875d666ba5819/app/lib/mode/mode-capacitor.js#L110-L114 should be updated with `ensureFileSync`, like https://github.com/quasarframework/quasar/blob/e8427b5f2320416e2391c2bed74867988f231a68/app/lib/mode/mode-cordova.js#L95-L101
- [.gitignore template in quasar-starter-kit] should be updated

More entry ideas for the .gitignore file are welcome.

_I opened this issue in this repo because it is not just related with `quasar-starter-kit` but also `@quasar/app`_

[.gitignore template in quasar-starter-kit]: https://github.com/quasarframework/quasar-starter-kit/blob/63dccab47559911d3d22bed1ac4b3d58d33ad579/template/.gitignore

**Comment by rstoenescu** [comment]
Merged, so closing.
