### ISSUE TITLE
Cordova router-link not work !

### ISSUE THREAD

**Issue by lyquocnam** [quasarframework/quasar#573]
Hi author, i tried use this code to go other route:
```html
<a v-link="{ path: '/hello' }">Hello</a>
<router-link :to="{ name: 'hello' }">Hello</router-link>
```
my terminal command:
```
quasar build
cd cordova
cordova run
```
but when run with cordova, it not happen. (it work fine on `quesar dev`)

![image](https://cloud.githubusercontent.com/assets/8347826/26085282/4c9f359a-3a0d-11e7-8b10-e66af5423d16.png)
(i try to click `hello` to go Hello component)

my project:
https://github.com/lyquocnam/quasar-test

**Comment by lyquocnam** [comment]
this debug detail as tutorial:
![report quasar bug](https://cloud.githubusercontent.com/assets/8347826/26085864/5a56cdde-3a11-11e7-8cdc-8626acf13f9e.gif)

**Comment by rstoenescu** [comment]
Hi,

1. I ran your project but could not reproduce. Routes change successfully.
2. Seems like a package you are importing is throwing an error on your mobile, thus route change is halting (common Vue-Router behavior). My guess is that it's `rxdb` is at fault, so you might want to open up a ticket on their website.

Either way (a fault in Vue-Router or most likely a package you are importing), Quasar is not at fault.

Wish I could help more, but I am on a tight schedule for v0.14.
Regards,
Razvan

**Comment by lyquocnam** [comment]
@rstoenescu please see this, may this relate quasar-cli https://github.com/pubkey/rxdb/issues/172

**Comment by rstoenescu** [comment]
@lyquocnam Posted a message on that thread. Seems like they don't transpile their npm distributable, which is not the expected behavior when the package is used in a Webpack environment. Let's see what they say.

**Comment by rstoenescu** [comment]
Until rxdb figures it out, you can add an exception for running babel on rxdb too. Change `/build/webpack.conf.js`:

```js
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: projectRoot,
        exclude: /node_modules/ <<<<<<<<
      },
```
`/node_modules/` should be `/node_modules(?!\/rxdb)/` for you.

**Comment by lyquocnam** [comment]
i changed in `webpack.base.config.js` but not work !
![image](https://cloud.githubusercontent.com/assets/8347826/26131955/3e00c9a8-3ac7-11e7-9f42-5e467ebe59c8.png)
