### ISSUE TITLE
[QSelect] Enhancement: Add option to truncate long labels

### ISSUE THREAD

**Issue by matthiasmoier** [quasarframework/quasar#5734]
**Is your feature request related to a problem? Please describe.**
When the label of a QSelect item is longer than the QSelect itself, the label is wrapped on multiple lines.

**Describe the solution you'd like**
I’d like to have an option to truncate long labels. This could e.g. be handled with an additional attribute `truncate` which could be added to the `<q-select>`:

```javascript
<q-select
    label="Options"
    :options="[
        {label: 'Please choose', value: '', disable: true},
        {label: 'Option 1 (which has a pretty long label)', value: '1'},
        {label: 'Option 2', value: '2'}
    ]"
    truncate
>
```

As far as I have tested this, it should be pretty simple as it seems that adding the [Quasar CSS Visibility](https://quasar.dev/style/visibility) class `ellipsis` to the `<span>` that wraps the label text already results in the desired behaviour:

<img width="245" alt="Screenshot 2019-11-28 at 18 21 58" src="https://user-images.githubusercontent.com/900640/69824844-682ee500-120d-11ea-8857-6808cdd7a076.png">

<img width="246" alt="Screenshot 2019-11-28 at 18 22 26" src="https://user-images.githubusercontent.com/900640/69824845-682ee500-120d-11ea-8403-8719c11514ae.png">

<img width="625" alt="Screenshot 2019-11-28 at 18 35 09" src="https://user-images.githubusercontent.com/900640/69824970-dd021f00-120d-11ea-8956-7674e8479cdf.png">

**Comment by pdanpdan** [comment]
Hello. You can use the scoped slot for options to display them in any way you like.

**Comment by matthiasmeier** [comment]
Hi @pdanpdan 

My request was about an option to optimize how the currently selected item / value is shown if it should be longer than the select itself.

The options themselves are not the problem as they are by default shown in "full width" when the select is opened:

<img width="136" alt="Screenshot 2019-11-28 at 18 57 06" src="https://user-images.githubusercontent.com/900640/69825891-2d2eb080-1211-11ea-9e36-fdc65fe1cc1c.png">


<img width="134" alt="Screenshot 2019-11-28 at 18 57 33" src="https://user-images.githubusercontent.com/900640/69825902-328bfb00-1211-11ea-95e2-be48f81bc636.png">

**Comment by matthiasmeier** [comment]
This would be an alternative way to achieve it:

```javascript
<template v-slot:selected-item="scope">
    <span class="ellipsis">{{ scope.opt.label }}</span>
</template>
```
I just thought that having a single attribute to fix this issue would be easier than to have to add this to every `q-select`.

**Comment by hawkeye64** [comment]
Can this also be added to other components that may need it? Like QBtn and family? Using slots every time is tedious compared to `truncate` and `label` props.

**Comment by matthiasmeier** [comment]
@hawkeye64 – interesting idea.

This could e.g. simplify the provided [truncate example](https://quasar.dev/vue-components/button#Example--Truncate-label) for `QBtn`:

```html
<q-btn color="primary" style="width: 200px">
  <div class="ellipsis">
    This is some very long text that is expected to be truncated
  </div>
</q-btn>
```

With `truncate` attribute:
```html
<q-btn color="primary" style="width: 200px" truncate label="This is some very long text that is expected to be truncated />
```

**Comment by hawkeye64** [comment]
@matthiasmeier The `div` in your example should be a `span` so you can still use the `align` property.

**Comment by matthiasmeier** [comment]
@hawkeye64 I just copy-pasted the example from https://quasar.dev/vue-components/button#Example--Truncate-label 😉

And with the `truncate` prop, it would not be necessary anymore.

But thanks for the hint.

**Comment by rfox12** [comment]
I think providing a consistent strategy/options for long text truncation should absolutely be part of Quasar core!  I run into this all the time.

**Comment by metalsadman** [comment]
popping a pen for when using multiple or single selection using css selector https://codepen.io/metalsadman/pen/yLNpgzw , can't be used with `use-chips`.

**Comment by pdanpdan** [comment]
Any special need to display the selected option are covered by the slots (custom display).

**Comment by matthiasmoier** [comment]
his issue had been closed 1+ years ago and then @rstoenescu luckily reopened it. I think it’s a bummer if this just gets closed again without providing a proper/consistent solution to it. Sure, it _can_ be done in other ways – but I also think that @hawkeye64 's idea/question should be addressed as this is not a `<q-select>` problem only:

> Can this also be added to other components that may need it? Like QBtn and family? Using slots every time is tedious compared to `truncate` and `label` props.

And as mentioned earlier – these simple props would help get much cleaner code in Quasar for an issue that appears ever so often.

**Comment by pdanpdan** [comment]
And then you want to truncate at 2 lines :)
Slots allow you to customize, new props do not.

**Comment by hawkeye64** [comment]
I personally think components should always handle truncation in an elegant way and if someone does not want it, then there would be a `no-truncate` prop. I think there is a high number of people who would want this over those who don't.

**Comment by matthiasmoier** [comment]
> And then you want to truncate at 2 lines :)

I agree that custom truncation should be handled with custom code. But even more than that I’m convinced that it would be a huge plus for Quasar if the framework properly handled truncation properly by default.

I therefore totally support @hawkeye64 ’s idea/proposal with the `no-truncate` prop. It would enhance the default behavior (in that it would no longer break the layout by default; especially in regard of responsive design where widths change all the time – let’s be honest …  Quasar’s default behavior [see the example in my first screenshot above] just looks broken/ugly by now) … 

Plus – it would provide an option for the cases where truncation should not be the desired behavior. (Also useful in combination with the Screen Plugin to disable truncation in an easy way if it should f.e. not be truncated on mobile/narrow screens or the like.)

**Comment by louisameline** [comment]
I support the last two messages, this is common sense. And so does Razvan probably, or he wouldn't have reopened this issue.

**Comment by gilhrpenner** [comment]
Very nice to see this issue open again, this is something that needs to be part of Quasar.

**Comment by hawkeye64** [comment]
@gilhrpenner It's not open

**Comment by Daemach** [comment]
Well it should be...
