### ISSUE TITLE
Swipe navigation for QDate

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5736]
**Is your feature request related to a problem? Please describe.**
`QDate` month and year navigation buttons have small tap targets. For easier use on smaller touch devices, swipe navigation may be a decent alternative.

**Describe the solution you'd like**
Calendar view: swipe left/right to go to previous/next month (and possibly swipe up/down to go to previous/next year but that isn't as intuitive).

Years view: swipe left/right to go to previous/next page.

**Describe alternatives you've considered**
None so far.

**Additional context**

**Comment by pdanpdan** [comment]
Common, are you duplicating a feture request from 16 days ago that also has a PR? :)

https://github.com/quasarframework/quasar/issues/5562

**Comment by GordonBlahut** [comment]
Oops, sorry. I searched qdate swipe and didn't see anything. GitHub related issues beta also let me down. :(
