### ISSUE TITLE
UglifyJS deprecated in PurifyCSS on Webpack2 template

### ISSUE THREAD

**Issue by fractalzombie** [quasarframework/quasar#574]
Some problem with PurifyCSS, because maintainer of uglifyjs is deprecated it yesterday.
Please update Webpack2 template or else.

**Comment by rstoenescu** [comment]
Opened https://github.com/purifycss/purifycss/issues/159
Waiting for an answer so I can take a decision.

Please be polite and don't use expressions like "or else".

Thanks,
Razvan

**Comment by rstoenescu** [comment]
Temporarily removed PurifyCSS from the build process until they release a new npm version with the fix.

**Comment by fractalzombie** [comment]
Thanks)

**Comment by rstoenescu** [comment]
The maintainer of PurifyCSS just released a new version which fixes the problem, so brought back PurifyCSS into the starter kit. Thanks for your patience!
