### ISSUE TITLE
Electron: nodeIntegration:false breaks platform detection

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5741]
**Describe the bug**
Thank you for the nodeIntegration option! However, there is an issue.
If you disable node integration in `electron-main.js`, The platform detection (`this.$q.platform.is.electron`) is unset.

**Codepen/jsFiddle/Codesandbox (required)**
-

**To Reproduce**
1. Disable nodeIntegration in `electron-main.js`
2. You can no longer detect electron as platform
3. In dev and prod electron mode

**Expected behavior**
Platform detection should work with disabled nodeIntegration

**Platform (please complete the following information):**
OS: Windows 7
Node: 10.16.0
NPM: 6.9.0
Yarn: 1.19
Browsers: -
iOS: -
Android: -
Electron: 7.1

Thank you

**Comment by brindosch** [comment]
Additional side bug, due to the wrong detection there is no `electron` class at the body, which results in a missing `q-electron-drag` definition of `-webkit-app-region: drag`

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting!
Fix will be available in "quasar" v1.5.2.
