### ISSUE TITLE
QPopupEdit: validate prop broken

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5742]
**Describe the bug**
The example in docs is broken, the validation doesn't work: [Quasar Docs](https://quasar.dev/vue-components/popup-edit#Example--Edit-with-validation)

**Codepen/jsFiddle/Codesandbox (required)**
-

**To Reproduce**
1. Try the validation example linked above

**Expected behavior**
Example should work

**Screenshots**

**Platform (please complete the following information):**
OS: Windows
Node:
NPM:
Yarn:
Browsers: Chrome 78
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Hi,

This is a mistake in the docs example code. If your model is a number, then don't forget to declare it as such. Example (notice `type="number"` and the two `v-model.number=`):

```
<q-td key="calories" :props="props">
  {{ props.row.calories }}
  <q-popup-edit v-model.number="props.row.calories">
    <q-input type="number" v-model.number="props.row.calories" dense autofocus />
  </q-popup-edit>
</q-td>
```

**Comment by rstoenescu** [comment]
Fixed examples will be available on next docs deployment.

**Comment by brindosch** [comment]
Thanks for investigation. My model is a string. No :validate trigger. Do you want a fiddle?

**Comment by rstoenescu** [comment]
@brindosch yes please

**Comment by brindosch** [comment]
Okay, here the example. Please have a look.
https://jsfiddle.net/edeltraud/mqghn706/14/

**Comment by brindosch** [comment]
There is another regression in recent Qusasar. The save button doesn't respect the validation (no save on error). This worked recently even when i used '@input' from 'q-input' to trigger validation method

Should i create a new issue for this?

**Comment by pdanpdan** [comment]
All is ok, you just misspelled the prop name - it's `validate`, not `validation`
https://jsfiddle.net/3sn9cgqt/

**Comment by brindosch** [comment]
Oh, you are right. Sorry for that.
But it still doesn't work for me with Chrome 78, FF 70, Opera 65

Because it sounds so crazy, here a gif.
![q-pupup-edit issue](https://user-images.githubusercontent.com/15967679/69881413-45fc9c00-12cd-11ea-8ea5-6b1bb092804c.gif)

**Comment by rstoenescu** [comment]
Clicking outside of the QPopupEdit is equivalent to a forced "cancel".

**Comment by brindosch** [comment]
Oh, i mean the validation message doesn't trigger and i can use `@save` with "error data". The validation method won't be called
