### ISSUE TITLE
Add option to change the border color of q-input and q-select on focus

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#5744]
The default focus color of q-input and q-select is something like blue.
Sometimes I just want to change the focus border color to green. 
This can be achieved by using adding prop `color="green-9"`. 
But in q-select I dont expect the text inside will also be green only the border.

Please see demo: https://codepen.io/ajcastro/pen/zYYgVgM?editors=1000
Thanks! ❤️

**Comment by metalsadman** [comment]
@ajacastro that only happens when `use-chips` is on, which is probably what your FR is for. can be done using selected slot atm, as seen here https://codepen.io/metalsadman/pen/XWJrQdP?editors=1010.

**Comment by ajcastro** [comment]
thanks a lot @metalsadman
