### ISSUE TITLE
Feature Request: create a flag to run quasar dev -m cordova from file:// instead of server on development machine

### ISSUE THREAD

**Issue by siauderman** [quasarframework/quasar#5746]
Currently, running quasar dev on cordova results in the app URL being re-pointed to the IP address of the development machine. This creates CORS errors which do not arise when cordova is running from file:// as in a production environment.

Additionally, running the pages from a development server results in hard to detect bugs which strangely arise when the cordova app runs from file:// in a production release.

This problem is currently mitigated by running quasar build -m android and cordova run android from src-cordova thereafter. However, this solution is not ideal as the source code is built for production and minified, making it very hard to debug remotely.

I am requesting for a new flag to be added so that a cordova dev build can run off file:// instead of pointing at the IP address of the development machine. This would be very helpful for debugging purposes. I understand that if this is done, hot-reload probably would not be able to work but that is a small price to pay.

**Comment by rstoenescu** [comment]
Hi,

There is no technical solution (at least yet) to run from file://... HMR would not work, so dev mode would become useless.. However Cordova should not trigger CORS issues. If it does, then it's a Cordova bug. Of course, it matters what webview you are using: the default, ionic, wkwebview? Each has its own way of dealing with CORS...

**Comment by siauderman** [comment]
I am using the default web view. Cordova triggers CORS issues as my API is on a different server from the dev server (I need to call a REST API). Although HMR would not work, this best mimics a production environment without having to do a production build. Hope that you can consider adding it (even without HMR).

**Comment by rstoenescu** [comment]
@siauderman  Configure your API server to send the `Access-Control-Allow-Origin` header with `*` value. There's no way that we can tap into the webview and change its security settings.
