### ISSUE TITLE
why hot update is Invalid

### ISSUE THREAD

**Issue by zouyujie** [quasarframework/quasar#5747]
hi,I've set hot update, but it doesn't work，here is my configuration
quasar.conf.js:
```
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
 plugins: [
      new HtmlWebpackPlugin({
        title: "Hot Module Replacement"
      }),
      new webpack.HotModuleReplacementPlugin()
    ],
    devServer: {
      // https: true,
      port: 8081,
      open: true, // opens browser window automatically
      hot: true, 
......
```
this is run info:
    Dev mode.......... spa
    Pkg quasar........ v1.4.5
    Pkg @quasar/app... v1.3.0

**Comment by rstoenescu** [comment]
Hi,

Hot update (HMR) is already available. No reason to add it yourself.

**Comment by SacDin** [comment]
Hi,
It seems to work in local but while using with custom `devServer.public` set and using it over https address, getting following error : 
```
VM9538 log.js:26 [HMR] Cannot apply update. Need to do a full reload!
VM9538 log.js:26 [HMR] Error: Aborted because ./src/pages/test.vue is not accepted
```
It is reloading entire page even when slight change is made.

**Comment by rstoenescu** [comment]
@SacDin this would be a question for the Webpack maintainers...
