### ISSUE TITLE
Drawer close event is not present for Items retrieved from asychrone request

### ISSUE THREAD

**Issue by cedrico2016** [quasarframework/quasar#575]
I have build a drawer with an array of elements. The first three elements are initialised in the code and the other elements are retrieved from and API Endpoint with an asychronous request. The problem is, for the elements retrieved from the Api Endpoint the drawer doesn't get closed after click, but the routing works without problem. (so the drawer stays opened). After debugging of the framework code, i've noticed that the close click event handler is added to the elemts with the mounted() functionm and at that moment the 
 asynchronous request has not yet been resolved. 

So i was obligated to manually add the close event. 
I don't know if that is a kind of bug or can we do it better? 

![html_code](https://cloud.githubusercontent.com/assets/20278476/26099739/fb9c7db4-3a2b-11e7-8f4c-25536af26649.png)
![event_handler1](https://cloud.githubusercontent.com/assets/20278476/26099744/023a81de-3a2c-11e7-96ee-d3a09113180b.png)
![event_handler2](https://cloud.githubusercontent.com/assets/20278476/26099750/056c12a0-3a2c-11e7-9acd-90a6653f616d.png)
![drawer](https://cloud.githubusercontent.com/assets/20278476/26099762/0cbb0796-3a2c-11e7-84fe-03ec005de7e2.png)

Here is the code 
https://gist.github.com/cedrico2016/b8d0b0c262b22414737b58e6da9fbe40

**Comment by rstoenescu** [comment]
Manually adding it is good. This issue is obsolete now that v0.14 is around the corner. You won't have same problem with [v0.14](http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list).

Thanks for reporting though!
