### ISSUE TITLE
QSelect shows value instead label on blur event

### ISSUE THREAD

**Issue by dexif** [quasarframework/quasar#5753]
**Describe the bug**
https://codepen.io/dexif/pen/povzgPK
Try to input "twi" then click outside QSelect to call blur event on QSelect.
You will see integer value instead human readable label.

**Comment by ZeroxJP** [comment]
this is because the selected options is filtered out
https://codepen.io/ZeroxJP/pen/wvBwMNm
the model is not a int but an object. i hope this help you out to fix your problem.

**Comment by dexif** [comment]
@ZeroxJP 
This may be a temporary fix. But not a real bug fix. When I filter parameters, I want to see only filtered elements. When QSelect loses focus, it must clear the filter and load the complete list to return to its original state.

**Comment by dexif** [comment]
For int values temporary fix looks like:
`return v.label.toLowerCase().indexOf(needle) > -1 || v.value === this.model`

**Comment by pdanpdan** [comment]
There is nothing to fix. Pass the full object as selection if you want to show details from it.

**Comment by dexif** [comment]
Oooh. Guys... Broken ui - is nothing to fix?! Really? After that you ask why we write wrappers? Because you broke model api... Where you have seen that the native select element returns value with label? You gave us the api to emit-value and map-options to fix that but we let you know that it doesn't work. And you say that is wrong usage? How can we use it by the right way? I love quasar, it is very useful and powerful framework. But migration to v1 is extremely  painful (( 
Maybe you just don't understand what I mean... 

Video: https://drive.google.com/file/d/1AB8eGuwLIlHvClP_HyXimgAeaXbx0Dsx/view?usp=drivesdk

If you think that it works correctly - I will no longer write to you about bugs. Apparently we are really not among those 95% of developers who use the framework correctly :cry:

**Comment by pdanpdan** [comment]
To recap:
- QSelect receives the model and emits the model
- the model can contain info about what to show (label)
- QSelect receives some options to show to the user to select from

You decide you want to pass QSelect a subset of info as model, which does not contain info about what to display. Then you complain QSelect does not display what you didn't give to it.
