### ISSUE TITLE
How to test Quasar (as Vue CLI plugin)?

### ISSUE THREAD

**Issue by zvadym** [quasarframework/quasar#5754]
**Describe the bug**
I can't import single component in my `jest` unit-test (but no problems inside vue components).
I've tried to describe everything here:
https://stackoverflow.com/questions/58974057/how-to-test-quasar-as-vue-cli-plugin

**Screenshots**
<img width="651" alt="n8ART" src="https://user-images.githubusercontent.com/780909/69884438-10fa4480-12e1-11ea-9767-a7312ac11eca.png">

**Platform (please complete the following information):**
OS: macos catalina
Node: 10.16.3
NPM: 6.12

**Comment by lucasfernog** [comment]
I believe you can learn a few things by reading our [testing AE](https://github.com/quasarframework/quasar-testing).

**Comment by lucasfernog** [comment]
That's one of the reasons we recommend using the Quasar CLI: a lot of things are just ready to use, plug and play.

**Comment by zvadym** [comment]
Agree, Quasar CLI looks good.. but for my next project. But now I really want to figure out how to run tests with current configuration (with Quasar as Vue CLI plugin)

**Comment by rstoenescu** [comment]
Hi,

By the looks of it, seems like in your setup the Quasar source code does not gets transpiled. So look into that.
