### ISSUE TITLE
1.5.2 Typescript scroll.d.ts possibly too strict

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5758]
**Describe the bug**
RE #5725, the changes to scroll.d.ts may be overly strict. Pinging @IlCallo for feedback.

I ran into a build issue with `setScrollPosition` after upgrading to 1.5.2. The `scrollTarget` type was changed from `Element | Window` to `HTMLElement | Window`.

`Element` has `scrollTop`, `scrollLeft`, `scrollHeight`, and `scrollWidth` so it should be compatible with the implementation of the various scroll methods already.

Requiring `HTMLElement` kills support for calling scroll methods on `$el` of a Vue component, since Vue defines `$el` as `Element`.

I'm not sure what is gained by restricting the type to `HTMLElement` in these cases?

**Codepen/jsFiddle/Codesandbox (required)**
N/A

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
N/A

**Comment by IlCallo** [comment]
@outofmemoryagain I remember you asked for this change on Discord but I cannot access the server now, do you remember why was it needed? Is it safe to revert? The pointed out use case seems pretty relevant

**Comment by rstoenescu** [comment]
@IlCallo can you revert back to Element pls? I'd like to catch this for next Quasar release. If time doesn't allow it, I'll do it. Just gimme a sign how to proceed. Thanks!

**Comment by IlCallo** [comment]
Yeah, I was waiting for a comment from Kerry since he requested the change, but no problem
I'll do it this afternoon :+1:

**Comment by rstoenescu** [comment]
Many thanks!

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.3.

**Comment by outofmemoryagain** [comment]
@IlCallo @rstoenescu, sorry I was out of town on holiday for Thanksgiving.  I did request this change.  I will have to dig back through my notes as to what was missing, but I do remember having to type cast to HTMLElement for something.  Let me see if I can dig up the logic behind the change.

**Comment by outofmemoryagain** [comment]
@IlCallo @rstoenescu, I think this request was initiated based on my use of the utility to scroll to a specific element as highlighted in the documention, https://quasar.dev/quasar-utils/scrolling-utils#Scrolling-to-an-element.  If the return is `Element` then the code will not work as is and will require `as HTMLElement` in order to use the `offsetTop` property.  I made a bad assumption based on the example of the intended type.  Based on the implementation the the scroll utility the type was correct as `Element`.  This is simply a case that highlights the need for some specific TS based examples in the documentation.  This is of course a longer term goal to improve our TS support.

**Comment by rstoenescu** [comment]
Thanks for both your efforts. Really appreciate it <3

**Comment by GordonBlahut** [comment]
@outofmemoryagain in that case, would it make more sense to have the other scroll methods as accepting `Element | Window`, but have `getScrollTarget` return `HTMLElement | Window`? I'm not sure if `getScrollTarget` would ever return an `Element` that isn't an `HTMLElement` based on the selectors it uses but if it's assumed to be an HTMLElement as per the example you referenced, then this could avoid the need to cast. Another option could be to make the `getScrollTarget` typing generic to match the `closest` it uses within and then one could do `getScrollTarget<HTMLElement>` which would return `HTMLElement | Window`.

**Comment by outofmemoryagain** [comment]
Matching `closest` typing is a good appoach we should consider
```ts
closest<E extends Element = Element>(selector: string): E | null;
```

**Comment by IlCallo** [comment]
I think it's safe to assume that `closest` parameter is always an `Element` for our purpose, so the generic part should be on the return value, if really needed.

I think we should start simple (without generics) and only add them if requested for a frequent-enough use case. Seems to me that Scroller features are only meant to work with `HTMLElement` and  `.scroll,.scroll-y,.overflow-auto` will never be added to some other type of element (for example, I think it won't work on SVGs, @rstoenescu confirm?) so probably just returning `HTMLElement` would work.

```ts
import 'quasar';

declare module 'quasar' {
  function getScrollTarget(el: Element): HTMLElement | Window;
}
```

If it would ever be needed, the generic version should be

```ts
import 'quasar';

declare module 'quasar' {
  function getScrollTarget<R extends Element = HTMLElement>(el: Element): R | Window;
}
```

@GordonBlahut @outofmemoryagain can you test if this will work for you?
As always, just copy/paste the snippet into a `test.shim.d.ts` and it should augment `quasar` module and let you check if it works as expected.

**Comment by GordonBlahut** [comment]
I think either definition is fine. The generic one is more flexible so unless there's a performance issue with having a generic definition, why not include it from the start?

> I think this request was initiated based on my use of the utility to scroll to a specific element as highlighted in the documention, https://quasar.dev/quasar-utils/scrolling-utils#Scrolling-to-an-element. If the return is Element then the code will not work as is and will require as HTMLElement in order to use the offsetTop property. 

Actually, if you look again at https://quasar.dev/quasar-utils/scrolling-utils#Scrolling-to-an-element, while `offsetTop` is referenced, it's not referenced from the `target` returned from `getScrollTarget` so the return type being `Element | Window` actually has no bearing in this example. Only the type of `el` passed into the `scrollToElement` would matter and since scrollToElement is a devland function, it would be upto the dev to type the `el` parameter as `HTMLElement`. 

So now I'm unsure if the return type really needs to change to `HTMLElement | Window` after all. Generally the target is only needed as a point of reference when setting offset on another element, right? Is it likely one needs to get `offset...` values on the target itself?

There's probably no harm in changing it, but this TypeScript version of the example is totally fine without either of the shims above:
```typescript
function scrollToElement (el: HTMLElement) {
    const target = getScrollTarget(el)
    const offset = el.offsetTop
    const duration = 1000
    setScrollPosition(target, offset, duration)
  }
```

**Comment by IlCallo** [comment]
> The generic one is more flexible so unless there's a performance issue with having a generic definition, why not include it from the start?

On the maintainer part, more complex code is always a burden. Also, simpler types are easier to understand by TS newbies.

> since scrollToElement is a devland function, it would be upto the dev to type the el parameter as `HTMLElement`.

True this.
Let's wait for someone else comes up with the same need before changing it (in which case, I'd still go with the non-generic version)

**Comment by GordonBlahut** [comment]
That sounds fine to me.
