### ISSUE TITLE
Custom SCSS not overriding imported/boot-plugin css

### ISSUE THREAD

**Issue by FaranAli9** [quasarframework/quasar#5759]
I am requiring a plugin(shakee93/vue-toasted) using a boot file but the default css for the plugin is not being overriden by custom css. This is happening because the App's custom SCSS is being included before the boot files are loaded.

**To Reproduce**
1. Require any third party plugin through quasar boot file. ( i used https://github.com/shakee93/vue-toasted )
2. Add custom css to css/app.scss to override style rules from the third party plugin
3. The custom css gets injected into the HTML before the plugin, the plugin css takes preference.

**Expected behavior**
The custom css should be the included at the very last to override any third party css rules.

**Comment by ibrainventures** [comment]
@FaranAli9 
not helping to your css-sorting issue .. but may overseen: 
https://quasar.dev/quasar-plugins/notify
If you are not bound to the "swipe-close", this quasar integrated notify is really sugar.

**Comment by FaranAli9** [comment]
Thanks @ibrainventures , yes I have seen and tried the notify plugin. The notify plugin does not give much configurations and options out of the box. Toased has default methods available for success/error/warning toasts so i'll be using it for now.

**Comment by pdanpdan** [comment]
Make a separate css file for overriding the variables and import it in the not file. It might work

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing! Merged your PR. Change will be available in "@quasar/app" v1.3.2.

However, you can add the same CSS (that you are importing from the boot files) to quasar.conf > css too (put a tilde character in front of them -- ~).

**Comment by FaranAli9** [comment]
Im not importing the css, rather im importing the whole package ( require('vue-toasted') ). This imports the js as well as inject the css through the style-loader. Thanks.

**Comment by rstoenescu** [comment]
Reverted the change in "@quasar/app" v1.3.3 due to https://github.com/quasarframework/quasar/issues/5790

The approach would be to create a boot file and import your CSS from there, rather than using quasar.conf.js > css. This way you can accurately control the order of imports. In future versions of "@quasar/app" I'll add an option to specify when to import each CSS entry (before or after the boot files).
