### ISSUE TITLE
Electron: Better nodeIntegration:false handling,

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5763]
**Is your feature request related to a problem? Please describe.**
Yes, `openUrl()` util is broken on electron with nodeIntegration:false. This brings me to a larger point

**Describe the solution you'd like**
The Quasar template for electron should provide a `electron-preload.js` that should inject by default Quasar related stuff. nodeIntegration should be disabled for new projects. The developer is free to change this completely afterwards.

But this will break `openUrl()` again. So the developer should wrap `openUrl()` on their own. Quasar may step back of maintaining such integrations like `openUrl()` with electron especially as there is basically no end. As example `copyToClipboard()` for all platforms? And even what about a `openConfirmDialog()`,`openPromptDialog()` which uses DialogPlugin or the best matching to the platform. This would be great, but is probably to much code that might be never used and needs to be maintained

Back to topic: Here an example preload.js
``` js
// src-electron/main-process/electron-preload.js
const { shell } = require('electron')
const { BrowserWindow } = require('electron').remote

window.electron = {
  shell,
  BrowserWindow
  // Add the whole stuff from $q.electron back
  // this can be now used in quasar as window.electron.shell.openExternal(URL)
}
```
The electron-main.js
``` js
// src-electron/main-process/electron-main.js
  // Create mainWindow
  mainWindow = new BrowserWindow({
    webPreferences: {
      preload: path.resolve(__dirname, 'electron-preload.js')
    }
  })
```

Webpack configuration needs to be tuned to copy around the file together with `electron-main.js`
```js
// quasar.conf.js
electron: {
  nodeIntegration: false,
  // webpack config to copy the file during build. How does this look usually?
  // There is probably also a need for a "electron-splash.html" next to it :)
}
```

**Describe alternatives you've considered**
Currently i use a hacked solution. My special problem is, i don't know how i can modify the Quasar electron webpack config to simply copy over the files during build. The static folder should never be used for this, as it is platform specific.
 - location: `statics/electron-preload.js`
 - loading: `preload: process.env.DEV ? path.resolve(__dirname, "..", "..", "src", "statics", "electron-preload.js") : path.resolve(__dirname, "statics", "electron-preload.js")`

**Additional context**

The preload.js can be further modified to something like this to prevent the node component in render thread scope. This would also work with a `openUrl()` or `copyToClipbord()` context
```js

window.electron = {
  openUrl(url) {
    shell.openExternal(url)
  },
  copyToClipboard (string) {
    clipboard.writeText(string)
  },
  minimize () {
    BrowserWindow.getFocusedWindow().minimize()
  },
  maximize () {
    BrowserWindow.getFocusedWindow().maximize()
  },
  unmaximize () {
    BrowserWindow.getFocusedWindow().unmaximize()
  },
  isMaximized () {
    return BrowserWindow.getFocusedWindow().isMaximized()
  },
  close () {
    BrowserWindow.getFocusedWindow().close()
  }
}
```

**Comment by rstoenescu** [comment]
Electron preload script support will be available shortly in "@quasar/app" v1.5.0.
