### ISSUE TITLE
Left Drawer do not hides itself under breakpoint on first draw

### ISSUE THREAD

**Issue by realtebo** [quasarframework/quasar#5765]
**Describe the bug**
My QDrawer is se to be hidden until a certain breakpoint. 
It works with normal resizing of windows, but if I reload the page, under the breakpoint, it is showed (also it's showed not respecting layout setting to be under the topbar)

**To Reproduce**
```
<q-drawer
      v-model="leftDrawerOpen"
      bordered
      content-class="bg-primary"
      :breakpoint="782"
      :width="230"
    >
```

having
```
  data () {
    return {
      leftDrawerOpen: this.$q.platform.is.desktop,
   }
}
```

**Expected behavior**
On desktop, if width is <782 pixel it must NOT be shown !

**Screenshots**

Taken at 570px 

![image](https://user-images.githubusercontent.com/1268699/69903793-b45d5f00-139e-11ea-98bc-56007cf1c304.png)

**Platform (please complete the following information):**

OS: Windows 10
Node: 10.16
NPM: 6.11.1
Yarn: 1.19.2
Browsers:  Chrome 

**Additional context**
    
```
    Dev mode.......... spa
    Pkg quasar........ v1.5.2
    Pkg @quasar/app... v1.3.1

```

Printout of` `this.$q.platform.is`

```
chrome: true
desktop: true
name: "chrome"
platform: "win"
version: "78.0.3904.108"
versionNumber: 78
webkit: true
win: true
```

**Comment by rstoenescu** [comment]
Hi,

You’re not using leftDrawerOpen as model for drawer :)

Never use Platform as model.

**Comment by rstoenescu** [comment]
Ok, I now see that you changed the initial description.

The model is king. You are now telling your drawer to be opened regardless of any breakpoint on desktop at startup.

What you want is to initialize leftDrawerOpen with this.$q.platform.is.desktop && this.$q.screen.width > 782
OR
Initialize leftDrawerOpen with false and simply use show-if-above prop.

**Comment by realtebo** [comment]
Thanks. I suggest to add a small note about this on documentation. I ll try later today and I will confirm the result

**Comment by realtebo** [comment]
Thanks for clarification.
Your system works.
At the end,  I removed the v-model and used breakpoint and show-if-above.

I'd like to point, anyway that: when using v-model, if v-model is true, the drawer is show above both header and footer, ignoring q-layout setup.

**Comment by rstoenescu** [comment]
That is the mobile behavior (below breakpoint). It works as designed. When above breakpoint, it takes into consideration the layout’s ‘view’ setup.
