### ISSUE TITLE
qSelect with use-input UX issues

### ISSUE THREAD

**Issue by Cmacu** [quasarframework/quasar#5768]
There are three issues with qSelect when using `use-input`:
1, pressing `backspace` on empty input(filter) should clear the model
2. typing in the input doesn't highlight the first filtered result
3. The input(filter) should be visually separated from the selected value to avoid confusion

Example:
https://codepen.io/dandcode/pen/jOENMGx?&editable=true&editors=101

**To Reproduce**
Case 1 (backspace): Open the codepen and click on the select. Press backspace (nothing happens)

Case 2(filtering): Open the codepen, click on the select and type `ora` in the input. Tab or press Enter (nothing happens). Most users would expect that the first available option is highlighted, because that's how most of the autocomplete and other select inputs work.

Case 3(UI design): Open the codepen, click on the select and type `app`. Look at the input (Google app), it looks very confusing.

**Expected behavior**
Case 1: The currently selected value should be cleared
Case 2: the first available option should be highlighted
Case 3: the input(filter) should be visually separate from the selected option. Best case is to be in the dropdown as every other select plugin and component from other libraries.

**Platform (please complete the following information):**
OS: Win, Mac
Node: Any
NPM: Any
Yarn: Any
Browsers: All
iOS: N/A
Android: N/A
Electron: Any

**Additional context**
I am aware of the `clearable` prop. The problem with it is that the user has to use the mouse to clear the value. In fact, if `clearable` is not selected, there is no way the user can clear the value.

I am aware of the `hide-selected` and `fill-input` props. The issue with them is that they hide the currently selected value while the user is filtering for a new selection. Also in order to start filtering they user have to first clear the current value. Finally, if the user doesn't find what they were trying to select it's confusing to figure out what the original value is. These props doesn't solve the first (backspace) issue.

I am interested in contributing for resolving this issue, but I am not sure where to start, I read the contribution guide and went through the component code and I have some ideas how to solve this. The next step should be to get someone to look into the issue and determine, if it's something worth doing.

**Comment by pdanpdan** [comment]
Why is 1 expected? Please provide a native behaviour example. And yes, by default a selected native select can be cleared by selecting an empty option in it.
Why is 2 expected? Please provide a native behaviour example or a reason why typing "ora" should generate the selection of "coraline"
For 3 you would need to click twice to get to the filter

**Comment by Cmacu** [comment]
@pdanpdan 
1 is expected mainly because of 3. The input is mixed with the selection and makes it look like you can delete the selection by pressing backspace. Not being able to do it is at the same time confusing and frustrating for our users. Providing an empty slot option is a good idea and, if 3 is resolved than this problem would be solved.

Here are a bunch of examples (note how the first available result is always highlighted):

![browser_autocomplete](https://user-images.githubusercontent.com/11044542/69918106-9d1c8100-1433-11ea-9375-470cd26bcc8d.gif)

https://select2.org/getting-started/basic-usage
![select2](https://user-images.githubusercontent.com/11044542/69918110-ab6a9d00-1433-11ea-9dfc-62ade3f8b6c6.gif)

https://vue-select.org/
![vue-select](https://user-images.githubusercontent.com/11044542/69918111-af96ba80-1433-11ea-8ec8-277536dff9a3.gif)

https://vuetifyjs.com/en/components/autocompletes
![vuetify](https://user-images.githubusercontent.com/11044542/69918112-b45b6e80-1433-11ea-9838-dd053575ebd5.gif)

I think you would be hard pressed to find example with different behavior. Even `qSelect` highlights the first result before filtering. I would definitely consider this a bug.
And, if you want to go down the rabbit whole of UX, a nice feature is to have the term (the filter string) styled (underlined) in the list of available options.

For 3, I don't understand why the user would need to click 2 times and this would be unacceptable. None of the examples above required that the user clicks 2 times to start filtering, even if all of them provide an option for separate filter input.

**Comment by pdanpdan** [comment]
1. Where does QSelect highlight the first result? I mean in what combination of options? That would be wrong.
2. In the google search example the first (selected option) is what you typed, so it's no really the first option in the list
3. About delete - maybe there would be an idea to allow clearing the model on single selection IF clearable is set and hide-selection is not set (@rstoenescu ?), otherwise it would generate a lot of confusion when clearing the filter
4. For single selection the combination of `use-input hide-selection fill-input` does exactly what you require
5. For multiple selection the combination `use-input fill-input` does exactly what you require

**Comment by Cmacu** [comment]
1. https://codepen.io/dandcode/pen/WNbNEzZ?&editable=true&editors=101 Probably this is because the first option is the selected option. Still confusing that it doesn't work when you start filtering... 

2...
![google2](https://user-images.githubusercontent.com/11044542/69974686-5db16b80-14eb-11ea-8358-980c9953d1ca.gif)
Did you see all of the other examples? Is there a reason that you think, highlighting the first **filtered** option is bad idea/practice? For the native select input (no filter, customizations, etc), that's what actually happens when you start typing, it searches for the first option matching your keyboard entry and highlights it. I can't think of any drawbacks for highlighting the first **filtered** option and there are a lot of UX benefits. 

Worst case at least provide an option for the developers to do the highlighting. I tried different combinations with `showPopup`, `options[0].focused`, `setOptionIndex`.
`setOptionIndex` actually sounds exactly like what I want. From documentation: `Sets option from menu as 'focused'` (my read: highlighted). But it doesn't work: https://codepen.io/dandcode/pen/WNbNZNJ?editors=1011
Maybe the confusion comes from the difference between highlighting the option on empty input(filter) and **after the user types something in the input(filter)**. My comments are focused on later as an example of good UX. 

3. I agreed that the clearing can be done via a `Clear` option and implemented it on my end. An improvement on Quasar side is to move the input filter in the dropdown and have qSelect automatically prepend the `Clear` option on top of the options list.

4. In the main issue I described why `hide-selection` and `fill-input` are not usable in my case.

5. Multiple selects works great (accept the highlighting first filtered result part). The chips visually separate the filter from the selection and backspace clears the last selected option. 

Single select is where qSelect needs improvements, simply because there is no way for the user to clear the model without `clearable`. This is what, a `Clear` option enables and it's a great idea (It should be added to the documentation)

**Comment by GordonBlahut** [comment]
I'd like the ability to not reset the input value on blur if the user doesn't select an option. Basically more of a text input with autocomplete and less of a select. 

Imagine an address form with street address, city, state/province, country, and postal code where typing in the street address field displays address results and selecting one fills in the remaining fields. In some cases (especially with newer addresses) there may not be any results or none of the results shown may be the intended address. If the user tabs or otherwise blurs the element, their input is lost. In this case, it would make sense for the street address v-model to be bound only to the street portion of an address and the menu options to contain address objects. In this case, selecting a menu item shouldn't automatically impact the v-model of the input itself. Instead I can choose what to do with the selected option inside of the callback.

**Comment by GordonBlahut** [comment]
@Cmacu if you make your update method `async` and `await this.$nextTick()` before `setOptionIndex` it seems to highlight the menu option: https://codepen.io/gordonblahut/pen/KKwpRPd?editors=1011 (only tested in Firefox).

**Comment by Cmacu** [comment]
@GordonBlahut wow, you are amazing! I owe you a beer!

**Comment by Cmacu** [comment]
By the way this solves your issue too. Since the first option is highlighted when you tab it's now selected and emitted to `@input`.

**Comment by GordonBlahut** [comment]
> By the way this solves your issue too. Since the first option is highlighted when you tab it's now selected and emitted to `@input`.

Not quite because I still want to keep the inputted text if there is no option available or the input loses focus without a tab/enter (like a regular text input). Also I'm not entirely sure if I want to automatically select the first item in my case since it may not be the correct one... but at least I can highlight if I need to (will probably add some logic around this in my case).

**Comment by behnoodk** [comment]
> I'd like the ability to not reset the input value on blur if the user doesn't select an option. Basically more of a text input with autocomplete and less of a select.

I think it would be nice feature to have. something like the component here: https://paliari.github.io/v-autocomplete/

**Comment by pdanpdan** [comment]
Added example in docs on how to customize the behavior after filtering:
https://quasar.dev/vue-components/select#Example--Selecting-option-after-filtering
Available in v1.7.4+
