### ISSUE TITLE
Disable tree control

### ISSUE THREAD

**Issue by fjl280855990** [quasarframework/quasar#5769]
When a child node of the tree is disabled, the check box option click of the parent node is invalid (the child node will not be processed automatically)

**Comment by pdanpdan** [comment]
And isn't it correct? Please add a codepen to show the problem.

**Comment by rstoenescu** [comment]
Please reopen with a codepen of your use-case. From your description, it works correctly.

**Comment by fjl280855990** [comment]
https://codepen.io/fjl280855990/pen/xxbxZVm?editors=1010

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.3.

**Comment by fjl280855990** [comment]
Thanks!
