### ISSUE TITLE
Table merging

### ISSUE THREAD

**Issue by fjl280855990** [quasarframework/quasar#5770]
![1](https://user-images.githubusercontent.com/35919845/69922837-9c8af580-14da-11ea-8ab1-11e1c55f2d9e.jpg)
![2](https://user-images.githubusercontent.com/35919845/69922838-9c8af580-14da-11ea-8322-6e0600b27ed3.jpg)

**Comment by pdanpdan** [comment]
Please add a description for the request, and a codepen showing what you have tried.

**Comment by rstoenescu** [comment]
Hi,

This is one of the use cases for header and row scoped slots. Use that along with the native attributes colspan and/or rowspan.

**Comment by pdanpdan** [comment]
Example here: https://codepen.io/pdanpdan/pen/vYEYNQM?editors=1010

**Comment by hks2002** [comment]
Does it possible add one attributes to one col/row to enable auto rowspan/colspan? So that the display could driven by the data, doesn't need to write the "rowspan='x' or colspan='x' " to the <q-td>

**Comment by fjl280855990** [comment]
yes, merge multiple rows and columns through property settings




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hks2002"<notifications@github.com&gt;; 
发送时间: 2019年12月30日(星期一) 上午9:58
收件人: "quasarframework/quasar"<quasar@noreply.github.com&gt;; 
抄送: "Moomba"<280855990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [quasarframework/quasar] Table merging (#5770)




Does it possible add one attributes to one col/row to enable auto rowspan/colspan? So that the display could driven by the data, doesn't need to write the "rowspan='x' or colspan='x' " to the 
 
&mdash;
