### ISSUE TITLE
Error Building when using sassLoaderOptions

### ISSUE THREAD

**Issue by SylvanoTombo** [quasarframework/quasar#5772]
**Describe the bug**
Failed to compile with 1 errors when using sassLoaderOptions
Error: SassError: $string: 0 is not a string.

Link codesandbox
https://codesandbox.io/s/github/SylvanoTombo/work

![Screenshot_2019-12-02_10-17-16](https://user-images.githubusercontent.com/40351002/69937912-f98fa700-14ec-11ea-9d09-29c015d0e704.png)

**Comment by rstoenescu** [comment]
Hi @SylvanoTombo ,

What is your sassLoaderOptions content?

**Comment by SylvanoTombo** [comment]
Hi @rstoenescu 

 sassLoaderOptions: {
        implementation: require('sass')
 }
I can't see the implementation in doc, may be i am wrong

**Comment by rstoenescu** [comment]
What is the reason for specifying that?

**Comment by SylvanoTombo** [comment]
i want to use dart-sass (npm sass) as the implementation. i would like to compile sass files from vuetify.

**Comment by rstoenescu** [comment]
Hi,

You won't like it, but please use node-sass instead.
