### ISSUE TITLE
QPopupEdit: :validate broken

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5780]
**Describe the bug**
Sorry for re-opening this but you probably missed the point. Back to [docu](https://quasar.dev/vue-components/popup-edit#Example--Edit-with-validation)
The validation never triggers. `:error="errorProtein"` and `:error-message="errorMessageProtein"` are never set/unset.

The result is also that `@save` doesn't work as documented: `Emitted when value has been successfully validated and it should be saved`

**Codepen/jsFiddle/Codesandbox (required)**
not required

**To Reproduce**
1. Try to use `:validate` and `@save` as documented

**Expected behavior**
`@save` should block until `:validate` is true. But `:validate` is broken

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers: Opera 65
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
What is not working for you. In the documentation you link to it works. Only the ok button triggers the validation.

**Comment by brindosch** [comment]
It seems that my cache messed around with the results. You are right. Works as intended.
Sorry for the noise!

:heart:
