### ISSUE TITLE
CSS are breaking for the button component in Safari browser 

### ISSUE THREAD

**Issue by VasuLaravel** [quasarframework/quasar#5783]
**Describe the bug**
I am using UMD CDN of Quasar framework. After 2nd Dec 2019 release the CSS of the button component started breaking in Safari browser. Height is taking 100% for this class `'.q-btn__wrapper'`

**Expected behavior**
Height of the button should be normal

**Screenshots**
<img width="1432" alt="Screen Shot 2019-12-03 at 10 55 22 AM" src="https://user-images.githubusercontent.com/22410955/70022875-b7816680-15bb-11ea-9a80-d006e2400eb5.png">

**Platform (please complete the following information):**
OS: Mac OS
Node: v8.15.1
NPM: 6.4.1
Yarn:
Browsers: Safari
iOS:
Android:
Electron:

**Additional context**
Attached the screenshot for your reference. And also you can see the highlighted CSS which is causing the issue in the photo. Thanks !

**Comment by pdanpdan** [comment]
Please make a codepen where you can reproduce the problem.

**Comment by VasuLaravel** [comment]
I have created the codepen. But not able to replicate this issue in codepen.

https://codepen.io/vasularavel/pen/gObOqXo

Please create a HTML file with the content available in the codepen and try to open in safari. You will see the error. Thanks !

**Comment by pdanpdan** [comment]
I'll put here a proper pen for testing:
normal: https://codepen.io/pdanpdan/pen/rNaNPra?editors=1010
debug view: https://cdpn.io/pdanpdan/debug/rNaNPra/RBAOJXRmQywr

**Comment by pdanpdan** [comment]
Hello.

Your HTML pages are lacking the doctype definition at start, and as a result Safari probably enters some kind of compatibility mode.

Add at the start of your HTMl template

```html
<!DOCTYPE html>
<html ...>
...
</html>
```

**Comment by VasuLaravel** [comment]
Really appreciate the effort. Thanks a ton
