### ISSUE TITLE
Ugly blurry menu icon

### ISSUE THREAD

**Issue by imShara** [quasarframework/quasar#5784]
**Describe the bug**
Wrong size of burger menu icon

**Codepen/jsFiddle/Codesandbox (required)**
Just at official docs https://quasar.dev/start/pick-quasar-flavour

**To Reproduce**
Zoom in at 1dpr ratio
![2019-12-03_09-17](https://user-images.githubusercontent.com/4913196/70025861-489e1080-15af-11ea-8f67-0c08bb68a2a4.png)

**Expected behavior**
Should be when icon size = 24 px
![2019-12-03_09-18](https://user-images.githubusercontent.com/4913196/70025911-679ca280-15af-11ea-97d3-e80f943d2c71.png)

**Screenshots**
![2019-12-03_09-16](https://user-images.githubusercontent.com/4913196/70026028-b6e2d300-15af-11ea-83fe-d976b8ae14db.jpg)

**Platform (please complete the following information):**
Any device with 1dpr ration

**Additional context**
Icon fonts should be used pixel perfectly

**Comment by rstoenescu** [comment]
Hi,

Fix will be available in "quasar" v1.5.4.
