### ISSUE TITLE
[Internet Explorer] - Problems with Intranet Sites

### ISSUE THREAD

**Issue by patrickmonteiro** [quasarframework/quasar#5789]
I currently work with quasar on several projects in the company I provide services. Our environment is windows, with IIS server.
Quasar systems have always worked perfectly on internet explore, but last week we had an error where the page was not rendered showing a console error.
So I decided to analyze with a project created from scratch, without any other implementation.
I found that when a site is in the list of sites in Internet Compatibility View explore, it is rendered in document mode 7 (IE 7 emulation). Causing support errors for ecmascript methods and properties.

1. Create a project with the quasar create command, with internet explore support active.
2. Generate a spa build with the quasar build command
3. Go to the project dist / spa directory and start a server with the quasar serve command.
4. Go to http: // localhost: 4000 at internet explore.
5. The quasar site should display normally as in the image below:
![image](https://user-images.githubusercontent.com/13258255/70078732-ffb37f80-15e1-11ea-977a-811f02373201.png)
6. In internet explore, go to **Tools**-> **Compatibility View Settings**.
7. Add localhost as a site to the list of sites that used compatibility view.
8. Check the "Display intranet sites in Compatibility View" checkbox.
9. Hit close on the "compatibility view settings" modal and wait for the site to reload.
10. A blank screen will be displayed. Pressing f12 we get an informational message "The attached page is directed to document mode 7. Some console features and APIs may not be available." And some errors are displayed as "Object doesn't support 'bind' property or method".
11. Print of how my console is displayed (my operating system is pt-br):
![image](https://user-images.githubusercontent.com/13258255/70079265-232afa00-15e3-11ea-910a-3380b0171375.png)

**Platform (please complete the following information):**
OS:  Windows_NT(10.0.18362) - win32/x64
Node: 12.13.0
NPM: 6.4.1
Yarn: 1.17.3
Browsers: Internet Explore 11.476.18362.0
quasar: 1.5.2
@quasar/cli 1.0.0
@quasar/app: 1.3.1
@quasar/extras: 1.3.3

**Partial solution of the problem:**
By adding the meta tag to index.html, the site ignores the fact that it is on the compatibility list, and uses the version specified in the tag:

`<meta http-equiv="X-UA-Compatible" content="IE=11" />`

Thus the site is normally rendered on the Internet explore.

Some references:
https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/3764531c-97c8-4bf2-bdc6-b3623738ea46
https://stackoverflow.com/questions/22034924/how-to-set-ie11-document-mode-to-edge-as-default

**Comment by lucianopereira86** [comment]
Great question, Patrick

**Comment by rstoenescu** [comment]
Hi,

Good to know. Maybe a tip on docs will do if any of you have a bit of time.
Adding the meta tag in src/index.template.html is the way to go.
