### ISSUE TITLE
q-drawer-link is turning into an active link with the class router-active-link

### ISSUE THREAD

**Issue by jeimz143** [quasarframework/quasar#579]
hi i'm having trouble regarding my q-drawer-link. whenever i try to add a drawer link, it result to an active link.. is this a feature or a bug? i think you must remove the active-router-link class

```
<q-drawer ref="leftDrawer">
                <div class="toolbar">
                    <q-toolbar-title>
                        Drawer Title
                    </q-toolbar-title>
                </div>
                <div class="list platform-delimiter">
                  <q-drawer-link icon="mail" to="/account">Account</q-drawer-link>
                </div>
            </q-drawer>
```
![untitled](https://cloud.githubusercontent.com/assets/13939947/26245439/a0a93e5e-3cc6-11e7-938e-74fe27a2565a.png)

as you can see to the image it result the link as active

**Comment by rstoenescu** [comment]
Hi, Use `exact` so it won't match every sub-routes.

**Comment by jeimz143** [comment]
I still getting the same  active link button

**Comment by rstoenescu** [comment]
@jeimz143 How did you use 'exact'?

**Comment by jeimz143** [comment]
actually i fixed it already, i just forgot to add some routes path to my router.js.. i was just confused.. thanks :)

**Comment by rachitpant** [comment]
> Hi, Use `exact` so it won't match every sub-routes.

@rstoenescu This should probably be fixed in quasar.styl (css) in v1. Though adding the exact link fixes it, its actually a css issue. exact is supposed to tell the vue router how to behave.
