### ISSUE TITLE
[app-1.3.2] new position of "css import command" inside client-entry template breaks boot-flow e.g. responsiveness

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5790]
Sorry, sorry, sorry for again disturbing the support area ...

**Describe the bug**
with quasar app 1.3.1 and below we had no problem with following boot/work-flow:

Initialiase a Store and read out some getComputedStyle-Property as state,
The resize / and toggling is later done with a eventlistener inside app.vue.

With 1.3.2 - where the position of the following script:

> <% css.length > 0 && css.filter(asset => asset.client !== false).forEach(asset => { %>
>   import '<%= asset.path %>'
> <% }) %>
> 

is positoned after the Vue Import, it seems that those css rules are not avaible during the
app-boot-flow (e.g. the store initial-command or the app.vue eventlistener). It only get respected
after a resize on the rendered-app.

Putting the import script to the old position (line 32..) the getComputedStyle works without
any problems.

If my usecase is a edge-case i can work with manually re-position that script (as long as i can edit that file without vendor-source compilation) - but may this repositining has also some side-effects on other functionality.

Quasar 1.5.4
All Browsers

Thank you again for all the effort and updates and many more ...

**Comment by rstoenescu** [comment]
Fix available in "@quasar/app" v1.3.3.
Reverted the change.
