### ISSUE TITLE
Selection finishing outside popup edit triggers 'hide' event

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#5791]
People usually select a text with some kind of margin, which naturally happens, as most of us just drag the cursor over the text.

As the input inside popup edit is located near the popup border, that often happens that the 'text selection drag' ends not over the popup but over the underlying element.

That case triggers 'hide' event' which hides the popup unexpectedly and the input focus is dropped as well.

That would be useful to make the popup persist while the selection drag takes place.

For an example, please go to: https://quasar.dev/vue-components/popup-edit, trigger popup-edit component by clicking on an editable cell in the table and start selecting popped up value in the input, and finish holding the mouse button when the cursor has left the popup-edit area. That would trigger the 'hide' event

Hope that helps!
Many thanks!

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.9.0

**Comment by pikil** [comment]
Thank you Razvan!
