### ISSUE TITLE
a weird behavior in exportFile util

### ISSUE THREAD

**Issue by iJosephY** [quasarframework/quasar#5792]
**Describe the bug**
I have this line of code
![image](https://user-images.githubusercontent.com/42868470/70124974-30dd8f80-1676-11ea-9c7e-e6bb8b1b681f.png)
As you see i have the file mimeType set to json
when i save the file, it doesn't save as .json

when i add .json to the end of the fileName
![image](https://user-images.githubusercontent.com/42868470/70125186-a9445080-1676-11ea-9722-86cd0cbc8b4e.png)

it saves as json 
BUT when i change the name from the explorer dialog it doesn't save as JSON -_- 
![image](https://user-images.githubusercontent.com/42868470/70125299-dc86df80-1676-11ea-8f19-a066261a5a7e.png)

is it a bug? or i don't know how to use it? or it can't be done

i'm using Quasar 1.5.2 ..

**Comment by pdanpdan** [comment]
What do you mean it doesn't save as JSON? It saves the file with the name you provided and the content you provided and the mimeType is there just as a hint for the browser to know what actions to perform (save or open with a specific registered application for that mimeType)

**Comment by iJosephY** [comment]
i mean if the user want to change the file name when he select where to save it
the extension of the file will not be the same as i provided

**Comment by pdanpdan** [comment]
Of course, it's his decision how to save the file :)

**Comment by iJosephY** [comment]
can't a strict a certain extension ?

**Comment by rstoenescu** [comment]
That would be a browser feature request.
Only thing that you can do (and you should!) is specify the extension for the file yourself too when you call exportFile().

**Comment by iJosephY** [comment]
Alright
Electron api it is
