### ISSUE TITLE
Round QBtn Stretches Height to Fit Container

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#5797]
Round QBtn always stretches its height to fit it's container's height.

Link to codepen: https://codepen.io/topvis/pen/jOEEoPY

**Expected behavior**
expect the round button to keep round

**Screenshots**
![image](https://user-images.githubusercontent.com/5996531/70161516-288f4f80-168a-11ea-90ee-e73f5c907132.png)

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Chrome

**Additional context**
1. `:stretch="false"` doesn't work.
2. A side issue is that the QBtn overlaps the QInput as shown in the screenshot.

**Comment by pdanpdan** [comment]
- by default a flex parent tries to stretch the children
- you cannot use self-closing component tags in codepen
- here is a working example: https://codepen.io/pdanpdan/pen/qBEEzRm?editors=1010
