### ISSUE TITLE
Problem with auto-import and functional component

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#5799]
**Describe the bug**
Auto-import quasar components does not import components inside a functional component.

**Codepen/jsFiddle/Codesandbox (required)**
Sorry, I dont have one but the steps are pretty simple

**To Reproduce**
1. Create a quasar project
2. Create a functional component using a quasar component
3. Use the component somewhere

**Expected behavior**
Show the functional component without problem

**Comment by pdanpdan** [comment]
Exact duplicate of https://github.com/quasarframework/quasar/issues/5373
