### ISSUE TITLE
[Request] Indexeddb support

### ISSUE THREAD

**Issue by matthewpull** [quasarframework/quasar#580]
Do you have planned support for IndexedDB, with similar APIs to LocalStorage and SessionStorage?

Both of those are really easy to work with, especially for my project which requires a large amount of data (1,000,000 names and email addresses). However, LocalStorage is not possible as this much data is ~13x more than the 5MB limit of LocalStorage.

Using IndexedDB would completely solve this issue, but it is difficult to work with and would be a great idea for a Quasar utility method. I'm sure that there are many other uses for storing more than 5MB of data offline at a time :)

Thanks for your consideration,
--Matthew Pull

**Comment by smolinari** [comment]
Hi Matthew,

Are you suggesting you'd like to have all the data on each client's device?

Scott

**Comment by matthewpull** [comment]
The project is a data collecting app for an event. Passers-by submit their name and email address to be entered to win a tablet. This app stores their details until the event is over and the device is back in a location with wifi (there is no guarantee of wifi at the event and the app has to work regardless)

**Comment by danikane** [comment]
https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html

**Comment by matthewpull** [comment]
Thanks, I've seen that and am using it for now. However, my feature request is for Quasar to has easy to use utility methods like for LocalStorage and SessionStorage http://quasar-framework.org/api/js-web-storage.html to make using IndexedDB easier.

**Comment by smolinari** [comment]
Unfortunately, I'd say the concern of supporting offline data storage local to the client is currently toward the bottom of the to-do list. Before that happens, we'd also need to support some form of data management within the framework itself, and that isn't there yet.

Scott

**Comment by matthewpull** [comment]
Fair enough, I appreciate that this is a somewhat specialised request.

**Comment by rhyek** [comment]
Wouldn't this be out of scope for this project?

**Comment by matthewpull** [comment]
@rhyek My thought is not, as IndexedDB is now a mainstream API with strong cross-browser support. Pretty much all libraries that add easy-to-use methods for LocalStorage and SessionStorage add the same for IndexedDB, so it feels like there is something missing by not having it.

**Comment by rstoenescu** [comment]
@matthewpull I've documented a little about Indexeddb. Seems like pretty straightforward and not really needing a wrapper. What would be the benefit of a wrapper and how do you see such a wrapper being used?

If we get past the first question then let's move on to second question and build the API specifications for Quasar Indexeddb wrapper together with the community.

**Comment by matthewpull** [comment]
From my point of view, having the wrapper would help with three things:

1. Standardise data storage using Quasar (i.e. the Quasar wrapper would feel familiar to the LocalStorage / SessionStorage wrappers)
2. Avoid any vendor-specific bugs with IndexedDB support
3. Provide a reliable and consistent error when IndexedDB is not supported

As you say, IndexedDB is not overly difficult to work with and I don't imagine that this is a big priority, but it would be nice to have eventually to complete the trio of local storage apis and provide consistent, simple access to all of them.

**Comment by lbssousa** [comment]
There's an interesting project by Mozilla called [localForage](http://localforage.github.io/localForage/), which wraps LocalStorage, WebSQL and IndexedDB with a simple LocalStorage-based API. I think it may be useful for you.

**Comment by matthewpull** [comment]
Yeah, there are a few libraries that do wrap it. MDN, for example, has this message:

> Note: IndexedDB API is powerful, but may seem too complicated for simple cases. If you'd prefer a simple API, try libraries such as localForage, dexie.js, and ZangoDB, that make IndexedDB more user-friendly.

I wouldn't worry about WebSQL support as that is deprecated and browsers are going to start removing it - new sites should _definitely_ avoid using it.

One of the really great things about Quasar is that you need very few other libraries. This is because there are so many JS and CSS utilities built in, which are fantastic. It just seems odd that this one is missing.

**Comment by rhyek** [comment]
@matthewpull: I am not a contributor to this project, so you can ignore me. IMO, you should not be interested in being shielded from all of the JS ecosystem with this one framework. There is so much great work out there on npmjs.com and also native APIs and there is just no way for Quasar to eventually be a wrapper/replacement for all of it. Instead you should embrace all of this pre-existing work and take advantage of all the man-hours already put into it, as well as the support you'll find on their respective repos, stackoverflow, etc.

To be honest, I find it surprising that Quasar *currently* does any wrapping of the Web Storage API at all. It is not needed.

**Comment by matthewpull** [comment]
@rhyek: True, you make a good point.

**Comment by rstoenescu** [comment]
@rhyek Oh but Quasar's wrapper has its benefits. It's not just syntactic sugar. It is often an overlooked fact that Quasar's web storage wrapper maintains the type of data you put into it (including regexp), while vanilla flavor works only with Strings.

Regarding the other libraries out there, it's again overlooked the fact that importing whole libraries for small parts of their functionality can turn your bundle in multiple MB faster than you can think. Not saying you should use only Quasar's functionality, far from it. Just making a point that more often than it should people import lots of packages without considering the consequences. I saw people importing jQuery only for setting a scroll position on a div. It's absurd. Use other libraries too, but use them wisely :)

Just my thoughts.

**Comment by matthewpull** [comment]
@rstoenescu I fully agree with the jQuery reference. It makes me really mad when I see the top SO answer being jQuery when there are other answers that do the exact same thing without it. Plus, Quasar has tree-shaking (or will have in 2 days), so the bundle size will only reflect the part of Quasar that is being used.

**Comment by rstoenescu** [comment]
I'm sorry but I'm going to close this one. Quasar may have an Indexeddb wrapper at some point, but it's out of reach at the moment.
