### ISSUE TITLE
QSelect: make popup-content-class the same as input-class

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#5803]
![image](https://user-images.githubusercontent.com/10262924/70246190-8d9f7f80-1734-11ea-829d-29487b195a58.png)

The property `popup-content-class` can only take a `String`, yet `input-class` can take `Array | String | Object`.

```html
          :input-class="{ 'text-primary bg-white': !$q.dark.isActive }"
          :popup-content-class="{ 'text-primary bg-white': !$q.dark.isActive }"
```
The top one is valid, but the bottom one is not.

**Comment by hawkeye64** [comment]
would this satisfy this feature?
```js
    menuContentClass () {
      if (this.virtualScrollHorizontal === true) {
        if (this.popupContentClass !== void 0) {
          if (isObject(this.popupContentClass)) {
            return Object.assign(this.popupContentClass, { 'q-virtual-scroll--horizontal': true })
          }
          else if (Array.isArray(this.popupContentClass)) {
            return [...this.popupContentClass].push('q-virtual-scroll--horizontal')
          }
          else {
            return 'q-virtual-scroll--horizontal ' + this.popupContentClass
          }
        }
        return 'q-virtual-scroll--horizontal'
      }
    },
```

**Comment by rstoenescu** [comment]
Hi,

Sorry, but don't... perf is important for this one.

**Comment by hawkeye64** [comment]
I thought it being computed would help out with that :(
It's ok tho, there's always a way to work-around something like this. I just thought consistency would be nice, since the results are going to QMenu which takes `Array | String | Object`.
