### ISSUE TITLE
q-infinite-scroll leaves gap after content

### ISSUE THREAD

**Issue by Demivan** [quasarframework/quasar#5804]
**Describe the bug**
When infinite-scroll scroll finishes loading it leaves blank space after content

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/demivan/pen/MWYwQxx

**To Reproduce**
1. Open Codepen
2. Scroll down, you can see loader
3. After 2 seconds loading finishes
4. Scroll down again
5. You can see gap after content where loader would have been

**Expected behavior**
After `done(false)` is called on `load` event loader should be removed and not just made invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/2339406/70251251-d2083b00-1787-11ea-9b92-8fef820811db.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: v10.16.0
Yarn: 1.19.1
Browsers: all

**Additional context**
This was changed as a fix for issue #5339. New behavior should either be made configurable or infinite-scroll should hide loader after last page is loaded.

**Comment by pdanpdan** [comment]
I forgot to check if it's stopped. Untill the next release set it as `disable` when you stop it.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.5.
