### ISSUE TITLE
Flickering transitions on Chrome IOS

### ISSUE THREAD

**Issue by moander** [quasarframework/quasar#5809]
There is a problem with transitions in Chrome IOS. The codepen is using animated stepper as an example but all transitions seems to be problematic.

**To Reproduce**
Change steps in codepen example:
https://codepen.io/moanderpen/pen/zYxvOZM

**Expected behavior**
The transitions when changing steps should behave like in Safari and Firefox IOS.

**Platform (please complete the following information):**
Browsers: Chrome 78.0.3904.84
iOS: 13.2.3
Quasar: 1.5.4

**Comment by rstoenescu** [comment]
Hi,

This is a problem with the blink rendering engine, used by chrome and opera. They need to fix it for iOS. We (Quasar) can’t do anything about it. Googling about “chrome ios choppy animation” gives a ton of results on the issue... :(
