### ISSUE TITLE
It is not possible to use :options-dark="false" if q-select is dark

### ISSUE THREAD

**Issue by Demivan** [quasarframework/quasar#5811]
**Describe the bug**
If both `dark` and `:options-dark="false"` are set on q-select options are still dark.

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/demivan/pen/PowPqVj

**To Reproduce**
1. Go to Codepen
2. See that options are dark even with `:options-dark="false"`

**Expected behavior**
Options should default to dark if select is dark but it should be possible to override this behavior with `:options-dark="false"`.

**Platform:**
OS: Windows 10
Node: v10.16.0
Yarn: 1.19.1
Browsers: All

**Additional context**
Looks like it was changed when global dark mode was implemented.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.8.
