### ISSUE TITLE
Table background color on mouse hover 

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#5813]
**Describe the bug**
Is there an option how to correct set a background color for table row on mouse hover? 

**jsFiddle**
The example is from original documentation with a simple css style changes.
https://codepen.io/woloda375/pen/eYmpzyY?&editable=true&editors=101

**How to reproduce**
Click on a row (on arrow) to expand it and observe color of expanded row. 

**Expected behaviour**
The color of expanded row should be white -> so it should not be "highlighted" 

**Purpose**
At the end of day I want to have table in table(after expantion) and that inner table do not have all rows clickable.

**Comment by pdanpdan** [comment]
Check here: https://codepen.io/pdanpdan/pen/rNaOjLX

**Comment by woloda375** [comment]
@pdanpdan I have to aggree with @rstoenescu that your solution solve only part of problem. The hover highlighting is someway propagating below and when there is a table in table, than the inner table rows will be highlighted after to hover over the inner table. 
https://codepen.io/woloda375/pen/QWwyGzq

**Comment by rstoenescu** [comment]
Stopped hover propagation. And also added "no-hover" Boolean prop for QTr and QTd.
Will be available in "quasar" v1.5.9.
