### ISSUE TITLE
QTable Select All adding selected undefined values

### ISSUE THREAD

**Issue by outofmemoryagain** [quasarframework/quasar#5814]
**Describe the bug**
When a QTable has Selection enabled, `rowsPerPage` is greater than the number of rows in the data, and the pagination `sortBy` is set.  Clicking Select all check box sets the `selected` property to an array that is the same length as the rowsPerPage, which results in undefined entries.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/outofmemoryagain/pen/RwNWReM?&editable=true&editors=101

**To Reproduce**
1. Go to https://codepen.io/outofmemoryagain/pen/RwNWReM?&editable=true&editors=101
2. Click on the "Select All" checkbox in the table header
3. Scroll down to the selected rows label
4. The data includes 25 rows even though the table only has 10 rows, with the last 15 being undefined

**Expected behavior**
The selected property should only contain actual data, in this case all 10 rows currently displayed in the table.

**Platform (please complete the following information):**
OS: Windows
Quasar: 1.5.4 
Browsers: Chrome

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.5.6.
