### ISSUE TITLE
QTable slot no-data not working after recent update

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#5816]
**Describe the bug**
I have upgraded from v1.2.x and noticed that now the slot no-data in QTable is not showing anymore.

I think it's something related to computedRows.length (and nothingToDisplay computed property in QTable.js)

**Codepen**
https://codepen.io/dariodepaolis/pen/bGNVBvr

**To Reproduce**
1. Type something in search field
2. When there are no more filtered rows the total is 0 but the no-data slot doesn't show
3. If you pass an empty data [] array it works (in the codepen there's a commented line for this test)

**Expected behavior**
Template slot no-data must show when filtered rows are equal to 0

**Platform (please complete the following information):**
OS: macOS Mojave
Browsers: Chrome 78 and Firefox 70

**Additional context**
I have other 2 projects with v1.1.x and 1.2x, and the same code is working without problem.

**Comment by dariodepaolis** [comment]
Or maybe it's related to this: https://github.com/quasarframework/quasar/commit/64fba90e8ead89a7bb1fdfae2038c4838b19eaa4 because now is a reference and not a copy of the data, maybe an array cloning [...data] can solve the issue.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.5.6.

**Comment by dariodepaolis** [comment]
Thank you for the instant update!
