### ISSUE TITLE
q-drawer-link 'router-link-active' class applied to multiple links

### ISSUE THREAD

**Issue by RaiserWeb** [quasarframework/quasar#582]
I am using a v-for to create links, the only difference in the link is the id at the end. When selecting a link, all the elements are getting the 'router-link-active' class applied, even through they are different.

``
<q-drawer-link icon="" v-for="event in events" :key="event.id" :to="'/event/programme/'+event.id"  >
	<span @click="$refs.leftDrawer.close()">{{event.name}}</span>
</q-drawer-link>
``

**Comment by rstoenescu** [comment]
Fixed in future v0.14 which is around the corner. Thanks for reporting.

**Comment by RaiserWeb** [comment]
That's great, thanks for the update
