### ISSUE TITLE
q-input shows undefined for a short period of time on blur

### ISSUE THREAD

**Issue by moander** [quasarframework/quasar#5820]
If model is undefined the input shows the text undefined for a short period when leaving the component.

https://codepen.io/moanderpen/pen/yLyYMRM

**To Reproduce**

1. Click the input
2. Click the hint
3. Pay close attention and you see 'undefined' for a very short period of time. 

On desktop it happends if you click other stuff as well but in iOS you must click the hint.

And for Chrome IOS undefined is actually editable until you click the second input.

**Platform:**
Browsers: Seems to happend in all browsers on both desktop and iOS

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.5.6.

**Comment by KeloLux** [comment]
Hello, I have seen that they solved this problem. But in my project it continues to fail. Using Vue Devtools I see that the innerValue is undefined. My "data" is the same as in the first comment. Please help me, thanks.

![image](https://user-images.githubusercontent.com/35495010/70418163-2864ca80-1a63-11ea-8b7b-3aff9c5b3fe5.png)

**Comment by pdanpdan** [comment]
@KeloLux You still send undefined. The fix is for not showing the undefined text. If you don't want the innerValue to be undefined ton't set it to undefined.

**Comment by KeloLux** [comment]
I am using a new empty object {} and sending a new property as in the example. Using the example, accessing the innerValue and value property is shown as undefined, but is not shown when losing focus.
Reviewing the code I think "undefined" is shown in the watch of value.

**Comment by pdanpdan** [comment]
But what is the problem you want fixed? Does undefined still show in the UI?

**Comment by KeloLux** [comment]
I want that when I lose focus, is not shown 'undefined' for a very short period of time.

**Comment by pdanpdan** [comment]
Did you update and it still show undefined?

**Comment by KeloLux** [comment]
Yes, I do not understand why. I attach a video for you to watch.
![QInput-Undefined](https://user-images.githubusercontent.com/35495010/70424324-7aabe880-1a6f-11ea-9998-b1a4fd289163.gif)

**Comment by pdanpdan** [comment]
@KeloLux Please add a codepen showing this, because I cannot reproduce it neither in the original OP codepen nor in my test cases.

**Comment by KeloLux** [comment]
I have already seen the error....
When accessing the debugger I have seen that the file QInput.js was not updated but if I accessed the VS Code at "node_modules\quasar\src\components\input\QInput.js"  this one was updated. I renamed the file, the compilation failed, reversed the changes and the correct code in the debugger was updated.
I have been testing the code in incognito mode, so the cache should not influence.
What do you recommend me to do next time?

Thank you very much and sorry for the inconvenience.

**Comment by pdanpdan** [comment]
Sometimes npm has some problems with really updating the files, so the best approach is this:
- update package.json
- remove node_modules folder and yarn.lock / package-lock.json files
- do a yarn / npm install (if using windows then yarn is strongly recommended)
