### ISSUE TITLE
Custom component in Dialog without boilerplate.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5822]
### Custom component in Dialog without boilerplate implementation example

I realised it's possible to provide the entire wrapper boilerplate for custom components in Dialog by default.
(When [invoking custom components](https://quasar.dev/quasar-plugins/dialog#Invoking-custom-component))

It's possible to use a slot inside the boilerplate element with a `<component :is="slotComponent" />` inside.

Then when invoking a dialog like so, you need to pass the boilerplate wrapper + your component you want like so:
```js
import slotComponent from '~components/atom/mybutton.vue'

this.$q.dialog({
  component: boilerplateWrapper,
  parent: this,
  slotComponent,
})
```
Depending on the events you listen to on the slotComponent from inside the boilerplate wrapper, you can even still pass events through `Ok()` etc.

### Request

I bet that all people who use custom components inside Dialogs might find such a possibility useful.

So I thought it might be good if Quasar could officially integrate something similar. Have the boilerplate wrapper component already attached by default, so the dev's "component" can just be a standalone component.

**Comment by holtalanm** [comment]
kind of related, but I was able to extract away the boilerplate in my project by using a component mixin.  Made the custom dialog components a lot cleaner.

**Comment by mesqueeb** [comment]
@holtalanm Yes me too, however, each component still needs to be wrapped into a `<q-dialog />`.
So say you have a bunch of atoms like buttons, sliders, inputs, they can't be easily used inside a Dialog, because you need to have an extra `<q-dialog />` around them.

My full implemented dialog wrapper so you can easily show ANY component inside a dialog is as follows.
These are the props you can pass when triggering the Dialog via plugin:

-    showCloseButton
-    dialogProps
-    slotComponent
-    slotProps
-    slotEvents

```html
<template>
<q-dialog ref="dialog" @hide="onDialogHide()" v-bind="dialogProps">
  <div class="d-wrapper">
    <component
      :is="slotComponent"
      v-bind="slotProps"
      v-on="slotEvents"
    />
    <q-btn
      v-if="showCloseButton"
      @click="hide"
      class="_close"
      icon="close"
      color="primary"
      size="lg"
      flat
    />
  </div>
</q-dialog>
</template>

<style lang="sass" scoped>
// $

.d-wrapper
  position: relative
  background: white
  +pa-lg
  min-width: 50vw
  ._close
    position: absolute
    top: 0
    right: 0

</style>

<script>
import QDialogMethods from '~mixins/QDialogMethods'

export default {
  name: 'DWrapper',
  mixins: [ QDialogMethods ],
  props: {
    showCloseButton: {
      desc: 'Display a generic `✗` close button on the top-right.',
      type: Boolean,
      default: true,
    },
    dialogProps: {
      desc: 'The props that will be bound to the dialog component (with `v-bind="dialogProps"`)',
      type: Object,
    },
    slotComponent: {
      desc: 'The component to show in the dialog. Can be a direct Vue component instance or a string with the component name (if registered).',
      type: undefined,
    },
    slotProps: {
      desc: 'The props that will be bound to the slot component (with `v-bind="slotProps"`)',
      type: Object,
    },
    slotEvents: {
      desc: 'The events that will be listened to, on the slot component (with `v-on="slotEvents"`)',
      type: Object,
    },
  },
  data () {
    return {}
  },
  computed: {},
  methods: {},
}
</script>

```

The mixin called `QDialogMethods` above has the required logic as per the Quasar Dialog plugin documentation.

**Comment by rstoenescu** [comment]
How about making it dead simple (with no breaking changes and support for the current API too):

```vue
<template>
  <q-dialog>
    <q-card>
      <q-card-section>Weee</q-card-section>

      <!-- buttons example -->
      <q-card-actions align="right">
        <q-btn color="primary" label="OK" @click="onOKClick" />
        <q-btn color="primary" label="Cancel" v-close-popup />
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

<script>
export default {
  props: {
    // ...your custom props
  },

  methods: {
    onOKClick () {
      // emit "ok" event (with optional payload)
      // to trigger the Dialog plugin onOK() method
      // otherwise onCancel() will be called
      this.$emit('ok')
      // or with payload: this.$emit('ok', { ... })
    }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Sorry. Turned this upside down but there's no feasible way to cover all possible use-cases.
