### ISSUE TITLE
EnableHttpsSelfSigned.enable prevents Capacitor plugins from working

### ISSUE THREAD

**Issue by jcesarmobile** [quasarframework/quasar#5823]
If `EnableHttpsSelfSigned.enable(findViewById(R.id.webview));` is present in `MainActivity.java`, it will prevent Capacitor native plugins from working, since `EnableHttpsSelfSigned` class overrides the `WebViewClient` that Capacitor uses to inject the javascript that makes plugins work.

**Comment by nklayman** [comment]
I'm not sure how to get around this one, as I don't know any other way of ignoring ssl errors. We might have to make a pr to capacitor that adds the option to ignore ssl errors.

**Comment by nklayman** [comment]
PR here: https://github.com/ionic-team/capacitor/pull/2271.

**Comment by rstoenescu** [comment]
The suggested changes will be shipped with "@quasar/app" v2. A big "thank you!" from Quasar team for guiding us.
