### ISSUE TITLE
Capacitor using EnableHttpsSelfSigned even if https is not set on the devServer

### ISSUE THREAD

**Issue by jcesarmobile** [quasarframework/quasar#5824]
All Capacitor apps include `EnableHttpsSelfSigned.enable` even if https is not set on the devServer  which causes issues with Capacitor plugins when running with dev command. (see https://github.com/quasarframework/quasar/issues/5823 for more information about that).

And when using build command, Capacitor just don't load since the Capacitor WebViewClient can't intercept the WebView requests and will fail to load the app because of that.

This "hack" should only be enabled if https is set in the devServer and never if build command is used.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting and congrats on your first Quasar PR!
Good work. Looking forward to more contributions!

This will go into "@quasar/app" v1.3.4.
