### ISSUE TITLE
Wrong QSpinner animation when using SASS and RTL

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#5826]
Today I switched my Quasar V1 app from Stylus to SASS and noticed this problem. This is exactly the same issue as #3736. This can easily be reproduced when a new SASS project is in RTL mode. 

The only difference from #3736 is that the problem is both in `dev` and `build` versions.

tested on quasar `v1.5.5` and `@quasar/app v1.3.3`

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.5.8.

**Comment by rstoenescu** [comment]
Will require "quasar" v1.5.8 AND "@quasar/app" v1.3.6.
