### ISSUE TITLE
Remove Vue dependency from date utils

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5827]
**Is your feature request related to a problem? Please describe.**
After trying to write isolated tests for functions only using Quasar Date utils, I found out through the setup that the **Quasar Date utils have Vue as a non-treeshakable dependency.**

**Describe the solution you'd like**
I'd love the date utils to be importable in any project without requiring Vue at all.
If a project doesn't use Vue, writing:
```js
import { date } from 'quasar'
const { formatDate, adjustDate } = date
```
Will also have/require Vue to be in the final bundle.

**Describe alternatives you've considered**
Use another date utils package.

**Additional context**
Date utils import `lang.js` which in turn has this single line which uses Vue:
https://github.com/quasarframework/quasar/blob/dev/ui/src/lang.js#L43

I just wonder if this can be re-written in a way that the date utils don't require that line?
Because they don't execute `lang.set` anyway, so it should be able to be refactored so they don't import the `this.set` function.

**Comment by mesqueeb** [comment]
I think something like
```js
export const langInstance = {/* existing code ... */}
export const set = (lang, _langInstance) => {/* just the set function extracted */}

export default {
  ...langInstance,
  set
}
```
i'm not sure but I think that would have no changes to existing functionality while making it possible to import _just_ `langInstance` without the Vue dependency.

**Comment by rstoenescu** [comment]
Hi,

I fail to see the reasoning here. The date utils is meant for Quasar devs, which obviously will be using Vue... This util is not meant as a standalone package...
