### ISSUE TITLE
Introduce styles for "active" QItem when QList is in dark mode

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#5830]
Currently there are no default styles for active QItems when QList is in dark mode.

https://github.com/quasarframework/quasar/blob/dev/ui/src/components/item/QItem.sass#L118

**Comment by pdanpdan** [comment]
There are the same defaults, and they look good on dark mode too.
And you can customize the active class if you want.

**Comment by rstoenescu** [comment]
If the active class prop is not enough (it should!), then worth mentioning: https://quasar.dev/style/dark-mode#How-to-style-your-app and also how to get global status so that you can apply different classes based on dark or light mode `:some-prop="$q.dark.isActive ? 'dark-class' : 'light-class'"`.
