### ISSUE TITLE
color.setBrand not working as stylus variable

### ISSUE THREAD

**Issue by NicoP-S** [quasarframework/quasar#5831]
Hi,

i'm trying to set the brand colors dynamic with [Dynamic-Theme-Colors](https://quasar.dev/style/color-palette#Dynamic-Change-of-Brand-Colors-(Dynamic-Theme-Colors))
`colors.setBrand('accent','red')`

It's working well for components. But if I [use it in stylus](https://quasar.dev/style/color-palette#Using-Sass%2FSCSS%2FStylus-Variables) variables it's not working:

```
<style lang="stylus">
.border {
  border: 1px solid $accent;
}
</style>
```
This still loads the default color from quasar.variables.styl

Is this a bug or is there a other way to get this working?
Quasar v1.5.7

**Comment by rstoenescu** [comment]
Hi,

The 'setBrand()' method updates the equivalent [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), so you'd need to use it accordingly.
The compiled Stylus variables can never be changed on the fly.

```stylus
.border
  border 1px solid var(--q-color-accent)
```

**Comment by anpabupa** [comment]
If I want to change the opacity of the color, what should I do
such as background:lighten($accent,50)
You can't write it this way background:lighten(var(--q-color-accent),50)

**Comment by rstoenescu** [comment]
Use getBrand() + lighten() https://quasar.dev/quasar-utils/color-utils
