### ISSUE TITLE
QEditor scrolls to the top on scrollable content when selecting something in dropdown menu on toolbar.

### ISSUE THREAD

**Issue by TheCheat** [quasarframework/quasar#5833]
**Describe the bug**
When selecting text at the bottom scroll position of editable div in QEditor and then selecting something in toolbar within dropdown menu like Font Size or Font Family, it scrolls you to the top of the scrollbar while selection is still active.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/iwan-firago/pen/VwYebeg?&editable=true&editors=101

**To Reproduce**
1. Go to codepen
2. Scroll down to "edit this"
3. Click on 'Font Size' -> 'Big'
4. You'll get scrolled to the top

**Expected behavior**
To stay at the same scroll position as before applying formatting.

**Platform (please complete the following information):**
OS: Debian Linux
Node: 10.17.0
NPM: 6.11.3
Yarn: 1.19.2
Pkg quasar: v1.5.2
Pkg @quasar/app: v1.2.4
Browsers: Chrome 78.0.3904.108 (Official Build) (64-bit)

**Comment by TheCheat** [comment]
Also. I found out that it scrolls you to the top only when you click on text in dropdown menu. Icon works fine though.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.8

**Comment by TheCheat** [comment]
> Fix will be available in "quasar" v1.5.8

The bug still persists in 1.5.9:
https://codepen.io/iwan-firago/pen/VwYebeg?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.10. Tested thoroughly.
