### ISSUE TITLE
@quasar/app v1.3.5 breaks webpack code splitting

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#5836]
When building a SPA project with `@quasar/app v1.3.5` all chunks are added to vendor file.
Here is how to reproduce the problem:
in a newly created quasar project run `yarn add xlsx` and add following code to `Error404.vue`:

``` js
methods:{
    test: async function(){
       const XLSX = await import(/* webpackChunkName: "xlsx" */ 'xlsx')
       return XLSX.version
    }
  }
```
now run `quasar build`. here is what I have with two different versions of `@quasar/app`:

```

Build mode........ spa
Pkg quasar........ v1.5.5
Pkg @quasar/app... v1.3.3
Debugging......... no
Publishing........ no


js/076faf7a.6f3f2faf.js    485 KiB  076faf7a  [emitted] [immutable]
js/2d0e8be2.a4d6639e.js  544 bytes  2d0e8be2  [emitted] [immutable]
js/2d22c0ff.11a03bab.js   3.02 KiB  2d22c0ff  [emitted] [immutable]
js/4b47640d.88e89fb6.js   12.4 KiB  4b47640d  [emitted] [immutable]
js/app.9543f6cb.js   1.36 KiB       app  [emitted] [immutable]  app
js/runtime.b77053da.js   2.35 KiB   runtime  [emitted] [immutable]  runtime
js/vendor.59948947.js    151 KiB    vendor  [emitted] [immutable]  vendor
js/xlsx.f887effd.js    922 KiB      xlsx  [emitted] [immutable]  xlsx

```
As you can see `xlsx` chund is correctly generated. now with `@quasar/app v1.3.5` :

```

Build mode........ spa
Pkg quasar........ v1.5.7
Pkg @quasar/app... v1.3.5
Debugging......... no
Publishing........ no

js/2d0e8be2.f2df23b4.js  552 bytes  2d0e8be2  [emitted] [immutable]
js/2d22c0ff.95887667.js   3.14 KiB  2d22c0ff  [emitted] [immutable]
js/4b47640d.fe6247aa.js   12.4 KiB  4b47640d  [emitted] [immutable]
js/app.2b4866ac.js   1.35 KiB       app  [emitted] [immutable]  app
js/runtime.da05fae9.js   2.33 KiB   runtime  [emitted] [immutable]  runtime
js/vendor.15d5e6ad.js    1.1 MiB    vendor  [emitted] [immutable]  vendor
js/xlsx.d5c4a87e.js  120 bytes      xlsx  [emitted] [immutable]  xlsx

```
`xslx` chunk file is created but all the js is injected in the `vendor` file.

**Comment by rstoenescu** [comment]
This is the correct behavior.
Everything from node_modules goes into the vendor chunk. Except if you choose otherwise through quasar.conf.js > vendor > add/remove --> https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-vendor

**Comment by behnoodk** [comment]
Thank you for your answer. I am however confused. So the behavior up until `v1.3.5` was incorrect?

I added following code to `quasar.conf.js` and build the project and the output is not changed and still all code are injected into vendor.js.

``` js


module.exports = function (ctx) {
  return {
    vendor: {
      remove: ['xlsx']
    },
...

```

What I am trying to achieve here is to separate the `xlsx` as a different chunk because it is huge in size and is only used in a few of my pages. The behavior before v1.3.5 was exactly what one would expect when reading the docs on https://webpack.js.org/guides/code-splitting/#dynamic-imports 

I'd appreciate it if you can point out to me what I'm doing wrong that still xlsx code is being injected in vendor file.

I think what I'm trying to ask is that how can one achieve proper code splitting when using quasar cli. Thank you.

**Comment by freddy38510** [comment]
I'm facing the same issue than @behnoodk since [this commit](https://github.com/quasarframework/quasar/commit/edd7258178af05edfb84b51891cfde08756ebfb2#diff-f241fa28405448aea9e872a23ce2a0cdR256)

Adding chunk to the remove array in vendor property doesn't separate the chunk from vendor file.

**Comment by freddy38510** [comment]
A quick workaround for you @behnoodk,
Use this in your `quasar.conf.js`:

```javascript
chainWebpack (chain) {
    chain.optimization.get('splitChunks').cacheGroups.vendors.chunks = 'initial'
}
```
If i let `all` instead of `initial` my dynamics imports of Quasar components are included in vendor chunk. I could remove them like it was suggested by @rstoenescu, but some modules needed by these components are not removed from the vendor chunk.

I made a [PR](https://github.com/quasarframework/quasar/pull/5838) to fix add/remove modules into the vendor chunk.

**Comment by rstoenescu** [comment]
@freddy38510 Thanks for the PR and welcome to the list of Quasar contributors!

@freddy38510 @behnoodk Don't change cacheGroups.vendors.chunks to 'initial', especially if you are using import: 'auto', as this will duplicate Quasar source code. Please hold tight for the next "@quasar/app" release (to come today).

Thanks for this thread. It made Quasar better.

**Comment by freddy38510** [comment]
@rstoenescu Thanks you, i really appreciate how this framework is clean and performant.

I have a special use-case, i disabled auto import and manually importing Quasar components in my app. I hoped that dynamically (and lazy loaded) imported Quasar components would be in a separate chunk, but that's not the case with cacheGroups.vendors.chunks to 'all'

I'm looking for a better way to separate them from vendor chunk than a RegExp. Because others Quasar components/mixins/directives imported in these Quasar components (and not needed elsewhere in my app) are not separated from the vendor chunk.

Ps: sorry for my bad English

**Comment by freddy38510** [comment]
@behnoodk i found a solution, i made an [issue ](https://github.com/quasarframework/quasar/issues/5866) for that with all explanations.

For now, you can put this in your quasar.conf.js file:

```javascript
// quasar.conf.js

module.exports = function (ctx) {
  return {
    // ...

    chainWebpack (chain) {
        chain.optimization.get('splitChunks').cacheGroups.vendors.name = (_module, chunks) => {
          const allChunksNames = chunks.map((item) => item.name).join('~')
          if (allChunksNames) return 'vendor'
          else return !ctx.prod
        }
      }

    // ...
  }
}
```

**Comment by behnoodk** [comment]
@freddy38510 Thank you! although my webpack knowledge is minimal, I'll give it this a try 😃

**Comment by freddy38510** [comment]
@behnoodk 
Just to clarify some things, for your use-case it could be better to just use quasar.conf.js -> vendor config.

But if for some reasons you prefer to "tweak" webpack i made an error with my previous code by not considering a dev build.

It should be better like this:

```javascript
// quasar.conf.js

module.exports = function (ctx) {
  return {
    // ...
    
    if(ctx.prod) {
      chainWebpack (chain) {
        chain.optimization.get('splitChunks').cacheGroups.vendors.name = (_module, chunks) => {
          const allChunksNames = chunks.map((item) => item.name).join('~')
          if (allChunksNames) return 'vendor'
          else return false
        }
      }
    }

    // ...
  }
}
```
