### ISSUE TITLE
Allow framework for not use q-* components and styles

### ISSUE THREAD

**Issue by Czako** [quasarframework/quasar#5837]
**Is your feature request related to a problem? Please describe.**
Quasar should allow to remove/disable styles and q-* components. In our app we write our own components with fit and lightweight solutions. We need to disable the styling for tree shaking purposes.

**Describe the solution you'd like**
This feature should be configurable in quasar.conf.js as parameter in `framework: { disableComponentsAndStyling: true }` (default false). This will disable import of sass/stylus default css and quasar components

**Describe alternatives you've considered**
We are manually removing the css code from `/node_modules/quasar/dist/quasar.sass`. Another option is to do it with `purgecss-webpack-plugin` (https://www.npmjs.com/package/purgecss-webpack-plugin)

**Comment by pdanpdan** [comment]
Please use the alternatives.

**Comment by rstoenescu** [comment]
It doesn't makes sense to use Quasar CLI if you're not using Quasar UI...

**Comment by Czako** [comment]
I’m only use quasar for ssr and cordova support

**Comment by DetectiveHuman** [comment]
> It doesn't makes sense to use Quasar CLI if you're not using Quasar UI...

It makes perfect sense, some of us use it for SSR.



> Please use the alternatives.
We can't find any other alternatives as good as Quasar.
