### ISSUE TITLE
QEditor Link - ability to add target="_blank"

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#5840]
**Is your feature request related to a problem? Please describe.**
I use the QEditor to edit content on my site, having the links open in new tabs is very important because I don't want my users to be directed away from my site. 

**Describe the solution you'd like**
I would like some option in QEditor to make the <a> tags have the attribute target="_blank" by default when creating links. 

**Describe alternatives you've considered**
There could also be a toggle/checkbox seen after clicking the Hyperlink button in the Editor which sets this attribute.

**Comment by pdanpdan** [comment]
Sorry, execCommand that is used to create link does not support target setting.
QEditor is just for basic HTML editing requirements. If you need more extensive HTML support please use a full editor, there are some great ones, but they are a lifetime job in themselves :).

**Comment by darkclip** [comment]
@pdanpdan actually, if use 'insertHTML' instead of 'createLink', you could add anything.
