### ISSUE TITLE
QMenu: Closes on click hold

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar#5842]
**Describe the bug**
QMenu closes if you click -> hold -> move mouse out of menu. I noticed this while selecting a color value from QColor header. Is think this is not intended. A menu usually don't close in this case.

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
1. open QMenu
2. Click and hold a QItem
3. Move mouse out of QMenu
4. Release click hold

**Expected behavior**
QMenu should stay open

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers: Chrome 78
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Mouse click action is performed when you release the mouse button, on the element the cursor is over in that moment, so this is the expected behavior.
