### ISSUE TITLE
Improve date checking

### ISSUE THREAD

**Issue by digulla** [quasarframework/quasar#5844]
This is related to the comments on this PR: https://github.com/quasarframework/quasar/pull/4666

I would like to suggest a new validation API which allows to register arbitrary JavaScript functions to validate input fields. The function should get a callback which it can call for any detected problems plus it should return boolean `true` when the validation succeeds. Anything else should be considered as "invalid" which would allow for this code:

    function dateValidation(value, invalid) {
        if (hasYear(value)) {
            return invalid("Missing year");
        }

        return true;
    }

The default implementation for dates can then use the existing regexp. If someone has different needs, they can quickly replace the default validation.

The callback should accept a string argument, an error message.
The default implementation should add a marker to the affected input element (red "!" or something) with a tooltip that contains the error message.

Alternatively, the error message can be displayed in a smaller red font below the input element.

**Comment by pdanpdan** [comment]
You can already use internal or external validation using custom functions:
- https://quasar.dev/vue-components/input#Validation
- https://quasar.dev/vue-components/input#External-validation
