### ISSUE TITLE
[Request] Ability to overwrite VueRouterBase from quasar.conf.js

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#5845]
**Is your feature request related to a problem? Please describe.**
I can update the publicPath which updates all my assets to their CDN urls, but it also updates VueRouterBase url to use the CDN URL which throws security errors and prevents the app from rendering.

**Describe the solution you'd like**
Add `vueRouterBase` to `quasar.conf.js` inside `build`

**Describe alternatives you've considered**
I tried overriding it in router/index.js too and it still kept the same url as the publicPath override.
Also changing the `process.env.VUE_ROUTER_BASE` in `quasar.conf.js` does not appear to work either.

**Comment by rstoenescu** [comment]
Will be available in "@quasar/app" v1.4.2.

You can already change it by overwriting the `base: process.env.VUE_ROUTER_BASE` line with your desired value :) But added quasar.conf.js > build > vueRouterBase in "@quasar/app" v1.4.2.

I've seen people wanting to change app base and the router base often, but I cannot stress enough that changing any of these will most likely break your app completely. Be sure that you really want this...
