### ISSUE TITLE
Cordova dev starts emulator before build is completed

### ISSUE THREAD

**Issue by outofmemoryagain** [quasarframework/quasar#5847]
When running on a project with a lengthy build (Typescript)
`quasar dev -m android` or `quasar dev -m ios` 

The iOS or anrdoid emulator is started before the bundle is deployed and which cause the emulator to have an error.  For iOS the app must be restarted to be able to debug, for Android swtiching between apps sometimes get the app to refresh and the debugger to properly load.

**To Reproduce**
1. Create a cordova project
2. Add Typescript extension, `quasar ext add @quasar/typescript`
3. Run `quasar dev -m android`
4. Emulator is started and the App is attempted to be opened while the build is still running.
5. The following errors is displayed:
"Application Error: net:: ERR_CONNECTION_REFUSED"

**Expected behavior**
...
4. Quasar build completes
5. App is started in emulator
6. App starts without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/16638153/70540525-0a629d00-1b2b-11ea-9f90-3e2ed86003a9.png)

**Platform (please complete the following information):**
OS: MacOS (Catalina) and Windows 10
Node: v12.12.0
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Comment by outofmemoryagain** [comment]
Additional reports of the issue:
* [Cordova discord channel](https://discordapp.com/channels/415874313728688138/596276082458492929/651560504099209231)
* [Capacitor discord channel](https://discordapp.com/channels/415874313728688138/631888733863411715/653963722515152906)

**Comment by pdanpdan** [comment]
Can you please upgrade to the latest app version (v1.3.7) and check if it's fixed?

**Comment by outofmemoryagain** [comment]
Verified the issue is resolved on both iOS and Android.
