### ISSUE TITLE
Pointer cursor for clickable table row

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#5849]
The QTable component exposes a `row-click` event, however the row itself is not showing a pointer cursor, hereby inhibiting clear user interaction.

The entire table body could be put in a slot and then the `.cursor-pointer` class could be assigned to QTr, but it seems odd that the class isn't attached automatically when the click event is already available. Modding the entire body slot seems cumbersome when I only want to attach the pointer class...

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.5.9

**Comment by Propaganistas** [comment]
Great, thanks!
