### ISSUE TITLE
[Request] Add a val attribute to q-checkbox 

### ISSUE THREAD

**Issue by makiten** [quasarframework/quasar#585]
[See also quasar-framework.org - #122](https://github.com/quasarframework/quasar-framework.org/issues/122).

I design e-learning software that has quizzes where multiple answers could be selected at once. It's possible to allow for multiple checkboxes selected and check their values in Vue, but it's not with `q-checkbox`.

Right now, my workaround would be to gather values with `q-select`, but this adds an additional step for the user, and it may seem unintuitive since `q-radio` already has a `val` attribute. Allowing `q-checkbox` to take a value can make processing the form submissions easier, because there's no longer a roundabout method of evaluating the value of the checkbox.

**Comment by rstoenescu** [comment]
Hi,

The concept of a checkbox is to be able to handle 2 states: checked and unchecked, so a boolean is the default choice as model for it.

In future v0.14 however there's already a `val` attribute which when used, transforms the checkbox's model into an array. For example you can have N checkboxes binded to the same model:
```html
<q-checkbox v-model="myModel" val="John" />
<q-checkbox v-model="myModel" val="Jack" />
<q-checkbox v-model="myModel" val="Jim" />
```
If user checks first two, the model will be ['John', 'Jack']. If it unchecks first, then ['Jack']. If it unchecks all, then model is an empty [].

I think that this is what you are looking. Gonna close the issue but feel free to reopen if I missed something.
Thanks for reporting this so others can see it too.
