### ISSUE TITLE
q-tooltip persists when hovered button goes disabled on Chrome

### ISSUE THREAD

**Issue by holtalanm** [quasarframework/quasar#5851]
**Describe the bug**
This specifically happens on Google Chrome and Chromium-based browsers.  Tooltip works as expected on Firefox.

When you have a button with a tooltip, that when clicked causes the button to go into a disabled state, on Chrome the tooltip stays around.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/holtalanm/pen/povyyKw?editors=1010

**To Reproduce**
1. In Google Chrome, or a Chromium-based browser, click on the button within the CodePen.
2. Note that the tooltip sticks around.
3. In Firefox, click on the button within the CodePen.
4. Note that the tooltip disappears as expected.

**Expected behavior**
The tooltip should disappear when the button is no longer hovered, regardless of disabled state.

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Edge Chromium (79.0.309.43), Chrome (78.0.3804.108), Firefox (71.0)

**Comment by holtalanm** [comment]
workaround:  use a `v-if` on the tooltip:   https://codepen.io/holtalanm/pen/povybzp?editors=1010

**Comment by pdanpdan** [comment]
Yes, there is not much we can do about this. Chrome (and new Edge, and I think old Edge also) do not respond to any mouse event on an disabled `<button>`.

If you don't need a '<button>' (as in tag) you can add `type="a"` to the QBtn or use v-if as suggested above.
