### ISSUE TITLE
Notification actions are fuchsia

### ISSUE THREAD

**Issue by gruppler** [quasarframework/quasar#5857]
**Describe the bug**
On line 4598 of quasar.styl, the class `.q-notification__actions` is assigned color `#c581ff` for no apparent reason.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gruppler/pen/jOEqZqW

**To Reproduce**
1. Create a notification with actions, but don't assign a color to the actions
2. Observe the color of the actions

**Expected behavior**
Inherit the color from the text.

**Comment by pdanpdan** [comment]
It must be a color other than the main color of text, and only the dev can pick his desired color.

You can override it in:
- defaults for notification actions
- definition of the actions passed to Notify
- CSS

**Comment by rstoenescu** [comment]
This was the advertised color on Material Guidelines, along with the default darkish bg.
