### ISSUE TITLE
Cross-Site Scripting audit message since 1.5.8

### ISSUE THREAD

**Issue by zachmanpro** [quasarframework/quasar#5858]
**Describe the bug**
after upgrading to 1.5.8 cause audit warning  https://www.npmjs.com/advisories/1426 (Cross-Site Scripting) on package  **serialize-javascript** recommended action to upgrade to >=2.1.1 

**To Reproduce**
Run upgrade command to update to 1.5.8

**Comment by rstoenescu** [comment]
This is not related to the Quasar UI package.
It's a deep dependency of "@quasar/app" package, and that dep has recently been fixed. So latest version of "@quasar/app" has upgraded it -- which you need to do too (latest "@quasar/app" atm is v1.3.7).

**Comment by ibrainventures** [comment]
Still alive or back in 1.4.0 .. getting now the audit message ..

**Comment by rstoenescu** [comment]
Seems like not all the underlying packages have yet upgraded the affected version of serialize-javascript. This is out of Quasar's reach, but will release a new version of "@quasar/app" once everything is fixed upstream. As a small comment, this package does not gets into the app UI code so there's no security threat actually.
