### ISSUE TITLE
[Request] QTree - more customization options - avoid showing connector lines

### ISSUE THREAD

**Issue by drank** [quasarframework/quasar#5860]
The `QTree` component is great but currently I am missing the following options:

- ability to customize the expansion icon, e.g. swap the default ones with `+` and `-`
- ability to remove the guiding lines (the vertical and angled lines to the left of the items)

The expansion icon is easily customizable in `QExpansionItem` (`expand-icon` and `expanded-icon` props), so to have some consistency b/w components it would be nice to be able to do the same in `QTree`. Vuetify, for example, is able to change the icon - https://vuetifyjs.com/en/components/treeview#custom-selectable-icons

It would also be nice to be able to disable the guiding lines - I need a tree that does not display them and indicates hierarchy based solely on indentation. I can disable the lines via CSS but this feels like a hack and IMHO should be an option of the component.

**Comment by drank** [comment]
OK, my bad regarding the icon - I missed the `icon` prop on QTree - which does exactly what I want.

The request for the lines remains though :)

**Comment by rstoenescu** [comment]
Hi,

QTree new Boolean prop ("no-connectors") will be available in "quasar" v1.5.10.

**Comment by drank** [comment]
@rstoenescu , thank you very much!
