### ISSUE TITLE
stacked label/icon stepper

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5862]
**Describe the feature you'd like**

A "stacked" label/icon stepper like so:
(from design mock)
<img width="972" alt="image" src="https://user-images.githubusercontent.com/3253920/70604147-746a6780-1c3b-11ea-92d0-e5216ea17214.png">

**Describe alternatives you've considered**
I was able to create this with the Quasar stepper just by adjusting the CSS:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/3253920/70624170-0fc30300-1c63-11ea-9fdf-38cadf1cd660.png">

I'm currently implementing it, with the following CSS:
```sass
.q-stepper--horizontal
    .q-stepper__tab
        flex-direction: column !important
        justify-content: center !important
        &:after, &:before
            content: ''
            position: absolute
            top: 33%
            height: 1px
            background: rgba(0, 0, 0, 0.12)
            z-index: 0
        &:before
            left: 0
            right: 50%
        &:after
            left: 50%
            right: 0
        &:first-child:before
            display: none
        &:last-child:after
            display: none
        .q-stepper__dot
            margin: 0
            margin-bottom: 0.5em
            z-index: 1
    .q-stepper__label:after, .q-stepper__dot:after
        display: none
    .q-stepper__line:before, .q-stepper__line:after
        display: none
```

**Additional context**
I'd love support for this!
Let me know if I can help with the PR. I might need a little bit of direction, example:
> "you can make a PR.
> try to do it via a dynamic class and then provide the css for that class in the stepper sass file"

Or something, then I can figure out the rest. 😉

**Comment by rstoenescu** [comment]
https://quasar.dev/vue-components/stepper#Example--Alternative-labels

**Comment by mesqueeb** [comment]
Oh this is embarrassing!! While I did search for it in the api, I must have overlooked this !!!
Thanks !!
