### ISSUE TITLE
Setting config build.publicPath in quasar.conf.js mode SSR

### ISSUE THREAD

**Issue by kororo** [quasarframework/quasar#5865]
**Describe the bug**
I am trying to deploy Quasar framework to Serverless Framework. There is default requirement in AWS Lambda to have prefix of stage for every URLs such as:
/dev/
/prod/

This means, all the paths such as JS, CSS need to have prefix URI (/dev/ or /prod/) this also include the
<base href=/dev/>

This leads to settings publicPath as described in [here](https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build)

Settings the publicPath will be ignored due to snippet in the file **node_modules/@quasar/app/lib/quasar-config.js**
```
if (this.ctx.mode.ssr) {
      Object.assign(cfg.build, {
        vueRouterMode: 'history',
        publicPath: '/',  // this one is the culprit
        gzip: false
      })
    }
```

I may be do something that I shouldn't be done, which, safeguard code to prevent some silly config, which I do recommend to add big warning message rather than silent overrides like Object.assign. It does drives me nuts when the settings seems does nothing.

However, let me know how to set publicPath so I can control how to render the assets.

Apologies, I don't have any codepen to do this. If you have documentation on how to deploy Quasar to Serverless Framework, please do let me know. Otherwise, I can make PR to have one. It took me bit time to do this.

Thanks for Allan for helping me debug some stuffs in this problem @webnoob

**Comment by kororo** [comment]
Silly me, I forgot to add the environment
Build mode........ ssr
 Pkg quasar........ v1.5.8
 Pkg @quasar/app... v1.3.7
 Debugging......... no
 Publishing........ no

```
node -v
8.15.1

npm -v
6.9.0

# executed with
quasar build -m ssr
```

**Comment by rossity** [comment]
I believe you and I may be experiencing similar issues as I'm trying to go the serverless approach as well.

My issue is here https://github.com/quasarframework/quasar/issues/5845

**Comment by kororo** [comment]
@rossity, yeah same, i am doing the serverless framework to do. i have working one now. thinking to create PR for the documentation.

**Comment by webnoob** [comment]
@kororo Are you doing a docs PR for this? It would be appreciated so we can get this ticket closed down.

**Comment by pdanpdan** [comment]
https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build - check `appBase` and `vueRouterBase` - but don't cry if it breaks the app :)

**Comment by kororo** [comment]
@pdanpdan thanks for the suggestion. Actually SSR not in the root path is wrong approach.

In my specific requirements, I changed so that SSR now viewable in root path. The AWS lambda currently has requirement to always have subpath of the environment stage such as (/dev/ or /prod/) however this can be mitigated using custom domain based on the API gateway.

Hence, I am closing this ticket.

@webnoob thanks for the help. Going to cancel the documentation. I am switching to different approach now, not using quasar or Vue.

Thanks everyone!
