### ISSUE TITLE
Add possibility to exclude optional dependencies from production build process

### ISSUE THREAD

**Issue by endymonium** [quasarframework/quasar#5868]
**Is your feature request related to a problem? Please describe.**
A package I'm using has an optional depency to `opencv`, which is a rather big native module with a long compile time. I don't need it and would like to exclude it.

**Describe the solution you'd like**
Generic solution would be to be able to add custom parameters to the underlaying npm/yarn command of `quasar build`, this would allow for adding the  `--no-optional` (npm)/ `--ignore-optional` (yarn) switch.

Adding `--no-optional` to https://github.com/quasarframework/quasar/blob/df4688eb74656993bd30e0e659e5ae44a069b045/app/lib/electron/index.js#L75 locally solved it for me.

**Comment by pdanpdan** [comment]
There might be a simple solution to this (if npm/yarn works :) ):

- remove `node_modules` and `yarn.lock` / `package-lock.json`
- execute `npm i --no-optional` / `yarn --ignore-optional` that should create the lock file without optional
- execute `quasar build ...` - hopefully this will use the lock files as source

related:
- https://unix.stackexchange.com/questions/168034/is-there-an-option-to-install-an-npm-package-without-dependencies
- https://npm.community/t/npm-install-no-optional-not-actually-filtering-optionals-in-cli-6-0-1-or-6-1-0/257/2

Please test in your case and report back, thank you.

**Comment by rstoenescu** [comment]
New param (Array) in quasar.conf.js > electron > unPackagedInstallParams will be available in "@quasar/app" v1.4.2+
