### ISSUE TITLE
select component needs label and value parameters

### ISSUE THREAD

**Issue by afilic** [quasarframework/quasar#587]
Here is what would improove SELECT component. Now, I have to rename my fields to get this component work, but this woud be much better.
```html
<q-select
  type="list"
  v-model="select"
  :options="selectOptions"
  label="comp_name"
  value="comp_id"
></q-select>
```
Thank you for this great framework.

**Comment by rstoenescu** [comment]
Hi, what exactly are you looking for? Be more specific please.

**Comment by afilic** [comment]
This is from documentation example:
```
selectOptions: [
  {
    label: 'Google',
    value: 'goog'
  },
  {
    label: 'Facebook',
    value: 'fb'
  },
  ...
]
```
My data looks like this:

```
selectOptions: [
  {
    comp_name: 'Google',
    comp_id: 'goog'
  },
  {
    comp_name: 'Facebook',
    comp_id: 'fb'
  },
  ...
]
```
I don't like to rename the fields from database. Maybe I missed something?

**Comment by rstoenescu** [comment]
I see now. What you can do is when you retrieve data use JS `.map()` to store options in the requested format.

```js
let options = selectOptions.map(opt => ({label: opt.comp_name, value: opt.comp_id}))
```

**Comment by Dmedip** [comment]
Hi, 
How can I use this for dynamic data?

**Comment by rstoenescu** [comment]
@Dmedip use a Vue computed property

**Comment by Dmedip** [comment]
@rstoenescu Thank you but how can id to that .In data instead of passing label and value (static data) how can I pass dynamic data ?
Types:
 [
         {
           label: 'fdf',
           value: 'dfd'
         }
      ],

**Comment by rstoenescu** [comment]
@Dmedip Use a Vue computed property... :|

```js
computed: {
  selectOptions () {
     return [ { label: this.myLabel, value: this.myLabelValue }, ... ]
  }
}
```

**Comment by Dmedip** [comment]
hi @rstoenescu Thank you so much fro your time,trying but still could not workout,can you please take a look at below code .I have two dropdowns and need to display data for dropdowns using computed.Please help.Thanks
<q-select
        class="full-width"
        type="radio"
        v-model="selectType"
        label="subscripName"
        :options="Types"
        ></q-select>
<q-select
        class="full-width"
        type="radio"
        v-model="selectOperation"
        :options="Operations"
        ></q-select> 

data{
Types: [],
      Operations: [],
}
computed {
}
