### ISSUE TITLE
q-input focus triggered before click on append slot

### ISSUE THREAD

**Issue by nailfar** [quasarframework/quasar#5871]
**Describe the bug**
q-input focus triggered before click on append slot
```
<q-input @focus="onfocus">
      <template v-slot:append>
        <q-icon name="close" @click="onclick" class="cursor-pointer" />
      </template>
</q-input>

onfocus(){
console.info('focus')
}
onclick(e){
console.info('click')
e.preventDefault();
e.stopPropagation();
}
```
click icon 'focus' should not print 
[https://jsfiddle.net/o7mg1b65/](url)

quasar component v1.5.8
NPM 6.9.0
OS:macOS

**Comment by pdanpdan** [comment]
The icon is inside so it should focus.
Here are some things you can check to understand: https://jsfiddle.net/zbs9k3y1/
