### ISSUE TITLE
Custom table hover/selected colors make text disappear in 1.5.9

### ISSUE THREAD

**Issue by tsulli** [quasarframework/quasar#5879]
**Describe the bug**
After upgrading to 1.5.9, text in our table rows disappears when hovered or selected if custom colors are used to override Quasar defaults in quasar.variables.*

**Codepen**
https://codesandbox.io/s/still-wave-sdnn6

**To Reproduce**
1. Set custom color values for $table-hover-background and $table-selected-background in quasar.variables.*
2. Hover or select rows in q-table and watch text disappear like magic ✨

**Expected behavior**
Text should not disappear. 

**Platform (please complete the following information):**
Chrome Windows 10, Quasar 1.5.9

**Comment by pdanpdan** [comment]
You must put a color with transparency in the variable (`$table-hover-background: rgba(255, 0, 0, 0.2)`)
