### ISSUE TITLE
Context menu not working on IOS Safari 13

### ISSUE THREAD

**Issue by gaw89** [quasarframework/quasar#5880]
I have reviewed #1858 and #4343 and they do not appear to be the same as the issue I am facing.

**Steps to reproduce:**
Using Safari on 6th generation iPad, (model # MR7F2LL/A), with IOS 13.2.3, try to long-press to open context menu.  Rather than opening a context menu, it will simply try to select any text/images that are within the target element.

It even happens in the example in the docs here: https://quasar.dev/vue-components/menu

**Solutions Attempted**
I tried adding `--webkit-touch-callout: default` to the elements with the context menu as well as to the whole html document but experienced the same issue.  I also tried adding `user-select: none` on various elements, but this didn't help.

The context menu works normally in Chrome on the same device.  It appears that Safari is the only browser that is affected.  I am using Quasar v1.5.9 and @quasar/app v1.4.0, but the issue has been present at least since v1.4.4 (the last version I was using).

Thanks for an amazing framework!!!

**Comment by pdanpdan** [comment]
Please check if Safari is in desktop mode or in normal mode.

**Comment by gaw89** [comment]
Wow.  Genius.  That was indeed the problem.  Thank you!!!

🤦‍♂
