### ISSUE TITLE
Qdate unexpectedly changes local offset

### ISSUE THREAD

**Issue by pw4rn3r** [quasarframework/quasar#5883]
**Describe the bug**

If you select a date in Qdate too far (few months) in the past or the future, the local offset changes.

**Codepen/jsFiddle/Codesandbox (required)**

https://codesandbox.io/s/quasar-qdate-issue-8vfrf

**To Reproduce**

This bug can be seen with the Qdate component with no masks or special props. The component provides a time of midnight today local time. The code sandbox linked above converts that output to ISO string format to easily see how the local offset is changed.

For instance:

- Pick 11/3/2019 (-40 days from today) --> `2019-11-03T06:00:00.000Z` (-0600)
- Pick 11/4/2019 (-39 days from today) --> `2019-11-04T07:00:00.000Z` (-0700)
- Pick 3/8/2020 (+86 days from today) --> `2020-03-08T07:00:00.000Z` (-0700)
- Pick 3/9/2020 (+87 days from today) --> `2020-03-09T06:00:00.000Z` (-0600)

You may have to adjust the dates picked depending on what day you test.  Regardless, I would expect that the behavior is consistent if you compare +/- 1 day versus +/- 90 days.

**Expected behavior**

Local offset should stay the same regardless of which date is picked.

**Platform (please complete the following information):**
Quasar: First noticed this in v1.1.4, but it is not fixed in v1.5.9
OS: Windows
Node: 10.11.0
NPM: 6.4.1
Browsers: Google Chrome 79.0.3945.79

**Comment by pdanpdan** [comment]
The offset if between the local timezones and Greenwich, at that time. You forgot about daylight saving time.
