### ISSUE TITLE
vue 2.6.11 causes errors

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#5886]
**Describe the bug**
There are errors while compiling after updating vue to 2.6.11

```
Module build failed (from ./node_modules/vue-loader/lib/index.js):
  TypeError: Cannot read property 'parseComponent' of undefined

  - parse.js:14 parse
    [@vue]/component-compiler-utils/dist/parse.js:14:23

  - index.js:67 Object.module.exports
    [vue-loader]/lib/index.js:67:22
```

**To Reproduce**
1. update `vue` to `2.6.11`
2. then run `quasar dev`

**Expected behavior**
No errors

**Platform (please complete the following information):**
OS: Win10 x64
Node: 12.13.0
NPM: 6.13.2

**Additional context**
https://github.com/vuejs/vue/releases/tag/v2.6.11
> Bump vue-server-renderer's dependency of serialize-javascript to 2.1.2

**Comment by pdanpdan** [comment]
You must upgrade `vue-loader` (and `vue-template-compiler` if you use templates) also to keep them in sync.

**Comment by matro-skin** [comment]
thanx
strange that these packages didn't be updated while `npm update`

**Comment by rstoenescu** [comment]
@matro-skin 

Do NOT manually install vue & co packages. These come along with "@quasar/app". Installing by your own can potentially blow up the stability of your app.

**Comment by matro-skin** [comment]
Should I remove all these packages from json?

**Comment by rstoenescu** [comment]
A sounding “Yes!”. And upgrade to q/app v1.4.1 which has latest vue packages anyway.

**Comment by MintyOrb** [comment]
I'm trying to upgrade to quasar 1.6.0 but struggling to get everything working properly. 

I'm not requiring any core vue or vue-loader packages in my own package.json, but I have a couple of components (necessary for my app) directly requiring Vue 2.6.11 that is causing the dev build to fail with the error: `Module build failed (from ./node_modules/vue-loader/lib/index.js):
  TypeError: Cannot read property 'parseComponent' of undefined`

Would anyone have suggestions for workarounds?

**Comment by rstoenescu** [comment]
@MintyOrb It doesn't matter. Just don't install vue yourself.

**Comment by MintyOrb** [comment]
@rstoenescu, I'm not installing vue myself...vue and associated core packages do not appear in my own package.json but the issue persists. It's the third-party components that appear to be requiring vue directly...and it isn't clear to me how to override or side-step that.

**Comment by rstoenescu** [comment]
@MintyOrb if you're using npm, try to flatten the node_modules. Recommended way to go is with yarn though.
