### ISSUE TITLE
QStepper label value not always visible

### ISSUE THREAD

**Issue by moander** [quasarframework/quasar#5891]
**Describe the bug**

The `label-value` in `q-slider` is not always visible

https://codepen.io/moanderpen/pen/xxbEWpQ

**To Reproduce**

1. Pull the slider all the way to the right

**Expected behavior**

Label should be visible to the left instead of enabling scroll in stepper.

**Screenshots**

![image](https://user-images.githubusercontent.com/380191/70855489-d0e3b600-1ecb-11ea-8ac7-854c8310455c.png)

**Comment by pdanpdan** [comment]
If you use labels on QSlider/QRange please use a horizontal margin on the element large enough to accommodate the label.

**Comment by moander** [comment]
@pdanpdan How to calculate that margin to fit the label? I have two cases, one where label comes from user input and second where the label is multi-lang.

**Comment by pdanpdan** [comment]
You can try to put a safe larger margin to account for all variants. It's not so easy.
Or you can try some custom CSS styles for the label, using the value of the slider to make the label left aligned on left and right aligned on right - something along the lines of setting a CSS variable on the slider element holding a percent to translate the label horizontally.

See this for a crude start: https://codepen.io/pdanpdan/pen/dyPNBej

**Comment by moander** [comment]
Thanks for your suggested workaround @pdanpdan but why do you close the ticket? It's still a bug, right?

**Comment by pdanpdan** [comment]
I don't consider it a bug. It's something expected and normal. @rstoenescu ?

**Comment by rstoenescu** [comment]
Let's try to improve current QSlider/QRange labels positioning.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.10.
