### ISSUE TITLE
Use ES Modules on SSR "from the box"

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#5893]
There is currently built-in support of ES Modules at Node.js. 
Can the initial src-ssr folder be built using ES Modules (perhaps with a CLI flag to set it)?

**Comment by eladcandroid** [comment]
Hi, any idea for that issue?

**Comment by rstoenescu** [comment]
It will come. You just have to be patient.

**Comment by orenSampson** [comment]
Hi, any news regarding this issue?

**Comment by hawkeye64** [comment]
I believe this has been implemented in Quasar v2 (recently)
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
