### ISSUE TITLE
Flex works differently in minimal codepen than in minimum project with layout

### ISSUE THREAD

**Issue by jtlindsey** [quasarframework/quasar#5894]
**Describe the bug**
Flex breakpoint is not working as expected. When screensize reaches small, the divs seem to break instead of stacking. In this minimal [codepen](https://codepen.io/jtlindsey/pen/QWwKoVv) it works as expected when i resize the screen. Basic code:
```
<div id="q-app">
  <div class="q-pa-md">
    <div class="row">
      <div class="col-xs-12 col-sm-4">col-4</div>
      <div class="col" style="background-color: blue">xxx beef</div>
    </div>
  </div>
</div>
```

**Codepen/jsFiddle/Codesandbox (required)**
Example that works as expected
https://codepen.io/jtlindsey/pen/QWwKoVv

I'm not sure how to reproduce issue in codepen because I need codepen to have full layout that you get from running `quasar create`. So i have step by step to reproduce below.

**To Reproduce**
1. Update to at least get latest quasar and run `quasar create example1` This gives me project with quasar `v1.5.9`
2. For options in `quasar create` choose SCSS, auto-import, features(eslint, vuex, axios, vue-i18n), airbnb lint, use NPM.
3. CD into project directory and open `src/pages/index.vue` and replace contents with following:
```
<template>
  <div class="q-pa-md">
    <div class="row">
      <div class="col-xs-12 col-sm-4">col-4</div>
      <div class="col" style="background-color: blue">xxx beef</div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PageIndex',
};
</script>

```

4. Run 'quasar dev' and resize page to see the same results as example2.gif

**Expected behavior**
Breakpoint should work as expected and as in first codepen.

**Screenshots**
Example following the steps to reproduce issue:
![example2](https://user-images.githubusercontent.com/7409277/70868419-c1598100-1f4e-11ea-8825-dbd866935fba.gif)

Expected behavior:
![example](https://user-images.githubusercontent.com/7409277/70868697-38901480-1f51-11ea-9795-8c4321403937.gif)

**Platform (please complete the following information):**
OS: Mac
Node: v12.9.1
NPM: v6.10.2
Browsers: Chrome and Safari

**Additional context**
In my project, the first div (that has `col-xs-12 col-sm-4`) will sometimes be hidden with `v-if` because it will be a area users adjust settings for the table to the right. The second div (with `background-color: blue`) is where the table will be that will be full width unless settings pane is open, or if on mobile it will be full with and settings pane will be above it. The codepen is functioning exactly as I would expect. When i use the same code in a page for the project, it doesn't work.

**Comment by pdanpdan** [comment]
It looks like it works the same way.
The difference is in the codepen you set a padding on the divs that are children of `.row`, so the second div, the one with `.col` has a minimum width of 20px and jumps on the second row.

**Comment by jtlindsey** [comment]
> It looks like it works the same way.
> The difference is in the codepen you set a padding on the divs that are children of `.row`, so the second div, the one with `.col` has a minimum width of 20px and jumps on the second row.

yes with the padding removed they both perform the same way. But the issue is adding the padding does not seem like the intended behavior requirement of the flex breakpoints in quasar.

From the docs "Auto-layout for flexbox grid columns also means you can set the width of one column and the others will automatically resize around it. You may use predefined grid classes (as shown below) or inline widths. Note that the other columns will resize no matter the width of the center column."

Can this not also work when specifying the breakpoints? Im just applying the above rule but instead of just `col-4`, i specify breakpoints like `col-md-4` and it doesn't work. Is this intended behavior?

**Comment by pdanpdan** [comment]
The minimum width of a `.col` is 0 by default, so if you have a `.col-12 + .col` the second column will stay at 0 width and not wrap below.
