### ISSUE TITLE
Add custom package icon

### ISSUE THREAD

**Issue by OnePunchMan007** [quasarframework/quasar#5897]
**Is your feature request related to a problem? Please describe.**
Quasar have limited number of iconSet and i need some icon related to business. It would be great if we have a possibility to add cutom icon package.

**Describe the solution you'd like**
The possibility to have one custom prefix that can be link to a icon set

**Describe alternatives you've considered**
this solution : 
https://forum.quasar-framework.org/topic/3196/using-a-custom-icon-font-fontello-flaticons-etc

**Additional context**

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/icon#1.-Support-for-custom-icon-library
