### ISSUE TITLE
Vue and vue-server-renderer versions mismatch

### ISSUE THREAD

**Issue by victor-alegre-santos** [quasarframework/quasar#5898]
Error serving a SSR app with @quasar/app@1.4.1 .

```
UnhandledPromiseRejectionWarning:   Error: Vue packages version mismatch:
  - vue@2.6.10
  - vue-server-renderer@2.6.11
```

It  works when building for production but not when serving in development.

**Comment by pdanpdan** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/5886 and https://github.com/quasarframework/quasar/issues/5889
