### ISSUE TITLE
Update q-icon to support a floating q-badge

### ISSUE THREAD

**Issue by stevendesu** [quasarframework/quasar#5900]
**Is your feature request related to a problem? Please describe.**
I wish to create a menu with badges over the icons, like so:

![Screenshot from 2019-12-16 18-16-10](https://user-images.githubusercontent.com/1384974/70951017-3bae0200-2030-11ea-82e7-3ac85ad1b7b5.png)

**Describe the solution you'd like**
```
<q-icon name="widget">
    <q-badge color="primary" floating>{{ count }}</q-badge>
</q-icon>
```

**Describe alternatives you've considered**
I created a `CustomIcon` component which gave me the functionality I needed. In creating the `CustomIcon` I realized there are some CSS rules which may need to be adjusted to accommodate the new component, and as I'm not intimately familiar with all of the components and design decisions of Quasar, I felt it better to leave the task to a dev deeply ingrained in the project rather than submit a pull request that breaks icons for tons of people

Here is my custom component:

```
<template>
    <div style="position: relative; display: inline-block;">
        <q-icon :name="name"></q-icon>
        <slot></slot>
    </div>
</template>

<style>
.q-item__section--side .q-icon {
    font-size: 24px;
}
</style>

<script>
export default {
    props: ["name"]
};
</script>
```

As a bonus, this also adds support for `<q-tooltip>` and any other components which expect a `position: relative` parent

**Additional context**
Take special note of the `<style>` portion of my custom component. After embedding the `<q-icon>` inside of a `<div>`, the font size changed. There's a CSS rule in Quasar like `.q-item__section--side > .q-icon`. The `>` means that this rule only applies to the `.q-icon` if it's an ***immediate** child. My component makes it a more distant child (below a `div`)

An alternative to my rule would have been `.q-item__section--side > div > .q-icon` or even applying a class to my CustomIcon and saying `.q-item__section--side > .custom-icon > .q-icon`

**Comment by metalsadman** [comment]
@stevendesu you can wrap the q-icon and q-badge in a div with class `relative-position`.

**Comment by pdanpdan** [comment]
You can put the badge directly in QIcon, you just have to add this to your app.styl/.sass

```sass
.q-icon .q-badge
  font-family: $typography-font-family
```

Example: https://codepen.io/pdanpdan/pen/PowbVyy
