### ISSUE TITLE
q-tooltip applyBoundaries error.

### ISSUE THREAD

**Issue by nailfar** [quasarframework/quasar#5902]
Tooltips does not show completely,it should to left;
 
[https://codepen.io/nailfar/pen/eYmBNpY
](url)

**Comment by pdanpdan** [comment]
What do you mean? The codepen works fine. Add full description as required, including browser, os, mode and words

**Comment by nailfar** [comment]
![image](https://user-images.githubusercontent.com/12581226/70975811-a10ffa80-20e5-11ea-8240-37dc7e458abf.png)
https://codepen.io/nailfar/pen/eYmBNpY
It is outof the boundary

**Comment by pdanpdan** [comment]
I can reproduce it on desktop, thank you.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.10.
