### ISSUE TITLE
@row-dblclick support for QTable

### ISSUE THREAD

**Issue by datadisc** [quasarframework/quasar#5905]
It would be useful to support @row-dblclick on QTable component. Sure it can be done by adding dblclick event handler on q-tr component in body slot but then you need to provide a "whole" body slot only to support this feature. For example, from my experience, the and user usually wants to view/edit row on double click - it is still very "natural". I know the double click is related to the popup editing in QTable component but sometimes is useful to edit whole record at once. QTable already supports @row-click but it is very unlikely to use that event for editing especially on desktop systems.

**Comment by rstoenescu** [comment]
Hi,

The new event will be available in "quasar" v1.5.10.

**Comment by matthiasmeier** [comment]
We use Quasar 1.6.1 and tried to implement this today on a table but it did not work. The `@row-click` event works properly, but `@row-dblclick` does not. Any tips on what we should check?

**Comment by rstoenescu** [comment]
@matthiasmeier I assure you that it is working 100%. Maybe a misunderstanding somewhere?

**Comment by matthiasmeier** [comment]
Hmm… alright, will check again and let you know if we find out something.
Thanks @rstoenescu

**Comment by matthiasmoier** [comment]
@rstoenescu I just tried to fix our issue here and figured what causes it. What we’re trying to do is accessing the `props.row.id` of the row in the `@row-dblclick` event which results in nothing happening:

```javascript
@row-dblclick="$router.push({ name: 'name-of-the-route', params: { id: props.row.id } })"
```

While debugging, I tried to replace `props.row.id` with a hard coded `id` which worked as expected:
```javascript
@row-dblclick="$router.push({ name: 'name-of-the-route', params: { id: 123 } })"
```

Any idea on how to get the desired result?

**Comment by pdanpdan** [comment]
Hello - please read the description of the `@row-dblclick` event: the handler is called with 2 parameters: evt (native click event) and row.

**Comment by rstoenescu** [comment]
@matthiasmoier 
```@row-dblclick="evt => { $router.push({ name: 'name-of-the-route', params: { id: props.row.id } }) }"```
