### ISSUE TITLE
[Infinite Scroll] reverse mode scroll bar position issue

### ISSUE THREAD

**Issue by evazc** [quasarframework/quasar#5906]
**Describe the bug**
```
// source code

if (this.reverse === true) {
      const
        scrollHeight = getScrollHeight(this.scrollContainer),
        containerHeight = height(this.scrollContainer)

      this.scrollContainer.scrollTop = scrollHeight - containerHeight
    }
```
When `this.scrollContainer === window`,  Setting `window.scrollTop` won't change the position of the scroll bar (window doesn't have scrollTop property).

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/gvszt0ao/1/

**Expected behavior**
keep the scroll bar at bottom when loading data.

**Additional context**
Please use `document.scrollingElement = scrollPosition + heightDifference` when `this.scrollContainer === window`, but don't `addEventListener` on it, it won't emit the `scroll event`.

Hope could help!

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.10.
