### ISSUE TITLE
QField: suffix positioned wrong in default slot

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#5907]
**Describe the bug**
When using QField "default" slot as per documentation, the "suffix" will be displayed _in front of_ the content.

However, when using the "control" slot, this is _not_ the case. When using "control" the suffix appear **correctly** _behind_ the content.

"control" appears to be a "scoped slot" but I'm confused about when we should add the content into the "control" or in the "default" slots...

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mesqueeb/pen/wvBggLG?&editable=true&editors=101

**Expected behavior**
default slot _should_ work like "control" slot?

**Screenshots**

<img width="442" alt="Screenshot 2019-12-18 at 17 30 34" src="https://user-images.githubusercontent.com/3253920/71069522-41d0e980-21bc-11ea-92b0-2ee8fe21680c.png">

**Comment by pdanpdan** [comment]
I see the control slot documented as the first one in the scopedSlots.
Also all examples of including a custom component use the control slot.
