### ISSUE TITLE
Mismatch in item-aligned / items-aligned in QField validation.

### ISSUE THREAD

**Issue by steersbob** [quasarframework/quasar#5908]
**Describe the bug**
QField and descendants have the styling property `item-aligned`. 

In `ui/src/components/field/QField.json` this is spelled `item-aligned`, but in `ui/src/components/field/__QField.json` it is spelled `itemS-aligned`.

Using `item-aligned` changes rendering, but causes an eslint warning (quasar/check-valid-props).

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/Kargathia/40pz2cqa/2/

**To Reproduce**
For rendering impact of nothing / `items-aligned` / `item-aligned`: see linked JSFiddle.

Steps to reproduce the linter warning:
1. Create a new quasar project
2. Enable ESLinting (extends `plugin:quasar/standard`, with plugin `quasar`)
3. Create a new Vue component
4. Add the following components to the template
```
<q-input :value="''" items-aligned></q-input>
<q-input :value="''" item-aligned></q-input>
```
5. Run ESLint
6. Get linting error on the second component
```
'item-aligned' is not a property of 'QInput'      eslint(quasar/check-valid-props)
```

**Expected behavior**
`<q-input :value="''" item-aligned></q-input>` to be aligned as QItem, and not cause any ESLint warnings. 

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: v12.13.0
NPM: 6.12.0
Yarn: N/A
Browsers: N/A
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.5.10.
