### ISSUE TITLE
[Feature] Introduce GH Actions for Core

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#5909]
**Is your feature request related to a problem? Please describe.**
I am frustrated that patch releases sometimes break existing installations. Especially when security issues are resolved, folks (like myself) who have compliance agreements (to never knowingly ship vulnerabilities of any kind in production code) can sometimes get into very critical situations where we can't ship because the toolchain has a regression. One recent example of this is what I encountered in #5904 

**Describe the solution you'd like**
At [Tauri](https://github.com/tauri-apps/tauri) we use a matrix build to not only validate core and run tests on Mac, Win and Lin, but also to build smoketests that guarantee our code changes still build on the variety of platforms we support. 

https://github.com/tauri-apps/tauri/blob/dev/.github/workflows/test-on-pr.yml

Even if this is only done once on a merge of app / cli to master in Quasar, it would go a long way to making the entire framework more trustworthy, and reduce the amount of time I regularly spend tracking obscure issues that shouldn't be happening at patch level.

Granted, Quasar has MANY more targets and flavours and edge cases - but since the only testing at the moment is manual compliance testing using the https://github.com/quasarframework/quasar/tree/dev/ui/dev folder, literally anything would be better than nothing.

And I am not saying it HAS to be GH Actions - it could be any CI. Just reporting that we at Tauri are very happy with the "free and unlimited for public repositories" service that GitHub provides.

**Describe alternatives you've considered**
- Moving to UMD (unfortunately not practical, and also just kicks the can down the road without  addressing the underlying concerns).
- Choosing another framework (also not practical, because Quasar is still best in class).

**Comment by rstoenescu** [comment]
Hi, We will consider this.

**Comment by nothingismagick** [comment]
👍

**Comment by Tofandel** [comment]
Any updates on this? Still surprised there isn't any CI tools, at least just to show the validity of PR's and commits, it takes 3 minutes to setup on github actions
