### ISSUE TITLE
run quasar dev -m electron nothing happens

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#5911]
**Describe the bug**
run quasar dev -m electron nothing happens

```md
i ｢wds｣: Project is running at http://0.0.0.0:8080/
i ｢wds｣: webpack output is served from
i ｢wds｣: 404s will fallback to /index.html
 app:electron Building main Electron process... +9s

 Renderer process █████████████████████████ [100%] in ~9s
 Main process     █████████████████████████ [100%] in ~1s

 app:electron Webpack built Electron main process +1s

Hash: 3fab292d26938bb724fd
Version: webpack 4.41.2
Time: 1376ms
Built at: 2019-12-18 5:23:56 PM
           Asset     Size         Chunks             Chunk Names
electron-main.js  221 KiB  electron-main  [emitted]  electron-main
Entrypoint electron-main = electron-main.js

WARNING in ./node_modules/electron-debug/index.js 96:45-58
Critical dependency: the request of a dependency is an expression
 @ ./src-electron/main-process/electron-main.dev.js
 @ multi ./src-electron/main-process/electron-main.dev.js

WARNING in ./node_modules/electron-debug/index.js 97:61-74
Critical dependency: the request of a dependency is an expression
 @ ./src-electron/main-process/electron-main.dev.js
 @ multi ./src-electron/main-process/electron-main.dev.js

 app:electron Booting up Electron process... +0ms
 app:spawn Running "C:\laragon\www\quasar-test-elett\node_modules\electron\dist\electron.exe --inspect=5858 C:\laragon\www\quasar-test-elett\.quasar\electron\electron-main.js" +0ms

 Debugger listening on ws://127.0.0.1:5858/3b36ecb1-aab4-4fe6-a5cd-18c2ece5ffa2
For help, see: https://nodejs.org/en/docs/inspector
```

**To Reproduce**
1. quasar create `name`
2. quasar mode add electron
3. quasar dev -m electron

**Expected behavior**
the app should open

**Quasar Info**
```md
Operating System - Windows_NT(10.0.18362) - win32/x64
NodeJs - 10.16.3

Global packages
  NPM - 6.12.0
  yarn - 1.17.3
  @quasar/cli - 1.0.3
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.5.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.1 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - 7.1.6 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 14.1.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 21.2.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.5 -- Babel compiler core.
  webpack - 4.41.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-909JHS4
  Ethernet - 192.168.1.187
```

**Additional context**
when i ran `quasar mode add electron`, there was no electron-builder or electron-packager in the package.json

```md
quasar mode add electron
 app:mode-electron Installing Electron dependencies... +0ms
 app:spawn [sync] Running "npm install --save-dev electron@^7.0.0 electron-debug@^3.0.0 electron-devtools-installer@^2.2.4 devtron@^1.4.0" +0ms


> core-js@3.5.0 postinstall C:\laragon\www\quasar-test-elect2\node_modules\global-agent\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> electron@7.1.6 postinstall C:\laragon\www\quasar-test-elect2\node_modules\electron
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ electron-devtools-installer@2.2.4
+ electron-debug@3.0.1
+ devtron@1.4.0
+ electron@7.1.6
added 76 packages from 349 contributors and audited 13842 packages in 34.48s
found 0 vulnerabilities

 app:mode-electron Creating Electron source folder... +35s
 app:mode-electron Electron support was added +16ms
```

**Comment by rstoenescu** [comment]
Hi,

The "additional context" section is correct. Adding Electron mode does not require electron-packager/builder (yet). That is installed on demand when doing an app build.

Grouping this ticket with https://github.com/quasarframework/quasar/issues/5892

**Comment by heartbeatLV** [comment]
perhaps there is a misunderstanding
when i run `quasar dev -m electron` the command does not fail but the electron app does not open

**Comment by rstoenescu** [comment]
If the Electron app remains in the background, then it's out of Quasar's control and this should be reported to the Electron team.

**Comment by hugetiny** [comment]
I met this problem too.
I think  electron-packager/builder is not necessary for developing, just for packaging.

**Comment by hugetiny** [comment]
I met this problem too.
I think  electron-packager/builder is not necessary for developing, just for packaging.
This happened when I upgraded may quasar to the latest version,here is my info
Operating System - Windows_NT(10.0.18362) - win32/x64
NodeJs - 12.12.0

Global packages
  NPM - 6.11.3
  yarn - 1.21.1
  @quasar/cli - undefined
  cordova - Not installed

Important local packages
  quasar - 1.5.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - 6.1.7 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - 21.2.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows
 and Linux with “auto update” support out of the box
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.7 -- Babel compiler core.
  webpack - 4.41.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can
 be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that
 workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-FKIU25H
  Ethernet - 192.168.31.134
  VirtualBox Host-Only Network - 169.254.124.40
  VirtualBox Host-Only Network #2 - 169.254.109.233
