### ISSUE TITLE
Using reset.css

### ISSUE THREAD

**Issue by jd-0001** [quasarframework/quasar#5912]
**Is your feature request related to a problem? Please describe.**
Recently we were discussing on how we should use/include reset.css in quasar project. The point is which is the best way/proper way to include `reset.css` in quasar. Does quasar already have reset.css added? Do we need to enable something from `quasar.conf.js`?

**Describe the solution you'd like**
It would be really great if we can just enable `reset.css` from `quasar.conf.js` file.

**Describe alternatives you've considered**
Currently we have hack which is placing reset.css in `statics/css` folder and refering this stylesheet in `index.template.html ` file

**Additional context**
If I use sass version of `reset.css` it gets intialized after quasar styles. Hence overrides quasar styles.

**Comment by rstoenescu** [comment]
Hi,

Quasar already uses a [reset/normalization css](https://github.com/quasarframework/quasar/blob/dev/ui/src/css/normalize.sass) (there's a .styl equivalent also), so there's no need to add it yourself.

Can the current version be improved? Is something important missing? If so, I'd love a PR on it.

**Comment by jd-0001** [comment]
Hi @rstoenescu Thanks for reply. Actually I didn't know about `normalize.sass`. However, some reset styles are missing like heading margin resets.

If you like I want to make PR.

Thanks ~

**Comment by rstoenescu** [comment]
Heading is covered in [typography.sass/styl](https://github.com/quasarframework/quasar/blob/dev/ui/src/css/core/typography.sass).

**Comment by rstoenescu** [comment]
Meaning PR is welcomed :)
Closing this in the meantime.
