### ISSUE TITLE
[docs] Broken link to /newsletter

### ISSUE THREAD

**Issue by patryk-tech** [quasarframework/quasar#5913]
Hello,

there's a broken link to https://quasar.dev/newsletter on the front page ( https://quasar.dev ).
 Clicking the link renders a white page, but refreshing it or following a link to it from the outside renders a 404 not found.

As far as I can tell, the link appears to be coming from [LandingTopBar.vue:17](https://github.com/quasarframework/quasar/blob/dev/docs/src/components/page-parts/landing/LandingTopBar.vue#L17).

Don't know how you would prefer to deal with it (whether by adding the missing page or removing the link), so I'll bring it to your attention rather than posting a pull request at this time :)

Regards,
Pat

![quasarnewsletter](https://user-images.githubusercontent.com/47309236/71156410-a5085d80-2248-11ea-9716-9ee647fa93d8.png)

**Comment by rstoenescu** [comment]
Oops, thanks for reporting this!
Will be fixed in next docs deployment.
