### ISSUE TITLE
Failed to restore plugin "cordova-plugin-whitelist" from config.xml

### ISSUE THREAD

**Issue by evazc** [quasarframework/quasar#5914]
**Describe the bug**
it appears when I run `quasar build -m cordova -T android` without folders 'node_modules, platforms, plugins' under `/src-cordova`(which are ignored by git)

**To Reproduce**
1. create a quasar-cli project with android platform
2. delete 'node_modules, platforms, plugins' folders under `/src-cordova`
3. run `quasar build -m cordova -T android`

**Screenshots**
![image](https://user-images.githubusercontent.com/26076008/69714102-c5a93000-1140-11ea-98a2-194354ae477e.png)

**Platform (please complete the following information):**
OS: both Windows and macOS
Node: 12.13.1
NPM: 6.12.1
Yarn: 1.10.1
Cordova: 9.0.0
@quasar/cli: 1.0.2

**Comment by rstoenescu** [comment]
Improved Cordova & Capacitor flow after git cloning a Quasar app repo.
Will be available in "@quasar/app" v1.4.2.
