### ISSUE TITLE
Version mismatch when upgrading quasar

### ISSUE THREAD

**Issue by Khan294** [quasarframework/quasar#5918]
**Describe the bug**
![2019-12-19 22_54_58-Administrator_ Command Prompt - quasar  dev -m ssr](https://user-images.githubusercontent.com/36960116/71197584-bdfa2880-22b3-11ea-80ff-520378114e8b.png)

**Additional info**
May have happened because of failed commit.
![2019-12-19 23_13_55-](https://user-images.githubusercontent.com/36960116/71198581-e7b44f00-22b5-11ea-8a7e-b0b8e6273637.png)

**Can be reproduced by upgrading quasar**
![2019-12-19 22_49_34-Administrator_ Command Prompt](https://user-images.githubusercontent.com/36960116/71197512-96a35b80-22b3-11ea-91bd-2ae3cfcf7963.png)

**What is required**
A way to make sure libraries use same version in node_modules/quasar/package.json 
![2019-12-19 23_00_39-F__work_visa_frontend_node_modules_quasar_package json (scrapping, backend, fron](https://user-images.githubusercontent.com/36960116/71198737-4974b900-22b6-11ea-8323-7d4f380e439d.png)

**Comment by rstoenescu** [comment]
Hi,

As I said a million times before, vue, vue-loader, vue-server-renderer, vue-router etc should not be manually installed. They come with quasar/app after being thoroughly tested.

**Comment by Khan294** [comment]
That's the main issue. I only used "quasar upgrade --install" as mentioned [here](https://quasar.dev/start/upgrade-guide).

It worked fine before but I think due to failed commit in "vue" repo, upgrade command was only able to download recent version for "vue-server-renderer" and not for "vue".

**Comment by rstoenescu** [comment]
Yes, it might be related to the recent NPM server issue. Please delete your node_modules and yarn.lock / package-lock.json and yarn/npm install again. Works ok for a lot of people.
