### ISSUE TITLE
[docs] Do/Don't regarding Password length

### ISSUE THREAD

**Issue by demon** [quasarframework/quasar#5919]
Currently the text is: **DON'T** limit the length of passwords.

While this is correct in principle, it opens up developers/sysadmins to a potential DOS vector. You want your limit to be high enough that no legitimate user will ever hit it, but not so high as to cause your server(s) to grind to a halt trying to compute the hash. Limits around 1000 or so are nice for this reason.

I would've written a PR, but I struggled with nice wording in the DO/DON'T style of this doc.

**Comment by rstoenescu** [comment]
Thanks for this ticket. Updated and will be available on next docs release.
