### ISSUE TITLE
Expose HTML5 'download' attribute of <a> tags within QBtn API

### ISSUE THREAD

**Issue by johnrix** [quasarframework/quasar#5920]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have a button instruct the browser to initiate a download rather than render the linked resource.

**Describe the solution you'd like**
HTML5 introduced a 'download' attribute for <a> tags. Expose this in the QBtn API to support cases where type="a"

**Describe alternatives you've considered**
JavaScript-based solutions, or adding query parameters to the URL for the server to instruct it to add a Content-Disposition header to the GET response.

**Additional context**
None

**Comment by pdanpdan** [comment]
Have you also tried to add the download attribute to QBtn?

**Comment by rstoenescu** [comment]
Vue allows you to pass HTML attributes to components. So create a QBtn type=“a” and pass the attribute(s) that you need as if they are props.

**Comment by johnrix** [comment]
Nice! I didn't realise that. Thanks guys!
