### ISSUE TITLE
Build APK

### ISSUE THREAD

**Issue by ToxicSnails** [quasarframework/quasar#5922]
i can't build to apk because when add platform android get error like this. any solutions?
<img width="667" alt="bug" src="https://user-images.githubusercontent.com/59079097/71234723-72d02c00-232c-11ea-9516-4067cda8e764.png">

**Comment by rstoenescu** [comment]
Your app name is invalid (`cordova`) as the error says.
Pick a correct name like indicated (`com.something.Name`).
