### ISSUE TITLE
Carousel and button component!

### ISSUE THREAD

**Issue by N1Mirzo** [quasarframework/quasar#5924]
**Is your feature request related to a problem? Please describe.**

Before a month I started to create a new ecommerce website. And I have it future design, namely, UX Design now. And There are so many components I want to add into my website. But there is no any of them in quasar. One of them is a multi carousel component and the second one is a button with two colors, some text and an icon.
**Describe the solution you'd like**
The components I wanted to create were described in the picture below.
![image](https://user-images.githubusercontent.com/55438076/71237651-f33e5f00-2323-11ea-85a0-b28d64ecec30.png)

I want a new button component with 2 colors with icon and some text to be added to components of buttons. Then I want you to add mutli carousel like this:
![image](https://user-images.githubusercontent.com/55438076/71243054-33f0a500-2331-11ea-80d6-70a2957e6e3a.png)

**Comment by rstoenescu** [comment]
Button: https://codepen.io/rstoenescu/pen/jOEBzLN
Carousel part is already described in another ticket (duplicate).
