### ISSUE TITLE
q-scroll-area content not showed

### ISSUE THREAD

**Issue by realtebo** [quasarframework/quasar#5926]
**Describe the bug**
when q-scroll-area has some content inside, the content is not showed 

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/realtebo/tfrzdjyu/71/

**To Reproduce**
See the linked jsFiddle.

I am rendering 100 paragraph insider a q-scroll-area, but nothing is shown !

**Expected behavior**
I expect q-scroll-area to expand vertically to occupy all, but not more, than available space and the content should be rendered inside of this component

**Platform (please complete the following information):**
OS: any
Node: 8.x, 10.x, 12.x
NPM: 5.x
Yarn: 1.9
Browsers: Chrome
iOS: n/a
Android: n/a
Electron: n/a

**Screenshot**

![image](https://user-images.githubusercontent.com/1268699/71294908-4d6a0f00-237a-11ea-8baf-c8a922bd317f.png)

**Comment by hawkeye64** [comment]
> I am rendering 100 paragraph insider a q-scroll-area, but nothing is shown !
That's not how a scrolled area works.
If you look at the [examples](https://quasar.dev/vue-components/scroll-area#QScrollArea-API), you will see that it requires styling to determine of width and height.
```html
<q-scroll-area style="height: 200px; max-width: 300px;">
```

**Comment by realtebo** [comment]
The documentation, yes, uses an explicit height, but it was not stating the it was mandatory. I didn't understand. Thanks

Is there a solution for my situation?

**Comment by metalsadman** [comment]
> The documentation, yes, uses an explicit height, but it was not stating the it was mandatory. I didn't understand. Thanks
> 
> Is there a solution for my situation?

Giv it a class `fit` or `full-height`.
