### ISSUE TITLE
[Infinite Scroll] setScrollPosition param error

### ISSUE THREAD

**Issue by evazc** [quasarframework/quasar#5928]
**Screenshots**
![image](https://user-images.githubusercontent.com/26076008/71300602-50dcb500-23d1-11ea-8116-7efb467e78bc.png)

the first param should be `this.scrollContainer`

I'm still learning using Pull Requsest So I didn't make a PR.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available on "quasar" v1.5.11
