### ISSUE TITLE
Vuex getters with parameters

### ISSUE THREAD

**Issue by SpareShade** [quasarframework/quasar#5930]
Thank you for all the hard work in making Quasar happen!

To access a Vuex "getter" from a module store one can just write this.$store.getters['auth/getAuthenticated'] .

In Vuex it is also possible to pass parameter ie. payload object, this.$store.getters['auth/getProfile] ({"user_id": 123})

But the above does not work in Quasar

    Pkg quasar........ v1.5.9
    Pkg @quasar/app... v1.4.2

Is this something that will be possible in Quasar with Vuex store?

**Comment by SpareShade** [comment]
ahh, of course it's possible 

```javascript
export const getProfile = state => id => {
  return state.profiles.find(profile => profile.id === id)
};
```

**Comment by smolinari** [comment]
It would be better, before you create a bug like this, to ask about it in the forum or Discord server. If we come up to find it is an issue, then we'll ask you to create one here. Thanks!

https://forum.quasar.dev
https://chat.quasar.dev

Scott
