### ISSUE TITLE
q-layout causes flickering scroll bar when resizing window.

### ISSUE THREAD

**Issue by awulkan** [quasarframework/quasar#5932]
**Describe the bug**

For some reason the q-layout component modifies its min-height css style when you resize the browser window. This causes the scroll bar to flicker since the min-height becomes larger than the max height of the window when shrinking the window. This not only causes an annoying flickering scroll bar, but it also pushes all of the website content to the left every time the scroll bar flickers.

**To Reproduce**
1. Create a new Quasar project.
2. Launch it in the browser.
3. Resize the height of the browser window with your mouse.

**Expected behavior**

No scroll bar should show up, and definitely not flicker.

**Screenshots**

https://www.loom.com/embed/2082371d03b743ba85c7937c6833abef

**Platform (please complete the following information):**
OS: Windows 10
Node: 13.5.0
NPM:
Yarn: 1.21
Browsers: Chrome 79
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
It's a trade off between layout responsiveness and load. If in your case resizing the window is so frequent that it's creating problems you can set Screen's plugin debounce to 0 to have instant updates.
Just put `this.$q.screen.setDebounce(0)` in you App.vue in `mounted () { ... }` (see docs here: https://quasar.dev/options/screen-plugin#Configuration)

**Comment by awulkan** [comment]
Why is min-height even set with javascript though? Why Doesn't it just use plain css?

**Comment by CrawfordW** [comment]
That solved it for the main window, but I still get it in the drawer.
