### ISSUE TITLE
QSelect doesn't show all the option items

### ISSUE THREAD

**Issue by topvis** [quasarframework/quasar#5934]
**Describe the bug**
options is updated dynamically with the values obtained from REST API in filter update function but QSelect doesn't show all the items in options.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/topvis/pen/jOEmLqq

**To Reproduce**
1. Go to Codepen link provided above
2. Select the text "United States of America" in the QSelect component
3. type in "RU" (without quotation marks)

**Expected behavior**
After "RU" is typed in, the country options is displayed on the right side in a QList control. The dropdown list of the QSelect control is supposed show all the items but it only shows one item "Aruba".

**Screenshots**

![image](https://user-images.githubusercontent.com/5996531/71328137-2af20600-24e0-11ea-982d-1b222f20a161.png)

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Chrome

**Comment by rstoenescu** [comment]
Misusage. You forgot to also call `update()` like in https://codepen.io/rstoenescu/pen/LYEymPQ
