### ISSUE TITLE
QBtnDropdown doesn't get same spacing as QTab in QTabs

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#5945]
**Describe the bug**
When QBtnDropdown is used as replacement in QTabs and QTabs is stretched out, the QBtnDropdown does not get the same width as the other QTab components. This causes the displayed content to look "off".

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Hawkeye64/pen/qBEjZZv?editors=1010

**To Reproduce**
1. The wider the screen the better you can see this issue
2. You will see that the QTab in the QTabs get wider
3. The QBtnDropdown components don't get any width adjustments

**Expected behavior**
The QBtnDropdown components to have same width as QTab components (isn't this flex?)

**Screenshots**
![image](https://user-images.githubusercontent.com/10262924/71421593-21c87c80-2639-11ea-86e1-2723a9e77471.png)

**Comment by hawkeye64** [comment]
I should mention, this was tagged as a bug at work. I found a work-around by placing the QBtnDropdown in the QTab slot. However, when hovering occurred, both the QTab and QBtnDropdown had overlapping hover highlighting that did not look good (as they are different sizes).

Suggestions:
1) have a `no-hover` prop for QBtnDropdown so it can be used in a QTab slot.
2) have a `tab` prop for QBtnDropdown so it can act more like a QTab
3) have a new component QBtnDropdownTab that combines both functionalities

**Comment by hawkeye64** [comment]
I may have resolved this simply by adding the class 'q-tab' to the QBtnDropdown
https://codepen.io/Hawkeye64/pen/GRgMJVZ?editors=1010

In your opinion, would this be suitable for the issue at work?

**Comment by hawkeye64** [comment]
I am still having slight issues with this. QA is really nit-picking this one. :(

**Comment by pdanpdan** [comment]
It's not the spacing - on large screens the tabs have a min-width of 128px, maybe this is the problem?

**Comment by hawkeye64** [comment]
I just need make them so they are consistent, noo matter the width. Your insight is appreciated.
![image](https://user-images.githubusercontent.com/10262924/71926767-49e3cf80-3151-11ea-88be-1eb1e084ac11.png)
See, they are larger here than the QTabs

**Comment by pdanpdan** [comment]
This is a user-land customization, but if you need to adjust the padding it's easy to do.
Check here for a simple solution: https://github.com/quasarframework/quasar/issues/6270#issuecomment-580662420

**Comment by hawkeye64** [comment]
Thanks @pdanpdan !
