### ISSUE TITLE
 [Windows]Electron process terminated after changing main-process code

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5949]
**Describe the bug**
When I tried to change any code of Electron，quasar CLI shows：
 app:electron ⚠️  Electron process ended with error code: 1

**Codepen/jsFiddle/Codesandbox (required)**
quasar/cli issue

**To Reproduce**
1. quasar dev -m electron
2. change any code in main-process

**Expected behavior**
Electron should reload with new code like https://github.com/SimulatedGREG/electron-vue

Quasar info:
Operating System - Windows_NT(10.0.18362) - win32/x64
NodeJs - 12.14.0

Global packages
  NPM - 6.13.4
  yarn - 1.21.1
  @quasar/cli - 1.0.5
  cordova - Not installed

Important local packages
  quasar - 1.5.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - 5.0.13 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 14.1.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 21.2.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.7 -- Babel compiler core.
  webpack - 4.41.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-FKIU25H
  Ethernet - 192.168.31.134
  VirtualBox Host-Only Network - 169.254.124.40
  VirtualBox Host-Only Network #2 - 169.254.109.233

**Comment by ed-yee** [comment]
I have the same problem with Windows 10 machine. However, it doesn't happen on my Mac.

Here is my Windows quasar info:

Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.16.3

Global packages
  NPM - 6.11.3
  yarn - Not installed
  @quasar/cli - 1.0.0
  cordova - Not installed

Important local packages
  quasar - 1.5.11 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - 7.1.7 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.7 -- Babel compiler core.
  webpack - 4.41.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*


Here is my Mac quasar info:

Operating System - Darwin(19.2.0) - darwin/x64
NodeJs - 10.16.0

Global packages
  NPM - 6.12.1
  yarn - Not installed
  @quasar/cli - 1.0.0
  cordova - Not installed

Important local packages
  quasar - 1.5.11 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - 7.1.7 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.7 -- Babel compiler core.
  webpack - 4.41.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

**Comment by hugetiny** [comment]
Electron should reload with new code like https://github.com/SimulatedGREG/electron-vue
Anyway, this isn't a bug , but a feature request.

**Comment by mahwd** [comment]
same here still waiting for fix

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available shortly in "@quasar/app" v1.4.4.
