### ISSUE TITLE
Add hover method to show submenu

### ISSUE THREAD

**Issue by gongzemin** [quasarframework/quasar#5950]
**Is your feature request related to a problem? Please describe.**
Submenu can only become visible at click, if we can hover show, it would be much easier.

**Describe the solution you'd like**
maybe add hoverable props, `<q-item clickable hoverable>,`

<img width="1217" alt="1" src="https://user-images.githubusercontent.com/10809643/71500333-81c05c80-289f-11ea-9dc3-fd9583bd0335.png">
https://codepen.io/pen/?&editable=true&editors=101

**Comment by metalsadman** [comment]
@gongzemin you can use ref atm, then call show method, ie. `@mouseover="$refs.subMenu.show()"`.

**Comment by gongzemin** [comment]
@metalsadman Thanks, it works. I have added the show() and hide().
Here is the working demo, maybe someone needs it.
[https://codepen.io/andersonmin/pen/rNazgqK?&editable=true&editors=101](url)

**Comment by rfox12** [comment]
I'm primarily on the desktop so mouseover to open a submenu would be great.  Hiding on mouse-out can be problematic... on my machine the submenu hides so fast the user can't actually select a sub-menu item--super frustrating user experience.  Need to set a delay.

**Comment by smolinari** [comment]
Closing this, as it seems the OP's problem is solved.

Scott

**Comment by mike-hsieh-tw** [comment]
I had made one. I think it's a little complicated. 
By the way, what I design just only have three submenus. Cause it's enough for my project.
Hope it could help some one. https://jsfiddle.net/ph822720355/4dbfqLjc/

![quasar_hover_menu](https://user-images.githubusercontent.com/60645233/140242049-aaf68d0c-4e7c-4357-8d44-9bb964db7435.gif)
