### ISSUE TITLE
Q-Table top row slot undefined

### ISSUE THREAD

**Issue by cashmisa** [quasarframework/quasar#5951]
**Describe the bug**
When top-row slot is used but with an empty template
```
<template v-slot:top-row>
   <tr v-if="false">hello</tr>
</template>
```
We have such senario when
1. wrapping q-table and exposing the top-row, but parent of the wrapped component does not use the slot
2. template in top-row slot is rendered with v-if conditions

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/cashmisa/pen/BayZXde?editors=1010

**To Reproduce**
Toggle "using top row" and console will show the "Cannot read property 'concat' of undefined" error message

**Expected behavior**
Should be the same as bottom-row, which is allow empty slot template

**Comment by rstoenescu** [comment]
Hi,

Put the v-if directive on the `<template>` tag itself.
