### ISSUE TITLE
[Bug] QEditor unexpected behavior when working with pre tag

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#5954]
In `QEditor` when working inside `PRE` tag there is very strange behavior with white space symbols and with new line.

1. Line breakes when press `enter` or `ctrl + enter` breakes `pre` tag, and impossible to unbreak it after.
2. White spaces turn into `&nbsp;` sometimes, and sometimes even disappeared at all.

Some strange behavior when turn into code editing mode with white spaces and `&nbsp;`.

**Comment by rstoenescu** [comment]
Hi,

QEditor relies upon document.execCommand() so it is the browser choosing the HTML syntax to translate to.

**Comment by wsw70** [comment]
> QEditor relies upon document.execCommand()

Is this still the case? `document.execCommand()` is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand).
