### ISSUE TITLE
q-menu transition not working on IOS devices

### ISSUE THREAD

**Issue by dangtu1795** [quasarframework/quasar#5955]
Hi there,
I have just tried testing q-menu with ios devices and realized that the transition function doesn't work

Steps to reproduce:
1. Go to https://quasar.dev/vue-components/menu
2. Scroll down to Transitions section
3. Open debugging mode and debug as an IOS device

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.6.2.
