### ISSUE TITLE
Input "standout" classes incorrect

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#5956]
In the documentation pages the following code example is given:

https://quasar.dev/vue-components/input#Standout

```
<q-input standout="bg-teal text-white" v-model="text" label="Custom standout" :dense="dense" />
```

However, it seems that `text-white` is irrelevant. You could enter any text coloring you want, it won't get applied and defaults to white.

The text class should be applied to the underlying `<input>` element and not to `q-field__control` in order to be effective...

**Comment by rstoenescu** [comment]
Hi,

Everything works as expected. This pen should explain it. https://codepen.io/rstoenescu/pen/XWJajER?&editable=true&editors=101

**Comment by Sjoerd82** [comment]
Dead link. But I believe the solution here is: 
```
standout="bg-teal text-white"
input-class="text-white"
```

Referencing:
https://github.com/quasarframework/quasar/issues/7711
https://github.com/quasarframework/quasar/issues/3914

The `standout` property seems to be a little confusing in this way.
