### ISSUE TITLE
[HELP] use quasar components in SSR without quasar CLI

### ISSUE THREAD

**Issue by mohandeblaze** [quasarframework/quasar#5958]
I am trying to use quasar component in Nuxt SSR, when i register the quasar in nuxt/plugins/ and used QBtn component. 

On server rendering i get this error.

`[Vue warn]: Error in render: "TypeError: Cannot read property 'platform' of undefined"`

`found in`

`---> <QBtn>`

QBtn excepts to have platform properties from [here](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/btn/QBtn.js#L228). I 
 have analyzed quasar CLI project and found that `Quasar.ssrUpdate({ app, ssr: ssrContext })` is being called to populate these properties. Unfortunately these `ssrContext` and `app` objects are present inside `.nuxt` generated files. Is there a simple or proper way to register quasar component in nuxt SSR ?

###### _PS: I posted same question in nuxt community [here](https://cmty.app/nuxt/nuxt.js/issues/c10109) but no response._

**Comment by metalsadman** [comment]
@mohandeblaze please head to our discord for inquiries (gh ticket is supposedly for bug and feature request tickets), here's an example of someone using it in their nuxt project https://discordapp.com/channels/415874313728688138/596275881907978240/609628085872230401.

**Comment by mohandeblaze** [comment]
@metalsadman I'm sorry for posting it here, I have already tried in Discord (you might have came across me in SSR channel a week ago) but i didn't get enough help to get through this issue. From the above link example, QBtn will render successfully in the SPA mode but i looking to render in the SSR.

Here i have attached a repo ([here](https://github.com/mohandeblaze/nest-nuxt-quasar)) of reproducing the issue. Please have a look at it, just un-comment `quasar` import in `client/plugin/quasar.js` file and you will the issue.

**Comment by rstoenescu** [comment]
Use Quasar CLI to generate a project. Add your button and all the rest. Do a build. Check the `.quasar` folder files around the `Vue.use(Quasar, ...)`.
