### ISSUE TITLE
Adressba color is causing problems

### ISSUE THREAD

**Issue by N1Mirzo** [quasarframework/quasar#5960]
**Describe the bug**
Quasar addessbar color is causing this problem: Quasar_src_plugins_AddressbarColor_js__WEBPACK_IMPORTED_MODULE_0__.default.set is not a function

**Expected behavior**
I've expected chnaged color of cordova mobile app on my Xperia M2 Dual.
**Screenshots**
This is the problem on chrome web browser.
![image](https://user-images.githubusercontent.com/55438076/71549429-f3eb8b00-29de-11ea-992b-8e99aed3798c.png)

And these are the boot file and quasar.cong.js files which I tried as it was in docs.
![image](https://user-images.githubusercontent.com/55438076/71549417-c999cd80-29de-11ea-88cd-c0fe39fdeec8.png)
**Platform (please complete the following information):**
OS: Windows 10, Windows 7
Node: v13.3.0
NPM: 6.13.1
Yarn: 1.21.1
Browsers: Chrome desktop, mobile , latest, laptop and Firefox, so, the Opera, too.
iOS: Safari
Android:  Android 5. 1.1

**Additional context**
_**I am so curious to know how to make it happen to change color of it.

**Comment by rstoenescu** [comment]
Hi,

Add AddressbarColor to your quasar.conf.js > framework > plugins list.
If on a cordova build, remember that this Quasar Plugin hooks into the [Statusbar cordova plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/index.html), so install that too in your /src-cordova.
