### ISSUE TITLE
QTable global default pagination values

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#5961]
Quasar is hardcoded to show 5 rows per page by default. I'd like to bump the default up to, let's say, 10. How can I do this globally without having to define `rowsPerPage: 10` over and over again?

**Comment by metalsadman** [comment]
@Propaganistas wrap your own q-table component that already set rows per page and use that component over and over again whenever you need to :)

**Comment by Propaganistas** [comment]
Thanks @metalsadman . How'd you proxy all bindings, listeners and slots down to the actual QTable component?

I found this on [SO](https://stackoverflow.com/questions/50891858/vue-how-to-pass-down-slots-inside-wrapper-component)?

```
<template>
  <q-table v-bind="$attrs" v-on="$listeners">

    <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope">
        <slot :name="slot" v-bind="scope"/>
    </template>

  </q-table>
</template>
```

**Comment by datadisc** [comment]
Maybe not the most accurate answer, but i'm using following mixin in my projects:

````javascript
export default {
    data() {
        return {
            tableName: 'table',
            pagination: {
                descending: false,
                page: 1,
                rowsPerPage: this.$q.localStorage.has(this.tableName+'-rowsPerPage') ? this.$q.localStorage.getItem(this.tableName+'-rowsPerPage') : 50,
                rowsNumber: 0
            }
        }
    },
    watch: {
        'pagination.rowsPerPage': {
            handler(newValue) {
                this.$q.localStorage.set(this.tableName+'-rowsPerPage', newValue);
            }
        }
    }
}
````

Additional bonus here is that the user can preserve his/her selection with the `localStorage` plugin. You can also override `tableName` property in component definition.

**Comment by rfox12** [comment]
I think code along the lines of Propaganistas's finding on Stackoverflow is documentation-worthy.  One thing I struggled with in Quasar (and Vue in general) is: what is the "right" way to extend a default (Quasar) component?

**Comment by pdanpdan** [comment]
@datadisc's solution is very elegant and simple.

**Comment by Propaganistas** [comment]
> @datadisc's solution is very elegant and simple.

It doesn't scale welk when you have for example multiple tables on the same page.

**Comment by datadisc** [comment]
@Propaganistas
> It doesn't scale well when you have for example multiple tables on the same page.

What do you mean "on the same page"? Within the same component?

**Comment by Propaganistas** [comment]
Exactly. Suppose a simple component that happens to have 2 QTables. In that case a mixin isn't generic enough since it applies to the component as a whole and not a particular table. Of course you could go down the route of making a dedicated component for each table. But that's the whole point of this issue: I feel like that's overkill when I just need a simple default for all QTables i'll ever use..

**Comment by metalsadman** [comment]
> I think code along the lines of Propaganistas's finding on Stackoverflow is documentation-worthy. One thing I struggled with in Quasar (and Vue in general) is: what is the "right" way to extend a default (Quasar) component?

peeps just need to remember there's thing called google.

**Comment by ajcastro** [comment]
you can also create a Factory that will return the pagination object and use it in your component

```js
import PaginationFactory from 'where/you/put/your/PaginationFactory';

export default {
  data() {
    return {
      pagination: PaginationFactory.make({
        // we can pass some pagination props that can override the default pagination props
      })
    };
  }
}
```
