### ISSUE TITLE
[Request] Add format button to QEditor HTML mode.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#5962]
Really unreadable text in QEditor when HTML mode.

![image](https://user-images.githubusercontent.com/10674646/71553074-e6072b80-2a19-11ea-80c7-5019fa13bf37.png)

I propose to add button to format selected or all html text with standart classic html formating.
And to add interface to allow adding custom buttons on this panel.

**Comment by Dimitij-Polianin** [comment]
Also need to add fullscreen button and prev, next buttons at this mode if it is at normal mode.

**Comment by pdanpdan** [comment]
We will not implement this in core. Please use an external html editor for more complex things.
