### ISSUE TITLE
Post radio and select in dotnecore controller

### ISSUE THREAD

**Issue by JTrotta** [quasarframework/quasar#5963]
**Describe the bug**
Use quasar framework with Asp.net core. Frontend views, use form components. But only q-input are posted to the back end model. q-radio and q-select are not.

**Codepen/jsFiddle/Codesandbox (required)**
Not applicable

**To Reproduce**
1. create a dotnecore asp.net mvc project 
2. crate a page with quasar framework and a radio or selcet component
3. submit the page
4. model in controller is not populated

**Expected behavior**
model passed from front-end to back-end as it works with simple input 

**Screenshots**
Not applicable

**Platform (please complete the following information):**
OS: windows
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
I tried to add name attribute to radio and select but it does not work, Even if radio is not posted at all into form collecction, while select is posted but its value is null.

**Comment by pdanpdan** [comment]
This will be available in the next version v1.9.0 - a new prop `name` will be available on all form controls. But according to html specifications only text values (and File objects) will be passed.

**Comment by JTrotta** [comment]
It seems that q-editor is still affected by the same problem, o better, it does not have the name property.

**Comment by pdanpdan** [comment]
@JTrotta please open an issue for this one if it is missing, thank you
