### ISSUE TITLE
Many thanks to the Quasarteam, goodbye 2019 - welcome 2020 and a little wishlist

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5964]
I know that this issue area is may wrong for this entry, but it can alternativly handled as a feature request.

I will thank the whole quasarteam for all the work, effort, calmness, money, ideas, support, cleverness, heartblood and time for building and maintenance the quasar-universe in 2019. 

You - p.p. Scott, Jeff, Metalsadman, Lucas, Webnoob, Razvan, Tobias M, PDan, Eduardo, Kerry, Adam, Callo, Aurone, Stasi (no special order and sorry for all i forget - there are many many more) are doing a outstanding job and without your endurance the quasar-verse would not exist as it is.

After expanding my belt, caused by some heavy christmas-meals, my development intentions for 2020 are based on this fluffy feeling. If allowed i would opening here a little wishlist for the quasar 2020 "edition":

- some rudimentary, lightweight, basic alternative components for e.g. q-button, q-input, etc.

- a (pre)-quasar boot-loading splash screen / animation (web spa) (before any vue/js based "actions")

- the overflow-hidden body-css-rule instead of the position: fixed for dialogs :-)

- a Quasar Enterprise Edition ($$$) with LTS 

- a Github-Sponsor-Perk/Bonus with "ask me anything" monthly for 1 hour with the quasar-founder(s)

- a Quasar (for me favorised: European) Developer Meetup 

My personal Mantra for 2020 : 
Less domnodes, Less eventlisteners, less filesize => more performance.

Thank you for building and supporting this fabulous framwork.

**Comment by hawkeye64** [comment]
@ibrainventures And, Happy New Year to you too! :heart:

**Comment by ibrainventures** [comment]
Also back to you and to all other quasarians. 2020 would be great!

**Comment by rstoenescu** [comment]
Noted all requests. Happy New Year to you too!
