### ISSUE TITLE
tooltip on QIcon is not workihg

### ISSUE THREAD

**Issue by cbleek** [quasarframework/quasar#5967]
**Describe the bug**
using "img:/my/image.svg" as name of q-icon, tooltips are not shown. Maybe slots are note executed

**Codepen/jsFiddle/Codesandbox (required)**
I have no jsFiddle but PR

**To Reproduce**
1. Go to https://cross-solution.de
2. tooltp on "upwork" is not working

**Expected behavior**
![Bildschirmfoto 2019-12-29 um 21 11 00](https://user-images.githubusercontent.com/858642/71562353-f81bb500-2a7f-11ea-8eae-488efcfd6f7b.png)

**Comment by hawkeye64** [comment]
@cbleek The best way to handle this is to put a div around your image and place the q-tooltip in the div.

**Comment by rstoenescu** [comment]
`<img>` tags cannot have any children, so if tooltips are needed in this case pls use @hawkeye64's solution above.

**Comment by gaw89** [comment]
Another good option for those who arrive here is to place the `q-icon` and the `q-tooltip` next to each other inside a `<span>`.  This worked for me!
