### ISSUE TITLE
Slide positions wrong in IE 11

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#597]
### Software version

Quasar: 0.13.9
OS:
Node:
NPM:
Browsers: IE 11
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
The slider functionality is working, but the positions of the slides are off. The first slide is a little bit off to the right and each slide is off a bit more.

### What were you expecting?
Correct positioning as I see in the other browsers

### What steps did you take, to get the error?
View a page with the slider in IE 11.

`<q-slider
            arrows infinite dots
            ref="stationSlider"
            class="allStations text-white mw7 center"
            @slide="handleSlideChange"
          >
            <div slot="slide"
                 :key="station.stationId"
                 v-for="station in selectedGenre.stations"
            >
              <station-button
                class="w-100 h5 h-80-m vh-50-l"
                :genreId="genreId"
                :station="station"
              ></station-button>
            </div>
          </q-slider>`

**Comment by pdanpdan** [comment]
This should be fixed. Can you please check?

**Comment by smakinson** [comment]
Thank you! Should I look to update my app to 0.14 now or wait a bit?

**Comment by pdanpdan** [comment]
You have to update to 0.14 and include src/ie-compat/ie.{theme}.styl

**Comment by rstoenescu** [comment]
There's going to be another official way to include ie support, not yet done. Do not include from src.

**Comment by smakinson** [comment]
Ok, I'll wait and possibly start a new site I'm looking at with 0.14 to check out the differences.

**Comment by rstoenescu** [comment]
@pdandan he's talking about QCarousel in v0.14, not the QSlider. Just making sure we are on the same page. It just bumped me now :)

**Comment by pdanpdan** [comment]
Yes. I made the fixes and they are in Dev. Not in the ie-compat. I'll try to identify the commit.

**Comment by rstoenescu** [comment]
@pdanpdan No need to identify the commit. Knowing it's in Quasar already will suffice. Thanks!
