### ISSUE TITLE
Select component does not show the label of the initial value

### ISSUE THREAD

**Issue by dvbeek** [quasarframework/quasar#5971]
**Describe the bug**
When a q-select component is used with objects as data, the current value of the v-model is initially displayed by it's value instead of it's label.

**To Reproduce**
template:
```
<template>
  <q-select filled v-model="model" :options="options" label="Standard" />
</template>
```

script:
```
<script>
export default {
  data () {
    return {
      model: 'google-value',
      options: [
        {
          label: 'Google',
          value: 'google-value',
          description: 'Search engine',
          category: '1'
        },
        {
          label: 'Facebook',
          value: 'facebook-value',
          description: 'Social media',
          category: '1'
        }
      ]
    }
  }
}
</script>
```

**Comment by dvbeek** [comment]
I had to add 'map-options'... my bad.

**Comment by smolinari** [comment]
Hi,

Please use either our [forum](http://forum.quasar-framework.org/) or our [discord channel](https://discord.gg/5TDhbDg) to get help on deciphering the cause of an issue. If we come to the conclusion your issue is a bug, we'll then ask you to add an issue here. 

Thanks. 😄 

Scott
