### ISSUE TITLE
q-btn-dropdown with auto-close on mobile not passing event to the target element on click/tap

### ISSUE THREAD

**Issue by dmitry** [quasarframework/quasar#5972]
**Describe the bug**

When I click to button dropdown (`q-btn-dropdown`) with `auto-close` or without it and then would like to click on the other element, I expect that the target element going to receive a click event.
In case of desktop it works as expected, in case of mobile (IOS/Android) it doesn't work.

https://codepen.io/dmitry-polushkin/pen/zYxEYMY

**To Reproduce**

Use iOS or Android chrome:

1. Click on dropdown (it should open)
2. Click on "Click me button"
3. `x` variable should change

Desktop works well.

**Expected behavior**

Target element should receive click/tap element on mobile.

**Platform (please complete the following information):**

Browsers: Chrome on iOS/Android

**Additional context**

btn-dropdown belongs to menu element, so the fix should be made there.

**PS.** What is the difference on using `auto-close` or not using it (when not enabling `persistent` option)? Does the `btn-dropdown` works a little different when `auto-close` is opt-out?

**Comment by rstoenescu** [comment]
Hi,

This is a feature of the underlying QMenu. On mobile, the screen is much smaller, so we need to protect against accidental taps outside of the menu which trigger "stuff" (navigation, clicks, etc etc) -- as it has been heavily requested by the community.

**Comment by dmitry** [comment]
@rstoenescu probably it would be good to make it work identically to work on desktop as well as it works on mobile? Or at least make it clear in the documentation about the "tricky" behaviour depending on the platform.

**Comment by dmitry** [comment]
@rstoenescu And additionally: what is the difference on using auto-close or not using it (when not enabling persistent option)? Does the btn-dropdown works a little different when auto-close is opt-out?

Thank you and your team for your hard work!

**Comment by rstoenescu** [comment]
auto-close and persistent are two independent features:

The first has to do with clicking/tapping anywhere on the menu content and automatically making the menu to close. Which is a convenience feature: rather than applying v-close-popup directive to each menu item or by using a v-model and adding event listeners which change the menu model to close it.

The second has to do with allowing or not the menu to be closed when clicking/tapping outside of it, which comes in very handy on many scenarios.
