### ISSUE TITLE
Q-table overflows display:grid wrapper

### ISSUE THREAD

**Issue by natajonasdacoliveira** [quasarframework/quasar#5975]
**Describe the bug**
When inside a container with "display: grid", the "q-table" component overflows the main div, instead of creating a horizontal scroll

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Hkz/full/KKwXzWN

**To Reproduce**
1. Open the codepen/put a q-table inside a div with display:grid;
2. Resize the page to lower resolutions.

**Expected behavior**
Put the correct horizontal scroll and not overflow

**Comment by hawkeye64** [comment]
@natajonasdacoliveira I am not seeing this issue with the pen you provided.
![Screenshot from 2019-12-30 14-26-50](https://user-images.githubusercontent.com/10262924/71601416-90617a80-2b10-11ea-9d21-72a98512ede6.png)

**Comment by natajonasdacoliveira** [comment]
> @natajonasdacoliveira I am not seeing this issue with the pen you provided.
> ![Screenshot from 2019-12-30 14-26-50](https://user-images.githubusercontent.com/10262924/71601416-90617a80-2b10-11ea-9d21-72a98512ede6.png)
> Also, `height` should be spelled correctly for CSS to recognize it.

As I can see, codepen put a scroll in the entire page itself, instead of letting overflows. The scroll should be inside the table, as you can see here: [https://quasar.dev/vue-components/table#Basic]

**Comment by rstoenescu** [comment]
This is not a bug with QTable.
