### ISSUE TITLE
hourglass spinner animation in firefox

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#5976]
hourglass spinner animation not working properly in firefox.

**Comment by hawkeye64** [comment]
All the spinners are working for me on Ubuntu/Firefox. Please paste your `quasar info` here. Thanks.
![hour-glass-firefox](https://user-images.githubusercontent.com/10262924/71670549-6e910f00-2d2d-11ea-8f42-3f2f5c6e5f48.gif)

**Comment by elselapatha** [comment]
> All the spinners are working for me on Ubuntu/Firefox. Please paste your `quasar info` here. Thanks.
> ![hour-glass-firefox](https://user-images.githubusercontent.com/10262924/71670549-6e910f00-2d2d-11ea-8f42-3f2f5c6e5f48.gif)

Look at this. Hourglass
![miniGif_20200102214752](https://user-images.githubusercontent.com/19161540/71677958-016f8f00-2daa-11ea-858a-7fe2a2449025.gif)

**Comment by hawkeye64** [comment]
@elselapatha haha! I see it now. I'm so blind. :joy:
They are all looking a bit "funky"

**Comment by hawkeye64** [comment]
@elselapatha Got you covered. Check out the PR and many thanks again for bringing this to our attention. :heart:

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.6.0.
