### ISSUE TITLE
Q-Step: Number as name breaks vue-devtools searching, prevents tree browsing.

### ISSUE THREAD

**Issue by geraldbiggs** [quasarframework/quasar#5979]
Description: 

Cycling through q-step has numbers in the names prop. This seems to cause vue-devtools component search to crash as well as loading component information - as it appears to be expecting a string. This may be potentially resolved by changing the name of the prop "name" for q-step. 

Codepen:
https://codepen.io/geraldbiggs/pen/povWOBJ
(I'm not sure if devtools will load in debug view)

**To Reproduce**
1. Open devtools
2. Search for QBadge in the component search
3. Component list displays incorrect results, error, and manual component search does not reveal data
4. Clicking on components also trigger error response

**Expected behavior**
Component is found, everyone gets a kitten.

**Screenshots**
<img width="694" alt="Screen Shot 2020-01-01 at 12 10 08 PM" src="https://user-images.githubusercontent.com/3213608/71644149-c9752880-2c91-11ea-8e96-e2dcfb2d6b17.png">

Preview shows step number of 999, set by data in the component.

**Platform (please complete the following information):**
OS: 10.14.6
Node:12.9.0
Yarn:  1.19.2
Browsers: Chrome

**Additional context**
    at backend.js:153
    at cachedFn (backend.js:147)
    at isQualified (backend.js:2414)
    at findQualifiedChildren (backend.js:2394)
    at Array.map (<anonymous>)
    at findQualifiedChildrenFromList (backend.js:2381)
    at findQualifiedChildren (backend.js:2396)
    at Array.map (<anonymous>)
    at findQualifiedChildrenFromList (backend.js:2381)
    at findQualifiedChildren (backend.js:2396)

**Comment by rstoenescu** [comment]
Hi,

Shouldn't this be reported to Vue devtools repo instead?
