### ISSUE TITLE
[ios] q-scroll-area sporadically did not show scroll-thumb

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5980]
**Describe the bug**

After loading a vue page with a included scroll-area, and touch-swipe / scroll the inner elements
the "scroll-thumb" is sporadically not displayed. Sometimes a reload helps and the thumb is shown.

Also happens on the:
https://quasar.dev/vue-components/scroll-area

some scroll-examples shows the thumb, some examples not. (randomly)

**Expected behavior**
It should always show a thumb, after starting a scroll-swipe.

**Platform (please complete the following information):**
OS: Ios 12, IpadOS 13
Browsers: Safari

Quasar: 1.5.11

**Comment by rstoenescu** [comment]
Hi,

Like specified at the top of the page:

```
When on a mobile device, QScrollArea simply wraps the content in a <div> configured for default mobile browser scrolling – so no QScrollArea features apply on such devices.
```

What you have specified is an iOS issue and not related to Quasar...

**Comment by ibrainventures** [comment]
Hi Razvan,
thanks for the fast response this night. Sorry, i was irritated by the randomness of this behaviour and didnt re-checked the docs. Yes, you are absolutly right, the scrolling-thumb-display-issue is (once again) a ios issue. Tested with some plain HtmL Documents, there is also this "effect", and this is not a quasar issue.

I like the "force-on-mobile" option which was implented on the version 1.5.11. Thank you very much for this usefull feature. It helps for a better UI Design. As written in the docs, the dynamic-touch-scrolling get away with this option. Sometimes on Ios 12/13 it snaps over to the dynamic scrolling (which is my favorited combination:  Display always the thumb, and have the dynamic touch scrolling).

On Android 9 / chrome the force-on-mobile kills the touch-dynamic scrolling complete, but there is without this option a (not customized) scrollbar (as alternative way) always displayed.

Did you see any chance or success for the ios 12/13 to have force-on-mobile-always displayed thumb with a good working dynamic touch scrolling?
