### ISSUE TITLE
QTable Grouping row 

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#5981]
Like this issue https://github.com/quasarframework/quasar/issues/1512 ,  It's not possible to grouping row by a row key ?

**Comment by nseb** [comment]
Vuetify has this feature : https://vuetifyjs.com/en/components/data-tables#grouped-rows

**Comment by nseb** [comment]
Up , not planed ?

**Comment by nseb** [comment]
Up , not planed ?

**Comment by rstoenescu** [comment]
It'll happen, but not over night.

**Comment by pdanpdan** [comment]
Please use one of:

https://github.com/pratik227/quasar-qhierarchy
https://github.com/Narcis13/quasar-grouped-table

**Comment by mapkbalaji** [comment]
[https://github.com/Narcis13/quasar-grouped-table] doesn't work on latest quasar frameswork.

**Comment by hawkeye64** [comment]
@mapkbalaji Contact the author on github @Narcis13

**Comment by gaby64** [comment]
interested in having grouping built in QTable

**Comment by ivan-pinto** [comment]
any idea if this will be a built-in feature on the QTable component in the near future ?
