### ISSUE TITLE
Meta plugin: Uncaught TypeError: Cannot read property 'stopPropagation' of undefined

### ISSUE THREAD

**Issue by dodohack** [quasarframework/quasar#5982]
**Describe the bug**
When using meta plugin with dynamic meta props, it will hit "Uncaught TypeError: Cannot read property 'stopPropagation' of undefined" from line 147 parseMeta(component, meta) from Meta.js.

How to reproduce, add code 
`  meta () {
    return {
      title: 'hello, world'
    }
  },`
to any component can trigger the bug.

I have made a simple fix by replace code at line 147 of Meta.js
`if (component.$options.meta.stopPropagation === true)`
with
`if (component.$options.meta && component.$options.meta.stopPropagation === true)`
to check if meta is defined before accessing it's attribute.

**Comment by rstoenescu** [comment]
Hi,

Can you fork https://codesandbox.quasar.dev and provide a minimum reproducible use-case pls? The code changes that you are requesting should not be necessary.

**Comment by dodohack** [comment]
I've found the root cause which caused the issue, it was due to I have a meta html tag in my template:
`<meta itemprop="thumbnailUrl" :url="entity.thumb" />`
I have renamed my <meta> tag to others to fixed this issue.

**Comment by rstoenescu** [comment]
Thank you!

Much clearer now. The v-runtime-template component blindly copies stuff from parent which gives false positives with Meta plugin. Corrected this.

Fix will be available in "quasar" v1.6.0.
