### ISSUE TITLE
Add support to set customized icons for QPagination direction-links

### ISSUE THREAD

**Issue by dodohack** [quasarframework/quasar#5984]
If not using the default icon set, there is issue to display QPagination direction-links, like the screenshot below.

<img width="575" alt="Screen Shot 2020-01-02 at 3 04 21 PM" src="https://user-images.githubusercontent.com/19568348/71673634-37445180-2d71-11ea-9d07-c3b2a6302401.png">

It would be great to customize QPagination icons just like other Quasar components.

**Comment by rstoenescu** [comment]
What icon set are you using? Are you on `@quasar/extras` or other? If on q/extras, have you configured the Quasar icon set too?

**Comment by dodohack** [comment]
I use mdi-v4 as my icon system.
Here is the extras in my quasar.conf.js:
`
    extras: [
      'roboto-font', // optional, you are not bound to it
      'mdi-v4' // optional, you are not bound to it
    ],

`

I mean there should be props to customize the icon name just like the prev-icon/next-icon in QCarousel.
