### ISSUE TITLE
Quasar attenpting to load Roboto Font over http when using https

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#5985]
**Describe the bug**
Quasar isn't taking into consideration that the app is running in running under https and attempts to load roboto font over http, causing the request to be blocked.

**To Reproduce**
1. Configure quasar to work with ssl 
2. run app in browser
3. open console'
4. See error: Mixed Content: `The page at 'https://localhost:8001/#' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1MmgVxFIzIFKw.woff2'. This request has been blocked; the content must be served over HTTPS.`

**Expected behavior**
No error, it should just load font using https when https is not false in quasar.config.

**Platform (please complete the following information):**
OS: Mac OS Majove
Node: 13.2.0
Browsers: Chrome

**Comment by rstoenescu** [comment]
Hi,

How is this related to Quasar? Instead of using `@quasar/extras` you are manually specifying a URL (or one of your deps is). Please change the URL to point to a https address instead. Quasar takes care of all the assets that are specified using a relative path or through statics, but it doesn't (and should not) change the full URLs specified by the developers.

**Comment by emahuni** [comment]
Hi. No you misunderstand. I didn't specify any manual URL. For fonts and the SSL I just configured this:

```js
  {
      //...
      extras: [
      // 'ionicons-v4',
      'mdi-v4',
      // 'fontawesome-v5',
      // 'eva-icons',
      // 'themify',
      // 'roboto-font-latin-ext', // this or either 'roboto-font', NEVER both!

      'roboto-font', // optional, you are not bound to it
      // 'material-icons' // optional, you are not bound to it
    ],
    //...
    devServer: {
      https:        {
        key:  certKey,
        cert: cert,
        // ca:   readFileSync('/path/to/ca.pem'),
      },
      // ...
   }
```
in _quasar.config_ and that error happens. Quasar Extras is loading that font over http when the server is secured with https. I think it should detect this and load assets over https when the server uses https.

Please open the issue.

**Comment by rstoenescu** [comment]
"@quasar/extras" is not Google's CDN is what I'm saying :) When you specify any "extras" in quasar.conf.js it does NOT use `fonts.gstatic.com/....` so this can't be a Quasar issue. Like I mentioned earlier, Quasar does take care of all the assets that are specified using a relative path or through statics.

It must be something that you are overlooking, so please fork https://codesandbox.quasar.dev or create a minimal reproduction repo and post the link here. Thanks.
