### ISSUE TITLE
QCardActions disabled prop

### ISSUE THREAD

**Issue by labs20** [quasarframework/quasar#5986]
**Is your feature request related to a problem? Please describe.**
It would be nice to enable / disable all actions of a card by simply disabling the actions card

**Describe the solution you'd like**
A new boolean prop "disable" on QCardAction

**Describe alternatives you've considered**
Setting individual disable prop for each QBtn

**Additional context**
Thanks

**Comment by pdanpdan** [comment]
The alternative solution is the right one :)

**Comment by rstoenescu** [comment]
We should avoid communication between components when the use-case of a certain feature is extremely low (like in this case). It introduces overhead regardless if the feature is used or not. Considering the alternative (which is the way to go), the adding of this feature would introduce too little benefit. Throwing in another alternative: Add "disabled" and "no-pointer-events" helper CSS classes directly on QCardAction.

**Comment by labs20** [comment]
> "no-pointer-events" helper CSS classes directly on QCardAction.

Looks nice. Thanks.
