### ISSUE TITLE
`quasar build -m pwa` failing with latest version

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#5987]
After upgrading to the latest version of quasar from these previous versions:

@quasar/extras: 1.3.1 → 1.3.3
 quasar: 1.1.0 → 1.5.11
 @quasar/app: 1.0.6 → 1.4.3
 @quasar/quasar-app-extension-icon-genie: 1.0.2 → 1.1.3

The build command for generating a pwa fails.

quasar build -m pwa

 Build mode........ pwa
 Pkg quasar........ v1.5.11
 Pkg @quasar/app... v1.4.3
 Debugging......... no
 Publishing........ no

 app:extension Running "@quasar/icon-genie" Quasar App Extension... +0ms
 app:quasar-conf Reading quasar.conf.js +14ms
 app:workbox [GenerateSW] Will generate a service-worker file. Ignoring your custom written one. +815ms
 app:webpack Extending PWA Webpack config +22ms
 app:artifacts Cleaned build artifact: "/Users/jonpaulmiles/Documents/Work/prowlers-and-paragons/dist/pwa" +5ms
 app:generator Generating Webpack entry point +0ms
 app:build Extension(@quasar/icon-genie): Running beforeBuild hook... +4ms
 app:build Building... +23ms

 PWA █████████████████████████ [100%] in ~13s

Version: webpack 4.41.3
Time: 12889ms
Built at: 01/02/2020 2:16:15 PM
                                                  Asset      Size  Chunks               Chunk Names
            fonts/KFOkCnqEu92Fr1MmgVxIIzQ.5cb7edfc.woff  19.9 KiB                       
           fonts/KFOlCnqEu92Fr1MmEU9fBBc-.87284894.woff    20 KiB                       
           fonts/KFOlCnqEu92Fr1MmSU5fBBc-.b00849e0.woff  19.9 KiB                       
           fonts/KFOlCnqEu92Fr1MmWUlfBBc-.adcde98f.woff  19.9 KiB                       
           fonts/KFOlCnqEu92Fr1MmYUtfBBc-.bb1e4dc6.woff  19.9 KiB                       
               fonts/KFOmCnqEu92Fr1Mu4mxM.60fa3c06.woff  19.8 KiB                       
                      fonts/fa-brands-400.c5e0f14f.woff  86.4 KiB                       
                     fonts/fa-brands-400.cccc9d29.woff2  73.6 KiB                       
                     fonts/fa-regular-400.c4f508e7.woff  16.4 KiB                       
                    fonts/fa-regular-400.f5f2566b.woff2  13.3 KiB                       
                       fonts/fa-solid-900.333bae20.woff  96.1 KiB                       
                      fonts/fa-solid-900.44d537ab.woff2    74 KiB                       
       fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.29b882f0.woff  77.7 KiB                       
fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.0509ab09.woff2  59.4 KiB                       
                               img/Villain.72547154.png   373 KiB                       
                             img/hero-bg-2.380a5aea.png  3.74 MiB                       
                                  js/vendor.837c757e.js  1.18 MiB  vendor  [immutable]  vendor
Entrypoint app = js/vendor.837c757e.js

ERROR in chunk app [entry]
Cannot convert undefined or null to object

ERROR in chunk app [entry]
({
              chunk: chunkData
            }) => this.options.moduleFilename(chunkData)
Path variable [contenthash:8] not implemented in this context: css/[name].[contenthash:8].css

 app:build [FAIL] Build failed with errors. Check log above. +1ms

**Comment by m-bonanno** [comment]
Change in your package.json _@quasar/app-v1.4.3_ to _@quasar/app-v1.3.2_, run _yarn_ and then _yarn build_ and let me know if it works. 

That worked for me!

**Comment by jeancaffou** [comment]
@m-bonanno so.... downgrading....

I'm having the same issue as OP

Pinging
@rstoenescu @pdanpdan

**Comment by jeancaffou** [comment]
I'm having the same issue as OP.

```
ERROR in chunk app [entry]
Cannot convert undefined or null to object

ERROR in chunk app [entry]
({
chunk: chunkData
}) => this.options.moduleFilename(chunkData)
Path variable [contenthash:8] not implemented in this context: css/[name].[contenthash:8].css

app:build [FAIL] Build failed with errors. Check log above. +1ms
```

Something broke between versions `1.3.2` and `1.4.5` probably in `app/lib/webpack/create-chain.js`

Somebody suggested renaming `[contenthash]` to `[hash]`:
> I just upgraded to Webpack 4.3 and got the same error. I hope this gets fixed, but for the moment I changed `[contenthash]` to `[hash]` to get it working again.

_Originally posted by @esausilva in https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763#issuecomment-376498755_

But this is also not a good solution because then `app` and `vendor` chunks get the same hash.

@rstoenescu

**Comment by jeancaffou** [comment]
Also, I don't know what helped but it seems to build PWA now with `"@quasar/app": "^1.4.5"`

I tried lots of things, but last things were:
```
npm uninstall @quasar/cli node-sass sass-loader
npm ci
```

Removing 
`'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',` 
from `.eslintrc.js`

and adding 
`formatter: require('eslint').CLIEngine.getFormatter('stylish')`
in `options` property of webpack rule (function `extendWebpack` in `quasar.conf.js`)

**Comment by rstoenescu** [comment]
Any repo from which I can reproduce the issue pls?

**Comment by rstoenescu** [comment]
Please reopen if it happens again with future "@quasar/app" v1.5.0.
Also, please do NOT manually install packages supplied by quasar/app (like webpack, vue, vue-router, ..)

**Comment by jeancaffou** [comment]
Just to add here, my steps didn't seem to help, because I commited package-lock.json and checked out on another machine, ran `npm ci` which should take care of making the workspace identical on all machines, but the problem still appears. Upgrading quasar to v1.5.0 on the working machine broke it again.
