### ISSUE TITLE
Input label style or label class when input donesn't get focus

### ISSUE THREAD

**Issue by hks2002** [quasarframework/quasar#5989]
As we known, we could use `standout` set the dispaly style which got focus,
If we could change the input label display style which the input doesn't get focus? such as, I want to the label color be white rather than gray.

**Comment by metalsadman** [comment]
@hks2002 doable with conditionals https://codepen.io/metalsadman/pen/mdymzZw.

**Comment by hks2002** [comment]
thanks.
