### ISSUE TITLE
[directives] v-touch-hold: How to use click event with touch-hold?

### ISSUE THREAD

**Issue by xiaoer3301** [quasarframework/quasar#5990]
I have a component that can be clicked, but long press will have other actions. How do I use the two together?
If I use them together, a long press on the component will trigger a click. Please help me, thank you.

**Comment by pdanpdan** [comment]
Here is a working example: https://codepen.io/pdanpdan/pen/MWYQypY
I don't understand what is not working for you, but if you can provide a codepen with what is not working and details about the os/browser/mode please feel free to add them here.
