### ISSUE TITLE
[@quasar/cli]Unable to start building main process.The console shows 'Main process [0%]'

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5991]
REPO：
https://github.com/hugetiny/negibox

Reproduce：
C:\Users\huget\WebstormProjects\downloadbox>quasar dev -m electron

 Dev mode.......... electron
 Pkg quasar........ v1.5.11
 Pkg @quasar/app... v1.4.3
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8081)... +4ms
 app:webpack Extending Renderer process Webpack config +944ms
 app:webpack Extending Main process Webpack config +371ms
 app:generator Generating Webpack entry point +6ms
 app:dev-server Booting up... +3ms

 Renderer process █████████████████████████ [100%] in ~14s
 Main process                               [0%]

**Platform (please complete the following information):**
NodeJs - 12.14.0

Global packages
  NPM - 6.13.4
  yarn - 1.21.1
  @quasar/cli - 1.0.5
  cordova - Not installed

Important local packages
  quasar - 1.5.11 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - 5.0.13 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - 21.2.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update
” support out of the box
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.7 -- Babel compiler core.
  webpack - 4.41.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support
loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - DESKTOP-FKIU25H
  以太网 - 192.168.31.134
  VirtualBox Host-Only Network - 169.254.48.227
  VirtualBox Host-Only Network #2 - 169.254.36.12
  VMware Network Adapter VMnet1 - 192.168.214.1
  VMware Network Adapter VMnet8 - 192.168.36.1

**Comment by hugetiny** [comment]
Node.js is still working in backgroud with a high cpu usage while console still showing:'Main process [0%]'

**Comment by hugetiny** [comment]
I tired to change Electron version from 5-7,and node.js version from 12 to 10 ,and nothing changes.

**Comment by TimWeidner** [comment]
@hugetiny how did you fix this?
