### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#5993]
nice to have customized (css) scrollbar for the all overflow contents including tables like scroll area

**Comment by Fanvadar** [comment]
You can change all scrollbars (except the scroll area ones) with native css (put in your app.styl file). Use `::-webkit-scrollbar` and `::-webkit-scrollbar-thumb`. 

Could look something like this: 
```
::-webkit-scrollbar {
    height: 12px;
    width: 14px;
    background: transparent;
    z-index: 12;
    overflow: visible;
}

::-webkit-scrollbar-thumb {
    width: 10px;
    background-color: #c1c1c1;
    border-radius: 10px;
    z-index: 12;
    border: 4px solid rgba(0, 0, 0, 0);
    background-clip: padding-box;
    transition: background-color .32s ease-in-out;
    margin: 4px;
    min-height: 32px;
    min-width: 32px;
}

::-webkit-scrollbar-thumb:hover {
    background: #c1c1c1;
}
```

**Comment by shomalikhashayar** [comment]
### How to change color of scrollbar color dynamically?

**For example like this:**

`
::-webkit-scrollbar {
  height: 12px;
  width: 14px;
  background: transparent;
  z-index: 12;
  overflow: visible;
}

::-webkit-scrollbar-thumb {
  width: 10px;
  background-color: $primary;
  border-radius: 10px;
  z-index: 12;
  border: 4px solid rgba(0, 0, 0, 0);
  background-clip: padding-box;
  margin: 4px;
  min-height: 32px;
  min-width: 32px;

  &:hover {
    background: $primary;
  }
}
`

**Comment by shomalikhashayar** [comment]
I found problem we should use var(--q-primary).

background-color: var(--q-primary);

[webida](https://webida.ir)

**Comment by shomalikhashayar** [comment]
I found problem we should use var(--q-primary).

background-color: var(--q-primary);
