### ISSUE TITLE
Auto import feature not working

### ISSUE THREAD

**Issue by yuvraj2112** [quasarframework/quasar#5994]
Hi!
I recently upgraded quasar and quasar-cli to versions 1.5.11 and 1.4.3 respectively.

After upgrade, the auto-import feature seems to have stopped working. It works if I change the framework option from auto to true.
framework: { all: 'auto' -> true }
The build happens without any errors but this seems to be haunting me for no apparent reason.

Greatly appreciate any help in the matter.

**Screenshots**
![image](https://user-images.githubusercontent.com/11533989/71727738-3ee32380-2e61-11ea-8ea9-bd36fd817b9e.png)

**Comment by rstoenescu** [comment]
Any reproduction repo? Also, please fill in the full Github ticket template... What's your OS etc etc. Copy paste the output from "quasar info" pls.

**Comment by rstoenescu** [comment]
Please supply the requested information. Thank you.
