### ISSUE TITLE
[Request] QEditor debounce Support

### ISSUE THREAD

**Issue by mtrivera** [quasarframework/quasar#5996]
**Is your feature request related to a problem? Please describe.**
I have a q-editor that has its value get/set in the store, with six possible values based on buttons. I do not want to overload the store. 

**Describe the solution you'd like**
The ability to add the `debounce` value similar to the **QInput** component.

**Describe alternatives you've considered**
I've considered using the lodash debounce method but the Quasar **QInput** component has a `debounce` model available.

**Additional context**
It's a closed source application but can give a generic diagram if needed.

**Comment by pdanpdan** [comment]
You can use quasar's debounce function to update the model.
