### ISSUE TITLE
[perf / debug-optim. ] start q-scroll-observer inside q-layout only if needed

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#6001]
I often use vue-developer tools to debug our product. 

On all pages when i scroll, a un-debounced / un-throttled q-scroll-observer is emitting events / flooding the event-overview. I think this is needed, if a q-layout with header / footer reveal is used.

We are actually not use any reveal option, so i think this eventlistener is not needed. 
I tested with a commented q-scroll-observer my web-app, and all is working fine. Also pages with infinite-scroll (as they come with their own listeners).

If there is no more need - only for reveal - of the eventlistener, may this observer can be "optionated switch off" so the flooding stops and the overview for debugging is much easier (any also the emitting pollution).

**Comment by rstoenescu** [comment]
Hi,

Sorry but this is needed for several other cases that your app might not use. But there is no dynamic way to tell when not to use the observer. It gets even more complicated when dealing with SSR and hydration.
