### ISSUE TITLE
QDrawer behavior differences between icon/text avatars

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#6002]
**Describe the bug**
I use the QDrawer with QList where it's mini until the user mouses over.  Most of my QItems follow the standard Avatar / (non-Avatar) QItemSection pattern.  Until now my avatars have always been QIcons--and no issue.  Recently I wanted to use a text-based avatar.  Now alignment seems to be off when the QDrawer is in "standard" mode.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/robert123789/pen/XWJzvgr?&editable=true&editors=101

**To Reproduce**
Mouse over the QDrawer.  Notice that the "T" avatar "jumps" but the normal icons remain nicely in place.

**Expected behavior**
I would like text avatars to stay in their place.

**Screenshots**
Let me know if you need these.

**Platform (please complete the following information):**
OS: Windows 10 Desktop
Chrome (latest)

**Comment by metalsadman** [comment]
@rfox12 treat it the way you styled your icons to sm for it to be consistent. Ie. https://codepen.io/metalsadman/pen/BayJGJK?&editable=true&editors=101

**Comment by rfox12** [comment]
Thank you @metalsadman!!
