### ISSUE TITLE
[@quasar/cli]Print out all the useful info in console instead of ' █████████████████████████ '

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#6003]
**Describe the solution you'd like**
Directly print out all the useful info in console

**Describe alternatives you've considered**
Maybe commands like 'quasar dev --inspect' should be added

**Comment by hugetiny** [comment]
For developers to approach errors easier during building.

**Comment by rstoenescu** [comment]
Hi,

With all due respect, your description is vague.
You can use quasar.conf.js > build > showProgress: false. It allows the terminal to print out any errors during initial build.

**Comment by hawkeye64** [comment]
Also, sometimes `quasar build --debug` will show errors that you can't see with `quasar dev`.

**Comment by hugetiny** [comment]
@hawkeye64 Thanks，It works.
