### ISSUE TITLE
Issue with QBtn located in toolbar in browser IE11

### ISSUE THREAD

**Issue by jvaca92** [quasarframework/quasar#6004]
**Describe the bug**
The toolbar with QBtn behave really strange on mouse over. When I mouse over the QBtn on toolbar the button background change color to white and after few seconds to return normal. But anything else works fine as popup. 
Actually in Edge everthing works fine.

**Codepen/jsFiddle/Codesandbox (required)**
I am pasting here the snippet of the code, but actually Codepen or jsFiddle not work in IE11. https://jsfiddle.net/urfh6y2p/1/

**To Reproduce**
Just put QBtn in toolbar and used in IE11 and after mouse over you see the white background.

**Expected behavior**
I would expect the normal change of background of the QBtn on mouse over action.

**Screenshots**
![image](https://user-images.githubusercontent.com/14887227/71778854-5af6da00-2fb3-11ea-96f0-48ad62215ec9.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: v10.15.3
NPM:  6.4.1
Browsers: IE11

**Comment by pdanpdan** [comment]
Ref URL for testing: https://codepen.io/pdanpdan/pen/ZEYvXOb
https://cdpn.io/pdanpdan/debug/ZEYvXOb/vWMRwRKdDyJr

**Comment by jvaca92** [comment]
Maybe just for easier testing when you open dev web page of Quasar (https://quasar.dev/start/pick-quasar-flavour) and mouse over on button like Version or Tools then you can also see strange behavior of the buttons

**Comment by pdanpdan** [comment]
I just tested on IE11 on Win7 and I cannot reproduce, neither in the codepen nor in the Quasar docs site.
If you can add more details on how you get this error please put them here.
If you need to test make a fork of https://codepen.io/pdanpdan/pen/ZEYvXOb and open the debug view of it in IE.

**Comment by jvaca92** [comment]
I tried with the debug mode, but it required Pro which I do not have. Anyway can you please provide which version of IE11 are you using ? 
And little curries if can be some different between Win10 and Win7 of IE11 usage.

**Comment by pdanpdan** [comment]
It looks like they are - the one in Win10 is more broken than the one in Win7 :) - I can reproduce it on Win10

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.6.2.

**Comment by jvaca92** [comment]
Thanks for info and collaboration. Will look forward for new version.
