### ISSUE TITLE
[Request] Add component to stack toolbar buttons depend on screen size.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#6005]
On header toolbar can be many items, and if screen size is small need to move some to other place or to hide totally.

For example I have 10 buttons on header toolbar, but on mobile there is no place to fit them all, and only possible to fit 2. On tablet possible to fit 5. On wide screen PC 10.

So needed component which can show only needed items depend on screen size.

How I see this API:

```
<q-toolbar-hider>
   <q-btn  :hider-priority="1" moveTo="firstPlace" />
   <q-btn  :hider-priority="2" moveTo="firstPlace" /> 
   <q-btn  :hider-priority="3" moveTo="secondPlace" />
   ...
   <q-icon  :hider-priority="7"  moveTo="secondPlace"/>
</q-toolbar-hider />

...

<q-hider-placeholder name="firstPlace" />

...

<q-hider-placeholder name="secondPlace" />

```

- `hider-priority` is property to choose what component to hide first
- `q-hider-placeholder` can be not one but many with different nameы. And if we hide some component its moved to placeholder with corresponding name. If no `moveTo` selected just totally hide.

`hider-priority` and `moveTo` have to be vue directives and can be applied to any vuejs component or html tag.

And also I think this will be good idea (but do not know is this possible to move some items in many places, it will be useful in some cases.

```
  <q-btn moveTo="firstPlace,thirdPlace" />
```

This component can be made without correlation with q-toolbar, just `q-hider`, and to make it work in any place, and even with vertical alignment (if this is possible).

**Comment by pdanpdan** [comment]
You can use v-if/v-show, or if you need something complex you can use https://github.com/LinusBorg/portal-vue (or wait for Vue 3 where this is expected to be in the core).

**Comment by DimitrOkeanij** [comment]
I am thinking that on different places component visualization can be different.
For example on toolbar it is q-btn but when moved to side menu the same item can be q-item.

So I propose to make events on hiding/showing components inside `q-hider`. 
And on hide I will manually show corresponding component on side panel.
And on show - hide corresponding component on side panel.

Allow `moveTo` attribute to has `null` value, if I want to trigger manually.

------

The second way I see to make auto toggle effect.

```
<q-toolbar-hider>
   <q-btn  :hider-priority="1" moveTo="firstPlace" />
   <q-btn  :hider-priority="2" toggle="someId,someId2" /> 
</q-toolbar-hider />

<q-item id="someId" />

<div id="someId2"> </div>

```
If the second button disappeared visibility of elements with  `someId` and `someId2` will be toggle.

**Comment by rstoenescu** [comment]
Hi,

Sorry but not feasible to implement with Vue.
