### ISSUE TITLE
[Feature Request] QSkeleton 'speed' property

### ISSUE THREAD

**Issue by tmartty** [quasarframework/quasar#6006]
**Is your feature request related to a problem? Please describe.**
QSkeleton animation has a fixed speed.

**Describe the solution you'd like**
Add a prop `speed` to the QSkeleton component.

**Describe alternatives you've considered**
Add a prop where you could pass the `ms` for the animation duration, or maybe just a preset with `slow`, `fast` values or something similar.

The `ms` approach is probably harder sincer you'd need to somehow grab that prop from the js file and use it on sass. However, maybe that particular animation can be moved to be done through js in the same file where the prop is recieved. Otherwise, the presets approach might be easier since it'd require to just make a couple different classes.

**Additional context**
PS: Loved the new QSkeleton component!

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.1.10
