### ISSUE TITLE
[Request] Allow Numbers in q-autocomplete

### ISSUE THREAD

**Issue by damosse31** [quasarframework/quasar#601]
Hi !

is it possible for a new release, to allow Numbers values in q-autocomplete model ?

actually, q-autocomplete allow only String values and sometimes we have values as Number (ex: VAT)

Code below fail : (Invalid prop: type check failed for prop "value". Expected String, got Number.)
```
let MyVAT = 20
<q-autocomplete v-model="MyVAT" @search="searchVAT">....
```

Code below work :
```
let MyVAT = "20"
<q-autocomplete v-model="MyVAT" @search="searchVAT">....
```

I use release 0.13.9

**Comment by rstoenescu** [comment]
Hi, Yes, all types will be available in v0.14.
