### ISSUE TITLE
copyToClipboard not work on Android

### ISSUE THREAD

**Issue by Yelvabaoji** [quasarframework/quasar#6013]
**Describe the bug**
copyToClipboard works fine on windows desktop browser. But failure on Android app.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Come on, man. Give more info. What Android, what environment (mobile browser or cordova or capacitor, and if cordova then what webview). Also, there's a `.catch(err => { ... })` that can be used. What does the error say? If on cordova or capacitor, do you have enough permissions to copy to clipboard?

**Comment by hawkeye64** [comment]
@Yelvabaoji Likely permission. Please read here for more info: https://developers.google.com/web/updates/2018/03/clipboardapi#security_and_permissions
