### ISSUE TITLE
Disable server side sorting

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#6014]
When table is server-side, prop `sort-method` doesn't work I want to prevent a request for sorting and locally do sort, at the moment it doesn't work.

**Comment by rstoenescu** [comment]
How is this a bug? At best, it's a feature request. BUT, when table is server-side you're in full control of what happens to your data. You get the params and you can decide what to do with them.. make a server request, do local computation (in your case you can use a Vue ref on your QTable and manually call "sortMethod(data, sortBy, descending)" on it) etc etc.

**Comment by miladmeidanshahi** [comment]
Many thanks, @rstoenescu the important part of the issue is that we can't stop requests on sorting.
Can you show me an example?
