### ISSUE TITLE
[Request] Slide Cell Component

### ISSUE THREAD

**Issue by jblyberg** [quasarframework/quasar#6018]
**Is your feature request related to a problem? Please describe.**
Not directly, but it would be a useful UI feature to have native in Quasar.

**Describe the solution you'd like**
A mobile cell slider component, similar to https://youzan.github.io/vant/#/en-US/swipe-cell that can be used for custom actions.

**Comment by pdanpdan** [comment]
You mean this? https://quasar.dev/vue-components/slide-item

**Comment by jblyberg** [comment]
Yes, but with the ability to add additional options/buttons.

**Comment by smolinari** [comment]
You can create whatever you want in the slots (which is the awesome power of slots), so like you can do the reset of the slider after any "button actions" are carried out. Here is a lame example. Slide the top slider to the left.

https://codepen.io/smolinari/pen/eYmyaqW?editors=1010

Scott
