### ISSUE TITLE
Add router 'prefixWith' helper

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#6021]
**Is your feature request related to a problem? Please describe.**
When using vue router, it's currently not possible to logically group multiple routes with the same prefix while keeping them at the same router-outlet level of ther others.

Example
```ts
// This won't work
const routes = [
  {
    path: '/',
    component: () => import('layouts/frame.vue'),
    children: [
      { path: '', component: () => import('pages/home.vue') },
      { path: 'home', component: () => import('pages/home.vue') },
      {
        path: 'products',
        children: [
          { path: '', component: () => import('pages/products.vue') },
          {
            path: 'type-a',
            component: () => import('pages/product-type-a.vue'),
          },
          {
            path: 'type-b',
            component: () => import('pages/product-type-b.vue'),
          }
        ],
      },
      { path: 'company', component: () => import('pages/company.vue') }
    ],
  },
];

// This will work, but you have to repeat the parent path name
const routes = [
  {
    path: '/',
    component: () => import('layouts/frame.vue'),
    children: [
      { path: '', component: () => import('pages/home.vue') },
      { path: 'home', component: () => import('pages/home.vue') },
      { path: 'products', component: () => import('pages/products.vue') },
      { path: 'products/type-a', component: () => import('pages/product-type-a.vue') },
      { path: 'products/type-b', component: () => import('pages/product-type-b.vue') },
      { path: 'company', component: () => import('pages/company.vue') }
    ],
  },
];
```

**Describe the solution you'd like**
Current suggested workaround is to create a [`prefixWith` helper](https://github.com/vuejs/vue-router/issues/745#issuecomment-263410514), which would already be enough.

Another step would be to detect when `component` isn't provided on the parent route and automatically flat it, or add a `logical` property which serve the same purpose (detect routes to be flattened) but is more explicit about what's going to happen.

**Describe alternatives you've considered**
Adding a notice on the docs linking to the proposed solution from Evan You.

**Comment by IlCallo** [comment]
Minimal solution (with helper function)

```ts
function withPrefix(prefix, routes) {
  return routes.map(route => {
    route.path = prefix + '/' + route.path;
    return route;
  });
}

const routes = [
  {
    path: '/',
    component: () => import('layouts/frame.vue'),
    children: [
      { path: '', component: () => import('pages/home.vue') },
      { path: 'home', component: () => import('pages/home.vue') },
      ...withPrefix('products', [
        { path: '', component: () => import('pages/products.vue') },
        { path: 'type-a', component: () => import('pages/products-type-a.vue') },
        { path: 'type-b', component: () => import('pages/products-type-b.vue') },
      ]),
      { path: 'company', component: () => import('pages/company.vue') }
    ],
  },
];
```

**Comment by rstoenescu** [comment]
Hi,

This should be suggested to the vue-router repo at best. But my opinion is that they'll recommend you to use your helper function :)

**Comment by pdanpdan** [comment]
If somebody needs something like this the solution is pretty simple. And the Quasar docs are not a coverall for the vue/vuex/vue-router/javascript documentation.

**Comment by IlCallo** [comment]
Quasar already adds a lot of helper functions to make working with Vue easier, that's why I asked it here: on vue-router they already stated it's something they don't want to add, even if many devs was wondering why it isn't already baked-in, being a well known problem.

Thank you anyway :)

**Comment by metalsadman** [comment]
@IlCallo cool helper, it's a shame vue router doesn't take care of this ootb for deep nested routes, couldve made route configs more reusable when you want them to be modularized instead of planning or structuring them beforehand.

**Comment by IlCallo** [comment]
[Here](https://github.com/vuejs/vue-router/issues/745#issuecomment-571648240) I provided my implementation to automatically detect and flat logical nested routes.

It's easy to integrate it into `index.js` Quasar router file

**Comment by IlCallo** [comment]
We released a package to address this problem
https://github.com/dreamonkey/vue-routes-flattener
