### ISSUE TITLE
quasar dev fails on iOS 13

### ISSUE THREAD

**Issue by Rosadojonathan** [quasarframework/quasar#6026]
Hi there!

@quasar/app => 1.4.3
@quasar/cli => 1.0.5
Xcode => 11.3

iOS 13.3

Whenever I try to run `quasar dev -m cordova -T ios` the commands fails with the following error

```
2020-01-08 10:28:28.564 ios-deploy[27512:8368418] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253
 app:spawn Command "cordova" failed with exit code: 253 +0ms
```

Has anyone else faced the same issue? I didn't have when I was on iOS 12. I suspect it has something to do with it.

**Comment by pdanpdan** [comment]
Yes, google has seen a lot of these error messages: the first one links to this: https://github.com/ios-control/ios-deploy/issues/292
