### ISSUE TITLE
Aspect ratio for QVideo

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#6032]
**Is your feature request related to a problem? Please describe.**
QVideo is sometimes very thin (not high enough) when the surrounding div is wide.

**Describe the solution you'd like**
I would like the ability, just like QImg, to keep aspect ratio of a regular video.

**Describe alternatives you've considered**
Write my own CSS.
I was able to temporarily fix it by adding this CSS to the wrapper div:
```css
height: 0
padding-bottom: 50%
```

**Additional context**
Here's a screenshot:
![IMG_AB21976BC500-1](https://user-images.githubusercontent.com/3253920/72026640-7d446c80-32bf-11ea-86bd-f21b0923c0af.jpeg)

I'd like the video to be much higher by default, but only if the surrounding div is as wide as this.

**Comment by pdanpdan** [comment]
Add a codepen

**Comment by rstoenescu** [comment]
Will be available in "quasar" v1.6.2 through new "ratio" prop (Number).
