### ISSUE TITLE
Qtoggle support for an array of objects using val

### ISSUE THREAD

**Issue by msacchetti** [quasarframework/quasar#6033]
using other UI frameworks you can use an array of objects to bind the toggle values. in this framework, the value has to be a string.

here is a codepen example of it not working. this works in frameworks like Buefy but not in Quasar. i cant use quasar in my project because i have so much code relying on this functionality already

https://codepen.io/msacchetti/pen/KKwodQg

**Describe the solution you'd like**
this code below does not work, and it would be great if it did (see codepen for example)
```
            <q-toggle
              v-for="t in topics"
              v-model="userTopics"
              :val="{
                topic: t.topicName,
                cat: t.categoryId
              }"
            />

```

:val only works if it is a string like so

```
            <q-toggle
              v-for="t in topics"
              v-model="userTopics"
              :val="t.topicName"
            />

```

**Comment by pdanpdan** [comment]
First, what you are using is an object, not an array.
Second, the object created from a literal object will always be different than another object created from the same literal object.

https://codepen.io/pdanpdan/pen/jOEzMpz?editors=1010

**Comment by msacchetti** [comment]
> https://codepen.io/pdanpdan/pen/jOEzMpz?editors=1010

just want to say thanks for the help. now seeing your example, it looks like Buefy just does the map() function automatically so I didnt think to implement the mapping.

cheers

**Comment by msacchetti** [comment]
> https://codepen.io/pdanpdan/pen/jOEzMpz?editors=1010

Actually, this solution doesnt work between route changes
