### ISSUE TITLE
no-hover not working if q-table element is in slot

### ISSUE THREAD

**Issue by marekkaczkowski** [quasarframework/quasar#6035]
**Describe the bug**
When `<q-tr>` or `<q-td>` with `no-hover` attribute is in q-table's slot (eg. `bottom-row`) class responsible for no-hover effect is not rendered on elements. However, we can manually add `q-td--no-hover` class.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/objective-sun-yxfk3

**To Reproduce**
1. Go to q-table
2. Add `<template v-slot:bottom-row="props">...</template>` slot
3. Add `<q-tr><q-td no-hover>...</q-td></q-tr>` in slot (no-hover on `tr` acts the same)
4. `<q-td no-hover>` still has hover row effect

**Expected behavior**
Hover effect should be removed (`q-td--no-hover` class should be rendered on element) if `no-hover` attribute is present on `<q-tr>` or `<q-td>` elements in slots.

**Platform (please complete the following information):**
OS: Windows_NT(10.0.17763) - win32/x64
Node: 12.13.1
NPM: 6.12.1
Yarn: 1.19.2
Browsers: Chrome 79.0.3945.117
Quasar: 1.6.1

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.6.2.
