### ISSUE TITLE
Error when switching to grid mode <-> list mode on QTable

### ISSUE THREAD

**Issue by furyscript** [quasarframework/quasar#6038]
I got this console error
```Error in callback for watcher "needsReset": "TypeError: Cannot read property 'reset' of undefined"```
When I switch on grid-mode with a button and return to list-mode on QTable.
I have virtual scroll enable and the problem is on that line: https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/QTable.js#L118
Because the refs isn't ready.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.6.2.
