### ISSUE TITLE
Horizontal Card

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6040]
Horizontal Card not exists ?

**Comment by pdanpdan** [comment]
What do you mean?

**Comment by nseb** [comment]
Like vueify : https://vuetifyjs.com/en/components/cards#horizontal-cards

**Comment by pdanpdan** [comment]
I still fail to see what you mean. Just use flex classes to obtain your desired layout.

**Comment by rstoenescu** [comment]
What you want will be available in "quasar" v1.7.0 through QCardSection with "horizontal" prop.

**Comment by nseb** [comment]
@rstoenescu Thanks,  it's will possible to control ratio vs section ?
