### ISSUE TITLE
draggable tree

### ISSUE THREAD

**Issue by qzzm** [quasarframework/quasar#6044]
Can drag and drop Tree nodes by adding a draggable attribute?
Demo:
https://element.eleme.cn/#/en-US/component/tree#draggable

**Comment by DimitrOkeanij** [comment]
Yes. Needed feature.

**Comment by Trellian** [comment]
+1

**Comment by pdanpdan** [comment]
Moving this to the generic request - https://github.com/quasarframework/quasar/issues/5890
