### ISSUE TITLE
QTable: bad row highlighting on IE 11

### ISSUE THREAD

**Issue by blaluc** [quasarframework/quasar#6045]
Tested on Quasar V.1.6.1
The background color of highlighted table rows on IE 11 is not uniform:
![image](https://user-images.githubusercontent.com/4599417/72086719-b274ad00-3307-11ea-9bb6-856230244a89.png)

**Comment by pdanpdan** [comment]
I'm sorry but I can find no easy solution to fix it. I cannot test right now but in theory this problem should be only on IE11 on Win7 - on Win10 it should be fixed in the browser.
I'll leave this issue open and maybe somebody can find a solution.

**Comment by rstoenescu** [comment]
Microsoft just ended support for Windows 7. Since this issue happens only on IE11 with Win 7, then it's time to consider this as obsolete. Sorry for any inconveniences.
