### ISSUE TITLE
App can not connect from iPhone to development server

### ISSUE THREAD

**Issue by qstiegler** [quasarframework/quasar#6047]
I want to test my application on my iPhone. Therefor I use the command `quasar build -m capacitor -T ios` and by connecting the iPhone through my cable to my MacBook and transfer the App to the phone by Xcode. Sadly the screen of the app on the iPhone stays white after showing the app icon.

In the developer console of Xcode there is the error message: `Error: A server with the specified hostname could not be found.`

When I try the same by the Simulator of Xcode it works as expected and the app gets loaded correctly.

On the following documentation page `https://quasar.dev/quasar-cli/developing-capacitor-apps/build-commands` there is the sentence `In order for you to be able to develop on a device emulator or directly on a phone (with Hot Module Reload included), Quasar CLI follows these steps:`. Cause of this sentence I expected that it also works on a connected phone.

I think I don't have access to the localhost of my MacBook by the iPhone. Is something missing in my configuration or is maybe something missing in the documentation?

In the `quasar.conf.js` my dev server is configured like that:

```
    devServer: {
      https: true,
      host: 'app.example.localhost',
      port: 4300,
      open: true, // opens browser window automatically
      proxy: {
        '/api': {
          target: 'https://app.example.localhost',
          changeOrigin: true,
          secure: false
        }
      }
    },
```

OS: macOS 10.15.2
Node: 10.16.3
NPM: 6.9.0
iOS: 13.3

**Comment by rstoenescu** [comment]
Hi,

Your phone and development machine must be in the same network and the phone must be able to resolve the address. It's right there in the docs...
