### ISSUE TITLE
Bug: QSelect can't add new values in Dialog mode, if the filter function has a delay.

### ISSUE THREAD

**Issue by mortenscheel** [quasarframework/quasar#6048]
**Describe the bug**
The "new-value" feature seems to be broken when QSelect uses a dialog and the filter function doesn't update the options immediately.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/qselect-dialog-issue-h5ev9

**To Reproduce**
See the codesandbox for more detailed examples and exceptions.

1. Set `behavior="dialog"`
2. Set `new-value-mode` and/or listen for `@new-value`
3. Use a `@filter` listener that updates the options after a delay

**Expected behavior**
The `new-value` feature ought to work consistently, regardless of behavior mode, or filter latency

**Screenshots**

**Platform (please complete the following information):**
OS: Tested on MacOS and Win10
Node: v13.6.0
NPM:  v6.13.4
Yarn: v1.21.1
Browsers: Tested in Chrome, Firefox and Safari
iOS: Only tested in SPA mode.
Android: Only tested in SPA mode.
Electron: Only tested in SPA mode.

**Additional context**
As far as I can tell, the issue is that QSelect's `this.$refs.target` disappears, or points at something other than the `input` element. This results in the `keydown` event getting ignored because it's not coming from the target (`QSelect.js  in __onTargetKeydown`).

**Comment by smolinari** [comment]
Has to be the best presented reproductions I've seen to date. Nice work. 👍 

Scott

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this!
Fix will be available in "quasar" v1.7.0.
