### ISSUE TITLE
QTable not updating properly when connected to server

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#6053]
**Describe the bug**
In a QTable connected to a server, when you make a search, change records per page to all, then clear that search, you end up with an incorrect number of results (in my example it shows 4 results but says at the bottom 1-40 of 40).  

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/table#Server-side-pagination%2C-filter-and-sorting

**To Reproduce**
1. Go to the docs -> QTable -> 'Server side pagination, filter and sorting' section -> the example table
2. Type "Fr" into the search bar of the example table
3. Change records per page to "All"
4. Clear the search bar of text

**Expected behavior**
This should then display all results without any filtering, but it only shows 4.

**Screenshots**
![image](https://user-images.githubusercontent.com/11305093/72126482-ff17c100-33b7-11ea-959c-1a531d22713c.png)

**Platform (please complete the following information):**
OS: Windows
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
I originally found this problem in my own project, then found it within the docs.

**Comment by rstoenescu** [comment]
Hi,

Thanks for spotting this in the docs example. The corrected example will be available on next docs deployment. Link before it is officially available: https://github.com/quasarframework/quasar/blob/dev/docs/src/examples/QTable/Synchronizing.vue
