### ISSUE TITLE
Heartbeat animation

### ISSUE THREAD

**Issue by moas** [quasarframework/quasar#6054]
Hi

Heartbeat animation is not supported! can you please add it?

Thx

**Comment by smolinari** [comment]
We use Animate CSS and it supports it. 

https://quasar.dev/options/animations#Usage
https://daneden.github.io/animate.css/

Scott

**Comment by smolinari** [comment]
Sorry. I see the issue. It's missing in extras. 

Scott

**Comment by rstoenescu** [comment]
and some other missing too. "@quasar/extras" v1.4.2 will have an up to date "animate.css".
