### ISSUE TITLE
QCheckbox: size prop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#6057]
**Is your feature request related to a problem? Please describe.**
I need a larger size checkbox for an iPad app for elderly.

**Describe the solution you'd like**
`<q-checkbox size="lg" />`

**Describe alternatives you've considered**
I am currently using css `transform: scale(2)` but it's a little bit blurry. (luckily the elderly don't care so much.)

**Additional context**
I believe QCheckbox is one of the few components without a `size` prop. Having this `size` prop would be a great addition, just like the other components.

**Comment by rstoenescu** [comment]
"size" prop will be available for QCheckbox/QRadio/QToggle in v1.8.0.
(standard sizes also supported: xs, sm, md, lg, xl)

**Comment by mesqueeb** [comment]
Wow so great!!! Thank you so much !!
