### ISSUE TITLE
[docs] Serveo is down, provide localhost.run as alternative

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#6059]
https://quasar.dev/quasar-cli/opening-dev-server-to-public

Serveo is down because too many people used it to perform phishing attacks or spamming.
I found a new service (https://localhost.run/) which does the same thing, I don't know if it has downsides.

**Comment by rstoenescu** [comment]
@IlCallo can you please update docs with this? replace serveo with localhost.run pls.
