### ISSUE TITLE
Add transparency function in colors

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6060]
Like lighten or luminosity , it's possible to add function to adjust transpareny color

**Comment by Valianton** [comment]
Or, use [sass less stylus] built-in functions, like this http://stylus-lang.com/docs/bifs.html?

**Comment by nseb** [comment]
@Valianton  it's possible  , but in javascript block not

**Comment by rstoenescu** [comment]
`updateAlpha(color: string, value: number)` (where "value" can be an offset) will be available in "quasar" v1.7.2.
