### ISSUE TITLE
Bug: QField with validation error and no value should only have a floating label if focused.

### ISSUE THREAD

**Issue by mortenscheel** [quasarframework/quasar#6065]
**Describe the bug**
A field with an error always has a floating label, even if the value is empty, and it isn't focused.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/q-field-empty-floating-label-7w5r7

**To Reproduce**
See the codesandbox for an example.
1. Create a `QInput` with an empty string as model.
2. Set `:error="true"`

The label will float

**Expected behavior**
The label should only float if the field
1. Is focused or
2. Has a value or
3. Has the `stack-label` prop

It should matter whether the field has an error or not.

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.13.1
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Chrome
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
Not sure if it's the official standard, but on [material.io](https://material.io/components/text-fields/) the label doesn't float in this case.

**Comment by rstoenescu** [comment]
This was the recommended approach on Material Guidelines at some point. They frequently change the specs. Updated behavior coming in "quasar" v1.7.0.

**Comment by mortenscheel** [comment]
Great, thanks.
