### ISSUE TITLE
Multiple chunks emit assets to the same filename

### ISSUE THREAD

**Issue by bmansfie** [quasarframework/quasar#6071]
Nobody seems to be looking at the other issue that was previous closed due to lack of reproducibility, so I'm opening this new one to make sure it gets looked at.

This error occurs during the production build step.

ERROR in chunk 8daa19ae
js/8daa19ae.8a00ee1b.js
Conflict: Multiple chunks emit assets to the same filename js/8daa19ae.8a00ee1b.js (chunks 8daa19ae and 8daa19ae)

app:build [FAIL] Build failed with errors. Check log above. +0ms

I prepared a smallish project with the build issue. The packages are part of the issue so this has the dependencies included.  I'm using a private package that seems to be at the heart of the issue and you can't just install that with npm/yarn so I've bundled it all up here.

https://www.sharpsoftware.dev/dl/quasar/buildIssueDebug.tar.gz

Extract and try to build and it should produce the above error.

**Comment by nothingismagick** [comment]
Yeah - I am seeing something similar, thanks for reproducing it! My setup uses a yarn workspace and I am linking to app extensions that are not published on NPM either.

```
ERROR in chunk 8daa19ae
js/8daa19ae.7552df51.js
Conflict: Multiple chunks emit assets to the same filename js/8daa19ae.7552df51.js (chunks 8daa19ae and 8daa19ae)


 app:build [FAIL] Build failed with errors. Check log above
```

**Comment by rstoenescu** [comment]
I was looking at the initial ticket just yesterday :) Sorry it takes so long, but a lot on the plate at the moment. It will get fixed, just hang in there for a bit longer.

Before I look at the reproduction repo, some info: the chunk names are generated based on their content. So, do you have duplicates?

**Comment by rstoenescu** [comment]
@bmansfie I looked at the tar.gz, but seems incomplete. I get missing authModule on it.

```
ERROR in ./src/boot/auth.js
Module not found: Error: Can't resolve 'authModule/boot' in '/Users/Razvan/Downloads/quasarBuildIssueDebug/src/boot'
 @ ./src/boot/auth.js 1:0-43 2:15-27
 @ ./.quasar/client-entry.js
 @ multi ./.quasar/client-entry.js

ERROR in ./src/router/routes.js
Module not found: Error: Can't resolve 'authModule/routes' in '/Users/Razvan/Downloads/quasarBuildIssueDebug/src/router'
 @ ./src/router/routes.js 3:32-60
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi ./.quasar/client-entry.js
```

**Comment by nothingismagick** [comment]
don't run yarn @rstoenescu

**Comment by rstoenescu** [comment]
@nothingismagick that can't change anything. Imported files are still missing (authModule/boot, authModule/routes)... :|

**Comment by nothingismagick** [comment]
[authModule.zip](https://github.com/quasarframework/quasar/files/4053597/authModule.zip)

**Comment by nothingismagick** [comment]
just unzip and place in node_modules

**Comment by rstoenescu** [comment]
Are you two working together?

**Comment by nothingismagick** [comment]
No, but I am facing a similar situation and I was able to replicate with his repo. Would love to have this sorted.

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v1.5.0.

**Comment by rstoenescu** [comment]
@bmansfie thanks for supplying a reproducible case
@nothingismagick thanks for pointing out the authModule was already in node_modules and no yarn/npm install was necessary

**Comment by bmansfie** [comment]
Excellent :)
