### ISSUE TITLE
q-mt-auto & q-mb-auto

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#6073]
**Is your feature request related to a problem? Please describe.**

I was surprised that `.q-mt-auto` doesn't work. I checked the [docs](https://quasar.dev/style/spacing#Syntax) and it seems it's only available for x-axis directions.

I feel that it's completely normal to have situations where a flexbox `.column` has a set height and you want the last child to automatically stick to the bottom. In this case you'd use `.q-mt-auto`.

**Describe the solution you'd like**
I'd like `.q-mt-auto` and `.q-mb-auto` and `.q-my-auto` to exist.

**Describe alternatives you've considered**
Add these classes myself is an alternative, but I really think they _should_ be in Quasar for these reasons:
- it's completely normal to do something like i described above and other devs will certainly try the same
- there's not really a good reason I can think of to **not** provide the `-auto` classes _just_ for the y-axis...
- it's better to be consistent
- giving a wonderful paradigm to combine these: `q-[p|m][t|r|b|l|a|x|y]-[none|auto|xs|sm|md|lg|xl]` but **just not provide the y-axis for `-auto`** just seems strange, and it's difficult for devs when working with Quasar to remember which combinations of this paradigm are not existent.

**Comment by rstoenescu** [comment]
Hi,

This has been discussed before. Please check the archive...

**Comment by rstoenescu** [comment]
Auto margins do not work with top and bottom. If the value has been set to auto, the specs define that the used value for top and bottom will be zero. That applies to inline and block level elements.

http://www.w3.org/TR/CSS2/visudet.html#Computing_heights_and_margins

**Comment by drank** [comment]
> Auto margins do not work with top and bottom. If the value has been set to auto, the specs define that the used value for top and bottom will be zero. That applies to inline and block level elements.
> 
> http://www.w3.org/TR/CSS2/visudet.html#Computing_heights_and_margins

Yes, but not true for flexbox:

1. https://stackoverflow.com/a/33856609
2. http://www.w3.org/TR/css-flexbox-1/#auto-margins

Please reconsider.

**Comment by rstoenescu** [comment]
@drank ok, they'll be in "quasar" v1.9.12.
* q-mx-auto
* q-mt-auto
* q-mb-auto

**Comment by drank** [comment]
@rstoenescu , thank you very much for that!

Minor detail - I believe you mean `q-my-auto` in the 1st bullet since `q-mx-auto` is already there :)

**Comment by rstoenescu** [comment]
Yes, typo :)

**Comment by rstoenescu** [comment]
Edited above to avoid confusions.

**Comment by drank** [comment]
Great, let's then remove our obsolete comments then, to not clutter the conversation. I'll remove mine.

**Comment by ddenev** [comment]
@rstoenescu 
Could you please also add it to `size.styl`? I have upgraded to 1.9.12 and the new values do not appear in `quasar.styl`

**Comment by rstoenescu** [comment]
Oops. Pushed but will be available in 1.9.13.
