### ISSUE TITLE
All Quasar bundled in library using Quasar Notify

### ISSUE THREAD

**Issue by gbouteiller** [quasarframework/quasar#6074]
**Describe the bug**
I have a library that makes use of `Notify` with : `import { Notify } from 'quasar';`.  When I use my library inside a project and use `quasar prod`, all **Quasar** is bundled inside my library in the vendor file.

**Expected behavior**
Quasar not added to the library as it is already included in the project.

**Comment by rstoenescu** [comment]
Hi,

Configure your library's build system to treat "quasar" package as external.

**Comment by gbouteiller** [comment]
@rstoenescu  thank you, it works!
But for my own understanding, as it was working before, I'm curious about the possible cause? 
Indeed, my library and my quasar projects are part of a monorepo and so, the library source code is directly used by the project so there is no other compilation apart from the one for the quasar project. Any thoughts?

**Comment by rstoenescu** [comment]
It's hard to help you without details (a repo with your use-case)...

**Comment by gbouteiller** [comment]
@rstoenescu  you're totally right, I'm gonna make some tests and create a repo, it was just to have a lead if you had one :). I'll be back soon ;)

**Comment by gbouteiller** [comment]
@rstoenescu here it is : https://github.com/gbouteiller/monorepo

**Comment by gbouteiller** [comment]
@rstoenescu any news?
