### ISSUE TITLE
The link to the JDK is incorrect.

### ISSUE THREAD

**Issue by patrickmonteiro** [quasarframework/quasar#6077]
![image](https://user-images.githubusercontent.com/13258255/72213376-d0d7d580-34cc-11ea-87ee-7da639adaad2.png)

In cordova documentation, for preparation the link is pointing to a page that no longer exists.
The correct link would be: https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by jesusvilla** [comment]
@patrickmonteiro Done #6078

**Comment by rstoenescu** [comment]
Thx to both of you!
