### ISSUE TITLE
[docs] QTable (Synchronizing with Server) sorting issue

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#6080]
When you sort by description it does not work. Then if you sort by something else, it takes 2 tries after sorting by desc.

![QTable-binary-state-sort--issue](https://user-images.githubusercontent.com/10262924/72219469-b66d1e80-3503-11ea-9dac-3c6849827e09.gif)

**Comment by pdanpdan** [comment]
Fixed on the docs site.
