### ISSUE TITLE
Swipe down on bottom q-dialog

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6082]
If we use `q-dialog` and set `position` equals `bottom` (I mean it useful at mobile screens), I wonder we're able to swipe it down to hide dialog window.

**Describe the solution you'd like**
Maybe prop of `q-dialog` smth like `hideOnSwipe`

**Comment by rstoenescu** [comment]
Hi,

I think this has already been requested but can't find the ticket atm (sorry for not supplying it). Closing. This will get into Quasar, but it's not a high priority currently.

**Comment by pdanpdan** [comment]
https://github.com/quasarframework/quasar/issues/5202
