### ISSUE TITLE
After using quasar.ie.polyfills.umd.min.js file for or UMD/Standalone project to support it in IE 11 but still it not support in IE11.

### ISSUE THREAD

**Issue by ravimule22** [quasarframework/quasar#6085]
Hello @rstoenescu I used quasar.ie.polyfills.umd.min.js for UMD/Standalone project to support it in IE 11 but still it not support in IE11. I placed this script before the vue and qusar tag.
Ex -

<script src="https://unpkg.com/quasar-framework@0.17.20/dist/umd/quasar.ie.polyfills.umd.min.js"></script>
<div id="app" v-cloak >		
	<form id="userLogout" action="<%=apiURL%><%=pageURL%>" method="post"></form>

<q-dialog v-model="dialog.show" :persistent="dialog.showCancel" >
    
  </q-dialog>
	
</div>

 
<script src="https://cdn.jsdelivr.net/npm/quasar@17.20/dist/quasar.ie.polyfills.umd.min.js"></script> 

<script src="./common/vue/js/vue-2.6.js"></script>

<script src="https://cdn.jsdelivr.net/npm/quasar@1.1.0/dist/quasar.umd.min.js"></script>
    Functions..................
 </body>

**Comment by rstoenescu** [comment]
Hi,

You are using v0.17 for the IE polyfills and v1.1.0 for the Quasar UI... Versions do not match. Please correct the version. Also notice the change in package name: "quasar-framework" (0.17) vs "quasar" (v1).

**Comment by ravimule22** [comment]
Hello @rstoenescu , I used same version to all file still in IE 11 it shows source code.
<body>
   <script src="https://cdn.jsdelivr.net/npm/quasar@1.7.0/dist/quasar.ie.polyfills.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@^2.0.0/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@1.7.0/dist/quasar.umd.min.js"></script>
   
  
	 <div id="app" v-cloak >
	
		<cnx-page v-if="viewRoot.pageLoaded" v-bind:uiprops="viewRoot.uiprops" v- bind:model="viewRoot.model" :key="viewRoot.key" ></cnx-page>
			
	
		<form id="userLogout" action="<%=apiURL%><%=pageURL%>" method="post"></form>
	
	<q-dialog v-model="dialog.show" :persistent="dialog.showCancel" >
        <q-card class="bg-primary text-white" dark>
          <q-card-section class="row items-center dialog">
            <q-avatar :icon="dialog.icon" color="blue-7" text-color="white" ></q-avatar>
            <div class="text-h6 q-pl-md">{{ dialog.title }}</div>
            
          </q-card-section>    
        </q-card>
      </q-dialog>
	</div>

   <script	src="./common/jquery-2.1.1.js"></script>
	<script src="./common/js/moment.min.js"></script>
	<script src="./common/js/utils.js"></script>
 	 
 	<%@include file="/appfiles/v-zero/shared/components/ex.html" %>
</body>


Result - 
![Screenshot from 2020-01-13 12-20-30](https://user-images.githubusercontent.com/25847608/72237052-27ddc780-35ff-11ea-99fc-ddb0a44371a4.png)

**Comment by rstoenescu** [comment]
What does the console say?

**Comment by ravimule22** [comment]
Console shows some script errors but when i solved this they again generate other error. But this code works fine in chrome, firefox.
![Console log](https://user-images.githubusercontent.com/25847608/72239575-742d0580-3607-11ea-93ac-c062b0be99f0.png)

**Comment by rstoenescu** [comment]
There's an error in some other dependency. I see contineoEntity.js. It's not Quasar at fault here. Are your other dependencies transpiled?

Rechecked Quasar basecode -- works correctly on IE.

**Comment by ravimule22** [comment]
Thank u for help. Does any file automatically do transpile(dependency) for UMD/standalone project in IE11 ?

**Comment by rstoenescu** [comment]
UMD does not transpile because there's no build system in place to transpile.
Use Quasar CLI instead if UMD is not what you are looking for.

**Comment by ravimule22** [comment]
@rstoenescu  Ok, Thanks for help.
