### ISSUE TITLE
Cookie not working properly after v1.7... Cookie.has() always returns true

### ISSUE THREAD

**Issue by chamy098** [quasarframework/quasar#6087]
Cookie.has('xxxx') always returns true, even if the Cookie is an empty object.
//Will return true, but it doesn't exist
if(Cookies.has('cookie_name')){ 
//value will be null
var value = Cookies.get('cookie_name');
}

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this.
Fix will be available shortly in "quasar" v1.7.1.
