### ISSUE TITLE
The icon of the first q-step in a q-stepper cannot be configured.

### ISSUE THREAD

**Issue by jokase** [quasarframework/quasar#6089]
The icon of the first q-step cannot be configured.
It is always the "edit" icon.

See https://codepen.io/jokase/pen/OJPEWLZ 

![image](https://user-images.githubusercontent.com/9984868/72249499-6bc9d000-35f1-11ea-8686-6bce1bbad3bf.png)

**Comment by rstoenescu** [comment]
Hi,

This is not a bug. You are currently "editing" the "Select campaign settings" step, so the "active-icon" is used for it.
