### ISSUE TITLE
Support JavaFX WebView as wrapper

### ISSUE THREAD

**Issue by giflw** [quasarframework/quasar#609]
Hi

I'am a Java developer. Since Java 8 there is a WebView based on WebKit that can be used to run HTML apps. The JavaFX WebView allows for integration between the browser context and Java. This integration allows JavaScript to call Java code and vice-versa. So, one can use any Java library and call it from the HTML app as it was JavaScript. Some useful libraries in Java are for embedded RDMS or NOSQL, webservers and ORM.

One of the benefits would be enable the app to be distributed with a fully integrated backend using Java, making a transition between Java Desktop apps and SPA hybrid desktop apps easier to Java developers.

As a lot of people have Java already installed, this wrapper could have a option to set if a JRE should be embedded or not, allowing for reduced distribution size, as JRE should be installed by the client and only the needed java libraries would be delivered in distribution package.

Best regards

**Comment by rstoenescu** [comment]
If enough people become interested in this I'll give it a go. So please upvote this if you'd use it. Thank you!

**Comment by lakinmohapatra** [comment]
Is this quasar framework loading contents in webview for mobile app or its using native apis of android/ios ?

**Comment by rstoenescu** [comment]
It's using Cordova, so webview. Please read documentation.

**Comment by lakinmohapatra** [comment]
Thanks for informing . Instead of cordova , cant you guys develop something like react native or nativescript which can be used to build native apps ? Please let me know.

**Comment by jkirkby91-2** [comment]
@lakinmohapatra take a look at weex for that, is being built by alibaba group

**Comment by rstoenescu** [comment]
I'm sorry but due to the lack of interest in this from multiple people and also from very low resources available, I'm going to close this.
