### ISSUE TITLE
Excessive Q-Dialog padding

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#6092]
Hello,

The padding of a dialog created with $q.dialog is excessive.

This is a comparison between the dialog component (https://quasar.dev/vue-components/dialog) and the dialog plugin (https://quasar.dev/quasar-plugins/dialog):

![image](https://user-images.githubusercontent.com/371814/72250563-252da300-35fc-11ea-9f49-34496e8aa55c.png)

![image](https://user-images.githubusercontent.com/371814/72250588-31b1fb80-35fc-11ea-9f49-4eff601e611a.png)

As a side note, I wonder why the text is in grey by default when using the plugin, I think it should stay non-colored. Firstly for consistency between interfaces, secondly for user experience (no reason to put grey here), thirdly because I like my text color to be applied everywhere by default.

**Comment by rstoenescu** [comment]
The color is specified in the Material Guidelines...

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.7.2.
Wish this was reported a little eariler so it could have gone into 1.7.1 :)

Even though it's against Material Guidelines, I tend to agree with you on the color. So changed it too.

**Comment by louisameline** [comment]
Thank you so much.
