### ISSUE TITLE
Add QTable.scrollTo() method

### ISSUE THREAD

**Issue by pdwinkel** [quasarframework/quasar#6093]
**Is your feature request related to a problem? Please describe.**
Need possibility to set scroll position of QTable with virtual-scroll

**Describe the solution you'd like**
Add QTable.scrollTo() method (like QVirtualScroll has)

**Describe alternatives you've considered**
None

**Additional context**
You can get the current scroll position via: @virtual-scroll=“onVirtualScroll” or QTable

**Comment by pdanpdan** [comment]
For the moment please use the ref of ref :) like here: https://codepen.io/pdanpdan/pen/wvBXJqK

But it makes sense, so I'll create a PR.

@rstoenescu Do you think it makes sense to allow animated scrolling?

**Comment by pdanpdan** [comment]
This is now available in v1.7.2
