### ISSUE TITLE
icon loading delay

### ISSUE THREAD

**Issue by YakQin** [quasarframework/quasar#6097]
Hello,

when the icons are not rendered completely, we see the icon names on the page. I have the issue with my own implementations.

![q-icon](https://user-images.githubusercontent.com/17231180/72317274-a9068e80-36d3-11ea-9c1b-73ef991f3a81.JPG)

**Comment by Valianton** [comment]
Maybe you should use https://quasar.dev/vue-components/icon#Svg-icons

**Comment by YakQin** [comment]
Thanks, will try that
