### ISSUE TITLE
QSlider — @input & @change event does not fire by @mousedown.native

### ISSUE THREAD

**Issue by Valianton** [quasarframework/quasar#6098]
Everything is simple. In Quasar version 0, when user dispatch mousedown event model props in Qslider does not change. And visual thumb does not jump to new position. But in Quasar version 1 works differently.

I have two QSlider with one model. When i mousedown first QSlider, his thumb jump into new position, and his model has been changing, but he does not dispatch input or change. But this is wrong. If the slider visually changes with a mousedown, it should already generate an event (input or change) in order to synchronize the work of the second slider.

https://codepen.io/Valianton/pen/RwNJdEJ

**Comment by pdanpdan** [comment]
Can you give a step by step explanation of what is expected to happen in the codepen?

**Comment by rstoenescu** [comment]
Well, of course “input” and “change” are not triggered because the model already contains the new values since you manually update it. This is by design in order to avoid unnecessary vue renders.

**Comment by pdanpdan** [comment]
I think what he meant was that on the mousedown the knob gets into the new position, but the @input is only emitted on mouseup.

**Comment by Valianton** [comment]
No matter how to initiate and how to change.
There is an error in the component.
The error is that visually the slider changes its value with a mousedown, but the property of the model does not change.

**Comment by Valianton** [comment]
Look this https://v0-17.quasar-framework.org/quasar-play/android/index.html#/showcase/forms/slider
The slider visually changes when the user triggering click event;
In new version of Quasar the slider visually changes when the user triggering mousedown event;

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.7.2.
