### ISSUE TITLE
Qslider does not working in some cases

### ISSUE THREAD

**Issue by Valianton** [quasarframework/quasar#6099]
**Describe the bug**
![captured (1)](https://user-images.githubusercontent.com/6735990/72323689-1f52c300-36cb-11ea-9b6d-679ab6adb397.gif)

When i mousedown on slider and move up or down cursor for a 1px - QSlider not working

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this.
Fix will be available in "quasar" v1.7.2.

**Comment by Valianton** [comment]
Okey, but got another bug, if this is of course a bug.
![qslider--range--bug](https://user-images.githubusercontent.com/6735990/72701843-801e4780-3b72-11ea-9989-e9b2a9b9ce47.gif)

Bug repeat in _drag-range_ mode. To get this bug, do as it is written in my first post, but you need to do this on label. 

I expect a thumb drag, but a range drag occurs

**Comment by rstoenescu** [comment]
Hi,

This is not a bug. There's a fine line in detecting if dragging started between the points or outside the points.. in the gif above you're actually playing with that limit.
