### ISSUE TITLE
Fab button invisible on ipad

### ISSUE THREAD

**Issue by lordfuoco** [quasarframework/quasar#610]
### Software version

Quasar: 0.13.4
OS: OSX Sierra
Node: 7.10.0
NPM: 4.2.0
Browsers: Not reproducible on browsers
iOS: ios 9
Android: /
Any other software related to your bug:

### What did you get as the error?
Fab button inside a nested route with fixed-bottom right position, the fab is visible on the browsers and android, invisible on the ipad ( ios )  

### What were you expecting?

The fab button to be visible

### What steps did you take, to get the error?

quasar build ios
cordova build ios
run the app through xcode
test the app on the device

The problem is fixed by adding this override on the ios styl theme:
```
.layout-view {
  -webkit-overflow-scrolling: auto;
}
```

**Comment by rstoenescu** [comment]
Hi,

Thanks for filing this issue and also supplying a fix! In v0.14 the Layout has been rewritten from scratch using a completely different approach (syntax is 90% same though) so this is obsolete for it. Do you need this in v0.13 branch?

Cheers,
Razvan

**Comment by lordfuoco** [comment]
Hi,
No, I have the override in my css and I will try to upgrade and see how it works with 0.14 when I can.
Thank you for the quick reply

Cheers,
Nico

**Comment by rstoenescu** [comment]
You won't be needing the extra CSS in v0.14.
Ok, closing this issue now as it's obsolete in respect to v0.14, like I said.

Thanks.
