### ISSUE TITLE
[windows] @quasar/app local CLI: Quasar App Extension "upgrade" is missing

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#6100]
In Windows enviroment, WebStorm IDE, running `quasar upgrade` in WebStorm console produces an error:
```
 app Looking for Quasar App Extension "upgrade" command +0ms
 app:extension ⚠️  Quasar App Extension "upgrade" is missing... +25ms
```
It looks like WebStorm takes "@quasar/app" CLI instead of global "@quasar/cli"

Running the command `quasar upgrade` in project directory in normal Command Prompt works as expected.

Not sure if this is only WebStorm related, but is there any way to invoke global quasar CLI when running quasar upgrade?

**Comment by rstoenescu** [comment]
Hi,

Configure WebStorm terminal env PATH to also contain the global npm/yarn's node_modules.

**Comment by jeancaffou** [comment]
It is in path, because running it in other (non quasar) project, it just looks like the priority is messed up. Why not have different naming schemes for app and cli?

**Comment by rstoenescu** [comment]
Fix the priority then :) Global should be first.
Having different naming schemes would confuse a lot of people, historically speaking.. and it would be a breaking change atm -- so a no-go.

**Comment by drank** [comment]
Actually the problem is caused by a setting in WebStorm. Here is the description and the solution - https://stackoverflow.com/questions/53559809/phpstorm-webstorm-terminal-shows-old-npm-version

**Comment by jeancaffou** [comment]
@drank thanks, it works!
Also the option is only visible if `node_modules` exists in the project
