### ISSUE TITLE
Repeated padding when stacking various QCardSection 

### ISSUE THREAD

**Issue by jamesstylesage** [quasarframework/quasar#6101]
When various QCardSection are stacked in a card, the padding-top for the following sections were set to 0px. Prior to v1.7.0, this was working correctly with the following lines of styles:
  &__section + &__section
      padding-top: 0px

However, these lines were removed in 1.7.0, so now the distance between QCardSections are doubled. Is this the new expected behavior?

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, yes. The introduction of horizontal QCardSections makes this near impossible to easily handle custom cases, so it's better if the developer adds its own padding (or q-pt-none -- as in no top padding). Sorry for any inconveniences.
