### ISSUE TITLE
[QTabs] Consider supporting Boolean model?

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#6104]
I find it very useful in my apps to use q-tabs to toggle a boolean model, for example when filtering a list of items.

Would it be possible to have a support for a Boolean model out of the box? This can be managed in the user land by using 0 or 1, but this requires a bit of a custom handling when you transform this value to a query param for example.

See example: https://codepen.io/jean-moldovan/pen/RwNBWaZ?editable=true&editors=101

![Screen Shot 2020-01-14 at 5 17 04 PM](https://user-images.githubusercontent.com/3635352/72351747-fb56a800-36f1-11ea-9a1f-0f65bb54352a.png)

![Screen Shot 2020-01-14 at 5 16 59 PM](https://user-images.githubusercontent.com/3635352/72351636-c8141900-36f1-11ea-8c38-f4ae3af683a4.png)

**Comment by rstoenescu** [comment]
Hi,

Sorry but we won't support QTabs acting the same as a QToggle.
