### ISSUE TITLE
Tooltip in disabled button doesn't hide

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#6105]
**Describe the bug**
If you click a button with a tooltip and the click event disable the button, the tooltip doesnt hide.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/eduardodgarciac/pen/XWJBbOw

**To Reproduce**
1. Click the button
2. Move the cursor outside the button while is disabled

**Expected behavior**
Tooltip must hide

**Platform (please complete the following information):**
OS: Pop!_OS 19.10
Browsers: Chrome Versión 79.0.3945.117 (Build oficial) (64 bits)

**Additional context**
Is working correctly on loading state

**Comment by eduardodgarciac** [comment]
@hawkeye64 Thank you. I tested `<q-tooltip v-if="!disable">Standard</q-tooltip>` and it works. But this is still a bug or  is the correct behavior?

**Comment by pdanpdan** [comment]
A disabled `<button>` does not emit native events, so it's the expected behavior.
