### ISSUE TITLE
Q-icon not loading, loading text instead --- almost 0,5% to 2% users affected

### ISSUE THREAD

**Issue by eeerrrttty** [quasarframework/quasar#6108]
When some users load our site, SOMETIMES THE ICONS DO NOT APPEAR ! (Even after load finished!)

Will this be fixed with quasar 'true svg icons' ?

Version used:     

Pkg quasar........ v1.5.0
Pkg @quasar/app... v1.3.1

    extras: [
      'fontawesome-v5',
      'roboto-font', // optional, you are not bound to it
      'material-icons' // optional, you are not bound to it
    ]

**Comment by eeerrrttty** [comment]
![10677eb4-13a3-4712-87dd-f1e3d215e15a](https://user-images.githubusercontent.com/19417947/72369810-44e5c980-36d7-11ea-8635-96a4ae3a52fa.jpeg)

**Comment by eeerrrttty** [comment]
I could reproduce the error 'translating' the page. Icons are translated together, so the bug is reproduced.

![WhatsApp Image 2020-01-14 at 16 21 31 (1)](https://user-images.githubusercontent.com/19417947/72379725-600e0480-36ea-11ea-877e-dc150a13caf3.jpeg)
![WhatsApp Image 2020-01-14 at 16 21 31](https://user-images.githubusercontent.com/19417947/72379728-61d7c800-36ea-11ea-90c6-eb631065ae88.jpeg)

**Comment by eeerrrttty** [comment]
Icons must not be translated!!

**Comment by pdanpdan** [comment]
Please create a linked issue on Google Translate and one on Chrome and request then to immediately fix the problem because "almost 0,5% to 2% users affected" :)

**Comment by rstoenescu** [comment]
Enhancement for Google Translate will be available in "quasar" v1.7.2.

**Comment by rstoenescu** [comment]
You may want to update both "quasar" (1.7.2) and "@quasar/extras" (1.4.1) in your app (both not released yet as of writing these lines).

Alternatively, if you still encounter issues (this problem is 99% outside of our control), you may start using the svg icons (recommending the mdi ones, not the material-icons).

**Comment by jesusvilla** [comment]
The same happens on the official website of Material Icons.
![image](https://user-images.githubusercontent.com/16493932/72437602-14eb0480-3771-11ea-87c4-2d81e498cfe9.png)

**Comment by rstoenescu** [comment]
@jesusvilla Upgrade "quasar" (1.7.3) and "@quasar/extras" (1.4.1) ;)

**Comment by eeerrrttty** [comment]
Thanks

> @jesusvilla Exactly.
> @eeerrrttty Upgrade "quasar" (1.7.3) and "@quasar/extras" (1.4.1) ;)

Thanks!!! I changed the language set to 'pt-br' and i will upgrade to newer version too
