### ISSUE TITLE
Bug: Fontawesome icons are cut in QTab and QRouteTab

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#6114]
This wasn't an issue in a version released last month, but something broke in the newer versions of Quasar. The icon is now 24 px.
```
<q-route-tab icon="fas fa-desktop" label="Monitor" :to="{ name: 'monitor' }" />
```

A workaround is sytling the `q-tab__icon` (non-scoped)
```
.q-tab__icon {
  width: 32px;
  height: 32px;
}
```

Comparison
![Cut](https://i.imgur.com/yEiFy2N.png) ![OK](https://i.imgur.com/j3yYpxB.png)

**Comment by rstoenescu** [comment]
It's from v1.7.2/3.
Fix will be available in "quasar" v1.7.4.
