### ISSUE TITLE
QUploader component does not work on Firefox Focus

### ISSUE THREAD

**Issue by patrickas** [quasarframework/quasar#6118]
Steps to reproduce:
Using "Firefox Focus" for android ( https://support.mozilla.org/en-US/kb/focus )
Go to a web page that has QUploader component ( ex: https://quasar.dev/vue-components/uploader )
Click on the [plus] button to upload a file
Nothing happens
I expect the file upload screen to open like it does in other browsers.

**Comment by rstoenescu** [comment]
Hi,

Works just fine?

![quploader-ff-focus](https://user-images.githubusercontent.com/4665641/72660138-04859480-39d2-11ea-8158-47c9156c35a7.jpg)

**Comment by patrickas** [comment]
Oh I forgot to specify I have an Android phone. I tried it and reproduced the bug on a pixel 3 and a pixel 2 and Nokia 8.1

I think I think Firefox focus on iPhone is forced to use Safari's rendering engine so it is in effect just a Safari Content Blocker.
