### ISSUE TITLE
Feature Request for floating numbers for QRating component (3.5/5)

### ISSUE THREAD

**Issue by mohanzeal** [quasarframework/quasar#6119]
Feature request for QRating Component.

**Is your feature request related to a problem? Please describe.**
I am trying to create a rating system where I have to calculate average user rating on a product. Most of the time the average rating is a floating point number ex: 3.5 out of 5 and this is a valid use case.

So I am thinking we should also support v-model to have 3.5 and star rating should show half star on the 4th star indicating 3.5 to the user.

**Current behaviour**
https://codepen.io/mohanzeal/pen/OJPobWM?editors=1010

**Actual Behavior should be**
<img width="197" alt="star-rating" src="https://user-images.githubusercontent.com/5113135/72503862-b69e4e80-3862-11ea-9dd4-f786f3eeeb26.PNG">

**Comment by rstoenescu** [comment]
Will be available in half an hour with "quasar" v1.7.4 through new props: `icon-half` (mandatory in cases like this) & `color-half`.

**Comment by mohanzeal** [comment]
Quasar framework is awesome because people behind quasar framework are awesome.. Thank you very much  for a quick feature release in less than half day @rstoenescu .

**Comment by rstoenescu** [comment]
Please consider donating if you can.
