### ISSUE TITLE
optimize build times using happypack

### ISSUE THREAD

**Issue by janviehweger** [quasarframework/quasar#612]
current codebase takes quite a while to (re-)build due to large amount of packages. would be nice to have [happypack](https://github.com/amireh/happypack) in the webpack build pipeline by default.

**Comment by laurentpayot** [comment]
related: https://github.com/vuejs-templates/webpack/issues/533

**Comment by rstoenescu** [comment]
Hi, please open this for default starter kit repo. Thanks!

**Comment by rstoenescu** [comment]
https://github.com/quasarframework/quasar-template-default
