### ISSUE TITLE
QSelect: placeholder prop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#6120]
**Is your feature request related to a problem? Please describe.**

I often require a QSelect **without label** but **with a placeholder** (slightly grey) when no value is selected.

**Describe the solution you'd like**
```html
<QSelect outlined placeholder="select a value" :options="['some', 'options']">
```
for usage without label!

**Describe alternatives you've considered**
I considered making a PR on the source code. If it's OK for me to do so, let me know in a comment and I'll make the PR.

**Additional context**
an example:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/3253920/72505306-0260f000-3883-11ea-9d69-ff30559e78f9.png">

**Comment by pdanpdan** [comment]
Use the selected slot to customize the display as you wish: https://codepen.io/pdanpdan/pen/VwYGbQo

**Comment by rstoenescu** [comment]
Alternatively, there is also `display-value` prop: https://codepen.io/rstoenescu/pen/VwYGMyo

**Comment by BarnabasSzabolcs** [comment]
This does not seem to cooperate well with the "use-input" tho...

**Comment by alexfaus08** [comment]
@BarnabasSzabolcs 
> This does not seem to cooperate well with the "use-input" tho...

You can conditionally set the placeholder based on the model value with "use-input":

`:placeholder="model ? '' : 'Search...'"`
