### ISSUE TITLE
QSelect confusing behaviour when filtering options

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#6121]
Hello!

QSelect is great, but I think that way it works when selecting filtered options is confusing.

Steps to reproduce:
Using an official example (https://codepen.io/pen/?&editable=true&editors=101)
1) Click inside
2) Type 'F'
3) A list of options is displayed
4) Press ENTER
5) Nothing is selected, 'F' remains inside the input
6) Click outside 'F' is removed from the input (reverted to the previous valid value)

If an option from the list is required to be chosen, I don't think we need to close the list of options when pressing ENTER until one of the options is highlighted.

Expected:
1) Click inside
2) Type 'F'

If several options are found and no options are highlighted:
3) Clicking ENTER will not close the options dropdown until you manually highlight one of the options (example https://material.angular.io/components/autocomplete/overview)

If only one option is found:
3) This option needs to be highlighted (consider adding a configurable prop, example: https://material.angular.io/components/autocomplete/overview#automatically-highlighting-the-first-option), pressing ENTER will choose the highlighted option. Also related to https://github.com/quasarframework/quasar/pull/5779

Thanks!

**Comment by rstoenescu** [comment]
This is a misunderstanding on how you can configure QSelect.
@pdanpdan can you please explain him how to do it? don't have time at the moment

**Comment by pdanpdan** [comment]
Added example in docs on how to customize the behavior after filtering:
https://quasar.dev/vue-components/select#Example--Selecting-option-after-filtering
Available in v1.7.4+

**Comment by jean-moldovan** [comment]
@pdanpdan , Thanks for adding the examples!

Would it be possible to configure QSelect so that it does not fill the input when highlighting the option in the dropdown and have 'hide-selected' set to true. Similar to https://material.angular.io/components/autocomplete/overview#simple-autocomplete

Thanks!

**Comment by pdanpdan** [comment]
@jean-moldovan Please post a codepen with what you have tried.

**Comment by jean-moldovan** [comment]
Here is an example: https://codepen.io/jean-moldovan/pen/rNaqejY?editable=true&editors=101

**Case 1**
Currently:
1) Type in 'G'
2) Multiple options are shown
3) Press ENTER
4) Options dropdown is hidden

Expected:
1) When pressing ENTER options dropdown should not be hidden until one of the options is highlighted

**Case 2**
Currently:
1) Set fill-input to false and hide-selected to true
2) Type in 'G'
3) Select an option
4) Empty input is displayed

Expected:
1) I should be able to see the value selected inside the input without the need to display it on the left side of the input (hide-selected: true) and, at the same time, I should have an ability to not to fill input with the highlighted option (fill-input to false)

As I mentioned previously, see angular material example https://material.angular.io/components/autocomplete/overview#simple-autocomplete. In my opinion this is a great example of how autocomplete should work.

Thank you and I really appreciate your effort in trying to solved this!

**Comment by pdanpdan** [comment]
Examples updated on docs: https://quasar.dev/vue-components/select#Example--Selecting-option-after-filtering

**Comment by jean-moldovan** [comment]
Nice, thanks for taking the time out to update the examples!
