### ISSUE TITLE
QVirtualScroll: virtual-scroll-slice-size property doesn't work

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#6122]
**Describe the bug**
virtual-scroll-slice-size property doesn't work in QVirtualScroll component 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/1001v/pen/xxbaqEd?editors=1010

**To Reproduce**
Check out codepen. You can see that virtual scroll scope length doesn't correlate with virtual-scroll-slice-size value

**Comment by pdanpdan** [comment]
`virtual-scroll-slice-size` is more a hint than a fixed value.
It is used on SSR to pre-render that number of rows, but in the browser it is recomputed to the gretest value between the supplied value and 2 * (the size of the window divided by `virtual-scroll-item-size`).
