### ISSUE TITLE
QIcon overflow

### ISSUE THREAD

**Issue by haasz** [quasarframework/quasar#6124]
Not good:
https://github.com/quasarframework/quasar/blob/4857a46448ee949560229a3d4d9232ce924b55f2/ui/src/components/icon/QIcon.sass#L2

Result (Font Awesome Pro):
![bad-icon](https://user-images.githubusercontent.com/2394963/72522475-19411b80-385e-11ea-89b8-b95c9a1a63b4.png)

Correctly:
![good-icon](https://user-images.githubusercontent.com/2394963/72522575-4ee60480-385e-11ea-91b0-1bd552056490.png)

**Comment by rstoenescu** [comment]
Fixed already in 1.7.4 (to be released in 1-2 hrs).
