### ISSUE TITLE
Fontawesome icon sets appear cut-off

### ISSUE THREAD

**Issue by aatecey** [quasarframework/quasar#6127]
**Describe the bug**
After upgrading to quasar 1.7.3 from 1.6.1 font awesome icons appear to be cutting off.

Quasar: 1.7.3
Quasar extras: 1.4.2
Quasar app: 1.5.1

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/mvdzg318/

**To Reproduce**
See fiddle above. Icon is cut-off.

**Expected behavior**
The icon shouldn't be cut-off

**Screenshots**
![Screenshot from 2020-01-16 15-19-43](https://user-images.githubusercontent.com/21364333/72537256-b8bcd900-3873-11ea-8700-8ff3741b3f40.png)

**Platform (please complete the following information):**
OS: Ubuntu 19.10
Node: 12.13.1
NPM: N/A
Yarn: 1.19.1
Browsers: Chrome Version 79.0.3945.117 (Official Build) (64-bit)
iOS: N/A
Android: N/A
Electron: N/A

**Comment by rstoenescu** [comment]
Fix already in future v1.7.4 (to be released in half an hour).
