### ISSUE TITLE
QPage: style-fn is useless when layout is container

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#6128]
**Is your feature request related to a problem? Please describe.**
Problem: when we apply style-fn to qpage component inside layout, which has container property, we can't calculate the proper height because we need the height of layout. Quasar uses layout.containerHeight inside qpage, which is provided by layout itself, but we don't have this parameter outside.

**Describe the solution you'd like**
I'd like to have this parameter as style-fn argument, like offset is.

**Describe alternatives you've considered**
We can use ref to layout component, but this is a limited solution.

**Comment by rstoenescu** [comment]
New second param (height) for style-fn in "quasar" v1.7.4 (to be released in half an hour).
