### ISSUE TITLE
button-clear into Stylus Variables

### ISSUE THREAD

**Issue by pdipasqua** [quasarframework/quasar#613]
hi,
stylus variables are great!
I don't find 
_button-clear-color_ 
_and button-clear-active-color._

Could you add this?
Thanks, Regards.
P

**Comment by pdipasqua** [comment]
hi,
the problem is the function lighten 60% and i have problem with toogle component also.
I can't personalize the theme without use css override file.
My primary color is similar to teal class but the lighten is eccessive.
Whit this color i think that grey neutral color is better than lighten color.
Sorry for my english.
P

**Comment by rstoenescu** [comment]
@pdipasqua In future v0.14 (around the corner - releasing on 16th of June) there is going to be a button component (QBtn) -- which a total rework of how buttons are styled now. If you can overwrite CSS in your app to fix your issue, it's better this way, as working on this is obsolete and further delays the new and shiny v0.14 release ;)

Please reopen if you need a fix in v0.13 branch badly though. Thank you and hope you understand.
