### ISSUE TITLE
Quasar CLI should check if Vuex store is already added or not while creating new one 

### ISSUE THREAD

**Issue by ShahnazK** [quasarframework/quasar#6133]
Currently if we do not add Vuex store while creating new project using `quasar create` , it doesn't add a folder `src\store` as well as `index.js` into this.
When we add new store later using `Quasar new store`, it creates `src\store` folder with new store folder and related boiler plate code. But it doesn't create `index.js` file into `src\store` folder. I believe it assumes that its already there.

Currently the work around is we need to create new project with initial Vuex Store and copy the folder with index.js into existing project. 

Ideally `quasar new store` should check if no `index.js` file is there inside `src\store` then it should create default one.

**Comment by metalsadman** [comment]
@ShahnazK you can copy the store/index.js boilerplate code from the docs. https://quasar.dev/quasar-cli/cli-documentation/vuex-store#Introduction

**Comment by ShahnazK** [comment]
@metalsadman Yes, that is another workaround but that is not great developer experience. Ideally CLI command `quasar new store` should handle this.

**Comment by rstoenescu** [comment]
This has been implemented. Forgot version, but I can tell for sure that "@quasar/app" v1.8.6 has it.
