### ISSUE TITLE
[Bug] Dialog not closing on back button on Capacitor build

### ISSUE THREAD

**Issue by josephharveyangeles** [quasarframework/quasar#6134]
**Describe the bug**
QDialog doesn't close when device back button is clicked on Capacitor apps. Cordova works fine as is but for some reason on Capacitor build, nothing happens when device's back button is pressed.

**Codepen/jsFiddle/Codesandbox (required)**
Any non-persistent QDialog ie: [https://codepen.io/yev/pen/dyPqjJp](https://codepen.io/yev/pen/dyPqjJp?editable=true&editors=101)

**To Reproduce**
1. Create a fresh Quasar project
2. Use plain QDialog component
3. Make sure `persistent` prop is not set
4. Add capacitor mode
5. Build android apk
6. Install, open app and open dialog
7. Click device back button
8. Nothing happens

**Expected behavior**
The dialog should close same behavior like hitting esc-key.

**Platform (please complete the following information):**
OS: Pop!_OS
Node: v12.4.0
NPM: 6.9.0
Yarn: 1.21.1
Browsers: Chrome
iOS:
Android: Android 8.0 Oreo
Electron:

**Comment by pdanpdan** [comment]
Try to follow here: https://github.com/ionic-team/capacitor/issues/417

**Comment by josephharveyangeles** [comment]
@pdanpdan it looks like that specific issue is already fixed. I'm not particularly sure why it happens on quasar capacitor build though. Is there any more information that might explain what happens based on the related capacitor issue?

**Comment by rstoenescu** [comment]
Will do a test (in the next days) to see if the Capacitor API supports this correctly and will update Quasar. We currently allow the auto closing behavior on Cordova only.

**Comment by rstoenescu** [comment]
This will be available in "quasar" v1.9.3.
