### ISSUE TITLE
Improve Carousel

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6135]
Improve Quasar Carousel like (https://gs-shop.github.io/vue-slick-carousel/?ref=madewithvuejs.com#/ or integrate. 
There are some interesting features in this component including the 'multiple' feature , variable width

**Comment by mYnDstrEAm** [comment]
This would be very useful. Asked about a center mode for the slideshow here: https://forum.quasar-framework.org/topic/5122/how-to-build-a-slideshow-qcarousel-with-parts-of-the-next-and-previous-image-showing/

**Comment by rstoenescu** [comment]
Hi,

An image tag as content for the slide would do the trick. You are not bound to using the slide's prop only. We'll keep on adding features to the QCarousel but integrating some external library is out of the question (both for maintenance and footprint in KBs). If there is some vue plugin that fits your needs, please use it. Sorry if this is not something that you want to hear.
