### ISSUE TITLE
[docs] Inner Loading on element with large height to fix the spinner on screen

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#6136]
I suggest to demo inner loading on divs with large height. When height is large the spinner usually can't be seen because it is centered. I created a sample to fix the spinner on the screen. 

https://codepen.io/ajcastro/pen/MWYqxbz

**Comment by rstoenescu** [comment]
Hi,

Thanks for this, but this is part of the customization on a case by case basis.
