### ISSUE TITLE
TypeScript: no exported member 'QUploaderBase'.ts (missing type)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#6137]
**Describe the bug**
When trying a custom uploader in a `.ts` file and doing `import { QUploaderBase } from 'quasar'` it gives this error:

> import QUploaderBase
> Module 'node_modules/quasar/dist/types' has no exported member 'QUploaderBase'.ts(2305)

**Expected behavior**
`QUploaderBase` type should be exported by Quasar, now it is only exporting `QUploader`

**Screenshots**
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3253920/72582458-2cb7b980-3926-11ea-8392-464361b574f3.png">

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "quasar" v1.8.0.
