### ISSUE TITLE
File input?

### ISSUE THREAD

**Issue by zz5840** [quasarframework/quasar#6145]
Is there any plan to beautify this ugly components?
![image](https://user-images.githubusercontent.com/16662647/72632117-910f6300-3990-11ea-9033-364539b4c5ea.png)

you can refer to https://vuetifyjs.com/en/components/file-inputs
![image](https://user-images.githubusercontent.com/16662647/72632323-02e7ac80-3991-11ea-90c7-432e75c1be37.png)

as for Uploader components, i think it's too complex in some occasion
i just want user to select a file, and i will use FileReader api to read it, no upload action exists

**Comment by pdanpdan** [comment]
There were some discussions about Microsoft wanting to beautify the native components, but I don't know when and how :)

**Comment by zz5840** [comment]
@pdanpdan i don't think it's a wise choice to wait for browser's beautifying, different browsers may have different appearance after all

**Comment by rstoenescu** [comment]
Until we create something nice, there's this. If you take the knowledge from this you can create your very own filepicker. https://codepen.io/rstoenescu/pen/OJPBbaN

**Comment by rstoenescu** [comment]
Also, you can combine with QField, which a wrapper for any type of inputs ;)

**Comment by zz5840** [comment]
@rstoenescu thx, should i close this issue?

**Comment by metalsadman** [comment]
@zz5840 https://codepen.io/metalsadman/pen/yLyRPwZ?editors=1010

**Comment by zz5840** [comment]
@metalsadman it's perfect, but would you consider to make it a component?

**Comment by metalsadman** [comment]
@zz5840 you can make a wrapper component out of it.

**Comment by zz5840** [comment]
@metalsadman yes, i have done it indeed, but i think it would be useful to be a built-in component

**Comment by rstoenescu** [comment]
QFile coming in v1.8.

**Comment by rstoenescu** [comment]
QFile will be available in "quasar" v1.8.0.
