### ISSUE TITLE
QTable expand API missing

### ISSUE THREAD

**Issue by pdwinkel** [quasarframework/quasar#6147]
**Is your feature request related to a problem? Please describe.**
QTable is missing the same expand API as QTree has

**Describe the solution you'd like**
Give QTable also an expand API

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rstoenescu** [comment]
Hi,

It's already there... https://quasar.dev/vue-components/table#Expanding-rows

**Comment by pdwinkel** [comment]
The 'selected' of QTable has
`:selected.sync="selected"`
I was looking for the same possiblity for 'expand', so something like:
`:expanded.sync="expanded"`

(Sorry, the feature request was not clear ;-)

**Comment by rstoenescu** [comment]
Feature will be available in "quasar" v1.8.3.
`:expanded.sync="expanded"`, where `expanded` is an Array of row keys.

**Comment by pdwinkel** [comment]
Thanks, works great!
