### ISSUE TITLE
QVirtualScroll snaps to second-to-last item when fast scrolling instead to the end of the list

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#6148]
When fast scrolling using the scrollbar with the mouse or with touch events on mobile, flicking the list to the end, it snaps to the second to last item, instead of the last item.

Codepen:
https://codepen.io/jeancaffou/pen/MWYPqQY

Screencast:
https://drive.google.com/file/d/1VGnBQ6ZEfS1tivnL73YXOeobTIAPkfFy/view
See screencast, it jumps back to item 99 instead of 100

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.8.0.
