### ISSUE TITLE
[Request] Add truncatePath option to QEditor

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#6149]
When I makeing some text with QEditor there can be some links like
```
<a href="http://somesite.site/somepath/1">
<img src="http://somesite.site/somepath/2">
```
It is very useful to auto truncate link path's and to excluding base path if truncate option is true
```
<a href="/somepath/1">
<img src="/somepath/2">
```
Feature request to make such syntax if it is possible.

```
<q-editor basePath="http://somesite.site" truncateLinks="true" />
```

Or maybe simpier
```
<q-editor linksTruncatePath="http://somesite.site" />
```

**Comment by rstoenescu** [comment]
Hi,

QEditor relies 100% on the browser's support for contenteditable and document.execCommand. We are not the ones handling how the content is managed, so your request is not really possible. Sorry.
