### ISSUE TITLE
[Feature] SSR: On DEV Mode - Give an option to build only server

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#6151]
When there's only a server change (on src-ssr directory) -  build only the server app part.

**Comment by rstoenescu** [comment]
Hi,

Are you referring just to the webserver part?

**Comment by eladcandroid** [comment]
I'm running 
```bash
npx quasar dev -m ssr 
```
and I don't want that the script will rebuild Client files when I just change some server files

**Comment by rstoenescu** [comment]
Ok, I see now. Unfortunately, there is no way to tell if client or server changed only. A full build is necessary.
