### ISSUE TITLE
IDE don't recognized quasar's components after update 1.7.4

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6152]
**Describe the bug**
IDE don't recognized quasar's components after update 1.7.4

**To Reproduce**
1. Open any Vue component with quasar's component inside

**Expected behavior**
IDE recognized components and offer autocompleting of props.

**Screenshots**
https://prnt.sc/qpuq2j

**Platform (please complete the following information):**
OS: Win10 x64
IDE: Jetbrains PhpStorm 2019.3.1-193.5662.63

**Additional context**
1.7.3 is ok

**Comment by rstoenescu** [comment]
Hi,

Not our fault. A bug in the IDE which is under investigation: https://youtrack.jetbrains.com/issue/WEB-43354

**Comment by matro-skin** [comment]
Yep, answer is already got in discord. Thanks
