### ISSUE TITLE
text-xxx in standout for inputs does not override the default text colour when focused

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#6153]
That would be great if <q-input standout="bg-black text-amber" /> would override both background and text on focus. At the moment, that is just a background override.

Many thanks!

**Comment by rstoenescu** [comment]
Hi,

Always check the API cards. It's already possible: https://codepen.io/rstoenescu/pen/dyPQGOv?editable=true&editors=101

**Comment by pikil** [comment]
Hi Razvan,
Thanks for that! That's one of the approaches indeed, however, that would not work, when there is a big contrast between focused/non-focused standouts (like black and white). In that case, entered text would blend in when the input is not focused. Please see the code below

(That's the one from your example on codepen but with bg-black in toolbar and with input-class="text-right text-grey-9"). Let me know if you want me to set an example instead. Many thanks!

`<div id="q-app">
  <div class="q-pa-md">
      <div class="q-gutter-y-md column" style="width: 300px; max-width: 100%">
        <q-toolbar class="bg-black text-white rounded-borders">
          <q-btn round dense flat icon="menu" class="q-mr-xs" ></q-btn>
          <q-avatar class="gt-xs">
            <img src="https://cdn.quasar.dev/logo/svg/quasar-logo.svg">
          </q-avatar>
  
          <q-space ></q-space>
  
          <q-input dark dense standout v-model="text" input-class="text-right text-grey-9" class="q-ml-md">
            <template v-slot:append>
              <q-icon v-if="text === ''" name="search" ></q-icon>
              <q-icon v-else name="clear" class="cursor-pointer" @click="text = ''" ></q-icon>
            </template>
          </q-input>
        </q-toolbar>
      </div>
    </div>
</div>`

**Comment by rstoenescu** [comment]
Ok, but then write a CSS class targeting q-field--focused input for your custom use-case.

**Comment by pikil** [comment]
Sure, that's what I actually did.
Thank you for the clear explanation Razvan!
