### ISSUE TITLE
[docs] Explain how to deploy ssr app with zeit v2

### ISSUE THREAD

**Issue by ghost** [quasarframework/quasar#6158]
I’m new to quasar and the documentation use zeit v1 for ssr deployement, but v1 is no longer available today 😞 I’can’t deploy quasar ssr app to now

**Comment by Inklud** [comment]
Very simple
You do not need to add a now.json file to your project to make quasar work with Zeit Now.

This is how to make Zeit Now work with Quasar
1. Log into Zeit Now https://zeit.co/
2. Create a project or import project from Github etc.
3. Go into Build & Development Settings

Add the following build command: "quasar build"
Add the following output directory: /dist/spa
Press save when done.

4. That's it! You may now try to deploy your project to Zeit Now, and it should work :-)
