### ISSUE TITLE
disable vs disabled prop

### ISSUE THREAD

**Issue by gaby64** [quasarframework/quasar#6162]
why is there some components using `disabled` while others use `disable`?

QInput uses `disable`
QBtn uses `disabled`

**Comment by rstoenescu** [comment]
There is no "disabled". All components use `disable`.

**Comment by gaby64** [comment]
my mistake,  I believe disabled was working because its the native button attribute

**Comment by rstoenescu** [comment]
Yep. It's also a class that can be used on any DOM element. But do not mistake it with the `disable` prop. Whenever there is a `disable` prop (all Quasar components that are relevant to a disabled state have it) use that instead.

**Comment by huy-tran** [comment]
😀

**Comment by Rosadojonathan** [comment]
@rstoenescu Was there a reason for not using the "disabled" prop everywhere in quasar and following HTML5 standard? Thanks!
