### ISSUE TITLE
Table Grid mod pagination virtual not working

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6163]
All in title

**Comment by rstoenescu** [comment]
Virtual pagination is designed for non grid only.

**Comment by nseb** [comment]
Vuetify support infinite scrolling with data iterator , it's same thing grid mode of quasar table

**Comment by smolinari** [comment]
@nseb - I looked for an example, but couldn't find one. Can you please link to an example? I'm interested in seeing this.

Scott

**Comment by nseb** [comment]
@smolinari 
Hi Scott ,  i migrate application with lot of table and infinite scrolling developped in GWT , (data retrieve loaded from server). 
https://vuetifyjs.com/en/components/data-iterators

I admit to having a lot of trouble with your notions of virtual scroll table or the infinite scroll component. They do not work well when the data has to be loaded. I could show you.
In addition, your virtual scroll works only if we set an absolute height, if we set a height to 100%, nothing works.
I find that this is the black point of the quasar framework for applications for 'real' production, as well as the grouping functionality from which I also created an issue.

Best Regards,
Sébastien.

**Comment by smolinari** [comment]
I saw that page, but there is no example of an infinite scroll with something like Quasar's grid mode table. Just lists similar to Quasar's grid mode data table, but with pagination.  

>I admit to having a lot of trouble with your notions of virtual scroll table or the infinite scroll component. They do not work well when the data has to be loaded. 

Maybe it's your understanding needing some help? How about asking in the forums or Discord for help? Would be a better place to discuss. 😄 See you there, if you are interested.

Scott

**Comment by metalsadman** [comment]
@nseb you can use serverside pagination with q-table, it will call your pagination api every sort/nextpage/search etc...

**Comment by rstoenescu** [comment]
Furthermore, infinite scroll is not the same as virtual scroll which only Quasar has.
References:
* QInfiniteScroll: https://quasar.dev/vue-components/infinite-scroll
* QVirtualScroll: https://quasar.dev/vue-components/virtual-scroll
* QTable (non-grid mode) with virtual scroll (**use this!**): https://quasar.dev/vue-components/table
* QSelect has virtual scrolling enabled by default; example with 100k options: https://quasar.dev/vue-components/select#Render-performance
