### ISSUE TITLE
Quasar cli can not new a plugin in my project

### ISSUE THREAD

**Issue by shilohooo** [quasarframework/quasar#6166]
**Describe the bug**
when i excuted quasar new plugin <plugin name> in my project, i get the following error msg:
![image](https://user-images.githubusercontent.com/46670399/72774318-22a6fb00-3c45-11ea-923d-28993454d378.png)

my quasar cli verson is 1.5.2

**Comment by smolinari** [comment]
There is no such command. That is normally a Vue-CLI command.

https://quasar.dev/quasar-cli/cli-documentation/commands-list#new

With Quasar, you can use the boot file system to get the plug-in installed into Quasar. 

https://quasar.dev/quasar-cli/cli-documentation/boot-files#Introduction

Scott

**Comment by shilohooo** [comment]
thanks for your answer.
But i saw this usage in the Chinese documentation of quasar.
Here is the documentation link:[http://v0-16.quasarchs.com/guide/app-plugins.html](url)
It makes me wonder:(

**Comment by shilohooo** [comment]
please see that：
![image](https://user-images.githubusercontent.com/46670399/72775143-2e47f100-3c48-11ea-98e8-97b9c8e16f03.png)

**Comment by smolinari** [comment]
Ah. The boot file system used to be called plugins prior to version 1.0. They are no longer called plugins.  The command now is `quasar new boot <boot-file-name>`.

Scott

**Comment by shilohooo** [comment]
That'it, i know.
tks~
