### ISSUE TITLE
QScrollArea, scroll to bottom

### ISSUE THREAD

**Issue by hlb8122** [quasarframework/quasar#6167]
**Is your feature request related to a problem? Please describe.**
In some applications, such as a messaging apps chat box, one would like to scroll to the bottom of a `QScrollArea` on a new message.

**Describe the solution you'd like**
An API method for `QScrollArea` to scroll to the bottom.

**Describe alternatives you've considered**
```
      this.$refs.chatScroll.setScrollPosition(this.$refs.chatScroll.$el.scrollHeight, 1)
```

`setScrollPosition` is such a method but the above doesn't seem to scroll to bottom correctly all the time.

**Comment by pdanpdan** [comment]
```javascript
const scrollArea = this.$refs.chatScroll;
const scrollTarget = scrollArea.getScrollTarget();
const duration = 300; // ms - use 0 to instant scroll
scrollArea.setScrollPosition(scrollTarget.scrollHeight, duration);
```

https://codepen.io/pdanpdan/pen/yLyQdOz?editors=1010

**Comment by ligecarryme** [comment]
<template>
    <q-scroll-area ref="chatArea" @scroll="scrollinfo" >
          <div v-for="item of message" :key="item.id">
             <q-chat-message :name="item.nickname" :text="[item.content]" :stamp="item.createTime" />
           </div>
        <q-scroll-observer /> 
    </q-scroll-area>
</template>
<script>
export default {
	data(){
        return {
		scrollsize: 0;
        }
    },
    watch:{ // 监控滚动条的变化
        scrollsize: function(val){
      		this.$refs.chatArea.setScrollPosition(val-500,100); //设置到底部,500是我自己设置的聊天区域高度
    	}
    }，
    scrollinfo(info){ 
      const size = info.verticalSize;
      this.scrollsize = size;
    }
}
</script>
