### ISSUE TITLE
q-markup-table border glitches with colspan / rowspan

### ISSUE THREAD

**Issue by tomlukman** [quasarframework/quasar#6168]
https://www.screencast.com/t/kGHTBB1UFl9A

See screenshot - left borders on first columns don't render. Triggering border-left on the style I marked will make them render but then the left table border gets too thick. I can fix this with custom css but I believe quasar styles need some tweaking. I'm including the table code below for testing:

```
<template>
  <div class="row container">
    <div class="col-12">
      <q-markup-table bordered flat separator="cell">
      <thead>
        <tr>
          <th colspan="3" rowspan="2" class="text-left">Zustand Rotor<br>State of rotor</th>
          <th colspan="12" class="text-center">Messstellen<br>Measuring points</th>
          <th rowspan="2" class="text-center">Datum<br>Date</th>
        </tr>
        <tr>
          <th class="text-center" v-bind:key="i" v-for="i in 12">{{ i }}</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td rowspan="3" class="text-center">A</td>
          <td class="text-center">Ansicht</td>
          <td class="text-center">R</td>
          <td class="text-center" v-bind:key="i" v-for="i in 12">R{{ i }}</td>
          <td class="text-center">21. 04. 1979.</td>
        </tr>
        <tr>
          <td class="text-center">Schluss-Kontrolle</td>
          <td class="text-center">H</td>
          <td class="text-center" v-bind:key="i" v-for="i in 12">H{{ i }}</td>
          <td class="text-center">21. 04. 1979.</td>
        </tr>
      </tbody>
    </q-markup-table>
    </div>
    <div class="col-12 q-mt-lg text-subtitle2">{{ reportData }}</div>
  </div>
</template>
```

**Comment by pdanpdan** [comment]
Hello. Please put that code in a codepen so it can be tested. Thank you.
Also keep in mind that custom colspan/rowspan will always require custom CSS.
You can also add in the codepen some CSS solutions you used to fix the problem in your case.

**Comment by tomlukman** [comment]
I'm sorry, but I can't get it to run in codepen. The way I work around this glitch is adding custom class to buggy field which has proper border thickness.

**Comment by rstoenescu** [comment]
Hi,

There is nothing we can do about this. Writing CSS for all the million possible combinations is out of the question.

However, you can tweak the CSS for you table easily. Example:
```
<tr><td class="text-center">Schluss-Kontrolle</td>
```
...should become:
```
<tr><td style="border-left: 1px solid rgba(0, 0, 0, 0.12)" class="text-center">Schluss-Kontrolle</td>
```
