### ISSUE TITLE
Debounce does not work for the native number buttons

### ISSUE THREAD

**Issue by dvbeek** [quasarframework/quasar#6173]
**Describe the bug**
Debounce does not work with the native arrow-buttons for increasing and decreasing the value (at least in Chrome and Firefox).

If the value is changed using the keyboard the debounce works good, but when the user increases the value using the up arrow the debounce is ignored and every click results in the direct input handler.

`<q-input type="number" v-model="someNumber" debounce="500" @input="expensiveServerCall" />`

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/DennisVanBeek/pen/qBELWRV?editors=1010

**To Reproduce**
Click the up or down arrow in a number field and check the debounce

**Expected behavior**
The debounce should work on the arrows the same as changing the value in the input field.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10
Node: 8.9.0
NPM: 5.6.0
Yarn: 1.6.0
Browsers: Firefox + Chrome

**Additional context**
See also the forum, where  metalsadman posted a workaround:
https://forum.quasar-framework.org/topic/5106/debounce-does-not-work-for-the-native-number-buttons

**Comment by pdanpdan** [comment]
This is because the arrows emit a change event instead of input one - and change is imperative. Nothing we can do about it.
