### ISSUE TITLE
@quasar/extras SVG Material Icons: some icons are missing

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#6175]
I recently decided to change my `iconSet` to SVG icons(`svg-material-icons`) from web font icons(`material-icons`), but I found that some icons are missing, I see that `svg-material-icons` are generated from [google/material-design-icons](https://github.com/google/material-design-icons) repo, in here:
https://github.com/quasarframework/quasar/blob/7dd75fa32e4d1e7d847fbea70808984d4763de48/extras/build/material-icons.js#L1-L16
The reason some icons are missing is explained in this issue: https://github.com/google/material-design-icons/issues/778

#### Reproduction
The issue can be reproduced with the following code
```js
import {
  matWifi,
  matWifiOff // matWifiOff not found in '@quasar/extras/material-icons' - eslint(import/named)
} from '@quasar/extras/material-icons'
```

#### Possible Solutions
 - (Laziest) The situation can be stated in the docs
 - (?) Maybe a good fork that is maintained can be used instead
 - (Probably the hardest, but one-time work) As the last commit in the repo is more than 2 years old, maybe we can ditch the script and add the missing icons
 - ?

**Comment by rstoenescu** [comment]
Hi,

Yes. As stated before, the repo for Material Icons is 3 years old... Recommended approach is to use MDI v4 svgs instead.

**Comment by yusufkandemir** [comment]
For anyone interested;
> As stated before, the repo for Material Icons is 3 years old

Source: https://github.com/quasarframework/quasar/tree/dev/extras#svg (Notes section)

> Recommended approach is to use MDI v4 svgs instead.

I think we could derive that from the fact that the docs are using it: https://github.com/quasarframework/quasar/blob/662945821410e711bf5ab1a2d54753dbf6e37457/docs/quasar.conf.js#L84

Other than those, I didn't see any mentions anywhere, especially in the docs and `@quasar/extras`'s README.

**Comment by rstoenescu** [comment]
I'm writing an import guide for the svg icons as we speak :)
