### ISSUE TITLE
Scss variables give an error

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#6176]
**Describe the bug**
When trying to use $space-md variable in app.scss build fails.
![image](https://user-images.githubusercontent.com/5757159/72808462-e03be900-3c59-11ea-8010-d2a9ac0fd22b.png)

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. Create a project with Quasar CLI (use sass/scss)
2. Use $space-md in app.scss somewhere
3. Quasar dev

**Expected behavior**
Not sure what is going wrong but it seems to be something with the sass-loader.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows
Node: 12.13.1
NPM: 6.12.1
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
@quasar/app@1.4.3
sass-loader@8.0.0

**Comment by rstoenescu** [comment]
Please do not manually install any sass related packages (a.k.a node-sass or dart-sass). These come supplied by `@quasar/app` package so you don't bump into these kind of issues.

You are most likely using dart-sass instead of node-sass.

**Comment by Evertvdw** [comment]
@rstoenescu Hi there, I did not install sass-loader, I just looked up which version @quasar/app was using. Also I don't use dart-sass, I just use whatever is installed by the quasar cli.

**Comment by Evertvdw** [comment]
I just updated quasar and followed the mentioned reproduction steps. That results in the same error, so it's something in the Quasar code/setup.

**Comment by rstoenescu** [comment]
No, it's the usage. `$space-md` is a list. Correct usage is: `map-get($space-md, "x")` or `map-get($space-md, "y")`. Sadly, the Sass compiler shows the wrong place where the error occurs in this particular case.

**Comment by Evertvdw** [comment]
My bad, didn't know that. Thanks for the help!
