### ISSUE TITLE
QSelect: using 'multiple' together with 'option-label', 'option-value', 'map-options' and 'emit-value' results in unwanted behavior

### ISSUE THREAD

**Issue by tobiasfuhlroth** [quasarframework/quasar#6177]
**Describe the bug**
Using 'multiple' together with 'option-label', 'option-value', 'map-options' and 'emit-value' results in unwanted behavior. When configuring the QSelect this way it is possible to select the same option multiple times.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tofupen/pen/yLyGOLL?editors=1010

**To Reproduce**
1. Go to https://codepen.io/tofupen/pen/yLyGOLL?editors=1010
2. Click on the QSelect to open the options
3. Click on the option 'Google'
4. Click on the option 'Google' again
4. Error: the option 'Google' gets selected twice

**Expected behavior**
After the second click the option 'Google' should be deselected and removed from QSelect

**Screenshots**
![Screenshot 2020-01-21 at 15 00 53](https://user-images.githubusercontent.com/616903/72810942-ee403880-3c5e-11ea-8305-6be90766b5fd.png)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available this week in v1.8.0.
