### ISSUE TITLE
Q-Input with mask doesn't allow to input any of the prefix characters

### ISSUE THREAD

**Issue by TheCheat** [quasarframework/quasar#6182]
**Describe the bug**
When using Q-input with mask that has prefixed characters (i.e. masks like '+49(####)###-####')
it doesn't allow to input any of the characters that are in the prefix (i.e. '+', '4' and '9')

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/jerk_thehuman/uraq4jkb/4/

**Expected behavior**
Being able to input any characters with prefix. For example when pressing +, 4, 9 cursor moves alongside these characters and then I'm able to type anything. When I press any other key, it acts just like current implementation.

**Platform (please complete the following information):**
OS: Debian 10
Node: 10.18.1
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Google Chrome 79.0.3945.130 (Official Build) (64-bit)

**Comment by pdanpdan** [comment]
Yep, there are some problems, but we cannot fix them in the next release (v1.8.0).
We'll post here when it's solved.

**Comment by pdanpdan** [comment]
Closing this to follow in https://github.com/quasarframework/quasar/issues/6969
