### ISSUE TITLE
None of the Codepen examples are working [docs]

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#6183]
None of the codepen examples are working for me at the moment. 

Screenshot: 
![image](https://user-images.githubusercontent.com/11305093/72867671-6ffd9800-3d2b-11ea-92b2-f2331d71aab3.png)

![image](https://user-images.githubusercontent.com/11305093/72867695-8572c200-3d2b-11ea-849a-e608c0641a70.png)

I think maybe the settings (importing Quasar) are not getting carried over? Not sure. Hopefully this is just me. 

Using Chrome in Incognito mode.

**Comment by rstoenescu** [comment]
Well, seems like this should be reported to Codepen. They have an error in their code when browser is in incognito mode... Please try not to use this mode.

![codepen](https://user-images.githubusercontent.com/4665641/72868519-e1692680-3cea-11ea-9b93-74f26a17b19d.png)

**Comment by smolinari** [comment]
The codepens aren't working for me either.

This link works: https://codepen.io/rstoenescu/pen/VgQbdx

The examples in the docs don't. 

Scott

**Comment by pdanpdan** [comment]
It looks like they are changing something in the interface. If you save the codepen it will work, but they do not list the external scripts.

**Comment by smolinari** [comment]
Yup. Using the Save button works. So, it's a temp fix for now. 😃 

Scott

**Comment by Fanvadar** [comment]
Awesome thanks @pdanpdan

**Comment by rstoenescu** [comment]
(joke): Since this is a ticket opened against Quasar, here's the course of action that we must take. We hijack the DNS of codepen.io, write up a quick codepen clone and then close this ticket.
