### ISSUE TITLE
How to apply colResizable to Q-Table in quasar framework ?

### ISSUE THREAD

**Issue by ravimule22** [quasarframework/quasar#6185]
<q-table id="overflow">
 </q-table>
I took  id = overflow in q-table tag and it call jquery function 
$(document).ready(function(){
	 $("#overflow").colResizable({
          liveDrag:true, 
          gripInnerHtml:"<div class='grip'></div>", 
          draggingClass:"dragging", 
          resizeMode:'overflow'
      });
	});	
 
and i used following jquery files
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
 <script src="./common/js/colResizable-1.6.js"></script>
It works in normal javascript with html but how to make it work with q-table in quasar tables.

**Comment by rstoenescu** [comment]
Hi,

How is this a bug? Please use our [Discord channel](https://chat.quasar.dev) or [Forum](https://forum.quasar.dev) for asking questions, although if you're using jQuery along with Vue....

**Comment by ravimule22** [comment]
Hi, sorry for this i mentioned question on Forum but is it possible that you can tell me here that how i 
make colResizable of q-table it's urgent ?
