### ISSUE TITLE
Notify Plugin: Prevent duplicates

### ISSUE THREAD

**Issue by matthiasmeier** [quasarframework/quasar#6189]
**Is your feature request related to a problem? Please describe.**
When there are a lot of notifications shown, the screen gets pretty crowded and sometimes even partially unusable when the notifications cover buttons, links or other interaction elements.

This especially annoying when for some reason the same notification is shown multiple times. (E.g. when let’s say some function shows a generic notification for multiple "Action finished successfully" messages.)

**Describe the solution you'd like**
It would be fantastic if there was an option to prevent duplicated notifications. Or even better – group the same notifications together and show a `q-badge` on the notification with the according amount in it. (Similar to what the dev tools in the browser do when there’s the same message/log a couple of times.)

**Additional context**
I’m aware that in such a case the order of notifications could be "wrong" in terms of the order in which the according actions happened. But I think that the advantage of not having a screen full of notifications would justify that.

This option could be added either globally in the `setDefaults` 
```javascript
this.$q.notify.setDefaults({
    // duplicates: prevent, // Prevent duplicates …
   duplicates: group, // … or group duplicates (and show according amount in badge)
   badgeColor: 'red' 
})
```

… and/or could be set per notification:
```javascript
this.$q.notify({
    message: this.$t('common.notifications.edit-mode-enabled'),
    timeout: 1500,
    duplicates: prevent
})
```
![q-notifications-badge](https://user-images.githubusercontent.com/900640/72909023-a856a380-3d36-11ea-8c55-8e6aa7c9cd12.jpg)

**Comment by rstoenescu** [comment]
Feature will be available in "quasar" v1.9.0 through new props:
* optional "group" prop (if not specified, it is hashed to message + caption)
* optional "badge" Object prop: { color, textColor, style, class }
