### ISSUE TITLE
QPopupProxy does not pass target prop to QMenu component

### ISSUE THREAD

**Issue by losadaem** [quasarframework/quasar#6192]
**Describe the bug**
When using `target` prop with `QPopupProxy` and setting props like `anchor` and `self` that are passed through `QMenu` the positioning of the menu doesn't take into account the target element.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/rte39ujc/

**To Reproduce**
1. Increase the size of the render split panel to see the problem better.
2. Click on 'TEST ME DATE'
3. See error

**Expected behavior**
To position the `QProxyPopup` menu the same way as the `QMenu` component.

**Comment by pdanpdan** [comment]
This will be fixed in the next version v1.9.0, thank you for reporting.
