### ISSUE TITLE
Progressbar QFile

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6193]
It's possible to Add progress bar when file is uploaded ?
like this [component](https://gwtmaterialdesign.github.io/gwt-material-demo/#fileuploader)

**Comment by metalsadman** [comment]
@nseb you can attach a linearprogress somewhere as loading indicator. https://quasar.dev/vue-components/linear-progress#Introduction

**Comment by nseb** [comment]
It's possible to have drag and drop ?

**Comment by pdanpdan** [comment]
@nseb Drag and drop progressbar? :)

**Comment by rstoenescu** [comment]
1. If you want Quasar to handle the upload process also, then there's a better fit: [QUploader](https://quasar.dev/vue-components/uploader).
2. QFile already has drag'n'drop support.
3. QFile also has a "loading" Boolean prop that you can use. Also, it inherits everything else from QField (so you can play with the slots).

**Comment by pdanpdan** [comment]
Here is an example:
https://codepen.io/pdanpdan/pen/bGNzYdG?editors=1010
