### ISSUE TITLE
Error in mounted hook: "SyntaxError: '' is not a valid selector"

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#6198]
![image](https://user-images.githubusercontent.com/19161540/72979969-8bd26e00-3dff-11ea-9846-c34174797a98.png)

**Comment by pdanpdan** [comment]
What are you passing as `scroll-target` to QPopupProxy?

**Comment by elselapatha** [comment]
> QPopupProxy

I'm not using QPopupProxy component and scroll-target attribute too

**Comment by elselapatha** [comment]
this error occurred after 1.8 upgrade before than working fine

**Comment by elselapatha** [comment]
![image](https://user-images.githubusercontent.com/19161540/72987822-2d15f000-3e11-11ea-963b-98b1a6c60ade.png)

**Comment by pdanpdan** [comment]
I don't understand, I got some mails with updates but I don't see the comments here.
Please reopen if it's still a problem.
