### ISSUE TITLE
Please add the opportunity of editing the background color of QStepper component in the next releases

### ISSUE THREAD

**Issue by N1Mirzo** [quasarframework/quasar#6200]
_Razvan Stoenescu and staff.(I am writing this in a Happy Mood, so don't think me, "you're writing in ordering mood")._

**_Consider this post as a feature request or feedback for the highest ranked and the best framework, Quasar. But this is not a complaint. I only said, if you add this things I believe it will be great! I have been using Quasar for a long time. And for me, it's a pleasure to create a cross-platform app using Quasar capabilities. And I believe Quasar is the best framework in the world. I am happy that If I  gave a little feedback of myself for Quasar's development._**

**_Hmm, I think adding QStepper component was the best one in the versions released before. And there is no such a component in some of the other frameworks. BUT, I think header of QStepper should be more customizable. For example its backgound color. I tried so many times but I couldn't. I asked help in #components channel. They gave me their help. But it was only working on CodePen.Io website (https://codepen.io/Mirzo-N1/pen/mdyvMoM). But when I copied and see before editing it, the look of my website was not the same with the one in the CodePen which I said above. I will send you the two images first one is the worked code in  CodePen. And the second is the one after I copied. So ,please add the opportunity of editing the background color of QStepper component n the next releases._**

Thank you in advance.

**Comment by pdanpdan** [comment]
Hello. It's a very simple set of css rules you need to apply. You already have a working simple example.

Please use discord channel for support requests.

Thank you.

**Comment by N1Mirzo** [comment]
@pdanpdan Yes, you're right and the staff helped me in discord.
BUT, It doesn't work in the project it only works in codepen.
For sure create a new Quasar project and write the working codes in it.
You can't get what you see in the codepen.I'm sure for that.
Just the link is here you can test it! [CodePen Link To Test](https://codepen.io/smolinari/pen/ZEYwywx)

**Comment by N1Mirzo** [comment]
And please open the issue if someone know they may write.
Or otherwise pleease, help me to create the component. Please.

**Comment by smolinari** [comment]
@N1Mirzo - Please offer your code in Discord, so we can help you get it right. 

Scott
