### ISSUE TITLE
Draggable Floating action button

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#6201]
Nice to have this feature for the floating action button

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/xxbBZOM?editors=1010

**Comment by smolinari** [comment]
Nice! It's that easy? OMG! 😁 

Scott

**Comment by RonaldinhoL** [comment]
> https://codepen.io/pdanpdan/pen/xxbBZOM?editors=1010

the link was not accessable now, anyone can explain more in here?

**Comment by RonaldinhoL** [comment]
nvm found here https://quasar.dev/vue-directives/touch-pan
