### ISSUE TITLE
Quasar / Docs Menu According does not function while displayed in left dialog

### ISSUE THREAD

**Issue by stevebor1** [quasarframework/quasar#6206]
**Describe the bug**
When the viewport is minimized to display left menu as  dialog / modal, the accordion does not function and menu does not dismiss on click away.

This is discovered while using the docs section of quasar.dev and resizing to a smaller window.
https://quasar.dev/vue-components/tab-panels

I am not sure this is a Quasar bug or some other issue with how the docs section was developed :)

**Expected behavior**
The accordion should open and close items.
The menu should close if user clicks away (not sure if it was coded this way or not)

![quasar mobile menu issue](https://user-images.githubusercontent.com/1202448/73008247-08932700-3dc3-11ea-8466-284eb63b9e4a.gif)

**Comment by rstoenescu** [comment]
Can't reproduce :/

**Comment by pdanpdan** [comment]
Hello. Before you finish the click you move your mouse, and that starts to move the drawer's scroll.
Just click.

**Comment by stevebor1** [comment]
I am on
OS Windows 10
Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Edge Version 79.0.309.68 (Official build) (64-bit)

Open browser to docs url
Click menu accordion to open / close
Resize browser so that the menu hides
Open menu
Click on accordion; does not expand; does not close when clicking away

![quasar mobile menu issue chrome edge](https://user-images.githubusercontent.com/1202448/73038377-1074ba80-3e07-11ea-9303-00fa28d5115c.gif)

**Comment by metalsadman** [comment]
can't reproduce either here windows 10 chrome Version 79.0.3945.130 (Official Build) (64-bit) and MS Edge Version 79.0.309.71 (Official build) (64-bit).
this is most likely just in your browser maybe an extension is messing it up, try resetting your settings and restart your pc.
