### ISSUE TITLE
Option to show fill-mask only while input is focused

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#6207]
**Is your feature request related to a problem? Please describe.**
Mask fills can clutter the UI when there are several and the fields are empty.

**Describe the solution you'd like**
Add the option to show a mask only when the input has focus.

**Describe alternatives you've considered**
Adding `@focus` and `@blur` event handlers to set a true/false value that is used for the `fill-mask` prop.

**Additional context**
The mask itself should remain applied regardless of focus state, only the unfilled portion of the mask would disappear when not focused.

**Comment by pdanpdan** [comment]
The alternative is the correct thing, and is all that can be done.
