### ISSUE TITLE
QTable bottom non-pagination slot / QTable default pagination independent component

### ISSUE THREAD

**Issue by DelaneDiamon** [quasarframework/quasar#6208]
**Is your feature request related to a problem? Please describe.**
There are bottom and pagination slots for q-table at the bottom. 
I would like to keep default "Rows by page" selector component or q-table pagination component as a whole, but also implement q-pagination component in the middle of the bottom of q-table.

**Describe the solution you'd like**
Extract default q-table pagination as a separate component to be able to combine q-pagination with default q-table pagination in the bottom slot **or** provide additional slot to place content at the bottom of the q-table next to pagination slot.

**Describe alternatives you've considered**
Copying q-table default pagination component

**Additional context**
None

**Comment by ajcastro** [comment]
Do you mean something like this? I extract and created a component `TablePagination` which I put in top slot of my q-table so I have a pagination on top of my table.. 

https://gist.github.com/ajcastro/83af279e7d7540f82cae791d9bd430f9

**Comment by rstoenescu** [comment]
Enhancements will be available in "quasar" v1.12.0.
