### ISSUE TITLE
Better QItem routes matching

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#6209]
**Describe the bug**
I am using the QItem 'to' property for routing (like QTabs with QRouteTab), with the following routes: 

* `/users`
* `/user/123` (user ID)

I want the route `/users` to also match `/user?page=3` and other queries as these change dynamically within the page. With the example below connected to real routing and pages, the QTabs work perfectly but with QItems the route `/users/123` also makes `/users` active. 

I want `/user/123` to match only `/user/123`. Also I want `/users` and `/user?page=3` to match `/users`. 

When using the exact property `/users` is not matched on route `/user?page=3`. When not using the exact property `/users/123` also matches `/users`.

This has been difficult to communicate because I can't seem to get the example working with real routing. 

**Codepen example - QItems vs QTabs**
https://codepen.io/Fanvadar/pen/JjoxQmm

**Screenshots**
![image](https://user-images.githubusercontent.com/11305093/73042711-efb37000-3ead-11ea-8e00-e0540149edac.png)

**Platform (please complete the following information):**
OS: Windows
Node: v10.16.3
NPM: 6.9.0
Yarn: 1.19.1
Browsers: Chrome

**Comment by rstoenescu** [comment]
Hi,

Use the “exact” boolean prop on QItem with routing to “/users”. Always check the API card on docs.

**Comment by Fanvadar** [comment]
Like I said in the OP, when I use the exact property, `/users` is not matched on the route `/user?page=3` and therefore will not display as active.

**Comment by rstoenescu** [comment]
I thought that was a mistake, because in the same phrase you then mention `/users/123` and `/users`. Can you please correct that?

QItem uses Vue Router's matching and what you are requesting is not possible with that. Will mark this as a feature request.

**Comment by Fanvadar** [comment]
Okay thanks, I've updated it to be a bit more clear. 

The reason I thought this was a bug was because QTabs is already able to handle this with almost the exact same code (as seen in the Codepen).

**Comment by rstoenescu** [comment]
Yes, but QTabs uses our own algorithm where it makes a whole lot more sense. If we implement it for QItems too, then all the perf would go down severly...

**Comment by Fanvadar** [comment]
Oh I see... 
Well thanks so much for explaining this, and because it seems this isn't feasable I'll close this.

**Comment by rstoenescu** [comment]
I'll have this ticket in mind and see if I can do something on the next versions without a heavy impact on the perf. If it can be done, I'll reference this ticket.
