### ISSUE TITLE
Prop expand resetting to false when I have q-input 

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#6210]
**Describe the bug**
The prop `expand` is resetting to false when I have input and change the value. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ajcastro/pen/QWwoLOP?editors=1010

**To Reproduce**
1. Expand a row
2. Type or change the value in the q-input
3. You will notice the row closed because the prop `expand` suddenly changed to false

**Expected behavior**
The row should stay open (expand should stay true)

**Comment by pdanpdan** [comment]
As I told you already on the discord channel, you are editing the value used as key for the row.
Change the column used as key.
