### ISSUE TITLE
QTime midnight and midday are displayed reversed on "format24h"

### ISSUE THREAD

**Issue by de-mim-1974** [quasarframework/quasar#6211]
**Describe the bug**
In QTime the time '00' and '12' at the wrong place and should by reversed. '00' should be there where the '12' is and vice versa.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/time#Example--QDate-and-QTime-with-QInputCodesandbox 

**To Reproduce**
Use Chrome v79.0.3945.117(64bit) / also FF ...
1. Go to URL (Quasar dev - QTime)
2. Open a QTime Popup
3. You see the Bug

**Expected behavior**
'00' should be there where the '12' is and vice versa.

**Screenshots**
![image](https://user-images.githubusercontent.com/31286244/73062047-c38ef380-3e9b-11ea-8819-f84e9b4d7740.png)

**Comment by pdanpdan** [comment]
You people are so funny:

https://github.com/quasarframework/quasar/issues/4755
