### ISSUE TITLE
[Request] scrollArea smooth scroll

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#6213]
**Is your feature request related to a problem? Please describe.**
The scrollbar in a scrollArea is never smooth.

**Describe the solution you'd like**
The scroll bar should be smooth, and if we can choose the smoothness of the scroll bar just like in the setScrollPosition function, this is even better ;)

**Describe alternatives you've considered** 
The only way I found to make it smooth is to use the method setScrollPosition. Also, this doesn't work inside the scroll area since I am using the wheel event to make it work.

**Additional context**
Go to https://quasar.dev/vue-components/scroll-area
Try wheeling in scroll areas

**Comment by pdanpdan** [comment]
That is something you can set in browser or is.

**Comment by Medhyena** [comment]
Can you go further in the explanation? CSS doesn't work there, and as I said, I didn't find any way to make it work smoothly, also no examples are displayed on the documentation page (would be a good thing to do)

**Comment by pdanpdan** [comment]
Sorry, it was a typo - it should have been OS (not is).
So QScrollArea uses the scroll smoothness that is used by the browser for wheel scroll.
In chrome I think there is a chrome://flags option for smooth scroll, and in firefox I think there is an option in settings.

**Comment by pdanpdan** [comment]
Now that I think more about it I'll try something and post back.

**Comment by rstoenescu** [comment]
Hi,

Enhancement will be available in "quasar" v1.8.4.

**Comment by Medhyena** [comment]
Thank you and good job ;)
