### ISSUE TITLE
Slide Item with v-if

### ISSUE THREAD

**Issue by KNetiin** [quasarframework/quasar#6214]
**Describe the bug**
The slide item is about the information, default template.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/knetiin/pen/mdyoVxr?editable=true&editors=101

**To Reproduce**
1. Drag left or right (slide item)
2. Click on toggle (Disable template left and right)
3. Click on toggle (Enable template left and right)

**Expected behavior**
I dont know

**Screenshots**
![error](https://user-images.githubusercontent.com/39486992/73075665-32b81800-3e9b-11ea-92da-ec13761c7a93.png)

**Platform (please complete the following information):**
OS: W10 -  GOOGLE CHROME
Node: v12.14.0
Yarn: 1.21.1

**Comment by KNetiin** [comment]
SOLVED:

.q-slide-item__content
    transform: translate(0px, 0px)

**Comment by rstoenescu** [comment]
Fix will be available in v1.8.3.
Thanks for reporting!

**Comment by rstoenescu** [comment]
For whoever is reading this, the fix above is NOT the right way. Please wait for v1.8.3.
