### ISSUE TITLE
q-btn loading+disabled

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6220]
**Is your feature request related to a problem? Please describe.**
I can't imagine case when button shouldn't be disabled while it's in loading state.
When it is loading? e.g. when it is "submit" button, we click to send data - button is being in "loading" state. 
But it should be disabled, we not able to click the button again before response/callback is given

**Describe the solution you'd like**
Combine loading and disable states. If it is loading - is should be disabled.

**Describe alternatives you've considered**
Or, not the best way, new prop, smth like `submitting` - we see spinner and button is disabled.

**Comment by matro-skin** [comment]
Now all the "submit" buttons I must duplicate state in two props to prevent missclick while data's sending
`<q-btn :loading="loading" :disable="loading" />`

**Comment by rstoenescu** [comment]
Hi,

QBtn does not emit any click events when in loading mode however the `<form>` native tag doesn't care about that. Will fix this behavior.

**Comment by matro-skin** [comment]
So is it just "visual" bug?

**Comment by rstoenescu** [comment]
Not a visual bug. Just a side effect of how browsers work when QBtn is wrapped by a `<form>`.

**Comment by rstoenescu** [comment]
Thanks for reporting this.
Fix will be available in "quasar" v1.8.3.

Took this opportunity to make some nice enhancements to the behavior of QBtn in loading state too.

**Comment by novuscy** [comment]
I still have this issue with Quasar 2.0.3, is this a regression in the Quasar V2?
