### ISSUE TITLE
qinput type number accepts characters

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#6221]
Hi

I'd expect the following input
`<q-input filled v-model.number="itemCount" type="number" label="Items count" />`
to accept only digits but it also accepts characters. Is it on purpose?

To reproduce just add the above line. In the docs, the relevant input also accepts characters.

The expected behavior is that the field will accept only digits and a decimal separator and ignore all characters.

**Comment by rstoenescu** [comment]
Hi,

There are only a billion browsers and platforms, so not specifying which means back-and-forth and lost time. I cannot replicate your issue. Furthermore, the accepted characters are handled exclusively by the browser.

**Comment by Amosss** [comment]
Man you're right....
Firefox 72.0.2 accepts characters
Chrome 78 accepts only digits as expected...
Just for my clarity: is it a bug in Firefox?
