### ISSUE TITLE
Auto import feature breaking class components global registration scope

### ISSUE THREAD

**Issue by Eldar-X** [quasarframework/quasar#6228]
When auto import is turned on and the Class decorator is used, globally registered components cannot be found.

This problem only appears when auto import is active and used in the class decorator and when at least 1 quasar component is included.

Error: did you register the component correctly? For recursive components, make sure to provide the "name"

```typescript
import Vue from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'
import i18n from './i18n'
import './quasar'
import MyTest from './components/MyTest.vue'

Vue.config.productionTip = false
Vue.component('MyTest', MyTest)

new Vue({
  router,
  store,
  i18n,
  render: h => h(App)
}).$mount('#app')
```

```vue
<template>
  <div>
    <MyTest></MyTest>
    <q-input></q-input>
  </div>
</template>
<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator'

  @Component
  export default class TestPage extends Vue {
  }
</script>
```

It's working when not using vue-class-component decorator or when no quasar components exists or when auto import feature is disabled.

**Comment by webnoob** [comment]
I use `auto: 'all'` with classes and have my components declared gloablly without issue 🤔

**Comment by Eldar-X** [comment]
Oww, this is my fault. I forgot to add the class decorator to the app component, so it loses the scope during rerender.
