### ISSUE TITLE
QSeparator between QCard not working

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6230]
**Describe the bug**
I want use a QSeparator  in infinite scrol panel or each item it's a QCard , but it's not working , QSeparator not display

**Codepen/jsFiddle/Codesandbox (required)**
` <q-card flat class="full-width" v-for="(item, index) in items" :key="index" style="margin-bottom: 6px">
        <q-card-section horizontal>
          <q-img
            :src="getPostMedia(item)"
            class="col-4"
          >
          </q-img>
          <q-card-section class="col-8" horizontal style="padding:0px;padding-left: 2px">
            <q-card-section style="padding :0px">
              
              <div class="text-h6">{{item.title}}</div>
              <div class="text-caption text-grey">
                {{getAbreviatePostResume(item)}}
              </div>
              <div>Date</div>
            </q-card-section>
          </q-card-section>
        </q-card-section>
      </q-card>
      <q-separator inset ></q-separator>`
**To Reproduce**

**Comment by Valianton** [comment]
https://codepen.io/Valianton/pen/abzKpvN

**Comment by pdanpdan** [comment]
Thank you @Valianton for putting the code in a codepen. Closing because the original issue is missing almost all details required in the issue template.

**Comment by nseb** [comment]
Thanks @Valianton @pdanpdan
