### ISSUE TITLE
Loading prop on QTab/QRouteTab

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6231]
**Is your feature request related to a problem? Please describe.**
Among `QTabs` I have one which doesn't switch content or goes to route.
It just call method by `@click`. So it will be use to switch state to `loading` while response is returned.

**Describe the solution you'd like**
Add prop `loading` at `QTab`/`QRouteTab`. Just replace content of tab with spinner. 

**Additional context**
Add `loading` slot to customize the spinner.

**Comment by pdanpdan** [comment]
Hello.
With very little CSS you can do a nice loading indicator:
https://codepen.io/pdanpdan/pen/zYxVjjP

And for replacing content with spinner just set the label to '' and put the spinner in the default slot:
https://codepen.io/pdanpdan/pen/gObNKyW?editors=1010

**Comment by matro-skin** [comment]
Second option is great, thanks )
