### ISSUE TITLE
'@input'  event not work at 'SELECT' component in quasar 1.8.3

### ISSUE THREAD

**Issue by dannykhoo** [quasarframework/quasar#6232]
After i upgraded to 1.8.3  ,  all my event '@input'  not work in 'SELECT' component .  Can fix it asap?  thanks in advance!

**Comment by pdanpdan** [comment]
Hello. Please reopen when you have all the details required for filled in. Thank you.

**Comment by pdanpdan** [comment]
> After i upgraded to 1.8.3 , all my event '@input' not work in 'SELECT' component . **Can fix it asap**? thanks in advance!

Didn't you forget to add: "toot suite, chop chop"?
