### ISSUE TITLE
Right-clickable QImg images so that they can be easily downloaded and viewed in full resolution

### ISSUE THREAD

**Issue by mYnDstrEAm** [quasarframework/quasar#6233]
For web apps made with QF it would be useful if the [QImg](https://quasar.dev/vue-components/img) images were right-clickable with the usual context menu entries for images like "View Image" and "Save Image As..."

Asking this due to: https://github.com/mYnDstrEAm/Switch2Linux/issues/17

An alternative solution would be to add a button to the image that opens it in full resolution or to link it to its full resolution image. But I'd like to avoid doing that in my case and having these context menu entries is useful even if such an alternative solution is implemented.

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.8.4 through a new Boolean prop (`native-context-menu`).
