### ISSUE TITLE
Single row expansion for QTable

### ISSUE THREAD

**Issue by tof06** [quasarframework/quasar#6235]
It would be great if `QTable` could have a property `expansion` which would allow to have only a single row expanded at a time (like an accordion).

`expansion="single"`: single row expansion
`expansion="multiple"`: (default) multiple rows expansion, current behavior.

For now, I'm using the new (1.8.3) `expanded.sync` with a computed property like this :
```
<q-table
  :expanded.sync="expanded"
  .../>

data() {
  expandedInternal: []
}

computed: {
  expanded: {
    get() {
      return this.expandedInternal
    },
   set(val) {
     this.expandedInternal = val.filter(x => !this.expandedInternal.includes(x))
   }
 }
}
```

But it would be great if this can be in integrated into QTable.

Thanks

**Comment by pdanpdan** [comment]
This can be done much simpler like here:
https://codepen.io/pdanpdan/pen/eYmwryW?editors=1010

But because it is so simple and not something that is needed by lots of users let's keep it in user land.

**Comment by fabriciobatalha** [comment]
> This can be done much simpler like here: https://codepen.io/pdanpdan/pen/eYmwryW?editors=1010
> 
> But because it is so simple and not something that is needed by lots of users let's keep it in user land.

Thank you, my friend @pdanpdan. It Works very well!
