### ISSUE TITLE
[docs] q-table documentation missing property computedData

### ISSUE THREAD

**Issue by XiaotongW** [quasarframework/quasar#6239]
It is normal for the [`computedData`](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/QTable.js#L139) property to be missing from the [q-table](https://quasar.dev/vue-components/table) documentation ?

**Comment by rstoenescu** [comment]
Hi,

That is internal, so "yes".

**Comment by XiaotongW** [comment]
- So how do we get the current displayed rows?

- Is it safe to used this property?

**Comment by rstoenescu** [comment]
Although it's internal, this one is pretty safe to use as it's not going to change.
