### ISSUE TITLE
Make auto-import work with Typescript too

### ISSUE THREAD

**Issue by DenisNP** [quasarframework/quasar#6240]
**Describe the bug**
Auto-import doesn't work with Typescript project if I import components in router as static files, non in lazy style. See below.

**Codepen/jsFiddle/Codesandbox (required)**
Cant recreate this in Codepen etc. [Here is the reproduction repo](https://github.com/DenisNP/quasar-import-bug).

**To Reproduce**
```bash
quasar create myapp
cd myapp
quasar ext add @quasar/typescript
```
Then in `router.ts` change any lazy-import to static one ([commit](https://github.com/DenisNP/quasar-import-bug/commit/1a2fff97bd3e8a5542de2eb3ad4c2b6bba38fa9f)):
```ts
import { RouteConfig } from 'vue-router'
import MyLayout from '../layouts/MyLayout.vue'

const routes: RouteConfig[] = [
  {
    path: '/',
    component: MyLayout, // <= here it is!
    children: [
      { path: '', component: () => import('pages/Index.vue') },
    ],
  },
];
```
Run `quasar dev`, you'll see a lot of errors like `Unknown custom element <q-layout>`.

**Expected behavior**
App loads normally and all the components are auto-imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/720975/73196017-ed684480-413f-11ea-93bd-a22217d1e1b5.png)

**Platform (please complete the following information):**
Operating System: Windows_NT(10.0.18362) - win32/x64
NodeJs: 12.13.0

Global packages: 
NPM 6.12.0
yarn Not installed
@quasar/cli 1.0.5
cordova Not installed

**Comment by pdanpdan** [comment]
Hello.
Can you please check if this https://github.com/quasarframework/quasar/issues/6228 is not the same issue you have here?

**Comment by DenisNP** [comment]
@pdanpdan I don't use class components, see my repo. This is fresh project right from the template with one small change.

**Comment by rstoenescu** [comment]
Auto import works only with Babel.
Marking this as a feature request.

**Comment by IlCallo** [comment]
@DenisNP just created a new project (now TS support is integrated into core), imported the layout directly and had no problems.
Can you check if everything works fine for you with the new TS option when creating a new project?

**Comment by DenisNP** [comment]
@IlCallo I've given up using auto-import because there are many `Unknown custom element` errors when I use it in components connected with `v-if` directive. Now I import all necessary components explicitly.

**Comment by rstoenescu** [comment]
@DenisNP The TS App Extension has been deprecated. Everything needed is now supplied directly by `@quasar/app`. So try to create a new project, select the TS support, and see if you can reproduce the problem again. Do NOT install the TS AE (skip step `quasar ext add @quasar/typescript`).

Feel free to reopen if you still encounter problems.
