### ISSUE TITLE
QSelect - Native QChips should expose props for text & background color

### ISSUE THREAD

**Issue by stevebor1** [quasarframework/quasar#6241]
**Issue**
When using "use-chips", the selected items are displayed using the native QChip components, however no direct styling is available without replacing selected item with a QChip by way of the selected item slot.

In my specific use case, I have entities/options that correspond to a specific color throughout my application, ie Companies, Signals, Themes. I would like to have those selected match the corresponding color when selected in a QSelect.

Default behavior:
![image](https://user-images.githubusercontent.com/1202448/73204927-c2a4ce80-40f4-11ea-9cb8-ac627ed79cfe.png)

Exposed color props
![image](https://user-images.githubusercontent.com/1202448/73205037-04357980-40f5-11ea-9494-e782d0b2982a.png)

**Solution**
An optional prop for "chip-text-color" & "chip-bg-color" should be made available so that they can easily be set.

**Existing Alt Solution**
An alternate solution would be to define a new QChip and apply to the selected item slot, however since this is just a styling change, it would be nice to not have to do it with way.

**Comment by pdanpdan** [comment]
Hello.

It is very simple to customize the QChips as you see fit - here is an example
Some new options would only generate overhead for the ones that do not use them, and with a great probability you would still need to customize the QChips further.

So please use the simple method, thank you.

**Comment by Crypto69** [comment]
The example provided is great thanks (https://codepen.io/pdanpdan/pen/yLyroQK?editors=1010)
Please note it only works if the colour attribute is a colour label like red or green or blue. If you try use this with custom colours eg

` {
    label: 'Facebook',
    value: 'fb',
    color: '#d66c00'
  }
`
It won't work. If you have customised colours from a colour picker for example you need to change this line of code     

`:color="scope.opt.color"`

 to this

` :style="{ backgroundColor: scope.opt.color }"    `
