### ISSUE TITLE
q-select: Emit event when options change

### ISSUE THREAD

**Issue by MadnessTabletop** [quasarframework/quasar#6248]
**Is your feature request related to a problem? Please describe.**
While using q-select, I am dynamically loading in data to create more options as the user scrolls. This is do a sort of pagination in the selection so that queries to a database don't respond with large chunks of data. Using virtual-scroll, this works fairly well, I'm able to filter, and add in options to the q-select fairly easily.

The problem comes in when adding the data however. When new data is added to the options, the q-select resets the virtual scroll position to 0. Which can be frustrating to a user who may have scrolled quite far down on the q-select. Now, we do have the scrollTo method for q-selects. But we hit a timing problem if we try to use scrollTo to update the index of the virtual scroll. We don't have an event for adding options to the q-select. The events we have are only for when the value of the q-select is changed. So if I try to set the scrollTo immediately after adding the options, it gets over-ridden when the q-select catchs up to render the newly added options.

This is also a problem if you decide to filter options out, and remove options from the list.

**Describe the solution you'd like**
I would like to have an event that emits when the options change in q-select. This would rid us of the timing issue since the options should have already changed by the time the event emits. Thus, making it safe to update the virtual scroll index.

**Describe alternatives you've considered**
Another thing that has come into my mind is to use v-bind:keys to help keep track of where the virtual scroll is. A potential issue that comes to mind with this though, is what if the items that are currently rendered in the virtual-scroll are removed?

**Comment by pdanpdan** [comment]
We have some tweaks on virtual scroll in v1.8.4 and we added an example in docs on how to dynamically add options on the end of the list.

For changes done in filter function there is already an example in docs.

**Comment by MadnessTabletop** [comment]
Dang that was a fast response. Thank you.
