### ISSUE TITLE
Add outline-color in QBtn to separate the outline color and the label text color

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#6252]
Currently this is how I do it:
```html
<q-btn
  no-caps
  outline
  dense
  size="md"
  class="fa-14 q-px-sm"
  color="grey-5"
>
  <div class="text-black">
    Filter
  </div>
</q-btn>
```

I suggest we can do something like this:
```html
<q-btn
  no-caps
  outline
  dense
  label="Filter"
  size="md"
  class="fa-14 q-px-sm"
  outline-color="grey-5"    // new prop outline-color
  text-color="black"
/>
```
This is is more convenient when changing props if the UI designer wants to switch to
different styles because the html markup is the same structure.

**Comment by pdanpdan** [comment]
Hello.

The way you do it in the first example is the preferred way to do it. An alternative would be to add a specific class on the QBtn and add a CSS rule to set the label text to your desired color.

**Comment by ajcastro** [comment]
Ok, thanks!. Here what I did

```html
<q-btn
    no-caps
    outline
    dense
    size="md"
    class="fa-14 q-px-sm my-btn"
    color="grey-5"
    label="Filter"
    icon="fa fa-filter"
/>

<style lang="scss">
.my-btn .q-btn__content *{
  color: #000000;
}
</style>
```
