### ISSUE TITLE
Electron: In preloader, require is not defined

### ISSUE THREAD

**Issue by MadnessTabletop** [quasarframework/quasar#6256]
**Describe the bug**
I'm running Quasar 1.5.2, with node integration off. However, in my preload script I'm getting an error that require doesn't exist.

It was my understanding that I should still be able to require in the pre-load script as long as I used the same name as defined in the docs.

Turning nodeIntegration to true does fix this. But that can be a security issue, and since this is a preload script I should be able to have nodeIntegration off.

Doing some testing shows that require is available in the pre-load script, and its type is function. However, it looks like webpack is still attempting to do something with it.

**Codepen/jsFiddle/Codesandbox (required)**
Considering this is for Electron, a Codepen/jsFiddle/Codesandbox is not doable. However.

Main Window Creation (src-electron/main-process/electron-main.js):
```
import { app, BrowserWindow, ipcMain } from 'electron'
import path from 'path'

/**
 * Set `__statics` path to static files in production;
 * The reason we are setting it here is that the path needs to be evaluated at runtime
 */
if (process.env.PROD) {
  global.__statics = require('path').join(__dirname, 'statics').replace(/\\/g, '\\\\')
}

let mainWindow

function createWindow () {
  /**
   * Initial window options
   */
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    useContentSize: true,
    webPreferences: {
      preload: path.resolve(__dirname, 'electron-preload.js'),
      nodeIntegration: false,
      enableRemoteModule: false,
      contextIsolation: true,
      sandbox: true
    }
  })

  mainWindow.loadURL(process.env.APP_URL)

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow()
  }
})

ipcMain.on('check', (event, data) => {
  // Access form data here
  console.log(data)
})
```

Preload (src-electron/main-process/electron-preload.js):
```
const { ipcRenderer } = require('electron')

process.once('loaded', () => {
  window.addEventListener('message', event => {
    const message = event.data

    ipcRenderer.send(message.myTypeField, message)
  })
})
```

**To Reproduce**
1. Turn off node integration
2. Add a pre-load script as described [here](https://quasar.dev/quasar-cli/developing-electron-apps/electron-preload-script)
2. Try to require ipcRenderer in pre-load script

**Expected behavior**
I would expect to be able to run requires in Electron Pre-load scripts

**Screenshots**
![](https://cdn.discordapp.com/attachments/596276102570311681/672174345862381568/unknown.png)

**Platform (please complete the following information):**
OS: Windows 10 & Mac 10.15.1
Node: 8.11.1
NPM: 6.0.1
Electron: 5.0.13

**Comment by MadnessTabletop** [comment]
per the suggestion of a kind soul on the discord, I attempted to use.

`import { ipcRenderer } from 'electron'`

However, this sadly results in an error as well.

![](https://media.discordapp.net/attachments/596276102570311681/672461095956381696/unknown.png?width=400&height=224)

**Comment by MadnessTabletop** [comment]
I think the issue comes from using a project that was originally generated with an older version of quasar.

I created a brand new project and was able to use require just fine.

**Comment by rstoenescu** [comment]
If not following the exact syntax where you point to the preload script, then things might work just for prod or just for dev...

**Comment by MadnessTabletop** [comment]
@rstoenescu 

My Code (As above):

`preload: path.resolve(__dirname, 'electron-preload.js'),`

Docs (As detailed [here](https://quasar.dev/quasar-cli/developing-electron-apps/electron-preload-script)):

`preload: path.resolve(__dirname, 'electron-preload.js')`

I'm not seeing the difference

**Comment by Pmca96** [comment]
The first two errors comes from compiling, when you compile the application preload.js isnt being found you have two option, add preload manualy or add automaticly when you start

The second error you need to set target web in your webpack config

The image bellow is my vue.config.js for building electron with vue, its fixes the two bugs

![imagem](https://user-images.githubusercontent.com/43204551/116791959-b658af80-aab5-11eb-89fb-658d4a68efc3.png)

**Comment by eric-burel** [comment]
You should probably build this file alongside the renderer process, instead of using the main process build, but to be confirmed

The problem is that the preload script need to access Node API but be built for the web, so I am not sure how to handle it correctly. Using `electron-preload` target like here doesn't work: https://stackoverflow.com/questions/43796358/how-do-i-compile-a-preload-script-w-webpack-in-electron
