### ISSUE TITLE
Push multiple value on Q-Select add-new-value mode in once enter

### ISSUE THREAD

**Issue by florensiuslaylim** [quasarframework/quasar#6257]
i had a problem when i copy and paste many value from excel in one row into Q-Select. But when i entered it, they push into array in one string. 

Actually i want that value split into multiple string based on my pasted value from excel

I suggest Q-select has new props like 'multiple' for get multiple value in once enter without enter many times for copy paste case.

**Comment by pdanpdan** [comment]
Hello. Can you please create and share a codepen with the code you have tried? We can improve from there.

**Comment by rstoenescu** [comment]
Added example in docs how to do it.
Will be available on next docs deployment which will come with v1.8.4.
