### ISSUE TITLE
Add HTML 'spellcheck="true"' option prop in Input Component and WYSIWYG Component

### ISSUE THREAD

**Issue by newCodeRunner** [quasarframework/quasar#6258]
**Is your feature request related to a problem? Please describe.**
If i want to add native HTML spell check attribute to a Quasar Form Component, i have to add it manually using Javascript once the component has rendered. 

**Describe the solution you'd like**
It would be nice to have a prop that you can just set to true for Input Text components and WYSIWYG components.

Link to this W3 HTML attribute
https://www.w3schools.com/tags/att_spellcheck.asp

**Comment by pdanpdan** [comment]
Hello, have you tried? Can you please supply a codepen with what you tried and is not working?

**Comment by rstoenescu** [comment]
@newCodeRunner All attributes get passed down to the inner native input. So `<q-input spellcheck="true"` will do the trick.
