### ISSUE TITLE
Bad template in PWA when use Prettier Eslint

### ISSUE THREAD

**Issue by MrJmpl3** [quasarframework/quasar#6259]
**Describe the bug**
The template of PWA generate error when compile, because has problem with Eslint - Prettier.

https://github.com/quasarframework/quasar/blob/dev/app/templates/pwa/register-service-worker.js

Related: https://github.com/quasarframework/quasar-starter-kit/pull/72/files

**To Reproduce**
- Create a project with Eslint Prettier
- Add SSR mode
- Activate PWA in SSR mode
- Start server

**Expected behavior**
Compile correct and open browser

**Comment by pdanpdan** [comment]
Hello.
The template files use the standard profile. In case you are using some other profile:

- check your package.json file to have

```json
"scripts": {
  "lint": "eslint --ext .js,.vue src src-pwa",
  ...
},          
```

- then do a `yarn lint --fix`

**Comment by MrJmpl3** [comment]
@pdanpdan I say, The cli need make a pwa template with config of prettier.

I wish this is added in the roadmap.
