### ISSUE TITLE
Adding a meta description tag through meta plugin results in duplicate tags

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#6260]
**Describe the bug**
Adding a meta description tag through meta plugin results in duplicate tags instead of replacing the existing description tag (coming from `index.template.html`)

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/busy-vaughan-7eyfx

**To Reproduce**
1. Add `meta` plugin to quasar.conf.js
2. Add the following to `src/App.vue`
```js
  meta() {
    return {
      meta: {
        description: {
          name: 'description',
          content: 'New description added through meta plugin'
        }
      }
    }
  }
```
4. Inspecting head section of the page shows duplicate description meta tag

**Comment by rstoenescu** [comment]
You've missed this on the Meta plugin docs:

![meta](https://user-images.githubusercontent.com/4665641/73434091-c0d64780-434e-11ea-8685-8a1afa7aca9f.png)

**Comment by ejez** [comment]
Got it, thanks @rstoenescu , sorry for disruption!

The natural place for the description tag is "page level" instead of "app level", so maybe something to consider is to remove it from `src/index.template.html` in the starter-kit

**Comment by rstoenescu** [comment]
Can't remove it from there because not everyone is using the Meta plugin. So not wanting to force devs do something they may not want/need.
