### ISSUE TITLE
In ssr mode, added meta tags through meta plugin result in incorrect position of charset meta tag

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#6261]
**Describe the bug**
`<meta charset="utf-8">` should be placed at the beginning of the head section.
Quote from MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset

> The <meta> element declaring the encoding must be inside the <head> element and within the first 1024 bytes of the HTML as some browsers only look at those bytes before choosing an encoding.

When adding meta tags through meta plugin in ssr mode, the added tags are placed at the top of the head section, resulting in pushing down the charset tag

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/busy-vaughan-7eyfx

The issue can also be seen in quasar website https://quasar.dev/
![Screenshot from 2020-01-30 11-36-46](https://user-images.githubusercontent.com/48388358/73433051-085fd200-4355-11ea-948a-0eb1d2c7df4e.png)

**Comment by rstoenescu** [comment]
Hi,

For perf reasons, Meta will not search upon the contents of the other `<meta>` tags that come from index.template.html. If this is of importance to you, then remove the charset from index.template.html and add it through Meta plugin. A good place for it would be src/App.vue to ensure that all pages will contain it.

**Comment by ejez** [comment]
Thanks again @rstoenescu 
maybe we can add a small note in the docs about this, as most people would easily miss it ?

**Comment by ejez** [comment]
> ...then remove the charset from index.template.html and add it through Meta plugin. A good place for it would be src/App.vue to ensure that all pages will contain it.

The problem with this is when running in spa mode, meta plugin tags are placed at the bottom including charset.

May I ask why there is different positioning of meta plugin tags for ssr and for non-ssr ?

**Comment by ejez** [comment]
a cumbersome workaround might be:

`index.template.html`
```html
<%= htmlWebpackPlugin.options.ctx.modeName !== 'ssr' ? '<meta charset="utf-8" >' : '' %>
```

`App.vue`
```js
  meta () {
    const metaObj = {
      title: 'My Quasar App',
      meta: {
        description: { name: 'description', content: 'A Quasar Framework app' }
      }
    }

    if (process.env.MODE === 'ssr') {
      metaObj.meta = {
        charset: { charset: 'utf-8' },
        ...metaObj.meta
      }
    }
    return metaObj
  }
```
