### ISSUE TITLE
Allow q-icon component to a different tag than <i>

### ISSUE THREAD

**Issue by Morialkar** [quasarframework/quasar#6263]
**Is your feature request related to a problem? Please describe.**
The q-icon uses the i tag to print the icon, which breaks semantic meaning of the tag according to the HTML Living Standard https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-i-element . It can arguably be used that way but it depends on your actual interpretation.

**Describe the solution you'd like**
The q-icon component should allow the use of either <span> or <i> elements using a property to allow most use cases implementation without trouble.

**Describe alternatives you've considered**
I considered building a custom component, which I really didn't want, and forcing the use of span but this would replace the current implementation for very little gain, and remove the choice for everyone.

**Comment by rstoenescu** [comment]
Hi,

Enhancement will be available in "quasar" v1.8.4.

**Comment by Morialkar** [comment]
Thanks for the reactiveness! Really impressive, even if it's a pretty simple enhancement.

**Comment by rstoenescu** [comment]
Btw, just released v1.8.4 :)

**Comment by rstoenescu** [comment]
If you can, please visit https://quasar.dev/why-donate
