### ISSUE TITLE
QOptionGroup (or multiple radio button) validation

### ISSUE THREAD

**Issue by nulele** [quasarframework/quasar#6264]
Is it already possibile? (I've tried with no luck)
Are you going to add this feature?

Thanks

**Comment by pdanpdan** [comment]
Hello, please check here: https://github.com/quasarframework/quasar/issues/5500

**Comment by nulele** [comment]
Ah... didn't think about the QField!
Thanks

**Comment by ivan006** [comment]
that styles the radio too look very weird tho so no i dislike this answer
