### ISSUE TITLE
q-input Not being registered as Vue Component

### ISSUE THREAD

**Issue by GGLionCross** [quasarframework/quasar#6266]
Testing q-input using data attribute and found that it is not registered as a vue instance for some reason. In Jest, I'm switching from targeting my Quasar components using classes to use data attributes instead, and it works as expected for all my q-checkbox, q-btn-toggle, and q-btn, but not for my q-inputs.
```
MyLayout.vue---------------:
<q-input
  data-attrib="input-name"
  class="input-name"
  label="Sample Label"
  :readonly="readOnly"
  maxlength="40"
/>
```
```
MyLayout.unit.test.js---------------------------------------------------------------------:
it('Sample Test Description', async() => {
  let wrapper = mountQuasar() // helper function for mounting quasar components
  //let name = wrapper.find('[data-attrib="input-name"]') // this doesn't work
  let name = wrapper.find('.input-name') // but this does work
  // passes when targeting via class but fails if using data-
  expect(name.isVueInstance()).toBe(true)
})
```
Also, if it helps, when I target by class and console log `name.html()`, I see that it targets the input as well as all of the wrappers (I'm assuming Quasar puts around it), but if I target via a data attribute and then console log `name.html()` it only targets the input element.

Update: Also fails if targeting using an id. But it's not good practice to be using ids in what are supposed to reusable Vue components anyway, but just thought I'd point that out

**Comment by pdanpdan** [comment]
All attrs (including data-attrib="input-name") goes on the real `<input ...>` DOM element.
Go up from there to the parent `<label>` to find the Vue element instance.
A simple function should be enough:

```js
function findVueInstance (sel) {
  let el = typeof sel === 'string' ? document.querySelector(sel) : sel
  
  while (el !== null) {
    if (el.__vue__ !== void 0) {
      return el.__vue__
    }

    el = el.parentNode
  }
}
```

**Comment by GGLionCross** [comment]
How come q-input is the only one that needs this, but q-checkbox applies the data attribute to the actual vue instance?

**Comment by pdanpdan** [comment]
Because the input field has lots of attributes that can be applied on it.
