### ISSUE TITLE
capacitor, QDialog, position bottom & seamless

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#6267]
**Describe the bug**
When running in capacitor mode, if I have a seamless QDialog with `position="bottom"` and `seamless`, the page scrolls to the the very end when the dialog shows.

The code causing the scrolling is at:
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/dialog/QDialog.js#L211
to
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/dialog/QDialog.js#L220

Should that code not run when seamless is set? Perhaps only if also position bottom?

**To Reproduce**
1. Clone the quasar repo
2. add capacitor mode
3. add ios
4. yarn dev:capacitor:ios
5. run from xcode (sim is fine)
6. Choose QDialog from the list (search for it)
7. drag the page so that sou can see the seamless button and position it so there is room for the page to scroll
8. press the seamless button
9. notice the page was scrolled to the end

**Expected behavior**
The page to stay where it is and the seamless dialog to open at the bottom.

**Screenshots**

**Platform (please complete the following information):**
Operating System	Darwin(19.2.0) - darwin/x64
NodeJs          	12.14.0

Global packages 	
yarn          	1.21.1
@quasar/cli   	1.0.3

quasar 1.8.3

iOS: Simulator Version 11.3.1 (running capacitor) (fresh setup)

**Additional context**
This is an issue as is, but I also have a page that closes the seamless dialog via a computed prop when near the footer of the page, so when its auto scrolled to the end, the seamless dialog closes (as expected from computed prop) but when I swipe/scroll back up, as soon as the seamless/position bottom dialog shows again, it immediately scrolls back down to the end of the page, trapping me there in the capacitor app.

**Comment by smakinson** [comment]
note, the seamless position bottom combination is fine in website when only using quasar dev

**Comment by metalsadman** [comment]
@smakinson try using the  `no-refocus` on your QDialog.

**Comment by smakinson** [comment]
@metalsadman Adding `no-focus` does seem to fix it. I'll go that route for now, but I suppose it would be better to not need to add those props. I'm looking back at the QDialog code, I had commented out `document.activeElement.scrollIntoView()` locally with no affect, so I'm wondering why `no-refocus` fixes it. I did not dig in far enough to see where `document.scrollingElement` gets assigned, does it have something to do with altering the value of that?

**Comment by smakinson** [comment]
Note. I just realized this also happens also happens on iOS safari, so its not limited to capacitor

**Comment by metalsadman** [comment]
> Note. I just realized this also happens also happens on iOS safari, so its not limited to capacitor

it overrides the default behavior, that's what those props are for. you can extend the qdialog with the 2 props set to true, then re-use that said extended component.

**Comment by rstoenescu** [comment]
Hi,

The props are as they are to enable accessibility by default.
