### ISSUE TITLE
QScrollArea: Allow simultaneous scrolling on touch screen

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#6269]
**Is your feature request related to a problem? Please describe.**
When on a touch screen (likely in an electron app, but any mode should work) a page with more than one QScrollArea should allow simultaneous scrolling. This would be most likely on a large touch screen where more than one user is interacting at the same time, perhaps scrolling through a list menu on each side of the display.

**Describe the solution you'd like**
Each person should be able to scroll at the same time with no interruption to the other users scrolling.

**Describe alternatives you've considered**
Directives outside of Quasar.

**Additional context**
The users should also be able to perform any other touch based interaction outside the scrollers with no interruption to scrolling for any user.

A current example with 2 QScrollArea's is here: https://codepen.io/smakinson/pen/bGNPWjo
For context, try to scroll both of those simultaneously. You will notice you cant and its possible to end up scrolling the opposite scroll area when swiping.

**Comment by pdanpdan** [comment]
There is already a change in code for the next version (1.8.4) that makes QScrollArea use the browser provided native scroll.
So if in browser in a simple html it works then it will also work on 1.8.4

**Comment by smakinson** [comment]
@pdanpdan I forked the codepen above and changed it to use 1.8.5. It looks like it is still not possible to interact with more than one scroll area at a time, it seems as soon as 2 touches are used it prevents the scroll dragging at all.

https://codepen.io/smakinson/pen/bGNPWjo

Can this feature request still be open for consideration?

**Comment by pdanpdan** [comment]
Does it work with 2 simple, native scrollable elements in a simple web page?

**Comment by pdanpdan** [comment]
I tested it on android(chrome) and iOS(safari and chrome).
On android it's not working, on iOS is working on both (but you might trigger zoom).
So it looks like you can make it work with the right hardware.

**Comment by smakinson** [comment]
@pdanpdan Thanks for checking into this. I do see it working on an iPad, I believe i did use an android tablet when setting up that codepen. I'm looking to make it work within electron on a windows box. I have used another directive I found for now that works after a slight modification (though it does not have a scroll bar) it was being interrupted by touch events outside of itself since it was listening for `touchmove` on `window`.

I am not having trouble with the window itself zooming, so I don't think thats the culprit. I use this to stop it:

```
webContents.setZoomFactor(1)
webContents.setVisualZoomLevelLimits(1, 1)
webContents.setLayoutZoomLevelLimits(0, 0)
```

I'm gonna send your codepen over to and see if it works on his display. It would be best to be able to stick with Quasar for all the components.

**Comment by smakinson** [comment]
@pdanpdan actually after reconfirming with the guy with the windows hardware, it seems the dual scrolling is working now on windows. I am going to see if I can work through this some more and update you later if I find anything of interest. It seems what he is seeing now is related to presses on the list & buttons inside the QScrollArea now, which I believe are all using `v-hammer:press`. Thanks again! This feature request may already be working fine, possibly with the exception of android.

**Comment by smakinson** [comment]
@pdanpdan After some back & forth I got one of the guys to record what he sees in chrome on his PC for this codepen: https://codepen.io/smakinson/pen/oNXXGPp?editors=1010

Would you be interested in checking  out the recording to see what you think of the trying using the 2 areas at once?
