### ISSUE TITLE
QBtnDropdown with split and padding is not working properly

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#6270]
I discovered that when QBtnDropdown  has a split, the padding is broken:

https://codepen.io/ajcastro/pen/dyPBRdR?editors=1010

My current fix/workaround is add class `.fix-split` then add the padding size:
```
.fix-split .q-btn.q-btn-dropdown__arrow-container{
  padding-right: 8px;
}
.fix-split .q-btn:not(.q-btn-dropdown__arrow-container){
  padding-left: 8px;
}

```

**Comment by Valianton** [comment]
U need to remove class **q-px-lg** from **q-btn-dropdown** with split = true

**Comment by pdanpdan** [comment]
You need to pad the buttons in CSS, something like this (add that class on the split QBtnDropdown):
It would look horible otherwise anyway.

```stylus
.q-btn-dropdown--split--padded
  > .q-btn:first-child
    padding-left: 18px
    padding-right: 15px
  > .q-btn:last-child
    padding-left: 7px
    padding-right: 7px
```
