### ISSUE TITLE
[docs] Request for docs page on Quasar SSR Cache

### ISSUE THREAD

**Issue by mohanzeal** [quasarframework/quasar#6271]
I want to implement caching for my quasar ssr build. 

Basically, I have some static pages like /about-us page where I only render simple text. I want to cache these kind of pages to reduce server load.

How do I implement Page-level Caching/component level caching (https://ssr.vuejs.org/guide/caching.html) in quasar framework. I have tried searching in the docs but I didn't get any information. 

Can any one please suggest me how to implement caching? Thanks in advance.

**Comment by pdanpdan** [comment]
Hello. Please search Google for how to implement server side http caching. It is something that is completely independent from Quasar and specific to your solution.
