### ISSUE TITLE
Assigning attribute id to QInput does not work

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#6274]
**Describe the bug**
This is the html:
```html
      <q-input
        id="email"
        filled
        v-model="email"
        label="Your email *"
        hint="Email"
        autocomplete="email"
        lazy-rules
        :rules="[ val => val && val.length > 0 || 'Please type something']"></q-input>
```
Notice, the `id="email"`

What happens, is it looks like quasar generates an id of its own, disregarding passed in id. The reason quasar does this, is for the `label for=""` attached to the input.

```html
<label for="f_a5c64984-a7cb-c5f7-2727-abd55fba3ba9" class="q-field row no-wrap items-start q-input q-field--filled q-field--focused q-field--labeled q-field--with-bottom q-field--error">
    <div class="q-field__inner relative-position col self-stretch column justify-center">
        <div tabindex="-1" class="q-field__control relative-position row no-wrap text-negative">
            <div class="q-field__control-container col relative-position row no-wrap q-anchor--skip">
                <input tabindex="0" aria-label="Your email *" id="f_a5c64984-a7cb-c5f7-2727-abd55fba3ba9" autocomplete="email" type="text" class="q-field__native q-placeholder">
```
Notice the long uid used for the label's `for=` and the `input`'s `id` attribute

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Hawkeye64/pen/oNgrJEM

**To Reproduce**
1. Open dev tools on the QInput of the provided codepen
4. See issue

**Expected behavior**
If an `id="email"` is provided by user, then quasar uses this id instead of generating a uid.

**Comment by hawkeye64** [comment]
I see the QField mixin has a `for` property. You can close this if that would be the right way to use this, but it's very hidden to the casual user.

**Comment by pdanpdan** [comment]
QField is a label and everything is very complex - in order to put an id on the native form element you must use the for of the label.
