### ISSUE TITLE
q-time doesn't behave well when combined with date model

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#6279]
When dragging minutes arrow in `<q-time />` which has `mask="YYYY-MM-DD HH:mm"` the element emits undefined value. When just selecting a minute, that works perfectly fine.

You can view that in the documentation (open codepen) by selecting the date and then by starting dragging arrows in `<q-time />` element.
https://quasar.dev/vue-components/time#Example--QDate-and-QTime-with-QInput

Many thanks!

**Comment by metalsadman** [comment]
@pikil https://codepen.io/metalsadman/pen/mdyNERm?editable=true&editors=101

**Comment by hawkeye64** [comment]
@metalsadman That never popped up the QDate for me:
![image](https://user-images.githubusercontent.com/10262924/73692792-41b87a80-4692-11ea-9208-6dc846192b3b.png)

**Comment by metalsadman** [comment]
what browser and os are you using? i could swear it was working in the office, but yeah not working in my home win 10 pc on chrome.

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.9.0.

**Comment by pikil** [comment]
Great, thank you guys!
