### ISSUE TITLE
Animate ['all'] option does not work.

### ISSUE THREAD

**Issue by megastary** [quasarframework/quasar#6280]
**Describe the bug**
Cannot add animations using 'all' option.

**To Reproduce**
1. Create fresh Quasar project using quasar CLI
2. Go to quasar.conf.js
3. Change animate option to:
`animations: ['all']`
4. Run `quasar dev`
5. Get: 

> 
> ERROR  Failed to compile with 1 errors                                                                                                                                                        17:54:48
> This dependency was not found:
> 
> * @quasar/extras/animate/all.css in ./.quasar/client-entry.js
> 
> To install it, you can run: npm install --save @quasar/extras/animate/all.css

**Expected behavior**
Build and launch quasar app.

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.14.1.
Yarn: v1.21.1
Electron: 7.1.10

**Additional context**
Running `npm install --save @quasar/extras/animate/all.css` yields following result:
`npm ERR! code ENOLOCAL
npm ERR! Could not install from "@quasar\extras\animate\all.css" as it does not contain a package.json file. `

Running `yarn add @quasar/extras/animate/all.css` yields following result:
 `error An unexpected error occurred: "https://registry.yarnpkg.com/@quasar%2fextras/animate/all.css: Request \"https://registry.yarnpkg.com/@quasar%2fextras/animate/all.css\" returned a 405".`

**Comment by megastary** [comment]
Never mind. As always I had to submit an issue to instantly realize what I did wrong. 
Of course I have to remove brackets and set option to:
`animations: 'all',`

**Comment by moxuanyuan** [comment]
I have the same  problem

**Comment by rstoenescu** [comment]
@moxuanyuan Maybe if you can read the comment right above you :)

**Comment by valjar** [comment]
> Never mind. As always I had to submit an issue to instantly realize what I did wrong.
> Of course I have to remove brackets and set option to:
> `animations: 'all',`

Good thing you did that @megastary! :D Almost went crazy for a moment, then I found this answer :D

**Comment by megastary** [comment]
I'm glad I could be of help. 👍
