### ISSUE TITLE
QTable visible-columns not working on some columns

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#6282]
I tried to fork the example visible columns from the docs. Then I tried to create a toggle for all the columns. 
Then I noticed the description(Dessert) toggle is not working. 

See codepen:
https://codepen.io/ajcastro/pen/YzPmdGe

Here is another codepen from my project. Here you can see that the last column Action is the only one working for visible-coumns.
https://codepen.io/ajcastro/pen/GRgVzZV

**Comment by rstoenescu** [comment]
Hi, The column that you are talking about is marked as `required: true` so its visibility cannot be toggled.

**Comment by ajcastro** [comment]
Ah I see. Thanks!

**Comment by Menighin** [comment]
@rstoenescu Just ran into the same "issue" haha
Maybe this is not clear enough in the docs. Made a PR, hope it helps: #6299

**Comment by rstoenescu** [comment]
@Menighin Merged. Thanks for taking time for this <3
