### ISSUE TITLE
MDI-v4 not showing correct icon with QInput

### ISSUE THREAD

**Issue by rafaelmaiach** [quasarframework/quasar#6284]
**Describe the bug**
When setting in quasar.config.js in the extras field the "mdi-v4" icons and on framework.iconSet the "svg-mdi-v4", the calendar in QInput isn't working, it shows a "event" string instead of the icon.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

Link to codesandbox: https://codesandbox.io/s/quasar-mdi-v4-qinput-bug-9g4kw

**To Reproduce**
1. Check the input on the main screen
2. It has an event string instead of the calendar icon

**Expected behavior**
Show the calendar icon

**Screenshots**
![image](https://user-images.githubusercontent.com/13542718/73703838-13f22680-46d0-11ea-9e38-99efe3a18c54.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: 12.14.1
NPM: 6.13.4
Yarn:
Browsers: Chrome 79.0.3945.130
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

1. The Quasar Icon Set refers to Quasar's own inner icons, not to the devland ones.
2. Your usage corresponds to a webfont icon, not an svg icon. [Example with svg icons](https://quasar.dev/vue-components/icon#Svg-usage)
3. Even if using a webfont icon in your case, then "event" is a not an MDI-v4 icon. Needs the "mdi-" prefix.

More info on how to use MDI-v4 svg icons: https://quasar.dev/vue-components/icon#SVG-MDI-(Material-Design-Icons
