### ISSUE TITLE
QVirtualSroll scrollTo() doesn't work predictably

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#6289]
When using `scrollTo()` in `mounted`, even if items are ready and even if using `nextTick`, sometimes it will not scroll to the specified position, it will stay at 0.

Sometimes items will not even be rendered, and will only render when manually scrolling, probably because internally it thinks it's at position X, but it's not, so it's not rendering the first items.

Codepen example, should scroll to position 50, but if you refresh the page the list will stay at scroll position 0
https://codepen.io/jeancaffou/pen/MWYPqQY

**Comment by pdanpdan** [comment]
Hello. Sorry, I cannot reproduce it. Please fill the details required to reproduce (os, browser, mode, version, ...) that are already requested in the issue template.

**Comment by jeancaffou** [comment]
@pdanpdan Open codepen link, if it's on 50, click refresh a few times. I can record screen. Happens on chrome and firefox, and not every time...

**Comment by jeancaffou** [comment]
@pdanpdan  https://drive.google.com/file/d/1oro-Xiv0YvkgJ9jDKJASbUkHQUS-BGXR/view

**Comment by jeancaffou** [comment]
@pdanpdan https://drive.google.com/file/d/1FQZ_jtVvYXoUbvrrHNY9Tycy5j2hoZhu/view

**Comment by pdanpdan** [comment]
I'll check - it only happens in firefox

**Comment by jeancaffou** [comment]
For me it's much more buggy in Chrome than Firefox.

**Comment by pdanpdan** [comment]
You have scroll restoration in browser.
Hide the list for a time at loading so that the browser does not try to restore the scroll.
https://codepen.io/pdanpdan/pen/wvawooa
