### ISSUE TITLE
Support for Electron 8 

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#6290]
Would be greatly appreciated.  There seem to be numerous bug fixes and performance enhancements in the communication between render and main threads.

**Comment by pdanpdan** [comment]
It looks to me like it's working. Do you have some special request?

**Comment by rfox12** [comment]
@pdanpdan Maybe I just need a little education... I noticed my Quasar was using Electron 7.1.*

How do I upgrade to Electron 8?  Simply update my package.json?  Historically I've been reluctant to change anything that the quasar cli has installed.  I'll make the change and report back if I run into any issues.

Pkg quasar........ v1.8.5
Pkg @quasar/app... v1.5.2

**Comment by pdanpdan** [comment]
Just set the desired version in package.json and do a yarn.
