### ISSUE TITLE
quasar.dev: clicking on an item in the TOC does not update url

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#6294]
**Describe the bug**
Using the 'table of content' links to navigate inside a doc page scrolls to the corresponding anchor, however the url stays at the previous value (main page url or wrong anchor link) and does not reflect the change to the new anchor.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/introduction-to-quasar#What-is-Quasar%3F

**To Reproduce**
1. Go to [`https://quasar.dev/introduction-to-quasar#What-is-Quasar%3F`](https://quasar.dev/introduction-to-quasar#What-is-Quasar%3F)
2. Click on a different item in the TOC
3. Check that the url in the address bar is not reflecting the change to the new anchor

**Expected behavior**
The url should sync with the clicked item in the TOC.

**Screenshots**
![anchor-issue](https://user-images.githubusercontent.com/48388358/73830761-44dc7380-4816-11ea-8d3b-3601bf99d544.png)

**Additional context**
I suggest extracting the scroll functionality out of Layout.vue and putting it in a separate module (ex: `utils/scroll.js`) , then importing and calling needed scroll function from the router `scrollBehavior()` function, and instead of having `@click="scrollTo(toc.id)"` we can use ```:to="`#${toc.id}`"```
in Layout.vue.

Working example:
https://quasarmarkdown.netlify.com/demo
https://github.com/ejez/quasarmarkdown/blob/master/src/router/index.js#L25

**Comment by pdanpdan** [comment]
This will be fixed when the docs for the next version (v1.9.0) will be published.
