### ISSUE TITLE
QAjaxBar: whitelist of domains to watch

### ISSUE THREAD

**Issue by maiolica** [quasarframework/quasar#6303]
**Is your feature request related to a problem? Please describe.**
QAjaxBar is super useful as it watch every XHR call, the downside is that it also catches calls from external libraries (ex: analytics), showing the loading bar when the library fires a call. 

**Describe the solution you'd like**
A `domains-whitelist` prop maybe, to have a list of domains to watch.

**Describe alternatives you've considered**
I could just setup and use the the LoadingBar plugin, I know, I've put ```LoadingBar.start();```, ```LoadingBar.start();``` in axios interceptors and ```LoadingBar.increment(amount)``` in `onDownloadProgress` axios event, but the result is not the same, QAjaxBar is more accurate in showing loading feedback.
I am aware of the `skip-hijack` prop, not sure how it could help me.

**Comment by xiaoer3301** [comment]
Same needs!

**Comment by ibrainventures** [comment]
That would be really great.

Actually i am handling "hidden" requests with the browser native `fetch('url').then` which has no start / stop effect on the axios hijack, but it would be much better to have this (predefinied) (option) for the axios service ..

(setting up a please please "dear quasar team make this possible" face / look)

**Comment by rstoenescu** [comment]
No promises this will get in soon, but it definitely will.

**Comment by rstoenescu** [comment]
Will be available through new prop (hijack-filter Function) in Quasar v2.4.5
