### ISSUE TITLE
Q-Select typing text doesn't work with keyRepeat and option-label as function

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#6305]
**Describe the bug**
When typing in a **Q-Select** if I use :option-label function there's a bug in the __onTargetKeydown and __getOptionLabel that return **'undefined'**

**Codepen**
https://codepen.io/dariodepaolis/pen/VwLYYNM

Try to press G for Google, multiple times and look at the error in console
This is the forked example from Quasar Guide

**Expected behavior**
The keyRepeat behavior need to cycle correctly

**Comment by pdanpdan** [comment]
Thanks for reporting, we'll fix the example :)
But the error is in the function in the example, not in framework:
```html
:option-value="opt => Object(opt) === opt && 'id' in opt ? opt.id : null"
:option-label="opt => Object(opt) === opt && 'desc' in opt ? opt.desc : '- Null -'"
:option-disable="opt => Object(opt) === opt ? opt.inactive === true : true"
```

**Comment by dariodepaolis** [comment]
Thank you for clarification.
