### ISSUE TITLE
qtime minutes set to null on hour input

### ISSUE THREAD

**Issue by SMen1** [quasarframework/quasar#6306]
Regarding QTime - it was suggested to me on discord that I should raise an issue.

On all examples on the QTime documentation page the hour shows with the v-model  'hour line', but when selecting a different hour you lose the 'minute line' for the default minutes. 

The user is left with a blank face and minutes are set to null.
There is no @input  event emitted on hours - only minutes.

There are lots of reasons for not setting the minute to null:  user friendliness, pre-setting of defaults (when most selections might be on the hour for example - it does not require additional clicks, or a new  user wondering what to click).

So I think this must be quite likely to be unintended so raising this as an issue.

**Comment by rstoenescu** [comment]
Hi,

This is the intended behavior. There are lots of reasons, including playing nicely with a QInput.
If the user should only select an hour, then a QSelect would do the job. No need for a full QTime.

**Comment by SMen1** [comment]
HI

But the user does not see the minute hand?  This is the expected behaviour with Android certainly.

Why not have the minute hand display even with 00. I don't understand this or why it would not work with QInput.

It is not that they should only select an hour, that is not what I meant. Can I request a minute hand instead of blank face or null as an expected behaviour?

Many thanks

**Comment by rstoenescu** [comment]
Reopening (so that I don't forget about it) for further explanations in a few days (currently extremely busy with v1.9)

**Comment by SMen1** [comment]
Yes, I understand, many thanks. 

Maybe after v1.9. 

It's giving me a headache with users (further down the line), so hopefully!

**Comment by flowt-au** [comment]
Just to add to this. If my meeting time starts at (say) 19:15 and I want to shift it to 20:15, I would expect to be able to just click the hour and leave the minutes as they are.  But instead I need to click 20, then click 15 again.

It is not a big deal but maybe an option to say "leave the minutes when changing the hour" could be handy.

Thanks! :-)

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v2.2.4
