### ISSUE TITLE
q-chat-message component should allow us to render the text div element as different html element then the default one

### ISSUE THREAD

**Issue by wasifsn** [quasarframework/quasar#6311]
**Is your feature request related to a problem? Please describe.**

I was using Quasar Framework for making a chat app and found that the q-chat-message component  text always render as a div when we pass an array to :text prop

**Describe the solution you'd like**

if we could either render the text div as anchor tag or other native html element would be great as many time we would pass a geolocation url link that needs to be put in the href attribute so we would have the freedom to toggle the rendered element on the basis of certain parameters.

most of the vue libraries offer this functionality

**Comment by pdanpdan** [comment]
Please create a codepen showing what you cannot do.

**Comment by rstoenescu** [comment]
@wasifsn but you can: https://codepen.io/rstoenescu/pen/jOPEVrN?editable=true&editors=101
