### ISSUE TITLE
Ctrl+MouseLeftClick on q-btn, which acts as router-link

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#6315]
That would be great if `<q-btn to="XXX" />` reacts in a common way for links on mouse clicks while holding keys. For example, Ctrl+MouseLeftClick or Cmd+MouseLeftClick tells the browser to open a new tab.

Many thanks!

**Comment by rstoenescu** [comment]
Thanks for suggesting this.
Will be available in upcoming v1.9.0

**Comment by pikil** [comment]
Many thanks!
