### ISSUE TITLE
QSelect doesn't work with objects that do not contain a value prop

### ISSUE THREAD

**Issue by alexeigs** [quasarframework/quasar#6319]
**Describe the bug**
Upgrading to 1.8... some `q-select` have stopped working: all those who take objects as options and do not contain a property `value`. Even though I do not care about that `value` specifically and the v-model just takes/passes the whole object, it doesn't pass any new selection if this object does not contain a `value` property.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/lexixon/pen/ExjaoGP

So far I couldn't find anything in the documentation that explained this change as a conscious one.

**Comment by pdanpdan** [comment]
Hello. Thanks for reporting it - it will be fixed in v1.9.0
