### ISSUE TITLE
q-popup-edit buttons should have same props as regular q-btn buttons

### ISSUE THREAD

**Issue by mickey58github** [quasarframework/quasar#6325]
**Is your feature request related to a problem? Please describe.**
q-popup-edit allows to specify two buttons through its buttons prop. However, those buttons do not have the same props as regular Quasar q-btns and therefore usually have a different style compared with other buttons in the Quasar app, making the app look inconsistent. Especially, props like no-caps, color, or glossy style are not supported for those buttons.

**Describe the solution you'd like**
Add support for props like no-caps, color, and glossy for those buttons.

**Describe alternatives you've considered**
Not aware of what the alternative is, except not to use those buttons.

**Additional context**

**Comment by pdanpdan** [comment]
Hello. You can use any kind if button in slot, you have examples in docs: https://quasar.dev/vue-components/popup-edit#Example--Default-scoped-slot-parameters

**Comment by mickey58github** [comment]
Thanks, @pdapdan. I had already taken a look at the default-scoped-slot sample, trying to adapt it to my use case. The difficulty I have with using it comes from the fact  that my q-popup-edit works on 3 q-input-fields within the q-popup-edit, not just one. I have that working perfectly wiht the pre-defined buttons and some other methods that are called upon q-popup-edit events @before-show (to save old values for the 3 fields), @cancel (to restore all 3 fields to the old values), and @save. 

I could not get rid of the custom buttons and use regular q-btns. The sample under the doc link you provided inserts the v-slot:after into the (single) q-input field - not sure how to adapt it to 3 q-input fields - maybe my fault, since my experience with v-slots is limited.

**Comment by pdanpdan** [comment]
Just put the html for what you want to be shown in QPopupEdit: https://codepen.io/pdanpdan/pen/poJJbmp?editors=1010

**Comment by mickey58github** [comment]
@pdanpdan - I tried it, but failed: When I wrapped the 3 q-inputs into a div, and put the v-slot:after before the end of that div, after the last q-input, I got an error message from Vue. Don't remember the exact message, it said something like the v-slot needs to be a direct child of something else. 

So I could not figure out how to exactly attach the v-slot correctly.

**Comment by pdanpdan** [comment]
You should not use v-slot:after - check the example I made for you

**Comment by mickey58github** [comment]
Thanks - now I realize you did not use v-slot:after. That makes it easier.

One more question (thanks for your patience): Is it possible to add own custom code in those 2 functions that are named cancel and set - how would that be done?

**Comment by pdanpdan** [comment]
No. One is saving if all is good and the other is reverting if not.

**Comment by mickey58github** [comment]
Sorry, I'm still not getting it - where do I put the code that saves the input (e.g. to backend) or reverts the input (e.g. from backend or store)?

**Comment by pdanpdan** [comment]
Please head to the discord channel (https://chat.quasar.dev/) or to the forum (https://forum.quasar.dev/) for help
