### ISSUE TITLE
QSelect - displacement "options" in right col

### ISSUE THREAD

**Issue by Teodorko** [quasarframework/quasar#6328]
Pkg quasar........ v1.8.5
Pkg @quasar/app... v1.5.3

Chrome 79.0.3945.79

https://codepen.io/teodorko/pen/YzXXXoJ

![image](https://user-images.githubusercontent.com/20430124/74141929-e42fab00-4c08-11ea-9245-df11e2f1af6b.png)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.2.
Thanks for reporting!
