### ISSUE TITLE
QCheckbox on IE11: Always shows icon for indeterminate state

### ISSUE THREAD

**Issue by MartinManev** [quasarframework/quasar#6329]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required)**
See official docs https://quasar.dev/vue-components/checkbox

**To Reproduce**

**Expected behavior**

**Screenshots**
![qcheckbox_ie_bug](https://user-images.githubusercontent.com/16416643/74150198-142f7c00-4c12-11ea-8811-d29440462548.png)

**Platform (please complete the following information):**
OS: Windows
Node: -
NPM: -
Yarn: -
Browsers: IE11 only
iOS: -
Android: -
Electron: -

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fix will be available in "quasar" v1.9.0.
