### ISSUE TITLE
QSelect - fill-input is not reactive

### ISSUE THREAD

**Issue by multicolaure** [quasarframework/quasar#6336]
## Steps to reproduce

A fiddle to reproduce: https://jsfiddle.net/9zng1ax3/1/

- At start, fill-input is `true`
- Change the value in the select and unfocus. The selected value is displayed in the select when the menu is closed. -> **OK**
- Untick the checkbox `Fill input`, to change `fill-input` to `false`. The selected value is still displayed in the select. -> **I expected the value to disappear**.

By comparison, `hide-selected` reactively hide / display the selected value.

## Workaround

I found out that when you force the selected value to be repaint, it hides / displays the selected value as expected. 

Steps: 
- At start, fill-input is `true`
- Change the value in the select and unfocus. The selected value is displayed in the select when the menu is closed. 
- Untick the checkbox `Fill input`, to change `fill-input` to `false`. The selected value is still displayed in the select. 
-  Change the value in the select again and unfocus. Now the selected value is not displayed. -> **Ok**. Also works if you reselect the same value.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.0
