### ISSUE TITLE
[Feature Request] Allow manual dependency installation in Electron build process

### ISSUE THREAD

**Issue by hybridmuse** [quasarframework/quasar#6345]
### Issue
Building electron app fails for lerna packages because the symlinked dependencies can't be resolved, and the install command is [hardcoded](https://github.com/quasarframework/quasar/blob/cf9184b7d40491ff4c6d7319cda44e978da572c0/app/lib/electron/index.js#L94) inside quasar:

```js
spawn(
  nodePackager,
  [ 'install', '--production' ].concat(cfg.electron.unPackagedInstallParams),
  { cwd: cfg.build.distDir },
  code => {
    if (code) {
      warn(`⚠️  [FAIL] ${nodePackager} failed installing dependencies`)
      process.exit(1)
    }
    resolve()
  }
)
```

### Workaround (feature request)
The simplest workaround for this would be to allow the build command `quasar build -m electron` to be optionally used in 2 steps (e.g. `quasar build -m electron --pre-install` and `quasar build -m electron --post-install`), allowing to manually handle dependency installation with `lerna bootstrap` in between.

------
Detailed issue:
### To Reproduce
1. Setup lerna monorepo;
2. Create 2 (hypothetical) packages: @pkg/app, @pkg/utils;
3. Add @pkg/utils to @pkg/app dependencies (create symlink through `lerna bootstrap`);
4. Set @pkg/app to electron mode (at this point `quasar dev -m electron` works just fine);
5. Attempt to build @pkg/app via `quasar build -m electron` : 
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/[@pkg/utils] - Not found
[...]
app:spawn Command "npm" failed with exit code: 1
app:electron ⚠️  [FAIL] npm failed installing dependencies
```
The local package isn't recognized and npm wrongly attempts to find it in the online registry.

### Expected behavior
Electron app should build successfully from lerna package, with symlinked node_modules from src directory preserved.

### Additional context
* Figured quasar maintainers are already familiar with lerna, as it's being used in [quasarframework/quasar-testing](https://github.com/quasarframework/quasar-testing).

* Found [this somewhat related question](https://forum.quasar-framework.org/topic/4590/electron-build-with-local-dependency), which has been left unanswered.

**Comment by dbjorge** [comment]
https://github.com/yarnpkg/yarn/issues/7902

**Comment by hybridmuse** [comment]
@dbjorge that's not it, none of the package names start with a digit. It really is an issue of lost symlinks when the electron build process installs dependencies in dist/electron/UnPackaged.

**Comment by hybridmuse** [comment]
Closed as this is an ([issue with electron-packager](https://github.com/electron/electron-packager/issues/738), not with quasar.

**Comment by hybridmuse** [comment]
After looking deeper, quasar is actually responsible for dependency installation [here](https://github.com/quasarframework/quasar/blob/cf9184b7d40491ff4c6d7319cda44e978da572c0/app/lib/electron/index.js#L93), so this isn't an issue with the bundler. Reopening this with workaround as feature request as this doesn't really qualify as a bug.

**Comment by rstoenescu** [comment]
This is a non-issue. Install the deps manually before running "quasar dev" or "quasar build" then Quasar App CLI won't have to. Reopen if I missed anything.

**Comment by hybridmuse** [comment]
Thanks for getting back.
> Install the deps manually [...] then Quasar App CLI won't have to.

Even with the depencencies pre-installed manually, `quasar build -m electron` overwrites them, running `npm install --production` inside dist/electron/UnPackaged.

**Comment by IUnknown68** [comment]
Hello @rstoenescu, I'm having the exact same problem in the exact same setup. The suggestion to manually install the deps does not solve the problem, as @hybridmuse already pointed out: Since `quasar build -m electron` re-creates the `UnPackaged`-folder, the manual deps-installation is useless. This is a real bummer - any chance to reopen this issue?
Cheers!

**Comment by yacinehmito** [comment]
Hello @rstoenescu. We are hitting the same issue. We'd like to customize how installation is done. At the moment quasar auto-detects pnpm and the run of pnpm install --prod thrashes the node_modules for the whole monorepo.
