### ISSUE TITLE
Invalid sass selector in 1.9.0

### ISSUE THREAD

**Issue by Eldar-X** [quasarframework/quasar#6347]
Hello in latest release 1.9 during compilation i have warning
WARNING on line 1915, column 3 of ../../node_modules/quasar/dist/quasar.sass: 
This selector doesn't have any properties and won't be rendered.

**Comment by pdanpdan** [comment]
Hello.

What OS, what command you run to build/start, any scripts that get invoked from package.json, your quasar.conf?

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.1
