### ISSUE TITLE
QUploader thumbs slows down a webpage, when working with big images, because of base64 encoding

### ISSUE THREAD

**Issue by Sonit90** [quasarframework/quasar#6348]
When you load big amount of photos (~20) into QUploader which have big resolution (6000x4000), the browser slows down a lot, because images are encoded to base64

Codepen: https://codepen.io/sonit90/pen/wvaKobZ

1. Go to https://codepen.io/sonit90/pen/wvaKobZ
2. Select 20 high res photos
3. Try to scroll thumbs area

Problem could be solver, by window.URL.createObjectURL(image), instead of base64 encoding

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.9.1.
