### ISSUE TITLE
QFile clearable doesn't work

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#6351]
**Describe the bug**
QFile component clearable prop doesn't work correctly.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pen/?&editable=true&editors=101
see console for error

![Screenshot from 2020-02-12 12-38-54](https://user-images.githubusercontent.com/11172818/74320007-20901200-4d95-11ea-8d10-c75f0956e849.png)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.1
