### ISSUE TITLE
Reset model after form validation cause validation error

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#6353]
**Describe the bug**
Reset model after form validation cause validation error

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/heartbeatlv-the-bashful/pen/RwPWpmK

**To Reproduce**
1. Fill the two input
2. Press ENTER

**Expected behavior**
I expect that after resetting the model and then the form doesn't cause the validation error

**Comment by rstoenescu** [comment]
Fixed in v1.9.1.
