### ISSUE TITLE
arrows props at QPagination

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6358]
**Is your feature request related to a problem? Please describe.**
Add icon props for left and right arrows at `QPagination`

**Describe the solution you'd like**
Like `prev-icon` and `next-icon` at `QCarousel`

**Comment by rstoenescu** [comment]
@hawkeye64 We need a `icon-first`, `icon-prev`, `icon-next`, `icon-last` props to be hooked into existing `icons` computed prop.

**Comment by hawkeye64** [comment]
Hope you mean v1.9.4 @rstoenescu :)

**Comment by rstoenescu** [comment]
Yep. Released 1.9.3 already. Couldn't postpone it more. :)

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.9.4.
