### ISSUE TITLE
[0.14] q-button might be better than q-btn

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#636]
The new 0.14 demo and docs are very exciting~! Only one thing: all other components are using full names but `q-btn` uses `btn` rather than `button`. This short name might not be necessary.

**Comment by smolinari** [comment]
I believe the short name was used to stay familiar with [Bootstrap's naming convention for the button class](https://v4-alpha.getbootstrap.com/components/buttons/#button-tags). A number of things follow Boostrap's naming conventions in Quasar. I'd say, i
It's a matter of keeping things familiar for front-end devs, which helps make using Quasar as intuitive as possible. 

Razvan will probably chime in to tell you the real story, if mine should be false. 😄 

Scott

**Comment by rstoenescu** [comment]
In addition to what Scott said, it also helps the developer by having to type less for such a massively used component. This is something that Quasar often pursues: simplified and crystal clear templates in apps, less typing.

I hope you don't mind, but I will close this.
Looking forward to more suggestions though!

-Razvan
