### ISSUE TITLE
Backdrop while QFab actions are expanded

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6361]
**Is your feature request related to a problem? Please describe.**
Activate backdrop when we open QFab actions.
To use external labels looks a little bit... monstrous, if there are more than 3-4 actions.
But if we use external labels - it's hard to concentrate view on its, they're going to be losed

**Describe the solution you'd like**
Using backdrop will resolve this problem, won't it?

**Comment by pdanpdan** [comment]
A FAB does not work with backdrop, and the recommended max number of actions is 5 I think.
And if the external labels are not good for your case do not use them, you can use the internal ones or no label.
And you can customize how the external labels look.

**Comment by GordonBlahut** [comment]
@pdanpdan 

Material design example seems to show a backdrop for FAB actions. https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1579302979877%2Fassets%2F1CMssxsx--CjFfG_JIw35cPRhxJldwRWM%2Ffab-toolbar-speeddial-v03.mp4

**Comment by matro-skin** [comment]
@GordonBlahut that's exactly what I mean, thanks.
Hope it will be realized soon.
