### ISSUE TITLE
Hide button label on xs resolution

### ISSUE THREAD

**Issue by jonalxh** [quasarframework/quasar#6367]
I've been looking the docs and was unable to find an implementation to hide the button label when it is in mobile resolution or X resolution, It would be amazing if you consider it.

Thanks.

**Comment by pdanpdan** [comment]
`<q-btn icon="email" :label="$q.screen.gt.xs ? 'Email' : void 0" />`

**Comment by jonalxh** [comment]
Wow, thanks for quick response, please consider adding it to the documentation.

Thanks a lot.

**Comment by hawkeye64** [comment]
@jonalxh You may also be interested in these classes: https://quasar.dev/style/body-classes
In particular, the `screen-*` ones (like `screen-xs`)

**Comment by jonalxh** [comment]
@hawkeye Very useful, thank you.

**Comment by Raimigu** [comment]
@pdanpdan tnx
