### ISSUE TITLE
Is there no `progress-button` in 0.14?

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar#637]
The `progress-button` component in 0.13 (http://quasar-framework.org/components/progress-button.html) (the one with the very useful `percentage` prop) is absent in 0.14 docs. The `q-btn` with `progress` in 0.14 does not seem to have `percentage`.

**Comment by smolinari** [comment]
That is correct. The progress button is only for indeterminate progress. Determinate progress needs to be added. 

Scott

**Comment by rstoenescu** [comment]
Will add that back as QPercentageButton in a few days.

**Comment by rstoenescu** [comment]
Check "Handling deterministic progress" section in Button docs.
