### ISSUE TITLE
QTable Examples is not working

### ISSUE THREAD

**Issue by pratik227** [quasarframework/quasar#6370]
Quasar Documentation QTable page Examples is not working.

**Screenshot**

![screenshot-quasar dev-2020 02 14-17_33_37](https://user-images.githubusercontent.com/34883558/74530480-2aaa4000-4f50-11ea-84b8-5680731ef171.png)

![screenshot-quasar dev-2020 02 14-17_34_16](https://user-images.githubusercontent.com/34883558/74530506-3dbd1000-4f50-11ea-9e6d-a4c2e3a366e8.png)

Google Chrome - 
Version 68.0.3440.84 (Official Build) (64-bit)

System Info - 

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"

**Comment by diadal** [comment]
facing same issue thinking it was my code `QTable` not working upgrade to 1.9.1

**Comment by pdanpdan** [comment]
It is working. Can you check the console for errors?

**Comment by rstoenescu** [comment]
Does this work with Chrome v79 or v80 for you?

**Comment by diadal** [comment]
no error in console my chrome Version 80.0.3987.100 (Official Build) (64-bit)
<img width="718" alt="Screenshot 2020-02-14 at 13 48 48" src="https://user-images.githubusercontent.com/19895516/74533009-d774c500-4f30-11ea-98ed-eb779a539b56.png">
<img width="721" alt="Screenshot 2020-02-14 at 13 48 29" src="https://user-images.githubusercontent.com/19895516/74533023-e196c380-4f30-11ea-9d40-1a444016ffe5.png">
all working fine on 1.8.5 before upgrading to 1.9.1

**Comment by diadal** [comment]
`q-markup-table` working but `q-table` not working

**Comment by pratik227** [comment]
It as also not working for Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.2.
Thanks for reporting!

**Comment by diadal** [comment]
how soon this or is it possible to downgrade because this slow down my project

**Comment by rstoenescu** [comment]
Later today, so no worries.
