### ISSUE TITLE
QAlert handler not firing if no animation defined

### ISSUE THREAD

**Issue by spectrolite** [quasarframework/quasar#638]
### Software version

Quasar: 0.14

### What did you get as the error?
handler function doesn't get called when clicking the action button of a q-alert (no errors, just not firing)

### What were you expecting?
handler function to be called

### What steps did you take, to get the error?
insert a q-alert tag in the HTML without specifying any enter/leave prop
(issue raised by nicco91 and discussed yesterday on gitter at various moments in the afternoon and evening, with code samples)

### Temporary solution:
adding an animation for the "leave" prop makes it correctly call the handler on click (after the animation has ended, which introduces an unneeded delay btw)

**Comment by rstoenescu** [comment]
Available in latest v0.14.
npm update quasar-framework for it.

Thanks for reporting!
