### ISSUE TITLE
[Bug] Notify - onDismiss is always triggered before action handlers

### ISSUE THREAD

**Issue by the-collaborator** [quasarframework/quasar#6380]
**Describe the bug**
Action handlers in Notify are triggered after onDismiss is triggered. The behavior was changed in Quasar v1.9.0: [github diff](https://github.com/quasarframework/quasar/commit/07090ac4905a8c7da59d06c9ebdd7369908fde49#diff-0706ac6170c5af0352828f8bfd1c11cfL101)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/the-collaborator/pen/ZEGWbdL

**To Reproduce**
1. Go to https://codepen.io/the-collaborator/pen/ZEGWbdL
2. Click on "Delete Me"
3. Check in console order of logs ("deleted" is logged before "cancelled").
4. Change the quasar version to 1.8.2 in codepen settings.
5. Click on "Delete Me".
6. Check in console order of logs ("deleted" is not visible, "cancelled" is logged).

**Expected behavior**
Action handlers are triggered before notif.meta.close() which triggers onDismiss(). This allows actions to influence the behavior defined in onDismiss().
You might change quasar version to one prior to v1.9.0 to check the expected behavior.

**Screenshots**
n/a

**Platform (please complete the following information):**
OS: Windows 10 Pro 64-bit
Browsers: Chrome 80.0.3987.106

**Additional context**
To improve UX on delete action on an item I was showing notification using Notify with an option to rollback. I figured out that it was easier to hide the item and remove it in onDismiss event, however in 1.9.0 the order was changed and right now onDismiss is executed before action handler so the item is always deleted.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.3.
