### ISSUE TITLE
Google-Analytics Code showing on page 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#6383]
when I change route google-analytics code showing at footer 

<img width="1440" alt="Screenshot 2020-02-15 at 22 21 58" src="https://user-images.githubusercontent.com/19895516/74595493-3bd37980-5042-11ea-964b-43f7b89fdd19.png">

**Platform (please complete the following information):**
OS: Mac 
Node:
NPM:
Yarn:
Browsers: Chrome, Safari
iOS: iPhone XR 
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Hello. For jQuery related problems please refer to a dedicated knowledge resource.
