### ISSUE TITLE
QSelect as dialog doesn't have a submit button for new values on Android

### ISSUE THREAD

**Issue by TomDeSmet** [quasarframework/quasar#6384]
**Describe the bug**
I'm creating an Android app and I'm using QSelect in dialog behavior with filter and new-value options.
It all works well on desktop, but on mobile I'm not able to add new values because there's just no submit button. The Android keyboard automatically has a search button instead of an enter button as the input is used to filter the list. 
But how would I go about adding new values on mobile than? I can't press enter and there's no submit button.
I can't find anything online, seems impossible I'm the first to notice this?
Is there a built-in option I missed or should I add a button with custom functionality?

**Codepen/jsFiddle/Codesandbox (required)**
Can't add a jsFiddle as it's a problem on Android when the app was built.

**Platform (please complete the following information):**
OS: Android 9 Pie

**Comment by pdanpdan** [comment]
Have you tried to press the search/enter/whatever the button shows on the keyboard?

**Comment by TomDeSmet** [comment]
Of course I have :) But it just triggers a search in the select which it already did on input. So nothing changes.

**Comment by pdanpdan** [comment]
Ok, I'll research what if sends on that key. Thanks for reporting.

**Comment by pdanpdan** [comment]
Ok. It's about the android keyboard: when you type something the keyboard enters composition mode (you get the suggestions on the top row of the keyboard). In order to be able to add you need either to type a space after the last letter of select the suggestion in the suggestions bar and then press on the search button on keyboard.

The reason we cannot to anything is that we cannot detect the type of keyboard and only the android one does this :(

**Comment by TomDeSmet** [comment]
To bad, it works as you describe although you have to click away in the black overlay in the background for the dialog to 'submit' the new value. There's no submit button.

For people who come across this issue: I solved it by adding a QButton in the ```before-options``` and ```no-option``` scoped slots that when clicked sets the input value to the input I get from the @filter function and closes the dialog with the ```hidePopup()``` method.

**Comment by cmcleese** [comment]
Do you know how to clear the input field after adding to the model?

Ex:

```js
const selectRef = ref<QSelect>();

const multipleInputModeValue = ref();
// set the value in the temp ref for capture the input value
const filterMultipleAdd: QSelectProps['onFilter'] = (val, update, abortFn) => {
  multipleInputModeValue.value = val;
  // abort immediately to stop loading indicator for displaying indefinitely
  abortFn();
};
// handler for manually adding input values when using multiple
const manualAddHandler = () => {
  selectRef.value?.add(multipleInputModeValue.value);
};
```
Simplification of usage:
```html
<q-select @filter="filterMultipleAdd" ref="selectRef">
    <template v-slot:append>
      <q-btn 
        @click="manualAddHandler()"
       label="add"
      />
    </template>
</q-select>
```

![image](https://github.com/quasarframework/quasar/assets/2061466/dcb067ea-474b-41d8-bc70-8384488c47c3)
