### ISSUE TITLE
QUploder removeFile error

### ISSUE THREAD

**Issue by haasz** [quasarframework/quasar#6387]
**Describe the bug**
An error occurs when calling the removeFile method of Quploader component,  so the file upload cannot be aborted.

**Error message in Firefox**
```
TypeError: "'abort' called on an object that does not implement interface XMLHttpRequest."
```

**Error message in Chrome**
```
TypeError: Illegal invocation
```

**Bad code**
https://github.com/quasarframework/quasar/blob/c7a44157484db01b56f326e4f7e19911c504da8d/ui/src/components/uploader/uploader-xhr-mixin.js#L239

**Correctly**
```js
        file.__abort = () => { xhr.abort() }
```

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
The fix is indeed correct.
Fix will be available in "quasar" v1.9.3.

**Comment by rstoenescu** [comment]
Feel free to PR next time. Helps us speed things up.

**Comment by haasz** [comment]
OK. Thanks!
