### ISSUE TITLE
Problem with parsing colors

### ISSUE THREAD

**Issue by neyasbltb88** [quasarframework/quasar#6388]
This problem occurs when working with rgb color. It also manifests itself in color distortion if you use colors.lighten with rgb color. If you use hex colors, this is not a problem

![Quasar color bug](https://user-images.githubusercontent.com/28704903/74617431-1035b980-513e-11ea-9d38-4c1f4bd7cced.png)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.9.3.

**Comment by KirillKaverin** [comment]
@rstoenescu using the fix, 

> QColors.textToRgb("rgb**a**(255, 159, 64)")

will return `{r: 255, g: 159, b: 64, a: 0}`
with zero Alpha Channel, but should be equals 1 (default alpha channel) or missed from returned object: 

> {r: 255, g: 159, b: 64, a: 1}

or

> {r: 255, g: 159, b: 64}

**Comment by rstoenescu** [comment]
True. Will correct it. Working on a related QColor issue and will include it from there.
