### ISSUE TITLE
Why is .vscode in .gitignore?

### ISSUE THREAD

**Issue by gregveres** [quasarframework/quasar#6389]
**Describe the bug**
Why is the .vscode directory in the .gitignore file? 

I would have expected the contents of this directory to be checked in. VS Code has both a user and a workspace set of configurations. I would have expected the workspace config files to be checked in and shared among people on the team and then certain personal choices could be done in the user's User config for VS Code. 

But with .vscode in the .gitignore file, none of those workspace configurations can be shared among people on the team. 

Yes it is easy for the team to go into the .gitignore file and change the .gitignore, but I would have thought it would make sense to not list it in there in the first place.

**To Reproduce**
create a quasar project and look in the .gitignore file. You will find .vscode listed under the editor settings section.

**Expected behavior**
I don't know how the other editors work, but given how VSCode already splits things between personal and workspace, I would have expected the workspace to be checked in with the project.

**Platform (please complete the following information):**
OS: Windows 10
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
The .vscode folder has personal preferences. Not everybody uses VSCode, and not with the same settings. But as you said just remove if from .gitignore if it fits your case better.

**Comment by rstoenescu** [comment]
@gregveres good point. removed it from .gitignore.
