### ISSUE TITLE
QColor - cannot enter a value in input box

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#6390]
In the QColor input box at the top (where you can enter your own hex value), whenever I try to type a value into the box, it will remove the input and clear the value altogether.

Also:

https://quasar.dev/vue-components/color-picker#With-QInput
When using it with a separate QInput, if you start trying in the QInput INSIDE the QColor dialog, the outer QInput will result in [object InputEvent]

![image](https://user-images.githubusercontent.com/13761766/74622532-50745680-5195-11ea-8f5f-b821d38b060c.png)

**Comment by rstoenescu** [comment]
Hi,

What browser are you using, cause I cannot reproduce.

**Comment by nicholaszuccarelli** [comment]
Hi. This was on Chrome for Windows 10.

**Comment by rstoenescu** [comment]
What chrome version, pls?

**Comment by nicholaszuccarelli** [comment]
Chrome 79.0.3945.130

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.3.
