### ISSUE TITLE
QTable fixed headers and footer

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#6396]
**Is your feature request related to a problem? Please describe.**
Sticky headers css is refused by the table. Other css is applied with no problem. The below does not work, changing the height to see an effect results with nothing. Also virtual scrolling works down to a certain record and afterwards I can scroll but no data is visible.
```
<q-table
   class="my-sticky-virtscroll-table"
   separator="cell"
   :data="data"
   :columns="columns"
   no-data-label="No data to show"
   virtual-scroll
   :pagination.sync="pagination"
   :rows-per-page-options="[0]"     
   :virtual-scroll-sticky-size-start="48"     
   hide-bottom/>
</q-table>

<style lang="sass">
.my-sticky-virtscroll-table
  /* height or max-height is important */
  height: 100px

  .q-table__top,
  .q-table__bottom,
  thead tr:first-child th /* bg color is important for th; just specify one */
    background-color: #fff

  thead tr th
    position: sticky
    z-index: 1
  /* this will be the loading indicator */
  thead tr:last-child th
    /* height of all previous header rows */
    top: 48px
  thead tr:first-child th
    top: 0
</style>

data () {
  return {
    pagination: {
      rowsPerPage: 0
    },
```

If I do the following, the table size is affected, even the virtual scroll works but the sticky headers are obviously not working.
```
<q-table
        class="tableCss"

.tableCss {
    height: 80vh
  }

```
Regarding the footer: the footer only has a total records, there is no way to add sum/count that will be linked to a certain column/header.

**Describe the solution you'd like**
I want to be able to have sticky headers and a sticky footer.

**Describe alternatives you've considered**
Add a "final record" that will include the totals, that mean more sticky css that didn't work in the first place (see above, regarding sticky headers).

**Comment by pdanpdan** [comment]
Please put the code in a codepen and make sure it works, so we can understand what you mean.
Thank you.

**Comment by Amosss** [comment]
Thanks for replying but I'm not sure what do you mean by 
> and make sure it works

Regarding the sticky headers: It's not working, that's the problem... (I will try to make a codepen though)
Regarding the sticky footer: this feature does not exist at all so not sure how to make it work, thus the feature request

**Comment by pdanpdan** [comment]
All sticky something can only be done using CSS.
Here https://github.com/quasarframework/quasar/blob/42bab27d1cb0cddbd91c47a69571358ab75b6a2b/ui/dev/src/pages/components/virtual-scroll-5.vue#L76 you can see an example using both header and footer.

For the CSS, this must be adapted to your use case. Please make a codepen and seek more help on the discord channel (https://chat.quasar.dev/) or forum (https://forum.quasar.dev/).

Thank you.

**Comment by Amosss** [comment]
I made a codepen: https://codepen.io/amosss/pen/ExjKzKG
What about the footer? It is a feature request, no? Why hurry to close this?

**Comment by pdanpdan** [comment]
100px height is too short to show any row - https://codepen.io/pdanpdan/pen/NWqNVyX
I just gave you an example of footer.

**Comment by Amosss** [comment]
OK, so if it works in a codepen and does not work in vscode, what should I check? I'm confused. The problem in my project is that the table scrolls including the headers, they are not stick.

Regarding the footer: I mean to use the footer that is already there in qtable for the totals. That's the reason for a new feature request, no? requesting something that is new...

**Comment by Amosss** [comment]
After changing class to table-class (in qtable), sticky headers are working! 
I will try your link for the footer but still I hope that a summary footer will be added.

**Comment by Amosss** [comment]
I played with the code in the link you gave me but the main problem is setting the totals to the relevant column. That was not possible or I failed to do it. 

If you can, please re-open this feature request as I think it is still relevant. If it's not possible to re-open, please let me know and I will open a new one with just the relevant data. Thanks

**Comment by pdanpdan** [comment]
Please open a new issue and specify what you need. Please describe clearly what you want to do and what you cannot do. And attach a codepen with what you have tried.

**Comment by luishgp** [comment]
Is it possible to do this without leaving the scroll visible in the table header?

**Comment by carlosepcc** [comment]
I got it with the qtable prop `table-style="max-height:50vh"`
also used `class="overflow-hidden-y"` in index.html body (not sure if it's the best way to achieve it)
