### ISSUE TITLE
q-toggle icon appears over q-page-sticky

### ISSUE THREAD

**Issue by bjbk** [quasarframework/quasar#6398]
**Describe the bug**
When scrolling content containing a QToggle, the `checked-icon` and `unchecked-icon` props have the higher z-index.

**Codepen/jsFiddle/Codesandbox (required)**
[Codepen - QToggle z-index bug](https://codepen.io/bjbk/pen/mdJEbJe) 

**To Reproduce**
Create a q-sticky element
Add q-toggles to page and when scrolling the icons have a higher z-index

**Expected behavior**
Expect icons to be behind the QSticky contents as the rest of the QToggle is.

**Screenshots**
![z-index](https://user-images.githubusercontent.com/7434052/74681129-9b3f9f80-5190-11ea-9862-2e3c11d56edc.gif)

**Platform (please complete the following information):**
OS: macOS
Node: 13.2.0
NPM: 6.13.4
Yarn: 1.21.1
Browsers: 
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Safari Version 13.0.5 (14608.5.12)
Electron: 8.x.x

**Quasar**
@quasar/app: 1.5.7
@quasar/cli: 1.0.5

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in "quasar" v1.9.3.
