### ISSUE TITLE
[Request] select a whole week in Datetime component

### ISSUE THREAD

**Issue by llin55** [quasarframework/quasar#640]
Would you please consider adding type="week" to Datatime component? We need a possibility to select a whole week, like here:

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_week

**Comment by smolinari** [comment]
This could be a very unique addition. I know Germans also reference weeks, and it's a step above saying "The week of monday the 26th of June".

I wonder how many other countries speak in terms of "weeks" too?

Scott

**Comment by llin55** [comment]
I think it's rather a business type specific requirement. We serve some automotive companies (not from Germany yet) and they use week numbers for planned deliveries.

And also <input type="week"> is actually in HTML5 specification so hopefully it is not so unique requirement and it will be useful not anly for us :)

thanks! Longin

**Comment by smolinari** [comment]
Yes. It's is definitely more a business thing. Thanks for pointing that out.

Scott

**Comment by KevinHoward** [comment]
Another issue with weeks is how you define it. Some countries start a week on Sunday while others start on Monday. 

Plus, you also have to consider how the week is reflected at the change of the year. Do you allow partial weeks? i.e. first week in 2017 and last week in 2017. Do you reflect weeks by year and week number? 

Just some thoughts on the subject. There will have to be some configuration options that are specific to the week type.

**Comment by spectrolite** [comment]
A lot of people already spent their time defining all this for us, and you can see a pretty good explanation here: https://en.wikipedia.org/wiki/ISO_week_date

**Comment by spectrolite** [comment]
the info below is to be taken with a grain of salt and probably partially inaccurate, but gives a rough idea of the spread of Monday-first vs Sunday-first throughout the world:
https://www.reddit.com/r/MapPorn/comments/35hb3a/first_day_of_the_week_in_different_countries/

**Comment by smolinari** [comment]
Yes, for i18n the day to start the week is important. Saturday can also be the first day of the week in some Islamic countries like Saudi Arabia.  

Scott

**Comment by rstoenescu** [comment]
The day to start the week is configured with 'monday-first' boolean prop. Default is Sunday.

**Comment by smolinari** [comment]
Thanks Razvan. I think this is now two different suggestions. One to have a possibility to have Saturday as  the day to start a week. 

http://chartsbin.com/view/41671

And the other is to have a week selection for q-datetime or q-datetime-range, whichever fits best. 

I'll make a second issue for Saturday. 

Scott

**Comment by spectrolite** [comment]
according to http://beta.quasar-framework.org/components/handling-js-date.html#Format-for-display
we can format a date using `ww` or simply `w` if you don't need 0-padding to output the week of year.
We can also get it like this `date.getWeekOfYear(anyDay)`

but we have no way to specify a date by year + week

more specifically, **week** is absent from 
```
addToDate()
subtractFromDate()
adjustDate()
```
which all accept already : 

-milliseconds 
-seconds
-minutes
-hours 
-days 
-month 
-year

ok a week is just 7 days so it's not a big issue, but why not add week for added convenience ?

and week would be greatly useful in `isSameDate` (which would essentially mean "happens on the same week", pretty useful), and also as a unit in 
```
getDateDiff
startOfDate
endOfDate
```
And for the last two, knowing which day is the first day of the week is indeed important.

**Comment by spectrolite** [comment]
Once we have all that, we are well armed to think, code and manipulate dates in terms of weeks.

It also makes a lot of sense to extend the Datetime Range component UI to accept a `fixed-range` prop, that automatically sets `endDate = startDate + fixedRange` as soon as the start date is picked. 
Obviously we'd like range-size to take any arbitrary or even dynamic value.

Your request of having 
> a possibility to select a whole week

would now be trivial to implement.

**Comment by rstoenescu** [comment]
Will enhance.

**Comment by stgunholy** [comment]
It would be also great to display the week number in calendar. In Norway it is the most common way how people addressing dates - "Tuesday, Week N 36"

**Comment by Abekonge** [comment]
> It would be also great to display the week number in calendar. In Norway it is the most common way how people addressing dates - "Tuesday, Week N 36"

+1 from Denmark and Sweden, this is used all the time, in busineses, in  schools, everywhere. So a week display in the picker-pop-up would really be great...

![image](https://user-images.githubusercontent.com/3431275/57362401-0b8bb000-717f-11e9-8f26-2dd7c2c1fc4f.png)

**Comment by nothingismagick** [comment]
Paging @hawkeye64

**Comment by hawkeye64** [comment]
@nothingismagick Interesting I never saw the notification on this.

**Comment by pdanpdan** [comment]
Close this issue - please follow up in unified #5052
