### ISSUE TITLE
QButton type="submit" doesn't work

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#6400]
**Describe the bug**

submit button contained in the slot of input control , doesn't submit

**Codepen**
[codepen](https://codepen.io/fprijate/pen/ExjyYMY?editors=1011)

**Expected behavior**
Submit should work

**Platform**
OS: win10
Quasar; 1.9.2

**Comment by pdanpdan** [comment]
Hello. Please read the docs: https://quasar.dev/vue-components/input#Slots-with-QBtn-type-%E2%80%9Csubmit%E2%80%9D
