### ISSUE TITLE
StatusBarBackgroundColor Android 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#6401]
Have been on this for some hours google I dont know this is not working how to override the StatusBarBackgroundColor on Android App  have tired this https://github.com/apache/cordova-plugin-statusbar/releases still not working 

<img width="309" alt="Screenshot 2020-02-17 at 20 53 14" src="https://user-images.githubusercontent.com/19895516/74684576-9567af80-51cc-11ea-807f-f097a4a7b74e.png">

**Platform (please complete the following information):**
OS: Android 10 , 9 , 7, 6 
iOS:
Android: 
Electron:

**Comment by rstoenescu** [comment]
Is this a bug or a question? If the cordova plugin doesn't works then open them up a ticket.
