### ISSUE TITLE
Footer with totals/sum/average/custom per column

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#6402]
**Is your feature request related to a problem? Please describe.**
I'm missing a summary footer other than just the number of rows

**Describe the solution you'd like**
I want to have a summary footer where **each column** has its own summary that consists of either sum/count/average/custom (calculation).

**Describe alternatives you've considered**
q-table already have a footer but it only has the count of rows in general. This footer can maybe be extended to have more summary items per column.

![image](https://user-images.githubusercontent.com/17168621/74686610-b46d3e00-51da-11ea-862d-463ce440f81f.png)

**Comment by rstoenescu** [comment]
Hi,

You can use the before/after slots. https://quasar.dev/vue-components/table#Before%2Fafter-slots
