### ISSUE TITLE
Target is passed to QMenu but might be a boolean

### ISSUE THREAD

**Issue by martijn788** [quasarframework/quasar#6406]
In the latest release, (https://github.com/quasarframework/quasar/pull/6310) target is passed from QPopupProxy to QMenu, but according to the documentation, the value of target might also be a boolean. (https://quasar.dev/vue-components/popup-proxy#QPopupProxy-API)

This results in a console error: 
[Vue warn]: Error in nextTick: "TypeError: Cannot read property of 'getBoundingClientRect' of 'undefined'" found in <QMenu>

https://codepen.io/martijn788/pen/OJVXmOp

**To Reproduce**
1. Try to open the q-popup-proxy
2. See error

The expected behaviour is that the pop-up is opened as a QMenu, but nothing happens except for the console error. 
Another expected behaviour is that :target can be filled as a boolean. 

OS: Windows
Browsers: Chrome
Quasar: 1.9.2

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.9.3.
