### ISSUE TITLE
QCarousel & autoplay as Number in 1.9.0

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#6408]
**Describe the bug**
Did autoplay stop working in v1.9.0+ when a number is specified?

**Codepen/jsFiddle/Codesandbox (required)**
forked from the docs and changed `autoplay` to `:autoplay="5000"`
https://codepen.io/smakinson/pen/JjdKrLg?editors=1010

**Expected behavior**
autoplay to function

**Platform (please complete the following information):**
OS: Catalina
Node:
NPM:
Yarn:
Browsers: Chrome, Safari
iOS:
Android:
Electron:

**Comment by webnoob** [comment]
I'll take a look and report back.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.4.

**Comment by smakinson** [comment]
Thank you!
