### ISSUE TITLE
Allow to rotate button icons and standalone icons

### ISSUE THREAD

**Issue by gughog** [quasarframework/quasar#6410]
**Is your feature request related to a problem? Please describe.**
Consider I have a button in the middle of two inputs, and this button has an icon like the `mdi-format-horizontal-align-center`, the visual is something like this: (-> | <- ). This button works perfectly on breakpoints 'md' and above because It points to the element on right and on left, but if I want a mobile view which elements (the two inputs and the button) needs to behave full width ? In this case will make more sense to turn it 90°, so It will point to element on top and bottom. 

**Describe the solution you'd like**
It will be awesome if `q-btn` and `q-icon` has a property like `rotate=90` where we define how much degrees we will rotate that element, or even a class that rotates only the icon in the button element (I know that we actually have a `rotate-90` class, but in the button example it rotates all element, and not only the icon). 

**Describe alternatives you've considered**
As said before, I have tried to rotate my button element with `rotate-90`, but in my case all button was moved, but I need only the icon.

**Comment by hawkeye64** [comment]
@gughog You can use the `rotate-*` classes.
https://quasar.dev/style/other-helper-classes#Orientation-Related

**Comment by hawkeye64** [comment]
sorry, did not mean to close

**Comment by hawkeye64** [comment]
@gughog You can use the slot to define your content and rotate what you need there.

**Comment by hawkeye64** [comment]
@gughog Here is an example: https://codepen.io/Hawkeye64/pen/ZEGOvoy

**Comment by gughog** [comment]
Thank you man, I forgot slots can do this! :smile: But by the way, It will be nice and will make more easy if we have a property to do this. Thanks again!
