### ISSUE TITLE
Elevation prop for components

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#6412]
**Is your feature request related to a problem? Please describe.**
For some components, it does not seem possible to change the elevation using `shadow-N` classes because you can't target the correct DOM element (e.g. FAB).

**Describe the solution you'd like**
Elevation prop that allows to specify the elevation which would be applied to the DOM element most suitable depending on the component.

```vue
<q-fab elevation="12" />
```
**Describe alternatives you've considered**
Custom CSS but prone to breaking because undocumented DOM structure may change.

**Additional context**
I've mostly run into this on the FAB which I would like to change the box-shadow but it ends up creating a square box around the fab if you use a `shadow-N` class.

https://codepen.io/gordonblahut/pen/bGdeaaN?editable=true&editors=101

**Comment by hawkeye64** [comment]
@GordonBlahut Here's your codepen fixed: https://codepen.io/Hawkeye64/pen/dyoXJwa?editors=1010
You just need to apply style `border-radius: 50%` to the QFab.
Leaving this open as @rstoenescu may want to do this in the code. I see no point for the fab to be square unless the `square` property is used.

**Comment by GordonBlahut** [comment]
@hawkeye64 yeah that's my current workaround but it's very focused to the specific example as opposed to a general solution for all cases. 

You end up with separate drop shadows on `.q-fab` and `.q-btn__wrapper` but it's not the end of the world.

I guess as long as the shadow-N classes work as expected then a prop is not necessary.

**Comment by hawkeye64** [comment]
@GordonBlahut The fix I did is to add the missing `q-fab--form-rounded` class, which should help out one part of your issue. It'll be up to @rstoenescu if QFab should get an `elevation` prop.

**Comment by hawkeye64** [comment]
@GordonBlahut Ok, that was not a good fix -- I didn't do enough testing. It made the Fabs look like footballs when used with label. So, it's something you would have to do manually. But, don't round it if using labels -- looked horrid.

**Comment by rstoenescu** [comment]
Enhancement will be available on "quasar" v1.9.5.
