### ISSUE TITLE
QImg Lazy Loading of images

### ISSUE THREAD

**Issue by HenriqueSPin** [quasarframework/quasar#6415]
If we have a bunch of images in ```q-img``` componentes in a scrollable container, all images tries to load immediately, regardless of being present in the viewport or not.

My suggestion is to have a property called ```lazy``` that tell the ```q-img``` component to start loading the file only when it is visible or is about to be (threshold, that could be another property in "viewport units". E.g.: ```:lazy-threshold="1.5"```).

We've considered using [vue-lazyload](https://www.npmjs.com/package/vue-lazyload) in order to solve this, but we would miss some of the great functionalities that ```q-img``` has, specially when used with ```q-avatar```.

**Comment by rstoenescu** [comment]
Hi,

Combine with [QIntersection component](https://quasar.dev/vue-components/intersection) or [Intersection directive](https://quasar.dev/vue-directives/intersection).

**Comment by HenriqueSPin** [comment]
Thanks a lot. As always! But, it would be a nice shortcut :)
Implementing as suggested anyway. Thanks again.
