### ISSUE TITLE
Selected item label in q-select wrapping

### ISSUE THREAD

**Issue by natajonasdacoliveira** [quasarframework/quasar#6416]
Instead of creating a slider, the input expands horizontally, and breaking large texts.

https://codepen.io/Hkz/pen/ZEGOxZb?editors=1000

**To Reproduce**
1. Resize the screen to 320px;
2. Select the biggest option.

**Expected behavior**
https://codepen.io/anon/pen/eXggYK
This is what would be ideal, however, with a scroll (similar to how actually inputing text works)

**Comment by pdanpdan** [comment]
Hello.
I don't understand what is the problem, can you please explain? What do you mean by slider and input that expands horizontally?

Maybe you want something like this?
https://codepen.io/pdanpdan/pen/NWqrJjL?editors=1100

**Comment by natajonasdacoliveira** [comment]
This was exactly what you solved, especially at the second example, thank you very much!
