### ISSUE TITLE
QChatMessage bg-color prop not accepting custom colors

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#6419]
**Describe the bug**
With a custom color added to app.styl, eg:
```
.text-brand {
  color: #a2aa33;
}
.bg-brand {
  background: #a2aa33;
}
```
and using that color in the bg-color prop in a QChatMessage: 
```
<q-chat-message
  avatar="statics/brand/brandLogo.png"
  :text="['I recommend these resources:']"
  bg-color="brand"
  text-color="white"
/>
```
the color does not change to the color specified in app.styl as expected. 

**Platform (please complete the following information):**
OS: Windows
Node: 10.16.3
NPM: 6.9.0
Yarn: 1.22.0
Browsers: Chrome

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.4.
