### ISSUE TITLE
Notify Plugin: Position of group/number badge

### ISSUE THREAD

**Issue by matthiasmeier** [quasarframework/quasar#6421]
Thanks again for adding my notification grouping proposal to Quasar. Highly appreciated.

In the original feature request (#6189), I only added examples with the badge being on the left hand side of the notification. I think being able to choose the position (left/right) of the badge would be another great addition to this feature.

**Describe the solution you'd like**
I’d like to define whether the grouping number badge is shown on the left or right hand side of the notification.

```javascript
this.$q.notify({
    message: 'Jim pinged you.',
    badgePosition: 'left' // or 'right'
})
```

**Describe alternatives you've considered**
This can easily be achieved by adding a badgeClass and the following CSS (we already use this in our project):

```javascript
this.$q.notify({
    message: 'Jim pinged you.',
    badgeClass: 'some-class'
})
```

```scss
// Notification grouping
// Option to move the grouping number badge to the right
.some-class {
    left: auto;
    right: -22px;
}
```

**Additional context**
I thinkk it would be great, if Quasar would by default position the badge on the right hand side of the notifications (as most apps do, e.g. when you get a new message on you phone etc.) and only show it on the left hand side when the notification has a position of either `top-right`, `right` or `bottom-right`. That way, most of the users would very likely don’t have to change it manually.

<img width="1544" alt="Screenshot 2020-02-19 at 11 16 42" src="https://user-images.githubusercontent.com/900640/74826072-42e0dd00-530b-11ea-907e-1fe0e69eb5ca.png">

**Comment by rstoenescu** [comment]
New prop -> badgePosition (top-left, top-right, bottom-left, bottom-right) will be available in "quasar" v1.9.5.
