### ISSUE TITLE
QTable Grid mode + Fullscreen Mode pushes items downwards.

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#6423]
**Describe the bug**
on 1.9+ QTable flex css rule for .q-table__middle class seem to push the items downwards in grid + fullscreen mode.
**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/metalsadman/full/YzXGpLP

**To Reproduce**
1. Go to the codepen link provided
2. Click on Fullscreen icon to go to fullscreen view
3. See the bug.

**Expected behavior**
Grid items should not be pushed to bottom on full screen mode.

**Screenshots**
 normal view
![image](https://user-images.githubusercontent.com/31038838/74885735-44fd7700-53b1-11ea-9a58-10448e5f806c.png)

fullscreen view
![image](https://user-images.githubusercontent.com/31038838/74885794-69f1ea00-53b1-11ea-9f88-e850513f8fc3.png)

removing flex rules
![image](https://user-images.githubusercontent.com/31038838/74885821-78400600-53b1-11ea-9e22-b7974104a6eb.png)

**Platform (please complete the following information):**
OS: Ubuntu 18.6/ Win 10
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
the new css looks great in non grid mode as the bottom slots sticks at bottom even on scrolling.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.5.
