### ISSUE TITLE
Using mask with any non-latin letters

### ISSUE THREAD

**Issue by andreydos** [quasarframework/quasar#6424]
**Is your feature request related to a problem? Please describe.**
I try to use :mask with Cyrillic (the same situation will exist with any non-latin alphabet), but with mask="AA" or mask="aa" I can't type any letter in Russian(for example "ы", "Н")
You can try in out example in official documentation
https://quasar.dev/vue-components/input#Mask

**Describe the solution you'd like**
I want to have some possibility to use non-latin letters (add new token here https://github.com/quasarframework/quasar/blob/dev/ui/src/mixins/mask.js#L13)

**Describe alternatives you've considered**
Maybe it will be a more light way to add some  new "blank" TOKEN (except #,S,N,A,a,X,x) which will accept any character.

**Additional context**
no additional context

**Comment by aren1989** [comment]
Please do this as soon as possible, thx.

**Comment by kulkoff** [comment]
Hi. I am joining. A very necessary option

**Comment by pdanpdan** [comment]
Closing this to follow in https://github.com/quasarframework/quasar/issues/6969
