### ISSUE TITLE
Unable to customize or use SVG icon for QPagination direction links

### ISSUE THREAD

**Issue by dodohack** [quasarframework/quasar#6426]
**Describe the bug**
When using SVG icons(https://quasar.dev/vue-components/icon#Svg-icons) and no webfont icon set is defined in extras in quasar.conf.js, QPagination will display empty left/right direction link icons if set :direction-links="true".

Using quasar v1.9.3.

![Screen Shot 2020-02-19 at 1 15 41 PM](https://user-images.githubusercontent.com/19568348/74837801-31530180-531a-11ea-86c0-08991c8294b4.png)

**Comment by rstoenescu** [comment]
Have you also set the Quasar iconSet to the same name as the svg icons that you want to use?

**Comment by hawkeye64** [comment]
@dodohack You might be interested in this: https://github.com/quasarframework/quasar/pull/6409 - will be in quasar v1.9.4
