### ISSUE TITLE
Custom icon to QExpansionItem

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6427]
**Is your feature request related to a problem? Please describe.**
Please add `icon` prop to `QExpansionItem`.
I use new icons Line Awesome, and caret icon there... not so nice looking )

**Describe the solution you'd like**
Add new prop to QExpansionItem

**Comment by metalsadman** [comment]
> **Is your feature request related to a problem? Please describe.**
> Please add `icon` prop to `QExpansionItem`.
> I use new icons Line Awesome, and caret icon there... not so nice looking )
> 
> **Describe the solution you'd like**
> Add new prop to QExpansionItem

there's the `expand-icon` and `expanded-icon` props for this https://codepen.io/metalsadman/pen/XWbjryO?editors=1010. check the api for usage https://quasar.dev/vue-components/expansion-item#QExpansionItem-API.

**Comment by matro-skin** [comment]
Sorry, my bad
