### ISSUE TITLE
Suggested practice to develop mobile/desktop only part of project

### ISSUE THREAD

**Issue by slanska** [quasarframework/quasar#643]
First, thanks for an amazing project, both in terms of quality of components and convenience of tooling.
I have a few questions/suggestions, so this is the first issue in coming serie. What is suggested way to develop cordova (or electron) only specific portion of code. Let's say, how do I manage code which gets executed only when running as cordova app? Also, for electron app, what is recommended way to bundle server side logic (node.js worker)?

Thanks in advance

**Comment by rstoenescu** [comment]
Hi,

Please use forum for questions as stated in the comment when creating a new issue.
http://forum.quasar-framework.org/

Thanks!
