### ISSUE TITLE
Dark mode support for QPullToRefresh

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#6434]
**Is your feature request related to a problem? Please describe.**
QPullToRefresh has no support for dark mode (for the icon's background).

**Describe the solution you'd like**
Please add support for dark mode for QPullToRefresh.

**Describe alternatives you've considered**
Custom CSS.

**Additional context**

**Comment by rstoenescu** [comment]
In order to keep backward compatibility, adding "bg-color" String prop in v1.9.5.
