### ISSUE TITLE
Toggle UI wrong

### ISSUE THREAD

**Issue by stegithub** [quasarframework/quasar#6435]
"quasar": "^1.9.3"
"@quasar/extras": "^1.3.3"

Everywhere toggle is broken on UI only, logic is working.
code (with tag): q-toggle v-model="accept" label="I accept the license and terms" 

<img width="314" alt="Schermata 2020-02-19 alle 22 19 28" src="https://user-images.githubusercontent.com/19598492/74877739-3b9aed00-5366-11ea-8248-0da87847a1af.png">

**Comment by rstoenescu** [comment]
UI seems fine, docs look fine, codepen looks fine. U haven't provided all the information necessary in the ticket template here on Github.

Unless I am missing something really big, I am 100% sure it's one of your CSS rules tampering with QToggle. But there's no way of helping you without more information.
