### ISSUE TITLE
Label color of q-radio in q-field

### ISSUE THREAD

**Issue by billycat** [quasarframework/quasar#6436]
**Describe the bug**
Hi, when put q-radio in q-field, I found the q-radio label color maybe has problem. They get the same color of q-radio choosed color( default primary )

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/az73ukx8/

**To Reproduce**
1. Open jsfiddle, run
2. You can see the first q-radio group has same label color.

**Screenshots**
![image](https://user-images.githubusercontent.com/6973133/74898896-36758680-53d6-11ea-880e-da19e10fc83a.png)

Maybe there will be some options of q-radio I don't found.
Thanks.

**Comment by metalsadman** [comment]
@billycat wrap it in q-field's scope slot `control`. https://jsfiddle.net/pgr8v3jf/

**Comment by rstoenescu** [comment]
Also, as a good to know: the label inherits the current text color.

**Comment by billycat** [comment]
Thanks for the help.
