### ISSUE TITLE
Local/Session Storage Plugins: Get all keys

### ISSUE THREAD

**Issue by the-nicolas** [quasarframework/quasar#6440]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to get a list of all keys - just getAll() which also returns all the values.
I need a way to iterate over the keys

**Describe the solution you'd like**
The function key() of the web storage api is not included.
https://developer.mozilla.org/de/docs/Web/API/Storage/key

Witth that method in combination with the existing getLength() it would work.

**Describe alternatives you've considered**
None/

**Comment by the-nicolas** [comment]
I guess it just got forgotten. I think it makes no sense to open a community pull request for that...

**Comment by rstoenescu** [comment]
getKey and getAllKeys will be available for both local and session storage in "quasar" v1.9.4

**Comment by rstoenescu** [comment]
Why did u say that it makes no sense for a PR?
