### ISSUE TITLE
Q-Form check if is dirty

### ISSUE THREAD

**Issue by dungeon2567** [quasarframework/quasar#6443]
Is your feature request related to a problem? Please describe.
I want QForm to have a 'is-dirty' property to show 'unsaved changes' warning dialog.

Describe the solution you'd like
Add is-dirty syncable property to Q-Form

**Comment by metalsadman** [comment]
@dungeon2567 you can use a ref on your QForm and call validate on it. ie. `this.$refs.form.validate()` returns a promise, check if it's false then show a warning.
from the docs:
![image](https://user-images.githubusercontent.com/31038838/75103636-55735300-5638-11ea-94d7-fa6f580c71d6.png)

**Comment by pdanpdan** [comment]
How could the form know it has unsaved changes?

**Comment by dungeon2567** [comment]
add a listener to every 'field'?

**Comment by pdanpdan** [comment]
Hello. Please do data validation based on model, not on markup. In your specific case check if the form model changed from the default, or implement a proxy for the model that sets the dirty flag when the model is changed.
