### ISSUE TITLE
QResponsive component won't causes compile error when importing to quasar.conf.js

### ISSUE THREAD

**Issue by elorenzen** [quasarframework/quasar#6444]
**Describe the bug**
When trying to import 'QResponsive' to the components array in quasar.conf.js, it causes a build compile error.

**Codepen/jsFiddle/Codesandbox (required)**
N/A -- compile error

**To Reproduce**
1. Go to 'quasar.conf.js'
2. Type 'QResponsive' in components array.
3. Run 'quasar dev'

**Expected behavior**
The build fails and presents an error.

**Screenshots**
https://user-images.githubusercontent.com/16691999/74971984-d1219580-53d5-11ea-9ff4-0307f97ad17c.png

https://user-images.githubusercontent.com/16691999/74972004-d5e64980-53d5-11ea-8035-23f4fc5e2daa.png

**Platform (please complete the following information):**
OS: Windows 10
Node: Yes
NPM: Yes
Yarn: No
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by metalsadman** [comment]
yep, it's not displaying anything for me neither 
![image](https://user-images.githubusercontent.com/31038838/74972977-a24f0200-545d-11ea-82f5-2941f0cbbee7.png)

**Comment by pdanpdan** [comment]
Output of `quasar info` in the project folder, please?

**Comment by metalsadman** [comment]
![image](https://user-images.githubusercontent.com/31038838/74973371-4638ad80-545e-11ea-8297-520e0b570b81.png)

**Comment by pdanpdan** [comment]
@metalsadman In your case you just have to set an width to QResponsive - it's collapsed - try to make a codepen with your case, else we cannot help.

@elorezen Update your quasar package - I suppose you try to use QResponsive on a version before it was introduced.

**Comment by metalsadman** [comment]
> @metalsadman In your case you just have to set an width to QResponsive - it's collapsed - try to make a codepen with your case, else we cannot help.
> 
> @elorezen Update your quasar package - I suppose you try to use QResponsive on a version before it was introduced.

ok that worked, i just added a col class. ty.

**Comment by elorenzen** [comment]
@pdanpdan Forgetting to update my Quasar version was an oversight. It works now, thanks
