### ISSUE TITLE
Disable tab-index for QEditor toolbar

### ISSUE THREAD

**Issue by jd-0001** [quasarframework/quasar#6449]
**Is your feature request related to a problem? Please describe.**
This feature request is related to UX.
Assume you are filling the form which includes QEditor somewhere between. So, if you use `Tab` to navigate through form, When you try to enter text in QEditor it will loop through all the Toolbar actions and then cursor will be available in content area to enter text.

This is case can go worse if someone have more than 7 toolbar actions.

**Describe the solution you'd like**
Prop for disabling tab index in toolbar actions. So, user can directly fall into content area to enter text.

**Describe alternatives you've considered**
None.

**Additional context**
![chrome-capture](https://user-images.githubusercontent.com/47495003/75033987-2e9b0c80-54d2-11ea-8841-77e363682b1c.gif)

**Comment by hawkeye64** [comment]
@jd-0001 I encourage you to read up about Aria/A11y as what you propose would be deterrent for those with disabilities. How would they find the "action" they want to perform using a screen reader?
https://www.w3.org/TR/wai-aria/#managingfocus

**Comment by jd-0001** [comment]
I got it. Thanks, @hawkeye64

**Comment by GoodiesHQ** [comment]
Seems like there was no solution for this. Is there any workaround? It is definitely too many tabs...
