### ISSUE TITLE
Tip: How to get a list of all used components in your application

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#645]
Execute this in the root of your project.
You'll get for each .vue file the list of quasar components used.

```shell
find ./src -name *.vue -printf "list=\$(grep -oP \"<\\\\K(q-[^\\\\s>/]+)\" %p | sed -r 's/(-|^)(.)([^-]*)/\\\\U\\\\2\\\\L\\\\3/g; s/^/  /; s/$/,/' | sort | uniq); echo \"\\\n*** %p\\\n\\\nimport {\\\n\$list\\\n} from 'quasar';\\\n\\\ncomponents: {\\\n\$list\\\n},\\\n\";" | sh
```

**Comment by rstoenescu** [comment]
Excellent tip. Maybe an addition to the docs instead? Probably on the upgrade guide too.

**Comment by BenoitRanque** [comment]
Does this work on windows? I get errors

**Comment by pdanpdan** [comment]
On windows with cmder/git-for-windows installed.
And you have to check the path of the commands because windows uses it's own ones.

**Comment by rstoenescu** [comment]
Linked this issue from [forum](http://forum.quasar-framework.org/topic/522/upgrade-guide-for-0-14-beta).
