### ISSUE TITLE
mistyped `options.model` in QDialogOptions type

### ISSUE THREAD

**Issue by steersbob** [quasarframework/quasar#6452]
**Describe the bug**
The interface `QDialogOptions` has `options.model` as type `any[]`. This is incorrect for dialogs with a singular model (eg. radio).

**Codepen/jsFiddle/Codesandbox (required)**
```typescript
import { Dialog } from 'quasar'; 
Dialog.create({
  options: {
    type: 'radio',
    model: 'a',
// ^ Type 'string' is not assignable to type 'any[]'. Vetur(2322)
    items: [
      { label: 'a', value: 'a' },
      { label: 'b', value: 'b' },
    ],
  },
});
```
Replace `model: 'a'` with `model: 'a' as any` to get a correct radio button dialog.

**To Reproduce**
- Initialize quasar project with typescript enabled.
- Add the above code
- Run `quasar dev`

**Expected behavior**
QDialogOptions to allow non-array types in `options.model` when `options.type` is a singular value.

**Screenshots**

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 12.14.1
NPM: 6.13.4
Yarn: N/A
Browsers: N/A
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.9.4.
