### ISSUE TITLE
Deploying app in SSR mode - Transpile ES6

### ISSUE THREAD

**Issue by vdraceil** [quasarframework/quasar#6454]
`quasar build -m ssr` succeeds.
`quasar dev -m ssr` starts the server, but on the first request it throws up a ES6 related error
_SyntaxError: Unexpected token 'export'_
as one of the files imported (from an npm package) in the client side (by some component) has `export default xyz;` in it

I'm totally new to Quasar. I just moved from Nuxt.
I tried the docs but couldn't find much help there - https://quasar.dev/quasar-cli/developing-ssr/configuring-ssr

How do I get the client js files transpiled?
Any help/pointers would be appreciated

**Comment by yusufkandemir** [comment]
@vdraceil [build.transpileDependencies](https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build) is probably what you are looking for.

**Comment by vdraceil** [comment]
Ah yes! I totally overlooked this config item. Thank you!
