### ISSUE TITLE
Overflow Component

### ISSUE THREAD

**Issue by psprokofiev** [quasarframework/quasar#6456]
**Is your feature request related to a problem? Please describe.**
What you have too large text, it makes it fix-height and add "expand" button at the bottom.
Smth like that:
https://gist.github.com/matro-skin/4b10635219deabd2781d5d4dbcfcd6d5

**Comment by pdanpdan** [comment]
you can do something very simple like this (CSS only): https://codepen.io/pdanpdan/pen/WNGBpgM?editors=1100
but I'm pretty sure you can use some sort of clamp.js to get some more complex things

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
