### ISSUE TITLE
classes and stylus variables for predefined button sizes (xs, sm, md, lg, xl)

### ISSUE THREAD

**Issue by aleksander237** [quasarframework/quasar#6459]
**Is your feature request related to a problem? Please describe.**
Sometimes medium is too big and small is too small. Especially with icons. Sure I can set the exact button size or bind the size to the vuex property but there is probably a cleaner solution.

**Describe the solution you'd like**
classes and stylus variables for predefined button sizes (xs, sm, md, lg, xl). Something like .q-btn--size-xs and $button-size-xs ...

**Comment by aleksander237** [comment]
Any chance for this?

**Comment by matiasjg** [comment]
Hi,

We are looking for the same here, is there any way that we can switch to use style vars? Right now the values are inside the JS:

![image](https://user-images.githubusercontent.com/5497563/85169402-1f3e8c80-b242-11ea-9f6a-e3827925081b.png)

**Comment by gabriel-maus** [comment]
Something on this?

**Comment by rstoenescu** [comment]
Hi,

There is no need for custom stylus variables. Just create a few CSS classes with your desired sizes and add those classes to your QBtns: https://codepen.io/rstoenescu/pen/KKVmqGV or even a .q-btn class (used by QBtns) with your default size that you want to have (same technique with font-size).

The whole UI is built with extensibility in mind and ease of customization so benefit from it!
