### ISSUE TITLE
Drawer not working mobile or zoom in google chrome browser

### ISSUE THREAD

**Issue by rof20004** [quasarframework/quasar#646]
Drawer not working properly when I change to mobile ou zoomin the page, It not closes when I click in a item or swipe to left, here is the site in production to test:

https://gerador-formulario-pdf.firebaseapp.com

**Comment by rof20004** [comment]
The error occurr if I change another route and try to swipe to left the drawer, or choose another route again.

**Comment by BenoitRanque** [comment]
Steps to recreate

1. Create a new quasar project using `quasar init default#beta <folder_name>`
2. `cd <folder_name>`
3. 'npm i`
4. modify routes in router.js to look like this
```
  routes: [
    {
      path: '/',
      component: load('Hello'),
      children: [
        {
          path: 'tab1',
          component: load('tab1')
        },
        {
          path: 'tab2',
          component: load('tab2')
        }
      ]
    },

    // Always leave this last one
    { path: '*', component: load('Error404') } // Not found
  ]
```
5. Add the folowing files in `src/components`
```
// tab1.vue
<template lang="html">
  <div>
    <h1>This is tab 1</h1>
  </div>
</template>

// tab2.vue
<template lang="html">
  <div>
    <h1>This is tab 2</h1>
  </div>
</template>
```
6. Modify `src/components/Hello.vue`
```
...
    <div slot="left">
      <q-list no-border link inset-delimiter>
        <q-list-header>Menu</q-list-header>
        <q-item to="/tab1" exact>
          <q-item-side icon="add_box"></q-item-side>
          <q-item-main label="tab1" sublabel="Th first Tab"></q-item-main>
        </q-item>
        <q-item to="/tab2" exact>
          <q-item-side icon="transfer_within_a_station"></q-item-side>
          <q-item-main label="tab2" sublabel="The second tab"></q-item-main>
        </q-item>
      </q-list>
    </div>
    <router-view/>
...
```
7. `quasar dev`
8. resize browser window until left panel dissapears
9. click menu icon to open left panel
10. click tab 2 _panel should close, does not_
11. click outside panel. **panel will not close**

**Comment by rstoenescu** [comment]
You need to use [QSideLink](http://beta.quasar-framework.org/components/layout-side-links.html) instead of QItem for route changes. I will make it more clear in the documentation.

```js
<q-side-link item to="/tab1" exact>
          <q-item-side icon="add_box"></q-item-side>
          <q-item-main label="tab1" sublabel="Th first Tab"></q-item-main>
        </q-side-link>
```

**Comment by rof20004** [comment]
Thanks, I used q-item because this came with template, in a fresh install, I think you can change the template to use q-side-link item instead q-item.
