### ISSUE TITLE
Q-Message-Avatar lost margin 

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#6462]
In newer versions of Quasar there is no margin between Q-Message-Avatar and the message bubble.

![Example](https://i.imgur.com/Gs98iZx.png)

It was probably lost in commit 0ba20e1481945cd61b55200bda5dd3eb56e7ce6b ?

Workaround:
```
  .q-message-avatar {
    margin-right: 10px;
    .q-message-sent & {
      margin-right: 0;
      margin-left: 10px;
    }
```

**Comment by rstoenescu** [comment]
Looks fine.. Can you provide a codepen pls?
If you are using the "avatar" slot, you need to either attach both "q-message-avatar" and "q-message-avatar--sent/received" CSS classes or your custom margin. It's indeed more code to write, but it allows for easy customization.

**Comment by jeancaffou** [comment]
Yes, using slot. 
Adding class `q-message-avatar--sent` or `q-message-avatar--received` works.

In previous versions, just adding `q-message-avatar` class was enough.

**Comment by rstoenescu** [comment]
Will enhance docs.
