### ISSUE TITLE
[feat] QTabs/QTab needs text-align prop

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#6466]
Currently, QTabs has an `align` prop. This is basically how the actual tabs align in horizontal mode on a tab row. Since vertical tabs were introduced, this property is no longer as clear and people have been using it to try and align text within a tab.

A new `text-align` property would determine how the text within a tab would be aligned. This can be used for both horizontal and vertical tabs, but would be most visible and make most sense for the vertical tabs.

**Comment by hawkeye64** [comment]
or this, to be similar to `inline-label` on QTabs, this could be called `align-label`

**Comment by tanthammar** [comment]
Or/And  add the "align" and "justify" prop to q-tab.
Naming consistency ...

Example:
```html
<q-tabs
   vertical
   align="left" //existing prop to control row justification
>
<q-tab
   align="left || right ..." // new prop, grouped alignment of label and icon. 
   justify="between || around || start || end ..." // new prop, spacing between label and icon
/>
</q-tabs>
```

**Comment by hawkeye64** [comment]
@tanthammar I made further adjustments that cover your scenario

**Comment by rstoenescu** [comment]
Breaking changes... can't merge this one...

**Comment by hawkeye64** [comment]
@rstoenescu Can you tell me what's breaking? Is it fixable?

**Comment by Jokertwo** [comment]
Is there any progress?

**Comment by hawkeye64** [comment]
@Jokertwo Nope. Pretty much dead.

**Comment by dsl101** [comment]
I was about to submit a FR for this. As a really simple option perhaps, if the QTabs is `vertical` and the `align="left"` prop is set, applying `style="justify-content: initial"` to the QTab children achieves the left alignment.

Any chance it could be resurrected?

**Comment by hawkeye64** [comment]
@dsl101 You'd also have to NOT break vertical tabs

**Comment by dsl101** [comment]
Sorry? This is about improving vertical tabs...
