### ISSUE TITLE
Card with list structure of documentation is different of sample smartphone

### ISSUE THREAD

**Issue by lvfx93** [quasarframework/quasar#647]
### Software version
Quasar: 0.13.10
OS: Windows 10
Node: v6.10.3
NPM: 3.10.10
Browsers: 
Google Chrome version 58.0.3029.110 (64-bit)

### What did you get as the error?

Pasting the card structure in my project, I saw the error:

![documentation](https://user-images.githubusercontent.com/28195681/27520294-406622e8-59de-11e7-8819-8aa71526f534.png)

### What were you expecting?

I expected to have the component rendering like the doc shows:

![smartphone](https://user-images.githubusercontent.com/28195681/27520305-754e0d40-59de-11e7-9ca4-5b1d82d38534.PNG)

I fixed my problem following the smartphone sample. But I hope that in next version It should be solved.

### What steps did you take, to get the error?

Just copy and paste from doc

**Comment by smolinari** [comment]
Could you please create this issue in the docs repo? 

https://github.com/quasarframework/quasar-framework.org

Thanks!

Scott
