### ISSUE TITLE
Dialog @show and @before-show events don't return the native event

### ISSUE THREAD

**Issue by omnichronous** [quasarframework/quasar#6473]
**Describe the bug**
The `@show` and `@before-show` events on a `<q-dialog>` element don't return the native event (like `@hide` and `@before-hide` do).

**Codepen/jsFiddle/Codesandbox (required)**
Here is a fork of the simplest QDialog demo from Quasar docs: https://codepen.io/omnichronous/pen/GRJrbjJ

**To Reproduce**
1. Click any of the buttons in the Codepen and see the resulting output

**Platform (please complete the following information):**
OS: Kubuntu 18.04 64-bit
Node: 12.2.0
NPM: 6.13.0
Yarn: 1.21.1

**Comment by pdanpdan** [comment]
You are showing the dialogs using the model - there is no event involved that can be emitted.
If you want the events call `show` method on the ref with the event: https://codepen.io/pdanpdan/pen/VwLpYJr?editors=1010
