### ISSUE TITLE
Virtual-scroll: Always display items while scrolling

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#6474]
**Is your feature request related to a problem? Please describe.**
Its not really a problem more like a UI improvement as well as making the virtual scroll component prettier

**Describe the solution you'd like**
I would like to see the new items when fast scrolling a virtual scroll component. Not the light-grey moving lines as it is right now.
This implements what i want:
https://tangbc.github.io/vue-virtual-scroll-list/demos/vfor-mode/ 

**Describe alternatives you've considered**
I will probably implement it using this external component but it would be nice to have something similar in quasar by default.
https://github.com/tangbc/vue-virtual-scroll-list

**Additional context**
none.

**Comment by pdanpdan** [comment]
This is not really possible - it's a trade off between smooth scrolling and speed of update.

**Comment by hybridmuse** [comment]
Vuetify seems to have this working: [https://vuetifyjs.com/en/components/virtual-scrollers/#virtual-scroller](https://vuetifyjs.com/en/components/virtual-scrollers/#virtual-scroller)

**Comment by Quasarman** [comment]
Yeah I know that, also these two projects managed to show the items while scrolling through the list:

https://github.com/tangbc/vue-virtual-scroll-list
https://github.com/Akryum/vue-virtual-scroller

I am using the latter one for now. Maybe support for this will be added to quasar in the future.

Furthermore I am not sure if things like dynamic height for the list items (e.g. in a chat history) would even be possible with the quasar virtual scroll component.

**Comment by pdanpdan** [comment]
@Quasarman No, it's not possible. the examples in the docs have a person that manually draw a picture when you scroll :)

You are free to use whatever virtual scroll implementation you like, it's not like you payed something for the current one.

**Comment by Quasarman** [comment]
Hey @pdanpdan I was just pointing this out for @hybridmuse. I know I am not paying anything for quasar and I am really grateful that it is free....

**Comment by hybridmuse** [comment]
@Quasarman thank you for the virtual scroll alternatives. I'm sorry you got whacked for it lol.

> it's a trade off between smooth scrolling and speed of update

So from what I get these other libs went with slightly rougher scrolling for faster view update.
I guess it's a matter of taste then. It's just always nice to cover both sides of the spectrum.

And yes we're all very grateful for quasar, and all want it to be the best framework possible. 

> the examples in the docs have a person that manually draw a picture when you scroll :)

is that person Razvan? :)

**Comment by pdanpdan** [comment]
Hmm, as I took it as a personal challenge I checked all the referenced implementations:
- vuetify - it will smooth scroll on the start of the list but jump one page at a time at the end of the list, only works with fixed height elements - it looks like they needed to tick this box of available features list
- tangbc - in the example if you use 100k elements will trigger a recursion limit error and break
- **akryum** - I knew this before and it has the **most advanced implementation**, very nice (there is something broken in the recycler example, scroll all way down and then up)

**Comment by hybridmuse** [comment]
Good overview, I checked and you're right, there's really no perfect implementation yet... wow that akryum bug is weird, quasar's version might hide the items on scroll but at least it's reliable. Better stick to what works for now, thanks for the investigation @pdanpdan
