### ISSUE TITLE
q-table data with currency format

### ISSUE THREAD

**Issue by bobc82** [quasarframework/quasar#6485]
Is there a way to format numeric data as currency inside q-table cells?

For example actually i have :

columns:[
{
          name: "price",
          label: "Price",
          sortable: true,
          required: false,
          field: row => row.Price,
          sort: (a, b) => a - b
        },
...
],

Actually i view numeric data as: 470798.92. But the desired formatting is 470.798,92 (european format currency: point separator for thousands and comma separator for decimals).

**Comment by pdanpdan** [comment]
Format the value as you see fit for display adding a format function in the definition of the column.
Please read the docs: https://quasar.dev/vue-components/table#Defining-the-columns
