### ISSUE TITLE
Helper to request files from user

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#6488]
**Is your feature request related to a problem? Please describe.**
I believe this problem was faced by everybody. When you want to customize files input, you should create a hidden input[type=file] element and click on it programmatically when you need it (when user click a button, for example). That's a huge overhead.

**Describe the solution you'd like**
I'd like to have a helper or plugin of some sort which handles this for me. The usage could look like this:
```js
const files
try {
  files = await requestFiles({ accept: ['image/png', 'image/jpeg']  /* some input options */ })
} catch {
  console.log('mmmmm?')
}
```

**Describe alternatives you've considered**
There are two alternatives inside quasar: file picker and uploader. But i believe that handling input files it very personal case in each project, even if they follow md specs, so many developers could use this helper.

**Comment by pdanpdan** [comment]
There is no other way to get a file from client fs but the input `<type="file" .../>`.

**Comment by 1001v** [comment]
@pdanpdan would you please read what i've written more carefully? I don't want a magic new way to handle files, i want quasar to handle these inputs for me.

**Comment by pdanpdan** [comment]
Please describe step by step what would your code in OP do.

**Comment by 1001v** [comment]
@pdanpdan 
1) We put this code in a method
2) We call this method on btn click or somewhere else
3) The method calls for requestFiles with arguments
4) requestFiles internally creates an input with given arguments and clicks it programmatically
5) A file selector opens and user selects files
6) requestFiles returns these files
Maybe this helper should be sync, i didn't think of it very well.

**Comment by pdanpdan** [comment]
You mean something like this?
https://codepen.io/pdanpdan/pen/ExjmYBb?editable=true&editors=101

It's a 10 lines function you can implement in your code without a problem. But to cover all possible use cases it would become more complex, so I think it's best to make it tailored to your use case.

Also you have to check if it would work on mobile.

**Comment by 1001v** [comment]
@pdanpdan this is the meaning of helpers: not to write the same code again and again, even if it's 10 lines of code. Also i'm pretty sure that this works on mobile.

**Comment by pdanpdan** [comment]
Then feel free to make a PR for it.

**Comment by 1001v** [comment]
@pdanpdan that is the point of feature requests in that case, if you answer "just make PR"? That's confusing. At first you just closed this issue and didn't try to understand it. If it's about language barrier i'm sorry, but in that case you could point me on it. You could just say "we don't want to do it" or "that's something we don't want to do right now" and it's totally fine, i can understand. But if it's a legit feature request, why close it immediately? I don't try to demand on something here, i'm sorry if it looks that way for you.

**Comment by rstoenescu** [comment]
So I reopened this ticket to go as far as I can with a bulletproof implementation of this. Unfortunately, there is no solution **for all platforms** to detect when the user hits the Cancel button -- so that we can perform a cleanup. As a result, I'm sorry but will close this ticket.
