### ISSUE TITLE
Error when style tag has lang="postcss"

### ISSUE THREAD

**Issue by AgentCosmic** [quasarframework/quasar#6489]
**Describe the bug**
In my vue component adding a <style> tag with lang="postcss" will fail to build with this error "You may need an additional loader to handle the result of these loaders."

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/qh87fb40/

**To Reproduce**
Add lang="postcss" to <style> tag

**Expected behavior**
Should not fail to build.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows
Node: 12.14.0
NPM: 6.11.3
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Specifying "postcss" is redundant. Remove it. All CSS assets, be that regular CSS, Sass/SCSS or Stylus go through postcss.

**Comment by AgentCosmic** [comment]
Hi,
I know it goes through postcss, but there are 2 issues that arise:
1) When I import components from other project that doesn't use Quasar the build fails.
2) Linting will fail because it does not detect the style as postcss.
