### ISSUE TITLE
DataTable Toolbar rendering

### ISSUE THREAD

**Issue by lusaxxx** [quasarframework/quasar#649]
Quasar: 0.14
OS: Windows 10
Browsers: Chrome

**What did you get as the error?**

conditional rendering of toolbar - hasToolbar has wrong condition this.filteringCols.length.  Filtering select is displayed in different row. Now toolbar can be empty but is still rendered.

**What were you expecting?**

Toolbar will not be rendered when condition is true

```
hasToolbar () {
      return this.config.title || this.config.columnPicker || this.config.refresh
    }
```

**Comment by rstoenescu** [comment]
Available in latest v0.14.
Thanks for reporting this!
