### ISSUE TITLE
[iOS] QSelect doesn't trigger the keyboard when using Autocomplet on more than 2 chars

### ISSUE THREAD

**Issue by alexpvieira** [quasarframework/quasar#6491]
**Describe the bug**
Using the docs examples, when you tap on the QSelect example for Basic autocomplete (https://quasar.dev/vue-components/select#Example--Basic-autocomplete) the keyboard show up and the user can start typing immediately.

When using the example Autocomplete on more than 2 chars (https://quasar.dev/vue-components/select#Example--Autocomplete-on-more-than-2-chars) the user has to tap on the search box on the top of the screen for the keyboard to show up.

**Codepen/jsFiddle/Codesandbox (required)**
Working example: https://quasar.dev/vue-components/select#Example--Basic-autocomplete
Not working example: https://quasar.dev/vue-components/select#Example--Autocomplete-on-more-than-2-chars

**To Reproduce**
1. On **iOS** access the docs on https://quasar.dev/vue-components/select#Example--Autocomplete-on-more-than-2-chars
2. Tap on the Qselect from the example
3. Tap on the search box on top of the screen
4. The keyboard will show up
5. On **iOS** access the docs on https://quasar.dev/vue-components/select#Example--Basic-autocomplete
6. Tap on the Qselect from the example
7. The keyboard will show up without the user tapping on the search box

**Expected behavior**
The keyboard has to show up without the need for a second tap on the example https://quasar.dev/vue-components/select#Example--Autocomplete-on-more-than-2-chars

**Screenshots**
![image](https://user-images.githubusercontent.com/11370643/75377356-60d0b380-58b0-11ea-8ba9-d64ada0ba33f.png)

![image](https://user-images.githubusercontent.com/11370643/75377327-4dbde380-58b0-11ea-88c6-afe16edc2e03.png)

**Platform (please complete the following information):**
OS: iOS
Node: 11.12.0
NPM: 6.13.7
Browsers: Safari
iOS: 13.3.1

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.9.

**Comment by Bosphoramus** [comment]
This is not fixed, i think the field on the popup gets focused, but the keyboard is not triggered

**Comment by pdanpdan** [comment]
@Bosphoramus 
Hello, his looks like a regression in Qv2 (in Qv1 all works as expected)
Can you please open an issue with the same title and specify Qv2 and link to this issue?

**Comment by Bosphoramus** [comment]
yes @pdanpdan thank you :)
