### ISSUE TITLE
QTree Node with background color for selection

### ISSUE THREAD

**Issue by papotte** [quasarframework/quasar#6493]
I would like to have background color for a selected item inside a tree, the same way one can set the text color for selected items. This can help usability when brand colors are darker.

**Comment by pdanpdan** [comment]
Closing this to track it in https://github.com/quasarframework/quasar/issues/6959

**Comment by glorat** [comment]
I wanted this too... but workaround for now is styling such as

```
<style scoped>
::v-deep .q-tree__node--selected .q-tree__node-header-content {
  background-color: #e8f0fe;
}
</style>
```

or
```
<style scoped>
::v-deep .q-tree__node--selected {
  background-color: #e8f0fe; /* Light blue background */
  color: #202124; /* Default dark color for text and icons */
  border-radius: 10px; /* Rounded corners for a modern look */
}
</style>
```
