### ISSUE TITLE
input event triggered unexpectedly on QEditor

### ISSUE THREAD

**Issue by zz5840** [quasarframework/quasar#6501]
**Describe the bug**
input event will be triggered once sometimes

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/quasar-test-iqkzn

**To Reproduce**
1. type some thing in the editor, and there is only one console message printed when typing first time
2. change the :value to v-model at line 2 in components/Editor.vue， the event triggered normally although there are some errors
![image](https://user-images.githubusercontent.com/16662647/75450876-8e018c80-59aa-11ea-8ab9-90907233d0be.png)
3. so change the value to text which uses computed proterty, the event will be triggered only once again

**Comment by pdanpdan** [comment]
This is normal - you cannot mutate a prop.
And if you don't update the value passed to the QEditor there will be no new emit because from it's point of view there is no change from the internal model.

Updating the prop should be done by emitting the changed value up and changing the value in the original place.

**Comment by zz5840** [comment]
@pdanpdan but the input event is only triggered once no matter type how much

**Comment by pdanpdan** [comment]
You are not changing the value for the QEditor, so there will be no new event emitted.

**Comment by zz5840** [comment]
@pdanpdan so type in the editor is not change?

**Comment by pdanpdan** [comment]
Please head to our discord channel (https://chat.quasar.dev/) or to the forum (https://forum.quasar.dev/) for help requests.
Thank you.

**Comment by pdanpdan** [comment]
Please head to our discord channel (https://chat.quasar.dev/) or to the forum (https://forum.quasar.dev/) for help requests.
Thank you.
