### ISSUE TITLE
[docs] QPullToRefresh throught a picture

### ISSUE THREAD

**Issue by speyou** [quasarframework/quasar#6503]
I just spend a few minutes on something that looked like a bug during my Quasar 0.x to 1.x migration regarding QPullToRefresh.

It used to work perfectly on any of my components in 0.x, but for 1.x I had to add `pointer-events: none;` on my pictures in order for the pull event to register correctly.

I'm not sure it's 100% intended but I'm not that surprised.

So maybe add this information to the doc, or please correct me. :)

Related codepen (img left to badge: no pull, img right to badge pointer events none and pull is working): https://codepen.io/speyou/pen/wvadzeP

**Comment by pdanpdan** [comment]
Imgs are in some browsers (Firefox for sure) draggable. Add `:draggable="false"` to them.

**Comment by speyou** [comment]
You are much smarter than me.
It would be awesome to have a line on the doc about that. :)

**Comment by pdanpdan** [comment]
I'll have to dig through the docs to see where we use drag. If you find other places that need that info please add them in a comment here.

Thank you.

**Comment by speyou** [comment]
Besides the QPullToRefresh page, I don't see anywhere else.
For instance in the tips section?

* If used in conjunction with an `<img>`, you should add `draggable="false"` in order to allow the pull event to register correctly

![image](https://user-images.githubusercontent.com/7300113/75469128-be3b3200-598e-11ea-8178-27258557bcf8.png)

**Comment by rstoenescu** [comment]
Updated docs.
