### ISSUE TITLE
UI elements overlaps on IOS status bar

### ISSUE THREAD

**Issue by josephharveyangeles** [quasarframework/quasar#6507]
**Describe the bug**
Contents of the app overlaps with apple IOS status bar. See attached picture.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. Create any quasar app
2. Put a title and a button inside a q-page
3. Build capacitor for IOS
4. See screenshot below

**Expected behavior**
IOS status bar should not overlap with the contents of the page/s

**Screenshots**
![screenshot](https://cdn.discordapp.com/attachments/631888733863411715/682872320498597903/unknown.png)

**Platform (please complete the following information):**
iOS: 13.3

**Comment by josephharveyangeles** [comment]
Might be related to [Status bar overlays webview on iOS #1277](https://github.com/ionic-team/capacitor/issues/1277)

**Comment by autukill** [comment]
This is not an bug, please configure it according to your project situation.
eg:
.header{
     padding-top: constant(safe-area-inset-top);
     padding-top: env(safe-area-inset-top);
 }

**Comment by josephharveyangeles** [comment]
Closing. There's an existing config under `capacitor.config.json`:`iosStatusBarPadding`. Setting it to true solves this issue.
