### ISSUE TITLE
Allow customization of how errors under QInput are shown (without using the current slots)

### ISSUE THREAD

**Issue by Powersource** [quasarframework/quasar#6514]
**Is your feature request related to a problem? Please describe.**
I want the error message (when something in `rules` fails) under QInput to be right-aligned instead of left-aligned.

![image](https://user-images.githubusercontent.com/1427063/75555844-52fc6900-5a3d-11ea-8feb-21c4d0c678bb.png)

**Describe the solution you'd like**
I don't know what you'd prefer but for me it'd be enough with a prop for putting it on the right. But maybe that's too narrow, maybe you could send the current `rules` error message into the `error` slot with a slot prop (or whatever it's called). Right now I think rendering the error slot is completely up to the user, and the user basically has to reimplement the error logic themselves. Plus you still get the animation bug I describe below.

**Describe alternatives you've considered**
I've tried

```
.q-field__bottom {
    text-align: right;
}
```

which works at first, but the animation when the error disappears still is on the left. Same when you use the error slot.

**Comment by rstoenescu** [comment]
Hi,

I wish I could implement this directly in Quasar, but there are technical difficulties that cannot be currently overcome. Sorry that I need to offer a solution again with custom CSS code.

There are two cases, both have the correct animation: 

1. For standard/borderless types of QInput/QSelect/QField: https://codepen.io/rstoenescu/pen/oNjpaRw

2. For filled/outlined/standout types of QInput/QSelect/QField: https://codepen.io/rstoenescu/pen/ZEbvqwE
