### ISSUE TITLE
Form native submit does not work

### ISSUE THREAD

**Issue by danbars** [quasarframework/quasar#6517]
**Describe the bug**
When a q-form that has `action` and `method` properties is submitted, nothing happens

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/danbars/pen/WNvjaGP

**To Reproduce**
1. Create a q-form. set its `action` property to some url, and set its `method` to `post`
2. Add q-btn to the form, with `type="submit"`
3. try to submit the form

**Expected behavior**
A The form will be URLEncoded and POSTed to the URL in the action.
The entire window should navigate to that URL

**Platform (please complete the following information):**
OS: Mac
NPM: 6.13.6
Browsers: Chrome latest
Quasar: 1.9.4 / 1.9.5

**Additional context**
The documentation about native submit is really not clear:
1. In the form element the example has `method="POST"` although the valid value according to mdn is `post`
2. All the examples in the different input fields say that `When dealing with a native form which has an action and a method...`, but the example itself does not have these properties. Instead it has `@submit="onSubmit" `

I also tried calling a method that does:
`this.$refs.myForm.submit()` which didn't work either.

**Comment by pdanpdan** [comment]
Hello. We'll improve the docs for this, but until that moment:

- use `method="post"` - you are right, the method should be in lowercase (but it doesn't really matter, as the browsers are forgiving)
- add a `@submit="onSubmit"` listener on the QForm
- create a `onSubmit (evt) { evt.target.submit() }` method in the component methods

**Comment by rstoenescu** [comment]
Improvements will come with "quasar" v1.9.7.

**Comment by danbars** [comment]
Works! thanks!
