### ISSUE TITLE
QResizeObserver, include padding, border, and scrollbar sizes

### ISSUE THREAD

**Issue by MadnessTabletop** [quasarframework/quasar#6522]
**Is your feature request related to a problem? Please describe.**
Was working on getting some elements that I had to not grow larger than the page height, Virtual-Scrolls specifically. I was having some trouble getting them to behave and that's when I came across QResizeObserver. Seemed an ideal solution to what I was wanting to do. Use the Observer to grab the height and width of the page, drop it into a store, then reference it in the Virtual Scroll.

The problem however, is that the methods that QResiveObserver uses are getoffsetHeight(), and get offsetWidth(). These functions include the paddings, borders, and scrollbars in their calculations. So if I'm try to size off these values I can overlap with the padding, and depending on the padding still run off the page. And with the QPage padding slot allowing the padding to be variable, it gets tricky.

**Describe the solution you'd like**
I would like to add Padding, Border, and Scrollbar sizes (not actually sure if you can measure a scrollbar size to be honest) into the size object that's returned. That way these measurements can be accounted for.

**Additional context**
I'm willing to make the changes and make the pull request myself, however I wished to discuss the issue before diving into it.

**Comment by pdanpdan** [comment]
One easy solution: listen for the `@resize` event of the observer (that will tell you that something happened) and compute the size in your desired way. This way you have maximum flexibility.

**Comment by MadnessTabletop** [comment]
You know... I'm not quite sure why I didn't think of this myself because that's a good idea.

*Though, my suggestion may still have merit.*

**Comment by pdanpdan** [comment]
I'm leaving this open for @rstoenescu to take a look, but I think it would open a can of worms for how many different things one may need to measure, and it would slow down calculations for all.

**Comment by MadnessTabletop** [comment]
That is definitely true.

Let me know if it's something that is decided is wanted. As stated, I would be happy to do the work for it.
