### ISSUE TITLE
Make ripple click effect optional for mousedown instead of mouseup

### ISSUE THREAD

**Issue by squareloop1** [quasarframework/quasar#6524]
**Is your feature request related to a problem? Please describe.**
This is related to #4901 and #878.

Even though ripple effect is showing on touch device while scrolling may feel "not right" for some people, it is my biggest pain point with Quasar at the moment. It makes the clicks feel very sluggish. All official Google material design apps do the ripple effect on mousedown too. They also have the issue with ripple on scroll for touch devices, but it feels more natural that way and makes the app overall _feel_ subjectively more performant.

**Describe the solution you'd like**
If not reverted to ripple on mousedown, please make it somehow optional if the ripple effect should fire on mouseup or mousedown.

**Describe alternatives you've considered**
If it is somehow possible to globally and easily override the ripple effect to fire on mousedown instead of mouseup for an app it may be already a sufficient solution without adding this as a new feature.

**Comment by ODtian** [comment]
Yes,the way you mentioned is just like the ripple in vuetify. Fortunately, both of  quasar and vuetify use directive to add ripple to elements. So I replaced the ripple directive js file and it work really well. Only trouble is that I need build everything when quasar update and somehow i can't build from source code on my computer(probably my problem)

**Comment by rstoenescu** [comment]
New in "quasar" v1.9.8 -> "early" modifier (or Boolean prop when using Object form).
Some examples:

```html
<q-btn :ripple="{ early: true }" ... />
<div v-ripple.early />
<div v-ripple="{ early: true }" />
```

Looking to also hook a "ripple" prop in quasar.conf.js > framework > config to avoid redeclaring this for each ripple instance, but meanwhile closing this ticket.
