### ISSUE TITLE
QSlideItem Cannot read property 'style' of undefined in RTL mode

### ISSUE THREAD

**Issue by shafiramaki** [quasarframework/quasar#6525]
![Quasar RTL QSlideItem issue](https://user-images.githubusercontent.com/35919418/75604029-3bcb8300-5af2-11ea-9264-deefa960db85.PNG)

QSlideItem is working perfectly without rtl mode but when switching to rtl languages it shows the upper error.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.7
