### ISSUE TITLE
Lags/freeze with 1.9.6 and keep-alive 

### ISSUE THREAD

**Issue by lmfmaier** [quasarframework/quasar#6526]
I have my main router view wrapped in a keep-alive include="components" to cache some heavier components that I want to maintain their state.

As of 1.9.6, the browser (Chrome) becomes laggy and ultimately freezes shortly after using the components in question. Disabling the keep-alive fixes the problem, also reverting to 1.9.4. 

I have yet to dig deeper to locate the exact source of the problem and can't provide any reproducable code, but it's definetely related to the keep-alive with 1.9.6

**Comment by rstoenescu** [comment]
Hi,

Can you try with "quasar" 1.9.6 and "@quasar/app" v1.5.8 and report if there is still a problem? This sure sounds like a vue-router issue and vue-router was upgraded to its latest patch version in "@quasar/app" 1.6.0.

**Comment by lmfmaier** [comment]
Sadly, this also freezes the browser. It only works with framework 1.9.4 or without the keep-alive on the router-view

The component I'm caching is a blog-like article-list and I want to reload the list and maintain its scroll state when the user klicks on an article and then back to the list.

There are most probably other ways to achieve this, but keep-alive is convenient

**Comment by pdanpdan** [comment]
Are you using QIntersection in the components that are being kept alive?

**Comment by lmfmaier** [comment]
Yes, pretty heavily. Not QIntersection, but v-intersection handlers on q-items

**Comment by pdanpdan** [comment]
Then remove the handler for v-intersection in deactivated hook of component and add it back in activated.

**Comment by lmfmaier** [comment]
Removing all intersections from all child components involved in the rendering of the kept-alive view solves the problem.

Will there be a fix for that? I have loads of intersections, e.g. for lazy loading stuff and I don't have activated/deactivated hooks on every component

Thanks!

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.7.

**Comment by lmfmaier** [comment]
Thank you very much!

**Comment by dsl101** [comment]
Sorry—commented on the commit, didn't spot this. Apologies. My comment was:

This has broken my app for some reason, and also the [docs page](https://quasar.dev/vue-directives/intersection#Basic)(so I'm pretty sure it's not just me). Console error is:

In Firefox: `TypeError: e.__vue__ is undefined`
In Chrome: `Uncaught TypeError: Cannot read property '_inactive' of undefined`

**Comment by rstoenescu** [comment]
Fixing...

**Comment by rstoenescu** [comment]
@dsl101 Thanks for reporting this. Fix will be available in "quasar" v1.9.8.
