### ISSUE TITLE
Hot reload doesn't work

### ISSUE THREAD

**Issue by ethicnology** [quasarframework/quasar#6527]
**Describe the bug**
Hot reload doesn't work when i use quasar dev.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. global install quasar CLI
2. create a project
3. quasar dev
4. change code and ctrl+s doesn't reloading the app

**Expected behavior**
When i save on VSCode i expect the app reload

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 13.9.0
NPM: 6.13.7
Yarn: /
Browsers: Firefox
iOS:
Android:
Electron:

**Additional context**
VS Code

**Comment by pdanpdan** [comment]
- don't use node 13, use stable 12
- https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
