### ISSUE TITLE
QBtn: colorHover and iconHover

### ISSUE THREAD

**Issue by matthiasmoier** [quasarframework/quasar#6528]
To enhance the styling of buttons, I’d like to be able to define a color and icon that will be used when the button is hovered/focused (button states `:hover`/`:focus`/`:active`).

**Describe the solution you'd like**
I’d like to be able to define `colorHover` and `iconHover` for QBtns.

**Describe alternatives you've considered**
This can be achieved using workarounds with CSS and/or using `q-icon` inside `q-btn` (as can bee seen in the example). But I think it would be great addition to the Quasar Framework if it could be defined directly on the `q-btn`.

Also, I think that this might enhance the overall user experience. Especially from e design point of view when e.g. there’s a list of items and instead of looking like a wild bunch of M&Ms, the buttons all can all have the same color by default and only change the color on hover … e.g. a delete button to "negative" … or a save button to "positive".

Like this, `colorHover` and `iconHover` can be used to point out important or dangerous actions when the buttons are hovered/focused.

**Examples**
I created a quick example on Codepen to demonstrate the desired behaviour: https://codepen.io/moier/pen/rNVwwqp?editors=1100

**Comment by matthiasmoier** [comment]
Added examples of buttons with text and icons as well as buttons that only show the icon on :hover.

**Comment by rfox12** [comment]
I develop mostly for the desktop.. and you'll start to notice that Quasar seems to be developed primarily mobile-first in mind (I'm OK with that--Quasar is amazing!).  I wanted hover-over and I decided to tackle it with a custom component.  Sharing it... this might be a nice example of how to extend standard components.  I've made my own **HoverButton** component (`HoverButton.vue`) below:
```
<template>
  <q-btn
    @mouseover="setHovering(true)"
    @mouseout="setHovering(false)"
    :color="(hovering && hoverColor !== undefined ? hoverColor : $attrs.color)"
    :icon="(hovering && hoverIcon !== undefined ? hoverIcon : $attrs.icon)"
    v-bind="$attrs"
    v-on="$listeners"
  />
</template>

<script>
export default {
  name: 'HoverButton',
  props: {
    hoverColor: {
      type: String,
      required: false,
      default: '',
    },
    hoverIcon: {
      type: String,
      required: false,
    },
  },
  data() {
    return {
      hovering: false,
    };
  },
  methods: {
    setHovering(tf) {
      if (this.hovering != tf) {
        this.hovering = tf;
      }
    },
  }
}
</script>
```
and then to use it in a parent page or component:
```
<template>
  <q-hover-btn
      flat
      color="grey"
      hover-color="negative"
      icon="delete"
      hover-icon="delete_forever"
      label="hover me"
    />
</template>
<script>
export default {
  ...
  components: {
    "q-hover-btn": require("components/HoverButton.vue").default,
    ...
  },
...
```
You'll notice some magic (`v-bind="$attrs"`) that allows all attributes other than hover-color and hover-icon to get passed through to the q-btn as normal.  Same with events (`v-on="$listeners"`)

**Comment by rstoenescu** [comment]
Hi,

While this seems like a good addition, it would only open up a Pandora's box as more and more properties will require hover equivalents leading to a very bloated component.

However, it's easy to wrap the QBtn component like @rfox12 indicated above (thanks @rfox12 !). This would ensure perf for the most used component in any app.
