### ISSUE TITLE
q-slide-item reseter

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#6529]
reset page dont go back to normal when used `q-slide-item`

<img width="313" alt="Screenshot 2020-03-01 at 14 30 53" src="https://user-images.githubusercontent.com/19895516/75630761-aad9d200-5bed-11ea-924d-2da03a6f879e.png">

<img width="368" alt="Screenshot 2020-03-01 at 18 45 31" src="https://user-images.githubusercontent.com/19895516/75630768-b200e000-5bed-11ea-9577-1055d46be4b4.png">

**Platform (please complete the following information):**
OS: Android & iOS 
Node:
NPM:
Yarn:
Browsers:
iOS: iPhone 6 real device & iPhone XR Max simulator
Android: Pixel 10 emulator 
Electron:

**Comment by pdanpdan** [comment]
Can you please explain with words what is the problem? Thank you.

**Comment by diadal** [comment]
after sliding the red and blue space backgrounds remains

**Comment by pdanpdan** [comment]
Please make a codepen to show how you use it. Thank you.

**Comment by pdanpdan** [comment]
I'll close this for lack of details.
If you have new details please reopen.
Thank you
