### ISSUE TITLE
All dynamic routes are being pre-fetched forcefully (SSR)

### ISSUE THREAD

**Issue by vdraceil** [quasarframework/quasar#6531]
I have my router code set up with dynamic imports as not all pages need to be loaded initially - some routes lead to heavy pages, besides there are a lot of routes.
```
path: 'research'
component: () => import(
  /* webpackPrefetch: false, webpackChunkName: "research" */
  'pages/research/Overview'
)
```
This generates me a **research.js** bundle (implying the magic comment is being picked up at build time), but the prefetch=false doesn't seem to have any effect all.
The research bundle is being pre-fetched even if I visit another totally unrelated route in the browser.

`build.preloadChunks = false` just removes all `<link rel="preload" ...>` and `<link rel="prefetch" ...>` items from the <head>. `true` is the default.

So, all routes are just being pre-fetched for me initially on any page hit.
Any pointers on how to get past this?

**Comment by rstoenescu** [comment]
Hi,

Any repo that I can take a look at which reproduces your problem?

**Comment by rstoenescu** [comment]
Or [codesandbox](https://codesandbox.quasar.dev)

**Comment by hawkeye64** [comment]
@vdraceil `webpackPrefetch: expected true or a number, but received false`

**Comment by vdraceil** [comment]
@hawkeye64 oh yeah, `webpackPrefetch: false` gives that error you mentioned - but only when I do `quasar dev -m ssr`.
With `quasar build -m ssr` the build just succeeds with no errors or warnings.

 Pkg quasar........ v1.9.14
 Pkg @quasar/app... v1.6.2

It was just me trying if `webpackPrefetch: false` would have any effect on my lazy loading; not exactly wanting that to work.

**Comment by vdraceil** [comment]
@rstoenescu Sorry for the delay.

I've made 3 sets of routes /type1/a , /type1/b, /type1/c and same for type2 and type3
With webpack chunks, each of these typeN routes generate their own .js chunks during build.
The routes are to be lazily loaded (I've used dynamic imports in routes.js).

Now, when I do a build, run the app on port 3000 and hit the page http://localhost:3000/type1/a ,
the remaining unrelated chunks - type2.js, type3.js are getting loaded (type2 & 3 are not even children of type1 pages).
They just come up in `<link rel="prefetch" ... >` tags in the type1 page which has nothing to do with these pages (no navigations).
I was thinking with dynamic imports, when I load type1/x page, I'd only have to download the type1.js.xxxxx chunk and not the others.
Let me know if I've misunderstood or doing it all the wrong way.

I just made a demo repo for explaining my issue.
https://gitlab.com/vdraceil/quasar-ssr-lazy-load-routes

```
git clone https://gitlab.com/vdraceil/quasar-ssr-lazy-load-routes.git
cd quasar-ssr-lazy-load-routes
npm i
quasar build -m ssr
cd dist/ssr
npm start
```
then hit http://localhost:3000/type1/a with dev tools Network tab open

**Comment by vdraceil** [comment]
When in `quasar dev -m ssr` only required JS chunks are getting loaded - ex. in /type1/a route only type1.js is loaded.

**Comment by rfox12** [comment]
@vdraceil I tracked this one down...  This isn't a Quasar thing, this is a Vue thing:  

> By default, all assets in async chunks will be prefetched since this is a low-priority directive; however you can customize what to prefetch in order to better control bandwidth usage. This option expects the same function signature as shouldPreload

from https://ssr.vuejs.org/api/#shouldprefetch

Quasar has an undocumented SSR configuration attribute called `preloadChunks`, but it doesn't work as intended.  To remove ALL `<link rel="prefetch" href="/js/type2.911fedb6.js">` type of entries in your SSR pages you'll need to reference the Vue documentation and directly hack the `index.js` file that gets generated (in `dist/ssr` by default)
from:
```
const rendererOptions = {
  template,
  clientManifest,
  // for component caching
  cache: new LRU(settings.componentCache),
  basedir: __dirname,
  // recommended for performance
  runInNewContext: false,
}

if (settings.preloadChunks !== true) {
  const fn = () => false
  Object.assign(rendererOptions, {
    shouldPreload: fn,
    shouldPrefetch: fn
  })
}
```
to:
```
const rendererOptions = {
  template,
  clientManifest,
  // for component caching
  cache: new LRU(settings.componentCache),
  basedir: __dirname,
  // recommended for performance
  runInNewContext: false,
  shouldPrefetch: (file, type) => {
    return false;
  }
}
// This is an unfinished Quasar config flag--let's comment this out
// if (settings.preloadChunks !== true) {
//   const fn = () => false
//   Object.assign(rendererOptions, {
//     shouldPreload: fn,
//     shouldPrefetch: fn
//   })
// }
```
And obviously you could write some smarts into that `shouldPrefetch` if you so desired (you have full control over what gets prefetched).  Hope this helps.

**Comment by rfox12** [comment]
For the Quasar devs.. I'm not certain enough to do a proper PR, when we build this out I would think that we should separate the `preload` from the `prefetch` settings--very different intent right?

**Comment by rstoenescu** [comment]
How is it undocumented?? https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build -> preloadChunks.

This ticket is obsolete. preloadChunk is by default "false" starting with "@quasar/app" v1.8.
No change is necessary like indicated above.

**Comment by rfox12** [comment]
@rstoenescu my bad... I was using (the handy) link in my quasar.conf.js and looking at https://quasar.dev/quasar-cli/developing-ssr/configuring-ssr

I didn't occur to me that this would be a setting that effect other build types!

And indeed I was using the config flag in the wrong place... thus not getting the result I expected.

So... no issue with Quasar.  But it may very well be worth discussion on the last point I made... I don't think, for a large SSR site like mine, that I would want to change shouldPreload and shouldPrefetch in tandem with each other.

**Comment by p1pchenk0** [comment]
@rfox12 sorry for late answer (faced same issue today), but there is a way to customize vue ssr renderer via extension (just an example):
```
module.exports.extendApp = function ({ app, ssr }) {
  if (ssr.mergeRendererOptions) {
    ssr.mergeRendererOptions({
      shouldPrefetch: () => false,
      shouldPreload: (file, type) => type === 'style',
    });
  }
}
```
