### ISSUE TITLE
[QStepper] - Allow to disable lazy loading

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#6535]
In my project, i have a QForm wrapping a QStepper. Many form blocs are dispatched in QStepper's slots. In order to apply properly a full form validation, i need to load every panel. Unfortunaly, it's not currently possible.

I suggest to add a props named `eager` to toggle the default lazy loading off.

Thanks for your great job.

**Comment by pdanpdan** [comment]
Hello. Please validate the data using the models and business rules, not using markup.

**Comment by DaedalusDev** [comment]
Hello...

So please remove the :rules props on all Quasar component... If you are a "Framework", don't provide the wrong way to validate data...

Thanks...

**Comment by rstoenescu** [comment]
@DaedalusDev Hi, thanks for being snarky, disregarding what Dan suggested and proposing to remove a feature just because your edge case doesn't cut it. You're using Vue, so you connect your components with a model. So validate the model instead. The panels cannot be lazy loaded.

**Comment by DaedalusDev** [comment]
Hello,

i'm not trying to be snarky but pragmatic ! I apologize if i hurt you... You were not targeted but :
Previously with Quasar 0.17, all my forms  were validated with Vuelidate. Since 1.0, you provide added `:rules` on every form components, it work very well and i was enthousiast with this feature even if i suspect some possible edge case !

Unfortunaly, i agree with your analyse, i'm exactly on an edge case... Currently panels *ARE* lazy loaded and so your validation (based on call component's instance `validate` method) wont work.

But i prefer your answer, who sound like "sorry, we can't fix your problem for technical reason" than,   "don't use rules props" (sorry for my hard comment @pdanpdan but admit it was awkward).

Since some week, i've wrote a workaround (based on your validation API) and it work very well. I've post that issue because i'm one of your fervent admirers. I follow your project since some years (and i use quasar for 95% of my apps). But i think some quasar's developer can be confronted to this "edge case" and in order ton improve your wonderful project, we can write an elegant workaround.

So, i apologize again...

Your projet rocks ! 🎉

**Comment by rstoenescu** [comment]
@DaedalusDev All good. Sometimes the language barrier can create moments like this. We are all working inhuman number of hours each day to create the best possible product, and practically for coffee money. The accumulated fatigue bubbles up once or twice into inappropriate comments, especially when we detect a possible lack of respect. But bottom line, we're all in the same boat and we work towards making things better together, so let's get on with constructive comments! Go Quasar, go you, because the success depends on both sides.
