### ISSUE TITLE
Master-Detail View

### ISSUE THREAD

**Issue by Batsirai** [quasarframework/quasar#6536]
**Is your feature request related to a problem? Please describe.**
Many Mobile and Desktop interfaces use a Master-Detail List
I would love to see a Quasar Master-Detail List Component - even if its a child of the List Component.

**Describe the solution you'd like**
A list of items with a drill down to a card or container for item details or an item edit form. 
https://cdn.discordapp.com/attachments/596275881907978240/680883002951204873/master-detail-example.png

**Describe alternatives you've considered**
I tried to mix a list component, transition, and card... very hacky.
https://codesandbox.io/s/vue-quasar-master-detail-qhhch

**Additional context**
![master-detail-example](https://user-images.githubusercontent.com/4148235/75707353-bdefaf00-5c8c-11ea-9103-ef54967f6fb0.png)

**Comment by lmfmaier** [comment]
Have you tried putting the detail view for a list item into a layout drawer on the right that expands full screen on mobile devices? I have a similar solution for contact list and it work pretty well

**Comment by pdanpdan** [comment]
Hello. You have all the bricks to do your desired implementation of this pattern. This cannot be a framework component because there are so many implementations possible.
But you can try:
- vertical tabs with tab panels (example in docs)
- router-link with route children in <router-view>
- ...
