### ISSUE TITLE
QUploader - Uploading same file twice

### ISSUE THREAD

**Issue by jd-0001** [quasarframework/quasar#6537]
**Describe the bug**

**BUG 1:** If we upload same file twice or files with same name, uploader component gives duplicate key warning. You can check it in the `multiple` demo of quasar docs.

**BUG 2:** Now if we remove any file from duplicates, all images with that name get removed.

**Codepen/jsFiddle/Codesandbox (required)**
BUG 1: You can check this in multiple [demo](https://quasar.dev/vue-components/uploader#Uploading-multiple-files) in quasar docs
BUG 2: Same

**To Reproduce**

**Bug 1**
1. Go to above link in docs
2. Click on codepen icon
2. In first demo of multiple upload same file twice.
3. Check console.

**Bug 2**
1. Follow above steps and try to remove any of duplicate files.
2. Both files will get removed even if we remove on one.

**Expected behavior**
Files with same name should not give error. This can easily get handled by index. And for removing file, only that file should get removed.

**Screenshots**
![quasar-same](https://user-images.githubusercontent.com/47495003/75760904-1b9ffc00-5d5e-11ea-9a67-dfe5b341f695.gif)

**Platform (please complete the following information):**
OS: Ubuntu
Node: 12
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Chrome
iOS: Not tested
Android: Not tested
Electron: Not tested

**Additional context**
I think index should be used to mitigate duplicate keys warning. For bug-2 index kind of thing should do it.

I love to make PR but I am not yet fully understand how quasar handles same code on all devices. So I can not.

~ Thanks for developing such great framework

**Comment by jd-0001** [comment]
Sorry for the issue. I was trying to make PR and found that it is already handled.

**How:** Files with same name will not be added in uploader.

Closing this.

**Comment by jd-0001** [comment]
It is still not working in package. I checked node_modules folder and found that code is not present in source.

**Comment by rstoenescu** [comment]
What code is not present in the source?

**Comment by jd-0001** [comment]
Hi, @rstoenescu 
repo clone:
![source](https://user-images.githubusercontent.com/47495003/75767548-ff558c80-5d68-11ea-8a88-69c8dd9f0758.jpg)


Node Modules:
![node_modules](https://user-images.githubusercontent.com/47495003/75767562-054b6d80-5d69-11ea-9c04-75184da31478.jpg)

**Comment by jd-0001** [comment]
Duplicate key issue can be mitigated if we use slot and render list on our but removing file still removes files with same name.

**Comment by rstoenescu** [comment]
Then update your project's Quasar version... It means you are on an older version.

**Comment by jd-0001** [comment]
Hello @rstoenescu I am already on latest version 1.9.7. You can check this issue in codepen also if you like.

**Comment by rstoenescu** [comment]
With all due respect, we ship what it is on our repo, not something else. So please figure out why you have other version installed. Thank you.

**Comment by jd-0001** [comment]
Hi @rstoenescu,
Sorry for the trouble. I have inspected the issue and found that this exist in the latest version of the quasar framework.

I have made a clone few days back(or maybe a month). In that version, code was present to prevent duplicates. So, this was the confusion. I am really sorry.

But I am sure that this issue still exist in latest/current version of quasar qUploader. So can you please open this issue again.

~ Thanks for your time :pray:

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.9.
