### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined at Function.getFileName (Webpack)

### ISSUE THREAD

**Issue by kzaiwo** [quasarframework/quasar#6538]
**Describe the bug**
I am getting this error message exactly same as here:
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/333

`when i use usb module on main process, the bindings js report a TypeError

TypeError: Cannot read property 'indexOf' of undefined at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16) at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48) at eval (webpack:///./node_modules/usb/usb.js?:1:112) at Object../node_modules/usb/usb.js (/Users/leehu/Code/circulate/pi-bank2/dist_electron/index.js:5146:1) at __webpack_require__ (/Users/leehu/Code/circulate/pi-bank2/dist_electron/index.js:20:30) at eval (webpack:///./node_modules/@ledgerhq/hw-transport-node-hid/lib/listenDevices.js?:15:12) at Object../node_modules/@ledgerhq/hw-transport-node-hid/lib/listenDevices.js (/Users/leehu/Code/circulate/pi-bank2/dist_electron/index.js:193:1) at __webpack_require__ (/Users/leehu/Code/circulate/pi-bank2/dist_electron/index.js:20:30) at eval (webpack:///./node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js?:21:23) at Object../node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js (/Users/leehu/Code/circulate/pi-bank2/dist_electron/index.js:181:1)`

Replicable when requiring the node_module.
OS: Windows 10
Node: 12.8.1
NPM: 6.10.2
Yarn: n/a
Browsers: Chrome (Electron)
iOS: n/a
Android: n/a
Electron: 7.1.8

According to the github repo, solution is:
`Mark the usb module as an external by setting your vue.config.js to:

// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['usb']
    }
  }
}`

However, I can't seem to find vue.config.js nor its counterpart here in Quasar.
No issues when running directly using node.js (non-quasar setup).

Help!!

--Edit:
Here is another link with the same problem as me:
https://forum.quasar-framework.org/topic/4173/can-t-use-the-serialport-module-building-for-electron

**Comment by rstoenescu** [comment]
Hi,

Please use quasar.conf.js > electron > extendWebpack to add the externals into the Webpack config ;)

**Comment by kzaiwo** [comment]
I tried to add:
`
      extendWebpack (cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/,
          externals: ['usb'],
          options: {
            formatter: require('eslint').CLIEngine.getFormatter('stylish')
          }
        })
      }
`

But it gives an error:
`
(node:23900) UnhandledPromiseRejectionWarning:   WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration.module.rules[11] has an unknown property 'externals'. These properties are valid:
     object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
`

Which option can I use? Thank you!

**Comment by kzaiwo** [comment]
I tried to add:
`
      extendWebpack (cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/,
          options: {
            formatter: require('eslint').CLIEngine.getFormatter('stylish')
          }
        })

        // do something with Electron main process Webpack cfg
        // chainWebpack also available besides this extendWebpack
      }
`

But it gives an error:
`
(node:23900) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

    configuration.module.rules[11] has an unknown property 'externals'. These properties are valid:
    object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
`

Which option can I use? Thank you!

**Comment by rstoenescu** [comment]
quasar.conf.js > electron > extendWebpack (cfg)
`cfg.externals.push('usb')` (out of the top of my head; if it's not this, then head to Webpack docs)

`externals` is a root prop on the Webpack config. What you did is you added it to some webpack rule instead.

**Comment by gjh1** [comment]
> quasar.conf.js > electron > extendWebpack (cfg)
> `cfg.externals.push('usb')` (out of the top of my head; if it's not this, then head to Webpack docs)
> 
> `externals` is a root prop on the Webpack config. What you did is you added it to some webpack rule instead.

this solution not works for me ， how about you？
