### ISSUE TITLE
QSelect Ignoring color for popup-content-style

### ISSUE THREAD

**Issue by vladimirvrabelml** [quasarframework/quasar#6539]
**Describe the bug**
Q-select is ignoring "color" style for popup-content-style property alongside with "dark" property

**jsFiddle**
https://jsfiddle.net/a0vo5wcj/3/

**To Reproduce**
Expand options list of **second** q-select and please observe, that the text color for an options is **not** set to desired color (red)

**Expected behavior**
Expand options list of **first** q-select and please observe, that the text color for an options is set correctly to desired color (red)

**Use case**
Without this fix, there is impossible to proper styling an app, where exists a q-select on dark styled toolbar.

**Comment by hawkeye64** [comment]
@woloda375 I just ran into this myself. The work-around is:

Sass
```css
.popup-content .q-item
  color: #616161 !important
  background: white
```
and then,
JavaScript

```html
popup-content-class="popup-content"
```

**Comment by pdanpdan** [comment]
You mean you want to set `:options-dark="false"`?
https://jsfiddle.net/80u41owk/
