### ISSUE TITLE
[0.14] Issue with leftClass and pageClass on layout

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#654]
Quasar: 0.14
OS: Win10
Node: 8
NPM: 5
Browsers: all
Any other software related to your bug:
`Invalid prop: type check failed for prop "leftClass". Expected Object, got String.`
`Invalid prop: type check failed for prop "pageClass". Expected Object, got String.`

### What did you get as the error?
LeftClass in layout is not working at all. It is not applied.
pageClass is applied but throwing errors.

### What were you expecting?
To leftClass be applied. 

### What steps did you take, to get the error?
`<q-layout ref="layout" pageClass="bg-grey-1 page-padding" leftClass="bg-grey-1">`

It is strange because errors are the same but class are applied to page  container.

**Comment by rstoenescu** [comment]
**It expects an Object** as the error suggests.
Example:
```js
<q-layout ref="layout" :pageClass="{'bg-grey-1': true, 'page-padding': true}" :leftClass="{'bg-grey-1': true}">
```

**Comment by murbanowicz** [comment]
Hi
Thank you.
It's fine but I think somethingClass should expect either Object or String for all components and be consistent? 
E.g. for q-modal-layout `footer-class="bg-primary some-class"` (from docs) so it is confusing.

**Comment by rstoenescu** [comment]
@murbanowicz I agree with you on that. But this is due to performance reasons.
