### ISSUE TITLE
Cookies.set( {..., secure: true }) not working

### ISSUE THREAD

**Issue by kms695** [quasarframework/quasar#6540]
When you use the Cookies helper the option **secure** is currently not working. It does not throw an error but is just not setting the cookie entirely. I noticed it with the warning from Google Chrome:

> A cookie associated with a resource at ... was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`.

What can I do to set the `Secure` option in the cookie while using the Quasar Cookie helper?

- Dev mode.......... pwa
- Pkg quasar........ v1.8.3
- Pkg @quasar/app... v1.5.2

**Comment by rstoenescu** [comment]
The `secure` option means that the cookie will only be sent through HTTPS. Are you on HTTPS? If "yes", then please feel free to reopen.

**Comment by kms695** [comment]
Sorry, my fault!

But I suggest that the [doc here](https://quasar.dev/quasar-plugins/cookies#Option%3A-secure) is updated with the fact that you need to set the `https: true` in your devServer in the quasar.conf.js.

**Comment by rstoenescu** [comment]
It does say: `If true, the cookie transmission requires a secure protocol (HTTPS) and will NOT be sent over HTTP.`....

**Comment by kms695** [comment]
Please improve the doc with the fact that this requires the `quasar.conf.js` to enable the dev server `https: true`. When I forgot it, maybe others will also. This is a strong connection to the config.
