### ISSUE TITLE
Colorful shadow

### ISSUE THREAD

**Issue by ODtian** [quasarframework/quasar#6541]
**Is your feature request related to a problem? Please describe.**
a colorful component with dark shadow doesn't look pretty
**Describe the solution you'd like**
add options in components,like shadow-color

**Describe alternatives you've considered**
none yet, it's too burden

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Sorry but will not add such classes as they will unnecessary bloat Quasar's CSS framework. Nobody would enjoy all possible color combinations for an extra 70-100k of CSS which you can't get rid of.

It's really not hard to write your own shadow classes. You can take a look at Quasar's shadows for inspiration... we're open-source :)
