### ISSUE TITLE
Ripple animation

### ISSUE THREAD

**Issue by ODtian** [quasarframework/quasar#6543]
**Is your feature request related to a problem? Please describe.**
A real material design ripple,which have a good implement in vuetify

**Describe the solution you'd like**
I just try to replace the ripple directive js file,and it's work perfectly.

**Describe alternatives you've considered**
Just like above,but i must build everything when the framework update

**Additional context**

**Comment by pdanpdan** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/6524

**Comment by squareloop1** [comment]
Also related: https://github.com/quasarframework/quasar/issues/6593
To further improve the ripple effect.
