### ISSUE TITLE
Tooltip doesn't show on disabled buttons

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#6544]
**Describe the bug**
The tooltip doesn't show on disabled buttons.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mesqueeb/pen/PoqKXLb?editable=true&editors=101

**Expected behavior**
The tooltip should show.

My use case is that I'm explaining to the user why a button is disabled. I want to explain this via a tooltip.

**Comment by pdanpdan** [comment]
A disabled <button> does not emit native events, so it's the expected behavior.
Either use `<q-btn type="a" />` or wrap the QBtn in a div and place the tooltip in the div:

```html
<div>
  <q-btn ... />
  <q-tooltip> ... </q-tooltip>
</div>
```
