### ISSUE TITLE
Save event for q-input for periods of inactivity

### ISSUE THREAD

**Issue by DelaneDiamon** [quasarframework/quasar#6547]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Emit @save/saving event on blur/interval of inactivity (time since last @input/@change) event for a user to be able to perform a request to a backed to save input provided, but not finished (any feedback/post/comment system). 

**Describe alternatives you've considered**
Implementing it myself with @blur handler, setting/re-setting setInterval for @input/@change event.

Small notification with any custom message would be also nice, but that can be done in @save event with QNotify anyway.

**Comment by rstoenescu** [comment]
Hi,

Sorry but this is pretty custom. It shouldn't be done in the framework but in devland.
