### ISSUE TITLE
'Unknown custom element' error when importing all components

### ISSUE THREAD

**Issue by opichon** [quasarframework/quasar#655]
### Software version

Quasar: 0.14
OS: OSX Sierra
Node: 8.1.2
NPM: 5.0.3
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
In browser: `Unknown custom element q-layout, q-toolbar, etc.`
 
### What were you expecting?
No errors

### What steps did you take, to get the error?
App vue template contains the example layout from the docs.

main.js imports all components as per docs

```
require(`quasar/dist/quasar.${__THEME}.css`)
// ==============================

import Vue from 'vue'
import Quasar, * as All from 'quasar'
import router from './router'

Vue.use(Quasar, {
  components: All,
  directives: All
})

Quasar.start(() => {
  /* eslint-disable no-new */
  new Vue({
    el: '#q-app',
    router,
    render: h => h(require('./App'))
  })
})
```

**Comment by rstoenescu** [comment]
I just tested it again and it works. Are you sure you are using v0.14? A repo I can take a look?

**Comment by OckhamRazor** [comment]
First of all, please forgive my English is not very good
I encountered this problem, the use of npm installed quasar-framwork, missing a lot of components in the source file, such as q-btn, including the release version also has this problem. But this component exists on the development branch.

Please confirm that I did not understand, or really is a problem

**Comment by rstoenescu** [comment]
Please reopen if you used the v0.14 beta starter kit (`quasar init default#beta <folder>`) or ported the minimal required changes to your current project folder and it still does not works.

I am very confident when I say this works, but please reopen if I missed something. Thanks!
