### ISSUE TITLE
Message Component

### ISSUE THREAD

**Issue by brsanthu** [quasarframework/quasar#6551]
**Is your feature request related to a problem? Please describe.**
Problem is when we are implementing forms with server interaction, and if there is any error, we want to show the message within the form itself. As of now, quasar provides Notify component that shows message defined places but we want to show message inline so it goes with context.

**Describe the solution you'd like**
Message component that support type of message (info, warning, success and error) and renders in place.

**Describe alternatives you've considered**
Notify component or implement our own

**Additional context**
https://vuetifyjs.com/en/components/alerts

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/banner#Introduction
