### ISSUE TITLE
[QSelect] - use-chips allows modification of readonly component

### ISSUE THREAD

**Issue by HaisojYellams** [quasarframework/quasar#6555]
**Describe the bug**
A QSelect component that using `use-chips` and `readonly` is still able to be modified by removing the chip.

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/Haisoj-yellams/pen/eYNGrKV](https://codepen.io/Haisoj-yellams/pen/eYNGrKV)

**To Reproduce**
1. Go to the [codepen](https://codepen.io/Haisoj-yellams/pen/eYNGrKV) provided.
2. Click on the `x` button on a chip to delete it.
3. The readonly select is modified.

**Expected behavior**
If the parent QSelect is set to 'readonly' the chips within the component should not be able to be clicked/removed.

**Platform (please complete the following information):**
OS: Fedora (Linux 5.5.7-200.fc31.x86_64)
Node: v12.15.0
NPM: 6.13.7
Yarn: 1.22.0
Browsers: Chrome (Version 80.0.3987.132 (Official Build) (64-bit))

**Additional context**
I know this issue can be "handled" by not using the chips when in readonly mode (like the bottom section of the provided codepen), but I like the look of the chips and it adds better readability (in my opinion) of the options selected especially in the rare case where the options themselves contain commas (as in the example). 

I also understand that developers can also use the `selected-item` slot to create custom chip behavior, but if the only behavior being changed is the `removable` prop on the chip itself, I'm not sure that it merits using the slot.

If it is not desired for the the chip's `removable` prop to be dependent on the QSelect's `readonly` prop, maybe an addition `chip-removable` prop could be added to the QSelect instead.

If this is indeed a bug that needs fixed (and not just me being ignorant), and you would like me to attempt to create a pull request to fix this, let me know. Thank you for your time!

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.9
