### ISSUE TITLE
custom filter function for autocomplete to perform fuzzysearch etc

### ISSUE THREAD

**Issue by mygnu** [quasarframework/quasar#656]
I have a case where I'm trying to auto complete some names, user should be able to do fuzzy matching rather than matching the first name with  just ```startswith()```.
I found this [fuzzy sarch](https://github.com/bevacqua/fuzzysearch) implementation that I would like to use.
I suggest the following optional porp for the auto-complete component where you provide custom filter with the same signature as the inbuilt one.

```html
<q-autocomplete 
:static-data="{field: 'name', list:myList }"  :filter='myFilter'
          @selected="selected" />
```
filter function
```javascript
myFilter(terms, { field, list }) {
      const token = terms.toLowerCase();
      return list.filter(item => fuzzysearch(token, item[field].toLowerCase()));
    },
```
PR to follow :)

**Comment by rstoenescu** [comment]
PR merged. Thanks! Looking forward to docs update.
