### ISSUE TITLE
QEditor toolbar buttons cannot be activated at the same time

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#6568]
**Describe the bug**
If you want to (for example) write an italic bold underlined message, you can select one and write, then select another, but you cannot select all three of them and write something. Also, same problem for removing them.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/editor#Example--Default-editor

**To Reproduce**
1. Go to https://quasar.dev/vue-components/editor#Example--Default-editor
2. Click on the editor
3. Click on the bold icon and on the underline icon for example
4. Bold icon gets disabled

**Expected behavior**
It would select both the bold icon and the underline icon.

**Comment by prophe05** [comment]
+1

**Comment by pdanpdan** [comment]
We will not implement this in core. Please use an external html editor for more complex things.
