### ISSUE TITLE
APP: first tab is cut when multiple tabs width is larger than screen width 

### ISSUE THREAD

**Issue by nulele** [quasarframework/quasar#6573]
**Describe the bug**
I have created a component with this tabs. The first is always cut, even if another tab is selected. The last one always works well. Obviously the problem occours in portrait mode or when the tabs width doesn't fit the screen width.

```
  <q-tabs
    v-model="tab"
    inline-label dense
    class="bg-primary text-white shadow-2"
  >
    <q-route-tab"
      label="Presenze"
      :to="{ name: 'event-calls' }"
      name="event-calls"
      exact
    />
    <q-route-tab"
      label="Immagine"
      :to="{ name: 'appearance' }"
      name="appearance"
      exact
    />
    <q-route-tab "
      label="Opportunità"
      :to="{ name: 'opportunities' }"
      name="opportunities"
      exact
    />
    <q-route-tab"
      label="Check-list"
      :to="{ name: 'check-list' }"
      name="check-list"
      exact
    />
    <q-route-tab"
      label="Tempistiche"
      :to="{ name: 'timings' }"
      name="timings"
      exact
    />
  </q-tabs>
```

And I use it in other components...

```
<q-pull-to-refresh @refresh="refresh">
    <q-page class="">

      <EventTabs selected-tab="event-calls"></EventTabs>

      ...
```

**Expected behavior**
The first tab should be visibile

**Screenshots**
This is the initial state on iOS
https://ibb.co/GCWJ1WY

and on Android
https://ibb.co/8N3wDtJ

**Platform (please complete the following information):**
OS: Darwin(19.3.0) - darwin/x64
Node: 10.16.0
NPM: 6.9.0
Yarn:  1.19.1
@quasar/cli - 1.0.2
iOS: any version
Android: any version

**Comment by pdanpdan** [comment]
Can you scroll the list of tabs? I think we need an example that can reproduce the problem, because in my tests it looks good.

**Comment by nulele** [comment]
Yes I can scroll the list but the first tab is always cut.
Gosh, you're right but my app is quite complex and I don't know how to reproduce the problem... :(
Maybe I can arrange a layout + some pages and see what happen... please, give me a few days before closing the issue.

**Comment by pdanpdan** [comment]
Sure, take your time. Thank you.

**Comment by nulele** [comment]
Ah-ha! While I was working on a very very very simplified version of my app, I found out some custom css in Layout.vue that were interfering with my tabs component. After a little fix now the first tab is perfectly visibile... 

**buuuuut**... 

I've noticed that when I click/touch the last tab, the corresponding page loads but the QTabs "reset" itself and the last tab, although selected, is out of the screen and not visible... so, is there a way to auto scroll the QTabs to the selected tab?
Consider that my tabs component is not in the layout but included in every tab page.

Thanks!

**Comment by pdanpdan** [comment]
:( I cannot reproduce this either in our tests - a reproduction case would really help.
The only thing I could find is a possible 1px offset for the selected tab (that makes the right arrow still be visible when the last tab is selected), but nothing else.

**Comment by nulele** [comment]
Hi, in my simplified version that problem doesn't happen so it's definitely something related to my app... I'm doing some experiments but can't figure out what is the problem. Anyway the "bug" isn't a bug anymore so I can close this issue.
Many thanks!!!
