### ISSUE TITLE
For help! Custom quasar perfetch reports an error

### ISSUE THREAD

**Issue by a599155162** [quasarframework/quasar#6576]
Hi~ For help!

package.json
`"@quasar/app": "^1.6.0",`
`"@quasar/extras": "^1.5.2",`
`"quasar": "^1.9.8"`
`"typescript": "^3.8.3"`

quasar.conf.js 
 `supportTS: true`
 `preFetch: true`

Previously there were no errors with the `@quasar/typescript` plug-in

![企业微信截图_15836745205238](https://user-images.githubusercontent.com/28429119/76163890-2d7e0680-6185-11ea-828e-2df946c0c37c.png)
![企业微信截图_15836745934920](https://user-images.githubusercontent.com/28429119/76163892-2f47ca00-6185-11ea-98ff-36acb1a68488.png)

thx!

**Comment by rstoenescu** [comment]
@IlCallo can you clarify here pls? Thx.

**Comment by IlCallo** [comment]
For the first screenshot, TS is inferring your promises as returning `unknown` (and they return an array, because that's what `Promise.all` do), it's up to you to make it infer void or force it with a type cast.

I cannot understand what you're asking about the second screenshot, can you explain it better?

Without other info I don't really know why you got this error now. Maybe you didn't had `strict: true` before in your tsconfig?

Always keep in mind that you can override the Quasar TS configuration options by adding them into your `tsconfig.json`

**Comment by a599155162** [comment]
`quasar/app 1.6` build-in TS
img 1: Return not supported `Promisi.all`
img 2: Try to customize the prefetch interface

plug-in `@quasar/typescript` My custom interface is fine

Sorry, my English is not very good  (╥﹏╥)

**Comment by a599155162** [comment]
tsconfig.json
`{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "strict": true,
    "allowJs": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "quasar"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "./src/**/*"
  ]
}
`
customize the prefetch interface
`export interface PreFetchOption {
  store: STORE
  ssrContext: SSRContext
  currentRoute: Route
  redirect: Function
}

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    preFetch?: (options: PreFetchOption) => void | Promise<void>,
    meta?: object | ((this: V) => object)
  }
}
`

**Comment by IlCallo** [comment]
**Problem 1**
Because of how `Promise.all` is typed, it will always return a promise of an array, while we expect a `Promise<void>`.
There are multiple solutions:
- you can cast the promise to be the one we need like this

```ts
  preFetch(context) {
    return Promise.all([
      new Promise((res, rej) => {
        res();
      })
    ]) as unknown as Promise<void>;
  },
```

- you can use async/await to reduce the type to `Promise<void>` like this

```ts
  async preFetch(context) {
    await Promise.all([
      new Promise((res, rej) => {
        res();
      })
    ]);
  },
```

- we can change the accepted return type to `Promise<{}>`, which will accept pretty much everything (even `void[]` and `unknown[]`)

**Comment by IlCallo** [comment]
**Problem 2**
That's just standard TypeScript stuff: you cannot augment an already defined method with a conflicting interface.
Anyway you made me noticed the context has not been typed properly, I'll fix that :)

**Comment by a599155162** [comment]
thx~

**Comment by IlCallo** [comment]
Let's keep this open until the related PR is merged :)

**Comment by wowissu** [comment]
hi, I try your example  
```js 
 async preFetch(context) {
    await Promise.all([
      new Promise((res, rej) => {
        res();
      })
    ]);
  },
```
this got error "Type 'Promise<void>' is not assignable to type 'Promise<{}>'."
maybe add it on ? 
<img width="742" alt="Screen Shot 2020-04-22 at 1 48 21 PM" src="https://user-images.githubusercontent.com/12434914/79945224-ef704400-849f-11ea-8887-453ce94e38de.png">

and another question 
where I can define <TStore> 
<img width="374" alt="Screen Shot 2020-04-22 at 1 58 21 PM" src="https://user-images.githubusercontent.com/12434914/79945858-55a99680-84a1-11ea-9e58-b9d708750179.png">
<img width="662" alt="Screen Shot 2020-04-22 at 1 58 50 PM" src="https://user-images.githubusercontent.com/12434914/79945886-665a0c80-84a1-11ea-80a7-3d39b816ce72.png">

thx!

**Comment by IlCallo** [comment]
@wowissu hey!
I checked and something is definitly not working.
I'll add `Promise<void>` as possible return type.

On the usage, it's true that generics cannot be used in that way because of syntactic limitations of TS.
Unluckily, the only way I came up with, given that it's an augmentation of Vue options types, is to use a wrapper function to make it work.
You can test this pattern adding

```ts
type PrefetchCallback<TStore = any> = (
  options: PreFetchOptions<TStore>
) => void | Promise<void> | Promise<{}>;

function prefetch<TStore>(callback: PrefetchCallback<TStore>) {
  return callback;
}

export default defineComponent({
  // ...
  preFetch: prefetch<{ prop1: string }>(({store}) => {
    // ...
  })
  // ...
});
```

Tell me what do you think

**Comment by IlCallo** [comment]
For Vue 2.x this is pretty much all we can offer, even Vuex augmentation is nothing more than a

```ts
declare module "vue/types/options" {
  interface ComponentOptions<V extends Vue> {
    store?: Store<any>;
  }
}
```

Because we cannot add a new generic into an augmentation and we are forced to use the augmentation to add a Vue option

**Comment by wowissu** [comment]
```ts
declare module "vue/types/options" {
  interface ComponentOptions<V extends Vue> {
    // https://github.com/quasarframework/quasar/issues/6576#issuecomment-603787603
    // Promise<{}> allow nearly any type of Promise to be used
    preFetch?: (options: PreFetchOptions<Vue['$store']>) => void | Promise<void> | Promise<{}>;
  }
}
```
maybe ?

**Comment by IlCallo** [comment]
I think that won't help.
As I wrote in my previous comment you'd just get the `Store<any>` type, due to Vuex typings

**Comment by wowissu** [comment]
I follow your way and

![image](https://user-images.githubusercontent.com/12434914/80006146-15750300-84f7-11ea-97d5-d7d8322e333d.png)

Am I missing something ?

**Comment by IlCallo** [comment]
I probably also changed something into `@quasar/app` :thinking: 
Can you replicate locally the changes I did in the PR?

**Comment by rstoenescu** [comment]
Fix will be available with "quasar" v1.9.16.

**Comment by a599155162** [comment]
hi~ I'm back again.   :)
The upgrade to Typescript 3.9.3

![image](https://user-images.githubusercontent.com/28429119/83606002-75a59d00-a5ab-11ea-98af-4e3a0791e7fe.png)


```
{
 "typescript": "3.9.3", 
 "@quasar/app": "1.9.5",
 "quasar": "1.12.2"
}

ERROR in /mnt/f/Teleone-Frontend/Vue-Typescript-Quasar-sample/node_modules/@quasar/app/types/boot.d.ts(1,23):
TS2724: Module '"quasar"' has no exported member 'HasStoreParam'. Did you mean 'HasSsrParam'?
ERROR in /mnt/f/Teleone-Frontend/Vue-Typescript-Quasar-sample/node_modules/@quasar/app/types/configuration.d.ts(1,10):
TS2724: Module '"quasar"' has no exported member 'QuasarContext'. Did you mean 'QSsrContext'?
ERROR in /mnt/f/Teleone-Frontend/Vue-Typescript-Quasar-sample/node_modules/@quasar/app/types/configuration.d.ts(1,25):
TS2305: Module '"quasar"' has no exported member 'QuasarConf'

```

**Comment by rstoenescu** [comment]
@a599155162  Do not manually add "typescript" dependency on your own. Let Quasar handle it.
v3.9.x has some bugs that were not yet fixed. So we are running with v3.8.3

**Comment by a599155162** [comment]
@rstoenescu  thx~
