### ISSUE TITLE
https://quasar.dev/options/transitions  how to use transition in router docs not cleat 

### ISSUE THREAD

**Issue by nkb-bd** [quasarframework/quasar#6577]

**Comment by nkb-bd** [comment]
https://quasar.dev/options/transitions

**Comment by pdanpdan** [comment]
https://www.google.com/search?q=vue+router+transitions&oq=vue+router+transitions&aqs=chrome..69i57j0l3.7958j0j7&client=ms-android-huawei&sourceid=chrome-mobile&ie=UTF-8
