### ISSUE TITLE
q-btn inside column

### ISSUE THREAD

**Issue by matro-skin** [quasarframework/quasar#6578]
**Describe the bug**
If `q-btn` is placed inside `column`/`col` - its height becomes 100% of container

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/matro-skin/pen/poJdBjJ

**Expected behavior**
Normal height of button.

**Comment by pdanpdan** [comment]
This is the normal behavior (the same happens to a native element). Add a self-... class on QBtn or a justify-... class on the container to make it not stretch to 100% height.
