### ISSUE TITLE
Placeholder prop for QEditor

### ISSUE THREAD

**Issue by tanthammar** [quasarframework/quasar#6579]
Please add these props from QInput to QEditor:

- label
- hint
- placeholder 
- error-message
- error
- clearable

**Comment by rstoenescu** [comment]
Hi,

You can wrap it with a [QField](https://quasar.dev/vue-components/field). This is what it was created for: to wrap anything you want with it and benefit from those props that you mentioned + many more.

**Comment by Medhyena** [comment]
Placeholder doesn't work with the [QField](https://quasar.dev/vue-components/field) and the [QEditor](https://quasar.dev/vue-components/editor), I didn't try for the others, but this is a legit question.
Maybe because the editor is a "<div></div>" string when "empty"

**Comment by rstoenescu** [comment]
Will be available in "quasar" v1.9.12.
