### ISSUE TITLE
I can't react to tab changes inside q-tab-panel

### ISSUE THREAD

**Issue by turigeza** [quasarframework/quasar#6580]
**Describe the bug**
When one passes down a the model of `q-tab` to a component inside `q-tab-panel` as a prop you can not watch that prop inside your component. As a result one can not easily react to tab changes inside `q-tab-panel`.

Short discussion on forum is here:
https://forum.quasar-framework.org/topic/5401/reacting-to-tab-changes-within-tab-panel

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/turigeza/pen/KKpXerr

**To Reproduce**
1. Go to https://codepen.io/turigeza/pen/KKpXerr
2. Open the console. 
3. Click on any of the tabs.
4. You should have the tab logged to console because it is watched by the component and passed down as prop. 

**Expected behavior**
I am expecting the watcher in the pen on `globalComponent`  to log to the console as the tab changes.

**Platform (please complete the following information):**
OS: macOS 10.15
Browsers: 80.0.3987.122

**Comment by pdanpdan** [comment]
You are not using the global components anywhere. For help requests please head to the forum or discord chat, and also to Vue documentation.

**Comment by pdanpdan** [comment]
Sorry, misread.

**Comment by turigeza** [comment]
@pdanpdan 
Thank you for that explanation it now make sense. Not desirable but make sense : )

Mounted hook will only work if you don't use keep-alive on tab panels (the documented keep-alive and not Vue's built in one) and it is not a replacement for watching the tab model change in that case.  

I also think this is an odd enough behaviour worth mentioning in the docs near 
https://quasar.dev/vue-components/tab-panels#Usage

How can I react to changes to the tab model inside tab panel if I use keep-alive ? 

I realise this is now not a bug and more of a question in this case the original link to my question here on the forum:

https://forum.quasar-framework.org/topic/5401/reacting-to-tab-changes-within-tab-panelI 
I would be grateful for anyone who know just to drop a one liner ... Thank you.

**Comment by pdanpdan** [comment]
If you use `keep-alive` then use the `activated` hook in the `QTabPanel` - it's the same as `mounted` but it's called when the inactivated component comes alive.
It's the same situation - if the hook is called that means that the model (tab) has changed and points to the current QTabPanel.
