### ISSUE TITLE
InstallAPI.js fails on JSON5

### ISSUE THREAD

**Issue by rmehner** [quasarframework/quasar#6582]
**Describe the bug**
JSON5 (comments in JSON) break extension installer

**To Reproduce**

I've stumbled across an issue trying to install this package with: `quasar ext add @quasar/typescript`.

When I choose "Yes" for the VSCode question, the installer bails out with this error:

`UnhandledPromiseRejectionWarning:   SyntaxError: vscode/settings.json: Unexpected token } in JSON at position 524`

This is caused by a trailing comma in the existing `settings.json`:

```json5
{
  "[vue]": {
    "editor.formatOnSave": true,
    // trailing comma here
    "editor.formatOnPaste": true,
  },
  "eslint.validate": [
      "javascript",
      "javascriptreact",
      "vue"
  ]
}

```

This is not valid JSON, but it is valid [JSON5](https://json5.org) which VSCode is using for their setting files.

Full Log:
<details>
? Please choose how to derive webpack: Use the fork-ts-checker-webpack-plugin module for type-checking (recommended)
? Rename .js files to .ts (experimental) Yes
? Will you use VSCode for this project? (Adds ESLint and Vetur configuration quirks, you must manually install the extensions) Yes
? Generate prettier configuration (ESLint and VScode, if used)? Yes

 app:extension-manager Updating /quasar.extensions.json for "@quasar/typescript" extension ... +21s
 app:extension Running App Extension install script... +16ms
(node:21189) UnhandledPromiseRejectionWarning:   SyntaxError: vscode/settings.json: Unexpected token } in JSON at position 524

  - JSON.parse

  - loader.js:987 Object.Module._extensions..json
    internal/modules/cjs/loader.js:987:27

  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32

  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14

  - loader.js:849 Module.require
    internal/modules/cjs/loader.js:849:19

  - helpers.js:74 require
    internal/modules/cjs/helpers.js:74:18

  - InstallAPI.js:214 InstallAPI.extendJsonFile
    [frontend]/[@quasar]/app/lib/app-extension/InstallAPI.js:214:48

  - install.js:42 module.exports
    [frontend]/[@quasar]/quasar-app-extension-typescript/src/install.js:42:9

  - Extension.js:326 Extension.__runInstallScript
    [frontend]/[@quasar]/app/lib/app-extension/Extension.js:326:11

  - Extension.js:163 Extension.install
    [frontend]/[@quasar]/app/lib/app-extension/Extension.js:163:30

(node:21189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</details>

**Platform (please complete the following information):**
OS: macOS 10.14.6
Node: 12.16.1
NPM: 6.13.4
**Additional context**
Original issue: https://github.com/quasarframework/app-extension-typescript/issues/42

**Comment by IlCallo** [comment]
Seems like it's not JSON5, but rather just JSON with Comments and some more quirks, and they have their own parser for it.
https://code.visualstudio.com/docs/languages/json#_json-with-comments

Seems like typescript actually expose the parser function as `require('typescript').parseConfigFileTextToJson()`, I'm gonna try to use it to solve the issue, giving that we already have `typescript` as a dependency of `@quasar/app`

**Comment by IlCallo** [comment]
Angular CLI uses a [custom parser](https://github.com/angular/angular-cli/blob/1e258317b1f6ec1e957ee3559cc3b28ba602f3ba/packages/angular_devkit/core/src/json/parser.ts#L650) when normal `JSON.parse` fails.
Reading the JSONC is pretty easy, the hard part is to rewrite it while keeping comments in place :sweat_smile:

**Comment by IlCallo** [comment]
I found [an issue on JSON5 repo](https://github.com/json5/json5/issues/177) to do exactly what we need. But it hasn't been implemented yet.

Right now, I think the benefit of supporting JSON human-readable flavors isn't worth the effort.
I'll fallback to provide a more useful and not-blocking error in some way.
