### ISSUE TITLE
q-infinite-scroll 

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#6585]
I use q-infinite-scroll  for listing several datas , with a filter.
When there is no filter , when I loaded all data , I call done(true) in my @load -> function(index, done) , 
Now I want to filter with new call my backend , I do : 
this.$refs.virtualScroll.reset()
this.$refs.virtualScroll.resume()

Bu reset , not reset the fact that i called once done

**Comment by pdanpdan** [comment]
Call them on ref to QInfiniteScroll, not virtualScroll.
For help requests please head to discord channel or to forum.
Thank you.

**Comment by vijaypadala94** [comment]
I use q-infinite-scroll for listing several datas , with a filter.
When there is no filter , when I loaded all data , I call done(true) in my @load -> function(index, done) ,
Now I want to filter with new call my backend ,

this not wring this.$refs.virtualScroll.reset()
this.$refs.virtualScroll.resume()
