### ISSUE TITLE
[docs] Theming Examples

### ISSUE THREAD

**Issue by razbakov** [quasarframework/quasar#6586]
On introduction page it states that

> You get a state of the art UI (that follows Material Guidelines) for your websites and apps out of the box

Material Design doesn't mean exactly default styles as they shown, there are [7 material studies](https://material.io/design/material-studies/about-our-material-studies.html) (read themes) available on the official documentation.

What are the best practices in theming Quasar? Are there any good examples, where app doesn't look like default? What are the recommendation to workflow between designer and developer while creating a theme?

**Comment by rstoenescu** [comment]
Hi,

We are working on Quasar Themes and will post updates as we get closer to releasing them.

**Comment by razbakov** [comment]
Would be great to have this issue open until then.
