### ISSUE TITLE
A QComment component

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/quasar#6589]
Hello, 
I was thinking that it would be nice to have a component dedicated to comments and their replies.
I think it would be a great addition to the framework. Some frameworks like [Uikit](https://getuikit.com/docs/comment) and [ant-design](https://ant.design/components/comment/)
have a comment component. If it can help with ideas about the implementation.

**Comment by rstoenescu** [comment]
Hi,

This would be a pretty custom component and would open up a can of worms if added. Quasar already has everything baked in to build any UI, so please use it to create the component that perfectly fits your needs. Layouting something like that is pretty easy.
