### ISSUE TITLE
Keyboard navigation support for q-table

### ISSUE THREAD

**Issue by Olafxso** [quasarframework/quasar#6590]
Hi,

I would like to navigate through a q-table use the arrow keys. 
Pressing arrow down the next row must be selected.
Pressing arrow up the previous row must be selected.
 
Would this be possible?

**Comment by pdanpdan** [comment]
Sure, you need to add event listeners for keydown (or keyup if you don't want repeat) and change the current selected row based on the keys that are pressed.

https://codepen.io/pdanpdan/pen/NWqyppJ

**Comment by Olafxso** [comment]
@pdanpdan Thanks. I'am trying to put it in my code, but @keydown.native="onKey" does not trigger the onKey method. Any idea's what could be wrong? I am using quasar 1.9.4 now.
I don't see a @keydown event available in the qtable api doc also. Is it new and not available yet?

**Comment by pdanpdan** [comment]
`@keydown.native` is listening to the native keydown event in the dom element. Can you make a codepen with what you did?
Try to add a console.log as the first line in onKey and check if it is triggered - maybe it's rejected by the first if.

**Comment by Olafxso** [comment]
@pdanpdan I have got it working. There must a tabindex added to the table also. Otherwise it cannot get the focus.

I have got one small repaint issue. I want to use it in a fullheigth table and sticky header, without pagination. I have added `this.$refs.myTable.scrollTo(index)` where the selected item is set in the onKey method. This works, but when there are more then 80 rows in the table and the table height is greater then 800px the first 4 lines remains blurry. 

Check this code pen to see the problem in action: https://codepen.io/olafxso/pen/XWbZOOY 
Select a row in the table and use the arrow key down to scroll.

![Image1](https://user-images.githubusercontent.com/29576321/76506915-348a6a80-644c-11ea-9d2f-1c8096a28436.jpg)

Any idea's?

**Comment by pdanpdan** [comment]
I think you need to set `:virtual-scroll-item-size="30"` and `:virtual-scroll-slice-size="80"`.
Adjust the values as needed:
- virtual-scroll-item-size is the height of a row (height for how much space to precalculate for one item) - in the example it is 30px (from inspector)
- virtual-scroll-slice-size is the minimum number of items to render - in your case it looks like the auto detection based on screen height / item size fails and sets a too small value - set it to something twice as large as the greatest number of rows expected to fit on screen
