### ISSUE TITLE
Q-Table support Card Row Class and Style

### ISSUE THREAD

**Issue by ttquoccuong** [quasarframework/quasar#6591]
**Is your feature request related to a problem? Please describe.**
[q-table] using grid. In case, we need to add class to row of card.
ex: i want to add class `flex justify-between` to show row label&content between without using slot

**Describe the solution you'd like**
Just add two attribute for card-row: card-row-class and card-row-style same with card-class and card-style

**Comment by rstoenescu** [comment]
Hi,

Props already available: card-container-class (String/Array/Object) and card-container-style (String/Array/Object).

**Comment by ttquoccuong** [comment]
Hi,

card-container-class apply for `q-table__grid-content` and  card-class apply for `q-table__grid-item-card`.
I mean I think we should have a attribute to add class for `q-table__grid-item-row`.

I have created a pen. please see [here](https://codepen.io/ttquoccuong/pen/bGdLBgE)

I think attribute name maybe: `card-row-class` & `card-row-style` :D
<img width="1264" alt="Screen Shot 2020-03-11 at 16 25 33" src="https://user-images.githubusercontent.com/7381858/76401720-f2621a00-63b4-11ea-8df7-254693dfc6ec.png">


Thank you for best work!
