### ISSUE TITLE
material ripple

### ISSUE THREAD

**Issue by ODtian** [quasarframework/quasar#6593]
**Is your feature request related to a problem? Please describe.**

#6524 #6543 #4901 #878

Hello, in fact you may have seen me post many issues about the ripple. Actually what I want to do now is to supplement my needs and the reason I want it. 

Let me first explain the ripple animation I am referring to. 

It should be an interactive process. When you click the button (or some other element), the ripples will appear, and when you quickly click multiple times, the ripples will overlap, and if you just hold down the mouse,  Finally, a mask is left on the button, and when you release the mouse, the mask will slowly disappear. 

This animation is actually the de facto standard in front-end frameworks, including Angular material, react material and vuetifyjs, as well as many front-end frameworks, and of course Android.  

This shows that it makes sense to do this. First of all, its logic is clearer, because it distinguishes between raise and non-click states more deeply, users get better feedback, and on the other hand, the animation is more perfect, because it is fully implemented into the process of clicking, making everything look smoother.  

I always hope to integrate this ripple animation into the quasar framework. I also made some attempts and succeeded. I transplanted the ripple directive in vuetifyjs into quasar, which perfectly fits all places, but this 's troublesome, and due to this way is broken, I have to use other libraries to achieve this goal, to be honest it is bloated and ineffective. 

Ripple animation is one of the most attractive places in material design. And Quasar is also my favorite front-end framework. I hope to see the perfect look of ripple animation in quasar.  Of course, today's ripple can also provide users with a good experience, so this is not an immediate request, I just hope to see it in future plans.  
One more thing:this kind of ripple doesn't feel wrong on touch screen,it have same experience both on desktop and mobile phone

have a nice day

**Describe the solution you'd like**

 I have looked the code of quasar's ripple directive and the vuetifyjs's, and compared them. The difference is not so big, so this should not be difficult to implement.listen to the mouseup event to remove the ripple should be work.

**Describe alternatives you've considered**
 Use the ripple directive of vuetify js, but this is not an elegant method, and it has broken

**Additional context**

**Comment by squareloop1** [comment]
I second this. A nice ripple effect goes a long way for the overall look and feel. I also feel like the radius of the ripple effect in quasar is just too big. In Vuetify and other material design (like on official Google apps) you can kind of see a circle expanding in the button which creates a nice "click" feel on the button. In Quasar that circle is starting too big and thus it looks like the ripple is just expanding horizontally, which destroys that "click" feel to it.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
