### ISSUE TITLE
QUploader has fixed width property, breaking small screen layouts

### ISSUE THREAD

**Issue by INVITR0** [quasarframework/quasar#6596]
**Describe the bug**
The **QUploader** has a fixed `width` set in the **css** (see [Line 8 in the QUploader stylus file](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/uploader/QUploader.styl#L8)). This breaks the layout on very **small screens**. I fixed it by removing the `width `attribute and replacing it with `max-width` instead.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/az0r3f5m/

**To Reproduce**
1. Add a QUploader to a standard Layout
2. Change the screen size to something smaller than 340px (e.g. iPhone 5)

**Expected behavior**
The QUploader should **not overflow** it's container, but rather **reduce it's width** to fit

**Screenshots**
![image](https://user-images.githubusercontent.com/15647636/76403848-d3985f00-6385-11ea-84a2-2ac03fa9e6bb.png)

**Platform (please complete the following information):**
OS: Any
Node: Any
NPM: Any
Yarn: Any
Browsers: Any
iOS: Any
Android: Any
Electron: Any

**Additional context**
I have not tested if any inner layouts of the QUploader are affected.

**Comment by pdanpdan** [comment]
You don't need to remove anything, set the style on `<q-uploader />` to `max-width: 100%`
https://jsfiddle.net/x1pdkf5o/1/

**Comment by INVITR0** [comment]
Okay, sure I can add additional CSS. But shouldn't the component be responsive out of the box?

**Comment by pdanpdan** [comment]
You can do a PR to add a `max-width: 100%` - please make it both for sass and styl files.
Thank you.
