### ISSUE TITLE
Vetur tags for PascalCase

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#6600]
**Is your feature request related to a problem? Please describe.**
Currently, the generated vetur tags are only available in kebab-case format, so they are unusable for someone who uses PascalCase.

**Describe the solution you'd like**
The tags are available in kebab-case format and PascalCase format.

**Describe alternatives you've considered**
I briefly looked at other frameworks (Bueify, Vuetify) and they all seem to only provide kebab-case tags. I don't know if it could be the standard to only provide kebab-case tags, and it would be vetur's responsibility to propose the tags in the desired format, based on a setting (or simply propose both formats). It's just an alternative, but the easiest way to implement it for Quasar would be to generate both I think.

**Additional context**

**Comment by TobyMosque** [comment]
https://quasar.dev/quasar-cli/quasar-conf-js#Auto-import-feature
```json
framework: {
  all: 'auto',
  autoImportComponentCase: 'pascal'
}
```

**Comment by philfontaine** [comment]
Thanks, but that is unrelated.

I'm talking about vetur Intellisense in VS Code (autocomplete, suggestions, hints) which has nothing to do with quasar's autoImport feature.

**Comment by philfontaine** [comment]
I'll put this on hold, this cannot currently be implemented by Quasar. Vetur does a [toLowerCase on the tag](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/htmlCompletion.ts#L146) to retrieve the attributes, so that will need to be sorted out first.

**Comment by rfox12** [comment]
Be aware that kebab-case is semi-standard for a reason: HTML isn't case sensitive... and if you use pascal for tags it's _possible_ to run into issues where <MyTag> and <myTag> get confused and wreak havoc.

**Comment by philfontaine** [comment]
Thank you, I am aware of that. However, we are talking about Vetur, which is an extension mainly used to parse SFC, which will 100% get compiled with the vue compiler, so this is not an issue.

Vue style guide even recommends using PascalCase : https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended

**Comment by TobyMosque** [comment]
"vetur.completion.tagCasing": "kebab"
and  "PascalCase" isn't an all around recommendation, while kebac is:
[image: image.png]

Em sex., 20 de mar. de 2020 às 10:36, Philippe Fontaine <
notifications@github.com> escreveu:

**Comment by pdanpdan** [comment]
@philfontaine In the style guide the PascalCase is recommended, but as an alternative to kebab-case. You have 4 places where you use component names:
- SFC template: here you can use PascalCase or kebab-case
- DOM strings: here you always use kebab-case
- render functions: here you always use PascalCase
- JS/JSX: here you should always use PascalCase

The gist of this would look like when writing JS/JSX use PascalCase and when using strings use kebab-case.

Also it looks like the vetur issue is not getting any traction, so I'll close this as there is nothing we can do. If something changes you can always ping here and we'll reconsider.
