### ISSUE TITLE
Can quasar use with Single-spa?

### ISSUE THREAD

**Issue by whsqjss** [quasarframework/quasar#6601]
A Single-spa sub project requests export lifecycles functions in main.js, like this:

```
import singleSpaVue from "single-spa-vue"
 import Vue from 'vue'
 const vueOptions = {
    el: "#vue",
    router,
    store,
    render: h => h(App)
 }

 const vueLifecycles = singleSpaVue({
      Vue,
      appOptions: vueOptions
})

export const bootstrap = vueLifecycles.bootstrap
export const mount = vueLifecycles.mount
export const unmount = vueLifecycles.unmount
export default vueLifecycles
```

Is there anyway in quasar can make this possible?

**Comment by rstoenescu** [comment]
Hi,

Use a boot file to initialize it. Your "vueOptions" above is the "app" parameter.
https://quasar.dev/quasar-cli/cli-documentation/boot-files

**Comment by ernisov** [comment]
> A Single-spa sub project requests export lifecycles functions in main.js, like this:
> 
> ```
> import singleSpaVue from "single-spa-vue"
>  import Vue from 'vue'
>  const vueOptions = {
>     el: "#vue",
>     router,
>     store,
>     render: h => h(App)
>  }
> 
>  const vueLifecycles = singleSpaVue({
>       Vue,
>       appOptions: vueOptions
> })
> 
> export const bootstrap = vueLifecycles.bootstrap
> export const mount = vueLifecycles.mount
> export const unmount = vueLifecycles.unmount
> export default vueLifecycles
> ```
> 
> Is there anyway in quasar can make this possible?

Could you please elaborate on this topic? Did you find a way?

**Comment by dallinbjohnson** [comment]
I am also trying to figure out how to make single-spa work with quasar. If someone has figured out how to do this please share an example!

**Comment by lopes-gustavo** [comment]
It'd be great to access the `main.js`. Many people use quasar for the components and doesn't care about `electron` or `ssr`.

Without the `main.js`, for example, we cannot make our appr a package, we cannot export methods/variables to use with microfrontend, we cannot modify the `q-app` container.

I read the documentation over and over and couldn't find a way to modify the `app.js`. If there's a way, can you please explain how?

**Comment by lopes-gustavo** [comment]
@dallinbjohnson and @ernisov by now, you can create an entrypoint in `quasar.conf.js` and use it like that:

`quasar.conf.js`
```js
      chainWebpack (config) {
        config.entry('app').add(path.join(__dirname, 'src', 'single-spa-entry.js'))
      },
      extendWebpack (cfg) {
        cfg.output = {
          libraryTarget: 'umd',
        }
        cfg.plugins.push(new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }))
      }
```

`src/single-spa-entry.js`
```js
import './set-public-path'
import Vue from 'vue'
import singleSpaVue from 'single-spa-vue'
import createApp from '../.quasar/app.js'

function deferredPromise () {
  let _resolve
  const promise = new Promise(resolve => {
    _resolve = resolve
  })

  return {
    promise,
    resolve: _resolve
  }
}

let asyncLifecycles
createApp().then(({ app }) => {
  const { promise, resolve } = deferredPromise()

  asyncLifecycles = promise

  const vueLifecycles = singleSpaVue({ Vue, appOptions: app })
  resolve(vueLifecycles)
})

export const mount = async () => asyncLifecycles.then(lifecycles => lifecycles.mount)
export const unmount = async () => asyncLifecycles.then(lifecycles => lifecycles.unmount)
export const bootstrap = async () => asyncLifecycles.then(lifecycles => lifecycles.bootstrap)
```

I'm trying to use quasar with [qiankun](https://qiankun.umijs.org). I'm still struggling with assets, but it should be in this way. If you can manage to make it work, please, let me know.

**Comment by hawkeye64** [comment]
@lopes-gustavo 
> It'd be great to access the `main.js`. Many people use quasar for the components and doesn't care about `electron` or `ssr`.
> 
> Without the `main.js`, for example, we cannot make our appr a package, we cannot export methods/variables to use with microfrontend, we cannot modify the `q-app` container.
> 
> I read the documentation over and over and couldn't find a way to modify the `app.js`. If there's a way, can you please explain how?


Look up Boot files for adding things like Vue Plugins, things like Axios, your own code, to your app.
https://quasar.dev/quasar-cli/boot-files

**Comment by lopes-gustavo** [comment]
Boot files won't work because they don't export anything out of the bundled module. 
In webpack, only the entrypoints can export methods.
If you look at the generated `.quasar/app.js`, you can see that there is only one `export default` and that function loads all the boot files. But we need to export things, not load them...

**Comment by prem-singh-1** [comment]
Anyone found the complete solution? I am struggling with the same.

**Comment by lopes-gustavo** [comment]
My solution above works, @prem-singh-1. Can I help you with anything in particular?

**Comment by lopes-gustavo** [comment]
For anyone interested, I created a repo with the minimum setup needed to make quasar work with single-spa.
I tried to let the default setup as pure as possible

https://github.com/lopes-gustavo/quasar-single-spa

**Comment by dialguiba** [comment]
Hello, Is it possible to make it work similarly with federated modules in webpack 5? I have been trying to implement that but i couldn't. I always got the same error. "the loading of the script have failed". 

![error](https://i.ibb.co/vL91cPB/xdp-git.png)

Thank you in advance

**Comment by MilosPaunovic** [comment]
Take a look at this:
https://github.com/single-spa/single-spa-vue/issues/51

**Comment by Karnith** [comment]
I have a working demo repo for quasar v2 https://github.com/single-spa/single-spa-vue/issues/65#issuecomment-962133674

**Comment by schupp13** [comment]
> Hello, Is it possible to make it work similarly with federated modules in webpack 5? I have been trying to implement that but i couldn't. I always got the same error. "the loading of the script have failed". 
> 
> ![error](https://i.ibb.co/vL91cPB/xdp-git.png)
> 
> Thank you in advance

Did you ever find a solution for using module federation? I've been trying for a while and can't seem to find anything out there (examples/documentation)?

**Comment by SkyWalker653** [comment]
@schupp13 make sure to pass puplicPath and splitChunk options in quasar config file.

chain.output.publicPath('http://localhost:8080/')
chain.optimization.splitChunks(false)


Here is a working demo: https://github.com/SkyWalker653/quasarv2-mf-example

**Comment by porprojecthub** [comment]
> @dallinbjohnson and @ernisov by now, you can create an entrypoint in `quasar.conf.js` and use it like that:
> 
> `quasar.conf.js`
> 
> ```js
>       chainWebpack (config) {
>         config.entry('app').add(path.join(__dirname, 'src', 'single-spa-entry.js'))
>       },
>       extendWebpack (cfg) {
>         cfg.output = {
>           libraryTarget: 'umd',
>         }
>       }
> ```
> 
> `src/single-spa-entry.js`
> 
> ```js
> import Vue from 'vue'
> import singleSpaVue from 'single-spa-vue'
> import createApp from '../.quasar/app.js' // Dynamic created by Quasar CLI
> 
> function deferredPromise () {
>   let _resolve
>   const promise = new Promise(resolve => {
>     _resolve = resolve
>   })
> 
>   return {
>     promise,
>     resolve: _resolve
>   }
> }
> 
> let asyncLifecycles
> createApp().then(({ app }) => {
>   const { promise, resolve } = deferredPromise()
> 
>   asyncLifecycles = promise
> 
>   const vueLifecycles = singleSpaVue({ Vue, appOptions: app })
>   resolve(vueLifecycles)
> })
> 
> export const mount = async () => asyncLifecycles.then(lifecycles => lifecycles.mount)
> export const unmount = async () => asyncLifecycles.then(lifecycles => lifecycles.unmount)
> export const bootstrap = async () => asyncLifecycles.then(lifecycles => lifecycles.bootstrap)
> ```
> 
> I'm trying to use quasar with [qiankun](https://qiankun.umijs.org). I'm still struggling with assets, but it should be in this way. If you can manage to make it work, please, let me know. I'll update it here with new information on whatever improvements I make

I'm try using quasar with qiankun too, but i struggle at "[import-html-entry]: error occurs while executing entry/normal script" have you ever encountered this error?
