### ISSUE TITLE
QPage: apply css height property 

### ISSUE THREAD

**Issue by 1001v** [quasarframework/quasar#6602]
**Describe the solution you'd like**
Hello. When we place q-page component inside q-page-container, q-page receives min-height property, so it would fit the container. However, if we want to fit a card (or anything else) inside the q-page, we can't do properly, because q-page has min-height, but not height itself. Please take a look at the example:
https://codepen.io/1001v/pen/abOqrMR
The solution i'd like is that height property will be applied to q-page as well as min-height property does, so the child could fit the q-page.

**Describe alternatives you've considered**
Now there's a style-fn property in the q-page component, but it's not very convenient to apply it each time. 

Thank you.

**Comment by pdanpdan** [comment]
The right solution is style-fn and set whatever you want in it.

**Comment by 1001v** [comment]
@pdanpdan why not to apply height as well? What is the limitation? Will it break something?

**Comment by pdanpdan** [comment]
Yes. In the general case the body would not scroll

**Comment by 1001v** [comment]
@pdanpdan ok, thanks for the explanation.
