### ISSUE TITLE
Make it simpler to customize button borders

### ISSUE THREAD

**Issue by Powersource** [quasarframework/quasar#6603]
**Is your feature request related to a problem? Please describe.**
I upgraded from 1.4.5 to 1.9.9 and my old code that was similar to
```
    .q-btn {
        border: 1px solid pink;
    }
```
stopped working. After a while of debugging I figured out the new selector I have to use which is
```
    >>> .q-btn--outline .q-btn__wrapper::before {
```

**Describe the solution you'd like**
Maybe one of these:
* allow the old behaviour
* document this new behavior
* add a prop for adding styles/a class that can modify the border

**Comment by pdanpdan** [comment]
Sorry about the change but it was necessary.
Would you like to try to do a PR in the docs about how to change the borders with CSS?
But if you need you can hide the borders from `.q-btn--outline .q-btn__wrapper::before` and apply them on `.q-btn`

**Comment by Powersource** [comment]
No I won't have the time to submit a PR.

And yeah removing all the borders like that would be a good idea if you don't want any of them. But I only want to replace them in certain cases, which is why I end up having to use the weird selector.

**Comment by Powersource** [comment]
Does this mean that both

> * document this new behavior

and

> * add a prop for adding styles/a class that can modify the border

are `wontfix`?

**Comment by pdanpdan** [comment]
No, we are open to PRs.

**Comment by rstoenescu** [comment]
Hi,

I tried, but we can't simplify it.
However, you can:

1. write a CSS class then use it on each of your buttons

```sass
.my-btn
  .q-btn__wrapper::before
    border: 1px solid pink
```
```html
<q-btn class="my-btn" ...
```

2. target all buttons (not recommended though):

```sass
.q-btn--outline
  .q-btn__wrapper::before
    border: 1px solid pink
```
