### ISSUE TITLE
Integration with python based backend frameworks

### ISSUE THREAD

**Issue by j209** [quasarframework/quasar#6606]
Hi
[Masonite](https://github.com/MasoniteFramework/masonite) is a new python web framework that has a [built in](https://docs.masoniteproject.com/whats-new/masonite-2.3#added-preset-command) integration [with vue](https://github.com/MasoniteFramework/masonite/issues/183).
I think deep integration between masonite and quasar can be a good idea.
[link](https://github.com/quasarframework/quasar/issues/4794#issuecomment-598506111)

**Comment by smolinari** [comment]
Hi. Thanks for your suggestion. However, that would be either something the Masonite team/ community would need to put together or for the Quasar community to do. It wouldn't be a core integration, as Quasar is back-end agnostic. Thus closing this issue. 

Thanks again though! 😃 

Scott
