### ISSUE TITLE
QFab button needs less padding when used on a toolbar beside other QBtn's with/without dense.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#6607]
**Is your feature request related to a problem? Please describe.**

I've just added an FAB (with a list of vertical drop down FAB action buttons) to replace a single button on a toolbar. Looks very cool but there appears to be no way to adjust the padding of the FAB button (16 px) to match the **dense** padding of other buttons on the toolbar.  Even if the other buttons are non-dense the padding is still larger. 

**Describe the solution you'd like**

I think QFab needs a `dense` property (that's all I need today!)
Perhaps you'd also want some other option to match the padding for non-dense toolbars.

**Describe alternatives you've considered**

Tried setting style values on the FAB but that only affects the outer div whereas this padding is set on an inner wrapper div and perhaps the nested QBtn inside QFab.

**Comment by tohagan** [comment]
Ahh the QFab button is also increasing the height of the toolbar due to vertical padding..

**Comment by pdanpdan** [comment]
Please add a codepen.

**Comment by tohagan** [comment]
I've created a codepen but for some reason the QFabAction buttons are now displaying vertically. I don't have this issue in my app.  Anyway it does show the padding issue.  

https://codepen.io/tohagan/pen/RwPMKVr

**Comment by tohagan** [comment]
I suspect that you want to set miniFab: true when QFab is dense.

**Comment by pdanpdan** [comment]
Just for ref the codepen with fixed end of tags: https://codepen.io/pdanpdan/pen/XWbEpGL?editors=1000

We'll think about the problem, but the Fab is only thought to be large, and not in a toolbar but standalone.

**Comment by tohagan** [comment]
Yes I understand that's the traditional use of FAB. But I'd suggest that the this new application for FAB's is very good. My need is for internationalisation (avoiding menu labels) and having a very compact UI.

**Comment by smolinari** [comment]
@tohagan - With a little bit of tweaking. 😃 

https://codepen.io/smolinari/pen/eYNMvQJ?editors=1100

Scott

**Comment by tohagan** [comment]
@smolinari  Thanks Scott ... will give that a try. 
I wondered if there might be a way to adapt the wrapper.

**Comment by tohagan** [comment]
My app no works fine ... but I've left this issue open in case you'd wish to add the `dense` option to QFab.  Thanks guys ... Awesome community!

**Comment by rstoenescu** [comment]
New prop (`padding`) will be available in "quasar" v1.11.0.

**Comment by tohagan** [comment]
Thanks @rstoenescu !
