### ISSUE TITLE
Autogrow dosen't work with dense on q-input

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#6608]
**Describe the bug**
Autogrow dosen't work with dense on q-input

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
1. put autogrow and dense on the same q-input
2. write enough text so it forces a new line

**Expected behavior**
q-input should expand it dosent

**Screenshots**
![image](https://user-images.githubusercontent.com/30523269/76603942-23a22d80-650e-11ea-8d6c-9e7f218d4a16.png)

**Comment by pdanpdan** [comment]
Please add a codepen showing the problem, and the details required in the issue template.
