### ISSUE TITLE
Cannot change year in DatePicker when default-view = 'Months'

### ISSUE THREAD

**Issue by prophe05** [quasarframework/quasar#6609]
**Is your feature request related to a problem? Please describe.**
There is no clear and easy way to change the year when default-view is 'Months' and emit-immediately is true

<img width="300" alt="img" src="https://user-images.githubusercontent.com/5876477/76616283-bc4ba400-6534-11ea-8544-c7e675afb368.png">

**Describe the solution you'd like**
Add left and right arrows, like on 'Years' view to change year:

<img width="297" alt="img-2" src="https://user-images.githubusercontent.com/5876477/76616397-fb79f500-6534-11ea-9824-ce851adcbae8.png">

**Comment by smolinari** [comment]
You can click/ touch the header year value to get the year view, (if you possibly didn't know that). 

Scott

**Comment by prophe05** [comment]
Yes sure, but it's not clear for the first time, so this action produces a lot of questions from users. In my opinion if quasar team will add arrows UX will be improved. 

And when they select the year, widget triggers 'input' event immediately, in my case (I use text field with picker) it also closes DatePicker menu immediately and user has to open it again to change month. So the only way to set the month of the previous year - select required month first and then change the year in the title, only this sequence of actions works now. It makes users unhappy.

**Comment by smolinari** [comment]
Well, I would suggest you need to build out a custom component that allows for "setting" the selection, instead of just closing after the selection. Remember, Quasar is the building blocks to making what you want. :smile: Here is a code pen of sort of what I am referring to. 

https://codepen.io/smolinari/pen/GepzNO

Scott

**Comment by prophe05** [comment]
Yes I understand it, that's why it's the feature request. The 'Years' view already has the arrow buttons, why not to have the same option for the 'Months' it will only improve the datepicker block itself.

'Set' and 'Cancel' buttons only complicate the case imho (one additional and not required click)

**Comment by prophe05** [comment]
When DatePicker is minimal, it's even not possible to change year

**Comment by smolinari** [comment]
I actually like that last idea. 😁 

Scott

**Comment by prophe05** [comment]
Yup, It would be cool to have

**Comment by rstoenescu** [comment]
New prop (years-in-month-view) will be available in "quasar" v1.11.2.
