### ISSUE TITLE
[request] Mini-drawer

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#661]
For some time already we can see the trend in Material Design (also on Google) with doing sidebar menu this way, where the 'closed' state is not really closed but it's just really compact, all labels are hidden

Attached image is taken just today from new UI of Google Analytics.
There is plenty other examples on e.g. material.uplabs.com but I think one is enough, but if you need more, please let me know and I will paste more.
![image](https://user-images.githubusercontent.com/9385106/27594246-30cf3d5a-5b51-11e7-92fe-cdf90e580dc0.png)

**Comment by mstaack** [comment]
really like that proposal!

**Comment by rohyadav** [comment]
Great like that proposal!..thumbs up!

**Comment by Zyles** [comment]
This should be a priority.

**Comment by pjar** [comment]
I'm going to implement it myself - it would be really helpful if it was already in quasar.

**Comment by spectrolite** [comment]
@pjar please share your implementation, that may help @rstoenescu include it quasar earlier.

**Comment by dewdad** [comment]
Has anyone made any leeway with this. I would happily contribute to any such efforts.

**Comment by murbanowicz** [comment]
@dewdad - usually when @rstoenescu working on the feature, he's updating the issue with milestone which did not happen here, so I suppose he does not have time to do that. 
You can create a fork for that and prepare the modification of drawer for that and submit PR.
Even if he will need to do that in a bit different way he will use your ideas in some degree and it will just make it faster and easier for him.

**Comment by murbanowicz** [comment]
@rstoenescu - is this feature gone because of the new drawer implementation?

**Comment by rstoenescu** [comment]
Nope. This will still be in.

**Comment by rstoenescu** [comment]
Work on this has already begun.
This will probably go into 0.15.10

But please note it's easy to make this effect in app-space yourselves with 0.15.

**Comment by rstoenescu** [comment]
Going into 0.15.11

**Comment by Zyles** [comment]
Is this in yet?

This feature is a dealbreaker for me, highly needed.

I tried looking at the showcase but I can't get the drawer to behave like this. Maybe the showcase didn't get updated?

Thanks.

**Comment by rstoenescu** [comment]
@Zyles https://quasar-framework.org/components/layout-drawer.html#Mini-mode
