### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isFinal' of undefined in __spectrumPan()

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#6611]
Method __spectrumPan() sometimes received undefined event quasar/src/components/color/QColor.js.

Checked in browsers:  Google Chrome,  Safari, Firefox.
OS: MacOS Catalina.

To reproduce that issue, please go to https://quasar.dev/vue-components/color-picker#Installation and start hitting the spectrum in random places (not dragging). Within ten clicks you should see that message appearing in the console.

![Screen Shot 2020-03-14 at 1 05 54 PM](https://user-images.githubusercontent.com/26779040/76670276-8d950280-65f4-11ea-9ac7-3455da821ce4.png)

**Comment by rstoenescu** [comment]
Hi,

This has already been fixed in future v1.9.10

**Comment by pikil** [comment]
Great,
Thank you Razvan!
