### ISSUE TITLE
q-tooltip not work in q-icon with name="img:..."

### ISSUE THREAD

**Issue by aloky** [quasarframework/quasar#6618]
`<q-icon name="img:statics/img/icon.svg"><q-tooltip>TEXT</q-tooltip></q-icon>`

**Comment by hawkeye64** [comment]
@aloky You are telling the code to use an `image` tag, which does not have a closing tag.

Wrap it all in a div, so tooltip and image is encapsulated by div and then your tooltip will work.

**Comment by aloky** [comment]
But i need create `div.inline-block`, i think its bad

**Comment by hawkeye64** [comment]
You'll have to do it the same way as if you used the `<image ...>` tag directly. You can also use a `<span>` tag.
