### ISSUE TITLE
meta plugin doesnt set correctly title and meta description in ssr mode

### ISSUE THREAD

**Issue by UXMichael** [quasarframework/quasar#6621]
**Describe the bug**
In SSR Mode i prefetch the site meta data and set it with the meta() function.
This is working correctly.

On the same site when i switch the language the meta() function is called but the title and meta description dont change as described in the documentation

My simple code (called really twice with the right title)
  meta () {
    console.log('Calling Meta' + this.page.title)
    return {
      title: this.page.title,
      meta: {
        description: { name: 'description', content: this.page.metaDescription }
      }
    }
  },

**Comment by pdanpdan** [comment]
Please create a minimal repo showing the problem and link it here.

**Comment by UXMichael** [comment]
Is this ok as cheap example : https://jsfiddle.net/6htuvb7x/2/

**Comment by pdanpdan** [comment]
Yep, good, I can reproduce it, thank you.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.10.0.
