### ISSUE TITLE
QInfiniteScroll load event triggered every time you open the QMenu

### ISSUE THREAD

**Issue by HristinaK** [quasarframework/quasar#6623]
Every time you open a QMenu component it triggers the load method on the QInfiniteScroll inside it. A prime example of when you would need an infinite scroll inside a menu component is a simple notifications component as can be found in Facebook. 

![image](https://user-images.githubusercontent.com/7267222/76747395-5a2fb080-6779-11ea-98a1-1323f79ce1ce.png)

I've put an example from a combination of the docs for QMenu and QInfiniteScroll:
https://codepen.io/TheGeekiestGirl/pen/bGdMooX?editable=true&editors=101

1. Click on the button to open the menu
2. Notice how the scroll jumps as new elements are loaded because the load event is triggered
3. Close the menu
4. Open it again by clicking the button
5. Notice how each time you open the menu the load event is again triggered and loads new elements

**Expected behavior**
What I expected to happen is for the load event to be triggered only when you scroll to the set offset and not on each opening of the menu.

**Comment by pdanpdan** [comment]
You need to be a little creative for this:
- set the scroll-target after the menu is shown
- skip the first load event

https://codepen.io/pdanpdan/pen/yLNjzmM?editors=1011

**Comment by HristinaK** [comment]
This worked perfectly, thank you so much. I tried a couple of dozen combinations similar to your solution but I guess the trick was the setting of the scroll target after the menu is shown. 

However I really think this should be included in the docs for the QInfiniteScroll as it's a common real world scenario. Please consider updating them with the example or consider this as a bug for a future version to be fixed in.

**Comment by pdanpdan** [comment]
There is a warning for `scroll-target` in the docs, but I think you are right that an example would help.

**Comment by rstoenescu** [comment]
Example will be available on next docs deployment.
