### ISSUE TITLE
how to import only component if not chosen to import everything from Quasar

### ISSUE THREAD

**Issue by Summer-Lin** [quasarframework/quasar#6624]
Dear all,
     I don't use Quasar Cli and Vue-cli. I build a project by myself with webpack 4.x
     I want to import one component like QSelect and don't import everything from Quasar.
     Do you have any suggest ?

   Now I import like this and it can work, but I think it's wrong this way.
  When I build the project it's more than 300KB and it's too big.
 
  The document want me installed vue-cli-plugin-quasar, but my project don't build in Vue-cli.
   `
import Quasar from 'quasar/src/vue-plugin'
import iconSet from 'quasar/icon-set/fontawesome-v5'
import QSelect from 'quasar/src/components/select/QSelect.js'
import QInput from 'quasar/src/components/input/QInput.js'
import QIcon from 'quasar/src/components/icon/QIcon.js'
import QDate from 'quasar/src/components/date/QDate.js'
import QBtn from 'quasar/src/components/btn/QBtn.js'

Vue.use(Quasar, {
    components: {
        QSelect,
        QInput,
        QIcon,
        QDate,
        QBtn
    },
    iconSet: iconSet
})
   `

**Comment by aleksander237** [comment]
I use Laravel Mix for most of my projects and imports are done like this

`import { QSelect } from 'quasar/dist/quasar.esm';`

**Comment by Summer-Lin** [comment]
I hava a try like this:

The file named ".babelrc"

```js
"plugins": [
        [
            "transform-imports",
            {
                "quasar": {
                    "transform": "../../conf/transform.js",
                    "preventFullImport": true
                }
            }
        ]
    ]
```

The file named "transform.js""
```js
const transform = require('quasar/dist/babel-transforms/imports.js')
module.exports = transform
```

I can use in SPF and it can work
```
import { QSelect } from quasar  
```

**Comment by psi-4ward** [comment]
I've a setup with typescript and seems transform-imports is not working here.

**Comment by psi-4ward** [comment]
?

**Comment by lucianobosco** [comment]
Same situation here, I just want to use only the table component. Is that possible at all? I don't want to import the whole framework, just table component

**Comment by LeoonLiang** [comment]
I made a demo that I hope will help you
https://github.com/LeoonLiang/nuxt2.0-quasar1.0

**Comment by LeoonLiang** [comment]
Because some components in Quasar also use some things from $q, such as $q.platform, I had to register $q. I wrote a demo here which integrates Quasar 1.0 into Nuxt 2.0. Most of the basic issues have been resolved.


https://github.com/LeoonLiang/nuxt2.0-quasar1.0
