### ISSUE TITLE
Q-Item Url/Link

### ISSUE THREAD

**Issue by JTrotta** [quasarframework/quasar#6626]
Is it possible to use Q-Item as "old-style"menu with url links?
Which property can be set as menuItem.Url?

`                    <q-list v-for="(menuItem, index) in menuList" :key="index">                   
                            <q-item clickable :active="menuItem.label === 'Outbox'" v-ripple>
                                <q-item-section avatar>
                                    <q-icon :name="menuItem.icon" />
                                </q-item-section>
                                <q-item-section>
                                    {{ menuItem.label }}
                                </q-item-section>
                            </q-item>                      
                    </q-list>`

**Comment by pdanpdan** [comment]
For help requests please head to the discord server or to the forum. Thank you.
