### ISSUE TITLE
Blurred backdrop for Q-Dialog

### ISSUE THREAD

**Issue by DelaneDiamon** [quasarframework/quasar#6627]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add backdrop-filter for QDialog backdrop with a prop of "blurred-backdrop"

**Describe alternatives you've considered**
.q-dialog__backdrop.fixed-full{
 backdrop-filter: blur(4px)
}

**Additional context**
N/A

**Comment by pdanpdan** [comment]
Hello.
You can pass `content-class` to dialog and then you can style `.your-specific-dialog-class > .q-dialog__backdrop` however you like.
