### ISSUE TITLE
QSkeleton prop to remove cursor spinner

### ISSUE THREAD

**Issue by fergusmeiklejohn** [quasarframework/quasar#6628]
**Is your feature request related to a problem? Please describe.**
In one component I'm using QSkeleton to give users a template for their data entry so `<q-skeleton/>` is not used to show loading and I don't want the cursor spinner. 

**Describe the solution you'd like**
Either a prop to remove the cursor spinner or add this to `animation="none"`

**Describe alternatives you've considered**
I used `style="cursor: default"` on each `<q-skeleton/>` to solve this problem 

**Additional context**
this is what I mean by "cursor spinner": 
![grab1](https://user-images.githubusercontent.com/11864025/76832875-3184e500-6865-11ea-96ec-760a0dede811.jpg)

**Comment by pdanpdan** [comment]
For the moment you can more simply override the `.q-skeleton` cursor, like here: https://codepen.io/pdanpdan/pen/NWqMVpV

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.9.11.
