### ISSUE TITLE
Not yet implemented classes used in demo

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#663]
In the test pages in quasar there are some classes that are used but not implemented

- [ ] gt-{$name}-row (gt-sm-row in data-table, gt-md-row in html-table)
- [ ] justify-{$name}-{$type} (justify-md-center in flex-rows and flex-columns)

Maybe there should be an optionally loaded extension to the flex.styl that adds breakpoint specific classed for all properties (as in no gutter on xs and sm-gutter on md)

**Comment by rstoenescu** [comment]
Those classes are obsolete and need to be removed.
It just so happens that I am currently polishing flex demo (on Quasar Play) and will take care of this. Thanks for reporting!
