### ISSUE TITLE
Quasar/CLI Command to create new languages

### ISSUE THREAD

**Issue by absantanna2412** [quasarframework/quasar#6637]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a **quasar new** command, something like that:

quasar new [i|18n] <language_code>  --- quasar new i pt-br

In that moment it creates a new folder in i18n directory and a new index.js file and copy the contents of **fallbackLocale** file, modify the i18n\index.js adding the specific configuration.

If you already added suport to vue-i18n it creates a new language file, but if you havent added it could add all the needed configuration, the same when we choose at the project creation.

**Describe alternatives you've considered**
The only alternative is doing by hand.

**Additional context**
I think thats it.

Keep the good work.

Best

Alexandre

**Comment by rstoenescu** [comment]
Hi,

Sorry, but the "do it by hand" approach is really not complicated and pretty straight-forward. The benefits vs the effort to support this feature is simply not feasible (at least at this point).
