### ISSUE TITLE
[Screen plugin] body screen--sm/xs etc is not set by default

### ISSUE THREAD

**Issue by vykimo** [quasarframework/quasar#6641]
**Describe the bug**
body.screen--sm/xs/lg/etc is not set when you arrive with small resolution (for instance on mobile) or when refreshing page. It only appears when resizing width of the page.

**Codepen/jsFiddle/Codesandbox (required)**
Not available because body classes need to be enabled.

**To Reproduce**
1. Enable and Add body classes in your page :
```
body.screen--sm {
  .my-class {
    background-color: red;
  }
}
```
2. Open page, check console
3. Set mobile mode (Firefox) with small resolution
4. Refresh page
5. body have not screen--... classes by default

**Expected behavior**
body.screen--... must be set when page is first loaded (and not resized)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
This will be available in "quasar" v1.9.11.
