### ISSUE TITLE
add rows index

### ISSUE THREAD

**Issue by ganfubin** [quasarframework/quasar#6644]
**Is your feature request related to a problem? Please describe.**
When using table components, rows index is not returned. In some scenarios, Na reading and writing cannot be obtained accurately

**Describe the solution you'd like**
I want to return index in row

**Describe alternatives you've considered**
   // toble-body.js

    getTableBody (h) {
      const
        body = this.$scopedSlots.body,
        topRow = this.$scopedSlots['top-row'],
        bottomRow = this.$scopedSlots['bottom-row'],
        mapFn = body !== void 0
          ? (row, $index) => this.getTableRowBody(Object.assign({...row, $index}), body)
          : (row, $index) => this.getTableRow(h, Object.assign({...row, $index}))

      let child = this.computedRows.map(mapFn)

      if (topRow !== void 0) {
        child = topRow({ cols: this.computedCols }).concat(child)
      }
      if (bottomRow !== void 0) {
        child = child.concat(bottomRow({ cols: this.computedCols }))
      }

      return h('tbody', child)
    },

**Comment by hawkeye64** [comment]
You can add an `index: #` to your own data and do your own searching for indices.

**Comment by rstoenescu** [comment]
Hi,

There's multiple alternatives, but not the one that you highlighted --- if also using filtering or pagination. Unfortunately, for performance reasons, we will not add this into core because developers can:

1. Add an index into their own data, like Jeff said above
2. Do a `data.indexOf(row)`.
