### ISSUE TITLE
Avoid inline styles (e.g. min-height) on q-* components.

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#6645]
I was having layout issues and inspection of my page revealed that:
`<q-page padding>`
was transformed into:
`<main class="q-page q-layout-padding" style="min-height: 839px;">`

This caused all sorts of problems for me.  I end up avoiding the use of `q-page` in favor of `div class="q-pa-md"` so it's no big deal for me right now.  

My request is: can we avoid styling things directly like this in Quasar?  Today I can override a lot by referencing the .q-whatever--style css classes but this new case of inline styles is terrible for extensibility.

**Comment by pdanpdan** [comment]
https://quasar.dev/layout/page#QPage-API

Check style-fn
