### ISSUE TITLE
quasar build -m cordova -T android not building apk

### ISSUE THREAD

**Issue by blusol850** [quasarframework/quasar#6646]
**Describe the bug**
apk files are no longer being generated, when running 
quasar build -m cordova -T android
i get an error that states: A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

**Platform (please complete the following information):**
OS: mac
Node:v13.11.0
NPM:6.13.7
Yarn:
Browsers:
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
So install them. You give no details at all about if it was working before or not, what you changed, ...

**Comment by blusol850** [comment]
<img width="1007" alt="Screen Shot 2020-03-20 at 12 05 38 PM" src="https://user-images.githubusercontent.com/35044908/77182471-30d99200-6aa3-11ea-9fbd-8feef719adb1.png">
I have the build tools installed ( see screenshot ) I upgraded to android studio 3.6.1
it appears to be something wrong during the gradle execution.
below is the full error:

app:cordova-conf Updated Cordova config.xml +12s
 app:spawn Running "cordova build --release android" +0ms

Android Studio project detected
ANDROID_HOME=/usr/local/Caskroom/android-sdk/4333796
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
studio
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* Where:
Script '/Users/andrewdavis/Developer/BluewaterSolutions/HaveAGoodNightApp/src-cordova/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
(node:5750) UnhandledPromiseRejectionWarning: Error: /Users/andrewdavis/Developer/BluewaterSolutions/HaveAGoodNightApp/src-cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/Users/andrewdavis/Developer/BluewaterSolutions/HaveAGoodNightApp/src-cordova/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
    at ChildProcess.whenDone (/Users/andrewdavis/Developer/BluewaterSolutions/HaveAGoodNightApp/src-cordova/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:5750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


 Build succeeded

 Build mode........ cordova
 Pkg quasar........ v1.0.0-rc.5
 Pkg @quasar/app... v1.0.0-rc.7
 Debugging......... no
 Publishing........ no
 ==================
 Output folder..... /Users/andrewdavis/Developer/BluewaterSolutions/HaveAGoodNightApp/src-cordova

**Comment by pdanpdan** [comment]
Check here (https://quasar.dev/quasar-cli/developing-cordova-apps/preparation#Introduction) for some info on setting up cordova, and refer to cordova/android studio documentation for more support.

Thank you.
