### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined  on QUploader

### ISSUE THREAD

**Issue by baryon** [quasarframework/quasar#6647]
**Describe the bug**

When we use `max-total-size` on QUploader comp, it was raise a exception

> TypeError: Cannot read property 'filter' of undefined 

```
<q-uploader
        url="http://localhost:4444/upload"
        label="Max total upload size (4k)"
        multiple
        :max-total-size="4096"
        style="max-width: 300px"
      />
```

**To Reproduce**

Use Restricting-upload sample to reproduce these issue
https://quasar.dev/vue-components/uploader#Restricting-upload

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in "quasar" v1.9.11.
