### ISSUE TITLE
q-chat-message: HTML text content vue directives (@click) dont work

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#6650]
**Is your feature request related to a problem? Please describe.**
Im not quite sure why since im not an expert in vue but it seems if you use the chat message component provided by quasar and pass a html element within the text array this created element dosen't work with any vue directives. This feature would be helpful when e.g. wanting the names of the user withing the message to be clickable.

Example:
```
<template>
<q-chat-message
        :text="['<div @click="someFunction">Click me</div>', 'Click above']"
>
</template>

<script>
export default {
    methods: {
        someFunction () {
            console.log("hello");
        }
    }
}
</script>
</q-chat-message>
```

The chat message creates the div inside itself but it dosent register the @click event at all. Using native javascript events like onClick does for but this is not what im looking for.

If this does already work and I have overlooked something please let me know.

**Describe the solution you'd like**
It would be great if the dom elements created by the chat message componet could also use vue directives

**Comment by pdanpdan** [comment]
Use the slots to put content if you need something that interacts with vue.
https://quasar.dev/vue-components/chat#Slots

**Comment by Quasarman** [comment]
Yeah I thought about that but how would this work if i want to for example have the first message of a person be an image the second and third a text then an image again etc..
With my solution i would pass in an array into the text field where the first element hold the html syntax for an image and the second and third are some text elements and the 4th an image etc.. How would using the slot allow the same behaviour?
Having multiple slot:default instances will only create a single message with the context of the last slot:default instance so i cannot think of a way for this to work for multiple messages of the same person...

**Comment by Quasarman** [comment]
If you have a suggestion please let me know @pdanpdan :)

**Comment by pdanpdan** [comment]
If you are not using slots the content you pass is rendered using either textContent (sanitized) or innerHTML (unsanitized). Neither option allow rendering vue components.

**Comment by Quasarman** [comment]
So it is not possible what id like to achive with the current implementation of the chat message component...because using the default slot only creates the content in a si gle message and dosent allow content to be created in the respective submessages, am I right.

**Comment by Quasarman** [comment]
@pdanpdan Or is there a way to have multiple default slots for the message component to achieve the same behaviour as passing a text array to the component in the text prop. In short that all the submessages are generated using slots?

**Comment by Quasarman** [comment]
Looking at the code for the q-chat-message this seems not to be possible but it devinitly should be IMO.
