### ISSUE TITLE
Please add more SCSS/SASS variables

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#6656]
**Is your feature request related to a problem? Please describe.**
A lot of CSS code use hardcoded values which makes it hard to overrule them.

Just a few examples for `font-weight`:
https://github.com/quasarframework/quasar/blob/7be67fc88e022979e5ae9044558a604ef441cc83/ui/src/components/table/QTable.sass#L15
https://github.com/quasarframework/quasar/blob/7be67fc88e022979e5ae9044558a604ef441cc83/ui/src/components/table/QTable.sass#L69
https://github.com/quasarframework/quasar/blob/80c789f63e781e2e970c74f8b735f3a2628b47e0/ui/src/components/tooltip/QTooltip.sass#L7

**Describe the solution you'd like**
Add more variables.

**Describe alternatives you've considered**
Creating a PR for it.

**Additional context**
I'm happy to create a PR if wanted. :)

**Comment by rstoenescu** [comment]
Hi,

We are trying to get away from scss/stylus variables as much as possible as we want to eventually replace them with native CSS variables (when IE11 will reach end of life).

This is easy to customize in your own app by overwriting the .q-table th etc selector, so no reason to add something that will generate a breaking change later. Hope you understand.
