### ISSUE TITLE
[QEditor] - Prevent null pointer on blur

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#6660]
**Describe the bug**
I use QEditor inside a `QPopupEdit`. When the popup hide and the editor has focus, a null pointer appear in the console.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/6pn4m3us/1/

**To Reproduce**
1. Go to https://jsfiddle.net/6pn4m3us/1/
2. Click on the first Field
3. Click out of the QEditor to close Popup
4. See the following error in the console :
```TypeError: Cannot read property 'scrollTop' of undefined
    at a.__onBlur (quasar.umd.min.js:6)
    at He (vue:6)
    at HTMLDivElement.n (vue:6)
    at HTMLDivElement.Yr.o._wrapper (vue:6)
```

**Expected behavior**
This is not a bug, but the popup clear content before Editors's blur. Just check

**Comment by pdanpdan** [comment]
Hello. Thank you for reporting this. A fix will be available in Quasar v1.9.12
