### ISSUE TITLE
Sharing components between two internal products using lerna

### ISSUE THREAD

**Issue by brsanthu** [quasarframework/quasar#6662]
We are working two products which shares similar needs. We want to create set of components/mixings and share them with other two products. We want to use mono-repo with lerna.

For ex., this is the folder structure we are trying to achieve.

```
repo
	common
		components
		mixins

	product1
		components
		routes
		pages

	product2
		components
		routes
		pages
```

Is there any docs or an example on how to achieve this? (could not find any by searching around).

**Comment by hawkeye64** [comment]
@brsanthu I am currently working on a project like that. I am using Yarn Workspaces, which seems to be working quite well for me. You can also use Lerna, as it is complimentary to Workspaces, but depends on what your needs are.
```
package.json
node_modules
     packages
        	common
        		package.json
        		components
	        	mixins

        	product1
        		package.json
	        	components
                        routes
         		pages

        	product2
        		package.json
	        	components
         		routes
         		pages
```
where you main package.json has thisL
```json
  "workspaces": [
    "packages/*"
  ],
```
Hope that helps.
