### ISSUE TITLE
Clearable Select do not retain cleared value

### ISSUE THREAD

**Issue by martinpare** [quasarframework/quasar#6663]
When we clear the value of a select and we then move the focus on another element (Buttons, etc...), the old selected value reapear. I cannot reproduce exactly the sequence of operations but play with the following CodePen and you will come across this problem rapidly.

CodePen: https://codepen.io/martinpare/pen/RwPYmNR

Thanks in advance for considering this bug.

You are doing an AMAZING job.

**Comment by pdanpdan** [comment]
Sorry, I need a clear reproduction procedure. In quick tests I cannot reproduce. Also does it happen on desktop/mobile, what browser, what is?

**Comment by martinpare** [comment]
**Chrome** Last build. Version 80.0.3987.149 (Build officiel) (64 bits)
**Desktop**. Windows 10
Do the following:
1. Change value in the select, 
2. Press tab (Keyboard) to set focus on the button. 
3. Clear value within the select. 
4. Press tab two times to set the focus back on button.

Repeat these operation and you will discover that at some point, the last value before we clear the select is reapring when the second tab is pressed to set the focus back to the button. Happens most ofen the third time we clear the value.

Weird stuff. I Hope that it is more clear.

Thanks for such a quick response.

**Comment by olegvakulenko** [comment]
Maybe this related to my issue?
https://codepen.io/olegvakulenko/pen/bGNVYmO?editors=1010

**Comment by pdanpdan** [comment]
No, I found it - it was not resetting the current option index on popup close.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.12.

**Comment by martinpare** [comment]
Thanks!
