### ISSUE TITLE
A Suggestion for Quasar iOS/Android improvement

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#6664]
I've been using Quasar for a while and this is my open source project , an all-in-one downloader .
https://github.com/hugetiny/negibox 300+ stars

Quasar is the best Vue framework I've ever used, the styles are responsive and I don't have to write a lot of css code, and the table component is powerful.
But Quasar's weakness is on the mobile side
In China, the most popular cross-platform applicationframework is uni-app, 
https://github.com/dcloudio/uni-app 19k+ stars
(without Electron)

It is more advanced than Capacitor and Cordova
1.It solves many user experience problems by compiling the nvue component to Weex(native component)
2.Oneclick to compile to Android/iOS/Html/Other build-in apps in Wechat etc.(Cloud building)
3.Interface to call native functions with html plus standard.
and it is officially recommanded by Vue.js.
Unfortunately uni-app is mainly for Chinese developers, if Quasar can integrate the advantages of uni-app,it will be the greastest cross-platform framework I believe.

**Comment by rstoenescu** [comment]
Hi,

Weex is not web code that runs in a browser. It's a completely different technology, so Quasar and Weex are incompatible. A Quasar port to Weex would take tremendous effort (and time!) and I'm really not sure that it could support all the features embedded into Quasar.

It's actually an insult to say that Quasar's weakness is on the mobile side, but I think there's a language barrier here. I think that you mean "Quasar would be better if it would support uni-app". But let's say we start working on this. There's two problems: their docs are not in English.. and who's gonna pay our bills while we work on this? :) Not trying to be harsh (far from it), but it's the reality..

**Comment by hugetiny** [comment]
Yes,its a lot of work.Just a suggestion.
I was not insulting Quasar.
Maybe,Quasar cloud  provide cloud services in the future like heroku PaaS to profit from.
