### ISSUE TITLE
Quasar routing notification callback.

### ISSUE THREAD

**Issue by rachitpant** [quasarframework/quasar#6666]
**Is your feature request related to a problem? Please describe.**
When you get a native android or ios notification for your quasar app , and click on the notification , the app is opened automatically. However there is no way to open a particular page/route in your app automatically , dependeing on the payload in the notification. This is a very common scenario, eg. if you are building a fileexplorer in your quasar app  , and you get a notification " New file shared with you" , quasar should automatically redirect to the route of that new file/folder. Most notifications are always tied to a particular page.

**Describe the solution you'd like**
A quasar feature that wraps native ios/android callback code and uses existing routes.js mapping to navigate the app to , depending on the value of route received in the notification payload.

**Describe alternatives you've considered**
Using phone-plugin-push. It would be nice to have a quasar feature that handles all this.

**Comment by rstoenescu** [comment]
Hi,

Why reinventing the wheel? phone-plugin-push is the way to go. When you receive a notification you can redirect your router to a path based on the payload that you receive.
