### ISSUE TITLE
QSelect placeholder disappears on any device other than a desktop

### ISSUE THREAD

**Issue by Xyltos** [quasarframework/quasar#6669]
**Describe the bug**
Using the QSelect along with "_use-input_" prop and a "_placeholder_" works fine on desktop. Once we open the application with the QSelect on any device other than a desktop the placeholder text disappears.

Regular QInput's show the placeholder no matter what platform.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/shandrolis/pen/abORpay

**To Reproduce**
1. Open Codepen on desktop
2. QSelect placeholder should show
3. Open Codepen on any device other than a desktop
3.1. Simulate tablet device on Chrome
3.2. Open Chrome DevTools (F12)
3.3. Toggle device toolbar (Ctrl + Shift + M)
3.4. Select iPad
3.5. Refresh page
4. QSelect placeholder is empty

**Expected behavior**
Placeholder should still show, no matter what platform the application is visited from

**Screenshots**
##### QSelect on desktop
![afbeelding](https://user-images.githubusercontent.com/37328500/77419807-4adbe300-6dc9-11ea-9603-b52d564dcf7b.png)

##### QSelect on iPad
![afbeelding](https://user-images.githubusercontent.com/37328500/77419744-313a9b80-6dc9-11ea-9bb3-be8e6103f17b.png)

**Platform (please complete the following information):**
Happens on any platform except desktops.

**Additional context**
Was able to reproduce this bug on Android and iOS phones

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.12.
