### ISSUE TITLE
Inconsistencies on height, min-width and wrapping for form elements

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#667]
Test case 1:
- enhance size-test with 2 more columns with q-datetime type="date" and type="datetime"
- clean all fields
- decrease window width till the fields reach minimum width

Observations:
- all normal fields (on top) have a reasonable min-width that shows a few letters from label / placeholder (expected), execept QSelect that only shows one letter (but it's ok, you can see it it empty)
- QInput and QDialogSelect inverted are ok
- QSelect, QSearch and QDatetime have no visual indication of the content

Test case 2:
- fill content in QInput, choose Apple Inc. in QSelect and pick a datetime

Observations:
- QInput is ok
- QSelect, QDialogSelect, QDatetime(date and datetime) have content that wraps and change the height (I would expect it to hold to one line use ellipsis to indicate overflow)
- QSearch has no visual indication of the content, except that it's present (because of the clear button) and no indication of label

**Comment by rstoenescu** [comment]
I think this has been fixed in v0.15.
