### ISSUE TITLE
QDate: With QInput - Append Bug

### ISSUE THREAD

**Issue by kevinmelo** [quasarframework/quasar#6670]
**Describe the bug**
When using v-slot:append on a QInput and for some reason you change his visibility(v-if) to show another QInput(without v-slot:append) the append icon still show but in the other QInput

**Codepen**
https://codepen.io/Tydroth/pen/abORJVj?editors=1010

**To Reproduce**
1. Create an QInput with v-slot:append
2. Create other QInput but without v-slot:append
3. Create a QBtn to change their visibility (see on codepen)
4. When change visibility, the v-slot:append still show in both cases

**Expected behavior**
When QInput with v-slot:append is not showing the slot has to hide too

**Screenshots**
See on CodePen

**Platform (please complete the following information):**
OS: Zorin
Browsers: Google Chrome

**Additional context**
Didn't test with others v-slot

**Comment by pdanpdan** [comment]
This is related to how Vue reuses the components - if you want to switch similar elements use a different `key` prop on each of them.

Sorry, but this cannot be fixed in the framework.

**Comment by kevinmelo** [comment]
Got it. thanks... Adding an key they work fine
