### ISSUE TITLE
quasar dev process crash when misusing .sync modifier.

### ISSUE THREAD

**Issue by Fulbert** [quasarframework/quasar#6674]
**Describe the bug**
When doing something like this `:pagination.sync="{ ... }"` (indeed it makes no sense), the `quasar dev` won't finish and use all the processor until it crash. `quasar build` will make a confusing error (but point out the correct part of the code).

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gregoirelannoy/pen/VwLEQyj

**To Reproduce**
1. Run `quasar dev`
1. Create a component with a QTable
1. Add a property like this one : `:pagination.sync="{ ... }"`
1. The `quasar` process will go in a loop and use all processor ressources.

**Expected behavior**
I would have expected an error that indicates me I'm dumb. 👌

**Platform (please complete the following information):**
OS: Ubuntu Desktop 19.10
Node: 13.10.1
NPM: 6.13.7
Yarn: 1.22.1

**Additional context**
I did this mistake, and I was not focused right after I add the `.sync` modifier. I forgot what I've done last on my code when I notice the computer crashed (cannot undo because I had to kill the virtual machine who was not responding).

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, there is nothing that we can do. This is handled entirely by webpack and vue-loader...
