### ISSUE TITLE
QStepper error color defaults to negative on current step.

### ISSUE THREAD

**Issue by hitostacha** [quasarframework/quasar#6676]
**Describe the bug**
QStepper error color defaults to negative color on current step.

**Codepen/jsFiddle/Codesandbox (required)**
[Right here](https://codepen.io/pen/eYNPree)

**To Reproduce**

1. Create a new component using QStepper
2. Pass a color to the error-color prop
3. Change steps back and forth
4. See the error

**Expected behavior**
The current error color should be the one I pass to the prop but it keeps defaulting to the negative color

**Platform (please complete the following information):**
OS: Windows 7 64 bits
Node: v12.14.0
NPM: 6.13.4
Yarn: 1.21.1
Electron: 7.1.12

I can work around this by adding `.q-stepper__tab--error {
  // color: $somecolor !important;
}` to the css, but I figured that this shouldn't be the default behavior

**Comment by rstoenescu** [comment]
Hi,

Why is this a bug. You are telling QStep that the step has an error on it...

**Comment by pdanpdan** [comment]
The problem is that even if the `error-color` is set, the color used for current step with error is the default one (not the one in `error-color`).

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.13.
