### ISSUE TITLE
QSelect throws "this.$refs.target.select is not a function" when calling updateInputValue() and behaviour is "dialog"

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#6677]
**Describe the bug**
QSelect occasionally throws `TypeError: "this.$refs.target.select is not a function"` in `__selectInputText`. Seems to be reproduceable when the QSelect is shown as a dialog and `updateInputValue()` is called.

Background: I'm trying to make a "recipients" component where the QSelect will show a filtered list of contacts to pick from. The list should not show contacts that are already selected and the input value should be cleared when a value is selected from the options.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gordonblahut/pen/RwPeJQK?editors=1111

**To Reproduce**
1. Go to https://codepen.io/gordonblahut/pen/RwPeJQK?editors=1111
2. Set behavior to dialog or resize window so that default will trigger dialog
3. Type 'j' into the "Recipients" field.
4. Select the first option, notice the 'j' input is cleared and the options disappear.
5. Type 'j' into the "Recipients" field.
6. Select the remaining option. At this point The QSelect dialog seems to lose focus and attempts to focus it trigger the exception above. Tapping outside of the dialog to dismiss it and then tapping the QSelect to re-open it seems to reset it, but it will again fail on the second selection.

**Expected behavior**
Error should not be thrown, behavior for steps 5/6 should be same as steps 3/4.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10 x64 (10.0.18363)
Node: 10.15.3
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Firefox, Chrome,
iOS:
Android: Chrome Webview using Cordova
Electron:

**Additional context**
Not sure if there's a better way to clear the input on option selection. Also seems to work as expected when the QSelect is in menu behavior.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.12.
