### ISSUE TITLE
[docs]how to extend custom funtion to qeditor

### ISSUE THREAD

**Issue by wideweide** [quasarframework/quasar#6678]
I want to format some selection node to some other ,but not found the api,some function like :

1. import some css, that can redefine the style
2. add some predefined style,that can be apply to selected element
3. do any replace as I want (maybe what I need is get selection's element node,content,then set content)

add parent element div and class
```
<p>autor: abc</p><p>date:2020...</>
----->
<div class='postInfo'><p>autor: abc</p><p>date:2020...</></div>
```

merge some tag and clean : 
```
<p style=xxx>adf</p><span>abc</span>
--->
<p>adfabc</p>
```

**Comment by wideweide** [comment]
6 days ago, I have to switch to use tinymce

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area.
