### ISSUE TITLE
Improve Quasar boot and prefetch redirect API to match the Vue Router replace api

### ISSUE THREAD

**Issue by frankievx** [quasarframework/quasar#6682]
**Is your feature request related to a problem? Please describe.**

I found it slightly frustrating having to remember the redirect API for a prefetch or boot file when it seems to behave like a $router.replace.

**Describe the solution you'd like**

The ideal solution would be to rewrite the redirect API to match the $router.replace API so they are consistent and it will simpler to remember.

**Describe alternatives you've considered**

**Additional context**

**Comment by pdanpdan** [comment]
I don't understand what is the request. Redirect accepts false or a string (or an object - but only on client side). Please details what you propose. Thank you.

**Comment by pdanpdan** [comment]
Please reopen when you have relevant details. Thank you.
