### ISSUE TITLE
No Nodes slot for QTree

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#6683]
**Is your feature request related to a problem? Please describe.**
Nice to have slot for no nodes in QTree

**Describe the solution you'd like**
``` html
<q-tree>
<template #no-nodes></template>
</q-tree>
```

**Comment by pdanpdan** [comment]
I understand this is for top level tree data and to be honest I don't see the utility of this over a `v-if` checking if there is data for tree.
Can I have some more details on what should be different?

**Comment by pdanpdan** [comment]
I can't see the use case for this, so I'll close it.
