### ISSUE TITLE
QTime closes prematurely on Safari

### ISSUE THREAD

**Issue by petrmifek** [quasarframework/quasar#6684]
**Describe the bug**

On Safari 13.0.5, the time picker closes prematurely while selecting the Minutes when used with QInput (while dragging the minutes clock hand) that has a mask set. This is different to Chrome, where it stays on until clicked outside of the menu/dialog.

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/petredm/pen/VwLVjrM

Same issue at https://quasar.dev/vue-components/time#With-QInput

**To Reproduce**

Use Safari, click on the QInput icon and drag the hand around while selecting the hour and minute. The dialog will close __while__ dragging in the minute view.

**Expected behavior**

Consistent behavior across the browsers.

Probably the behavior this has in Chrome, which is, to close only when clicked outside of the dialog. Alternatively, self-close when the the time selection is complete - minute or second selected and eventually meridiem/am-pm selection is done (Safari made me believe this was the original intent! Chrome made me standing corrected I guess... )

**Platform (please complete the following information):**
OS: macOS 10.15.3
Node: n/a (UMD/standalone version)
Browsers: Safari 13.0.5, Chrome 80.0.3987.149

Thanks!

**Comment by rstoenescu** [comment]
Hi,

This is no longer the case. At least with Quasar v1.12.1. So closing this ticket.
However, I've noticed something else (like keyboard popping out, which will fix).

**Comment by rstoenescu** [comment]
The other issue that I mentioned will be fixed in Quasar v1.12.2.

**Comment by petrmifek** [comment]
Checked and confirmed the behaviour is now consistent between the browsers.

Thanks!
