### ISSUE TITLE
QSelect height problem with "use-chips" and "label" at the same time.

### ISSUE THREAD

**Issue by billycat** [quasarframework/quasar#6685]
**Describe the bug**
QSelect height problem with "use-chips" and "label" at the same time. 
It may be get higher.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/billycatcat/pen/BaNGwOd

**To Reproduce**
1. q-select choose an item, such as "Google"
2. q-input type something, such as "USA"
3. I found that the q-select is higher than q-input at the first group

**Expected behavior**
Hope that q-select do not expend the height while with lable and chips. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6973133/77634958-c46ffe80-6f8c-11ea-8b55-fcf90b076bc2.png)

**Platform (please complete the following information):**
OS: Win7
Node:
NPM:
Yarn:
Browsers: Chrome 78.0.3904.108 (64bit)
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Hello.

- take the CSS from this commit: https://github.com/pdanpdan/quasar/commit/fd87e59e8af6757d0ae71c000cd5cd818d1fe3a8
- add by hand the `q-select--with-chips` class on your QSelect
- it does look a little bit squeezed, but it's the best I could do in the limited space

**Comment by billycat** [comment]
@pdanpdan  Thanks for your idea !
I take a try, it's very helpful.
