### ISSUE TITLE
aws-amplify issue work around

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#6689]
After adding the aws-amplify package, which adds graphql as a dependency, I saw 175 errors similar to:

`Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)`

when running `quasar dev`

This comment: https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574

led me to add `cfg.resolve.extensions.unshift('.mjs')`

in `quasar.conf.js` in `extendWebpack`

Not sure I'm actually requesting anything, but wanted to make you aware of it incase you wanted to tweak the standard webpack config and also for anyone else that might find this. So far that seems to fix the issue.

**Comment by rstoenescu** [comment]
Hi,

Thanks for the suggestion.
Will be available out of the box starting with future quasar/app v1.6.1.
