### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by ajayashuba** [quasarframework/quasar#669]
The directive you made for touch , how it is different to using hammerjs vue binding ..  how both works or compared ?

**Comment by rstoenescu** [comment]
Hi,

Please use [forum](http://forum.quasar-framework.org/) for questions.
I'll make an exception and answer this quickly here:

* significantly faster running
* much much lower footprint
* bloat-free

At some point Quasar required Hammerjs as dependency, until I got tired of asking them to fix some bugs and decided to do a better Quasar in-house solution. This solution would "sell" well as standalone too ;)

Don't have time now to get into details, but one small and significant example: Quasar's touch directive get "isFirst" and "isFinal" props right.

You won't miss anything from hammerjs.

-Razvan
