### ISSUE TITLE
How to go to source code?

### ISSUE THREAD

**Issue by fxjs** [quasarframework/quasar#6692]
I use quasar-cli created a default project. I tried to jump to the source code with webstrom, but it didn't work. 
How to fix this？ Thanks.
local  component:
![photo_2020-03-27_23-41-21](https://user-images.githubusercontent.com/3682415/77774858-ae466900-7086-11ea-98fd-1c242ceea762.jpg)

node_modules  component:
![Screenshot_20200327_235611](https://user-images.githubusercontent.com/3682415/77774783-9242c780-7086-11ea-833d-8156112d88c5.png)

**Comment by pdanpdan** [comment]
Hello. For help requests please go to uor discord channel or to the forums. Thank you.

**Comment by fxjs** [comment]
Solved, [quasar-ide-helper](https://github.com/panstromek/quasar-ide-helper), thanks!
