### ISSUE TITLE
Indent and Outdent buttons on the WYSIWYG Editor don't work

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#6697]
Dev mode.......... spa
Pkg quasar........ v1.9.11
Pkg @quasar/app... v1.6.0
I'm on Windows 10 Desktop Chrome (latest).  

The indent and outdent button's don't work for me:
https://quasar.dev/vue-components/editor#Example--Kitchen-sink

**Comment by pdanpdan** [comment]
They work for me. If you don't give any context it's hard to help. What are you trying to indent/outdent. Make a codepen that can reproduce the problem.

**Comment by rfox12** [comment]
I didn't think a codepen was necessary--the public example page in the documentation I linked to doesn't work for me.

I type some text, highlight it, and attempt to press the "Increase Indent" button.  Nothing happens.  In fact the "Increase Indent" button is disabled.  For every other editor in the known universe this would put a tab at the beginning of my text.

I do notice that the indent/outdent buttons seem to work fine on lists--but this functionality should not be just for lists.

**Comment by rfox12** [comment]
Ultimately I think you could put a blockquote in with margin-right set to zero.  That would have the effect of indenting.

**Comment by pdanpdan** [comment]
Indent and outdent are mainly for list items. Also this is just a simple editor using the browser internal content editable.
