### ISSUE TITLE
[Notify] Actions defined in registered type are ignored

### ISSUE THREAD

**Issue by the-collaborator** [quasarframework/quasar#6698]
**Describe the bug**
According to documentation custom types of notifications allow to define actions. Actions defined as default does work. However actions defined for custom type have no effect:

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/the-collaborator/pen/poJqrMe

**To Reproduce**
1. Go to https://codepen.io/the-collaborator/pen/poJqrMe
2. Click on 'Test me'
3. Check that Notification doesn't have button to close it.
4. Check the JS code where action for closing the notification is defined.

**Expected behavior**
Actions should be populated also for custom types.

**Comment by rstoenescu** [comment]
Thanks for reporting and also PRing the fix!
This will go into "quasar" v1.9.12.
