### ISSUE TITLE
Win 10 x64 - Unexpect token import

### ISSUE THREAD

**Issue by eullercristian** [quasarframework/quasar#67]
Dears, 

I just created an application using the get started. When i try run the application , an error is showed.

index.html:1 Uncaught SyntaxError: Unexpected token import, see that https://puu.sh/qTJLp/946d2249e4.png

My code app.js https://gist.github.com/eullercristian/93d3bfb33b5e7197d646c8087a08e171

How I can solve the problem? I am using win10. Thanks a lot.

**Comment by rstoenescu** [comment]
Is this the standard boilerplate created by the CLI, with no alterations?

**Comment by eullercristian** [comment]
Yes @rstoenescu , i dont changed nothing. Its my first contact with Quasar.

**Comment by rstoenescu** [comment]
Will look right into it now.

**Comment by eullercristian** [comment]
Thanks a lot @rstoenescu

**Comment by rstoenescu** [comment]
I hope this does not affect the way you perceive the quality of Quasar :)

**Comment by eullercristian** [comment]
@rstoenescu No way. I am eager to start using it.

**Comment by rstoenescu** [comment]
Investigating. Shouldn't take long.

**Comment by rstoenescu** [comment]
For the life of me, I cannot reproduce... Please delete your app folder and make it again (`quasar init app`, `cd app`, `npm install`, `quasar dev`). Make sure npm install does not issue any errors...

**Comment by rstoenescu** [comment]
Also, what Node and NPM version are you running?

**Comment by eullercristian** [comment]
@rstoenescu 

NPM 3.10.3
NODE v6.3.1

Its weird, i tried install all things again, and i had the same problem :(

**Comment by eullercristian** [comment]
@rstoenescu  see that: https://puu.sh/qU8CF/8568439487.png

**Comment by rstoenescu** [comment]
I'll investigate tomorrow with your environment. By that error it seems that babel does not transpile.. very weird. Thank you for logging this bug!

**Comment by eullercristian** [comment]
Thanks one more time @rstoenescu .  I am excited for use quasar :)

**Comment by ErickPetru** [comment]
Are you on Windows 10 x64? Maybe it's the same problem I had some time ago with webpack template in vue-cli: https://github.com/vuejs-templates/webpack/issues/116

**Comment by rstoenescu** [comment]
Woah, would you be so kind to make this change in .eslintrc.js and tell me if this works for you, please?
https://github.com/vuejs-templates/webpack/commit/a20a796f4c9733d3379ecab9301a154fcc6820d2

**Comment by eullercristian** [comment]
@rstoenescu its working now :star:  thanks a lot :)

**Comment by rstoenescu** [comment]
I'm a little baffled. It's really weird, because that fix is already in the starter pack. Please explain exactly what you did to make it work so I can patch the starter kit.

**Comment by eullercristian** [comment]
@rstoenescu  it really was very weird. I fix the problem running the command npm install -g npm-windows-upgrade
npm-windows-upgrade

When a generated a new project Quasar, the error was fix. Thanks a lot.

**Comment by rstoenescu** [comment]
So what Node and NPM are you using now after npm installing that?

**Comment by eullercristian** [comment]
The same version, i believe that command clear cache npm, and all things was generated rigth.

Thanks a lot.

**Comment by catalinbuletin** [comment]
Hi @rstoenescu,

I have the exact same problem. `Unexpected token import` on `index.vue`, this line:

`import Quasar, { Utils } from 'quasar'`

Fresh new install of quasar. 

Node version: 7.0.0

MacOS Sierra 10.12 - not sure if it has anything to do with everything tho.

**Comment by rstoenescu** [comment]
vuejs-templates/webpack@a20a796

**Comment by rstoenescu** [comment]
I fix the problem running the command npm install -g npm-windows-upgrade
npm-windows-upgrade

**Comment by catalinbuletin** [comment]
My bad on commenting on a windows issue, but i'm running MacOS Sierra 10.12.

And the node version i'm running is the latest stable one.

**Comment by rstoenescu** [comment]
Please open an issue on https://github.com/quasarframework/app-template-v2
The Quasar template is a fork of https://github.com/vuejs-templates/webpack so check out if someone else is having same issue ;)
