### ISSUE TITLE
QSelect margins inside the QToolbar

### ISSUE THREAD

**Issue by conx13** [quasarframework/quasar#670]
Quasar:latest quasar-edge.git (0.14)
OS:osx

QSelect inside QToolbar have margins. But QSearch inside QToolbar none? (sorry my english)
![screen shot 2017-06-29 at 11 34 12](https://user-images.githubusercontent.com/2715581/27679562-c66e1dce-5cc1-11e7-8588-ca0e07001d06.png)

**Comment by rstoenescu** [comment]
Use "no-margin" CSS class on form components.
