### ISSUE TITLE
Qselect with simple input + autocomplete + addnew can't use backspace

### ISSUE THREAD

**Issue by natxocc** [quasarframework/quasar#6703]
**Describe the bug**
When use a Qselect with an autocomplete, not mutiple, like an input text, we can't remove the value with BackSpace key

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/natxocc/pen/eYNbMKO?editable=true&editors=101

**To Reproduce**
1. Goto input text and try to remove it with backspace key 

**Expected behavior**
Like a simmple combobox, remove the keys one by one to rewrite again that you want

**Screenshots**

**Platform (please complete the following information):**

**Additional context**
Using Quasar 1.9.11

**Comment by natxocc** [comment]
Please, want to add a question on how to use the @input-value sample code, as in quasar docs are not any. Thanks

**Comment by pdanpdan** [comment]
Backspace does not clear options from single selection QSelect by design.
There are examples in docs: https://quasar.dev/vue-components/select#Example--Text-autocomplete

**Comment by trymbill** [comment]
> Backspace does not clear options from single selection QSelect by design.

I don't understand this decision. The user can use their keyboard to filter the options down to what they want, use the arrow keys to highlight their choice, and hit `enter` to select an option. Then realize they've picked the wrong option and want to remove their initial option and start over, why wouldn't you want to allow them to use `backspace` at that point? They've used their keyboard up until this point, I'd argue it's bad UX to not allow them to use their keyboard to remove their selection.

Why does it matter that the select input is a single select? They've used their keyboard up until this point without any issues, why are we forcing them to now switch over to using a mouse just to clear the input?

**Comment by pdanpdan** [comment]
@trymbill You might have a point. I'll reopen and think about it.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.14.7.
