### ISSUE TITLE
Quasar localization with ssr

### ISSUE THREAD

**Issue by DiaaEddin** [quasarframework/quasar#6704]
**Describe the bug**
when changing localization in ssr based on cookies in a boot file. the changes to html(lang,dir) are taking to the next request to change values. though it catches up on client when the browser taking over also it is working just fine on the next request.

for example when changing locale from en-us to ar on the client side (setting this in cookies) and then requesting the server (ssr) for the first time after changing cookies locale value. the html properties (lang,locale) are still giving `<html lang=en-us dir=ltr>` .. every thing else is doing just fine. on the second request the `<html lang=ar dir=rtl>` is present. 
I tried to use meta plugins to alter this unwanted behavior but htmlAttr changed nothing.

**Codepen/jsFiddle/Codesandbox (required)**
I could not get it to work on Codepen and I think this can not be done because it is ssr related issue any ways this is my language boot file:
```
const res: any = async ({ app, ssrContext }: any) => {
  let langIso = 'en-us'; // ... some logic to determine it (use Cookies Plugin?)

  let cookies: Cookies = process.env.CLIENT
    ? Cookies
    : (Cookies.parseSSR(ssrContext) as Cookies);

  if (cookies.has('locale')) langIso = cookies.get('locale');
  let quasar: any = Quasar;
  try {
    await import(
      /* webpackInclude: /(ar|en-us|zh-hans)\.js$/ */
      'quasar/lang/' + langIso
    ).then(lang => {
      console.log('changing language to ' + langIso);
      quasar.lang.set(lang.default);
    });
  } catch (err) {
    console.log('error when changing langauge');
    console.log(err);
  }
  // Set i18n instance on app
  app.i18n = i18n;
  app.i18n.locale = langIso;
  axios.defaults.headers.common['Accept-Language'] = langIso;
};
export default res;
```
**To Reproduce**
1- enable ssr.
2- set ` build: {rtl:true}`.
3- on ssr try to change locale based on cookie or something.. the html(lang,dir) will not change util the second request and upove. and by the way it is affecting the requests from other browsers.. for example if I request it for en-us from a browser , and other one is requesting it with ar the latest will get en-us on html local, the second request will go just fine, then who ever request any other lang will get `<html lang=ar dir=rtl>` on the first request and he will change these values for the whole application for all users. 

**Expected behavior**
the above code should change local for the current request (it does) for everything expect direction and lang attribute in html tag.

**Platform (please complete the following information):**
Browsers, ssr

**Comment by rstoenescu** [comment]
Hi,

The problem lies with your i18n. You need a new instance for each request, otherwise when you say `app.i18n.locale = langIso` it essentially translates to `i18n.locale = langIso` -- you are directly tampering with the global.

**Comment by DiaaEddin** [comment]
but I am making new instance of i18n
this is my `boot/i18n.ts` content:
```
import Vue from 'vue';
import VueI18n from 'vue-i18n';
import messages from '../i18n';
import axios from 'axios';
import Quasar, { Cookies } from 'quasar';
Vue.use(VueI18n);

const i18n = new VueI18n({
  locale: 'en-us',
  fallbackLocale: 'en-us',
  messages
});

const res: any = async ({ app, ssrContext }: any) => {
  let langIso = 'en-us'; // ... some logic to determine it (use Cookies Plugin?)

  let cookies: Cookies = process.env.CLIENT
    ? Cookies
    : (Cookies.parseSSR(ssrContext) as Cookies);

  if (cookies.has('locale')) langIso = cookies.get('locale');
  let quasar: any = Quasar;
  try {
    await import(
      /* webpackInclude: /(ar|en-us|zh-hans)\.js$/ */
      'quasar/lang/' + langIso
    ).then(lang => {
      console.log('setting language' + langIso);
      quasar.lang.set(lang.default);
    });
  } catch (err) {
    console.log('error settings langauge');
    console.log(err);
    // Requested Quasar Language Pack does not exist,
    // let's not break the app, so catching error
  }
  // Set i18n instance on app
  app.i18n = i18n;
  app.i18n.locale = langIso;
  axios.defaults.headers.common['Accept-Language'] = langIso;
};
export default res;

export { i18n };
```

**Comment by DiaaEddin** [comment]
And even If I am changing the locale of the global it should affect the current request but it does not.

**Comment by DiaaEddin** [comment]
and by the way every thing else is behaving as intended including i18n. the only wrong thing I encountered is the html tag attributes (lang and dir).

**Comment by rstoenescu** [comment]
There you go. You're creating one global instance, then injecting it and sharing it into the new app created for each request... Put the `new VueI18n(...)` inside of the async function so that there is a new instance of it **for each request**, like I mentioned earlier.

**Comment by DiaaEddin** [comment]
@rstoenescu I tried every thing I could but it seems to me that:

1.  `app.$q.locale` that provided in boot file is global and calling `set` changes the value for the whole application affecting later request.
2.   setting `html` tag attributes `lang` and `dir` is happening before calling boot file causing it to render values from the last request.


this is my final `boot/i18n.ts`
```
import Vue from 'vue';
import VueI18n from 'vue-i18n';
import messages from '../i18n';
import langEn from 'quasar/lang/en-us';
import langAr from 'quasar/lang/ar';
import langZhHans from 'quasar/lang/zh-hans';

let langs: any = { 'en-us': langEn, ar: langAr, 'zh-hans': langZhHans };
Vue.use(VueI18n);

let i18n: any = null;

const res: any = async ({ app, ssrContext }: any) => {
  return new Promise(async (resolve, reject) => {
    let langIso = 'en-us'; // ... some logic to determine it (use Cookies Plugin?)
    if (app.$q.cookies.has('locale')) langIso = app.$q.cookies.get('locale');
    i18n = new VueI18n({
      locale: langIso,
      fallbackLocale: 'en-us',
      messages
    });
    app.$q.lang.set(langs[langIso]);
    app.i18n = i18n;
    app.i18n.locale = langIso;
    resolve();
  });
};
export default res;

export { i18n };

```

**Comment by DiaaEddin** [comment]
I moved the code to `store/index.ts` and now it is behaving as it should. looks like the code in `store/index.ts` is getting executed first. any how I could add this code somewhere more convenient. I tried `prefetch` on `App.vue` but It did not work as well.
I am using QuasarCLI, ssr, spa, typescript.
