### ISSUE TITLE
Q-Tree `getTickedNodes` method does not return correct array when calls from the `update:ticked` handler

### ISSUE THREAD

**Issue by garrlker** [quasarframework/quasar#6705]
**Describe the bug**
The `getTickedNodes` method on `q-tree` lags does not contain every ticked node if you call it from the `update:ticked` event handler

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/mgqk3w4j/2/

**To Reproduce**
1. Open the fiddle and open Chrome dev tools
2. Click the checkbox of any of the 3 items. In the console, notice you get the ticked items `id` and the `getTickedNodes` log is an empty array.
3. Click on a second item. Now you correctly get 2 `ids` and the `getTickedNodes` log only displays one node.
4. Keep clicking on items, the `getTickedNodes` log is always one step behind the other call.

**Expected behavior**
`getTickedNodes` returns an array with every ticked node.

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 12.15
NPM: 6.13.4
Browsers: Chrome

**Comment by pdanpdan** [comment]
https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

**Comment by garrlker** [comment]
Hey @pdanpdan ,

![image](https://user-images.githubusercontent.com/7344576/77917787-97f40500-7260-11ea-99d9-256b2b00a8ff.png)
My `ticked` variable _is_ `.sync`'ed and my bug is not with the `ticked` variable.
My bug is with the `getTickedNodes` method _not_ being up to date with `ticked`.

I can't `.sync` a method.

**Comment by pdanpdan** [comment]
I thought you'll understand from the documentation that there is no `.sync`. The value is updated in the `update:ticked` event - you are trying to check the value in the component in the same tick you are updating it. Use a `$nextTick`.

**Comment by garrlker** [comment]
`$nextTick` does fix the bug nicely.

My original issue was more concerned with should `getTickedNodes` already have the updated set when you call from the `update:ticked` event.

But it does make sense that events are still propagating when that is called and it won't be updated by then.

Thank you for you time!
