### ISSUE TITLE
Cannot add to or modify htmlVariables in beforeDev hook in quasar.conf.js unless changing a child of an existing variable

### ISSUE THREAD

**Issue by onexdata** [quasarframework/quasar#6706]
**Describe the bug**
According to the docs, (https://quasar.dev/quasar-cli/quasar-conf-js) you can use the beforeDev build hook to put async/await dev mode tasks in quasar.conf.js. I've done this with success, however, I cannot change the htmlVariables inside this function unless I am modifying a child of an existing variable, otherwise it has no effect.

**To Reproduce**
1. Take any quasar project
2. Edit quasar.conf.js and add a build.beforeDev hook
3. Attempt to add or change any cfg.quasarConf.htmlVariables root item. It will fail without an error (The result will never appear or be available to in index.template.html).
4. However, change a child of a custom variable (i.e. cfg.quasarConf.htmlVariables.myVar.myChildVar), and it works as expected.

**Expected behavior**
This should work as expected or the odd behavior should be documented somewhere.

**Comment by rstoenescu** [comment]
This should be fixed in future "@quasar/app" v2 (to be released really soon).
