### ISSUE TITLE
Q-Dialog (plugin with custom component) and keep-alive

### ISSUE THREAD

**Issue by mila76** [quasarframework/quasar#6707]
**Is your feature request related to a problem? Please describe.**
Is it possibile to make an options (like tabpanel etc) to keep-alive the component used for a dialog?

**Describe the solution you'd like**
Component isn't destroyed on Dialog close if i pass a keep-alice option/props

**Comment by pdanpdan** [comment]
No. The dialog is meant to be a one time disposable element - but you can keep the data and rebuild it from data.
