### ISSUE TITLE
Location of webpack config (needed for vue-styleguidist)

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#6713]
Hello,

as my quasar project is starting to get bigger and bigger I searched for a solution to generate documentation for all my .vue component files out of comments embedded inside the code. I found a few options of which the most promising one is **vue-styleguidist**. This seems to be exactly what I need in order to provide a good overview for my project in the future.

The only problem I am facing is that I need the location of the webpack config file in order to configure vue-styleguideist (https://vue-styleguidist.github.io/docs/Webpack.html#reusing-your-project%E2%80%99s-webpack-config).
I looked at the quasar docs and it seems quasar is doing some magic in the back that there is no need for any sepearte webpack config file (or I simply haven't found the correct info).

Is this possible with quasar to use vue-styleguidist to document my vue components? If yes please guide me in the right direction, how can I accomplish the intigration?
If not are there any good alternatives? I already had a look at Vuese and vue-jsdoc both are not what I need since they only offer very limited documentation features.

Thanks for the help!

**Comment by TobyMosque** [comment]
@Quasarman https://quasar.dev/quasar-cli/cli-documentation/handling-webpack#Introduction
search by `extendWebpack` or `chainWebpack`
