### ISSUE TITLE
Why second Q-Menu is closed when first gets a .hide()? Maybe a bug.

### ISSUE THREAD

**Issue by pdwrl** [quasarframework/quasar#6716]
**jsFiddle**
https://jsfiddle.net/g5bmnk7j/3/

**Description**
I have two q-menus.
The first has to be closed only when clicked outside this menu, but not when clicking another menu.
The second is just a menu :-)
When I clicking on 2nd menu, .hide() is executing in my code to hide 2nd menu.
Why in this case 1st menu is hid too?

**To Reproduce**
1. Click on the Button with label "Click"
2. Click on the Menu 2
3. after .hide() Menu 2 we see that Menu 1 is hid too.

**Expected behavior**
I expect Menu 1 to remain visible.

**Note**
__permanent__ option is not a way for me.

**Comment by alexanderaleskin** [comment]
same problem

**Comment by pdwrl** [comment]
**UPD:**
/node_modules/quasar/src/components/menu/ClickOutside.js
if You delete a line with a code `execHandlers(handlers.focus, evt)`. it works ok.

**Comment by pdanpdan** [comment]
A menu stays open if it's persistent or if focus is inside it.
Try to refocus an element in the first menu when you close another one: https://jsfiddle.net/30rehc6f/10/

**Comment by pdwrl** [comment]
> A menu stays open if it's persistent or if focus is inside it.
> Try to refocus an element in the first menu when you close another one: https://jsfiddle.net/30rehc6f/10/

Thank You very much!
