### ISSUE TITLE
Q-Input field little bug within a form with clearable attribute and enter keypress

### ISSUE THREAD

**Issue by dariodepaolis** [quasarframework/quasar#6719]
**Describe the bug**
Look at the simple form in codepen
I want to submit the form using enter key, but if I use clearable attribute it intercept the form submission clearing the model.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dariodepaolis/pen/GRJLEeN

**Steps to reproduce**
Fill first field, then second field and press enter key to submit.

**Expected behavior**
I think that clear method must not intercept enter keypress and this example form need to be submitted with enter keypress, and clearing method must be called only if I click on the clear button or if I focus on it with tab key.

**Comment by pdanpdan** [comment]
Arrrgg, good catch.

**Comment by dariodepaolis** [comment]
I'm trying on a previous version and it seems to work, maybe it's only a regression bug for #6680 or something similar

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.13.
