### ISSUE TITLE
Datetime i18n

### ISSUE THREAD

**Issue by galan83** [quasarframework/quasar#672]
### Software version

Quasar: Beta 14
OS: OSX
Node: 0.7.3
NPM:3.10.10
Browsers: All
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
day-names and month-names props are not working.
### What were you expecting?
Both props should pass names for months and days in popup calendar.
### What steps did you take, to get the error?

```
        <q-datetime
            monday-first
            v-model="form.scheduled_at"
            type="datetime"
            clear-label="Limpiar"
            ok-label="Aceptar"
            cancel-label="Cancelar"
            format="DD-MM-YYYY HH:mm"
            float-label="Programa la fecha y la hora de publicación"
            :month-names="monthNames"
            :day-names="dayNames"
          ></q-datetime>
```

I have been looking QDateTime.vue in the project folder, and I have found this code section:
```
      <q-inline-datetime
        ref="target"
        v-model="model"
        :default-selection="defaultSelection"
        :type="type"
        :min="min"
        :max="max"
        :format24h="format24h"
        :monday-first="mondayFirst"
        :color="color"
        class="no-border"
        :class="{'full-width': $q.theme === 'ios'}"
      >
```
I you maybe missed pass that props.

Thanks in advance.

**Comment by rstoenescu** [comment]
Thanks for reporting. It is fixed now.
