### ISSUE TITLE
noRouteDismiss don't work when using QDialog as a plugin

### ISSUE THREAD

**Issue by jraez** [quasarframework/quasar#6722]
**Describe the bug**
noRouteDismiss doesn't work when using QDialog as a plugin

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jraez/pen/XWbobqy

**To Reproduce**
1. Go to provided codepen
2. Click on notify
3. wait 3s for a background route change
4. dialog is not closed.

**Expected behavior**
The dialog should be closed.

**Screenshots**
None

**Platform (please complete the following information):**
OS: Win10, Ubuntu
Browsers: Chrome, Firefox, Edge

**Additional context**
Same test with QDialog as a plain component works fine.

**Comment by pdanpdan** [comment]
Hello. `noRouteDismiss` is false by default and it is not processed by the dialog plugin. You need to close the dialog on route change if this is what you need.

**Comment by jraez** [comment]
Maybe add something in the docs because it explains nowhere.
Is there a way to close all dialogs open without have a reference on them? For example, if I ave a axios interceptor that changes the current route, I don't know which dialogs are open in the interceptor code.

**Comment by pdanpdan** [comment]
Sorry for misleading you. The route change is processed by the plugin, but you must pass the vm instance when you open the plugin. Use the `parent` key, like here: https://codepen.io/pdanpdan/pen/yLNrPjK

**Comment by jraez** [comment]
Oh, I see. I have an instance when I call it. Thanks for help!
