### ISSUE TITLE
Set API URL for electron mode in production

### ISSUE THREAD

**Issue by ali-hallaji** [quasarframework/quasar#6723]
How can I set my server API URL in my codes?
I use from electron mode and I want to get build for production. How can I declare my RESTful API server IP address into my quasar.config file?
I upload my file to another server and I use my API from another server IP address.

Also, I ask this question in the [Stackoverflow](https://stackoverflow.com/questions/60979902/set-api-url-for-quasar-in-the-electron-mode-build)

**Comment by pdanpdan** [comment]
https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build, search for `env`.

This is not a place to put help requests - please use the discord server or the forum.

**Comment by ali-hallaji** [comment]
Sorry about that. I asked this there too.
But I need it for the Electron mode.
