### ISSUE TITLE
q-input mask not working well

### ISSUE THREAD

**Issue by lukasztyszko** [quasarframework/quasar#6725]
I created a mask for telephone number with country prefix : '+48#########' or '+48 ### ### ###' and this is not accepting any number starting from '4' or '8', and sometimes if '4' or '8' are included in value the maximum lenght of value and mask are not the same

https://codepen.io/lukasztyszko/pen/NWqmyNV

**To Reproduce**

Try to type those numbers for '+48#########' mask:
* 128 128 128 - err 10chars
* 412 421 421 - err 11chars
* 888 888 888 - err 10chars
* 444 444 444 - err  3chars
* 148 148 148 - err 10chars
* 128 128 128 - err 10chars
* 111 111 111 - ok  12chars

or those numbers for '+48 ### ### ###' mask:
* 111 111 111 - ok  15chars
* 444 444 444 - err  4chars
* 888 888 888 - err  4chars
* 128 128 128 - ok  15chars
* 123 123 852 - ok  15chars

**Expected behavior**
I think q-input with any mask should accept the right amount of characters and let user start typing from any number 

**Edit: **
Now i see this maybe is not bug.. just '+48' characters are not allowed in masks?

**Comment by pdanpdan** [comment]
Closing this to follow in https://github.com/quasarframework/quasar/issues/6969

**Comment by Elchin5757** [comment]
I have same bug, I wrote `mask="+998 ## ### ## ##"` musk, and when i start with 9 or 8 the input doesn't get these nubers. 

how can i fix this issue
