### ISSUE TITLE
qInput set autogrow attribute will make type = "number" lose effect

### ISSUE THREAD

**Issue by 9527Lin** [quasarframework/quasar#6731]
**Describe the bug**
qInput set autogrow attribute will make type = "number" lose effect

codepen:[https://codepen.io/9527lin/pen/RwPmaRM?__cf_chl_jschl_tk__=027215a57c8bb409386489c295aecc136c3b0991-1585901026-0-ASTfzBnjV-dOQQ-EKABeHfznxrEkqOV2qpM6xsxe3z2QAUmczE7J79r8n8vzSjGfiaxu2MfIfned7s8TBQlhDWp4AEthyJaqoIl_hZA1f77v4rQlvf0eiVW0D_hGk23a5dP-l8IrdVf9XmQd-5AYhVnyT6IOwB-a00aPUuHdT6RMTYhdV2lE70kHrnCYAANZVgDpUQrrtBOqVFkyat92IxLjI988kCMXNDYbo2RQIV7A-Gc2i6GBhN7zivsM6pkxIMBa9yA2k2XBpyMbyO3TleqeP5Hb0ZC-vCDuYFSbVv3_kP6sRLkx5zcfASwIRSOPA_uz2dKN1eJUJzYsf6mPJDiefeQ2naTfRpg77oAddDM8](codepen)

**Comment by pdanpdan** [comment]
This is normal, there is not textarea with type number.
