### ISSUE TITLE
Wrong or at least non standard implementation of util throttle

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#6733]
First of all, thank you for sharing with community ❤️ 

**Describe the bug**
throttle function is not executing the last call after protection time runs out, see comparison in following codepen.

You can see also marble diagram https://rxjs-dev.firebaseapp.com/api/operators/throttle

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luckylooke/pen/LYVoRwx?editors=1010

**To Reproduce**
1. Go to https://codepen.io/luckylooke/pen/LYVoRwx?editors=1010
2. Click on Quasar throttle button multiple times (quicker than 2 per sec)
3. As you see count stay stable after last click (should be changed once more after 2sec period runs out)
4. Click same way on Lodash button
5. As you see it works as expected

**Expected behavior**
Execution of provided function should be one more time after time runs out with latest provided arguments.

**Platform (please complete the following information):**
any

Thank you 🙏

**Comment by pdanpdan** [comment]
Hi - by reading the description on rxjs it looks like the throttle function is correct:

- it receives one call => it executes and enter waiting state
- any event received in waiting state is discarded
- the first event received after the waiting state is over restarts the process

To me the lodash implementation seems to be wildly wrong:
- do a quick dbl click on lodash button - there will be:
  - 1 immediate increment
  - another increment after 2 seconds

**Comment by pdanpdan** [comment]
@rstoenescu if the throttle function was not meant to be `{ leading: true, trailing: false }` please reopen - else it's working as expected (even if it's not implementing all the combinations).

**Comment by luckylooke** [comment]
Ok, my fault, I am sorry.. I thought the diagram shows default behaviour.. basicly I need `{ leading: true, trailing: true }` behaviour, which is lodash default, but I agree that quasar implementation is correct after revision, because I consider rxjs more relevant for this area.  Thank you 👍
