### ISSUE TITLE
Little improvement for safe area insets

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#6734]
Hello, I think
```
body.q-ios-padding .q-dialog__inner > div {
  max-height: calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom)) !important;
}
```
could be written like this:
```
.q-dialog__inner > div {
  max-height: calc(100vh - env(safe-area-inset-top, 0) - env(safe-area-inset-bottom, 0)) !important;
}
```
There can be systems other than ios that use safe area insets. Specifying 0 as a default value if there are no environment variables of a given name does the job. Not using descendance selectors will also improve performance. The only use I see for  a class on the body would be to easily disable the insets applied by Quasar, is that what it's here for? Because I'd be happy to get rid of them and manage insets myself, as I said in another ticket. Thank you

**Comment by rstoenescu** [comment]
Hi,

Thank you for writing a detailed ticket.
However, I have two comments:

1. CSS selector speed is not actually faster nowadays. You can't even say that selectors which contain attributes are slower than the other. Browsers have evolved a lot. There's lots of metrics available on the net regarding this.

2. This auto padding is one of the places which one might think that it can be done better. The matter of fact is that the current state is perfectly aligned (and as refined as possible) to work cross-platforms, including iOS with Safari mobile and Chrome mobile, iOS on Capacitor, iOS on Cordova, Android with Chrome mobile, Android on Capacitor, Android on Cordova, etc etc and on a million scenarios (layouts, dialogs etc etc). Explaining all the cases would take a day.

We'd prefer to leave things oiled as they are. If there is some special case, there is always the option for custom CSS to override the stock Quasar behavior.

**Comment by louisameline** [comment]
Ok, thank you for your reply.
