### ISSUE TITLE
Mobile Uncaught TypeError: win.focus() is not a function @ open-url.js:24

### ISSUE THREAD

**Issue by tommulkins** [quasarframework/quasar#6738]
**Describe the bug**
When clicking a link using openURL helper in built Cordova app (iOS & android) the following console error is generated:

```
Uncaught TypeError: win.focus is not a function
    at open-url.js:24
    at HTMLAnchorElement.<anonymous> (extensions.js:34)
```

Because of the directness of the error I did not prepare a codepen since it's present only on mobile apparently.  On `line 24` of built script `open-url.js` you will find the offending call to `win.focus()` being made.

**Comment by rstoenescu** [comment]
Hi,

When wrapping with Cordova (or Capacitor), it's best if InAppBrowser cordova plugin is also installed so that openURL can hook into that. But regardless, fixed the offended instruction. Thanks for reporting.

Fix will be available in "quasar" v1.9.13.
