### ISSUE TITLE
Feature Suggestion - enhanced textareas with "autogrow" and character count

### ISSUE THREAD

**Issue by nootn** [quasarframework/quasar#674]
I frequently need text areas that allow a lot of text to be entered.  Using the base text area (http://quasar-framework.org/components/textarea.html) I think it would be good to have some extra options:

1) autogrow (boolean - defaulted to false)
The way I have implemented this in other frameworks with positive reviews from users is to add an "autogrow" feature,  where instead of setting a height and as people type too much they get a scrollbar, it grows the text area so that it has the correct height to fit the text.  So you never get a scrollbar.
(E.g. a jquery one: https://plugins.jquery.com/autogrow/)

2) character count (maxchars int property = if null no character count shows,  if it's set, it has a count such as 15/200, as they type another character it would say 16/200).
(E.g. a jquery one: http://www.jqueryscript.net/demo/jQuery-Character-Counter-Limiter-For-Textarea/)

**Comment by rstoenescu** [comment]
Both are in Quasar v0.14.

**Comment by nootn** [comment]
Ah yes, sorry I was looking at the doco and couldn't see it, but looking at the showcase it's there.  Looks great,  thanks heaps!
