### ISSUE TITLE
Missing App Icons for Electron (Linux)

### ISSUE THREAD

**Issue by nikolayhg** [quasarframework/quasar#6740]
**Describe the bug**
The app icons of a fresh new electron application are missing on Linux.

**To Reproduce**
1. Run:
`npm install -g @quasar/cli`
`quasar create testproject`
`cd testproject`
`quasar mode add electron`

2. Run '`ls src-electron/icons/`'
3. Result is: `icon.icns  icon.ico  linux-512x512.png`

**Expected behavior**
All icons described in the official [Documentation](https://quasar.dev/quasar-cli/developing-electron-apps/app-icons-electron) should have been created.

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 13.12.0
NPM: 6.14.4
Yarn: 1.22.4
Electron: 8.2.0

**Additional context**
```
$ quasar info

Operating System - Linux(4.15.0-91-generic) - linux/x64
NodeJs - 13.12.0

Global packages
  NPM - 6.14.4
  yarn - 1.22.4
  @quasar/cli - 1.0.5
  cordova - Not installed

Important local packages
  quasar - 1.9.12 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.6.1 -- Quasar Framework local CLI
  @quasar/extras - 1.6.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.6 -- Official router for Vue.js 2
  vuex - 3.1.3 -- state management for Vue.js
  electron - 8.2.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.9.0 -- Babel compiler core.
  webpack - 4.42.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.10.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
```

**Comment by nikolayhg** [comment]
Solved. After Step 1 I run `quasar ext add @quasar/icon-genie`.

**Improvement Suggestion**: Describe in the [Electron documentation](https://quasar.dev/quasar-cli/developing-electron-apps/app-icons-electron) that the Quasar Icon Genie app extension should be installed.

**Comment by rstoenescu** [comment]
You should really use Icon Genie v2 instead of Icon Genie v1.

**Comment by vilas2488** [comment]
here is the solution for that... 
"linux": {
      "target": [
        "deb"
      ],
      "icon": ".//logoassets/uxp"
    }
in uxp folder give icon name as size of icon like 256x256.png or 512x512.png

**Comment by gvorster** [comment]
I added icon property to electron-main.js and now the icon is showing in the Ubuntu sidebar.

```
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    useContentSize: true,
    webPreferences: {
      contextIsolation: true,
      // More info: /quasar-cli/developing-electron-apps/electron-preload-script
      preload: path.resolve(__dirname, process.env.QUASAR_ELECTRON_PRELOAD)
    },
    icon: path.join(__dirname, 'icons/linux-512x512.png')
  })
```
