### ISSUE TITLE
[BEX] ES6 module export on background.js

### ISSUE THREAD

**Issue by dlopezp** [quasarframework/quasar#6744]
**Describe the bug**
When you add the BEX mode to a project, the file `src-bex/background.js` has the next code:
```
// Background code goes here

export default function attachGlobalBackgroundHooks (chrome) {
  chrome.browserAction.onClicked.addListener((tab) => { // eslint-disable-line no-unused-vars
    // Opens our extension in a new browser window.
    chrome.tabs.create({
      url: chrome.extension.getURL('www/index.html')
    }, (newTab) => { // eslint-disable-line no-unused-vars
      // Tab opened.
    })
  })
}
```
And, if you add the extension to a browser, you get an error on this file:
` Uncaught SyntaxError: Unexpected token 'export'`

**Codepen/jsFiddle/Codesandbox (required)**
I dont know how make a COdepen of a browser extension

**To Reproduce**
1. Clone https://github.com/quasarframework/quasar and swotch to `bex-review` branch
2. Build `app` folder
3. Create a new quasar project and replace `@quasar/app` dependency path to your local fork. ie: 
`"@quasar/app": "link:../quasar/app"`
4. Reinstall dependencies of you project
5. Add `bex` mode to the project: `quasar mode add bex`
6. Start development server `quasar dev -m bex`
7. Add the extension to a browser
8. You can see the error on the extensions manager
**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS: MacOS 10.15.3
Node: 12.16.0
NPM: 6.13.7
Yarn: 1.22.0
Browsers: Chrome 80.0.3987.163
iOS: -
Android: -
Electron: -

**Additional context**
The content of `src-bex/background.js` come from this file
https://github.com/quasarframework/quasar/blob/bex-review/app/templates/bex/js/background.js

**Comment by rstoenescu** [comment]
Fixed.

**Comment by radiantone** [comment]
I tried using the default content script that quasar creates for my extension, but it doesn't work at all. First, was this error
```
SyntaxError: Cannot use import statement outside a module (at my-content-script.js:4:1)
```
then this error
```
SyntaxError: Unexpected token 'export'
```
