### ISSUE TITLE
Q-Carousel prev-icon next-icon object support

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#6747]
I'm trying to use Icons from SVG method to decrease my bundle size, but I can't use it on Q-Carousel nav icons because it supports only icon string name

**Comment by rstoenescu** [comment]
Hi,

Can you elaborate on your request pls? What SVG are you using? Are you importing a file, is it in statics, is it [....]? Please detail exactly what you want to do.

But first, make sure that you read https://quasar.dev/vue-components/icon#Svg-icons and also https://quasar.dev/vue-components/icon#Inlined-svg

**Comment by eladcandroid** [comment]
@rstoenescu 
First, thanks for your quick reply! You're doing an awesome work...

I'm talking about using an imported SVG icon like in this example, on Q-Carousel prev/next icon:
https://quasar.dev/vue-components/icon#Svg-usage
(I don't use any of icons libraries on quasar.conf.js)

The navigation dots also doesn't show up using that method..

My code is something like:

```javascript
<q-carousel
        v-model="slide"
        :prev-icon="matArrowBack"
        :next-icon="matArrowForward"
        swipeable
        animated
        control-color="white"
        navigation
        padding
        height="300px"
        class="bg-primary text-white shadow-1 rounded-borders"
      >
....

<script>
import { matArrowBack, matArrowForward } from '@quasar/extras/material-icons'

export default {
  // ...
  created () {
    this.matArrowBack = matArrowBack
    this.matArrowForward = matArrowForward
  }
}
...
</script>
```

**Comment by rstoenescu** [comment]
Hi,

Works just fine... [y.zip](https://github.com/quasarframework/quasar/files/4437265/y.zip)
Check your deps, if you have any errors in console etc.
