### ISSUE TITLE
[docs] Owasp link about XSS seems to be dead.

### ISSUE THREAD

**Issue by PrinceOwen9466** [quasarframework/quasar#6749]
I put my outside shoes on, and scrolled back up to read OWASP's article about XSS, but the link seems to be dead. Where else can I get good information about these attacks? 

Thanks for the helpful resource by the way.
Resource Link: (https://quasar.dev/security/dos-and-donts#Final-Note).

Regards,
Prince.

**Comment by smolinari** [comment]
Fixed.

Scott
