### ISSUE TITLE
Capitalize also for uppercase values

### ISSUE THREAD

**Issue by dvbeek** [quasarframework/quasar#6751]
**Is your feature request related to a problem? Please describe.**
Values may sometimes be in uppercase (for example enum values from the server), where capitalize would also be helpful.

**Describe the solution you'd like**
It would be nice if capitalize would also work for these uppercase values, without having to also call toLowerCase() first.

**Describe alternatives you've considered**
I.e. in table I now have to use: format: val => capitalize(val.toLowerCase())
(instead of format: capitalize)

Just an idea...
No problem to close this issue, if it isn't desired or it's too much risk for breaking current implementations or something...

**Comment by pdanpdan** [comment]
This is no possible by default, because the most frequent case is the one where you have uppercase acronyms. and `capitalize(val.toLowerCase())` is exactly what is to be done.
