### ISSUE TITLE
QTab's aren't symmetrical when QTabs align="justify".

### ISSUE THREAD

**Issue by luizhenriquerdias** [quasarframework/quasar#6752]
Aren't QTab suppose to be equaly spaced when used within QTabs with justify alignment?
In the codepen below, I put a QSeparator between the QTab to make it easier to view. You can view it with the inspect tool of the browser aswell.

https://codepen.io/luizhenriquerdias/pen/NWqQxEw

**Expected behavior**
QTab to be equaly spaced, making it symmetrical.

**Comment by pdanpdan** [comment]
It's more like it'll give each tab an equal weight based on the native width (flex: 1 1 auto)

**Comment by luizhenriquerdias** [comment]
Yeah! Thank you!
Anyway, maybe this should be the default behavior when align="justify" in QTabs.

**Comment by pdanpdan** [comment]
If it would be default it wouldn't be easily reversible - so you'll need to make some very specific CSS to make them not be equal.
Like it is now you just add a class to the tabs.

**Comment by luizhenriquerdias** [comment]
Fair enough. Thank you!
