### ISSUE TITLE
[Request] QFab hide-icon prop

### ISSUE THREAD

**Issue by gaby64** [quasarframework/quasar#6753]
I would like to have a text only fab

currently not setting the icon leaves the icon space visible

this could be enabled when icon is undefined/null

**Comment by smolinari** [comment]
If you remove the icon prop and put text between the QBtn tags, then you'll have a text only FAB. 

Scott

**Comment by rstoenescu** [comment]
`hide-icon` Boolean prop will be available in "quasar" v1.9.14 for both QFab and QFabActions. Note that you should then use an internal label.

**Comment by rstoenescu** [comment]
Small change. Removed "hide-icon" for QFabAction -- not specifying an icon will suffice. "hide-icon" will remain only for QFab.

**Comment by gaby64** [comment]
thanks
