### ISSUE TITLE
QInput on IE11

### ISSUE THREAD

**Issue by zarpou** [quasarframework/quasar#6759]
**Describe the bug**
Hello guys, when using QInput in IE11 I get the following error on the console:

```javascript 
TypeError: The object does not support the 'slice' property or method
```

**Codepen/jsFiddle/Codesandbox (required)**
None of the editors support IE11, but just use the example given by quasar and put the QInput component and look at the console

**To Reproduce**
1. Copy example Quasar (https://quasar.dev/start/umd)
2. Use QInput componet and run on IE11

**Expected behavior**
The object does not support the 'slice' property or method

**Screenshots**
![Anotacao_2020-04-07_040513](https://user-images.githubusercontent.com/62584555/78703866-56f39480-78e1-11ea-84af-3f9088e33b2a.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: - 
NPM: 6.13.6
Yarn: 1.22.4
Browsers: IE11
iOS: -
Android: -
Electron: -

**Additional context**
Talking to people on discord, Polyfill was found for the slice method, after adding this code to my JS file it worked perfectly

```javascript
//Polyfill for slice 
//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice
if (!Uint8Array.prototype.slice) {
  Object.defineProperty(Uint8Array.prototype, 'slice', {
    value: function (begin, end)
     {
        return new Uint8Array(Array.prototype.slice.call(this, begin, end));
     }
  });
}
```

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.14.
