### ISSUE TITLE
Not possible to run application via filesystem?

### ISSUE THREAD

**Issue by jn73** [quasarframework/quasar#676]
Not sure if it is supposed to run the app directly from filesystem - if so, there's a problem :)

I'm on edge-build and tried to run the production code under dist/ directly from chrome via file:///<path to dist>/index.html.

Chrome shows this in console log: vendor.js:6 GET file:///Users/janeriksson/projects/private/gbox-client/dist/cordova.js net::ERR_FILE_NOT_FOUND

I guess it's similar to https://github.com/quasarframework/quasar/issues/485 and that cordova is assumed since there is no http in the url.

**Comment by rstoenescu** [comment]
It clearly says at end of building a quasar website/app:
```
 Build complete with "mat" theme in "/dist" folder.

 Built files are meant to be served over an HTTP server.
 Opening index.html over file:// won't work.
```
Use "quasar serve" command to see it in your browser. It won't work in browser if you use Cordova plugins, for obvious reasons.
