### ISSUE TITLE
[docs] Windows Cordova android.bat from the command line

### ISSUE THREAD

**Issue by jackedai** [quasarframework/quasar#6760]
In reference to documentation at:
[quasar-cli/developing-cordova-apps/preparation]( https://quasar.dev/quasar-cli/developing-cordova-apps/preparation)

Google has deprecated the AppData\Local\Android\Sdk\Tools folder that contained android.bat, it has been moved to AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat

To re-enable this deprecated functionality you have to go into Tools > SDK Manager > SDK Tools, then untick 'Hide Obsolete Packages' and tick 'Android SDK Tools (Obsolete)'

This isn't covered in the documentation and took about 30 mins to figure out, I'm not sure if there are plans for quasar cli to reference the new sdkmanager.bat instead of android.bat, but if not the documentation could use an update so new users don't get frustrated.

**Comment by webnoob** [comment]
@rstoenescu Do we want to do anything re: updating the CLI to use the new sdkmanager.bat file?

**Comment by rstoenescu** [comment]
Isn’t the cordova and capacitor cli’s job?

**Comment by webnoob** [comment]
Yes, you're right. Stupid moment :)

**Comment by webnoob** [comment]
Confirmed the issue and PR'd a warning.

**Comment by jackedai** [comment]
Awesome work, I love Quasar by the way, it's an amazing framework with incredibly good documentation!
