### ISSUE TITLE
[docs] -  Uncertainty with ordering flex boxes

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#6761]
Hi,

Not sure it is a bug or just a bit of missing clarity in the docs. It says here:

https://quasar.dev/layout/grid/introduction-to-flexbox#Order

>use order CSS property and assign the desired value.

Does "assign the desired value" mean using the style attribute as in `style="order: 2"` as demonstrated in the docs, or should it be possible to also do `class="order-2"`? If the latter should be possible, it doesn't work. 

https://codepen.io/smolinari/pen/mdebwjz

See the second examples. First ones are using "style". 

It was also brought to my attention that Vuetify allows for `class="order-2"` and they also include breakpoints, as in `class="order-md-2"`.  https://vuetifyjs.com/en/styles/flex/#flex-order

Once I understand what the correct way is to look at this from Quasar's perspective or if there is any fixes or enhancements needed(made from someone else, as I am not a designer), I can help do any docs updating necessary. :smile:

Scott

**Comment by smolinari** [comment]
The user I was helping on this issue came up with this solution. 
```
body.screen--xs {
  .order-ad {
    order: 0;
  }
  .order-attendance {
    order: 1;
  }
}
body.screen--sm {
  .order-ad {
    order: 1;
  }
  .order-attendance {
    order: 0;
  }
}
```
and said he felt it was a workaround. As, according to the docs, using the body classes will add time to first meaningful paint for the app.

Scott

**Comment by rstoenescu** [comment]
Adding order-N classes is not an option. It adds a lot of KB to the CSS files and for what? For something that can be easily added directly by the developer.

You don't have to use the body classes. You can use pure CSS with media queries and Sass/Stylus variables provided by Quasar:
```
@media (max-width: $breakpoint-xs-max)
  .order-ad
    order: 0
  .order-attendance
    order: 1

@media (min-width: $breakpoint-sm-min and max-width: $breakpoint-sm-max)
  .order-ad
    order: 0
  .order-attendance
    order: 1
```

**Comment by smolinari** [comment]
Thanks Razvan. I'll let the user know. 

Scott
