### ISSUE TITLE
Variable Icon for QTab alert

### ISSUE THREAD

**Issue by hebinet** [quasarframework/quasar#6762]
**Is your feature request related to a problem? Please describe.**
We use the alert property of QTab to display if an validation error has occured in that Tab.
But in our application we use a warning sign on validation error to show the user the error.

**Describe the solution you'd like**
Please add a new property like `alert-icon` to change the shown icon. This could be used like that `alert-icon="alarm"` In this case it would use the alarm icon from materialize design or whatever icon pack is configured.

**Describe alternatives you've considered**
If the above solution is not easily implementable, it would also be possible to use a custom slot for that.

**Additional context**
Before:
![image](https://user-images.githubusercontent.com/24890467/78748227-c4e49e00-796b-11ea-92e6-d8f4b236f77a.png)
After:
![image](https://user-images.githubusercontent.com/24890467/78748521-81d6fa80-796c-11ea-9ea0-6f3d8f467c4f.png)

**Comment by rstoenescu** [comment]
New prop (alert-icon) will be available in "quasar" v1.9.14.
