### ISSUE TITLE
Notify icon & color bug 

### ISSUE THREAD

**Issue by OnlyReFLeX** [quasarframework/quasar#6763]
https://quasar.dev/quasar-plugins/notify#With-icon-or-avatar

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/27870021/78769586-389ba080-7996-11ea-8622-c37e5c2cedc8.gif)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in "quasar" v1.9.14.
