### ISSUE TITLE
i'm having a problem reading .yml files !

### ISSUE THREAD

**Issue by JbFiras** [quasarframework/quasar#6766]
Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---

**Comment by pdanpdan** [comment]
For help requests please head to the discord channel or to the forum.
But in your case please head to the documentation for webpack.

**Comment by rstoenescu** [comment]
@JbFiras so install the loader and use quasar.conf.js > build > extendWebpack/chainWebpack to add the appropriate rule.
