### ISSUE TITLE
QEditor selected text cannot be changed style in IE11

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#6769]
**Describe the bug**
It is not possible to select text and change its style under IE11 (bold/italic/underlined).

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/editor

**To Reproduce**
1. Open link in IE11
2. Write some texts in QEditor
3. Select text
4. Put in bold
5. ???
6. Profit

**Expected behavior**
It should do the same as in Chrome, change text into the selected format

**Comment by pdanpdan** [comment]
Fixed in quasar 1.9.15
