### ISSUE TITLE
[Request] Add Filter/Search to Dialog Select 

### ISSUE THREAD

**Issue by silverphoenix1110** [quasarframework/quasar#677]
Hi authors, thanks for your fantastic framework.
Could you add an input to filter/search to Dialog Select Component? 
We have a same option in  Select Component, and it very useful with users.
P/S: Could you set default to focus into search input while user click to open the dropdown list?

**Comment by rstoenescu** [comment]
Will do. In next v0.14.7

**Comment by rstoenescu** [comment]
Hi, In v0.15 the QDialogSelect has been removed. You can however use the QSelect for same effect. So closing this as QSelect has filter.
