### ISSUE TITLE
Bug: Vue-loader dependency

### ISSUE THREAD

**Issue by vuvandong** [quasarframework/quasar#6770]
ERROR  Failed to compile with 2 errors                                                  6:25:10 PM

This dependency was not found:

* @/components/HelloWorld.vue in ./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loade
r/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @/components/HelloWorld.vue

This relative module was not found:

* ../assets/logo.png in ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options
!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=template&id=4bc9d
7de&

**Comment by rstoenescu** [comment]
Hi,

Check your import statements and your path to logo.png. There must be an error.. some relative path is not right. Also, have you manually added the "@" webpack alias (that's not an alias created by Quasar CLI).
