### ISSUE TITLE
Virtual-scroll can be better, such as web.skype.com, it does not have blank space when scrolling.

### ISSUE THREAD

**Issue by varjay** [quasarframework/quasar#6777]
**Is your feature request related to a problem? Please describe.**
Virtual-scroll will appear blank when scrolling, some customers feel uncomfortable, if you can, please optimize it.

**Describe the solution you'd like**
web.skype.com is the best solution for virtual scrolling I have seen, but no one has yet implemented it.

Thank you for your contributions!

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, it cannot be further optimized and still work with vuejs and on all platforms (including iOS). We will keep an eye on this one though. Thank you for your suggestion.
