### ISSUE TITLE
Breadcrumbs and text when small

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#678]
### Software version

Quasar: 0.14
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
When the Quasar Breadcrumb component is on a small screen and it seems the text labels are hidden, they are actually wrapping and if they are the same color as the page background it seems as if they are hidden.

### What were you expecting?
The labels should be clipped so that they do not take up space and are no visible if they would have wrapped.

### What steps did you take, to get the error?
You can see the error on the phone example here: http://beta.quasar-framework.org/components/breadcrumb.html

**Comment by rstoenescu** [comment]
Hi, Breadcrumbs have their own component in v0.15, so this issue is outdated since the implementation is revamped. Your issue will no longer happen.
