### ISSUE TITLE
Webstie not reloaded on updating state.js files in the store

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#6780]
**Describe the bug**
When I change something in the file ‘/store/navigation/state.js’, say I change ‘label: “About”’ to ‘label: “About2222”’, the webpage is not reloaded automatically after saving the file.

Quasar detects the change as I see it re-running in the terminal when the file is saved but the browser needs a manual refresh by clicking the refresh button or hitting F5. Don’t know if this is me, Quasar or a plugin that is failing.

**Codesandbox **
Check out the [header file on codesandbox](https://codesandbox.io/s/falling-sea-s33z7?file=/src/components/Header.vue) and the [state.js file](https://codesandbox.io/s/falling-sea-s33z7?file=/src/store/navigation/state.js). If you change something in state.js a manual refresh is needed.

**To Reproduce**
1. Start the server, see the page correctly loaded
2. Change the the label of the header from 'About' to 'SomethinngElse' in the file src/store/navigation/state.js
3. Notice the browser didn't reload itself

**Expected behavior**
A reload of the browser window

**Comment by rstoenescu** [comment]
This would be a bug in the the vue or webpack HMR at best.
Not a ticket for Quasar.

**Comment by DarkLite1** [comment]
Thanks for the feedback @rstoenescu , appreciate it. I opened the same [bug report with webpack](https://github.com/webpack/webpack/issues/10697).  They think it's a Quasar issue. 

As a novice web developer I don't really understand the internals and what does what. So maybe you can shime in here to clear things up a bit.

**Comment by rstoenescu** [comment]
Will look at it, but from my own experience, I get everything to reload just fine.

**Comment by smolinari** [comment]
Is this only happening in Codesandbox?

Scott

**Comment by DarkLite1** [comment]
o, it's aslo happening on my server where I develop.

**Comment by smolinari** [comment]
Remove the code in the store's `index.js` file. That fixed it on codesandbox.

```
if (process.env.DEV && module.hot) {
    module.hot.accept(['./tickets', './navigation'], () => {
      Store.hotUpdate({
        modules: {
          tickets: require('./tickets').default,
          navigation: require('./navigation').default
        }
      })
    })
  }
```

Scott

**Comment by DarkLite1** [comment]
Thannk you Scott, that fixed indeed the issue. From the docs I thought we needed that to be able to use hot reloading. Maybe I'm just not understanding what hot reloading means but this will do just fine for me for now.

I'll close the ticket wtih Webpack too. Thannk you verh much and have a nice day.
