### ISSUE TITLE
[q-tab q-badge and alert]:Dislocation of seats:open 

### ISSUE THREAD

**Issue by HuiJunTNT** [quasarframework/quasar#6785]
![image](https://user-images.githubusercontent.com/37110122/79004095-9d1d5200-7b86-11ea-923f-9fa1b20286b7.png)

**Comment by pdanpdan** [comment]
I'm sorry you have that bad picture - you can try to adjust it in Photoshop. :)

On a more serious note:
- a description of what do you mean
- a codepen that show the problem
- fill the issue template

**Comment by pdanpdan** [comment]
When you have details please reopen.
