### ISSUE TITLE
this.$q.notify  is undefined

### ISSUE THREAD

**Issue by Lyqxyz** [quasarframework/quasar#6786]
this.$q.notify  is undefined

**Comment by pdanpdan** [comment]
Hello. Please fill the info required in the issue template.
I quick guess is that you should read the docs, the part about installing plugins.

**Comment by Lyqxyz** [comment]
I didn't see how to install the plug-in like notify in the official document

**Comment by pdanpdan** [comment]
Where have you looked? The url, please.

**Comment by rstoenescu** [comment]
It's right there in the docs... https://quasar.dev/quasar-plugins/notify
