### ISSUE TITLE
Disable mini-mode on larger vewport sizes

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#6787]
**Is your feature request related to a problem? Please describe.**
Currently [q-drawer](https://quasar.dev/layout/drawer#QDrawer-API) accepts a lot of properties, which is really great to mix and match what you need. Using these I ended up with a sidebar that does exactly what it's designed for. However, I'm struggling to have q-drawer expanded (or not in mini-mode to be more correct) when the viewport is larger than 1023px (md). See q-drawer in the [codesandbox](https://codesandbox.io/s/falling-sea-s33z7?file=/src/components/Sidebar.vue) for a better understanding..

**Describe the solution you'd like**
I would like to have an extra property on q-drawer to set the width at whcih mini is always set to false, regardless of what input it receives, Something like `mini-breakpoint="1023"`, this would then mean, if the viewport is larger than 1023pc mini-mode is disabled and the drawer is expanded. However, v-model can still be used to collapse/expand the drawer. Only mini-mode is affected here.
```
  <q-drawer
    v-model="drawerState"
    @mouseover="miniState = false"
    @mouseout="miniState = true"
    :mini="miniState"
    mini-breakpoint="1200"
    :width="200"
    :breakpoint="500"
    show-if-above
    bordered
    content-class="bg-grey-3"
    class="gt-xs"
  >
```

**Describe alternatives you've considered**
I have considered duplicating the q-drawer with [classes like](https://quasar.dev/style/visibility#Window-Width-Related) `lt-md` and `gt-xs`, but that's not working out. Another option was to use the [ResizeObserver](https://quasar.dev/vue-components/resize-observer#Introduction) to set `:mini="false"`. But that comes at a price as it states in the docs "_overusing it is costly too._"

**Additonal**
On large displays/viewports, mini mode makes no sense. So this option would be useful to cover those cases.

**Comment by pdanpdan** [comment]
Hello. You just need to check the size in you code: https://codesandbox.io/s/elastic-bush-lxoik?file=/src/components/Sidebar.vue

Please use the discord channel or the forum for help requests. Thank you.

**Comment by DarkLite1** [comment]
Thank you for the elegnt solution. But when I resizie the window it is a serious performance hit. The CPU goes from 12% idle to 35% upon a single resize. I was hoping that this would've been possible within the css. like how breakpoint can be set on q-drawer and doesn't have a performance impact. 

Thank you for reconsidering this feature request as I think it's not uncommon for people to want to have mini mode disbaled on large dispays but not on smaller ones.

**Comment by DarkLite1** [comment]
I just tested it, even without your code it goes up the CPU. So it makes no difference and my remark was incorrect. Sorry for that...
