### ISSUE TITLE
quasar create muzi   is fail

### ISSUE THREAD

**Issue by LXQlxq** [quasarframework/quasar#6789]
PS G:\workspace\quasarchs> quasar create muzi

  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|

? Target directory exists. Continue? Yes
? Project name (internal usage for dev) muzi
? Project product name (must start with letter if building mobile apps) Quasar App
? Project description A Quasar Framework app
? Author lixiaoqing <lixiaoqing@whalejoy.com>
? Pick your favorite CSS preprocessor: (can be changed later) None
? Pick a Quasar components & directives import strategy: (can be changed later) Auto import
? Check the features needed for your project:
? Cordova/Capacitor id (disregard if not building mobile apps) no
? Should we run `npm install` for you after the project has been created? (recommended) NPM

  Quasar CLI · Generated "muzi".

 [*] Installing project dependencies ...

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-11T09_48_10_971Z-debug.log

 npm install FAILED... Possible temporary npm registry issues?
 Please try again later...

**Comment by LXQlxq** [comment]
How to Solve It??????????

**Comment by pdanpdan** [comment]
Hello. Please fill the details required in the issue template. I would guess you either have node v13 or a node before 10.
