### ISSUE TITLE
[Request] Select all for QDataTable

### ISSUE THREAD

**Issue by lyquocnam** [quasarframework/quasar#679]
i see currently, quasar is beta, but this still missing. Author, please add more features to QDataTable, this really need when multi select on many records.

**Comment by mstaack** [comment]
datatable will  be redone after 0.14 is done... so please wait

**Comment by rstoenescu** [comment]
This will get done. As mstaack said, please be patient.
Closing as it is duplicate of https://github.com/quasarframework/quasar/issues/560

**Comment by lyquocnam** [comment]
thanks so much @mstaack @rstoenescu
