### ISSUE TITLE
Capacitor build has issue with androidX support

### ISSUE THREAD

**Issue by sharmaankit25** [quasarframework/quasar#6790]
**Describe the bug**
When i build my project with capacitor it shows build error in AndroidManifest.xml stating:

AndroidManifest.xml: 22:18-91 Error: Attributes @application@appComponentFactory value=(android.support.v4.app.coreComponent) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml 22:18-91 is also present at [androidx.core:core:1.2.0] AndroidManifest.xml 24.18-86 value=[androidx.core.app.coreComponentFactory]

**suggest adding _'tools:replace="android:appComponentFactory"'_ to <application> in AndroidManifest.xml**

**To Reproduce**
1. quasar build -m capacitor -T android --ide

(I use ide to build using quasar build -m capacitor -T android always generate corrupt package)

**Expected behavior**
Build should succeed

**Additional context**
I fixed it by
1.In AndroidManifest.xml replace **android:name="android.support.v4.content.FileProvider"** with **android:name="androidx.core.content.FileProvider"**
2. In gradle.properties file add 
**android.useAndroidX=true
android.enableJetifier=true**

Ps: I am new to the community i don't know if it is the expected behaviour is to be fixed

**Comment by rstoenescu** [comment]
Hi,

This should be reported on Capacitor as it is outside of our reach.
