### ISSUE TITLE
Having issue with the first item of QExpansionItem element.

### ISSUE THREAD

**Issue by PremiumNoFreemium** [quasarframework/quasar#6791]
Having issue with the first item of QExpansionItem element.
And now I just copied example of the QExpansionItem.
Then put it into a component. I write some CSS. It just hides ``footer-pc.vue`` component on mobile screen sizes and so hides ``footer-mob.vue`` in PC screen sizes. Just this is only. Nothing more.

I am now creating a new CodeSandbox for that. But I don't know when I finish that.

Expected: Normal working QExpansionItem component just in the footer.

![image](https://user-images.githubusercontent.com/60849894/79042852-8d4c4f00-7c14-11ea-8936-9ae4ed7a4883.png)

This is my component

[FooterProblem.zip](https://github.com/quasarframework/quasar/files/4464541/FooterProblem.zip)

And you can see full problem in the video above. I just zipped it.

Here there only the first item is not behaving normal. Other QExpansionItems are working.

OS: Windows 10 Latest
Quasar/CLI: ^1.0.5
Quasar/app: ^1.5.8
Quasar version: 1.9.14
Node:  8.9.0
NPM:.6.0
Yarn: 1.6.0
Browsers: Firefox, Chrome, Opera, Safari
iOS: on IOS not tested
Android: Tested but has bug like PC browsers
Electron: not builded electron app

So, I don't know anything about that. Why it may be happening and how to avoid it and make it to behave normal .

**Comment by pdanpdan** [comment]
Hello. Please use the discord channel or the forum for help requests. Also it would help to describe the problem in words when you ask for help there, and provide a way to reproduce that does not require the potential helper to put his system in danger.
