### ISSUE TITLE
q-checkbox possibility to reverse behavior for the array values

### ISSUE THREAD

**Issue by tpoxa** [quasarframework/quasar#6793]
**Is your feature request related to a problem? Please describe.**
I would like to use checkbox array of values feature but vice versa. I have an array of skipped values. The disabling checkbox should add value to this array. 

**Describe the solution you'd like**
IMHO If I set :true-value="false" and :false-value="true" it should affect on array search 

**Describe alternatives you've considered**
Some kind of reverse option

**Additional context**
Such behavior would be useful for any kind of skip list, ignore list.

**Comment by pdanpdan** [comment]
Hello. I'm not sure I understand what you mean, but if I understand correctly than you just need to be creative: https://codepen.io/pdanpdan/pen/NWGPVNr?editors=1010

Please use the discord channel or the forum for help requests.

**Comment by tpoxa** [comment]
You understood me wrong. I was talking about built in functionality into checkbox and toggles. When val is using as element for array in v-model. And that this functionality allows only adding val into the v-model when checkbox is enabled. BTW Your creativity looks terrible.

**Comment by pdanpdan** [comment]
Ty. Please make a codepen with what you would want to happen.
