### ISSUE TITLE
Masonry mode on grid row

### ISSUE THREAD

**Issue by PH7-Jack** [quasarframework/quasar#6795]
**Is your feature request related to a problem? Please describe.**
Um recurso similar ao do [link](https://tobiasahlin.com/blog/masonry-with-css/), para fazer as colunas da grade auto ajustar nos espaços livres

**Describe the solution you'd like**
Grid columns with masonry

**Comment by pdanpdan** [comment]
Hello. This is a nice solution, but it is something highly specific (at most 3 columns) and need css adjustment for each use case, so it cannot be implemented in a framework.
Please use English, thank you.

**Comment by rstoenescu** [comment]
@pdanpdan pls create an example in docs with this technique
