### ISSUE TITLE
Progress Bar 'reverse' option [feature request]

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#680]
I'm using the [Progress Bar](http://beta.quasar-framework.org/components/progress-bar.html) to count down things instead of up. Therefore I'd love to see a "reverse" option available seeing it get emptied in horizontal mirror to the current way.

**Comment by rstoenescu** [comment]
This sounds like a really custom thing needed in your app, but a progress bar is a progress bar showing how much of a process the user is at.
If you really want a horizontal mirror of progressbar, then add a `transform: rotate(180deg)` to it.
