### ISSUE TITLE
Tabindex on qipunt with clearable

### ISSUE THREAD

**Issue by kevinmelo** [quasarframework/quasar#6800]
**Describe the bug**
After i uptade my quasr version from 1.9.9 to 1.9.14 the clearable button on q-inputs got tabindex="0" instead of old value "-1"

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Tydroth/pen/mdeJzXb?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fbutton

**To Reproduce**
1. Write something on q-input in codepen example
2. Press tab
3. The focus element is the clearable... in older version what the submit button

**Expected behavior**
Submit button on example be focus not the clearable button on q-input

**Platform (please complete the following information):**
OS: Zorin OS
Node: v12.16.1
NPM: 6.14.4

**Additional context**
Don't know if this is configurable or not, but if i have a large form with a lots of q-input with clearable and i use tab to pass to next field, will be much slower cause i will need 2 tabs per field

**Comment by pdanpdan** [comment]
The clear button was lacking a way to be accessible with keys. I don't think it would be good design, but maybe we can add a way to disable the focus- but it's not a priority.

**Comment by kevinmelo** [comment]
@pdanpdan Thanks.

For now i can do anything to not focus the clearable button from q-inputs?

**Comment by pdanpdan** [comment]
Not very efficient but does the job: https://codepen.io/pdanpdan/pen/VwvvbRO?editors=1010

**Comment by kevinmelo** [comment]
Yeap, can't use this for all my pages and forms :/

Thanks anyway

**Comment by pdanpdan** [comment]
After thinking about this it would be overkill to add a prop specific for the tabindex of the clearable button.
It is a very special case and can be solved easily with:
```html
<q-input v-model="model">
  <template v-if="[null, void 0, ''].indexOf(model) === -1" v-slot:append>
    <q-icon name="cancel" @click.stop="model = null" class="cursor-pointer" />
  </template>
</q-input>
```

**Comment by kevinmelo** [comment]
Well, i would have to update all my q-inputs and q-fields and q-select to add this new code, only to get my clearable button not get focus on tab :/

**Comment by rstoenescu** [comment]
@kevinmelo Forgive me if I seem out of line, but you should really be considerate towards the people who have disabilities. It's very easy to dismiss them, but bear in mind that they will not have a way to reset the model of QField/QInput/QSelect should they want to.

**Comment by eyedean** [comment]
I ran into the same issue.  The problem is on username/password forms, I am so used to go to "password" from "username" via <tab>, but if I make the username field `clearable`, it's gonna take two tabs.

I really wish there was an option of `clearable-without-tabindex` on `q-input`.

For now, I should go with https://stackoverflow.com/a/64119123 and manually do it.

**Comment by Patfreeze** [comment]
Sorry to dig out a Closed issue 3 years later... I totally agree with rstoenescu for the consideration towards people who have disabilities, but how it suppose to be triggered once the focus is on the `clearable` option? Expected the `Enter` but doesn't working. `Esc` and `Space` too. 🤔
