### ISSUE TITLE
 This dependency was not found:

### ISSUE THREAD

**Issue by nkb-bd** [quasarframework/quasar#6804]
When I followed the doc to add ion icon it says dependency was not found  
I added it to quasar config and installed quasar extra.
: quasar/icon-set/ionicons-v4  in ./.quasar/import-quasar.js  To install it, you can run: npm install --save quasar/icon-set/ionicons-v4

**Comment by Fanvadar** [comment]
Not really sure what the feature you're requesting is. Could you elaborate?

**Comment by smolinari** [comment]
Being worked on here: https://forum.quasar-framework.org/topic/5621/icon-setup-issue

Scott
