### ISSUE TITLE
Latest Updates are Causing Build Failure

### ISSUE THREAD

**Issue by ShawnClake** [quasarframework/quasar#6806]
**Describe the bug**
Our app was previously running the following versions of each Quasar package:

    "@quasar/cli": "1.0.5",
    "@quasar/extras": "1.6.0",
    "quasar": "1.9.9",
    "@quasar/app": "1.6.0",
    "@quasar/quasar-app-extension-icon-genie": "1.1.3",
    "@quasar/quasar-app-extension-qcalendar": "1.5.1",

With these versions I experience no build issues. However, I recently tried to upgrade all of the quasar packages to their latest versions using the `quasar upgrade --install` command, and this started causing my container builds to fail with the error shown in the screenshots section.

What's most interesting is that the build does not fail on my development PC when I run NPM/Quasar commands manually, but when I try to build it in a docker container based on Ubuntu 18 it does fail. 

**To Reproduce**
1. Not sure other than a clean container build fails with the latest quasar packages

**Expected behavior**
The build should not fail when building from a clean container. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19659689/79157424-c52cd100-7d91-11ea-9526-ad9f54dd683d.png)

**Comment by pdanpdan** [comment]
Check your node.js version in container. Use only 10 or 12.

**Comment by ShawnClake** [comment]
Yup, that was the problem. Thanks!
