### ISSUE TITLE
Thank you for your excellent framework and it is recommended that the Qtree component provide a prop to specify the propName of childNode

### ISSUE THREAD

**Issue by zxcvc** [quasarframework/quasar#6809]
Thank you for your excellent framework and it is recommended that the Qtree component provide a prop to specify the propName of childNode

E.g：
<q-tree  :nodes="tree"  childName="sub"><q-tree/>

**Comment by zxcvc** [comment]
E.g：
<q-tree :nodes="tree" child-name="sub">

**Comment by zxcvc** [comment]
E.g：  < q-tree :nodes="tree" child-name="sub">< /q-tree >"

**Comment by pdanpdan** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/6661 on the same page
