### ISSUE TITLE
roboto-font doesn't have Cyrillic characters

### ISSUE THREAD

**Issue by nik0145** [quasarframework/quasar#6811]
**Describe the bug**
 `roboto-font` does  not included cyrillic.

[Codesandbox](https://codesandbox.io/s/quasar-font-kjo0d?file=/src/pages/Index.vue)
**To Reproduce**
1. See font for "шрифт" (Arial)
1. See font for "font" (Roboto)

**Expected behavior**
I'm added the link in template.index.html
`<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">`

**Additional context**
https://codesandbox.quasar.dev not working for me.

**Comment by pdanpdan** [comment]
Hello. I don;t know what you are doing there - it looks like you're not loading the Roboto font.
It works with Cyrillic characters, as you can check on the docs site.

About https://codesandbox.quasar.dev - you need to fork it.

**Comment by nik0145** [comment]
@pdanpdan but in [Codesandbox](https://codesandbox.io/s/quasar-font-kjo0d?file=/src/pages/Index.vue) loading the Roboto font.
For this is not loaded.
![image](https://user-images.githubusercontent.com/23018061/79208070-434cae80-7e4a-11ea-8dcc-4710e37ab5d3.png)

**Comment by rstoenescu** [comment]
@nik0145 

1. Why would you open a ticket on Quasar if you load a font directly from Google and you think it's an issue with it?

2. You might want to use quasar/extras package:
![roboto](https://user-images.githubusercontent.com/4665641/79210260-3a111100-7e4d-11ea-9960-cdbde5c109e7.png)

Uncomment `roboto-font-latin-ext` and then comment `roboto-font`.

**Comment by ildar-gilmanov** [comment]
@rstoenescu , @nik0145 ,  it seems the `roboto-font-latin-ext` does not contain Cyrillic symbols. For example, you can check this site: https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=latin

And as you can see there are `Cyrillic` and `latin-ext` options.

**Comment by MilosPaunovic** [comment]
That's why there is a `Cyrillic` version of it :)

**Comment by ildar-gilmanov** [comment]
@MilosPaunovic , does the Quasar support the Cyrillic Roboto font extension, like `roboto-font-latin-ext` ? I did not find it in the Quasar source files.
