### ISSUE TITLE
[QTabPanels] - Allow to disable lazy loading

### ISSUE THREAD

**Issue by iahdevelop** [quasarframework/quasar#6812]
Hello,

I have a long-form which consists of many tabs. I have a problem with validating the fields of the hidden tabs because they are not instantiated yet. Is it possible to add a feature to instantiate all tabs upfront?

**Comment by pdanpdan** [comment]
Hello. Please validate you forms using the models, not the markup.

**Comment by Tofandel** [comment]
That's quite a timely workaround if there is a lot of validation to do and requires duplication of all rules so is not maintanable

It would still be a much needed feature especially for SEO, we should be able to eager render the tabs
