### ISSUE TITLE
Allow Drawer under Header on mobile

### ISSUE THREAD

**Issue by 54mu3l** [quasarframework/quasar#6813]
With a menu like this:
![image](https://user-images.githubusercontent.com/17022670/79200369-9fa5d300-7e36-11ea-8745-e5cc6baa83a1.png)

On mobile devices (or smaller screens) one always gets this:
![image](https://user-images.githubusercontent.com/17022670/79199795-c7e10200-7e35-11ea-852c-54da0ddf6a13.png)

But our customer wants to see the header all the time whether or not the menu is opend or closed. And the behaviour should be the same on mobile as on desktop.

It would be really great and useful if there would be a flag, by which you can make the Drawer appear under the Header (on mobile devices).

I already tried to set `behavior="desktop"` and `:overlay="isMobile"` (`isMobile` is a computed property in my component). But with that I won't get the nice backdrop as when the `behavior` is set to `mobile`. With this I get something like this (on mobile devices):
![image](https://user-images.githubusercontent.com/17022670/79201282-1abbb900-7e38-11ea-935c-9fda12584a13.png)
Which is kind of the behavior we need (with the Header always shown). But as I said, there is no nice backdrop nor will a click on the content close the overlayed-menu.
But I would love to see something like this (on mobile devices):
![image](https://user-images.githubusercontent.com/17022670/79201613-a46b8680-7e38-11ea-94d5-54205be29cb4.png)

I could imagine a flag `show-header-on-mobile`, `always-show-header` or `header-on-top` to get this kind of behavior.

Thank you very much for your response.

**Comment by pdanpdan** [comment]
Hello - set a very high `z-index` on the header.

**Comment by jaymoh** [comment]
Hi @54mu3l, did you find a fix for this?

**Comment by 54mu3l** [comment]
@jaymoh I'm afraid no...
We just implemented our own component to behave like we need it to. It's not the best solution but it kinda works for now.. The z-index thing (mentioned by @pdanpdan) didn't worked for us.

**Comment by PickleNik** [comment]
I also need this

**Comment by pdanpdan** [comment]
Make a codepen so we can play with it

**Comment by Ammamon** [comment]
Add :breakpoint  behaviour to your drawer. This will keep it under header.

**Comment by Gnopps** [comment]
@pdanpdan Could this request be reopened? As for codepen just the standard from the documentation can be used: https://codepen.io/pen/?&editors=101&prefill_data_id=deca9376-d9fb-4516-a4f6-3bd90dd652ba

Compare behaviour with respecting layout header setting (drawer above or below header) when on screen resolution vs. desktop resolution. 

For me the use-case is that I would like to use mobile _behaviour_ (swipe to open/close, click outside to close) but show header and footers. I can use z-top as header/footer class or build my own even triggers to open/close but they are all imperfect workarounds.

**Comment by pdanpdan** [comment]
It's an empty codepen.
Make a codepen with what you have tried.

**Comment by hawkeye64** [comment]
...and don't forget to save it, then share the link.

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/dyVOXoZ?editors=1100

**Comment by andrisi** [comment]
@pdanpdan do we have a solution to this after all? None of the codepens exist anymore, and adding z-index to the header does not help either. @Ammamon could you share your solution please?
