### ISSUE TITLE
Layout Drawer Bug - breakpoint / @input / :value

### ISSUE THREAD

**Issue by turigeza** [quasarframework/quasar#6817]
**Describe the bug**
When I am using `@input` and `:value` with a `:breakpoint="1439`" I get this strange behaviour whereby the buttons open the wrong drawer.

Take a look at the pen. 
The problem is that the right menu icon controls the left drawer if you are bellow the breakpoint.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/turigeza/pen/vYNNWGE?editors=1010

**To Reproduce**
1. Go to https://codepen.io/turigeza/pen/vYNNWGE?editors=1010
2. Resize your screen so it is bellow 1440px width.
3. Click on the right menu icon.
4. Left drawer will open instead of the right. If you are above the breakpoint all seems fine.

**Expected behavior**
The right side drawer should open instead of the left.

**Platform (please complete the following information):**
OS: OS X but I don't think it matters. All browsers I tested FF. CHROME, and Safari

**Comment by pdanpdan** [comment]
Hello. You have attached no codepen and you have not filled any of the details for platform.

**Comment by turigeza** [comment]
> Hello. You have attached no codepen and you have not filled any of the details for platform.
@pdanpdan 
I am sorry ... I managed to submit it accidentally I don't know how ... my bad. 
But since it is submitted you might as well look. 
Please look at the updated description.  Thank you,

**Comment by pdanpdan** [comment]
This is because you toggle the left drawer on every input, no matter what that input is.
When the menus are in mobile mode only one of them can be open, so an open of the right emits a close of the left.

I'll let this ticket open for a possible optimization, but you must use the emitted value, not toggle the model.

https://codepen.io/pdanpdan/pen/GRppyeX?editors=1010

**Comment by turigeza** [comment]
@pdanpdan You are right.  It works just fine. Thank you!
https://codepen.io/turigeza/pen/wvKKyma

I meant to ask this on the forum first but then accidentally submitted the ticket here. Sorry about that.

I don't think it needs changing how it works. You are welcome to close the ticket. Perhaps worth mentioning it in the docs ( even if it's obvious to you ) puzzled me for a while. Basically I wasn't expecting the input to trigger for the right drawer.

**Comment by pdanpdan** [comment]
Note: the code for drawer is ok - it's just a corner case that requires the input event to be emitted even if it's already closed.
