### ISSUE TITLE
Unknown custom element: <q-btn>

### ISSUE THREAD

**Issue by Zyles** [quasarframework/quasar#682]
I hate getting these lame starter issues when trying out a new framework.

### Software version

Quasar: Package JSON says 0.14, demo template says 0.13.10. Who knows.
Browsers: Electron Wrapper
Any other software related to your bug:

### What did you get as the error?

I am trying to add a simple button to try the framework. I did as the guide said, ran the install and launched the electron app with "quasar dev"

Then I get the error: `Unknown custom element: <q-btn>` in browser console.

I only changed the template in index.vue of the boilerplate.

`<q-btn icon="edit" color="primary" small>
      Edit
    </q-btn>`

The script:

`import { Utils, Platform, QBtn } from 'quasar'`

`components: {
    QBtn
  }`

It only renders the text "Edit" without a button.

I don't think I missed anything?

### What were you expecting?

A working button.

**Comment by smolinari** [comment]
How did you initialize the app? 

Did you do ```quasar init <project folder>``` or did you do ```quasar init 'default#beta' `<projectfolder>```

Scott

**Comment by rstoenescu** [comment]
To get the version of Quasar you are currently running on, use the CLI: `quasar version`. Also, there's no Utils import anymore. Instead import the utils method you want, eg. `import { date } from 'quasar'`.

**Comment by rstoenescu** [comment]
I think you are either using the wrong template or upgrading from an older template and something is missing. If the latter, please use forum for help.

But, please reopen this if you've used `quasar init default#beta` and it still happens (I doubt that 99,99%).

**Comment by Zyles** [comment]
No I read and did like the manual instructed: http://beta.quasar-framework.org/guide/index.html

**Comment by rstoenescu** [comment]
Little mistake in beta docs. Use `quasar init default#beta <folder_name>` as on beta docs landing page. Fixed the mistake. Thank you.
