### ISSUE TITLE
[BEX] content-script.js - improper declaration [SOLUTION]

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/quasar#6820]
**Describe the bug**
The generated code in file content-script.js doesn't work in chrome and firefox

**To Reproduce**
1. Create BEX project
2. Try to override attachContentHooks in content-script.js
3. It doesn't work in Firefox and Chrome

**Platform (please complete the following information):**
OS: Windows
Browsers: Firefox, Chrome

**Additional context**

the generated code looks like this:
```
export default function attachContentHooks (bridge) {
```
and it should look like that:
```
// eslint-disable-next-line no-unused-vars
function attachContentHooks (bridge) {
```
After the change everything works as expected.

**Comment by webnoob** [comment]
Thanks for the report.

Did you by any chance create this bex before the official release yesterday? The reason I ask is that the template now has the `bridge` commented out to avoid any linting errors.

See: https://github.com/quasarframework/quasar/blob/dev/app/templates/bex/js/content-hooks.js

**Comment by webnoob** [comment]
Closing as I can't see this being an issue with the new template. Will re-open if something more sinister is taking place.

**Comment by qyloxe** [comment]
Please reopen...

The problem still exists. I created this repo:
https://github.com/qyloxe/qbexlinks

The idea is to isolate the minimal BEX behaviours which generate this problem. This repo is based on Quasar Docs and as for now, it is only about content BEX. I have a bigger repo with my whole toy project and there are two other BEX problems, but lets deal with this showstopper first.

In my main repo I created a working simple page scraper as BEX - but it is not in conformance with Quasar docs :-) I will happily port this toy scraper (grab news from hackernews and do something with them) as an example of Quasar BEX technology and donate this qbexlinks repo to you at the end.

If you clone this repo, run "quasar dev -m bex" and register it in Chrome (and/or try to open new webpage) you will see those two errors:

error 1:
![image](https://user-images.githubusercontent.com/467508/79387463-11cc0400-7f6c-11ea-8271-a48a539238da.png)

and error 2:
![image](https://user-images.githubusercontent.com/467508/79387521-26a89780-7f6c-11ea-94e4-6c0b92792f16.png)

and on webpage (news.ycombinator.com) console log you will see:
![image](https://user-images.githubusercontent.com/467508/79387610-4cce3780-7f6c-11ea-8263-4d3d0b98b580.png)

I assume, that there shouldn't be such errors, the code is almost identical to code from docs and it looks reasonable. The same errors are on Firefox, BUT unfortunately Firefox doesn't show them as easily and conveniently as Chrome.

**Comment by webnoob** [comment]
I'm reviewing this now.

**Comment by webnoob** [comment]
Ok, RE: Issue one - in short, it's your fault ;)
You have `content-hooks.js` and `content-script.js` files mixed up. content script is a native script injected into the client side page and as such can't have export. The code you have put in that file belongs in `content-hooks.js`.

RE: Issue 2. I have seen this on occasion but really the content_security_policy is up to the developer to manage and it's not something we can get a one stop fits all on unfortunately. That being said, I've not seen it on this code base since moving the content-script code into content-hooks.

**Comment by webnoob** [comment]
Following a discussion with @qyloxe the docs need updating as they're pointing the code towards content-script.js`.

**Comment by webnoob** [comment]
PR done. Closing.
