### ISSUE TITLE
Ability to change dark mode text color

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#6821]
**Is your feature request related to a problem? Please describe.**
On some of my compenents the white text in dark mode contrasts too greatly with the background.

**Describe the solution you'd like**
I would like the global white text that appears on dark mode to be editable in some way. I notice in many components the text is set something like the following in Quasar's code:

```
&--dark
    color: #fff
```

Thus I see why this may not be possible. 

**Describe alternatives you've considered**
I've seen that you could change most of the text colors with something like this: 

```
.q-dark
    color: #f2f2f2
```

However, I'm uncertain if this will apply to all text.

Any suggestions for alternative solutions would be greatly appreciated.

**Comment by rstoenescu** [comment]
Hi,

The text color is set to be inherited right up to the body tag. If you wish to change it only for dark mode, then:

```
body.body--dark {
  color: ......
}
```

**Comment by smolinari** [comment]
This might also be of interest. @Fanvadar 

https://codepen.io/smolinari/pen/KKpqWBe?editors=1010

Scott
