### ISSUE TITLE
QSelect - Dynamic loading options using Vuex

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#6826]
**Is your feature request related to a problem? Please describe.**
I'm trying to dynamic loading options using Vuex:

```
<q-select
          ref="tags"
          v-model="body.tags"
          :input-debounce="500"
          :max-values="15"
          :options="options"
          :loading="loading"
          @filter="filterTags"
          @virtual-scroll="onScroll"
          label="Select tags"
          multiple
          option-label="name"
          option-value="id"
          use-input
        >
```

```
async filterTags (val, update, abort) {
      // Reset items
      this.$store.dispatch('tags/reset', {
        params: {
          'filter[query]': val || null
        }
      })

      // Fetch tags
      await this.$store.dispatch('tags/fetch')

      // Update options
      update()
    },

    async onScroll ({ to, ref }) {
      // Fetch more tags
     await this.$store.dispatch('tags/fetch')
   }
```

For some reason it keeps calling `onScroll` even when no (more) results are available.
It tried looking into the methods for a call like `done()` to stop the fetching from happening, but it seems this isn't available?

*The Vuex store handles the page limits, next page, results, etc.

**Describe the solution you'd like**
Call done() to stop onScroll calling.

**Describe alternatives you've considered**
I don't know if it is possible.

**Additional context**
I'm using the infinite scroll feature and this works great.

Thanks.

**Comment by pdanpdan** [comment]
Hello. Virtual scroll is not infinite scroll - the point of the `virtual-scroll` event is to notify you of changes in scroll position - if you change the source (options) when this event is triggered then you force a repaint of the list and a new event is emitted.

Sorry. Maybe a codepen would help.

**Comment by francoism90** [comment]
@pdanpdan Thanks for your reply. I just mentioned infinite scroll because it works with the store.

It's a bit difficult to create an example as it has Vuex as backend. I'm basically using the same as infinite scroll, but call `done(true)` to stop further processing, something that isn't possible on virtual scroll?

**Comment by pdanpdan** [comment]
There are examples in the docs: https://quasar.dev/vue-components/select#Example--Dynamic-loading-options
