### ISSUE TITLE
Adding row number column for QTable

### ISSUE THREAD

**Issue by ryhn** [quasarframework/quasar#6828]
Hi,
How can I add row-number column to QTable.
No matter which column sorted, row-number column value must be 1 to data.length

Thanks.

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott

**Comment by ryhn** [comment]
Hi,
There is no bug. But i think row-number column can be "feature request"  that's why i wrote here.

i will take my change on the quasar forum :smile: 

Thanks.

**Comment by smolinari** [comment]
I've changed my panned text for the future. See above. :)

Scott

**Comment by pdanpdan** [comment]
I'd like to think about this for some time - reopening for checking in the code.

**Comment by rfox12** [comment]
@ryhn I think @pdanpdan has 3-4 full time jobs worth of work. ;)

This is my hack that perhaps does what you're looking for?
https://codepen.io/robert123789/pen/LYpZyaO

It uses CSS Counters, which I haven't tested much on different browsers/platforms. (I'm Chrome most of the time).  Maybe this is a temp solution for you?  Just trying to give back to the community.

In case the pen disappears here is the relevant code... for the `<template>`:
```
    <q-table
      :table-style="'counter-reset: cssRowCounter ' + ((pagination.page - 1) * pagination.rowsPerPage) + ';'"
      title="Treats"
      :data="data"
      :columns="columns"
      row-key="name"
      :pagination.sync="pagination"
    ><template v-slot:body-cell-row-number="props">
        <q-td><span class="rowNumber"/>
         </q-td>
      </template>
    </q-table>
```

And then all you need is an entry in the `<style>` area:
```
.rowNumber::before {
  counter-increment: cssRowCounter;
  content: counter(cssRowCounter) ". ";
}
```
And that's it!

**Comment by ryhn** [comment]
Hi,

@rfox12 this is a good solution. I will try this. Thanks.

**Comment by rstoenescu** [comment]
There's gonna be "rowIndex" and "pageIndex" in the **sorted and filtered table** available in "quasar" v1.10.0.

**Comment by hmeine** [comment]
I would have liked to [make use of this to access the previous row in the data array](https://forum.quasar-framework.org/topic/6814/qtable-with-less-clutter-on-hierarchical-data), but apparently one does not have access to the sorted & filtered table data itself, right?

**Comment by rstoenescu** [comment]
There's a computed prop on the QTable instance named `filteredSortedRows` -- you can use that @hmeine
