### ISSUE TITLE
QUploader multiple, formFields custom to each file

### ISSUE THREAD

**Issue by gaby64** [quasarframework/quasar#6830]
can I build formFields for each file in the upload queue?

if not, can this be implemented?

**Comment by pdanpdan** [comment]
Please use the discord channel or the forum for help requests.

**Comment by gaby64** [comment]
this does belong here, its not simply a help request, its a feature request, 
I already know the answer to my first question

**Comment by pdanpdan** [comment]
And what is the answer? and where is the description of what you want, what you tried?

**Comment by gaby64** [comment]
well possibly factory can do what I need

**Comment by gaby64** [comment]
the docs dont say factory will run on each file when not in batch mode

**Comment by rstoenescu** [comment]
@gaby64 that's the purpose of the "batch" mode. either all files in one batch or separate requests, so separate factory.
