### ISSUE TITLE
Add unicons library to Quasar icons set

### ISSUE THREAD

**Issue by Yan-intelia** [quasarframework/quasar#6837]
**Is your feature request related to a problem? Please describe.**
A designer sent us a new design look for the website application of our business, the icons used in the de sign is https://iconscout.com/unicons/explore/line, as those icons is not in the quasar standard like font aweosome is, we would like to know if there is possibility to add this set in quasar

**Describe the solution you'd like**
Add the https://iconscout.com/unicons/explore/line library to the quasar icon set to have the possibility to use them in the icon= of the quasar tags.

**Describe alternatives you've considered**
Do you have an alternative ?

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Quasar allows the use of **any** webfont icon lib. You don't have to wait for us to implement it with "@quasar/extras":
1. Load the css of Unicons (it's in their docs) --- either put it directly in /src/index.template.html, or download it (along with its woff/woff2/etc files) to your app's folder and import it.
2. Creating a custom mapping for QIcon to work with Unicons: https://quasar.dev/vue-components/icon#Custom-mapping
3. Optional, create your custom Quasar Icon set and tell Quasar to use it (this is for Quasar component's icons).

Unfortunately we cannot prioritize to get this into "@quasar/extras" over other requests from donators/sponsors as those are the ones keeping us alive.
