### ISSUE TITLE
Default app will not build on Android using capacitor

### ISSUE THREAD

**Issue by kurtroberts** [quasarframework/quasar#6838]
**Describe the bug**
When trying out the capacitor - android workflow, the default app fails to build with the message:

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.2.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-44:19 to override.

**Codepen/jsFiddle/Codesandbox (required)**
... I can't, this is an issue with the cli.

**To Reproduce**
1. `quasar create new-project`
2. `cd new-project`
2. `quasar mode add capacitor` 
3. `quasar dev --mode capacitor --target ios` # works fine
4. `quasar dev --mode capacitor --target android` # fails with above error

**Expected behavior**
I expected the demo project to build.

**Screenshots**

**Platform (please complete the following information):**
OS: Tested on macos (10.15.4) and Ubuntu (18.04.4)
Node: macos - 13.10.1, ubuntu - 12.16.1
NPM: 6.14.3 (both)
Yarn: NA
Browsers: NA
iOS: NA
Android: NA
Electron: NA
Java: Mac - openjdk 14 2020-03-17, Ubuntu - openjdk version 1.8.0_242

**Additional context**

**Comment by pdanpdan** [comment]
You provide no info on the version of capacitor, but I suppose you are using v2.
https://capacitor.ionicframework.com/docs/android/updating/#from-1-5-1-to-2-0-0

Please reopen if it's something else.

**Comment by AaronNBrock** [comment]
@pdanpdan I'm having the same issue & I've gone through the Android X migration mentioned in the capacitor documentation.

**Comment by AaronNBrock** [comment]
This solved my problem:  https://github.com/quasarframework/quasar/issues/6768#issuecomment-612399885

However, I think this still is an issue since by default capacitor didn't work.

**Comment by bfour** [comment]
Same problem here with @quasar/cli v1.0.7, node v12.16.3.

**Comment by bfour** [comment]
> This solved my problem: [#6768 (comment)](https://github.com/quasarframework/quasar/issues/6768#issuecomment-612399885)
> 
> However, I think this still is an issue since by default capacitor didn't work.

And this solved it for me, too. Thank you!
