### ISSUE TITLE
QSelect - option to show before-options and after-options with no results

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#6839]
In its current form, the before-options and after-options slots for the QSelect component will only be shown if there are results in the dropdown.

In my case, I have used the slot `no-option` and `before-options`, with before-options showing some filter-toggles. So if the user has selected a filter which returns no results, the filters disappear (as before-options disappears when no results exist).

**Comment by pdanpdan** [comment]
Make the filters a component and use it in the before-options slot and add the first element of the no-option

**Comment by nicholaszuccarelli** [comment]
I figured I'd have to do something like that.

I only thought it might be a bit neater if I could define a prop to force show the before-options slot either way.

Thanks though 😊

**Comment by pdanpdan** [comment]
Considering that:
- the slots are places to put the content in
- the `no-option` slot and the list of options are mutually exclusive
- `before-options` and `after-options` are related to the options list

I would say we should keep it as is is.

@rstoenescu if you think there is something to be improved please reopen.
