### ISSUE TITLE
Eslint: no-duplicates Resolve error: unable to load resolver “node”

### ISSUE THREAD

**Issue by jkirkby91-2** [quasarframework/quasar#684]
Hello after running npm update to get an update of a dep I was using quasar no longer compiles,  getting the following error

Eslint: no-duplicates Resolve error: unable to load resolver “node”

I am using the beta version, here is exact version from package-lock.json

    "quasar-extras": {
      "version": "0.0.7",
      "resolved": "https://registry.npmjs.org/quasar-extras/-/quasar-extras-0.0.7.tgz",
      "integrity": "sha1-L7tab+cZr4wGmZ1wNNSMUDWcPMA="
    },
    "quasar-framework": {
      "version": "git+https://git@github.com/quasarframework/quasar-edge.git#a3532a3c3fee3c46f81894f2589ece806bfad77b"
    },

seems others are also experiencing this issue

https://stackoverflow.com/questions/44865507/eslint-no-duplicates-resolve-error-unable-to-load-resolver-node

**Comment by jkirkby91-2** [comment]
seems others are also experiencing this issue

https://stackoverflow.com/questions/44865507/eslint-no-duplicates-resolve-error-unable-to-load-resolver-node

**Comment by jkirkby91-2** [comment]
I think some dependancies have been removed to fix I did

npm install eslint-plugin-import --save-dev 

npm install babel-preset-env --save-dev
Then I edited .eslintrs.js

modify extends to look like this

  extends: [
    'standard',
    'plugin:import/errors',
    'plugin:import/warnings',
    ],
add the import plugin like

  plugins: [
    'html',
    'import'
  ],
then add the following rules

'import/named': 2,
'import/namespace': 2,
'import/default': 2,
'import/export': 2,

**Comment by rstoenescu** [comment]
Got a few questions:

1. Are you taking into account semver notation for the packages you are upgrading? Some may have breaking changes.
2. What packages have been upgraded, and from what version to what version?
3. Are you sure you need an update for some packages? The common rule is to use Quasar's template to figure out when it's safe to upgrade some packages like ESLint for example, who keeps releasing breaking changes. If "npm update" updates a package, then it's fine, but if you modify package.json to get a newer ESLint, then you as a developer are on your own to figure out breaking changes and whatnot.

Also, why would you have to import Quasar like that? It makes me think the template you are using has been wrongfully altered. 'quasar' should be a Webpack alias to 'quasar-framework' npm package. How can an update break this... it doesn't...

If the above still don't make sense to you, please reopen with a detailed case. It helps in investigating. What version have you used previously and to which versions have you upgraded.
Also remember about semver notation when manually updating to a newer npm package.

**Comment by murbanowicz** [comment]
@rstoenescu it is not about how he imports. 
I got the same issue and I did not rouch Quasar imports.

**Comment by rstoenescu** [comment]
@murbanowicz I need those questions answered. Last time I looked into your repo everything was working fine, except your imports that needed correction (from "src" to the recommended way of importing).

**Comment by murbanowicz** [comment]
Is it possible to get it from npm kind of history? Npm is just showing numbers of packages updated now.

**Comment by rstoenescu** [comment]
Compare https://github.com/quasarframework/quasar-template-default/blob/beta/template/package.json to your package.json.

I also noticed some npm 5 bugs when updating or installing new packages. The fix was to delete node_modules and npm install again... Just saying :)

**Comment by jkirkby91-2** [comment]
as @murbanowicz I didn't touch anything to do with quasar, the only package changed was from the  vue-authenticate master to a develop branch im working on adding cordova oauth support

https://github.com/jkirkby91-2/vue-authenticate

no modifications to how .eslintrc.js or any other eslint/babel/webpack packages or configs were made

**Comment by dhax** [comment]
had this same problem too when only updating eslint-plugin-import from 2.6.0 to 2.6.1.
Deleting and reinstalling node_modules did not solve the problem, had to revert to 2.6.0.

**Comment by lzhuor** [comment]
Having the same issue after upgrading from `2.3.0` to `2.7.0`
