### ISSUE TITLE
Select @new-value for single

### ISSUE THREAD

**Issue by fjl280855990** [quasarframework/quasar#6842]
Select component @new-value is in multiple mode, but what I want is single choice, for example：
...
data() { list: [1, 2, 3, 4] }
@enter="() => Auto add when I enter 6"
methods: {
    add() {
        if (this.list.filter(val => val === 6).length === 0) { this.list.add(6) }
    }
}
...

**Comment by pdanpdan** [comment]
Add a codepen with what you have tried.

**Comment by pdanpdan** [comment]
For help request please use the discord channel or the forum.
