### ISSUE TITLE
Quasar doesn't seem to read electron-builder config

### ISSUE THREAD

**Issue by Menighin** [quasarframework/quasar#6844]
**Describe the bug**
I'm trying to build my electron app to Windows and Linux (Im using Windows). I have tried tuning the configuration in `quasar.conf.js` but nothing I do seems to have any impact on the build. All `quasar build -m electron` does is to build for Windows

Maybe and probably I'm just missing something >.<

**To Reproduce**
1. Create a project from scratch with `quasar create`
2. Set the build options to build Windows and Linux like:
```
    electron: {
      bundler: 'builder', // 'packager' or 'builder'
      builder: {
        appId: 'test-build',
	win: {
	    icon: 'src-electron/icons/icon.png',
	    target: 'nsis'
	},
	linux: {
	    target: [
	        'AppImage',
	        'deb'
	    ]
        }
    }
```

3. run `quasar build -m electron`

**Expected behavior**
`electron-builder` would read `quasar.conf.js` and build for both Windows and Linux

**Logs**
The output from `electron-builder`
```
 app:electron Bundling app with electron-builder... +2ms

  • electron-builder  version=22.5.1 os=10.0.18363
  • writing effective config  file=dist\electron\Packaged\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=8.2.3 appOutDir=dist\electron\Packaged\win-unpacked
  • building        target=nsis file=dist\electron\Packaged\Quasar App Setup 0.0.1.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist\electron\Packaged\Quasar App Setup 0.0.1.exe.blockmap

 app:electron [SUCCESS] electron-builder built the app +1ms


 Build succeeded

 Build mode........ electron
 Pkg quasar........ v1.9.15
 Pkg @quasar/app... v1.7.1
 Debugging......... no
 Publishing........ no
 ==================
 Output folder..... D:\Projects\bundle-test\dist\electron
```

**Platform (please complete the following information):**
OS: Windows 10
Node: 12.14.0
NPM: 6.13.4
Electron: 7.1.9
electron-builder: 22.5.1

**Comment by pdanpdan** [comment]
Hello.

https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron#Packager-vs.-Builder

What you are editing there is the defaults/setting for building, not the target to build for.
You need to tell what arch to build for (see first link).

From `quasar --help`:
```
    ONLY for Electron mode:
    --bundler, -b   Bundler (electron-packager or electron-builder)
                      [packager|builder]
    --arch, -A      App architecture (default: yours)
                      - with default "electron-packager" bundler:
                          [ia32|x64|armv7l|arm64|mips64el|all]
                      - with "electron-builder" bundler:
                          [ia32|x64|armv7l|arm64|all]

    ONLY for electron-builder (when using "publish" parameter):
    --publish, -P  Publish options [onTag|onTagOrDraft|always|never]
                     - see https://www.electron.build/configuration/publish
```
