### ISSUE TITLE
Unable to add and run capacitor in my Quasar project

### ISSUE THREAD

**Issue by OPerel** [quasarframework/quasar#6845]
**Describe the bug**
I'm trying to add capacitor to my Quasar project with no success. I'm following the docs on Developing Capacitor Apps, and in the [Preparation](https://quasar.dev/quasar-cli/developing-capacitor-apps/preparation) section everything works fine until step 3. After running `quasar mode add capacitor` (step 2) I have the `src-capacitor` folder in my project folder.
But on step 3, when running `quasar dev -m capacitor -T android` I get the following error:
```bash
 Dev mode.......... capacitor
 Pkg quasar........ v1.9.15
 Pkg @quasar/app... v1.7.1
 Debugging......... enabled
 Running mode...... IDE (manual)

 app:mode-capacitor Adding Capacitor platform "android" +0ms
 app:spawn [sync] Running "C:\Users\Ori\code\wonderfloyd\Hackathon-Corona\Quasar_Firebase_Todo_App\src-capacitor\node_modules\@capacitor\cli\bin\capacitor add android" +1ms


 app:spawn ⚠️  Command "C:\Users\Ori\code\wonderfloyd\Hackathon-Corona\Quasar_Firebase_Todo_App\src-capacitor\node_modules\@capacitor\
cli\bin\capacitor" failed with exit code: null +1ms
 app:spawn ⚠️  Please globally install "C:\Users\Ori\code\wonderfloyd\Hackathon-Corona\Quasar_Firebase_Todo_App\src-capacitor\node_mod
ules\@capacitor\cli\bin\capacitor" +3ms
```
I found issue https://github.com/quasarframework/quasar/issues/5278 with a similar problem, but the problem there was solved by upgrading to `@quasar/app v1.2.1` and I'm using `@quasar/app v1.7.1`.

**To Reproduce**
Not sure if this will be easily reproduced. As mentioned, I just followed the Capacitor guide in the official docs and encountered this, and I'm guessing it does not happen to most users.  

**Expected behavior**
According to the docs, after running `quasar dev -m capacitor -T android` the Android Studio is suppose to open up.

**Screenshots**
![Error](https://user-images.githubusercontent.com/42510547/79632494-4dcbb880-8168-11ea-948b-e5d176141a97.JPG)

**Platform (please complete the following information):**
OS: Windows 10 PRO 64-bit
Node: v12.16.0
NPM: 6.13.4
Browsers: Google Chrome 80
Android: Android Studio 3.6

**Additional context**
I'm attaching my config files in case it helps.

__`/package.json`__:
```json
{
  "name": "quasar_firebase_todo",
  "version": "0.0.1",
  "description": "A simple Todo app with Quasar and firebase",
  "productName": "Quasar Firebase Todo",
  "cordovaId": "io.FlowBiz.QuasarFirebaseTodo",
  "capacitorId": "",
  "author": "FlowBiz",
  "private": true,
  "scripts": {
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "quasar": "latest"
  },
  "devDependencies": {
    "@quasar/app": "latest"
  },
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ]
}
```

__`/src-capacitor/package.json`__:
```json
{
  "name": "quasar_firebase_todo",
  "version": "0.0.1",
  "description": "A simple Todo app with Quasar and firebase",
  "author": "FlowBiz",
  "private": true,
  "dependencies": {
    "@capacitor/cli": "^1.0.0",
    "@capacitor/core": "^1.0.0"
  }
}
```

__`capacitor.config.json`__:
```json
{
  "appId": "io.FlowBiz.QuasarFirebaseTodo",
  "appName": "Quasar Firebase Todo",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www"
}
```

Please let me know if I can provide any further info that can help to debug this.
Thanks a lot!

**Comment by rstoenescu** [comment]
Hi,

Yarn/npm install deps in /src-capacitor. That seems to be your problem.

**Comment by OPerel** [comment]
Hi @rstoenescu,
I ran `npm install` in /src-capacitor.
Nothing changed.

Thank you!

**Comment by rstoenescu** [comment]
Are you managing deps with workspaces or anything similar? Cause the Capacitor CLI bin file is not where it's supposed to be.

**Comment by OPerel** [comment]
> Are you managing deps with workspaces or anything similar?

No. So I guess that's the problem.
The file is definitely in `src-capacitor\node_modules\@capacitor\cli\bin\capacitor`:

![folder](https://user-images.githubusercontent.com/42510547/79669611-5f8f7900-81c5-11ea-9deb-dd474c50d70f.JPG)
 
Any idea on how I can resolve this?
