### ISSUE TITLE
quasar build -m cordova breaks dev server

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#6846]
**Describe the bug**
Immediately after running quasar build for cordova mode, the dev server stops working. Page gets reloaded but no script is executed, app is not mounted in "q-app".

Doesn't happen when building in SPA or PWA mode.

**Comment by rstoenescu** [comment]
Hi,

What's build got to do with devserver?
Please fill in the ticket template to understand more and try to be really specific on what you are doing.

Thanks.

**Comment by jeancaffou** [comment]
If dev server is running (`quasar dev`), when I do a cordova build (`quasar build -m cordova -T android / ios`), it renders the dev server unusable. I can see that it is still responding to requests, connects to the node websocket. Stuff in boot configs get executed, but the app doesn't mount in `<div id="q-app"/>` in `index.html`. It seems that javascript execution is stopped soon after page load, but there is nothing in the console.
I don't know why these (cordova and dev builds) are connected. They shouldn't be.
It doesn't matter if dev server runs in http or https mode.
If I do `quasar build -m spa` or `quasar build -m pwa` then the dev server and build still works normally.
If I restart the dev server after it breaks, it works normally again. It's just annoying to restart.

Is it possible that while doing the cordova build, some files required for the dev server to work, get removed, and f*cks up the dev build?

I will test further if it is caused by some plugin, for example I am using [webpack-auto-inject-version](https://github.com/radswiat/webpack-auto-inject-version).
It's the only thing that could be an issue. Will report back.

And this is extra in extendWebpack
```
        cfg.plugins.push(new WebpackAutoInject({
          componentsOptions: {
            components: {
              AutoIncreaseVersion: false,
              InjectAsComment: false,
              InjectByTag: true
            },
            InjectByTag: {
              dateFormat: 'yy-mm-dd@HH-MM-ss'
            }
          }
        }))
```

**Comment by jeancaffou** [comment]
Doesn't seem to be caused by WebpackAutoInject plugin.

**Comment by jeancaffou** [comment]
I am also using `@quasar/icon-genie`. Might be related.
Seems to happen after 
` app:build Extension(@quasar/icon-genie): Running beforeBuild hook... +5ms`

**Comment by rstoenescu** [comment]
I suspected this is your case, but wanted to make sure.
The architecture does not allow to run simultaneous quasar commands on the same project folder, be that quasar dev or quasar build.

**Comment by jeancaffou** [comment]
Allright, thanks for the info @rstoenescu 

Running quasar dev and build spa / pwa simultaneouisly works though.

**Comment by rstoenescu** [comment]
Regardless of whether a particular quasar.conf.js configuration works or not on a dev + build case, please avoid it. Run each command separately and not simultaneously, otherwise there may be unpredictable consequences that may slip at first glance.
