### ISSUE TITLE
Can QBtn has its own right or left side icon with icon's own color?

### ISSUE THREAD

**Issue by PremiumNoFreemium** [quasarframework/quasar#6847]
Lets' say there's a **QBtn** component with label **"Hello Quasar"**. And you add and _right_ or _left icon_ of "info" from **_material-icons_**. This looks great, am I right? And then you want the **button will have its own background color**. For instance if we give the button **_Quasar color of "red-6"_**,just we want to give the Quasar color of **_"red-5"_** to the icon background. And it now looks more great. _What about that can anyone add something like this?_

**Comment by pdanpdan** [comment]
Hello. For help requests please head to the discord channel or to the forum.

**Comment by rstoenescu** [comment]
Yes, it's possible. Just use the default slot to define your QIcons and label instead of using the QBtn props.

**Comment by OtabekSadiridinov** [comment]
Hi, @rstoenescu, I finally did it. But why Quasar can't have such a good button.
I used some tricky ways true 😄 But  what about adding such thing. icon-bg="primary" and icon has its own background. I tried to give class of bg-primary 🙄  to the icon but because of the padding space in the button the icon background color couldn't cover full button. Ha ha 😃 it worked now with hacky way. Please add this kind of awesome thing to Quasar. I think everyone loves it. 👍

**Comment by OtabekSadiridinov** [comment]
https://codepen.io/Impeccable-Ninja/pen/dyYvGMm

**Comment by OtabekSadiridinov** [comment]
In the above one it is working perfectly but with some unnormal changes with padding and margins.
But here if I don't specify that properties it is problem.
https://codepen.io/Impeccable-Ninja/pen/jObBWGW?editors=1010

Have a great day!

**Comment by OtabekSadiridinov** [comment]
Oh, I found what is making this padding it was .q-btn__wrapper class has 16px of padding.
If you add icon-bg prop you can just make that padding zero 😄 Hhm, I think there is a way.

**Comment by OtabekSadiridinov** [comment]
Huh, No way? No way of doing that in Quasar?
Ah, just I will never finish project. What it would be even if I have such kind of button?
Whatever, the block mode(full-width) will be a problem. 😢😭Oh nooo.
Sorry if I bothered you.

**Comment by rstoenescu** [comment]
Just use CSS to override the selectors that get in your way...
