### ISSUE TITLE
Manage electron app as capacitor's module

### ISSUE THREAD

**Issue by deckyfx** [quasarframework/quasar#6849]
I added the electron to the capacitor-quasar target, using ```npx cap add electron```  but the build command, as you documented it only support ios and android 

```quasar dev -m capacitor -T [ios|android]```

**Comment by rstoenescu** [comment]
Hi,

We have our own Electron mode.

Handling Capacitor's Electron mode would not be in your interest as a developer using Quasar. It would mean that we are spreading our resources thin. And the most troubling part would be that any bug will be reported here but it will be out of our control.

Sorry, but we can't have this.
