### ISSUE TITLE
[docs] Document argument types for @add and @remove in QSelect

### ISSUE THREAD

**Issue by rabbiveesh** [quasarframework/quasar#6852]
I'm using the QSelect component in my app, and I noticed something surprising.
I'm using the `use-input` and `use-chips` and `multiple` options, and I'm updating the backend via the `@add` and `@remove` events.

I found that the `@remove` event gave me the removed value (`details.value`) in an array (even though only one value can be removed at a time), and the `@add` gives me the value as one string. If this is the intended behaviour, the docs should mention that explicitly. If this won't always happen that way, then there should be clearer docs about what to expect.

**Comment by pdanpdan** [comment]
It's an inconsistency in how `@remove` works.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.16
