### ISSUE TITLE
There is some misspelling in in the Quasar BEX types page.

### ISSUE THREAD

**Issue by PremiumNoFreemium** [quasarframework/quasar#6854]
I was reading. Then see an incorrect path url. There the ``css`` was defined as the ``.js`` extension.
I thought there will never be **.js** in the _css_ folder. So just writing and telling about that.
Below is a picture that shows the error and  the url.
https://quasar.dev/quasar-cli/developing-browser-extensions/types-of-bex
![image](https://user-images.githubusercontent.com/60849894/79688725-9dde7400-8269-11ea-9206-b127160f5ee2.png)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fixed and will be available in next docs deployment.
