### ISSUE TITLE
Multiple execution @virtual-scroll on QTable when loading prop changes

### ISSUE THREAD

**Issue by igisev** [quasarframework/quasar#6855]
**Describe the bug**
In the QTable component, while using the "virtual-scroll" and "loading" props, the "@virtual-scroll" event is executed many times.
The "@virtual-scroll" event is executed every time the "loading" prop changes.
This is the wrong behavior.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/igisev/pen/VwvjJWG

The example uses 2 tables.
The first table for the event "@virtual-scroll" uses the method "onScroll1" and prop "loading".
The second table uses only the "onScroll2" method without the "loading" prop.

Note.
Uncomment the code inside the onScroll1 method.
This may cause the page to freeze.

**To Reproduce**
1. on QTable use virtual-scroll and loading props at the same time
2. at @virtual-scroll event change loading prop several times

**Expected behavior**
The "@virtual-scroll" event should not depend on a change in the "loading" prop.

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers: Chrome 80.0.3987.163
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
The loading indicator makes the table re-render, so a new `@virtual-scroll` event is emitted - it's normal and expected.
In the handler you should check and avoid re-rendering the table (correct as implemented in codepen - except when starting to toggle loading).
There is nothing I can think of that can be done at framework level.

I'll leave this open - maybe I or someone else will come with an idea.

**Comment by igisev** [comment]
> The loading indicator makes the table re-render, so a new @virtual-scroll event is emitted - it's normal and expected.

I don`t think this is expected.
For example, changing the hide-bottom prop does not re-render.

> In the handler you should check and avoid re-rendering the table

Now we use a code similar to the code below.
We modify this.loading inside the "@virtual-scroll" event because this is the best place to do this.
In a real project, in some cases we get a crash of browser page, because when changing this.loading, the "@virtual-scroll" event sometimes occurs not 2 times, but much more often.

these is typical code for using the "@virtual-scroll" event
```es6
  /**
   * @nothrow
   */
  public async onVirtualScroll({ ref, to }) {
    if (this.loading) {
      return;
    }

    let isComplete = 'some code here';
    let isEndOfList = 'some code here';

    if (isComplete || !isEndOfList) {
      return;
    }
    
    // cancel previous active fetch here
    if (this.abortController) {
      this.abortController.abort();
    }
    this.abortController = new AbortController();

    try {
      // point of interest
      this.loading = true;

      // @throws
      let fetchResult = await fetch('api/method', { signal: this.abortController.signal });
      this.tableData = await response.json();

      await new Promise(r => this.$nextTick(r));
      ref.refresh();
    } catch (e) {
      //
    } finally {
      // point of interest
      this.loading = false;
    }
  }
```

**Comment by pdanpdan** [comment]
`hide-bottom` does re-render, but the changes are not inside the virtual scroll area, so there is not scroll event.
And about the loop/lock - as I told you the code is wrong - you toggle the loading prop inside the event handler, but you check and only prevent re-entry when loading is true - so you get loops.

https://codepen.io/pdanpdan/pen/XWmNmGa?editors=1010

**Comment by igisev** [comment]
> https://codepen.io/pdanpdan/pen/XWmNmGa?editors=1010

I think `this.inOnScroll1 = true;` should be inside quasar and not in user code.

Your code is for the simplest case, however in a real application you sometimes have to cancel the "@vitrual-scroll" event from the outside. For example, when filters change, we need to reset the data in the table and fire the "@virtual-scroll" event manually.

Complete example for you from our real application.
**Steps to reproduce a crash of browser page:**
- check "Use loading"
- Press "Start / Stop" button
- Type "d" to text field
https://codepen.io/igisev/pen/dyYOVPP?editors=1010

**Comment by pdanpdan** [comment]
That is your user written handler. The framework cannot know what you want to do in your code. You cannot cancel the event - the scroll event that is the main trigger is not cancelable.

**Comment by pdanpdan** [comment]
ok, I just found out I'm an idiot :)
there is a watcher on the classes applied on the table, and it triggers a refresh of the content

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.2.

**Comment by igisev** [comment]
better late than never =)

**Comment by pdanpdan** [comment]
:)
