### ISSUE TITLE
Datetime doesn't work properly on Safari

### ISSUE THREAD

**Issue by galan83** [quasarframework/quasar#686]
### Software version

Quasar: Beta 14
OS: OSX
Node: 0.7.3
NPM: 3.10.10
Browsers: Safari 10.0.3
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
TypeError: undefined is not an object (evaluating 'this.monthNames[this.month - 1].slice')
### What steps did you take, to get the error?
I use the datetime component in this way:
            <q-datetime
              v-model="form.scheduled_at"
              type="datetime"
              clear-label="Limpiar"
              ok-label="Aceptar"
              cancel-label="Cancelar"
              format="DD-MM-YYYY HH:mm"
              float-label="Programa la fecha y la hora de publicación"
              sunday-first
              :month-names="monthNames"
              :day-names="dayNames"
            ></q-datetime>

where monthNames and dayNames are like:

    monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    dayNames:  ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

Things work well in Chorme and Firefox browsers.

Thanks in advance.

**Comment by rstoenescu** [comment]
Hi. I see it working on Safari. Can you please elaborate a little?
Mind that day-names must start with Sunday, not Monday. It's in the docs.

**Comment by galan83** [comment]
Hi, I've changed day names array to start with Sunday, thanks.

I still have the error in safari, did you try to test it passing v-model value with a date?, if you don't have a v-model date value it is ok, but when you have one it fails.

Thank again.

**Comment by rstoenescu** [comment]
@galan83 yes, naturally. what is the value you are using as v-model?

**Comment by galan83** [comment]
I have tested this morning again and now seems to work properly. I don't now what was happen yesterday.

Thank you.
