### ISSUE TITLE
Popup editing in a sorted table column

### ISSUE THREAD

**Issue by pavel-at-adamos** [quasarframework/quasar#6860]
**Describe the bug**
There is unexpected behaviour when trying to popup edit a cell in a sorted table column. If the value is changed so that the sorting gets updated, then when trying to save the change the value of another row  is returned instead of the row being edited.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pavel-at-adamos/pen/abvBoyb
The codepen from the documentation can also be used - https://quasar.dev/vue-components/table#Popup-editing

**To Reproduce**
1. Go to the codepen link
2. Sort the Calories column
3. Edit the calories of the Frozen Yogurt row to a value greater than 237 so that the sorting gets updated
4. Click on Set to save the value
5. You should see 237 in the alert, which is the value of the Ice cream sandwich

**Expected behavior**
When editing the table cell in a row with a popup, the table sorting should not interfere with the editing.

**Comment by pdanpdan** [comment]
PopupEdit is directly changing the model (and undoes the changes on cancel) - so on any change of the ordered column you would end up with a redraw.

The best solution is to work on a row clone, like here:
https://codepen.io/pdanpdan/pen/bGVBGPd?editors=1010

**Comment by pavel-at-adamos** [comment]
@pdanpdan works like a charm! Thank you!
