### ISSUE TITLE
[docs] Example of making a Layout column fixed using "view" prop

### ISSUE THREAD

**Issue by sagrawal-idrc** [quasarframework/quasar#6861]
Ref URL: https://quasar.dev/layout/layout

Documentation says:

> For example, if you want your layout’s right side / drawer to be placed on the right of the header, page and footer, you’d use hhr lpr ffr. If you’d like to also make it fixed, just transform one r character to uppercase, like this: hhr lpR ffr, or hhr lpR ffr or hhr lpR ffr.

Shouldn't it say:

> For example, if you want your layout’s right side / drawer to be placed on the right of the header, page and footer, you’d use hhr lpr ffr. If you’d like to also make it fixed, just transform one r character to uppercase, like this: hhR lpr ffr, or hhr lpR ffr or hhr lpr ffR.

**Comment by rstoenescu** [comment]
Hi,

Thanks for catching this. Fixed and will be available on next docs deployment.
