### ISSUE TITLE
Arguments types missing  in boot() helper with Typescript

### ISSUE THREAD

**Issue by wowissu** [quasarframework/quasar#6862]
**Describe the bug**
I create a clean project with `quasar create <project_name>` choose use `typescript` 

Missing arguments types definition when using `boot()` helper which `import  { boot } from 'quasar/wrappers'`
[Boot-File](https://quasar.dev/quasar-cli/cli-documentation/boot-files#Anatomy-of-a-boot-file)

**Screenshots**
<img width="640" alt="Screen Shot 2020-04-22 at 3 42 53 PM" src="https://user-images.githubusercontent.com/12434914/79954461-ef784000-84af-11ea-939f-0a3325e736ee.png">

also missing something in `quasar/wrappers`
<img width="523" alt="Screen Shot 2020-04-22 at 4 16 40 PM" src="https://user-images.githubusercontent.com/12434914/79957770-aaa2d800-84b4-11ea-8632-f993d18caac3.png">

found in `boot.d.ts` on [IlCallo/quasar/ui](https://github.com/IlCallo/quasar/tree/adbea785f4b388ef1fb4ad333fdfdd0c76a6b14c/ui/types) but not [quasarframework/quasar/ui](https://github.com/quasarframework/quasar/tree/dev/ui)

**Platform Information**
```
Operating System - Darwin(19.3.0) - darwin/x64
NodeJs - 13.2.0

Global packages
  NPM - 6.13.1
  yarn - 1.21.1
  @quasar/cli - 1.0.5
  cordova - Not installed

Important local packages
  quasar - 1.9.15 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.7.1 -- Quasar Framework local CLI
  @quasar/extras - 1.6.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.6 -- Official router for Vue.js 2
  vuex - 3.1.3 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.9.0 -- Babel compiler core.
  webpack - 4.42.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.10.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-typescript - 1.0.0 -- A Quasar CLI Extension
```

**Comment by IlCallo** [comment]
@wowissu I just tried it and types work flawlessly...
Could there be something in your environment messing things up?

Wrappers types has been moved into `@quasar/app` package to avoid conflicts when using Quasar UI into a Vue CLI project, so you won't find them there anymore.
The link to my fork is of a commit previous to the change.

**Comment by wowissu** [comment]
@IlCallo I finally found the problem

It should be the typescript version of vscode
I used rare typescript version
<img width="294" alt="Screen Shot 2020-04-23 at 9 47 48 AM" src="https://user-images.githubusercontent.com/12434914/80050182-7fb59400-8547-11ea-9a8c-d3b33f9eff4d.png">
when I switch to 3.8.3 is work perfect. 

Close this issue and leave result. thx !
