### ISSUE TITLE
Add custom-service-worker.js to Webpack Bundle (pwa)

### ISSUE THREAD

**Issue by vykimo** [quasarframework/quasar#6863]
**Requested feature** 
Make `process.env` accessible in `custom-service-worker.js` for PWA.
I know that `process.env` is rendered manually by Quasar (because `process.env` does not exist on frontend) but I cannot understand why the feature is accessible everywhere excepted in `custom-service-worker.js`.

**How to reproduce**
We are able to check `process.env.DEV` in `register-service-worker.js` but in `custom-service-worker.js`, when I try to print env var like that :
```
self.addEventListener("fetch", async event => {
  console.log(process.env)
  event.respondWith(handleRequest(event));
});
```
You'll get error on console.

**Comment by hawkeye64** [comment]
@vykimo The information for process.env is handled by webpack: https://webpack.js.org/plugins/environment-plugin/

However, service-worker.js is not bundled by webpack so this cannot be done.

**Comment by trymbill** [comment]
@vykimo, how did you end up implementing this? I've got environment variables I don't want in git or saved anywhere other than within a `.env` file locally or encrypted on the server. Not sure how I'm supposed to use `custom-service-worker.js` with different environment variables for different environments.
