### ISSUE TITLE
Add Debricked to readme and website as sponsor

### ISSUE THREAD

**Issue by Powersource** [quasarframework/quasar#6865]
[Debricked just started making a monthly](https://opencollective.com/quasar#section-contributors) $250 donation to quasar! :) So we (I work there) would like to be added to the readme and website.

You can use [this image](https://debricked.com/wp-content/uploads/2019/04/debricked_black-2048x364.png) if you're putting it on a white background. With a link to [our website](https://debricked.com/).

---

The donation page also says "Your feature requests get priority.". How do we go about this? I [have created some feature requests](https://github.com/quasarframework/quasar/issues/created_by/Powersource), is it enough that I'm part of the [Debricked github org](https://github.com/debricked) for these issues to get prioritized?

**Comment by rstoenescu** [comment]
Hi,

Thank you again for becoming our sponsor!
We need more funding to grow, so this is very welcomed.

It would have been easier if the donation was made through Github Sponsorship (which notifies us directly that a sponsor has logged a ticket). Will mark your Github username to remember it.

And yes, of course, tickets logged by sponsors/backers take priority over anything else.

Added the logo to the sponsors list -- on docs website it will be available on next deployment.

Cheers,
Razvan
