### ISSUE TITLE
Error css in chips on QSelect

### ISSUE THREAD

**Issue by PH7-Jack** [quasarframework/quasar#6866]
**Describe the bug**
Erro de css no q-select usando o atributo use chips

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pedro-henrique-the-flexboxer/pen/qBORZGb
 

**Screenshots**
![Screenshot from 2020-04-22 17-15-02](https://user-images.githubusercontent.com/38913462/80029954-eb531f00-84bd-11ea-9fe5-63b4d6ae253b.png)

**Additional context**
I solved this css error by placing an attribute by css, follow the example in codepen

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.16.
