### ISSUE TITLE
Show side of phone in docs even with smaller browser window.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#687]
Dear Razvan,

I believe it's important to try and keep any new people who come check out the website.
First impressions are really important!

I'm a person who usually keeps my browser width at around 800~1000 pixels when I'm browser, and have some things or other pages open next to it. I'm sure there are a lot ppl like me.

Currently there is no visual indication of the smartphone sitting there on the right side if you make your browser window bigger than 1200 pixels. And personally I think being able to see this in the docs was originally a big win for Quasar. I immediately fell in love.

That's why I'm thinking, even on smaller window widths you should slightly see the side of the phone. As this will engage people to wider than browser windows, and make them quasar fans forever. : D

**Comment by spectrolite** [comment]
I absolutely agree this demo preview next to the docs is immensely useful and a HUGE, easily spotted and all too rare selling point for the framework. It should be more apparent at first glance whatever the window size. The how doesn't matter much, it should just be somehow more visible (or hinted at) at all window desktop widths.

**Comment by rstoenescu** [comment]
Hi, let's move this to docs repo. Thanks. I totally agree with the remarks.
