### ISSUE TITLE
q-markup-table border issues with rowspan

### ISSUE THREAD

**Issue by jnouza** [quasarframework/quasar#6874]
**Describe the bug**
Some left side borders on TD don't render. It's related to the <td rowspan="5"> on the left side.
Also very botom border of TD with rowspan is thicker.
There will be similar issue for colspan

Related to the: https://github.com/quasarframework/quasar/issues/6168

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jnouza/pen/ExVZEQy

**Expected behavior**
All cell have the same border. Table bottom border on a column, that has cell with rowspan at the botton dosn't have a thicker border.

**Screenshots**
https://www.screencast.com/t/G80iq6ERT

**Platform (please complete the following information):**
OS: Windows 10, 64 bit
Browsers: Chrome, latest

**Additional context**
Realated to these styles:
.q-table--cell-separator td:first-child, .q-table--cell-separator th:first-child, .q-table--vertical-separator td:first-child, .q-table--vertical-separator th:first-child {
    border-left: 0;
}
as td:first-child is applied, even when it is visually the 2nd ćolumn

**Comment by rstoenescu** [comment]
Hi,

We cannot write CSS to encapsulate all of the use-cases when row-span or col-span are being used without jumping Quasar's CSS by a few tens of K. The developer would have to write the CSS for himself/herself.
