### ISSUE TITLE
CSS class .q-field--with-bottom missing for q-select

### ISSUE THREAD

**Issue by StefanNeuser** [quasarframework/quasar#6877]
Hi Guys,

labels from q-field's have a css class .q-field--with-bottom but q-select not. This ends up with not well placed elements accross a form.

Regards

**Comment by pdanpdan** [comment]
Hello. What do you mean by label? please add a codepen showing the problem.

**Comment by pdanpdan** [comment]
Please reopen when you have relevant information. Thank you.
