### ISSUE TITLE
ssr authentication not working https://github.com/modemb/larasar

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#6879]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by modemb** [comment]
how can I make work the ssr authentication  https://github.com/modemb/larasar

**Comment by rstoenescu** [comment]
Please use our Discord server if you need help. Github is reserved for issues and feature requests. Thanks.
