### ISSUE TITLE
[request] 0.14 q-collapsible 'disable' prop

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#688]
### Software version

Quasar: 0.14
OS: Windwos 10 64-bit
Browsers: Vivaldi 1.10.862.6 (Official Build) (64-bit)

### What did you get as the error?
Setting the `disabled` state of `q-collapsible` to `true` changes the look of the component, but it still responds to clicks and opens / closes as normal.

### What were you expecting?
The collapsible item would show in 'greyed out' style, and not respond to clicks.

**Comment by pdanpdan** [comment]
There is no disabled state in QCollapsible.

**Comment by dsl101** [comment]
Well, if you apply the `disabled` prop, it _looks_ disabled. This is the code snippet:

      <q-collapsible
        :disabled="numComments === 0"
        icon="fa-comments"
        :label="plural(numComments, 'Comment', 'Comments')"
        dense
      >

In any case, if `disabled` isn't really supported, what would be the best approach to achieve this:

![image](https://user-images.githubusercontent.com/900542/27854207-bfe0b1e2-615d-11e7-8454-99723cc3107a.png)

which should not 'open' when clicked, and indeed shows the 'disabled' mouse pointer, to this:

![image](https://user-images.githubusercontent.com/900542/27854223-d3361ad4-615d-11e7-8fde-27cac366fb04.png)

which should open?

**Comment by dsl101** [comment]
Looking at the code, it would seem that adding a `disabled` prop, and this change would do the trick no?

    toggle () {
      if (!this.disabled) {
        this.active = !this.active
      }
    },

Obviously it could still be opened in code, closed by a group, etc. But that makes sense to me - the `disabled` state is more about the UI than functionality...

**Comment by dsl101** [comment]
As a final 'nice-to-have', the display of the drop arrow could also be dependent on the `disabled` prop, so it would look like this:

![image](https://user-images.githubusercontent.com/900542/27858199-3e0c130a-616c-11e7-8c35-ac002afe027c.png)

with something like this from line 13:

    <q-item-tile
      icon="keyboard_arrow_down"
      class="transition-generic"
      :class="{'rotate-180': active, invisible: disabled}"
    ></q-item-tile>

**Comment by pdanpdan** [comment]
I think it doesn't make sense to use QCollapsible if you have no children. It's more efficient to use a v-if/v-else and use a normal item with the desired disabled content.
That way you have full control on display.
I don't see a case when you would want a disabled QCollapsible with open content.

**Comment by dsl101** [comment]
Agree 100% with your last point - I was just pointing out that if it was part of a group and became disabled, it would still behave 'properly'.

Regarding the first point, it makes the user-side code bloated and less readable, and makes keeping the design of the 'enabled' collapsible and the 'disabled' item the developer's problem, whereas it could, with very little extra code, be entirely done by the library. I thought that's what libraries were for :).

**Comment by rstoenescu** [comment]
1. QCollapsible does not have a disabled prop.
2. `disable` as DOM element attribute is a global CSS helper. It works on any element and applies a disabled cursor and fades the element.
3. I'm currently on vacation, if you think things could be improved and it's easy (like you mentioned), please help out and provide a PR.

Thank you.

**Comment by dsl101** [comment]
Happy to try. Just to be clear though - you said the `disable` attribute creates the visual effect, but when I do this:

    <q-collapsible :disabled="numComments === 0">

I get the effect (which is dynamic as `numComments` changes) as if `q-collapsible` had a `disabled` property. I wasn't applying the `disable` (no 'd') attribute directly. Does something translate one to the other?

**Comment by pdanpdan** [comment]
- "disabled" attribute has a global CSS rule to apply disabled cursor and fading (same thing can be obtain using "disabled" class)
- Quasar components use a property named "disable" (action, not state) to tell if the component should be disabled or not

**Comment by dsl101** [comment]
Right - so, to clarify:

- `disabled` _attribute_ - apply the fading and cursor via CSS
- `disabled` _class_ - same as above
- `disable` _prop_ - boolean to be interpreted by the component

and with that last one, presumably the component would normally apply the `disabled` attribute / class to any of its UI elements when `disable === true`?

I'm keen to try adding this to `q-collapsible` - at least for my projects. Is there a guide anywhere about getting started on Quasar development? I'm presuming I'll need a fork of the project and a local clone to work on. But how to build and test that version locally? Is it just `npm build` and copy `dist` into my application's `node_modules\quasar-framework`? Or is there a more elegant way?

**Comment by rstoenescu** [comment]
Yes on all three bullets. Add "disabled" class when "disable" prop is `true`.
But please make a PR on this so other can benefit from it too. https://github.com/quasarframework/quasar/blob/dev/.github/CONTRIBUTING.md

**Comment by pdanpdan** [comment]
1. On QCollapsible - only apply disabled class (or attribute) on the list item that toggles the collapse (not on the whole components, as this would apply the style on the child content) - so on the wrapper.
2. Fork the project, npm build and copy dist is the simplest method
3. You can also fork and change package.json to publish in your own repository in master and use that as source in your project

**Comment by dsl101** [comment]
Yes, I will. It was the setup for dev and testing I wasn't sure about - I didn't spot that link before. Tx.

**Comment by dsl101** [comment]
OK - I think I did what's needed. Let me know if the PR looks OK. I updated the `dev` demo page to show it in action, based on the state of the previous collapsible.

**Comment by JCharante** [comment]
Pull Request: #697
