### ISSUE TITLE
QInput QSelect style

### ISSUE THREAD

**Issue by perochak** [quasarframework/quasar#6880]
**Having default input style will be great**
If there is option to have default input/select styles like having label than input than error/hint will be great. 

Also, if there could be option for template which enable to structure the output as required will be great

`<q-input template="{label}{input}{hint}{error}" ></q-input>`

Same for q-select and other form elements will be great feature.

**Comment by pdanpdan** [comment]
Hello. This is not in the scope of the components. If you need exotic things you can try to adjust the order using css or better build the components you need.
