### ISSUE TITLE
Need a TypeScript support for the Bex mode

### ISSUE THREAD

**Issue by Arsync** [quasarframework/quasar#6883]
With project, written on TS, got message
```
(TS) Property 'bex' does not exist on type 'QVueGlobals'.
```
for `this.$q.bex` in App.vue

For @webnoob

**Comment by webnoob** [comment]
@Arsync Once the PR's are merged, this should be it.

**Comment by rstoenescu** [comment]
Merged both. Fix will be available in "@quasar/app" v1.7.5.
