### ISSUE TITLE
Root page '/' link on left and right drawers always show as 'active'

### ISSUE THREAD

**Issue by DaveAuld** [quasarframework/quasar#6885]
**Describe the bug**
I have a home link on my left drawer, and it always remains in the active state, regardless of which page I am actually on.
All other links work correctly, and only show active when the $route.path check is performed on the :active binding.

On the codesandbox below, I recreated from scratch a basic representation of what I have done, with a left and right drawer and a few links. I put the home and somepage links on each drawer, and another dashboard link on the right drawer only. You can see that the Home ones always show 'active' regardless of which page selected.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/dark-tdd-j70o1

**To Reproduce**
1: Add home items to a left or right drawer,
2: user a bind to :active and check against $router.path=== 'the page path'

**Expected behavior**
The home link should be black when not on the index page  '/'
The home link should be active (blue) when only on the index page '/'

**Screenshots**
![image](https://user-images.githubusercontent.com/4674288/80286666-5bb7a580-8735-11ea-8ece-92fc7fc2b487.png)

**Platform (please complete the following information):**
OS: Windows 10Pro version 1909
Node: v12.16.1
NPM: v6.13.4
Yarn: 
Browsers: Chrome 81.0.4044.122 (Official Build)(64-bit)
iOS:
Android:
Electron:

**Additional context**
The codesandbox and the build at my home machine, have not shared any code or cloned. Codesandbox demo was direct from their scratch reference build.

**Comment by pdanpdan** [comment]
Hello - please read the docs for Vue Router - mainly the part about exact.
And please use the discord channel or the forum for quasar related help requests.

**Comment by DaveAuld** [comment]
Brilliant, many thanks for the help. Problem solved.

Link below for others who may stumble across this........

https://router.vuejs.org/api/#exact

**Comment by kishsak** [comment]
Thank you for the solution. It works for me too
