### ISSUE TITLE
debounce helper breaks if immediate is set to true

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#689]
### Software version

Quasar: 0.14.0
OS: Linux 4.11.7-1-ARCH
Node: v8.1.3
NPM: 4.5.0
Browsers: Firefox 54.0.1 (64-bit) / Chromium 59.0.3071.115 (64-Bit)
iOS: - 
Android: - 
Any other software related to your bug: - 

### What did you get as the error?
When the third parameter of the debounce function is set to true the function that should be debounced is never called. When it is set to false, it works as expected.

### What were you expecting?
The function should be called and the immediate parameter should be respected.

### What steps did you take, to get the error?
Initalize a fresh Quasar project via CLI and create a new component:
```vue
<template>
  <q-btn @click="handleClick">Test</q-btn>
</template>

<script>
  import {
    QBtn,
    debounce
  } from 'quasar'

  export default {
    methods: {
      handleClick: debounce(function () {
        console.log('Click handled')
      }, 200, true)
    },

    components: {
      QBtn
    }
  }
</script>

```
If the button is pressed, nothing happens.

**Comment by mstaack** [comment]
debounce return the function
```
methods: {
  onResizeMasonry: () => {
    console.log('resizing')
    this.debouncedFunction()
  }
},
mounted () {
  // we create the debounced function
  this.debouncedFunction = debounce(() => {
    console.log('updating')
    this.$refs.devicesMasonry.iso._requestUpdate()
  }, 500)
}
```

see http://forum.quasar-framework.org/topic/324/debounce-trouble/7

cheers max

**Comment by a47ae** [comment]
@mstaack I don't think this issue has something todo with the issue you posted.
I am currently in the progress of migrating an Quasar 0.13 app to 0.14. In the previous version the code was functional as described above. Also the above snippet works if the immediate parameter is set to false, like so

```vue
<template>
  <q-btn @click="handleClick">Test</q-btn>
</template>

<script>
  import {
    QBtn,
    debounce
  } from 'quasar'

  export default {
    methods: {
      handleClick: debounce(function () {
        console.log('Click handled')
      }, 200, false)
    },

    components: {
      QBtn
    }
  }
</script>
```

**Comment by rstoenescu** [comment]
Available in latest v0.14 beta.

**Comment by mstaack** [comment]
@a47ae sry for that :) raz fixed it

**Comment by spectrolite** [comment]
I love how quasar bugs get fixed at lightning speed and pushed to edge immediately. We'll have to learn to be more patient in the coming days... Razvan is finally taking a well deserved holiday.

@rstoenescu I think I'll start calling you The Flash.

**Comment by a47ae** [comment]
@mstaack No problem, I wasn't sure mysel at first if this is a real bug :D 

And I can only agree on what @spectrolite said, I filed two issues and both were fixed in less than a day!
@rstoenescu keep up the good work, Quasar is really an awesome project. And enjoy your days off :)

**Comment by rstoenescu** [comment]
=)))))
Doing best I can... from vacation :)
