### ISSUE TITLE
using forked library as dependency throws error

### ISSUE THREAD

**Issue by TheHussein** [quasarframework/quasar#6890]
**Describe the bug**
I forked the project and made some changes to the q-tree component to fit my requirements, Now everytime I run quasar dev I get the following error

```
/Users/omar/projects/main/node_modules/@quasar/app/lib/helpers/banner.js:4
const quasarVersion = getPackageJson('quasar').version
                                              ^
[  TypeError: Cannot read property 'version' of undefined
```

**To Reproduce**
1. Remove existing quasar on any quasar project (`yarn remove quasar`)
2. Add our quasar (`yarn add https://github.com/TheHussein/quasar#dev`)
3. run development server (`quasar dev`)

**Expected behavior**
Development server to run properly without errors.

**Platform (please complete the following information):**
OS: Mac 10.15.4
Node: 14.0.0
NPM: 6.14.4
Yarn: 1.22.4

**Additional context**
Seems const quasarVersion = getPackageJson('quasar').version is returning undefined on the getPackageJson

This is how quasar looks in my package.json
`    "quasar": "https://github.com/TheHussein/quasar#dev",`

**Comment by rstoenescu** [comment]
The approach is wrong, but let's take it one by one:

1. The "quasar" package has a build step ("yarn build"). If you're using your own fork, you need to build it and include the dist folder in the npm package -- in your case, include it in your git repo (it's currently ignored through .gitignore).

2. There's a better approach than staying behind the official Quasar version. Why not import the source file for QTree and extend it instead into your own component. Then use your custom component.
