### ISSUE TITLE
Little icon misplacement with lang: 'zh-hans' option in FireFox

### ISSUE THREAD

**Issue by guogangj** [quasarframework/quasar#6892]
I set the lang option in quasar.js like this:

```
    framework: {
      lang: 'zh-hans', // Quasar language pack
      // ...
    }
```
And that’s the result:
![misplacement](https://forum.quasar-framework.org/assets/uploads/files/1587603862793-icon-misplacement.png)

OS: Windows 10 2004
Node: 12.13.1
NPM: 6.14.2
Yarn: 1.22.0
Browsers: 75.0 (64bit)

**Comment by pdanpdan** [comment]
Hello. And you can only reproduce this in Firefox with `lang: 'zh-hans'`? Or is it a general problem you see with Firefox?

**Comment by guogangj** [comment]
> Hello. And you can only reproduce this in Firefox with `lang: 'zh-hans'`? Or is it a general problem you see with Firefox?

Either 'zh-hans' or 'zh-hant' can reproduce this problem in Firefox.

**Comment by pdanpdan** [comment]
Hello. I am sorry but I cannot reproduce it. I need a codepen showing the problem or the exact step by step instructions to reproduce it.

**Comment by guogangj** [comment]
> Hello. I am sorry but I cannot reproduce it. I need a codepen showing the problem or the exact step by step instructions to reproduce it.

I tried it on Ubuntu 20.03 (English environment) with Firefox 75, this issue is not exist. So, I am wondering if it is something to do with my Chinese Windows 10 operating system. Because I don't have a English Windows 10 OS environment, I am not very sure.

**Comment by pdanpdan** [comment]
But if you set the page to use 'en-us' on the Chinese windows does the problem show?

**Comment by guogangj** [comment]
> But if you set the page to use 'en-us' on the Chinese windows does the problem show?

No, it does not. Perhaps it's a bug of Firefox, because I found nothing suspicious things in the DOM structure. As far as I know, this problem appears only in Firefox on Chinese Windows OS with Quasar's zh-han option.

**Comment by rstoenescu** [comment]
Seems like unfortunately there's nothing that we can do about it :(
