### ISSUE TITLE
Recursively expand tree till a node (QTree component)

### ISSUE THREAD

**Issue by sagrawal-code** [quasarframework/quasar#6894]
I wanted to expand the `QTree` component till a node. Currently I wrote a recursive function looking for the parent of the node and start expanding once it reaches the first parent which isn't expanded yet.

Maybe something like this can be built into `QTree`?

I am not sure how lazily loaded nodes can be handled in this case. I call the recursive function only after the node's children have loaded.

**Comment by pdanpdan** [comment]
Closing this to track it in https://github.com/quasarframework/quasar/issues/6959

**Comment by pintaf** [comment]
I also build a custom code to do this.
Huge tree, lazy loaded, I wanted to be able to go to a specific children, and also the tree to scroll to this specific child.

For the scrolling part, here is what I did:
[V](https://forum.quasar-framework.org/post/20388)

**Comment by Code-Case** [comment]
> I also built a custom code to do this.
> Huge tree, lazy loaded, I wanted to be able to go to a specific children, and also the tree to scroll to this specific child.
> 
> For the scrolling part, here is what I did:
> https://forum.quasar-framework.org/post/20388

could show me some of the custom code to be able to go to a specific child? Im trying to do the same.

**Comment by pintaf** [comment]
Have your tired implementing the code I showed in the forum thread ? if it is not working, can you share a codepen or similar ?
Maybe better to continue the conversation in the forum

**Comment by hawkeye64** [comment]
Here is some code I used for a file explorer (electron) to recursively open a tree to the right location: https://github.com/hawkeye64/electron-quasar-file-explorer/blob/master/src/components/folderTree.vue#L82
