### ISSUE TITLE
bug: q-carousel-slide - some characters in img-src attribute are breaking the component

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/quasar#6898]
**Describe the bug**
When characters "(" or ")" are used in img-src attribute in q-carousel-slide the image on specific slide is not displayed. Thumbnail image is displayed though.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/qyloxe/pen/GRpEoPY

**To Reproduce**
click on the first or second thumbnail in codepen example. There are no images, because in img-src attribute are characters "(" or ")".

**Expected behavior**
Component should work as described in documentation - the img-src attribute might not be parsed and interpreted with some unknown set of characters.

**Screenshots**
screenshot - there is no image in carousel:
![image](https://user-images.githubusercontent.com/467508/80416880-21850a00-88d5-11ea-97ea-ee05bc37d175.png)

**Platform (please complete the following information):**
Browsers: chrome

**Additional context**

- Maybe there are more breaking characters than "(" and ")"?
- This is a potential XSS attack vector.
- Maybe in other components or their parts there is similar behaviour with some special characters which breaks something?
- Replacing "(" with "%28" and ")" with "%29" in img-src is a temporary solution.

**Comment by rstoenescu** [comment]
Fix will be available in the next release.
