### ISSUE TITLE
q-circular-progress:  Don't allow progress to go further after min/max value

### ISSUE THREAD

**Issue by Mirakurun** [quasarframework/quasar#6900]
I have an issue where the progress keeps going further after the specified min/max value.

I want the progress to remain blank/full depending on value reaching the min/max value. For example, progress should be blank if value is a negative value and if the min value is 0.

**Comment by pdanpdan** [comment]
Hello.
Then please use the functions provided by the Math library in javascript to limit the value to the min/max. You should validate the data before using it.

This is not a form control that is expected to change the input value.
