### ISSUE TITLE
Problem in Select Some Items of A Multi Select with toggle

### ISSUE THREAD

**Issue by alirezajs** [quasarframework/quasar#6903]
I'm using a multi-select component with toggle, everything is okay; except when I want to select some items as default selected. 
I've turned the v-model object to the flowing code:
 model: [
      {
          label: 'Google',
          value: 1
        },
      ]
I can see 'google' item as default selected in Select component but toggles weren't checked as default.

![image](https://user-images.githubusercontent.com/35213349/80581077-ddebe680-8a21-11ea-8ead-ca84e736e1a6.png)

you can see my code in [codepen](https://codepen.io/alirezavmm/pen/qBOXOJW?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fselect)

**Comment by pdanpdan** [comment]
if you use `map-options` and `emit-value` the model should be 1

**Comment by alirezajs** [comment]
Could you explain in more detail?

**Comment by pdanpdan** [comment]
Hello. Please use the discord channel or the forum for help requests. And read the docs first.
