### ISSUE TITLE
Scroll horizontally with mousewheel in QScrollArea

### ISSUE THREAD

**Issue by wowissu** [quasarframework/quasar#6904]
Hi ! 
When scrolling inner `<q-scroll-area horizontal>` with mousewheel there only go down or up
Could make it scrolled horizontally when I scrolling in area with mousewheel ? 

Add a attr like `<q-scroll-area horizontal scroll-horizontally>` 

or output the native event from scroll ? so I can implement it by myself.

here is solution for change direction of scroll to horizontally
https://stackoverflow.com/questions/31755803/how-to-change-the-direction-of-mousewheel-scrolling-on-an-html-page

Thx!

**Comment by pdanpdan** [comment]
The solution is native to each OS/browser (usually it's to keep SHIFT key pressed).
you have the native event if you attach `.native` modifier.
