### ISSUE TITLE
QField with clearable keeps focus state after clear + click outside

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#6906]
**Describe the bug**
QField with clearable prop seems to keep focus state after clicking the clear button and clicking outside the field. Only after then clicking into the field and back out will the focus appearance disappear.

**Seems to be specific to Firefox.**

This also seems to affect external validation triggering (e.g. a required rule not triggering until the field is refocused and reblurred so it does not appear to be only visual.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gordonblahut/pen/VwvzPKJ

**To Reproduce**
1. Go to https://codepen.io/gordonblahut/pen/VwvzPKJ
2. Click on the clear icon in the first input
3. Click outside the input
4. See the input still has a blue underline to indicate focus/active

**Expected behavior**
Focus appearance should be lost when clicking outside

**Screenshots**

**Platform (please complete the following information):**
OS: Windows_NT(10.0.18363) - win32/x64
Node: 10.15.3
NPM: 6.13.4
Yarn:1.21.1
Browsers: Firefox 75.0
iOS:
Android:
Electron:

**Additional context**
Seems to be specific to Firefox. QInput does not seem to be affected.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.10.0
