### ISSUE TITLE
[FR] Cascader Component

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#6907]
Hello Team;

I saw this powerful component that saves a lot of space and time for users using it to travel through cascading selects in ONE select component. Could you please consider such component?

Here is a link to what I saw.

Thank you in advance.
…Ben

https://www.antdv.com/components/cascader/

**Comment by hawkeye64** [comment]
@BenHayat You can achieve the same thing with QMenu: https://quasar.dev/vue-components/menu#Example--Menus-in-menus
