### ISSUE TITLE
Blurring when hovering over interactive elements in Chrome

### ISSUE THREAD

**Issue by artmakarov** [quasarframework/quasar#6908]
**Bug when using Chrome**
When the cursor hovers over a button or list item containing an icon or letter avatar-type, the outline of the icon or letter is blurred for a fraction of a second. Also, when you hover over a group element, the neighboring elements also blur the outline of the icon or letter avatar-type.

See the attached gif file:

![q](https://user-images.githubusercontent.com/37446577/80616318-72b60a80-8a49-11ea-84c8-85c17a24adbb.gif)

**Expected behavior**
Icon or letter avatar-type should not be blurred.

**Platform:**
OS: Windows 10
Node: 10.16.3
NPM: 6.14.3
Browsers: Chrome 81.0.4044.122 (Official build), (64 bit)

**Comment by pdanpdan** [comment]
Hello. You should open this on the Chrome, Webkit, and all video driver manufacturers bug trackers :)
Sorry - it's nothing we can do about it.

**Comment by artmakarov** [comment]
If you play with the location and styles of the "q-focus-helper" block, you can remove the blur.
FYI, this behavior is not observed in Vuetify and similar Material Design Frameworks.

**Comment by pdanpdan** [comment]
Then please make a PR with the fix. Thank you.
