### ISSUE TITLE
Build error :  SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by machliang** [quasarframework/quasar#691]
### Software version

Quasar: 0.13 above
OS: win10 64bit
Node: V8.1.2
NPM:  5.0.3
Browsers: NONE
iOS: NONE
Android: NONE
Any other software related to your bug: NONE

### What did you get as the error?
under the source root : node build\script.build.js
### What were you expecting?
build a modified quasar version
### What steps did you take, to get the error?
node build\script.build.js

**Comment by machliang** [comment]
Got the error message after building :
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\test\quasar-master\build\script.build.javascript.js:120:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

I traced the code and some docs, found the new UglifyJS has no "outSourceMap" option, that's why caused the undefined result and raise the error !

I update the script.build.javascript.js line 107~112 as following:
      //fromString: true,
      //outSourceMap: 'quasar.standalone.min.js.map',
      sourceMap: {
          filename: "quasar.standalone.min.js",
          url: "quasar.standalone.min.js.map"
      },
and the build process is ok~

**Comment by rstoenescu** [comment]
Hi,

Please use the recommended packages that get installed by the starter kit/boilerplate (`quasar init default` or `quasar init default#beta` -- latter will become default when releasing final v0.14).

I'm currently on vacation. If you think the starter kit can be improved, please help out and provide a PR (for this repo: https://github.com/quasarframework/quasar-template-default on "beta" branch).

Also mention what UglifyJS version you are using. Notice the semver notation. If a breaking change version is released for any package, then of course, upgrading to the new package should require some changes in the starter kit.

Let's continue talk on starter kit repo (mentioned above). Thank you!
