### ISSUE TITLE
icongenie 2 uses backslashes in cordova config.xml

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#6910]
**Describe the bug**
Icon paths in config.xml now have backslashes where they were previously forward slashes.

e.g. `<icon density="ldpi" src="res\android\ldpi.png" />` instead of `<icon density="ldpi" src="res/android/ldpi.png" />`

I suspect this is probably specific to Windows.

**Codepen/jsFiddle/Codesandbox (required)**
N/A

**To Reproduce**
1. Run icon genie with -m cordova

**Expected behavior**
Slashes should be forward slashes for consistency and possibly cross-platform compatibility.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows_NT(10.0.18363) - win32/x64
Node: 10.15.3
NPM: 6.13.4
Yarn: 1.21.1
Cordova: 9.0.0 (cordova-lib@9.0.1)

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this.
Fix will be available in "@quasar/icongenie" v2.1.0
