### ISSUE TITLE
Truncate word in q-table

### ISSUE THREAD

**Issue by arthur55** [quasarframework/quasar#6917]
Hi,

I met a problem truncating word a q-table.  
The original data is like this:  
![image](https://user-images.githubusercontent.com/8954015/80693482-a6566a80-8b05-11ea-9fec-705c7d1f43bb.png)

And I add attributes :  
```html
<q-td
  :props="props"
  :style="{width: '500px', whiteSpace: 'pre-wrap'}"
  auto-width
  class="ellipsis"
>
```
It then looks like:
![image](https://user-images.githubusercontent.com/8954015/80693714-02b98a00-8b06-11ea-820b-0dea1e3aa5b0.png)

But what I want is like this:
![image](https://user-images.githubusercontent.com/8954015/80693842-34325580-8b06-11ea-8d80-993452ffaf06.png)

I would like to truncate the word in the table cell.
Are there any solutions? Thank you!

**Comment by pdanpdan** [comment]
Please use the discord channel or the forum for help requests. Thank you.

**Comment by Kanglinwu** [comment]
@arthur55 
Hi, I just get the same issue, and i use the custom css to achieve this.

```
<q-td key="link" :props="props">
  <div class="row justify-center">
    <div style="width:200px" class="customEllipsis">{{ props.row.link }}</div>
  </div>
</q-tb>
```

```
.customEllipsis {
  text-overflow: ellipsis !important;
  white-space: nowrap !important;
  overflow: hidden !important;
}
```

hope this can help you

**Comment by mdhelaluddin-ctg-bd** [comment]
Hi, @arthur55 
How did you solve this?

**Comment by allan98** [comment]
thanks @arthur55 
https://quasar.dev/vue-components/table#example--body-cell-name-slot
