### ISSUE TITLE
0.14 Dialog reserved name

### ISSUE THREAD

**Issue by galan83** [quasarframework/quasar#692]
### Software version

Quasar: Beta 14
OS: OSX
Node: 0.7.3
NPM: 3.10.10
Browsers: Safari 10.0.3
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Dialog
### What were you expecting?
No warning message
### What steps did you take, to get the error?
Use Dialog component.

It seems that Dialog name is reserved name in HTML.

Thank you.

**Comment by rstoenescu** [comment]
How do you use it? Can you give an example?
Quasar does not use `dialog` as HTML component anywhere.

I strongly believe there is a misuse in your app. Please reopen with the template that you are using and how you import and call Dialog. Thanks!

**Comment by galan83** [comment]
Hi again

This is the import
`
  import {
    QBtn,
    QIcon,
    QSearch,
    QSelect,
    QInfiniteScroll,
    QSpinner,
    Dialog,
    Toast
  } from 'quasar'
`

The component:

`  export default {
    name: 'TopicList',
    mixins: [PaginatedList],
    components: {
      TopicListItem,
      QBtn,
      QIcon,
      QSearch,
      QSelect,
      QInfiniteScroll,
      QSpinner,
      Dialog
    },
    methods: {
      ...mapActions(['publishTopic', 'unpublishTopic', 'deleteTopic']),
      openPublishModal (topic) {
        this.selectedTopic = topic
        this.dialog = Dialog.create({
          title: 'Are you sure?',
          buttons: [
            { label: 'Cancel', color: 'negative', outline: true },
            { label: 'Publish', color: 'positive', handler: () => this.publish(), preventClose: true }
          ]
        })
      },
...
`

Thanks

**Comment by rstoenescu** [comment]
Hi. Why do you specify "Dialog" in the components object? This is the misuse. Dialog is meant to be imported and used directly. It is not a Vue component and should not be declared in components object.

**Comment by galan83** [comment]
Yes, sorry, that was the problem.

Thank you very much.

**Comment by zuck** [comment]
I received the same warning due to my misuse of the Dialog import...I think it's better to add a note to docs :wink:

**Comment by rstoenescu** [comment]
A PR would to docs would be awesome!

**Comment by zuck** [comment]
Done, check [#232](https://github.com/quasarframework/quasar-framework.org/pull/232)
