### ISSUE TITLE
Input v-slot breaks events

### ISSUE THREAD

**Issue by engineertdog** [quasarframework/quasar#6921]
**Describe the bug**
Attempting to perform a `submit` function for a form input, when using `v-slot:after` results in nothing happening. This happens when the only event is `@submit="sendMessage"` is present on the form, or if the submit button is in a `v-slot` template. This can currently be mitigated in two ways, as described below.

**Codepen/jsFiddle/Codesandbox (required)**
Wouldn't work with Vue3, which is what I'm using, but the issue happens with Vue2 as well.
https://codepen.io/engineertdog/pen/VwvMjZV

**To Reproduce**
Use the codepen, or implement the `script` and `html` in your own app.

**Ways to fix**
1. Remove the `v-slot` for the submit button, but this also breaks the ability to see the button.
2. Add `@click="sendMessage"` to the submit button, and it works like a charm.

**Expected behavior**

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/input#Slots-with-QBtn-type-%E2%80%9Csubmit%E2%80%9D
