### ISSUE TITLE
QTable - prop to force internal sorting and filtering when rowsNumber is specified - dynamic loading

### ISSUE THREAD

**Issue by kresten8** [quasarframework/quasar#6922]
**Describe the bug**
When using a Q-table with dynamic loading and you specify a rowsNumber, the sorting won't work.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pen/?&editable=true&editors=111=https%3A%2F%2Fquasar.dev%2Fvue-components%2Ftable

**To Reproduce**
1. Go to the example in Q-table with virtual dynamic loading
2. Click on any header to sort
3. Nothing happens

**Expected behavior**
Table gets sorted

**Comment by rstoenescu** [comment]
Hi,

This is by design since the purpose of querying the backend is to supply only the needed data.

**Comment by pdanpdan** [comment]
This was for me to think about it :)
But I think it's good as it is now.

**Comment by rstoenescu** [comment]
Thinking is hard
