### ISSUE TITLE
quasar create cli errors when AirBnB linting selected

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#6924]
Running @quasar/cli v1.0.0-rc.2 on Windows 10
`quasar create test`
With these selections:
? Project name (internal usage for dev) test-app
? Project product name (must start with letter if building mobile apps) Test App
? Project description A Test App
? Author Robert <robert@ .com>
? Pick your favorite CSS preprocessor: (can be changed later) Sass
? Pick a Quasar components & directives import strategy: (can be changed later) Auto import
? Check the features needed for your project: ESLint, Vuex, TypeScript, Axios, Vue-i18n
? Pick a component style: Composition
? Pick an ESLint preset: Airbnb
? Cordova/Capacitor id (disregard if not building mobile apps) org.cordova.quasar.app
? Should we run `npm install` for you after the project has been created? (recommended) NPM

results in:
```
 [*] Running eslint --fix to comply with chosen preset rules...



> test-app@0.0.1 lint C:\Temp\client2
> eslint --ext .js,.ts,.vue --ignore-path .gitignore ./ "--fix"


C:\Temp\client2\src\store\index.ts
  15:1  error  This line has a length of 111. Maximum allowed is 100  max-len

C:\Temp\client2\src\store\module-example\mutations.ts
  5:16  error    'state' is defined but never used  no-unused-vars
  5:16  warning  'state' is defined but never used  @typescript-eslint/no-unused-vars

✖ 3 problems (2 errors, 1 warning)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.0.1 lint: `eslint --ext .js,.ts,.vue --ignore-path .gitignore ./ "--fix"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-app@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Robert\AppData\Roaming\npm-cache\_logs\2020-05-01T14_56_31_435Z-debug.log

 npm install FAILED... Possible temporary npm registry issues?
 Please try again later...


PS C:\Temp> 
```
I think these are fix-able by the end user; just not great experience for newbies if the CLI fails out of the box.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting! Fixed it.
As the linting error says, it's simply about a parameter being declared and not used. You can either manually fix this or create a new project folder. But regardless, this does not ruin the newly created project.
