### ISSUE TITLE
ionicon v5 outline icons issue: svg files corrupted

### ISSUE THREAD

**Issue by Lobidu** [quasarframework/quasar#6925]
When using the new ionicon v5 svg icons with quasar-extras, the outlined version seems to have an issue: All outline icons that include an area, like a circle or rectangle are filled. This seems to be an svg issue.

**To Reproduce**
1. Use e.g. ionMailOutline or ionGlobeOutline  from '@quasar/extras/ionicons-v5';

**Expected behavior**
Icon should look like on the ionicon website

The issue does not occur with the non-outlined version

The issue occurs in both `<q-icon>` and `<q-input>` components, possibly other components, too.

<img width="198" alt="Screenshot 2020-05-01 at 16 57 26" src="https://user-images.githubusercontent.com/27945016/80819491-fa785200-8bcc-11ea-9af1-2c9156aa099c.png">

**Comment by Quasarman** [comment]
Same issue here can confirm.
![image](https://user-images.githubusercontent.com/30523269/80832472-06740c00-8bed-11ea-8ae7-3e54035ed66a.png)

**Comment by Quasarman** [comment]
btw @Lobidu how are you setting the ion-icons-v5? Do I really have to import each one that i want to use like this?
```
import { ionHome, ionCompass, ionBrowsersSharp, ...} from '@quasar/extras/ionicons-v5';
```
Or is there a more convenient way of setting them?

**Comment by Lobidu** [comment]
Yes. Since it looks like Ionicons v5 isn't available as a webfont (see #6425) this is the only way I found how to use them.

**Comment by rstoenescu** [comment]
Will fix. Please be patient :)

**Comment by rstoenescu** [comment]
Enhanced the parsing of Ionicons source for quasar/extras.

Fix will be in "@quasar/extras" v1.8.0 -- you will also need "quasar" v1.11+ (unreleased yet) for the enhanced QIcon svg format ([details](https://github.com/quasarframework/quasar/issues/6976)).

**Comment by Lobidu** [comment]
Can con firm this is working now - thank you!

@Quasarman since you asked, there is a more convenient way I found how to use all icons in all components:
If you assign the iconSet to a global prototyped property, like $i:
```// main.js
import * as iconSet from '@quasar/extras/ionicons-v5';

Vue.prototype.$i = iconSet;

new Vue({
  render: (h) => h(App),
}).$mount('#app');
```
You can access that global property inside the component without explicitly importing it:
```// myComponent.vue
<q-icon :name="$i.ionManOutline" />
```
That saves a bit of boilerplate code, although I guess it increases the bundle size since you import more icons than you need.

**Comment by Quasarman** [comment]
@Lobidu Thanks I already came up with a solution that fits me well for now. Basically its very similar to yours but im only importing the icoms I need and assign them to a global property to midigate the bundle size problem that arises when importing all the icons.
@rstoenescu Thanks for the update works like a charm now!
