### ISSUE TITLE
Set validation errors on QForm

### ISSUE THREAD

**Issue by aleksander237** [quasarframework/quasar#6926]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For server validation, it would be much "cleaner" to set returned errors on QForm instead of on each input separately. QForm could provide the error bag object to its descendants:

```
errors: {
    first_name: 'First name is required',
    last_name: 'Last name is required'
}
```

we already have the `name` prop on inputs, so an input control could simply inject the error bag object and pull error by its name. 

`<q-input v-model="first_name" name="first_name" label="First Name"/>`

If error bag has property and property is not empty then the error is displayed.

I saw this feature in one of the Vue frameworks. Unfortunately I don't remember on which one and cannot find it at this moment.

**Describe alternatives you've considered**
Currently I'm having something like this in the wrapping component:

```
fields: {
    first_name: { value: '', error: ""},
    last_name: {value: "", error: ""}
}
```

and

```
<q-input v-model="first_name" label="First Name" :error="!!fields.first_name.error" :error-message="fields.first_name.error"/>
```

and I think it is ugly

**Comment by pdanpdan** [comment]
Hello
What you are proposing is to directly tie an independent component (the form element) to a parent element (the form) for no reason. This is against all Vue philosophy.
Sorry.

**Comment by aleksander237** [comment]
Well I disagree it is a perfect example for usage of the provide / inject concept. The child is not "tie" to the parent. It can be still used independently. The error bag could be (and should be) optonal. The fields are send to the server as a part of the request which is represented by a form (I believe this the whole point of the form - to "gather" together input values). How can we say that input is independend component. True, maybe it is implemented that way in Quasar but conceptually input is very dependant. You make decision on how to send data and where to send data on the form level. Please give some more thoughts to that.

**Comment by rstoenescu** [comment]
The provide / inject feature is not free. It comes with a runtime cost and we're not willing to "punish" the most use-cases where this would not be used (but still computed). Sorry.

**Comment by anardil** [comment]
Hello,
I agree with @aleksander237. 
I want to integrate server side validation and I have a headache. Why is there no simple solution to deal with errors in a global way? I have to put error for each input, it's overkill !! Most use qform with API validation. 
Thanks.

**Comment by stalniy** [comment]
server side validation is very common, so I as well don't understand why is so common case is not covered by UI frameworks... Very strange

**Comment by stalniy** [comment]
For those who are looking for a solution, I found a good compromise. We can think about server side validaiton as about any kind of custom validation. For custom validation, we can provide a custom rule function to `q-input`.

So, what I come up with: 

```html
<template>
  <q-form @submit.prevent="submit" ref="form">
     <q-input :rules="[remote.email]" reactive-rules />
  </q-form>
</template>

<script>
export default {
  data: () => ({ remote: {} }),
  methods: {
    async submit() {
      this.remote = {};
      if (!this.$refs.form.validate(true)) {
        return
      }

       const result = await http.post(...);

       if (result.errors) {
          const validators: Record<string, any> = {};
          result.errors.forEach(error => {
            validators[error.path] = () => `errors.${error.code}`;
          });
         this.remote = validators
       }
    }
  }
}


</script>
```

**Comment by hekep** [comment]
@stalniy 

I am new to Quasar and VueJs. 
We too have server side validation, and we are looking for elegant solution.

For example. When we try to post data to  server, it may responds to API Query with json:

```
{
    "status": 400,
    "message": "The Record is not saved",
    "validationErrors": {
        "description": {
            "_empty": "This field cannot be left empty"
            "_min_length": "Minimum length is 10 chars"
        }
    },
}
```
the template has
```
<template>
<q-form>
                   <q-input
                                    v-model="description"
                                    class="col-12"
                                    label="Description"
                                   reactive-rules
                                    :rules="[]"
                                    />
</q-form>
</template>
```

How to  show error messages ( `"This field cannot be left empty"` and   `"Minimum length is 10 chars"`  )  near the `description`  `<q-input>` field ?

**Comment by MilosPaunovic** [comment]
Check these out:

https://quasar.dev/vue-components/form#child-communication
https://quasar.dev/vue-components/input#external-validation

**Comment by hekep** [comment]
> 

Sorry it does not give hint. Yes I can set `bottom-slots` and `<template v-slot:error> ... </template>`  but in our case error messages, which come from the API query result,  are totally dynamic.  

Then again I could do   `<template v-slot:error> {{ descriptionFieldValidationErrorMessages }} </template>`   and set `isValid`  to `false`:

```
<template>
 <q-form @submit="onSubmit" @reset="onReset" class="q-ma-md">
  <div class="q-pa-md" style="max-width: 300px">
    <q-input
      filled
      v-model="description"
      label="Type here"
      bottom-slots
      :error="!descriptionFieldisValid"
      
    >
      <template v-slot:error>
        {{ descriptionFieldValidationErrorMessages }} 
      </template>
    </q-input>
  </div>

<q-btn label="Submit" type="submit" color="dark" />

 </q-form>
</template>
<script>

import { ref } from 'vue'
import { onMounted } from "vue";
import { api } from "boot/axios";

export default {
  setup () {
    const description= ref('')
    const  descriptionFieldValidationErrorMessages = ref('');
    const descriptionFieldisValid  = ref(true);

    return {
     description,
     descriptionFieldValidationErrorMessages ,
     descriptionFieldisValid ,
           onSubmit() {
  
              var postingDataFields = {
	                "description" : description.value,
                    };
api.post("api_data_editing_url/", postingDataFields )
	.then((res) => {
	////////// nicely saved
	})
	.catch((e) => {
	// API responded with 400 and error 
		descriptionFieldisValid.value = false;
		descriptionFieldValidationErrorMessages.value  = e.data.validationErrors.description._empty
	});
            },
    }
  }
}
</script>
```
would this work ?

**Comment by yusufkandemir** [comment]
@hekep you were on type right path. You can use `Object.values()` on `validationErrors.description` so you can get an array of all error messages, then loop over it to display them.

```html
<template>
  <q-form @submit="onSubmit" @reset="onReset" class="q-ma-md">
    <div class="q-pa-md" style="max-width: 300px">
      <q-input
        v-model="description"
        filled
        label="Type here"
        bottom-slots
        :error="!descriptionFieldisValid"
      >
        <template #error>
          <div v-for="message in errorMessages">
            {{ message }}
          </div>
        </template>
      </q-input>
    </div>

    <q-btn label="Submit" type="submit" color="dark" />
  </q-form>
</template>

<script setup>
import { ref } from 'vue'
import { api } from 'boot/axios';

const description = ref('');
const descriptionIsValid = ref(true);
const descriptionErrors = ref([]);

async function onSubmit() {
  const postingDataFields = {
    description: description.value,
  };

  try {
    await api.post("api_data_editing_url/", postingDataFields);
  } catch(error) {
    if (error.response) {
      const { data: { validationErrors } } = error.response;

      descriptionErrors.value = Object.values(validationErrors.description);
    } else {
      // Other kinds of errors (network errors and such)
      console.error(error);
    }
  }
}
</script>
```

**Comment by hekep** [comment]
thanks!
You wrote:
```
<template #error>
          <div v-for="message in errorMessages">
            {{ message }}
          </div>
        </template>
```
Should it be 
```
<template #error>
          <div v-for="message in descriptionErrors">
            {{ message }}
          </div>
        </template>
```
So will  it does create `<div>` per each error?

**Comment by hekep** [comment]
thanks @yusufkandemir !

I ended up with this error template:

```
<template v-slot:error>
    <ul>
        <li v-for="message in descriptionFieldValidationErrors" :key="message" >
              {{ message }} 
        </li>
    </ul>
</template>
``` 
This works for us! :)
