### ISSUE TITLE
Project broken after release upgrade to 1.10.0

### ISSUE THREAD

**Issue by drummerroma** [quasarframework/quasar#6928]
These dependencies were not found:

* core-js/modules/es6.array.find in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/components/tabs/QTabs.js and 3 others
* core-js/modules/es6.array.find-index in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/mixins/panel.js and 1 other
* core-js/modules/es6.array.from in ./node_modules/quasar/src/mixins/file.js
* core-js/modules/es6.array.iterator in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/lang.js and 36 others
* core-js/modules/es6.function.name in ./node_modules/quasar/src/icon-set.js, ./node_modules/quasar/src/install.js and 15 others
* core-js/modules/es6.map in ./node_modules/quasar/src/utils/is.js
* core-js/modules/es6.number.constructor in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/components/btn/QBtn.js and 23 others
* core-js/modules/es6.number.is-integer in ./node_modules/quasar/dist/quasar.ie.polyfills.js
* core-js/modules/es6.object.assign in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/ssr-update.js and 18 others
* core-js/modules/es6.object.freeze in ./node_modules/quasar/src/install.js
* core-js/modules/es6.object.keys in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/lang.js and 35 others
* core-js/modules/es6.object.to-string in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/ssr-update.js and 44 others
* core-js/modules/es6.promise in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/mixins/validate.js
* core-js/modules/es6.regexp.constructor in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/mixins/mask.js and 3 others
* core-js/modules/es6.regexp.flags in ./node_modules/quasar/src/utils/is.js
* core-js/modules/es6.regexp.match in ./node_modules/quasar/src/utils/date.js, ./node_modules/babel-loader/lib??ref--1-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/components/BigMap.vue?vue&type=script&lang=js&
* core-js/modules/es6.regexp.replace in ./.quasar/client-entry.js, ./node_modules/quasar/dist/quasar.ie.polyfills.js and 12 others
* core-js/modules/es6.regexp.split in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/lang/it.js and 8 others
* core-js/modules/es6.regexp.to-string in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/utils/web-storage.js and 7 others
* core-js/modules/es6.set in ./node_modules/quasar/src/utils/is.js
* core-js/modules/es6.string.anchor in ./node_modules/quasar/src/components/tooltip/QTooltip.js
* core-js/modules/es6.string.ends-with in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/mixins/file.js
* core-js/modules/es6.string.fixed in ./node_modules/quasar/src/components/drawer/QDrawer.js, ./node_modules/quasar/src/components/footer/QFooter.js and 1 other
* core-js/modules/es6.string.includes in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/ssr-update.js and 18 others
* core-js/modules/es6.string.iterator in ./node_modules/quasar/src/mixins/file.js, ./node_modules/quasar/src/mixins/validate.js and 1 other
* core-js/modules/es6.string.starts-with in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/components/icon/QIcon.js and 1 other
* core-js/modules/es6.symbol in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/components/btn/QBtn.js and 25 others
* core-js/modules/es6.typed.uint8-array in ./node_modules/quasar/src/utils/uid.js
* core-js/modules/es6.typed.uint8-clamped-array in ./node_modules/quasar/dist/quasar.ie.polyfills.js
* core-js/modules/es7.array.includes in ./node_modules/quasar/dist/quasar.ie.polyfills.js, ./node_modules/quasar/src/install.js and 19 others
* core-js/modules/es7.object.get-own-property-descriptors in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/components/btn/QBtn.js and 25 others
* core-js/modules/es7.promise.finally in ./node_modules/quasar/dist/quasar.ie.polyfills.js
* core-js/modules/web.dom.iterable in ./node_modules/quasar/src/lang.js, ./node_modules/quasar/src/ssr-update.js and 36 others

To install them, you can run: npm install --save core-js/modules/es6.array.find core-js/modules/es6.array.find-index core-js/modules/es6.array.from core-js/modules/es6.array.iterator core-js/modules/es6.function.name core-js/modules/es6.map core-js/modules/es6.number.constructor core-js/modules/es6.number.is-integer core-js/modules/es6.object.assign core-js/modules/es6.object.freeze core-js/modules/es6.object.keys core-js/modules/es6.object.to-string core-js/modules/es6.promise core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.flags core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.set core-js/modules/es6.string.anchor core-js/modules/es6.string.ends-with core-js/modules/es6.string.fixed core-js/modules/es6.string.includes core-js/modules/es6.string.iterator core-js/modules/es6.string.starts-with core-js/modules/es6.symbol core-js/modules/es6.typed.uint8-array core-js/modules/es6.typed.uint8-clamped-array core-js/modules/es7.array.includes core-js/modules/es7.object.get-own-property-descriptors core-js/modules/es7.promise.finally core-js/modules/web.dom.iterable

**Comment by pdanpdan** [comment]
- remove icon genie extension if installed
- `rm -rf node_modules yarn.lock package-lock.json`
- `yarn`

check duplicates here:
- https://github.com/quasarframework/quasar/issues/6458
- https://github.com/quasarframework/quasar/issues/6741
