### ISSUE TITLE
CSP security header support in Meta plugin for SSR builds

### ISSUE THREAD

**Issue by hecsalazarf** [quasarframework/quasar#6929]
**Is your feature request related to a problem? Please describe.**
The Meta plugin initial state is inlined as `window.__Q_META__`, causing an error when the Content Security Policy header is not enabled for `'unsafe-inline'` scripts. Therefore, apps cannot take advantage of this added layer of security.

**Describe the solution you'd like**
As of Vue 2.6.0+, the render template automatically injects the nonce if `context.nonce` is present. In fact, by setting the fore mentioned property in the Quasar `ssrContext` within a boot function, Vue adds such attribute in the initial Vuex state. Same approach could be taken for the Meta initial script.

**Describe alternatives you've considered**
The easiest (not desirable) one would be to disable CSP; however, Vue already conforms to it. In terms of security and following Quasar guidelines, we must not forget to use restrictive headers.

**Additional context**
[Vue render template options](https://ssr.vuejs.org/api/#template)

**Comment by rstoenescu** [comment]
Fair point. Will be available, but you will need "quasar" v1.10.1 AND "@quasar/app" v1.8.4.

**Comment by hecsalazarf** [comment]
Thanks!
