### ISSUE TITLE
Documentation error, or perhaps even helper class naming issue

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#693]
I was going to propose a change to the helper class page [here](http://beta.quasar-framework.org/components/visibility.html), as I'm presuming that the `invisible` class actually sets `visibility: hidden` rather than `visibility: none` (see CSS spec). This leads to the rather undesirable mapping:

       hidden → display: none
    invisible → visibility: hidden

Lots of possible confusion with `hidden` being used twice, and people familiar with CSS might assume one over the other. But of course there's probably lots of Q code already written which would break if `hidden` suddenly meant `visibility: hidden`.

Other than marking the `hidden` class as deprecated and replacing it with a new `no-display` class or something, I don't have a good solution for this. But maybe it just needs extra highlighting in the docs?

**Comment by rstoenescu** [comment]
@dsl101 hi,

In Quasar, "hidden" is meant to not display the element + element won't occupy real estate space on screen. "invisible" it's just meant to not be displayed, but the element does occupy real estate space on screen.
CSS "visibility" can take the following values: visible|hidden|collapse|initial|inherit, but never "none".

I don't see why these helper classes should be changed. If the docs need more emphasis on this, then can you help out, please?

**Comment by dsl101** [comment]
The Quasar docs currently say "invisible: Set visibility to none", which as you pointed out isn't a valid value. That was the intent of my original post. But then I got to wondering about whether `hidden` meaning one thing in CSS (not shown but taking space) and another in Quasar (not shown and not taking space) was really the best approach...

I'll make a PR to clarify in the docs if you're not keen to change the classes.

**Comment by rstoenescu** [comment]
Thank you for the PR!

**Comment by dsl101** [comment]
Did it come through? I wasn't sure if I'd made it all the way to the end :).

**Comment by rstoenescu** [comment]
Yep. All good. Thank you for taking time for the PR!
