### ISSUE TITLE
QCircularProgress: Make the transition delay customizable

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#6930]
**Is your feature request related to a problem? Please describe.**
The transition delay is hardcoded to 0.6s https://github.com/quasarframework/quasar/blob/dev/ui/src/components/circular-progress/QCircularProgress.js#L69

**Describe the solution you'd like**
Make this customizable

**Describe alternatives you've considered**
Setting `instantFeedback` to true does the job for me, although it is not a public property. https://github.com/quasarframework/quasar/blob/dev/ui/src/components/circular-progress/QCircularProgress.js#L55

**Additional context**
The value is binded to an input type number. When I increase that value by long pressing the input arrows, it introduces a significant lag.

Example: https://jsfiddle.net/byzpte9m/

**Comment by rstoenescu** [comment]
You can safely use the `instant-feedback` prop. I'll make it public instead of private in the next Quasar version.

**Comment by philfontaine** [comment]
Great, thanks.

**Comment by philfontaine** [comment]
I closed it, did not know if you were planning to make it customizable anyway.
