### ISSUE TITLE
request deprecated warning

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#6934]
Hi

When building an electron app or running npm on my project, I get the following:

> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm list shows quasar app is using it

> +-- @quasar/app@1.8.3
> | -- node-sass@4.14.0
> |   +-- node-gyp@3.8.0
> |   | -- request@2.88.2  deduped
> |   -- request@2.88.2
> 

I guess this should be changed to something else?
Thanks

**Comment by pdanpdan** [comment]
Hello. Please open a bug report for this on `node-sass` repo. Thank you.
