### ISSUE TITLE
[docs] Add example of using a Service Worker in SPA

### ISSUE THREAD

**Issue by jaybo** [quasarframework/quasar#6935]
While there seems to be lots of information on creating a service worker in a PWA, there's none on how to add a simple service worker to an SPA.

Given a service worker:

    // src/modules/sw.js
    importScripts('/js/moment.js'); 
    console.log(`From worker: worker started at ${moment().format("HH:mm:ss")}`);

And a module trying to use sw.js:

    // src/modules/foo.js
    let worker = new Worker("/modules/sw.js");

Results in the error:

    Failed to load resource: the server responded with a status of 404 (Not Found) 
    https://localhost:44444/modules/sw.js

Presumably ```quasar.config.js``` needs to be augmented to specify ```sw.js``` is a service worker, but how exactly is this done?

I would suggest adding a page to the SPA section of the docs or else just appending this information to:

https://quasar.dev/quasar-cli/developing-spa/build-commands

**Comment by pdanpdan** [comment]
service workers load files over http(s) so it's only normal to put your files somewhere where you can access them - try to put it in statics

**Comment by rstoenescu** [comment]
Are you referring to [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) or [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker)? Cause you seem to be using a Web Worker and putting it into statics like Dan indicated above is the way to go.

**Comment by tachibana-shin** [comment]
> Are you referring to [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) or [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker)? Cause you seem to be using a Web Worker and putting it into statics like Dan indicated above is the way to go.

hi i am having this problem i want to use service worker(pwa) on SPA mode
