### ISSUE TITLE
BEX: BG script can't receive comms from Content Script when proxy for DOM hooks.

### ISSUE THREAD

**Issue by webnoob** [quasarframework/quasar#6937]
```
// Only mount the background hooks once; on app initialization.
  // if (port.name === 'app') {
  attachBackgroundHooks(bridge, connections)
  // }
```

Port name check needs reworking.

**Comment by webnoob** [comment]
Need to do something like:

```
if (bridgeAttached === false) {
    attachBackgroundHooks(bridge, connections)
    bridgeAttached = true
  }
```
bridgeAttached to be a global var.

**Comment by webnoob** [comment]
connection needs a bridge prop
assign the bridge to that prop
on disconnect, call `thisConnection.bridge.removeAllListeners()`

**Comment by rstoenescu** [comment]
Any progress on this?

**Comment by webnoob** [comment]
Forgot I opened this: Fixed via - https://github.com/quasarframework/quasar/commit/3c482d323aa3f5f079ebf438f260c0bc8dbf98de.
The other notes in this issue were red herring's and the clean up is actually happening.
