### ISSUE TITLE
icongenies new trim feature removes part of the icon

### ISSUE THREAD

**Issue by NicolasReibnitz** [quasarframework/quasar#6940]
**Describe the bug**
When using the Icon Genie v2.1.0 CLI with default values, the black outline of the input file gets cut off from all sides.

**Codepen/jsFiddle/Codesandbox (required)**
Not applicable.

**To Reproduce**
`icongenie g -i ./app-icon.png`

**Expected behavior**
Remove the transparent part of the image and leave the blackish outline untouched.
You also might want to add an option for disabling trimming altogether.

**Screenshots**
![icon-example](https://user-images.githubusercontent.com/20308845/80909660-04e33a80-8cf8-11ea-8e01-b062c79e1d00.png)
Left side: input
Right side: generated output

**Platform (please complete the following information):**
OS: macOS v10.14.6
Node: v12.16.2
NPM: v6.14.4
Yarn: v1.22.4
Browsers: n/a
iOS: n/a
Android: n/a
Electron: v5.0.13

**Additional context**
Note: the outline isn't even pure black. And padding just adds padding after the trimming. So it didn't help.

Other than that, awesome stuff, you guys! ❤️

Original input file:
![app-icon](https://user-images.githubusercontent.com/20308845/80909766-cac66880-8cf8-11ea-9a63-060cf1a8b05c.png)

**Comment by NicolasReibnitz** [comment]
P.S. Changing the outline color does help. At least for testing purposes. 😉

Output:
![icon](https://user-images.githubusercontent.com/20308845/80909965-6d331b80-8cfa-11ea-815e-599f5eb27c0d.png)

**Comment by dariosalvi78** [comment]
I have the same issue. Can't really use this tool if trims my icon!

**Comment by rstoenescu** [comment]
There will be a "--skip-trim" param in "@quasar/icongenie" v2.2.0

**Comment by rstoenescu** [comment]
IconGenie v2.2 released.

**Comment by NicolasReibnitz** [comment]
Just to confirm, "--skip-trim" works perfectly. Thank you very much for that great support!
