### ISSUE TITLE
Unnecessary re-renders Q-components

### ISSUE THREAD

**Issue by alexdee2007** [quasarframework/quasar#6941]
**Describe the bug**
Useless re-renders of components on parent update

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/alexdee2007/pen/LYpObve

**To Reproduce**
1. Open console
2. Enter some text into field  "Text1" -> Vue re-renders all four q-inputs as well as q-btn

**Expected behavior**
In console:

> "updated" "Text1"

**What is actually happening?**
In console:

> "updated" "Text1"
> "updated" "Text2"
> "updated" "Text3"
> "updated" "Text4"
> "updated" "Button"

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
Using $listeners and/or $attrs in component's render function causes the component to be rendered whenever its parent is updated even though his props hasn't changed.
It causes high performance impact when using e.g. form with a lot of q-inputs.

Related to https://github.com/vuejs/vue/issues/7257 and https://github.com/vuejs/vue/issues/10115

There are workarounds, e.g. [vuetify](https://github.com/vuetifyjs/vuetify/pull/8822) or [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue/pull/4825)

**Comment by rstoenescu** [comment]
Hi, we actually noticed this too and were preparing a workaround.

**Comment by rstoenescu** [comment]
Perf improvements will be available in "quasar" v1.10.1.
