### ISSUE TITLE
Tick Strategy  leaf does not work when  lazy: true

### ISSUE THREAD

**Issue by MarinaUI** [quasarframework/quasar#6943]
When` lazy is true`, tick-strategy is 'leaf' the checkboxes are not displayed.
After expanding to leaf, the checkboxes will appear.

Expected Behavior:
The checkboxes should be displayed when tick-strategy is 'leaf'. 
Do you have some workaround to fix this bug?

Here is some part of code

https://codepen.io/_marina_/pen/PoPOejb

Noticed that Parent Node is lazy: true and it has not checkbox near.

**Comment by pdanpdan** [comment]
Hello.

Lazy means that the list of children (nodes) will be loaded on expand, so there is not point in showing a checkbox that would do nothing.

https://codepen.io/pdanpdan/pen/bGVarPY?editors=1010
