### ISSUE TITLE
Configuring the language pack in SSR sets a wrong HTML 'lang' attribute 

### ISSUE THREAD

**Issue by hecsalazarf** [quasarframework/quasar#6944]
**Describe the bug**
The HTML `lang` attribute does not change correctly when configuring the language pack in SSR mode. This issue was previously described in #6704, but I think it was not discussed deeper and consequently was closed.

It has nothing to do with Vue I18n instantiation, but how Quasar sets the new language. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/quasar-issue--93vw1?file=/src/boot/locale.js

**To Reproduce**
A boot file has been created with a very naive way to change the locale. The important part is the server side; client code is left for consistency only as it works as expected.

1. Go to path `/`. The default language pack (en-us)  is set. Everything OK.
```html
<html lang=en-us dir=ltr>
``` 

2. Then go to `/fr`. In the boot file, this route triggers the language pack configuration. We can either _right click->View page source_ or use Postman, for example, to see that the generated markup did not change.
```html
<html lang=en-us dir=ltr>
``` 

3. Refresh the same route. There we have it; changed after the first time.
```html
<html lang=fr dir=ltr>
```

4. Go back to `/` and refresh. We should see `lang=en-us` again, but we receive `lang=fr`; a polluted response with the preceding request.

5. If we restart the server, and enter to `/` one more time, `en-us` locale is back.
 
**Expected behavior**
A homogeneous `lang` attribute when setting the language pack. 

**Platform (please complete the following information):**
OS: Linux 4.15.0
Node: 12.13.0
NPM: 6.14.0
Browsers: Chromium 81.0.4044.129

**Additional context**
SSR mode.

**Comment by rstoenescu** [comment]
Hi,

The usage is incorrect.

Remember that the server part keeps on running and so when you change a singleton it'll change it for all of the clients. This is what you are doing when calling Quasar.lang.set() in the boot file. The language is set to en-us until the first client requests /fr page which sets the new language on the Quasar singleton. The concept is explained here in more details: https://quasar.dev/quasar-cli/developing-ssr/writing-universal-code#Avoid-Stateful-Singletons

What you should do to avoid this is rather hook your logic into /src/App.vue (recommending "created()" method) where you can access the client's own instance (this.$q.lang.set etc etc)

**Comment by hecsalazarf** [comment]
Fair enough. Those comments should be documeted as well, just as the cookies section does.

Thanks.
