### ISSUE TITLE
QButton click event not working after set :loading = false

### ISSUE THREAD

**Issue by CamiloEspinoza** [quasarframework/quasar#6945]
**Describe the bug**
On QButton when you set :loading = true and then :loading = false the button get inactive, @click event wont trigger anymore.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/CamiloEspinoza/pen/PoPOdrJ

**To Reproduce**
1. Go to the Codepen
2. Click on the button

**Expected behavior**
There is a counter of click events, you should expect the number to increment but the @click event won't work anymore.

**Platform (please complete the following information):**
OS: MacOs 10.14.6
Node: 12.16.1
NPM: 6.14.1
Yarn: 1.22.4
Browsers: Chrome, Safari
iOS: 13.3.1
Android:
Electron:

**Comment by DarkLite1** [comment]
Same here, been looking at this for a while now but the problem only appeared after upgrading to the latest Quasar version. And as you say it is totally related to the `loading` property being set. When this is taken away it works fine.

**Comment by rstoenescu** [comment]
Fix will be available shortly in "quasar" v1.10.4.
