### ISSUE TITLE
[v1.10.3] - Qbtn @click only fires once

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#6947]
**Describe the bug**
Any q-btn that has an @click event tied to it is only firing the function on the first click.

**To Reproduce**
1. Create a q-btn
2. Attach an @click event
3. Click once, function fires, subsequent, not firing

**Expected behavior**
Function tied to event should keep firing.

**Platform (please complete the following information):**
OS: Windows 10
Node: 10x
NPM: 6x
Yarn:
Browsers: Chrome 81.0.4044.129
iOS:
Android:
Electron:

**Additional context**
This is a pretty major bug, any chance it can be hot fixed?

**Comment by pdanpdan** [comment]
Yes, it was just fixed before you posted :)

**Comment by rstoenescu** [comment]
Upgrade to "quasar" v1.10.4.

**Comment by sn0rcha** [comment]
Many thanks guys :)
