### ISSUE TITLE
QTable, allow `sort-method` to be `null `

### ISSUE THREAD

**Issue by Chettbi** [quasarframework/quasar#6948]
Hi there :)

**Is your feature request related to a problem? Please describe.**

Sometime I need to dynamically display QTable and when I describe my QTable I don't know if I have a custom sort method defined for my table.

If I set `sort-method` attribute with a null value, I got the error `TypeError: "this.sortMethod is not a function"`. (And an empty function just do nothing of course)

**Describe the solution you'd like**

It should be nice to be able to set a `null` value to `sort-method` attribute, and that the sort has his default behavior.

**Describe alternatives you've considered**

I find a workaround with a computed and dynamic attribute name, but I think it's not a very good practice.

Thanks in advance (and sorry for my poor english) :)

**Comment by pdanpdan** [comment]
Set it to undefined (void 0)

**Comment by Chettbi** [comment]
Oh thanks, I didn't try it, it's works :)

Sorry for the inconvenience.
