### ISSUE TITLE
[Request] method for responsiveness based on screen sizes, not just platforms

### ISSUE THREAD

**Issue by genox** [quasarframework/quasar#695]
Could be based on bootstrap style breakpoints.

**Comment by rstoenescu** [comment]
Hi.

What exactly do you need? Be more specific.
If you need CSS helper classes based on screen size they are already in. Check Flex CSS and also the other helper classes.
If you need a JS method, then use an observable Quasar component. Check Element Resize Observable or Window Resize Observable.

Please reopen with a detailed case if all these don't suffice.
Thanks!
