### ISSUE TITLE
Qtree not expendable after node reset to lazy and empty children

### ISSUE THREAD

**Issue by pintaf** [quasarframework/quasar#6950]
**Describe the bug**
A Qtree completely lazy (to make it simple).
Starting tree: Two nodes, with empty children and lazy.
Try expending them, and then reset node 1 to lazy, and children:[]
It is then not possible anymore to click the arrow to expand the tree,

**Codepen**
https://codepen.io/pintaf/pen/PoPJMyJ

**To Reproduce**
1. Open node 1 and (optional) some of it's children
2. Click on 'Collapse Node1' Button
4. See arrow disapearing

**Expected behavior**
Since the tree is reset to it's original state, original behaviour should be observed (arrows with lazy loading)

**Platform (please complete the following information):**
OS: Linux
Node: 12.16.1
NPM: 6.14.4
Browsers: Firefox
Quasar: v1.9.15
@quasar/app: v1.7.1

**Additional context**
The reason I want to achieve the above:
I have a Huge tree (24 000 elements), with 98 on 1st level.
All the rest is lazy loaded.
Thanks to some custom code I was able to enable the display of all children of a 1st parent in one click.
I want to be able to collapse a node by removing it's elements. In my app it is unlikely that once collapsed, someone will go there again, so I want to take advantage of that to clear DOM.
Becuase otherwise with 24'000 elements it quickly becomes a nightmare

**Comment by pdanpdan** [comment]
It looks like you need a way to unload a branch.

**Comment by pintaf** [comment]
Well, that is exactly what I needed.
The trick is accessing the lazy property of the tree, I didn't know about it.

Your code for auto-unloading on collapse is neat, it does have a little issue though:
The `expended` array keep nodes that were unloaded.

Example:
Expand up to 1.1.1 then collapse node 1. If you print `expanded` you will see it keep references to 1.1 and 1.1.1  
It does not have any consequences on usability though.

Thanks for your **quick** help, my RAM and I will have more pleasant days.
I will close that issue in few hours in case someone has something to add, but I recommand you to post it in forum, as I think it might be useful to others.

**Comment by pdanpdan** [comment]
Closing this to track it in https://github.com/quasarframework/quasar/issues/6959

**Comment by iljaverba00** [comment]
This solution doesn't work. There is no lazy property in the quasar project in q-tree. 
https://github.com/quasarframework/quasar/commit/300fb92fc396de4ab6f05ea78975a0371291f1b7#diff-387b9b62424fed6c9add037b377c07e02f3deca0d50edeb2a415defd12f0e9bb

**Comment by lx66629** [comment]
This solution doesn't work. There is no lazy property in the quasar project in q-tree.
https://github.com/quasarframework/quasar/commit/300fb92fc396de4ab6f05ea78975a0371291f1b7#diff-387b9b62424fed6c9add037b377c07e02f3deca0d50edeb2a415defd12f0e9bb

**Comment by pintaf** [comment]
Well. I've been using this solution since then and no regressions.
You should share a jsfiddle or something to demonstrate the issue
