### ISSUE TITLE
Validation is doing opposite things

### ISSUE THREAD

**Issue by OtabekSadiridinov** [quasarframework/quasar#6954]
# I am going to say some bugs on Quasar.
https://codesandbox.io/s/quasarerror-re26g
1.Go with this address of Codesandbox.
2. Write _123456_ to the first input.
3. Write _123456_ to the second input and press submit button.
4. Get error of the **_passwords are'nt the same_**.
5. Look code.
6. See it was written if the passwords are **NOT THE SAME**
7. But working when they are **THE SAME**

Everything is working incorrectly.

**Comment by OtabekSadiridinov** [comment]
I think this should be fixed.

**Comment by rstoenescu** [comment]
It should be `val => val !== password || 'Both ....` as in "if val === password then return true, so everything is fine, otherwise return the error message.

**Comment by OtabekSadiridinov** [comment]
Ok. I understand but before I was thinking.
If val !== password do something means: _If value is not equal to password show the message_

**Comment by OtabekSadiridinov** [comment]
Sorry for misunderstanding.
