### ISSUE TITLE
[Feature]: QFile append on multiple

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#6955]
**Is your feature request related to a problem? Please describe.**
Users that have the ability to upload multiple files, may have those files in different folders. The way that QFile works now, is the FileList is always cleared when anything is added to to it. Users have to accumulate their files into a single location, then perform the drag-and-drop with all wanted files.

**Describe the solution you'd like**
A new property `append` that only works with `multiple` that allows new files to be appended.

**Describe alternatives you've considered**
There are none

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/jObYWXx?editors=1010

**Comment by hawkeye64** [comment]
hey @pdanpdan Thanks a lot for that!

**Comment by hawkeye64** [comment]
@pdanpdan Try deleting a chip and see what happens. Not good.

**Comment by pdanpdan** [comment]
If you need remove than it's more to check: https://codepen.io/pdanpdan/pen/jObYWXx?editors=1010

**Comment by pdanpdan** [comment]
Adding it to https://github.com/quasarframework/quasar/issues/6961 - to think of it.

**Comment by hawkeye64** [comment]
The codepen is still no good. If you add prop `max-files` you can exceed it. This is not the right place to be doing this kind of logic. In the end, there will be a LOT of duplicated code.
A big problem with the above, is that the user checks come after the other checks, so they would have to be done all over again in devland.

Check out the code I posted here. It's small and gets the job done: https://github.com/quasarframework/quasar/issues/6961#issuecomment-624331133

**Comment by pdanpdan** [comment]
Regarding de-duplication of files - this cannot be done because each file selected creates a new object and the only way to check for duplicates would be a combination of name, size and a hash function over the content - which is too much.
So an append option would have the problem of possible duplicates.

**Comment by hawkeye64** [comment]
Regards de-duping, it'd be nice if the File object would contain a hash of the blob. They really messed this up. I already generate the blobs, so I can check for dupes, if needed. Messy, but can be done and prone to memory leaks if user doesn't release the blob data.Maybe quasar can do it, but only with flag because of performance reasons.

**Comment by pdanpdan** [comment]
They didn't mess it - it's intended for two reasons:
- performance
- security

**Comment by hawkeye64** [comment]
@pdanpdan yes, obviously, something would have been better than nothing. They could have even had a "duplicate: true/false" field to indicate it's a dupe.

Anyway, regardless of de-duping, the main point of this issue is to have better multiple-file management (ie: ability to append instead of replace).

**Comment by rstoenescu** [comment]
New Boolean prop (`append`) will be available in "quasar" v1.11.3

**Comment by hawkeye64** [comment]
@rstoenescu You are my hero! :heart: you man!

**Comment by raudipra** [comment]
Hi all, that prop append was a painkiller! However I found that it doesn't work together with @input event handler, meaning the append feature will be overwritten by whatever method handler on @input property. How do I get both of these feature to work without getting overwritten to one another?

My case is I want to use the append feature while also keep track and run a method whenever new files being appended

Thank you
