### ISSUE TITLE
QPopupProxy events broken

### ISSUE THREAD

**Issue by nkofl** [quasarframework/quasar#6956]
**Describe the bug**
QPopupProxy no longer forwards underlying events from QMenu or QDialog due to a code change that references a property that does not exist (this.onEvents). It looks like this was placed in watchers on accident.

See:
https://github.com/quasarframework/quasar/commit/a6940aeab2c3f558c0451a92e10ad84fc182248a#diff-c97fcc285b91d9e6431e683538ff3aebR112

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/0ormhf7s/

**To Reproduce**
1. Try to hook up a QPopupProxy event
2. Do something that would fire the event
3. See that nothing happens. The underlying QMenu / QDialog event fires, but not QPopupProxy's event.

**Expected behavior**
Events such as show, hide, before-show, before-hide should fire

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: any
Node: any
NPM: any
Yarn: any
Browsers: any
iOS: any
Android: any
Electron: any

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thanks for catching this. Fix will be available in "quasar" v1.10.5 shortly.
