### ISSUE TITLE
Multiple entry points?

### ISSUE THREAD

**Issue by rmaes4** [quasarframework/quasar#6958]
I am trying to create an SSR website and a mobile app. I am not aiming for 1:1 feature parity with the mobile app. I just want it to do a small subset of things compared to the website. I do want to share code between them however, hence not creating 2 separate projects. 

So my mobile app is using the capacitor/ionic Bluetooth Low Energy API. This is all working fine. I even managed to create separate routes for the mobile vs web applications. The problem is that the SSR web app is now complaining that it cannot resolve the import for the BLE package inside src-capacitor. I don't want bluetooth for the website, I don't need it. It won't even work. I've been playing around with the Webpack config options and I cannot figure this out. How can I have routes/packages A for capacitor and routes/packages B for the SSR while still having components/vuex etc. C for both. Please advise. Thank you.

**Comment by pdanpdan** [comment]
Hello. For help requests please head to the discord channel or the forum.
