### ISSUE TITLE
[Request] Toggle ripple off for a component (q-btn), and/or fix ripple influence on dom

### ISSUE THREAD

**Issue by spectrolite** [quasarframework/quasar#696]
### Software version

Quasar: 0.14
OS: MacOS Sierra
Browsers: Chrome latest

WORKS CORRECTLY ON: Firefox dev latest

Any other software related to your bug: Google Maps, but it's just what helped uncover the bug, not part of the cause imho.

Copied from http://forum.quasar-framework.org/topic/573/change-ripple-color/
Btw is there a way to disable the ripple entirely on a q-btn ?
I ask this because it seems the ripple is somehow affecting its environment: I have a Modal with layout and a few buttons in the footer toolbar, and whenever I click one of those buttons, the content of the modal gets a scrollbar for a fraction of a second. And since it contains a full width google map, it reacts to the resize and I end up with the map having a grey border on right, the size of what used to be a scrollbar. I can refresh the map somehow, but there’s still a flicker visible. Maybe fixing Ripple would be a better idea, but I could not find where the problem comes from. In the meantime, it would be great if I could disable ripple locally (I really dont wanna use plain old buttons, q-btn is too good of a component).

### What were you expecting?
the ripple to have no influence outside its container.

**Comment by rstoenescu** [comment]
It doesn't influences the outside container by design. Need to see the specific context in which you are experiencing issues, but when I come back from vacation.

**Comment by spectrolite** [comment]
anyone else needs to disable ripple globally or on a single component, for any reason ?

**Comment by StrikerUnit** [comment]
I'm not sure, but it would be nice if we can have more control over the Ripple such as globally disable, example use case would be for the sake of design reason.

**Comment by aprilpnguyen** [comment]
I find ripple on input fields extremely annoying, especially when I try to select the text on the inverted inputs. It would be nice to be able to disable this at least on the input fields.

**Comment by Frondor** [comment]
Ripple should be optional in most component. Besides its GPU hunger, sometimes we don't really need it, simple because it doesn't even show up like when implemented on `q-side-link`s.

**Comment by mesqueeb** [comment]
I would also like to disable ripple on QBtn.

**Comment by NoRabbit** [comment]
+1 for a way to disable ripple on any component
or at least input at the moment

**Comment by rstoenescu** [comment]
Available in future v0.15 through "no-ripple" boolean prop.
