### ISSUE TITLE
Unable to have a clickable button inside QTooltip

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#6965]
Hello!

In my scenario I'd love to manually control the visibility of the tooltip (`no-parent-event` prop). However,  the button inside the tooltip is not clickable, due to `pointer-events: none !important;`

Expected: buttons should be clickable inside the tooltip.

Example: https://codepen.io/jean-moldovan/pen/rNOJaEQ?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Ftooltip

**Comment by rstoenescu** [comment]
Hi. QTooltip is not designed for what you want. Use QMenu instead.
