### ISSUE TITLE
Add an option to make QSelect's dropdown "drop up" instead

### ISSUE THREAD

**Issue by x-ji** [quasarframework/quasar#6967]
**Is your feature request related to a problem? Please describe.**
See https://github.com/quasarframework/quasar/issues/6962

When the optional element is below the QSelect, the QSelect wouldn't move after being selected, and the problem linked above would be solved. However, the optional element would be hidden, since QSelect always opens the dropdown in a downwards direction.

This could also be helpful in other use cases where a "drop up" is preferred.

**Describe the solution you'd like**
Instead of the dropdown dropping "down", it drops up instead. See for example [this SO question](https://stackoverflow.com/questions/7814186/drop-down-menu-that-opens-up-upward-with-pure-css)

**Describe alternatives you've considered**
Modify my UI flow so that the drop up is not needed.

**Additional context**

**Comment by pdanpdan** [comment]
Hello.

You can use `menu-anchor` and `menu-self` to set the position for the menu like here: https://codepen.io/pdanpdan/pen/rNOJONO?editors=1010

But in order for the menu to open up you must have enough space there (or more than on the bottom)

**Comment by x-ji** [comment]
Thanks for the quick help 👍

**Comment by EsraaRMashaal** [comment]
thanks this helps me
