### ISSUE TITLE
Creating a new TypeScript project complains about module not found

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#6968]
**Describe the bug**
When running `quasar create <name>` and selecting the TypeScript route a project is correctly created. However, in the file `Index.vue` the following is visble:

![image](https://user-images.githubusercontent.com/10828570/81160223-15aadf00-8f8a-11ea-85cc-ae2ff33dbaa4.png)

It says it cannot find module 'components/models' although it's clearly there. 

**Additional context**
As suggested on discords by Callo I tried his advice but no luck:

> @DarkLite1 follow `@quasar/app/tsconfig-preset` path and copy the `compilerOptions.path` part into your project `tsconfig` Then restarts VSCode and see if it works

I've also tried all options for TS in the Vetur settings but no luck:

![image](https://user-images.githubusercontent.com/10828570/81160692-ad103200-8f8a-11ea-91d3-706fdbd6452e.png)

**Comment by DarkLite1** [comment]
The issue is withing Vetur as it is not able to traverse vs code multi project folders and find the correct tsconfig.js file. This is not Quasar related and will be closed.

**Comment by rstoenescu** [comment]
Thanks for the followup!

**Comment by jdheeter** [comment]
I'm seeing the same issue. I'm using Volar (Vetur extension is not installed). Is there a solution for this? maybe copy the .tsconfig.js file to a different directory? How do others in the community solve this issue?
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/2530957/160576181-66da895a-6981-4b78-a927-bec68280c803.png">
