### ISSUE TITLE
The Mac Electron app follows the system theme (dark/light) in dev mode but not in prod mode, which seems inconsistent

### ISSUE THREAD

**Issue by x-ji** [quasarframework/quasar#6971]
**Describe the bug**
When I launch a new (default) Quasar app with `quasar dev -m electron`, it follows the MacOS system theme (dark/light), and some texts are not displayed well because the background went dark. However, when I build the app with `quasar build -m electron`, it actually always launches in light mode, which seems inconsistent.

I couldn't find anywhere in the app the setting to force light/dark mode for the app.

I asked the question [in the forum](https://forum.quasar-framework.org/topic/5725/force-the-app-to-always-use-light-theme-in-electron) but received no reply, thus I thought I'd post it here.

**Codepen/jsFiddle/Codesandbox (required)**
Not sure if this helps. I just created a new default Quasar project and ran `quasar dev -m electron`.

**To Reproduce**
0. Set the MacOS system theme to dark.
1. `quasar create test`
2. `cd test`
3. `quasar dev -m electron`: The app launches in dark mode, and some texts blend into the background.
4. `quasar build -m electron` and then double click on the release: The app launches in light mode.

**Expected behavior**
- Both `dev` and `build` produce Electron apps that run under the light mode, or both conform to the system specification.
- The developer knows where to look for/change this setting.

**Screenshots**
Dev (dark):
![Screenshot 2020-05-06 15 35 01](https://user-images.githubusercontent.com/2999209/81183252-389bba00-8faf-11ea-8bf7-1f00adc4b8f9.png)

Prod (light):
![Screenshot 2020-05-06 15 35 21](https://user-images.githubusercontent.com/2999209/81183257-39345080-8faf-11ea-80f2-77cf60d7273d.png)

**Platform (please complete the following information):**
OS: MacOS 10.15.4
Node: v 12.16.2
NPM: 6.14.4
Yarn: 1.22.4
Electron: v8.2.5

**Additional context**

**Comment by x-ji** [comment]
Also I always had to `rm -rf node_modules`, `yarn` and `quasar build -m electron` to make the building process work. Though that might not be related to this issue.

**Comment by rstoenescu** [comment]
This depends entirely on Electron's webview and is out of our reach. It is also probably a bug in Electron which will be fixed in next version(s).

**Comment by x-ji** [comment]
Cool. Just wanted to make sure that it's not a setting in Quasar, but exclusively an Electron issue.
