### ISSUE TITLE
Add pointer (arrow) to Quasar tooltips component QTootip

### ISSUE THREAD

**Issue by MurzNN** [quasarframework/quasar#6975]
Current Quasar tooltips component QTootip miss arrows (pointers), like tooltips in most of other frameworks (even in old-scool Bootstrap!). Here is example:
![image](https://user-images.githubusercontent.com/336662/81277128-a651ef80-905c-11ea-8c44-bd408f054b63.png)

There are previous feature requests about this https://github.com/quasarframework/quasar/issues/2418 https://github.com/quasarframework/quasar/issues/2105 https://github.com/quasarframework/quasar/issues/5338  and even pull request https://github.com/quasarframework/quasar/pull/2419 - but all are too old and already closed.

So I think good idea is open new fresh feature request about this.

**Comment by pdanpdan** [comment]
Hello. I have tried to make some sort of generic arrow that just works TM, but it's not going to work and we don't have the resources to support all the people that would want all kind of shadows/borders/positions/shapes of the arrows.
So please add a class to your tooltip and use something like http://www.cssarrowplease.com/ to make the arrows as you need fit.
