### ISSUE TITLE
Add "superlazy" mode to QInput

### ISSUE THREAD

**Issue by Powersource** [quasarframework/quasar#6977]
**Is your feature request related to a problem? Please describe.**
I want QInput to only run validation when I manually call `validate()`. (for context, I call `validate` when the user clicks "next" in a form. I don't want to alert them before that)

**Describe the solution you'd like**
A prop a bit like `lazy-rules` but that makes the validation not even run on losing focus

**Describe alternatives you've considered**
Just now I tried adding this
```
<q-input
            ...
            ref="qinput"
            lazy-rules
            :rules="[...]"
            @blur="$refs.qinput.resetValidation()"
></q-input>
```
and it seems to work but it's pretty hacky and feels likely to break.

**Comment by webnoob** [comment]
How about - add a data prop: `applyRules: false`, then:
```
:rules="applyRules === true ? [...] : void 0"
```
Then before you call `validate()` set: `this.applyRules = true`

**Comment by rstoenescu** [comment]
I think the way to go is to add one more possible value for lazy-rules. Example: `lazy-rules="ondemand"`

**Comment by webnoob** [comment]
Just to clarify, my idea was instead of `@blur="$refs.qinput.resetValidation()"`.

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.11.0. Like told above, `lazy-rules` will also support the `ondemand` String value for the superlazy behavior.

**Comment by dvbeek** [comment]
Editors (at least IntelliJ) now give a warning 'Wrong attribute value' with the conventional use of 'lazy-rules'.

**Comment by webnoob** [comment]
That'll need reporting to them as they manage that.

**Comment by Tofandel** [comment]
@webnoob Nope they don't, this kind of warnings comes from a type inference usually typescript
