### ISSUE TITLE
QDialog not closing when triggered on focus event

### ISSUE THREAD

**Issue by goldsteinrazvan** [quasarframework/quasar#6979]
**Describe the bug**
If you trigger a QDialog on a focus event (such as focusing on an input), it will not be possible to close it, regardless if you use v-close-popup or set the v-model explicitly to false. 

Code example here: [https://codesandbox.io/s/quasar-sandbox-g3s26?file=/src/pages/Index.vue](https://codesandbox.io/s/quasar-sandbox-g3s26?file=/src/pages/Index.vue)

**To Reproduce**
1. Create an input field and a q-dialog component with a close button.
2. Set the @focus to trigger QDialog (see code example).
3. When the QDialog is open, try closing it.
4. QDialog should not close.

**Comment by pdanpdan** [comment]
Please reopen when you add the code that should close the dialog.
For help requests please head to our discord channel or to the forum.

**Comment by goldsteinrazvan** [comment]
Hi, I updated the code with the part that should close the dialog. It is still not working even after adding this part.

**Comment by pdanpdan** [comment]
Add a `no-refocus` on the `<q-dialog ...` - you are opening the dialog on input focus and on close the dialog restores focus to the input.

**Comment by goldsteinrazvan** [comment]
Thank you! I didn't realize that was happening.

**Comment by pdanpdan** [comment]
No problem, but please first seek help in the discord channel or on forum - it saves our time for development.
