### ISSUE TITLE
q-layout doesn't seem to respect CSS 'no-shadow'

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#698]
I'd like a layout where the colour of the header and the colour of the main view join seamlessly. I tried adding the `no-shadow` class to the `q-layout` and the `q-toolbar` which is in the header slot, but the box-shadow is still there. I also tried adding this style:

    <style lang="stylus">
      .layout-header
        box-shadow none
    </style>

but still no joy. If I remove the box-shadow in the browser web inspector, the effect is as I want it.

I've looked at the code for `q-layout`, and I'm not sure where to begin - it's a bit of a monster :). I see there are `computedHeaderStyle()` and `computedHeaderClass()` functions - perhaps there are ways to influence it there? Any advice or other components which implement shadow by default and allow `no-shadow` to override I could study?

**Comment by spectrolite** [comment]
From http://beta.quasar-framework.org/components/layout.html#Vue-Properties
Vue Property	Type	Description
header-style	Object	Style applied to header.
header-class	Object	CSS classes applied to header.

==>```header-class="{'no-shadow': true}" ``` might bring you joy, and if not, you have header-style to try out other things.

**Comment by dsl101** [comment]
I like it when things bring joy. Needed and extra colon, but many thanks:

    :header-class="{'no-shadow':true}"

**Comment by spectrolite** [comment]
my bad...
I think this should work too though:
```header-class="no-shadow"```
if you have only one class

**Comment by spectrolite** [comment]
Thanks, code updated, to avoid anyone making the same mistake if they don't read it all.
