### ISSUE TITLE
Screen.width returns type string instead of type number

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#6980]
**Describe the bug**
I don't know if this is by design or an oversight but while preparing my code for TypeScript I noticed that the return value of `Screen.width` is of type `string` not `number` as I would've exptected.

```javascript
import { Screen } from 'quasar'

const setMiniState = (width: number) => {
   if (width > 1023) { ... }
}

setMiniState(Screen.width) // fails by TypeScript
```

Current workaround is casting to `number`:
```javascript
setMiniState(+Screen.width)
```

**Comment by rstoenescu** [comment]
Would u be so kind to provide a reproduction repo, a codesandbox (https://codesandbox.quasar.dev) or a codepen (https://codepen.quasar.dev) pls?

The error doesn't quite makes sense. It's a guaranteed number... But the devil is in the details so I can investigate with a reproduction repo. Thanks in advance.

**Comment by DarkLite1** [comment]
Couldn't [duplicate](https://codepen.io/DarkLite1/pen/QWjmpBG?editors=1010) it either. Probably a TypeScript bug in Visual Studio Code.
