### ISSUE TITLE
QSelect ie11

### ISSUE THREAD

**Issue by vpotap** [quasarframework/quasar#6982]
Get errors with IE11 (for Edge/Chrome is ok) for quasar v 1.10.5 QSelect component with all polyfills included, in UI can open q-select only once and then get errors in console :
```
[Vue warn]: Error in callback for watcher "value": "TypeError: Object doesn't support property or method 'closest'" found in ---> <QMenu> <QSelect>
```
```
[Vue warn]: Error in nextTick: "TypeError: Object doesn't support property or method 'remove'" found in <QSelect>
```
```
SCRIPT438: Object doesn't support property or method 'remove'
portal.js (64,9)
```

**Comment by vpotap** [comment]
found solution added two polyfills . Does this polyfills included in babel/core-js bundled with quasar  ? 
```
if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.msMatchesSelector ||
    Element.prototype.webkitMatchesSelector;
}

if (!Element.prototype.closest) {
  Element.prototype.closest = function(s) {
    var el = this;

    do {
      if (Element.prototype.matches.call(el, s)) return el;
      el = el.parentElement || el.parentNode;
    } while (el !== null && el.nodeType === 1);
    return null;
  };
}
(function (arr) {
  arr.forEach(function (item) {
    if (item.hasOwnProperty('remove')) {
      return;
    }
    Object.defineProperty(item, 'remove', {
      configurable: true,
      enumerable: true,
      writable: true,
      value: function remove() {
        if (this.parentNode === null) {
          return;
        }
        this.parentNode.removeChild(this);
      },
    });
  });
})([Element.prototype, CharacterData.prototype, DocumentType.prototype]);
```

**Comment by pdanpdan** [comment]
If you get this error in the docs then this is normal - the docs are no longer published with IE11 support.
Either you did not activate IE11 compatibility in quasar.conf or you have your IE11 working in Compatibility View due to some company policy.

Due to lack of any other detail it must be one of these.

**Comment by rstoenescu** [comment]
You don't need to manually embed any polyfills (not recommended anyway). Just edit your quasar.conf.js > supportIE: true. Quasar CLI takes care of the rest.

https://quasar.dev/quasar-cli/cli-documentation/supporting-ie#Installation-of-IE-Support
