### ISSUE TITLE
Two "input" events generated for QKnob

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#6983]
**Describe the bug**
Two "input" events are always generated using Knob.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/philfontaine/pen/mdexXby?editors=1011

**To Reproduce**
1. Click somewhere or use the keys to increase/decrease the Knob.
2. Check the console log, there will be two events.

**Expected behavior**
There is only one event

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in "quasar" v1.11.0.
