### ISSUE TITLE
I can't add cordova mode to my quasar project

### ISSUE THREAD

**Issue by hunter19850919** [quasarframework/quasar#6984]
when I used this command like this: quasar mode add cordova, then I got this error report.. please help me to check the attachment, why npm is installing package.json from index.js ?
![图片](https://user-images.githubusercontent.com/58357948/81408626-29179f00-9170-11ea-9ff7-778d289ca898.png)

**Comment by pdanpdan** [comment]
Hello. Please fill the issue template - we cannot help you if we know nothing about your case.
And try to use yarn - npm is frequently broken with windows.
