### ISSUE TITLE
Add instantFeedback prop to QKnob

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#6985]
**Is your feature request related to a problem? Please describe.**
This feature request is related to #6930. 
I switched to a QKnob because ultimately I needed to change the value but the animation is once again causing me some problems. 

More precisely, my biggest problem is when I'm going from 99 to 0 to 1, the animation does a whole counter clockwise turn.

**Describe the solution you'd like**
Add the instantFeedback prop, and in the code the check [here](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/knob/QKnob.js#L253) would be something like:
```js
props: {
  ...this.$props,
  value: this.model,
  instantFeedback: this.instantFeedback || this.dragging
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Will be available in "quasar" v1.11.0.
