### ISSUE TITLE
The q-stepper component should be aware of positioning CSS classes

### ISSUE THREAD

**Issue by averri** [quasarframework/quasar#6988]
I would like to change the default padding used by the `q-stepper` component. 
I have tried to use the standard positioning CSS classes, like the `q-pa-sm` and the component does not respect it, please see the example below.

Partial code with the relevant configuration (the `class` attribute):
```html
<q-stepper
      v-model="step"
      ref="stepper"
      color="primary"
      animated
      class="q-pa-sm"
    >
```

Resulting rendering:

![image](https://user-images.githubusercontent.com/1898447/81431894-d632ed00-9159-11ea-8b69-348473e16175.png)

Codepen example: https://codepen.io/averri/pen/WNQzKBV

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum. Thank you.

**Comment by averri** [comment]
Hi @pdanpdan, thanks for your answer, but I think it deserves a feature.

**Rationale for the feature support:**
The lack of support for the standard CSS positioning classes is a break in the design of the `q-stepper` component. The CSS positioning classes are a Quasar standard feature. Many components respects the CSS positioning classes, but `q-stepper` does not respect it. 

Reference: https://quasar.dev/style/spacing

**Comment by averri** [comment]
@pdanpdan, thank you for showing the workaround, which I'm reproducing here:

```html
<q-stepper
      v-model="step"
      ref="stepper"
      color="primary"
      animated
      class="my-custom-paddding"
    >
```

```css
.my-custom-paddding
  .q-stepper
    &__tab
      &:first-child
        padding-left: 8px
      &:last-child
        padding-right: 8px
    &__step-inner,
    &__nav
      padding-left: 8px
      padding-right: 8px
```

**Comment by CrawfordW** [comment]
The workaround doesn't work for me - has no effect. I would like to reduce the padding around a large table in one of the steps.
