### ISSUE TITLE
[Question] How to center a div for login form

### ISSUE THREAD

**Issue by tindecken** [quasarframework/quasar#699]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by tindecken** [comment]
I'd like to center my login form, please suggest me the solution
[https://i.imgur.com/EJj8MqK.png](https://i.imgur.com/EJj8MqK.png)

My code:
`<template>
  <div>
    <div class="layout-padding">
      <input type="text" placeholder="User Name" />
      <input type="password" placeholder="" />
      <button class="primary">Login</button>
    </div>
  </div>
</template>`

**Comment by rstoenescu** [comment]
Hi. Pls use forum for questions. Check Flex CSS doc page. Thanks.
