### ISSUE TITLE
QKnob: events are not in sync with UI when readonly/disable properties are changed

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#6990]
**Describe the bug**
When changing the value of readonly or disable (both behave exactly the same, so I will only use disable in the example) during the execution, the events are completely out of sync with the UI.

If disable was true initially then false: The UI will be correctly updated (not disabled) but the click events are not working at all.

If disable was false initially then true: The UI will be correctly updated (disabled) but the click events are still working.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/philfontaine/pen/abvYRdP?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fknob

**To Reproduce**
1. Change the readonly or disable properties using the toggles
2. Try to modify the QKnob by clicking

**Expected behavior**
UI and events are in sync

**Comment by rstoenescu** [comment]
There's no "disabled" prop. It's "disable" (notice no "d" at the end).
Since disabled is not defined as a component prop, it gets rendered as node attribute for which the "[disabled]" Quasar CSS selector goes into play.

However there seems to be a regression for the panning events and will fix them.

**Comment by philfontaine** [comment]
Right, I edited the title/description/codepen.

**Comment by rstoenescu** [comment]
Thank you so much for reporting!
Fix will be available on "quasar" v1.11.0.
