### ISSUE TITLE
How to automatically translate labels

### ISSUE THREAD

**Issue by Cosby86** [quasarframework/quasar#6994]
Hello all
Is there any possibility or whatever for automatically translate text in pages? I would like to avoid to call for every label the translation function because, in a big application, this call might be forgotten.

If it's non possible, any chance to cartch forgotten translated labels with automatic tests? Any other idea?

Thank you

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum. Thank you.
