### ISSUE TITLE
openURL to check for SafariViewController when cordova/ios

### ISSUE THREAD

**Issue by tommulkins** [quasarframework/quasar#6996]
**Is your feature request related to a problem? Please describe.**

My cordova project has both cordova plugins InAppBrowser (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/) and SafariViewController (https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller).  

I found that later iOS versions aren't allowing normal functionality of InAppBrowser any longer so replacing it with SafariViewController, which is now Apple's preference, was necessary to open a new browser window successfully.

**Describe the solution you'd like**

Enhance `openURL` logic by checking if 
* `Platform.is.ios` is `true`
* `window.SafariViewController` && `window.SafariViewController.isAvailable`
* Use `window.SafariViewController.show(options)` passing `options` as default object `{ url: url }`
* Consider allowing `openURL` to be passed an alternative object as first argument to allow for `options` to `window.SafariViewController.show`.  See https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller for usage.
* Finally, default to `window.open` for InAppBrowser if `SafariViewController` is unavailable. 

**Describe alternatives you've considered**
I've attempted all options of existing `InAppBrowser` and could not get it to work within cordova on iOS.

**Additional context**

See behavior of InAppBrowser attached 
![2020-05-09 15 40 01](https://user-images.githubusercontent.com/11251283/81484711-dbee0880-9215-11ea-86c0-4e0e76a0fed7.gif)
here

**Comment by pdanpdan** [comment]
Hello. As you already researched this problem can you please help and provide a PR?
Thank you.

**Comment by rstoenescu** [comment]
Had a bit of time to squeeze this in. Thank you for the research.
Enhancement will be available in "quasar" v1.11.0.
