### ISSUE TITLE
Quasar hot update does not work

### ISSUE THREAD

**Issue by Lyqxyz** [quasarframework/quasar#6997]
Quasar hot update does not work。In electron mode, when I change the code, the interface does not change

**Comment by rstoenescu** [comment]
Hi. There is a github template in place for tickets. Please open another ticket and fill all the information. It saves time for both you and us. Quasar can be run on a billion environments with a billion settings so it's impossible to tell which might be a scenario where something fails. Thank you.

**Comment by Lyqxyz** [comment]
![a](https://user-images.githubusercontent.com/38280023/81488151-c15c7380-9297-11ea-9e22-b6a2038505f2.PNG)

**Comment by rstoenescu** [comment]
Did you read what I wrote earlier? :)
