### ISSUE TITLE
hot update not working

### ISSUE THREAD

**Issue by Lyqxyz** [quasarframework/quasar#6998]
Operating System - Windows_NT(10.0.18363) - win32/x64
NodeJs - 12.16.1

Global packages 
  NPM - 6.13.4
  yarn - 1.22.4
  @quasar/cli - 1.0.5
  cordova - Not installed

Important local packages
  quasar - 1.10.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.8.5 -- Quasar Framework local CLI
  @quasar/extras - 1.7.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.6 -- Official router for Vue.js 2
  vuex - 3.3.0 -- state management for Vue.js
  electron - 8.2.5 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 14.2.1 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.9.6 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.10.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.   
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
![a](https://user-images.githubusercontent.com/38280023/81488633-e5bb4e80-929d-11ea-8913-f4171e4c156c.PNG)

**Comment by pdanpdan** [comment]
Hello. You circled some things without any detail on what you are doing.
Do you have any errors in any of the consoles (shell and electron dev tools)?
Does changing something else in code produce a change in output?
