### ISSUE TITLE
ionicons v5 svg file issue with outline version

### ISSUE THREAD

**Issue by Lobidu** [quasarframework/quasar#7001]
**Describe the bug**
Hey, I have to report that unfortunately the svg parser used for ionicons v5 may still not be 100% correct (Follow up from #6925)

Although most icons seem to be fine now, the mail icon still has an issue.

Below is a screenshot comparing ionicons imported via @quasar/extras, on the right the original ionicons icon imported as `img:/icons/mail-outline.svg`

<img width="66" alt="Screenshot 2020-05-10 at 19 19 24" src="https://user-images.githubusercontent.com/27945016/81507264-044c3480-92f4-11ea-8512-c370a10c480a.png">

I haven't seen a comparable issue in another icon, but I haven't used all of them. I will update this issue if I detect more.

Thanks

Janis

**Comment by rstoenescu** [comment]
Thanks for reporting this! Forgot to keep account of rect rx and ry when they are specified :)
Fix available in "@quasar/extras" v1.8.1
