### ISSUE TITLE
Problem with Quasar and JustPy from version 1.10.1

### ISSUE THREAD

**Issue by elimintz** [quasarframework/quasar#7005]
I am opening this issue following the recommendation of pdan on discord.

My use case is very specific so I wouldn't classify this as a bug. I you also understand if you do not find this a high priority issue as it involves Python and not JavaScript. In that case, please let me know so that we can discuss an arrangement that works for you.

[JustPy](https://justpy.io) is a Python framework that enables building websites without using JavaScript. It also allows using [Quasar components](https://justpy.io/quasar_tutorial/introduction/) which users find very useful. Basically, it allows people to develop Quasar websites using only Python and use Quasar as a GUI for Python programs.

The issue is that some components stopped rendering properly when used with the framework. The issue arose from version 1.10.1 of Quasar. Till version 1.10.0, there was no problem.

Below is a program that exhibits the issue. The program is in Python. To be able to run it, you would need to [install JustPy](https://justpy.io/tutorial/getting_started/). (I apologize for the inconvenience and the programming language involved)

In addition to running the program you will also need to create a file called `justpy.env` that is located in the same directory your program is. The file should include the following lines:

```python
NO_INTERNET = False
QUASAR_VERSION = '1.10.0'
```

This configuration tells the framework to fetch Quasar from the CDN and what version of Quasar to fetch.

And now for the example program: 

```python
import justpy as jp

html_string = """
<div class="q-pa-md" style="max-width: 350px">
    <q-list bordered class="rounded-borders">
      <q-expansion-item
        expand-separator
        icon="perm_identity"
        label="Account settings"
        caption="John Doe"
        expand-icon-toggle
      >
        <q-card>
          <q-card-section>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, eius reprehenderit eos corrupti
            commodi magni quaerat ex numquam, dolorum officiis modi facere maiores architecto suscipit iste
            eveniet doloribus ullam aliquid.
          </q-card-section>
        </q-card>
      </q-expansion-item>
      <q-expansion-item
        expand-separator
        icon="signal_wifi_off"
        label="Wifi settings"
      >
        <q-card>
          <q-card-section>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, eius reprehenderit eos corrupti
            commodi magni quaerat ex numquam, dolorum officiis modi facere maiores architecto suscipit iste
            eveniet doloribus ullam aliquid.
          </q-card-section>
        </q-card>
      </q-expansion-item>
    </q-list>
  </div>
"""


def my_click(self, msg):
    self.label = 'I was clicked'

async def expansion_basic():
    wp = jp.QuasarPage(dark=False)
    jp.parse_html(html_string, a=wp)
    jp.QBtn(label='click me now', click=my_click, a=wp, classes='q-ma-md')
    return wp

jp.justpy(expansion_basic)
``` 

The program itself is very short, just the last 10 lines of the above. The first 60 lines are an html string that gets parsed by the framework (the html is taken from the Quasar docs). In addition to the QList with QExpansion items described by the html string, the program puts on the page a QBtn that when clicked, its label changes to 'I was clicked'.

Please run this program first with the `justpy.env` specified above. You will see that it works as expected.

Then please change `justpy.env` to the following:
```python
NO_INTERNET = False
QUASAR_VERSION = '1.10.1'
```

The version of Quasar now loaded will be 1.10.1. You will see that the components do not render correctly. Still, try clicking the button or toggling the QExpansion items. You will see the components now render correctly. What is happening is that the components are updated by Vue.js and now display correctly. 

The issues seems to occur just when the components are initially created. When I debug the frontend, what I see is that during the mounting of the problematic elements, the update life cycle hook is called. For some reason, from version 1.10.1, the mounting of some elements also causes them to update. 

I hope the above is clear. Please don't hesitate to let me know if it is not or if you need additional information.

**Comment by pdanpdan** [comment]
In `jp/lib/python3.8/site-packages/justpy/templates/js/quasar_component.js` at line 38 change
`attrs: this.jp_props.attrs,` to `attrs: { ...this.jp_props.attrs },` - we are caching both $listeners and $attrs and if you use it in the current way it will not notify of change because it's the same object.

**Comment by elimintz** [comment]
Thank you very much! This indeed solved the problem. Much appreciated.
