### ISSUE TITLE
build: add flag for source maps in production (for upload)

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [quasarframework/quasar#7006]
**Is your feature request related to a problem? Please describe.**
If I am was searching right, there currently is no way to instruct the build to generate source maps e.g. for uploading to Sentry. I am trying to workaround this via `quasar build -d && upload.sh && quasar build`

**Describe the solution you'd like**
`SOURCE_MAPS=true quasar build` or `quasar build --source-maps` based on the strategy in the conf.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by appsoftwarenl** [comment]
@hawkeye64 @rstoenescu any chance for this to be added to the V2 release/roadmap? 
Building the project twice in CI/CD just to get the source-maps is just currently wasting precious CPU cycles 😉

**Comment by mstroeve** [comment]
@hawkeye64 @rstoenescu any chance for this to be added to the V2 release/roadmap?
Building the project twice in CI/CD just to get the source-maps is just currently wasting precious CPU cycles 😉

**Comment by hawkeye64** [comment]
@eljefedelrodeodeljefe  @mstroeve I believe if you add the `--debug` flag on, you will get source maps.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.

**Comment by lmm-git** [comment]
We are using a self-implemented fix by extending the webpack config to achieve a similar behavior like requested for Sentry integration. Would be nice if this could get officially supported.

```js
// extendWebpack  in quasar.conf

if (process.env.SOURCE_MAPS === 'yes') {
  const sourceMapPlugin = new webpack.SourceMapDevToolPlugin({
    filename: 'sourcemaps/[file].map'
  })
  cfg.plugins.push(sourceMapPlugin)
}

// Create sentry release only in CI
if (process.env.SENTRY_UPLOAD === 'yes') {
  const SentryWebpackPlugin = require('@sentry/webpack-plugin')
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const sentryPluginInstance = new SentryWebpackPlugin({
    // sentry-cli configuration
    authToken: process.env.SENTRY_WEBPACK_AUTH_TOKEN,
    org: 'our_org',
    project: 'our_project',
    url: 'https://sentry.our.domain',
    // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
    release: process.env.RELEASE_NAME,
    stripCommonPrefix: true,
    rewrite: true,

    // webpack specific configuration
    include: cfg.output.path,
    ignore: ['node_modules', 'webpack.config.js', 'tests']
  })
  cfg.plugins.push(sentryPluginInstance)
}
```

The workaround @eljefedelrodeodeljefe described does not work for us as there are some changes to the source code/maps which make debugging hard when building it twice.

**Comment by mstroeve** [comment]
@lmm-git thanks for the fix. It would we be great if the quasar team would add this source map parameter by default . 

The sentry part is not generic enough but this can be added in the project itself.

@hawkeye64 would you reconsider reopening this request using the suggested fix for the source map part?

**Comment by irux** [comment]
@lmm-git do you delete the source-maps after you upload them ?

**Comment by lmm-git** [comment]
> @lmm-git do you delete the source-maps after you upload them ?

Exactly, otherwise the source code would be publicly available, which is not always wanted.

**Comment by hawkeye64** [comment]
Did anyone try the `--debug` flag to create your source maps with a production build?

**Comment by roberttolton** [comment]
@hawkeye64 Adding the `--debug` flag, along with the second half of @lmm-git 's solution was what seems to have worked for me.

**Comment by hawkeye64** [comment]
I am closing this (again) but tagging @rstoenescu to see if it should be reopened.

**Comment by eleonor-aloware** [comment]
Hi, I'm currently encountering and I followed @lmm-git's fix. However, the build would output an error like this. Can someone please tell me what's missing?
![image](https://user-images.githubusercontent.com/83615121/233121122-bc57340d-1fb6-41cc-bb76-a7702734b791.png)

**Comment by robgwin** [comment]
Not sure if anyone will see this but I have this issue too and the workaround proposed here is less than ideal.

Taking the advice here I'm doing my prod build on a work server with debug flag:
```
npx quasar build --debug
```
Then I can sync everything but *.map to my webservers and upload the map files to bugsnag. Cool.

But here's the problem: debug mode has other effects that aren't appropriate in production:
- browser devtools shows all debug/warning/info messages in console
- browser devtools spits out lots of "failed to load source map" errors
- according to quasar-cli docs, in debug mode code is not minified

It seems obvious that something called "debug mode" is never intended for a production build, so it seems odd that that's the best recommendation here. Uploading sourcemaps to bug tracking platforms should be a pretty common use case...no?

**Comment by robgwin** [comment]
Update: I finally landed on a slightly more generic version of @lmm-git 's solution
```
// build.extendWebpack
        cfg.plugins.push(new webpack.SourceMapDevToolPlugin({
          append: false,
          filename: 'sourcemaps/[file].map',
          exclude: ['vendor.js'],
        }))
```
"append: false" keeps the map references out of the production js files so browser tools don't keep trying to load them. It's like setting devtool: 'hidden-source-map' but this is the only way I could find to do it without --debug mode.

**Comment by yeus** [comment]
I got another solution here using quasar.conf.ts:

```
        if (ctx.prod) {
          const commitHash = getGitCommitHash();

          // Add BannerPlugin to add a comment with the chunk name
          //  https://webpack.js.org/plugins/banner-plugin/
          chain.plugin('banner').use(webpack.BannerPlugin, [
            {
              banner: `//# sourceMappingURL=http://localhost:4000/sourcemaps/[name].${commitHash}.map`,
              raw: true,
              entryOnly: false,
              // I think this is basically the ast webpack stage...
              stage: webpack.Compilation.PROCESS_ASSETS_STAGE_REPORT,
              footer: true,
              test: /\.js$/, // Apply only to JavaScript files
            },
          ]);
          const create_sources = process.env.SOURCEMAP === 'true';
          console.log('build sources', create_sources);
          if (create_sources) {
            chain.plugin('sourcemap').use(webpack.SourceMapDevToolPlugin, [
              {
                //append:
                //  '\n//# sourceMappingURL=http://localhost:4000/sourcemap/[url]',
                append: false,
                // we are using "name" here in order to preserve the source maps across builds.
                // we need to be
                filename: `sourcemaps/[name].${commitHash}.map`,
                //exclude: ['vendor.js'],
              },
            ]);
          }
        }
```

this does the following:

- adds a valid sourceMappingURL to all production builds, but doesn't generate the sourcemaps at all
- we switch out the webpack hash for a git commit hash.
- You can generate now generate the sourcemaps in CI and locally using the `SOURCEMAP=true` env variable and always generating the correct sourcemaps for the relevant build.
- You simply start a dev-server on your computer (http://localhost:4000 in this case) and then go to the domain with the production webpage. Opening the dev panel, it should automatically load all the relevant sourcemaps from your local server.
