### ISSUE TITLE
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore my-release-key.keystore -destkeystore my-release-key.keystore -deststoretype pkcs12"

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#7008]
When following the guide on creating a keystore:

https://quasar.dev/quasar-cli/developing-capacitor-apps/publishing-to-store#Android-Publishing

I get this notification:

> The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore my-release-key.keystore -destkeystore my-release-key.keystore -deststoretype pkcs12".

**Comment by pdanpdan** [comment]
And?
