### ISSUE TITLE
I  can not install @quasar/icongenie

### ISSUE THREAD

**Issue by chulaiguo** [quasarframework/quasar#7009]
Error: pngquant failed to build, make sure that libpng-dev is installed

**Comment by chulaiguo** [comment]
win10

**Comment by pdanpdan** [comment]
http://letmegooglethat.com/?q=win+10+pngquant+failed+to+build%2C+make+sure+that+libpng-dev+is+installed

**Comment by chulaiguo** [comment]
I google that. but all the solution does not work !  installing windows-build-tools also does not work.

I don't know why.  I re-install the node/quasar, but it does not work.

**Comment by pdanpdan** [comment]
If you cannot install windows build tools then there is a problem with the system. Most probably a company windows image

**Comment by chulaiguo** [comment]
1. C:\Windows\system32> npm install --global windows-build-tools
...
All done!
+ windows-build-tools@5.2.2

2. reboot the computer

3. C:\Users\chulaiguo> npm install -g @quasar/icongenie
....
× Error: pngquant failed to build, make sure that libpng-dev is installed

That's all.  I try it many times, but the same result.

**Comment by rstoenescu** [comment]
@chulaiguo Maybe this thread will help you: https://github.com/imagemin/imagemin-pngquant/issues/46

Someone reports that it was an antivirus (Kaspersky) doing a false positive and ruining everything.

This other comment is interesting too: https://github.com/imagemin/imagemin-pngquant/issues/46

Some other saying that "Windows 10 users, if you follow @hkniyi steps and still cannot install, your corporate firewall might be blocking the download. We had an https proxy firewall blocking it and that was the problem for me."

Please report back which solution worked for you so we can add it to the docs. Thank you.

**Comment by chulaiguo** [comment]
I done! It's worked!

1.C:\Windows\system32> npm install --global windows-build-tools

2. goto C:\Users\{your PC username}\.windows-build-tools,  run vs_BuildTools.exe, and  select npm, python to install.

3. C:\Users\{your PC username}> npm install -g @quasar/icongenie
OK!

**Comment by bkirvin** [comment]
Having the same problem on macOS Sonoma with Apple chip. Can windows build tools be installed on Mac?
