### ISSUE TITLE
Scheduler (or Calendar) component.

### ISSUE THREAD

**Issue by aleksander237** [quasarframework/quasar#7013]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Any plans for creating the official Scheduler (Calendar) component?

[Vuetify](https://vuetifyjs.com/en/components/calendars/)
[Kendo UI](https://www.telerik.com/kendo-vue-ui/components/scheduler/)
[jQuery UI Widgets](https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxscheduler/index.htm#demos/jqxscheduler/defaultfunctionality.htm)

**Describe alternatives you've considered**
There is an unofficial one [Daykeep calendar](https://github.com/stormseed/daykeep-calendar-quasar) but probably not in development anymore.

**Comment by pdanpdan** [comment]
https://quasar.dev/app-extensions/discover#Components
https://github.com/quasarframework/quasar-ui-qcalendar
