### ISSUE TITLE
"quasar clean" creates folder called "dist" when distDir is set to something else

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#7014]
Very minor...
In my `quasar.conf.js` I have `build.distDir` set to a new value.  I deleted the "dist" folder in my project root--I don't need it.
When I run `quasar clean` I see:
```
 app:artifacts Cleaned build artifact: "C:\Temp\server\app_bundle" +0ms
 app:artifacts Cleaned build artifact: "C:\Temp\.quasar" +5ms
 app:artifacts Emptied dist folder +4ms

 app:clean Done cleaning build artifacts +1ms
```
and I see that a new (empty) `dist` folder has been created in my project.

**Comment by rstoenescu** [comment]
Fix will go into "@quasar/app" v1.8.7.
Thanks for also supplying a PR.
