### ISSUE TITLE
Electron dev mode not rendering UI

### ISSUE THREAD

**Issue by bunya017** [quasarframework/quasar#7017]
**Describe the bug**
My PC ran into a Blue Screen of Death few days ago, I was able to restore it using a restore point 
and then updated the windows OS on it. I then ran electron dev server in my project folder and it 
spit out some errors, so I `rm -rf node_modules` and ran `yarn install`, but the errors persisted. I then 
`rm -rf node_modules` on both yarn global path and project folder, and installed everything afresh, it 
finished installation without errors!

I ran the dev server again in electron mode, it compiles successfully with some warnings on the terminal, spawns 
the electron instance, but nothing gets rendered (see screenshot below). 

When I run `quasar dev -m electron`, I get: 
quasar dev -m

```
 Dev mode.......... electron
 Pkg quasar........ v1.11.1
 Pkg @quasar/app... v1.8.6
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +164ms
 app:webpack Extending Renderer process Webpack config +37s
 app:webpack Extending Main process Webpack config +18s
 app:generator Generating Webpack entry point +815ms
 app:dev-server Booting up... +552ms


 • Compiling:
 ├── Renderer process ████████████████████ 100% done in ~6m
 └── Main process     █                    0%



 DONE  Compiled successfully in 385695ms                                                                      8:53:27 PM

i ｢wds｣: Project is running at http://0.0.0.0:8080/
i ｢wds｣: webpack output is served from
i ｢wds｣: 404s will fallback to /index.html
 app:electron Building main Electron process... +7m

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in ~6m
 └── Main process     ████████████████████ 100% done in ~43s

 app:electron Webpack built Electron main process +43s

Hash: 8776d0ae16ceefe407d4
Version: webpack 4.43.0
Time: 43025ms
Built at: 05/12/2020 8:54:19 PM
           Asset     Size         Chunks             Chunk Names
electron-main.js  220 KiB  electron-main  [emitted]  electron-main
Entrypoint electron-main = electron-main.js

WARNING in ./node_modules/electron-debug/index.js 96:45-58
Critical dependency: the request of a dependency is an expression
 @ ./src-electron/main-process/electron-main.dev.js
 @ multi ./src-electron/main-process/electron-main.dev.js

WARNING in ./node_modules/electron-debug/index.js 97:61-74
Critical dependency: the request of a dependency is an expression
 @ ./src-electron/main-process/electron-main.dev.js
 @ multi ./src-electron/main-process/electron-main.dev.js

 app:electron Booting up Electron process... +256ms
 app:spawn Running "C:\Users\bunyaminu\Desktop\yaro-post\node_modules\electron\dist\electron.exe --inspect=5858 C:\Users\bunyaminu\Desktop\yaro-post\.quasar\electron\electron-main.js" +143ms


Debugger listening on ws://127.0.0.1:5858/97069647-97c0-41c2-bdb8-ec6858e8324b
For help, see: https://nodejs.org/en/docs/inspector
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:1656) UnhandledPromiseRejectionWarning:   TypeError: mime.getType is not a function

  - middleware.js:100 processRequest
    [yaro-post]/[webpack-dev-middleware]/lib/middleware.js:100:32

  - util.js:53 ready
    [yaro-post]/[webpack-dev-middleware]/lib/util.js:53:12

  - util.js:182 handleRequest
    [yaro-post]/[webpack-dev-middleware]/lib/util.js:182:5

  - middleware.js:64
    [yaro-post]/[webpack-dev-middleware]/lib/middleware.js:64:7

  - new Promise

  - middleware.js:63 middleware
    [yaro-post]/[webpack-dev-middleware]/lib/middleware.js:63:12

  - layer.js:95 Layer.handle [as handle_request]
    [yaro-post]/[express]/lib/router/layer.js:95:5

  - index.js:317 trim_prefix
    [yaro-post]/[express]/lib/router/index.js:317:13

  - index.js:284
    [yaro-post]/[express]/lib/router/index.js:284:7

  - index.js:335 Function.process_params
    [yaro-post]/[express]/lib/router/index.js:335:12

  - index.js:275 next
    [yaro-post]/[express]/lib/router/index.js:275:10

  - route.js:127 next
    [yaro-post]/[express]/lib/router/route.js:127:14

  - route.js:131 next
    [yaro-post]/[express]/lib/router/route.js:131:14

  - route.js:131 next
    [yaro-post]/[express]/lib/router/route.js:131:14

  - route.js:131 next
    [yaro-post]/[express]/lib/router/route.js:131:14

  - route.js:131 next
    [yaro-post]/[express]/lib/router/route.js:131:14


(node:1656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. Update windows
2. Run `rm -rf node_modules` in both global path and project folder
3. Delete yarn-lock.json in both global path and project folder
4. Install global and project's local packages
5. Run `quasar dev -m electron`

**Expected behavior**
Electron instance gets spawned with rendered UI

**Screenshots**
![Annotation 2020-05-12 220246](https://user-images.githubusercontent.com/26235763/81747626-4f0aaf80-94a0-11ea-915f-7188b91c265b.png)

**Platform (please complete the following information):**
OS: Windows_NT(10.0.18362) - win32/x64
Node: 12.16.1
NPM: 6.13.4
Yarn: 1.22.4
Browsers: Firefox 76.0.1
iOS:
Android:
Electron: 8.2.5

**Additional context**
Other packages:
  quasar - 1.11.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/cli - 1.0.7
  @quasar/app - 1.8.6 -- Quasar Framework local CLI
  @quasar/extras - 1.8.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.6 -- Official router for Vue.js 2
  vuex - 3.3.0 -- state management for Vue.js

**Comment by pdanpdan** [comment]
Hello.

What do you mean by global path and project folder?

I suppose your nodejs is somehow broken on your machine after the restore and upgrade.
The only advice I can give is to completely cleanup nodejs on the system, reinstall, cleanup your project (try a `quasar mode remove electron` and `quasar mode add electron`).

Your description is like "A Series of Most Unfortunate Events" :(

If you can reproduce the problem on a clean machine then please reopen.

**Comment by bunya017** [comment]
I followed your advice but the problem persisted.

I later discovered `mime` to be the culprit, it was installed but some files were missing, so error persisted.
I downloaded `mime@latest` zip, extracted and compared it with `node_modules/mime`.
I ran `node -e "console.log(require('mime'))"` on terminal and replaced the missing file until it returned no errors, See pictures below:

### Before replacing missing files
![Before 2020-05-13 174257](https://user-images.githubusercontent.com/26235763/81872951-ada05e00-9572-11ea-8b53-1b0ee8e34942.png)


### After replacing missing files
![After 2020-05-13 174257](https://user-images.githubusercontent.com/26235763/81873043-d88ab200-9572-11ea-91f0-520405c5e066.png)



Thank you.
