### ISSUE TITLE
how to make qajaxbar catch vue-router lazy loading progress

### ISSUE THREAD

**Issue by afx919** [quasarframework/quasar#7018]
i use vue-router lazy loading. doc url: https://router.vuejs.org/guide/advanced/lazy-loading.html
i want qajaxbar show lazy loading  progress
or teach me another way
thanks

code in routes.js :
routes: [
    { path: '/foo',component: () => import('pages/Foo.vue'), }
]

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum.

**Comment by rstoenescu** [comment]
A more appropriate use for what you need would be the [LoadingBar plugin](https://quasar.dev/quasar-plugins/loading-bar). Then use vue router hooks to trigger it.
