### ISSUE TITLE
qDate, qInput and format

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7019]
**Describe the bug**
qInput format is broken after opening a qDate inside a qInput

This is the code
```
<q-input rounded readonly v-model="dateWhen" :rules="['dateWhen']">
              <template v-slot:append>
                <q-icon name="event" class="cursor-pointer">
                  <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                    <q-date v-model="dateWhen" @input="() => $refs.qDateProxy.hide()" />
                  </q-popup-proxy>
                </q-icon>
              </template>
            </q-input>

dateWhen: "2020-01-31",
```
click on the icon, select a date in qDate, the date is selected and the format changes.
Adding mask='dateWhen' like in the docs, makes things worse.

**Expected behavior**
At first it shows the format 2020-01-31 as expected.
I expect it to remain the same after selecting a new date.

**Screenshots**
![image](https://user-images.githubusercontent.com/17168621/81782313-4fd42d80-9502-11ea-81e8-bc6a7819de72.png)

**Platform (please complete the following information):**
OS: Windows 10/web
Browsers: Firefox/chrome
Electron: version=22.6.0

**Comment by pdanpdan** [comment]
Hello. Please add a codepen showing your problem.

**Comment by Amosss** [comment]
The issue was in the documentation of q-date with q-input. Thanks, works now.

**Comment by pdanpdan** [comment]
What example? Please give me the url (click on the example ribbon to copy the url) so that we can fix it. Thank you.

**Comment by Amosss** [comment]
Well, it's not really an issue because the format in the docs is YYYY/MM/DD so it works, but it can be misleading if your format is different, like in my case: YYYY-MM-DD, then the example won't work and you will need to do some modifications: https://quasar.dev/vue-components/date#With-QInput

**Comment by rstoenescu** [comment]
* There's no "dateWhen" rule. https://quasar.dev/vue-components/input#Internal-validation
* Use mask when your format is different than the "standard".
