### ISSUE TITLE
shake event not emitted on shake 

### ISSUE THREAD

**Issue by Codebreaker101** [quasarframework/quasar#7020]
**Describe the bug**
shake event not emitted on shake 

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/codebreaker101/pen/GRpBmPg?editors=1010

**To Reproduce**
1. Go to codepen
2. Click on the button
3. Click OK to shake

**Expected behavior**
`onDialogShake` function to be called when dialog shakes

**Additional context**
The [documentation](https://quasar.dev/vue-components/dialog?#QDialog-API) states that there is an event that is fired when the dialog is _shaken_. Seeing the codepen link, it does not. Browsing the source I could not find that the `shake` is emitted anywhere. I don't know if this is a code issue (code not implemented), or documentation issue (event does not exist anymore).

**Comment by pdanpdan** [comment]
Hello. I'll check, but please fix the link you put for the API - now it points to a wrong url (different than the shown one)

**Comment by Codebreaker101** [comment]
Fixed

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.11.2.
