### ISSUE TITLE
QSelect + input-class does nothing

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#7023]
**Describe the bug**
`<q-select input-class="text-h1" />` does nothing

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mesqueeb/pen/KKdBvoO?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fselect

**Expected behavior**
The class should be applied somewhere according to the documentation.

**Comment by pdanpdan** [comment]
It is used on the input that is used if you use `use-input` - see my use of `use` that I used here?

**Comment by mesqueeb** [comment]
Hahahahaha !! I got it 😉
