### ISSUE TITLE
icongenie: segmentation fault on Node 13.x

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#7026]
**Describe the bug**
Icongenie generation produce a segmentation fault when on Node 13.4
The bug isn't blocking in any way as the segmentation fault happens after icons generation.

**To Reproduce**
1. Install Node 13.4
2. Run icongenie generation command
3. See segfault error

**Expected behavior**
No segfault error

**Screenshots**

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 13.4
Yarn: 1.22

**Additional context**
One time I randomly got more details on the error

```
FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place
 1: 0x9f27a0 node::Abort() [node]
 2: 0x9f4a62 node::OnFatalError(char const*, char const*) [node]
 3: 0xb59e0a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb5b40e v8::HandleScope::HandleScope(v8::Isolate*) [node]
 5: 0x9c5463  [node]
 6: 0x99275a node::Environment::RunAndClearNativeImmediates(bool) [node]
 7: 0x99eafc node::Environment::CleanupHandles() [node]
 8: 0x99ef7e node::Environment::RunCleanup() [node]
 9: 0xa2f9b0 node::NodeMainInstance::Run() [node]
10: 0x9c43c1 node::Start(int, char**) [node]
11: 0x7f8f3f047b97 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
12: 0x960ea5  [node]
```

**Comment by rstoenescu** [comment]
This is at best a problem upstream in one of the deps.

**Comment by IlCallo** [comment]
Shall I close this as "won't fix"? The issue was just to notice we know. Even just adding a "don't use with Node 13" on the docs could be fine

**Comment by rstoenescu** [comment]
Wanna take a look at it before I close it. Currently no time.

**Comment by rstoenescu** [comment]
Sorry but don't have time to investigate this. Non LTS versions of Node are discouraged anyway so probably not worth seeing what's actually happening.
