### ISSUE TITLE
TypeScript definition for Notify.setDefaults requires 'message'

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#7027]
**Describe the bug**
The TypeScript definition for `Notify.setDefaults` requires a `message` property on the options.

**Codepen/jsFiddle/Codesandbox (required)**
N/A, it's a TypeScript definition issue.

**To Reproduce**
1. Create a TypeScript quasar project
2. Add something like ```Notify.setDefaults({
      position: "top"
    })```
3. Compile
4. See TypeScript error:

```
TS2345: Argument of type '{ position: "top"; }' is not assignable to parameter of type '{ type?: string | undefined; color?: string | undefined; textColor?: string | undefined; message: string; caption?: string | undefined; html?: boolean | undefined; icon?: string | undefined; ... 14 more ...; multiLine?: boolean | undefined; }'.
  Property 'message' is missing in type '{ position: "top"; }' but required in type '{ type?: string | undefined; color?: string | undefined; textColor?: string | undefined; message: string; caption?: string | undefined; html?: boolean | undefined; icon?: string | undefined; ... 14 more ...; multiLine?: boolean | undefined; }'.
```

**Expected behavior**
`message` should be optional (or maybe even excluded, as it doesn't really make sense as a default)

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10
Node: 10.15.3
NPM: 6.13.4
Yarn: 1.22.4
Browsers:
iOS:
Android:
Electron:
TypeScript 3.7.5

**Additional context**

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.11.2
