### ISSUE TITLE
Instant feedback prop for q-linear-progress 

### ISSUE THREAD

**Issue by Simon-JB** [quasarframework/quasar#7031]
A new prop "instant-feedback" was recently added (or made public) to the q-circle-progress component. It would be great to have a similar one for the q-linear-progress.

Right now when I set a short interval loop to update the value it results in a choppy transition (I guess because the duration of the animation is fixed and slower than my interval).

Another option would be to make the animation duration a parameter (with the ability to put it at zero)?

**Comment by rstoenescu** [comment]
Hi,

Prop will be available in "quasar" v1.11.2
