### ISSUE TITLE
Enable --skip-trim support from profile json

### ISSUE THREAD

**Issue by Nigui** [quasarframework/quasar#7038]
**Is your feature request related to a problem? Please describe.**
I can't use `--skip-trim` command option in my profile.json.
Works great with CLI.

**Describe the solution you'd like**
You could add camelCase `skipTrim` option in profile json

**Describe alternatives you've considered**
use CLI

**Additional context**

**Comment by rstoenescu** [comment]
Hi. It's there already. Forgot to document it.
