### ISSUE TITLE
Backspace on QSelect with hide-selected remove item from model

### ISSUE THREAD

**Issue by ymoreiratiti** [quasarframework/quasar#7039]
**Describe the bug**
The QSelect is removing items from vmodel, even if it doesn't appear on the screen

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/yurititi13/pen/MWaqyay?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fselect

**To Reproduce**
1. Create a QSelect with multiple selection, filter and hide-input
2. Select a couple items, then press "backspace" on the input field.

**Expected behavior**
If the QChips containing the vmodel it's set to hidden (hide-selected attribute) and the user press backspace, don't delete the item from array

**Screenshots**
![Issue](https://user-images.githubusercontent.com/5731429/81948851-9005df80-95d8-11ea-9ba6-30696d1cbbd7.gif)

**Platform (please complete the following information):**
OS: Windows 10 x64
Node: 12.16.1
NPM: 6.13.4
Browsers: Chrome

**Comment by pdanpdan** [comment]
Just when everybody wanted to be able to delete options with backspace :)
Good catch.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.11.2.

**Comment by limajonatas** [comment]
But it hasn't been fixed yet.
