### ISSUE TITLE
Grid (Flexbox) Gutter: Bottom margin

### ISSUE THREAD

**Issue by daniel-shuy** [quasarframework/quasar#704]
Quasar: 0.13

Why do the gutter classes add a bottom margin? This causes issues when trying to add a gutter to a flex row that has a top margin that is less than the negative top margin added by the gutter class. This also adds unnecessary space below the flex row when it isn't wrapped (and isn't even required for the vertical gutter, because that is created by the padding, not the margin).

**Comment by rstoenescu** [comment]
The new gutter on v0.14 also fixes this.

**Comment by daniel-shuy** [comment]
Awesome!
