### ISSUE TITLE
qBadge color not in Quasar Color Palette

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7041]
**Is your feature request related to a problem? Please describe.**
I can set a color to a badge only from quasar palette and sometimes the color is not specific with a name or can't be translated to a palette's color.

**Describe the solution you'd like**
I want to be able to set a color using rgb, hex etc.

Thanks

**Comment by pdanpdan** [comment]
You can define your own color (with whatever name you want) and then use that color. Or if you want direct CSS colors then add styles. Sorry.

**Comment by Amosss** [comment]
I tried color="#50af00" - didn't work
I tried color="rgb(175,80,0)" - didn't work
I tried color="green" - worked 
and then I read this in the documents under style->color:
Color name for component **from the Quasar Color Palette**
examples: primary teal-10

So please tell me, how can I define a different color, using rgb and hex?

**Comment by rstoenescu** [comment]
@Amosss https://quasar.dev/style/color-palette#Adding-Your-Own-Colors

**Comment by Amosss** [comment]
Thanks but the color is going from green to red based on a value from 0 to 100 of a cell/value inside a table... I was hoping for something more user friendly for this case.

**Comment by pdanpdan** [comment]
Use CSS: https://codepen.io/pdanpdan/pen/GRpXWeG?editors=1010

**Comment by Amosss** [comment]
Thanks
