### ISSUE TITLE
qmenu and q-popup-proxy does not work correctly

### ISSUE THREAD

**Issue by Timz** [quasarframework/quasar#7045]
**Describe the bug**
after changing the target, the qmenu and q-popup-proxy does not work correctly

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Timz02/pen/abvaQJR

**To Reproduce**
Click first time on button or click on the same button several times

**Expected behavior**
the menu is dynamically updated and works correctly

**Screenshots**
![GIF 15 05 2020 13-42-53](https://user-images.githubusercontent.com/2128043/82042360-6a4d0900-96b2-11ea-8ba1-153992295093.gif)

**Platform (please complete the following information):**
OS: win10
Node: 12
NPM: last
Yarn: last
Browsers: chrome

**Comment by pdanpdan** [comment]
Hello. You are setting the variable and trying to open the menu in the same tick. Vue only evaluates changes at the end of the tick.
