### ISSUE TITLE
Error while closing qTime Popup by calling hide method on mobile

### ISSUE THREAD

**Issue by Codebreaker101** [quasarframework/quasar#7046]
**Describe the bug**
When in a mobile view (chromium simulation) error `Error in v-on handler: "TypeError: Cannot read property 'getBoundingClientRect' of undefined"` occurs when trying to close QTime popup using `@input` event

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/codebreaker101/full/oNjPQdK

**To Reproduce**
1. Go to codepen
2. Open Inspector 
3. Toggle device toolbar
4. Select one of the mobile clients
5. Refresh page
5. Open time selector and select hours and seconds
6. Check console for error

**Expected behavior**
For the error not to occur. 

**Additional context**
QDate works fine as it does not use `getBoundingClientRect`

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.11.3.
