### ISSUE TITLE
Lazy loading of images

### ISSUE THREAD

**Issue by den67rus** [quasarframework/quasar#7049]
**Is your feature request related to a problem? Please describe.**
Add a function for images that implements lazy loading, that is, when the image falls into the viewport, it starts loading. Also by scrolling, 500px before the image falls into the viewport, etc.

**Describe the solution you'd like**
QImg-API: `lazy="true"`, `lazy-scroll="500"`

**Describe alternatives you've considered**
Example: https://github.com/verlok/lazyload

**Additional context**
There are new attributes for img `loading="lazy"` https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading  They are not supported everywhere yet. https://caniuse.com/#search=loading%3D%22lazy%22  And don't work for `<div style="background-image: url('http://img');"></div>`

P.S. I know about: Combine with QIntersection component or Intersection directive. I would like a solution without workaround. After all, this is what the frameworks were created for...

**Comment by pdanpdan** [comment]
Loading lazy is only implemented on Chrome and Firefox(desktop), and is basically exactly what the intersection observer does. Loading lazy also is browser implementation dependent and not configurable.
It's pointless to invent a lot of things just for this. You can use the intersection directive also.

**Comment by den67rus** [comment]
@hpdanpdan then let's add the recipe to the documentation. The attribute I referenced is not an example implementation.

**Comment by pdanpdan** [comment]
It is already:
https://quasar.dev/vue-directives/intersection#Example--Scrolling-Cards
https://quasar.dev/vue-components/intersection
