### ISSUE TITLE
Alert component's property need to be adjusted.

### ISSUE THREAD

**Issue by Mykeyb2004** [quasarframework/quasar#705]
Alert component 's property "position" need to be adjusted. Its property `top-right`, `right`, `bottom-right` , `bottom-left`, `left` and `top-left` shows proper width that can just fits the texts' width . But `top` and `bottom` shows too wide windows on the page. It's need to be adjusted : )

**Comment by spectrolite** [comment]
I can see cases where top and bottom would be useful as they are now.
Maybe we just need 2 more positions, bottom-center and top-center, that would be sized in the same way as the other 6 and horizontally centered just like top and bottom.

**Comment by rstoenescu** [comment]
Will implement @spectrolite's suggestion.
