### ISSUE TITLE
a console.log with boolean forgotten in knob

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#7051]
**Describe the bug**
When knob values is changed, in the console one can see "false" for each value change.
**Codepen/jsFiddle/Codesandbox (required)**
Any from https://quasar.dev/vue-components/knob

**To Reproduce**
open console in https://quasar.dev/vue-components/knob and change any value

**Screenshots**
![image](https://user-images.githubusercontent.com/31144210/82070168-055ad880-96dd-11ea-835d-77d6975da4a8.png)

**Platform (please complete the following information):**
browser

**Comment by pdanpdan** [comment]
Too late :)

**Comment by rstoenescu** [comment]
Which has already been fixed in v1.11.2
