### ISSUE TITLE
QUploader: max-total-size and max-files restrictions don't apply if adding files consequently

### ISSUE THREAD

**Issue by dasaveliev** [quasarframework/quasar#7055]
**The bug description**
https://quasar.dev/vue-components/uploader#Restricting-upload
Examples with **max-total-size** and **max-files**.
Max total upload size (4k): we can add as many files as we want, each less than 4k if adding consequently by any quantity if the **being added** total size is less than restriction (4k in this case)
Same with **Max number of files (3)** example: adding consequently any quantity less than or equal 4 will pass successfully.
Verification works as if current files list was empty every time we add files.
P.S. It also would be nice if canAddFiles() in QUploaderBase.js would return false if the indicated size and quantity limits are reached.

**Codepen/jsFiddle/Codesandbox (required)**
The bug can be observed from the docs examples, so I omit this.

**To Reproduce**
1. Open https://quasar.dev/vue-components/uploader#Restricting-upload
2. Use **Max total upload size (4k)** and **Max number of files (3)** examples. Total size and quantity limits do not apply if adding file(s) not exceeding limits multiple times: less than 4k and up to 3 files at a time, respectively.

**Expected behavior**
1. Totals limits should apply correctly respecting files already in the list. 
2. canAddFIles() should return false if the mentioned limits hit.

**Comment by rstoenescu** [comment]
The adding action is not appending but replacing current list. As in “oops, I made a mistake, I wanted these files instead”. After uploading, it’s your duty to disable the component (disable prop) if you’re done with it.

**Comment by rstoenescu** [comment]
As a sidenote, there’s also a ticket requesting append instead of replace.

**Comment by rstoenescu** [comment]
Ah, sorry. Totally misread and thought it was about QFile. Too many tickets on QFile and QUploader lately :) Reopened.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "quasar" v1.11.3.
