### ISSUE TITLE
Add non-linear scale to QRange and QSlider

### ISSUE THREAD

**Issue by kermiv** [quasarframework/quasar#7058]
When QRange is used for price input, it becomes unusable if the total range is large, such as 0 - 1000, but the user tries to select a price range between 10 and 20. This is only 1% of the length of the QRange line.

**Possible solutions**

***The first solution***
Add new prop `mode` with values `lienear` (default) and  `logarithmic`.
But in this case, prices from 100 to 1000 occupy only 33% of the line. I wanted at least 50%.

***Most robust solution (recomended)***
Allow provide custom function, witch must return precentage from line start for given price. Of course it can be anything else that would be useful in QRange's internal calculations

```
<q-range
  v-model="standard"
  :min="0"
  :max="this.max"
  :positionFn="this.getPositionForPrice"
/>
```
and in my comopnent methods I definine function:
```
getPositionForPrice(price) {
  const correction = 1/3
  return Math.pow(price, correction) / Math.pow(this.max,correction)
}
```

**Comment by pdanpdan** [comment]
Hello - you can already do this now - use whatever conversion function you want to change from the value of the slider to your desired value.
I put a one way example here: https://codepen.io/pdanpdan/pen/YzyRNrg?editors=1010
If you need 2-way use a get/set computed to cast values both ways.
