### ISSUE TITLE
Q-badge doesn't work on q-expansion-item

### ISSUE THREAD

**Issue by liambarr** [quasarframework/quasar#7059]
**Is your feature request related to a problem? Please describe.**
Expected behaviour: Q-badge should show on a q-expansion item but doesn't seem to attach.

**Describe the solution you'd like**
A badge sits on buttons, avatars and text divs. When put above a q-expansion item, it doesn't float in the same way.

**Describe alternatives you've considered**
Currently, I'm simply using the icon of the q-expansion item to display a "badge".
It's not quite what I'm looking for - users should be able to expect a badge to look the same across the app.

**Comment by pdanpdan** [comment]
Please create a codepen with what you have tried.

**Comment by pdanpdan** [comment]
Closing for lack of feedback.
