### ISSUE TITLE
QSelect is pulling up an on-screen keyboard on capacitor Android

### ISSUE THREAD

**Issue by vycoder** [quasarframework/quasar#7061]
**Describe the bug**
QSelect is pulling up an on-screen keyboard on Android when it shouldn't. Only happens on `behavior="menu"`.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/yev/pen/rNOQzMq

**To Reproduce**
1, Create a QSelect just like attached codepen above
2. Make sure behavior="menu"
3. Run in capacitor mode android.
4. Choose an option on QSelect

**Expected behavior**
No onscreen keyboard should be displayed.

**Platform (please complete the following information):**
OS: Pop!_OS 20.04
Node: 12.4.0
NPM: 6.14.5
Yarn: 1.22.4
Browsers: N/A
iOS: Not tested
Android: Yes
Electron: N/A
Quasar: 1.11.3

**Additional context**

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.11.4.

**Comment by slowaways** [comment]
Now I can't Select Option in Cordova! The fix generate another bug!
