### ISSUE TITLE
QFile doesn't fire @input inside of QBtnDropdown with v-close-popup

### ISSUE THREAD

**Issue by jaybo** [quasarframework/quasar#7064]
**Describe the bug**
If a QFile is placed inside QListItem inside a QList inside a QBtnDropdown, then the @input event does not fire when the item is selected.  The file selection dialog _does_ appear, but the @input event is not triggered.  Curiously, the problem doesn't seem to exist if either (a) the QList is not encased in a QBtnDropdown, or (b) the QItem does not include **v-close-popup**.

This issue makes it difficult to put a file selection option inside a menu.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jaybonomad/pen/dyYQjye?editors=1111

**To Reproduce**
1. Go to https://codepen.io/jaybonomad/pen/dyYQjye?editors=1111
2. Click on 'Save works'.  Note that the alert appears with the name of the selected file.
3. Click on 'Save fails'.  Note that the alert does not appear.

**Expected behavior**
Both 'Save works' and 'Save fails' menu selections should trigger the alert.

**Screenshots**

**Platform (please complete the following information):**
OS: Win10
Node: 10.16.0
NPM: 6.13.17
Yarn: 1.22.4
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

When you are closing the menu (v-close-popup is triggered on "click") the components inside of it also get destroyed. For your use case, close the menu after you get the file picked by the user.
