### ISSUE TITLE
Min value of rowsPerPageOptions has no effect on table pagination

### ISSUE THREAD

**Issue by onurkose** [quasarframework/quasar#7065]
**Describe the bug**
We use rows-per-page-options on table component to modify default definition ([3, 5, 7, 10, 15, 20, 25, 50, 0])

Although the default array has 3 as min value for pagination, QTable.js has a data elm named as innerPagination, and rowsPerPage value set here as 5. Therefore, if you don't modify any rows-per-page-options and without server side pagination, the default rowsPerPage comes out of package as 5, which is fine.

But, when I set a custom pagination options, something like [10, 20, 30, 50, 100, 0], 5 from the innerPagination object is still renders on the screen by default and there are no owerriding property to set another default.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/zc8gm94o/

**To Reproduce**
1. Just click the rows per page select to see if there's no 5 listed

**Expected behavior**
innerPagination should receive the minimum value of rowsPerPageOptions array in table-pagination.js, probably in the begining of computedPagination method.

**Additional context**
I do generate my tables dynamically, so I can't use pagination.sync property to set a rowsPerPage value. But I think the expected behavior should be as described above anyways just because there is a rows-per-page-options property.

**Comment by pdanpdan** [comment]
Hello. For help requests please head to:
- documentation (check the API card - pagination object)
- our discord channel
- the forum

**Comment by onurkose** [comment]
Hello @pdanpdan,

I am reading the documentation almost since the begining of Quasar framework but I don't think you are reading the issue here.

If you do so, please let me know how you implement that pagination object to a table that dynamicaly generated. Imagine there are 2+ tables generated from an array. How do you have seperate pagination object for each?

**Comment by pdanpdan** [comment]
Why can't you set the pagination if something is dynamic?

**Comment by onurkose** [comment]
This is a dynamic table.

```
<template>
  <div>
    <q-expansion-item
      :label="group.name"
      :key="`expansion-item-${group.name}`"
      v-for="group in groupedData"
    >
      <q-table
        :columns="columns"
        :ref="`table-${group.name}`"
        :data="group.data"
        :rows-per-page-options="[10,20,50,100,0]"
      />
    </q-expansion-item>
  </div>
</template>

<script>
export default {
  data () {
    return {
        groupedData: [{
             name: 'a group name',
             data: [...]
        }, {
             name: 'another group name',
             data: [...]
        }, +18 groups]
    }
  }
}
```

Imagine there are 20 expansion items and obviously 20 tables.

Just to load all tables 10 rows per page, which is the intended behaviour in this example above (_see the [10,20,50,100,0] array_), are you suggesting to append a pagination object to each group object in groupedData array? QTable is already keeping those pagination data in sync. Why should anyone needs a duplication?

**Comment by pdanpdan** [comment]
If you make a codeped showing your problem we can help you.

**Comment by rstoenescu** [comment]
Like the commit above says: "feat(QTable): Ability to use "pagination" without sync modifier for the initial state; rowsPerPage is by default first from rowsPerPageOptions #7065"

So you're double covered :) @onurkose 
This will go into "quasar" v1.11.4.

**Comment by onurkose** [comment]
Thank you for such a great work!
