### ISSUE TITLE
QFile webkitRelativePath is empty

### ISSUE THREAD

**Issue by peppicus** [quasarframework/quasar#7066]
I used q-file in this way

                    <q-file v-model="file2Send"
                      filled
                      bottom-slots
                      counter
                      accept=".jpg, image/*"
                      multiple max-files="1"
                      @input="checkFile"
                      >
                      <template v-slot:before>
                        <q-avatar>
                          <q-icon name="attach_file" />
                        </q-avatar>
                      </template>

                      <template v-slot:hint>
                        allega foto
                      </template>

                      <template v-slot:after>
                        <q-btn round dense flat icon="send" @click="uploadFile"/>
                      </template>
                    </q-file>

but in checkFile and uploadFile i get this object with empty webkitRelativePath

![image](https://user-images.githubusercontent.com/20922241/82312087-dedfba80-99c6-11ea-8f45-f10327456430.png)

So how can I send the correct file to the server?

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum.

**Comment by rstoenescu** [comment]
The File entries are generated by a native `<input type="file">`, so if anything is out of place it's the browser's fault.

**Comment by peppicus** [comment]
> The File entries are generated by a native `<input type="file">`, so if anything is out of place it's the browser's fault.

tnks!
