### ISSUE TITLE
QDrawer mini state with hover functionality and show expansion items beside the hovered item

### ISSUE THREAD

**Issue by rmagpantay05** [quasarframework/quasar#7067]
Is there a way to have Mini Drawer with Hover functionality and will popup the corresponding expansion item based on the hovered icon/menu item?

As of the current behavior, when drawer is in mini state, most of the elements for the expansion item will be set to “display: none” which is difficult to manipulate/control since it is based on the drawer component functionality for mini mode.

Desired functionality/behavior

![image](https://user-images.githubusercontent.com/62052722/82313229-ab1e8800-99fa-11ea-8098-4b4d3a294e28.png)

**Comment by rstoenescu** [comment]
Hi,

I'm sorry, but this is just too specific to be embedded into the framework. However, with a bit it can be done.
