### ISSUE TITLE
[Request] Uploader clear (reset state) method

### ISSUE THREAD

**Issue by zajca** [quasarframework/quasar#707]
### what
api method to clear uploader content (reset state).

### use case
I'm using uploader for adding images to editor. When user clicks on add image button, modal will open with uploader and user can add single image. On upload modal is closed and image pasted to editor. When user clicks on button again modal is open and uploader has still item from previous.

This can be now done only with:
`this.$refs.uploader.$data.files = []`

but general api method would be better.

**Comment by rstoenescu** [comment]
Will add a reset() method.
