### ISSUE TITLE
Error: 'Vue is a constructor and should be called with the `new` keyword');

### ISSUE THREAD

**Issue by Zireael** [quasarframework/quasar#7072]
**Describe the bug**
I'm getting error `'Vue is a constructor and should be called with the `new` keyword');` when using latest Quasar through vue-cli plugin. Page render fails.
Follow your installation guide here:
https://quasar.dev/start/vue-cli-plugin
run `yarn upgrade --latest`
Fail.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/gifted-rubin-qi2d1

**To Reproduce**
1. Go to https://quasar.dev/start/vue-cli-plugin
2. Follow installation instructions
3. Execute `yarn upgrade --latest`
4. Start `"serve": "vue-cli-service serve"`
5. Open project webpage
6. Open browser console to see error

**Expected behavior**
Latest Quasar works with cue-cli plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/3856578/82412983-7f3bea80-9a6c-11ea-9e6b-8ab79b78ea9e.png)

**Platform**
OS: Win10
Node: 14.0.0
NPM: 6.14.4
Yarn: 1.22.4
Browsers: Chrome

**Additional context**
I would like to use Quasar in a Vue-first environment, not Quasar-first environment. I appreciate you pushing for people using quasar cli, but quasar relies on vue, not the other way around, so I would like to reflect that in the order of my stack imports.

**Comment by pdanpdan** [comment]
Hello.

I just checked on a new project and all looks ok.
I don't know what you did in your repo (the codesandbox attached is full of all kind of errors about eslint and it's not working), but I suppose you broke it by doing `yarn upgrade --latest` - there is a safe alternative `yarn upgrade-interactive`.

**Comment by Zireael** [comment]
Well, I have found the culprit:
✔️works: "babel-plugin-transform-imports": "**1.5.0**",
❌breaks: "babel-plugin-transform-imports": "**2.0.0**",

**Comment by rstoenescu** [comment]
Do not manually install packages that come with q/app or q/babel-preset-app.

**Comment by Zireael** [comment]
> Do not manually install packages that come with q/app or q/babel-preset-app.

I was using `babel-plugin-transform-imports` to treeshake Lodash, but can achieve that in a different way. There will be times where people will use quasar dependencies for other purposes than just quasar. Maybe quasar should keep it's own node_modules to avoid dependency version side-effect vulnerability? Like I see 'sass' in my node_modules has it's own node_modules.
Maybe I'm minority in using quasar as a component in my application rather than using it as a starting point. For example, if I were to create an electron app, I would do my stack as electron>vue>quasar because that's how I see the order of scopes and provided features. So any dependencies I use would fist serve electron, then vue, then quasar.
Anyho, we get to live another day. 
Thank you for your advice.

**Comment by rstoenescu** [comment]
Of course you can use the deps however you want. Just don't install other versions (aka just use the ones already installed). It's not a "must" but a kind reminder that we do thoroughly test compatibility between the million deps out there so that in the end we ensure that everything "simply works out of the box" -- so that you won't have headaches like above.
