### ISSUE TITLE
Infinite loop QFab/QFabAction in unit test

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#7073]
**Describe the bug**
I been upgrading Quasar in my project. Here are the versions:
@quasar/app: 1.5.5 > 1.8.6
quasar: 1.9.1 > 1.11.3

The project still runs so that is not the issue. Some of my unit tests are suddenly broken now, and are reporting:
```
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <QFab>
       <Container>
         <Root>
```

Since nothing changed in my code and I still use the same Jest version, the only thing I can think of here is that this is a Quasar related issue. 

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
I'm testing the following component: 
```html
<template>
	<q-fab-action color="info" icon="save" :disable="isDisabled" @click="onClick" class="someName" />
</template>
```
The test is quite simple, I mount the component and change the computed "isDisabled" property in the test and then assert if the HTML rendered does not have the "disabled" property anymore. 
```ts
const btn = wrapper.find(".someName");
expect(btn.exists()).toBe(true);
// Change value that causes computed "isDisabled" to return true
await wrapper.vm.$nextTick();
expect(btn.attributes()).not.toHaveProperty("disabled");
```
My real example uses a Store for the computed property so I excluded that to make the example simpler. But as previously said, the element is working fine when running the project.

**Expected behavior**
No infinite loop.

**Platform (please complete the following information):**
OS: Windows
Node: 12.13.1
NPM: 6.12.1

**Comment by pdanpdan** [comment]
QFabAction needs to be child of QFab (provide/inject) - maybe this is one of the reasons?
Can you try adding a parent QFab?
Also the original idDisabled was replaced with a isActionable some time ago, so I hope you are not checking for it.

**Comment by Evertvdw** [comment]
@pdanpdan It is a child of QFab, I use a wrapper component with only a QFab to place the component in for a test. And in the docs I still see the disable prop as the way to disable the component. 

I check for the attribute "disabled" on the button, which is there when disabled and is removed when not disabled. (I checked in the DevTools)

**Comment by pdanpdan** [comment]
I was talking about the comment in code (`// Change value that causes computed "isDisabled" to return true`). Yes, the prop is `disable`.

**Comment by Evertvdw** [comment]
@pdanpdan Hahaha, good hunch. I was already trying previous Quasar versions before I saw your comment and came back here to report that the bug is indeed introduced with 1.10.1. 

Do you know then what the issue is?
Ill try to see how a QBtn behaves.

**Comment by Evertvdw** [comment]
The issue is still there when replacing QFabAction with QBtn.

**Comment by Evertvdw** [comment]
Either: [Commit](https://github.com/quasarframework/quasar/commit/8ec188b67dc30b1a6a01fd218db25681c2e23c30) or [Commit](https://github.com/quasarframework/quasar/commit/a6940aeab2c3f558c0451a92e10ad84fc182248a) I guess is the problem. Why, I have no clue..

**Comment by pdanpdan** [comment]
I think it is something about the cache-ing of listeners. Please do 2 more tests (on the current quasar, because it has some fixes):
- use a QBtn but without the `@click` listener
- use a QBtn but with the `disable` hardcoded

```
<template>
	<q-btn :disable="isDisabled" />
</template>
```

```
<template>
	<q-btn disable />
</template>
```

**Comment by Evertvdw** [comment]
In both cases I get the same infinite loop.

**Comment by pdanpdan** [comment]
Can you also test an empty QBtn?

```
<template>
	<q-btn />
</template>
```

**Comment by Evertvdw** [comment]
Yes then also

**Comment by pdanpdan** [comment]
Hello. I just created a clean quasar project, added @quasar/testing with JEST, and I cannot reproduce your problem.
Please create a reproduction repo.

**Comment by Evertvdw** [comment]
Hi, just had a week off from work, will see if I can get a reproduction repo up and running.

**Comment by k-bialucha** [comment]
I think I have a very closely related issue. I also try to test for a button disabled state in a similar way that @Evertvdw . I've got this error reported from QSelect component:
`
      [Vue warn]: You may have an infinite update loop in a component render function.
      found in
      ---> <QSelect>
             <TcAddress>
               <QCardSection>
                 <QForm>
[...]
`
It also happens when upgrading to v1.10.1 or above.
One additional trait I noticed it that it happens when I use `mount` from `@vue/test-utils`, but not when using `shallowMount`.
Any ideas what could be our common problem?

**Comment by k-bialucha** [comment]
Okay, I think I spotted the issue. The problem was coming from `@vue/test-utils`. I was previously on `@1.0.0-beta.31`. Upgrading to the newest version (`@1.0.3`) eliminated the problem.
Related issue:
https://github.com/vuejs/vue-test-utils/issues/1407

**Comment by Evertvdw** [comment]
@k-bialucha I will check and see if that resolves my issue as well!

**Comment by Evertvdw** [comment]
That does indeed solve the issue, so I will close this ticket. Thanks @k-bialucha!
