### ISSUE TITLE
q-virtual-scroll scopedSlots default Unable to render

### ISSUE THREAD

**Issue by liuzeWeb** [quasarframework/quasar#7074]
Because of the large amount of data, and the hierarchical presentation of qtree can't meet the demand, I modified the qexpansionitem drop-down presentation. There are too many data in the drop-down. Nest qvirtualscroll in the place where qexpansionitem is expanded, render with function recursion, and render with qvirtualscroll default slot can't be rendered.

Novice code:
`
<script>
import {
    mapActions
} from 'vuex'
 
export default {
    name: 'dataTree',
    data() {
        return {
            nodes: [],
            options: [],
            filter: null,
            name: [],
            select: null,

        }
    },
    mounted() {
        this.getdata()

    },

    methods: {
        getdata() {
            this.$showloading(this);
            this.handleTreeDeviceGet({
                sort: 'channel'
            }).then(res => {
                this.$clearloading(this);
                if (res.errno == 0) {
                    this.nodes = Object.assign([], Object.freeze(this.initdata(res.data)));  // getdata
 
                }
            })
        },
    
        initdata(data) {
            if (!_.isEmpty(data)) {
                let _self = this
                let arr = []
                for (let i = 0; i < data.length; i++) {
                    let temp = data[i]
                    let hsachildren = []
                    if (temp.children && temp.children.length > 0) {
                        hsachildren = Object.assign([], this.getChildren(temp.children))
                    }
                    arr.push({
                        data: {
                            name: temp.hasOwnProperty('name') ? temp.name : temp.device_name,
                            count: temp.children ? this.getDevice(temp.children) : '',
                            id: temp.id,
                            pid: temp.pid,
                            device_id: temp.hasOwnProperty('device_id') ? temp.device_id : null,
                            children: hsachildren,
                            channel: temp.hasOwnProperty('channel') ? temp.channel : 0,
                            online_state: temp.hasOwnProperty('online_state') ? temp.online_state : null,
                            header: temp.header ? temp.header : false
                        },
                    })
                }
                return arr
            }
        },
        getChildren(children) {
            let arr = []
            let _self = this
            if (children && children.length > 0) {
                for (let i = 0; i < children.length; i++) {
                    let temp = children[i]
                    let havechild = []
                    if (temp.children && temp.children.length > 0) {
                        havechild = Object.assign([], this.getChildren(temp.children))
                    }
                    arr.push({
                        data: {
                            name: temp.hasOwnProperty('name') ? temp.name : temp.device_name,
                            count: temp.children ? this.getDevice(temp.children) : '',
                            id: temp.id,
                            pid: temp.pid,
                            device_id: temp.hasOwnProperty('device_id') ? temp.device_id : null,
                            children: havechild,
                            channel: temp.hasOwnProperty('channel') ? temp.channel : 0,
                            online_state: temp.hasOwnProperty('online_state') ? temp.online_state : null,
                            header: temp.header ? temp.header : false
                        }

                    })
                }
            }
            return arr
        },
        renderChildren(h, tempchildren, left) {
            console.log(tempchildren)
            let width = left + 12
            let arr = []
            let _self = this
            return [h('QVirtualScroll', {
                attrs: {
                    item: tempchildren,
                    separator: ''
                },
                style: {
                    "max-height": "300px"
                },

                scopedSlots: {
                    default: props => {
                        console.log(this.$scopedSlots)
                        return [
                            h('div', {}, item.data.name)
                        ]
                    }
                }
            },)]
        },
        
        getDevice(data) {
            let max = 0
            let count = (children) => {
                for (let i = 0; i < children.length; i++) {
                    let temp = children[i]
                    if (temp.channel && temp.channel !== 0) {
                        max++;
                    }
                    if (temp.children && temp.children.length > 0) {
                        count(temp.children);
                    }
                }
            }
            count(data)
            return max
        },
    },
    render() {
        let h = this.$createElement
        let arr = []
        let width=12
        let _self = this
        console.log(this.nodes)
        for (let i = 0; i < this.nodes.length; i++) {
            let temp = this.nodes[i]
            let children = temp.data.children
            let badge = ''
            if (temp.data.count) {
                badge = h('QBadge', {
                    class: 'q-ml-md'
                },temp.data.count)
            }
            arr.push(h('QExpansionItem', {
                scopedSlots: {
                    header() {
                        return h('div', {
                            class: 'flex items-center',
                            style: {
                                'width': '100%'
                            },
                        }, [
                            h('QIcon', {
                                attrs: {
                                    name: 'bt-jiedian'
                                },
                                style: {
                                    'padding-left': width + 'px',

                                }
                            }),
                            h('div', {
                                style: {
                                    'padding-left': '12px'

                                }
                            }, temp.data.name),
                            badge
                        ])
                    }
                }
            },children && children.length > 0 ? _self.renderChildren(h, children, width) : ''))

        }
        return h('div',{},arr)
    },
}
`

**Comment by pdanpdan** [comment]
Sorry, nobody would understand what is your request. You have codepen where you can put your code for inspection. And please use the quasar discord channel or the forum for help requests.
