### ISSUE TITLE
QTable: Add go to first/last page

### ISSUE THREAD

**Issue by mountash** [quasarframework/quasar#7075]
**Is your feature request related to a problem? Please describe.**
The user wants an opportunity to jump to first and last page in the table

**Describe the solution you'd like**
Show double arrows near prev and next page in pagination. If the last page is unknown, an event will be emitted, developer must implement the reaction.
![tempsnip](https://user-images.githubusercontent.com/6277925/82444053-440cdc00-9aab-11ea-9cf3-9f14a28f00f8.png)

**Describe alternatives you've considered**
An aternative will be to overwrite the bottom section of qtable in each table, which is not a perfect solution.

**Additional context**
I can create a PR for that

**Comment by rstoenescu** [comment]
Will be available in "quasar" v1.12.0.
