### ISSUE TITLE
QSelect: ability to customize scroll bar

### ISSUE THREAD

**Issue by p1pchenk0** [quasarframework/quasar#7077]
**Is your feature request related to a problem? Please describe.**
In my current project there is a need to customize scroll bars for the whole project. While it is doable elsewhere via `QScrollArea` component, there is no way to do it inside select dropdown.

**Describe the solution you'd like**
Solution could be wrapping options list in `QScrollArea` and add ability to pass styling props for it from `QSelect` props:
```vue
<q-select
  :options="options"
  :scroll-styling="{
    scrollStyle: { ... },
    thumbStyle: { ... }
  }"
/>
```
**What I've tried**
Put all options inside `before-options` slot, but it brings a lot of overhead and feels more like a hack rather than solution

**Comment by rstoenescu** [comment]
Hi,

This can (and should) be done through regular css (albeit not all browsers will be happy, I must admit). https://scotch.io/tutorials/customize-the-browsers-scrollbar-with-css

It might sound like a good idea to add QScrollArea to QSelect's internals, but that would mean a huge overhead for which the majority of devs won't even benefit. We are trying to keep performance at its best, which I must regretfully decline this request. Sorry for any inconveniences and hope that the CSS approach will be in your favour.

**Comment by dgiaccobasso** [comment]
Hi! Same problem here, and it was impossible for me to solve it with CSS because I don't know how to target the q-select dropdown.

Has someone achieved it?

**Comment by t-manan** [comment]
@dgiaccobasso  @rstoenescu @p1pchenk0  if anyone has made the custom scrollbar for q-select , please share the solution.

**Comment by pdanpdan** [comment]
Rocket science :)
https://codepen.io/pdanpdan/pen/VwxzEMQ

**Comment by t-manan** [comment]
> Rocket science :) https://codepen.io/pdanpdan/pen/VwxzEMQ

Thanks @pdanpdan it works 🎊
