### ISSUE TITLE
QMenu - quasar@1.11.3

### ISSUE THREAD

**Issue by duwensi** [quasarframework/quasar#7079]
__Describe the bug__

The menu doesn't show up in IE 11 browser.

__To Reproduce__

Please open the Quasar document page (https://quasar.dev/vue-components/menu) in IE 11.

**Comment by pdanpdan** [comment]
The documentation is no longer built using IE11 compat - there is no reason you should need to use the docs in IE11. But if you need this you can clone the repo, change the ie11 compat flag in config and start locally.
Maybe @rstoenescu can point to the official announcement.

**Comment by duwensi** [comment]
This BUG is also occured in my project, in which the `supportIE` configure is turned on in quasar.conf.js. Do I need to open up a new issue to describe it. @pdanpdan

**Comment by pdanpdan** [comment]
You can put the required details here:
- a codepen showing how you use the code
- browser/os/...
