### ISSUE TITLE
QPopupEdit : Add open (show) and close (hide) methods ?

### ISSUE THREAD

**Issue by DocBouCou** [quasarframework/quasar#7085]
Hi,

There are use cases when you may want to open a popup-edit by clicking elsewhere than on the text which is to be changed (on a button / icon next to the text).

For instance, in my app, most of the time when something is written outside of an input, you cannot edit it directly. 
Inside a few pages, I would like the user to be able to edit some written text and QPopupEdit would offer a nice shortcut. Indeed, I do not want to clutter these pages with some inputs (there are already more than enough) but I would like the users to avoid the overhead of going to another page to make a few changes. 
But, you do not expect to be able to edit the text just by clicking on it (as most of the time it won't edit anything). So I would like to offer a visual clue (like a pen icon, or a button) telling them they can edit.
**(** In my specific cases I could just probably add the pen outside the curly brackets, and it would work, but I still  think that, if doable, adding the open and close methods would widen the possibilities. Hence, I made this feature request. **)**

Regards,

**Comment by pdanpdan** [comment]
You can force open/hide now by putting a ref on the QPopupProxy and calling `this.$refs.popupProxyRef.$refs.menu.show()` and `this.$refs.popupProxyRef.$refs.menu.hide()`.

**Comment by DocBouCou** [comment]
@pdanpdan Thank you for your fast answer! When you wrote "ref on the QPopupProxy", did you mean "ref on the QPopupEdit" ?

**Comment by smolinari** [comment]
@DocBouCou - Yes. He did mean QPopupEdit. 

Scott

**Comment by DocBouCou** [comment]
Thank you very much for your answer.
I let you decide if you want to close the issue or not (I guess it depends on whether you want to add the show/hide directly on the QPopupEdit or not).

**Comment by rstoenescu** [comment]
Added show() and hide() and will be available in Quasar v1.12.0.
