### ISSUE TITLE
Integration with Symfony Encore

### ISSUE THREAD

**Issue by Mausino** [quasarframework/quasar#7086]
**Is your feature request related to a problem? Please describe.**
You can intgrate Vue or React with Symfony framework by Symfony Encore which make your work much easier... 

**Describe the solution you'd like**
Look if is possible by easy way.. to integrate it as Vue or React

**Describe alternatives you've considered**

**Additional context**
Now you must develop app if you want good background rock solid fondations for your aplication with vue and copy and edit your code to quasar that extennd your layer to desktop, mobile or browser app.

**Comment by rstoenescu** [comment]
Hi,

Quasar **is** Vue, so whatever you need to do with a basic vue project you can also do with a Quasar project.

**Comment by Mausino** [comment]
Hi, @rstoenescu thank you for your answer :) 

i figure out how add quasar to encore as Quasar UMD

i think that many persons want also use strong background enviroment as API Platform is.. and i hope that somebody should looks on issue with Quasar generator 

https://github.com/api-platform/client-generator/issues/188
