### ISSUE TITLE
Make it possible hide the arrow in the QSelect when using it in as a text autocomplete

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#7087]
**Is your feature request related to a problem? Please describe.**
When using q-select as a text autocomplete (https://quasar.dev/vue-components/select#Example--Text-autocomplete) i want to be able to hide the arrow down icon. I want the user to see it as a normal input. Also when i'm allowing to filter after 3 chars the arrow down is there the whole time, clickable, but clicking it has no effect and is misleading to the user.

**Describe the solution you'd like**
A prop `dont-show-arrow` or something like that.

**Comment by pdanpdan** [comment]
there is already - search in the API card for hide or dropdown or icon
