### ISSUE TITLE
Animated doesn't work on q-tab-panels with router_views

### ISSUE THREAD

**Issue by Asthonishia** [quasarframework/quasar#7089]
**Describe the bug**
Animated doesn't work on q-tab-panels with router_views

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/codesandbox-app-endd4

**Expected behavior**
We expect an animation between tabs

Browsers: Chrome / Firefox

**Comment by pdanpdan** [comment]
you are not changing the panels - you are using the same panel and changing the route in it.

**Comment by Asthonishia** [comment]
Humm ok understood. Thank you :)
