### ISSUE TITLE
Use of QScrollArea with custom styling may result in inconsistent design across the app

### ISSUE THREAD

**Issue by DocBouCou** [quasarframework/quasar#7090]
Hi,

Initially for a list and list-items, I used a scroll-area component (with a --q-color-secondary colored scrollbar, slightly rounded), with infinite scrolling. It works fine.
Then, I realized that within my QTables, the scrollbars were not alike (just standard scrollbars). So I customized it using css (a mix of #5993 and [this css-trick article](https://css-tricks.com/the-current-state-of-styling-scrollbars/) ), and forgetting about the rounded effect on the scrollbar (not possible to have a consistent design with firefox and chromium, as far as I know, if using only css). So I changed the QScrollArea I just made, to take off the rounded effect and make it consistent with the pure-css customized scrollbars of my QTables. 
So far, so good, but... But then I thought about the QSelects (see #3871), maybe QMenu, and else... So, for now, I have decided to forget about custom scrollbars in my app. 

I think you see my point. If you start using QScrollArea with a custom toolbar it is hard, if not impossible, to keep a consistent scrollbar-design all along the app. 

I realize how much work it might be if you want to allow the use of custom scrollbar all along the app. It probably implies to encapsulate all the Quasar components which may need it inside some QScrollArea, and to make the scroll-area props available from parent components... check for unwanted consequences while taking care it does not slow everything just for very few people who may need it...
But it is still an issue, so I thought I would better point it out here.

**Important edit**:
With Firefox, the scrollbar-design becomes inconsistent per sé. The default scrollbar when using QScrollArea (or sidebar drawer layout for instance) is a grey rectangle (chromium-like), although the default scrollbar with Firefox is a thin orange bar.

Regards,

**Comment by rstoenescu** [comment]
Hi,

Thank you for the detailed writeup, but you do realise that:
1.  QScrollArea's "scrollbar" is not the browser's scrollbar. It wound mean a world of injustice for QScrollArea to call it a dumb component with only "some CSS applied". The scrollbar that you see in it is simulated completely by QScrollArea.
2. QScrollArea has style props and can be customized.
3. There is no standard way to customize the native scrollbars cross-browsers. Not our fault they don't sit and work together towards a w3c specs on it.

**Comment by DocBouCou** [comment]
Thank you for your answer. I do agree with your three points. And I do acknowledge and understand that QScrollArea is more than just css customization for the scrollbar. Hence, among other things, the scrollbar only appears on hover and may be fully customized consistently accross browsers. Which is already a lot.
 
To clarify, I was speaking about scrollbars _"inside"_ element/components. 
For instance, the scrollbar _inside_ a QSelect (or whatever select in fact) is the default browser scrollbar (orange in Firefox, grey in Chromium). Then, if you have a QSelect next to a scroll area, it looks odd (especially in Firefox, even with _basic_ QScrollArea). That is a fact, which can be observed and/or tested using Firefox and going to quasar.dev (just need to go to the QSelect docs, you scroll within a select and then within the left or right drawer, it is different and might feel odd - but not awful or terrible for sure ;) - )
This is what I mean when I speak about inconsistent design (side note: I am French, in french we use the word "design" and it means mostly the _look_ of something -colours, shape, etc-, it does not have a meaning as strong as in english and I do realize that now :) ). I do understand that it is not Quasar fault. And I do understand that it would be an insane amount of work to _maybe_ solve such a tiny issue (if it is at all doable). 

But, as this issue is a matter a fact, which has been more or less pointed out in #5993 and #3871, I think that a small warning in the docs should be enough. 
Something like "if using QScrollArea you should be aware that the scrollbar within your scroll-area might be different (and _will_ in some browsers) than the window scroll-bar and different than native scrollbars within QSelect, QTable, etc."

Regards,
