### ISSUE TITLE
QMenu: Property scroll-target does not accept function

### ISSUE THREAD

**Issue by eliaspanagiotidis** [quasarframework/quasar#7093]
Trying to assign the following function returning scroll-target:
`<q-menu :scroll-target="getScrollTarget">`
`getScrollTarget () {
      return someComponent.$el.closest('.scroll,.scroll-y,.overflow-auto')
}`
I get the error bellow:
`TypeError: scrollTarget[fnProp] is not a function
    at VueComponent.__changeScrollEvent (anchor.js?c474:176)`

**Codepen**
https://codepen.io/eliaspanagiotidis/pen/ExVMdzY?editors=1010

**Expected behavior**
I tried this solution because it seems that a QMenu element behaves in an unexpected (??) manner if its target is an element whose closest scrolling element is not the document. More specifically when the user tries to scroll through the scrollbar the menu disappears, while if they try to scroll using the mouse wheel then the menu does not follow the target.
I'd expect a consistent behavior in both cases (either hiding or moving the menu with its target).

**Comment by pdanpdan** [comment]
You have assigned a function to scrollTarget. It does not expect a function.

**Comment by dwweb0309** [comment]
What is solution?
I also have scrolling problem with QMenu

**Comment by pdanpdan** [comment]
Use a ref or computed - not a function name

**Comment by dwweb0309** [comment]
https://stackblitz.com/edit/quasarframework-6qtzv8
Open drawer, click **Basic Menu** button, and scroll up/down. The calendar doesn't follow the button.
How can I solve this problem? Scroll target is used in this case?

**Comment by dwweb0309** [comment]
@eliaspanagiotidis 
Did you find the solution? I also want to have a consistent behavior
