### ISSUE TITLE
QSlider to support predefined steps

### ISSUE THREAD

**Issue by mkhanal** [quasarframework/quasar#7095]
**Is your feature request related to a problem? Please describe.**
When allowing users to use a slider, currently we can select a recurring/sequential steps 

```html
<q-slider :step="10" :min="0" :max="50"/>
```
What this does not only allow is for a slider to have predefined steps of say
[1, 5, 10, 15, 25, 50]. Notice non-uniform steps.

Also, notice if I need to allow selecting [1,10,20,30,40,50], I can't do it right now, because the first step is 9 (10-1=9), and the ones after that is 10 (20-10=10) 

**Describe the solution you'd like**
It would be good if the step field could also take an Array of numbers or a different prop could take in an array of steps to allow for this.
```html
<q-slider :step="[1, 10, 15, 25, 50]"/>
```
or
```html 
<q-slider :options="[1, 10, 15, 25, 50]"/>
```

**Describe alternatives you've considered**
1. QSelect, with a non-preferred UX
1. https://nightcatsama.github.io/vue-slider-component/#/basics/marks?hash=use-with-included

**Additional context**
Typical use cases:
1. Plan selection https://bitbucket.org/product/pricing
1. This can further be expanded to use non-numeric values as data points eg: grade scale [F, E, E+, ...A+]

**Comment by pdanpdan** [comment]
For the moment you can try something like this: https://codepen.io/pdanpdan/pen/YzyMyvE
Sorry, I don't have time to make a fully working example.

**Comment by mkhanal** [comment]
Hi @pdanpdan . I have workarounds right now.

Since quasar has an active roadmap and plans to make enhancements, I think this might be a good candidate to go into component enhancements.

Thanks for the codepen though.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
