### ISSUE TITLE
Tooltip Stuck Visible When Button Disabled

### ISSUE THREAD

**Issue by robopeter** [quasarframework/quasar#7096]
**Describe the bug**
A tool tip on a button which is disabled while the tool tip is visible gets "stuck" visible and never goes away. 

https://codepen.io/robopeter/pen/ExVJaVm

**To Reproduce**
1. Add any tool tip on a button which transitions to "disabled" while the tool tip is visible. An example can be found here: https://codepen.io/robopeter/pen/ExVJaVm
2. Hover over the button (to see the tool tip), and while the tool tip is still visible, click on the button
3. Notice that the tool tip is now stuck on the screen.

**Expected behavior**
Tool tip should disappear after the configured (or default) timeout.

**Platform (please complete the following information):**
Browsers: Tested (fails) on Chrome 81 and Edge

**Comment by rstoenescu** [comment]
Hi,

This is normal because native `<button>` also does not emit any events so QTooltip doesn't know when to hide. Put a `v-if` on the QTooltip as well (v-if="!yourBtnIsNotDisabled").

**Comment by gaby64** [comment]
> Hi,
> 
> This is normal because native `<button>` also does not emit any events so QTooltip doesn't know when to hide. Put a `v-if` on the QTooltip as well (v-if="!yourBtnIsNotDisabled").

is this still the best solution?

**Comment by rstoenescu** [comment]
Yes
