### ISSUE TITLE
Error from chokidar on upgrade quasar

### ISSUE THREAD

**Issue by alexandremsouza1** [quasarframework/quasar#7097]
__log__

Error from chokidar (/var/www/my-repository/node_modules/quasar/src/plugins): Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/my-repository/node_modules/quasar/src/plugins/Platform.js'
Error from chokidar (/var/www/my-repository/node_modules/quasar/src/plugins): Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/my-repository/node_modules/quasar/src/plugins/Platform.json'
Error from chokidar (/var/www/my-repository/node_modules/quasar/src/plugins): Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/my-repository/node_modules/quasar/src/plugins/Screen.js'
Error from chokidar (/var/www/my-repository/node_modules/quasar/src/plugins): Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/my-repository/node_modules/quasar/src/plugins/Screen.json'
Error from chokidar (/var/www/my-repository/node_modules/quasar/src/plugins): Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/my-repository/node_modules/quasar/src/plugins/SessionStorage.js'
Error from chokidar (/var/www/my-repository/node_modules/quasar/src/plugins): Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/my-repository/node_modules/quasar/src/plugins/SessionStorage.json'
Error from chokidar (/var/www/my-repository/node_modules/quasar/src/utils): Error: ENOSPC: System limit for numb

_____quasar info____

 quasar - 1.11.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.8.10 -- Quasar Framework local CLI
  @quasar/extras - 1.8.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.9.6 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.8.3 -- TypeScript is a language for application scale JavaScript development

Quasar App Extensions
  *None installed*

Networking
  Host -*******i
  wlan0 -

**Comment by pdanpdan** [comment]
https://www.google.com/search?q=number+of+file+watchers
