### ISSUE TITLE
Add resize feature in QDrawer

### ISSUE THREAD

**Issue by joyalkj** [quasarframework/quasar#7099]
In most of the desktop applications, the sidebars are resizable,(eg: VS Code), where the width can be changed dynamically using the mouse. Requesting to add **`resizable`** or similar behavior to `QDrawer` or similar components to adjust the component width dynamically, where the mouse pointer changes when we hover over the borders/margin and can be dragged to change the size.

**Comment by pdanpdan** [comment]
This is something that can be easily done in your code - add a vertical div at the side of your drawer (and style it as you see fit), put a VTouchPan directive on it and change the with of the drawer.

**Comment by joyalkj** [comment]
@pdanpdan Thanks for your reply. I have tried your steps, It worked with the below tree
```
<q-drawer>
<q-list></q-list>
<div></div>
</q-drawer>
```
But not when we add scroll area around the q-list as below, because the div wont be displayed right next to the list
```
<q-drawer>
<q-scroll-area>
<q-list></q-list>
<div></div>
</q-scroll-area>
</q-drawer>
```
Or with the below approch
```
<q-drawer>
<q-scroll-area>
<q-list></q-list>
</q-scroll-area>
<div></div>
</q-drawer>
```
However I could do that in the Chrome element tree, when I add `display: flex` in the parent div which is just inside the `aside` tag in the rendered tree, but I couldt do that from a vue source file

**Comment by julie777** [comment]
Why is this closed? It would allow running on a desktop to have a normal desktop experience.

**Comment by rstoenescu** [comment]
@julie777 like explained above, it's something really easy that can be done devland through the touch-pan directive https://quasar.dev/vue-directives/touch-pan

**Comment by julie777** [comment]
Although it may be accomplished "easily" by adding other code, it would be even simpler and much more obvious if it was built in. Don't get me wrong, I love the way Quasar works. I do think the learning curve could be simplified with some improvements to both functionality and documentation.

**Comment by balage1551** [comment]
Really it is easy, but here is a complete example of doing it (not best programmed, but I'm still learning Vue3 Composition API):
It allows the right drawer to be resized between 200 and 800 pixel width.

The HTML:
```HTML
<div id="q-app" style="min-height: 100vh;">
  <div class="q-pa-md">
    <q-layout view="hHh Lpr lff" container style="height: 300px" class="shadow-2 rounded-borders">
      <q-header elevated class="bg-black">
        <q-toolbar>
          <q-toolbar-title>Header</q-toolbar-title>
          <q-btn flat @click="drawerRight = !drawerRight" round dense icon="menu"></q-btn>
        </q-toolbar>
      </q-header>

     

      <q-drawer
        side="right"
        v-model="drawerRight"
        show-if-above
        bordered
        :width="drawerWidth"
        :breakpoint="500"
        class="bg-grey-3"
      >
        <div class="row fit">
          <!-- The trick is here: adding the resize div and applying v-touch-pan on it. -->
          <div  style="width: 6px; cursor: col-resize;" class="bg-primary"
               v-touch-pan.horizontal.prevent.mouse.preserveCursor="handlePan"
               ></div>
          <q-scroll-area class="fit col">
            <div class="q-pa-sm">
              <div v-for="n in 50" :key="n">Drawer {{ n }} / 50</div>
            </div>
          </q-scroll-area>
        </div>
      </q-drawer>

      <q-page-container>
        <q-page padding>
          <p v-for="n in 15" :key="n">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit nihil praesentium molestias a adipisci, dolore vitae odit, quidem consequatur optio voluptates asperiores pariatur eos numquam rerum delectus commodi perferendis voluptate?
          </p>
        </q-page>
      </q-page-container>
    </q-layout>
  </div>
</div>
```

And the JS:
```js
const { ref } = Vue

const app = Vue.createApp({
  setup () {
    const drawerWidth = ref(200)
    let originalWidth 
    let originalX
    return {
      drawerRight: ref(false),
      drawerWidth,
      handlePan ({ evt, ...newInfo }) {
        if (newInfo.isFirst) {
          originalWidth = drawerWidth.value
          originalLeft = newInfo.position.left
        } else {
          const newDelta = newInfo.position.left - originalLeft
          // Should add (instead of subtract) for left drawer
          const newWidth = Math.max(200,Math.min(800,originalWidth-newDelta))
          drawerWidth.value = newWidth
        }
      }
    }
  }
})

app.use(Quasar, { config: {} })
app.mount('#q-app')
```

Hope it will help!

**Comment by MichaelJCole** [comment]
This code doesn't work and was not a good use of time.

This is an obvious feature for the drawer, but Quasar like you to struggle for it.

An alternative solution is to use the QSplitter: https://codepen.io/metalsadman/pen/YzPgKML

**Comment by pdanpdan** [comment]
Yes, you must struggle the whole 1 line of html and 5-6 lines of js :)

https://codepen.io/pdanpdan/pen/mdLjrGL?editors=1100

**Comment by MichaelJCole** [comment]
Actually, there was considerably more work than that as the QSplitter doesn't set the height of it's children correctly.  Maybe Quasar is best suited to codepen apps?
