### ISSUE TITLE
QInputFrame warning: 'Injection "__field" not found'

### ISSUE THREAD

**Issue by jskrzypek** [quasarframework/quasar#710]
### Software version

Quasar: quasarframework/quasar-edge#2e51575
OS: Mac OS X Sierra 10.10.25
Node: 6.10.3 & 8.1.4
NPM: 3.10.10(Node 6) & 5.0.3(Node 8)
Browsers: Chrome Version 60.0.3112.66 (Official Build) beta (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
```
[Vue warn]: Injection "__field" not found

found in

---> <QInputFrame>
       <QUploader>
         <QModal>
           <PageGallery> at /Users/jskrzypek/dev/my-vue-project/src/pages/storage/Gallery.vue
             <QScrollArea>
               <QLayout>
                 <PageStorage> at /Users/jskrzypek/dev/my-vue-project/src/pages/storage/Storage.vue
                   <QLayout>
                     <PageDashboard> at /Users/jskrzypek/dev/my-vue-project/src/pages/dashboard/Dashboard.vue
                       <App> at /Users/jskrzypek/dev/my-vue-project/src/App.vue
                         <Root>
```
### What were you expecting?
No error
### What steps did you take, to get the error?
This happens at page load. As you can see above I have an uploader in a modal on a sub-page. I don't know what exactly is causing the error.

Happy to create a repro, I'll try to set one up later if you can't reproduce the bug.

**Comment by rstoenescu** [comment]
Yes, please provide a repro. Should be easy to fix then. Thanks.

**Comment by jskrzypek** [comment]
Ok here's the repro repo: https://github.com/jskrzypek/q-input-frame-bug-repro

Instructions: 
Clone, `npm install`, run `quasar dev`, and then open the console and navigate to http://localhost:8080/#/my-uploader, the error should show up there.

**Comment by rstoenescu** [comment]
I was just notified of a bug in Vue 2.4.x which breaks inject props.
Downgrade to Vue 2.3.x in your project. Thanks.

**Comment by pdanpdan** [comment]
The bug in vue is vuejs/vue#6093, but it's about broken inject on merge.
I think the warn on missing inject property will stay after the fix.

**Comment by jskrzypek** [comment]
Great, thanks 👍

**Comment by anhnhoktvn** [comment]
The bug in vuejs/vue [#6093](https://github.com/vuejs/vue/issues/6093) has been fixed but I still got the same problem in quasar.
-------
Version:
Vue: 2.4.2
Quasar: edge

**Comment by rstoenescu** [comment]
Like the forum announcement says: do not upgrade to Vue 2.4.x yet.
Waiting PR to be merged: https://github.com/vuejs/vue/pull/6322

Please follow this forum thread: http://forum.quasar-framework.org/topic/616/do-not-upgrade-to-vue-2-4-x-yet

**Comment by guyulmaz** [comment]
https://github.com/vuejs/vue/pull/6322 
merged!!!

**Comment by rstoenescu** [comment]
Ok, now waiting for the PR to get into an official Vue release and then v0.14.5 will use this new functionality.

**Comment by Zyles** [comment]
Same problem with Vue 2.3.3 and q-input ...

**Comment by rstoenescu** [comment]
@Zyles Vue up to 2.3.4 is safe from this warning. Please check if you indeed use Vue 2.3.3.

**Comment by syntacticsolutions** [comment]
I have the same problem when I am using autocomplete. I don't get the error if I just use <q-search></q-search>, but then this shows up in my input on page load.

function boundFn(a) {    var l = arguments.length;    return l      ? l > 1        ? fn.apply(ctx, arguments)        : fn.call(ctx, a)      : fn.call(ctx)  }

**Comment by rstoenescu** [comment]
@syntacticsolutions Please upgrade to latest Vue.

**Comment by syntacticsolutions** [comment]
Thanks, I did that and everything is working now. :)
