### ISSUE TITLE
Iphone (Safari or Chorome) cann't display date. 

### ISSUE THREAD

**Issue by PawelNackiewicz** [quasarframework/quasar#7100]
**Describe the bug**
On mobile devices from Apple (tested on iphone 7 and iphone 5) cann't correct display object type date. This object before display is parsed by [toLocaleDateString] (https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Date/toLocaleDateString) method. 

**Codepen/jsFiddle/Codesandbox (required)**
[codepen](https://codepen.io/pawelnackiewicz/pen/abvxZWv)

**To Reproduce**
Call function parseDate(date) in IOS device. 

**Expected behavior**
Date should be real date. Actual it returns invalid date.
**Screenshots**
[image from chrome on iphone 7](https://ibb.co/VMGK7RB)

**Platform (please complete the following information):**
iOS: iphone 7 (chrome and safari) iphone 5 (safari)

**Comment by pdanpdan** [comment]
Hello.
In your code there is nothing that has to do with Quasar.
We are not responsible for what Apple does, please open your report there.
