### ISSUE TITLE
Android remote debugging is changed

### ISSUE THREAD

**Issue by nulele** [quasarframework/quasar#7102]
Hi,

the instructions at page https://quasar.dev/quasar-cli/developing-cordova-apps/troubleshooting-and-tips#Android-remote-debugging has become obsolete becouse now there’s this new “chrome://inspect/#devices” interface... even if I have difficulties to make it work as described in my related post https://forum.quasar-framework.org/topic/5983/cannot-debug-android-pwa-on-linux-with-chrome-network-panel-is-blank?_=1590395662621 in the forum.

Thanks

**Comment by Jake21x** [comment]
Im also finding a way for this, but this issue is related on Chrome version,Android Webview version
