### ISSUE TITLE
QEditor & source view formatting

### ISSUE THREAD

**Issue by turigeza** [quasarframework/quasar#7103]
**Is your feature request related to a problem? Please describe.**
I would like to format the source in the editor and display it formatted. For this I need to apply css styles `white-space: pre-wrap;` to the source view only. Currently I have no way of doing this.

**Describe the solution you'd like**
Option 1
The simplest. Please add a class to the editor `isViewingSource` when it is in source mode.

Option 2
Allow me to customise the toolbar in source mode as well as provide a slot to replace `q-editor__content` in source mode. This would enable one to implement other source editors such as CodeMirror or https://ace.c9.io/

**Describe alternatives you've considered**
I have tried to add `@mousedown="editorMouseDown"` on the editor to determine of the $ref.editor.isViewingSource true on every click on the toolbar and add class to the editor myself but I can not get it work. @mousedown="editorMouseDown" will no be called if you click on the toolbar. 
You can not watch $ref.editor.isViewingSource nor can one use it in a computed property and also isViewingSource is not in the docs so I assume it is not meant to be used. 

**Additional context**
Simple formatting of source code achieved with  js-beautify and adding `white-space: pre-wrap;`.
<img width="666" alt="Screenshot 2020-05-25 at 14 22 51" src="https://user-images.githubusercontent.com/9335740/82816588-4f894a00-9e93-11ea-8422-f28c4361a65e.png">

Please and Thank you ! : )

**Comment by rstoenescu** [comment]
In v1.12.0 it will add the class "q-editor--source" (when viewing source) or "q-editor--default" otherwise.

**Comment by a4amaan** [comment]
how you used white-space: pre-wrap;?
