### ISSUE TITLE
QTabs: Prev/Next button next to tabs

### ISSUE THREAD

**Issue by hraq** [quasarframework/quasar#7104]
**Problem**
Currently prev/next icons are on over tabs. On some cases trying to press next, there is possibility to miss click and instead to scroll tabs open new tab. It's also for some user confusing and cannot read or see correctly that there is chevron top of text.

**Solution**
Adding new prop "icon-position" with possible value are "over" and "outside", where "over" is default.

End result could shown something like this:
![image](https://user-images.githubusercontent.com/1770919/82816139-47390b00-9ea3-11ea-980d-d5f3ccb1cf7e.png)

This should only alter position of icon.

**Comment by slowaways** [comment]
I understand this Feature Request but the title is not clear.

Maybe the background of Prev/Next button slightly opaque will improve the indication of the click area.

**Comment by rstoenescu** [comment]
We can't have the prev/next buttons "outside" because it would mean that we always need to allocate space for them (otherwise we bump into an infinite loop while detecting if it should display the buttons).

Exploring some ideas of better highlighting the prev/next buttons.

**Comment by webnoob** [comment]
Will be available in 1.12.9
