### ISSUE TITLE
Virtual scroll does not work in Firefox and Safari when using <colgroup>

### ISSUE THREAD

**Issue by vojvodics** [quasarframework/quasar#7107]
**Describe the bug**
Virtual scroll does not work when using the `<colgroup>` element inside the table. It works in chromium based browsers, but not in Firefox or Safari. Try out the example provided below. If you comment out the `<colgroup>` part everything works fine. It does not work with the fixed height nor when scrolling on the window object. (both examples provided in pen)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/vojvodics/pen/ZEbZoOW

**To Reproduce**
Try scrolling down the table.

**Expected behavior**
You should see rows instead of placeholders.

**Screenshots**
/

**Platform (please complete the following information):**
OS: /
Node: /
NPM: /
Yarn: /
Browsers: Tested on Firefox, Safari, Chrome and Brave. It works as expected in Chrome and Brave (and probably other chromium-based browsers)
iOS: /
Android: /
Electron: /

**Additional context**
/

**Comment by pdanpdan** [comment]
Hello.
It looks like Chrome and Firefox+Safari disagree on the height of the colgroup element :)
I extended the utility class `.q-virtual-scroll--skip` to also skip processing the size of the elements in before and after slots, so when the new quasar release will be ready you'll have to add that class to the colgroup element.

**Comment by vojvodics** [comment]
Awesome!
Thanks @pdanpdan

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.12.0.
