### ISSUE TITLE
QForm - validate method is no longer called

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#7112]
**Describe the bug**
Since a recent change, the`validate` method is not called recursively on each component but, only on components having a root dom element with `.q-field` class... Unfortunaly, i've create my own components with custom `validate` method. 

I'm aware that it ils totaly my fault, because it is not a good practice to use some unexposed functionnality  from your api...

But is it possible to introduce another API to inject custom validator ? (provide / inject ?)

**Additional context**
Thanks for your great job.

**Comment by rstoenescu** [comment]
Good point.

In Quasar v1.12.0, you'll be able to attach "q-validation-component" CSS class at the root element of your custom component (which also has the "validate()" method) and it'll get recognized by QForm.
