### ISSUE TITLE
QInfiniteScroll - detecting loading state

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#7117]
**Is your feature request related to a problem? Please describe.**
I would like to display the content within the infinite scroll differently if it is loading - thus I would like some way of determining if the QInfiniteScroll is loading.

**Describe the solution you'd like**
Maybe QInfiniteScroll could take a prop called loading that could then be read to determine the loading state. 

**Describe alternatives you've considered**
Alternatively I can have my own data variable track it. 

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

But you already have a way through the required `@load` event. It gets triggered when something new should load and you're the one calling `done()` on it when that content has loaded. So you're the one controlling the loading state...
