### ISSUE TITLE
custom route ssr not showing with ssr + pwa mode

### ISSUE THREAD

**Issue by jeremyriverain** [quasarframework/quasar#7119]
Hi,

I have an issue with my app and made a repository on Github to explain it.
https://github.com/jeremyriverain/quasar-test

This repo is a minimal Quasar Project, highlighting my issue.

Launch the app with `quasar dev -m ssr` and open `http://localhost:8080/sitemap.xml`.

When `ssr.pwa` is set to false in `quasar.conf.js`, the route defined in `ssr-ssr/extension.js` works fine. I can get the content of `http://localhost:8080/sitemap.xml`.

But when I set `ssr.pwa` to true, then, when I browse to `http://localhost:8080/sitemap.xml`, I only get white screen, nothing else.

When SSR is combined with PWA, it's like extension.js is not called anymore.

Is this behavior expected by Quasar or is it a bug ? Is it related to PWA cache ? Do I have to write a custom service worker to make it work properly ? 

Jérémy R.

**Comment by rstoenescu** [comment]
Hi,

This is not a bug. The client takes over as PWA so everything is served from cache. There's also a "fallback" route in place (points to a generated offline.html based on your /src/index.template.html). Either: a) disable the default fallback (quasar.conf.js > pwa > workboxOptions: { navigateFallback: false }) but you lose an important aspect of the pwa which is offline support or b) configure the caching strategy for your special asset (sitemap.xml) to be NetworkFirst:

```
// quasar.conf.js
pwa: {
  workboxOptions: {
     runtimeCaching: {
        urlPattern: '/sitemap.xml',
        handler: 'NetworkFirst'
     }
   }
}
```

**Comment by jeremyriverain** [comment]
Hi,

The 1st approach works fine. Not the 2nd one. With that approach, I still have white screen. An HTML response is sent and not the XML one expected by the route configured in src-ssr/extension.js

Anyway, I'm quite happy with the 1st option. I don't need offline support so much. So I can let it like this for now, until I find a better solution. I imagine I need to learn more about PWA and workboxOptions. 

Thank you for helping me,
Jérémy
