### ISSUE TITLE
SSR + PWA offline.html and SSR template injection differentiation

### ISSUE THREAD

**Issue by dmitry** [quasarframework/quasar#7120]
**Is your feature request related to a problem? Please describe.**

I have SSR + PWA app.

While I'm reloading page it takes generated `offline.html` with the following contents:

```html
    {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
```

Takes it from the service worker storage.

Html template contents I'm using:

```
    <% if (htmlWebpackPlugin.options.ctx.mode.ssr) { %>
    {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
    <% } %>
```

I'd like to generate PWA `offline.html` without this contents, but the problem is that `cfg.__html.variables` is identical while server injection and `offline.html` generation.

Solution might be to add some additional value to the `/ssr/html-template` in `getIndexHtml` function `htmlWebpackPlugin` `option`, so it will be hint I can use inside the htmlWebpackPlugin

At the moment solution is to use specific webpack options (which are not available during the compilation of the SSR template):

```
    <% if (htmlWebpackPlugin.options.ctx.mode.ssr && !htmlWebpackPlugin.options.filename) { %>
    {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
    <% } %>
```

The contents of the `cfg.__html.variables` while it generates both HTMLs (for SSR and PWA `offline.html`):

```javascript
{
  ctx: {
    dev: true,
    prod: false,
    mode: { ssr: true, pwa: true },
    modeName: 'ssr',
    target: {},
    targetName: undefined,
    emulator: undefined,
    arch: {},
    archName: undefined,
    bundler: {},
    bundlerName: undefined,
    debug: false,
    publish: undefined,
    vueDevtools: false
  },
  process: {
    env: {
      NODE_ENV: 'development',
      CLIENT: true,
      SERVER: false,
      DEV: true,
      PROD: false,
      MODE: 'ssr',
      VUE_ROUTER_MODE: 'history',
      VUE_ROUTER_BASE: '/',
      APP_URL: 'https://localhost:8080/',
      SERVICE_WORKER_FILE: '/service-worker.js'
    }
  },
  productName: 'APP',
  productDescription: 'Description'
}
```

**Comment by rstoenescu** [comment]
Hi,

Thanks for filing this request. Will be available in "@quasar/app" v2 (to be released soon -- no worries, no major breaking changes - 5 min max needed to upgrade to it).
