### ISSUE TITLE
Add keyboard navigation to QTable

### ISSUE THREAD

**Issue by nahuel** [quasarframework/quasar#7122]
For some desktop usages and improved accessibility it will be nice to have Keyboard focus/navigation enabled in QTable, e.g. arrows keys and pgup/pgdown.

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/table#Keyboard-navigation

**Comment by nahuel** [comment]
sorry, missed that example (but I still think it should be a QTable prop).

**Comment by pdanpdan** [comment]
There is no standard way to navigate a table. That means you have to adjust it to your particular case.
