### ISSUE TITLE
Horizontal virtual scroll inside virtual scroll doesn't works fine

### ISSUE THREAD

**Issue by AEiosApp** [quasarframework/quasar#7123]
**Describe the bug**
I'm trying to make a vertical list of rows, where each row is horizontal list.
So I configured a vertical virtual scroll with :key="idx" and put inside a horizontal virtual scroll with :key="idy".

I have a double array of items heavySubCats[a][b].
When I try to set items for horizontal list :items="heavySubCats[idx]" (where idx is a key of a vertical list) - it doesn't work, but if I'll set a constant instead of the index :items="heavySubCats[2]"  - it works.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/antonsvens/sfvkmbc5/9/

**To Reproduce**
1. Go to the jsfiddle link above, run - you will only see vertcal list titles
2. In the HTML tab, line #28 replace
     :items="heavyItems[idx]"
with
     :items="heavyItems[3]"
or any other number instead of idx, run - you will see horizontal scroll list in each row

**Expected behavior**
I need to pass index of the row of vertical list to the horizontal list

**Comment by pdanpdan** [comment]
Hello. Please use the discord channel or the forum for help requests.
