### ISSUE TITLE
Upgrade to 1.12.o breaks loader

### ISSUE THREAD

**Issue by RonchettiAssociati** [quasarframework/quasar#7126]
**Describe the bug**
After upgrading to 1.12 I get following error in quasar dev

You may need an additional loader to handle the result of these loaders.
| //
| //
> import date as quasarDate  from 'quasar/src/utils/date.js';;

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce*

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS: mac osx catalina

**Additional context**

**Comment by rstoenescu** [comment]
Hi, can u give more details pls? What mode are you developing with? Are you using modern build, TS? There’s a template in place when opening a ticket...

**Comment by rstoenescu** [comment]
Nvm, reproduced. Fix will come shortly.

**Comment by rstoenescu** [comment]
For now, just don't use "as newName". Just `import { date } from 'quasar'`.

**Comment by rstoenescu** [comment]
Seems like webpack's acorn doesn't like import + renaming.

**Comment by rstoenescu** [comment]
Fix coming.

**Comment by rstoenescu** [comment]
Fix will be available shortly in "@quasar/app" v1.9.1.

**Comment by rstoenescu** [comment]
Please upgrade to "@quasar/app" v1.9.1.
Thanks for reporting!

**Comment by RonchettiAssociati** [comment]
It works now. Thank YOU Ravzan.

Great framework and outstanding support!

**Comment by rstoenescu** [comment]
If you or your company can afford to drop a buck, it'd be much appreciate it -> https://donate.quasar.dev

**Comment by RonchettiAssociati** [comment]
Ok, I have contributed 250 USD. Let me talk to my partners and see if we can make this recurring in the future.

**Comment by rstoenescu** [comment]
@RonchettiAssociati thank you! Every donation really matters!
