### ISSUE TITLE
Option to load veux store before the router

### ISSUE THREAD

**Issue by timouwerkerk** [quasarframework/quasar#7128]
Hi,

I have been using the Vuex plugin pathyfy now for the automatic creation of mutations, actions, getters etc for my my state.
In other non Quasar projects I have had no problems and tried to implement it the same way.
However, when I implement it in Quasar I get the following errors in the console and it won't work:

[Vuex Pathify] Unable to expand wildcard path 'search/*':
    - The usual reason for this is that the router was set up before the store
    - Make sure the store is imported before the router, then reload

However, I can't seem to get the Vuex store loaded before the router, I've looked in the .quasar/app.js and .quasar/client-entry.js

**Comment by metalsadman** [comment]
the store is created first before the router in .quasar/app.js judging by these lines
```js
const store = typeof createStore === 'function'
    ? await createStore({Vue})
    : createStore
  
  const router = typeof createRouter === 'function'
    ? await createRouter({Vue, store})
    : createRouter
```
tested the plugin and it works fine, although i haven't tried using wildcards like in your log.
just simple
```js
computed: {
  example: get('example/sample')
}
```
gave me the result.

**Comment by timouwerkerk** [comment]
@metalsadman It seems the get('example/sample') is working indeed.
However I actually never use the get() I often use the method ..sync(), this will automaticly generate mutations for all state properties.

store/index.js

`import state from './state'
import * as getters from './getters'
import * as actions from './actions'

import { make } from 'vuex-pathify'

const mutations = make.mutations(state)

export default {
  namespaced: true,
  getters,
  mutations,
  actions,
  state
}`

and then in component

 `computed: {
    ...sync('example/*')
  },` 

This will trigger the error.

However, I just found out that instead of the fully automation, just use the sync method per state property does work.

` computed: {
    example: sync('example/test'),
    example2: sync('example/test2'),
  }`

So it seems to be an issue with the spread operator.

**Comment by metalsadman** [comment]
@timouwerkerk still working for me using spread.
state.js
```js
export default function () {
  return {
    sample: null,
    msg: 'hello'
  }
}
```
component
```html
{{ example }}
    <q-input
      v-model="msg"
      label="test"
    />
```
```js
computed: {
    example: sync('example'),
    ...sync('example/*')
  }
```

**Comment by rstoenescu** [comment]
The title reflects what we actually do in Quasar App CLI so closing. The details do not reflect any bug in Quasar's own code.
