### ISSUE TITLE
SPA Modern not build

### ISSUE THREAD

**Issue by mila76** [quasarframework/quasar#7131]
**Describe the bug**
If i try to build with modern feature enabled receive 4 times a similar error

js/5.128fc588.js from Terser
Unexpected token: punc ()) [js/5.128fc588.js:288,6]

I upgraded with npn update not a new project
run dev work just fine

**Platform (please complete the following information):**
OS: Windows 7
Node: 12.16.1
NPM: 6.13.4

**Comment by rstoenescu** [comment]
Hi,

Can you supply a reproduction repo pls? There's no chance this will ever get figured out otherwise. Thanks.

**Comment by mila76** [comment]
here one test https://github.com/mila76/clienttest
i managed to figure out the problem on store/index.js  and particular with the mutations updatePlan
removing that function all build
no problema "compiling" for dev

**Comment by mila76** [comment]
Here the problem:
`
const index = state.plans.findIndex(
  (stored) => stored.id_plan === payload.id_plan,
);
`
removing the comma al work... but need to remove eslint on trailing comma
i think is not a new bug... other people having this issue from year?

here a link that helped https://stackoverflow.com/questions/54380816/unexpected-token-punc-when-building-for-production

**Comment by rstoenescu** [comment]
Thanks for the reproduction repo. I'll get to the bottom of this.

**Comment by rstoenescu** [comment]
Fixed in "@quasar/app" v1.9.2 -- just released it.
Thanks for reporting and helping reproduce!

**Comment by mila76** [comment]
Thanks to you for the hard work on quasar.
Beacause Trailing commas in function calls are not an ES6 feature your fix remove the comma or put Tenser on a more modern setting?

**Comment by rstoenescu** [comment]
It was actually an unnecessary thing to set the ecma level. What I should've done from the beginning is to either set the highest level possible or don't set it at all. Went with the safer approach of letting terser be able to use all its "knowledge". Under the covers it uses acorn v7 which has a default of 2020. This doesn't mean it will break anything from what we're trying to achieve. On the contrary. It won't trigger useless errors on newer syntax.
