### ISSUE TITLE
SVG icons inside of QNotify have broken layout [chrome only]

### ISSUE THREAD

**Issue by cmcleese** [quasarframework/quasar#7132]
**Describe the bug**
SVG icons inside of QNotify have broken layout.
When a left icon is used with QNotify, the width is not calculated correctly resulting in a the svg icon taking up most space in the notify container and sometimes pushing out the elements.

__Note: Issue only seems to occur with Chrome.__

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/broken-qnotify-quasar-pqehf

**To Reproduce**
1. Go to codesanbox and run
2. Click on 'Show Notification With Icon'
3. Notice broken layout
4. Click on 'Show Notification Without Icon'
5. Notice correctly displayed layout without icon.

See `pages/index.vue` for code

**Expected behavior**
The QNofity when used with a left icon should have its width set correctly.

**Screenshots**
__Chrome (83.0.4103.61)__
![screenshot](https://user-images.githubusercontent.com/2061466/83247933-96818300-a1a4-11ea-8d67-61ba467dfb3f.png)
----
__Chrome Canary (85.0.4158.5)__
![screenshot2](https://user-images.githubusercontent.com/2061466/83248273-20c9e700-a1a5-11ea-9bac-0cf1d5b95949.png)
-----
__Firefox (76.0.1)__
![screenshot3](https://user-images.githubusercontent.com/2061466/83248521-78685280-a1a5-11ea-9d23-bfc09f7a701d.png)
-----

**Platform (please complete the following information):**
Quasar: v1.12.0
Browsers: Chrome 83.0.4103.61,  85.0.4158.5

**Comment by rstoenescu** [comment]
I'm on Chrome Version 83.0.4103.61 (Official Build) (64-bit). But can't reproduce :/

**Comment by rstoenescu** [comment]
Do you have any browser extensions that might do funny stuff?

**Comment by cmcleese** [comment]
I'm not sure what other information I can provide or what else I could do to test..

**Comment by cmcleese** [comment]
> Do you have any browser extensions that might do funny stuff?

I tried in incognito mode and same result.

**Comment by rstoenescu** [comment]
@cmcleese What's your OS?

Anyone else: can you reproduce this?

**Comment by cmcleese** [comment]
> @cmcleese What's your OS?
> 
> Anyone else: can you reproduce this?

Windows 10 pro x64  v:1909

**Comment by webnoob** [comment]
This is fine for me as well:

Windows 10
Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by yusufkandemir** [comment]
Everything seems fine for me as well.

OS: Windows 10 v2004
Browser: Edge Chromium Version 84.0.508.0 (Official Build) dev (64-bit)

**Comment by cmcleese** [comment]
Ok seems like its just me and all versions of Chrome which makes no sense.

**Comment by yusufkandemir** [comment]
I can confirm that it also works as expected with non-Chromium Edge too.

Microsoft Edge 44.19041.1.0 (EdgeHTML 18.19041)

**Comment by hawkeye64** [comment]
Works fine for me too
![image](https://user-images.githubusercontent.com/10262924/83264235-0a0f9a00-a17d-11ea-9a89-1015b314f454.png)

**Comment by hawkeye64** [comment]
The codesandbox referenced in link above does not have icons loaded properly
![image](https://user-images.githubusercontent.com/10262924/83264508-696daa00-a17d-11ea-9e27-65997965bdc7.png)

**Comment by cmcleese** [comment]
> > The codesandbox referenced in link above does not have icons loaded properly
> > ![image](https://user-images.githubusercontent.com/10262924/83264508-696daa00-a17d-11ea-9e27-65997965bdc7.png)

I didnt bother to replace the menu button link to use SVG. So it can be ignored.

**Comment by cmcleese** [comment]
I just tried in a VM with Windows 10 and Chrome.
Seems like something is wrong with local environment specific to Chrome.
I'm going to guess this can probably be closed as it is only happening with me.

Thanks for everyone who tested.
