### ISSUE TITLE
There is some problem with QIntersection API section [docs]

### ISSUE THREAD

**Issue by pratik227** [quasarframework/quasar#7133]
**Describe the bug**

There is some issue with that first Tab It's not showing anything I think it's misplaced.

![screenshot-quasar dev-2020 05 29-18_36_38](https://user-images.githubusercontent.com/34883558/83262935-630e1b00-a1db-11ea-936b-be7769f4860d.png)

**Comment by rstoenescu** [comment]
Thanks for reporting. Will get it fixed shortly.

**Comment by rstoenescu** [comment]
Fixed and docs redeploying. Will work again in 5-10 min.
