### ISSUE TITLE
QButton deterministic progress not completed

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#7134]
Hi,

i've been using the q-btn component while i noticed that the progress bar inside the component never complete itself leaving the "last slice of completion" empty.

You can see the problem even in the quasar documentation by trying the example:
https://quasar.dev/vue-components/button#Example--Deterministic-progress

Anyway here's also an example on CodeSandBox:
https://codesandbox.io/s/practical-browser-d4it4?file=/src/components/AmmoManage.vue

**To Reproduce**

- To reproduce the bug in the quasar documentation just click over one of the 3 button under the "deterministic progress" category and watch it carefully the last slice. At first galance you could not notice that foult of the randomic filling value so try different time.

- To reproduce it in the CodeSandBox example just press the button labelled "RELOAD" here the delay between adding the slices is smaller and the slice value is costant on purpose to enfatize the bug.

**Expected behavior**
The bug could be really annoying for someone that base the loading action on small time intervals that want the progress fill the button instead of partially  filling it.

**Platform:**
OS: Windows10
Node :v12.16.3.
Yarn: v1.21.1
Browsers:  Chrome v81.0.4044.138 

**Additional context**
The problem is related to the transition's time and the end premature ending of the loading phase.

**Comment by rstoenescu** [comment]
Hi,

Just set "loading = false" with a bit of delay :)

**Comment by vandelpavel** [comment]
I state that I've made this solution as a case study and for that reason I don't claim my proposal to be integrated into the codebase, but here's a possible fix for the problem.

After inspecting the component's source code I made some changes on **quasar/src/components/btn/QBtn.js** file.

First of all I've added a "transitionTime" **props**:

```js
transitionTime: {
      type: Number,
      default: 600,
      validator: function (value) {
        if (value >= 0) return true;
        else return false;
      },
    },
```

then a **data property**:

```js
timeoutReference: undefined,
```

later I've modified the already existing "percentageStyle **computed property**:

```js
percentageStyle() {
      const val = Math.max(0, Math.min(100, this.percentage));
      if (val > 0) {
        const transitionValue = "transform " + this.transitionTime + "ms";   //modified row
        return {
          transition: transitionValue,
          transform: `translateX(${val - 100}%)`,
        };
      }
    },
```

and for last but not least I've added a **watcher**:

```js
percentageStyle: function () {
      if (typeof this.timeoutReference !== "undefined") {
        clearTimeout(this.timeoutReference);
      }
      this.timeoutReference = setTimeout(() => {
        this.$emit("loading-end", this.percentage);
        this.timeoutReference = undefined;
      }, this.transitionTime);
    },
```

**Little explanation:**
Now anyone could pass a delay property and if not then it remains set on 600ms (the one used before). I simulated the async request using a setTimeout. Once the animation completes, the component emit a **end-loading** event that you can listen and react.

What if I set different percentage values before any completion?" you may ask... Well, I've got you cover! The **timeoutReference** is used to verify that the previous animation is ended and if not it will automatically delete the previous timeout.
At the end of the day only one evet is emitted wich is the final animation and all others steps will be ignored. 

Heres a **little example** I've made to try it yourself:

```js
<template>
  <div>
    <q-btn
      :loading="reloadBtnLoading"
      label="reload"
      :disable="reloadBtnDisable"
      :percentage="reloadBtnPercentage"
      :transitionTime="reloadBtnTransTime"
      @click="testLoad()"
      @loading-end="endLoading()"
    />
    <q-select
      v-model="model"
      :options="options"
      label="Standard"
    />
  </div>
</template>

<script>
export default {
  data() {
    return {
      reloadBtnDisable: false,
      reloadBtnLoading: false,
      reloadBtnPercentage: 0,
      reloadBtnTransTime: 0,
      model: 500,
      options: [500, 1000, 2000, 3000]
    };
  },
  methods: {
    testLoad() {
      this.reloadBtnDisable = true;
      this.reloadBtnLoading = true;
      this.reloadBtnPercentage = 0;
      setTimeout(() => {
        this.reloadBtnPercentage = 100;
      }, 0);
    },

    endLoading() {
      this.reloadBtnDisable = false;
      this.reloadBtnLoading = false;
      this.reloadBtnPercentage = 0;
    }
  },

  watch: {
    model: {
      handler: function(val) {
        this.reloadBtnTransTime = this.model;
      },
      immediate: true
    }
  }
};
</script>
```
