### ISSUE TITLE
Quasar build succeeds but returns failure exit code on lint warnings

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#7135]
```
Build succeeded

 Build mode........ pwa
 Pkg quasar........ v1.12.2
 Pkg @quasar/app... v1.9.3
 Debugging......... no
 Publishing........ no
 Modern build...... no (legacy ES5); use "--modern" param for ES6+
 ==================
```
but returns exit code of 1.

Taking a look at the code I believe the issue is here: https://github.com/quasarframework/quasar/commit/9208aba636db3db63b1db896529a5ee60d629ef9#diff-c7301393a79065cc0aeb98112917f576

I think most users will always have lint warnings of some type--it would be nice to go back to the original functionality that allows the build to exit with success (0) unless the lint issues are truly errors.  Especially important for build automation toolchains.

Not sure if the version of eslint matters here... but just in case this is what I have in package.json:
```
    "eslint": "^7.1.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.0.0-alpha.5",
```

**Comment by rstoenescu** [comment]
If the lint rules are set as "error" then it's normal to halt the build. However, if you set the lint rules to "warning" then the build won't fail.
If I'm missing something, please reopen with a reproduction repo (codesandbox works too). Thanks.

**Comment by rfox12** [comment]
This was an issue on my end... through a complicated set of circumstances.  The build process emits both stderr and stdout in a way that caused windows powershell to choke on the output as it tee'd it to my build log and the console.  Switched to bash.  All good.
