### ISSUE TITLE
Page cannot refresh

### ISSUE THREAD

**Issue by imohuan** [quasarframework/quasar#7136]
`quasar.config.js` add
``` javascript
module.exports = configure(function(ctx) {
  return {
    devServer: {
      hot: true,
    }
  }
})
```

![image](https://user-images.githubusercontent.com/41279222/83354551-0b62e180-a38c-11ea-96b3-445f5b5b8b43.png)

![image](https://user-images.githubusercontent.com/41279222/83354568-17e73a00-a38c-11ea-859c-e51d135200e7.png)
There was no response from the page

**Comment by pdanpdan** [comment]
Hello. You have no explanation on what your problem is, and the details required in the issue template are missing.
For help requests please head to our discord channel or to the forum.

**Comment by imohuan** [comment]
https://forum.quasar-framework.org/topic/6040/page-cannot-refresh-hot-reload

**Comment by rstoenescu** [comment]
@imohuan there's a ticket template in place for a reason. to not waste both your and our time by asking the basic questions. A reproduction repo (or a [codesandbox](https://codesandbox.quasar.dev)) is also required for your problem.

Now to tackle your problem with the info that you've provided: the HMR itself is not handled by Quasar. It's handled by Webpack and Vue. At best, it's a problem with one of the two. Also check if you've hit the limit of file watchers for your OS.
