### ISSUE TITLE
QImg does not load SVG images without "height" attribute for Firefox

### ISSUE THREAD

**Issue by bernardoalves** [quasarframework/quasar#7137]
**Describe the bug**
Creating a QImg with SVG image without "height" attribute does not work with Firefox (v76.0.1).
Chrome and Safari works fine.

**Codepen**
https://codepen.io/bernardoalves/pen/KKVPMNm

**To Reproduce**
1. Create a SVG QImg without a "height" attribute with Firefox (v76.0.1)

**Expected behavior**
SVG image should show

**Platform:**
Browsers: Firefox (v76.0.1)
OS: macOS Mojave

**Comment by pdanpdan** [comment]
Hello.

Firefox has another of its long standing bugs: https://bugzilla.mozilla.org/show_bug.cgi?id=1328124

See here for a test: https://github.com/whatwg/html/issues/3510#issuecomment-369982529

So the bottom line is: if you want to use SVG in Firefox either pass the `ratio` prop or put both the intrinsic width and height in the SVG.
