### ISSUE TITLE
Counter and maxlength on Dialog plugin input

### ISSUE THREAD

**Issue by sebastien-prudhomme** [quasarframework/quasar#7138]
**Describe the solution you'd like**

I'd like to have a counter and a maxlenght on the text input in dialog plugin.

**Describe alternatives you've considered**

I've made my own dialog plugin component. It works but i think it will be better to have such features in the default dialog plugin component.

**Comment by rstoenescu** [comment]
This and some other props for "prompt" will be available in Quasar v1.12.3.
