### ISSUE TITLE
Firebase Authentication problems with Quasar Framework. 404 error

### ISSUE THREAD

**Issue by Nelzio** [quasarframework/quasar#7139]
After deploying to firebase, the application stop the authentication, I get 404 error and in browser console i have the `Uncaught Error: Network Error`. I think that quasar routes redirect the authentication url to 404 route.

![bugq](https://user-images.githubusercontent.com/23185608/83414930-92f93080-a41e-11ea-9f75-458615a9fd5c.png)

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum. Also check how to configure your server together with vue-router.
