### ISSUE TITLE
iOS soft keyboard problem

### ISSUE THREAD

**Issue by kase-siu** [quasarframework/quasar#7142]
I click the input field first, the soft keyboard is show. And then i click the date-picker to show the PopupProxy component, there is a content cover problem during the keyboard scrolling down, please look at the following image.

Quasar: v1.12.2
iOS: v13
Device: iPhone 8

<img width="375" alt="PNG-image" src="https://user-images.githubusercontent.com/58541962/83483429-3b69cc00-a4d5-11ea-86dc-0e4d239b362b.png">

**Comment by rstoenescu** [comment]
Hi,

Please fill in the required ticket template. A reproduction jsfiddle/codepen is mandatory. Also, what are you developing? A spa/ssr/pwa/cordova/capacitor app? If on Cordova or Capacitor mode, are you using ionic webview or the default one?
