### ISSUE TITLE
QRouteTab enable route matching but disable route navigation

### ISSUE THREAD

**Issue by Nigui** [quasarframework/quasar#7143]
**Is your feature request related to a problem? Please describe.**
I have a QTabs with QRouteTab all matching their own route. I want a specific behaviour when particular QTab is clicked, like doing more things than just navigate. 

**Describe the solution you'd like**
Today there is a single prop to set :
- route to match to be in active state
- route to navigate on component click

So I can't add custom logic on QRouteTab click. It's both features or none.
Could be great to be able to override `@click` event.

**Describe alternatives you've considered**
As an alternative I had to use QTab and handle manually QTab activation based on current route (what QRouteTab actually doing) in order to be able to customize `@click` event.

**Comment by pdanpdan** [comment]
If you want to do something else when clicking on the tab: https://codepen.io/pdanpdan/pen/mdVdBKK?editors=1010

If you don't want to navigate to that route than it's not working.

**Comment by Nigui** [comment]
Thank you, but yes I want to use my own navigation function

**Comment by pdanpdan** [comment]
If it is urgent you can resolve it by making the content of the tab to cover all tab space:
https://codepen.io/pdanpdan/pen/mdVdBKK

But it's just temporary.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
