### ISSUE TITLE
add class fixed-center-right ...

### ISSUE THREAD

**Issue by amitgur** [quasarframework/quasar#7149]
I'm using the class fixed-right-top .. and all of its variants. I found that most of the buttons I used are using also the center, ex. fixed-center-right. like in this test example
https://bandpad.musiced.org.il

here is the css for that one
`
.fixed-center-right {
  position: fixed;
  top: 50%;
  left: 100%;
  transform: translate(-100%, -50%);
}
`
etc..

**Comment by rstoenescu** [comment]
Hi,

First of all, nice & interesting app!

Indeed it would be nice to add all those classes, but the fact is that the CSS would grow a lot (and we do care about the footprint in KB) and we just don't want to bloat the CSS with stuff that most won't even use. At the end of the day, if you think about it, this is simple CSS that can be added when needed only. Quasar's purpose is to offer the foundation building blocks. Sorry if this is not the answer you were looking for.
