### ISSUE TITLE
Modal from top looses position: fixed as soon as input is focussed

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#715]
### Software version
Quasar: beta v0.14
Browsers: Safari iOS
iOS: latest

### What did you get as the error?
This error is only on mobile devices!

The QModal from top (probably other modals as well) they loose their `position: fixed !important;` and the user can scroll above and below the modal and the backdrop, as if the position is relative.
This occurs as soon as the user focuses an input/textarea inside the QModal, or you add a `v-focus` for autofocussing the input upon opening it.

### What were you expecting?
Modal should stay fixed even with input/textarea inside focussed.

### What steps did you take, to get the error?
`<q-modal position="top"><input/></q-modal>`

**Comment by rstoenescu** [comment]
@mesqueeb Does this reproduce if you install https://github.com/apache/cordova-plugin-wkwebview-engine ?

**Comment by rstoenescu** [comment]
Tested myself. It works. Will add this to the docs. Closing.
