### ISSUE TITLE
QBtnToggle does not emit native events

### ISSUE THREAD

**Issue by steersbob** [quasarframework/quasar#7150]
**Describe the bug**
QBtnToggle does not emit native events, despite its API saying it does.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/tb9epqco/7/

The first QBtnToggle has a @click event set. The second uses @click.native.

**To Reproduce**
1. Click the first button (No Popup) -> no notification is spawned
2. Click the second button (Popup) -> notification is spawned

**Expected behavior**
Both buttons to spawn a notification on click

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.12.3
