### ISSUE TITLE
Display issue with focused QSelect in Firefox again

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#7154]
**Describe the bug**
Very similar to #5320. There is a visible artifact on focused `QSelect` controls in Firefox. It looks kinda like a backtick.

Also sometimes upon selection, the selected value has a dotted outline around it. That part seems to be inconsistent.

**Codepen/jsFiddle/Codesandbox (required)**
You can see it in the docs: https://quasar.dev/vue-components/select

**To Reproduce**
1. Go to https://quasar.dev/vue-components/select in Firefox
2. Click on any QSelect

**Expected behavior**
It shouldn't be there.

**Platform**
Quasar:1.12.2
OS: Windows_NT(10.0.18363) - win32/x64
Browsers: Firefox 76.0.1

**Comment by pdanpdan** [comment]
I found the backtick :D, but I cannot reproduce the problem with the option, if you manage to detect the pattern please help me.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.12.3

**Comment by GordonBlahut** [comment]
@pdanpdan 
Here's an example of the dotted outline around a selected item in Firefox:
https://codepen.io/gordonblahut/pen/gOPbmVR

It's using the slot for the selected item, maybe that's the difference?

_Also, it seems to only happen if you select a value when the field is null. If the field already has a value it doesn't happen._

It's hard to inspect what's up because as soon as I switch over to devtools, the outline disappears.

Let me know if I should create a new issue.

**Comment by pdanpdan** [comment]
Good catch on this, thank you. Until it's fixed in the framework add a `key` to the content of the slot - vue reuses the div.
