### ISSUE TITLE
QSelect clearable no longer leaves QSelect focused

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#7157]
**Describe the bug**
Not sure if this is intentional with the recent QSelect focus/blur changes or unintended side-effect.

When tapping the clear button, the following events used to happen (v.1.11.1):
`focus`, `focus`, `input`, `clear`, (QSelect is left in focused state, so after tap outside, `blur`)
Now in v.1.12.2:
`focus`, `input`, `clear`, (QSelect is not left in focused state, so after tap outside, nothing) 

Also, if the field already had focus when the clear button is tapped, the field still loses focus without the `blur` event as well.

This affects validation libraries like Vee-Validate that listen on blur events to validate.

**Codepen/jsFiddle/Codesandbox (required)**
v.1.11.1: https://codepen.io/gordonblahut/pen/xxZxzdE
v.1.12.2: https://codepen.io/gordonblahut/pen/yLeLEMd

**To Reproduce**
1. Go to the codepens
2. Click on the clear button
3. Click outside the field
4. v1.11.1: validation is displayed, v1.12.2: no validation is displayed

**Expected behavior**
I expected behavior to be unchanged, but my expectation could be wrong if this new behavior is intentional.

**Platform (please complete the following information):**
Browsers: Firefox, Chrome

**Additional context**
If it's intentional then I can workaround it but no sense in setting up a workaround if it's a legitimate bug.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Fix will be available in "quasar" v1.12.3.
