### ISSUE TITLE
notify - Out-of-the-box-types

### ISSUE THREAD

**Issue by ME-CLASS** [quasarframework/quasar#7158]
Text is not properly formatted for the notify plugin's Out-of-the-box-types examples.

**Comment by rstoenescu** [comment]
Hi,

Can you be more specific of what you think it's wrong? The description is pretty vague.

**Comment by pdanpdan** [comment]
When using default notification types (using SVG icons as in docs) the icons are very small because they are shrinked by the padding-right.

**Comment by rstoenescu** [comment]
Upon some discussion, seems like a bug in Chrome 84 beta. But regardless, we'll bulletproof QIcon.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.12.4.
