### ISSUE TITLE
Installation stoped @ sudo npm install 

### ISSUE THREAD

**Issue by augmen** [quasarframework/quasar#716]
![screen shot 2017-07-15 at 16 16 35](https://user-images.githubusercontent.com/11497036/28238823-c4a9b3b2-6979-11e7-83de-6102e76922a5.png)
I am run the command on Mac terminal after installing node js and Nom .

$ sudo  npm install -g quasar-cli
$ quasar init <folder name>
$ cd <folder name>
$ sudo npm install

the installation stopped after fethmetadata : map registry to url
[](url)

**Comment by rstoenescu** [comment]
This is purely an NPM issue. Please file an issue for NPM itself.
Might be a lazy npm server.. You might want to change the npm server that you are using.
