### ISSUE TITLE
body-cell-[name] slot should have precedence over body-cell slot

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#7160]
First of all, thank you for great framework. 🙏 

**Describe the bug**
It is common that more specific things have precedence over general ones.. see CSS rules for example, and it makes sense why it is so. 
Therefore I would expect also same for cell slots, named one should be applied over general one.
This is not happening and solving it makes a lot of extra code and effort.
I want to have some basic template for cell "body-cell slot" and in some cases, for some columns I need to override this by `body-cell-[name] slot`. It is not happening currently.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luckylooke/pen/PoZwqeB

**To Reproduce**
- see the template, both slots are specified
- see the result, only general one is applied

**Expected behavior**
template v-slot:body-cell-name to be applied for "name" column cells

**Platform (please complete the following information):**
any, codepen is platform agnostic I think

**Additional context**
I expect that same happen for header cells and should be corrected too.

I am willing to try to make MR during the weekend once one of the framework representatives will agree with the change.

Thank you, happy coding 👍

**Comment by metalsadman** [comment]
@luckylooke it's specified in the api description `body-cell: Slot to define how all body cells look like; Suggestion: QTd`, what you could do is just use body-cell-[name] with conditions. ie. https://codepen.io/metalsadman/pen/VweYjgR

**Comment by luckylooke** [comment]
Thank you @metalsadman for your input. I know this may be the option but I do not like it. Imagine that default cell is defined in some component and other are passed from outside, in such situation your solutions are getting even uglier... having correct precedence would produce nicer/cleaner/readable code. I have already checked the corresponding code and it does not seems to be difficult to make this happen.

**Comment by rstoenescu** [comment]
Enhancement will be available in "quasar" v1.12.4.

**Comment by luckylooke** [comment]
You are amazing guys! 👏 👏 👏

**Comment by dariodepaolis** [comment]
Thank you for this enhancement, just a quick info related to this:
Now I can customize all the cells and a single cell in particular, but only the Q-TD.
If I need to customize the Q-TR (for a handling a click event for example) at this moment I can do this using the body slot, but this will override the other slots.

Is there a way to customize cells with their slot and at the same time customize the TR without rewriting all the body?

**Comment by henrychoy** [comment]
> Thank you for this enhancement, just a quick info related to this: Now I can customize all the cells and a single cell in particular, but only the Q-TD. If I need to customize the Q-TR (for a handling a click event for example) at this moment I can do this using the body slot, but this will override the other slots.
> 
> Is there a way to customize cells with their slot and at the same time customize the TR without rewriting all the body?

I was having the same issue, I was using the body slot to make the rows selectable, but also needed to use the body-cell-[name] slot to override specific columns.  It turns out you can use body-cell-[name] within the body slot, see below for an example.  Hope this helps.  If anyone knows of a simpler way, please let me know!

```
    <template v-slot:header="props">
      <q-tr :props="props">
        <q-th v-for="col in props.cols" :key="col.name" :props="props">
          {{ col.label }}
        </q-th>
      </q-tr>
    </template> 
    <template v-slot:body="props">
      <q-tr class="cursor-pointer" :props="props" @click="props.selected = !props.selected">
        <q-td v-for="col in props.cols" :key="col.name" :props="props">
          <slot v-bind="props" :name="`body-cell-${col.name}`"></slot>
          <div>
            {{ col.value }}
          </div>
        </q-td>
      </q-tr>
    </template>
```

**Comment by pstatham-exp** [comment]
> > Thank you for this enhancement, just a quick info related to this: Now I can customize all the cells and a single cell in particular, but only the Q-TD. If I need to customize the Q-TR (for a handling a click event for example) at this moment I can do this using the body slot, but this will override the other slots.
> > Is there a way to customize cells with their slot and at the same time customize the TR without rewriting all the body?
> 
> I was having the same issue, I was using the body slot to make the rows selectable, but also needed to use the body-cell-[name] slot to override specific columns. It turns out you can use body-cell-[name] within the body slot, see below for an example. Hope this helps. If anyone knows of a simpler way, please let me know!
> 
> ```
>     <template v-slot:header="props">
>       <q-tr :props="props">
>         <q-th v-for="col in props.cols" :key="col.name" :props="props">
>           {{ col.label }}
>         </q-th>
>       </q-tr>
>     </template> 
>     <template v-slot:body="props">
>       <q-tr class="cursor-pointer" :props="props" @click="props.selected = !props.selected">
>         <q-td v-for="col in props.cols" :key="col.name" :props="props">
>           <slot v-bind="props" :name="`body-cell-${col.name}`"></slot>
>           <div>
>             {{ col.value }}
>           </div>
>         </q-td>
>       </q-tr>
>     </template>
> ```

@henrychoy Does this  work? I don't believe you can define a `<slot>` in the body template and then below it use `<template #body-cell-[name]>`, as the body slot will still override it.

Edit: Looks like this _should_ work if you're defining this slot in the `QTable` within your own component; then you must use this cusom component elsewhere and you can define the `<template #body-cell-[name]>` accordingly. I don't believe this works (as I could not get it working and the [QTable Source](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/QTable.js#L379) makes it pretty clear that the body slot has precedence over the individual cells.
