### ISSUE TITLE
Updated Material Icons released

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#7161]
**Describe the bug**
When using an icon from the 'Action' section from Material Icons the _ is interpreted as a space and the icon is not shown.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Evertvdw/pen/WNrbQBo

**Expected behavior**
I expect the right icon to show.
https://material.io/resources/icons/?search=filter&icon=filter_alt&style=baseline

**Screenshots**
![image](https://user-images.githubusercontent.com/5757159/83754326-178cbe80-a66c-11ea-9aec-80da230b340a.png)
![image](https://user-images.githubusercontent.com/5757159/83754352-22475380-a66c-11ea-8115-82d41b6b8a26.png)

**Platform (please complete the following information):**
Browsers: Chrome

**Comment by rstoenescu** [comment]
Hold on with the "bug" label :)
They've updated Material Icons recently. We'll update to their latest tomorrow.

**Comment by Evertvdw** [comment]
Ok, thanks!

**Comment by rstoenescu** [comment]
Got a bit of time to squeeze in "@quasar/extras" v1.8.2. Enjoy!
