### ISSUE TITLE
Ability to resize an image after image is loaded into Browser memory BEFORE upload

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#7165]
Suppose a user uploads a very high resolution from phone. We want the ability to check the resolution and of the image if it is greater than X,Y, then resize it to x,y and then upload it. This will eliminate a lot of bandwidth and storage problems down the road due to large image sizes.
Thanks!

**Comment by pdanpdan** [comment]
Hello. This is something you should implement in your application. You can use for example vue-croppa.
