### ISSUE TITLE
Ability to use Mobile’s Browser phone capture.

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#7166]
This feature streamlines capturing and uploading images from cell phone. Otherwise user has to save the image first and then manually search for it to upload. This should also allow to resize large image to smaller images.
Thanks

**Comment by pdanpdan** [comment]
Hello. This is something the device provides - if you set the correct `accept` prop the mobile will allow you to choose how to take the picture.
For QFile you can set also the `capture` attribute to tell which camera you want to use.

**Comment by kapchew** [comment]
Hi, 

Referring to this test case: https://codepen.io/kapchew/pen/LYGdabr

using QFile, if I need my phone to offer camera option and file explorer, I find that I need to include accept="*,image/*", but if I choose any non image file, it will always fail the "Accept" validation.

if I include accept="*", it will not offer the option of camera at all.

Is this a bug? or is there other ways to offer both Camera and File Explorer? I would like my users to be able to take a snapshot or to be able to upload any valid documents, such as PDF or DOC.

**Comment by kapchew** [comment]
Further to my test, I found that if accept="*", it will always fail for whatever files picked, including image files.

**Comment by pdanpdan** [comment]
Please use the correct formats for accept. Check mdn site.

**Comment by kapchew** [comment]
But if you click at the regular HTML file input on the same test case, it works properly:

<input type="file" accept="*,image/*" >

**Comment by pdanpdan** [comment]
Ok, I have to check the vaalidation function.

**Comment by webnoob** [comment]
Available in 1.12.9
