### ISSUE TITLE
Quasar-edge.git - Repository missing fatal error

### ISSUE THREAD

**Issue by MHassanSaqib** [quasarframework/quasar#7169]
Hi there, 

I am facing the following error. Could you guide me on how can I resolve the missing repository?  

`fatal: repository 'https://git@github.com/quasarframework/quasar-edge.git/' not found`

**Comment by rstoenescu** [comment]
Hello.

There is no quasar-edge repository... Assuming you are pointing "quasar" dependency to it, just replace that with "^1.0.0".
