### ISSUE TITLE
Not critical issue - not round button with only icon margin 

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#717]
When the button does not have any label, but only icon and it is not round, the icon shouldn't have the margin on the right which comes from class on-left as icon is then not in the middle of button which looks bad. Round is not solution as it is not that compact.

**Comment by rstoenescu** [comment]
Rectangle button with just an icon should be used as follows only (note we do not use the icon props):
```html
<q-btn .......> <q-icon name="mail" /> </q-btn>
```

If you feel this should be specified in the documentation, would you be so kind as to provide a PR for it pls? Thanks!

**Comment by smolinari** [comment]
I've added this info in the docs.

Scott
