### ISSUE TITLE
Icon Genie v2 generated splashscreens stretched on 18:9 screens

### ISSUE THREAD

**Issue by TomDeSmet** [quasarframework/quasar#7173]
**Describe the bug**
When generating splashscreens with Icon Genie v2 (or v1) the splashscreen is stretched on 18:9 screens (such as Samsung Galaxy S8 and any other modern big phone).
It looks good on a Pixel 2 for example.

The image itself is OK, but when loading the app it gets stretched vertically which looks awfull of course.

**To Reproduce**
1. Generate a splashscreen with Icon Genie (with a round app icon for example).
2. Launch app in Android studio or build app and install on 18:9 device.

**Expected behavior**
I expect the spashscreen to be shown in the correct aspect ratio unstretched.

**Screenshots**
![example-splashscreen](https://user-images.githubusercontent.com/16959207/83940111-678d9180-a7e2-11ea-99aa-eaf5514e5b62.jpg)

**Platform (please complete the following information):**
OS: Android 9
Node: v 12.12.0
NPM: v 6.14.5
Android: 9 - API 28

**Comment by rstoenescu** [comment]
Hi,

This is not a fault of IconGenie, but rather of cordova/capacitor configuration. From IconGenie perspective, at best, you could create an IconGenie profile to create additional pngs at some additional resolutions.

@IlCallo can u comment a little more, pls?

**Comment by IlCallo** [comment]
Hi @TomDeSmet!
I recently met this problem too, you can find [here](https://forum.ionicframework.com/t/splash-screen-is-stretched-in-some-devices/185430/9) the solution.

In `capacitor.config.json` add

```json
"plugins": {
  "SplashScreen": {
    "androidScaleType": "CENTER_CROP"
  }
}
```

In `src-capacitor/android/app/src/main/res/values/styles.xml`, `AppTheme.NoActionBarLaunch` style must be like this
```xml
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowIsTranslucent">true</item>
    </style>
```

We are still not sure this configuration is ok for every use case, so we haven't added this to Quasar Capacitor mode yet, but we'll explore what we can do in this direction
