### ISSUE TITLE
Initial/final size of animated dialogs

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#7174]
From this discussion on Discord:

- when I compare the transition when opening a dialog in Quasar (https://quasar.dev/vue-components/dialog) and in Vuetify (https://vuetifyjs.com/en/components/dialogs/), I feel that the Vuetify one is more "snappy", like if Quasar was slower to render the dialog
- the transition to open the dialog begins with a near-0 scale so it is slower to open at 100%
with Vuetify, the dialog starts to open as soon as the button is pressed and it starts at ~50% so it is faster to open
- tweaking example: https://codepen.io/pdanpdan/pen/rNOYNrd

Maybe we should also not start from 0 but with something more.

**Comment by rstoenescu** [comment]
Let's be reasonable. It's just an animation and it runs in 0.3 seconds... If we start doing exceptions to the default shipped transitions then CSS can skyrocket...

**Comment by pdanpdan** [comment]
It was more as a reference to point people that sfânt this.
