### ISSUE TITLE
Q-Editor - name property missing

### ISSUE THREAD

**Issue by JTrotta** [quasarframework/quasar#7175]
**Describe the bug**
q-editor does not have  a name property, used during native form submit.

**Codepen/jsFiddle/Codesandbox (required)**
not applicable

**To Reproduce**
not applicable

**Expected behavior**
Like all submittable components, it shoudl have name property

**Screenshots**
not applicable

**Platform (please complete the following information):**
OS: Windows  .netcore
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
not applicable

**Comment by pdanpdan** [comment]
Hello.
The easiest solution for this is to create a hidden `input` (or a `textarea`) field and set the `name` and `value` for it.
The QEditor does not really have a native field inside, so what we would end up doing would be the same thing.

**Comment by JTrotta** [comment]
Ok. 
This means you will add it in future and hidden field it's just a temporary solution, or not?
Thank you.

**Comment by pdanpdan** [comment]
Let me check the required changes for this.

**Comment by JTrotta** [comment]
@pdanpdan Closed, with no news?

**Comment by pdanpdan** [comment]
I commented above.
