### ISSUE TITLE
QDataTable with QPopupEdit offset attribute does not have effect in vertical axis when combined with anchor

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#7179]
Thank you for your active maintenance and development of this framework, you are awesome! 🙏 

**Describe the bug**
Offset does not work vertically when combined with anchor.
I make the offset significant to make it visible... in my project I need to offset it just 1px.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luckylooke/pen/gOPpzEM

**To Reproduce**
1. open codepen
2. Click on cell in "name" column.. see vertical offset works (I put significant value to make ot more visible)
3. Same setup for calories column but now included anchor attribute
4. click on calories cell and see popup is not vertically offseted

**Expected behavior**
Offset to work with anchor.

**Screenshots**
![Screenshot at Jun 07 10-55-28](https://user-images.githubusercontent.com/3660030/83964445-8147db00-a8ad-11ea-863b-90a461090c2b.png)

**Platform (please complete the following information):**
platform agnostic (codepen)

While I was playing with code in my project it now fits well without offset used at all.
But anyway should not offset work? 🙂 

Thanks

**Comment by pdanpdan** [comment]
You used `center` for vertical align in `self` and `anchor` - use some other alignment.
Supposing you want the popup to align top-left with the td: https://codepen.io/pdanpdan/pen/NWxGjzY?editors=1010
