### ISSUE TITLE
Rounding numbers

### ISSUE THREAD

**Issue by Berkmann18** [quasarframework/quasar#7182]
**Is your feature request related to a problem? Please describe.**
As it doesn't seem possible to import js modules to use as a utility module, it would be great to have such functions built-in.

**Describe the solution you'd like**
The possibility to import a function say `round` or `roundTo` from `quasar.format` which allows coders to pass numbers and optionally a precision or desired number of decimal places like:
```js
import { round } from 'quasar/format';
//...
round(this.someValue);
```

Where `round`/`roundTo` would be defined as follows.
```js
const round = (num, dp = 2) => {
  const precision = 10**dp;
  return Math.round(num * precision) / precision;
};
```

**Describe alternatives you've considered**
Importing my own utility module the same way I would do when using VueJS/Gridsome (e.g. `import { round } from '@/components/util'`) which works in Quasar.

**Additional context**

**Comment by pdanpdan** [comment]
Math.format/Math.precission

**Comment by Berkmann18** [comment]
@pdanpdan Neither of those function exists...

**Comment by pdanpdan** [comment]
Sorry, I misremembered:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision

**Comment by Berkmann18** [comment]
@pdanpdan I knew about the last 2 however, those convert to a string whereas the `round` function I was on about keep the number as a number, you know what I mean?
