### ISSUE TITLE
Dialog does not show up within a maximized component

### ISSUE THREAD

**Issue by DOOMitru** [quasarframework/quasar#7187]
**Describe the bug**
Dialog does not show up within a maximized component.

**Codepen**
https://codepen.io/doomitru/pen/OJMVqoq

**To Reproduce**
Click on 'show dialog' button while in normal mode and the dialog shows up. Click on 'fullscreen' and then click on 'show dialog' button while the component is maximized and the dialog does not show up. It does however show up if you then close the full screen.

**Expected behavior**
I would expect the dialog to show up within the maximized component.

**Platform**
OS: Win 10
Node: 12.13.1
NPM: 6.12.1
Browsers: Chrome 83.0.4103.97, FF 77.0.1, Opera 68.0.3618.125, Edge: 85.0.531.1

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fix will be available in "quasar" v1.12.5.

**Comment by rstoenescu** [comment]
Additional work: 

commit 2146d1da983b677a6d53eb5de0af8a3a5e48b996 (HEAD -> dev, origin/dev, origin/HEAD)
Author: Razvan Stoenescu <razvan.stoenescu@gmail.com>
Date:   Thu Jun 11 14:43:24 2020 +0300

    perf+fix(portal): Do not recreate vm when on Dialog plugin; fullscreen support for Dialog plugin
