### ISSUE TITLE
Pause carousel autoplay on hover (or focus)

### ISSUE THREAD

**Issue by AaronAtkinson** [quasarframework/quasar#7189]
**Is your feature request related to a problem? Please describe.**
When hovering over an autoplaying carousel, the carousel continues to cycle through.
This makes it hard to read slides with more text, as there is no way for the user to prevent slides from changing.
It also can lead to clicking on the wrong slide, if the page changes just before the user clicks.

**Describe the solution you'd like**
Hovering over the carousel should pause the autoplay timer. I think most people would agree, this is fairly standard behavior these days.

**Describe alternatives you've considered**
I don't really think there is any need in exploring other options, pausing the timer is simple, and pretty commonplace.
[bootstrap carousel docs (autoplay example)](https://getbootstrap.com/docs/4.5/components/carousel/#individual-carousel-item-interval)

**Additional context**
It would be nice to see similar behavior on other components that change automatically, such as the notify plugin. I personally think if a user were hovering over a notification's undo action the notification should not close itself.

**Comment by pdanpdan** [comment]
As discussed on discord, mouseless (touch) devices do not have hover. This would lead to a design that is unusable. Even more, in the case of the carousel this is trivial to implement in userland. The case where it's not easy is the notifications, but relying on this is still a problem because of first point.

**Comment by AaronAtkinson** [comment]
That doesn't seem like an overly accurate way to look at it. How would it lead to a design that is unusable? Unless you are just simply saying the changes would not be usable on mobile... but then so what? There are plenty of props and components that rely on hover and are not used on mobile devices. Those things existing, shouldn't be a problem for devices that simply don't make use of them. 

It is certainly valid to say that implementing this functionality on a carousel is trivial, but I don't think that is an excuse for it not to be built in to Quasar. It's very basic functionality that (as far as I can tell) has no reason to not be included. I actually considered categorizing this as a bug because it seems to fundamental that I assumed it just got overlooked.

I'm fine to implement it myself on carousels, I just thought improvements were encouraged.

**Comment by pdanpdan** [comment]
Not just on mobiles, on all pointerless systems. And almost the only thing you cannot detect in is is if you have pointer/mouse or not.

**Comment by rstoenescu** [comment]
But we can do it for non-mobile platforms.

**Comment by AaronAtkinson** [comment]
> Not just on mobiles, on all pointerless systems. And almost the only thing you cannot detect in js is if you have pointer/mouse or not.

But for something like disabling autoplay for carousels on hover, it doesn't really matter if it's present on a mobile (or pointerless) system does it? It just wouldn't ever trigger.

On another (mildly relevant but very uncommon) note, I have a friend that keeps his android paired as the 3rd device on his MX master, only because he doesn't have another device he needs it for. And while I don't think he has found a single measurable benefit to having a mouse in android, it is unlikely but entirely possible for the code to get used on a mobile device.
Not to mention devices running ChromeOS which may have mobile apps installed, or access mobile/touch friendly versions of websites.

Again, I'm not trying criticize the framework in any way what-so-ever, I just think it's the expected behavior when navigating a carousel with a mouse, and was surprised to see it wasn't the implemented in Quasar.

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/WNrwjJj?editors=1010

**Comment by hawkeye64** [comment]
@pdanpdan That should be a docs example, imo

**Comment by pdanpdan** [comment]
If somebody want, a PR with this trivial example for the docs would be welcomed.

**Comment by webnoob** [comment]
Docs updated with this example.

**Comment by francisashley** [comment]
Hi, this is a pretty standard feature for a toast. The example shared here now 404's and can't see anything in the docs
