### ISSUE TITLE
validation for form in the popup Dialog

### ISSUE THREAD

**Issue by HarleyTan** [quasarframework/quasar#719]
feature suggestion/request

when I create a Dialog with form components,such as :
```
import { Dialog, Toast } from 'quasar'
Dialog.create({
  title: 'Prompt',
  form: {
    name: {
      type: 'text',
      label: 'Textbox',
      model: ''
    },
    mobilephone: {
      type: 'text',
      label: 'Textbox',
      model: ''
    },
  },
  buttons: [
    'Cancel',
    {
      label: 'Ok',
      handler (data) {
        Toast.create('Returned ' + JSON.stringify(data))
      }
    }
  ]
})
```
can I do some validation for the mobilephone number?
I need some feature to support vuelidate. or can I pass a @blur event handler to mobilephone ?

thx very much

**Comment by rstoenescu** [comment]
Hi,

Check http://beta.quasar-framework.org/components/dialog.html#Prevent-Closing-the-Dialog
This will allow you to use validations and prevent closing the dialog until all data is filled in correctly. If you need something more specific, create your own Modal.

**Comment by Marcelofj** [comment]
@rstoenescu , can you show some code snippet? I can not know how validate from dialogs.
