### ISSUE TITLE
[TS] Error not using lazy loading

### ISSUE THREAD

**Issue by BeginsDuang** [quasarframework/quasar#7194]
**To Reproduce**
1. `quasar create test` 

![QQ截图20200609191202](https://user-images.githubusercontent.com/25838823/84141158-4e583f80-aa85-11ea-8842-8528c4d7c761.png)

2. not using lazy loading
![QQ截图20200609190224](https://user-images.githubusercontent.com/25838823/84140188-caea1e80-aa83-11ea-98e1-a3f3a0a10e6e.png)
3. See error
![QQ截图20200609190328](https://user-images.githubusercontent.com/25838823/84140311-fb31bd00-aa83-11ea-8a0f-d6dd32fd55d9.png)

**Platform (please complete the following information):**
OS: windows 10(10.0.18363)
Node: 14.4.0
NPM:6.14.5
Yarn:1.22.4
Browsers: Microsoft Edge（83.0.478.45）

**Additional context**
[test dome](https://github.com/BeginsDuang/examples/tree/master/example-1)
![QQ截图20200609191833](https://user-images.githubusercontent.com/25838823/84141630-0c7bc900-aa86-11ea-8945-3d43ce7d60d5.png)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this.
Will be fixed with the upcoming "@quasar/app" v2.

**Comment by BeginsDuang** [comment]
@rstoenescu thanks😀

**Comment by rstoenescu** [comment]
Thank you for providing sufficient data to reproduce it! Without the repo it would have taken 100x more time and lots of back and forth messages.
