### ISSUE TITLE
Cordova build duplicates static assets

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#7195]
I have the problem that when ever I build my application for cordova the content of the **src/statics** folder is copied to the **www/img** folder despite the statics folder also being present in the **www** directory. The image below further illustrates my problem.

![image](https://user-images.githubusercontent.com/30523269/84145552-5fd82200-aa5a-11ea-9e49-57fd7a76d441.png)

What this does is essentially doubling the file size of the apk. My question is if this is intentional or if I have mis-configured something along the way. Please let me know if I need to provide more information.

Thank you in advance,
Quasarman

**Comment by rstoenescu** [comment]
Hi,

That's not a duplication. One are static assets (statics) and the other are images handled by webpack directly (img).

**Comment by rstoenescu** [comment]
More info: https://quasar.dev/quasar-cli/handling-assets

**Comment by Quasarman** [comment]
Ok that makes sense. But can I prevent webpack from including any of the images into the img folder. I dont see the point in having them in there if I already have them in the statics folder of the project. Or am I missing something with the way static assests are supposed to work.

**Comment by rstoenescu** [comment]
It means that you're pointing webpack to files from statics and it forces it to embed them (they end up as assets). So don't. Please have a good read on that page again.

**Comment by Quasarman** [comment]
Ok thank you!
