### ISSUE TITLE
[bug] Line-awesome icons not vertically aligned in qbtn

### ISSUE THREAD

**Issue by DocBouCou** [quasarframework/quasar#7198]
Hi,

If you put a line-awesome icon in a q-button, then the icon and the text are not aligned (the text looks a few pixels upward).
For instance:
```html
<q-btn label="Edit" icon="las la-edit"></q-btn>
```
Of course, for now, it can be solved by using custom css within the slot.

Regards,

**Comment by rstoenescu** [comment]
Hi,

The icon is actually centered and perfectly aligned with the text. But we cannot account for cases where the icons themselves (supplied by their respective authors) do not "seem" balanced enough vertically. In this case notice the pencil spans to the far top-right outside of the rectangle.

**Comment by DocBouCou** [comment]
Ok, understood. Thank you for your answer.
