### ISSUE TITLE
LayoutDrawer: Elevation shadow pops in when swiped open

### ISSUE THREAD

**Issue by TheTyrius** [quasarframework/quasar#7205]
**Describe the bug**
I have a LayoutDrawer, with mobile behavior and "elevated" prop.
When swiping from the left edge of the screen, the drop shadow does not show until after I let go.
This is easily done on moble, but you can observe the same on desktop, if you use your mouse to pull open the drawer.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/TheTyrius/pen/OJMNVRy

**To Reproduce**
Note the shadow is normal until the drawer is completely closed. When dragging from the left edge of the screen the shadow appears only when let go (best seen if the drawer is pulled completely open before letting go).

**Expected behavior**
The shadow should be there all the time.

**Platform (please complete the following information):**
OS: Windows/Linux
Browsers: Chrome/Chromium

**Comment by rstoenescu** [comment]
Hi,

This is by design since otherwise the shadow would be visible on screen even if Drawer is closed.
