### ISSUE TITLE
Notify emits error

### ISSUE THREAD

**Issue by hao1118** [quasarframework/quasar#7206]
only in v1.12.4:
my code:
`
import { Notify, Dialog, date, format } from 'quasar'

qnotify(msg) {
    Notify.create({
      color: 'negative',
      position: 'bottom',
      message: msg,
      icon: 'report_problem'
    });
  }

qnotify("some message...");
`

**error message:**
TypeError: Cannot read property 'add' of undefined
    at Object.create (Notify.js?1f39:373)
    at Object.qnotify (apis.js?024f:18)
    at Object.xproc (apis.js?024f:68)
    at _callee2$ (apis.js?024f:132)
    at tryCatch (runtime.js?ad1f:45)
    at Generator.invoke [as _invoke] (runtime.js?ad1f:274)
    at Generator.prototype.<computed> [as next] (runtime.js?ad1f:97)
    at asyncGeneratorStep (asyncToGenerator.js?7b6b:3)
    at _next (asyncToGenerator.js?7b6b:25)

**Comment by hao1118** [comment]
PS:
the qnotify function is defined in an exportable js file.

Notify.js line 373:
return this.__vm.add(opts);
here "this" refers to the exporting package, then __vm is undefined.

**Comment by luckylooke** [comment]
What is the solution? I hit pretty same issue..
```js
TypeError: Cannot read property 'add' of undefined
    at Object.create (Notify.js?2a19:433)
```
 quasar@1.12.8
I just followed documentation
```js
 Notify.create({
        message: 'some message',
        type: 'negativecustom',
        multiLine: true,
      });
```
Thank you for any hints 🙏

**Comment by luckylooke** [comment]
Ahaa.. this is mandatory to make it work:
```js
Vue.use(Quasar, {
  plugins: {
    Notify,
  },
});
```
Happy coding 👍 🙂

**Comment by PaulCombal** [comment]
Just for the noobs like me to follow, in what file is it best to put this?

**Comment by hawkeye64** [comment]
@PaulCombal If using Quasar CLI, then it's in the quasar.conf.js
If using Vue CLI, then it's anytime before Vue is instantiated to an app

**Comment by F145h** [comment]
have the same error with vue-cli

my main.js:

```
import { Quasar, Notify } from 'quasar'

Vue.use(Quasar, {plugins: {Notify}})

Vue.config.productionTip = false


new Vue({
  render: h => h(App),
}).$mount('#app')
```

but have error **TypeError: Cannot read property 'add' of undefined** when called Notify

```
import { Notify } from 'quasar'

Notify.create({
  message: 'test!'
})
```

**Comment by rstoenescu** [comment]
@F145h It's not nice to cross-post.

However, I'll write down the same thing here, in the hope that it may help someone else ending up here.

---

This is because you're installing Quasar twice.
Notice this in the default main.js:

```
// src/main.js
import Vue from 'vue'
import App from './App.vue'
import './quasar' // <<<<<<<<<<<<<<< THIS
```

The contents of the /src/quasar.js file is (just an extract of it):

```
// src/quasar.js
// .....

Vue.use(Quasar, {
  config: {},
  plugins: {
  }
 })
```

This is the place where you should add the plugins (and whatever else you need). Otherwise just delete src/quasar.js, remove the import statement for it from main.js and write it all in main.js :)

**Comment by F145h** [comment]
> // src/main.js
> import Vue from 'vue'
> import App from './App.vue'
> import './quasar' // <<<<<<<<<<<<<<< THIS

big thanks!
hope this helps others too

**Comment by yssunjoko** [comment]
Hey guys I got simpler solution.
Just search for the plugin section in the quasar.conf.js
and insert:

module.exports = function (/* ctx */) {
  return {
   ....
   // Quasar plugins
      plugins: [
        **'Notify'**
      ]
  }

Voila! You'll get the Notify pop up.

**Comment by hawkeye64** [comment]
@yssunjoko I think they were discussing using with Vue CLI and not Quasar CLI
