### ISSUE TITLE
loading statics in css url

### ISSUE THREAD

**Issue by amitgur** [quasarframework/quasar#7207]
**Describe the bug**
When I try to load a static font with url() as described by the docs [https://quasar.dev/quasar-cli/handling-assets#Static-Assets---%2Fsrc%2Fstatics](url)
`
src:  url('statics/fonts/icomoon.eot?6dhi7a');
`
In dev it's working fine, but in prod, doing quasar build, I get "Error: Can't resolve './src/statics/fonts/icomoon.eot?6dhi7a'"

looking here [https://stackoverflow.com/questions/59414668/reference-statics-file-in-app-sass-with-quasar](url) and using:
`
src:  url('../statics/fonts/icomoon.eot?6dhi7a');
`
It's working in dev, build, and production.

Am I missing something here?

**Comment by rstoenescu** [comment]
Hi,

Why not place your font files in assets and let webpack handle them?
