### ISSUE TITLE
QSeparator spaced - add "size" option

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#7209]
**Is your feature request related to a problem? Please describe.**
Currently using the `spaced` prop on `QSeparator` only adds `8px` margin on top/bottom, which sometimes doesn't fit the styling and forces you to add a class instead to increase the margin (like `q-my-md`).

**Describe the solution you'd like**
Let `spaced` take an optional size value, as you've done with other props (`xs`, `sm`, `md`, `lg` etc.)

**Describe alternatives you've considered**
Using additional classes as mentioned above.

**Comment by rstoenescu** [comment]
Hi,

What's wrong with setting that yourself? The "spaced" is only a "helper". Add one of the "q-my-*" Quasar CSS classes or set margin-top/bottom directly.

**Comment by FrittenKeeZ** [comment]
@rstoenescu it's more of a convenience really. Also it would make it more streamlined when using the separator vertically, not having to change classes.
`<q-separator spaced="md" />` vs. `<q-separator class="q-my-md" />`
`<q-separator spaced="md" vertical />` vs. `<q-separator vertical class="q-mx-md" />`

**Comment by rstoenescu** [comment]
Will be available in "quasar" v1.12.5.
