### ISSUE TITLE
 Configuring the pages  + Adding Third party npm packages

### ISSUE THREAD

**Issue by augmen** [quasarframework/quasar#721]
I have started with the Quasar framework for developing a media streaming app. I want to add Loading  + authentication page + Search bar + Media  list +  media play page . How to do it guide . Are there any step by step repo for doing this ?  I guess we need to add new pages with <quasar new component hell> command ? But how to add other  JS / CSS components to the pages ? Where to add the Player Api :  in index HTML page / main.js file  ? or index.vue page ? Does Quasar supports firebase API ? Where to add the firebase API / SDK ? in main.js file ?  Please guide us ?

**Comment by rstoenescu** [comment]
Hi,

I'm currently on vacation.
Please use forum for questions. You will get help there. Thanks.
