### ISSUE TITLE
Scroller missing in ssr mode 

### ISSUE THREAD

**Issue by yeyeck** [quasarframework/quasar#7212]
**Describe the bug**
When I run the quasar project in ssr mode, the webpage is over flow and scroller dosen't show on right. After I close the right Q-Drawer, the scroller appears.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. Create a  main layout with left drawer and right drawer.
2. Run the quasar project in ssr mode
3. When the page layout is over flow, the scroller is missing.
![image](https://user-images.githubusercontent.com/30868198/84558599-bf8a4200-ad66-11ea-9d98-75feaac6b140.png) 
4. After hide the right drawer, the scroller appears.
![image](https://user-images.githubusercontent.com/30868198/84558639-f8c2b200-ad66-11ea-9d02-51b8decbca11.png)
5. Show the right drawer agin. It behaves as expected.
![image](https://user-images.githubusercontent.com/30868198/84558690-3de6e400-ad67-11ea-8745-3a33a6c1f621.png)

**Expected behavior**
The scroller should show on the brower.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
My MainLayout.vue
<template>
  <q-layout view="hHh LpR fFf">
    <q-header reveal class="bg-secondary text-white">
      <q-toolbar>
        <q-btn fixed-top dense flat round icon="menu" @click="left = !left" />
        <q-toolbar-title>
          <q-avatar>
          </q-avatar>
          晚风习习
        </q-toolbar-title>
        <q-btn dense flat round icon="menu" @click="right = !right" />
      </q-toolbar>
    </q-header>

    <q-drawer show-if-above overylay v-model="left" side="left" bordered>
      <q-img class="side-head-bg fixed" src="https://cdn.quasar.dev/img/material.png" style="text-align: center">
        <img class="side-head" src="https://img.hacpai.com/avatar/1589442629841_1589523523093.png?imageView2/1/w/128/h/128/interlace/0/q/100">
      </q-img>
      <q-separator/>
      <div class="items-center" style="margin-top: 248px">
        <q-separator/>
        <q-item to="/">
          <q-item-section class="items-center">
            ----- 首页 -----
          </q-item-section>
        </q-item>
        <q-item to="/">
          <q-item-section class="items-center">
            ----- 标签 -----
          </q-item-section>
        </q-item>
        <q-item to="/about">
          <q-item-section class="items-center">
            ----- 关于我 -----
          </q-item-section>
        </q-item>
        <q-item >
          <q-item-section class="items-center">
            <a href="https://github.com/yeyeck">
              <q-avatar>
                <q-icon name="ion-logo-github" style="font-size: 2.5rem" />
              </q-avatar>
            </a>
          </q-item-section>
        </q-item>
      </div>
    </q-drawer>
    <q-drawer v-model="right" side="right" bordered>
       <q-date
        v-model="date"
        minimal
      />
    </q-drawer>
    <q-page-container class="bg-grey-2">
      <router-view />
    </q-page-container>

    <q-footer reveal elevated class="bg-teal-10 text-white">
      <div class="row items-center">
        <q-item class="row items-center">
          <q-item-section>
            © 2020 yeyeck.com
          </q-item-section>
        </q-item>
      </div>
    </q-footer>

  </q-layout>
</template>

<script>
export default {
  data () {
    return {
      left: false,
      right: true,
      date: '2019/05/26'
    }
  }
}
</script>

<style scoped>
.side-head-bg {
    width: 100%;
    height: 248px;
}
.side-head {
  border-radius: 60px;
  width: 120px;
  height: 120px;
  margin-top: 60px;
}
</style>

**Comment by rstoenescu** [comment]
Confirmed. Fixing.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.12.6
