### ISSUE TITLE
drawer bug in scroll

### ISSUE THREAD

**Issue by mehran-akb** [quasarframework/quasar#7214]
Hi
I have issue with drawer when page scroll
when scroll page drawer is glitch

i record video from this issue
https://drive.google.com/file/d/1KFfR4deUXtiXYF4rAHKk31KsTissOh9I/view?usp=sharing

i created drawer with this code
https://codepen.io/mehran-akb/pen/VwejjeY

**Comment by pdanpdan** [comment]
Hello. Please fix the link, and fill the issue template, including a description of the problem using words.

**Comment by mehran-akb** [comment]
I Updated
