### ISSUE TITLE
qselect dropdown very slow to show on IOS

### ISSUE THREAD

**Issue by anubhavkamath** [quasarframework/quasar#7215]
**Describe the bug**
I have a q-select with 5 options. When the arrow icon is pushed, on IOS, it takes a good 2-3 seconds for the dropdown popup to show up. So, on first instinct the user will think nothing happenend and push it again which may actually close it and cause more confusion. On android and browser the delay is negligible and q-select works as expected.

**To Reproduce**
Just using a q-select on Iphone 10 seems to be problematic, nothing special about the code. 

**Expected behavior**
Not as long a delay. 

**Platform (please complete the following information):**
OS: IOS 
Node: 10.16.3
NPM: 6.9.0
Yarn: N/A
Browsers: Safari
iOS: 12.01
Android: N/A
Electron: N/A

I think this wasn't as big a problem in earlier releases of Quasar. I just started noticing the long delay recently. Please let me know if you need any other info.

**Comment by rstoenescu** [comment]
Hi,

I'm really not sure what you are referring to. It's instant on iOS too :|

**Comment by anubhavkamath** [comment]
> Hi,
> 
> I'm really not sure what you are referring to. It's instant on iOS too :|

Ok, I tried the same app code on a newer iphone (11) v.13.3.1 and the problem doesn't happen.  But good to know it's not a common problem. It's probably something specific to the that one device I was testing on. Feel free to close the issue. Thanks for your response.
