### ISSUE TITLE
VS Code debugging - Babel config [docs]

### ISSUE THREAD

**Issue by charlie17** [quasarframework/quasar#7216]
It regards getting successfully up and running in VS Code with the Debugger for Chrome extension.

The existing docs section [here](https://quasar.dev/start/vs-code-configuration#Debugging-a-Quasar-project-in-VS-Code) got things to a point where it would at least register a breakpoint. But from there it would jump around to unexpected lines. The sourcemap did not match up to what was sent to the browser. This rendered VS Code debugging pretty much useless.

After some trial and error, turns out Babel was interfering. Adding the code below to `babel.config.js` fixed the issue.

So, it's not a Quasar bug or issue per se, but it may well help folks to at least include a "tip" on the docs page.

    //babel.config.js
      env: {
        development: {
          sourceMaps: true,
          retainLines: true
        }
      },

**Comment by pdanpdan** [comment]
Can you please make a PR for the docs? the section about VSCode.

**Comment by delebash** [comment]
I have the same problem with breakpoints jumping around.  I tried your suggestion but it did not work for me.

**Comment by charlie17** [comment]
Yes, I’ve found that it works for certain files but not for others. That’s why I held off on submitting the PR. After some intense rabbit hole sessions I’ve discovered this is a complex multivariate problem. Source maps, launch configs, webpack, Babel ... lots of interactions. It would be great if someone from the Quasar team (smarter than me) is able to definitively crack the code on this.

**Comment by webnoob** [comment]
I don't think this is docs related, it's actually the source maps not being generated properly which we have fixed and will release an update for soon. 

Closing in favor of: https://github.com/quasarframework/quasar/issues/7318
