### ISSUE TITLE
Cordova error 

### ISSUE THREAD

**Issue by augmen** [quasarframework/quasar#722]
Installed cordova in the machine and run the following command $ cordova requirements got this error ;
![screen shot 2017-07-16 at 10 04 31](https://user-images.githubusercontent.com/11497036/28244679-86e3020a-6a0e-11e7-8cb1-a9ce5cbbc0d4.png)

**Comment by rstoenescu** [comment]
You need to make a first build of your app ($ quasar build) before running that command.
