### ISSUE TITLE
q-uploader-base component button not work

### ISSUE THREAD

**Issue by macibo** [quasarframework/quasar#7220]
As seen in the picture,
upload(add) button
quasar version;
1.11.2 working,
1.11.3 and later bug

**Comment by macibo** [comment]
![image-1-11-2](https://user-images.githubusercontent.com/40409549/84604893-e7ca8b80-aea1-11ea-8eed-70b326c62bb7.jpg)
![image-1-11-3](https://user-images.githubusercontent.com/40409549/84604894-ea2ce580-aea1-11ea-838a-03e03570a2a1.jpg)

**Comment by rstoenescu** [comment]
Please offer a [codepen](https://codepen.quasar.dev) or [jsfiddle](https://jsfiddle.quasar.dev).

**Comment by rstoenescu** [comment]
Found the culprit, but pls note that QUploaderBase is to be used a mixin and not as standalone. Regardless, it will handle your case in "quasar" v1.12.5.
