### ISSUE TITLE
Ellipsis 2 and 3 lines not working when q-p*-** is in the same div

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#7221]
**Describe the bug**
There is a 3rd/4th line appearing when using ellipsis on 2/3 lines on a div that has a q-p*-** class if the text is too long

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/medhyena/pen/pogbMXJ

**To Reproduce**
1. Create a div with q-pa-md as a class
2. Add ellipsis-2-lines
3. Put a huge text in the div
4. See the 3rd line popping after the 3 dots

**Expected behavior**
It should basically do an ellipsis and doesn't make the text appear because of q-pa-md

**Comment by pdanpdan** [comment]
Hello. Please add a codepen showing the problem.

**Comment by Medhyena** [comment]
Done ! :) I was doing it indeed ^^

**Comment by pdanpdan** [comment]
Hello. It looks like the implementation in browser is to show the rest of the text, so if you have bottom padding it is going to be shown.
The only solution I see is to wrap the div with ellipsis and without padding in an outer div with padding.
Sorry, there is nothing we can do, it's just a helper class for the webkit implementation (it is also limited to webkit and friends).
https://codepen.io/pdanpdan/pen/wvMzwaL?editors=1010
