### ISSUE TITLE
Slider not hide label and not show circle after disable/enable.

### ISSUE THREAD

**Issue by profsoft** [quasarframework/quasar#7225]
After v1.12 version slider not hide label and not show circle after disable/enable.

[See on jsfiddle](https://jsfiddle.net/profsoft/j6pban5t/)

1. Drag slider
2. Wait enable after 2s.
3. Label is shown, circle is hidden.

OS: Windows 10
Browsers: Chrome fresh version 83

**Comment by pdanpdan** [comment]
Hello.
For the moment add a setTimeout on setting the disable prop (https://jsfiddle.net/41n7qyrs/2/)
I'll investigate the problem.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.12.6.
