### ISSUE TITLE
[docs] service-worker cache busting mini-guide

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#7227]
### Goal
always ensure a certain website displayed to visitor is the latest version, and not an old cached version (eg. with your `main.js` logic from a previous version)

### Methods
are two ways I believe this is possible to implement:
1. make an API call that checks the version on a server/cloud function and returns the version which is to be checked against a version saved in the localStorage. If they don't match prompt to reload the page.
2. use a service worker.

### Service worker approach

I believe the common approach with a service worker is to expand a bit on the `updated()` hook like so:

```js
updated() {
      console.log('New version needs refresh.');
      Notify.create({
        title: 'New version available: ' + require('./../package').version,
        actions: [
            {
                label: "Refresh",
                handler: () => window.location.reload(true)
            }
        ]
      })
    },
```

### Request

I'm personally however very confused on how to do the whole "check the hash of the app against the new version of the service worker" or something.

There are many articles on this, but they all say different things, and the part about automatically exposing and checking against a hash of some sort is still confusing to me.

I'd love this to be an extra section on the [handling-service-worker](https://quasar.dev/quasar-cli/developing-pwa/handling-service-worker) documentation page of Quasar!

**Comment by rstoenescu** [comment]
Hi,

1. We can't just duplicate workbox's docs :)
2. Use the `/src-pwa/register-service-worker.js` to handle this. You don't have to reinvent the wheel.

**Comment by mesqueeb** [comment]
Yes, but what if there's no update to your service worker. Just to your app.

How will the `register-service-worker.js` know so it triggers the `updated` function?

**Comment by rstoenescu** [comment]
You don't need anything. You already have everything backed in. The build creates a precache manifest then checks against installed assets. Then it triggers the according event which is caught by "register-service-worker".

**Comment by mesqueeb** [comment]
Is it possible to add just the service worker to an SPA as well? Or do the usage of service workers require an app-manifest to exist as well?

I have some cases where somehow even SPAs sometimes are not loading the latest main.js but serve from cache instead.
