### ISSUE TITLE
feat(capacitor/cordova): make backButtonExit customizable

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#7228]
**Is your feature request related to a problem? Please describe.**
My Capacitor app, like many apps, only have a one-level flat history (dialogs excluded).
Main pages are `/login` and `/home` pages, to which the user is redirected when hitting root path (`/`), depending on his authentication status.
Right now `backButtonExit` is configured to exit only when the location hash matches `#/` (the root path), but some apps (especially the ones which require login) this condition is never met, so the app cannot exit via back button with current behaviour.

**Describe the solution you'd like**
The app should allow to customize the exit hash.
A wildcard value should be defined to allow exit on all pages.

I would suggest this values options for `backButtonExit`:
- not defined / `undefined` -> keep current behaviour, exit on `#/` hash
- `false` -> keep current behaviour, disable the feature
- `'*'` -> string wildcard, exit on any page when history length is 0
- `['login', '/home', 'my-page/my-nested-page/']` -> array form, exit when current hash is root path or it matches provided pages, and history length is 0. Initial `/` should be automatically prepended if not present, trailing `/` should be automatically removed

The feature is purely additional and opt-in to avoid breaking changes.

**Describe alternatives you've considered**
I added a "exit on double back press" implementation into MainActivity.
In this way I can exit the app regardless of Capacitor history management, but you'll get the message even when rightfully going back from a nested page or exiting a fullscreen dialog.

**Comment by rstoenescu** [comment]
This will be available in "quasar" v1.12.6
