### ISSUE TITLE
[Request] Support new Vue 2.4 $attrs property

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#723]
Vue 2.4 introduced `$attrs` as new instance property.
If `QInput` components would use this, it would increase the flexibility of input fields.
For example, at the moment `QInput` does not support the `readonly` attribute, but only `disabled`. Instead of adding props for each missing attribute this would allow to just pass every attribute, not defined as a prop, to the input tag.

In my tests, the only changes that needed to be made were altering the `input` and `textarea` tags to `v-bind="$attrs"` and adding `inheritAttrs: false` to the `QInput` component to prevent that the attributes are also applied to the wrapper.

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.7 through the "attributes" prop.
