### ISSUE TITLE
resumable uploader protocol 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#7230]
I will be great if QUploader can resume and pause uploading file or possibility of using it with other api like `tus.io`

**Comment by pdanpdan** [comment]
Hello.
We cannot cover all protocols. It is your job to create your specific implementation as described here:
https://quasar.dev/vue-components/uploader#Supporting-other-services

If you implement one protocol or another we would be happy to accept PRs (for the docs, as extensions or even on core).
