### ISSUE TITLE
Q-select checkboxes broken on official docs page (mobile view only)

### ISSUE THREAD

**Issue by rf987** [quasarframework/quasar#724]
v0.13.10

I've noticed that the v-model reactivity of the Q-select checkboxes is broken on mobile views.  Even the example page on the official docs doesn't work.

Link:
http://quasar-framework.org/quasar-play/android/index.html#/showcase/form/select/basic

To reproduce the behavior:
1) Load the url above
2) Open chrome DevTools
2) Toggle the device toolbar (Ctrl+Shift+M)
3) Choose "iPhone 6"  from the dropdown of devices
3) Reload the page
4) On the third Select on the page, labeled "With checkboxes", open the select and change any of the options

You'll see the reactivity doesn't work.  

 If you revert to regular desktop view, and reload the page, it works fine.

**Comment by rstoenescu** [comment]
This is a problem only with dev tools emulator.
Not reproducible on a real device or with v0.14 on real device or emulator.

**Comment by rf987** [comment]
Thank you.  I lost some hair on this one.   Thanks for the amazing framework.
