### ISSUE TITLE
QSelect does not work inside QDialog in v1.12.5

### ISSUE THREAD

**Issue by foondook** [quasarframework/quasar#7240]
**Describe the bug**
In v.1.12.5 the QSelect rendered inside the QDialog does not show up the options anymore.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/quasar-select-in-dialog-65m5i?file=/src/components/MyDialog.vue

**To Reproduce**
1. Open the Dialog
2. Try use the Select

**Expected behavior**
The Select component should render its options.
Same exact component rendered outside the Dialog and works.

Downgrading to 1.12.4 fixes the problem for now.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.12.6.
