### ISSUE TITLE
q-select optional dropdown on focus or show dropdown only when filtering

### ISSUE THREAD

**Issue by gughog** [quasarframework/quasar#7242]
**Is your feature request related to a problem? Please describe.**
Is there any way to make the default dropdown with options appear only when I'm filtering ? My problem is: I need this dropdown to only appear when user starts to typing, but I am not having any success on searching how to make this.

**Describe the solution you'd like**
Maybe a prop to tell if dropdown will show when filtering or a boolean to me controls when It will popup.

EDIT:
Sorry, I forgot to specify, but my problem/feature request is related to "**q-select**" component

**Comment by pdanpdan** [comment]
For help request please use our discord channel or the forum.
I suppose than in you case it is enough to have an empty list of options when there is no filter typed.

**Comment by gughog** [comment]
Oh ok, sorry and thank you!
