### ISSUE TITLE
CLI: Better Typescript templates for VueX store module files

### ISSUE THREAD

**Issue by jagged3dge** [quasarframework/quasar#7245]
**Is your feature request related to a problem? Please describe.**
When I create a store module file from the CLI (`quasar new store -f ts <module>`), I have to manually enter the boilerplate typings and module structure to contain the code that matters. 

Currently, when store modules are generated via the CLI, they're only contain commented lines JS code without TS typings inside a file with an extension of `.ts`.

**Describe the solution you'd like**
The generated files must contain correct boilerplate structure with required TS types. 

PS: If the name of the module, can be interpolated and have the relevant StoreInterface named as the provided module name, that'd be the cherry on top. 
PPS: Even if it doesn't, it's not too tough to refactor the name of an interface, like `ExampleStoreInterface` in modern IDEs. 

**Describe alternatives you've considered**
I've been foregoing the CLI method to generate store. I duplicate the `module-example` folder (that gets created when using `quasar create` command) to a separate name. Then refactor/rename the interface name.

If there's enough support for this, I'll submit a PR for the necessary changes.

**Comment by pdanpdan** [comment]
Sure, a PR would be welcome.

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v2 (to be released tomorrow).
