### ISSUE TITLE
Quasar docs is taking too long to load [docs]

### ISSUE THREAD

**Issue by riyaz7us** [quasarframework/quasar#7246]
Hi,
I'd like to inform that quasar documentation (quasar.dev) takes long time to load. Moreover, I can only see the "Getting started" page, other sections are simply taking forever (**resulting in timeout**).
![image](https://user-images.githubusercontent.com/32412620/84935987-302eb700-b0f7-11ea-8ea0-14913b02f34e.png)

**Comment by pdanpdan** [comment]
I suppose it was a temporary problem. What country are you in? Does this happen often? Can you try some speed tests?

**Comment by rstoenescu** [comment]
And why not use Chrome so you can benefit from the PWA (so offline usage too).

**Comment by riyaz7us** [comment]
The problem was temporary. Now it's active and working fine. @rstoenescu Chrome showed similar error, even pwa did not load back then.

**Comment by rstoenescu** [comment]
We cannot account for Internet issues... Was mentioning Chrome since even if network failed you would still have access to the docs (albeit in this case it might not be latest content, but still). Anyway, glad it's now working for you too.

**Comment by riyaz7us** [comment]
Weirdly, it wasn't an internet issue, all the other domains were working fine and speed was efficient enough. I thought something was wrong with quasar hosted servers.
