### ISSUE TITLE
Quasar.conf.js：framework>all:true Import don't work

### ISSUE THREAD

**Issue by BeginsDuang** [quasarframework/quasar#7247]
**Describe the bug**
![QQ截图20200618125810](https://user-images.githubusercontent.com/25838823/84981202-8f77e000-b166-11ea-9e7a-a2bdea3ec0a2.png)

**Expected behavior**
`It's working`

**Screenshots**
### `test result`：` quasar v1.12.4 and v1.12.5 don't work`

![QQ截图20200618125810](https://user-images.githubusercontent.com/25838823/84981439-22b11580-b167-11ea-84a8-50ce76125e3e.png)
`all:'auto'`
![QQ截图20200618132409](https://user-images.githubusercontent.com/25838823/84981452-2b095080-b167-11ea-973b-cd65df23b876.png)
`all:'true'`
![QQ截图20200618132445](https://user-images.githubusercontent.com/25838823/84981460-2d6baa80-b167-11ea-912c-8b363be377ff.png)
**Platform (please complete the following information):**
OS: Windows_10(10.0.18363) - win32/x64
Node:14.4.0
NPM:6.14.5
Yarn:1.22.4
Browsers: Microsoft Edge 83.0.478.50 and Google Chrome 83.0.4103.106
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
I cannot test now, but shouldn't you use `all: true`?
Why do you use the string 'true'?

**Comment by rstoenescu** [comment]
`all: true` instead of pointing to the `"true"` String...
