### ISSUE TITLE
QTable - new slot "v-slot:body-cell-selected"

### ISSUE THREAD

**Issue by blackcodetavern** [quasarframework/quasar#7252]
In the QTable component there are slots for all self defined columns in a row (v-slot:body-cell-"name"). But if I activate the selection for the table I have no slot to manipulate the appearence of the column, where the checkbox is. I have for example the case, that I want to disable the checkbox for some rows, or put an q-icon instead.

It would be very nice to have a slot such as body-cell-selected, which has as a scope the row-data as well as the state of the selection.

The only workaround I see is to build the table by myself over the body slot, like in the examples where e.g. a switch is used instead of a checkbox. But I would like to avoid this.

**Comment by jaybo** [comment]
It looks like there's a workaround for this:
https://forum.quasar-framework.org/topic/4078/solved-qtable-selection-option-not-working-when-slots-are-overridden/6

**Comment by rstoenescu** [comment]
Of course there is. Slots "body-selection" and "header-selection".
