### ISSUE TITLE
Suggestion for adding Enter listener for q-menu

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#7255]
Hi there,
That would be great to have q-menu listen for Enter key as well, like it does for Escape key.

As per contribution guide, I am setting the suggestion first :) These code chunks might help:

**Add file ui/src/utils/enter-key.js**
`import { isKeyCode } from './key-composition.js'`

`let handlers = []`

`export default {`
`  __install () {`
`    this.__installed = true`
`    window.addEventListener('keyup', evt => {`
`      if (handlers.length !== 0 && isKeyCode(evt, 13) === true) {`
`        handlers[handlers.length - 1].fn(evt)`
`      }`
`    })`
`  },`

`  register (comp, fn) {`
`    if (comp.$q.platform.is.desktop === true) {`
`      this.__installed !== true && this.__install()`
`      handlers.push({ comp, fn })`
`    }`
`  },`

`  pop (comp) {`
`    if (comp.$q.platform.is.desktop === true) {`
`      const index = handlers.findIndex(h => h.comp === comp)`
`      if (index > -1) {`
`        handlers.splice(index, 1)`
`      }`
`    }`
`  }`
`}`

**edit: ui/src/components/menu/QMenu.js**
`+13: import EnterKey from '../../utils/enter-key.js'`
`+32:     listenEnter: Boolean,`

`+: 123: if (this.listenEnter) {
        EnterKey.register(this, () => {
          this.$emit('enter-key')
          this.hide()
        })
      }`

`+208:         EnterKey.pop(this)`

**Comment by pikil** [comment]
Yes, sorry, doing it right now, Enter went on accidentally

**Comment by pikil** [comment]
Ouch, ugly...

**Comment by pdanpdan** [comment]
Please use words to explain what you want to add as a feature and the problem that feature would solve.

**Comment by pikil** [comment]
Sure, q-menu at the moment has 'escapeKey' event only attached and that basically for cancelling the popup, but on the other hand having confirmation for popup with enterKey would be beneficial as well for that component.
Many thanks!

**Comment by pdanpdan** [comment]
It is enough to put a button with tabindex 0 in the menu and use auto-close

**Comment by pikil** [comment]
Great, thanks for that pdanpdan!

**Comment by pdanpdan** [comment]
For the moment you should focus the button like here: https://codepen.io/pdanpdan/pen/QWydEQG?editors=1010
There are improvements that should simplify this in the future 1.13 version.

**Comment by pikil** [comment]
Ah, that's why focus() method I tried initially didn't work. Of course, there is $el inside q-btn. 

Sorry, I should have checked if that is actually the case in the first place.

The suggestion is still viable I think, but I am closing this issue for now :)
Thank you for that, Dan!
