### ISSUE TITLE
[docs]q-uploader How do I get the server return data?

### ISSUE THREAD

**Issue by BeginsDuang** [quasarframework/quasar#7258]
Finished working ->get server return file url？
```
 factoryFn (files) {
      return {
        url: 'http://localhost:4444/upload',
        method: 'POST'
      }
    }
```

**Comment by pdanpdan** [comment]
The file is uploaded to your desired endpoint. The way you use that file is under your control and has nothing to do with quasar.

if you mean how you get the call response in the frontend then you can listen for the `@uploaded` and `@failed` events that receive the xhr as the second argument.

**Comment by ryhn** [comment]
Hi,
@uploaded event info.xhr elements returns is null or empty on request complete. Unable to receive returns data

````
xhr: XMLHttpRequest
onabort: null
onerror: null
onload: null
onloadend: null
onloadstart: null
onprogress: null
onreadystatechange: () => {…}
ontimeout: null
readyState: 0
response: ""
responseText: ""
responseType: ""
responseURL: ""
responseXML: null
status: 0
statusText: ""
timeout: 0
