### ISSUE TITLE
process.env is empty

### ISSUE THREAD

**Issue by codenamezjames** [quasarframework/quasar#7259]
**Describe the bug**
When i create and run a fresh instance of quasar and console log `process.env` i get an empty object

**Codepen/jsFiddle/Codesandbox (required)**
codesandbox is the only one that would show the issue and its broken :(

**To Reproduce**
1. Create a new quasar project `quasar create testproject`
2. in the src/pages/Index.vue file add a console log statement and log out process.env
3. start server and observe.

**Expected behavior**
I expect for the process.env to have many values in it such as DEV or PROD

**Screenshots**
![Screen Shot 2020-06-19 at 7 20 40 PM](https://user-images.githubusercontent.com/2415359/85185614-b9163180-b262-11ea-9907-9702719360d4.png)

**Platform (please complete the following information):**
OS: Darwin(19.5.0) - darwin/x64
Node: 12.11.0
NPM: 6.14.4
Yarn: 1.22.4
Browsers: Chrome
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
It seems to be related to the 2.0 update

**Comment by codenamezjames** [comment]
Ok so there is some webpack magic going on here. When i access the property directly it returns the correct response so if i access `process.env.MODE` i get spa like i expect
but if i do something like `myEnv = {...process.env}` i can no longer access `myEnv.MODE`

**Comment by rstoenescu** [comment]
This is for security purposes. The compile time replacement happens only when directly accessing the full path of process.env. Example: process.env.JAMES

However, should you want to break the security rule (NOT recommended, but posting here for completeness), you should use an Object and put everything that you want to access into that Object. Example: quasar.conf.js > build > env: { myprop: { ....... } } then you can console.log(process.env.myprop). Note that the final code after being compiled would look like: `console.log({ ...all-myprop-properties... })` which exposes everything to the user!

**Comment by codenamezjames** [comment]
Thanks for clearing that up!  
Something like that is what I ended up doing, I needed to access that param in the UI. I have supporting non UI code that uses the actual `proccess.env.DEV` so that the end-user cant be malicious.

When I have a few mins ill add to the docs for future Quasarians :)
