### ISSUE TITLE
#6240  same issue

### ISSUE THREAD

**Issue by towith** [quasarframework/quasar#7260]
**Describe the bug**
see #6240 
I create the app by `quasar create ...`, no step of adding ts ext , so I think that issue should be reopened

**To Reproduce**
see #6240 
To reproduce , may click between the pages back and forth several times, On my occasion  it is normal first load(F5 refresh)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9798922/85190669-0d65f380-b2ed-11ea-877f-b3b862187e85.png)

![image](https://user-images.githubusercontent.com/9798922/85190716-b876ad00-b2ed-11ea-8e70-e130f4739178.png)

**Platform (please complete the following information):**
OS: 
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

1. Manually yarn/npm install "@quasar/app@^2.0.0".
2. Do not use the obsolete TS app extension. Instead use the q/app built-in TS support: https://quasar.dev/quasar-cli/supporting-ts
