### ISSUE TITLE
Linear Progress in reversed mode reverses content of the default slot

### ISSUE THREAD

**Issue by mclate** [quasarframework/quasar#7261]
**Describe the bug**
When using `q-linear-progress` with default slot and `reverse` property, whole content of default slot is being mirrored. (You can also see styles being messed a bit)
Also notice that in reversed mode default slot is hidden beneath the progress bar (see jsfiddle) in case when progress bar overlaps with the slot content.

**Codepen/jsFiddle/Codesandbox (required)**

https://jsfiddle.net/1ghd82k6/

**To Reproduce**
1. Create `q-linear-progress` with a default slot as described in official documentation
2. Apply `reverse` property
3. Observe default slot dissappearing

**Expected behavior**
Default slot to remain unchanged and visible in reverse mode

**Platform (please complete the following information):**
OS: MacOS
Node:v14.3.0
Browsers: Brave

**Comment by mclate** [comment]
Looks like this is due to how `reverse` is implemented. I see that it applies `transform: scale3d(-1, 1, 1);` style to a whole `q-linear-progress`

**Comment by webnoob** [comment]
@mclate As a work around, just do another transform on your content: https://codepen.io/webnoob/pen/wvMqbKG

@pdanpdan Do you have a suggested fix for this? Could we just re-apply a transform around the default slot content (similar to what I've done in the codepen above)?

**Comment by webnoob** [comment]
Fix available in 1.12.9
