### ISSUE TITLE
Components like dialogs move outside body on fullscreen request without target

### ISSUE THREAD

**Issue by blaspix-tech** [quasarframework/quasar#7262]
Hello @rstoenescu , 

Replacing "document.documentElement" by "document.body" fixes the issue.
Reference: https://github.com/quasarframework/quasar/blob/dev/ui/src/plugins/AppFullscreen.js#L28

Cheers

**Comment by rstoenescu** [comment]
Hi,

This should not happen if on latest Quasar v1.12.6... Please reopen if you're on 1.12.6 and still experiencing problems.
