### ISSUE TITLE
about the commonent of vue and their use

### ISSUE THREAD

**Issue by gxlqssjf** [quasarframework/quasar#7267]
**Describe the bug**
how to use vue components in orgin website? I use then follow the guide of the orgin website

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**
quasar.conf.js config framework:
![图片](https://user-images.githubusercontent.com/1277598/85247064-30281180-b47f-11ea-99ce-40813db9512c.png)
use like：
![图片](https://user-images.githubusercontent.com/1277598/85247086-3fa75a80-b47f-11ea-8b41-8b384f36e58d.png)
why the browser consol has bug:
![图片](https://user-images.githubusercontent.com/1277598/85247119-5baafc00-b47f-11ea-9a7f-d4d8d4572fe7.png)

another bug:

use:
![图片](https://user-images.githubusercontent.com/1277598/85247162-7d0be800-b47f-11ea-8622-801349462066.png)
browser console:
![图片](https://user-images.githubusercontent.com/1277598/85247149-6feef900-b47f-11ea-9b83-2beaaa01ba88.png)

**Platform (please complete the following information):**
OS: win10
Node: 14.4.0
NPM: 6.14.5
Yarn:1.22.4
Browsers:chrome or firefox
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

If you are using "@quasar/app" v2, then instead of `framework: 'all'` use: `framework: { importStrategy: 'all' }`.

If you are using "@quasar/app" v1, then instead of `framework: 'all'` use: `framework: { all: true }`.
