### ISSUE TITLE
importStrategy auto not working correctly

### ISSUE THREAD

**Issue by fess932** [quasarframework/quasar#7269]
```
importStrategy: 'auto',
config: {
        loading: {
          spinner: 'QSpinnerInfinity',
          delay: 40
        }
      }
```
![image](https://user-images.githubusercontent.com/17965077/85259252-665e9480-b471-11ea-8c00-aa18036e61b9.png)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. This does not have anything to do with auto-import. But regardless a bug was in another place and it got fixed. Will be available in "@quasar/app" v2.0.1.

**Comment by smShakil** [comment]
@rstoenescu same issue again. `importStrategy: 'auto'` stopped working again for me.

**Comment by rstoenescu** [comment]
@smShakil tested again. couldn't reproduce. looked at the code -- everything checks out...
