### ISSUE TITLE
[Proposal]Weibo-style Image Gallery Component

### ISSUE THREAD

**Issue by landall** [quasarframework/quasar#727]
I'd like to ask if the image gallery component can support the style of weibo or wechat.
(apologize that i haven't found the english version of the apps)

Features:
1. List a thumbnail image as a grid of 1x1, 2x1, 3x1, 2x2, 3x2 3x3.
![new image - mtz5w](https://user-images.githubusercontent.com/7061302/28307003-fabe4cfe-6bd3-11e7-9c69-35ace0bec742.jpg)

2. click a thumbnail, display the (middle) image fit to full screen
![new image - v9fkc](https://user-images.githubusercontent.com/7061302/28307002-fabe263e-6bd3-11e7-930e-efcf5ec04a10.jpg)

3. touch hold to move the view port of the image
![new image - 3oivm](https://user-images.githubusercontent.com/7061302/28307001-fabe026c-6bd3-11e7-884f-32bd96ddd108.jpg)

4. the image can be stretched to zoom in. 
![new image - scgnk](https://user-images.githubusercontent.com/7061302/28307005-fac5148a-6bd3-11e7-8059-fa7232eafb63.jpg)

5. double click the image to zoom in or zoom out

6. with a action list to do some thing (in the image below, the actions are saving the image, viewing the original image, retweeting, sending a like, cancelling) 
![new image - nmx7q](https://user-images.githubusercontent.com/7061302/28307004-fac2209a-6bd3-11e7-8fda-97a0fdf10bb4.jpg)

**Comment by jolee11** [comment]
Having a component to view an image which support zoom in zoom out seems quite necessary!
