### ISSUE TITLE
QSelect: allow to add new value via calling a function directly (without calling an event dispatcher)

### ISSUE THREAD

**Issue by dmitry** [quasarframework/quasar#7270]
**Is your feature request related to a problem? Please describe.**
While using QSelect I'd like to add new value by clicking on the button with a mouse. Currently it's bound to the keyboard keydown event.

**Describe the solution you'd like**
Would be great to have a separate function for that with public interface (not with prefix `__`).
`done` is prepared inside the function (`__onTargetKeydown`) which is accessible only when you call a `dispatchEvent`, as event passed should have `e.target.id` which only can be set internally via dispatch event.

**Describe alternatives you've considered**
Current solution is to prepare keyboard event and dispatch it as event:

```
      this.$refs.select.$refs.target.dispatchEvent(
        new KeyboardEvent('keydown', {
          key: 'enter',
          keyCode: 13,
          code: 'enter',
          which: 13,
          shiftKey: false,
          ctrlKey: false,
          metaKey: false
        })
      )
```

**Comment by pdanpdan** [comment]
Creating a new value is adding it to the list of options. Please create a codepen showing what you are trying to achieve, because I think I didn't understand.

**Comment by dmitry** [comment]
@pdanpdan currently it's only possible to add value using "enter" keydown event. I'd like to have ability to call add method by on click on the button. I will try to add codepen example soon.

**Comment by pdanpdan** [comment]
Hello. When you have a detailed explanation of what you are trying to do with an example please comment here and we'll reopen.
