### ISSUE TITLE
Chrome Warnings - GenerateSW has been called multiple times

### ISSUE THREAD

**Issue by Basgrani** [quasarframework/quasar#7272]
**Describe the bug**
Console warnings when run to pwa mode:

```
[WDS] Warnings while compiling.
GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information
```

**Codepen/jsFiddle/Codesandbox (required)**
not aplicable

**To Reproduce**
1. run in pwa mode
2. update pages/index.vue
3. save  and auto-reload
4. show warning in console

**Expected behavior**

**Screenshots**
https://www.dropbox.com/s/qbqje4v7uy5sojp/bug1.png?dl=0

**Platform (please complete the following information):**
OS: MacOS Catalina 10.15.5
Node: 10.18.1
NPM: 6.13.4
Yarn:
Browsers: Chrome Version 83.0.4103.106 (Build oficial) (64 bits)
iOS:
Android:
Electron:

**Additional context**
Quasar/app v2 1.12.7

**Comment by rstoenescu** [comment]
Hi,

Like it is described in https://github.com/GoogleChrome/workbox/issues/1790 there is no good way to fix this (especially from Quasar side). However, we do not want to supply a dummy service worker in dev mode because that would make the whole developer experience awful. You'd be able to test your service worker only on production builds which adds a lot of overhead and time lost. But like we wrote in our docs, when you develop an app and your goal at that moment does not include handling the service worker, you can temporarily switch to "quasar dev -m spa". Wish the workbox team would find a way to avoid the issue, but at the moment, it is what it is.

**Comment by Basgrani** [comment]
ok, Thanks!

**Comment by samgermain** [comment]
> you can temporarily switch to "quasar dev -m spa"

What does that mean? Switch what?

**Comment by jmunckhof** [comment]
> > you can temporarily switch to "quasar dev -m spa"
> 
> What does that mean? Switch what? Would that be a solution with React and Webpack?

I don't think so, same issue here 🙋🏻‍♂️, Any updates on this?

**Comment by rstoenescu** [comment]
I think I explained it clearly the first time. https://github.com/GoogleChrome/workbox/issues/1790
It's kind of out of our reach. Just ignore it as it will not break anything. @jmunckhof

**Comment by jmunckhof** [comment]
> I think I explained it clearly the first time. [GoogleChrome/workbox#1790](https://github.com/GoogleChrome/workbox/issues/1790)
> It's kind of out of our reach. Just ignore it as it will not break anything. @jmunckhof

Oh Okay, Is there a way to suppress these warnings?

**Comment by zenflow** [comment]
> Oh Okay, Is there a way to suppress these warnings?

@jmunckhof Disabling webpack watch mode in `pwa.extendWebpackCustomSW` in `quasar.conf.js` worked for me: 

```js
    // https://v2.quasar.dev/quasar-cli-webpack/developing-pwa/configuring-pwa
    pwa: {
      workboxPluginMode: 'GenerateSW', // 'GenerateSW' or 'InjectManifest'
      workboxOptions: { ... },
      manifest: { ... },
      extendWebpackCustomSW (cfg) {
        // Disable watch mode - See https://github.com/quasarframework/quasar/issues/7272
        cfg.watch = false
      }
    }
```

I believe only Quasar v2 has this config option

**Comment by rupam71** [comment]
Disable this in next js for development environment,

```
const prod = process.env.NODE_ENV === 'production'
const withPWA = require('next-pwa')({
    dest: 'public',
    register: true,
    disable: prod ? false : true,
    skipWaiting: true
});
```
