### ISSUE TITLE
In PWA mode (+ InjectManifest), error during service worker registration since quasar/app v2

### ISSUE THREAD

**Issue by Brice155** [quasarframework/quasar#7273]
**Describe the bug**
In PWA mode, error during service worker registration since quasar/app v2 :
createCacheKey.js:23 Uncaught add-to-cache-list-unexpected-type: An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry 'undefined' isn't supported. You must supply an array of strings with one or more characters, objects with a url property or Request objects.

**Codepen/jsFiddle/Codesandbox (required)**
I can't reproduce with a codepen... i don't know how to do...

**To Reproduce**
1. In quasar.config.js : pwa > workboxPluginMode: 'InjectManifest'
2. Fill some values for the manifest. Here is my configuration :
 manifest: {
        name: `name`,
        short_name: `short name`,
        display: 'fullscreen',
        orientation: 'portrait',
        background_color: '#ffc000',
        theme_color: '#ff00ee',
        start_url: '.',
        icons: [
          {
            'src': 'icons/icon-128x128.png',
            'sizes': '128x128',
            'type': 'image/png'
          },
          {
            'src': 'icons/icon-192x192.png',
            'sizes': '192x192',
            'type': 'image/png'
          },
          {
            'src': 'icons/icon-256x256.png',
            'sizes': '256x256',
            'type': 'image/png'
          },
          {
            'src': 'icons/icon-384x384.png',
            'sizes': '384x384',
            'type': 'image/png'
          },
          {
            'src': 'icons/icon-512x512.png',
            'sizes': '512x512',
            'type': 'image/png'
          }
        ]
}
3. Create the file "custom-service-worker.js" with : 
importScripts('https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js')
workbox.precaching.precacheAndRoute([ self.__WB_MANIFEST ], {})
4. Run the app in debug mode : quasar dev -m pwa --debug
5. Check in the browser and see the following error :
createCacheKey.js:23 Uncaught add-to-cache-list-unexpected-type: An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry 'undefined' isn't supported. You must supply an array of strings with one or more characters, objects with a url property or Request objects.
    at createCacheKey (https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-precaching.dev.js:76:15)
    at PrecacheController.addToCacheList (https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-precaching.dev.js:280:15)
    at precache (https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-precaching.dev.js:1157:26)
    at Object.precacheAndRoute (https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-precaching.dev.js:1192:7)
    at eval (webpack-internal:///./src-pwa/custom-service-worker.js:76:20)
    at Object../src-pwa/custom-service-worker.js (http://localhost:1977/service-worker.js:1031:1)
    at __webpack_require__ (http://localhost:1977/service-worker.js:20:30)
    at http://localhost:1977/service-worker.js:84:18
    at http://localhost:1977/service-worker.js:87:10

**Expected behavior**
self.__WB_MANIFEST has not to be 'undefined'.

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: windows 10
Node: N/A
NPM: 6.13.7
Yarn:N/A
Browsers: Chrome v83
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
Quasar/app v2 and quasar v1.12.7.
For additional information, i followed the App CLI v2 Upgrade Guide

**Comment by Brice155** [comment]
Not an issue since i tested wihout "workbox.precaching.precacheAndRoute([ self.__WB_MANIFEST ], {})" and it works

**Comment by rstoenescu** [comment]
Thanks for the follow-up.
