### ISSUE TITLE
Quasar CLI - "quasar create" Install issue

### ISSUE THREAD

**Issue by smartops-main** [quasarframework/quasar#7274]
I just downloaded the CLI for the first time, ran 

Quasar create

Accepted all the defaults and for the options/packages I selected Axios and Lint.  After approximately 30mins waiting at the es lint processing prompt during the install process, I get the following error:

  39264:50   error  Identifier '__webpack_require__' is not in camel case                                                                 camelcase
  39268:32   error  Identifier 'vue__WEBPACK_IMPORTED_MODULE_0__' is not in camel case                                                    camelcase
  39269:32   error  Identifier 'vue__WEBPACK_IMPORTED_MODULE_0___default' is not in camel case                                            camelcase
  39290:29   error  Identifier '__webpack_exports__' is not in camel case                                                                 camelcase
  39290:50   error  Identifier '__webpack_require__' is not in camel case                                                                 camelcase
  39298:21   error  Do not access Object.prototype method 'hasOwnProperty' from target object                                             no-prototype-builtins
  39315:24   error  Identifier '__WEBPACK_EXTERNAL_MODULE_vue__' is not in camel case                                                     camelcase

✖ 149920 problems (149920 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scholarassist@0.0.1 lint: `eslint --ext .js,.vue ./ "--fix"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scholarassist@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2020-06-22T17_10_35_575Z-debug.log

 npm install FAILED... Possible temporary npm registry issues?
 Please try again later...

I don't really need lint so would the best option to go back through another 'quasar create' and remove lint support?  The lint processor was consuming 50% CPU for at least 30minutes before spitting out the above garbage.

This was an empty directory install, the latest quasar CLI install / NPM....

**Comment by webnoob** [comment]
Sorry for the delay in responding to this. Something is definitely off with this.

Did you ask it to use yarn on the prompts or NPM for dep management?

If it was yarn, can you zip up the folder it created (quasar project) and add it to this issue please. I'll take a look.

**Comment by webnoob** [comment]
Assuming you've sorted this as no response. Closing.
