### ISSUE TITLE
Editable qSelect

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7275]
**Is your feature request related to a problem? Please describe.**
I want to be able to show a list of options and let the user enter his own option.

**Describe the solution you'd like**
An editable qSelect where the user can select an option from the list and be able to enter one on his own.

**Additional context**
use-input let the user enter his own text but when focusing another component, the text disappears. Maybe because the value is not one of the given options?

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/select#Example--Text-autocomplete
