### ISSUE TITLE
QTable virtual scroll with resize does not display correctly

### ISSUE THREAD

**Issue by sinbino** [quasarframework/quasar#7276]
**Describe the bug**
In QTable with virtual scroll, when I increase the size of the table after mount, the table row layout is broken.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/sinbino/pen/WNrjxav?editors=1010

**To Reproduce**
1. Open the url of the above codepen.
2. Resize the window so the table height is as small as possible and reload the browser.
3. Resize the window so that the table height is as large as possible.
4. Scroll down the table.
5. The layout of the table is broken after the 30th row.

**Expected behavior**
The table layout is displayed correctly.

**Screenshots**
https://i.imgur.com/Hep8HHe.png

**Platform (please complete the following information):**
(Use vue-cli-plugin-quasar)
OS: client is MacOS10.15.5, server is alpine linux 3.11.6
Node: v12.15.0
NPM: 6.13.4
Browsers: Chrome 83.0.4103.106

**Comment by sinbino** [comment]
I tried to observe the height of the q-table and update the virtual-scroll-slice-size with the optimal number of rows, but it seems to have no effect.
Is virtual-scroll-slice-size not a reactive property?
If the first to give a large enough value to the virtual-scroll-slice-size, it will go well, but I think that there is some waste.
If possible, I would like to update the slice size dynamically with the size of the table.

**Comment by zknic** [comment]
> I tried to observe the height of the q-table and update the virtual-scroll-slice-size with the optimal number of rows, but it seems to have no effect.
> Is virtual-scroll-slice-size not a reactive property?
> If the first to give a large enough value to the virtual-scroll-slice-size, it will go well, but I think that there is some waste.
> If possible, I would like to update the slice size dynamically with the size of the table.

:table-style="{ maxHeight: $q.screen.height-215+'px' }"

**Comment by pdanpdan** [comment]
`virtual-scroll-slice-size` is a little bit particular
- the value passed to the property is used as the minimum number of items to be rendered
- based on the item size (`virtual-scroll-item-size`) and the size of the window, another value is computed as 2 * number of elements to fit in the window
- the max of these 2 values is used

I think you have 2 solutions:
- use a large enough value for `virtual-scroll-slice-size` (estimate the largest expected window height, divide by the row height and make duble) - it should make no big difference on rendering if the rows are not extremelly complex
- use an observer and something like this (but it's using an internal method and some refs) - https://codepen.io/pdanpdan/pen/wvMdJoG?editors=1010

**Comment by sinbino** [comment]
I don't assume complex row extremely. 
I'm worried about using the internal method, so I decided to get a large enough slice size. 
(I used twice the count of lines that fit in the height of the display device)
