### ISSUE TITLE
importStrategy can't used in render component 

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar#7278]
i used the config importStrategy: 'auto'，it works in 。but it can't work in render (h) {return h('q-tr', 'test')}.
![e1](https://user-images.githubusercontent.com/11263870/85378626-604dde00-b56d-11ea-8d61-1b9408bd80dc.jpg)
![e2](https://user-images.githubusercontent.com/11263870/85378630-617f0b00-b56d-11ea-9583-92f568424032.jpg)
![e3](https://user-images.githubusercontent.com/11263870/85378631-617f0b00-b56d-11ea-8001-c0864dc2644b.jpg)

**Comment by pdanpdan** [comment]
Hello. This is normal and expected - the auto-import feature is for HTML templates - in the render functions you need to import the component and use it as a component. Only already globally installed components and native DOM elements can be used with the string notation.

**Comment by rstoenescu** [comment]
@zknic Instead of writing `q-tr` you can:

```
import { QTr } from 'quasar'
// ....
h(QTr, ....)
```

**Comment by zknic** [comment]
> @zknic Instead of writing `q-tr` you can:
> 
> ```
> import { QTr } from 'quasar'
> // ....
> h(QTr, ....)
> ```

Thx! quasar has the best front-end optimization.
