### ISSUE TITLE
File included in client/server-manifest that should not be there

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#7279]
**Describe the bug**
We use PM2 to run our app in production. For this we have defined an ecosystem.config.js which is in the root of our repository. When we do a SSR build we use a CopyPlugin to transfer this file also to the /dist/ssr/ folder as we want this in the root there to start our application with it. We use this code in `quasar.conf.js`

```js
extendWebpack(cfg, { isServer, isClient }) {
	if (ctx.prod && ctx.modeName == "ssr") {
		cfg.plugins.push(
			new CopyPlugin({ patterns: [{ from: "ecosystem.config.js", to: "./../ecosystem.config.js" }] })
		);
	}
}
```
We recently switched to @quasar/app v2 and with the new SSR build I noticed the client-side on the browser trying to request this `ecosystem.config.js` file, which of course fails because it is outside of the `www` folder. When I checked this file is included in the `quasar.client-manifest.json` and the `quasar.server-manifest.json`.

```json
{
  "publicPath": "/",
  "all": [
    "../ecosystem.config.js",
```

I don't know why this happens but this file should not be in there as something outside the `www` folder cannot be requested and results in 404's on the client side.

**Expected behavior**
Files outside of the www folder should be excluded from this generated manifest.

**Additional context**
@quasar/app@2.0.0 and quasar@1.12.6

**Comment by rstoenescu** [comment]
Hi,

The copy-webpack-plugin pushes an entry for each file in the webpack asset list and the vue ssr render plugin looks at this list to generate the manifest file.

What you should do instead is to use the quasar.conf.js > build > afterBuild() hook and manually copy that file to the desired destination (use `fs` or `fs-extra` to do this -- also, no need to install fs-extra as it is supplied by q/app out of the box).

**Comment by Evertvdw** [comment]
Hi, that works thanks!

For reference, here is the same thing with afterbuild:
```
afterBuild() {
	if (ctx.prod && ctx.modeName == "ssr") {
		fs.copyFileSync("ecosystem.config.js", "dist/ssr/ecosystem.config.js");
	}
},
```
