### ISSUE TITLE
QInput floating label will overlap value when it's a numeric type and has a value of zero

### ISSUE THREAD

**Issue by Phunky** [quasarframework/quasar#728]
QInput floating label will overlap value when it's a numeric type and has a value of zero on the current beta build.

![image](https://user-images.githubusercontent.com/67351/28326685-5d902a78-6bd9-11e7-8cab-0bf12592654c.png)

Could not reproduce this on the stable release.

**Comment by rstoenescu** [comment]
Will fix it. Thanks for reporting.
