### ISSUE TITLE
QSlideItem - Slide Action Active color

### ISSUE THREAD

**Issue by pietrorobbi** [quasarframework/quasar#7282]
**Is your feature request related to a problem? Please describe.**
I've have a UX problem with slide item: it's difficult to undersand for the user when sliding traslation fire action.

**Describe the solution you'd like**
My idea is add a "ActiveColor[left/right/...]" props. 
That color is applied on background when "this.__scale === 1"
#7288

**Comment by pietrorobbi** [comment]
Hi, i'm new on Quasar community, no interest on this feature?

**Comment by pdanpdan** [comment]
I would suggest another approach: a @slide event that is emitted while sliding and that allows changing colors/texts in the slots as required

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.15.2.

**Comment by pietrorobbi** [comment]
Good suggest! Thank you
