### ISSUE TITLE
QStep header-nav always true for current step

### ISSUE THREAD

**Issue by mv-go** [quasarframework/quasar#7284]
**Describe the bug**
Header navigation seems to always be true (active) on a current `q-step`. I attempted to set linear navigation following the example from docs (links below) and found that current step would always have `header-nav` enabled on it, unless `header-nav` is set to `false` on parent `q-stepper` (which disables header navigation for all steps, which defeats the purpose).

**Codepen/jsFiddle/Codesandbox (required)**
Can be found right in the docs here https://quasar.dev/vue-components/stepper#Example--Linear-header-navigation
Direct link to CodePen https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fquasar.dev%2Fvue-components%2Fstepper

**To Reproduce**
Set `header-nav: true` to q-stepper
Set `header-nav: false` to all q-steps
All steps will have header-nav disabled except for the current one

**Expected behavior**
Header-nav on q-step to always override header-nav on q-stepper.

**Platform (please complete the following information):**
any

**Additional context**
Maybe we could go further and provide some sort of validation Fn to `q-stepper` `header-nav` prop, similar to the `q-input` component approach, like so
`:headerNav="isEnabled"`
...and later in methods...
`isEnabled (step) { return this.currentStep > step }`

**Comment by webnoob** [comment]
I've read this 5 times and I don't understand the issue properly.

Are you saying that the current QStep shouldn't be clickable? What problems is this causing?

**Comment by mv-go** [comment]
My apologies for not being clear on this one.

You are basically correct. Current step (just as any other step) should not be clickable if it has its `:header-nav="false"`.
Current behaviour is, in my humble opinion, somewhat misleading.

Maybe this will help:

Have `q-stepper` with `header-nav`.
Have one of the `q-step`s' `:header-nav="false"` (or any condition that returns false)
This step will still be clickable and have hover effects (so essentially have its header-nav enabled) when it's "current".

Demonstrated in this codepen (slightly modified 'Linear Header Navigation' example from quasar docs). Step 2 has `:header-nav="false"`, and step 3 has `:header-nav="step > 4"` (which is ultimately false as well), but both of these steps are coverable and clickable when they are "current". https://codepen.io/mv-go/pen/xxZPZJr?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fstepper

From my perspective (developer) this behaviour is not clear, as I'm expecting `header-nav` prop on `q-step` to control the behaviour.
From user perspective (what I'm trying to achieve) is to not misguide user by suggesting there is some action or change happening in the background, when he or she clicks on the current step in the header.

Hope this helps and once again my apologies for not being clear in the first place.

**Comment by webnoob** [comment]
Thanks for that extra information.

I've done a PR for this but I honestly don't know if it will be merged or not. I couldn't find any reference which explains it was forcing the header to be navigable when it was active but I can't see any side effects with it being removed either.

We'll have to see what Razvan says (he generally has some very smart reason why something is the way it is). 

I won't be merging this PR until it has Razvan's approval though so it might be a little wait as he's off sick at the moment.

**Comment by webnoob** [comment]
Will be available in 1.12.11
