### ISSUE TITLE
QSelect change input on mouse focus

### ISSUE THREAD

**Issue by sgauthiertremblayOpenmindt** [quasarframework/quasar#7286]
**Describe the bug**
When we navigate in a form using only the keyboard (TAB key), we select a value in the qSelect, move the mouse a little and press tab, there's a chance that the value change for what the mouse was hovering in the close transition.

**Expected behavior**
Disable mouse hover in the close transition

**Screenshots**
https://www.berrycast.com/conversations/fefff098-9025-54bb-abef-fba0727ecbee

**Comment by sgauthiertremblayOpenmindt** [comment]
After testing with transitions, I think that the problem come from the mouse hover delay. I think that if this delay could be customizable, it could solve this problem.

**Comment by pdanpdan** [comment]
Interesting case :)

**Comment by pdanpdan** [comment]
I cannot reproduce it in any way that does no imply a voluntary action of the user to obtain that effect.
If you can find a way to reproduce it in natural, not forced way, please comment here and I'll reopen.
