### ISSUE TITLE
CSS class non-selectable allows me to select an image.

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#7287]
**Describe the bug**
CSS class `.non-selectable` allows me to select an image.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/whoacowboy/pen/LYGyQvx

**To Reproduce**
Drag the image on the left, it is selectable.

**Expected behavior**
It would not be selectable.

**Platform (please complete the following information):**
OS: Mac Chrome

**Additional context**
This fixes it.
```
.non-selectable {
  user-select: none;
  pointer-events: none;
}
```

**Comment by pdanpdan** [comment]
Hello. You are confusing selectable with draggable.
