### ISSUE TITLE
Bug: v0.14 v-model prop on q-layout for the sides prop doesn't show drawer

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#729]
### Steps to reproduce
1. Use this snippet
```pug
  q-layout(v-model="sides" view="hHh Lpr fFf" v-if="!$auth", :left-breakpoint="1024")
      q-toolbar(slot="header")
        q-btn(flat round small @click="sides.left = !sides.left")
          q-icon(name="menu")
        q-toolbar-title {{$auth ? $auth.name : 'Default Admin'}}
      router-view(:trybes="$trybes")

      div(slot="left")
        q-list(no-border link inset-separator)
          q-list-header Navigation
```
2. Add sides to data function of the component like this

```javascript
data() {
  return {
   sides: {
    left: false,
    right: false
   }
  }
}
```

3. Try to open the left drawer on mobile mode 

### What is Happening
![image](https://user-images.githubusercontent.com/25447231/28332581-ecebafe6-6c27-11e7-9981-d6d7903334bd.png)

### What is Expected
![image](https://user-images.githubusercontent.com/25447231/28332486-9c05ee66-6c27-11e7-9d8c-7a85cc69df8b.png)

**Comment by rstoenescu** [comment]
V-model works only to tell Layout to show one or the other side when on a large window (above the threahold). This differs from the show/hide methods which do not take into account window size.

**Comment by laurentpayot** [comment]
@ralphchristianeclipse see https://github.com/quasarframework/quasar/issues/479
