### ISSUE TITLE
QDialog with `content-class` or `content-style` involving background color negatively affects overlays.

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#7294]
**Describe the bug**
Opening a QDialog with `content-class` or `content-style` involving background colour causes the overlay to completely obscure the background page, in contrast with the nice 'faded' affect when no custom colours are used. In addition, it seems that the content class / style _isn't_ actually applied to the dialog content itself.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/bGEWXxB?editors=1010

**Expected behavior**
That the background colour / class would _only_ affect the QDialog content, and not the page overlay.

**Platform (please complete the following information):**
OS: Windows
Browsers: Firefox, Chrome

**Comment by pdanpdan** [comment]
Content-class/style are there to apply to all. Make your classes to apply css specific to the components you want.
