### ISSUE TITLE
Move to Bootstrap 5 for next version

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#7295]
Hello Team;

As new and nicer features coming to Bootstrap 5 and removal of jQuery, it would be great if quasar can move from Material Design to BS5 or allow us to choose from the two in Quasar CLI when we create our project or replace an existing MD project to BS project in V2 for Vue 3

**Comment by pdanpdan** [comment]
Hello. Quasar is not using Bootstrap or other CSS framework for it's CSS.
