### ISSUE TITLE
QUploader - Uploading duplicate file should be allowed with minor name change

### ISSUE THREAD

**Issue by coopersamuel** [quasarframework/quasar#7298]
Related to this [ticket](https://github.com/quasarframework/quasar/issues/6537). When I attempt to upload two files with the same name, the second file is simply ignored. I'd like the uploader to allow duplicate files by mimicking the functionality of most browsers and operating systems. For example, if the first image is `name.jpg`, the next image is `name (1).jpg`, next is `name (2).jpg` and so on.

If this is not possible, I'd like to at least be able to build this myself by hooking into events. Currently, if a duplicate file is added, the `added` event is emitted, but the file argument is empty.

**Comment by coopersamuel** [comment]
@rstoenescu bump on this. 

At the very least I should be able to hook into this to display an error message to users. When a file with duplicate name is uploaded it is simply ignored, it does not trigger the `@rejected` event nor can I manually see the file with a `:filter`.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v2.2.4 -- duplicate files should also make QUploader/QFile emit the `@rejected` event; and by doing so the files can be renamed and added under a different name.
