### ISSUE TITLE
Draggable tree

### ISSUE THREAD

**Issue by fjl280855990** [quasarframework/quasar#7299]
**Is your feature request related to a problem? Please describe.**
The location of nodes cannot be changed quickly

**Describe the solution you'd like**
My idea is add a "draggable" props.
Nodes can be dragged when "draggable === true"

**Describe alternatives you've considered**
https://codepen.io/fjl280855990/pen/OJMgpaM?editable=true%3Dhttps%3A%2F%2Felement.eleme.cn%2F

**Comment by webnoob** [comment]
This is not something we will be implementing on core, however, a user has created an App Extension for this so if you're using the Quasar CLI then you can make use of this: https://github.com/mayank091193/quasar-draggable-tree

**Comment by fjl280855990** [comment]
thanks
