### ISSUE TITLE
Bug: v0.14 q-tabs TabMixin errors when using q-tab and q-tab-pane 

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#730]
### What is Happening

Too many errors when using the q-tabs like this

```pug

```

the errors points to TabMixin 

based on my understanding the inject prop is undefined so i tried to fix it like this

![image](https://user-images.githubusercontent.com/25447231/28337281-bbc634d0-6c37-11e7-8255-5a31aaa8164f.png)

### What is Expected

It works after the fix

![image](https://user-images.githubusercontent.com/25447231/28337294-c6c3782a-6c37-11e7-9a50-ba92d9a470be.png)

**Comment by rstoenescu** [comment]
There is a bug in Vue 2.4.x which is being worked on. Downgrade to Vue 2.3 in the mean time.

More info here (including vue bug link): https://github.com/quasarframework/quasar/issues/710
