### ISSUE TITLE
Tree node double click event

### ISSUE THREAD

**Issue by fjl280855990** [quasarframework/quasar#7300]
Is your feature request related to a problem? Please describe.
Sometimes when editing a node, you need to quickly edit the corresponding event, for example, double-click a node to edit it

Describe the solution you'd like
My idea is add a "@update:dblclick" event.
But it conflicts with the @update:selected event

**Comment by webnoob** [comment]
Would `@dblclick.native="someFunction"` not suffice?

**Comment by fjl280855990** [comment]
This is not on the document..
