### ISSUE TITLE
Favor includes() vs indexOf() in QSelect filtering

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#7301]
For example in https://quasar.dev/vue-components/select#Example--Basic-filtering the code for filtering uses _indexOf_ for filtering: 

`stringOptions.filter(v => v.toLowerCase().indexOf(needle) > -1)`

Where _includes_ is semantically closer to what is to achieve. 

`stringOptions.filter(v => v.toLowerCase().includes(needle))`

I suggest switching in the code examples to the latter, to encourage using this method.

**Comment by pdanpdan** [comment]
Please attach jsperf compare of the two - in at least chrome/firefox/safari

**Comment by pdanpdan** [comment]
From this test the performance is very erratic on browsers and situations: https://jsperf.com/array-indexof-vs-includes/62
Something against the .includes is that it's not supported in IE11

**Comment by webnoob** [comment]
@pdanpdan Do you plan on doing anything else with this one? From my perspective, if users want to use indexOf vs includes then it's up to them. Better to have the one in the example that works globally than to let the copy / paste people get it wrong and not know why....

**Comment by pdanpdan** [comment]
I'm waiting for the required analysis from the OP.
