### ISSUE TITLE
[Request] Export mixins

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#7302]
**Is your feature request related to a problem? Please describe.**
I am developing an app extension and it would be convenient to use quasar mixins. For example transition.js

**Additional context**
in version v0.15 it was accepted: #1113

**Comment by webnoob** [comment]
You can still import them via:

`import TransitionMixin from 'quasar/src/mixins/transition.js'`. 

They're just not exported as named exports in the package.
