### ISSUE TITLE
Slow since upgrade to @quasar/app v2

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#7304]
**Describe the bug**
Hi there, I recently upgraded our project to @quasar/app v2. Before that we used quasar@1.12.4 and @quasar/app@1.9.6. Since that upgrade one of our components suddenly is very unresponsive, there is a 2 second delay between click and action. Where as before the response to the click had no noticable delay. 

Has something changed also in that update in one of the component we use in there?
I will try to draw our component structure:
```html
<q-dialog>
  <div>
    <q-layout>
      <q-page-container>
        <q-page>
          <q-table grid>
            <q-intersection v-for="i in 1000">
              <q-img></q-img>
            </q-intersection>
          </q-table>
        </q-page>
      </q-page-container>
    </q-layout>
  </div>
</q-dialog>
```

We have a media gallery with a lot of images (around 1000) with a Q-intersection. Before the upgrade filtering and searching this list was fast and with no (noticable) delay. 

Since the upgrade before searching and filtering and even closing the dialog, there is a 2 second delay in which everything is blocked and you cannot do anything. Anyone with ideas about what is happening and why there is such a decrease in performance?

It becomes a lot better once you reduce the number of items but that is of course not a fix for this problem. Especially because it used to work ok. 

**Codepen/jsFiddle/Codesandbox (required)**
I hope that one of the developers will see this and think of something that changed recently with one of these components that could have caused this. If that is not the case I will see if I can make a reproducible example.

**Video illustrating the behaviour**
[Captures.zip](https://github.com/quasarframework/quasar/files/4835872/Captures.zip)

**Expected behavior**
To be at least just as fast as before

**Comment by pdanpdan** [comment]
Try to use consecutive versions of the Quasar framework and find the one that works well and the one that does not. Then tell us the versions.

**Comment by Evertvdw** [comment]
@pdanpdan Not so easy as the @quasar/app needs quasar>1.12.6.

**Comment by Evertvdw** [comment]
Ok, I was able to do some testing. I used @quasar/app 1.9.6 and then updated quasar step by step to 1.12.6 but that still works fine. Also tried to turn on modern build there, but that also still worked fine.

Only change not accounted for then is @quasar/app from 1.9.6 > 2.0.0. Is it maybe something babel related with compilation of the code?

**Comment by Evertvdw** [comment]
Ok, I've been looking into this for a while now, trying to reproduce a sandbox with the problem but I guess I have another issue which is hard to reproduce... 

I did some more thinking about the problem and I have a hypothesis about what is happening. It seems since appv2 that when you filter the list of items in the table, it does this:

- Filter the array based on filter function
- Destroy items no longer visible
- Check which items need to be displayed
- Create these items, get images in my case
- Render everything at once (everything is visible immediatly)

Before it did something like this:
- Filter array based on filter function
- Destroy items no longer visible
- Check which QIntersection items need to be displayed
- Render these items (you then see the image loading spinner with the previous image at that location still visible)
- Create the items (one by one the new images start to appear)

So probably it is not technically slower but now everything is blocked and you don't get immediate feedback when you type/filter something, which make the perceived performance very bad. Seems very likely that this is something that was async, suddenly becoming sync or something like that, causing the Vue render thread to be blocked not reacting to the initial list filtering but instead immediately going on to create/delete all the components based on that change.

**Comment by pdanpdan** [comment]
Can you please try @quasar/app 1.9.6 with the latest quasar 1.12.8?

**Comment by Evertvdw** [comment]
@pdanpdan that combination also works fine. I'm currently investigating when destroyed/mounted and nextTicks after those are called in each version. Hoping to find some differences there that can pinpoint the issue :)

**Comment by Evertvdw** [comment]
@pdanpdan I added two videos as a zip in the description. There you can clearly see what I mean, also look at the console to see the difference between the two versions.

**Comment by ibrainventures** [comment]
hi,
may unrelated .. but on wednesday, after the release of 2.0.1 qapp we also transfered our system to 2.0.1.
After some little twerks we had a running system, and "mostly subjectiv" we had the impression that there
was a little hickup .. 
Our investigation goes to the router direction, as we are working with a "catch all on root path" and may it
now intereferes with the /public (also now a root path) handling. We also saw some issues with unreachable 
code after some return s.  We tested some Browserlist-Rules, as we saw that the deployed code was with
the default qapp 2.0.1 browserlist was 10 - 20% bigger ..

We stopped at this point and switched back to 1.9.6 qapp .. where non of those effects were happend.

**Comment by ibrainventures** [comment]
good morning @pdanpdan,

in the q-app  <= 1.9.6 starter kit, the error route handling 

`if (process.env.MODE !== 'ssr') {
  routes.push({
    path: '*',
    component: () => import('pages/Error404.vue')
  })
}`

was outside the const routes array.

In q-app 2+ it is inside the array. To understand the reason or the possible changes, is it also okay to let it outside the routes array with the q-app 2+ ?

**Comment by pdanpdan** [comment]
Sure.

**Comment by Evertvdw** [comment]
@pdanpdan Are you looking into it or do you require something more from my side? As the need more info label is still on this issue.

**Comment by Evertvdw** [comment]
Maybe this is the culprit? https://github.com/zloirock/core-js/issues/677
Although I do not use Array.splice in my filter and I also don't know why that would cause the delay in closing the dialog.

**Comment by webnoob** [comment]
@Evertvdw Do you think you could work on a repro for this? I've seen the videos but we're unlikely to get anywhere without something to test against.

The problem is that given it's a QApp update, it essentially just affects the deps and the build side of things. The components themselves don't change.

**Comment by Evertvdw** [comment]
I can give it a go, it might be worthwile creating a sort of template resembling our project that I can use in such cases to reproduce problem. It will take a while though, we use SSR + Typescript and class components, which is quite some work to get up and running in a codesandbox. I will get back as soon as possible!

**Comment by webnoob** [comment]
Perfect, thanks. I'm keen to nail any perf issues but as I'm sure you're aware, it can be very difficult with so many variables at play.

I'll tag this as need more info for now.

**Comment by Evertvdw** [comment]
Ok, I've been at it the whole day yesterday and the conclusion is: I guess it's something with npm and package.lock.json.

I first created a codesandbox with our exact component and that worked fine. I then moved on to port our whole project onto that same codesandbox, including tests, babel configs, tsconfig and what not. After all that the bug was gone! But that joy soon faded as I found out that in that new setup my unit tests with Jest did not work anymore. Jest decided it did not like class components anymore, giving this error: 

```ts
TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)

       5 | </template>
       6 | 
    >  7 | <script lang="ts">
         | ^
       8 | import Vue from "vue";
       9 | import Component from "vue-class-component";
      10 | // import { Vue, Component } from "vue-property-decorator";

      at extendStatics (src/themes/default/components/static/shortcuts/SearchButton.vue:7:1)
```

With every unit test involving a Vue component. I spent a few hours trying to fix this with no success. I also tried using yarn instead of npm to install stuff in there but that did not work. 

At last I moved back to the original project and removed the package.lock.json and removed node_modules. Then installed again. That solved the problem in this topic and my unit tests kept working :)

So it is fixed, but it feels like I'm cord dancing here with things breaking so easely and without any clear reason why.

**Comment by webnoob** [comment]
Great info and this just highlights the fragility of the node eco system :)
Glad it's sorted.
