### ISSUE TITLE
Upgrade from QUASAR/App 1.9.6 to QUASAR/App 2.0.1

### ISSUE THREAD

**Issue by ghaddon** [quasarframework/quasar#7306]
**Describe the bug**
After upgrading to quasar/app 2.0.1 from quasar/app 1.9.6 I receive the following error message after running the following:

**run quasar dev -m spa**

Html Webpack Plugin:
  Error: TypeError: Cannot read property 'mode' of undefined
    
    - index.template.html:9 eval
      [.]/[app]/[html-webpack-plugin]/lib/loader.js!./src/index.template.html:9:36
    
    - index.template.html:14 module.exports
      [.]/[app]/[html-webpack-plugin]/lib/loader.js!./src/index.template.html:14:3
    
    - index.js:393 
      [shopping]/[app]/[html-webpack-plugin]/index.js:393:16
    
    - runMicrotasks
    
    - task_queues.js:97 processTicksAndRejections
      internal/process/task_queues.js:97:5
    
    - async Promise.all

**Codepen/jsFiddle/Codesandbox (required)**

no codepen

**To Reproduce**

1. run quasar dev -m spa

**Expected behavior**
Get a clean compile of SPA application.

**Screenshots**

nothing to see

**Platform (please complete the following information):**
OS: Windows 10 
Node: V12.8.0
NPM:  V6.14.5
Yarn: N/A
Browsers: Google Chrome: Version 83.0.4103.116 (Official Build) (64-bit)
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
The application compiles without error with Quasar/app 1.9.6

**Comment by rstoenescu** [comment]
Hi,

You've skipped one step from the upgrade guide. Exactly the one referring to /src/index.template.html.

**Comment by ghaddon** [comment]
I went through the upgrade steps and everything is working.
I just overlooked that one step.

Thanks for your help.

**Comment by baryon** [comment]
Where is upgrade guild to 2.0.1?

I got a message https://quasar.dev/start/upgrade-guide

> % quasar upgrade
>   Quasar CLI · Gathering information with npm...
> 
>   Congrats! All Quasar packages are up to date.

**Comment by ghaddon** [comment]
Just follow this link.
https://quasar.dev/quasar-cli/app-upgrade-guide#Upgrade-Guide

Gary
    On Tuesday, June 30, 2020, 06:49:06 PM MST, LI Long <notifications@github.com> wrote:  
 
 


Where is upgrade guild to 2.0.1?

I got a message https://quasar.dev/start/upgrade-guide


% quasar upgrade
Quasar CLI · Gathering information with npm...

Congrats! All Quasar packages are up to date.

**Comment by pkovalevmsis** [comment]
### **App CLI v2 Upgrade Guide**
https://quasar.dev/quasar-cli/app-upgrade-guide

**Comment by dili021** [comment]
> Just follow this link. https://quasar.dev/quasar-cli/app-upgrade-guide#Upgrade-Guide Gary On Tuesday, June 30, 2020, 06:49:06 PM MST, LI Long <notifications@github.com> wrote: Where is upgrade guild to 2.0.1? I got a message https://quasar.dev/start/upgrade-guide % quasar upgrade Quasar CLI · Gathering information with npm... Congrats! All Quasar packages are up to date. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I am having the same issue.
Following your link gives me a 404.
Looking through the [upgrade guide](https://quasar.dev/start/upgrade-guide#introduction) I can't see index.template.html mentioned anywhere.
