### ISSUE TITLE
Hide event not firing inside custom dialog component

### ISSUE THREAD

**Issue by LukeDisc** [quasarframework/quasar#7307]
**Describe the bug**
When using a custom component with the dialog, the hide method is never fired.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/rzb6s4pf/1/

**To Reproduce**
1. Click 'Open Dialog'
2. Click anywhere to close the dialog
3. The expected console log does not fire

**Expected behavior**
The hide event should be fired, so that the action can be stopped.

**Platform (please complete the following information):**
OS: Microsoft Windows 10 Pro 10.0.18363 N/A Build 18363
Node: 12.14.1
NPM: 6.13.4
Browsers: Chrome 83.0.4103.106

**Comment by pdanpdan** [comment]
Hello.
The 'hide' method is a method that can be called to close the dialog. It has no other hidden properties/use cases//internal magic except implementing the common interface.
To prevent close you need to use the QDialog in a :value/@input mode, and not change the value if you don't want.
https://jsfiddle.net/vw0t4bfj/2/
