### ISSUE TITLE
First App Won't Build In Electron Properly

### ISSUE THREAD

**Issue by vahost** [quasarframework/quasar#7308]
**Describe the bug**
This is my first app. When I test my app in Electron, my app works just fine with emulators for both Mac and PC. However, when I try to build the app, the resulting app on both platforms doesn't work properly.

The home page loads just fine. However, if I try to navigate to any other page, my home page opens just fine, but my other pages are all blank. Even if I am on the home page and I try to access the home page via the navigation, the page goes blank.

Dev Tools for these blank pages shows:

```
<html>
<head></head>
<body></body>
</html>
```
I can’t think of anything about these blank pages that could cause the problem because they’re not doing much of anything from a JS perspective. They mainly just contain HTML content.

I see in Dev Tools under Sources that there are three folders: css, fonts, and JS, along with my index.html file.

But when I try to navigate to any of the pages that end up displaying blank pages, the JS folder disappears in the Sources list, leaving only the css and font folders.

Again, I get the same result when I build with either my Mac and my PC.

I’ve tried deleting the src-electron folder entirely and starting again, but that doesn’t help. And I can’t find anything via Google that gives me any good clues.

It’s baffling to me that the app would work fine on the simulator but would then fail so completely when building the actual app. And I don’t really know what to do next.

How can I resolve this?

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

I don't see how to create a codepen for this issue. so I will upload my files instead for your review.

**To Reproduce**
1. Open project in Visual Studio Code
2. Run command: quasar build -m electron
3. Open the resulting executable file
4. Navigate to any page from the home page

**Expected behavior**
I expect to see the content on any page that I attempt to navigate to.

**Screenshots**
N/A
**Platform (please complete the following information):**
OS: Windows 10 or Mac
Node: 12.15.0
NPM: 6.13.4
Yarn: N/A
Browsers: N/A
iOS: N/A
Android: N/A
Electron: 1.12.2 according to @electron > get > package.json
[loa-today-master.zip](https://github.com/quasarframework/quasar/files/4836330/loa-today-master.zip)

**Additional context**

**Comment by webnoob** [comment]
I've managed to recreate this with your zip file. Looking into it now.

**Comment by webnoob** [comment]
This is also happening on a fresh Quasar App with an internal link:

![image](https://user-images.githubusercontent.com/10404747/85933348-f10a1e00-b8cd-11ea-94db-dd4c0d8f07cc.png)

**Comment by vahost** [comment]
I feel better ... I thought it might have been my own noobieness. Thanks for helping!

**Comment by webnoob** [comment]
@vahost Not sure why at this point but if you change your links to:

`./index.html#/somePath` it's working

**Comment by vahost** [comment]
I can't get it to work in either dev or build mode after changing my links the way you suggest. I'll just wait to see what you all find is the root of the issue.

**Comment by webnoob** [comment]
Well I tried it on your source code and it worked fine ... These are the 2 I changed:
```js
{
          title: 'Privacy Policy',
          caption: 'for the LOA Today App',
          icon: 'security',
          link: './index.html#/privacy'
        },
        {
          title: 'Terms of Service',
          caption: 'with the LOA Today App',
          icon: 'thumb_up_alt',
          link: './index.html#/terms'
        }
```

**Comment by vahost** [comment]
Oh! I see. I was trying to change routes.js. Yes, I can confirm that works for some reason.

**Comment by webnoob** [comment]
I've tracked this down and it's not update related. Basically, it's just the way the example data is setup and the way you're using it.

So, by default this is EssentialLink (The demo component which you're using to generate the links on the left in your menu):
```html
<q-item
    clickable
    tag="a"
    :href="link"
  >
```
Under the hood, this will create a QItem with a standard html hyperlink pointing to whatever URL you set. This is why `./index.html#/somePath` works as it needs a relative URL.

If you change it to:
```html
<q-item
    clickable
    @click="$router.push(link)"
  >
```
This then hooks into VueRouters routing (with no page refresh) and sorts out the link itself.
