### ISSUE TITLE
Bug V. 0.14.0(BETA) Alert

### ISSUE THREAD

**Issue by rogeriomq** [quasarframework/quasar#731]
Alert properties: **duration** and **html** are not working as expected.

### Software version

Quasar: 0.14.0(BETA)
OS: Linux Fedora 26
Node: 8.1.4
NPM: 5.3.0
Browsers: Google Chrome, Mozilla Firefox
iOS:
Android:

**Comment by rstoenescu** [comment]
I can assure you they are working correctly. Make sure you read its doc page top bottom, have looked at the demo and its source, and if you still think something is wrong, please provide template and script with which you are using it. Thanks!
