### ISSUE TITLE
QTabs not properly working on mobile RTL mode

### ISSUE THREAD

**Issue by MomenYasser** [quasarframework/quasar#7312]
**Describe the bug**
When using QTabs in mobile RTL mode the sliding arrows is showing strange behavior.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/laughing-nobel-vifbh?file=/src/App.vue

**To Reproduce**
1. Open sandbox link here https://codesandbox.io/s/laughing-nobel-vifbh?file=/src/App.vue
2. Notice the left arrow on tabs rtl mode

**Expected behavior**
The left arrow should be replaced by right arrow and it should be clickable 

**Screenshots**
<img width="377" alt="image" src="https://user-images.githubusercontent.com/6758791/85923880-f4ca8000-b88e-11ea-91c5-5881f016dc5e.png">

**Platform (please complete the following information):**
OS: Mac
Node: 10.18
NPM: 6.9.0
Browsers: Firefox and Chrome

**Additional context**
I guess this happens because the QTabs component is not compatible yet to RTL

**Comment by pdanpdan** [comment]
Hello. There are no arrows in mobile view for QTabs. Can you give some more details?

**Comment by MomenYasser** [comment]
I'm very sorry i was using firefox mobile simulator. Once i tried it on actual device it worked fine. Misunderstanding sorry again 🙈

**Comment by pdanpdan** [comment]
But thanks to this report I found a problem with the indicator animation on RTL :D
