### ISSUE TITLE
[Request] Optional layout reveal for qtab navigation

### ISSUE THREAD

**Issue by cnk789** [quasarframework/quasar#732]
Permit Qtabs in the navigation slot to be excluded from the layout reveal functionality, allowing the nav tabs to stick at the top of page when scrolling down.

**Comment by spectrolite** [comment]
What about a "reveal-header" (alternate to reveal) that would leave the navigation slot excluded from the reveal functionality?
This would have no effect (other than reveal) on iOS theme, but would allow more flexibility for mat theme.

Or maybe a new "fixed-nav" slot, that acts as the navigation slot, except it's excluded from the reveal directive. Or even "fixed-nav-top" and "fixed-nav-bottom", to accomodate special cases where the default mat/ios positioning of navigation does not fit the intended use ?

Just my 2cents.

**Comment by rlam3** [comment]
anybody figure a workaround for this yet? Thanks!

**Comment by pdanpdan** [comment]
You can use https://quasar-framework.org/components/page-sticky.html#Expand-mode
