### ISSUE TITLE
QSlider's lable pin is cut off when used with QSplitter

### ISSUE THREAD

**Issue by poppy-poppy** [quasarframework/quasar#7320]
**Describe the bug**
When QSlider is used in QSplitter, the label pin on the slider is cut off, shown in the screenshot. Even adding a very high `z-index` to the label pin does not help. 

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/FlickerSoul/8bsrpoyt/24/

**To Reproduce**
1. Make a QSplitter. 
2. Add a QSlider with `label-always` prop to the `after` slot. 
3. Then you can see the label pin is covered

**Expected behavior**
The label pin should not be covered. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13360148/85968539-371cbb80-b97a-11ea-836e-7431cb5bfaa7.png)

**Platform (please complete the following information):**
OS: macOS 10.15.5
Node: v12.16.1
NPM: 6.14.5
Browsers: Chrome, Safari, Firefox

**Comment by pdanpdan** [comment]
Hello. Add more space on top of the slider so that the label is visible.

**Comment by poppy-poppy** [comment]
Hi~ Unfortunately, adding more space is not an option for me. Are there other ways to solve this? Thank you!

**Comment by pdanpdan** [comment]
Yes, you can add a class on the QSplitter and make the panels have overflow visible:
https://jsfiddle.net/n21mg06h/7/

**Comment by poppy-poppy** [comment]
It works. Thank you so much!

**Comment by pdanpdan** [comment]
But watch out that you need to put the rest of the content of the splitter in a div with overscroll auto, else it will spill outside :)

**Comment by poppy-poppy** [comment]
Got ya! Thank you!
