### ISSUE TITLE
Typescript: Quasar.lang has type any

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar#7322]
Following the documentation on changing the language using Quasar.lang (https://quasar.dev/options/quasar-language-packs#Dynamical-(non-SSR)) results in the following TS error on line ```Quasar.lang.set(lang.default)```:
`Unsafe member access .set on an any value.eslint@typescript-eslint/no-unsafe-member-access`

The `lang` member is defined as `any`. This was discussed here: https://github.com/quasarframework/quasar/issues/4584#issuecomment-510935674 , but it is not clear why `lang` is not defined as `QuasarLanguage` directly.

The obvious fix is to define the type, but there might be a reason why `$q` and `Quasar` are treated differently, hence this issue.

**Comment by webnoob** [comment]
Pretty sure Quasar.lang.set isn't the Quasar language but the browsers. I've been over this before - will try and find a reference. This might be a reason it's not marked as the QuasarLanguage.
@IlCallo Just my initial thoughts on this.

**Comment by webnoob** [comment]
I've taken a look at the types in Quasar, one thing is for sure $q !== Quasar types so we can't just do a straight forward assignment. lang and iconSet do match in both though from what I can see so I've PR'd that change. @IlCallo is our TS lead so have requested a review on the PR from him.

**Comment by webnoob** [comment]
Will be available in UI version 1.12.9
