### ISSUE TITLE
QSelect opens if it was clicked while it was readonly after it's editable again

### ISSUE THREAD

**Issue by vilyus** [quasarframework/quasar#7323]
**Describe the bug**
If QSelect gets `:readonly="false"` and it was already clicked while it was `readonly` it opens immediately. This behaviour happens only with `behavior="dialog"`

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Vilyus/pen/KKVXRNP

**To Reproduce**
1. Click readonly QSelect with `behavior="dialog"`
2. Make it editable again
3. Dialog shows up immediately

**Expected behavior**
QSelect stays closed

**Platform (please complete the following information):**
OS: Linux Mint 19.3 Tricia
Node:
NPM:
Yarn:
Browsers: FF, Chromium

**Comment by webnoob** [comment]
Fix available in 1.12.9
