### ISSUE TITLE
qselect options with '<>' is not rendered as text

### ISSUE THREAD

**Issue by rvyas** [quasarframework/quasar#7324]
**Describe the bug**
If I specify an option in '<' and '>', it is not rendered as text.

**To Reproduce**
1. For q-slect define options as: 
`   options: [ 'Google', '<Facebook>', 'Twitter', 'Apple', 'Oracle'  ]`
2. Click on Select for drop down options
4. Notice the option blank

**Expected behavior**
Instead of blank, it should be `<Facebook>`

**Screenshots**
![image](https://user-images.githubusercontent.com/2732444/86038567-fd899600-b9f5-11ea-832b-9900352bc645.png)

**System**
 - Quasar Version: 1.9.13 (and latest too)

**Comment by webnoob** [comment]
Add: ` :options-sanitize="true"`.

> Force use of textContent instead of innerHTML to render options; Use it when the options might be unsafe (from user input); Does NOT apply when using 'option' slot!

https://quasar.dev/vue-components/select#QSelect-API

**Comment by rvyas** [comment]
Thanks! I was about to update with that answer. should have gone through the docs in more details. 🤦‍♂️
