### ISSUE TITLE
q-uploader clear all button issues

### ISSUE THREAD

**Issue by jorgv** [quasarframework/quasar#7326]
First thanks to all the quasar team to make such a great framework, it is just awesome!
I am using Quasar v1.12.8

q-uploader clear all button, has three issues:

- It doesn't fire the removed event, so we can't handle the same actions as when removing one by one.
- When using clicking on it, maybe related to not firing the event, the total size doesn't change back to 0

![image](https://user-images.githubusercontent.com/32174909/86059628-5cd1bf80-ba63-11ea-972f-4bfa70ce2129.png)

- There should be a prop to hide the clear all button just to avoid the above issues.

**Comment by webnoob** [comment]
Hi @jorgv ,

I'm not seeing the issues you're describing. See this codepen: https://codepen.io/webnoob/pen/yLePgxG?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fuploader

As you can see, the stats reset and the button triggers the removed event.

**Comment by webnoob** [comment]
Closing as no response and OP information doesn't seem valid.
