### ISSUE TITLE
@quasar/app@2.0 Browser support header could be misleading when not transpiling JS

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar#7330]
**Is your feature request related to a problem? Please describe.**
I'm building a web app that only needs to target Chrome, so I've disabled transpiling altogether. 

From the moment one disables transpiling, browser support becomes completely irrelevant (If I understand correctly). So, I think it is misleading (to other developers) to print a header showing the browser support, when in reality none of them are really supported.

--------------

**EDIT**
As pointed out, CSS is still relevant. It is still a bit misleading, but at least it has a purpose. Maybe slightly alter the header message to something like (Browser Support (CSS Only)). But it is not that important, feel free to choose what's best.

--------------

![image](https://user-images.githubusercontent.com/16233697/86147928-fa5eda80-bac7-11ea-9412-1e0ba5cc6aec.png)

**Describe the solution you'd like**
Do not show the Browser support if `build.transpile === false`

**Describe alternatives you've considered**

**Additional context**

**Comment by pdanpdan** [comment]
Completely irrelevant except CSS :)

**Comment by philfontaine** [comment]
True, I forgot about CSS. In that case it could make sense to let it as is. 

I will let this open to see what Razvan wants to do about it, but I understand why the header _could_ still be relevant.

**Comment by webnoob** [comment]
I'm going to close this for now. At this point the header is still relevant (even if it is CSS).
