### ISSUE TITLE
quasar build on 95% emitting fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by diejsel** [quasarframework/quasar#7337]
Hi.

**Describe the bug**
95% (quasar build) crashes with "emitting fork-ts-checker-webpack-plugin"

**To Reproduce**
1. quasar build (once gathered)

**Expected behavior**
100%

**Screenshots**
![scr](https://user-images.githubusercontent.com/8231501/86319135-70844e00-bc3c-11ea-882a-081d4857d68c.jpg)

**Platform (please complete the following information):**
OS: Ubuntu 18.04.3 LTS
Node: 12.14.1
NPM: 6.13.4
Yarn: 1.22.4

**Additional context**
same problem (current package v4.1.6) - https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/357

**Comment by webnoob** [comment]
Do you have a reproduction of this, your current information isn't enough as I can build projects without issue.

Quasar uses a pinned version of fork-ts-checker-webpack-plugin with version 4.1.6 which is greater than the link you supplied.

I would start by deleting your node_modules / yarn.lock file then doing `yarn install` again.

**Comment by diejsel** [comment]
already tried:
1) deleting node_modules and yarn.lock
2) yarn cache clean

behavior:
more often falls from 95%, although sometimes it collects - by itself, honestly even no thoughts, what is the reason

ps: I pointed out I know that the current version is 4.1.6 in Quasar.

**Comment by diejsel** [comment]
I do not observe a problem in the Window 10 (localhost)

**Comment by webnoob** [comment]
Can you post the output of `quasar build --debug` please?

**Comment by diejsel** [comment]
The same output.

**Comment by webnoob** [comment]
> The same output

It can't be the *same* - it's adding debug information so you should have more information in the console. Please put some effort in. We can't help if you don't provide more information.

**Comment by diejsel** [comment]
> The same output.

![scr](https://user-images.githubusercontent.com/8231501/86512292-88f59380-be09-11ea-82f1-79a9aff72fc9.jpg)

**Comment by webnoob** [comment]
Thanks @diejsel and apologies for doubting you :) Something is wrong ...

@IlCallo Can you weigh in on this when you get a moment please?

**Comment by IlCallo** [comment]
@diejsel can you provide us the output of `quasar info` too?
Do you have any global configuration which may interfer?
Does this problem happens only on a project or on all you projects?
I have your same exact environment but cannot reproduce the problem

**Comment by diejsel** [comment]
I use nodejs as npm package - https://www.npmjs.com/package/n, the rest is like a standard.
Tried to update the version nodejs (v14.4.0 with removal node_modules) - the same problem.
On the same server there is another project with quasar-cli: 0.17.15, it works fine.

![scr](https://user-images.githubusercontent.com/8231501/86520626-5ec6c480-be4f-11ea-97d7-cbf22fd67182.jpg)

PS: Thank you for your desire to help and appreciate your speed of responses.

**Comment by IlCallo** [comment]
> I use nodejs as npm package
Interesting, first time I see this used like this

Quasar doesn't currently support Node 14

As highlighted on the issue you linked, the problem seems to be about node going OOM.
I'm afraid there is nothing we can do on our end

Have you tried increasing the node process memory?

**Comment by webnoob** [comment]
That would also explain why the same source is working on Windows and not on Ubuntu.

**Comment by diejsel** [comment]
Is it a test server, 2GB is not enough?
Is there a minimum requirement for Quasar?

**Comment by IlCallo** [comment]
It's not much about Quasar than what you do in your project

Also note that node process won't take all available RAM by default if I remember correctly
Try increasing that check if it works

**Comment by diejsel** [comment]
So the project is small there just a couple of pages and a map with vue2-leaflet and leaflet.
what should increase I did not quite understand?

**Comment by webnoob** [comment]
I think the point is, this isn't a Quasar issue. It's a fork ts issue and as such is off topic for this issue board.

We're quite happy supporting people using Quasar but as a small team of volunteers, we have to draw a line somewhere and I think we've reached that line with this one.

**Comment by diejsel** [comment]
so I don’t understand what the problem is, the memory is not enough, you said?

**Comment by webnoob** [comment]
Please go over to fork-ts-checker GitHub and ask there. We don't support that package so anything we say is just conjecture

**Comment by seanaye** [comment]
@diejsel have you found a solution to this? i'm getting the exact same thing. My yarn.lock doesn't even contain fork-ts-checker-webpack-plugin. I'm on MacOS

**Comment by seanaye** [comment]
This issue is preventing me from running dev or build on my main workstation. Have tested on a second mac and I cannot reproduce the issue

**Comment by sehugg** [comment]
For me, ForkTsCheckerWebpackPlugin was running out of memory trying to compile a bunch of .ts files I had symlinked in my public/ directory. I added this to my tsconfig.json to fix it:

    "include": ["src"]

**Comment by eyedean** [comment]
Another idea: 

If your project is not huge (or it has used to work in the past), then chances are high that you are linting/compiling the folders that are not supposed to. (e.g. `/dist` or any folder that has compiled artifacts.)

I would recommend running `tsc` and `eslint` individually (preferably with `- debug` option) to see if they are doing their job properly and only compiling/linting the source code.
