### ISSUE TITLE
Invalid Option: bugfixes is not a valid top-level option.

### ISSUE THREAD

**Issue by liuzeWeb** [quasarframework/quasar#7338]
**Describe the bug**

upgrade @quasar/appV2

Error Failed to compile with 1 errors 
error in ./.quasar/client-entry.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL] F:\spyw\sxapp\.quasar\client-entry.js: Invalid Option: bugfixes is not a valid top-level option.
          Maybe you meant to use 'modules'? (While processing: "F:\\spyw\\sxapp\\node_modules\\@quasar\\babel-preset-app\\index.js.overrides[0]$0")

  - normalize-options.js:61 validateTopLevelOptions
    [sxapp]/[@babel]/preset-env/lib/normalize-options.js:61:13

  - normalize-options.js:190 normalizeOptions
    [sxapp]/[@babel]/preset-env/lib/normalize-options.js:190:3

  - index.js:113 
    [sxapp]/[@babel]/preset-env/lib/index.js:113:37

  - index.js:19 
    [sxapp]/[@babel]/helper-plugin-utils/lib/index.js:19:12

  - full.js:165 
    [sxapp]/[@babel]/core/lib/config/full.js:165:14

  - caching.js:33 cachedFunction
    [sxapp]/[@babel]/core/lib/config/caching.js:33:19

  - full.js:235 loadPresetDescriptor
    [sxapp]/[@babel]/core/lib/config/full.js:235:63

  - full.js:77 
    [sxapp]/[@babel]/core/lib/config/full.js:77:21

  - Array.reduce

  - full.js:74 recurseDescriptors
    [sxapp]/[@babel]/core/lib/config/full.js:74:38

 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

 

**Platform (please complete the following information):**
Node:12.7.0
NPM:6.14.4
Yarn:1.22.4

**Comment by webnoob** [comment]
This is either very specific to your code or your modules are messed up.

Delete `node_modules`, delete `yarn.lock`. Run `yarn install`.

Note: If you're using npm for local deps, move to `yarn` please. NPM is too buggy.

**Comment by liuzeWeb** [comment]
thanks I made it. But IE11 prompt after successful compilation vendor.js syntax error

**Comment by liuzeWeb** [comment]
thanks I made it. But IE11 prompt after successful compilation vendor.js syntax error 

`
  class Features {
.......................
}

`

**Comment by webnoob** [comment]
Have you followed these instructions: https://quasar.dev/quasar-cli/browser-compatibility#IE-11-Support ?

**Comment by liuzeWeb** [comment]
This is how I configure it. On the right is an error opened with ie11
![3](https://user-images.githubusercontent.com/39473896/86342112-bd424600-bc89-11ea-812c-1153e97bad3a.jpg)

**Comment by webnoob** [comment]
What is the exact error you're getting ?

**Comment by liuzeWeb** [comment]
`
“browserslist":[
    "ie 11"
]
`

IE11 is not as accurate as this. After looking at the compiled code, there is still a 'class' syntax and' = > 'function. Can you take a look at your configuration method

**Comment by webnoob** [comment]
You have "last 3 version, not dead, ie >= 11",

Can you try explicitly adding "ie 11" so it becomes:

```
"browserslist": [
  "ie 11"
]
```

**Comment by liuzeWeb** [comment]
Yes, I tried But it didn't work

**Comment by webnoob** [comment]
Can you provide a reproduction example? Or email me your source to try to allan (at) quasar.dev?

Given your original path was `F:\spyw\sxapp.quasar\client-entry.js` I'm assuming you were playing around with something (should be .quasar, not sxapp.quasar) so I wonder if something else is broken in your project.

**Comment by pdanpdan** [comment]
We'll reopen once relevant info is added.
