### ISSUE TITLE
cordova.js not found

### ISSUE THREAD

**Issue by boneq** [quasarframework/quasar#734]
I'm not doing app development, I was doing web development.
cordova.js not found  Net:: err_file_not_found

**Comment by murbanowicz** [comment]
Provide all required details...

**Comment by boneq** [comment]
quasar serve Can I open it? Local can not be opened directly?

**Comment by boneq** [comment]
How to run locally?

**Comment by boneq** [comment]
Sorry, I can't use English

**Comment by boneq** [comment]
What I want to ask is how can I open it locally after I compile?

**Comment by boneq** [comment]
![2017-07-19 20-40-17](https://user-images.githubusercontent.com/24372727/28367307-038d2900-6cc3-11e7-8af4-2b2c015850fc.png)

**Comment by JCharante** [comment]
@boneq That is expected behavior. cordova.js is not generated for browser platforms.

**Comment by rstoenescu** [comment]
Use "quasar serve". Distributable folder is meant to be run under a web server. Locally opening it will not work, as stated also when using "quasar build" to build it.

**Comment by boneq** [comment]
@rstoenescu @JCharante @murbanowicz Just put it under the server, thank you

**Comment by rstoenescu** [comment]
@boneq what do you mean?

**Comment by boneq** [comment]
@rstoenescu The problem has been settled，thank you
