### ISSUE TITLE
q-gutter and q-col-gutter issues

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#7340]
I have several `row` divs contained in a `q-gutter-y` parent to separate the rows vertically. On each  `row` div I also specified `q-col-gutter-md` to separate the columns inside each row horizontally.

```html
<div class="q-gutter-y-md">
    <div class="row q-col-gutter-md">
        <div class="col-4"></div>
        <div class="col-8"></div>
    </div>
    
    <div class="row q-col-gutter-md">
        <div class="col-2"></div>
        <div class="col-10"></div>
    </div>
</div>
```

Unfortunately this setup doesn't play nice together. The spacing of `q-gutter-y` is lost as soon as the `q-col-gutter` classes are added to the rows.

How should this be tackled? I'm missing some guidance in the docs for this kind of setup.

**Comment by pdanpdan** [comment]
You have a whole page in the docs that shows how to get children in rows. Wrap the .row in a div.

**Comment by Propaganistas** [comment]
Hi @pdanpdan 

Unfortunately wrapping .row in divs also doesn't work out. See this fiddle:
https://jsfiddle.net/tp4y8kau/

![Schermafbeelding 2020-07-03 om 08 15 43](https://user-images.githubusercontent.com/6680176/86437810-9b86a480-bd05-11ea-9d78-a01840895652.png)

I would greatly appreciate your help.

Side note: I didn't mean to offend you by mentioning the docs. I did read them, but all entries are either for `q-gutter` OR `q-col-gutter`. I'm now combining them in a parent-child way and as it seems this is more contrived, so it seemed more of an opportunity to mention something about this in the docs

**Comment by pdanpdan** [comment]
You're pointing to the QCard spacing - use the DevTools to check.
