### ISSUE TITLE
q-video not working on mobile

### ISSUE THREAD

**Issue by bizready** [quasarframework/quasar#7347]
**Describe the bug**
I have a basic video link in my app (just like https://quasar.dev/vue-components/video#Introduction > Basic). It works fine on the browser (PWA app) but does not work on the mobile (Cordova). It does not provide any error message.

Video work ok on Browser:
![Screen Shot 2020-07-02 at 7 21 19 PM](https://user-images.githubusercontent.com/63766875/86471434-60876f80-bd0b-11ea-9fab-dfe536c9e52e.png)

Video is not showing up on mobile: (no error message on console)
<img width="426" alt="Screen Shot 2020-07-02 at 7 23 30 PM" src="https://user-images.githubusercontent.com/63766875/86471483-785ef380-bd0b-11ea-9f28-93f8ea0cfa71.png">

**Comment by pdanpdan** [comment]
Check the video format, maybe it's not supported in Cordova?

**Comment by bizready** [comment]
It is a youtube video, not local server uploaded a video. 
I just exported as Capacitor and video work. Maybe q-video does not work on Cordova or Cordova does handle video streaming?

**Comment by pdanpdan** [comment]
As QVideo is just a wrapper over the webpage for youtube I think we can close it - it must be related to how cordova works with youtube.
