### ISSUE TITLE
QSelect is not working (at all) in IE11.

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#7348]
**Describe the bug**
The component appears and the selected option is valid, but you cannot interact with the q-select and thus change the option.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/medhyena/pen/XWXVoWw
https://jsfiddle.net/yxpqocar/

**To Reproduce**
1. Go to any of those links
2. Click on the Q-Select
3. Nothing happens.

**Expected behavior**
It should open the q-select template when you want to choose an option.

**Additional context**
It has been tested on our side with quasar 1.9.12
Since IE11 is the best internet browser in the entire galaxy, I cannot even open the quasar doc with it so I believe it also bugs there if it would work...

**Comment by webnoob** [comment]
Have you enabled IE support?

Please post your Quasar.conf and package.json file.

**Comment by pdanpdan** [comment]
The docs are no longer built with ie11 support (for some 6 months ago)
