### ISSUE TITLE
QInfiniteScroll: Smooth scrolling and fully virtual list features. 

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#7349]
**Is your feature request related to a problem? Please describe.**

The current UX for `QInfiniteScroll` is scroll, wait(loading), scroll, wait(loading), scroll, wait(loading) etc ... whereas the preferred UX is just to smoothly backward / forward scroll with pauses being infrequent. The scroll bar height only represents the current number of rows loaded, not the "full size" of the list you're scrolling so you have no way to say "scroll to the bottom" or to a position that's 25% / 50% / 75% of the full "virtual" list. Theses are all things you can do in products like Sencha grid which it achieves with least memory and rendering speed impact.  So here's a few solution ideas that would get you there that you may wish to add to your roadmap for `QInfiniteScroll`.

**Describe the solution you'd like**

**Smooth scrolling**: The trick is to preload more rows both **ahead of** and **behind** the currently visible rows.  So rather than delay loading until the user has scrolled to the bottom of the current scrollable region, we instead preload additional rows before they get there. Our trigger for loading data is now "how close are they to viewing the end of the rendered rows?". How many rows we preload ahead and behind will depend on average row height and visible viewport height. I think we'd want to allow the developer to override a computed default for this "no. of rows loaded" value so if needed they can choose the trade off between server load and smooth scrolling UX. Making this all work in a responsive context will take some thought. Why preload rows **behind**? ... well lets cover the next solution first. 

**A Fully Virtual List**: If we have a monster list we may wish to still represent it's final full size as the height of the scroll bar but obviously we don't want to load the full set of data. Trick #2 is to fake the hidden rows by replacing them with div's of the same height. This ensures we only need to load and render about 2 or 3 visible pages of data with the hidden rows **before** and **after** our visible region replaced with the two `div`s that are dynamically adjusted in height each time we load a new slice of the full list. The goal as usual is to minimize the DOM (See Sencha optimization strategies below).

If we can estimate the total height of a fully loaded virtual list at the start, then we can make the our two hidden div's + rendered rows equal that total height.  So now our scroll bar will match that height and our user can click on the scroll bar to instantly scroll to any offset in the virtual list. We they jump to a new offset, then, quite acceptably, they will wait for the page at that offset to load and render.  So they can continue to smoothly scroll both forwards and backwards we actually want to load/render a bit more - say 2 - 3 pages and keep that much loaded/rendered. So now hopefully the idea of "preloading rows behind" makes more sense.

**Describe alternatives you've considered**

I've used commercial grid components that implement this. 

Here's a demo infinite scrolling for the Sencha Grid
- http://www.mongpstrace.com/ext/examples/grid/infinite-scroll.html

Discussion when it was release (page based caching strategy)
- https://forum.sencha.com/forum/showthread.php?185483-Grid-buffered-infinite-scrolling-in-4.1
- https://www.sencha.com/blog/optimizing-ext-js-4-1-based-applications

**Comment by HunderlineK** [comment]
I've had a similar need for displaying of photos in an overflowed divs. Though I've been thinking if this feature is not more within the scope of some sort of a composition function that can be used as adapter with various components? The requirements for all usages seems to be similar; predicting where the user will land, what need to be displayed there, the position trajectory based on velocity and acceleration of scrolling.

**Comment by pdanpdan** [comment]
You can already do this: https://codepen.io/pdanpdan/pen/NWxyRGy?editors=1010

Can you add details on what you cannot do?

**Comment by tohagan** [comment]
Oh !  My ignorance.  I'd missed that component. Might be all I needed. Will check it out.

**Comment by pdanpdan** [comment]
If you find things you cannot implement please comment here and if needed we'll reopen, but I'll close it for now.
