### ISSUE TITLE
Chrome alignment issue with sticky columns in 0.14 beta

### ISSUE THREAD

**Issue by myknbani** [quasarframework/quasar#735]
### Software version

Quasar: 0.14 beta
OS: Linux
Node: 8.1.4
NPM: 5.2.0
Browsers: Chrome 59

### What did you get as the error?

Alignment with sticky column looks off in Chrome.

![screenshot_20170720_001605](https://user-images.githubusercontent.com/5841268/28377635-051c13cc-6ce0-11e7-985d-f62919b79fea.png)

### What were you expecting?

Alignment is correct.  Like in Firefox

![screenshot_20170720_001836](https://user-images.githubusercontent.com/5841268/28377648-15bbdc58-6ce0-11e7-9551-817f525a18b0.png)

### What steps did you take, to get the error?

Just checking out Quasar and viewing the showcase.

**Comment by pdanpdan** [comment]
Can you please give some more info:
- browser version/platform
- do you use any custom styles in browser (non default global font size?), or zoom
- a screen shot of the whole table
- which columns were sticky (left/right and how many)

**Comment by myknbani** [comment]
You're right.  I am using a non-default global font size (Large in Chrome).  WIth the default/recommended Medium, it seems OK.

Browser is Chrome 59 on a Linux desktop
Sticky columns: Left - 1, Right - none

Here's the screenshot:
![screenshot_20170721_234346](https://user-images.githubusercontent.com/5841268/28470712-4386b2aa-6e6d-11e7-88fe-f611a4b0b439.png)

**Comment by pdanpdan** [comment]
I can reproduce it with greater than normal fonts, and I'll try to find a way to fix it.

**Comment by wh1100717** [comment]
any progress on this issue?

using relative font size cannot fix it....

**Comment by rstoenescu** [comment]
This won't apply to v0.15 datatable revamp, so closing. Sorry for the delay.
