### ISSUE TITLE
Lots of vulnerabilities 

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7352]
Hi

Until not long time ago, I saw 7-8 vulnerabilities. 5-6 low and the rest were moderate. Today suddenly I saw

> found 615 vulnerabilities (610 low, 5 moderate) in 2505 scanned packages
>   615 vulnerabilities require manual review. See the full report for details.

`npm audit fix`, fixes nothing.

I won't paste here ALL the 615 items but I noticed that lots of them are of lodash package. Because the list is long, the output is more than what the terminal shows.

Please advice
Here is one example

> Low             Prototype Pollution                                           
> 
>   Package         lodash                                                        
> 
>   Patched in      No patch available                                            
> 
>   Dependency of   @quasar/app                                                   
> 
>   Path            @quasar/app > @quasar/babel-preset-app > @babel/preset-env >  
>                   @babel/plugin-transform-classes >                             
>                   @babel/helper-replace-supers > @babel/traverse >              
>                   @babel/generator > lodash                                     
> 
>   More info       https://npmjs.com/advisories/1523

**Comment by pdanpdan** [comment]
Here we go again. Lodash is only used on build on your machine.

**Comment by Amosss** [comment]
OK, and should I do something about it? change something? define something differently?
Thanks

**Comment by pdanpdan** [comment]
No, just ignore them. They are dependencies of dependencies, and all related to lodash can be skipped.
