### ISSUE TITLE
Doesn't make hot reload when change a file

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#7359]
**Describe the bug**
Making a change dont trigger a rebuild

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/magical-wing-g97mw?file=/src/pages/Index.vue

**To Reproduce**
1. Create a new proyect
2. Execute `quasar dev`
3. Make a change in some file
4. See the console didn't make another build and the page not show the change

**Expected behavior**
Rebuild the proyect and shows the change

**Comment by pdanpdan** [comment]
I just tested on a new codesandbox created from the template and it works fine.
I suppose you need to use yarn instead of npm or something like this.
Try to reinstall the packages on that repo. Also I don't know what version of nodejs they have, or what limit for inotify.
If you have the problem on a real machine, and mode details, please reopen.

**Comment by Nisgrak** [comment]
I have the problema in a real machine.

I try to create a new proyect and it doesn't rebuild when I start a new one.

Maybe related with #6923 

```
Operating System - Linux(4.19.104-microsoft-standard) - linux/x64
NodeJs - 12.18.2

Global packages 
  NPM - 6.14.5
  yarn - 1.22.4
  @quasar/cli - 1.1.0
  cordova - Not installed

Important local packages
  quasar - 1.12.8 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.0.1 -- Quasar Framework local CLI
  @quasar/extras - 1.8.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.0.0 -- Official ESLint plugin for Quasar
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.10.4 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.9.5 -- TypeScript is a language for application scale JavaScript development

Quasar App Extensions
  *None installed*

Networking
  Host - EnekoSobremesa
  eth0 - 172.30.39.190
```

**Comment by pdanpdan** [comment]
Increse de inodes limit on the machine

**Comment by Nisgrak** [comment]
I have almost 99% of inodes frees.

I try in powershell (it's a wsl enviroment) and it works well, must be related to wsl/linux.

![image](https://user-images.githubusercontent.com/19597708/86609436-39030200-bfac-11ea-9c6b-288f6aa12c87.png)

**Comment by onurkose** [comment]
I have the same problem after upgrading app/2.0

**Comment by yunseop-kim** [comment]
+1

**Comment by yunseop-kim** [comment]
Delete `node_modules` and try installing dependencies again.

Are you using a Mac? If an error message such as `gyp: No Xcode or CLT version detected` appears, Please refer to [here](https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d) and reinstall it.

I solved it like this.

**Comment by b3j0f** [comment]
The same for me :

| distrib | eval |
|---------|-------|
| macos | 👍 |
| powershell | 👍 |  
| wsl 2 | 👎 |
| wsl 1 | ❔ | 
| linux | ❔ |

**Comment by Nisgrak** [comment]
@pdanpdan I return again with this problem, in powershell don't have this issue but in wsl2 didn't work...

**Comment by Nisgrak** [comment]
Ok, the bug it's from the WSL2 itself, it isn't read the inotify events from Windows files https://github.com/microsoft/WSL/issues/4739

Possible solutions:
* Move the project files inside Linux filesystem (i.e from `/mnt/c/projects/quasar-proyect` to `/opt/quasar-proyect`) and use WSL extension in VSCode
* Return to WSL1 in your daily distro `wsl.exe --set-version <distro> 1` (allow use WSL2 in docker, don't worry)
