### ISSUE TITLE
Add prop to QSlideTransition to render a <transition-group> instead of <transition> 

### ISSUE THREAD

**Issue by rathga** [quasarframework/quasar#7362]
As per the title, I'd like a new prop so QSlideTransition can render a `<transition-group>` so it can be used for v-for lists.  

Maybe 'group', e.g. `<q-slide-transition group>...</q-slide-transition>`

I believe simply changing the tag should work just fine with no side effects (at least seems to in my current project).

**Comment by pdanpdan** [comment]
How would it work? How would you expect to use it?

This is a very specific component that applies a specific transition on one thing that is inside it.
Foe multiple components you have `<transitions-group>` in Vue?

**Comment by pdanpdan** [comment]
@rathga ping

**Comment by pdanpdan** [comment]
Please reopen if you have details, thank you.
