### ISSUE TITLE
Clicking on notifications

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#7363]
I'd like notifications to be closed when clicking on the entire body of the notification (instead of making available an action). This greatly enhances mobile experience and usability.

My suggestion is to make available a body click handler?

A very simple feature to describe, but perhaps not so trivial to implement?

**Comment by ibrainventures** [comment]
long, long time ago i openend a similar feature request for also handling the esc key during
notification / timeout 0

https://github.com/quasarframework/quasar/issues/4697

-> Response: a global handler for those "checking / emitting" was that time a perf issue problem.

may, with the future upcoming this can also be watched :-)

**Comment by Propaganistas** [comment]
I think the main difference is that your suggestion would require a page-wide key listener (which is indeed detrimental for performance), while this request specifically targets only the painted box of the notification.

**Comment by pdanpdan** [comment]
This can now be done using an empty flat button with `absolute-full` class (v1.15.1)
