### ISSUE TITLE
Combine Quasar css helpers with custom classes using stylus

### ISSUE THREAD

**Issue by MAMUGI1492** [quasarframework/quasar#7364]
Hi,

It would be nice if you could combine Quasar's css helper with custom classes. It would help to keep the code as clean and tidy as possible, maximizing SFC's ability to separate different languages.

So, we could have custom classes following extended BEM with the Quasar css helper in Stylus (or any other preprocessor) in the `<style></style>` tag, like this:

![code](https://user-images.githubusercontent.com/25407315/86623943-bfc2d980-bfc2-11ea-9c0a-b1832c8f2b2b.png)

You already closed an issue about that  (#2131), indicating that it was not yet possible, in January 2018. To this day it still cannot be done.

Greetings and thanks

**Comment by pdanpdan** [comment]
The example you posted is in my opinion one of the worst use of CSS preprocessors and class names.
Almost all the class names are a specific simple CSS property, that make sense to have exposed in a library (to a certain point), but their use to compose one CSS definition as an extension of other definitions is pointless.
What refactoring would this allow? Stick with CSS and variables and you should be good.

Also, as I explain in the other issue, you ca do this if you want - import the Quasar styl/sass file and extend whatever class you want.
