### ISSUE TITLE
uploader Can support compression image function Or customize the content format of the picture

### ISSUE THREAD

**Issue by yangzxzx** [quasarframework/quasar#7366]

**Comment by pdanpdan** [comment]
It can if you compress or customize the file. But you have to write the code in a factory code.

**Comment by Stefano1990** [comment]
@pdanpdan do you have examples of that or do you know where I could find examples for that?

**Comment by pdanpdan** [comment]
No, sorry, it's not something I would like to do client side :)
But I'm pretty sure there is some wasm version of gimp or there.

**Comment by Stefano1990** [comment]
Yh I know that there are libraries, thats not the problem (as an example
compressjs) but I don't know how to return a file from the factory function
that will be used by the QUploader. As far as I understand you can only
overwrite the QUploader fields from the factory function.

Actually compressing the file before you upload it might not be a bad idea.

Compressing before uploading can save significant amounts of traffic for
the mobile user. Unless you are compressing huge number of photos the power
consumption is probably negligible (?).

**Comment by Arkshine** [comment]
I did use this lib in a SPA app.
I don't know if there are better ways, but to compress before files are added, you need to create a custom components with `QUploaderBase` as base. Then you can overwrite `__addFiles` method and use the compressorjs lib there. Once compressed, you add the compressed files with the `QUploaderBase` object.
It works great.

**Comment by Stefano1990** [comment]
@Arkshine is there an example how to do this? I have never created a custom component using a quasar component as base. I googled a bit but couldn't find anything useful.
