### ISSUE TITLE
[docs] Setting up Translation Blocks in your SFCs fails on V2

### ISSUE THREAD

**Issue by noodlelive** [quasarframework/quasar#7367]
When following the instructions for setting up YAML based translation blocks at https://quasar.dev/options/app-internationalization#Setting-up-Translation-Blocks-in-your-SFCs on V2 I setup the config as:

```js
extendWebpack (cfg) {
  cfg.module.rules.push({
    resourceQuery: /blockType=i18n/,
    use: [
      {loader: '@kazupon/vue-i18n-loader'},
      {loader: 'yaml-loader'}
    ]
  })

  cfg.module.rules.push({
    enforce: 'pre',
    test: /\.(js|vue)$/,
    loader: 'eslint-loader',
    exclude: /node_modules/
  })
},
```

However this throws the error on my custom component:
``` sh
This relative module was not found:

* ./EventSelectorComponent.vue?vue&type=custom&index=0&blockType=i18n in ./src/components/EventSelectorComponent.vue
```

I was able to fix the problem by using an updated configuration and the JSON based importer for which I will create a docs section PR.

**Comment by webnoob** [comment]
Needs: `type: 'javascript/auto',`

Docs need PR'ing to change the example to:

```js
cfg.module.rules.push({
    resourceQuery: /blockType=i18n/,
    type: 'javascript/auto',
    use: [
      {loader: '@kazupon/vue-i18n-loader'},
      {loader: 'yaml-loader'}
    ]
  })
```

**Comment by webnoob** [comment]
Merged. Pending update.
