### ISSUE TITLE
QTable - Get row by index

### ISSUE THREAD

**Issue by Menighin** [quasarframework/quasar#7373]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A method on the `QTable` to retrieve the row data based on the row index. Not sure if there is one and I'm missing it.

**Describe alternatives you've considered**
Manually reading the DOM and getting the correspondent `tr` for the index I have.
Maybe sorting the data myself and then the `rowIndex` would be the same index of my data

**Additional context**
I have the following scenario:
- The user is presented with a table of data
- One of the columns can be eddited inline.
- To do it, I have a `QButton` that when clicked, renders a `QInput`.
- The users fills the input and if he presses TAB I want him to jump to the next row, in the same column, in edit mode

I can get the row index with the `rowIndex` property, but I didn't find a way to get the next row's data given `index + 1`.
I can see we have a method `getTableRow` but it requires some parameters I couldn't understand.
And I cannot simply use the index on my dataset because ordering the table does not order my dataset (nor it should, of course).

Thanks!

**Comment by pdanpdan** [comment]
Hello.
You can use the `filteredSortedRows` computed on a ref to the QTable.
Check here: https://quasar.dev/vue-components/table#Example--Custom-multiple-selection

**Comment by Menighin** [comment]
@pdanpdan I think it would be nice to have a section for this kinda of properties in that table of contents in the end of every component docs page... Do we have something like that? Don't know how it should be called...
