### ISSUE TITLE
Quasar BEX massive vendor.js file issue

### ISSUE THREAD

**Issue by Inklud** [quasarframework/quasar#7374]
**Describe the bug**
When uploading browser extension to Firefox Add On there is a limitation "Files larger than 4MB will not be parsed".

Scenario 1: Everything works
If you do "quasar create my-test-bex", then "quasar build -m bex" you get a zip file inside the \dist\bex\Packaged\firefox that few warnings and a small file size. Firefox will accept this with no problems when uploading it to  Firefox Add On store.  

Scenario 2: Plugin will be rejected due to massive vendor.js files and to many eval() warnings
If you do "quasar create my-test-bex", then "quasar dev -m bex", then "quasar build -m bex" you get a massive vendor file inside the \dist\bex\Packaged\firefox that is more than 4mb, in addition it produces more than 450 eval() warnings when trying to upload it to the Firefox Add On store.  The plugin will therefor be rejected by Firefox. 

**To Reproduce**
1. quasar create my-test-bex 
2. quasar dev -m bex
3. quasar build -m bex
4. Check vendor file sizes inside \dist\bex\Packaged\firefox 

**Expected behavior**
Scenario 1 (see under Describe the bug heading) is expected regardless of running "quasar dev -m bex" inside the project.

**Screenshots**
https://media.discordapp.net/attachments/634694790994329600/729831922057871451/unknown.png?width=1109&height=672

**Platform (please complete the following information):**
Quasar: 2.0.1
OS: Windows 10
Node: v12.16.2
NPM: 6.10.2

**Comment by webnoob** [comment]
Confirmed this as an issue.

Will look into it.

**Comment by webnoob** [comment]
Ok, it seems something is off with @quasar/app v2.0 on this as the vendor files etc are not building in the correct place. They're in the www/js folder where they should be but also in the www/ root folder. This is where the massive vendor file is so I assume it's doubling up / bringing in more than it should.

Investigating.
