### ISSUE TITLE
Multiple problems in running the my application - 0.14

### ISSUE THREAD

**Issue by alexandesigner** [quasarframework/quasar#738]
### Software version

Quasar: 0.14
OS: MAC OSX
Node: 8.2.0
NPM: 5.3.0
Browsers: Chrome

### What did you get as the error?

I am developing a project using beta 0.14 and today when I went to run, several errors appeared that I am not able to identify them ..

Vue Warns

> QInputFrame
1) Avoid using non-primitive value as key, use string / number value instead.
2) Injection "__field" not found

> QRouteTab
1) Error in nextTick: "TypeError: Can not read property 'contains' of undefined"

> QTab
1) Error in render function: "TypeError: Can not read property 'tabName' of undefined"

### What steps did you take, to get the error?

Reinstall /node_modules in new version node 8.2.0, Before you were using version 8.0.0

**Comment by a47ae** [comment]
Which version of Vue are you using? There is currently an [issue with Vue 2.4.x](https://github.com/quasarframework/quasar/issues/710). Try downgrading to Vue 2.3.x until this is resolved and keep a look [at this forum thread](http://forum.quasar-framework.org/topic/616/do-not-upgrade-to-vue-2-4-x-yet)

**Comment by alexandesigner** [comment]
@a47ae Thanks for the quick reply... It was just that .. as incredible as it seemed I did not update the package.json.. However when I ran the npm install it forced the version of vue-cli 2.4 that I had previously installed.. Thanks again!
