### ISSUE TITLE
QSelect throws typeError when typing in a focused state

### ISSUE THREAD

**Issue by lajuffermans** [quasarframework/quasar#7382]
**Describe the bug**
We use a lot of arrays with objects in combination with `map-options` in QSelects, in order do translate them we use `i18n` translation functions. Basically we do this: `:option-label="item => translationFn(item.label)"`.

However this seems to cause some issues, when selecting the select the menu opens. You can type and select an option without problems. The menu will close and the select is still focused, now if you start typing you will get `typeErrors` (can not read property of item).

**Codepen**
https://codepen.io/lajuffermans/pen/PoZeQRe

**To Reproduce**
1. Click the select
2. Start typing, select an option (menu/select will close)
3. Start typing again, menu will open, option won't be selected

**Expected behavior**
No errors and a selected option

**Screen recording**
[Screen Recording 2020-07-09 at 09.38.33.zip](https://github.com/quasarframework/quasar/files/4895238/Screen.Recording.2020-07-09.at.09.38.33.zip)

**Screenshot**
![Screenshot 2020-07-09 at 09 40 52](https://user-images.githubusercontent.com/6448352/87011521-54e2ef80-c1c8-11ea-9984-5aa5619b7591.png)

**Comment by webnoob** [comment]
Will be available in 1.12.9
