### ISSUE TITLE
Certificate Error on iOS (Quasar 2 + Capacitor 2)

### ISSUE THREAD

**Issue by maximilianmaihoefner** [quasarframework/quasar#7388]
**Describe the bug**
After settings up a new Quasar 2 Project and enabling Capacitor 2 I set `https: true` for the `devServer`. When I try to run the app on iOS using `quasar dev -m capacitor -T ios` it has a blank screen and the XCode Console reports the following errors:
```
Loading app at https://192.168.1.6:8080...
APP ACTIVE
⚡️  WebView failed provisional navigation
⚡️  Error: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.6” which could put your confidential information at risk.
SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitorjs.com/docs/apis/splash-screen#hiding-the-splash-screen
```

**Codepen/jsFiddle/Codesandbox (required)**
Codepen/jsFiddle/Codesandbox cannot run iOS Apps but here is a GitHub example Repo instead: https://github.com/maximilianmaihoefner/quasar-https-ios

**To Reproduce**
1. Create a new quasar app using: `quasar create test-app` and continue with the defaults.
2. Set `https: true` in the `devServer` section of the `quasar.conf.js`.
3. Enable Capacitor by using: `quasar mode add capacitor` and again continue with the defaults.
4. Run the iOS App with: `quasar dev -m capacitor -T ios`.
5. Select an Emulator to run the App (I use iPhone 11 with iOS 13.5)
6. The app should show the Splashscreen and then turn white.
7. Check the bottom right inside XCode, it will show the errors described above.

**Expected behavior**
Using the same setup with @quasar/app v1 and capacitor 1 worked without problems, so I expected it to work with the newer versions as well.

**Platform (please complete the following information):**
OS: macOS 10.15.4
Node: v10.16.0
NPM: 6.14.5
Yarn: n/a
Browsers: n/a
iOS: 13.5
Android: n/a
Electron: n/a

**Comment by pdanpdan** [comment]
Hello. Please read the docs: https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-devServer

**Comment by maximilianmaihoefner** [comment]
Hello @pdanpdan. Thanks for the reply. I've read the Docs but I don't see any mention that what I am describing is unsupported nor how to make it work. I've seen that you can supply a custom SSL Certificate, which could be used as a workaround, which works for me. But the old setup with the autogenerated Certificate used to work fine. Am I overlooking something in the Docs?

**Comment by pdanpdan** [comment]
If iOS does not accept a self signed certificate. Follow https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/ to make an accepted certificate.
Also check this duplicate issue https://github.com/quasarframework/quasar/issues/7264
