### ISSUE TITLE
[request] Floating Action Button Dissapear / Appear Animation

### ISSUE THREAD

**Issue by JCharante** [quasarframework/quasar#739]
Per [Material Design (FAB >> Lateral Screens)](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior), a FAB should dissapear and appear with an animation when switching screens, as seen [here](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B6Okdz75tqQsWm9PdVplYzZvNTg/components-buttons-fab-behavior_03_xhdpi_001.webm) and [here](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3OC0xSGRjUGgwbVE/components-buttons-fab-behavior_04_xhdpi_009.webm). Currently there's no method built into Quasar to make the FAB dissapear or appear with an animation, so it'd be nice if there were.

**Comment by a47ae** [comment]
In v0.14 you should be able to achieve the desired output by using [Transitions](http://beta.quasar-framework.org/components/transition.html).

```html
<q-fixed-position corner="bottom-right" :offset="[18, 18]">
  <q-transition appear enter="zoomIn" leave="zoomOut">
    <q-btn round color="primary" @click="method">
      <q-icon name="mail" />
    </q-btn>
  </q-transition>
</q-fixed-position>
```

In my opinion, this is a more flexible approach, then bake the transition into the FABs directly.

**Comment by JCharante** [comment]
@a47ae I can't believe I didn't take a look at QTransition, thank you!

**Comment by a47ae** [comment]
Haha, I am sometimes surprised myself what Quasar offers out of the box, for example, the nifty little helper functions can come in really handy too. :D
