### ISSUE TITLE
Compile problem from @quasar/app"^2.0.2" to @quasar/app"^2.0.3"

### ISSUE THREAD

**Issue by ghaddon** [quasarframework/quasar#7391]
**Describe the bug**

All was working before the upgrade.

Moved from @quasar/app "^2.0.2" to @quasar/app"^2.0.3" and now receive the following error after running the following command:  quasar dev -m spa.

 **ERROR  Failed to compile with 1 errors**                                                                                                             10:37:31 AM
This dependency was not found:

* core-js/fn/object in ./src/store/modules/shopping.js

To install it, you can run: npm install --save core-js/fn/object

**To Reproduce**
1. npm update - locale directory for application
2. quasar dev -m spa
3. received the above error message

**Expected behavior**
QUASAR would compile.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10 PRO build: 19041.328
Node:  12.18.03
NPM: 6.14.6
Yarn:  n/a
Browsers: n/a
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**
Performed the following steps to correct the problem.

1. Dropped back to @quasar/app"^2.0.2" and reran QUASAR DEV -m SPA *** SAME ERROR ***

2. Delete node_modules directory and package-lock.json, ran npm install *** SAME ERROR ***

3. Dropped back to @quasar/app"^2.0.1" and reran QUASAR DEV -m SPA *** SAME ERROR ***

4. I went with last successful build with @quasar/app"^2.0.2 package.json" Delete node_modules directory and package-lock.json, rebooted Windows and then ran npm install and executed QUASAR dev -m spa  *** SAME ERROR ***

5. Based upon the error I should see core-js/fn/object in node_modules directory but I have never seen after all the steps above.
    I have seen subdirectories core-js/features/object. 

Stopped any help would b grateful.
Gary

**Comment by hawkeye64** [comment]
@ghaddon I assume since you were already using q/app 2.0.2, that you have followed the [upgrade guide](https://quasar.dev/quasar-cli/app-upgrade-guide#Upgrade-Guide)?
Specifically, I am looking at the **required** portion where it says:
> yarn/npm install core-js v3: yarn add core-js@^3.0.0 (or npm install core-js@^3.0.0)

**Comment by ghaddon** [comment]
Jeff,
That is correct. 
Everything working and then I thought I would just apply the upgrade to @quasar/app"^2.0.3" and started getting the error.
 The problem is I'm stuck and seem not to be able to return back a level or two, which makes no sense to me. 
Let me know if I can provide anything else.
Gary
    On Thursday, July 9, 2020, 11:38:48 AM MST, Jeff Galbraith <notifications@github.com> wrote:  
 
 


@ghaddon I assume since you were already using q/app 2.0.2, that you have followed the upgrade guide?
Specifically, I am looking at the required portion where it says:


yarn/npm install core-js v3: yarn add core-js@^3.0.0 (or npm install core-js@^3.0.0)

**Comment by hawkeye64** [comment]
@ghaddon I also assume, when you went back, that you remove node_modules and yarn.lock before re-installing?

**Comment by ghaddon** [comment]
I did.
That is what so strange. Removing node-modules and package-lock.json closing down vscode and going back in and running npm installI thought would have worked. That what has me puzzled.
I went so far as to reboot to make sure nothing was lingering in memory.


    On Thursday, July 9, 2020, 12:26:44 PM MST, Jeff Galbraith <notifications@github.com> wrote:  
 
 


@ghaddon I also assume, when you went back, that you remove node_modules and yarn.lock before re-installing?

**Comment by ghaddon** [comment]
Jeff,
I just found the problem.
Somehow, and don't ask me how, an entry import for core-js was at the top of my shopping.js file that controls my VUEX definitions for actions, getters, state, and mutation.This is not a new file and it makes no sense.
Just another day in the life of a programmer. 
Thanks for your help.Gary


    On Thursday, July 9, 2020, 12:26:44 PM MST, Jeff Galbraith <notifications@github.com> wrote:  
 
 


@ghaddon I also assume, when you went back, that you remove node_modules and yarn.lock before re-installing?

**Comment by hawkeye64** [comment]
@ghaddon Glad you found the issue and got it resolved.
