### ISSUE TITLE
CSS spacing classes don't work on <q-markup-table>

### ISSUE THREAD

**Issue by Gnopps** [quasarframework/quasar#7395]
**Describe the bug**
Trying to remove the padding on a <td> element in a <q-markup-table> does not work with class "q-pa-none". Only class "no-padding" works.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Gnopps/pen/QWyrewG

**To Reproduce**
1. In a <q-markup-table> add a <td> element as a child to <tbody> and <tr>
2. Add class "q-pa-none" to the <td>-element

**Expected behavior**
Padding to be removed from <td>-element. Actual behaviour is that padding is unchanged unless class "no-padding" is added.

**Platform (please complete the following information):**
OS: Windows
Node: n/a
NPM: n/a
Yarn: n/a
Browsers: Firefox 78.0.1

**Comment by webnoob** [comment]
no-padding has !important. q-pa-none, doesn't.

Use `no-padding`...

Not sure this is something we'd want to change. If we changed q-pa-none to have !important, it'd be a breaking change.

**Comment by pdanpdan** [comment]
Hello. Yes, this is expected - the specificity of the td/th padding is higher than the one of the .q-pa-xx classes.
Either use no-padding (that uses ~important) or define your own classes as you need them and use !important or define them on `.q-table td/th`.
There is nothing else that can be done.

**Comment by Gnopps** [comment]
Thanks for your replies! Should I write a notice about it in the docs for markup-table in case other people are struggling with this?

**Comment by webnoob** [comment]
I don't think it's required TBH. It's the first time I've someone asking about it. General CSS knowledge should be enough and we can help directly when people need it.
