### ISSUE TITLE
Enable properties like square, borderless, dense globally

### ISSUE THREAD

**Issue by tpoxa** [quasarframework/quasar#7396]
**Is your feature request related to a problem? Please describe.**
Now I have to add "square" or "dense" property to each Quasar component and bind them to vuex module to enable globally.

**Describe the solution you'd like**
I would like to have one place where I can force quasar use square style of components where possible. (same for other properties like borderless or dense) 
quasar.conf.js => framework=> config maybe? Like dark option...

**Describe alternatives you've considered**
Manual binding props to vuex getter.

**Additional context**
I read this https://quasar.dev/quasar-cli/quasar-conf-js but did not found existing solution.

Thanks.

**Comment by hawkeye64** [comment]
@tpoxa Why not write a wrapper around the Quasar components you are interested in having this feature and have your code look at something globally to do what you intend?

**Comment by tpoxa** [comment]
I am providing a list of UI settings for end-user like brand colors and enable dark mode.

Its would be logical if I provide also, "use square borders"

This wrapper you saying. Is it is a single wrapper code or it should be written for each component separate wrapper?

**Comment by pdanpdan** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/7379
