### ISSUE TITLE
QEditor.js  `getContentEl` return type and esm module export

### ISSUE THREAD

**Issue by pixelvm** [quasarframework/quasar#7397]
#### QEditor.js  `getContentEl` return type `string` or `Element`?

https://github.com/quasarframework/quasar/blob/7bcf01df63709e576d61b4842143d5a27fbcac98/ui/src/components/editor/QEditor.js#L388-L392
https://github.com/quasarframework/quasar/blob/4af04721131cf5dc393b59daceacc6133d3110d3/ui/src/components/editor/QEditor.json#L275-L282

#### Quasar `export`, `export default` or both

node_modules/quasar/dist/types/index.d.ts
```ts
export const QVideo: VueConstructor<QVideo>
export const QVirtualScroll: VueConstructor<QVirtualScroll>
export const Quasar: PluginObject<Partial<QuasarPluginOptions>>

import './vue'
```
https://github.com/quasarframework/quasar/blob/6bff945eb0bff5056f70faff6c6ead0019f63319/ui/src/index.esm.js#L12-L22

有人能快点修复这两个问题么。现在懒人们用起来很不方便。

**Comment by IlCallo** [comment]
Hi! Can you better explain the issue in english?

**Comment by pixelvm** [comment]
I create my project use  @vue/cli with typescript support,and add quasar support with `vue add quasar`.
When using it, i found two problems in the type define file:

If code is first
1. The return type of QEditor method getContentEl should be an HTMLElement, not string.
2. The variable `Quasar` should be `export default`.

The type define file in my project: node_modules\quasar\dist\types\index.d.ts
```ts
//line 2453
export interface QEditor extends Vue {
  ... 
// line 2633
  /**
    * Retrieve the content of the Editor
    * @returns Provides the pure HTML within the editable area
    */
  getContentEl (): string
}
...
// line 8469
export const QVideo: VueConstructor<QVideo>
export const QVirtualScroll: VueConstructor<QVirtualScroll>
export const Quasar: PluginObject<Partial<QuasarPluginOptions>>

import './vue'
import './shim-icon-set'

```

**Comment by IlCallo** [comment]
Gonna check this out in some days, I think you're right on the first one, but the second one is like this on purpose.
Thanks for reporting this
