### ISSUE TITLE
Unable to disable TLS certificate validation trough Quasar config.

### ISSUE THREAD

**Issue by Arsync** [quasarframework/quasar#7405]
Issue occurs in SSR mode of Quasar, Axios communication with an API. 

There is option, known as [NODE_TLS_REJECT_UNAUTHORIZED](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value)

When it placed within .env file with [@quasar/dotenv](https://github.com/quasarframework/app-extension-dotenv), we've got in console output
```
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0'...
```
This is expected behavior: option found.

But when it placed into `quasar.conf.js` env section like this
```
build: {
  env: {
    NODE_TLS_REJECT_UNAUTHORIZED: ctx.dev
      ? 0
      : 1
   }
},
```
we've got output like:
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
```

**Expected behavior**
Node must recognize NODE_TLS_REJECT_UNAUTHORIZED option within build.env section.

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.16.1
Yarn: v1.22.4
Browsers: Chrome 83.0.4103.116

**Additional context**
Dev mode SSR
Quasar v1.12.9
@quasar/app v2.0.4

**Comment by pdanpdan** [comment]
Node is started before reading the conf, of course. The job of it is to provide env for quasar, not for node. Node needs the end from os.

**Comment by Arsync** [comment]
But dotenv extension of Quasar started before Node? Extension does this work...

**Comment by pdanpdan** [comment]
I don't know, I suppose it mixes the values in node values.
But what is wrong with setting that value in the env that starts node or in process.env in node when it starts?

**Comment by Arsync** [comment]
Behavior is different, so I think, it incomplete for migrating from dotenv to quasar.conf build.env and may cause a dev issues with self-signed certs while communicating with api.
