### ISSUE TITLE
QBtn - Side effect of stretch property since 1.12.9 

### ISSUE THREAD

**Issue by Freespacer** [quasarframework/quasar#7406]
**Describe the bug**
I use the QToolbar with QToolbarTitle, QSpace and several QBtn elements. If I use QBtn with the property stretch, I'm getting strange behavior with 1.12.9. Earlier versions do not have this side effect. Codepen examples see below.

The bug is caused by #7387.

**File:** ui/src/components/btn/QBtn.sass
**Line:** 98
**Class:** &--stretch
**CSS-Style:** flex-grow: 1
https://github.com/quasarframework/quasar/pull/7387/files#diff-b58a63fbc9363b1ce7f8fb9507eda25aR98

**File:** ui/src/components/btn/QBtn.styl
**Line:** 98
**Class:** &--stretch
**CSS-Style:** flex-grow: 1
https://github.com/quasarframework/quasar/pull/7387/files#diff-80c6894f16b607a4a61fd5608f1a7426R98

**Codepen examples**

Version 1.12.8: https://codepen.io/Freespacer/pen/NWxzvLj

Version 1.12.9: https://codepen.io/Freespacer/pen/eYJKEjK

**Expected behavior**
Version 1.12.8 is the desired behavior.

**Comment by pdanpdan** [comment]
Sorry, my fault, I'm checking

**Comment by webnoob** [comment]
This has been resolved with update 1.12.11
