### ISSUE TITLE
The custom Loading can not work in the newest version

### ISSUE THREAD

**Issue by Partialsky** [quasarframework/quasar#7411]
**Describe the bug**
in quasar.conf.js 
boot: [  'plugins']
`      plugins: ['Notify', 'LocalStorage', 'Loading'],
      config: {
        notify: { position: 'top', timeout: 500 },
        loading: {
          spinner: 'MyLoading',
          spinnerSize: '50'
        }
      }`

plugins.js
`import MyLoading from '../components/loading/loading.vue'

export default ({ Vue }) => {
  Vue.component('MyLoading', MyLoading)
}`
quasar dev the error is
Module build failed (from ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js):
  Error: **Unknown import from Quasar: MyLoading**

[https://codepen.io/partialsky/project/editor/ZwqGpJ](url)

I have a  custom loading, in previous version, it works.

**Comment by pdanpdan** [comment]
Please fill the issu etemplate (versions of components, cli, ...)

**Comment by Partialsky** [comment]
> Please fill the issu etemplate (versions of components, cli, ...)

"@quasar/extras": "^1.8.2"
"quasar": "^1.12.9"
"@quasar/app": "^2.0.0"

**Comment by webnoob** [comment]
At what point did this break? When moving onto QApp 2.0?

**Comment by Partialsky** [comment]
> At what point did this break? When moving onto QApp 2.0?
> 
> Also, your codepen doesn't work. Please update it.

yess，https://codesandbox.io/s/loading-issue-t7uui

**Comment by webnoob** [comment]
Please answer all my questions:

> At what point did this break? When moving onto QApp 2.0?

**Comment by Partialsky** [comment]
> Please answer all my questions:
> 
> > At what point did this break? When moving onto QApp 2.0?

the original version i use is 1.00, moving into 1.9.6, it works, but need corejs 2.6.5, When moving onto QApp 2.0, this break

**Comment by webnoob** [comment]
Great - that's what I needed to know. Thanks.

Info: Docs show that this is done automatically for Quasar CLI in QApp 2.0 so I guess this broke it: https://quasar.dev/vue-components/inner-loading#Installation

What I'm not sure of is if what you were doing was a feature in the first place :) Will review.

**Comment by Partialsky** [comment]
so how can i use a custom loading?

**Comment by webnoob** [comment]
As I said, I'll review it. Once I've done that I'll report back but it will take some time.

**Comment by webnoob** [comment]
This will be fixed with an update to QApp tomorrow (Thursday 16th July)

**Comment by Partialsky** [comment]
> This will be fixed with an update to QApp tomorrow (Thursday 16th July)

Thanks,
In Plugins.js，I import Loading from quasar
`import MyLoading from '../components/loading/loading.vue'
import { Loading } from 'quasar'

export default async ({ Vue }) => {
  // Vue.component('MyLoading', MyLoading)
  Loading.setDefaults({ spinner: MyLoading, spinnerSize: '50' })
}`

in quasar.config.js，I comment 
`      config: {
        notify: { position: 'top', timeout: 500 }
        // loading: {
        //   spinner: 'MyLoading',
        //   spinnerSize: '50'
        // }
      }`

It works.

**Comment by webnoob** [comment]
Available in quasar/app-v2.0.6
