### ISSUE TITLE
Make Date Utils keys consistent

### ISSUE THREAD

**Issue by Gnopps** [quasarframework/quasar#7414]
**Is your feature request related to a problem? Please describe.**
The Date Utils keys for adding & subtracting are sometimes in plural and sometimes in singular, making it harder to automatically utilise them. "month" and "year" have to be written in singular, whereas all the other keys have to be written in plural (e.g. "days", "hours"). This is inconsistent not only within adding/subtracting but also with difference calculations, where all is written in plural

https://quasar.dev/quasar-utils/date-utils#Add%2FSubtract

![image](https://user-images.githubusercontent.com/16313148/87233756-0c4b5200-c3d3-11ea-9c15-e2950b8da059.png)

**Describe the solution you'd like**
For all keys to be written either in singular or plural form.

**Describe alternatives you've considered**
Currently my program needs to check what key is used and then convert to plural/singular, instead of being able to use either singular or plural for all.

**Comment by webnoob** [comment]
I agree on the inconsistencies on these, however, it's not something we could *change* in V1 as it would introduce breaking changes.

I've added a note to our v2 board for review.

**Comment by rstoenescu** [comment]
Fixed inconsistency for Quasar v2.
Thank you again for reporting this.
