### ISSUE TITLE
[QStep] content-class / no-padding prop

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#7416]
**Is your feature request related to a problem? Please describe.**
I need a QStepper with QStep's without padding.

The padding is currently applied to `.q-stepper__step-inner`, which is not targetable through props nor is there a prop to disable padding.

**Describe the solution you'd like**
I'd love `QStep` to have either:
- a prop called `content-class` / `content-style`
- or a prop called `padding` which we can set to `false`

**Describe alternatives you've considered**
Target the inner css, however, I'm afraid this is prone to break, since it's not documented.

**Comment by webnoob** [comment]
What's wrong with:

```sass
.my-stepper
  .q-stepper__step-inner
    padding: 0px
```

I'm not sure I see the value in adding props to a component just to make it easier to target with CSS. Sometimes this is required (for instance QMenu) as the element are added automatically when the button is clicked so you can't target it in the same way but with this it's perfectly possible / easy to use standard css.

**Comment by drascom** [comment]
this is working for me `.q-stepper--horizontal .q-stepper__step-inner {
  padding: 10px;
}`
