### ISSUE TITLE
QDrawer on-layou event fire before it should

### ISSUE THREAD

**Issue by wizzar** [quasarframework/quasar#7417]
**Describe the bug**
According to the documentation, on-layout should be "emitted when drawer toggles between **occupying space on page or not**"

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/victor-carvalho-the-styleful/pen/vYLagBJ

**To Reproduce**
Click on the button to toggle the drawer and notice the timestamp on each event.

**Expected behavior**
The expected behavior was for `on-layout` to run only after the drawer hiding animation had finished, thus actually not occupying space on the page.

**Platform (please complete the following information):**
OS: win 8.1
Node: 12.18.2
NPM: 6.14.5
Yarn:
Browsers: Chrome 83.0.4103.116
iOS:
Android:
Electron:

**Additional context**
What I need is to recalculate some element width after the drawer is hidden or shown. I tried using the on-layout but I noticed that I couldn't because the recalculation would fail because on-layout is triggered before the drawer is actually hidden.

**Comment by pdanpdan** [comment]
Hello.
The `on-layout` event notifies if the drawer changes state - the internal state - and does not fire if the drawer will not occupy space (Emitted when drawer toggles between occupying space on page or not). The actual show/hide events can be used to determine the moment the space is actually occupied/cleared.

**Comment by wizzar** [comment]
It says right there on the documentation: "Emitted when drawer toggles between occupying space on page or not".
This phrase implies two states: occupying space, and not occupying space. It also implies that it is called when the drawer switches between said states. However, the reality is that it fires before the state has actually switched to 'not occupying space', calling the callback while it still *is* occupying state. This can be a grammar error, or a programming error. Either way it is not doing what it is supposed to do according to the documentation.
You described the expected behavior of @input (Emitted when showing/hidden state changes; Is also used by v-model).

**Comment by pdanpdan** [comment]
Ref your comment:
```
It says right there on the documentation: "Emitted when drawer toggles between occupying space on page or not".
This phrase implies two states: occupying space, and not occupying space. It also implies that it is called when the drawer switches between said states. However, the reality is that it fires before the state has actually switched to 'not occupying space', calling the callback while it still is occupying state. This can be a grammar error, or a programming error. Either way it is not doing what it is supposed to do according to the documentation.
You described the expected behavior of @input (Emitted when showing/hidden state changes; Is also used by v-model).
```

`@input` does not tell if it's going to occupy space or not.
This is emitted on toggle so you can prepare for the hide/show. An expected usage would be:
```
@on-layout
  drawer.$once('show/hide', do something because the layout has changed)
```
