### ISSUE TITLE
Using preFetch with vue keep-alive

### ISSUE THREAD

**Issue by SacDin** [quasarframework/quasar#7418]
It is unclear how to use preFetch with vue's keep-alive. I have tried to use preFetch with keep-alive but preFetch is called every time even if data has to be cached as per keep-alive. This is not actually bug at quasar end but it is unclear to me about how to skip preFetch for specific route if is cached by keep-alive. Thank you.

**Comment by pdanpdan** [comment]
Hello. preFetch is called by the router, it has nothing to do with keep-alive (https://quasar.dev/quasar-cli/prefetch-feature#When-PreFetch-Gets-Activated)

But in you case, if you keep your data, just set a flag in the store (or set aa global to store it to) and do not execute the content of preFetch if the flag is present.

**Comment by SacDin** [comment]
@pdanpdan thank you for prompt response. understood.
