### ISSUE TITLE
Weird selection behaviour when searching in QSelect by keyboard

### ISSUE THREAD

**Issue by jippeholwerda** [quasarframework/quasar#7419]
**Describe the bug**
When using the keyboard navigation to select an item, it is sometimes not possible to select a certain value by typing. 

This issue seems to be introduced in 1.12.9. 1.12.8 still works as expected. Perhaps related to https://github.com/quasarframework/quasar/commit/c6c80a9c1b1ba781714d179713ad9394d7d1b5f6 or https://github.com/quasarframework/quasar/commit/981135c7ae84d290e27ab6f592875698dd8ae4aa?

**Codepen/jsFiddle/Codesandbox (required)**
See for instance the official documentation: https://quasar.dev/vue-components/select#Overview

**To Reproduce**
1. Go to the documentation of QSelect: https://quasar.dev/vue-components/select#Overview
2. Open the first select
3. Try to select Twitter by typing "twi"
4. The item is not selected

**Expected behavior**
The Twitter option is selected when typing "twi"

**Platform (please complete the following information):**
OS: MacOS
Browsers: Safari, Chrome and Firefox

**Additional context**
The options "Google" and "Oracle" can be selected by typing "go" and "or" respectively. I can only select "Facebook" by typing "book", not by typing "face". The funny thing is that I can select "Twitter" if I type "wi", although when typing only the "w", "Google" is selected.

**Comment by pdanpdan** [comment]
Sorry, will be fixed in the next version

**Comment by webnoob** [comment]
Will be fixed in quasar v1.12.12
