### ISSUE TITLE
suggestion: Allow us to set toast position top or bottom from the options.

### ISSUE THREAD

**Issue by donmbelembe** [quasarframework/quasar#742]
somethig like this:

Toast.create({
  html: 'Message to display',
  icon: 'alarm_add',
  timeout: 2500,
  color: '#f8c1c1',
  bgColor: 'white',
  **position: top,** // or bottom
  button: {
    label: 'Undo',
    handler () {
      // Specify what to do when button is clicked/tapped
    },
    color: '#000'
  }

in case of top the style will be

,q-toast toast{
  top: 0px;
  transform: translateY(-1%);
}

.q-toast.active{
 transform: translateY(-0%);
}

**Comment by smolinari** [comment]
Just out of curiosity, why would you need a toast to come out of the top of the screen? Couldn't you use an alert for that?

Scott

**Comment by donmbelembe** [comment]
I'm using for validation and each times there is an error, the error message is displayed on a toast component, my submit button is located on the footer so when the toast is called i can't use my button until slide down. something that i don't need in my project.

I already made a modification using **css**, now my toast is coming from top. but it could be good if we have toast option just for flexibility.

**Comment by smolinari** [comment]
Hmm... ok. But, if there is an error, the submitting of the form shouldn't be possible, should it?

Scott

**Comment by donmbelembe** [comment]
yeah in case you fix your error before the toast slides down.

I think we can also use a toast for another purpose, for example showing some **tips** to the user without interrupting him, we may need it to slides on top if the commands button are located in the footer

**Comment by smolinari** [comment]
Maybe your timeout is a bit too long? 

I wonder too if you could work with blur and focus with the `dismiss()` method of the toast. In other words, if there is an error, remove focus of any input field and when the user clicks back into the input to correct it, the toast is automatically dismissed. 

Scott

**Comment by donmbelembe** [comment]
I got your point, 

but what i'm trying to say is with the toast on top we can use it for example for in app notification without interrupting the user.

something like this 

http://media.dmnews.com/images/2014/08/29/push_650555.png

**Comment by smolinari** [comment]
Ehem. Hihi.....that is exactly what an alert is made for. 😄 

http://beta.quasar-framework.org/components/alert.html

Scott

**Comment by donmbelembe** [comment]
it's seems available only on v0.14,
😄😄😄 I didn't see that before. thank's Scott.

**Comment by smolinari** [comment]
Yes. It's new. And it is cool too. Enjoy! 😄 

Scott

**Comment by rstoenescu** [comment]
Available in v0.15 through Notify plugin. Forgot to close this.
