### ISSUE TITLE
Q-select (multiple use-chips) adding new chips with "Tab" key

### ISSUE THREAD

**Issue by Spoja** [quasarframework/quasar#7420]
**Is your feature request related to a problem? Please describe.**
Alot of my users got used to using the "Tab" key to fill in inputs when navigating forms, so when they come across a q-select with multiple chips enabled they get confused because "Tabbing" it just deletes whatever was written (if it was not confirmed with "Enter" key yet) and focuses to the next field.

**Describe the solution you'd like**
It would be more logical in my opinion that pressing "Tab" would result in adding whatever was written into a new chip, and in case that nothing was written then it would focus out to the next field.

**Describe alternatives you've considered**
I have tried adding @keydown.tab function to the q-select but i don't know how i can access the value that is waiting for input (the one that's passed in event "@input-value -> function(value)"). Even if i could access the value i don't know how to stop the "Tab" key from focusing to the next one (i'm not sure if this is even possible or it has something to do with browsers?), alternative would be manually putting the focus back from the function called by @keydown.tab but that just seems like patching up and opens additional problems (if next field has event that's called on losing focus you wouldn't want it called).

**Comment by pdanpdan** [comment]
Sorry, TAB will only select in single selection mode.
But it's very easy to make it do what you want: https://codepen.io/pdanpdan/pen/QWyBzjb?editors=1010
Just change the names of the variables - quick edit.

**Comment by Spoja** [comment]
Thanks, there is no way to force it to stay focused on q-select after TAB?

**Comment by pdanpdan** [comment]
that would be verrrrrry strange - not to be able to navigate with TAB. There is a way, but you have to search: add event listener for keyou (or keydown), check the key and prevent

**Comment by Spoja** [comment]
You'd still be able to navigate when nothing is written, id just prevent the focus out when you're adding new chips. Currently, if i want to write 2 chips into a q-select with TAB, i have to write in first, TAB, manually return focus with mouse or something into the q-select and then write again.

**Comment by MarcusXavierr** [comment]
I think that using `@keydown.tab.prevent` event would be a better option than creating state and creating a chip when element is unfocused. Even more when you need to have a debounce

https://codepen.io/marcusxavierr/pen/OPLmbMr
