### ISSUE TITLE
Follow_the_signs icon material icons don't exists

### ISSUE THREAD

**Issue by brunokunace** [quasarframework/quasar#7425]
**Is your feature request related to a problem? Please describe.**
try to use "follow_the_signs" material icon and get blank

**Describe the solution you'd like**
add this icon/const on https://github.com/quasarframework/quasar/blob/dev/extras/material-icons/index.js

**Comment by sn0rcha** [comment]
Also, "book_online" is missing as well :)

**Comment by hawkeye64** [comment]
This is actually going to take a while. The icons used by extras, comes from a Google github site that is no longer maintained (at least 3 years old). I have figured out a way to get the most current icons for parsing by downloading directly from google. I just have to hook it "in" to the system for parsing. Not only all this, but I should be able to provide svg icons for the outlined, round and sharp versions.

**Comment by hawkeye64** [comment]
If all goes well, the fix will be in `@quasar/extras` v1.9.0 and quasar v1.12.13 releases.

**Comment by webnoob** [comment]
Fixed in quasar-v1.12.13 and @quasar/extras-v1.9.0
