### ISSUE TITLE
q-stepper header-class does not work with vertical property enabled

### ISSUE THREAD

**Issue by ontwikkelfabriek** [quasarframework/quasar#7427]
**Describe the bug**
The q-stepper header-class does not work in combination with the vertical property. The  header classes are not applied to the header if in vertical mode.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ontwikkelfabriek/pen/qBbMqQB?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fstepper

**To Reproduce**

1. remove vertical property in codepen sample
2. header-class working as expected
3. add vertical again
4. header-class not applying classes

**Comment by webnoob** [comment]
There is no header for vertical tabs. 

I would suggest you use standard css to target each `q-stepper__tab` in this instance.

i.e

```sass
.my-stepper.q-stepper--vertical
  .q-stepper__tab
    font-weight: bold
```
