### ISSUE TITLE
QInput "native" types conflict with label

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#7429]
Here are examples using https://codepen.io/Hawkeye64/pen/qBbMjqN (just plug in appropriate native type)

You can just NOT add a label. But was hoping we could discuss some better alternatives.

type="datetime-local"
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
![image](https://user-images.githubusercontent.com/10262924/87470879-adf0c000-c5da-11ea-87e6-04aea0a795f1.png)

type="month"
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month
![image](https://user-images.githubusercontent.com/10262924/87471188-2e172580-c5db-11ea-8d89-cb8553ee46a8.png)

type="range"
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
![image](https://user-images.githubusercontent.com/10262924/87471306-628ae180-c5db-11ea-8bb5-dc6968c379ef.png)

type="time"
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
![image](https://user-images.githubusercontent.com/10262924/87471420-8fd78f80-c5db-11ea-9252-ccf93134ae0a.png)

type="week"
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week
![image](https://user-images.githubusercontent.com/10262924/87471510-b5fd2f80-c5db-11ea-9dd8-f344af6d0897.png)

**Comment by pdanpdan** [comment]
You mean the tip about stack-label?
https://quasar.dev/vue-components/input#Input-of-number-type

**Comment by hawkeye64** [comment]
@pdanpdan That was exactly it, thanks!
