### ISSUE TITLE
In dialog scroll error: q-header and q-footer in q-dialog scroll with content on iPhone (safari/chrome)

### ISSUE THREAD

**Issue by xrnv2** [quasarframework/quasar#7436]
Invalid render of q-header and q-footer in dialog when scrolling content on iPhone 6s / iPhone 8 in safari/chrome/firefox (ios13.5.1) 
(This devices and browsers 100% confirmed, for other iOS devices it may be also problem)
On android devices example works as expected.

https://quasar.dev/vue-components/dialog#Example--With-containerized-QLayout

**To Reproduce**
1. Open link to documentation example on iPhone
2. Click on "Click me" under "With-containerized-QLayout" example
3. Scroll down

**Expected behavior**
Footer and header fixed.

**Screenshots**
![PHOTO-2020-07-16-10-50-57](https://user-images.githubusercontent.com/45299717/87652201-33e44680-c754-11ea-84ee-9a2f7fe2c9f6.jpg)
![PHOTO-2020-07-16-10-51-22](https://user-images.githubusercontent.com/45299717/87652222-39419100-c754-11ea-97df-2ae590778d8a.jpg)

![IMG_4897](https://user-images.githubusercontent.com/45299717/87652569-ac4b0780-c754-11ea-9cc9-6a82eeca66c7.gif)

**Platform:**

iOS: 13.5.1
quasar: v1.12.3
Pkg: 1.9.6
Browsers: Chrome mobile: 83.0.4103.88, Safari 13.5.1, Firefox 27.0

**Additional information:**
Not 100% sure but I think problem appeared after update of quasar or iOS (both was updated)
Problem was noticed in our application, but is also present in official documentation example so I not created any codepen example.

**Comment by pdanpdan** [comment]
Yes, it's a known issue - iOS ~ie11~ safari only notifies of scroll when it wants to to improve performance, and fixed positioning when scrolling is also applied only when they consider it's ok for performance.

Sorry, nothing that can be done now. But I'll leave the issue opened, maybe a solution shows up.

**Comment by xrnv2** [comment]
> Yes, it's a known issue - iOS ~ie11~ safari only notifies of scroll when it wants to to improve performance, and fixed positioning when scrolling is also applied only when they consider it's ok for performance.
> 
> Sorry, nothing that can be done now. But I'll leave the issue opened, maybe a solution shows up.

Problem present also on chrome (attached gif is from chrome), and just now checked on Firefox problem also exist. :(
So maybe someone will have some idea to workaround :)

**Comment by pdanpdan** [comment]
There is no other browser than safari on iOS. All others are just skins

**Comment by xrnv2** [comment]
Behavior is much better in iOS 14. Not ideal when scrolling through examples, but in static dialog with footer and header fixed and scrollable content everything works correct.
