### ISSUE TITLE
Direction of offsetting columns in RTL isn't correct

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#7437]
**Describe the bug**
Offsetting columns in RTL doesn't work correctly.

https://quasar.dev/layout/grid/row#Offsetting-columns

because of `postcss-rtl` system, class `offset-*` style `margin-left` turned to `margin-right` and the direction isn't correct.

**Platform:**
OS: Ubuntu
Browsers: Chrome

**Comment by pdanpdan** [comment]
It looks to me it's the right thing to happen. Do you have an example, or more details?

**Comment by miladmeidanshahi** [comment]
Here is my form I want to put the first and second input on the right-hand side but the offset is `margin-right`.
![Screenshot from 2020-07-16 19-11-22](https://user-images.githubusercontent.com/11172818/87685267-6ca60f00-c798-11ea-9832-80b3b7729673.png)

**Comment by pdanpdan** [comment]
if you want to put them on the right side then you don't need to offset.

**Comment by miladmeidanshahi** [comment]
@pdanpdan attention please they have `col-6` they will get inlined if i don't add `offset-6` :|

**Comment by pdanpdan** [comment]
Offset is to space from the start/previous element - in the case of RTL this is right.
You have the same case you would have by trying to left align in LTR - just add a .col-6 after each element

**Comment by miladmeidanshahi** [comment]
Please try to create a form that the first and second input is on the right side with `col-6` and stay in one line (block).
You can't do that because if you add offset they will set on left side this is a mistake in RTL.

**Comment by miladmeidanshahi** [comment]
I think we need some thing like `offset-push-*` and `offset-pull-*` classes :thinking:

**Comment by pdanpdan** [comment]
Post the codepen with your try and I'll adjust it.

**Comment by pdanpdan** [comment]
You have 2 ways of doing it: https://codepen.io/pdanpdan/pen/bGEQBwd?editors=1010
The first one, with a column aligned inside the row is the one I would go for.

**Comment by miladmeidanshahi** [comment]
It doesn't seem better to add new classes for example `offset-push-*` and `offset-pull-*`?

```
.offset-push-x
    margin-left: ...

.offset-pull-x
    margin-right: ...
```

**Comment by pdanpdan** [comment]
too much extra CSS in the core, and it would not play well with gutters.
