### ISSUE TITLE
[REQUEST] Icon Genie: custom destination path

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#7439]
**Is your feature request related to a problem? Please describe.**
Since we updated to app v2 the url path has changed from __statics/icons/__ to __icons/__
To publish the application I use apache and there are some limitations with the url path `icons/`

**Describe the solution you'd like**
It would be useful to have a parameter to configure where the images will be saved
and generate the html links with the relative path

**Describe alternatives you've considered**
Do a global search and replace for “icons/” and replace with “app-icons/”

**Additional context**
https://stackoverflow.com/questions/17280204/wamp-cant-have-a-folder-named-icons

**Comment by rstoenescu** [comment]
Hi.

This is what profiles are for. Generate one then search and replace paths...
