### ISSUE TITLE
Icongenie: How to generate splashscreen and icons from separate files like it worked in v1?

### ISSUE THREAD

**Issue by mahoho** [quasarframework/quasar#7443]
Hello!
I am confused a bit with v2 of icongenie. In v1, icongenie was generating icons and splash screens from two separate files. It was nice, especially when icons and splash screen are completely different.
In v2, I can’t see an option to generate splash screen from separate file.

Following command:
`icongenie generate -i app-icon.png -b app-splashscreen.png`
Just puts icon atop of splash screen images.

And this:
`icongenie -b app-splashscreen.png`
Does the same but uses sample logo instead.

The most frustrating thing is that v1 doesn’t work on new projects utilizing quasar/app v2.

The question is:
how to generate icons and splashscreen from different separate files?

Thank you!

**Comment by mahoho** [comment]
Workaround I used:
Add ` "@quasar/app": "^1.9.6",` and `"@quasar/quasar-app-extension-icon-genie": "^1.1.3",` in package.json, remove node_modules, install it again, generate assets using brew-build hook, and then rollback to quasar/app v2.

**Comment by webnoob** [comment]
Have you seen ` --splashscreen-icon-ratio` and the note: `If 0 then it doesn't add the icon of top of background`?

**Comment by mahoho** [comment]
Missed it. This command:
` icongenie generate -i app-icon.png -b app-splashscreen.png --splashscreen-icon-ratio=0`
Does exactly exactly what I needed! 

@webnoob Thank you for advise.
