### ISSUE TITLE
Use of the QTab in a div with class Column breaks the FLEX

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#7445]
**Describe the bug**
Use of the QTab in a div with class Column breaks the FLEX

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/heartbeatlv-the-bashful/pen/jOWegOJ

**Comment by pdanpdan** [comment]
For help requests please head to our discord channel or to the forum.
https://codepen.io/pdanpdan/pen/vYLVoWj?editors=1010
