### ISSUE TITLE
QInput label slot hover

### ISSUE THREAD

**Issue by vadymvoitko** [quasarframework/quasar#7446]
Is caused by this feature https://github.com/quasarframework/quasar/issues/7358
I want to provide label to QInput as slot - this feature works and thanks a lot for it.
Hovewer if my label contains icon with some tooltip on hover its not getting hovered and tooltip doesn't show up.
No listeners are propagated in QInput, I couldn't reach any programmatically.

![image](https://user-images.githubusercontent.com/37067559/87795587-f44f5480-c850-11ea-85f6-91190be84a6e.png)

Is there an easy way to fix it? I call it feature because this requirement wasn't described in initial request
Regards

**Comment by pdanpdan** [comment]
Please add a codepen showing the problem

**Comment by pdanpdan** [comment]
I'll reopen once there is a codepen showing the problem.

**Comment by vadymvoitko** [comment]
Good afternoon!
Sure, 
https://codepen.io/vadymvoitko/pen/LYGMjyb

Hope this helps, thanks

**Comment by pdanpdan** [comment]
I'm pretty sure I put it in the docs:
https://codepen.io/pdanpdan/pen/PoZXJoX?editors=1010
https://quasar.dev/vue-components/input#Custom-Label

**Comment by vadymvoitko** [comment]
My bad, didn't catch up with latest docs update, good lesson. And thanks again for being highly responsive !

**Comment by drewjosh** [comment]
> I'm pretty sure I put it in the docs: https://codepen.io/pdanpdan/pen/PoZXJoX?editors=1010 https://quasar.dev/vue-components/input#Custom-Label

Amazing, thanks for the example. 😃
