### ISSUE TITLE
typescript compilation error : Cannot use namespace 'QuasarIconSet' as a type.

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#7447]
In node_modules\quasar\dist\types\shim-icon-set.d.ts, at line 5, the compilation breaks because of the QuasarIconSet type that isn't recognized as a type.

It is happening in current version (1.12.12) and also older versions which I can't give a full list.

**Comment by webnoob** [comment]
@IlCallo Care to take a look at this?

**Comment by IlCallo** [comment]
Hey @Medhyena, sorry for the delay.
Some people reported this problem in the past, but no one was able to provide a repro for this so we are pretty blind and don't know how to debug it.

Usually refreshing `yarn.lock` or creating a new project and copy over the files solves the problem.
Can you also please follow the issue creation template, to help us understand better your dev environment?

**Comment by rstoenescu** [comment]
Please reopen or comment with the requested feedback. Thank you.
