### ISSUE TITLE
Module not found: Error: Can't resolve '@capacitor/core' in

### ISSUE THREAD

**Issue by MHassanSaqib** [quasarframework/quasar#7448]
After running the command **"quasar dev -m capacitor -T android**", the project starts throwing error detailed below:

"**Failed to compile.

./.quasar/app.js
Module not found: Error: Can't resolve '@capacitor/core' in 'H:\project\.quasar'** "

Could you please guide me on what's going wrong there?

**Comment by arbisyarifudin** [comment]
Hi, do you have the solution? I got some errors here.
