### ISSUE TITLE
Modal still allows interaction with background form

### ISSUE THREAD

**Issue by jclijmans** [quasarframework/quasar#745]
### Software version

Quasar: 0.14-beta
OS: Windows 10
Node: 8.1.3
NPM: 5.0.4
Browsers: IE Edge, Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
By using the tab key, the user is able to give the background focus and change values on the form.

### What were you expecting?
When the modal is shown, all input should be restricted to the modal. The user should not be allowed to give the background focus by using the tab key.

### What steps did you take, to get the error?
Create a form with some q-input fields on it and a button. Clicking on button shows a modal.
Using the tab key several times, the background form gets focus and the user is able to change the value of the q-input fields.

**Comment by rstoenescu** [comment]
Hi, there's a problem: can't control this browser behaviour...
If anyone is interested in doing some leg work to find a workaround, feel free to reopen.

**Comment by dboune** [comment]
- Aria Dialog
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html
This seems to be a good model to look at, especially considering the importance of accessibility today. The code used on the example page linked below appears to trap the focus event, and forces the focus to wrap among the desired elements. Some additional effort is made to handle opening modals from within modals. Overall, very little data is stored. See `dialog.js` linked from within the article.

- JQuery UI Dialog
https://jqueryui.com/dialog/#modal-form
https://github.com/jquery/jquery-ui/blob/master/ui/widgets/dialog.js#L367
Uses a similar method, trapping the keydown event instead, and wraps focus to the first or last depending on the current element in focus.

Another method I've seen involves modifying the tabindex of all tabbable elements outside of the modal, and then setting them back to their original values when the modal closes. This seems excessive to me, and presents some additional issues for nested modals.

Whatever method is used, the following features appear to be indicated:

- Works with both tab and shift tab (forward or reverse direction
- Continues to work as expected when elements are dynamically inserted into any position, including first and last.
- Works as expected in nested modals
