### ISSUE TITLE
Spacing utilities for breakpoints

### ISSUE THREAD

**Issue by frederikhors** [quasarframework/quasar#7452]
It would be amazing to have in Quasar spacing utilities for breakpoints (similar to Bootstrap ones).

Bootstrap signature: `{property}{sides}-{breakpoint}-{size}`.

Example: **q-mx-md-sm**.

An important difference is that Bootstrap uses numbers to differentiate breakpoints.

I know I can use Screen plugin for this but is cumbersome.

**Comment by pdanpdan** [comment]
Hello. It would be a huge overhead in the case and you can use dynamic classes based on screen plugin
