### ISSUE TITLE
Slide Item control

### ISSUE THREAD

**Issue by ghaddon** [quasarframework/quasar#7453]
**Describe the bug**
Upon swiping right afer setting up the Slide Item control, I recieve the following error:

**QSlideItem.js?de1d:43 Uncaught TypeError: Cannot read property 'style' of undefined
    at VueComponent.reset (QSlideItem.js?de1d:43)**

The issue is tied to the reset() function I believe.

**Codepen/jsFiddle/Codesandbox (required)**

N/A

**To Reproduce**
1. Setup for swipe right on the item in the item list.
2.  Swipe works but get the above error message.

**Expected behavior**
Would not receive an error message of an undefined style.

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: Windows Pro
Node: v12.18.0
NPM: v6.14.6
Yarn: n/a
Browsers: Google Chrome Version 84.0.4147.89 (Official Build) (64-bit) 
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**
**The swipe works it is only throwing the undefined style message.**

**Comment by pdanpdan** [comment]
Please add a codepen showing the problem.

**Comment by pdanpdan** [comment]
I'll suppose you were using a slot with v-if. If you post a codepen showing the problem I'll reopen.

**Comment by ghaddon** [comment]
Dan,

I spent some time today working on trying to reproducing the style error but, could not get it to fail.
Let's go with keeping the issue closed. 

Thanks,
Gary
