### ISSUE TITLE
[docs] Doubt about the carousel component

### ISSUE THREAD

**Issue by alexandremsouza1** [quasarframework/quasar#7454]
Is there any way to cancel the component's next event?

I wanted to make a rule that if he didn’t answer he couldn’t go to the next slide.

but I'm having a lot of difficulty.
I'm using the transition event and then I update the vmodel.
it goes into an infinite loop.

I do not know what else to do.

Can someone help me?

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel.

**Comment by webnoob** [comment]
Discord channel for help: https://chat.quasar.dev/
