### ISSUE TITLE
Toolbar options

### ISSUE THREAD

**Issue by Vladislav-wn** [quasarframework/quasar#7455]
Hi,
Thanks for your hard work!
Request.
Please expand Toolbar options:
1. The appearance of a shadow when scrolling the page (there was no shadow, but when scrolling the page it appears at the bottom of the panel)
2. Changing the background color and text color (initially, for example, black background and white text. When scrolling the page changes - white background and black color)
3. Changing the background color of toolbar segments (toolbar consists of three consecutive segments, for example: white, black, white. When scrolling the page, all segments turn black. The text changes accordingly)

Thanks!

**Comment by smolinari** [comment]
I'm not sure what you want with the shadow, as the description isn't quite clear, but I'm certain all of those things you can do yourself.  And in fact, those are very specific requests, which won't be built into the framework. 

If you need help doing these things yourself, we have a [discord server](https://chat.quasar.dev) and a [forum](https://forum.quasar.dev) where you can get help, once you get stuck in your attempts. 

Scott
