### ISSUE TITLE
Linear progress reverse doesn't work

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#7456]
**Describe the bug**
Linear progress reverse in both directions `LTR` and `RTL` doesn't work.

open it on code pen https://quasar.dev/vue-components/linear-progress#Reversed

It seems that it's has a bug in the latest quasar version.

**Comment by smolinari** [comment]
It works. The bars start on the right instead of the left with `LTR`. What are you expecting?

Scott

**Comment by pdanpdan** [comment]
Hello. Thank you for catching this, it was a desync between the sass and styl files, and the dist css is built from styl.

**Comment by webnoob** [comment]
Fixed in quasar-v1.12.13

**Comment by suj-ai** [comment]
Another solution you can use CSS transform and rotate the progress bar to 180 deg
`transform: rotate(180deg);`
