### ISSUE TITLE
Vue 2.4 non-primitive keys

### ISSUE THREAD

**Issue by tobiasdierich** [quasarframework/quasar#746]
### Software version

Quasar: v0.14 beta
Vue: 2.4

### What did you get as the error?

Just a warning:

```
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead. Found in <QSelect>
```

### Steps to reproduce:

Use the QSelect example from the play app ([here](https://github.com/quasarframework/quasar-play/blob/v0.14/src/components/showcase/forms/select/standard-select.vue)) in a clean quasar installation.

**Comment by rstoenescu** [comment]
There is a bug in Vue 2.4.x which is being worked on. Downgrade to Vue 2.3 in the mean time.

More info here (including vue bug link): #710
