### ISSUE TITLE
QCarousel has effect like earthquake when changing slides. 

### ISSUE THREAD

**Issue by OtabekSadiridinov** [quasarframework/quasar#7460]
**Mood**
 I am writing thing somehow bad but quite funny mood.
Reason of my happiness maybe the Quasar framework developers may solve this issue.

**REPORT TYPE** **BUG**

**Describe the bug**
I used examples from docs and try to create my custom caorusel component to use in my website. I tested on many devices and  it is working perfectly. **BUT,** on some of the laptops like lenovo thinkpad and macbook air, it has a earthquakelike bug effect.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/OtabekSadiridinov/pen/YzwRRQy

**To Reproduce**
1. Create a new Quasar project.
2. Create component called MyCarousel.vue in components folder.
3. Paste code from codepen link above
4. Go to index.vue file and import component
5. Use it like below:
```html
      <product-carousel carousel="go-skyblue-bg" :products="banner1"></product-carousel>
```

```js
      banner1: [
    {
        "id": 1,
        "product_name": "Bamboo paper straws",
        "category": "Bar Accessories",
        "price": "0.03",
        "free_delivery": true,
        "image_large": "/media/img/homeproduct/large/lake-ohara-4-700x700.jpg",
        "image_medium": "/media/img/homeproduct/medium/Gallet_clamshell_600x600_2.jpg",
        "image_small": "/media/img/homeproduct/small/girl-500x500.jpg",
        "image_extra_small": "/media/img/homeproduct/extra_small/400X400.jpg",
        "product_position_type": "bss",
        "author": "Someone",
        "product_position_raiting": 1
    },
    {
        "id": 2,
        "product_name": "Velosiper",
        "category": "Uy joy buyumlari",
        "price": "1.00",
        "free_delivery": true,
        "image_large": "/media/img/homeproduct/large/lake-ohara-4-700x700_erYkWSU.jpg",
        "image_medium": "/media/img/homeproduct/medium/Gallet_clamshell_600x600_2_tz4jQl4.jpg",
        "image_small": "/media/img/homeproduct/small/girl-500x500_A3WHbRJ.jpg",
        "image_extra_small": "/media/img/homeproduct/extra_small/400X400_Vr5avim.jpg",
        "product_position_type": "tg",
        "author": "Someone",
        "product_position_raiting": 2
    }
]
```
6. Then check it. On some devices like lenovo thinkpad and macbook air it has earthquakelike bug effect.

**Expected behavior**
Expected to see a responsive carousel with bottom right side prev and next button and with the feature of touch swiping and 40% of its left side has some info and the other 40% of it image then 20% space between them.
**I mean something the same with below image**
![image](https://user-images.githubusercontent.com/60849894/87874658-f34f2c00-c9e4-11ea-9733-74f92d5769b8.png)

**Screenshots**
No screenshot.
Because it is impossible to show what's happening in screenshots.
And sliding to next slide happens quickly.

**Platform (please complete the following information):**
OS: Windows, MacOS, Linux
Node: v10.19.0, latestst-stable(12.18.2), the latest one(14.5.0).

NPM: 6.0.0, 6.14.5 

Yarn: 1.22.4, 2, 2.1.1
Browsers: Chrome(Latest), Safari(Latest), Mozilla Firefox(latest), Opera(maybe old version), IE(latest), IE(8)
iOS: Safari, Opera Touch
Android: Chrome, Google (phone's own browsers)
Electron: ?

**Additional context**
I am waiting for a solution and answer please help us. :eyes:.

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum.

**Comment by OtabekSadiridinov** [comment]
@pdanpdan This is not asking help. This is bug report. Please, reopen the issue.
This is about some bug which happens when jumped into next slide of Quasar carousel.
FYI: I filled out all needed information and reported.

PS: If anyone will never fixes, who fixes such kind of bugs?

**Comment by pdanpdan** [comment]
Please make a working codepen where this can be reproduced.
