### ISSUE TITLE
希望出个国际化语言设置的包!

### ISSUE THREAD

**Issue by zengcheng1** [quasarframework/quasar#7461]
希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!希望出个国际化语言设置的包!现在不能设置语言...日期的月份是英文的...我想要中文都没办法

**Comment by webnoob** [comment]
Please post issues in English :)

**Comment by hawkeye64** [comment]
Google Translate:
> I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! I hope a package with international language settings! Can’t set the language now...the month of the date is in English...I can’t do anything if I want Chinese

**Comment by webnoob** [comment]
That helps ... :D

**Comment by hawkeye64** [comment]
This is a question that should be asked on Discord or forums, not issues.
