### ISSUE TITLE
Q-Input first key press is ignored (only Firefox)

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7467]
**Describe the bug**
When qInput (resides inside a drawer*) receives focus for the first time (when the app starts) and the user starts entering text, the first key is ignored. Happens only when first focusing the component (either by mouse click or $refs.component.focus()). Happens only in Firefox. qInput has a menu inside it though it happens also when I removed it. It triggers `keyup` event but it happens also without it. I tried removing functionalities but the same scenario happened. `keyup` event is triggered and args parameter contains the entered key but the field itself remains empty.

I don't know if the drawer is the problem or whether the fact that it is hidden at first and shown only after the user logs in.

**Codepen/jsFiddle/Codesandbox (required)**
There are a lot of factors with the q-input so I didn't find which exactly is problematic in order to reproduce it and why it happens only in Firefox. Following is the html code of the q-input.
```
                    <q-input
                        label="label"
                        style="text-transform: uppercase; margin-left: 10px; width: 100%;"
                        size="sm"
                        ref="searchInput"
                        v-model="dataToSearch"
                        rounded
                        @keyup="triggerSearch"
                        ><q-tooltip>Enter at least 3 characters...</q-tooltip>
                        <q-menu v-model="showResultsMenu" anchor="top right" self="top left" @show="setFocus()">
                            <q-list bordered separator style="height: 400px" class="list scroll">
                                <q-item clickable v-ripple v-bind:key="item.itemName" v-for="item in searchListOptions" @click="addItem(item.itemName)">
                                    <q-item-section>
                                        <q-item-label>{{ item.itemName }}</q-item-label>
                                        <q-item-label caption>{{ item.itemDesc }}</q-item-label>
                                    </q-item-section>
                                </q-item>
                            </q-list>
                        </q-menu>
                    </q-input>
```
**To Reproduce**
I have no idea what is causing it but it's consistent. Other qInputs are working and even the same one works after the first click so I couldn't find the cause for this issue and why it happens only with Firefox.

**Expected behavior**
All keys entered, including the first one, should be acknowledged.

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.16.3
NPM: 6.14.4
Browsers: Firefox 78 (Chrome 83 works)

**Comment by pdanpdan** [comment]
Please add a way to reproduce the problem.

**Comment by pdanpdan** [comment]
we'll reopen if a reproduction scenario is provided
