### ISSUE TITLE
QScrollArea support Y and X scrollbar at the same time

### ISSUE THREAD

**Issue by SnosMe** [quasarframework/quasar#7471]
**Is your feature request related to a problem? Please describe.**
QScrollArea currently has an exclusive mode for displaying scrollbar horizontally or vertically. Components like a "text file editor" require both scrollbars to be shown.

**Describe the solution you'd like**
QScrollArea shows vertical and horizontal scrollbar at the same time.

**Describe alternatives you've considered**
None

**Additional context**
The only issue I see is how to handle scrollbars overlapping in corner.
- `Y scrollbar = container height`, `X scrollbar = container width - Y scrollbar width` (like vscode does)
- Mimic default scrollbars and add a styleable `resize square`
- ...

**Comment by rstoenescu** [comment]
This is scheduled for Quasar 2.0.
We cannot add this without introducing breaking changes to the current API.

**Comment by slowaways** [comment]
I was already opening an Issue requesting for it, but I found this one.
Waiting for this!

**Comment by rstoenescu** [comment]
Will be available in Quasar v2

**Comment by rstoenescu** [comment]
Will be available in Quasar v2
