### ISSUE TITLE
app Unknown command "ext" +3ms

### ISSUE THREAD

**Issue by reBiocoder** [quasarframework/quasar#7472]
**Describe the bug**
i want to use command `quasar ext add @quasar/qmarkdown` install markdown plugin,but qurasr/cli can't use `ext` command. As shown below:
![can't fand ext command](https://user-images.githubusercontent.com/39401819/88078571-31984700-cbaf-11ea-9730-9288e46b42fc.png)

i run command `quasar info` have follow infomation:
![截屏2020-07-22 00 08 17](https://user-images.githubusercontent.com/39401819/88078798-74f2b580-cbaf-11ea-8135-102a5426b73f.png)

**Comment by hawkeye64** [comment]
@reBiocoder You have an old version of quasar and quasar cli (v0.17).
App extensions are a v1.x feature.

**Comment by reBiocoder** [comment]
> @reBiocoder You have an old version of quasar and quasar cli (v0.17).
> App extensions are a v1.x feature.

How can I upgrade? Thank you very much

**Comment by hawkeye64** [comment]
@reBiocoder Follow these instructions: https://quasar.dev/start/upgrade-guide#Upgrading-from-0.x-to-v1
Also, add eslint-plugin-quasar: https://github.com/quasarframework/eslint-plugin-quasar
Follow the instructions for the latter on the readme. It will help identify legacy components and suggest what to use for new components.

**Comment by reBiocoder** [comment]
> @reBiocoder Follow these instructions: https://quasar.dev/start/upgrade-guide#Upgrading-from-0.x-to-v1
> Also, add eslint-plugin-quasar: https://github.com/quasarframework/eslint-plugin-quasar
> Follow the instructions for the latter on the readme. It will help identify legacy components and suggest what to use for new components.


extremely grateful !
