### ISSUE TITLE
Indeterminate State for the Loading Bar Plugin & Ajax Bar

### ISSUE THREAD

**Issue by mkarras** [quasarframework/quasar#7473]
**Describe the solution you'd like**

To achieve a more realistic loading behavior/feedback (instead of faking the progress) it would be great if the Loading Bar Plugin & Ajax Bar would have a Indeterminate Mode/State like QLinearProgress here: https://quasar.dev/vue-components/linear-progress#Indeterminate-state

**Comment by pdanpdan** [comment]
duplicate of #2823
