### ISSUE TITLE
Add scoped slot for QTab icon

### ISSUE THREAD

**Issue by CVeniamin** [quasarframework/quasar#7475]
**Describe the solution you'd like**
To be able to override the icon slot for a QTab to use a QAvatar instead.

**Describe alternatives you've considered**
Tried to pass URL to icon prop but with no success.

**Comment by pdanpdan** [comment]
Please attach a codepen showing how you tried to pass the url to the icon.

**Comment by pdanpdan** [comment]
When you have details I'll reopen.

**Comment by CVeniamin** [comment]
@pdanpdan, thank you for your reply!

First, I tried to pass the URL as follows:
```vuejs
<q-tab name="test" :icon="https://example.com/avatar.png" />
```
then I tried to use a scoped slot
```vuejs
<q-tab name="test" :icon="'https://example.com/avatar.png'">
  <template #icon>
    <img src="https://example.com/avatar.png" />
  </template>
</q-tab>
```
but that also did not work, after searching through the documentation I saw that there we no scoped slot for QTab.

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/icon#Image-icons
