### ISSUE TITLE
QBtnToggle doesn't pass button props

### ISSUE THREAD

**Issue by SnosMe** [quasarframework/quasar#7478]
**Describe the bug**
QBtnToggle doesn't pass button props

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/4o6rpaze/

**To Reproduce**
1. Go to jsFiddle
2. `padding` prop is not passed to QBtn

**Expected behavior**
"Opt 1" button must look same as the "Btn 1"

**Platform (please complete the following information):**
Browsers: All

**Additional context**
API says:
> Name: ...props
> Type: Any
> Description: Any other QBtn props (including class and style)

**Comment by rstoenescu** [comment]
Will be available in "Quasar v1.13.0"
