### ISSUE TITLE
How To  disabled the feature on cordova:close dialogs and drawers using back button 

### ISSUE THREAD

**Issue by wideweide** [quasarframework/quasar#7479]
**Is your feature request related to a problem? Please describe.**
we could close dialogs and drawers using back button while on cordova. This feature is present on Cordova, but not on PWA (browser).

**Describe the solution you'd like**
To  disabled the feature on cordova,  then I can use onpopstate to control myself,especailly if I need back opertion in dialog.

**Comment by pdanpdan** [comment]
Can you explain better what you want and what is not possible?

**Comment by pdanpdan** [comment]
I asked you to use full sentences to explain what you want and what is not working.
That means:
- on what platform you want something to happen
- what you want to happen
- what you want not to happen
- what have you tried
- what is not working

**Comment by wideweide** [comment]
> I asked you to use full sentences to explain what you want and what is not working.
> That means:
> 
> * on what platform you want something to happen
> * what you want to happen
> * what you want not to happen
> * what have you tried
> * what is not working

I found doc here:  https://quasar.dev/vue-components/dialog#Cordova%2FCapacitor-back-button
```
Cordova/Capacitor back button
Quasar handles the back button for you by default so it can hide any opened Dialogs instead of the default behavior which is to return to the previous page (which is not a nice user experience).

However, should you wish to disable this behavior, edit your /quasar.conf.js file:
```

I just want to  disable this behavior... ,then I can use window.onpopstate to handle the back button in same way whatever cordova or pwa

Is there another better way to handle the back button?

**Comment by pdanpdan** [comment]
https://github.com/vuejs/vue-router/issues/2796#issuecomment-498348465
https://github.com/vuejs/vue-router/issues/2796#issuecomment-498348465

**Comment by wideweide** [comment]
@pdanpdan 
It seems not usable...
My quasar project is created 1 year before, may be quasar version is 1.0

Now:
quasar -v 
1.6.0
there is no config in quasar.conf.js,so I add myself:
```
framework: {
      // iconSet: 'ionicons-v4',
      lang: 'zh-hans', // Quasar language
      config: {
        cordova: {   // I test capacitor  too
          backButtonExit: false
        }
      },

      all: true // --- includes everything; for dev only!
      // components: [
      //   'QEditor',

```

Is there somthing else need to do?
