### ISSUE TITLE
[Request] Display key packages' versions along with quasar version

### ISSUE THREAD

**Issue by spectrolite** [quasarframework/quasar#748]
It would be greatly useful (for bug reporting as well as other uses) if `quasar version` also showed the currently installed versions of at least npm and Vue, and maybe a few other key packages, like quasar-extras or webpack.
```
> quasar version -v
Quasar CLI v0.6.2
webpack  v2.2.1
npm v2.15.11
  
  App running on Quasar v0.14.0 (edge version)
  quasar-extras  v0.0.7
  vue  v2.3.4
```
Just a suggestion. What do you guys think ?

**Comment by JCharante** [comment]
Wrong repo, post this to https://github.com/quasarframework/quasar-cli instead

**Comment by spectrolite** [comment]
https://github.com/quasarframework/quasar-cli/issues/41
