### ISSUE TITLE
CSS Helper Class rotate-205 "Rotate by 205 degrees" should be 225 degrees.

### ISSUE THREAD

**Issue by innominata** [quasarframework/quasar#7483]
Hi there, looks like 205 degrees is in error, as all the other rotations are increments of 45 degrees.

Page : https://quasar.dev/style/other-helper-classes#Orientation-Related

:)

**Comment by hawkeye64** [comment]
@innominata You're right. I'll add rotate-225, but keep rotate-205 for backwards compatibility.

**Comment by hawkeye64** [comment]
Will be in v1.12.14
