### ISSUE TITLE
[docs] Explain how to get instance from the wrapper function

### ISSUE THREAD

**Issue by WangHansen** [quasarframework/quasar#7486]
By default when I init a new quasar app, I get the following code for router:
```javascript
/*
 * If not building with SSR mode, you can
 * directly export the Router instantiation
 */

export default route<IRootState>(function({ Vue }) {
  Vue.use(VueRouter);

  const Router = new VueRouter({
    scrollBehavior: () => ({ x: 0, y: 0 }),
    routes,

    // Leave these as is and change from quasar.conf.js instead!
    // quasar.conf.js -> build -> vueRouterMode
    // quasar.conf.js -> build -> publicPath
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE
  });

  return Router;
});

```

Because the `Router` is wrapper within the function, there is no doc regarding how to get the router instance in this case.
The only way currently to do is to remove the wrapper function and directly expose the router instance as suggested in the code comment.
Similar things to store instance as well.

The reason I want to get the `router` instance is because I want to wrap it to be used with composition api like this:
```javascript
import router from "./router";

function userRouter() {
  function routeTo(route: RawRoute) {
    router.push(route)
  }

  return { routeTo }
}
```

**Comment by pdanpdan** [comment]
https://quasar.dev/quasar-cli/boot-files#Anatomy-of-a-boot-file

**Comment by WangHansen** [comment]
I have tried the following code but it doesn't work:

```javascript
// ./boot/instances.ts

import { boot } from 'quasar/wrappers';
import VueRouter from 'vue-router';
import { Store } from 'vuex';
import { IRootState } from '../store/index';

let router: VueRouter, store: Store<IRootState>;

export default boot(({ router: _router, store: _store }) => {
  router = _router;
  store = _store;
});

export { router, store };

// .vue file

import { router } from '../boot/instances';

router.push() // cannot read push of "undefined"
```

**Comment by pdanpdan** [comment]
I hope you are not putting the `router.push` after the import :)
that would mean you are trying to push at file instantiation, before the app has started.
Please use the discord channel or the forum for help requests.
