### ISSUE TITLE
Vercel PWA Deployment Issue

### ISSUE THREAD

**Issue by PatCode9** [quasarframework/quasar#7489]
**Deployment Bug**
After deploying on Vercel (formerly Zeit NOW), the favicons and other icons are lost.

**What Happen then**
The final PWA product is missing manifest.json icons. The app will load as normal but there's no icon, and if you open the debugger. Icons has failed on loading.

**When did this happened**
Well, after migrating to Quasar 2.x. Maybe the Dev's PUBLIC folder is mixing with Vercel's PUBLIC folder after deploying.

**Or is it just me**
I was hoping this answers YES, if so. Please send instruction to fix this.

**Comment by pdanpdan** [comment]
if vercel is doing something strange on deploy just make a subforler in the public forlder and put the icons there
you should check what you have deployed and try to debug, it has nothing to do with quasar, sorry.
