### ISSUE TITLE
Vue warning [Vue warn]: Avoid using non-primitive value as key,  View 2.4.1

### ISSUE THREAD

**Issue by mygnu** [quasarframework/quasar#749]
### Software version

Quasar: 0.14
OS: Fedora
Node: 7.10
NPM: 5.x
Browsers: Firefox, chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

```
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

found in

---> <QSelect>
       <QTablePagination>
         <QDataTable>
```
### What were you expecting?
No Error
### What steps did you take, to get the error?
Using data table, and also using any QSelect component

**Comment by rstoenescu** [comment]
Hi, this has been reported multiple times. Please downgrade to Vue 2.3 (there is also a bug in Vue 2.4 that breaks a lot of packages out there, not only Quasar and the fix in Vue awaits to be included its next release).
Will post a message on forum when it is safe to upgrade to Vue 2.4.
Thanks.

**Comment by mygnu** [comment]
No Worries, Thanks for a quick reply Cheers

**Comment by fionagithub** [comment]
vue 2.3 :this error still exists..plz help

**Comment by rstoenescu** [comment]
This error does not exists when using Vue 2.3. Please check your package version (not from package.json, but from the actual Vue package inside node_modules).

**Comment by fionagithub** [comment]
Great!when i degrated vue to 2.3.4 ,it's fine with quasar V0.13.x.thx a lot

**Comment by mesqueeb** [comment]
Just posting here to get notified when fixed!
Keep up the good work!

**Comment by dcolley** [comment]
we see this in vue-material also
https://github.com/vuematerial/vue-material/issues/1005#issuecomment-325880017
it seems to stem from the development mode, and should not appear on production

**Comment by andresdrastiko** [comment]
Hi dears, 

I am new in this, how is posible to downgrade a version of Vue? I have the same problem than fionagithub
