### ISSUE TITLE
`quasar build` for different env

### ISSUE THREAD

**Issue by dishcheng** [quasarframework/quasar#7490]
If I have three hosts for different env,for example :local,test(online),production(online).If I want to build test ,and next for production.I have to change my config.js.Have you support  command like `quasar build test`and `quasar build production`

**Comment by pdanpdan** [comment]
You can use one of
https://github.com/quasarframework/app-extension-qenv
or
https://github.com/quasarframework/app-extension-dotenv
or change the confib based on some env variable.
