### ISSUE TITLE
Horizontal Responsive QSplitter

### ISSUE THREAD

**Issue by nathan-rapidstash** [quasarframework/quasar#7491]
**Is your feature request related to a problem? Please describe.**
Mobile responsive layout with a QSplitter requires using JavaScript checks on window size to change QSplitter from Horizontal to Vertical or vice versa

**Describe the solution you'd like**
Ability to define a breakpoint which will toggle the QSplitter vertical/horizontal layout

**Describe alternatives you've considered**
Using the screen plugin to change vertical/horizontal layout programmatically

**Additional context**

**Comment by pdanpdan** [comment]
use the screen plugin
