### ISSUE TITLE
Customize icon colors in item expansion components

### ISSUE THREAD

**Issue by aprilahijriyan** [quasarframework/quasar#7495]
Hello everyone, I want to ask if there is a feature to change the color of the icons on the expansion item components?

Sorry, if my English is bad xD.
Regards, april.

**Comment by pdanpdan** [comment]
Hello. For help requests please head to our discord channel or to the forum.
You should use `expand-icon-class`

**Comment by aprilahijriyan** [comment]
Not the expand-icon that I mean, but the icon on the left before the expansion-item label.

**Comment by pdanpdan** [comment]
Have you read the docs? Try https://quasar.dev/vue-components/expansion-item#Example--Header-slot
