### ISSUE TITLE
Support for Open Emoji 👀

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#7497]
**Is your feature request related to a problem? Please describe.**

[Open Emoji](https://openmoji.org/) a new open source library for 3150 categorised glyphs (color and black & white) covering a very wide range of applications domains. This huge library is CC BY-SA 4.0 licensed. So I think it would significantly enhance Quasar.

My current need is to use them for avatars that that are racially and culturally neutral. Existing emoji characters cover this to some extent but may have backward compatibility issues for older browsers. A consistent SVG solution like this lib would be ideal. 

**Describe the solution you'd like**

Would be awesome if their color and bw fonts were supported as SVG fonts in Quasar. This request is intended more as a friendly "heads up" ✨ . 

There may be some important browser compatibility issues with their existing TTF fonts that you'd need to consider. See discussion [here](https://github.com/hfg-gmuend/openmoji/issues/93).  These issues might make directly importing their TTF fonts premature.  I'm not an expert on fonts so would need someone on your team who understands these issues to evaluate this.  If this is a problem, then I'd say just flag this request in your roadmap and wait a bit for them to resolve these issues. In the meantime, you may still be able to support an early release.

**Comment by hawkeye64** [comment]
@tohagan I will look into this.

**Comment by hawkeye64** [comment]
Sorry, I forgot about this. I did look into it and it increases the size of @quasar/extras significantly. It also used css styling on svg groups, which the quasar svg icon builder does not support. This would have been additional changes that may have been breaking.

**Comment by tohagan** [comment]
Thanks for taking time to assess this idea Jeff. Perhaps this suggest that additional icon fonts belong as plugins rather than as part of extras
