### ISSUE TITLE
[docs] missing  :hide-pagination in the QTable docs

### ISSUE THREAD

**Issue by wsw70** [quasarframework/quasar#7498]
Documentation for `:hide-pagination` for the `QTable` component is missing

**Comment by pdanpdan** [comment]
are you sure?

**Comment by wsw70** [comment]
@pdanpdan Honestly - you provided the worst, least helpful comment one can get. I am happy for your enlightened knowledge.

It is distasteful of you to assume I did no research - the documentation **search** does not yield any results


![image](https://user-images.githubusercontent.com/1345886/88474851-dfe31a00-cf2a-11ea-84fe-3ef4865c2852.png)


![image](https://user-images.githubusercontent.com/1345886/88474849-dc4f9300-cf2a-11ea-9ec0-edb70d790882.png)

**Comment by pdanpdan** [comment]
So the search for hide-pagination is not giving helpful result.
If you change the title from `[docs] missing :hide-pagination in the QTable docs` to 
`Algolia search does not search in API table` then I'll reopen.

**Comment by wsw70** [comment]
I won't change anything - this is beyond ridiculous.

Why do you think I am opening an issue? For the sake of opening it and having fun? 
No - this is because, as a casual user, I cannot find that element in the **official way to search documentation**.

Have a nice day and enjoy your secret, hidden knowledge you may want to distill or may not. Just grow up.

**Comment by wsw70** [comment]
For others who my be looking for it, the documentation is at Qtable API → props → content. 

Thanks @smolinari
