### ISSUE TITLE
[docs] Can you classify the vue component of doc，like element-ui 🍔

### ISSUE THREAD

**Issue by dirkhe1051931999** [quasarframework/quasar#7499]
sometimes，I want quickly find vue components in docs，but too much name also have same name ，it is Hard to find

if like element-ui 
![20200726215249](https://user-images.githubusercontent.com/22389976/88480787-91fdfe80-cf8a-11ea-82ed-f2ad717f8a3b.png)

😁😁

**Comment by pdanpdan** [comment]
I don't really see how this would be helpful. There are  lots of components that would fit in more than one category. But you can provide a list of how you would classify all of them and we can discuss from there.

**Comment by dirkhe1051931999** [comment]
> I don't really see how this would be helpful. There are lots of components that would fit in more than one category. But you can provide a list of how you would classify all of them and we can discuss from there.

such as message have qdialog  qbanner qbadge qtooltip notify confirm prompt bottomSheet. I think these are all about message .

**Comment by pdanpdan** [comment]
I meant take all the components and post here all of them classified, so we can discuss.

**Comment by dirkhe1051931999** [comment]
> I meant take all the components and post here all of them classified, so we can discuss.

`For vue components`
**Basic**
  separator 
  skeleton
  space 
  icon 
  button 
**Form**
  `...Merge current components`
  editor
  popup-edit
  uploader
**Data**
  table 
  markup-table
  circular-progress 
  knob
  linear-progress
  ajax-bar
  loading-bar
  chip
  tree 
  pagination 
  badge 
  avatar 
  list-and-list-items
**Notice**
  bottomSheet(plugins)
  banner
  popup-proxy
  Loading(plugins)
  notify(plugins)
  dialog(plugins)
  spinners
  tooltip
**Navigation**
  menu
  tabs
  tab-panels
  breadcrumbs 
  header 
  stepper
**Others**
  video
  card 
  carousel 
  chat
  expansion-item
  timeline
  toolbar
  splitter
  inner-loading
  intersection
  img 
  infinite-scroll
  virtual-scroll
  scroll-area
  color-picker
  parallax
  pull-to-refresh
  rating
  slide-item
  slide-transition

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area.
