### ISSUE TITLE
Labels don't appear when QRange is readonly

### ISSUE THREAD

**Issue by plmercereau** [quasarframework/quasar#7500]
**Describe the bug**
Labels don't appear when QRange `readonly` prop is one, despite `label` being set to `true`.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/xns1mrfu/8/

**To Reproduce**
See codepen

**Comment by pdanpdan** [comment]
This is by default for `readonly` and `disable` because there is not interaction with the controls.
If you need labels in these cases use `label-always`.

**Comment by plmercereau** [comment]
`label-always` works, but I would like the same behaviour as with the label prop, i.e. labels only appear when hovering the mouse.

mouseover/out, mouseenter/leave to toggle label-always works, but we loose the animation

using `:value` without `readonly` instead of `v-model` allows the use to move the cursors and raises errors.

**Comment by rstoenescu** [comment]
Enhancements will be available in Quasar v1.13.0
