### ISSUE TITLE
[Capacitor] KeyBoard doesn't close without click event

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#7503]
**Describe the bug**
When click on input, you cant hide keyboard without click on any button, because no click events on layout.
My simple solution on screenshot :)

Steps:

Bug:

**To Reproduce**
Requirements:
Iphone 6s ios 12+
Mac OS Catalina

Quasar create
Add input
Add capacitor mode
Add ios capacitor
Dev mod on capacitor ios

**Expected behavior**
Add empty click event on layout

**Screenshots**
![image](https://user-images.githubusercontent.com/11452353/88487556-d5f30280-cf8e-11ea-86a8-cea1ad1f6944.png)

**Platform (please complete the following information):**
OS: MacOS
Node: 12
NPM: latest
Yarn: latest
Browsers: 85%
iOS: 12
Android: 30
Electron: none

**Additional context**

**Comment by bazuka5801** [comment]
@rstoenescu I found as you commit so much on capacitor template, may be I need send this bug to you <3

**Comment by pdanpdan** [comment]
Hello. I just tested and it's working fine. If you need help please use our discord channel or the forum.
