### ISSUE TITLE
Allow both pixel and percentage limits for QSplitter

### ISSUE THREAD

**Issue by nathan-rapidstash** [quasarframework/quasar#7508]
**Is your feature request related to a problem? Please describe.**
Some panels may have absolute limits (px) but switching the unit to px can introduce a host of unwanted behavior: v-model also becomes a pixel unit (this is undocumented in the QSplitter API), and it is impossible to specify the second panel size without using absolute units.

**Describe the solution you'd like**
Allow ratio limits to be a percentage while still specifying absolute minimums for panels as px.

**Describe alternatives you've considered**
Create an unscoped class with a min-height and apply directly to panels.

**Additional context**

**Comment by pdanpdan** [comment]
Hello. I don't understand your use case, can you please add a codepen showing what you cannot do?
But on the value beeing in px I agree, we should add it to the docs.
