### ISSUE TITLE
Allow setting the exact size of a (round) QBtn

### ISSUE THREAD

**Issue by Powersource** [quasarframework/quasar#7510]
**Is your feature request related to a problem? Please describe.**

I tried

```
<q-btn round size="30px"></q-btn>
```

but that made my button 90px tall due to https://github.com/quasarframework/quasar/blob/dev/ui/src/components/btn/QBtn.sass#L98-L101 (the width and height is set to 3em, and `size` only sets the font size in the button)

**Describe the solution you'd like**
Maybe additional props for the button's exact `height` and `width`

**Describe alternatives you've considered**
We thought about making a component that lets the user input a size that we then divide by 3 :P But that's super hacky and doesn't work with "sm", "md", etc. which we use sometimes. I guess maybe we can add a specific prop for setting the pixel size, but that's pretty hacky and a more official version would be nice

**Comment by pdanpdan** [comment]
Sorry, the size cannot be computed the other way around.

**Comment by Powersource** [comment]
You mean for the text size? In my case I don't care about that since I've only got a custom icon inside the button.

Plus, why wouldn't that be possible with some refactoring?

**Comment by pdanpdan** [comment]
The font size applies to the icon also. And if in your case it doesn't matter it's a 10 seconds job to get the correct font size (1/3 of desired diameter)
