### ISSUE TITLE
v-slot cannot use uppercase or mixed case names

### ISSUE THREAD

**Issue by brakop** [quasarframework/quasar#7513]
Found this while adding custom menu items to [q-editor](https://quasar.dev/vue-components/editor) using templates with v-slots and the definition stanza, but in short, if you use anything aside from lowercase characters or numbers to identify your v-slot it will never be found. What's truly odd to me, is that the <template v-slot:<name>> The name upper or lowercase does not matter. However, add ANY uppercase character to the toolbar definition and it will never find/render the template.

[CodePen (Broken) Example](https://codepen.io/steelon169/pen/MWKdxjY?editable=true&editors=111%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Feditor)
To "fix" the example, just change "Token" to "token" on line 14.

**To Reproduce**
Working Examples: (toolbar definition | template definition)
['token']   | <template v-slot:"token">
['token']   | <template v-slot:"TOKEN">
['token']   | <template v-slot:"tOkEn">
['token']   | <template v-slot:"ToKeN">

Failing Examples (which I expected would work as long as case matched, but they don't):
['TOKEN']   | <template v-slot:"TOKEN">
['ToKen']   | <template v-slot:"ToKen">
['tOkEn']   | <template v-slot:"tOkEn">

1. Go to the CodePen
2. Change ['Token'] to ['token'] on line 14, you'll see the Token drop down appear in the toolbar menu.
3. Change it back to 'Token' (or any other uppercase combination) and watch Token disappear with no error/warning/explanation

**Expected behavior**
If the case matches, it should find the v-slot name. I was just trying to do some appropriate naming: RowCount and could not figure out why it wouldn't render but 'symbol' would until I stumbled across the case. Either that or AT LEAST tell me "could not find definition 'RowCount' so that I know that's why the template isn't loading.

**Screenshots**
Broken Code Pen:
![image](https://user-images.githubusercontent.com/17260055/88756508-293f9d80-d1a7-11ea-90d1-ee6064f68ac4.png)
Working Code Pen:
![image](https://user-images.githubusercontent.com/17260055/88756566-512f0100-d1a7-11ea-9017-ce4fabbdde04.png)

**Platform (please complete the following information):**
OS: Linux running from Docker container
This actually isn't a compiled Quasar, it's running on a ColdFusion server using these JS libraries for Vue and Quasar:
    <script src="https://cdn.jsdelivr.net/npm/vue@^2.0.0/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@1.9.15/dist/quasar.umd.min.js"></script>

Browsers: Chrome

**Comment by pdanpdan** [comment]
Hello. Very good and detailed bug report, but

https://github.com/vuejs/vue/issues/9449
https://gitmemory.com/issue/vuejs/vue/11528/660709335

**Comment by brakop** [comment]
Thanks for the quick answer! A trap for young players then! Cheers!

**Comment by pdanpdan** [comment]
It's better to use all lowercase for slot names. But I think if you only use render functions then mixed case will work on slot names. It's just a html / sfc thing.
