### ISSUE TITLE
QInput with dropdown ( input-group support for Inputs )

### ISSUE THREAD

**Issue by tjunussov** [quasarframework/quasar#7516]
**Is your feature request related to a problem? Please describe.**
Trying to implement QInput with Dropdown feature with whole "filled" design, 
I Know there is QSelect(use-input) but selected value affects v-model (did't find how to modify QSelect to behave differently)

**Describe the solution you'd like**
`<qselect use-input v-selected-model="selectedModel" :prefix="selectedModel" v-model="inputModel">`

**Describe alternatives you've considered**
I need Dropdown to modify for example prefix of QInput, I'm from BootstrapVue fan community, I would solve it via 
```
<input-group>
  <input>
  <dropdown>
</input-group>
```

**Additional context**
So I asume there is ways to achieve this:

1. modify `qselect` and introduce `v-selected-model` property or `split-value-and-options`
2. modify `qinput ` with `qselect `slot ?
3. introduce new component like input-group 
4. tweaking callback functions on `qselect `maybe ?

**Comment by pdanpdan** [comment]
Hello. This can be easily done by using the slots of QInput. Please use the discord channel or the forum for help.

**Comment by tjunussov** [comment]
Strange results happens :(
I dont want select to display its value, only show dropdown icon 
```
q-input(filled v-model="name"  label="Employee" :prefix="position" stack-label)
    template(v-slot:append)
       q-select(v-model="position" :options="positions")
```
![image](https://user-images.githubusercontent.com/2089278/88775973-2fce1500-d1a7-11ea-8f01-e2fbbb1c03f8.png)

**Comment by pdanpdan** [comment]
make a codepen, and use `hide-selected`

**Comment by tjunussov** [comment]
Here is [CodePen](https://codepen.io/tjunussov/pen/ExPzBQW) with use of hide-selected, still solved part of the issue, still background persist

![image](https://user-images.githubusercontent.com/2089278/88778040-cac7ee80-d1a9-11ea-9c02-c47c175adb4a.png)

**Comment by tjunussov** [comment]
> make a codepen, and use `hide-selected`
> https://codepen.io/pdanpdan/pen/ZEQNdJQ?editors=1100

Looks great! Thanks! maybe add this use case in doc ?

**Comment by tjunussov** [comment]
> Strange results happens :(
> I dont want select to display its value, only show dropdown icon
> 
> ```
> q-input(filled v-model="name"  label="Employee" :prefix="position" stack-label)
>     template(v-slot:append)
>        q-select(v-model="position" :options="positions")
> ```
> 
> ![image](https://user-images.githubusercontent.com/2089278/88775973-2fce1500-d1a7-11ea-8f01-e2fbbb1c03f8.png)

Here is my mistake, you need to use borderless and hide-selected
https://codepen.io/tjunussov/pen/ExPzBQW

**Comment by pdanpdan** [comment]
I updated the codepen a little to show some more things to set in CSS

**Comment by tjunussov** [comment]
Thanks! Final issue is width of the dropdown menu (options),

**Comment by tjunussov** [comment]
according to `hide-selected` it will be depricated ?
So my issue Feature request still actual i think, did you tried [Input Group from Bootstrap ](https://bootstrap-vue.org/docs/components/input-group) it solves a lot of issues with inlining multiple inputs and buttons

**Comment by pdanpdan** [comment]
What do you mean? Why deprecated?

**Comment by tjunussov** [comment]
> Why deprecated?
According to this https://github.com/quasarframework/quasar/issues/3987
and in latest docs there is no metion about this prop `hide-selected`

And btw, may be it is possible to use QSelect with some kind of hook ? When user selects option, hook hijacks value to another variable and returns false, so value of select become unchanged  ?

**Comment by tjunussov** [comment]
In Discord, another interesting approach found, here is code pen https://codepen.io/tjunussov/pen/VweOoEo
```
<q-select filled use-input hide-selected  flat 
   :value="name" :prefix="position" :options="positions" @input="onSelect" @input-value="onInput">
</q-select>

new Vue({
  el: '#q-app',
  data: function () {
    return {
      version: Quasar.version,
      positions:['Driver','Singer'],
      position:'Driver',
      name:'Michael Lorie'
    }
  },
  methods: {
    onInput(value){
      this.name = value;
    },
    onSelect(value){
      this.position = value;
    }
	}
})
```

Almost working! Fine, but when focus is removed from QSelect, value is clearing by itself? What am I doing wrong?

![image](https://user-images.githubusercontent.com/2089278/88844344-52dae200-d204-11ea-94e4-d87c1428cd3e.png)

**Comment by tjunussov** [comment]
I think value is clearing because value is new, so I added ` new-value-mode="add"` prop, now it saves value, but random abnormal clearing still happens, i need press ENTER to save value, if click outside without ENTER menu value is cleared,
