### ISSUE TITLE
QTable and Virtual Scrolling `scrollTo` not working correctly

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7517]
**Describe the bug**
If I want to move to the specified **far** position, you need to scroll **twice.**
However, if the destination is on the **viewable** table body, nothing happens at all.

**Codepen/jsFiddle/Codesandbox (required)**
[scrollTo Demo](https://codepen.io/test-qq/pen/OJMeJee)

**To Reproduce**
1. Use the example above
2. enter the line number you want to scroll to
3. click "go" button

**Expected behavior**
The row number of the scroll target should always be at the top of the table body.

**Platform (please complete the following information):**
OS: Windows 10, macOS 10.15.3
Node: v12.16.2
Browsers: Chrome v84.0.4147

**Comment by pdanpdan** [comment]
Hello - this is by design - if you scroll in the end direction the item will be aligned at the end, if you scroll in the start direction the item will be aligned at the start.

**Comment by kevin61416** [comment]
Okay, thank you for your explanation, but I need this feature (`always be at the top of the table body`) in my application scenario. Is there a way to achieve it? Or can be a new feature?

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.13.0.
