### ISSUE TITLE
header-cell and body-cell slots for selection checkbox in QTable

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7519]
**Is your feature request related to a problem? Please describe.**
In my application scenario (e.g., @click.shift="myFunc"), I need to make many customizations for the checkbox of the QTable, However, it does not provide a slot for this.

**Describe the solution you'd like**
Provide header-cell and body-cell slots for QTable.

**Describe alternatives you've considered**
Although this can be done through the body slot, or can implement the selection function myself, a custom checkbox is a very common requirement, and I think it should be able to easily support this.

**Comment by rstoenescu** [comment]
Hi,

Added "header-selection" and "body-selection" scoped slots. Also improved the scoped data on every header/body related scoped slots.

Will be available in Quasar v1.14.0.

For completeness, this is how it would be done without the new scoped slots:

```html
<q-table
  title="Treats"
  :data="data"
  :columns="columns"
  row-key="name"
  selection="multiple"
  :selected.sync="selected"
>
  <template v-slot:header="props">
    <q-tr :props="props">
      <q-th auto-width>
        <q-checkbox v-model="props.selected" />
      </q-th>
      <q-th
        v-for="col in props.cols"
        :key="col.name"
        :props="props"
      >
        {{ col.label }}
      </q-th>
    </q-tr>
  </template>

  <template v-slot:body="props">
    <q-tr :props="props">
      <q-td auto-width>
        <q-checkbox v-model="props.selected" />
      </q-td>
      <q-td
        v-for="col in props.cols"
        :key="col.name"
        :props="props"
      >
        {{ col.value }}
      </q-td>
    </q-tr>
  </template>
</q-table>
```
