### ISSUE TITLE
Remove transition in side menu und top bar

### ISSUE THREAD

**Issue by nitram** [quasarframework/quasar#752]
I would like to remove the transition I get from the side menu and the top bar when I load a quasar application. I am using the latest beta quasar version.
What can I do to disable this transition?
Or is it possible to change the transition from coming form the top left to simply fade in?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2828767/28628251-6ec68a48-7224-11e7-8752-bc192c99f3db.gif)

**Comment by JCharante** [comment]
The github issues section is intended for bug reports and feature requests.  You'll probably get more support by asking on the [Quasar Gitter](https://gitter.im/quasarframework/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [Quasar Forums](http://forum.quasar-framework.org/category/11/help)

**Comment by rstoenescu** [comment]
Awesome improvements in future v0.15 for QLayout ;)

**Comment by rstoenescu** [comment]
Code ready in future v0.15 so closing this.
