### ISSUE TITLE
Using preFetch to mutate vuex causes errors across page components

### ISSUE THREAD

**Issue by pianopronto** [quasarframework/quasar#7520]
**Describe the bug**
I am using preFetch to call an API and populate vuex with the information each page will need. Each page's preFetch call to the API returns an object that overwrites the old page's object in vuex. In other words, the page object in vuex contains all the information for that page only.

When I mutate the store and replace the object, it happens before the router-view component changes, causing errors where the old page tries to access data that is no longer there. Specifically, computed properties in the old page are firing since the store is mutated before the old page is unmounted.

**Codepen/jsFiddle/Codesandbox (required)**
Basic github reproduction example, instead of using an API, I simply call the vuex mutation in prefetch directly. https://github.com/pianopronto/quasar-prefetch-test

**To Reproduce**
1. Clone repo
2. Run quasar dev
3. Open dev tools
4. Switch between the pages using the links in the drawer

**Expected behavior**
There should be someway to mutate vuex in a preFetch hook after the old component has unmounted. When using a non async preFetch, nextTick does work (see topic-next-tick branch) but when using an async prefetch that workaround doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/51970393/88827167-73605900-d17e-11ea-8434-7f512fc1a837.png)

The above shows the errors when running the master branch of the test repo, and switching from the Index page to the Other page. I put in logging statements in the preFetch hooks and router hooks. You can see after "finishing prefetch in other page" when the vuex mutation happens, the computed handler runs in the index page.

**Edit:** Added a few more console.log statements in each component's beforeMount, mounted, beforeDestroy, destroyed hooks just to give a better idea what's happening.

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: v12.14.1
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Chromium 83
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**
Am I going about this the wrong way? To give more context, each page has vastly different info that needs to be stored in vuex.

**Comment by pdanpdan** [comment]
Hello, this is expected because that's the lifecycle of vue-router. You should check in your component of you have the right data. Or just don't use preFetch and use a Vue-router hook that suits you.

**Comment by pianopronto** [comment]
Thanks @pdanpdan, you're right, vue-router mounts the new component before destroying the old one. I'll simply improve the computed properties to make sure the expected data is there. Thanks for the quick answer and confirming this can't be an issue with Quasar.

**Comment by pianopronto** [comment]
Hi again @pdanpdan, I thought about this some more, and came up with a workaround: https://github.com/pianopronto/quasar-prefetch-test/blob/topic-router-guard/src/pages/Index.vue#L19

Basically, I define a afterEach route hook in preFetch, and mutate vuex there, then unregister the hook. However, I needed to modify quasar to pass the router object to the preFetch function. So my question is, can upstream quasar be modified to pass router by default? Are there reasons this is a bad idea or goes against conventions? I should note that I do use SSR which is why I rely on preFetch in the first place.

In the same vein, but unrelated to this issue, it would also be nice is App was passed to preFetch, since I inject my axios instance there. Right now, I just call it from `store.$axios` but it would be clearer if I called it from the main app instance IMO. 

Copy pasted code for posterity, and in case any one ever stumbles upon this issue:
```
  async preFetch ({ router, store, currentRoute, previousRoute, redirect, ssrContext }) {
    console.log('running prefetch in index page')
    // simulate timeout
    await new Promise(resolve => setTimeout(resolve, 100))
    const unregister = router.afterEach(() => {
      store.commit('example/setPage', {
        someObj: {
          someValue: 'bar'
        }
      })
      console.log('finishing prefetch in index page')
      unregister()
    })
  },
```

**Comment by pdanpdan** [comment]
I'm not very sure what you did is the best approach, but I think it doesn't hurt to expose the router in preFetch also, so I did o PR for that.

**Comment by pianopronto** [comment]
Hi @pdanpdan, thanks for the PR. I think there are other scenarios when using preFetch where you need to make sure that data isn't committed to vuex until the route actually changes. Could be a watcher that has some side effect that you don't want to trigger on the old component for example. Anyway, definitely an edge case, but since I'm already using preFetch for my dynamic page data, it works for me. Thanks again!
