### ISSUE TITLE
Class and Style definitions attributed to the content

### ISSUE THREAD

**Issue by PickleNik** [quasarframework/quasar#7524]
Whenever using components such as QTooltip, that have `content-class` and `content-style` attributes, it is impossible to use v-bind, because it counts as a duplicated attribute.

Unlike `class` and `style` attributes, which you can use both with v-bind: and without for the same element, `content-class` and `content-style` can only be used one way or the other, not both. The only way to bind content-classes is if you bind all of them :content-class="{ something: true, somethingElse: true, blue: condition }", which is not elegant and adds unnecessary logic.

It would be nice if we could v-bind content-class and content-style without duplicate attribute error.

![duplicateattributes](https://user-images.githubusercontent.com/31113245/88862860-4be5ac80-d1cf-11ea-833f-30f0efe4d9fb.png)

![QtooltipAPI](https://user-images.githubusercontent.com/31113245/88862616-c19d4880-d1ce-11ea-8e4b-4c40879eed49.png)

**Comment by pdanpdan** [comment]
I don't understand your use case, and I don't see the feature request. Please add a description of what you want to do and cannot do.

**Comment by PickleNik** [comment]
> I don't understand your use case, and I don't see the feature request. Please add a description of what you want to do and cannot do.

Updated with screenshots.

**Comment by pdanpdan** [comment]
you know that is the case with all vue properties, yes? Class and style are 2 special cases in Vue, and they cannot be placed on another element.
