### ISSUE TITLE
QPopUpProxy does not respond to value change if target is set as false

### ISSUE THREAD

**Issue by sunsf** [quasarframework/quasar#7525]
Sample code to confirm the behaviour

    <template>
      <q-page class="flex column">
       <q-btn @click="showPop = !showPop">
          <q-popup-proxy :value="showPop" :target="false">
            <div style="background-color: white; padding: 10pt;">
              Hello
            </div>
          </q-popup-proxy>
        </q-btn>
      </q-page>
    </template>
    export default {
      data () {
        return {
          showPop: false
        }
      }
    }
    </script>

I am actually using the q-popup-proxy to show a dropdown list in a text field and the list is filtered using the text field (so I need to make the target props as false to keep the pop-up taking away focus from the text field.

**Comment by pdanpdan** [comment]
Hello. Sorry but what you are doing makes no sense. If you don't provide a target then there is no place where the QMenu/QTooltip should position. I think you are mixing up things, maybe you want is `no-focus`.
