### ISSUE TITLE
[Request] QLayout: Default Sides State

### ISSUE THREAD

**Issue by JCharante** [quasarframework/quasar#753]
There should be props to define the default state of the left/right panels/sides.

Currently in v0.14, if you don't want the panels open by default you need to add `ref="layout"` to your `<q-layout>` and call `this.$refs.layout.hideLeft()` or `this.$refs.layout.hideRight()` in your mounted() function. (or use the `v-model` prop and add the sides obj to your data())

There should instead props for QLayout called defaultLeft & defaultRight, where (following the rules of the `v-model` prop) true means visible, while false means hidden. This of course be incompatible with the `v-model` prop.

This would not change existing behavior, because defaultLeft & defaultRight would default to true.

**Comment by pdanpdan** [comment]
And what is different from v-model where you set them to false in data?

**Comment by JCharante** [comment]
@pdanpdan Nothing other than it being quicker.

**Comment by spectrolite** [comment]
If it’s not only quicker but also results in cleaner code that is easier to understand (when you read it x months later), then count me as +1 too.

**Comment by rstoenescu** [comment]
Code ready in future v0.15 so closing this.
