### ISSUE TITLE
QTabs it's not contained to its boundaries when used with CSS Grid

### ISSUE THREAD

**Issue by Rolanddoda** [quasarframework/quasar#7531]
In the codepen below, you can see a simple layout and you can observe that q-tabs components exceeds its boundaries making the content of the page to have an horizontal scroll.

Codepen: https://codepen.io/Roland1993/pen/zYrVEjV

**To Reproduce**

1. Go to the CSS part in Codepen and comment the `display: grid;` in the `.page` class.
2. See that by commenting the CSS grid style, the tabs are contained within the boundaries of the page.

**Comment by pdanpdan** [comment]
Hello. For help requests please use our discord channel or the forum.

**Comment by Rolanddoda** [comment]
If I add an `oveflow: auto` to the `.q-tabs` the issue it fixed

**Comment by Rolanddoda** [comment]
@pdanpdan I think it's a bug because the `QTabs` component should automatically stay inside the boundaries of the layout

**Comment by pdanpdan** [comment]
Quasar does not use grid. You break it - you fix it :)

**Comment by Rolanddoda** [comment]
> Quasar does not use grid. You break it - you fix it :)

CSS grid is widely supported. And that doesn't mean that if Quasar doesn't uses it, it should not support it. 
Also I don't think I break something there. I am just using CSS grid without doing any hack to the QTabs component.

But anyway, you are convinced to close this issue, so I am not insisting that it's a bug. I will go with the workaround I mentioned above.

Thank you for your time. 🙂

**Comment by rstoenescu** [comment]
Hi, It's not a matter of Quasar using it or not. You're changing how the layout works (I see some CSS for #q-app at least), but you are stumbling into some problem. Doesn't mean it's Quasar's fault. It's just that you need to dig deeper and see what your current CSS needs further to solve your needs.

**Comment by Rolanddoda** [comment]
Hi @rstoenescu and thank you for commenting.

>  You're changing how the layout works (I see some CSS for #q-app at least)

I am not changing something, I am just building a layout with CSS grid. It is true that I am adding some CSS to the `#q-app` but that's not the problem.


I edited the example by removing the sidebar and the CSS from the `#q-app` and I guess it should be simpler to understand the demo -> https://codepen.io/Roland1993/pen/RwrzEvb

Browser's can show you the grid-items by highlighting them, so here it is how it looks. (The QTabs is not contained to the layout boundaries)

![image](https://user-images.githubusercontent.com/18482346/88964598-e7e3e680-d2a9-11ea-9d4c-04e96d5e9396.png).

**By adding `overflow: auto` to the `.q-tabs` you can see that everything is fixed.**

From the CSS of the `.q-tabs` I can see that it has `display: flex` and `flex-wrap: nowrap` and that is causing the contents to overflow. By adding `overflow: auto` it can fix that as illustrated [HERE](https://jsfiddle.net/rfwgb3qz/13/)

**Comment by Rolanddoda** [comment]
@rstoenescu to be clear, I can easily fix the issue in my end by adding `overflow: auto` to the `.q-tabs`. But I thought it was an issue and that's why I spend time creating the demo and opening the issue.

If you still think it's not an issue, then it's fine with me. 🙂 

Thanks for you time, and for making Quasar awesome 🙂
