### ISSUE TITLE
Dynamic Virtual Scrolling is Not Working in Grid Mode

### ISSUE THREAD

**Issue by nkreiger** [quasarframework/quasar#7532]
When you switch from rows to grid mode with QTable, the virtual scroll breaks.

https://codepen.io/nkreiger/pen/mdVZKqO

**To Reproduce**
1. Go To quasar.dev
2. click edit codepen of the quasar dynamic virtual scroll example
3. Add prop `:grid="true"` to change to grid mode

**Expected behavior**
Table works in grid mode with virtual scroll. Scroll event registers.

**Platform (please complete the following information):**
OS: Mac 
Node: v12.14.0
NPM: 6.14.4
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Read the description on virtual-scroll prop.

**Comment by razorness** [comment]
You can hack this into QTable. Everything is there. Take a look at: 
https://codepen.io/razorness/pen/oNbrMYW

This is a simple example of a responsive Table with virtual scroll and grid display for small displays.
