### ISSUE TITLE
[docs] Signing Apps with Electron in Quasar 

### ISSUE THREAD

**Issue by vahost** [quasarframework/quasar#7539]
I'm having trouble figuring out how to create a Mac app with Electron and sign that app to get it past Apple's gatekeepers. Right now, when I build an app, it generates an error when opened: 

"[App] can't be opened because Apple cannot check it for malicious software."

With the help of metalsadmin at forum.quasar.dev, I looked at https://www.electronjs.org/docs/tutorial/code-signing#code-signing but I am having a lot of trouble figuring out how to implement it with quasar using those notes.

This article appears to have identified the generic steps involved, but I don't know where to add them in Quasar:
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

That article begins by saying, "Starting with MacOS 10.14.5, all signed applications by ‘new’ developers will need to be notarized or they will trigger Apple’s Gatekeeper software and prevent users from installing your app. That means that aside from signing your application, you will need to notarize it as well."

There is a page for helping to add to the store using Cordova and Capacitor, but I can't find anything in the docs for similar help with Electron.

I'm able to create a PC version of the app without signing, although I saw a note that says that even this might not work properly for all PC users.

So we really need some docs to help with signing Electron versions of our apps.

**Comment by pdanpdan** [comment]
Hello. As you already researched this problem, put down your research in a PR for the docs.

**Comment by vahost** [comment]
@pdanpdan  Calling what I've done "research" would be generous because I really don't understand an awful lot about what I've found so far. I don't feel qualified to even begin a PR on this.

**Comment by IlCallo** [comment]
@vahost have you found a solution? It's unfeasible for the team to test every single environment and configuration, but we gladly accept contributions from the community to enhance the docs with your experience

**Comment by vahost** [comment]
@IlCallo No, I haven't found a solution yet. 

I was a little surprised to see you characterize this as an example of a requested test for "every single environment and configuration" because from what I understand, Apple is now requiring this of submissions from all new developers. So while it doesn't apply to developers who submitted apps before a certain date, it definitely applies to all submissions by developers (like me) who establish their Apple account after that date, which means that this issue will keep becoming more and more prevalent over time.

**Comment by pdanpdan** [comment]
Speaking strictly for me. I'm not going to throw out of the window the money for a Mac and for a developer account just to discover this week's new shitty way to force developers not to be able to distribute their programs without paying to apple :)

**Comment by IlCallo** [comment]
@vahost I see your point, but I'm afraid I won't be able to check this out shortly, gonna ask if someone else in the team already hit this roadblock and can PR the docs to cover this new limitation

**Comment by vahost** [comment]
@IlCallo  Thank you for your efforts!

**Comment by nklayman** [comment]
@vahost are you using electron-builder or electron-packager? I'm not sure about code signing with packager, but I know builder supports it, see [the docs](https://www.electron.build/code-signing). Hopefully this can help you. As for the article you posted, the `mac` configuration will go inside `quasar.conf.js` under `electron.builder`, see [these docs](https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron#Quasar.conf.js) for details.

**Comment by vahost** [comment]
I'm using electron-builder, so that part's okay. 

I looked at the Signing Apps doc page you linked to, and I find it confusing. The two sections that seem relevant are "How to Export Certificate on macOS" and perhaps "How to Disable Code Signing During the Build Process on macOS"

I'm not certain what the second section is about. Is that a way to build an app for Mac without getting the message, "[App] can't be opened because Apple cannot check it for malicious software."? If so, that would work for me because I really don't need to have my app in Mac's store. I just want the user to be able to download it from my website and install it without issues.

However, even if that section is what I'm looking for, I'm lost on what to do with it. It says, "To disable Code Signing when building for macOS leave all the above vars unset except for CSC_IDENTITY_AUTO_DISCOVERY which needs to be set to false. This can be done by running export CSC_IDENTITY_AUTO_DISCOVERY=false."

All very nice, I'm sure, but where do I unset those vars? That part isn't clear to me at all. And where do I set CSC_IDENTITY_AUTO_DISCOVERY=false? Do I do set or unset them somewhere in /src-electron? Perhaps in the electron-main.js file? I don't see an obvious candidate in the electron files in my project.

**Comment by vahost** [comment]
I found a solution that works for me. I don't need signing for my purposes. I was just trying to do it because Mac was requiring it. But there's a way to disable signing. For Quasar users, in the quasar.conf.js file, go to the electron.builder object and add this parameter:
forceCodeSigning: false

That turns off the signing requirement. This is a solution for someone who doesn't need their app included in the Mac app store but who simply wants it to be downloadable off their own website.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
