### ISSUE TITLE
Q-Drawer transition issue

### ISSUE THREAD

**Issue by ECallum** [quasarframework/quasar#7540]
**Describe the bug**
Q-Drawer transition rate is not changing.

**To Reproduce**
I have changed the transition speed of the Q-Drawer component in the core code of the Quasar framework from 150 to 500 yet it is not taking effect.

**Expected behavior**
Q-Drawer transition speed should be changed.

**Platform (please complete the following information):**
OS: Windows 
Browsers: Chrome

**Comment by pdanpdan** [comment]
Hello. It is clear you have changed it in a bad way. As you have modified the code it can only be opened as a bug on your application.

**Comment by ECallum** [comment]
Can you please tell me what I have to do to change q-drawer transition speed?

**Comment by pdanpdan** [comment]
If you change the 150 in the QLayout.js to 500 it should work

**Comment by ECallum** [comment]
But it is not working brother :) In the Q-Layout.js, there is no 150, it is in the Q-Drawer but it is not taking effect no matter what I do.

**Comment by pdanpdan** [comment]
According to your provided information in the issue template it should be there and work.

**Comment by fxjs** [comment]
> But it is not working brother :) In the Q-Layout.js, there is no 150, it is in the Q-Drawer but it is not taking effect no matter what I do.

Could you tell me how to modify it, I encountered the same problem, is it resolved? Thanks.
