### ISSUE TITLE
QDate: Disable weekdays

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#7542]
QDate have `option` prop to limit user's select date, will be useful if have option for disable by Weekday(s), like [PIGNOSE Calendar's Disabled Weekdays Option](https://www.pigno.se/barn/PIGNOSE-Calendar/) (go to section "Disabled Weekdays Calendar")

**Comment by pdanpdan** [comment]
Hello. In the option prop you can disable the day if it's (not) weekday
