### ISSUE TITLE
QTable with Virtual Scrolling: Loss of `focus` when using the arrow up/down keys

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7545]
**Describe the bug**
When using the up and down keys to scroll the table, the `focus` will be lost when the Virtual Scrolling component is loaded new items.

**Codepen/jsFiddle/Codesandbox (required)**
[Quasar Official Demo](https://codepen.io/test-qq/pen/jOWgxpr)

**To Reproduce**
1. Press the up/down arrow keys to scroll through the table until see the loading placeholder
2. Press arrow key again and nothing happens

**Platform (please complete the following information):**
OS: Win 10, macOS v10.15.3
Node: v12.16.2
NPM: v6.14.5
Browsers: Chrome v84.0.4147.105

Thanks 👍

**Comment by pdanpdan** [comment]
Yes, this will happen if the focus was on an element that was scrolled out of view. We'll try to improve this in future iterations. If you want to workaround this add a user focus the scrollbar and use arrow keys from there.

**Comment by kevin61416** [comment]
Thanks, this is helpful 😀

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.13.0.
