### ISSUE TITLE
[Feature Request] Build modern and legacy mode together

### ISSUE THREAD

**Issue by Saeid-Za** [quasarframework/quasar#7546]
Hello,

**Is your feature request related to a problem? Please describe.**
Before releasing @Quasar/app v2, developer could've explicitly asked for modern or legacy browser support by using `--modern` flag in the CLI. this feature was dropped when @Quasar/app v2 was out and it now only depends on browserlist config.
But there is a problem with current and previous implementations. they could've provided both legacy and modern browser support on the same build, by using the method described in [vue-cli ](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode )page.

> The modern bundle is loaded with <script type="module">, in browsers that support it; they are also preloaded using <link rel="modulepreload"> instead. The legacy bundle is loaded with <script nomodule>, which is ignored by browsers that support ES modules.

some of the benefits of using this method for building & serving the website / web app are smaller bundle size and faster parsing  for modern browsers.

**Describe the solution you'd like**
Provide a modern/legacy build that would take browserlist into account and then generate one artifact that would consist of these two (legacy and modern) builds. the implementation on vue-cli could help on this matter.

**Comment by pdanpdan** [comment]
The problem with modern is that the only switch between the 2 builds on loading in the browser is based on support of modules.
And based on https://caniuse.com/#feat=es6-module it will match:
- old edge (that will break spectacularly because it fetches but not executes the code, among other problems)
- Safari 10

Basically the only thing that is excluded is IE11 :)

**Comment by rstoenescu** [comment]
Hi, This has been discussed countless times. Almost all browsers today (which includes 80%+ of market share) support high levels of ES code. From our resources perspective, it doesn't makes sense to invest time in a complex feature that decreases its usefulness with each day passing. At the end of the day it's a matter of doing extra work for mostly only IE11. We'd rather spend time on new components/directives/plugins/features.

**Comment by Saeid-Za** [comment]
Hello, thanks for clarification, i agree that this a heavy work to achieve too little.
didn't know about the support coverage of es6-modules are almost over 90%.
