### ISSUE TITLE
QTable with Virtual Scrolling: loading very slow when work with selection feature or QPopupEdit

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7551]
**Describe the bug**
I got 130ms average scroll loading time If disable selection props and QPopupEdit  body-cell.
However, when I enabled them, the load time increased to 330ms, which was too slow to be acceptable.
I think the performance of cooperation between components should be enhanced.

**Codepen/jsFiddle/Codesandbox (required)**
[VScroll + Select + QPopupEdit](https://codepen.io/test-qq/pen/JjXPWVv)

**Screenshots**
<img src="https://i.imgur.com/NCB8pWT.png">

**Platform (please complete the following information):**
OS: Win10, macOS v10.15.3
Node: v12.16.2
NPM: v6.14.5
Browsers: Chrome v84.0.4147.105

**Comment by pdanpdan** [comment]
Hello. For me it looks like it works pretty good.
But I can hardly understand the bug label :)
If we can improve something we'll improve.

**Comment by kevin61416** [comment]
Ok! Thank you @pdanpdan.
Sorry for the misclassification caused by negligence.
