### ISSUE TITLE
QTable pop-up editing does not work with sorting

### ISSUE THREAD

**Issue by martijn788** [quasarframework/quasar#7552]
**Describe the bug**
When you are editing a sorted column, the rows are flipping on the background. therefore you are changing all the different rows instead of the one you want to change. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/martijn788/pen/QWNLgJY?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Ftable

(Quasar table pop-up editing example from the documentation)

**To Reproduce**
1. sort on calories (desc)
2. Try to edit the calories of the top row to 1243232342 (typing one for one)
3. The rows are changing on the background

**Expected behavior**
I expect that the sortation will only change when the row is saved by clicking on the save button. 

**Screenshots**
![quasar](https://user-images.githubusercontent.com/19963444/89195220-bec49e00-d5a8-11ea-8956-60a774628839.gif)

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers: Chrome & Firefox
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Do not edit the column used as key and the column(s) used for sorting. Make a clone of them and sort by one and edit the other.

**Comment by martijn788** [comment]
https://github.com/quasarframework/quasar/pull/7553

I've created a pull request to update the documentation with the extra information you provided here.
