### ISSUE TITLE
QInfiniteScroll - Fails to load more content on filtered list unless scroll position is greater than 0

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#7554]
**Describe the bug**
Let's assume a container is filled with enough data so that it does not trigger `@load` anymore.
If this data now gets filtered, so that new space is available, then `@load` only gets triggered if the container got scrolled at least one pixel.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/danielfaust/pen/ExKYQdG?editors=1010

**To Reproduce**
1. In the Codepen example above, just let the complete data load without scrolling at all.
2. Press "Apply fake filter", which removes all items except the first one. There is enough space available for new elements to be loaded, but nothing happens.
3. **Reload** (F5) the page
4. Wait until the window has been filled with data and no longer loads more of it.
5. Scroll down at least one pixel.
6. Click "Apply fake filter", which again removes all items except the first one. The free space will trigger an @load event and more items are loaded, as many times as necessary to fill the entire area.

**Expected behavior**
In step 2) above, `@load` should be triggered, even if no scrolling has been done.

**Platform (please complete the following information):**
OS: Windows, Android 10
Browsers: Chrome, Firefox
Android: Chrome, Firefox

**Additional context**
Sometimes even after scrolling down at least one pixel, if more data loads and you scroll up and down and finally all way up, and then press the "Apply fake filter" button, new data won't be loaded after the filter removed all but the first item.

**Comment by pdanpdan** [comment]
Hello - it is meant to load data, not as a dynamic guess what funny thing I can do :)
Call the stop method before modifying the data and resume after - you might be lucky.

https://codepen.io/pdanpdan/pen/oNxvqxj?editors=1010

**Comment by danielfaust** [comment]
Hi, I don't understand what you are trying to tell me with "not as a dynamic guess what funny thing I can do".

Where is the difference between having not scrolled and having scrolled 1 pixel? If there were to be a difference, then why does it do the initial loading even though the container never got scrolled?

Thank you for the solution.

**Comment by pdanpdan** [comment]
The problem is not with scrolling 1px, but with making the scroll smaller when it knew it was bigger.
