### ISSUE TITLE
how to hidden the expansion-item arrows ?

### ISSUE THREAD

**Issue by dishcheng** [quasarframework/quasar#7556]
![image](https://user-images.githubusercontent.com/26062252/89261283-618c2380-d660-11ea-9148-c342098dd12f.png)

these items are links

**Comment by pdanpdan** [comment]
Hello. For help request please use our discord channel or the forum.

**Comment by wilbertverayin** [comment]
inspect element using the dev tool and add css classes to hide/remove them
