### ISSUE TITLE
Layout Drawer: v-model with breakpoint doesn't restore after window resize via overlay mini-mode 

### ISSUE THREAD

**Issue by tjunussov** [quasarframework/quasar#7559]
**Describe the bug**
When using Layout Drawer with `overlay `and `mini-mode` feature 
after window is resized, drawer stays hidden, value of` v-model` stays false, in other scenarios it restores to true automatically 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tjunussov/pen/eYZObYm

**To Reproduce**
1)  set attr overlay and min-mode to q-drawer
2) resize window width and look at left drawer menu, drawer menu doesnt appear after resizing, 
and v-model value always shows false

**Expected behavior**
in other scenarious when overlay is not specified, v-model restores to set to true, 
maybe we should introduce "BreakpointRestoreVisibilityAfterResize"

**Screenshots**
![image](https://user-images.githubusercontent.com/2089278/89270399-1a506380-d65d-11ea-8067-6193e3a21639.png)

**Platform (please complete the following information):**
Browsers:

**Comment by pdanpdan** [comment]
Hello. If you are using overlay mode then the menu does not restore it's state.
https://codepen.io/pdanpdan/pen/OJNLGba?editors=1010
