### ISSUE TITLE
Qdate. Month picker.

### ISSUE THREAD

**Issue by kulkoff** [quasarframework/quasar#7560]
Hey. Add a props that will not show the calendar with days. emit-immediately doesn't work very well. The event is triggered to change any field. If I want to change the month and year, then I have to open the form 2 times. If I add a props - no-days, when I select the desired year and month, let the form close and the day is set to 1 day. Sorry for my english

**Comment by pdanpdan** [comment]
Hello. If you want a month-year selector it makes no sense to use the QDate component. Use 2 fields for year and month.

**Comment by kulkoff** [comment]
Well, it's just not very beautiful.
But competitors have similar functionality implemented - https://vuetifyjs.com/ru/components/date-pickers/#month-pickers
And add one props to the quasar and everything will be fine ;)

**Comment by pdanpdan** [comment]
use that one, we don't insist on any specific components you are using

**Comment by kulkoff** [comment]
But it was not bad for choosing a credit card expiration date at least.

**Comment by rstoenescu** [comment]
The month picker is equivalent to a QSelect with the months as options, for which reason it doesn't makes sense to add this feature...

**Comment by gsmitto** [comment]
> Hey. Add a props that will not show the calendar with days. emit-immediately doesn't work very well. The event is triggered to change any field. If I want to change the month and year, then I have to open the form 2 times. If I add a props - no-days, when I select the desired year and month, let the form close and the day is set to 1 day. Sorry for my english

Hi @kulkoff  i leave here a pen with a solution made with quasar https://codepen.io/gsmitto/pen/wvgmYvr
