### ISSUE TITLE
QTable rowIndex should respect virtual scroll

### ISSUE THREAD

**Issue by razorness** [quasarframework/quasar#7562]
**Describe the bug**
`props.rowIndex` represents index of rendered slice instead of row index when using virtual scroll.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/razorness/pen/OJNLeym?editors=1010

Left column generated field `index`, right column `props.rowIndex`.

**Expected behavior**
`props.rowIndex` should represent the index of the current item in the list.

May you can add another property.

**Comment by pdanpdan** [comment]
good catch, ty

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.13.0
