### ISSUE TITLE
Generate splascreen without combining with icon

### ISSUE THREAD

**Issue by OtabekSadiridinov** [quasarframework/quasar#7565]
**Is your feature request related to a problem? Please describe.**
When I installed IconGenie V2 and generate icon and splashscreen for my app icon is created successfully, but the splashscreen was combined with app icon.

**Describe the solution you'd like**
I would like to see if there is an option which asks user to generate a splashscreen by combining app-icon.png with app-splashscreen.png or just using  app-splashscreen.png as is.

**Describe alternatives you've considered**
There was such opportunity in IconGenie V1.

**Additional context**
My splashscreen before:
![image](https://user-images.githubusercontent.com/60849894/89334203-983d5a80-d6af-11ea-9451-9d048eaec246.png)

My Icon before
![pngfuel com](https://user-images.githubusercontent.com/60849894/89334310-c1f68180-d6af-11ea-8b11-4beb3e081604.png)

Generated splashscreen:
![image](https://user-images.githubusercontent.com/60849894/89334369-d9ce0580-d6af-11ea-9069-a8e414cf52ba.png)

**Comment by rstoenescu** [comment]
Hi,

Use the `--splashscreen-icon-ratio` param (set it to 0).

Extract from docs:

```
--splashscreen-icon-ratio  Ratio of icon size in respect to the width or height
                               (whichever is smaller) of the resulting splashscreen;
                               Represents percentages; Valid values: 0 - 100
                               If 0 then it doesn't add the icon of top of background
                               Default: 40
```
