### ISSUE TITLE
IconGenie: generated ic_launcher images are cropped/zoomed too much when rounded

### ISSUE THREAD

**Issue by kmschott** [quasarframework/quasar#7566]
When I generate assets for capacitor, the `ic_launcher` files for android look zoomed in or cropped. Is this a configuration thing or how do I prevent this behaviour?

My command is: `icongenie g -m capacitor -i ./app-icon.png --quality 12 --skip-trim`

`ic_launcher` and `ic_launcher_round` are wrong, the app icon should always be like `ic_launcher_foreground`:

![Screenshot 2020-08-05 at 12 42 18](https://user-images.githubusercontent.com/54347972/89403992-87c1ca00-d719-11ea-9a57-3738f5408f14.png)

**Comment by rstoenescu** [comment]
Hi, you need to apply a padding (check IconGenie part of the docs).

**Comment by kmschott** [comment]
Hm, that's unsatisfactory. When I apply a padding, it is applied to all icons. Currently all icons that come out look right, only in Android Studio they are "zoomed in".

**Comment by rstoenescu** [comment]
You could generate a profile file from the IconGenie's defaults and then tweak it (split it into two profile files - one for those needing padding and ones that don't).

**Comment by kmschott** [comment]
I think IconGenie is not doing the right job here and this workaround is not the solution for my problem. Maybe these file should have some kind of an "auto-padding"?

**Comment by kmschott** [comment]
I few more "real world" examples in the doc would be great.

**Comment by rstoenescu** [comment]
I assure you it's doing exactly as instructed. Would love to help out more, but I need your original icon.

**Comment by kmschott** [comment]
Okay, thanks. I sent you my logo via Email.

**Comment by kmschott** [comment]
I upgraded IconGenie to latest version (2.3.1), applied a padding (5,5 and also 10,10) => no effect, did not solve the problem.

**Comment by kmschott** [comment]
@rstoenescu ?

**Comment by cabassi** [comment]
I can confirm the issue. Icons for iOS get generated just fine, but for Android they get trimmed and zoomed.

Also I couldn't find a way to specify a background color for the Android icons, so if you have a white icon with dark background you don't see anything.

Quasar in general has great documentation but regarding to IconGenie is missing some real world usage examples ;)

**Comment by kmschott** [comment]
@cabassi Like you said, Quasar and IconGenie are pretty nice but documentation for IconGenie is missing with some examples; maybe we need to adjust a padding in Android Studio itself?

**Comment by cabassi** [comment]
> @cabassi Like you said, Quasar and IconGenie are pretty nice but documentation for IconGenie is missing with some examples; maybe we need to adjust a padding in Android Studio itself?

I resolved doing it the old way directly in Android Studio.

Also if you try to use 2 profile for the icon generation in params.include you can't write capacitor.ios / capacitor.android in order to discriminate the destination of your fresh generated icons, making it impossible to use another source for the Android icons with larger padding to avoid the cropped image.
