### ISSUE TITLE
QTable: `virtual-scroll-sticky-size-start` prop causes app block

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7567]
**Describe the bug**
When the table is inactive (keep-alive), if I insert "multiple" table rows elsewhere, the entire program will block (or I guess it may be infinite updating). If I only insert "one" row, the application runs normally.

This situation only occurs when the `virtual-scroll-sticky-size-start` property is used. If I only use the `virtual-scroll` prop, there is no such problem.

**Codepen/jsFiddle/Codesandbox (required)**
[bug of virtual-scroll-sticky-size-start blocked the app](https://codepen.io/test-qq/pen/eYZYmGZ)

**To Reproduce**
[YouTube Reproduce Demo](https://youtu.be/et6phfa-hAw)
1. Go to 'Home Page'
2. Select 2 or 3 rows at will, and then press "b" key to add bookmarks. 
3. Go to 'Bookmark Page' (to create instance) by the drawer, and you will see your selections.
4. Go back to 'Home Page'
5. Select 2 or 3 rows at will, and then press "b" key to add bookmarks. 
6. App Blocking!

If you select only 1 row in step 5, the application may be run normally.

**Expected behavior**
The program should not get stuck and add data successfully.

**Screenshots**
<img src="https://i.imgur.com/gCFqJ9C.png">
Home Page is Blocking and selections not working.

**Platform (please complete the following information):**
OS: Win 10, macOS 10.15.3
Node: v12.16.2
NPM: 6.14.5
Browsers: Chrome v84.0.4147.105, iOS v13.4.1 Safari & Chrome
Electron: v9.1.0

**Additional context**
In the CodePen demo, HomeTable Component is the 'Subject' role in the Observer Design Pattern;
BookmarkTable Component is the 'Observer' role in the Observer Design Pattern.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.13.0

**Comment by kevin61416** [comment]
Amazing efficiency!
Thank you @pdanpdan @rstoenescu
