### ISSUE TITLE
Typescript: async support for RouteCallback and StoreCallback helpers

### ISSUE THREAD

**Issue by larvanitis** [quasarframework/quasar#7572]
**Describe the bug**
I think `RouteCallback` should return `VueRouter | Promise<VueRouter>` and `StoreCallback` should return `Store<any> | Promise<Store<any>>`.

![image](https://user-images.githubusercontent.com/1144686/89468817-ee2e0300-d780-11ea-811d-609e081d6d41.png)

**Comment by IlCallo** [comment]
Per 964f460523ab14654c2db8aaf539bd69ff9c82d2 it seems this is a legitimate usage of router setup.
@rstoenescu can you confirm this is valid usage? I could not find it into the docs, we shall probably integrate it into https://quasar.dev/quasar-cli/routing#Introduction.

@larvanitis after Razvan confirmation, could you please PR it [here](https://github.com/quasarframework/quasar/blob/9a953b9c01dfc42eb51ce744d7376ebf7184cfd0/app/types/route.d.ts#L13) and [here](https://github.com/quasarframework/quasar/blob/9a953b9c01dfc42eb51ce744d7376ebf7184cfd0/app/types/store.d.ts#L18), and mention this use case into the docs?

**Comment by rstoenescu** [comment]
@IlCallo This is valid usage.

**Comment by rstoenescu** [comment]
Enhancements will be available in "@quasar/app" v2.0.10
