### ISSUE TITLE
QSlider is not reactive after interacting with it multiple times.

### ISSUE THREAD

**Issue by douglance** [quasarframework/quasar#7573]
**Describe the bug**
The slider should be responsive when the value is set, it should go to where the value is set to. Currently, only the first interaction is responsive.

**Codepen/jsFiddle/Codesandbox (required)**
[Codepen](https://codepen.io/douglance/pen/mdPdQKR?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fslider)

**To Reproduce**
1. Click anywhere on the slider higher than 5
1. The slider goes to five.
1. Click anywhere on the slider higher than 5
1. The slider remains where you click.

**Expected behavior**
1. Click anywhere on the slider higher than 5
1. The slider goes to five.
1. Click anywhere on the slider higher than 5
1. The slider goes to five.

**Comment by pdanpdan** [comment]
Hello. For help requests please use our discord channel or the forum.

**Comment by douglance** [comment]
It’s a bug. Not a help request.

**Comment by pdanpdan** [comment]
No, it's a help request because you don't know how reactive values work in Vue and you are expecting something to happen when you change nothing.

**Comment by douglance** [comment]
That should not be the expected behavior. The slider position and its model are out of sync.

**Comment by pdanpdan** [comment]
You can always open o bug report on Vue if you wish :)

**Comment by douglance** [comment]
It doesn’t have anything to do with how Vue works. The component could be written in vanilla js and expose a Vue interface and the issue would remain. 

Components are abstractions that have expected behaviors. The most basic behavior of a slider is that its position directly correlates to its value. It’s literally the primary function.

**Comment by rstoenescu** [comment]
@douglance Dude, on any change to the QSlider you are setting the model to 5. `@change="val => { lazy = 5 }"` ... you actually want `@change="val => { lazy = val }"`

**Comment by douglance** [comment]
I know how to make it function in that way. The point of the Codepen is that the value of the slider's model and the value the slider shows the user are different.

**Comment by rstoenescu** [comment]
@douglance There is an internal optimization in place to avoid extra renders (so for perf). You could:

```
@change="onChange"

onChange (val) {
      this.lazy = val
      this.$nextTick(() => {
        this.lazy = 5
      })
    }
```

**Comment by douglance** [comment]
Ahh--I did not suspect a $nextTick issue there. I would still contend that that behavior is unintuitive and should be avoided if possible.

**Comment by pdanpdan** [comment]
As you seem to have problems understanding simple reactivity maybe you can understand basic one: https://codepen.io/pdanpdan/pen/dyMPGOv?editors=1010
