### ISSUE TITLE
Notify with action causes previous notification to snap into position

### ISSUE THREAD

**Issue by Codebreaker101** [quasarframework/quasar#7575]
**Describe the bug**
When activating a notification with actions, previous notifications snap into position, instead of sliding. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/codebreaker101/pen/oNxNRVV

**To Reproduce**
Click on the two buttons to view the difference

**Expected behavior**
For the previous notifications to slide.

**Comment by pdanpdan** [comment]
Hello. This was already fixed as a side effect of d1510d4957c745353ecd78bb27411b2dc7804a38
It will be available in the next release (v1.13.0)
