### ISSUE TITLE
npm i @quasar/extras is not in the npm registry.

### ISSUE THREAD

**Issue by LeoWangJ** [quasarframework/quasar#7576]
**Describe the bug**
@quasar/extras is not in the npm registry.
> npm i @quasar/extras

![截圖 2020-08-06 下午6 17 17](https://user-images.githubusercontent.com/17901443/89520853-106f6180-d811-11ea-82ee-20bc8d471a6b.png)

version:
node: v12.13.1
npm: v6.13.1

**Comment by pdanpdan** [comment]
Please check the status of npm registry

**Comment by hawkeye64** [comment]
@LeoWangJ This is happening more and more. Not just Quasar packages, but any. It is caused by NPM doing maintenance, of which they have been doing a lot since Github took over. Expect more of this to happen. When it does, try again at a later time.
