### ISSUE TITLE
QExpansionItem scrolls up when changing selected option in accordion mode on Chromium browsers

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#7577]
**Describe the bug**
When using QExpansionItem on Chromium-based browsers (both desktop and mobile), if you have the first option selected and then you select the second option (or any other option below the selected one), the page will scroll up.

It doesn't seem intentional behaviour, as there is no scrolling related code into the component and it doesn't happen on Firefox.
I'm on Chromium 84.0.4147.105
Could be a bug of latest Chromium versions? 

**To Reproduce**
1. Go to https://quasar.dev/vue-components/expansion-item#Example--Accordion-mode
1. Click on the second option
1. Notice the page scrolling up a bit

**Expected behavior**
No scrolling

**Platform (please complete the following information):**
OS: Ubuntu/Android
Node: 12.14.0
NPM: 6.13.4
Yarn: 1.22.4
Browsers: Chromium, Chrome, Brave
Android: 10

**Comment by pdanpdan** [comment]
Hmm, in Android Chrome 84.0.4147.105 I cannot reproduce. I'll keep you posted with results on desktop.

**Comment by rstoenescu** [comment]
Nothing that can be done... it's natural browser behavior which seems to change from chrome version to version... It matters a lot of things for this behavior to trigger: how the page is built (the dom structure + its css), ...

**Comment by IlCallo** [comment]
@pdanpdan just checked again on Chrome Android and Brave Android, it doesn't happen on the docs but it does in the "servizi" section of the footer of this site we are building: http://athenia.s3-website.eu-central-1.amazonaws.com/

On Chromium it keeps happening on desktop on the docs too. I'm confused.

**Comment by hawkeye64** [comment]
@IlCallo This also happen in dev tools when stepping through code (everything shifts down one line). It's annoying, but nothing that can be done about it. The dev tools issue started 2-3 Chrome versions ago.

**Comment by IlCallo** [comment]
Well, I guess we can open a bug on Chromium on this, to understand the underlying motivations and causes.
But I agree that probably the result isn't worth the effort

**Comment by pdanpdan** [comment]
It's not a bug. It's the correct behavior. When an element is focused it scrolls into view.

**Comment by IlCallo** [comment]
As far as I can see, the problem is present even when all the elements are already into view and none of them get the focus, that's why I say it's a bug.

**Comment by zhongjiaguo001** [comment]
Simply giving ExpansionItem a vertical margin will trigger scrolling, increasing "margin" by 5px for the example on the official documentation; reproducible
