### ISSUE TITLE
Qeditor @focus doesn't work

### ISSUE THREAD

**Issue by AdagioB** [quasarframework/quasar#7578]
In version 1.12.13 I have noticed that the @focus even is not triggered in the WYSIWYG editor. It worked fine in version 1.0.0

I have the following two Codepen:
https://codepen.io/Adagio_B/pen/vYGEBVq
https://codepen.io/Adagio_B/pen/JjXoPem

The first codepen is version 1.0.0, while the second is 1.12.13. All code is the same

Go to the codepen, click in the editor to get focus, then click somewhere else to blur (seen in the text just below, turning from blue to red), then click in the editor to get focus
I'm expecting the text to change back to blue when getting focus. This works in the codepen version 1.0.0, but not in version 1.12.13

**Platform**
OS: Windows 10
Browsers: Chrome (version 84.0) and Firefox (version 79.0). Both 64 bit

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.13.0.

**Comment by eugenevk** [comment]
Still not working for me. Using quasar 2.11.6

I have a component InputEditor.vue:
```
<q-editor
   :focus="focus"
   ...
```
When I test the value, it says true, but in the UI the focus is not set.
