### ISSUE TITLE
[QDatetime] Initial view when opening datepicker

### ISSUE THREAD

**Issue by Snippo** [quasarframework/quasar#758]
Currently the default view when opening the datetime picker is 'day'. In some cases, it would be useful if the default view is set to 'year' (e.g. when selecting a birth date, to make sure the right year is selected).
Even better would be if it would start with year, then continue with the selection of the month and finally the day of the month.

The 'year' view which you also get by clicking on the year:
![datetime](https://user-images.githubusercontent.com/1881040/28688866-b7a6bb3a-7313-11e7-9c73-10ad5851c364.png)

I am willing to implement this myself, but I am still figuring out how to 'compile' the changes into a running app.

**Comment by spectrolite** [comment]
I would try copying the original component’s folder into my own src and modify that
You then import Datetime from your own /src/Datetime.
No guarantees, but that would be my first approach.
I’m sure when @rstoenescu comes back, he’ll show you how to do a proper setup and PR and all. Or maybe @smolinari or @pdanpdan would know how to guide you.

**Comment by Snippo** [comment]
Thanks, I managed to get it to work.
I am able to open the datepicker in the 'year' view. However, it does not scroll to the current year.
I guess this is achieved by this function inside view (value) {} : 
`      this.$nextTick(() => {
        view.scrollTop = rows * height(view.children[0].children[0]) - height(view) / 2.5
      })
`
But inserting this in data() gives ""TypeError: Cannot read property '0' of undefined"". So I am not sure where the "view" variable originates from.

**Comment by Snippo** [comment]
I pushed a commit to my fork:
https://github.com/Snippo/quasar/commit/763be2f5a890fcc47b19821c100ad2dca6079814

This seems to work fine but maybe there is a better approach.

**Comment by rstoenescu** [comment]
Available in v0.15. Forgot to close this.
