### ISSUE TITLE
Dot is wrong position in Thai language

### ISSUE THREAD

**Issue by thingnoy** [quasarframework/quasar#7586]
<img width="1211" alt="Screen Shot 2020-08-07 at 01 00 42" src="https://user-images.githubusercontent.com/25950077/89566534-8643ef00-d84a-11ea-9d79-05ddc1c43082.png">

// It is now
`daysShort: 'อา._จ._อ._พ._พฤ_.ศ._ส.'.split('_')`

// It should be 
`daysShort: 'อา._จ._อ._พ._พฤ._ศ._ส.'.split('_')`

**Comment by pdanpdan** [comment]
Please make a PR to fix it.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 1.13.0.
Thanks for PRing it!
