### ISSUE TITLE
[Request] The case of week and weekofyear

### ISSUE THREAD

**Issue by spectrolite** [quasarframework/quasar#759]
I decided to post this separately from #640, with a few adjustments for the sake of clarity

according to http://beta.quasar-framework.org/components/handling-js-date.html#Format-for-display
we can format a date using `ww` or simply `w` if you don't need 0-padding to output the week of year.
We can also get it like this `date.getWeekOfYear(anyDay)`

but we have no way to specify a date by year + week

more specifically, **week** is absent from 
```
addToDate()
subtractFromDate()
adjustDate()
```
which all accept already : 

-milliseconds 
-seconds
-minutes
-hours 
-days 
-month 
-year

ok a week is just 7 days so it's not a big issue, but why not add week for added convenience ?

week and weekofyear would be greatly useful in `isSameDate` , which would essentially mean resp. “these 2 days happen less than a week apart” or “..in the same calendar week”, both pretty useful!, and also as units in 
```
getDateDiff
startOfDate
endOfDate
```
knowing which day is the first day of the week is indeed important.

**Comment by spectrolite** [comment]
this gitter excerpt might be useful in better understanding the issue and its pitfalls for users/developers.

Laurent @spectrolite 16:30
there’s 2 things here at play
1 - week as a unit of time (=7days)
2 - week of the year as calendar anchors (like months)   [aka. week of year or calendar year]

John @JCharante 16:32
and you need a third, starting day because the world is divided on starting on saturday/sunday/monday

Laurent @spectrolite 16:34
no need for a third, it’s just a variant on 2.

1 and 2 are two ways to look at the word week
we need the code to support both
atm it supports 1 through the use of 7days, and 2 as an analysis tool (getWeekOfYear), but not to create or manipulate (add, compare etc) date objects.
I say we need more explicit support for week, both as a unit (instead of 7days, to help write clean code) and as calendar weeks (Week of Year), eg. allow to create a date from year + weekofyear.

**Comment by nothingismagick** [comment]
FYI - in Quasar 1.0 there is an App Extension called QCalendar. This approach has been treated there.
https://quasarframework.github.io/app-extension-qcalendar/docs

Because this isn't part of the Material Design spec, it hasn't been included in the core component. I am not sure if this needs to be part of the date plugin...

**Comment by rstoenescu** [comment]
@nothingismagick he is referring to the date utils, not to a component.
