### ISSUE TITLE
upload component add a customized upload function 

### ISSUE THREAD

**Issue by dirkhe1051931999** [quasarframework/quasar#7595]
**Is your feature request related to a problem? Please describe.**
i want use my customized axios upload some file ,but upload component url is required when use removeQueuedFiles api
![image](https://user-images.githubusercontent.com/22389976/89634329-c3a28e00-d8d7-11ea-9efa-6c03ece449dc.png)
![image](https://user-images.githubusercontent.com/22389976/89634356-d0bf7d00-d8d7-11ea-9994-dba857cdd8b5.png)

**Describe the solution you'd like**
add a customized upload function  by use my function 

thanks

**Comment by pdanpdan** [comment]
Hello.
In order to custimize the QUploader use the factory function (https://quasar.dev/vue-components/uploader#Factory-function)
or make your customized implementation (https://quasar.dev/vue-components/uploader#Supporting-other-services)
