### ISSUE TITLE
Browser extension (BEX) CLI mode

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#76]
Please thumbs up on this one if you want it implemented.

**Comment by tmartty** [comment]
& Firefox

**Comment by onexdata** [comment]
I see Quasar is looking like BEX (Browser EXtension) mode will soon be supported. It looks like Chrome is the only browser target though? Is that accurate? And how long is BEX support away time-wise? I saw support for it was announced with Quasar 1.2 in October.

**Comment by rstoenescu** [comment]
@onexdata let's connect on Discord (https://chat.quasar.dev)
-Razvan

**Comment by Nice2Work** [comment]
Hello guys, I love the idea of having the BEX with Quasar, but I was browsing the available extensions for Quasar and did not see it in there, is it still under developing? And are there already samples we can look at and play with? Thanks -- Ronald

**Comment by smolinari** [comment]
@Nice2Work - The BEX mode is waiting for review and merging. Shouldn't be too long before it comes. No samples yet, AFAIK. There is however, our HYS article with an example. 

https://dev.to/quasar/hys-2-have-you-seen-bex-58e1 

Scott

**Comment by webnoob** [comment]
If you're desperate in the mean time, feel free to checkout the review branch as well: https://github.com/quasarframework/quasar/tree/bex-review

**Comment by smakinson** [comment]
Would quasar BEX mode & Chrome kiosk apps (https://support.google.com/chrome/a/answer/3316168?hl=en) be a good combination?

**Comment by webnoob** [comment]
@smakinson Chrome Apps and Chrome Extensions are different beasts so, with the current integration, no.

**Comment by hawkeye64** [comment]
![image](https://user-images.githubusercontent.com/10262924/74256037-04ff0b80-4cb0-11ea-89cb-c180822ef36e.png)
Chrome Apps are being deprecated

**Comment by webnoob** [comment]
Ahh that's changed since November. 
Initially they were just being deprecated for Chrome and keeping for Chrome OS.
Less work then :)

**Comment by hawkeye64** [comment]
@webnoob I like `less work` :)

**Comment by webnoob** [comment]
> Fostering a robust ecosystem of extensions is critical to Chrome's mission and we are committed to providing a useful extension platform for customizing the browsing experience for all users.

That's comforting though!
