### ISSUE TITLE
[Discussion] Quasar for Enterprise?

### ISSUE THREAD

**Issue by sagrawal-idrc** [quasarframework/quasar#7600]
Thanks for building & maintaining such a highly functional framework.

I am a full-stack engineer and am completely sold for using Quasar for a wide variety of projects.

I need to convince a new large "enterprisy" client that Quasar is a good choice for their in-house (web) applications.

I found some sections in documentation which help me in this:

1. Best practices integrated by default
https://quasar.dev/introduction-to-quasar#Best-practices-integrated-by-default
2. Comprehensive security document & policy
https://quasar.dev/security/
https://github.com/quasarframework/quasar/security/policy
3. Good sponsors
https://quasar.dev/sponsors-and-backers

Are there any further arguments which the community can propose which can help me in this? I am pretty sure that others might have thought about this already.

Also, if there a list of companies who are already using Quasar for Enterprise class applications, it will be very helpful.

Thank you for bearing with this non-technical issue, but any inputs will be very helpful for me and in my humble opinion for others in similar situations as well.

**Comment by hawkeye64** [comment]
I use Quasar at Intelliviewtech.com (not the web site, that is wordpress and our marketing team manages that). We make dual-camera devices (DCAM) and the video is analyzed via ML to detect pipeline leaks. The User front-end for these devices is made with Quasar.

**Comment by IlCallo** [comment]
https://youtu.be/6ZKBZ3k4Ebk?t=7153
Here I speak exactly about Enterprise support and what we are doing to enhance that :)
My company, Dreamonkey, does exactly this: we help Enterprises upgrade their software and tech stack, and we sponsor Quasar because we think this can really be The Next Big Thing in this field :P

**Comment by m0jimo** [comment]
I see a big advantage in PWA (no need for store) and Electron (recently testing also Tauri) for needs in our company.

**Comment by sagrawal-idrc** [comment]
Thank you all for your responses. They are very helpful.

Can we keep this issue open for a few more days (or as the moderators deem fit) for further responses?
