### ISSUE TITLE
Remove some limitations on electron-preload.js 

### ISSUE THREAD

**Issue by newCodeRunner** [quasarframework/quasar#7601]
**Is your feature request related to a problem? Please describe.**
I think we can easily remove the following limitations associated with preload scripts
(mentioned on https://quasar.dev/quasar-cli/developing-electron-apps/electron-preload-script)
1. This file is not transpiled by Babel.
2. You cannot import files with a relative path from it, as it is copied as-is into the final app bundle.

**Describe the solution you'd like**
1. Instead of just 1 preload file (which is not suitable for multi-window apps, where each can require a separate preload), we can add a preloads folder, such that the ./src-electron folder looks like
```
 --./src-electron
       -icons
       -main-process
       -preloads
```

2. Then before the electron webpack config is handled by Quasar, it should run something like the following code:
```
// for preloads
fs.readdir('./src-electron/preloads/', (err, files) => {
    if (err) throw err;
    else {
      files = files.filter((i) => i.indexOf('.js') > -1);
      if (files.length > 0) {
          resolve({ preloads: files });   // Get hold of the preload entry files here
       }
    }
  });
``` 

3. Then in webpack electron config, it should automatically add these entry points to the config like: 
```
const path = require('path');

preloads.forEach((file) => {
          const fileName = `${file.replace('.js', '')}`;
          cfg.entry[fileName] = [
            path.resolve(path.join(__dirname, `./src-electron/preloads/${file}`)),
            // each preload gets a separate entry point - handles the relative paths as well 
          ];
        });

cfg.output.filename = '[name].js';
``` 

4. Then in electron main process, we can update the creating BrowserWindow code like below:
```
import { resolve } from 'path';

const mainWindow = new BrowserWindow({
    webPreferences: {
      // More info: /quasar-cli/developing-electron-apps/electron-preload-script
      preload: resolve(`${process.env.PROD ? __dirname : './.quasar/electron'}/mainWindow-preload.js`),
      // where "mainWindow-preload.js" is a file present in ./src-electron/preloads folder
    },
});
```

**Describe alternatives you've considered**
I have tested the above solution by manually adding the read directory hooks and updating the electron webpack config in quasar.config.js, and it works perfectly.

**Additional context**
If you agree with this approach, I will be more than happy to create a PR for this issue.

**Comment by IlCallo** [comment]
Hey @newCodeRunner, go on and give it a try!
Please make a PR for every concern and make them purely additive: separate the "provide transpilation capabilities" from the "allow to use multiple files with relative paths" and make the latter compatible with current usage.

Also remember to upgrade docs in every PR :)

**Comment by yusufkandemir** [comment]
All limitations are resolved in Quasar v2, it even has TS support now 🎉 But, we don't have support for multiple preload files.

**Comment by ghost** [comment]
Closing this, since, I have switched to Svelte
