### ISSUE TITLE
[docs] Animations page should mention migrating from 3.X of animate.css to 4.

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7602]
Since Quasar's Animations is mainly borrowed from **animated.css** which has a breaking change:
Starting from version 4, all CSS classes need to be prefixed with `animate__ `  

Although they also provide the "animate.compat.css" version, I think the migration should be mentioned in the Animations Page of the Quasar.

ref: [Migration from v3.x and under](https://animate.style/#migration)

**Comment by pdanpdan** [comment]
Hello. I'm trying to understand what your request means, but I cannot.
Can you please explain what you want and why? Thank you.

**Comment by kevin61416** [comment]
This is the quasar's [animations page](https://quasar.dev/options/animations#Installation).  

How to import [Animate.css](https://animate.style/) **v4** is demonstrated in the **Install** section:
<img src="https://i.imgur.com/0e6SCVQ.png" />
  

However, all the examples in **Usage** section have the syntax of Animate.css **v3**:
<img src="https://i.imgur.com/KEPOOpT.png" style="width: 100px" />
  
The main problem is that the examples are missing the prefix `animate__ ` introduced in the Animate.css v4, It should be recommended to either mention that or use the [compact version](https://animate.style/#migration).

**Comment by pdanpdan** [comment]
Aha, I got it - can you please PR for this - but please mention that the prefix should only be used if importing directly from animate.css.

**Comment by kevin61416** [comment]
No problem, I will do it these few days, I appreciate your hard work. 🥰
