### ISSUE TITLE
"Blurhash" support for q-img component

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#7605]
**Is your feature request related to a problem? Please describe.**
Loading of large images takes time --> spinners or a black background dosent look to good.

**Describe the solution you'd like**
It would be great, in addition to the spinner and placeholder image, for the **q-img** component to also support something like blurhash [https://blurha.sh/](url) (displaying a blurry image based on a hash). There is also a vue component that implements this, but compared to quasars **q-img** component it is lacking alot of other features.

**Describe alternatives you've considered**
* I have also considered a simple spinner, which dosent look to great. 

* The placeholder option is a nice alternative for something like a "blur up" effect, but the disadvatage would be that one has to store the same image twice (original size and small size). More on the "blur up" method can be found here [https://css-tricks.com/the-blur-up-technique-for-loading-background-images/](url)

**Additional context**
IMO this would be a nice third option for the q-img component to render a blurry image while the original sized images load in.

I am always open for other solutions that would achive the same effect without to much redundent saving of images :)

**Comment by pdanpdan** [comment]
you can already do that - use whatever you want to generate the placeholder image
we will not include that algorithm from blurha.sh, but if you need to use it it should be simple
btw, that is only a non generic compression method, so you still encode your image twice

https://codepen.io/pdanpdan/pen/mdPJxxJ?editors=1010 (just a standard placeholder for ref)
