### ISSUE TITLE
Infinite Scroll non-stop loading in tab panel

### ISSUE THREAD

**Issue by kapchew** [quasarframework/quasar#7609]
**Describe the bug**
When infinite scroll is placed inside a tab panel, the loading will not stop

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/kapchew/pen/RwaWaYY

**To Reproduce**
Just run the codepen, the result will show non-stop loading

**Expected behavior**
It should behave the same as when it is without a tab panel

**Screenshots**
Refer to the codepen project

**Platform (please complete the following information):**
OS: Mac Mojave
Browsers: Safari and Chrome

**Comment by pdanpdan** [comment]
It is working the same way. You have not set a height.

**Comment by kapchew** [comment]
If I simply remove the tab panels, and without setting height, it works properly. Can you check the same codepen project again? This time the tab panels are commented out, and there is still no explicit height.

https://codepen.io/kapchew/pen/RwaWaYY

**Comment by pdanpdan** [comment]
If you want to scroll based on the body scroll add `scroll-target="body"` to QInfiniteScroll

**Comment by kapchew** [comment]
I see. Thanks.
