### ISSUE TITLE
Quasar plugin to handle file storage on Cordova and Electron platforms.

### ISSUE THREAD

**Issue by davidhooey** [quasarframework/quasar#7611]
**Is your feature request related to a problem? Please describe.**
I currently have a Cordova app which uses the cordova file plugin to store files on iOS and Android. I would like to be able to port the application to Quasar and have Quasar handle the file storage APIs from Cordova and Electron.

**Describe the solution you'd like**
It would be great to have a Quasar plugin that will handle the file storage at a higher level to support Cordova and Electron. 

**Describe alternatives you've considered**
Include individual Cordova and Electron file storage code.

**Comment by pdanpdan** [comment]
Hello. The 2 are very different and specific to the implementation. Also they are not working on normal web environment. Sorry
