### ISSUE TITLE
PLEASE can we have google maps and mapbox integration for Quasar?

### ISSUE THREAD

**Issue by creativemacmac** [quasarframework/quasar#7620]
**Is your feature request related to a problem? Please describe.**
The quasar dev page is a true delight, but no maps which is a problem because virtually every website now a days has a map to show directions to a business

**Describe the solution you'd like**
I would love to have the ability to use both google maps and mapbox in my quasar apps
**Describe alternatives you've considered**

considering using the vue cli

**Additional context**
thanks guys for making Quasar it's phenomenal :)

**Comment by pdanpdan** [comment]
Yes. There are at least a few connectors for vue.

**Comment by creativemacmac** [comment]
could you possibly direct me in the direction of some that work with quasar? :)

**Comment by pdanpdan** [comment]
Any that works with Vue 2 works with Quasar.

**Comment by creativemacmac** [comment]
thanks 👍
