### ISSUE TITLE
Wrong Q-select baseline align, if there is blank value

### ISSUE THREAD

**Issue by FragsterAt** [quasarframework/quasar#7623]
**Describe the bug**
Wrong Q-select baseline align, if there is blank value

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/gdh6cr9e/30/

**To Reproduce**
1. Go to fiddle
2. See the bug %) (pay attention: blank q-input is fine)
3. Select value in "blank" q-select
4. See all text on one line
5. Clear any input
6. See the bug again

**Expected behavior**
all inputs and text on one line

**Screenshots**
https://imgur.com/1MKrDEm

**Platform (please complete the following information):**
Browsers: Firefox, chrome, edge

**Additional context**
blank q-input is fine.
In some cases workaround is class="self-start"

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
