### ISSUE TITLE
QTable & VirtualScroll: Add a new argument to control the loading strategy of VScroll

### ISSUE THREAD

**Issue by kevin61416** [quasarframework/quasar#7624]
**Is your feature request related to a problem? Please describe.**
Assume `:virtual-scroll-slice-size="90"`, the current loading strategy is like this:
<img src="https://i.imgur.com/I3M6jy2.jpg" alt="quasar current strategy">

Its effect is: divide the slice size into two halves (45), the upper half is the **invisible part (blue, 45 items)**, the lower half contains the current **table/list (yellow, maybe 30 items)** and the **invisible part (pink, 15 items)**.  

Under normal circumstances, this is not a problem, but for big data tables, this indirectly causes scrolling to become quite delayed.

Current strategy does not fit the general user's usage scenario: **continuous scrolling down**. There should be more items in the upper half that can be recycled for use in the lower half, like this:
<img src="https://i.imgur.com/CP3CmFY.png" alt="new vscroll strategy" />

**Describe the solution you'd like**
Provide a new option (e.g., `:virtual-scroll-top-ratio` or `:virtual-scroll-top-tolerance`) to control the ratio of loading items.

For example, when `:virtual-scroll-slice-size="90"`, if `:virtual-scroll-top-ratio` is set to 20 (in percentage):
<img  src="https://i.imgur.com/L96xYCK.png" alt="virtual-scroll-top-ratio example" />

**Describe alternatives you've considered**
In my case, I need to load a lot of log data. When I scroll quickly, I will continue to see the loading placeholder 😟. However, increasing the `slice size` is not a good choice for me, because the data objects are complex and need to be modified (`Object.freeze` cannot be used). Increasing slice size will increase the loading delay time greatly.

At this time, if I can recycle the excessively loaded items in the **upper half (blue)** and use it in the **lower half (pink)**, it will perfectly solve my problem.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.14.7.
