### ISSUE TITLE
q-input programmatic assignment does not work since version 1.10.0

### ISSUE THREAD

**Issue by antux** [quasarframework/quasar#7627]
**Description**
I am using the watch to validate if the input value completes the numeric condition, if not I assign the previous value to the v-model property, but the value is not rendered, the data binding does not work. Until version 1.9.16 it works, but from then on not.

Important observation, if a slot is added to it, the behavior is as expected.

Also I did the test with a standard input and it works.

Is there a condition, configuration or new standard in quasar or is this a bug?

**https://codepen.io/antux/pen/KKzVrZz**

**Expected behavior**
if the condition is not met, the previous value of the watch should be shown in the input

**Screenshots**

**Platform (please complete the following information):**
OS: Manjaro
Node: 12.15.0
NPM: 6.13.4
Yarn: 1.22.4
Browsers: Firefox 78.0.2
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Hello, this is related to #7573

When you change the value inside the watch you are doing so in the same tick as the original change - make the revert change in a nextTick.

The reason the native input works here is that being a native element it is re-drawn, and on redraw the current value is used.
But in the case of components a change in the value is required to update.

**Comment by antux** [comment]
Thanks for answering.

@pdanpdan  Just out of curiosity, can you tell me why the change from v1.9.16 to v1.10.x was due, because before the components were rendered when changing their value without using nextTick, at least the q-input, was it to optimize?

**Comment by pdanpdan** [comment]
It is related to this: 8ec188b67dc30b1a6a01fd218db25681c2e23c30
When the components were forwarding events and had listeners attached on them they would re-render every time.
Once that was fixed the components would work as expected by communicating through props (and not fully re-rendering) - and now the explanation on top kicks in :)

**Comment by antux** [comment]
I understand, great.

Great job.
