### ISSUE TITLE
About Alert and Toast!

### ISSUE THREAD

**Issue by Bangood** [quasarframework/quasar#763]
hello, i use quasar beta 0.14.0

I neede a component(Toast, Alert in Quasar) whic can display on the top of screen and disappear 
automatically after some seconds.

But now, the Toast in quasar can't set position which meets my automatic vanishing need,
the Alert in quasar can't set timeout property which meets my displaying on the top of screen need.

How can i do to meet my needs.

**Comment by jonafrankbrimma** [comment]
You can change the css for the toast in App.vue .... fairly simple to do so 👍 
position : fixed and top : 0

**Comment by Bangood** [comment]
@jonafrankbrimma I have meet my need by your help, but the animation experience is not very good.
Has a easy way to use the animation in Toast like Alert?

**Comment by rstoenescu** [comment]
Will enhance Toast.
