### ISSUE TITLE
quasar serve --history still displays '#' in page URL (vueRouterMode set to 'history')

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/quasar#7631]
**Describe the bug**
```vueRouterMode: 'history'``` not removing the '#' symbol from the URL when running ```quasar serve --history```

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
configure the history mode in the quasar.conf.js under build: { vueRouterMode: 'history',... }

1) build quasar application ```quasar build```
2) navigated to dist/spa
3) run ```quasar serve --history```
4) open http://localhost:4000/#
5) url is still displayed with a hash

**Expected behavior**
Actual history mode without the '#'

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.13.0
NPM: 6.12.0
Yarn: N/A
Browsers: Chrome / Firefox
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

Not sure if I missed something configuring the history mode but as far as reading how to configure quasar.conf here

https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build

and reading how to serve the quasar application after building it here

https://quasar.dev/quasar-cli/commands-list#Serve

I think I set up everything correctly.

**Comment by pdanpdan** [comment]
Why would vue-router modify your desired URL? Also I hope you are aware what the hash part of the URL is.

**Comment by Quasarman** [comment]
Hi @pdanpdan,

if I am correct the hash part of the URL is so that, since we are dealing with a SPA, the page does not get reloaded when navigating the page e.g. changing the route from '/home' to '/users'.

But when configuring the serverside correctly, to always return the index.html file, it should be possible to use "normal" url representation e.g. without the leading hash.

This is basically what I was asking. I configured the vueRouterMode to be 'history' in the quasar.conf.js file and run the built application with ```quasar serve --history```. I expected the url not to start wirh the leadin # but it still did. So when navigating my app i would always see 'localhost:4000/#/home' or 'localhost:4000/#/users' in the browsers search bar. But I want it to be just localhost:4000/home when serving with ```quasar serve --history```.

I am not sure if I need to configure anything else, since IMO i did everything as stated in the quasar docs I have linked in the ticket.

Maybe you can guide me in the right direction to achive this. Thanks in advance.

**Comment by pdanpdan** [comment]
Why do you open the url with the hash?

**Comment by rstoenescu** [comment]
Hi @Quasarman . Your app is served correctly, however you initially access the URL with a hash which is maintained while navigating (basic browser stuff). Type the address without the hash and you'll be fine.

**Comment by Quasarman** [comment]
Hello @pdanpdan and @rstoenescu 
Thanks for the reply's I am not purposely setting the # in the URL in the browser. When I type localhost:4000 in the browsers search bar the '/#/' is automatically appended.

I had another look at my configurations, and for some reason, my routes/index.html file was missing the ```mode: process.env.VUE_ROUTER_MODE,``` prop in the VueRouter config...maybe I missed something along the way while upgrading quasar i dont know. Anyways I added it back and everything works fine now!

Thanks for the help.

**Comment by disarticulate** [comment]
Just leaving a note for anyone running into this error for Quasar v2 using vite:
- index.js for the router now uses the key ```history:``` and is set by the ```process.env.VUE_ROUTER_BASE``` flag which comes from ```quasar.config.js > build > vueRouderMode```
- However, you can override this accidently by modifying the ```build > extendViteConf(viteConf) > viteConf.define```

Solution ```Object.assign(viteConf.define, { yourEnvVar: JSON.stringify("here") })```

There's some other .dotenv reading here: https://quasar.dev/quasar-cli-vite/handling-process-env#introduction for more complicated vite setups
