### ISSUE TITLE
button with icon and text not centered

### ISSUE THREAD

**Issue by Manubi** [quasarframework/quasar#7636]
Hey,
![Dialog___Quasar_Framework](https://user-images.githubusercontent.com/20935138/90394200-820da200-e092-11ea-9603-423315123aa5.png)
as you can see from the documentation, the icon is not vertically centered.

**Comment by pdanpdan** [comment]
Hey,
As we cannot see from the screenshot is the browser and os :)
And we can also not see where is the page you took the screenshot from.
Also from the screenshot it looks like the text is not centered.
Please help us with relevant info.

**Comment by Manubi** [comment]
Hey,
it's indeed the browser. Firefox 80.0b8 (64-bit) Dev Edition.
Link in Doku: https://quasar.dev/vue-components/button#With-icon
Thanks!

**Comment by pdanpdan** [comment]
It looks like firefox is not good with subpixel alignment.
You can solve it by setting in your `quasar.variables.sass`

```sass
$button-line-height : 1.714em
```

But I don't think we can change it by default because it would break layout for existing users.

**Comment by Ezbaze** [comment]
I get the same thing using "Version 122.0.6261.112 (Official Build) (64-bit)", the text isn't centered with or without an icon
![image](https://github.com/quasarframework/quasar/assets/68749104/495a9a5b-7037-46e2-91f5-55f0c28faeeb)
From https://quasar.dev/vue-components/button#standard

![image](https://github.com/quasarframework/quasar/assets/68749104/d2b33ac4-7ae9-4b15-abcc-01d2fa59a5af)
From https://quasar.dev/vue-components/button#with-icon

They are both 1px too high :')
