### ISSUE TITLE
iOS dev doesn't seem to be working with https

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#7637]
Hi awesome team,
For some reason the self signed certificate cannot be used when launching:
quasar d -m ios

quasar.conf:
    devServer: {
      https: true,
      port: 8081,
      open: true // opens browser window automatically
    }

if that is a emulator, the page is blank:
<img width="439" alt="Screen Shot 2020-08-18 at 8 08 45 AM" src="https://user-images.githubusercontent.com/26779040/90439922-7ec5f500-e12a-11ea-9e12-6379f5ba3f37.png">

The same blank page is happening on the actual device as well.

OS: MacOS 10.15.6 (Catalina)
Node: 12.18.3
NPM: 6.14.6
iOS: 7, 8 (tested)
I've created a new quasar project with `quasar create` to test that in the clean environment.

Could you please check that when you have a time?

Cheers!

**Comment by rstoenescu** [comment]
Hi,

iOS 7 & 8 is very old (and has negligible marketshare nowadays).
Also, can you post the console output of "quasar info"?

**Comment by pikil** [comment]
Hi Razvan,
I also tested on iOS 13 as well, that gives the same output. Sorry, shouldn't have been mentioned such old versions in the first place :)

Please see below,
$quasar info

Operating System - Darwin(19.6.0) - darwin/x64
NodeJs - 12.18.3

Global packages
  NPM - 6.14.6
  yarn - Not installed
  @quasar/cli - 1.1.0
  cordova - 10.0.0

Important local packages
  quasar - 1.12.13 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.0.6 -- Quasar Framework local CLI
  @quasar/extras - 1.9.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - 9.2.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.11.1 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.9.5 -- TypeScript is a language for application scale JavaScript development

Quasar App Extensions
  *None installed*

**Comment by rstoenescu** [comment]
Found the culprit. Capacitor packages changed the location of the bridge file.
Fix will be available in "@quasar/app" v2.1.5.

**Comment by pikil** [comment]
Awesome! You rock!

Thank you Razvan!
