### ISSUE TITLE
QCarousel hide arrow on first/last slide

### ISSUE THREAD

**Issue by 54mu3l** [quasarframework/quasar#7639]
I would like to hide the left arrow on the first slide and the right arrow on the last slide (+ no arrows if there is only 1 slide).

Would be great to see a new prop added to QCarousel. E.g. `auto-hide-arrows`.

I also considered to hide/show them by implementing some css/js logic myself. But it would be way more tidier with a prop out of the box.

Thank you!

--
Just by the way: also it would be fun to only show the arrows on hover... (maybe another new prop?) ;)

**Comment by rstoenescu** [comment]
Hi,

Forgot to close this. It is available in Quasar v1.13

**Comment by 54mu3l** [comment]
why can't I find it in the release notes?

**Comment by rstoenescu** [comment]
My mistake. Knew I implemented this, but it's in v1.13.2 (unreleased yet).
