### ISSUE TITLE
Request build mode with development settings

### ISSUE THREAD

**Issue by kastork** [quasarframework/quasar#7641]
I've looked at docs and code pretty hard, but I can't seem to find a way to just build the SPA in development mode.
There's got to be a straightforward way to do this, so I'm guessing it is just an oversight in the documentation.

I would have expected `quasar build -d` to do this, but a build done this way does not seem to create artifacts that the vue developer tools in Chrome or Firefox can recognize as development builds.

**Comment by pdanpdan** [comment]
Hello. What do you mean by build in development mode?

**Comment by kastork** [comment]
When you do `quasar build` (regardless of the flags you set), the NODE_ENV is forced into `production` by the CLI.  I'm trying to set NODE_ENV be `development`.

Like `quasar dev`, except make a build that does into `dist/spa` instead of just running the dev server.

**Comment by kastork** [comment]
Here's the scenario....

I have a back end server that is not implemented in node, it serves the SPA.

I want to have the ability to do something like

`quasar build -d --watch` which simply creates a development build into `dist/spa` whenever something changes so when the back end serves the app it is up to date.

This isn't as convenient as the dev server with its nice hot module reloading, but it is useful in cases where the back end is serving multiple SPA's or doing redirection based security.  Or, say, you have a CI/CD pipeline that deploys the whole thing into a test environment and you want to use vue dev tools when testing in that environment.

**Comment by pdanpdan** [comment]
Please change the name in something like "Request build mode with development settings" so we can track it. Thank you.

**Comment by kastork** [comment]
Just curious if this has made it onto a roadmap or anything.
Thanks

**Comment by hawkeye64** [comment]
I guess `quasar build --debug` doesn't do it?

**Comment by kastork** [comment]
@hawkeye64 Yes it seems to.  It didn't when I filed this issue almost a year ago.
I'll close the ticket.
