### ISSUE TITLE
QEditor (WYSIWYG) param not processing function (but docs says it accepts function)

### ISSUE THREAD

**Issue by rulrok** [quasarframework/quasar#7642]
**Describe the bug**
As of version 1.12.13 the docs says that `cmd` accepts `param` which could be either a `string` or `function`.
![image](https://user-images.githubusercontent.com/3097987/90545757-82c03a00-e15f-11ea-8567-883fd2172a48.png)

But for what I could check, the code does not treat it.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/rulrok/1ryse54d/4/

**To Reproduce**

1. Put the cursor somewhere on the editor
2. Click um 'Custom' command on toolbar

**Expected behavior**
The returned value from the function would be used as the param, but instead, the whole function definition is being used as the param.

**Screenshots**

**Platform (please complete the following information):**
OS: Linux
Node: 14.7.0
NPM: 6.14.7
Yarn: ---
Browsers: Chrome
iOS: ---
Android: ---
Electron: ---

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

We apologize, but it is an ancient mistake in the API file. Hasn't changed in 1.12.13 (but been like this since we added the API cards), but regardless: "param" was always a String only.
