### ISSUE TITLE
iOS 11 dont support rest parameters

### ISSUE THREAD

**Issue by baryon** [quasarframework/quasar#7643]
**Describe the bug**
I am making a project for iOS and android, 
it dont work on iOS 11 but working iOS 12, iOS13

I found because iOS 11 dont support rest parameters 
https://kangax.github.io/compat-table/es6/

**To Reproduce**
make a project with capacitor
then write some code using rest parameters 
run it on iOS11 simulation

**Expected behavior**

Works.

**Platform (please complete the following information):**
OS:  Mac OS 10.15.6
Node: 12
NPM:
Yarn:
Browsers: 
iOS: 11
Android:
Electron:

**Additional context**

If I add plugins: ['@babel/plugin-proposal-object-rest-spread'] in babel.config.js, it works.
Would you add the plugin in quasar/babel-preset-app

**Comment by pdanpdan** [comment]
Hello. What version of @quasar/app do you use? What do you have written in package.json in the browsers list?

**Comment by baryon** [comment]
Here
```
"@quasar/app": "^2.0.6",
```

```
"browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ]
```

**Comment by rstoenescu** [comment]
There seems to be a bug in browserlist logic. Will report it to them.
But anyway, until then, there's nothing wrong in adding something to the babel.config.js.
