### ISSUE TITLE
openURL dont works on iOS13

### ISSUE THREAD

**Issue by baryon** [quasarframework/quasar#7644]
**Describe the bug**

I found sometimes, the openURL dont works on iOS13, if the url include a query param.
I found a issue at 
https://github.com/ionic-team/capacitor/issues/2713#issuecomment-616526918

**To Reproduce**

Maker a project with capacitor supporting
use quasar openURL to open a link example: https://www.example.com/order?order_id=1234567890
it dont works on iOS13, a reject callback raised.

but it works on android

**Expected behavior**

launch safari and open link

**Screenshots**

**Platform (please complete the following information):**
OS: MacOS 10.15.6
Node: 12
NPM:
Yarn:
Browsers:
iOS: 13
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

What Quasar mode are you building with?

**Comment by baryon** [comment]
```
 Dev mode.......... capacitor
 Pkg quasar........ v1.12.13
 Pkg @quasar/app... v2.0.6
 Debugging......... enabled
 Running mode...... IDE (manual)

 Configured browser support (at least 84.55% of global marketshare):
 · Chrome for Android >= 81
 · Firefox for Android >= 68
 · Android >= 81
 · Chrome >= 73
 · Edge >= 79
 · Firefox >= 67
 · iOS >= 10.0-10.2
 · Opera >= 64
 · Safari >= 10.1

```

**Comment by arnoldtkl** [comment]
Please try go to iOS Settings -> Safari -> off Block Pop-ups

**Comment by rstoenescu** [comment]
Sorry, but unfortunately, there's nothing that we can do if the browser (through the OS) rejects our API call. :(
