### ISSUE TITLE
Editor WYSISWYG doesn't refresh when tags are changed

### ISSUE THREAD

**Issue by AdagioB** [quasarframework/quasar#7647]
**Describe the bug**
When changing tags (e.g. removing bold, adding italics) inside a method called from computed get/set methods, this will not be shown in the editor

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Adagio_B/pen/RwaGGEX?editors=1011

**To Reproduce**
1. Go to above mentioned codepen (notice at the start the following is sent to the editor: `"The <b>bold</b> bacon!"`, which is correctly shown 
2. Show the console to see what is sent back to the editor
3. Write anything at the end of the text in the editor to trigger a change
4. The console shows this is sent back to editor: `"The bold <i>bacon</i>! <br>"` (after adding extra space)

**Expected behavior**
I would expect the editor would show the following:
The bold _bacon_! 
But instead it shows this:
The **bold** bacon! 

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Firefox and Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.13.2.
