### ISSUE TITLE
Side Panel, bug?

### ISSUE THREAD

**Issue by johncloud200** [quasarframework/quasar#765]
http://beta.quasar-framework.org/quasar-play/android/index.html#/showcase/layout/play-with-layout

- open with mobile device(I use android+chrome)
- open left/right panel
- press back physic button
- yes panel goes hidden, but the main content can't scrolling

**Comment by rstoenescu** [comment]
Will investigate. Thx for reporting

**Comment by rstoenescu** [comment]
I believe this is fixed in latest v0.14.
