### ISSUE TITLE
ResizeObserver loop limit exceeded (Issue #2233 closed to early)

### ISSUE THREAD

**Issue by 54mu3l** [quasarframework/quasar#7656]
I'm referencing the issue https://github.com/quasarframework/quasar/issues/2233 here becaused it was closed without a proper solution.

Please reopen the Issue #2233 again. You can read everything there.

Thank you.

**Comment by marcorivm** [comment]
This has been happening a lot more recently, many projects that were doing just fine on sentry base plan, went over their limit like crazy this last month

**Comment by pdanpdan** [comment]
ResizeObserver only emits an event. if you do something based on that event that triggers a resize you should ignore the next events. it's not related to the component.
