### ISSUE TITLE
[request] support long names and short names for QDateTime

### ISSUE THREAD

**Issue by anhnhoktvn** [quasarframework/quasar#766]
It would be great if QDateTime support for customizing long and short month names and day names. 

Ex: 
Long name: January
Short name: Jan

**Comment by rstoenescu** [comment]
It's already in v0.14 as monthNames and dayNames props. Please reopen if you think something can still be improved. Thx.

**Comment by anhnhoktvn** [comment]
Hi currently we only have monthNames, dayNames.
And it can not be customize for 2 forms: Long name and short name.
In others langues, short name may not be the first 3 characters of long name. 
For example, in Vietnamese: 
January is Tháng 1
February is Tháng 2
When it's showed in short name, it's always 'Thá', which is not correct.
You can see the image below:
[Image](http://i.imgur.com/zX7f2rPl.png)

**Comment by anhnhoktvn** [comment]
ref: https://github.com/chmln/flatpickr/blob/master/dist/l10n/vn.js

**Comment by rstoenescu** [comment]
Insee your point. Will add short names.

**Comment by anhnhoktvn** [comment]
bump!

**Comment by rstoenescu** [comment]
Hi, This has been implemented in v0.15 through the i18n, so closing this.
