### ISSUE TITLE
[Capacitor] TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#7662]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5028905/90962433-2edf8900-e4b0-11ea-8f4f-973108401897.png)

This happens the second time when I build the app. It seems something goes wrong with the rebuild command?

The only workaround is to remove the `src-capacitor` and start over.

**Codepen/jsFiddle/Codesandbox (required)**
Codepen is going to be difficult for mobile. It does work fine when simple running it from a browser (SPA).

**To Reproduce**
1. `cd project/src-capacitor`
2. `quasar build -m capacitor -T android --ide`
3. Install apk to device

The APK doesn't install at all when running without `--ide`. Also it doesn't open Android Studio, I need to open it manually.

**Expected behavior**
Build without the vendor error.

**Screenshots**
See Describe the bug

**Platform (please complete the following information):**
OS: Arch Linux
Node: `v14.8.0`
NPM: `6.14.7`
Yarn: N/A
Browsers: Brave
iOS: N/A
Android: S9 - Android 10
Electron: N/A

**Additional context**
No build errors, only when running.

**Comment by rstoenescu** [comment]
Hi,

1. js/24.js is a devland chunk. That's the place where the error is reported.
2. Android Studio is opened only if its executable is part of your PATH, otherwise there's no way that Quasar can detect where it actually lies.
3. Doesn't makes any sense for a rebuild to break something.

Can you try to "quasar build -m capacitor -d" (-d is for debug) and check the log again to see where the error actually happens pls? If error is not from devland (don't think so by looking at the reported chunk) then is it possible for you to offer a reproducing repo (or upload a zip here -- without node_modules in it)?

**Comment by francoism90** [comment]
@rstoenescu Thanks for your reply.

This is the output of the build command including `-d`: https://gist.github.com/francoism90/bf9309401f8becf3a87de6aad586764b

My repo: https://github.com/francoism90/mediadb-ui/tree/feat-capacitor

I'm now getting more info from the console:

![image](https://user-images.githubusercontent.com/5028905/91017836-07dba100-e5ef-11ea-95e4-90184b66312b.png)

I don't get console errors when running it in a browser (quasar dev/quasar build).

Thanks.

**Comment by francoism90** [comment]
I managed to solve the issue and it was indeed my own fault. :+1: 

First I did incorrect API-response message failure handling: `e.response.data.message`
The object doesn't exists when the API call fails/timeouts/etc. In this case an invalid API URL was given.

When I want to make calls to my REST API on an Android emulator, I need to use my local IP address as `API_URL`, e.g. `API_URL=http://192.168.1.100:8000/api/v1`

When I'm deploying my app to my phone, the SSL certificate is incorrect and that blocks the API-call as well. So I need to generate an user trusted certificate for this as well.

Thanks for looking in to the issue, it's my first experience developing mobile apps, hope it helps others as well. :)

**Comment by francoism90** [comment]
@rstoenescu Just one final question: do you need to keep the android folder: https://github.com/francoism90/mediadb-ui/tree/feat-capacitor/src-capacitor

Cordova looks a lot better: https://github.com/francoism90/mediadb-ui/tree/feat-capacitor/src-cordova

**Comment by rstoenescu** [comment]
Yes, you need it. It's the actual native app that wraps everything for Android. When building for iOS, an ios folder will also appear there. Same goes for Cordova too. But you first need to dev/build for that platform in order for those folders to show up. I recommend sticking with Capacitor for a whole lot of reasons.

**Comment by francoism90** [comment]
@rstoenescu Thanks for the information. :)

So far my experience with Capacitor have been mixed. It doesn't seem to allow external API calls, even when setting the correct URL's in `allowNavigation` as server option. It also seems to cause some weird rendering issues when actually deploying the app to my device. Cordova works fine, however if I'm not mistaken Capacitor should be a better alternative as it is open-source?
