### ISSUE TITLE
Can't install icongenie

### ISSUE THREAD

**Issue by tuanpn** [quasarframework/quasar#7669]
Please help me
I can't install icongenie on MacOS
It show error like this:

ERR! sharp EACCES: permission denied, mkdir '/Users/thomas/.npm/_libvips'
info sharp Are you trying to install as a root or sudo user? Try again with the --unsafe-perm flag
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/thomas/Library/Caches/node-gyp/12.18.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/.node-gyp'
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.25.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2020-08-23T18_10_07_645Z-debug.log

Thanks in advance

**Comment by rstoenescu** [comment]
Hi,

We have [chat](https://chat.quasar.dev) or the [forum](https://forum.quasar.dev) for questions and quick help. We'd appreciate if this is used instead of logging a ticket here on Github.

Your problem is that you do not have permissions to write in the ~/.npm folder... you've probably installed something with the root account. So just prepend "sudo" to your install command or change the folder/file permissions on ~/.npm to accomodate your username.
