### ISSUE TITLE
Modal button hover causes background flicker

### ISSUE THREAD

**Issue by tobiasdierich** [quasarframework/quasar#767]
### Software version

Quasar: v0.14-beta
OS: macOs Sierra, Arch Linux
Node: 8.2.1
NPM: 5.3.1
Browsers: Chrome (Version 60.0.3112.78), Chromium

### What did you get as the error?

Hovering a button inside a modal causes the whole background to flicker. Demo video: 

![quasar](https://user-images.githubusercontent.com/20173900/28821836-4bac07ee-76b7-11e7-9ef4-e0f0a81e4332.gif)

### What were you expecting?

Hovering the button should not affect the whole background.

### What steps did you take, to get the error?

Visit the Quasar Play App modal example ([here](http://beta.quasar-framework.org/quasar-play/android/index.html#/showcase/popups/modal)). Open any modal and hover the button.

Bug does not occur in Firefox and Safari.

**Comment by pdanpdan** [comment]
Can you please check if you don't have some sort of auto-brightness feature on your monitor?

**Comment by spectrolite** [comment]
I doubt that’s the problem, it does not flicker in other browsers, and the modal itself does not seem affected (it’s mostly white, so that may be my eyes tricking me), imho it’s most probably not display-wide.

There’s definitely something wrong with QBtn + QModal, I also have an issue with button click affecting Modal content with a glitch.

**Comment by tobiasdierich** [comment]
Tested it on 3 different monitors and got the same result. Also, if auto-brightness causes the flickering, it should not be visible in the video.

Furthermore, as already mentioned, the modal content itself is not affected by the flickering:

![ezgif-3-4db0506f45](https://user-images.githubusercontent.com/20173900/28874482-4e10f504-7792-11e7-8bb7-aa7de85f5228.gif)

The v0.13 modals are not affected by the flickering.

**Comment by pdanpdan** [comment]
The problem is I cannot reproduce, and I checked the css and nothing seems to change.

**Comment by tobiasdierich** [comment]
I just checked with my Windows machine connected to the same monitor. Weirdly, Windows+Chrome seem to not be affected by this. It seems like this is a macOS+Chrome and Linux+Chromium thing only.

**Comment by rstoenescu** [comment]
Tried with a macOS Sierra and Chrome and could not reproduce..

**Comment by a47ae** [comment]
On OS X 10.11.6 with Chrome Version 60.0.3112.90 there is a very subtle flickering on the background, which is definitely not there on Safari. But it is not nearly as heavy as in the video and only visible if you look for it.

**Comment by spectrolite** [comment]
I tried on Sierra + Chrome Version 59.0.3071.115 (Official Build) (64-bit) and I can see a faint flicker of the shadow around the modal. 
On Chrome Version 62.0.3175.0 (Official Build) canary (64-bit) I cannot see the flicker.
On Chromium Version 59.0.3071.115 (Developer Build) (64-bit) same shadow flicker as in Chrome.

**Comment by spectrolite** [comment]
Chrome Version 60.0.3112.90 (Official Build) (64-bit) on MacOS Sierra
shadow flickers on button hover 
(but I could never get the same window-wide flicker as the OP, only the modal’s shadow flickers)

**Comment by JCharante** [comment]
Chrome Version 60.0.3112.90 (Official Build) (64-bit) on Ubuntu 17.04 4.10.0-28-generic

Modal shadow flickers on button hover

https://s3.amazonaws.com/jcharante/public/quasarWeirdModalShadow.mp4

**Comment by laurentpayot** [comment]
Very subtle effect… I had to look very closely 👀

**Comment by tobiasdierich** [comment]
Seems like `.q-focusable` and `.q-hoverable` cause this. Removing both classes from the button fixes the flickering for me (obviously removing the button hover effect as well). But I have no idea why this causes the flickering, the css looks fine to me.

**Comment by tobiasdierich** [comment]
To follow up on this issue: I've tested it again on the latest chrome canary version and everything worked just fine. I guess it's okay to close this issue for now and blame the chrome devs 😀
