### ISSUE TITLE
table header sorting icon customization

### ISSUE THREAD

**Issue by raghuvarbisht** [quasarframework/quasar#7670]
How i can customize sort icon in table header?
I want to use my own icon to display as per requirement from the client.

**Comment by rstoenescu** [comment]
How is this considered a bug instead of a feature request?

**Comment by raghuvarbisht** [comment]
Thanks for tagging it correctly as a feature. Can you suggest we that is possible?

**Comment by rstoenescu** [comment]
You can override $q.iconSet.table.arrowUp to your desired icon. Do this in a boot file.

**Comment by fardolieri** [comment]
In case someone stumbles upon this, I made it work by adding the following lines to my main.ts
```ts
import { Quasar } from 'quasar';
import quasarIconSet from 'quasar/icon-set/svg-material-icons';

app.use(Quasar, {
  iconSet: quasarIconSet,
});

// I like the sorting arrow to point from lowest to highest
quasarIconSet.table.arrowUp = 'arrow_downward';
```
