### ISSUE TITLE
Why not quasar support JSX?

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#7672]
**Describe the bug**
Vue 2 support TypeScript and JSX using the @vue-cli 3 tool, Why not in quasar since quasar use Vue 2?

**Codepen/jsFiddle/Codesandbox (required)**
none

**To Reproduce**
1. create a quasar project using'quasar create quasardemo' command with the typescript support option, 
2. rename the filename 'MainLayout.vue' to 'MainLayout.tsx' and put the following code into it:
   import { VNode } from 'vue'
   import { Vue, Component } from 'vue-property-decorator'

   @Component
   export default class MainLayout extends Vue {
     private render (h: typeof Vue.prototype.$createElement): VNode {
       // return h("p","this is p");
       return (&lt;p&gt; this is p&lt;/p&gt;)
     }
   }

3. in file routes.ts, put the following code into it:
    import { RouteConfig } from 'vue-router'

    import MainLayout from '../layouts/MainLayout'

    const routes: RouteConfig[] = [
    {
      path: '/',
      component: MainLayout,
      children: [
        { path: '', component: () => import('pages/Index.vue') }
      ]
    },

    // Always leave this as last one,
    // but you can also remove it
    {
      path: '/1',
      component: () => import('pages/Error404.vue')
    }
    ]

    export default routes

4. in tsconfig.json, put the following the option into "compilerOptions":
   "jsx": "preserve"

5. execute the command “quasar dev" under the project root directory.
6. after executing the comand “quasar dev", the following error will occur:
   ERROR  Failed to compile with 1 errors                                       11:37:35
   This relative module was not found:
   * ../layouts/MainLayout in ./src/router/routes.ts

**Expected behavior**
the comand “quasar dev" would executed succussfully

**Screenshots**
none

**Platform (please complete the following information):**
OS: windows 10
Node: Node.js v12.9.1
NPM: npm 6.10.2

**Additional context**
none

**Comment by zouzg7829** [comment]
MainLayout.tsx:

`import { VNode } from 'vue'
import { Vue, Component } from 'vue-property-decorator'

@Component
export default class MainLayout extends Vue {
  private render (h: typeof Vue.prototype.$createElement): VNode | null {
    // return h("p","this is p");
    return (<p> this is p</p>)
  }
}
`

**Comment by anyclub** [comment]
use jsx 
1. install "babel-plugin-syntax-jsx" and "babel-plugin-transform-vue-jsx"
![image](https://user-images.githubusercontent.com/19922265/96061834-ca94e080-0ec6-11eb-9456-45dcf1dd8a2d.png)

2. in babel.config.js,  add plugins 
![image](https://user-images.githubusercontent.com/19922265/96061876-e00a0a80-0ec6-11eb-99e1-d2c8e5b3e4ad.png)

ok, it work


For quasar/cli in the current VUE3 plan, are you considering upgrading to VITE?

**Comment by seanaye** [comment]
@anyclub This doesn't work for me on the latest quasar.

```
 error  in ./src/components/render/ParseMention.jsx

Module parse failed: Unexpected token (29:15)
File was processed with these loaders:
 * ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
|       if (word.charAt(0) === '@') {
|         const href = `/user/${word.substring(1)}`
>         return <a href={href}></a>
|       } else {
|         return word
```

**Comment by anyclub** [comment]
Babel.config.json set？

**Comment by seanaye** [comment]
@anyclub 

```js
/* eslint-env node */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require('fs-extra')
let extend

/**
 * The .babelrc file has been created to assist Jest for transpiling.
 * You should keep your application's babel rules in this file.
 */

if (fs.existsSync('./.babelrc')) {
  extend = './.babelrc'
}

module.exports = {
  presets: [
    // '@vue/babel-preset-jsx',
    '@quasar/babel-preset-app'
  ],
  extends: extend,
  plugins: [
    'transform-vue-jsx'
  ]
}

```

I have also tried previously with the official vue babel preset which is commented out here

**Comment by anyclub** [comment]
https://codesandbox.io/s/magical-dew-mybq9?file=/src/pages/Index.vue
@seanaye

**Comment by seanaye** [comment]
Thanks for all your help! Although it doesn't appear to be working in the sandbox you setup
![image](https://user-images.githubusercontent.com/24496822/98059536-5f7b6180-1e15-11eb-9435-37f0a06fbe14.png)

**Comment by anyclub** [comment]
I don’t know why it can’t start automatically

![image](https://user-images.githubusercontent.com/19922265/98060368-61303e00-1e84-11eb-8d96-d3caaf75f86e.png)

**Comment by pdanpdan** [comment]
I think this is solved. If you still have problems please use the discord channel or the forum
Thank you
