### ISSUE TITLE
QBtnDropdown && no-route-dismiss

### ISSUE THREAD

**Issue by gewisser** [quasarframework/quasar#7673]
**Is your feature request related to a problem? Please describe.**
In my app click in any element in q-btn-dropdown changes the URL. If I change the url the dropdown menu is closed

**Describe the solution you'd like**
I need the ‘no-route-dismiss’ prop like in q-dialog, q-menu, which will keep the q-btn-dropdown functionality but just prevent it from closing when changing URL

**Describe alternatives you've considered**
If I use the "persistent" property, then the menu doesn't close when changing url. However, now clicking outside of this menu does not close the menu.

**Comment by rstoenescu** [comment]
Will be available in Quasar v1.13.2.

**Comment by gewisser** [comment]
Thank. Works on the desktop. On mobile devices (with a small screen size, where the menu slides out from the bottom) does not work.

**Comment by rstoenescu** [comment]
@gewisser You're probably referring to a Cordova/Capacitor app and QDrawer's behavior which you can change by using QDrawer's "persistent" prop.

**Comment by gewisser** [comment]
@rstoenescu Yes thank you. Understood this issue

**Comment by H0WARDDD** [comment]
Can this prop add to q-elect as well?
