### ISSUE TITLE
When QSelect is used as a prepend/append slot of a QInput, its paddingTop depends on whether that QInput has a label or not

### ISSUE THREAD

**Issue by Anhil-111** [quasarframework/quasar#7676]
**Describe the bug**
There's a CSS selector `.q-field--labeled .q-field__native` that sets line-height, padding-top and padding-bottom. When you nest QFields, it causes an issue if one has a label but at least one of its descendants does not.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/2xwdk0p7/

**To Reproduce**
1. Create a QInput;
2. Add a QSelect with `slot="prepend"`;
3. Add a label to QInput.

**Expected behavior**
QSelect shouldn't be affected by the presence of a label in one of its ancestors.

**Screenshots**
![quasar-inner-qfield](https://user-images.githubusercontent.com/53266103/91046620-70dc0c80-e621-11ea-8ba8-b40bdb128296.png)

**Platform (please complete the following information):**
OS: macOS 10.15.6
Node: 10.22.0
NPM: -
Yarn: 1.22.4
Browsers: Chrome 84.0.4147.135, FF 79.0
iOS: -
Android: -
Electron: -

**Additional context**
\-

**Comment by rstoenescu** [comment]
Hi,

Do not nest QSelects in QInput... would you nest a `<select>` into a `<input>`?
Rather use the flexbox classes and put them one next to each other (`<div class="row no-wrap items-center"> <q-input... /> <q-select..... /> </div>`)

**Comment by Anhil-111** [comment]
This does solve the problem with `label`, but the reason I went with `slot="prepend"` is that the result looks like a single element when you focus either part of it or when validation fails. Here's how it looks when elements are siblings inside of a `<div class="row no-wrap items-center" />`:

<img width="315" alt="Focus" src="https://user-images.githubusercontent.com/53266103/91154036-a89e8f00-e6c9-11ea-8a1f-e021716552f1.png">
<img width="315" alt="Failed validation" src="https://user-images.githubusercontent.com/53266103/91154037-a9372580-e6c9-11ea-8271-404fffc68900.png">

The bottom border is what bothers me.
