### ISSUE TITLE
Box-shadow on QAvatar with rounded or square props displays as a circle 

### ISSUE THREAD

**Issue by cnegrisanu** [quasarframework/quasar#7678]
**Describe the bug**
Adding a box-shadow style to a  QAvatar component with the rounded or square prop set, seems to apply the shadow to the original component border-radius of 50% instead of applying it to the correct shape. So, no matter what shadow is applied and how the avatar actually looks, the shadow is always a circle.  

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/apzgcuds/11/

**To Reproduce**
1. Add a QAvatar anywhere on a page or component
2. Set the 'square' or 'rounded' prop on the QAvatar
3. Add an inline style or in the <style> section add a box-shadow effect like so: `box-shadow: 4px 4px 10px rgba(0, 0, 0, 2.0);`
4. Run server and checkout the page/component, the applied shadow is still a circle

**Expected behavior**
The box-shadow effect should follow the shape of the QAvatar

**Platform (please complete the following information):**
OS: Linux(5.4.0-42-generic) - linux/x64 or Windows_NT(10.0.18363) - win32/x64 (it replicates on both)
Node: 12.18.3
NPM: 6.14.8
Browsers: Chrome (_Version 84.0.4147.125 (Official Build) (64-bit)_), Brave (_Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)_)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v1.13.2.

**Comment by cnegrisanu** [comment]
Mutumesc mult! Am testat fix-ul si e totul in regula! Sanatate!

**Comment by rstoenescu** [comment]
Cu placere.
