### ISSUE TITLE
[Request] Draggable modals and dialogs

### ISSUE THREAD

**Issue by kerbylav** [quasarframework/quasar#768]
I think it is a must: modals or dialogs very often hides behind them information which could be useful to make decisions

**Comment by rstoenescu** [comment]
This makes sense only when running under a desktop browser. Will do. Thanks for the proposal.

**Comment by Zyles** [comment]
I really need draggable modals, see here: https://github.com/mzabriskie/react-draggable

**Comment by marco-quintella** [comment]
This draggable would be wonderfull

**Comment by tzmartin** [comment]
Example `q-dialog` draggable component https://codesandbox.io/s/quirky-shannon-nfpci

**Comment by rstoenescu** [comment]
This can be done with TouchPan directive. The problem with doing this within the framework is that we don't know what the Dialog will contain so we can't just attach the logic to the whole Dialog. Some content's behavior might negatively interfere with TouchPan. However, in devland, you can use the directive on a particular part of the dialog (like a QToolbar for the title or a specific QCardSection).
