### ISSUE TITLE
q-uploader only 1 image upload when using multiple with batch

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#7680]
``` 
<q-uploader
        url="http://localhost:4444/upload"
        label="Batch upload"
        multiple
        batch
        style="max-width: 300px"
      />
```

**Comment by rstoenescu** [comment]
Just want to make sure that you understand what "batch" means:
(extract from docs) "By default, multiple files will be uploaded individually (one thread per file). Should you want all files to be uploaded in a single thread, use the batch property (second QUploader in the example below)." 

This is exactly what happens as shown in the screenshot.

![upload](https://user-images.githubusercontent.com/4665641/91185525-9c7cf680-e6f6-11ea-9f45-81c5d8edfe7e.png)

**Comment by diadal** [comment]
i understand the document 

check this 
<img width="973" alt="Screenshot 2020-08-25 at 3 27 57 PM" src="https://user-images.githubusercontent.com/19895516/91187167-c37ffc00-e6e7-11ea-92c0-66db9e9e564b.png">

only 1 file send to backend when i use `batch` what am expecting is `$r->file('image');` to be in array of images 

```
public function ImageUpload(Request $r)
    {
        $image = $r->file('image');
        logger(['image '=> $r->file]);
        $extension = $image->getClientOriginalName();
        $filename  = 'image-' . time() . '.' . $extension;
        Storage::disk('public')->putFileAs('/images/', $image, $filename);
        $paths =   url(Storage::url('images/'.$filename));
        logger(['image urls'=> $paths]);
        return $paths;
    }
```

**Comment by rstoenescu** [comment]
@diadal I just showed you that Quasar sends a FormData with two files (see for yourself in the Network tab). Handling this in your PHP backend is your task. We are not responsible for your backend code to correctly parse a standardised way of sending files. We however are responsible for sending the correct data (which I just showed you proof of).

**Comment by diadal** [comment]
@rstoenescu am not asking you guys @ the backend only want to know if any fast way to the bug this on my end

**Comment by rstoenescu** [comment]
Please use https://chat.quasar.dev (Discord server) to request help from the community.

**Comment by diadal** [comment]
am close to what am looking just one last question is there any to know file `key` when using batch  
like 
`:field-name="(file) => 'background' + file.key"`

**Comment by diadal** [comment]
never mind figured out
