### ISSUE TITLE
Confusion of between and normalizeToInterval function

### ISSUE THREAD

**Issue by christianMurschall** [quasarframework/quasar#7681]
The [formatter-utils docs](https://quasar.dev/quasar-utils/formatter-utils#Normalize-Number-to-Interval) describe the `between` function under the _Normalize-Number-to-Interval_ section.
After looking at the source it confuses me that there is both a `between` function and a `normalizeToInterval` function exported.

I would also suggest to rename the between function to the more common used name `clamp`.

**Comment by rstoenescu** [comment]
Thanks for pointing this out. Fixed docs.

**Comment by rstoenescu** [comment]
(Will be available on next deployment)
