### ISSUE TITLE
QDate unexpectedly clears selected date

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#7682]
**Describe the bug**
When using `QDate` in single mode since v1.13.0, selecting the currently-selected date sets the model to null. Prior to v1.13.0, the component would retain the same value (and I believe re-emit the input event so that it can be closed if used in a `QPopupProxy` or similar).
 
Under the heading **Multiple selection**, The documentation mentions
> Clicking on an already selected day will deselect it.

implying that this behaviour is intended to be specific to `multiple`. However the same behaviour is present in non-multiple use cases.

It's not clear if this is intended behaviour for non-multiple use cases.  

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fquasar.dev%2Fvue-components%2Fdate

**To Reproduce**
1. Go to the Codepen above
2. Click on February 1st, 2019.
3. See the selection being cleared

**Expected behavior**
The date to remain selected as it was prior to v1.13.0 unless `multiple` or `range` are specified.

**Screenshots**

**Platform (please complete the following information):**

**Additional context**
If the current behaviour is preferred/intended, then perhaps including the original model value in the `input` event or a callback to reject the change would make it easier to undo the de-selection.

**Comment by rstoenescu** [comment]
New prop will be available in Quasar v1.13.2: Boolean "no-unset"
Please note that the recommended way is to use additional buttons instead of relying on the selection events, like here: https://quasar.dev/vue-components/date#Example--With-additional-buttons

**Comment by rstoenescu** [comment]
The current behavior of being able to unselect dates is required otherwise multiple and range selection would become almost useless.
