### ISSUE TITLE
Problem of swiping on touchscreen to up and down  on mobile platform (Android, Chrome) for SPA application.

### ISSUE THREAD

**Issue by atillaaliyev** [quasarframework/quasar#7683]
Hi everyone, 
First of all, sorry for my English.

I created a SPA (http://aaliyev.sefaakmemis.com/#/file/fileentry) and I made it responsive.
But it swipe too hard when swiping up and down in the middle of the screen and sometimes it doesn't swipe at all.
But when you swipe it from the right and left side, there is no problem,it swipes perfect, I couldn't understand why.

Thank you

https://codesandbox.io/s/great-shannon-8gtcs

**Comment by metalsadman** [comment]
seem related to this https://forum.quasar-framework.org/topic/5967/tab-panels-swipeable-textarea-selection-swipes-tab-panel, try the poster's solution.

**Comment by atillaaliyev** [comment]
I dont understand this solution , probably we dont have same problem.But , still, I tried it.
I got into Q-Stepper inside of Q-Tab-Panels and set swipable properties.But it didnt work.

Touchscreen swipable is still lazy.

**Comment by atillaaliyev** [comment]
I solved my problem.

Problem is usage of  v-touch-swipe.mouse.I wanted stepper's go to the previous and next step, swiping left and right.It's success but it prevent to swipe up and down at the mobile platform,I dont know main reason.

I used v-touch-swipe.mouse.left.right , it's worked.

Thank you.
