### ISSUE TITLE
Splitter resizing breaks when changing :horizontal state

### ISSUE THREAD

**Issue by MIDIBlocks** [quasarframework/quasar#7684]
**Describe the bug**
If you bind the `horizontal` property of the [QSplitter](https://quasar.dev/vue-components/splitter#Horizontal), then it is not possible to resize to a lesser value then what it was set to when the `horizontal` state updated.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/MIDIBlocks/pen/PoNpREb?editors=1010

**To Reproduce**
1. Create a splitter like: `<q-splitter v-model="splitterModel" :horizontal='isHoriz'>` (see: https://codepen.io/MIDIBlocks/pen/PoNpREb?editors=1010)
2. Resize the splitter
3. Click the "Flip" once at the top of the view
4. Try resizing up
5. Notice how the more you drag up, the more it resizes downward

**Expected behavior**
Resizing up after flipping `horizontal` should resize upwards and not downward

**Screenshots**
![](https://i.imgur.com/o1iC2KF.gif)

**Platform (please complete the following information):**
OS: Windows 10
Node: 12.x.x LTS
Browsers: Chrome

**Comment by metalsadman** [comment]
Use a key on your qsplitter that changes as you set horizontal.

**Comment by MIDIBlocks** [comment]
Thanks that fixed it!

**Comment by rstoenescu** [comment]
Thanks for reporting this regression.
Fix will be available in Quasar v1.13.2. When this is released, please remove the key (workaround suggested above).
