### ISSUE TITLE
Click events inside q-route-tab gets not triggered anymore

### ISSUE THREAD

**Issue by hebinet** [quasarframework/quasar#7686]
**Describe the bug**
Click events inside q-route-tab gets not triggered anymore since updateing from 1.12 to 1.13.1

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/hebinet/pen/wvGJRgj

**To Reproduce**
1. click on any of the 'close' icons in the tabs

**Expected behavior**
When cklicking on the tab, it should navigate as expected, but when clicking on the 'close' icon it should increment the counter by 1

Even @click.stop.prevent doesn't help

**Platform (please complete the following information):**
OS: Arch Linux, Mac OS
Browsers: Chrome, Firefox

**Additional context**
I think it has to do something with the following changes related to this issues.
- #7143 
- #7365

**Comment by dercodercom** [comment]
i have the same problem =( can fix it?

**Comment by rstoenescu** [comment]
@pdanpdan please take a look. it has to do with your latest change on the component.

**Comment by gaby64** [comment]
I also have this issue

**Comment by hebinet** [comment]
Yesterday, I also noticed, that the `click` event on the `q-route-tab` itself doesn't get triggered accordingly. I updated my codepen so you can see the newly found problem too.

It's been now a month since I opened this issue without any significant updates.
Is there a rough timeline when this issue will be fixed?

**Comment by hebinet** [comment]
Any updates on this issue?

**Comment by gaby64** [comment]
> Any updates on this issue?

its not coming to quasar v1, but check my fix, its quite simple to add to your copy in node_modules folder

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
