### ISSUE TITLE
.htaccess vom /public folder won´t get copied to /dist folder when building

### ISSUE THREAD

**Issue by mobsean** [quasarframework/quasar#7687]
**Describe the bug**
Hi,
when I `quasar build -m pwa` my project the all files from the /public folder get copied to /dist/pwa except the .htaccess file.
When I copy the file and rename, for example to Copy.htaccess the will land in the /dist/pwa folder after building.

**To Reproduce**
1. create .htaccess file in /public folder
2. `quasar build -m pwa` the project
3. .htaccess file won´t get copied to /dist/pwa

**Expected behavior**
Also copy the .htaccess file to the /dist/pwa folder after building the project.

**Platform:**
OS: Win10/ 64bit
Node: 10.16.0
NPM: 6.9.0

**Comment by rstoenescu** [comment]
Enhancement will be available in "@quasar/app" v2.0.9.
