### ISSUE TITLE
[Request] Consider formatted text when searching in DataTable

### ISSUE THREAD

**Issue by icylogic** [quasarframework/quasar#769]
For now, when filtering rows in DataTable, it simply finds the text in **Original Fields**
`row => (row[field] + '').toLowerCase().indexOf(terms) > -1`
(https://github.com/quasarframework/quasar/blob/1e43188a1ec749213af3d9a6d298ed3c7fd26a9b/src/components/data-table/plugins/filter/filter.js#L28-L34)

which means if I provide the formatter for columns, users are not able to search by what they saw (`format(value, row)`). They could only search by the original data (`row[field]`), especially when I do some i18n works in `format()` .

**Comment by rstoenescu** [comment]
DataTable revamp is in progress for v0.15. It will include this. Thanks for your patience.

**Comment by rstoenescu** [comment]
Closing as it's ready in future v0.15
