### ISSUE TITLE
QSticky z index - QInput outlined overlaps QSticky

### ISSUE THREAD

**Issue by bjbk** [quasarframework/quasar#7690]
**Describe the bug**
When scrolling past a QSticky, any outline added to a QInput has a higher z index.  The content of the QInput does not overlap, just the outline. 

**Codepen/jsFiddle/Codesandbox (required)**
Codepen (https://codepen.io/bjbk/pen/mdJEbJe)

**To Reproduce**
Place a `q-sticky` and an element with some `q-inputs` having the `outlined` prop set.  Scroll until the input passes beneath the QSticky.  See z index behavior.

**Expected behavior**
Expected the QSticky to have a higher z index than the outline.

**Screenshots**
<img width="366" alt="Screen Shot 2020-08-26 at 8 16 35 PM" src="https://user-images.githubusercontent.com/7434052/91369188-2b623f80-e7d9-11ea-8945-9455858a3502.png">

**Platform (please complete the following information):**
OS: macOS 10.15.6
Node: v14.4.0
NPM: 6.14.5
Yarn: 1.22.4
Electron: 9.2.0
Quasar: 1.13.1
quasar/app: 2.0.8
quasar/cli: 1.1.0

**Comment by metalsadman** [comment]
i dunno why is it so, but can't you just add a class z-top or z-max on the sticky instead? or add a style z-index.

**Comment by bjbk** [comment]
@metalsadman, Sure can.  Easy fix on my end, but I assume that this is not expected behavior and wanted to alert the team.

**Comment by rstoenescu** [comment]
Thank you for reporting.
Fix will be available in Quasar v1.13.3.

**Comment by pdanpdan** [comment]
Just for future reference, solving this breaks the lines on all bordered QField derivates that have autocomplete.

**Comment by rstoenescu** [comment]
Took care of that too right in the next commit yesterday.

**Comment by pdanpdan** [comment]
I'll check, but as far as I remember when I tried the same approach there are problems with standard focused and with the corners of outlined
