### ISSUE TITLE
Duplicated text on DO & DON'Ts page on the docs.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [quasarframework/quasar#7691]
![image](https://user-images.githubusercontent.com/60849894/91434383-299e8780-e87e-11ea-9663-df9c834f6082.png)
https://quasar.dev/security/dos-and-donts#Cryptography

**Comment by OtabekSadiridinov** [comment]
Why in every step you just emphasized  **DON'T** create your own cryptographic solution?
Just leaving last one with link is enough I think. Whatever, you know what to do. This is just my idea.

**Comment by rstoenescu** [comment]
This is to emphasize on "just don't do your own cryptographic solution", as in drama. It's intended.
