### ISSUE TITLE
[Service-Worker Bug] The new offline.html has been cached, but the refresh is still the old version of offline.html.

### ISSUE THREAD

**Issue by xiaoer3301** [quasarframework/quasar#7693]
**Describe the bug**
service-worker.js can download the new file, but still access the old offline.html after refreshing.

This problem is very obvious on iOS PWA, no matter how many times it is closed and restarted, it cannot be refreshed to the latest version. You must clear the cache in the settings and open it again to refresh to the latest version.

**Screenshots**
<img width="878" alt="iShot2020-08-28上午11 11 25" src="https://user-images.githubusercontent.com/49556560/91517682-ea754280-e920-11ea-9709-f492bd7471bf.png">
<img width="880" alt="iShot2020-08-28上午11 11 54" src="https://user-images.githubusercontent.com/49556560/91517710-01b43000-e921-11ea-8297-1f3928b410c4.png">
It can be seen from the figure that the new offline has been downloaded. The new offline.html has `window.version = '1.0.0-272309'`, and the old offline.html has `window.version ='######'`.
<img width="583" alt="iShot2020-08-28上午11 10 41" src="https://user-images.githubusercontent.com/49556560/91517721-0b3d9800-e921-11ea-9551-9360d6609f83.png">
When the page is refreshed many times, the offline.html is still not updated, and it is the old version of offline.html.

**Platform (please complete the following information):**
OS: centOS
Node:v10.16.3
NPM:6.14.5
Yarn:-
Browsers:Chrome 84
iOS:-
Android:-
Electron:-

**Comment by rstoenescu** [comment]
Hi,

This should be fixed in "@quasar/app" v2.0.9. Please reopen or comment if you still experience problems.

**Comment by xiaoer3301** [comment]
@rstoenescu 
Thanks for solving this problem.
Now macOS Safari can be updated, and it is expected that iOS Safari can also. But both Chrome and Safari need to be restarted to update to the latest version.
Can it be updated to the latest version after refreshing the page? This will make it more perfect.
I hope that in the future, we will pay attention to such features that may cause major problems. This service-worker has already caused users to be unable to upgrade to the latest version.

**Comment by rstoenescu** [comment]
The upgrade process in itself is triggered by the browser, so out of our control.
