### ISSUE TITLE
Cannot resolve importing script even when in the same folder

### ISSUE THREAD

**Issue by gg4u** [quasarframework/quasar#7695]
I am struggling to port a Vue app in Quasar.

I cannot resolve dependencies.

for the sake of testing:
```

// in /pages/index.vue

<script>
import content from 'contentSources.js'
...

</script>

```
and

```

// in the same folde /pages/ contentSources.js

export default {

		wikipedia: {
			decorators : 'blabla',
			entityPage : 'blabla'
		}

}
```

error:

Failed to compile.

```
./src/pages/Index.vue?vue&type=script&lang=js& (./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'contentSources.js' in '[my_proj]/src/pages'
```

I cannot figure out what the problem is.

Could you please advice? thank you!

**Comment by metalsadman** [comment]
> import content from 'contentSources.js'

try `'./contentSources.js'`.

**Comment by rstoenescu** [comment]
When you are not specifying a path then webpack will resolve it as a package from node_modules. So, as indicated above, put "./" before the name of the file.

**Comment by gg4u** [comment]
Thank you @metalsadman and @rstoenescu for clarifying what webpack does.

The confusing part is that it find the path for the vue component, but not for the script.

my folder structure:
```
/src
- components
--  myComp.vue
- lib
-- myScript.js
- pages
-- Index.vue

```

With this folder structure, if I do:

```
import myComp from 'components/myComp.vue'  // is found
import content from 'lib/contentSources.js' // is NOT found

```
I must : 

```
import myComp from '../components/myComp.vue'  // is found
import content from '../lib/contentSources.js' // is ALSO found

```

I am editing `Index.vue` (I started a project using Layout builder).

**Comment by metalsadman** [comment]
> Thank you @metalsadman and @rstoenescu for clarifying what webpack does.
> 
> The confusing part is that it find the path for the vue component, but not for the script.
> 
> my folder structure:
> 
> ```
> /src
> - components
> --  myComp.vue
> - lib
> -- myScript.js
> - pages
> -- Index.vue
> ```
> 
> With this folder structure, if I do:
> 
> ```
> \\ Index.vue file
> import myComp from 'components/myComp.vue'  // is found
> import content from 'lib/contentSources.js' // is NOT found
> ```
> 
> I must :
> 
> ```
> \\ Index.vue file
> import myComp from '../components/myComp.vue'  // is found
> import content from '../lib/contentSources.js' // is ALSO found
> ```
> 
> I am editing `Index.vue` (I started a project using Layout builder).

Because components directory has an alias registered lib does not. Check the docs about it and also how to add your own https://quasar.dev/quasar-cli/handling-webpack#Webpack-Aliases.
