### ISSUE TITLE
QScrollArea.scrollPercentage

### ISSUE THREAD

**Issue by TheWindRest** [quasarframework/quasar#7696]
**Is your feature request related to a problem? Please describe.**
can we set QScrollArea.scrollPercentage’s value, not just setScrollPosition function.

**Describe the solution you'd like**
add a QScrollArea.setScrollPercentage, params: percentent(0, 1)

**Comment by rstoenescu** [comment]
New method (setScrollPercentage) will be available in Quasar v1.13.2.
