### ISSUE TITLE
The event object is not passed to QInput events

### ISSUE THREAD

**Issue by egyel** [quasarframework/quasar#7697]
**Describe the bug**
The event object is not passed to QInput events (input, blur).

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/orpf4L28/1/

**To Reproduce**
- Change the number in the top (standard input) component -> the message below the input changes and there are no error.
- Change the number in the second (QInput + @blur) component and click away -> the value is set back to original one.
- Change the number in the last (QInput + @input) component -> the "Cannot read property 'value' of undefined" error is thrown in the console

**Expected behavior**
QInput events should work similarly as they work in standard input.

**Screenshots**
N/A

**Platform (please complete the following information):**
Quasar: v1.13.1

**Additional context**
None

**Comment by metalsadman** [comment]
Thats not a bug, pls join discord for questions. See the api for the input event, should just be the value, which you couldve easily figured out logging e instead of target.

**Comment by egyel** [comment]
thanks
