### ISSUE TITLE
QAjaxBar: ability to hide bar on specific page manually

### ISSUE THREAD

**Issue by p1pchenk0** [quasarframework/quasar#7698]
Hi, on my project there is a need to make api request on specific page with 5 seconds interval, meaning that loading bar on top is showing each time request is made. I am totally fine with this bar on other pages, where no interval requests happen. Is it possible to provide some `show()` `hide()` methods to visually hide bar and then return it back after page is changed?

**Comment by metalsadman** [comment]
> Hi, on my project there is a need to make api request on specific page with 5 seconds interval, meaning that loading bar on top is showing each time request is made. I am totally fine with this bar on other pages, where no interval requests happen. Is it possible to provide some `show()` `hide()` methods to visually hide bar and then return it back after page is changed?

use our discord for questions next time, use `skip-hijack` https://quasar.dev/vue-components/ajax-bar#QAjaxBar-API

**Comment by p1pchenk0** [comment]
@metalsadman this is feature request, `skip-hijack` is non-reactive, so it doesn't give expected behavior

**Comment by pianopronto** [comment]
@p1pchenk0 I use a mixin for this, just include it on whatever page you want to hide the loading bar on.
```
export default {
  created() {
    this.loadingBarSize = this.$q.loadingBar.size
    this.$q.loadingBar.setDefaults({
      size: '0px'
    })
  },
  destroyed() {
    this.$q.loadingBar.setDefaults({
      size: this.loadingBarSize
    })
  },
}
```

**Comment by victortrusov** [comment]
Another workaround with wrapper (ts):
```
// useLoadingBar.ts

import { LoadingBar, type QAjaxBarProps } from 'quasar';

let defaults: QAjaxBarProps | undefined = undefined;

export default () => ({
  get isActive() {
    return LoadingBar.isActive;
  },
  start: LoadingBar.start,
  stop: LoadingBar.stop,
  increment: LoadingBar.increment,
  setDefaults: (props: QAjaxBarProps) => {
    LoadingBar.setDefaults(props);
    defaults = props;
  },
  hide: () => {
    LoadingBar.setDefaults({
      ...defaults,
      hijackFilter: () => false
    });
  },
  restore: () => {
    LoadingBar.setDefaults(defaults);
  }
});
```
```
// YourComponent.vue

const loadingBar = useLoadingBar();

loadingBar.hide();
await doStuff();
loadingBar.restore();
```
