### ISSUE TITLE
QTree - Custom filtering with custom filters

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#7699]
**Describe the solution you'd like**
I want to use custom filtering with a custom `:filter-method`. However this `:filter-method` is only called when `:filter` is set to a non-empty string. I want to filter the nodes based on some custom properties I add to the nodes, so only a filter on string is not very useful. It should not be necessary to pass an empty filter string in order for my custom filter method to start working. 

**Describe alternatives you've considered**
Current hack to get it to work is not pretty: `:filter="' '"` on the `<q-tree>` element. Either disable the filter check if only the filter-method is provided or make it possible to provide a custom object to the filter property.

**Comment by rstoenescu** [comment]
Hi,

You can always do the filter outside of QTree (your own controls, like QInput, QToggle etc etc). Then supply the filtered nodes to QTree.

**Comment by mgulla701** [comment]
This kinda sucks. If you go for implementing your own filter, you have to rebuild a whole tree
