### ISSUE TITLE
Qbadge does not work with QBtnToggle

### ISSUE THREAD

**Issue by VIM-Arcange** [quasarframework/quasar#7702]
**Describe the bug**

**Code To Reproduce**
```
<template>
  <div class="q-pa-md">
    <q-btn-toggle
      v-model="model"
      toggle-color="primary"
      :options="[
        {label: 'One', value: 'one'},
        {label: 'Two', value: 'two'},
        {label: 'Three', value: 'three'}
      ]"
    >
       <q-badge color="orange" floating>123</q-badge> 
    </q-btn-toggle>
  </div>
</template>
```

**Expected behavior**
The floating badge should be displayed

**Current behavior**
The badge is not displayed.
While the QBtnToggle is correctly displayed, the component stops working (select has no effect)

**Comment by rstoenescu** [comment]
Default slot has been enabled for this component.
Will be available in Quasar v1.13.2.
