### ISSUE TITLE
QTable: add title-class property.

### ISSUE THREAD

**Issue by jeroenqui** [quasarframework/quasar#7705]
**Is your feature request related to a problem? Please describe.**
I'm trying to achieve a table title with background color (see attached screenschot), but without colouring the pagination slot.

**Describe the solution you'd like**
Like _card-class, card-container-class, table-class, table-header-class_ i'd like to see **title-class**

**Describe alternatives you've considered**
1. A borderless table with a q-toolbar component on top
2. Colouring the whole table with: card-class="bg-deep-purple-7 text-white" and then reverting the colour of other parts with: table-class="bg-white text-black" and table-header-class="text-black"

**Additional context**
![image](https://user-images.githubusercontent.com/3017558/91767465-7666c300-ebdc-11ea-8b14-f523f903d22d.png)

**Comment by rstoenescu** [comment]
Hi,

New prop (title-class) will be available in Quasar v1.13.2.

However, you can already do what you want by adding a class to your QTable and using a selector to target the title "div". Example:

```
.my-table .q-table__title
  color: #fefefe
```

**Comment by jeroenqui** [comment]
Thank you very much @rstoenescu ! I was aware of that method, but I need to give it a classname so it's themable. Thanks again!
