### ISSUE TITLE
QTabs unexpectedly center aligned

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#7706]
**Describe the bug**
QTabs sometimes unexpectedly becomes left aligned when changing browser zoom. This stops happening when the padding in the example is removed. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Fanvadar/pen/YzqxLxP

**To Reproduce**
1. Go to https://codepen.io/Fanvadar/pen/YzqxLxP
2. Change your browser zoom to 75%
3. For me this adds the "q-tabs__content--align-center" class

**Expected behavior**
I expected the tabs to be center aligned regardless of browser zoom level.

**Platform (please complete the following information):**
Browsers: Chrome

**Comment by pdanpdan** [comment]
Hello. When a specific width breakpoint is reached the tabs will be stretched.
Also I see no way how it would become left aligned. Also the reproduction steps cannot reproduce the problem.
If you can provide a way to reproduce the problem please post it here and we'll check.
