### ISSUE TITLE
browserslist: Unknown browser query `bad apple`. Maybe you are using old Browserslist or made typo in query.

### ISSUE THREAD

**Issue by 491552374** [quasarframework/quasar#7707]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by 491552374** [comment]
browserslist: Unknown browser query `bad apple`. Maybe you are using old Browserslist or made typo in query.

**Comment by rstoenescu** [comment]
Hi,

Please visit [https://github.com/browserslist/browserslist] as indicated in the docs to see the valid values that you can use for the package.json > browserslist. Thanks.

**Comment by 491552374** [comment]
> 你好
> 
> 请按照文档中的指示访问[https://github.com/browserslist/browserslist]，以查看可用于package.json> browserslist的有效值。谢谢。

Be mindful about it though, as it is sufficient to add one “bad apple” in the options list and that will dumb down your code back to ES5.

**Comment by rstoenescu** [comment]
This is an expression in the English language, not a value. In this case it means "it is sufficient to add one really old browser and that will dumb down your code back to ES5."
