### ISSUE TITLE
QTable: add top-class property.

### ISSUE THREAD

**Issue by jeroenqui** [quasarframework/quasar#7710]
Is your feature request related to a problem? Please describe.
I'm trying to achieve a table title bar with background color.
Fix https://github.com/quasarframework/quasar/commit/7c409d00bbb326ab9a47115c0a6c9ac142018dfa 
 to issue: https://github.com/quasarframework/quasar/issues/7705 did not give the intended result.

Describe the solution you'd like
Like card-class, card-container-class, table-class, table-header-class, title-class i'd like to see top-class

Describe alternatives you've considered

A borderless table with a q-toolbar component on top

Colouring the whole table with: card-class="bg-deep-purple-7 text-white" and then reverting the colour of other parts with: table-class="bg-white text-black" and table-header-class="text-black"

adding a class to your QTable and using a selector to target the title "div". Example:

.my-table .q-table__title
  color: #fefefe

Additional context
![image](https://user-images.githubusercontent.com/3017558/92008394-67505400-ed47-11ea-8fdc-bff66114dfb0.png)

**Comment by rstoenescu** [comment]
You can also use: `background-color: var(--q-color-primary)`
If you have some spare bucks, please visit https://donate.quasar.dev

Cheers.
