### ISSUE TITLE
q-input standout text colour customisation is ignored when outlined is used

### ISSUE THREAD

**Issue by vijayganeshpk** [quasarframework/quasar#7711]
**Describe the bug**
When `outlined` mode is used with `standout` customisation, any text colour settings in `standout` is ignored

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/codecanvas/heq1pLu6/

**To Reproduce**
1. use q-input with outlined and standout attributes

**Expected behavior**
`standout` customisation is respected while in `standout` mode (the input is in focus)

**Screenshots**
![image](https://user-images.githubusercontent.com/1961111/92028894-d17fed80-ed75-11ea-9659-8874643106cc.png)
![image](https://user-images.githubusercontent.com/1961111/92029223-4d7a3580-ed76-11ea-9cd2-4dfa3d3c58a4.png)

**Platform (please complete the following information):**
OS: macOS 10.15.6
Node: v12.18.3
NPM: 6.14.8
Yarn:
Browsers: Brave  - Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)

**Comment by pdanpdan** [comment]
Hello. Standout and outlined are mutually exclusive, decide which one you want to use.
