### ISSUE TITLE
QBtn[type="a"][href="https://google.com"] in QInput append slot has not working.

### ISSUE THREAD

**Issue by luozhihua** [quasarframework/quasar#7713]
**Describe the bug**
QBtn[type="a"][href="https://google.com"] in QInput append slot has not working.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/colinluo/pen/LYNzMqw?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2F

**To Reproduce**
1. Go to https://codepen.io/colinluo/pen/LYNzMqw?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2F
2. Click on 'HOME' icon
3. not jump to google home.

**Expected behavior**
Expected links with in QInput append slot working right.

**Screenshots**

**Platform (please complete the following information):**
OS: Darwin(20.0.0) - darwin/x64
Node: 14.9.0
NPM: 6.14.8
Yarn: -
Browsers: Chrome 86.0.4240.22
iOS: -
Android: -
Electron: -

**Comment by rstoenescu** [comment]
Add a "@click.stop" on the button to stop propagation of the event.
