### ISSUE TITLE
quasar.conf.js doesn't communicate devServer settings (specifically headers) - CORS error

### ISSUE THREAD

**Issue by Christo1101** [quasarframework/quasar#7716]
**Bug description:**
It very much seems like when one sets header changes in the quasar.conf.js/devServer for API request to bypass CORS policy it isn't actually carried out and then send with the request. I successfully made an api request and bypassed the CORS problem with a chrome extension (CORS Unblock - https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino/related?hl=en), which doesn't do anything else but simply appends "access-control-allow-origin: *" header to every web request when enabled.

If I include the headers in the devServer (quasar.conf.js), I still receive the CORS Policy block:

```
 devServer: {
      https: false,
      port: 8080,
      open: true, // opens browser window automatically
      headers: {
        'access-control-allow-origin': '*',
        'access-control-allow-methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS'
      }
}
```

Another way to bypass it mentioned in this thread (https://github.com/quasarframework/quasar-cli/issues/203), doesn't work either. 

**Codepen/jsFiddle/Codesandbox (required)**
Can't because it is my private API with weclapp.com. 
But the error is well known in the quasar community without any proper solution, potentially being shrugged off as backend serverproblem.

**To Reproduce**
1. make vue instance with API request other than openweather ;) -> has to violate CORS policy (two different ports!)
2. try to send request
3. fail
4. try to implement headers (as above) or even try to implement cors as described by Razvan previously (also doesn't work)
5. fail
6. install Chrome CORS Unblock
7. Successfully send request

**Expected behavior**
Successful request by bypassing CORS policy, so one of the following settings made in devServer works: headers, proxy, whitlisting via allowedHost, cors npm

**Platform used**
MacOS, Chrome, Quasar, NPM - dev mode, starting quasar with "quasar dev"

**Comment by Christo1101** [comment]
Wrong. 
The devServer doesn't even react to changes of the port from e.g. 8080 to 8081 - meaning, there must be a default-setting or something that inhibits the quasar.conf.js from being read properly.

devServer: {
      https: false,
      port: 8081,
      open: true
}

**Comment by yuwade** [comment]
i see

**Comment by yuwade** [comment]
1. quasar.config.js 
 devServer: {
      proxy: {
        '/api': 'http://127.0.0.1:7001',
      },
    },
2. axios
const api = axios.create();  //** don't set baseURL
api.get("/api/test").then((data) => {
  console.log(data)
})
