### ISSUE TITLE
q-input validation adds unnecessary spacing at bottom

### ISSUE THREAD

**Issue by joppehoekstra** [quasarframework/quasar#7717]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by joppehoekstra** [comment]
Excuse me, I accidentally posted the issue before finishing it. It has been updated now.

**Comment by rstoenescu** [comment]
The padding is on purpose because otherwise the content would wiggle, which is not what we want.

**Comment by joppehoekstra** [comment]
Alright, well, I prefer wiggling content instead of my required input fields being spaced more than input fields without validation. I'll just add the CSS code I wrote above to my project then.
