### ISSUE TITLE
Option to hide "Records per page" control in QTable

### ISSUE THREAD

**Issue by jeangomes** [quasarframework/quasar#7718]
**Is your feature request related to a problem? Please describe.**
I see the need to have more power in personalize the pagination controls.

**Describe the solution you'd like**
Hide "Records per page" select control, an option to show one fixed quantity without possibility to change.

**Describe alternatives you've considered**
Personalize in slots.

**Additional context**
I use this prop :rows-per-page-options="[15]" with a unique value, and control disappear.

**Comment by rstoenescu** [comment]
Hi,

There's "pagination" slot. And there's also the "pagination-label" prop.
Please check the QTable API card.

**Comment by jeangomes** [comment]
Thanks.
I use the "pagination-label" prop, is nice.
But the slot "pagination", as in the doc, I was able to modify the navigation controls, not the control in question.
https://quasar.dev/vue-components/table#Pagination-slot
I don't see the way.
