### ISSUE TITLE
QMenu not closing when clicking within iframe.

### ISSUE THREAD

**Issue by rulrok** [quasarframework/quasar#7719]
**Describe the bug**
The `q-menu` does not get closed when I click on an iframe. Even using `v-close-popup` on it does not help.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/rulrok/gxLzjpw0/4/

**To Reproduce**
1. Click on the button
2. The menu list will appear
3. Click on the iframe
4. The menu will stay

**Expected behavior**
The menu would disappear just like when I click anywhere else on the page (outside the iframe)

**Platform (please complete the following information):**
OS: Linux
Node: 14.8.0
NPM: 6.14.8
Yarn: --
Browsers: chrome
iOS: --
Android: --
Electron: --

**Comment by pdanpdan** [comment]
Hello. This is normal and expected. You are interacting with another window, it's like you are clicking in another application.
What you can do is to add logic in your iframe to communicate with the main application and tell it to close the menu, but it's not very easy to do and requires control of both parent and child content.
