### ISSUE TITLE
Specifing `:before` parameter inline on  `q-input` of `type="password"` causes unexpected behavior

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar#772]
### Software version

Quasar: v14 beta
OS: Window
Node:
NPM:
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

Specifying `:before` atribute inline causes unexpected behavior, including loss of focus on q-input after introducing the first character

### What were you expecting?

Normal q-input behavior

### What steps did you take, to get the error?

Fresh quasar v14 beta install.
Use modified template from [the docs](http://beta.quasar-framework.org/components/input.html#Icon-buttons)

```
<q-input
  v-model="text"
  type="password"
  :before="[
    {
      icon: 'warning',
      handler () {
        // do something...
      }
    }
  ]"
/>
```

How to solve:

Bind `:before` to value in data

```
<q-input
  v-model="text"
  type="password"
  :before="before"
/>
...
data: function () {
  return {
    text: '',
    before: [
    {
      icon: 'warning',
      handler () {
        // do something...
      }
    }
  ]
  }
}
```

Adding a `:after` attribute bound to a property of the data object also solves the issue

**Comment by rstoenescu** [comment]
This has to do entirely with Vue. On what Vue version are you on?

**Comment by rof20004** [comment]
I have this error, this is my dependencies, on package.json:

```
"dependencies": {
    "babel-runtime": "^6.0.0",
    "quasar-extras": "0.x",
    "quasar-framework": "git+https://git@github.com/quasarframework/quasar-edge.git",
    "vue": "~2.3.0",
    "vue-router": "^2.0.0"
  }
```

**Comment by rstoenescu** [comment]
Are you sure the `handler` method's content can be inline per Vue rules? For example, using the following handler inline will generate error:

```js
handler () {
  console.log('bla bla')
}
```

Please reopen with full handler() code. Thanks!

**Comment by BenoitRanque** [comment]
```
template>
  <div>
    <q-input v-model="password" type="password" :before="[ { icon: 'warning', handler: hand }, { icon: 'lock' } ]"/>
  </div>
</template>

<script>
import { QInput } from 'quasar'
export default {
  name: 'login',
  components: {
    QInput
  },
  data () {
    return {
      password: '',
      before: [ { icon: 'warning', handler: () => {} } ]
    }
  },
  methods: {
    hand: function () {
      console.log('hand')
    }
  }
}
</script>
```

click on warning icon will trigger handler as expected

**Comment by rstoenescu** [comment]
So is there an issue or not? :)

**Comment by BenoitRanque** [comment]
There is. Focus on input is lost after input of 1 character.
