### ISSUE TITLE
using $q.electron in Electron app throws an error

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#7721]
**Describe the bug**
<div> {{$q.electron}} </div> throws an exception
**[Vue warn]: Error in render: "TypeError: Converting circular structure to JSON** 

**Platform (please complete the following information):**
OS: win10
Electron: v10.1.0

**Comment by metalsadman** [comment]
@fprijate exactly like the error logs says, it has circular dependencies so you can't just print it as a string, if you want to check the object, try console logging it and see it in your devtool.
