### ISSUE TITLE
QDate - possibility to define value emit view level

### ISSUE THREAD

**Issue by mvandak** [quasarframework/quasar#7722]
**Is your feature request related to a problem? Please describe.**
In our solution we are using QDate in custom DatePicker to pick date that could have predefined format of value, whether it is year format, or year/month format or calendar format. So in case of picking date only in year format, we do not want to trigger view down from year to month and to calendar after selection in corresponding view. In case of year format, we want the value to be emitted after year click and do not want to change the view to Months or Calendar.

**Describe the solution you'd like**
QDate will have prop that will say what is the final view level that could be showed after value click in some view. E.g. if it will be set to "Years", only Years view will be displayed and after value selection, value will be emitted and no change of view to Months or Calendar will be processed.
In case of Months final view, it should be value emitted when value in Months view is selected. From Years view, user should be navigated to Months view after selection. No change from Months to Calendar view should processed.

**Describe alternatives you've considered**
Currently we have to manage it by our logic checking what was changed that is very tricky after adding navigation events and some changes that resulted in last 13.1 version. In some cases even no input, nor navigation events are emitted and we need to decide based on viewModel values after click event

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
