### ISSUE TITLE
[open PR] QTable table-bottom-style table-bottom-classes props

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#7723]
**Is your feature request related to a problem? Please describe.**
There's `table-header-style` and `table-header-classes` props, but no footer equivalents.

**Describe the solution you'd like**
`table-bottom-style` and `table-bottom-classes` props

**Describe alternatives you've considered**
targeting `.q-table__bottom`, with CSS.

but I'd rather not, because my header and footer need to look similar, and I'm using the `header-classes` already, so for consistence `footer-classes` make a lot of sense, and preventing the need for having to target inner classes is always a good thing!

**Additional context**
Semi related to #7570 but I don't need a custom slot, and solving this with custom slot content seems overkill. : )

**Comment by mesqueeb** [comment]
I have updated the request to say `table-bottom-classes` instead of `footer-classes` to be in line with the syntax already used for the table footer so far.

I have also determined that the change would probably need to be implemented around here:

https://github.com/mesqueeb/quasar/blob/origindev/ui/src/components/table/table-bottom.js#L45

but I'm still thinking of the best way

**Comment by mesqueeb** [comment]
Opened a PR!
### 🎉

**Comment by rstoenescu** [comment]
Hi,

This is interesting, but let's not go wild with class/style props, as long as you can add a class on the QTable and target whatever div needs the custom design. Something more is not always better. And it opens the pandora's box for god knows what other div within the QTable. I appreciate your PRs, but I am going to close this one. Sorry.
