### ISSUE TITLE
table sorting icon 

### ISSUE THREAD

**Issue by raghuvarbisht** [quasarframework/quasar#7725]
For table header sorting icon, i have two requirements.
1- Align the sorting icon left and it should visible by default for every column.
2- How i can use my own svg icon for the same also change icon color when hovering on the column header?
pleas find link for image how i want.

https://github.com/raghuvarbisht/quasar-custom/blob/master/src/assets/tabledesign.png

**Comment by raghuvarbisht** [comment]
Can you help on the same?

**Comment by ontwikkelfabriek** [comment]
You should post implementation questions on the Quasar forum. You'll get better support there for non-bugs.

**Comment by pdanpdan** [comment]
Please use the discord channel or the forum for help requests.
