### ISSUE TITLE
slot for stepper header

### ISSUE THREAD

**Issue by raghuvarbisht** [quasarframework/quasar#7728]
Can we add slot for stpper header similar to navigation?
 <template v-slot:navigation>
        <q-stepper-navigation>

**Comment by rstoenescu** [comment]
Hi,

Sorry but we cannot add that. The component is designed to work with the same markup for both horizontal and vertical mode (which is no small feat) and to be able to dynamically change the orientation (again no small feat) AND to also work correctly on SSR given the before mentioned features (huge deal). Won't get into too many details, but bottom line is that we cannot supply a slot for the header navigation without breaking one of the actual features that are available.
