### ISSUE TITLE
QTable does not display all rows even if hide-pagination="true". Rows per page default is hard coded to 5

### ISSUE THREAD

**Issue by flowt-au** [quasarframework/quasar#7731]
**Describe the bug**
The rows per page default is hard coded to 5. If, like me as a noob, you set `hide-pagination="true"` because you know you will only have 10 or so rows in total, it still limits to 5 rows and of course without the pagination toolbar it is not immediately obvious why.

**To Reproduce**

    <q-table
      :data="eventList"
      :columns="columns"
      :hide-pagination="true"
      row-key="internalId"
    >

No matter how many rows there are you will only get a maximum of 5

**Expected behavior**
Either default to "infinite" or if `:hide-pagination="true"` then set to infinite. Or, update the docs to say what the default is for `rows-per-page-options`. The addition of ` :rows-per-page-options="[0]"` solved it. :-)

    <q-table
      :data="eventList"
      :columns="columns"
      :hide-pagination="true"
      :rows-per-page-options="[0]"   <=======
      row-key="internalId"
    >

Thanks. Loving Quasar. :-)

**Comment by rstoenescu** [comment]
Hi,

Hiding the pagination means exactly that. It doesn't allows the user to change the pagination (it's 100% under the developer's control). But it does not mean that it should affect the behavior, which you as a developer can control -- and that you did, through "rows-per-page-options" (first value is the default rows per page that is being used). You can also control it through the "pagination" prop (with or without sync modifier) when it has rowsPerPage or rowsPerPageOptions specified. Conceptually, what you did is the way to go. We shouldn't mix not displaying something with the actual inner configuration of that something. There might be people who want exactly 7 rows per page but also the pagination being hidden.

**Comment by murrah** [comment]
@rstoenescu : Thank you, yes I see. As a complete newcomer to both Quasar and Vue I didn't realise that, of course, there are programatic ways to control the pagination even if one can't see the UI for it. Doh!
Thanks again for this fantastic framework.
Murray

**Comment by rstoenescu** [comment]
Cheers and welcome to our community!
