### ISSUE TITLE
qDrawer in desktop mode

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7733]
**Is your feature request related to a problem? Please describe.**
When in desktop mode and above breakpoint, the drawer shows itself automatically but the user can't swipe to close it.
When In desktop mode below breakpoint, swiping works. (the default of the drawer is hidden ofcourse).

**Describe the solution you'd like**
When in desktop mode and above breakpoint, I want the drawer to show itself **but** with the option for the user to swipe to close (and then swipe to open).

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this. Fixed the docs. Will be available on the next deployment.

**Comment by rstoenescu** [comment]
Hi,

You can control the shown/hidden status of QDrawer through its model or through `show-if-above` Boolean prop. However, swiping is indeed only available when window width is below the configured breakpoint. This is a natural UX behavior for mobile devices (which have small screens), but not for desktop. Tipically, a "menu" button is used on desktops. I'm sorry, but we do not intend to change this.

**Comment by Amosss** [comment]
Thanks for replying. 
Reading your last comment, what was fixed in the docs then?
A menu button is used for mobiles,. with small screens, no?

**Comment by rstoenescu** [comment]
The initial docs with docs fixed was a mistake. Had a ton of tabs opened and posted here instead of another ticket :) Docs don't require any update. Please read the last post in isolation.
