### ISSUE TITLE
[docs] Wrong return type for Cookies.get on missing cookie

### ISSUE THREAD

**Issue by BenceSzalai** [quasarframework/quasar#7734]
The [Cookies documentation](https://github.com/quasarframework/quasar/blob/dev/docs/src/pages/quasar-plugins/cookies.md) says :
> When cookie is not set, the return value is `undefined`.

But [it looks like the actual return value](https://github.com/quasarframework/quasar/blob/dev/ui/src/plugins/Cookies.json#L21) for missing cookie is `null`.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting this. Fixed the docs. Will be available on the next deployment.
