### ISSUE TITLE
[Infinite Scroll] Combine standard behavior AND reverse

### ISSUE THREAD

**Issue by clement-berard** [quasarframework/quasar#7735]
Hello everyone!

I was wondering if there was a solution to have the Infinte Scroll component with bottom loading and top loading (the reverse mode)?

If you activate the reverse mode, then you lose the loading at the bottom of the page.

This would be very useful to avoid loading too many elements in the DOM.

Thanks in advance,

**Describe the solution you'd like**
no one for the moment :) but if anyone else is interested, or if anyone has an idea, then let's go!

**Describe alternatives you've considered**
no alternative. The `q-table` doesn't meet my requirements. 

**Additional context**
the goal is to reduce the printing of the elements on the DOM. After a while, the page becomes very heavy. Because the infinite is the infinite :) and I don't want to put the infinite on my page :D 

Kind regards

**Comment by rstoenescu** [comment]
Hi,

Quasar already has what you need.
You can use [QVirtualScroll](https://quasar.dev/vue-components/virtual-scroll). See "Generate items on the fly" (https://quasar.dev/vue-components/virtual-scroll#Example--Generate-items-on-the-fly) and also setting the scroll to a position (https://quasar.dev/vue-components/virtual-scroll#Scroll-to-position).
