### ISSUE TITLE
Compilation hangs if QBtn @click contains `await`

### ISSUE THREAD

**Issue by BenceSzalai** [quasarframework/quasar#7736]
**Describe the bug**
Compilation hangs up at 100% done if one adds `@click="await any_method()"` to a `QBtn`.

While it is incorrect in fact, one would expect the compiler:
* display some kind of an error
* do not hang up
* continue watching files (when running `dev`)

Instead the compiler:
* shows no error
* stops with this on the console:
```
...
 App · Generating Webpack entry point
 App · Booting up...

 • Compiling:
 └── SPA ████████████████████ 100% done in 6507 ms

```
* stops watching changes (if e.g. running `dev` job)

I haven't tested with many components, only found this issue with `QBtn`. As for comparison, if I add similar invalid `await somefunction()` to a `QTooltip` component, Quasar shows this:
```
 ERROR  Failed to compile with 1 errors                                                                                                         5:10:39 PM

 error  in ./src/components/global/ToolbarMenu.vue?vue&type=template&id=2d42b9fe&

Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) 

  Errors compiling template:

  avoid using JavaScript keyword as property name: "await"
  Raw expression: @click="await test()"
```

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/sbnc_eu/pen/Vwayzdg
Please note that in CodePen there's no visible difference between `QBtn` and `QTooltip` behaviour, as no compilation is happening.

**To Reproduce**
1. Create a `QBtn` component as follows:
`<q-btn label="Test" @click="await notify"></q-btn>`
2. Run the `dev` npm script.
3. Observe freeze once compilation reaches 100%.

**Expected behavior**
See above in issue description.

**Platform (please complete the following information):**
Quasar: v2.0.8
OS: MacOS v10.14.6
Node: Tested on both v8.17.0 and v12.18.2
NPM: v6.14.5
Yarn: v1.22.4
Browsers: not related
iOS: not related
Android: not related
Electron: not related

**Comment by rstoenescu** [comment]
Hi,

This logic is part of the vue-loader. Please open a ticket on their repo. Thanks.

**Comment by BenceSzalai** [comment]
Thanks!

**Comment by BenceSzalai** [comment]
Just for the record: analysed further and it is in fact not at all related to QBtn, but using `await` in an `@method` attribute on a component passed into a named slot.

Reported to vue-loader here: https://github.com/vuejs/vue-loader/issues/1722

**Comment by BenceSzalai** [comment]
Sorry for bothering still, but provided I've got more info on the issue, let me ask:

Shouldn't Quasar be able to handle the case if `vue-loader` crashes with a `syntax error` without returning a proper error?

**Comment by rstoenescu** [comment]
Quasar reports all errors. If an error isn't reported, it's not our fault, but a subpackage misbehaving. Obviously, we won't monkey patch packages. We want the bug to be fixed at the source so the whole opensource community using that subpackage can benefit.
