### ISSUE TITLE
Need to disabled year navigation

### ISSUE THREAD

**Issue by masidiq** [quasarframework/quasar#7737]
**Is your feature request related to a problem? Please describe.**
I use the latest quasar. 
The day of my datepicker available only up to 2 year. For departure date / return date

**Describe the solution you'd like**
I want to disable or hide the year navigation on datepicker, but it still can navigate year at month view.
Im googling it, its like the old version quasar v.0.17.20

**Describe alternatives you've considered**
My current solution is hide the navigation arrow button by css

**Additional context**
Latest version quasar
![current datepicker](https://user-images.githubusercontent.com/7765289/92329688-45323b00-f093-11ea-8a46-f5a0df17f261.PNG)

I want the q-date like this one (old version quasar, v0.17.20)
![request disable navigation year](https://user-images.githubusercontent.com/7765289/92329700-554a1a80-f093-11ea-97bc-0c119d61d360.PNG)

My current solution (hide the arrow by css)
![current solution](https://user-images.githubusercontent.com/7765289/92329859-9131af80-f094-11ea-997c-738911e4841c.PNG)

Many Thanks

**Comment by rstoenescu** [comment]
Hi,

You don't need to hide the arrows through CSS. Use the new props navigation-min-year-month and navigation-max-year-month.
