### ISSUE TITLE
[umd] v1.13.2 broke time picker hour-options and minute-options

### ISSUE THREAD

**Issue by aarela** [quasarframework/quasar#7738]
Starting from version 1.13.2 it's impossible to select any hours/minutes, if q-time has hour-options or minute-options defined.

**Comment by rstoenescu** [comment]
Hi,

Seems to be working. What platforms are you testing on?

**Comment by aarela** [comment]
I use UMD platform.
Made little fiddle to demonstrate problem i have:
with version 1.13.1 https://jsfiddle.net/qw63fd1s/25/ (everything works)
with version 1.13.2 https://jsfiddle.net/qw63fd1s/24/ (can't choose hours or minutes)

**Comment by rstoenescu** [comment]
Ok, so you're using UMD. We eliminate the cordova/electron/bex/capacitor from the equation. But I was asking for the browser with which you are testing (and the OS if it's a mobile platform).

**Comment by rstoenescu** [comment]
Nevermind. Reproduced with the UMD version (only).

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v1.13.3
