### ISSUE TITLE
RTL theme override custom app.variables

### ISSUE THREAD

**Issue by netanelwebzi** [quasarframework/quasar#774]
Im trying to customize the app.variables.styl and its working when I dont import the rtl.css file.
When I import the rtl.css file all the app.variables are override.

**Comment by rstoenescu** [comment]
The order of imports in your app is wrong. Initialize a new Quasar app folder and follow main.js imports order from there.
Pls reopen if something is still wrong. RTL support is still experimental and not yet officially released a stable version.
