### ISSUE TITLE
Setting default-view to Months always navigates to date after year selection

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#7740]
I am using QDate to implement a month selection, so I used the infos found to do this (enabling emit-immediately and close the date selection (Its a Q-popup-proxy) on month selection and setting default-view to Months).

But if I go to the year selection and select a new year the component changes to the date view.

If I set the default-view to Years, the year selection changes to the month selection like I want it to do.
But most of the time the user just wants to change the month so it is impractical to always let them first select a year and then a month.

https://jsfiddle.net/jkfn0yw5/7/

1. In the first date-picker select a year and it changes to the months
2. In the second date-picker click on the first ---- to change to the year selection
3. In the second date-picker select a year

It is possible to configure the QDate that regardless of the default-view after a year selection the month selection appears

**Comment by rstoenescu** [comment]
Hi,

A month selection is perfectly equivalent with a QSelect with the 12 options. I'm sorry but we will not increase the complexity of QDate when there's a better solution.

**Comment by chaosKP** [comment]
But I also want to be able to select the year.
So I should use a dropdown for the months and a textfield for the year or how is there a better way to select year and month without day?
