### ISSUE TITLE
Disable click on subtitle navigation to the date selection

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#7741]
I am using QDate to implement a month selection, so I am closing my date popup on @input if the reason is month.
I am also setting the sub-title to a costum value because I only want the month info there without the date.
But if I click on the sub-title I am navigated to the date selection which I obviously don't want.
It is not possible to disable this behaviour.

An alternative would be to configure it so that the component navigates to the month selection instead.

**Comment by rstoenescu** [comment]
Hi,

A month selection is perfectly equivalent with a QSelect with the 12 options. I'm sorry but we will not increase the complexity of QDate when there's a better solution.

**Comment by chaosKP** [comment]
But I also want to be able to select the year.
So I should use a dropdown for the months and a textfield for the year or how is there a better way to select year and month without day?
