### ISSUE TITLE
Horizontal Expansion Item

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#7743]
**Is your feature request related to a problem? Please describe.**
I have a requirement to create a form like this, with steps. 
![obraz](https://user-images.githubusercontent.com/9776384/92440537-f7a9f100-f1ac-11ea-85cc-1a0b0617873e.png)
Naturally i would use a QStepper for this, but i think it might be easier for you to implement this in https://quasar.dev/vue-components/expansion-item#Basic first.
So i want the expansion items to slide horizontally, not vertically. 

**Describe the solution you'd like**
I would like to have a **horizontal** prop. 

**Describe alternatives you've considered**
I would like to have this in a Stepper but i think it will be easier for you to do it here (first). 

**Additional context**
I feedback will be positive i will add an ticket for the same in the QStepper, as this would be my preferred solution.

**Comment by pratik227** [comment]
@robert-niestroj  I think Jeff Galbraith (hawkeye64) is working on that extension.

Link - https://github.com/hawkeye64/quasar-ui-qverticalexpansionitem

**Comment by rstoenescu** [comment]
Hi. Please follow the UI AE link indicated above my comment.

**Comment by irux** [comment]
do you have something like this in your roadmap ?
