### ISSUE TITLE
QRadio/QCheckbox/QToggle selecting label text

### ISSUE THREAD

**Issue by datyin** [quasarframework/quasar#7744]
**Describe the bug**
Clicking same QToggle multiple times selects label text on Chrome & Edge, but works fine on Firefox

**To Reproduce**
1. Click 2+ times on QToggle component while using chrome/edge

**Screenshots**
[Imgur](https://imgur.com/zjxSd3O)

**Platform (please complete the following information):**
Browsers: Chrome Version 85.0.4183.83 (Official Build) (64-bit) / Edge Version 85.0.564.44 (Official build) (64-bit)

**Comment by OtabekSadiridinov** [comment]
For now, you can use ``<q-toggle style="user-select: none"></q-toggle>``.
But, I think, you've already tried that.

**Comment by rstoenescu** [comment]
Hi,

From a framework perspective, we cannot disallow text selecting. The label content can be anything and maybe devs want users to be able to select text, or depending on the content then the selection might actually be necessary.

**Comment by datyin** [comment]
@rstoenescu I'm not saying users shouldn't be able to select text. But the text shouldn't be selected while clicking toggle button.
Here is example:
Left is youtube, Right is quasar
[Imgur](https://imgur.com/Tl5nTpb)

**Comment by rstoenescu** [comment]
Thanks for insisting on this.
Found a way to fix the whole gang (QRadio/QCheckbox/QToggle).

Will be available in Quasar v1.13.3.
