### ISSUE TITLE
QSelect is missing a click handler on text in Safari

### ISSUE THREAD

**Issue by jjeising** [quasarframework/quasar#7745]
**Describe the bug**
QSelect options cannot be selected in Safari, if the text is clicked.

**To Reproduce**
1. Open Safari, go to https://quasar.dev/vue-components/select
2. Scroll to a QSelect with multiple options
3. Try to select one of the options, clicking on the Text or close around the text
4. Option is not selected, nothing happens, sometimes the text is selected

**Expected behavior**
Option is always selected.

**Screenshots**
https://www.dropbox.com/s/7dkdxiniz05kcww/qselect.mov?dl=0

**Platform (please complete the following information):**
Quasar: 1.13.2
OS: macOS 10.14.6
Browsers: Safari 13.1.2

**Additional context**
Similar issue was already reported #5431

**Comment by rstoenescu** [comment]
Hi,

Tested with Safari -> Version 13.1 (15609.1.20.111.8)
Cannot reproduce....

**Comment by jjeising** [comment]
Safari Version 13.1.2 (14609.3.5.1.5)
Also happens in a private window without content blockers. Reproducible with mouse and trackpad.

Any ideas how to narrow this down?

**Comment by jjeising** [comment]
Disabling/Enabling extensions and restarting Safari fixed this, while it was reproducible on multiple independent pages with Quasar before. Really strange issue, I will reopen this if there is anything new.
