### ISSUE TITLE
Q-col-gutter is not working.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [quasarframework/quasar#7746]
**Describe the bug**
I was just trying to display 4 QCards with some margin between them like this:
![image](https://user-images.githubusercontent.com/60849894/92471608-a6702080-f1f1-11ea-91b4-bc9892c42fc2.png)
And I write code like below:

```html
<div class="row q-col-gutter-md">
    <q-card class="col-3" v-for="n in 8" :key="n">
        <q-card-section>
            .........
        </q-card-section>
    </q-card>
</div>
```
And you said **q-col-gutter is used if children has col-**....
![image](https://user-images.githubusercontent.com/60849894/92471456-690b9300-f1f1-11ea-87f1-5dbd5efb706e.png)

But the result is:
![image](https://user-images.githubusercontent.com/60849894/92472016-534a9d80-f1f2-11ea-8114-4857e6a3e872.png)
Or:
![image](https://user-images.githubusercontent.com/60849894/92472202-9a389300-f1f2-11ea-8643-5a5c7690939c.png)

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/nervous-browser-xfyq8?file=/src/pages/Index.vue

**To Reproduce**
1. Go to the above codesandbox link
2. Then see it's not working.

Is it a bug?

**Expected behavior**
Expected to see as the first wireframelike image.

**Screenshots**
Screenshots are shown above when needed.

**Platform (please complete the following information):**
OS: Windows 10, Linux(Ubutnu 2020 focal fossa)
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
I hope, I'll get answer soon. Thank you.

**Comment by Darxan** [comment]
It is not working on my project too. 
I'm using last version of quasar :(😒

**Comment by OtabekSadiridinov** [comment]
@Darxan No need of thinking more. Just adding inner div makes it to work. Otherwise it overlaps content. If we add additional div space will be added and just it works. Look this sample:
```html
<template>
  <q-page padding>
    <div class="row q-col-gutter-md">
      <div class="col-3" v-for="n in 5" :key="`xl-${n}`">
        <div class="my-content">&nbsp;</div>
      </div>
    </div>
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex'
}
</script>

<style lang="sass" scoped>
.my-content
  background: rgba(86,61,124,.15)
  border: 1px solid rgba(86,61,124,.2)
</style>
```

Thank you all. Closing the issue.

**Comment by rstoenescu** [comment]
Inner divs with "col-*" are required. This is by design. No other way around it.

**Comment by userpta005** [comment]
Quasar's q-gutter and q-col-gutter is horrible.
I encourage everyone to stop using them and use a CSS gap class generator function.

```
$sizes: (
  none: 0,
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 48,
);

@each $key, $value in $sizes {
  .q-gap-#{$key} {
    gap: #{$value}px;
  }

  .q-gap-x-#{$key} {
    column-gap: #{$value}px;
  }

  .q-gap-y-#{$key} {
    row-gap: #{$value}px;
  }
}
```

**Comment by rstoenescu** [comment]
@userpta005 Hi, if you think it's horrible then you haven't grasped it yet. Please read the docs thoroughly.

**Comment by Tenrys** [comment]
I would like to know though, why is there no support for CSS gaps at all? What's different between those and the gutter system?

**Comment by rstoenescu** [comment]
No harm in using gaps, it's just that this piece was written when grid didn't exist. However, doing a change to it now will mean a breaking change. However, Quasar v3 will use gaps.

**Comment by AlexDaniel** [comment]
@rstoenescu but maybe there's value in providing a new gap-based flex layout in Quasar v2? Or even, indeed, a .q-gap alternative that can be used instead of q-gutter? This way the breaking change won't be as breaking.

**Comment by kalebberry** [comment]
I am glad I am not the only who was wondering why q-gutter doesn't make sesne, when using flexbox or grid. I was confused why margins where being used, instead of using col-gap or gap. CSS has tons of changes since 2020, that makes this 10x easier.

**Comment by AlexDaniel** [comment]
Well, back in the day quasar grid was a godsend. The way it works, indeed, is not intuitive and you need to understand what it actually does in order for it to make sense. At the end of the day you'll be just wrapping everything in extra divs because that's what you have to do. It's not that unintuitive afterwards, and it gets the job done.

Today, yeah, you don't need all the negative margin magic. Just set a `gap` in your flexbox and you're done. We're considering to adopt Quasar in 2024 and now I'm wondering if we should use the quasar grid, or if instead we should use plain flexboxes (which is probably somewhat easier). 🤷🏼

**Comment by kalebberry** [comment]
I remember those days. ahahaha, creating systesm with math and percentages. But, honestly, the quasar grid and flex is wonderful. I think it just honestly need just to add a gap class. Spacing is key when it comes to design. I was kinda suprised gap wasn't in yet, which let me here. I don't think it needs much, the more intrinsic quasar is the better.

**Comment by otabekoff** [comment]
> I remember those days. ahahaha, creating systesm with math and percentages. But, honestly, the quasar grid and flex is wonderful. I think it just honestly need just to add a gap class. Spacing is key when it comes to design. I was kinda suprised gap wasn't in yet, which let me here. I don't think it needs much, the more intrinsic quasar is the better.

@kalebberry And yeah, I think so too. However, they stuck very hard to the Material Design System. When Quasar 3 comes no one knows. I hope many features from Quasar V3.
