### ISSUE TITLE
Can we change Vue Delimiters from "{{" "}}" to "<%" "%>" in Quasar

### ISSUE THREAD

**Issue by sanketbajoria** [quasarframework/quasar#7747]
I would like to change Vue delimiters. Can we do it in Quasar.

Please help me with this.

**Comment by rstoenescu** [comment]
Hi,

Create a [boot file](https://quasar.dev/quasar-cli/boot-files). Changing delimiters is described on [Vuejs documentation](https://vuejs.org/v2/api/#delimiters). One of the parameters that you'll be receiving there is "app", which is the options Object with which Quasar App CLI instantiates the Vue object.

```
export default async ({ app }) => {
  app.delimiters = [ '${', '}' ]
}
