### ISSUE TITLE
Make QStepper header-class prop to accept an array

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#7748]
**Is your feature request related to a problem? Please describe.**
The `header-class` prop of the QStepper accepts only a string. 

**Describe the solution you'd like**
I would like it to accept an Array also

**Additional context**
I thought it was intended like this. Maybe it's a bug. But the docs say only it accepts a string. 
Codepen: https://codepen.io/robert-niestroj/pen/XWdZOjZ

**Comment by pianopronto** [comment]
This is the proper way to add multiple classes:

`header-class="text-bold text-capitalize"`

**Comment by rstoenescu** [comment]
Like @pianopronto said (thx for jumping in).
