### ISSUE TITLE
Add active-bg-color prop for QStepper

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#7749]
**Is your feature request related to a problem? Please describe.**
They want me to change the bg color of inactive steps. I mean in the header/nav. 

**Describe the solution you'd like**
Add an `active-bg-color` prop just like in QTabs.

**Comment by rstoenescu** [comment]
Hi,

Please use CSS for this one. Target `.q-stepper__tab:not(.q-stepper__tab--active)`. We can't add endless props for styling. We need to draw a line somewhere or else each component would have 500+ such props. We've designed the components to be REALLY easy to customize should such need arise.
