### ISSUE TITLE
"quasar dev" have different result compared "quasar build"

### ISSUE THREAD

**Issue by johncloud200** [quasarframework/quasar#775]
![untitled](https://user-images.githubusercontent.com/29952776/29004438-17874846-7af1-11e7-9f73-ff15ca5529b6.png)

Why "quasar dev" have different result compared "quasar build"
I use "q-table bordered cell-delimiter striped-even responsive fit"
[here my example code](https://github.com/johncloud200/quasartest/blob/master/src/views/Dashboard.vue)

**Comment by a47ae** [comment]
Can confirm this issue with the example repo.
The breakpoints are missing from the prod build.
If the `purifyCSS` variable is set to `false` it works as expected.

**Comment by a47ae** [comment]
Maybe it has to do with this issue in purifycss 
https://github.com/purifycss/purifycss/issues/161

**Comment by guyulmaz** [comment]
as workaround
inside css-utils.js you can add
`purify(js, [file], {minify: true, whitelist: [ '*:not*' ]}, function (purified) {`
this is mentioned in
https://github.com/purifycss/purifycss/issues/161

**Comment by matheus-rossi** [comment]
thanks @guyulmaz , solved my problem in q-table ...

**Comment by rstoenescu** [comment]
This is no longer a problem for v0.15 (along with new CLI and starter kit, so closing this).
