### ISSUE TITLE
Q-Table: The "filteredSortedRows"-property does not contain the expected rows when sorting by a column

### ISSUE THREAD

**Issue by FabShaw** [quasarframework/quasar#7752]
**Describe the bug**
Hey guys, I have a problem with q-table: 
The "filteredSortedRows"-property (referenced by the "Custom-Multiple-Selection"-Example in Quasar Docs:  https://quasar.dev/vue-components/table#Example--Custom-multiple-selection) doesn't contain the expected rows after I sorted by a column. It seem like it only contains the first page of q-table.

Background: I have to export the sorted and filtered table-data as CSV-File...

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/FabShaw/pen/ExKwZaN

**To Reproduce**
Look at bottom of Codepen-Snippet

**Expected behavior**
The filteredSortedRows"-property should contain the rows that are shown by q-table.

**Screenshots**
-

**Platform (please complete the following information):**
OS: Windows 10
Node: 10.22
NPM: 6.14.6
Yarn: -
Browsers: Current Chrome, Firefox, Edge
iOS: -
Android: - 
Electron: -

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v1.13.3.

**Comment by FabShaw** [comment]
It's incredible how quickly you solved my problem. 
Thanks a lot!
