### ISSUE TITLE
Morph directive - morphs one way but not the other while routing.

### ISSUE THREAD

**Issue by megamidge** [quasarframework/quasar#7754]
**Describe the bug**
2 routes present. One has an image in the middle (A), the other has an image in the top bar (B). Routing from A to B, the morph between the two images occurs. Routing from B to A, the morphing does not occur. If B is loaded first, the **first** routing from B to A has the morph happen. Any subsequent routing from B to A, the morph doesn't happen. The morph always happens when going from A to B.

**Codepen/jsFiddle/Codesandbox (required)**
[Codepen](https://codepen.io/MrBeletal/pen/oNxqgrM)
[Github Repo](https://github.com/megamidge/QuasarMorphRouteExample)

**To Reproduce**
1. Apply a v-morph directive to an element on route A. Apply a v-morph to an element in the top bar on route B.
2. ``quasar dev``
3. Navigate between the routes
4. Observe that morph animation occurs from A to B, not B to A

**Expected behavior**
The morphing animation happens when routing from A to B **and** when routing from B to A. The morphing happens both ways.

**Screenshots**
https://i.imgur.com/BFPyjSn.gif
Gif shows clicking to go from route A to route B - morph occurs. Clicking 'GO TO HOME' shows the morphing element jump instead of morph.

**Platform (please complete the following information):**
OS: Windows 10 Build 19041
Node: v12.18.3
Yarn: v1.22.5
Browsers: Brave, Edge, Chrome

**Comment by rstoenescu** [comment]
Hi,

You're using the directive incorrectly. You need individual elements with v-morph attached to the same morph group. Then you can switch from one to the other (and also backwards). In the codepen I can see that you are using only one element (with "topimg" as morph name in the "logogroup" morph group) then you switch the morph model to/from "topimg"/"homeimg". There's no morph element registered with "homeimg".

<div v-morph:topimg:logogroup="model" ....
<div v-morph:homeimg:logogroup="model" ...
where "model" is either "topimg" or "homeimg"

**Comment by megamidge** [comment]
Hi,
Respectfully, you are mistaken.

There is an element with 'homeimg' as morph name - in the codepen, line 6 of the JS, in a template.
This element is the paragraph tag that contains the text "Logo" on the page that shows the title "Home". If it did not exist, then the element with morph name 'topimg' would not have anywhere to morph from.

The same can be said for the gitrepo i linked as example too, however the homeimg variant is named 'main' and isn't an in-line template, but rather part of a fully-fledged component.

If you re-read the example(s), you'll see that 2 elements with 2 different morph names, in the same morph group, do exist. 

Can you verify that when you run the codepen, you see the text 'logo' morph from its initial position on the 'home' route, to a different position on the 'other' route, and then upon going back to the 'home' route, instead of morphing it just jumps.

**Comment by rstoenescu** [comment]
I see now. Sorry for missing that.
However, the "homeimg" element only exists while in the "home" route. Both morphing elements must exist while transitioning. When you switch from "home" route the "homeimg" morph element gets destroyed.

**Comment by megamidge** [comment]
Ah, that might be the kicker then, gotcha.
So in this case, when going from 'other' to 'home, because the 'homeimg' element doesn't yet exist, the morph operation can't actually happen because it doesn't know where its morphing to? But it can morph from 'home' to 'other', because when the morph is trigger, the 'homeimg' element exists (albeit for only a moment), so it has chance to figure out a starting position to morph from. The only reason the morph from 'home' to 'other' is working is because 'topimg' is present no matter the route. Hopefully i'm understanding this correctly?

I'm guessing the delay you can add doesn't delay the triggering/finding the elements to transition from/to, so the best way to go about this particular case would be the Morph function? Then in cases where the elements never exist in tandem (elements in separate routes), the morph function would have to be triggered with some light fudging (likely faking the 'from' element manually or something). Either way i'll do some experimenting because i think a major use case for the morphing is to make transitions between pages (routes) much more fluid and native-like.

Thanks for clearing that little detail out though, much appreciated.
