### ISSUE TITLE
[docs] Icongenie padding docs might need update

### ISSUE THREAD

**Issue by sluedecke** [quasarframework/quasar#7755]
According to icongenie docs, padding can be an arbitrary value, but in https://github.com/quasarframework/quasar/issues/7750 it was said that favicons are 16x16 thus not allowing for a padding of 10,5.  

https://github.com/quasarframework/quasar/blob/dev/icongenie/bin/icongenie-generate#L104, line 104ff:
```
    --padding             Apply fixed padding to the icon after trimming it;
                          Syntax: <horiz: number>,<vert: number>
                          Default: 0,0
                          Example: "--padding 10,5" means apply 10px padding to top
                            10px to bottom, 5px to left side and 5px to rightside
```

Maybe padding can be expressed as a percentage (then it's not a doc issue)?

**Comment by rstoenescu** [comment]
Favicon**s** are not 16x16. There's only one.
Please wait for the next release, as indicated. Thank you.
