### ISSUE TITLE
quasar build --mode pwa -> TypeError: can't access property "screen", this.$q is undefined

### ISSUE THREAD

**Issue by mkungla** [quasarframework/quasar#7756]
**Describe the bug**
Building pwa resulting app throws into console `TypeError: can't access property "screen", this.$q is undefined` 

**To Reproduce**
1. Run 'quasar build --mode pwa'
2. Open app in browser
3. Open dev tools
4. See error `TypeError: can't access property "screen", this.$q is undefined`

**Platform (please complete the following information):**
OS: Fedora 32
Node: v12.18.3
NPM: 6.14.6
Browsers: Firefox 81.0b7

**Comment by rstoenescu** [comment]
Can you supply a reproduction repo (or https://codesandbox.quasar.dev) pls?
Otherwise this cannot be reproduced.

**Comment by rstoenescu** [comment]
Please reopen or comment here with the requested info. Thanks.

**Comment by mkungla** [comment]
confusing error occurred in  monorepo

**quasar.conf.js**

```
workboxPluginMode: 'InjectManifest'
```

**custom-service-worker.js** 

and when `custom-service-worker.js` was missing following  content.

```
import { precacheAndRoute } from 'workbox-precaching/precacheAndRoute'
precacheAndRoute(self.__WB_MANIFEST) 
```

**Comment by mkungla** [comment]
@rstoenescu can be reproduced when dynamically adding routes from npm package e.g.

```
  const { routes } = app.router.options
  const routeData = routes.find(r => r.path === '/')
  const currentRoutes = routeData.children.map(route => route.path)
  const newRoutes = [
    {
      path: '/somepath',
      name: 'somepath',
      component: () => import('npm-pkg/SomePath'),
    },
  ]
  routeData.children = []
  for (const route of newRoutes) {
    if (!currentRoutes.includes(route.path)) {
      routeData.children.push(route)
    }
  }
  app.router.addRoutes([routeData])
}
```

**Comment by rstoenescu** [comment]
@mkungla please provide a reproducible repo (or a https://codesandbox.quasar.dev), otherwise we can't make any progress with this ticket. Thanks in advance.
