### ISSUE TITLE
QTree skips composing keys in the header section which makes impossible to use spacebar in embedded input fields

### ISSUE THREAD

**Issue by althink** [quasarframework/quasar#7757]
**Describe the bug**
When input field is used in QTree (inside header of tree item) it's not possible to type a space by hitting spacebar, spacebar events are skipped.
Looks like this code is responsible for that behaviour (shouldIgnoreKey(e) !== true):

https://github.com/quasarframework/quasar/blob/edf50853a8a69ba109ff84165e6d3163ebab2a4a/ui/src/components/tree/QTree.js#L498

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/krzysztof-szczeniak/pen/KKzoaZx

**To Reproduce**
Steps to reproduce the behaviour:
1. Open sample in codepen
2. Click on the input field that's part of the item in QTree
3. Write some letters and then try to type space using spacebar
4. See that space is not added

**Expected behaviour**
Space should be added in input fields when user types by pressing spacebar

**Comment by rstoenescu** [comment]
Hi,

Just add a `@keypress.stop` to the QInput. No other way around it when using "unusual" content.
