### ISSUE TITLE
QBtnDropDown with split, type="a" href="...",  Clicking does not work

### ISSUE THREAD

**Issue by vajacn** [quasarframework/quasar#7758]
**Describe the bug**
QBtnDropDown with split,  `type="a" href="https://quasar.dev"`,  Clicking the main button does not work.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/vajacn/pen/ExKEwVo

**To Reproduce**
1. Click the main button
2. The specified URL is not opened

**Expected behavior**
Open the url like a hyper-link.

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fix will be available in Quasar v1.13.3.
