### ISSUE TITLE
QTree setExpanded not working from children nodes

### ISSUE THREAD

**Issue by luizhenriquerdias** [quasarframework/quasar#7761]
**Describe the bug**
QTree's setExpanded is not working from children nodes

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luizhenriquerdias/pen/xxVWjNP

**To Reproduce**
Just execute the codepen

**Expected behavior**
The tree should expanded until the node passed via parameter

**Comment by rstoenescu** [comment]
Hi,

Your usage is telling QTree to expand the respective node. And it's a leaf. You should expand all its parents until hitting root (which you should determine by analyzing the tree structure)...
