### ISSUE TITLE
APP V2 or COREJS 3 OR SOMETHING ELSE?? is making touchmove event VERY sluggish

### ISSUE THREAD

**Issue by VanderSP** [quasarframework/quasar#7762]
**Describe the bug**
touchmove event working in a very slow performance, but when you connect chrome inspect it goes fine!

PROJECTS FILES ATTACHED FOR V1 AND V2
[v2_touchmove_bug.zip](https://github.com/quasarframework/quasar/files/5204918/v2_touchmove_bug.zip)

**To Reproduce**
1. just touch move to scroll some element on mobile

**Expected behavior**
Smooth fast movement

**Platform (please complete the following information):**
OS: Android
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android: 9
Electron:

**Additional context**

Interestingly if you do it like a tween, it goes fast, so it´s not a dom performance thing... but something bizarre with touchmove, but i don´t know if it´s APP v2 or COREJS 3 that´s causing that, or even some other thing!

**Comment by VanderSP** [comment]
Probably totally related to: https://github.com/quasarframework/quasar/issues/7729

**Comment by rstoenescu** [comment]
Let's continue on the related ticket. Assuming that you're experiencing the same thing (slow QDrawer).
