### ISSUE TITLE
Option to hide first/last page button in QTable

### ISSUE THREAD

**Issue by squarer** [quasarframework/quasar#7764]
**Is your feature request related to a problem? Please describe.**
Just upgraded from 1.11 to 1.13, seems QTable shows first/last page button by default.
wonder if there is a option to hide the buttons, or should i go with pagination slot, thanks!

**Describe the solution you'd like**
Option to hide first/last page button in QTable.

**Comment by rstoenescu** [comment]
Hi,

Pagination slot is indeed the way to go.
