### ISSUE TITLE
[question] - select, filter and tagging in one component (or how to with select and chips)

### ISSUE THREAD

**Issue by gg4u** [quasarframework/quasar#7768]
I have spent quite some time to make use of this vue project https://vue-select.org/  that allows to select, filter and tag multiple items from a list of suggested results.

One challenge of external components is to adapt the look ad feel, but I would like to take the opportunity to learn how I could recreate a same behaviour by using native quasar components.

Eventually, I would like to suggest portability of this great component for quasar. 
My opinion of great is that search is a very important entry point for UX, and vue select is flexible on many aspects.
I think that having the possibility to combine tagging (chips) in quasar and select components would benefit developers with the flexibility to pass props and reuse native quasar components (like chips used as slots, when user select an item).

My use case is:

- user can query a server (ajax call)
- user can filter through suggested results 
- user can select multiple results (tags) and remove them (it would be great to use quasar chips)
- on a search, a query / action will be launched against all the selections

I am looking at:
https://quasar.dev/vue-components/select#Create-new-values

and 
https://quasar.dev/vue-components/chip#QChip-API

I'd be greatful if you could show a simple example that combine select and chips components, to achieve use case described above:

note that one challenge is to make appear the chips inside the input of the select : see the picture as an example

<img width="771" alt="Screen Shot 2020-09-13 at 2 17 00 PM" src="https://user-images.githubusercontent.com/284214/93017762-777bf500-f5cb-11ea-86c1-181b1f1527e4.png">

**Comment by smolinari** [comment]
Doesn't this fit the use case? https://quasar.dev/vue-components/select#Example--Filtering-and-adding-to-menu

Scott

**Comment by smolinari** [comment]
Also, in general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug or a good suggestion, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott

**Comment by gg4u** [comment]
@smolinari thank you for suggesting the discord channel! I am experimenting with the documentation right now.
