### ISSUE TITLE
QBtnToggle not working with QBadge when inserted in QToolbar and options refer a function

### ISSUE THREAD

**Issue by VIM-Arcange** [quasarframework/quasar#7769]
**Describe the bug**

I made some tests related to issue #7702
 
When 
- the QBtnToggle with QBadge is inserted in a QToolbar 
- the options properties refer to a function instead of a static code definition

then 
 - the QBadge is correctly displayed but the QBtnToggle isn't working anymore, i.e. clicking on any button has no effect.

**Codepen/jsFiddle/Codesandbox (required)**

[MainLayout.vue.txt](https://github.com/quasarframework/quasar/files/5215526/MainLayout.vue.txt)

**To Reproduce**
1. Create a project using `quasar create`
2. replace `MainLayout.vue` with the above-provided code
3. start the application and try to click on button "two" or "three"

**Expected behavior**
Clicking on a button should make it selected and toggle its color.

Commenting out the `<q-badge color="orange" floating>123</q-badge>` makes the buttons working back.
Defining option with static code makes the buttons working back:
```
:options="[
            {label: 'One', value: 'one'},
            {label: 'Two', value: 'two'},
            {label: 'Three', value: 'three'}
          ]"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/21260036/93033397-60262180-f636-11ea-931d-a61ffb7c5d27.png)

**Platform (please complete the following information):**
OS: Windows
Node: 12.18.2
NPM: 6.14.5
Browsers: Brave Version 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Comment by pdanpdan** [comment]
Hello.
Please create a codepen that shows the problem and reopen.
I'm sorry but we don't have time to save and play with files.
Thank you
