### ISSUE TITLE
[Request] Responsive image component aka QImage

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#777]
This proposes a new `QImage` component which handles responsive images.

To accomplish this, the HTML 5 `srcset` attribute could be used.

Also, it should be possible to include an appropriate webpack loader, like [the responsive loader](https://github.com/herrstucki/responsive-loader) to automatically generate scaled down images.

Initially, I thought about using the `picture` tag, but I think this only makes sense when you really want to serve different images on different viewports, which could not be automated and therefore would not make sense for its own component.

Forum discussion regarding this: http://forum.quasar-framework.org/topic/674/best-practice-for-responsive-images/

**Comment by BenoitRanque** [comment]
Here is a proposal. Please comment

Not making a pr since I do not think it is worth one yet.

```
<template lang="html">
  <img 
  :src="`/img/md/${src}`" 
  :alt="alt"
  :srcset="imgsrc"
  :sizes="imgsize"
  >
</template>

<script>
const xsBreakpoint = 576px,
  smBreakpoint = 768px,
  mdBreakpoint = 992px,
  lgBreakpoint = 1200px

export default {
  props: {
    src: {
      required: true,
      type: String
    },
    w: { // Width, in pixels, of our original image.
      required: true,
      type: Number
    },
    alt: {
      type: String
    },
    size: {
      type: Number
    },
    xsSize: {
      type: Number
    },
    smSize: {
      type: Number
    },
    mdSize: {
      type: Number
    },
    lgSize: {
      type: Number
    }
  },
  computed {
    imgsrc () {
      let imgsrc = ''

      imgsrc += `/img/lg/${this.src}.jpg ${this.w}w, `
      imgsrc += `/img/md/${this.src}.jpg ${this.w * 0.5}w, `
      imgsrc += `/img/sm/${this.src}.jpg ${this.w * 0.25}w`

      return imgsrc
    },
    imgsize () {
      let imgsize = ''

      if (this.xsSize !== undefined)  imgsize += `(max-width: ${xsBreakpoint}) ${this.xsSize}vw, `
      if (this.smSize !== undefined)  imgsize += `(max-width: ${smBreakpoint}) ${this.smSize}vw, `
      if (this.mdSize !== undefined)  imgsize += `(max-width: ${mdBreakpoint}) ${this.mdSize}vw, `
      if (this.lgSize !== undefined)  imgsize += `(max-width: ${lgBreakpoint}) ${this.lgSize}vw, `
      imgsize += `${this.size}vw`

      return imgsize
    }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Done for v1.0.

**Comment by mesqueeb** [comment]
I am wondering if it's possible to add a little bit of automation to responsive images.

Eg. I would love to be able to just set a src-image and Quasar automatically generating lower res versions for me, and adding them to srcset.

**Comment by BenoitRanque** [comment]
I have a project using sharp that generates the images automatically. Maybe the icon factory could help too. Would be nice to have as an optional plugin of some kind

**Comment by mesqueeb** [comment]
I think making different resolution images should be something that's recommended for all projects out there, no? 😃 in that case, if a plugin is ever made that does this, I'd vote to put it as a standard option QImage really. I bet 99% of people need this.

**Comment by mesqueeb** [comment]
Might also be related. Adding lazy loading to images by default: 
https://addyosmani.com/blog/lazy-loading/

**Comment by nothingismagick** [comment]
I opened a new issue @mesqueeb and @BenoitRanque over at the icon factory repo. Maybe we could continue the discussion there.

**Comment by mesqueeb** [comment]
@nothingismagick I understand that both this feature and the icon factory would use similar underlying technology. However, I think when people want to automate responsive images, I'm not sure it is intuitive they would look at the icon factory extension.

If this is to be added as an extension I would opt for a separate name, something like `quasar-app-extension-responsive-images` which feels like it more resembles what it does.

**Comment by mesqueeb** [comment]
I just wanna throw this in here for further **inspiration**.

Adding support for the [Intersection_Observer_API](https://developer.mozilla.org/docs/Web/API/Intersection_Observer_API) might be cool. That way images can be prevented from being downloaded if they don't come in the view. 

A similar package that does that is: [v-lazy-image](https://github.com/alexjoverm/v-lazy-image)

**Comment by mesqueeb** [comment]
Just leaving some relevant reading material in case anyone starts digging into this topic:
https://www.smashingmagazine.com/2019/05/hybrid-lazy-loading-progressive-migration-native/

**Comment by abullahatdefox** [comment]
![logo](https://user-images.githubusercontent.com/44596709/62510362-36da7580-b828-11e9-86bc-3f0f0c68dabb.png)
![summer](https://user-images.githubusercontent.com/44596709/62510370-3b069300-b828-11e9-92c0-786dc794bf38.jpg)
