### ISSUE TITLE
[docs] How to add a custom column to table

### ISSUE THREAD

**Issue by jonalxh** [quasarframework/quasar#7770]
Hi, I'm trying to add a custom column at the end of each row in my tables with some button options like delete, edit and show more, the problem is docs does not include examples of how to do it, I've tried reading all the table docs and I've found nothing, looking at the API slots there is not a column option.

How to achieve it?

**Comment by pratik227** [comment]
@jonalxh You can add let say action column and use that column for displaying add/edit Item buttons.

Example - https://codepen.io/Pratik__007/pen/eYNvvva

**Comment by jonalxh** [comment]
Thanks for your quick anwer, it worked very well.

Is it possible to add a section in Docs with Custom/Action Columns?

**Comment by ontwikkelfabriek** [comment]
> Thanks for your quick anwer, it worked very well.
> 
> Is it possible to add a section in Docs with Custom/Action Columns?

There already is a example with a custom column using slots:

https://quasar.dev/vue-components/table#Example--Body-cell-%5Bname%5D-slot

**Comment by jonalxh** [comment]
Yes, I remember I saw it, but in the example yo use existing columns, maybe it is important to show people that a new column can be added.

Thanks a lot.

**Comment by godtoy** [comment]
#7788 I think using slots to change column will write very cumbersome code and difficult to maintain ,hope it can customize the render
