### ISSUE TITLE
Quasar app not installing on my windows 10 system

### ISSUE THREAD

**Issue by laplus1** [quasarframework/quasar#7772]
C:\Users\MEDIA&I.T LFC>npm install -g @quasar/cli

┌────────────────────────────────────────────────────────────────────┐
│                      npm update check failed                       │
│                Try running with sudo or get access                 │
│                to the local update config store via                │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\MEDIA&I.T LFC\.config │
└────────────────────────────────────────────────────────────────────┘
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
C:\Users\MEDIA&I.T LFC\AppData\Roaming\npm\quasar -> C:\Users\MEDIA&I.T LFC\AppData\Roaming\npm\node_modules\@quasar\cli\bin\quasar
+ @quasar/cli@1.1.0
updated 1 package in 78.573s

┌────────────────────────────────────────────────────────────────────┐
│                      npm update check failed                       │
│                Try running with sudo or get access                 │
│                to the local update config store via                │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\MEDIA&I.T LFC\.config │
└────────────────────────────────────────────────────────────────────┘

C:\Users\MEDIA&I.T LFC>quasar upgrade -i
'I.T' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\MEDIA\node_modules\@quasar\cli\bin\quasar'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

C:\Users\MEDIA&I.T LFC>quasar create uzor_app -b dev
'I.T' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\MEDIA\node_modules\@quasar\cli\bin\quasar'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

C:\Users\MEDIA&I.T LFC>quasar info
'I.T' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\MEDIA\node_modules\@quasar\cli\bin\quasar'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by pdanpdan** [comment]
Try to use some normal paths. Do you have any kind of development working on your account? Try to use a shell/terminal that works with such paths.
Anyway there is nothing quasar can do to fix the problem.
