### ISSUE TITLE
[Question] What is the reasoning behing quasar palettes' {color}-[11|12|13|14] ?

### ISSUE THREAD

**Issue by rulrok** [quasarframework/quasar#7775]
For colors 1 through 10 it seems quite clear the intention: gradually changing the saturation.

But then it seems like at some point colors 11 through 14 have been added like that just not to introduce a breaking change for projects already using the 1-10 classes as 11-14 _seems_ to fit somewhere in the middle of them. Or if not, why are there not classes 11 through 20?

**[extra question]** Since we're already in the topic, is there any particular thought behind the stepping of colors from 1-10, or is it just like 'evenly spaced' around the base color?

![image](https://user-images.githubusercontent.com/3097987/93256176-56ed9f80-f771-11ea-9112-c6c22fff0bef.png)

**Comment by rstoenescu** [comment]
Hi,

The color palette is the Material one. The 1-10 represents evenly distributed colors around the base color. Then 11-14 are accent colors around the base one.
