### ISSUE TITLE
Customize elements with CSS

### ISSUE THREAD

**Issue by kentforth** [quasarframework/quasar#7776]
Quasar is great framework, but why it is so hard to modify elements with CSS?

Example: I like behavior of inputs in form component. but I don't like how it looks. I would like to change text color in input, it's border color and place holder. I can't do it with CSS

i tried to do it like:

```
-q-input {
color: green !important;
}
```

it doesn't work. I also tried to add to input my custom css class, and it is also doesn't work

Please add feature for customizing all elements in quasar

**Comment by pdanpdan** [comment]
Hello. You can customize everything you want by using CSS. Just check the styles for that component (or use inspector) and make your desired changes. The css you have in the issue makes no sense. Please make a codepen showing what you have tried and we will be able to help you.
But you should use the forum or the discord channel for help requests.

**Comment by kentforth** [comment]
Oh, I tried to modify wrong css classes=(
Thank you for fast answer!
