### ISSUE TITLE
[docs] Cannot change background colour of splash screen

### ISSUE THREAD

**Issue by enricribas** [quasarframework/quasar#7778]
Using icongenie CLI works great. However, when I build for cordova, the images are overwritten. 
I've changed the background colour setting and theme color setting in quasar.config.js under `pwa` and even under `cordova` with `manifest`->`theme_color`. 

How can I get the build to not create new icons and splashscreen on each deploy? I don't change the icons each build, or if I can't do that, how do I change the theme color for the build?

Thanks.

**Comment by rstoenescu** [comment]
Hi,

I don't think that you are using the IconGenie CLI. I think that you are using the old version of IconGenie (v1) which was an App Extension. You can follow this [guide](https://quasar.dev/icongenie/installation#Upgrading-to-Icon-Genie-v2) to start using the IconGenie CLI.

The IconGenie CLI is a standalone CLI which you run once in your terminal then you can forget about it until you want to change the graphics :)

**Comment by enricribas** [comment]
I think I'm using both which is why I'm getting confused I guess. 
I *am* using the CLI and it generates images, but *I think* you're right in that the app extension is ALSO installed which is what is overriding my generated images. 

Thanks!!!

I will try and remove the extension, and run from the command line which makes more sense to me.
