### ISSUE TITLE
qSelect - removing item return error null

### ISSUE THREAD

**Issue by gg4u** [quasarframework/quasar#7779]
I initialize a qSelect component with options, but if I remove the selected one my model return a `null` error : `_vm.selectedNode is null` in spite I am checking if model is null. I could not identify the issue, this is the way I am using it:
```

<q-select
        name="preferred_genre"
        v-model="selectedNode"
        :options="nodesInGraph"

        :option-value="opt => Object(opt) === opt && 'uid' in opt ? opt.uid : null"
        :option-label="opt => Object(opt) === opt && 'name' in opt ? opt.name : '- Null -'"
        :display-value="`Entity: ${selectedNode ? selectedNode.name : '*Select a node*'}`"
        color="primary"
        filled
        clearable
        label="Preferred genre"

      >
```

```
  // script
  mounted() {
    // populate model and options once rendered : the component is in a modal, 
    // things on the app will have to run first
    this.selectedNode = this.currentNode

    this.nodesInGraph = this.getNodeInGraph()
  },
  data (){
    return {

      selectedNode: null,
      nodesInGraph: null
   }
  },
```

```
// and the model and options will be get populated 
{
  uid: 344334,
  name: 'A node',
  // other props
}
```

error when I click the close (`x`) button to remove the selected option:

<img width="634" alt="Screen Shot 2020-09-16 at 3 39 16 PM" src="https://user-images.githubusercontent.com/284214/93345008-a21bb700-f832-11ea-8ddd-aea0d037a1d9.png">

**Comment by rstoenescu** [comment]
Hi,

Initialize the options, even with an empty array but don't leave it as "null". While we specify that "options" must be an Array, if you give it a "null" value then Vue will not default it to an empty array (as instructed).

This is what I'm seeing wrong in the usage. May be other things as well, but without a codepen, it's hard to help you...
