### ISSUE TITLE
[Request] Standalone build and CDN integration

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#778]
At the moment Quasar v0.14 does not have a standalone build, but in my opinion, this would be a very useful feature to have. Of course, it is not recommended to pull in Quasar without using a build system for production ready sites, but a standalone build would really help debugging issues.

If we would have a standalone build which is uploaded to a common CDN, Quasar could be included into sites like `JSBin`. This would allow users to provide minimal working examples of their issues or solutions to a problem, without setting up a whole new project. It would also be great for showcasing things like Vue does it in their documentation.

Relevant Forum discussion: http://forum.quasar-framework.org/topic/581/single-js-css-file-for-the-whole-framework/20

**Comment by rstoenescu** [comment]
99% done and will be available in future v0.15.

**Comment by olegvakulenko** [comment]
Could you tell me please
1. when standalone version of Quasar framework will be approximately (week, month) available for download and usage?
2. is exist a way to build this files (js & css) automatically from current version by myself?

After my experiments I could manually edit _quasar.esm.js_ as that was in v13 and run simple app, but my knowledge of JS and Quasar does not allow to register components in Vue.

Thanks!

**Comment by SeregPie** [comment]
To make a standalone build, edit the file `/build/script.build.javascript.js`.

```js

build([
  {
    input: resolve('src/index.esm.js'),
    output: resolve('dist/quasar.esm.js'),
    format: 'es'
  },
  {
    input: resolve('src/ie-compat/ie.js'),
    output: resolve('dist/quasar.ie.js'),
    format: 'es'
  },
  {
    input: resolve('src/index.esm.js'),
    output: resolve('dist/quasar.standalone.js'),
    format: 'umd'
  },
].map(genConfig))

```

Then run `npm run build` from the root.

In dist you will have `quasar.standalone.js`, `quasar.mat.css` and , `quasar.ios.css`, wich you can use directly.

**Comment by olegvakulenko** [comment]
@SeregPie 
Thanks! Work perfect!

Maybe, it could be useful for others framework users, who want use Quasar standalone without **npm**.
To change theme just do follow steps in backend:

1. In `<head>` add `<link href="quasar.ios.css" rel="stylesheet">` or `<link href="quasar.mat.css" rel="stylesheet">`;
2. In `<script>` before `new Vue ({ el: '#q-app', ... });` add `Quasar['default'].theme.set('ios');` or `Quasar['default'].theme.set('mat');`

**Comment by Masanix** [comment]
Hello,
Thanks SeregPie for your answer.

As I am new I do not know steps to get the `/build/script.build.javascript.js` file.

I have followed steps in _Getting Started_ but I found only _script.build.js_ .

ANy help on this it is highly appreciated.

Thanks in advance

**Comment by olegvakulenko** [comment]
@Masanix 
Hi!
If you want to build standalone version do this:

1. Download release from GitHub and put files in new folder.
2. Run `npm install` in this folder.
3. Edit `/build/script.build.javascript.js` and add `'umd'` section.
4. Run `npm run build` from same folder.

**Comment by SeregPie** [comment]
Hello Masanix.

Download the latest release [here](https://github.com/quasarframework/quasar/releases). There is a file `/build/script.build.javascript.js`.

**Comment by Masanix** [comment]
Hi!

Work perfect!

Thanks a lot for your support.

**Comment by mburke05** [comment]
I followed the steps above and received "Error: Could not resolve '.QSpinner' from src\components\spinner\index.js'". I can provide the full error and context if anybody else has the issue.

**Comment by extend1994** [comment]
Hi I am adding this library to cdnjs. [Here](https://github.com/cdnjs/cdnjs/pull/12233) is process.
However, I met some trouble. 
First, cdnjs needs library's official built files. But after v0.13 of npm pacakge, there is no `quasar.standalone.js`;

Second, anyone meets the error when using `quasar.standalone.js` in browser?
```
quasar.standalone.js:12 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at quasar.standalone.js:12
    at quasar.standalone.js:9
    at quasar.standalone.js:9
```

Any kind of help would be good :)

**Comment by rstoenescu** [comment]
Hi all,

Please be patient for v0.15 release. This will be the first version officially supporting a standalone build.

**Comment by natxocc** [comment]
Hi. Using standalone version have a problem. Using Tabs component, only first tab is shown, the rest are hidden. Using the same in webpack all is correct. Something missing probably when setup a standalone version?

**Comment by mesaglam** [comment]
We strongly need a standalone versiyon like vuetify...

**Comment by rstoenescu** [comment]
It's coming. Please be patient.

**Comment by mesaglam** [comment]
I'll be a backer then! :+1:

**Comment by rstoenescu** [comment]
@mesaglam Here's a very very early alpha version of UMD starter kit: `vue init quasarframework/quasar-starter-kit-umd <folder>`

**Comment by olegvakulenko** [comment]
@mame82 

https://unpkg.com/quasar-framework@0.17.9/dist/umd/

**Comment by mame82** [comment]
Thanks!
