### ISSUE TITLE
QInfiniteScroll allow bidirectional scrolling

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#7782]
**Problem**
When bookmarking an item in an infinite scroll list, in such a way that it then has an undefined number of successors as well as predecessors, the infinite scroll can only be used to scroll in one direction, either up or down, depending on the `reverse` property. This means you can only scroll to load more items which followed the bookmarked item, or load more items which preceded the bookmarked item, but you do not have the freedom to scroll up or down depending on the current need.

**Solution**
Add a `bidirectional` property which allows to load more items up- and downwards of the currently visible items. A combination of reverse=false and reverse=true.

**Comment by pdanpdan** [comment]
I think it would make things too complex, because you would need to both append and prepend items in the list.

But I would say you are using the wrong tool for the job, use QVirtualScroll because it does exactly this.

https://codepen.io/pdanpdan/pen/qBaZOYr?editors=1010
