### ISSUE TITLE
QInput @input handler called twice when calling QDialog plugin inside.

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#7783]
**Describe the bug**
QInput `@input` handler called twice when calling QDialog plugin inside.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/metalsadman/pen/oNxPYpw
**To Reproduce**
1. Type something in the input
2. handler is called twice

**Expected behavior**
handler called once.

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
Workaround wrap the dialog call inside `Vue.nextTick`.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
