### ISSUE TITLE
IE11 error: SCRIPT5009: "Proxy" is undefined 

### ISSUE THREAD

**Issue by Fly-Besom** [quasarframework/quasar#7784]
**Describe the bug**
Open the project page blank in IE11 and report an error SCRIPT5009: "Proxy" is undefined but It works perfectly on Google
(quasar v1.9.6)
**Codepen/jsFiddle/Codesandbox (required)**
The Codepen/jsFiddle/Codesandbox link is not available because it is a local project

**To Reproduce**
1. Go to 'IE11'
2. Open the console
3. See error: SCRIPT5009: "Proxy" is undefined 

**Expected behavior**
IE11 is working properly

**Screenshots**
![image](https://user-images.githubusercontent.com/32609213/93443157-cba41380-f902-11ea-9939-ecf236b22323.png)
![image](https://user-images.githubusercontent.com/32609213/93447493-0c049100-f905-11ea-901b-6e1f71540f5a.png)

**Platform (please complete the following information):**
OS: windows
Node:
NPM:
Yarn:
Browsers: IE11
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

There is no "Proxy" in Quasar code. Please add a list of deps/files that need transpiling to quasar.conf.js > build > transpileDependencies. https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build
