### ISSUE TITLE
Option to disable setting of language to html attribute

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#7785]
**Is your feature request related to a problem? Please describe.**
I was frustrated when I found out that Quasar sets lang attribute to html element on background without asking for it. Backend send me language information by setting lang attribute on html tag.. therefore reseting by Quasar breaks stuff.

**Describe the solution you'd like**
At least option to turn this behaviour off, but I think it should be default to NOT setting lang on html element.  And it should be turned on only for those who need it. I didn't need setting lang on Quasar so far and I am working almost a year with it. 

**Describe alternatives you've considered**
`Vue.use(Quasar, {disableHtmlLangChange: true);`
or have it by default and then
`Vue.use(Quasar, {setHtmlLang: true);`

**Additional context**
https://github.com/quasarframework/quasar/blob/ca2c70a3d7cb3fe2b4029071b7efb3934a8a6d47/ui/src/lang.js#L56

Thank you 🙏

**Comment by pdanpdan** [comment]
Hello. Quasar changes the lang attribute to be in sync with the language selected in the application.
If you set the correct language in the application it should be all good.
Please comment with a full description of what you do, thank you.
