### ISSUE TITLE
can i use render method in Table [docs]

### ISSUE THREAD

**Issue by godtoy** [quasarframework/quasar#7788]
table render method need

If can support this function, it will be very good, instead of using slot placeholders

example:
```
       {
                    name: 'name',
                    label: 'Dessert (100g serving)',
                    align: 'center',
                    field: '',
                    render: (h, { row }) => {
                        return h('img', { class: 'hk-product-logo', attrs: { src: row.pic_link } });
                    },
      }
```

**Comment by godtoy** [comment]
maybe my idea is stupid, but I really want to know why not use the more convenient render method
![image](https://user-images.githubusercontent.com/13638996/93563204-00bf6d00-f9ba-11ea-918a-1076f9498d4e.png)

**Comment by pdanpdan** [comment]
Hello.
The render function is the scoped slot. You can already define generic and per column scoped slots.
