### ISSUE TITLE
q-select with use-input - lable covers value if it is integer

### ISSUE THREAD

**Issue by NicoP-S** [quasarframework/quasar#7789]
**Describe the bug**
If i use a combination of "use-input fill-input  hide-selected" on an q-select AND the options object label property is not an string the label covers the input.

https://jsfiddle.net/y8hxp56m/ 

Pkg quasar........ v1.14.0
Pkg @quasar/app... v2.1.0

![grafik](https://user-images.githubusercontent.com/8988747/93564986-e4580c00-f98a-11ea-93aa-70257eaa481f.png)

**Comment by pdanpdan** [comment]
Hello. The label should be string, or else it's considered missing. Please cast your labels to string.
