### ISSUE TITLE
[Request] Display value property for Autocomplete

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar#779]
The QAutocomplete component should have a display property just like QSelect.
For example, If I want to autocomplete on an object, maybe search for an address and return the address in parts in the response:
```
{
  'locality': 'foo',
  'address_line': 'bar',
  'country': 'baz'
}
```

Currently, there is no way to tell QAutocomplete to use something like `value.address_line` as display value.

**Comment by rstoenescu** [comment]
http://beta.quasar-framework.org/components/autocomplete.html#Using-Static-Data
You can tell which field to search on (`field` prop), and what to display when user selects an autocomplete entry (`value` from `list` entry).

**Comment by rstoenescu** [comment]
Assuming you are on v0.14.

**Comment by a47ae** [comment]
Oh sorry, I missed that part in the docs.
But does this also work on not static data?
When I tried to pass an object `{ field: 'label', list: [{ label: 'foo', value: 'bar' }] }` to the `done` callback nothing is displayed at all and the `computedResults` property is `undefined`.

**Comment by rstoenescu** [comment]
If not using static data then you can use `.map()` to convert to the required format (in this case `value` will be used).

**Comment by a47ae** [comment]
Yeah, but that brings me back to my initial problem, with dynamic data, always `value` is displayed as selected field.
So this is a breakdown of the code I am using at the moment. It fetches a country from Algolia.
But now I want to be able to display the country name as selected value but assign the country code to `address.countryCode`.
Currently, I am unable to display anything other than `value` as selected when using dynamic data. And because I generate lots of these fields with `v-for` I am also not able to use the `@selected` event, because I do not know from which of the multiple fields that event fired.

```vue
<template>
  <q-field class="col-md">
    <q-search v-model="address.countryCode">
      <q-autocomplete @search="handleCountrySearch" />
    </q-search>
  </q-field>
</template>

<script>
 function parseCountries (countries) {
   return countries.hits.map(country => {
     let name = country.locale_names.default[0]
      return {
        label: name,
        value: country.country_code.toUpperCase()
      }
    })
  }

  export default {
    data () => {
      return { country: { countryCode: null } }
    },

    methods: {
      handleCountrySearch (term, done) {
        axios.post('https://places-1.algolianet.com/1/places/query', {
          type: 'country',
          query: term
        })
          .then(response => {
            done(parseCountries(response.data))
          })
      },
    }
  }
</script>
```

**Comment by kyriediculous** [comment]
Having to remap to label, value is TERRIBLE!
