### ISSUE TITLE
QEditor loses caret after clearing model

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#7790]
**Describe the bug**
Clearing / refocusing to QEditor no longer works as it used to

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/gOrdNJO

**To Reproduce**
1. Go to codepen
2. Open console pane
3. Enter some text into the QEditor, then hit CTRL+Enter
4. The text is logged, cleared, but focus does not stay in QEditor

**Expected behavior**
This code is lifted from a large application, and used to work, but in the last few weeks (months? not 100% certain when it stopped to be honest), the cursor is not positioned where it should be, and the QEditor is no longer ready for the next input. Sometimes the cursor is positioned right over to the far right of the component, sometimes it's not visible at all.

**Platform (please complete the following information):**
OS: Windows 10
Node: 12.16.2
NPM: 6.14.1
Yarn: 1.21.1
Browsers: Firefox, Safari, Chrome
iOS: 13

**Additional context**
Note that the call to `focus()` perhaps used to mask the (potential) real issue of clearing the model? At the moment, the behaviour is the same with or without the `focus()` call.

**Comment by dsl101** [comment]
I updated the codepen to show that the code works when attached to a QInput, but not a QEditor. The event logging shows that the QEditor _is_ still getting events (try hitting CTRL+Enter twice in a row), but not positioning the caret or triggering input events for regular keystrokes.

**Comment by hawkeye64** [comment]
@dsl101 I will look into this ticket for you so vue3-work is not disrupted.
Anything more to add to your findings?

**Comment by hawkeye64** [comment]
Not sure if this is related, but adding it here, in case: https://bugs.chromium.org/p/chromium/issues/detail?id=1046357

**Comment by dsl101** [comment]
Thanks. Nothing new I'm afraid—I tried obvious things like calling `focus()` on `$nextTick`, with `setTimeout()`, etc. Also tried it with out an empty model—the text of the model is updated, and the input caret does appear in the right place then, but still no response to input events (apart from CTRL+Enter).

This seems to affect every browser I've tried (Chrome, Firefox, Edge, Safari, Mobile Safari), so not sure if it's an engine-specific thing, unless it's something actually in the spec that they're all doing 'correctly' and QEditor is tripping over.

**Comment by hawkeye64** [comment]
@dsl101 I possibly found the issue. Will come up with a fix if I can.

**Comment by hawkeye64** [comment]
Changed title to reflect what actually happened. QEditor never lost focus, so calling focus doesn't do anything. 
It lost the caret because internally it had created an invalid range, which it applied.

**Comment by hawkeye64** [comment]
@dsl101 dsl Will be available in v1.14.2

**Comment by emahuni** [comment]
Hi. I've noticed this in qinput as well, could you please take a look if this is related. The fix should be the same. I actually used a forced focus after clearing.

**Comment by dsl101** [comment]
Can confirm this has fixed the QEditor issue I had. @emahuni if you're using (for example) an appended button to clear the input model, that button will take the focus, and you must explicitly set the focus back—that's not a bug.
