### ISSUE TITLE
"quasar build -m capacitor -T android" fails to build apk

### ISSUE THREAD

**Issue by abbjoafli** [quasarframework/quasar#7791]
**Describe the bug**
When i try to build my Quasar code with capacitor then it comes upp with an error

BUILD SUCCESSFUL in 29s
46 actionable tasks: 21 executed, 25 up-to-date
(node:6840) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\Users\joafli\Documents\projs\AdaApp\src-capacitor\android\app\build \outputs'

i have manually created the folders to see if something is different but still the same error.

**To Reproduce**
1. Go to main folder'
2. Open cmd 
3. Write "quasar build -m capacitor -T android"

**Expected behavior**
I expected the build to happen

**Platform (please complete the following information):**
OS: Windows
Node:
  "dependencies": {
    "@capacitor/android": "^2.4.0",
    "@capacitor/cli": "^2.4.0",
    "@capacitor/core": "^2.4.0",
    "@quasar/extras": "^1.9.4",
    "capacitor": "^0.5.5",
    "cordova": "^9.0.0",
    "firebase": "^5.8.3",
    "quasar": "^1.2",
    "vuefire": "^2.2.4",
    "vuelidate": "^0.7.4",
    "vuex": "^3.5.1",
    "yarn": "^1.22.5"
  },
  "devDependencies": {
    "@quasar/app": "^1.9.6",
    "@quasar/quasar-app-extension-dotenv": "^1.0.5",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.10.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "quasar-cli": "^0.17.26",
    "strip-ansi": "=3.0.1"
  },
Capacitor:
npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.1
  @capacitor/core: 2.4.1
  @capacitor/android: 2.4.1
  @capacitor/electron: 2.4.1
  @capacitor/ios: 2.4.1

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/electron not installed

**Additional context**
## Full log

`
**quasar build -m capacitor -T android**

 Build mode........ capacitor
 Pkg quasar........ v1.13.2
 Pkg @quasar/app... v1.9.6
 Debugging......... no
 Publishing........ no
 Packaging mode.... gradle

 App · Running "@quasar/dotenv" Quasar App Extension...
 App · Reading quasar.conf.js
 App · Extension(@quasar/dotenv): Extending quasar.conf...
App Extension (dotenv): '.env.prod' file missing; skipping
 App · Generating legacy js code (ES5); use "--modern" param for ES6+
 App · Extending Capacitor Webpack config
 App · Cleaned build artifact: "C:\Users\joafli\Documents\projs\AdaApp\dist\capacitor\android"
 App · Generating Webpack entry point
 App · Compiling with Webpack...

 • Compiling:
 └── Capacitor ████████████████████ 100% done in 39147 ms

 Build summary for css/js/json (the rest are omitted):
 ╔══════════════════╤════════════╤═══════════╗
 ║            Asset │       Size │   Gzipped ║
 ╟──────────────────┼────────────┼───────────╢
 ║   1.0e433876.css │    0.00 KB │   0.02 KB ║
 ║   2.45e9321d.css │    0.08 KB │   0.09 KB ║
 ║   4.a44af2fe.css │    7.59 KB │   1.99 KB ║
 ║   5.51b158e5.css │    2.46 KB │   0.74 KB ║
 ║   6.f3a5e403.css │    0.00 KB │   0.02 KB ║
 ║   7.53de6821.css │    1.60 KB │   0.43 KB ║
 ║   8.0e433876.css │    0.00 KB │   0.02 KB ║
 ║ app.f093d636.css │  195.66 KB │  33.95 KB ║
 ║        style.css │    0.18 KB │   0.16 KB ║
 ╟──────────────────┼────────────┼───────────╢
 ║             1.js │    0.81 KB │   0.50 KB ║
 ║             2.js │    3.99 KB │   1.41 KB ║
 ║             4.js │    3.58 KB │   1.37 KB ║
 ║             5.js │    2.71 KB │   1.07 KB ║
 ║             6.js │    2.94 KB │   1.20 KB ║
 ║             7.js │    2.78 KB │   1.11 KB ║
 ║             8.js │    2.90 KB │   0.94 KB ║
 ║             9.js │   12.10 KB │   3.85 KB ║
 ║           app.js │   15.94 KB │   6.57 KB ║
 ║        vendor.js │ 1039.09 KB │ 291.32 KB ║
 ╚══════════════════╧════════════╧═══════════╝

 App · Updated src-capacitor/package.json
 App · Updated capacitor.config.json
 App · Running "C:\Users\joafli\Documents\projs\AdaApp\src-capacitor\node_modules\@capacitor\cli\bin\capacitor sync android"

√ Copying web assets from www to android\app\src\main\assets\public in 821.73ms
√ Copying native bridge in 2.53ms
√ Copying capacitor.config.json in 2.47ms
√ copy in 864.78ms
√ Updating Android plugins in 1.64ms
  Found 0 Capacitor plugins for android:
√ update android in 164.90ms
Sync finished in 1.071s

 App · Updated capacitor.config.json
 App · Building Android app...
 App · [sync] Running "./gradlew.bat assembleRelease"

Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

BUILD SUCCESSFUL in 22s
46 actionable tasks: 21 executed, 25 up-to-date
(node:13768) UnhandledPromiseRejectionWarning:   Error: ENOENT: no such file or directory, stat 'C:\Users\joafli\Documents\projs\AdaApp\src-capacitor\android\app\build  \outputs'

  - polyfills.js:301 Object.statSync
    [AdaApp]/[graceful-fs]/polyfills.js:301:34

  - stat.js:10 statSync
    [AdaApp]/[app]/[fs-extra]/lib/util/stat.js:10:52

  - stat.js:24 getStatsSync
    [AdaApp]/[app]/[fs-extra]/lib/util/stat.js:24:19

  - stat.js:49 Object.checkPathsSync
    [AdaApp]/[app]/[fs-extra]/lib/util/stat.js:49:33

  - copy-sync.js:24 Object.copySync
    [AdaApp]/[app]/[fs-extra]/lib/copy-sync/copy-sync.js:24:38

  - index.js:125 CapacitorRunner.__buildAndroid
    [AdaApp]/[@quasar]/app/lib/capacitor/index.js:125:9

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

(node:13768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by rstoenescu** [comment]
@abbjoafli 

Can you zip me the src-capacitor/android folder after a failed build pls? You can use dropbox if attaching directly here on Github does not works.

As a sidenote, your apk has been built and is available there in src-capacitor/android. Capacitor changed the output folder (but I cannot reproduce this issue) and so Quasar cannot copy it to /dist/capacitor/android, that's all.

**Comment by abbjoafli** [comment]
I cant find the apk file. Here is the capictor/android folder. https://gofile.io/d/UeLLH5

Thanks

**Comment by rstoenescu** [comment]
Haven't looked yet into the zip, but if it isn't there, then it means this is a Capacitor or Android build tools bug. This is because "BUILD SUCCESSFUL in 22s" is written to the console by these tools.

Does anyone else experience this?

**Comment by rstoenescu** [comment]
I've just tested with latest "@quasar/app" (v2.1.4), Android Studio (v4.1), Capacitor (the "@capacitor/*" packages) and latest Android SDK (30). Everything seems alright... Please do the upgrades too and report back if the bug is still there.
