### ISSUE TITLE
Notify action buttons shift sometimes

### ISSUE THREAD

**Issue by radixcorp** [quasarframework/quasar#7792]
Notify displays correctly here.
![Notify 1](https://user-images.githubusercontent.com/12922438/93626689-ceaa0d00-f9b1-11ea-8725-a3eb484e47b3.png)

After the action button is clicked.
![Notify 2](https://user-images.githubusercontent.com/12922438/93626837-07e27d00-f9b2-11ea-97f4-43d51294dbb1.png)

It appears that in some cases where the message width is shorter than the actions buttons width, the action buttons shift after one of them is clicked.

**Comment by pdanpdan** [comment]
Please reopen with a codepen where we can reproduce the problem.
Thank you
