### ISSUE TITLE
Drawer scrolling page on close.

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#7793]
I am wondering if this is expected behavior or if I should file a bug.

I have a page that has a drawer on it.

When I scroll to the bottom, open the drawer then close it. 

The page starts back at the top and scrolls to position the page was at before the drawer was opened.

I made a quick video.

https://youtu.be/lVQEjejHSw4

Here is the relevant source code.

```
// layout
<template>
  <q-layout view="lHr lpr lFr" class="main-layout">
    <q-header class="main-header">
    </q-header>
    <q-drawer
      v-model="leftDrawer"
      behavior="mobile"
    >
      <q-btn @click="leftDrawer = !leftDrawer">Close</q-btn>
    </q-drawer>
    <q-page-container>
      <router-view />
    </q-page-container>
  </q-layout>
</template>
```

```
// page
<template>
    <q-page class="scroll-test">
      <basic-thumbnail-series :collection="fakeThumbnails"/>
    </q-page>
</template>
```

**Comment by pdanpdan** [comment]
Can you make a codepen that can reproduce the problem?
I suppose it only happens on mac safari, or cand you reproduce it on some other browser/os?

**Comment by pdanpdan** [comment]
I'll reopen if more details are added.
