### ISSUE TITLE
Compatible with Vue 3?

### ISSUE THREAD

**Issue by frederikhors** [quasarframework/quasar#7794]
_I apologize if it is written somewhere and I have not read it, I have searched._

**Is your feature request related to a problem? Please describe.**
Can I use this project with Vue 3?

**Describe the solution you'd like**
Is there a temporary branch of work in progress that I can try?

**Describe alternatives you've considered**
I need to start a new project and need to find out more before starting.

Thank you.

**Comment by rstoenescu** [comment]
Hi,

If you are looking for starting your project today, then the answer is "no". Quasar is not **yet** compatible with it. Plan is to rollout the vue 3 compatible version by the end of the year (worst case scenario).

**Comment by psi-4ward** [comment]
do you have smth which tracks the progress to vue3 ?

**Comment by rstoenescu** [comment]
We'll make it public next week. Rough target for first beta is one month from now.
