### ISSUE TITLE
Model changes are not correctly handled by QEditor

### ISSUE THREAD

**Issue by dvbeek** [quasarframework/quasar#7797]
**Describe the bug**
When the model changes for a QEditor, the inner model does not always change accordingly.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/DennisVanBeek/pen/abvoKgv

**To Reproduce**
1. Select 1st tab
2. Enter some text
3. Select 2nd tab
4. Enter a different text
5. Select 1st tab
6. Select 2nd tab => the text of the 1st tab is still displayed

**Expected behavior**
Every tab contains the entered text for that tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/13819325/93751851-09a08080-fbfe-11ea-84dd-02086d9c5385.png)

**Platform:**
OS: Windows 
Browsers: Firefox / Chrome
Pkg quasar........ v1.14.0
Pkg @quasar/app... v1.9.6

**Additional context**
In codepen the problem cannot be reproduced.
But in a local environment it does not work.

**Comment by outofmemoryagain** [comment]
@webnoob I was able to reproduce this issue locally, but as described it does work correctly in the codepen

**Comment by rstoenescu** [comment]
This should be already fixed.
Please look out for Quasar v1.14.2 (not yet released).

**Comment by hawkeye64** [comment]
It is fixed, coming in next release.
