### ISSUE TITLE
QCarousel and v-for does not work on quasar cli

### ISSUE THREAD

**Issue by igormcsouza** [quasarframework/quasar#7798]
Hello everyone! First of all thank you for this great tools for building applications! 

**Describe the bug**
Well, I was building an app using vue and add quasar to it, it was great, but I wanted to go one step further and decided to migrate the entire project to build using quasar cli!

Well, since then I'm not able to use q-carousel anymore, and I have no idea why!

The way it works is simple, I have a list stored at Vue data. I wanted to show the content of this list on screen, which is working already using v-for. But when put q-carousel instead nothing is shown on screen! Is like the list is empty although is full of guys! Not sure was could be causing it! 

The exactly same thing was working when my project was using quasar as plugin!

I really wonder why it was working perfectly before, but now using quasar cli it doesn't anymore!

Not sure if I was clear enough! Please, lemme know if more details is needed! That issue is driving me crazy!

**Code Issue**
```
<template>
  <div class="row q-ma-sm">
    <div class="col-8 q-pa-md">
      <q-carousel
        v-model="slide"
        transition-prev="scale"
        transition-next="scale"
        swipeable
        animated
        control-color="white"
        navigation
        padding
        arrows
        height="300px"
        class="bg-primary text-white shadow-1 rounded-borders"
      >
        <q-carousel-slide :name="each" class="column no-wrap flex-center" v-for="each in test" :key="each">
          <q-icon name="style" size="56px" />
          <div class="q-mt-md text-center">
            {{ each }}
          </div>
        </q-carousel-slide>
      </q-carousel>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      slide='style',
      test: [1, 2, 3, 4, 5]
    }
  },
}
</script>
```
That issue happens when on quasar-cli

**Screenshot**
![image](https://user-images.githubusercontent.com/38996012/93811042-edb0d500-fc25-11ea-9fa6-f5f16664a32f.png)

On the Slide, I can't go to next, it stays fixed on the first slide. And the number one is not there too!

**Expected behavior**
Q-carousel show all slides when v-for is present.

**Platform (please complete the following information):**
OS: Linux
Node: 10.19.0
NPM: 6.14.4
Browsers: Chrome

**Comment by rstoenescu** [comment]
Hi,

There's absolutely no reason why switching to Quasar CLI would affect the UI code. However, I noticed two things in your example above:

1. `slide='style'` is invalid JS. It should be `style: 'style'`.
2. You're giving the following names to your slides: 1, 2, 3, 4. But the model is 'style'. So basically this will tell QCarousel that there's no match with any of the slides.
