### ISSUE TITLE
Improve scroll util to use frame time for requestAnimationFrame 

### ISSUE THREAD

**Issue by B4RteQPl** [quasarframework/quasar#7800]
Please change the fixed number for calculating animation frames, because this functionality is working well only when display frame rate has only 60hz

**Is your feature request related to a problem? Please describe.**
Yes it's a problem because we're using own implementation to make scrolling behavior fluid

**Describe the solution you'd like**
Calculate frame time and use it

**Describe alternatives you've considered**
calculating frame time works with animations even for old devices, so IMO that's the best option

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.15.1
