### ISSUE TITLE
Why not quasar support CSS Modules fully? VSCode show error

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#7801]
**Describe the bug**
Vue 2 support CSS Modules using the @vue-cli 3 tool and VSCode show properly, no error in VSCode.
But in Quasar, VSCode show error.

**Codepen/jsFiddle/Codesandbox (required)**
none

**To Reproduce**
1. create a quasar project using'quasar create quasardemo' command.
2. in file 'MainLayout.vue', add  the following code:
   `<style module>
.bg {
  background: green;
}
</style>`
   and add the css class in the template code, such as:
   `:class="$style.bg"`
3. VSCode show error, VSCode say "Property '$style' does not exist on type 'MainLayout'.Vetur(2339)" 

**Expected behavior**
VSCode should show properly, should show no error in VSCode.

**Screenshots**
none.

**Platform (please complete the following information):**
OS: windows 10
Node: Node.js v12.9.1
NPM: npm 6.10.2

**Additional context**
none

**Comment by metalsadman** [comment]
That's a vetur error as you can see in your log.

**Comment by zouzg7829** [comment]
> That's more like a vetur error as you can see in your log.

but if you create a vue project with @vue-cli 3 tool and add the same CSS module code, VSCode show properly, no error in VSCode.

**Comment by hawkeye64** [comment]
@zouzg7829 quasar.conf.js is extensible for exactly this type of purpose. No one wants extra bloat, so user can pick and choose things, like added webpack loaders that do what you need to be done.

You'll need to add a rule to load css-loader and style-loader...

Here's a good starting point: https://css-tricks.com/css-modules-part-2-getting-started/#loading-the-styles

**Comment by zouzg7829** [comment]
@hawkeye64 why close the bug? this is not the problem of extensions about the quasar.conf.js, I think this is the problem of the setting about vetur that Quasar do.

**Comment by zouzg7829** [comment]
@metalsadman @hawkeye64 I think it is probablly the problem of the setting about VSCode that Quasar-Cli do, such as some settings in file '**extensions.json**' or file '**settings.json**' under the Quasar project '**.vscode**' directory that Quasar-Cli generate.
