### ISSUE TITLE
QForm not checking rules on first submit nm some cases?

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#7802]
**Describe the bug**
I'm seeing q-form not check the rules locally when I hit the submit button the first time. If I focus a field first then it works as expected. I created a similar codepen, but without a boot file, but I am not seeing the issue reproduce there. Possible this is an edge case of some sort?

https://codepen.io/smakinson/pen/zYqyqyg?editors=1010

**Expected behavior**
Rules to always be checked.

**Platform (please complete the following information):**
OS: OSX
Node:
NPM:
Yarn:
Browsers: Chrome, Safari
iOS:
Android:
Electron:

**Additional context**
"quasar": "^1.14.0"

**Comment by smakinson** [comment]
If I call 

`await this.$refs.theForm.focus()`

before calling

`const formValid = await this.$refs.thForm.validate()`

it seems to work around the issue.

**Comment by outofmemoryagain** [comment]
@smakinson I checked your codepen and it appears to work for me.

**Comment by smakinson** [comment]
@outofmemoryagain I was not able to get the same thing to happen in the codepen, but I included it to show the setup.

**Comment by outofmemoryagain** [comment]
Can you create a small repo and I can pull it?  Otherwise I will do so later today when I have more time.

**Comment by smakinson** [comment]
I'm not able to at this time, things are rushed for me right now. Thanks for checking this one out.

**Comment by hawkeye64** [comment]
@smakinson What happens if you set your first field with attribute `autofocus`? Does it work then?

**Comment by smakinson** [comment]
@hawkeye64 Yes, auto focus did also fix it, but I had a situation where I had 2 forms side by side and could not pick one to use autofocus.

**Comment by rstoenescu** [comment]
Please reopen after providing a reproduction repo (or a https://codesandbox.quasar.dev). We can't do anything until we can reproduce this.

**Comment by smakinson** [comment]
@rstoenescu sorry for the delay, here is a repo: https://github.com/smakinson/quasar-7802

There is a comment in Pages/Index.vue

**Comment by FangHanZreo** [comment]
I ran into a similar problem because I was using the QInput component through a new component. This caused the getValidationComponents method in the QForm to fail to get my new component. I don't know you can understand my expression. My English is poor.

**Comment by pdanpdan** [comment]
See here: https://github.com/quasarframework/quasar/issues/8173

**Comment by DouglasCalora** [comment]
@FangHanZreo Did you fix it? I'm having the same issue.
