### ISSUE TITLE
TS2709: Cannot use namespace 'QuasarIconSet' as a type.

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#7805]
I just updated from Quasar 1.12.13 to 1.14.0 and now get his error

ERROR in xxx/node_modules/quasar/dist/types/shim-icon-set.d.ts(5,18):
TS2709: Cannot use namespace 'QuasarIconSet' as a type.

I know that this problem already appeard by update from 1.9 to 1.12.13 and should be fixed with 1.13 (https://github.com/quasarframework/quasar/issues/7640) but I didn't have this error with 1.12.13.

  "dependencies": {
    "@quasar/extras": "^1.9.5",
    "axios": "^0.20.0",
    "core-js": "^3.6.5",
    "file-saver": "^2.0.2",
    "lodash": "^4.17.20",
    "quasar": "^1.14.0",
    "vee-validate": "^3.4.0",
    "vue-class-component": "^7.2.6",
    "vue-i18n": "^8.21.1",
    "vue-property-decorator": "^9.0.0",
    "vuex-class": "^0.3.2"
  },
  "devDependencies": {
    "@quasar/app": "^2.1.0",
    "@types/node": "^14.11.2",
    "@types/file-saver": "2.0.1",
    "@types/lodash": "^4.14.161",
    "@typescript-eslint/eslint-plugin": "^4.2.0",
    "@typescript-eslint/parser": "^4.2.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.9.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^2.1.2"
  },

**Comment by IlCallo** [comment]
As already stated in other issues, we are not able to find the root cause of this without a repro.
All who tried to create it could not make it work and the problem is usually solved by a yarn.lock refresh and VSCode restart.

Can you try this, and if it doesn't work, provide a repro?

**Comment by chaosKP** [comment]
Issue has disappeard after some time
