### ISSUE TITLE
Material Icons 4.0.0

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#7806]
Google has released an update to the icon font with a full set of styles.

https://github.com/google/material-design-icons/releases

**Comment by hawkeye64** [comment]
@olegvakulenko Thanks for bringing this up. It's nice to see activity in that repo again. We don't actually get our icons there. We download them directly from Google cloud services. This service is actually the "single source of truth" for the icons and the fonts, which we would prefer over the repo as there is a good chance of it falling behind again sometime in the future. Our Google fonts and icons are always up to date as we test regulary for new releases and updates.

**Comment by 54mu3l** [comment]
I'm looking up the icons and their names here:
https://material.io/resources/icons/?style=baseline

But this seems not identical to the icons quasar contains (following problem: https://github.com/google/material-design-icons/issues/1022).

If you're getting them directly from Google, where should I look up the icons and their names?


Also I would like to mentions the following issue here:
https://github.com/google/material-design-icons/issues/1129

**Comment by hawkeye64** [comment]
@54mu3l The list is here: https://fonts.google.com/metadata/icons

**Comment by 54mu3l** [comment]
@hawkeye64 Yes, but that's not what a web-developer/designer is looking for during development (at least not me).
I was looking for a website where all icons are displayed with their name below. Like an overview page.

I guess I'll continue using https://material.io/resources/icons/?style=baseline for the projects where we use material icons.

For everyone else who runs into the same issue: When possible I would recommend using font-awesome or mdi-icons.

**Comment by hawkeye64** [comment]
@54mu3l I see what you mean.
For svg webfonts use this one: https://quasarframework.github.io/quasar-ui-qiconpicker/demo
For svg's only, use this one: https://quasar-svg-icons.netlify.app/
