### ISSUE TITLE
QEditor: Optionally use <p> tag instead of <div> for paragraphs

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#7809]
**Is your feature request related to a problem? Please describe.**
Related to #7804 
In order to use `<p>` tags instead of `<div>`, you have to override the definition and manually execute `document.execCommand('defaultParagraphSeparator', false, 'p')` when the component is mounted.

**Describe the solution you'd like**
A simple prop to control what tag to use for paragraphs, defaulting to `<div>` to retain backwards compatibility.

**Describe alternatives you've considered**
Manual override of the above mentioned actions.

**Additional context**
In addition, it would be nice to be able to specify if the editor should add a default empty paragraph tag (`<div><br></div>` or `<p><br></p>`), since content editable doesn't add this by default for the first line.

Handling this seemed a bit more tricky, as the cursor didn't quite want to play along.
I had to do some custom value syncing to get it working:
```javascript
computed: {
    valueSync: {
        get: function() {
            return this.value
        },
        set: function(value) {
            const insertParagraph = value && !!value.length && !value.startsWith('<')
            if (insertParagraph) {
                this.$refs.editor.runCmd('formatBlock', 'P')
                const range = document.createRange()
                const sel = window.getSelection()
                range.setStart(this.$refs.editor.$refs.content, value.length)
                range.collapse(true)
                sel.removeAllRanges()
                sel.addRange(range)
                value = `<p>${value}</p>`
            }
            this.$emit('input', value)
        },
    }
}
```

**Comment by rstoenescu** [comment]
Thank you for also supplying a PR on this. Will be available in Quasar v1.14.4.
