### ISSUE TITLE
Upgrade to Vue 3.0

### ISSUE THREAD

**Issue by luizhenriquerdias** [quasarframework/quasar#7812]
Upgrade Quasar to use Vue 3.0.

**Comment by HendrikJan** [comment]
This question has been asked before: #7794

**Comment by luizhenriquerdias** [comment]
Sorry.

**Comment by rstoenescu** [comment]
Porting Quasar to Vue 3 is our main focus now.

**Comment by dodanex** [comment]
> Porting Quasar to Vue 3 is our main focus now.

I have donated to you because I love Quasar and can't wait for vue 3 full support, thank you so much for your effort!
Apropo, sper sa ne cunoastem intro zi :)
