### ISSUE TITLE
quasar app not working on any ios devices or mac desktop with safari

### ISSUE THREAD

**Issue by jtlindsey** [quasarframework/quasar#7813]
**Describe the bug**
I'm running the latest version of quasar app. It's a large SPA app in private repo. I'm trying to find out if there is anything standard to quasar that I might be missing.

My app works on all desktop computers (tested on a linux deskop and laptop, and a mac desktop and laptop in google chrome). It does not work in safari and it does not work on ipad in safari or even google chrome and does not work on iphone. I can login but data pages are all blank .

In dev tools in safari on mac desktop I get the following error:

`RangeError: currencyDisplay must be either "code", "symbol", or "name"`

is there a checklist or something for quasar to work across mobile devices? I don't really care that it's not working in safari on desktop or mobile but I'm lost as to why it won't at least work in chrome on a ipad or iphone but works great on chrome desktop from linux computer or mac.

**To Reproduce**
I'm not sure how to reproduce this in a manner i can share publicly.

**Expected behavior**
Should work in all mobile and desktop sites.

**Platform (please complete the following information):**
OS: Ubuntu, Catalina, IpadOS, iOS
Node: 14.12
NPM:6.14.8
Browsers: Safari and Chrome
iOS: Latest

**Additional context**
This is a private app that i can't share publicly. My guess is this problem is very specific to quasar development because I'm able to spin up straight vue and nuxt apps easily without any issues. My hopes is that someone will know what specifically would keep a quasar SPA app from working everywhere and not just chrome desktop.

**Comment by jtlindsey** [comment]
The following was causing the issue from a private module:

```
      return val.toLocaleString('en-US', {
        maximumFractionDigits: 2,
        minimumFractionDigits: digits,
        currency: 'USD',
        style: 'currency',
        currencyDisplay: 'narrowSymbol',
      });
```

fix = narrowSymbol => symbol

**Comment by rstoenescu** [comment]
Glad that you figured it out.
