### ISSUE TITLE
Popup editing can't work and column content can't show when eable Grid style in QTable

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#7814]
**Describe the bug**
Popup editing can't work and column content can't show when eable Grid style in QTable.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/zouzg7829/pen/GRZzLgd

**To Reproduce**
1. click 'Frozen Yogurt', the popup editor can't show
2. the 'operate' column show nothing
3. if remove the 'grid' attribute of the 'q-table', everything is ok.

**Expected behavior**
1. click 'Frozen Yogurt', the popup editor will show
2. the 'operate' column should  show a button, and click the button, a menu will show

**Screenshots**
none

**Platform (please complete the following information):**
none

**Additional context**
none

**Comment by metalsadman** [comment]
It's not a bug, supply an `item` slot as well for the grid view, with implementation of qpopupedit. See docs for example on how to use the said slot.

**Comment by zouzg7829** [comment]
@rstoenescu metalsadman Thank you very much!

**Comment by ronaldchoi** [comment]
Is there anyway for q-table to re-use the `body` slot for grid display?  It seems counterintuitive to have to re-define the `item` slot if the display logic is the same.

**Comment by rstoenescu** [comment]
@ronaldchoi That's not possible because the markup is different. One is for `<table>` element and the other is custom divs.
