### ISSUE TITLE
Proxy is not working in History mode

### ISSUE THREAD

**Issue by rafis** [quasarframework/quasar#7818]
**Describe the bug**
I want to use both History mode and Proxy features with quasar serve:
```
quasar serve --history --proxy proxy.js dist/spa
```
But they can't work together because history middleware works first.

**Codepen/jsFiddle/Codesandbox (required)**
I'm not JavaScript developer, sorry. I'm DevOps engineer.

**To Reproduce**
1. Create proxy.js with `/api` path as described in `quasar serve -h`
2. Run `quasar serve --history --proxy proxy.js dist/spa`
3. Open http://localhost:4000/api
4. See blank page instead of proxied response body.

**Expected behavior**
Proxied response body.

**Screenshots**
Blank page.

**Platform (please complete the following information):**
Node: 10
Browsers: any

**Additional context**
Not needed.

**Comment by rstoenescu** [comment]
Thanks for reporting AND also fixing it!
Your PR will go into "@quasar/cli" v1.1.1.

**Comment by rafis** [comment]
Thank you very much!

**Comment by rstoenescu** [comment]
...and it's released! Thanks for contributing!
