### ISSUE TITLE
Scoped Slot for Virtual Scroll: "Loading"

### ISSUE THREAD

**Issue by myd-mannheim** [quasarframework/quasar#7821]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Today the [virtual scroll](https://quasar.dev/vue-components/virtual-scroll) displays blurred grey lines to inidcate that the data is currently being loaded (or being rendered):
![image](https://user-images.githubusercontent.com/3975508/94286190-f1f62e80-ff54-11ea-9ff7-0f20c4b1e177.png)
(Screenshot from the docs.)

It would be nice if this default loading indicator could be overruled by the content of a scoped slot. In the scoped slot we could place e. g. [skeletons](https://quasar.dev/vue-components/skeleton#Introduction) or a spinner instead.

**Describe alternatives you've considered**
At the moment I use a property that shows on app launch if the data is still loading. If it is true I display skeletons. However, the virtual scroll shows the blurred grey lines anyways for around a second _after_ the data was loaded (maybe while it renders?), so the user gets to see two busy indications. Also, when the data is already loaded and the user scrolls down the virtual scroll also shows the default grey lines when the list is re-rendered. Here I also would like to show the skeletons instead.

**Additional context**
Nothing.

Thanks!

**Comment by pdanpdan** [comment]
Hello.
Because the spacers can be placed in different html components with restrictions, the overlay can only be CSS only. Please inspect the CSS classes that show it and change as you see fit.
Thank you
