### ISSUE TITLE
Please add a option to not append file-name to Uploader formdata

### ISSUE THREAD

**Issue by leafiy** [quasarframework/quasar#7823]
Aliyun oss POSTOBJECT upload does not allow formdata's size (except file field) over 4k

Formdata like this works
![image](https://user-images.githubusercontent.com/870449/94325638-e85edc00-ffd1-11ea-9b23-5c5cc6876d9c.png)

But this does not work
![image](https://user-images.githubusercontent.com/870449/94325686-3a9ffd00-ffd2-11ea-8540-606276bbb3ca.png)

**Comment by rstoenescu** [comment]
Hi. There's the 'send-raw' prop for that. Please read about it in the docs and reopen (or comment here) if there's something that I missed.

**Comment by leafiy** [comment]
> Hi. There's the 'send-raw' prop for that. Please read about it in the docs and reopen (or comment here) if there's something that I missed.

But Aliyun oss does not support send blob

**Comment by pdanpdan** [comment]
Isn't it enough to set `field-name="file"` for QUploader?
It should append the file as `file`.
Please comment if it doesn't solve the problem, and also explain why you have both a `file` and `full_file_name...` fields in the POST? The configuration for QUploader would help.
