### ISSUE TITLE
Loading q-img from cache causes animation to trigger twice

### ISSUE THREAD

**Issue by joppehoekstra** [quasarframework/quasar#7824]
**Describe the bug**
Loading an image asset using the <q-img> component from cache causes animation to trigger twice.

**Codepen/jsFiddle/Codesandbox (required)**
Codepen doesn't really reproduce the issue because there is no caching. 

**To Reproduce**
1. Create a <q-img> component.
2. Load a page containing this component. The animation will show as expected.
3. Reload the page. The animation will now play twice. Even when not applying an animation, the image will flicker.

**Expected behaviour**
The image animation should only be played once.

**Platform (please complete the following information):**
OS: MacOS
Browsers: tested on Chrome, Safari, Safari mobile

**Comment by pdanpdan** [comment]
We need a code sample of what you used to reproduce, and the exact test conditions.

**Comment by pdanpdan** [comment]
I'll reopen if new details are added
