### ISSUE TITLE
Failed to fetch platform and Source path does not exist errors

### ISSUE THREAD

**Issue by anubhavkamath** [quasarframework/quasar#7825]
I'm unable to create a cordova (ios) build. I'm guessing this may be because of some incompatibility. Also it's complaining about a .png image. I have used icon-genie to generate the images but looks like one is missing. 

When trying to create an ios build using  quasar build -m ios, I get the following output

 Converting to long form: -m cordova -T ios

 Build mode........ cordova
 Pkg quasar........ v1.14.0
 Pkg @quasar/app... v1.9.6
 Debugging......... no
 Publishing........ no
 Packaging mode.... cordova

 App · Adding Cordova platform "ios"
 App · [sync] Running "cordova platform add ios"

Using cordova-fetch for cordova-ios@^6.1.0
Failed to fetch platform cordova-ios@^6.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: CordovaError: Could not determine package name from output:
audited 101 packages in 3.691s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

 App · ⚠️  Command "cordova" failed with exit code: 1
 App · ⚠️  There was an error trying to install Cordova platform "ios"

**Then I try running: cordova platform add ios, I get the following:**

Using cordova-fetch for cordova-ios@^6.1.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.tennisNE1.NE1apps.www
	Name: Tennis NE1
iOS project created with cordova-ios@6.1.1
Source path does not exist: res/screen/ios/Default@2x~universal~anyany.png

**Expected behavior**
The ios platform should build.

**This is the quasar info output:** 

Operating System - Darwin(19.2.0) - darwin/x64
NodeJs - 10.16.0

Global packages
  NPM - 6.9.0
  yarn - 1.22.5
  @quasar/cli - 1.1.0
  cordova - 10.0.0

Important local packages
  quasar - 1.14.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.9.6 -- Quasar Framework local CLI
  @quasar/extras - 1.9.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.

**Additional context**

**Comment by anubhavkamath** [comment]
Actually if I create the platform using the cordova platform add command, I get the error about the source path but the IOS platform is created.

**Comment by rstoenescu** [comment]
Hi,

Running the command "cordova platform add ios" is exactly what Quasar CLI does (and is showing it in the logs). If this fails or there is an error with it, then it means that it is a Cordova error and it should be reported to them.
