### ISSUE TITLE
File watching doesn't work on Windows machines running the system in a container

### ISSUE THREAD

**Issue by colinnewell** [quasarframework/quasar#7826]
If I run `quasar dev` in a container on windows changes in files are not detected.  

The usual way to work around that is to configure whatever is watching the files to switch to polling.  

It looks like Quasar is using `chokidar` which does appear to have a polling option, but it doesn't appear that I can push options to it from the `quasar.conf.js`.  Ideally I'd like to be able to provide it with configuration via that file.

**Comment by colinnewell** [comment]
Looking at this some more, I suspect it's just the watching of a couple of specific files that are problematic.  `quasar.conf.js` and `index.template.html` are the files that probably won't work.

It looks like the bulk of the source is watched by `webpack`, and that config is accessible.  A tweak like this appears to work fine for most files:

```
diff --git quasar.conf.js quasar.conf.js
index de7eda2..47c014f 100644
--- quasar.conf.js
+++ quasar.conf.js
@@ -76,7 +76,10 @@ module.exports = function (/* ctx */) {
     devServer: {
       https: false,
       port: 8080,
-      open: true // opens browser window automatically
+      open: true, // opens browser window automatically
+      watchOptions: {
+        poll: 1000
+      }
     },
 
     // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-framework
```

**Comment by Karnith** [comment]
I have this issue as well. Changing any file will not recompile the project, leaving me to halt and run dev again..

**Comment by hawkeye64** [comment]
@colinnewell @Karnith I have added this to docs. Will be in next update/release.
![image](https://user-images.githubusercontent.com/10262924/95225263-d5f65680-07b8-11eb-9e4a-34eb71190bce.png)

**Comment by colinnewell** [comment]
It's just been pointed out to me that there is an alternative way to switch to polling that will probably work for *all* the watchers (rather than just webpack).

You can set an environment variable to tell the chokidar library to poll which should affect both your code and the webpack which uses it too.

```
CHOKIDAR_USEPOLLING=true
```

**Comment by Karnith** [comment]
> It's just been pointed out to me that there is an alternative way to switch to polling that will probably work for _all_ the watchers (rather than just webpack).
> 
> You can set an environment variable to tell the chokidar library to poll which should affect both your code and the webpack which uses it too.
> 
> ```
> CHOKIDAR_USEPOLLING=true
> ```

@colinnewell so would this be in a .env file or directly in quasar.conf.js? I ask as I don't seem to find any references on .env files in the documentation website.

**Comment by colinnewell** [comment]
> @colinnewell so would this be in a .env file or directly in quasar.conf.js? I ask as I don't seem to find any references on .env files in the documentation website.

@Karnith you could set the environment variables in multiple ways.  If you're using something like docker-compose you can set them in the config there, or if running as a single container using `docker run` you can specify using `-e CHOKIDAR_USEPOLLING=true`.

It looks like there may be a way to do it from the `quasar.conf.js`, but I'm not sure if the life-cycle would be quite right.

https://quasar.dev/quasar-cli/handling-process-env#Adding-to-process.env

**Comment by Karnith** [comment]
@colinnewell I tried with quasar env https://quasar.dev/quasar-cli/handling-process-env#Adding-to-process.env, it didn't work. i'll try with docker-compose. The polling setting is working for me in quasar.config, so it's not a high priority. thx.
