### ISSUE TITLE
Alternative Layout Design

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#7828]
**Is your feature request related to a problem? Please describe.**
Javascript is having to perform unnecessary work and reduce the speed of the page to calculate site layout, q-header, and q-footer and code is more complex.

**Describe the solution you'd like**
The solution is to add a flexbox layout to handle layout header, footer, and body instead of q-layout and q-header and q-footer which require javascript to calculate heights and padding.

**Describe alternatives you've considered**
Here is an example of how layout could be performed:

```
<style lang="stylus">
  html,
  body,
  #q-app
    height: 100vh

  .layout
    flex: 1
    min-height: 0
    height: 100%
    display: flex
    flex-direction: column

  .layout-scrollable-body
    flex: 1
    overflow-y: scroll
</style>

<script>
export default {
  name: 'flex-layout',
  props: {
    'sticky_header': {
      type: Boolean,
      default: false
    },
    'sticky_footer': {
      type: Boolean,
      default: false
    },
  },

  /**
   <template>
    <section class="layout">

      <slot v-if="sticky_header" name="header"></slot>

      <section class="layout-scrollable-body">

        <slot name="header" v-if="!sticky_header"></slot>

        <slot></slot>
        
        <slot name="footer" v-if="!sticky_footer"></slot>

      </section>

      <slot v-if="sticky_footer" name="footer"></slot>

    </section>
  </template>
   */
  render(h) {
    const loose_level = []

    if(!this.sticky_header) {
      loose_level.push(this.$slots.header)
    }

    loose_level.push(this.$slots.default)

    if(!this.sticky_footer) {
      loose_level.push(this.$slots.footer)
    }

    const sticky_level = []

    if(this.sticky_header) {
      sticky_level.push(this.$slots.header)
    }

    sticky_level.push(h('section', { staticClass: 'layout-scrollable-body' }, loose_level))

    if(this.sticky_footer) {
      sticky_level.push(this.$slots.footer)
    }

    return h('section', {
      staticClass: 'layout'
    }, [ sticky_level ])
  }
}
</script>
```
```html
<flex-layout sticky_header sticky_footer>

    <template #header>
      Sticky header
    </template>
    
    <flex-layout sticky_header sticky_footer>

      <template #header>
        Sticky page header
      </template>

      <p v-for="p in 10">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas in accusantium ipsam ducimus nostrum pariatur, inventore eligendi dolore facere esse, eos quibusdam consequatur, veritatis dolorem animi amet voluptatem placeat. Ea!
      </p>

      <template #footer>
        Sticky page footer
      </template>

    </flex-layout>

    <template #footer>
      Sticky footer
    </template>

  </flex-layout>
```

The flex-layout component can be nested multiple levels deep allowing you to have a sticky footer at the page level and the layout level.

**Additional context**
This is just an alternative layout design I was working on. It would be very cool if Quasar had the ability to incorporate a flex-layout component and reduce javascript activity.

**Comment by rstoenescu** [comment]
Hi,

That JS activity is almost negligible and handled by observers. Switching to a flexbox managed layout means reverting to Quasar v0.5 (or 0.6/0.7) and throwing out years of R&D so that the layout behavior be perfect on all platforms (including mobile browsers, Cordova wrapped, Capacitor wrapped). There's a TON of issues that come with this approach. But essentially, if all you want is a flexbox managed layout then just skip QLayout & friends and use the Quasar's flexbox CSS.

**Comment by codingfriend1** [comment]
Ah I see. Thank you for the explanation. I would have reached out directly to you before submitting a Feature Request but I couldn't find out how to contact you. Out of curiosity, what are some of the problems you discovered with the Flexbox approach?

Thanks!
