### ISSUE TITLE
Layout elements (header, tabs) are move from place when keyboard open and scrolling the view

### ISSUE THREAD

**Issue by netanelwebzi** [quasarframework/quasar#783]
### Software version

Quasar: 0.14
OS: iOS
Node: Latest
NPM: Latest
Browsers: --
iOS: any ios version... iphone 6, 7
Android: ---

I have quasar application wrapped for cordova.
In the code I use q-layout for having header fixed to top, tabs fixed to bottom.
The bug is, that I have a form with inputs on some view in the app, I focus the input , the device keyboard is opened, and then while the keyboard is open I scroll the view, the header or the tabs are suddenly move from their positions and float on the screen....

Its happened only on iOS, android works fine.
Some pictures:

![greeninvoice-issue-2](https://user-images.githubusercontent.com/19428767/29037846-0a46856c-7bae-11e7-8c99-253c77dd84b6.png)

![greeninvoice-issue-1](https://user-images.githubusercontent.com/19428767/29037848-0d0ca07e-7bae-11e7-96c7-6160edab9587.png)

**Comment by spectrolite** [comment]
I know RTL support is in the pipeline for quasar, but I’m curious, how are you faring without it? did you have to tweak a lot of things?

Concerning your issue I’m sure @rstoenescu will investigate thoroughly if you provide some code or a repo to reproduce.

**Comment by netanelwebzi** [comment]
@spectrolite actually quasar rtl support now is in beta, but it work's great, I did really few css fixes to make it great, but the quasar.rtl.css is working very well.

@rstoenescu can you help me understand what happened ?

**Comment by spectrolite** [comment]
Ha, I’ve missed that. Glad to see it’s working well already. There’s so much evolution so quickly in Quasar!

**Comment by spectrolite** [comment]
still, without any code or reproduction instructions, it’s hard to inspect this issue.

**Comment by rstoenescu** [comment]
@netanelwebzi Browser quirks. I'm really interested in your "few css fixes". I want Quasar RTL to be perfect. Please send me an email and share. This will ensure that on future Quasar versions you won't have to revisit the RTL fixes. Thanks!

**Comment by Angele91** [comment]
I'm having this issue and i haven't any clue of what's happening!
Maybe someone could get me a workaround?

**Comment by andreydos** [comment]
same issue on iOS, I use q-header and q-footer and q-input. Pretty long page with input for scrolling on mobile. When input not focused header and footer stays at top and bottom, when I focus in input and try to scroll page footer or header start scroll with page content (become "unsticky")

**Comment by Piping** [comment]
same problem happened on me. the header position move beyond the screen when mobile user types in input box that is at the bottom.
BTW, I am using edge browser in android platform. the quasar framework is on the newest version.
