### ISSUE TITLE
notify setDefaults type not work

### ISSUE THREAD

**Issue by icksky** [quasarframework/quasar#7830]
**Describe the bug**
```
Quasar.Notify.setDefaults({
  type: 'positive',
  color: 'positive',
  position: 'top',
});
```
Quasar.Notify.setDefaults can't set default `type` (eg. `positive`)

**Codepen/jsFiddle/Codesandbox (required)**
[LiveDemo](https://codepen.io/icksky/pen/zYqXZgZ)

**To Reproduce**
1. Click on button *Default Notify*
2. Click on button *Typed Notify*

**Expected behavior**
step 1 should show the notification with a icon same as step 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/13565030/94418770-6a0e5f80-01b4-11eb-9b1b-188f1236f5ed.png)

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this.
Fix will be available in Quasar v1.14.1.
