### ISSUE TITLE
q-select: trigger filter with onclick only at icon

### ISSUE THREAD

**Issue by labs20** [quasarframework/quasar#7834]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to have the q-select just focused when the user clicks it, except if the click happens directly on the arrow down icon.

**Describe the solution you'd like**
A boolean property that disable the trigger of the filter when it occur on the "body" of the q-select.

**Describe alternatives you've considered**
I've tried to intercept the click event but with no success, as when I intercept it, the trigger was already fired.

**Additional context**
nope.

**Comment by pdanpdan** [comment]
Hello.
Please reopen with a codepen showing what you have tried.
Thank you

**Comment by labs20** [comment]
Hi. 

Well, it would be a pen with only a q-select on it and no code at all, as the issue is about the user interaction with the comp. As explained above, its simple: once some "pops_only_if_clicked_on_arrow_icon" boolean prop is set, the options popup would only show up if the user click exactly on the arrow icon.

Thanks.

**Comment by pdanpdan** [comment]
You mentioned:
> I've tried to intercept the click event but with no success, as when I intercept it, the trigger was already fired.
