### ISSUE TITLE
QDate does not emit input anymore on month or year change

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#7838]
**Describe the bug**
QDate does not emit @input anymore when a year or month is selected

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/zmwt3v67/2/

**To Reproduce**
1. Click on the month or year to change to their respective view
2. Select a new month/year
3. No notification is shown

If a date is selected the notification is shown

**Expected behavior**
Whether a year, month or day is selected the input method is triggered (Like in 1.12.13

**Platform (please complete the following information):**
OS: Win10
Node: 14.11.2
Browsers: Firefox/Chrome

**Comment by rstoenescu** [comment]
Hi,

In your jsfiddle you are not using any model for QDate. The correct usage would be:


```html
<!-- notice v-model -->
<q-date v-model="date" @input="input" :emit-immediately='true' />
```

```js
new Vue({
  el: '#q-app',
  data: function () {
    return {
      date: null, // <<<<<<<-----
      version: Quasar.version
    }
  },
  methods: {
  	input: function (value, reason, details) {
      this.$q.notify('Running on Quasar v' + this.$q.version + ' ' + value + ' ' + reason + ' ' + details)
    }
	}
})
```
