### ISSUE TITLE
QCarousel navigation-icon slot active prop is incorrect

### ISSUE THREAD

**Issue by Demivan** [quasarframework/quasar#7839]
**Describe the bug**
When using new `navigation-icon` slot on `QCarousel` active prop is wrong.

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/demivan/pen/zYqQrOV

**To Reproduce**
1. Use `navigation-icon` slot on QCarousel
2. Try using `active` scoped property

**Expected behavior**
`active` prop should match slide carousel is currently on.

**Platform (please complete the following information):**
OS: Windows
Node: 14
Yarn: 2
Browsers: Chrome, Firefox, probably all

**Additional context**
Looks like index is multiplied by two. So if first slide is selected then second button is active, etc
No idea how it works in docs. As soon as I clicked "Edit in Codepen" this issue is visible.

**Comment by rstoenescu** [comment]
Hi,

Are you using the UMD version or Quasar CLI?

**Comment by Demivan** [comment]
Neither. I'm importing Quasar from npm and building with webpack. You can say it is like vue-cli.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v1.14.1.
