### ISSUE TITLE
QDate emits input only for year and month if the model is not null

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#7840]
**Describe the bug**
If the model of a QDate is null and a year or month is selected without having selected a day, the input event is not emitted.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/13ehpqbL/10/

**To Reproduce**
The **left** QDate with null as model
1. Select a year -> nothing happens
2. Select a month -> nothing happens
3. Select a date -> input is triggered

The **right** QDate with a value as model
1. Select a year -> input is triggered
2. Select a month -> input is triggered
3. Select a date -> input is triggered

**Expected behavior**
Input is trigger on year/month/day selection regardless of the current model state like in version 1.12.13

**Comment by hawkeye64** [comment]
@chaosKP It looks `like emit-immediately` has been deprecated.
![image](https://user-images.githubusercontent.com/10262924/95366324-85eac300-0890-11eb-8cf1-a6fc4d0a8cb1.png)

**Comment by rstoenescu** [comment]
Instead of relying on the emit-immediately prop (which is indeed deprecated), please use the additional buttons. Adding an Ok and a Cancel would be much better. https://quasar.dev/vue-components/date#Example--With-additional-buttons

**Comment by chaosKP** [comment]
Deprecated deosn't mean that it isn't working anymore... only that you shouldn't use it because there is a new/better way. ATM there is no better way to recieve a event on month/year change, so this is a clear feature regression form version 1.12..
I can't use buttons because the user shouldn't be able to select a day...

**Comment by rstoenescu** [comment]
Reopening for later posting a codepen.

**Comment by rstoenescu** [comment]
Made a reassessment. Compared to behavior from v1.12.13. You're perfectly right, also on the use case (aka "user shouldn't be able to select a day"). Fixed emit-immediately behavior and even removed the deprecation notice (due to the above).

Fix will be available in Quasar v1.14.2.
