### ISSUE TITLE
q-expansion-item change URL when expanding

### ISSUE THREAD

**Issue by brylie** [quasarframework/quasar#7841]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out a concise way to [determine which `q-expansion-item` in a group is currently opened](https://stackoverflow.com/questions/64125507/how-to-determine-which-q-expansion-item-is-open). According to the documentation, the `to` property can be used to set the URL when a user clicks on the `q-expansion-item`. However, the URL does not get set when *expanding* the `q-expansion-item`, only when clicking on the title (which doesn't seem to expand the item).

**Describe the solution you'd like**
When clicking the down arrow to expand a `q-expansion-item` containing a string value for the `to` attribute, the URL would be updated.

**Describe alternatives you've considered**
I have documented an alternative approach on the StackOverflow question:

https://stackoverflow.com/questions/64125507/how-to-determine-which-q-expansion-item-is-open

**Comment by rstoenescu** [comment]
Hi. Checked out the stackoverflow link and it seems like someone already gave a good answer. So closing.
