### ISSUE TITLE
Disable active-icon on QStepper

### ISSUE THREAD

**Issue by igonzalezprs** [quasarframework/quasar#7842]
**Is your feature request related to a problem? Please describe.**
QStepper has a default active-icon value, which overrides the 1st step icon. I'd like to have an option to set no active-icon on my QStepper, so the icon for my 1st step does not get overriden.

**Describe the solution you'd like**
Have a QStepper prop that nulls the active-icon, or set the default active-icon to null

**Describe alternatives you've considered**
Setting a computed property that checks if it's the first step and assigns the active icon to the desired one.

**Comment by rstoenescu** [comment]
Hi,

What's wrong with specifying `active-icon` prop for your first step component too? Assign it the same value as the `icon` prop.

```html
<q-step icon="map" active-icon="map" ....
```

**Comment by DevBodin** [comment]
I strongly agree with this request.

The the `active-color` property already signals which step is currently being "edited." The icon unnecessarily obscures the visual information regarding the step (which is all the more important if the stepper is in `contracted` mode, as I have them set to at narrower screen sizes).

Yes, specifying the `active-icon` on the q-step works, but doing that for every step creates a lot of redundancy to cancel out what seems should be an optional feature.
