### ISSUE TITLE
[docs] Document "hoverable" class

### ISSUE THREAD

**Issue by thedelk** [quasarframework/quasar#7843]
On the [Shadows](https://quasar.dev/style/shadows) page, in the description for the `shadow-transition` class, there is a mention of a `hoverable` class that is mentioned nowhere else in the documentation.

**Comment by rstoenescu** [comment]
Hi,

This is an obsolete class. It does not exists since anywhere between v0.10 and v0.12.
The shadow-transition class just adds the `transition` property which you can use.
