### ISSUE TITLE
Auto yarn/npm install when node_modules is missing in src-capacitor/src-cordova

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#7844]
**Describe the bug**
If I install the capacitor mode and delete node_modules it shows that capacitor isn't installed.

**Codepen/jsFiddle/Codesandbox (required)**
I can't because it's for node_modules folder and codesandbox doesn't allow to delete

**To Reproduce**
1. Create a new blank proyect
2. Execute `quasar mode add capacitor`
2. Execute `quasar dev -m capacitor -T android` or `quasar dev -m capacitor -T ios`
5. See that it works (starts the IDE)
3. Delete node_modules
3. Execute `yarn install`
2. Execute `quasar dev -m capacitor -T android` or `quasar dev -m capacitor -T ios`
5. The IDE doesn't start and an error of "capacitor don't found" it's showed

**Expected behavior**
Set the capacitor and all the required modules in devDependencies in package.json to install always with yarn install

**Comment by rstoenescu** [comment]
Hi,

What node_modules folder are you deleting? The one in the root of the project folder or the one in `src-capacitor`?

**Comment by Nisgrak** [comment]
In the root folder, i.e: if I have upload the proyect to git anyone that download the code can't use capacitor, only if removes the capacitor mode and apply again.

**Comment by rstoenescu** [comment]
A yarn install is required in the 'src-capacitor' also.

**Comment by Nisgrak** [comment]
Maybe the `quasar dev -m capacitor -T [android|ios]` would detect if exists the node_modules folder in `src-capacitor` and make a nmp\yarn install if's not.

Anyways please add to the FAQ or the troubleshooting please
https://quasar.dev/quasar-cli/developing-capacitor-apps/troubleshooting-and-tips

**Comment by rstoenescu** [comment]
I'm leaving this ticket opened because I want to auto yarn install in src-capacitor (also in src-cordova). Got a lot to handle currently so haven't looked at the code, but I remember it already does this. Regardless, will investigate and improve.

**Comment by rstoenescu** [comment]
Was about to make the necessary changes. But they are already there. Just forgot about them.
Quasar CLI checks if {src-capacitor|src-cordova}/ node_modules is there and auto-installs if it's not :|
