### ISSUE TITLE
https server with iOS capacitor

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#7845]
**Describe the bug**
Set the `https: true` in devServer in quasar.config.json in iOS and it doesn't start

Bug described and solution in https://forum.quasar-framework.org/topic/6595/capbridgeviewcontroller-swift-not-found-or-content-is-unrecognized-please-disable-https-from-quasar-conf-js-devserver-https/2

**To Reproduce**
1. Add capacitor mode `quasar mode add capacitor`
1. Set `https: true` in devServer in quasar.config.json 
2. Execute `quasar dev -m capacitor -T ios`
3. The error is showed and the IDE doesn't start

**Expected behavior**
The IDE starts and load the https.
With the fix proposed in the forums works like a charm

**Screenshots**

**Additional context**
https://forum.quasar-framework.org/topic/6595/capbridgeviewcontroller-swift-not-found-or-content-is-unrecognized-please-disable-https-from-quasar-conf-js-devserver-https/2

**Comment by rstoenescu** [comment]
Path to capacitor iOS bridge changed during their v2, which made Quasar CLI to stop working correctly.
Thanks for reporting this.

Fix will be available tomorrow in "@quasar/app" v2.1.5
