### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by luizhenriquerdias** [quasarframework/quasar#7852]
=== npm audit security report ===                        

  High            Prototype Pollution in node-forge                             

  Package         node-forge                                                    

  Patched in      >= 0.10.0

  Dependency of   @quasar/cli [dev]

  Path            @quasar/cli > selfsigned > node-forge

  More info       https://npmjs.com/advisories/1561

**Comment by rstoenescu** [comment]
Hi,

Thank you for reporting this, but please follow the correct steps for logging a security issue, which is to select the security template.

"@quasar/cli" v1.1.2 has been released.
