### ISSUE TITLE
adding min-width to the q-splitter to address min-width issues when using the precentage as the unit

### ISSUE THREAD

**Issue by faxinwang** [quasarframework/quasar#7856]
**Is your feature request related to a problem? Please describe.**
when using the q-splitter with precentage as the unit, it is very hard to guarantee the min-width of both panels, especially of the nested q-splitter.

**Describe the solution you'd like**
provide attributes like `min-width-before` and `min-width-after` to handle the problem.

**Comment by pdanpdan** [comment]
Hello.
If you haven't solved the problem with CSS please reopen with a codepen showing what you have tried.
Thank you
