### ISSUE TITLE
[docs]

### ISSUE THREAD

**Issue by gaw89** [quasarframework/quasar#7858]
I am creating this as a doc report as I don't know if it is actually a bug.  I am using quasar 1.12.13 and @quasar/app 1.9.6.  When I use the Dialogs plugin (awesome feature, by the way) with a custom component, it works flawlessly if I import the component at the top of my script (e.g. `import MyComponent from './MyComponent.vue'`).  However, if I try to use a dynamically-loaded custom component, I get `Error in mounted hook: "TypeError: Cannot read property 'show' of undefined"` from QGlobalDialog:

```
this.$q.dialog({
    component: () => import('./MyComponent'),
    parent: this
})
```

I am not certain if this is intended to work or not, as it isn't addressed in the docs.  I would recommend:
1. If it is supposed to work, fix the bug
2. If it isn't supposed to work, put one of your handy "Warning" or "Tip" notes in the docs for the Dialogs plugin.

If it's not supposed to work, I'm happy to try and create a PR for updating the docs.  If it is supposed to work, my JS skills are sadly not sufficient to fix it 😭, but maybe I'll get there someday...  

**Thank you for your incredible work on this amazing framework!!!**

**Comment by TobyMosque** [comment]
I don't think that is a bug.

maybe we can improve the docs with something like that:
```js
const MyComponent = await import('./MyComponent')
this.$q.dialog({
  component: MyComponent,
  parent: this
})
```

or even check if the component is a promise and wait for them.

**Comment by gaw89** [comment]
Dude, you guys are the best.
