### ISSUE TITLE
{request] searchString prop for QTree component

### ISSUE THREAD

**Issue by jmellicker** [quasarframework/quasar#786]
I think it would be cool to be able to optionally pass a 'searchString' prop to the QTree component. Maybe the HTML could be something like:

    <span v-if="!this.searchstring || model[title].indexOf(this.searchstring)" v-html="model.title"></span>
    
?

**Comment by rstoenescu** [comment]
Hi,

I believe the exactly same thing can be done in userland by using a computed variable (along with a QSearch) which filters your tree object model based on a searchString and then feeding that computed variable as model for QTree, so not really useful to bloat QTree with this. This also allows total freedom of how the filtering itself is being done.

You can use the forum if you need help on this one.

Thanks.

**Comment by jmellicker** [comment]
That's probably best, thanks for the advice!
