### ISSUE TITLE
ios 14 & cordova: q-header doesnt respect notch safe-areas

### ISSUE THREAD

**Issue by perelin** [quasarframework/quasar#7862]
**Describe the bug**

When building for iOS with Cordova the q-header element doesnt respect the notch spacing (as it should according to https://quasar.dev/quasar-cli/developing-cordova-apps/troubleshooting-and-tips#Status-bar-and-notch-safe-areas)

![B3323991-FD08-4A29-A670-3A841E9E010E](https://user-images.githubusercontent.com/517976/94995495-eb903400-059e-11eb-8a8c-09bd8d1fb194.jpeg)

iPhone 11 / iOS 14.0.1
@quasar/cli v1.1.2
@quasar/app v2.1.1
Cordova 10.0.0

Since Apple started rejecting Apps build with UIWebView, I use the Cordova built-in WKWebView capabilities as described in https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html 
(Ionic Webview Plugin breaks Firebase Auth and is therefore not an option)

**Codepen/jsFiddle/Codesandbox (required)**

Code is based on the demo project. HTML currently looks like this

<img width="616" alt="image" src="https://user-images.githubusercontent.com/517976/94995524-3ad66480-059f-11eb-849c-e6a7ced07a8e.png">

**To Reproduce**

Build the demo Project for iOS with the lib configuration described above.

**Expected behavior**

q-header adds some spacing on ios to avoid being placed directly under the notch

**Comment by rstoenescu** [comment]
Hi,

This has worked flawlessly for lots of previous iOS versions. Looking forward to investigate and see what Apple has changed now :)

**Comment by perelin** [comment]
Can I somehow support the effort?

**Comment by perelin** [comment]
Hold the horses: I just build the vanilla Quasar Demo Project and checked it on device and it looks fine. So there must be some issue in my code. I´ll try to nail this down further and get back to you. For now we can close this I think.

**Comment by perelin** [comment]
Ok, it seems these classes are missing in my app. Even though the code and configuration is pretty much the same one as far as I can tell. Any idea where I can look next?

![image](https://user-images.githubusercontent.com/517976/95013456-ade3e780-0640-11eb-9e61-692930da62c4.png)

**Comment by perelin** [comment]
I fixed it by creating a vanilla demo project and copying over my code and config file by file. Now it runs and everything looks fine. Very strange. Maybe some old experiment / configuration that I have not cleaned up was causing the issue.

**Comment by rstoenescu** [comment]
Glad to see everything's working again for you.

**Comment by rstoenescu** [comment]
And thanks for reporting back on the progress so we don't lose time doing a wild goose chace :)
