### ISSUE TITLE
A Vertical Nested Sliding Menu in the Drawer

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#7866]
**Is your feature request related to a problem? Please describe.**
Used for things like mobile product category trees in e-commerce stores to filter products by a category.

**Describe the solution you'd like**
The ability to have a q-list that when clicking the right arrow slides in a new list of options that can also have sub-options. Likely placed within the standard navigation drawer. Good for things like a category lists. Here's a rough example of how it might work:
https://guansunyata.me/guansunyata/vue-nested-menu

But with the ability to click on the parent item or the arrow separately. And keeping the animation aspect.

**Describe alternatives you've considered**
guansunyata/vue-nested-menu
Perhaps a q-list, transition animation, and translateX would solve the problem?
If it's possible to already build this in Quasar, perhaps an example in the documentation of how to construct it would be helpful.

**Additional context**
<img width="360" alt="Screen Shot 2020-10-05 at 11 17 18 AM" src="https://user-images.githubusercontent.com/7112345/95105166-5e62f180-06fc-11eb-9fb5-0aff2a52a8bf.png">

**Comment by metalsadman** [comment]
@codingfriend1 Use something like qpanels https://codepen.io/metalsadman/pen/dyMaeVe

Click on settings.

**Comment by hawkeye64** [comment]
Nice solution @metalsadman ! I like it!

**Comment by codingfriend1** [comment]
Thanks @metalsadman! That does work well!
