### ISSUE TITLE
[docs] ANDROID_HOME is replaced with ANDROID_SDK_ROOT

### ISSUE THREAD

**Issue by Floriantoine** [quasarframework/quasar#7867]
https://quasar.dev/quasar-cli/developing-cordova-apps/preparation

for install cordova on Quasar app in Unix Variable  ANDROID_HOME is deprecated, it's ANDROID_SDK_ROOT

**Comment by hawkeye64** [comment]
Looks like both should be set until others are using the latest: https://github.com/apache/cordova-android/issues/949

**Comment by hawkeye64** [comment]
@Floriantoine Fixed with this commit https://github.com/quasarframework/quasar/commit/dfdf7e20f4a5d31a03b7736815bbc65efb88d9ae

Thanks for bringing this to our attention :heart: 
Will be in the next docs release.
