### ISSUE TITLE
QIntersection did not work in cross origin iframe

### ISSUE THREAD

**Issue by mmis1000** [quasarframework/quasar#7868]
**Describe the bug**
The q-intersection never updates in a cross origin iframe.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.
https://jsfiddle.net/mmis1000/y6wjpotr/
**To Reproduce**
1. Create a app with a q-intersection outside of viewport
2. Load the page in a `cross origin` iframe
3. Scroll up until the q-intersection element is in the viewport
4. Realize It never load the content

**Expected behavior**
It should load the content

**Platform (please complete the following information):**
OS: Any
Node: 12
NPM: 6
Yarn: --
Browsers: Any
iOS: --
Android: --
Electron: --

**Additional context**

The `rootBounds` of Intersection entry will always be `null` if the page is in a cross origin iframe due to security concern.
The root need to be something else or the check of `rootBounds` must be removed in this situation.

**Comment by hawkeye64** [comment]
@mmis1000 This will be fixed with this commit: https://github.com/quasarframework/quasar/commit/690bb69e3598ce5fecfa101044ed097ec0896506#diff-5d82619b838dd0bc896c67dcfe50d15e
There is a new property `root` that you will need to set in order to have it work in an iframe. The root needs to be an ancestor within the iframe. The issue here is that the default root is the default view. This new property allows you to change that so QIntersection will work properly in an iframe.
Fix will be in v1.14.2

**Comment by mmis1000** [comment]
Unfortunately that didn't works with safari even you set the `root` to `document` due to safari bug.

Safari on ios 13 throws when root is document
Safari on ios 14 **scrolls the document area** when it absolutely shouldn't.
Change the q-page to a fixed height container and use it as root might fix the intersection problem.
But nested scroll container(you can't make the body overflow hidden on safari, I don't know why) don't really plays well with buggy safari.

**Comment by hawkeye64** [comment]
@mmis1000 Are you using the component or directive?

**Comment by mmis1000** [comment]
The component (for lazy loading)

**Comment by hawkeye64** [comment]
The component, which will be released in v1.14.2, is working on iOS with the new `root` prop
![image](https://user-images.githubusercontent.com/10262924/95217740-c83cd300-07b0-11eb-9ae0-2ed63cff3c36.png)

It also is working, when hosted in an iframe:
![image](https://user-images.githubusercontent.com/10262924/95217962-03d79d00-07b1-11eb-9674-551f1a5f8e11.png)

The directive has always had the ability to specifiy a `root`, so I am not sure why you had to "monkey patch" it.

**Comment by mmis1000** [comment]
Do specify root as `document` and scroll down actually work?
I only use it for lazy load, so all I care is viewport.

But neither set the `document`  (the iframe area), `null` (the whole screen) works with safari.

**Comment by hawkeye64** [comment]
The default root is always the highest available anscestor. Probably `document.body`, I don't know for sure. But, when in an iframe, it can't access the default root so needs to be given a different root, that is contained within the iframe.

**Comment by mmis1000** [comment]
The default when you set the root to `null` is always the  `document` of the top window.
https://w3c.github.io/IntersectionObserver/#intersectionobserver-implicit-root

So the `rootBounds` will be `null` if it is not a same origin frame.
Because give you the access to it leaka the top windows's size.

However, the event will still fires, just without the `rootBounds`

https://w3c.github.io/IntersectionObserver/#dom-intersectionobserverentry-rootbounds
