### ISSUE TITLE
q-editor model not always updating display

### ISSUE THREAD

**Issue by radixcorp** [quasarframework/quasar#7869]
**Describe the bug**
In some cases where the editor contents are deleted or changed, the editor will not update correctly when the model changes. This appears to be a new issue after upgrading from 1.13.1

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/d0nz5euw/5/

**To Reproduce**
Example #1:
    Click One,Two,Three buttons in sequence. The editor contents change accordingly
    Click Blank - nothing happens

Example #2:
    Restart to clear everything.
    Click One,Two,Three buttons in sequence (don't click Blank). The editor contents change accordingly
    Click One
    Select the editor contents (do not delete). Overwrite the editor contents by typing 'three'
    Click Two - editor contents change
    Click Three - nothing happens
    Click One - editor contents change
    Click Three - nothing happens

**Expected behavior**
The editor contents should change to reflect the model.

**Platform (please complete the following information):**
OS: Windows
Node: 12.18.2
NPM: 6.14.5
Browsers: Chrome

**Additional context**
Did not see the issue in Quasar 1.13.1

**Comment by radixcorp** [comment]
It appears that  `$data.lastEmit` isn't being cleared when the model changes.  As a workaround,` $data.lastEmit = null` before the model changes, seems to mask the problem.

**Comment by hawkeye64** [comment]
@radixcorp Thanks for finding this! :heart: 
Fix will be in quasar v1.14.2
