### ISSUE TITLE
after migrating from 0.13 to 0.14, "Unknown custom element: <q-data-table>"

### ISSUE THREAD

**Issue by ssuess** [quasarframework/quasar#787]
Quasar: 0.14 beta
OS: Mac OS Sierra
Node: 7.10.0
NPM: 4.2.0
Browsers: Chrome
iOS: n/a
Android: n/a
Any other software related to your bug:

### What did you get as the error?
`Unknown custom element: <q-data-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
### What were you expecting?
That it would work exactly as it did in 0.13, the code is identical in that component
### What steps did you take, to get the error?
Migrated from 0.13 to 0.14 beta with the following steps:
1. `quasar init default#beta myproject_quasar14`, `cd myproject_quasar14`, `npm install` (and deps)
2. `quasar dev`
3. copied a .vue file from my old components folder (0.13) to my new one
4. adapted router.js, main.js to match 0.13

Error is present whether I include this in the default Hello.vue or replace Hello.vue in router.js with just my component (Dashboard.vue). Same code runs fine in 0.13

**Comment by rstoenescu** [comment]
Please read the following links:

* http://beta.quasar-framework.org/components/introduction-for-beginners.html (especially the section for using components and directives)
* http://forum.quasar-framework.org/topic/522/upgrade-guide-for-0-14-beta

**Comment by ssuess** [comment]
Thanks, that helped. For some reason in 0.13, I didn't need to import components individually, but in 0.14, I did. All working now.

**Comment by rstoenescu** [comment]
Yes, lots changed. Be sure to read the v0.14 docs carefully.
Requiring components is now mandatory to take advantage of tree shaking in webpack.
