### ISSUE TITLE
feat: pass arguments to npx cap and choose mode npx cap sync or npx cap copy

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#7870]
**Is your feature request related to a problem? Please describe.**
I know how to pass arguments to cordova (with `--` )
like quasar dev -m android -- someargs
but how i can pass arguments to capacitor?

Why?
when running `quasar build -m capacitor -T ios -s`
it updates pods versions with new
link: https://github.com/ionic-team/capacitor/issues/2242#issuecomment-565434091

I setup CI/CD, in my workflow I need disable `npx cap sync` (only use `npx cap copy`) to save compile time.
It's possible to support in Quasar

**Describe the solution you'd like**
Implement possibility to pass arguments to **npx cap** and choose mode **npx cap sync** or **npx cap copy**

**Comment by bazuka5801** [comment]
@rstoenescu can you help with this feature, please ;)
Our ci step take >5 min instead few secconds.
How we can add some flag to capacitor cmd `quasar build -m capacitor -T ...`

**Comment by rstoenescu** [comment]
Hi. You'll have to wait a bit for this one. Currently in the middle of something complex with the vue3 work.

**Comment by bazuka5801** [comment]
> Hi. You'll have to wait a bit for this one. Currently in the middle of something complex with the vue3 work.

Okay, no problem 😉
On hold))

**Comment by rstoenescu** [comment]
New quasar.conf.js > capacitor prop -> capacitorCliPreparationParams (default value: [ 'sync', ctx.targetName ])
Will be available in "@quasar/app" v2.1.5.

It would be nice if your company would take a look at https://donate.quasar.dev ;)

**Comment by bazuka5801** [comment]
@rstoenescu 
Ohh, Thank you very much 😍
Now I can don't worry about CI/CD))
