### ISSUE TITLE
Window component

### ISSUE THREAD

**Issue by mirshahreza** [quasarframework/quasar#7872]
Window component can use for floating a document over another (resizable / draggable / closable / multiple instance ...).
This is a base component and is not about other components
Maybe by extending the modal component.

**Comment by hawkeye64** [comment]
@mirshahreza 
If you have an issue with QWindow, you should add issues to it's repo: https://github.com/quasarframework/quasar-ui-qwindow/issues
Other than that, I really don't see a question here, so have no fathomable answer for you.
