### ISSUE TITLE
Drawer feature

### ISSUE THREAD

**Issue by mirshahreza** [quasarframework/quasar#7873]
**Is your feature request related to a problem? Please describe.**
I it is about drawer . there must be an option for closing the drawer by clicking anywhere and an dark overlay to covering the page content

**Comment by rstoenescu** [comment]
When in mobile mode, there is a dark overlay for QDrawer and it can be closed by clicking/tapping on it.

**Comment by mirshahreza** [comment]
And why it is disable at desktop mode? it is very useful for end user and it seems is important for UX reasons.
Clicking anywhere is a good UX but clicking a small button is harder and is not good idea.

**Comment by rstoenescu** [comment]
You can enable it by changing the breakpoint or by setting the behavior prop to "mobile".

**Comment by mirshahreza** [comment]
Well done 👍
