### ISSUE TITLE
Dialog overlay

### ISSUE THREAD

**Issue by mirshahreza** [quasarframework/quasar#7874]
**Is your feature request related to a problem? Please describe.**
It is about the dialog overlay. When a dialog is appeared the scroll bar is show in a light color  that makes a bad view. It is better to cover it by the overlay. this way we get a better view

**Comment by rstoenescu** [comment]
This is by design, to alleviate a much worse problem: flickering of the dialog content (since scrollbar disappears).

**Comment by mirshahreza** [comment]
Yes but there is a solution that bootstrap use it and is easy :
https://getbootstrap.com/docs/4.5/components/modal/

**Comment by rstoenescu** [comment]
I clearly remember I had the same idea but gave it up due to other issues. Reopening to reassess.

**Comment by mirshahreza** [comment]
💯
