### ISSUE TITLE
The q-select is changing the value after click

### ISSUE THREAD

**Issue by rafabattazza** [quasarframework/quasar#7875]
When I select one value with a mouse click, and move the mouse to another item and press the TAB, the option selected change.

**Test on quasar.dev page, in first q-select component**
1. Click on q-select to open drawer
2. Click in first item (e.g. 'Google')
3. Move the mouse to another item (e.g. 'Twitter')
4. Press TAB

**Additional context**
Workaround: set **transition-show="none" transition-hide="none"**

**Comment by hawkeye64** [comment]
@rafabattazza As specified in the docs:
```
pressing TAB (or SHIFT + TAB if use-chips is not set or the first QChip is selected) will navigate to the next or previous focusable element on page
```
![image](https://user-images.githubusercontent.com/10262924/95363255-72d5f400-088c-11eb-9e39-194459995861.png)
