### ISSUE TITLE
Studio layout

### ISSUE THREAD

**Issue by mirshahreza** [quasarframework/quasar#7876]
**Is your feature request related to a problem? Please describe.**
It is about the layout component. I manually create a fixed layout like visual studio but you can create a new layout Skelton officially so it can be a good idea because many web applications needs this layout.

Header / Footer / Right Pane / Body Pane with a tabbed document place
  

**Describe the solution you'd like**
the implementation is very easy with splitter and tab components.

**Comment by rstoenescu** [comment]
Hi,

That's the point. It's very easy to do it with QSplitter and QTabs... it's not in everyone's interest to bloat the framework with obvious redundancies...

**Comment by mirshahreza** [comment]
Yes it is very easy but your framework can be better than other with completed practices. the official practices can be maintain and can be continuesly grows. but personal practices can be forgotted

**Comment by rstoenescu** [comment]
It is better than others. The use-cases are endless, so it's never possible to offer a complete set of practices. Regarding using a QSplitter and QTabs for your case, why not reach out for help on our https://chat.quasar.dev ? That's what the community is there for :)

**Comment by mirshahreza** [comment]
👍
