### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by mirshahreza** [quasarframework/quasar#7877]
**Describe the bug**
I am using Quasar with requirejs. when I use the Quasar without the requirejs dialog animations is well but when I integrate it with requirejs it works but with no animation !!!!

I can send you a visual studio project if needed

**Comment by outofmemoryagain** [comment]
@mirshahreza please provide either a codepen or a minimal quasar project in a github repo that reproduces the issue.  Visual Studio or Visual Studio Code?  Visual Studio is not a tool that most web developers have available, so it would be difficult for us to reproduce the issue.

**Comment by rstoenescu** [comment]
Please reopen with the requested information. Thanks.

**Comment by mirshahreza** [comment]
I am proofing another component suite so I think this case is closed for me. thank u again maybe later if needed
