### ISSUE TITLE
Drawer plugin

### ISSUE THREAD

**Issue by mirshahreza** [quasarframework/quasar#7878]
The Drawer layout utility must be hard coded at the html. It is good idea create a new plugin for it similar Dialog plugin that user can call it in code level like this
this.$q.drawer({...options...});

**Comment by Arquetipo28** [comment]
You mean a function to open and close your drawer but built in Quasar?

**Comment by mirshahreza** [comment]
Yes, Exactly

**Comment by pdanpdan** [comment]
Hello. The drawer belongs to the layout, but you can always:
- use render functions to generate dynamically generate it
- use a side dialog to put the content there
