### ISSUE TITLE
q-dialog unexpectedly closed by $q.dialog on top if it

### ISSUE THREAD

**Issue by carueda** [quasarframework/quasar#7879]
**Describe the bug**

Probably not a bug, but still a bit surprising behavior:  persistent `q-dialog` gets closed upon a `$q.dialog` is open on top of it.

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/carueda/pen/oNLNMNB

**To Reproduce**

As demonstrated in the codepen above, the (mis?)behavior only occurs if there's a dropdown involved, which launches the first `q-dialog`, from which the subsequent `$q.dialog` is opened:

1. Open the dropdown and click the button that makes the `q-dialog` open
2. Click the button that triggers the `$q.dialog` call

Observed behavior: 

Unexpectedly, the `q-dialog` gets closed.

**Expected behavior**
The `q-dialog` remains open, especially if it has the `persistent` property set (as in the codepen).

**Additional context**

Noted with previous Quasar versions but tested now with v1.14.1.

Note: again, this might just be some improper setup of the components.  In fact, just moving the `<q-dialog>` outside of the dropdown makes the general behavior proceed as expected.  But still it's a bit surprising especially when having that `persistent` prop.  Thanks!

**Comment by rstoenescu** [comment]
Hi,

This is not a bug but a normal behavior. The QDialog is placed under the default slot of QBtnDropdown... which is only rendered as long as the dropdown menu remains opened. But you click outside of it (on the button from the dialog to trigger the $q.dialog()) so it gets closed -> then vue destroys the QDialog. Place the QDialog outside of the dropdown.

**Comment by carueda** [comment]
Understood ...  Thanks for the quick reply!
