### ISSUE TITLE
IE 11 - Buttons width

### ISSUE THREAD

**Issue by lusaxxx** [quasarframework/quasar#788]
Quasar: 0.14
OS: Windows
Browsers: IE 11.0.9

### What did you get as the error?
![image](https://user-images.githubusercontent.com/15838305/29171232-14dde7b0-7ddc-11e7-873d-07d3394a9da5.png)

![image](https://user-images.githubusercontent.com/15838305/29171372-a6fc0212-7ddc-11e7-84e5-ab4652eb00f8.png)

Buttons width is wrongly calculated -> basic layout , onhover  etc are then wrongly rendered

**Comment by rstoenescu** [comment]
Please confirm that you enabled IE support: http://beta.quasar-framework.org/guide/browser-support.html

**Comment by lusaxxx** [comment]
Thx...my bad :(

**Comment by rstoenescu** [comment]
No worries. The reason IE support is added separately is that in most of the cases devs don't need it and since it adds a few tens of Ks to the build it doesn't makes sense to always have it.

Cheers.
