### ISSUE TITLE
[docs] Dark mode for Docs

### ISSUE THREAD

**Issue by geoidesic** [quasarframework/quasar#7881]
Please can we have a switch on the Docs for setting it to Dark Mode?

Since quasar has this built-in and the docs are built on quasar, it should be trivial to set up I think.

**Comment by rstoenescu** [comment]
Hi,

It's a good idea, but it's not so trivial, as the whole website needs a Dark design. Showing a QCheckbox/QToggle for switching Quasar Dark mode is just the first step, but it can't use the current colors. Unfortunately, we currently don't have the time for this "nice to have". But a dark mode for the docs website will come at some point.

**Comment by mra-dev** [comment]
Why not. I wish i could help. It's really annoying while working in dark and suddenly have to switch to documentation, and ....

**Comment by MilosPaunovic** [comment]
There is a PR https://github.com/quasarframework/quasar/pull/13177 for it in the works; it will be available soon.

**Comment by adgower** [comment]
@geoidesic https://discord.com/channels/415874313728688138/415880302229979137/1039912034197839964
