### ISSUE TITLE
Quasar with OneSignal & Capacitor

### ISSUE THREAD

**Issue by NickHatBoecker** [quasarframework/quasar#7886]
Hey guys,

I'm desperately trying to integrate OneSignal Push Notifications in my quasar app with capacitor.
Can anyone help please?

I know there is also a quasar plugin from some user for this:
https://github.com/motia/quasar-app-extension-onesignal

But I couldn't get this to work either. :(

Best regards
Nick

**Comment by NickHatBoecker** [comment]
Okay I managed to add OneSignal, so I can receive notifications, by following the [Native iOS Tutorial](https://documentation.onesignal.com/docs/ios-sdk-setup).

BUT I need to tell my API the OneSignal ID, **after** the user logs in. So I guess I have to hand OneSignal from Native/Capacitor to Vue Code...? Is this even possible?
Or is it the other way around? In Vue Code I save the `accessToken` in LocalStorage. Can I get this from Native files?

I would be very grateful for any tips.
Thank you very much!

Best regards
Nick

**Comment by alexpvieira** [comment]
Do you really need to use OneSignal? I stoped using OneSignal on my app and started using Firebase instead, following [https://capacitorjs.com/docs/guides/push-notifications-firebase](url) and everything works fine for me.

**Comment by NickHatBoecker** [comment]
@alexpvieira Yes, because the API, which is maintained by another company, is using it.

I finally got it working with OneSignal and wrote a [blog article](https://blog.nick-hat-boecker.de/onesignal-push-notifications-quasar/) about it. I dont know if I'm allowed to post it here (Feel free to remove the link). Unfortunately it's in German.
