### ISSUE TITLE
iOS app open Safari tab automatically when opening the app.

### ISSUE THREAD

**Issue by phuclh** [quasarframework/quasar#7890]
**Describe the bug**
I have integrated Stripe.com into my app.

```
<script src="https://js.stripe.com/v3/"></script>
```

When I open the app in iOS, Safari always open this link `https://js.stripe.com/v3/` automatically. I don't have it in Android app.

**Platform (please complete the following information):**
```
Operating System - Darwin(19.4.0) - darwin/x64
NodeJs - 10.21.0

Global packages
  NPM - 6.14.4
  yarn - 1.22.5
  @quasar/cli - 1.1.2
  cordova - 10.0.0

Important local packages
  quasar - 1.12.8 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.9.6 -- Quasar Framework local CLI
  @quasar/extras - 1.8.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.3.4 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - 7.3.2 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
```

**Comment by rstoenescu** [comment]
Hi,

How do you know it's not a bug in Stripe's code or Capacitor and it's Quasar's fault?

**Comment by phuclh** [comment]
@rstoenescu yeah, I am not sure the bug is from Stripe, Cordova, or Quasar. Just don't understand why Stripe js is opened in iOS, not Android.

It was a normal script tag: `<script src="https://js.stripe.com/v3/"></script>`

**Comment by rstoenescu** [comment]
One thing is for sure. It's impossible this to be from Quasar.
