### ISSUE TITLE
QTable top-row slot not displayed when using virtual-scroll property 

### ISSUE THREAD

**Issue by neomobil** [quasarframework/quasar#7895]
On the QTable component when the virtual-scroll property is used, the top-row slot is not displayed

https://jsfiddle.net/neomobil/tyLecrhx/5/

Remove/Add the virtual-scroll property

**Expected behavior**
The top row should also be displayed when the virtual-scroll property is used

Browsers: Chrome
Other Bowsers not tested

**Comment by jayQS** [comment]
@pdanpdan
@neomobil Facing the same issue for both the slots ['top-row', 'bottom-row']
These slots disappear while using virtual-scroll
Found any solution for this issue?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.0.
