### ISSUE TITLE
QSelect - Improve keyboard support (Home/End - PgUp/PgDown)

### ISSUE THREAD

**Issue by labs20** [quasarframework/quasar#7898]
I need to deliver navigational control over the options list using also the keys:
  **Home**           => Go to first option
  **End**              => Go to last option
  **Page Up**      => Scroll up one page* of options  
  **Page Down** => Scroll down one page of options
\* a page being the amount of options displayed on the popup viewport.

Also, the wrapping **last <=> first <=> last** option using keyboard should be optional, controlled by a property.

**Describe the solution you'd like**
Implement natively the support for mentioned keys and create a "no-wrap" property to enable/disable such behaviour.

**Describe alternatives you've considered**
I've tried to intercept key events to implement it by myself, but looks like those events are not fired from the options popup.

**Additional context**
Firing keyboard and mouse events from popup interaction would be a nice thing.

Thanks

**Comment by pdanpdan** [comment]
Hello.
About disable navigation wrapping - it won't be done - it's pointless as if someone overshoots by mistake he can get back with one keypress.
About Home/End - they will only work if QSelect does not have `use-input`.
About Page Up/Down - I'll see what can be done :)

**Comment by pdanpdan** [comment]
this is available in v1.15.0
