### ISSUE TITLE
QLayout doesn't bring on top of the page on changing page 

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#7899]
**Describe the bug**
When scrolling down a page, navigate to an other and returning to it will load the page from the last visited offset position.

**Reproduce case**
https://github.com/vandelpavel/layout-problem

**To Reproduce**
1. scroll page1 to bottom
2. go to page2
3. go back to page 1 USING THE FOOTER
4. you will see that the page is not loaded on top even if:

```js
// src/router/index.js
const Router = new VueRouter({
    scrollBehavior: () => ({ x: 0, y: 0 }),  // <------------------------------ Notice
    routes,

    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE
  });
```

**Expected behavior**
The page should be loaded from top.

**Platform (please complete the following information):**
OS: Windows
Node:v12.16.3
Yarn: 1.21.1
Browsers: chrome

**Additional context**
I found that changing the second last letter of the q-layout view in F solve the problem BUT the footer would be sticked to the bottom of the screen.

**Comment by rstoenescu** [comment]
Hi,

Isn't this a Vue Router bug instead? Quasar does not handles the page scrolling index at all.

**Comment by vandelpavel** [comment]
@rstoenescu 
Actually i don't know. I can't explain why it works with all other combinations except that one.
My guess is that when the scrolling phase is "activated" the page isn't fully loaded and in some kind of way the "focus" remains on the footer and then the page loads on top. So i decided to return a promise with a set timeout. It's obviously a work around but it could be helpful:

```js
// src/routes/index.js

      scrollBehavior(){
      return new Promise((resolve) => {
      setTimeout(() => {
        resolve({ x: 0, y: 0 })
      }, 0)
    })
```

**Comment by hawkeye64** [comment]
@vandelpavel You can also try this:
```js
export default function (/* { store, ssrContext } */) {
  const Router = new VueRouter({
    scrollBehavior (to, _, savedPosition) {
      return new Promise(resolve => {
        setTimeout(() => {
          if (to.hash !== undefined && to.hash !== '') {
            const el = document.getElementById(to.hash.substring(1))

            if (el !== null) {
              resolve({ x: 0, y: el.offsetTop - el.scrollHeight })
              return
            }
          }

          resolve(savedPosition || { x: 0, y: 0 })
        }, 100)
      })
    },
    routes,

    // Leave these as they are and change in quasar.conf.js instead!
    // quasar.conf.js -> build -> vueRouterMode
    // quasar.conf.js -> build -> publicPath
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE
  })

  return Router
}
```
