### ISSUE TITLE
Tipster / Product tour component

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#79]
## Tipster Component

Highlight areas of your UI to help user understand what they are for; something like helping the user know about hidden or non-intuitive features of your UI.
Example: User can swipe here or there, and so on…

**Comment by spectrolite** [comment]
That would be great, esp. for the web mobile platform where people aren't always expecting swipe actions to be available (but quasar handles it great). I wish I had a simple way to attach a UI tip overlay to a tag, and show a curved arrow and/or a little hand with pointed finger and a few words...

**Comment by forgottencreature** [comment]
:+1: This component would seal the deal for me. Absolutely am going to need it. Glad to see it on the roadmap. With that being said, I'm assuming it didn't make the cut for 0.14?

**Comment by rstoenescu** [comment]
Unfortunately, no. But there will be implemented soon as time allows. Thank you for your patience.

**Comment by murbanowicz** [comment]
@MartinMuzatko  - either you made misstype or they've changed the link: https://kamranahmed.info/driver.js/

I think it is exactly what @rstoenescu mean by tipster, but I may be wrong.

**Comment by rstoenescu** [comment]
Yes, it will be something like what driver.js does.

**Comment by saveroo** [comment]
i use vue-intro.js instead

**Comment by darkscript** [comment]
@rstoenescu I know on the milestones there are more urgent tasks but this tipster component could be amazing

**Comment by rstoenescu** [comment]
We are sorry but our bandwidth doesn't allows us to create this component. At least for now.

**Comment by goforu** [comment]
Is there any lib compatible with quasar? I tried vue-shepherd not working
