### ISSUE TITLE
Feature Request: Icons and click events for the data table

### ISSUE THREAD

**Issue by hawkleaf** [quasarframework/quasar#790]
I'd like to request some features for the data table, they are simple but very handy and add good customisation.

First of all I'd like to be able to bind a click event my rows, I'm using the data table as an index. I think it'd be a lot cleaner to just have the row clickable instead of putting in a column with a button to view a resource. An event like @refresh containing the row that has been clicked on would be sufficient and very modular. I have no idea what would be the best implementation as I'm not a Vue guru ^^

Secondly I would like to be able to simply give my column an icon name which it will then prepend to the column's header. This is not really functional although it does add a nice touch to the data-table component.

Like so:
```
{ label: 'Title', field: 'title', width: '150px', filter: true, icon: 'some_icon'},
```

Thanks for the hard work you put in Quasar framework, I'm loving it!

**Comment by rstoenescu** [comment]
v0.15 will contain a complete overhaul of QDataTable, extending its functionality and making it much more customizable. There are more tickets opened for this component and all are going to be included in the overhaul.

**Comment by rstoenescu** [comment]
Closing as code is ready (and even expands on the original request) in future v0.15.
