### ISSUE TITLE
Blank slides showing when more than 1 carousel are shown

### ISSUE THREAD

**Issue by aarzuagat** [quasarframework/quasar#7900]
![quasar](https://user-images.githubusercontent.com/31313488/96018554-69630380-0e19-11eb-9d2d-6e792f180cbe.png)
These 3 elements are sliders.... Image 3 is a slider...but it just have 2 slides....other have 5. When 3 get a slide number higher than 2, it comes blank!!!
Any idea? Please help... It should restart at 1 and let other slides to end at 5th slide.

**Comment by rstoenescu** [comment]
Hi,

This is normal. You are setting the model to a non-existent slide for the third carousel. And the model is king.
Assuming that you are using the "infinite" property for all three carousels, then did you actually mean to use a ref on them and call next()?

Can't help much if no https://codepen.quasar.dev or https://jsfiddle.quasar.dev or https://codesandbox.quasar.dev is provided...
