### ISSUE TITLE
How can i apply vue.config.js in quasar-cli, or is there anyway i can config such as 'ignoredElements' to allow third plugins not warn me.. 

### ISSUE THREAD

**Issue by zta7** [quasarframework/quasar#7902]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

This config is not necessary since you can easily do it in a [boot file](https://quasar.dev/quasar-cli/boot-files).

```js
import Vue from 'vue'

// https://vuejs.org/v2/api/#ignoredElements
Vue.config.ignoredElements = [
  'my-custom-web-component',
  'another-web-component'
]
```
