### ISSUE TITLE
Issue of getting data of Coockie (this.$q.cookies.get('id'))

### ISSUE THREAD

**Issue by AbingPj** [quasarframework/quasar#7903]
![Coockie](https://user-images.githubusercontent.com/38340100/96121552-cb5b6000-0f22-11eb-9e34-a7c7d5ec138b.JPG)

When I get the cookie named "id" it will return null/undefined. But when I checked it on the browser the cookie named "id" has been duplicated and the other one has value 80. I want to get the id with value 80. It will only happens when I refresh the dashboard page.  the cookie named "id" was set on the login page.

**Comment by rstoenescu** [comment]
Hi,

As you highlighted, one of the cookie has been set with path "/" and one with path "/dashboard". So when you retrieve it, the current path is taken into account (that's how browsers work).

Remove the second offending cookie (from browser devtools) -- AND also revise your code to set this cookie with path "/" instead of "/dashboard".

**Comment by AbingPj** [comment]
> Hi,
> 
> As you highlighted, one of the cookie has been set with path "/" and one with path "/dashboard". So when you retrieve it, the current path is taken into account (that's how browsers work).
> 
> Remove the second offending cookie (from browser devtools) -- AND also revise your code to set this cookie with path "/" instead of "/dashboard".

I was set it in "/" path in Login page.
![image](https://user-images.githubusercontent.com/38340100/96204434-e8317b00-0f96-11eb-8f08-8f160fc18c4a.png)

after successful login, it will direct to the /dashboard path. if user try to refresh/hard refresh the dashboard page. it will create another cookie in the browser with "/dashboard" path.

this is the code in dashboard page
![image](https://user-images.githubusercontent.com/38340100/96204715-95a48e80-0f97-11eb-844a-ddf5536c291c.png)
