### ISSUE TITLE
Two-axes FAB Button

### ISSUE THREAD

**Issue by alvarosaburido-nc** [quasarframework/quasar#7910]
**Is your feature request related to a problem? Please describe.**
Hi, we have the requirement for a [FAB Button](https://quasar.dev/vue-components/floating-action-button) with two menus, one with `direction="left"` and other with `direction="up"`, but seems like the QFab API only accepts 1 direction.

**Describe the solution you'd like**
Be able to pass to `direction` combination string such as `direction="left up"`

**Describe alternatives you've considered**
By now we have overlapped two FAB Buttons and linked the events emitters, but for accessibility we would like to avoid it.

Thanks a lot

**Comment by pdanpdan** [comment]
Hello. This looks like a very specific user case, sorry but it would be very complex - it would require multiple fab action containers.
I think the alternative you used is not so bad.
