### ISSUE TITLE
QDrawer shows white overlay footer when I scroll down

### ISSUE THREAD

**Issue by phuclh** [quasarframework/quasar#7915]
I got this issue when scrolling down my app with `QDrawer`. I tried different ways but it still shows the overlay footer. Below is my code

```
        <q-drawer
            v-model="rightDrawerOpen"
            side="right"
            :width="drawerWidth"
            overlay
            elevated
            no-swipe-open
            content-class="bg-grey-1"
            behavior="mobile"
        >
            <div class="md:hidden absolute" :style="'top: 0px; left: -65px'">
                <q-btn
                    unelevated
                    color="primary"
                    icon="fal fa-times"
                    class="p-2 text-sm lg:text-3xl rounded-none text-light"
                    @click="rightDrawerOpen = false"
                />
            </div>
            <div class="hidden md:block xl:hidden absolute" :style="'top: 0px; left: -80px'">
                <q-btn
                    unelevated
                    color="primary"
                    icon="fal fa-times"
                    class="p-3 text-sm lg:text-3xl rounded-none text-light"
                    @click="rightDrawerOpen = false"
                />
            </div>
            <div class="hidden xl:block absolute" :style="'top: 0px; left: -90px'">
                <q-btn
                    unelevated
                    color="primary"
                    icon="fal fa-times"
                    class="p-1 text-sm lg:text-3xl rounded-none text-light"
                    @click="rightDrawerOpen = false"
                />
            </div>
<!--            <q-scroll-area class="fit">-->
            <div>
                <div v-if="request_loading" class="p-base">
                    <default-loading/>
                </div>
                <div v-else>
                    <client-profile v-if="clientProfileOpen" :client_id="selected_request.client_id"></client-profile>
                    <div v-else-if="requestDetailsOpen">
                        <request-summary v-if="selected_request" :request="selected_request" :target_timestamp="selected_request.proposal_window_closes_at"/>
                    </div>
                    <div v-else-if="completeProposalViewOpen">
                        <proposal-complete-view :proposal="selected_proposal" :property-types="property_types"/>
                    </div>
                </div>
            </div>
            <!--            </q-scroll-area>-->
        </q-drawer>
```

**Video:** https://youtu.be/RzxrMJQ_dyc

**Screenshot:**

![Image from iOS](https://user-images.githubusercontent.com/6707194/96355658-df28d280-1098-11eb-9d9f-d3c5658d9636.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/6707194/96355660-e0f29600-1098-11eb-8b19-84d25c4bb47c.png)
![Image_from_iOS__2_](https://user-images.githubusercontent.com/6707194/96355741-07650100-109a-11eb-81e3-2ccb03a4a5a9.png)

**Comment by joshtorres** [comment]
Hello, I'm on the same team that is trying to figure this issue out. Just to be clear, we don't know if it's the footer or what the object is because it only shows up on iOS using Cordova, and we don't know how to inspect it to find out what it is. 
When we view it on the web, even on small screens, it does not do this

**Comment by joshtorres** [comment]
`<template>
    <q-layout :view="layout" container style="overflow-y:scroll;-webkit-overflow-scrolling:touch">
        <q-header class="bg-white shadow-0 shadow-none w-full flex justify-center">
            
            <q-toolbar class="hidden xl:block">
                <h-nav-menu v-if="$store.state.auth.isLoggedIn && ($store.state.auth.user.email == 'agent@virlyst.com' || $store.state.auth.user.email == 'client@virlyst.com')"
                            class="text-base"
                            :navMenuItems="navMenuItemsUser"
                            :rightNavMenuItems="rightNavMenuItemsUser"/>
                <h-nav-menu v-else-if="$store.state.auth.isLoggedIn"
                            class="text-base"
                            :navMenuItems="navMenuItemsUserEarlyAccess"
                            :rightNavMenuItems="rightNavMenuItemsUser"/>
                <h-nav-menu v-else
                            class="text-base"
                            :navMenuItems="navMenuItemsGuest"
                            :rightNavMenuItems="rightNavMenuItemsGuest"/>
            </q-toolbar>
            <q-toolbar v-if="$route.name != 'login' && $route.name != 'register'"
                       class="xl:hidden text-primary bg-white sm:px-8 py-4 flex justify-between items-center">
                <div class="flex justify-start items-center">
                    <q-btn v-if="$store.state && $store.state.auth.isLoggedIn" class="hidden sm:block xl:hidden mr-2" dense flat round icon="menu" v-on:click.prevent="leftMenuOpen = !leftMenuOpen"/>
                    <logo class="hidden md:block mr-4" style="width: 150px"/>
                    <q-toolbar-title v-if="$route.meta.title" class="md:hidden pt-2 text-2xl">
                        {{ $route.meta.title }}
                    </q-toolbar-title>
                </div>
                <div v-if="$store.state && $store.state.auth.isLoggedIn" class="flex justify-end items-center">
                    <q-btn :to="{ name: 'notifications' }" flat round dense icon="far fa-bell">
                        <q-badge v-if="$store.getters['auth/hasUnreadNotifications']" color="red" floating>{{ $store.getters['auth/unreadNotificationsCount'] }}</q-badge>
                    </q-btn>
                    <div class="mx-2">
                        <router-link :to="{ name: 'settings-user-profile' }" class="text-black cursor-pointer"><img :src="userAvatarUrl" width="40px" class="rounded-full"/></router-link>
                        <q-icon name="fas fa-circle" size="" color="success" style="position: relative; bottom: 12px; float:right;"/>
                    </div>
                    <q-btn :to="{ name: 'logout' }" flat dense color="" class="py-2 px-2 rounded-4">
                        <q-icon name="far fa-sign-out" class="text-xl mr-2"></q-icon>
                    </q-btn>
                </div>
            </q-toolbar>
            
        </q-header>
        
        <q-drawer v-model="leftMenuOpen" side="left" overlay behavior="mobile" bordered>
            <div class="pt-10">

                <logo class="2xl:hidden xl:pl-1 m-auto" style="width: 120px"/>

                <q-tabs align="left"
                        vertical
                        class="mt-10">
                    <div v-for="(navItem, index) in navMenuItemsUser" :key="index">
                        <div v-if="(navItem.type == null || navItem.type == undefined) || (navItem.type && navItem.type == $store.state.auth.user.user_type)">
                            <q-route-tab :to="{ name: navItem.slug }" content-class="text-2xl" active-class="border border-solid border-white" :label="navItem.name"/>
                        </div>
                    </div>
                </q-tabs>
            </div>
        </q-drawer>
        <q-page-container>
            <div class="my-base">
                <div v-if="$store.state" class="flex justify-center">
                    <div class="w-11/12 xl:w-10/12">






                        <router-view/>
                    </div>
                </div>
                <default-loading v-else/>
            </div>
        </q-page-container>
        
        <q-footer class="hidden md:block bg-primary text-grey-6 py-3">
            <footer class="the-footer flex-wrap justify-center">
                <p>
                    <span>&copy; </span>
                    <a href="" target="_blank" rel="nofollow" class="text-grey-6">VirLyst </a>
                    <span>{{ new Date().getFullYear() }} </span>
                    
                </p>
            </footer>
        </q-footer>
        <q-footer v-if="$store.state && $store.state.auth.isLoggedIn" class="md:hidden bg-white py-2 text-primary">
            <q-tabs v-if="$store.state.auth.user.email == 'agent@virlyst.com'"
                    narrow-indicator
                    dense
                    align="justify"
            >
                <q-route-tab :to="{ name: 'request-agent-list' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="requests" icon="far fa-inbox-in"
                             label="Requests"></q-route-tab>
                <q-route-tab :to="{ name: 'proposal-list' }" exact replace :ripple="false" name="proposals" icon="far fa-paper-plane" label="Proposals"/>
                <q-route-tab :to="{ name: 'messages' }" exact replace :ripple="false" name="messages" icon="far fa-comment-alt-lines" label="Messages"/>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else-if="$store.state.auth.user.email == 'client@virlyst.com'"
                    narrow-indicator
                    dense
                    align="justify"
                    content-class="px-0"
            >
                <q-route-tab :to="{ name: 'welcome' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="welcome" icon="fad fa-door-open" label="Welcome"></q-route-tab>
                <q-route-tab :to="{ name: 'request-client-list' }" :ripple="false" class="py-3 text-sm" name="requests" icon="far fa-inbox-in" label="Requests"/>
                <q-route-tab :to="{ name: 'messages' }" exact replace :ripple="false" name="messages" icon="far fa-comment-alt-lines" label="Messages"/>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else-if="$store.state.auth.user.user_type === 'client'"
                    narrow-indicator
                    dense
                    align="justify"
                    content-class="px-0"
            >
                
                
                <q-route-tab :to="{ name: 'welcome' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="welcome" icon="fad fa-door-open" label="Welcome"></q-route-tab>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else-if="$store.state.auth.user.user_type === 'agent'"
                    narrow-indicator
                    dense
                    align="justify"
            >
                
                
                
                
                
                <q-route-tab :to="{ name: 'welcome' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="welcome" icon="fad fa-door-open" label="Welcome"></q-route-tab>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else
                    narrow-indicator
                    dense
                    align="justify"
            >
                <q-route-tab :to="{ name: 'logout' }" exact replace :ripple="false" name="logout" icon="far fa-sign-out-alt" label="Logout"/>
            </q-tabs>
        </q-footer>
    </q-layout>
</template>


<script>
    import BackToTop from 'vue-backtotop'
    import HNavMenu from '../../layouts/components/horizontal-nav-menu/HorizontalNavMenu.vue'
    import navMenuItemsGuest from '../../layouts/components/navbar/navMenuItemsGuest.js'
    import navMenuItemsUser from '../../layouts/components/navbar/navMenuItemsUser.js'
    import navMenuItemsUserEarlyAccess from '../../layouts/components/navbar/navMenuItemsUserEarlyAccess.js'
    import rightNavMenuItemsGuest from '../../layouts/components/navbar/rightNavMenuItemsGuest.js'
    import rightNavMenuItemsUser from '../../layouts/components/navbar/rightNavMenuItemsUser.js'
    import TheNavbarHorizontal from '../../layouts/components/navbar/TheNavbarHorizontal.vue'
    import TheNavbarVertical from '../../layouts/components/navbar/TheNavbarVertical.vue'
    import TheFooter from '../../layouts/components/TheFooter.vue'
    import themeConfig from '../../../themeConfig.js'
    import VNavMenu from '../../layouts/components/vertical-nav-menu/VerticalNavMenu.vue'
    import DefaultLoading from 'components/core/loading/default'
    import Logo from '../components/Logo.vue'

    export default {
        components: {
            DefaultLoading,
            BackToTop,
            HNavMenu,
            TheFooter,
            TheNavbarHorizontal,
            TheNavbarVertical,
            VNavMenu,
            Logo
        },
        data () {
            return {
                leftMenuOpen: false,
                rightDrawerOpen: false,
                footerType: themeConfig.footerType || 'static',
                hideScrollToTop: themeConfig.hideScrollToTop,
                isNavbarDark: false,
                navbarColor: themeConfig.navbarColor || '#fff',
                navbarType: themeConfig.navbarType || 'floating',
                navMenuItemsGuest: navMenuItemsGuest,
                navMenuItemsUser: navMenuItemsUser,
                navMenuItemsUserEarlyAccess: navMenuItemsUserEarlyAccess,
                rightNavMenuItemsGuest: rightNavMenuItemsGuest,
                rightNavMenuItemsUser: rightNavMenuItemsUser,
                routerTransition: themeConfig.routerTransition || 'none',
                routeTitle: this.$route.meta.pageTitle,
                menuList: [
                    {
                        icon: 'inbox',
                        label: 'Inbox',
                        separator: true
                    },
                    {
                        icon: 'send',
                        label: 'Outbox',
                        separator: false
                    },
                    {
                        icon: 'delete',
                        label: 'Trash',
                        separator: false
                    },
                    {
                        icon: 'error',
                        label: 'Spam',
                        separator: true
                    },
                    {
                        icon: 'settings',
                        label: 'Settings',
                        separator: false
                    },
                    {
                        icon: 'feedback',
                        label: 'Send Feedback',
                        separator: false
                    },
                    {
                        icon: 'help',
                        iconColor: 'primary',
                        label: 'Help',
                        separator: false
                    }
                ]
            }
        },
        watch: {
            '$route' () {
                this.routeTitle = this.$route.meta.pageTitle
            },
            isThemeDark (val) {
                const color = this.navbarColor == '#fff' && val ? '#10163a' : '#fff'
                this.updateNavbarColor(color)
            },
            '$store.state.mainLayoutType' (val) {
                this.setNavMenuVisibility(val)
            }
        },
        computed: {
            userAvatarUrl () {
                if (this.$store && this.$store.state && this.$store.state.auth.user) {
                    return this.$store.state.auth.user.photo_url
                }
            },
            layout () {
                if ((this.$q.platform.is.mobile || this.$q.platform.is.cordova) && !this.$q.platform.is.ipad) {
                    return 'lHr lpr fFf'
                } else {
                    return 'lHr lpr lfr'
                }
            },

            bodyOverlay () {
                return this.$store.state.bodyOverlay
            },
            contentAreaClass () {
                if (this.mainLayoutType === 'vertical') {
                    if (this.verticalNavMenuWidth == 'default') {
                        return 'content-area-reduced'
                    } else if (this.verticalNavMenuWidth == 'reduced') {
                        return 'content-area-lg'
                    } else {
                        return 'content-area-full'
                    }
                    // eslint-disable-next-line brace-style
                }
                // else if(this.mainLayoutType === "boxed") return "content-area-reduced"
                else {
                    return 'content-area-full'
                }
            },
            footerClasses () {
                return {
                    'footer-hidden': this.footerType == 'hidden',
                    'footer-sticky': this.footerType == 'sticky',
                    'footer-static': this.footerType == 'static',
                }
            },
            isAppPage () {
                return this.$route.meta.no_scroll
            },
            isThemeDark () {
                return this.$store.state.theme == 'dark'
            },
            layoutTypeClass () {
                return `main-${this.mainLayoutType}`
            },
            mainLayoutType () {
                return this.$store.state.mainLayoutType
            },
            navbarClasses () {
                return {
                    'navbar-hidden': this.navbarType == 'hidden',
                    'navbar-sticky': this.navbarType == 'sticky',
                    'navbar-static': this.navbarType == 'static',
                    'navbar-floating': this.navbarType == 'floating',
                }
            },
            verticalNavMenuWidth () {
                return this.$store.state.verticalNavMenuWidth
            },
            windowWidth () {
                return this.$store.state.windowWidth
            }
        },
        methods: {
            changeRouteTitle (title) {
                this.routeTitle = title
            },
            updateNavbarColor (val) {
                this.navbarColor = val
                if (val == '#fff') {
                    this.isNavbarDark = false
                } else {
                    this.isNavbarDark = true
                }
            },
            setNavMenuVisibility (layoutType) {
                if ((layoutType === 'horizontal' && this.windowWidth >= 1200) || (layoutType === 'vertical' && this.windowWidth < 1200)) {
                    this.$store.commit('TOGGLE_IS_VERTICAL_NAV_MENU_ACTIVE', false)
                    this.$store.dispatch('updateVerticalNavMenuWidth', 'no-nav-menu')
                } else {
                    this.$store.commit('TOGGLE_IS_VERTICAL_NAV_MENU_ACTIVE', true)
                }
            }
        },
        created () {
            console.log('NODE_ENV')
            console.log(process.env.NODE_ENV)
            const color = this.navbarColor == '#fff' && this.isThemeDark ? '#10163a' : this.navbarColor
            this.updateNavbarColor(color)
            this.setNavMenuVisibility(this.$store.state.mainLayoutType)
        }
    }

</script>
`

**Comment by joshtorres** [comment]
```
<template>
    <q-layout :view="layout" container style="overflow-y:scroll;-webkit-overflow-scrolling:touch">
        <q-header class="bg-white shadow-0 shadow-none w-full flex justify-center">
            <!-- Navbar -->
            <q-toolbar class="hidden xl:block">
                <h-nav-menu v-if="$store.state.auth.isLoggedIn && ($store.state.auth.user.email == 'agent@virlyst.com' || $store.state.auth.user.email == 'client@virlyst.com')"
                            class="text-base"
                            :navMenuItems="navMenuItemsUser"
                            :rightNavMenuItems="rightNavMenuItemsUser"/>
                <h-nav-menu v-else-if="$store.state.auth.isLoggedIn"
                            class="text-base"
                            :navMenuItems="navMenuItemsUserEarlyAccess"
                            :rightNavMenuItems="rightNavMenuItemsUser"/>
                <h-nav-menu v-else
                            class="text-base"
                            :navMenuItems="navMenuItemsGuest"
                            :rightNavMenuItems="rightNavMenuItemsGuest"/>
            </q-toolbar>
            <q-toolbar v-if="$route.name != 'login' && $route.name != 'register'"
                       class="xl:hidden text-primary bg-white sm:px-8 py-4 flex justify-between items-center">
                <div class="flex justify-start items-center">
                    <q-btn v-if="$store.state && $store.state.auth.isLoggedIn" class="hidden sm:block xl:hidden mr-2" dense flat round icon="menu" v-on:click.prevent="leftMenuOpen = !leftMenuOpen"/>
                    <logo class="hidden md:block mr-4" style="width: 150px"/>
                    <q-toolbar-title v-if="$route.meta.title" class="md:hidden pt-2 text-2xl">
                        {{ $route.meta.title }}
                    </q-toolbar-title>
                </div>
                <div v-if="$store.state && $store.state.auth.isLoggedIn" class="flex justify-end items-center">
                    <q-btn :to="{ name: 'notifications' }" flat round dense icon="far fa-bell">
                        <q-badge v-if="$store.getters['auth/hasUnreadNotifications']" color="red" floating>{{ $store.getters['auth/unreadNotificationsCount'] }}</q-badge>
                    </q-btn>
                    <div class="mx-2">
                        <router-link :to="{ name: 'settings-user-profile' }" class="text-black cursor-pointer"><img :src="userAvatarUrl" width="40px" class="rounded-full"/></router-link>
                        <q-icon name="fas fa-circle" size="" color="success" style="position: relative; bottom: 12px; float:right;"/>
                    </div>
                    <q-btn :to="{ name: 'logout' }" flat dense color="" class="py-2 px-2 rounded-4">
                        <q-icon name="far fa-sign-out" class="text-xl mr-2"></q-icon>
                    </q-btn>
                </div>
            </q-toolbar>
            <!-- /Navbar -->
        </q-header>
        <!-- Left Menu -->
        <q-drawer v-model="leftMenuOpen" side="left" overlay behavior="mobile" bordered>
            <div class="pt-10">
<!--                <h3 class="text-center">Menu</h3>-->
                <logo class="2xl:hidden xl:pl-1 m-auto" style="width: 120px"/>

                <q-tabs align="left"
                        vertical
                        class="mt-10">
                    <div v-for="(navItem, index) in navMenuItemsUser" :key="index">
                        <div v-if="(navItem.type == null || navItem.type == undefined) || (navItem.type && navItem.type == $store.state.auth.user.user_type)">
                            <q-route-tab :to="{ name: navItem.slug }" content-class="text-2xl" active-class="border border-solid border-white" :label="navItem.name"/>
                        </div>
                    </div>
                </q-tabs>
            </div>
        </q-drawer>
        <q-page-container>
            <div class="my-base">
                <div v-if="$store.state" class="flex justify-center">
                    <div class="w-11/12 xl:w-10/12">
<!--                        <back-to-top v-if="!hideScrollToTop" class="hidden md:block" :bottom="$q.platform.is.mobile && !$q.platform.is.ipad ? '12%' : '5%'" :right="$vs.rtl-->
<!--                         ? 'calc(100% - 2.2rem - 38px)' : '30px'"-->
<!--                                     visibleoffset="500">-->
<!--                            <q-btn icon="fas fa-arrow-up" color="primary" square class="shadow-lg text-lg"/>-->
<!--                        </back-to-top>-->

                        <router-view/>
                    </div>
                </div>
                <default-loading v-else/>
            </div>
        </q-page-container>
        <!--                <the-footer/>-->
        <q-footer class="hidden md:block bg-primary text-grey-6 py-3">
            <footer class="the-footer flex-wrap justify-center">
                <p>
                    <span>&copy; </span>
                    <a href="" target="_blank" rel="nofollow" class="text-grey-6">VirLyst </a>
                    <span>{{ new Date().getFullYear() }} </span>
                    <!--                            <span class="hidden sm:inline-block">, All rights Reserved</span>-->
                </p>
            </footer>
        </q-footer>
        <q-footer v-if="$store.state && $store.state.auth.isLoggedIn" class="md:hidden bg-white py-2 text-primary">
            <q-tabs v-if="$store.state.auth.user.email == 'agent@virlyst.com'"
                    narrow-indicator
                    dense
                    align="justify"
            >
                <q-route-tab :to="{ name: 'request-agent-list' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="requests" icon="far fa-inbox-in"
                             label="Requests"></q-route-tab>
                <q-route-tab :to="{ name: 'proposal-list' }" exact replace :ripple="false" name="proposals" icon="far fa-paper-plane" label="Proposals"/>
                <q-route-tab :to="{ name: 'messages' }" exact replace :ripple="false" name="messages" icon="far fa-comment-alt-lines" label="Messages"/>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else-if="$store.state.auth.user.email == 'client@virlyst.com'"
                    narrow-indicator
                    dense
                    align="justify"
                    content-class="px-0"
            >
                <q-route-tab :to="{ name: 'welcome' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="welcome" icon="fad fa-door-open" label="Welcome"></q-route-tab>
                <q-route-tab :to="{ name: 'request-client-list' }" :ripple="false" class="py-3 text-sm" name="requests" icon="far fa-inbox-in" label="Requests"/>
                <q-route-tab :to="{ name: 'messages' }" exact replace :ripple="false" name="messages" icon="far fa-comment-alt-lines" label="Messages"/>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else-if="$store.state.auth.user.user_type === 'client'"
                    narrow-indicator
                    dense
                    align="justify"
                    content-class="px-0"
            >
                <!--                <q-route-tab :to="{ name: 'request-client-list' }" :ripple="false" class="py-3 text-sm" name="requests" icon="far fa-inbox-in" label="Requests"/>-->
                <!--                <q-route-tab :to="{ name: 'messages' }" exact replace :ripple="false" name="messages" icon="far fa-comment-alt-lines" label="Messages"/>-->
                <q-route-tab :to="{ name: 'welcome' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="welcome" icon="fad fa-door-open" label="Welcome"></q-route-tab>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else-if="$store.state.auth.user.user_type === 'agent'"
                    narrow-indicator
                    dense
                    align="justify"
            >
                <!--                <q-route-tab :to="{ name: 'request-agent-list' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="requests" icon="far fa-inbox-in"-->
                <!--                             label="Requests"></q-route-tab>-->
                <!--                <q-route-tab :to="{ name: 'proposal-list' }" exact replace :ripple="false" name="proposals" icon="far fa-paper-plane" label="Proposals"/>-->
                <!--                <q-route-tab :to="{ name: 'messages' }" exact replace :ripple="false" name="messages" icon="far fa-comment-alt-lines" label="Messages"/>-->
                <!--                <q-route-tab :to="{ name: 'notifications' }" exact replace :ripple="false" name="alerts" icon="far fa-bell" label="Alerts"><q-badge color="red" floating>2</q-badge></q-route-tab>-->
                <q-route-tab :to="{ name: 'welcome' }" exact replace :ripple="false" content-class="py-3 px-0 mx-0 text-3xl" name="welcome" icon="fad fa-door-open" label="Welcome"></q-route-tab>
                <q-route-tab :to="{ name: 'settings-user-profile' }" exact replace :ripple="false" name="account" icon="far fa-user" label="Account"/>
            </q-tabs>
            <q-tabs v-else
                    narrow-indicator
                    dense
                    align="justify"
            >
                <q-route-tab :to="{ name: 'logout' }" exact replace :ripple="false" name="logout" icon="far fa-sign-out-alt" label="Logout"/>
            </q-tabs>
        </q-footer>
    </q-layout>
</template>


<script>
    import BackToTop from 'vue-backtotop'
    import HNavMenu from '../../layouts/components/horizontal-nav-menu/HorizontalNavMenu.vue'
    import navMenuItemsGuest from '../../layouts/components/navbar/navMenuItemsGuest.js'
    import navMenuItemsUser from '../../layouts/components/navbar/navMenuItemsUser.js'
    import navMenuItemsUserEarlyAccess from '../../layouts/components/navbar/navMenuItemsUserEarlyAccess.js'
    import rightNavMenuItemsGuest from '../../layouts/components/navbar/rightNavMenuItemsGuest.js'
    import rightNavMenuItemsUser from '../../layouts/components/navbar/rightNavMenuItemsUser.js'
    import TheNavbarHorizontal from '../../layouts/components/navbar/TheNavbarHorizontal.vue'
    import TheNavbarVertical from '../../layouts/components/navbar/TheNavbarVertical.vue'
    import TheFooter from '../../layouts/components/TheFooter.vue'
    import themeConfig from '../../../themeConfig.js'
    import VNavMenu from '../../layouts/components/vertical-nav-menu/VerticalNavMenu.vue'
    import DefaultLoading from 'components/core/loading/default'
    import Logo from '../components/Logo.vue'

    export default {
        components: {
            DefaultLoading,
            BackToTop,
            HNavMenu,
            TheFooter,
            TheNavbarHorizontal,
            TheNavbarVertical,
            VNavMenu,
            Logo
        },
        data () {
            return {
                leftMenuOpen: false,
                rightDrawerOpen: false,
                footerType: themeConfig.footerType || 'static',
                hideScrollToTop: themeConfig.hideScrollToTop,
                isNavbarDark: false,
                navbarColor: themeConfig.navbarColor || '#fff',
                navbarType: themeConfig.navbarType || 'floating',
                navMenuItemsGuest: navMenuItemsGuest,
                navMenuItemsUser: navMenuItemsUser,
                navMenuItemsUserEarlyAccess: navMenuItemsUserEarlyAccess,
                rightNavMenuItemsGuest: rightNavMenuItemsGuest,
                rightNavMenuItemsUser: rightNavMenuItemsUser,
                routerTransition: themeConfig.routerTransition || 'none',
                routeTitle: this.$route.meta.pageTitle,
                menuList: [
                    {
                        icon: 'inbox',
                        label: 'Inbox',
                        separator: true
                    },
                    {
                        icon: 'send',
                        label: 'Outbox',
                        separator: false
                    },
                    {
                        icon: 'delete',
                        label: 'Trash',
                        separator: false
                    },
                    {
                        icon: 'error',
                        label: 'Spam',
                        separator: true
                    },
                    {
                        icon: 'settings',
                        label: 'Settings',
                        separator: false
                    },
                    {
                        icon: 'feedback',
                        label: 'Send Feedback',
                        separator: false
                    },
                    {
                        icon: 'help',
                        iconColor: 'primary',
                        label: 'Help',
                        separator: false
                    }
                ]
            }
        },
        watch: {
            '$route' () {
                this.routeTitle = this.$route.meta.pageTitle
            },
            isThemeDark (val) {
                const color = this.navbarColor == '#fff' && val ? '#10163a' : '#fff'
                this.updateNavbarColor(color)
            },
            '$store.state.mainLayoutType' (val) {
                this.setNavMenuVisibility(val)
            }
        },
        computed: {
            userAvatarUrl () {
                if (this.$store && this.$store.state && this.$store.state.auth.user) {
                    return this.$store.state.auth.user.photo_url
                }
            },
            layout () {
                if ((this.$q.platform.is.mobile || this.$q.platform.is.cordova) && !this.$q.platform.is.ipad) {
                    return 'lHr lpr fFf'
                } else {
                    return 'lHr lpr lfr'
                }
            },

            bodyOverlay () {
                return this.$store.state.bodyOverlay
            },
            contentAreaClass () {
                if (this.mainLayoutType === 'vertical') {
                    if (this.verticalNavMenuWidth == 'default') {
                        return 'content-area-reduced'
                    } else if (this.verticalNavMenuWidth == 'reduced') {
                        return 'content-area-lg'
                    } else {
                        return 'content-area-full'
                    }
                    // eslint-disable-next-line brace-style
                }
                // else if(this.mainLayoutType === "boxed") return "content-area-reduced"
                else {
                    return 'content-area-full'
                }
            },
            footerClasses () {
                return {
                    'footer-hidden': this.footerType == 'hidden',
                    'footer-sticky': this.footerType == 'sticky',
                    'footer-static': this.footerType == 'static',
                }
            },
            isAppPage () {
                return this.$route.meta.no_scroll
            },
            isThemeDark () {
                return this.$store.state.theme == 'dark'
            },
            layoutTypeClass () {
                return `main-${this.mainLayoutType}`
            },
            mainLayoutType () {
                return this.$store.state.mainLayoutType
            },
            navbarClasses () {
                return {
                    'navbar-hidden': this.navbarType == 'hidden',
                    'navbar-sticky': this.navbarType == 'sticky',
                    'navbar-static': this.navbarType == 'static',
                    'navbar-floating': this.navbarType == 'floating',
                }
            },
            verticalNavMenuWidth () {
                return this.$store.state.verticalNavMenuWidth
            },
            windowWidth () {
                return this.$store.state.windowWidth
            }
        },
        methods: {
            changeRouteTitle (title) {
                this.routeTitle = title
            },
            updateNavbarColor (val) {
                this.navbarColor = val
                if (val == '#fff') {
                    this.isNavbarDark = false
                } else {
                    this.isNavbarDark = true
                }
            },
            setNavMenuVisibility (layoutType) {
                if ((layoutType === 'horizontal' && this.windowWidth >= 1200) || (layoutType === 'vertical' && this.windowWidth < 1200)) {
                    this.$store.commit('TOGGLE_IS_VERTICAL_NAV_MENU_ACTIVE', false)
                    this.$store.dispatch('updateVerticalNavMenuWidth', 'no-nav-menu')
                } else {
                    this.$store.commit('TOGGLE_IS_VERTICAL_NAV_MENU_ACTIVE', true)
                }
            }
        },
        created () {
            console.log('NODE_ENV')
            console.log(process.env.NODE_ENV)
            const color = this.navbarColor == '#fff' && this.isThemeDark ? '#10163a' : this.navbarColor
            this.updateNavbarColor(color)
            this.setNavMenuVisibility(this.$store.state.mainLayoutType)
        }
    }

</script>

```

**Comment by joshtorres** [comment]
That's the full Main.vue component which houses the outermost <q-layout />

**Comment by IlCallo** [comment]
@joshtorres can you create a repro of this? Seems like a CCS issue with safari (the Cordova webview on iOS is always webkit based I guess). It's pretty difficult to understand the problem with the full code, you should try to reproduce the problem with bare minimum code and push it to a repo for us to dig deeper

**Comment by joshtorres** [comment]
Sorry I just realized that I gave some bad information as this is definitely a safari issue. I'm not sure how to reproduce it, but the same thing happens when I log on to our web app in iOS safari. I'm trying to look into how to test it with layout builder, but there isn't enough content to scroll down and test it.

**Comment by joshtorres** [comment]
Ignore this, I just figured it out. It was because of this styling that I found in one of our stylesheets. Sorry to waste everyone's time! Thanks for trying to help!
```
html {
    height  : 100%;
    overflow: hidden;
    position: relative;
}
body {
    height  : 100%;
    overflow: auto;
    position: relative;
}
```

**Comment by IlCallo** [comment]
Happy you found the solution!
