### ISSUE TITLE
[docs] support vue-devtools for capacitor, cordova apps

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#7916]
[Vue DevTools Electron](https://github.com/vuejs/vue-devtools/blob/dev/packages/shell-electron/README.md)
Using this we can connect vue devtools  to everywhere vue project.
Does capacitor mode support this feature?
How i can add this script to header or quasar add auto this script when  quasar.conf.js -> devServer -> vueDevtools: true?
![image](https://user-images.githubusercontent.com/11452353/96358503-8bf26680-1110-11eb-9fdd-396b8ad6c684.png)

**Comment by bazuka5801** [comment]
I enable  quasar.conf.js -> devServer -> vueDevtools: true
works only components.
How enable store and events?
![image](https://user-images.githubusercontent.com/11452353/96359642-bac30980-111d-11eb-8229-27609b4f216a.png)

**Comment by hawkeye64** [comment]
Did you enable `strict: true` in your `src -> store -> index.js`, should be near the bottom

**Comment by bazuka5801** [comment]
@hawkeye64 
Hmm... I see `process.env.DEV` it may true when i run quasar dev.
I tried with strict:true, same problem

**Comment by bazuka5801** [comment]
My index.js
`import Vue from "vue";
import Vuex from "vuex";
import auth from "./auth";
import app from "./app";
import firestore from "./firestore";
import axiosModule from "../boot/axios";
import LongPress from 'vue-directive-long-press';

// import example from './module-example'
import user from "./user";


Vue.use(Vuex);

Vue.directive('long-press', LongPress)
  
Vue.config.devtools = true;

const Store = new Vuex.Store({
  modules: {
    auth,
    app,
    user,
    firestore
  },
  plugins: [
    store => {
      store.$axios = axiosModule.axios;
      store.$q = Vue.prototype.$q;
      store.$set = Vue.set;
      store.$delete = Vue.delete;
    }
  ],
  actions: {
    async init({ dispatch }) {
      await dispatch("auth/init");
      await dispatch("user/init");
    }
  },

  // enable strict mode (adds overhead!)
  // for dev mode only
  strict:true 
});

if (process.env.DEV && module.hot) {
  module.hot.accept(["./auth"], () => {
    const auth = require("./auth").default;
    Store.hotUpdate({ modules: { auth } });
    Store.dispatch("auth/init");
  });
  module.hot.accept(["./app"], () => {
    const app = require("./app").default;
    Store.hotUpdate({ modules: { app } });
  });
  module.hot.accept(["./user"], () => {
    const user = require("./user").default;
    Store.hotUpdate({ modules: { user } });
  });
  module.hot.accept(["./firestore"], () => {
    const firestore = require("./firestore").default;
    Store.hotUpdate({ modules: { firestore } });
  });
}
export default Store;
`

**Comment by hawkeye64** [comment]
@bazuka5801 
I believe you need to set this as well:
```
Vue.config.productionTip = false;
```

**Comment by bazuka5801** [comment]
@hawkeye64 
I set this, not worked :(
I found this sets on my generated client-entry.js by Quasar.
![image](https://user-images.githubusercontent.com/11452353/96683457-e1ce4500-1382-11eb-9037-674494ac1950.png)

**Comment by bazuka5801** [comment]
@hawkeye64 
Checked with:
quasar dev -m capacitor -T android
same problem :(
https://drive.google.com/file/d/1u2Jveh3inchJLNOx1Z3KP04q25gjI2XU/view

quasar.conf -> devServer
```js
devServer: {
      https: false,
      port: 8080,
      vueDevtools: true,
      open: true // opens browser window automatically
    }
```

**Comment by bazuka5801** [comment]
@rstoenescu Can you reopen issue?

**Comment by bazuka5801** [comment]
@rstoenescu Thank you))

**Comment by rstoenescu** [comment]
Ok, so investigated this. I've checked vue-devtools docs and concluded that Quasar is doing everything according to their specs.

However, vue-devtools is indeed not detecting the vuex store correctly when on a Capacitor app (haven't tested Cordova but I imagine it's the same thing).

This is a vue-devtools bug so please report this to the vue-devtools owner.

**Comment by bazuka5801** [comment]
@rstoenescu Okay, I will))

**Comment by bazuka5801** [comment]
@rstoenescu 
Four months later, a solution was found! Today I will create an issue with PR))
