### ISSUE TITLE
 Please add: id="q-app" (or write #q-app if using Pug)   to the outermost HTML element of the template.

### ISSUE THREAD

**Issue by ForceBoot** [quasarframework/quasar#7919]
How to modify ID？
```
<template>
    <div id="miu-app">
        <router-view />
    </div>
</template>
<script>
export default {
    name: 'App'
}
</script>
```

 Please add: id="q-app" (or write #q-app if using Pug)   to the outermost HTML element of the template.

**Comment by hawkeye64** [comment]
@ForceBoot It's in your `index.template.html` file - look for it there
Please use forums or Discord for similar, future questions instead of Github issues.
We would all appreciate it.

**Comment by alex-milyutin** [comment]
but what's the solution???

**Comment by hawkeye64** [comment]
The solution is in my previous response.
