### ISSUE TITLE
cordova is not defined

### ISSUE THREAD

**Issue by moringaman** [quasarframework/quasar#792]
I am receiving "reference error, cordova is not defined" when trying to access any cordova plugins
from method calls inside vue templates

I have asked on forum and gitter nobody has an answer, quasar cli app is wrapped with cordova, everything else works, just cannot access cordova

There is no troubleshooting info in the docs which I have followed to the letter

### Software version

Quasar: 0.13.4
OS: OSX Sierra
Node: v6.10.3
NPM: 5.3.0
Browsers: All
iOS: 10
Android: N/A
Any other software related to your bug:

**Comment by moringaman** [comment]
Something that I feel may be of note is the fact that I have been able to work around this issue by using `navigator.camera` instead of `cordova.plugins.camera `. Hopefully this can shed some light on what is causing this behavour

**Comment by rstoenescu** [comment]
Hi,

Can you test with latest 0.13.x (which is 0.13.10) pls? If it doesn't works, do you have any trpo where I can reproduce?

Thanks.

**Comment by moringaman** [comment]
Question. 

How do I test v0.14 as it says no matching version if I place "quasar-framework": "^0.14.0" into my package.json?

**Comment by rstoenescu** [comment]
@moringaman use the edge version. v0.14 is not yet officially released. http://beta.quasar-framework.org/guide/quasar-nightly-build.html
You might want to use the appropriate starter kit too: `quasar init default#beta <folder_name>`

**Comment by moringaman** [comment]
I've tested versions mentioned but I'm still getting this issue. maybe I'm doing something wrong?

My repo is:

 https://github.com/moringaman/Q-DSK

**Comment by rstoenescu** [comment]
Any user/pass with which I can login? If this is too sensitive, please contact me on Gitter. Thanks.

**Comment by moringaman** [comment]
UID: test@tester.com
Pass: password

**Comment by rstoenescu** [comment]
`cordova` is defined and working well.
The problem is how you use all the cordova plugins. Please read their documentation page.

For example, Camera plugin is accessed with `navigator.camera` instead of `cordova.plugins.camera`. Same for geolocation.

**Comment by moringaman** [comment]
That's what I discovered after reading the README.md of the camera plugin, (see my first comment)

As some user feedback, might I suggest that you also add that to your documentation as this has also affected at least one other developer that I know of  (who also used cordova.plugins as a reference in his app) and had me stuck for quite a while aswell.

Anyway, thanks for looking into this for me. I'm loving the framework

**Comment by rstoenescu** [comment]
Always read each Cordova plugin's documentation to see how it can be used.
