### ISSUE TITLE
Better support for alternative themes/css

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#7921]
The one thing that is stopping adoption of Quasar is the lack of support for different CSS.  We have been using our own Bootstrap theme for years and would prefer that sites we convert to use Quasar look the same, but it is exceedingly difficult to do this with Quasar.  Tailwind is another popular CSS framework we've been interested in adopting.

**Comment by hawkeye64** [comment]
@Daemach You could look at this until we can support such a feature. Thanks.
https://github.com/quasarframework/quasar/issues/6775#issuecomment-661891743
