### ISSUE TITLE
QParallax not working

### ISSUE THREAD

**Issue by BasitCode** [quasarframework/quasar#7922]
**Describe the bug**
QParallax is not working inside QTabPanel

https://codepen.io/codebasit/pen/mdEEabV?editors=1010

1. Go to https://codepen.io/codebasit/pen/mdEEabV?editors=1010
2. Scroll down to QParallax

Qparallax has no effect inside QTabPanel

**Platform (please complete the following information):**
OS: win 10
Node: 10.21.0
NPM: 6.14.6
Yarn: 1.22.4
Browsers: Chrome
iOS:
Android:
Electron: 2.0.18

**Comment by rstoenescu** [comment]
Hi,

This is because the QTabPanel has its own scrolling container. Which in this case is not triggered because it's not the one scrolling, but your page.

So use the `scroll-target` prop to set it to your scrolling container.
