### ISSUE TITLE
Allow use capacitor package in web

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#7925]
**Is your feature request related to a problem? Please describe.**
I have a capacitor app, the Capacitor plugins like Geolocation or Storage allows to work in the browser, but quasar didn't allow to use the capacitor mode without load an IDE, and the normal `quasar dev` doesn't load the capacitor libs

**Describe the solution you'd like**
Add a new `-T [android|ios|web]` in `-m capacitor`, same as `quasar dev` but loading the capacitor libds

**Describe alternatives you've considered**
Create a compatibility layers detecting the platforms and use different solutions, but fails with `quasar dev` because can't load the "@capacitor/core" module.

In `quasar dev -m capacitor -T android` I can't access from the browser, I don't know why.

**Comment by rstoenescu** [comment]
This is already available and working....
Not sure what you did to conclude this isn't working.

Attached below the code that was tested and the actual output in the console.

![code](https://user-images.githubusercontent.com/4665641/96750931-3dc1b980-13d5-11eb-9eb8-af990c0b3789.png)

![import-capacitor](https://user-images.githubusercontent.com/4665641/96750895-33072480-13d5-11eb-8f1c-173b24ebe5db.png)

**Comment by Nisgrak** [comment]
With only `quasar dev` this is the result.

![image](https://user-images.githubusercontent.com/19597708/96751458-7fe6fd00-13cd-11eb-8d48-0286199ebace.png)
![image](https://user-images.githubusercontent.com/19597708/96751470-85444780-13cd-11eb-90eb-709f87ab5248.png)

**Comment by rstoenescu** [comment]
You haven't mentioned what "@quasar/app" version you are using. I assume it's an old version...
Please upgrade to latest. The code for making capacitor/* packages available is there...

**Comment by Nisgrak** [comment]
Sorry, forgot about that. But its a relative recent version.

![image](https://user-images.githubusercontent.com/19597708/96753246-da815880-13cf-11eb-9482-55b90b2a6f13.png)
![image](https://user-images.githubusercontent.com/19597708/96753262-e1a86680-13cf-11eb-8db7-d4a6fb0fe130.png)

**Comment by rstoenescu** [comment]
But your output of "quasar info" shows that you don't have any capacitor/* packages installed... Install them in src-capacitor :/

**Comment by Nisgrak** [comment]
I see that shows that capacitor is not installed, but... I have the src-capacitor and `quasar dev -m capacitor -T android` and it works

![image](https://user-images.githubusercontent.com/19597708/96753899-d30e7f00-13d0-11eb-91a8-f48f633d2e69.png)
![image](https://user-images.githubusercontent.com/19597708/96753922-dbff5080-13d0-11eb-9567-e5c1576469a0.png)

**Comment by rstoenescu** [comment]
The "quasar info" command had a bug (fixed it and will be available in next q/app release) where it was looking for capacitor deps in the wrong folder.

BUT, the logic for the web code still stands and works. Several people tested it on multiple platforms. And I also see that your last output does not error out while building. Which is REALLY confusing me.

**Comment by Nisgrak** [comment]
The error only happend with `quasar dev`, in `quasar dev -m capacitor -T [android|ios]` works. It's very strange and the creation of the project is very recent, like 1 week.

**Comment by rstoenescu** [comment]
Oh. Then this should have been highlighted more. If you're not using "-m capacitor" then it's perfectly normal. Build modes do not pollute each other.

If you want to make your thing work, you should create a boot file (and guard it in quasar.conf to run only for capacitor builds) which injects different parts of what you need to access from Capacitor.

```
// quasar.conf.js
boot: {
  ctx.mode.capacitor ? 'inject-capacitor' : ''
}

// boot/inject-capacitor.js
import { Plugins, ... } from '@capacitor/core'

export default ({ Vue }) => {
  Vue.prototype.$myVar = Plugins // or whatever
}
```

You'll have access to `this.$myVar` (or however you call it) only on capacitor builds.

**Comment by Nisgrak** [comment]
The problem isn't that.

When I use `quasar dev -m capacitor -T [android|ios]` the capacitor libs like `@capacitor/core` is available (or it's detect like installed), so not error here
![image](https://user-images.githubusercontent.com/19597708/96874747-c47aa300-1476-11eb-930d-44edfdeaa61f.png)

But when only use `quasar dev` the capacitor libs isn't available, so I want a new command like `quasar dev -m capacitor -T web`, its inject capactior libs to allow use libs even without open the Android Studio or Xcode
![image](https://user-images.githubusercontent.com/19597708/96874898-e8d67f80-1476-11eb-8b42-88b6dde358c7.png)

**Comment by rstoenescu** [comment]
We do not support capacitor builds other than android or ios.
What our architecture supports is what I told above, which can be used with (quasar dev --- equivalent to your requested "web") and (quasar dev -m capacitor -T [android|ios]).

**Comment by Nisgrak** [comment]
But that solution only load in $myVar the Plugin from `@capacitor/core` in `quasar dev -m capacitor -T [android|ios]`, if I try to load that in `quasar dev` the `@capacitor/core` isn't founded.

![image](https://user-images.githubusercontent.com/19597708/96876202-75357200-1478-11eb-8c64-b13cf1e0c238.png)

**Comment by hawkeye64** [comment]
@Nisgrak `@capacitor/core` is in the `src-capacitor` project

**Comment by rstoenescu** [comment]
@Nisgrak like I mentioned above, Quasar supports the regular SPA (quasar dev) or Capacitor (quasar dev -m capacitor -T [android|ios]). Try to think in these terms. We do not pollute build modes, which is why `@capacitor/*` are only available for Capacitor. Which is why a boot file that gets injected only on Capacitor is needed (the quasar.conf > boot > ctx.mode.capacitor ? 'inject-capacitor' : '' part).

**Comment by Nisgrak** [comment]
I understand to not pollute build modes, for that reason I ask for a new `-T web` capacitor mode.

The libs in `@capacitor/core` like Geolocation or Camera also works in web, using the native web API, that way I don't need to make a compatibility layer checking if I am in capacitor mode or not.
It's works in any plataform, even Electron.

**Comment by IlCallo** [comment]
@Nisgrak if you need capacitor stuff to also work on web, your best shot is just to require those dependencies on you main package.json too

**Comment by Nisgrak** [comment]
@IlCallo But when I use `quasar dev -m capacitor -T [android|ios]` it will use the libs in `src-capacitor`, not in regular `node_modules`

**Comment by IlCallo** [comment]
If I remember correctly, it will actually use both. That said, duplicate the dependency on both `package.json` files and it should work fine

**Comment by Nisgrak** [comment]
For the record (I just receive an email asking my solution).

I ended doing "quasar dev -m capacitor -T android", close Android Studio and open the link in the browser anyway. The @capacitor packages are loaded and works in the browser like a charm (you need to make some adjustments in geolocation, for example, but works).

You can add surely @capacitor packages to dependencies of the project, I don't think that is a bad idea, but work more faster with that way.

**Comment by sbellver** [comment]
Hi there.

I want to use capacitor geolocation into web.

Which is the best option to do that?

In the production server, I cannot do "quasar dev -m capacitor -T android" because I don't have installed java, android studio and so on,

I need to compile into desktop and then export the dist folder to webserver?

**Comment by renzocastillo** [comment]
Hi! I'm currently facing the same issue, I imported capacitor plugins my quasar vue page but it doesn't find them. However, when I try to do the andriud buld like @Nisgrak  it does work. Is there a way to point to this plugins over web, without creating this boot file ?

**Comment by renzocastillo** [comment]
> For the record (I just receive an email asking my solution).
> 
> I ended doing `quasar dev -m capacitor -T android`, close Android Studio and open the link in the browser anyway. The @capacitor packages are loaded and works in the browser like a charm (you need to make some adjustments in geolocation, for example, but works).
> 
> You can add surely @capacitor packages to dependencies of the project, I don't think that is a bad idea, but work more faster with that way.

@Nisgrak  which link you mean? 
![image](https://user-images.githubusercontent.com/21372177/141234421-6b15792d-23ac-4031-ab11-21431dfb0041.png)


BTW. I'm trying to implement background geolocation using capacitor with quasar. Could you please recommend me a good library/ plugin for that ?

**Comment by renzocastillo** [comment]
Just for the record I solved it by pointing to src-capacitor this way:
import { Geolocation } from "../../src-capacitor/node_modules/@capacitor/geolocation"
import { Device } from '../../src-capacitor/node_modules/@capacitor/device';

not sure if its the "right" way to do it though
