### ISSUE TITLE
q-btn text-color property not change in dark mode

### ISSUE THREAD

**Issue by DjawadT** [quasarframework/quasar#7927]
hi every body
Im trying to add dark mode to my project
i have my own custom colors and also i set text-color property for all buttons

now in dark mode, my button text color no change!

when i set text color in q-btn class it changes in dark mode but in text-color prop not

Can anyone help me?

**Comment by hawkeye64** [comment]
@DjawadT You are setting the color explicitly, so you are also responsible for dark mode. This is what I do. You can adapt it for your needs:
```
:class="{ 'text-black bg-grey-4': $q.dark.isActive, 'text-white bg-primary': !$q.dark.isActive }"
```
