### ISSUE TITLE
@quasar/app@2.1.2 throws an error in electron app

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#7928]
Create  quasar app on win64:
**quasar create test
cd test
quasar dev -m -electron** 

 App threw an error during load
SyntaxError: Invalid left-hand side in assignment
    at Object../node_modules/debug/src/node.js (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:175:1)
    at __webpack_require__ (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:21:30)
    at eval (webpack:///./node_modules/debug/src/index.js?:9:19)
    at Object../node_modules/debug/src/index.js (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:164:1)
    at __webpack_require__ (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:21:30)
    at eval (webpack:///./node_modules/electron-localshortcut/index.js?:6:16)
    at Object../node_modules/electron-localshortcut/index.js (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:270:1)
    at __webpack_require__ (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:21:30)
    at eval (webpack:///./node_modules/electron-debug/index.js?:3:23)      
    at Object../node_modules/electron-debug/index.js (F:\TEST\ELECTRON\t2\.quasar\electron\electron-main.js:198:1)

after 
****npm update****  
which updates to @quasar/app@2.1.2 ( and  some other packages)
the same error is thrown

after 
**npm uninstall @quasar/app
npm install @quasar/app@2.1.1**

Everything works OK.
**So @quasar/app@2.1.1 works** 
**But Quasar/app@2.1.0  and @quasar/app@2.1.2  dont work with ELECTRON**

**Comment by hawkeye64** [comment]
@fprijate Please provide your code from `/src-electron/main-process/electron-main.js`
I don't get this in my own Electron app.
I am pretty sure this is a user error, but can't help you if we can't see the uncompiled source.
From the above, the compiled source is getting an error at line 175, but this is what it looks like to me:
![image](https://user-images.githubusercontent.com/10262924/96619646-a7ea3980-12c3-11eb-950d-487b7556ce89.png)

**Comment by hawkeye64** [comment]
As you can see, this is also incluing node_modules dependencies. So, you should also include your "dependencies" from package.json

**Comment by fprijate** [comment]
There is no "my code".
This is your code created with 
**quasar create test**
and nothing more.
It was created half an hour ago.
I you repeat this simple step. you get all the code.
By the way I am using @quasar/cli@1.1.2 if this has some meaning.

**Comment by fprijate** [comment]
And here is zipped dir with "Your - (Quasar team) code
[test.zip](https://github.com/quasarframework/quasar/files/5410576/test.zip)

It doesn't work on my machine .
If I change @quasar/app to 2.1.1 , it works again.
Try it yourself please.
And thanks for your quick reaction.

**Comment by rstoenescu** [comment]
Thanks for reporting this.
Fixed it in "@quasar/app" v2.1.3.

**Comment by fprijate** [comment]
At the same time I  comented out devteron from electron-main.dev.js 
And  everything works again. Deveteron didn't work anyhow (no icon in devtools) for some time

**Comment by fprijate** [comment]
This is new code which solves the problem.
As I said Devteron isn't working for some time .
The last release is 4 years old and there is a message:
WARNING: Devtron is currently unmaintained.
So I think, that you can remove it without any real damage.

`/**
 * This file is used specifically and only for development. It installs
 * `electron-debug` & `vue-devtools`. There shouldn't be any need to
 *  modify this file, but it can be used to extend your development
 *  environment.
 */


//import electronDebug from 'electron-debug'
import installExtension, { VUEJS_DEVTOOLS } from 'electron-devtools-installer'
import { app } from 'electron'

// Install `electron-debug` with `devtron`

//electronDebug({ showDevTools: true })
// Install vuejs devtools
app.whenReady().then(() => {
  installExtension(VUEJS_DEVTOOLS)
    .then(name => {
      console.log(`Added Extension: ${name}`)
    })
    .catch(err => {
      console.log('An error occurred: ', err)
    })
})

import './electron-main'`

**Comment by siauderman** [comment]
I see that it's supposed to be fixed in 2.1.3, but I just installed 2.1.11 and it still does not work unless I comment out the electron-debug lines.

**Comment by hawkeye64** [comment]
@siauderman I created a brand new project and built electron with no issue.

```bash
$ quasar dev -m electron

 Dev mode.......... electron
 Pkg quasar........ v1.14.7
 Pkg @quasar/app... v2.1.11
 Debugging......... enabled

 Configured browser support (at least 87.88% of global marketshare):
 · Chrome for Android >= 87
 · Firefox for Android >= 83
 · Android >= 81
 · Chrome >= 77
 · Edge >= 84
 · Firefox >= 74
 · iOS >= 10.3
 · Opera >= 68
 · Safari >= 11

 App · ⚠️  Quasar ELECTRON is missing. Installing it...
 App · Installing Electron dependencies...
 App · [sync] Running "yarn add --dev electron@^9.0.0 electron-debug@^3.0.1 electron-devtools-installer@^3.0.0 devtron@^1.4.0"

yarn add v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
warning devtron > highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-loader@3.0.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 22 new dependencies.
info Direct dependencies
├─ devtron@1.4.0
├─ electron-debug@3.1.0
├─ electron-devtools-installer@3.1.1
└─ electron@9.4.0
info All dependencies
├─ accessibility-developer-tools@2.12.0
├─ devtron@1.4.0
├─ electron-debug@3.1.0
├─ electron-devtools-installer@3.1.1
├─ electron-is-accelerator@0.1.2
├─ electron-is-dev@1.2.0
├─ electron-localshortcut@3.2.1
├─ electron@9.4.0
├─ extract-zip@1.7.0
├─ fd-slicer@1.1.0
├─ highlight.js@9.18.5
├─ humanize-plus@1.8.2
├─ immediate@3.0.6
├─ jszip@3.5.0
├─ keyboardevent-from-electron-accelerator@2.0.0
├─ keyboardevents-areequal@0.2.2
├─ lie@3.3.0
├─ pend@1.2.0
├─ set-immediate-shim@1.0.1
├─ unzip-crx-3@0.2.0
├─ yaku@0.16.7
└─ yauzl@2.10.0
Done in 8.33s.
 App · Creating Electron source folder...
 App · Electron support was added
 App · Reading quasar.conf.js
 App · Checking listening address availability (0.0.0.0:8080)...
 App · Transpiling JS (Babel active)
 App · Extending Renderer process Webpack config
 App · Extending Main process Webpack config
 App · Generating Webpack entry point
 App · Booting up...


 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 8863 ms
 └── Main process     █                    0% 



 DONE  Compiled successfully in 8868ms                                                                                                                                         7:38:42 AM

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from 
 App · Building main Electron process...

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 8863 ms
 └── Main process     ████████████████████ 100% done in 736 ms

 App · Webpack built Electron main process

Hash: a8dbcd528714fb01adf0
Version: webpack 4.44.2
Time: 738ms
Built at: 12/12/2020 7:38:43 AM
           Asset     Size         Chunks             Chunk Names
electron-main.js  706 KiB  electron-main  [emitted]  electron-main
Entrypoint electron-main = electron-main.js

 App · Booting up Electron process...
 App · Running "/data2/projects/sandbox/electron-test/node_modules/electron/dist/electron --inspect=5858 /data2/projects/sandbox/electron-test/.quasar/electron/electron-main.js"

Debugger listening on ws://127.0.0.1:5858/52a0e903-d2d5-47ca-9c93-5d63eb31390b
For help, see: https://nodejs.org/en/docs/inspector
(node:797737) ExtensionLoadWarning: Warnings loading extension at /home/jeff/.config/Electron/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
Added Extension: Vue.js devtools
```
and result:
![image](https://user-images.githubusercontent.com/10262924/101986785-4d2ee780-3c4d-11eb-9589-5adcc658328c.png)

**Comment by hawkeye64** [comment]
I just noticed this on a brand new project:
```
warning devtron > highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
```
and if you run this in console (as outlined here: https://www.electronjs.org/devtron):
```js
require('devtron').install()
```
Then you get this error:
```
electron/js2c/renderer_init.js:131 Uncaught (in promise) Error: Loading extension at /data2/projects/sandbox/electron-test/node_modules/devtron failed with: The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.
```

**Comment by hawkeye64** [comment]
https://github.com/electron-userland/devtron/issues/200
