### ISSUE TITLE
bug: keyboard_arrow_right does not disappear in material theme of QDatetime when max month reached

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar#793]
### Software version

Quasar: 0.14
OS: Desktop / Material Theme

### What did you get as the error?

![screen shot 2017-08-11 at 12 13 19 am](https://user-images.githubusercontent.com/500715/29202950-28cf79e8-7e2a-11e7-9d94-f4910f9d73f6.png)

Create a date selector in material theme. Set a max date. You can see that the correct days are greyed out in the calendar. However, the 'next month' arrow in the upper right remains active and clicking on it messes up date selection. 

FYI, looking through code in src/components/datetime/InlineDatetimeMat.vue, there is a function defined "aferMaxDays" which is a misspelling and you are attempting to call "afterMaxDays()" (presumably correct spelling) at least once in the code base.

### What were you expecting?

The next month button (keyboard_arrow_right) should disappear if there is no next month that can be selected because of the 'max' value. I'm guessing this error exists for min, but I didn't test to reproduce.

### What steps did you take, to get the error?

Set a :max value on QDatetime, click 'next month' icon repeatedly

**Comment by rstoenescu** [comment]
Available in v0.14 edge

**Comment by mattwright** [comment]
thank you!!
