### ISSUE TITLE
Extra padding with QEditor's link command when wrapped with QField

### ISSUE THREAD

**Issue by kpwbo** [quasarframework/quasar#7932]
**Describe the bug**
When a QEditor is wrapped with a QField that has a label, the QEditor's link command's input has extra padding over it.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/kpwbo/pen/NWrRzwe

**To Reproduce**
1. In the codepen, enter some text in the QEditor.
2. Select the entered text.
3. Click on the link command. The link command's input should appear.
4. Notice that the link command's input is not aligned with the text "URL:" because it has extra padding on top of it.
5. Remove the label on the QField and try again. Notice that the extra padding is not there and that the link command's input is aligned with the text "URL:".

**Expected behavior**
The input should not have extra padding and should be aligned with the text "URL:" when wrapping the QEditor with a QField that has a label.

**Screenshots**
![image](https://user-images.githubusercontent.com/5074608/96660694-44d6c200-1318-11eb-923c-28b62ce4a406.png)

**Platform (please complete the following information):**
Quasar 1.14.2 on Codepen.
OS: Windows
Browsers: Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.3.
