### ISSUE TITLE
Infinite Scroll in reverse mode always auto-fire at least once

### ISSUE THREAD

**Issue by kapchew** [quasarframework/quasar#7933]
**Describe the bug**
Infinite Scroll in reverse mode always auto-fire at least once. If it is in normal mode (without reverse), it works as expected

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/kapchew/pen/GRqjBre

**To Reproduce**
1. Please check the console that shows it will always trigger the onLoad event upon first load, regardless how may items initially loaded
2. If the "reverse" property is removed, it works properly

**Expected behavior**
Reverse mode should work as normal mode.

**Screenshots**

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
