### ISSUE TITLE
[service-worker]🙏On macOS Safari and ios Safari, the offline.html cache cannot be updated no matter how many times you refresh or restart the browser.

### ISSUE THREAD

**Issue by xiaoer3301** [quasarframework/quasar#7935]
**Describe the bug**
On macOS Safari and ios Safari, the offline.html cache cannot be updated no matter how many times you refresh or restart the browser.
Chrome and Edge behave normally, the problem only occurs in Safari.

When requesting service-worker.js, there are still cached information such as ʻEtag` in the response headers. Can this problem be solved if removed?

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**Screenshots**
![iShot2020-10-21-11 33 35](https://user-images.githubusercontent.com/49556560/96671239-ed763780-1393-11eb-81b4-75a046f3c939.png)

**Platform (please complete the following information):**
OS: macOS Safari14.0 (15610.1.28.1.9, 15610), ios 13.5 Safari
Node :v12.13.1
NPM: 6.14.8
Browsers: macOS Safari14.0 (15610.1.28.1.9, 15610), ios 13.5 Safari

**Comment by rstoenescu** [comment]
Hi,

You will need to configure the deployment's webserver cache time to lower values for the .html files. This is outside of Quasar's reach as it's something that the developer needs to configure himself/herself.
