### ISSUE TITLE
Named import from json will be deprecated from webpack 5

### ISSUE THREAD

**Issue by renekaesler** [quasarframework/quasar#7943]
**Is your feature request related to a problem? Please describe.**
When using Quasar with webpack 5 you will get the following console warnings:

`Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`

The reason for this warning is the named import from json, wich webpack will not support in the future:
- `node_modules/quasar/src/install.js`
- `node_modules/quasar/src/vue-plugin.js`

**Describe the solution you'd like**
These warnings are really annoying. It would be nice if quasar will support webpack 5. The implementation is quite simple. The json file has to be imported as default & the version has to be accessed directly.

```javascript
// install.js
// ==========

import pkg from '../package.json'

// ...previous code

export const $q = {
  version: pkg.version,
  config: {}
}


// vue-plugin.js
// =============

import install from './install.js'
import pkg from '../package.json'
import lang from './lang.js'
import iconSet from './icon-set.js'
import ssrUpdate from './ssr-update.js'

export default {
  version: pkg.version,
  install,
  lang,
  iconSet,
  ssrUpdate
}

```

**Comment by rstoenescu** [comment]
Fixed for Quasar v2.

Unfortunately, it's not easy to backport the fix to Quasar v1 also without introducing a breaking change (a required minimum version of q/app). But as things stand, Quasar v1 won't get Webpack 5 anyways (too many heavy breaking changes would be required overall). So closing because of being fixed in future Quasar v2.
