### ISSUE TITLE
[Chip] Add router props

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#7944]
**Is your feature request related to a problem? Please describe.**
```
// template
<q-chip clickable @click="onClick" />

// methods
onClick () {
  this.$router.push(..)
}
```

**Describe the solution you'd like**
It would be great if one could use the same router props as seen in qBtn/qItem/.. (`to`, `replace`, `append`):

```
<q-chip :to="{ name: 'home' }" />
```

**Describe alternatives you've considered**
Using $router in methods as seen in first example.

**Additional context**
Should the `chip` component be wrapped into another element instead?

Thanks!

**Comment by rstoenescu** [comment]
Hi,

But you can add a click listener and make it this.$router.push(..route..)
It makes sense for a few key components to have this ability, but not all. Don't think anyone would want a bloated and a disaster perf-wise framework.

**Comment by francoism90** [comment]
@rstoenescu Thanks for your reply.

I don't want to use an bloated framework as well, if this causes a lot of overhead to the code than I'll be fine without these props and use the `@click` method instead.
