### ISSUE TITLE
Item-Aligned QSelect in Dialog Mode has extra padding

### ISSUE THREAD

**Issue by gruppler** [quasarframework/quasar#7945]
**Describe the bug**
A QSelect with the attribute `item-aligned` has extra padding in the dialog popup.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gruppler/pen/zYBNEvb

**To Reproduce**
1. Create a QSelect with `item-aligned` and `behavior="dialog"` (or use it on a mobile device)
2. Click on the input
3. See the extra padding in the pop-up copy of the input

**Expected behavior**
It should look as it does without `item-aligned`

**Comment by gruppler** [comment]
Basically we just need to add something like `.q-select__dialog .q-field--item-aligned { padding: 0; }`

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
