### ISSUE TITLE
Dark Dialog Plugin Prompt hard-coded with text-amber

### ISSUE THREAD

**Issue by gruppler** [quasarframework/quasar#7946]
**Describe the bug**
A prompt created with the Dialog Plugin in Dark Mode has 'text-amber' hard-coded on the QField with no apparent way to override.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gruppler/pen/MWeJEeq

**To Reproduce**
1. Create a prompt in Dark Mode with the Dialog Plugin
2. Open the prompt dialog
3. See the input color is amber

**Expected behavior**
Either use the primary color, or accept a color option.

**Comment by pianopronto** [comment]
@gruppler the dialog plugin does indeed have a color option:

```
this.$q.dialog({
        dark: true,
        title: 'Prompt',
        message: 'What is your name?',
        color: 'primary',
        // ...
})
```

**Comment by rstoenescu** [comment]
As @pianopronto said.

**Comment by gruppler** [comment]
I could have sworn I tried this and it didn't work, but you are correct. Thanks!
