### ISSUE TITLE
q-select can't show properly in the q-table top slot

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#7949]
**Describe the bug**
when the q-table top slot use the q-select, the select label can't show

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/zouzg7829/pen/pobRxPZ

**To Reproduce**
1. the q-select lable 'Standard' can't show

**Expected behavior**
q-select show properly and the q-select lable 'Standard' can show

**Screenshots**
none

**Platform (please complete the following information):**
none

**Additional context**
none

**Comment by hawkeye64** [comment]
@zouzg7829 Give your QSelect a width style: https://codepen.io/Hawkeye64/pen/wvWgQgQ

**Comment by zouzg7829** [comment]
@hawkeye64 of course, you can use style attribute to solve it,  but I think QSelect should have own initial width to render itself, in this sample, the QSelect **SHOULD** will render the 'Standard' label correctly when first show in UI

**Comment by rstoenescu** [comment]
@zouzg7829 The problem is more complex. Cannot add a default width because it will break other use-cases of QSelect. Just like native input/select, most likely you'll need to set a width for it.
