### ISSUE TITLE
[Request] Custom color for v-ripple directive

### ISSUE THREAD

**Issue by devistar** [quasarframework/quasar#795]
Currently, the v-ripple directive uses only the color of the element. It would be great to be able to define a custom color not linked to the element color.

Example : 
`<q-item style="color: black" v-ripple="blue">...</q-item>` => does a blue ripple effect.

Best regards

**Comment by rstoenescu** [comment]
This would affect performance so it's a no-go. Best way to proceed is to declare "color: black" on the subitems of QItem.
