### ISSUE TITLE
Configurable QPortal target element

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#7950]
**Is your feature request related to a problem? Please describe.**
I had to encapsulate quasar styles not to affect parent project
```css
.wsk-root {
  @import './wsk_vars.scss';
  @import './wsk_theme.scss';
  @import '~quasar/src/css';
  @import '~quasar/src/css/flex-addon';
}
```
problem is that QDialog and QMenu append body and therefore quasar styles are missing there :/

**Describe the solution you'd like**
I would need to configure to use not document body element, but Element with `.wsk-root` class so Quasar styles applies also there.

```js
Vue.use(Quasar,{
    // sets portal element so quasar styles applies also to ported elements
    portalTarget: document.querySelectorAll('.wsk-root')[0],
   // other settings ...
    iconSet: mdiV4,
    plugins: {
      Notify,
    },
});
```

**Describe alternatives you've considered**
When I come with some I will write them here.

Thank you 🙏

**Comment by pdanpdan** [comment]
Hello. The dialogs/menus are rendered there for that exact reason - to not be affected by the environment CSS.
But you can add a class selector to them and define the styles you need starting from there.

**Comment by ivan006** [comment]
best you can do is

```

[id^="q-portal--"],
.wsk-root {
  @import './wsk_vars.scss';
  @import './wsk_theme.scss';
  @import '~quasar/src/css';
  @import '~quasar/src/css/flex-addon';
}
```
