### ISSUE TITLE
ssr+pwa mode not caching offline.html after reload in development

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/quasar#7952]
**Describe the bug**
While running `quasar dev -m ssr` with pwa enabled in the quasar config and using InjectManifest, the first load in the browser works fine. But after making changes to the service worker code and reloading, an error occurs because the offline.html is not precached. 

**To Reproduce**
1. create new quasar project
2. add ssr and pwa modes
3. enable pwa mode for ssr and use InjectManifest workboxPluginMode
4. Use the following code for custom-service-worker.js:
```
import { setCacheNameDetails, skipWaiting, clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { CacheFirst } from "workbox-strategies";

setCacheNameDetails({ prefix: "quasar-app" });
clientsClaim();
skipWaiting();

self.addEventListener("message", event => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    console.log("in condition: ", event);
  }
});
self.__precacheManifest = [].concat(self.__WB_MANIFEST || []);
precacheAndRoute(self.__precacheManifest);

registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst()
);

registerRoute(
  new NavigationRoute(createHandlerBoundToURL("/offline.html"), {
    denylist: [/service-worker\.js$/, /workbox-(.)*\.js$/]
  })
);
```
5. Open browser and console an connect to the page
6. make some change to the service worker
7. Reload the page and see error:
```
Uncaught non-precached-url: createHandlerBoundToURL('/offline.html') was called, but that URL is not precached. Please pass in a URL that is precached instead.
```

**Expected behavior**
service-worker should cache offline.html on all reload

**Screenshots**
![Screenshot from 2020-10-25 22-03-05](https://user-images.githubusercontent.com/10757342/97120316-1f79f780-170e-11eb-8014-88d9a9d90c57.png)

**Platform (please complete the following information):**
OS: Zorin OS 15.3
Node: 14.14
NPM: 6.14.8
Yarn: 1.22.5
Browsers: Chromium Version 86.0.4240.111

**Comment by rstoenescu** [comment]
Please add offline.html to the cache list.
