### ISSUE TITLE
Erro after remove icon-genie v1

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#7953]
**Describe the bug**
I has been upgraded my icon genie from v1 to v2, and when I try to build removing icon-genie v1 form my quasar proejct extension, I'm getting this erro:

![image](https://user-images.githubusercontent.com/24510745/97123796-34558b80-170c-11eb-940c-f78018164d45.png)

Anyone know how to solve?

Here is my quasar info:
![image](https://user-images.githubusercontent.com/24510745/97123669-9c57a200-170b-11eb-9cd2-568b4b916e12.png)

**Comment by rstoenescu** [comment]
Delete node_modules and package-lock.json/yarn.lock, yarn/npm install again.
Note that IconGenie v2 is a CLI and should be installed globally not in your project folder.

**Comment by maico910** [comment]
I have get another issues about missing core-js@3.0 dependencies, but it's solved following upgrade guide in this time, thanks!
