### ISSUE TITLE
UnhandledPromiseRejectionWarning during quasar dev (happens when creating project using latest Node)

### ISSUE THREAD

**Issue by hsalis** [quasarframework/quasar#7954]
**Describe the bug**
Creating a new Quasar project using Quasar CLI while running Node 15.x triggers a UnhandledPromiseRejectionWarning when running Quasar dev.

**To Reproduce**
1. Install Node 15.x and Quasar CLI
2. quasar create <project>
3. cd <project> and quasar dev
4. Output and Error are:

Dev mode.......... spa
 Pkg quasar........ v1.14.2
 Pkg @quasar/app... v2.1.5
 Debugging......... enabled

 Configured browser support (at least 87.77% of global marketshare):
 · Chrome for Android >= 85
 · Firefox for Android >= 79
 · Android >= 81
 · Chrome >= 76
 · Edge >= 83
 · Firefox >= 72
 · iOS >= 10.3
 · Opera >= 67
 · Safari >= 11

 App · Reading quasar.conf.js
 App · Checking listening address availability (0.0.0.0:8080)...
 App · Transpiling JS (Babel active)
 App · Extending SPA Webpack config
 App · Generating Webpack entry point
 App · Booting up...
(node:55337) [DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING] DeprecationWarning: Using a string as loader options is deprecated (ruleSet[0].rules[0].use[0].options)
(node:55337) UnhandledPromiseRejectionWarning:   Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
    "exclude": [
      null
    ],
    "use": [
      {
        "loader": "babel-loader",
        "options": {
          "compact": false,
          "extends": "<snip>/babel.config.js"
        },
        "ident": "clonedRuleSet-2[0].rules[0].use[0]"
      }
    ]
  }
  
  <snip>

**Expected behavior**
App · Opening default browser at http://localhost:8080

**Platform (please complete the following information):**
OS: MacOSx
Node: 15.x

**SOLUTION**
   **Solution:  Delete the entire Quasar project, install Node 12.x and recreate the Quasar project.** 

   However, the issue **was not** resolved by simply uninstalling Node 15.x, installing Node 12.x, deleting node_modules & reinstalling dependencies, and then running quasar dev.

**Comment by hsalis** [comment]
Solution is above, but Googling was not helpful, so paying it forward to the next new Quasar user.

**Comment by rstoenescu** [comment]
Please use Node 12 LTS. Any newer version of Node has issues with webpack 4, including problems related to file watchers.
