### ISSUE TITLE
Textbox (input) size and selectbox size

### ISSUE THREAD

**Issue by muzammil17** [quasarframework/quasar#7956]
hey,
You guys have added dense feature for the size of input to make it smaller . After adding dense property, the input size is still very big and after changing its size using css the whole application is facing issue. So the request is to allow the user to select the size of textbox itself or make a size more small.
This would be very helpful.

**Comment by Saeid-Za** [comment]
here's a naive attempt to override quasar default styles to make input even smaller.
you can play with the values to make it as small as you want, but consider that values below 32 pixels, might harm [UX](https://uxplanet.org/designing-perfect-text-field-clarity-accessibility-and-user-effort-d03c1e26004b#:~:text=A%20rule%20of%20thumb%20is,large%20at%20the%20same%20time.).
Please do note that this is just a workaround and might not work in future or in some special cases, you need to handle them yourself.
```vue
<template>
  <div>
    <q-input dense
      class="super-small"
      label="Hello"
      :input-style="{ fontSize: '12px' }" />
    <q-select dense
      class="super-small"
      label="Hello"
      :input-style="{ fontSize: '12px' }" />
  </div>
</template>

<style lang="scss">
.super-small.q-field--dense {
  .q-field__control-container,
  .q-field__native {
    padding-top: 10px !important;
  }

  .q-field__control {
    height: 32px !important;
    min-height: 32px !important;
  }

  .q-field__marginal {
    height: 32px !important;
  }

  .q-field__label {
    top: 6px !important;
  }
}
</style>
```

**Comment by muzammil17** [comment]
@Saeid-Za  thanks for your help.
Actually I want to use it inside my table and due to the size of the box it is increasing the size of the table which I dont want.
I  want it more smaller. A user should have some props of changing the height or size of the box. Dense property is not that good there should be some more options for changing the size.

**Comment by pdanpdan** [comment]
Hello.
You can either inspect the style in browser or check the source code (SASS or Stylus) and make the required changes from there.
Please us the discord channel or the forum for help requests.
Thank you
