### ISSUE TITLE
Add spread operator in dev-server for ssrExtension 

### ISSUE THREAD

**Issue by adamkpurdy** [quasarframework/quasar#7958]
**Is your feature request related to a problem? Please describe.**
When developing for SSR in dev, adding to the context object in the ssr/extensions.js file isn't being passed to the development server. Whereas in a production build the addition to the context object is available from the ssr/extensions.js 

**Describe the solution you'd like**
Add the spread operator in the dev-server.js at line 235. So the new signature would look like:
```js
ssr: {
            renderToString (opts, fn) {
              const context = {
                ...opts,
                url: opts.req.url
              }
    /.../
        }
    }
```

**Describe alternatives you've considered**
Tried working with @TobyMosque to figure out a way to allow update of the context object during the dev build without touching the dev-server, but unfortunately, the dev-server's args are not allowing any additions to the argument being passed.

**Additional context**
Just to reiterate, this feature is available during a ssr production build. The actual output of the prodcution build is:
```js
module.exports.renderToString = function (opts, cb) {
  const ctx = {
    ...opts,
    url: opts.req.url
  }


  renderer.renderToString(ctx, cb)

}
```

**Comment by rstoenescu** [comment]
Done!
Will be available in q/app v2.1.6.
