### ISSUE TITLE
quasar vue3 with native app build

### ISSUE THREAD

**Issue by eeerrrttty** [quasarframework/quasar#7960]
We all know that the strongest thing that KILL VUE against REACT is just ONE THING:

react build NATIVE APPS. End of story.

Vue is far away the best for learning curve and everything easy to read code, but we are missing this 'native development'.

Vue 3 comes with the composition API which as i saw will make it much easier to build something to build native using vuejs.

Let's be true, if we get to have quasar + native build using vue 3, quasar will be far away be THE BEST FRAMEWORK EVER.

So i ask here:

Is it possible?
If yes, what is necessary to have it ?
Can we ask founds to this ?
What would be the cost ?
What would be the time cost ?

Of course this feature request is after the complete integration with vue3,
but i think this could be the biggest thing ever made in the development world.

**Comment by hawkeye64** [comment]
@eeerrrttty I think you are looking for this: https://nativescript.org/vue/

**Comment by eeerrrttty** [comment]
No Hawkeye, i'm not looking for nativescript. Are you really comparing nativescript with quasar framework ?

nativescript compiles to REACT, to THEN compile to native.
I'm talking of QUASAR/VUE doing IT. 

**Not the shit react.**

so yes, i'm sugesting quasar doing it, 

WHY NOT ?

**Comment by rstoenescu** [comment]
First of all, I'd appreciate if the posts would not contain that kind of language.

Secondly, If you want to hop to the nativescript bandwagon, Quasar is not the right place to search for it.
Writing a Quasar nativescript would mean writing another framework from scratch. You're asking for a completely different framework. The foundation is different from all angles. **Understanding** that technology would immediately answer your question.

**Comment by rstoenescu** [comment]
Thirdly, if you imagine you can have the same area of freedom like in a browser you're wrong. I've seen a lot of people interested in such technology only to come back later.

**Comment by eeerrrttty** [comment]
Sorry for language, really, i'm a superfan of quasar and vue, so...

that's the thing, quasar is really powerfull and full of components and everything, alongside with a very well structured code and docs (thing that nativescript is distant as infinity).

But the core thing is that we do not have a great way of doing native apps using vue tech with no one framework (let's be true, nativescript does use react).

Of course we wouldn't have such freedom as browser, but the most common components as form, etc ... simple core to build VUE -> NATIVE.

Do you think this reality is possible ? Making a vue project build directly to native ?

**Comment by eeerrrttty** [comment]
And let's be true, you are the boss in this thing of framework building, you are really in another level of development

**Comment by rstoenescu** [comment]
Anything's possible. The financing of this work is the problem.

**Comment by eeerrrttty** [comment]
how much, tell me, please.
