### ISSUE TITLE
QTable Header w/ Virtual Scroll on Mobile Safari

### ISSUE THREAD

**Issue by tmas** [quasarframework/quasar#7961]
**Describe the bug**
On mobile Safari, using the virtual scroll option on QTable leads to the table header container (`.q-table__top`) being too short to contain its contents. This causes the table title to overlap the table's contents upon scrolling.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.
This bug can be reproduced on the virtual scroll example from the Quasar documentation: https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fquasar.dev%2Fvue-components%2Ftable

**To Reproduce**
1. Acquire an iOS device and open Safari
2. Open the Codepen link above, or navigate to https://quasar.dev/vue-components/table#Virtual-scrolling
3. Scroll down in the table contents slightly
4. You should see the table title overlap the table's row contents

**Expected behavior**
The table header should be sufficiently tall to contain its contents, rather than allowing them to overflow and overlap the table's rows.

**Screenshots**
![Screenshot of problem on iPad running Safari](https://i.imgur.com/uU0f3mz.png)

**Platform (please complete the following information):**
OS: iPadOS 14.0.1 (dev server is running on Ubuntu 19.10)
Node: 12.16.1
NPM: 6.14.8
Yarn: 1.22.5
Browsers: Mobile 
iOS: 14.0.1
Android: N/A
Electron: N/A

**Additional context**
This problem occurs when using custom table header content (`v-slot:top`) and when using the `title` prop.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.7.
