### ISSUE TITLE
Dialog Plugin with more than 2 buttons

### ISSUE THREAD

**Issue by Fanvadar** [quasarframework/quasar#7963]
**Is your feature request related to a problem? Please describe.**
I want to create a dialog that has three buttons: 
* Save
* Don't save
* Cancel

Much like Word when you close a doc without saving.

**Describe the solution you'd like**
I'd like some way of creating additional buttons (other than Ok and Cancel) in a Dialog Plugin, with the ability to handle their click.

**Describe alternatives you've considered**
A QDialog could be used instead - however, since I am placing this in beforeRouteLeave it's a bit tricky.

**Comment by matejmohar** [comment]
When I need more buttons I use custom component, then you can have as many buttons as you wish.

**Comment by rstoenescu** [comment]
The custom component (as indicated above too) is the way to go if you want something really specific.

**Comment by asdrubalp9** [comment]
how about customizing a third option for dismiss? there is already a function for it:
 }).onDismiss(() => {
    console.log('Called on OK or Cancel')
  })

**Comment by rstoenescu** [comment]
`onDismiss` is called not only when clicking on the already existing buttons, but may come as a result of user hitting the ESC key or clicking on the backdrop.
Again, the Dialog plugin is meant to cover only the most basic functionality, just like the native `alert()`. Should you need something more specific, don't be afraid to write a component and call the Dialog plugin with it (it's really easy).
