### ISSUE TITLE
QPageContainer paddingBottom calc incorrect in mobile!!!

### ISSUE THREAD

**Issue by ghf1990525** [quasarframework/quasar#7965]

**Comment by pdanpdan** [comment]
Please fill the issue template

**Comment by ghf1990525** [comment]
![dac19b93ed554326ee986bad689245cf](https://user-images.githubusercontent.com/24802764/97436156-7d9c1a00-195c-11eb-8566-651000103770.jpg)
![用户管理](https://user-images.githubusercontent.com/24802764/97436157-7d9c1a00-195c-11eb-8e4f-08fef05b771e.png)

**Comment by rstoenescu** [comment]
No explanation given, no filling of the issue template like requested. And moreover logging a presumed bug over a battle-tested feature. Closing. Feel free to reopen with proper explanations.

**Comment by ghf1990525** [comment]
<img width="473" alt="企业微信截图_1606726150842" src="https://user-images.githubusercontent.com/24802764/100587855-1216e500-332c-11eb-8c44-769f8b3e50e9.png">

**Comment by ghf1990525** [comment]
![image](https://user-images.githubusercontent.com/24802764/100588456-d29cc880-332c-11eb-8ca2-9868f68b4d8b.png)

**Comment by ghf1990525** [comment]
![image](https://user-images.githubusercontent.com/24802764/100588507-e47e6b80-332c-11eb-94af-1abc09bbd0aa.png)

**Comment by ghf1990525** [comment]
header&fotter Covered by status bar,
But it is not on all mobile phones, but will appear on Huawei mobile phones。 @pdanpdan

**Comment by hawkeye64** [comment]
@ghf1990525 This would be hard. I don't anyone with a Huawei and it's not one of the mobile phones offered on Browserstack. Although, I do know this is a very popular phone in China.

**Comment by ghf1990525** [comment]
Thank you for your answer, I have solved this problem! @hawkeye64

**Comment by hawkeye64** [comment]
@ghf1990525 Please feel free to enlighten us so we have an answer for next time.
