### ISSUE TITLE
q-time options hrs 11&23 Broken

### ISSUE THREAD

**Issue by martinfruehmorgen** [quasarframework/quasar#7968]
The q-time options is broken with hour #11 and #23
You can see this in the following codepen (see console): Hour 11 and 23 is missing

https://codepen.io/martinfruehmorgen/pen/oNLExZY?editors=1011

Thanks

**Comment by rstoenescu** [comment]
Ah.. thanks for reporting.
Fix will be available in Quasar v1.14.4.
