### ISSUE TITLE
QEditor: toolbar menu - list: 'no-icons' has no effect

### ISSUE THREAD

**Issue by ldiebold** [quasarframework/quasar#7969]
**Describe the bug**
With QEditor, when adding `no-icon` to an object in the toolbar, the labels still show.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ldiebold/pen/gOMvXqV

**To Reproduce**
1. go to the codepen link above
2. notice the **list** attribute is set to **only-icons**
3. open the menu
4. notice the label still shows

**Expected behavior**
labels should no longer be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1305724/97502752-e10f6180-19c7-11eb-87d3-f40d6290fbce.png)

**Platform (please complete the following information):**
OS: Ubuntu
Node: v14.14.0
NPM: 6.14.8
Yarn: 1.22.5
Browsers: chrome
iOS: na
Android: na
Electron: na

**Comment by rstoenescu** [comment]
I think you mean "no-icons" has no effect, rather than "only-icons" not working.

**Comment by rstoenescu** [comment]
Fix for "no-icons" will be available in Quasar v1.14.4.
