### ISSUE TITLE
[Request] Allow 'prefix' in QDatetime to act as a prompt (like stack-label)

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#797]
I would prefer to use `prefix` as a prompt in a date picker - they can make the reading of a single-row field with multiple values 'flow' much better - e.g.:

    <div class="row nowrap">
      <q-input v-model="signupCode" />
      <q-datetime prefix="Valid from:" v-model="signupValidFrom" type="date" />
      <q-datetime prefix="Until:" v-model="signupValidUntil" type="date" />
    </div>

but the prefix is only shown if there is a valid date selected, and so it can't really be used as a prompt. Perhaps a `prefix-always` alternative to preserve the current behaviour?

**Comment by rstoenescu** [comment]
Hi,

I'm sorry but I'm gonna have to close this as this feature would seriously interfere with stack/float labels.
