### ISSUE TITLE
the QTab can't work well in the QCard  if using  such as `<q-tab ... />`  tag

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#7972]
**Describe the bug**
the QTab can't work well in the QCard if using  such as `<q-tab ... />`  tag, But it is ok if using `<q-tab ...></q-tab>`  tag,
what's the difference between `<q-tab name="mails" label="Mails"></q-tab>` and `<q-tab name="mails" label="Mails"/>`?

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/zouzg7829/pen/PozRGPY

**To Reproduce**
1. the QTab can't show correctly.
2. if replace `<q-tab ... />` tag with  `<q-tab ...></q-tab>`  tag, it is ok.

**Expected behavior**
`<q-tab ... />` tag  and `<q-tab ...></q-tab>`  **SHOULD** work the same

**Screenshots**
none

**Platform (please complete the following information):**
none

**Additional context**
none

**Comment by rstoenescu** [comment]
I assume that you're talking about the UMD usage. And it's explained in the docs. The template needs to be valid before Vue kicks in and parses it. And custom tags are not recognized by the browser that they are self-closing. Even if this would be a bug, it has nothing to do with Quasar.

**Comment by zouzg7829** [comment]
@rstoenescu yes, you are right
