### ISSUE TITLE
QInput color and bgColor with any color besides quasar palette

### ISSUE THREAD

**Issue by rulrok** [quasarframework/quasar#7973]
**Is your feature request related to a problem? Please describe.**
I am building a site constructor where the user can customize the UI through a visual editor.
Among many options, the user can freely choose an input's background color from a color picker.

![image](https://user-images.githubusercontent.com/3097987/97714348-ca3c3e00-1a9f-11eb-86f7-cabc37681888.png)

Thus, the color will be some #HEX or RGB() string.

Today, `q-input` will just configure the `color/bgColor` passed in as `text-{color}/bg-{bgColor}`.

![image](https://user-images.githubusercontent.com/3097987/97714521-07a0cb80-1aa0-11eb-953c-abde461ab671.png)

**Describe the solution you'd like**
Either `color` and `bgColor` accepts a string which would be validated by `anyColor` util function, or add another option to accept these colors other than quasar palette.

So, one solution I see is to instead of using the `text-{color}`/`bg-{bgColor}` classes, just add an inline `style` to the rendered `.q-field__control`
![image](https://user-images.githubusercontent.com/3097987/97716007-d3c6a580-1aa1-11eb-9b04-2b5c3c7695c3.png)

**Describe alternatives you've considered**

I tried to use using `input-style` with background, but it leads to inconsistent styles.
![image](https://user-images.githubusercontent.com/3097987/97714695-3dde4b00-1aa0-11eb-90ab-b8bd6beee273.png)

Using `bgColor`:
![image](https://user-images.githubusercontent.com/3097987/97714611-243d0380-1aa0-11eb-94bf-8d95d94747cf.png)

**Comment by pdanpdan** [comment]
Hello. Please check the docs on how to support brand colors (custom colors).
