### ISSUE TITLE
select with chinese height change

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar#7978]
select with chinese height change

https://codesandbox.io/s/eloquent-franklin-jxydv?file=/src/App.vue

1. change select value in options
2. height will change

**Comment by hawkeye64** [comment]
@anyclub In your Codesandbox for QInput, you are incorrectly using the `item-aligned` property. You have it set to `item-aligned="center"`. This property is a Boolean.
![image](https://user-images.githubusercontent.com/10262924/97785316-e9070700-1b69-11eb-9831-4a3efa5708c3.png)

**Comment by anyclub** [comment]
https://codesandbox.io/s/eloquent-franklin-jxydv?file=/src/App.vue

This is an irrelevant attribute, ignore it
I renewed the DEMO

**Comment by hawkeye64** [comment]
Thanks for adjusting it. I have created a codepen with the data you supplied here: https://codepen.io/Hawkeye64/pen/mdELRbM

**Comment by hawkeye64** [comment]
@anyclub  I have fixed in my referenced codepen. https://codepen.io/Hawkeye64/pen/mdELRbM?editors=1010
It's because you have the class "column" on the `q-card`. Remove that and all will be good.

**Comment by anyclub** [comment]
Ok, solved the problem
However, I think this can be considered in the document. I did not find a reminder on the document that COLUMN cannot be used in Q-CARD. It did cause a lot of confusion.

**Comment by hawkeye64** [comment]
@anyclub To be honest, I didn't either. Flex can sometimes work against you.

**Comment by rstoenescu** [comment]
Column can be used on QCard but only along a fixed height (due to how flex works).
