### ISSUE TITLE
align QAjaxBar with QCircularProgress & QLinearProgress APIs

### ISSUE THREAD

**Issue by andrisi** [quasarframework/quasar#7979]
QAjaxBar is useful in all the same scenarios as the other progress indicators, that is waiting for something calculated in the browser or a remote operation, but uses a different scale (1-100 vs. 0-1), has another way to set the value programatically (move by value vs. position value), and is linked to AJAX hooks in the browser. Perhaps using the same 0 to 1 scale as it's more granular than a 100 distinct values (think of waiting for 150 values to come in), having the ability to set to arbitary values (including going back a little) and making the link to AJAX calls and auto-increase optional you could make this component more universal. Thanks! 

Minor bug: the first increase() call seems to jump without easing unlike later ones if done right after the start() call.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
