### ISSUE TITLE
[Request] Make double-click on dates in QDatetime picker trigger `set()`

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#798]
Pretty much that is all :).

**Comment by NothingWeAre** [comment]
Or maybe option to accept click on bottom level as `set()`. Some users are lazy, and complaining about having to press another button (

**Comment by rstoenescu** [comment]
Closing as duplicate of https://github.com/quasarframework/quasar/issues/798

**Comment by dsl101** [comment]
Duplicate of itself?

**Comment by rstoenescu** [comment]
Damn. Duplicate of this: https://github.com/quasarframework/quasar/issues/718
