### ISSUE TITLE
Built in support for web workers

### ISSUE THREAD

**Issue by ssuess** [quasarframework/quasar#7980]
As apps I have written have grown more complex and larger, I have noticed performance issues that are caused by UI blocking on the main thread. These could in theory be resolved with web workers, but currently they are very difficult (at least for me) to get working in quasar (via webpack mods, etc)

It would be amazing if quasar had built in support for web workers that could be called via some simple keyword or mechanism on any function in a component, or offloaded to a separate component that could pass some meaningful context. 

A deep search around the web does not find anything this elegant, so I suppose there must be reasons for that. That said, at the very least it would be nice if quasar out of the box could configure the following:

1. Webpack setup to use workers (with comlink loader, workerize or something else)
2. Correct eslint/error messaging setup to aid in debugging worker files
3. The above working with hmr, so changes made to workers are picked up immediately in dev environment

None of the above is easy at the moment. At the very least it would be great if clear instructions were added to the docs for how to include and work with them accounting for the three items above.

Let me add that I love quasar as a dev environment, and very much appreciate all the hard work that has gone into making it so great. 

Thanks!

**Comment by jaybo** [comment]
Just to clarify the current state of affairs. Adding support for web workers requires `npm install -D worker-plugin` and then the following change to `quasar.config.js`:
```
const WorkerPlugin = require("worker-plugin");  // at the top of the file
...
 build: {
     ...
     extendWebpack(cfg) {
         cfg.plugins.push(new WorkerPlugin()); // tell Webpack about it
     },
 },
 ```
And that's it.  I can debug the worker in VSCode, and it seems to behave just like any other module in terms of eslint and logging.  The only thing missing is hmr.  I don't really see much to be gained by another abstraction around postmessage between the worker and client.

**Comment by ssuess** [comment]
I don't actually think that solves the problem in the way I described above. I see a lot to be gained from a quasar built-in way of abstracting this actually.

**Comment by caitcif** [comment]
> Just to clarify the current state of affairs. Adding support for web workers requires `npm install -D worker-plugin` and then the following change to `quasar.config.js`:
> 
> ```
> const WorkerPlugin = require("worker-plugin");  // at the top of the file
> ...
>  build: {
>      ...
>      extendWebpack(cfg) {
>          cfg.plugins.push(new WorkerPlugin()); // tell Webpack about it
>      },
>  },
> ```
> 
> And that's it. I can debug the worker in VSCode, and it seems to behave just like any other module in terms of eslint and logging. The only thing missing is hmr. I don't really see much to be gained by another abstraction around postmessage between the worker and client.

Are you using Quasar V2? I am trying to upgrade Quasar from V1 to V2 and I cannot get web workers to compile. I am using workerize-loader in V1 with no issues. Even a vanilla create quasar example and your instructions will not let me compile. I originally used this article in V1:
https://forum.quasar-framework.org/topic/6840/web-workers-how-to-use-in-quasar

I now get this. Same with your instructions:

Module parse failed: Cannot read property 'resource' of undefined
    [quasar2js]/[webpack]/lib/NormalModule.js:813:5
File was processed with these loaders:
 * ./node_modules/workerize-loader/dist/rpc-worker-loader.js
 * ./node_modules/eslint-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
  TypeError: Cannot read property 'resource' of undefined

  - index.js:97
    [quasar2js]/[workerize-loader]/dist/index.js:97:44


  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [quasar2js]/[tapable]/lib/Hook.js:14:14

  - JavascriptParser.js:1904 JavascriptParser.blockPreWalkExportNamedDeclaration
    [quasar2js]/[webpack]/lib/javascript/JavascriptParser.js:1904:35

  - JavascriptParser.js:1496 JavascriptParser.blockPreWalkStatement
    [quasar2js]/[webpack]/lib/javascript/JavascriptParser.js:1496:10

  - JavascriptParser.js:1417 JavascriptParser.blockPreWalkStatements
    [quasar2js]/[webpack]/lib/javascript/JavascriptParser.js:1417:9

  - JavascriptParser.js:3308 JavascriptParser.parse
    [quasar2js]/[webpack]/lib/javascript/JavascriptParser.js:3308:9

  - NormalModule.js:1022
    [quasar2js]/[webpack]/lib/NormalModule.js:1022:26

  - NormalModule.js:749 processResult
    [quasar2js]/[webpack]/lib/NormalModule.js:749:11

  - NormalModule.js:813

**Comment by hawkeye64** [comment]
@caitcif @ssuess You no longer need a plugin with webpack 5 to use web workers. I haven't tried this myself as I have not had the need for it. See their documentation for more info: https://webpack.js.org/guides/web-workers/

Also, from their docs:

> Note that this is only available in ESM. Worker in CommonJS syntax is not supported by either webpack or Node.js.

**Comment by caitcif** [comment]
OMG, I spent hours trying to make it work and it just works out of the box as you said. Thank you so much!

**Comment by hawkeye64** [comment]
I am going to close this now as you have it working. Maybe you can share what you did with @ssuess ?

**Comment by ssuess** [comment]
@hawkeye64 I have not had a chance to look into it, but can @caitcif or someone else verify that all three items at the top of this issue are working with this first? If so, I guess we can close it, although my hope was for a simpler way to invoke web workers in addition to not having to manually install a and configure a plugin. But I realize that may be beyond the scope of quasar at the moment, so if plugin is auto installed, linting and hmr work out of the box, ok to close. Thanks!

**Comment by caitcif** [comment]
> 
> 
> @hawkeye64 I have not had a chance to look into it, but can @caitcif or someone else verify that all three items at the top of this issue are working with this first? If so, I guess we can close it, although my hope was for a simpler way to invoke web workers in addition to not having to manually install a and configure a plugin. But I realize that may be beyond the scope of quasar at the moment, so if plugin is auto installed, linting and hmr work out of the box, ok to close. Thanks!

Yes, it all works as expected. I did:
quasar create quasar2js

I added a file called deep-thought.js in the pages folder:
self.onmessage = ({ data: { question } }) => {
    self.postMessage({
        answer: 42,
    });
};

In Index.vue I added mounted():

  mounted() {
    const worker = new Worker(new URL('./deep-thought.js', import.meta.url));
    console.log("MOUNTED");
    worker.postMessage({
      question:
      'The Answer to the Ultimate Question of Life, The Universe, and Everything.',
    });
    worker.onmessage = ({ data: { answer } }) => {
      console.log(answer);
    };
  }

run:
quasar dev

console shows 42. Changing deep-thought.js recompiles

**Comment by ssuess** [comment]
Great @caitcif thanks!
