### ISSUE TITLE
Material Icons are not working in IE11 (Intranet)

### ISSUE THREAD

**Issue by jmriyaz84** [quasarframework/quasar#7982]
**Describe the bug**
Dear Team , 
Yesterday our quasar based application went live . Material Icons are getting displayed in Chrome but in IE11 it is not working , same good works in Development Environment , but in Production Environment it is not working . Our Production Environment is running on top of VPN , can some one suggest what could be the issue. I have attached both screen for reference.
Development Environment , Material Icons are getting displayed

**Codepen/jsFiddle/Codesandbox (required)**
Only in our Intranet9VPN) it is not working , sane code works without VPN
**Code for Material Icons**
@font-face{font-family:Material Icons;font-style:normal;font-weight:400;font-display:block;src:url(../fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.fa3334fe.woff2) format("woff2"),url(../fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.1811d381.woff) format("woff")}.material-icons{font-family:Material Icons;font-weight:400;font-style:normal;display:inline-block;line-height:1;text-transform:none;letter-spacing:normal;word-wrap:normal;white-space:nowrap;direction:ltr;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;-moz-osx-font-smoothing:grayscale;font-feature-settings:"liga"}

**To Reproduce**
 

**Expected behavior**
It should work in IE11

**Screenshots**
Development Environment
<img width="957" alt="Dev Server" src="https://user-images.githubusercontent.com/8514576/97829693-35765200-1ce4-11eb-93c7-8e1fa79826c0.png">
Production Environment
<img width="953" alt="Prod" src="https://user-images.githubusercontent.com/8514576/97829711-44f59b00-1ce4-11eb-8f8f-69bb14e95842.png">

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.18.2
NPM: 6.14.5 
Browsers: IE11

**Comment by webnoob** [comment]
It's possible that your internet security options change when on the VPN and in turn IE then has a custom level of security which disallows font downloads. There are various posts online about icons not appearing in IE11. My best advice is to check them out and work through them for a solution.

Also, notice in your second screenshot at the bottom, the total KB to be transferred is only 544KB whereas it's 4.83MB in the top screenshot. Something off there.

This isn't an issue with Quasar but it related to the network. We would love to help more but unfortunately we can't given the current workload and the low use of IE11.

If you do find a solution, please post back as it might help others facing the same.
