### ISSUE TITLE
QBtnToggle with a button content slot (through options) doesn't work right in combination with other QBtnToggle

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#7984]
**Describe the bug**
QBtnToggle with a button content slot (through options) doesn't work right in combination with other QBtnToggle

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/y6fs1qxr/

**To Reproduce**
1. Go to the fiddle provided
2. Click on the first button (left to right)
3. Then click on the second button
4. See that both light up as it should
5. Reload
6. Click on the last button (left to right)
7. Then click on the first button
8. See that the last button lights up and the first doesn't. The first button's model is not updated/no input event is emitted.

**Comment by metalsadman** [comment]
@wc-matteo ```js
<template :slot="1">
      aaa
    </template>
``` 
what do you plan this code do? since that's what causing your error.

**Comment by wc-matteo** [comment]
having something like a card inside. Still, whatever the case, the documentation and the api make it seem like it's something that is supported, right?

**Comment by metalsadman** [comment]
> having something like a card inside. Still, whatever the case, the documentation and the api make it seem like it's something that is supported, right?

it just takes a default slot, and no your code is not correct. should be `<template v-slot...>` see https://vuejs.org/v2/guide/components-slots.html.

**Comment by wc-matteo** [comment]
you're right! I was using the deprecated slot syntax. I updated the fiddle with the new one and now it's working: https://jsfiddle.net/7g81atv3/

**Comment by wc-matteo** [comment]
> it just takes a default slot
if I want to put something *inside* the button I have to use a named slot. The default slot puts something *besides* the button
