### ISSUE TITLE
Cannot use property rules AND error + error-message at the same time

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#7985]
**Describe the bug**
If you define both, it will always display the error-message string even if the rules are set and not the string defined in rules.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/medhyena/pen/WNxJPyd

**To Reproduce**
1. Go to https://codepen.io/medhyena/pen/WNxJPyd
2. See default error
3. Write 'test' in the input
4. No error
5. Write 'foobar' in the input
6. Same error as the beginning

**Expected behavior**
I would like the rules to display its own error. My point is, I would like to ask my user to input something that is mandatory, and then when he enters something, checks the rules (like it should be https:// instead of just a string) and display the error defined in the rules and not in the error-message field in case the user isn't following the said rules.

**Comment by rstoenescu** [comment]
Hi,

They are exclusive. `rules` prop already embeds the ability to tell if there is any error and also what error message to display. Use either internal validation (`rules`) or external validation (`error` + `error-message`).

**Comment by Medhyena** [comment]
But what if I want to have two different error messages for two different use case? (empty string error and not following the rule error)

**Comment by rstoenescu** [comment]
Adapt to how `rules` works. It can handle any scenario.
