### ISSUE TITLE
Notify does not work if used outside a .vue file

### ISSUE THREAD

**Issue by mahmoudsaeed** [quasarframework/quasar#7986]
**Describe the bug**
Notify does not work if used outside a `.vue` file such as `store/index.js`. Error message `"TypeError: Cannot read property 'add' of undefined"`.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/serene-fermi-lgzxb?file=/src/store/index.js

**To Reproduce**
1. Click on Notify
2. See error in the console

**Expected behavior**
Display the notification.

**Comment by rstoenescu** [comment]
You haven't installed the Notify plugin as instructed in the docs.
quasar.conf.js > framework > plugins: [ 'Notify' ]
