### ISSUE TITLE
How to redirect back to a certain path in quasar from cordova plugin

### ISSUE THREAD

**Issue by linjujp** [quasarframework/quasar#7987]
I am using a cordova plugin ( cordova-plugin-deeplinks ) in my application and I need to get back to a particular path in my quasar app for android platform. How to give the path in cordova, so that I can redirect to one of the page in the application?

**Comment by webnoob** [comment]
This doesn't sound like a question for us. If you have a question about how to appropriately link to an app - any app - then it should be for the developers of `cordova-plugin-deeplinks`. Quasar produces urls like any other application so to get your a page in that app you'd have your routes in the Quasar app setup to deliver content on that route. i.e `https://my.somesite.com/this/is/my/route`
