### ISSUE TITLE
1.14.3 QTime options handler is not called for 11/23 hour. 1.14.2 is working as expected

### ISSUE THREAD

**Issue by Sfinx** [quasarframework/quasar#7988]
**Describe the bug**

1.14.3 QTime options handler is not called for 11/23 hour. 1.14.2 is working as expected. The 11/23 hour just disabled

https://jsfiddle.net/Harbour/nc0que5a/

**To Reproduce**

Open fiddle, try select the time.

**Expected behavior**

All hours must be available for selection

**Comment by rstoenescu** [comment]
Hi,

This has already been reported and fixed. Will be available in the next Quasar version.
