### ISSUE TITLE
Platform detection on capacitor ios app

### ISSUE THREAD

**Issue by 4321ip** [quasarframework/quasar#7990]
Platform.is.desktop === true on WKWebView on iphone
because of this, horizontal scrolling tabs work incorrectly(like on desktop version (with scroll buttons))

**To Reproduce**
1. open wkWebView on iphone (use capacitor)
1. Go to https://quasar.dev/options/platform-detection#Example--Your-device
4. See you device Platform properties

**Expected behavior**
Platform.is.desktop === false
Platform.is.mobile === true

**Screenshots**
<img width="491" alt="Снимок экрана 2020-11-03 в 21 06 45" src="https://user-images.githubusercontent.com/11890535/98024210-09102200-1e19-11eb-85a5-1bb4570d8006.png">
<img width="486" alt="Снимок экрана 2020-11-03 в 21 16 52" src="https://user-images.githubusercontent.com/11890535/98024841-f3e7c300-1e19-11eb-894d-f0038970485c.png">

**Comment by rstoenescu** [comment]
Hi,

Is it a bug for you or you discovered the source of your problem?
