### ISSUE TITLE
QDate title/subtile "Day, Month DayNumber" change langage

### ISSUE THREAD

**Issue by oliviermorpa** [quasarframework/quasar#7991]
quasar version 1.14.3

QDate show the date in "Day, Month dayNumber".
when setting language to FR, we still have this "Day, month, dayNumber" but in France (and other country), we display:
"Day dayNumber Month"

see example:
Ven, Dec 4 should be Ven. 4 Dec
![qdate](https://user-images.githubusercontent.com/9378538/98078025-8cf5f880-1e71-11eb-8033-85f7e72a9a2f.JPG)

**Comment by oliviermorpa** [comment]
be crefull to change the , to a point

Ven**,** Dec 4 should be Ven**.** 4 Dec

the best maybe should be to parameter the display format ?

**Comment by webnoob** [comment]
We'll change this as we have done for other formats - i.e the chinese one. Will be done today / tomorrow.

**Comment by webnoob** [comment]
@oliviermorpa Hey! Sorry for the delay on this.

Is this format correct? 
![image](https://user-images.githubusercontent.com/10404747/98574384-c2ef0e80-22af-11eb-9d80-0b6d82b5bdc2.png)

**Comment by oliviermorpa** [comment]
yes that's the correct in France.
Thanks

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.4.
