### ISSUE TITLE
q-chat-message: clickable URL should be a thing

### ISSUE THREAD

**Issue by cappydh** [quasarframework/quasar#7992]
**Is your feature request related to a problem? Please describe.**
URLs are not clickable on chat messages. I had to use 3rd party sanitizer for sanitize message. After that decide if the url is valid and modifiy the message to be clickable right now.

**Describe the solution you'd like**
There should be a bool option for that.

`<q-chat-message
v-for="(message) in messages"
:key="message.id"
:text="[formatMessage(message)]"
/>`

I am using component like that. And my formatMessage function;

        formatMessage (str) {
            const self = this
            // Sanitize
            str = sanitizeHtml(str, {
                allowedTags: [],
                allowedAttributes: {}
            })
            let messageArray = str.split(' '),
                modifiedArray = [],

            messageArray.forEach((value) => {
                // Check if valid url
                if (self.urlPattern.test(value)) {
                    modifiedArray.push(`<my-custom-tag url='${value}'>${value}</my-custom-tag>`)
                } else {
                    modifiedArray.push(value)
                }
            })
            return modifiedArray.join(' ')
        }

I am using Electron. Right now my custom tag opens url through shell on a browser.

In my opinion it should wrap valid urls with a tag.

Thanks in advance.

**Comment by pdanpdan** [comment]
Hello. It's not the job of the generic component to change your content in this way - as seen from your example it's a lot of custom code you are using, and the performance cost for people not using this feature is high.
