### ISSUE TITLE
QDate Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by icksky** [quasarframework/quasar#7994]
**Describe the bug**
when `mask` is `YYYY-MM`(without day) and `value` is `2020-11`(`YYYY-MM` format), `QDate.js` will prompt `TypeError: Cannot convert undefined or null to object`.

**To Reproduce**
1. Go to [Live Demo](https://codepen.io/icksky/pen/GRqGPYL)
2. Open Console with `F12`
3. See error in the console `TypeError: Cannot convert undefined or null to object`

**Expected behavior**
No error

**Comment by webnoob** [comment]
I've added this to my list for review.

**Comment by leoelz** [comment]
Hi @icksky, the day is mandatory in the _date picker_, maybe you are looking for a _year-month picker_?

**Comment by icksky** [comment]
> Hi @icksky, the day is mandatory in the _date picker_, maybe you are looking for a _year-month picker_?

aha~ you are right. I try to wrap qdate to a year-month picker. I'll close this issue, sorry for disturbing you.

**Comment by leoelz** [comment]
Not disturbing at all, I was thinking that maybe a year-month picker can be a feature request or an extension...
