### ISSUE TITLE
QCircularProgress's foreground and background colors are inverted in Safari when reverse prop is true

### ISSUE THREAD

**Issue by pawee** [quasarframework/quasar#7997]
**Describe the bug**
QCircularProgress's foreground and background colors are inverted in Safari when reverse prop is true

**To Reproduce**
1. Go to https://quasar.dev/vue-components/circular-progress with Safari and Chrome
2. Scroll down to reverse example
3. Compare the colors

**Comment by hawkeye64** [comment]
![image](https://user-images.githubusercontent.com/10262924/100627158-e4a64900-32e3-11eb-8d58-9ec85820eae1.png)

**Comment by webnoob** [comment]
@pdanpdan We had a similar issue with another component a few months back, can you recall which one it was and the fix required?

**Comment by hawkeye64** [comment]
@webnoob Looks like it's because Safari is the only browser that doesn't allow negative numbers in the 3d-rotate. So, if the code is modified to always be positive (-90 === +270, for a circle) then it will work for all.
I believe I saw @pdanpdan working on a fix already.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.6.
