### ISSUE TITLE
Odd scrolling behaviour in Docs while in Safari

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#8000]
Hi q-team,
Just bumped into the issue with non-static positions for drawers and toolbars when the one scrolls through the page in Safari. The drawers and the content for some reason do not want to stay on their designated places.

To replicate:
Just head to the docs and try to scroll through the page:
https://quasar.dev/layout/drawer

![Screen Shot 2020-11-05 at 1 51 27 PM](https://user-images.githubusercontent.com/26779040/98183925-0ffc7900-1f6e-11eb-8511-8422507796d4.png)

Safari: Version 14.0
OS: MacOS 10.15.7 (Catalina)

Cheers!

**Comment by hawkeye64** [comment]
After investigation, I could replicate this using "command/ctrl + mouse wheel"
![image](https://user-images.githubusercontent.com/10262924/98838086-06a55d80-2401-11eb-87d0-7a038cbc2ff9.png)

**Comment by webnoob** [comment]
@pdanpdan Any chance you can weigh in on this?

**Comment by pdanpdan** [comment]
I don't think there is much that can be done on this - safari delays the scroll events when it needs to keep a high animation rate.
I'll assign it to me so I can remember about it, but don't expect miracles
