### ISSUE TITLE
Capacitor Splash Screen always being hidden by Quasar

### ISSUE THREAD

**Issue by seanaye** [quasarframework/quasar#8001]
**Describe the bug**
I want to manually hide the splash screen but it seems that quasar it always hiding it on mount of the root Vue instance.
I cannot get quasar to stop auto hiding the splash screen even after setting it in both capacitor.config.json and quasar.config.js. This occurs on both iOS and Android

capacitor.config.json
```
{
...
  "plugins": {
   ...
    "SplashScreen": {
      "launchAutoHide": false,
      "showSpinner": true,
      "androidSpinnerStyle": "small",
      "iosSpinnerStyle": "small",
      "spinnerColor": "#ffffff",
      "backgroundColor": "#21252dff",
      "splashFullScreen": true,
      "androidScaleType": "CENTER_CROP",
      "splashImmersive": false
    }
  }
}
```
I have run `npx cap copy` after setting as described in capacitor docs

quasar.conf.js
```
return {
  ...
  capacitor: {
    hideSplashscreen: false
  },
  framework: {
      config: {
        dark: true,
        capacitor: {
          hideSplashscreen: false
        }
  }
}
```
**Codepen/jsFiddle/Codesandbox (required)**
Not applicable since it only applies to capacitor apps on iOS/Android

**To Reproduce**
I am assuming this would reproduce the behaviour

1. use Quasar CLI and create capacitor app
2. Add my config from above
3. `npx cap copy`
4. `yarn dev -m capacitor -T (ios|android)`

This also occurs in production build version

**Expected behavior**
Capacitor splash screen should not hide until explicitly called by 

```ts
import { Plugins } from '@capacitor/core'

const { SplashScreen } = Plugins

SplashScreen.hide()
```

**Screenshots**

**Platform (please complete the following information):**
OS: Mac OS 10.15.5
Node: Node 14.15.0
NPM: n/a
Yarn: 1.22.10
Browsers: n/a
iOS: 13 and 14
Android: 10 and 11
Electron: n/a

**Comment by webnoob** [comment]
@nklayman Hey Noah, are you able to look into this one?

**Comment by IlCallo** [comment]
This is pretty strange as the options you set should avoid adding the code managing splashscreen entirely

https://github.com/quasarframework/quasar/blob/df9a2c8aedde8e9c36f46f24295a4dde021f206d/app/templates/entry/app.js#L29
https://github.com/quasarframework/quasar/blob/df9a2c8aedde8e9c36f46f24295a4dde021f206d/app/templates/entry/app.js#L61

Can you create a repro?

**Comment by seanaye** [comment]
Ill try to create a repo which produces this bug (original is closed source). You will need to clone the repo and run it on iOS or Android though.

**Comment by IlCallo** [comment]
I can run it on Android, not so easy on iOS

**Comment by seanaye** [comment]
I have removed and re-installed node_modules in my main project and updated quasar. It appears to be working as expected and the problem is resolved. Thanks for looking into this though.
