### ISSUE TITLE
QEditor - Add ability to set label for the editor

### ISSUE THREAD

**Issue by mspiderv** [quasarframework/quasar#8002]
**Is your feature request related to a problem? Please describe.**
Imagine you have a form which consist of multiple inputs, checboxes, radios etc. All these things can have a label. But if you want to use QEditor there is no `:label` option for that.

**Describe the solution you'd like**
I would like to do something like this: `<q-editor label="My WYSIWYG" v-model="..." />`

**Comment by hawkeye64** [comment]
@mspiderv Wrap your editor with QField. Give QFiled a label and also add "stack-label" property.
https://codepen.io/Hawkeye64/pen/dyXwVOW

**Comment by Tofandel** [comment]
The editor gets the q field style applied to it with QField, which sadly isn't desirable behavior (it's all primary basically)

A quick way is just 

```vue
<label>
  <div class="q-field__label pb-2">
    Description
  </div>
  <QEditor
    v-model="form.description"
  />
</label>
```

**Comment by mgnd** [comment]
To use `<q-field>` without applying its style to the editor, wrap the editor into `<template #control>`

```js    
    <q-field label="My Editor" stack-label>
      <template #control>
        <q-editor v-model="myContent" class="full-width" />
      </template>
    </q-field>
```
