### ISSUE TITLE
Responsive text alignment problems.

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#8003]
I'm trying to switch to Quasar from Bootstrap/Vue but I'm running into some problems.  Responsive text alignment (and responsive text size) was one of the best things about Bootstrap and this will keep me from making the switch.  

@rulrok found a solution that should work in the related case.  This really should be added.  In my situation, it's more about resizing the window, not mobile vs desktop.   The $q.screen.sizes might work for mobile vs desktop detection but that's not going to help me.  I need the alignment to change when the screen is resized which only happens via css breakpoints.  The referenced solution would cover both cases.

> Use dynamic class names based on $q.screen sizes. It's much cheaper than defining lots of classes.
> 
> _Originally posted by @pdanpdan in https://github.com/quasarframework/quasar/issues/6665#issuecomment-602753931_

**Comment by Daemach** [comment]
Following up, apparently $q.screen.sizes does work, but it's not pleasant to watch.  See here for a vue3 app using a bootstrap template vs quasar.  There may be more going on here, but more work needs to be done with responsive typography - both alignment and sizing. https://www.screencast.com/t/2y7wAZkoc2zm

**Comment by pdanpdan** [comment]
Hello. You just need to define your stayles as you see fit.
Please use the discord channel or the forum for help.
Thank you
