### ISSUE TITLE
Poor performance of Bottom Sheet on mobile.

### ISSUE THREAD

**Issue by Codebreaker101** [quasarframework/quasar#8006]
**Describe the bug**
I am experiencing low performance of bottom sheet plugin on a mobile phone. 
Compared to a pure dialog, it has a significant lag. On a computer browser (chrome) and in electron it works fine. I’ve tried it on 2 different phones with different browsers (chrome, brave, firefox, edge and opera), phone app (capacitor, dev and build), android studio emulator - all of which have had some level of lag whilest opening the bottomsheet - except, firefox. Surprisingly, Edge, of all browsers, was second in terms of lag, which is interesting since it is based on Chromium, as are Chrome and Brave.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/quasar-plugins/bottom-sheet#Usage

**To Reproduce**
1. Go to the docs 
2. Click on button to open bottom sheet on a mobile phone
3. Witness slow performance while opening bottom sheet

**Expected behavior**
For the animation to be as smooth like opening a dialog. 

**Platform (please complete the following information):**
OS: Android
Node: v12.18.4 + version that quasar.dev was compiled with. 
NPM: 6.14.7 
Yarn: 1.22.5
Browsers: Firefox Android 82.1.1, Opera Android 60.3.3004.55692, Edge Android 45.09.4.5083, Brave Android 1.16.74, Chrome Android 86.0.424.185, Brave Desktop  1.12.105 (84.0.4147.105)
iOS: N/A
Android:  8
Electron: 9.2.1

**Comment by Codebreaker101** [comment]
User dobbel at forums states that these versions didn't have performance issues. Will test when I can. 
```
“quasar”: “1.9.15”
“@quasar/app”: “1.7.1”
“@quasar/extras”: “1.6.4”
```

**Comment by webnoob** [comment]
Closing for now.
Will re-open if confirmed as being an issue on the latest versions.

**Comment by hawkeye64** [comment]
Just so everyone is aware, the BottomSheet(.js) plugin has not been modified in 2 years.
![image](https://user-images.githubusercontent.com/10262924/100669123-28b44080-331a-11eb-8031-a86711231f17.png)

**Comment by Codebreaker101** [comment]
Testing on the latest release with empty project and the lag persists. 

```
"dependencies": {
    "@quasar/extras": "^1.0.0",
    "core-js": "^3.6.5",
    "quasar": "^1.0.0"
  },
  "devDependencies": {
    "@quasar/app": "^2.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.1.2"
  },
```

Steps to reproduce: 
1. Initiate blank quasar project with everything staying default
2. Add capacitor support
3. Copy example of the [bottom-sheet documentation](https://quasar.dev/quasar-plugins/bottom-sheet#Usage) into `src/pages/Index.vue`
4. Build android app `quasar build -m capacitor -T android`
5. Install on mobile and open

Demonstration video of the lag: https://youtu.be/j4AtB65e0UQ
