### ISSUE TITLE
QTable: add 'visible' as attribute to column

### ISSUE THREAD

**Issue by edgar-koster** [quasarframework/quasar#8007]
**Situation**
A table column has the attribute `required`. When you don't define visible colums (`visibleColumns`) for a table then this attribute determines if it will or won't be shown in the table itself. This works perfectly. Now when you add a function to open a record, you can pass the row to that function. For example by adding `funcRowClick(props.row)"` to a row template. The row passed contains all the columns. However there are situations that you use a different column to open a record then the ID displayed. A situation could be that a user sees '1, 2,3,4' etc, but the actual opening will be on a `uuid` value, something you won't want to be visualized in the table. Now to use this, you would have to read the data object of the table based on the row passed to get additional information.

**Solution**
Add `visible` to the column definition as attribute. Then in the `table-column-selection.js` file adjust at least the line 32 to become:
`this.colList.filter(col => col.visible === true || this.visibleColumns.includes(col.name) === true)`. Because the column is still `required`, it will be in the row passed to a function, and you can also still use it in conditional formatting of templates for the rows etc.

**Addition info**
In my current project I have implemented something like this. I added some extra attributes to my column definitions and made the `visibleColumns` to filter the data from that with Lodash. I've added more attributes then `visible` like show checkbox or not with boolean, which dataset to use if it's an relational field. Sometime next year I'll try to make an extension for q-table for some of that.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.

**Comment by geekfahim** [comment]
Is there any new way implement to hide the column ?
