### ISSUE TITLE
QEditor - htmlTip definition seems to show as a menu item, not a tooltip

### ISSUE THREAD

**Issue by ldiebold** [quasarframework/quasar#8009]
**Describe the bug**
In the docs, under definitions -> **htmlTooltip** it says "HTML formatted text to be displayed within a tooltip on hover".
It looks like the htmlTooltip will only show as the description in a dropdown menu. Not when hovered (make more sense in the codepen)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ldiebold/pen/LYZJGWy

**To Reproduce**
1. Go to the codepen
2. Hover over the **B**
3. Click "dropdown" and notice the tooltip showing as a list item

**Expected behavior**
The html tooltip should show on hover (just like a normal **tooltip**

**Screenshots**
![image](https://user-images.githubusercontent.com/1305724/98360970-d9faea00-207e-11eb-8225-72676a43fb09.png)

**Platform (please complete the following information):**
OS: Ubuntu 20
Node: v14.15.0
NPM: 6.14.8
Yarn: 1.22.5
Browsers: Chrome
iOS: -
Android: -
Electron: -

**Comment by ldiebold** [comment]
I dug into the souce code, and it looks like this might be the intention (noticed that html tips are used to show, for example, larger font sizes)

Perhaps this just needs to be reflected in the docs?

**Comment by webnoob** [comment]
I can't actually find any reference to `htmlTip` in the docs. The functionality as it stands appears correct for me.

Where have you seen htmlTip in the docs?

**Comment by webnoob** [comment]
I actually think is this a bug and don't see a reason that htmlTip couldn't be used in the tooltip. @rstoenescu Care to weigh in?

Any reason _not_ to change the code to:

```js
if ((btn.htmlTip || btn.tip) && vm.$q.platform.is.desktop) {
    const Key = btn.key
      ? h('div', [h('small', `(CTRL + ${String.fromCharCode(btn.key)})`)])
      : null
    child.push(
      h(QTooltip, { props: { delay: 1000 } }, [
        h('div', { domProps: { innerHTML: btn.htmlTip || btn.tip } }),
        Key
      ])
    )
  }
```

**Comment by ldiebold** [comment]
@webnoob Would be happy to add this into the docs!

**Comment by hawkeye64** [comment]
@ldiebold No traction for over a year. Can this ticket be closed?

**Comment by ldiebold** [comment]
Yes, closed ☺️
