### ISSUE TITLE
Templates for v0.14 are the same than for 0.13

### ISSUE THREAD

**Issue by danielo515** [quasarframework/quasar#801]
Hello,

Not sure if this is a bug or not, but the templates generated using the 0.14 version of the starter kit are the same than 0.13
This makes adoption of 0.14 more harder because templates does not work out of the box as expected, and you are forced to go to the examples and see the source code to see what are you doing wrong.

All that I did was the getting started guide

> quasar init default#beta <folder name>

### Software version

Quasar: 0.14
OS: MacOsx
Node: 7
NPM: 3

Many thanks for this great framework
Regards

**Comment by rstoenescu** [comment]
`quasar init default#beta` means you are creating a default template on a folder called "default#beta"

The full syntax is `quasar init <template_name> <folder>`. If folder param is missing, then the default template (currently v0.13) is created with the indicated folder name. It's in docs.

So for v0.14 template go with specifying the folder too: `quasar init default#beta <folder_name>`

**Comment by danielo515** [comment]
Hello @rstoenescu , that is exactly what I did, I just forgot to include it in my issue. Have you tried it recently? Are you sure it works as you think

**Comment by XristMisyris** [comment]
I think @danielo515 is talking about the templates forlder that quasar cli uses to create new components.

**Comment by danielo515** [comment]
Exactly @XristMisyris, I am talking about that. Sorry for not being clear about it

**Comment by rstoenescu** [comment]
I can confirm component templates are updated to match v0.14 specifications on the default#beta starter kit. The only change required was in in templates/layout.vue.

If you are upgrading a v0.13 starter kit then also copy the default#beta templates folder.
