### ISSUE TITLE
QUploader's files' status and other properties can't be defined in the factory function

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#8011]
**Is your feature request related to a problem? Please describe.**
I am trying to use the QUploader, but since we've got a special way to upload the files, I can't rly use the QUploader API while I want to use all the design etc... So the user always see the "failed" status, I can hide it for now tho.

**Describe the solution you'd like**
My question is : can the factory function be made so we can change the status/data of the files and a "failed" status doesn't appear all the time while they are being pushed... I would like to make an "interactive" upload where the user can see the real state instead of having no idea when it will finish.

**Describe alternatives you've considered**
Hiding status and adding a spinner to "fake" the upload loading

**Comment by hawkeye64** [comment]
@Medhyena I am just curious, have you also looked into QFile as an alternative?

**Comment by Medhyena** [comment]
Absolutely not ! And it seems it may be something worth to look for ! But it is weird this uploader (QFile provides that functionality but not the Quploader...

**Comment by hawkeye64** [comment]
@Medhyena QFile was written, after QUploader, to handle form submissions. It could be that they have different functionality for a reason, or it just could have been simply overlooked.

**Comment by rstoenescu** [comment]
Hi @Medhyena,

I am a little confused about this ticket.

1. QUploader has slots for specific cases (like yours where you want to display a certain status in a specific way). Is there a case that it can't handle?
2. It's a bit unclear about "user always see the "failed" status".. what failed status? Any chance we can see some of your code?
3. For a custom upload process you can check out this section: https://quasar.dev/vue-components/uploader#Supporting-other-services ..and ultimately in the same place in docs there's a tip pointing to [this](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/uploader/uploader-xhr-mixin.js) (this is where you can also check how to set the status for a particular file (`this.__updateFile(file, 'uploading', file.size)` etc..):
  ```
  TIP
  For the default XHR implementation, check out source code.
  ```

If there is something that I am missing, pls feel free to comment. But I think no. 3 above should answer your question.
