### ISSUE TITLE
QTable: Scroll to position (with edge) does not work correctly 

### ISSUE THREAD

**Issue by pdwinkel** [quasarframework/quasar#8012]
**Describe the bug**
The .scrollTo(index, edge) does not work correctly for QTable with virtual-scroll

**Codepen/jsFiddle/Codesandbox (required)**
Works with QVirtualScroll: https://codepen.io/pdwinkel/pen/wvWEEVb?editors=1010
Does not work correctly with QTable: https://codepen.io/pdwinkel/pen/xxOaaaq?editors=1010

**To Reproduce**
1. Click on button to scroll to index 1200

**Expected behavior**
That record with index 1200 is positioned in the **center** of the table view.

**Platform (please complete the following information):**
OS: Linux
Node: 13.14
NPM: 6.14.4
Yarn: 1.22.5
Browsers: Chrome
Quasar: 1.14.3

**Comment by pdanpdan** [comment]
It was not a bug - it was not in the documentation that it has the edge parameter

**Comment by pdwinkel** [comment]
But it does not work in the second codepen link. It uses:
`$refs.virtualListRef.scrollTo(virtualListIndex, 'center-force')`
But e.g. if you Go to 1200, then record 1200 is at the bottom of the screen, not in the center.

**Comment by pdanpdan** [comment]
It's the scrollTo from QTable, and now it doesn't have the second param :)

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.14.7.

**Comment by pdwinkel** [comment]
Works great, thx!
