### ISSUE TITLE
Are there some samples that integrate the vue-styleguidist with Quasar to produce document for Quasar App Project?

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#8013]
**Is your feature request related to a problem? Please describe.**
Are there some samples that integrate the vue-styleguidist with Quasar to produce document for Quasar App Project?
for example, in the official vue-styleguidist web site: https://vue-styleguidist.github.io/docs/GettingStarted.html.
there are some samples how to integrate the vue-styleguidist with vuetify to produce the project document:
1. https://vue-styleguidist.github.io/Examples.html#vuecli3-vuetify-ie
2. https://vue-styleguidist.github.io/Examples.html#vuetify

**Describe the solution you'd like**
if developer want to use vue-styleguidist to maintain the document and is developing App with Quaser, so he/she prefer a sample how to  integrate the vue-styleguidist with Quaser

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by zouzg7829** [comment]
the vue-styleguidist need the project tell it how to load your code, so in general, create a styleguide.config.js file in the same directory that your package.json. and put some code such as following:
`module.exports = {
...
webpackConfig: require('./node_modules/@vue/cli-service/webpack.config'),`

so the question is how to find the webpack.config.js of the quasar app project?
Obviously, the file 'quasar.conf.js' isn't suitable for the case.

**Comment by fal-pasa** [comment]
I made this [repository](https://github.com/fal-pasa/Quasar-Vue-Styleguidist)
It isn't perfect but it can help you integrate

**Comment by hawkeye64** [comment]
This is a question better asked in forums of Discord channels.

**Comment by zouzg7829** [comment]
@fal-pasa The following component can't be parsed with your demo app configuration:
```
<template>
  <button :style="styles" @click="handleClick">
    <!-- @slot Use this slot to place the button content -->
    <slot></slot>
  </button>
</template>
<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'

@Component
export default class AppButton extends Vue {
  @Prop(Number)
  size?: number;

  /**
   * Sets the button font color
   */
  @Prop(String)
  color?: string;

  @Prop(String)
  /** Sets background color of the button
   * @since 1.2.0
   */
  background?: string;

  /** @deprecated Use color instead */
  @Prop(String)
  oldColor?: string;

  get styles () {
    return {
      'font-size': this.size,
      color: this.color,
      background: this.background
    }
  }

  handleClick (e: Event) {
    /** Triggered when button is clicked
     * @event click
     * @type {Event}
     */
    this.$emit('click', e)
    /** Event for Alligator's example
     * @event gator
     * @type {Event}
     */
    this.$emit('gator', e)
  }
}
</script>
```

**Comment by zouzg7829** [comment]
I have open a topic in forums channels of the quasar: [](https://forum.quasar-framework.org/topic/7186/are-there-some-samples-that-integrate-the-vue-styleguidist-with-quasar-to-produce-document-for-quasar-app-project)

**Comment by rstoenescu** [comment]
Pinging vue-styleguidist owner about support for Quasar would be nice. We are not obliged to create integrations ourselves for just everything out there. We already support too many.

**Comment by zouzg7829** [comment]
@rstoenescu I have created a feature request, see https://github.com/vue-styleguidist/vue-styleguidist/issues/1016
