### ISSUE TITLE
QDataTable with QPopupEdit: how to identify which cell it is

### ISSUE THREAD

**Issue by peonmodel** [quasarframework/quasar#8014]
When using QDataTable with QPopupEdit, and its event "@save -> function(value, initialValue)" & "@cancel", how can i know which cell is being edited?

Would it be possible to add the props as an params to the function? i.e. "@save -> function(value, initialValue, props)" where props is the props of the table & contain the (x,y) coordinates of the cell being edited

I tried to use a method that returns a function i.e.
```vue
<q-popup-edit
                  buttons
                  v-model="props.row.value"
                  @save="onTest(props)"
                />
```
```
export {
  methods: {
    onTest: (props) => (value, initialValue) => {}
}
}
```
but it doesnt work

**Comment by webnoob** [comment]
Please use the forums or discord for help requests, GitHub issues are for bugs or feature requests only.
