### ISSUE TITLE
Add Quasar to Cordova Tools

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#8015]
**Is your feature request related to a problem? Please describe.**
Quasar works perfectly well with Cordova and I was a bit surprised the framework wasn't listed on the [Cordova homepage](https://cordova.apache.org/).

**Describe the solution you'd like**
Add Quasar to the tools:
https://github.com/apache/cordova-docs/issues/1134#issuecomment-723649064

**Describe alternatives you've considered**
Adding Quasar myself, unfortunately I'm not able to do so.

**Additional context**
Maybe you devs have reasons not be listed. :)

**Comment by webnoob** [comment]
PR done, I'll take it from here: https://github.com/apache/cordova-docs/pull/1136

Thanks for raising this - will be nice to get a little more reach.
