### ISSUE TITLE
QTabPanels not swipeable with images

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#8016]
**Describe the bug**
All of the pages in my app are scrollable TabPanels, so the page itself is scrollable down, but you can swipe right/left to open the other page(s).

However, I noticed that whenever you try to swipe on an image it doesn't work.
QTabPanels `swipeable` feature is completely non-working with any kind of image.

Some of my pages are galleries of images, so once navigated to such a page, you're basically stuck on that page. : S

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/mesqueeb/pen/JjKmEag?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Ftab-panels

**To Reproduce**
1. Try to swipe the image

**Expected behavior**
That the panels are swappable

**Platform (please complete the following information):**
Chrome / Safari / Capacitor android / iOS

**Comment by pianopronto** [comment]
@mesqueeb Putting `draggable="false"` on the image works for me: 
```
<img src="" style="width: 100%; height: 400px" draggable="false" />
```

**Comment by webnoob** [comment]
Closing as adding ` draggable="false"` resolves this.
