### ISSUE TITLE
Skeleton loader doesn't work properly on safari

### ISSUE THREAD

**Issue by nurgi17** [quasarframework/quasar#8017]
**Describe the bug**
Hello, I'm used the skeleton loader on my web app it's work good on chrome and other browsers but not in safari browsers.

**Expected behavior**

**Screenshots**
On safari: (Also in iPhone works like this)
<img width="541" alt="Снимок экрана 2020-11-09 в 11 18 51" src="https://user-images.githubusercontent.com/28563673/98502969-a2a65c00-227d-11eb-98d4-854c3dcae8fd.png">

On chrome: 
<img width="509" alt="Снимок экрана 2020-11-09 в 11 20 00" src="https://user-images.githubusercontent.com/28563673/98502982-a89c3d00-227d-11eb-91f5-004860c6e3e9.png">

It should look like on chrome.
**Platform (please complete the following information):**
OS: macOS Catalina 10.15.5
Node: v12.13.0
NPM: 6.14.8
Browsers: Safari 13.1.1 (15609.2.9.1.2)
iOS: 14.0

**Comment by nurgi17** [comment]
I fixed that by change the transparent property on linear gradient to rgba
.q-skeleton--anim-wave:after {
  background: linear-gradient(90deg, transparent, rgba(255,255,255, 0.5), transparent);
}
.q-skeleton--anim-wave:after {
  background: linear-gradient(90deg, rgba(255,255,255, 0), rgba(255,255,255, 0.5), rgba(255,255,255, 0));
}

**Comment by rstoenescu** [comment]
Hi @nurgi17 ,

Don't really understand what's wrong. Can't tell from a static image. Also, is your problem happening on mobile safari or desktop safari? And why closing if it's really a problem instead of PRing the fix so the whole community can benefit? But we need to first confirm that there is a problem. I'm running Safari Version 14.0 (15610.1.28.1.9, 15610) and QSkeleton appears to be working as expected.

**Comment by nurgi17** [comment]
It's not a problem of quasarframework. It's problem of transparency(transparent property on linear gradient) on safari which doesn't show correctly.

**Comment by nurgi17** [comment]
> Hi @nurgi17 ,
> 
> 
> 
> Don't really understand what's wrong. Can't tell from a static image. Also, is your problem happening on mobile safari or desktop safari? And why closing if it's really a problem instead of PRing the fix so the whole community can benefit? But we need to first confirm that there is a problem. I'm running Safari Version 14.0 (15610.1.28.1.9, 15610) and QSkeleton appears to be working as expected.

It's not a problem of quasarframework. It's problem of transparency(transparent property on linear gradient) on safari which doesn't show correctly.

**Comment by nurgi17** [comment]
Could you please test on previous versions of safari on desktop and mobile.

**Comment by rstoenescu** [comment]
Ok, can confirm the issue for iOS. When dealing with linear gradients, iOS assumes "transparent" to be "black transparent". Changes all linear gradients to use rgba instead of "transparent".

Fix will be available in Quasar v1.14.4.
