### ISSUE TITLE
Dialog plugin - Provided props are no longer reactive

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#8021]
**Describe the bug**
Previously, when Dialog was invoked with [custom component](https://quasar.dev/quasar-plugins/dialog#Invoking-custom-component),  "Object like" forwarded props was automaticly reactive (maybe they were handled in Dialog state).

This is not a bug in fact (maybe it was an unwanted feature 🤣 ) but it was usefull !

**Codepen/jsFiddle/Codesandbox (required)**
1.14.x exemple https://codepen.io/daedalusdev/pen/GRqwJGz
1.13.2 exemple https://codepen.io/daedalusdev/pen/JjKeYVQ

**To Reproduce**
1. Created a dialog with a custom form component
2. Provide extra "Object like" forwarded props outgoing from a reactive state
3. Object is not reactive and won't update fields, input, etc

**Expected behavior**
In previous version (ex: quasar@1.13.x) reactivity was automaticly applied

**Platform (please complete the following information):**
OS: *
Node: *
NPM: *
Yarn: *
Browsers: *
iOS: *
Android: *
Electron: *

**Comment by rstoenescu** [comment]
Hi,

Use the `update()` method on the returned Object. This is its purpose. An example of using it is: https://quasar.dev/quasar-plugins/dialog#Progress

**Comment by DaedalusDev** [comment]
Hi,

i'm not sure to understand.

In my exemple, the model is provided has a props to a children component (like a form in fact). So, the model's keys are automaticly managed with `v-model`. How my child component is supposed to notify the parent ?

Thanks.

**Comment by ontwikkelfabriek** [comment]
If you define the 'value' attribute( that will be binded to the input) inside the custom component instead of $q.dialog , and pass a prop to your custom component it will work again as before:
https://codepen.io/ontwikkelfabriek/pen/OJXroXR
