### ISSUE TITLE
QParallax doesn't work properly on capacitor

### ISSUE THREAD

**Issue by greggameplayer** [quasarframework/quasar#8022]
# Describe the bug
Image in slot media of QParallax doesn't display on capacitor.

# Code of the component I made : 
[Click Here](https://codepen.io/greggameplayer/pen/BazGLpm)

# To Reproduce
Put an image inside the media slot of the QParallax and see the bug on capacitor and the expected behavior on the other platforms.

# Screenshots
**When in media slot of QParallax :**
![image](https://user-images.githubusercontent.com/33609333/98692370-54718580-236f-11eb-89b5-69194e48ba3f.png)

**When outside of media slot of QParallax :**
![image](https://user-images.githubusercontent.com/33609333/98692693-b16d3b80-236f-11eb-96fe-6dd923b7e21e.png)

# Platform (please complete the following information) :
OS: Windows 10 Insider
Node: v14.12.0
NPM: 6.14.8
Android: using Capacitor Pixel 3 API 30 on android studio

**Comment by hawkeye64** [comment]
@greggameplayer Please provide code so it can be tested. It would be too tedious to type it from a screenshot.

**Comment by greggameplayer** [comment]
@hawkeye64 I've gaved the component code above

**Comment by hawkeye64** [comment]
@greggameplayer That link has code, but shows nothing for me. Is it also supposed to work with desktop?
What I originally meant, is if this is a capacitor issue, then provide a repo (not codepen), so someone on staff can easily clone and test. Thanks.

**Comment by greggameplayer** [comment]
@hawkeye64 it's juste the code of the component you have to paste it inside a normal quasar project

**Comment by hawkeye64** [comment]
@greggameplayer Well, unfortunately, I am not going to be that much help. I reformatted my computer last month. I tried to install android studio and something is messed up. Hopefully, someone else can look into this while I try and figure out my issues.

**Comment by rstoenescu** [comment]
Hi,

QParallax works fine in Capacitor or any other environment. A common mistake is to have a custom scrolling div other than the page and not setting it with `scroll-target` prop. But not saying this would be it. I'm looking at your codepen and I can see that the image is outside of QParallax and the media slot is empty (?!?!) This is why it's important to create a working codepen/codesandbox/jsfiddle. It saves precious time for both you and us to get to the bottom of a possible bug.

```
<img src="../assets/homeimg.jpg" alt=""/>
    <q-parallax>
      <template v-slot:media>
      </template>
```
