### ISSUE TITLE
Quasar CLI does NOT work with Node 15.x and NPM 7.x

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#8025]
**Describe the bug**
I had installed latest Node and NPM, and when I tried to create a NEW Quasar app, I failed due to errors related to NP registry.

**To Reproduce**
Install Node 15.x, npm 7.x and try to create a new Quasar app.

**Expected behavior**

**Platform (please complete the following information):**
OS: Windows 10
Node: 15.x
NPM: 7.x
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
It cannot work because of webpack v4. Please use Node v12.
We cannot upgrade Node because this is would be a major breaking change. However, we will upgrade webpack to v5 for Quasar v2 and "@quasar/app" v3 (with Vue 3).

**Comment by BenHayat** [comment]
> 
> 
> It cannot work because of webpack v4. Please use Node v12.
> We cannot upgrade Node because this is would be a major breaking change. However, we will upgrade webpack to v5 for Quasar v2 and "@quasar/app" v3 (with Vue 3).

No problem. I just wanted to report it, so others won't use Node 15.x and npm 7.x.
