### ISSUE TITLE
windows build electron app error NODE_MODULE_VERSION mismatch

### ISSUE THREAD

**Issue by afx919** [quasarframework/quasar#8027]
**To Reproduce**
1. yarn add serialport
2. write a simple serialport code
3. quasar build -m electron
4. error: '
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 82. Please try re-compiling or re-installing
'

electron 10.1.5 use NODE_MODULE_VERSION 82
but [https://nodejs.org/en/download/releases/](https://nodejs.org/en/download/releases/) can't find NODE_MODULE_VERSION 82

fix doc:
[https://www.electronjs.org/docs/tutorial/using-native-node-modules]https://www.electronjs.org/docs/tutorial/using-native-node-modules

run command:
1、yarn add electron-rebuild --dev
2、.\node_modules\.bin\electron-rebuild
3、quasar dev -m electron
4、sucess, appcation running！ happy(*^▽^*)

but i use command quasar build -m electron, i can't run command (yarn add electron-rebuild --dev) in dist\electron\UnPackaged, quasar will clean /dist dir at compile time 

**so how to build electron app?**
Thanks!

**Platform (please complete the following information):**
OS: Windows10
Node:14.3.0
NPM:6.14.5
Yarn:1.22.10
Browsers:
iOS:
Android:
Electron:10.1.5

**Comment by hawkeye64** [comment]
@afx919 https://github.com/electron/electron/issues/25650

**Comment by Githubber2021** [comment]
I just did run into this issue. Does that mean this is fixed in a nightly build? At the same time, I didn't do any updates of electron, why did it just pop up on my machine?
