### ISSUE TITLE
auto expand matched node when filter

### ISSUE THREAD

**Issue by icksky** [quasarframework/quasar#8031]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
auto expand matched node when filter in locale mode (not remote)

**Describe alternatives you've considered**
expand all when filter, and just expand the root node when filter's value is empty. 

```typescript
function handleFilter (val: string) {
      if (tree.value) {
        if (val) {
          tree.value.expandAll()
        } else {
          expanded.value = [0]
        }
      }
}
```

**Additional context**
No.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
