### ISSUE TITLE
SSR problem when adding classes using classList.add()

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#8033]
**Describe the bug**
I was trying to build my project in SSG mode using the @freddy38510 's  [quasar-app-extension-ssg](https://github.com/freddy38510/quasar-app-extension-ssg) and i found that adding a class with `classList.add()` doesn't work as expected while in standard dev mode does.

**Repository**
Here you can fork my [repository](https://github.com/vandelpavel/Issue-classList.add-on-ssr).

**To Reproduce**
First try to run a simple `quasar dev` to see the expected behaviour then run `quasar dev -m ssr` or if you want to see the issue using ssg run `quasar ssg generate` and then `quasar ssg serve dist/ssg`.

You can find 2 examples. I found that the bug only happen when the image have a class on. You can find the behaviour both adding and without adding a start class (the content is not important).

**Expected behavior**
The image should be as the second example and the cut portion should follow the grey one on top.

**Platform (please complete the following information):**
OS: Windows 10
Node:v12.16.3.
Yarn:v1.21.1
Browsers: Chrome

**Additional context**
This is a bit strange and i can't give an explanation to that. I just found some hacks to fix it.

In the repository inside `src/components/waved-clip.vue` from row 51 you can see 3 chunks of code.
- The first is uncommented and is what is reproducing the bug.

- If you comment the first one and uncomment the second you can see that modifying directly the attributes does the job.

-If you uncomment the third instead you can see that also wrapping the same command with a set timeout makes it work.

**Comment by rstoenescu** [comment]
Hi,

This has nothing to do with Quasar but rather with the App Extension itself. So please refer to its owner.
