### ISSUE TITLE
QDate range type error

### ISSUE THREAD

**Issue by apple314159** [quasarframework/quasar#8038]
**Describe the bug**
After selection of a range, clicking on from date causes a type error

**To Reproduce**
1. Click on a start date
2. Click on a end date (this marks a range)
3. Click on the start date of step 1
4. See error on console

**Expected behavior**
No console errors

**Screenshots**
![QDate-console-error](https://user-images.githubusercontent.com/854164/99068385-6e32e880-257a-11eb-9fc5-966e2819b07e.png)

**Comment by pdanpdan** [comment]
Hello, this is related to your other issue #8037.
In fact this one is not related to quasar but to your code.

**Comment by apple314159** [comment]
Yes, this is with my code.
However, #8037 is a valid issue.
