### ISSUE TITLE
date.formatDate wrong result 

### ISSUE THREAD

**Issue by pikax** [quasarframework/quasar#8039]
**Describe the bug**
format date to `DD/MM/YYYY` when the initial date is `1234-12-12`  (YYYY-MM-DD), gives the result of `11/12/1234` instead of `12/12/1234`

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/serene-williams-84uc3?file=/src/App.vue

**To Reproduce**
1. Go to https://codesandbox.io/s/serene-williams-84uc3?file=/src/App.vue
2. Click on 'Click me'
3. See the output

**Expected behavior**
Output is expected  to 12/12/1234

**Screenshots**

![image](https://user-images.githubusercontent.com/4620458/99077873-5593f400-25b5-11eb-9d84-fdaa755313ed.png)

**Platform (please complete the following information):**
OS: CBS
Browsers: Chrome

**Additional context**

**Comment by pdanpdan** [comment]
Hello.

Do not use dates in dash separated formats - they'll be interpreted in your local (client/browser) timezone, so you might end up in the prev/next day.
See here:
- https://github.com/quasarframework/quasar/issues/3214#issuecomment-462308714
- https://forum.quasar-framework.org/topic/2888/date-utils-on-mobile-browsers/12
- https://github.com/felixge/node-dateformat/issues/73
- https://stackoverflow.com/a/4310986

**Comment by pikax** [comment]
Hello, makes sense, but can that be added to the docs, because the dash separated formats shows in the docs. 

![image](https://user-images.githubusercontent.com/4620458/99087248-757de480-25c2-11eb-86b9-f26f6506c3cb.png)
https://quasar.dev/quasar-utils/date-utils



A gotcha or warn would be great.

Thanks
