### ISSUE TITLE
[request/bug] align "disable" style across input components

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar#804]
### Software version

Quasar: 0.14
Browsers: Chrome

### What did you get as the error?

Setting "disable" attribute to "true" on a QDateTime and QInput results in different font colors.

Disabled text input:
<img width="375" alt="screen shot 2017-08-14 at 4 59 00 pm" src="https://user-images.githubusercontent.com/500715/29295547-331f782c-8112-11e7-86be-78b801c5ef83.png">

Disabled date time input:
<img width="374" alt="screen shot 2017-08-14 at 4 59 20 pm" src="https://user-images.githubusercontent.com/500715/29295550-3537bc3c-8112-11e7-9276-b74658dc9d2f.png">
 

### What were you expecting?

QInput appears to be correct, as it lightens/dims the disabled text field. I would like QDateTime to also have a lighter/gray text color when disabled. It appears that QSelect also fails to dim on disable state (I didn't check all the components).

### What steps did you take, to get the error?

Screenshotted the disabled components from the following pages in quasar-play:
http://beta.quasar-framework.org/components/input.html
http://beta.quasar-framework.org/components/datetime.html

**Comment by rstoenescu** [comment]
Hi, This has been fixed in v0.15, so closing this. Thanks for reporting!
