### ISSUE TITLE
QTime with QInput: Autoclose on input

### ISSUE THREAD

**Issue by 54mu3l** [quasarframework/quasar#8042]
I'm using QTime with QInput (like described here https://quasar.dev/vue-components/time#With-QInput).

I would like to have the popup proxy closed automatically as soon as the minute is selected.

There is a temporary fix I currently use:
```html
<q-popup-proxy
  ref="timeProxy"
  no-parent-event
  transition-show="scale"
  transition-hide="scale"
  >
  <q-time
    v-model="date"
    ref="qTime"
    :mask="displayFormat"
    @input="timeInput"
  />
</q-popup-proxy>
```

```javascript
timeInput() {
  this.$refs.timeProxy.hide();
},
```

The only problem I have is that `@input` is not fired if the user selects the same time.

I see to options to resolve this:

Option 1 would be:
Add a new feature to q-time to be auto-closed within a popup-proxy.

Option 2:
Make `@input` fire even if the user selects the same time.

In context of the whole application I really need to have the proxy closed as soon as the selection is done. So I would really appreciate if you could look into it.

Thank you!

**Comment by metalsadman** [comment]
that's just normal that input event won't be called since the model didn't change.

**Comment by 54mu3l** [comment]
@metalsadman Yes, I know. That's why my temporary fix only works if the user selects a different time. And that's why I need an auto-close-feature.

**Comment by rstoenescu** [comment]
Hi. Please use the slot which adds buttons. There's an example in docs for this.

**Comment by 54mu3l** [comment]
No. You have misunderstood me or I did not express myself well, but I do know the docs and all the examples.

I want to have it closed automatically as soon as the time is selected. **I don't want to make the user click any button.**

Reason behind this whole issue: better UX

**Comment by eqoram** [comment]
I have the same issue. Would be nice to have some kind of attribute to auto close when selecting an option. :)

**Comment by thijs** [comment]
Does the silence on this issue mean that it will not be addressed? Forcing a button click to close a popup like this is just plain bad UI. I thought the idea of quasar was to improve UI?

**Comment by 54mu3l** [comment]
There are multiple ongoing Discussions for this topic:
https://github.com/quasarframework/quasar/discussions/13874
https://github.com/quasarframework/quasar/discussions/12166
https://github.com/quasarframework/quasar/issues/13562
https://github.com/quasarframework/quasar/discussions/12187
https://github.com/quasarframework/quasar/discussions/13875
https://github.com/quasarframework/quasar/discussions/13873

**Comment by zsozark** [comment]
It's definitely not a _solution_ per se, since it's a MASSIVE hack, but it works for now and it saved hours for me, so i won't need to integrate another library into my project.

```
<q-popup-proxy
          v-model="timeVisible"
        ...
        >
          <q-time
            ref="timeRef"
            ...
```

```
function onChange(value: string) {
  const element = timeRef.value?.$el;
  const minSelected = element.querySelector(
    '.q-time__link.q-time__link--active:last-child'
  );
  if (minSelected) {
    timeVisible.value = false;
  }
}
```

Yeah, I know. I'm ashamed of myself, but difficult times require difficult decisions! ;)

**Comment by darkopetreski** [comment]
Did someone found a solution how to close the time picker automatically without a button?
