### ISSUE TITLE
Change default selected icon in QChip

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#8043]
**Is your feature request related to a problem? Please describe.**
I want customize the selected icon when I select a QChip

**Describe the solution you'd like**
A icon prop, as QBtn for example

**Describe alternatives you've considered**
Rebuilt the select system to use my own and add the icon in the default slot

**Comment by hawkeye64** [comment]
@Nisgrak I don't see what the problem is here exactly.

```html
<q-chip icon="event">Add to calendar</q-chip>
```
Just change the `icon` property.

**Comment by Nisgrak** [comment]
I explain wrong, sorry.

When I use `selected` prop its change the icon with a check, I want to change that check with a `selected-icon` prop.

https://codepen.io/Nisgrak/pen/JjRPVqE

**Comment by hawkeye64** [comment]
@Nisgrak I get it now. Thanks for the clarification.

**Comment by hawkeye64** [comment]
@Nisgrak The PR I did lets you change the selected icon to be different for each chip. If you want them all to be the same, you can change it already via `$q.iconMapFn` detailed here: https://quasar.dev/vue-components/icon#Custom-mapping

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.14.6
