### ISSUE TITLE
 Design inconsistency in arrow behavior in QSelect and QBtnDropdown

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#8048]
**Describe the bug**
If the menu is opened, the arrow rotates if the component is a QBtnDropdown but it doesn't if it is a QSelect.
Also the arrow for QSelect is grey and the QBtnDropdown arrow is black.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/smqdjkza/2/

**To Reproduce**
1. Click on the select to open menu => Arrow doesn't rotate
2. Click on the btn-dropdown to open menu => Arrow rotates

**Expected behavior**
For both components to rotate the arrow if the menu is opened/closed and to have the same color

**Comment by pdanpdan** [comment]
About the icon animation I agree, about the color not so much - they are different controls (button vs field).
Maybe @rstoenescu has a point on this.

**Comment by rstoenescu** [comment]
I agree about the color staying as is for QSelect.
Fix for the other thing will be available in Quasar v1.14.4.
