### ISSUE TITLE
Nested elements with QTooltips cause multiple tooltips to open when hovered over

### ISSUE THREAD

**Issue by richlanc** [quasarframework/quasar#8049]
**Describe the bug**
When you use nested HTML elements and both the parent and child have QTooltips, both tooltips open when you hover over the child element.

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/rl0/pen/PozgoXV

**To Reproduce**
1. Go to the code pen above
2. Hover the cursor over the "HOVER ME" button
3. You should see tools tips for both the inner button and the outer div

**Expected behavior**
In the example above, I would expect to only see the tool tip for the button when hovering over the button and only see the div tooltip when hovering not hover in the child element. 

**Screenshots**

**Platform (please complete the following information):**
OS: Ubuntu 18.04 LTS
Node: v12.19.0
NPM: 6.14.8
Yarn: 1.22.4
Browsers: 86.0.4240.198

**Additional context**
I think the expected behaviour is doable by moving from "onmouseenter/onmouseleave" to "onmouseover/onmouseout + stopPropagation" and using a timer for the "onmouseout" event handler,  so that the tooltip doesn't close when moving the cursor over child elements that don't have a QTooltip.

**Comment by hawkeye64** [comment]
@richlanc You need to work-around this in dev land. You need to be mindful of nesting when working with HTML. We can't stopPropogation on events the user might need.
