### ISSUE TITLE
[Request] Datetime component provides some property like "disabled dates" or "valid dates" for allow only a sub range of dates

### ISSUE THREAD

**Issue by MoacirSchmidt** [quasarframework/quasar#805]
The Datetime component could provide some property like "disabled dates" or "valid dates" for me to allow only a sub range of dates to select. "min" and "max" are not enough...unfortunately...

**Comment by spectrolite** [comment]
The ability to exclude specific dates (or weekdays btw), as well as including/excluding multiple ranges would indeed be very useful to the less trivial use cases (think e.g. event/flight/hotel booking apps).

**Comment by cedriccouret** [comment]
Hi, any news on this ?
The ability to disable/enable a set of dates or days of week would be much appreciated.

Thanks.

**Comment by stefanvanherwijnen** [comment]
I would also be interested in this feature. For some applications it would be useful to prevent the user from selecting e.g. holiday dates.

**Comment by thugic** [comment]
This is something that would be very useful, I tried to dig in the code but can't seem to find a way to do it on my own. 

I guess it would be enough to check at somepoint on rendering the component if the day is included in an array of "disabled days of week" (something like v-if="inDisabledDayOfWeek(day)") or if in disabled dates  array....

And then having the array disabledDaysOfWeek: [0,6]

And a method inDisabledDayOfWeek(day) --- if this.disableddaysofweek.includes((new Date(day).getDay()) ... or something like that ...

Am I digging in the right component ('QDatetimePicker.mat.vue') ????

Thanks...
/cc @rstoenescu

**Comment by rstoenescu** [comment]
@thugic Yes, that's the Material component.

Sorry for not participating in the discussion yet. Overloaded with work preparing the v0.15 release. Will join afterwards.

**Comment by jpgilchrist** [comment]
I have been working to rewrite our client side mobile application utilizing quasar. This is a critical component of a large set of our features. Is there any update/timeline WRT to this? 

I have a lot left to do, so I don't need this immediately, but I absolutely need it within 6 months.

**Comment by rstoenescu** [comment]
@jpgilchrist Rest assured this is planned for v1 which is set to be released this year.

**Comment by jpgilchrist** [comment]
@rstoenescu excellent! Oh, I should have noticed that you just added it to the milestone 5 days ago. :+1:

**Comment by rstoenescu** [comment]
Done for v1.0.

**Comment by mings1** [comment]
Hi @rstoenescu, may I know how to  disable specific dates?

**Comment by rstoenescu** [comment]
@mings1 this is a v1.0 feature. v0.17 does not has this.

**Comment by stefanvanherwijnen** [comment]
@mings1 
v1.0 is not released yet. I have no idea what the ETA of v1.0 is, but maybe the feature is integrated in a development branch somewhere. But considering the question, you will have to wait until v1.0 gets released.
