### ISSUE TITLE
Add UTC support to startOfDate / endOfDate 

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#8052]
### Problem description

Its not easy to build an UTC date for the start / end of a date. Usually, APIs take UTC timestamps for filters and date handling, so UTC support is very important. Several methods of the Date Utils library have a boolean parameter specifying if UTC is used instead of local time, but `startOfDate` / `endOfDate` don't. 
### Solution I'd like
I would like to make something like:
`newDate = date.endOfDate(newDate, 'day', true)`
and have in the newDate variable, a date pointing to UTC start of the `newDate`. Currently, what happens is that the returned date points to the end of date but in local time.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.14.8.
