### ISSUE TITLE
SlideInLeft transition has stutter in safari

### ISSUE THREAD

**Issue by jsfeldman** [quasarframework/quasar#806]
### Software version

Quasar: 0.14
OS: OSX/iOS
Node: quasar site version
NPM: quasar site version
Browsers: Safari 10.1.1
iOS: 10.3.3
Android: Not affected
Any other software related to your bug:

### What did you get as the error?
Using animate.css's SlideInLeft transition doesn't always work in safari. It will just appear instead, I believe the same issue occurs with SlideOutLeft. You can see it in this gif:
https://giphy.com/gifs/bug-transitions-quasar-framework-xT39DlUPs9QEHHeMdW

I tried recreating it on the animate.css site itself, but it doesn't seem to occur so I think it might be an issue with additional css added by quasar, but I'm not sure. I tried diving into it myself, but I'm not the best at troubleshooting css bugs.

### What were you expecting?
I was expecting a smooth SlideInLeft transition.

### What steps did you take, to get the error?
On safari I selected SlideInLeft on the quasar site and clicked toggle. It happens intermittently, but with some frequency so it shouldn't be too hard to trigger.

**Comment by rstoenescu** [comment]
No additional CSS from Quasar is added. Only animate.css...

**Comment by rstoenescu** [comment]
Like I mentioned earlier, there is nothing specific to Quasar, it's more of a Vue's `<transition>` component issue.

**Comment by jsfeldman** [comment]
Sorry, for not updating this. Initially, I thought there was some css from quasar that was being inherited and effecting things, but I think you're right. I was planning to check this by creating a jsfiddle with just vue and seeing if it also had the issue, but I got distracted. Thanks.
