### ISSUE TITLE
QUploader: Custom header "Pick Files" issue with icon right

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#8061]
**Describe the bug**
Adding a custom header with the "Pick Files" button having an `icon-right`, the trigger doesn't work when clicking the icon, only the text. It does however work when the icon is in the left side.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dwarfhq/pen/JjKVvxe

**To Reproduce**
1. Go to the Codepen
2. Click on "Pick Files" text part of the button
3. See that the files selection triggers
4. Cancel and click on the "Pick Files" icon part of the button
5. See that nothing happens

**Expected behavior**
Files selection should trigger regardless of the icon position.

**Platform (please complete the following information):**
Quasar: 1.14.3
Browsers: Chrome 86

**Comment by pdanpdan** [comment]
Please add `style="z-index: 1"` on `q-uploader-add-trigger` like here: https://codepen.io/pdanpdan/pen/zYBXMRq?editors=1010
The `icon-right` is rendered after the default slot in QBtn so it ends up above the trigger.

Either this or populate all the content inside the default slot (or only the icon)

**Comment by FrittenKeeZ** [comment]
@pdanpdan wouldn't it make sense then, to just add `z-index` by default to the trigger?

**Comment by pdanpdan** [comment]
We don't know how it is used, it might affect other cases.
But a note about it in the docs would be nice. If you have time would you try your hand with a PR for the docs?

**Comment by FrittenKeeZ** [comment]
@pdanpdan I'm not sure it's how you wanted it, but the PR is made :)

**Comment by pdanpdan** [comment]
I think it's pretty good. Maybe you should also put a more generic warning, like `if it's not working check if you have element rendered above it and change the zIndex`

**Comment by FrittenKeeZ** [comment]
@pdanpdan I've updated the docs and added an additional warning.

**Comment by pdanpdan** [comment]
Looks good, thank you.
