### ISSUE TITLE
Latest upgrades causes Quasar to fail

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#8063]
**Describe the bug**
```
quasar                  ^1.14.3  →  ^1.14.4     
vue-i18n                ^8.22.1  →  ^8.22.2     
@quasar/app              ^2.1.6  →   ^2.1.7     
eslint-config-standard  ^16.0.1  →  ^16.0.2
```

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. Upgrade to latest packages (see `ncu` above)
2. Run `$ quasar dev`
3. App does build, but doesn't render correctly

**Expected behavior**
Render correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/5028905/99566308-05f66380-29cd-11eb-8717-8acc5cd4014f.png)

The layout is missing

**Platform (please complete the following information):**
OS: Linux
Node: `v15.2.1`
NPM: `6.14.8`
Yarn: N/A
Browsers: Chrome, FireFox
iOS:
Android: 10
Electron:

**Additional context**
It seems JS is working, but maybe this is a CSS problem?

**Comment by rstoenescu** [comment]
Working on a fix.

**Comment by petr-panek** [comment]
I guess it's issue with new sass preprocessor.

**Comment by rstoenescu** [comment]
Please upgrade to Quasar v1.14.5 -- which is a correct repackage of 1.14.4.

**Comment by francoism90** [comment]
@rstoenescu Thanks for the fix!

However I keep getting the following warnings since the latest upgrade when running `$ quasar build`:
```
 App · ⚠️  2 warnings encountered:

Conflict: Multiple assets emit different content to the same filename js/.gz

Conflict: Multiple assets emit different content to the same filename js/.gz


 App · ⚠️  Build succeeded, but with 2 warnings. Check log above.
```

Downgrading to `@quasar/app": "^2.1.6` fixes the issue.

**Comment by rstoenescu** [comment]
Problem with compression-webpack-plugin. Temporarily reverted back to the old version of it. Please upgrade to q/app v2.1.8. And thanks for reporting this! @francoism90

**Comment by francoism90** [comment]
@rstoenescu Sorry for creating a second bug report, thanks for the fix again. :)

**Comment by rstoenescu** [comment]
No problem. Would be nice to take a look at https://donate.quasar.dev :)
