### ISSUE TITLE
@quasar/app v2.1.7 - generates empty .gz files when gzip is enabled

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#8064]
**Describe the bug**
Sorry for reporting another bug, it seems using `build: { gzip: true }` causes building to fail.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. Upgrade to v2.1.7
2. Enable `gzip` in `quasar.conf.js`
3. `$ quasar build`

**Expected behavior**
Generating correct gzip files.

**Screenshots**
![image](https://user-images.githubusercontent.com/5028905/99572405-ea8f5680-29d4-11eb-85d4-78ca08a4a82d.png)

**Platform (please complete the following information):**
OS: Linux
Node: `v15.2.1`
NPM: `6.14.8`
Yarn: N/A
Browsers: Chrome, FireFox
iOS:
Android: 10
Electron:

**Additional context**
Downgrading to v2.1.6 fixes the issue.

**Comment by rstoenescu** [comment]
Fixed in "@quasar/app" v2.1.8. Thanks for reporting.
It was a problem with compression-webpack-plugin. Temporarily reverted to its old version.
