### ISSUE TITLE
Module build failed - ./node_modules/sass-loader/dist/cjs.js

### ISSUE THREAD

**Issue by utopianknight** [quasarframework/quasar#8065]
**Bug description**
Quasar project was upgraded from
* quasar: 1.14.3 → 1.14.5
* @quasar/app: 2.1.6 → 2.1.8

After running `quasar dev` I get the following error:

```` 
ERROR  Failed to compile with 1 errors                                                                 0:00:00 AM
 error  in ./node_modules/office-ui-fabric-core/dist/sass/Fabric.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $string: ms-fadeIn  is not a string.
    ╷
177 │     $namelist: append($namelist, unquote($newname), 'comma');
    │                                  ^^^^^^^^^^^^^^^^^
    ╵
  node_modules\office-ui-fabric-core\dist\sass\mixins\_Animation.Mixins.MDL2.scss 177:34  ms-animation()
  node_modules\office-ui-fabric-core\dist\sass\mixins\_Animation.Mixins.MDL2.scss 205:5   @content
  node_modules\office-ui-fabric-core\dist\sass\mixins\_Directionality.Mixins.scss 11:5    ms-LTR()
  node_modules\office-ui-fabric-core\dist\sass\mixins\_Animation.Mixins.MDL2.scss 204:3   ms-slideRightIn10()
  node_modules\office-ui-fabric-core\dist\sass\_Animation.MDL2.scss 10:3                  @import
  node_modules\office-ui-fabric-core\dist\sass\_Animation.scss 58:9                       @import
  node_modules\office-ui-fabric-core\dist\sass\Fabric.scss 12:9                           root stylesheet

 @ ./node_modules/office-ui-fabric-core/dist/sass/Fabric.scss 4:14-261 14:3-18:5 15:22-269
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js
````

**Steps to reproduce the behavior**

1. Install [office-ui-fabric-core](https://www.npmjs.com/package/office-ui-fabric-core)
2. Add the following line in **quasar.conf.js**:

````JavaScript
module.exports = function (/* ctx */) {
  return {
    css: [
      'app.scss',
      '~office-ui-fabric-core/dist/sass/Fabric.scss' // Add this line
    ]
  }
}
````

3. Use any Fabric styles in your code.
4. Run `quasar dev`.

**Expected behavior**

* No errors

**Platform:**
* OS: Windows 10 19042.630
* Node: v14.15.0
* NPM: 7.0.11

**Additional context**

The `quasar dev` and `quasar dev -m electron` commands were running perfectly fine on the previously installed version of quasar (1.14.3).

The node_modules folder was removed and recreated. The same problem persists.

**Comment by rstoenescu** [comment]
Hi,

This is indeed a bug in office-ui-fabric-core's Sass which got uncovered with the latest Sass (the CLI uses the latest version of it now). Please report this issue to office-ui-fabric-core so they can solve.

Until then, you have two options:
1. Use `'~office-ui-fabric-core/dist/css/fabric.css'` instead of the sass equivalent.
2. Keep on using "@quasar/app" v2.1.6 until they fix the issue.
