### ISSUE TITLE
Using props in v-model mapping within globalDialog objects is broken in 1.14.0 onward

### ISSUE THREAD

**Issue by jemarlin** [quasarframework/quasar#8069]
**Describe the bug**
Using passed prop in v-model mapping results in model updating, but the 'value' reverting when field focus is last.  This is due to the removal of "Vue.observable(props);" within global-dialog.js

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**
v-model mapping update is reflected in the UI display

**Screenshots**
![image](https://user-images.githubusercontent.com/5114196/99688567-95425c00-2a4b-11eb-8565-002ae953af97.png)

**Platform (please complete the following information):**
OS: windows/chrome

**Additional context**
Adding Vue.observable(props); back in resolved the issue for us

**Comment by jemarlin** [comment]
Submitted PR 8070 which resolved the issue within our project

**Comment by rstoenescu** [comment]
Hi,

Please use the "update()" method. More info on another ticket: https://github.com/quasarframework/quasar/issues/8021
Vue.observable() adds a lot of overhead which we want to avoid.
