### ISSUE TITLE
Drag&Drop Outlook Mail (native app) into QUploader moves the mail in the trash section

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#8071]
**Describe the bug**
When you drag&drop an outlook mail from the outlook native app to the quploader. It moves the mail to the trash section in the outlook native app.

**Codepen/jsFiddle/Codesandbox (required)**
https://quasar.dev/vue-components/uploader#QUploader-API

**To Reproduce**
1. Go to https://quasar.dev/vue-components/uploader#QUploader-API
2. Drag & drop any mail from Outlook (native app) to one QUploader
3. It appears in the QUploader
4. But the mail has "disappeared" from my Outlook inbox and has been moved to the trash section

**Expected behavior**
The mail shouldn't be moved by the Quasar component...

**Comment by rstoenescu** [comment]
What is Quasar got to do with the behavior of Outlook?

**Comment by Medhyena** [comment]
Well, if you drag&drop anywhere else, it works just fine, but on the QUploader IN PARTICULAR, it does move the mail while it shouldn't. So it's obviously something from Quasar side and not Outlook... Same issue for the QFile btw, I just checked.

**Comment by Medhyena** [comment]
Nevermind this issue seems to appear only in the browser (I am using Chrome). I will check by my side on other browsers !
Sorry for that ^^

**Comment by pdanpdan** [comment]
Ok, I think something can be done according to this:
- https://answers.microsoft.com/en-us/msoffice/forum/all/drag-and-drop-works-however-deletes-email-can-we/865f60c3-7980-4465-8a19-4d60b0ae5aba?rtAction=1575537469456&page=2
- https://support.google.com/chrome/thread/14094827?hl=en

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.6.

**Comment by rstoenescu** [comment]
@Medhyena thanks for insisting on this
