### ISSUE TITLE
QInput 'shadow-text' misaligns when there is no label

### ISSUE THREAD

**Issue by ldiebold** [quasarframework/quasar#8077]
**Description**
When using `shadow-text` on a QInput **with no label** and **without autogrow**, the shadow text is misaligned.

**Codepen**
https://codepen.io/ldiebold/pen/BazeOZe?editors=101

**To Reproduce**
1. Open codepen
2. click on first input (shadow text is misaligned)
3. click on second input (shadow text **works**)
4. notice that the difference is the `expand` attribute

**Expected behavior**
Shadow text sits squarely in the input

**Screenshots**
![image](https://user-images.githubusercontent.com/1305724/99740913-08b79c80-2b24-11eb-88d6-b1f8334b0df6.png)

**Comment by pdanpdan** [comment]
the fix will go in Quasar v1.4.6
