### ISSUE TITLE
[enhancement] open event for fab actions

### ISSUE THREAD

**Issue by dkebler** [quasarframework/quasar#808]
fab action buttons should have open event so tooltips can be displayed on mobile devices by default.

Even better fab actions should always display tooltips by default when the media query indicated a touch or mobile device is being used.

At the very least the fab component should have a property to set any enclosed fab action buttons to display their tooltips by default.

See this post from forum http://forum.quasar-framework.org/topic/689/display-fab-action-tooltips-on-open

**Comment by rstoenescu** [comment]
Sounds good.

**Comment by kevingermain** [comment]
I would like this feature too!! :D

**Comment by rstoenescu** [comment]
I just re-read the request. QFab emits 'open'/'close' events already. You can hook into those and trigger the tooltips (call 'open' method on their refs). This needs to be done in userland and not in Quasar.

**Comment by kevingermain** [comment]
Hum, I've just tried, it works but I have to handle their absolute position because they overlay each other...

**Comment by rstoenescu** [comment]
@kevingermain put each tooltip inside your q-fab-actions

**Comment by kevingermain** [comment]
See in images: 
![screenshot at 23-13-34](https://user-images.githubusercontent.com/1334099/30401057-3dc28592-98d9-11e7-8796-a080bfa101c0.png)
![screenshot at 23-13-20](https://user-images.githubusercontent.com/1334099/30401059-3dcb4178-98d9-11e7-8159-f1265096ae42.png)
![screenshot at 23-13-09](https://user-images.githubusercontent.com/1334099/30401058-3dc59250-98d9-11e7-8cbe-185fa144490c.png)

**Comment by rstoenescu** [comment]
Just found a bug for the close() method in QFab. Please update to edge version or wait 1-2 days until v0.14.4 becomes official.

Anyway, the reason that tooltips are misplaced is that when the Fab is opened, the action buttons travel to their final position but Tooltips are opened before this happens. So, add a setTimeout for 300ms like this:

```js
    openFab () {
      setTimeout(() => {
        this.$refs.tooltip1.open()
        this.$refs.tooltip2.open()
      }, 300)
    },
    closeFab () {
      this.$refs.tooltip1.close()
      this.$refs.tooltip2.close()
    }
```
```html
<q-fab @open="openFab" @close="closeFab" .... >
```

**Comment by rstoenescu** [comment]
You can also use the Platform detection to decide if you want your Tooltips to get opened only on mobile.

**Comment by dkebler** [comment]
I filed this issue because of what @kevingermain also experienced (overlapping tool tips)  I knew fab has @open and @close and that I was I used that created the the issue. 

I will try again with 14.4 and if it is not resolved will report back here.

@rstoenescu, bit confused if I use platform detection will tips still open for other than mobile on hover?  Can you please point me to example of using platform detection for controlling tooltips display thx

**Comment by dkebler** [comment]
can't get this to work since my use case is not hard coded fab actions.   See below,

Would be great if this component has this enhancement and had prop for this behavior (automatically opened tooltips), dealt with timing issue and thus could be set on platform detection mobile.  What is involved?  If I have to make the code the below work any number of actions I might as well incorporate it into the q-fab component itself.  

```
<q-fixed-position corner="bottom-right" :offset="[18, 18]" >
<q-fab
  @open="openFab()"
  @close="closeFab()"
  color="primary"
  icon="fa-list"
  active-icon="fa-list-alt"
  direction="up"
>
  <q-fab-action v-for="view in views" :key="view._id" color="secondary" @click="filter(view)" icon="fa-list">
    <q-tooltip ref="fabviewtp" anchor="center left" self="center right" :offset="[0, 0]">{{ view.name }}</q-tooltip>
  </q-fab-action>
</q-fab>
</q-fixed-position>
```
```
    openFab () {
      setTimeout(() => {
        console.log('opening tool tips')
        this.$refs.fabviewtp.open()
      }, 300)
    },
    closeFab () {
      this.$refs.fabviewtp.close()
    }

```
TypeError: _this.$refs.fabviewtp.open is not a function[Learn More]
```

**Comment by dkebler** [comment]
Turns ouf fabviewtp is an array not single element so had to do this

So...any object to me adding this enhancement?  I see it needed for proper mobile UI,

```
    openFab () {
      setTimeout(() => {
        for (let index in this.$refs.fabviewtp) {
          this.$refs.fabviewtp[index].open()
        }
      }, 300)
    },
    closeFab () {
      for (let index in this.$refs.fabviewtp) {
        this.$refs.fabviewtp[index].close()
      }
    }
```

**Comment by MichaelJCole** [comment]
Pro-tip:  In the attached article there is some example code that uses $refs as an array.

[That only works if you are using a v-for](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements).  If you are declaring them in the template, you'll want to name and reference them individually:

``` jade
  // This is a jade <template>
  q-fab#fab(@show="showFab()" @hide="hideFab()" color="none" flat icon="img:statics/logo.svg" direction="down")
    q-fab-action(v-if="currentUser" @click="logout" icon="mail" color="amber" text-color="white")
      q-tooltip(ref="fabTipLogout" anchor="center left" self="center right" :offset="[0, 0]") Logout

    q-fab-action(v-if="currentUser" @click="goProfile" icon="stars" color="green" text-color="white")
      q-tooltip(ref="fabTipProfile" anchor="center left" self="center right" :offset="[0, 0]") Profile

    q-fab-action(v-if="!currentUser" @click="login" icon="power_settings_new" color="purple" text-color="white")
      q-tooltip(ref="fabTipLogin" anchor="center left" self="center right" :offset="[0, 0]") Login

```
```
  methods: {
    ...
    //https://github.com/quasarframework/quasar/issues/808
    showFab() {
      if (this.$q.platform.has.touch) {
        const r = this.$refs;
        setTimeout(() => {
          if (r.fabTipLogout) r.fabTipLogout.show();
          if (r.fabTipLogin) r.fabTipLogin.show();
          if (r.fabTipProfile) r.fabTipProfile.show();
        }, 350);
      }
    },
    hideFab() {
      if (this.$q.platform.has.touch) {
        const r = this.$refs;
        if (r.fabTipLogout) r.fabTipLogout.hide();
        if (r.fabTipLogin) r.fabTipLogin.hide();
        if (r.fabTipProfile) r.fabTipProfile.hide();
      }
    }
```

**Comment by MichaelJCole** [comment]
Hey, FYI that code doesn't work all of the time.  It only works 95% of the time, and when it doesn't it looks like this:

```
QTooltip.js?05c0:117 Uncaught TypeError: Cannot read property '$el' of undefined
    at VueComponent.updatePosition (QTooltip.js?05c0:117)
    at eval (QTooltip.js?05c0:88)
```

And maybe 0.5% of the time leaves artifacts.
