### ISSUE TITLE
QEditor: Pasting script and links

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#8081]
**Describe the bug**
The paste helping script described [here](https://quasar.dev/vue-components/editor#Plaintext-pasting), is missing handling for pasting of links in the link input dialog.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dwarfhq/pen/Bazegow

**To Reproduce**
1. Go to the Codepen
2. Click in the "Current" editor
3. Mark some text and click the link command
4. Try and paste a link into the input field
5. See that the original text marked in the editor is replaced with the paste text
6. Repeat step 3-4 in the "Adjusted" editor
7. See that the text is correctly pasted into the input field

**Expected behavior**
Pasting text into the editor should only be cleaned, if it's not into an input field like the link dialog.

**Screenshots**
![preview-full-links-wysiwyg](https://user-images.githubusercontent.com/1186125/99792684-baa49800-2b27-11eb-860f-0859932f790a.gif)

**Platform (please complete the following information):**
Quasar: 1.14.3

**Additional context**
Adding this code snippet to the top of the `pasteCapture` method fixes the issue:
```javascript
// Let inputs do their thing, so we don't break pasting of links.
if (evt.target.nodeName === 'INPUT') return
```

**Comment by rstoenescu** [comment]
Thanks for reporting and also improving docs!
