### ISSUE TITLE
[docs] Slide Item: this.finalize(reset) seems like wrong

### ISSUE THREAD

**Issue by outluch** [quasarframework/quasar#8085]
I tried to make slide item as in docs:

```
onLeft ({ reset }) {
      this.$q.notify('Left action triggered. Resetting in 1 second.')
      this.finalize(reset)
    },
```

But it says finalize is not a function. just calling reset seems to do the job.

**Comment by pdanpdan** [comment]
Hello, `finalize` is also there in the example.
