### ISSUE TITLE
Quasar not found vue-interactive-paycard

### ISSUE THREAD

**Issue by souzadavi** [quasarframework/quasar#8088]
I installed vue-interactive-paycard 
https://github.com/muhammederdem/vue-interactive-paycard

Into my quasar project, but when I try to run the project I'm getting this error:

`ERROR Failed to compile with 1 errors 10:16:18 PM

This dependency was not found:

boot/vue-interactive-paycard in ./.quasar/client-entry.js
To install it, you can run: npm install --save boot/vue-interactive-paycard
`

FULL LOG ERROR:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/souzadavi/.nvm/versions/node/v14.7.0/bin/node',
1 verbose cli   '/home/souzadavi/.nvm/versions/node/v14.7.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'boot/vue-interactive-paycard'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.7.0
4 verbose npm-session e006383eca4ea04b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:boot/vue-interactive-paycard Error while executing:
7 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/boot/vue-interactive-paycard.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData git@github.com: Permission denied (publickey).
7 silly fetchPackageMetaData fatal: Could not read from remote repository.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Please make sure you have the correct access rights
7 silly fetchPackageMetaData and the repository exists.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 4124ms
10 verbose stack Error: exited with error code: 128
10 verbose stack     at ChildProcess.<anonymous> (/home/souzadavi/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
10 verbose stack     at ChildProcess.emit (events.js:314:20)
10 verbose stack     at maybeClose (internal/child_process.js:1051:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
11 verbose cwd /home/souzadavi/ownCloud/pessoal/linknacional/pagamento/vindi/vindi2
12 verbose Linux 5.4.0-54-generic
13 verbose argv "/home/souzadavi/.nvm/versions/node/v14.7.0/bin/node" "/home/souzadavi/.nvm/versions/node/v14.7.0/bin/npm" "install" "--save" "boot/vue-interactive-paycard"
14 verbose node v14.7.0
15 verbose npm  v6.14.8
16 error Error while executing:
16 error /usr/bin/git ls-remote -h -t ssh://git@github.com/boot/vue-interactive-paycard.git
16 error
16 error git@github.com: Permission denied (publickey).
16 error fatal: Could not read from remote repository.
16 error
16 error Please make sure you have the correct access rights
16 error and the repository exists.
16 error
16 error exited with error code: 128
17 verbose exit [ 1, true ]
~                              `

Please any info will be appreciated, thanks

**Comment by francoism90** [comment]
This isn't a bug, did you import the project correctly in your boot file?

https://quasar.dev/quasar-cli/boot-files

**Comment by pdanpdan** [comment]
Please use the discord channel or the forum for help requests.
