### ISSUE TITLE
[Request] Allow time selection to be restricted to a step value.

### ISSUE THREAD

**Issue by Phunky** [quasarframework/quasar#809]
It would be great if we could define a minute-step prop on the datetime component to allow us to limit the selected value.

For example if minute-step="5" then the selection would only allow you to select multiples of 5 or if it minute-step="15" you could only select every quarter hour.

**Comment by rstoenescu** [comment]
Sounds good.

**Comment by rstoenescu** [comment]
Done for future v1.0.
