### ISSUE TITLE
Morph animations not showing in q-dialog

### ISSUE THREAD

**Issue by gaw89** [quasarframework/quasar#8091]
**Describe the bug**
If the `Morph` utility (awesome feature, by the way!!) is used in a `q-dialog` that has an opaque background (e.g. `q-dialog` that contains a `q-card`), the animating element is hidden behind its parent.  

**Codepen/jsFiddle/Codesandbox (required)**
- Transitions hidden: https://codepen.io/gaw89/pen/WNxVOjX?editors=101
- Transitions showing (added a z-index to each of the morph group elements): https://codepen.io/gaw89/pen/NWrQvWL?editors=101

**To Reproduce**
1. Click through the morph sequence in the Codepen. (first link)
2. To fix the behavior, add `z-index: 10000 !important` to the style of each element in the morph group. (second link)

**Expected behavior**
I would expect to see the animated transition.

**Platform (please complete the following information):**
OS: Windows 10
Browsers: Tested in Chrome, Edge, and Firefox

**Additional context**
I would propose two possible solutions to this issue:

1. Update the docs with a warning that, if used within a dialog, the `Morph` must include a high `z-index` in the style for every element in the morph group.

2. I'm happy to work on a PR for this.  I believe it would be as simple as adding a `z-index` somewhere in [here](https://github.com/quasarframework/quasar/blob/eee79c419fc9e8f7175af1887680e3945764b246/ui/src/utils/morph.js#L314).

**Comment by gaw89** [comment]
@pdanpdan, your solution is **way** smarter than mine!

**Comment by pdanpdan** [comment]
Now it's really fixed, i made some enhancements.
It depends on the zIndex of positioned elements.

**Comment by gaw89** [comment]
Right, that makes perfect sense.  Thanks again!

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.6

**Comment by gaw89** [comment]
@rstoenescu, you guys rock!
