### ISSUE TITLE
Why is the formatting different when using rules on q-input?

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#8096]
**Describe the bug**
When `q-input` is used the formatting is different when using the `rules` attribute. 

**To reproduce**

[Codepen reproduction](https://codepen.io/DarkLite1/pen/GRqVaPK).:
- Check the box "I don't know my driver ID"
- Notice the spacing changes because one `q-input` has `rules` and the other does not
From:
![image](https://user-images.githubusercontent.com/10828570/100080351-04ea8980-2e46-11eb-992a-fc89a2958675.png)
To:
![image](https://user-images.githubusercontent.com/10828570/100080391-12a00f00-2e46-11eb-86e9-e73bab4aaa1f.png)

I hope this is not by design as I thought the rules would not impact how the content is displayed on screen. I mean, when there is no error message to display yet it should not consume empty white space.

**Comment by pdanpdan** [comment]
Hello.
Check `hide-bottom-space` in the API card for QField or QInput.
An please use the dicord channel or the forum for help requests.

**Comment by DarkLite1** [comment]
I'm sorry, I really thought this was a bug. Thanks for the help.
