### ISSUE TITLE
optgroup for q-select component

### ISSUE THREAD

**Issue by rulrok** [quasarframework/quasar#8098]
**Describe the solution you'd like**
I'd like to be able to create `<optgroup>`s for `q-select` component to mimic this native design.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

**Describe alternatives you've considered**
Using an scoped slot with `q-list/q-item` to render it somehow.

**Additional context**
So, I thought that besides `:options` the component could accept a new `:optgroups` property as :

```
{
  "groupname": { ...'regular ":options" object'... },
  "group 2" : { ...'another ":options" object'... }
}
```

**Comment by hawkeye64** [comment]
@rulrok I know quasar currently does not support option groups, but you can get creative. Would something like this work? https://codepen.io/Hawkeye64/pen/xxbXajq

**Comment by pdanpdan** [comment]
And a version for multiple selection: https://codepen.io/pdanpdan/pen/WNGerrK?editors=1010
I'll try to think if there is some way to make it work with the scope properties.

**Comment by pdanpdan** [comment]
Sorry, I thought about this and it has too many edge cases for the general implementation.
If someone want to add an example to the docs on how this is done in userland it would help.

**Comment by rulrok** [comment]
No problem, I ended up not needing this for now in the end, but If I come across this use case again I'll try to think about a implementation solution. :+1:
