### ISSUE TITLE
[Request] initial sorting in DataTable

### ISSUE THREAD

**Issue by llin55** [quasarframework/quasar#810]
Please add a possibility to set an initial sorting in DataTable for a specified column (asc/desc)

**Comment by rstoenescu** [comment]
DataTable revamp is in progress for v0.15. It will include this. Thanks for your patience.

**Comment by LarryEitel** [comment]
Curious if when you enable setting initial sort column/direction that you could expose the column key/name and direction? This would include some kind of a catchable sort ‘changed’ event. I am persisting filters/search parameters as URL Query Parameters. It would be awesome to include/update sort parameters as well. Thank you. :)

**Comment by rstoenescu** [comment]
Yes, you'll be able to do that. Many new possibilites open up with the revamp.

**Comment by ssuess** [comment]
Is there an ETA for this (even a rough one)? I really (really) need the new data table functionality, but if the component isn't coming for months I will look for another solution. I have already donated money to the project, but if a little more would help move this along, I am happy to donate again.

**Comment by rstoenescu** [comment]
Rough ETA: 1 month. v0.15 coming along with other components and need to ensure quality. Otherwise the datatable would be ready in 2-3 days. Thanks for your patience.

**Comment by ssuess** [comment]
Thanks @rstoenescu, this info helps a lot with my own app planning.

**Comment by rstoenescu** [comment]
Closing as code is ready in v0.15 datatable revamp.

**Comment by NicksonYap** [comment]
Implemented here: https://quasar-framework.org/components/datatable.html#Pagination

**Comment by devidw** [comment]
Since the last shared docs link in the thread does land on the front page of the docs, here is the current one: https://quasar.dev/vue-components/table#pagination
