### ISSUE TITLE
Ability to change 302 to 301 status

### ISSUE THREAD

**Issue by p1pchenk0** [quasarframework/quasar#8107]
**Is your feature request related to a problem? Please describe.**
For SEO purposes in my current project we need to have 301 status redirect instead of 302, which is set by default while calling `redirect(...)` method in `preFetch` hook. Moreover, for some cases we may receive status code from internal api (it may be 301 or 302 depending on code from response), so it is necessary for us to be able to pass this code on our own.

**Describe the solution you'd like**
As a solution we may have second optional parameter for status: `redirect(redirectUrl, 301)`

**Comment by p1pchenk0** [comment]
we can do it in this function:
```javascript
function redirectBrowser (url, router, reject) {
  const normalized = Object(url) === url
    ? router.resolve(url).route.fullPath
    : url

  reject({ url: normalized })
}
```
I suppose, we can pass it as forth parameter:
```javascript
function redirectBrowser (url, router, reject, status) {
  const normalized = Object(url) === url
    ? router.resolve(url).route.fullPath
    : url

  reject({ url: normalized, status })
}
```
and then change redirect itself:
```javascript
const redirect = (url, status) => {
      hasRedirected = true
      redirectBrowser(url, router, reject, status)
    }
```

**Comment by p1pchenk0** [comment]
I will prepare PR so you could check my suggestion (I've tested it and it worked as expected)

**Comment by p1pchenk0** [comment]
https://github.com/quasarframework/quasar/pull/8109

**Comment by p1pchenk0** [comment]
closing since it was implemented in v.2.1.9

**Comment by rstoenescu** [comment]
And thank you for contributing with the PR!
