### ISSUE TITLE
Update deprecated dependencies

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#8108]
**Describe the bug**
I'm creating a new quasar project, and npm is warning about deprecated dependencies, how to upgrade it's?

**Expected behavior**
None warn about deprecated dependencias

**Screenshots**
![image](https://user-images.githubusercontent.com/24510745/100363149-1a44ec80-2fdb-11eb-85bf-8950dac16b3f.png)

![image](https://user-images.githubusercontent.com/24510745/100363157-1dd87380-2fdb-11eb-953a-b0b376b530e5.png)

**Additional context**

**Comment by pdanpdan** [comment]
The deprecated packages are dependencies of dependencies of are required on that version.

**Comment by hawkeye64** [comment]
@maico910 In the meantime, while we wait for upstream packages to get updated, don't use a Node version higher than 12+.

**Comment by maico910** [comment]
@hawkeye64 thanks for the information! I didn't know about this.
