### ISSUE TITLE
[Request] Add window.resize to Quasar Events

### ISSUE THREAD

**Issue by daniel-shuy** [quasarframework/quasar#811]
Currently, using `window.addEventListener` and `window.removeEventListener` feels very un-Quasar-like.

It would be nice if Quasar automatically emits a `resize` event so that we could simply do something like:
```javascript
import { Events } from 'quasar'

export default {
  // ...
  methods: {
    resize () {
      // ...
    }
  },
  mounted () {
    Events.$on('resize', this.resize)
  },
  beforeDestroy () {
    Events.$off('resize', this.resize)
  }
}
```

**Comment by rstoenescu** [comment]
Hi,

There are observables Quasar components.
Yours is at http://beta.quasar-framework.org/components/window-resize-observable.html

-Razvan

**Comment by daniel-shuy** [comment]
Oh, its a 0.14 feature, no wonder I didn't notice it, cool!

**Comment by manelclos** [comment]
Link is broken, could not find the resize observable in beta3

**Comment by rstoenescu** [comment]
There's no WindowResizeObservable in 1.0 because you don't need it anymore. Directly use `$q.screen.width/height`.
