### ISSUE TITLE
Typescript declaration missing ssrUpdate function

### ISSUE THREAD

**Issue by Trinovantes** [quasarframework/quasar#8112]
**Describe the bug**
Quasar object is missing `ssrUpdate` function definition

**To Reproduce**
```ts
import Vue from 'vue'
import App from '@components/App.vue'
import Quasar from 'quasar'

Vue.use(Quasar)

export function createApp(ssrContext?: { req: Request, res: Response }): App {
    const router = createRouter()
    const store = createStore()

    const appConfig: AppConfig = {
        router: router,
        store: store,
    }

    // Unsafe call of an any typed value
    Quasar.ssrUpdate({
        app: appConfig,
        ssr: ssrContext,
    })

    return new App(appConfig)
}
```

**Expected behavior**
No Typescript errors

**Additional context**
Here's a possible solution but I'm not sure if you want a PR with all of this in the same place
```diff
+ import { Request, Response } from 'express'
+ import VueRouter from 'vue-router'
+ import { Store } from 'vuex'
+ 
+ export type QSSRContext = {
+     req: Request,
+     res: Response,
+ }
+ 
+ export type QSSRArgs = {
+     app: {
+         router: VueRouter
+         store: Store<unknown>
+     },
+     ssr?: QSSRContext
+ }
+ 
+ interface QuasarPlugin extends PluginObject<Partial<QuasarPluginOptions>> {
+     ssrUpdate: (args: QSSRArgs) => void,
+ }

- export const Quasar: PluginObject<Partial<QuasarPluginOptions>>
+ export const Quasar: QuasarPlugin
export default Quasar
```

**Comment by IlCallo** [comment]
`ssrUpdate` doesn't has a type as it's internal API, and the codebase is written in TS, so we only export types for the public API.
Also, `ssrUpdate` is only used on the Vue CLI plugin, but we cannot generate different types for Vue CLI and Quasar CLI version.

What's the use case for this anyway?

**Comment by Trinovantes** [comment]
I want to use Quasar components in a SSR application as a standalone Vue plugin without using other CLI programs*. However the problem I'm running into is `this.$q` is `undefined` in Quasar components when trying to render on the server side without calling `ssrUpdate` first. 

*I'm not using Vue/Quasar CLI because I need more flexibility in customizing the build process

**Comment by IlCallo** [comment]
I see, this is a very rare edge case. I prefer not to expose this types as, as said previously, we consider it an internal API subject to change.

I'd suggest to you to just disable that linting error in this case
