### ISSUE TITLE
template src not load css components

### ISSUE THREAD

**Issue by gcastellan0s** [quasarframework/quasar#8120]
When you import template html with:

![code](https://user-images.githubusercontent.com/4236722/100523512-9aec2000-3176-11eb-83de-476a57564379.png)

the styles of quasar components not loaded correctly

![Screen Shot 2020-11-28 at 12 35 31](https://user-images.githubusercontent.com/4236722/100523473-60828300-3176-11eb-8241-dec46518f492.png)
![Screen Shot 2020-11-28 at 12 35 51](https://user-images.githubusercontent.com/4236722/100523475-61b3b000-3176-11eb-8bde-6e3d6b2c5626.png)

**Comment by pdanpdan** [comment]
When you import it where? You don't provide any kind of details of what you are doing

**Comment by gcastellan0s** [comment]
In this case the code is loaded but without css
![code](https://user-images.githubusercontent.com/4236722/100523930-abea6080-3179-11eb-95a9-870dd8170f21.png)
![code2](https://user-images.githubusercontent.com/4236722/100523933-b0af1480-3179-11eb-80d1-f99e31812b37.png)

**Comment by pdanpdan** [comment]
Please use the forum or the discord channel for help requests.
Also next time you open an issue please fill the issue template.
