### ISSUE TITLE
ESLint error PWA at start

### ISSUE THREAD

**Issue by Zerotask** [quasarframework/quasar#8121]
**Describe the bug**
I'm getting an error by ESLint (using it with airbnb style) after I created a fresh project as described below.
I can simply fix it by saving the file and VS Code applies the proper style, but it would be good if it's already valid code after the creation.

**To Reproduce**
1. `quasar create quasar-app`
2. `cd quasar-app`
3. `quasar mode add pwa`
4. `quasar dev -m pwa`

**Expected behavior**
The app starts without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/20150243/100524902-4ff4fb80-31bc-11eb-9c74-84de3923f6a9.png)

**Platform (please complete the following information):**
OS: Windows 10 64 bit
Node: 15.3.0
NPM: 7.0.14

**Comment by hawkeye64** [comment]
The default style is "standard", so the code is written for that. If you change the style, you may need to fix the issues, based on that style. Since it's very easy formatting issues, just add to the scripts section of package.json:
```
"lint-fix": "eslint --ext .js,.vue src --fix",
```
and run it `yarn lint-fix`
