### ISSUE TITLE
Error creating a new project with electron

### ISSUE THREAD

**Issue by Zerotask** [quasarframework/quasar#8122]
**Describe the bug**
I can't install quasar with electron. It seems like the installation process is never ending; probably a npm bug.
I aborted the installation process after 20 minutes.

**To Reproduce**
1. `quasar create quasar-app`
2. `cd quasar-app`
3. `quasar dev -m electron`

**Expected behavior**
Installation without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/20150243/100525519-cba57700-31c1-11eb-8928-234ffcc209b1.png)

**Platform (please complete the following information):**
OS: Windows 10 64 bit
Node: 15.3.0
NPM: 7.0.14

**Additional context**

**Comment by pdanpdan** [comment]
Use yarn on Windows, please.
