### ISSUE TITLE
lang(uyghur): Partially written in Chinese

### ISSUE THREAD

**Issue by Blfrg** [quasarframework/quasar#8123]
**Describe the bug**
Thank you @Ansar-786 for: "add uyghur language pack" #7832

However, I noticed the ['Editor' section](https://github.com/quasarframework/quasar/blob/dev/ui/lang/ug.js#L49) (lines 50-92) is all in Chinese.
Was this on purpose or accidental oversight?

**Codepen/jsFiddle/Codesandbox (required)**
Can be seen in the ['Editor' section](https://github.com/quasarframework/quasar/blob/dev/ui/lang/ug.js#L49) of the Uyghur language file.

**To Reproduce**
Can be seen in the ['Editor' section](https://github.com/quasarframework/quasar/blob/dev/ui/lang/ug.js#L49) of the Uyghur language file.

**Expected behavior**
All values to be in Uyghur or fallback to English (or Chinese in this case) but only when no value exists in the language.

**Screenshots**
N/A

**Platform (please complete the following information):**
OS: Linux(5.4.0-54-generic) - linux/x64 [Ubuntu 20.04.1 LTS (Focal Fossa)]
Node: 12.20.0
NPM: 6.14.9
Yarn: 1.22.10
Browsers: Chrome, Firefox
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**

Below is a Google translation for the 'Editor' section:

```json5
  editor: {
    url: 'URL',
    bold: 'Bold',
    italic: 'ئىتالىيان',
    strikethrough: 'Strikethrough',
    underline: 'ئاستى سىزىق',
    unorderedList: 'تەرتىپسىز تىزىملىك',
    orderedList: 'زاكاز تىزىملىكى',
    subscript: 'مۇشتەرى',
    superscript: 'Superscript',
    hyperlink: 'Hyperlink',
    toggleFullscreen: 'تولۇق ئېكراننى ئالماشتۇرۇڭ',
    quote: 'نەقىل',
    left: 'سول تەڭگە',
    center: 'Center align',
    right: 'ئوڭ توغرىلاش',
    justify: 'توغرىلاشنى توغرىلاڭ',
    print: 'بېسىش',
    outdent: 'تەۋەككۈلچىلىكنى ئازايتىش',
    indent: 'تەۋەككۈلچىلىكنى ئاشۇرۇش',
    removeFormat: 'فورماتنى ئۆچۈرۈڭ',
    formatting: 'فورماتلاش',
    fontSize: 'خەت چوڭلۇقى',
    align: 'توغرىلاش',
    hr: 'توغرىسىغا قائىدە قىستۇرۇش',
    undo: 'ئەمەلدىن قالدۇرۇش',
    redo: 'Redo',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    heading4: 'Heading 4',
    heading5: 'Heading 5',
    heading6: 'Heading 6',
    paragraph: 'ئابزاس',
    code: 'كود',
    size1: 'بەك كىچىك',
    size2: 'ئازراق كىچىك',
    size3: 'نورمال',
    size4: 'ئوتتۇراھال چوڭ',
    size5: 'چوڭ',
    size6: 'بەك چوڭ',
    size7: 'ئەڭ چوڭ',
    defaultFont: 'كۆڭۈلدىكى خەت نۇسخىسى',
    viewSource: 'مەنبەنى كۆرۈش',
  },
```
I could submit a PR with the above but it's accuracy could be questionable.

@Ansar-786 would you please be able to review and correct the translations above
and then update the language file with the new translations?

**Comment by webnoob** [comment]
We are watching this but as we don't know uyghur, we'll wait for @Ansar-786 to report back :)

**Comment by rstoenescu** [comment]
This has been left hanging :(
Pushed changes suggested by @Blfrg (thanks btw!)

This will go into Quasar v2.1.10
