### ISSUE TITLE
QDate: Date and Time in persian calendar

### ISSUE THREAD

**Issue by amiraghazadeh** [quasarframework/quasar#8124]
in the QDate component, persian calendar forced me to use "YYYY/MM/DD" mask and i can't set time in fact i can't set calendar mask to "YYYY/MM/DD HH:mm"

```
<q-input filled v-model="date">
      <template v-slot:prepend>
        <q-icon name="event" class="cursor-pointer">
          <q-popup-proxy class="no-shadow" transition-show="scale" transition-hide="scale">
            <div class="row">
              <q-date v-model="date" mask="YYYY/MM/DD HH:mm" calendar="persian"></q-date>
              <q-time class="on-right" v-model="date" mask="YYYY/MM/DD HH:mm" format24h></q-time>
            </div>
          </q-popup-proxy>
        </q-icon>
      </template>
</q-input>
```

**Comment by IlCallo** [comment]
As stated on the docs, the mask is forced to `YYYY/MM/DD`: https://quasar.dev/vue-components/date#Model-mask

Here's the PR introducing this limitation: https://github.com/quasarframework/quasar/pull/4153

If you know any way to overcome this, please PR :)
