### ISSUE TITLE
qInput borderless does not work in combination with filled

### ISSUE THREAD

**Issue by NicoP-S** [quasarframework/quasar#8125]
**Describe the bug**
I need a qInput with filled background but without the bottom border line. 
I tried borderless which works alone but not with filled and borderless

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/k6fsbyu8/5/

**To Reproduce**
Check the jsfiddle.
q-input with filled and borderless attribute does show the bottom border line.

**Expected behavior**
The bottom line should not be there

**Screenshots**
![image](https://user-images.githubusercontent.com/8988747/100659231-a135f400-3350-11eb-839a-33030d282a74.png)

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/input#Design

Use CSS
