### ISSUE TITLE
[Feature] Allow a global configuration for labels/i18n/internationalization on components

### ISSUE THREAD

**Issue by wagnereliakim** [quasarframework/quasar#813]
I'd like the ability to globally set the labels of the Datetime components (to avoir write ok-label, clear-label, month-names in all use of component)  and all the other components that have intenationalizable labels.
The configuration looks like this:

```
Vue.use(Quasar, {
  components: Everything,
  directives: Everything,
  i18n: {
    dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    clearLabel: 'Limpar',
    okLabel: 'Pronto',
    cancelLabel: 'Cancelar'
  }
})
```

If this is approved, I already have an implementation to do the PR. ;)

**Comment by rstoenescu** [comment]
Might interfere with what I already have in mind, but your idea is very good and I'd like to see it done. So let's have it :) Thanks for the proposal and your efforts on a PR!

Might be an idea to also be able to dynamically change language at runtime. The plan with i18n is to make language packs that you can import. Your idea is a great starting point.

**Comment by brucelane** [comment]
I can help for the french part, if needed

**Comment by a47ae** [comment]
I volunteer for the German translation :D

**Comment by murbanowicz** [comment]
I'd be more than happy to do polish translation

**Comment by guyulmaz** [comment]
I can do the Turkish traslation

**Comment by a47ae** [comment]
German translation:

```
export const i18n = {
  dayNames: 'Sonntag_Montag_Dienstag_Mittwoch_Donnerstag_Freitag_Samstag'.split('_'),
  monthNames: 'Januar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November_Dezember'.split('_'),
  clearLabel: 'Löschen',
  okLabel: 'Bestätigen',
  cancelLabel: 'Abbrechen',
  selectLabel: 'Auswählen',
  dataTable: {
    columns: 'Spalten',
    allCols: 'Alle Spalten',
    rows: 'Reihen',
    selected: {
      singular: 'Eintrag ausgewählt.',
      plural: 'Einträge ausgewählt.'
    },
    clear: 'Abwählen',
    search: 'Suchen',
    all: 'Alle',
    noDataAfterFiltering: '<i class="material-icons">warning</i> Keine Ergebnisse. Bitte verfeinern Sie die Suchanfrage.',
    noData: '<i class="material-icons">warning</i> Keine Daten verfügbar.'
  }
}
```

I think it is easier if you add it to your PR instead of me open a PR on your fork :D

**Comment by wagnereliakim** [comment]
@a47ae  done. :ok_hand:

**Comment by rstoenescu** [comment]
This is work in progress. Going a step further with the PR and making dynamic language change possible. Lots of quirks to take care of before releasing this.

For any new translations, please use temporary "i18n" branch (`/i18n` folder).

Building a kick-ass i18n system. Thanks for your patience.

**Comment by dmig** [comment]
I'd propose one more feature: optional short day names. If unspecified, use current algorithm (get first 3 letters).
Reason for this is because some languages have standardized short names, e.g. russian, ukrainian, belorussian have 2-letter abbreviations.

**Comment by colinmollenhour** [comment]
It seems like this is reinventing the wheel... There are great libraries that are well maintained such as moment.js.  If you implement i18n directly you will forever be bogged down with little issues for supporting  every language on earth. I'm not advocating making another library a dependency, but perhaps an official optional extension.

**Comment by rstoenescu** [comment]
Hi, this has been done for v0.15, so closing this. Please provide PRs for a language you want if it's not already here: https://github.com/quasarframework/quasar/tree/dev/i18n
Thanks.
