### ISSUE TITLE
q-input in q-tab-panels cant support swip

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar#8132]
In the q-tab-panels tag
q-select textaarea etc. can swipe normally
q-input cannot be triggered

https://codesandbox.io/s/upbeat-fermi-w7y3v?file=/src/App.vue

**Comment by pdanpdan** [comment]
Hello. This is the expected behavior, else you would not be able to select text or move the cursor on mobile (where swipe makes sense).
