### ISSUE TITLE
Q-Btn click method ain't triggering button animation

### ISSUE THREAD

**Issue by kotoOo** [quasarframework/quasar#8134]
There's click method on q-btn component, said it emulates a click on the button, right? When I call it, the buttons fires a subsequent @click handler, but ain't conducting an animation. However if I call a standard DOM method "click" there is a ripple animation (but no push animation), and the @click handler ain't triggered.
I understand that click method might accept the event object, however I've got no such object, because I try to emulate click not based on mouse activity.
Any suggestion how to implement this correctly?

1. Install Vite.
2. Install quasar@next.
3. Strap it. I use the following code in main.js:

```
import { Quasar } from 'quasar';
import { provide } from 'vue';

const app = createApp(App);

Quasar.install({
  config: {
    globalProperties: {},
    dark: true
  },
  provide,
  component: app.component,
  directive: app.directive 
});
```

4. Place a button and ref it:

`<q-btn push color="primary" ref="btn" @click="onClick">Emulated click</q-btn>`

```
import { ref } from "vue";

...

setup() {
    const btn = ref(null);

    const onClick = () => console.log("@click triggered.");

    return { btn, onClick };
}

...
```

5. Try to emulate a click:

`btn.value.click();`

**Expected behavior**
Button animation triggered with a ripple effect at the center of the button.

**Platform (please complete the following information):**
OS: Windows 10
Node: latest
NPM: latest
Yarn: none
Browsers: Chrome
iOS: -
Android: -
Electron: -

**Additional context**
If we would assign an ID and call `document.getElementById(...).click()`, ripple effect will happen, but not the push effect and also `@click` handler won't be called.

With my best regards to the cutest Vue UI framework =^_^=

PS: It would be nice to have a compehensive doc page about using Quasar just as an NPM package, w/o vue-cli nor quasar-cli. My research shows that it is doable, however there's lack of information on that. 

And probably it would be useful for someone to have described how to use only CSS part of Quasar (at a marking up stage of a project for example). The grid system served well for me from CDN @alpha.6.

**Comment by kotoOo** [comment]
There's an `evt` argument to the `click` method, and we might create a fake event to pass with something like this

```
          const clickEvent = new MouseEvent('click', {
            view: window,
            bubbles: true,
            cancelable: true
          });
```

The problem is: I don't know what properties to pass, there're tons of them. May I have a details on what properties Quasar will use from the argument?

**Comment by pdanpdan** [comment]
It's a little more complicated that you would expect.
- you need real user generated events
- you need to send `mousedown`, `mouseup` and `click` in that order

An example here: https://codepen.io/pdanpdan/pen/vYXLqvR?editors=1010

But this doesn't belong to the core, it's fun to play with but not easy to implement.
And this is only for mouse, you have also touch and keyboard events :)

**Comment by davija** [comment]
> An example here: https://codepen.io/pdanpdan/pen/vYXLqvR?editors=1010

Do you think you could post that example again?  Seems to no-longer be there.  This should REALLY be part of the documentation at least.  The q-btn document page lists the method but there are no examples that use that aspect of it.

**Comment by pdanpdan** [comment]
I think it should be something like this: https://codepen.io/pdanpdan/pen/NWJxgzd?editors=0010
