### ISSUE TITLE
Tabs Alignment in Firefox

### ISSUE THREAD

**Issue by GlutenBoy** [quasarframework/quasar#8140]
**Describe the bug**
Tabs alignment in Firefox changes when using tabs within a splitter.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/glutenboy/pen/QWKjQYz

**To Reproduce**
1. Use Firefox as your browser
1. Go to https://codepen.io/glutenboy/pen/QWKjQYz
1. Move the splitter slowly
1. Tabs alignment doesn't stay as Justified

**Expected behavior**
Tabs alignment should stay as justified

**Screenshots**
![image](https://user-images.githubusercontent.com/2528256/100903303-bb2c1f80-3493-11eb-908e-fa51a87d1d1c.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: 14.15.1
NPM: 6.13.6
Yarn:
Browsers: Firefox 83.0 (64 bits)
iOS:
Android:
Electron:
Quasar: v1.14.5

**Additional context**
N/A

**Comment by rstoenescu** [comment]
This has been fixed for Quasar v2.
