### ISSUE TITLE
Version changes from assigned version number in package.json to 1.0 when .apk is built with Capacitor and then uploaded to Google Play console

### ISSUE THREAD

**Issue by vahost** [quasarframework/quasar#8141]
**Describe the bug**
When I build and sign the app for Google Play using Capacitor, then upload it to the Google Play console, it reports that the version that I set in my package.json file gets changed to version 1.0.

If I use Cordova instead, the package uploads successfully and maintains the assigned version number in package.json.

So I'm pretty sure this issue is specific to Capacitor.

I tried submitting this as a bug at the Capacitor repository, but they kicked it back saying that the native version doesn't use package.json

**Codepen/jsFiddle/Codesandbox (required)**
This isn't a problem with Quasar per se. It's a problem with using Capacitor to publish my Quasar app to Google Play.

**To Reproduce**
1. Double-check version number in package.json
2. Run: quasar build -m capacitor
3. Sign the .apk file
4. Upload to Google Play console.

**Expected behavior**
I expect the file to upload and show the proper version of the app as assigned in package.json.

**Screenshots**

**Platform (please complete the following information):**
Operating System - Windows_NT(10.0.19041) - win32/x64
NodeJs - 12.18.3

Global packages
NPM - 6.14.9
yarn - 1.21.1
@quasar/cli - 1.1.0
@quasar/icongenie - 2.3.0
cordova - 10.0.0

Important local packages
quasar - 1.14.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
@quasar/app - 2.1.8 -- Quasar Framework local CLI
@quasar/extras - 1.9.10 -- Quasar Framework fonts, icons and animations
eslint-plugin-quasar - Not installed
vue - 2.6.12 -- Reactive, component-oriented view layer for modern web interfaces.
vue-router - 3.2.0 -- Official router for Vue.js 2
vuex - 3.5.1 -- state management for Vue.js
electron - 7.1.7 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
electron-packager - Not installed
electron-builder - Not installed
@babel/core - 7.12.9 -- Babel compiler core.
webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
workbox-webpack-plugin - Not installed
register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
typescript - 3.9.5 -- TypeScript is a language for application scale JavaScript development
@capacitor/core - 2.4.4 -- Capacitor: cross-platform mobile apps with the web
@capacitor/cli - 2.4.4 -- Capacitor: Cross-platform apps with JavaScript and the web
@capacitor/android - 2.4.4 -- Capacitor: cross-platform mobile apps with the web
@capacitor/ios - Not installed

Quasar App Extensions
None installed

Networking
Host - Abraham
Ethernet 2 - 10.0.0.198
Wi-Fi - 10.0.0.125

**Additional context**
That's about it.

**Comment by 1pavanb** [comment]
ugh nooo!
why is such an important thing not working in the stable release? 😔

**Comment by vahost** [comment]
Well, to be fair, rstoenescu and his team do a great job with the Quasar framework, and I really appreciate all of the work they do. It's easy for a glitch like this to happen given all of the changes they make so devotedly.

I'm looking forward to seeing the resolution for this particular bug, and I'm sure they'll be able to find it!

**Comment by 1pavanb** [comment]
I've written a script to copy the version from `package.json` into android's build.gradle.
Haven't got to iOS yet

**Comment by vahost** [comment]
> I've written a script to copy the version from `package.json` into android's build.gradle.
> Haven't got to iOS yet

I have been able to upload to Apple without issue.

**Comment by pdanpdan** [comment]
Do you have a version set in `quasar.conf.js` under `capacitor` key?
If you have that version will be used, else the version from `package.json` is used.

**Comment by vahost** [comment]
@pdanpdan I didn't have it set in quasar.conf.js, but I did have it set in package.json. I double-checked the src-capacitor folder, and the package.json file in that location had it set as well.

**Comment by tegola** [comment]
I'm in the same boat. After bumping the version inside `package.json` (in the root object) from `0.2.0` to `0.2.1` I can't submit the final build to the Google Play Store. It says it's the same version 1.

Actually, even the first build I uploaded is marked as version 1.0, even though it should have been 0.2.0.

**Comment by vahost** [comment]
@tegola While we wait for the team to make changes to fix this issue, there is a workaround we can use.

If you open the file at src-capacitor > android > app > build.gradle and change the VersionName field manually there, the app will compile correctly, and you will be able to successfully send the app with the correct version to Google. Once you compile it correctly, the build.gradle file will disappear from src-capacitor > android > app.

**Comment by tegola** [comment]
Thanks @vahost, that’s what I did, albeit I changed the incremental `versionCode` to 2 instead of changing the `versionString`.

**Comment by adrian-e** [comment]
Is there any plan to address this? This seems like a very basic problem (not being able to publish with specified version number).
For those who were able to solve it manually, did you have to compile from the Android Studio or could you do it from the command line?
Any help would be really appreciated!

**Comment by tegola** [comment]
@adrian-e IIRC I could compile from Android Studio.

**Comment by Fireant456** [comment]
Is there any update on this issue, I still have this issue and would like to resolve it

**Comment by yusufkandemir** [comment]
Please see, it's a problem with Capacitor in general, nothing related with the Quasar integration: https://github.com/ionic-team/capacitor/issues/3943
