### ISSUE TITLE
SSR dev mode: Hot reloading from *node_modules* does not work on the server side

### ISSUE THREAD

**Issue by chetzof** [quasarframework/quasar#8150]
**Describe the bug**
Hot reloading from *node_modules* does not work on the server side

**Codepen/jsFiddle/Codesandbox (required)**
Not possible

**To Reproduce**
1. Create a dir with a file in node_modules
2. Add a line `console.log(1)`
3. `quasar dev -m ssr`
4. Change the line to  `console.log(2)`
5. Reload the page

**Expected behavior**
1. Browser console displays `2`
2. Server side terminal console displays `2`

**Current behavior**

1.  Browser console displays `2` :white_check_mark:
2. **Server side terminal console displays `1`** :x: 

**Platform (please complete the following information):**
OS: MacOS

    Dev mode.......... ssr
    Pkg quasar........ v1.14.6
    Pkg @quasar/app... v2.1.9
    Transpiled JS..... yes (Babel)

**Additional context**
I'm using this to develop a decoupled standalone node package - I think thats a quite common use-case.

Tried to add

      watchOptions: {
        ignored: [/node_modules(\\+|\/)+(?!my-module)/],
      },

The server reloads but still old files show

**Comment by rstoenescu** [comment]
Hi,

No, it's not common use-case nor a good practice. node_modules is considered "immutable". The content can only change when yarn/npm installing/upgrading/uninstalling. You could however try to use yarn workspaces.
