### ISSUE TITLE
QInput / password / security

### ISSUE THREAD

**Issue by dev31337** [quasarframework/quasar#8155]
Hi,

Would it be possible to make the QInput with type=password a little bit more secure about showing the password ?

At this time using the inspector and removing "type=password" to the QInput directly shows the password.

Maybe a specific password component that would not be so easy to edit (where the logic would be in JS) could be more secure, what do you think ?

Unless you have a suggestion on how to make Qinput a bit more secure than it is ?

Regards.

**Comment by pdanpdan** [comment]
The security of password fields is provided by the browser and is only meaningful against people watching your screen.
