### ISSUE TITLE
[rtl] QSelect's options menu should always align to the start(right)

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#8157]
**Describe the bug**
It seems that some work has been done on rtl in `1.14.6` which has affected the `QSelect` options menu. When in rtl mode, if a `QSelect` has an option with a long text such that the rendered options menu is wider than the `QSelect` itself, the options menu should always align to the start of select element, which in rtl, it is to the right. This behavior was changed in `v1.14.6` and now ltr and rtl are behaving the same.

If I'm not mistaken, `QSelect` uses `QMenu` for its options menu, but the `QMenu` itself when used independently is not affected by this and is behaving correctly in `v1.14.6` so the issue seems to be limited to `QSelect`.

I have made two pens one with `v1.14.5` and one with `v1.14.6` to demonstrate the issue.

Incorrect behavior: `QSelect` with long option text using `v1.14.6`
https://codepen.io/behnoodk/pen/RwGRwop

Correct behavior: `QSelect` with long option text using `v1.14.5`
https://codepen.io/behnoodk/pen/JjRKjRo

**Comment by pdanpdan** [comment]
If on LTR the list is align on right (end) shouldn't it be aligned on end on RTL also?

**Comment by behnoodk** [comment]
It never occurred to me that the LTR behavior has been revered as well. As far as I know, and what comes naturally is that when an option is very long, a user should not have to go and look for the beginning of the option text. It should always start from the start of parent component (select) and continue from there on.

I checked and that is in fact the default behavior of both desktop Chrome and Firefox when rendering an option element that is wider than the select element. This default behavior can be seen in the following pen:

https://codepen.io/behnoodk/pen/jOMrEEj

So as it stands, `QSelect` is rendering its options menu for wide options incorrectly for both LTR and RTL as of `v1.14.6`.

**Comment by pdanpdan** [comment]
From my point of view it should be aligned on the dropdown arrow by default. But you can use `menu-anchor` and `menu-self` to put it the other way around

**Comment by rstoenescu** [comment]
Fix will be available shortly in Quasar v1.14.7.

**Comment by behnoodk** [comment]
Thank you Dan and Razvan.

I have been using Quasar since the very first day v1-beta1 was released on a daily basis. Using Quasar has always been a joy and communicating with the team always a pleasant experience.
