### ISSUE TITLE
q-table > columns > needs dynamic classes

### ISSUE THREAD

**Issue by renaudham** [quasarframework/quasar#8158]
**Is your feature request related to a problem? Please describe.**
Currenlty we can't set dynamic classes to a row's cell
trying 
            classes:  (val, row)  =>  `${val} bg-grey-2 ellipsis`,
not working

**Describe the solution you'd like**
We would surely lot of us, need to be able to set variable classes for each rows based on row values
for classes

**Comment by renaudham** [comment]
or maybe, at least to be able to add HTML inside this
format: val =>  `${memberStatus[val].label}`,
so we could wrap and set dynamic look directly from columns WITHOUT using cell scope templates
(quite important when we want to generate columns and row automatically from objects configs only)

**Comment by pdanpdan** [comment]
You can use a generic scoped slot for cell and set what you want from your config. It would slow the simple case too much.

**Comment by renaudham** [comment]
Hi 
right yes true, I did it
I didnt see before that it was possible ot get columns config in it with props.col
thanks

<template v-slot:body-cell="props">
          <q-td :props="props" @contextmenu.prevent="showContextualMenuRghtClk(props.row.id)">
            <q-btn v-if="props.col.hasMenuAction" padding="xs" round flat class="q-mr-sm"
                   color="grey-8"
                   icon="menu" size="sm" :id="'menuBtn-'+props.row.id"
                   @click.stop.prevent="showContextualMenu(props.row.id)"
                   @mouseover="setContextualMenuTarget(props.row.id)"
            >
              <q-tooltip anchor="bottom left" self="center middle" content-class="bg-black" :ref="'ttctx'+props.row.id">
                Actions on this row
              </q-tooltip>
            </q-btn>
            <q-avatar v-if="props.col.hasAvatar!==undefined && props.col.hasAvatar.position==='before'" size="26px" class="q-mr-sm">
              <img :src="props.row[props.col.hasAvatar.field !==undefined ? props.col.hasAvatar.field : 'avatar']">
            </q-avatar>
  
  
            <component v-if="props.col.cellCmpPath!==undefined" v-bind:is="getCellsCmp[props.col.name]" :row="props.row"></component>
            <span v-else>{{ props.value }}</span>
            
            <q-avatar v-if="props.col.hasAvatar!==undefined && props.col.hasAvatar.position==='after'" size="26px" class="q-ml-sm">
              <img :src="props.row[props.col.hasAvatar.field !==undefined ? props.col.hasAvatar.field : 'avatar']">
            </q-avatar>
          </q-td>
        </template>
