### ISSUE TITLE
QForm actions (submit, reset, etc...) aren't triggered if they are called from a v-slot of an QInput

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#8161]
**Describe the bug**
I have a form in which there is an input after which, with the v-slot:after attribute, I put some buttons that are supposed to trigger the submit actions (reset/submit) but they don't.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/medhyena/pen/XWjKKpL

**To Reproduce**
1. Go to https://codepen.io/medhyena/pen/XWjKKpL
2. Click on the "click me" button
3. Alert doesn't appear
4. Click on the "click me 2" button
5. Alert does appear

**Expected behavior**
Idk if this is normal or not, but it seems weird that the QForm scope doesn't access the v-slot of QInput (it may happen with other components, I haven't tried at all). So it should just proc the events like it normally does.

**Comment by pdanpdan** [comment]
Please read that big yellow block of text: https://quasar.dev/vue-components/input#Slots-with-QBtn-type-%E2%80%9Csubmit%E2%80%9D

**Comment by Medhyena** [comment]
INDEED, Thx for the advice
