### ISSUE TITLE
[docs] Clearer information how to do access control of routes

### ISSUE THREAD

**Issue by aliclark** [quasarframework/quasar#8166]
As a relative newbie to both Vue and Quasar it took me unreasonable amount of effort to track down the guidance that is essentially contained in the following forum answer: https://forum.quasar-framework.org/post/14454

The problem is that there are lots of variations on how to do this, including some that used to work on previous Quasar versions that returned a singleton from `./store`. Some places suggest simply hacking that file to expose the singleton, which I guess is not the best advice.

Other Vue resources in general suggest using `beforeCreate` to add a router push if needed, but elsewhere I learned that apparently this might not actually stop the component from beginning to load, and also seems a bit odd.

So there's a lot of confusion out there, and I think it would help other newbies to have the suggestion of the forum link above in the official docs somewhere (along with relevant searchable terms like "access control" and "login redirect".

**Comment by pdanpdan** [comment]
Hello.

You have:
- https://quasar.dev/quasar-cli/boot-files#Anatomy-of-a-boot-file
- the default `router/index.js` that shows the signature of the function (`export default function (/* { store, ssrContext, Vue } */)`)
- https://quasar.dev/quasar-cli/prefetch-feature

If you think the docs can be improved please make a PR with the desired improvements, but don't put there things that are in the vue-router docs.
