### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/Users/src-cordova/platforms/ios/build/emulator'

### ISSUE THREAD

**Issue by SamnnyWong** [quasarframework/quasar#8167]
Environment: mac OS 10.15 and Xcode 12.2, Quasar build using cordova mode

when i run `quasar build -m cordova -T ios` it gives me this error.

complete log looks like this:

```
** ARCHIVE SUCCEEDED **

Running command: xcodebuild -exportArchive -archivePath TacticsApp.xcarchive -exportOptionsPlist /Users/xxx/src-cordova/platforms/ios/exportOptions.plist -exportPath /Users/xxx/src-cordova/platforms/ios/build/device
2020-12-09 02:36:59.575 xcodebuild[64442:4626987] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/62/74cgqn1d3q9b2x59g3gwm9hh0000gn/T/TacticsApp_2020-12-09_02-36-59.574.xcdistributionlogs'.
Exported TacticsApp to: /Users/sam/xxx/src-cordova/platforms/ios/build/device
** EXPORT SUCCEEDED **
(node:64230) UnhandledPromiseRejectionWarning:   Error: ENOENT: no such file or directory, stat '/Users/xxxsrc-cordova/platforms/ios/build/emulator'
  
  - polyfills.js:307 Object.statSync
    [AppTactics]/[graceful-fs]/polyfills.js:307:34
  
  - stat.js:10 statSync
    [AppTactics]/[fs-extra]/lib/util/stat.js:10:52
  
  - stat.js:24 getStatsSync
    [AppTactics]/[fs-extra]/lib/util/stat.js:24:19
  
  - stat.js:49 Object.checkPathsSync
    [AppTactics]/[fs-extra]/lib/util/stat.js:49:33
  
  - copy-sync.js:24 Object.copySync
    [AppTactics]/[fs-extra]/lib/copy-sync/copy-sync.js:24:38
  
  - index.js:94 CordovaRunner.build
    [AppTactics]/[@quasar]/app/lib/cordova/index.js:94:9
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```
I tried adding and removing ../platform/ios by running `cordova platform rm ios` and `cordova platform add ios` with no luck.
I also remove node_modules and npm install, doesn't work.
It saids its missing /src-cordova/platforms/ios/build/emulator, but when i run `quasar dev -m cordova -T ios` without the test device plug in to the mac, emulator boots up, app launch with no problem, and the emulator directory appears under /src-cordova/platforms/ios/build.
Even though it prompted an error but when I run `cordova run ios` under dir `src-cordova` the app launches and run with no problem.
in quasar.conf.js i disabled the legacy build system so it is using the new build system.
```
    cordova: {
      noIosLegacyBuildFlag: true,
    },
```
Do I need to specify a build.json under the directory `src-cordova` for me to build successfully? if yes is there an example provided?
been stuck to this issue for days and seems like no other similar post.
thanks in advance.
I also posted this same issue in cordova-ios repo: https://github.com/apache/cordova-ios/issues/1039 becuase i am not sure if this is an issue from quasar or cordova.

**Comment by dominixdesign** [comment]
I ran into the same issues, and after a few hours I found a solution:
Just unplug all connected devices.

It seems that Xcode detects, that there is a device, and it don't create the emulator folder. If there is no real device, the emulator folder is created.

**Comment by pdanpdan** [comment]
Glad you found a solution.
