### ISSUE TITLE
QSelect with use-input and append slot will not trigger dropdown if append slot content is clicked

### ISSUE THREAD

**Issue by DelaneDiamon** [quasarframework/quasar#8169]
**Describe the bug**
Using QSelect with use-input and append slot will not trigger dropdown popup if append slot is clicked, but will focus input without cursor.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/Diamon33/mxct8rpy/32/

**To Reproduce**
1. Click 'expand_more' icon
2. See no dropdown

**Expected behavior**
QSelect dropdown is expected to appear

**Additional context**
If use-input is **not** used - works by design

Possible workarounds:
1. this.$q.iconSet.arrow.dropdown = 'expand_more' in created hook or wherever. Not optimal, also introduces additional CSS styling and conditional class binding and non-material icons (ex. FontAwesome) are seem to be non-selectable by this.
2. append slot with @click with $refs.{refname}.showPopup - works, but you have to adjust icon element size to occupy fill input height, otherwise there will still be a space with non-dropdown click behavior around the icon.

**Comment by pdanpdan** [comment]
Why don't you use `dropdownIcon` prop?
I'll check the behavior.

**Comment by DelaneDiamon** [comment]
I (and our team) do use dropdown-icon, but product requirements are to change this arrow's color (and sometimes shape) whenever it has validation error or this dropdown is a required form field. 
I know it's CSS matter, but we went with "easier" path of icon color class bindings and icon names for append slot, and found out this behavior. I wanted to clarify if it's intended or not.

**Comment by pdanpdan** [comment]
this is available in v1.15.0
