### ISSUE TITLE
[Feature] Extend QFixedPosition to include 'top', 'right', 'bottom', 'left'

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#817]
Maybe by introducing an alternative prop called `side`? Or extending the 'corner' to include 'middle-top', 'middle-left', etc. Not really corners though...

The result should be centred against whichever side was specified. This would make putting a 'scroll up' /  'scroll down' button at the middle-top or middle-bottom much easier.

**Comment by JCharante** [comment]
I've wanted this bu forgot to make a feature request. Thanks for creating one :+1:

**Comment by smolinari** [comment]
How about a value in percent for the locations vertically and horizontally? For vertical, 0% would be the top. 50% would be the middle and 100% would put whatever it is we are fixing at the bottom. For horizontal, 0% would be left and 100% would be right. That way, the fixed position can end up being anywhere on the screen. Maybe?  v-50% and h-50% would be smack in the middle. 😄

Scott

**Comment by smolinari** [comment]
Oh, and this shouldn't be too hard to implement either. So, this could be labeled "contributor friendly". 😄 

Scott

**Comment by rstoenescu** [comment]
I guess the best implementation should be to only have "position" prop to support all of these values. But this means introducing a breaking change and I am a little bit reluctant to do this. Will ponder on this to see how best to proceed.

**Comment by smolinari** [comment]
@rstoenescu - How about this? Allow percentage values in the offset?

For instance, 
```
<q-layout>
  ...  
  <q-fixed-position corner="top-right" :offset="[50, 50, '%']">    
    <q-btn round color="primary" @click="alert" icon="alarm" />  
 </q-fixed-position>  
  ...
</q-layout>
```
Would put the button in the middle of the screen. 

Or this:
```
<q-layout>
  ...  
  <q-fixed-position corner="top-right" :offset="[50, 0, '%']">    
    <q-btn round color="primary" @click="alert" icon="alarm" />  
 </q-fixed-position>  
  ...
</q-layout>
```
This would put the button on the right side of the screen, but in the middle. 

This way, we could have both relative and pixel exact offsets to the corners and the change would be backwards compatible? :smile:

Scott

**Comment by spectrolite** [comment]
IMHO it feels a bit clunky compared to the rest of quasar, and makes the code quite hard to mentally visualize.

I mean that by reading the code you will have a hard time figuring out what it's going to look like, and the intention is lost: "put the button on the right side of the screen, but in the middle" becomes `corner="top-right" :offset="[50, 0, '%']"`... to me it feels weird already, and that's forgetting how much this can be abused (you started from top and used a sensible (50, 0) but using (80, 50) or (25-75) or worse could make it a nightmare.. and switching the corner would wreak havoc unless you change also the offset... and someone could write some seriously horrific stuff like `corner="bottom-right" :offset="[90, 90, '%']"` to get near the top left corner...) Feels like a pandora's vase opening imo.

I hope Razvan can find some solution with a cleaner usage syntax.

Using `side="top|bottom|left|right"` (as @dsl101 suggested)  as an *alternate* to `corner` would be clean and should not break the code of people using `corner` where needed. But I may be missing something.

Surely a unique `position` prop would be best, but I respect the reluctance to introduce breaking changes.

**Comment by dsl101** [comment]
@rstoenescu I'm not sure how _adding_ a `position` prop (which would support all variations - corner, side, optional offset, etc.) would be a breaking change. Just continue to support `corner` as well, and mark it deprecated - perhaps with a console warning? Then remove it in `X` years :).

**Comment by smolinari** [comment]
@spectrolite - agreed. I don't like my suggestion much either, but I only made it to keep things backwards compatible. My opinion is, being Quasar is still in beta, then in effect, breaking changes are normal and should be expected i.e. are supposed to happen. If Quasar were to be 1.0, I would consider breaking changes a no-no at that point. 

Scott

**Comment by dsl101** [comment]
I'm still confused about what would break - see me previous post?

**Comment by spectrolite** [comment]
@rstoenescu I think I understand your point of view, and to answer @dsl101 I’d say just one word : bloat. And then I’ll bloat my paragraph by adding: it could result in some very confusing code/results if used wrong (e.g. position+corner together).
But proper documentation can mitigate this, and the convenience would really outweigh the “risks”.

So please Razvan, can we have some interpretation of this feature in v0.15 ?

**Comment by dsl101** [comment]
If `corner` issues console warnings and then is removed in 0.16, it shouldn't bloat more than happens to me during the summer holiday, and I'm back down to my fighting weight now :)

**Comment by spectrolite** [comment]
@dsl101 What I mean by “bloat” is that as both codebase and quasar get bloated by potentially contradicting properties, elegance and predictability both go out the window. So you’re technically right in that it can be implemented so that nothing will actually break, you introduce a pinch of entropy in the core, that Razvan has so skilfully kept simple and free of unnecessary chaos with great care and effort. Feels like shame, hence his reluctance.

But I’m sure an elegant solution can be found..

**Comment by dsl101** [comment]
Whilst `corner` and `position` coexist, yes. But when `corner` goes, where is the bloat? Other than `position` will necessarily be bigger because, well, it does more...

**Comment by rstoenescu** [comment]
This will go into v0.15.
"corner" prop getting removed.

**Comment by rstoenescu** [comment]
QPageSticky will have this, replacing QFixedPosition in future v0.15
