### ISSUE TITLE
Bouncing button on quasar.dev home page does not support mobile touch

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#8171]
**Describe the bug**
Bouncing button on quasar.dev home page does not respond to mobile touch. Works in Chrome on my desktop computer.

**To Reproduce**
1. Go to quasar.dev in Android Chrome
2. Click on bouncing down arrow button
3. Nothing happens

**Expected behavior**

Should scroll to next section of the home page.

**Platform 
Android: Chrome

**Comment by pdanpdan** [comment]
Hello. That is just and indicator, it doesn't do anything on click on any device.
