### ISSUE TITLE
BEX: background-hooks can not catch bridge events from dom-hooks

### ISSUE THREAD

**Issue by bruha** [quasarframework/quasar#8174]
BEX: background-hooks can not catch bridge events from dom-hooks

I emit my event in **dom-hooks.js**:
```js
export default function attachDomHooks (bridge) {
  bridge.send('message.to.quasar', { from: 'dom-hooks' })
}
```

But I failed to catch it in **background-hooks.js**:
```js
export default function attachBackgroundHooks (bridge) {
  bridge.on('message.to.quasar', event => {
    console.log('message.to.quasar', event.data.from)
    bridge.send(event.eventResponseKey)
  })
}
```

Same code in **content-hooks.js** works as expected:
```js
export default function attachContentHooks (bridge) {
  bridge.send('message.to.quasar', { from: 'content-hooks' })
}
```

**Comment by webnoob** [comment]
You need to use the content-hooks.js file as a proxy to forward on the event to the background script. The dom cannot access the background script - this is by design.
