### ISSUE TITLE
set select aglin

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar#8180]
Like the following link

https://codesandbox.io/s/elegant-ganguly-q37yl?file=/src/App.vue

I need both INPUT and SELECT to be aligned on the right
INPUT can be implemented simply by "input-class"
And select is more cumbersome. Can you provide "select-class" or other solutions?

**Comment by pdanpdan** [comment]
For the input/filter in QSelect you have inputClass/inputStyle.
For the selected option you have slot.

**Comment by anyclub** [comment]
Re-coded the link 
https://codesandbox.io/s/elegant-ganguly-q37yl?file=/src/App.vue
What I mean is that INPUT can simply use a scheme like text-right to achieve right alignment effect
But select must use penetration capabilities like v-deep,
Expect to directly provide an API to modify the style or class of q-field__native
Just like q-input

I don't want to write too much v-deep in the project
And expect that this component can use scoped

Now this realization always feels too cumbersome
