### ISSUE TITLE
Make QInput with QDate and QTime default to today, not 1899

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#8196]
**Describe the bug**
When QInput is used with QDate and QTime and you select first the time, then the Date defaults to 1899-12-31. It should default to today. 

**To Reproduce**
1. Go to https://quasar.dev/vue-components/date#Example--QDate-and-QTime-with-QInput
2. Click on the TimePicker and select a time
3. The date will default 1899-12-31

**Expected behavior**
I would expect today's date instead of 1899-12-31. 1899 is almost never what i want and to get back to 2020 using the mouse is a lot of clicking. 

**Screenshots**
![obraz](https://user-images.githubusercontent.com/9776384/102079634-58c90c80-3e0d-11eb-8b5a-9b5c429d88e3.png)

**Platform (please complete the following information):**
OS: Windows 10 x64
Browsers: Firefox

**Comment by pdanpdan** [comment]
Set the `default-date` as you see fit.

**Comment by pdanpdan** [comment]
Ah, default-date is not working :(

**Comment by robert-niestroj** [comment]
I dont even see such a prop. All i see is `default-year-month` and this does not work too.

**Comment by robert-niestroj** [comment]
Anyway i still think today is the better default for this then 1899. It's just looks buggy.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.8

**Comment by robert-niestroj** [comment]
How has this been fixed? It's not clear for me from the commits.

**Comment by pdanpdan** [comment]
QTime will have the default date of today or the default date you specify
