### ISSUE TITLE
Only dismiss QDialog when click outside

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#8197]
**Is your feature request related to a problem? Please describe.**
I use the QDialog plugin to choose between 2 options, I use the cancel and ok button to each options but if I click outsite its uses onCancel

**Describe the solution you'd like**
onClickOutside or onDismiss prop to check if has been closed or canceled

**Describe alternatives you've considered**
Create my custom dialog

**Comment by pdanpdan** [comment]
Please read the API card, especially the `persistent` and `noEscDismiss` options.

**Comment by Nisgrak** [comment]
I want that the Dialog can be canceled by click outside, that its the "none" option, but i don't have any way to only detect that.

**Comment by pdanpdan** [comment]
I don't understand. Please make a codepen showing the problem.

**Comment by Nisgrak** [comment]
Of course, sorry for not provided before

https://codepen.io/Nisgrak/pen/BaLpXJm

**Comment by pdanpdan** [comment]
Ok, I understand what you want.
In my opinion it would be best to go with the custom component for dialog plugin.
By default the cancel button is a cancel for the dialog, the same as click outside or escape key, and it would only complicate things for the basic case.

**Comment by Nisgrak** [comment]
Okey, would be nice to have a component like that, but I understand that not fit to Ok/Cancel dialog
