### ISSUE TITLE
quasar.mat.css + quasar.mat.styl missing variables

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#820]
Hello, I've tried to set up Quasar Framework v0.14.1 with Laravel and compile it while noticing that there is some kind of bug in "quasar.mat.css":

1. 
.q-collapsible-sub-item.indent {
  padding-left: $collapsible-menu-left-padding; //
  padding-right: 0;
}

2.
.q-progress-model:not(.indeterminate) {
  position: absolute;
  top: 0;
  bottom: 0;
  border-radius: $progress-border-radius; //
  transition: width 0.3s linear;
}

And when I checked "quasar.mat.styl", these 2 variables below seem to be missing:

1.
.q-collapsible-sub-item
  padding $collapsible-padding
  &.indent
    padding-left $collapsible-menu-left-padding //
    padding-right 0

2.
.q-progress-model
  background currentColor
  &.animate
    animation q-progress-stripes 2s linear infinite
  &:not(.indeterminate)
    position absolute
    top 0
    bottom 0
    border-radius $progress-border-radius //
    transition $progress-transition

**Comment by rstoenescu** [comment]
Fixed. Available in edge and future 0.14.2. Thanks for reporting!
