### ISSUE TITLE
iosStatusBarPadding always true in build

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#8200]
**Describe the bug**
The iosStatusBarPadding prop in capacitor didnt work in build mode, it's always true

**To Reproduce**
1. Create a new project
2. Set the iosStatusBarPadding to false
3. Check with `quasar dev -m capacitor -T ios`
4. Check with `quasar build -m capacitor -T ios`

**Expected behavior**
When it's false it takes all screen, in dev works but in build has a margin

**Screenshots**
Dev mode
![image](https://user-images.githubusercontent.com/19597708/102096345-e19f7280-3e24-11eb-9d67-01c94d460b8b.png)
Build mode
![image](https://user-images.githubusercontent.com/19597708/102096166-b157d400-3e24-11eb-8d9f-1c598faa0f25.png)

**Comment by pdanpdan** [comment]
Can you inspect the html and check if you have a class `q-ios-padding` on body?

**Comment by Nisgrak** [comment]
No it doesn't, but the top bar didn't show in html code, I select the body tag and didn't highlight that....
![image](https://user-images.githubusercontent.com/19597708/102254186-9e1e3480-3f08-11eb-805d-da13b84dbaac.png)

In fact many times I need to change the iosStatusBarPadding to "refresh" the app and the top disappear in dev, it's has a very strange behavior...

Here iosStatusBarPadding as true (dev mode)
![image](https://user-images.githubusercontent.com/19597708/102254973-aa56c180-3f09-11eb-9687-5fd6ebabf83f.png)

Then change to false (dev mode, so it's hot reload) and same result...
![image](https://user-images.githubusercontent.com/19597708/102255032-c35f7280-3f09-11eb-9e80-4cd33b20fa99.png)

I don't understand the prop maybe

**Comment by oscar466102** [comment]
I thought quasar was only for a pc os, did u install it using xcode?

**Comment by pdanpdan** [comment]
Ok, so the code works as expected. You use `iosStatusBarPadding` correctly.
Btw, you are using a QLayout - because the padding is applied to
- first QToolbar in QHeader
- QDrawer
- last QTollbar in QFooter
- QDialog
- QNotify

**Comment by Nisgrak** [comment]
But I don't want the space, I want as this. With the same code has different results in dev/build...

![image](https://user-images.githubusercontent.com/19597708/102273371-85bb1380-3f22-11eb-9ddd-f7a4fa324be9.png)

**Comment by pdanpdan** [comment]
I understand what you want. I don't have the mac bundle required to debug, so I need your help.
I need you to inspect and report, both for dev and build mode, with iosStatusBarPadding set to false:
- padding and margin for html
- padding and margin for body
- padding and margin, and also the style/classes applied for your element that should cover the screen (the map?)

**Comment by Nisgrak** [comment]
Okey, let's begging:

## Dev mode
I clear the build folder and uninstall the app in iphone
### HTML
![image](https://user-images.githubusercontent.com/19597708/102396446-c11a1880-3fdc-11eb-8257-884313d5881a.png)
### Body
![image](https://user-images.githubusercontent.com/19597708/102396472-c6776300-3fdc-11eb-8cdd-bd4c8d5acce8.png)
### Map
It covers all screen (375x812)
![image](https://user-images.githubusercontent.com/19597708/102396543-e149d780-3fdc-11eb-8c0f-eb23643155cb.png)

## Build mode
I clear the build folder and uninstall the app in iphone
### HTML
![image](https://user-images.githubusercontent.com/19597708/102396808-4a314f80-3fdd-11eb-9fc6-d07b6f7d8121.png)
### Body
![image](https://user-images.githubusercontent.com/19597708/102396832-53bab780-3fdd-11eb-9e01-8b32f9c1c002.png)
### Map
It covers all screen (375x812), has the same size as in Dev Mode BUT the top bar is there...
![image](https://user-images.githubusercontent.com/19597708/102396926-78af2a80-3fdd-11eb-8d69-04793cbbce4c.png)

**Comment by pdanpdan** [comment]
Wtf, it's the exact same sizes.
I'll try to search maybe I can discover something.
Thank you for the help.

**Comment by pdanpdan** [comment]
I think I found something.

1. Check if in build mode you have `<meta name="viewport" content="initial-scale=1, width=device-width, height=device-height, viewport-fit=cover">` - **viewport-fit=cover** in `<head>`
2. Check https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator - the part about the splash screen

**Comment by Nisgrak** [comment]
1. It has
2. Has the same value
3. The splash screen is different in this days, isn't from Cordova/Capacitor, is from iOS itself (Storyboard) and the sizes are good.

**Comment by Nisgrak** [comment]
@pdanpdan I have something!

I enter in the screen and click THAT button
![image](https://user-images.githubusercontent.com/19597708/102684378-3e5dad00-41d8-11eb-874d-02ac8680a08d.png)

It's reload the page and boom!
![image](https://user-images.githubusercontent.com/19597708/102684385-4c133280-41d8-11eb-8411-511282e7f8be.png)

**Comment by Nisgrak** [comment]
Also, the simulator I have been using is iOS 14.1, this are the results in iOS 12.4
![image](https://user-images.githubusercontent.com/19597708/102684807-0a848680-41dc-11eb-87ac-b74adeea41f0.png)

iOS 13.7
![image](https://user-images.githubusercontent.com/19597708/102684868-7f57c080-41dc-11eb-827b-2c57d300addf.png)

It's seem is starting in iOS 13...

**Comment by pdanpdan** [comment]
I can find:
- https://github.com/ionic-team/ionic-v1/issues/341#issuecomment-380773950 - also related to splash image
- https://developer.apple.com/forums/thread/68244
Maybe the splash image is cached somehow?

**Comment by Nisgrak** [comment]
OH GOD I have it.

In `capacitor.config.json` I have:
```json
"ios": {
    "contentInset": "always"
  }
```

My god, as always, thanks for all the help @pdanpdan
