### ISSUE TITLE
Components (QInput and QSelect) don't lose focus...

### ISSUE THREAD

**Issue by jaronwanderley** [quasarframework/quasar#8203]
**Describe the bug**
### The components are:

- QInput from Quasar Examples - [Input Types](https://quasar.dev/vue-components/input#Input-types), types: time, date
- QSelect with a rule validation

### The behavior is:

The components when it come into focus using the 'TAB' key and when they should lose focus, because the focus changed to another component, the behavior is to still maintain focused.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/JaronWanderley/pen/OJRbaxR?editors=1000

**To Reproduce**
1. Click on any place inside the screen.. not a component..
3. Press the 'TAB' key on keyboard until the focus has passed through all components
4. See error (A animated blue border indicating the focused input)
5. Select tab 'WITH VALIDATION' Repeat the process 1,2,3

**Expected behavior**
After passing through all components with 'TAB' key, should not exist a component focused.

**Screenshots**
![image](https://user-images.githubusercontent.com/20912155/102123031-21665a00-3e25-11eb-9108-8e878a18abd0.png)
![image](https://user-images.githubusercontent.com/20912155/102123073-2fb47600-3e25-11eb-9cae-27bc1e48966c.png)

**Platform (please complete the following information):**
OS: Windows
Browsers: 
Chrome Version 87.0.4280.88 (QInput and QSelect)
Microsoft Edge Version 87.0.664.60 (QInput and QSelect)
Firefox Version 83.0 (QSelect)

**Comment by pdanpdan** [comment]
I don't know the problem yet, but you deserve a prize for the bug report :)

**Comment by jaronwanderley** [comment]
> I don't know the problem yet, but you deserve a prize for the bug report :)

The problem is that I want a application to be used only with keyboard, and I use a 'box-shadow animated border' to show my user where he is at moment. But shouldn't show more then **one** 'border animated', because the focus is only on a unique input.

As you can see the 'box-shadow border' is showing on a false focused input.

**Comment by pdanpdan** [comment]
I apologize if you misunderstood me. I meant I don't know the reason of the problem, and I was serious about the fact that I like the bug report.

Meanwhile I made some tests and it looks like:
- there is a bug in Chrome(including Edge) regarding emitting focusout on input type date/time, but it's very strange (details above) - firefox works ok
- for QSelect with rules I'm sure is something bad in our code

Focusout bug:
- navigate forward 1st time from before a field with date/time/week/... - the focusout event is not emitted
- navigate no matter what direction later - focusout is emitted
- now the fun part: exit 1st time backwards and focusout is emitted :(
- I'm pretty sure sometimes I was able to focus the icon of the picker, but most of the times not

So for that part I would say it's nothing we can do.
I'll check the QSelect

**Comment by jaronwanderley** [comment]
> I apologize if you misunderstood me. I meant I don't know the reason of the problem, and I was serious about the fact that I like the bug report.
My bad, but thanks! 🤣🤣
 
> * there is a bug in Chrome(including Edge) regarding emitting focusout on input type date/time, but it's very strange (details above) - firefox works ok
Yes, I had noticed that it seems to be something from chrome / chromium, I was hoping it wouldn't be that ... 😓

> * for QSelect with rules I'm sure is something bad in our code
Thanks for your help!

**Comment by pdanpdan** [comment]
Ok, it's a bug from chrome, but something more strange that I expected. See the PR code.
About the QSelect - it's not really a bug but a bad decision to use `--focused` class both when the field is focused and when it has error. In your case it was the only field with label.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.14.8
