### ISSUE TITLE
QTable: Header classes added twice

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#8205]
**Describe the bug**
Adding header classes to a column adds them twice.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dwarfhq/pen/abmJLzv?editors=101

**To Reproduce**
1. Add `headerClasses` to a column
2. See that they're added twice

**Expected behavior**
Additional header classes should only be added once.

**Screenshots**
It's easy to see when inspecting the codepen.

**Platform (please complete the following information):**
Quasar: 1.14.7

**Additional context**
It doesn't break anything, it's just odd.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.14.8.
