### ISSUE TITLE
Need a function for disabling ScrollArea component

### ISSUE THREAD

**Issue by saifobeidat** [quasarframework/quasar#8207]
**Is your feature request related to a problem? Please describe.**
I am currently using the [ScrollArea ](https://quasar.dev/vue-components/scroll-area)component, I want to disable it on small screens, I didn't find a function to do that in the docs.

**Describe the solution you'd like**
Add `destroy `function , so it would be flexible to either have a scroll on certain screens or not

**Describe alternatives you've considered**
I am going to disable the ScrollArea using custom CSS where it will override Quasar's style.

**Comment by pdanpdan** [comment]
I don't understand what you need.
You can use the `screen` plugin to chose different ways to show your content.
Please describe what you want to do and you cannot, a codepen would help also.

**Comment by saifobeidat** [comment]
@pdanpdan 

if you look at this example [https://codepen.io/saifobiedat/pen/XWjMqRo?editors=101](url), I want to remove the scrollbar in small screens, so what's the way to remove or destroy the scrollbar? is there a function to remove scrollbar once called?

It's simply a function like this `$q.scrollarea.destroy() `

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/xxEqjyx?editors=1010

**Comment by saifobeidat** [comment]
@pdanpdan ScrollArea adds uncontrolable classes such as `absolute` class, where it might break the layout (it did in my case).

![image](https://user-images.githubusercontent.com/24841143/102235627-31506d80-3efb-11eb-870d-c74fdc162bd8.png)

However, I know it can be handled by custom CSS and with some CSS overriding it can be implemented , that's why I suggested to have a destroying function.

**Comment by pdanpdan** [comment]
As I told you, use the screen plugin and render with or without QScrollArea based on the screen size.

**Comment by saifobeidat** [comment]
If I understand correctly what you mean, is this the way you want me to use?

 ```
<!-- With ScrollArea -->
<q-scroll-area v-if="$q.screen.width > 768"
        class="comments-groups"
        :thumb-style="thumbStyle" >
    <!-- Content Here !-->
 </q-scroll-area>

<!-- Without ScrollArea -->
<div v-if="$q.screen.width <= 768"
        class="comments-groups" >
     <!-- Content Here !-->
</div>
```

**Comment by pdanpdan** [comment]
something like that, it doesn't make sens to render a component and try to fight against it

**Comment by saifobeidat** [comment]
I probably will go with this way although it has a caveat which is I have to add/edit my code in two places when needed, so this can be more and more harder if I have a lot of lines of codes between the scroll-area tags.

Thanks for your comments!

**Comment by pdanpdan** [comment]
You put that part in a component and render that component in the right place
