### ISSUE TITLE
[typescript] Missing definition for Platform.parseSSR

### ISSUE THREAD

**Issue by rulrok** [quasarframework/quasar#8209]
**Describe the bug**
`Platform.parseSSR` is not strongly typed yet `Cookies.parseSSR` has its typescript definition.

**Screenshots**
![image](https://user-images.githubusercontent.com/3097987/102235044-ae1a2200-3ed0-11eb-87e9-75f72374d003.png)

**Platform (please complete the following information):**
OS: Manjaro Linux
Node: 15.0.1
NPM: 6.14.9
Yarn: ---
Browsers: ---
iOS: ---
Android: ---
Electron: ---

**Comment by IlCallo** [comment]
Seems like `plugin/Platform.json` just missed this method all along :thinking: 
Adding it right now
