### ISSUE TITLE
[Request] Allow data table 'field' to come from deeper than top level of data object.

### ISSUE THREAD

**Issue by kastork** [quasarframework/quasar#821]
Sometimes data coming from the server that you want to display as a data table is not flat.

```
data () {
 return {
   tableData: [
     { 
         id: 1,
         name: 'fred',
         boss: {
            id: 2,
            name: 'bossman'
         }
      },
 ...
]
```

Now, in a column configuration, there's no way to identify boss.name as the data for a column. i.e., something like,

```
id   name   bossName
--  -----   --------
1   fred     bossman
```   

The work-arounds I can think of:

1. Change the shape of what comes from the server (you might not have control of the server, so this one isn't always available).

2. Flatten the data by using a computed property to transform the hierarchical structure to a flat one.  This isn't so bad, but is probably not a great idea when the data set starts getting large.

```
import _ from 'lodash

tableData: function () {
     return _.map(this.employees, (employee) => {
       return {id: employee.id, name: employee.name, bossName: employee.boss.name}
     })
  }
```

This seems to work at first blush, but I'm not certain it would hold up in all the data table use-cases like changing the sort or applying filters.

Perhaps it could look like,

```
columns: [
   {
      label: 'bossName',
      field: 'boss.name',
...
```

I'd also be satisfied with a workaround that didn't involve duplication of the entire data source array.  Perhaps one exists using a function in place of the field name, but I can't think of it.

**Comment by kastork** [comment]
Another workaround, even solution, perhaps...

3. Use a transformer when fetching the data.

This came from the MAPT video course by Peter van Meijgaard
https://www.packtpub.com/mapt/video/web_development/9781788291613

```
class BaseTransformer {
  static fetchCollection (items) {
    return items.map(item => this.fetch(item))
  }

  static sendCollection (items) {
    return items.map(item => this.send(item))
  }
}
```

```
class EmployeeTransformer extends BaseTransformer {
  static fetch(employee) {
    return {
      id: employee.id,
      name: employee.name,
      bossId: employee.boss.id,
      bossName: employee.boss.name
    }
  }
  static send(employee) {
    // ...
  }
}
```

Then in the API call, filter the fetched data through the transformer before putting it into the vuex store.

```
// in vuex store actions...

export const list = ({commit}) => {
  proxy.list()
    .then((response) => {
      const data = {
        employees: EmployeeTransformer.fetchCollection(response)
      }
      commit(types.RECEIVE_EMPLOYEES, data)
    })
}

```

**Comment by rstoenescu** [comment]
Will make this possible with the revamp of QDataTable

**Comment by rstoenescu** [comment]
This will be part of the QDataTable revamp.

**Comment by flesser** [comment]
Another workaround, currently used by me:

4. Render cell with a component.
```vue
<q-data-table :data="tableData" ...>
  <template slot="col-boss" scope="cell">
    <span>{{ cell.data.name }}</span>
  </template>
</q-data-table>
```

**Comment by rstoenescu** [comment]
Closing as code is ready in v0.15 datatable revamp.

**Comment by smolinari** [comment]
Just to update this so everyone is clear what now can be done now, should you land here wondering what to do.

Use `val => val.some.nested.value` in your `field` property for the column. So, for Kirk's example above, it would be:

```
columns: [
   {
      label: 'bossName',
      name: 'The Boss'
      field: boss => boss.name,
...
```

Scott

**Comment by stefanvanherwijnen** [comment]
I believe it should be:
`field: row => row.boss.name,`

This will return 'bossman' instead of 'fred'.

**Comment by smolinari** [comment]
@stefanvanherwijnen - Correct! I was testing to see if anyone was awake! You passed! LOL! :)

Just kidding. 

Here is a fiddle to show it correctly. 

https://jsfiddle.net/smolinari/g7vj091a/

Scott

**Comment by stefanvanherwijnen** [comment]
Any clue how I can set the nested property dynamically?
If I set:
`field: row => row[variable]`
The field variable is set to:
`function field(row) { return row[variable]`
Where as it should be the value (string) of the variable (so if variable is 'boss', it should be return row['boss']).

**Comment by stefanvanherwijnen** [comment]
Thanks.
You are right, it seems to be impossible without using eval() or new Function().
What works is this:
`var func = new Function('return function field(row){ return row[\'' + variable + '\']}')`
`field: func()`

However, ESLint tells you not to use new Function so you have to set `'no-new-func': 0`.

... I have just tried setting `field: variable` again and it now seems to work fine :sob: .
I think the key is to set the Object as the field variable and use custom QTr and QTd to extract the values out of the nested object.

**Comment by sachingk** [comment]
I ended up getting  following error when I use field: row => row.createdBy.email

[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

My code looks like as below 

```
columns: [
   {
      label: 'createdBy',
      name: 'The Boss'.
      field:  row =>row.createdBy.email  

```
My data comes dynamically from DB and it is getting the data correctly. 

Please help with this.

**Comment by kastork** [comment]
@sachingk  This sounds like a standard vue iteration warning -- what are you using for the :key in the  v-for loop that defines your columns?

**Comment by hawkeye64** [comment]
@sachingk Based on the vue warning, your email is either object or array

**Comment by sachingk** [comment]
You are right.

I fixed my for loop. Now it works fine.
