### ISSUE TITLE
QUploader - removeFile of already uploaded file don't recompute total size

### ISSUE THREAD

**Issue by NPi2Loup** [quasarframework/quasar#8216]
**Is your feature request related to a problem? Please describe.**
We use quasar in the UMD/Standalone (Unified Module Definition) version.
We use the QUploader like there is an auto synchro with server side.
So when we pickup file it's auto uploaded (we have a POST endpoint)
And when we remove it (the done icon) we send a DELETE to server

It work well **BUT** the total size isn't recomputed, and is inaccurate.

**Describe the solution you'd like**
We need two things :

- params to change icons : we need *remove-like* icons
- method to recompute total size

**Describe alternatives you've considered**
Maybe a full support of a behaviour  where file state is kept server side, should be top :)

**Others elements**
Usage 
```XML
<q-uploader url="/upload"
	field-name="file"
	auto-upload
	auto-expand
	ref="myComponentId"	
	@removed="uploader_removeFiles($event, 'myComponentId')|"
></q-uploader>
```
script:
```JavaScript
uploader_removeFiles: function (removedFiles, componentId) {
        let componentStates = this.$data.componentStates;
        removedFiles.forEach(function (removedFile) {
            var component = this.$refs[componentId];
            var xhrParams = {};
            xhrParams[component.fieldName] = removedFile.fileUri;
            this.$http.delete(component.url, { params: xhrParams, credentials: component.withCredentials })
                .then(function (/*response*/) { //Ok
                    componentFileUris.splice(0);
                }.bind(this))
                .catch(function (error) { //Ko
                    this.$q.notify(error.response.status + ":" + error.response.statusText + " Can't remove temporary file");
                }.bind);
        }.bind(this));
```

**We can work on it, if your are fine with this feature**

**Comment by rstoenescu** [comment]
Hi,

The total size reflects what is "to be uploaded". It does not includes uploaded resources.

**Comment by NPi2Loup** [comment]
So it's weird because the total size keep the uploaded resources : 
- I add a file, the total size increase
- I upload the file, the total size don't change
- I click on the "done" icon : the size don't change

It works if I don't upload 
- I add a file, the total size increase
- I click on the "delete" icon : the size revert too the old value

**Comment by pazarbasifatih** [comment]
> Hi,
> 
> The total size reflects what is "to be uploaded". It does not includes uploaded resources.

What is to be uploaded keeps going up when you remove the item and add it back.
