### ISSUE TITLE
[Feature] Allow to disable stepper header navigation

### ISSUE THREAD

**Issue by tobiasdierich** [quasarframework/quasar#822]
**Suggestion:**

Allow to disable the ability to jump to already completed steps by clicking on the step in the stepper header.

**Use Case:**

Imagine a stepper where the last step is optional. However, all other steps have to be completed and the data has to be send to the backend in order to get to the last (optional) step. I'd like to prevent the user from going back to already completed steps, since the data has already been send to the backend and can no longer be edited.

Any comments on the suggestion ?

I'd be happy to contribute a PR for this :)

**Comment by rstoenescu** [comment]
Hi.
You are in total control of what the navigation buttons do. Use the disabled prop.

**Comment by tobiasdierich** [comment]
Whoops, I should definitely read the docs/source more carefully. Sorry for wasting your time 😕
