### ISSUE TITLE
Qusar serve index.html cache

### ISSUE THREAD

**Issue by jhmen** [quasarframework/quasar#8221]
**Describe the bug**
When i serve a spa with the quasar serve command the index.html response with the header 
`Cache-Control: public, max-age=86400`

**Codepen/jsFiddle/Codesandbox (required)**
Not possible

**To Reproduce**
1. Create a quasar project
2. Build spa
3. Run SPA with quasar serve
4. Make a get request to index.html or /
5. Check the Cache-Control header

**Expected behavior**
The server should response with `no-cache, no-store, must-revalidate`. (https://quasar.dev/quasar-cli/developing-spa/deploying#Important-Hosting-Configuration)

**Platform (please complete the following information):**
OS: Docker image node:14-alpine
Node: 14

**Comment by pdanpdan** [comment]
Maybe we should either:
- make `index` file be server with `no-cache, no-store, must-revalidate`
- remove the mention about using `quasar serve` for production

> Tip: You can use "$ quasar serve" command to create a web server,
>      both for testing or production. Type "$ quasar serve -h" for
>      parameters. Also, an npm script (usually named "start") can
>      be added for deployment environments.
>      If you're using Vue Router "history" mode, don't forget to
>      specify the "--history" parameter: "$ quasar serve --history"

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/cli" v1.1.3 (remember that this package should be installed globally).
