### ISSUE TITLE
Boot files context problem

### ISSUE THREAD

**Issue by nevadavid** [quasarframework/quasar#8222]
I would like to use in my boot files Vue Router instance in that same way: https://quasar.dev/quasar-cli/boot-files#Router-authentication
But I get this console error message:
`[Quasar] boot error: TypeError: Cannot read property 'beforeEach' of undefined`

When I write the context to console, I don't see router object (or any other props just store and Vue).
```javascript
export default async(
    context,
) => {
    console.log(context);
};
```

![image](https://user-images.githubusercontent.com/816750/102464942-535a0500-404d-11eb-929d-ac2b9c9f961e.png)

**Quasar**: 1.14.3
**Quasar App**: 2.1.6
**Mode**: SPA

**Comment by pdanpdan** [comment]
I don't know how you are using the boot files, but you should have a lot more content in the `context`.
Make a codesandbox with you code and share.

**Comment by nevadavid** [comment]
It was my mistake.
