### ISSUE TITLE
devServer.before will be access two times 

### ISSUE THREAD

**Issue by wowissu** [quasarframework/quasar#8223]
**Describe the bug**
I want add dev only middleware into devServer. I try implement that in devServer.before 
I found before() will be exec twice when serve on.
also my middleware been registered twice.

**Codepen/jsFiddle/Codesandbox (required)**
[before() will be exec two times](https://codesandbox.io/s/dreamy-breeze-r4iqr?file=/quasar.conf.js)

**To Reproduce**
1. Just start dev mode

**Expected behavior**
Only one time exec.

**Screenshots**
<img width="730" alt="Screen Shot 2020-12-17 at 5 03 53 PM" src="https://user-images.githubusercontent.com/12434914/102466375-ec0e7600-4089-11eb-81d5-a02268be144d.png">

<img width="429" alt="Screen Shot 2020-12-17 at 5 03 04 PM" src="https://user-images.githubusercontent.com/12434914/102466255-bec1c800-4089-11eb-8756-e27496fb7b39.png">

<img width="473" alt="Screen Shot 2020-12-17 at 4 56 43 PM" src="https://user-images.githubusercontent.com/12434914/102465666-e95f5100-4088-11eb-8bcf-517fb38983b3.png">

**Platform (please complete the following information):**
Quasar: 1.14.7

**Additional context**
According to doc of [Webpack.devServer.before](https://v4.webpack.js.org/configuration/dev-server/#devserverbefore) the before is provider three parameters.
but quasar only transfer first parameter. and first time and seconed time got differnet arguments
could provider all arguments every times. thanks

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v2.1.12.
