### ISSUE TITLE
QDate : Add possibility for infinite range by dissociating To/From

### ISSUE THREAD

**Issue by GrandOurs35** [quasarframework/quasar#8224]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an improvement who would be really nice. For the QDate, have the possibility to dissociate To/From to be able to choose a fixed (or infinite) begin/end date.

**Describe the solution you'd like**
In my use case, a user can select a date range or if he doesn't know the end date, he can just pick the From. I would like the date range to be endless if possible (by setting null to To/From), and allowing the user to choose only the To or the From. The date range would color according to this.

**Describe alternatives you've considered**
For now, i switch between Single date/Date range according to a switch button but the UI is not very nice.

Thank you very much

**Comment by pdanpdan** [comment]
you can already do this
https://codepen.io/pdanpdan/pen/dypWqYL?editors=1010

**Comment by GrandOurs35** [comment]
Hi,
thank you for your quick answer but i think i expressed myself rather bad :- )
I would like to show on the calendar the infinite date range by coloring all days after the start date (when the user navigates to others months).

So maybe, in this case, would be better to switch to a single date mode (the user does not have this pending date range selection) and when the user pick a date, automatically color all the days after (or before) his selection.
Do you think that something possible?

**Comment by pdanpdan** [comment]
You can pick a large enough value for the `to` part (same codepen, updated)

**Comment by GrandOurs35** [comment]
thanks a lot for your help, i had tried this before but i was not very satisfied with the UX because you still have this pending date range selection and it's not very neat for the user (in my opinion). Anyway, i will try to manage something. Thanks!
