### ISSUE TITLE
copyToClipboard not working on iOS

### ISSUE THREAD

**Issue by pixankthanh** [quasarframework/quasar#8236]
**Describe the bug**
Some old iOS versions has error when apply copyToClipboard utils. But it's OK with newer versions. It can be related to https://github.com/quasarframework/quasar/issues/6378

**Platform (please complete the following information):**
Browsers: Chrome, Safari
iOS: 12.3.1

**Comment by pdanpdan** [comment]
Can you please provide the error?

**Comment by pdanpdan** [comment]
I'll reopen if more details are added
