### ISSUE TITLE
Forum not available via secure https connection

### ISSUE THREAD

**Issue by wowcut** [quasarframework/quasar#824]
The forum does not seem to be served via https - I can only see not encrypted http.

**Comment by JCharante** [comment]
While factual, this is not an issue with the actual "quasar" framework. While https://github.com/quasarframework/quasar-framework.org is generally for the docs, I'd suggest filing an issue there instead.

**Comment by rstoenescu** [comment]
Hi. @JCharante is right. Thanks.

**Comment by wowcut** [comment]
I just copied the issue content and title to the place you pointed me to.
