### ISSUE TITLE
 SSR mode setting publicPath routing redirection problem

### ISSUE THREAD

**Issue by regchiu** [quasarframework/quasar#8247]
**Describe the bug**
Routing error.

**Codepen/jsFiddle/Codesandbox (required)**
[Codesandbox](https://codesandbox.io/s/quasar-ssr-mode-forked-w409y)

**To Reproduce**
1. Go to `quasar.conf.js` set build > `publicPath: '/app'` and `vueRouterBase: '/app'`
2. Go to `/router/routes.js` as fllows.
```js
{
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    redirect: { name: 'index' },
    children: [
      {
        path: 'index',
        name: 'index',
        component: () => import('pages/Index.vue')
      }
    ]
  },
```
3. Browser URL input 'App URL'. (e.x. http://localhost:8080/app/)

**Expected behavior**
It should be redirected to the correct page as some as SPA mode.

**Screenshots**

**Platform (please complete the following information):**
OS: Windows 10
Node:
NPM:
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
Maybe it is not recommended to change `publicPath` in SSR mode?

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v2.1.14
