### ISSUE TITLE
QUploader - removeUploadedFiles don't emit 'removed' event

### ISSUE THREAD

**Issue by NPi2Loup** [quasarframework/quasar#8248]
**Describe the bug**
In QUploader for pending files : 
- click on one file (clear icon) : event 'removed' is send
- click on the icon in header (clear_all icon) : event 'removed' is send

In QUploader for already uploader files: 
- click on one file (done icon) : event 'removed' is send
- click on the icon in header (done_all icon) : no event is send

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/npi2loup/pen/jOMLvKy
(Need a backend for test)

**To Reproduce**
- Add a file to uploader
- Click upload button
- When upload is done, the icon change to done_all
- Click 'done_all' icon in the header
- No 'removed' event send

**Expected behavior**
- Add a file to uploader
- Click upload button
- When upload is done, the icon change to done_all
- Click 'done_all' icon in the header
- A 'removed' event send with all files removed

**Screenshots**

**Platform (please complete the following information):**
OS: Win10
Quasar : 1.14.7
Browsers: Chrome  87.0.4280.88

**Additional context**
Actually there is two type of actions : 
- clear file in upload queue
- clear uploaded file

We need the same events when we clear them one by one or all at once.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.0
