### ISSUE TITLE
Horizontal QStepper pagination

### ISSUE THREAD

**Issue by CopperGiraffe** [quasarframework/quasar#8249]
**Is your feature request related to a problem? Please describe.**
The QStepper has a strange behaviour when it has to many steps (wrap on two lines for example, is not ideal)

**Describe the solution you'd like**
It would be nice to have pagination, like in the carousel, but for the QStepper

**Additional context**
Something a bit like that (don’t mind the numbers):
![image](https://user-images.githubusercontent.com/8639751/102877123-897cf780-4446-11eb-9567-66e2e2b6c41a.png)

**Comment by pdanpdan** [comment]
You can use `alternative-labels` or `contracted` or use a vertical stepper if you have too many steps.
Or if you really want you can try something like this https://codepen.io/pdanpdan/pen/QWKqbZm?editors=1010
But a stepper with so many steps that cannot fir the screen is not good :)
