### ISSUE TITLE
How to stop load in the next page?

### ISSUE THREAD

**Issue by dishcheng** [quasarframework/quasar#8253]
In the page A,I set q-infinite-scroll component and keep-alive , and I pressed the button to the page B. At page B,when I scroll to footer,I trigger the A page's load function. How can I stop this, support like infinite-scroll-disabled?

layout.vue
![image](https://user-images.githubusercontent.com/26062252/102954999-daa4ee00-450f-11eb-9629-aab826e07c6d.png)

router set
![image](https://user-images.githubusercontent.com/26062252/102954986-d4167680-450f-11eb-98be-6d15cf388972.png)

page A
![image](https://user-images.githubusercontent.com/26062252/102955046-fad4ad00-450f-11eb-8cbc-2ca50dcafdfb.png)

**Comment by metalsadman** [comment]
@dishcheng  please use quasar's discord channel or forums for questions. QInfiniteScroll api offers some methods to control its behavior https://quasar.dev/vue-components/infinite-scroll#QInfiniteScroll-API > `METHODS` tab.
