### ISSUE TITLE
Type of number in <q-input> is not working as expected

### ISSUE THREAD

**Issue by b02505048** [quasarframework/quasar#8254]
**Describe the bug**
`<q-input type="number" v-model="number" />` does allow alphabetic input. 
e.g. Only `e` is allowed in Chrome, every alphabets like`kasjiqejansd` are welcome in Safari. 🙃 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Adriantango/pen/MWjEogZ

**To Reproduce**
`<q-input type="number" v-model="number" />` is more than enough to reproduce the magic.

**Expected behavior**
Only numeric input are allowed.

**Comment by pdanpdan** [comment]
Hello. Please open an issue on Apple/safari.

**Comment by b02505048** [comment]
@pdanpdan Hello, then how about the Chrome issue since the `e` is allowed? 🤔

**Comment by pdanpdan** [comment]
e is exponential and it is allowed
2.5e2 = 250
