### ISSUE TITLE
Regression in 1.13.1 (1.13.0?) in validating form fields on submit

### ISSUE THREAD

**Issue by jippeholwerda** [quasarframework/quasar#8256]
**Describe the bug**
I have a form in a dialog. The form contains multiple fields having validation rules (e.g. some are mandatory). Since 1.13.1 (probably 1.13.0 introducted the problem, but because of errors in QRouteTab which have been fixed in 1.13.1 I could not get the app to run in 1.13.0), when pressing the submit q-button in the greedy q-form, the validation is not triggered and the submit action of the form is called.

Also, when setting the focus on a mandatory field and submitting the form, only the validation of that field is trigger. I would expect that all field validations would be triggered, since the form is greedy.

**Codepen/jsFiddle/Codesandbox (required)**
I've tried to reproduce the issue in a Codepen (https://codepen.io/jippeh/pen/YzGrYJB), but unfortunately I could not.

**To Reproduce**
See the attached screencasts.

**Expected behavior**
I would expect the submit button to trigger all formfield validations greedily.

**Screenshots**

https://user-images.githubusercontent.com/117410/102996489-8277e700-4523-11eb-8c02-4c4f296764ac.mp4

https://user-images.githubusercontent.com/117410/102996501-8572d780-4523-11eb-9f91-6416219fbbd9.mp4

**Platform (please complete the following information):**
OS: Ubuntu 20.04
Node: 15.4.0
NPM: 7.0.15
Yarn: - 
Browsers: latest Chrome and Firefox
iOS: -
Android: -
Electron: -

**Additional context**
The problem does not occur in Quasar version 1.12.13. It still occurs in version 1.14.7.

**Comment by pdanpdan** [comment]
Are your fields wrappers over QInput/QSelect/QField? Or are they wrapped in other elements?
Then see here: https://github.com/quasarframework/quasar/issues/8173

**Comment by jippeholwerda** [comment]
They are indeed wrapped. Fixed by implementing `validate` and `resetValidation` methods and delegating to the wrapped Quasar components.

Thanks for your help!
