### ISSUE TITLE
Can you support iconfont（http://iconfont.cn）?

### ISSUE THREAD

**Issue by likecao** [quasarframework/quasar#826]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What were you expecting?

I am a Chinese developer and I use the iconfont(http://iconfont.cn) online management project icons. It really works.Now the use of Toast and Alert is not normal. Can you provide support or provide custom options?

**Comment by rstoenescu** [comment]
Hi,

Are these free? If they are not then it's troublesome.
Anyway, need to understand more of how iconfont.ch works. How does a downloaded set of icons look like. How do the owners tell you to use them?

Can you supply this information pls?

**Comment by smolinari** [comment]
Is there possibly a way to make an icon set configurable? I mean make it configurable, so that not every font set on the Internet becomes a request to be added to Quasar, but rather let userland add the set themselves somehow through configuration?

Scott

**Comment by rstoenescu** [comment]
@smolinari wish that could be possible, but every set has its distinctive way of using it, so not really possible.

**Comment by smolinari** [comment]
Hmm... that is too bad. 

Scott

**Comment by rstoenescu** [comment]
Please reopen with the details above. Thanks!
