### ISSUE TITLE
QSelect persistent popup and input text

### ISSUE THREAD

**Issue by edwillys** [quasarframework/quasar#8262]
**Is your feature request related to a problem? Please describe.**
I would like QSelect to be able to behave like an input autocomplete. I have currently two problems:
1. Whenever I click outside of the input field the input text is lost and the popup disappears. 
2. If I click on the input the current text remains, but the pop is hidden until I click on it again. This is especially frustrating if I want to click in the middle on the entry to modify a character while being able to visually track the popup.

**Describe the solution you'd like**
To mitigate the disappearing popup, a "persistent" prop to QSelect could be one idea. Similar to what already exists for QMenu. 
As for the input text disappearing when clicking outside the input field, there could be another prop: "input-persistent".

**Describe alternatives you've considered**
For issue 2. there is (almost) a workaround: to force the popup to show upon click (check stackoverflow link below). The inconvenience is that the popup still shortly disappears for a short while before showing again.
For issue number 1 I haven't got any ideas yet-

**Additional context**
See [thread](https://stackoverflow.com/questions/65382475/quasar-qselect-popup-and-input-text-persistent-on-click) on stackoverflow. Code Pen is also referenced there and [here](https://codepen.io/edwillys/pen/bGwraYE?editors=1010) again for consistency.

**Comment by pdanpdan** [comment]
1. I think you even have an example in the docs: https://quasar.dev/vue-components/select#Example--Text-autocomplete
2. You have to play a little with the click event to keep the menu open, but it's not so difficult: https://codepen.io/pdanpdan/pen/YzGEygr?editors=1010

**Comment by edwillys** [comment]
@pdanpdan I am aware of this example on the official doc. Both of the problems stated above are present in this example. Moreover, they are still present in your Code Pen: when I click on the input, the popup closes. Same happens when I click outside it. I updated it so that the QApp takes the whole vertical space and you can easily reproduce it: https://codepen.io/edwillys/pen/zYKPoBj 
One aspect is indeed solved: the entry no longer clears when you click outside. I wouldn't consider the issue as solved yet.

**Comment by pdanpdan** [comment]
I appologize if I didn't understand what you meant:
> 1. Whenever I click outside of the input field the input text is lost and the popup disappears.
> 2. If I click on the input the current text remains, but the pop is hidden until I click on it again. This is especially frustrating if I want to click in the middle on the entry to modify a character while being able to visually track the popup.

So I understand that both of this are not resolved, except that the text is kept and the popup is not closed :)

**Comment by edwillys** [comment]
Exactly :)

**Comment by pdanpdan** [comment]
I really meant it. Except not closing on click outside (which I don't agree with) what is missing?

**Comment by edwillys** [comment]
If you click on the input field, the popup toggles instead of remaining active. This is particularly annoying if you want to change the cursor position while keeping an eye on the pop up. See the video below:

https://user-images.githubusercontent.com/1780037/103141041-0205e180-46ef-11eb-821f-795685dc71e1.mp4

**Comment by pdanpdan** [comment]
On the codepen I posted as answer to 2?

**Comment by edwillys** [comment]
Video is based on the Pen I adapted from yours, in which I extended QApp to the whole vertical space: https://codepen.io/edwillys/pen/zYKPoBj
The behavior is the same on the Pen you posted.

**Comment by pdanpdan** [comment]
Sorry, it looks like the event prop is called somehow different on firefox - I just changed it to not close on click on arrow also
https://codepen.io/pdanpdan/pen/JjROyNy?editors=1010

It can be fixed, but it would require a little check on browsers compatibility.

**Comment by edwillys** [comment]
I could agree that the popup persistence when clicking outside the input field is a particularity of my use case.
On the other hand, its persistence when clicking **on** the input field (not on the arrow, as the arrow itself is hidden in my case, see my codepen) is the expected behavior of an autocomplete input. QSelect proposes to fulfill that feature. 
I'm sorry, but your codepen is still not working, not for Chrome, not for Firefox.

**Comment by edwillys** [comment]
Ok, I figured it out and simplified the conditions a bit. It is working now on my [pen](https://codepen.io/edwillys/pen/bGwraYE?editors=1010).
One last remark: can't you foresee any side effects by manually setting the model at each new input value? Usually it is only updated when the user clicks on one of the options, but now it is done this way so that it doesn't disappear when clicking outside of the input field.

**Comment by rraghees** [comment]
@pdanpdan @TobyMosque , I am facing the same issue of persisting input text when using q-select for multiple options. Above example works when model-value consist of single value but in my case my model-value is array and I don't want to update model-value based on input-value so they should be independent and I want to have input-value persistent when clicking outside of the input field.

**Comment by rraghees** [comment]
@rstoenescu @pdanpdan @hawkeye64  Is their any solution to that?
