### ISSUE TITLE
initialValue change for QpopUpEdit method

### ISSUE THREAD

**Issue by mila76** [quasarframework/quasar#8264]
**Is your feature request related to a problem? Please describe.**
I'm working on a reusable QpopupEdit for many cells (for performance reason).
If i edit one cell and edit another the initialValue is not resetted. I need a method or other tips for reset this initialValue programmatically.
Example here:
https://jsfiddle.net/xemyc427/11/

**Describe the solution you'd like**
A method to change the initialValue

**Comment by mila76** [comment]
Direct update after show method, using refs, can change initialValue,
For now seems ok.
Maybe adding another parameter on the show method?

**Comment by pdanpdan** [comment]
I suppose you want something like this: https://jsfiddle.net/dqhuLvty/25/
Watch out for `no-parent-event` - else the popup it bound to main div element.
And use computed get/set, it's easier to reason about.

**Comment by mila76** [comment]
Thanks for the hint on this.. your version is much better but the initialValue remain incorrect

Put 1 on the second. Press Enter. Click on first and you see before = 1 and when the event @save is not fired.
v-model is updated (but on @input bases and is not what i want)

see: https://jsfiddle.net/znLmfyoh

**Comment by pdanpdan** [comment]
Yes, I checked now and you need a tick between setting the edit value and opening the popup.
https://jsfiddle.net/82604f93/9/

**Comment by mila76** [comment]
Thanks again for your work on this ;)
