### ISSUE TITLE
How to use Q-Carousel in 1.1v like Quasar 0.14v

### ISSUE THREAD

**Issue by ukik** [quasarframework/quasar#8266]
https://v0-17.quasar-framework.org/components/carousel.html

https://quasar.dev/vue-components/carousel#Basic

on new version, swipe effect is gone...

swipeable directives on version 1.1 is working diferrent from old version,

**Comment by pdanpdan** [comment]
Please change the title to match the request

**Comment by metalsadman** [comment]
swiping behavior wise, v0.14 has actually better UX than v0.17 or v1 imho. https://v0-14.quasar-framework.org/components/carousel.html

**Comment by pdanpdan** [comment]
Cross reference:
https://github.com/quasarframework/quasar/issues/4714
https://github.com/quasarframework/quasar/issues/4406
https://github.com/quasarframework/quasar/issues/7404
https://github.com/quasarframework/quasar/issues/7795
https://github.com/quasarframework/quasar/issues/8266

**Comment by rstoenescu** [comment]
Sorry but not planning on bringing back the old "full-swipe" behavior. It's incompatible with the current set of features that were requested by the community since v0.14. We can't technically achieve that swipe and all the other features simultaneously without convoluting the code A LOT.
