### ISSUE TITLE
build externals quasar  (use umd cdn) error .

### ISSUE THREAD

**Issue by 625781186** [quasarframework/quasar#8267]
**Describe the bug**
After `npm run build` , can't show text.
![image](https://user-images.githubusercontent.com/30521429/103156626-6905c200-47e5-11eb-9ec9-393c186fd901.png)

![image](https://user-images.githubusercontent.com/30521429/103156454-aec18b00-47e3-11eb-9f82-102bf2d007c9.png)
 
**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/625781186/quasar_externals_bug
[app00.zip](https://github.com/quasarframework/quasar/files/5743456/app00.zip)

**Platform (please complete the following information):**
OS: win10
Node: v12.16.2
NPM: 6.14.4 
Browsers: chrome v86.

**Comment by pdanpdan** [comment]
Can you please describe what you are doing using words?

**Comment by 625781186** [comment]
> Can you please describe what you are doing using words?

Sorry . 

I'm try to use `webpack externals options` build `appp00` project , and import Quasar from CND ,
but `q-btn` can show text `123` when `npm run serve` ,  
and can't show `123` when `npm run build`.

**Comment by pdanpdan** [comment]
Please use the Vue plugin steps here:
https://quasar.dev/start/vue-cli-plugin#Introduction

**Comment by 625781186** [comment]
> Please use the Vue plugin steps here:
> https://quasar.dev/start/vue-cli-plugin#Introduction

@pdanpdan 
Sorry , the same error.

![image](https://user-images.githubusercontent.com/30521429/103171505-d9651f80-4887-11eb-8c58-ff1256f066a0.png)

Or I hope you can directly give me a demo using Externals Quasar and CDN. I have been looking for it for two days, but it doesn't work.

**Comment by pdanpdan** [comment]
I don't know what you are trying to do, but if you use quasar as umd you should refer to the umd section of the docs. And you must have vue available before loading it.

**Comment by 625781186** [comment]
@pdanpdan 

1. without use `externals` : 
The volume of the app : 1.75MB;
![image](https://user-images.githubusercontent.com/30521429/103255045-b3906580-49c2-11eb-94c9-a8d320549c33.png)

2. use `externals`:
The volume of the app : 272kb;
![image](https://user-images.githubusercontent.com/30521429/103255101-fa7e5b00-49c2-11eb-827d-f94b72621a6f.png)

**Comment by 625781186** [comment]
> I don't know what you are trying to do, but if you use quasar as umd you should refer to the umd section of the docs. And you must have vue available before loading it.

My UMD usage is now successful, but the text is not displayed.

![image](https://user-images.githubusercontent.com/30521429/103255341-edae3700-49c3-11eb-97ce-235a36548ab3.png)

**Comment by pdanpdan** [comment]
Have you checked if you have the font?

**Comment by 625781186** [comment]
> Have you checked if you have the font?

I don't think it was the font.

1. the umd section of the docs. 
![image](https://user-images.githubusercontent.com/30521429/103288705-7a86de00-4a20-11eb-9e47-26cdcaea24ee.png)

2. externals test.
![image](https://user-images.githubusercontent.com/30521429/103288837-c5a0f100-4a20-11eb-88c1-15cf9ab1dd42.png)

This is how it's rendered in the app.js .
![image](https://user-images.githubusercontent.com/30521429/103288933-f97c1680-4a20-11eb-91cc-49446f3774ba.png)

So , I think you can try it yourself . https://github.com/625781186/quasar_externals_bug

**Comment by pdanpdan** [comment]
It looks like you have to use template elements for default slots:

```html
<q-btn>
  <template v-slot>123</template>
</q-btn>
```

**Comment by 625781186** [comment]
> It looks like you have to use template elements for default slots:
> 
> ```
> <q-btn>
>   <template v-slot>123</template>
> </q-btn>
> ```

But I didn't actually do that.

https://github.com/625781186/quasar_externals_bug/blob/master/src/App.vue#L5

**Comment by 625781186** [comment]
@pdanpdan 
Hi , Can the issue be reopened?  I still think this is a bug.

**Comment by pdanpdan** [comment]
It's related to how your configuration passes (does not pass) the content of the element as default slot to Quasar component.
