### ISSUE TITLE
Some pixels in QCard corners show the color of the card instead of the image

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#8273]
**Describe the bug**
When using QCard with an image, some pixels from the card are showing in the corners of the image.
This is noticeable e.g. when the image is white and the card is red, as in the following example:

![image](https://user-images.githubusercontent.com/83443/103208629-ce52d380-4909-11eb-8354-b736ca9b221e.png)

![image](https://user-images.githubusercontent.com/83443/103208496-72884a80-4909-11eb-80fe-746a801f9212.png)

**To Reproduce**
```
<!--
  Forked from:
  https://quasar.dev/vue-components/card#Example--Cards-with-media-content
-->
<div id="q-app">
  <div class="q-pa-md row items-start q-gutter-md">
    <q-card class="bg-negative" style="max-width: 200px">
      <img src="https://www.wallpaperbetter.com/wallpaper/471/516/832/apple-logo-white-background-2K-wallpaper.jpg">

      <q-card-section>
        <div class="text-h6">Our Changing Planet</div>
        <div class="text-subtitle2">by John Doe</div>
      </q-card-section>

      <q-card-section class="q-pt-none">
        lorem ipsum
      </q-card-section>
    </q-card>
  </div>
</div>
```

**Comment by pdanpdan** [comment]
Please make a codepen with the reproduction code.

**Comment by tomers** [comment]
https://codepen.io/tomers-the-encoder/pen/oNzpwLv?editors=111

**Comment by pdanpdan** [comment]
Hello. There is nothing that can be done al framework level - these are rendering glitches due to the way circles are mapped to square pixels.

You can workaround the problem by:
- using a smaller border radius on the image
- using the bg color only on the sections and not on the card

https://codepen.io/pdanpdan/pen/JjRMJQG?editors=1010
