### ISSUE TITLE
Quasar/CLI wird info about new version and other version installed on update

### ISSUE THREAD

**Issue by Mausino** [quasarframework/quasar#8274]
**Describe the bug**
I looked on version of quasar version  (look on screenshot) and it showed me that is available version 1.1.2 but installed me version 1.1.3

Why did not showed that the latest version is 1.1.3 ??? 

![Snímka obrazovky z 2020-12-28 20-09-33](https://user-images.githubusercontent.com/5773777/103237728-cebe8f00-4948-11eb-845a-2f6274b8bcae.png)

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
Look on screenshot

**Expected behavior**
Show the latest version

**Platform (please complete the following information):**
OS: Linux Ubuntu 18.04
IDE: PHPStorm 2020.3

**Comment by pdanpdan** [comment]
That was the version that npm/yarn reported. It's nothing that we can do.

**Comment by rstoenescu** [comment]
Verify if you globally installed "@quasar/cli" with npm or yarn, and upgrade it with the same tool.

**Comment by Mausino** [comment]
@pdanpdan @rstoenescu thank you for your answer and your time.. :yarn:  sometimes wird things hapend in dev world :+1:
