### ISSUE TITLE
Option to read the documentation in Dark mode

### ISSUE THREAD

**Issue by Mausino** [quasarframework/quasar#8275]
**Is your feature request related to a problem? Please describe.**

In the quasar we have dark mode.. now i also write the feature request in github in dark mode..
Why we dont apply what we have also on documentation :1st_place_medal: 

![Snímka obrazovky z 2020-12-29 02-47-40](https://user-images.githubusercontent.com/5773777/103253207-773c1580-4980-11eb-8a8c-e2083ebc6a4e.png)

**Comment by rstoenescu** [comment]
We are currently planning on revamping the docs. They will include dark mode also.
