### ISSUE TITLE
Quasar QTable with Composite row-key

### ISSUE THREAD

**Issue by jmriyaz84** [quasarframework/quasar#8277]
Dear Team , 
My Data Structure is like 
  {
          line: "1",
          room:"A"
          section: "1",
          status: "in_progress",
          value1: 7000,
          value2: 1000,
          quantity: 1 
        }
here I want to give composite key as row-key , because single column is not unique here , so in quasar table I want to give row-key like "line+room+section"

<q-table
          row-key="line+room+section"
          :rows-per-page-options="[0]"
          :data="data"
          hide-bottom
          virtual-scroll
          flat
          bordered
        >

Please guide how I can do this .

**Comment by pdanpdan** [comment]
Hello. Please use the discord channel or the forum for help requests.
