### ISSUE TITLE
Internationalization for Q-Input with type="date"

### ISSUE THREAD

**Issue by brianjpetersen** [quasarframework/quasar#8278]
**Describe the bug**
Q-Input with type="date" ignores internationalization of Quasar’s own components (https://quasar.dev/options/quasar-language-packs). 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/brianjpetersen/pen/ExgQeOy

**To Reproduce**
1. Create app with q-input with type="date"
2. Attempt to internationalize
3. Observe lack q-input with type="date" not updating

**Expected behavior**
It would be preferred if q-input component labels were responsive to internationalization settings similar to q-date component 

**Screenshots**
![image](https://user-images.githubusercontent.com/2500718/103422637-7b2e8a00-4b70-11eb-8439-1734bf2346c8.png)

**Platform (please complete the following information):**
    Pkg quasar........ v1.14.7
    Pkg @quasar/app... v2.1.13

**Comment by pdanpdan** [comment]
Hello. I hope you do realize that input type="date" is implemented by the browser.

**Comment by brianjpetersen** [comment]
I did not. Thanks for educating and sorry to bother.
