### ISSUE TITLE
[Request] "Select all" option for multiselect

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#828]
Title^

**Comment by fscardua** [comment]
+1

**Comment by igorgo** [comment]
+1 and even more... The "Clear all" option would be useful too.

**Comment by panstromek** [comment]
Current solution in userland: https://jsfiddle.net/waugrryy/5759/

**Comment by olegvakulenko** [comment]
IMHO, if add this option, it could be property "select-all" (or something similar) and icon like

https://fontawesome.com/icons/check-double?style=solid

or `done_all` in Material Desing icon.
But, will not it look too complicated with three icons (`select all`, `clear`, `open popover`)?

**Comment by pdanpdan** [comment]
This can be done now in v1.1.0 using slots (either the before/after or before-list/after-list) where you can put the UI for selecting/deselecting/toggling/...
