### ISSUE TITLE
.q-separator should have min-height / min-width

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#8280]
### Current behaviour:

**case:** when using flexbox + in a tight situation (not all content fits the flexbox)
**result:** because `.q-separator` is only 1px wide/high, **flexbox usually squishes it to 0px**

### Desired behaviour:

I believe, since a QSeparator is usually used as a 1px wide/high line between elements, in a tight flexbox situation, this is not an element we want to see squished to 0px and disappear...

**fix:** for this reason above, I believe, it's better to add min-height / min-width to the `.q-separator` which prevents this

So my suggestion is to add:
```sass
.q-separator--horizontal
  min-height: 1px
.q-separator--vertical
  min-width: 1px
```

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.1
