### ISSUE TITLE
Icongenie: Specify an output folder

### ISSUE THREAD

**Issue by robert-hanuschke** [quasarframework/quasar#8281]
**Is your feature request related to a problem? Please describe.**
I was trying to deploy a PWA on one of my hosted webspaces. While the upload worked fine, the PWA never did as it couldn't load the icons. Turns out, some webhosters do not allow using your own root level "icons" folder as they have it reserved for file listing if you're browsing your webspace from the admin panel as the support of mine explained.

**Describe the solution you'd like**
An additional parameter for icongenie to have a non-"icons" folder for your icons in case you use one of those webhosters where the standard is impossible.

**Describe alternatives you've considered**
For this once, it was easy enough to modify index.template.html an quasar.conf to point all occurrences of "icons/" to "app-icons/" and rename the folder accordingly - but now "icongenie verify" does not work any more as it is hardcoded to "icons/" and if I ever modify my icons and want to "icongenie generate" again, it's going to be a cumbersome process.

**Additional context**
Even if this will not be implemented, I hope manually working around the issue will always be possible also in future versions, otherwise Quasar will not be usable in many situations depending on your hosting provider.

**Comment by rstoenescu** [comment]
Hi,

This is already possible. You can create a custom profile file which has all the internal list of resources:

```
# supplying assets based on Icon Genie's internal list
$ icongenie profile -o <filename> --assets all
```

Then you can edit the paths with a search & replace.
Then you can generate the resources using the custom profile file. And also verify using it.

```
$ icongenie generate -p <path_to_filename.json>
$ icongenie verify -p <path_to_filename.json>
```
