### ISSUE TITLE
Improving SEO and meta tag load times for a Quasar SPA

### ISSUE THREAD

**Issue by lllDMDlll** [quasarframework/quasar#8282]
My website is a single page app built using Quasar where almost every page is dynamically rendered. Users create new notes and these notes are loaded for viewing in a Vue component by querying our cloud database and distributed storage network. Each time a note is loaded, it creates a new 'page' which is a url pointing to the display component with dynamic segments (i.e. view/:type/:id). On each of these display pages, I have meta tags using the Quasar Meta plugin that are dynamically populated based on the database or store query. 

**The issue is that these pages do not load fast enough for Google to pick up the meta tags since it must wait for the database query.**

Is there an easy way to improve this, or an alternate method to improve SEO for a single page Quasar app? I am trying to avoid SSR just because of how my app is currently built, but if that is the only option I will rebuild it to use SSR.

**Comment by pdanpdan** [comment]
Hello. Please use the discord channel or the forum for help requests.

**Comment by rstoenescu** [comment]
If you want SEO you need to pick SSR.
