### ISSUE TITLE
QSelect not showing options

### ISSUE THREAD

**Issue by Kylyi** [quasarframework/quasar#8283]
**Describe the bug**
In some cases, when using QSelect with use-input and filters, after filtering and removing the filter (via backspace), the options list is missing some rows.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Kylyi/pen/wvzmorb?editors=1011

**To Reproduce**

**First case**
1. Click QSelect and type in "John" (everything is fine here)
2. Remove "John" via backspace
3. See options list - it's missing last 2 options even though the options array is filtered correctly

**Second case:**
1. Click QSelect and type in "John" (everything is fine here)
2. Defocus QSelect
3. Focus QSelect

**Expected behavior**
Should display all possible options

**Additional context**
If you go from filtering "john" to just "j" to "", it works fine

**Comment by pdanpdan** [comment]
You are calling update multiple times in your filter function.

**Comment by Kylyi** [comment]
Badly copied code, sorry.

Check now please.

**Comment by pdanpdan** [comment]
You have multiple elements in the QSelect option template. The ones after the first one need a `q-virtual-scroll--with-prev` class.

https://codepen.io/pdanpdan/pen/JjRLWYP?editors=1011

I'll leave this open as it is missing from the documentation for QSelect (it's only present in QVirtualScroll)

**Comment by rstoenescu** [comment]
Doc update will be available on next deployment.
