### ISSUE TITLE
Qlayout

### ISSUE THREAD

**Issue by ghf1990525** [quasarframework/quasar#8287]
Scrollbarwidth = 0 in qlayout, but it may be the problem of the browser, leading to the page layout dislocation! So how to deal with this situation?

**Comment by pdanpdan** [comment]
Hello. Please write a note clear description of the problem in english.

**Comment by ghf1990525** [comment]
<img width="883" alt="企业微信截图_16097502821830" src="https://user-images.githubusercontent.com/24802764/103518114-2495b880-4eae-11eb-95a6-91ccac49cb9f.png">

**Comment by ghf1990525** [comment]
<img width="73" alt="企业微信截图_16097507941799" src="https://user-images.githubusercontent.com/24802764/103518217-53ac2a00-4eae-11eb-8da6-3cf3edd3ab47.png">

**Comment by ghf1990525** [comment]
<img width="574" alt="issue" src="https://user-images.githubusercontent.com/24802764/103530395-4e58da80-4ec2-11eb-84a5-942880e53287.png">

**Comment by ghf1990525** [comment]
The problem is that when you open a qdialog with width = 100vw and height = 100vh on a page with a scroll bar, you will go to the red box in the figure above, resulting in a scroll bar no matter what!

**Comment by ghf1990525** [comment]
I want to know what the meaning of this code is?

**Comment by pdanpdan** [comment]
Please, a small codepen to show the problem would help.

**Comment by pdanpdan** [comment]
We'll reopen if we have a reproduction codepen to understand what we should check for.
