### ISSUE TITLE
QEditor | Error in render: "TypeError: Cannot read property 'type' of undefined"

### ISSUE THREAD

**Issue by abelardolg** [quasarframework/quasar#8289]
**Describe the bug**
The message `[Vue warn]: Error in render: "TypeError: Cannot read property 'type' of undefined"` is displayed when I refresh the browser while I was customizing your editor component.

**Codepen/jsFiddle/Codesandbox (required)**
Sorry, but I only created this GIST --> https://gist.github.com/abelardolg/ce86c8635db114b869efdb23963b0528

**To Reproduce**
1.quasar create hello-quasar
2. cd hello-quasar
3. quasar-dev
4. Add your qeditor component and add it some buttons (see the above gist).
5. I created a new file ("CrearRecurso.vue") and I added into it the `<q-editor>` component. Please, visit the above gist to see the full code of the affected vue component.

**Expected behavior**
An editor WYSIWYG should be seen with its icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/22522883/103574287-ee693080-4ecf-11eb-8ac8-c3c7c725d01c.png)

When I click on `editor-utils.js?a139:81` (above screenshot), I see the following code:

![image](https://user-images.githubusercontent.com/22522883/103574528-69324b80-4ed0-11eb-8f8e-34bc23acc4e0.png)

**Platform (please complete the following information):**
OS: Linux Ubuntu
Node: 12.14.1
NPM: 6.13.4
Yarn: 1.22.10
Browsers: Google Chrome Versión 87.0.4280.88 (Build oficial) (64 bits)
iOS: - 
Android: -
Electron: -

**Additional context**

**Comment by pdanpdan** [comment]
I suppose it's your button pictures from the list of options.
Please use it discord channel or the forum for help requests.
