### ISSUE TITLE
"CSS Spacing Classes" not working in table cell 

### ISSUE THREAD

**Issue by ngekoding** [quasarframework/quasar#8290]
**Describe the bug**
Trying to add headerClass for padding in table, but override by default header style.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ngekoding/pen/zYKjozB

**To Reproduce**
1. Use table component
2. Add `headerClasses` at the first column with `q-pl-lg`
3. No change applied
4. Open the browser > Inspect Element > Elements, and look for the padding style

**Expected behavior**
The padding must use by the "CSS Spacing Classes"

**Screenshots**
<img width="325" alt="Padding not applied" src="https://user-images.githubusercontent.com/11625690/103602658-8b1ae500-4f47-11eb-8bba-53a8c04ca650.png">

**Platform (please complete the following information):**
OS: MacOS Big Sur
Node: v12.10.0
NPM: 6.14.8
Yarn: - 
Browsers: Version 87.0.4280.88 (Official Build) (x86_64)
iOS: -
Android: - 
Electron: -

**Comment by pdanpdan** [comment]
Hello. There are some cases where the css is more specific than some generic classes.
You can define some class if your own or wrap the conrwnt of the header in docs.

**Comment by ngekoding** [comment]
> Hello. There are some cases where the css is more specific than some generic classes.
> You can define some class if your own or wrap the conrwnt of the header in docs.

Thank you, because this is the first time I use Quasar, so I think we can do like that.
