### ISSUE TITLE
QBadge - round prop

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#8292]
**Is your feature request related to a problem? Please describe.**
I want a possibility to make the QBadge round. 
So that it looks like this Badge with Number: 
https://material.io/develop/android/components/badging

**Describe the solution you'd like**
Add a prop named `round` and then make the Badge round then. Like in QBtn.

**Comment by robert-niestroj** [comment]
> 
> 
> you can use your custom class like here:
> https://codepen.io/pdanpdan/pen/ExgLQvy

Works. Thank you. Still - prop would be nice :-)

**Comment by pdanpdan** [comment]
Yes, the issue stands, but you don't have to wait for it to be implemented.

**Comment by yusufkandemir** [comment]
As per https://github.com/quasarframework/quasar/pull/8370#issuecomment-766330957, this feature is already implemented and published as `rounded` prop.
