### ISSUE TITLE
Possible bug with qbtn-dropdown with extra pixles 

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#8293]
**Describe the bug**
When I use btn-dropdown with dropdown-icon, there is a 8 extra pixels to the left side of the icon which throws off the spacing

**To Reproduce**
`          <q-btn-dropdown
            class="q-mr-md"
            dense
            rounded
            flat
            auto-close
            dropdown-icon="more_horiz">`
       

**Expected behavior**
the width & height should be the same size, as this works withq-btn

**Screenshots**
If applicable, 
![dropdown](https://user-images.githubusercontent.com/7861196/103751310-1773e900-4fd6-11eb-8cce-f139fa1b1a91.png)
add screenshots to help explain your problem.

**Platform (please complete the following information):**
OS: Wndows
Node: 14.15
NPM: 6.13
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.1

**Comment by BenHayat** [comment]
Thank you!
