### ISSUE TITLE
QTable: Option to specify default descending value

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#8294]
**Is your feature request related to a problem? Please describe.**
By default the `descending` value when sorting a different column is `false`, as you can see [here](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/table-sort.js#L74).
If you want columns to sort descending by default, you have to implement a custom sort, which won't reflect in the visuals of the arrow icon in the header when hovering.

**Describe the solution you'd like**
Adding a new `Boolean` prop after `binaryStateSort` called `defaultDescending`, which should be used at the location mentioned above and [here](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/QTable.js#L117) - thinking `!!this.defaultDescending` should do the trick.
In addition, to properly reflect the state in the icons, the follow line should be changed [here](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/table/table-column-selection.js#L44):
```javascript
(col.sortable === true ? ' sortable ${col.name !== sortBy && this.defaultDescending === true ? 'sort-desc' : ''}' : '') +
```

**Describe alternatives you've considered**
A custom sort method, but that won't reflect properly in the icons.

**Additional context**
I'd love to change it myself, but I actually haven't got a clue on how to test this locally.

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.
