### ISSUE TITLE
Can we add slots to QOptionGroup?

### ISSUE THREAD

**Issue by GGLionCross** [quasarframework/quasar#8301]
**Is your feature request related to a problem? Please describe.**
I want to add label slot to my QRadios in QOptionGroup without having to break it up into a list of QRadios.

**Describe the solution you'd like**
We should be able to specify a slot that trickles into the component used for option group, whether it's QRadio or QCheckbox

**Comment by pdanpdan** [comment]
To be honest the amount of code required in userland to use such a feature would be the same as writing the whole thing the way you want it.

Sorry, but we will keep it simple.
