### ISSUE TITLE
Want transfer components.

### ISSUE THREAD

**Issue by infiniteDemon** [quasarframework/quasar#8302]
Want transfer components.Such as https://element-plus.org/#/en-US/component/transfer.

**Comment by pdanpdan** [comment]
Hello. You can create it as you see necessary for your purpose with 2 lists and a few buttons.

**Comment by infiniteDemon** [comment]
I want the transfer to have drag and drop.
Such as https://quasar.dev/vue-directives/mutation.
But I'm not very good at mouse events.
Thanks for your reply.
I will try it.

**Comment by rstoenescu** [comment]
@infiniteDemon

Hi, this is easily achievable with the components that are supplied by Quasar. The native drag'n'drop is also really easy to learn. Here's an example: https://quasar.dev/vue-directives/mutation#Example--Drag-and-Drop-(desktop-only)

**Comment by TobyMosque** [comment]
if u think that component can be util to others, you can ever create a new ui extension and make that public.:

https://quasar.dev/app-extensions/development-guide/introduction#Introduction

**Comment by infiniteDemon** [comment]
Thinks.I will try it and push new component.
