### ISSUE TITLE
quasar/extras v1.9.13 missing CSS file for ionicons v5.3.0

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#8304]
**Describe the bug**

The ionicons 5.x folder in github is missing the css file
https://github.com/quasarframework/quasar/tree/dev/extras/ionicons-v5

First I activated the “ionicons-v5”, in the Quasar.conf extra sections
Then I got error that I need to install CSS
npm install --save @quasar/extras/ionicons-v5/ionicons-v5.css

When I tried to install the css, I got error that the css file is missing from github.

**Comment by rstoenescu** [comment]
Ionicons does not ship the CSS equivalent. It is only available in SVG format.

**Comment by rstoenescu** [comment]
More information: https://github.com/ionic-team/ionicons/issues/785

**Comment by hawkeye64** [comment]
That issue I files is back from Feb 2020 -- no response from their team. I don't think it's going to happen.
Maybe we should explicitly point this out on the readme?
https://github.com/quasarframework/quasar/tree/dev/extras

**Comment by imlinhanchao** [comment]
How to enable Ionicons v5? I have the same issue when I add `ionicons-v5` in `extras` of `quasar.config.js`.

**Comment by hawkeye64** [comment]
> How to enable Ionicons v5? I have the same issue when I add `ionicons-v5` in `extras` of `quasar.config.js`.

Because Ionicons no longer has web fonts, you have to use the SVG files. For example: `svg-ionicons-v6`
