### ISSUE TITLE
Bug on table scroll bar going over a dialog box

### ISSUE THREAD

**Issue by cesar128** [quasarframework/quasar#8305]
**Describe the bug**
Not sure if looks like that on Mobile but when i have a page with a table (several columns so it must have a scroll bar) and i open a Dialog, if i resize the window (testing responsiveness) the scrollbar of the table will show over the dialog.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/cesar128/pen/MWjXMgY

**To Reproduce**
1- Open pen
2- Leave dialog open
3- press Ctrl + Shift + M (Firefox) 
4- Test responsiveness of the page, try to find the grey scroll bar that is going to be in front of the dialog

**Expected behavior**
Scroll bar should stay behind the dialog

**Screenshots**
![Screenshot_20210107_135004](https://user-images.githubusercontent.com/8787121/103952392-b99aea80-5116-11eb-8acb-e14d987ab0ef.png)

**Platform (please complete the following information):**
OS: Ubuntu    20.04
Node:             10.22.0
NPM:              6.14.6
Yarn:               1.22.5
Browsers:       Firefox
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment]
Hello. Have you checked if this happens on a real mobile device in Firefox or any other browser?
Firefox is notoriously bad with mobile emulation.
