### ISSUE TITLE
[docs]  Change in CLI V2  prod. build file structure is not documented

### ISSUE THREAD

**Issue by pjar** [quasarframework/quasar#8306]
Upgrade guide v2 does not mention the changes in production build file structure. 

In our project we don't use autogenerated index.html file as we have to combine our custom stuff for back-end features in our own index.html file to make everything work together. We have to specifically include quasar build generated JS and CSS files, as well as static files since we need to whitelist them.
Upgrading quasar from v1 to v2 resulted in complete break up of our app and we had to spend some significant time to figure out why our build has different files now. We thought it might be because of some missing part in our setup.

It turned out that CLI in v2:
- does not generate runtime.js file (its contents are now merged into app.js and vendor.js files)
- generates new vendor.css file

Upgrade in our case could be significantly better experience if above changes were documented in the guide: https://quasar.dev/quasar-cli/app-upgrade-guide

**Comment by BenHayat** [comment]
@pjar 

Suggestion: You should update the title of your thread to "CLI V2", as the current title is misleading and hints at the up coming Quasar V2.

**Comment by hawkeye64** [comment]
@pjar Feel free tp PR the docs. You have recent experience, so it'd be best if you added this. It's not always easy to get all the changes into the docs. Also, besides looking at the `upgrade guide` in the docs, make sure to look at the release notes: https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v2.0.0
