### ISSUE TITLE
Vertical QSeparator is misplaced when inset="true"

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#8307]
I'v found this old issue  #5397 and i'm having the same problem.
I'm on 1.15.0 and it's happening on chrome.

You can see the exact behaviour in the other issue.

**Additional context**
I'v also found that the problem comes when i'm using a custom height over the toolbar.
Removing the height works just fine.

Consider change height: inherit to auto.

**Comment by pdanpdan** [comment]
Hello. What browser and what version, because you specify chrome and I cannot reproduce it.
Please also add a codepen.

**Comment by vandelpavel** [comment]
Here is a code pen https://codepen.io/vandelpavel/pen/gOwjgJN.
Try to uncomment the height.

By the way my browser is on 87.0.4280.88.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.1
