### ISSUE TITLE
Quasar using node_modules from another project

### ISSUE THREAD

**Issue by gaby64** [quasarframework/quasar#8309]
I have two vue projects, tracker and training

when node_modules is populated in tracker, there are issues in training

![image](https://user-images.githubusercontent.com/2108555/104038927-b7cb3880-51a3-11eb-94db-b9d465911619.png)

this is after deleting the quasar folder in node_modules of tracker 

![image](https://user-images.githubusercontent.com/2108555/104038986-cade0880-51a3-11eb-81aa-b7c2a50d0bf3.png)

the only solution atm is to delete the entire node_modules folder of tracker so that training can compile correctly.

**Comment by pdanpdan** [comment]
I'm not sure what you want to do, but it's not good :)
Please use the discord channel or the forum for help requests.

**Comment by gaby64** [comment]
im trying to build two independent vue websites, somehow quasar uses node_modules from the other which leads to issues

**Comment by pdanpdan** [comment]
You are using vue-cli, check what it does, maybe you have a symlink
