### ISSUE TITLE
QChip: icon markup is rendered even when the icon property is set to the empty string.

### ISSUE THREAD

**Issue by aleksander237** [quasarframework/quasar#8312]
The icon markup inside of the QChip component is rendered event when the icon is set to the empty string. 

[https://codepen.io/aleksander237/pen/WNGKard](
https://codepen.io/aleksander237/pen/WNGKard)

I not sure if this is by design, but excepcted behavior would be not rendering the icon markup if the string is empty. It would be easier to render dynamic chips (example above).

**Comment by pdanpdan** [comment]
By default you should use `undefined` for making a prop as missing.
