### ISSUE TITLE
Make q-focus-helper customizable per component?

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar#8314]
**Is your feature request related to a problem? Please describe.**
I want to change the hover/focus effect for my custom button (e.g. using a `my-btn` class), however it seems `q-focus-helper` is globally defined (attached to `body.desktop`), which means it cannot seem to be overwritten a single component?

**Describe the solution you'd like**
```
.my-btn {
  .q-btn__wrapper::before {
    border: 2px solid $grey-8;
    background: transparent;
  }

  &:focus,
  &:hover {
    background: $grey-8;
  }
}

.my-btn .q-focus-helper {
  opacity: 1;

  &::before,
  &::after {
    opacity: 1;
  }
}
```

**Describe alternatives you've considered**
Add custom CSS to disable q-focus-helper globally: https://github.com/quasarframework/quasar/blob/a200c3ad0233431953bc7149572e8a7ca4b71a0b/ui/src/css/core/visibility.sass#L154

**Additional context**
I'm not a CSS expert, maybe my syntax is wrong, sorry.

**Comment by pdanpdan** [comment]
Hello. What you have in your code looks almost good. Please make a codepen and add for help on the forum or on the discord channel.

**Comment by scottie** [comment]
Did this get fixed and merged ? Issue seems to still exist.
