### ISSUE TITLE
FR - Cascade Select/Dropdown Button

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#8315]
**Is your feature request related to a problem? Please describe.**
To automate Cascading processing UI as part of a built in component.

**Describe the solution you'd like**
Ability for developers to create nested collection and bind data to these collections and the component at runtime shows the related sub collections according to parent selections.

**Describe alternatives you've considered**
The alternative is to create a series of Dropdowns which takes too much space and manual coding

**Additional context**
Here is a link to same feature from another vendor.
https://www.primefaces.org/primevue/showcase/#/cascadeselect

![cascade](https://user-images.githubusercontent.com/7861196/104132322-a2444300-534a-11eb-8bf0-442221b7c618.png)

**Comment by pdanpdan** [comment]
The solution is to use cascaded menus that pick what option you need.

**Comment by BenHayat** [comment]
Thanks!

**Comment by hawkeye64** [comment]
You can use this: https://quasar.dev/vue-components/menu#Example--Menus-in-menus

**Comment by BenHayat** [comment]
@hawkeye64 
Thanks Jeff;

It would be great to extend this sample to be data bound.

**Comment by hawkeye64** [comment]
@BenHayat You could get really tricky and use a computed state machine that does something like that. Unfortunately, I am bogged down atm. But, shouldn't be hard to implement.

**Comment by BenHayat** [comment]
> 
> 
> @BenHayat You could get really tricky and use a computed state machine that does something like that. Unfortunately, I am bogged down atm. But, shouldn't be hard to implement.

I understand you're limited with time.
My request was mostly for new users coming in.
Or perhaps somet text to expand the proper way of using it, i.e directly binding to data collection or using computed property or via connecting to Vuex state and etc.

Lots of people who are new, mostly go to docs for best practices and guidelines not to make mistake. 
My original question was to create a data bound drop down for business apps with data. And it was suggested to use menu component.
More informed docs, avoid mistakes and questions.
Thanks!
