### ISSUE TITLE
feat(QTabs): make getScrollTarget work with QTabs

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#8317]
### **Is your feature request related to a problem? Please describe.**

When you have a lot of QTabs, and they overflow X (horizontal scroll), they currently do so by this CSS:

```sass
body.mobile .q-tabs

  &__content
    overflow: auto
```
(see [source](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/tabs/QTabs.sass#L188))

#### The problem:

Because it does not use the `.scroll` class, it's not targetable with Quasar's `getScrollTarget` scroll helper.

Here is the scroll helper:
```js
target = el.closest('.scroll,.scroll-y,.overflow-auto')
```
https://github.com/quasarframework/quasar/blob/dev/ui/src/utils/scroll.js/#L19

So I cannot make sure on mobile that the tabs get scrolled horizontally automatically to the correct tab of my QTabs when I open one that's way off to the right side.

### **Describe the solution you'd like**
I'd love to see either
- a fix to the QTabs, have them use `.scroll` class instead of using `overflow: auto`
- or a fix to the `getScrollTarget` helper that it can find the correct scroll target even if it doesn't have the `.scroll` class.

### **Describe alternatives you've considered**
I can't find one. Native `element.scrollIntoView()` also doesn't work for some reason...

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.1

**Comment by mesqueeb** [comment]
@rstoenescu what's the behaviour change you went with ?

**Comment by pdanpdan** [comment]
We use .scroll class
