### ISSUE TITLE
slots for q-table bottom: 'bottom-left' and 'bottom-right' - like 'top' has.

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#8319]
**Is your feature request related to a problem? Please describe.**
I want to use the space on the bottom left for info like total nr. of items, total amount, etc.
I don't want to remove pagination as it works very well but I can't. The slot 'bottom' will remove it.

**Describe the solution you'd like**
Have slots 'bottom-left' and 'bottom-right'(where pagination is)

**Comment by yusufkandemir** [comment]
Duplicate of #7208
