### ISSUE TITLE
Screen Plugin + SSR improvement: Take browser client hints headers into account

### ISSUE THREAD

**Issue by chetzof** [quasarframework/quasar#8320]
**Is your feature request related to a problem? Please describe.**
As specified here
https://github.com/quasarframework/quasar/issues/5079
server has no way of knowing about the client's screen size during render, so it defaults to the lowest possible size.
This causes a series of ugly layout jumps and even some hydrations errors in my case when using q-drawer in combination with screen plugin.

**Describe the solution you'd like**
Thanks to the client hints, we finally can receive the client's screen size info on server.
https://developer.mozilla.org/en-US/docs/Glossary/Client_hints

The browser support is currently limited to Chromium and Edge based browsers, but I hope Safari and Firefox will follow shortly.
https://caniuse.com/client-hints-dpr-width-viewport

You can this feature on a supported browser by viewing this  server-rendered page.
https://shocking-steep-sage.glitch.me/
Here's an example from my Chrome Stable on Mac
![CleanShot 2021-01-11 at 15 31 12](https://user-images.githubusercontent.com/467230/104188609-25849800-5422-11eb-876f-8cb39fbed5ba.png)

Thanks to this feature, the Screen Plugin on SSR can be aware of the user screen size.
I wonder what other things for SSR it can help improve.

**Comment by Evertvdw** [comment]
This would be very nice if this was implemented! I do notice that the 'viewport-width' is always the width of my primary screen when I check it at the url you provided. So it does not take the size of the browser-window which I find strange as in CSS the viewport is the browser window size right? 

Despite that I think it could still be a benefit over the current solution, we also had issues with hydration errors due to this. Big +1 from me to do something with this information :)

**Comment by pdanpdan** [comment]
All nice and dandy, but you haven't read what it does :)
These are not headers that are sent on the initial request but on subsequent requests if the meta tag is present in the head of html. It is useless for ssr's initial render.

**Comment by rstoenescu** [comment]
There's also the `Accept-CH-Lifetime` header that can be sent. Sure, on the first render it's going to be useless. But on subsequent requests it really helps.

The real downside is that it's still marked as being "experimental" (so specs can change without any notice) and "non-standard".

For the life of me, I couldn't make Chrome 88, FF 84 or Safari 14 to send the headers. Sure, Accept-CH-Lifetime works on HTTPS only, but I tried with HTTPS too and nothing is being sent. I should probably try it out with a real domain and SSL certificate (maybe that was the issue? although I doubt it).

**Comment by hawkeye64** [comment]
Just wondering if you did this:
![image](https://user-images.githubusercontent.com/10262924/107650752-06a13d80-6c3c-11eb-9593-49320ac59811.png)

**Comment by rstoenescu** [comment]
Even disabled cache entirely. No luck.
