### ISSUE TITLE
Q-table, v-touch-hold on standard row event

### ISSUE THREAD

**Issue by xrnv2** [quasarframework/quasar#8322]
To improve q-table expirence on mobile I think it will be great to add v-touch-hold on row as standard event.
We have now row-click and row-dbclick events. It will be exelent to have ability to use something like row-touch-hold.

**Comment by pdanpdan** [comment]
VTouchHold e too heavy to go on each table row.
I think it would go better with #7803

**Comment by pdanpdan** [comment]
Please use the new 'row-contextmenu` event in v1.15.1 or go with a full row slot implementation.
