### ISSUE TITLE
[docs] Potential security risk using an example code in practice

### ISSUE THREAD

**Issue by aliclark** [quasarframework/quasar#8325]
The [Ajax Requests](https://quasar.dev/quasar-cli/ajax-requests#Introduction) documentation includes a helpful example to automatically populate the `Authorization` header for axios, based on returned token data from a previous authentication:

```js
function setAxiosHeaders (token) {
  axios.defaults.headers.common['Authorization'] = 'Bearer ' + token
}
```

This is fine when only a single API endpoint is used, but in the general case it can lead to accidentally sending the `token` to other 3rd party services when invoking them using axios.

This example could be made safer by either calling out the hidden dangers explicitly in a comment (this is what `axios` now does in its README), or modifying the example to use a custom instance for accessing specific APIs. I think the latter would be helpful, as that's probably what the user would want in all cases.

**Comment by hawkeye64** [comment]
@aliclark A PR would be most welcomed.

**Comment by hawkeye64** [comment]
https://github.com/quasarframework/quasar/pull/8326
