### ISSUE TITLE
QTree - Remove attributes for selectable node from node with children and not selectable

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#8327]
**Describe the bug**
When I use the `'selectable: false'` property on a node with children, it still has the `q-hoverable`, `q-focusable` and `q-tree__node--link` HTML attributes as if the node were selectable. The selection does not work but these attributes remains in the HTML element and implies that the node is still selectable. The same is not true for a node that has no children and the `'selectable: false'` property is used.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/slowaways/pen/bGwmaeX?editors=101

**To Reproduce**
1.1 Mouse over a node with '(not selectable) in the label' that contains children
1.2 The background color of the node will change as if it were still selectable.
2.1 Mouse over a node with '(not selectable) in the label' that NOT contains children
2.2 The background color of the node will NOT change as if it were still selectable (as expected).

**Expected behavior**
Do not modify the `background color` and remove `cursor: pointer` in the node that contains children when the node has the property `'selectable = false'` (keep the same behavior when the node has the property `'selectable = false'` and has no children).

**Screenshots**

![Clipboard01](https://user-images.githubusercontent.com/9668277/104378636-1297c380-5507-11eb-9c58-2bed0fdcec00.jpg)
*[❌] Node with '(not selectable) in the label' that contains children*

![Clipboard02](https://user-images.githubusercontent.com/9668277/104378696-2a6f4780-5507-11eb-971d-2e39bd3db70a.jpg)
*[✅] Node with '(not selectable) in the label' that NOT contains children*

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
Node with attribute `q-hoverable`, `q-focusable` and `q-tree__node--link`
![image](https://user-images.githubusercontent.com/9668277/104379128-c9943f00-5507-11eb-854a-f653bc50b81d.png)

**Comment by metalsadman** [comment]
both hover effect and pointer is applied for expandable nodes. i don't think it's a bug, just probably need a feature props to disable that behavior, ie. expand only via indicator, disable hover effect etc...

**Comment by slowaways** [comment]
> 
> 
> both hover effect and pointer is applied for expandable nodes. i don't think it's a bug, just probably need a feature props to disable that behavior, ie. expand only via indicator, disable hover effect etc...

@metalsadman 
There is no need a prop to disable this behavior because the expected behavior when `selectable='false'` is: no hover effect and `cursor: text` in CSS (not pointer).
Currently, this is also the case: the node is only expanded via the indicator ">". Selecting the node does not expand it.

**Comment by slowaways** [comment]
@rstoenescu Can update this in Quasar v2?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.5.2 and v1.18.2
