### ISSUE TITLE
QFabAction - Add 'external-label' and 'label-position' to QBtn or allow to use QFabAction outside of QFab.

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#8328]
**Is your feature request related to a problem? Please describe.**
I want to have floating action buttons always expanded, with their external labels and the option to adjust the direction of the label, without the need to have `QFab` to open / close `QFabActions`.

When I try to use QFabAction outside of QFab:
![image](https://user-images.githubusercontent.com/9668277/104491460-0a945e00-55b1-11eb-9649-fa9cd4349cba.png)

The second problem: I can't use `external-label` and `label-position` in a `QBtn` with `fab` prop.

**Describe the solution you'd like**
Add `external-label` and `label-position` to `QBtn` or allow to use QFabAction outside of `QFab`.

Design expected using `QPageSticky` with `position="bottom-right"`:

![image](https://user-images.githubusercontent.com/9668277/104492028-d4a3a980-55b1-11eb-85f9-52b2823828ed.png)

**Describe alternatives you've considered**
1) Use `QFab` with `QFabAction` inside `QPageSticky` and change the `QPageSticky` `offset` (eg. ` :offset="[18, -60]"`) until it disappears from the screen and set `QFab` `:value="true"` but this is not an elegant solution.
2) Use `QFab` with `QFabAction`, set prop `:value="true"` in `QFab` and hide only `QFab` using CSS.

**Additional context**
None

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v1.15.1

**Comment by slowaways** [comment]
Thank you @pdanpdan and @rstoenescu !!!
