### ISSUE TITLE
electron source code protection using bytenode

### ISSUE THREAD

**Issue by faxinwang** [quasarframework/quasar#8331]
I'm finding **electron source code protection** solution for a while, and found a possible solution.

[bytenode](https://www.npmjs.com/package/bytenode) is a tool that can compile js code to it's binary format, thus can be used to implement javascript source code protection. 

In the current electron building process, the source code is firstly processed by webpack and then packed by bundlers. We can compile the generated "electron-main.js" file by webpack into it's binary format "electron-main.jsc" using bytenode.  and then using `require('./electron-main.jsc')` to replace the old contents of "electron-main.js".
That it.

If your maintainers can spare time to implements this, it will benefit all other developers. Or you
can provide some hooks of the building process to developers so we can implements it ourselves.

Thank You.

**Comment by hawkeye64** [comment]
@faxinwang Sounds interesting, but I am a little concerned about this issue they have:
> Async arrow functions cause crash in Electron apps if used in render processes. See #47.

**Comment by faxinwang** [comment]
It's sames that the compiled binary code generated by bytenode can only be executed by node, thus it can only protect the main thread js code, but it will still help a lot. 

And by doing some tricks in the main process, such as checking the app.asar's file size or change time, we can know whether the sources code has been modified.

**Comment by hawkeye64** [comment]
@faxinwang  I truly believe this would be better off as an app-extension that can call bytecode in the Quasar (afterBuild)[https://quasar.dev/app-extensions/development-guide/index-api#api.afterBuild] life-cycle hook.

**Comment by faxinwang** [comment]
thanks, i will try------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jeff&amp;nbsp;Galbraith&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上10:26
收件人:&nbsp;&quot;quasarframework/quasar&quot;<quasar@noreply.github.com&gt;;
抄送:&nbsp;&quot;faxinwang&quot;<1094828998@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [quasarframework/quasar] electron source code protection using bytenode (#8331)
