### ISSUE TITLE
Button Toggle Not wokring for dynamic label with slot

### ISSUE THREAD

**Issue by masidiq** [quasarframework/quasar#8332]
**Describe the bug**
Button toggle with template and dynamic label cannot click (Not working)
If comment the code on mounted (example below) it will working again

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/masidiq/pen/YzGRjKy?editors=101

**To Reproduce**
1. just change label dynamicaly

**Expected behavior**
Button toggle can click normally

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.1.
