### ISSUE TITLE
Building Android Apps Using Android SDK Command Line Tools

### ISSUE THREAD

**Issue by engineervix** [quasarframework/quasar#8336]
Is it possible to build Android apps without Android Studio? I'd like to simply use the Android SDK Command Line Tools.

**Comment by pdanpdan** [comment]
I suppose you can build it with the cli also, you just have to search how it is done.
If you do such a research please open a PR for the cli or for the docs with your findings.
Thank you.

**Comment by rstoenescu** [comment]
You haven't specified if you're using Cordova or Capacitor.

Cordova -> https://quasar.dev/quasar-cli/developing-cordova-apps/build-commands
Capacitor -> https://quasar.dev/quasar-cli/developing-capacitor-apps/build-commands

Not sure if this is what you are looking for, but note the `--skip-pkg` param when you want to finalize the build with Cordova/Capacitor CLI. Using this param only fills in the www folder and then you need to manually issue the Cordova/Capacitor CLI commands to generate the actual .app/.apk file.
