### ISSUE TITLE
QColor - Hide header tabs but keep the hex editor

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#8337]
Simple request, I'd like the option of removing the tabs at the top of the QColor component, but keep the actual HEX editor.
In my case, I'd like the user to be able to change the HEX color code but not use RGB(A).

![image](https://user-images.githubusercontent.com/13761766/104882172-b0cbd380-59b6-11eb-893a-03608d0a5592.png)

**Comment by nurlansu** [comment]
@nicholaszuccarelli You can hide header by passing prop `no-header`: https://quasar.dev/vue-components/color-picker#No-header-or-footer.

**Comment by nicholaszuccarelli** [comment]
> @nicholaszuccarelli You can hide header by passing prop `no-header`: https://quasar.dev/vue-components/color-picker#No-header-or-footer.

Yes I know that, but that will hide the hex editor as well. I want to hide the tabs but keep the hex editor.

**Comment by nurlansu** [comment]
> Yes I know that, but that will hide the hex editor as well. I want to hide the tabs but keep the hex editor.

Oh, sorry for my misunderstanding.

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.1.10 through new Boolean prop (no-header-tabs).
