### ISSUE TITLE
Cordova - cannot single-tap QItem (with tag="label") and QRadio/QCheckbox

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#8339]
I'm struggling to use the implementation as outlined on https://quasar.dev/vue-components/radio#With-QItem
(Same applies with QCheckbox).

This implementation works fine normally (through the mobile browser and directly on desktop), but via Cordova you must double-tap on the QItem for it to register and change the QRadio value.

**Comment by rstoenescu** [comment]
Are you using Ionic Webview as indicated in the docs?

**Comment by nicholaszuccarelli** [comment]
> Are you using Ionic Webview as indicated in the docs?

Yes, I am using it.

**Comment by rstoenescu** [comment]
For completeness, can you post a ssnippet of the whole QItem pls?

**Comment by nicholaszuccarelli** [comment]
> For completeness, can you post a snippet of the whole QItem pls?

Absolutely.

![image](https://user-images.githubusercontent.com/13761766/105099467-d9131980-5aff-11eb-8248-4b51ad92b0ae.png)

The structure is the exact same as the example you have in the docs, however `messageType` is a local variable in my component.

On web/browser, I am able to tap the QItem. On Cordova, if I tap the item, it activates the v-ripple but doesn't change the value of the QRadio. 
I need to double-tap on the QItem in order for it to change the QRadio value.
If I tap on the actual QRadio element, it will change correctly.

This was tested on iPhone 6S.

**Comment by nicholaszuccarelli** [comment]
I just created a fresh Quasar app and copied that code, loaded into Cordova and I am having the same result.

**Comment by nicholaszuccarelli** [comment]
Fresh project here with QRadio and QCheckbox

https://github.com/nicholaszuccarelli/virtual_scroll_bug

**Comment by rstoenescu** [comment]
What is the iOS version running that device?

**Comment by nicholaszuccarelli** [comment]
> What is the iOS version running that device?

iPhone 6S. Latest version of iOS 14. Can’t remember the exact version, but either 14.2 or 14.3

**Comment by nicholaszuccarelli** [comment]
@rstoenescu  Sorry, I was only able to just check the phone and it is running iOS 14.0.1
I am updating it to 14.3 now and will report back if the bug is happening on that version too.

**Comment by nicholaszuccarelli** [comment]
I have run it on iOS 14.3 and am still having the same bug.

**Comment by xiaoxiao99** [comment]
For others who reached this thread by search. This issue seems finally addressed in #13619

**Comment by rstoenescu** [comment]
Is this still happening? It should not. Please comment so I can reopen if it's still an issue. Thank you.

**Comment by xiaoxiao99** [comment]
I saw this issue in earlier version, but confirmed it is already fixed with latest (Quasar V2.14.7)
