### ISSUE TITLE
Can slider components and range components support lazy option?

### ISSUE THREAD

**Issue by likecao** [quasarframework/quasar#834]
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What were you expecting?

The current change event is actually the input event.Historical records are frequently changed and undo and redo are affected.

**Comment by rstoenescu** [comment]
Initially the slider was "lazy" updating the model then a request came by to avoid this.
Will add a "lazy" option and research how to optimally do this.

**Comment by rstoenescu** [comment]
It will, closing as this has become duplicate of a more complete Github ticket: #882 
Scheduled for v0.15.
