### ISSUE TITLE
change quasar.conf.js to quasar.config.js

### ISSUE THREAD

**Issue by leandroruel** [quasarframework/quasar#8342]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem

**Describe the solution you'd like**
change the quasar.conf.js to quasar.config.js

**Describe alternatives you've considered**
i've seen so many libs and projects using the same pattern *next.config.js*, *babel.config.js*, *postcss.config.js* so my question is why quasar has to be different from others? it is a bit irrelevant feature request but i feel like this file could follow same pattern as other libs do too

**Additional context**
nothing more to add

**Comment by pdanpdan** [comment]
Does it really matter? It's a standard short name for config.

**Comment by hawkeye64** [comment]
Beside, we like that it marries well with `Quasar.Conf`, our online conference
