### ISSUE TITLE
[docs] Release Notes page does not show releases

### ISSUE THREAD

**Issue by node-ex** [quasarframework/quasar#8345]
Hi guys, today I've noticed that the Release Notes page stopped showing release details, here is a screenshot with an empty table and console errors related to rate limiting from GitHub API:

![image](https://user-images.githubusercontent.com/8402099/105169104-5435f900-5b1b-11eb-9471-ee492b5db2f3.png)

**Comment by node-ex** [comment]
Looks like it was only a temporary problem, everything looks ok now. Closing the issue.

**Comment by rstoenescu** [comment]
We're using the github api which is indeed rate limited. If you refresh this page enough times then you'll hit that limit. And there is nothing that we can do. Fortunately, the limited access is lifted after some time (I believe it is 1 hour).
