### ISSUE TITLE
setScrollPosition has some kind of side effect (random scroll)

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#8347]
Using setScrollPosition works great untill you try to use a dropdown button with mouse-over feat.

Fork my example project here:
https://github.com/vandelpavel/Issue-classList.add-on-ssr.git
PS: do not mind the repository name

**To Reproduce**
Follow the instruction in the project:
1 Use the scroller
2 Hover the dropdown

**Expected behavior**
Nothing should happen

**Current behavior**
Random scroll over the button

**Platform (please complete the following information):**
OS: Windows 10
Node:v12.16.3.
NPM:6.14.4
Yarn:v1.22.5
Browsers: Chrome 87.0.4280.141

**Additional context**
Probably is not directed to the dropdown behaviour and i found that if you loose the active/focus state of the component hovering the button the side effect wont happen.

**Comment by vandelpavel** [comment]
My current workaround allows me to use [HTML DOM blur() method](https://www.w3schools.com/jsref/met_html_blur.asp) and make the activeElement loose it's focus status.

**Comment by pdanpdan** [comment]
Please make a codepen from your example so it can be tested.

**Comment by vandelpavel** [comment]
https://codepen.io/vandelpavel/pen/wvzZdrN

I can't manage to import setScrollPosition.
How can i handle that on codepen?

**Comment by pdanpdan** [comment]
`Quasar.utils.scroll.setScrollPosition`

**Comment by pdanpdan** [comment]
The reason:
When the QMenu is closed it refocuses the element that was focused in page when it was opened (in this case it is the button that scrolled the page)

The fix:
Focus the dropdown button first when you hover it.
https://codepen.io/pdanpdan/pen/PoGgjEw?editors=1010

**Comment by vandelpavel** [comment]
Now i understand. My workaround so wasn't fixing the problem inside the project but only on the button used to scroll.

Could be a good idea to add a default hoverable prop feature that manage this behaviour or at least metion it inside the doc.

Maybe is a well know behaviour for experts but newer ones like me could fall in it.

Just my opinion is all up to you :)

Thanks again!
