### ISSUE TITLE
bug with 'disabled' style,click event still be used??

### ISSUE THREAD

**Issue by fionagithub** [quasarframework/quasar#835]
with vuelidate ,i set button ,and  validate if this is disabled or not
code:
`        <button @click="add()" :class="{'disabled':$v.$dirty&&$v.$error }">add</button>
`
but when i change the code like below , it was fine,and for why?
code:
`        <button@click="add()" :disabled="$v.$dirty&&$v.$error">add</button>
`

**Comment by rstoenescu** [comment]
Please upgrade to Quasar v0.14.x, where the "disabled" prop solves your problem. Thanks.
