### ISSUE TITLE
QTabs __updateContainer size calculate wrong in safari.

### ISSUE THREAD

**Issue by ruojianll** [quasarframework/quasar#8356]
**Describe the bug**
QTabs width is 379,  four QTab s offsetWidths are 95,95,95,95 (which excepted four 94.75). The QTab s total width is not 379, so there is a bug in QTab's __updateContainer inner function.

In chrome, They are 95,95,94,95.

**Codepen/jsFiddle/Codesandbox (required)**
OPEN IN SAFARI !!!
https://codepen.io/ruojianll/pen/RwGOMMz

**To Reproduce**
Create a horizontal QTabs with four QTab s. 
Resize the window to width 379.

**Expected behavior**
Align justify four tabs not align left
**Screenshots**
Safari
![Safari](https://i.imgur.com/GlMq6hI.jpg)
Chrome
![Chrome](https://imgur.com/4u0kvX7.jpg)
**Platform (please complete the following information):**
IOS MacOS's safari in certain width, such as 379 with four tabs

**Additional context**
Fix the algorithm in __updateContainer

**Comment by pdanpdan** [comment]
Please also make a codepen that can be used to reproduce it.

**Comment by ruojianll** [comment]
@pdanpdan updated

**Comment by pdanpdan** [comment]
Hello, can you please test if this fixes the problem for you?

In package.json replace quasar dependency with:
"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.0-beta.3"

Then do a yarn or npm install and start the app again.

Please report if you find something not working.

**Comment by ruojianll** [comment]
@pdanpdan `npm install` blocked when quasar=https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.0-beta.5

**Comment by ruojianll** [comment]
For "https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.15.0-beta.3", I upzip and install it from my local file system. The bug has fixed.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.1
