### ISSUE TITLE
Select components within Popovers don't work

### ISSUE THREAD

**Issue by pwinckles** [quasarframework/quasar#836]
### Software version

Quasar: 0.14
Browsers: Firefox; Chrome

### What did you get as the error?

Select components within Popover components cause the Popover to close when the Select box is clicked.

### What were you expecting?

I was expecting the Popover to remain open.

### What steps did you take to get the error?

`
<q-btn flat>
  <q-popover ref="popover">
    <q-select v-model="selection" :options="options" />
  </q-popover>
  <q-icon name="notifications_active" color="red-7" />
</q-btn>
`

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, this is a limitation. Avoid adding any components which also have popovers (like QSelect, QDialogSelect and so on).

This limitation will get liften in the future, though.
Sorry for any inconvenience.

-Razvan

**Comment by ldenblyd** [comment]
Hello @rstoenescu there is still no solution for this ?

**Comment by ldenblyd** [comment]
for now the only solution i found is to use native html select
