### ISSUE TITLE
Destructuring process.env stopped working in @quasar/app v2

### ISSUE THREAD

**Issue by nurlansu** [quasarframework/quasar#8361]
**Describe the bug**

After upgrading `@quasar/app` from v1 to v2, destructuring  process.env doesn't work properly.
With IE11 support enabled I get error `ReferenceError: process is not defined`, without it variables are always `undefined`:

```js
const { DEV, MODE } = process.env;

console.log(DEV, MODE); // undefined, undefined
```

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/destructuring-processenv-s1tjx?file=/src/App.vue

**To Reproduce**
1. Create a new project with `@quasar/cli`
2. Add process.env destructuring anywhere
3. Start the server

**Expected behavior**
In both situations (IE11 support mode on/off), destructuring works properly.

**Platform (please complete the following information):**
OS: macOS, Linux
Node: 10.20.1, 12.20.1
NPM: 6.14.10
Browsers: any

**Additional context**
Found the related bug report for webpack: https://github.com/webpack/webpack/issues/5392, but it worked properly and still works in `@quasar/app@1`.
Also destructuring works properly if you extract exactly one property:
```js
const { DEV } = process.env;

console.log(DEV); // spa|ssr
```
Strange.

**Comment by hawkeye64** [comment]
@nurlansu This was done on purpose for security reasons so someone can't `console.log` your sensitive data. Use the full object path all the time.

**Comment by nurlansu** [comment]
@hawkeye64 Thank you for your answer and your time. Sorry to bother.
