### ISSUE TITLE
q-chip @remove causing maximum callstack size exceeding

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#8362]
Hi

When implementing a remove functionality for a qchip, when the code is executed, I see the following error
![image](https://user-images.githubusercontent.com/17168621/105482591-41552d00-5cb1-11eb-980c-6415e61e9fb0.png)

In qchip.js, the following code from the error is
```
    __onRemove (e) {
      if (e.keyCode === void 0 || e.keyCode === 13) {
        stopAndPrevent(e)
        !this.disable && this.$emit('remove', false) <<<< failed code
      }
    },

```
The thing is, it happens only when executing 
`this.$store.dispatch("userData/updateLastStructure", { lastStructure: "" });`
which is a simple data saving to the store object. Also, it never reaches the one last line in the event, after the above one. 
Any hint on where to look will help, thanks

```
<q-chip dense removable v-show="currentViewName != ''" @remove="showDefaultView()" color="primary" text-color="white">
    {{ currentViewName }}
</q-chip>
```

**Comment by pdanpdan** [comment]
Please use our discord channel or the forum for help requests.

**Comment by Amosss** [comment]
I will but I thought it maybe a bug

**Comment by hawkeye64** [comment]
@Amosss It's your code here `@remove="showDefaultView()"` that is causing the issue. Look into this function and whatever else it may call: showDefaultView()

**Comment by Amosss** [comment]
That's the thing, there are several lines of code but this one specifically is causing the error, if I comment it out, there is no error
`this.$store.dispatch("userData/updateLastStructure", { lastStructure: "" });`

**Comment by Amosss** [comment]
I did some more debugging and it looks like it's coming from QResizeObserver
![image](https://user-images.githubusercontent.com/17168621/105497131-22619580-5cc7-11eb-8d93-f71759d74773.png)

The if condition fails and goes into invoke with error and there it fails

**Comment by Amosss** [comment]
OK, I tried something else and it's not related to the chip but to 
this.$store.dispatch(“userData/updateLastStructure”, { lastStructure: “” });

I have no idea what can cause an InternalError: too much recursion in Firefox or maximum callstack size exceeded in Chrome. If you have an idea, please let me know, thanks :)

**Comment by Amosss** [comment]
OK, strict in Store to false did the trick, obviously it was meant to be false in production so while developing, how can I make it true and fail safe? Thanks

**Comment by hawkeye64** [comment]
`strict: process.env.DEBUGGING`

**Comment by Amosss** [comment]
It was process.env.DEV , the question is why it is giving the callstack size exceeding in the first place. I mean, is it a problem on my side or a setting I should set somewhere. It looks like it is related to the object I'm storing in the store and though it can be multi leveled, it's not that gigantic.

**Comment by hawkeye64** [comment]
`process.env.DEV` is just if you run `quasar dev`
`process.env.DEBUGGING` is either `quasar dev` **or** `quasar build --debug`

> the question is why it is giving the callstack size exceeding in the first place

This is 99.9% user error. You will need to figure out what is causing the recursion.
One hard aspect is two reactive objects that cause each other to update. Very difficult to track down.

**Comment by Amosss** [comment]
Thanks a lot for your explanation :)
