### ISSUE TITLE
Touching a Popover button a second time re-opens rather than closes the Popover

### ISSUE THREAD

**Issue by pwinckles** [quasarframework/quasar#837]
### Software version

Quasar: 0.14
Browsers: Chrome
Android: 7.1.1

### What did you get as the error?

After touching a button to open a Popover, touching the button again causes the Popover to close and then immediately reopen.

### What were you expecting?

I expected the Popover to close and remain closed on the second touch.

### What steps did you take to get the error?

The problem is reproducible using the Popovers in the Quasar demo:

http://quasar-framework.org/components/popover.html

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting!

**Comment by rstoenescu** [comment]
Hi, This has been fixed in v0.15, so closing this.
