### ISSUE TITLE
Trigger autocomplete without submitting a form

### ISSUE THREAD

**Issue by 549393092** [quasarframework/quasar#8371]
Dear Quasar team,

I found Q-Input can provide autocomplete, but it’s not complete.
Please see my demo. https://codepen.io/Stanley-549393092/pen/oNzRXde
Here, it uses vue modify @submit.prevent so that submit event will no longer reload the page.
Step1. Input name and click button ‘submit’ (or press enter), you can find the value in the autocomplete list.
Step2. If you change the name and submit again, you can’t find the value.
Step3. If you refresh the browser and submit again, now you can see it.
It seems Q-Input can only remember the name when the first time.

Could it be enhanced?
For more info, please below link, thanks!
https://forum.quasar-framework.org/topic/7610/trigger-autocomplete-without-submitting-a-form

**Comment by rstoenescu** [comment]
Hi,

The autocomplete is using the native browser behavior. If anything, this should be reported to the browser vendors :)
