### ISSUE TITLE
QEditor bug whitespace enters as nbsp in html editor mode 

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/quasar#8376]
When I turn into HTML editor mode and write some code, editor enter all spaces as nbsp, this breakes all ready html content entered with QEditor.

![image](https://user-images.githubusercontent.com/10674646/105630663-82894080-5e5b-11eb-852e-9e58d2778e4e.png)

And got this code.

![image](https://user-images.githubusercontent.com/10674646/105630679-9af95b00-5e5b-11eb-929e-bdce631655ed.png)

I understand that this is normal on WISYWIG mode.
But on HTML edit mode this breakes all page.

Expected behavior on html editor mode: whitespace writes as whitespace.

**Comment by rstoenescu** [comment]
Hi Dmitrij,

The code is generated by the native browser API, not by Quasar. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

**Comment by DmitrijOkeanij** [comment]
I think this is possible just to convert editable div to textarea, on changing to html edit mode, this will solve this problem and some others.
