### ISSUE TITLE
metatags with prefetch and SSR

### ISSUE THREAD

**Issue by vitorhugosg** [quasarframework/quasar#8377]
Hello, how are you?
So I'm having a problem hydrating the META object in the SSR quasar, would there be any way to enable this, as in nuxt in the quasar, or a better method to hydrate this goal to improve my page's SEO?

(sorry my english is not so good, but i think i was chlorine, thanks in advance.)

![image](https://user-images.githubusercontent.com/17458174/105644659-6c887980-5e75-11eb-992d-38c8a8a6c1ba.png)
![image](https://user-images.githubusercontent.com/17458174/105644663-77dba500-5e75-11eb-835e-3c523fc5f80e.png)

![image](https://user-images.githubusercontent.com/17458174/105644665-7dd18600-5e75-11eb-9f37-dc22d3f6f725.png)

![image](https://user-images.githubusercontent.com/17458174/105644714-cc7f2000-5e75-11eb-9173-97c297792c2e.png)

**Comment by nurlansu** [comment]
Hey, @vitorhugosg. You should use `meta` as function here, which is the way to reference properties from the Vue component's scope.

```js
meta() {
    return {
        title: this.postStore.title.rendered,
    };
}
```

Read more here: https://quasar.dev/quasar-plugins/meta#How-It-Works
