### ISSUE TITLE
Buttons have no margin-top when using quasar.rtl.min.css 

### ISSUE THREAD

**Issue by sabars** [quasarframework/quasar#8379]
**Describe the bug**
Buttons have no margin-top when using quasar.rtl.min.css 
Bug after this commit:
https://github.com/quasarframework/quasar/commit/0142e0b145a89a24dc5d04ea6a32e4699ed320ab

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/sabars/pen/KKgOdgj.

**To Reproduce**
1. Open Codepen https://quasar.dev/layout/grid/gutter#Example--Sizes-for-q-gutter
2. Add https://cdn.jsdelivr.net/npm/quasar@1.15.1/dist/quasar.rtl.min.css
1. See error

**Expected behavior**
Buttons must have margin-top when using quasar.rtl.min.css 

**Screenshots**
Good:
![image](https://user-images.githubusercontent.com/14573743/105825445-a8842180-5fd0-11eb-8cc5-531652a70ca5.png)
Bad:
![image](https://user-images.githubusercontent.com/14573743/105825364-91ddca80-5fd0-11eb-9e23-314f5d4caaa8.png)

**Platform (please complete the following information):**
OS: Windows
Node: v14.7.0
NPM: 6.14.7
Browsers: Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.2.
