### ISSUE TITLE
Feature Request: QTabs scrollable on wheel events

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#8382]
**Is your feature request related to a problem? Please describe.**
like other tabs, it would be useful to navigate between tabs when using the mouse wheel

**Describe the solution you'd like**
when the arrows are active listen to the mouse wheel event

**Additional context**
[codepen](https://codepen.io/heartbeatlv-the-bashful/pen/oNzKKzy)

**Comment by pdanpdan** [comment]
Sorry, not going to go in core, there would be to many problems.
And it looks like it's easy to do in username.
