### ISSUE TITLE
QInput produces Touch Bar icon with invalid height in electron

### ISSUE THREAD

**Issue by enedrio** [quasarframework/quasar#8387]
**Describe the bug**
When focusing a QInput field in my electron app, on a MacBook Pro the backend produces this warning:
```Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7feba5ca81d0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.```

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/enedrio/electron-touchbar-warning

**To Reproduce**
(Only tested on MacBook Pro with macOS Big Sur)
1. Download the reproducer repo
2. run `quasar dev -m electron` 
3. click into the input field on the Index page
4. look at the log output in the main process.

**Expected behavior**
Clicking the input field should not produce any warnings in the backend.

**Platform (please complete the following information):**
OS: macOS Big Sur
Node: v12.18.1
NPM: 6.14.5
Yarn: 1.22.10
Browsers: Chrome (Electron)
Electron: 9.0.0

**Comment by pdanpdan** [comment]
Hello. As you are a apple user it would help if you can investigate the problem and post here a full report of what they are trying to to with their touchbar and how that can be solved.
After you find out it would also help if you PR a fix.

**Comment by enedrio** [comment]
Yes, you're right, when replacing the `<q-input />` with a regular `<input />` the main process shows the same warning.

**Comment by enedrio** [comment]
Since the Touch Bar API is still experimental (https://www.electronjs.org/docs/api/touch-bar)
I tried updating the electron version to Version 11.0.0, which made the warning disappear. :)

Is there a specific reason Quasar CLI is using Electron 9.0.0 as default?

**Comment by pdanpdan** [comment]
No specific reason that I know of. It's just that we didn't want to update the dependency across major version changes (by default) in the same major Quasar version.
But it should be no problem to update it in your project.

**Comment by enedrio** [comment]
Ok, so that solves it for me. I'm closing this, since it will be solved as soon as the default electron version is bumped.
