### ISSUE TITLE
Add text-offset in q-btn to solve icon and text alignments issues

### ISSUE THREAD

**Issue by DocBouCou** [quasarframework/quasar#8388]
**Is your feature request related to a problem? Please describe.**
The issue is related to q-btn. When using different libraries for icons, or custom icons, the text might not seem/be vertically aligned. (see for instances #7636 or #7198 )

**Describe the solution you'd like**
As I know this is not something you can take into account (it is obivously not your job to manage custom alignment for random icons :) ), I propose to add a text-offset property (type array [x offset in px, y offset in px] ). If used it would add a custom top-margin (y-offset) and left-margin (x-offset). It would give possibility to easily manage custom alignments, without the need to use slots.

Thanks you for your awesome work.

**Comment by pdanpdan** [comment]
Why would you need some properties for a pure CSS problem?
If the icon is before text then it's as simple as a single rule: https://codepen.io/pdanpdan/pen/wvowEMb
If the icon is after the text add a class to the QBtn and target that class.

**Comment by DocBouCou** [comment]
Thank you for your answer and for the codepen.
