### ISSUE TITLE
Pass global object from SSR extension.js to boot files

### ISSUE THREAD

**Issue by dmitry** [quasarframework/quasar#8389]
Is there are any way to pass object from SSR `extension.js` to the boot file, so it can be used.

The idea: create a client, that can be used as a global object in SSR mode, on the low level there will be a clear cache URL, and in boot it will be used. Once I trigger `/clear-cache` object on the high level will be cleared.

I've checked this file (https://github.com/quasarframework/quasar/blob/dev/app/lib/dev-server.js#L232), seems like there are only context (`app`) object with `req`, `res` and `url` is passed to the boot loaders. Seems like there are no way to pass any object from express to vue app.

**Comment by TobyMosque** [comment]
all boot files already had access to the ssrContext.
https://quasar.dev/quasar-cli/boot-files#Anatomy-of-a-boot-file

**Comment by TobyMosque** [comment]
what exactly do u're trying to do? if u're trying to extend the express app, the boot isn't the best place for it.

**Comment by dmitry** [comment]
@TobyMosque I need to share object on the server on express and boot/vue level.
In express it should clear cache via webhook and on vue level it should use this client with cache data.

**Comment by TobyMosque** [comment]
a middleware didn't work in your case? https://expressjs.com/en/guide/using-middleware.html

**Comment by dmitry** [comment]
@TobyMosque how I can pass some object from middleware to the vue boot? I don't believe it's possible.

**Comment by dmitry** [comment]
```javascript
import getClient from 'client'

module.exports.extendApp = function ({ app, ssr }) {
  ssr.client = getClient()

  app.put('flush', function () {
    ssr.client.flushCache()
  })
})
```

Then in boot

```javascript
export default ({ store, ssrContext, redirect }) => {
  store.client = ssrContext.client
})
```

And then access in Vue components through the store object.

**Comment by pianopronto** [comment]
@dmitry You could probably attach it to the `req` object:
```
app.use(function (req, res, next) {
    req.client = getClient()
    next()
})
```

And get it in boot:
```
export default ({ store, ssrContext, redirect }) => {
  store.client = ssrContext.req.client
})
```

Which is maybe a bit hacky, but only way I can think of getting it to work in dev mode without modifying the core code.

In production, I believe you could do it right in index.js by passing another var into renderToString, but a quick look at the core code and I see no way to do it via dev mode.

```
ssr.renderToString({ req, res, client }, (err, html) => {
```
