### ISSUE TITLE
<q-side-link> don't close left toolbar (drawer) on desktop sites

### ISSUE THREAD

**Issue by RodrigoBernardino** [quasarframework/quasar#839]
### Software version

Quasar: 0.14.1
OS: windows 7
Browsers: Chrome
iOS: none
Android: none
Any other software related to your bug:

### What did you get as the error?
When I click on q-side-link the router goes to the path correctly, but the left menu don't close as expected. Using the chrome's mobile simulation the left menu closes as expected.

### What were you expecting?
The left menu close automatically after router change state.

### What steps did you take, to get the error?
My left menu looks like this:

<q-layout
    id="q-app"
    ref="layout"
    view="lHh Lpr fff"
    :left-class="{'bg-grey-2': true}"
  >
    <q-toolbar slot="header" class="glossy">
      <q-btn
        flat
        @click="$refs.layout.toggleLeft()"
      >
        <q-icon name="menu" />
      </q-btn>
      <q-toolbar-title>
        <img src="./assets/logo suncoke energy brasil_branca.svg" style="height: 50px"/>
      </q-toolbar-title>
    </q-toolbar>

    <div slot="left">
        <q-list-header>Gestão de Produção de Manufatura</q-list-header>
        <q-side-link item to="/Index" exact>
          <q-item-side icon="home" />
          <q-item-main label="Início" sublabel="Visão Geral" />
        </q-side-link>
        <hr>
        <q-list-header>
          <span slot="subtitle">
            Inventário de Carvão de Coque
          </span>
        </q-list-header>
        <q-side-link item to="/Carvao" disabled exact>
          <q-item-side icon="label" />
          <q-item-main label="Carvão" />
        </q-side-link>
        <hr>
        <q-list-header>
          <span slot="subtitle">
            Configuração
          </span>
        </q-list-header>
        <q-side-link item to="/PerfilAcesso" exact>
          <q-item-side icon="supervisor_account" />
          <q-item-main label="Perfis de Acesso" />
        </q-side-link>
        <q-side-link item to="/Teste" disabled exact>
          <q-item-side icon="view_list" />
          <q-item-main label="Auditoria" />
        </q-side-link>
    </div>

    <div class="layout-view">
      <router-view />
    </div>
  </q-layout >

Did I do something wrong or do I have to do something else?
The behavior of clicking outside of the left menu for closing it is possible on desktop sites too?

**Comment by rstoenescu** [comment]
Configure [the threshold](http://quasar-framework.org/components/layout.html#Vue-Properties) point in window width (`left-breakpoint` or `right-breakpoint` props).

Also read about [the breakpoints](http://quasar-framework.org/components/layout.html#The-Breakpoints).

It will all make sense.

**Comment by rstoenescu** [comment]
No problem. Glad that I could help.
