### ISSUE TITLE
Copy to Clipboard for Android

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#8391]
**Describe the bug**
I tried to use `copyToClipboard` for android, I'm get the error `"NotAllowedError: Read permission denied."`, I search for a while, has related before #6013 #6566, but I didn't find sind for this, do anyone know the solution for this?

**Expected behavior**
Copy the text to clipboard

**Platform (please complete the following information)**
Android: 10.0

**Comment by pdanpdan** [comment]
Are you using it in browser (what browser?) or in app (cordova/android?) Also can you check if it works for you case on Android 9? And by the way, what is the code that is not working?

**Comment by pdanpdan** [comment]
I'll suppose it's app - please check here:
https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest
