### ISSUE TITLE
QInput autogrow with limited max-height or number of rows

### ISSUE THREAD

**Issue by fialkovod** [quasarframework/quasar#8393]
In case of building chat or messaging system we use QInput with autogrow.
Is there any way to limit max height of growing as in all modern messengers? 
For example field starts with 1 row, grows with text typing, but in case the limit set (in max-height or even better in number of  rows), input size stop growing and add vertical scroll.

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/yLZmNdd?editors=1100
You need to choose/tweak a good visual style for the field (so that the scrollbar doesn't look bad) but else it's all there

**Comment by mkurak** [comment]
Hello pdanpdan,

The link you provided is currently inactive. I am facing the same issue and looking for a solution. Therefore, if the codes at the provided address contain a solution to this problem, could you please add an updated link?

If there are any other people with suggestions on this matter, please share them. I'm sure there are others like me who are also seeking a solution to this problem.

**Comment by pdanpdan** [comment]
I updated the url. You need to target the QInput with some class and adjust min/max height.

```css
.limited-autogrow.q-field--labeled .q-field__native {
  min-height: 6ch;
  max-height: 13ch
}
```
