### ISSUE TITLE
Set position of q-scroll-area reactively

### ISSUE THREAD

**Issue by utopianknight** [quasarframework/quasar#8394]
**Is your feature request related to a problem?**
Yes. Synced scrolling does not work perfectly. There is a delay in the second component.
https://quasar.dev/vue-components/scroll-area#Scroll-event

**Describe the solution you'd like**
"position" property. Like this:

```JavaScript
<template>
  <q-scroll-area
    ref="First"
    :position="scrollPosition">
      <div>Text</div>
  </q-scroll-area>
  <q-scroll-area
    ref="Second"
    :position="scrollPosition">
      <div>Text</div>
  </q-scroll-area>
</template>

<script>
export default {
  data () {
    return {
      scrollPosition: 0,
    };
  },
  methods:  {
    scroll (position) {
      this.scrollPosition = position;
    },
  }
};
</script>
```

**Additional context**
https://quasar.dev/vue-components/scroll-area#Scroll-event

**Comment by pdanpdan** [comment]
It is normal to have a delay of at least 2 ticks in the generic implementation.
If you want a more precise implementation you need to make you own non generic one and target the DOM components directly.
