### ISSUE TITLE
[docs] BEX - Debug section (background scripts)

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#8395]
When starting with BEX would be nice to have a brief information with screenshot how to debug background scripts. e.g.
-  `background-hooks.js` to view an output from `console.log` you have to use debug console opened from extension property
![image](https://user-images.githubusercontent.com/37825539/106380453-a1835780-63b2-11eb-8a4b-399205a6002a.png)
- Popup window use right click in popup and Inspect
![image](https://user-images.githubusercontent.com/37825539/106380492-f9ba5980-63b2-11eb-85d0-da5c1e85f046.png)

[BEX - documentation](https://quasar.dev/quasar-cli/developing-browser-extensions/build-commands#Developing)
I'm sure it would save a lot of pain when you try the BEX for the first time and wondering why there are no console messages in debug console :-)

**Comment by pdanpdan** [comment]
You can pr it to the docs

**Comment by m0jimo** [comment]
OK, I'm not best in writing in English but I'll try to prepare some draft.

**Comment by m0jimo** [comment]
PR uploaded #8396
