### ISSUE TITLE
Calling "removeFile" and "addFiles" on Uploader in single-file-mode fails when a file is already present

### ISSUE THREAD

**Issue by joelbarmettlerUZH** [quasarframework/quasar#8399]
**Describe the bug**
When the [Uploader](https://quasar.dev/vue-components/uploader) component is in `":multiple="false"` mode, it is not possible to replace a File (`removeFile(oldFile), addFiles([newFile]`) programmatically in one step. Since the uploader only allows one file, it removes the `<input type="file" class="q-uploader__input overflow-hidden absolute-full">` element as soon as one File is uploaded. However, when adding a new File, the Uploader [tries to reset the input.value property](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/uploader/QUploaderBase.js#L257), which does not exist anymore. This leads to an error. This error can be overcome by using nextTick, which ensures that the `<input>` is mounted before a new file is being added using addFiles. However, I propose to fix this bug by checking whether the `<input>` exists before trying to reset its value.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/joelbarmettlerUZH/pen/QWGbxXG

**To Reproduce**
The steps to reproduce this bug are documented within the codepen. I have added them here for completeness:
1. Add an image to the Uploader by hand, eg. by clicking the [+] icon on the top-right corner
2. Now click the button "Add Image Programmatically". This executes two methods: `this.$refs.uploader.removeFile(selected_file)`, and `this.$refs.uploader.addFiles([new_file])` right after each other.
3. Observe the error that is caused by removing and then adding a new file to the uploader programmatically.
4. At this point, the error is clear. To show that using nextTick overcomes the issue temporarily, pease add a new image to the Uploader by hand, eg. by clicking the [+] icon on the top-right corner
4. Now click the "Add Image Programmatically using NextTick()"
5. Observe that the error no longer appears and that the quasar-logo is added to the uploader. This is the expected behaviour.

**Expected behavior**
When the Uploader only accepts one File and the user has already a File selected, I expect that I can use the `removeFile` and `addFiles` methods right after each other in order to simulate "replacing" the users file.

**Platform (please complete the following information):**
OS: Windows 10, Version 1909, Build 18363.1316
Node: v12.16.2
NPM: 6.14.4
Yarn: 1.22.10
Browsers: Chrome Version 88.0.4324.104 (Official Build) (64-Bit)
iOS: -
Android: -
Electron: -

**Additional context**
I will open up a PR to fix this issue myself in the next hour.

**Comment by rstoenescu** [comment]
Thanks for reporting and providing a PR.
This will go into quasar v1.15.3.
