### ISSUE TITLE
q-input - handler() function's "this" is undefined

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#840]
Hello, I am trying to put + and - signs on q-input number to make it like it was before, but it seems like handler() function's "this" is undefined and not bind to Vue instance, is there a workaround?

**Comment by rstoenescu** [comment]
Hi,

Read about ES6 arrow functions and understand how scoping works with them.

```js
handler () {
   // "this" refers to the scope of this block
}

handler: () => {
   // "this" refers to outer scope, so possibly your Vue component
}
```
