### ISSUE TITLE
Feature Request: Can you add an iOS look and feel theme?

### ISSUE THREAD

**Issue by inglesuniversal** [quasarframework/quasar#8401]
Based on Framework7.io I personally like that components render to the user depending on the platform or mobile browser they are using.

Can this be done on Quasar?

or at least to change components like the switch to look thicker the way iOS has it vs material design.

Thanks

**Comment by pdanpdan** [comment]
You can't change the css to match the look you want.
You can make a pr for it, or you can try to pay someone to do it for you.
