### ISSUE TITLE
q-input select all on focus

### ISSUE THREAD

**Issue by fredericoregateiro** [quasarframework/quasar#8402]
**Is your feature request related to a problem? Please describe.**
A simpler way to make my inputs select all text on focus

**Describe the solution you'd like**
A new prop like ```select-all-focus```

**Additional context**
Now i'm using the @focus event like

```javascript
@focus="(input) => input.target.select()"
```

**Comment by pdanpdan** [comment]
It's a very good solution you are using.

**Comment by CynthiaBlue** [comment]
it seems this cannot be used on a number field, a q-input with  mask="##"
Any solutions for a number input?
Thanks.

**Comment by MilosPaunovic** [comment]
Input type `number` does not support mask prop, check warning card:
[https://quasar.dev/vue-components/input#mask](https://quasar.dev/vue-components/input#mask)

Without mask, this solution still works just fine:
[https://codepen.io/milospaunovic/pen/eYEKeVr?editors=101](https://codepen.io/milospaunovic/pen/eYEKeVr?editors=101)

**Comment by tvogel** [comment]
> `@focus="(input) => input.target.select()"`

Thanks a lot! Basing on this, I am using `@focus.once="(input) => input.target.select()"` because I only want it on initial focus, not later on.

**Comment by bonatoc** [comment]
if your `q-input` has a ref, it's even simpler :

**template :**
`         <q-input 
         ref="my_input_ref" 
         @focus="my_input_ref.select()"  
           v-model=... 
         >
`

**script setup :**
`          let my_input_ref = ref(null)
`
