### ISSUE TITLE
[Vue3][Typescript] property names for date options on adjust- and buildDate 

### ISSUE THREAD

**Issue by susnux** [quasarframework/quasar#8403]
**Describe the bug**
The typing for the modification options of `adjustDate` and `buildDate` are not valid for `year` and `month` (and `adjustDate` also for `date`).
Both should support this modifiers, as the name is used for the operation to call in date.js
For `date` you could change the typing of `adjustDate` to: `BuildDateOptions` instead of `ModifyDateOptions` and fix `year` and `month`.

TS-Error:

    Argument of type '{ year: number; month: number; date: number; }' is not assignable to parameter of type 'ModifyDateOptions'.

**Codepen/jsFiddle/Codesandbox (required)**
Not sure what to put there.

**To Reproduce**
1. Create quasar project with Typescript on Vue3 branch
2. Import date from quasar
3. Try to create a Date with `let newDate = date.buildDate({ year:2010, date:5, hours:15, milliseconds:123})`
4. See error `Argument of type '{ year: number; month: number; date: number; }' is not assignable to parameter of type 'BuildDateOptions'.`

**Expected behavior**
No error as this are the arguments required by date.js (and from the documentation).

**Platform (please complete the following information):**
OS: Linux
Node: 12.20.1
NPM:
Yarn: 1.22.10
Browsers: -
iOS: -
Android: -
Electron: -

**Additional context**
This was introduced in https://github.com/quasarframework/quasar/commit/3bbdbac0f3477bcb8669c7de677452daf0f695d6

**Comment by pdanpdan** [comment]
Hello. Please read the upgrade guide.

**Comment by susnux** [comment]
> Hello. Please read the upgrade guide.

I read it, but it only mentioned `addToDate` and `substractFromDate`:
https://github.com/quasarframework/quasar/blob/vue3-work/docs/src/pages/start/upgrade-guide.md#date-utils

Even the documentation still lists `year` and `month` instead of `years` and `months`:
https://github.com/quasarframework/quasar/blob/vue3-work/docs/src/pages/quasar-utils/date-utils.md#set-datetime

If you fore `years` instead of `year`, date.js will fail because there is no js function `setYears` on the Date Object.

**Comment by rstoenescu** [comment]
The add/subtract makes sense to use plural. But for adjustDate it does not. You're not setting years - you are setting one year. Same for the month.

**Comment by rstoenescu** [comment]
Like in English you don't say: In the years 2021 bla bla. Or: In the months of February bla bla.

**Comment by susnux** [comment]
Yes and also the current names are not working, as I mentioned if you set `years` in `adjustDate` it will fail, because there is no function `setYears`, you have to set `year` to get `adjustDate` calling `setFullYear` on the Date Object.
I fixed it for me like this:

https://github.com/susnux/quasar/commit/6dd27e36795f7255f22d8cd5f1675c23a26943c4

**Comment by rstoenescu** [comment]
That's because adjustDate needs month and year. Explained in my previous post why...

**Comment by susnux** [comment]
So not sure if I made clear what is the problem, sorry if I am confusing, but I try it again:
Here is a code sandbox: https://codesandbox.io/s/epic-hopper-12oko?file=/src/pages/Index.vue
Look at line 24, this "works", as it creates the date, but results in a TS Error (see Terminal) as the date.d.ts is invalid.

Line 26 is "valid" but does not work (no TS Error in Terminal, but exception in Console)

**Comment by rstoenescu** [comment]
I see what you mean now. Fixing the typedefs. Thanks for insisting on this.

**Comment by susnux** [comment]
> I see what you mean now. Fixing the typedefs. Thanks for insisting on this.

Maybe

**Comment by susnux** [comment]
sorry

**Comment by rstoenescu** [comment]
Your fix looks correct (https://github.com/susnux/quasar/commit/6dd27e36795f7255f22d8cd5f1675c23a26943c4)
Can you PR it pls?

**Comment by rstoenescu** [comment]
Thanks for PRing. Fix will go into beta 2. Releasing it shortly.
