### ISSUE TITLE
QDialog - close animation not being played (Beta)

### ISSUE THREAD

**Issue by Bjornvdb** [quasarframework/quasar#8407]
**Describe the bug**
When closing a QDialog, the animation will not play. The open animation works.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/gbkwmsay/

**To Reproduce**
1. Open the jsfiddle
2. Click on the alert button
3. The open animation will play
4. Close the dialog
5. The close animation will NOT play

**Expected behavior**
The close animation should be played.

**Additional context**
I think this is because of [this line](https://github.com/quasarframework/quasar/blob/vue3-work/ui/src/components/dialog/QDialog.js#L228). The prop "transitionDuration" does not exists on QDialog. In v1 a default value of 300 was used. 

(FYI: The prop is also being used in the handleShow function)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in beta.2
