### ISSUE TITLE
Vuei18n - exception thrown in component served via dialog plugin [Quasar 2 beta]

### ISSUE THREAD

**Issue by Milancos** [quasarframework/quasar#8408]
**Describe the bug**
Seems like vuei18n loses the app context in components served via quasar dialog plugin in Quasar 2 Beta

Sorry I am working currently for the company and do not have much time to fork a codepen and try to reproduce it
But it should be very easy to reproduce locally in few minutes

Will share snippets of my code

boot files that contains vuei18n installation

```
import messages from "src/i18n";
import { createI18n } from "vue-i18n";
import { boot } from "quasar/wrappers";

export const i18n = createI18n({
    locale: "de",
    fallbackLocale: "en-GB",
    messages,
});

export default boot(({ app }) => {
    app.use(i18n);
});

```

code to call the dialog
```

const options = {
                component: EventCreateReservation,
                componentProps: {
                    freeTables: floor.freeTables
                        .filter((table) => tableId !== table.tableId)
                        .map((table) => table.tableId),
                    tableId,
                },
            };

            const dialog = $q
                .dialog(options)
                .onOk(handleReservationCreation(floor))
                .onDismiss(resetCurrentOpenCreateReservationDialog);

```

part of the code of custom component
```
emits: [...useDialogPluginComponent.emits],
    setup(props, { emit }) {
        const { t } = useI18n();
        const state = reactive<State>({
            guestName: "",
            numberOfGuests: 2,
            guestContact: "",
            reservationNote: "",
            groupedWith: [],
        });

```

**Expected behavior**
Should be attached to the app that it is installed on
Works completely fine on all other components
I am not sure if this is a specific quasar problem but it affects just dialog plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/43552501/106798515-5c834d80-665e-11eb-9b41-67a17290fb5c.png)

**Platform (please complete the following information):**
OS: Windows
Node: 12
NPM: 6
Browsers: Chrome, Firefox, etc..

**Comment by Smrtnyk** [comment]
Same issue for me, not sure on which end is the issue
But I think I saw in one of the Razvans PR's that new vue app is created for dialog but I am not sure
If that is the case maybe that explains why it is not recognized

**Comment by rstoenescu** [comment]
Fix is on the way. Testing it thoroughly tomorrow.

**Comment by rstoenescu** [comment]
Thank you for reporting!
Fix will be available in beta.2
