### ISSUE TITLE
[Quasar 2 Beta] useDialogPluginComponent.emits not typed properly

### ISSUE THREAD

**Issue by Smrtnyk** [quasarframework/quasar#8409]
**Describe the bug**

 I know it is the begining and there is a lot to do but just in case it doesn't get forgoten
 When we use ts with quasar v2 beta now the `useDialogPluginComponent.emits` is not typed properly and emits property gets infered as `any[]`

**Comment by rstoenescu** [comment]
Until this is fixed, you can use the following workaround:
```
...(useDialogPluginComponent.emits as string[])
```

**Comment by rstoenescu** [comment]
Fix will be available in beta.2
