### ISSUE TITLE
Invisible text in text area in modal on iOS

### ISSUE THREAD

**Issue by jsfeldman** [quasarframework/quasar#841]
### Software version

Quasar: 0.1.4
OS: iOS
Node: v8.1.4
NPM: 5.0.3
Browsers: Safari iOS
iOS: 10.3.3
Android: Doesn't happen
Any other software related to your bug:

### What did you get as the error?
When typing in an input or textarea component in a modal on iOS safari the text will have a long delay before appearing (sometimes requiring to click outside the input field). Here's a picture: 
![image](https://user-images.githubusercontent.com/8559979/29774788-d04815a0-8bd0-11e7-9461-936c88f1587f.png)

The text between first letter and the cursor isn't spaces but actual letters.

### What were you expecting?
The text to appear as you type.

### What steps did you take, to get the error?
Create a textarea in a modal and try typing in the textarea on safari iOS.

**Comment by rstoenescu** [comment]
Hi,

I'm sorry, don't know how this ticket slipped out for so long. You need to use, for example in v0.15, the `max-height` prop.

```html
<q-input type="textarea" :max-height="100" v-model="myModel" />
```

For some reason, iOS is buggy when the textarea height auto-grows.

**Comment by antoineschaller** [comment]
Hi,

I still encounter the exact same issue in v0.15, and the use of `:max-height="100"` does not seem to resolve it. Any ideas what might now be responsible for it?

**Comment by Klaasvaak** [comment]
Triggering a new layer in Safari sometimes solves these issues. You can trigger it by adding `-webkit-transform: translateZ(0px)` to the textarea.
