### ISSUE TITLE
[docs] [Quasar 2 beta] Anchors with special characters aren't working

### ISSUE THREAD

**Issue by jeroenqui** [quasarframework/quasar#8411]
First off, hats off and massive respect for the work on Quasar 2!
Really impressed by the quality and improvements.
For now, have only found 1 small issue in the docs.

For example:
Go to https://next.quasar.dev/vue-components/table
On the right, click on "Sticky header/column"
It links to: https://next.quasar.dev/vue-components/table#Sticky-header%252Fcolumn and does not scroll to the related anchor.
It should link to: https://next.quasar.dev/vue-components/table#Sticky-header%2Fcolumn

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix for docs will be available on the next deployment.
