### ISSUE TITLE
[bug] Quasar CLi isn't generating the store correctly while using Quasar V2

### ISSUE THREAD

**Issue by TobyMosque** [quasarframework/quasar#8412]
**Describe the bug**
If while u're creating a new ts project based in the next brand, and you decide to not use vuex, and after that you decide to add a new vuex module using the command `quasar new store -f ts`, the `src/index/store.ts` will not be Vue 3 compliant.

**Codepen/jsFiddle/Codesandbox (required)**
...

**To Reproduce**
1. create a new project without vuex and standard eslint rules.
2. use the command `quasar new store -f ts` to add a new module
3. the generated `src/store/index.js` is using the Vue 2 syntax.

**Expected behavior**
the `src/store/index.js` would be Vue 3 compliant

**Screenshots**
...

**Platform (please complete the following information):**
OS: Linux(4.19.128-microsoft-standard) - Ubuntu 20.04 LTS running on Windows 10 WSL2
Node: 14.15.2
NPM: 6.14.9
Yarn: 1.22.10
Browsers:
iOS:
Android:
Electron:

**Additional context**
...

**Comment by IlCallo** [comment]
Closing as it's fixed into @quasar/app-v3.0.0-beta.2

**Comment by rstoenescu** [comment]
@IlCallo not sure about templates/app/ts/store ones, which is why I didn't close it. If you can confirm those are working too then pls close.

**Comment by IlCallo** [comment]
Yeah, it should be the same of starter kit one. You changed the applied linting, but nothing really important
