### ISSUE TITLE
[Bug] Quasar 2: BeforeEach navigation guard is not firing for initial request while registered in boot files

### ISSUE THREAD

**Issue by Arsync** [quasarframework/quasar#8414]
**Describe the bug**
BeforeEach navigation guard is not firing while it registered within boot file for direct navigation to our SPA.

**Codepen/jsFiddle/Codesandbox (required)**
...

**To Reproduce**
Put following code in `.quasar/client-entry.js` and see the console output for 'First' and 'Second' messages of guards. 
```js
createQuasarApp(createApp)
  .then(app =>
  {
    // Ok!
    app.router.beforeEach((to, from, next) =>
    {
      console.log(`First: navigated to ${to.fullPath}`);
      next();
    });

    return Promise.all([
      import(/* webpackMode: "eager" */ 'boot/i18n'),
      // import(/* webpackMode: "eager" */ 'boot/our-boot-file')
    ]).then(bootFiles =>
    {
      // Nope! This guard will not be called at startup.
      app.router.beforeEach((to, from, next) =>
      {
        console.log(`Second: navigated to ${to.fullPath}`);
        next();
      });

      const boot = bootFiles
        .map(entry => entry.default)
        .filter(entry => typeof entry === 'function')

      start(app, boot)
    })
  })
```
To ensure that second guard is working:
- navigate to any wrong url within SPA.
- click on "Go Home" button.
- console will show the 'First' and the 'Second' messages.

**Expected behavior**
BeforeEach navigation guard must catch initial navigation request in boot files.

**Platform (please complete the following information):**
OS: Windows 10 (1809)
Node: v12.16.1
Yarn: 1.22.4
Browsers: Chrome 88.0.4324.146

**Comment by Smrtnyk** [comment]
I have the same issue
At first I thought it is some of the vue router 4 breaking changes which I need to go through and fix but after a while realized something is happening here

**Comment by rstoenescu** [comment]
Would be a good idea to put that beforeEach hook code directly in /src/router/index.js

**Comment by Arsync** [comment]
Some portion of required dependencies must be initialized before this guard. For example, boot file inits the IdentityManager in async manner, configures its persisted storage to obtain tokens...
```ts
export default boot(async ({ router, store }) => {

  const manager = await initSomethingHeavy();
  
  // Navigation delayed until initialization complete.

  router.beforeEach(async (to, from, next) => {
    if (!await manager.canAccess(to)) {
        // do something.
    }
    next();
  });
  
});
```
It not belongs to router, so I natively decided to put it in boot file where we have router, store and other things in proper boot files order.

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v3.0.0-beta.2

**Comment by rstoenescu** [comment]
@Arsync your approach is correct. Releasing q/app 3.0.0-beta.2 (which has the fix) in a bit.

**Comment by Arsync** [comment]
Still not called, if boot function contains async action before guard attached. Sample:
```ts
import { boot } from 'quasar/wrappers';

function timeout (ms: number)
{
    return new Promise(resolve => setTimeout(resolve, ms));
}

// boot file:
export default boot(async ({ router }) =>
{
  console.log(`[Guard Checker] Now starting for path "${router.currentRoute.value.fullPath}"`);

  await timeout(0); // even 0 ms! Comment this line to let guard work for initial request

  router.beforeEach((to, from, next) =>
  {
    console.log(`[Guard Checker] BeforeEach called for path "${to.fullPath}"`);
    next();
  });
});
```

**Comment by Arsync** [comment]
Working only if we put `app.use(router)` after boot files cycle:
```js
async function start ({ app, router, store }, bootFiles) {

  // omitted code

  for (let i = 0; hasRedirected === false && i < bootFiles.length; i++) {
    try {
      await bootFiles[i]({
        app,
        router,
        store,
        ssrContext: null,
        redirect,
        urlPath,
        publicPath
      })
    }
    catch (err) {
      // omitted code
      console.error('[Quasar] boot error:', err)
      return
    }
  }

  // omitted code

  app.use(router)
  app.use(store)
  app.mount('#q-app')
}

createQuasarApp(createApp)
  .then(app =>
  {
    // omitted code
  })

```
But I cannot imagine all other consequences of this.

**Comment by rstoenescu** [comment]
You're right. Fixed in q/app beta 3

**Comment by Arsync** [comment]
If I understood the new patch correctly, then it can lead to uninitialized store while accessing it in boot files before client hydration.

**Comment by rstoenescu** [comment]
Regarding store: that's not the case. The store is not yet installed into the app, but it's fully initialized AND working.
The app.use(store) part just injects the store reference.

**Comment by Arsync** [comment]
I mean, this line
https://github.com/quasarframework/quasar/blob/e5ba61dff440226f97bb823e8b3657477c1aad74/app/templates/entry/client-entry.js#L126
is placed after the boot files cycle:
https://github.com/quasarframework/quasar/blob/e5ba61dff440226f97bb823e8b3657477c1aad74/app/templates/entry/client-entry.js#L89-L91
If I will try to access server-rendered state in my boot file on client side, is it possible?

**Comment by rstoenescu** [comment]
SSR is not ready yet, so this line doesn't matter for the moment as it's for SSR only.
