### ISSUE TITLE
QInfiniteScroll with QScrollArea as scroll-target keeps calling onLoad infinitely 

### ISSUE THREAD

**Issue by DiaaEddin** [quasarframework/quasar#8417]
**Describe the bug**
QInfiniteScroll keeps calling onLoad when setting scroll-target to QScrollArea

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/DiaaEddin/pen/PobZEqG?editors=101](https://codepen.io/DiaaEddin/pen/PobZEqG?editors=101)

**To Reproduce**
Place an infinite scroll inside scroll area and set scroll target to scroll area.

**Expected behavior**
The QInfiniteScroll should call onLoad until the scrollarea is full of content or if the offset from bottom is less than the offset value (default 500px)

**Platform (please complete the following information):**
Quasar Version: 1.15.2
@quasar/app Version:
Quasar mode:
  [ ] SPA
  [ ] Capacitor
Tested on:
  [ ] SPA
  [ ] Capacitor

**Comment by pdanpdan** [comment]
you used the wrong scrollTarget, it should be the scrollable element (`.scrollareaclass > .scroll`)

**Comment by DiaaEddin** [comment]
Thank you, It would be helpful to mention this in the documentation.
