### ISSUE TITLE
[Quasar 2][Typescript] "onDialogOK" typed as "onDialogOk" for useDialogPluginComponent interface

### ISSUE THREAD

**Issue by Smrtnyk** [quasarframework/quasar#8418]
**Describe the bug**
There is a typo in quasar types for `useDialogPluginComponent`

onDialogOK function is named as onDialogOk which causes wrong autocompletion and runtime error when invoked

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available on 2.0.0-beta.3.
