### ISSUE TITLE
Dialog plugin don`t focused buttons

### ISSUE THREAD

**Issue by aperture-it** [quasarframework/quasar#8419]
**Describe the bug**
Dialog option `focus` not working

**Codepen/jsFiddle/Codesandbox (required)**
`https://codepen.io/aperture-it/pen/eYBJLvQ`

**To Reproduce**
1. Go to `https://codepen.io/aperture-it/pen/eYBJLvQ`
2. Click on button «CONFIRM» for open dialog
3. There is no focus on any buttons in the modal dialog

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.2
Quasar mode:
  [* ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [* ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Ubuntu 18.04
Node: v14.15.4
NPM: 7.5.2

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in beta.3.
