### ISSUE TITLE
Make Electron work with Typescript in Quasar project

### ISSUE THREAD

**Issue by Exxili** [quasarframework/quasar#8422]
**Describe the bug**
Not so much a bug as a extra quality of life addition to those of us who like typescript.

I wanted to run a Quasar Typescript based app along with Electron with Typescript support

Adding Electron support to a quasar app via "quasar mode add electron" creates the following files:
![image](https://user-images.githubusercontent.com/32906176/107084644-393bd800-67ef-11eb-9cdd-8486ebeae5a1.png)

Simply changing these 2 files to typescript (and tweaking to support typings) is not enough,  when attempting to run with "quasar dev -m electron" you will get the following error:
![image](https://user-images.githubusercontent.com/32906176/107085630-a734cf00-67f0-11eb-9227-bce18620cb89.png)

**Solution**
In order to change these files to be typescript you need to perform the following changes:
1) Include the main-process folder in tsconfig.json, AND set noEmit to False ( noEmit is false by default, but if you don't explicitly put it in tsconfig, it does not seem to work)
```js
{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "baseUrl": ".",
    "experimentalDecorators": true,
    "noEmit": false
  },
  "include": [
    "./src-electron/main-process/**/*",
    "./src/**/*" // Note: This needs to be added to fix some ESLint errors
  ]
}
```

2) Set your SourceFiles in quasar.conf.js:
```js
module.exports = configure(function (ctx) {
  return {
    sourceFiles: {
      electronMainDev: 'src-electron/main-process/electron-main.dev',
      electronMainProd: 'src-electron/main-process/electron-main'
    },
```
3) Configure chainWebpack in quasar.conf.js under the Electron Section:
```js
      chainWebpack (cfg) {
        cfg.resolve.extensions.prepend('.ts').prepend('.tsx')

        cfg.module
          .rule('typescript')
          .test(/\.ts?$/)
          .use('ts-loader')
          .loader('ts-loader')
          .options({
            onlyCompileBundledFiles: true,
            transpileOnly: false
          })
      }
```
4) Change your electron-main.js and electron-main.dev.js to Typescript files:
(Quite a few changes here, tweaking of types etc So I will just post my two files as a Gist for those that need help)
* electron-main.ts > https://gist.github.com/Exxili/1b918d718dec9d305e408d63aa851fc1
* electron-main.dev.ts > https://gist.github.com/Exxili/d74e71f005f84c37e4e00cf71957450a

5) Lastly, when changing the above files you will get an error regarding "__statics does not exist"
![image](https://user-images.githubusercontent.com/32906176/107086627-2f67a400-67f2-11eb-92dd-70ba696bd418.png)
Fixing this by creating a new file in "main-process" folder called "node.d.ts" as below:
```ts
declare module NodeJS {
  interface Global {
      __statics: any
  }
}
```

Thats it!  I was then able to run the app with "quasar dev -m electron", as well as build with "quasar build -m electron"

**Platform (please complete the following information):**
Quasar Version:  2.1.14
@quasar/app Version: ^2.0.0
Quasar mode:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [x] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [x] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Windows 10 Pro
Node: v12.18.4
NPM: 6.14.6
Yarn: N/A
Electron: ^9.4.2

**Comment by IlCallo** [comment]
> noEmit is false by default, but if you don't explicitly put it in tsconfig, it does not seem to work

noEmit options is required to avoid errors with `.babelrc` and other config files, it's set to true by the quasar tsconfig preset

Thanks for taking the time to explore and document how to use Electron with TS!

**Comment by rstoenescu** [comment]
Just pushed out a commit for out of the box TS support for Electron mode in Quasar v2. Thanks to you. Also, MAJOR improvements in Electron coming in next beta.

**Comment by Exxili** [comment]
Hey no problem, glad i could help, thank you for supporting TS,  used Quasar Framework for some time now and have nothing but praise!

**Comment by rstoenescu** [comment]
Closing as the next Quasar v2 beta is around the corner.

**Comment by IlCallo** [comment]
The best way to keep the global `noEmit: true` but still solve the electron transpilation files issue is to override that property directly in the loader options. Probably all files which uses the node version of Quasar webpack chain (electron, pwa, other modes) would hit the same problem.

This should be the correct chain extension, without touching the global tsconfig
```js
chainWebpack (cfg) {
        cfg.resolve.extensions.prepend('.ts').prepend('.tsx')

        cfg.module
          .rule('typescript')
          .test(/\.ts?$/)
          .use('ts-loader')
          .loader('ts-loader')
          .options({
            compilerOptions: {
              noEmit: false
            },
            onlyCompileBundledFiles: true,
            transpileOnly: false
          })
      }
```

@Exxili in case you want to update the code in the initial post
