### ISSUE TITLE
[Quasar2][QSelect]Selecting option after filtering error

### ISSUE THREAD

**Issue by aperture-it** [quasarframework/quasar#8423]
**Describe the bug**
In the filter function, the argument the doneFn has a second callback with Vue reference to the QSelect which triggered the filtering parameter. This reference is undefined and the callback throws an exception.

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/aperture-it/pen/MWbyYbX](https://codepen.io/aperture-it/pen/MWbyYbX)

**To Reproduce**
1. Go to [https://codepen.io/aperture-it/pen/MWbyYbX](https://codepen.io/aperture-it/pen/MWbyYbX)
2. Open browser console
3. Input text in the QSelect
4. See error `ref is undefined`

**Screenshots**
[https://i.imgur.com/AZgR97D.png](https://i.imgur.com/AZgR97D.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.2
Quasar mode:
[* ] SPA
[ ] SSR
[ ] PWA
[ ] Electron
[ ] Cordova
[ ] Capacitor
[ ] BEX
Tested on:
[* ] SPA
[ ] SSR
[ ] PWA
[ ] Electron
[ ] Cordova
[ ] Capacitor
[ ] BEX
OS: Ubuntu 18.04
Node: v14.15.4
NPM: 7.5.2

**Comment by rstoenescu** [comment]
Fix will be available in beta.3
