### ISSUE TITLE
[v2][docs] Document CSS variable name changes in upgrade guide

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#8424]
_Reported by coder1337#4362 in v2-help>upgrading channel on Discord._

The naming of CSS variables is changed in v2, changes in the helper functions(i.e. `getBrand` -> `getCssVar`) are documented in the upgrade guide, but their naming structure is not mentioned there. As the naming structure of these variables is documented in v1, there might be some people that are referencing those variables in their CSS code like `color: var(--q-color-primary)` which will get broken now.

## v1
`--q-color-${name}` (example: `--q-color-primary`, `--q-color-secondary`)

https://github.com/quasarframework/quasar/blob/dev/docs/src/pages/style/color-palette.md#dynamic-change-of-brand-colors-dynamic-theme-colors
https://github.com/quasarframework/quasar/blob/dev/ui/src/utils/colors.js#L266-L289

## v2
`--q-${name}` (example: `--q-primary`, `--q-secondary`)

https://github.com/quasarframework/quasar/blob/vue3-work/docs/src/pages/style/color-palette.md#dynamic-change-of-brand-colors-dynamic-theme-colors
https://github.com/quasarframework/quasar/blob/vue3-work/ui/src/utils/set-css-var.js

**Comment by rstoenescu** [comment]
Fixed
