### ISSUE TITLE
QSelect doesn't work with lazy-loaded options

### ISSUE THREAD

**Issue by rafte** [quasarframework/quasar#8427]
**Describe the bug**
After lazy-loading options for QSelect and picking one of the options, the visible QSelect value is not updated.

**To Reproduce**
1. Go to https://next.quasar.dev/vue-components/select#Lazy-loading
2. Click on the select box
3. Wait for lazy-loaded options, and then select one
4. The value for select box is not updated

**Expected behavior**
The select box is expected to be populated with the selected option.

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.2
@quasar/app Version: 3.0.0-beta.3

**Comment by aperture-it** [comment]
This is a typo in the sample script `model: null,` => `model: ref(null),`

[](https://codepen.io/aperture-it/pen/ExNKNwK)

**Comment by rstoenescu** [comment]
Indeed. Fixed the docs example (will be available on next deployment).
Thank you to both of you.
