### ISSUE TITLE
Quasar-CLI internationalization doesn't work

### ISSUE THREAD

**Issue by alexandreDavid** [quasarframework/quasar#8429]
**Describe the bug**
By default, the configuration is wrong to use $t. The problem is the default language key is 'en-US' instead of 'en-us'. i18n is parametized to manage lowercase.

**Platform (please complete the following information):**
Quasar Version: ^2.0.0-beta.1
@quasar/app Version: ^3.0.0-beta.1
Quasar mode:
  [ ] SPA
  [ ] SSR
  [ x ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: MacOs BigSur
Node: v12.13.1
NPM: 7.5.2
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by hawkeye64** [comment]
@alexandreDavid Can't you just `.toLowerCase()` on the value, before passing to `$t`?

**Comment by alexandreDavid** [comment]
@hawkeye64 I could but It might be automatic, I didn't change anything about the default configuration

**Comment by pdanpdan** [comment]
How is i18n parameterized?

**Comment by alexandreDavid** [comment]
When you create your app with Quasar-cli, you've 2 files for i18n.
 * /src/boot/i18n.js : Ln6 --> `locale: 'en-us',`
 * /src/i18n/index.js : Ln4 --> `'en-US': enUS`

If the keys don't match, the function `this.$t('myLabel')` use by i18n can find the matched label.
If you use `Quasar.lang.getLocale()`, the return is 'en-US' that means the key in /src/boot/i18n.js should be 'en-US'

**Comment by rstoenescu** [comment]
I assume you are upgrading a Quasar v1 project to v2. If you're using the lang.getLocale() helper to initialize the default vue-i18n language pack, then just rename your locales to match the new [standard browser scheme](https://next.quasar.dev/start/upgrade-guide#Quasar-language-packs).
