### ISSUE TITLE
[bug]  Uploader component click the addFile , the browser console show error that it is [ VM14:1 Uncaught TypeError: Cannot read property 'match' of null ]  

### ISSUE THREAD

**Issue by yanghuilong** [quasarframework/quasar#8431]
**Describe the bug**
[bug]  Uploader component click the addFile , the browser console show error that it is [ VM14:1 Uncaught TypeError: Cannot read property 'match' of null ]  

**To Reproduce**
official website https://quasar.dev/
1. First, Go to other page, 
2. Again, Go to the Uploader component page, 
3. Click on 'add file' method

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10112138/107133958-8e2f3980-6928-11eb-9708-d364458a6dcd.png)

**Comment by pdanpdan** [comment]
Hello.
I cannot reproduce it - can you please add the requested details about browser, version, os, and some steps to allow us to reproduce it?

**Comment by yanghuilong** [comment]
@pdanpda
Hello,
The error was displayed  in the official website .
browser is The latest version of EDGE
1. open browser development tools
2. go into Uploader component page
3. then switch to other component page
4. again go into Uploader component page
5. click the addfile button of Uploader component

the error can reproduce.

**Comment by hawkeye64** [comment]
@pdanpdan Using Browserstack.com and testing with Edge 88 it gets a CORS issue on the quasar.dev docs
![image](https://user-images.githubusercontent.com/10262924/107150016-f1b16b00-6918-11eb-9c8f-db24f8d0cdd0.png)

**Comment by pdanpdan** [comment]
@hawkeye64 this is normal and expected and had nothing to do with the issue :D

**Comment by pdanpdan** [comment]
I tested on latest edge on both windows 10 and ubuntu, I cannot reproduce it.
I suppose you have some extensions installed, but I really need a clear step by step case that can reproduce it.
The OS, exact page you are using, what you click on, in what page (full URL), in what order.
Also please expand the error messages in the console and copy/paste them here.

**Comment by yanghuilong** [comment]
> I tested on latest edge on both windows 10 and ubuntu, I cannot reproduce it.
> I suppose you have some extensions installed, but I really need a clear step by step case that can reproduce it.
> The OS, exact page you are using, what you click on, in what page (full URL), in what order.
> Also please expand the error messages in the console and copy/paste them here.

I just send you email about details pls kindly check , thank you.

**Comment by yanghuilong** [comment]
thank you , i just try is again , the error is caused by some extensions installed in my browser .
