### ISSUE TITLE
QV2: Component Library - resolveComponent can only be used in render() or setup().

### ISSUE THREAD

**Issue by geraldbiggs** [quasarframework/quasar#8432]
Description:
I'm taking a stab at V2 CLI with a branch of some of my projects. 

Locally on a monorepo, I have two apps, that share a component library (that wraps quasar components to expand upon some of their features). 

Upon upgrading and loading the component package as a plugin, I receive the error:

runtime-core.esm-bundler.js?d941:38 [Vue warn]: resolveComponent can only be used in render() or setup().
```
//boot for component
export default boot(({ app, store }) => {
  app.use(MyLibrary, store);
});
```

```
//assume fancy features
<template>
  <q-btn />
</template>
<script>
import {defineComponent} from 'vue';
export default defineComponent({
  name: "BaseButton",
});
</script>
```

This one works fine
```
<template>
  <div />
</template>
<script>
import {defineComponent} from 'vue';
export default defineComponent({
  name: "BaseButton",
});
</script>
```
I tested on fresh installs. and checked for differing versions of vue. Everything appears to be fine there. Additionally, switching `<q-btn>` to `<div>` seems to tell me everything is loaded correctly.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3213608/107136586-c3a93800-68d2-11eb-8461-39bbe069c052.png)
![image](https://user-images.githubusercontent.com/3213608/107136607-f18e7c80-68d2-11eb-90c8-fed8b183fdfb.png)

**Platform (please complete the following information):**
Operating System - Darwin(18.7.0) - darwin/x64
NodeJs - 12.13.0

Global packages
  NPM - 6.12.0
  yarn - 1.22.5
  @quasar/cli - 1.1.3
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.0.0-beta.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.0.0-beta.3 -- Quasar Framework local CLI
  @quasar/extras - 1.9.16 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.0.5 -- vue
  vue-router - 4.0.3
  vuex - 4.0.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.12.3 -- Babel compiler core.
  webpack - 4.44.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 4.1.3 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qenv - 1.0.4 -- Load targeted variables into your quasar project

**Comment by IlCallo** [comment]
Quasar uses an auto-loader feature to automatically include Quasar components when they're used. There may be a naming conflict there. Could you rename your library components to use another prefix which is not `q-` and try again?

**Comment by geraldbiggs** [comment]
Hi, thanks for responding. I put together a minimal repro to see if it was an error in my setup.

**Comment by geraldbiggs** [comment]
Discovered issue with how the project was hoisting resources.

**Comment by IlCallo** [comment]
Can you be more specific? So other people coming here with the same problem will have a better explanation

**Comment by chrislandeza** [comment]
Hi @geraldbiggs, can you give specific details on how you solve this problem? currently dealing with this right now.

**Comment by GastienneLea** [comment]
Hi, having the same issue

**Comment by geraldbiggs** [comment]
Hi, a lot happened between then and now - sorry to have let this dangle. The best I can do is recommend a small checklist of recommendations: 

Take the time to do a fresh project, if only to exclude any complexity of upgrading in place. I did so for the sole purpose of successfully implementing my package of components. 

In my quasar.conf.js I included the list of components wrapped by my custom library rather than using the "auto setting." 

The boot file loading the library is a standard `app.use(ComponentLibrary);`

Additionally, it's essential to check any package using Vue is properly made external, and that the versions aren't mismatched. EX: All my `vite`, `@vitejs/plugin-vue`,  `@vue/compiler-sfc`, versions match across each package. 

Below are examples of my relevant app files and component library files. 

```
//quasar.conf.js

framework: {
    components: ["QBtn"]
}
// ...etc
```

My package.json app consuming the component library:

```
{
  "name": "app",
  "version": "0.0.1",
  "description": "A Quasar Framework app",
  "productName": "app",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "QENV=development quasar dev",
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "component-library": "0.1.0",
    "core-js": "^3.6.5",
    "quasar": "^2.0.3",
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.15.0",
    "@quasar/app": "^3.0.4",
    "@quasar/quasar-app-extension-qenv": "^1.1.0",
    "@quasar/quasar-app-extension-testing": "^1.0.3",
    "@quasar/quasar-app-extension-testing-unit-jest": "^2.2.2",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-jest": "^24.4.0",
    "eslint-webpack-plugin": "^3.0.1"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 12.22.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}
```

Package.json of the component library: 
```
{
  "name": "component-library",
  "version": "0.1.0",
  "main": "./dist/component-library.umd.js",
  "module": "./dist/component-library.es.js",
  "exports": {
    ".": {
      "import": "./dist/component-library.es.js",
      "require": "./dist/component-library.umd.js"
    }
  },
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.4.0",
    "@vue/compiler-sfc": "^3.1.1",
    "vite": "^2.4.4"
  }
}
```

Vite config
```
import vue from "@vitejs/plugin-vue";
const path = require("path");

/**
 * https://vitejs.dev/config/
 * @type {import('vite').UserConfig}
 */
export default {
  resolve: {
    dedupe: ["vue"],
  },
  plugins: [vue()],
  build: {
    lib: {
      entry: path.resolve(__dirname, "src/main.js"),
      name: "ComponentLibrary",
    },
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: [
        "vue",
      ],
      output: {
        // Provide global variables to use in the UMD build
        // for externalized deps
        globals: {
          vue: "Vue",
        },
      },
    },
  },
};
```

**Comment by chrislandeza** [comment]
@geraldbiggs @GastienneLea This was due to multiple instances of Vue. In my case, I only encountered this problem when testing my extension via yarn link or npm link. Everything works fine if I publish the extension and pull it normally on the hosting app. This article will give us an idea of why we're encountering the issue: https://newbedev.com/how-to-create-vue-package-that-imports-another-component 

I resolved mine by adding vue alias to my test application
```
  build: {
      vueRouterMode: 'hash', // available values: 'hash', 'history'
      extendWebpack (cfg, { isServer, isClient }) {
        cfg.resolve.alias = {
          ...cfg.resolve.alias, // This adds the existing alias

          // This will make sure that the hosting test app is pointing to only one instance of vue.
          vue: path.resolve('./node_modules/vue')
        }
      },
```

**Comment by stefanvanherwijnen** [comment]
As stated above, this is definitely an error with multiple vue instances in your app.
If you're using Vite, note that Vite prebundles some dependencies and if one of them use `vue` it might prebundle a different version from the one defined in your `resolve.alias`.
Have a look at `/node_modules/.vite/chunk-*.js` and see if any vue code is prebundled.

To prevent/fix this, add the following to vite.config:
```
    optimizeDeps: {
      exclude: ['vue']
    }
```

Also when developing and using local packages with yarn, you either need to delete the node_modules in the dependency folder, or use yalc to add the dependency to your project.

So if anyone encounters this:
- Make sure all your projects and packages have compatible versions of Vue.
- Make sure any dependencies/libraries have `vue` as an external dependency (i.e. the compiled bundle contains `import ... from 'vue'`)
- Check `node_modules` for nested vue instances (don't forget the .vite folder if you use vite) and remove any vue instances other than `node_modules/vue` (use yalc or remove node_modules from linked packages)

**Comment by shunyue1320** [comment]
vue.config.js

add
```
module.exports = {
    ...
    configureWebpack:{
        resolve:{
            alias:{
               vue: path.resolve('./node_modules/vue')
            }
        }
    }
}
```

**Comment by ErhardScampi** [comment]
Same error comes when using q-parallax or  q-img. in the following situation :
(Update of the quasar stack yesterday uses it with webpack)
I have Pinia and get images from aws in a store. The store is bound to a page.
The page calls a component  and the url
is given via props to this component  Here is the boiled down component :

if the q of q-img is deleted it works.

`<template>
  <div>
    {{ image }}
    <div v-if="image">
    <q-img :src="image"/>
    </div>
  </div>
</template>
<script setup>
import {ref} from "vue"
const props = defineProps([
  "img",
]);
const image = ref(props.img)
</script>`

same behavior is when I use in the  Component the Pinia store via a getter q-img does not work img works.

Doing the very same thing one level higher - means I do not use the sub component at all . I do it directly on the page level q-img works the error does not occur. 

Perhaps this helps

**Comment by ErhardScampi** [comment]
Same error comes when using q-parallax or q-img. in the following situation :
(Update of the quasar stack yesterday uses it with webpack)
I have Pinia and get images from aws in a store. The store is bound to a page.
The page calls a component and the url
is given via props to this component Here is the boiled down component :

if the q of q-img is deleted it works.

`
template>

  <div>

    {{ image }}

    <div v-if="image">
    <q-img :src="image"/>
    </div>
  </div>
</template>
<script setup>
import {ref} from "vue"

const props = defineProps([
  "img",
]);
const image = ref(props.img)
</script>

`

Doing the very same thing one level higher - means I do not use the sub component at all . I do it directly on the page level q-img works the error does not occur.

Perhaps this helps perhaps this error should be reopened

**Comment by stefanvanherwijnen** [comment]
@ErhardScampi
Could you try running `npm dedupe` in the project?

**Comment by ErhardScampi** [comment]
@stefanvanherwijnen 

I have done this, but same error. Also with deleting node_modules and reinstalling with yarn.

**Comment by LennonSantos** [comment]
> @geraldbiggs @GastienneLeaIsso ocorreu devido a várias instâncias do Vue. No meu caso, só encontrei esse problema ao testar minha extensão via fio link ou link npm. Tudo funciona bem se eu publicar a extensão e puxá-la normalmente no aplicativo de hospedagem. Este artigo nos dará uma ideia de por que estamos enfrentando o problema: https://newbedev.com/how-to-create-vue-package-that-imports-another-component
> 
> Resolvi o meu adicionando o alias vue ao meu aplicativo de teste
> 
> ```
>   build: {
>       vueRouterMode: 'hash', // available values: 'hash', 'history'
>       extendWebpack (cfg, { isServer, isClient }) {
>         cfg.resolve.alias = {
>           ...cfg.resolve.alias, // This adds the existing alias
> 
>           // This will make sure that the hosting test app is pointing to only one instance of vue.
>           vue: path.resolve('./node_modules/vue')
>         }
>       },
> ```

works for me! Thanks!
