### ISSUE TITLE
I can't build the quasar by the tslint issue of electron-main.dev.js/electron-main.js. I did never edit these standard two files after project setup

### ISSUE THREAD

**Issue by forevereffort** [quasarframework/quasar#8433]
I did run `yarn quasar build`. but it was failed as the tslint issue of electron-main.dev.js and electron-main.js. I did never edit the two files after project setup.

![V3XfT](https://user-images.githubusercontent.com/58469967/107150131-3ed42200-6997-11eb-963d-d6d85861341e.png)

How can I fix these issues?

Regards

**Comment by hawkeye64** [comment]
@forevereffort I think you need to follow instructions here: https://github.com/quasarframework/quasar/issues/8422
