### ISSUE TITLE
Custom emit functions for Dialog Plugin with custom components

### ISSUE THREAD

**Issue by jdpmoore** [quasarframework/quasar#8436]
I appreciate this is potentially a fairly niche case, but I found myself editing Quasar (global-dialog.js) to obtain some desired functionality for a project recently.

I use custom components with the dialog plugin all the time, and I found myself needing to pass an event back to the parent component, without triggering `ok` or `cancel`, so I added a function definition for onCustom() under API. This works perfectly for my use case, as I simply emit `custom` from my dialog component, and that passes the information back to the parent component and triggers the associated `onCustom` callback function. However, it strikes me as it could be useful for users to be able to define their own custom functions on specific emitted events.

My suggested feature request is a function prop when creating the dialog component for custom dialogs, allowing users to define their own callback functions (which can include payload), and the emitted event they would be associated with.

**Comment by rstoenescu** [comment]
This sounds like a good idea. Thanks for sharing. Will do it.

**Comment by m0jimo** [comment]
I don't know if it fits here but AngularJS has been using `.then(() => {})` which seems to me as clean way to manage next action.
Dialog plugin with `onOk` and `onCancel` is confusing in cases when you need OK button on the left side and cancel right side. So `onOk` function fires Cancel action and vice versa. Is there a more elegant way to manage it?
```
// switch ok and cancel positions - not to delete content by accident
this.$q.dialog({
        title: 'Confirm',
        message: 'Delete file?',
        // cancel: true,
        cancel: "OK",
        ok: "cancel",
        persistent: true
      }).onOk(() => {
        console.log('>>>> OK - CANCEL')
      }).onCancel(() => {
         console.log('>>>> DELETE')
      }).onDismiss(() => {
        // console.log('I am triggered on both OK and Cancel')
      })
```

**Comment by mila76** [comment]
Some news on this feature??

**Comment by pdanpdan** [comment]
The name `onOk`  is unfortunate.
In fact `onCancel` is the function to be called on cancel (is the .catch) and `onOk` is the one to be called when an action should be performed (is the .then) - you can pass payload when you emit, and branch your code based on the payload.

**Comment by rstoenescu** [comment]
Props when invoking the custom Dialog plugin with custom component can be given. These props can also be functions. So there is no need to add anything to the current Dialog specs.

**Comment by mila76** [comment]
Ok maybe an example for this for the documentation??
I'm not so confident to do by myself but i can try to create a simple example if needed
