### ISSUE TITLE
QTree is missing the lazy-loading icon and does not fire the onlazyload event

### ISSUE THREAD

**Issue by HayasyLL** [quasarframework/quasar#8437]
**Describe the bug**
QTree is missing the lazy-loading icon and does not fire the onlazyload event

**Codepen/jsFiddle/Codesandbox (required)**
The error is even in the Doc sample: https://next.quasar.dev/vue-components/tree#Lazy-loading

**To Reproduce**
1. Go to 'https://next.quasar.dev/vue-components/tree#Lazy-loading
2. See error

**Expected behavior**
show lazy-loading icon and fire event

**Screenshots**
![image](https://user-images.githubusercontent.com/22284698/107170689-fdc22900-69fb-11eb-9899-0bbc835f6407.png)

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.3
@quasar/app Version:
Quasar mode:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Fix will be available in Quasar 2.0.0-beta.4.
