### ISSUE TITLE
Autofocus of <q-input/> is not working in v2.0.0-beta.3

### ISSUE THREAD

**Issue by xiazhichen1** [quasarframework/quasar#8446]
**Describe the bug**
Simply put, \<q-input autofocus /> will not automatically get focused after mounted. I also tried using template refs but still failed.

**Codepen/jsFiddle/Codesandbox (required)**
[autofocus](https://codepen.io/zxia31/pen/jOVroxe?editors=101)
[template refs](https://codepen.io/zxia31/pen/YzpWbjZ?editors=1010)

**To Reproduce**
For the `autofocus` Codepen, the input field does not get focused automatically.
For the `template refs` Codepen, the ref of the input field is retrieved but its `focus()` does not work.

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.3

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.5
