### ISSUE TITLE
Js/Ts intellisense for composition API  not working inside setup function .Quasar v2.0.0-beta.3

### ISSUE THREAD

**Issue by soulsam480** [quasarframework/quasar#8447]
**Describe the bug**
Javascript/Typescript intellisense for composition API methods/properties inside the setup function is not working inside a Quasar v2.0.0-beta.3 project. This does work with vanilla Vue 3 project.

**To Reproduce**
- Open a quasar 2.x project
- type OnMounted or any composition API method/property
- IDE should provide intellisense for the method/properties
- It does not work

**Expected behavior**
- IDE should provide intellisense for the methods/properties.

**Screenshots**

![composition API](https://user-images.githubusercontent.com/35460828/107385109-91474700-6b2d-11eb-80d2-3a68c30839ed.JPG)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.0.0-beta.3
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Ubuntu 20
Node: 14.x
Yarn: 2.x
Browsers: Edge, Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
As long as you don't have it imported I would not expect to autocomplete it, because it is not available.

**Comment by soulsam480** [comment]
> As long as you don't have it imported I would not expect to autocomplete it, because it is not available.

yes that's correct, but if you reproduce the case with a Vue cli Vue 3 project, on typing onMounted, it'll show the intellisense to import the method.

**Comment by IlCallo** [comment]
See https://github.com/quasarframework/quasar/issues/9235#issuecomment-941133038 for an explanation
