### ISSUE TITLE
[Feature Req] Infinite scroll for datatable component

### ISSUE THREAD

**Issue by ftKnox** [quasarframework/quasar#845]
Would be super nice to have infinite scroll added to the datatable component. I think this works much better on mobile than pagination. Maybe by adding a loadMore property.

```html
<q-data-table :loadMore="getMyData">
...
</q-data-table>
```

**Comment by ababo** [comment]
I need that feature too.

**Comment by neorganic** [comment]
Same here!

**Comment by etcogit** [comment]
I'm also intersted !!!!

**Comment by smolinari** [comment]
I'd venture to say, this needs to be its own component. Datatable has a lot of features, which don't really jive with an infinite scroll capability, or rather, the features become useless. I'm thinking about the sort and filter features, for instance. It shouldn't be too hard to build your own simple datatable with [QInfiniteScroll](https://quasar-framework.org/components/infinite-scroll.html).

Scott

**Comment by JoicePaz** [comment]
I was wishing it a few minutes ago haha!

**Comment by solovieff** [comment]
A small piece of mine: implementing load more button is pretty easy:
`<template slot="bottom">
        <q-btn outline color="positive" label="Load More..." @click="loadMore" style="width: 100%"/>
      </template>`

**Comment by pdanpdan** [comment]
This can now be implemented in QVirtualScroll in table mode (QMarkupTable).

**Comment by decotech1216** [comment]
> Would be super nice to have infinite scroll added to the datatable component. I think this works much better on mobile than pagination. Maybe by adding a loadMore property.
> 
> ```
> <q-data-table :loadMore="getMyData">
> ...
> </q-data-table>
> ```

I want this feature. This helps if implemented. :)
