### ISSUE TITLE
q-breadcrumbs-el causing page reload

### ISSUE THREAD

**Issue by ntoljic** [quasarframework/quasar#8450]
**Describe the bug**
When using breadcrumbs in combination with vue-router, clicking on a breadcrumb element navigates to the correct path but not before reloading the entire page. This happens only when using the `to` property. When using the default slot to add a router-link element it works.

**Codepen/jsFiddle/Codesandbox (required)**
Since the bug is related to vue-router this wouldn't work, right?

**To Reproduce**
Create a quasar app with `quasar create --branch next` (I chose the default values).
Replace the template code in Index.vue with the [Router links example](https://next.quasar.dev/vue-components/breadcrumbs#Example--Router-links) from the docs. 
Run the app and click on one of the breadcrumb elements. The app will reload and display the 404 page.

**Expected behavior**
The navigation should happen without a page reload.

**Platform (please complete the following information):**
Quasar Version: v3.0.0-beta.3
@quasar/app Version: v3.0.0-beta.3
Quasar mode:
  [ x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: macOS
Node: v12.14.1
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Firefox, Chrome
iOS:
Android:
Electron:

I have also tried this with a v1 app (`quasar create`) and could not reproduce the issue, so I assume it only affects the v2 beta.

**Comment by ntoljic** [comment]
A quick follow-up as I hadn't checked for new releases.
The issue persists even with the latest beta release.
Quasar Version: v2.0.0-beta.4
@quasar/app Version: v3.0.0-beta.5

**Comment by rstoenescu** [comment]
Will investigate.

**Comment by rstoenescu** [comment]
Root caused it. Fix coming.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.5

**Comment by ntoljic** [comment]
@rstoenescu wow, thank you for the quick response!
I will try it out as soon as v2.0.0-beta.5 is released

**Comment by ntoljic** [comment]
I just updated to v2.0.0-beta.5 and can confirm that the issue has been resolved. Thanks again!
