### ISSUE TITLE
QSelect - do not focus with hide-selected

### ISSUE THREAD

**Issue by krychu90** [quasarframework/quasar#8451]
**Is your feature request related to a problem? Please describe.**
When I use hide-selected in q-select there should be no focus effect for label:
https://jsfiddle.net/qjrvh5z0/

**Describe the solution you'd like**
Disable focus effect on select with hide-selected.

**Describe alternatives you've considered**
Give some option to disable focus effect.

**Comment by krychu90** [comment]
My current solution in css: 
.my-select.q-field--float .q-field__label {
    transform: none;
}

**Comment by pdanpdan** [comment]
There is a simpler solution. I suppose you want a fixed label shown all the time.
Use no label and use the selection slot with a fixed value as the label.

**Comment by pdanpdan** [comment]
Please reopen if the provided solution does not work for you.
But I would say a form component without a focus indicator is not very nice.
