### ISSUE TITLE
[docs] Quasar docs is awesome!

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [quasarframework/quasar#8452]
I just want to thank you, Quasar guys, for your awesome job!

I haven't seen any documentation (and framework) nearly as complete and useful as yours!
With complete and excellent usage recommendations and a search field that is better than Google.
I had this in mind for quite a while, but I had to write something when I saw https://quasar.dev/start/vs-code-configuration 
since I just melted when I saw that complete - and truly awesome! - list of plugins you recommended! <3

Does any developer want anything better than this? 

Thank you so much!

Best,
Barney

**Comment by pdanpdan** [comment]
Thank you, but please use the forum or the discord channel for such things.
