### ISSUE TITLE
Chips in QSelect

### ISSUE THREAD

**Issue by GitNomster** [quasarframework/quasar#8453]
**Describe the bug**
When using chips in QSelect component they rendered not quite round.

**Codepen/jsFiddle/Codesandbox**
https://codepen.io/gitnomster/pen/bGBBdVq

**To Reproduce**
Click on some options in selector

**Expected behavior**
Nice circle

**Screenshots**
Bugged chip
![image](https://user-images.githubusercontent.com/29253035/107608030-93f48a00-6c5c-11eb-984c-9324e15a2562.png)

Normal chip
![image](https://user-images.githubusercontent.com/29253035/107607879-44ae5980-6c5c-11eb-9dce-b9c1efe510cb.png)

**Platform:**
Quasar Version: 1.15.2
@quasar/app Version: 2.1.14
Quasar mode:
  [x] SPA
  [x] PWA
Tested on:
  [x] SPA
  [x] PWA
OS: Win 10
Node: 12.19.0
NPM: 6.14.8
Browsers: Chrome 88

**Comment by rstoenescu** [comment]
Looking at your codepen with Chrome 88. Can't reproduce. Some weird browser quirk?

**Comment by GitNomster** [comment]
Very strange. Tested on different computers result the same. But on firefox all is ok.

**Comment by pdanpdan** [comment]
I was able to reproduce it on Win10 (both Chrome and Edge - so chrome engines), but it looks like a rendering bug.
As a workaround you can try to set this in your CSS (or play a little with the value):

```sass
.q-chip--dense .q-chip__icon
  font-size: 1.24em
```

**Comment by GitNomster** [comment]
Ok, i'll give it a try, thank you. Hope this bug is not so wide spread.
