### ISSUE TITLE
Missing some Font Awesome icons

### ISSUE THREAD

**Issue by petr-panek** [quasarframework/quasar#8454]
**Describe the bug**
Some Font Awesome icons don't display. They're missing in @quasar/extras/fontawesome-v5/fontawesome-v5.css.
These icons are missing:
octagon
plus-octagon
minus-octagon
times-octagon

These icons are in Font Awesome Pro only. Maybe this is the source of the problem.
I'm using Font Awesome Pro. Installed with recommended steps on https://quasar.dev/options/installing-icon-libraries.

**To Reproduce**
1. Install the Font Awesome Pro with recommended steps on https://quasar.dev/options/installing-icon-libraries.
2. Insert in Vue page  <q-icon name="fa fa-octagon"   />
3. See the icon is not displayed

**Expected behavior**
Icon is displayed

**Platform (please complete the following information):**
Quasar Version: 1.15.3
@quasar/app Version: 1.9.6
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: MacOS 11.2.1
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

You are either using `@quasar/extras/fontawesome-v5/fontawesome-v5.css` (the free version of FA) or the Fontawesome Pro version. If the pro version is missing something, it should be reported to Fontawesome team.

**Comment by hawkeye64** [comment]
@petr-panek 
> These icons are in Font Awesome Pro only. Maybe this is the source of the problem.
@quasar/extras has nothing to do with Fontawesome Pro.
Make sure you created the boot file and imported your fonts as specified in the link you posted.

**Comment by petr-panek** [comment]
Solved. Free version of Font Awesome  was not disabled in quasar.conf.js.
Thank you for your quick help!
