### ISSUE TITLE
[v2] Vuei18n broken

### ISSUE THREAD

**Issue by Smrtnyk** [quasarframework/quasar#8456]
**Describe the bug**
Beta 4 broke translations for vuei18n
I guess it has to do with one of your latest commit @rstoenescu where you added some ff for vue i18n
I'll attach a screenshot, it now shows the mapping keys instead of translation values

![Capture](https://user-images.githubusercontent.com/31451544/107657431-7687e600-6c85-11eb-9660-12e17ee50ebe.JPG)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: quasar beta 4
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS:
Node: 14
NPM: 6
Yarn:
Browsers: all
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
It's been fixed in beta.5 after just a few hours.
