### ISSUE TITLE
Please add a global, "page/app is focused" event to which I can attach actions

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#8458]
I need a way to turn on and off a websocket connection when a user is focused or not focused.  We use Pusher and get charged for every connection that is either sending or receiving data, so I want to disconnect if no one is looking at the app, and reconnect when the window regains focus.  This would cover switching browser tabs, minimizing the browser or switching apps entirely.

Mozilla provides some hints here, but I don't see an easy way to integrate this into a quasar app:  https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API  A global "app is focused" event in quasar to which I could react would be very helpful.

**Comment by pdanpdan** [comment]
Please read the docs and use the forum or discord channels for help requests.
Hint, search for visibility.

**Comment by Daemach** [comment]
Did read the docs.  Searched for "focus" as that's an actual event.

**Comment by rstoenescu** [comment]
Quasar plugins > AppVisibility
