### ISSUE TITLE
@quasar/app uses undeclared dependency "pretty-error"

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#8459]
```
Error: @quasar/app tried to access pretty-error, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: pretty-error (via "pretty-error")
Required by: @quasar/app@npm:2.1.14 (via /Users/lucaban/ghq/github.com/CyCraft/magnetar/.yarn/cache/@quasar-app-npm-2.1.14-3e6d9e2195-872dda9a1f.zip/node_modules/@quasar/app/lib/helpers/)

Require stack:
- /Users/lucaban/ghq/github.com/CyCraft/magnetar/.yarn/cache/@quasar-app-npm-2.1.14-3e6d9e2195-872dda9a1f.zip/node_modules/@quasar/app/lib/helpers/cli-error-handling.js
- /Users/lucaban/ghq/github.com/CyCraft/magnetar/.yarn/cache/@quasar-app-npm-2.1.14-3e6d9e2195-872dda9a1f.zip/node_modules/@quasar/app/bin/quasar
- /usr/local/lib/node_modules/@quasar/cli/bin/quasar
    at internalTools_makeError (/Users/lucaban/ghq/github.com/CyCraft/magnetar/.pnp.js:32317:34)
    at resolveToUnqualified (/Users/lucaban/ghq/github.com/CyCraft/magnetar/.pnp.js:33282:23)
```

**Comment by mesqueeb** [comment]
@pdanpdan what info do you need

**Comment by mesqueeb** [comment]
here it's being used:
https://github.com/quasarframework/quasar/blob/d14af36cb3f0f965d94446d293a2b62a6d4b3640/app/lib/helpers/cli-error-handling.js#L1

and here is the package.json that doesn't have the dependency:
https://github.com/quasarframework/quasar/blob/dev/app/package.json

**Comment by pdanpdan** [comment]
The version of app :) but now can be inferred from the branch

**Comment by mesqueeb** [comment]
it's yarn with version codename berry, I believe it's beta of v2, but I'm not 100% sure.

**Comment by pdanpdan** [comment]
So you're using yarn2 with plug'n'play?
Then we would be very interested on how you made it to work, because:
https://github.com/quasarframework/quasar/issues/8245
https://github.com/quasarframework/quasar/issues/8286
https://github.com/quasarframework/quasar/issues/7581

**Comment by mesqueeb** [comment]
I didn't I had too many problems so immediately s itched back haha. 

But the fact that that package is not in the package.json I felt was worth reporting regardless.

**Comment by rstoenescu** [comment]
This is a non-issue. The html-webpack-plugin already includes it. By now you would've noticed that if this was an issue it would've surfaced ages ago on any CLI errors being printed out :) For completeness though, I'll add it.

**Comment by merceyz** [comment]
> The html-webpack-plugin already includes it

That's not how that works, if you're interested see https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies for details on dependency hoisting

**Comment by rstoenescu** [comment]
This will become an obsolete thing anyway. Working on the Webpack 5 upgrade and I'm at the stage of redesigning how all errors and warnings are caught and displayed. This includes explicitly adding pretty-error as a direct dep of q/app.
