### ISSUE TITLE
<keep-alive> doesn't works with QTabs

### ISSUE THREAD

**Issue by fnicollier** [quasarframework/quasar#846]
Quasar: Quasar 0.14.2
OS: Windows 7
Node: 8.1.3
NPM: 5.2.0
Browsers: Chrome 60.0.3112.101 (Official Build) (64-bit)
iOS: NA
Android: NA

### What did you get as the error?
No error, it just doesn't seems to work.

### What were you expecting?
Switching from one tab to the other would maintain the state of each tab. As of now created() is called on each component as I switch tab.

### What steps did you take, to get the error?
Created a QTabs with each pane containing a single component, each wrapped with Vue's <keep-alive>.

**Comment by rstoenescu** [comment]
`keep-alive` Boolean property added to QTabPane. Avoid using `<keep-alive>` Vue component and use this property instead.

Available in future v0.15.
Let me know if you need this quick as it may take a while before v0.15 will be out.

**Comment by fnicollier** [comment]
Thanks, that was fast!

**Comment by rstoenescu** [comment]
Available starting with v0.14.3
