### ISSUE TITLE
[v2] Change template for i18n to use capitalized locale variant to match quasar internal

### ISSUE THREAD

**Issue by florin-rotaru** [quasarframework/quasar#8460]
**Describe the bug**
Beta 5 translations for i18n still not working...

**To Reproduce**
1. create a new project: quasar create q2i18n --branch next
2. change boot/i18n.ts where locale: 'en-us' to locale: 'en-US'
3. add a new element to pages/Index.vue `<h1>{{` $t('success') }}</h1>`
4. run quasar dev
5. check console

![image](https://user-images.githubusercontent.com/54668297/107746783-13e32880-6d1f-11eb-85ad-bf705c203425.png)

![image](https://user-images.githubusercontent.com/54668297/107746990-67557680-6d1f-11eb-91b1-585cbfdeee42.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  [ X] SPA
  
Tested on:
  [X] SPA
  
OS: Win10
Node: 14
NPM: 6
Yarn:
Browsers: all
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
i18n locales and quasar locales are 2 different things.
If you change the locale for i18n to use `en-US` then you need to also change the config for i18n.

Please change the name of the issue to be: `[v2] Change template for i18n to use capitalized locale variant to match quasar internal`.

**Comment by florin-rotaru** [comment]
thanks for the prompt feedback!

**Comment by rstoenescu** [comment]
Fixed the "message compiler isn't included in this build".
Fix will be available in "@quasar/app" 3.0.0-beta.6

Also fixed the casing in the starter kit.
