### ISSUE TITLE
[bug] remote vueDevtools - store tab not working 

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#8461]
#7916 
https://github.com/quasarframework/quasar/issues/7916#issuecomment-711120442

Four month later, I found solution and bug in Quasar
https://github.com/quasarframework/quasar/blob/dev/app/templates/entry/app.js#L24-L36

When we import createStore we already create store (if store is not a function - my case) 
https://github.com/vuejs/vuex/blob/dev/src/store.js#L67-L70
In store constructor we are trying use devtool plugin
https://github.com/vuejs/vuex/blob/dev/src/plugins/devtool.js#L6-L9
And this devtool plugin call `return` without installation and do not emit `vuex:init` event on `__VUE_DEVTOOLS_GLOBAL_HOOK__`

After we import `@vue/devtools` and it's add hook, but devtool don't know about store without `vuex:init` event.
I tried call `vuex:init` with store in my project -> App.vue -> mounted hook and it's working.

Then I change reordering import's in node_modules/@quasar/app/template/entry/app.js and it's working without calling any devtool hook!!!!

**Platform:**
Quasar Version: 1.0.0
@quasar/app Version: 2.1.14
Quasar mode:
-> Cordova
-> Capacitor
Tested on:
-> Capacitor
OS: Mac OS -> Android & IOS
Node: 15.6
Yarn: 1.22.10
iOS: 12
Android: SDK 29+

**Comment by rstoenescu** [comment]
Fix will be included in "@quasar/app" 2.1.15.

**Comment by bazuka5801** [comment]
@rstoenescu  Thank you!

**Comment by tmilker** [comment]
@bazuka5801 Could you tell me how to call vuex:init from the mounted hook so I can work around this for quasar 2.0.5?

**Comment by bazuka5801** [comment]
@tmilker
```js
__VUE_DEVTOOLS_GLOBAL_HOOK__.emit('vuex:init', store)
```
If you using in script, yo can prepend it with **window**
```js
window.__VUE_DEVTOOLS_GLOBAL_HOOK__.emit('vuex:init', store)
```
You can try execute this code in devtools chrome or safari

**Comment by tmilker** [comment]
@bazuka5801 Thanks. Well, I looked a little closer at the dependencies and I've got @quasar/app 3.0.5 and verified your PR fix is already included.  I just cannot get the Vue Dev Tools to find my Vuex store.
