### ISSUE TITLE
q-popup-edit buttons not working

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#8463]
when click set button no even works `useEditLabel`

```

<q-popup-edit v-model="e.accLabel" buttons @save="useEditLabel(e)">
                  <q-input v-model="e.accLabel" dense autofocus counter>
                    <template v-slot:append>
                      <q-icon name="mdi-lead-pencil" color="primary" />
                    </template>
                  </q-input>
                </q-popup-edit>


```

**Comment by pdanpdan** [comment]
Please make a codepen to show the problem.

**Comment by diadal** [comment]
https://codepen.io/diadal/pen/bGBggmm

**Comment by pdanpdan** [comment]
What are you trying to do there? I cannot understand what you want to do with the popup edit in a div that you cannot click on.
Please use the forum or the discord channel for help requests.

**Comment by diadal** [comment]
check the updated  https://codepen.io/diadal/pen/bGBggmm 
check this function not working 

```
function useEditLabel(e) {
      console.log(e);
      test.value = e;
    }
```

**Comment by diadal** [comment]
i said it before that @save event not working work not Emitted this `quasar........ v2.0.0-beta.4 @quasar/app... v3.0.0-beta.5 `

**Comment by pdanpdan** [comment]
You should read how to use the scoped slot in QPopupEdit.

**Comment by diadal** [comment]
please watch the 30s video many not working in QPopupEdit even from your website @ https://next.quasar.dev/vue-components/popup-edit#Usage i understand if you guys still working i just want to confirm if this is general issue as i thought or my own mistake  
https://user-images.githubusercontent.com/19895516/107845647-55d2a400-6ddd-11eb-96c3-9e909a75601b.mov

**Comment by diadal** [comment]
`@cancel` and `@save` event not working other event working call sample `@cancel  ="useEditLabel">  ` @cancel  ="useEditLabel()">`  `@cancel  ="useEditLabel(null, null)">` none works but rest event works

**Comment by pdanpdan** [comment]
As I already said above: read the docs, check the examples, try to understand :)
You are already changing the external value.

**Comment by diadal** [comment]
none of the examples https://next.quasar.dev/vue-components/popup-edit#Usage point out how to use event `@cancel` or `@save` maybe am wrong you can share the link

**Comment by zkyCarry** [comment]
bug
@save="savePopEdit"   
first input 0     not implement  savePopEdit
