### ISSUE TITLE
Quasar 2.x.beta QInput not emitting @input event continuously

### ISSUE THREAD

**Issue by soulsam480** [quasarframework/quasar#8465]
**Describe the bug**

QInput component is not emitting the 'input' event sometimes and when it emits, it does after the component is out of focus. Also, the event is not getting fired continuously.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
- Instead of v-model add a @input event handler on a QInput component.
- Log the event in console.
- The event will not fire even after typing inside the QInput field.

**Expected behavior**
- QInput should emit the @input event continuously upon typing.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.4
@quasar/app Version: v3.0.0-beta.5
Quasar mode:
  - [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  - [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Ubuntu 20
Node: 14.15.4
NPM: NA
Yarn: 2.x
Browsers: Edge, Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Please create a codepen showing the problem.

**Comment by soulsam480** [comment]
In the v2.x docs, it's mentioned that the event is @update:modelValue -> function(value) not @input. Please update the editor intellisense files. Thanks 
[Link to docs](https://next.quasar.dev/vue-components/input#QInput-API)

**Comment by pdanpdan** [comment]
The editor is not wrong, you just added a listener in the native event.

**Comment by soulsam480** [comment]
> The editor is not wrong, you just added a listener in the native event.

Sorry, but the native event isn't getting fired. Any way to make the new **update:modelValue** event from the QInput same as the native input event? I think that'll remove the confusion and also make dev UX better.

**Comment by pdanpdan** [comment]
No. It's something completely different. One is a vue event, the other native event. And the event name is that one in vue2.

**Comment by therealcoder1337** [comment]
had the same issue and just switched to `@update:modelValue`. unfortunately, i cannot reproduce this issue in a codepen. as there seems to be no disadvantage of using the vue3 style event, i'll stick to that.
