### ISSUE TITLE
Why was my issue closed without a word?

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#8469]
**Why was my issue closed without a word?**
**Why were other issues not closed?**
**What can I do?**

### The issue was closed without a word because one or more of the reasons below:
- it was a help request
- it was related to JS basics
- it was related to Vue basics
- it has nothing to do with Quasar
- it was caused by not reading Quasar docs
- it had no codepen when it was something that had to be tested in specific conditions
- it had no details required in the issue template (quasar version, quasar mode, platform, browser, device)

### Other issues were not closed when they matched above list because:
- they were describing an obvious bug
- they were about a problem that was interesting and we considered it's worth the effort to get more details from the opener

### If you consider the issue should stay open, please:
- fill the details
- add a codepen (if it makes sense - but even if it's about mobile sometimes it helps to have it)

### Else:
- use the forum or our discord channel to get help

**Comment by rstoenescu** [comment]
This ticket should be closed. And still referenced when needed.
