### ISSUE TITLE
Form with validation API should be redesign

### ISSUE THREAD

**Issue by fyeeme** [quasarframework/quasar#8471]
**Is your feature request related to a problem? Please describe.**
quasar's form with validate is too complex, and less reusable.

**Describe the solution you'd like**
rule should remove to js data as object, so it can be simplify template and improve reusable. new api design can refer to elementui, it power by [ async-validator](https://github.com/yiminghe/async-validator), so provide out of the box for basic type validate and custom validate and aync validate
[elementui Validation](https://element-plus.org/#/en-US/component/form)
Custom validate callback function must be called. See more advanced usage at async-validator.

A glance to it's api.
![Xnip2021-02-13_23-06-05](https://user-images.githubusercontent.com/6078758/107853318-20b36980-6e50-11eb-9fc3-3486ef1fc88a.jpg)

**Comment by pdanpdan** [comment]
What you are referring to is a sort of copy of vuelidate, having all the disadvantages and none of the benefits.
Using a data validator is the recommended solution most of the time.
The validation in Quasar is for when you don't want to use vuelidate.
Also, the solution in quasar is very flexible and reusable (just put your functions in a file and export them, then import them and use as required).

**Comment by fyeeme** [comment]
@pdanpdan , by reading quasar's doc many time，i still can't find a simple way to use form validate api

**Comment by pdanpdan** [comment]
Please show a codepen with something you find difficult

**Comment by fyeeme** [comment]
@pdanpdan 
I‘v see the v2 doc about form and input  and try with the example, found that seems quasar provide validate level on input, not   the form.
code pen links:
[quasar form validate](https://codepen.io/fyeeme/pen/oNYeWwG)
[element form validate](https://codepen.io/fyeeme/pen/OJbjmWB)

diffs are here:
## 1. validate level

 although i can use array to apply form with  validate() and hasError, but still validate level on input ,and with Composition API it's can not use iterator when use reactive() cause it's a proxy object.

doc just show form validate with input, not include  radio, checkbox , and I'll try them  later to test is `rules` can work. 

![image](https://user-images.githubusercontent.com/6078758/108580982-fdfde500-7368-11eb-9815-8768d16790ff.png)
![image](https://user-images.githubusercontent.com/6078758/108580994-0e15c480-7369-11eb-889a-352578905c04.png)

## 2. validate lib
quasar default validate is good, using rules on input providing error msg. also providing vuelidate,  but with different apis

`You can also use external validation and only pass error and error-message (enable bottom-slots to display this error message)`

i think External  validte lib should just care about  rules, and providing out of box(vuelidate truly did so but with it's view)


## 3. missing things

as i'm not familiar with quasar and not reading source code yet. so if i'm missing some things that quasar can do it with a easy way, please let me know. many thanks.

**Comment by pdanpdan** [comment]
Validation is in fact at field level (QField) - and if you use QForm you can validate all the field within.
I'll reopen this, but for Quasar v2.

**Comment by fyeeme** [comment]
After research the doc and source code,  as you say  Quasar implements internal validation on QField, but also integration on QForm with submit() and reset(), it's truly flexible.

but I found the validate code  related files:
https://github.com/quasarframework/quasar/blob/dev/ui/src/utils/patterns.js
https://github.com/quasarframework/quasar/blob/dev/ui/src/mixins/validate.js

validate support to way:
 function with message 
 patterns regex function (`can not provide msg`)

but I found it's not easy to do something like this:

1. required : just require val not null (now can do with: `(val) => !!val || 'custom required msg'` or `(val) => (val && val.length > 0) || 'custom required msg`), 

2. max: 

3. min: 

if validate support like this:
 name: [
        { required: true, message: '请输入活动名称' },
        { min: 3, max: 5, message: '长度在 3 到 5 个字符' },
        { pattern: /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/ } //or use self lib or other like this utils.regex.hexColor
],

then quasar's validate should be more flexible and powerful.

@pdanpdan

**Comment by rstoenescu** [comment]
What can be more flexible than the current design? You have Functions as rules. You return a String on error, otherwise a Boolean. It's the mother of flexibility.

* `{ min: 3, max: 5, message: 'fgdfgdd' },` is: `val => val >= 3 && val <= 5 || 'fgdfgdd'`
* `{ pattern: /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/ , message: 'fgdfg'}` is: `val => /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/ .test(val) || 'fgdfg'`

I guess you're hinting at us providing these out of the box. But it makes no sense since the current way is extremely easy. Plus we'd open up the Pandora's box where people would request their custom stuff forever and ever, bloating the framework more and more.

However, you can create a .js file where you can write your own rules, then import it in the components where you need it. Supply it to the vue scope then you're good to go.
