### ISSUE TITLE
The App Ext functions for Install and Uninstall should be the same

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#8473]
The Install API looks like this:
![image](https://user-images.githubusercontent.com/10262924/107858488-9805e080-6df1-11eb-9d17-ee21c940fa34.png)
But the Uninstall looks like this:
![image](https://user-images.githubusercontent.com/10262924/107858497-aa801a00-6df1-11eb-8195-e4af39db4ddd.png)

With a big difference in Vue 3/Quasar 2 handling, there is now a need to check the quasar version on install (this is available) and on uninstall (this is not available re: `api.getPackageVersion` and others). It makes sense if you can do something in the Install, then you will need the same functions available in the Uninstall.

Sorry to dump more work on you @rstoenescu . But, there are some app-exts that can't get updated to Quasar 2 until this happens (specifically the Apollo extension: https://github.com/quasarframework/app-extension-apollo/pull/89). I am not sure I am qualified enough to make the changes and do the PR. :(

**Comment by rstoenescu** [comment]
So you'd need getPackageVersion. Anything else? Write them down explicitly.

**Comment by rstoenescu** [comment]
Added getPackageVersion() and hasPackage().
One comment though: don't try to supply both Vue 2 and Vue 3 versions in the same package. Should be separate packages or different major versions. We'll talk more in the following days.
