### ISSUE TITLE
QSelect: show dropdown list in readonly mode

### ISSUE THREAD

**Issue by 549393092** [quasarframework/quasar#8474]
Currently, QSelect can't show the dropdown list in readonly mode.
See this example https://quasar.dev/vue-components/select#Disable-and-readonly

Could you please add this feature, you could refer below link as an example.
https://codepen.io/ontwikkelfabriek/pen/zYoBQLY

For more detail info, please see this link.
https://forum.quasar-framework.org/topic/7743/qselect-is-that-possible-to-show-drop-list-in-readonly-mode

Regards

**Comment by pdanpdan** [comment]
Hello.
The solution in the codepen is almost good - here are some fixed alternatives: https://codepen.io/pdanpdan/pen/RwoKqBZ?editors=1010
But what would be the point of having this (from the pov of the UI)?

**Comment by 549393092** [comment]
@pdanpdan Thanks!
What I am thinking of is: even in the read only mode, user still has the chance to see the possible dropdown list values.
For example, when opening an order, it is usually in display (readonly) mode, if user are allowed to see the possible dropdown list values and he realized that the current value is incorrect, then he can switch to change mode and pick the correct one.
Regards

**Comment by pdanpdan** [comment]
As the workaround is simple, and it's not something that would be frequent, I'll close this.
