### ISSUE TITLE
Error Install Cli Node 14

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#8476]
**Describe the bug**
When try to install `@quasar/cli` it fails because `ghost-cli@1.14.1` don't support node 14.

**To Reproduce**
1. Use node 14
2. Execute `yarn global add @quasar/cli` or `npm i -g @quasar/cli`

**Expected behavior**
Install the cli

**Screenshots**
![image](https://user-images.githubusercontent.com/19597708/107879619-30779000-6eda-11eb-90f4-b56cd8a5d084.png)

**Platform (please complete the following information):**
OS: WSL 1
Node: 14.15.5
Yarn: 1.22.5

**Comment by pdanpdan** [comment]
I suppose it's this: https://github.com/TryGhost/Ghost-CLI/issues/796

Not exactly the reason for your error, but https://quasar.dev/quasar-cli/installation#Introduction (I know it could have been worded better)

**Comment by rstoenescu** [comment]
Quasar CLI is using Webpack 4, which does not supports Node 14. We're in the process of upgrading to Webpack 5, but will do this for Quasar v2 only, since this is a hard breaking change.
