### ISSUE TITLE
moduleNameMapper of Jest config links to files that do not exist

### ISSUE THREAD

**Issue by speasley** [quasarframework/quasar#8478]
When creating a new project with the Jest test harness (alone or with other harnesses) I run into errors when trying to run the tests.

**To Reproduce**
1. Create a new project: `quasar create my_project --branch next`
    * `Sass with SCSS syntax`
    * `ESLint (Prettier)`
    * `Vuex`
    * `Axios`
    * `Vue-i18n`
    * `use Yarn`
2. `cd my_project`
3. Install test harnesses: `quasar ext add @quasar/testing`
    * `Jest`
    * `Cypress`
    * `Quality`
    * `Security`
    * `Overwrite babel.config.js and use additional .babelrc`
    * `Extra "scripts" in your package.json`
    * `SFC webpack <test> loader`
    * `Cypress: extra "scripts" in your package.json`
    * `Lighthouse: extra "scripts" in your package.json`
    * `install the OWASP ZAP Heads Up Display`
    * `configure with Chrome`
4. Run `quasar test --unit jest`
5. See error:
```$ jest --ci
 FAIL  test/jest/__tests__/App.spec.js
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module vue mapped as:
    vue/dist/vue.common.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^vue$/": "vue/dist/vue.common.js"
      },
      "resolver": undefined
    }

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:551:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:11)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.004 s
Ran all test suites.
```
The files that appear in `node_modules/vue/dist/` are:
```
vue.cjs.js
vue.cjs.prod.js
vue.d.ts
vue.esm-browser.js
vue.esm-browser.prod.js
vue.esm-bundler.js
vue.global.js
vue.global.prod.js
vue.runtime.esm-browser.js
vue.runtime.esm-browser.prod.js
vue.runtime.esm-bundler.js
vue.runtime.global.js
vue.runtime.global.prod.js
```
If I map to another file instead, I get the following error:
```
Cannot find module 'vue-template-compiler' from 'node_modules/@vue/test-utils/dist/vue-test-utils.js'

    Require stack:
      node_modules/@vue/test-utils/dist/vue-test-utils.js
      test/jest/__tests__/App.spec.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:6:27)
```
In that directory, `vue-template-compiler` is not present either.

**Expected behavior**
The test suite should run the tests without configuration errors.

**Platform**
Quasar Version: `3.0.0-beta.6`
@quasar/app Version: `2.0.8`
OS: `macOS 10.15.7`
Node: `12.20.0`
NPM: `7.5.0`
Yarn: `1.22.10`

**Additional context**
I have reproduced this several times from fresh projects.

**Comment by IlCallo** [comment]
I see the problem, testing AE isn't still ready for Qv2

**Comment by MounirOnGithub** [comment]
I've encountered this error anyone has the solution ?

**Comment by IlCallo** [comment]
@MounirOnGithub the problem is still the same:

> testing AE isn't still ready for Qv2

I'm working on it :)

**Comment by BenitoJD** [comment]
i too have the same issue

**Comment by cbleek** [comment]
same issue here. 

maybe the issue should be reopened

**Comment by cbleek** [comment]
was done in https://github.com/quasarframework/quasar-testing/tree/next/packages/unit-jest

Thank you
