### ISSUE TITLE
In ssr mode prefetch is not working.

### ISSUE THREAD

**Issue by shahriar350** [quasarframework/quasar#8479]
![image](https://user-images.githubusercontent.com/44544213/107946387-2bd6d880-6fbb-11eb-9e74-defb4ae85dd2.png)
![image](https://user-images.githubusercontent.com/44544213/107946488-4ad56a80-6fbb-11eb-8f57-13c860cfa3e8.png)
Quasar v1.15.3
in store i fetch my user and I called that store from App.vue.
In SPA I can retrieve my user data =>
![image](https://user-images.githubusercontent.com/44544213/107946804-ba4b5a00-6fbb-11eb-930d-cf89c0f09f26.png)
But in SSR, I cannot retrieve my user data => 
![image](https://user-images.githubusercontent.com/44544213/107946927-e1a22700-6fbb-11eb-91fa-c28712ec0274.png)
Also, in SSR, it shows a error =>
![image](https://user-images.githubusercontent.com/44544213/107947219-51181680-6fbc-11eb-8062-7196ea30c5e5.png)
Please help me out. Thank you..

**Comment by pdanpdan** [comment]
hello. Please see #8469.

**Comment by shahriar350** [comment]
> hello. Please see #8469.

Thank you. But if you point my error that will be more efficient for me learning.

**Comment by rstoenescu** [comment]
`this._vm` seems off. There's no "this" in a preFetch() call, like explained in the docs.
Directly import axios from your boot file.
