### ISSUE TITLE
Form required disabled input gets triggered when sumbit

### ISSUE THREAD

**Issue by FlorinBadea** [quasarframework/quasar#8481]
Open https://quasar.dev/vue-components/form#Usage in Codepen and add disable attr to one of the two inputs and press "submit" btn.
Result: **disabled input** gets validated (see pic attached).

![image](https://user-images.githubusercontent.com/3803202/107954370-0a6af200-6fa5-11eb-8bcf-c7dcd44a2dc1.png)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.4.

**Comment by yangjiafu** [comment]
v1.15.10 disabled components can't use resetValidation void, because disabled components no class "q-validation-component"
