### ISSUE TITLE
QField doesn't expand to contain a QColor control

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8482]
**Describe the bug**
QField wrapping a QColor component (to provide consistent look / hint next to QInput components) does not expand vertically to 'contain' the QColor component.

Note this could just need additional elements or CSS to fix, but it's not clear from the documentation of QField how to do this.

And, this may be straying into 'feature request' territory now, but ideally I'd like to disable the focus effect of the QField. Using `borderless` is close, but messes up the padding / alignment of the hint when used vertically with other QInput elements set to `filled`.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/WNopoEG?editors=1010

**To Reproduce**
1. Go to codepen
2. See the hint and second QInput element 'through' the QColor component
3. Switch to RGB mode, and it is _almost_ correct

**Expected behavior**
The QField would expand vertically to accomodate the QColor component regardless of its current mode.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.5.
