### ISSUE TITLE
[v2] q-select with ref options: v-on with no argument expects an object value

### ISSUE THREAD

**Issue by florin-rotaru** [quasarframework/quasar#8483]
**Describe the bug**
Using q-select with ref(options) will create lot of of Vue warnings

**To Reproduce**
1. create a new project: quasar create qtest --branch next
2. goto https://next.quasar.dev/vue-components/select#Customizing-menu-options
3. copy template content
4. open src/pages/index.vue and paste template content somewhere inside q-page
5. in src/pages/index.vue, defineComponent, setup create few options using ref
6. run quasar dev then on the page click the select 'input' and check console

index.vue file attached (as .txt :) )

[Index.txt](https://github.com/quasarframework/quasar/files/5986740/Index.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/54668297/108030321-b8bf7780-7037-11eb-9fc4-c31d23e64499.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  [X] SPA
Tested on:
  [X] SPA
OS: win10
Node: 14.15.4
NPM: 6.14
Yarn:
Browsers: all
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
Hello. Please make a codepen.

**Comment by rstoenescu** [comment]
@florin-rotaru Remove `v-on="scope.itemEvents"`. Due to the new architecture in Vue 3, we are supplying everything in scope.itemsProps.

**Comment by rstoenescu** [comment]
Also, reference from the upgrade guide: https://next.quasar.dev/start/upgrade-guide#QSelect
