### ISSUE TITLE
QSelect Multiple @input event not working

### ISSUE THREAD

**Issue by saudsayed** [quasarframework/quasar#8488]
Hello, All
Qselect multiple @input is not working for me in the development branch, however, I can see it working in codepen.

` <q-select
            multiple
            filled
            v-model="user.roles"
            :options="roles"
            label="Roles"
            map-options
            emit-value
            @input="notify()"/>`

`new Vue({
  el: '#q-app',
  data: function () {
    return {
      version: Quasar.version,
      user: {
        roles: []
      },
      roles: [
        {label: 'user', value: 'user'},
        {label: 'agent', value: 'agent'},
      ]
    }
  },
  methods: {
  	notify: function () {
      this.$q.notify('Running on Quasar v' + this.$q.version)
    }
	}
})`

**Comment by pdanpdan** [comment]
#8469
