### ISSUE TITLE
Autocomplete -> Uncaught TypeError: fns.apply is not a function 

### ISSUE THREAD

**Issue by devistar** [quasarframework/quasar#849]
I got "Uncaught TypeError: fns.apply is not a function" error when using Autocomplete component.
I defined a sample static-data autocomplete. The error occurs in browser console when I select a result. The result block also doesn't close after selection.

### Code

![2017-09-01 10_24_38-glayout vue gestloy visual studio code](https://user-images.githubusercontent.com/11228594/29961392-ce1fb3c8-8eff-11e7-98ee-4b09b00ddd48.png)

![2017-09-01 10_23_11-glayout vue gestloy visual studio code](https://user-images.githubusercontent.com/11228594/29961329-9cd0124a-8eff-11e7-9c42-6ab34eef872b.png)

![2017-09-01 10_23_44-developer tools - http___localhost_8080_dossier_1_detail](https://user-images.githubusercontent.com/11228594/29961351-ac5da646-8eff-11e7-9634-9c2b767fde19.png)

### Software version

Quasar: 0.14.2
OS: Windows 8.1
Node: v7.5.0
NPM: 4.1.2
Browsers: Google Chrome

**Comment by rstoenescu** [comment]
`selected` needs to be a Function which takes one param as the item that got selected.
