### ISSUE TITLE
Quasar version when using quasar CLI

### ISSUE THREAD

**Issue by bddexter** [quasarframework/quasar#8491]
Hi,

More a question: when I use the quasar CLI and startcreation a project by running `quasar create <project name>` my `package.json` tells me that quasar version 1.0.0 is being used and not the latest.

Is this normal? Or am I doing something wrong?

**Comment by pdanpdan** [comment]
Please read about npm package versioning, pinning and version ranges. ^1.0.0 means any 1 version and in install the latest is used.

**Comment by hawkeye64** [comment]
@bddexter If you use yarn, you can `yarn why quasar` and it'll return the version being used.
