### ISSUE TITLE
Documentation - Tooltip Sample Code under 'Reusable' Radio button not working

### ISSUE THREAD

**Issue by bakbluelabel** [quasarframework/quasar#8492]
_A gentle reminder_: The sample code of [Tooltips](https://next.quasar.dev/vue-components/tooltip) under the **Reusable** section not working properly - the radio button no response. I guess missing the below:
``` js
import { ref } from "vue";
...
const targetEl = ref("#target-img-1");
return { targetEl };
```
Hope this help!

**Comment by rstoenescu** [comment]
Thanks for the report!
Why not PR it? Would help us unload the small stuff from our already full plates.

**Comment by bakbluelabel** [comment]
> Thanks for the report!
> Why not PR it? Would help us unload the small stuff from our already full plates.

I'd love to, but don't know how to help... 😳

**Comment by hawkeye64** [comment]
@bakbluelabel You can read up on it here: https://quasar.dev/contribution-guide/contribution-guide#Contributing-to-the-Quasar-Documentation

**Comment by bakbluelabel** [comment]
@hawkeye64 alright, thanks.
