### ISSUE TITLE
Any plan to introduce cache on image urls for android apps

### ISSUE THREAD

**Issue by anandtripathi5** [quasarframework/quasar#8495]
Like in the native app the libraries are having the functionality to cache the images on the disk.

**Comment by pdanpdan** [comment]
Are you talking about cordova/capacitor, or about web aps?

**Comment by anandtripathi5** [comment]
For Cordova

**Comment by anandtripathi5** [comment]
Something like if I am rendering an image using 

<q-img :src="<custom-url>"></q-img>

if the page is reloaded again then it avoids re-fetching the image from the source instead of that just fetch the saved image from the cache. Something like that

**Comment by pdanpdan** [comment]
You can use something like https://github.com/triniwiz/capacitor-image-cache.
Anyway, it should be done at cordova/capacitor side to be efficient.

**Comment by anandtripathi5** [comment]
Maybe quasar can put some flag in q-img component!!
