### ISSUE TITLE
QBtnToggle + TypeScript = "TypeError: Assignment to constant variable"

### ISSUE THREAD

**Issue by dobrebydlo** [quasarframework/quasar#8497]
**Describe the bug**
Using QBtnToggle with TypeScript leads to "TypeError: Assignment to constant variable" when clicked. Model value is not changed.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dobrebydlo/pen/xxRrRZd

**To Reproduce**
1. Use Quasar and TypeScript
2. Use QBtnToggle component
3. Click on any button in QBtnToggle component
4. See error in console

**Expected behavior**
No errors, model value changes according to clicked item's value

**Screenshots**
The codepen seems to be self-explanatory

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.5
@quasar/app Version:
Quasar mode:
  [ x ] SPA
  [ ] SSR
  [ x ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ x ] SPA
  [ ] SSR
  [ x ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: macOs Catalina
Node: v14.15.5
NPM: 6.14.11
Yarn:
Browsers: Chrome 88.0.4324.150
iOS:
Android:
Electron:

**Additional context**
Vue 3.0.5

**Comment by rstoenescu** [comment]
Seems like a minifier issue.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.6. It was the minifier which needed an update to its configuration when building Quasar itself.
