### ISSUE TITLE
QV2: [Vue Warn] Component emitted event "keydown" but it is neither declared in the emits option nor as an "keydown" prop

### ISSUE THREAD

**Issue by daifuku99** [quasarframework/quasar#8498]
**Describe the bug**
Mixins emit event is not declared in Component, so vue warn occured.
It's warning, not critical error.

**Codepen/jsFiddle/Codesandbox (required)**
The warning does not show up in Codepen

**To Reproduce**
1. Use Quasar
2. Use QDate with QInput default sets
https://next.quasar.dev/vue-components/date#With-QInput
3. come up keydown events to QInput
4. See error in console

**Expected behavior**
There should be no event related console warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/68150735/108355531-4cf32f80-722e-11eb-8320-3c3ecf594fd6.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  [ × ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ × ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Windows10
Node: v12.16.1
NPM: 6.13.4
Yarn:
Browsers: 88.0.4324.150
iOS:
Android:
Electron:

**Additional context**
I think this issue that mask.js makes warn.
Because, "__onMaskedKeydown " emits "keydown" events
https://github.com/quasarframework/quasar/blob/ca1ef4f97487d957c930d81418b12b10166ed86b/ui/src/mixins/mask.js#L410

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce. Please supply a [codepen](https://codepen.io/rstoenescu/pen/xxEvBLR?editors=101) or [jsfiddle](https://jsfiddle.net/rstoenescu/a2cuzods/) and tell exactly what you click and type.

**Comment by rstoenescu** [comment]
Also, your link points to Quasar v1, not v2. The branch for v2 is `vue3-work`.

**Comment by rstoenescu** [comment]
Wait. I think I know what you are referring to. Fixing. No need for codepen/jsfiddle.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.6.
Thanks for reporting.

**Comment by daifuku99** [comment]
Thank you for your support
