### ISSUE TITLE
Other Utils may provide Event Bus in v2

### ISSUE THREAD

**Issue by xiazhichen1** [quasarframework/quasar#8501]
In Quasar v1, event bus is provided as a basic util via `this.$root`. In Vue 3, event bus is [no longer provided](https://v3.vuejs.org/guide/migration/events-api.html#_3-x-update), instead third-party equivalents are recommended. Such kind of implementation may be included in "Other Utils" as it is one of the most commonly used functionality.

**Comment by pdanpdan** [comment]
If you change the description to `In Vue2 event bus ...` and open it on Vue it would be more on target.
But in Vue3 you dont need an event bus, you can use a ref and watch it and it's the same thing.
