### ISSUE TITLE
Suspense conflict using Quasar?

### ISSUE THREAD

**Issue by CesarGomezTissini** [quasarframework/quasar#8502]
**Describe the bug**
I'm trying to use Suspense with Quasar.dev. But some "Vue internal bug" warning show me in browser console.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/cesargomeztissini/pen/qBqjyaQ?editors=1010

**To Reproduce**
Check codepen above

**Expected behavior**
The template should show loading and waiting 3 second, my name and my age in stringified object form

**Platform (please complete the following information):**
Quasar Version: 
@quasar/app Version: 2.0 Beta 5
Quasar mode:
  [x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Windows
Node: =>14
NPM: 7.5
Yarn: NONE
Browsers:
iOS: NONE
Android: NONE
Electron: NONE

**Additional context**
None

**Comment by pdanpdan** [comment]
Hello. Sorry, but your codepen is a mess. And it has nothing to do with Quasar.
Try reading the Vue 3 documentation.
