### ISSUE TITLE
Full support of Jsx/Tsx in Quasar v2 with Vue-Cli

### ISSUE THREAD

**Issue by mockingjet** [quasarframework/quasar#8503]
It seems Quasar v2 not fully support Jsx/Tsx with Vue-cli in some ways.

For example,

    import { QLayout } from "quasar";

    const App = () => (
      <QLayout></QLayout>
    );
    export default App

It throws error: JSX element type 'QLayout' does not have any construct or call signatures

However, in an auto import strategy,
   
    // auto import
    const App = () => (
       <q-layout></q-layout>
    );
    export default App

It can work.

So I modify importStrategy (vue.config.js) from 'kebab' to 'pascal', and it's still not working.

Hope Quasar team release Jsx/Tsx support and related docs soon, thanks!

**Comment by Smrtnyk** [comment]
You should point out here that you are using vue cli to create a project so you have partial support
Projects created with quasar cli have no support for tsx at all

**Comment by panhezeng** [comment]
Update Quasar v2, Vue 3, tsx error

quasar create <folder_name> --branch next

https://github.com/vuejs/jsx-next

**Comment by mockingjet** [comment]
@panhezeng support vue-cli as well?

**Comment by MrJmpl3** [comment]
> Update Quasar v2, Vue 3, tsx error
> 
> quasar create <folder_name> --branch next
> 
> https://github.com/vuejs/jsx-next

Quasar support tsx? Because I have error too

**Comment by IlCallo** [comment]
Quasar CLI doesn't support jsx/tsx yet

**Comment by MrJmpl3** [comment]
> Quasar CLI doesn't support jsx/tsx yet

Oh, Thanks for the fast reply

**Comment by IlCallo** [comment]
No problem. Unluckily it isn't a priority for us right now, but we'd gladly accept a PR adding it :)

**Comment by Smrtnyk** [comment]
tsx works with quasar, but it requires some setup and jsx plugin
just in case someone thinks it is not possible to run it together

**Comment by IlCallo** [comment]
You're right, let me specify: JSX and TSX won't work **out of the box**, but since you have full control on the webpack chain via `quasar.conf.js`, you can add the support yourself.

@Smrtnyk if you have some experience in this area, could you write an example on how to add JSX/TSX support via `quasar.conf.js`?

**Comment by Smrtnyk** [comment]
@IlCallo sure, I will write up something tomorrow about the setting it up

**Comment by IlCallo** [comment]
Closing in favor of https://github.com/quasarframework/quasar/issues/8690 since we went ahead there
