### ISSUE TITLE
feat: Quasar v1/v2: Keyboard SVG component 

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#8504]
**Is your feature request related to a problem? Please describe.**

I'd like to provide 3D buttons as keypress visual queues like this one ...

![key-board-button](https://user-images.githubusercontent.com/301525/108471205-c7778a00-72d6-11eb-9b2d-73ea7c810c4e.png)

**Describe the solution you'd like**
A new `QKeyboardKey` component could take strings like "CTRL-K ALT-Z" as a `keys` property and generate the SVG buttons.  

- Would be great if CTRL key auto adapted for platforms: macOS / win / unix. 
- A `colour` property would be nice to highlight keys (very useful for documents / training).  Needs to also work for named keys like "return", "tab" or "space".
- Needs a button size property `xs`, `sm`, `md` `lg` etc

To simplify code, you might even be able to support emitting a standard `@onKey` event when the `keys` sequence is pressed.

**Describe alternatives you've considered**
- Generate images for the keypress buttons.

**Additional context**
I noticed these used by Angolia Search box on the new v3 Vue site thought they'd be cool to have in Quasar.

- https://v3.vuejs.org/guide/introduction.html  - Tap the search box or key CTRL-K and you'll see some more examples in the Angolia search popup.

**Comment by pdanpdan** [comment]
Hello. This is just some CSS you need for your (I hope) `kbd` tags.

**Comment by tohagan** [comment]
- https://github.com/kremalicious/kbdfun/
