### ISSUE TITLE
interactive image with SVG polygon usage configuration

### ISSUE THREAD

**Issue by wng97** [quasarframework/quasar#8505]
Recently I am having problem with the dynamic image render, I tried several plugins but its still didn't work as the :src is unable to bind data when it is an inline SVG

And then I found a new plugins yesterday and I could like to try it out but this plugins didn't provide the usage configuration for quasar as it only provide for Vue2 and 3. I have look through the vue-i18n example but still have no idea how to fit in the usage configuration code. Its great if anyone in here is able to provide me some help.

below is the link of the plugins:
https://github.com/oliverfindl/vue-svg-inline-plugin

Thanks.

**Comment by pdanpdan** [comment]
#8469
