### ISSUE TITLE
Do you consider multilingual documents

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar#8506]
In quasar version 1.0, there is a relevant Chinese community.
However, the document translation is not complete, especially the api-related parts. It is found through the source code that it is generated because of the related JSON files under the introduced quasar/dist, but there is no such a multi-language solution as I18N.
Whether to consider giving better support for multiple languages on QUASAR 2.0

http://www.quasarchs.com/vue-components/chat

**Comment by rstoenescu** [comment]
Hi.

The author of that website (not us) can duplicate those JSON API files and translate them. They don't have to be located on the "quasar" NPM package...
