### ISSUE TITLE
Quasar v2 - Docs - Right Drawer - blue marking not moving

### ISSUE THREAD

**Issue by enpasos** [quasarframework/quasar#8508]
v2.0.0-beta6
tested in FF 85.0.2

On the right drawer the blue marking is not moving to a new selected topic.

**Comment by rstoenescu** [comment]
Looks fine to me. Tested with same version (85.0.2 (64-bit)) on macos...
Any specific page that has this problem? Is anyone else experiencing this?

**Comment by enpasos** [comment]
Maybe it depends on the OS ... I am running on Windows 10.

**Comment by rstoenescu** [comment]
@enpasos any specific page that this happens on or all of them? any errors in the console?

**Comment by enpasos** [comment]
@rstoenescu  e.g. https://next.quasar.dev/vue-components/ajax-bar ... I have the experience on the whole site (on this Windows 10 PC) ... no error in the console

**Comment by enpasos** [comment]
by the way ... FF on iPad: no problem

**Comment by Smrtnyk** [comment]
Maybe he just has cached version of site or something, for me works perfectly fine on ff

**Comment by Smrtnyk** [comment]
I am able to see it on chrome
![Capture](https://user-images.githubusercontent.com/31451544/108631388-173a8a80-746a-11eb-84d2-de7c88196349.JPG)

I clicked introduction but the menu item on right stayed focused on  tips

**Comment by hawkeye64** [comment]
![quasarv2-right-menu--issue](https://user-images.githubusercontent.com/10262924/108634377-85655a00-7436-11eb-9b5b-7b7797bba5ed.gif)

**Comment by rstoenescu** [comment]
Oh, I thought scrolling the page didn't change it. Found the culprit and fixed it. Will work correctly on next deployment.
