### ISSUE TITLE
Running on Windows Server

### ISSUE THREAD

**Issue by gabrielmsd** [quasarframework/quasar#851]
I've tried to run a quasar project using "quasar dev" in Windows Server 2012 and nothing happens. After that, i've tried to run using "npm run dev" and I've got the following erros messages:

npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! quasar-app@0.0.1 dev: `node build/script.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quasar-app@0.0.1 dev script 'node build/script.dev.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quasar-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/script.dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quasar-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quasar-app
npm ERR! There is likely additional logging output above.

Obs: The same project runs in my local environment (Windows 7).
Obs2: Quasar Framework - v0.14.2

![npm-version](https://user-images.githubusercontent.com/14005011/29989364-dac5e13a-8f48-11e7-9a07-20f65d3c4c23.PNG)

**Comment by rstoenescu** [comment]
Please redirect this bug to the appropriate repo: https://github.com/quasarframework/quasar-template-default (assuming you are using the default template).

Also specify the terminal that you are using. I believe this error is determined by a security setting on your OS, but don't have a Windows Server 2012 to test on...
