### ISSUE TITLE
add an option to define class to all popups global nodes

### ISSUE THREAD

**Issue by iagafonov** [quasarframework/quasar#8510]
**Is your feature request related to a problem? Please describe.**
We want to use Quasar components in our old application with the set of existing classes that intersect with the quasar classes.
For this purpose I created postcss [plugin](https://github.com/iagafonov/postcss-add-root-selector) to wrap quasar styles with our custom selector, and this thing works well. But it doesn't work with popup (portal) components, which are inserted in the body

**Describe the solution you'd like**
I want to add an option to define class, which will be applied to all popup (portal) components root (global-nodes.js, createGlobalNode function creates that)

**Additional context**
I will create an a PR for that option, but I want to be approved first, and I don't know how to name this option and where to put it (and which docs I should change)

**Comment by pdanpdan** [comment]
Maybe it helps that all the quasar popup components have one of .q-dialog, .q-menu or .q-tooltip classes.

**Comment by iagafonov** [comment]
> Maybe it helps that all the quasar popup components have one of .q-dialog, .q-menu or .q-tooltip classes.

All that class are wrapped by postcss [plugin](https://github.com/iagafonov/postcss-add-root-selector) and works only inside custom root selector, and presented in resulting css like this: `.some-root .q-dialog, .some-root .q-menu and .some-root .q-tooltip`

**Comment by rstoenescu** [comment]
Available in Quasar v2.0.0-beta.11
`globalNodes: { class: 'myclass' }`
