### ISSUE TITLE
Provide InjectionKey as option when installing Vuex plugin

### ISSUE THREAD

**Issue by jaredmcateer** [quasarframework/quasar#8511]
**Is your feature request related to a problem? Please describe.**
I want to be able to provide an InjectionKey when installing the vuex plugin so I can get better typescript support.

**Describe the solution you'd like**
There needs to be a mechanism for providing a `Symbol`,

```ts
// store/index.ts
export const key: InjectionKey<Store<MyStateInterface>> = Symbol()
```

as an option when installing the vuex store 
```js
// .quasar/client-entry.js
import {key} from '../src/store'
app.use(store, key)
```

and allows the user to also use this `Symbol` when retrieving the store in a vue component using compositional api 

```ts
// src/pages/Index.vue
setup() {
  // const store = useStore() // <- Store<any>
  const store = useStore(key) // <- Store<MyStateInterface>
}
```

**Describe alternatives you've considered**
It's possible to override the type of `useStore` but that is error prone and cumbersome

**Additional context**
Here is the relevant documentation for using InjectionKey with Vuex4 
https://next.vuex.vuejs.org/guide/typescript-support.html#typing-usestore-composition-function

**Comment by rstoenescu** [comment]
Will be available through q/app v3.0.0-beta.11

**Comment by farums** [comment]
quasar.conf.js =>   store: 'src/Domain/App/Store.ts',

Error:Module not found: Can't resolve imported dependency "app/src/store/index"
```ts
import createStore from 'app/src/Domain/App/Store.ts'
  const { storeKey } = await import('app/src/store/index');
```

**Comment by IlCallo** [comment]
Fixed, will be available in next release
