### ISSUE TITLE
Spinners don't show properly when RTL is enabled

### ISSUE THREAD

**Issue by iJosephY** [quasarframework/quasar#8514]
**Describe the bug**
When you set RTL to true in quasar.conf.js and use QSpinner component or ongoing notification they don't render or animate properly.

**Codepen/jsFiddle/Codesandbox (required)**
Couldn't manage to create one, sorry

**To Reproduce**
Create a new project
set RTL to true in build.rtl
add a QSpinner component or a ongoing notifications

**Expected behavior**
full shape and animation

**Screenshots**
https://cdn.discordapp.com/attachments/806171748046733332/812339040338051135/unknown.png
![image](https://user-images.githubusercontent.com/42868470/108570634-b3e81580-730e-11eb-82ef-5509abe60b84.png)

**Platform (please complete the following information):**
Quasar Version: latest
@quasar/app Version: latest
Quasar mode:
  [ ] SPA
Tested on:
  [ ] SPA
OS: Windows 10
Node: 14.15.4
Yarn: 1.22.5
Browsers: Latest Chrome Version

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.7
