### ISSUE TITLE
Quasar v2 beta Website is extremly slow from China, while Quasar v1 website is ok

### ISSUE THREAD

**Issue by tongorz** [quasarframework/quasar#8519]
Quasar v2 beta Website is extremly slow from China, while Quasar v1 website is ok. VPN can not help to solve this problem.

Url: `https://next.quasar.dev`
![next](https://user-images.githubusercontent.com/28854458/108633242-2b07e000-74ae-11eb-8776-02706fa0837f.jpg)

**Comment by hawkeye64** [comment]
It's because v2 is running as SPA and not SSR. We are still waiting on Vue 3 to make some fixes to properly support SSR.
