### ISSUE TITLE
How is not possible to move or rename styles/quasar.variables.scss?

### ISSUE THREAD

**Issue by mvsantos013** [quasarframework/quasar#8520]
It should be a essential feature to rename or move quasar.variables.scss, but it can't be done not even with quasar.conf.js...

My app, unfortunatelly, has the current structure:

```
assets/
    css/
    fonts/
styles/
```

I'm sorry to say, but that's very annoying...

**Comment by pdanpdan** [comment]
Hello. We feel for your grief.

**Comment by mvsantos013** [comment]
So, it's not on the roadmap to add this option?

**Comment by pdanpdan** [comment]
I can see no point to do something like this in Quasar v1.
It's just something that is loaded by webpack, why would you put it under assets when you can put it under src/styles?

**Comment by mvsantos013** [comment]
I just learned about Quasar and got interested, should I move to v2? Is it a possibility in v2?

Well, I definately moved all css to styles now, no problem, but I think would be cool to give the user the option to organize the app folder structure.
