### ISSUE TITLE
q-input error slot it not rendered

### ISSUE THREAD

**Issue by ntoljic** [quasarframework/quasar#8522]
When using the error slot in a q-input component, the content is not shown when `error` is `true`.

As an example you can have a look at the quasar docs for [external input validation](https://next.quasar.dev/vue-components/input#external-validation). The example with `error-message` displays the error, while the example with the error slot does not.

**To Reproduce**
1. Go to https://next.quasar.dev/vue-components/input#example--slot-for-error-message
2. Type a string into the input field that is longer than 3 characters
4. See missing error

**Expected behavior**
The error slot should be rendered

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.7
@quasar/app Version: 3.0.0-beta.7
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: macoOS
Node: v12.14.1
NPM: 6.13.4
Yarn: 1.21.1
Browsers: Firefox, Chrome, Safari

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.8

**Comment by tuxuuman** [comment]
Still not working. v2.0.0-beta.12

**Comment by rstoenescu** [comment]
@tuxuuman it is working. Check docs, for example. Are you sure that you are not mixing internal and external validation? If I missed anything, please supply a codepen or jsfiddle.

**Comment by Lalrinfela** [comment]
I face the same problem. I am mixing the external and internal validation (in most of my application, i need to use a mix of both), and it used to work this whole time. Is there any change lately.

```
<q-input
    :error="errors.hasOwnProperty('phone')"
    :rules="[val => !!val || 'Field is required']"
    bg-color="white"
    label="Phone No. (10 Digit)" outlined square
    type="tel"
    bottom-slots
    v-model="auth.phone">
    <template v-slot:error>
        <span :key="index" v-for="(title, index) in errors.phone">
          {{title}}
        </span>
    </template>
</q-input>
```

When POST to api, the server validates and send back error messages. These error messages are set in the 'errors' object. Is it possible to bring back the mixable feature please.
@rstoenescu
