### ISSUE TITLE
Providing further options with Dialog Plugin using custom component not working

### ISSUE THREAD

**Issue by mkarras** [quasarframework/quasar#8523]
**Describe the bug**
When using the Dialog Plugin with invoked component ([doc](https://next.quasar.dev/quasar-plugins/dialog#invoking-custom-component)), providing other options then `component` or `componentProps` not working. `opts` is from type `QDialogOptions` with properties like `transitionShow` or `position`.

**Code Example**
Because i cant setup the problem within CodePen (here it worked without a not fully furnished dialog component: https://codepen.io/MTOTHEK/pen/YzprEvB) here a full example for components reproducing the problem.

`OpenDialogBtn.vue`:
```
<template>
  <QBtn label="Open Dialog" @click="openDialog" />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useQuasar } from 'quasar';

export default defineComponent({
  name: 'OpenDialogBtn',
  setup() {
    const { dialog } = useQuasar();

    const openDialog = () => {
      dialog({
        component: DialogTest,
        componentProps: {},
        transitionShow: "fade-in", // <-- not working
        position: "top" // <-- not working
      });
    };

    return {
      openDialog
    };
  }
}
</script>
```

invoked `DialogTest.vue` component:
```
<template>
  <QDialog ref="dialogRef" @hide="onDialogHide">
    <QCard>
      <QCardSection>Title</QCardSection>
      <QCardSection class="q-pt-none">Content</QCardSection>
      <QCardActions align="right">
        <QBtn flat label="Close" color="primary" @click="onCancelClick" />
      </QCardActions>
    </QCard>
  </QDialog>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useDialogPluginComponent } from 'quasar';

export default defineComponent({
  emits: [...useDialogPluginComponent.emits],
  setup() {
    const {
      dialogRef,
      onDialogHide,
      onDialogCancel
    } = useDialogPluginComponent();

    return {
      dialogRef,
      onDialogHide,
      onCancelClick: onDialogCancel,
    };
  }
});
</script>
```

**Expected behavior**
All properties of `QDialogOptions` can be used and work.

**Platform**
Vue: 3.0.5
Quasar: 2.0.0-beta.7

**Comment by rstoenescu** [comment]
How is this a bug? You have QDialog directly in your custom component. So add the props there. Or if you need them to be dynamic, make some props on your component and assign them to the QDialog.

**Comment by mkarras** [comment]
Okay thank you. It would help to describe this in docs. I just saw the opts from type `QDialogOptions` and used it. But as you said, in case of a custom component you have to do it inside the custom component and cant use the `QDialogOptions`.
