### ISSUE TITLE
[docs] Electron Public folder access

### ISSUE THREAD

**Issue by bjbk** [quasarframework/quasar#8528]
## Issue: accessing static files (ie: png, etc) in public folder

[Documentation states:](https://quasar.dev/quasar-cli/developing-electron-apps/electron-static-assets#Introduction)
> [W]hen we deal with Electron then Quasar CLI offers a handy __static variable in addition. Statics can be consumed by both the main process and renderer process, but since the paths change when building for production (due to packaging), then usage with fs and other modules that need a full path can be a little tricky. So __statics can come into play.

**Question:** Where is the CLI documentation on the `__static` variable?

So, say one needs to add some icons or images to they Tray or TouchBar API's in the main process, the Public folder is the place to put them so Webpack knows what to do.  Therefore the documentation says to do [this:](https://quasar.dev/quasar-cli/developing-electron-apps/electron-static-assets#Static-assets-with-fs%2C-path-and-__statics)

>Let’s say we have a static asset that we need to read into our application using fs, but how do we get a reliable path, in both development and production, to the statics/ folder? Quasar provides a global variable named __statics that will yield a proper path to it. Here’s how we can use it to read a simple text file in both development and production.

However, when using `__statics` in the main process, the variable is undefined.  Where is the documentation on how to define it?

```javascript
// main or renderer process

import fs from 'fs'
import path from 'path'

let fileContents = fs.readFileSync(
  path.join(__statics, '/someFile.txt'),
  'utf8'
)
```

this results in `__statics` being undefined. Even when including this in the `electron.main.js` file:
```javascript
if (process.env.PROD) {
  global.__statics = require('path').join(__dirname, 'statics').replace(/\\/g, '\\\\')
}
```

Example:
`path.join(__statics, '/help.png')` fails 

Attempt at implementation:
```javascript
// create touchbar button
import path from 'path'
import { TouchBar } from 'electron'
const { TouchBarButton } = TouchBar

const pathToIcon = path.join(__statics, '/help.png') // ! __statics undefined
const helpIcon = nativeImage.createFromPath(patToIcon).resize({ height: 22 })

const helpButton = new TouchBarButton({
  icon: helpIcon,
  label: 'Help',
  click: () => { //do stuff }
})
```

Is the setting somewhere in `quasar.conf.js`? There is no note in the docs [here](https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron#Introduction).

Also, the CLI documents have this statement in the v2 prep:
> (@quasar/app 2.0.7+) Ignores the /public folder. If you depend on a statics folder then you will need to configure it yourself (outside of Quasar or through the extendWebpack/chainWebpack), so make sure that you know what you are doing.

Wish I knew what I was doing. 😄 My v1 app uses the `"@quasar/app": "^2.1.15"`

**Questions:** Is the documentation regarding the use of static assets in the public folder outdated, or is my understanding of how to properly implement it flawed?  If it must be configured outside of Quasar, as stated above, then why is the statement about the `__static` variable still in the docs?  Is there a better way to use assets in the main process and create paths to them that Webpack understands?  If this is outside of the scope of the Quasar docs, where does one go to find a way to configure?

**Comment by rstoenescu** [comment]
Just replace:

```js
if (process.env.PROD) {
  global.__statics = require('path').join(__dirname, 'statics').replace(/\\/g, '\\\\')
}
```

with the proper way (that q/app spawn when adding electron mode):

```js
if (process.env.PROD) {
  global.__statics = __dirname
}
```

We missed this in our q/app v1 to v2 upgrade guide.

**Comment by bjbk** [comment]
Thanks, @rstoenescu .  I'm still getting `__statics` undefined.  Will keep digging to see what else I have done wrong.

**Comment by devszr** [comment]
I have the same problem. __statics is always showing up as undefined. However, if I do a console.log(__global) I can see that global.__statics exists inside the .vue file's created() method. Very strange.

**Comment by devszr** [comment]
@rstoenescu not sure what I'm doing wrong, but it seems like this line `<script>window.__statics` = `__dirname</script>` which gets added to the generated index.html after a build is after `<div id=q-app></div>`. Now, if I manually move `<div id=q-app></div>` to the end of the generated index.html after all the <script> entries, I am able to access __statics in my App.vue. Any ideas?

I'm using 
`@quasar/cli - 1.2.0`
`quasar - 1.15.16`
`@quasar/app - 2.2.6`
`@quasar/extras - 1.10.5`
`vue - 2.6.12`

**Comment by devszr** [comment]
So, further to my previous post, changing the line 

`data.bodyTags.push(`
`  makeScriptTag(bodyScript)`
 `)`

to

`data.bodyTags.unshift(`
`  makeScriptTag(bodyScript)`
 `)`

in node_modules/\@quasar/app/lib/webpack/plugin.html-addons.js also seems to work in both dev and production environments. Could someone who knows more of the Quasar internals comment as to if this might break something else or why this might be happening?
