### ISSUE TITLE
Navigation/routes fail to change when building capacitor app for iOS

### ISSUE THREAD

**Issue by JonathanSloan** [quasarframework/quasar#8529]
**Describe the bug**
When developing using capacitor on iOS application runs properly, but when built navigation fails to work. Once logged in I see the notification and changes in the drawer and nav bar, but the redirect to /home fails and no links in my drawer will work when clicked.

**Codepen/jsFiddle/Codesandbox (required)**
I am prohibited from directly sharing code/repo by my employer, but can share any logs or details outside of such.

**To Reproduce**
1. after installing capacitor, run `quasar build -m capacitor -T ios --ide`

**Expected behavior**
Route should automatically change to /home once logged in. Navigation links should change views.

**Screenshots**

**Platform (please complete the following information):**
  Quasar Version: 1.15.3 and 1.15.4
@quasar/app Version: 2.1.14 and 2.1.15
Quasar mode:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [x] Capacitor
  [ ] BEX
Tested on:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [x] Capacitor
  [ ] BEX
OS: macOS 11.2.1
Node: 14.15.4
NPM: 7.5.4
Yarn:
Browsers:
iOS: 11.0
Android:
Electron:

**Additional context**
user g_holt at this link: https://forum.quasar-framework.org/topic/7843/capacitor-routes-won-t-change-when-building-ios-applicaiton said the following (I am unsure where he got this from, and may not be the case for me): 

"I’m using router hash mode and on initial load the url is capacitor://localhost# instead of capacitor://localhost/#. So there is no trailing slash initially which breaks things. Sometimes when I navigate around this gets corrected. I tried setting PUBLIC_PATH=capacitor://localhost/ but it doesn’t seem to work."

The only error I see within xcode is: `2021-02-22 13:40:45.122741-0500 App[12125:127986] API error: <_UIKBCompatInputView: 0x7fe4c85096a0; frame = (0 0; 0 0); layer = <CALayer: 0x6000022e0e00>> returned 0 width, assuming UIViewNoIntrinsicMetric`.

**Comment by rstoenescu** [comment]
What is the Capacitor version that you are using? We've never encountered this with Capacitor v2 (and not yet recommending Capacitor v3 beta because we haven't got to the point of adding support for it yet).

**Comment by rstoenescu** [comment]
Run a `quasar info` command in the root of your project and post the output here.

**Comment by JonathanSloan** [comment]
Here is the output for `quasar info`:

Operating System - Darwin(20.3.0) - darwin/x64
NodeJs - 14.15.4

Global packages
  NPM - 7.5.4
  yarn - Not installed
  @quasar/cli - 1.1.3
  @quasar/icongenie - 2.3.3
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.15.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.1.15 -- Quasar Framework local CLI
  @quasar/extras - 1.9.17 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.12 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.6.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.12.10 -- Babel compiler core.
  webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.9.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 2.4.6 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/cli - 2.4.6 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - Not installed
  @capacitor/ios - 2.4.6 -- Capacitor: cross-platform mobile apps with the web

Quasar App Extensions
  *None installed*

Networking
  Host - ENG-JSloan
  en1 - 192.168.1.207

**Comment by JonathanSloan** [comment]
I have noticed this warning in xcode as well, but I am unsure of its relevance:
`App[33692:994291] [Snapshotting] Snapshotting a view (0x7fd37b026e00, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.`

**Comment by JonathanSloan** [comment]
My apologies, I have discovered that the issue was on my end and not yours. Another developer made changes involving routing that flew under the radar. Thank you for your assistance!

**Comment by rstoenescu** [comment]
Glad that u figured it out!
