### ISSUE TITLE
A couple of questions about the framework...

### ISSUE THREAD

**Issue by MejorCodigo** [quasarframework/quasar#853]
Hi, so I want to start with this framework, it looks really good. 

However, I would like to know if it's possible to use cordova plugins? For example, the inappbrowser, geolocation, etc. I would also like to know how I would go about using the plugins and where are the cordova specific events located (onDeviceReady)?

Some plugins require to be initialized in the `onDeviceReady`  event function and other, like for example the geolocation plugin, can be used across the whole app by running `navigator.geolocation.getCurrentPosition(onSuccess, onError, { timeout: 5000 });` in the Javascript.

**Comment by ILABUTK** [comment]
geolocation is possible in this framework. You can use VueGoogleMaps etc.

**Comment by MejorCodigo** [comment]
Can you use all other Cordova plugins?

**Comment by rstoenescu** [comment]
All Cordova plugins are available.

`Quasar.start(Function Callback)` takes care of listening to ondeviceready event and then fires the callback.
