### ISSUE TITLE
QRadio bound to numeric value

### ISSUE THREAD

**Issue by andrisi** [quasarframework/quasar#8530]
**Describe the bug**
When a radio item is bound to a numberic value (v-model.number="days") than the value is set currectly in Vue (.days property here), but the radio does not pick up the value visually, so none are selected. Of course the val="7" values might be typed as string...

**Expected behavior**
If a value is bound as numberic, then val should be treate as such too.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 1.14.7
@quasar/app Version: 2.1.13

**Comment by pdanpdan** [comment]
#8469

**Comment by rstoenescu** [comment]
Reopened for later assesment of the idea

**Comment by andrisi** [comment]
Thanks! BTW, works ok if you create the radios from an array of numbers, and use a :value assignment.

**Comment by pdanpdan** [comment]
I fail to understand what you want.
As I suppose you were too busy to add a codepen here is one for you: https://codepen.io/pdanpdan/pen/JjbOyLz?editors=1010
Please add the not working example.

**Comment by andrisi** [comment]
Sorry... will try next time. So the one below does work, but the apropriate radio is not highlighted visually, as the .days value is 1 and the value="1" is perhaps interpreted as a string. If I generate the radios from an array of numbers [1, 7, 14] assinging them to :value then all works fine - this is why I assume it is a string/into type problem.

`<q-radio v-model.number="days" :val="1" />`

**Comment by pdanpdan** [comment]
Please make that bloody codepen that shows the problem.

**Comment by andrisi** [comment]
I tried, but now can not reporduce... feel like a newbie. Sorry for the distraction. Works fine now.
