### ISSUE TITLE
Tree-shakeable fontawesome 5 svg icon support in QIcon

### ISSUE THREAD

**Issue by schniper** [quasarframework/quasar#8531]
As I don't have the proper setup to create a proper pull request and I also have a question mark related to dependencies, I'd like to describe this idea first.

Fontawesome allows for a treeshaking approach, when using @fortawesome/fontawesome-svg-core together with some of the @fortawesome/pro-duotone-svg-icons, @fortawesome/free-brands-svg-icons. This means it works both with the free and with the pro icons.

In order to be able to use pro svg icons as well as free icons, I came up with the following changes to QIcon.
My only hesitation is that it would introduce a dependency in QIcon to @fortawesome/fontawesome-svg-core. But this being a free library, it could be acceptable.

So here goes: q-icon will support icons with names like `fad:envelope`, `fab:facebook`, etc.

QIcon needs:
`import { findIconDefinition, icon } from '@fortawesome/fontawesome-svg-core'`

And then, in setup, 2 changes:

First, in the type computed value:

```
if (icon.match(/^fa[blsrd]:/)) {
        const [ _, faPrefix, faIconName, __, extraClasses ] = icon.match(/^(fa[blsrd]):([^ ]+)(\s+(.+))?/)

        return {
          cls: classes.value +
            (extraClasses ? (classes.value.length ? ' ' : '') + extraClasses : ''),
          fa: true,
          faPrefix,
          faIconName
        }
      }
```

Then in the return part of setup, just after const data = {...}:

```
if (type.value.fa === true) {
        const builtIcon = icon(findIconDefinition({ prefix: type.value.faPrefix, iconName: type.value.faIconName }))
        const fullIconDef = Object.assign({}, builtIcon.abstract[0])

        fullIconDef.attributes.class = type.value.cls + ' ' + fullIconDef.attributes.class

        fullIconDef.attributes.style = Object.assign(sizeStyle.value || {},
          fullIconDef.attributes.style || {})

        function renderSvgNode(abstract) {
          return h(abstract.tag, abstract.attributes, abstract.children ? abstract.children.map(renderSvgNode) : null)
        }

        return renderSvgNode(fullIconDef)
      }
```

This will retain all classes passed to the q-icon tag and uses fontawesome's svg rendering.

In order for treeshaking to work, the approach is to specify all the icons you are going to use.
This is a separate issue, which is needed anyway, if you want to use this feature, with or without QIcon.

The idea is to use boot files to initialise things; this could be very well specified in the framework documentation.

I have this boot file to kickstart fontawesome:

```
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  fad
} from '@fortawesome/pro-duotone-svg-icons'

// instead of all icons, each one can be imported and added, for tree shaking
library.add(
  fad
)
``` 

The above code would include all duotone icons, so not that much treeshaking going on. But you could import { faEnvelope, faCheck, etc. } and then add only these to the library. Treeshaking works.

Then I have created a boot file for the framework icon set, using the syntax from the updated QIcon; sorry for the length, but this is complete and ready to use:

```
import { Quasar } from 'quasar'
import { library } from '@fortawesome/fontawesome-svg-core'

import {
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBold,
  faCalendarCheck,
  faCaretDown,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClipboardCheck,
  faClock,
  faCode,
  faEraser,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExpandArrowsAlt,
  faEyeDropper,
  faFont,
  faHeading,
  faIndent,
  faInfoCircle,
  faItalic,
  faLink,
  faListOl,
  faListUl,
  faLongArrowUp,
  faMinusSquare,
  faOutdent,
  faPencilAlt,
  faPlay,
  faPlus,
  faPlusSquare,
  faPrint,
  faQuoteRight,
  faRedo,
  faSlidersH,
  faStar,
  faStepBackward,
  faStepForward,
  faStream,
  faStrikethrough,
  faSubscript,
  faSuperscript,
  faSwatchbook,
  faSyncAlt,
  faTextHeight,
  faTimes,
  faTimesCircle,
  faUnderline,
  faUndo,
  faUpload
} from '@fortawesome/pro-duotone-svg-icons'

library.add(
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBold,
  faCalendarCheck,
  faCaretDown,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClipboardCheck,
  faClock,
  faCode,
  faEraser,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExpandArrowsAlt,
  faEyeDropper,
  faFont,
  faHeading,
  faIndent,
  faInfoCircle,
  faItalic,
  faLink,
  faListOl,
  faListUl,
  faLongArrowUp,
  faMinusSquare,
  faOutdent,
  faPencilAlt,
  faPlay,
  faPlus,
  faPlusSquare,
  faPrint,
  faQuoteRight,
  faRedo,
  faSlidersH,
  faStar,
  faStepBackward,
  faStepForward,
  faStream,
  faStrikethrough,
  faSubscript,
  faSuperscript,
  faSwatchbook,
  faSyncAlt,
  faTextHeight,
  faTimes,
  faTimesCircle,
  faUnderline,
  faUndo,
  faUpload
)

const definition = {
  name: 'fontawesome-v5-pro-duotone',
  type: {
    positive: 'fad:check',
    negative: 'fad:exclamation-triangle',
    info: 'fad:info-circle',
    warning: 'fad:exclamation'
  },
  arrow: {
    up: 'fad:arrow-up',
    right: 'fad:arrow-right',
    down: 'fad:arrow-down',
    left: 'fad:arrow-left',
    dropdown: 'fad:caret-down'
  },
  chevron: {
    left: 'fad:chevron-left',
    right: 'fad:chevron-right'
  },
  colorPicker: {
    spectrum: 'fad:eye-dropper',
    tune: 'fad:sliders-h',
    palette: 'fad:swatchbook'
  },
  pullToRefresh: {
    icon: 'fad:sync-alt'
  },
  carousel: {
    left: 'fad:chevron-left',
    right: 'fad:chevron-right',
    up: 'fad:chevron-up',
    down: 'fad:chevron-down',
    navigationIcon: 'fad:circle'
  },
  chip: {
    remove: 'fad:times-circle',
    selected: 'fad:check'
  },
  datetime: {
    arrowLeft: 'fad:chevron-left',
    arrowRight: 'fad:chevron-right',
    now: 'fad:clock',
    today: 'fad:calendar-check'
  },
  editor: {
    bold: 'fad:bold',
    italic: 'fad:italic',
    strikethrough: 'fad:strikethrough',
    underline: 'fad:underline',
    unorderedList: 'fad:list-ul',
    orderedList: 'fad:list-ol',
    subscript: 'fad:subscript',
    superscript: 'fad:superscript',
    hyperlink: 'fad:link',
    toggleFullscreen: 'fad:expand-arrows-alt',
    quote: 'fad:quote-right',
    left: 'fad:align-left',
    center: 'fad:align-center',
    right: 'fad:align-right',
    justify: 'fad:align-justify',
    print: 'fad:print',
    outdent: 'fad:outdent',
    indent: 'fad:indent',
    removeFormat: 'fad:eraser',
    formatting: 'fad:heading',
    fontSize: 'fad:text-height',
    align: 'fad:align-left',
    hr: 'fad:minus-square',
    undo: 'fad:undo',
    redo: 'fad:redo',
    heading: 'fad:heading',
    code: 'fad:code',
    size: 'fad:text-height',
    font: 'fad:font',
    viewSource: 'fad:code'
  },
  expansionItem: {
    icon: 'fad:chevron-down',
    denseIcon: 'fad:caret-down'
  },
  fab: {
    icon: 'fad:plus',
    activeIcon: 'fad:times'
  },
  field: {
    clear: 'fad:times-circle',
    error: 'fad:exclamation-circle'
  },
  pagination: {
    first: 'fad:step-backward',
    prev: 'fad:chevron-left',
    next: 'fad:chevron-right',
    last: 'fad:step-forward'
  },
  rating: {
    icon: 'fad:star'
  },
  stepper: {
    done: 'fad:check',
    active: 'fad:pencil-alt',
    error: 'fad:exclamation-triangle'
  },
  tabs: {
    left: 'fad:chevron-left',
    right: 'fad:chevron-right',
    up: 'fad:chevron-up',
    down: 'fad:chevron-down'
  },
  table: {
    arrowUp: 'fad:long-arrow-up',
    warning: 'fad:exclamation-triangle',
    firstPage: 'fad:step-backward',
    prevPage: 'fad:chevron-left',
    nextPage: 'fad:chevron-right',
    lastPage: 'fad:step-forward'
  },
  tree: {
    icon: 'fad:play'
  },
  uploader: {
    done: 'fad:check',
    clear: 'fad:times',
    add: 'fad:plus-square',
    upload: 'fad:upload',
    removeQueue: 'fad:stream',
    removeUploaded: 'fad:clipboard-check'
  }
}

Quasar.iconSet.set(definition)
```

What do you think?

And by the way, fa also exposes a dom.watch() (I think) or similar method, which just watches the DOM and replaces icons all over the place. It’s just that doing it the way I described above seems more controlled, not having an external library’s listeners running all over the place.

**Comment by hawkeye64** [comment]
@schniper We already provide something similar, but with all the svg icon sets available with @quasar/extras: https://quasar.dev/vue-components/icon#Svg-usage

**Comment by schniper** [comment]
Doesn’t this look like you need to import icons in every component and furthermore that you need them in the format you have extracted them in @extras? For fa pro this is no go...

**Comment by schniper** [comment]
What could be nice then, would be to allow that icon map method you have in there return the render result directly under some parameter name, instead of just the converted name. That would allow us to use any library in the back and just render the icons that way. It would need to receive a few more params though, like the extra classes and style.

**Comment by hawkeye64** [comment]
@schniper I am thinking we need a CLI. Maybe even an app-ext that registers a command with Quasar CLI that can take a folder and output a file in Quasar svg format...

As for the above, doing it that way for just one SVG package seems a bit overkill to be added to Quasar.

**Comment by schniper** [comment]
What about my idea to extend the use of the icon map function, to render icons too instead of just messing with the names?

**Comment by hawkeye64** [comment]
I would need to talk to @rstoenescu about the merits.

**Comment by schniper** [comment]
I can talk to him in Romanian, if needed :))
The advantage, again, is that we would allow anyone to use any icon rendering technique / library they want. We would not be constrained by the short list of modified icons quasar exposes.
I am willing to suggest a pull request for either an updated signature icon map function, or a different hook method, specialized in rendering an icon, instead of just renaming it or returning the quasar style of svg text, which sometimes is a lot harder to extract than just render the image some other way.
Keep me in the loop, please. Until this is settled, I have aliased my modified QIcon version and I am using that. But it feels dirty :)
Thank you

**Comment by hawkeye64** [comment]
Please contact @rstoenescu about a PR concerning this. He can tell you to go ahead, rather than wasting time on something that may not be accepted. Good luck.

**Comment by sgielen** [comment]
@hawkeye64 @rstoenescu @schniper did anything ever come out of this? I can find fontawesome pro support since v2.6.2 in the documentation, but it seems to include [all icons without tree shaking](https://github.com/quasarframework/quasar/issues/12834#issuecomment-1079110566). How should I use, for example, `faChartNetwork` after `import { faChartNetwork } from '@fortawesome/pro-regular-svg-icons'`?
