### ISSUE TITLE
QInput autofocus causes rendering issues in Chrome / Safari (not FireFox)

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8533]
**Describe the bug**
Using a QDialog to open a 'wizard' based on a QStepper, where each step contains a QInput, if the QInput is set to `autofocus`, the first step is not rendered properly on Chrome and Safari. Firefox appears to work correctly.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/full/OJbxBbQ
Note the issue _appears_ to be related to viewport height, and so full-screen view is sometimes needed to reproduce the error on smaller monitors. Switching to Editor view will _sometimes_ fix the issue when the window is not very tall. Likewise, changing the number of steps in the `data` section will affect whether or not the problem manifests.

**To Reproduce**
1. Go to the codepen in Chrome (windows or mac) or Safari (mac)
2. Click on Show Popup
3. The first step is rendered 'above' the top of the QDialog
4. Typing some characters brings the QInput into view, but the behaviour is different on Chrome and Safari
5. Change to a different step (e.g. Step 2), then close the dialog (Escape)
6. Re-open the dialog, and all is correct.
7. Go back to Step 1, close, reopen the dialog to see the error again.

**Expected behavior**
Step 1 would be rendered correctly

**Screenshots**
Initial state (incorrect):
![image](https://user-images.githubusercontent.com/900542/109026377-95d83780-76b7-11eb-8354-0d07c9fece50.png)

After typing 'test', the QInput is shown, but the Step Title is not (on Chrome—on Safari, typing brings the Step Title into view as well):
![image](https://user-images.githubusercontent.com/900542/109026654-e3ed3b00-76b7-11eb-90ac-d123de2fdaee.png)

After selecting Step 2, closing, reopening (now Step 1 is visible and selectable):
![image](https://user-images.githubusercontent.com/900542/109026434-a4beea00-76b7-11eb-90a0-4a6626ea36f1.png)

**Platform (please complete the following information):**
Quasar Version: 1.15.4
OS: Windows 10, macOS
Browsers: Chrome (88 & 90), Safari (14)

**Additional context**
Removing `autofocus` from the QInput seems to fix the rendering issue on all platforms / browsers.

**Comment by dsl101** [comment]
I'm not sure I follow what's happening with this one—any chance of a quick update?

**Comment by dsl101** [comment]
Sorry if I'm just making noise—any chance of a comment on where this is at?

**Comment by rstoenescu** [comment]
Fixed for v2.0.0-rc.1 (with one gotcha that on iOS the fields will get focused but now keyboard won't pop up; no way around it).

Considering a port to v1 as well.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.4.12 & v1.17.7
