### ISSUE TITLE
HMR not working for files directly imported in the router

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#8534]
**Describe the bug**
When starting up a new project (I added Vuex and Typescript, and using Class components FYI) and running the dev server the HMR seems broken for files that are imported in the `routes.ts` file. So in this case the `layouts` and `pages`.

**To Reproduce**
1. Create a new app as described above.
2. Startup the dev server'
3. Add some text to "Index.vue" and save
4. Check if HMR worked

**Expected behavior**
HMR should work for all files, also the pages and layouts that are imported in the router.

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.7
@quasar/app Version: v3.0.0-beta.7
Quasar mode:
 - [x] SPA
 - [ ] SSR
 - [ ] PWA
 - [ ] Electron
 - [ ] Cordova
 - [ ] Capacitor
 - [ ] BEX

Tested on:
 - [x] SPA
 - [ ] SSR
 - [ ] PWA
 - [ ] Electron
 - [ ] Cordova
 - [ ] Capacitor
 - [ ] BEX

OS: Windows
Node: v12.13.1
NPM: 6.12.1
Yarn: 1.22.4
Browsers: Chrome
iOS:
Android:
Electron:

**Comment by SuspiciousLookingOwl** [comment]
Seems like this is caused by `vue-class-component`. I had similar issue and after changing the component type to normal options API the HMR started to work

**Comment by rstoenescu** [comment]
This is an issue that should be reported to `vue-class-component` owners, not Quasar.

**Comment by Evertvdw** [comment]
Reported issue at vue-class-component: https://github.com/vuejs/vue-class-component/issues/521
