### ISSUE TITLE
q-table with body slot : @selection details.evt is undefined

### ISSUE THREAD

**Issue by yellowgrey** [quasarframework/quasar#8535]
**Describe the bug**
When use the `body slot` feature of the `q-table`, parameter `details.evt` of `@selection` event is undefined

**Codepen/jsFiddle/Codesandbox**
[Codepen](https://codepen.io/ylg/pen/gOLogMK)

**To Reproduce**
1. Open the Codepen
2. Open the browser console
3. Click on a checkbox of the table
4. See in the browser console, the `evt` property of the `details` parameter is undefined (`@selection` event)

**Expected behavior**
`details.event` parameter of the `@selection` event is expected to exist, even with the `body slot` use

**Platform**
Quasar Version: 1.14.5
@quasar/app Version: 2.1.8
Quasar mode: SPA

Tested on: SPA
 
OS:
Node: 15.8.0
NPM: 7.5.1
Browsers: chrome 88.0.4324.150

**Comment by rstoenescu** [comment]
Hi,

This is expected, because Quasar is no longer in control of the checkbox. You are. You're defining it so no events can be auto-attached to it.
