### ISSUE TITLE
Vue-Router version does not include composition API helpers

### ISSUE THREAD

**Issue by nathan-rapidstash** [quasarframework/quasar#8537]
The included version of vue-router does not include the composition API functions described here: https://next.router.vuejs.org/guide/advanced/composition-api.html

Appears Vue is currently using  vue-router 3.2.0, latest is 4.0.4.

**Comment by rstoenescu** [comment]
1. Vue Router 4 is shipped for Quasar v2 (through "@quasar/app" v3).
2. Vue Router 3 is shipped for Quasar v1 (through "@quasar/app" v2).
3. You can't use Vue Router 4 with Vue 2.

**Comment by rstoenescu** [comment]
And by the looks of it, you are using Quasar v1 (with Vue 2).

**Comment by nathan-rapidstash** [comment]
@rstoenescu Should we not be using the composition API with Vue 1 then? It is listed as recommended by the vue-cli setup process.

**Comment by rstoenescu** [comment]
It is recommended as one of the TS options. However let's not confuse things. This does not means that Vue Router 4 (which is designed for Vue 3 only) is also compatible with Vue 2. The same goes for the other Vue packages.

The composition api (@vue/composition-api) in Vue 2 is supplied by a plugin created by the Vue Team which is a wrapper over the standard Vue 2. It does not mean that this adds magical support for Vue 3 nor does it makes all vue 2 packages magically offer composables.

If you want the Composition API supplied natively by Vue 3, just use Quasar v2. Then you can take advantage of the whole ecosystem (including Vue Router 4).

**Comment by nathan-rapidstash** [comment]
Makes sense. Thanks!
