### ISSUE TITLE
Indirect val for QToggle or QCheckbox

### ISSUE THREAD

**Issue by ababo** [quasarframework/quasar#854]
I render my toggles from within v-for, so I need to use indirect values (i.e. ":val=..."), but the don't seem to be supported.

**Comment by rstoenescu** [comment]
Hi,

Have you seen [QOptionGroup](http://quasar-framework.org/components/option-group.html)?
Also, can you please reopen with a more detailed case? When creating a new issue on this repo there is a template, please do not disregard that as it helps us help you.

**Comment by ababo** [comment]
Thanks, that seems to be useful.

**Comment by smolinari** [comment]
Hi,

Please use either the [forum](http://forum.quasar-framework.org/) or the [gitter channel](https://gitter.im/quasarframework/Lobby) for general questions. You'll get answers there for sure. 

Thanks. 😄 

Scott
