### ISSUE TITLE
QCarousel swipeable property not working

### ISSUE THREAD

**Issue by SDesya74** [quasarframework/quasar#8540]
Swipeable property not working in Quasar v2. 

Example: https://jsfiddle.net/SDesya74/bfhgqjs1/29/

To reproduce the behavior try to swipe QCarousel.

Quasar Version: v2.0.0-beta.7

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.8
