### ISSUE TITLE
Images from assets folder are incorrectly handled in srcset (QImg and native tags)

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#8548]
There are a couple of bugs in Quasar v2 or one of its dependencies, possibly in webpack plugin that handles asset imports. This happens in dev mode and in production SPA builds. I am hoping you can identify what component is causing this just by looking at it, as Codepen/jsFiddle/Codesandbox cannot be used to replicate this. I can investigate further if I know where to look.

I have the following code in HTML:

```
<picture>
    <source srcset="~assets/logos/logo-dm-2x.png 2x" media="(prefers-color-scheme: dark)" />
    <source srcset="~assets/logos/logo-dm.png 1x" media="(prefers-color-scheme: dark)" />
    <source srcset="~assets/logos/logo-2x.png 2x"/>
    <img src="~assets/logos/logo.png" alt="Image bad" />
</picture>

<img src="~assets/asset.png" srcset="~assets/asset-2x.png 1x, ~assets/asset-2x.png 2x" alt="Image bad" />

<img src="~assets/logos/logo.png" alt="Image works" />

<img src="~assets/asset.png" alt="Image works" />
```

And it gets converted into:

```
<picture>
    <source srcset="img/logo-dm-2x.png2x" media="(prefers-color-scheme: dark)">
    <source srcset="img/logo-dm.png1x" media="(prefers-color-scheme: dark)">
    <source srcset="img/logo-2x.png2x">
    <img src="img/logo.png" alt="Image bad">
</picture>

<img src="img/asset.png" alt="Image bad" srcset="img/asset.png1x, img/asset-2x.png2x">

<img src="img/logo.png" alt="Image works" />

<img src="img/asset.png" alt="Image works" />
```
_Data attributes removed for clarity._

You can see that it does two things here:

- Butchers the resource URL by appending pixel density
- Ignores the subdirectory of assets when creating assets (3rd image works, but if there already was another image named logo.png in ~assets/, then it would have been overwritten)

This only happens with `srcset` attribute, for both QImg and for native tags. With QImg it simply doesn't create any image element - it only creates the wrapper/container elements.

**Platform:**
Quasar Version: 2.0.0-beta.7
@quasar/app Version: 3.0.0-beta.7

**Comment by rstoenescu** [comment]
Hi,

This would be vue-loader at play. Nothing we can do about it unfortunately.
However, you could use the /public folder instead..
