### ISSUE TITLE
Drawer link icons jumping while closing animation

### ISSUE THREAD

**Issue by mkarras** [quasarframework/quasar#8555]
**Describtion**
The icons of drawer links align right / jumping when drawer closes (closing animation runs).

**Codepens**
[Quasar v2](https://next.quasar.dev/layout/drawer#example--mini-mode-with-mouseover-mouseout-trigger)
[Quasar v1](https://quasar.dev/layout/drawer#Example--Mini-mode-with-mouseover%2Fmouseout-trigger) (like it should be)

**To Reproduce**
1. Hover over the closed drawer
2. Leave the opened drawer

**Expected behavior**
The icons alignment does not change like in [Quasar v1](https://codepen.io/pen/?&editors=101&prefill_data_id=effbcdfd-baf3-4794-b04c-83c6a83ee379).

**Platform**
@quasar: v2.0.0-beta.8 (and before)

**Comment by aleksanderbrylski** [comment]
I have the same issue.

**Comment by ThibaultJousse** [comment]
Same issue with v2.0.0-beta12

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.16
