### ISSUE TITLE
 Quasar 2.0 Beta UMD   V-Model

### ISSUE THREAD

**Issue by klagit** [quasarframework/quasar#8556]
Update V-Model not working in the UMD Flavor

<!DOCTYPE html>
<html>
  

  <head>
    <title> Quasar TEST</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.0.0-beta.8/dist/quasar.prod.css" rel="stylesheet" type="text/css">
  </head>

  <body>
    
    <div id="q-app">
	
	 <q-layout view="hHh Lpr lff" container style="height: 300px" class="shadow-2 rounded-borders">
      <q-header elevated class="bg-black">
        <q-toolbar>
          **<q-btn flat @click="drawer = !drawer" round dense icon="menu" />**
          <q-toolbar-title>Header</q-toolbar-title>
        </q-toolbar>
      </q-header>

      <q-drawer
	    **v-model="drawer"** 
	    :width="200"
        :breakpoint="500"
        bordered
        class="bg-grey-3"
      >
        <q-scroll-area class="fit">
          <q-list>

            <template v-for="(menuItem, index) in menuList" :key="index">
              <q-item clickable :active="menuItem.label === 'Outbox'" v-ripple>
                <q-item-section avatar>
                  <q-icon :name="menuItem.icon" />
                </q-item-section>
                <q-item-section>
                  {{ menuItem.label }}
                </q-item-section>
              </q-item>
              <q-separator :key="'sep' + index"  v-if="menuItem.separator" />
            </template>

          </q-list>
        </q-scroll-area>
      </q-drawer>

      <q-page-container>
        <q-page padding>
          <p v-for="n in 15" :key="n">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit nihil praesentium molestias a adipisci, dolore vitae odit, quidem consequatur optio voluptates asperiores pariatur eos numquam rerum delectus commodi perferendis voluptate?
          </p>
        </q-page>
      </q-page-container>
    </q-layout>
	
	
	</div>

    
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.0.0-beta.8/dist/quasar.umd.prod.js"></script>
    
    <script>
		  	   const menuList = [
  {
    icon: 'inbox',
    label: 'Inbox',
    separator: true
  },
  {
    icon: 'send',
    label: 'Outbox',
    separator: false
  },
  {
    icon: 'delete',
    label: 'Trash',
    separator: false
  },
  {
    icon: 'error',
    label: 'Spam',
    separator: true
  },
  {
    icon: 'settings',
    label: 'Settings',
    separator: false
  },
  {
    icon: 'feedback',
    label: 'Send Feedback',
    separator: false
  },
  {
    icon: 'help',
    iconColor: 'primary',
    label: 'Help',
    separator: false
  }
]

      /*
        Example kicking off the UI. Obviously, adapt this to your specific needs.
        Assumes you have a <div id="q-app"></div> in your <body> above
       */
      const app = Vue.createApp({
        setup () {
          return {
		     drawer:true,
			 menuList
		  }
		   
        }
      })

      app.use(Quasar)
      app.mount('#q-app')
    </script>
  </body>
</html>

**Comment by rstoenescu** [comment]
Hi.

Isn't it normal? The `drawer` that you are returning in `setup()` is not reactive.
Then, you are using self-closing tags, which we explicitly [mention in docs](https://next.quasar.dev/start/how-to-use-vue#self-closing-tags) that should not be used for UMD.

```
setup () {
  return {
    drawer: Vue.ref(true),
    menuList
  }
}
```

Example of self-closing tag: `<q-btn  />` . It should be `<q-btn></q-btn>`.

**Comment by rstoenescu** [comment]
Also, you're using QLayout with "container" prop. Please make sure that you understand it. When you want to manage the whole screen real-estate, don't use it. The examples in docs use it cause otherwise it's impossible to show them (they'd overlap each other).

**Comment by klagit** [comment]
Thank you

Now it’s all ok
