### ISSUE TITLE
Add ability to add custom icon name for arrows in QDate

### ISSUE THREAD

**Issue by bak-one** [quasarframework/quasar#8557]
Hi! Almost for all components we can set props for icon name to change default icon. But I can't find if I can do this for the QDate. From the source code I see that I can't do this. Is it possible to add this ability to this component? Because I don't use material icons at all in my project, and don't want to load icon pack just for the date picker.

Arrows that I'm talking about https://i.codeit.pro/kateryna.khomenko/i/chrome_u5sNAWUeqp.png

**Comment by pdanpdan** [comment]
https://quasar.dev/options/quasar-icon-sets#Configuring-the-default-Icon-Set

They are all under `datetime` key.
