### ISSUE TITLE
Adding Q-uploader `max-...` props removes the upload button.

### ISSUE THREAD

**Issue by pazarbasifatih** [quasarframework/quasar#8558]
**Describe the bug**
The some of the props coming from the `composables/use-file.js` are blocking the upload button, thus rendering the component useless. The ones that I've found are `max-file-size` , `max-files`, `max-total-size`.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pazarbasifatih/pen/zYoWQXy

**To Reproduce**
1. Go to your 'q-uploader component'
2. Add on any of the following props 'max-file-size , max-files, max-total-size' with a size value.
3. See error

**Expected behavior**
max-file-size, limits the file size
max-files, limits the number of items
max-total-size, limits the total uploaded size,

**Screenshots**
![image](https://user-images.githubusercontent.com/42507858/109496995-7586ef00-7aa2-11eb-88c0-a98e3798080e.png)

**Platform (please complete the following information):**
Quasar Version: 2 beta 8
@quasar/app Version: 3 beta 8
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
`Reproduceable on Codepen`
OS: Windows 
Node: 14.15 LTS
NPM: 6.14
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.9
