### ISSUE TITLE
Responsive font size support

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#8560]
I have an environmental sensor dashboard that requires responsive font size support on mobile devices.   The work has been done here:  https://github.com/twbs/rfs  

It should be easy to implement for gurus such as yourself, and even an example in the docs for how one could include the existing rfs library seamlessly or as a plugin or extra would be good enough.

**Comment by hawkeye64** [comment]
Duplicate https://github.com/quasarframework/quasar/issues/4320

**Comment by Daemach** [comment]
I don't agree.  The other issue is not specific to RFS and I am concerned that this will get lost.  RFS should be easy to add without the extra cruft in that post.

**Comment by hawkeye64** [comment]
My referencing the other issue, this one will automatically also be referenced.

**Comment by hawkeye64** [comment]
I am also going to reference this RFC: https://github.com/quasarframework/rfcs/issues/3
