### ISSUE TITLE
Support for fragment-like component

### ISSUE THREAD

**Issue by PaulCombal** [quasarframework/quasar#8565]
**Is your feature request related to a problem? Please describe.**
I would like to export a component composed of a QDialog, and a QTable. To do so, I would need to export two root elements (not possible), or wrap both of them in an useless div (yuck).

**Describe the solution you'd like**
I believe a good take on this issue would be to introduce Fragments, similar to what React uses specifically for this situation.

**Describe alternatives you've considered**
I find [this article](https://blog.logrocket.com/fragments-in-vue-js/) very interesting, and I'm actually going with their solution.

**Additional context**
I would love if this was a Quasar component out of the box.
As always much love for all your work and support.

**Comment by pdanpdan** [comment]
Hello. Vue2 does not support fragments.
Vue2 supports fragments. Check next.quasar.dev
