### ISSUE TITLE
Electron main process build failed after upgrated from v1 to v2

### ISSUE THREAD

**Issue by faxinwang** [quasarframework/quasar#8566]
Previously quasar dev -m electron can start my project normally. When I upgrade to quasar v2, after solved all reported errors of the renderer process code, according to [quasar upgrade guide](https://next.quasar.dev/start/upgrade-guide), and adjust files according to the [Upgrade guide on Electron](https://next.quasar.dev/quasar-cli/developing-electron-apps/electron-upgrade-guide#introduction) , the Webpack build process of the main process code report the following error.

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 84833 ms
 ├── Preload process  ███                  10% building 1/2 modules 1 active
 └── Main process     ████████████████████ 100% done in 30629 ms

 App · Webpack built Electron main process

Hash: 4e75f4a0f10d0d277d02
Version: webpack 4.44.1
Time: 30636ms
Built at: 2021-03-03 8:07:12 ├F10: PM┤
           Asset      Size         Chunks  Chunk Names
electron-main.js  5.56 KiB  electron-main  electron-main
Entrypoint electron-main = electron-main.js

ERROR in ./src-electron/electron-main.ts
Module build failed (from ./node_modules/ts-loader/index.js):
  Error: TypeScript emitted no output for D:\Learn\web\quasar\myproject\src-electron\electron-main.ts.

  - index.js:53 makeSourceMapAndFinish
    [myproject]/[ts-loader]/dist/index.js:53:18

  - index.js:40 successLoader
    [myproject]/[ts-loader]/dist/index.js:40:5

  - index.js:23 Object.loader
    [myproject]/[ts-loader]/dist/index.js:23:5

 @ multi ./src-electron/electron-main electron-main[0]

 App · ⚠️  Electron main build failed with errors

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 84833 ms
 ├── Preload process  ████████████████████ 100% done in 57787 ms
 └── Main process     ████████████████████ 100% done in 30629 ms

 App · Webpack built Electron preload process

Hash: d5daa056daaddb3fe6da
Version: webpack 4.44.1
Time: 57790ms
Built at: 2021-03-03 8:07:40 ├F10: PM┤
              Asset      Size            Chunks  Chunk Names
electron-preload.js  5.59 KiB  electron-preload  electron-preload
Entrypoint electron-preload = electron-preload.js

ERROR in ./src-electron/electron-preload.ts
Module build failed (from ./node_modules/ts-loader/index.js):
  Error: TypeScript emitted no output for D:\Learn\web\quasar\myproject\src-electron\electron-preload.ts.

  - index.js:53 makeSourceMapAndFinish
    [myproject]/[ts-loader]/dist/index.js:53:18

  - index.js:40 successLoader
    [myproject]/[ts-loader]/dist/index.js:40:5

  - index.js:23 Object.loader
    [myproject]/[ts-loader]/dist/index.js:23:5

 @ multi ./src-electron/electron-preload electron-preload[0]

 App · ⚠️  Electron preload build failed with errors

**Platform (please complete the following information):**
Quasar Version:  2.0.0-beta.8
@quasar/app Version:  3.0.0-beta.8
Quasar mode:
  [x] SPA
  [x] Electron

OS: win10
Node: v12.18.4
NPM: 6.14.9
Yarn: 1.22.5
Electron: 11.3.0

electron-preload.ts:

```typescript
import {contextBridge} from 'electron';
import {tmpdir} from 'os';

contextBridge.exposeInMainWorld("napi",{
    os:{
        tmpdir,
    },
})
```

could you please tell me what is the problem and how can I solve it. thank you. I have been stuck for two days.

**Comment by IlCallo** [comment]
Is your a JS or TS project? :thinking:

`Entrypoint electron-main = electron-main.js` this line seems to say it's JS, but the error is TS

**Comment by faxinwang** [comment]
before upgrade, it was electron-main.js. The [Upgrade Guide on Electron] says that it support ts file now, so I changed it to ts file.

**Comment by faxinwang** [comment]
Previously I can use ts file in the main process by extending the main process webpack config, with electron-main.js being js file.
but after upgrade, the main process cannot process those ts files.

**Comment by faxinwang** [comment]
I have solved it. here is it:

1. remove the "noEmit": true item in the @quasar/app/tsconfig-preset.json.

```json
{
  "compilerOptions": {
      
    // "noEmit": true,
  },
}

2. add "noImplicitAny": false in the tsconfig.js in project root.

```json
{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "baseUrl": ".",
    "noImplicitAny": false,
  }
}
```

**Comment by IlCallo** [comment]
Interesting...
I'll investigate this further, thanks for the workaround in the meantime.
You could actually set `noEmit` as false on your tsconfig instead.
Having to disable `noImplicitAny` too is pretty strange, something is definitely going wrong down there

**Comment by faxinwang** [comment]
`noImplicitAny` is not necessary, but a convenient way to write ts code that allow some variables not typed. It's helpful in some case. But using too much `any` is definitely not a good practice.

**Comment by IlCallo** [comment]
Oh ok, that make sense, but know you're actively opting-out of some advanced TS inference in this way (eg. the one you get on `.call` or `.apply` methods if I recall correctly).

The original problem is only with `noEmit` then

**Comment by rstoenescu** [comment]
@IlCallo any progress with this?

**Comment by faxinwang** [comment]
I think this can be closed.

**Comment by IlCallo** [comment]
@rstoenescu nope, still had no time to investigate, sorry

**Comment by DarkLite1** [comment]
Same issue, it goes away when using `"noEmit" = false` int he `tsconfig.json` file as explained [here](https://stackoverflow.com/questions/49969071/module-build-failed-error-typescript-emitted-no-output-for). But this doesn't seem to be a good solution.

**Comment by IlCallo** [comment]
Fixed by applying `noEmit: false` only on the node version of Quasar webpack chain: https://github.com/quasarframework/quasar/commit/e87b421dd91979c321035ffdd097238799bcfd26

Will be available with next beta release. Also note we'll scaffolding directly TS files based on @DarkLite1 [PR](https://github.com/quasarframework/quasar/pull/8661/files) soon
