### ISSUE TITLE
SVG QImg in QAvatar does not display properly in Firefox

### ISSUE THREAD

**Issue by kpwbo** [quasarframework/quasar#8569]
**Describe the bug**
Putting a QImg with a src that links to an SVG inside a QAvatar does not display the SVG properly in Firefox. In Chrome and Edge, the SVG is displayed properly. Using a PNG instead of an SVG works fine for all three browsers.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/kpwbo/pen/vYyrvVp?editors=101

**To Reproduce**
1. Open the Codepen in Firefox.
2. Notice that only one picture is displayed even though two QAvatars are present.
3. Open the Codepen in Chrome/Edge.
4. Notice that both pictures are displayed.

**Expected behavior**
Both images should be displayed properly on all browsers.

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/5074608/109897066-238bc800-7c60-11eb-919c-5416a6a9cf3b.png)
Chrome/Edge:
![image](https://user-images.githubusercontent.com/5074608/109897120-36060180-7c60-11eb-9b9c-fed24c7a2f15.png)

**Platform (please complete the following information):**
Quasar Version: 1.15.0
@quasar/app Version: 2.1.14
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Windows
Node: 14.15.4
NPM: 6.14.10
Yarn:
Browsers: Firefox.
iOS:
Android:
Electron:

**Comment by craigrileyuk** [comment]
Seems to be related to the height on `<div class="q-img overflow-hidden>`. If you manually set the .q-img to `height:100%` then the SVG renders as well.

**Comment by pdanpdan** [comment]
If the SVG does not have an intrinsic width/height set inside then you need to specify how you want it displayed.

Isn't it very simple to set a `fit` or `full-height` class, or set `ratio` prop on the QImg?
https://codepen.io/pdanpdan/pen/eYBQpev?editors=1010
