### ISSUE TITLE
Tooltip opens on different button when hiding other button

### ISSUE THREAD

**Issue by jippeholwerda** [quasarframework/quasar#8573]
**Describe the bug**
When clicking on a button to enable other buttons, the tooltip of a newly enabled button opens even though there is no mouse-over event on the new button.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jippeh/pen/yLVqLRE

**To Reproduce**
With Firefox:
1. Click on the change button and let the mouse hover over the change button.
2. The tooltip on the cancel button is shown and remains open.

In Chrome, the tooltip on the cancel button is also triggered, but closes again.

**Expected behavior**
I don't expect the tooltip of the cancel button to open.

**Platform (please complete the following information):**
Quasar Version: 1.15.4

**Comment by pdanpdan** [comment]
You don't have `key` props on the buttons and Vue reuses the elements
https://codepen.io/pdanpdan/pen/YzpjPGN?editors=1000
