### ISSUE TITLE
Timeline marker and two-way infinite scroll

### ISSUE THREAD

**Issue by umonaca** [quasarframework/quasar#8577]
**Is your feature request related to a problem? Please describe.**
Suppose that I am making a web app like Twitter. On Twitter, when I expand a tweet, click back button on the browser, I still get to the original location of the infinite scroll. And I can also scroll down and up, like I never have left the infinite scroll. But for my app, I don’t see any components that directly support such feature.

**Describe the solution you'd like**
1. A timeline marker that I can use to jump back to the original location in the infinite scroll.  
2. Support a Twitter-like infinite scroll that the user can scroll and load in both up and down directions.

**Describe alternatives you've considered**
Probably use the scroll observer and implement these two features my self. But I think this feature will be helpful to other Quasar developers

**Comment by pdanpdan** [comment]
See here:
https://github.com/quasarframework/quasar/issues/7782
https://github.com/quasarframework/quasar/issues/7349

If you have the virtual scroll at body level you'll be brought back to the last scroll position on navigation back (with the default vue-router config)

**Comment by pdanpdan** [comment]
Not by itself. But you can store the listing index in deactivate and set it back in activate.

**Comment by umonaca** [comment]
> Not by itself. But you can store the listing index in deactivate and set it back in activate.

Thanks. Besides you should probably add more examples to the QInfiniteScroll document. Pagination is a difficult subject, but most of the methods in the current document lack examples in the document. And you probably want to add a link to Virtual Scroll on the QInfiniteScroll document, since it's hard to find this component.

**Comment by umonaca** [comment]
> See here:
> #7782
> #7349
> 
> If you have the virtual scroll at body level you'll be brought back to the last scroll position on navigation back (with the default vue-router config)

Could you provide an example of "body level"? How do you prevent the `QVirtualScroll` from being destroyed with the default vue-router config?

**Comment by pdanpdan** [comment]
I mean a QVirtualScroll with the scroll-target set to body - see here: https://github.com/quasarframework/quasar/blob/dev/ui/dev/src/pages/components/virtual-scroll-2.vue
