### ISSUE TITLE
[Feature Request]Show/Hide components in Dialog

### ISSUE THREAD

**Issue by saloustrosm** [quasarframework/quasar#858]
Hi,

It would be nice to have the ability to show/hide form components when an event happens to another component.

For example a group of radio buttons (or a toggle) that when changed another component (or more) would be visible or hidden, this way i could show the valid input components regarding the case, maybe a handler available for every component instead for only buttons? i suppose after that, that the button's handler's data object should be only for the visible components.

**Comment by smolinari** [comment]
What is stopping you from creating this yourself?

Scott

**Comment by saloustrosm** [comment]
@smolinari thanks for your answer Scott,

I suppose nothing stops me, i just feel that this is a common case and would be usefull to be supported out of the box (maybe at v0.15) since this conponent is used for user input and is heavily used, for now i will find a solution myself but i just propose something that sounds usefull.

Marios

**Comment by vuchl** [comment]
This is actually pretty solvable when your state is in the form (maybe even vuex) and not the component (and passed down via props). You are right, it's not there out of the box but as I said this is pretty simple so solve on your end.

**Comment by smolinari** [comment]
Thanks Marios.

Can you then suggest how the QDialog component could offer such functionality? 

What I am trying to get at is whether or not this kind of feature belongs in QDialog. 

I personally think that component building/ composition (as is hiding/ showing them) is a userland responsibility. You could theoretically build a component that is standardized for your purposes, which can show/ hide blocks as you wish. But, how you determine that is specialized for you and only you, thus it would be hard to offer such a feature in general. Or put another way, this ability is there for you, but built into the composition of components and manipulating their states.

Scott

**Comment by saloustrosm** [comment]
Thanks both of you for your fast and usefull replies.

Yes, i see your point, the work needed to achieve this in the user side probably does not worth it to iplement something inside Qdialog and still would not have the same flexibility and options, so as Scott says, it is a userland responsibility.

 Thanks again for your time, i will close this request.

**Comment by smolinari** [comment]
BTW!

If you have an idea or suggestion, try to run it through either the [forum](http://forum.quasar-framework.org/). You'll get answers and feedback there for sure and also guidance on if the idea is a good one or not. When you get the proverbial thumbs-up, you can add your suggestion here with a reference to the discussion in the forum and it probably stand a much better chance to not get shot down.  😄 

Scott
