### ISSUE TITLE
Material IO Font are not getting identified while changing folder path through CopyWebPackPlugin 

### ISSUE THREAD

**Issue by jmriyaz84** [quasarframework/quasar#8581]
**Describe the bug**
We want to change folder path of js & css so we achieve that through CopyWebPackPlugin . Now while doing build js & css folders are getting created under my myproject folder like dist/spa/saqr/js/*.js & dist/spa/saqr/css/*.css . But now the application cannot recognize the material io font icons seems like relative path issue.

 
**To Reproduce**
1. Change the minified production folder path through CopyWebPackPlugin  for js & css
2. Run build command , after the open index.html 
3. Then you can recognize material io path are not recognized   

**Expected behavior**
Material Icons should get displayed as before

**Screenshots**
 CopyWebPackPlugin COnfiguration
<img width="445" alt="configuration" src="https://user-images.githubusercontent.com/8514576/110228186-9757fa00-7f18-11eb-8043-70f318026baa.png">

Material Icons Issue
<img width="840" alt="error" src="https://user-images.githubusercontent.com/8514576/110228188-a179f880-7f18-11eb-9315-e7390baad164.png">

**Platform (please complete the following information):**
Quasar Version: 1.1.3 
Quasar mode: SPA 
Tested on: SPA
OS: Windows 10
Node: 12.18.2
NPM: 6.14.5 
Browsers :Chrome 

**Additional context**
**quasar.conf**
module.exports = function(/* ctx */) {
return {
…
extras: [
“roboto-font”, // optional, you are not bound to it
“material-icons” // optional, you are not bound to it
],
…
build:{
framework: {
iconSet: “material-icons”, // Quasar icon set
lang: “en-us”, // Quasar language pack
config: {},
components: [“QInput”],
importStrategy: “auto”,
// Quasar plugins
plugins: [“AppFullscreen”, “Loading”, “Dialog”, “Notify”]
},
}

**Comment by bazuka5801** [comment]
@jmriyaz84 Why you think this is a bug?
Please, describe additional info.
My opinion:
Quasar build app to some box (index.html + resource files)
You run it everywhere with web server.
I don't know case where I need to change these paths

**Comment by jmriyaz84** [comment]
I changed my build folder structure like /spa/ja/saqr/*.js here saqr is my sub-project name , but when I changed this folder structure quasar's in-built material io icons referring old path, also in quasar documentation it is not clear that how to change material io font relative path .

**Comment by bazuka5801** [comment]
@jmriyaz84 quasar.conf.js have a prop like 'publicPath' I think this is helpful

**Comment by jmriyaz84** [comment]
@bazuka5801  , sorry this is not helpful for us .

**Comment by jmriyaz84** [comment]
Issue got resolved
