### ISSUE TITLE
bug(app): not hide splashscreen in capacitor

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#8582]
**Describe the bug**

@rstoenescu, I waited a very long time for the support of Capacitor V3 on Quasar v1, I decided to write it myself, then I found a bug in Quasar v2

https://github.com/quasarframework/quasar/blob/vue3-work/app/lib/quasar-conf-file.js#L943
Variable 
cfg.__versions._capacitorSplashscreen_
not equal
_capacitor<span class="f2">_**Plugin**_</span>Splashscreen_
https://github.com/quasarframework/quasar/blob/vue3-work/app/lib/quasar-conf-file.js#L936

Expected workflow: close splashscreen after app started.
Actual workflow: only import splashscreen plugin and not hiding splashscreen.

Quasar v2 is so important update, we need test all features completely.

Platform: capacitor
Quasar: 2.X.X+
@quasar/app: 3.X.X+

**Comment by rstoenescu** [comment]
Thanks for both reporting and providing a PR!
This will go into "@quasar/app" 2.0.0-beta.9
