### ISSUE TITLE
Contribution guide: how to test app changes

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#8583]
In `/ui` package devDependency is static version on npm
https://github.com/quasarframework/quasar/blob/vue3-work/ui/package.json#L64

I make like this
```
 "@quasar/app": "../app",
```
but many people don't know about it.
We need add documentation: How to test source change (`/ui`, `/app` and other)
I face to face with this problem when solving upgrade capacitor to v3 on quasar v1, because update depends on /ui /app changes

**Comment by rstoenescu** [comment]
We already have that in docs: https://next.quasar.dev/contribution-guide/contribution-guide
Especially: https://next.quasar.dev/contribution-guide/contribution-guide#contributing-to-the-quasar-ui-source-code
