### ISSUE TITLE
CSS utils bg-* wrong implementation

### ISSUE THREAD

**Issue by EchoCompanyK** [quasarframework/quasar#8587]
The bg-*  utility sets the whole background attribute with the !important flag, which causes any other background definitions (image position size etc.) to be lost.

```
.bg-grey
  background: $grey !important
```

Must set background-color:
```
.bg-grey
  background-color: $grey !important
```

**Comment by rstoenescu** [comment]
Hi,

This was a technical decision to avoid Quasar's CSS growing by 10-20KB and still cover the vast majority of use-cases.
Sorry, but if you have some custom use case you will either have to write your own color classes or overwrite Quasar's. I know it's not what you want to hear.
