### ISSUE TITLE
v-model binding for QRange does not work

### ISSUE THREAD

**Issue by e-tobi** [quasarframework/quasar#8588]
Using v-model binding in QRange to bind to a reactive object does not work. min/max are set from the model values, but the 
model does not update. 
The [doc about QRange](https://next.quasar.dev/vue-components/range#introduction) does use v-model this way and all examples in the doc don't work.

Codepen:

https://codepen.io/etobi/pen/GRNYoKp

The first slider uses normal binding and sets the new values "manually" in the update:modelValue event handler and works as expected. The second slider uses v-model.

Please note, that once you use the second slider, the first one will also not work anymore. It looks like v-model is assigning a new range object instead of just updating the reactive min/max properties of the range object.

Quasar Version:
@quasar/app Version: v2.0.0-beta.8

Quasar mode:
  [X] SPA

Tested on:
  [X] SPA

OS: Debian
Node: v12.20.2
NPM: 7.5.2
Browsers: Firefox, Chromium

**Comment by bazuka5801** [comment]
@e-tobi v-model only supported on Vue2 or Quasar with Webpack (vue-loader)

**Comment by e-tobi** [comment]
@bazuka5801 This is all about Quasar v2 / Vue3. The Quasar v2 docs use `v-model` on QRange to bind to `reactive({min:10, max:30})` which does not even work in the doc samples. I'm not sure if Vue3 is capable to do this at all. I couldn't find any examples where modelValue is an Object and I could not get this working with the `update:modelValue` event.

**Comment by rstoenescu** [comment]
Use `ref` instead of `reactive` and it'll work.
Will fix docs for next deployment.

**Comment by rstoenescu** [comment]
Also, v-model is supported on Vue 2 and Vue 3.

**Comment by e-tobi** [comment]
Yes, ref() works here. Thanks! I was afraid that with ref() I would loose reactivity of the inner min/max properties, but it seems this is not the case, even if I don't know why.

**Comment by bazuka5801** [comment]
@rstoenescu what the difference ref and reactive?
I see so many docs and cant find this

**Comment by pdanpdan** [comment]
@bazuka5801 can you link to the vue 3 docs or the Google search where you haven't found the difference explained? :D

**Comment by e-tobi** [comment]
I just stumbled upon [this StackOverflow answer from Chris Hayes](https://stackoverflow.com/questions/61452458/ref-vs-reactive-in-vue-3/65262638#65262638), which is a nice summary of ref vs. reactive. The key point for me was, that ref() actually also uses reactive() internally.

**Comment by bazuka5801** [comment]
@pdanpdan In docs only theoretical about every function, but difference in this situation.
If vue docs have difference explained -> I'm fail
But in vue docs all basic values uses ref and complex objects uses reactive and no difference expected.

**Comment by bazuka5801** [comment]
@e-tobi Thanx!
