### ISSUE TITLE
QBtnToggle add active class

### ISSUE THREAD

**Issue by germanp** [quasarframework/quasar#8591]
There is no easy way to customize the styles of the active button under QBtnToggle. The only way is to change the toggle-color or toggle-color-text variables but that only change the color but only that. Also there is no way to customize using a slot because there is no scope data passed by. 

I think the most straightforward way to fix this is by adding an active class to the corresponding child button.

**Comment by rstoenescu** [comment]
toggle-color and toggle-text-color
