### ISSUE TITLE
q-btn-dropdown outline split render issue

### ISSUE THREAD

**Issue by moander** [quasarframework/quasar#8594]
**Describe the bug**
There is a space in the solid border when combining `split` and `outline`

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/moanderpen/pen/yLVQOmL?editors=101

**To Reproduce**
Add `outline` and `split` to `q-btn-dropdown`

**Expected behavior**
Solid border without whitespace

**Screenshots**
![image](https://user-images.githubusercontent.com/380191/110505627-a0a2bb80-80fe-11eb-805e-3b83defaf658.png)

**Platform (please complete the following information):**
Quasar Version: v1.15.5
@quasar/app Version: v2.2.1
Quasar mode:
  [X ] SPA

**Comment by rstoenescu** [comment]
That's the separator right there. But good point. Thanks for reporting this bug.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.6.
