### ISSUE TITLE
@quasar/cli commands failures should exit with code 1

### ISSUE THREAD

**Issue by mkungla** [quasarframework/quasar#8597]
**Describe the bug**
Running `@quasar/app` commands outside of project root should exit with correct exit status

**To Reproduce**
1. `cd  /tmp`
2. `quasar dev`
2. `echo $?`
3. Outputs `0`

**Expected behavior**
Outputs `1`

**Platform (please complete the following information):**
Quasar Version:
@quasar/cli Version: 1.1.3

https://github.com/quasarframework/quasar/blob/afc678361e367746e15c9da246a7753a4846df3d/cli/bin/quasar#L84-L91

So ` process.exit(1)` should be called when that failure condition is met.

also it would make sense to check that if in project root, but just missing deps 

e.g.

```
if (root && !localFile) {
  console.log(`${chalk.red(`Error`)} missing @quasar/app install it "npm i -S @quasar/app"`)
  process.exit(1)
}
```

**Comment by rstoenescu** [comment]
Will be available in "@quasar/cli" v1.1.4
