### ISSUE TITLE
QTooltip could have an anchor on another QTooltip to avoid overlapping

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#8598]
**Is your feature request related to a problem? Please describe.**
We have several places where we use QTooltip to display a name and another one for insufficient rights for example. In this case, the insufficient rights cannot be put at the same place than the other tooltip due to overlapping and thus, avoiding it right now is a pain or ugly (one up one down).

**Describe the solution you'd like**
I would like to be able to attach a QTooltip to another QTooltip like we do on other component (we could use the "target" attribute to make it appear if needed) so they never overlap and they appear nicely for users.

**Describe alternatives you've considered**
Several alternatives have been considered, one up and one down to the location where tooltip is issued or put everything in the same tooltip, or dynamically change offset of the second tooltip (imagine if there is a third, I hope not x_x)

**Comment by pdanpdan** [comment]
Please add a codepen showing a case like this so we can play with it.

**Comment by Medhyena** [comment]
Hello, sorry for the wait. Here is an example : https://codepen.io/medhyena/pen/poRoXVg both tooltips are linked to the button

**Comment by pdanpdan** [comment]
I'm sorry but I don't think it's a good idea to anchor one tooltip on another.
You can try something like this: https://codepen.io/pdanpdan/pen/mdREgGq?editors=1010

**Comment by pdanpdan** [comment]
I'll close this - it would be too error prone to anchor some tooltip on another one. Either use offset or combine them in the same tooltip. Sorry.
