### ISSUE TITLE
[Feature Request]Select allow create new items

### ISSUE THREAD

**Issue by dsonet** [quasarframework/quasar#860]
Like this component, can create new item when there is no matched.(It's very useful when we don't have the option matched then allow user to create new one)
Scroll down, see the Create new items section:
http://element.eleme.io/#/en-US/component/select

Also like the functionalities of  Remote Search, Option filtering.( You can see that on the same page above)

**Comment by rstoenescu** [comment]
Will do.

**Comment by dsonet** [comment]
@rstoenescu So cool. Thanks for your great work.

**Comment by rstoenescu** [comment]
Done for future v1.0.
