### ISSUE TITLE
QInput with v-model.trim: Cursor jumps to end

### ISSUE THREAD

**Issue by FabShaw** [quasarframework/quasar#8600]
Describe the bug
Hey guys, I have a problem with q-input:
When I use a q-input with v-model.trim, the cursor jumps to the end of the input field under certain circumstances, even though I don't want it to.

Codepen/jsFiddle/Codesandbox (required)
https://codepen.io/FabShaw/pen/GRNwzMv

To Reproduce
Open the Codepen-Snippet: 
1. enter a text in the QInput text field
2. put a space at the end of the text
3. place the cursor (with the mouse) at a position in the middle of the previously entered text
4. type a letter
5. the cursor will automatically jump to the end of the text field
Note: The native input field in the codepen does not behave like this.

Expected behavior
The cursor should not automatically jump to the end of the input field

Screenshots
Platform (please complete the following information):
OS: Windows 10
Node: 10.22
NPM: 6.14.6
Yarn: -
Browsers: Current Chrome, Firefox, Edge
iOS: -
Android: -
Electron: -

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.6.
