### ISSUE TITLE
QTabs in a keep-alive panel render justified then revert

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8601]
**Describe the bug**
When defining a complex dialog based on tabs with subtabs, the redering of the subtabs visually glitches if using the `keep-alive` directive on the parent panel.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/zYoMbxq?editors=1010

**To Reproduce**
1. Go to codepen
2. Click on the Dialog button to open the dialog
3. Click on the 'No subtabs' tab
4. Click back on the 'Subtabs' tab
5. As the Subtabs content is rendered, the subtabs are initially justified, then revert back to non-justified, causing a visual glitch

**Expected behavior**
The subtabs would be rendered correctly on second activation of the main tab.

**Platform (please complete the following information):**
Quasar Version:  v1.15.4 

**Additional context**
Omitting the `keep-alive` directive fixes the glitch, but is needed in my particular app case to maintain some complex state under each tab.

**Comment by pdanpdan** [comment]
Sorry, I cannot reproduce.
Try to determine the exact device, browser and **dialog width** where it can be reproduced.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.6.
