### ISSUE TITLE
Remove inline styling from QTabPanels

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8602]
**Is your feature request related to a problem? Please describe.**
Using QTabPanels deviates from main app styling unless you remember to reapply background colour to the component.

**Describe the solution you'd like**
That QTabPanels would just inherit the background colour / style of the containing element and not have inline colour

**Describe alternatives you've considered**
Trying to remember to reapply styling :)

**Additional context**
I'm not 100% certain _why_ this component in particular doesn't inherit—perhaps there's a good reason, but if not, it would be much more convenient if it didn't include `background: #fff;`

**Comment by rstoenescu** [comment]
Hi,

Sorry but changing the current behaviour would be a breaking change and so definitely not what we want.
