### ISSUE TITLE
quasar.conf.js export final webpack configuration for external tools

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8608]
**Is your feature request related to a problem? Please describe.**
Using editor linting tools (ESLint) with plugins such as `eslint-plugin-import` do not understand the Quasar generated aliases such as in `import Thing from 'components/Thing'` and report that import as not found. Since they are outside the `quasar dev` context, there's no obvious way to integrate them.

**Describe the solution you'd like**
A simple method to 'export' or otherwise integrate external linting with the Quasar webpack configuration.

**Describe alternatives you've considered**
I've been manually adding the following to quasar.conf.js (for every project):
```
const fs = require('fs')
const util = require('util')

...
      extendWebpack (cfg) {
      .
      .
      .
        fs.writeFileSync('./webpack.config.js', `module.exports = {
          resolve: ${util.inspect(cfg.resolve, { showHidden: false, compact: false, depth: null })}
        }`)
      }
```

It does seem to work, but is clunky, _must_ come at the end of that function, and requires significant edits of the configuration for every project.

**Additional context**
Perhaps that _is_ the only way to do this, and for that plugin the whole webpack configuration is not needed (hence only exporting the `resolve` property. But it would be great if there was a setting under `build: {}` something like:
```
build: {
  exportWebpack: 'webpack.config.js'
}
```
to streamline / simplify.

**Comment by pdanpdan** [comment]
Make sure you have the aliases set up in `jsconfig.json`:

```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      .... // default aliases
      "fancy_in_src/*": [
        "src/fancy_in_src/*"
      ],
      "fancy_in_root/*": [
        "fancy_in_root/*"
      ]
    }
  },
  ....
}
```

and also in `quasar.conf.js`

```js
extendWebpack(cfg) {
  .....

  cfg.resolve.alias = {
    ...cfg.resolve.alias, // This adds the existing alias

    // Add your own alias like this
    fancy_in_src: path.resolve(__dirname, './src/fancy_in_src'),
    fancy_in_root: path.resolve(__dirname, './fancy_in_root')
  };
},
```

If it's not enough check here: https://arunmichaeldsouza.com/blog/aliasing-module-paths-in-node-js

**Comment by dsl101** [comment]
I think it's a misunderstanding. The problem is _not_ with ESLint as part of the quasar build process (in fact, I don't usually enable that, as I have lots of things flagged as errors in eslintrc such as console.log that would prevent compilation). I use sublimelint to highlight such things in SublimeText, and _that's_ where it is unable to understand those aliases. ESLint is being run by the editor completely independently of the quasar context, and so cannot read the config.

With that hacky export code, and adding both `eslint-plugin-import` and `eslint-import-resolver-webpack` to the dev environment, ESLint is now able to check that those imports are valid, but only after quasar writes the config on the first build. Every change causes the quasar build process to spit out the latest webpack config, which the external ESLint can then use. Obviously, most of the time, this hasn't changed, but if a new alias is added, it is then picked up.

**Comment by rstoenescu** [comment]
Sorry, but exporting the final webpack config is simply not an option for us. It requires a hell of a lot of work and I even doubt it'll work correctly with IDEs in the end.
