### ISSUE TITLE
About Carousel min-height.

### ISSUE THREAD

**Issue by Bangood** [quasarframework/quasar#861]
### Software version

Quasar: v0.14.2
OS: windows10
Node:v7.10.0
NPM:v4.2.0
Browsers:60.0.3080.5

### Description
When I use `Carousel` as my image gallery, I meet an unfriendly experience that the Carousel has a `min-height:200px` style.

How can i remove it easily.

**Comment by rstoenescu** [comment]
Hi, configure `$slider-min-height` Stylus variable.
