### ISSUE TITLE
"Added non-passive event listener to a scroll-blocking 'touchstart' event" console warning when using QBtn component in Quasar v.2 

### ISSUE THREAD

**Issue by fomalhaut79** [quasarframework/quasar#8610]
**Describe the bug**
"Added non-passive event listener to a scroll-blocking 'touchstart' event" warning in the console when using QBtn component in Quasar v.2 

1. Open https://next.quasar.dev/vue-components/button in Chrome
2. Warnings will apear in the console
<img width="1242" alt="Screen Shot 2021-03-11 at 12 10 25 PM" src="https://user-images.githubusercontent.com/16054779/110826926-8f26f400-8263-11eb-99d8-0eaf43c8964d.png">

**Expected behavior**
1. Open https://quasar.dev/vue-components/button in Chrome
2. No warnings in the console
<img width="1240" alt="Screen Shot 2021-03-11 at 12 10 42 PM" src="https://user-images.githubusercontent.com/16054779/110827119-c0072900-8263-11eb-9b18-43e5e02b5ffb.png">

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: v. 2.0.0-beta9
OS: macOS Mojave
Browser: Chrome Version 89

**Comment by metalsadman** [comment]
I'm not getting the warnings Chrome `89.0.4389.82`.

**Comment by fomalhaut79** [comment]
@metalsadman I'm getting the  same warnings in Chrome 85 on Windows. To see them make sure Verbose level is enabled in the console:
<img width="164" alt="Screen Shot 2021-03-12 at 9 01 07 AM" src="https://user-images.githubusercontent.com/16054779/110950191-87be2400-8311-11eb-86d1-e0cfc5b24abc.png">

**Comment by metalsadman** [comment]
> @metalsadman I'm getting the same warnings in Chrome 85 on Windows. To see them make sure Verbose level is enabled in the console:
> <img alt="Screen Shot 2021-03-12 at 9 01 07 AM" width="164" src="https://user-images.githubusercontent.com/16054779/110950191-87be2400-8311-11eb-86d1-e0cfc5b24abc.png">

still not getting the same warning as yours, mine is from `fastclick`.
![image](https://user-images.githubusercontent.com/31038838/111018571-94677880-83f4-11eb-914c-df070d054d26.png)

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.10.
