### ISSUE TITLE
reactive-rules validations are not triggered anymore after a brief "disable" of the form component

### ISSUE THREAD

**Issue by CamilleDrapier** [quasarframework/quasar#8611]
**Describe the bug**

If a Form component has some "reactive" validations that are run on back-end and for which the result are retrieved in the submit response, we should be able to display these results, even if the form fields where disabled during the submit.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/CamilleDrapier/pen/OJbdVyR

<details>
<summary>Single Component version</summary>

```
<template lang="pug">
q-form(
  @submit="onSubmit"
  @reset="onReset"
  class="q-gutter-md"
  ref="aForm"
)
  q-input(
    filled
    v-model="name"
    label="Your name *"
    hint="Name"
    reactive-rules
    :disable="disabled"
    :rules="rules"
  )
  div
    q-btn(label="Submit" type="submit" color="primary")
    q-btn(label="Reset" type="reset")
</template>

<script>

export default {
  name: 'TestForm',
  data() {
    return {
      name: null,
      disabled: false,
      apiError: null,
      apiErrorValue: null,
    };
  },

  computed: {
    rules() {
      const result = [
        (val) => (val && val.length > 0) || 'Please type something',
      ];
      if (this.apiError) {
        result.push(this.apiValidation);
      }
      return result;
    },
  },

  methods: {
    onSubmit() {
      this.disabled = true;
      setTimeout(() => {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          icon: 'warning',
          message: 'Some error',
        });
        this.apiError = 'Invalid Name';
        this.apiErrorValue = this.name;
        this.disabled = false;
        // this.$refs.aForm.validate();
        // setTimeout(() => {
        //   this.$refs.aForm.validate();
        // }, 500);
        // this.$nextTick(() => this.$refs.aForm.validate());
      }, 500);
    },

    onReset() {
      this.disabled = false;
      this.apiError = null;
      this.name = null;
      this.apiErrorValue = null;
    },

    apiValidation() {
      return !(this.apiError && this.apiErrorValue === this.name) || `${this.apiError}: ${this.apiErrorValue}`;
    },
  },
};
</script>
``` 

</details>

NB: I'm not entirely sure that the `rules` should be handled/written the way they are in this example, in real-life we are using `vuelidate` that seems to give reactiveness for validation rule definitions out of the box.

**To Reproduce**
1. Type anything in the input
2. Click on 'Submit'
3. No error is shown in/below the input field when the submit is finished (error notification appears in the middle of the screen).

**Expected behavior**

- The validation should be triggered and the error should show in/below the input field.

In provided example, the expect behavior can be achieved by either:
  
  - not disabling the input field.
  - calling a `.validate()` on the form either after a small timeout or a "$nextTick", calling it directly does not work.

#### details

What I think I am expecting here, is that if a component has `reactive-rules` (and depending on the value of lazy-rules also?) and it is being enabled again, it should probably run the validation rules? Would that be reasonable or out of the scope of the support of reactive-rules? If there is a simpler way to do this I would be happy to hear about that as an alternative as well. :bow: 

**Platform (please complete the following information):**
Quasar Version: 1.15.5

**Additional context**

This used to work until version `1.15.3`, so I think that https://github.com/quasarframework/quasar/pull/8485 introduced the behavior change.

**Comment by pdanpdan** [comment]
It's related to this one: https://github.com/quasarframework/quasar/pull/8485#discussion_r577721330

**Comment by CamilleDrapier** [comment]
Oh I see thank you.
Does that mean that we should take care of running the validation within our submit on the next tick for this use-case?
Or do you think that the changes you made in the related PR (thanks for taking care of this! :bow:) can solve the problem I have been having?

**Comment by pdanpdan** [comment]
The changes in the PR:
- do not change the dirty status of a field when it is disabled
- revalidate the field when it is enabled if it was dirty
- reset the validation status of a field even if it is disabled

So I think it would also cover your use case.

**Comment by rstoenescu** [comment]
Fix will be available in next Qv2 and Qv1 versions.
