### ISSUE TITLE
Platform Detection with SSR + cache proxy result in bad body classes

### ISSUE THREAD

**Issue by laekem34** [quasarframework/quasar#8612]
Hello ! 

I noticed that when using a proxy to cache its application in SSR mode.
The Platform object returned to all visitors requesting a cached page is the one of the first to have requested it.

For example if an ios first calls an url, the body will have the following classes: `mobile platform-ios`. And for all other calls from other devices, the body will have these same classes.

Would there be a solution to force creation of client side plaform object in ssr mode or update Platform object via method

Maybe a method like:
`Platform.refresh()`
or a config in quasar.conf:
```
framework: {
  platform: {
     useClientSideOnSsr: true 
  }
}
```

Thanks you!

**Comment by pdanpdan** [comment]
Common :)
How would you expect a pre-rendered page that is cached to to delivered changed for each client.
You may try playing with the `VARY` headers.

**Comment by laekem34** [comment]
I understand what you say, but It's not that I was asking,

I wanted to know if it was possible to have an option to refresh or force the detection of the platform on the client side in the case of a cache system where a detecting the platform on the server side would not make sense .

As there is in SPA mode
