### ISSUE TITLE
QPagination with input is not working

### ISSUE THREAD

**Issue by pratik227** [quasarframework/quasar#8614]
**Describe the bug**

QPagination with input is not working. Not reflecting placeholder and event's are also not working.

**Codepen/jsFiddle/Codesandbox**

https://codepen.io/Pratik__007/pen/dyOaOaM

**To Reproduce**

1. Go to 'https://next.quasar.dev/vue-components/pagination#with-input'
2. Click on the input and try to enter the value it's not working on enter.
3. Also Placeholder is not reflecting

**Expected behavior**

It should reflect the placeholder and also needs to work on the input value.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.10
