### ISSUE TITLE
QTooltip 'mobile'

### ISSUE THREAD

**Issue by florin-rotaru** [quasarframework/quasar#8615]
**Describe the bug**
On a mobile, holding / tap for a short time will trigger the tooltip but however if the page content doesn't require scroll the tooltip will remain open with no options to dismiss it (other than refresh page).

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/florin-rotaru/pen/QWGpJPV](url)

**To Reproduce**
1. Open codepen url
2. Open browser developer tools
3. Toggle device toolbar
4. Pick a mobile from the list (ex: IPhone X)
5. **Important!** Refresh the page
6. Hold AAAAA button until tooltip will show up
7. Tap BBBBB button too
8. Try other actions like scroll / tab arround

**Expected behavior**
Tooltip should disappear.

**Screenshots**
![chrome-capture](https://user-images.githubusercontent.com/54668297/110963475-c6c49780-835a-11eb-9682-f697bbb9a9b8.gif)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  [ X] SPA
Tested on:
  [X ] SPA
OS:
iOS: x
Android: x

**Comment by hawkeye64** [comment]
I found this to also be true on an actual mobile (Pixel 4a using Chrome)
Probably need a "click outside" for the tooltip to get dismissed.

**Comment by martinfruehmorgen** [comment]
Hello,
are there any news on this? This affects every tooltip in mobile view...

Thanks!
Martin

**Comment by rstoenescu** [comment]
Improvement will be available in Quasar v2.0.0-beta.12.
