### ISSUE TITLE
Clicking on q-item in q-menu throws error with q-dialog (Capacitor)

### ISSUE THREAD

**Issue by accron-1** [quasarframework/quasar#8616]
**Describe the bug**
In Capacitor (Android): when clicking on a `q-item` and the `q-item` opens a `dialog`, a Quasar error occurs (see screenshots).
Sample markup:
```html
<q-menu>
<q-list style="min-width: 150px">
	<q-item
		@click="openDialog()"
		clickable
		v-close-popup
	>
		<q-item-section>Edit routine</q-item-section>
	</q-item>
</q-list>
</q-menu>
```
If `openDialog()` does a
```javascript
 $q.dialog({
        title: 'Some alert',
        message: `Test`,
        cancel: true
      })
```
the error occurs.

Without the dialog, I've noticed that the error occurs intermittently.

**Codepen/jsFiddle/Codesandbox (required)**
Not able to reproduce in browser, only in Capacitor apps.

**To Reproduce**
See previous point.

**Expected behavior**
Close the menu without errors.

**Screenshots**
![img1](https://user-images.githubusercontent.com/14213307/110989989-01d2c500-8373-11eb-9301-ba4c6ce14262.png)

![img2](https://user-images.githubusercontent.com/14213307/110990009-07c8a600-8373-11eb-8c2c-0c2e7c786a1a.png)

Demo:
![demo](https://user-images.githubusercontent.com/14213307/111025537-0afc7a00-83e5-11eb-965f-f80a3bcb6b5b.gif)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.9
@quasar/app Version: 3.0.0-beta.9
Quasar mode:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ X ] Capacitor
  [ ] BEX
Tested on:
  [ ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ X ] Capacitor
  [ ] BEX
OS: Ubuntu 20:10
Node: 12.21.0
NPM:  6.14.11
Yarn: --
Browsers: --
iOS: --
Android: emulator
Electron: --

**Additional context**
This bug didn't exist on:
Quasar Version: 2.0.0-beta.7
@quasar/app Version: 3.0.0-beta.7

I just upgraded from those versions and spotted the bug within a couple of minutes, as I'm in the process of rewriting my app from v2 -> v3. As such, I'm constantly monitoring the console for any errors that might occur because of my rewrite.

**Comment by hawkeye64** [comment]
Also verified this is not an issue with desktop app. Not sure why Capacitor is having this issue.

**Comment by rstoenescu** [comment]
Hi,

No matter how much I tried, I could not reproduce. Can you supply a reproduction repo pls?
Also: what version of Capacitor are you using and what Android version

**Comment by accron-1** [comment]
These are the versions I'm currently running:
```
"@capacitor/android": "^2.4.5",
"@capacitor/cli": "^2.4.5",
"@capacitor/core": "^2.4.5",
"quasar": "^2.0.0-beta.10", --> upgraded from beta.9 in my original post
"@quasar/app": "^3.0.0-beta.9",
```

I have only tested it on the emulator so far. Version:
![emulator](https://user-images.githubusercontent.com/14213307/112047450-98f70400-8b4d-11eb-9498-7e89685e1aa3.png)


I'll try to prepare a repo.

**Comment by rstoenescu** [comment]
Yes, a repo (or codesandbox) would help. Thanks.

**Comment by rstoenescu** [comment]
Please supply the required repo (or fork [codesandbox](https://codesandbox.io/s/optimistic-poitras-4t3m3)). We cannot reproduce so we have no way to make any progress with this ticket otherwise.
