### ISSUE TITLE
date change to "years" and "months" not implemented in v2-beta

### ISSUE THREAD

**Issue by ldiebold** [quasarframework/quasar#8617]
**Describe the bug**
In the beta docs, for the [date utility](https://next.quasar.dev/start/upgrade-guide#date-utils), `year` is now `years` and `month` is now `months`.
this change doesn't seem to be reflected in the code.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ldiebold/pen/oNYmdda?editors=1011

**To Reproduce**
1. Go to the code pen
2. notice the old date format works
3. uncomment lines for the new format
4. notice the new format does not work

**Expected behavior**
the `years` and `months` properties should work pluralized, not singular.

**Platform (please complete the following information):**
Quasar Version: ^2.0.0-beta.9
@quasar/app Version: ^3.0.0-beta.9
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Ubuntu 20.04
Yarn: 1.22.5
Browsers: chrome

**Comment by rstoenescu** [comment]
It is implemented. Just a bug in the implementation for "months" (was correctly identifying it but referencing "month" param).
Fix will be available in next beta.
