### ISSUE TITLE
Title of md container not showing up in bold (on FF/Windows10)

### ISSUE THREAD

**Issue by enpasos** [quasarframework/quasar#8618]
**Quasar Context**: v2.0.0-beta9, docs, styling detail on particular browser/os

**Reproduce:** The title in a markdown container - e.g. "Quasar v2 beta" - appears in the same style as normal text in FF 86.0.1 (64-Bit) on Windows 10. 

![grafik](https://user-images.githubusercontent.com/9622808/111022411-ded7fd80-83d2-11eb-844a-48a4a45f3e7e.png)

**Detail:** When turning the font weight slightly up it appears in "bold".

**Comment by rstoenescu** [comment]
Thanks for reporting! Fix will be available on next docs deployment.
