### ISSUE TITLE
Please add placeholder option for $q.dialog()

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#8620]
I want to force a user to type something before deleting an account - perhaps the account's ID, the word "delete" or something else.  As such, it would be very helpful to have a placeholder that shows exactly what needs to be entered before the 'OK' button is enabled.  The existing prompt + validation should handle most of this if a placeholder is added.  

Even better if the placeholder doesn't disappear when they start typing, as it would in a normal form field, but starts grey and turns white/dark (depending on theme) letter by letter as they type.  Once the last character is entered, the OK button should enable.

**Comment by hawkeye64** [comment]
@Daemach It sounds like you are asking for something similar for when you delete a repository on Github. They make it so you have to enter some text (which they give you) and the delete buttton stays disabled until the exact text is entered. Why not use $q.dialog to wrap a component that does this for you?

**Comment by Daemach** [comment]
That is what I'm asking for.  I don't know how to do what you're suggesting.

**Comment by pdanpdan** [comment]
Please read the docs and ask for help on our discord channel or in the forum.

**Comment by Daemach** [comment]
Remind me why I am a Quasar sponsor...

**Comment by rstoenescu** [comment]
Hi @Daemach ,

It's all described here:
* for v1: https://quasar.dev/quasar-plugins/dialog#Invoking-custom-component
* for v2: https://next.quasar.dev/quasar-plugins/dialog#invoking-custom-component

This will allow you to write a dialog with any custom behavior. Having this knowledge under your belt will greatly enhance what you can do with Quasar.
