### ISSUE TITLE
Webpack Config Issue

### ISSUE THREAD

**Issue by jmriyaz84** [quasarframework/quasar#8621]
**Describe the bug**
I want to change my js & css folder name for that I have added following code in quasar.conf.js , it is working fine when I do quasar build , but when I run quasar dev I am getting following error.

 **_App · Chaining SPA Webpack config
(node:4392) UnhandledPromiseRejectionWarning:   Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('mini-css-extract').use(<Plugin>) first._**

**Code**
extendWebpack(cfg) {
        cfg.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /node_modules/
        });
        //For SAQR Folder
        cfg.module.rules.find(_rule =>
          (_rule.test + "").includes("woff")
        ).use[0].options.name = "fonts-saqr/[name].[contenthash:8].[ext]"; 
        //END
      },
      //For SAQR Folder
      chainWebpack(chain) {
        chain.output
          .filename("js-saqr/[contenthash:8].js")
          .chunkFilename("js-saqr/[contenthash:8].js");
        chain
          .plugin("mini-css-extract")
          .tap(args => [{ filename: "css-saqr/[contenthash:8].css" }, ...args]);
      }
      //END

 **To Reproduce**
1. Add the above configuration code in quasar.conf.js to change default folder names.
2. Run quasar dev 
3. The following error is thrown
     (node:4392) UnhandledPromiseRejectionWarning:   Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('mini-css-extract').use(<Plugin>) first._**

**Expected behavior**
Application should be running

**Screenshots**

**Code**
<img width="507" alt="code1" src="https://user-images.githubusercontent.com/8514576/111059078-3b5b1b80-84ac-11eb-95cd-bf617fe950dd.PNG">

**Error**
<img width="955" alt="error1" src="https://user-images.githubusercontent.com/8514576/111059087-401fcf80-84ac-11eb-951d-28c9e29ac1ee.PNG">
<img width="955" alt="error2" src="https://user-images.githubusercontent.com/8514576/111059088-431ac000-84ac-11eb-98a7-f993a70dceb8.PNG">

**Platform (please complete the following information):**
Quasar Version: 1.15.5
@quasar/app Version:2.2.1
Quasar mode: SPA
Tested on: SPA
OS: Windows
Node:12.18.2
NPM:6.14.5 
Browsers: Chrome 

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Put the mini-css-extract behind a flag. `if (ctx.prod) { /* tap into mini-css-extract */ }`
It's only used in production.

**Comment by jmriyaz84** [comment]
> Hi,
> 
> Put the mini-css-extract behind a flag. `if (ctx.prod) { /* tap into mini-css-extract */ }`
> It's only used in production.

Thanks it is solved now
