### ISSUE TITLE
QPageScroller reverse prop not affect scroll-offset

### ISSUE THREAD

**Issue by ali4533** [quasarframework/quasar#8625]
**Describe the bug**
In QPageScroller , when use reverse prop, scroll-offset didn't measured from the Bottom (even in your example [here](https://quasar.dev/layout/page-scroller#Reverse).)

**Codepen/jsFiddle/Codesandbox (required)**
I think no need sandbox. 😅 in your example not worked too : https://quasar.dev/layout/page-scroller#Reverse

**To Reproduce**
1. Go to 'https://quasar.dev/layout/page-scroller#Reverse'
2. Click on 'page scroller button'
3. Scroll up about 50px ( scroll-offset is 20 )
4. Where is Page Scroller Button? 

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 1.9.6
Quasar mode:
  [ ] SPA
  [ x] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ ] SPA
  [ x] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Windows 10
Node: v10.16.3
NPM: 6.9.0
Yarn:
Browsers: Google Chrome Version 89.0.4389.82 (Official Build) (64-bit)
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.6 (and v2.0.0-beta.10).
