### ISSUE TITLE
Transition not working

### ISSUE THREAD

**Issue by SDesya74** [quasarframework/quasar#8627]
Transitions not working when I clicking on "Trigger" button in docs (https://next.quasar.dev/options/transitions#introduction)

When i tried to create animated routing in my project I noticed that transition not working in my project too.

Steps to reproduce the behavior click on "Trigger" button in docs (https://next.quasar.dev/options/transitions#introduction)
![image](https://user-images.githubusercontent.com/41489405/111176187-28cf0800-85ba-11eb-9806-ddf7dec4616d.png)

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. The example uses QImg which no longer supports the transitions. Will update with a proper example.
However, the transitions described do work in Quasar v2 for all the components that support them (example: QMenu etc etc).

**Comment by rstoenescu** [comment]
Fixed example will be available on next deployment.
