### ISSUE TITLE
Add CSS to remove the underline?

### ISSUE THREAD

**Issue by aprilahijriyan** [quasarframework/quasar#8631]
I think it's better if in quasar add CSS class to remove the underline in the anchor tag.
For reference: https://www.geeksforgeeks.org/how-to-remove-underline-for-anchors-tag-using-css/
Maybe it's called a `no-underline` ?

**Comment by pdanpdan** [comment]
It is not recommended to not have a visual indicator or links, and the styling to show them is very dependant on what you want.
Also it's a one line class you can do as you like.

**Comment by aprilahijriyan** [comment]
I think it would be nice to have this added, and also that it is "optional" depending on the user.  🤔

**Comment by aprilahijriyan** [comment]
And also the quasar document is very good, this makes it easier to find than searching on google or others.
