### ISSUE TITLE
Provide/Inject with custom dialog components doesn't work

### ISSUE THREAD

**Issue by tiagoskaneta** [quasarframework/quasar#8633]
**Describe the bug**
When using the Dialog plugin to invoke a custom component, the `provide/inject` mechanism doesn't seem to be working as expected when the provide is not done in the `app` level.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/tiagoskaneta/pen/RwoOdzg

**To Reproduce**
1. Use `provide` in the setup of a parent component
2. Open a dialog with a custom component
3. Try to `inject` in the custom component
4. Get undefined

**Expected behavior**
The value should be correctly injected into the component.

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.9
@quasar/app Version: 3.0.0-beta.9
Quasar mode:
  [ x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX

**Additional context**
In Quasar v1, the `parent` prop was used to define the parent component. As this doesn't exist anymore in Quasar v2, is the expected behavior that `provide/inject` doesn't work? In which case, is there any workaround except passing it by prop?

**Comment by rstoenescu** [comment]
Hi,

This is a limitation. If you need something just inject it into the component that's calling the Dialog and supply it through componentProperties.
