### ISSUE TITLE
QInput placeholder is not reactive

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#8637]
**Describe the bug**
q-input placeholder is not reactive.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/eduardodgarciac/pen/vYywVNa

**Expected behavior**
q-input placeholder should be reactive

**Platform (please complete the following information):**
Quasar Version: Quasar v2.0.0-beta.9
@quasar/app Version: v3.0.0-beta.9
Quasar mode:
  [ x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX

**Comment by metalsadman** [comment]
@eduardodgarciac looks like it's already fixed in https://github.com/quasarframework/quasar/commit/1c8b2c98acb83f29b21ae8ea192217316ad5d040 just awaiting release.
