### ISSUE TITLE
error "fs.readFileSync is not a function" after upgrade to quasar v2.

### ISSUE THREAD

**Issue by faxinwang** [quasarframework/quasar#8639]
**Describe the bug**
I'm using the electron mode. After upgrading to quasar v2, when I `quasar dev -m electron` starting up the project, it report 
"fs.readFileSync is not a function" in the devtool console tab. The error message is from `node_modules\electron\index.js` :
```javascript
var fs = require('fs')
var path = require('path')

var pathFile = path.join(__dirname, 'path.txt')

function getElectronPath () {
  if (fs.existsSync(pathFile)) {
    var executablePath = fs.readFileSync(pathFile, 'utf-8')     //Here 
    if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
      return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath)
    }
    return path.join(__dirname, 'dist', executablePath)
  } else {
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  }
}

module.exports = getElectronPath()
```
I guess that may be it is because of the contextIsolation is enabled so that it cann't access to nodejs API. But why this script should be packed into vender.js and run in the browser. when I add some console.log() to `node_modules\electron\index.js`, the hot module replacement would be triggered.

I use quasar cli to create a new quasar v2 project and run `quasar dev -m electron`, there is no such error as above. And
when I add some console.log() to `node_modules\electron\index.js`, the hot module replacement did not be triggered.

I delete node_modules and .quasar folders and install them again, the error still exists. I don't know where is the problem.
I have been stuck for days. help me please...

Note that there is no additional webpack config for electron in the quasar.conf.js

**Expected behavior**
The same as a newly create quasar v2 project, the `node_modules\electron\index.js` script should not packed into vendor.js file to run in the browser.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:  2.0.0-beta.9
@quasar/app Version: 3.0.0-beta.9
Quasar mode: 
  [x] SPA
  [x] Electron
OS: window10
Node:  v12.18.4
NPM:  6.14.9
Yarn: 1.22.5
Electron: 11.3.0

**Comment by rstoenescu** [comment]
Hi,

The whole "issue" that you are experiencing is due to an Electron upstream breaking change.

As per the [Electron upgrade](https://next.quasar.dev/quasar-cli/developing-electron-apps/electron-upgrade-guide) page (more specifically the renderer thread [section](https://next.quasar.dev/quasar-cli/developing-electron-apps/electron-upgrade-guide#renderer-thread-src-):

> **Warning!**
> You will need to transfer all the Node.js stuff away from your renderer thread (the UI code from /src) and into the preload script. Provide the same functionality through the contextBridge as seen in the preload script section above.

The electron preload file is described [here](https://next.quasar.dev/quasar-cli/developing-electron-apps/electron-upgrade-guide#the-electron-preload-js-file).

Make sure that you have latest electron also (not mandatory, but recommended).

**Comment by faxinwang** [comment]
I do have a preload scritp that transfer all the necessary functionality to the renderer process!

**Comment by faxinwang** [comment]
The problem is why `node_modules\electron\index.js` packed into renderer process and run in the browser, while in a newly create v2 project, it do not packed into the renderer process code.

**Comment by rstoenescu** [comment]
Then it means that in your preload script you are exposing the electron instance itself, or some of it? This is a no-go. Expose methods that interact with the electron instance in the preload script itself. Also make sure that the electron-main.js file is configured correctly (check a newly created v2 project for its content).

The solution depends on a lot of stuff in your project, but we don't have access to it so we're trying to help you blindly which is not efficient. And we're currently under heavy load at the moment anyway. Please try to use our chat (https://chat.quasar.dev) or forum (https://forum.quasar.dev) to get someone in the community to help you.

**Comment by faxinwang** [comment]
finally I find the problem. I forget that I have `import {shell} from 'electron' ` in my renderer process, which should be exposed through preload script. My fault!

**Comment by rstoenescu** [comment]
No prob. Glad that u figured it out!
