### ISSUE TITLE
Model window ( including dialogue ) open and right side scroll bar of browser disappears 

### ISSUE THREAD

**Issue by bujji1** [quasarframework/quasar#864]
**Software version**
Quasar: 0.14.2

This is not exactly an issue but distracting the user . When I open a dialogue window ( any model ) the browser right side scroll bar disappears and so the contents behind the model window ( the parent window contents )  are moving right side and when we close the model the scroll bar again comes up and the content are moving to the left side . So if I have really good content the content moving right and left is really distracting .

You can try this on the below link . Open it and reduce the reduce the browser size until you get right side scroll bar and click on any dialogue and you will see the problem I am talking 
http://quasar-framework.org/quasar-play/android/index.html#/showcase/popups/dialog

This was not the case in our old version :)

Thank You

**Comment by rstoenescu** [comment]
Yes, this can be improved. Will do.

**Comment by rstoenescu** [comment]
The main reason for this is for user to not be able to scroll the background (the page underneath the Modal), since the Modal has full attention of user.

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.3.

**Comment by alexandesigner** [comment]
https://github.com/quasarframework/quasar/commit/035be323b90782f5784fc559e491cd9bf3c36fd3#commitcomment-25015800
