### ISSUE TITLE
Ability to simply number QSteps

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8640]
**Is your feature request related to a problem? Please describe.**
It seems really difficult to simply _number_ the steps in QStepper. Changing the icon to show active / inactive / error are all catered for, but it seems you can only _number_ the steps using `prefix`, and that only applies when not active.

**Describe the solution you'd like**
The ability to specify something like `prefix-always`. This would always display the prefix string for every state of the QStep.

**Describe alternatives you've considered**
Perhaps `icon`, (and maybe `active-icon`, `error-icon`, and `done-icon`) could detect being passed a number, to avoid creating an additional prop? Then it could be possible to use:
```
:icon="1"
```
But that would not account for the case where the steps should be labelled 'A', 'B', etc.

**Additional context**
This would be really useful in Quasar v1 as well, but for this specific project I'm using v2

**Comment by mfiot-rm** [comment]
For a relatively easy work around - you could do achieve this effect in CSS with the [counter method](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters). 

I've made an example [here](https://codepen.io/mdf96/pen/rNjaZNm). You can remove the "upper-alpha" in the CSS counter to display numbers and you can initialize the counter with the reset. I also removed the icons to make it clearer. 

Maybe someone else knows a better way, I feel like there should be a slot for it... I see the navigation slot, but there's not much documentation on it.
 
I agree it feels like it should just be an included feature - editing that step navigation come up in my own projects multiple times. However I would argue an additional prop would make things clearer and avoid type errors.

**Comment by dsl101** [comment]
Thanks @mfiot-rm that's really helpful as a workaround. I agree, hopefully it can become a simple prop / setting.

**Comment by Evertvdw** [comment]
I created a PR that should fix this issue: #10671

**Comment by rstoenescu** [comment]
Feature will be available in Quasar v2.5.5.
Use `done-icon="none" active-icon="none" error-icon="none"` and your prefix.

**Comment by CamilleDrapier** [comment]
Thank you very much for adding this issue/feature :heart_eyes: 

Sorry for commenting on a closed issue, please let me know if you would prefer having a dedicated issue for this. Maybe my understanding is odd/wrong, but I feel the documentation for this might be a bit difficult to understand.

According to https://github.com/quasarframework/quasar/blob/quasar-v2.5.5/ui/src/components/stepper/QStepper.json#L55-L81 and https://github.com/quasarframework/quasar/blob/quasar-v2.5.5/ui/src/components/stepper/QStep.json#L46-L72 adding `done-icon="none" active-icon="none" error-icon="none"` should work on both the stepper and the step, but apparently, according to this example I made, it only works for stepper: https://codepen.io/camilledrapier-the-flexboxer/pen/PoOQdLa?editors=1010

Should this be able to be overwritten at the step level, or is it just a matter of removing that part of the step documentation?

**Comment by Levyks** [comment]
> Thank you very much for adding this issue/feature 😍
> 
> Sorry for commenting on a closed issue, please let me know if you would prefer having a dedicated issue for this. Maybe my understanding is odd/wrong, but I feel the documentation for this might be a bit difficult to understand.
> 
> According to https://github.com/quasarframework/quasar/blob/quasar-v2.5.5/ui/src/components/stepper/QStepper.json#L55-L81 and https://github.com/quasarframework/quasar/blob/quasar-v2.5.5/ui/src/components/stepper/QStep.json#L46-L72 adding `done-icon="none" active-icon="none" error-icon="none"` should work on both the stepper and the step, but apparently, according to this example I made, it only works for stepper: https://codepen.io/camilledrapier-the-flexboxer/pen/PoOQdLa?editors=1010
> 
> Should this be able to be overwritten at the step level, or is it just a matter of removing that part of the step documentation?

I agree with this, I was going crazy here trying to figure out why I couldn't get the prefix to show up in the active step, when I saw your comment, thanks
