### ISSUE TITLE
QInput appears to be missing the `hasError` prop

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8644]
**Describe the bug**
External testing of the built-in `rules` prop using the `hasError` prop doesn't seem to work.

**Codepen/jsFiddle/Codesandbox (required)**
https://next.quasar.dev/vue-components/input#example--form-validation

**To Reproduce**
1. Go to the doc link above
2. Accept the terms but don't fill in the form fields
3. Click Submit
4. See the invalid form submitted

**Expected behavior**
The notification would not show, as the line `if (nameRef.value.hasError || ageRef.value.hasError) {` should have caught the invalid form fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/900542/111684749-01c54000-881f-11eb-8b11-2cbcf5a29e4e.png)

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.10
