### ISSUE TITLE
Starter kit doesn't build

### ISSUE THREAD

**Issue by szekelyisz** [quasarframework/quasar#8645]
**Describe the bug**

Trying to build the starter kit, but I get this error:

```
/tmp/qtest/node_modules/@types/webpack-dev-server/index.d.ts
ERROR in /tmp/qtest/node_modules/@types/webpack-dev-server/index.d.ts(17,38):
TS7016: Could not find a declaration file for module 'http-proxy-middleware'. '/tmp/qtest/node_modules/http-proxy-middleware/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/http-proxy-middleware` if it exists or add a new declaration (.d.ts) file containing `declare module 'http-proxy-middleware';`
```

After `yarn add -D @types/http-proxy-middleware@0.19.1`:

```
/tmp/qtest/node_modules/@types/webpack-dev-server/index.d.ts
ERROR in /tmp/qtest/node_modules/@types/webpack-dev-server/index.d.ts(30,53):
TS2694: Namespace '"/tmp/qtest/node_modules/@types/webpack-dev-server/node_modules/http-proxy-middleware/dist/index"' has no exported member 'Config'.
/tmp/qtest/node_modules/@types/webpack-dev-server/index.d.ts
ERROR in /tmp/qtest/node_modules/@types/webpack-dev-server/index.d.ts(36,29):
TS2694: Namespace '"/tmp/qtest/node_modules/@types/webpack-dev-server/node_modules/http-proxy-middleware/dist/index"' has no exported member 'Config'.
```

**To Reproduce**

1. Create a new app, settings as follows:
 ```
? Pick your favorite CSS preprocessor: (can be changed later) Sass
? Pick a Quasar components & directives import strategy: (can be changed later) Auto import
? Check the features needed for your project: ESLint (recommended), TypeScript, Axios
? Pick a component style: Class
? Pick an ESLint preset: Prettier
? Continue to install project dependencies after the project has been created? (recommended) yarn
 ```
2. `quasar build`

**Expected behavior**

Build cleanly

**Platform (please complete the following information):**

Quasar Version: 1.15.5
@quasar/app Version: 2.2.1
Quasar mode:
  [X] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [X] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: Linux
Node: 12.21.0
NPM: N/A
Yarn: 1.22.5
Browsers: Firefox 86.0
iOS: N/A
Android: N/A
Electron: N/A

**Comment by IlCallo** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51420#issuecomment-799529662

Related

**Comment by IlCallo** [comment]
This will be fixed with next q/app release, related PR has already been merged: https://github.com/quasarframework/quasar/pull/8596

**Comment by IlCallo** [comment]
Fix is available in `@quasar/appv2.2.2`
Thanks for reporting!
