### ISSUE TITLE
Typo on BEX Content Hooks page

### ISSUE THREAD

**Issue by thdoan** [quasarframework/quasar#8651]
This doesn't look correct in the sample code:
```
    // Find a .some-class element and add our highlight CSS class.
    const el = document.querySelector('.some-class')
    if (el !== void 0) {
      el.addClass('bex-highlight')
    }
```
Shouldn't it be this instead?
```
    // Find a .some-class element and add our highlight CSS class.
    const el = document.querySelector('.some-class')
    if (el) {
      el.addClass('bex-highlight')
    }
```
On a related note, I don't think `addClass()` is native JavaScript -- adding a class would be `el.classList.add('bex-highlight')`. (If `addClass()` is part of some helper module that is provided by Quasar, then apologies, I wasn't aware of that.)

**Comment by rstoenescu** [comment]
Thanks for reporting.
