### ISSUE TITLE
InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.

### ISSUE THREAD

**Issue by jtlindsey** [quasarframework/quasar#8653]
**Describe the bug**
When you start typing in a input field with type email, you get the following error:
`InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.`

**Codepen/jsFiddle/Codesandbox (required)**
Error is visible in console of original example from project documents 
https://codepen.io/pen/?editors=1011

**To Reproduce**
1. Create email input with `<q-input v-model="email" filled type="email" hint="Email" />`
2. Start typing
3. See error in console

**Expected behavior**
Properly recognize input text as email without error

**Screenshots**
![error_2021-03-21 at 10 00 33](https://user-images.githubusercontent.com/7409277/111907621-8a64fb80-8a2c-11eb-975a-d9a36e92fdfa.gif)

**Platform (please complete the following information):**
Quasar Version: 1.15.6
@quasar/app Version: 2.2.2
Quasar mode:

  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac
Node: 14.16
NPM: 6.14.11
Browsers: Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.7.
