### ISSUE TITLE
Failed to load plugin 'vue-libs' warning

### ISSUE THREAD

**Issue by thdoan** [quasarframework/quasar#8656]
**Describe the bug**
Upon creating a fresh app, the server is throwing a warning whenever a file is updated.

**To Reproduce**
1. `quasar create <myapp>`
2. `cd <myapp>`
3. `quasar dev -m bex`
4. Open `<myapp>/src/App.vue` and save it without making any changes
5. Observe the warning:

```
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Failed to load plugin 'vue-libs' declared in 'node_modules\vue-loader\.eslintrc.js': Cannot find module 'eslint-plugin-vue-libs'
Require stack:
- <myapp>\node_modules\vue-loader\__placeholder__.js
Referenced from: <myapp>\node_modules\vue-loader\.eslintrc.js
```

**Expected behavior**
No "failed to load plugin" warnings should be displayed.

**Platform (please complete the following information):**
Quasar Version: 1.15.7
@quasar/app Version: 2.2.3
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [x] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [x] BEX

OS: Windows 10
Node: 14.16.0
NPM: 7.5.6
Yarn: 1.22.5
Browsers: 89.0.4389.90 (Official Build) (64-bit)
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Fixed in the starter kit.
Please spawn your project again.

Thanks for reporting.
