### ISSUE TITLE
q-tab-panel is kept alive even with keep-alive-exclude

### ISSUE THREAD

**Issue by ansonkan** [quasarframework/quasar#8657]
**Describe the bug**
keep-alive-exclude does not exclude q-tab-panel from being keep-alive.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/blissful-haslett-eux51?file=/src/pages/Index.vue

**To Reproduce**
1. Go to 'MOVIES' tab
2. Click on 'MOVIES COUNTER: 0' button then the counter is increased
3. Click on another tab then click back to the 'MOVIES' tab
4. The Movies button counter is still remain the same

**Expected behavior**
Because keep-alive-exclude="movies" is defined, the 'MOVIES' tab should not be kept alive and the Movies counter should be 0 at Step 4.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 1.15.7
@quasar/app Version: ^2.0.0
Quasar mode: SPA

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS Big Sur 11.2.3
Node:
NPM:
Yarn:
Browsers: Brave Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.8 (and Quasar v2.0.0-beta.11)
