### ISSUE TITLE
Align icon problem for QSelect inside QField with a filter

### ISSUE THREAD

**Issue by kevingermain** [quasarframework/quasar#866]
A right alignment for an icon is not working with a QField and a QSelect with a **filter** (the floatLabel javascript property is empty, so the class "q-field-floating" doesn't appear, so the icon doesn't have a margin-top: 12px.

![screenshot at 23-24-46](https://user-images.githubusercontent.com/1334099/30185934-d0a2e286-9423-11e7-8c57-fbff191b366c.png)

![screenshot at 23-25-03](https://user-images.githubusercontent.com/1334099/30185937-d3fc9490-9423-11e7-8b39-3308cb1ea194.png)

**Comment by rstoenescu** [comment]
Will investigate. Thanks for reporting!

**Comment by kevingermain** [comment]
A pleasure to report, I'm working with Quasar for the moment, it's an amazing work! I'm currently doing a long project with it so I'll try to report any issue I can find.

**Comment by rstoenescu** [comment]
I just tried to reproduce but couldn't. Can you post your template pls and specify each scope variable what it points to? Thanks!

**Comment by rstoenescu** [comment]
Please reopen with requested info. Cannot reproduce. Thanks!
