### ISSUE TITLE
RTL is not working in the latest beta

### ISSUE THREAD

**Issue by MuhammadFayed** [quasarframework/quasar#8660]
**Describe the bug**
 Setting [rtl: true] in [quasar.conf.js] results in this error when building the app with "quasar dev"

```
 TypeError: Cannot read property 'unprefixed' of undefined

  - keyframes.js:5 Object.<anonymous>
    [WebApp]/[postcss-rtl]/lib/keyframes.js:5:35   [line 5: const unprefixed = postcss.vendor.unprefixed;]

  - loader:1092 Module._compile
    node:internal/modules/cjs/loader:1092:14
```
I searched and found that "vendor" has been removed in postcss 8+ according to [postcss/postcss#1372](https://github.com/postcss/postcss/issues/1372)

And the current installed postcss in quasar is 8.2.7
while "postcss-rtl": "^1.7.3" is still expecting vendor, and no one is supporting this repo anymore.

**To Reproduce**
A new project with "rtl" set to true:

**Expected behavior**
"quasar dev" should run smoothly

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.9
@quasar/app Version: 2.2.3
Quasar mode:
  - SPA

Tested on:
  - SPA
  
OS: Windows 10
Node: v15.11.0
NPM:7.6.1

**Comment by ejez** [comment]
I tried `rtl` and it is working for me.

Can you confirm the version of `@quasar/app`, as Quasar v2 should have `@quasar/app` v3

**Comment by MuhammadFayed** [comment]
@quasar/app version is "3.0.0-beta.9"

I'm attaching the following sample for more information

[rtl-test.zip](https://github.com/quasarframework/quasar/files/6191566/rtl-test.zip)

![issue](https://user-images.githubusercontent.com/5268288/112189320-543a9e00-8c1d-11eb-8f6f-68e628679e56.png)

**Comment by ejez** [comment]
(I asked for the version because you reported 2.2.3 initially)

Can you please retry with exactly the following steps with the same selections:
(use a normal terminal, not the editor terminal)

```sh
quasar create rtl-test --branch next

? Project name (internal usage for dev) rtl-test
? Project product name (must start with letter if building mobile apps) Quasar App
? Project description A Quasar Framework app
? Pick your CSS preprocessor: SCSS
? Check the features needed for your project: ESLint (recommended), Vue-i18n
? Pick an ESLint preset: Prettier
? Continue to install project dependencies after the project has been created? (recommended) yarn

cd rtl-test

# Enable rtl.
sed -i "/build: {/a rtl: true," quasar.conf.js # or add it manually.
# Set app lang.
sed -i "/framework: {/a lang: 'ar'," quasar.conf.js # or add it manually.

quasar dev
```
I just did the above and all was ok:
![20210323_20h54m54s](https://user-images.githubusercontent.com/48388358/112195205-bd6ce200-8c1a-11eb-9324-5fbe931aec88.png)

**Comment by MuhammadFayed** [comment]
> (I asked for the version because you reported 2.2.3 initially)

Sorry about that 😊

I tried Yarn and It's working.

So I looked for the PostCSS version and found out that Yarn is installing PostCSS version **"7.0.35"**, just the one before the 8th.. which is compatible with PostCSS-RTL.

**Comment by rstoenescu** [comment]
This ticket is obsolete now. Fixed while upgrading q/app to use Webpack 5 AND switching from postcss-rtl to postcss-rtlcss in the process.
Will work correctly with "@quasar/app" v3.0.0-beta.16.

**Comment by zhengju1893** [comment]
> > (I asked for the version because you reported 2.2.3 initially)
> 
> Sorry about that 😊
> 
> I tried Yarn and It's working.
> 
> So I looked for the PostCSS version and found out that Yarn is installing PostCSS version **"7.0.35"**, just the one before the 8th.. which is compatible with PostCSS-RTL.

thank you! The perfect solution to my problem. Check the package.lock to see if the bear version is  **"7.0.36"**
