### ISSUE TITLE
Q-stepper hase some strange mechanism while using forms

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar#8663]
**Describe the bug**
I'm using a q-stepper which is inside a q-form.
Assume you have 2 step with different input fields with their rules.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:

  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment]
#8469

**Comment by vandelpavel** [comment]
@pdanpdan Sorry I made a mistake when posting the issue.

**Comment by metalsadman** [comment]
> @pdanpdan Sorry I'v made a mistake when posting the issue.
> Could this issue be reopened?
see `Else` section of https://github.com/quasarframework/quasar/issues/8469

stepper has `keep-alive`, see this example it's panel example but related as both have same mechanism https://codepen.io/metalsadman/pen/povXyrL.
