### ISSUE TITLE
Inject name & description into BEX manifest.json

### ISSUE THREAD

**Issue by thdoan** [quasarframework/quasar#8664]
**Is your feature request related to a problem? Please describe.**
At the moment when you spawn a BEX mode app, the generated `manifest.json` does not take into account the app name and description that you entered when creating the app.

**Describe the solution you'd like**
It would be nice to have `name` and `description` fields prepopulated with the info you provided.

**Comment by rstoenescu** [comment]
Implemented this for Quasar v2 with the upcoming Quasar CLI on Vite (unreleased as of writing these lines though).
Apart from taking care of this automatically (should the "name"/"version"/"description" is missing from the bex manifest), there will also be available: quasar.config.js > bex > extendBexManifestJson (json)
