### ISSUE TITLE
Remove overscroll glow...

### ISSUE THREAD

**Issue by MejorCodigo** [quasarframework/quasar#867]
I would like to know if it's possible to remove the glow effect when the user tries to overscroll.

I noticed that the play app ([this app](https://play.google.com/store/apps/details?id=com.quasarframework.quasarplay&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)) doesn't show the glow effect and I would like to know how I can replicate that.

**Comment by rstoenescu** [comment]
Can you be more specific pls? A screenshot highlighting with what exactly you need might help. Thanks.

**Comment by MejorCodigo** [comment]
Hi, yeah I want to remove this overscroll glow effect ([image](https://ibb.co/mRG7ia)). Is it possible?

**Comment by rstoenescu** [comment]
No solution that I know of. That is part of Android WebView. Nothing to do with Quasar at all. You might want to check out the Android docs.
