### ISSUE TITLE
Unexpected recursion when component's filename matches subcomponent's alias

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#8672]
**Describe the bug**

Basically, there is a conflict between multiple components having the same alias. This happens in dev mode and in production mode.

There is no actual conflict, but it seems that somehow the names are being globally registered without "scoping" them to the component that creates the alias.

**This may be vuejs or webpack problem, but this most definitely used to work in Quasar@v1. I am also submitting the same Codesandbox to Vue.**

Example from Codesandbox:

> pages/PrivacyPolicy.vue
```
<template>
  <PrivacyPolicy /> <!-- Changing this alias to anything but this file's filename, makes it work -->
</template>

<script>
export default {
  components: {
    PrivacyPolicy: () -> import('components/PrivacyPolicy')
  }
}
</script>
```

> components/PrivacyPolicy.vue
```
<template>
  <q-card flat class="lm-card">
    <q-card-section class="full-height">
      <h4 class="q-mt-xs q-mb-md">Privacy Policy</h4>
    </q-card-section>
  </q-card>
</template>

<script>
export default {
  name: 'PrivacyPolicy' <!-- Changing this has no effect -->
}
</script>
```

So basically, we have a shared component with a name `PrivacyPolicy`, we can alias it to anything, but we choose `PrivacyPolicy`. We also have `PrivacyPolicy` page, which displays the privacy policy contents, it defines an alias for `components/PrivacyPolicy` and uses it in its template. However, `PrivacyPolicy` already (somehow) resolves to `pages/PrivacyPolicy`, so we get recursion.

**Codesandbox**
[https://codesandbox.io/s/bold-violet-1t891](https://codesandbox.io/s/bold-violet-1t891)

**To Reproduce**
- Open `/privacy` route (`/#/privacy`), blank page shows
- Open `/fixed` route (`/#/fixed`), **Privacy Policy** is displayed

**Expected behavior**
**Privacy Policy** displayed in both cases

**Screenshots**
![image](https://user-images.githubusercontent.com/2260539/112254374-684fc100-8c58-11eb-93de-f1a1a0fe8e1a.png)

**Platform:**
Quasar Version: 2.0.0-beta.10
@quasar/app Version: 3.0.0-beta.9
Quasar mode:
  - [X] SPA

Tested on:
  - [X] SPA

**Additional context**

Similar undesired behavior was experienced in #8548, when all images in ~assets subdirectories were included at root. In other words, `~assets/subdirectory/image.png` would resolve to `~assets/image.png` in development and production modes.

**Comment by rstoenescu** [comment]
This has to do entirely with Vue (in particular, with vue-loader) and not with Quasar.
