### ISSUE TITLE
update:modelValue event not fired for q-input/q-time

### ISSUE THREAD

**Issue by smadep** [quasarframework/quasar#8673]
As discussed on discord here 
https://discord.com/channels/415874313728688138/806171748046733332/824172056353701938
there seems to be a bug that the update:modelValue event is not fired for neither q-input nor q-time

https://codepen.io/smadep/pen/VwPYbjv

**Comment by rstoenescu** [comment]
While on UMD, use kebab-case event names. In this case `@update:model-value`. This is a Vue thing, not a Quasar thing.

**Comment by smadep** [comment]
thanks - that made the codepen somewhat work. but I think the update event on qtime should only be triggered on mouseup of the last part not mouse down
