### ISSUE TITLE
Table with both multiselection ability and Q-pop-up

### ISSUE THREAD

**Issue by YimingXieUSC** [quasarframework/quasar#8677]
**Is your feature request related to a problem? Please describe.**
I am working on a project where both multi-select and pop-up edit are required. Could you please improve the Table component so that it could support both functionalities?

**Describe the solution you'd like**
If there exists a current solution to this problem, please provide me an example that is easy for replication. Thank you.

**Comment by pdanpdan** [comment]
8469
