### ISSUE TITLE
Notify plugin bug

### ISSUE THREAD

**Issue by disfated** [quasarframework/quasar#8687]
**Describe the bug**
Appears in the example at <https://next.quasar.dev/quasar-plugins/notify#updatable-notifications>

> Uncaught TypeError: Object.defineProperty called on non-object

**Codepen**
<https://codepen.io/disfated/pen/jOyWBVj>

**To Reproduce**
1. Click the button
2. Wait till 100%
3. Exception -> See console

**Expected behavior**
No exception

**Version** `quasar-v2.0.0-beta.10`

**Additional context**
Exception is thrown from here
<https://github.com/quasarframework/quasar/blob/87cead03ed78419129f9a5eb51e1a966b723ad88/ui/src/plugins/Notify.js#L117>
when `notif({ spinner: false })` is passed.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.12
