### ISSUE TITLE
Clicking QChip triggers ripple always

### ISSUE THREAD

**Issue by abiliodasilva** [quasarframework/quasar#8691]
**Describe the bug**
Clicking `QChip` triggers ripple even if the prop is set as false.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/abiliodasilva/pen/RwKaoxm?editors=101

**To Reproduce**
Click on a `QChip` with `ripple="false"`

**Expected behavior**
No ripple.

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.10
Quasar mode: UMD

Tested on: UMD

OS: Windows 10
Browsers: Google Chrome 89.0.4389.90

**Comment by abiliodasilva** [comment]
Testing a little more, ripple appears even with the `QChip` disabled.

**Comment by rstoenescu** [comment]
`ripple="false"` means that you're supplying the String "false" to it, not the Boolean false.
Correct is `:ripple="false"`.

**Comment by rstoenescu** [comment]
Fixed the ripple when QChip is in `disable` state though.
Will be available in Quasar v2.0.0-beta.12.

**Comment by abiliodasilva** [comment]
Greetings, @rstoenescu

> `ripple="false"` means that you're supplying the String "false" to it, not the Boolean false.
> Correct is `:ripple="false"`.

Oh, sorry about that, silly error from my part.

> Fixed the ripple when QChip is in `disable` state though.
> Will be available in Quasar v2.0.0-beta.12.

Glad to know about it!
I'm pretty satisfied so far with Quasar Framework, it really boost Vue reactive apps, it's amazing!

**Comment by lupodellasleppa** [comment]
I find it a little bit uncomfortable and especially counterintuitive to always have to specify `:ripple="false"` on all chips. Wouldn't it be better to have the ripple effect only on `clickable` chips? I think it also adheres more to design principles and guidelines (why have a ripple effect on something that does nothing when clicked?)

Anyway, thanks for the great work on Quasar! :pray:
