### ISSUE TITLE
Quasar Middleware

### ISSUE THREAD

**Issue by aprilahijriyan** [quasarframework/quasar#8693]
Do quasar has a configuration for adding middleware to the page?

**Comment by aprilahijriyan** [comment]
The following link might be a reference https://gist.github.com/acfatah/719c67a4effb63d4ebe053ab00561093

**Comment by Smrtnyk** [comment]
that what you posted is vue-router specific, and can be easily implemented by yourself
I don't think quasar should go such an opinionated route and add all kinds of stuff people come up with

**Comment by aprilahijriyan** [comment]
@Smrtnyk Unfortunately I don't really understand vue js or its derivatives. It may be helpful for others if they don't understand the details of its usage. BTW, it's similar to nuxt js, which is very helpful in my opinion.

**Comment by francoism90** [comment]
Quasar offers 'boot file' support, meaning you can hook router, store, etc. to create your own middleware(s):
https://quasar.dev/quasar-cli/boot-files
