### ISSUE TITLE
Cant read process.env.VAL properly

### ISSUE THREAD

**Issue by jtlindsey** [quasarframework/quasar#8695]
**Describe the bug**
Server can't read `process.env` in production or the first time in development. Everything worked in development without this package just by using the more common `dotenv` package. After testing everything in dev mode and deploying/build to production `process.env` doesn't contain any of my custom variables. So i tried the suggested packages.

I'm trying to access `process.env.VAL` from inside `src-ssr/extensions.js` and it only works in development. 

I also checked the example in this repo but the example doesn't use `ssr`. The `src-ssr` is empty.

**To Reproduce**
1. Create a quasar app that is ssr (repo example [https://github.com/jtlindsey/quasar-broken-ssr-env](https://github.com/jtlindsey/quasar-broken-ssr-env))
2. Create some custom process.env variables like `VAL` in `.env` AND `.quasar.env.json`
3. See how process.env.VAL works fine in development Home page displays "Whatis val? something" `npm run dev`
4. See how in production it is undefined `npm run build && npm start`

**Expected behavior**
process.env.VAL should be available in production in `src-ssr`.

**Screenshots**

![Kapture 2021-03-27 at 07 20 56](https://user-images.githubusercontent.com/7409277/112719053-12378380-8ecd-11eb-9462-318620a7c954.gif)

**Platform (please complete the following information):**
`@quasar/app@2.2.2`
`quasar@1.15.6`
Quasar mode:

  - [ ] SPA
  - [x ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac and Linux
Node: 14.16
NPM: 6.14.11
Browsers: All

**Additional context**
What is also strange is the behavior is not consistent or it doesn't work the first time in development.
1. start server with `npm run dev` an the example variable is undefined.
2. make small change on server `extension.js` file to trigger hot reload and see example variable is defined

Whatever is causing the above may be the reason why production never works.

Posting this in quasar too as it seems to be affecting more than just the env packages.
ref issue https://github.com/quasarframework/app-extension-qenv/issues/65

**Comment by rstoenescu** [comment]
The recommended way is described [here](https://quasar.dev/quasar-cli/quasar-conf-js#using-dotenv).
Remove "@quasar/qenv" and "@quasar/dotenv" App Extensions. They have been deprecated.

**Comment by jtlindsey** [comment]
> The recommended way is described [here](https://quasar.dev/quasar-cli/quasar-conf-js#using-dotenv).
> Remove "@quasar/qenv" and "@quasar/dotenv" App Extensions. They have been deprecated.

I updated the repo to show that even after [the changes](https://github.com/jtlindsey/quasar-broken-ssr-env/commit/2134c04f5fe66c1ef5dce5c2f879999992c7e5ab), you still can't read `.env` from production but you can in dev. Line 15 of extension.js will not allow the app to run if it can't read 'something' from VAL in `.env`. It runs fine in dev like before and not in production. 


Can you please point out what I missed in my minimum production repo from the docs:


#### Using dotenv

Should you wish to use `.env` file(s), you can even use [dotenv](https://www.npmjs.com/package/dotenv) package. The following is just an example that passes env variables from the terminal right down to your UI's app code:

```bash
$ yarn add --dev dotenv
```

Then in your `/quasar.conf.js`:
```
build: {
  env: require('dotenv').config().parsed
}
```
