### ISSUE TITLE
-webkit-overflow-scrolling is a invalid-property in Quasar

### ISSUE THREAD

**Issue by anandtripathi5** [quasarframework/quasar#8696]
Quasar based android app is too jerky and when I inspect my android app using Google Chrome I saw that the -webkit-overflow-scrolling: touch is an invalid property in Quasar. Can somebody help me with this. I want a smooth momentum scrolling in my App
![image](https://user-images.githubusercontent.com/10723482/112730240-794d4a80-8f56-11eb-86f7-4603ba50c35d.png)

Quasar version used: v2.1.1

**Comment by pdanpdan** [comment]
#8469
