### ISSUE TITLE
QInfiniteScroll done-callback TypeError: stop is not a function

### ISSUE THREAD

**Issue by susnux** [quasarframework/quasar#8697]
**Describe the bug**
The `done` callback of the `load`-event accepts a boolean `stop` parameter to indicate stop loading.
But setting this on the Quasar2's version of `QInfiniteScroll` results in a `TypeError`:
```console
    Uncaught (in promise) TypeError: stop is not a function
    trigger QInfiniteScroll.js:94
    promise callback*nextTick runtime-core.esm-bundler.js:245
    trigger QInfiniteScroll.js:83
```

[Line 94](https://github.com/quasarframework/quasar/blob/9d94dbf472c5c0f809f9148823d3a959bfc8e70f/ui/src/components/infinite-scroll/QInfiniteScroll.js#L94) calls `stop()`, which should be [the stop function](https://github.com/quasarframework/quasar/blob/9d94dbf472c5c0f809f9148823d3a959bfc8e70f/ui/src/components/infinite-scroll/QInfiniteScroll.js#L117) but is shadowed by the [boolean `stop` parameter](https://github.com/quasarframework/quasar/blob/9d94dbf472c5c0f809f9148823d3a959bfc8e70f/ui/src/components/infinite-scroll/QInfiniteScroll.js#L80).

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/wonderful-meninsky-ds6kh?file=/src/pages/Index.vue

**To Reproduce**
1. Go to link above
2. Open the browser debug console
3. Scroll down until a `trigger` is triggered

**Expected behavior**
Stop calling `trigger ()` / stop loading / no error.

**Screenshots**
![Screenshot_20210327_230625](https://user-images.githubusercontent.com/1855448/112736223-5ec4a280-8f51-11eb-892f-8722236b79b0.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.11
@quasar/app Version: 3.0.0-beta.10
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux 5.11.6 (openSUSE Tumbleweed)
Node: 10.24.0
NPM:
Yarn:1.22.10
Browsers: Mozilla Firefox 86.0.1, Chromium 89.0.4389.90 
iOS:
Android:
Electron:

**Additional context**
The example was taken from the docs.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-beta.12.
