### ISSUE TITLE
Mask - reverse-fill-mask - Add a literal string from mask even if val is less than mask

### ISSUE THREAD

**Issue by livioalves** [quasarframework/quasar#8698]
Reverse fill mask formatting add a part of literal mask when the value length entered is lower than mask position. 

For Example

  <q-input v-model="val" 
                                            reverse-fill-mask
                                            input-class="text-right"
                                            mask="###.###.###.###,##"
                                            placeholder="Value" label-color="label" outlined dense />

When inputed 12345 the output is .123,45 the dot should not appear in resulting format. The correct output should be 123,45

**Platform (please complete the following information):**
Quasar Version: 1.15.14
@quasar/app Version: 2.1.5
Quasar mode: 

  - [ X ] SPA
  - [ X ] SSR
  - [ X ] PWA
  - [ X ] Electron
  - [ X ] Cordova
  - [ X ] Capacitor
  - [ X ] BEX

**Codepen/
![Captura de Tela 2021-03-27 às 20 45 39](https://user-images.githubusercontent.com/5504723/112737959-772ac200-8f3d-11eb-8bab-69c3021750f3.png)
jsFiddle/Codesandbox (required)**
https://codepen.io/livioalves/pen/bGgepGJ

**Comment by pdanpdan** [comment]
Nice catch. Checking your PR I also found some other issues with cursor repositioning after delete/insert.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.15
