### ISSUE TITLE
Workflow with quasar...

### ISSUE THREAD

**Issue by BrianMoreno1994** [quasarframework/quasar#870]
Hi, so i've been using this framework for a bit now and I'm liking it so far. I'm using it with cordova to make apps. However, when I want to create the app for the first time I have to follow these steps:

1. Run `quasar build`
2. Run `quasar wrap cordova`
3. Run `cd cordova`
4. Run `cordova platform add android`
5. Run `cordova run android`

Whenever I update the app I delete the cordova folder and restart the whole process which takes a bit of time, I was wondering if their is a way to automate these tasks? 

Another slight disadvantage I'm having is when updating my app... I delete the cordova folder which deletes 2 important files, my config.xml file which is where i specify preferences, name of the app, description, etc and also deletes my package.json which is where I have all my cordova plugins specified. Any way I can remedy this?

**Comment by smolinari** [comment]
Write a bash script that takes your code from another place on your computer and copies it over to continue to build it? 

Also, in general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [gitter channel](https://gitter.im/quasarframework/Lobby) for general questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by BrianMoreno1994** [comment]
Thanks, that's what I was thinking of doing. In regards to my second question, would I just need to reconfigure my `package.json` and my `config.xml` files every time I update the app?

**Comment by smolinari** [comment]
Create a bash script for the deletion, which also takes your files out first and puts them in a safe place and then deletes the folder. When you rebuild, reinsert the files. That is a quick guess on my part. I've never built a cordova app to be honest.

Scott

**Comment by MoacirSchmidt** [comment]
Why do you need to delete cordova folder? Usually a "quasar build" command updates all....

**Comment by BrianMoreno1994** [comment]
Including the project under the cordova folder? @MoacirSchmidt

**Comment by MoacirSchmidt** [comment]
Yes! My workflow is (initial wrap runs only once)
1. quasar build
2. cd cordova
3. cordova run android

**Comment by MoacirSchmidt** [comment]
Lets continue at http://forum.quasar-framework.org/topic/835/quasar-workflow/3. Soon this will be deleted :-)
