### ISSUE TITLE
quasar v2.0.0-beta.11 makes error when RTL set to TRUE

### ISSUE THREAD

**Issue by progdev** [quasarframework/quasar#8701]
(node:39151) UnhandledPromiseRejectionWarning:   TypeError: Cannot read property 'unprefixed' of undefined
  
  - keyframes.js:5 Object.<anonymous>
    [q_dailyloco]/[postcss-rtl]/lib/keyframes.js:5:35
  
  - loader.js:999 Module._compile
    internal/modules/cjs/loader.js:999:30
  
  - loader.js:1027 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1027:10
  
  - loader.js:863 Module.load
    internal/modules/cjs/loader.js:863:32
  
  - loader.js:708 Function.Module._load
    internal/modules/cjs/loader.js:708:14
  
  - loader.js:887 Module.require
    internal/modules/cjs/loader.js:887:19
  
  - helpers.js:74 require
    internal/modules/cjs/helpers.js:74:18
  
  - index.js:18 Object.<anonymous>
    [q_dailyloco]/[postcss-rtl]/lib/index.js:18:19
  
  - loader.js:999 Module._compile
    internal/modules/cjs/loader.js:999:30
  
  - loader.js:1027 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1027:10
  

(node:39151) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:39151) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pdanpdan** [comment]
Are you using npm instead of yarn?
Or did you add postcss-rtl in package.json?

**Comment by progdev** [comment]
yes, i use npm

**Comment by pdanpdan** [comment]
It's installing the wrong version of the dependency I suppose.

**Comment by rstoenescu** [comment]
Please use yarn as its the only one installing the correct versions of dependencies. There's currently no solution for npm due to the use of webpack 4. We plan on upgrading it to webpack 5 (which is a heavy breaking change), but for Quasar v2 only.
