### ISSUE TITLE
Update is-svg due to Dependabot alert

### ISSUE THREAD

**Issue by jakobnoergaard** [quasarframework/quasar#8702]
Hi,
 
Im getting the Dependabot alert. Can this be updated?

![Screenshot 2021-03-29 at 10 26 06](https://user-images.githubusercontent.com/20745759/112808539-5ebfc200-9079-11eb-8334-11d7e9a9411d.png)

Truly truly amazing framework, by the way!!!!!!!

**Comment by rstoenescu** [comment]
Hi,

This is not the way to report a security issue. We've made it extra clear in the docs > Security group section.
