### ISSUE TITLE
Quasar Typescript error

### ISSUE THREAD

**Issue by rainer9202** [quasarframework/quasar#8706]
After creating a new project using quasar create <proyectname> and enabling the typescript option, typescript errors are displayed in the console.

1. Run command quasar create <proyectname>
2. Enable typescript option in quasar cli options.
3. Run command quasar dev.
4. Change any file to force quasar recharge files.
5. See the typescript errors.

**Expected behavior**
Dont show typescript errors

**Screenshots**
![image](https://user-images.githubusercontent.com/44645071/112844366-83577200-9058-11eb-8267-5548aee35acd.png)

**Platform (please complete the following information):**
Quasar Version: 1.15.9
@quasar/app Version: 2.2.3
Quasar mode: 

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows_NT (10.0.19042) - win32/x64
Node: 14.15.5
NPM: 6.14.11
Yarn: 1.22.5
Browsers: Any
iOS: 
Android:
Electron:

**Additional context**
![image](https://user-images.githubusercontent.com/44645071/112844747-eea14400-9058-11eb-9a94-357d1ceccc3a.png)

**Comment by rstoenescu** [comment]
This should be fixed in next "@quasar/app" release.
