### ISSUE TITLE
[Request] quasar build to build inside a specified location

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#871]
If a quasar app is located inside a back end set up, we sometimes want the `quasar build` command to save the app in a separate location outside of the quasar folder.

In my case quasar lives in my Laravel directory: `laravelwebsite/resources/apps/quasarapp`
And I would like the `quasar build` command to also save my app into: `laravelwebsite/public/` without messing with the Laravel index.php.

So my request is a simple **config file** inside the quasar folder where you can **set the folder you want to build** your app in and with what appname.html you want to build it with.

In my case, I need it to be built as `quasarapp.html` using the name of my quasar-app inside the Laravel public folder.

For reference, I have set up my Laravel route like so:

```php
// set up the route:
Route::domain('quasarapp'.env('SESSION_DOMAIN')) // e.g. choose a subdomain
	->get('/', 'ViewController@quasarapp')
	->name('quasarapp.index');

// set up the view controller:
public function quasarapp()
{
    return \File::get(public_path() . '/quasarapp.html');
}
```

**Comment by rstoenescu** [comment]
Hi,

Please open to the according repo, which is the [default starter kit](https://github.com/quasarframework/quasar-template-default/issues) as this has nothing to do with Quasar core itself. Thanks!
