### ISSUE TITLE
Tooltip with button doesn't hide when button is disabled

### ISSUE THREAD

**Issue by mam-ijinus** [quasarframework/quasar#8718]
**Describe the bug**
When you add tooltip at button and the button is disable after the click on it ( as reset button) the tooltip stay and doesn't hide.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/madam_ijinus/pen/yLgVBPL

**To Reproduce**
1. Go to the fiddle
2. Click on the button
3. See error: the tooltip stay showed

**Expected behavior**
The tooltip hide

**Platform (please complete the following information):**
Quasar Version: from last fiddle: 1.15.8

**Comment by rstoenescu** [comment]
This is because even disabled native buttons do not emit any events. However, should you want QBtn to emit events, change its type to `type="a"` (renders and `<a>` tag). That will emit events regardless of disable state.

**Comment by mam-ijinus** [comment]
thanks a lot ! Nice tips
