### ISSUE TITLE
Layout (with header) and scrollbar behavior in 0.14.2 versus 0.13.4 (on desktop)

### ISSUE THREAD

**Issue by leob** [quasarframework/quasar#872]
Config:

Quasar: 0.14.2
OS: OSX 10.11.6
Node: v6.9.1
Browsers: Chrome 60.0.3112.113

Issue:

There's a difference in look/behavior regarding the browser scrollbar, between a simple app built with Quasar 0.14.2 versus the same app built with Quasar 0.13.4, when viewing the app in a browser (Chrome) on my desktop (Macbook).

This is most easily explained by showing two screenshots, one of the 0.13.4 app (left) and one of the 0.14.2 app (right):

![layout](https://user-images.githubusercontent.com/993465/30262563-fb26c36e-9703-11e7-832a-32f64f0e42a1.jpg)

As you can see, in the 0.13.4 app the scrollbar starts BELOW the header (the header is fixed at the top), in the 0.14.2 app the scrollbar starts at the top of the browser window (viewport).

Is this by design, or am I doing something wrong? It's not a big deal but the "old" behavior (0.13.4) seems more logical to me (it scrolls only the part under the fixed header).

The code that I've used:

0.13.4:

```
<template>
  <q-layout>
    <div slot="header" class="toolbar">
	stuff here
    </div>
    <router-view class="layout-view" :user="user"></router-view>
  </q-layout>
</template>
```

and 0.14.2:

```
<template>
  <q-layout ref="layout" view="hHr LpR lFf">
    <q-toolbar slot="header">
	stuff here
    </q-toolbar>
    <router-view class="layout-view" :user="user"></router-view>
  </q-layout>
</template>
```

I've fiddled a bit with the "view" attribute on the q-layout element, but that didn't affect the outcome (as far as the scrollbar goes).

**Comment by rstoenescu** [comment]
Hi,

Yes, this is the default behavior now. QLayout has been redesigned from the ground up to avoid some common pitfalls and enable a lot of new possibilities. One of the side-effects of this revamp is what you have noticed, which unfortunately due to technical possibilities cannot be made to look like v0.13. Sorry for any inconvenience.

**Comment by leob** [comment]
Sorry to bother you (and it's okay of course to close the issue) but can I ask just one additional question? Can you expand a bit (in one or two lines) what the technical problem is?

If you think this is difficult but technically feasible then I would be willing to volunteer to help you out (you're probably overloaded with work on the framework), maybe (if it makes sense) this could be an option n the component to choose the "old" or the "new" behavior.

On the other hand, I don't want to make a big deal out of it, I haven't checked but probably other frameworks (e.g. Ionic) do this in the same way. I probably wouldn't have noticed it if I would't have compared it to the "old" framework.
