### ISSUE TITLE
Module System with new Quasar

### ISSUE THREAD

**Issue by bazuka5801** [quasarframework/quasar#8722]
**Is your feature request related to a problem? Please describe.**
Module System with Quasar to reduce security problems on implementing some functional (eg. pincode)
In my work, quasar is everywhere’s, and I believe that I can improve simple usage of quasar for developers.

**Terminology + Prologue:** 
Quasar - foundation of any UI app [ Web (PWA and/or SSR), Android & IOS (Cordova or Capacitor) ]
Quasar merge many utils, instruments to one build engine, and it's awesome!
My daily work spin around developing mobile applications with Quasar + Capacitor v3, and some my feature request 'Module System' may be bottleneck.

I work with Quasar more than 2 years, and now my work **50-60%** usually for new projects is a copy-paste logic+store+vue code. I want to reduce it time with "Module System".

**Examples**
Quasar is good for me for some project types: Admin Panel and mobile app, and I will use these types to provide a module system examples.'

Ex. Admin Panels have a login page
All realtime projects have role-based access to app.
Good! We can create module "**roles**", that create one `vue-router` navigation guard and:
1) Provide instruction how init this module
2) Provide instruction how set role
3) Provide instruction how use this module in code logic

Implementations of set role can be more (axios post or Firebase Auth, OAuth, ....)
This module can be used in upper level module - "**firebase-auth**"
**firebase-auth**
1) Provide instruction how to use (call authenticate method with some arguments)
2) Provide instruction how module works with other modules(fetch [custom claims](https://firebase.google.com/docs/auth/admin/custom-claims) from user auth and call **setRole** on `roles` module)
Or we can use for **admin panel** project some another module for auth with roles dependency.
For mobile app we can use same `roles` module to provide role-based access in app (ex. "Customer", "Executor")
And we can use module `roles` anywhere Bex, Cordova or PWA app.

What you think about it?

**Comment by rstoenescu** [comment]
I think you are referring to the App Extensions.

**Comment by rstoenescu** [comment]
Please reopen after reading about App Extensions if I missed something.

**Comment by corepay** [comment]
Look at '[Module Fedeation](https://module-federation.github.io/blog/get-started)'.  I am successfully using this and Quasar between multiple applications.  Basically I have a 'base' app that has my common features - store, auth screens, layouts common components like addresses, emails and phones I use across multiple apps.  I also have an application that is my 'Customers' domain, an application that is my 'Products' domain etc.  Each of these I export components I may use in any new application I build.  

For example, when I build a new app that needs a store and auth and addresses I access those from my 'Base' app with a simple import.  If I need any of my exposed modules from my Products app I simple import those also.  I'm proud to say with a little forward thinking on the architecture I can know whip out an app in hours - mostly by dropping in modules I already built where I need them in quasar views.  Troubleshooting and tweaking is super simple now - I have only one module to deal with say when I want to add a field to my exposed Addresses Detail form.


Cherry on the top is all the apps I build - whether they be the domain apps like Customers or Products or a new app I lego-snap together using exposed modules is that I can name shared dependencies between them so bundle size stays minimal.  Check it out - it is Webpack 5 so you have to use Vue3 with Quasar plugin or Vue2 w/quasar plugin upgrading webpack to 5...

**Comment by Arkshine** [comment]
@corepay Hey. Any chance you would share some basic examples how you implement it, please? That would be awesome. I'm having a hard time to make it work.
