### ISSUE TITLE
"dir" and "lang" attributes not updated after "Quasar.lang.set" in ssr mode

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#8724]
**Describe the bug**
When changing Quasar language, the html document attributes `dir` and `lang` are not updated to reflect the new language. This happens when using ssr.

**To Reproduce**
```sh
quasar create ssr-lang-issue --branch next

# default selections
? Project name (internal usage for dev) ssr-lang-issue
? Project product name (must start with letter if building mobile apps) Quasar App
? Project description A Quasar Framework app
? Pick your CSS preprocessor: SCSS
? Check the features needed for your project: ESLint (recommended)
? Pick an ESLint preset: Prettier
? Continue to install project dependencies after the project has been created? (recommended) yarn

cd ssr-lang-issue/

# allow ssr
sed -i '/TODO vue3/,+9 s/^/\/\//' node_modules/@quasar/app/bin/quasar-dev node_modules/@quasar/app/bin/quasar-build

quasar dev -m ssr
```
Create `src/components/LangSelector.vue` with code from https://next.quasar.dev/options/quasar-language-packs#change-quasar-language-pack-at-runtime

Add it to `src/layouts/MainLayout.vue`:
```diff
        <div>Quasar v{{ $q.version }}</div>

+       <lang-selector></lang-selector>
      </q-toolbar>
...
+import LangSelector from "components/LangSelector.vue";
...
  components: {
    EssentialLink,
+   LangSelector,
  },
```

**Expected behavior**
When changing the language, the attributes `lang`/`dir` should reflect the change.

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.11
@quasar/app Version: v3.0.0-beta.10
Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Additional context**
In SPA mode, the issue does not happen.

When investigating the issue, I found that the issue is coming from `isRuntimeSsrPreHydration` check in https://github.com/quasarframework/quasar/blob/18d6d0d70d12171f26f9afc2bc55cd3b60bdb19b/ui/src/lang.js#L56
```js
      if (isRuntimeSsrPreHydration === false) {
        const el = document.documentElement
        el.setAttribute('dir', lang.rtl === true ? 'rtl' : 'ltr')
        el.setAttribute('lang', lang.isoName)
      }
```
which reports `true`, hence not running the code inside the `if` statement.

`isRuntimeSsrPreHydration` is defined in https://github.com/quasarframework/quasar/blob/18d6d0d70d12171f26f9afc2bc55cd3b60bdb19b/ui/src/plugins/Platform.js#L15:
```js
export let isRuntimeSsrPreHydration = __QUASAR_SSR_SERVER__ || (
  __QUASAR_SSR_CLIENT__ && (
    __QUASAR_SSR_PWA__ ? document.body.getAttribute('data-server-rendered') !== null : true
  )
)
```
Which causes it to be `true` when in "client" in ssr mode which explains the issue.

**Comment by rstoenescu** [comment]
Hi,

Thanks for pointing this out.
Fix will be available in Quasar v2.0.0-beta.12.
