### ISSUE TITLE
Avoid app logic that relies on enumerating keys on a component instance (Q-Tabs in iOS WKWebView in Vue 3) Quasar 2.0.0-beta.11

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#8727]
**Describe the bug**

In iOS version 12.4 (16G77) WkWebView with a Capacitor build, QTabs cause an infinite loop of "Avoid app logic that relies on enumerating keys on a component instance" warnings leading to maximum call size errors, sluggish app performance, and ultimately crashes. This is the case with copy paste qtabs examples from the docs. The bug doesn't exist on Android, only iOS.

**Codepen/jsFiddle/Codesandbox (required)**
I don't now how to replicate WKWebView in Codepen

**To Reproduce**
Create an app for ios, build with capacitor, load a page with q-tabs on it.

You can use this for the layout:

```
<q-layout ref="layout" view="hHr LpR lFf">
  <q-page-container class="relative-position"
    <router-view v-slot="{ Component }">
      <component v-show="state.app_synced" :is="Component" />
    </router-view>
  </q-page-container>
</q-layout>
```

**Expected behavior**
No infinite loop of warnings.

**Screenshots**
<img width="1440" alt="Screen Shot 2021-03-29 at 6 52 26 PM" src="https://user-images.githubusercontent.com/7112345/113044138-f4834c00-9162-11eb-9313-96398215034c.png">

**Platform (please complete the following information):**
Quasar Version: ^2.0.0-beta.11
@quasar/app Version: ^3.0.0-beta.10
Quasar mode: 
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [x] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [x] Capacitor
  - [ ] BEX

OS: Apple iPhone 7
Node: v10.23.2
NPM: 6.14.10
Yarn: 1.22.10
Browsers: iOS WKWebView with Capacitor
iOS: 12.4

**Additional context**
Capacitor version:

"@capacitor/android": "^2.4.7",
"@capacitor/cli": "^2.0.0",
"@capacitor/core": "^2.0.0",
"@capacitor/ios": "^2.4.7",
"@codetrix-studio/capacitor-google-auth": "^2.1.3",
"capacitor-firebase-auth": "^2.4.0",
"cordova-plugin-purchase": "^10.5.3"

**Comment by codingfriend1** [comment]
I did some further investigation. I upgraded my iOS version to 14.4.2 but still get the same bug.

However, I found that the issue only presents itself when you use @update:modelValue="fn" on q-tabs.

**Comment by rstoenescu** [comment]
This seems like a Vue 3 bug. Is this still an issue nowadays? If so, please comment/reopen. Thank you.
