### ISSUE TITLE
LoadingBar setDefaults method is not working

### ISSUE THREAD

**Issue by AlwaysLoveme** [quasarframework/quasar#8729]
**Describe the bug**
using LoadingBar by outside vue; setDefaults method is not working, the LoadingBar style not changed.
```js
import { LoadingBar } from 'quasar';
LoadingBar.setDefaults({ // it is not working
  color: '#1c95ff',
  size: '3px',
  position: 'top'
});
export default LoadingBar;
```

**Expected behavior**
woking well

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.1
@quasar/app Version: 3.0.0-beta.1
Quasar mode: spa
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MAC OSX
Node:  14.15.4
NPM: 7.7.6
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Hi,

1. Please note that the color prop should be a color from Quasar [Color Palette](https://next.quasar.dev/style/color-palette) or [your custom color](https://next.quasar.dev/style/color-palette#adding-your-own-colors).
2. Your deps are outdated. Latest is:
  ```
  Pkg quasar........ v2.0.0-beta.11
  Pkg @quasar/app... v3.0.0-beta.10
  ```

**Comment by rstoenescu** [comment]
Also, not sure why you are exporting LoadingBar. You can import directly from 'quasar' wherever you need it.
