### ISSUE TITLE
QPopupEdit position prop 'self' does not work

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#8731]
**Describe the bug**
Setting "bottom middle" to `self` prop of popup edit component should show QMenu above the anchor, it is showing bellow instrad

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/luckylooke/pen/vYggERN

**To Reproduce**
1. Click on button

**Expected behavior**
QMenu should be above the anchor

**Screenshots**
EXPECTED:
![Screenshot from 2021-03-31 14-51-38](https://user-images.githubusercontent.com/3660030/113147032-ab013280-9230-11eb-82b2-8a8aaa4d9fff.png)
CURRENT:
![Screenshot from 2021-03-31 14-50-43](https://user-images.githubusercontent.com/3660030/113147036-ab99c900-9230-11eb-9316-7b51f8550a71.png)

**Platform (please complete the following information):**
codepen from docs
any platform I suppose
But I have latest chrome on ubuntu 20

Thank you for any help :pray:

**Comment by luckylooke** [comment]
Found the answer: 
Prop `cover`
Type Boolean

Description:
Allows the menu to cover its target. When used, the 'self' and 'fit' props are no longer effective

Default value
true

**Comment by pdanpdan** [comment]
https://codepen.io/pdanpdan/pen/RwKKPog
:)
