### ISSUE TITLE
Issue when opening a modal from a child component with an event

### ISSUE THREAD

**Issue by abacram** [quasarframework/quasar#874]
Hi, we are trying to open a modal from a subcomponent, in fact we have a GridComponent.vue with a DetailPanelComponent.vue inside and a a ModalGroupGridComponent.vue inside this last.

We have this code inside ModalGroupGridComponent.vue:

```
<template>
  <button class="push primary text-white animate-pop" @click="openModalGroupGrid"><i :class="getIcon('nuevo')"></i></button>
</template>

<script>
import { Events } from 'quasar'
import helpers from '../../../../../utils/helpers'

export default {
  mixins: [helpers],
  mounted () { },
  data () {
    return { }
  },
  components: { },
  methods: {
    openModalGroupGrid () { Events.$emit('openModalGroupGrid') }
  },
  beforeMount () { }
}
</script>

<style lang="styl" scoped>
button
  padding 0px 8px
  min-height 1.75rem
</style>

```
And in the DetailPanelComponent.vue this code:

```
<template>
  <div class="full-width-panel">
    <q-modal ref="modalGroupGrid" class="minimized" :content-css="{minWidth: '60vw', minHeight: '40vh'}">
      <div class="card no-margin no-shadow">
        <button class="float-right primary" @click="$refs.modalGroupGrid.close()"><i>close</i></button>
        <div class="card-title">
          <h5>Detalle de Historial</h5>
        </div>
        <div class="card-content">
        </div>
      </div>
    </q-modal>
  </div>
</template>

<script>
import Vue from 'vue'
import { Events } from 'quasar'
import store from '../../../../../vuex/store'
import ModalGroupGridComponent from './ModalGroupGridComponent.vue'
import helpers from '../../../../../utils/helpers'

export default Vue.extend({
  mixins: [helpers],
  data () {
    return {
    }
  },
  components: {
    ModalGroupGridComponent
  },
  methods: {
  },
  mounted () {
    Events.$on('openModalGroupGrid', () => {
      this.$refs.modalGroupGrid.open()
    })
    Events.$on('closeModalGroupGrid', () => {
      this.$refs.modalGroupGrid.close()
    })
  }
})
</script>
```

We are injecting the ModalGroupGridComponent.vue inside a table in order to load a modal each time we click the button inside this component, but always receive the same error:
`Uncaught TypeError: Cannot read property 'open' of undefined`

And by that we are looking for some help in the issues forum, any help?
Thanks,

Antonio

**Comment by rstoenescu** [comment]
Hi,

This is not related to Quasar, but exclusively to Vue. What I notice is that you register the events but you don't unregister them before DetailPanelComponent is destroyed, which means the two events are still executing even after component is destroyed. Also, please take note that events are global, so triggering 'openModalGroupGrid' event will be captured by each instance of DetailPanelComponent.

What I recommend is to use ref on DetailPanelComponent and add it some methods for opening/closing the modal then use that ref.

As this is not related to Quasar functionality, but to using Vue exclusively, I'd continue talks about your problem on the forum. Thanks!

**Comment by abacram** [comment]
Nice @rstoenescu, i have the destroyed instance in my code with the $off methods in order to unlink the Event, don't worry.

I'll try to investigate some more. Thanks for your help again, i appreciate it :)
