### ISSUE TITLE
[Types] Missing IconSets on type QuasarIconSets

### ISSUE THREAD

**Issue by susnux** [quasarframework/quasar#8746]
**Describe the bug**
The [`QuasarIconSets`](https://github.com/quasarframework/quasar/blob/05d22f400ce66a2cc5222e05b2bc78914dc3fd7a/ui/types/extras/icon-set.d.ts#L95) type is missing some more icons sets, e.g. `'mdi-v5'` is missing.
Also the `svg`-prefixed versions might missing.

Compare [types](https://github.com/quasarframework/quasar/blob/05d22f400ce66a2cc5222e05b2bc78914dc3fd7a/ui/types/extras/icon-set.d.ts#L95) with [available icon sets](https://github.com/quasarframework/quasar/tree/dev/extras#webfonts).

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.12.
