### ISSUE TITLE
Jest Import QPage

### ISSUE THREAD

**Issue by a-hardin** [quasarframework/quasar#8747]
**Describe the bug**
I am trying to test a QPage components. I have copied and pasted the exact code from [https://testing.quasar.dev/packages/unit-jest/#testing-qpage-components](https://testing.quasar.dev/packages/unit-jest/#testing-qpage-components) and changed: 
```
import PageIndex from './Index';

const factory = mountFactory(PageIndex, {
```

when I run the jest test:
`quasar test --unit jest`

i get the following error:
`Cannot find module './Index' from 'test/jest/__tests__/Index.spec.js'`

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/dank-shape-drmw8?file=/test/jest/__test__/Index.spec.js

**To Reproduce**
1. Go to the terminal
2. Navigate to the quasar project folder
3. In the terminal execute the following: 'quasar test --unit jest'

**Expected behavior**
In the terminal I would see the output of Test Suite passing, and I would not see an error stating 'Cannot find module './Index' from 'test/jest/__tests__/Index.spec.js'

**Screenshots**
![Screenshot from 2021-04-02 15-08-53](https://user-images.githubusercontent.com/25305805/113450530-ba65b480-93c5-11eb-87f7-adfec271b592.jpg)

**Platform (please complete the following information):**
Quasar Version: 1.15.9
@quasar/app Version: 2.2.3
Quasar mode: Dev

  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04LTS
Node: v10.19.0
NPM: 7.8.0
Yarn: n/a
Browsers: Chrome
iOS: n/a
Android: n/a
Electron: n/a

**Additional context**
None yet

**EDIT**
If I add the full path from my Ubuntu machine it will pass:
`import PageIndex from '/home/<user>/Documents/Work/Apps/jesttest/src/pages/Index.vue';`

**Comment by bazuka5801** [comment]
@a-hardin In most cases we should import all files with extension(our case '.vue')
And prodive full or relative or alias path to the file.

**Comment by hawkeye64** [comment]
@a-hardin I agree with @bazuka5801 , you need to update
```js
import PageIndex from './Index';
```
with the correct relative path
