### ISSUE TITLE
store-flag.d.ts file created in a Quasar CLI v2 beta project generated WITHOUT Typescript and WITH Vuex/Router/i18n

### ISSUE THREAD

**Issue by Ammamon** [quasarframework/quasar#8749]
store-flag.d.ts file created in a Quasar v2 beta project generated WITHOUT Typescript and WITH Vuex/Router/i18n

Steps to reproduce:

1)  quasar create vuex_without_typescript --branch next

2) Select the options shown below except Typescript

![image](https://user-images.githubusercontent.com/7417777/113469100-75df2500-9468-11eb-9d67-1e15ed012688.png)

3) When the project is generated, you won't see store-flag.d.ts file

4) But when running "quasar dev", you see the following console log

![image](https://user-images.githubusercontent.com/7417777/113469901-df623200-946e-11eb-8b2a-00f783187de4.png)

5) And after that, you see store-flag.d.ts file created under store folder.

![image](https://user-images.githubusercontent.com/7417777/113469139-e4bc7e00-9468-11eb-8dd0-94b3fdbbcbf9.png)

Don't know whether this is correct behaviour.

**Comment by rstoenescu** [comment]
Hi,

This is by design. It helps some IDEs at autocompletion. One example is VSCode.

**Comment by NYN1100** [comment]
the same problem happened
 with me.

**Comment by doox911-opensource** [comment]
Is it possible to change the place of generation of this type?

I need it to be generated to `./src/app/store` or `./src/shared/types`. I use vite.

**Comment by dsl101** [comment]
I know this is old, but it doesn't look like making this optional is on the horizon. One workaround until it can be configured in quasar.conf is adding this to `extendViteConf()`:
```
const fs = require('node:fs')
const path = require('node:path')

// ...

      extendViteConf (viteConf) {
        const tsGuff = path.join(__dirname, './src/stores/store-flag.d.ts')
        fs.stat(tsGuff, err => {
          if (err) return
          fs.unlink(tsGuff, () => {})
        })

      },

```
Of course in there you could also move it to where you need it but bear in mind it will still get regenerated in the original location on each build.
