### ISSUE TITLE
Quasar not work fine when "rerendered"

### ISSUE THREAD

**Issue by lyquocnam** [quasarframework/quasar#875]
Quasar not work fine when "rerendered"
i use roast.io for hosting and rerender service. demo: https://foregoing-view-289.roast.io/#/
- sidebar not hide when toggle.
- change route not work
-...
my source code: https://github.com/lyquocnam/quasar-house

**Comment by rstoenescu** [comment]
Please contact the prerendering team to sort this out. Not a Quasar issue.
One note: when using a static site web server you don't need to prerender your website. Simply serving the 'dist' folder will work.

**Comment by lyquocnam** [comment]
@rstoenescu i need SSR so i try using roast.io. can other way to do this ?

**Comment by rstoenescu** [comment]
SSR is in the roadmap: https://goo.gl/utPgbz

**Comment by lyquocnam** [comment]
awesome, thanks author ! i'm waiting for this. hope v0.15 will come soon

**Comment by ram-you** [comment]
@lyquocnam I think that SSR is not related specifically with v0.15 :(
