### ISSUE TITLE
In a Quasar v2 beta project without typescript, Vuex store getter is working, but NOT the action.

### ISSUE THREAD

**Issue by Ammamon** [quasarframework/quasar#8750]
In a Quasar v2 beta project without typescript, Vuex store getter is working, but NOT the action.

Steps to reproduce:

1) Create a Quasar v2 beta project
    quasar create vuex_without_typescript --branch next

2) Select  Vuex/Router/i18n options , but NOT Typescript

3)  Rename module-example folder to module-item

4) Update index.js under store for the changed module name

```
import { store } from 'quasar/wrappers'
import { createStore } from 'vuex'
import item from './module-item'
export default store(function (/* { ssrContext } */) {
  const Store = createStore({
    modules: {
      item
    },
    strict: process.env.DEBUGGING
  })
  return Store
})
```

5) Add the below code in Index.vue, action.js and getters.js

```
<script>
import { defineComponent, computed } from 'vue';
import { useStore  } from 'vuex';
export default defineComponent({
  setup(props) {
    const store = useStore()
    const something = computed(()  =>  store.getters['item/getSomething'])
    store.dispatch['item/postSomething']
    return {something};
  },
})
</script>
```
actions.js
```
export function postSomething (/* context */) {
    console.log("Reached here")
}
```
getters.js

```
export function getSomething (/* state */) {
    console.log("Reached here")
    return 30
}
```

Though I get output for getter function, action function is not being called.

**Comment by Ammamon** [comment]
If I use mapActions, it is working.

return {...mapActions('item', [ 'postSomething' ]), ...mapGetters('item', ['getSomething']),};

**Comment by Ammamon** [comment]
Able to use mapActions with typescript enabled project also.

I think I was naive enough to post my issue in the bug category.

Couldn't find any other category in the forum.

Can you please add another category where developers can post their questions on using the framework?

**Comment by metalsadman** [comment]
> Able to use mapActions with typescript enabled project also.
> 
> I think I was naive enough to post my issue in the bug category.
> 
> Couldn't find any other category in the forum.
> 
> Can you please add another category where developers can post their questions on using the framework?

Post questions in https://github.com/quasarframework/quasar/discussions or at the discord channel.
