### ISSUE TITLE
QSelect menu gets hidden when there's no option and a before-options slots exists

### ISSUE THREAD

**Issue by Melchyore** [quasarframework/quasar#8755]
**Describe the bug**
Hello!

I've created a custom filterable QSelect. For that, I'm using an QInput in the before-options slot. It doesn't use the native filter.

When I try to filter options, it works if the option(s) exist. But if the options don't match the filter value, the QSelect gets hidden... which is not the desired behavior because I can't even edit the filter value and the QSelect doesn't work anymore even if I click on it, the toggle icon changes but the list options is still hidden.

It was working fine on Quasar V1, so I think it's a bug.

**Codepen/jsFiddle/Codesandbox (required)**
Codesandbox won't run the application so here's my code:
```vue
<template>
  <q-select
    ref="select"
    v-model="selected"
    outlined
    dense
    hide-bottom-space
    :rules="rules"
    :input-debounce="0"
    :label="label"
    :options="allOptions"
    :disable="disable"
    @update:modelValue="onInput"
    @popup-show="onPopupShow"
  >
    <template #before-options>
      <q-input
        ref="filterElement"
        v-model="filter"
        filled
        stack-label
        label="Filter"
        @update:modelValue="filterFn"
      />
    </template>
  </q-select>
</template>

<script lang="ts">
  import { defineComponent, ref, watch, PropType, nextTick } from 'vue'

  import { QSelect, QInput } from 'quasar'

  type Selected = {
    label: string,
    value: string | number
  }

  export default defineComponent({
    name: 'FilterableQSelect',
    props: {
      value: {
        type: [Number, String, Array, Object],
        default: (): Selected => null
      },
      options: {
        type: Array as PropType<Array<Selected>>,
        default: (): PropType<Array<Selected>> => []
      },
      multiple: {
        type: Boolean,
        default: false
      },
      label: {
        type: String,
        default: ''
      },
      rules: {
        type: Array,
        default: (): Array<() => void> => []
      },
      disable: {
        type: Boolean,
        default: false
      }
    },
    emits: ['update:modelValue'],
    setup (props, { emit }) {
      const select = ref<QSelect>()
      const filterElement = ref<QInput>()

      const originalOptions = ref<Array<Selected>>(props.options)
      const allOptions = ref<Array<Selected>>(props.options)
      const selected = ref<Selected>(props.value)
      const filter = ref<string>('')
      const isOptionSelected = true

      watch(() => props.options, (newValue: Array<Selected>, oldValue: Array<Selected>) => {
        emit('update:modelValue', null)

        selected.value = null
        allOptions.value = newValue
        originalOptions.value = newValue
      })

      const onInput = () => {
        emit('update:modelValue', selected)

        if (filter.value) {
          allOptions.value = originalOptions.value
          filter.value = null
        }
      }

      const filterFn = (value: string): void => {
        if (value === '') {
          allOptions.value = originalOptions.value
        } else {
          const needle = value.toLowerCase()
          allOptions.value = originalOptions.value.filter((v: Selected) => v.label.toLowerCase().indexOf(needle) > -1)
          select.value.refresh(0)
        }
      }

      async function onPopupShow (): Promise<void> {
        await nextTick(() => {
          if (!selected.value) {
            filterElement.value.focus()
          }
        })
      }

      return {
        allOptions,
        selected,
        filterFn,
        filter,
        onInput,
        isOptionSelected,
        onPopupShow,
        select,
        filterElement
      }
    }
  })
</script>
```

**Expected behavior**
The QSelect menu should not hide when there's no options or where a before-options slot exists.

**Screenshots**
Even better, I made a video:

[Video](https://drive.google.com/file/d/1tZrDu6tadR7cFlwMtKGPAmDWFUcvWIlG/view)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 7
Node: Nodejs 14.7.0
NPM: 6.14.7
Yarn: 1.22.4
Browsers: Brave Browser
iOS:
Android:
Electron:

**Additional context**

**Comment by Melchyore** [comment]
Ok, the only workaround is to add another slot (no-option) and fill with with the same content as before-options slot but it's a dirty way to do it, I think, as it's a "workaround".

**Comment by rstoenescu** [comment]
Hi,

I'm sorry but before-options and after-options is only meant to be displayed when there are options available. Changing this behavior would introduce a breaking change -- which is a no-go.

You will indeed have to inject this into the no-option slot.
I hope you can understand that we cannot introduce a breaking change at this point.

**Comment by Setuini** [comment]
Hi
I am currently having the same use case as [Melchyore](https://github.com/Melchyore) and also solved it by adding my q-input to the before-options and no-options slot.<br>
It is a working but it's not pretty.

- Duplication of the input
- When the filter input returns no options the focus is lost because the other input is displayed

Would it be feasible to add a additional slot (something like 'menu-header') that is persistent no matter if options are present or not?

**Comment by ChristosTanailidis** [comment]
A bit late but...
As a better workaround (in my case) I added a watcher on the options (and my loading flag), I check if the new options length is greater than 0 and if the previous options length was 0 and also if my loading flag is false. If so, I hide and show immediately the popup. This will re-render the options menu and there is no need to change your `no-options` slot.

```
const qSelectRef= ref<QSelect>()

watch([() => props.loading, () => props.options], ([loading, options], [_, oldOptions]) => {
      if (bSelectRef.value && !loading && (!oldOptions.length && options.length)) {
        bSelectRef.value.hidePopup()
        bSelectRef.value.showPopup()
      }
    })
```

If this is applicable to your issue, its a bit more easy and less code repetitive.
