### ISSUE TITLE
Is there a icon property in the dialog plugn component?

### ISSUE THREAD

**Issue by besley** [quasarframework/quasar#8758]
The dialog plugin is very important to display some page interaction messages for software users. But there isn't a icon option to make a clear image for the friendly user experience. Can I suggest to enhance this feature? Some code is here below:

```
Dialog.create({
      title: 'Alert',
      icon: 'Warning',            //maybe to show some icons, especially colorful icons...
      message: message
    }).onOk(() => {
      // console.log('OK')
    }).onCancel(() => {
      // console.log('Cancel')
    }).onDismiss(() => {
      // console.log('I am triggered on both OK and Cancel')
    })
```

**Comment by pdanpdan** [comment]
And the icon should be displayed where? And using what color? And what size?

**Comment by besley** [comment]
![info](https://user-images.githubusercontent.com/2442853/113503033-077e8d80-9562-11eb-97b5-f6c8d612cb66.png)
![warning](https://user-images.githubusercontent.com/2442853/113503037-08afba80-9562-11eb-9fde-f3e2db60b34c.png)
![confirmation](https://user-images.githubusercontent.com/2442853/113503039-09485100-9562-11eb-9de4-0b5e6fba92c7.png)
![error](https://user-images.githubusercontent.com/2442853/113503041-09e0e780-9562-11eb-8c53-dbb7c70bdefd.png)

**Comment by metalsadman** [comment]
@besley use custom component https://quasar.dev/quasar-plugins/dialog#invoking-custom-component.

**Comment by rstoenescu** [comment]
The default dialogs are meant to be as simple as possible while providing the basic functionality. We do not plan to extend this provided functionality -- it would only bloat it and open a Pandora's box with continuous requests on it (some need the icon on the left, some need it on the right, some need it with a certain size, some need it on the title, etc etc etc... endless possibilities). We do not want to transform the basic functionality into a monster with 1000 properties. For custom use cases that are not matched by these dialogs, you can create your own through custom components (like mentioned above) then reuse them over and over again. That's their purpose anyway.

**Comment by evil-shrike** [comment]
Hi @rstoenescu, I understand your point, but look at the notify plugin:
```
          $q.notify({
            color: 'negative',
            message: 'Loading failed',
            icon: 'report_problem'
          });
```
it has a quite similar API but it does allow showing `icon` without opening any Pandora box.
Icons in dialogs is a common functionality that everyone would except to find an API. Just look at the win32 API.

And you didn't ask the same questions about message - what font, color and size we should use. Same for icon. Just take meaningful defaults. That would be enough. For complex cases as you said there're custom components.
