### ISSUE TITLE
Vuex and Vue router are not autoimported

### ISSUE THREAD

**Issue by LadIQe** [quasarframework/quasar#8759]
**Describe the bug**
Im not getting autoimport option when using packages like vuex, vue-router. I tried to use GetterTree, ActionTree etc, but none of them was autoimported. When I tried to import it manualy, there is no option for vuex and vue-router in import

**To Reproduce**
1. create new v2 project with quasar-cli
2. go to store/<module>/actions | getters | mutations | index | whatever
3. typing MutationTree | ActionTree | whatever from vuex are not autoimported, even manual import is not giving option for them
4. same for vue router in vue component

**Expected behavior**
Autoimport Types, Interfaces, functions etc from vuex, vue router

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta11
@quasar/app Version: 3.0.0-beta10
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS Big Sur
Node: 14.15
NPM:
Yarn: 1.22.10
Browsers: Chrome / Safari
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
The autoimport feature in Quasar refers to Quasar components and directives only.
