### ISSUE TITLE
[Request] Allow opening Modal via v-model

### ISSUE THREAD

**Issue by fnicollier** [quasarframework/quasar#876]
Currently modals require using "ref" in order to be opened by a parent component.
This complicates things and adds strong dependencies between components.
Looking at Vuetify.js they have an approach where binding via v-model on a boolean opens and closes the dialog and this seems much more flexible and removes the need to use the "ref" attribute.

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.4.

**Comment by rstoenescu** [comment]
Modals, Popovers and Tooltips now support v-model in edge and future v0.14.4.

**Comment by fnicollier** [comment]
Fantastic! Thanks!

**Comment by rstoenescu** [comment]
Added "v-model" support for QFab too. -- edge and future v0.14.4
