### ISSUE TITLE
quasar-v2.0.0-beta.12 | Parsing error: ',' expected in quasar.conf.js -> line (125:6)

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#8767]
Hello,
Thank you for the enormous effort you make to provide us with this wonderful framework.

**Describe the bug**
When creating a new project  with command :
`quasar create <project_name> --branch next`

there is a small oversight in the config file "quasar.conf.js" in line (125:6)

```
125:6  error  Parsing error: ',' expected

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

part of the code concerned : 

```javascript
  ssr: {
      pwa: false,
      // manualStoreHydration: true,
      prodPort: 3000, // The default port that the production server should use
                      // (gets superseded if process.env.PORT is specified at runtime)

      maxAge: 1000 * 60 * 60 * 24 * 30,
        // Tell browser when a file from the server should expire from cache (in ms)

      chainWebpackWebserver (/* chain */) {
        //
      }  //<---------------------------------------------------------------------  ( add ' , ' ) 

      middlewares: [
        ctx.prod ? 'compression' : '',
        'render' // keep this as last one
      ]
    },
```
a small comma is missing 

**Platform (please complete the following information):**
Quasar Version:  quasar-v2.0.0-beta.12
@quasar/app Version: @quasar/app-v3.0.0-beta.11

OS:
Node: v15.11.0
NPM: 7.6.3
Yarn: 1.22.10

Thank you again for your responsiveness.

**Comment by rstoenescu** [comment]
Fixed. Thanks for reporting.
