### ISSUE TITLE
Minor issue, dev server opens browser page two times in ssr mode.

### ISSUE THREAD

**Issue by ejez** [quasarframework/quasar#8772]
Many thanks for the hard work on ssr!

**To Reproduce**
```sh
quasar create my-app  --branch next
cd my-app
quasar dev -m ssr
```

**Expected behavior**
Only one browser page should be opened.

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.12
@quasar/app Version: v3.0.0-beta.11
Quasar mode:
  - [x] SSR

**Additional context**
The first browser page is opened when the server is not ready yet.
![20210405_12h07m10s](https://user-images.githubusercontent.com/48388358/113557967-87126800-9607-11eb-9b2f-7514b22f0404.png)

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fixed in "@quasar/app" v3.0.0-beta.13
