### ISSUE TITLE
babel-plugin-prismjs  doesn't work in  Quasar Cli !

### ISSUE THREAD

**Issue by q350241636** [quasarframework/quasar#8774]
**I try to use prismjs to hightlight my code block;**
But it doesn't load  prismjs's css and prismjs's plugins;

Here is my babel.config 

`/* eslint-env node */
module.exports = {
  presets: ['@quasar/babel-preset-app'],
  plugins: [
    [
      'prismjs',
      {
        languages: [
          'html',
          'css',
          'javascript',
          'php',
          'dart',
          'bash',
          'nginx',
          'sql',
          'c',
          'cpp',
          'python',
          'go',
          'java'
        ],
        plugins: [
          'line-numbers',
          'show-language',
          'copy-to-clipboard',
          'inline-color'
        ],
        theme: 'okaidia',
        css: false
      }
    ]
  ]
};
`
The same config is worked  in vue-cli;

**Comment by rstoenescu** [comment]
Why use a babel plugin for this??
Just yarn/npm install prismjs and import it in a boot file...
