### ISSUE TITLE
Allow stamp to be extended using a slot on QChatMessage Component

### ISSUE THREAD

**Issue by marcorivm** [quasarframework/quasar#8779]
**Is your feature request related to a problem? Please describe.**
While using the QChatMessage component it's a great way to show user messages on the interface, I have found that the stamp feature lacks some details that I think are important, like being able to show the actual message time when hovering over the time ago timestamp.

**Describe the solution you'd like**
Extend the QChatMessage to allow the stamp section to be customized using a slot like we can do for the avatar and message sections.

**Describe alternatives you've considered**
It's possible to prepare each message with an html rich stamp that can be used with the stamp-html attribute, but this becomes cumbersome as the stamp template get's complicated, users might be more familiar with using slots than building their own html markup  for injecting.

**Additional context**
I have started working on this here https://github.com/marcorivm/quasar/commit/d7b8b44dd5d3530f601ac95a2a2661685f76edff it's still a WIP but I would like your input into if this is something that could be merged as a feature

**Comment by rstoenescu** [comment]
"stamp" (and "name") slots added in Quasar v1.15.14 and Quasar v2.0.0-beta.16
