### ISSUE TITLE
Quasar Dev webserver crash during Qualys Vulnerability Scanning

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#8781]
When the "Qualys dev" webserver is hit with a specific path from a server vulnerability scanner, it crashes with the following error:

  URIError: Failed to decode param '/%NETHOOD%/'

  - decodeURIComponent

  - layer.js:172 decode_param
    [space]/[express]/lib/router/layer.js:172:12

  - layer.js:123 Layer.match
    [space]/[express]/lib/router/layer.js:123:27

  - index.js:574 matchLayer
    [space]/[express]/lib/router/index.js:574:18

  - index.js:220 next
    [space]/[express]/lib/router/index.js:220:15

  - init.js:40 expressInit
    [space]/[express]/lib/middleware/init.js:40:5

  - layer.js:95 Layer.handle [as handle_request]
    [space]/[express]/lib/router/layer.js:95:5

  - index.js:317 trim_prefix
    [space]/[express]/lib/router/index.js:317:13

  - index.js:284 
    [space]/[express]/lib/router/index.js:284:7

  - index.js:335 Function.process_params
    [space]/[express]/lib/router/index.js:335:12

  - index.js:275 next
    [space]/[express]/lib/router/index.js:275:10

  - query.js:45 query
    [space]/[express]/lib/middleware/query.js:45:5

  - layer.js:95 Layer.handle [as handle_request]
    [space]/[express]/lib/router/layer.js:95:5

  - index.js:317 trim_prefix
    [space]/[express]/lib/router/index.js:317:13

  - index.js:284 
    [space]/[express]/lib/router/index.js:284:7

  - index.js:335 Function.process_params
    [space]/[express]/lib/router/index.js:335:12

events.js:186
      throw er; // Unhandled 'error' event
      ^

[  Error: read ECONNRESET

  - stream_base_commons.js:201 TCP.onStreamRead
    internal/stream_base_commons.js:201:27

Emitted 'error' event on Socket instance at:

  - destroy.js:91 emitErrorNT
    internal/streams/destroy.js:91:8

  - destroy.js:59 emitErrorAndCloseNT
    internal/streams/destroy.js:59:3

  - task_queues.js:80 processTicksAndRejections
    internal/process/task_queues.js:80:21

] {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

Not sure if this is something you can fix in the cli or something I need to report in another repository.   Let me know....

Thanks!

**Comment by Lou-Der** [comment]
Sorry, forgot to mention the environment:

Operating System - Windows_NT(10.0.18363) - win32/x64
NodeJs - 12.10.0

Global packages
  NPM - 6.10.3
  yarn - Not installed
  @quasar/cli - 1.1.3
  cordova - Not installed

Important local packages
  quasar - 1.11.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.0.4 -- Quasar Framework local CLI
  @quasar/extras - 1.8.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.4.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.10.4 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.9.5 -- TypeScript is a language for application scale JavaScript development

**Comment by pdanpdan** [comment]
I don't think you have to report it anywhere. It's a vulnerability scanner and the response of express is quite correct.
