### ISSUE TITLE
tabs in q-modal-layout

### ISSUE THREAD

**Issue by BMahier** [quasarframework/quasar#879]
### Software version

Quasar: 0.14.1
OS: iOS (via cordova)
Node:
NPM:
Browsers:
iOS: 
Android:
Any other software related to your bug:

### What did you get as the error?
Using q-tabs in a modal, my tabs would always stretch my modal instead of being scrollable when being too large for the modal.

### What were you expecting?
I was expecting the tab bar to be scrollable when its content were too large to show everything, as I can see in Android and web browser

### What steps did you take, to get the error?
Here's some code to show you my error:
```  
<q-modal-layout>

    <!--Header, footer -->

    <q-tabs inverted v-if="$store.state.currentSite">
      <q-tab v-for="test in 10" :key="test" slot="title" @select="onTestSelected(test.name)">{{test.name}}</q-tab>
    </q-tabs>

</q-modal-layout>
```

If I'm using q-layout instead of q-modal-layout, it's working properly.

**Comment by rstoenescu** [comment]
Misuse. Please check Tabs documentation and QTab syntax/props/usage. Thanks.
