### ISSUE TITLE
public config js do not work

### ISSUE THREAD

**Issue by PongChen** [quasarframework/quasar#8790]
before build my public folder
![image](https://user-images.githubusercontent.com/21305978/113677342-0e3b0b00-96f0-11eb-89df-19be2d8d5fb3.png)

after build
![image](https://user-images.githubusercontent.com/21305978/113677291-ffecef00-96ef-11eb-839f-2ca54ff47dc4.png)

some js code writen in the ./config/config.js

while build it does not read from the dist/config/config.js

and that code was build in other js file

do i miss any operation?  Look forward to your reply ， thanks

**Comment by PongChen** [comment]
![image](https://user-images.githubusercontent.com/21305978/113678395-28c1b400-96f1-11eb-8858-566bccf069c3.png)
it used at boot/config.js
![image](https://user-images.githubusercontent.com/21305978/113678571-60306080-96f1-11eb-8ef1-72512d4eaf0f.png)

then  config at 
![image](https://user-images.githubusercontent.com/21305978/113678551-56a6f880-96f1-11eb-9fd8-c9ebd557ffed.png)

**Comment by pdanpdan** [comment]
#8469
