### ISSUE TITLE
Input bgColor and text color conflict when set color to white and set inverted.

### ISSUE THREAD

**Issue by Bangood** [quasarframework/quasar#880]
### Software version

Quasar:latest

hi, when i write `<q-input inverted color="white"/>`.

the input text disappers, because the text color is white, how can i fix it.

I hava try to set class="text-red"， but useless.

**Comment by rstoenescu** [comment]
White is the only color that cannot be used along with inverted. Is this a breaking point in your app? I want to keep component's code as light as possible and not add another prop to handle this corner case if possible.

What I would do instead is in your app I'd add the following:
`<q-input inverted color="white" class="my-inverted".....`
```css
.my-inverted .q-if-inner input {
   color: black !important;
}
```

Let me know how it goes. Thanks!

**Comment by rubnvp** [comment]
when set to white also hide the icon and the loading spinner... so I had to add .q-if-control too
```
.my-inverted .q-if-inner input,
.my-inverted .q-if-control {
    color: black;
}
```
but then, the placeholder was also hidden, so in the end the best solution was to just remove the inverted and color properties and add the same input inverted style:
```
.my-inverted  {
    min-height: 38px;
    border-radius: 2px;
    padding-top: 8px;
    padding-left: 8px;
    padding-right: 8px;
    -webkit-box-shadow: 0 1px 3px rgba(0,0,0,0.2), 0 1px 1px rgba(0,0,0,0.14), 0 2px 1px -1px rgba(0,0,0,0.12);
    box-shadow: 0 1px 3px rgba(0,0,0,0.2), 0 1px 1px rgba(0,0,0,0.14), 0 2px 1px -1px rgba(0,0,0,0.12);

    &:after{
        display: none; /* hide the .q-if:after */
    }
}
```

maybe this should be warned in the doc: http://quasar-framework.org/components/input.html#Vue-Properties
