### ISSUE TITLE
The last issue was closed but not resolved.

### ISSUE THREAD

**Issue by jtlindsey** [quasarframework/quasar#8802]
The last issue was closed but not resolved.
https://github.com/quasarframework/quasar/issues/8695#issuecomment-814517181

**Comment by antonio-piha** [comment]
If there's no `.env` file, then `require('dotenv').config().parsed` returns `undefined`
And if used in that form it won't throw an error like this one:
```
error: Error: ENOENT: no such file or directory, open 'D:\PROJEKTI\SignalsDashboard\frontend-quasar-app\.env'
      at Object.openSync (fs.js:476:3)
      at Object.readFileSync (fs.js:377:35)

```
Only if it's used like this for the first time `require('dotenv').config()` (without `.parsed`).

In `quasar.conf.js`
```
    build: {
      env: require('dotenv').config().parsed,
```
will become:
```
build: {
    env: undefined
```
because `quasar.conf.js` will be loaded before `extensions.js` where you're using it like this `require('dotenv').config()` but then it's just skipped because the module is already loaded and cached.

Happens on node version 14.
Are you sure you have `.env` file in production?

**Comment by jtlindsey** [comment]
Sorry, i thought it was obvious `.env` are usually not commited....default `.gitignore`. From the last issue, dev works. If dev isn't working for you, you need to create `.env` and add VAL=something.

I'm testing dev and production on the same machine by simply running `npm run dev` to test dev or `npm run build && npm start` to test production. Dev works, so `.env` is good since https://github.com/jtlindsey/quasar-broken-ssr-env/blob/2134c04f5fe66c1ef5dce5c2f879999992c7e5ab/src-ssr/extension.js#L15 didn't throw error.

**Comment by rstoenescu** [comment]
I think this can be closed?

**Comment by jtlindsey** [comment]
> I think this can be closed?

Is this a joke @rstoenescu ? If not, then why close a thread about a unresolved problem?

I provided you a repo with minimal needed to reproduce the issue. I explained how to reproduce the issue and answered questions about the problem. You closed the first issue without confirming if you resolved the problem. Then i updated the repo to make it clear the problem hasn’t been resolved after you changed the docs and posted a copy of the doc reference. Then on the follow up issue you say “i think this can be closed” with a question mark (usually used for questions) and immediately close the thread without addressing the issue. The bug is still there. You can see from the thread above you need to add your .env to see the issue.

**Comment by rstoenescu** [comment]
@jtlindsey Apologies. I keep on forgetting that this was reported for Quasar v1. (This is fixed in Quasar v2 through the new architecture with ssr middlewares)

Will see what I can do about v1 without making any breaking changes.

**Comment by jtlindsey** [comment]
> @jtlindsey Apologies. I keep on forgetting that this was reported for Quasar v1. (This is fixed in Quasar v2 through the new architecture with ssr middlewares)
> 
> Will see what I can do about v1 without making any breaking changes.

Thank you. I didn’t realize what was going on and that it was fixed in v2. I only have 1 quasar app that doesn’t have all the backend services with sensitive environment variables handled in a completely separate app/api. I think the only use case people will see this issue is using ssr and not hard coding sensitive information. 

With v2 around the corner and priority, I can understand if closing as “wont fix in v1” given there’s no simple fix.

**Comment by yusufkandemir** [comment]
[Quasar v1 is EOL](https://github.com/quasarframework/quasar/discussions/15229), so I am closing this issue.
