### ISSUE TITLE
Hydration text content mismatch

### ISSUE THREAD

**Issue by yanghuilong** [quasarframework/quasar#8805]
**Describe**
Vue warn]: Hydration text content mismatch in <span>:
- Client: test{
  "prop": false,
  "test": "test"
}
- Server: {
  "prop": false,
  "test": ""
} 
  at <Index2 onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
undefined
> > 
  at <RouterView> 
  at <App> 

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/suspicious-leaf-lbqjd?file=/src/pages/Index2.vue

**To Reproduce**
1. Go to router '/index2'
2. See error

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.0.0-beta.12
Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Comment by yanghuilong** [comment]
const storeInitialState = window.__INITIAL_DATA;
if (storeInitialState) {
  store.replaceState(storeInitialState);
}
There is a problem with this place, in vue3

**Comment by rstoenescu** [comment]
Confirmed. Fixing in next release.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix is available in "@quasar/app" v3.0.0-beta.15
