### ISSUE TITLE
@electron/remote support

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar#8806]
"@quasar/app": "^3.0.0-beta.1"
  "electron": "^12.0.2"

![image](https://user-images.githubusercontent.com/19922265/113805997-1d739480-9794-11eb-981b-ee0b87a6f5dd.png)

https://github.com/electron/remote

```js
// Before
const { BrowserWindow } = require('electron').remote

// After
const { BrowserWindow } = require('@electron/remote')
```

Support new version of remote module

**Comment by rstoenescu** [comment]
Docs pages have been updated with examples using `@electron/remote` instead of the deprecated `remote`. Will be available on next deployment.
