### ISSUE TITLE
Why no "en" in Quasar Language Packs?

### ISSUE THREAD

**Issue by flopail** [quasarframework/quasar#8810]
**Is your feature request related to a problem? Please describe.**
Hi! :) Is there a special reason to have `en-us` and `en-gb` but no `en` in Quasar Language Packs? Thanks.

**Describe the solution you'd like**
It could be quite useful to have `en` in order to use it as in vue-i18n implicit fallback:  [https://kazupon.github.io/vue-i18n/guide/fallback.html#implicit-fallback-using-locales](https://kazupon.github.io/vue-i18n/guide/fallback.html#implicit-fallback-using-locales)

**Describe alternatives you've considered**
For now, I use `en-gb` as locale and `en-us` as fallbackLocale in `src/boot/i18n.js`. But it seems to me that logic is to go from the more specific locale (territory or dialect: `en-gb` for example), to the more global one (`en`).

**Comment by Smrtnyk** [comment]
en can be anything, even english in india
