### ISSUE TITLE
Specific NODE_ENV in build

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#8815]
**Is your feature request related to a problem? Please describe.**
I have been use qenv, but now it's deprecated so I moved to `dotenv-flow`, but seems like only can have development and production enviroments with quasar, I need a staging build.

In dev is NODE_ENV development, in build is forced to production, so I can't specific other enviroments.

**Describe the solution you'd like**
As qenv allows, specific NODE_ENV vars, or something more than `production` or `development` build

**Describe alternatives you've considered**
Use Qenv or make some strange process to load the vars with another var then NOVE_ENV

**Comment by hawkeye64** [comment]
@Nisgrak Look at the code for qenv and do something similar. You could even create your own js file and then import it into quasar.conf.js
