### ISSUE TITLE
q-pagination doesn't support zero-values (:min="0")

### ISSUE THREAD

**Issue by Dealerpriest** [quasarframework/quasar#8817]
**Describe the bug**
q-pagination component doesn't handle values of 0. Setting the min prop to for example 0, won't allow the component to change the v-modelled value when clicking the 0-button

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/dealerpriest/pen/OJWOyRX](https://codepen.io/dealerpriest/pen/OJWOyRX)

**To Reproduce**
1. Go to the codepen
2. Click on 1 in pagination.
3. Click on 0 in pagination.

**Expected behavior**
Change the value to 0 if clicking the 0-button

**Platform (please complete the following information):**
Quasar Version: v1.15.10
@quasar/app Version: v1.9.6

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.11
