### ISSUE TITLE
[Request] Support for v-model "lazy" modifier

### ISSUE THREAD

**Issue by daveline** [quasarframework/quasar#882]
### Software version

Quasar: v0.14.4
OS: Win10x64
Node: v6.9.2
NPM: 3.10.9
Browsers: Chrome 61.0.3163.79/Edge
Any other software related to your bug:

### What did you get as the error?
Typing in a q-input field with the lazy modifier is firing change events and syncing data.

### What were you expecting?
This isn't consistent with the desired behavior of the Vue lazy modifier. Adding the lazy modifier should instead fire the change event and sync data only after you leave the field.
https://vuejs.org/v2/guide/forms.html#lazy

### What steps did you take, to get the error?
Run the following code and notice how "myData" changes and the events are logged to the console while typing. Compare the q-input vs the traditional HTML/Vue input. 

```
<template>
  <div>
    <h3>"{{ myData }}"</h3>
    <h3>q-input</h3>
    Normal: <q-input type="text" v-model="myData" @input="input" @change="change" /><br>
    Lazy: <q-input type="text" v-model.lazy="myData" @input="input" @change="change" /><br>
    Trim: <q-input type="text" v-model.trim="myData" @input="input" @change="change" /><br>
    <h3>html/vue input</h3>
    Normal: <input type="text" v-model="myData" @input="input" @change="change" /><br>
    Lazy: <input type="text" v-model.lazy="myData" @input="input" @change="change" /><br>
    Trim: <input type="text" v-model.trim="myData" @input="input" @change="change" /><br>
  </div>
</template>

<script>

import {
  QField,
  QInput
} from 'quasar'

export default {
  name: 'Lazy',
  components: {
    QField,
    QInput
  },
  data () {
    return {
      myData: 'abc'
    }
  },
  methods: {
    change () {
      console.log('myData change')
    },
    input () {
      console.log('myData input')
    }
  }
}
</script>
<style >

</style>
```

**Comment by buccfer** [comment]
+1

I have the same issue.

**Comment by dsl101** [comment]
Will it be possible to combine `.trim` and `.lazy`? I mentioned this on gitter some time ago that typing into a q-input with `.trim` gives surprising results when you delete a word in that it also deletes the space. Perhaps `.trim` should even _imply_ `.lazy`?

Try typing "First Second", then deleting back to make it say "First Third". Unless you're _very_ careful and watching, you'll end up with "FirstThird" (no space).
