### ISSUE TITLE
Quasar CLI does not generate new components in the proper location

### ISSUE THREAD

**Issue by ovidiuc** [quasarframework/quasar#8821]
**Describe the bug**
Related to the command `quasar new <c|component> [-f <option>] <component_file_name>`

New component is generated in the `components` directory (relative to root of the project), not in `src/components`

**Codepen/jsFiddle/Codesandbox (required)**
N/A

**To Reproduce**
1. Go to console
2. Run ` quasar new c SomeComponent`
3. A new directory `components` is created relative to the root of the project, which contains the new component.

Output:
```
App · Generated component: components/SomeComponent.vue
```

**Expected behavior**
Create the new component in the `src/components` directory.

**Screenshots**
N/A

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.12
@quasar/app Version: v3.0.0-beta.13
@quasar/cli Version: v1.1.3
Quasar mode:
  - [*] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [*] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Debian GNU/Linux 9 (Docker)
Node: v14.15.1
NPM:
Yarn: 1.22.5
Browsers:
iOS:
Android:
Electron:

**Additional context**

It started happening following one of the latest upgrades, as it used to work fine.

Workaround:
```
quasar new c ../src/components/SomeComponent
```

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v3.0.0-beta.14
