### ISSUE TITLE
Support for Chrome extensions Manifest V3 (MV3)

### ISSUE THREAD

**Issue by thdoan** [quasarframework/quasar#8822]
**Is your feature request related to a problem? Please describe.**

It's not related to a current problem, but it could be a problem down the road for BEX when MV3 is enforced and MV2 is deprecated.

**Describe the solution you'd like**

You should start looking at migrating BEX to the MV3 platform.  More information below:

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by saveroo** [comment]
Any news regarding this?

**Comment by gaoliang** [comment]
Any progress?

**Comment by gaoliang** [comment]
According to https://developer.chrome.com/blog/mv2-transition/

- January 17, 2022: New Manifest V2 extensions will no longer be accepted by the Chrome Web Store. Developers may still push updates to existing Manifest V2 extensions, but no new Manifest V2 items may be submitted.

- January 2023: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

**Comment by jra11** [comment]
Hi,

Same issue, my BEX is ready but I cannot upload it.

Is there a workaround? Can I modify the manifest.json manually according to the V3 requirements or does V3 have an impact on the compilation or Quasar components? 

Many thanks

**Comment by thdoan** [comment]
@jra11 complying to MV3 is more involved than updating manifest.json. The Quasar team will have to go through this checklist: https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/

**Comment by jra11** [comment]
@thdoan Many thanks. So I don't try anything for now, I don't have the needed knowledge to do it. 

May I suggest putting a big red warning in the doc to say that current BEXs cannot be published on the Chrome web store? 

Some people may develop a BEX for their client, and have a very bad surprise when trying to publish it. Can be really a nightmare to manage. (not my case, fortunately). 

I am opened to test any migrating process for my BEX, even if it's informal/ugly, if it can help.

**Comment by zxqp** [comment]
I am unable to publish after building it.
Please migrate from v2 to v3

**Comment by jra11** [comment]
@zxqp I guess it is not "so easy", it's more than a migration.

I reviewed the source code of Qasar to see if I can do it myself. It seems doable, but the main issue is that you'll need two manifest.json, one for v2 and the other for v3. Why? Because Firefox does not support v3 yet! 

Quasar devs may want to wait for the support of v3 from Firefox to avoid too much work (eg managing two different configurations) that would be totally useless in a few weeks/months.

Google is a shame, they did things far too quickly.

**Comment by rstoenescu** [comment]
Implemented this for Quasar v2 with the upcoming Quasar CLI on Vite (unreleased as of writing these lines though).
When spawning the BEX mode it will ask you which manifest version you'd like.

**Comment by osarhan** [comment]
> Implemented this for Quasar v2 with the upcoming Quasar CLI on Vite (unreleased as of writing these lines though). When spawning the BEX mode it will ask you which manifest version you'd like.

Any insight on release dates?

**Comment by rstoenescu** [comment]
@osarhan It's already released as mentioned. Use Quasar CLI with Vite and add bex mode with it. It'll ask which version of manifest you want.
