### ISSUE TITLE
Video on Parallax page does not play in Safari

### ISSUE THREAD

**Issue by enedrio** [quasarframework/quasar#8826]
When viewing this page in Safari https://quasar.dev/vue-components/parallax
the video example does not play.

When loading the video link individually in Safari the video does load but sometimes produces funny colors, like in the screen shot.
<img width="782" alt="funny video colors" src="https://user-images.githubusercontent.com/3957174/114144584-c85f8c00-9915-11eb-8408-a4e900ea327f.png">

When I copy the parallax video code into a quasar spa the video does play in Safari, but still produces funny colors sometimes. 

Is something wrong with the mp4 file here, or just another Safari madness?
In Chrome and Firefox everything works fine.

**Comment by hawkeye64** [comment]
I am not totally sure, but based on your image above this looks more like a codec issue. I wonder if Safari uses a different codec than Chrome or FF?

**Comment by rstoenescu** [comment]
Closing as it's not a Quasar issue.
