### ISSUE TITLE
QToggle and QCheckbox native form submit does not work

### ISSUE THREAD

**Issue by maddogcz** [quasarframework/quasar#8829]
**Describe the bug**
'name' prop does not get transfered to native 'input' element, so the value cannot get to submitted data.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/maddogcz/pen/xxgPNBW?editors=1010

**To Reproduce**
1. Click on submit
2. See result below: only value from radio input gets to form data, values from checkbox and toggle don't

**Expected behavior**
Values from checkbox/toggle get to form data

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.12
@quasar/app Version:
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 18.4
Node: 15.11
NPM:7.6
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Thanks for reporting!
Will be fixed in v2.0.0-beta.18.
