### ISSUE TITLE
Q-uploader limit file size?

### ISSUE THREAD

**Issue by ssuess** [quasarframework/quasar#883]
It would be great if the uploader component allowed limiting the file size...

**Comment by KaisNeffati** [comment]
It would be great also to set the number of files to upload

**Comment by aleksandrmelnyk** [comment]
Yep, limit of size and limit of num files are really missed

**Comment by rstoenescu** [comment]
Will do.

**Comment by valeriancure** [comment]
@rstoenescu FYI these will be included in my next PR (this week) 👍

**Comment by slowaways** [comment]
Change the title of this Issue to: "[Request] Q-Uploader - limit file size

**Comment by smolinari** [comment]
@valeriancure - did you work on this? 

Scott

**Comment by BenHayat** [comment]
Will it be in V1?

Thanks!

**Comment by rstoenescu** [comment]
Done for v1.0.
