### ISSUE TITLE
QTable with Vitual scroll, the scroll event is emitting infinitely 

### ISSUE THREAD

**Issue by axe-me** [quasarframework/quasar#8832]
**Describe the bug**
QTable with Vitual scroll, the scroll event is emitting infinitely 

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/upbeat-sound-5u9h2?file=/src/components/HelloWorld.vue

**To Reproduce**
1. Open the console to see the infinite logs

**Expected behavior**
event stop emit after table filled with data

**Platform (please complete the following information):**
Quasar Version: 2.0 beta 12
@quasar/app Version:
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
The scroll event is emitted. You change the data so component re-renders. It emits the event again, repeating the cycle hence your infinite loop. It's not Quasar, it's how you handle it.

Also, doing intensive work on a scroll event is far from ideal. The scroll event is fired many times. You probably don't even finish executing the first handle that there's already many more scheduled. The fact that you async/wait doesn't mean everything else outside of it will wait for it to be finished.

A good practice would be to use the debounce util, at least. But changing the rows mid-way is definitely a no-go. It's like standing in a tree and cutting the branch you're standing on.

**Comment by axe-me** [comment]
you are right, it is the rerender trigged the emit. 

I guess the right thing I need is the infinite scroll instead of the virtual scroll. any plans to integrate it into QTable?
