### ISSUE TITLE
exportFile charset

### ISSUE THREAD

**Issue by ziltonvasconcelos** [quasarframework/quasar#8847]
I am using exportFile Utils from quasar

https://quasar.dev/quasar-utils/other-utils

but I cannot set charset for the csv file...any idea how?

thanks,
Zilton.

**Comment by rstoenescu** [comment]
Third parameter of exportFile(). Set it to something like: `text/plain;charset=utf-8`.

**Comment by rstoenescu** [comment]
Also, if you started a Discussion on it, please don't duplicate the thread by opening a ticket also. This doesn't speed up you getting an answer.
