### ISSUE TITLE
Support for aria-invalid in form fields

### ISSUE THREAD

**Issue by jippeholwerda** [quasarframework/quasar#8884]
In order to comply with WCAG 2.1, it would be nice to use the aria-invalid attribute for form validation. Perhaps in combination with aria-required?

See for more information:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute
- https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA21.html

**Comment by rstoenescu** [comment]
Improvement will be available in Quasar v2.0.3 and v1.15.23.
