### ISSUE TITLE
Incompatibility with workbox v6

### ISSUE THREAD

**Issue by kefniark** [quasarframework/quasar#8892]
**Describe the bug**
Just for information, and also because I wasted few hours on it 😄 

I was trying to understand why suddenly my PWA app offline mode was not working anymore.
Figured that a recent upgrade of workbox by one of my coworker kinda worked, but also started to generate wrong `service-worker.js`

This break precache of CSS and JS (so probably related to webpack) and make PWA not available offline

![image](https://user-images.githubusercontent.com/4903529/114677272-1aa11280-9d45-11eb-8608-e00abce1fd10.png)

All those files with file-content = 0, it's because those files do not exist on the server with those hashes. File hashes in the build and in the service-worker do not match.

So I suppose something in the quasar quasar build process is not working anymore

With workbox v5

```txt
[
{'revision':'df54bf315dcdc68443930d05b8953646','url':'/js/app.0a9c4114.js'},
{'revision':'61c6fc419ada393a95dd6335ba9aa623','url':'/js/vendor.71fe3b3f.js'}
]
```

With workbox v6 (revision: null and wrong hashes, files in the build folder are different)

```txt
[
{'revision':null,'url':'/js/app.0a9c4114.js'},
{'revision':null,'url':'/js/vendor.71fe3b3f.js'}
]
```

**To Reproduce**
1. Create a new PWA project
2. Set it up in `InjectManifest`
3. Setup a basic `custom-service-worker.js`
with
```js
import { precacheAndRoute } from 'workbox-precaching'
precacheAndRoute(self.__WB_MANIFEST || [], {})
```
4. Build for PWA -> the `service-worker.js` content should be OK
5. npm install --save-dev workbox-webpack-plugin@6.1.5
6. Build for PWA -> the `service-worker.js` content is wrong

**To Solve**
`npm install --save-dev workbox-webpack-plugin@5.1.4`

**Expected behavior**
The precache should work, even in recent version of workbox

Or the build process should throw an error/warning

**Platform:**
Quasar Version: v1.15.10
@quasar/app Version: v2.2.4

Quasar mode:
  - [x] PWA

Tested on:
  - [x] PWA

OS: Windows, Docker
Node: 12.20.2
NPM:  6.14

**Comment by yusufkandemir** [comment]
[Quasar v1 is EOL](https://github.com/quasarframework/quasar/discussions/15229), so I am closing this issue.

With Quasar v2, especially with Quasar CLI with Vite, the PWA mode has been drastically improved. So, this should no longer be an issue. If there is an issue with Quasar v2, please open a new issue.
