### ISSUE TITLE
Add focus() methods & handling to QScrollArea

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#8893]
**Is your feature request related to a problem? Please describe.**
It seems hard to make layouts using QScrollArea keyboard-accessible, since it's hard to point keyboard input to the scroll area directly (e.g. via a shortcut key).

**Describe the solution you'd like**
A method in QScrollArea to set the current focus for keyboard input (specifically arrow keys to scroll up / down).

**Describe alternatives you've considered**
Setting a ref on the QScrollArea, then using things like `this.$refs.scrollArea.$el.firstChild.focus()`, but it seems quite brittle if QScrollArea was ever to change. In fact, it doesn't seem to work in Chrome at all for some reason, but does on Firefox.

**Comment by pdanpdan** [comment]
The scrolling element of QScrollArea will not be focusable if there will be no tabindex attribute on it.
One simple solution would be a focusable element in the content, or a focusable wrapper around the content:
https://codepen.io/pdanpdan/pen/bGgMxZq?editors=1010

**Comment by dsl101** [comment]
According to most accessibility guides I’ve read, you shouldn’t use
tabindex on non-interactive elements (like buttons, input areas, etc.). I’m
not sure if a scroll area counts as interactive, but I found adding
tabindex and directly focusing didn’t work as expected in chrome anyway.

I’ll make a simple codepen to experiment with.

**Comment by pdanpdan** [comment]
If you want to interact with it with the keyboard and to be able to focus it, it must have tabindex, else you can check for yourself that it's not focusable.

**Comment by dsl101** [comment]
I think that's the issue—it _shouldn't_ be focusable with tab (so no tabindex), but it _should_ be usable with the keyboard. As an example, see [this in the docs](https://quasar.dev/vue-components/scroll-area#basic). If you go to that link and use the up / down arrow keys, the whole docs page scrolls up and down. Now click on one of the text blocks in the scroll areas—there's no 'focus', but now the arrow keys allow interaction with the QScrollArea. How to achieve that 'focus' that isn't really true tab-style focus in code?

**Comment by hawkeye64** [comment]
@dsl101 If I turn on the focused element to be highlighted, I can see it's the `q-scrollarea`

![image](https://user-images.githubusercontent.com/10262924/115240675-386fce00-a0dd-11eb-966d-2675184a822b.png)

**Comment by rstoenescu** [comment]
"tabindex" prop will be available in Quasar v1.15.15.
