### ISSUE TITLE
Horizontal Stepper

### ISSUE THREAD

**Issue by ndamjan** [quasarframework/quasar#89]
Proposal: add orientation property to the Stepper component in order to allow horizontal orientation as well. Default vertical could be assigned if not defined.

Do you need help with this?

**Comment by rstoenescu** [comment]
Help is always greatly appreciated. If you have energy and feel like it, please take a shot at it. I'm currently totally spent after the v0.7 release.

**Comment by rstoenescu** [comment]
Will be available in v0.14.
