### ISSUE TITLE
QDrawer mini mode transition is jumping

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#8909]
**Describe the bug**
The transition from normal mode to mini mode is 'jumpy' as the icons which should stay in place also move with the animation of closing the drawer to mini mode.

This is V2 docs:
![qdrawerminiv2](https://user-images.githubusercontent.com/5757159/114983702-39142480-9e91-11eb-9388-fe99053278fe.gif)

This is V1 docs:
![qdrawerminiv1](https://user-images.githubusercontent.com/5757159/114983727-3f0a0580-9e91-11eb-9cec-58b0bf948855.gif)

**To Reproduce**
Check out any of the [mini-mode](https://next.quasar.dev/layout/drawer#mini-mode) examples on the Quasar V2 docs and compare them with the V1 behavior.

**Expected behavior**
I want the V1 behavior back :)

**Comment by Evertvdw** [comment]
Will this be fixed before going to stable on v2?

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.16.
