### ISSUE TITLE
PreFetch not working with class components

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#8915]
**Describe the bug**
When using class components the `preFetch` hook is not called. This is because the preFetch function is located not under `c` but under `c.__c` when using class components. See:
![image](https://user-images.githubusercontent.com/5757159/114994902-91512380-9e9d-11eb-8634-bb4d0784f402.png)

In the `client-prefetch.js` this line checks if the preFetch function exists: `.filter(m => m.c && typeof m.c.preFetch === "function")` which is of course never true when the preFetch function is not located there. 

This also needs to be adjusted for SSR as the same preFetch checking logic is applied there.

**To Reproduce**
Create a preFetch hook in the `@Options` decorator when creating a class component. For example:
```ts
import { Vue, Options } from "vue-class-component";

@Options({
	preFetch() {
		return new Promise<void>(resolve => {
			console.log("preFetch hook called!");
			resolve();
		}) as any;
	},
})
export default class Test extends Vue {}
```

**Expected behavior**
PreFetch should work for class components, so I guess the logic of checking the preFetch function should be extended to also account for class components.

Can this get some priority? Because we cannot really upgrade if this is not working properly because we do depend on the preFetch hook quite a bit.

**Comment by hawkeye64** [comment]
@Evertvdw I believe preFetch can only be called if it belongs to a route.
