### ISSUE TITLE
QDate `year` is undefined when model changes to a less then 4 digit year

### ISSUE THREAD

**Issue by lajuffermans** [quasarframework/quasar#8918]
**Describe the bug**
When using QDate range in combination with inputs an error is thrown in the subtitle function when the year becomes 2 digits. See movie:

https://user-images.githubusercontent.com/6448352/115006248-f2322900-9ea8-11eb-9831-9ff4625df17c.mov

Same behaviour with the default "mask" so that's not it.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/lajuffermans/pen/poRKGWL

**To Reproduce**
1. Create a range QDate
2. Bind the `from` and `to` properties to a QInput
3. Change the year e.g.: 2020 -> 202 -> all good -> 20 -> still good -> 22 or 202 -> error

**Expected behavior**
Don't throw an error

**Platform (please complete the following information):**
Quasar Version: 1.15.10
@quasar/app Version: 2.2.4
Quasar mode:

  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: OSX
Node:
NPM:
Yarn:
Browsers: At least Chrome 89.x
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.2.4.
