### ISSUE TITLE
v-ripple Error in directive ripple unbind hook: "TypeError: Cannot read property 'h' of undefined"

### ISSUE THREAD

**Issue by bulohjoe** [quasarframework/quasar#892]
Quasar: v0.14.2

Hi, I'm new here and I love quasar......

I'm keep getting below error everytime I navigate from one page to another, where the page that I'm navigating from a page that have v-ripple directive set to q-input.

_____START LOG_____

webpack-internal:///2:431 [Vue warn]: Error in directive ripple unbind hook: "TypeError: Cannot read property 'h' of undefined"

found in

---> <Login> at x:\xxxxxxxxx\components\views\account\login.vue
       <App> at x:\xxxxxxxxx\App.vue
         <Root>
warn @ webpack-internal:///2:431
webpack-internal:///2:520 TypeError: Cannot read property 'h' of undefined
    at unbind (webpack-internal:///8:1381)
    at callHook$1 (webpack-internal:///2:5484)
    at _update (webpack-internal:///2:5448)
    at updateDirectives (webpack-internal:///2:5390)
    at Array.unbindDirectives (webpack-internal:///2:5384)
    at invokeDestroyHook (webpack-internal:///2:5026)
    at invokeDestroyHook (webpack-internal:///2:5030)
    at invokeDestroyHook (webpack-internal:///2:5030)
    at invokeDestroyHook (webpack-internal:///2:5030)
    at invokeDestroyHook (webpack-internal:///2:5030)

_____END LOG_____

I have managed to track down to problem (after a long debugging). the problem is found in 

IN qasasr.esm.js, in unbind method

\node_modules\quasar-framework\dist\quasar.esm.js(1182):var Ripple = {
......
  unbind: function unbind (el, ref) {
    var modifiers = ref.modifiers;

    if (shouldAbort(modifiers)) {
      return
    }

    var ctx = el.__qripple;
    Object.keys(ctx.h).forEach(function (evt) {  <----- Problem
      el.removeEventListener(evt, ctx.h[evt], false);
    });

    delete el.__qripple;  <----- Problem
  }

I made the change to my local file and hoping this will be resolve, before the next upgrade.

Changes I made:
  unbind: function unbind (el, ref) {
    var modifiers = ref.modifiers;

    if (shouldAbort(modifiers)) {
      return
    }

    if (el && el.__qripple) { <--- AMENDMENT
      var ctx = el.__qripple;
      if (ctx.hasOwnProperty('h') && typeof (ctx.h) !== 'undefined') { <--- AMENDMENT
        Object.keys(ctx.h).forEach(function (evt) {
          el.removeEventListener(evt, ctx.h[evt], false);
        });
      } <--- AMENDMENT

      delete el.__qripple;
    } <--- AMENDMENT
  }

**Comment by rstoenescu** [comment]
May I take a look at your repo pls? It would be easier to see what's going on.
This error should not happen unless a misusage. Thanks.

**Comment by paritosh149** [comment]
Hi, I am also getting this error after upgradin gfrom v0.14.3 to v0.14.4.
Please add null check before calling below functions in ripple.js 
 el.removeEventListener('click', ctx.click, false);
 delete el.__qripple;

**Comment by rstoenescu** [comment]
Please reopen with the request. Thanks.
