### ISSUE TITLE
Mapbox cordova plugin not operating as expected

### ISSUE THREAD

**Issue by kylebuckingham** [quasarframework/quasar#893]
Hi -

I'm trying to use this plugin (https://github.com/Telerik-Verified-Plugins/Mapbox), but no matter what I do, I can't seem to get a hold of the "Mapbox" object. When I replace the www folder with cordova's default page, I can access the Mapbox object inside any of their functions. When I do so within a component (or anywhere in the app, I get "Mapbox is undefined". 

Thoughts?

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by kylebuckingham** [comment]
I've potentially solved this by including the cordova script in the index.html before the app gets injected. I've also noticed lots of inconsistencies with the cordova wrapper documentation.

**Comment by rstoenescu** [comment]
This cordova script issue has been fixed for ALL use cases possible through the new CLI for v0.15.
