### ISSUE TITLE
q-table examples to docs with :href for body-cell-[name] + img in cells

### ISSUE THREAD

**Issue by Mausino** [quasarframework/quasar#8932]
I am wondering why isn't in documentation the examples like

href attribute for celll that will possible click on it and open content on new tab
img attribute for show images in cells
img + href (clicable img) 

I think that will great to show advanced concept of working with q-table

My original resource where i search answer on this topic
`https://stackoverflow.com/questions/56514641/how-can-i-add-an-href-to-a-q-table-quasar-data-table`

**Comment by bazuka5801** [comment]
@Mausino It's part of html + vue, not quasar docs, you can read more:
https://developer.mozilla.org/ru/docs/Web/HTML/Element/img
https://www.w3schools.com/tags/att_a_href.asp
https://vuejs.org/v2/guide/syntax.html#Arguments
