### ISSUE TITLE
Add Vetur support for VSCode

### ISSUE THREAD

**Issue by frankdors** [quasarframework/quasar#894]
Vetur is Vue tooling for VSCode.

Is useful have support simular to others ui framework like Element and Onsen.
See here:  https://vuejs.github.io/vetur/framework.html

I can't do this, i'm a beginner in Vue.

**Comment by leopiccionia** [comment]
The required amount of Vue knowledge required for this task is actually minimal.

Anyway, I'm a Vetur user and willing to contribute on this issue.

**Comment by odranoelBR** [comment]
I'm waiting this too, will be awesome.

quasarjs creater, @rstoenescu already did this,

http://forum.quasar-framework.org/topic/1745/vetur-support-for-quasar-coming-up

**Comment by odranoelBR** [comment]
I guess, next vetur patch will bring quasar feature.
