### ISSUE TITLE
Syntax error: SassError, caused by a missing Scss file

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#8941]
**Describe the bug**
I get this error:
Syntax error: SassError: Nothing may be indented beneath a variable deceleration.

**To Reproduce**
1. Create a new Vue CLI project with SCSS support
2. Run: npm i -D vue-cli-plugin-quasar@next 
2. Invoke quasar plugin with: vue invoke quasar
3. Choose SCSS support feature
4. Run with "npm run serve"

**Expected behavior**
Running project

**Screenshots**
![image](https://user-images.githubusercontent.com/13297000/115143740-c7cf9f80-a051-11eb-8fcd-9f1b9b5639e2.png)
![image](https://user-images.githubusercontent.com/13297000/115143830-3876bc00-a052-11eb-8eb5-52e1e32dd434.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.12
@quasar/app Version: none
Quasar mode:
  - [x] SPA

Tested on:
  - [x] SPA

OS: Windows 7 Ultimate
Node: 13.14
NPM: 6.14.4

**Additional context**

**Comment by hawkeye64** [comment]
@eladcandroid Do you have sass in your package.json? I just ran into this exact error and downgraded sass from 1.32.10 back to v1.32.8 and pinned it. Then the error went away (don't forget to delete node_modules folder and yarn.lock and re-install when downgrading).

**Comment by eladcandroid** [comment]
@hawkeye64 You're right. When I downgrade sass to 1.32.8 it goes away. Thanks!

But we still need to fix the indentations and line brakes on the sass file so it'll work with the default Vue CLI project and latest sass package.

**Comment by hawkeye64** [comment]
@eladcandroid The latest sass is broken. It'll get fixed soon - hopefully.

https://github.com/sass/dart-sass/issues/1287
