### ISSUE TITLE
Can quasar-framework offer a function to close a q-slide-item?

### ISSUE THREAD

**Issue by flyinmind** [quasarframework/quasar#8942]
**Is your feature request related to a problem? Please describe.**
In a list, there is some action-buttons on each item.
I  want to realize "click any button or anywhere, then hide the buttons, if no actions keep the buttons visible".

**Describe the solution you'd like**
I refer to the example of the q-slide-item,  use a timer to make the buttons un-visible.
I think it is not flexible.

**Comment by rstoenescu** [comment]
Hi,

The example is with a timer because we need a quick way to show that it's doable, that you can "close" it programmatically. So close it programmatically by adding a capturing "click" event on the `body`.

**Comment by flyinmind** [comment]
Is there a example？
If in an 'click' event, how to get a 'reset' to call?
Thanks!
