### ISSUE TITLE
How to remove hash from file name after build ?

### ISSUE THREAD

**Issue by BaukaKZ** [quasarframework/quasar#8951]
![image](https://user-images.githubusercontent.com/42600725/115184765-53076e80-a100-11eb-87ee-c31bb950eacb.png)

**Comment by hawkeye64** [comment]
@BaukaKZ Why would you want to do that? Read this (https://madole.xyz/asset-hashing-with-webpack) and see if you still want to do it.

**Comment by yusufkandemir** [comment]
[Quasar v1 is EOL](https://github.com/quasarframework/quasar/discussions/15229), so I am closing this issue.

This behavior is supported for Quasar CLI with Vite, though:
https://quasar.dev/quasar-cli-vite/developing-pwa/configuring-pwa#filename-hashes-quirk
