### ISSUE TITLE
Infinite Scroll Prop scrollTarget should be the closest one

### ISSUE THREAD

**Issue by alexandre-le-borgne** [quasarframework/quasar#8952]
**Describe the bug**
https://quasar.dev/vue-components/infinite-scroll

When I put a class in the scrollTarget property I expect this to be the closest element to my infinite scroll component but it is not.

The behavior is correct if I am not using the property but one of the 3 classes defined here:
https://github.com/quasarframework/quasar/blob/6ca12d609677f9e7567d830f3b19051cba642a1b/ui/src/utils/scroll.js#L19
`target = el.closest('.scroll,.scroll-y,.overflow-auto')`

This behavior is also not documented which is another problem.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/b9avf2yh/

**To Reproduce**
See result in console. 

> "st1"
>"st1"

**Expected behavior**
> "st1"
> "st2"

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:  v1.15.10
Quasar mode:

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: v15.14.0
NPM:
Yarn: 1.22.10
Browsers: Google Chrome Version 90.0.4430.72 (Build officiel) (64 bits)

**Comment by pdanpdan** [comment]
If you pass a text in scrollTarget it will be search using document.querySelector.
Why would you expect closest to be used? It would not allow you to select elements that are not parent.
Use a specific id if you have multiple elements.

**Comment by alexandre-le-borgne** [comment]
"Why would you expect closest to be used?" Did you open the jsfiddle ? I find this behavior not at all intuitive. Moreover, the behavior I am trying to have is already that of the lib by default, but on classes documented nowhere:
https://github.com/quasarframework/quasar/blob/6ca12d609677f9e7567d830f3b19051cba642a1b/ui/src/utils/scroll.js#L19

 One solution would have been to look for the closest if the selector is a class or a tag, and throughout the document if it is an ID. Or first search in the ancestors, and if not found then search in the document. This could also be handled by a prop which defines whether we should search among the ancestors or not.
