### ISSUE TITLE
Native Page Transitions for Mobile Platform

### ISSUE THREAD

**Issue by vikas-vimal** [quasarframework/quasar#8959]
It is always a struggling task to add Native Page transitions for Mobile Platforms in the application.

It would be great if Native Page Transition animations could be added automatically on Mobile Platform like Ionic Framework has.

I have tried many times by adding transitions manually, but its very frustrating to add a native feature by my self while those features should have been in the framework itself.

Also, Ionic Framework has many more native looking components and provides native User Interface and native User Experience on both iOS and Android.
Picker Component
Native Header Component UI for iOS
Buttons UI in iOS
and many more elements are missing.

**Comment by rstoenescu** [comment]
Hi,

This can be achieved with the Vue's native `<transition>` over `<router-view>`. We already ship lots of predefined transitions (https://quasar.dev/options/animations). But main issue is that Quasar is not in control of the `<router-view>` in devland unless we write a component for this and force the developers to use it. But the component would be a dumb wrapper over the `<transition>` native component anyway, so why the overhead. There are also a lot of use cases that we'd need to cover, further increasing the complexity unnecessarily.

Also, there's Danny Connell who'll create a tutorial on this - https://twitter.com/danny__connell/status/1390337305785868290
