### ISSUE TITLE
dont works with typescript @ symbol

### ISSUE THREAD

**Issue by baryon** [quasarframework/quasar#8965]
**Describe the bug**
In typescript env, 

I want import store from ```/root/src/pages/desktop/file.vue``` file.
must use ``` import { useStore } from '../../store'; ```

if I want use it like ``` import { useStore } from '@/store'; ```

write tsconfig.json like 
```
{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "target": "es2017",
    "noImplicitAny": false,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "types": ["jest", "node"],
    "typeRoots": ["node_modules/@types"],
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
```
it don't works.

```
* @/store in ./node_modules/@quasar/app/lib/webpack/loader.js.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.vue.auto-import-quasar.js??ref--0-0!./node_modules/vue-loader/dist??ref--0-1!./src/layouts/desktop/AccountLayout.vue?vue&type=script&lang=js, ./node_modules/@quasar/app/lib/webpack/loader.js.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.vue.auto-import-quasar.js??ref--0-0!./node_modules/vue-loader/dist??ref--0-1!./src/pages/desktop/Account.vue?vue&type=script&lang=js
```

it should works thats sound from https://stackoverflow.com/a/51614395

**Expected behavior**

support typescript @ symbol.

OR, How to import module from src path?

**Platform (please complete the following information):**

 Dev mode.......... electron
 Pkg quasar........ v2.0.0-beta.12
 Pkg @quasar/app... v3.0.0-beta.15
 Debugging......... enabled

**Comment by Smrtnyk** [comment]
you can use ... from "src/store"

**Comment by IlCallo** [comment]
`@` alias isn't a standard, into quasar we have many aliases (`app`, `src`, etc) you can check out here: https://quasar.dev/quasar-cli/handling-webpack#webpack-aliases

TS and webpack aliases aren't the same thing, Quasar default aliases are provided to TS via the preset tconfig you extend coming from `@quasar/app` package.
You want to add your own, you need to add the new aliases both in TS and in webpack
