### ISSUE TITLE
Disable store initialization

### ISSUE THREAD

**Issue by luizhenriquerdias** [quasarframework/quasar#8968]
I don't want to use the Vuex store because the Composition API is suiting me better.

The problem is if I use the file store/index, the Quasar thinks I'm using Vuex and configures the .quasar/app.js accordingly and creates the store-flag.d.ts in the store folder.

I'm looking for a way to disable this Vuex/store initialization, maybe with a boolean in quasar.conf.

**Comment by rstoenescu** [comment]
Hi,

You can already do that. Two options come to mind:

1. Tell Quasar that the Vuex store is somewhere else (a bogus path): quasar.conf.js > sourceFiles > store: 'some-bogus-thing'
2. Use other folder than `/src/store` for your stuff
