### ISSUE TITLE
SSR + PWA mode InjectManifest not working - cant find service-worker.js

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#8969]
**Describe the bug**
When running the project in SSR mode with PWA enabled it throws an error saying the service-worker file can't be found.

```
Entry module not found: Error: Can't resolve 'C:\Users\evert\Programming\test-ssr-pwa\.quasar\pwa\service-worker.js' in 'C:\Users\evert\Programming\test-ssr-pwa'

[Client] EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'C:\Users\evert\Programming\test-ssr-pwa\.quasar\pwa\service-worker.js' 
```

**To Reproduce**
1. Create new starter project
2. Add SSR mode
3. Set `pwa` to true in ssr options in `quasar.conf.js`
4. Change `workboxPluginMode` to `InjectManifest` in `quasar.conf.js`
4. Run `quasar dev -m ssr`

**Expected behavior**
No errors

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in "@quasar/app" v3.0.0-beta.16.
