### ISSUE TITLE
Disable page scroll...

### ISSUE THREAD

**Issue by BrianMoreno1994** [quasarframework/quasar#897]
Hi guys, so I have a question... I'm currently developing a hybrid app with this framework. I've noticed that you can still scroll the page when a drawer is open, which in an app shouldn't happen. 

Is it possible to disable page scrolling when the drawer is open?

**Comment by rstoenescu** [comment]
Can you post the required info please? There's a ticket template when you create a new one. Thanks.

**Comment by BrianMoreno1994** [comment]
Is this the ticket template I should fill out?

Browsers: 
iOS: 
Android: 
Any other software related to your bug:

### What did you get as the error?
 
### What were you expecting?

### What steps did you take, to get the error?

**Comment by rstoenescu** [comment]
Yes, helps in investigating issues. Quasar is able to run under a LOT of environments so the details are essential. Thanks.

**Comment by BrianMoreno1994** [comment]
Ok:

Browsers: Not tested.
iOS: Not tested.
Android: Android 6.0 
Any other software related to your bug: None

What did you get as the error?
I'm currently creating a hybrid app, I noticed that when opening the drawer (slideable left hand menu) I was still able to scroll the content beneath the drawer. 

What were you expecting?
I was expecting the content beneath to stay in a fixed position, not being able to scroll it. 

What steps did you take, to get the error?
So far none, I'm trying to see if there's an existent fix for it first.

**Comment by JosielFaleiros** [comment]
I am facing the same trouble, can't fix it :'[

**Comment by matejicekme** [comment]
Same here :) 0.14.7

**Comment by rlam3** [comment]
Is this problem fixed? Was anybody here able to find a workaround?

**Comment by bloodf** [comment]
You will scroll because the drawer it's an overlay on the page, and the event target that it's happening when scrolling the drawer will pass to the window and it will scroll it down or up.

You can try this https://stackoverflow.com/a/9280412
