### ISSUE TITLE
currentRoute in preFetch SSR mode get params undefined

### ISSUE THREAD

**Issue by ysya** [quasarframework/quasar#8974]
**Describe the bug**
When using object of `currentRoute` in `preFetch` will get undefined, need to use `currentRoute.value` to access object in `currentRoute`, but `currentRoute` don't have 'value' in typescript.

**To Reproduce**
1. Create quasar app in ssr mode and make `preFetch: true` in quasar.conf.js
2. add state `test` and mutations 'setTest' in vuex
3. use `preFetch` in vue file and call mutations `setTest` to set `currentRoute.params` to state `test`
4. console log vuex `test` onMounted

**Expected behavior**
don't need to add `.value` and things in `currentRoute` should not be undefined

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "@quasar/app" v3.0.0-beta.16.
