### ISSUE TITLE
Quasar Cookie wrapper not functional with electron build and dev mode

### ISSUE THREAD

**Issue by KineticFox** [quasarframework/quasar#8975]
**Describe the bug**
In my project I'm using the Quasar [Cookie Plugin](https://quasar.dev/quasar-plugins/cookies#introduction)

In SPA mode the Plugin works fine but if change to dev/build electron mode it gets ignored. (looks like that for me)
Thats how i use the cookie implementation in my code:
```js
const cookieItem = {
      acToken: this.userDetails.token,
      user: this.userDetails.userID,

    };
    Cookies.set('user-cookie', cookieItem, { path: '/', expires: '1d', secure: true });
```

**To Reproduce**
1. use the code example above and change to ```quasar dev -m electron```
2. go to dev tools in the electron app and look for created cookie u will see nothing nor will u see an ```error``` or ```warning```

**Expected behavior**
In the browser in SPA mode if u go to dev tools and then check for created cookie u gonna see the cookie described in the code snippet above.
So it's proven that we can execute the cookie operation in general but not in the electron app.

**Platform (please complete the following information):**
Quasar Version:  v1.12.13
@quasar/app Version: v2.0.6
Quasar mode: 

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: linux / macOS
Node:
NPM:
Yarn:
Browsers: FireFox
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Hi,

This is the nature of Cookies in Electron and it's out of Quasar's reach how Cookies are handled. The Electron version would have been very important to mention. Better use something else, like LocalStorage or something more appropriate (you will need to check [Electron's docs](https://www.electronjs.org/docs)).

**Comment by KineticFox** [comment]
Ok thanks for the answer
