### ISSUE TITLE
q-popover margin glitch with long title and short items

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#898]
### Software version

Quasar: 0.14
OS: Windows
Browsers: Vivaldi 1.11.894.3 (Official Build) (64-bit)

Note I asked about this in the gitter chat, but it got lost in the stream I think.

### What did you get as the error?
When a `q-popover` contains a list (e.g. for a menu) and a `q-list-header` which is longer than any of the `q-item`s, there is not enough margin to the right of the `q-list-header`:

![image](https://user-images.githubusercontent.com/900542/30592585-3ea62968-9d3f-11e7-9320-d0893abcf121.png)

### What were you expecting?
The same margin on the left and right of the header

### What steps did you take, to get the error?
    <q-popover ref="menuRef">
      <q-list>
        <q-list-header>Jump to an event:</q-list-header>
        <q-item link>
          <q-item-main>
            <q-item-tile label>test 1</q-item-tile>
          </q-item-main>
        </q-item>
        <q-item link>
          <q-item-main>
            <q-item-tile label>test 2</q-item-tile>
          </q-item-main>
        </q-item>
      </q-list>
    </q-popover>

**Comment by rstoenescu** [comment]
Hi, set a margin.
`<q-list style="padding-right: 5px" ...`

**Comment by dsl101** [comment]
Tx - any reason why that wouldn't be part of the framework?
