### ISSUE TITLE
QMeta, can't use reactive title without composition API?

### ISSUE THREAD

**Issue by rigibore-charlie** [quasarframework/quasar#8982]
**Describe the bug**
This always used to be possible in v1 but now only seems possible with the composition API, I am still migrating options API to Vue 3 at the moment so cannot currently use composition.

In this scenario `this` is undefined and the page fails to compile/load.

**To Reproduce**
```javascript
<script>
  import { createMetaMixin } from 'quasar';
  
  export default {
    meta: {
      createMetaMixin({
        title: this.title
      }),
    },
    data: () => ({
      title: 'Hello world',
    }),
  }
</script>
```

**Expected behavior**
Page title is changed when `this.title` property is updated.

**Comment by rstoenescu** [comment]
Hi,

Make the parameter to supply createMetaMixin a function so it can be reactive.

```
createMetaMixin(function () {
  return {
    title: this.title
  }
})
```

**Comment by rigibore-charlie** [comment]
Ah thank you that worked, but I am getting a type error now, I think I had tried the solution before but never tested because of type error.  Don't know whether that's something that could be fixed...

![image](https://user-images.githubusercontent.com/63846513/115578155-f1d8ca00-a2bc-11eb-8e17-14f01508d2db.png)

**Comment by rstoenescu** [comment]
Yes, we're aware of it. It'll get fixed in the next release.
