### ISSUE TITLE
Search inside dropdown menu has lot of issues

### ISSUE THREAD

**Issue by Rolanddoda** [quasarframework/quasar#8985]
**Describe the bug**
There are many issues so I made a video -> https://www.loom.com/share/2e02fc23cd9e4f6db389c7ef6009f965

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Roland1993/pen/VwPVVZg?editors=1010

**Additional context**
All I want to do is to have a search inside the dropdown options popup.
In the original code, I have the search fixed so it doesn't scroll with the options.
As you can see from the video, there is a lot of strange things happening there and my guess it's because of the `virtual-scroll`. I have made some hacks in my code to fix some issues but still there is a lot of issues there.

What is the best way to implement a search inside dropdown menu for filtering options ?

**Comment by IlCallo** [comment]
Hey there, seems like you mixed in some strange way Quasar components.

Moving this to discussions as issues aren't meant for usage questions.
You could also ask to the Quasar community on our Discord server.
