### ISSUE TITLE
HTML Table responsive class -> remove table border on normal screen

### ISSUE THREAD

**Issue by Mohanrau** [quasarframework/quasar#899]
### Software version

Quasar:v 0.14.3
OS:Window 10
Node:v6.11.3
NPM:v5.4.2
Browsers:Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
refer title
![html table - 1](https://user-images.githubusercontent.com/1044660/30633350-f135904e-9e1d-11e7-93a6-8a33f70cd3ff.PNG)

### What were you expecting?
![html table - 2](https://user-images.githubusercontent.com/1044660/30633364-faa59d22-9e1d-11e7-8913-8f58111ba31d.PNG)

### What steps did you take, to get the error?
```
<table class="q-table bordered responsive cell-separator full-width mt-10">
                    <thead>
                    <tr class="header bg-grey-3">
```

**Comment by rstoenescu** [comment]
Can you post your full template please? Thanks.

**Comment by Mohanrau** [comment]
Actual code. Sorry i missed out responsive class in previous comment 
```
           <table class="q-table responsive bordered cell-separator full-width mt-10">
                <thead>
                <tr class="header bg-grey-3">
                    <th data-th="Product Code" class="text-left">Product Code</th>
                    <th data-th="Product Name" class="text-left">Product Name</th>
                    <th data-th="Quantity" class="text-left">Quantity</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
                <tr>
                    <td>Test</td>
                    <td>Test</td>
                    <td>Test</td>
                </tr>
            </table>
```

**Comment by rstoenescu** [comment]
This is obsolete starting with v0.15, so closing. Sorry for any inconvenience.
