### ISSUE TITLE
hex color value options do not come through using spinner component

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#900]
On quasar 0.14.3 when I use the example code for a spinner:
```
Loading.show({
  spinner: QSpinnerGears,
  message: 'Some message',
  messageColor: '#00ff00',
  spinnerSize: 250, // in pixels
  spinnerColor: '#f034a3'
})
```

colors-options are not used (but are inherited from body element instead). When I do:
```
Loading.show({
  spinner: QSpinnerGears,
  message: 'Some message',
  messageColor: 'red',
  spinnerSize: 250, // in pixels
  spinnerColor: 'white'
})
```
the colors do come through as they should.

**Comment by rstoenescu** [comment]
It's a glitch in the documentation. You need to use only colors from the Quasar Color Palette. Care for a PR on documentation pls?

**Comment by musicformellons** [comment]
Ok, just did.
