### ISSUE TITLE
Q-input problem in Japanese  when using Safari

### ISSUE THREAD

**Issue by rhymer211** [quasarframework/quasar#9000]
**Describe the bug**
Q-input(text) 
When using q-input  in Japanese by Safari, it shows wrong  display.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/actit/pen/XWpomaY?editors=101

**To Reproduce**
1. Go to First input field 
2. Input 'これはテストです'
3. See error 'kこれはtテストです'

**Expected behavior**
expected
 'これはテストです'

**Screenshots**
<img width="379" alt="スクリーンショット 2021-04-23 1 54 18" src="https://user-images.githubusercontent.com/11678221/115759841-acf78500-a3db-11eb-86b9-a831b125e2a0.png">

https://user-images.githubusercontent.com/11678221/115760301-298a6380-a3dc-11eb-8025-c2eb7ffe3c9b.mov

**Platform (please complete the following information):**
Quasar Version:2.0.0-beta.12
@quasar/app Version:3.0.0-beta.15
Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac OS 10.15.7
Node: v14.4.0
NPM: 7.7.5
Yarn: 1.22.10
Browsers: Sarafi 14.0 
iOS:
Android:
Electron:

**Additional context**

**Comment by yangjiafu** [comment]
Chinese has the same problem

**Comment by pdanpdan** [comment]
Hello.
Can you please try if it's fixed here: https://pdanpdan.github.io/quasar-docs/vue-components/input ?
It's for Q1, but just to check.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.15 & v2.0.0-beta.17.

**Comment by rhymer211** [comment]
> Hello.
> Can you please try if it's fixed here: https://pdanpdan.github.io/quasar-docs/vue-components/input ?
> It's for Q1, but just to check.

Yes,
It's fixed!
