### ISSUE TITLE
Allow readonly in QInput component

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#901]
Currently there is no way to have a readonly input on Quasar. The difference between disabled and readonly is that readonly allows the user to copy the text.

The solution has to be bindable to a data property, allowing the creation of forms that can be editable or not based on a criteria.

**Comment by rstoenescu** [comment]
Hmm, don't know how this ended up missing. Will add it to v0.14.4. Thanks for reporting!

**Comment by rstoenescu** [comment]
Available in edge version and future v0.14.4.
