### ISSUE TITLE
this.$t is undefined in Quasar 2

### ISSUE THREAD

**Issue by alexanderdeabreuwannme** [quasarframework/quasar#9010]
Currently I have Quasar 2 installed in a project and when I try to access this.$t for example for the i18n, I get an error saying that it is undefined.

UPDATE: I have seen what the error is, I am trying to access this.$t, currently I see that this is not supported, what would be your alternative? and if I want to use for example this.$q from Quasar I should do: import { useQuasar } from 'quasar' but... what would be the equivalent of $t for i18n?

**Comment by ThibaultJousse** [comment]
I'm guessing you're trying to use `this` in setup(), where it is undefined : see https://v3.vuejs.org/guide/composition-api-setup.html

you have to import usei18n first :
```javascript
import { useI18n } from "vue-i18n";
```

then you can access $t (without `this` prefix) in setup() this way :
```javascript
const { t: $t } = useI18n();
```

**Comment by rstoenescu** [comment]
Always read the documentation of the packages that you are using. In this case, the docs for vue-i18n should state how it can be used with Composition API.

**Comment by tmikaeld** [comment]
@rstoenescu Still, should update the [Quasar docs](https://quasar.dev/options/app-internationalization#introduction) on how to use it, since this is where people check first. And it doesn't mention the composable API, but it's mentioned on most other places.

**Comment by rstoenescu** [comment]
@tmikaeld There you go. Improved docs. Will be available in next docs deployment.
Took the opportunity to also PR the vue-i18n docs with references to Quasar CLI usage :)
