### ISSUE TITLE
Quasar Stepper "keep-alive" not working when in vertical mode

### ISSUE THREAD

**Issue by Klay1337** [quasarframework/quasar#9013]
**Describe the bug**
When the QStepper is put into vertical mode with enabled "keep-alive" flag, it looses the data of previous steps when switchting to the next. Does only happen if in vertical mode, horizontal is working fine..

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/fg0seqn3/26/

**To Reproduce**
1. Add some photos to the uploader
2. Click next
3. Click Back
4. Photos lost.

**Expected behavior**
Photos are keept in the Uploader as the keep-alive is set

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.12
@quasar/app Version: v3.0.0-beta.15
Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: win 10
Node: v14.15.5
NPM: 6.14.11
Browsers: Chrome

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.14
