### ISSUE TITLE
Drawer: side-opener overlaps toolbar

### ISSUE THREAD

**Issue by NikitaKA** [quasarframework/quasar#902]
I using Quasar for my iOS/Android app (with my own wrapper with WebView, not Cordova), and I found that side-opener element overlaps toolbar and partially overlaps left button so I cant normally tap button on it.

![tlfd3q0hls](https://user-images.githubusercontent.com/2543427/30697908-1df02e3e-9ee9-11e7-8a1a-f0d6b2d87f5e.gif)

I tried to add `top: 51px` for `.layout-side-opener` and that works. Maybe there should be some setting for that case?

**Comment by rstoenescu** [comment]
This is normal behavior. That side opener on the left is needed in order for user to be able to do the swipe. It's width is perfect for still being able to hit on buttons though. This is not a bug.

**Comment by NikitaKA** [comment]
A user doesn't want to do the swipe right in the corner of the screen, especially when there is a button. Imagine, that there is a back button and user wants to go back. When he trying to tap a button - in 50% cases it does not fire because of side-opener. We made a focus group with 4 people, and everyone faced that problem. iOS and Android users. Try to tap a button in the upper left corner like an obvious user, not like a programmer who knows how it works.
