### ISSUE TITLE
MAX and MIN range issue in q-range component 

### ISSUE THREAD

**Issue by bagladivyang03** [quasarframework/quasar#9020]
I m using the q-range component as below: 
           <q-range
              markers
              v-on:change="changedata()"  
              v-model="standard"
              :step = "7"
              :min="0"
              drag-range
              :max="28"
            />
       
 But I want to restrict the max and min to have the same value as when sliding the slider we can slide the max or min on the same value .
 Anybody can pls help How to restrict I was thinking of drag only range but in that we can have fix value range drag only. 
 Pls help ?

**Comment by Godfadatun** [comment]
When you mean restrict do you mean for both the max an min to move together?

if that is it create a watcher to watch both max and min and increaser by same range difference 

But if not kindly Expatiate so I can clearly understand

**Comment by bagladivyang03** [comment]
Actually what I want is exactly is that the distance between max and min I want to fix to some value instead of directly 0.
As I read the documentation I found the drag-only but in that the distance is fixed between min and max I want variable distance between min and max.

**Comment by bagladivyang03** [comment]
@Godfadatun is there any way ?

**Comment by pdanpdan** [comment]
Change min and max according to what you want when the value changes.
