### ISSUE TITLE
[Request] QSelect add key events

### ISSUE THREAD

**Issue by fsgiudice** [quasarframework/quasar#903]
It could be useful to handle key events to use keyboard on desktop version. 
On forms I would like to use keys to move between fields and also on a select (i.e. press enter to submit form, currently handled on simple qinput fields but not on qselect field, but also move between qselect values using up and down keys).

**Comment by rstoenescu** [comment]
Notice that you can use TAB to move between input fields.
QSelect indeed needs some extra code to handle moving between its values. And this is on the roadmap.

**Comment by fsgiudice** [comment]
Hi @rstoenescu, 
about TAB key I saw, but other key events are necessary for keyboard use. Thank you.

**Comment by igorgo** [comment]
In addition to handle moving values, it needs handlers for selecting a value by `Enter`, and for opening the list itself (usually `F4` or `Ctrl+↓`)

**Comment by rstoenescu** [comment]
Yes, all this is available in Autocomplete. What is needed is a wrapper so it can be used with multiple components.

**Comment by dboune** [comment]
@rstoenescu is this on the roadmap for v.15?

**Comment by rstoenescu** [comment]
Available in 0.15.1. Forgot to close this.

**Comment by rstoenescu** [comment]
@wc-matteo opened https://github.com/quasarframework/quasar/issues/1652 and pushed fix then closed it. Will be available in 0.15.4

**Comment by wc-matteo** [comment]
Thank you very much! Sorry, I couldn't it open it myself.
