### ISSUE TITLE
Uploader file parse params before file body

### ISSUE THREAD

**Issue by borikinternet** [quasarframework/quasar#904]
This is not a bug, but some inconvenience

I'm using openresty (nginx based distro) to serve my backend. And I need to upload a very big files to database. Quickest way for me is to parse them in process of uploading. I do a POST request with Uploader and attach array of parse params: table to which content of file must be inserted and delimiter.

On the backend side I do reed() of chunks and try to split it with delimeter and insert them to database, but... delimiter param came to me in later chunks :( I need to recieve all file and only after this I recieve paramse for its parsing. Its a bad way... 

I'll add a pull request for fix this issue shortly

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.4.
Thanks for also providing a PR!
