### ISSUE TITLE
Quasar v2 QRouterTab @click e has no navigate property

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar#9052]
**Describe the bug**

navDelay (e, go) {
      e.navigate = false // we cancel the default navigation

      // console.log('triggering navigation in 2s')
      setTimeout(() => {
        // console.log('navigating as promised 2s ago')
        go()
      }, 2000)
    },
<q-route-tab :to="{ query: { tab: '1' } }" exact replace label="Activate in 2s" @click="navDelay" />

e.navigate  undefined

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/xxEvBLR?editors=101) or a jsFiddle (https://jsfiddle.net/rstoenescu/a2cuzods/) or a Codesandbox (https://codesandbox.io/s/optimistic-poitras-4t3m3) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
New behavior will be available in Quasar v2.0.0-beta.17:

```
// OLD way
function onClick (e, go) {
  e.navigate = false // <<<--- this changed
  // ...maybe later call go()?
}

// NEW way
function onClick (e, go) {
  e.preventDefault() // <<<--- this changed
  // ...maybe later call go()?
}
```
