### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by alexanderdeabreuwannme** [quasarframework/quasar#9058]
I have recently upgraded to the following versions

* "quasar": "^2.0.0-beta.13",
* "@quasar/extras": "^1.10.4",

Since I have done this I have literally stopped working all the global paths, the .env files, I have not been able to do anything. I've been reading the documentation but couldn't find anything useful, has anyone else had this happen?

If i remove process.env declaration the project will work but that isn't a option for me right now. 

It also happens that the global paths of the images are not working for me (I noticed this when I deleted process env).

Actually import like this: `<img :src='`${require(`src/assets/flags/${language}.png`)}`'>`

![image](https://user-images.githubusercontent.com/81359416/116241498-3e148600-a765-11eb-96b1-f9d05277557e.png)

MY VERSIONS

"node": ">= 12.22.1",
"npm": ">= 6.14.2",
"yarn": ">= 1.21.1"

**Comment by rstoenescu** [comment]
You've most likely also updated "@quasar/app" which now ships with Webpack 5. But regardless, checked process.env declarations and webpack aliases and found no issue.

Are you sure that you've read the release notes before upgrading? This was the last breaking change while v2 is in beta, but it has impact nonetheless. https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v3.0.0-beta.16

**Comment by alexanderdeabreuwannme** [comment]
@rstoenescu and.. how can I solve this problem? actually I need to use the environment variables, how can I update the project dependencies so that they do not fail?

**Comment by rstoenescu** [comment]
First, follow the upgrade guide.

Then I think you need some clarification on how process.env works:
```
if (process) --> won't work
if (process.env) --> won't work
if (process.env.MY_ACTUAL_VAR) --> WORKS
```
```

**Comment by alexanderdeabreuwannme** [comment]
That's the current problem, actually im using process.env.MY_ACTUAL_VAR and getting a warning that "process" is not defined.

**Comment by rstoenescu** [comment]
Please share a reproduction repo. Have not encountered your issue.
Also, what Quasar modes are you building?

**Comment by alexanderdeabreuwannme** [comment]
Package.JSON
https://pastebin.com/rbq4BEQR

Quasar.conf.js
https://pastebin.com/GnsmNNUT

Quasar.extensions.json
https://pastebin.com/7qPJ0EP2

SPA mode

**Comment by rstoenescu** [comment]
Those files are not helpful at all. Need a full project folder (without node_modules) to see the actual /src that breaks something.

**Comment by alexanderdeabreuwannme** [comment]
https://github.com/alexanderdeabreuwannme/reproduction-repo  here you are

**Comment by rstoenescu** [comment]
From looking at the error message in your screenshot, seems like /src/services/api/master/index.js tries to directly access "process" on its own.

Released q/app v3.0.0-beta.17 -- has a change to maintain the previous webpack 4 behavior when importing a media asset, so your `<img :src="require()" won't complain.

**Comment by alexanderdeabreuwannme** [comment]
Line 2 

https://github.com/alexanderdeabreuwannme/reproduction-repo/blob/dev/src/services/api/master/index.js

that's whats im doing about access to process

**Comment by rstoenescu** [comment]
Care to supply the .env file also pls? Let's connect on Discord so we can make progress faster.

**Comment by alexanderdeabreuwannme** [comment]
Okay. Byakko#9851 on Discord, I can't speak very fluent English but I can support myself by typing.

**Comment by rstoenescu** [comment]
Ok, writing here for other people who might be reading this thread. The problem was that the devland code was accessing `process.env.SOMETHING` but `SOMETHING` was NOT defined in quasar.conf.js > build > env. As a result, `process.env.SOMETHING` did not get replaced with the actual value so the runtime actually tries to access the `process` object (which does not exists --- it got removed in Webpack 5 anyways).

**Comment by AlexDaniel** [comment]
@rstoenescu thank you very much for taking the time to leave the comment. I was struggling with the same problem for other reasons, but found this ticket by searching for the error message, and your comment helped me figure out what was wrong (it was just an accidental naming mistake). It saved a lot of time for me, thank you!
