### ISSUE TITLE
data-table tooltip function is not everyone needs [proposal]

### ISSUE THREAD

**Issue by zhuyifang** [quasarframework/quasar#906]
data-table tooltip function is not everyone needs, not to mention tooltip tips are so beautiful! The The
Hope to be able to provide a table in the data-table config tooltip configuration options

**Comment by rstoenescu** [comment]
QDataTable is running a revamp as we speak. Will be available in v0.15.
You'll be able to configure it to the core.

Thanks for your patience!

v0.15 roadmap: http://forum.quasar-framework.org/topic/815/quasar-v0-15-roadmap

**Comment by rstoenescu** [comment]
Closing as code for this is ready in v0.15 revamp.
