### ISSUE TITLE
Dependencies error in quasar v1.15.11, "q-date-picker" does not work.

### ISSUE THREAD

**Issue by DengnisR** [quasarframework/quasar#9067]
Hi, I don't know if it will be a dependency problem, but when opening a "q-date" contained within a "q-popup-proxy" this error will appear in the console.

```
TypeError: Cannot read property 'months' of undefined
    at H (vendor.84e27e9d.js:110)
    at a.__decodeString (vendor.84e27e9d.js:110)
    at a.__getViewModel (vendor.84e27e9d.js:110)
    at a.data (vendor.84e27e9d.js:110)
    at a.<anonymous> (vendor.84e27e9d.js:235)
    at cr (vendor.84e27e9d.js:235)
    at ur (vendor.84e27e9d.js:235)
    at sr (vendor.84e27e9d.js:235)
    at a.t._init (vendor.84e27e9d.js:235)
    at new a (vendor.84e27e9d.js:235)
```

This causes the "datepicker" not to be displayed on the screen.

My understanding is that some packets can break the quasar.
Could someone pass me their "package.json" to compare packages?

My package.json

```  
"dependencies": {
    "@quasar/babel-preset-app": "^1.1.9",
    "@quasar/extras": "^1.10.4",
    "@websanova/vue-auth": "^2.21.14-beta",
    "axios": "^0.21.1",
    "chart.js": "^2.9.3",
    "chartjs-plugin-zoom": "^0.7.7",
    "core-js": "^2.6.5",
    "http-proxy-middleware": "^0.19.1",
    "my-local-ip": "^1.0.0",
    "os": "^0.1.1",
    "public-ip": "^3.2.0",
    "quasar": "^1.15.11",
    "quill": "^1.3.7",
    "quill-image-resize-module": "^3.0.0",
    "socket.io": "^2.3.0",
    "vue-axios": "^2.0.2",
    "vue-chartjs": "^3.5.0",
    "vue-clipboard2": "^0.3.0",
    "vue-i18n": "^8.17.0",
    "vue-router": "^3.1.6",
    "vue2-editor": "^2.10.2",
    "vuex-router-sync": "^5.0.0",
    "webpack": "^4.44.2"
  },
  "devDependencies": {
    "@quasar/app": "^2.2.5",
    "babel-eslint": "10.0.1",
    "copy-webpack-plugin": "^6.1.1",
    "eslint": "^6.0.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-friendly-formatter": "4.0.1",
    "eslint-loader": "2.1.1",
    "eslint-plugin-import": "2.14.0",
    "eslint-plugin-node": "7.0.1",
    "eslint-plugin-promise": "4.0.1",
    "eslint-plugin-standard": "4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "html-webpack-plugin": "^4.5.0",
    "strip-ansi": "^3.0.1",
    "workbox-webpack-plugin": "^5.1.4"
  },
  "resolutions": {
    "ajv": "6.8.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0"
  }
```

**Comment by hawkeye64** [comment]
@DengnisR A few things you can do here, that I quickly noticed:
1. Remove reference to webpack as you already inherit via @quasar/app and it's pinned at a known version that works well with Quasar
2. Remove "strip-ansi" package as that is no longer needed
3. Remove your resolutions to "avj" as that is also no longer needed
4. remove node_modules and package-lock.json/yarn.lock and re-install

**Comment by DengnisR** [comment]
@hawkeye64 Thanks I'll try.

**Comment by DengnisR** [comment]
@hawkeye64 It didn't work, I removed the packages
Then install again
But I keep getting the same error
Could it be some other reason?

**Comment by hawkeye64** [comment]
@DengnisR The best thing you can do at this point is to create a CodePen.

**Comment by DengnisR** [comment]
@hawkeye64 Let's provide another point of view.

Initially, the issue occurred because I removed ": locale" from component "q-date"
Since I had this problem, every month has the same days.

I thought the problem was "i18n" or "locale", so I removed the ": locale" directive from the component.
Also, since I didn't need it, I removed the object with the translation in my "i18n / es / index.js", this caused it to send the message that opened the issue.

Which shouldn't be a problem, since you don't have the ": locale" directive specified in the component.

Here's a link to my google drive so you can see the screenshots of what the "q-date" component looks like at first.

[Screenshot 1](https://drive.google.com/file/d/11Az3_TNeYnZni1HQDr7qCUNpLgLgtg7h/view?usp=sharing)
[Screenshot 2](https://drive.google.com/file/d/1nCg6bNwPMom8Q5l3xFhRAGZ5_nI0COXi/view?usp=sharing)

**Comment by metalsadman** [comment]
@DengnisR codepen error log is different than the error you originally sited, `locale` expects an object with properties described in the API section of QDate, ie. `{days: ['Duminica', 'Luni', 'Marti'], daysShort: ['Dum', 'Lun', 'Mar'], months: ['Ianuarie', 'Februarie', 'Martie'], monthsShort: ['Ian', 'Feb', 'Mar']}`. if you are suspecting a dependency error, then try `4.` of Jeff's suggestion, otherwise provide a reproduction repo, that we can clone and test locally.

**Comment by DengnisR** [comment]
@hawkeye64 @metalsadman Thank you very much for the contribution.
But I already managed to fix the problem.

As mentioned in the comment above, I use the "i18n" package to manage my translations, the problem is that I was using this as the main translator of my application, so components that have translations choose to search first in the custom translations of "i18n" than in quasar translation packages.

All you have to do is add the "date" object with the translations to my translations file. Just as you mentioned.
The problem with the days appearing the same in each month was due to the fact that a couple of indices were missing from the date object.

These in particular.

```
firstDayOfWeek: 1,
format24h: !0,
pluralDay: "dias"
```

Adding them to the "date" object resolved the agenda issue.

This does not eliminate the fact that removing the "locale" directive in the "q-date" component should work with the translation of the quasar.
But it seems that the package "i18n" causes this conflict.
