### ISSUE TITLE
Using QSelect inside QFab inside QSticky produces unexpected behaviour 

### ISSUE THREAD

**Issue by maggie0002** [quasarframework/quasar#9073]
I have a q-page-sticky for the bottom right of the page. Inside that I have q-fab to provide a menu on click. Inside that I have a q-select as I need to provide the option to choose from a range of items populated from the script. 

It results in a couple of issue. 

1. First, the QFab is already open when the page loads. 
2. Second, The icon for the QSelect adopts an odd shape (see screenshot). 
3. Third, the 'label' option is not available on the QSelect in this instance, when inputting a label it doesn't appear. When clicking the QSelect menu, it is bunched up, but when closing the select and reopening it, it appears ok (see screenshot). 

Of course this is a rather odd scenario, but one I haven't found an alternative way to achieve. 

```
      <q-page-sticky
        position="bottom-right"
        :offset="[18, 18]"
      >
        <q-fab
          v-if="!this.$q.fullscreen.isActive"
          v-model="fabRight"
          vertical-actions-align="right"
          color="white"
          padding="xs"
          icon="keyboard_arrow_up"
          text-color="primary"
          direction="up"
        >
          <q-fab-action
            label-position="left"
            v-if="this.$q.fullscreen.isCapable"
            color="primary"
            :icon="$q.fullscreen.isActive ? 'fullscreen_exit' : 'fullscreen'"
            text-color="white"
            @click="toggle"
            :label="$t('full_screen')"
          />
          <q-fab-action
            label-position="left"
            @click="redirect"
            color="primary"
            text-color="white"
            class="material-icons"
            icon="arrow_back_ios"
            :label="$t('back')"
          />
          <q-select
            filled
            v-model="chapter"
            :options="toc"
            rounded
            dense
            option-value="href"
            option-label="label"
            option-disable="inactive"
            emit-value
            bg-color="primary"
            map-options
            @update:model-value="goToExcerpt"
          >
            <template #prepend>
              <q-icon
                name="menu_book"
                color="white"
              />
            </template>
          </q-select>
        </q-fab>
      </q-page-sticky>
```

"@quasar/app": "^3.0.0-beta.15"
"quasar": "^2.0.0-beta.12"
"@quasar/extras": "^1.10.2"

<img width="165" alt="Screenshot 2021-04-27 at 20 25 49" src="https://user-images.githubusercontent.com/64841595/116342189-0cb4ae00-a797-11eb-8e31-8eb99287022f.png">
<img width="263" alt="Screenshot 2021-04-27 at 20 25 55" src="https://user-images.githubusercontent.com/64841595/116342191-0de5db00-a797-11eb-92cd-6414932accfe.png">

**Comment by metalsadman** [comment]
q-select is not suited for what you're doing. just use QMenu instead. https://codepen.io/metalsadman/pen/PoWgaob?editors=1010

**Comment by maggie0002** [comment]
> q-select is not suited for what you're doing. use QMenu instead. https://codepen.io/metalsadman/pen/PoWgaob?editors=1010

I'm currently drawing on QSelects's 'options' option (`:options="toc"`) to populate the menu. Perhaps I'm missing something, but I can't see that option on QMenu, is it possible?

**Comment by maggie0002** [comment]
I switched it to the QMenu with v-for to loop through the items. It is still open by default though when the page loads. I see from the examples on the Quasar Docs that this isn't what usually happens.

```
      <q-page-sticky
        style="z-index: 2001;"
        position="bottom-right"
        :offset="fabPos"
      >
        <q-fab
          v-if="!this.$q.fullscreen.isActive"
          v-model="fabRight"
          vertical-actions-align="right"
          color="white"
          padding="xs"
          icon="keyboard_arrow_up"
          text-color="primary"
          direction="up"
          :disable="draggingFab"
          v-touch-pan.prevent.mouse="moveFab"
        >
          <q-fab-action
            label-position="left"
            v-if="this.$q.fullscreen.isCapable"
            color="primary"
            :icon="$q.fullscreen.isActive ? 'fullscreen_exit' : 'fullscreen'"
            text-color="white"
            @click="toggle"
            :label="$t('full_screen')"
            :disable="draggingFab"
          />
          <q-fab-action
            label-position="left"
            @click="redirect"
            color="primary"
            text-color="white"
            class="material-icons"
            icon="arrow_back_ios"
            :label="$t('back')"
            :disable="draggingFab"
          />
          <q-btn
            no-caps
            fab-mini
            no-wrap
            color="primary"
            icon-right="menu_book"
            :label="$t('chapter')"
            :disable="draggingFab"
            rounded
          >
            <q-menu>
              <q-list>
                <q-item
                  clickable
                  v-close-popup
                  v-for="i in toc"
                  :key="i['href']"
                  @click="goToExcerpt(i)"
                >
                  <q-item-section>{{ i['label'] }}</q-item-section>
                </q-item>
              </q-list>
            </q-menu>
          </q-btn>
        </q-fab>
      </q-page-sticky>
```

**Comment by maggie0002** [comment]
> I switched it to the QMenu with v-for to loop through the items. It is still open by default though when the page loads. I see from the examples on the Quasar Docs that this isn't what usually happens.
> 
> ```
>       <q-page-sticky
>         style="z-index: 2001;"
>         position="bottom-right"
>         :offset="fabPos"
>       >
>         <q-fab
>           v-if="!this.$q.fullscreen.isActive"
>           v-model="fabRight"
>           vertical-actions-align="right"
>           color="white"
>           padding="xs"
>           icon="keyboard_arrow_up"
>           text-color="primary"
>           direction="up"
>           :disable="draggingFab"
>           v-touch-pan.prevent.mouse="moveFab"
>         >
>           <q-fab-action
>             label-position="left"
>             v-if="this.$q.fullscreen.isCapable"
>             color="primary"
>             :icon="$q.fullscreen.isActive ? 'fullscreen_exit' : 'fullscreen'"
>             text-color="white"
>             @click="toggle"
>             :label="$t('full_screen')"
>             :disable="draggingFab"
>           />
>           <q-fab-action
>             label-position="left"
>             @click="redirect"
>             color="primary"
>             text-color="white"
>             class="material-icons"
>             icon="arrow_back_ios"
>             :label="$t('back')"
>             :disable="draggingFab"
>           />
>           <q-btn
>             no-caps
>             fab-mini
>             no-wrap
>             color="primary"
>             icon-right="menu_book"
>             :label="$t('chapter')"
>             :disable="draggingFab"
>             rounded
>           >
>             <q-menu>
>               <q-list>
>                 <q-item
>                   clickable
>                   v-close-popup
>                   v-for="i in toc"
>                   :key="i['href']"
>                   @click="goToExcerpt(i)"
>                 >
>                   <q-item-section>{{ i['label'] }}</q-item-section>
>                 </q-item>
>               </q-list>
>             </q-menu>
>           </q-btn>
>         </q-fab>
>       </q-page-sticky>
> ```

Which is controlled by `fabRight: ref(false),` which I had set to true. All came down to my ability/lack there of. Thanks for your patience.
