### ISSUE TITLE
QPagination: active-color not applied to first and last button when :max-pages is set

### ISSUE THREAD

**Issue by captainjex** [quasarframework/quasar#9075]
**Describe the bug**
We have q-pagination with props `color` and `active-color` set with different color. The active color works properly until we set props `max-pages`, The buttons for first and last page still applied with the color from `color` props, not the `active-color` one.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/wkwksama/pen/NWdmyMz

**To Reproduce**
1. Go to link to pen above
2. See the first q-pagination, the button for first and last page applied with primary color when it is active
3. Add props `:max-pages="5"` to the q-pagination
4. The first and last buttons is not applied with `active-color`

**Expected behavior**
The button for active color should primary

**Screenshots**
![image](https://user-images.githubusercontent.com/21119252/116364982-ffe39900-a82e-11eb-80f6-10591a7a97cc.png)*without props max-pages*
![image](https://user-images.githubusercontent.com/21119252/116365108-21dd1b80-a82f-11eb-9a80-22dcbd4fffb7.png)*with props max-pages*

**Platform (please complete the following information):**
Quasar Version: 1.15.10
@quasar/app Version: 2.1.15
Quasar mode:

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: v12.8.1
NPM: 6.10.2
Yarn:
Browsers: chrome
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.12.
