### ISSUE TITLE
QDialog with auto-close prop on iOS: cannot open dialog

### ISSUE THREAD

**Issue by ntoljic** [quasarframework/quasar#9077]
**Describe the bug**
QDialog elements with the auto-close prop set cannot be opened on iOS (in the browser).
Possibly related to https://github.com/quasarframework/quasar/issues/5785

**Codepen/jsFiddle/Codesandbox (required)**
https://next.quasar.dev/vue-components/dialog#styling
Add the auto-close prop to e.g. the first dialog

**To Reproduce**
1. Open the fiddle
2. Add the auto-close prop to the first dialog
3. Click on the button
4. See that dialog opens briefly but closes again right away without any user interaction

**Expected behavior**
The dialog should remain open if all the user does is click/tap the button to open it.

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.12
@quasar/app Version: v3.0.0-beta.15
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Additional context**
I was able to reproduce the issue on an iPhone simulator on macOS but the bug was initially reported to me by a user with a physical iPhone.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.14.

**Comment by ntoljic** [comment]
Wow, that was super-fast! Looking forward to update 👍
