### ISSUE TITLE
QInput get/set caret position

### ISSUE THREAD

**Issue by lyle45** [quasarframework/quasar#9078]
**Is your feature request related to a problem? Please describe.**
There is currently no way to get or set caret position for QInput
Only current workaround is

``` typescript
      const messageInput = ref<QInput | null>(null); // for example purpose
      const input = messageInput.value.$refs.input as HTMLInputElement ;
      const cursorPosition = input.selectionStart;
      message.value = [
        message.value.slice(0, cursorPosition),
        emoji.native,
        message.value.slice(cursorPosition),
      ].join('');

      nextTick(() => {
        messageInput.value && messageInput.value.focus();
        input.selectionEnd = cursorPosition + 1;
      });
```

Which is extremely unwanted especially since i need to access QInput $refs directly, which, other then being unhealthy code, $refs is also deprecated for Vue 3

**Describe the solution you'd like**
Add methods to getCaretPos and setCaretPos (Not even relating to get/setSelectionArea) 

**Describe alternatives you've considered**
To avoid further edge cases and allow pretty coding without feature requests, maybe add messageInput.getNativeInputRef() or something

**Comment by rstoenescu** [comment]
Is this ticket correctly tagged with Qv1? I think you wanted Qv2?
Regardless, new method (`getNativeElement()`) will be available in Quasar v1.15.15 & Quasar v2.0.0-beta.17.
