### ISSUE TITLE
Build options for Staging and Live servers

### ISSUE THREAD

**Issue by afnan** [quasarframework/quasar#9080]
**Is your feature request related to a problem? Please describe.**
Our app is becoming bigger and bigger with every feature. Now we push it to a staging server and do testing before it goes on the live server. We use different endpoints for API for this. For example, we would use staging.abc.com for staging and api.abc.com for the live version. Currently, we handle this in the config file in `env: ctx.dev`. The problem that is one API is deployed on localhost for development and two for the live server (staging and live) and we have to frequently comment and un comment respective endpoints.

**Describe the solution you'd like**
A build command that takes in a parameter during the build and applies the respective endpoint in the config file. For example, quasar build -staging

**Comment by nucle** [comment]
Hi afnan,

this is how I did it.

### Package added:
@quasar/quasar-app-extension-dotenv": "^1.1.0

### Local Development: 
I created a _.env_ file with all my URLs:
E.g.:
```
API_URL=
API_AUTH_URL=
```

In quasar.conf.js I did the following:
```
const dotenv = require('dotenv')
const parsedEnv = dotenv.config().parsed
module.exports = configure(function (ctx) {
        build: {
            vueRouterMode: 'hash', // available values: 'hash', 'history'
            env: {
                myApp: { parsedEnv }
            }
       }
}
```

In code I can now access my environment variables:
```
const apiUrl = process.env.API_URL
const authUrl = process.env.API_AUTH_URL
```

When you want to connect to different machines or mix local and dev environment for example then you can use the proxy in quasar.conf.js

```
       // Full list of options: https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-devServer
        // https://webpack.js.org/configuration/dev-server/#devserver-proxy
        devServer: {
            https: false,
            port: 8083,
            vueDevtools: false,
            open: 'firefox',
            proxy: {
                '/api/v1/user': 'http://localhost:3000',
                '/api/v1/auth': 'http://dev-app.test:3000',
            }
        },
```
### PROD, STAGING, TEST, and DEV
They have different .env files

**Comment by Smrtnyk** [comment]
@quasar/quasar-app-extension-dotenv is deprecated
use just dotenv package
https://www.npmjs.com/package/dotenv

**Comment by rstoenescu** [comment]
@afnan like mentioned in the above comment, you can use dotenv or directly access environment variables (terminal variables) through `process.env` in your quasar.conf.js file. Not sure what you are using for the deployment (a service or your own machine), but most deployment services have the ability to configure env variables. Then it's as easy as: `ctx.dev ? 'this' : (process.env.PRODUCT_STAGING ? 'that' : 'other_that')` (just an example so you can get the hang of it) -- calling the build script with `PRODUCT_STAGING=true quasar build` will result in `that`.
