### ISSUE TITLE
input in radio slot can't focused

### ISSUE THREAD

**Issue by nailfar** [quasarframework/quasar#9088]
**Describe the bug**
input in radio slot can't focused

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/nailfar/pen/ZELNLOz?editors=1010

**To Reproduce**
1. Go to https://codepen.io/nailfar/pen/ZELNLOz?editors=1010
2. Click on q-input
3. radio will checked. but input will not foucsed
 
**Expected behavior**
radio checked and input focused
**Screenshots**
 
**Platform (please complete the following information):**
Quasar Version: 1.15.10
Quasar mode: 

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on: 
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:  Mac os
Node: 10.16.2
NPM:6.9.0
Browsers: Chrome

**Comment by hawkeye64** [comment]
That's not the intended usage. QRadio follows specs for label tag with `for` attribute so that clicking on the label puts focus on the radio button. This is a normal browser procedure.
https://www.w3schools.com/tags/att_input_type_radio.asp

**Comment by rulrok** [comment]
Just leaving a note here in case anyone stumble upon this problem.
I found myself on the same scenario with a `q-input` inside a `q-radio`.

I had to go with a hack:

```vue
<q-input @focus="onFocusHack" />
```

```typescript
import {throttle} from 'quasar';

  focusElementThrottled = throttle((el: HTMLInputElement): void => {
    el.focus();
  }, 300);

  onFocusHack(e: Event): void {
    setTimeout(() => {
      this.focusElementThrottled(e.target as HTMLInputElement)
    }, 150);
  }
```
