### ISSUE TITLE
q-btn doesn't follow custom spacing when in toolbar.

### ISSUE THREAD

**Issue by delay** [quasarframework/quasar#909]
I am adding: `$button-padding = 0px 20px 0px 20px` into app.variables.styl.  When buttons are in q-toolbar they do not follow my custom padding. When the buttons are not on q-toolbar the custom spacing is followed correctly. 

You can duplicate this by loading the starter template and adding a button in the toolbar then add a custom button-padding amount.  Using latest released version of Quasar Framework.

I am new to quasar so if I have missed some additional setting please let me know.

Thanks,
-Jeff

P.S. Really loving Quasar so far, Great Work!

**Comment by rstoenescu** [comment]
This is no longer relevant for v0.15 as there is no implicit spacing in toolbar no more. So it's easy customisable and also there are the new [Spacing CSS classes](http://quasar-framework.org/components/spacing.html).
