### ISSUE TITLE
Issue when inserting HTML non editable span on Q-Editor

### ISSUE THREAD

**Issue by MrBars24** [quasarframework/quasar#9091]
Inline display works when it is on the first line of q-editor but when it is on the next line it always go to new line which is I think not a good behavior.

![image](https://user-images.githubusercontent.com/19724597/116521260-f412d800-a8fd-11eb-8ad0-f01d3fbbd085.png)

**Comment by rstoenescu** [comment]
Hi,

Unfortunately we are not in full control over what the browser decides to output as HTML (QEditor is based on the  `document.execCommand` API). As a result we are not able to fine-tune all the possible scenarios.
