### ISSUE TITLE
Bumping vue router version to 4.0.6 required

### ISSUE THREAD

**Issue by szympol** [quasarframework/quasar#9096]
**Describe the bug**
Navigating from router-view throws Missing required param. 

**Codepen/jsFiddle/Codesandbox (required)**
https://github.com/vuejs/vue-router-next/issues/845

**Expected behavior**
User should navigate to other pages without errors

**Comment by rstoenescu** [comment]
Will be available through "@quasar/app" v3.0.0-beta.21
