### ISSUE TITLE
Allow date/time picker to choose and close without pressing "set"

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#910]
### Feature
Allow the datetime picker to select a date without having to hit "set". Just by tapping the date it automatically selects and closes the dialog.

Example of Feature
```
<q-datetime v-model="selectedDay" type="date" :set-button="false" />
```

**Comment by dsl101** [comment]
I'm sure there was an issue about this, but I'd also like double-click for this.

**Comment by NothingWeAre** [comment]
It was in issue #718.
By the way i'm too in support of this option.

**Comment by dsl101** [comment]
Actually, it was #798 I was thinking of. Looks like they could all be merged somehow into QDatetime improvements?

**Comment by webnoob** [comment]
I've got the latest source and it appears the set buttons have been removed. I was also looking for the same feature (and thought I had seen it somewhere). Haven't dug into what controls it bu certainly on the latest source I can just select the date without using the set button.

**Comment by rstoenescu** [comment]
Hi,

Yes. This ticket should now be closed. Will be available in v0.15.

**Comment by realcarbonneau** [comment]
As a reference, I will add full flexibility for all datetime picker options, while at the same time leaving the default behavior the way most people prefer it.

**Comment by webnoob** [comment]
@realcarbonneau So rather than just having the set buttons "gone" - we will disable them? That seems like a less breaking change than it is at the moment 👍 (Although for me, I prefer them off)

**Comment by realcarbonneau** [comment]
Yes, exactly.  The code is still there and the buttons do appear in specific scenarios.  It's just a question of adding some flexibility props for more customized usages.

**Comment by rstoenescu** [comment]
We also need to think about performance. Sure, every component can be enhanced infintely, but it does matter in the end how well the framework is performing. It won't matter if it can do everything but it's slow as a snail. I think it's ok have those buttons stripped out when on desktop. It also makes Datetime's UI consistent with the other form components.

**Comment by webnoob** [comment]
Fair point.
I agree with the change regarding the date time - All (most?) other libraries I've seen set the date based on the initial click, not an extra click.

**Comment by rabee05** [comment]
How can I enable this?

**Comment by MilosPaunovic** [comment]
> How can I enable this?

https://codepen.io/milospaunovic/pen/xxjjYGj?editors=1011
