### ISSUE TITLE
Add week and quarter to scope in date methods 

### ISSUE THREAD

**Issue by codingfriend1** [quasarframework/quasar#911]
Quasar currently supports

second
minute
hour
day
month
year

I've found it helpful if it supported week and quarter as well. Perhaps have the startDate of the week be configurable but default to sunday.

date.startOfDate(date, 'week', { weekStart: 'monday' })
date.endOfDate(date, 'week', { weekStart: 'monday' })
date.isSameDate(date1, date2, 'week')
date.adjustDate(date, { week: 3 })

Thanks for all your hard work. Your framework is amazing!

**Comment by rstoenescu** [comment]
Closing as duplicate.
