### ISSUE TITLE
The q-input component has a bug when inputting Chinese in the Mac Safari browser

### ISSUE THREAD

**Issue by yangjiafu** [quasarframework/quasar#9111]
Duplicate English
in the quasar v1.15.11
the Safari browser version 14.0.3
<img width="377" alt="image" src="https://user-images.githubusercontent.com/28332458/116657593-4537d000-a9c1-11eb-814b-0ed8801e7241.png">

**Comment by rstoenescu** [comment]
Hi,

The screenshot that you have posted is not the official documentation. I think it's from quasarchs.com? That's an unofficial website, not under our control so we can't do anything.

**Comment by yangjiafu** [comment]
Thank you for your reply!
This is your official website,
The website is&nbsp;https://quasar.dev/start/pick-quasar-flavour.
Please use Mac Safari to open your official website and enter Chinese to prove that there is indeed a problem with your q-input component
















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quasarframework/quasar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月1日(星期六) 凌晨0:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quasarframework/quasar] The q-input component has a bug when inputting Chinese in the Mac Safari browser (#9111)





 
Hi,
 
The screenshot that you have posted is not the official documentation. I think it's from quasarchs.com? That's an unofficial website, not under our control so we can't do anything.

**Comment by yangjiafu** [comment]
When I input Chinese, there will be repeated Pinyin

https://user-images.githubusercontent.com/28332458/117004257-72b1b000-ad18-11eb-8a96-1e5e13f70b13.mov

**Comment by yangjiafu** [comment]
> Hi,
> 
> The screenshot that you have posted is not the official documentation. I think it's from quasarchs.com? That's an unofficial website, not under our control so we can't do anything.

When I use the q-input component to input Chinese in the mac Safari browser, there will be repeated Chinese pinyin

https://user-images.githubusercontent.com/28332458/117004615-d63bdd80-ad18-11eb-8db2-7b96a3b513d8.mov

**Comment by pdanpdan** [comment]
Hello.
Can you please try if it's fixed here: https://pdanpdan.github.io/quasar-docs/vue-components/input ?

**Comment by hawkeye64** [comment]
@pdanpdan Seems like a good fix.


https://user-images.githubusercontent.com/10262924/117358959-03e96980-ae74-11eb-975f-94d86fc7e69a.mp4

**Comment by yangjiafu** [comment]
No, I can’t use this scheme.Because my project has hundreds of input boxes.And I cannot ask the user to do this.

I found that there is no such problem in version 1.14.2


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quasarframework/quasar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 凌晨4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quasarframework/quasar] The q-input component has a bug when inputting Chinese in the Mac Safari browser (#9111)





 
@pdanpdan Seems like a good fix.
 
https://user-images.githubusercontent.com/10262924/117358959-03e96980-ae74-11eb-975f-94d86fc7e69a.mp4

**Comment by hawkeye64** [comment]
@yangjiafu What do you mean by "scheme"?
