### ISSUE TITLE
QItem accessibility issue with ios voiceover

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#9115]
**Describe the bug**
A clickable and focusable `q-item` containing a `q-item-section side` with a `q-btn` does not respond to click events with ios voiceover enabled.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/poRXJgW

**To Reproduce**
1. Visit the codepen on ios mobile safari without voiceover
2. The items can be tapped to 'navigate' (see the 'Last Navigation' label as indication of the call to `routeTo()` method), and the star can be tapped to toggle the 'favourite' mark for each page
3. Enable ios voiceover
4. Now the page item can be focussed, but on double-tap, only the star button can be 'activated', and no navigation is possible.

**Expected behavior**
The item and embedded button would be separately accessible using ios voiceover to select and activate.

**Platform (please complete the following information):**
Quasar Version:  v1.15.11 

Browsers: Mobile safari 
iOS: 14.4.2

**Additional context**
This is part of a page menu structure which uses a list with items to represent clickable pages, and each page has a 'star' button to mark favourites. See the codepen for the template, and this _may_ be a bug with ios voiceover. However, I'm not sure exactly how this is supposed to work, and perhaps is something in the DOM model that the list / item / button that Quasar is generating that confuses the accessibility features.

Note the use of `role="button"` and `tabindex="0"` means that the elements _are_ focusable via keyboard, and that works as expected (the item can be focussed, and then the star button focussed separately).

**Comment by pdanpdan** [comment]
I think this is relevant: https://stackoverflow.com/questions/64522551/accessible-nested-button-inside-button

I think you can work around this by moving the button role on the first QItemSection: https://codepen.io/pdanpdan/pen/RwVWExL?editors=1010

Try it on ios and see if it will work.

**Comment by dsl101** [comment]
Thanks—can confirm that works as expected.
