### ISSUE TITLE
TypeError: cap.nativePromise is not a function. (In 'cap.nativePromise(pluginName, prop.toString(), options)'

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#9116]
capacitor iOS any quick fix for this app won't get pass write screen

<img width="766" alt="Screen Shot 2021-04-30 at 12 37 41 PM" src="https://user-images.githubusercontent.com/19895516/116690294-16b1f900-a9b1-11eb-8d69-02922565c448.png">
<img width="1103" alt="Screen Shot 2021-04-30 at 12 37 29 PM" src="https://user-images.githubusercontent.com/19895516/116690308-1ade1680-a9b1-11eb-9ba8-df299ae6a9a6.png">

**Comment by diadal** [comment]
fixed but clean up and reinstall dependance

**Comment by MohsinJamadar09** [comment]
> 
@diadal 
could you please elaborate more on this solution?

I am getting the same error

**Comment by diadal** [comment]
@MohsinJamadar09  delete `node_modules` folder
