### ISSUE TITLE
QStepper Linear Header Navigation is ignored

### ISSUE THREAD

**Issue by ThibaultJousse** [quasarframework/quasar#9118]
**Describe the bug**
Changing header-nav prop has no visible effect in Quasar V2 while it's working in Quasar V1.

**Codepen/jsFiddle/Codesandbox (required)**
Quasar V1: https://codepen.io/pen/?&editors=101&prefill_data_id=0249f208-6221-4ed4-bae7-d755f40244dc
Quasar V2: https://codepen.io/pen/?&editors=101&prefill_data_id=df316ccf-640b-4777-a17b-72fc2d8fdd72

**To Reproduce**
1. Go to Quasar V1 docs: https://quasar.dev/vue-components/stepper#example--linear-header-navigation
2. Click on steps header
3. Go to Quasar V2 docs: https://next.quasar.dev/vue-components/stepper#example--linear-header-navigation
4. Click on steps header
5. See difference

**Expected behavior**
User shouldn't be able to click on step header if its header-nav prop is false

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.14
@quasar/app Version: 3.0.0-beta.18
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers: Chromium 90.0.4430.72 
iOS:
Android:
Electron: 12.0.5

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar 2.0.0-beta.15.
