### ISSUE TITLE
QSearch |  @Click, :after, :before not working

### ISSUE THREAD

**Issue by danielcomcom** [quasarframework/quasar#912]
### Software version

Quasar:   Quasar v0.14.1
OS: Linux
Node: v7.10.0
NPM: 5.4.2
Browsers: Chrome

### What did you get as the error?
Didn't work, no noticeable errors in the inspector

### What were you expecting?
1. @Click Event to work
2. :after :before to work the same as they do on input component
 
### What steps did you take, to get the error?

Using the QSearch component as shown below:

    <q-search
      v-model="filterText"
      :debounce="600"
      @change="updateQuery()"
      @click="showMore = true"
     :after="[{icon: 'arrow downward', handler () { }}, {icon: 'attach file',   handler () { }}]"
    />

**Comment by rstoenescu** [comment]
Fix available in edge and future v0.14.4.
Thanks for reporting!

**Comment by danielcomcom** [comment]
Thanks Razvan for your unbelievably fast response! Totally loving your
framework so far!

Sent from Daniel's iPhone

On Sep 22, 2017, at 5:08 PM, Razvan Stoenescu <notifications@github.com>
wrote:

Fix available in edge and future v0.14.4.
Thanks for reporting!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quasarframework/quasar/issues/912#issuecomment-331586494>,
or mute the thread
