### ISSUE TITLE
q-gutter-xl 'eat-up' the area of previous q-card-section

### ISSUE THREAD

**Issue by bakbluelabel** [quasarframework/quasar#9123]
**Describe the bug**
When using `class='q-gutter-xl'`  in __\<q-card-section\>__, it will 'eat-up' the _previous_ __\<q-card-section\>__ area, lead to the component in the previous \<q-card-section\> will have no response to the mouse hovering (about 60% area from the bottom of the component). This happened also for `class='q-gutter-lg'`, but not so serious, it's about 20% of the area from the bottom of the component.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/KingKong-II/pen/ZELdOJg?editors=101

**To Reproduce**
1. goto the codepen link above
2. move mouse from the bottom on the QSelect component or click on the lower-half of the QSelect component (no response)

**Expected behavior**
The text (see the text __'testing...'__ on the codepen link) should be well beneath the _previous_ __\<q-card-section\>__ if `class='q-gutter-xl'`. And the QSelect component should well response to mouse hovering.

**Screenshots**
(see codepen link)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.14
@quasar/app Version: 3.0.0-beta.18
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: 14.10.1
NPM: 6.14.11
Yarn: 1.22.10
Browsers: Chrome Version 90.0.4430.85 (Official Build) (64-bit)
iOS: -
Android: -
Electron: -

**Additional context**
nil

**Comment by rstoenescu** [comment]
Hi. Use `<div>` instead of `<span>` for the children.

**Comment by rstoenescu** [comment]
```html
<q-card-section>
              <div class="q-gutter-xl">
                <div>testing...</div></q-card-section>
              </div>
           </q-card>
```

It's the nature of CSS... We've tried to explain it extensively in docs.

**Comment by bakbluelabel** [comment]
I see... understand. Thanks. 👍
