### ISSUE TITLE
BEX with multiple content_scripts ("www/bex-content-script.js")

### ISSUE THREAD

**Issue by OskarArce** [quasarframework/quasar#9124]
**Describe the bug**
When you build a BEX project with multiple content_scripts (js: [,,,, "www/bex-content-script.js"]) it fails because "www/bex-content-script.js" is translated to "www/js/bex-content-script.js" just one time.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/xxEvBLR?editors=101) or a jsFiddle (https://jsfiddle.net/rstoenescu/a2cuzods/) or a Codesandbox (https://codesandbox.io/s/optimistic-poitras-4t3m3) and hit save then copy-paste link here.

**To Reproduce**
1. Create BEX project
2. Add multiple content scripts with "www/bex-content-script.js" js
3. Build project

**Expected behavior**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ X] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ X] BEX

**Comment by rstoenescu** [comment]
Implemented this for Quasar v2 with the upcoming Quasar CLI on Vite (unreleased as of writing these lines though). Will be available through: quasar.config.js > bex > contentScripts: [ 'my-first-content-script', 'my-second-content-script', ... ]
