### ISSUE TITLE
Event row-* and Qtable (one bug and one feature request)

### ISSUE THREAD

**Issue by alemila01** [quasarframework/quasar#9132]
**Describe the bug**
Actually 2 issue on this:
the "easy" one i this warning on console:
Component emitted event "row-contextmenu" but it is neither declared in the emits option nor as an "onRow-contextmenu" prop

The second is that not work if i set grid mode.

**Expected behavior**
No warning and work in grid mode

**Comment by metalsadman** [comment]
It works fine https://codepen.io/metalsadman/pen/JjEQqpz?editors=101.
for `2` it's stated in docs already 
> @row-contextmenu -> function(evt, row, index)
Description
Emitted when user right clicks/long taps on a row; Is not emitted when using body/row/item scoped slots

**Comment by alemila01** [comment]
1) if you use production js warning dont came out
2) i dont use any slot at all so i supposed that work

https://jsfiddle.net/3z96aLt4

**Comment by metalsadman** [comment]
@alemila01 
1. use latest qv2 version https://jsfiddle.net/1xfqmzwp/
2. read my last reply, the one in bold.

**Comment by metalsadman** [comment]
@alemila01 
use latest qv2 version https://jsfiddle.net/1xfqmzwp/, or fork the one from https://codesandbox.io/s/optimistic-poitras-4t3m3.

**Comment by alemila01** [comment]
I already told you that is a problem in dev mode not in production... 

https://codesandbox.io/s/kind-hill-cw02c

**Comment by rstoenescu** [comment]
Pushed a workaround until the bug can be fixed in Vue.
Was possible due to another event related fix that went into vue 3.0.11 (https://github.com/vuejs/vue-next/commit/c1cd42e627bdeb561d54e64ea5fea87ccbbae637)

Workaround will go into v2.0.0-beta.18.
