### ISSUE TITLE
Cordova Interface changes on 9.1.0

### ISSUE THREAD

**Issue by CharlesJQuarra** [quasarframework/quasar#9135]
**Describe the bug**

I am using Cordova-android plugin from a v2.1.15 quasar app. In cordova version 9.0.0, the `cordova` object had the following keys:

```
document.addEventListener('deviceready', () => {
  console.log(`{Object.keys(cordova)}`)
}, false)
output:
define,require,version,platformVersion,platformId,addWindowEventHandler,addStickyDocumentEventHandler,
addDocumentEventHandler,removeWindowEventHandler,removeDocumentEventHandler,getOriginalHandlers,
fireDocumentEvent,fireWindowEvent,callbackId,callbacks,callbackStatus,callbackSuccess,callbackError,
callbackFromNative,addConstructor,exec,plugins
```

On version 9.1.0, this interface object has some important differences:

```
document.addEventListener('deviceready', () => {
  console.log(`{Object.keys(cordova)}`)
}, false)
output:
define,require,version,platformVersion,platformId,addWindowEventHandler,addStickyDocumentEventHandler,
addDocumentEventHandler,removeWindowEventHandler,removeDocumentEventHandler,getOriginalHandlers,
fireDocumentEvent,fireWindowEvent,callbackId,callbacks,callbackStatus,callbackSuccess,callbackError,
callbackFromNative,addConstructor
```

As you can see, the objects `exec` and `plugins` are absent, which is how we interact with native components

Btw, the upgrade I did was as simple as doing `cordova platform remove android` and `cordova platform add android@9.1.0` and rerunning the same codebase with `quasar dev -m cordova -T android -e android-phone-dev`

**Expected behavior**
`exec` and `plugins` should still show up inside the cordova object

**Platform (please complete the following information):**

@quasar/app Version: 2.1.15
Quasar mode:

  - [X ] Cordova

Tested on:
  - [X ] Cordova

OS: OS X 10.13.6
Node: v12.21.0
NPM: 7.7.5
Yarn:

**Comment by rstoenescu** [comment]
Hi,

Quasar is not in control over Cordova's code. You should head over to Cordova's forum/team.

**Comment by CharlesJQuarra** [comment]
Actually @rstoenescu I posted the problem first on Cordova: https://github.com/apache/cordova-android/issues/1225

In short, some of the interface functions missing are not even defined by cordova, so presumably the 3rd party framework is adding it somewhere. I spent about an hour looking through the quasar plugin code for cordova, and I couldn't make sense of the source of the issue. 

I recommend to not close the issue before making sure the problem is not on quasar

**Comment by rstoenescu** [comment]
**Quasar does NOT tamper with the "cordova" object in any way**. If you were told that 3rd party changes it in any way, they were referring to the Cordova plugins.
