### ISSUE TITLE
webpack error: "Can't resolve" for css url()

### ISSUE THREAD

**Issue by therealcoder1337** [quasarframework/quasar#9136]
**Describe the bug**
in quasar v2 with webpack 4 you could write the following css with a `image.png` (or .jpg etc.) in `public/`:

```css
.my-class {
  background: url(/image.png)
}
```
with the upgrade to webpack 5 however, you will get an error similar to:

`Can't resolve '/image.png' in '/home/user/.....`

users have basically two options to fix this right now:

1. provide a path relative to the css file (but then it won't be served from `/public`)
2. add the following comment above every css rule that uses `url()` with an image in `/public`: `/* webpackIgnore: true */`

**Expected behavior**
for backward compatibility, i shouldn't be required to change my css/less/sass when upgrading to the latest quasar beta.

**Platform (please complete the following information):**

tested with quasar v2 beta 14 and quasar app v3 beta 18. cli. spa. linux.

**Comment by rstoenescu** [comment]
Thank you for this ticket.
Enhancement will be available in "@quasar/app" v3.0.0-beta.20.
