### ISSUE TITLE
RTL Transformation with source: rtl not working

### ISSUE THREAD

**Issue by Saeid-Za** [quasarframework/quasar#9145]
**Describe the bug**
Hello,
After updating to Quasar v2, and setting quasar.conf.js > “build” > rtl > “source” to "ltr" (replacing "fromRTL" -> true) meaning quasar css should be transformed to RTL, this transformation never happens.

**To Reproduce**
1. create a new project with `quasar create <name> --branch next`
2. set  “build” > rtl > “source” to "ltr"
3. set "framework" > "lang" to "fa-IR" or any RTL language pack.
3. open the application with `quasar dev`

**Expected behavior**
when setting rtl > source to "ltr", quasar styles should be transformed to RTL version.
This issue only exists on quasar v2.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux(5.4.0-72-generic) - linux/x64
Node: 14.16.1
NPM: 6.14.13
Yarn: 1.21.1
Browsers: Chrome
iOS: -
Android: -
Electron: -

**Additional context**
I'm working on a pull request, should be ready soon to fix this issue.

**Comment by hawkeye64** [comment]
> set “build” > rtl > “source” to "ltr"

This looks wrong. It should be:
```js
build: {
  rtl: true
}
```
https://next.quasar.dev/options/rtl-support#enabling-rtl-support

**Comment by rstoenescu** [comment]
@Saeid-Za 

Thank you for reporting!
Fix will be available in "@quasar/app" v3.0.0-beta.19

**Comment by Saeid-Za** [comment]
Just a side note, in the docs, it is stated that rtl also could take postcss-rtl plugin options, based on that, setting `source` to ltr, means that we have our userland CSS in LTR which is not true.

`source` should be set to `rtl` and docs should be updated accordingly.

**Comment by rstoenescu** [comment]
Thanks for pointing this out. Fixed docs also.
Preparing the new release now ;)
