### ISSUE TITLE
QChatMessage component should support #text slot to enable multiple message entries in slots

### ISSUE THREAD

**Issue by lyle45** [quasarframework/quasar#9148]
**Is your feature request related to a problem? Please describe.**
QChatMessage component should support #text slot to enable multiple message entries in slots

Chat slots should be able to mimic props behavior completely

In continuance to this discussion 
https://github.com/quasarframework/quasar/discussions/9142

example can be found here

https://codepen.io/lyle45/pen/ZELgJqB

**Describe alternatives you've considered**
It's possible to mimic this behavior with css using negative margin to mock that white strip that separates messages but it's hackish

Solution i offer is to use #text slot scope that recieves currently iterated text message that's recieved through text prop
Actually, chat component should probably also support stamp slot, label slot and name slot

**Comment by rstoenescu** [comment]
Ported to v1 as well.
So, it will be available in Quasar v2.0.0-beta.16 and Quasar v1.15.14

**Comment by lyle45** [comment]
@rstoenescu Amazing! lots of thanks for responsivnes!

To continue this, opened,

https://github.com/quasarframework/quasar/issues/9243

 maybe that could be integrated into that version as well
