### ISSUE TITLE
Not creating a BEX application for dev mode v2.0.0-beta.14

### ISSUE THREAD

**Issue by whiteua** [quasarframework/quasar#9153]
**Describe the bug**
After updating to v2.0.0-beta.14 it stopped creating the application for "quasar dev --mode bex"
Completely missing file structure in \src-bex\www\ folder:
index.html and all working js files except

For the command "quasar build --mode bex" the project compiles correctly

**To Reproduce**
1. quasar create quasarbextest --branch next
2. quasar mode add bex
3. quasar dev --mode bex

**Expected behavior**
I expect to create files in the \src-bex\www\ directory that I can load into Chrome extention to debug the project.

**Screenshots**

#### run quasar dev --mode bex 
![image](https://user-images.githubusercontent.com/6796581/116870902-0cdffe00-ac1c-11eb-8471-39b9929c8f73.png)
#### after compiling (Error)
![image](https://user-images.githubusercontent.com/6796581/116870962-2a14cc80-ac1c-11eb-8cc5-093473f4d005.png)

#### run: quasar build --mode bex (Ok)
![image](https://user-images.githubusercontent.com/6796581/116871810-86c4b700-ac1d-11eb-8977-2c39730170b6.png)

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.14
@quasar/app Version: v3.0.0-beta.18
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [x] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [x] BEX

OS: Windows 10
Node: v14.16.0
NPM:  6.14.11
Yarn:
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
Dev mode.......... bex
 Pkg quasar........ v2.0.0-beta.14
 Pkg @quasar/app... v3.0.0-beta.18
 Pkg webpack....... v5
 Debugging......... enabled

**Comment by rstoenescu** [comment]
Seems like the `write-file-webpack-plugin` is not compatible with Webpack 5.
The maintainer requests help to do it. More info: https://github.com/gajus/write-file-webpack-plugin/issues/73

Fortunately, there are other ways to achieve the same thing that `write-file-webpack-plugin` does. I am going to drop this dependency in favor of webpack-dev-middleware's "writeToDisk" option.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in "@quasar/app" v3.0.0-beta.19

**Comment by whiteua** [comment]
Thanks for the quick response!
The files compiled and I was able to continue debugging. 

I would like to point out another bug that occurred after the last update. 

During debugging, error messages appear 
**WebsocketClient.js?1872:40 WebSocket connection to 'ws://0.0.0.0/ws' failed:**
This happens on a "clean" QASAR-CLI installation out of the box. 

 » App dir........... C:\Dev\Temp\quasarbextest
 » Dev mode.......... bex
 » Pkg quasar........ v2.0.0-beta.15
 » Pkg @quasar/app... v3.0.0-beta.20
 » Transpiled JS..... yes (Babel)

![image](https://user-images.githubusercontent.com/6796581/117065533-502b9100-ad30-11eb-8d97-6a5f7a16c947.png)

**Comment by rstoenescu** [comment]
Yes, saw it too but had to release as is for now so that dev mode at least works. Seems like a deep problem with the new webpack-dev-server. Looking for a way to fix it but until then a manual refresh is necessary.

**Comment by rstoenescu** [comment]
Finally, the underlying problem was fixed in webpack-dev-server v4.0.0-beta.3.
It allowed me to do the final fix in q/app.

HMR will work correctly in "@quasar/app" v3.0.0-beta.25.

**Comment by rstoenescu** [comment]
And released it.
