### ISSUE TITLE
Cannot override components/directives option

### ISSUE THREAD

**Issue by Trinovantes** [quasarframework/quasar#9156]
**Describe the bug**
In v2, the `opts` is [destructured first](https://github.com/quasarframework/quasar/blob/vue3-work/ui/src/index.all.js#L19) whereas in v1 [it is at the end](https://github.com/quasarframework/quasar/blob/dev/ui/src/index.common.js#L16)

**Expected behavior**
Same behavior as v1 where specifying `opts.components` will only load the components that I want

**Background**
I'm using a custom build process with webpack (outside of the quasar cli) and aliased `quasar` to `quasar/src/index.all` to get tree shaking.

**Comment by rstoenescu** [comment]
Fair point.
Will be available in Quasar v2.0.0-beta.16.

**Comment by hawkeye64** [comment]
@rstoenescu I am just curious. If you specify a component in markdown (this would normally not get automatically added) and had to specify it in quasar.conf.js, so all you had was the lone component, does that stop the automatic inclusion for the rest, that is in Vue SFC files?
