### ISSUE TITLE
Can't Type When Building For iOS

### ISSUE THREAD

**Issue by BrianMoreno1994** [quasarframework/quasar#918]
### Software version

Quasar: Edge (git+https://git@github.com/quasarframework/quasar-edge.git)
OS: iOS 10

What did you get as the error?
- I have a couple of textboxes and some buttons on my page. The problem occurs when building with iOS theme and running the app in an emulator using cordova, I still get the material style textboxes, another issue I'm having is trying to type. I can't type in them when running the app in the emulator. Sometimes the keyboard won't even show up. This is an example video of me trying to type on the iOS simulator: [https://youtu.be/3HR0ZDigqKI](https://youtu.be/3HR0ZDigqKI). 

What were you expecting?
- iOS style textboxes and being able to type in them.

What steps did you take, to get the error?
- I tried a  couple of thing:
  1. Building the app with the terminal command specified in the docs: `quasar build ios`. I then entered the cordova folder and ran the app with `cordova run ios --emulate`.

  2. I tried changing the style directly in the `main.js` file, I uncommented the first option and commented the second option:

```
    // === DEFAULT / CUSTOM STYLE ===
    // WARNING! always comment out ONE of the two require() calls below.
    // 1. use next line to activate CUSTOM STYLE (./src/themes)
    require(`./themes/app.ios.styl`)
    // 2. or, use next line to activate DEFAULT QUASAR STYLE
    //require(`quasar/dist/quasar.${__THEME}.css`)
    // ============================== 
```

I tried these steps a couple of times and still wasn't getting the full iOS theme and still couldn't type. Is this a known bug or is it just me?

**Comment by cosformula** [comment]
are you typing chinese ?
see #1170

**Comment by rstoenescu** [comment]
In emulator you need to hit Cmd + K for keyboard to show up.
