### ISSUE TITLE
QSelect 'item-class' prop does not work

### ISSUE THREAD

**Issue by SKFrozenCloud** [quasarframework/quasar#9182]
**Describe the bug**

The prop 'item-class' does not work for QSelect.

**Codepen/jsFiddle/Codesandbox (required)**

[https://codepen.io/sk6315/pen/oNZNqjV](https://codepen.io/sk6315/pen/oNZNqjV)

**To Reproduce**

Go to the Codepen.

**Expected behavior**

In the Codepen the QSelect selected option should be on the right side but is not since 'item-class' does not work

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: ^2.0.0-beta.12
@quasar/app Version: ^3.0.0-beta.15
Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux
Node: 14
NPM:
Yarn:
Browsers: Firefox
iOS:
Android:
Electron:

**Additional context**

**Comment by metalsadman** [comment]
there's no `item-class` in q-select's api, perhaps you're looking for something like `popup-content-class` instead.

**Comment by SKFrozenCloud** [comment]
![image](https://user-images.githubusercontent.com/39242670/117326868-5c2f6400-ae92-11eb-9926-c78eb588a51d.png)

**Comment by metalsadman** [comment]
@SKFrozenCloud please point where you've seen `item-class` in the api.

**Comment by SKFrozenCloud** [comment]
@metalsadman You are right, I did not read it properly.
