### ISSUE TITLE
VUEX does not appear in Vue dev tools

### ISSUE THREAD

**Issue by Sacrekin** [quasarframework/quasar#9183]
In Chrome Vue Devtools beta, we can access components & Routes but there is no option for Vuex

Quasar Version: V2 beta 14
@quasar/app Version: V3 beta 18
Quasar mode:
  - [ X] SPA
  - [ ] SSR
  - [X ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
![image](https://user-images.githubusercontent.com/30285648/117274579-7dc22880-ae5d-11eb-924a-a50a4f805b3d.png)

OS:
Node:
NPM:
Yarn: X
Browsers: Chrome V90
iOS:
Android:
Electron:

PS: Chrome console shows this message: "DevTools failed to load SourceMap: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/util.js.map"

**Comment by Sacrekin** [comment]
Forgot to mention Vue Devtools version: Vue.js devtools 6.0.0 beta 8

**Comment by rstoenescu** [comment]
Please open a ticket on Vue Devtools repo. This has nothing to do with Quasar.
