### ISSUE TITLE
Using conditional rendering in body-cell slot yields empty table rows

### ISSUE THREAD

**Issue by jippeholwerda** [quasarframework/quasar#9185]
**Describe the bug**
Using conditional rendering in body-cell slot yields empty rows.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jippeh/pen/yLMLpvW

**Expected behavior**
Template logic is evaluated and the cells are rendered properly.

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta-15

**Additional context**
Removing the `v-if` and `v-else` renders the cells properly.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-rc.1
