### ISSUE TITLE
pattern prop support for QInput

### ISSUE THREAD

**Issue by Lyokolux** [quasarframework/quasar#9189]
**Is your feature request related to a problem? Please describe.**
It is currently a lame to have to handle pattern matching in JS, while a regex can be used.

**Describe the solution you'd like**
A prop `pattern` to QInput that will directly be applied on the `<input>`.
For example, `<q-input pattern="[0-9]" />` should force the field to have only the characters '0123456789'.
It is currently an HTML standard (see https://html.spec.whatwg.org/multipage/input.html#the-pattern-attribute).

**Describe alternatives you've considered**
* Using JS (inserting the pattern attribute after the component has been mounted or checking it with validators)
* Masks are not powerful enough since they have a fixed pattern.
¯\\_(ツ)_/¯

**Comment by pdanpdan** [comment]
Use the HTML native `pattern` attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
