### ISSUE TITLE
"usr/lib/node_modules/quasar-cli/bin/quasar-list(1) does not exist, try --help"

### ISSUE THREAD

**Issue by alidplus** [quasarframework/quasar#919]
I install quasar-cli globaly but when i want to use commands termux throw this error:

usr/lib/node_modules/quasar-cli/bin/quasar-list(1) does not exist, try --help

/data/data/com.termux/files/usr/lib/node_modules/quasar-cli/bin/quasar-init(1) does not exist, try --help

/data/data/com.termux/files/usr/lib/node_modules/quasar-cli/bin/quasar-list(1) does not exist, try --help

But its bullshit that file exist! 
I found similar issues on vue-cli but not any fix was there.

Tnx

Quasar: 0.6.4
OS: android 6 and 7 with termux
Node:6.11.2
NPM:3.10.10

**Comment by rstoenescu** [comment]
Please redirect this to the appropriate repo: https://github.com/quasarframework/quasar-cli
Thanks.
