### ISSUE TITLE
Support for iconify

### ISSUE THREAD

**Issue by fredericoregateiro** [quasarframework/quasar#9190]
**Is your feature request related to a problem? Please describe.**
Improve icon font loading and support mutiple icon font's

**Describe the solution you'd like**
Support https://iconify.design/ to improve icons loading times

**Comment by rstoenescu** [comment]
Hi,

There's nothing stopping you from using iconify in your apps. However, if you want this to work with QIcon, there are multiple reasons why this cannot happen. It doesn't plays nice when on a Vue component and furthermore we definitely don't want to include external libs thus bloating the framework. But if you're thinking "hey, I can use x thousands of icons and only load what I need" then simply using the `@quasar/extras` with the svg flavour does just that.
