### ISSUE TITLE
q-stepper header-nav aligns itself to right when only one q-step is appear.

### ISSUE THREAD

**Issue by SamnnyWong** [quasarframework/quasar#9192]
q-stepper header-nav aligns itself towards the right when only one q-step appears.
when I disable the following CSS in chrome dev tool it aligns itself to left
But when there are two steps or more everything looks normal.
.q-stepper__header--standard-labels .q-stepper__tab:last-child {
    justify-content: flex-end;
}
and the following css got disabled by itself for some reason
q-stepper__header--standard-labels .q-stepper__tab:first-child {
    justify-content: flex-start;
}
it looks like q-stepper recognize it as the last child when there is only one q-step appears.

codepen: https://codepen.io/samnnywong/pen/jOBEmQb

I am not sure if this is expected behaviour, but if it is, is there a proper way to make it aligns to left?

<img width="344" alt="Screen Shot 2021-05-07 at 20 00 01" src="https://user-images.githubusercontent.com/2942477/117446804-362bc180-af6f-11eb-8a9b-b872878e449b.png">

<img width="376" alt="Screen Shot 2021-05-07 at 19 59 57" src="https://user-images.githubusercontent.com/2942477/117446819-3d52cf80-af6f-11eb-8ffc-3fabc4b46565.png">

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.17 & Quasar v1.15.15.
