### ISSUE TITLE
Homepage Accessibility Issue

### ISSUE THREAD

**Issue by BradCoffield** [quasarframework/quasar#9193]
Wanted to let you know that the spinning stars on your homepage make me nauseous almost immediately any time I load it. I don't have trouble with really any other site I've ever been to, though I do have an ear condition that makes me prone to nausea and dizziness. I'd like to suggest that you make it a static background to help others like me across the internet. Thank you.

**Comment by IlCallo** [comment]
We plan to fully rework the landing page in some months, we'll consider this point of view too.
Thanks for sharing!
