### ISSUE TITLE
Qr Code Reader

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#9194]
if you be great if Quasar can have it own Qr-Coder Scanner just like the `QUploader` that work with all platform and able to access the camera. is will be nice to have default `QCodeReader` or `QCodeScanner` a clone copy of `QUploader` can easily be migrate to `QCodeReader` since `QUploader` has ability to open camera

**Comment by diadal** [comment]
this only support quasar v1

**Comment by hawkeye64** [comment]
@patrickmonteiro Any plans to create a Quasar v2/Vue v3 version?

**Comment by diadal** [comment]
in addition, it only works on the web and android App not working ios App

**Comment by rstoenescu** [comment]
Hi.

This would be better suited for Github Discussions.
But to answer about a QR code reader component in Quasar core -- it's a no-go. There are solutions out there (especially for mobile platforms), but we do not plan to reinvent the wheel with our own.
