### ISSUE TITLE
Webpack 5 not bundling inline-assets from css

### ISSUE THREAD

**Issue by toralux** [quasarframework/quasar#9195]
**Webpack 5 not bundling inline-assets from css**
Starting with version @quasar/app-v3.0.0-beta.16 that use Webpack 5, inline-assets, such as url()-file-references are not bundled correctly as inline assets (was using url-loader from Webpack 4) any more. Example from css that is referenced in quasar.conf.js, css-array:

`@font-face {
  font-family: DXIcons;
  src: local("DevExtreme Generic Icons"),local("devextreme_generic_icons"),url(icons/dxicons.woff2) format("woff2"),url(icons/dxicons.woff) format("woff"),url(icons/dxicons.ttf) format("truetype");
  font-weight: 400;
  font-style: normal;
}`

**To Reproduce**
1. When using @quasar/app": "3.0.0-beta.13" the icon from dxicons font is rendered on DxButton on Index.vue page
2. When using @quasar/app": "3.0.0-beta.20" the icon from dxicons font is not rendered on DxButton on Index.vue page

**Expected behavior**
Expected icon from dxicons font to be rendered on Index.vue page

**Screenshots**
Working:
![image](https://user-images.githubusercontent.com/422309/117485988-5c4e6300-af69-11eb-8f24-2083c236d9df.png)
Not working:
![image](https://user-images.githubusercontent.com/422309/117486179-9ae41d80-af69-11eb-86d7-241018557bba.png)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.15
@quasar/app Version: 3.0.0-beta.20
Quasar mode: all modes

OS: Windows and Macos
Node: 14.16.0 and 16.0.0
NPM: 6.14.11 and 7.11.2
Yarn: 1.22.5 and 1.22.10
Browsers: All browsers

**Additional context**
Example that works in Webpack 4 version and doesn't work in Webpack 5 version: [quasar2test.zip](https://github.com/quasarframework/quasar/files/6443311/quasar2test.zip)

**Comment by rstoenescu** [comment]
Hi,

Checked quasar2test.zip. The files that you are referencing (icons/dxicons.[...]) are missing. This is your public/icons folder:

![icons](https://user-images.githubusercontent.com/4665641/117666965-1255bf00-b1ad-11eb-8de5-e3f320709c11.png)

![icons2](https://user-images.githubusercontent.com/4665641/117667012-1e418100-b1ad-11eb-9393-bbe92ae935b1.png)

**Comment by toralux** [comment]
Old Webpack 4 version supported having the icon-files available in a relative-folder to the css-file from npm-package-folder referencing them, e.g. in /node_modules/devextreme/dist/css/icons (referenced using url() from /node_modules/devextreme/dist/css/dx.light.css) and built them into the bundle, but looks like the new Webpack 5 version refers the the file instead of bundling them as base64, and needs them in the public folder.. Copied the files from /node_modules/devextreme/dist/css/icons to /public/icons and now it works. Thanks :)

**Comment by rstoenescu** [comment]
Ok, spent time to dig as deeper as possible into this. Problems appeared due to the newer css-loader.
Handling of url() should now be exactly as it was before.

Available in "@quasar/app" v3.0.0-beta.24

**Comment by rstoenescu** [comment]
FYI: just released q/app beta.24.

**Comment by toralux** [comment]
@rstoenescu Great, q/app beta.24 works great again, css-loader and url() works as before :D Cheers! 👍
