### ISSUE TITLE
about how to reduce noused css 

### ISSUE THREAD

**Issue by AprilZhangyiyi** [quasarframework/quasar#9199]
i have a question, how to use purgecss-webpack-plugin config the vue.config.js to  reduce noused css code,  i use like 'full-width' class, but the app[hash].css not include it

**Comment by rstoenescu** [comment]
Hi. We've played with purgecss but it's very unreliable and requires a ton of customization. So we'll not be shipping it out of the box. For questions please use Github Discussions instead.
