### ISSUE TITLE
I can't import Cookies, LocalStorage

### ISSUE THREAD

**Issue by ejlocop** [quasarframework/quasar#920]
### Software version

Quasar: 0.0.18
OS: Windows 7 64bit
Node: v6.10.2
NPM: 3.10.10
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
ERROR in ./~/kaiser/lib/index.js
You may need an appropriate loader to handle this file type.
### What were you expecting?
I'm not using quasar-framework in my whole application. i only want to use the Cookies and LocalStorage helpers. 
so i just installed the `npm install --save-dev quasar`.

but when i `import { LocalStorage,Cookies } from 'quasar'`

it say's about the `kaiser` package. it needs an appropriate loader? what could that be?..

I am expecting to import the Cookies and LocalStorage. but instead i got an error.

### What steps did you take, to get the error?
i just put this `import { Cookies, LocalStorage } from 'quasar'` in one of my js file.

**Comment by ejlocop** [comment]
sorry! 
i noticed in my other quasar project that `quasar` is aliased to `quasar-framework`. haha

**Comment by rstoenescu** [comment]
"Quasar: 0.0.18" ??
