### ISSUE TITLE
[docs] Banner not visible in dark mode, recolor?

### ISSUE THREAD

**Issue by DeathVenom54** [quasarframework/quasar#9205]
The quasar banner on the Github readme is hardly visible for dark mode users (see attached screenshot).
My suggestion is to make it a tone of mid-grey so that it's equally visible in light + dark mode
![image](https://user-images.githubusercontent.com/65107979/117560801-83fb1380-b0ae-11eb-9819-7eb5dd9451a6.png)

**Comment by DeathVenom54** [comment]
I'll try to do it and send a PR

**Comment by hawkeye64** [comment]
@DeathVenom54 We are in the midst of getting a new marketing change, including icons and such. Hopefully, the new ones will be more respectful of dark mode. I will pass along the information you have provided to the marketing team. Thanks.
