### ISSUE TITLE
Improve doc on Vuex

### ISSUE THREAD

**Issue by shadowrad** [quasarframework/quasar#9210]
Vuex recomends (or at least say) that you should use an action to call mutations. 
In the example for vex ([https://quasar.dev/quasar-cli/vuex-store](https://quasar.dev/quasar-cli/vuex-store)) you directly call the mutation from the vue file. 
It would be really helpfull if you add it to the example because calling the mutation from the vue file works fine but its doesn't work for the action.

Regards

**Comment by metalsadman** [comment]
What you're seeing is correct way of doing `two-way binding` using vuex data in a v-model. https://vuex.vuejs.org/guide/forms.html#two-way-computed-property

**Comment by metalsadman** [comment]
@shadowrad 
What you're seeing is correct way of doing `two-way binding` using vuex data in a v-model. https://vuex.vuejs.org/guide/forms.html#two-way-computed-property
