### ISSUE TITLE
Cannot build after update : Cannot read property 'prefix_exceptions' of undefined`

### ISSUE THREAD

**Issue by afnan** [quasarframework/quasar#9213]
**Describe the bug**
After doing an update the project can no longer be compiled. Multiple module build fails.

`Module build failed (from ./node_modules/postcss-loader/src/index.js):
  TypeError: Cannot read property 'prefix_exceptions' of undefined`

**To Reproduce**
1. npm outdated
2. npm update

**Platform (please complete the following information):**
Quasar Version: 2.2.6
@quasar/app Version:
Quasar mode: SPA

OS: Win10 
Node: 13.12.0
NPM: 6.14.4

**Comment by rstoenescu** [comment]
Can you delete node_modules and package-lock.json files and npm install again pls?

**Comment by afnan** [comment]
Yes, I have tried that already. I downgraded and it compiled again.

**Comment by rstoenescu** [comment]
Can you supply a reproduction repo pls? I can't reproduce it.

**Comment by afnan** [comment]
How do I do it?

**Comment by lijing666** [comment]
Maybe this is 'caniuse-lite' problem, they have published a bad version this days and fixed it immediately, see this [prefix_exceptions issue](https://github.com/browserslist/caniuse-lite/issues/74)

**Comment by rstoenescu** [comment]
> Maybe this is 'caniuse-lite' problem, they have published a bad version these days and fixed it immediately, see this [prefix_exceptions issue](https://github.com/browserslist/caniuse-lite/issues/74)

Good point! Thanks for sharing!
