### ISSUE TITLE
[Suggestion] Improve the tree component

### ISSUE THREAD

**Issue by kevingermain** [quasarframework/quasar#922]
I'd like so much to, at least, be able to add checkboxes behavior to the tree component like this vuejs plugin : https://halower.github.io/vue2-tree/

What do you think?

**Comment by kevingermain** [comment]
I find a good temporary solution with an icon and transverse the tree to change it.

![screenshot at 01-23-44](https://user-images.githubusercontent.com/1334099/30835649-88e78fca-a259-11e7-96de-86c6fa732590.png)

**Comment by rstoenescu** [comment]
Yes, will do. Got some ideas to improve QTree too.

**Comment by rstoenescu** [comment]
QTree just received a great revamp. It's 99.99% v1.0 ready.
Available in future v0.15.
