### ISSUE TITLE
SSR mode set build  publicPath ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#9226]
SSR mode set build  publicPath ERR_TOO_MANY_REDIRECTS

```
 build: {
      publicPath: "/mobile/"
 }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/354878/117754689-6c0dc600-b24d-11eb-8e64-f85f2cd08884.png)
![image](https://user-images.githubusercontent.com/354878/117754722-7cbe3c00-b24d-11eb-94dc-729035faa19c.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.0-beta.22
Quasar mode:
  - [x] SSR

Tested on:
  - [x] SSR

OS: mac 
Node: 14
NPM: 7
Yarn: 1

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available through "@quasar/app" v3.0.0-beta.23
