### ISSUE TITLE
prefetch.d.ts redirect: (url: RouteRecordRaw) => void; error

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#9228]
error

prefetch.d.ts redirect: (url: RouteRecordRaw) => void;

correct

prefetch.d.ts redirect:(to: RouteLocationRaw) => void

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.0-beta.20

**Comment by IlCallo** [comment]
@panhezeng which error do you get?
Parameter names don't throw errors, you can write there `redirect: (timywhimeystuff: RouteLocationRaw) => void` and it will work anyway when using it

**Comment by panhezeng** [comment]
ts check error , can't pass lint. I temporarily use this method: `const redirect = options.redirect as (to: RouteLocationRaw) => void;` But inconvenient, this problem is easy to modify, although it is not a serious problem.

**Comment by IlCallo** [comment]
Can you please write here the actual error?

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in "@quasar/app" 3.0.0-beta.24.
