### ISSUE TITLE
VSCode IntelliSense suggestions pop up as I type 'reactive', but 'reactive' not in  the list.

### ISSUE THREAD

**Issue by zhouyou-az** [quasarframework/quasar#9235]
**Describe the bug**
I want to quickly import  reactive or other function from vue.
Although d.ts files  in   .node_modules/@vue floder can't trigger code completion  , d.ts files  in   .node_modules/quasar/dist/types  floder can trigger code completion.

OS:win10
Node:14.16.1
NPM:6.14.12
Yarn: 1.22.10
Browsers:Chrome

**Comment by hawkeye64** [comment]
@zhouyou-az Wouldn't this be more appropriate in the discussions on the Vue repo?

**Comment by hawkeye64** [comment]
@zhouyou-az It depends on your editor and any plugins you might be using that look for typings...
In many cases, they look for package.json and the "typings" key to find the `.d.ts` main file.
For example:
![image](https://user-images.githubusercontent.com/10262924/117843197-d9b0f680-b23b-11eb-9ca6-4eec183319ac.png)
But, this has nothing to do with Quasar...

**Comment by soulsam480** [comment]
> @zhouyou-az It depends on your editor and any plugins you might be using that look for typings... In many cases, they look for package.json and the "typings" key to find the `.d.ts` main file. For example: ![image](https://user-images.githubusercontent.com/10262924/117843197-d9b0f680-b23b-11eb-9ca6-4eec183319ac.png) But, this has nothing to do with Quasar...

I'm facing this issue from a long time, the import intellisense works perfectly fine with a normal vue 2/3 project (generated from vue cli or vite CLI or custom) when I type some API function but it doesn't work in quasar projects. I have to explicitly import it. I'm not sure if you understood the question @hawkeye64  CC @yusufkandemir . Thanks

**Comment by IlCallo** [comment]
We're actually aware of the problem, TS recently started ignoring symbols from transitional dependencies, on which Quasar heavily relies on, and didn't provide any escape hatch
We're searching for a way to restore this core feature, but still haven't found it

**Comment by soulsam480** [comment]
> We're actually aware of the problem, TS recently started ignoring symbols from transitional dependencies, on which Quasar heavily relies on, and didn't provide any escape hatch We're searching for a way to restore this core feature, but still haven't found it

Thanks for this update.

**Comment by soulsam480** [comment]
> We're actually aware of the problem, TS recently started ignoring symbols from transitional dependencies, on which Quasar heavily relies on, and didn't provide any escape hatch We're searching for a way to restore this core feature, but still haven't found it

Hii @IlCallo , the intellisense somehow worked today, but the catch is it only works when there is an import from vue already. But again this is not perfect.

Here I have an existing import for `computed` from vue and when I type `ref` it gives me intellisense.
![image](https://user-images.githubusercontent.com/35460828/137253693-1ca8c591-06af-456c-89ef-511815cd4b43.png)

**Comment by IlCallo** [comment]
Well, yesterday VSCode stopped doing auto-imports from lodash package in my projects, so I guess the problem is only partially related to Quasar 😄 
If you want to dig further and check out how we could make TS recognize transitional deps, that would help us out!

**Comment by soulsam480** [comment]
Will read more into it

**Comment by soulsam480** [comment]
> Well, yesterday VSCode stopped doing auto-imports from lodash package in my projects, so I guess the problem is only partially related to Quasar smile If you want to dig further and check out how we could make TS recognize transitional deps, that would help us out!

Is it possible to add vue as a dependency explicitly ? I did it and the types are working as expected. But is it ok to add vue as dependency even though it's inside quasar ?

**Comment by IlCallo** [comment]
Read up [here](https://github.com/quasarframework/quasar/pull/10277#issuecomment-942534889) why we cannot do this, at least for Qv2 lifecycle

That said, for sure you can install it on your project, but then you'd need to keep it in sync manually at each Vue/Quasar release, that's why we are searching for other ways to solve this problem which don't rely on adding all deps into the dev project package.json

**Comment by soulsam480** [comment]
> Read up [here](https://github.com/quasarframework/quasar/pull/10277#issuecomment-942534889) why we cannot do this, at least for Qv2 lifecycle
> 
> That said, for sure you can install it on your project, but then you'd need to keep it in sync manually at each Vue/Quasar release, that's why we are searching for other ways to solve this problem which don't rely on adding all deps into the dev project package.json

yes yes, got your point, keeping it synced manually is a tedious task. Also I don't think vue 3 has a @types/vue-next ts declarations package like vue 2, right ?

**Comment by IlCallo** [comment]
Nope... Which is good, but bad in this case
Anyway, I also noticed VSCode now started to suggest me vue symbols once I import the first one, which is an improvement, but I dunno if it's TS, VSCode or vue who allow for this now

**Comment by soulsam480** [comment]
> Nope... Which is good, but bad in this case Anyway, I also noticed VSCode now started to suggest me vue symbols once I import the first one, which is an improvement, but I dunno if it's TS, VSCode or vue who allow for this now

I'm also unsure.

**Comment by soulsam480** [comment]
@IlCallo This is a workaround for now I think, and IMO this will solve the TS import issue without any hard work from you guys what do you think ? https://github.com/antfu/unplugin-auto-import check the quasar section

**Comment by IlCallo** [comment]
I'm honestly impressed by that package, but I don't think it's a good idea to enforce it to the whole community
Still searching for other workarounds which don't require any action taken from the end user

**Comment by soulsam480** [comment]
> I'm honestly impressed by that package, but I don't think it's a good idea to enforce it to the whole community
Still searching for other workarounds which don't require any action taken from the end user

Sorry I din't mean it that way, I suggested that it's a good workaround for now, till we we find something more reliable and less hack-ish.

**Comment by rstoenescu** [comment]
Under the hood change in q/app v3.3 will make this work correctly.
