### ISSUE TITLE
q-linear-progress

### ISSUE THREAD

**Issue by tinohager** [quasarframework/quasar#9237]
**Describe the bug**
If q-linear-progress is used with `reverse` and `stripe`.
stripe is not displayed above the bar.

![image](https://user-images.githubusercontent.com/8215186/117871356-925b5200-b29d-11eb-8721-58a9ae76b164.png)

**Comment by pdanpdan** [comment]
Make a codepen please

**Comment by tinohager** [comment]
thanks for the quick fix
