### ISSUE TITLE
QSelect on Mobile not working as expected

### ISSUE THREAD

**Issue by danielcomcom** [quasarframework/quasar#924]
### Software version

Quasar: Quasar v0.14.1
Node: v7.10.0
NPM: 5.4.2
Browsers: Safari, Mobile Chrome 
iOS: 10.2.1

### What did you get as the error?
 No noticeable errors, just doesn't work as expected 

### What were you expecting?
That it would act like the desktop rendered select (on clicking, drop down to choose an option) 
Very hit and miss, when clicking it will sometimes open but the rest of the time it just flashes the options for a brief second.

### What steps did you take, to get the error?
Nothing special: 
<q-select
  v-model="contactMethod"
  :options="contactMethods"
/>

**Comment by danielcomcom** [comment]
Looks like it didn't take my code chunk, so here it is again
<q-select
  v-model="contactMethod"
  :options="contactMethods"
/>

**Comment by danielcomcom** [comment]
<q-select
  v-model="contactMethod"
  :options="contactMethods"
/>

**Comment by danielcomcom** [comment]
q-select
  v-model="contactMethod"
  :options="contactMethods"

**Comment by rstoenescu** [comment]
Try v0.15. Forgot to close this.
