### ISSUE TITLE
QPagination Event @update:model-value can't distinguish model

### ISSUE THREAD

**Issue by fixrule** [quasarframework/quasar#9242]
Latest (v2.0.0-beta.15)

![image](https://user-images.githubusercontent.com/24400760/117939118-57f3c280-b33a-11eb-91f2-33c278103200.png)
![image](https://user-images.githubusercontent.com/24400760/117939215-6fcb4680-b33a-11eb-98f7-6e02641d8f9e.png)

When my request reaches the total number of pages, after changing the max attribute, update:model-value will be triggered once, and I think update:model-value should be triggered only when the currentPage changes

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.17
