### ISSUE TITLE
 [Request] Morph Text To Toolbar Title

### ISSUE THREAD

**Issue by BrianMoreno1994** [quasarframework/quasar#925]
It would be pretty cool if we had the ability to morph text into the toolbar title. 

Something like this: [http://androcode.es/wp-content/uploads/2015/10/simple_coordinator.gif](http://androcode.es/wp-content/uploads/2015/10/simple_coordinator.gif)

It would also be nice to have the toolbar over the drawer and have a morphing toolbar icon when the drawer is opening: [https://androidexample365.com/content/images/2017/08/balysvmaterial-menu.gif](https://androidexample365.com/content/images/2017/08/balysvmaterial-menu.gif)

**Comment by zuck** [comment]
At least some basic animation, i.e. fading out of old element and fading in of new one (+ resize if needed). It would be like a simplified morphing.

**Comment by bloodf** [comment]
About the morphing to toolbar, I don't think it will be implemented soon on the Framework.

But abou tthe hamburger menu animation, you can try this -> https://jonsuh.com/hamburgers/
