### ISSUE TITLE
[docs][QFab] Example value not an accepted value

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#9269]
In QFab documentation, for both Qv1 and Qv2, the example for `direction` directive is given as `bottom`, which is not one of the allowed values.

https://github.com/quasarframework/quasar/blob/a94e3442a9960650cbf8c9fa86ddee46799c5e91/ui/src/components/fab/QFab.json#L29-L30

**Comment by hawkeye64** [comment]
@thexeos Thanks for letting us know! :heart:

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.15 & Quasar v2.0.0-beta.17
