### ISSUE TITLE
QScrollArea getScrollPercentage

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#9274]
v1 can also be obtained through the component's scrollPercentage property, v2 does not expose scroll.vertical.percentage and scroll.horizontal.percentage.

Hope to provide getScrollPercentage method, it is best to directly expose the scroll object.

```
    // expose public methods
    Object.assign(vm.proxy, {
      getScroll: () => scroll,
      ...
```

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.0.0-beta.17
