### ISSUE TITLE
getTickedNodes () of QTree does not return all ticked nodes

### ISSUE THREAD

**Issue by umonaca** [quasarframework/quasar#9278]
**Describe the bug**
getTickedNodes () of QTree does not return all ticked nodes when it is called in `@update:ticked` or when "watching" `ticked` array. It always  returns one item less than the true item list. However, it returns correct result when it is called from somewhere else, e.g. by clicking a QBtn.  
The following Codepen is a fork of the official document of QTree.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/muveex/pen/NWpNEZQ?editors=101

**To Reproduce**
1. Open console. Click any checkbox.
2. You should see the arrays returned in the console. The length is always correct length - 1.
3. Click getTickedNodes QBtn. You should see it returns correct length, just as I described above.

**Expected behavior**
getTickedNodes () should always return correct number of items.

**Platform (please complete the following information):**
Quasar Version: v1.15.14
@quasar/app Version: v2.2.6
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: 14
NPM: 7
Browsers: Chrome and Firefox latest

**Comment by hawkeye64** [comment]
With the above CodePen example:
Clicking the button, only returned 4 out of 5
![image](https://user-images.githubusercontent.com/10262924/118315800-323df900-b4b3-11eb-8a75-96fc385374bc.png)

and `@update:ticked` only shows 3 (yes, less -1 than button), but both are wrong
![image](https://user-images.githubusercontent.com/10262924/118315980-7630fe00-b4b3-11eb-953c-6de30c0d89d3.png)

"Good food" is never selected, but "Pleasant surroundings" is selected in both cases.

**Comment by umonaca** [comment]
It will be more problematic if you select an internal mode in 'leaf' strategy.

**Comment by umonaca** [comment]
Update: I have marked wrong label for this issue -- it is a Quasar v1 issue, not Quasar v2. I haven't tested on Quasar v2 yet.

**Comment by rstoenescu** [comment]
Use nextTick() until I can investigate this.

**Comment by rstoenescu** [comment]
What you are reporting is the expected behavior. Vue has a chance to update the ticked nodes AFTER `@update:ticked` is called. So using `nextTick()` is the way to go.

**Comment by umonaca** [comment]
Even inside a `watch` block I have to explicitly call `nextTick()` to fix this issue. Do you think it is better to "include" this `nextTick()` in the QTree component? Or at least document this behavior and tell the users about this inconsistency.

**Comment by rstoenescu** [comment]
Again, it's not an issue. It's how Vue works. You are requesting information that hasn't been updated yet. The `@update:ticked` is used by Vue itself to update it.

```
1. Component emits "update:ticked" which tells Vue "hey, this needs updating"
2. This is where you also run the update:ticked handler.
3. Vue updates it and supplies the component with the new value.
4. Component updates the value. Now getTickedNodes() can return the good result.
```
