### ISSUE TITLE
Problem with statusbarstyle black-translucent on ios devices

### ISSUE THREAD

**Issue by MandingaRadi** [quasarframework/quasar#9281]
Hi!
As you can see in the photo, when scrolling, you can see the content of index in the iphone status bar.
This does not happen in quasar v1

Thanks!
![image1](https://user-images.githubusercontent.com/49736014/118353347-3530fc00-b53c-11eb-84ec-0a3d8af928ad.jpg)

**Comment by rstoenescu** [comment]
Tested but cannot reproduce.
What mode are you using? Cordova or Capacitor? Or in mobile browser? Which Cordova, which Capacitor, which mobile browser, which version of Quasar. If on Cordova or Capacitor, do you use the recommended webview? And which version. And which version of iOS are you testing with...

**Comment by rstoenescu** [comment]
Please comment with the requested info above.

**Comment by MandingaRadi** [comment]
Hello stoenescu!
I am developing pwa, on android there is no problem, but on ios (iphone 6 with ios 12.4) ...
As you will see, I uploaded a pwa with the standard Quasar template, without adding my own code (the image is a screenshot).

The strange thing is that in quasar v1 I developed several pwa in the same way and I did not have this problem.

Thanks!

**Comment by MandingaRadi** [comment]
I add the following:
The error occurs in standalone mode (i.e. when I add the pwa to the main screen of the device).
In web mode, the semitransparent images are seen when I scroll, but it does not disturb the visual.

**Comment by MandingaRadi** [comment]
![image1](https://user-images.githubusercontent.com/49736014/118491318-3eb19400-b6f5-11eb-858a-497b8fb68730.jpg)

**Comment by MandingaRadi** [comment]
Anyway, ios 14.5 is the one that matters, if in your tests on a newer iphone you do not have this problem, I ask you to confirm it, and matter resolved.

Thanks again!

**Comment by rstoenescu** [comment]
Hi,

Thanks for offering the necessary details. I can confirm that newer iOS does not have this problem. The odd thing is that the header + toolbar handling is same in Qv2 as it was in Qv1 (CSS-wise and DOM structure-wise), so there would be no reason not to behave the same. But regardless, iOS's PWA when installed on homescreen runs on an old webview (for some reason Apple decided not to use the iOS Safari for it) and this webview is very buggy. Seems like in newer versions of iOS they've changed/upgraded the webview. But all in all, it should work correctly now.

**Comment by rstoenescu** [comment]
Hi,

Thanks for offering the necessary details. I can confirm that newer iOS does not have this problem. The odd thing is that the header + toolbar handling is same in Qv2 as it was in Qv1 (CSS-wise and DOM structure-wise), so there would be no reason not to behave the same. But regardless, iOS's PWA when installed on homescreen runs on an old webview (for some reason Apple decided not to use the iOS Safari for it) and this webview is very buggy. Seems like in newer versions of iOS they've changed/upgraded the webview. But all in all, it should work correctly now.

**Comment by MandingaRadi** [comment]
Perfect!
I'll try it on an iPhone 8 or higher. Anyway, 95% of iphone users already have ios 14 or higher, so it's less of a problem.

Thanks as always Rasvan!


https://user-images.githubusercontent.com/49736014/118495213-5be86180-b6f9-11eb-8133-5b1195b479d2.mp4
