### ISSUE TITLE
[Request] Checkbox/Toggle bind the input value to custom values

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#929]
It would help immensely if we could use v-bind:true-value and v-bind:false-value on checkbox and toggle components!

**Comment by sn0rcha** [comment]
I second this, when working with PHP / MySQL we use tinyint fields for these toggles, seem strange you can't do it in this framework yet Vue supports it!!

**Comment by rstoenescu** [comment]
Already in v0.15, so closing this.
