### ISSUE TITLE
Options Tree in QSelect

### ISSUE THREAD

**Issue by Nikitoring** [quasarframework/quasar#9290]
You can add options like tree in qselect?

![optionsTree](https://user-images.githubusercontent.com/50715463/118376098-90abca00-b5ce-11eb-85cc-d878e7d34583.png)
I created extention https://github.com/Nikitoring/quasar-qselect-option-tree
But I dont think that my solution is  true

**Comment by hawkeye64** [comment]
@Nikitoring Here is a CodePen you may be interested in. You'd have to fix it to do multi-select: https://codepen.io/Hawkeye64/pen/xxbXajq

**Comment by Nikitoring** [comment]
@hawkeye64 Yes. I saw it, but my idea is like: option slot can be chosen like checkboxes. If I choose group label v-model iselect equals group label. Example: this https://codesandbox.io/s/happy-hopper-qczfr?file=/src/App.vue
Or I can add in q-expansion-item checkboxes and added click.stop to header slot and choose all group options?
