### ISSUE TITLE
vulnerability warning during install

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar#93]
```
$ sudo npm install -g quasar-cli
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/bin/quasar -> /usr/lib/node_modules/quasar-cli/bin/quasar
```

Probaly nothing like they say [here](https://github.com/elm-lang/elm-platform/pull/166), but it would make a better first impression if this warning is removed.

**Comment by rstoenescu** [comment]
Will look into it. But as a side note, that's probably because of webpack dev server itself or one of its deps. This server is used while developing, so there's actually no security risk for Apps built with Quasar. Thanks for pointing this out.

**Comment by rstoenescu** [comment]
Moving to quasar-cli repo.
