### ISSUE TITLE
Fix some part for better RTL

### ISSUE THREAD

**Issue by AGhasemzadeh** [quasarframework/quasar#930]
Hello,
I want to change some part to make better RTL support but I can’t find them to change.
For example:
`<aside class=“layout-aside layout-aside-left scroll bg-grey-2 fixed transition-generic top-padding” style=“transform: translateX(-100%);”>`

or:
`<header class=“layout-header transition-generic fixed-top” style=“margin-left: 300px;”>`

or:
`<div class=“layout-page-container transition-generic” style=“padding-top: 50px; padding-left: 300px; padding-right: 0px;”>`

I want to change padding in all of these elements.

**Comment by rstoenescu** [comment]
Will do. All I am asking is patience.

**Comment by rstoenescu** [comment]
Available in 0.15.5
