### ISSUE TITLE
[docs] Dotenv / Qenv extensions are deprecated, confusion on which good practice to use for environment variables

### ISSUE THREAD

**Issue by davthedev** [quasarframework/quasar#9305]
Usual needs of web apps is to talk to an external API or reach database servers, among others. This requires storing per-environment URLs & API keys.

Using Quasar Framework, I lack information on how to store environment variables in a secure and extensible way.
There are two recommended extensions, quasar-qenv and quasar-dotenv, but both are deprecated since Apr 7, 2021.

Quasar documentation recommends using the quasar.conf.js to store environment variables. As this file is checked into source control, this does not address the requirements of 

- not having the API secrets saved into the repository
- have variables automatically set per deployment (read on the target env file) without having to rebuild the project

It is not clear if the standard JS, non-Quasar-specific, dotenv is supposed to work.

All those points make the situation about setting up per-environment variables quite confused. Could the docs be updated with a clear good practice regarding those points?

**Comment by hawkeye64** [comment]
@davthedev https://next.quasar.dev/quasar-cli/handling-process-env#using-dotenv

Please use repo discussions for questions. Thanks.

**Comment by tomtomcrypto** [comment]
Doc should have a clear way to setup environment variables, if you follow them to the letter it just gives a `Reference error: process is not defined` error. Having to spend hours looking thru outdated posts on how to set something basic like that up isn't helping anyone, especially since the audience here is people trying to adopt Quasar....

**Comment by hawkeye64** [comment]
Quasar is doing some security so people can't open the dev console and print out your env vars. `console.log(process)` won't work. Use the full signature of the variable: `console.log(process.env.<name>)`

This link should help you get started: https://quasar.dev/quasar-cli-vite/handling-process-env#introduction
