### ISSUE TITLE
[Request] flag icons

### ISSUE THREAD

**Issue by llin55** [quasarframework/quasar#932]
it would be nice to have flag icons integrated - I think it's a quite common need when you implement  i18n

this svg set looks good:

http://flag-icon-css.lip.is/

**Comment by sganz** [comment]
They look really good but I didn't see any license on it so it may be a problem. Would be good to have in any case!

**Comment by sganz** [comment]
Here is one more that might be usable based on wikipedia svgs 
https://github.com/hjnilsson/country-flags

**Comment by llin55** [comment]
they are MIT licensed so it's not a problem, 
the other ones look good too however they seem to be less popular according to github stars

https://github.com/lipis/flag-icon-css/blob/master/LICENSE

**Comment by sganz** [comment]
Nice, didn't see the license on the github page but saw the License file with it (what you pointed at).

**Comment by rstoenescu** [comment]
Hi,

It's really easy to import that into your project and I feel it's outside the scope of Quasar. We can't bloat the UMD version with this, for example. Sorry, but closing this.

**Comment by musicformellons** [comment]
@rstoenescu I would like to use https://www.npmjs.com/package/vue-flag-icon but when I want to have a country flag as an icon in front of QField I need to reference it as an icon (can not use vue-flag-icon <flag> element). How should I solve this? Especially to have it nice outlined compared to QFields on top of this it is important. Using the 'inset="full"' property does not work when I put the <flag> in front of the QField as it shifts the QField to the right.
