### ISSUE TITLE
Electron App Unable to Close Clicking X in window corner

### ISSUE THREAD

**Issue by JokerMartini** [quasarframework/quasar#9328]
**Describe the bug**
The app will not close when the user clicks the Close button in the window bar located at the top right on Windows 10 using Electron dev build.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. This issue is introduced when adding `autoHideMenuBar: true` to the electron-main.js file.

**Expected behavior**
This should close the app. Currently only possible by killing the terminal manually.

  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Electron: Yes

**Comment by hawkeye64** [comment]
```js
    mainWindow.on('close', function(e) { 
        e.preventDefault();
        mainWindow.destroy();
    });
  ```
  https://github.com/electron/electron/blob/master/docs/api/browser-window.md#windestroy
