### ISSUE TITLE
Allow optional debouncing on qTable with virtual scrolling

### ISSUE THREAD

**Issue by TuringJest** [quasarframework/quasar#9329]
**Is your feature request related to a problem? Please describe.**
I found that the default debouncing leads to a poor experience on trackpad devices which tend to scroll fast but lose scroll speed slowly. The debounce sets in quickly and no rendering happens until the scroll stops completely which feels very sluggish.      

**Describe the solution you'd like**
Make the debouncing optional.
Allow to set the threshold higher or use a minimum scroll velocity (if possible?) for the threshold.     

Especially for larger data tables, this is kind of a deal-breaker.

**Comment by rstoenescu** [comment]
Hi,

There's no way to work around this because on iOS the scrolling event is triggered only when the scroll animation ended.

**Comment by TuringJest** [comment]
Hi @rstoenescu, 
are you sure this is the root of the issue? I think the whole scrolling event issues have changed over the past years and I'm having this issue with the trackpad of a MacBook. 

I was thinking this issue will happen with any momentum scroller as the debounce is working on the scrollPosition.

If the debounce was optional the lib users would have more options to decide how to optimize network calls or rendering. 
Also, showing the blank scroller for data that has already been loaded should be optional. I understand the usefulness on mobile devices but the experience on desktop is not nice. 

It's quite a strong design decision, so would love it if it was a bit more open to customization. I also tried to put a loading spinner in every row of the empty scroll background but found it impossible without changing the source components.
