### ISSUE TITLE
Scrollbars on QDatetime

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#933]
Quasar: 0.14.2
OS: Linux
Browsers: Firefox, Chrome (more noticeable on chrome)

I'm seeing scrollbars on the QDatetime component that require me to scroll down in order to press any button, even if there is enough space on screen to show the entire popup:
![Scrollbars on QDatetime](https://user-images.githubusercontent.com/9467722/30908627-9518097c-a354-11e7-9a76-d430b9501de8.png)

The problem seems to be the popover that is showing the calendar... Inside it has a div with:
`style="transform-origin: left top 0px; max-height: 65vh; top: 96px; left: 24px;"`. If I remove the max-height it gets resolved (but I dont know if that is the right solution)

**Comment by rstoenescu** [comment]
Fix available in edge and future v0.14.4
