### ISSUE TITLE
QDate component setView method parameter name and external variable name conflict error

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#9334]
QDate component setView method parameter name and external variable name conflict error

QDate.js?52ee:732 Uncaught (in promise) TypeError: Cannot create property 'value' on string 'Months'
    at Proxy.setView (QDate.js?52ee:732)

![image](https://user-images.githubusercontent.com/354878/118783015-3e65f400-b8c1-11eb-928d-e7c9f7a0894a.png)

![image](https://user-images.githubusercontent.com/354878/118782158-62750580-b8c0-11eb-8199-c6bcfc5c5bfd.png)

It is recommended to modify the parameter name, view to value.

```
  function setView (value) {
      if (viewIsValid(value) === true) {
        view.value = value
      }
    }
```

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-beta.18
