### ISSUE TITLE
[Feature Discussion] QToolbarSpacer to make aligning buttons on a QToolbar more intuitive

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#934]
QToolbar is implemented as a flex row, and so inserting QBtn components can be spread across the available space by also including `div` elements with the `col` class:
```
<q-toolbar>
  <!-- Left group -->
  <q-btn flat>
    <q-icon name="keyboard_arrow_left" />
  </q-btn>

  <q-btn flat>
    <q-icon name="home" />
  </q-btn>

  <q-btn flat>
    <q-icon name="group" />
  </q-btn>

  <q-btn flat>
    <q-icon name="code" />
  </q-btn>

  <div class="col"></div>
  
  <!-- Right group -->
  <q-btn flat>
    <q-icon name="fa-sign-out" />
  </q-btn>

</q-toolbar>
```
Produces:
![image](https://user-images.githubusercontent.com/900542/30914083-44c34190-a38a-11e7-9fa7-742bc4df32d7.png)

The proposition is to create a minimal QToolbarSpacer component to replace the `<div class="col"></div>` line, simply to make the code more readable and easier to remember. It could be used multiple times to create multiple groupings:
```
<q-toolbar>
  <!-- Left group -->
  <q-btn flat>
    <q-icon name="keyboard_arrow_left" />
  </q-btn>

  <q-btn flat>
    <q-icon name="home" />
  </q-btn>

  <q-toolbar-spacer />

  <!-- Middle group -->

  <q-btn flat>
    <q-icon name="group" />
  </q-btn>

  <q-btn flat>
    <q-icon name="code" />
  </q-btn>

  <q-toolbar-spacer />
  
  <!-- Right group -->
  <q-btn flat>
    <q-icon name="fa-sign-out" />
  </q-btn>

</q-toolbar>
```

![image](https://user-images.githubusercontent.com/900542/30914104-52b88d78-a38a-11e7-9662-7ae023c6c6c0.png)

Using `class="col-X"` on the button elements allows individual width of buttons to be set:
```
<q-toolbar>
  <!-- Left group -->
  <q-btn flat>
    <q-icon name="keyboard_arrow_left" />
  </q-btn>

  <q-btn flat class="col-3">
    <q-icon name="home" />
  </q-btn>

  <q-toolbar-spacer />

  <!-- Middle group -->

  <q-btn flat>
    <q-icon name="group" />
  </q-btn>

  <q-btn flat>
    <q-icon name="code" />
  </q-btn>

  <q-toolbar-spacer />
  
  <!-- Right group -->
  <q-btn flat>
    <q-icon name="fa-sign-out" />
  </q-btn>

</q-toolbar>
```
![image](https://user-images.githubusercontent.com/900542/30914273-066bedce-a38b-11e7-9171-a68bd6b86adb.png)

Therefore, an additional 'helper' could be to implement `wide-1`, `wide-2` as attributes for the `q-btn` component, so it could be written as:
```
  <q-btn flat wide-3>
    <q-icon name="home" />
  </q-btn>
```
One issue here is that the default width of an icon button appears to be in between `class="col-1"` and `class="col-2"`, therefore `wide-1` _wouldn't_ give the default width. An alternative would be:

- `narrow`: `class="col-1"`
- `wide-1`: `class="col-2"`
- `wide-2`: `class="col-3"`
- etc.

**Comment by rstoenescu** [comment]
I find a few problems with this design:

1. If for example you have a sibling element which uses "col-X" then the spacer will not occupy the remaining space. The space will be divided according to col-X and col (used by spacer).

2. Overloading the button with additional props is not ideal from multiple perspectives. One is from performance perspective: it adds to the Quasar footprint and makes code run a (very) little bit slower. Second problem would be that while these new props add commodity, they won't work if the parent element does not have the "row" class.

Any suggestions to these problems?

**Comment by dsl101** [comment]
I'm still confused about problem 1. Can you post some html which shows it not working?

As for 2., all of these features are intended _only_ to be used in a toolbar, so that would take care of the parent element have a "row" class. If the props would affect every single button (in terms of performance, not whether or not they make sense to use), then I'm not too worried if they're left out. I would guess it's less likely you'll want custom width buttons than button grouping / alignment.

An alternative approach might be to go the whole `q-toolbar-btn` route and make a specific instance which supports all those things in a toolbar?

**Comment by rstoenescu** [comment]
Discussed this within the team. @zuck can give more details if required. For now, it's better to make yourself such a component in your website/apps. Sorry for any inconvenience.

**Comment by zuck** [comment]
Yes, while I agree it's better to avoid to generate a component for that, because it's simply a wrapper around a CSS rule, I think we can use the content of this issue to improve docs and provide a very clear and visual explanation to those are looking on how to implement a toolbar with grouped buttons.

**Comment by dsl101** [comment]
That would be great. I'm not sure I understand enough about flex to be able to create that, but I'd be happy to use it :).
