### ISSUE TITLE
[Dialog Plugin] cannot use custom component with `<script setup>` sugar

### ISSUE THREAD

**Issue by xuzuodong** [quasarframework/quasar#9347]
**Describe the bug**
`Dialog Plugin` provides a great way to imperatively open a dialog, which can even be a customized component. But when I use a custom component in new `<script setup>` way, an error occurs and the dialog cannot be opened. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/hidden-pine-0zub9?file=/src/components/HelloWorld.vue

**To Reproduce**
1. Click the link above
1. Click `<script setup> dialog` button

**Expected behavior**
A customized dialog should open, like if you click the button on the left. 

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS 11.3.1
Node: 14.5.3
NPM: 6.14.9
Yarn: 
Browsers: Chrome 90.0.4430.212 (arm 64) or Safari 14.1
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
Thanks for reporting.
This will be supported in Quasar v2.0.0-beta.18.

A small note though: using "script setup" is marked as experimental by the Vue Team, which means that they can change anything at any time. Using this feature might not be the best way to go for the stability of your app/website.
