### ISSUE TITLE
[Request] QInput: add properties autocompletetype, autocapitalize, autocorrect, spellcheck

### ISSUE THREAD

**Issue by aleksanderzubkov** [quasarframework/quasar#935]
Please add properties to QInput to set attributes of INPUT tag:
- autocompletetype="email"
- autocapitalize="off"
- autocorrect="off"
- spellcheck="false"

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.7 through new "attributes" Object property.
Example:

```html
<q-input :attributes="{autocompletetype: 'email'}" .... />
```
