### ISSUE TITLE
QPullToRefresh triggers when scrolling down, breaking scroll on children on touchscreens

### ISSUE THREAD

**Issue by gnarrrl** [quasarframework/quasar#9351]
**Describe the bug**
Pull-to-refresh prevents scroll on children (e.g. q-list) because it can trigger regardless of pull direction.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/bzens/pen/QWpdbXd?editors=1010

**To Reproduce**
1. At y-scroll position 0
2. Pull up on the list. No pull-to-refresh triggers.
3. Pull down on the list. Pull-to-refresh triggers.
4. Pull up on the list again. Now pull-to-refresh also triggers when scrolling up.
5. On touchscreens, it is now impossible to scroll the list.

**Expected behavior**
Pull-to-refresh only triggering when pulling down at position 0, as seen in [Material Guidelines - Swipe to Refresh](https://material.io/design/platform-guidance/android-swipe-to-refresh.html#usage)

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.17
@quasar/app Version: 3.0.0-beta.25
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [x] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [x] Capacitor
  - [ ] BEX

OS: Windows 10 Home x86_64 10.19042
Node: 16.1.0
NPM: 7.11.2
Browsers: Chrome dev 90.0.4430.212
Android: 11
Electron: 12.0.9

**Comment by rstoenescu** [comment]
Thanks for reporting and contributing with a PR!
Will be available in v2.0.0-beta.18 and v1.15.16.
