### ISSUE TITLE
Changing the Quasar Language Pack at runtime

### ISSUE THREAD

**Issue by NathanDePachtere** [quasarframework/quasar#9354]
**Describe the bug**
Changing the Quasar Language Pack at runtime seems to be not working.

**To Reproduce**

1. Install a new clean project with i18n
2. Follow the docs https://quasar.dev/options/quasar-language-packs and put the code below inside Page/Index.vue
```
<template>
  <q-page class="flex flex-center">
    <img
      alt="Quasar logo"
      src="~assets/quasar-logo-full.svg"
    >
    <q-select
      v-model="lang"
      :options="langOptions"
      label="Quasar Language"
      dense
      borderless
      emit-value
      map-options
      options-dense
      style="min-width: 150px"
    />
    <span>{{ dateToDisplay }}</span>
  </q-page>
</template>

<script>
import languages from 'quasar/lang/index.json'
import { date } from 'quasar';

const appLanguages = languages.filter(lang =>
  [ 'de', 'en-us' ].includes(lang.isoName)
);

export default {
  name: 'PageIndex',
  data() {
    return {
      lang: this.$q.lang.isoName,
      langOptions: [],
      test: Date.now(),
    };
  },
  computed: {
    dateToDisplay() {
      return date.formatDate(this.test, 'dddd D MMMM');
    },
  },
  watch: {
    lang(lang) {
      // dynamic import, so loading on demand only
      import(
        /* webpackInclude: /(de|en-us)\.js$/ */
      `quasar/lang/${lang}`
        ).then(lang => {
        this.$q.lang.set(lang.default);
      })
    }
  },

  created () {
    this.langOptions = appLanguages.map(lang => ({
      label: lang.nativeName, value: lang.isoName,
    }));
  }
};
</script>

```
4. See the date not changing

**Expected behavior**
The date day and month should switch language

**Also**
I tried to follow the Tip n°1 on this link https://medium.com/quasar-framework/adding-full-i18n-to-quasar-150da2d5bba4 that match the doc but I can only get the i18n locale changed.

**Comment by rstoenescu** [comment]
Quasar language pack is NOT the same thing as vue-i18n.
* Quasar language pack -> language for Quasar's own components
* vue-18n -> used for your components

Based on your example above, you're only setting the Quasar language pack, but you don't instruct vue-i18n to also switch the language. Example:

```
this.$i18n.locale = lang.value
```

**Comment by rstoenescu** [comment]
![lang-pack](https://user-images.githubusercontent.com/4665641/119137548-9465a380-ba49-11eb-9d9a-be242ef7eed5.png)

**Comment by NathanDePachtere** [comment]
@rstoenescu My goal is to translate dates in my app. And when using **date.formatDate(this.test, 'dddd D MMMM');** it seems to be using the quasar language pack and not the i18n. 

I got all the logic about the i18n working, just made this little code to target the issue with quasar language pack.

**Comment by rstoenescu** [comment]
Writing this again as it was ignored:

> Quasar language pack is NOT the same thing as vue-i18n.
> * Quasar language pack -> language for Quasar's own components
> * vue-18n -> used for your components

**When you change the vue-i18n locale also change Quasar's language.**

Like mentioned above for the second time, the Quasar language pack deals with Quasar's internals (including date.formatDate()). Alternatively, if you really don't want to also change Quasar's language, you can supply a third param to date.formatDate: https://quasar.dev/quasar-utils/date-utils#format-for-display

```js
let formattedString = date.formatDate(timeStamp, 'MMMM - dddd', {
  days: ['Duminica', 'Luni', /* and all the rest of days - remember starting with Sunday */],
  daysShort: ['Dum', 'Lun', /* and all the rest of days - remember starting with Sunday */],
  months: ['Ianuarie', 'Februarie', /* and all the rest of months */],
  monthsShort: ['Ian', 'Feb', /* and all the rest of months */]
})
```

But simply change both vue-i18n locale and Quasar's at the same time. And make sure that you thoroughly read the [App Internationalization](https://quasar.dev/options/app-internationalization) page (relates to vue-i18n package which is external to Quasar) and [Quasar Language Pack](https://quasar.dev/options/quasar-language-packs) one.

**Comment by NathanDePachtere** [comment]
OK so I'm using `Intl.DateTimeFormat` to format my date and passing `$i18n.locale` to it instead of date.formatDate() which seems to be not translating date when changing locale. 

```javascript
Vue.filter('format', (value, format) => {
    if (!value) return '';
    return Intl.DateTimeFormat(i18n.locale, format).format(value);
});
```

@rstoenescu Guessing we misunderstood each other at the beginning of this ticket but anyway my date finally get translated when changing the locale :wink: Thanks for your help, have a great day ;)
