### ISSUE TITLE
QScrollArea option to enable mobile behavior on desktop

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#9356]
**Is your feature request related to a problem? Please describe.**

When using QScrollArea on a desktop browser, it is not possible to scroll the content by mouse-downing on any point in the scroll area and then dragging it in the desired direction (up/down in vertical mode, left/right in horizontal mode).

**Describe the solution you'd like**

Add a `behavior` attribute with accepted values of `default`, `desktop`, `mobile`, where `mobile`, when used on the desktop, enables click-drag scrolling of the scroll area.

Eventually also add some bouncing, where it is possible to drag the content beyond it's scope, and have it flick back on release, like https://iscrolljs.com/ does

**Describe alternatives you've considered**

Possibly using https://iscrolljs.com
This example of a horizontal iScroll element shows exactly what is meant: https://codepen.io/soentio/pen/dojVJM (test it on a desktop browser). Also note how this demo allows to use the scroll wheel to scroll the horizontal area.
Another example: https://htmldom.dev/drag-to-scroll/

**Comment by metalsadman** [comment]
i took a dive into this sometime ago using quasar's VTouchPan directive. see the codepen here https://codepen.io/metalsadman/pen/zYNEXwG?editors=1010.

**Comment by pdanpdan** [comment]
Sorry, this does not belong to QScrollArea - use VTouchPan if you want something like this.
