### ISSUE TITLE
Deprecation warning with new dart-sass

### ISSUE THREAD

**Issue by Demivan** [quasarframework/quasar#9362]
**Describe the bug**
https://github.com/sass/dart-sass/releases/tag/1.33.0
After updating dart-sass I get a lot of deprecation warnings:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(round($number * $power), $power)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
36 │   @return round($number * $power) / $power
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\.pnpm\quasar@1.15.15_vue@2.6.12\node_modules\quasar\dist\quasar.sass 36:11    toFixed()
    node_modules\.pnpm\quasar@1.15.15_vue@2.6.12\node_modules\quasar\dist\quasar.sass 6639:19  fg()
    node_modules\.pnpm\quasar@1.15.15_vue@2.6.12\node_modules\quasar\dist\quasar.sass 6746:3   @import
```

**Additional context**
It is not something that needs to be fixed right away as replacement function `math.div` is only introduced in latest version of `dart-sass`.

**Comment by rstoenescu** [comment]
Explained it in #9202:

> We cannot upgrade the dart-sass module due to #9362 -- solving it would require multiple things that eventually would lead to breaking changes in the usage. This behavior change in Sass is really depressing. It requires us to use @use 'sass:math' in Quasar's CSS which in turn means changing the Quasar's css build system. That wouldn't be so bad, but then it means also changing how Quasar's sass file is imported (to take into account for /src/css/quasar.variables.{sass|scss}) then how the auto-import of these variables (and Quasar's) works in every SFV with style lang="sass". The @use syntax in Sass is extremely limiting and it's like a snowflake eventually causing an avalanche of needed breaking changes.
>
> For those using vue-cli-plugin-quasar -> please stay with "sass" v1.32.12. Do not upgrade further. It is what it is due to Sass changing things on the fly in the same major release (v1).

**Comment by Flamenco** [comment]
We just added a rollup plugin to remove these errors.

https://www.npmjs.com/package/rollup-plugin-sass-migrator/v/1.0.1

**Comment by tomukasas** [comment]
For anyone looking to supress the warnings in `quasar.conf` (`build` section):

```
sassLoaderOptions: {
        sassOptions: {
          logger: {
            warn(message, options) {
              const deprecationWarningsToIgnore = [
                'Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.',
                '3 repetitive deprecation warnings omitted.'
              ]

              if (options.deprecation || deprecationWarningsToIgnore.includes(message)) {
                return ''
              }
            }
          }
        }
      }
```

Logger docs: https://sass-lang.com/documentation/js-api/interfaces/logger-1/

Make sure to tweak to your needs, I didn't test this code extensively myself yet.

**Comment by rstoenescu** [comment]
@tomukasas There is no need to suppress these warnings anymore, unless you don't want to upgrade your own project's code to the newer sass syntax. Quasar UI is now using the newer syntax, just make sure that you have the latest version.

**Comment by tomukasas** [comment]
@rstoenescu thanks for the reply!

Interestingly, we are on `3.12.0` of `@quasar/app-webpack` but still getting this warning. Based on the release notes, this is the version the change has been added to the `@quasar/app-webpack`. The node modules were rebuilt after we upgraded to `3.12.0` version, so I doubt that is a problem. Gonna leave it as is for now, but at some point I'll debug to see what is going wrong.

**Comment by rstoenescu** [comment]
You need to upgrade the Quasar UI package as well ("quasar" package) to the latest version.

**Comment by rstoenescu** [comment]
You can use the "quasar upgrade --install" command in your project root folder (if you have the optional global CLI installed) for upgrading the deps.

**Comment by tomukasas** [comment]
@rstoenescu that did the trick! Thanks 👍
