### ISSUE TITLE
All form components should have :rules behavior

### ISSUE THREAD

**Issue by mobsean** [quasarframework/quasar#9363]
**Is your feature request related to a problem? Please describe.**
I tried to use, for example [QOptionGroup](https://quasar.dev/vue-components/option-group#undefined), in a QForm with validation.
And there is no :rules behavior to add to the component, like with QSelect and [QInput](https://quasar.dev/vue-components/input#undefined) have.

**Describe the solution you'd like**
Adding same rules behavior like QInput and QSelect have to validate QForm.

**Describe alternatives you've considered**
Manually validate every field...

**Additional context**
 none

**Comment by TobyMosque** [comment]
just wrap the component to be validated in a borderless and dense QField.
https://codepen.io/tobias-mesquita/pen/VwpPOpx?editors=1010
