### ISSUE TITLE
QFab | QFabAction - Unset or incorrect Z-index

### ISSUE THREAD

**Issue by danielcomcom** [quasarframework/quasar#938]
### Software version

Quasar: Quasar v0.14.1
Node: v7.10.0
NPM: 5.4.2
Browsers: Safari, Mobile Chrome, Chrome 
iOS: 10.2.1
OS: Linux

### What did you get as the error?
 No noticeable errors, just doesn't work as expected 

### What were you expecting?
For QFab and QFabAction to stay above all other elements

### What steps did you take, to get the error?
Use a QFab along with QBtn or QProgress, attached is an image of what I'm seeing both on mobile and on desktop.
I temporally set the z-index to confirm that it fixed the issue.
![fullsizerender 1](https://user-images.githubusercontent.com/13260904/30979246-01c24f00-a432-11e7-8aa8-977e68a6f46a.jpg)
![fullsizerender](https://user-images.githubusercontent.com/13260904/30979258-056a234e-a432-11e7-877c-f4361981a392.jpg)

**Comment by rstoenescu** [comment]
Will fix it. Thanks for reporting.

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.4

**Comment by michelsondan** [comment]
QFab - Z-index on QDataTable still incorrect on 0.14.6 - 
to fix it I added style:
.q-data-table table td, .q-data-table table th {
    overflow: visible;
  }
