### ISSUE TITLE
Extends q-input not work(and mb others)

### ISSUE THREAD

**Issue by Ridzhi** [quasarframework/quasar#9387]
**Describe the bug**
When I try extends QInput and use it, component not render

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/ridzhi/pen/yLMMGeq

**Expected behavior**
Expect QInput with my default label

**Platform (please complete the following information):**
Quasar Version: ^2.0.0-beta.1
@quasar/app Version: ^3.0.0-beta.1
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac OS 11.3.1
Node: 15.8.0
NPM: 7.5.0
Yarn:
Browsers: Google Chrome 90.0.4430.212
iOS:
Android:
Electron:

**Additional context**

**Comment by metalsadman** [comment]
@Ridzhi this is a vue issue not quasar. see https://github.com/vuejs/vue-next/issues/629, https://github.com/vuejs/vue-next/issues/3253, also see possible workarounds in this discussion thread https://github.com/quasarframework/quasar/discussions/8761.
