### ISSUE TITLE
[Request] DateTime month mode

### ISSUE THREAD

**Issue by NothingWeAre** [quasarframework/quasar#939]
Hello.
I would like to request an ability to limit minimal mode of datepicker to *month* through property, essentially making it MonthPicker, selecting for example first day of month. Or even configurable.

This can be useful when selected day has no meaning. 
In my case I have to implement assignment of finance document to certain *month*, and then filter by *month*. 
In case of creation selecting day is meaningless and in case of filter ability to select day can lead to confusion of user.

**Comment by rstoenescu** [comment]
This is a case where from a UI perspective, a better approach would be to make a QSelect with the months as options. I hope you can agree.

**Comment by NothingWeAre** [comment]
I think that i have to clarify my request.
At this time we have pair of selects: one for year and one for month and at submit i build date from values of both selects
While i agree that selecting only month more logical to do with single select, i think that selecting year + month still better with component similar to datetime.

**Comment by louisameline** [comment]
For the record, I wrote this a few months back: https://github.com/louisameline/quasar-monthpicker
