### ISSUE TITLE
QTabs focus effect stays after a click press on it and release outside it

### ISSUE THREAD

**Issue by Lyokolux** [quasarframework/quasar#9397]
**Describe the bug**
When you click on the tab and release the click outside it, the "focus" effect remains active. Think of it as a drag'n'drop movement starting on a QTab.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Alexandre4Ergosign/pen/oNZWZqj

**To Reproduce**
1. Click on a tab and stay press
2. Release the click outside of the tab
3. The focus effect is still present

**Expected behavior**
The tab does not have the focus effect anymore

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version:  2.0.0-beta.1
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS 10.15.7
Node: 14.13.1
NPM:
Yarn: 1.22.10
Browsers: Firefox, Chrome
iOS:
Android:
Electron:

**Comment by rstoenescu** [comment]
That's the "focused" state. We need to take care of the accessibility also.
