### ISSUE TITLE
QRange, individually coloured labels

### ISSUE THREAD

**Issue by comcomservices** [quasarframework/quasar#941]
Sometimes it is necessary to specify independent colours for the range labels.

We ran into this limitation while using the range slider to specify a colormap range on a graph

Code below, Please let me know if this is something that would be useful to others and I can create a pull request

Differences in QRange.vue highlighted here

https://www.diffchecker.com/l70foqEd

**Comment by comcomservices** [comment]
![image](https://user-images.githubusercontent.com/13089993/30997863-7939e1fe-a47f-11e7-9247-df350ca1490d.png)

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.4.

If you are a company, please consider supporting Quasar Framework as it will help speed up development. Contact me for details pls. Thanks!

**Comment by comcomservices** [comment]
Thanks Razvan,

We will definitely be supporting your framework

Jon

*________________________________*

*¬ Jon Mundall*
*   Senior Technical Adviser*
   281 Main Street, Lytton BC V0K1Z0
   Ph:  *+1 (877) 825-1530 ext: 3*
   Cell: *+1 (250) 256-8363*

*FlexSCADA | Modern Control Systems & Integration*
http://www.flexscada.com
A Subsidiary Company of ComComServices Inc.
