### ISSUE TITLE
Open Link in new tab or other browser

### ISSUE THREAD

**Issue by EmreKayaoglu** [quasarframework/quasar#9415]
**Describe the bug**
I am using the quasar framework 2 for web application and SPA mode.
In my quasar.conf.js, ssr mode is set as false:
`ssr: {
      pwa: false
    },`
And in routes.js, some routes are defined as following:
`const routes = [
  {
    path: '/',
    name: 'home',
    component: () => import('layouts/MyLayout.vue'),
  }, {
    path: '/login',
    name: 'login',
    component: LoginPage
  }, {
    path: '/productList',
    name: 'productList',
    component: ProductSelection
  }, {
    path: '/predictive/:modelID',
    name: 'prediction',
    component: ModelPrediction
  },
];`

In this case, when I open following url in a new tab or new browser, then I can see 404 error or go to home page.
I think this is error.

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
1. Go to 'http://domain_url/login'
2. Login, then you will go to product list page and url is 'http://domain_url/productlist'
3. Copy 'http://domain_url/productlist' and paste this in a new tab.
4. See 404 error or you will be redirected to home page

**Expected behavior**
You have to go product list page(authentication will be processed in user side).

**Platform (please complete the following information):**
Quasar Version: "quasar": "^1.12.8",
@quasar/app Version: "@quasar/babel-preset-app": "^2.0.1",
Quasar mode:
  - SPA

Tested on:
  -  SPA
 
OS: Windows 10, CentOS rhel fedora 2
Node: 14.16.0
NPM: 6.14.11
Browsers: Chrome, Edge

**Additional context**
I checked quasar framework and tried to solve this problem myself, and found a way to resolve this like this:
Add following code in 209 lines of 'quasar-serve' file in 'npm\node_modules\\@quasar\cli\bin'
`app.use('/*', serve('.', true))`

Then it will works.
Please check and fix this problem.

**Comment by rstoenescu** [comment]
Sounds to me like you're using Vue Router in history mode, but you spawn the "quasar serve" command without taking this into account. Should run it with `quasar serve --history [...path.to.where.you.serve...]` Check "quasar server -h" for more info.

**Comment by EmreKayaoglu** [comment]
When I try to make build in my local and deploy that on the server, then what do I have to do?
I checked "quasar build -h" and there is no option for history build.

**Comment by rstoenescu** [comment]
It's not the App CLI that has this info. It's the actual code being compiled. Configure quasar.conf.js > build > vueRouterMode to `history`.

**Comment by EmreKayaoglu** [comment]
I already did that.
But it doesn't works.
My config file contains following build configs:
`build: {
      scopeHoisting: true,
      vueRouterMode: 'history', // available values: 'hash', 'history'
      showProgress: true,
      gzip: false,
      analyze: false,
      extendWebpack(cfg) {
      }
    },`

**Comment by rstoenescu** [comment]
There's nothing wrong with Quasar. Have you correctly configured your webserver for how Vue Router's history mode works?
