### ISSUE TITLE
normal QButton's @click not working inside QForm

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#9418]
**Describe the bug**
I have some steps with forms to get some informations, I created 2 buttons:
  - `next page` (submit button to validate inputs) 
  - `previous page` (normal button with `@click`)

but if I put `previous page` inside of the form, it's `@click` will not working, but outside it will work

**Second bug discribed accidentally**
I have 3 forms to show the case in CodePen ShowCase, if I click `next page` button (submit), It will get me to next page, but after this, you will see the form will validade the second form automatically (will alert the input is required), It's like I have clicked the `next page` button in second form, but I didn't click the button

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/michael910/pen/YzZQErJ

**To Reproduce**
1. Fill the first input and click "Next"
** You will see the another bug mentioned in description **
2. Fill the second input and click "Next"
3. If you click the first one "Back" button it will not work, but if you click other "Back" button it will work

**Expected behavior**
The `@click` of the `q-button` works inside in `q-form` 

**Platform (please complete the following information):**
Quasar Version: 1.15.16
@quasar/app Version: 2.2.6
Quasar mode:

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows_NT(10.0.19041) - win32/x64
Node: 12.16.3
NPM: 6.14.4
Yarn:
Browsers: Microsoft Edge 90.0.818.66
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

This is the native behavior of `<form>` + `<button>`. Example: https://codepen.io/rstoenescu/pen/eYvRLjP
For your case, just add `@click.prevent="...handler"` to your form's buttons that "go back". Otherwise, both the `@click` and `@submit` events will be called. On the last step, this means decrementing and incrementing the step number which essentially stays on the same step number :)

Good version: https://codepen.io/rstoenescu/pen/PopjdyW

**Comment by maico910** [comment]
Hello, sorry for the delay,

Thanks for your answer, it's work a function to back page, but I have one question, In your [example](https://codepen.io/rstoenescu/pen/PopjdyW), even with `@click.prevent`, when I change step `1` from `2`, it's automatically check the form in second step (or page), is it a bug?
