### ISSUE TITLE
[Suggestion]Docker environment for dev

### ISSUE THREAD

**Issue by voldedore** [quasarframework/quasar#942]
Hi everyone, I currently switched to a totally different machine and wanted to continue my quasar project. Instead of installing nodejs on my machine, I decided to give Docker a try.

However the repo found [here](https://hub.docker.com/r/quasarframework/quasar-dev/) seems not to be up-to-date. Moreover, it also took a while pulling an over-200MB image.

So, I just made another approach for this

- Based on node:8-alpine (to reduce as much as possible pulling time/disk capacity/..., about a dozen of MB compared to hundreds)
- Mounted quasar source code to the container
- An entrypoint to install dependencies at the first runtime only.
- A command to do `npm run dev` or anything else.

It would be cooler for an Automated Build on docker hub.

I tested locally and everything works well. I'm willing to contribute, please tell me how (the contributing guideline only mentioned about contribute to the framework and not docker environment of the framework development).

**Comment by smolinari** [comment]
Hi,

I am the person who created the current docker solution. Sorry it isn't up-to-date. I'll fix that over the weekend. I also need to figure out how to automate the updating with new releases.

As for the size of the download, the client dev docker image is only 45MB. Are you sure you've gotten the right one for Quasar?

https://hub.docker.com/r/quasarframework/client-dev/tags/

More info on this image and how to use it is here: https://github.com/quasarframework/quasar-docker/tree/master/client-dev

Any feedback on improving this Docker process is always welcome. 

Scott

**Comment by voldedore** [comment]
Sorry about the misleading information of my development "with" or "for" Quasar. 😄 

Actually, I'm curious about development *for* Quasar. I also want to contribute because I've been using this framework for one of my small projects running on Herokuapp.

That said I picked the 'right' image to use but it's a bit out-of-date. I didn't mount any pulled Quasar source code but there was already another inside the container (0.9.0 if I remember it well). But you're right, it shouldn't be there since it uses (?) our own git pulled repo of Quasar.

Thanks for your quick reply. I'll always be ready to help about this Docker works. I'll create an automated build on docker hub and post it here soon.

Vinh

**Comment by smolinari** [comment]
I'll have a look over the weekend. Maybe I made a mistake with the image and uploaded the source in the container. That could explain why it is so big too. Hihi. 😄 

Scott

**Comment by rstoenescu** [comment]
Is anyone taking a look at this?

**Comment by smolinari** [comment]
Not yet. Sorry, I've been really busy. I've got a long weekend coming up. I'll get to it then.

Scott
