### ISSUE TITLE
QMenu no-route-dismiss and QDate

### ISSUE THREAD

**Issue by ssipak** [quasarframework/quasar#9422]
**Description**
A QMenu with "no-routes-dismiss" prop and a QDate with "range" prop  in it closes up when an ending date is selected from the next month.

**Codepen**
https://codepen.io/ssipak/pen/eYgorge

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the button
2. Click on any date
3. Advance to the next month
4. Click on any date
5. The menu fades away

**Expected behavior**
The menu should have stayed visible.

**Platform (please complete the following information):**
Quasar Version: 1.15.14

**Notes**
I actually figured out how to fix it by slightly modifying the clickoutside handler in QMenu, but I'm not sure I did it the right way.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.21.
