### ISSUE TITLE
[v2] QSelect: getOptionValue/getOptionLabel methods not working

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#9427]
**Describe the bug**
According to the documentation `getOptionValue` method should retun the value of the option passed as a parameter but it is not.
Same with `getOptionLabel`

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/heartbeatlv-the-bashful/pen/NWpvKbM

**To Reproduce**
1. click the TEST button
2. see in console

**Expected behavior**
`getOptionValue` should return the option value 
`getOptionLabel` should return the option label

**Comment by hawkeye64** [comment]
@heartbeatLV You are mixing composition api with options API.
Anyway, I fixed your codepen so you can work with it further: https://codepen.io/Hawkeye64/pen/jOBLvwB

**Comment by heartbeatLV** [comment]
@hawkeye64 there should be no problem with mixing option api and composition api
however, even in your example I can't get the expected result
`getOptionValue` should return the value. in the console I see the ref of the q-select

**Comment by rstoenescu** [comment]
`getOptionValue()` and `getOptionLabel()` require the full Object of the respective option, not its actual value.
What good is getOptionValue(value) if it returns the same value anyway?
Also, you have the "options" stored somewhere. You can filter it yourself to find the label of an option which has a certain value.

**Comment by heartbeatLV** [comment]
> `getOptionValue()` and `getOptionLabel()` require the full Object of the respective option, not its actual value.

I know, in fact that was just an example as the function should work even when the options are an array of strings
However, even passing the entire option does not return the value

> What good is getOptionValue(value) if it returns the same value anyway?

I originally wrote my own function to do this but then I saw that the component exposes this method.
The good part would be that this function takes care of returning the value regardless of the type of `options` prop and the `option-value`/`option-label` prop

> Also, you have the "options" stored somewhere. You can filter it yourself to find the label of an option which has a certain value.

for the reason I explained earlier, that is, because the type of options can change and so on

**Comment by heartbeatLV** [comment]
i updated the codepen to make it more detailed and added a codepen with the previous quasar version

I'm a huge fan of quasar. I just wanted to point out that these methods that the framework offers are not working properly
