### ISSUE TITLE
Fill a q-table by column

### ISSUE THREAD

**Issue by DDJavi** [quasarframework/quasar#9429]
Hello, Im trying to fill a table column by column, for example:
I ve an arraylist of objects and I want to asign each column to each object ->
months :[
   {days:31, worked:25, payed:10}, 
  {days:28, worked:10, payed:8}
]
And fill the table like:

Item  |  January  |  Febrary
days  |      31      |     28
worked |  25      |     10
payed |   10       |       8

Thanks anyway

**Comment by rstoenescu** [comment]
Please provide a codepen like requested in the ticket template.
