### ISSUE TITLE
QSlider - @input event fires twice with :value

### ISSUE THREAD

**Issue by ElijahKotyluk** [quasarframework/quasar#9430]
**Describe the bug**
When using `QSlider` component and supplying a bound `:value` in combination with the `@input` event, the event gets fired twice when it should only be firing once.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/elijahkotyluk/pen/zYZdGqV?editors=1011

**To Reproduce**
1. Go to the codepen link provided
2. Focus the slider, either one keypress to the left/right or a single click to a different position, and you'll notice in the console that the event fires twice when using a bound `:value` with the `@input` event.

**Expected behavior**
The @input event only fires once.

**Screenshots**
n/a

**Platform (please complete the following information):**
Quasar Version: 1.15.13
@quasar/app Version: 1.3.7
Quasar mode: electron

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [x] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS Big Sur 11.2.3
Node: 14
NPM: 6
Yarn: 1.22.5
Browsers: Mozilla & Chrome latest
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Fixed for v2 already. Will port the fix to v1 also.

**Comment by ElijahKotyluk** [comment]
@rstoenescu thank you.

**Comment by rstoenescu** [comment]
Was a bit confused, but checked your codepen now. You need to either 1. use v-model or 2. update the model yourself in the `@input` handler. Otherwise QSlider (and QRange for that matter) checks the current model and emits only if the current model has changed. In your case, it never changes.
