### ISSUE TITLE
Option to display scroller on q-menu

### ISSUE THREAD

**Issue by maggie0002** [quasarframework/quasar#9436]
When using a q-menu, it isn't always clear that there are more options available. In the below for example, it looks like it is limited to 4 items:

<img width="153" alt="Screenshot 2021-05-26 at 16 22 38" src="https://user-images.githubusercontent.com/64841595/119743549-fdc92600-be3e-11eb-85d3-67decc1e4c9c.png">

In fact, there is a lot more, but it is compacted due to the screen size:

<img width="102" alt="Screenshot 2021-05-26 at 16 27 40" src="https://user-images.githubusercontent.com/64841595/119743718-58fb1880-be3f-11eb-83af-3198db4c8f5f.png">

The general sizing and shape of the q-menu looks great, but would be good to find a visual way to indicate to users that there are more options to avoid things getting missed. 

I was thinking an option in the q-menu class that allows the scroll bar to always be visible? That way it would be clear that the user is at the top of a list.

**Comment by metalsadman** [comment]
@maggie0002 wrap your list items in a [QScrollArea ](https://quasar.dev/vue-components/scroll-area). ie. https://codepen.io/metalsadman/pen/qBrXXaJ?editors=1010

**Comment by maggie0002** [comment]
> @maggie0002 wrap your list items in a [QScrollArea ](https://quasar.dev/vue-components/scroll-area). ie. https://codepen.io/metalsadman/pen/qBrXXaJ?editors=1010

Thanks for the solution. It seems quite a lot of code for a UI improvement, and appears to rely on fixed height menus? Would still be nice to have something that improves the usability out of the box, but appreciate there is a way round.

**Comment by metalsadman** [comment]
@maggie0002 As for fixed heights there are ways to determine it dynamically using quasar's screen plugin etc...

 

> > @maggie0002 wrap your list items in a [QScrollArea ](https://quasar.dev/vue-components/scroll-area). ie. https://codepen.io/metalsadman/pen/qBrXXaJ?editors=1010
> 
> Thanks for the solution. It seems quite a lot of code for a UI improvement,

You don't need to write that code all the time you can make a it an independent component and re-use it where you need it.

> and appears to rely on fixed height menus? 

There are ways to determine it using quasar's screen plugin (check docs) then decide to change it dynamically.

> Would still be nice to have something that improves the usability out of the box, but appreciate there is a way round.

QMenu content can be anything not just simple lists so I don't think this feat request is viable, beside in desktop if you set a specific height for your qmenu, the browser's native scroll bars will be shown.

**Comment by metalsadman** [comment]
@maggie0002 
> Thanks for the solution. It seems quite a lot of code for a UI improvement,

You don't need to write that code all the time you can make an independent component and re-use it where you need it.

> and appears to rely on fixed height menus? 

There are ways to determine it using quasar's screen plugin (check docs) then decide to change it dynamically.

> Would still be nice to have something that improves the usability out of the box, but appreciate there is a way round.

QMenu content can be anything not just simple lists so I don't think this feat request is viable, beside in desktop if you set a specific height for your qmenu, the browser's native scroll bars will be shown.
