### ISSUE TITLE
this.$q.cookies.set(....httpOnly: true ) not setting cookie

### ISSUE THREAD

**Issue by fafutuka** [quasarframework/quasar#9439]
Hello,
I've been trying to set a cookie with using the this.$q.cookies.set(....httpOnly: true ) but its not working
In the home path 
below is the code
          this.$q.cookies.set('token', response.data.jwt, { expires:'',path:'/',domain:'',sameSite:'Strict',httpOnly:true,secure:true})

Brower
1. Chrome Version 90.0.4430.212 (Official Build) (64-bit)
2. Edge Version 90.0.818.66 (Official build) (64-bit)

I've set the in quasar.config 
    devServer: {
      https: true,
      port: 8080,
      open: true // opens browser window automatically
    },

and 
    ssr: {
      pwa: false
    },

**Comment by Smrtnyk** [comment]
have you read what httpOnly cookie is?
https://www.cookiepro.com/knowledge/httponly-cookie/

how are you trying to access it?
are you setting it server side?

you need to provide more context and repro idealy

**Comment by fafutuka** [comment]
I'm trying to set on the client side, since I saw on the documentation,
I'm doing REST API with PHP having trouble setting the cookie from the server.

**Comment by Smrtnyk** [comment]
Since you are trying to set httpOnly cookie client side I assume you are not familiar with the topic
Please read the link I posted above

You opened a bug knowing you are trying to manipulate with such cookie client side

**Comment by fafutuka** [comment]
I realize that after I open up the issue, but why put it in the documentation since it can't be set except in SSR Apps, anyways thanks for link its been a great help

**Comment by rstoenescu** [comment]
This comment is incosiderate towards developers writing SSR apps with Quasar. Of course we need to put that into the documentation.
