### ISSUE TITLE
QInnerLoading: form elements are active (z-index?)

### ISSUE THREAD

**Issue by ircop** [quasarframework/quasar#944]
Hello

Quasar-framework .14

Tried to use q-inner-loading inside main template element (q-layout or div).
Same element also contains form inputs.

When q-inner-layout activated, form elements are still available for iteraction over loading background.

My template:

```javascript
<q-layout view="hHr LpR lFf" class="layout-padding relative-position" >
        <q-inner-loading :visible="loadingVisible">
            <q-spinner-gears size="50px" color="primary"></q-spinner-gears>
        </q-inner-loading>

        <div class="row">
            <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <q-card>
                <q-card-main>
                    <div class="row">
                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-xs-8">
                                <q-input .....................
```

**Comment by odranoelBR** [comment]
Try to use QInnerLoading as final element.

**Comment by ircop** [comment]
I've tried, without any success :(

**Comment by odranoelBR** [comment]
You want all the screenn be loading ? if so , use Loading http://quasar-framework.org/components/loading.html

**Comment by ircop** [comment]
No, it's q-layout in q-layout.
I've tried div instead of q-layout, without success

**Comment by rstoenescu** [comment]
Hi. QLayout in QLayout is definitely something not to do. You should only have at most one QLayout at a time.
