### ISSUE TITLE
SSR mode sever render set brand colors not working

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#9442]
SSR mode sever render quasar conf set brand colors not working.

The page rendered by the server is still the default color, which will not change until the client is loaded.

sever
![image](https://user-images.githubusercontent.com/354878/119807522-c9746900-bf15-11eb-884f-d415dd5f4fd6.png)

client
![image](https://user-images.githubusercontent.com/354878/119807688-faed3480-bf15-11eb-80f3-72f7bfe2c1b4.png)

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.3.1 + "@quasar/app" v3.1.11 (both are required).
There is also another way to avoid this behavior, which is to directly change the Quasar Sass variables in /src/css/quasar.variables.[sass|scss]
