### ISSUE TITLE
[docs] the API Explorer should convert the searched text to lowercase

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#9443]
**Describe the bug**
when search in the API Explorer for methods containing uppercase letters it fails

**To Reproduce**
1. Go to [q-select-docs](https://next.quasar.dev/vue-components/select)
2. Switch to methods tab
3. Search 'scrollTo'

**Expected behavior**
the API search should convert the searched text to lowercase

**Comment by rstoenescu** [comment]
Thanks for notifying about this.
Will be fixed in next docs deployment.
