### ISSUE TITLE
double-click in modal unexpectedly going back in browser history

### ISSUE THREAD

**Issue by jmellicker** [quasarframework/quasar#945]
### Software version
Quasar CLI v0.6.4
Quasar: App running on Quasar v0.14.3 (edge version)

### Description:
We have some clickable icons in a Quasar modal. When clicked once, the icons close the modal and do other stuff. (The modal is not routed.)

A client reported that double-clicking in the modal unexpectedly took them back to the previous "page" (we confirmed).

### Theory for why this is happening
It seems that after the first click, `Platform.has.popstate = true`, so this line: https://github.com/quasarframework/quasar/blob/dev/src/components/modal/QModal.vue#L243
(`window.history.go(-1)`) is being triggered.

What's the best solution for this? Trap double-clicks? Change how `has.popstate` is being set?

### What were you expecting?
Client was expecting same behavior as a single click.

**Comment by rstoenescu** [comment]
I got a fix ready, but cannot reproduce the issue so I can confirm it's 100% fixed.
Can you paste a simple template with which I can reproduce pls?

**Comment by rstoenescu** [comment]
Fix available in latest edge and v0.14.4
