### ISSUE TITLE
<q-form> no longer validates inputs in child components

### ISSUE THREAD

**Issue by wujekbogdan** [quasarframework/quasar#9450]
**Describe the bug**

Quasar, when a `<q-form>` is submitted, goes through all inputs and validates them. It works fine with one exception: if a component, which is wrapped by `<q-form>` has `<q-input>` as a root element then this input doesn't get validated. Validation still passes even in case of invalid input.

Example: https://codesandbox.io/s/prod-glade-2529p?file=/src/App.vue

**To Reproduce**

1. Go to https://codesandbox.io/s/prod-glade-2529p?file=/src/App.vue
2. **Do not** set focus on any `q-form` field
3. Click all 3 submit buttons, one after another.

**Expected behavior**
All inputs have identicasl validation rules, so validation should fail for all inputs, but fails only for the first one and for the last one.

1. The first form contains a `<q-input>` field which has no wrapper component. It works as expected.
2. The second form contains a `<qInputWrapper>` component which is a wrapper for `<q-input>` where `<q-input>` is the only (and the root) element. In this case it doesn't work as expected. The input is not being validated on `<q-form>` submit.
3. The third form contains a `<qInputWrapperWorkaround>` component which is a wrapper  `<q-input>` where `<q-input>` is not a root element. It has an additional wrapping `<div>`. In this case it works as expected but requires a workaround - an additional div.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS 11.3.1
Node: v12.21.0
NPM: 6.14.11
Yarn: 1.22.10
Browsers: Chrome 90.0.4430.212

**Additional context**

Wrapping `<q-input>` in a `<div>` as a workaround is a no-go for me because in the app I'm working on it would cause a lot of regressions. I have wrapper components for `<q-input>` that add some additional logic, but inherit all `<q-input>` props and attrs and re-emmit all events. These wrappers are supposed to be a drop-in replacement for quasar inputs, so additional div is not an option.

**Comment by rstoenescu** [comment]
In your wrapper component, add a ref (let's call it "input" to the QInput) then also passthrough QInput's "validation" method:

```
methods: {
    validate() {
      return this.$refs.input.validate();
    },
  },
```

This has been greatly improved in Quasar v2, but cannot backport the fix due to vue perf issues.

**Comment by wujekbogdan** [comment]
Thanks I like this fix better than a wrapping `<div>` workaround.

**Comment by qxygene** [comment]
Any update??
