### ISSUE TITLE
[proposal] is element in viewport DOM Util

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#946]
A handy DOM Util wrapper for: “is this element in viewport” or not?

https://gomakethings.com/how-to-test-if-an-element-is-in-the-viewport-with-vanilla-javascript/

**Comment by rstoenescu** [comment]
Hi,

[Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is coming, so I don't think we need this.
