### ISSUE TITLE
QFile: Freezes safari in append mode when adding multiple files

### ISSUE THREAD

**Issue by thetaurean** [quasarframework/quasar#9465]
**Describe the bug**
When using the QFile component with `multiple` and `append`, adding multiple files freezes the webpage in Safari 14.1. The issue does not occur in Firefox. The issue only occurs on append, if multiple files are added at the same time it functions as expected.

**Codepen/jsFiddle/Codesandbox (required)**
See example in [docs](https://quasar.dev/vue-components/file-picker#appending-files)

**To Reproduce**
1. Go to the docs [page](https://quasar.dev/vue-components/file-picker#appending-files) for QFile
2. Scroll down to the section on Appending
3. Add a single file
4. Add another file

**Expected behavior**
When appending I would expect the 2nd file to be added to the model and displayed inside the component.

**Platform (please complete the following information):**
Quasar Version: v2 and v1
@quasar/app Version: N/A
Quasar mode:

  - [X] SPA
  - [X] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [X] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS Big Sur
Browsers: Safari v14.1

**Comment by thetaurean** [comment]
I added some logging to QFile and `use-field.js`, `use-form.js`, and `use-file.js` and thought I would share.

![Screen Shot 2021-06-01 at 3 05 34 PM](https://user-images.githubusercontent.com/24903423/120377450-22b01400-c2eb-11eb-9ce9-40b1a1ceaf29.png)

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v1.15.20 & v2.0.0-beta.20

**Comment by thetaurean** [comment]
@rstoenescu Sincerely appreciate the quick resolution! I applied the patch and it worked beautifully.

Salut from a fellow Romanian; been using this framework since 0.13 and pitch it everywhere I go! 💯 

Hope to contribute some code one day soon 👍.

**Comment by rstoenescu** [comment]
@thetaurean Cheers! Looking forward to your contributions.
