### ISSUE TITLE
QRouteTab count attribute missing QChip

### ISSUE THREAD

**Issue by gitwg** [quasarframework/quasar#947]
### Software version

Quasar: v0.14.3
OS: macOS Sierra 10.12.6 (16G29)
Node: v8.5.0
NPM: 5.4.2
Browsers: Chrome Version 61.0.3163.79 (Official Build) (64-bit)
iOS: N/A
Android: N/A
Any other software related to your bug:

### What did you get as the error?
When using QRouteTab 'count' attribute, the number is displayed below the tab label, not in a red QChip like QTab.

### What were you expecting?
The count to be displayed in a QChip to the top-right of the tab label, like it does in QTab.

### What steps did you take, to get the error?
<pre>
    &lt;q-tabs class="shadow-2"&gt;
         &lt;q-route-tab count="5" slot="title" label="Mails" to="/mails"&gt;&lt;/q-route-tab&gt;
    &lt;/q-tabs&gt;
</pre>

**Comment by gitwg** [comment]
This is fixable by making the following changes...

In quasar.esm.js at the definition of QRouteTab (...var QRouteTab = {...) 
     1. replace ",(_vm.count)?_c('span',{staticClass:"floating label circular"},[_vm._v(_vm._s(_vm.count))]):" with ",(_vm.count)?_c('q-chip',{attrs:{"floating":""}},[_vm._v(_vm._s(_vm.count))]):"
     2. add "QChip: QChip" to QRouteTab components.

**Comment by rstoenescu** [comment]
Thanks for reporting. Available in edge and future v0.14.4
