### ISSUE TITLE
Q-File Max File Size is not working?

### ISSUE THREAD

**Issue by tru3prodigy** [quasarframework/quasar#9478]
**Describe the bug**
https://quasar.dev/vue-components/file-picker
 <q-file
        style="max-width: 300px"
        v-model="filesMaxSize"
        outlined
        label="Max file size (2k)"
        multiple
        max-file-size="2048"
        @rejected="onRejected"
      />

I tried selecting file which is within the specified size limit, but every file throws "file did not pass validation constraint"

**Codepen/jsFiddle/Codesandbox (required)**

https://codepen.io/markanax/pen/jOBaMLW

**To Reproduce**
1. Go to https://codepen.io/markanax/pen/jOBaMLW
2. Click on Q-File input component
3. try to upload a file within size of 2mb
4. See error "1 file(s) did not pass validation constraints"

**Expected behavior**
![q-file error](https://user-images.githubusercontent.com/3002838/120093106-96102500-c135-11eb-98ac-28f27be04225.jpg)

It should validate the file and accept it as a valid input when selected file is within 2mb.

**Screenshots**
![q-file error](https://user-images.githubusercontent.com/3002838/120093115-a2947d80-c135-11eb-86d8-2a57a6a56de7.jpg)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: v1.15.19
Quasar mode:

  - [ ] SPA

Tested on:
  - [ ] SPA

OS: Windows 10
Node: 14.15.4
NPM:6.14.10
Browsers: Chrome

**Comment by xwyzsn** [comment]
2048 Bytes not equal to 2MB but 2kb. I thought that's the problem.

**Comment by tru3prodigy** [comment]
my bad, i didnt think the unit is in Bytes.
