### ISSUE TITLE
Add an option to put the header of a QInlineDatetime on top also on wider screens

### ISSUE THREAD

**Issue by omrihar** [quasarframework/quasar#948]
Currently the `QInlineDatetime` component displays the header on the left of the calendar on wide screens and on top for narrow screens (mobile). 
It would be really great to be able to choose through a parameter whether the header is on the top or on the left, since it is sometimes embedded in a narrow context (a drawer for example).

Thanks,
Omri

**Comment by slowaways** [comment]
QInlineDatetime has been renamed to QDatetimePicker.

**Comment by rstoenescu** [comment]
Done for future v1.0.
