### ISSUE TITLE
QVideo No way to remove native autoplay attribute from generated video tag

### ISSUE THREAD

**Issue by lyle45** [quasarframework/quasar#9496]
**Describe the bug**
QVideo No way to remove native autoplay attribute from generated video tag
unknown props are not propagated to native video tag and even if they were, autoplay needs to have special care

according to Mozilla,

`
To disable video autoplay, autoplay="false" will not work; the video will autoplay if the attribute is there in the <video> tag at all. To remove autoplay, the attribute needs to be removed altogether.
`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-autoplay

**Codepen/jsFiddle/Codesandbox (required)**
Self explanatory

**To Reproduce**
Self explanatory

**Expected behavior**
Attributes should propagate to native element + autoplay should probably not be default

**Platform (please complete the following information):**
Quasar Version: 1.15.19
Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
QVideo does not add any "autoplay" attribute. It's a very simple convenience component which embeds a Youtube iframe, which can be seen from the [`HTML markup`](https://quasar.dev/vue-components/video#markup-equivalent) section in docs.

Also, there's confusing information regarding the version of Quasar. Is it Quasar v1 or v2? You've specified `Quasar Version: 1.15.19` in the template but have selected the Quasar v2 template.

**Comment by lyle45** [comment]
🤦  

actually using it, pretty greatly, to preview video files so with objectUrl as src and it works great as a ratio enforcer and for responsiveness. So autoplay is basically native browser behavior same as navigating with chrome to that file

anyway, thx allot

**Comment by philpraxis** [comment]
FYI: On Chrome Version 108.0+ (Official Build) (x86_64), there's no autoplay behavior with q-video when using the q-video  with no options.
