### ISSUE TITLE
Datetime component customization

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#95]
I think the fontcolor of datetime component should be customizable. Currently does not seem to be the case (always black):
![screenshot from 2016-09-22 12-48-45](https://cloud.githubusercontent.com/assets/10334123/18745666/5a42b5e0-80c3-11e6-850d-0ef1caf1bff5.png)

![screenshot from 2016-09-22 12-52-31](https://cloud.githubusercontent.com/assets/10334123/18745695/864d7512-80c3-11e6-9a12-48f734330013.png)

**Comment by rstoenescu** [comment]
Will fix it. Nice font you chose there!

**Comment by rstoenescu** [comment]
In the mean time you can force color on those DOM elements.

**Comment by musicformellons** [comment]
Yep I did using:
.quasar-datetime-header
  color $text-color !important

.quasar-datetime
  color $text-color !important

**Comment by musicformellons** [comment]
I can not force on the month and the year views (already marked important), e.g. see here the month buttons are still black:
![screenshot from 2016-09-22 15-56-01](https://cloud.githubusercontent.com/assets/10334123/18750957/838a7c20-80dd-11e6-8f4c-23d6faa56842.png)

![screenshot from 2016-09-22 15-57-34](https://cloud.githubusercontent.com/assets/10334123/18750958/8397d3ca-80dd-11e6-8540-02b66465c1e5.png)

![screenshot from 2016-09-22 15-57-52]
(https://cloud.githubusercontent.com/assets/10334123/18750959/839b4d70-80dd-11e6-8b0d-3161adc03228.png)

**Comment by rstoenescu** [comment]
In `app.js` do a `require('./app.styl')`. Put all your app style in `app.styl`, like these overwrites. That's one way. There are some more ways, but this will do for you.

**Comment by musicformellons** [comment]
But how is that different from:
```
require('./themes/app.' + __THEME + '.styl')
// require('quasar/dist/quasar.' + __THEME + '.css')
Quasar.theme.set(__THEME)
```
in `app.js `using the `app.variable.style` I am doing now?

In app.variable.style I have (which does not work):
```
.quasar-datetime-view-year button
  color #5e4c46 !important
```

**Comment by rstoenescu** [comment]
require('./themes/app.' + __THEME + '.styl')
// require('quasar/dist/quasar.' + __THEME + '.css')
require('./app.styl')
Quasar.theme.set(__THEME)

**Comment by musicformellons** [comment]
Yeah, works. Still do not really get why, but works.

**Comment by rstoenescu** [comment]
Simple: you include Quasar theme then you include your own CSS where you can overwrite anything.
Do not forget about Stylus variables that you can change. http://quasar-framework.org/api/css-stylus-variables.html

**Comment by rstoenescu** [comment]
To add a stylus variable is really easy. Wanna give it a try for PR?

**Comment by musicformellons** [comment]
Ok, will try, but not in a short while.

**Comment by rstoenescu** [comment]
This will be possible in v0.11 (and it might even work with v0.10, but not tested with this version) and latest Quasar app template / boilerplate.
