### ISSUE TITLE
Cursor pointer doesn't appear after last update.

### ISSUE THREAD

**Issue by fomalhaut79** [quasarframework/quasar#9502]
**Describe the bug**
Go to [https://next.quasar.dev/vue-components/button](https://next.quasar.dev/vue-components/button). Move the mouse over a button element. Cursor doesn't change to pointer.

Quasar Version: v2.0.0-beta.19

OS: MacOs 10.14.6
Browsers: Chrome 91

**Additional context**
It probably happens due to an empty q-notification component located at the bottom of the page

**Comment by metalsadman** [comment]
@fomalhaut79 works fine on mine on `chrome Version 90.0.4430.212 (Official Build) (64-bit)`, you should probably check for a rogue browser extension messing it up.

**Comment by rstoenescu** [comment]
Latest version of Chrome is 90. I see you're on 91, so you're on the beta channel, which means it has bugs. This has nothing to do with Quasar.

**Comment by hawkeye64** [comment]
My latest is 91, but the issue described above does not happen for me on v2 or v1 docs. The cursor changes on both.

![image](https://user-images.githubusercontent.com/10262924/120328596-34bc9300-c2a8-11eb-9264-a0e11f18c5b3.png)
