### ISSUE TITLE
QFile not aligned correctly in q-gutter-*

### ISSUE THREAD

**Issue by miladmeidanshahi** [quasarframework/quasar#9509]
**Describe the bug**
`QFile` has extra CSS property `width: 100%` that cause the field can't aligned when use `q-gutter-*` classes.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/miladmeidanshahi/pen/OJpzxZX?editors=101

**Expected behavior**
`QFile` should be like `QInput` component.

**Platform (please complete the following information):**
Quasar Version: 1.15.19
Quasar mode:

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v1.15.20 and v2.0.0-rc.1
