### ISSUE TITLE
QTime issue :bug:

### ISSUE THREAD

**Issue by RJYOMAN485** [quasarframework/quasar#9513]
QTime :houroption greater than 12 ie, [13,14,15,..] not working :bug:

**Comment by rstoenescu** [comment]
Hi. The prop is named `hour-options`, not `houroption`.
Seems to be working fine: https://next.quasar.dev/vue-components/time#limiting-options

Please fill in the required template. Is this v1 or v2, what build mode, codepen/jsfiddle?
