### ISSUE TITLE
q-img not scaling down the image

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar#9514]
**Describe the bug**
There might be a small bug in Quasar v2. Since the update from v1 to v2 we see that the image used with the code below is no longer scaled to fit the circle. We tried using `fit` but no luck..
```ts
<template>
  <div>
    <q-chip clickable @click="goToProfilePage" class="absolute-right">
      {{ profile.givenName || t('general.welcome') }}
      <q-avatar class="q-avatar--right">
        <q-img
          :src="photo"
          spinner-color="black"
          width="38px"
          transition="scale"
          ratio="1"
          :placeholder-src="placeholder"
        />
      </q-avatar>
    </q-chip>
  </div>
</template>
```
![unknown](https://user-images.githubusercontent.com/10828570/120440228-a1f12680-c383-11eb-9fe2-25632fe0ac76.png)

**Codepen/jsFiddle/Codesandbox (required)**
[Codepen](https://codepen.io/DarkLite1/pen/LYWQGyL)

**To Reproduce**
Run the Codepen and notice the image is not fitting in the circle. 

**Expected behavior**
Same scaling as in Quasar v1

**Platform (please complete the following information):**
Quasar Version:"^2.0.0-beta.17",
@quasar/app Version: "3.0.0-beta.24"
Quasar mode:
  - [x] SPA

OS: Windows Server 2016
Node: v14.15.4

**Additional context**
Asked on Discords but they advised me to create a Codepen.

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in Quasar v2.0.0-beta.20.
