### ISSUE TITLE
`QIntersection` doesn't work inside iframe even with root prop being set

### ISSUE THREAD

**Issue by hivokas** [quasarframework/quasar#9517]
**Describe the bug**
`QIntersection` doesn't work inside iframe even with root prop being set.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/hivokas/pen/RwpQRaa?editors=111 (that's example from the documentation: https://quasar.dev/vue-components/intersection#example--root-viewport)

**To Reproduce**
1. Use QIntersection on the page
2. Open this page inside iframe
3. See that the content is not visible

**Expected behavior**
The content is visible.

**Screenshots**
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/22997803/120446705-7de91180-c392-11eb-8dc0-0c687acbf133.png">

**Platform (please complete the following information):**
Quasar Version: 1.15.19
@quasar/app Version:
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS
Node: v16.0.0
NPM: 7.10.0
Yarn: 1.22.10
Browsers: Safari, Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-rc.1 and v1.15.20.

Workaround before the releases above is to also set `margin` or `threshold` props. Example `margin: '0px'`

**Comment by hivokas** [comment]
> Thanks for reporting.
> Fix will be available in Quasar v2.0.0-rc.1 and v1.15.20.
> 
> Workaround before the releases above is to also set `margin` or `threshold` props. Example `margin: '0px'`

Thanks!!
