### ISSUE TITLE
BEX: Dialog in Popop not respecting configuration

### ISSUE THREAD

**Issue by preraksola** [quasarframework/quasar#9519]
**Describe the bug**
I have a custom dialog component that I am trying to display in the popup page of a BEX project. In the config I have set `persistent: true` but as soon as the dialog appears, the popup window gets resized so a small window.

While researching about this I came accross this https://forum.quasar-framework.org/topic/7794/dialog-in-bex-popup and so added `seamless: true` as well. However, the issue is still there.

As soon as I click somewhere in the small popup window, I can see the animation of a dialog closing and the popup window is resized to the original size (hence not respecting the `persistent` config). I added `noBackdropDismiss: true, noEscDismiss     : true,	 noRouteDismiss   : true` as well, but still no change.

Upon implementing via the "Dialog component", it works fine, but not with the "Dialog plugin" approach.

**Codepen/jsFiddle/Codesandbox (required)**
I am no sure if this can be reproduced via Codepen/jsFiddle/Codesandbox so below is the code that I have:

 ### ValidatePinDialog.vue (Dialog Component)
```
<template>
	<q-dialog
		ref="dialog"
		@hide="onDialogHide">

		<q-card class="q-dialog-plugin">
			<q-card-section>
				<div class="text-h6">{{ $t ( "pinLabel" ) }}</div>
			</q-card-section>

			<q-card-section class="q-pt-none">
				<q-input
					outlined
					dense
					v-model="pin"
					autofocus />

				<q-chip
					v-if="errorMessage.length > 0"
					square
					outline
					icon="mdi-alert-circle"
					color="negative">{{ errorMessage }}
				</q-chip>
			</q-card-section>

			<q-card-actions align="right">
				<q-btn
					type="submit"
					color="primary"
					:label="$t('validatePinForm')"
					@click="validatePin" />
			</q-card-actions>
		</q-card>
	</q-dialog>
</template>

<script lang="ts">
import { defineComponent }                        from "vue";
import { QDialog }                                from "quasar";

export default defineComponent ( {
	name: "ValidatePinDialog",
	data () {
		return {
			pin         : "",
			errorMessage: ""
		};
	},
	emits  : [
		"ok", "hide"
	],
	methods: {
		show () {
			( this.$refs.dialog as QDialog ).show ();
		},
		hide () {
			( this.$refs.dialog as QDialog ).hide ();
		},
		onDialogHide () {
			this.$emit ( "hide" );
		},
		onOKClick () {
			this.$emit ( "ok" );
			this.hide ();
		},
		async validatePin () {
			appendDebugMessage ( "PIN set successfully" );
                        this.hide();
		}
	}
} );
</script>
```

### PopupPage.vue (Parent Component)
```
import ValidatePinDialog  from "components/ValidatePinDialog.vue";

<script lang="ts">

export default defineComponent ( {
	name      : "PopupPage",
	data () {
		return { };
	},
	async mounted () {
		this.showPinValidationDialog ();
	},
	methods: {
		showPinValidationDialog () {
			this.$q.dialog ( {
				component        : ValidatePinDialog,
				persistent       : true,
				noBackdropDismiss: true,
				noEscDismiss     : true,
				noRouteDismiss   : true,
				seamless         : true
			} ).onOk ( async () => {
				console.log ( "OK" );
			} );
		}
	}
} );
</script>

```

**Expected behavior**
Dialog should remain persistent if `persistent: true` is set in the config object.

**Screenshots**

Popup Window upon invoking dialog
![image](https://user-images.githubusercontent.com/8655814/120472760-93683680-c3a6-11eb-959e-ec2819234d95.png)

Popup Window after clicking somewhere in the small window
![image](https://user-images.githubusercontent.com/8655814/120472917-c1e61180-c3a6-11eb-9d9c-56938e4fc2d4.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.0-beta.1

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [X] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [X] BEX

OS: Windows 10
Node: 16.2.0
NPM: 7.13.0
Browsers: Chrome

**Comment by Smrtnyk** [comment]
You are running first beta version, I would bump to latest both quasar and quasar/app and see if it was fixed
There were many improvements since

**Comment by preraksola** [comment]
I bumped both of them to the latest one **3.0.0-beta.28**, but the issue still persist.

**Comment by Smrtnyk** [comment]
you are passing persistent true as a prop but I don't see it being aplied to the q-dialog component

**Comment by preraksola** [comment]
@Smrtnyk I am passing `persistent: true` in the `this.$q.dialog()` method and not as a prop.
Moreover, I don't think I need to apply it on the q-dialog componenet as per the [docs](https://next.quasar.dev/quasar-plugins/dialog#options-api-variant).

**Comment by Smrtnyk** [comment]
I cannot find in the docs where it would state usage like that
I just see the options like
```
$q.dialog({
    component: CustomComponent,

    // props forwarded to your custom component
    componentProps: {
      text: 'something',
      // ...more..props...
    }
    ```
    And in examples there is no mention of persistence being applied automaticaly
    
    Can you copy the part of the docs or paste a screenshot with highlighet example or description about it?

**Comment by preraksola** [comment]
Oh, how dumb of me. I had a look at the [sample code](https://next.quasar.dev/quasar-plugins/dialog#predefined) of predefined dialogs and in that the options are passed directly.

However, in the scenario where a `component` is used, all the options should be passed in `componentProps` object. I missed this and as a result it was not working.

I updated my invokation to this as it works now:
```
this.$q.dialog ( {
	component     : ValidatePinDialog,
	componentProps: {
		persistent : true,
                seamless: true
	}
} ).onOk ( () => {
	console.log ( "OK" );
} );
```

However, I still have to pass `seamless` in order to maintain the popup window size. Without it, the window again shrinks to a small size.

Thanks a lot for your help @Smrtnyk  !!
