### ISSUE TITLE
TypeError when going to root route in layout when left sidebar open

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#952]
### Software version

Quasar: 0.14.4
OS: MacOS
Node: 7.10.0
NPM: 4.2.0
Browsers: Chrome, Safari ( Firefox may be ok )
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at style (quasar.esm.js?8bfb:217)
    at width (quasar.esm.js?8bfb:231)
    at VueComponent.__redraw (quasar.esm.js?8bfb:10864)
    at VueComponent.boundFn (vue.runtime.esm.js?ff9b:165)
    at later (quasar.esm.js?8bfb:955)
style @ quasar.esm.js?8bfb:217
width @ quasar.esm.js?8bfb:231
__redraw @ quasar.esm.js?8bfb:10864
boundFn @ vue.runtime.esm.js?ff9b:165
later @ quasar.esm.js?8bfb:955
setTimeout (async)
(anonymous) @ quasar.esm.js?8bfb:963
(anonymous) @ quasar.esm.js?8bfb:10989
setTimeout (async)
(anonymous) @ quasar.esm.js?8bfb:10988
(anonymous) @ vue.runtime.esm.js?ff9b:651
nextTickHandler @ vue.runtime.esm.js?ff9b:598
Promise resolved (async)
timerFunc @ vue.runtime.esm.js?ff9b:613
queueNextTick @ vue.runtime.esm.js?ff9b:661
Vue.$nextTick @ vue.runtime.esm.js?ff9b:3871
mounted @ quasar.esm.js?8bfb:10979
callHook @ vue.runtime.esm.js?ff9b:2552
insert @ vue.runtime.esm.js?ff9b:3379
invokeInsertHook @ vue.runtime.esm.js?ff9b:5207
patch @ vue.runtime.esm.js?ff9b:5372
Vue._update @ vue.runtime.esm.js?ff9b:2319
updateComponent @ vue.runtime.esm.js?ff9b:2435
get @ vue.runtime.esm.js?ff9b:2774
run @ vue.runtime.esm.js?ff9b:2844
flushSchedulerQueue @ vue.runtime.esm.js?ff9b:2611
(anonymous) @ vue.runtime.esm.js?ff9b:651
nextTickHandler @ vue.runtime.esm.js?ff9b:598
Promise resolved (async)
timerFunc @ vue.runtime.esm.js?ff9b:613
queueNextTick @ vue.runtime.esm.js?ff9b:661
queueWatcher @ vue.runtime.esm.js?ff9b:2698
update @ vue.runtime.esm.js?ff9b:2834
notify @ vue.runtime.esm.js?ff9b:728
reactiveSetter @ vue.runtime.esm.js?ff9b:958
proxySetter @ vue.runtime.esm.js?ff9b:2959
start @ quasar.esm.js?8bfb:571
boundFn @ vue.runtime.esm.js?ff9b:165
(anonymous) @ MainLayout.vue?524d:110
iterator @ vue-router.esm.js?fe87:1870
step @ vue-router.esm.js?fe87:1652
step @ vue-router.esm.js?fe87:1656
step @ vue-router.esm.js?fe87:1656
runQueue @ vue-router.esm.js?fe87:1660
confirmTransition @ vue-router.esm.js?fe87:1899
transitionTo @ vue-router.esm.js?fe87:1801
push @ vue-router.esm.js?fe87:2099
push @ vue-router.esm.js?fe87:2416
navigate @ NavIconBar.vue?8bdd:120
boundFn @ vue.runtime.esm.js?ff9b:164
click @ NavIconBar.vue?22ac:18
invoker @ vue.runtime.esm.js?ff9b:1733
Vue.$emit @ vue.runtime.esm.js?ff9b:2202
click @ quasar.esm.js?8bfb:3081
boundFn @ vue.runtime.esm.js?ff9b:164
invoker @ vue.runtime.esm.js?ff9b:1733

### What were you expecting?
No error and the route to change

### What steps did you take, to get the error?

A snippet of the routes: 
routes: [
    {
      path: '/',
      component: load('layouts/MainLayout'),
      children: [
        {
          path: '',
          component: load('routes/IndexRoute'),
          name: 'home'
        },

To cause it I load http://localhost:8080

Open the side bar and click a q-side-link item to goto /whatever.

Open the sidebar again and click a button I have that does: @click="navigate({name: 'home'})"

I then see the error in the console and the sidebar closes but the route did not change. If I then click that same button again, the route does change to the home route and I do not see a second error.

**Comment by rstoenescu** [comment]
You should first close the sidebar then navigate away.
`@click="layout.hideLeft(() => navigate({name: 'home'}))` (hideLeft/hideRight upon the case).

**Comment by smakinson** [comment]
I went to go make the change and this is what I have in navigate() now:

this.layout.hideLeft()
this.$router.push(to)

**Comment by smakinson** [comment]
oh wait, I just noticed your giving it as a callback, I'll go look at doing it that way.

**Comment by smakinson** [comment]
@rstoenescu This works to fix the error, but if the side is not open the navigate is never called. Is that the expected behavior?

**Comment by rstoenescu** [comment]
@smakinson Can you try latest edge and see if you still got a problem? Thanks!

**Comment by smakinson** [comment]
@rstoenescu Looks like its good on edge. Is that targeted for 0.14.7?

**Comment by rstoenescu** [comment]
Yes. Releasing 0.14.7 in a few days

**Comment by Isarstyle** [comment]
Having the same error, with child routes, with one difference: 
 using the q-side-link "to" description, cannot hide the sidebar by the click event. 
 example: <q-side-link item to="/secure/clients">
