### ISSUE TITLE
Deps problem of babel-preset-app

### ISSUE THREAD

**Issue by Clazex** [quasarframework/quasar#9526]
`@quasar/babel-preset-app` depends on `babel-loader` which requires `@babel/core@^7.0.0` and `webpack>=2` as peer dependencies, but does not provide them, causing Yarn 2 to complain about that.

Solution: Add `@babel/core@^7.0.0` and `webpack>=2` as peer dependencies of `@quasar/babel-preset-app`

**Comment by rstoenescu** [comment]
Please use yarn 1.x. We currently haven't had time to add support for Yarn 2.
