### ISSUE TITLE
Touch Swipe Directive registers on all directions when told not to. (v-touch-swipe)

### ISSUE THREAD

**Issue by sanchaz** [quasarframework/quasar#9533]
**Describe the bug**
Quasar v2 touch swipe directive will capture all directions, if told to do otherwise.

<div v-touch-swipe.right="userHasSwiped">...</div>

Should only capture right swipes.

However initially it will only capture right swipes, but after you swipe once to the right, it will start capturing swipes in all directions.

This actually makes it a pain on mobile (PWA) as scrolling becomes disabled if you have a swipe action that covers the whole page.

**Codepen/jsFiddle/Codesandbox (required)**
No Codepen/jsFiddle/Codesandbox as quasar already provides the demos.

1. [Quasar v1](https://quasar.dev/vue-directives/touch-swipe#example--one-direction-only)
2. [Quasar v2](https://next.quasar.dev/vue-directives/touch-swipe#example--one-direction-only)

**To Reproduce**
1. Go to '[Quasar v1](https://quasar.dev/vue-directives/touch-swipe#example--one-direction-only)'
2. Swipe 'left', nothing happens as expected
3. Swipe 'right' as expected it registers. 
4. Swipe 'left' nothing happens.
5. Go to '[Quasar v2](https://next.quasar.dev/vue-directives/touch-swipe#example--one-direction-only)'
6. Swipe 'left', nothing happens as expected
7. Swipe 'right' as expected it registers.
8. Swipe 'left' it registers, which is not the expected behaviour.

**Expected behavior**
Behave the same as quasar v1 and not register all swipe directions after the first swipe.

**Screenshots**
Not aplicable.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Might be the same on others but haven't tested.

Tested on:
  - [x] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu
Browsers: 
Firefox 88.0
Chrome 90.0.4430.93

iOS:
Same behaviour on browser but tester didn't report the browser and version

Android:
Chrome 91.0.4472.77

**Additional context**
Nop

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-rc.1
