### ISSUE TITLE
layout-background not blocking page scroll in Cordova on iOS

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#954]
### Software version

Quasar: 0.14.4
OS: MacOS
Node: 7.10.0
NPM: 4.2.0
Browsers: Cordova
iOS: 11.0.1
Android:
Any other software related to your bug:

### What did you get as the error?
The user is able to scroll the page under the layout-background div.
### What were you expecting?
The page scrolling to be blocked as it is on android.
### What steps did you take, to get the error?
Open the sidebar on a cordova app and swipe the page to scroll it.

**Comment by bloodf** [comment]
You can check here https://github.com/quasarframework/quasar/issues/897
