### ISSUE TITLE
openapi-client-axios build issues with v2.00-beta.19 and typescript

### ISSUE THREAD

**Issue by yarivgdidi** [quasarframework/quasar#9548]
Hi
I'm trying to start a project with openapi-client-axios and quasar cli 
I was able to start a project with vue cli and then had issues adding Quasar
Then I've created the project using Quasar cli and having issues with the open-api-plugin

this has something to do with Webpack config

the errors I'm getting:

```
App •  DONE  • "UI" compiled with errors • 8342ms

 App •  ERROR  •  UI  in ./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js

Module not found: Can't resolve imported dependency "http"
Did you forget to install it? You can run: yarn add http

 App •  ERROR  •  UI  in ./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js

Module not found: Can't resolve imported dependency "https"
Did you forget to install it? You can run: yarn add https

 App •  ERROR  •  UI  in ./node_modules/@jsdevtools/ono/esm/types.js

Module not found: Can't resolve imported dependency "util"
Did you forget to install it? You can run: yarn add util


 App •  COMPILATION FAILED  • Please check the log above for details.
```

all errors go away when I comment out these lines:
```
   const api = new OpenAPIClientAxios({
        definition: 'openApi/petstore.old.yml',
      });
      Api.client = await api.init<PetStoreClient>();

```
and as said, this is working in a Vue cli scaffolded project
 
I was able to complete the build by adding  to quasar config
```

...
    build: {
      ...
       extendWebpack (config) {
          config.resolve.alias.https = false;
          config.resolve.alias.http = false;
     }
     }

```
 and then 

` yarn add util`

 but then I'm getting errors in the console 

```
Uncaught ReferenceError: process is not defined
    at eval (util.js?6aed:109)
    at Object../node_modules/util/util.js (vendor.js:5164)
    at __webpack_require__ (app.js:280)
    at fn (app.js:559)
    at eval (types.js:2)
    at Module../node_modules/@jsdevtools/ono/esm/types.js (vendor.js:722)
    at __webpack_require__ (app.js:280)
    at fn (app.js:559)
    at eval (index.js:9)
    at Module../node_modules/@jsdevtools/ono/esm/index.js (vendor.js:656)
```
    
The project is available at:`
https://github.com/yarivgdidi/PetStore-Vue-OpenApi`

The installation steps I took to create the project are at :
`https://github.com/yarivgdidi/PetStore-Vue-OpenApi/blob/main/README-SETUP-STEPS.md`

Thanks in advances and
Best regards
Yariv

**Comment by TobyMosque** [comment]
just use the `openapi-generator-cli` and generate a pick on of the javascript-* client generator

```bash
npm i -g @openapitools/openapi-generator-cli
openapi-generator-cli list
```

![image](https://user-images.githubusercontent.com/13981214/120800704-a00b9c80-c516-11eb-8bf8-15572d9a4962.png)

I think u plugin is using the nodejs server generator under the hook.
I would recommend the typescript-axios:

```bash
openapi-generator-cli generate -i https://petstore.swagger.io/v2/swagger.json -g typescript-axios -o PetStore.Client --skip-validate-spec --additional-properties packageName=PetStore.Client
```

![image](https://user-images.githubusercontent.com/13981214/120801235-4bb4ec80-c517-11eb-80e5-543e0b3af5bc.png)

So, just copy that ts files to u project:

![image](https://user-images.githubusercontent.com/13981214/120801304-64250700-c517-11eb-90cb-609ed70a38e2.png)

so, configure u boot:
```ts
import axios from 'axios'
import { PetApi } from 'src/client/index'
import { boot } from 'quasar/wrappers'

export default boot(({ app }) => {
  const instance = axios.create({ baseURL: 'https://petstore.swagger.io/' })
  const petApi = new PetApi(undefined, undefined, instance)
  app.config.globalProperties.$petApi = petApi
})
```
![image](https://user-images.githubusercontent.com/13981214/120802580-f8439e00-c518-11eb-986c-cda96d29ead0.png)

**Comment by hawkeye64** [comment]
Isn't `http` and `https` native Node packages? Which means they won't be available for the browser.
You should check your dependencies and see if they are made only for Node.

**Comment by yarivgdidi** [comment]
@TobyMosque,  Thanks I'll try the client you've suggested
@hawkeye64 , I'm guessing you're right, just that it worked on project generated by vue.cli, so I'm guessing this is a webpack  configuration issue/ Any way, I'll try a different client as Toby suggested

**Comment by rstoenescu** [comment]
Hi,

If it works on vue-cli doesn't actually mean we're doing something wrong. In fact, it's just masking the problem through Webpack 4 which automatically adds a nodejs polyfill. Quasar CLI on the other hand uses the newer Webpack 5 which dropped this polyfill, unmasking the problems.

However, should you want to just get rid of the issue with that package: https://next.quasar.dev/start/upgrade-guide#nodejs-polyfills **BUT we DON'T recommend it** as the problem needs to be dealt with by that package's maintainers instead.

**Comment by yarivgdidi** [comment]
@TobyMosque 
I'm following your instructions and it sure seems the right way
this is my first Vue typescript and I seems to be missing somethisg

how do I access the globals in component? in store Action?
in none typesctipt vue I would used this.$petApi.... 
what is the proper way here?

thanks
Yariv
