### ISSUE TITLE
Device screen blank on cordova build - Module build failed

### ISSUE THREAD

**Issue by victorfeitosa** [quasarframework/quasar#955]
Alright, I was trying to deploy a debug app with the cordova wrapper using quasar v0.13 and I got an issue, the device screen is blank and the console logs the following (with chrome inspector):

> vendor.js:11
> 
>  Error: Module build failed: Error: Cannot find module 'he'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/build.js:8:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/index.js:18:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/build.js:8:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/index.js:18:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at Object.157 (file:///android_asset/www/js/app.js:1:510)
>     at n (file:///android_asset/www/js/manifest.js:1:101)
>     at _t.render (file:///android_asset/www/js/app.js:1:1716)
>     at _t.e._render (file:///android_asset/www/js/vendor.js:11:41370)
>     at _t.i (file:///android_asset/www/js/vendor.js:11:8760)
>     at Ui.get (file:///android_asset/www/js/vendor.js:11:36689)
>     at new Ui (file:///android_asset/www/js/vendor.js:11:36511)
>     at pe (file:///android_asset/www/js/vendor.js:11:8785)
>     at _t.$mount (file:///android_asset/www/js/vendor.js:11:55849)
>     at _t.e._init (file:///android_asset/www/js/vendor.js:11:38843)T @ vendor.js:11
> vendor.js:18 Error: Module build failed: Error: Cannot find module 'he'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/build.js:8:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/index.js:18:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/build.js:8:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Design/Dev/Workspace/Github/taskorganizer/node_modules/vue-template-compiler/index.js:18:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at Object.207 (file:///android_asset/www/js/0.e6a30b18c12a8ec8edc3.js:1:43)
>     at n (file:///android_asset/www/js/manifest.js:1:101)
>     at file:///android_asset/www/js/app.js:1:8907o @ vendor.js:18
___

I'm using vue v2.3 since I have errors when using the select input (vue recommends it because the latest version has a bug with selects and their value binding). I wrapped my app with cordova and installed crosswalk, built with no issues nor warnings, but when I run it I get this error message and I have no idea what it is. Aparently the template compiler / module builder is going nuts, and since it points to a webpack compiled app.js it's pretty hard to guess at this point.
Has anybody been through this sort of issue?

**Comment by rstoenescu** [comment]
This should work with v0.14 and Vue 2.5.
