### ISSUE TITLE
Screen size change detection inside IFrame no longer working with latest versions of Chrome and Edge

### ISSUE THREAD

**Issue by rob-64** [quasarframework/quasar#9563]
Screen size change detection inside IFrame no longer working with latest versions of Chrome and Edge. It gets the initial screen size but does not seem to be getting the resize events from the visualViewPort.

[Codepen](https://codepen.io/irvingwa/pen/YzZaMWp)

Hard to tell, but it may be fixed in next version of chromium?
chromium fix:

[Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1213418&sort=&groupby=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&x=m&y=releaseblock&cells=tiles&q=os%3Dchrome%20M%3D91%20status%3DFixed&can=1)

Quasar mode:
  - [X] SPA

Tested on:
  - [X] SPA

OS:
Browsers: Chrome, Edge latest

**Comment by rstoenescu** [comment]
Indeed seems to be problems with Chrome 91 but not with Chrome 90. Nothing we can do except to wait for browsers to fix this...

**Comment by rob-64** [comment]
Alright. Sounds good
