### ISSUE TITLE
[Feature Request] Provide option to unfocus QSelect when an option is selected

### ISSUE THREAD

**Issue by douglasg14b** [quasarframework/quasar#9576]
**Is your feature request related to a problem? Please describe.**
It's undesirable for the QSelect to stay focused (highlighted) after a selection has been made for my application

**Describe the solution you'd like**
A prop that disables this behavior

**Describe alternatives you've considered**
Unknown, copy pasting the code into my project and modifying it myself? Seems too janky.

**Comment by MilosPaunovic** [comment]
Hello @douglasg14b,

I'm not sure this is something that a lot of users will need (someone from the core team is welcome to correct me if I'm wrong) so I don't really see it as a feature in the near future.

Until then, you could create that behaviour by setting a `ref` of your `QSelect` and utilise existing `@input` event to blur it manually, as in the example below:

```js
<q-select
   v-model="selected"
   :options="options"
   label="Something cool"
   ref="myRef"
   @input="$refs.myRef.blur()"
/>
```

Hope that helps 😃

**Comment by pdanpdan** [comment]
The solution is the one above: blur the field if you want.

**Comment by douglasg14b** [comment]
While this does work, it's pretty kludgy no?
