### ISSUE TITLE
VueX not available in Quasar v2-rc1

### ISSUE THREAD

**Issue by maggie0002** [quasarframework/quasar#9585]
**Describe the bug**
I just updated from Quasar v2 beta to Quasar v2-rc1 (using `quasar upgrade -i`). I started seeing the following error when running quasar dev:

`TS2307: Cannot find module 'vuex' or its corresponding type declarations.`

I have been using VueX in the previous beta without any issues. When running `quasar info` I see:

`vuex - Not installed`

Seems like the VueX dependency has dropped out. 

Tried removing the node_modules folder and running yarn install, still nothing. 

Tried adding a VueX store with `quasar new store -f ts-composition savedResources`, which adds the store files as expected, but still shows `vuex - Not installed` in `quasar info`.

Looking at the docs, it suggests this should be handled by the CLI. Is there something needing to be done to trigger the installation?

**Comment by kei-ichi** [comment]
@maggie0002 If you read the latest release note, you will know why bro: 

> ### Breaking change

> **Not supplying "vuex" package anymore. If using a store, please yarn add vuex@4 / npm install vuex@4.
This makes sense because decoupling Vuex will allow developers to upgrade to the future Vuex 5 without us making any breaking changes.**

**Comment by maggie0002** [comment]
Thanks, makes sense. I searched the upgrade guide, couldn’t see anything on it there. Worth adding though if it’s missing.

**Comment by hawkeye64** [comment]
Yes, the docs need to be updated about this.

**Comment by kei-ichi** [comment]
@hawkeye64 The docs **"have to"** update about this because this is breaking change and it will make soooo many devs confused. Surprisingly, the CLI still have an option to add Vuex and it still work if you create new project with CLI.

**Comment by maggie0002** [comment]
When running `quasar info` on -rc1 I see `vuex - 4.0.1 -- state management for Vue.js` after installing manually. Everything works as expected, although I had thought `quasar info` only displayed packages that were managed by Quasar CLI? I had been using it as a guide to what I should be updating manually and what Quasar takes care of. Now VueX isn't managed by Quasar, I had expected it not to be in the list anymore.

**Comment by rstoenescu** [comment]
@maggie0002 the "quasar info" command is useful when logging tickets here on Github, so it makes sense to keep it there.

On another topic, updated docs and will be available on next deployment.
