### ISSUE TITLE
[proposal] get browser language Util

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#959]
It would be great if there could be a DOM Util for retrieving the browser language!
In JS that would be `navigator.language || navigator.userLanguage` but since Quasar is nicely gathering all handy Utils, that is another one for the family!

**Comment by spaceywolfi** [comment]
a nice function for this would be:

const detectLocale = () => {
  // Based on https://angular-translate.github.io/docs/#/guide/07_multi-language#multi-language_determining-preferred-language-automatically
  let val =
    navigator.languages[0] ||
    navigator.language ||
    navigator.browserLanguage ||
    navigator.systemLanguage ||
    navigator.userLanguage
  if (val) {
    return val.replace(/-.*$/, '')
  }
}

**Comment by rstoenescu** [comment]
Will incorporate this in the i18n work ;) Thanks for suggesting this.

**Comment by rstoenescu** [comment]
In next v0.15 beta tomorrow.
