### ISSUE TITLE
 How to add a click on the expasion-icon (arrow) icon if the expand-icon-toggle mode is on

### ISSUE THREAD

**Issue by antbelogurov** [quasarframework/quasar#9594]
I am using q-expansion-item with expand-icon-toggle mode.
I'm loading from the backend and I need to hang this event on the icon. How to implement this?

**Comment by MilosPaunovic** [comment]
Hello @antbelogurov,

Do you need `click` event specifically or you can get around with some of the `QExpansionItem`s events like this example below:

```js
<q-expansion-item
  @input="doSomething"
  expand-icon-toggle
  icon="perm_identity"
  label="Account settings"
  caption="John Doe"
>
  <q-card>
    <q-card-section>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, eius reprehenderit eos corrupti
        commodi magni quaerat ex numquam, dolorum officiis modi facere maiores architecto suscipit iste
        eveniet doloribus ullam aliquid.
    </q-card-section>
  </q-card>
</q-expansion-item>
```

**Comment by antbelogurov** [comment]
> Hello @antbelogurov,
> 
> Do you need `click` event specifically or you can get around with some of the `QExpansionItem`s events like this example below:
> 
> ```js
> <q-expansion-item
>   @input="doSomething"
>   expand-icon-toggle
>   icon="perm_identity"
>   label="Account settings"
>   caption="John Doe"
> >
>   <q-card>
>     <q-card-section>
>         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, eius reprehenderit eos corrupti
>         commodi magni quaerat ex numquam, dolorum officiis modi facere maiores architecto suscipit iste
>         eveniet doloribus ullam aliquid.
>     </q-card-section>
>   </q-card>
> </q-expansion-item>
> ```

Hi, thank you, but I want one function to occur when I click on the expansion, and another when I click on the expansion icon.
Example:
`  :label="title"
        exact-active-class="text-bold"
        @click="doSomething"
        class="cursor-pointer"
        expand-icon-toggle
        @input="doSomethingSecond"`

this does not work
