### ISSUE TITLE
Add current date highlight to material datetime picker component 

### ISSUE THREAD

**Issue by pure-zero** [quasarframework/quasar#960]
As per the material docs todays date needs to be highlighted 

https://material.io/guidelines/components/pickers.html#pickers-usage

"The selected day is indicated by a filled circle. The current day is indicated by a different color and type weight."

Can we get this feature implemented and adhere to the design docs?

Thanks,
Kartik.

**Comment by pure-zero** [comment]
https://github.com/quasarframework/quasar/pull/961

**Comment by rstoenescu** [comment]
Available in edge and future v0.14.5
