### ISSUE TITLE
QDate wrong selected value is displayed

### ISSUE THREAD

**Issue by AlexanderKuzmichev** [quasarframework/quasar#9600]
**Describe the bug**
The wrong selected value is displayed and processed if select same month/day and a different year.

**Codepen/jsFiddle/Codesandbox (required)**
[Fork a Codepen](https://codepen.io/M__A__K/pen/JjWZOEv?editors=101)

**To Reproduce**
1. Open picker
2. Select some year other than current (e.g. 2022)
3. Select same month (March)

**Expected behavior**
2022/03/01 is not selected (because the current date is 2021/03/01)

**Platform (please complete the following information):**
Quasar Version: 1.15.20
@quasar/app Version:
Quasar mode:

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Browsers: Firefox 89.0 (64-bit), Chrome 91.0.4472.77 (Official Build) (64-bit)

**Comment by pdanpdan** [comment]
I cannot reproduce it. Can you provide a step by step procedure to reproduce?
Including a codepen or a link to the example in the docs.

**Comment by AlexanderKuzmichev** [comment]
@pdanpdan did you try my [codepen](https://codepen.io/M__A__K/pen/JjWZOEv?editors=101)?
Repro steps:
1. Set the initial `value` (not `v-model`!) of the picker to 2021/03/01 and `default-view="Years"`
2. Open picker (by button click on the button in the codepain)
3. Click on the year "2022"
4. Click on the month "MAR"

**Result**: 2022/03/01 is selected as current value while the correct one is 2021/03/01 (see the badge value)
![2021-06-07](https://user-images.githubusercontent.com/3074079/121069920-bba4ca80-c7d6-11eb-8c37-2ad2774a12b9.png)

I can record a video if you want

**Comment by pdanpdan** [comment]
You use emit-immediately, so when you select the year you also change it.

**Comment by AlexanderKuzmichev** [comment]
@pdanpdan but I don't update `date`

**Comment by pdanpdan** [comment]
Found it :) Thank you for holding on strong against me.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.21 and v2.0.0-rc.3.
