### ISSUE TITLE
"Buffer is not defined" after upgrade from 11 to 16 (in 19, still the same error)

### ISSUE THREAD

**Issue by DrakoPOD** [quasarframework/quasar#9602]
**Describe the bug**
MQTT.js library stopped working after update, it says:
```
ReferenceError: Buffer is not defined
    at eval (constants.js?885d:46)
    at Object../node_modules/mqtt-packet/constants.js (vendor.js:3424)
    at __webpack_require__ (app.js:315)
    at fn (app.js:579)
    at eval (parser.js?7aac:4)
    at Object../node_modules/mqtt-packet/parser.js (vendor.js:3474)
    at __webpack_require__ (app.js:315)
    at fn (app.js:579)
    at eval (mqtt.js?e7bd:1)
    at Object../node_modules/mqtt-packet/mqtt.js (vendor.js:3444)
```

**To Reproduce**
1. Create a new quasar project
2. Install [MQTT.js library](https://github.com/mqttjs/MQTT.js)
3. Call `mqtt.connect`, no matter where from, but if you call this from boot your page will not load.
4. Open console in the browser and see the error.

**Expected behavior**
Connect to a MQTT broker

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:  16, 19
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10  19042
Node: 14.17.0
NPM: 6.14.13
Yarn: 1.22.10
Browsers: Edge v91.0.864.41

**Comment by iklemm** [comment]
This is exact the information i need.
But:
Can't access https://next.quasar.dev/start/upgrade-guide#nodejs-polyfills due to certificate problem

**Comment by rstoenescu** [comment]
The next.quasar.dev is obsolete.
Here's the current link: https://quasar.dev/start/upgrade-guide#nodejs-polyfills
