### ISSUE TITLE
dialog plugin problem

### ISSUE THREAD

**Issue by k3341095** [quasarframework/quasar#9603]
I am of quasar
I programmed it using dialog plugin.
The source is below.

      this.$q
        .dialog({
          component: detailView,
          parent: this,
          order: this.selectedItem
        })
        .onOk(res => {
          debugger;
          if (res.command === "preItem") {
            this.itemIdx -= 1;
          }
          if (res.command === "nextItem") {
            this.itemIdx += 1;
          }
          this.selectItem(this.itemIdx);
        });

Exported this.selectedItem as props.

After that, I updated this.selectedItem
The contents inside the child component are not changed.

When this.selectedItem is changed.. the content of the component is also changed
want to change..

How is there a way?

Quasar Version:1.5
@quasar/app Version: 1.5
Quasar mode:

  - [x] SPA

Tested on:
  - [x] SPA

OS: windows 10
Node: 15.14
NPM:  7.9
Browsers: chrome

**Comment by rstoenescu** [comment]
Hi,

You need to call the `update()` method.

```js
const dialog = this.$q.dialog({ ... })
// ....
dialog.update({ order: this.selectedItem })
```
