### ISSUE TITLE
q-toggle prevent switching

### ISSUE THREAD

**Issue by lunzilunzi** [quasarframework/quasar#9615]
example：
https://element-plus.gitee.io/#/en-US/component/switch
![image](https://user-images.githubusercontent.com/26265113/121286758-df6d2b00-c912-11eb-9d75-9fbef880996d.png)

**Comment by rstoenescu** [comment]
Hi,

This is essentially what the `disable` prop does.

**Comment by lunzilunzi** [comment]
> Hi,
> 
> This is essentially what the `disable` prop does.

The current q-toggle, after clicking, the bound value will change immediately. The significance of this function is that I can judge first, and then decide whether to change

**Comment by rstoenescu** [comment]
You can also use a computed property. It doesn't makes sense to display something to the user that upon interacting with it it will say "nope, you actually can't change this". It's also not a "vue-like" way of thinking about the UI.

**Comment by lunzilunzi** [comment]
@rstoenescu Thank you, I can achieve it by using `:model-value` one-way binding
