### ISSUE TITLE
[Request] Data Table custom header tooltip

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#962]
I'm writing a project and use acronyms in Data Table headers, so I was thinking that it would help if you could hover over the header and see it's whole name. Then I noticed that there is a default tooltip showing. It would be really great if we could replace it with what we want.

**Comment by rstoenescu** [comment]
Part of v0.15 datatable revamp. You'll love it ;)

**Comment by rstoenescu** [comment]
Closing as code is ready in future v0.15.
