### ISSUE TITLE
[docs] QOptionGroup API says it has 2 events but shows only one

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#9621]
https://quasar.dev/vue-components/option-group
QOptionGroup API says it has 2 events but shows only one. Either scroll is missing or there event count is wrong and there is just one. Windows 10 21H1, Firefox 89. 

![obraz](https://user-images.githubusercontent.com/9776384/121355842-988e2e00-c930-11eb-81a9-d4503263a2f9.png)

**Comment by rstoenescu** [comment]
@robert-niestroj thanks for reporting!
@MilosPaunovic thanks for the PR!

Fix to docs will be available on next deployment.
