### ISSUE TITLE
Hot reload and changes not taken into account when editing a package in node_modules folder

### ISSUE THREAD

**Issue by sebastien-vedrine** [quasarframework/quasar#9626]
I just installed a new Quasar v2 (rc-1 build) app.

After running `quasar dev`, when I edit my files in the `src` directory, the live reload happens with the latest modifications.
However when editing my dependency files (in `node_modules`) for dev purposes, the console warned me that the webpack-dev-server hot reloads but my components don't re-render and all my changes are not taken into account (even if I refresh the whole page).

This is what's displayed in the console when editing a file in a `node_modules` package (hot reload **not working**):
<img width="434" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/33923690/121386308-2de9ec00-c94a-11eb-9f54-5b78c5157883.png">

When editing an `src` file (hot reload **working**):
<img width="431" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/33923690/121387733-33940180-c94b-11eb-9084-c910c5e8086a.png">

In my previous Quasar v1 projects, I never encountered this issue. I was able to change any file in the `node_modules` folder and had hot reload working (without any specific configuration).

I've tried to add this config I found [here](https://next.quasar.dev/app-extensions/development-guide/introduction#install-and-prompts-scripts)
I'm aware this config is made for quasar extensions, but I think it should still work with any `node_modules`.
```
devServer: {
    https: false,
    port: 8080,
    open: false,
    watchOptions: {
      ignored: [
        'node_modules',
        '!node_modules/my-module',
      ],
    },
  },
```
But an error occurs stating that watchOptions does not match the API schema (when running `quasar dev`)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33923690/121386223-1ad71c00-c94a-11eb-80cc-c450a19beceb.png)

**To Reproduce**
1. Install a fresh Quasar v2 (rc-1) project.
2. Edit a package file in the node_modules folder.
3. Check your browser.

**Platform (please complete the following information):**
Quasar Version: v.2.0.0-rc1
@quasar/app Version: ^3.0.0-beta.1
Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: debian
Node: v14.16.1
NPM: 6.14.12
Yarn: 1.22.10
Browsers: Google Chrome

**Comment by hawkeye64** [comment]
Try this:
```js
  devServer: {
    https: false,
    port: 8080,
    open: false,
  watchOptions: {
    ignored: [
      /node_modules([\\]+|\/)+(?!my-package-name)/
    ]
  },
},
```

**Comment by hawkeye64** [comment]
@sebastien-vedrine 
I did some research and found out just including `watchOptions` causes this issue. As a workaround, you can roll back to an earlier version (beta15) until a fix is made.

**Comment by sebastien-vedrine** [comment]
@hawkeye64 
Thank you for your investigations.
When do you think this will be fixed?
Can you please update this issue when this is done? It is quite blocking for me right now.

**Comment by hawkeye64** [comment]
@sebastien-vedrine I don't think it'll be fixed until early next week

**Comment by sebastien-vedrine** [comment]
Okay that would be nice, thank you!

**Comment by rstoenescu** [comment]
There is no fix that we can do because this is a webpack v5 issue and outside of our reach. Everything under quasar.conf.js > devServer is passed to webpack-dev-server. Please open a ticket on https://github.com/webpack/webpack-dev-server and mention it's for v4.0.0-beta.3
