### ISSUE TITLE
How to generate .aab for Google Play

### ISSUE THREAD

**Issue by otabekoff** [quasarframework/quasar#9631]
**Is your feature request related to a problem? Please describe.**
When I uploaded my apk to Google Play, I noticed a warning in Google Play Console.
There it is being noticed that Google Play stops accepting .apk files after 2 months.
And they were telling that only .aab format bundles are acceptable.
**So my question and request is: Does Quasar able to generate .aab bunles? If yes how? If no when it will be available?**

**Describe the solution you'd like**
Generating .aab bundle format applications for Google Play.

**Describe alternatives you've considered**
For Instance, using Android Studio we can generate two kinds of apps.
1. Android APKs
2. Android .AAB bundles

**Additional context**
Please, tell me more about this feature request/question. Give explained answer.

**Comment by TobyMosque** [comment]
if u're on cordova, just follow that article:
https://dev.to/tobymosque/quasar-sign-a-apk-while-building-2447

that will be enough to sign u package without any aditional step, but u'll need to append an extra argument (`-- --packageType=bundle`) to generate the aab

```bash
quasar build -m cordova -T android -- --buildConfig="../build.cordova.json" -- --packageType=bundle
```

if u're on capacitor, u need to do that directly in the android studio.

just a remmeber, that isn't an issue, but if u'd more questions like that, u're welcome to start a discussion.

**Comment by gvorster** [comment]
When I do:
```quasar build -m cordova -T android -- --packageType=bundle```

I still get an apk file generated.
`/dev/prj/quasar/android/test2/src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk`

When I do:
```
cd src-cordova  
cordova build android --release -- --packageType=bundle  
//--> /dev/prj/quasar/android/test2/src-cordova/platforms/android/app/build/outputs/bundle/release/app-release.aab
```
Then app-release.aab is generated

```
cordova -v
10.0.0
```

My quasar info:
```
Operating System - Linux(5.8.0-59-generic) - linux/x64
NodeJs - 14.17.0

Global packages
  NPM - 6.14.13
  yarn - 1.22.5
  @quasar/cli - 1.2.1
  @quasar/icongenie - 2.3.3
  cordova - 10.0.0

Important local packages
  quasar - 2.0.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.0.1 -- Quasar Framework local CLI
  @quasar/extras - 1.10.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.1.2 -- The progressive JavaScript framework for buiding modern web UI.
  vue-router - 4.0.10
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.14.6 -- Babel compiler core.
  webpack - 5.41.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.0.0-beta.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
```

UPDATE:
I see in the output of ```quasar build -m cordova -T android -- --packageType=bundle```

```
 Summary for "UI" (only css/js/json)
 ╔════════════╤═══════════╤══════════╗
 ║      Asset │      Size │  Gzipped ║
 ╟────────────┼───────────┼──────────╢
 ║    app.css │   0.00 KB │  0.02 KB ║
 ║ vendor.css │ 183.18 KB │ 33.00 KB ║
 ╟────────────┼───────────┼──────────╢
 ║     403.js │   3.46 KB │  1.38 KB ║
 ║     716.js │   0.72 KB │  0.47 KB ║
 ║     943.js │   6.38 KB │  3.29 KB ║
 ║     app.js │   3.67 KB │  1.84 KB ║
 ║  vendor.js │ 166.18 KB │ 59.16 KB ║
 ╚════════════╧═══════════╧══════════╝
 
 App • Updated Cordova config.xml
 App • Running "cordova build --release android --packageType=bundle"
``` 

It's missing **"-- --packageType=bundle"**

**Comment by ap1969** [comment]
I'm seeing the same thing: the packageType=bundle parameter does not seem to be passed to the cordova build command.

**Comment by ap1969** [comment]
Ah, sorted it. You have to duplicate the "--" :

`quasar build -m android -- -- --packageType=bundle`

**Comment by gvorster** [comment]
> quasar build -m android -- -- --packageType=bundle

Yes! That works!

**Comment by otabekoff** [comment]
@TobyMosque Yeah! It worked perfectly. Thank you. Now, I am closing the issue.

**Comment by janne-rantala** [comment]
It seems that building Capacitor does not work: 

`quasar build -m capacitor -T android -- --packageType=bundle
`
or
`quasar build -m capacitor -T android -- -- --packageType=bundle
`

This produces error:

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :app:assembleRelease from command line.
> Unknown command-line option '--packageType'.


**Anyone got idea how to solve this?**


My `quasar info`:

NodeJs - 14.17.4

Global packages
  NPM - 7.20.3
  yarn - 1.22.4
  @quasar/cli - 1.0.0
  @quasar/icongenie - 2.3.3
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 2.0.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.0.4 -- Quasar Framework local CLI
  @quasar/extras - 1.10.10 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.0.0 -- Official ESLint plugin for Quasar
  vue - 3.1.5 -- The progressive JavaScript framework for buiding modern web UI.
  vue-router - 4.0.10
  vuex - 4.0.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.15.0 -- Babel compiler core.
  webpack - 5.49.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.0.0-beta.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 3.1.2 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 3.1.2 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 3.1.2 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 3.1.2 -- Capacitor: Cross-platform apps with JavaScript and the web`

**Comment by ap1969** [comment]
Does capacitor support AAB? The only thing I can find is an issue from last year saying they don't:

https://github.com/ionic-team/capacitor/issues/2605

Although I'd be surprised if they don't!

**Comment by janne-rantala** [comment]
I managed to solve this by running:

`gradlew :app:bundleRelease`

This will create the app-release.aab to android/app/build/outputs/release/bundle/ folder. Then I signed it with jarsigner.

Good tutorial for this: https://medium.com/androiddevelopers/building-your-first-app-bundle-bbcd228bf631

However, I use Bitrise.io as CI/CD and there I can just switch the apk->aab

**Comment by antbelogurov** [comment]
Hi.
I did it with this command cordova build android --release -- --packageType=bundle
debugg version apk works fine.
in google play console i have this error java.lang.ClassNotFoundException dalvik.system.BaseDexClassLoader.findClass 
![image](https://user-images.githubusercontent.com/63599667/136017161-ba1954f9-221a-4c25-9114-30aece57f1f2.png)

But when I load the application aab into google play it does not open and does not show any errors. What's wrong?

my quasar info
![image](https://user-images.githubusercontent.com/63599667/135985658-bac3d93a-1439-4634-9663-b643cf69b7b6.png)
![image](https://user-images.githubusercontent.com/63599667/135985794-53d83551-5c50-4b9d-b432-08c5d0dd8904.png)

**Comment by mijaelsaban** [comment]
do you know how to sign this app budle (.aab) I tried with zipallign but didnt work

**Comment by omega1996** [comment]
`quasar build -m capacitor -T android -- bundleRelease ` (with space)
Works fine for me, looks like it creates both apk and aab.

**Comment by paulopeloi** [comment]
> do you know how to sign this app budle (.aab) I tried with zipallign but didnt work

up
