### ISSUE TITLE
q-infinite-scroll component can not work together with q-scroll-area component

### ISSUE THREAD

**Issue by baoerapp** [quasarframework/quasar#9632]
The q-infinite-scroll component can not work together with q-scroll-area component,
When i wrap q-infinite-scroll by a q-scroll-area, the @load function of q-infinite-scroll will trigger forever.
But i wrap q-infinite-scroll by a normal div, everything will be ok.

Here is my code:
https://codepen.io/miqipanda/pen/mdWGEjv?editors=1010

**Comment by lyle45** [comment]
@baoerapp not happening to me,

also, try passing true as a first paramter to the done function

**Comment by lukadriel7** [comment]
@baoerapp you need to remove the `scroll-target` props on your infinite scroll to prevent the `@load` event from firing

**Comment by taisha** [comment]
Quasar v1 has the same bug.

**Comment by pdanpdan** [comment]
You are not using the right scroll target
https://codepen.io/pdanpdan/pen/eYrzdJM?editors=1010
