### ISSUE TITLE
Optional replacement of click events with touchstart

### ISSUE THREAD

**Issue by danielfaust** [quasarframework/quasar#9639]
**Is your feature request related to a problem? Please describe.**

A part of an app which I'm creating is a UI for biking. When the phone is attached to the handlebar and the handlebar is shaking, it becomes tricky to push buttons, tabs, sliders or any controls which require relatively precise control. Precise in the sense, that a click is only registered when the pixel distance between touchstart/mousedown and the touchend/mouseup event is not too big.

In this scenario it would be very desirable to replace all click handlers with touchstart handlers, so that a simple touch of the component results in the immediate execution of the click event code, without waiting for a release.

**Describe the solution you'd like**

Have the ability to set/unset a per-element attribute (bool) labeled something like "immediate-execution" which makes touchstart/mousedown events trigger click events immediately.

**Describe alternatives you've considered**

Reassign the event listeners manually via a JavaScript function.

**Comment by rstoenescu** [comment]
Hi,

Directly attaching `@touchstart` handlers instead of `@click` to your interactive elements will solve your problem. There's no reason to add overhead to Quasar...
