### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Zyles** [quasarframework/quasar#964]
### Software version

Quasar: ^0.14.4
OS: Win 10
Node: v6.10.3
NPM: 3.10.10
Browsers: Chrome / Electron

### What did you get as the error?

... \node_modules\quasar-framework…:12844 Uncaught SyntaxError: Unexpected token export
    at createScript (vm.js:74)

Clicking the error in Chrome console brings up this line:

> export { QAjaxBar, QAlert, QAutocomplete, QBtn, QCard, QCardTitle, QCardMain, QCardActions, QCardMedia, QCardSeparator, QCarousel, QChatMessage, QCheckbox, QChip, QChipsInput, QCollapsible, QContextMenu, QDataTable, QDatetime, QDatetimeRange, QInlineDatetime, QFab, QFabAction, QField, QFieldReset, QGallery, QGalleryCarousel, QIcon, QInfiniteScroll, QInnerLoading, QInput, QInputFrame, QKnob, QLayout, QFixedPosition, QSideLink, QItem, QItemSeparator, QItemMain, QItemSide, QItemTile, QItemWrapper, QList, QListHeader, QModal, QModalLayout, QResizeObservable, QScrollObservable, QWindowResizeObservable, QOptionGroup, QPagination, QParallax, QPopover, QProgress, QPullToRefresh, QRadio, QRange, QRating, QScrollArea, QSearch, QSelect, QDialogSelect, QSlideTransition, QSlider, QSpinner, audio as QSpinnerAudio, ball as QSpinnerBall, bars as QSpinnerBars, circles as QSpinnerCircles, comment as QSpinnerComment, cube as QSpinnerCube, dots as QSpinnerDots, facebook as QSpinnerFacebook, gears as QSpinnerGears, grid as QSpinnerGrid, hearts as QSpinnerHearts, hourglass as QSpinnerHourglass, infinity as QSpinnerInfinity, QSpinnerIos, QSpinnerMat, oval as QSpinnerOval, pie as QSpinnerPie, puff as QSpinnerPuff, radio as QSpinnerRadio, rings as QSpinnerRings, tail as QSpinnerTail, QStep, QStepper, QStepperNavigation, QRouteTab, QTab, QTabPane, QTabs, QToggle, QToolbar, QToolbarTitle, QTooltip, QTransition, QTree, QUploader, QVideo, backToTop as BackToTop, goBack as GoBack, move as Move, Ripple, scrollFire as ScrollFire, scroll$1 as Scroll, touchHold as TouchHold, TouchPan, TouchSwipe, addressbarColor as AddressbarColor, Alert, appFullscreen as AppFullscreen, appVisibility$1 as AppVisibility, cookies as Cookies, Events, Platform, LocalStorage, SessionStorage, index as ActionSheet, Dialog, index$1 as Loading, index$2 as Toast, animate, clone, colors, date, debounce, frameDebounce, dom, easing, event, extend, filter, format, noop, openUrl as openURL, scroll, throttle, uid };export default index_esm;

### What were you expecting?

A working page.

### What steps did you take, to get the error?

I have no idea. My app just stopped working. I ctrl+z the last changes I did but I can't get it to work again.

There is no error message in the cmd console, but there is the error message in the chrome console.

What is going on?

**Comment by Zyles** [comment]
Okay this happens when you add the following to package.json "dependencies":

> "fastclick": "^1.0.6",
>     "material-design-icons": "^3.0.1",
>     "moment": "^2.18.1",
>     "quasar-extras": "0.0.8",
>     "quasar-framework": "^0.14.4",
>     "roboto-fontface": "^0.8.0",

Why?

**Comment by rstoenescu** [comment]
@Zyles hi, please redirect this to the electron wrapper repo: https://github.com/quasarframework/electron-wrapper
Thanks!
