### ISSUE TITLE
active-class prop in QRouteTab not working in 2.0.0-beta.19

### ISSUE THREAD

**Issue by dinesh-chander** [quasarframework/quasar#9641]
**Describe the bug**
`active-class` prop in **QRouteTab** not working

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/5a42k8j0/92/

**Expected behavior**
As mentioned in the docs, active-class should behave like `router-link`'s active-class prop.

**Platform (please complete the following information):**
Quasar Version: `2.0.0-beta.19`
@quasar/app Version: `3.0.0-beta.28`
Quasar mode:
  - [X] SPA
  - [x] SSR
 
Tested on:
  - [X] SPA
  - [X] SSR

OS: Windows
Node: 16.3.0
NPM: 7.15.1
Yarn: 1.22.10
Browsers: Chrome

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.0-rc.2
