### ISSUE TITLE
QRouteTab [router-link] - event prop is deprecated and has been removed in Vue Router 4

### ISSUE THREAD

**Issue by ttquoccuong** [quasarframework/quasar#9642]
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/practical-curran-emwke?file=/src/layouts/MainLayout.vue

**To Reproduce**
1. Create new Quasar App
2. Add a QTabs with QRouteTab
3.The Warning of VueRouter appear in console

**Screenshots**
<img width="676" alt="Screen Shot 2021-06-11 at 00 13 32" src="https://user-images.githubusercontent.com/7381858/121568399-ddf24e80-ca49-11eb-905b-53fd8ed1c2ad.png">

**Platform (please complete the following information):**
Quasar Version: "^1.15.20",
@quasar/app Version: "^2.2.10",
Quasar mode:

  - [x] SPA

Tested on:
  - [x] SPA

**Comment by MilosPaunovic** [comment]
Hello @ttquoccuong,

You are right, `event` prop is deprecated in `Vue Router 4`, as well as `tag` and `addRoutes()`, as it states in the official [changelog](https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md#351-2021-01-26) and on the [documentation](https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link) for `router-next`.

But, the thing is that  Quasar`v1` currently uses `"vue-router": "3.5.1"`, so those props and methods aren't deprecated in it.

Quasar `v2` will utilise `"vue-router": "4.0.8"` from the start, so you don't have to worry about that, and if the router version gets updated to 4+ in this version of Quasar, be sure it will be implemented in the proper way.

**Comment by MilosPaunovic** [comment]
@ttquoccuong Could we close this issue if the above answers your questions?

**Comment by ttquoccuong** [comment]
@MilosPaunovic yes, i know that.
one more thing, I think we should have a new label `Warning` which mean no bugs. I spend little minus to find it :)
