### ISSUE TITLE
QImg: img-class not working

### ISSUE THREAD

**Issue by 13uraksahin** [quasarframework/quasar#9644]
**Describe the bug**
Images are not aware if have a user-defined class. **img-class** prop does not work properly on QImg on Quasar v2

**Codepen/jsFiddle/Codesandbox (required)**
Self-explanatory & easy bug

**To Reproduce**
Self-explanatory

**Expected behavior**
Images must have user-defined classes in the compiled HTML

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-rc.2
