### ISSUE TITLE
plugins dialog ok option cannot be set to object 

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar#9650]
ok option cannot be set to OBJECT 

https://codesandbox.io/s/strange-black-viykp?file=/src/App.vue

It works fine when I build the project using QUASAR-CLI,
But when I used [storybook](https://storybook.js.org/) to write documents for it, I got an error

**Comment by rstoenescu** [comment]
Hi,

You're supplying an invalid value to the "lang" prop. It's not a string.

Should be:

```
import quasarLang from 'quasar/lang/zh-CN'
// ...
lang: quasarLang
```
