### ISSUE TITLE
Logo in header extends into screen

### ISSUE THREAD

**Issue by enpasos** [quasarframework/quasar#9659]
Quasar v2.0.0-rc.2

On mobile 
Galaxy S21 Ultra, Android 11, Samsung Internet Browser

the Quasar logo extends into the main screen as the following screenshot illustrates

![grafik](https://user-images.githubusercontent.com/9622808/121795644-f6619500-cc12-11eb-9f7f-c063f81b2586.png)

**Comment by hawkeye64** [comment]
I just check with the same device and Samsung Internat Browser. This is indeed an issue with next.quasar.dev, but is not an issue with logo on quasar.dev.

**Comment by andreiTn** [comment]
Sorry for the noise, I was trying something new.

Setting the logo width to 100% fixes the issue.

**Comment by rstoenescu** [comment]
Thanks for reporting and for PRing.
Fix for docs will be available on next docs deployment.
