### ISSUE TITLE
[Request] More responsive images

### ISSUE THREAD

**Issue by ram-you** [quasarframework/quasar#966]
Hi,
as mentioned in W3C HTML 5 specification, any plans for using  **srcset** and **sizes** properties in **Image Gallery**, **Image Gallery Carousel** and **Parallax**

W3C HTML 5 specifications for using  **srcset**
http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset

Thanks

**Comment by rstoenescu** [comment]
Will do. Thanks for the suggestions!

**Comment by rstoenescu** [comment]
Duplicate of https://github.com/quasarframework/quasar/issues/777
