### ISSUE TITLE
Update to vue 3.1

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/quasar#9660]
**Is your feature request related to a problem? Please describe.**
I use vue apollo with typescript. When using it with quasar V2, an error about onServerPrefetch is always thrown 

**Describe the solution you'd like**
OnServerPrefetch was added in vue 3.1. Updating the vue version of quasar to 3.1 should fix it

**Comment by rstoenescu** [comment]
Hi,

No need to request the update of Vue. This goes without saying. We are heavily testing it at the moment. Expect a release of q/app with it next week.
