### ISSUE TITLE
[Request] Add QImageInput or 'image' type to QInput

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#967]
Currently it seems on **Quasar** there is no native support for a modern, clean and beautiful input field for images.

There is **QUploader** but it requires a server integration. Instead, we could support a client-only image input which encode the image data with _base64_ in order to handle it as a _Data URI:_

https://en.wikipedia.org/wiki/Data_URI_scheme

I've blogged about that here (with example of implementation and references):

https://zuck.github.io/better-html5-image-input/

**NOTE:** file input should receive some care too...

**Comment by rstoenescu** [comment]
Native inputs with type="image" do not work as you imagined. They don't have any "value" prop and are not used for uploading or storing images. They're simply used to create graphical submit buttons. Nothing is hindering you on using the native input in this way:

```html
<input id="image" type="image" alt="Login"
  src="https://raw.githubusercontent.com/mdn/learning-area/master/html/forms/image-type-example/login.png">
```

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/image
