### ISSUE TITLE
A "highlight" feature/plugin would be very helpful

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#9670]
I have a screen that allows users to flip the mode of operation on a specific function.  When this happens, some items' functionality changes.  I display a notification message when this happens using the notify function, but it would be really nice to be able to visually flag the individual affected items temporarily with a ripple, grow/shrink, color change or something similar.  Anything to draw their attention temporarily so they know to which elements I am referring.  

Here's what I mean:  hhttps://www.screencast.com/t/RxmfULPNC

**Comment by hawkeye64** [comment]
Why not add a css class that does this, then when notification ends, remove the css class?

**Comment by Daemach** [comment]
I was hoping for something more elegant and animated - flash red, fade back to white, or something like that.  And as I would use this in a number of places, something that could be configured once and reused, like notify, would be very helpful.

**Comment by rstoenescu** [comment]
Hi,

The kind of interaction that you require is not meant to be embedded into the framework. It is way too custom due to the page template that can be anything... The only way to do it is like Jeff indicated above.
