### ISSUE TITLE
package dependencies error (after quasar upgrade to v3.0.0-rc2)

### ISSUE THREAD

**Issue by greenn-lab** [quasarframework/quasar#9673]
Quasar Version: "quasar": "^2.0.0-rc.2"
@quasar/app Version: "@quasar/app": "^3.0.0-rc.2"
Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS Bigsur , Windows 10
Node: v16.0.0
NPM: 7.16.0
Yarn: 1.22.10

## run `quasar dev` 
below the error log.
```
D:\...\client\node_modules\vue-loader\dist\index.js:8
    throw new Error('vue-loader requires @vue/compiler-sfc to be present in the dependency ' +
          ^

[  Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.

  - index.js:8 Object.<anonymous>
    [client]/[vue-loader]/dist/index.js:8:11

  - loader:1108 Module._compile
    node:internal/modules/cjs/loader:1108:14

  - loader:1137 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1137:10

  - loader:988 Module.load
    node:internal/modules/cjs/loader:988:32

  - loader:828 Function.Module._load
    node:internal/modules/cjs/loader:828:14

  - loader:1012 Module.require
    node:internal/modules/cjs/loader:1012:19

  - helpers:93 require
    node:internal/modules/cjs/helpers:93:18

  - create-chain.js:5 Object.<anonymous>
    [client]/[@quasar]/app/lib/webpack/create-chain.js:5:29

  - loader:1108 Module._compile
    node:internal/modules/cjs/loader:1108:14

  - loader:1137 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1137:10

]
```
> add @vue/compiler-sfc dependency
> execute command `yarn add --dev  @vue/compiler-sfc` then boot success.

## open in browser
occurred error below
```
vue-router.esm-bundler.js?ece6:2332 

Uncaught (in promise) TypeError: Cannot read property 'parent' of null
    at warnDeprecatedUsage (vue-router.esm-bundler.js?ece6:2332)
    at setup (vue-router.esm-bundler.js?ece6:2238)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:154)
    at setupStatefulComponent (runtime-core.esm-bundler.js?9e79:7118)
    at setupComponent (runtime-core.esm-bundler.js?9e79:7074)
    at mountComponent (runtime-core.esm-bundler.js?9e79:5079)
    at processComponent (runtime-core.esm-bundler.js?9e79:5054)
    at patch (runtime-core.esm-bundler.js?9e79:4660)
    at mountChildren (runtime-core.esm-bundler.js?9e79:4844)
    at processFragment (runtime-core.esm-bundler.js?9e79:5013)
```
> execute `yarn add vue-router@4`
> after reboot success, without error

I thought you might know about that, but I wanted to let you know.

Always thanks your service :)

**Comment by rstoenescu** [comment]
Don't manually install vue-router yourself. The `Cannot read property 'parent' of null` is a message coming from Vue where HMR failed.

Yarn (or NPM) did not successfully installed deps correctly the first time, which is why you got the message. Deleting node_modules and yarn.lock/package-lock.json and installing again should fix it.

**Comment by greenn-lab** [comment]
Wow, sooooo great 👍 
Thank you for you advice. I resolved this problem by your advice.

I did:
`rm yarn.lock` and `yarn` ... after I saw magic from you!
