### ISSUE TITLE
quasar upgrade beta to rc VueX not found

### ISSUE THREAD

**Issue by franfrLor** [quasarframework/quasar#9676]
When i upgrade quasar beta  2.0.0-beta.17 to rc 2.0.0-rc.2 (and app 3.0.0.-beta.24 to 3.0.0-rc.2) i have this error :
App •  ERROR  •  UI  in ./src/store/index.ts

Module not found: Can't resolve imported dependency "vuex"
Did you forget to install it? You can run: npm install --save vuex

**Comment by MilosPaunovic** [comment]
@franfrLor In the [v3.0.0-rc.1](https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v3.0.0-rc.1) release a breaking change has been introduced:

> Not supplying "vuex" package anymore. If using a store, please yarn add vuex@4 / npm install vuex@4.
This makes sense because decoupling Vuex will allow developers to upgrade to the future Vuex 5 without us making any breaking changes.

**Comment by franfrLor** [comment]
Oh sorry thank you very much
