### ISSUE TITLE
Add "type" and "href" to clickable list item

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#9684]
I need to export a spreadsheet from a server via a split button.  It would be very useful to have an href param in addition to the "to" router link function so I can launch it directly/elegantly.  I am still on Q1 until Q2 is fully released but intend to upgrade soon.

**Comment by Daemach** [comment]
Apparently split button doesn't have an href param either for the main click.  It would be nice if both of these could be addressed.  I guess I'll try a button group, but it's going to take up a lot of room :/

**Comment by MilosPaunovic** [comment]
@Daemach `VueRouter` does not condone hard-coded `href`s, as it states in this part of their documentation: 

https://router.vuejs.org/api/#router-link

So I don't really see this as a new Quasar feature, because it follows only the best coding practices.

If you try to explain you problem a bit more (and possibly include a code snippet or codepen exapmle), I could help you find a more elegant solution.

**Comment by Daemach** [comment]
Yes of course.  The simplest way to explain this is that q-btn has both "type" and "href" params that let the button function like a standard link.

![image](https://user-images.githubusercontent.com/12553953/122245573-b0a70580-ce7a-11eb-92a6-0bbd0eaceabe.png)


The button dropdown and list items do not, though they, and q-btn, have "to" attributes that work with vue-router.  One would expect that if one can use the button dropdown and list items to navigate to a vue-router link, an external link should work too, as it does with q-btn.  Consistency more than anything.

That being said, it turns out there is an "externalURL" utility that might work around this problem for me.

**Comment by MilosPaunovic** [comment]
Hello @Daemach,

`QBtnDropdown` has a type prop as well as regular `QBtn`, which, if you set it to be anchor `a` will behave like a link and can be used to redirect user on external page or trigger download from external server.

```html
<q-btn-dropdown
  split
  label="Button"
  type="a"
  href="http://www.google.com"
  target="_blank"
>
  <!-- Dropdown content -->
</q-btn-dropdown>
```

Does this help you?

**Comment by Daemach** [comment]
Thanks.  I must have missed that in q-btn-dropdown, but if the list items don't support it I'm still out of luck.  I need to be able to launch the external page from either the button (which would contain query params for the default action) or from items within the list.  While I could probably embed a standard link, it's not elegant or consistent, since a list item can link to a vue route.

**Comment by rstoenescu** [comment]
This should have been closed. Implemented already (both Qv1 and Qv2)
