### ISSUE TITLE
QuasarIconSet type in quasar/dist/types/extras/icon-set does not match type of ui/icon-set/* objects

### ISSUE THREAD

**Issue by Lyokolux** [quasarframework/quasar#9688]
**Describe the bug**
The type `QuasarIconSet` present in `quasar/dist/types/extras/icon-set` does not match the objects in `ui/icon-set/fontawesome-v5-pro.js`.

I can be wrong, but then where is the type for the `ui/icon-set/fontawesome-v5-pro.js` object (and other objects in `ui/icon-set/*`)?

**To Reproduce**
1. Copy the object `ui/icon-set/fontawesome-v5-pro.js` into a `fontawesome-v5-pro.ts`
2. Adjust the values to your needs and add the type `QuasarIconSet` from 'quasar/dist/types/extras/icon-set'; to this object.
3. See some type errors such as properties `carousel.up` and `carousel.down` that should not exist.

**Expected behavior**
Setting the type `QuasarIconSet` to the object should be ok ? Or is it another type than `QuasarIconSet` ?

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version: 2.0.0-beta.12
Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available in Quasar v2.0.0-rc.3 and Quasar v1.15.21
