### ISSUE TITLE
Electron app not quitting

### ISSUE THREAD

**Issue by JoseCadenas** [quasarframework/quasar#9701]
Hello Everyone,

**Issue**
When I shut down the app from terminal the Electron app does not close, it stays open and requires that I force quit it. If i close the Electron app from the window controls then shut down Quasar/Electron hot reloads from the terminal it works fine. I unfortunately don't have steps to reproduce this issue but i think its vague enough that I may still be able to get help, if not I'll close the issue.

**Screenshot**
<img width="1280" alt="Screen Shot 2021-06-16 at 3 08 01 PM" src="https://user-images.githubusercontent.com/50152606/122300860-c46f5d80-ceb4-11eb-8cfe-682665f0d45d.png">

**Expected behavior**
Control+C in Terminal to shut down Electron completely

**Platform (please complete the following information):**
Quasar Version: 2.0.0-rc.3 (20 Days ago: ^2.0.0-beta.12)
@quasar/app Version: 3.0.0-rc.3 (20 Days ago: ^3.0.0-beta.22)
Quasar mode:  Electron

OS: MacOS Big Sur v11.4
Node: v14.16.1
NPM: v6.14.12
Electron: v13.1.2

**Comment by rstoenescu** [comment]
Hi,

Tried to reproduce it, but couldn't. Can you please supply a reproducible repo so I can play with it?
Thanks.

**Comment by JoseCadenas** [comment]
@rstoenescu  I appreciate you taking a look, I'm working on a private project so if I'm able to pinpoint the cause of my issue or reproduce on a Quasar template I'll reopen this post with said details.
