### ISSUE TITLE
adjustDate and buildDate can produce wrong result with input not in specific order

### ISSUE THREAD

**Issue by Carko** [quasarframework/quasar#9704]
**Describe the bug**
adjustDate and buildDate (and possibly others) take an object literal that specifies the components and their values of date/time to set.

However, due to the implementation of the adjustDate, the keys in the object literal are order sensitive, which should not be the case.

The date/time components are set in the order they are provided and not in the order that would produce the correct result every time.

For example, if you provide the following object literal to the buildDate function: `{ month: 2, day: 29, year: 2020 }`, it will:
* create the Date object with the current date (and year 2021)
* set the month to 2
* set the day to 29 (which will **not** work as there is no 29th of Feb in 2021)
* set the year to 2020. 
The result will be the **1st of March 2020** instead of the requested 29th of Feb 2020.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/9h7v5p8g/

**To Reproduce**
1. be in the month with 30 days (such as June)
2. use the `buildDate({date: 31, month: 7})` function
3. you get the date of the 1st of July instead of 31st of July
4. use the `buildDate({month: 7, date: 31})` function instead
5. observe correct result

**Platform (please complete the following information):**
Quasar Version: 2

OS: All
Browsers: All

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.2.1
