### ISSUE TITLE
icongenie generate goes error

### ISSUE THREAD

**Issue by mclubing** [quasarframework/quasar#9727]
I'm not sure if this is a problem with my use or with the command itself. Please Help.
 icongenie generate -m cordova -i icon.png -b starting-bg.png

/usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/lib/constructor.js:32
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/lib/constructor.js
- /usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/lib/index.js
- /usr/local/lib/node_modules/@quasar/icongenie/lib/utils/get-files-options.js
- /usr/local/lib/node_modules/@quasar/icongenie/lib/cmd/generate.js
- /usr/local/lib/node_modules/@quasar/icongenie/bin/icongenie-generate
- /usr/local/lib/node_modules/@quasar/icongenie/bin/icongenie

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/lib/constructor.js:32:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@quasar/icongenie/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**To Reproduce**
1. npm install --ignore-scripts=false --verbose sharp  still got error like above
2. Remove the "node_modules/sharp" reinstall sharp, got error like above

icongenie -v
2.4.0
npm view sharp version
0.28.3

**Platform (please complete the following information):**
Quasar Version: 2.2.8
@quasar/app Version: 
Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ √] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ √] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: catalina 10.15.7 
Node: v14.16.1
NPM: 6.14.12
Yarn:
Browsers:Chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Cannot reproduce it, but I'm on macOS Big Sur.
Can you please globally uninstall IconGenie then reinstall it? Might solve the issue.

**Comment by mclubing** [comment]
> Cannot reproduce it, but I'm on macOS Big Sur.
> Can you please globally uninstall IconGenie then reinstall it? Might solve the issue.

Reinstalling IconGenie worked. You are very helpful to me. Thank u very much!
