### ISSUE TITLE
Vue 3 side-effect !!!

### ISSUE THREAD

**Issue by andrey-hilux** [quasarframework/quasar#9732]
[Vue 3 - number 0 increase (++) is not 1 but 101 in template , why?](https://stackoverflow.com/questions/65689261/vue-3-number-0-increase-is-not-1-but-101-in-template-why)
There someone to explain this?!!!

**Comment by rstoenescu** [comment]
This has nothing to do with Quasar.

**Comment by rstoenescu** [comment]
Please use the appropriate channels (Vue forums, GH, etc).
