### ISSUE TITLE
QToggle is not working!

### ISSUE THREAD

**Issue by otabekoff** [quasarframework/quasar#9740]
**Describe the bug**
**QToggle component style is too bad. It is broken! Look at the below pictures and information for more info!**

Operating System - Windows_NT(10.0.19042) - win32/x64
NodeJs - 14.15.3

Global packages
  NPM - 6.14.9
  yarn - 1.22.10
  @quasar/cli - 1.2.0
  @quasar/icongenie - 2.3.3
  cordova - 10.0.0

Important local packages
  quasar - 1.15.21 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.2.10 -- Quasar Framework local CLI
  @quasar/extras - 1.10.7 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.14 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.5.1 -- Official router for Vue.js 2
  vuex - 3.6.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.14.3 -- Babel compiler core.
  webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. 
json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Otabek
  vEthernet (Default Switch) - 172.27.16.1
  WiFi - 192.168.43.104

**Codepen/jsFiddle/Codesandbox (required)**
No codepen available

**To Reproduce**
1. Create a new project
2. Open /pages/index.vue
3. Go Quasar docs: https://quasar.dev/vue-components/list-and-list-items#example--settings
4. Copy the settings example into /pages/index.vue
5. And look at the toggle its style is too bad.

**Expected behavior**
![image](https://user-images.githubusercontent.com/60849894/122658871-91b2b700-d18b-11eb-908b-5791c5a00c54.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/60849894/122658879-a000d300-d18b-11eb-8c90-4eab28317996.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [x] SPA
  - [x] PWA
  - [x] Electron
  - [x] Cordova

Tested on:
  - [x] SPA
  - [x] PWA
  - [x] Electron
  - [x] Cordova

OS: Windows_NT(10.0.19042) - win32/x64
Node: 14.15.3
NPM: 6.14.9
Yarn:  1.22.10
Browsers: Chrome, MSEdge, Firefox
iOS:
Android: Samsung Internet, Chrome, App version(WebView)
Electron: On the same computer

**Additional context**
I've just created project add the example for testing and get the problem!

**Comment by rstoenescu** [comment]
Hi,

This cannot be reproduced... Can you offer a reproduction repo pls?

**Comment by otabekoff** [comment]
@rstoenescu OK, this is the repo: https://github.com/otabekoff/arabuz-shifohiyya
After running `quasar dev` you can go to **http://localhost:8080/sozlamalar** and check it!

**Comment by otabekoff** [comment]
_OK, Now I am closing this issue._ I found the error. When I set font-size of all my div elements to 16px, all quasar components are becoming unresponsive and not behaving normal! The problem was: `div { font-size: 16px }` in my app.scss. Now, I change that **div** selector to **body** as `body { font-size: 16px }`.
Please, apologize me for not checking deeply! I will try not to do so, the next time.
