### ISSUE TITLE
devServer.public uses incorrect 'port' in wss connection

### ISSUE THREAD

**Issue by Richie765** [quasarframework/quasar#9750]
**Describe the bug**
When `devServer.public` is set, the wss connection will connect to that url on `devServer.port` but the reverse proxy is on  default port 443.

**To Reproduce**
* Create a new project
* Setup a reverse https proxy that points to the project at port 8080
* Modify quasar.conf.js as below
* Go to https://myapp.domain
* Page loads correctly
* Look in console output
* Error: WebSocket connection to 'wss://myapp.domain:8080/ws' failed 

```
    devServer: {
      public: 'https://myapp.domain',
      https: false,
      port: 8080,
      open: false // opens browser window automatically
    },
```

**Expected behavior**

**Screenshots**
It should connect to `wss://myapp.domain/ws`

**Platform (please complete the following information):**
Quasar Version: v2.0.0
@quasar/app Version: v3.0.0

Quasar mode:
  - [X] SPA

Tested on:
  - [X] SPA

OS:
Node: v14.16.0
NPM: 6.14.11

**Additional context**
It worked with:

Quasar 1.15.21
@quasar/app - 2.2.10

I'm using the following work-around:
```bash
socat TCP-LISTEN:8080,fork TCP:myapp.domain:443
```

**Comment by maggie44** [comment]
Related to https://github.com/quasarframework/quasar/issues/9466 ?

**Comment by rstoenescu** [comment]
Please report this to [webpack-dev-server](https://github.com/webpack/webpack-dev-server) and mention version 4.0.0-beta.3
