### ISSUE TITLE
electron doesn't install vue devtools

### ISSUE THREAD

**Issue by fprijate** [quasarframework/quasar#9757]
In V2 there is no installation of vue_ devtools.
In V2 missing code from V1 ,electron-main.dev.js :

import installExtension, { VUEJS3_DEVTOOLS } from 'electron-devtools-installer';
import { app, BrowserWindow } from 'electron';

app.whenReady().then(() => {
  // allow for a small delay for mainWindow to be created
  setTimeout(() => {
    // Install `electron-debug` with `devtron`
    electronDebug({ showDevTools: false });

    // Install vuejs devtools
    installExtension(VUEJS3_DEVTOOLS)
      .then((name) => {
        console.log(`Added Extension: ${name}`);
.....

**Comment by rstoenescu** [comment]
Hi,

This is not a bug. It now needs to be installed manually.
