### ISSUE TITLE
Authentication boot file

### ISSUE THREAD

**Issue by tonysnowboardunderthebridge** [quasarframework/quasar#9759]
Good morning, 

I suggest to update https://quasar.dev/quasar-cli/boot-files#router-authentication

with: 

1. the import on top import { boot } from 'quasar/wrappers'
2. Specify that without the import of the boot, the application doesn't use the logic for authentication on live environment.

I hit this problem this morning, application deployed on amazon S3, and without the boot wrapper, a refresh skip the logic on that file.  

Kind Regards
Antonio

**Comment by hawkeye64** [comment]
@tonysnowboardunderthebridge That doesn't make sense. Here is the code for boot:
```js
// Functions in this file are no-op,
//  they just take a callback function and return it
// They're used to apply typings to the callback
//  parameters and return value when using Quasar with TypeScript
// We need these in `ui` folder to make `quasar/wrapper` import work,
//  but they are useful only for Quasar CLI projects
// They are typed via module augmentation by `@quasar/app`

module.exports.boot = function (callback) {
  return callback
}
```
It's basically a no-op, but necessary for Typescript users.

**Comment by tonysnowboardunderthebridge** [comment]
@hawkeye64 you're right, tested on local application and the application deployed on amazon s3....
 
I'm wondering if the problem that I hit was caused by file named _router-authentication.js_ that I renamed _authentication.js_
Is there a convention on the name of the boot file, like avoiding dash?

Regards
Antonio

**Comment by hawkeye64** [comment]
@tonysnowboardunderthebridge No, that's not an issue, as long as you use the same file name in the boot section of quasar.conf.js
