### ISSUE TITLE
QTooltip triggers event error when unloaded?

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#976]
### Software version

Quasar: 0.14
OS: Win 10 Pro 64-bit
Node:
NPM:
Browsers: Vivaldi 1.13.971.8 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'removeEventListener' of undefined"

### What were you expecting?
No error :)

### What steps did you take, to get the error?
In the template, I'm defining this section of markup:
```
        <div>
          <span :class="{'not-visible': !is('visible')}">
          <q-icon name="fa-info-circle">
            <q-tooltip>
              {{page.explanation}}
            </q-tooltip>
          </q-icon>
          {{page.heading}}
          </span>
        </div>
```
All is fine until I navigate away from that page and back again. Then I get the error in the browser console. The component is unloaded in between (i.e. it's based on a router-view which navigates to a different component). The q-tooltip does still work, even on the 'reloaded' page. The order is:
1. browse to /eventID/pageID: all is fine, q-tooltip works in Page component
2. browse to /eventID: no error, Event component renders content
3. browse to /eventID/pageID: `error in beforeDestroy hook`

**Comment by rstoenescu** [comment]
Any chance I can take a look at your repo? It would help investigating.

**Comment by dsl101** [comment]
Actually, it's not on github I'm afraid. I will try to make a minimal test case

**Comment by dsl101** [comment]
Well, that was annoying. I couldn't make a repro case, so I just updated my main project, and the following things were upgraded:

+ express@4.16.1
+ vuex@2.4.1
+ firebaseui@2.4.0
+ quasar-framework@0.14.5
+ firebase@4.5.0

And now the error is no more. Woohoo!.

**Comment by dsl101** [comment]
OK, for some reason, this problem is back (I suspect it never really went away, and I just failed with the testing :). Anyway, the following simple App.vue below shows it happening on ios. I'm on Quasar 0.14.7 at the moment.
```
<template>
  <q-layout ref="layout" view="lHr lpr lFr">
    <q-toolbar slot="header">
      <q-btn flat @click="$refs.layout.toggleLeft()">
        <q-icon name="menu" />
      </q-btn>
      <q-toolbar-title>KI App</q-toolbar-title>
    </q-toolbar>

    <div slot="left">
      <q-toolbar>

        <q-btn flat @click="$refs.layout.hideLeft()">
          <q-icon name="close" />
          <q-tooltip>
            Close
          </q-tooltip>
        </q-btn>

      </q-toolbar>
    </div>
    <router-view />
  </q-layout>

</template>
```

**Comment by dsl101** [comment]
Aargh! Sorry, wrong ticket. I'll move this elsewhere...
