### ISSUE TITLE
QV2 - With Apollo  and Vue 3

### ISSUE THREAD

**Issue by Klerith** [quasarframework/quasar#9762]
I have been using Quasar v1 with no issues, now I'm moving to Quasar v2 with Vue 3.

This is not related to Quasar, but in Qv1, I was using this line inside a function that I trigger from the quasar.config.js like this:

boot: ['XXX', 'apollo', 'XXXX', 'XXXX'],

Then, at some point, I call this
Vue.use(VueApollo)

Now, Vue 3 does not expose the Vue object, do you have an idea or workaround to be able to set $apollo inside the vue object?
Right now, I'm calling the queries like this:

vue.$apollo.query
But vue.$apollo is undefined

Thank you

**Comment by Klerith** [comment]
After a whole day of migrating everything to Quasar v2, I manage to fix this issue.

In order to call 
```
vue.$apollo.query
```

We need to set the global property, before Vue 2, I was doing. 
```
Vue.use( VueApollo )
```

But now, I'm using the boot sequence of Quasar to configure the global $apollo property.
```
 app.config.globalProperties.$apollo = apolloClient
```

Where the __apolloClient__ is already instantiated
```
    const apolloClient = new ApolloClient({
        link: authLink.concat( httpLink ),
        cache: new InMemoryCache(),
        connectToDevTools: true,
    })
```

**Comment by MilosPaunovic** [comment]
@Klerith Sometimes a good night's sleep solves a lot of our problems :smile:
