### ISSUE TITLE
QField to always use a given error slot

### ISSUE THREAD

**Issue by NoBrainSkull** [quasarframework/quasar#9763]
Hi there,

**Is your feature request related to a problem? Please describe.**
I was upgrading a QSelect component we have in one of our projects and couldn't get the error slot to be overridden (had bottom-props enabled). Looking at [the source code responsible of the error slot rendering](https://github.com/quasarframework/quasar/blob/78df1f4939936fdbf591d90addf950a8f42e665b/ui/src/composables/private/use-field.js#L476), I saw that if using `rules` on the field, the error slot would'nt be used at all so that you must validate the input yourself. I'm very happy with how the `rules` are computing the error message though, I just wish I could template it differently (in a QTooltip for instance)

**Describe the solution you'd like**
I thought that maybe we could always use the error slot if provided, and give it the `computedErrorMessage` as a slot prop induced by `rules` ?

I'd love to contribute with a PR if this seems relevant to the maintainers team

**Comment by hawkeye64** [comment]
It seems to me that this would cause a conflict leading to confusion for users on which one to use.
I don't see any practicality in it so closing this issue. Feel free to open if you disagree and can have a valid argument that won't make the usage confusing for users.

**Comment by NoBrainSkull** [comment]
I'm not sure I've been clear since english isn't my mother tongue but to clarify : as a user I've been confused because I had to choose between using `rules` and overriding the `error slot` because their usage are conflicting (if I'm not mistaken). My point was precisely to stop having to make a choice by merging the usages.

**Comment by szwjonks** [comment]
Hello
Is it possible to include this feature in Qasar 2.X?

I have case, where internal validation works fine and return right error message, but sometimes I need render this message as HTML, so error slot as scoped slot with access to internal error message would be nice.
