### ISSUE TITLE
TypeError: router.currentRoute.value.matched.flatMap is not a function

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#9764]
**Describe the bug**
I get the following error when running the production app with SSR:
```
TypeError: router.currentRoute.value.matched.flatMap is not a function
at router.isReady.then (render-app.js:7153:65)
```

Which is code that I can only find in `quasar.server-manifest.json`. It seems to me this currentRoute property at this point might not be a proxy so accessing it's value will be undefined.

I have not been able to reproduce this locally yet, I only get it in my production app in Azure.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version: 3

Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by hawkeye64** [comment]
@Evertvdw Look at your routes and make sure they are all good. I am not an SSR expert, but I would also raise the issue with the vue-router repo and see what they say.

**Comment by Evertvdw** [comment]
It seems this issue fixed itself, maybe something cache related. I changed nothing and it started working after some time. I will close this issue.

**Comment by hawkeye64** [comment]
Yes, sometimes deleting node_modules and the associated lock file will also do that.

**Comment by Evertvdw** [comment]
@hawkeye64 I think I found the issue. I was running quasar v2 on Node v10. That version of node probably does not have that specific javascript feature. When moving to Node v14 the issue is gone :)
