### ISSUE TITLE
https://roadmap.quasar.dev redirects to the vue3-work branch

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar#9777]
I noticed the button here: https://quasar.dev/start/roadmap

links to: https://roadmap.quasar.dev

and ends up here: https://github.com/quasarframework/quasar/blob/vue3-work/ROADMAP.md

**Comment by Lapinskas** [comment]
And https://github.com/quasarframework/quasar/blob/vue3-work/ROADMAP.md page, in its turn, gives 404

**Comment by rstoenescu** [comment]
Thanks for reporting. Fixed the redirect.

**Comment by rstoenescu** [comment]
For completeness, here's the good redirect link: https://github.com/quasarframework/quasar/blob/dev/ROADMAP.md
