### ISSUE TITLE
"Module not found:" compilation error for modules (stream, http, https, constants, zlib_bindings)

### ISSUE THREAD

**Issue by yeus** [quasarframework/quasar#9780]
**Describe the bug**
I wanted to make use of an npm package "ccxt". When importing it in a component/module or anywhere in the project I get the following errors:

**Codepen/jsFiddle/Codesandbox (required)**
- not sure if this is possible with an error relaed to webpack5 and 3rd party library.

**To Reproduce**
1. initialize project
```
  quasar create my_new_app
  yarn add ccxt
```
2. add `import 'ccxt'` or `var ccxt = require ('ccxt')` to any javascript/vue file
3. `quasar dev`
4. See error:

```
quasar dev

 Dev mode.......... spa
 Pkg quasar........ v2.0.0
 Pkg @quasar/app... v3.0.0
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 87.60% of global marketshare):
 · Chrome for Android >= 91
 · Firefox for Android >= 89
 · Android >= 91
 · Chrome >= 81
 · Edge >= 88
 · Firefox >= 80
 · iOS >= 11.0-11.2
 · Opera >= 72
 · Safari >= 11.1


 App • ⚠️  ️️Setting port to closest one available: 8081

 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 10403ms



 App •  ERROR  •  UI  in ./node_modules/ccxt/js/static_dependencies/node-fetch/index.js

Module not found: Can't resolve imported dependency "stream"
Did you forget to install it? You can run: yarn add stream

 App •  ERROR  •  UI  in ./node_modules/ccxt/js/static_dependencies/node-fetch/index.js

Module not found: Can't resolve imported dependency "http"
Did you forget to install it? You can run: yarn add http

 App •  ERROR  •  UI  in ./node_modules/ccxt/js/static_dependencies/node-fetch/index.js

Module not found: Can't resolve imported dependency "https"
Did you forget to install it? You can run: yarn add https

 App •  ERROR  •  UI  in ./node_modules/ccxt/js/static_dependencies/node-rsa/schemes/pkcs1.js

Module not found: Can't resolve imported dependency "constants"
Did you forget to install it? You can run: yarn add constants

 App •  ERROR  •  UI  in ./node_modules/zlib/lib/zlib.js

Module not found: Can't resolve imported dependency "./zlib_bindings"


 App •  COMPILATION FAILED  • Please check the log above for details.

Issues checking in progress...
No issues found.

```

**Expected behavior**
App should compile, 

**Platform (please complete the following information):**
Quasar Version: 
@quasar/app Version: v2.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04
Node: v14.17.1
NPM: 6.14.13
Yarn: 1.22.5

**Additional context**

I think this is a quasar/webpack5 issue, as there are other projects which can make use of
ccxt through yarn/npm + vue. I successfully compiled this one here for example:

https://github.com/MoiOcanas/vue-ccxt

I suspect its something in the webpack configuration. Here are some possibly related issues

https://github.com/ethers-io/ethers.js/issues/998
https://jahed.dev/2021/02/06/upgrading-to-webpack-5/

The last one sounds like it has something to do with webpack v4 automatic polyfills?

I am not an expert on this. But any help on how to configure quasar/webpack5 in order to get rid of the above errors
would be appreciated!

**Comment by rstoenescu** [comment]
This is due to Webpack 5 not shipping with nodejs polyfills anymore.
Explanation is found on the upgrade guide (along with a solution): https://quasar.dev/start/upgrade-guide#nodejs-polyfills

**Comment by yeus** [comment]
@rstoenescu thank you so much for the superfast reply..  will try this.

**Comment by yeus** [comment]
thank your @rstoenescu this already helped a lot. unfortunately, one error still remains:

```
 App •  ERROR  •  UI  in ./node_modules/zlib/lib/zlib.js

Module not found: Can't resolve imported dependency "./zlib_bindings"
```

a related issue might be this one here:

https://github.com/mtth/avsc/issues/199

any idea how to solve this? and add for example "browserify-zlib" to replace zlib dependencies? I think that would probabyl solve the error...

**Comment by hawkeye64** [comment]
You may have to try this one: https://github.com/browserify/browserify-zlib

**Comment by yeus** [comment]
@hawkeye64 thx, that helped, finally got it compiling. FOr those who have a similar problem, I had to extend
the chainWebPack in quasar.conf.js like this:

      chainWebpack (chain) {
        // this is in order to support the not-updated version of ccxt:
        // also needs: 
        //    yarn add --dev node-polyfill-webpack-plugin browserify-zlib
        const nodePolyfillWebpackPlugin = require('node-polyfill-webpack-plugin')
        chain.plugin('node-polyfill').use(nodePolyfillWebpackPlugin)
        chain.resolve.alias.set('zlib', 'browserify-zlib')
      },

**Comment by Mihai-github** [comment]
Hi,

     I'm having this issue and cannot make this work... everything I try does nothing just downgrading the react-scripts to version 4.

ERROR:

```
Failed to compile.

Module not found: Error: Can't resolve 'http' in '/Users/admin/Work/reflex-test/node_modules/@isi/reflex/dist/esm'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
assets by path static/ 3.53 MiB
  asset static/js/bundle.js 3.52 MiB [emitted] (name: main) 1 related asset
  asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.93 KiB [emitted] 1 related asset
  asset static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg 2.57 KiB [emitted] (auxiliary name: main)
asset index.html 1.67 KiB [emitted]
asset asset-manifest.json 546 bytes [emitted]
cached modules 3.32 MiB (javascript) 31.4 KiB (runtime) [cached] 170 modules

ERROR in ./node_modules/@isi/reflex/dist/esm/index.js 5:0-21
Module not found: Error: Can't resolve 'http' in '/Users/admin/Work/reflex-test/node_modules/@isi/reflex/dist/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
 @ ./src/App.js 6:0-33
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/@isi/reflex/dist/esm/index.js 6:0-22
Module not found: Error: Can't resolve 'https' in '/Users/admin/Work/reflex-test/node_modules/@isi/reflex/dist/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }
 @ ./src/App.js 6:0-33
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/@isi/reflex/dist/esm/index.js 8:0-23
Module not found: Error: Can't resolve 'stream' in '/Users/admin/Work/reflex-test/node_modules/@isi/reflex/dist/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./src/App.js 6:0-33
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/@isi/reflex/dist/esm/index.js 10:0-21
Module not found: Error: Can't resolve 'zlib' in '/Users/admin/Work/reflex-test/node_modules/@isi/reflex/dist/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
        - install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "zlib": false }
 @ ./src/App.js 6:0-33
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/@isi/reflex/dist/esm/index.js 11:0-32
Module not found: Error: Can't resolve 'assets/scss/index.scss' in '/Users/admin/Work/reflex-test/node_modules/@isi/reflex/dist/esm'
 @ ./src/App.js 6:0-33
 @ ./src/index.js 7:0-24 11:33-36


```

**Comment by andorsk** [comment]
This worked like a charm! Thanks for the suggestion. 

> @hawkeye64 thx, that helped, finally got it compiling. FOr those who have a similar problem, I had to extend the chainWebPack in quasar.conf.js like this:
> 
> ```
>   chainWebpack (chain) {
>     // this is in order to support the not-updated version of ccxt:
>     // also needs: 
>     //    yarn add --dev node-polyfill-webpack-plugin browserify-zlib
>     const nodePolyfillWebpackPlugin = require('node-polyfill-webpack-plugin')
>     chain.plugin('node-polyfill').use(nodePolyfillWebpackPlugin)
>     chain.resolve.alias.set('zlib', 'browserify-zlib')
>   },
> ```
