### ISSUE TITLE
useFormChild ignores given validate method and uses vm.validate()

### ISSUE THREAD

**Issue by freakzlike** [quasarframework/quasar#9789]
**Describe the bug**
When using the `useFormChild` composable, then it is required to return the `validate` in the `setup` method. Otherwise the form submit will throw a TypeError. In addition if the `validate` method of the component is not the same as the method passed to `useFormChild`, it will call the `validate` from the component instance.

```
Uncaught TypeError: comp.validate is not a function
    at validate (QForm.js?0378:43)
    at submit (QForm.js?0378:114)
```

**Codepen/jsFiddle/Codesandbox (required)**
[Codepen example](https://codepen.io/freakzlike/pen/ExWqYaq)

**To Reproduce**
1. Open the [Codepen example](https://codepen.io/freakzlike/pen/ExWqYaq)
2. Click on 'Submit'
3. It should display 'Called from vm' in the output

You can also rename the `validate` in line 18 to test the `TypeError`.

**Expected behavior**
* It should display 'Called from useFormChild' instead of 'Called from vm'
* It should not throw an error when `validate` has not been returned in the `setup`

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.19
@quasar/app Version: -

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04
Node: v14.16.0
NPM: v7.18.1
Browsers: Chrome v91.0

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fix will be available in Quasar v2.0.1.
One comment though: it's not required to return the "validate" method in setup().
