### ISSUE TITLE
[bug] ios - modal - floating label - text align

### ISSUE THREAD

**Issue by SeregPie** [quasarframework/quasar#979]
IOS v 0.14.4

Open the [play app with modals](http://quasar-framework.org/quasar-play/apple/index.html#/showcase/popups/dialog).
Click on the menu item "Textfields".
Float labels are aligned in center and not on the left side, which looks horrible.

**Comment by rstoenescu** [comment]
Fix available in edge and future v0.14.5. Thanks for reporting!
