### ISSUE TITLE
[Feature Request] provide tag property in QTab API like in QItem API

### ISSUE THREAD

**Issue by drahkrub** [quasarframework/quasar#9793]
Problem: I would like to realize a horizontal menu with QTabs API. It's a mix of vue-router links and external links so I would like to mix QRouteTab and QTab - unfortunately QTab does not provide external links like QItem.

Solution: Provide tag property in QTab API like in QItem API e.g.
```
<q-tab label="Quasar v1" tag="a" target="_blank" href="https://v1.quasar.dev/" />
```

Alternative: I've tried several things. Among others surrounding q-tab with `<a>`-tag e.g. the clumsy
```
<a target="_blank" href="https://v1.quasar.dev/" style="text-decoration: none; color: inherit"><q-tab label="Quasar v1" /></a>
```
Looks ok at first glance but visual feedback is broken when switching the tab with TAB key.

**Comment by hawkeye64** [comment]
@drahkrub Why not use the slot of the QTab to put in a QBtn?  I think that will give you what you want.

**Comment by drahkrub** [comment]
@hawkeye64 Thanks for your answer and sorry for my late reaction!

I've tried
```
<q-tabs>
    <q-route-tab no-caps label="Page 1" to="/demo/links/page/1" />
    <!-- <a target="_blank" href="https://v1.quasar.dev/" style="text-decoration: none; color: inherit" tabindex="-1"><q-tab no-caps label="https://v1.quasar.dev/" /></a> -->
    <!-- above my try, below your suggestion -->
    <q-tab tabindex="-1"><q-btn no-caps flat type="a" target="_blank" href="https://v1.quasar.dev/" label="https://v1.quasar.dev/" /></q-tab>
    <q-route-tab no-caps label="Page 2" to="/demo/links/page/2" />
</q-tabs>
```
which gives me the following - screenshot taken when hovering the QBtn inside the QTab:
![image](https://user-images.githubusercontent.com/1061679/124635205-73390500-de87-11eb-90bd-92e269d0fdd5.png)

Is there a simple way to let QBtn fill out the QTab area?

But switching the tabs with the TAB key now works (thanks to `<q-tab tabindex="-1">`)!

Anyway, a tag property in the QTab API (like in QItem API) would be simpler... ;-)

**Comment by hawkeye64** [comment]
> Anyway, a tag property in the QTab API (like in QItem API) would be simpler... ;-)

I agree.

Try just using QBtn, without the parent QTab. I see I had to do something similar with using QBtnDropdown.

**Comment by pdanpdan** [comment]
Make a codepen so we can play with it.

**Comment by hawkeye64** [comment]
I made a codepen to play with that has QBtn and QBtnDropdown: https://codepen.io/Hawkeye64/pen/qBmZoVJ?editors=1010

Right away there is a couple of issues for consistency. The buttons don't have the same "equal width" of the tabs. The QBtn has some margin going on so it doesn't touch the top and bottom.

I am thinking, like QField for form items, a QTabWrapper would be nice, such that it can wrap something and make it somewhat behave like a QTab (the same width, underline selection, the same opacity, etc)

**Comment by pdanpdan** [comment]
You need to apply a `q-tab` class on the button: https://codepen.io/pdanpdan/pen/qBmZJLP?editors=1010

**Comment by hawkeye64** [comment]
Brilliant! Thanks, @pdanpdan :heart:
