### ISSUE TITLE
Dynamic import component

### ISSUE THREAD

**Issue by fredericoregateiro** [quasarframework/quasar#9796]
**Describe the bug**
Using a component that have been imported like:
`MyComponent: () => import('src/components/mycomponent.vue')`

gives the warning
`
[Vue warn]: Invalid VNode type: undefined (undefined) 
  at <MyComponent> 
  at <QPage class="flex flex-center" > 
  at <PageIndex onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <QPageContainer> 
  at <QLayout view="lHh Lpr lFf" > 
  at <MainLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
`

and the component is not displayed

https://github.com/fredericoregateiro/quasarTests

**To Reproduce**
1. install dependencies
2. quasar dev
3. the component is not rendered

**Expected behavior**
Show the component

**Platform (please complete the following information):**
Quasar Version: 1.2.1
@quasar/app Version: 2.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: win 10
Node: v14.15.5
NPM: 6.14.11
Yarn: 1.22.10
Browsers: edge
iOS:
Android:
Electron:

**Comment by freakzlike** [comment]
You are using Vue.js 3 and the lazy import for components has been changed. It is now required to use `defineAsyncComputed` for this.

```js
import { defineComponent, defineAsyncComponent } from 'vue'

export default defineComponent({
  name: 'PageIndex',
  components: {
    MyComponent: defineAsyncComponent(() => import('src/components/mycomponent.vue'))
  }
})
```
See [Migration of Async Components](https://v3.vuejs.org/guide/migration/async-components.html#overview).

**Comment by pdanpdan** [comment]
Nice way to confuse anyone: use qv2 but mention qv1
`Quasar Version: 1.2.1`

**Comment by fredericoregateiro** [comment]
@fprijate  thanks a lot,
The `defineAsyncComponent` work, but i was following this guide:
https://quasar.dev/quasar-cli/lazy-loading#lazy-load-components

Missing here is a mention to the `defineAsyncComponent`

> Nice way to confuse anyone: use qv2 but mention qv1
> `Quasar Version: 1.2.1`

@pdanpdan  my bad, copy paste done wrong 😄

**Comment by freakzlike** [comment]
It has already been fixed a couple of hours ago. See https://github.com/quasarframework/quasar/pull/9753
