### ISSUE TITLE
[Request] svg support in icon props

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#980]
Maybe it would be nice to have [this](https://materialdesignicons.com/) supported in Quasar as well?

I tried using [this](https://www.npmjs.com/package/vue-material-design-icons) within Quasar, but then the styling is off from the 'normal' quasar icons, and you would also have different html tags for the mdi icons.

**Comment by BrianMoreno1994** [comment]
Would love to see these implemented. 👍

**Comment by RyanHendricks** [comment]
Hi all, I am pretty sure that if you include [quasar-extras](https://github.com/quasarframework/quasar-extras) as a dependency you will be able to use the Material Design Icons. I am not sure, however, if this package is compatible with the latest updates although I imagine that it is. Hope this helps.

**Comment by rstoenescu** [comment]
MDI support was added in quasar-extras v1.0.0 (just released). Can be used in Quasar v0.14 too.

**Comment by ekoeryanto** [comment]
Halo, is the svg icon already supported or just MDI ?
