### ISSUE TITLE
Routing fails after crashing with "Scheduler Flush"

### ISSUE THREAD

**Issue by tampler** [quasarframework/quasar#9801]
**Describe the bug**
Previously was opened in the VueJS-Next repo [here](https://github.com/vuejs/vue-next/issues/4002), but was forwarded back to Quasar Community

When I switch two pages back and forth multiple times in the example project, routing stops working and stucks to one page with the following error:

```bash
Many errors occur, which eventually block Router navigation and Refreshing with F5 is required to get things back to work.
Router error: [Vue Router warn]: uncaught error during route navigation:
TypeError: _ctx.status is undefined
```

**Codepen/jsFiddle/Codesandbox (required)**
Minimal [project](https://github.com/Anadyne/vue-router-bug-report)

**To Reproduce**

1.   Checkout the project
2.   Install the Quasar CLI
3.   Run with: quasar dev
4.  When the browser opens automatically, open console (F12)
5.  Push buttons "Foo" and "Bar" back and forth. You'll see the errors and warnings in console

**Expected behavior**
Navigation between pages should work smoothly

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 2.0.0 / 3.0.0

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04.2
Node: 14.17.1
NPM: 7.17.0
Yarn: 1.22.10
Browsers: Chromium, Firefox
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Took a look at your project. By the looks of it, the problem really does not have anything to do with Quasar...
Also, tried running your reproduction repo project but had to solve a few build errors first and ended up not being able to reproduce the issue :(

Please try to get back to the vue-router team. If you could create them a minimal reproduction repo with no frameworks, just vue + vue-router and two native `<button>` which do a $router.push(...) it might be easier for them to look at the repo.

Sorry I could not help more.
