### ISSUE TITLE
release-notes sidebar title repeat.

### ISSUE THREAD

**Issue by zta7** [quasarframework/quasar#9803]
### To reproduct:
1. turn into https://quasar.dev/start/release-notes
2. click tree node 'Playground' just above 'Release-notes'
3. turn back to tree node 'Release-notes'
4. change 'Quasar' tag to '@Quasar/CLI' or '@Quasar/ICONGENIE' or '@Quasar'

### Something like that: 
![image](https://user-images.githubusercontent.com/30122066/123397362-ea8fae80-d5d4-11eb-802a-f0369321e46e.png)

**Comment by rstoenescu** [comment]
Cannot reproduce.
Is anyone else able to reproduce this?

**Comment by hawkeye64** [comment]
I can easily reproduce this.
PR here: https://github.com/quasarframework/quasar/pull/9809

**Comment by hawkeye64** [comment]
The easiest to see is icongenie as it has less releases

**Comment by rstoenescu** [comment]
Fix will be available on next docs deployment.
