### ISSUE TITLE
@quasar/qactivity is not compatible with app v3

### ISSUE THREAD

**Issue by har1s1m** [quasarframework/quasar#9820]
I just upgraded to the latest app v3 and found that the activity extension does not work. there is an error while trying to quasar dev. is there any workaround for how the extension can be upgraded?

P.S. @quasar/qribbon is also not working with v3.

**Comment by har1s1m** [comment]
Oh, my bad, I believe it is the wrong place to mention about extensions

**Comment by hawkeye64** [comment]
It's on the list to be done
