### ISSUE TITLE
@quasar/app v3 - node UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by har1s1m** [quasarframework/quasar#9821]
**Describe the bug**
Upgrade to quasar v3 and node to LTS 14.17.1 give me an error "(node:61979) UnhandledPromiseRejectionWarning: Unhandled promise rejection"

- index.js:63 mergeWithOptions
    [treeme]/[webpack-merge]/dist/index.js:63:19

  - index.js:52 merge
    [treeme]/[webpack-merge]/dist/index.js:52:35

  - quasar-conf-file.js:392 QuasarConfFile.compile
    [treeme]/[@quasar]/app/lib/quasar-conf-file.js:392:29

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - quasar-inspect:91 async inspect
    [treeme]/[@quasar]/app/bin/quasar-inspect:91:3

(Use `node --trace-warnings ...` to show where the warning was created)
(node:64263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:64263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**
in project folder -> quasar dev

**Expected behavior**
project should start. what node version is better to use? what can be done to eliminate such error? 

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
3.0.0

Quasar mode:
  - [v] SPA
  
Tested on:
  - [v] SPA

OS:Darwin(19.6.0) - darwin/x64
Node:14.17.1
NPM:6.14.13
Browsers:chrome

**Comment by hawkeye64** [comment]
@har1s1m Post your quasar.conf.js, package.json, and `quasar info`

**Comment by har1s1m** [comment]
@hawkeye64 they are

config

`/*
 * This file runs in a Node context (it's NOT transpiled by Babel), so use only
 * the ES6 features that are supported by your Node version. https://node.green/
 */

// Configuration for your app
// https://quasar.dev/quasar-cli/quasar-conf-js
/* eslint-env node */

module.exports = function(/* ctx */) {
  return {
    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    // https://quasar.dev/quasar-cli/cli-documentation/boot-files
    boot: [
      'i18n',
      'axios',
      'firebase',
      'croppa',
      'imgcompressor',
      'vue-gallery',
      'vue-awesome-swiper',
      'storefrontui',
      'toast-ui',
      'vuex-map-fields',
      'parseserver',
      'graphql',
      'watermark'
    ],
`
    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-css
    css: ['app.scss'],

    // https://github.com/quasarframework/quasar/tree/dev/extras
    extras: [
      // 'ionicons-v4',
      // 'mdi-v5',
      // 'fontawesome-v5',
      // 'eva-icons',
      // 'themify',
      // 'line-awesome',
      // 'roboto-font-latin-ext', // this or either 'roboto-font', NEVER both!

      'roboto-font', // optional, you are not bound to it
      'material-icons' // optional, you are not bound to it
    ],

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-framework
    framework: {
      iconSet: 'material-icons', // Quasar icon set
      // lang: 'en-us', // Quasar language pack
      lang: 'ru', // Quasar language pack

      // Possible values for "all":
      // * 'auto' - Auto-import needed Quasar components & directives
      //            (slightly higher compile time; next to minimum bundle size; most convenient)
      // * false  - Manually specify what to import
      //            (fastest compile time; minimum bundle size; most tedious)
      // * true   - Import everything from Quasar
      //            (not treeshaking Quasar; biggest bundle size; convenient)
      importStrategy: 'auto',

      components: [
        'QHeader',
        'QFooter',
        'QTabs',
        'QTab',
        'QRouteTab',
        'QList',
        'QItem',
        'QItemSection',
        'QItemLabel',
        'QCheckbox',
        'QIcon',
        'QDialog',
        'QInput',
        'QDate',
        'QTime',
        'QForm',
        'QBanner',
        'QSelect',
        'QScrollArea',
        'QTabPanels',
        'QTabPanel',
        'QSpinner',
        'QImg',
        'QRange',
        'QCheckbox',
        'QChip',
        'QTable',
        'QTh',
        'QTr',
        'QTd',
        'QRating'
      ],
      directives: ['ClosePopup', 'TouchHold'],

      // Quasar plugins
      plugins: ['LocalStorage', 'Dialog', 'Loading', 'Notify', 'SessionStorage']
      
    },
    

    // no need in quasar v2
    // https://quasar.dev/quasar-cli/cli-documentation/supporting-ie
    // supportIE: false,

    // https://quasar.dev/quasar-cli/cli-documentation/supporting-ts
    supportTS: false,

    // https://quasar.dev/quasar-cli/cli-documentation/prefetch-feature
    // preFetch: true

    // Full list of options: https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build
    build: {
      // vueRouterMode: 'hash', // available values: 'hash', 'history'
      vueRouterMode: 'history', // available values: 'hash', 'history'

      // rtl: false, // https://quasar.dev/options/rtl-support
      // preloadChunks: true,
      // showProgress: false,
      // gzip: true,
      // analyze: true,

      // Options below are automatically set depending on the env, set them if you want to override
      // extractCSS: false,

      // https://quasar.dev/quasar-cli/cli-documentation/handling-webpack
      extendWebpack(cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/,
          options: {
            formatter: require('eslint').CLIEngine.getFormatter('stylish')
          }
        });
      }
    },

    // Full list of options: https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-devServer
    devServer: {
      https: false,
      port: 8080,
      open: 'Google Chrome' // opens browser window automatically

      // open: true // opens browser window automatically
      // open: 'Chrome'
      // open: {
      //   app: ['Chrome', '--incognito']
      // }
    },

    // animations: 'all', // --- includes all animations
    // https://quasar.dev/options/animations
    animations: 'all',

    // https://quasar.dev/quasar-cli/developing-ssr/configuring-ssr
    ssr: {
      pwa: false
    },

    // https://quasar.dev/quasar-cli/developing-pwa/configuring-pwa
    pwa: {
      workboxPluginMode: 'GenerateSW', // 'GenerateSW' or 'InjectManifest'
      workboxOptions: {}, // only for GenerateSW
      manifest: {
        name: 'treeme web portal',
        short_name: 'treeme web portal',
        description: 'one place to find your pack ',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#027be3',
        icons: [
          {
            src: 'icons/icon-128x128.png',
            sizes: '128x128',
            type: 'image/png'
          },
          {
            src: 'icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: 'icons/icon-256x256.png',
            sizes: '256x256',
            type: 'image/png'
          },
          {
            src: 'icons/icon-384x384.png',
            sizes: '384x384',
            type: 'image/png'
          },
          {
            src: 'icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      }
    },

    // Full list of options: https://quasar.dev/quasar-cli/developing-cordova-apps/configuring-cordova
    cordova: {
      // noIosLegacyBuildFlag: true, // uncomment only if you know what you are doing
      id: 'com.asiagatc.app'
    },

    // Full list of options: https://quasar.dev/quasar-cli/developing-capacitor-apps/configuring-capacitor
    capacitor: {
      hideSplashscreen: true
    },

    // Full list of options: https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron
    electron: {
      bundler: 'packager', // 'packager' or 'builder'

      packager: {
        // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options
        // OS X / Mac App Store
        // appBundleId: '',
        // appCategoryType: '',
        // osxSign: '',
        // protocol: 'myapp://path',
        // Windows only
        // win32metadata: { ... }
      },

      builder: {
        // https://www.electron.build/configuration/configuration

        appId: 'treeme'
      },

      // More info: https://quasar.dev/quasar-cli/developing-electron-apps/node-integration
      nodeIntegration: true,

      extendWebpack(/* cfg */) {
        // do something with Electron main process Webpack cfg
        // chainWebpack also available besides this extendWebpack
      }
    }
  };
};`


package
`{
  "name": "treeme",
  "version": "0.0.1",
  "description": "one place to find your pack ",
  "productName": "treeme web portal",
  "author": "we are treeme",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore ./",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@growthbunker/vuetimeline": "^0.1.16",
    "@quasar/extras": "^1.10.7",
    "@storefront-ui/vue": "^0.8.1",
    "@toast-ui/vue-editor": "^2.5.2",
    "apollo-boost": "^0.4.9",
    "axios": "^0.21.1",
    "compressorjs": "^1.0.7",
    "core-js": "^3.15.1",
    "escape-html": "^1.0.3",
    "firebase": "^8.6.8",
    "firebase-admin": "^9.10.0",
    "firebase-functions": "^3.14.1",
    "firebaseui": "^4.8.0",
    "flatted": "^3.1.1",
    "graphql": "^15.5.1",
    "mapbox-gl": "^1.13.1",
    "parse": "^2.19.0",
    "quasar": "^1.15.21",
    "rough-notation": "^0.3.3",
    "sanitize-html": "^2.4.0",
    "swiper": "^6.7.1",
    "uuid": "^8.3.2",
    "vue-apollo": "^3.0.7",
    "vue-awesome-swiper": "^4.1.1",
    "vue-croppa": "^1.3.8",
    "vue-gallery": "^2.0.1",
    "vue-i18n": "^8.24.5",
    "vue-kinesis": "^1.3.3",
    "vue-pipeline": "^1.0.8",
    "vue-rough-notation": "^0.1.10",
    "vuex-map-fields": "^1.4.1",
    "vuex-persistedstate": "^3.2.0",
    "watermarkjs": "^2.1.1"
  },
  "devDependencies": {
    "@quasar/app": "^3.0.0",
    "babel-eslint": "^10.0.1",
    "cypress": "^6.9.1",
    "cypress-file-upload": "^4.1.1",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-vue": "^6.1.2"
  },
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "resolutions": {}
}`

info
`
Operating System - Darwin(19.6.0) - darwin/x64
NodeJs - 14.17.1

Global packages
  NPM - 6.14.13
  yarn - Not installed
  @quasar/cli - 1.0.7
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 1.15.21 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.0.0 -- Quasar Framework local CLI
  @quasar/extras - 1.10.7 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - Not installed
  vue-router - 4.0.9 -- > This is the repository for Vue Router 4 (for Vue 3)
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.14.6 -- Babel compiler core.
  webpack - 5.40.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.0.0-beta.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
`

**Comment by rstoenescu** [comment]
You are wrongly using Quasar v1 ("quasar" package 1.x) with the Quasar App CLI for Quasar v2 ("@quasar/app" v3.x).
Change the version of "@quasar/app" to "^2.0.0".
