### ISSUE TITLE
Quasar V2 - watchOptions not a valid webpack property under devServer

### ISSUE THREAD

**Issue by trentmurray** [quasarframework/quasar#9825]
**Describe the bug**

When using Quasar V2 "quasar dev" command, the "watchOptions" property under "devServer" is no longer accepted, and prevents the application from being built.

```
App • Chaining "UI" Webpack config
(node:34) UnhandledPromiseRejectionWarning:   ValidationError: Invalid configuration object. Object has been initialized usi  ng a configuration object that does not match the API schema.
   - configuration has an unknown property 'watchOptions'. These properties are   valid:
     object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?,   historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMi  ddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, publi  c?, setupExitSignals?, static?, transportMode?, watchFiles? }
  
  - validate.js:104 validate
    [app]/[webpack-dev-server]/[schema-utils]/dist/validate.js:104:11
  
  - Server.js:43 new Server
    [app]/[webpack-dev-server]/lib/Server.js:43:5
  
  - dev-server-regular.js:46 
    [app]/[@quasar]/app/lib/dev-server-regular.js:46:21
  
  - new Promise
  
  - dev-server-regular.js:19 DevServer.listen
    [app]/[@quasar]/app/lib/dev-server-regular.js:19:12
  
  - quasar-dev:281 runMain
    [app]/[@quasar]/app/bin/quasar-dev:281:24
  
  - task_queues.js:95 processTicksAndRejections
    internal/process/task_queues.js:95:5
  
```

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/modest-monad-rbfne

**To Reproduce**
1. Add the following property as a sub-property of "devServer"

```
    watchOptions: {
      poll: 1000,
    },
```

**Expected behavior**

Webpack should compile, and HMR should work with docker containers.

**Platform (please complete the following information):**
Quasar Version: 2.0.0
@quasar/app Version: 3.0.0

Quasar mode:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOs 11.4
Node: 14.17

**Comment by rstoenescu** [comment]
Like mentioned in docs, Quasar v2 uses Webpack 5 with its new [webpack-dev-server](https://github.com/webpack/webpack-dev-server). The new webpack-dev-server has changed its props, one of which being the removal of `watchOptions`.

Please update to the specs of webpack-dev-server v4.x. The current options have not been published to the official webpack documentation website, but you can take a look at them [here](https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json).

References:
* https://quasar.dev/start/upgrade-guide#webpack-devserver
* https://quasar.dev/quasar-cli/quasar-conf-js#property-devserver (more detailed)
* devServer options: https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json

**Comment by rstoenescu** [comment]
If there is an issue with devServer options, please report to their repository (https://github.com/webpack/webpack-dev-server/issues)

**Comment by Karnith** [comment]
see this post to fix file watching for quasar v2 in docker https://github.com/quasarframework/quasar/issues/9838#issuecomment-975367150
