### ISSUE TITLE
devServer no longer has watchOptions property

### ISSUE THREAD

**Issue by trentmurray** [quasarframework/quasar#9838]
The V2 documentation still references watchOptions for the docker HMR issue.

![image](https://user-images.githubusercontent.com/25923294/123579683-b659ff00-d81b-11eb-855e-8c4fbb11514d.png)

This is no longer valid and won't work in Q2.

**Comment by hawkeye64** [comment]
@trentmurray Check out Razvan's answer here: https://github.com/quasarframework/quasar/issues/9825#issuecomment-869148464

In the future, please search for similar before creating a duplicate ticket. Thanks.

**Comment by trentmurray** [comment]
@hawkeye64  - this is a doc bug. I understand the other issue - but the docs are wrong... This does NOT work for Quasar V2, yet it is in the documentation. 

I opened this ticket after my actual bug ticket was closed (palmed off to webpack) because using the docs doesn't work and it shouldn't be in there.

**Comment by rstoenescu** [comment]
Adding one more place in docs that needs updating: https://quasar.dev/app-extensions/development-guide/introduction#install-and-prompts-scripts

Can someone help with a PR for docs pls?

**Comment by trentmurray** [comment]
> https://quasar.dev/app-extensions/development-guide/introduction#install-and-prompts-scripts

Happy to help, just don't know how. Point me to the repo/location and I'll make the PR

**Comment by Karnith** [comment]
watchOptions is still available, just not on devserver. If you're using docker dev containers add the following to your quasar.config.js
```js
extendWebpack(cfg) {
  cfg.watchOptions = {
    aggregateTimeout: 200,
    poll: 1000,
  };
},
```
this will set the watcher to polling and make quasar v2 webpack file watcher functional in docker containers.

**Comment by NewtonMan** [comment]
Improve the [above reply](https://github.com/quasarframework/quasar/issues/9838#issuecomment-975367150), paste the code inside the "build" part as:
```js
    build: {
      vueRouterMode: 'hash', // available values: 'hash', 'history'

      // transpile: false,
      // publicPath: '/',

      // Add dependencies for transpiling with Babel (Array of string/regex)
      // (from node_modules, which are by default not transpiled).
      // Applies only if "transpile" is set to true.
      // transpileDependencies: [],

      // rtl: true, // https://quasar.dev/options/rtl-support
      // preloadChunks: true,
      // showProgress: false,
      // gzip: true,
      // analyze: true,

      // Options below are automatically set depending on the env, set them if you want to override
      // extractCSS: false,

      // https://v2.quasar.dev/quasar-cli-webpack/handling-webpack
      // "chain" is a webpack-chain object https://github.com/neutrinojs/webpack-chain
      
      extendWebpack(cfg) {
        cfg.watchOptions = {
          aggregateTimeout: 200,
          poll: 1000,
        };
      },
        
      chainWebpack (chain) {
        chain.plugin('eslint-webpack-plugin')
          .use(ESLintPlugin, [{ extensions: [ 'js', 'vue' ] }])
      }
      
    },
```
