### ISSUE TITLE
Cannot Build or Run app after update

### ISSUE THREAD

**Issue by afnan** [quasarframework/quasar#9846]
Updated the cli and now this happens when building or quasar dev

```
`(node:16052) UnhandledPromiseRejectionWarning:   TypeError: Merging undefined is not supported

  - index.js:63 mergeWithOptions
    [admin]/[webpack-merge]/dist/index.js:63:19

  - index.js:52 merge
    [admin]/[webpack-merge]/dist/index.js:52:35

  - quasar-conf-file.js:392 QuasarConfFile.compile
    [admin]/[@quasar]/app/lib/quasar-conf-file.js:392:29

  - task_queues.js:95 processTicksAndRejections
    internal/process/task_queues.js:95:5

  - quasar-build:179 async build
    [admin]/[@quasar]/app/bin/quasar-build:179:3


(Use `node --trace-warnings ...` to show where the warning was created)
(node:16052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

```
**downgraded and it works fine**

**Comment by rstoenescu** [comment]
Please post your quasar.conf.js

**Comment by afnan** [comment]
> Please post your quasar.conf.js

This is after downgrading. Not sure if there is any sensitive information there. 

`/*
 * This file runs in a Node context (it's NOT transpiled by Babel), so use only
 * the ES6 features that are supported by your Node version. https://node.green/
 */

// Configuration for your app
// https://quasar.dev/quasar-cli/quasar-conf-js
/* eslint-env node */

module.exports = function ( ctx ) {
  return {
    // https://quasar.dev/quasar-cli/supporting-ts
    supportTS: false,

    // https://quasar.dev/quasar-cli/prefetch-feature
    // preFetch: true,

    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    // https://quasar.dev/quasar-cli/boot-files
    boot: [

      'axios',
    ],

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-css
    css: [
      'app.sass'
    ],

    // https://github.com/quasarframework/quasar/tree/dev/extras
    extras: [
      // 'ionicons-v4',
      // 'mdi-v5',
      'fontawesome-v5',
      // 'eva-icons',
      // 'themify',
      // 'line-awesome',
      // 'roboto-font-latin-ext', // this or either 'roboto-font', NEVER both!

      'roboto-font', // optional, you are not bound to it
      'material-icons', // optional, you are not bound to it
    ],

    // Full list of options: https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build
    build: {
      vueRouterMode: 'history', // available values: 'hash', 'history'
      env: ctx.dev
        ? { // so on dev we'll have
          API: 'http://fje.localhost',
        }
        : { // and on build (production):
          API: 'https://api.coobabanana.com/'
          
        },
      // transpile: false,

      // Add dependencies for transpiling with Babel (Array of string/regex)
      // (from node_modules, which are by default not transpiled).
      // Applies only if "transpile" is set to true.
      // transpileDependencies: [],

      // rtl: false, // https://quasar.dev/options/rtl-support
      // preloadChunks: true,
      // showProgress: false,
      // gzip: true,
      // analyze: true,

      // Options below are automatically set depending on the env, set them if you want to override
      // extractCSS: false,

      // https://quasar.dev/quasar-cli/handling-webpack
      extendWebpack(cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/
        })
      },
    },

    // Full list of options: https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-devServer
    devServer: {
      https: false,
      port: 8080,
      open: true // opens browser window automatically
    },

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-framework
    framework: {
      iconSet: 'material-icons', // Quasar icon set
      lang: 'en-us', // Quasar language pack
      config: {},

      // Possible values for "importStrategy":
      // * 'auto' - (DEFAULT) Auto-import needed Quasar components & directives
      // * 'all'  - Manually specify what to import
      importStrategy: 'auto',

      // For special cases outside of where "auto" importStrategy can have an impact
      // (like functional components as one of the examples),
      // you can manually specify Quasar components/directives to be available everywhere:
      //
      // components: [],
      // directives: [],

      // Quasar plugins
      plugins: ['Notify','Dialog']
    },

    // animations: 'all', // --- includes all animations
    // https://quasar.dev/options/animations
    animations: 'all',

    // https://quasar.dev/quasar-cli/developing-ssr/configuring-ssr
    ssr: {
      pwa: false
    },

    // https://quasar.dev/quasar-cli/developing-pwa/configuring-pwa
    pwa: {
      workboxPluginMode: 'GenerateSW', // 'GenerateSW' or 'InjectManifest'
      workboxOptions: {}, // only for GenerateSW
      manifest: {
        name: `The Wellbeing Food Co`,
        short_name: `The Wellbeing Food Co`,
        description: `A product by AllSpice Technologies`,
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#027be3',
        icons: [
          {
            src: 'icons/icon-128x128.png',
            sizes: '128x128',
            type: 'image/png'
          },
          {
            src: 'icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: 'icons/icon-256x256.png',
            sizes: '256x256',
            type: 'image/png'
          },
          {
            src: 'icons/icon-384x384.png',
            sizes: '384x384',
            type: 'image/png'
          },
          {
            src: 'icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      }
    },

    // Full list of options: https://quasar.dev/quasar-cli/developing-cordova-apps/configuring-cordova
    cordova: {
      // noIosLegacyBuildFlag: true, // uncomment only if you know what you are doing
    },

    // Full list of options: https://quasar.dev/quasar-cli/developing-capacitor-apps/configuring-capacitor
    capacitor: {
      hideSplashscreen: true
    },

    // Full list of options: https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron
    electron: {
      bundler: 'packager', // 'packager' or 'builder'

      packager: {
        // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options

        // OS X / Mac App Store
        // appBundleId: '',
        // appCategoryType: '',
        // osxSign: '',
        // protocol: 'myapp://path',

        // Windows only
        // win32metadata: { ... }
      },

      builder: {
        // https://www.electron.build/configuration/configuration

        appId: 'figjam_express_admin'
      },

      // More info: https://quasar.dev/quasar-cli/developing-electron-apps/node-integration
      nodeIntegration: true,

      extendWebpack(/* cfg */) {
        // do something with Electron main process Webpack cfg
        // chainWebpack also available besides this extendWebpack
      }
    }
  }
}
`

**Comment by hawkeye64** [comment]
@afnan The default is now Quasar v2. I suspect you inadvertently upgraded to v2 and are still on a v1 project.

**Comment by afnan** [comment]
> @afnan The default is now Quasar v2. I suspect you inadvertently upgraded to v2 and are still on a v1 project.

I just ran `npm outdated `and checked packages and then ran `npm update`. After downgrading it worked fine. There were no major updates and definitely not V2 i am still working in V1

**Comment by hawkeye64** [comment]
Also, quasar/app is now at v3, for quasar v2.

Since the downgrade worked for you, I am closing this ticket.

**Comment by afnan** [comment]
Well in the future I can't upgrade to any releases? I reported the bug to
see if there is a fix and the upgrade.i did not upgrade to V3. just to
ask,you say quasar is on V3 now, does this mean previous is discontinued?

**Comment by hawkeye64** [comment]
> just to ask, you say quasar is on V3 now, does this mean previous is discontinued?
@quasar/app is on v3 and quasar is on v2

Quasar v1 will be supported until the end of April 2022, I believe

**Comment by rstoenescu** [comment]
Quasar v1 -> "quasar" v1.x; "@quasar/app" v2.x
Quasar v2 -> "quasar" v2.x; "@quasar/app" v3.x

"@quasar/app" has its own versioning. You can safely upgrade your packages as long as you don't jump the major versions. Like if you are on Quasar v1, don't jump to "quasar" v2.x or "@quasar/app" v3.x.
