### ISSUE TITLE
qtable No data available

### ISSUE THREAD

**Issue by gishys** [quasarframework/quasar#9853]
1.vue  create projectname
2.vue add quasar
3.modify HelloWorld.vue file：
![图片](https://user-images.githubusercontent.com/64127578/123750721-837e3c80-d8e9-11eb-9087-bc124667cebc.png)
4.show No data available.
![图片](https://user-images.githubusercontent.com/64127578/123750236-ed4a1680-d8e8-11eb-9d7f-84e56d19738b.png)
5.package.json
{
  "name": "hx-manager",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "core-js": "^3.6.5",
    "ipaddr": "^0.1.0",
    "quasar": "^2.0.0",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "1.32.12",
    "sass-loader": "^10.1.0",
    "vue-cli-plugin-quasar": "~4.0.1"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by MilosPaunovic** [comment]
Hello @gishys,

In Quasar 2, `data` prop is changed to `rows`, as can be seen [here](https://quasar.dev/vue-components/table#basic-usage).
