### ISSUE TITLE
innerFieldProps method in QSelect.js is not returning correct object

### ISSUE THREAD

**Issue by dinesh-chander** [quasarframework/quasar#9858]
**Describe the bug**
`innerFieldProps` method in QSelect.js is returning an empty object and not assigning the props fields to acc object.

https://github.com/quasarframework/quasar/blob/abd23719832f09f53d9a24471b9cdb770f10c7b4/ui/src/components/select/QSelect.js#L207

**Platform (please complete the following information):**
Quasar Version: 2.0.1

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting! Fix will be available in Quasar v2.0.3.
