### ISSUE TITLE
Q-menu seems to do some "pre-rendering" even when it is not displayed

### ISSUE THREAD

**Issue by CamilleDrapier** [quasarframework/quasar#9859]
**Describe the bug**
If a q-menu is used in a huge list, and the q-menu's content depends on some reactive property, and these reactive properties are updated, then this will cause a spike in the resources used; potentially freezing the whole application for a while.

**Codepen/jsFiddle/Codesandbox (required)**
[Codepen](https://codepen.io/CamilleDrapier/pen/RwVwPZa)

**To Reproduce**
1. Open the codepend here-above
2. Open the web console of your browser
3. No log entry should be there (unless the menu's content is effectively displayed on the screen)

**Expected behavior**
When a q-menu does not display its content, that content should not be "reactive"/updated when some underlying reactive property is updated. In other words, I would like it to behave more or less as if there was a `<template v-if="model">` surrounding the menu's content.

Alternatively, if this is an expected behavior, should there be a warning in the documentation saying that adding reactive code in the menu content might have some performance impact?

**Platform (please complete the following information):**
Quasar Version: v1.15.20
@quasar/app Version: 2.2.10

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu
Node: v16.3.0
NPM: 7.15.1
Browsers: Firefox

**Comment by pdanpdan** [comment]
Hello.

Vue (at least v2) does not process the content of a component exactly the same as a default slot.

If you want to avoid any problem you should always wrap your content with `<template #default>` if you want to avoid problems with rendering.

https://codepen.io/pdanpdan/pen/YzVPZLO

**Comment by pdanpdan** [comment]
ref https://github.com/vuejs/vue/issues/12157
