### ISSUE TITLE
QSelect is not honoring borderless attribute if used inside QInput

### ISSUE THREAD

**Issue by dinesh-chander** [quasarframework/quasar#9863]
**Describe the bug**
QSelect is not honoring borderless prop if used inside QInput

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dinesh-chander/pen/jOmOjGX?editors=1010

**Expected behavior**
QSelect should not have any borders with borderless prop.

**Platform (please complete the following information):**
Quasar Version: v2.0.1
@quasar/app Version: v3.0.1

Quasar mode:
  - [X] SSR
 
Tested on:
  - [X] SSR

**Comment by metalsadman** [comment]
@dinesh-chander you can't combine both as they both inherit QField, see warning https://quasar.dev/vue-components/field#introduction. just use https://quasar.dev/vue-components/menu#introduction if your use case require you to have a dropdown in an input slot. example https://codepen.io/metalsadman/pen/JjNoWyr?editors=1010

**Comment by pdanpdan** [comment]
You can take a look here: https://github.com/quasarframework/quasar/issues/7516

**Comment by dinesh-chander** [comment]
> @dinesh-chander you can't combine both as they both inherit QField, see warning https://quasar.dev/vue-components/field#introduction. just use https://quasar.dev/vue-components/menu#introduction if your use case require you to have a dropdown in an input slot. example https://codepen.io/metalsadman/pen/JjNoWyr?editors=1010

Makes sense,  thank you.
