### ISSUE TITLE
QTh component no longer propagates @click event

### ISSUE THREAD

**Issue by Dylancyclone** [quasarframework/quasar#9864]
**Describe the bug**
The `@click` handler is not called when clicking on a QTh component

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dylancyclone/pen/LYyEYEV

**To Reproduce**
1. Create a `QTh` component
2. Add a valid `@click` handler
3. Click the `QTh` component
4. Notice the click handler is not called

**Expected behavior**
The click handler should be called when the component is clicked like the `QTd` component, and as it did in Quasar v1 (example: https://codepen.io/dylancyclone/pen/ZEKYEEV)

**Platform (please complete the following information):**
Quasar Version: v2.0.1
@quasar/app Version: v3.0.1

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.04
Node: v12.22.1
Yarn: v1.22.10
Browsers: Chromium, Firefox

**Additional context**
Looking at the code, it appears the component only emits the click event if it's props say the column it's attached to is sortable https://github.com/quasarframework/quasar/blob/3e61e24d175b1ce073bbdfc21e1107a869dcd8fc/ui/src/components/table/QTh.js#L62-L67

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting!
Fix will be available in Quasar v2.0.3.
