### ISSUE TITLE
humanStorageSize formatting needs an update

### ISSUE THREAD

**Issue by HerHde** [quasarframework/quasar#9868]
**Describe the bug**
The function [`humanStorageSize()`](https://github.com/quasarframework/quasar/blob/3e61e24d175b1ce073bbdfc21e1107a869dcd8fc/ui/src/utils/format.js#L3) should include a space between the value and the unit, as it is [documented](https://quasar.dev/quasar-utils/formatter-utils#format-to-human-readable-size) and should be ([see rule #15](https://physics.nist.gov/cuu/Units/checklist.html)).

While on it, I would update the units to the IEC style or whatever *KiB* is called, to provide clarity.

Finally, I would update the documentation to show only one decimal, as it is implemented (`12.8` instead of `12.78`).

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/nmf0o6cz/1/

**To Reproduce**
Use `humanStorageSize()`

**Expected behavior**
The output should be something like `12.8 MiB` or `12.8 MB` instead of `12.8MB`

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: `3.0.0-beta.1`

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting. Fixed the docs. Like explained in your PR (thanks for it btw!), the current humanStorageSize() behaviour is the desired one. We want to avoid some special cases (in QUploader) where the space char can break text into multiple lines (without using any CSS for this, in order for the framework not to interfere with any possible devland css).
