### ISSUE TITLE
Documentation Issue in some of the components (QAvatar, QCard, etc.)

### ISSUE THREAD

**Issue by mayank091193** [quasarframework/quasar#9878]
It looks like something(Most probably CSS) has gone wrong on the "QAvatar" documentation page. Everything looks messy.

Please see the screenshot for more detail.

![Screenshot from 2021-06-30 17-56-45](https://user-images.githubusercontent.com/27857088/123960684-36739680-d9cd-11eb-8b65-bbd506b21d09.png)

![Screenshot from 2021-06-30 18-04-04](https://user-images.githubusercontent.com/27857088/123961049-95d1a680-d9cd-11eb-9ad9-b65858d66e5c.png)

Affected links:

- https://quasar.dev/vue-components/avatar
- https://quasar.dev/vue-components/card
- https://quasar.dev/vue-components/chip

It looks like this issue is happening with the components which contain images. The above are a few of them. I believe this has affected more component documentations.

**Comment by MilosPaunovic** [comment]
@mayank091193 Seems quite fine here. Could you try to clear browser cache and try again?

**Comment by mayank091193** [comment]
Hey, I tried in incognito mode and cleared the website's cache and the same issue is happening. Though, I tried on a different laptop, and seems to be working fine on it. Must be some kind of a caching issue on my laptop. Maybe I need to clear the whole cache.

Thanks
