### ISSUE TITLE
q-scroll-area component triggering about:blank in horizontal mode

### ISSUE THREAD

**Issue by FocussedFlyer3** [quasarframework/quasar#9891]
**Describe the bug**
Cordova IOS opens about:blank when using q-scroll-area component in horizontal mode.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/VgQbdx) or a jsFiddle (https://jsfiddle.net/rstoenescu/rmaodk0f) or a Codesandbox (https://codesandbox.io/s/github/quasarframework/quasar-codesandbox) and hit save then copy-paste link here.

https://codepen.io/FocussedFlyer3/pen/gOWpYYJ

**To Reproduce**
1. With the component in the page, just refresh and check the web inspector network tab, there should be ``about:blank`` appearing.

**Expected behavior**
Expected ``about:blank`` not to be triggered by component.

**Screenshots**
<img width="1027" alt="Screenshot 2021-07-01 at 2 26 40 PM" src="https://user-images.githubusercontent.com/36317458/124076119-69bf2f80-da78-11eb-9418-fb1b377ae6f7.png">

**Platform (please complete the following information):**
Quasar Version: 1.15.21
@quasar/app Version: 1.9.6

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [X] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [X] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:  macOS High Sierra 10.13.6 (17G65)
Node: v12
NPM: 7.5.4
Yarn: 1.22.4
Browsers: 
iOS: 14.5
Android:
Electron:

**Additional context**
cordova - 10.0.0

I did tried on the browser too and it does happens. You may check in the codepen with web inspector tool.

**Comment by rstoenescu** [comment]
For older webviews that do not support ResizeObserver yet we use a trick with an iframe (which points to "about:blank" which doesn't breaks anything). No other way around it. But main point is that it doesn't breaks anything.
