### ISSUE TITLE
Draggable/Droppable/Resizable/Selectable/Sortable

### ISSUE THREAD

**Issue by CookieJon** [quasarframework/quasar#99]
Many libraries do some of these things, but I've not found one that does them all or does them well without jQuery or some other animation plugin.

Could be a nice set of behaviours to separate Quasar even further from the rest of the herd?

**Comment by rstoenescu** [comment]
Seems like a good idea. Will think about this. Thanks for taking an interest in making Quasar even better!

**Comment by smolinari** [comment]
+1 👍 

Scott

**Comment by mariaczi** [comment]
Would be really useful !

**Comment by rstoenescu** [comment]
There are some Vue packages out there which deal with this (vue-dragula comes to mind first in no particular order), so sorry but unfortunately I decided not to pursue this one. Maybe in the future it will be on the roadmap, but currently this would be like a big project of its own which requires extensive man-power hours to build and maintain.

**Comment by smolinari** [comment]
Interesting. This is basically a necessity in a modern "admin" area of an application. I guess it will need to be attacked, once someone needs such backend control. 😉 

Scott

**Comment by murbanowicz** [comment]
Statement about it is still the same @rstoenescu or maybe changed?

**Comment by rstoenescu** [comment]
@murbanowicz Yes, definitely. There are Vue packages that can deal with this separately. No need for Quasar to reinvent the wheel as it doesn't add up any specific benefit.

**Comment by smolinari** [comment]
Could this be one of those "community driven" components, which could be added to a "community components" repo?

Scott

**Comment by rstoenescu** [comment]
@smolinari Yes. Will add the "community driven" components to the roadmap. There's a lot to talk about on this subject. Will comment at the right time.
