### ISSUE TITLE
[BEX] index.html not found after quasar build

### ISSUE THREAD

**Issue by ManUtopiK** [quasarframework/quasar#9908]
**Describe the bug**
Everything works well in dev mode, but after building the extension index.html is not found.

**To Reproduce**
1. Create a BEX app with `quasar create mybex` with Vuex, Axios, Vue-i18n
2. Add BEX mode with `quasar mode add bex`
3. Run dev mode with `quasar dev -m bex`. Works as expected.
4. Build the BEX with `quasar build -m bex`
5. Test built extension by loading unpackaged extension `dist/bex/UnPackaged`
6. Extension is loaded by google Chrome
7. Open extension with a click in the icon : ERR_FILE_NOT_FOUND
 
Or

5\. Test built extension by loading extension `dist/bx/Packaged/chrome/mybex.zip` with drag and drop in `chrome://extensions`
6\. Extension is loaded by google Chrome
7\. Open extension with a click in the icon : ERR_FILE_NOT_FOUND

**Expected behavior**
Open the page of the extension.
I also tried with popup and options. Same behavior.

After digging into `dist/bex/UpnPackaged` folder, I suppose the file index.html should be inside the www folder and not at the root folder. Like in `src-bex/www/index.html`.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: v3.0.1

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [x] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [x] BEX

OS: Mac
Node: v14.17.1
Yarn: latest
Browsers: google Chrome

**Comment by rstoenescu** [comment]
Fix will be available in q/app v3.1.7

**Comment by mbilalbakhtawar** [comment]
Yes facing same issue.  If you paste **index.html** inside **www**, it starts working fine.

![image](https://user-images.githubusercontent.com/34718017/143251298-f44087d3-2a61-4d24-80fc-108b38bb2dc5.png)
