### ISSUE TITLE
[Request] Button group

### ISSUE THREAD

**Issue by Iworb** [quasarframework/quasar#991]
How about button grouping?
This functionality well presented in Bootstrap, Semantic UI and many others frameworks, but I didn't find it here.
FAB is looks similar, but not exactly. This thing is usefull for making toolbars, etc.

**Comment by rstoenescu** [comment]
Already done for future v0.15.

**Comment by Iworb** [comment]
It so mysterious v0.15 with everything included :anguished:
But instead of UMD I don't want to use dev version, so waiting for release.
Well done! :+1:

**Comment by rstoenescu** [comment]
http://forum.quasar-framework.org/topic/815/quasar-v0-15-roadmap

**Comment by rstoenescu** [comment]
Will close this as its already done for future v0.15
