### ISSUE TITLE
Slide-item without action

### ISSUE THREAD

**Issue by reitbauer** [quasarframework/quasar#9914]
I use slide items without an action.
On mobile devices it's not possible to scroll up and down if I touch on an slide item without action.

**To Reproduce**
1. Create a long list with slide items without actions
2. Try to scroll on an mobile device or in browser (in mobile view)

**Expected behavior**
It should be possible to scroll

**Platform:**
Quasar Version: 2.0.1
@quasar/app Version: 3.0.1

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: macOS Big Sir
Node: v14.17.0
NPM: 7.19.1
Browsers: Safari, Google Chrome
iOS: 14

**Update**
CodePen: https://codepen.io/reitbauer/pen/rNmVZBB
<img width="560" alt="image" src="https://user-images.githubusercontent.com/31218726/124242842-79448400-db1d-11eb-9ec2-01deba652331.png">

Scroll on the slide items just work with mouse wheel

**Comment by pdanpdan** [comment]
Please add a codepen

**Comment by reitbauer** [comment]
> Please add a codepen

is added

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.3
