### ISSUE TITLE
Strange selection behavior on iOS.

### ISSUE THREAD

**Issue by theZaX** [quasarframework/quasar#9937]
**Describe the bug**
Typically when you press and hold on some text on iOS the selection controls appear and you simply tap on any part outside of the selection to cancel.

**To Reproduce**
1. Go to 'quasar.dev' on an iPhone
2. Try to select some text 
3. Try to cancel the selection by tapping

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [x] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS: yes
Android:
Electron:

**Comment by theZaX** [comment]
It actually seems to work on quasar sites, its the PWA mode where it has the issue. Double tapping seems to do the same thing as tapping off should do so it may be a click listener or something like that.

**Comment by rstoenescu** [comment]
This is a decision taken by Apple for the PWA webview. There is no way around it unless (high overview of an idea) you manually add a preventDefault() call somewhere along the "click" (or "touchstart") probably attached to document body -- but this might break other browser stuff.
