### ISSUE TITLE
`quasar create project` error: node-waf: command not found (due to zlib dependency)

### ISSUE THREAD

**Issue by Richie765** [quasarframework/quasar#9942]
**Describe the bug**
In specific setup (npm @7 with verdaccio) `quasar create project` gives error: node-waf: command not found (zlib).

**To Reproduce**
1. Use verdaccio
2. Use npm@7
3. quasar create project
4. choose npm

**Expected behavior**
Create project without error

**Screenshots**
```
npm ERR! code 127
npm ERR! path /Users/richard/tmp/project/node_modules/zlib
npm ERR! command failed
npm ERR! command sh -c node-waf clean || true; node-waf configure build
npm ERR! sh: node-waf: command not found
npm ERR! sh: node-waf: command not found
```

**Platform (please complete the following information):**
Quasar Version: 2.0.1
@quasar/app Version: 3.0.1

Quasar mode:
  - [X] SPA

OS: Linux, macOS
Node: v16.4.1
NPM: 7.19.1
Yarn: 1.22.10

**Additional context**
The problem only occurs when:
* npm @7
* Verdaccio

When I use npm @6 or bypass Verdaccio (rename .npmrc) it works fine. It also works when I use Yarn but I rather stick with npm. For now I'm going back to npm @6.

Question: Does Quasar really need zlib at all? Everywhere I look it tells it is old and integrated into Node. Could this dependency be removed? That should solve the issue.

Further reference: https://github.com/verdaccio/verdaccio/discussions/2316

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v3.0.2
