### ISSUE TITLE
[Question] How to connect Keycloak-js correctly with Quasar?

### ISSUE THREAD

**Issue by Excel1** [quasarframework/quasar#9950]
I tried to using Keycloak-js with Quasar (Quasar CLI) to perform web-authentication and getting the token for the webservices. 

At first i tried it with using https://www.npmjs.com/package/keycloak-js and with using https://github.com/dsb-norge/vue-keycloak-js. 

Additionally i used the tutorial from https://blog.icod.de/2021/02/25/keycloak-js-client-with-quasar/ to get it work but it seems Quasar have a problem with "Vue" cause by using the following code in boot as keycloak.js i got "[Quasar] boot error: TypeError: Vue is undefined"

```
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'
import axios from 'axios'

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export default async ({ Vue, router, store, app }) => {
  // eslint-disable-next-line @typescript-eslint/require-await
  async function tokenInterceptor () {
    axios.interceptors.request.use(config => {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access,@typescript-eslint/restrict-template-expressions
      config.headers.Authorization = `Bearer ${Vue.prototype.$keycloak.token}`
      return config
    }, error => {
      return Promise.reject(error)
    })
  }

  return new Promise(resolve => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-member-access
    Vue.use(VueKeyCloak, {
      init: {
        onLoad: 'login-required', // or 'check-sso'
        flow: 'standard',
        pkceMethod: 'S256',
        silentCheckSsoRedirectUri: window.location.origin + '/silent-check-sso.html',
        checkLoginIframe: false // otherwise it would reload the window every so seconds
      },
      config: {
        url: 'url',
        realm: 'realm',
        clientId: 'clientId'
      },
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      onReady: (keycloak) => {
        void tokenInterceptor()
        resolve()
      }
    })
  })
}
```

I was also reading https://github.com/quasarframework/quasar/issues/4758 and tried it to use but this didnt seem to work for me with the quasar cli. Also the token refresh didnt work and is missing in the named blogpost tutorial.

https://medium.com/keycloak/secure-vue-js-app-with-keycloak-94814181e344 There was also a tutorial for vue in general but this wont also work for the quasar cli. 

So how to connect Keycloak-js correctly with Quasar? And make it sense to write a  quasar-cli plugin  to connect keycloak with quasar?

**Comment by metalsadman** [comment]
Please use github discussions for questions or post this in our discord.

**Comment by yusufkandemir** [comment]
The need for `eslint-disable-next-line` should be enough to get suspicious. You didn't provide much info, but I can say that you are using Quasar v2. In Vue 3, global API has been changed, so you need to follow this instead: https://github.com/dsb-norge/vue-keycloak-js#vue-3, instead of `createApp(App)`, you would use the `app` parameter, in general, you can just replace `Vue` with `app` in your code.
