### ISSUE TITLE
 css style lost (error) in signed apk , 

### ISSUE THREAD

**Issue by thinkido** [quasarframework/quasar#9958]
**Describe the bug**
error info in video

**To Reproduce**
1.  android stutdio -> build -> signed apk -> debug 
2.  run app
3.  See error

**Screenshots**
video link
[quasar2 css error in signed apk](https://reccloud.cn/u/7zr9vgf)

![image](https://user-images.githubusercontent.com/5847958/124467566-95b91880-ddca-11eb-94a7-c0dfa0c7ffeb.png)

**Platform (please complete the following information):**
Quasar Version: v2.0.1
@quasar/app Version:  v3.0.1

Quasar mode:
  - [x] Capacitor

Tested on:
  - [x] Capacitor

OS:
Node: v12.22.2 
NPM: 7.16.0

**Comment by rstoenescu** [comment]
Hi,

What I gather from the video that you've sent is that you've definitely mixed dev and prod builds. You should not need to manually configure the address in the capacitor config.

1. Dev build (`quasar dev -m capacitor -T [ios|android]`) creates a native app which redirects to the local IP address and port that the Quasar devserver uses. Production build (`quasar build -m capacitor -T [ios|android]`) on the other hand fills the /src-capacitor/www folder with the actual web assets.
2. Do NOT run `quasar dev` and `quasar build` in parallel (or multiple `quasar dev` in parallel!) as this will mix the builds and create a mess!
3. Run `quasar dev` (and do NOT kill the webserver) while playing with the dev build. When you want the production build, kill any other `quasar dev` command that is running THEN run `quasar build.....`
