### ISSUE TITLE
[Request] Scroll to DOM element util

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#996]
Like good old jQuery smooth scrolling!

A quasar UTIL to (smooth) scroll to a DOM element.

**Comment by alexandesigner** [comment]
Maybe adapt this existing plugin [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) on a Quasar component `<q-scroll-virtual  />` or `<q-scroll-smooth />`

**Comment by rstoenescu** [comment]
It was already in Quasar, just not exposed to the public API. scroll -> animScrollTo.
Available now in edge and future v0.14.7

**Comment by musicformellons** [comment]
What is the difference between new animScrollTo and old [setScrollPosition](http://quasar-framework.org/components/scrolling-utils.html)?

**Comment by musicformellons** [comment]
Looked in to code. Looks like setScrollPosition with a third (duration) argument is identical to animScrollTo.

**Comment by mesqueeb** [comment]
@rstoenescu 
I was wondering if we should add a section on `animScrollTo` in the docs.

Because before you mentioned `animScrollTo` is **"not exposed to the public API"** I had created a section in the docs on "[how to manually scroll to an element](https://quasar-framework.org/components/scrolling-utils.html#Scrolling-to-an-element)".

But should I change this section with a section on how to use `animScrollTo`?
