### ISSUE TITLE
routing error Quasar v2

### ISSUE THREAD

**Issue by ibrahim-developper** [quasarframework/quasar#9970]
in android chrome or samsung browser when i use q-route-tab to navigate to new page in the first time it 's work correctly example from "/" -> to "/camera" using **to** attribute  but when i click to return to the home page the link change but the page not change i try to use this.$route.push and remove to attribute from q-route-tab but give me is not a function ( i use the methods property not the setup )

**Comment by Smrtnyk** [comment]
You litterally gave almost 0 information here
At least the code that you are using would be helpful

**Comment by ibrahim-developper** [comment]
> You litterally gave almost 0 information here
> At least the code that you are using would be helpful

**Comment by ibrahim-developper** [comment]
in chrome or IE on pc work normal but on android browser chrome/samsung make this problem 

**this in mobile browser when first time open the web go to the default view and when click to camera button in footer go to camera page** 


<img src="https://user-images.githubusercontent.com/52491316/124548779-da7a9900-de36-11eb-9c37-15afa178cf5d.jpg" width=50% height=50%>


**the below photo when i click to the camera button in the footer it work and go to camera page** 

<img src="https://user-images.githubusercontent.com/52491316/124548887-0bf36480-de37-11eb-99a7-04cb7df7fab3.jpg" width=50% height=50%>

**but in this below photo when the view in the camera page and i want go to home page if i click back or in the home button in the footer  the link change but the page still in camera view** 

<img src="https://user-images.githubusercontent.com/52491316/124549085-54ab1d80-de37-11eb-88f5-96e62cd913be.jpg" width=50% height=50%>





**routes.js** 

const routes = [
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', component: () => import('src/pages/PageHome.vue') },
      {
        path: '/camera',
         component: () => import('src/pages/PageCamera.vue')
      },
    ]
  },
  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/Error404.vue')
  }
]

export default routes


**footer** 

      <q-footer elevated class="bg-white small-screen-only" bordered>
          <q-tabs class="text-grey-10" active-color="red" indicator-color="primary">
            
            <q-route-tab @click="routerMethod('home')" name="home" icon="eva-home-outline" label="Home" />
            <q-route-tab @click="routerMethod('camera')" name="camera" icon="eva-camera-outline" label="Camera" />
          </q-tabs>
      </q-footer>

**im try the **to** attribute in the q-route-tab ( to="/" in the home button and  to="/camera" in the camera button )  but also same problem** 


in the methods properties

  methods:{
    routerMethod(mybutton){
    
      if(mybutton == 'home'){

        this.$router.push('/')
      }else{
        this.$router.push('/camera')
      }
    }
  }

and the same problem with this way

**Comment by MilosPaunovic** [comment]
Hello @ibrahim-developper,
 
Why don't you try to utilise `QRouteTab` `to` prop, something similar to this:

```js
<q-route-tab to="/camera" name="camera" icon="eva-camera-outline" label="Camera" />
```

**Comment by ibrahim-developper** [comment]
i'm try this but the same only on mobile this problem

**Comment by ibrahim-developper** [comment]
> Hello @ibrahim-developper,
> 
> Why don't you try to utilise `QRouteTab` `to` prop, something similar to this:
> 
> ```js
> <q-route-tab to="/camera" name="camera" icon="eva-camera-outline" label="Camera" />
> ```

i'm try this but the same problem (only on mobile this problem)

**Comment by MilosPaunovic** [comment]
Does the browser console give any error?

**Comment by ibrahim-developper** [comment]
> Does the browser console give any error?

no error 


<img src="https://user-images.githubusercontent.com/52491316/124555101-5d075680-de3f-11eb-955e-78aa0c3c71de.png" width=50% height=50%>




<img src="https://user-images.githubusercontent.com/52491316/124555172-71e3ea00-de3f-11eb-9972-d3193e35516f.png" width=50% height=50%>

**Comment by ibrahim-developper** [comment]
> > Does the browser console give any error?
> 
> no error
> 
> <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/52491316/124555101-5d075680-de3f-11eb-955e-78aa0c3c71de.png">
> 
> <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/52491316/124555172-71e3ea00-de3f-11eb-9972-d3193e35516f.png">

this warning i remove attr to (the footer work normal now on pc)

**Comment by MilosPaunovic** [comment]
Okay, so, `to` attribute is required if you are using `QRouteTab`. Wha you could try is name your routes:
```js
{ path: '', name: 'Home', component: () => import('src/pages/PageHome.vue') }
```
And after, in component, do this:
```js
<q-route-tab :to="{ name: 'Home' }" name="camera" icon="eva-camera-outline" label="Camera" />
```

**Comment by ibrahim-developper** [comment]
> Okay, so, `to` attribute is required if you are using `QRouteTab`. Wha you could try is name your routes:
> 
> ```js
> { path: '', name: 'Home', component: () => import('src/pages/PageHome.vue') }
> ```
> 
> And after, in component, do this:
> 
> ```js
> <q-route-tab :to="{ name: 'Home' }" name="camera" icon="eva-camera-outline" label="Camera" />
> ```

the same but it give me an error on console

<img src="https://user-images.githubusercontent.com/52491316/124556333-d784a600-de40-11eb-9b97-60c513d1d1c4.png" width=70% height=70%>

**Comment by ibrahim-developper** [comment]
> > Okay, so, `to` attribute is required if you are using `QRouteTab`. Wha you could try is name your routes:
> > ```js
> > { path: '', name: 'Home', component: () => import('src/pages/PageHome.vue') }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And after, in component, do this:
> > ```js
> > <q-route-tab :to="{ name: 'Home' }" name="camera" icon="eva-camera-outline" label="Camera" />
> > ```
> 
> the same but it give me an error on console
> 
> <img alt="" width="70%" height="70%" src="https://user-images.githubusercontent.com/52491316/124556333-d784a600-de40-11eb-9b97-60c513d1d1c4.png">

**routes.js**

  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '',name:'Home', component: () => import('src/pages/PageHome.vue') },
      {
        path: '/camera',
        name:'Camera',
         component: () => import('src/pages/PageCamera.vue')

      },
    ]
  },
  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/Error404.vue')
  }
]


**footer**

      <q-footer elevated class="bg-white small-screen-only" bordered>
          <q-tabs class="text-grey-10" active-color="red" indicator-color="primary">
            
            <q-route-tab :to="{name: 'Home'}" name="home" icon="eva-home-outline" label="Home" />
            <q-route-tab :to="{name: 'Camera'}" name="camera" icon="eva-camera-outline" label="Camera" />
          </q-tabs>
      </q-footer>

**Comment by ibrahim-developper** [comment]
and on samsung browser i don't know why the card and the photos like that 

<img src="https://user-images.githubusercontent.com/52491316/124557791-8fff1980-de42-11eb-866c-70a8d00a040e.jpg" width=50% height=50%>

**Comment by ibrahim-developper** [comment]
> Okay, so, `to` attribute is required if you are using `QRouteTab`. Wha you could try is name your routes:
> 
> ```js
> { path: '', name: 'Home', component: () => import('src/pages/PageHome.vue') }
> ```
> 
> And after, in component, do this:
> 
> ```js
> <q-route-tab :to="{ name: 'Home' }" name="camera" icon="eva-camera-outline" label="Camera" />
> ```

i remove all thing and try this way now it is working 
Thank you a lot ❤️❤️
