### ISSUE TITLE
Quasar dev server errors on paths with "." character

### ISSUE THREAD

**Issue by wreality** [quasarframework/quasar#9971]
**Describe the bug**
This appears to be an issue with how the express server for the quasar dev command proxies URLs.  If an "." character is present in the URL path, express responds with. for example, `Cannot GET /admin/us.ers`.  Serving the built SPA directly sends the request correctly through to the router as expected.

Discovered by creating paths like `/admin/users/:email`.

**To Reproduce**
1. Spin up a quasar dev server
2. Attempt to go to an URL with a period (doesn't matter if it exists in the app.. the app will never see it) such as `http://localhost:8080/my.site`
3. See error `Cannot GET /my.site`

**Expected behavior**
The dev server should proxy the request to the app.

**Platform (please complete the following information):**
Quasar Version: 2.0.0
@quasar/app Version: 3.0.0

Also present in:
Quasar Version: 1.15.15
@quasar/app version: 2.2.6

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows
Node: 12.22.1
NPM:
Yarn: 1.22.10

**Comment by pdanpdan** [comment]
https://stackoverflow.com/a/66439150
https://stackoverflow.com/a/38576357
https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback
https://joshtronic.com/2020/07/26/allow-dots-in-paths-with-webpack-dev-server/

**Comment by wreality** [comment]
Thanks so much. I searched my tail off and didn't come across those. I was sure this was my fault and it turns out it was. 

Appreciate the help.

**Comment by pdanpdan** [comment]
Not really your fault but more of a funky decision from dev server.
I know there was a reason for that, but I can't find it now.
