### ISSUE TITLE
Expanded FAB inside Expanded FAB

### ISSUE THREAD

**Issue by PickleNik** [quasarframework/quasar#9973]
**Describe the bug**
Expanded FAB breaks inside another Expanded FAB

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/PickleNik/pen/vYmLWgo?editors=101

**To Reproduce**
1. Click the FAB
2. See broken FAB inside :(

**Expected behavior**
FAB Expands and collapses as usual, inside a persistent FAB

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version: 3

Quasar mode:
  - [x] SPA
  - [x] SSR
  - [x] PWA
  - [x] Electron
  - [x] Cordova
  - [x] Capacitor
  - [x] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Operating System - Linux(5.8.0-59-generic) - linux/x64
NodeJs - 14.17.2

Global packages
  NPM - 7.16.0
  yarn - 1.22.10
  @quasar/cli - 1.2.1
  @quasar/icongenie - Not installed
  cordova - Not installed

**Comment by rstoenescu** [comment]
Improvement will be available in Quasar v2.0.3 and v1.15.23.
