### ISSUE TITLE
TouchPan.js breaks the scroll & spams the console

### ISSUE THREAD

**Issue by PickleNik** [quasarframework/quasar#9975]
**Describe the bug**
With a list of q-slide-items, it's not scrollable via touch, even when not using up&down slots, TouchPan takes over when trying to scroll

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/PickleNik/pen/BaRjJRJ?editors=1010

**To Reproduce**
1. Open console
2. Open a touch device emulator
3. Try to scroll
4. See spams to the console

**Expected behavior**
Scrolling & no spams

**Screenshots**
![touchStart](https://user-images.githubusercontent.com/31113245/124521793-d448d600-ddbe-11eb-957e-694e36775c2e.png)

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version: 3

Quasar mode:
  - [x] SPA
  - [?] SSR
  - [?] PWA
  - [?] Electron
  - [?] Cordova
  - [?] Capacitor
  - [?] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Operating System - Linux(5.8.0-59-generic) - linux/x64
NodeJs - 14.17.2

Global packages
  NPM - 7.16.0
  yarn - 1.22.10
  @quasar/cli - 1.2.1
  @quasar/icongenie - Not installed
  cordova - Not installed

**Additional context**
Sometimes scroll works, but only sometimes ¯\_(ツ)_/¯

**Comment by rstoenescu** [comment]
Fixed the leftover debug statement.
But cannot reproduce the "not scrollable issue" unless you provide more information.
