### ISSUE TITLE
the global provide is undefined by Dialog.create()

### ISSUE THREAD

**Issue by everyPassion** [quasarframework/quasar#9979]
**Describe the bug**

```
import DialogDetail from './dlg-detail.vue'
import { Dialog } from 'quasar'
Dialog.create({
  component: DialogDetail,
  componentProps: {
    maximized: true,
    transitionShow: 'fade',
    transitionHide: 'fade',
    vehicleId,
    from,
    to
  }
})
```

i can get the global provide in parentVue, When I use this method to create a dialog,
 i con't get  the global provider  in the DialogDetail component , 

**Expected behavior**
I can get global provide in dlg-detail.vue

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Please provide a forked https://codesandbox.quasar.dev with a minimal reproduction.
It's really hard to understand what you are actually doing otherwise. Thanks.
