### ISSUE TITLE
Side drawers "drag-to-open/close" inhibit nested touch behaviours

### ISSUE THREAD

**Issue by spectrolite** [quasarframework/quasar#998]
### Software version

Quasar: 0.14+
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Side drawers have by default a touch directive to open/close on drag, and that interferes with any component using drag nested inside of a drawer.
Currently there seems to be no way around this (that I know of). @rstoenescu Any ideas?
The same problem disallows the use of several quasar components, as well as any vue component that normally allows drag and drop, or any kind of sliding/panning behaviour.
See http://forum.quasar-framework.org/topic/975/slider-inside-right-menu for a typical example.

### What were you expecting?
The nested component should work as intended and not trigger a "close" on the drawer.

A quick workaround would be to allow disabling the drag to close behavior on side panels entirely, but a solution that correctly manages event bubbling would be best.

### What steps did you take, to get the error?
e.g. http://forum.quasar-framework.org/topic/975/slider-inside-right-menu

**Comment by rstoenescu** [comment]
Marked as "contributor-friendly" if anyone wants to take a shot at it.

**Comment by rstoenescu** [comment]
Currently fixed with "no-swipe-open" and "no-swipe-close" QLayoutDrawer props in v0.15, so closing this. This will get improved in the future, but the current schedule is too tight.
