### ISSUE TITLE
QCard issue in samsung browser

### ISSUE THREAD

**Issue by ibrahim-developper** [quasarframework/quasar#9980]
**Describe the bug**
When open the web using my phone on google chrome the card is showing normal but when open the web on samsung chrome the card view have some issue.

**Codepen/jsFiddle/Codesandbox (required)**

`<q-card class="q-ma-lg" flat bordered>
      <q-item>
        <q-item-section avatar>
          <q-avatar>
            the image
          </q-avatar>
        </q-item-section>

        <q-item-section>
          <q-item-label>Title</q-item-label>
          <q-item-label caption> Subhead </q-item-label>
        </q-item-section>
      </q-item>

      <q-separator />
      <q-card-section horizontal>
        <q-card-section> text </q-card-section>
        <q-separator vertical />

        <q-card-section class="col-4">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </q-card-section>
      </q-card-section>
    </q-card>`
this the same code from quasar.dev only i'm adding some margin 

**Screenshots**
<img src="https://user-images.githubusercontent.com/52491316/124565736-06077e80-de4b-11eb-8ce7-0148675dbadc.png" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/52491316/124565914-36e7b380-de4b-11eb-8c71-53e2e2700e4d.png" width=50% height=50%>

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [•] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [•] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: v14.15.4.
NPM: npm@6.14.10
Yarn:
Browsers: samsung internet Version 14.2.1.69
iOS:
Android: 9
Electron:

**Comment by hawkeye64** [comment]
![1625591309234798014805874339914](https://user-images.githubusercontent.com/10262924/124640412-9beed980-de4a-11eb-87e5-0cdfef2ed2d9.jpg)
![16255913630742913573946949768053](https://user-images.githubusercontent.com/10262924/124640463-ad37e600-de4a-11eb-8382-630af5533a0f.jpg)

**Comment by hawkeye64** [comment]
https://github.com/quasarframework/quasar/issues/9970#issuecomment-874518256

**Comment by Smrtnyk** [comment]
I don't think samsung browser is a worthy target to support, also in browsers field in package.json maybe you didn't specify correct browser targets to transpile your code or something

**Comment by Salt1024** [comment]
https://github.com/quasarframework/quasar/blob/ce20e29908db9f5f8b6cda3a1d8727a8f7e9943d/ui/src/components/avatar/QAvatar.sass#L16
https://www.caniuse.com/css-not-sel-list

use `&__content, img:not(.q-icon):not(.q-img__image)` may have better compatibility

**Comment by hawkeye64** [comment]
@rstoenescu @pdanpdan 

https://www.caniuse.com/?search=%3Anot

Both Samsung Internet and Opera Mobile do not support Selectors Level 4, but they do support Selectors Level 3. So, as @Salt1024 says using:
```js
&__content, img:not(.q-icon):not(.q-img__image)
```
will work for these browsers.

**Comment by pdanpdan** [comment]
Yes, can you please make a PR for it?

**Comment by hawkeye64** [comment]
done

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.0.2

**Comment by ibrahim-developper** [comment]
> https://github.com/quasarframework/quasar/blob/ce20e29908db9f5f8b6cda3a1d8727a8f7e9943d/ui/src/components/avatar/QAvatar.sass#L16
> 
> 
> https://www.caniuse.com/css-not-sel-list
> use `&__content, img:not(.q-icon):not(.q-img__image)` may have better compatibility

thank you a lot

**Comment by ibrahim-developper** [comment]
> @rstoenescu @pdanpdan
> 
> https://www.caniuse.com/?search=%3Anot
> 
> Both Samsung Internet and Opera Mobile do not support Selectors Level 4, but they do support Selectors Level 3. So, as @Salt1024 says using:
> 
> ```js
> &__content, img:not(.q-icon):not(.q-img__image)
> ```
> 
> will work for these browsers.

thank you a lot

**Comment by ibrahim-developper** [comment]
> @rstoenescu @pdanpdan
> 
> https://www.caniuse.com/?search=%3Anot
> 
> Both Samsung Internet and Opera Mobile do not support Selectors Level 4, but they do support Selectors Level 3. So, as @Salt1024 says using:
> 
> ```js
> &__content, img:not(.q-icon):not(.q-img__image)
> ```
> 
> will work for these browsers.

should put in the global style ?

**Comment by rstoenescu** [comment]
@ibrahim-developper wait for Quasar v2.0.2

**Comment by hawkeye64** [comment]
I am just confirming this now matches Samsung Internet Browser with what's displayed on a Chrome browser
