### ISSUE TITLE
possibly missing `setCssProperty` or docs issue

### ISSUE THREAD

**Issue by cmcleese** [quasarframework/quasar#9999]
**Describe the bug**
https://quasar.dev/style/color-palette#setting-up-defaults

In the boot file description section for setting up defaults there is mention of `setCssVar`.
Not sure if this is supposed to exist or just docs issue and meant to be `setCssVar` instead.
Regardless `setCssVar` doesn't exist and cannot be imported.

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/quasar-setcssproperty-hffcn?file=/src/App.vue

**To Reproduce**
1. Go to codesandbox link
2. Look at app.vue file
3. Notice terminal error output

**Expected behavior**
Should either exist or fixed in the docs.

**Platform (please complete the following information):**
Quasar Version: 2.0.1
@quasar/app Version: 3.0.1

Quasar mode:
  - [x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Fixed docs. It should indeed be `setCssVar` not `setCssProperty`.
